include::./index.adoc[]

[[v58-10-0]]
=== Hebreus, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-10-1]]

^<<v58-10-1,1>>^ A lei  dada por Moisés não é um modelo completo e fiel das coisas verdadeiras; é apenas uma sombra das coisas boas que estão para vir. Os mesmos sacrifícios  são oferecidos sempre, ano após ano. Portanto, como pode a lei, por meio desses sacrifícios, aperfeiçoar as pessoas que chegam perto de Deus?

[[v58-10-2]]

^<<v58-10-2,2>>^ Se as pessoas que adoram a Deus tivessem sido purificadas  dos seus pecados, não se sentiriam mais culpadas de nenhum pecado, e todos os sacrifícios terminariam.

[[v58-10-3]]

^<<v58-10-3,3>>^ Em vez disso esses sacrifícios, realizados ano após ano, servem para fazer com que as pessoas lembrem dos seus pecados.

[[v58-10-4]]

^<<v58-10-4,4>>^ Pois o sangue de touros e de bodes não pode, de modo nenhum, tirar os pecados de ninguém.

[[v58-10-5]]

^<<v58-10-5,5>>^ Por isso Cristo, ao entrar no mundo, disse: "Tu, ó Deus, não queres animais oferecidos em sacrifícios nem ofertas de cereais, mas preparaste um corpo para mim.

[[v58-10-6]]

^<<v58-10-6,6>>^ Não te agradam as ofertas de animais queimados inteiros no altar nem os sacrifícios oferecidos para tirar pecados.

[[v58-10-7]]

^<<v58-10-7,7>>^ Então eu disse: — Estou aqui, ó Deus; venho fazer a tua vontade, assim como está escrito a meu respeito no Livro da Lei ."

[[v58-10-8]]

^<<v58-10-8,8>>^ Primeiro ele disse: "Tu não queres sacrifícios ou ofertas de animais, e não te agradam as ofertas dos animais queimados inteiros no altar nem os sacrifícios oferecidos para tirar pecados." Ele disse isso embora todos os sacrifícios sejam oferecidos de acordo com a lei.

[[v58-10-9]]

^<<v58-10-9,9>>^ Depois ele disse: "Estou aqui, ó Deus, para fazer a tua vontade." Assim Deus acabou com todos os antigos sacrifícios e pôs no lugar deles o sacrifício de Cristo.

[[v58-10-10]]

^<<v58-10-10,10>>^ E, porque Jesus Cristo fez o que Deus quis, nós somos purificados do pecado pela oferta que ele fez, uma vez por todas, do seu próprio corpo.

[[v58-10-11]]

^<<v58-10-11,11>>^ Todo sacerdote judeu cumpre todos os dias os seus deveres religiosos e oferece muitas vezes os mesmos sacrifícios, mas estes nunca poderão tirar pecados.

[[v58-10-12]]

^<<v58-10-12,12>>^ Porém Jesus Cristo ofereceu só um sacrifício para tirar pecados, uma oferta que vale para sempre, e depois sentou-se do lado direito de Deus.

[[v58-10-13]]

^<<v58-10-13,13>>^ Ali Jesus está esperando até que Deus ponha os seus inimigos como estrado debaixo dos pés dele.

[[v58-10-14]]

^<<v58-10-14,14>>^ Assim, com um sacrifício só, ele aperfeiçoou para sempre os que são purificados do pecado.

[[v58-10-15]]

^<<v58-10-15,15>>^ E o Espírito Santo também nos dá o seu testemunho sobre isso. Primeiro ele diz:

[[v58-10-16]]

^<<v58-10-16,16>>^ "Quando esse tempo chegar, diz o Senhor, eu farei com o povo de Israel esta aliança : Porei as minhas leis no coração deles e na mente deles as escreverei."

[[v58-10-17]]

^<<v58-10-17,17>>^ Depois ele diz: "Não lembrarei mais dos seus pecados nem das suas maldades."

[[v58-10-18]]

^<<v58-10-18,18>>^ Assim, quando os pecados são perdoados, já não há mais necessidade de oferta para tirá-los.

[[v58-10-19]]

^<<v58-10-19,19>>^ Por isso, irmãos, por causa da morte de Jesus na cruz nós temos completa liberdade de entrar no Lugar Santíssimo .

[[v58-10-20]]

^<<v58-10-20,20>>^ Por meio da cortina, isto é, por meio do seu próprio corpo, ele nos abriu um caminho novo e vivo.

[[v58-10-21]]

^<<v58-10-21,21>>^ Nós temos um Grande Sacerdote  para dirigir a casa de Deus.

[[v58-10-22]]

^<<v58-10-22,22>>^ Portanto, cheguemos perto de Deus com um coração sincero e uma fé firme, com a consciência limpa das nossas culpas e com o corpo lavado com água pura.

[[v58-10-23]]

^<<v58-10-23,23>>^ Guardemos firmemente a esperança da fé que professamos, pois podemos confiar que Deus cumprirá as suas promessas.

[[v58-10-24]]

^<<v58-10-24,24>>^ Pensemos uns nos outros a fim de ajudarmos todos a terem mais amor e a fazerem o bem.

[[v58-10-25]]

^<<v58-10-25,25>>^ Não abandonemos, como alguns estão fazendo, o costume de assistir às nossas reuniões. Pelo contrário, animemos uns aos outros e ainda mais agora que vocês veem que o dia está chegando.

[[v58-10-26]]

^<<v58-10-26,26>>^ Pois, se continuarmos a pecar de propósito, depois de conhecer a verdade, já não há mais sacrifício  que possa tirar os nossos pecados.

[[v58-10-27]]

^<<v58-10-27,27>>^ Pelo contrário, resta apenas o medo do que acontecerá: medo do Julgamento e do fogo violento que destruirá os que são contra Deus.

[[v58-10-28]]

^<<v58-10-28,28>>^ Quem desobedece à lei  de Moisés é condenado sem dó à morte, se for julgado culpado depois de ouvido o testemunho de duas pessoas, pelo menos.

[[v58-10-29]]

^<<v58-10-29,29>>^ Então, o que será que vai acontecer com os que desprezam o Filho de Deus e consideram como coisa sem valor o sangue da aliança  de Deus, que os purificou ? E o que acontecerá com quem insulta o Espírito do Deus, que o ama? Imaginem como será pior ainda o castigo que essa pessoa vai merecer!

[[v58-10-30]]

^<<v58-10-30,30>>^ Pois sabemos quem foi que disse: "Eu me vingarei, eu acertarei contas com eles." E quem também disse: "O Senhor julgará o seu povo."

[[v58-10-31]]

^<<v58-10-31,31>>^ Que coisa terrível é cair nas mãos do Deus vivo!

[[v58-10-32]]

^<<v58-10-32,32>>^ Lembrem do que aconteceu no passado. Naqueles dias, depois que a luz de Deus os iluminou, vocês sofreram muitas coisas, mas não foram vencidos na luta.

[[v58-10-33]]

^<<v58-10-33,33>>^ Alguns foram insultados e maltratados publicamente, e em outras ocasiões vocês estavam prontos para tomar parte no sofrimento dos que foram tratados assim.

[[v58-10-34]]

^<<v58-10-34,34>>^ Vocês participaram do sofrimento dos prisioneiros. E, quando tudo o que vocês tinham foi tirado, vocês suportaram isso com alegria porque sabiam que possuíam uma coisa muito melhor, que dura para sempre.

[[v58-10-35]]

^<<v58-10-35,35>>^ Portanto, não percam a coragem, pois ela traz uma grande recompensa.

[[v58-10-36]]

^<<v58-10-36,36>>^ Vocês precisam ter paciência para poder fazer a vontade de Deus e receber o que ele promete.

[[v58-10-37]]

^<<v58-10-37,37>>^ Pois, como ele diz nas Escrituras Sagradas : "Um pouco mais de tempo, um pouco mesmo, e virá aquele que tem de vir; ele não vai demorar.

[[v58-10-38]]

^<<v58-10-38,38>>^ E todos aqueles que eu aceito terão fé em mim e viverão. Mas, se uma pessoa voltar atrás, eu não ficarei contente com ela."

[[v58-10-39]]

^<<v58-10-39,39>>^ Nós não somos gente que volta atrás e se perde. Pelo contrário, temos fé e somos salvos.

'''

xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[&#60; Capítulo Anterior] | <<v58-10-0,Topo>> | xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[Próximo Capítulo &#62;]