include::./index.adoc[]

[[v58-9-0]]
=== Hebreus, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-9-1]]

^<<v58-9-1,1>>^ A primeira aliança  tinha leis  sobre a adoração e tinha também um santuário construído por seres humanos, onde se adorava a Deus.

[[v58-9-2]]

^<<v58-9-2,2>>^ Foi armada uma Tenda , dividida em duas partes. Na parte da frente, chamada Lugar Santo , ficavam o candelabro  e a mesa com os pães oferecidos a Deus.

[[v58-9-3]]

^<<v58-9-3,3>>^ Atrás da segunda cortina ficava a parte que era chamada de Lugar Santíssimo .

[[v58-9-4]]

^<<v58-9-4,4>>^ Ali estava colocado o altar de ouro onde era queimado o incenso, e também estava colocada a arca da aliança , toda coberta de ouro. Dentro da arca estavam a vasilha de ouro com o maná , o bastão de Arão, do qual tinham saído brotos, e as duas placas de pedra com os mandamentos escritos nelas.

[[v58-9-5]]

^<<v58-9-5,5>>^ Em cima da arca, representando a Presença Divina, estavam os querubins , com as suas asas abertas sobre o lugar onde os pecados eram perdoados. Mas agora não é o momento de explicar os detalhes dessas coisas.

[[v58-9-6]]

^<<v58-9-6,6>>^ Depois de tudo isso ter sido preparado, os sacerdotes entram todos os dias na parte da frente da Tenda, que é o Lugar Santo, para cumprir os seus deveres religiosos.

[[v58-9-7]]

^<<v58-9-7,7>>^ Mas somente o Grande Sacerdote  entra na parte de trás, que é o Lugar Santíssimo, e isso apenas uma vez por ano. Ele oferece a Deus o sangue de animais, em favor de si mesmo e também pelos pecados que o povo cometeu sem saber que estava pecando.

[[v58-9-8]]

^<<v58-9-8,8>>^ Por meio disso tudo, o Espírito Santo nos ensina, de modo bem claro, que a entrada para o Lugar Santíssimo ainda não foi aberta enquanto a parte da frente, que é o Lugar Santo, continuar sendo usada.

[[v58-9-9]]

^<<v58-9-9,9>>^ Isso é um símbolo para hoje. Quer dizer que as ofertas e os sacrifícios  de animais oferecidos a Deus não tornam perfeito o coração das pessoas que o adoram.

[[v58-9-10]]

^<<v58-9-10,10>>^ Essas ofertas e sacrifícios têm a ver somente com comida, com bebida e com várias cerimônias de purificação . São regras externas que têm valor somente até que Deus renove todas as coisas.

[[v58-9-11]]

^<<v58-9-11,11>>^ Mas Cristo veio como o Grande Sacerdote das coisas boas que já estão aqui. A Tenda em que ele serve é melhor e mais perfeita e não foi construída por seres humanos, isto é, não é deste mundo.

[[v58-9-12]]

^<<v58-9-12,12>>^ Quando Cristo veio e entrou, uma vez por todas, no Lugar Santíssimo , ele não levou consigo sangue de bodes ou de bezerros para oferecer como sacrifício. Pelo contrário, ele ofereceu o seu próprio sangue e conseguiu para nós a salvação eterna.

[[v58-9-13]]

^<<v58-9-13,13>>^ O sangue de bodes e de touros e as cinzas da bezerra queimada são espalhados sobre as pessoas impuras , e elas ficam purificadas por fora.

[[v58-9-14]]

^<<v58-9-14,14>>^ Se isso é assim, imaginem então quanto maior ainda é o poder do sangue de Cristo! Por meio do Espírito eterno ele se ofereceu a si mesmo a Deus como sacrifício sem defeito. E o seu sangue nos purifica por dentro, tirando as nossas culpas; assim podemos servir ao Deus vivo, pois já não praticamos cerimônias que não valem nada.

[[v58-9-15]]

^<<v58-9-15,15>>^ Portanto, é Cristo quem consegue fazer uma nova aliança , para que os que foram chamados  por Deus possam receber as bênçãos eternas que o próprio Deus prometeu. Isso pode ser feito porque houve uma morte que livrou as pessoas dos pecados que praticaram enquanto a primeira aliança estava em vigor.

[[v58-9-16]]

^<<v58-9-16,16>>^ Onde há um testamento , é necessário provar que a pessoa que o fez já morreu.

[[v58-9-17]]

^<<v58-9-17,17>>^ Pois o testamento não vale nada enquanto estiver vivo quem o fez; só depois da morte dessa pessoa é que o testamento tem valor.

[[v58-9-18]]

^<<v58-9-18,18>>^ É por isso que a primeira aliança entrou em vigor somente com o uso do sangue de animais.

[[v58-9-19]]

^<<v58-9-19,19>>^ Em primeiro lugar, Moisés anunciou ao povo todos os mandamentos conforme estavam na lei . Depois pegou o sangue dos bezerros e dos bodes, misturou com água e borrifou o livro da lei e todo o povo, usando lã tingida de vermelho e hissopo .

[[v58-9-20]]

^<<v58-9-20,20>>^ Então disse: "Este é o sangue que sela  a aliança, que Deus mandou vocês obedecerem."

[[v58-9-21]]

^<<v58-9-21,21>>^ Da mesma forma Moisés também borrifou sangue sobre a Tenda e sobre todos os objetos usados na adoração.

[[v58-9-22]]

^<<v58-9-22,22>>^ De fato, de acordo com a lei, quase tudo é purificado com sangue. E, não havendo derramamento de sangue, não há perdão de pecados.

[[v58-9-23]]

^<<v58-9-23,23>>^ Essas coisas, que eram cópias das realidades celestiais, deviam ser purificadas  desse modo; mas as próprias coisas celestiais exigem sacrifícios  bem melhores.

[[v58-9-24]]

^<<v58-9-24,24>>^ Cristo não entrou num Lugar Santo  feito por seres humanos, que é a cópia do verdadeiro Lugar. Ele entrou no próprio céu, onde agora aparece na presença de Deus para pedir em nosso favor.

[[v58-9-25]]

^<<v58-9-25,25>>^ O Grande Sacerdote  entra, todos os anos, no Lugar Santíssimo , levando consigo sangue de um animal. Porém Cristo não entrou para se oferecer muitas vezes.

[[v58-9-26]]

^<<v58-9-26,26>>^ Se fosse assim, ele teria de sofrer muitas vezes desde a criação do mundo. Pelo contrário, uma vez por todas ele apareceu agora, quando os tempos estão chegando ao fim, para tirar os pecados por meio do sacrifício de si mesmo.

[[v58-9-27]]

^<<v58-9-27,27>>^ Cada pessoa tem de morrer uma vez só e depois ser julgada por Deus.

[[v58-9-28]]

^<<v58-9-28,28>>^ Assim também Cristo foi oferecido uma só vez em sacrifício, para tirar os pecados de muitas pessoas. Depois ele aparecerá pela segunda vez, não para tirar pecados, mas para salvar as pessoas que estão esperando por ele.

'''

xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[Próximo Capítulo &#62;]