include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-3-1]]

^<<v58-3-1,1>>^ Meus irmãos na fé, vocês que também foram chamados  por Deus, olhem para Jesus, que Deus enviou para ser o Grande Sacerdote  da fé que professamos.

[[v58-3-2]]

^<<v58-3-2,2>>^ Pois ele foi fiel a Deus, que o escolheu para esse serviço, assim como Moisés foi fiel no seu trabalho em toda a casa de Deus .

[[v58-3-3]]

^<<v58-3-3,3>>^ Assim como a pessoa que constrói uma casa é mais importante do que a casa, assim, também, Jesus é mais importante do que Moisés.

[[v58-3-4]]

^<<v58-3-4,4>>^ Uma casa tem de ser construída por alguém, mas Deus é o construtor de tudo o que existe.

[[v58-3-5]]

^<<v58-3-5,5>>^ E Moisés foi um servo  fiel no seu trabalho na casa de Deus e falou das coisas que Deus ia dizer no futuro.

[[v58-3-6]]

^<<v58-3-6,6>>^ Mas Cristo é fiel como Filho, que dirige a casa de Deus. E nós seremos a sua casa se conservarmos a nossa coragem e a nossa confiança naquilo que esperamos.

[[v58-3-7]]

^<<v58-3-7,7>>^ Por isso, como diz o Espírito Santo: "Se hoje vocês ouvirem a voz de Deus,

[[v58-3-8]]

^<<v58-3-8,8>>^ não sejam teimosos como foram os seus antepassados quando se revoltaram contra ele, no dia em que eles o puseram à prova no deserto.

[[v58-3-9]]

^<<v58-3-9,9>>^ Ali os antepassados de vocês me desafiaram e me puseram à prova, embora eles tivessem visto o que eu fiz durante quarenta anos.

[[v58-3-10]]

^<<v58-3-10,10>>^ Por isso fiquei irritado com aquela gente e disse: ‘Eles são gente de coração perverso e não querem obedecer aos meus mandamentos.’

[[v58-3-11]]

^<<v58-3-11,11>>^ Eu fiquei irado  e fiz este juramento: ‘Eles nunca entrarão na Terra Prometida , onde eu lhes teria dado descanso!’ "

[[v58-3-12]]

^<<v58-3-12,12>>^ Meus irmãos, cuidado para que nenhum de vocês tenha um coração tão mau e descrente, que o leve a se afastar do Deus vivo.

[[v58-3-13]]

^<<v58-3-13,13>>^ Pelo contrário, enquanto esse "hoje" de que falam as Escrituras Sagradas  se aplicar a nós, animem uns aos outros, a fim de que nenhum de vocês se deixe enganar pelo pecado, nem endureça o seu coração.

[[v58-3-14]]

^<<v58-3-14,14>>^ Pois seremos companheiros de Cristo se continuarmos firmes até o fim na confiança que temos tido desde o princípio.

[[v58-3-15]]

^<<v58-3-15,15>>^ É isso o que as Escrituras Sagradas dizem: "Se hoje vocês ouvirem a voz de Deus, não sejam teimosos como foram os seus antepassados quando se revoltaram contra ele."

[[v58-3-16]]

^<<v58-3-16,16>>^ Quem foi que ouviu a voz de Deus e se revoltou contra ele? Foram todos os que Moisés tirou do Egito.

[[v58-3-17]]

^<<v58-3-17,17>>^ Com quem foi que Deus se irritou durante quarenta anos? Foi com os que pecaram e caíram mortos no deserto.

[[v58-3-18]]

^<<v58-3-18,18>>^ E de quem é que Deus estava falando quando fez este juramento: "Eles nunca entrarão na Terra Prometida, onde eu lhes teria dado descanso"? Ele estava falando das pessoas que se revoltaram.

[[v58-3-19]]

^<<v58-3-19,19>>^ Portanto, vemos que elas não puderam entrar na Terra Prometida porque não tiveram fé.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]