include::./index.adoc[]

[[v58-8-0]]
=== Hebreus, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-8-1]]

^<<v58-8-1,1>>^ A coisa mais importante de tudo o que estamos dizendo tem a ver com o sacerdote que nós temos: ele é o Grande Sacerdote  que está sentado no céu, do lado direito do trono de Deus, o Todo-Poderoso.

[[v58-8-2]]

^<<v58-8-2,2>>^ Ele faz o seu serviço no Lugar Santíssimo , na verdadeira Tenda , que foi armada pelo Senhor e não por seres humanos.

[[v58-8-3]]

^<<v58-8-3,3>>^ Todo Grande Sacerdote é escolhido para apresentar a Deus as ofertas e os sacrifícios  de animais, e por isso é necessário que o nosso Grande Sacerdote tenha também alguma coisa para oferecer.

[[v58-8-4]]

^<<v58-8-4,4>>^ Se ele estivesse na terra, não seria sacerdote, pois existem sacerdotes que apresentam as ofertas de acordo com a Lei  de Moisés.

[[v58-8-5]]

^<<v58-8-5,5>>^ O trabalho que esses sacerdotes fazem é, de fato, somente uma cópia e uma sombra do que está no céu. Foi isso que aconteceu quando Deus falou com Moisés. Quando Moisés estava para construir a Tenda, Deus disse: "Tenha cuidado para fazer tudo de acordo com o modelo que eu lhe mostrei no monte."

[[v58-8-6]]

^<<v58-8-6,6>>^ Mas, de fato, Jesus foi encarregado de um serviço sacerdotal que é superior ao dos sacerdotes. Pois a aliança  que ele conseguiu é melhor porque ela se baseia em promessas de coisas melhores.

[[v58-8-7]]

^<<v58-8-7,7>>^ Pois, se a primeira aliança tivesse sido perfeita, não seria necessária uma nova aliança.

[[v58-8-8]]

^<<v58-8-8,8>>^ Mas Deus vê que o seu povo é culpado e diz: "Está chegando o tempo, diz o Senhor, em que farei uma nova aliança com o povo de Israel e com o povo de Judá.

[[v58-8-9]]

^<<v58-8-9,9>>^ Essa aliança não será como aquela que eu fiz com os antepassados deles, no dia em que os peguei pela mão e os tirei da terra do Egito. Não foram fiéis à aliança que fiz com eles, e por isso, diz o Senhor, eu os desprezei.

[[v58-8-10]]

^<<v58-8-10,10>>^ Quando esse tempo chegar, diz o Senhor, farei com o povo de Israel esta aliança: Eu porei as minhas leis na mente deles e no coração deles as escreverei. Eu serei o Deus deles, e eles serão o meu povo.

[[v58-8-11]]

^<<v58-8-11,11>>^ Ninguém vai precisar ensinar o seu patrício nem o seu parente, dizendo: ‘Procure conhecer o Senhor.’ Porque todos me conhecerão, tanto as pessoas mais humildes como as mais importantes.

[[v58-8-12]]

^<<v58-8-12,12>>^ Pois eu perdoarei os seus pecados e nunca mais lembrarei das suas maldades."

[[v58-8-13]]

^<<v58-8-13,13>>^ E, quando Deus fala da nova aliança, é porque ele já tornou velha a primeira. E o que está ficando velho e gasto vai desaparecer logo.

'''

xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[Próximo Capítulo &#62;]