include::./index.adoc[]

[[v58-13-0]]
=== Hebreus, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-13-1]]

^<<v58-13-1,1>>^ Continuem a amar uns aos outros como irmãos em Cristo.

[[v58-13-2]]

^<<v58-13-2,2>>^ Não deixem de receber bem aqueles que vêm à casa de vocês; pois alguns que foram hospitaleiros receberam anjos, sem saber.

[[v58-13-3]]

^<<v58-13-3,3>>^ Lembrem dos presos, como se vocês estivessem na cadeia com eles. Lembrem dos que sofrem, como se vocês estivessem sofrendo com eles.

[[v58-13-4]]

^<<v58-13-4,4>>^ Que o casamento seja respeitado por todos, e que os maridos e as esposas sejam fiéis um ao outro. Deus julgará os imorais e os que cometem adultério.

[[v58-13-5]]

^<<v58-13-5,5>>^ Não se deixem dominar pelo amor ao dinheiro e fiquem satisfeitos com o que vocês têm, pois Deus disse: "Eu nunca os deixarei e jamais os abandonarei."

[[v58-13-6]]

^<<v58-13-6,6>>^ Portanto, sejamos corajosos e afirmemos: "O Senhor é quem me ajuda, e eu não tenho medo. Que mal pode alguém me fazer?"

[[v58-13-7]]

^<<v58-13-7,7>>^ Lembrem dos seus primeiros líderes espirituais, que anunciaram a mensagem de Deus a vocês. Pensem como eles viveram e morreram e imitem a fé que eles tinham.

[[v58-13-8]]

^<<v58-13-8,8>>^ Jesus Cristo é o mesmo ontem, hoje e sempre.

[[v58-13-9]]

^<<v58-13-9,9>>^ Não se deixem levar por ensinamentos diferentes e estranhos que tiram vocês do caminho certo. É bom sermos espiritualmente fortes por meio da graça  de Deus e não por meio da obediência a regras sobre alimentos. Pois os que obedecem a essas regras não têm sido ajudados por elas.

[[v58-13-10]]

^<<v58-13-10,10>>^ Os sacerdotes que servem no Templo não têm o direito de comer do sacrifício  que é oferecido sobre o nosso altar.

[[v58-13-11]]

^<<v58-13-11,11>>^ O Grande Sacerdote  leva o sangue de animais para dentro do Lugar Santíssimo  a fim de oferecê-lo como sacrifício pelos pecados. Mas os corpos dos animais são queimados fora do acampamento.

[[v58-13-12]]

^<<v58-13-12,12>>^ Por isso Jesus também morreu fora da cidade de Jerusalém para, com o seu próprio sangue, purificar  o povo dos seus pecados.

[[v58-13-13]]

^<<v58-13-13,13>>^ Portanto, vamos para perto de Jesus, fora do acampamento, e soframos a mesma desonra que ele sofreu.

[[v58-13-14]]

^<<v58-13-14,14>>^ Porque neste mundo não temos nenhuma cidade que dure para sempre; pelo contrário, procuramos a cidade que virá depois.

[[v58-13-15]]

^<<v58-13-15,15>>^ Por isso, por meio de Jesus Cristo, ofereçamos sempre louvor a Deus. Esse louvor é o sacrifício que apresentamos, a oferta que é dada por lábios que confessam a sua fé nele.

[[v58-13-16]]

^<<v58-13-16,16>>^ Não deixem de fazer o bem e de ajudar uns aos outros, pois são esses os sacrifícios que agradam a Deus.

[[v58-13-17]]

^<<v58-13-17,17>>^ Obedeçam aos seus líderes e sigam as suas ordens, pois eles cuidam sempre das necessidades espirituais de vocês porque sabem que vão prestar contas disso a Deus. Se vocês obedecerem, eles farão o trabalho com alegria; mas, se vocês não obedecerem, eles trabalharão com tristeza, e isso não ajudará vocês em nada.

[[v58-13-18]]

^<<v58-13-18,18>>^ Continuem a orar por nós. Temos certeza de que a nossa consciência está limpa, pois sempre queremos fazer o que é correto.

[[v58-13-19]]

^<<v58-13-19,19>>^ E peço a vocês, de modo todo especial, que orem para que Deus me mande de volta a vocês o mais depressa possível.

[[v58-13-20]]

^<<v58-13-20,20>>^ Deus ressuscitou o nosso Senhor Jesus, que, por causa da sua morte na cruz, é o Grande Pastor do rebanho. E é por meio do sangue de Jesus que a aliança  eterna é selada . Que o Deus de paz lhes dê tudo de bom que vocês precisam para fazer a sua vontade. E que ele, por meio de Jesus Cristo, faça em nós tudo o que lhe agrada. E a Cristo seja dada a glória  para todo o sempre! Amém !

[[v58-13-21]]

^<<v58-13-21,21>>^ Deus ressuscitou o nosso Senhor Jesus, que, por causa da sua morte na cruz, é o Grande Pastor do rebanho. E é por meio do sangue de Jesus que a aliança  eterna é selada . Que o Deus de paz lhes dê tudo de bom que vocês precisam para fazer a sua vontade. E que ele, por meio de Jesus Cristo, faça em nós tudo o que lhe agrada. E a Cristo seja dada a glória  para todo o sempre! Amém !

[[v58-13-22]]

^<<v58-13-22,22>>^ Meus irmãos, peço que escutem com paciência essas palavras de ânimo, pois esta carta que escrevi não é muito longa.

[[v58-13-23]]

^<<v58-13-23,23>>^ Quero que saibam que o nosso irmão Timóteo já saiu da cadeia. Se ele vier logo, eu o levarei comigo quando for ver vocês.

[[v58-13-24]]

^<<v58-13-24,24>>^ Saudações a todos os líderes da igreja daí e a todo o povo de Deus. Os irmãos da Itália também mandam saudações a vocês.

'''

xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[&#60; Capítulo Anterior] | <<v58-13-0,Topo>> | xref:059-tiago/059-tiago-001.adoc#v59-1-0[Próximo Capítulo &#62;]