include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-7-1]]

^<<v58-7-1,1>>^ Esse Melquisedeque era rei da cidade de Salém e sacerdote do Deus Altíssimo. Quando Abraão estava voltando da batalha em que matou os reis, Melquisedeque foi ao encontro dele e o abençoou.

[[v58-7-2]]

^<<v58-7-2,2>>^ Abraão lhe deu a décima parte de tudo o que ele havia tomado dos inimigos na batalha. O nome de Melquisedeque quer dizer primeiramente "Rei da Justiça". E, porque ele era rei de Salém , o seu nome também quer dizer "Rei da Paz".

[[v58-7-3]]

^<<v58-7-3,3>>^ Não se conhece o pai, nem a mãe, nem qualquer antepassado de Melquisedeque. E também não se sabe nada sobre o seu nascimento ou sobre a sua morte. Por ser como o Filho de Deus, ele continua sacerdote para sempre.

[[v58-7-4]]

^<<v58-7-4,4>>^ Vejam como Melquisedeque era grande: Abraão, o patriarca , lhe deu a décima parte de tudo o que havia tomado dos inimigos na batalha.

[[v58-7-5]]

^<<v58-7-5,5>>^ Conforme a Lei  de Moisés, os sacerdotes, que são descendentes de Levi, têm a obrigação de receber do povo a décima parte de tudo. Eles recebem dos seus próprios patrícios, embora estes também sejam descendentes de Abraão.

[[v58-7-6]]

^<<v58-7-6,6>>^ Melquisedeque não era descendente de Levi, mas recebeu a décima parte daquilo que Abraão havia tomado na batalha e o abençoou. Sim, abençoou o próprio Abraão, que havia recebido as promessas de Deus.

[[v58-7-7]]

^<<v58-7-7,7>>^ Não há dúvida de que aquele que abençoa é mais importante do que aquele que é abençoado.

[[v58-7-8]]

^<<v58-7-8,8>>^ No caso dos sacerdotes, a décima parte é recebida por homens que um dia vão morrer. Mas, no caso de Melquisedeque, como dizem as Escrituras Sagradas , a décima parte foi recebida por alguém que continua vivo .

[[v58-7-9]]

^<<v58-7-9,9>>^ Portanto, quando Abraão pagou a décima parte, Levi, cujos descendentes recebem a décima parte, também pagou.

[[v58-7-10]]

^<<v58-7-10,10>>^ Pois Levi não tinha nascido, e, por assim dizer, ainda estava no corpo do seu antepassado Abraão quando este se encontrou com Melquisedeque.

[[v58-7-11]]

^<<v58-7-11,11>>^ A lei que o povo de Israel recebeu se baseava no sacerdócio dos levitas . Ora, se o trabalho dos sacerdotes levitas tivesse sido perfeito, não haveria necessidade de aparecer outro tipo de sacerdote, da ordem do sacerdócio de Melquisedeque e não da ordem de Arão .

[[v58-7-12]]

^<<v58-7-12,12>>^ Pois, quando se muda o sacerdócio, a lei também precisa ser mudada.

[[v58-7-13]]

^<<v58-7-13,13>>^ E o nosso Senhor Jesus, a respeito de quem são ditas essas coisas, pertencia a outra tribo . E nenhum membro dessa tribo jamais serviu como sacerdote.

[[v58-7-14]]

^<<v58-7-14,14>>^ É sabido que, por nascimento, Jesus, o nosso Senhor, pertencia à tribo de Judá, e Moisés não disse nada dessa tribo quando falou a respeito de sacerdotes.

[[v58-7-15]]

^<<v58-7-15,15>>^ E tudo isso se torna bem mais claro, pois surgiu um sacerdote diferente, parecido com Melquisedeque.

[[v58-7-16]]

^<<v58-7-16,16>>^ Ele não foi feito sacerdote pelas leis  ou regras humanas, porém se tornou sacerdote por meio do poder de uma vida que não tem fim.

[[v58-7-17]]

^<<v58-7-17,17>>^ Porque as Escrituras Sagradas  dizem: "Você será sacerdote para sempre, na ordem do sacerdócio de Melquisedeque."

[[v58-7-18]]

^<<v58-7-18,18>>^ Assim a regra antiga foi anulada porque era fraca e inútil.

[[v58-7-19]]

^<<v58-7-19,19>>^ Pois a lei não podia aperfeiçoar nada. Mas agora Deus nos deu uma esperança melhor, por meio da qual chegamos perto dele.

[[v58-7-20]]

^<<v58-7-20,20>>^ Além disso, há o juramento de Deus. Não houve juramento quando os outros se tornaram sacerdotes.

[[v58-7-21]]

^<<v58-7-21,21>>^ Porém houve juramento quando Jesus se tornou sacerdote, pois Deus lhe disse: "O Senhor jurou e não voltará atrás. Ele disse: ‘Você será sacerdote para sempre.’ "

[[v58-7-22]]

^<<v58-7-22,22>>^ Portanto, essa diferença também faz com que Jesus seja a garantia de uma aliança  melhor.

[[v58-7-23]]

^<<v58-7-23,23>>^ Há ainda outra diferença: os outros sacerdotes foram muitos porque morriam e não podiam continuar o seu trabalho.

[[v58-7-24]]

^<<v58-7-24,24>>^ Mas Jesus vive para sempre, e o seu sacerdócio não passa para ninguém.

[[v58-7-25]]

^<<v58-7-25,25>>^ E por isso ele pode, hoje e sempre, salvar as pessoas que vão a Deus por meio dele, porque Jesus vive para sempre a fim de pedir a Deus em favor delas.

[[v58-7-26]]

^<<v58-7-26,26>>^ Por isso Jesus é o Grande Sacerdote  de que necessitamos. Ele é perfeito e não tem nenhum pecado ou falha. Ele foi separado dos pecadores e elevado acima dos céus .

[[v58-7-27]]

^<<v58-7-27,27>>^ Ele não é como os outros Grandes Sacerdotes; não precisa oferecer sacrifícios  todos os dias, primeiro pelos seus próprios pecados e depois pelos pecados do povo. Ele ofereceu um sacrifício, uma vez por todas, quando se ofereceu a si mesmo.

[[v58-7-28]]

^<<v58-7-28,28>>^ A Lei de Moisés escolheu homens, que são imperfeitos, para serem Grandes Sacerdotes. Mas, pela promessa feita com juramento, a qual veio depois da Lei de Moisés, Deus escolhe o Filho, que se tornou perfeito para sempre.

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]