include::./index.adoc[]

[[v58-12-0]]
=== Hebreus, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-12-1]]

^<<v58-12-1,1>>^ Assim nós temos essa grande multidão de testemunhas ao nosso redor. Portanto, deixemos de lado tudo o que nos atrapalha e o pecado que se agarra firmemente em nós e continuemos a correr, sem desanimar, a corrida marcada para nós.

[[v58-12-2]]

^<<v58-12-2,2>>^ Conservemos os nossos olhos fixos em Jesus, pois é por meio dele que a nossa fé começa, e é ele quem a aperfeiçoa. Ele não deixou que a cruz fizesse com que ele desistisse. Pelo contrário, por causa da alegria que lhe foi prometida, ele não se importou com a humilhação de morrer na cruz e agora está sentado do lado direito do trono de Deus.

[[v58-12-3]]

^<<v58-12-3,3>>^ Pensem no sofrimento dele e como suportou com paciência o ódio dos pecadores. Assim, vocês, não desanimem, nem desistam.

[[v58-12-4]]

^<<v58-12-4,4>>^ Porque na luta contra o pecado vocês ainda não tiveram de combater até à morte.

[[v58-12-5]]

^<<v58-12-5,5>>^ Será que vocês já esqueceram as palavras de encorajamento que Deus lhes disse, como se vocês fossem filhos dele? Pois ele disse: "Preste atenção, meu filho, quando o Senhor o castiga, e não se desanime quando ele o repreende.

[[v58-12-6]]

^<<v58-12-6,6>>^ Pois o Senhor corrige quem ele ama e castiga quem ele aceita como filho."

[[v58-12-7]]

^<<v58-12-7,7>>^ Suportem o sofrimento com paciência como se fosse um castigo dado por um pai, pois o sofrimento de vocês mostra que Deus os está tratando como seus filhos. Será que existe algum filho que nunca foi corrigido pelo pai?

[[v58-12-8]]

^<<v58-12-8,8>>^ Se vocês não são corrigidos como acontece com todos os filhos de Deus, então não são filhos de verdade, mas filhos ilegítimos.

[[v58-12-9]]

^<<v58-12-9,9>>^ No caso dos nossos pais humanos, eles nos corrigiam, e nós os respeitávamos. Então devemos obedecer muito mais ainda ao nosso Pai celestial e assim viveremos.

[[v58-12-10]]

^<<v58-12-10,10>>^ Os nossos pais humanos nos corrigiam durante pouco tempo, pois achavam que isso era certo; mas Deus nos corrige para o nosso próprio bem, para que participemos da sua santidade .

[[v58-12-11]]

^<<v58-12-11,11>>^ Quando somos corrigidos, isso no momento nos parece motivo de tristeza e não de alegria. Porém, mais tarde, os que foram corrigidos recebem como recompensa uma vida correta e de paz.

[[v58-12-12]]

^<<v58-12-12,12>>^ Portanto, levantem as suas mãos cansadas e fortaleçam os seus joelhos enfraquecidos.

[[v58-12-13]]

^<<v58-12-13,13>>^ Andem por caminhos aplanados para que o pé aleijado não manque, mas seja curado.

[[v58-12-14]]

^<<v58-12-14,14>>^ Procurem ter paz com todos e se esforcem para viver uma vida completamente dedicada ao Senhor, pois sem isso ninguém o verá.

[[v58-12-15]]

^<<v58-12-15,15>>^ Tomem cuidado para que ninguém abandone a graça  de Deus. Cuidado, para que ninguém se torne como uma planta amarga que cresce e prejudica muita gente com o seu veneno.

[[v58-12-16]]

^<<v58-12-16,16>>^ E tomem cuidado também para que ninguém se torne imoral ou perca o respeito pelas coisas sagradas, como Esaú, que, por causa de um prato de comida, vendeu os seus direitos de filho mais velho.

[[v58-12-17]]

^<<v58-12-17,17>>^ Como vocês sabem, depois ele quis receber a bênção do seu pai. Mas foi rejeitado porque não encontrou um modo de mudar o que havia feito, embora procurasse fazer isso até mesmo com lágrimas.

[[v58-12-18]]

^<<v58-12-18,18>>^ Vocês não foram como o povo de Israel. Vocês não chegaram perto de alguma coisa que se pode tocar, como o monte Sinai com o seu fogo destruidor, a escuridão e as trevas, a tempestade,

[[v58-12-19]]

^<<v58-12-19,19>>^ o barulho de trombeta e o som de uma voz. Quando os israelitas ouviram a voz, pediram que ela não dissesse mais nada,

[[v58-12-20]]

^<<v58-12-20,20>>^ pois eles não podiam suportar a ordem que dizia: "Até um animal, se tocar o monte, deverá ser morto a pedradas."

[[v58-12-21]]

^<<v58-12-21,21>>^ O que estavam vendo era tão terrível, que Moisés disse: "Estou tremendo de medo!"

[[v58-12-22]]

^<<v58-12-22,22>>^ Pelo contrário, vocês chegaram ao monte Sião  e à cidade do Deus vivo, a Jerusalém celestial com os seus milhares de anjos.

[[v58-12-23]]

^<<v58-12-23,23>>^ Vocês chegaram à reunião alegre dos filhos mais velhos de Deus, isto é, daqueles que têm o nome deles escrito no céu. Vocês chegaram até Deus, que é o juiz de todos, e chegaram também aos espíritos dos que são corretos e que foram aperfeiçoados.

[[v58-12-24]]

^<<v58-12-24,24>>^ Vocês chegaram até Jesus, que fez a nova aliança  e que borrifou o sangue que fala de coisas muito melhores do que o sangue de Abel.

[[v58-12-25]]

^<<v58-12-25,25>>^ Portanto, tenham cuidado e não recusem ouvir aquele que fala. Aqueles que recusaram ouvir a pessoa que entregou a mensagem divina na terra não puderam escapar. Por isso muito menos escaparemos nós se rejeitarmos aquele que lá do céu nos fala.

[[v58-12-26]]

^<<v58-12-26,26>>^ Naquele tempo a voz de Deus fez com que a terra estremecesse, mas agora ele prometeu isto: "Mais uma vez farei com que trema não somente a terra, mas também o céu."

[[v58-12-27]]

^<<v58-12-27,27>>^ As palavras "mais uma vez" mostram bem que as coisas criadas serão abaladas e mudadas, para que as que não podem ser abaladas continuem como estão.

[[v58-12-28]]

^<<v58-12-28,28>>^ Por isso sejamos agradecidos, pois já recebemos um Reino  que não pode ser abalado. Sejamos agradecidos e adoremos a Deus de um modo que o agrade, com respeito e temor .

[[v58-12-29]]

^<<v58-12-29,29>>^ Porque, na verdade, o nosso Deus é um fogo destruidor.

'''

xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[Próximo Capítulo &#62;]