include::./index.adoc[]

[[v58-2-0]]
=== Hebreus, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-2-1]]

^<<v58-2-1,1>>^ Por isso devemos prestar mais atenção nas verdades que temos ouvido, para não nos desviarmos delas.

[[v58-2-2]]

^<<v58-2-2,2>>^ Não há dúvida de que a mensagem que foi dada por meio dos anjos é verdadeira; e aqueles que não a seguiram nem foram obedientes a ela receberam o castigo que mereciam.

[[v58-2-3]]

^<<v58-2-3,3>>^ Sendo assim, como é que nós escaparemos do castigo se desprezarmos uma salvação tão grande? Primeiro, o próprio Senhor Jesus anunciou essa salvação; e depois aqueles que a ouviram nos provaram que ela é verdadeira.

[[v58-2-4]]

^<<v58-2-4,4>>^ Ao mesmo tempo, por meio de sinais de poder, maravilhas e muitos tipos de milagres, Deus confirmou o testemunho deles. E, de acordo com a sua vontade, distribuiu também os dons  do Espírito Santo.

[[v58-2-5]]

^<<v58-2-5,5>>^ Pois Deus não deu aos anjos o poder de governar o mundo novo que está por vir, o mundo do qual estamos falando.

[[v58-2-6]]

^<<v58-2-6,6>>^ Pelo contrário, em alguma parte das Escrituras Sagradas  alguém afirma: "Que é um simples ser humano, ó Deus, para que penses nele? Que é o ser mortal para que te preocupes com ele?

[[v58-2-7]]

^<<v58-2-7,7>>^ Tu o colocaste por pouco tempo em posição inferior à dos anjos, tu lhe deste a glória  e a honra de um rei

[[v58-2-8]]

^<<v58-2-8,8>>^ e puseste todas as coisas debaixo do domínio dele." Quando se diz que Deus pôs "todas as coisas debaixo do domínio dele", isso quer dizer que nada ficou de fora. Porém não vemos o ser humano governando hoje todas as coisas.

[[v58-2-9]]

^<<v58-2-9,9>>^ Mas nós vemos Jesus fazendo isso. Por um pouco de tempo ele foi colocado em posição inferior à dos anjos, para que, pela graça  de Deus, ele morresse por todas as pessoas. Agora nós o vemos coroado de glória e de honra por causa da morte que ele sofreu.

[[v58-2-10]]

^<<v58-2-10,10>>^ Pois Deus, que cria e sustenta todas as coisas, fez o que era apropriado e tornou Jesus perfeito por meio do sofrimento. Deus fez isso a fim de que muitos, isto é, os seus filhos , tomassem parte na glória de Jesus. Pois é Jesus quem os guia para a salvação.

[[v58-2-11]]

^<<v58-2-11,11>>^ Jesus purifica  as pessoas dos seus pecados; e todos, tanto ele como os que são purificados, têm o mesmo Pai. É por isso que Jesus não se envergonha de chamá-los de irmãos.

[[v58-2-12]]

^<<v58-2-12,12>>^ Como ele diz: "Ó Deus, eu falarei a respeito de ti aos meus irmãos e te louvarei na reunião do povo."

[[v58-2-13]]

^<<v58-2-13,13>>^ Diz também: "Eu confiarei nele." E diz ainda: "Aqui estou eu com os filhos que Deus me deu."

[[v58-2-14]]

^<<v58-2-14,14>>^ Os filhos, como ele os chama, são pessoas de carne e sangue. E por isso o próprio Jesus se tornou igual a eles, tomando parte na natureza humana deles. Ele fez isso para que, por meio da sua morte, pudesse destruir o Diabo, que tem poder sobre a morte.

[[v58-2-15]]

^<<v58-2-15,15>>^ E também para libertar os que foram escravos toda a sua vida por causa do medo da morte.

[[v58-2-16]]

^<<v58-2-16,16>>^ É claro que ele não veio para ajudar os anjos. Em vez disso, como dizem as Escrituras: "Ele ajuda os descendentes de Abraão."

[[v58-2-17]]

^<<v58-2-17,17>>^ Isso quer dizer que foi preciso que Jesus se tornasse em tudo igual aos seus irmãos a fim de ser o Grande Sacerdote  deles, bondoso e fiel no seu serviço a Deus, para que os pecados do povo fossem perdoados.

[[v58-2-18]]

^<<v58-2-18,18>>^ E agora Jesus pode ajudar os que são tentados, pois ele mesmo foi tentado e sofreu.

'''

xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[Próximo Capítulo &#62;]