include::./index.adoc[]

[[v58-11-0]]
=== Hebreus, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-11-1]]

^<<v58-11-1,1>>^ A fé é a certeza de que vamos receber as coisas que esperamos e a prova de que existem coisas que não podemos ver.

[[v58-11-2]]

^<<v58-11-2,2>>^ Foi pela fé que as pessoas do passado conseguiram a aprovação de Deus.

[[v58-11-3]]

^<<v58-11-3,3>>^ É pela fé que entendemos que o Universo  foi criado pela palavra de Deus e que aquilo que pode ser visto foi feito daquilo que não se vê.

[[v58-11-4]]

^<<v58-11-4,4>>^ Foi pela fé que Abel ofereceu a Deus um sacrifício  melhor do que o de Caim. Pela fé ele conseguiu a aprovação de Deus como homem correto, tendo o próprio Deus aprovado as suas ofertas. Por meio da sua fé, Abel, mesmo depois de morto, ainda fala.

[[v58-11-5]]

^<<v58-11-5,5>>^ Foi pela fé que Enoque escapou da morte. Ele foi levado para Deus, e ninguém o encontrou porque Deus mesmo o havia levado. As Escrituras Sagradas  dizem que antes disso ele já havia agradado a Deus.

[[v58-11-6]]

^<<v58-11-6,6>>^ Sem fé ninguém pode agradar a Deus, porque quem vai a ele precisa crer que ele existe e que recompensa os que procuram conhecê-lo melhor.

[[v58-11-7]]

^<<v58-11-7,7>>^ Foi pela fé que Noé ouviu os avisos de Deus sobre as coisas que iam acontecer e que não podiam ser vistas. Noé obedeceu a Deus e construiu uma barca em que ele e a sua família foram salvos. Assim Noé condenou o mundo e recebeu de Deus a aprovação que vem por meio da fé.

[[v58-11-8]]

^<<v58-11-8,8>>^ Foi pela fé que Abraão, ao ser chamado  por Deus, obedeceu e saiu para uma terra que Deus lhe prometeu dar. Ele deixou o seu próprio país, sem saber para onde ia.

[[v58-11-9]]

^<<v58-11-9,9>>^ Pela fé ele morou como estrangeiro na terra que Deus lhe havia prometido. Viveu em barracas com Isaque e Jacó, que também receberam a mesma promessa de Deus.

[[v58-11-10]]

^<<v58-11-10,10>>^ Porque Abraão esperava a cidade que Deus planejou e construiu, a cidade que tem alicerces que não podem ser destruídos.

[[v58-11-11]]

^<<v58-11-11,11>>^ Foi pela fé que Abraão se tornou pai, embora fosse velho demais e a própria Sara não pudesse ter filhos. Ele creu que Deus ia cumprir a sua promessa.

[[v58-11-12]]

^<<v58-11-12,12>>^ Assim, de um só homem, que estava praticamente morto, nasceram tantos descendentes como as estrelas do céu, tão numerosos como os grãos de areia da praia do mar.

[[v58-11-13]]

^<<v58-11-13,13>>^ Todos esses morreram cheios de fé. Não receberam as coisas que Deus tinha prometido, mas as viram de longe e ficaram contentes por causa delas. E declararam que eram estrangeiros e refugiados, de passagem por este mundo.

[[v58-11-14]]

^<<v58-11-14,14>>^ E aqueles que dizem isso mostram bem claro que estão procurando uma pátria para si mesmos.

[[v58-11-15]]

^<<v58-11-15,15>>^ Não ficaram pensando em voltar para a terra de onde tinham saído. Se quisessem, teriam a oportunidade de voltar.

[[v58-11-16]]

^<<v58-11-16,16>>^ Mas, pelo contrário, estavam procurando uma pátria melhor, a pátria celestial. E Deus não se envergonha de ser chamado de o Deus deles, porque ele mesmo preparou uma cidade para eles.

[[v58-11-17]]

^<<v58-11-17,17>>^ Foi pela fé que Abraão, quando Deus o quis pôr à prova, ofereceu o seu filho Isaque em sacrifício . Deus tinha prometido muitos descendentes a Abraão, mas mesmo assim ele estava pronto para oferecer o seu único filho em sacrifício.

[[v58-11-18]]

^<<v58-11-18,18>>^ Deus lhe tinha dito: "Por meio de Isaque é que você terá descendentes."

[[v58-11-19]]

^<<v58-11-19,19>>^ Abraão reconhecia que Deus era capaz de ressuscitar Isaque, e, por assim dizer, Abraão tornou a receber da morte o seu filho Isaque.

[[v58-11-20]]

^<<v58-11-20,20>>^ Foi pela fé que Isaque prometeu bênçãos para o futuro a Jacó e a Esaú.

[[v58-11-21]]

^<<v58-11-21,21>>^ Foi pela fé que Jacó, pouco antes de morrer, abençoou os filhos de José. Ele se apoiou na sua bengala e adorou a Deus.

[[v58-11-22]]

^<<v58-11-22,22>>^ Foi pela fé que José, quando estava para morrer, falou da saída dos israelitas do Egito e deu ordens sobre o que deveria ser feito com o seu corpo.

[[v58-11-23]]

^<<v58-11-23,23>>^ Foi pela fé que os pais de Moisés, quando ele nasceu, o esconderam durante três meses. Eles viram que o menino era bonito e não tiveram medo de desobedecer à ordem do rei.

[[v58-11-24]]

^<<v58-11-24,24>>^ Foi pela fé que Moisés, quando já era adulto, não quis ser chamado de filho da filha de Faraó.

[[v58-11-25]]

^<<v58-11-25,25>>^ Ele preferiu sofrer com o povo de Deus em vez de gozar, por pouco tempo, os prazeres do pecado.

[[v58-11-26]]

^<<v58-11-26,26>>^ Ele achou que era muito melhor sofrer o desprezo por causa do Messias  do que possuir todos os tesouros do Egito. É que ele tinha os olhos fixos na recompensa futura.

[[v58-11-27]]

^<<v58-11-27,27>>^ Foi pela fé que Moisés saiu do Egito, sem ter medo da raiva do rei, e continuou firme, como se estivesse vendo o Deus invisível.

[[v58-11-28]]

^<<v58-11-28,28>>^ Pela fé Moisés começou o costume de celebrar a Páscoa  e mandou marcar com sangue as portas das casas dos israelitas para que o Anjo da Morte não matasse os filhos mais velhos deles.

[[v58-11-29]]

^<<v58-11-29,29>>^ Foi pela fé que os israelitas atravessaram o mar Vermelho como se fosse terra seca. E, quando os egípcios tentaram atravessar, o mar os engoliu.

[[v58-11-30]]

^<<v58-11-30,30>>^ Foi pela fé que caíram as muralhas de Jericó, depois que os israelitas marcharam em volta delas durante sete dias.

[[v58-11-31]]

^<<v58-11-31,31>>^ Foi pela fé que Raabe, a prostituta, não morreu com os que tinham desobedecido a Deus, pois ela havia recebido bem os espiões israelitas.

[[v58-11-32]]

^<<v58-11-32,32>>^ O que mais posso dizer? O tempo é pouco para falar de Gideão, de Baraque, de Sansão, de Jefté, de Davi, de Samuel e dos profetas .

[[v58-11-33]]

^<<v58-11-33,33>>^ Pela fé eles lutaram contra nações inteiras e venceram. Fizeram o que era correto e receberam o que Deus lhes havia prometido. Fecharam a boca de leões,

[[v58-11-34]]

^<<v58-11-34,34>>^ apagaram incêndios terríveis e escaparam de serem mortos à espada. Eram fracos, mas se tornaram fortes. Foram poderosos na guerra e venceram exércitos estrangeiros.

[[v58-11-35]]

^<<v58-11-35,35>>^ Pela fé mulheres receberam de volta os seus mortos, que ressuscitaram. Outros foram torturados até a morte; eles recusaram ser postos em liberdade a fim de ressuscitar para uma vida melhor.

[[v58-11-36]]

^<<v58-11-36,36>>^ Alguns foram insultados e surrados; e outros, acorrentados e jogados na cadeia.

[[v58-11-37]]

^<<v58-11-37,37>>^ Outros foram mortos a pedradas; outros, serrados pelo meio; e outros, mortos à espada. Andaram de um lado para outro vestidos de peles de ovelhas e de cabras; eram pobres, perseguidos e maltratados.

[[v58-11-38]]

^<<v58-11-38,38>>^ Andaram como refugiados pelos desertos e montes, vivendo em cavernas e em buracos na terra. O mundo não era digno deles!

[[v58-11-39]]

^<<v58-11-39,39>>^ Porque creram, todas essas pessoas foram aprovadas por Deus, mas não receberam o que ele havia prometido.

[[v58-11-40]]

^<<v58-11-40,40>>^ Pois Deus tinha preparado um plano ainda melhor para nós, a fim de que, somente conosco, elas fossem aperfeiçoadas.

'''

xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[&#60; Capítulo Anterior] | <<v58-11-0,Topo>> | xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[Próximo Capítulo &#62;]