include::./index.adoc[]

[[v58-5-0]]
=== Hebreus, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v58-5-1]]

^<<v58-5-1,1>>^ Cada Grande Sacerdote  é escolhido entre os homens e nomeado para servir a Deus em favor do povo, apresentando a Deus ofertas e sacrifícios  pelos pecados.

[[v58-5-2]]

^<<v58-5-2,2>>^ Como ele próprio tem as suas fraquezas, pode ter paciência com os ignorantes e com os que cometem erros.

[[v58-5-3]]

^<<v58-5-3,3>>^ E, porque ele mesmo é fraco, precisa oferecer sacrifícios não somente pelos pecados do povo, mas também pelos seus próprios pecados.

[[v58-5-4]]

^<<v58-5-4,4>>^ Ninguém escolhe para si mesmo a honra de ser Grande Sacerdote. É somente pela vontade de Deus que um homem é chamado  para ser Grande Sacerdote, como aconteceu com Arão.

[[v58-5-5]]

^<<v58-5-5,5>>^ Assim também Cristo não tomou para si mesmo a honra de ser Grande Sacerdote; foi Deus quem lhe deu essa honra, pois lhe disse: "Você é o meu Filho; hoje eu me tornei o seu Pai."

[[v58-5-6]]

^<<v58-5-6,6>>^ Em outro lugar das Escrituras Sagradas , ele também disse: "Você será sacerdote para sempre, na ordem do sacerdócio de Melquisedeque."

[[v58-5-7]]

^<<v58-5-7,7>>^ Durante a sua vida aqui na terra, Cristo, em voz alta e com lágrimas, fez orações e súplicas a Deus, que o podia salvar da morte. E as suas orações foram atendidas porque ele era dedicado a Deus.

[[v58-5-8]]

^<<v58-5-8,8>>^ Embora fosse o Filho de Deus, ele aprendeu, por meio dos seus sofrimentos, a ser obediente.

[[v58-5-9]]

^<<v58-5-9,9>>^ E, depois de ser aperfeiçoado, ele se tornou a fonte da salvação eterna para todos os que lhe obedecem.

[[v58-5-10]]

^<<v58-5-10,10>>^ E Deus o nomeou Grande Sacerdote, na ordem do sacerdócio de Melquisedeque.

[[v58-5-11]]

^<<v58-5-11,11>>^ Temos muito o que dizer a respeito desse assunto; mas, porque vocês custam a entender as coisas, é difícil explicá-las.

[[v58-5-12]]

^<<v58-5-12,12>>^ Depois de tanto tempo, vocês já deviam ser mestres, mas ainda precisam de alguém que lhes ensine as primeiras lições dos ensinamentos de Deus. Em vez de alimento sólido, vocês ainda precisam de leite .

[[v58-5-13]]

^<<v58-5-13,13>>^ E quem precisa de leite ainda é criança e não tem nenhuma experiência para saber o que está certo ou errado.

[[v58-5-14]]

^<<v58-5-14,14>>^ Porém a comida dos adultos é sólida, pois eles pela prática sabem a diferença entre o que é bom e o que é mau.

'''

xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[&#60; Capítulo Anterior] | <<v58-5-0,Topo>> | xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[Próximo Capítulo &#62;]