include::./index.adoc[]

[[v53-3-0]]
=== 2 Tessalonicenses, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v53-3-1]]

^<<v53-3-1,1>>^ Finalmente, irmãos, orem por nós para que a mensagem do Senhor continue a se espalhar rapidamente e seja bem-aceita, como aconteceu entre vocês.

[[v53-3-2]]

^<<v53-3-2,2>>^ Orem também para que Deus nos livre das pessoas más e perversas, pois nem todos creem na mensagem.

[[v53-3-3]]

^<<v53-3-3,3>>^ Mas o Senhor Jesus é fiel. Ele lhes dará forças e os livrará do Maligno .

[[v53-3-4]]

^<<v53-3-4,4>>^ E o Senhor faz com que confiemos em vocês; temos a certeza de que estão fazendo e continuarão a fazer o que lhes recomendamos.

[[v53-3-5]]

^<<v53-3-5,5>>^ Que o Senhor os faça compreender melhor o amor de Deus por vocês e a firmeza que ele, Cristo, dá!

[[v53-3-6]]

^<<v53-3-6,6>>^ Irmãos, em nome do nosso Senhor Jesus Cristo, ordenamos a vocês que se afastem de todos os irmãos que vivem sem trabalhar e que não seguem os ensinamentos que demos a eles.

[[v53-3-7]]

^<<v53-3-7,7>>^ Vocês sabem muito bem que devem seguir o nosso exemplo, pois não temos vivido entre vocês sem trabalhar.

[[v53-3-8]]

^<<v53-3-8,8>>^ Não temos recebido nada de ninguém, sem pagar; na verdade trabalhamos e nos cansamos. Trabalhamos sem parar, dia e noite, a fim de não sermos um peso para nenhum de vocês.

[[v53-3-9]]

^<<v53-3-9,9>>^ É claro que temos o direito de receber sustento; mas não temos pedido nada a fim de que vocês seguissem o nosso exemplo.

[[v53-3-10]]

^<<v53-3-10,10>>^ Porque, quando estávamos aí, demos esta regra: "Quem não quer trabalhar que não coma."

[[v53-3-11]]

^<<v53-3-11,11>>^ Estamos afirmando isso porque ouvimos dizer que há entre vocês algumas pessoas que vivem como os preguiçosos: não fazem nada e se metem na vida dos outros.

[[v53-3-12]]

^<<v53-3-12,12>>^ Em nome do Senhor Jesus Cristo, ordenamos com insistência a essas pessoas que vivam de um modo correto e trabalhem para se sustentar.

[[v53-3-13]]

^<<v53-3-13,13>>^ Mas vocês, irmãos, não se cansem de fazer o bem.

[[v53-3-14]]

^<<v53-3-14,14>>^ Se alguém não quiser obedecer ao que estamos mandando nesta carta, vejam bem quem está fazendo isso e se afastem dele para que fique envergonhado.

[[v53-3-15]]

^<<v53-3-15,15>>^ No entanto não o tratem como inimigo, mas o aconselhem como se aconselha um irmão.

[[v53-3-16]]

^<<v53-3-16,16>>^ Que o Senhor da paz dê a vocês a paz, sempre e de todas as maneiras! E que o Senhor esteja com todos vocês!

[[v53-3-17]]

^<<v53-3-17,17>>^ Com a minha própria mão escrevo isto: Saudações de Paulo.  É assim que assino todas as minhas cartas; é assim que escrevo.

[[v53-3-18]]

^<<v53-3-18,18>>^ Que a graça  do nosso Senhor Jesus Cristo esteja com todos vocês!

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[Próximo Capítulo &#62;]