include::./index.adoc[]

[[v19-4-0]]
=== Salmos, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-4-1]]

^<<v19-4-1,1>>^ Ó Deus, defensor dos meus direitos, responde-me quando eu te chamar! Eu estava em dificuldade, mas tu me ajudaste. Tem misericórdia de mim e ouve a minha oração!

[[v19-4-2]]

^<<v19-4-2,2>>^ Homens poderosos, até quando vocês vão me insultar? Até quando amarão o que não tem valor e andarão atrás de falsidades?

[[v19-4-3]]

^<<v19-4-3,3>>^ Lembrem que o Senhor  Deus trata com cuidado especial aqueles que são fiéis a ele; o Senhor  me ouve quando eu o chamo.

[[v19-4-4]]

^<<v19-4-4,4>>^ Tremam de medo e parem de pecar. Sozinhos e quietos nos seus quartos, examinem a sua própria consciência.

[[v19-4-5]]

^<<v19-4-5,5>>^ Ofereçam sacrifícios como o Senhor  exige e ponham a sua confiança nele.

[[v19-4-6]]

^<<v19-4-6,6>>^ Há muitas pessoas que oram assim: "Dá-nos mais bênçãos, ó Senhor  Deus, e olha para nós com bondade!"

[[v19-4-7]]

^<<v19-4-7,7>>^ Mas a felicidade que pões no meu coração é muito maior do que a daqueles que têm comida com fartura.

[[v19-4-8]]

^<<v19-4-8,8>>^ Quando me deito, durmo em paz, pois só tu, ó Senhor , me fazes viver em segurança.

'''

xref:019-salmos/019-salmos-003.adoc#v19-3-0[&#60; Capítulo Anterior] | <<v19-4-0,Topo>> | xref:019-salmos/019-salmos-005.adoc#v19-5-0[Próximo Capítulo &#62;]