include::./index.adoc[]

[[v19-9-0]]
=== Salmos, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-9-1]]

^<<v19-9-1,1>>^ Ó Senhor  Deus, eu te louvarei com todo o coração e contarei todas as coisas maravilhosas que tens feito.

[[v19-9-2]]

^<<v19-9-2,2>>^ Por causa de ti eu me alegrarei e ficarei feliz. Cantarei louvores a ti, ó Deus Altíssimo.

[[v19-9-3]]

^<<v19-9-3,3>>^ Quando apareces, os meus inimigos fogem; eles caem e morrem.

[[v19-9-4]]

^<<v19-9-4,4>>^ Tu és um juiz justo e, sentado no teu trono, fizeste justiça, julgando a meu favor.

[[v19-9-5]]

^<<v19-9-5,5>>^ Tu condenaste os pagãos e destruíste os maus; eles nunca mais serão lembrados.

[[v19-9-6]]

^<<v19-9-6,6>>^ Arrasaste as cidades dos nossos inimigos; elas foram destruídas para sempre, e eles estão completamente esquecidos.

[[v19-9-7]]

^<<v19-9-7,7>>^ Mas o Senhor  é Rei para sempre. Sentado no seu trono, ele faz os seus julgamentos.

[[v19-9-8]]

^<<v19-9-8,8>>^ Deus governa o mundo com justiça e julga os povos de acordo com o que é direito.

[[v19-9-9]]

^<<v19-9-9,9>>^ O Senhor  é um abrigo para os que são perseguidos; ele os protege em tempos de aflição.

[[v19-9-10]]

^<<v19-9-10,10>>^ Ó Senhor , aqueles que te conhecem confiam em ti, pois não abandonas os que procuram a tua ajuda.

[[v19-9-11]]

^<<v19-9-11,11>>^ Cantem louvores ao Senhor , que reina em Jerusalém. Anunciem às nações o que ele tem feito.

[[v19-9-12]]

^<<v19-9-12,12>>^ Pois Deus lembra dos que são perseguidos; ele não esquece os seus gemidos e castiga aqueles que os tratam com violência.

[[v19-9-13]]

^<<v19-9-13,13>>^ Ó Senhor  Deus, tem compaixão de mim! Vê como me fazem sofrer os que me odeiam. Livra-me da morte

[[v19-9-14]]

^<<v19-9-14,14>>^ a fim de que eu, na presença do povo de Jerusalém, possa me levantar para anunciar o motivo por que te louvo e dizer que sou feliz porque me salvaste da morte.

[[v19-9-15]]

^<<v19-9-15,15>>^ Os pagãos caíram na cova que fizeram; foram apanhados na armadilha que eles mesmos armaram.

[[v19-9-16]]

^<<v19-9-16,16>>^ O Senhor  se torna conhecido por causa dos seus julgamentos justos, e os maus caem nas suas próprias armadilhas.

[[v19-9-17]]

^<<v19-9-17,17>>^ Eles acabarão no mundo dos mortos ; para lá irão todos os que rejeitam a Deus.

[[v19-9-18]]

^<<v19-9-18,18>>^ Os pobres não serão esquecidos para sempre, e os necessitados não perderão para sempre a esperança.

[[v19-9-19]]

^<<v19-9-19,19>>^ Vem, ó Senhor , e não deixes que os seres humanos te desafiem! Põe os povos pagãos diante de ti e julga-os.

[[v19-9-20]]

^<<v19-9-20,20>>^ Faze, ó Senhor  Deus, com que sintam medo! Que eles fiquem sabendo que são simples criaturas mortais!

'''

xref:019-salmos/019-salmos-008.adoc#v19-8-0[&#60; Capítulo Anterior] | <<v19-9-0,Topo>> | xref:019-salmos/019-salmos-010.adoc#v19-10-0[Próximo Capítulo &#62;]