include::./index.adoc[]

[[v19-99-0]]
=== Salmos, 99
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-99-1]]

^<<v19-99-1,1>>^ O Senhor  Deus é Rei: os povos tremem. Ele está sentado no seu trono, que fica sobre os querubins ; a terra estremece.

[[v19-99-2]]

^<<v19-99-2,2>>^ O Senhor  é poderoso em Jerusalém; ele governa todos os povos.

[[v19-99-3]]

^<<v19-99-3,3>>^ Que todos o louvem por causa da sua grandeza e porque ele merece profundo respeito. O Senhor  Deus é santo.

[[v19-99-4]]

^<<v19-99-4,4>>^ Ó poderoso Rei, tu amas a justiça; tu a trouxeste ao povo de Israel, fazendo com que houvesse julgamentos justos e honestos.

[[v19-99-5]]

^<<v19-99-5,5>>^ Louvem o Senhor , nosso Deus, e se ajoelhem diante do seu trono. O Senhor  Deus é santo.

[[v19-99-6]]

^<<v19-99-6,6>>^ Moisés e Arão foram sacerdotes de Deus, e Samuel orava a ele; eles clamavam a Deus, o Senhor , e ele respondia.

[[v19-99-7]]

^<<v19-99-7,7>>^ Da coluna de nuvem, ele falava aos israelitas; eles obedeciam às leis  e aos mandamentos que ele lhes tinha dado.

[[v19-99-8]]

^<<v19-99-8,8>>^ Ó Senhor , nosso Deus, tu respondeste ao teu povo; tu mostraste que és Deus que perdoa, mas também que castiga as pessoas pelos seus pecados.

[[v19-99-9]]

^<<v19-99-9,9>>^ Louvem o Senhor , nosso Deus, e o adorem no seu monte santo . Pois o Senhor , nosso Deus, é santo.

'''

xref:019-salmos/019-salmos-098.adoc#v19-98-0[&#60; Capítulo Anterior] | <<v19-99-0,Topo>> | xref:019-salmos/019-salmos-100.adoc#v19-100-0[Próximo Capítulo &#62;]