include::./index.adoc[]

[[v19-7-0]]
=== Salmos, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-7-1]]

^<<v19-7-1,1>>^ Ó Senhor , meu Deus, em ti encontro segurança. Salva-me, livra-me de todos os que me perseguem.

[[v19-7-2]]

^<<v19-7-2,2>>^ Não permitas que eles, como um leão, me peguem e me despedacem, sem que ninguém possa me salvar.

[[v19-7-3]]

^<<v19-7-3,3>>^ Ó Senhor , meu Deus, se tenho feito qualquer uma destas coisas: se cometi alguma injustiça contra alguém,

[[v19-7-4]]

^<<v19-7-4,4>>^ se traí um amigo, se cometi sem motivo alguma violência contra o meu inimigo,

[[v19-7-5]]

^<<v19-7-5,5>>^ então que os meus inimigos me persigam e me agarrem! Que eles me deixem caído no chão, morto, e largado sem vida no pó!

[[v19-7-6]]

^<<v19-7-6,6>>^ Ó Senhor , levanta-te com ira e enfrenta a fúria dos meus inimigos! Levanta-te e ajuda-me, porque tu exiges que a justiça seja feita.

[[v19-7-7]]

^<<v19-7-7,7>>^ Ajunta todos os povos em volta de ti e, de cima, reina sobre eles.

[[v19-7-8]]

^<<v19-7-8,8>>^ Ó Senhor  Deus, tu és o juiz de todas as pessoas. Julga a meu favor, pois sou inocente e correto.

[[v19-7-9]]

^<<v19-7-9,9>>^ Eu te peço que acabes com a maldade dos maus e que recompenses os que são direitos. Pois tu és Deus justo e julgas os nossos pensamentos e desejos.

[[v19-7-10]]

^<<v19-7-10,10>>^ Deus me protege como um escudo ; ele salva os que são honestos de verdade.

[[v19-7-11]]

^<<v19-7-11,11>>^ Deus é um juiz justo; todos os dias ele condena os maus.

[[v19-7-12]]

^<<v19-7-12,12>>^ Se eles não se arrependerem, Deus afiará a sua espada. Ele já armou o seu arco para disparar flechas.

[[v19-7-13]]

^<<v19-7-13,13>>^ Ele pega as suas armas mortais e atira as suas flechas de fogo.

[[v19-7-14]]

^<<v19-7-14,14>>^ Vejam como os maus imaginam maldades. Eles planejam desgraças e vivem mentindo.

[[v19-7-15]]

^<<v19-7-15,15>>^ Armam armadilhas para pegarem os outros, mas eles mesmos caem nelas.

[[v19-7-16]]

^<<v19-7-16,16>>^ Assim eles são castigados pela sua própria maldade, são feridos pela sua própria violência.

[[v19-7-17]]

^<<v19-7-17,17>>^ Eu, porém, agradecerei a Deus a sua justiça e cantarei louvores ao Senhor , o Deus Altíssimo.

'''

xref:019-salmos/019-salmos-006.adoc#v19-6-0[&#60; Capítulo Anterior] | <<v19-7-0,Topo>> | xref:019-salmos/019-salmos-008.adoc#v19-8-0[Próximo Capítulo &#62;]