include::./index.adoc[]

[[v19-104-0]]
=== Salmos, 104
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-104-1]]

^<<v19-104-1,1>>^ Ó Senhor  Deus, que todo o meu ser te louve! Ó Senhor , meu Deus, como és grandioso! Estás vestido de majestade e de glória

[[v19-104-2]]

^<<v19-104-2,2>>^ e te cobres de luz. Estendes os céus como se fossem uma barraca

[[v19-104-3]]

^<<v19-104-3,3>>^ e constróis a tua casa sobre as águas lá de cima. Usas as nuvens como o teu carro de guerra e voas nas asas do vento.

[[v19-104-4]]

^<<v19-104-4,4>>^ Fazes com que os ventos sejam os teus mensageiros e com que os relâmpagos sejam os teus servidores.

[[v19-104-5]]

^<<v19-104-5,5>>^ Tu puseste a terra bem firme sobre os seus alicerces, e assim ela nunca será abalada.

[[v19-104-6]]

^<<v19-104-6,6>>^ Cobriste a terra com o oceano profundo, como se ele fosse uma capa , e as águas ficaram acima das montanhas.

[[v19-104-7]]

^<<v19-104-7,7>>^ Porém, quando repreendeste as águas, elas fugiram; quando ouviram o teu grito de comando, saíram correndo.

[[v19-104-8]]

^<<v19-104-8,8>>^ As águas correram pelos montes e desceram para os vales, indo ao lugar que preparaste para elas.

[[v19-104-9]]

^<<v19-104-9,9>>^ Tu puseste um limite para as águas a fim de que não cobrissem de novo a terra.

[[v19-104-10]]

^<<v19-104-10,10>>^ Tu fazes surgir nascentes nos vales, e os rios correm entre os montes.

[[v19-104-11]]

^<<v19-104-11,11>>^ Da sua água bebem todos os animais selvagens; com ela os jumentos selvagens matam a sede.

[[v19-104-12]]

^<<v19-104-12,12>>^ Nas margens dos rios, os pássaros fazem os seus ninhos e cantam entre os galhos das árvores.

[[v19-104-13]]

^<<v19-104-13,13>>^ Do céu tu envias chuvas para os montes, e a terra fica cheia das tuas bênçãos.

[[v19-104-14]]

^<<v19-104-14,14>>^ Fazes crescer capim para o gado e verduras e cereais para as pessoas, que assim tiram da terra o seu alimento.

[[v19-104-15]]

^<<v19-104-15,15>>^ Fazes a terra produzir o vinho, que deixa a gente feliz; o azeite, que alegra; e o pão, que dá forças.

[[v19-104-16]]

^<<v19-104-16,16>>^ Muita chuva cai sobre as árvores de Deus, o Senhor , sobre os cedros, que ele plantou nos montes Líbanos.

[[v19-104-17]]

^<<v19-104-17,17>>^ Ali os pássaros fazem os seus ninhos, e as cegonhas constroem as suas casas nos pinheiros.

[[v19-104-18]]

^<<v19-104-18,18>>^ Os cabritos selvagens vivem no alto das montanhas, e as lebres se escondem nos rochedos.

[[v19-104-19]]

^<<v19-104-19,19>>^ Tu fizeste a lua para marcar os meses; o sol sabe a hora de se pôr.

[[v19-104-20]]

^<<v19-104-20,20>>^ Tu fizeste a noite, e todos os animais selvagens saem quando escurece.

[[v19-104-21]]

^<<v19-104-21,21>>^ Os leões novos rugem enquanto caçam, procurando a comida que Deus dá.

[[v19-104-22]]

^<<v19-104-22,22>>^ Porém, quando o sol aparece, eles voltam e vão se deitar nas suas covas.

[[v19-104-23]]

^<<v19-104-23,23>>^ Então as pessoas saem para o serviço e trabalham até a tarde.

[[v19-104-24]]

^<<v19-104-24,24>>^ Ó Senhor , tu tens feito tantas coisas e foi com sabedoria que as fizeste. A terra está cheia das tuas criaturas.

[[v19-104-25]]

^<<v19-104-25,25>>^ Ali está o mar imenso, enorme, onde vivem animais grandes e pequenos, tantos, que não podem ser contados.

[[v19-104-26]]

^<<v19-104-26,26>>^ No mar passam os navios, e nele brinca Leviatã , o monstro marinho que tu criaste.

[[v19-104-27]]

^<<v19-104-27,27>>^ Todos esses animais dependem de ti, esperando que lhes dês alimento no tempo certo.

[[v19-104-28]]

^<<v19-104-28,28>>^ Tu dás a comida, e eles comem e ficam satisfeitos.

[[v19-104-29]]

^<<v19-104-29,29>>^ Quando escondes o rosto, ficam com medo; se cortas a respiração que lhes dás, eles morrem e voltam ao pó de onde saíram.

[[v19-104-30]]

^<<v19-104-30,30>>^ Porém, quando lhes dás o sopro de vida, eles nascem; e assim dás vida nova à terra.

[[v19-104-31]]

^<<v19-104-31,31>>^ Que a glória de Deus, o Senhor , dure para sempre! Que ele se alegre com aquilo que fez!

[[v19-104-32]]

^<<v19-104-32,32>>^ O Senhor  olha para a terra, e ela treme; toca nas montanhas, e elas soltam fumaça.

[[v19-104-33]]

^<<v19-104-33,33>>^ Cantarei louvores ao Senhor enquanto eu viver; cantarei ao meu Deus a vida inteira.

[[v19-104-34]]

^<<v19-104-34,34>>^ Que o Senhor  fique contente com a minha canção, pois é dele que vem a minha alegria!

[[v19-104-35]]

^<<v19-104-35,35>>^ Que desapareçam da terra aqueles que não querem saber de Deus, e que os maus deixem de existir! Que todo o meu ser te louve, ó Senhor  Deus! Aleluia !

'''

xref:019-salmos/019-salmos-103.adoc#v19-103-0[&#60; Capítulo Anterior] | <<v19-104-0,Topo>> | xref:019-salmos/019-salmos-105.adoc#v19-105-0[Próximo Capítulo &#62;]