include::./index.adoc[]

[[v19-53-0]]
=== Salmos, 53
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-53-1]]

^<<v19-53-1,1>>^ Os tolos pensam assim: "Para mim, Deus não tem importância." Todos são corruptos e cometem injustiças horríveis; não há uma só pessoa que faça o bem.

[[v19-53-2]]

^<<v19-53-2,2>>^ Lá do céu Deus olha para a humanidade a fim de ver se existe alguém que tenha juízo, se existe uma só pessoa que o adore.

[[v19-53-3]]

^<<v19-53-3,3>>^ Mas todos caíram, se desviando assim do caminho certo, e são igualmente corruptos. Não há mais ninguém que faça o que é direito, não há mesmo nem uma só pessoa.

[[v19-53-4]]

^<<v19-53-4,4>>^ Deus pergunta: "Será que essa gente má não entende nada? Eles vivem explorando o meu povo e, além de tudo, não oram a mim."

[[v19-53-5]]

^<<v19-53-5,5>>^ Mas eles vão tremer de medo como nunca tremeram antes, pois Deus espalha os ossos dos inimigos dele. Deus os rejeitou, e por isso o povo de Israel os derrotará completamente.

[[v19-53-6]]

^<<v19-53-6,6>>^ Queira Deus que de Jerusalém venha a vitória para Israel! Como ficarão felizes e alegres os descendentes de Jacó quando Deus os fizer prosperar de novo!

'''

xref:019-salmos/019-salmos-052.adoc#v19-52-0[&#60; Capítulo Anterior] | <<v19-53-0,Topo>> | xref:019-salmos/019-salmos-054.adoc#v19-54-0[Próximo Capítulo &#62;]