include::./index.adoc[]

[[v19-58-0]]
=== Salmos, 58
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-58-1]]

^<<v19-58-1,1>>^ Será que vocês, autoridades, dão sentenças justas? Será que julgam com justiça as pessoas?

[[v19-58-2]]

^<<v19-58-2,2>>^ Não. Vocês só pensam em fazer o mal e cometem crimes de violência no país.

[[v19-58-3]]

^<<v19-58-3,3>>^ Os maus passam a vida praticando o mal; desde o dia em que nascem, só contam mentiras.

[[v19-58-4]]

^<<v19-58-4,4>>^ Estão cheios de veneno como as cobras; tapam os ouvidos como uma cobra que se faz de surda,

[[v19-58-5]]

^<<v19-58-5,5>>^ que não quer ouvir a voz do encantador de serpentes.

[[v19-58-6]]

^<<v19-58-6,6>>^ Ó Deus, quebra os dentes dos maus! Ó Senhor  Deus, arranca os dentes desses leões ferozes!

[[v19-58-7]]

^<<v19-58-7,7>>^ Que os maus desapareçam como a água derramada na terra! Que sejam esmagados como a erva que nasce no caminho!

[[v19-58-8]]

^<<v19-58-8,8>>^ Que se derretam como o caracol na lama! Que sejam como a criança que nasce morta, que nunca viu a luz do sol!

[[v19-58-9]]

^<<v19-58-9,9>>^ Antes que os maus percebam o que está acontecendo, serão cortados como mato. Enquanto ainda estiverem vivos, Deus, em sua fúria terrível, os expulsará com um sopro.

[[v19-58-10]]

^<<v19-58-10,10>>^ Os bons ficarão contentes ao verem os maus sendo castigados; os bons lavarão os pés no sangue deles.

[[v19-58-11]]

^<<v19-58-11,11>>^ E as pessoas dirão: "De fato, os bons são recompensados. Realmente existe um Deus que julga o mundo."

'''

xref:019-salmos/019-salmos-057.adoc#v19-57-0[&#60; Capítulo Anterior] | <<v19-58-0,Topo>> | xref:019-salmos/019-salmos-059.adoc#v19-59-0[Próximo Capítulo &#62;]