include::./index.adoc[]

[[v19-116-0]]
=== Salmos, 116
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-116-1]]

^<<v19-116-1,1>>^ Eu amo a Deus, o Senhor , porque ele me ouve; ele escuta as minhas orações.

[[v19-116-2]]

^<<v19-116-2,2>>^ Ele me ouve sempre que eu clamo pedindo socorro.

[[v19-116-3]]

^<<v19-116-3,3>>^ Os laços da morte estavam me apertando, os horrores da sepultura tomaram conta de mim, e eu fiquei aflito e apavorado.

[[v19-116-4]]

^<<v19-116-4,4>>^ Então clamei ao Senhor , pedindo: "Ó Senhor  Deus, eu te peço: Salva-me da morte!"

[[v19-116-5]]

^<<v19-116-5,5>>^ O Senhor  é bondoso e fiel; o nosso Deus tem compaixão de nós.

[[v19-116-6]]

^<<v19-116-6,6>>^ O Senhor  protege os que não podem se defender. Quando eu estava em perigo, ele me salvou.

[[v19-116-7]]

^<<v19-116-7,7>>^ Meu ser inteiro, continue confiando em Deus, o Senhor , pois ele tem sido bom para mim!

[[v19-116-8]]

^<<v19-116-8,8>>^ Deus me livrou da morte, fez parar as minhas lágrimas e não deixou que eu caísse na desgraça.

[[v19-116-9]]

^<<v19-116-9,9>>^ Por isso, no mundo dos que estão vivos, viverei uma vida de obediência a ele.

[[v19-116-10]]

^<<v19-116-10,10>>^ Eu continuei crendo, mesmo quando disse: "estou completamente esmagado."

[[v19-116-11]]

^<<v19-116-11,11>>^ Não parei de crer, mesmo quando afirmei, sem pensar: "não se pode confiar em ninguém."

[[v19-116-12]]

^<<v19-116-12,12>>^ Que posso eu oferecer a Deus, o Senhor , por tudo de bom que ele me tem dado?

[[v19-116-13]]

^<<v19-116-13,13>>^ Levarei ao Senhor  uma oferta de vinho para lhe dar graças porque me salvou.

[[v19-116-14]]

^<<v19-116-14,14>>^ Na reunião de todo o seu povo eu lhe darei o que prometi.

[[v19-116-15]]

^<<v19-116-15,15>>^ O Senhor  Deus sente pesar quando vê morrerem os que são fiéis a ele.

[[v19-116-16]]

^<<v19-116-16,16>>^ Ó Senhor , eu sou teu servo ; eu te sirvo, como te servia a minha mãe. Tu me livraste da morte.

[[v19-116-17]]

^<<v19-116-17,17>>^ Eu te darei uma oferta de gratidão e a ti farei as minhas orações.

[[v19-116-18]]

^<<v19-116-18,18>>^ Na reunião de todo o teu povo, nos pátios do teu Templo, em Jerusalém, eu te darei o que prometi. Aleluia !

'''

xref:019-salmos/019-salmos-115.adoc#v19-115-0[&#60; Capítulo Anterior] | <<v19-116-0,Topo>> | xref:019-salmos/019-salmos-117.adoc#v19-117-0[Próximo Capítulo &#62;]