include::./index.adoc[]

[[v19-19-0]]
=== Salmos, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-19-1]]

^<<v19-19-1,1>>^ O céu anuncia a glória  de Deus e nos mostra aquilo que as suas mãos fizeram.

[[v19-19-2]]

^<<v19-19-2,2>>^ Cada dia fala dessa glória ao dia seguinte, e cada noite repete isso à outra noite.

[[v19-19-3]]

^<<v19-19-3,3>>^ Não há discurso nem palavras, e não se ouve nenhum som.

[[v19-19-4]]

^<<v19-19-4,4>>^ No entanto, a voz do céu se espalha pelo mundo inteiro, e as suas palavras alcançam a terra toda. Deus armou no céu uma barraca para o sol.

[[v19-19-5]]

^<<v19-19-5,5>>^ O sol sai dali todo alegre como um noivo, como um atleta ansioso para entrar numa corrida.

[[v19-19-6]]

^<<v19-19-6,6>>^ O sol sai de um lado do céu e vai até o outro lado; nada pode se esconder do seu calor.

[[v19-19-7]]

^<<v19-19-7,7>>^ A lei  do Senhor  é perfeita e nos dá novas forças. Os seus conselhos merecem confiança e dão sabedoria às pessoas simples.

[[v19-19-8]]

^<<v19-19-8,8>>^ Os ensinos do Senhor  são certos e alegram o coração. Os seus ensinamentos são claros e iluminam a nossa mente.

[[v19-19-9]]

^<<v19-19-9,9>>^ O temor  ao Senhor  é bom e dura para sempre. Os seus julgamentos são justos e sempre se baseiam na verdade.

[[v19-19-10]]

^<<v19-19-10,10>>^ Os seus ensinos são mais preciosos do que o ouro, até mesmo do que muito ouro fino. São mais doces do que o mel, mais doces até do que o mel mais puro.

[[v19-19-11]]

^<<v19-19-11,11>>^ Senhor, os teus ensinamentos dão sabedoria a mim, teu servo , e eu sou recompensado quando lhes obedeço.

[[v19-19-12]]

^<<v19-19-12,12>>^ Quem pode ver os seus próprios erros? Purifica-me, Senhor, das faltas que cometo sem perceber.

[[v19-19-13]]

^<<v19-19-13,13>>^ Livra-me também dos pecados que cometo por vontade própria; não permitas que eles me dominem. Assim serei uma pessoa direita e ficarei livre do grave pecado da desobediência a ti.

[[v19-19-14]]

^<<v19-19-14,14>>^ Que as minhas palavras e os meus pensamentos sejam aceitáveis a ti, ó Senhor  Deus, minha rocha e meu defensor!

'''

xref:019-salmos/019-salmos-018.adoc#v19-18-0[&#60; Capítulo Anterior] | <<v19-19-0,Topo>> | xref:019-salmos/019-salmos-020.adoc#v19-20-0[Próximo Capítulo &#62;]