include::./index.adoc[]

[[v19-102-0]]
=== Salmos, 102
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-102-1]]

^<<v19-102-1,1>>^ Ó Senhor , ouve a minha oração e escuta o meu grito pedindo socorro!

[[v19-102-2]]

^<<v19-102-2,2>>^ Não te escondas de mim quando estou aflito. Ouve-me quando eu te chamar e responde depressa.

[[v19-102-3]]

^<<v19-102-3,3>>^ A minha vida está desaparecendo como fumaça, e o meu corpo queima como se estivesse no fogo.

[[v19-102-4]]

^<<v19-102-4,4>>^ Estou acabado como a grama que foi cortada e pisada; não tenho nem vontade de comer.

[[v19-102-5]]

^<<v19-102-5,5>>^ Fico gemendo alto; sou apenas pele e osso.

[[v19-102-6]]

^<<v19-102-6,6>>^ Sou como um pássaro em lugares desertos, como uma coruja numa casa abandonada.

[[v19-102-7]]

^<<v19-102-7,7>>^ Não consigo dormir; sou como um pássaro solitário em cima do telhado.

[[v19-102-8]]

^<<v19-102-8,8>>^ Os meus inimigos me insultam o dia todo; aqueles que zombam de mim usam o meu nome para rogar pragas.

[[v19-102-9]]

^<<v19-102-9,9>>^ Por causa da tua ira  e do teu furor, as cinzas são a minha comida, e as lágrimas se misturam com a minha bebida. Tu me pegaste e me jogaste fora.

[[v19-102-10]]

^<<v19-102-10,10>>^ Por causa da tua ira  e do teu furor,

[[v19-102-11]]

^<<v19-102-11,11>>^ A minha vida é como as sombras do anoitecer; vou secando como o capim.

[[v19-102-12]]

^<<v19-102-12,12>>^ Mas tu, ó Senhor  Deus, és Rei para sempre; todas as gerações  futuras lembrarão de ti.

[[v19-102-13]]

^<<v19-102-13,13>>^ Tu te levantarás e terás pena de Jerusalém. Já é hora de teres compaixão dela, a hora certa já chegou.

[[v19-102-14]]

^<<v19-102-14,14>>^ Ainda que ela esteja destruída, os teus servos  a amam; eles têm compaixão dela, embora esteja arrasada.

[[v19-102-15]]

^<<v19-102-15,15>>^ As nações temerão  o Senhor ; todos os reis do mundo temerão o seu poder.

[[v19-102-16]]

^<<v19-102-16,16>>^ Quando o Senhor tornar a construir Jerusalém, ele mostrará a sua glória .

[[v19-102-17]]

^<<v19-102-17,17>>^ Ele ouvirá o seu povo abandonado e escutará a sua oração.

[[v19-102-18]]

^<<v19-102-18,18>>^ Que isso fique escrito para que os nossos descendentes saibam o que o Senhor  Deus fez e para que o louvem aqueles que ainda vão nascer!

[[v19-102-19]]

^<<v19-102-19,19>>^ Do seu lugar santo, nas alturas, o Senhor  olhou; do céu ele olhou para a terra

[[v19-102-20]]

^<<v19-102-20,20>>^ a fim de ouvir os gemidos dos prisioneiros e libertar os que tinham sido condenados à morte.

[[v19-102-21]]

^<<v19-102-21,21>>^ Por isso, o Senhor  Deus será louvado em Jerusalém, e a sua fama será anunciada ali

[[v19-102-22]]

^<<v19-102-22,22>>^ quando as nações e os reinos se reunirem para adorá-lo.

[[v19-102-23]]

^<<v19-102-23,23>>^ Ainda sou moço, mas Deus me tirou as forças e encurtou a minha vida.

[[v19-102-24]]

^<<v19-102-24,24>>^ Ó meu Deus, tu que vives para sempre, não me leves agora, antes que eu envelheça!

[[v19-102-25]]

^<<v19-102-25,25>>^ No começo, criaste a terra e, com as tuas próprias mãos, fizeste o céu.

[[v19-102-26]]

^<<v19-102-26,26>>^ A terra e o céu vão acabar, mas tu viverás para sempre. A terra e o céu se gastarão como roupas. Tu os trocarás como se troca de roupa, e eles serão jogados fora.

[[v19-102-27]]

^<<v19-102-27,27>>^ Mas tu és sempre o mesmo, e a tua vida não tem fim.

'''

xref:019-salmos/019-salmos-101.adoc#v19-101-0[&#60; Capítulo Anterior] | <<v19-102-0,Topo>> | xref:019-salmos/019-salmos-103.adoc#v19-103-0[Próximo Capítulo &#62;]