include::./index.adoc[]

[[v19-90-0]]
=== Salmos, 90
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-90-1]]

^<<v19-90-1,1>>^ Senhor, tu sempre tens sido o nosso refúgio.

[[v19-90-2]]

^<<v19-90-2,2>>^ Antes de formares os montes e de começares a criar a terra e o Universo , tu és Deus eternamente, no passado, no presente e no futuro.

[[v19-90-3]]

^<<v19-90-3,3>>^ Tu dizes aos seres humanos que voltem a ser o que eram antes; tu fazes com que novamente virem pó.

[[v19-90-4]]

^<<v19-90-4,4>>^ Diante de ti, mil anos são como um dia, como o dia de ontem, que já passou; são como uma hora noturna que passa depressa.

[[v19-90-5]]

^<<v19-90-5,5>>^ Tu acabas com a vida das pessoas; elas não duram mais do que um sonho. São como a erva que brota de manhã,

[[v19-90-6]]

^<<v19-90-6,6>>^ que cresce e abre em flor e de tarde seca e morre.

[[v19-90-7]]

^<<v19-90-7,7>>^ Nós somos destruídos pela tua ira , e o teu furor nos deixa apavorados.

[[v19-90-8]]

^<<v19-90-8,8>>^ Tu pões as nossas maldades diante de ti e, com a tua luz, examinas os nossos pecados secretos.

[[v19-90-9]]

^<<v19-90-9,9>>^ De repente, os nossos dias são cortados pela tua ira; a nossa vida termina como um sopro.

[[v19-90-10]]

^<<v19-90-10,10>>^ Só vivemos uns setenta anos, e os mais fortes chegam aos oitenta, mas esses anos só trazem canseira e aflições. A vida passa logo, e nós desaparecemos.

[[v19-90-11]]

^<<v19-90-11,11>>^ Quem já sentiu o grande poder da tua ira? Quem conhece o medo que o teu furor produz?

[[v19-90-12]]

^<<v19-90-12,12>>^ Faze com que saibamos como são poucos os dias da nossa vida para que tenhamos um coração sábio.

[[v19-90-13]]

^<<v19-90-13,13>>^ Olha de novo para nós, ó Senhor  Deus! Até quando vai durar a tua ira? Tem compaixão dos teus servos .

[[v19-90-14]]

^<<v19-90-14,14>>^ Alimenta-nos de manhã com o teu amor, até ficarmos satisfeitos, para que cantemos e nos alegremos a vida inteira.

[[v19-90-15]]

^<<v19-90-15,15>>^ Dá-nos agora muita felicidade assim como nos deste muita tristeza no passado, naqueles anos em que tivemos aflições.

[[v19-90-16]]

^<<v19-90-16,16>>^ Que os teus servos vejam as grandes coisas que fazes! E que os nossos descendentes vejam o teu glorioso  poder!

[[v19-90-17]]

^<<v19-90-17,17>>^ Derrama sobre nós as tuas bênçãos, ó Senhor, nosso Deus! Dá-nos sucesso em tudo o que fizermos; sim, dá-nos sucesso em tudo.

'''

xref:019-salmos/019-salmos-089.adoc#v19-89-0[&#60; Capítulo Anterior] | <<v19-90-0,Topo>> | xref:019-salmos/019-salmos-091.adoc#v19-91-0[Próximo Capítulo &#62;]