include::./index.adoc[]

[[v19-119-0]]
=== Salmos, 119
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-119-1]]

^<<v19-119-1,1>>^ Felizes são os que não podem ser acusados de nada, que vivem de acordo com a lei de Deus, o Senhor !

[[v19-119-2]]

^<<v19-119-2,2>>^ Felizes os que guardam os mandamentos de Deus e lhe obedecem de todo o coração!

[[v19-119-3]]

^<<v19-119-3,3>>^ Felizes os que não praticam o mal, os que andam nos caminhos de Deus!

[[v19-119-4]]

^<<v19-119-4,4>>^ Tu, ó Deus, nos deste as tuas leis e mandaste que as cumpríssemos fielmente.

[[v19-119-5]]

^<<v19-119-5,5>>^ Como desejo obedecer às tuas ordens e cumpri-las com fidelidade!

[[v19-119-6]]

^<<v19-119-6,6>>^ Se eu der atenção a todos os teus mandamentos, não passarei vergonha.

[[v19-119-7]]

^<<v19-119-7,7>>^ Com um coração sincero eu te louvarei à medida que for aprendendo os teus justos ensinamentos.

[[v19-119-8]]

^<<v19-119-8,8>>^ Obedecerei às tuas leis ; peço-te que não me abandones nunca.

[[v19-119-9]]

^<<v19-119-9,9>>^ Como pode um jovem conservar pura a sua vida? É só obedecer aos teus mandamentos.

[[v19-119-10]]

^<<v19-119-10,10>>^ Eu procuro te servir de todo o coração; não deixes que eu me desvie dos teus mandamentos.

[[v19-119-11]]

^<<v19-119-11,11>>^ Guardo a tua palavra no meu coração para não pecar contra ti.

[[v19-119-12]]

^<<v19-119-12,12>>^ Eu te louvo, ó Senhor  Deus! Ensina-me as tuas leis .

[[v19-119-13]]

^<<v19-119-13,13>>^ Costumo repetir em voz alta todas as ordens que tens dado.

[[v19-119-14]]

^<<v19-119-14,14>>^ Fico mais alegre em seguir os teus mandamentos do que em ser muito rico.

[[v19-119-15]]

^<<v19-119-15,15>>^ Estudo as tuas leis e examino os teus ensinamentos.

[[v19-119-16]]

^<<v19-119-16,16>>^ As tuas leis são o meu prazer; não esqueço a tua palavra.

[[v19-119-17]]

^<<v19-119-17,17>>^ Senhor, trata com bondade este teu servo , para que eu possa continuar vivo e obedecer à tua palavra!

[[v19-119-18]]

^<<v19-119-18,18>>^ Abre os meus olhos para que eu possa ver as verdades maravilhosas da tua lei .

[[v19-119-19]]

^<<v19-119-19,19>>^ Viverei poucos anos aqui na terra; não escondas de mim os teus mandamentos.

[[v19-119-20]]

^<<v19-119-20,20>>^ O meu coração sofre, ansioso, pois, em todos os momentos, quero conhecer a tua vontade.

[[v19-119-21]]

^<<v19-119-21,21>>^ Tu repreendes os orgulhosos; os que se desviam dos teus mandamentos são malditos.

[[v19-119-22]]

^<<v19-119-22,22>>^ Livra-me dos insultos e das zombarias deles, pois tenho obedecido aos teus ensinamentos.

[[v19-119-23]]

^<<v19-119-23,23>>^ Mesmo que as autoridades se reúnam e contra mim façam planos, eu, que sou teu servo, meditarei nas tuas leis.

[[v19-119-24]]

^<<v19-119-24,24>>^ Gosto de pensar nos teus ensinamentos; eles são os meus conselheiros.

[[v19-119-25]]

^<<v19-119-25,25>>^ Estou derrotado e caído no chão; de acordo com a tua promessa, dá-me novas forças.

[[v19-119-26]]

^<<v19-119-26,26>>^ Contei tudo o que tenho feito, e tu me respondeste; ensina-me os teus mandamentos.

[[v19-119-27]]

^<<v19-119-27,27>>^ Ajuda-me a compreender as tuas leis , e eu meditarei nos teus maravilhosos ensinamentos.

[[v19-119-28]]

^<<v19-119-28,28>>^ É tanta a minha tristeza, que estou me acabando; dá-me forças, como prometeste.

[[v19-119-29]]

^<<v19-119-29,29>>^ Não me deixes seguir o caminho errado; com a tua bondade, ensina-me a tua lei.

[[v19-119-30]]

^<<v19-119-30,30>>^ Eu escolhi o caminho da fidelidade e tenho dado atenção às tuas ordens.

[[v19-119-31]]

^<<v19-119-31,31>>^ Ó Senhor  Deus, tenho seguido os teus ensinamentos; não me deixes passar pela vergonha do fracasso.

[[v19-119-32]]

^<<v19-119-32,32>>^ Eu me apresso em obedecer aos teus mandamentos porque assim tu me darás mais entendimento.

[[v19-119-33]]

^<<v19-119-33,33>>^ Ó Senhor  Deus, ensina-me a entender as tuas leis , e eu sempre as seguirei.

[[v19-119-34]]

^<<v19-119-34,34>>^ Dá-me entendimento para que eu possa guardar a tua lei e cumpri-la de todo o coração.

[[v19-119-35]]

^<<v19-119-35,35>>^ Guia-me pelo caminho dos teus mandamentos, pois neles encontro a felicidade.

[[v19-119-36]]

^<<v19-119-36,36>>^ Faze com que eu queira obedecer aos teus ensinamentos, em vez de querer ajuntar riquezas.

[[v19-119-37]]

^<<v19-119-37,37>>^ Não me deixes ficar pensando em coisas sem valor; sê bondoso para comigo, como prometeste.

[[v19-119-38]]

^<<v19-119-38,38>>^ Eu sou teu servo ; cumpre a promessa que me fizeste, a promessa que fazes aos que te temem .

[[v19-119-39]]

^<<v19-119-39,39>>^ Livra-me dos insultos, que me causam medo; os teus julgamentos são bons.

[[v19-119-40]]

^<<v19-119-40,40>>^ Eu quero muito obedecer às tuas leis. Conserva-me vivo, pois tu és justo.

[[v19-119-41]]

^<<v19-119-41,41>>^ Ó Senhor  Deus, mostra-me o quanto me amas e livra-me dos meus inimigos, de acordo com a tua promessa!

[[v19-119-42]]

^<<v19-119-42,42>>^ Então saberei responder aos que me insultam, pois eu confio na tua palavra.

[[v19-119-43]]

^<<v19-119-43,43>>^ Ajuda-me a falar sempre a verdade, pois a minha esperança está nos teus julgamentos.

[[v19-119-44]]

^<<v19-119-44,44>>^ Todos os dias obedecerei à tua lei ; eu sempre a cumprirei.

[[v19-119-45]]

^<<v19-119-45,45>>^ Viverei à vontade, livre de perigos, porque tenho procurado seguir os teus ensinamentos.

[[v19-119-46]]

^<<v19-119-46,46>>^ Anunciarei aos reis as tuas ordens e não ficarei envergonhado.

[[v19-119-47]]

^<<v19-119-47,47>>^ Os teus mandamentos me trazem alegria, pois eu os amo.

[[v19-119-48]]

^<<v19-119-48,48>>^ Respeito e amo os teus mandamentos e medito nas tuas leis.

[[v19-119-49]]

^<<v19-119-49,49>>^ Lembra da promessa que fizeste a mim, este teu servo , a promessa que tem sido a minha esperança.

[[v19-119-50]]

^<<v19-119-50,50>>^ No sofrimento, eu fui consolado porque a tua promessa me deu vida.

[[v19-119-51]]

^<<v19-119-51,51>>^ Os orgulhosos estão sempre zombando de mim, mas eu não tenho me afastado da tua lei .

[[v19-119-52]]

^<<v19-119-52,52>>^ Eu lembro dos teus julgamentos do passado, e eles me confortam, ó Senhor .

[[v19-119-53]]

^<<v19-119-53,53>>^ Fico muito revoltado quando vejo os maus quebrando a tua lei.

[[v19-119-54]]

^<<v19-119-54,54>>^ Na minha curta vida aqui na terra, faço canções sobre os teus mandamentos.

[[v19-119-55]]

^<<v19-119-55,55>>^ De noite, eu penso em ti, ó Senhor  Deus, e medito na tua lei.

[[v19-119-56]]

^<<v19-119-56,56>>^ O meu dever nesta vida é este: obedecer aos teus mandamentos.

[[v19-119-57]]

^<<v19-119-57,57>>^ Tu, ó Senhor  Deus, és tudo o que eu tenho; prometo obedecer às tuas leis .

[[v19-119-58]]

^<<v19-119-58,58>>^ De todo o coração, eu te peço: tem misericórdia de mim, como prometeste.

[[v19-119-59]]

^<<v19-119-59,59>>^ Tenho pensado na minha maneira de agir e prometo seguir os teus ensinamentos.

[[v19-119-60]]

^<<v19-119-60,60>>^ Com toda a pressa e sem demora, procuro obedecer aos teus mandamentos.

[[v19-119-61]]

^<<v19-119-61,61>>^ Os maus armaram uma armadilha para me pegar, mas eu não esqueço a tua lei.

[[v19-119-62]]

^<<v19-119-62,62>>^ Por causa dos teus ensinamentos justos, eu me levanto no meio da noite para te louvar.

[[v19-119-63]]

^<<v19-119-63,63>>^ Eu sou amigo de todos os que te temem , de todos os que obedecem às tuas leis.

[[v19-119-64]]

^<<v19-119-64,64>>^ Ó Senhor  Deus, a terra está cheia do teu amor; ensina-me os teus mandamentos.

[[v19-119-65]]

^<<v19-119-65,65>>^ Ó Senhor  Deus, tu cumpriste a tua promessa e tens sido bom para mim, este teu servo .

[[v19-119-66]]

^<<v19-119-66,66>>^ Dá-me sabedoria e conhecimento, pois confio nos teus mandamentos.

[[v19-119-67]]

^<<v19-119-67,67>>^ Antes de me castigares, eu andava errado, mas agora obedeço à tua palavra.

[[v19-119-68]]

^<<v19-119-68,68>>^ Ó Deus, tu és bom e fazes o bem; ensina-me os teus mandamentos.

[[v19-119-69]]

^<<v19-119-69,69>>^ Os orgulhosos dizem mentiras contra mim, mas eu, de todo o coração, obedeço aos teus mandamentos.

[[v19-119-70]]

^<<v19-119-70,70>>^ Esses homens não querem aprender a tua lei , porém eu tenho prazer nela.

[[v19-119-71]]

^<<v19-119-71,71>>^ Foi bom que eu tivesse sido castigado, pois assim aprendi os teus mandamentos.

[[v19-119-72]]

^<<v19-119-72,72>>^ A tua lei vale muito mais para mim do que toda a riqueza do mundo.

[[v19-119-73]]

^<<v19-119-73,73>>^ Ó Deus, as tuas mãos me criaram e me formaram; dá-me entendimento para que eu possa aprender as tuas leis .

[[v19-119-74]]

^<<v19-119-74,74>>^ Aqueles que te temem  se alegram quando me veem porque a minha esperança está na tua palavra.

[[v19-119-75]]

^<<v19-119-75,75>>^ Ó Senhor  Deus, eu sei que os teus julgamentos são justos e que me castigas porque és fiel.

[[v19-119-76]]

^<<v19-119-76,76>>^ Peço que o teu amor me console, como prometeste a mim, este teu servo !

[[v19-119-77]]

^<<v19-119-77,77>>^ Tem compaixão de mim, e eu continuarei vivo, pois gosto de pensar na tua lei.

[[v19-119-78]]

^<<v19-119-78,78>>^ Que os orgulhosos fiquem envergonhados, pois me acusam com mentiras! Mas eu meditarei nos teus ensinamentos.

[[v19-119-79]]

^<<v19-119-79,79>>^ Que venham para o meu lado os que te temem, os que conhecem os teus mandamentos!

[[v19-119-80]]

^<<v19-119-80,80>>^ Que eu obedeça completamente aos teus mandamentos e não sofra a vergonha do fracasso!

[[v19-119-81]]

^<<v19-119-81,81>>^ Ó Deus, estou aflito, esperando que tu me livres dos meus inimigos; eu ponho a minha esperança na tua palavra.

[[v19-119-82]]

^<<v19-119-82,82>>^ Os meus olhos estão cansados de tanto olhar, esperando o que prometeste, e eu pergunto: "Quando vens me consolar?"

[[v19-119-83]]

^<<v19-119-83,83>>^ Sou tão inútil como um odre cheio de furos, porém não esqueço os teus mandamentos.

[[v19-119-84]]

^<<v19-119-84,84>>^ Até quando vai este teu servo ter de esperar? Quando vais castigar os que me perseguem?

[[v19-119-85]]

^<<v19-119-85,85>>^ Os orgulhosos, que não obedecem à tua lei , cavaram covas para me pegar.

[[v19-119-86]]

^<<v19-119-86,86>>^ Todos os teus mandamentos merecem confiança. Ajuda-me, pois sou perseguido por mentirosos.

[[v19-119-87]]

^<<v19-119-87,87>>^ Eles quase conseguiram me matar, porém eu não abandono os teus ensinamentos.

[[v19-119-88]]

^<<v19-119-88,88>>^ Por causa do teu amor, livra-me da morte para que eu possa obedecer aos teus mandamentos.

[[v19-119-89]]

^<<v19-119-89,89>>^ Ó Senhor  Deus, a tua palavra dura para sempre; ela é firme como o céu.

[[v19-119-90]]

^<<v19-119-90,90>>^ A tua fidelidade permanece em todas as gerações ; tu colocaste a terra no seu lugar, e ela fica firme.

[[v19-119-91]]

^<<v19-119-91,91>>^ De acordo com as tuas ordens todas as coisas permanecem até hoje, pois tudo te obedece.

[[v19-119-92]]

^<<v19-119-92,92>>^ Se a tua lei  não tivesse sido o motivo da minha alegria, eu já teria morrido de tanto sofrer.

[[v19-119-93]]

^<<v19-119-93,93>>^ Nunca esquecerei os teus ensinamentos, pois é por meio deles que tens conservado a minha vida.

[[v19-119-94]]

^<<v19-119-94,94>>^ Livra-me dos meus inimigos, pois sou teu e tenho procurado obedecer aos teus mandamentos.

[[v19-119-95]]

^<<v19-119-95,95>>^ Os maus estão esperando a hora de me matarem, mas eu meditarei nas tuas leis.

[[v19-119-96]]

^<<v19-119-96,96>>^ Tenho visto que todas as coisas têm o seu limite, mas o teu mandamento se aplica a tudo.

[[v19-119-97]]

^<<v19-119-97,97>>^ Como eu amo a tua lei ! Penso nela o dia todo.

[[v19-119-98]]

^<<v19-119-98,98>>^ O teu mandamento está sempre comigo e faz com que eu seja mais sábio do que os meus inimigos.

[[v19-119-99]]

^<<v19-119-99,99>>^ Eu entendo mais do que todos os meus professores porque medito nos teus ensinamentos.

[[v19-119-100]]

^<<v19-119-100,100>>^ Tenho mais sabedoria do que os velhos porque obedeço aos teus mandamentos.

[[v19-119-101]]

^<<v19-119-101,101>>^ Não tenho andado pelos caminhos da maldade, pois quero obedecer à tua palavra.

[[v19-119-102]]

^<<v19-119-102,102>>^ Não tenho deixado de cumprir as tuas ordens porque és tu que me ensinas.

[[v19-119-103]]

^<<v19-119-103,103>>^ Como são doces as tuas palavras! São mais doces do que o mel.

[[v19-119-104]]

^<<v19-119-104,104>>^ Por meio das tuas leis , consigo a sabedoria e assim detesto todos os caminhos da mentira.

[[v19-119-105]]

^<<v19-119-105,105>>^ A tua palavra é lâmpada para guiar os meus passos, é luz que ilumina o meu caminho.

[[v19-119-106]]

^<<v19-119-106,106>>^ Cumprirei o juramento que fiz de seguir os teus justos ensinamentos.

[[v19-119-107]]

^<<v19-119-107,107>>^ Ó Senhor  Deus, os meus sofrimentos são terríveis; conserva-me vivo, como prometeste.

[[v19-119-108]]

^<<v19-119-108,108>>^ Ó Senhor , aceita a minha oração de agradecimento e ensina-me os teus mandamentos!

[[v19-119-109]]

^<<v19-119-109,109>>^ A minha vida está sempre em perigo; no entanto não esqueço a tua lei .

[[v19-119-110]]

^<<v19-119-110,110>>^ Os maus armaram uma armadilha para me pegar, mas eu não desobedeci aos teus mandamentos.

[[v19-119-111]]

^<<v19-119-111,111>>^ Os teus ensinamentos são a minha riqueza para sempre; eles são a alegria do meu coração.

[[v19-119-112]]

^<<v19-119-112,112>>^ Eu resolvi obedecer às tuas ordens até o fim da minha vida.

[[v19-119-113]]

^<<v19-119-113,113>>^ Não suporto as pessoas falsas, mas amo a tua lei .

[[v19-119-114]]

^<<v19-119-114,114>>^ Tu és o meu esconderijo e o meu escudo ; eu ponho a minha esperança na tua promessa.

[[v19-119-115]]

^<<v19-119-115,115>>^ Afastem-se de mim, vocês que praticam o mal, e eu obedecerei aos mandamentos do meu Deus!

[[v19-119-116]]

^<<v19-119-116,116>>^ Dá-me forças, como prometeste, e eu continuarei vivo; não permitas que eu fique desiludido com a minha esperança.

[[v19-119-117]]

^<<v19-119-117,117>>^ Dá-me apoio, e estarei em segurança; e sempre darei atenção às tuas ordens.

[[v19-119-118]]

^<<v19-119-118,118>>^ Tu rejeitas todos os que desobedecem às tuas leis, pois os seus planos enganosos não valem nada.

[[v19-119-119]]

^<<v19-119-119,119>>^ Tu tratas todos os maus como lixo, e por isso eu amo os teus ensinamentos.

[[v19-119-120]]

^<<v19-119-120,120>>^ Eu tremo diante de ti e tenho medo dos teus julgamentos.

[[v19-119-121]]

^<<v19-119-121,121>>^ Tenho feito o que é certo e bom; não me entregues nas mãos dos meus inimigos.

[[v19-119-122]]

^<<v19-119-122,122>>^ Promete que ajudarás a mim, este teu servo . Não deixes que os orgulhosos me façam sofrer.

[[v19-119-123]]

^<<v19-119-123,123>>^ Os meus olhos estão cansados de tanto olhar, esperando que me salves e assim cumpras a tua promessa.

[[v19-119-124]]

^<<v19-119-124,124>>^ Trata este teu servo de acordo com o teu amor e ensina-me os teus mandamentos.

[[v19-119-125]]

^<<v19-119-125,125>>^ Sou teu servo; por isso, dá-me sabedoria para que eu possa conhecer os teus ensinamentos.

[[v19-119-126]]

^<<v19-119-126,126>>^ Ó Senhor  Deus, já é tempo de agires, pois a tua lei  está sendo desobedecida.

[[v19-119-127]]

^<<v19-119-127,127>>^ Eu amo os teus mandamentos mais do que o ouro, mais do que o ouro puro.

[[v19-119-128]]

^<<v19-119-128,128>>^ Por isso, sigo os teus ensinamentos e detesto todos os caminhos da mentira.

[[v19-119-129]]

^<<v19-119-129,129>>^ Os teus mandamentos são maravilhosos, e por isso os cumpro de todo o coração.

[[v19-119-130]]

^<<v19-119-130,130>>^ A explicação da tua palavra traz luz e dá sabedoria às pessoas simples.

[[v19-119-131]]

^<<v19-119-131,131>>^ Abro a boca e suspiro, pois o que mais desejo na vida é obedecer aos teus mandamentos.

[[v19-119-132]]

^<<v19-119-132,132>>^ Olha de novo para mim e tem compaixão, como sempre fazes com os que te amam.

[[v19-119-133]]

^<<v19-119-133,133>>^ Conserva-me firme, como prometeste; não deixes que eu seja dominado pelo mal.

[[v19-119-134]]

^<<v19-119-134,134>>^ Livra-me daqueles que me maltratam para que eu possa obedecer aos teus mandamentos.

[[v19-119-135]]

^<<v19-119-135,135>>^ Olha com bondade para mim, teu servo, e ensina-me as tuas leis .

[[v19-119-136]]

^<<v19-119-136,136>>^ As minhas lágrimas correm como um rio porque os outros não obedecem à tua lei.

[[v19-119-137]]

^<<v19-119-137,137>>^ Tu és justo, ó Senhor  Deus; as tuas leis  são certas.

[[v19-119-138]]

^<<v19-119-138,138>>^ Os ensinamentos que tens dado são completamente certos e justos.

[[v19-119-139]]

^<<v19-119-139,139>>^ Fico queimando de raiva porque os meus inimigos desprezam a tua palavra.

[[v19-119-140]]

^<<v19-119-140,140>>^ Como é firme a tua promessa! E como este teu servo  a ama!

[[v19-119-141]]

^<<v19-119-141,141>>^ Sou humilde e desprezado, porém não esqueço os teus ensinamentos.

[[v19-119-142]]

^<<v19-119-142,142>>^ A tua justiça dura para sempre, e a tua lei é sempre verdadeira.

[[v19-119-143]]

^<<v19-119-143,143>>^ Os sofrimentos e a ansiedade me atingem, mas os teus mandamentos me alegram.

[[v19-119-144]]

^<<v19-119-144,144>>^ Os teus ensinamentos são sempre certos; dá-me entendimento, e continuarei vivo.

[[v19-119-145]]

^<<v19-119-145,145>>^ De todo o coração, eu clamo a ti; responde-me, ó Senhor , e obedecerei aos teus mandamentos!

[[v19-119-146]]

^<<v19-119-146,146>>^ Eu clamo pedindo socorro; livra-me dos meus inimigos e eu seguirei as tuas ordens.

[[v19-119-147]]

^<<v19-119-147,147>>^ Antes do nascer do sol, eu clamo pedindo ajuda, pois a minha esperança está na tua promessa.

[[v19-119-148]]

^<<v19-119-148,148>>^ Eu fico acordado a noite inteira para meditar na tua palavra.

[[v19-119-149]]

^<<v19-119-149,149>>^ Ouve-me, ó Senhor  Deus, por causa do teu amor! Conserva-me vivo, de acordo com a tua justa vontade.

[[v19-119-150]]

^<<v19-119-150,150>>^ Os meus terríveis perseguidores estão chegando perto; é gente que nunca obedece à tua lei .

[[v19-119-151]]

^<<v19-119-151,151>>^ Mas tu, ó Senhor , estás perto de mim, e todos os teus mandamentos são verdadeiros.

[[v19-119-152]]

^<<v19-119-152,152>>^ Faz muito tempo que conheço os teus ensinamentos; tu os deste a fim de durarem para sempre.

[[v19-119-153]]

^<<v19-119-153,153>>^ Ó Deus, olha para o meu sofrimento e socorre-me, pois não tenho desprezado a tua lei !

[[v19-119-154]]

^<<v19-119-154,154>>^ Defende a minha causa e livra-me dos meus inimigos; conserva-me vivo, como prometeste.

[[v19-119-155]]

^<<v19-119-155,155>>^ Os maus não serão salvos dos seus sofrimentos porque eles não se importam com as tuas leis.

[[v19-119-156]]

^<<v19-119-156,156>>^ Como é grande a tua compaixão, ó Senhor ! Conserva-me vivo, de acordo com a tua justa vontade.

[[v19-119-157]]

^<<v19-119-157,157>>^ Tenho muitos inimigos e perseguidores, porém não deixo de obedecer aos teus mandamentos.

[[v19-119-158]]

^<<v19-119-158,158>>^ Quando olho para aqueles traidores, sinto nojo porque eles não obedecem à tua lei.

[[v19-119-159]]

^<<v19-119-159,159>>^ Vê como amo os teus ensinamentos, ó Senhor ! Conserva-me vivo, por causa do teu amor.

[[v19-119-160]]

^<<v19-119-160,160>>^ Todas as tuas palavras são verdadeiras; os teus mandamentos são justos e duram para sempre.

[[v19-119-161]]

^<<v19-119-161,161>>^ Os poderosos me atacam injustamente, mas eu respeito os teus mandamentos.

[[v19-119-162]]

^<<v19-119-162,162>>^ Como sou feliz por causa das tuas promessas, tão feliz como alguém que encontra um grande tesouro!

[[v19-119-163]]

^<<v19-119-163,163>>^ Odeio e detesto a mentira, mas amo a tua lei .

[[v19-119-164]]

^<<v19-119-164,164>>^ Sete vezes por dia, eu te louvo por causa dos teus julgamentos justos.

[[v19-119-165]]

^<<v19-119-165,165>>^ Aqueles que amam a tua lei têm muita segurança, e não há nada que os faça cair.

[[v19-119-166]]

^<<v19-119-166,166>>^ Espero que me livres dos meus inimigos, ó Senhor  Deus, pois cumpro os teus mandamentos.

[[v19-119-167]]

^<<v19-119-167,167>>^ Obedeço aos teus ensinamentos; eu os amo com todo o coração.

[[v19-119-168]]

^<<v19-119-168,168>>^ Cumpro os teus mandamentos e as tuas ordens, pois tu vês tudo o que eu faço.

[[v19-119-169]]

^<<v19-119-169,169>>^ Que o meu grito de socorro chegue a ti, ó Senhor  Deus! Dá-me sabedoria como prometeste.

[[v19-119-170]]

^<<v19-119-170,170>>^ Que a minha oração chegue diante de ti! Conforme a tua promessa, livra-me dos meus inimigos!

[[v19-119-171]]

^<<v19-119-171,171>>^ Sempre te louvarei, pois me ensinas as tuas leis .

[[v19-119-172]]

^<<v19-119-172,172>>^ Cantarei a respeito da tua lei, pois os teus mandamentos são justos.

[[v19-119-173]]

^<<v19-119-173,173>>^ Ó Deus, que a tua mão esteja sempre pronta para me ajudar, pois sigo os teus mandamentos!

[[v19-119-174]]

^<<v19-119-174,174>>^ Como desejo que me ajudes, ó Senhor  Deus! Na tua lei, encontro a felicidade.

[[v19-119-175]]

^<<v19-119-175,175>>^ Conserva-me vivo para que eu possa te louvar. Que os teus ensinamentos sirvam de ajuda para mim!

[[v19-119-176]]

^<<v19-119-176,176>>^ Como ovelha perdida, tenho andado sem rumo. Ó Senhor  Deus, vem buscar este teu servo , pois não esqueço os teus mandamentos!

'''

xref:019-salmos/019-salmos-118.adoc#v19-118-0[&#60; Capítulo Anterior] | <<v19-119-0,Topo>> | xref:019-salmos/019-salmos-120.adoc#v19-120-0[Próximo Capítulo &#62;]