include::./index.adoc[]

[[v19-2-0]]
=== Salmos, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-2-1]]

^<<v19-2-1,1>>^ Por que as nações pagãs planejam revoltas? Por que os povos fazem planos tão tolos?

[[v19-2-2]]

^<<v19-2-2,2>>^ Os seus reis se preparam, e os seus governantes fazem planos contra Deus, o Senhor , e o rei que ele escolheu.

[[v19-2-3]]

^<<v19-2-3,3>>^ Esses rebeldes dizem: "Vamos nos livrar do domínio deles; acabemos com o poder que eles têm sobre nós."

[[v19-2-4]]

^<<v19-2-4,4>>^ Do seu trono lá no céu o Senhor ri e zomba deles.

[[v19-2-5]]

^<<v19-2-5,5>>^ Então, muito irado , ele os ameaça e os assusta com o seu furor.

[[v19-2-6]]

^<<v19-2-6,6>>^ Ele diz: "Já coloquei o meu rei no trono lá em Sião , o meu monte santo."

[[v19-2-7]]

^<<v19-2-7,7>>^ O rei diz: "Anunciarei o que o Senhor  afirmou. O Senhor  me disse: ‘Você é meu filho; hoje eu me tornei seu pai.

[[v19-2-8]]

^<<v19-2-8,8>>^ Peça, e eu lhe darei todas as nações; o mundo inteiro será seu.

[[v19-2-9]]

^<<v19-2-9,9>>^ Com uma barra de ferro, você as quebrará e as fará em pedaços como se fossem potes de barro.’ "

[[v19-2-10]]

^<<v19-2-10,10>>^ Agora escutem, ó reis; prestem atenção, autoridades!

[[v19-2-11]]

^<<v19-2-11,11>>^ Adorem o Senhor  com temor . Tremam e se ajoelhem diante dele;

[[v19-2-12]]

^<<v19-2-12,12>>^ se não, ele ficará irado logo, e vocês morrerão. Felizes são aqueles que buscam a proteção de Deus!

'''

xref:019-salmos/019-salmos-001.adoc#v19-1-0[&#60; Capítulo Anterior] | <<v19-2-0,Topo>> | xref:019-salmos/019-salmos-003.adoc#v19-3-0[Próximo Capítulo &#62;]