include::./index.adoc[]

[[v19-78-0]]
=== Salmos, 78
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-78-1]]

^<<v19-78-1,1>>^ Meu povo, escute o meu ensino e preste atenção no que estou dizendo!

[[v19-78-2]]

^<<v19-78-2,2>>^ Pois falarei com vocês por meio de provérbios e explicarei os segredos do passado.

[[v19-78-3]]

^<<v19-78-3,3>>^ São coisas que ouvimos e aprendemos, coisas que os nossos antepassados nos contaram.

[[v19-78-4]]

^<<v19-78-4,4>>^ Não as esconderemos dos nossos filhos, mas falaremos aos nossos descendentes a respeito do poder de Deus, o Senhor , dos seus feitos poderosos e das coisas maravilhosas que ele fez.

[[v19-78-5]]

^<<v19-78-5,5>>^ O Senhor  deu leis  ao povo de Israel e mandamentos aos descendentes de Jacó. Ordenou aos nossos antepassados que ensinassem essas leis aos seus filhos

[[v19-78-6]]

^<<v19-78-6,6>>^ para que os seus descendentes as aprendessem, e eles, por sua vez, as ensinassem aos seus filhos.

[[v19-78-7]]

^<<v19-78-7,7>>^ Assim eles também porão a sua confiança em Deus; não esquecerão o que ele fez e obedecerão sempre aos seus mandamentos.

[[v19-78-8]]

^<<v19-78-8,8>>^ Eles não serão como os seus antepassados, um povo rebelde e desobediente, que nunca foi firme na sua confiança em Deus e não permaneceu fiel a ele.

[[v19-78-9]]

^<<v19-78-9,9>>^ Os homens da tribo  de Efraim, armados com arcos e flechas, fugiram no dia da batalha.

[[v19-78-10]]

^<<v19-78-10,10>>^ Os israelitas não cumpriram a aliança que Deus havia feito com eles e não quiseram obedecer à sua lei.

[[v19-78-11]]

^<<v19-78-11,11>>^ Esqueceram os milagres que ele havia feito na presença deles.

[[v19-78-12]]

^<<v19-78-12,12>>^ Diante dos seus antepassados, Deus realizou milagres na planície de Zoã, na terra do Egito.

[[v19-78-13]]

^<<v19-78-13,13>>^ Ele dividiu o mar e levou os israelitas pelo meio dele; ele fez com que as águas se levantassem como muralhas.

[[v19-78-14]]

^<<v19-78-14,14>>^ Durante o dia, ele os guiava com uma nuvem e de noite os conduzia por meio de um clarão de fogo.

[[v19-78-15]]

^<<v19-78-15,15>>^ Ele partiu rochas no deserto e das profundezas da terra tirou muita água para o povo beber.

[[v19-78-16]]

^<<v19-78-16,16>>^ Fez com que nascessem fontes na rocha e que água corresse como um rio.

[[v19-78-17]]

^<<v19-78-17,17>>^ Mas os nossos antepassados continuaram a pecar contra Deus; eles se revoltaram no deserto contra o Altíssimo.

[[v19-78-18]]

^<<v19-78-18,18>>^ De propósito, puseram Deus à prova, pedindo a comida que queriam.

[[v19-78-19]]

^<<v19-78-19,19>>^ Falaram contra ele, dizendo: "Será que Deus pode nos dar comida no deserto?

[[v19-78-20]]

^<<v19-78-20,20>>^ É verdade que ele partiu a rocha e que a água começou a correr como um rio. Mas será que ele pode nos dar pão? Será que pode fornecer carne para o seu povo?"

[[v19-78-21]]

^<<v19-78-21,21>>^ Quando o Senhor  Deus ouviu isso, ficou furioso. Ele atacou o seu povo com fogo, e a sua ira  contra eles aumentou

[[v19-78-22]]

^<<v19-78-22,22>>^ porque não confiaram nele e não acreditaram que ele os poderia salvar.

[[v19-78-23]]

^<<v19-78-23,23>>^ Porém Deus deu ordem ao céu lá em cima e mandou que as suas portas se abrissem.

[[v19-78-24]]

^<<v19-78-24,24>>^ Ele deu ao povo pão do céu, fazendo com que caísse o maná para eles comerem,

[[v19-78-25]]

^<<v19-78-25,25>>^ e assim comeram o pão dos anjos. Deus lhes deu comida com fartura.

[[v19-78-26]]

^<<v19-78-26,26>>^ Depois ele fez soprar do céu o vento leste e pelo seu poder agitou o vento sul.

[[v19-78-27]]

^<<v19-78-27,27>>^ Sobre o povo fez cair tantas aves, que pareciam nuvens de pó ou os grãos de areia de uma praia.

[[v19-78-28]]

^<<v19-78-28,28>>^ As aves caíam no meio do acampamento, em volta das barracas.

[[v19-78-29]]

^<<v19-78-29,29>>^ Então os israelitas comeram e ficaram satisfeitos, pois Deus lhes deu o que eles queriam.

[[v19-78-30]]

^<<v19-78-30,30>>^ Mas, enquanto estavam comendo, antes mesmo de ficarem satisfeitos,

[[v19-78-31]]

^<<v19-78-31,31>>^ Deus ficou irado com eles e matou os homens mais fortes, os melhores jovens de Israel.

[[v19-78-32]]

^<<v19-78-32,32>>^ Mesmo depois desses milagres, o povo ainda continuou a pecar e não quis acreditar em Deus.

[[v19-78-33]]

^<<v19-78-33,33>>^ Por isso ele os destruiu como se a vida deles fosse um sopro, como um desastre que acontece de repente.

[[v19-78-34]]

^<<v19-78-34,34>>^ Porém, quando Deus matava alguns, os que ficavam vivos voltavam para ele; eles se arrependiam e oravam com sinceridade a ele.

[[v19-78-35]]

^<<v19-78-35,35>>^ Eles lembravam que Deus era a sua rocha, lembravam que o Altíssimo era o seu Salvador.

[[v19-78-36]]

^<<v19-78-36,36>>^ Mas todas as palavras deles eram mentiras, tudo o que diziam era apenas para enganar.

[[v19-78-37]]

^<<v19-78-37,37>>^ O coração deles não era sincero para com Deus, e não foram fiéis à aliança que Deus havia feito com eles.

[[v19-78-38]]

^<<v19-78-38,38>>^ Porém Deus teve misericórdia do seu povo. Ele não os destruiu, mas perdoou os seus pecados. Muitas vezes parou com a sua ira e não se deixou levar pelo seu furor.

[[v19-78-39]]

^<<v19-78-39,39>>^ Lembrou que eles eram mortais, eram como um vento que passa e não volta mais.

[[v19-78-40]]

^<<v19-78-40,40>>^ Quantas vezes se revoltaram contra Deus no deserto! Quantas vezes o fizeram ficar triste!

[[v19-78-41]]

^<<v19-78-41,41>>^ Repetidas vezes o puseram à prova e entristeceram o Santo Deus de Israel.

[[v19-78-42]]

^<<v19-78-42,42>>^ Eles esqueceram o seu grande poder e o dia em que ele os tinha salvado dos seus inimigos.

[[v19-78-43]]

^<<v19-78-43,43>>^ Esqueceram as coisas maravilhosas e os milagres que ele havia feito na planície de Zoã, na terra do Egito.

[[v19-78-44]]

^<<v19-78-44,44>>^ Ali ele fez com que os rios virassem sangue, e assim os egípcios ficaram sem água para beber.

[[v19-78-45]]

^<<v19-78-45,45>>^ Mandou moscas para os atormentarem e rãs, que estragaram os seus campos.

[[v19-78-46]]

^<<v19-78-46,46>>^ Também mandou gafanhotos para comerem as suas colheitas e destruírem as suas plantações.

[[v19-78-47]]

^<<v19-78-47,47>>^ Com chuvas de pedras destruiu as suas videiras e com geada, as suas figueiras.

[[v19-78-48]]

^<<v19-78-48,48>>^ O seu gado e as suas ovelhas também morreram por causa das chuvas de pedra e dos raios.

[[v19-78-49]]

^<<v19-78-49,49>>^ Ele os destruiu com o fogo da sua ira e com o seu grande furor e a sua maldição, que vieram como mensageiros da morte.

[[v19-78-50]]

^<<v19-78-50,50>>^ Ele não parou com a sua ira, nem deixou que eles vivessem, mas os matou com uma praga.

[[v19-78-51]]

^<<v19-78-51,51>>^ Em cada casa, na terra do Egito, Deus matou o filho mais velho.

[[v19-78-52]]

^<<v19-78-52,52>>^ Depois, como pastor, Deus conduziu o povo de Israel para fora do Egito e o guiou pelo deserto.

[[v19-78-53]]

^<<v19-78-53,53>>^ Ele os guiou com segurança, e eles não tiveram medo; mas os seus inimigos foram cobertos pelo mar.

[[v19-78-54]]

^<<v19-78-54,54>>^ Deus levou os israelitas para a terra santa dele, para as montanhas que ele mesmo conquistou.

[[v19-78-55]]

^<<v19-78-55,55>>^ Ele expulsou os moradores daquelas terras enquanto o seu povo avançava. Repartiu as terras entre as tribos de Israel e deixou que os israelitas morassem nas casas dos seus antigos moradores.

[[v19-78-56]]

^<<v19-78-56,56>>^ Mas os israelitas se revoltaram contra o Deus Altíssimo e o puseram à prova. Não obedeceram aos seus mandamentos

[[v19-78-57]]

^<<v19-78-57,57>>^ e foram desleais e rebeldes como os seus pais, traiçoeiros como flechas atiradas com um arco defeituoso.

[[v19-78-58]]

^<<v19-78-58,58>>^ Eles o irritaram com os seus altares pagãos e, com os seus ídolos, fizeram com que ele ficasse enciumado.

[[v19-78-59]]

^<<v19-78-59,59>>^ Quando Deus viu isso, ficou irado e rejeitou completamente o seu povo.

[[v19-78-60]]

^<<v19-78-60,60>>^ Ele abandonou a sua Tenda Sagrada , que estava em Siló , a casa onde ele havia morado entre os seres humanos.

[[v19-78-61]]

^<<v19-78-61,61>>^ Deus deixou que os inimigos tomassem a arca da aliança , que representava o seu poder e a sua glória .

[[v19-78-62]]

^<<v19-78-62,62>>^ Ele ficou irado com o seu próprio povo e deixou que eles fossem mortos pelos inimigos.

[[v19-78-63]]

^<<v19-78-63,63>>^ Os jovens foram mortos na guerra, e as moças não tinham com quem casar.

[[v19-78-64]]

^<<v19-78-64,64>>^ Os sacerdotes foram mortos à espada, e as suas viúvas foram proibidas de chorar por eles.

[[v19-78-65]]

^<<v19-78-65,65>>^ Então o Senhor acordou como de um sono e gritou como um homem valente, embriagado pelo vinho.

[[v19-78-66]]

^<<v19-78-66,66>>^ Ele fez com que os seus inimigos fugissem derrotados e envergonhados para sempre.

[[v19-78-67]]

^<<v19-78-67,67>>^ Ele rejeitou os descendentes de José, não escolheu a tribo de Efraim.

[[v19-78-68]]

^<<v19-78-68,68>>^ Pelo contrário, escolheu a tribo de Judá, o monte Sião , que ele tanto ama.

[[v19-78-69]]

^<<v19-78-69,69>>^ Ele construiu o seu Templo parecido com a sua casa no céu e o fez firme como a terra, que está segura para sempre.

[[v19-78-70]]

^<<v19-78-70,70>>^ Então Deus escolheu o seu servo  Davi; ele o tirou do curral de ovelhas

[[v19-78-71]]

^<<v19-78-71,71>>^ quando ainda pastoreava o rebanho. Ele o pôs como rei de Israel, como pastor do povo de Deus.

[[v19-78-72]]

^<<v19-78-72,72>>^ Davi cuidou deles com dedicação e os dirigiu com sabedoria.

'''

xref:019-salmos/019-salmos-077.adoc#v19-77-0[&#60; Capítulo Anterior] | <<v19-78-0,Topo>> | xref:019-salmos/019-salmos-079.adoc#v19-79-0[Próximo Capítulo &#62;]