include::./index.adoc[]

[[v19-145-0]]
=== Salmos, 145
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-145-1]]

^<<v19-145-1,1>>^ Meu Deus e meu Rei, eu anunciarei a tua grandeza e sempre serei grato a ti.

[[v19-145-2]]

^<<v19-145-2,2>>^ Todos os dias te darei graças e sempre te louvarei.

[[v19-145-3]]

^<<v19-145-3,3>>^ O Senhor  Deus é grande e merece receber altos louvores. Quem pode compreender a sua grandeza?

[[v19-145-4]]

^<<v19-145-4,4>>^ Ó Deus, cada geração anunciará à seguinte as coisas que tens feito, e todos louvarão os teus atos poderosos.

[[v19-145-5]]

^<<v19-145-5,5>>^ Eles falarão da tua glória e da tua majestade, e eu meditarei nas coisas maravilhosas que fazes.

[[v19-145-6]]

^<<v19-145-6,6>>^ Falarão dos teus atos poderosos, e eu anunciarei a tua grandeza.

[[v19-145-7]]

^<<v19-145-7,7>>^ Falarão da tua imensa bondade e cantarão com alegria a respeito da tua fidelidade.

[[v19-145-8]]

^<<v19-145-8,8>>^ O Senhor  Deus é bom e cheio de compaixão; ele demora a ficar irado e tem sempre muito amor.

[[v19-145-9]]

^<<v19-145-9,9>>^ O Senhor  é bondoso com todos e cuida com carinho de todas as suas criaturas.

[[v19-145-10]]

^<<v19-145-10,10>>^ Ó Senhor  Deus, todas as tuas criaturas te louvarão, e te darão graças os que são fiéis a ti.

[[v19-145-11]]

^<<v19-145-11,11>>^ Todos falarão da glória do teu Reino e contarão a respeito do teu poder,

[[v19-145-12]]

^<<v19-145-12,12>>^ para que todos os povos conheçam os teus atos poderosos e a grandeza e a glória do teu Reino.

[[v19-145-13]]

^<<v19-145-13,13>>^ O teu Reino é eterno, e tu és Rei para sempre. O Senhor  Deus sempre cumpre o que promete; ele é fiel em tudo o que faz.

[[v19-145-14]]

^<<v19-145-14,14>>^ Ele ajuda os que estão em dificuldade e levanta os que caem.

[[v19-145-15]]

^<<v19-145-15,15>>^ Todos os seres vivos olham para ele com esperança, e ele dá alimento a todos no tempo certo.

[[v19-145-16]]

^<<v19-145-16,16>>^ Quando os alimenta, o Senhor  Deus é generoso; ele satisfaz a todos os seres vivos.

[[v19-145-17]]

^<<v19-145-17,17>>^ O Senhor  é justo em todos os seus atos e fiel em tudo o que faz.

[[v19-145-18]]

^<<v19-145-18,18>>^ Ele está perto de todos os que pedem a sua ajuda, dos que pedem com sinceridade.

[[v19-145-19]]

^<<v19-145-19,19>>^ A todos os que o temem dá o que é necessário; ele ouve os seus gritos e os salva da morte.

[[v19-145-20]]

^<<v19-145-20,20>>^ O Senhor  protege os que o amam, mas destruirá todos os maus.

[[v19-145-21]]

^<<v19-145-21,21>>^ Eu sempre louvarei o Senhor . Que todos os seres vivos louvem o Santo Deus para sempre!

'''

xref:019-salmos/019-salmos-144.adoc#v19-144-0[&#60; Capítulo Anterior] | <<v19-145-0,Topo>> | xref:019-salmos/019-salmos-146.adoc#v19-146-0[Próximo Capítulo &#62;]