include::./index.adoc[]

[[v19-25-0]]
=== Salmos, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-25-1]]

^<<v19-25-1,1>>^ Ó Senhor  Deus, a ti dirijo a minha oração.

[[v19-25-2]]

^<<v19-25-2,2>>^ Meu Deus, eu confio em ti. Salva-me da vergonha da derrota; não deixes que os meus inimigos se alegrem com a minha desgraça.

[[v19-25-3]]

^<<v19-25-3,3>>^ Os que confiam em ti não sofrerão a vergonha da derrota, mas serão derrotados os que sem motivo se revoltam contra ti.

[[v19-25-4]]

^<<v19-25-4,4>>^ Ó Senhor , ensina-me os teus caminhos! Faze com que eu os conheça bem.

[[v19-25-5]]

^<<v19-25-5,5>>^ Ensina-me a viver de acordo com a tua verdade, pois tu és o meu Deus, o meu Salvador. Eu sempre confio em ti.

[[v19-25-6]]

^<<v19-25-6,6>>^ Ó Senhor , lembra da tua bondade e do teu amor, que tens mostrado desde os tempos antigos.

[[v19-25-7]]

^<<v19-25-7,7>>^ Esquece os pecados e os erros da minha mocidade. Por causa do teu amor e da tua bondade, lembra de mim, ó Senhor  Deus!

[[v19-25-8]]

^<<v19-25-8,8>>^ O Senhor  é justo e bom e por isso mostra aos pecadores o caminho que devem seguir.

[[v19-25-9]]

^<<v19-25-9,9>>^ Deus guia os humildes no caminho certo e lhes ensina a sua vontade.

[[v19-25-10]]

^<<v19-25-10,10>>^ Ele é fiel e com amor guia todos os que são fiéis à sua aliança e que obedecem aos seus mandamentos.

[[v19-25-11]]

^<<v19-25-11,11>>^ Ó Senhor  Deus, cumpre a tua promessa e perdoa os meus pecados, porque são muitos!

[[v19-25-12]]

^<<v19-25-12,12>>^ Aqueles que temem  o Senhor aprenderão com ele o caminho que devem seguir.

[[v19-25-13]]

^<<v19-25-13,13>>^ Eles sempre terão sucesso, e a Terra Prometida será dos seus filhos.

[[v19-25-14]]

^<<v19-25-14,14>>^ O Senhor  Deus é amigo daqueles que o temem e lhes ensina as condições da aliança que fez com eles.

[[v19-25-15]]

^<<v19-25-15,15>>^ Eu olho sempre para o Senhor , pois ele me livra do perigo.

[[v19-25-16]]

^<<v19-25-16,16>>^ Ó Deus, olha para mim e tem pena de mim, pois estou sendo perseguido e não tenho proteção!

[[v19-25-17]]

^<<v19-25-17,17>>^ Livra o meu coração de todas as aflições e tira-me de todas as dificuldades.

[[v19-25-18]]

^<<v19-25-18,18>>^ Vê as minhas tristezas e sofrimentos e perdoa todos os meus pecados.

[[v19-25-19]]

^<<v19-25-19,19>>^ Vê quantos inimigos tenho; vê como é grande o ódio deles contra mim.

[[v19-25-20]]

^<<v19-25-20,20>>^ Protege-me e salva-me; livra-me da vergonha da derrota, pois em ti encontro segurança.

[[v19-25-21]]

^<<v19-25-21,21>>^ Que a minha honestidade e sinceridade me protejam porque confio em ti!

[[v19-25-22]]

^<<v19-25-22,22>>^ Ó Deus, salva Israel, o teu povo, de todas as suas dificuldades!

'''

xref:019-salmos/019-salmos-024.adoc#v19-24-0[&#60; Capítulo Anterior] | <<v19-25-0,Topo>> | xref:019-salmos/019-salmos-026.adoc#v19-26-0[Próximo Capítulo &#62;]