include::./index.adoc[]

[[v19-111-0]]
=== Salmos, 111
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-111-1]]

^<<v19-111-1,1>>^ Aleluia ! Na reunião do povo eu louvarei a Deus, o Senhor , com todo o meu coração, junto com os que lhe obedecem.

[[v19-111-2]]

^<<v19-111-2,2>>^ Como são maravilhosas as coisas que ele faz! Todos os que se alegram por causa delas querem entendê-las.

[[v19-111-3]]

^<<v19-111-3,3>>^ Em tudo o que ele faz, há glória  e grandeza; a sua fidelidade é eterna.

[[v19-111-4]]

^<<v19-111-4,4>>^ O Senhor  não nos deixa esquecer dos seus feitos maravilhosos; ele é bom e tem muita misericórdia.

[[v19-111-5]]

^<<v19-111-5,5>>^ Ele dá alimento aos que o temem e nunca esquece a sua aliança .

[[v19-111-6]]

^<<v19-111-6,6>>^ O Senhor  mostrou o seu poder ao povo de Israel quando lhe deu as terras de outras nações.

[[v19-111-7]]

^<<v19-111-7,7>>^ Ele é fiel e justo em tudo o que faz; todos os seus mandamentos merecem confiança.

[[v19-111-8]]

^<<v19-111-8,8>>^ Eles permanecem para sempre, pois se baseiam na verdade e na honestidade.

[[v19-111-9]]

^<<v19-111-9,9>>^ Deus pôs o seu povo em liberdade e fez com ele uma aliança eterna. Ele é santo e poderoso.

[[v19-111-10]]

^<<v19-111-10,10>>^ Para ser sábio, é preciso primeiro temer a Deus, o Senhor . Ele dá compreensão aos que obedecem aos seus mandamentos. Que o Senhor  seja louvado para sempre!

'''

xref:019-salmos/019-salmos-110.adoc#v19-110-0[&#60; Capítulo Anterior] | <<v19-111-0,Topo>> | xref:019-salmos/019-salmos-112.adoc#v19-112-0[Próximo Capítulo &#62;]