include::./index.adoc[]

[[v19-47-0]]
=== Salmos, 47
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-47-1]]

^<<v19-47-1,1>>^ Batam palmas de alegria, todos os povos! Cantem louvores a Deus em voz alta.

[[v19-47-2]]

^<<v19-47-2,2>>^ Pois o Senhor , o Altíssimo, deve ser temido ; ele é o grande Rei que governa o mundo inteiro.

[[v19-47-3]]

^<<v19-47-3,3>>^ Deus nos fez vencer os outros povos; ele nos fez governar as nações.

[[v19-47-4]]

^<<v19-47-4,4>>^ Ele escolheu para nós a terra onde vivemos, terra que é o orgulho do seu povo, a quem ele ama.

[[v19-47-5]]

^<<v19-47-5,5>>^ Deus vai subindo para o seu trono. Enquanto ele sobe, há gritos de alegria e sons de trombeta.

[[v19-47-6]]

^<<v19-47-6,6>>^ Cantem louvores a Deus. Cantem louvores ao nosso Rei.

[[v19-47-7]]

^<<v19-47-7,7>>^ Louvem a Deus com canções, pois ele é o Rei do mundo inteiro!

[[v19-47-8]]

^<<v19-47-8,8>>^ Deus está sentado no seu santo trono; ele reina sobre as nações.

[[v19-47-9]]

^<<v19-47-9,9>>^ Os que governam os povos se reúnem com o povo do Deus de Abraão, pois todo poder neste mundo pertence a Deus; ele domina tudo.

'''

xref:019-salmos/019-salmos-046.adoc#v19-46-0[&#60; Capítulo Anterior] | <<v19-47-0,Topo>> | xref:019-salmos/019-salmos-048.adoc#v19-48-0[Próximo Capítulo &#62;]