include::./index.adoc[]

[[v19-32-0]]
=== Salmos, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-32-1]]

^<<v19-32-1,1>>^ Feliz aquele cujas maldades Deus perdoa e cujos pecados ele apaga!

[[v19-32-2]]

^<<v19-32-2,2>>^ Feliz aquele que o Senhor  Deus não acusa de fazer coisas más e que não age com falsidade!

[[v19-32-3]]

^<<v19-32-3,3>>^ Enquanto não confessei o meu pecado, eu me cansava, chorando o dia inteiro.

[[v19-32-4]]

^<<v19-32-4,4>>^ De dia e de noite, tu me castigaste, ó Deus, e as minhas forças se acabaram como o sereno que seca no calor do verão.

[[v19-32-5]]

^<<v19-32-5,5>>^ Então eu te confessei o meu pecado e não escondi a minha maldade. Resolvi confessar tudo a ti, e tu perdoaste todos os meus pecados.

[[v19-32-6]]

^<<v19-32-6,6>>^ Por isso, nos momentos de angústia, todos os que são fiéis a ti devem orar. Assim, quando as grandes ondas de sofrimento vierem, não chegarão até eles.

[[v19-32-7]]

^<<v19-32-7,7>>^ Tu és o meu esconderijo; tu me livras da aflição. Eu canto bem alto a tua salvação, pois me tens protegido.

[[v19-32-8]]

^<<v19-32-8,8>>^ O Senhor  Deus me disse: "Eu lhe ensinarei o caminho por onde você deve ir; eu vou guiá-lo e orientá-lo.

[[v19-32-9]]

^<<v19-32-9,9>>^ Não seja uma pessoa sem juízo como o cavalo ou a mula, que precisam ser guiados com cabresto e rédeas para que obedeçam."

[[v19-32-10]]

^<<v19-32-10,10>>^ Os maus sofrem muito, mas os que confiam em Deus, o Senhor , são protegidos pelo seu amor.

[[v19-32-11]]

^<<v19-32-11,11>>^ Todos vocês que são corretos, alegrem-se e fiquem contentes por causa daquilo que o Senhor tem feito! Cantem de alegria, todos vocês que são obedientes a ele!

'''

xref:019-salmos/019-salmos-031.adoc#v19-31-0[&#60; Capítulo Anterior] | <<v19-32-0,Topo>> | xref:019-salmos/019-salmos-033.adoc#v19-33-0[Próximo Capítulo &#62;]