include::./index.adoc[]

[[v19-82-0]]
=== Salmos, 82
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-82-1]]

^<<v19-82-1,1>>^ Deus toma o seu lugar na reunião dos deuses e no meio deles dá a sua sentença:

[[v19-82-2]]

^<<v19-82-2,2>>^ "Vocês precisam parar de julgar injustamente e de estar do lado dos maus.

[[v19-82-3]]

^<<v19-82-3,3>>^ Defendam os direitos dos pobres e dos órfãos; sejam justos com os aflitos e os necessitados.

[[v19-82-4]]

^<<v19-82-4,4>>^ Socorram os humildes e os pobres e os salvem do poder dos maus.

[[v19-82-5]]

^<<v19-82-5,5>>^ "Vocês são ignorantes, não entendem nada; vocês vivem na escuridão. As bases da lei  e da ordem na terra estão abaladas.

[[v19-82-6]]

^<<v19-82-6,6>>^ Eu disse: ‘Vocês são deuses; todos vocês são filhos do Deus Altíssimo.

[[v19-82-7]]

^<<v19-82-7,7>>^ Porém morrerão como os homens comuns morrem; a vida de vocês acabará como a de qualquer príncipe.’ "

[[v19-82-8]]

^<<v19-82-8,8>>^ Vem, ó Deus, e governa o mundo, pois todas as nações são tuas!

'''

xref:019-salmos/019-salmos-081.adoc#v19-81-0[&#60; Capítulo Anterior] | <<v19-82-0,Topo>> | xref:019-salmos/019-salmos-083.adoc#v19-83-0[Próximo Capítulo &#62;]