include::./index.adoc[]

[[v19-71-0]]
=== Salmos, 71
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-71-1]]

^<<v19-71-1,1>>^ Ó Senhor  Deus, tu és a minha segurança; nunca deixes que eu sofra a vergonha da derrota.

[[v19-71-2]]

^<<v19-71-2,2>>^ Ajuda-me e livra-me, pois tu és justo; ouve-me e salva-me.

[[v19-71-3]]

^<<v19-71-3,3>>^ Ó Deus, sê a minha rocha de abrigo e uma fortaleza para me proteger! Tu és a minha rocha e a minha fortaleza.

[[v19-71-4]]

^<<v19-71-4,4>>^ Ó meu Deus, livra-me dos maus, livra-me do poder dos homens perversos e violentos!

[[v19-71-5]]

^<<v19-71-5,5>>^ Ó Senhor , meu Deus, em ti ponho a minha esperança; desde jovem tenho confiado em ti.

[[v19-71-6]]

^<<v19-71-6,6>>^ Toda a minha vida tenho me apoiado em ti; desde o meu nascimento tu tens me protegido. Eu sempre te louvarei.

[[v19-71-7]]

^<<v19-71-7,7>>^ A minha vida tem sido um exemplo para muitos porque tu tens sido o meu forte defensor.

[[v19-71-8]]

^<<v19-71-8,8>>^ O dia inteiro, eu te louvo e anuncio a tua glória .

[[v19-71-9]]

^<<v19-71-9,9>>^ Não me rejeites agora que sou velho; não me abandones agora que estou fraco.

[[v19-71-10]]

^<<v19-71-10,10>>^ Os meus inimigos querem me matar; eles falam contra mim e planejam a minha morte.

[[v19-71-11]]

^<<v19-71-11,11>>^ Eles dizem: "Deus o abandonou; vamos persegui-lo e agarrá-lo, pois ninguém o salvará."

[[v19-71-12]]

^<<v19-71-12,12>>^ Ó Deus, não fiques longe de mim! Ajuda-me agora, meu Deus!

[[v19-71-13]]

^<<v19-71-13,13>>^ Que sejam derrotados e destruídos aqueles que me atacam! Que fiquem arruinados e envergonhados os que querem a minha desgraça!

[[v19-71-14]]

^<<v19-71-14,14>>^ Eu sempre porei a minha esperança em ti e te louvarei mais e mais.

[[v19-71-15]]

^<<v19-71-15,15>>^ Anunciarei que tu és fiel; o dia inteiro falarei da tua salvação, embora não seja capaz de entendê-la.

[[v19-71-16]]

^<<v19-71-16,16>>^ Falarei do teu poder, ó Senhor , meu Deus; anunciarei a tua fidelidade, a tua fidelidade somente.

[[v19-71-17]]

^<<v19-71-17,17>>^ Tu tens me ensinado desde a minha mocidade, e eu continuo a falar das coisas maravilhosas que fazes.

[[v19-71-18]]

^<<v19-71-18,18>>^ Agora que estou velho, e os meus cabelos ficaram brancos, não me abandones, ó Deus! Fica comigo enquanto anuncio o teu poder e a tua força a este povo e aos seus descendentes.

[[v19-71-19]]

^<<v19-71-19,19>>^ A tua fidelidade, ó Deus, chega até o céu. Tu tens feito grandes coisas, e não há ninguém igual a ti.

[[v19-71-20]]

^<<v19-71-20,20>>^ Tu me tens feito passar por aflições e sofrimentos, mas me darás forças novamente e me livrarás da sepultura.

[[v19-71-21]]

^<<v19-71-21,21>>^ Tu me tornarás cada vez mais famoso e sempre me consolarás.

[[v19-71-22]]

^<<v19-71-22,22>>^ Prometo que te louvarei com harpa . Ó meu Deus, eu te louvarei porque és fiel. Na minha lira  tocarei hinos a ti, ó Santo Deus de Israel.

[[v19-71-23]]

^<<v19-71-23,23>>^ Cantarei de alegria quando tocar hinos a ti, cantarei com todas as minhas forças porque tu me salvaste.

[[v19-71-24]]

^<<v19-71-24,24>>^ O dia inteiro falarei da tua justiça, pois os que me queriam prejudicar foram derrotados e arruinados.

'''

xref:019-salmos/019-salmos-070.adoc#v19-70-0[&#60; Capítulo Anterior] | <<v19-71-0,Topo>> | xref:019-salmos/019-salmos-072.adoc#v19-72-0[Próximo Capítulo &#62;]