include::./index.adoc[]

[[v19-24-0]]
=== Salmos, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-24-1]]

^<<v19-24-1,1>>^ Ao Senhor  Deus pertencem o mundo e tudo o que nele existe; a terra e todos os seres vivos que nela vivem são dele.

[[v19-24-2]]

^<<v19-24-2,2>>^ O Senhor  construiu a terra sobre os mares e pôs os seus alicerces nas profundezas do oceano.

[[v19-24-3]]

^<<v19-24-3,3>>^ Quem tem o direito de subir o monte do Senhor ? Quem pode ficar no seu santo Templo?

[[v19-24-4]]

^<<v19-24-4,4>>^ Somente aquele que é correto no agir e limpo no pensar, que não adora ídolos, nem faz promessas falsas.

[[v19-24-5]]

^<<v19-24-5,5>>^ O Senhor  Deus o abençoará, o salvará e o declarará inocente no julgamento.

[[v19-24-6]]

^<<v19-24-6,6>>^ São assim as pessoas que adoram o Senhor , que prestam culto ao Deus de Jacó.

[[v19-24-7]]

^<<v19-24-7,7>>^ Abram bem os portões, abram os portões antigos, e entrará o Rei da glória .

[[v19-24-8]]

^<<v19-24-8,8>>^ Quem é esse Rei da glória? É Deus, o Senhor , forte e poderoso, o Senhor , poderoso na batalha.

[[v19-24-9]]

^<<v19-24-9,9>>^ Abram bem os portões, abram os portões antigos, e entrará o Rei da glória.

[[v19-24-10]]

^<<v19-24-10,10>>^ Quem é esse Rei da glória? É Deus, o Senhor  Todo-Poderoso; ele é o Rei da glória.

'''

xref:019-salmos/019-salmos-023.adoc#v19-23-0[&#60; Capítulo Anterior] | <<v19-24-0,Topo>> | xref:019-salmos/019-salmos-025.adoc#v19-25-0[Próximo Capítulo &#62;]