include::./index.adoc[]

[[v19-124-0]]
=== Salmos, 124
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-124-1]]

^<<v19-124-1,1>>^ Que teria acontecido se o Senhor  Deus não estivesse do nosso lado? Responda, povo de Israel!

[[v19-124-2]]

^<<v19-124-2,2>>^ O povo responde: "Se o Senhor  não estivesse do nosso lado quando os nossos inimigos nos atacaram,

[[v19-124-3]]

^<<v19-124-3,3>>^ eles nos teriam engolido vivos; pois, furiosos, se voltaram contra nós.

[[v19-124-4]]

^<<v19-124-4,4>>^ As águas nos teriam levado para longe, a enchente nos teria coberto,

[[v19-124-5]]

^<<v19-124-5,5>>^ e teríamos morrido afogados na correnteza violenta."

[[v19-124-6]]

^<<v19-124-6,6>>^ Demos graças ao Senhor , que não deixou que os nossos inimigos nos destruíssem.

[[v19-124-7]]

^<<v19-124-7,7>>^ Como o passarinho, nós escapamos da armadilha do caçador. A armadilha quebrou, e ficamos livres.

[[v19-124-8]]

^<<v19-124-8,8>>^ O nosso socorro vem do Senhor  Deus, que fez o céu e a terra.

'''

xref:019-salmos/019-salmos-123.adoc#v19-123-0[&#60; Capítulo Anterior] | <<v19-124-0,Topo>> | xref:019-salmos/019-salmos-125.adoc#v19-125-0[Próximo Capítulo &#62;]