include::./index.adoc[]

[[v19-17-0]]
=== Salmos, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-17-1]]

^<<v19-17-1,1>>^ Ó Senhor  Deus, atende o meu pedido de justiça! Escuta o meu pedido de ajuda. Ouve a oração que faço com sinceridade.

[[v19-17-2]]

^<<v19-17-2,2>>^ Tu julgarás a meu favor porque sabes o que é direito.

[[v19-17-3]]

^<<v19-17-3,3>>^ Tu conheces o meu coração e de noite me visitas. Tu tens me examinado profundamente e não encontraste em mim nenhum desejo mau. Não digo coisas que te desagradam,

[[v19-17-4]]

^<<v19-17-4,4>>^ como os outros fazem. Tenho obedecido às tuas leis e tenho procurado não agir como os violentos.

[[v19-17-5]]

^<<v19-17-5,5>>^ Tenho andado sempre nos teus caminhos e nunca me desviei deles.

[[v19-17-6]]

^<<v19-17-6,6>>^ Eu oro a ti, ó Deus, porque tu me respondes. Por isso ouve-me, escuta as minhas palavras.

[[v19-17-7]]

^<<v19-17-7,7>>^ Mostra o teu amor maravilhoso, ó Salvador! Ao teu lado estou livre dos meus inimigos.

[[v19-17-8]]

^<<v19-17-8,8>>^ Protege-me como protegerias os teus próprios olhos e, na sombra das tuas asas,

[[v19-17-9]]

^<<v19-17-9,9>>^ esconde-me dos ataques dos maus. Inimigos violentos estão ao meu redor;

[[v19-17-10]]

^<<v19-17-10,10>>^ eles não têm pena de ninguém e falam com arrogância.

[[v19-17-11]]

^<<v19-17-11,11>>^ Eles me seguem de perto e agora estão em volta de mim, esperando o momento de me derrubarem.

[[v19-17-12]]

^<<v19-17-12,12>>^ Eles são como leões escondidos, esperando por mim, prontos para me despedaçar.

[[v19-17-13]]

^<<v19-17-13,13>>^ Vem, ó Senhor  Deus, enfrenta os meus inimigos e acaba com eles! Com a tua espada, salva-me dos maus.

[[v19-17-14]]

^<<v19-17-14,14>>^ Ó Senhor  Deus, livra-me daqueles que nesta vida têm tudo o que querem! Castiga-os com os sofrimentos que tens guardado para eles. Que haja bastante castigo para os seus filhos e que ainda sobre para os filhos dos seus filhos!

[[v19-17-15]]

^<<v19-17-15,15>>^ Mas eu te verei, pois tenho vivido corretamente; e, quando acordar, a tua presença me encherá de alegria.

'''

xref:019-salmos/019-salmos-016.adoc#v19-16-0[&#60; Capítulo Anterior] | <<v19-17-0,Topo>> | xref:019-salmos/019-salmos-018.adoc#v19-18-0[Próximo Capítulo &#62;]