include::./index.adoc[]

[[v19-1-0]]
=== Salmos, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-1-1]]

^<<v19-1-1,1>>^ Felizes são aqueles que não se deixam levar pelos conselhos dos maus, que não seguem o exemplo dos que não querem saber de Deus e que não se juntam com os que zombam de tudo o que é sagrado!

[[v19-1-2]]

^<<v19-1-2,2>>^ Pelo contrário, o prazer deles está na lei  do Senhor , e nessa lei eles meditam dia e noite.

[[v19-1-3]]

^<<v19-1-3,3>>^ Essas pessoas são como árvores que crescem na beira de um riacho; elas dão frutas no tempo certo, e as suas folhas não murcham. Assim também tudo o que essas pessoas fazem dá certo.

[[v19-1-4]]

^<<v19-1-4,4>>^ O mesmo não acontece com os maus; eles são como a palha que o vento leva.

[[v19-1-5]]

^<<v19-1-5,5>>^ No Dia do Juízo eles serão condenados e ficarão separados dos que obedecem a Deus.

[[v19-1-6]]

^<<v19-1-6,6>>^ Pois o Senhor  dirige e abençoa a vida daqueles que lhe obedecem, porém o fim dos maus são a desgraça e a morte.

'''

xref:018-jo/018-jo-042.adoc#v18-42-0[&#60; Capítulo Anterior] | <<v19-1-0,Topo>> | xref:019-salmos/019-salmos-002.adoc#v19-2-0[Próximo Capítulo &#62;]