include::./index.adoc[]

[[v19-141-0]]
=== Salmos, 141
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-141-1]]

^<<v19-141-1,1>>^ Ó Senhor  Deus, eu clamo a ti; vem depressa me socorrer! Escuta-me quando peço a tua ajuda.

[[v19-141-2]]

^<<v19-141-2,2>>^ Recebe a minha oração como se fosse incenso, e que as minhas mãos levantadas sejam como a oferta da tarde!

[[v19-141-3]]

^<<v19-141-3,3>>^ Ó Senhor , controla a minha boca e não me deixes falar o que não devo!

[[v19-141-4]]

^<<v19-141-4,4>>^ Não permitas que o meu coração deseje fazer o mal, nem que eu ande com os que são perversos ou tome parte na maldade deles. E que eu nunca esteja presente nas suas festas!

[[v19-141-5]]

^<<v19-141-5,5>>^ Eu aceito que uma pessoa direita me repreenda ou castigue, pois isso é um gesto de amizade; mas eu nunca aceitarei elogios dos perversos e continuarei a orar contra a ruindade deles.

[[v19-141-6]]

^<<v19-141-6,6>>^ Quando os seus chefes forem atirados do alto dos rochedos, então o povo saberá que eu dizia a verdade.

[[v19-141-7]]

^<<v19-141-7,7>>^ Como a lenha é rachada e cortada em pedaços, assim os seus ossos serão espalhados na beira da sepultura deles.

[[v19-141-8]]

^<<v19-141-8,8>>^ Mas eu, ó Senhor , meu Deus, continuo confiando em ti e buscando a tua proteção. Não me deixes morrer.

[[v19-141-9]]

^<<v19-141-9,9>>^ Livra-me das redes que os perversos estendem para me pegar, livra-me das armadilhas dos que fazem o mal.

[[v19-141-10]]

^<<v19-141-10,10>>^ Que os maus caiam nas suas próprias armadilhas, e que eu consiga escapar são e salvo!

'''

xref:019-salmos/019-salmos-140.adoc#v19-140-0[&#60; Capítulo Anterior] | <<v19-141-0,Topo>> | xref:019-salmos/019-salmos-142.adoc#v19-142-0[Próximo Capítulo &#62;]