include::./index.adoc[]

[[v19-35-0]]
=== Salmos, 35
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-35-1]]

^<<v19-35-1,1>>^ Ó Senhor  Deus, ataca os que me atacam e combate os que me combatem!

[[v19-35-2]]

^<<v19-35-2,2>>^ Pega o teu escudo e a tua armadura e vem me ajudar.

[[v19-35-3]]

^<<v19-35-3,3>>^ Pega a tua lança e o teu machado de guerra e luta contra os que me perseguem. Dá-me a certeza de que vais me salvar.

[[v19-35-4]]

^<<v19-35-4,4>>^ Que sejam derrotados e humilhados aqueles que me querem matar! Que fujam envergonhados os que fazem planos contra mim!

[[v19-35-5]]

^<<v19-35-5,5>>^ Que sejam como a palha soprada pelo vento, quando o Anjo do Senhor os atacar!

[[v19-35-6]]

^<<v19-35-6,6>>^ Que o caminho deles fique escuro e escorregadio quando o Anjo do Senhor os perseguir!

[[v19-35-7]]

^<<v19-35-7,7>>^ Pois, sem motivo nenhum, armaram uma armadilha para mim; cavaram uma cova funda para me pegar.

[[v19-35-8]]

^<<v19-35-8,8>>^ Porém, quando menos esperarem, virá a destruição. Eles serão apanhados pelas suas próprias armadilhas; cairão nelas e serão destruídos.

[[v19-35-9]]

^<<v19-35-9,9>>^ Então eu me alegrarei por causa do que o Senhor  Deus tem feito; ficarei feliz porque ele me salvou da morte.

[[v19-35-10]]

^<<v19-35-10,10>>^ Com todo o coração eu lhe direi: "Não há ninguém como tu, ó Senhor ! Tu proteges os fracos quando são atacados pelos fortes e livras os pobres e os necessitados das mãos dos exploradores."

[[v19-35-11]]

^<<v19-35-11,11>>^ Homens maus testemunham contra mim e me acusam de crimes que não cometi.

[[v19-35-12]]

^<<v19-35-12,12>>^ O bem que faço eles me pagam com o mal, e por isso estou desesperado.

[[v19-35-13]]

^<<v19-35-13,13>>^ Mas, quando eles estavam doentes, eu vesti roupas de luto e até deixei de comer. Curvei a cabeça e orei por eles.

[[v19-35-14]]

^<<v19-35-14,14>>^ Orei como se fosse por um amigo ou um irmão. Eu andava curvado, de luto, como quem chora por sua própria mãe.

[[v19-35-15]]

^<<v19-35-15,15>>^ Porém, quando eu estava aflito, eles se alegravam e ficavam em volta de mim, zombando. Pessoas desconhecidas me bateram e me feriram várias vezes.

[[v19-35-16]]

^<<v19-35-16,16>>^ Como homens que zombam de um coxo, eles zombaram de mim e me olharam feio, com ódio.

[[v19-35-17]]

^<<v19-35-17,17>>^ Ó Senhor, até quando ficarás apenas olhando? Livra-me dos ataques deles; salva a minha vida desses leões.

[[v19-35-18]]

^<<v19-35-18,18>>^ Então eu te agradecerei em público; eu te louvarei no meio da multidão.

[[v19-35-19]]

^<<v19-35-19,19>>^ Não deixes que os meus inimigos, aqueles mentirosos, se alegrem com a minha derrota! Não permitas que os que me odeiam sem motivo fiquem rindo, felizes, por causa da minha desgraça!

[[v19-35-20]]

^<<v19-35-20,20>>^ Eles não falam como amigos; pelo contrário, inventam acusações falsas contra as pessoas que amam a paz.

[[v19-35-21]]

^<<v19-35-21,21>>^ Eles me acusam e gritam: "Nós vimos o que você fez!"

[[v19-35-22]]

^<<v19-35-22,22>>^ Mas tu, ó Senhor  Deus, tens visto isso. Então não te cales, Senhor, e não fiques longe de mim!

[[v19-35-23]]

^<<v19-35-23,23>>^ Acorda, Senhor, para me fazeres justiça! Levanta-te, meu Deus, e defende a minha causa!

[[v19-35-24]]

^<<v19-35-24,24>>^ Ó Senhor  Deus, tu és justo; por isso, declara que estou inocente. Ó meu Deus, não deixes que os meus inimigos se alegrem à minha custa!

[[v19-35-25]]

^<<v19-35-25,25>>^ Não deixes que eles digam: "Nós acabamos com ele. Era isso mesmo o que queríamos."

[[v19-35-26]]

^<<v19-35-26,26>>^ Que sejam completamente derrotados e envergonhados aqueles que se alegram com o meu sofrimento! Que fiquem cobertos de vergonha e de desgraça os que dizem que são melhores do que eu!

[[v19-35-27]]

^<<v19-35-27,27>>^ Porém que gritem de alegria os que desejam que eu seja declarado inocente! Que eles digam sempre: "Como é grande o Senhor ! Ele está contente porque tudo vai bem com o seu servo ."

[[v19-35-28]]

^<<v19-35-28,28>>^ Então anunciarei a tua fidelidade e te louvarei o dia inteiro.

'''

xref:019-salmos/019-salmos-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-salmos/019-salmos-036.adoc#v19-36-0[Próximo Capítulo &#62;]