include::./index.adoc[]

[[v19-42-0]]
=== Salmos, 42
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-42-1]]

^<<v19-42-1,1>>^ Assim como o corço  deseja as águas do ribeirão, assim também eu quero estar na tua presença, ó Deus!

[[v19-42-2]]

^<<v19-42-2,2>>^ Eu tenho sede de ti, o Deus vivo! Quando poderei ir adorar na tua presença?

[[v19-42-3]]

^<<v19-42-3,3>>^ Choro dia e noite, e as lágrimas são o meu alimento. Os meus inimigos estão sempre me perguntando: "Onde está o seu Deus?"

[[v19-42-4]]

^<<v19-42-4,4>>^ Quando penso no passado, sinto dor no coração. Eu lembro quando ia com a multidão à casa de Deus. Eu guiava o povo, e todos íamos caminhando juntos, felizes, cantando e louvando a Deus.

[[v19-42-5]]

^<<v19-42-5,5>>^ Por que estou tão triste? Por que estou tão aflito? Eu porei a minha esperança em Deus e ainda o louvarei. Ele é o meu Salvador e o meu Deus.

[[v19-42-6]]

^<<v19-42-6,6>>^ O meu coração está profundamente abatido, e por isso eu penso em Deus. Assim como o mar agitado ruge, e assim como as águas das cachoeiras descem dos montes Hermom e Mizar e correm com violência até o rio Jordão, assim são as ondas de tristeza que o Senhor  Deus mandou sobre mim.

[[v19-42-7]]

^<<v19-42-7,7>>^ O meu coração está

[[v19-42-8]]

^<<v19-42-8,8>>^ Que ele me mostre durante o dia o seu amor, e assim de noite eu cantarei uma canção, uma oração ao Deus que me dá vida.

[[v19-42-9]]

^<<v19-42-9,9>>^ Pergunto a Deus, a minha rocha: "Por que esqueceste de mim? Por que tenho de viver sofrendo por causa da maldade dos meus inimigos?"

[[v19-42-10]]

^<<v19-42-10,10>>^ Até os meus ossos doem quando os meus inimigos me ofendem, perguntando todos os dias: "Onde está o seu Deus?"

'''

xref:019-salmos/019-salmos-041.adoc#v19-41-0[&#60; Capítulo Anterior] | <<v19-42-0,Topo>> | xref:019-salmos/019-salmos-043.adoc#v19-43-0[Próximo Capítulo &#62;]