include::./index.adoc[]

[[v19-76-0]]
=== Salmos, 76
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-76-1]]

^<<v19-76-1,1>>^ Deus é bem-conhecido em Judá; o seu nome é famoso em Israel.

[[v19-76-2]]

^<<v19-76-2,2>>^ A sua casa está em Jerusalém; ele mora no monte Sião .

[[v19-76-3]]

^<<v19-76-3,3>>^ Ali Deus quebrou todas as armas dos inimigos: as flechas, os escudos  e as espadas.

[[v19-76-4]]

^<<v19-76-4,4>>^ Como és glorioso , ó Deus! E como foste grandioso quando voltaste das montanhas onde derrotaste os teus inimigos!

[[v19-76-5]]

^<<v19-76-5,5>>^ Foram levadas todas as coisas que os seus valentes soldados tinham; eles agora estão dormindo o sono da morte, pois não tiveram forças para se defender.

[[v19-76-6]]

^<<v19-76-6,6>>^ Quando tu, ó Deus de Jacó, os ameaçaste, os cavalos e os cavaleiros ficaram como mortos.

[[v19-76-7]]

^<<v19-76-7,7>>^ Todas as pessoas têm medo de ti. Quem pode permanecer na tua presença quando estás irado ?

[[v19-76-8]]

^<<v19-76-8,8>>^ Lá do céu fizeste conhecida a tua sentença de condenação. A terra teve medo e ficou quieta

[[v19-76-9]]

^<<v19-76-9,9>>^ quando te levantaste para fazer justiça, para salvar todos os que são explorados neste mundo.

[[v19-76-10]]

^<<v19-76-10,10>>^ Até a ira humana aumenta o louvor que é dado a ti; e aqueles que não morreram nas guerras vão comemorar as tuas festas.

[[v19-76-11]]

^<<v19-76-11,11>>^ Deem ao Senhor , nosso Deus, o que vocês prometeram; que todas as nações vizinhas venham e tragam ofertas para Deus, aquele que deve ser temido !

[[v19-76-12]]

^<<v19-76-12,12>>^ Deus humilha os governantes orgulhosos; ele enche de medo os reis da terra.

'''

xref:019-salmos/019-salmos-075.adoc#v19-75-0[&#60; Capítulo Anterior] | <<v19-76-0,Topo>> | xref:019-salmos/019-salmos-077.adoc#v19-77-0[Próximo Capítulo &#62;]