include::./index.adoc[]

[[v19-8-0]]
=== Salmos, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-8-1]]

^<<v19-8-1,1>>^ Ó Senhor , Senhor nosso, a tua grandeza é vista no mundo inteiro. O louvor dado a ti chega até o céu

[[v19-8-2]]

^<<v19-8-2,2>>^ e é cantado pelas crianças e pelas criancinhas de colo. Tu construíste uma fortaleza para te proteger dos teus inimigos, para acabar com todos os que te desafiam.

[[v19-8-3]]

^<<v19-8-3,3>>^ Quando olho para o céu, que tu criaste, para a lua e para as estrelas, que puseste nos seus lugares —

[[v19-8-4]]

^<<v19-8-4,4>>^ que é um simples ser humano para que penses nele? Que é um ser mortal para que te preocupes com ele?

[[v19-8-5]]

^<<v19-8-5,5>>^ No entanto, fizeste o ser humano inferior somente a ti mesmo e lhe deste a glória  e a honra de um rei.

[[v19-8-6]]

^<<v19-8-6,6>>^ Tu lhe deste poder sobre tudo o que criaste; tu puseste todas as coisas debaixo do domínio dele:

[[v19-8-7]]

^<<v19-8-7,7>>^ as ovelhas e o gado e os animais selvagens também;

[[v19-8-8]]

^<<v19-8-8,8>>^ os pássaros e os peixes e todos os seres que vivem no mar.

[[v19-8-9]]

^<<v19-8-9,9>>^ Ó Senhor , nosso Deus, a tua grandeza é vista no mundo inteiro.

'''

xref:019-salmos/019-salmos-007.adoc#v19-7-0[&#60; Capítulo Anterior] | <<v19-8-0,Topo>> | xref:019-salmos/019-salmos-009.adoc#v19-9-0[Próximo Capítulo &#62;]