include::./index.adoc[]

[[v19-41-0]]
=== Salmos, 41
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-41-1]]

^<<v19-41-1,1>>^ Felizes são aqueles que ajudam os pobres, pois o Senhor  Deus os ajudará quando estiverem em dificuldades!

[[v19-41-2]]

^<<v19-41-2,2>>^ O Senhor  os protegerá, guardará a vida deles e lhes dará felicidade na Terra Prometida . Ele não os abandonará nas garras dos inimigos.

[[v19-41-3]]

^<<v19-41-3,3>>^ Quando estiverem doentes, de cama, o Senhor  os ajudará e lhes dará saúde novamente.

[[v19-41-4]]

^<<v19-41-4,4>>^ Eu disse: "Ó Senhor  Deus, pequei contra ti. Tem compaixão de mim e cura-me."

[[v19-41-5]]

^<<v19-41-5,5>>^ Os meus inimigos falam mal de mim e perguntam: "Quando será que ele vai morrer e ser esquecido?"

[[v19-41-6]]

^<<v19-41-6,6>>^ Se algum deles vem me visitar, não fala com sinceridade e ainda junta más notícias a meu respeito, para sair espalhando por aí afora.

[[v19-41-7]]

^<<v19-41-7,7>>^ Todos os que me odeiam falam de mim, cochichando, e pensam que o pior vai me acontecer.

[[v19-41-8]]

^<<v19-41-8,8>>^ Eles dizem assim: "Ele está muito mal mesmo e não vai se levantar mais."

[[v19-41-9]]

^<<v19-41-9,9>>^ Até o meu melhor amigo, em quem eu tanto confiava, aquele que tomava refeições comigo, até ele se virou contra mim.

[[v19-41-10]]

^<<v19-41-10,10>>^ Ó Senhor  Deus, tem compaixão de mim e me dá saúde novamente para que eu dê aos meus inimigos o que merecem!

[[v19-41-11]]

^<<v19-41-11,11>>^ Eles não me vencerão, e assim ficarei sabendo que tu me aprovas.

[[v19-41-12]]

^<<v19-41-12,12>>^ Tu me ajudarás, porque faço o que é direito e me deixarás ficar para sempre na tua presença.

[[v19-41-13]]

^<<v19-41-13,13>>^ Louvado seja o Senhor , o Deus de Israel! Louvado seja, agora e sempre! Amém ! Amém!

'''

xref:019-salmos/019-salmos-040.adoc#v19-40-0[&#60; Capítulo Anterior] | <<v19-41-0,Topo>> | xref:019-salmos/019-salmos-042.adoc#v19-42-0[Próximo Capítulo &#62;]