include::./index.adoc[]

[[v19-33-0]]
=== Salmos, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-33-1]]

^<<v19-33-1,1>>^ Todos vocês que obedecem a Deus, o Senhor , alegrem-se por causa daquilo que ele tem feito! Louvem a Deus, todas as pessoas honestas.

[[v19-33-2]]

^<<v19-33-2,2>>^ Toquem lira  em louvor ao Senhor , cantem louvores com acompanhamento de harpas  de dez cordas.

[[v19-33-3]]

^<<v19-33-3,3>>^ Cantem a Deus uma nova canção, toquem harpa e gritem bem alto.

[[v19-33-4]]

^<<v19-33-4,4>>^ As palavras do Senhor são verdadeiras; tudo o que ele faz merece confiança.

[[v19-33-5]]

^<<v19-33-5,5>>^ O Senhor  Deus ama tudo o que é certo e justo; a terra está cheia do seu amor.

[[v19-33-6]]

^<<v19-33-6,6>>^ Por meio da sua palavra, o Senhor  fez os céus; pela sua ordem, ele criou o sol, a lua e as estrelas.

[[v19-33-7]]

^<<v19-33-7,7>>^ Deus juntou os mares num lugar só e guardou os oceanos em reservatórios.

[[v19-33-8]]

^<<v19-33-8,8>>^ Que toda a terra tema a Deus, o Senhor ! Que todos os habitantes do mundo o temam!

[[v19-33-9]]

^<<v19-33-9,9>>^ Pois ele falou, e o mundo foi criado; ele deu ordem, e tudo apareceu.

[[v19-33-10]]

^<<v19-33-10,10>>^ O Senhor  acaba com os planos das nações, ele não deixa que eles se realizem.

[[v19-33-11]]

^<<v19-33-11,11>>^ Mas o que o Senhor  planeja dura para sempre, as suas decisões permanecem eternamente.

[[v19-33-12]]

^<<v19-33-12,12>>^ Feliz a nação que tem o Senhor  como o seu Deus! Feliz o povo que Deus escolheu para ser dele!

[[v19-33-13]]

^<<v19-33-13,13>>^ O Senhor  Deus olha do céu e vê toda a humanidade.

[[v19-33-14]]

^<<v19-33-14,14>>^ Do lugar onde mora, ele observa todos os que vivem na terra.

[[v19-33-15]]

^<<v19-33-15,15>>^ É Deus quem forma a mente deles e quem sabe tudo o que fazem.

[[v19-33-16]]

^<<v19-33-16,16>>^ Nenhum rei vence por ter um exército poderoso, nem os soldados conseguem a vitória por causa da sua força.

[[v19-33-17]]

^<<v19-33-17,17>>^ Não são os cavalos de guerra que ganham a batalha; a sua grande força não pode salvar ninguém.

[[v19-33-18]]

^<<v19-33-18,18>>^ É o Senhor  Deus quem protege aqueles que o temem , é ele quem guarda aqueles que confiam no seu amor.

[[v19-33-19]]

^<<v19-33-19,19>>^ Ele os salva da morte e nos tempos de fome os conserva com vida.

[[v19-33-20]]

^<<v19-33-20,20>>^ Nós pomos a nossa esperança em Deus, o Senhor ; ele é a nossa ajuda e o nosso escudo .

[[v19-33-21]]

^<<v19-33-21,21>>^ O nosso coração se alegra por causa do que o Senhor  tem feito; nós confiamos nele porque ele é santo.

[[v19-33-22]]

^<<v19-33-22,22>>^ Ó Senhor  Deus, que o teu amor nos acompanhe, pois nós pomos em ti a nossa esperança!

'''

xref:019-salmos/019-salmos-032.adoc#v19-32-0[&#60; Capítulo Anterior] | <<v19-33-0,Topo>> | xref:019-salmos/019-salmos-034.adoc#v19-34-0[Próximo Capítulo &#62;]