include::./index.adoc[]

[[v19-18-0]]
=== Salmos, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-18-1]]

^<<v19-18-1,1>>^ Ó Senhor  Deus, como eu te amo! Tu és a minha força.

[[v19-18-2]]

^<<v19-18-2,2>>^ O Senhor  é a minha rocha, a minha fortaleza e o meu libertador. O meu Deus é uma rocha em que me escondo. Ele me protege como um escudo ; ele é o meu abrigo, e com ele estou seguro.

[[v19-18-3]]

^<<v19-18-3,3>>^ Eu clamo a Deus, pedindo ajuda, e ele me salva dos meus inimigos. Louvem a Deus, o Senhor !

[[v19-18-4]]

^<<v19-18-4,4>>^ Estive cercado de perigos de morte, e ondas de destruição rolaram sobre mim.

[[v19-18-5]]

^<<v19-18-5,5>>^ A morte me amarrou com as suas cordas, e a sepultura armou a sua armadilha para me pegar.

[[v19-18-6]]

^<<v19-18-6,6>>^ No meu desespero, eu clamei ao Senhor e pedi que ele me ajudasse. Do seu templo no céu o Senhor  ouviu a minha voz, ele escutou o meu grito de socorro.

[[v19-18-7]]

^<<v19-18-7,7>>^ Então a terra tremeu e se abalou, e as bases dos montes balançaram e tremeram porque Deus estava irado .

[[v19-18-8]]

^<<v19-18-8,8>>^ Do seu nariz saiu fumaça, e da sua boca saíram brasas e fogo devorador.

[[v19-18-9]]

^<<v19-18-9,9>>^ Ele abriu o céu e desceu com uma nuvem escura debaixo dos pés.

[[v19-18-10]]

^<<v19-18-10,10>>^ Voou nas costas de um querubim e viajou rápido nas asas do vento.

[[v19-18-11]]

^<<v19-18-11,11>>^ Ele se cobriu de escuridão; nuvens grossas, cheias de água, estavam ao seu redor.

[[v19-18-12]]

^<<v19-18-12,12>>^ Brasas e chuva de pedra saíram dos relâmpagos que estavam diante dele e atravessaram as nuvens escuras.

[[v19-18-13]]

^<<v19-18-13,13>>^ Então o Senhor  trovejou do céu; o Altíssimo fez ouvir a sua voz.

[[v19-18-14]]

^<<v19-18-14,14>>^ Ele atirou as suas flechas e espalhou os seus inimigos; com o clarão dos seus relâmpagos ele os fez fugir.

[[v19-18-15]]

^<<v19-18-15,15>>^ Quando tu, ó Senhor  Deus, repreendeste os teus inimigos e, furioso, trovejaste contra eles, o fundo do mar apareceu, e os alicerces da terra ficaram descobertos.

[[v19-18-16]]

^<<v19-18-16,16>>^ Lá do alto, o Senhor  me estendeu a mão e me segurou; ele me tirou do mar profundo.

[[v19-18-17]]

^<<v19-18-17,17>>^ O Senhor  me livrou dos meus poderosos inimigos, daqueles que me odiavam. E todos eles eram fortes demais para mim.

[[v19-18-18]]

^<<v19-18-18,18>>^ Quando eu estava em dificuldade, eles me atacaram; porém o Senhor  me protegeu,

[[v19-18-19]]

^<<v19-18-19,19>>^ me livrou do perigo e me salvou porque me ama.

[[v19-18-20]]

^<<v19-18-20,20>>^ O Senhor  Deus me recompensa porque sou honesto; ele me abençoa porque sou inocente.

[[v19-18-21]]

^<<v19-18-21,21>>^ Eu tenho feito a vontade do Senhor e nunca cometi o pecado de abandonar o meu Deus.

[[v19-18-22]]

^<<v19-18-22,22>>^ Eu tenho cumprido todas as suas leis e não tenho desobedecido aos seus mandamentos.

[[v19-18-23]]

^<<v19-18-23,23>>^ O Senhor  sabe que não cometi nenhuma falta e que tenho ficado longe do mal.

[[v19-18-24]]

^<<v19-18-24,24>>^ Assim ele me recompensa porque sou honesto e porque sabe que não sou culpado de nada.

[[v19-18-25]]

^<<v19-18-25,25>>^ Tu, ó Senhor  Deus, és fiel com os que são fiéis a ti e correto com aqueles que são corretos.

[[v19-18-26]]

^<<v19-18-26,26>>^ Tu és puro para os que são puros, mas és inimigo dos que são maus.

[[v19-18-27]]

^<<v19-18-27,27>>^ Tu salvas os humildes, mas humilhas os orgulhosos.

[[v19-18-28]]

^<<v19-18-28,28>>^ Tu, ó Senhor , me iluminas; tu, meu Deus, acabas com a minha escuridão.

[[v19-18-29]]

^<<v19-18-29,29>>^ Tu me dás força para atacar os meus inimigos e poder para vencer as suas defesas.

[[v19-18-30]]

^<<v19-18-30,30>>^ Este Deus faz tudo perfeito e cumpre o que promete. Ele é como um escudo para os que procuram a sua proteção.

[[v19-18-31]]

^<<v19-18-31,31>>^ O Senhor  é o único Deus; somente Deus é a nossa rocha.

[[v19-18-32]]

^<<v19-18-32,32>>^ Ele é o Deus que me dá forças e me protege aonde quer que eu vá.

[[v19-18-33]]

^<<v19-18-33,33>>^ Ele não me deixa tropeçar e me põe a salvo nas montanhas.

[[v19-18-34]]

^<<v19-18-34,34>>^ Ele me treina para a batalha para que eu possa usar os arcos mais fortes.

[[v19-18-35]]

^<<v19-18-35,35>>^ Tu, ó Senhor  Deus, me deste o escudo que salva a minha vida. O teu cuidado me tem feito prosperar, e o teu poder me tem sustentado.

[[v19-18-36]]

^<<v19-18-36,36>>^ Tu não tens deixado que os meus inimigos me peguem, e eu não caí nenhuma vez.

[[v19-18-37]]

^<<v19-18-37,37>>^ Persigo esses inimigos e os pego de surpresa; não paro até acabar com eles.

[[v19-18-38]]

^<<v19-18-38,38>>^ Eu os esmago, e eles não podem se levantar; eles caem derrotados aos meus pés.

[[v19-18-39]]

^<<v19-18-39,39>>^ Tu me dás força para a batalha e fazes com que eu derrote os meus inimigos.

[[v19-18-40]]

^<<v19-18-40,40>>^ Tu fazes com que eles fujam de mim, e eu destruo os que me odeiam.

[[v19-18-41]]

^<<v19-18-41,41>>^ Eles gritam pedindo socorro, mas não há ninguém para salvá-los. Chamam o Senhor  Deus, mas ele não responde.

[[v19-18-42]]

^<<v19-18-42,42>>^ Eu os esmago, e eles viram pó, o pó que o vento leva. Eu os piso como se fossem a lama das ruas.

[[v19-18-43]]

^<<v19-18-43,43>>^ Tu me livras de revoluções no meio do povo e me colocas como rei das nações. Povos que eu não conhecia são agora meus escravos.

[[v19-18-44]]

^<<v19-18-44,44>>^ Estrangeiros se curvam diante de mim e me obedecem quando dou ordens.

[[v19-18-45]]

^<<v19-18-45,45>>^ Eles perdem a coragem e saem tremendo das suas fortalezas.

[[v19-18-46]]

^<<v19-18-46,46>>^ O Senhor  vive. Louvem aquele que é a minha rocha, anunciem a grandeza do Deus que salva a minha vida.

[[v19-18-47]]

^<<v19-18-47,47>>^ Ele me vinga dos meus inimigos, põe os povos debaixo do meu poder

[[v19-18-48]]

^<<v19-18-48,48>>^ e me livra dos meus adversários. Tu, ó Senhor  Deus, fazes com que eu vença os meus inimigos e me proteges dos homens violentos.

[[v19-18-49]]

^<<v19-18-49,49>>^ Por isso eu te louvo entre os pagãos; a ti eu canto hinos de louvor.

[[v19-18-50]]

^<<v19-18-50,50>>^ Deus dá grandes vitórias ao seu rei e mostra o seu amor a quem ele escolheu — a Davi e aos seus descendentes, para sempre.

'''

xref:019-salmos/019-salmos-017.adoc#v19-17-0[&#60; Capítulo Anterior] | <<v19-18-0,Topo>> | xref:019-salmos/019-salmos-019.adoc#v19-19-0[Próximo Capítulo &#62;]