include::./index.adoc[]

[[v19-57-0]]
=== Salmos, 57
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-57-1]]

^<<v19-57-1,1>>^ Tem misericórdia de mim, ó Deus, tem misericórdia, pois em ti procuro segurança! Na sombra das tuas asas eu encontro proteção até que passe o perigo.

[[v19-57-2]]

^<<v19-57-2,2>>^ Eu chamo o Deus Altíssimo; eu chamo a Deus, que me ajuda em tudo.

[[v19-57-3]]

^<<v19-57-3,3>>^ Do céu, ele me responderá e me salvará; ele derrotará os que me atacam. Deus me mostrará o seu amor e a sua fidelidade.

[[v19-57-4]]

^<<v19-57-4,4>>^ Estou cercado de inimigos; eles são como leões, e querem me devorar. Os seus dentes são como lanças e flechas, e a língua deles, como espada afiada.

[[v19-57-5]]

^<<v19-57-5,5>>^ Ó Deus, mostra a tua grandeza nos céus, e que a tua glória  brilhe no mundo inteiro!

[[v19-57-6]]

^<<v19-57-6,6>>^ Os meus inimigos armaram uma armadilha para me pegar, e eu fiquei muito aflito. Fizeram uma cova no meu caminho, mas eles mesmos caíram nela.

[[v19-57-7]]

^<<v19-57-7,7>>^ O meu coração está firme, ó Deus, bem firme; eu cantarei hinos em teu louvor.

[[v19-57-8]]

^<<v19-57-8,8>>^ Acorde, meu coração! Minha harpa  e minha lira , acordem! Eu acordarei o sol.

[[v19-57-9]]

^<<v19-57-9,9>>^ Senhor, eu te darei graças no meio das nações; eu te louvarei entre os povos.

[[v19-57-10]]

^<<v19-57-10,10>>^ O teu amor chega até os céus, e a tua fidelidade, até as nuvens.

[[v19-57-11]]

^<<v19-57-11,11>>^ Ó Deus, mostra a tua grandeza nos céus, e que a tua glória brilhe no mundo inteiro!

'''

xref:019-salmos/019-salmos-056.adoc#v19-56-0[&#60; Capítulo Anterior] | <<v19-57-0,Topo>> | xref:019-salmos/019-salmos-058.adoc#v19-58-0[Próximo Capítulo &#62;]