include::./index.adoc[]

[[v19-16-0]]
=== Salmos, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-16-1]]

^<<v19-16-1,1>>^ Guarda-me, ó Deus, pois em ti eu tenho segurança!

[[v19-16-2]]

^<<v19-16-2,2>>^ Eu disse a Deus, o Senhor : "Tu és o meu Senhor; tudo o que tenho de bom vem de ti."

[[v19-16-3]]

^<<v19-16-3,3>>^ Como são admiráveis as pessoas que se dedicam a Deus! O meu maior prazer é estar na companhia delas.

[[v19-16-4]]

^<<v19-16-4,4>>^ Aqueles que correm atrás de outros deuses trazem muito sofrimento para si mesmos. Eu não tomarei parte nas suas ofertas de sangue, nem adorarei os seus deuses.

[[v19-16-5]]

^<<v19-16-5,5>>^ Tu, ó Senhor  Deus, és tudo o que tenho. O meu futuro está nas tuas mãos; tu diriges a minha vida.

[[v19-16-6]]

^<<v19-16-6,6>>^ Como são boas as bênçãos que me dás! Como são maravilhosas!

[[v19-16-7]]

^<<v19-16-7,7>>^ Eu louvo a Deus, o Senhor , pois ele é o meu conselheiro, e durante a noite a minha consciência me avisa.

[[v19-16-8]]

^<<v19-16-8,8>>^ Estou certo de que o Senhor está sempre comigo; ele está ao meu lado direito, e nada pode me abalar.

[[v19-16-9]]

^<<v19-16-9,9>>^ Por isso o meu coração está feliz e alegre, e eu, um ser mortal, me sinto bem seguro,

[[v19-16-10]]

^<<v19-16-10,10>>^ porque tu, ó Deus, me proteges do poder da morte. Eu tenho te servido fielmente, e por isso não deixarás que eu desça ao mundo dos mortos .

[[v19-16-11]]

^<<v19-16-11,11>>^ Tu me mostras o caminho que leva à vida. A tua presença me enche de alegria e me traz felicidade para sempre.

'''

xref:019-salmos/019-salmos-015.adoc#v19-15-0[&#60; Capítulo Anterior] | <<v19-16-0,Topo>> | xref:019-salmos/019-salmos-017.adoc#v19-17-0[Próximo Capítulo &#62;]