include::./index.adoc[]

[[v19-46-0]]
=== Salmos, 46
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-46-1]]

^<<v19-46-1,1>>^ Deus é o nosso refúgio e a nossa força, socorro que não falta em tempos de aflição.

[[v19-46-2]]

^<<v19-46-2,2>>^ Por isso, não teremos medo, ainda que a terra seja abalada, e as montanhas caiam nas profundezas do oceano.

[[v19-46-3]]

^<<v19-46-3,3>>^ Não teremos medo, ainda que os mares se agitem e rujam, e os montes tremam violentamente.

[[v19-46-4]]

^<<v19-46-4,4>>^ Há um rio que alegra a cidade de Deus, a casa sagrada do Altíssimo.

[[v19-46-5]]

^<<v19-46-5,5>>^ Deus vive nessa cidade, e ela nunca será destruída; de manhã bem cedo, Deus a ajudará.

[[v19-46-6]]

^<<v19-46-6,6>>^ As nações ficam apavoradas, e os reinos são abalados. Deus troveja, e a terra se desfaz.

[[v19-46-7]]

^<<v19-46-7,7>>^ O Senhor  Todo-Poderoso está do nosso lado; o Deus de Jacó é o nosso refúgio.

[[v19-46-8]]

^<<v19-46-8,8>>^ Venham, vejam o que o Senhor tem feito! Vejam que coisas espantosas ele tem feito na terra!

[[v19-46-9]]

^<<v19-46-9,9>>^ Ele acaba com as guerras no mundo inteiro; quebra os arcos, despedaça as lanças e destrói os escudos  no fogo.

[[v19-46-10]]

^<<v19-46-10,10>>^ Ele diz: "Parem de lutar e fiquem sabendo que eu sou Deus. Eu sou o Rei das nações, o Rei do mundo inteiro."

[[v19-46-11]]

^<<v19-46-11,11>>^ O Senhor  Todo-Poderoso está do nosso lado; o Deus de Jacó é o nosso refúgio.

'''

xref:019-salmos/019-salmos-045.adoc#v19-45-0[&#60; Capítulo Anterior] | <<v19-46-0,Topo>> | xref:019-salmos/019-salmos-047.adoc#v19-47-0[Próximo Capítulo &#62;]