include::./index.adoc[]

[[v19-68-0]]
=== Salmos, 68
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-68-1]]

^<<v19-68-1,1>>^ Deus se levanta e espalha os seus inimigos; os que o odeiam são derrotados e fogem da sua presença.

[[v19-68-2]]

^<<v19-68-2,2>>^ Ele os espalha como a fumaça que desaparece no ar. Os maus se acabam na presença de Deus como a cera se derrete perto do fogo.

[[v19-68-3]]

^<<v19-68-3,3>>^ Mas os bons ficam contentes e felizes na sua presença e, cheios de alegria, cantam hinos.

[[v19-68-4]]

^<<v19-68-4,4>>^ Cantem em louvor a Deus, cantem hinos em sua honra. Preparem o caminho daquele que vem montado nas nuvens. O seu nome é Senhor ; alegrem-se na sua presença.

[[v19-68-5]]

^<<v19-68-5,5>>^ Deus, que vive no seu santo Templo, cuida dos órfãos e protege as viúvas.

[[v19-68-6]]

^<<v19-68-6,6>>^ Ele dá aos abandonados um lar onde eles podem viver e solta os prisioneiros para que vivam livres e felizes. Mas os que se revoltam contra ele terão de morar numa terra deserta.

[[v19-68-7]]

^<<v19-68-7,7>>^ Ó Deus, quando conduziste o teu povo, quando marchaste pelo deserto,

[[v19-68-8]]

^<<v19-68-8,8>>^ a terra tremeu, e o céu derramou chuva por causa da vinda do Deus do Sinai , da vinda do Deus de Israel.

[[v19-68-9]]

^<<v19-68-9,9>>^ Tu fizeste cair muita chuva e renovaste a tua terra cansada.

[[v19-68-10]]

^<<v19-68-10,10>>^ O teu povo fez nessa terra o seu lar; com a tua bondade, cuidaste dos pobres.

[[v19-68-11]]

^<<v19-68-11,11>>^ O Senhor deu uma ordem, e muitas mulheres levaram esta notícia:

[[v19-68-12]]

^<<v19-68-12,12>>^ "Os reis e os seus exércitos estão fugindo!" Em casa, as mulheres repartiram o que havia sido tirado dos inimigos.

[[v19-68-13]]

^<<v19-68-13,13>>^ Elas pareciam pombas cobertas de prata, com asas brilhantes como ouro puro. Por que é que no dia da batalha alguns soldados ficaram no curral das ovelhas?

[[v19-68-14]]

^<<v19-68-14,14>>^ Quando o Deus Todo-Poderoso espalhou os reis, caiu neve ali no monte Salmom.

[[v19-68-15]]

^<<v19-68-15,15>>^ Como é alta a serra de Basã, a serra de muitos picos!

[[v19-68-16]]

^<<v19-68-16,16>>^ Por que é que vocês, montanhas tão altas, olham com inveja para o monte que Deus escolheu para nele morar? O Senhor  Deus viverá ali para sempre.

[[v19-68-17]]

^<<v19-68-17,17>>^ Com os seus milhares e milhares de carros poderosos, Deus, o Senhor, veio do monte Sinai para o seu lugar santo.

[[v19-68-18]]

^<<v19-68-18,18>>^ O Senhor subiu aos lugares mais altos, levando consigo muitos prisioneiros; ele recebeu presentes até mesmo de homens rebeldes. O Senhor  Deus viverá ali.

[[v19-68-19]]

^<<v19-68-19,19>>^ Louvado seja o Senhor, que dia a dia leva as nossas cargas! Deus é a nossa salvação.

[[v19-68-20]]

^<<v19-68-20,20>>^ O nosso Deus é o Deus que salva; ele é o Senhor , o Senhor nosso, que nos livra da morte.

[[v19-68-21]]

^<<v19-68-21,21>>^ Ele partirá a cabeça dos seus inimigos, daqueles que teimam em permanecer nos seus pecados.

[[v19-68-22]]

^<<v19-68-22,22>>^ Deus, o Senhor, nos disse: "Eu trarei os inimigos de vocês de volta do monte Basã. Eu os farei voltar das profundezas do mar

[[v19-68-23]]

^<<v19-68-23,23>>^ para que vocês se banhem no sangue deles e os cães de vocês possam lamber sangue à vontade."

[[v19-68-24]]

^<<v19-68-24,24>>^ Ó Deus, todos veem a tua marcha de vitória, o desfile de Deus, o meu Rei, entrando no seu Templo.

[[v19-68-25]]

^<<v19-68-25,25>>^ Os cantores vão na frente, e os músicos, atrás; no meio, estão as moças tocando tamboris.

[[v19-68-26]]

^<<v19-68-26,26>>^ Louvem a Deus na reunião do seu povo. Louvem a Deus, o Senhor , todos os descendentes de Israel!

[[v19-68-27]]

^<<v19-68-27,27>>^ Primeiro vem Benjamim, a menor das tribos ; depois vêm os líderes de Judá com o seu grupo; e, em seguida, os líderes de Zebulom e de Naftali.

[[v19-68-28]]

^<<v19-68-28,28>>^ Mostra o teu poder, ó Deus, o poder que tens usado em nosso favor!

[[v19-68-29]]

^<<v19-68-29,29>>^ Do teu Templo, em Jerusalém, onde os reis trazem ofertas a ti,

[[v19-68-30]]

^<<v19-68-30,30>>^ repreende o Egito, aquela fera dos canaviais. Ó Deus, repreende as nações, aquela manada de touros com os seus bezerros, até que elas se curvem e te ofereçam a sua prata! Espalha os povos que gostam de fazer guerra.

[[v19-68-31]]

^<<v19-68-31,31>>^ Virão embaixadores do Egito; e os etíopes, com as mãos levantadas, orarão a ti, ó Deus.

[[v19-68-32]]

^<<v19-68-32,32>>^ Cantem hinos a Deus, povos de todas as nações, cantem louvores ao Senhor!

[[v19-68-33]]

^<<v19-68-33,33>>^ Louvem a ele, o cavaleiro do céu, o antigo céu. Escutem a voz do Senhor, a sua voz poderosa.

[[v19-68-34]]

^<<v19-68-34,34>>^ Anunciem o poder de Deus; a majestade dele está sobre o povo de Israel, a sua força está nos céus.

[[v19-68-35]]

^<<v19-68-35,35>>^ Como Deus é maravilhoso no seu Templo! O Deus de Israel dá força e poder ao seu povo. Louvem a Deus.

'''

xref:019-salmos/019-salmos-067.adoc#v19-67-0[&#60; Capítulo Anterior] | <<v19-68-0,Topo>> | xref:019-salmos/019-salmos-069.adoc#v19-69-0[Próximo Capítulo &#62;]