include::./index.adoc[]

[[v19-30-0]]
=== Salmos, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-30-1]]

^<<v19-30-1,1>>^ Ó Senhor  Deus, eu te louvo porque me socorreste e não deixaste que os meus inimigos zombassem de mim.

[[v19-30-2]]

^<<v19-30-2,2>>^ Ó Senhor , meu Deus, eu gritei pedindo ajuda, e tu me curaste,

[[v19-30-3]]

^<<v19-30-3,3>>^ tu me salvaste da morte. Eu estava entre aqueles que iam para o mundo dos mortos , mas tu me fizeste viver novamente.

[[v19-30-4]]

^<<v19-30-4,4>>^ Cantem louvor a Deus, o Senhor , vocês, o seu povo fiel! Lembrem do que o Santo Deus tem feito e lhe deem graças.

[[v19-30-5]]

^<<v19-30-5,5>>^ A sua ira  dura só um momento, mas a sua bondade é para a vida toda. O choro pode durar a noite inteira, mas de manhã vem a alegria.

[[v19-30-6]]

^<<v19-30-6,6>>^ Eu me senti seguro e pensei: "Nunca terei dificuldades."

[[v19-30-7]]

^<<v19-30-7,7>>^ Ó Senhor  Deus, tu foste bom para mim e me protegeste como uma fortaleza nas montanhas. Depois tu te escondeste de mim, e eu fiquei com medo.

[[v19-30-8]]

^<<v19-30-8,8>>^ Ó Senhor  Deus, eu te chamei e pedi a tua ajuda.

[[v19-30-9]]

^<<v19-30-9,9>>^ Se eu morrer, que lucrarás com isso? Será que os mortos podem te louvar? Será que eles podem anunciar que és fiel?

[[v19-30-10]]

^<<v19-30-10,10>>^ Ó Deus, escuta-me e tem compaixão de mim! Ajuda-me, ó Senhor  Deus!

[[v19-30-11]]

^<<v19-30-11,11>>^ Tu mudaste o meu choro em dança alegre, afastaste de mim a tristeza e me cercaste de alegria.

[[v19-30-12]]

^<<v19-30-12,12>>^ Por isso, não ficarei calado, mas cantarei louvores a ti. Ó Senhor , tu és o meu Deus; eu te darei graças para sempre.

'''

xref:019-salmos/019-salmos-029.adoc#v19-29-0[&#60; Capítulo Anterior] | <<v19-30-0,Topo>> | xref:019-salmos/019-salmos-031.adoc#v19-31-0[Próximo Capítulo &#62;]