include::./index.adoc[]

[[v19-72-0]]
=== Salmos, 72
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-72-1]]

^<<v19-72-1,1>>^ Ó Deus, ensina o rei a julgar de acordo com a tua justiça! Dá-lhe a tua justiça

[[v19-72-2]]

^<<v19-72-2,2>>^ para que governe o teu povo com honestidade e trate com justiça os explorados.

[[v19-72-3]]

^<<v19-72-3,3>>^ Que haja prosperidade no país, pois o povo faz o que é direito!

[[v19-72-4]]

^<<v19-72-4,4>>^ Que o rei julgue os pobres honestamente! Que ele ajude os necessitados e derrote os que exploram o povo!

[[v19-72-5]]

^<<v19-72-5,5>>^ Que o rei viva enquanto o sol durar e a lua existir, por gerações  sem fim!

[[v19-72-6]]

^<<v19-72-6,6>>^ Que o rei seja como a chuva que cai sobre os campos, como os aguaceiros que regam a terra!

[[v19-72-7]]

^<<v19-72-7,7>>^ Que a justiça floresça durante a sua vida, e que haja prosperidade enquanto a lua brilhar!

[[v19-72-8]]

^<<v19-72-8,8>>^ O seu reino irá de um mar a outro e desde o rio Eufrates até os fins da terra.

[[v19-72-9]]

^<<v19-72-9,9>>^ Os povos do deserto se curvarão diante dele, e os seus inimigos se humilharão aos seus pés.

[[v19-72-10]]

^<<v19-72-10,10>>^ Os reis da Espanha e das ilhas lhe oferecerão presentes, e assim também os reis da Arábia e da Etiópia.

[[v19-72-11]]

^<<v19-72-11,11>>^ Todos os reis se curvarão diante dele, e todas as nações lhe obedecerão.

[[v19-72-12]]

^<<v19-72-12,12>>^ O rei ajuda os pobres que lhe pedem socorro; ele ajuda os necessitados e os abandonados.

[[v19-72-13]]

^<<v19-72-13,13>>^ Ele tem pena dos fracos e dos necessitados e salva a vida dos que precisam de auxílio.

[[v19-72-14]]

^<<v19-72-14,14>>^ Ele os livra da exploração e da violência; a vida deles é preciosa para ele.

[[v19-72-15]]

^<<v19-72-15,15>>^ Viva o rei! Que ele receba ouro da Arábia! Que todos os dias sejam feitas orações em favor dele, e que Deus sempre o abençoe!

[[v19-72-16]]

^<<v19-72-16,16>>^ Que no país haja fartura de cereais! Que os montes fiquem cobertos de colheitas e produzam tanto quanto os montes Líbanos! Que as cidades fiquem cheias de gente como o capim cobre os campos!

[[v19-72-17]]

^<<v19-72-17,17>>^ Que o nome do rei nunca seja esquecido, e que a sua fama dure enquanto o sol existir! Que todos os povos peçam que Deus os abençoe assim como ele tem abençoado o rei!

[[v19-72-18]]

^<<v19-72-18,18>>^ Louvem o Senhor , o Deus de Israel, pois é ele quem faz essas coisas maravilhosas.

[[v19-72-19]]

^<<v19-72-19,19>>^ Louvem para sempre o seu nome glorioso , e que a sua glória encha o mundo inteiro! Amém ! Amém!

[[v19-72-20]]

^<<v19-72-20,20>>^ Aqui terminam as orações de Davi, filho de Jessé.

'''

xref:019-salmos/019-salmos-071.adoc#v19-71-0[&#60; Capítulo Anterior] | <<v19-72-0,Topo>> | xref:019-salmos/019-salmos-073.adoc#v19-73-0[Próximo Capítulo &#62;]