include::./index.adoc[]

[[v19-143-0]]
=== Salmos, 143
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-143-1]]

^<<v19-143-1,1>>^ Ó Senhor  Deus, ouve a minha oração! Escuta o meu pedido. Responde-me, pois és fiel e bom.

[[v19-143-2]]

^<<v19-143-2,2>>^ Não julgues a mim, este teu servo , pois ninguém é inocente diante de ti.

[[v19-143-3]]

^<<v19-143-3,3>>^ O meu inimigo me perseguiu até me pegar e me derrotou completamente. Ele me pôs numa prisão escura, e eu sou como aqueles que morreram há muito tempo.

[[v19-143-4]]

^<<v19-143-4,4>>^ Por isso, estou quase desistindo, e o desespero despedaça o meu coração.

[[v19-143-5]]

^<<v19-143-5,5>>^ Eu lembro do passado. Penso em tudo o que tens feito e não esqueço as tuas ações.

[[v19-143-6]]

^<<v19-143-6,6>>^ A ti levanto as mãos em oração; como terra seca, eu tenho sede de ti.

[[v19-143-7]]

^<<v19-143-7,7>>^ Ó Senhor  Deus, responde-me depressa, pois já perdi todas as esperanças! Não te escondas de mim para que eu não seja como aqueles que descem ao mundo dos mortos .

[[v19-143-8]]

^<<v19-143-8,8>>^ Peço que todas as manhãs tu me fales do teu amor, pois em ti eu tenho posto a minha confiança. As minhas orações sobem a ti; mostra-me o caminho que devo seguir!

[[v19-143-9]]

^<<v19-143-9,9>>^ Ó Senhor  Deus, livra-me dos meus inimigos, pois em ti encontro proteção!

[[v19-143-10]]

^<<v19-143-10,10>>^ Tu és o meu Deus; ensina-me a fazer a tua vontade. Que o teu Espírito seja bom para mim e me guie por um caminho seguro!

[[v19-143-11]]

^<<v19-143-11,11>>^ Conserva-me vivo, ó Senhor , como prometeste! E, porque és bom, livra-me das minhas aflições.

[[v19-143-12]]

^<<v19-143-12,12>>^ Mata os meus inimigos, pois tens amor por mim; acaba com todos os que me perseguem, pois eu sou teu servo.

'''

xref:019-salmos/019-salmos-142.adoc#v19-142-0[&#60; Capítulo Anterior] | <<v19-143-0,Topo>> | xref:019-salmos/019-salmos-144.adoc#v19-144-0[Próximo Capítulo &#62;]