include::./index.adoc[]

[[v19-59-0]]
=== Salmos, 59
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-59-1]]

^<<v19-59-1,1>>^ Ó meu Deus, livra-me dos meus inimigos! Protege-me daqueles que me atacam.

[[v19-59-2]]

^<<v19-59-2,2>>^ Salva-me dos homens maus; livra-me desses assassinos.

[[v19-59-3]]

^<<v19-59-3,3>>^ Ó Senhor  Deus, olha! Eles estão esperando para me matar. Homens cruéis estão fazendo planos contra mim. Mas não é por causa de qualquer pecado ou maldade que eu tenha feito,

[[v19-59-4]]

^<<v19-59-4,4>>^ nem por causa de alguma falta, que eles têm pressa de me atacar.

[[v19-59-5]]

^<<v19-59-5,5>>^ Ó Senhor , Deus Todo-Poderoso, levanta-te e vem me ajudar! Vê, ó Deus de Israel! Acorda e castiga as nações pagãs; não tenhas pena desses traidores e perversos.

[[v19-59-6]]

^<<v19-59-6,6>>^ Quando anoitece, eles voltam e rodeiam a cidade, rosnando como cachorros.

[[v19-59-7]]

^<<v19-59-7,7>>^ A língua deles fere como espada; eles gritam insultos e ameaças e pensam que ninguém está ouvindo.

[[v19-59-8]]

^<<v19-59-8,8>>^ Mas tu zombas deles, ó Senhor ; tu ris de todos os pagãos.

[[v19-59-9]]

^<<v19-59-9,9>>^ Ó Deus, eu confio no teu poder; tu és a minha fortaleza.

[[v19-59-10]]

^<<v19-59-10,10>>^ Com o seu amor, o meu Deus virá ao meu encontro; ele fará com que eu veja a derrota dos meus inimigos.

[[v19-59-11]]

^<<v19-59-11,11>>^ Ó Deus, não acabes de uma vez com os meus inimigos para que o meu povo não esqueça da maldade deles! Ó Senhor, nosso escudo , espalha-os com o teu poder e derrota-os!

[[v19-59-12]]

^<<v19-59-12,12>>^ Todas as vezes que falam, os meus inimigos pecam; que eles sejam apanhados no seu próprio orgulho! Eles amaldiçoam e mentem;

[[v19-59-13]]

^<<v19-59-13,13>>^ por isso, peço que os destruas quando estiveres irado , e que sejam destruídos completamente. Aí todos saberão que Deus governa em Israel e que o seu Reino se estende pelo mundo inteiro.

[[v19-59-14]]

^<<v19-59-14,14>>^ De noite, os meus inimigos voltam e rodeiam a cidade, rosnando como cachorros.

[[v19-59-15]]

^<<v19-59-15,15>>^ Eles andam pela cidade como cachorros, procurando o que comer, e uivam se não encontram comida que chegue.

[[v19-59-16]]

^<<v19-59-16,16>>^ Porém eu cantarei a respeito do teu poder; de manhã louvarei bem alto o teu amor, pois tu tens sido uma fortaleza para mim, um refúgio nos meus dias de aflição.

[[v19-59-17]]

^<<v19-59-17,17>>^ Eu te louvarei, ó Deus, meu defensor! Tu és a minha fortaleza, tu és o Deus que me ama.

'''

xref:019-salmos/019-salmos-058.adoc#v19-58-0[&#60; Capítulo Anterior] | <<v19-59-0,Topo>> | xref:019-salmos/019-salmos-060.adoc#v19-60-0[Próximo Capítulo &#62;]