include::./index.adoc[]

[[v19-101-0]]
=== Salmos, 101
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-101-1]]

^<<v19-101-1,1>>^ Eu canto a respeito da fidelidade e da justiça; canto hinos a ti, ó Senhor  Deus.

[[v19-101-2]]

^<<v19-101-2,2>>^ Serei honesto em tudo o que fizer. Quando virás para te encontrares comigo? Viverei uma vida correta na minha casa

[[v19-101-3]]

^<<v19-101-3,3>>^ e não deixarei que entre nela nenhum mal. Eu detesto as ações daqueles que se afastam de Deus e não tomarei parte nos seus pecados.

[[v19-101-4]]

^<<v19-101-4,4>>^ Afastarei de mim pensamentos desonestos e não terei nada a ver com a maldade.

[[v19-101-5]]

^<<v19-101-5,5>>^ Destruirei aqueles que falam mal dos outros pelas costas e não suportarei os orgulhosos e os arrogantes.

[[v19-101-6]]

^<<v19-101-6,6>>^ Aprovarei os que são fiéis a Deus e deixarei que morem no meu palácio. Aqueles que vivem uma vida correta poderão trabalhar para mim.

[[v19-101-7]]

^<<v19-101-7,7>>^ Nenhum mentiroso viverá no meu palácio; nenhuma pessoa fingida ficará na minha presença.

[[v19-101-8]]

^<<v19-101-8,8>>^ Cada dia destruirei os maus da nossa terra e expulsarei da cidade do Senhor todos os que praticam o mal.

'''

xref:019-salmos/019-salmos-100.adoc#v19-100-0[&#60; Capítulo Anterior] | <<v19-101-0,Topo>> | xref:019-salmos/019-salmos-102.adoc#v19-102-0[Próximo Capítulo &#62;]