include::./index.adoc[]

[[v19-14-0]]
=== Salmos, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-14-1]]

^<<v19-14-1,1>>^ Os tolos pensam assim: "Para mim, Deus não tem importância." Todos são corruptos e as coisas que eles fazem são nojentas; não há uma só pessoa que faça o bem.

[[v19-14-2]]

^<<v19-14-2,2>>^ Lá do céu o Senhor  Deus olha para a humanidade a fim de ver se existe alguém que tenha juízo, se existe uma só pessoa que o adore.

[[v19-14-3]]

^<<v19-14-3,3>>^ Mas todos se desviaram do caminho certo e são igualmente corruptos. Não há mais ninguém que faça o bem, não há nem mesmo uma só pessoa.

[[v19-14-4]]

^<<v19-14-4,4>>^ O Senhor  pergunta: "Será que toda essa gente má não entende nada? Eles vivem explorando o meu povo e não oram a mim."

[[v19-14-5]]

^<<v19-14-5,5>>^ Mas eles vão tremer de medo porque Deus está do lado daqueles que lhe obedecem.

[[v19-14-6]]

^<<v19-14-6,6>>^ Os maus fazem com que fracassem as esperanças dos necessitados, mas estes são protegidos pelo Senhor .

[[v19-14-7]]

^<<v19-14-7,7>>^ Queira Deus que de Jerusalém venha a vitória para Israel! Como ficarão felizes e alegres os descendentes de Jacó quando o Senhor  fizer com que eles prosperem de novo!

'''

xref:019-salmos/019-salmos-013.adoc#v19-13-0[&#60; Capítulo Anterior] | <<v19-14-0,Topo>> | xref:019-salmos/019-salmos-015.adoc#v19-15-0[Próximo Capítulo &#62;]