include::./index.adoc[]

[[v19-27-0]]
=== Salmos, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-27-1]]

^<<v19-27-1,1>>^ O Senhor  Deus é a minha luz e a minha salvação; de quem terei medo? O Senhor  me livra de todo perigo; não ficarei com medo de ninguém.

[[v19-27-2]]

^<<v19-27-2,2>>^ Quando os maus, os meus inimigos, me atacam e procuram me matar, são eles que tropeçam e caem.

[[v19-27-3]]

^<<v19-27-3,3>>^ Ainda que um exército inteiro me cerque, não terei medo; ainda que os meus inimigos me ataquem, continuarei confiando em Deus.

[[v19-27-4]]

^<<v19-27-4,4>>^ A Deus, o Senhor , pedi uma coisa, e o que eu quero é só isto: que ele me deixe viver na sua casa todos os dias da minha vida, para sentir, maravilhado, a sua bondade e pedir a sua orientação.

[[v19-27-5]]

^<<v19-27-5,5>>^ Em tempos difíceis, ele me esconderá no seu abrigo. Ele me guardará no seu Templo e me colocará em segurança no alto de uma rocha.

[[v19-27-6]]

^<<v19-27-6,6>>^ Assim vencerei os inimigos que me cercam. Com gritos de alegria, oferecerei sacrifícios  no seu Templo; eu cantarei e louvarei a Deus, o Senhor .

[[v19-27-7]]

^<<v19-27-7,7>>^ Ó Senhor , ouve-me quando eu te chamar! Tem compaixão de mim e responde-me.

[[v19-27-8]]

^<<v19-27-8,8>>^ Tu disseste: "Venha me adorar." Eu respondo: "Eu irei te adorar, ó Senhor  Deus."

[[v19-27-9]]

^<<v19-27-9,9>>^ Não te escondas de mim. Não fiques irado  comigo; não rejeites este teu servo . Ó Deus, meu libertador, tu tens sido a minha ajuda; não me deixes, não me abandones.

[[v19-27-10]]

^<<v19-27-10,10>>^ Ainda que o meu pai e a minha mãe me abandonem, o Senhor  cuidará de mim.

[[v19-27-11]]

^<<v19-27-11,11>>^ Ó Senhor  Deus, ensina-me a fazer a tua vontade e guia-me por um caminho seguro, pois os meus inimigos são muitos.

[[v19-27-12]]

^<<v19-27-12,12>>^ Não me entregues nas mãos desses inimigos, que dizem mentiras contra mim e me ameaçam com violência.

[[v19-27-13]]

^<<v19-27-13,13>>^ Estou certo de que verei, ainda nesta vida, o Senhor  Deus mostrar a sua bondade.

[[v19-27-14]]

^<<v19-27-14,14>>^ Confie no Senhor . Tenha fé e coragem. Confie em Deus, o Senhor .

'''

xref:019-salmos/019-salmos-026.adoc#v19-26-0[&#60; Capítulo Anterior] | <<v19-27-0,Topo>> | xref:019-salmos/019-salmos-028.adoc#v19-28-0[Próximo Capítulo &#62;]