include::./index.adoc[]

[[v19-148-0]]
=== Salmos, 148
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-148-1]]

^<<v19-148-1,1>>^ Aleluia ! Todos os que estão nos céus, louvem o Senhor  Deus nas alturas!

[[v19-148-2]]

^<<v19-148-2,2>>^ Louvem o Senhor , todos os seus anjos, todos os seus exércitos celestiais!

[[v19-148-3]]

^<<v19-148-3,3>>^ Sol e lua, louvem o Senhor ! Todas as estrelas brilhantes, louvem a Deus!

[[v19-148-4]]

^<<v19-148-4,4>>^ Que os mais altos céus o louvem e também as águas que estão acima do céu !

[[v19-148-5]]

^<<v19-148-5,5>>^ Que todos eles louvem o Senhor , pois ele deu uma ordem, e eles foram criados!

[[v19-148-6]]

^<<v19-148-6,6>>^ Ele mandou, e foram firmados para sempre nos seus lugares; eles não podem desobedecer.

[[v19-148-7]]

^<<v19-148-7,7>>^ Louve o Senhor , tudo o que existe na terra: monstros do mar e todas as profundezas do oceano!

[[v19-148-8]]

^<<v19-148-8,8>>^ Louvem o Senhor , relâmpagos e chuva de pedra, neve e nuvens, e ventos fortes, que obedecem à sua ordem!

[[v19-148-9]]

^<<v19-148-9,9>>^ Louvem o Senhor , colinas e montanhas, florestas e árvores que dão frutas!

[[v19-148-10]]

^<<v19-148-10,10>>^ Louvem o Senhor , todos os animais, mansos e selvagens! Louvem o Senhor , passarinhos e animais que se arrastam pelo chão!

[[v19-148-11]]

^<<v19-148-11,11>>^ Louvem o Senhor , reis e todos os povos, governantes e todas as outras autoridades!

[[v19-148-12]]

^<<v19-148-12,12>>^ Louvem o Senhor , moços e moças, velhos e crianças!

[[v19-148-13]]

^<<v19-148-13,13>>^ Que todos louvem a Deus, o Senhor , porque ele é superior a todos os outros deuses! A sua glória  está acima da terra e do céu.

[[v19-148-14]]

^<<v19-148-14,14>>^ Ele fez com que a sua nação ficasse cada vez mais forte, e por isso o louvam todos os seus servos  fiéis, o povo de Israel, a quem ele tanto ama. Aleluia!

'''

xref:019-salmos/019-salmos-147.adoc#v19-147-0[&#60; Capítulo Anterior] | <<v19-148-0,Topo>> | xref:019-salmos/019-salmos-149.adoc#v19-149-0[Próximo Capítulo &#62;]