include::./index.adoc[]

[[v19-84-0]]
=== Salmos, 84
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-84-1]]

^<<v19-84-1,1>>^ Como eu amo o teu Templo, ó Senhor  Todo-Poderoso!

[[v19-84-2]]

^<<v19-84-2,2>>^ Como eu gostaria de estar ali! Tenho saudade dos pátios do Templo de Deus, o Senhor . Com todo o meu ser, canto com alegria ao Deus vivo.

[[v19-84-3]]

^<<v19-84-3,3>>^ Ó Senhor  Todo-Poderoso, meu Rei e meu Deus, perto dos teus altares os pardais constroem o seu ninho, e as andorinhas fazem a sua casa, onde cuidam dos seus filhotes.

[[v19-84-4]]

^<<v19-84-4,4>>^ Felizes são os que moram na tua casa, sempre cantando louvores a ti!

[[v19-84-5]]

^<<v19-84-5,5>>^ Felizes são aqueles que de ti recebem forças e que desejam andar pelas estradas que levam ao monte Sião !

[[v19-84-6]]

^<<v19-84-6,6>>^ Quando eles passam pelo Vale das Lágrimas, ele fica cheio de fontes de água, e as primeiras chuvas o cobrem de bênçãos.

[[v19-84-7]]

^<<v19-84-7,7>>^ Enquanto vão indo, a força deles vai aumentando; eles verão o Deus dos deuses em Sião.

[[v19-84-8]]

^<<v19-84-8,8>>^ Escuta a minha oração, ó Senhor , Deus Todo-Poderoso! Ouve-me, ó Deus de Jacó!

[[v19-84-9]]

^<<v19-84-9,9>>^ Ó Deus, abençoa o nosso protetor, o rei que tu escolheste!

[[v19-84-10]]

^<<v19-84-10,10>>^ É melhor passar um dia no teu Templo do que mil dias em qualquer outro lugar. Eu gostaria mais de ficar no portão de entrada da casa do meu Deus do que morar nas casas dos maus.

[[v19-84-11]]

^<<v19-84-11,11>>^ O Senhor  Deus é a nossa luz e o nosso escudo . Ele ama e honra os que fazem o que é certo e lhes dá tudo o que é bom.

[[v19-84-12]]

^<<v19-84-12,12>>^ Ó Senhor  Todo-Poderoso, como são felizes aqueles que confiam em ti!

'''

xref:019-salmos/019-salmos-083.adoc#v19-83-0[&#60; Capítulo Anterior] | <<v19-84-0,Topo>> | xref:019-salmos/019-salmos-085.adoc#v19-85-0[Próximo Capítulo &#62;]