include::./index.adoc[]

[[v19-51-0]]
=== Salmos, 51
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-51-1]]

^<<v19-51-1,1>>^ Por causa do teu amor, ó Deus, tem misericórdia de mim. Por causa da tua grande compaixão apaga os meus pecados.

[[v19-51-2]]

^<<v19-51-2,2>>^ Purifica-me de todas as minhas maldades e lava-me do meu pecado.

[[v19-51-3]]

^<<v19-51-3,3>>^ Pois eu conheço bem os meus erros, e o meu pecado está sempre diante de mim.

[[v19-51-4]]

^<<v19-51-4,4>>^ Contra ti eu pequei — somente contra ti — e fiz o que detestas. Tu tens razão quando me julgas e estás certo quando me condenas.

[[v19-51-5]]

^<<v19-51-5,5>>^ De fato, tenho sido mau desde que nasci; tenho sido pecador desde o dia em que fui concebido .

[[v19-51-6]]

^<<v19-51-6,6>>^ O que tu queres é um coração sincero; enche o meu coração com a tua sabedoria.

[[v19-51-7]]

^<<v19-51-7,7>>^ Tira de mim o meu pecado, e ficarei limpo; lava-me, e ficarei mais branco do que a neve.

[[v19-51-8]]

^<<v19-51-8,8>>^ Faze-me ouvir outra vez os sons de alegria e de felicidade; e, ainda que tenhas me esmagado e quebrado, eu serei feliz de novo.

[[v19-51-9]]

^<<v19-51-9,9>>^ Não olhes para os meus pecados e apaga todas as minhas maldades.

[[v19-51-10]]

^<<v19-51-10,10>>^ Ó Deus, cria em mim um coração puro e dá-me uma vontade nova e firme!

[[v19-51-11]]

^<<v19-51-11,11>>^ Não me expulses da tua presença, nem tires de mim o teu santo Espírito.

[[v19-51-12]]

^<<v19-51-12,12>>^ Dá-me novamente a alegria da tua salvação e conserva em mim o desejo de ser obediente.

[[v19-51-13]]

^<<v19-51-13,13>>^ Então ensinarei aos desobedientes as tuas leis , e eles voltarão a ti.

[[v19-51-14]]

^<<v19-51-14,14>>^ Ó Deus, meu Salvador, livra-me da morte, e com alegria eu anunciarei a tua salvação!

[[v19-51-15]]

^<<v19-51-15,15>>^ Ó Senhor, põe as palavras certas na minha boca, e eu te louvarei!

[[v19-51-16]]

^<<v19-51-16,16>>^ Tu não queres que eu te ofereça sacrifícios ; tu não gostas que animais sejam queimados como oferta a ti.

[[v19-51-17]]

^<<v19-51-17,17>>^ Ó Deus, o meu sacrifício é um espírito humilde; tu não rejeitarás um coração humilde e arrependido.

[[v19-51-18]]

^<<v19-51-18,18>>^ Ó Deus, com a tua bondade, ajuda Jerusalém e constrói de novo as suas muralhas!

[[v19-51-19]]

^<<v19-51-19,19>>^ Então terás prazer em receber os sacrifícios certos e os animais que são totalmente queimados. E touros novos serão oferecidos no teu altar.

'''

xref:019-salmos/019-salmos-050.adoc#v19-50-0[&#60; Capítulo Anterior] | <<v19-51-0,Topo>> | xref:019-salmos/019-salmos-052.adoc#v19-52-0[Próximo Capítulo &#62;]