include::./index.adoc[]

[[v19-50-0]]
=== Salmos, 50
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-50-1]]

^<<v19-50-1,1>>^ Deus, o Senhor  Deus, fala e chama todos os moradores do mundo, de um lado da terra ao outro.

[[v19-50-2]]

^<<v19-50-2,2>>^ Deus brilha lá de Jerusalém, a cidade de perfeita beleza.

[[v19-50-3]]

^<<v19-50-3,3>>^ O nosso Deus está chegando, porém não chega em silêncio. Um fogo destruidor vem na sua frente, e em volta dele há uma violenta tempestade.

[[v19-50-4]]

^<<v19-50-4,4>>^ Ele chama o céu e a terra como testemunhas para assistirem ao julgamento do seu povo.

[[v19-50-5]]

^<<v19-50-5,5>>^ Ele diz: "Reúnam aqueles que são fiéis a mim, aqueles que fizeram uma aliança  comigo, e, como sinal, ofereceram um sacrifício ."

[[v19-50-6]]

^<<v19-50-6,6>>^ Os céus anunciam que Deus é justo e que ele mesmo é quem vai julgar.

[[v19-50-7]]

^<<v19-50-7,7>>^ Deus diz: "Escute, meu povo, que eu vou falar; vou ser testemunha contra você, povo de Israel. Eu sou Deus, o seu Deus.

[[v19-50-8]]

^<<v19-50-8,8>>^ Não vou repreendê-los por causa dos sacrifícios e das ofertas que vocês sempre me trazem.

[[v19-50-9]]

^<<v19-50-9,9>>^ No entanto, eu não preciso dos touros das suas fazendas nem dos bodes dos seus rebanhos.

[[v19-50-10]]

^<<v19-50-10,10>>^ Pois os animais da floresta são meus e também os milhares de cabeças de gado espalhados nas montanhas.

[[v19-50-11]]

^<<v19-50-11,11>>^ São meus todos os pássaros dos montes e tudo o que vive nos campos.

[[v19-50-12]]

^<<v19-50-12,12>>^ "Se eu tivesse fome, não pediria nada a vocês, pois o mundo é meu e tudo o que nele há.

[[v19-50-13]]

^<<v19-50-13,13>>^ Por acaso, preciso comer carne de touros ou beber sangue de bodes?

[[v19-50-14]]

^<<v19-50-14,14>>^ Que a gratidão de vocês seja o sacrifício que oferecem a Deus, e que vocês deem ao Deus Altíssimo tudo aquilo que prometeram!

[[v19-50-15]]

^<<v19-50-15,15>>^ Se me chamarem no dia da aflição, eu os livrarei, e vocês me louvarão."

[[v19-50-16]]

^<<v19-50-16,16>>^ Porém Deus diz aos maus: "Que direito têm vocês de recitar as minhas leis e de falar a respeito da minha aliança?

[[v19-50-17]]

^<<v19-50-17,17>>^ Vocês não querem que eu os corrija e não aceitam as minhas ordens.

[[v19-50-18]]

^<<v19-50-18,18>>^ Vocês ficam amigos de cada ladrão que encontram e andam com pessoas adúlteras.

[[v19-50-19]]

^<<v19-50-19,19>>^ Vocês estão sempre prontos para dizer coisas más e não pensam duas vezes antes de pregar mentiras.

[[v19-50-20]]

^<<v19-50-20,20>>^ Estão sempre acusando os seus irmãos e espalhando calúnias a respeito deles.

[[v19-50-21]]

^<<v19-50-21,21>>^ Vocês fizeram essas coisas, e eu fiquei calado; por isso, pensaram que eu era igual a vocês. Porém agora vou repreendê-los; vou mostrar-lhes os seus erros.

[[v19-50-22]]

^<<v19-50-22,22>>^ "Vocês que esqueceram de mim, pensem bem nisso para que eu não os destrua, sem que ninguém possa salvá-los.

[[v19-50-23]]

^<<v19-50-23,23>>^ Aquele que me traz ofertas de gratidão está me honrando, e eu salvarei todos os que andam nos meus caminhos."

'''

xref:019-salmos/019-salmos-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-salmos/019-salmos-051.adoc#v19-51-0[Próximo Capítulo &#62;]