include::./index.adoc[]

[[v19-31-0]]
=== Salmos, 31
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-31-1]]

^<<v19-31-1,1>>^ Ó Senhor  Deus, em ti eu busco proteção; livra-me da vergonha de ser derrotado. Tu és justo; eu te peço que me ajudes.

[[v19-31-2]]

^<<v19-31-2,2>>^ Ouve-me e salva-me agora. Peço que sejas uma rocha de abrigo, uma defesa para me salvar.

[[v19-31-3]]

^<<v19-31-3,3>>^ Tu és a minha rocha e a minha fortaleza; guia-me e orienta-me como prometeste.

[[v19-31-4]]

^<<v19-31-4,4>>^ Não me deixes cair na armadilha que armaram para mim, pois tu és o meu refúgio;

[[v19-31-5]]

^<<v19-31-5,5>>^ nas tuas mãos entrego a minha vida. Tu me salvarás, ó Senhor , porque tu és Deus fiel.

[[v19-31-6]]

^<<v19-31-6,6>>^ Tu detestas os que adoram deuses falsos; eu, porém, ponho em ti a minha confiança.

[[v19-31-7]]

^<<v19-31-7,7>>^ Ficarei contente e me alegrarei por causa do teu amor. Tu vês que estou sofrendo e conheces as minhas aflições.

[[v19-31-8]]

^<<v19-31-8,8>>^ Não deixaste que os meus inimigos me pegassem e me livraste do perigo.

[[v19-31-9]]

^<<v19-31-9,9>>^ Ó Senhor  Deus, tem compaixão de mim, pois estou aflito! Os meus olhos estão cansados de tanto chorar; estou esgotado de corpo e alma.

[[v19-31-10]]

^<<v19-31-10,10>>^ A tristeza acabou com as minhas forças; as lágrimas encurtam a minha vida. Estou fraco por causa das minhas aflições; até os meus ossos estão se gastando.

[[v19-31-11]]

^<<v19-31-11,11>>^ Os meus inimigos zombam de mim, e os meus vizinhos também caçoam. Os meus conhecidos têm medo de mim e fogem quando me veem na rua.

[[v19-31-12]]

^<<v19-31-12,12>>^ Todos esqueceram de mim, como se eu tivesse morrido; sou como uma coisa que foi jogada fora.

[[v19-31-13]]

^<<v19-31-13,13>>^ Ouço muitos inimigos cochichando; há gente me ameaçando de todos os lados. Eles fazem planos contra mim, procurando um jeito de me matar.

[[v19-31-14]]

^<<v19-31-14,14>>^ Porém a minha confiança está em ti, ó Senhor ; tu és o meu Deus.

[[v19-31-15]]

^<<v19-31-15,15>>^ Tu estás sempre cuidando de mim. Salva-me dos meus inimigos, daqueles que me perseguem.

[[v19-31-16]]

^<<v19-31-16,16>>^ Olha com bondade para mim, teu servo ; salva-me por causa do teu amor.

[[v19-31-17]]

^<<v19-31-17,17>>^ Ó Senhor  Deus, eu estou te chamando. Livra-me da vergonha de ser derrotado. Que os maus sofram essa vergonha e que desçam em silêncio para o mundo dos mortos !

[[v19-31-18]]

^<<v19-31-18,18>>^ Que fiquem calados aqueles mentirosos, aqueles orgulhosos e arrogantes, que falam com desprezo contra as pessoas honestas!

[[v19-31-19]]

^<<v19-31-19,19>>^ Como são maravilhosas as coisas boas que guardas para aqueles que te temem ! Todos podem ver como tu és bom e como proteges os que confiam em ti.

[[v19-31-20]]

^<<v19-31-20,20>>^ Com a proteção da tua presença, tu os livras dos planos dos maus. Num esconderijo seguro, tu os escondes das ofensas dos seus inimigos.

[[v19-31-21]]

^<<v19-31-21,21>>^ Louvado seja Deus, o Senhor ! Quando os meus inimigos me cercaram e me atacaram, ele mostrou, de modo maravilhoso, o seu amor por mim.

[[v19-31-22]]

^<<v19-31-22,22>>^ Fiquei com medo e pensei que ele havia me expulsado da sua presença. Mas ele ouviu o meu grito quando o chamei pedindo ajuda.

[[v19-31-23]]

^<<v19-31-23,23>>^ Amem o Senhor , todos os que lhe são fiéis! Ele protege os que são sinceros, mas os orgulhosos ele castiga como merecem.

[[v19-31-24]]

^<<v19-31-24,24>>^ Sejam fortes e tenham coragem, todos vocês que põem a sua esperança em Deus, o Senhor !

'''

xref:019-salmos/019-salmos-030.adoc#v19-30-0[&#60; Capítulo Anterior] | <<v19-31-0,Topo>> | xref:019-salmos/019-salmos-032.adoc#v19-32-0[Próximo Capítulo &#62;]