include::./index.adoc[]

[[v19-106-0]]
=== Salmos, 106
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-106-1]]

^<<v19-106-1,1>>^ Aleluia ! Deem graças ao Senhor , porque ele é bom e o seu amor dura para sempre.

[[v19-106-2]]

^<<v19-106-2,2>>^ Quem pode contar todas as coisas maravilhosas que ele tem feito? Quem pode louvá-lo como ele merece?

[[v19-106-3]]

^<<v19-106-3,3>>^ Felizes são aqueles que vivem uma vida correta, aqueles que sempre fazem o que é certo!

[[v19-106-4]]

^<<v19-106-4,4>>^ Lembra de mim, ó Senhor , quando abençoares o teu povo; e, quando o libertares, liberta-me também a mim.

[[v19-106-5]]

^<<v19-106-5,5>>^ Deixa que eu veja o teu povo progredir e que eu tome parte na felicidade da tua nação, na alegria daqueles que pertencem a ti.

[[v19-106-6]]

^<<v19-106-6,6>>^ Nós temos sido maus e perversos; pecamos como os nossos antepassados pecaram.

[[v19-106-7]]

^<<v19-106-7,7>>^ Quando estavam no Egito, eles não entenderam os feitos maravilhosos de Deus. Esqueceram que muitas vezes ele havia mostrado o seu amor por eles, e eles se revoltaram perto do mar, o mar Vermelho.

[[v19-106-8]]

^<<v19-106-8,8>>^ Mas, para mostrar o seu grande poder, ele os salvou, como havia prometido.

[[v19-106-9]]

^<<v19-106-9,9>>^ O Senhor  Deus deu ordem, e o mar Vermelho secou; ele fez com que eles o atravessassem como se estivessem pisando terra seca.

[[v19-106-10]]

^<<v19-106-10,10>>^ Ele os livrou das mãos daqueles que os odiavam; ele os salvou dos seus inimigos.

[[v19-106-11]]

^<<v19-106-11,11>>^ As águas cobriram os inimigos; não escapou nem um.

[[v19-106-12]]

^<<v19-106-12,12>>^ Então o seu povo acreditou nas promessas de Deus e cantou louvores a ele.

[[v19-106-13]]

^<<v19-106-13,13>>^ Mas logo esqueceram o que Deus tinha feito e agiram sem esperar o seu conselho.

[[v19-106-14]]

^<<v19-106-14,14>>^ No deserto, eles se deixaram levar pelos seus desejos e puseram Deus à prova.

[[v19-106-15]]

^<<v19-106-15,15>>^ Então ele deu o que pediram, mas lhes mandou também uma doença terrível.

[[v19-106-16]]

^<<v19-106-16,16>>^ Ali, no seu acampamento, eles ficaram com inveja de Moisés e também de Arão, o sacerdote dedicado ao serviço do Senhor .

[[v19-106-17]]

^<<v19-106-17,17>>^ Então a terra se abriu e engoliu Datã; Abirão e a sua família também foram engolidos.

[[v19-106-18]]

^<<v19-106-18,18>>^ Fogo desceu sobre os seguidores deles e queimou aquela gente má.

[[v19-106-19]]

^<<v19-106-19,19>>^ No monte Sinai os israelitas fundiram um bezerro de ouro e adoraram aquele ídolo que haviam feito.

[[v19-106-20]]

^<<v19-106-20,20>>^ Trocaram a glória  de Deus pela imagem de um animal que come capim.

[[v19-106-21]]

^<<v19-106-21,21>>^ Eles esqueceram de Deus, o seu Salvador, que havia feito coisas maravilhosas no Egito.

[[v19-106-22]]

^<<v19-106-22,22>>^ Que coisas extraordinárias Deus fez ali! Que coisas espantosas fez no mar Vermelho!

[[v19-106-23]]

^<<v19-106-23,23>>^ Depois Deus disse que ia destruir os israelitas; porém Moisés, o seu servo escolhido, enfrentou Deus e não deixou que a sua ira os destruísse.

[[v19-106-24]]

^<<v19-106-24,24>>^ Mais tarde, porque não acreditaram na promessa de Deus, eles não quiseram entrar em Canaã, aquela terra tão agradável.

[[v19-106-25]]

^<<v19-106-25,25>>^ Eles ficaram nas suas barracas se queixando e não quiseram dar atenção a Deus, o Senhor .

[[v19-106-26]]

^<<v19-106-26,26>>^ Então o Senhor  lhes deu um aviso solene: ele os faria morrer no deserto,

[[v19-106-27]]

^<<v19-106-27,27>>^ espalharia os seus descendentes entre as nações pagãs, deixando que morressem em países estrangeiros.

[[v19-106-28]]

^<<v19-106-28,28>>^ Depois o povo de Deus se ajuntou no monte Peor para adorar o deus Baal , e eles comeram da carne dos sacrifícios oferecidos a deuses sem vida.

[[v19-106-29]]

^<<v19-106-29,29>>^ Com as suas ações, eles fizeram com que Deus ficasse irado e foram atacados por uma doença terrível.

[[v19-106-30]]

^<<v19-106-30,30>>^ Mas Fineias castigou o culpado, e a doença acabou.

[[v19-106-31]]

^<<v19-106-31,31>>^ Todos têm lembrado dessa boa ação de Fineias, e as gerações  futuras nunca esquecerão delas.

[[v19-106-32]]

^<<v19-106-32,32>>^ Depois, nas fontes de Meribá, o povo fez com que Deus ficasse irado , e quem sofreu por causa disso foi Moisés.

[[v19-106-33]]

^<<v19-106-33,33>>^ Eles fizeram com que Moisés ficasse tão irritado, que ele disse coisas que não devia.

[[v19-106-34]]

^<<v19-106-34,34>>^ Eles não mataram os pagãos como o Senhor  Deus tinha mandado,

[[v19-106-35]]

^<<v19-106-35,35>>^ mas casaram com aquela gente e imitaram os seus costumes pagãos.

[[v19-106-36]]

^<<v19-106-36,36>>^ O povo de Deus adorou ídolos e por causa disso foi destruído.

[[v19-106-37]]

^<<v19-106-37,37>>^ Eles ofereceram os seus próprios filhos e filhas como sacrifício a deuses pagãos.

[[v19-106-38]]

^<<v19-106-38,38>>^ Mataram aquelas crianças inocentes, os seus próprios filhos e filhas, como sacrifício aos ídolos de Canaã. E o país se tornou impuro por causa desse sangue.

[[v19-106-39]]

^<<v19-106-39,39>>^ Fazendo essas coisas, eles se corromperam e foram infiéis a Deus.

[[v19-106-40]]

^<<v19-106-40,40>>^ Então o Senhor  ficou irado com o seu povo, ficou muito aborrecido com eles.

[[v19-106-41]]

^<<v19-106-41,41>>^ Ele os abandonou nas mãos dos pagãos, e estes os dominaram.

[[v19-106-42]]

^<<v19-106-42,42>>^ Os israelitas foram maltratados pelos seus inimigos e ficaram debaixo das ordens deles.

[[v19-106-43]]

^<<v19-106-43,43>>^ Muitas vezes Deus livrou o seu povo, mas eles preferiram se revoltar contra ele e se afundar ainda mais no pecado.

[[v19-106-44]]

^<<v19-106-44,44>>^ Porém, quando pediram a sua ajuda, Deus os ouviu e se voltou para eles quando estavam aflitos.

[[v19-106-45]]

^<<v19-106-45,45>>^ Por causa deles, Deus lembrou da sua aliança e, por causa do seu grande amor, ele mudou de ideia.

[[v19-106-46]]

^<<v19-106-46,46>>^ Deus fez com que aqueles que os levaram como prisioneiros tivessem pena deles.

[[v19-106-47]]

^<<v19-106-47,47>>^ Ó Senhor , nosso Deus, liberta-nos! Tira-nos do meio dos pagãos e leva-nos de volta para a nossa terra. Assim nós te daremos graças e com prazer te louvaremos, ó Santo Deus.

[[v19-106-48]]

^<<v19-106-48,48>>^ Louvemos o Senhor , o Deus de Israel. Louvem o Senhor  agora e sempre. Que todos os povos da terra digam: " Amém "! Aleluia!

'''

xref:019-salmos/019-salmos-105.adoc#v19-105-0[&#60; Capítulo Anterior] | <<v19-106-0,Topo>> | xref:019-salmos/019-salmos-107.adoc#v19-107-0[Próximo Capítulo &#62;]