include::./index.adoc[]

[[v19-122-0]]
=== Salmos, 122
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-122-1]]

^<<v19-122-1,1>>^ Fiquei alegre quando me disseram: "Vamos à casa de Deus, o Senhor ."

[[v19-122-2]]

^<<v19-122-2,2>>^ E agora aqui estamos, dentro de Jerusalém.

[[v19-122-3]]

^<<v19-122-3,3>>^ Jerusalém é uma cidade construída de novo, onde o povo se reúne.

[[v19-122-4]]

^<<v19-122-4,4>>^ Para cá sobem as tribos , as tribos de Israel, para dar graças ao Senhor , como ele ordenou.

[[v19-122-5]]

^<<v19-122-5,5>>^ Aqui estão os tribunais de justiça, onde o rei julga o seu povo.

[[v19-122-6]]

^<<v19-122-6,6>>^ Orem para que haja paz em Jerusalém. "Ó Jerusalém, que prosperem aqueles que a amam!

[[v19-122-7]]

^<<v19-122-7,7>>^ Que haja paz na cidade protegida por muralhas! Que haja segurança nos seus palácios!"

[[v19-122-8]]

^<<v19-122-8,8>>^ Eu amo os meus patrícios e amigos e por isso digo a Jerusalém: "Que a paz esteja com você!"

[[v19-122-9]]

^<<v19-122-9,9>>^ Eu amo o Templo do Senhor , o nosso Deus, e por isso oro pela prosperidade de Jerusalém.

'''

xref:019-salmos/019-salmos-121.adoc#v19-121-0[&#60; Capítulo Anterior] | <<v19-122-0,Topo>> | xref:019-salmos/019-salmos-123.adoc#v19-123-0[Próximo Capítulo &#62;]