include::./index.adoc[]

[[v19-96-0]]
=== Salmos, 96
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-96-1]]

^<<v19-96-1,1>>^ Cantem uma nova canção a Deus, o Senhor . Cantem ao Senhor , todos os povos da terra!

[[v19-96-2]]

^<<v19-96-2,2>>^ Cantem ao Senhor  e o louvem. Anunciem todos os dias que ele nos salvou.

[[v19-96-3]]

^<<v19-96-3,3>>^ Falem da sua glória  às nações; contem a todos os povos as coisas maravilhosas que ele tem feito.

[[v19-96-4]]

^<<v19-96-4,4>>^ O Senhor  é grande e merece todo o nosso louvor; ele deve ser temido mais do que todos os deuses.

[[v19-96-5]]

^<<v19-96-5,5>>^ Pois os deuses das outras nações são somente ídolos, mas o Senhor  fez os céus.

[[v19-96-6]]

^<<v19-96-6,6>>^ Ele está cercado de glória e majestade; poder e beleza enchem o seu Templo.

[[v19-96-7]]

^<<v19-96-7,7>>^ Louvem o Senhor , todos os povos da terra! Louvem a sua glória e o seu poder.

[[v19-96-8]]

^<<v19-96-8,8>>^ Deem ao Senhor  a honra que ele merece; tragam uma oferta e entrem nos pátios do seu Templo.

[[v19-96-9]]

^<<v19-96-9,9>>^ Curvem-se diante do Santo Deus quando ele aparecer; trema diante dele toda a terra.

[[v19-96-10]]

^<<v19-96-10,10>>^ Digam em todas as nações: "O Senhor  é Rei! A terra está firme no seu lugar e não pode ser abalada; ele julgará os povos de acordo com o que é direito."

[[v19-96-11]]

^<<v19-96-11,11>>^ Alegre-se a terra, e fique contente o céu. Ruja o mar e todas as criaturas que nele vivem.

[[v19-96-12]]

^<<v19-96-12,12>>^ Alegrem-se os campos e tudo o que há neles. Então as árvores dos bosques gritarão de alegria diante de Deus, o Senhor ,

[[v19-96-13]]

^<<v19-96-13,13>>^ pois ele vem governar a terra. Com justiça e sem parcialidade, ele governará os povos do mundo.

'''

xref:019-salmos/019-salmos-095.adoc#v19-95-0[&#60; Capítulo Anterior] | <<v19-96-0,Topo>> | xref:019-salmos/019-salmos-097.adoc#v19-97-0[Próximo Capítulo &#62;]