include::./index.adoc[]

[[v19-29-0]]
=== Salmos, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-29-1]]

^<<v19-29-1,1>>^ Anjos, louvem a Deus, o Senhor ; louvem a sua glória  e o seu poder.

[[v19-29-2]]

^<<v19-29-2,2>>^ Deem ao Senhor  a honra que ele merece; curvem-se diante do Senhor , o Santo Deus, quando ele aparecer.

[[v19-29-3]]

^<<v19-29-3,3>>^ A voz do Senhor  é ouvida sobre as águas; o glorioso  Deus troveja, e sobre os mares se ouve a sua voz.

[[v19-29-4]]

^<<v19-29-4,4>>^ A voz do Senhor  é cheia de poder e majestade;

[[v19-29-5]]

^<<v19-29-5,5>>^ a sua voz quebra as árvores de cedro, quebra até os cedros dos montes Líbanos.

[[v19-29-6]]

^<<v19-29-6,6>>^ Os montes Líbanos ele faz saltar como bezerros; o monte Hermom ele faz pular como um boi novo.

[[v19-29-7]]

^<<v19-29-7,7>>^ A voz do Senhor faz brilhar o relâmpago.

[[v19-29-8]]

^<<v19-29-8,8>>^ A sua voz faz tremer o deserto; o Senhor  faz tremer o deserto de Cades.

[[v19-29-9]]

^<<v19-29-9,9>>^ A voz do Senhor sacode os carvalhos e arranca as folhas das árvores. Enquanto isso, no seu Templo, todos gritam: "Glória a Deus!"

[[v19-29-10]]

^<<v19-29-10,10>>^ O Senhor  Deus reina sobre as águas profundas; como Rei ele governa para sempre.

[[v19-29-11]]

^<<v19-29-11,11>>^ O Senhor  dá força ao seu povo e o abençoa, dando-lhe tudo o que é bom.

'''

xref:019-salmos/019-salmos-028.adoc#v19-28-0[&#60; Capítulo Anterior] | <<v19-29-0,Topo>> | xref:019-salmos/019-salmos-030.adoc#v19-30-0[Próximo Capítulo &#62;]