include::./index.adoc[]

[[v19-140-0]]
=== Salmos, 140
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-140-1]]

^<<v19-140-1,1>>^ Ó Senhor  Deus, salva-me dos maus! Livra-me dos homens violentos.

[[v19-140-2]]

^<<v19-140-2,2>>^ Eles vivem planejando o mal e estão sempre provocando brigas.

[[v19-140-3]]

^<<v19-140-3,3>>^ A língua deles parece a língua das cobras venenosas, e as suas palavras são como o veneno das serpentes.

[[v19-140-4]]

^<<v19-140-4,4>>^ Ó Senhor  Deus, protege-me do poder dos maus! Livra-me dos homens violentos, daqueles que procuram fazer com que eu caia na desgraça.

[[v19-140-5]]

^<<v19-140-5,5>>^ Homens orgulhosos armaram uma armadilha e estenderam uma rede no meu caminho; eles puseram armadilhas para me pegar.

[[v19-140-6]]

^<<v19-140-6,6>>^ Eu digo ao Senhor : "Tu és o meu Deus." Ó Senhor , escuta o meu pedido de ajuda!

[[v19-140-7]]

^<<v19-140-7,7>>^ Ó Senhor , meu Deus e meu Salvador, tu me protegeste na batalha.

[[v19-140-8]]

^<<v19-140-8,8>>^ Não dês aos maus o que eles querem, ó Senhor ! Não deixes que os seus planos perversos se realizem.

[[v19-140-9]]

^<<v19-140-9,9>>^ Não deixes que os meus inimigos consigam a vitória; faze com que as suas ameaças contra mim caiam sobre eles mesmos.

[[v19-140-10]]

^<<v19-140-10,10>>^ Que caiam brasas em cima deles! Que sejam jogados num poço e nunca mais possam sair de lá!

[[v19-140-11]]

^<<v19-140-11,11>>^ Que os caluniadores não consigam progredir! Que a maldade persiga, pegue e destrua os homens violentos!

[[v19-140-12]]

^<<v19-140-12,12>>^ Ó Senhor  Deus, eu sei que tu defendes o direito dos pobres e a causa dos necessitados.

[[v19-140-13]]

^<<v19-140-13,13>>^ Os que te obedecem certamente te louvarão e os que são corretos viverão na tua presença.

'''

xref:019-salmos/019-salmos-139.adoc#v19-139-0[&#60; Capítulo Anterior] | <<v19-140-0,Topo>> | xref:019-salmos/019-salmos-141.adoc#v19-141-0[Próximo Capítulo &#62;]