include::./index.adoc[]

[[v19-115-0]]
=== Salmos, 115
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-115-1]]

^<<v19-115-1,1>>^ Somente a ti, ó Senhor  Deus, a ti somente, e não a nós, seja dada a glória por causa do teu amor e da tua fidelidade.

[[v19-115-2]]

^<<v19-115-2,2>>^ Por que é que as outras nações nos perguntam: "Onde está o Deus de vocês?"

[[v19-115-3]]

^<<v19-115-3,3>>^ Nós respondemos: "O nosso Deus está no céu; ele faz tudo o que quer.

[[v19-115-4]]

^<<v19-115-4,4>>^ Os deuses das outras nações são de prata e de ouro, são feitos por seres humanos.

[[v19-115-5]]

^<<v19-115-5,5>>^ Eles têm boca, mas não falam; têm olhos, mas não veem.

[[v19-115-6]]

^<<v19-115-6,6>>^ Têm ouvidos, mas não ouvem; têm nariz, mas não cheiram.

[[v19-115-7]]

^<<v19-115-7,7>>^ Têm mãos, mas não podem pegar; têm pés, mas não andam; e da garganta deles não sai nenhum som.

[[v19-115-8]]

^<<v19-115-8,8>>^ Que fiquem iguais a esses ídolos aqueles que os fazem e os que confiam neles!"

[[v19-115-9]]

^<<v19-115-9,9>>^ Ó israelitas, confiem em Deus, o Senhor ! Ele é a ajuda e o escudo  de vocês.

[[v19-115-10]]

^<<v19-115-10,10>>^ Sacerdotes de Deus, confiem no Senhor ! Ele é a ajuda e o escudo de vocês.

[[v19-115-11]]

^<<v19-115-11,11>>^ Confiem no Senhor , todos os que o temem ! Ele é a ajuda e o escudo de vocês.

[[v19-115-12]]

^<<v19-115-12,12>>^ O Senhor  lembra de nós e nos abençoará; ele abençoará o povo de Israel e todos os sacerdotes de Deus.

[[v19-115-13]]

^<<v19-115-13,13>>^ Ele abençoará todos os que o temem, tanto os importantes como os humildes.

[[v19-115-14]]

^<<v19-115-14,14>>^ Que o Senhor  Deus lhes dê muitos filhos, a vocês e aos seus descendentes!

[[v19-115-15]]

^<<v19-115-15,15>>^ Que vocês sejam abençoados pelo Senhor , que fez os céus e a terra!

[[v19-115-16]]

^<<v19-115-16,16>>^ Os céus pertencem somente ao Senhor , mas a terra ele deu aos seres humanos.

[[v19-115-17]]

^<<v19-115-17,17>>^ Os mortos, que descem à terra do silêncio , não louvam a Deus, o Senhor .

[[v19-115-18]]

^<<v19-115-18,18>>^ Mas nós, que estamos vivos, daremos graças ao Senhor agora e para sempre. Aleluia !

'''

xref:019-salmos/019-salmos-114.adoc#v19-114-0[&#60; Capítulo Anterior] | <<v19-115-0,Topo>> | xref:019-salmos/019-salmos-116.adoc#v19-116-0[Próximo Capítulo &#62;]