include::./index.adoc[]

[[v19-20-0]]
=== Salmos, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-20-1]]

^<<v19-20-1,1>>^ Ó rei, que na hora da angústia o Senhor  Deus responda à sua oração! Que o Deus de Jacó o proteja!

[[v19-20-2]]

^<<v19-20-2,2>>^ Que, do seu Templo, Deus lhe envie socorro, e que, do monte Sião , ele o ajude!

[[v19-20-3]]

^<<v19-20-3,3>>^ Que Deus lembre de todas as suas ofertas e aceite com prazer os seus sacrifícios  queimados no altar!

[[v19-20-4]]

^<<v19-20-4,4>>^ Que Deus satisfaça os seus desejos, ó rei, e permita que todos os seus planos deem certo!

[[v19-20-5]]

^<<v19-20-5,5>>^ Então daremos gritos de alegria pelo seu triunfo e, em louvor ao nosso Deus, levantaremos as bandeiras da vitória. Que o Senhor  atenda todos os seus pedidos, ó rei!

[[v19-20-6]]

^<<v19-20-6,6>>^ Agora sei que o Senhor dá a vitória ao rei que ele escolheu. Do seu santo céu, ele lhe responde e, com o seu grande poder, ele o torna vitorioso.

[[v19-20-7]]

^<<v19-20-7,7>>^ Alguns confiam nos seus carros de guerra, e outros, nos seus cavalos, mas nós confiamos no poder do Senhor , nosso Deus.

[[v19-20-8]]

^<<v19-20-8,8>>^ Eles tropeçarão e cairão, mas nós nos levantaremos e ficaremos firmes.

[[v19-20-9]]

^<<v19-20-9,9>>^ Ó Senhor  Deus, dá a vitória ao rei! Responde-nos quando pedirmos a tua ajuda.

'''

xref:019-salmos/019-salmos-019.adoc#v19-19-0[&#60; Capítulo Anterior] | <<v19-20-0,Topo>> | xref:019-salmos/019-salmos-021.adoc#v19-21-0[Próximo Capítulo &#62;]