include::./index.adoc[]

[[v19-69-0]]
=== Salmos, 69
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-69-1]]

^<<v19-69-1,1>>^ Ó Deus, salva-me porque estou na água até o pescoço!

[[v19-69-2]]

^<<v19-69-2,2>>^ Estou atolado num lamaçal muito fundo, não tenho onde apoiar os pés. Entrei em águas profundas, e a correnteza quase me afoga.

[[v19-69-3]]

^<<v19-69-3,3>>^ Estou rouco de tanto gritar por socorro, e a minha garganta está ardendo. Os meus olhos estão cansados, esperando que tu, meu Deus, venhas me socorrer.

[[v19-69-4]]

^<<v19-69-4,4>>^ Aqueles que, sem motivo, me odeiam são mais numerosos do que os cabelos da minha cabeça. Os meus inimigos contam mentiras a respeito de mim; eles são fortes e querem me matar. Eles me forçam a devolver o que não roubei.

[[v19-69-5]]

^<<v19-69-5,5>>^ Os meus pecados não estão escondidos de ti, ó Deus; tu sabes como tenho sido tolo.

[[v19-69-6]]

^<<v19-69-6,6>>^ Ó Senhor , Deus Todo-Poderoso, não deixes que aqueles que confiam em ti passem vergonha por causa de mim! Ó Deus de Israel, não permitas que eu traga desgraça para aqueles que te adoram!

[[v19-69-7]]

^<<v19-69-7,7>>^ Pois é por causa do meu amor por ti que tenho suportado insultos e tenho passado vergonha.

[[v19-69-8]]

^<<v19-69-8,8>>^ Sou como um estranho para os meus irmãos, sou como um desconhecido para a minha família.

[[v19-69-9]]

^<<v19-69-9,9>>^ O meu amor pelo teu Templo queima dentro de mim como fogo; as ofensas daqueles que te insultam caem sobre mim.

[[v19-69-10]]

^<<v19-69-10,10>>^ Eu faço jejum e me humilho, e, no entanto, eles me insultam.

[[v19-69-11]]

^<<v19-69-11,11>>^ Eu me visto de luto, e eles riem de mim.

[[v19-69-12]]

^<<v19-69-12,12>>^ Falam de mim nas praças, e os bêbados fazem versos a meu respeito.

[[v19-69-13]]

^<<v19-69-13,13>>^ Porém eu, ó Senhor  Deus, faço a minha oração a ti. Ó Deus, responde-me quando achares por bem, pois me amas muito! Salva-me como prometeste.

[[v19-69-14]]

^<<v19-69-14,14>>^ Não me deixes afundar na lama. Livra-me dos meus inimigos e das águas profundas da morte.

[[v19-69-15]]

^<<v19-69-15,15>>^ Não deixes que as ondas me cubram. Não permitas que eu me afogue em águas profundas, nem que seja engolido pela sepultura.

[[v19-69-16]]

^<<v19-69-16,16>>^ Ó Senhor  Deus, tu és bom e amoroso; responde-me e vem me ajudar, pois é grande a tua compaixão.

[[v19-69-17]]

^<<v19-69-17,17>>^ Não te escondas do teu servo ; responde-me agora, pois estou muito aflito.

[[v19-69-18]]

^<<v19-69-18,18>>^ Vem e salva-me; livra-me dos meus inimigos.

[[v19-69-19]]

^<<v19-69-19,19>>^ Tu vês todos os meus inimigos; tu sabes como eles me insultam e conheces a vergonha e as humilhações que tenho sofrido.

[[v19-69-20]]

^<<v19-69-20,20>>^ Os insultos partiram o meu coração, e estou desesperado. Esperei que alguém tivesse pena de mim, mas ninguém teve; esperei que alguém viesse me consolar, porém ninguém apareceu.

[[v19-69-21]]

^<<v19-69-21,21>>^ Quando estava com fome, eles me deram veneno; quando estava com sede, me ofereceram vinagre.

[[v19-69-22]]

^<<v19-69-22,22>>^ Que os seus banquetes sejam a desgraça deles! E que as suas festas religiosas causem a sua queda!

[[v19-69-23]]

^<<v19-69-23,23>>^ Ó Deus, faze com que eles fiquem cegos! Faze com que percam completamente as forças!

[[v19-69-24]]

^<<v19-69-24,24>>^ Descarrega sobre eles a tua ira , e que o fogo do teu furor os alcance!

[[v19-69-25]]

^<<v19-69-25,25>>^ Que os seus acampamentos fiquem desertos! E que ninguém fique vivo nas suas barracas!

[[v19-69-26]]

^<<v19-69-26,26>>^ Eles perseguem aqueles que castigaste e zombam dos sofrimentos daqueles que feriste.

[[v19-69-27]]

^<<v19-69-27,27>>^ Toma nota de todos os pecados deles; não os deixes tomar parte na tua salvação.

[[v19-69-28]]

^<<v19-69-28,28>>^ Que o nome deles seja riscado do livro da vida e que não seja colocado na lista dos que te obedecem!

[[v19-69-29]]

^<<v19-69-29,29>>^ Eu estou sofrendo, desesperado; ó Deus, levanta-me e salva-me!

[[v19-69-30]]

^<<v19-69-30,30>>^ Louvarei a Deus com uma canção; anunciarei com gratidão a sua grandeza.

[[v19-69-31]]

^<<v19-69-31,31>>^ Isso será mais agradável a Deus, o Senhor , do que oferecer em sacrifício um touro crescido.

[[v19-69-32]]

^<<v19-69-32,32>>^ Quando os que são perseguidos virem isso, ficarão contentes, e os que adoram a Deus ficarão animados.

[[v19-69-33]]

^<<v19-69-33,33>>^ Pois o Senhor ouve os necessitados e não despreza o seu povo que está na prisão.

[[v19-69-34]]

^<<v19-69-34,34>>^ Louvem a Deus, ó céu e terra, ó mares e todas as criaturas que estão neles!

[[v19-69-35]]

^<<v19-69-35,35>>^ Ele salvará Jerusalém e construirá de novo as cidades de Judá. O seu povo viverá ali e possuirá a Terra Prometida .

[[v19-69-36]]

^<<v19-69-36,36>>^ Os descendentes dos servos de Deus herdarão essa Terra, e aqueles que o amam viverão ali.

'''

xref:019-salmos/019-salmos-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-salmos/019-salmos-070.adoc#v19-70-0[Próximo Capítulo &#62;]