include::./index.adoc[]

[[v19-85-0]]
=== Salmos, 85
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-85-1]]

^<<v19-85-1,1>>^ Ó Senhor  Deus, tu tens sido bom para a tua terra; fizeste com que Israel prosperasse outra vez.

[[v19-85-2]]

^<<v19-85-2,2>>^ Perdoaste todos os pecados do teu povo e não olhaste para as suas maldades.

[[v19-85-3]]

^<<v19-85-3,3>>^ Acalmaste todo o teu furor e deixaste de lado o fogo da tua ira .

[[v19-85-4]]

^<<v19-85-4,4>>^ Faze com que prosperemos de novo, ó Deus, nosso Salvador, e não continues aborrecido com o teu povo!

[[v19-85-5]]

^<<v19-85-5,5>>^ Será que vais ficar irado para sempre contra nós? Será que a tua ira nunca vai acabar?

[[v19-85-6]]

^<<v19-85-6,6>>^ Dá-nos forças novamente e assim o teu povo se alegrará por causa de ti.

[[v19-85-7]]

^<<v19-85-7,7>>^ Mostra-nos, ó Senhor  Deus, o teu amor e dá-nos a tua salvação!

[[v19-85-8]]

^<<v19-85-8,8>>^ Eu escuto o que o Senhor está dizendo. Para nós, o seu povo, para nós, os que somos fiéis, ele promete paz se não voltarmos aos nossos caminhos de loucura.

[[v19-85-9]]

^<<v19-85-9,9>>^ Na verdade, Deus está pronto para salvar os que o temem a fim de que a sua presença salvadora fique na nossa terra.

[[v19-85-10]]

^<<v19-85-10,10>>^ O amor e a fidelidade se encontrarão; a justiça e a paz se abraçarão.

[[v19-85-11]]

^<<v19-85-11,11>>^ A fidelidade das pessoas brotará da terra, e a justiça de Deus olhará lá do céu.

[[v19-85-12]]

^<<v19-85-12,12>>^ O Senhor  Deus nos dará o que é bom, e a nossa terra produzirá as suas colheitas.

[[v19-85-13]]

^<<v19-85-13,13>>^ A justiça irá adiante do Senhor e preparará o caminho para ele.

'''

xref:019-salmos/019-salmos-084.adoc#v19-84-0[&#60; Capítulo Anterior] | <<v19-85-0,Topo>> | xref:019-salmos/019-salmos-086.adoc#v19-86-0[Próximo Capítulo &#62;]