include::./index.adoc[]

[[v19-40-0]]
=== Salmos, 40
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-40-1]]

^<<v19-40-1,1>>^ Esperei com paciência pela ajuda de Deus, o Senhor . Ele me escutou e ouviu o meu pedido de socorro.

[[v19-40-2]]

^<<v19-40-2,2>>^ Tirou-me de uma cova perigosa, de um poço de lama. Ele me pôs seguro em cima de uma rocha e firmou os meus passos.

[[v19-40-3]]

^<<v19-40-3,3>>^ Ele me ensinou a cantar uma nova canção, um hino de louvor ao nosso Deus. Quando virem isso, muitos temerão  o Senhor e nele porão a sua confiança.

[[v19-40-4]]

^<<v19-40-4,4>>^ Feliz aquele que confia em Deus, o Senhor , que não vai atrás dos ídolos, nem se junta com os que adoram falsos deuses!

[[v19-40-5]]

^<<v19-40-5,5>>^ Ó Senhor , nosso Deus, tu tens feito grandes coisas por nós. Não há ninguém igual a ti. Tu tens feito muitos planos maravilhosos para o nosso bem. Ainda que eu quisesse, não poderia falar de todos eles, pois são tantos, que não podem ser contados.

[[v19-40-6]]

^<<v19-40-6,6>>^ Tu não queres animais oferecidos em sacrifício , nem ofertas de cereais. Não pediste que animais fossem queimados inteiros no altar, nem exigiste sacrifícios oferecidos para tirar pecados. Pelo contrário, tu me deste ouvidos para ouvir,

[[v19-40-7]]

^<<v19-40-7,7>>^ e por isso respondi: "Aqui estou; as tuas instruções para mim estão no Livro da Lei .

[[v19-40-8]]

^<<v19-40-8,8>>^ Eu tenho prazer em fazer a tua vontade, ó meu Deus! Guardo a tua lei  no meu coração."

[[v19-40-9]]

^<<v19-40-9,9>>^ Ó Senhor  Deus, na reunião de todo o teu povo, eu contei a boa notícia de que tu nos salvas. Tu sabes que nunca vou parar de anunciá-la.

[[v19-40-10]]

^<<v19-40-10,10>>^ Não tenho guardado para mim mesmo a notícia da tua salvação. Tenho sempre falado da tua fidelidade e do teu poder salvador. Nas reuniões de todo o teu povo, não fiquei calado a respeito do teu amor e da tua fidelidade.

[[v19-40-11]]

^<<v19-40-11,11>>^ Ó Senhor  Deus, eu sei que nunca deixarás de ser bom para mim. O teu amor e a tua fidelidade sempre me guardarão seguro.

[[v19-40-12]]

^<<v19-40-12,12>>^ Estou rodeado por muitas dificuldades, tantas, que nem posso dizer quantas são. Fui apanhado pelos meus próprios pecados e quase não posso mais enxergar. Tenho mais pecados que cabelos na cabeça e por isso estou muito desanimado.

[[v19-40-13]]

^<<v19-40-13,13>>^ Ó Senhor  Deus, salva-me! Ajuda-me agora.

[[v19-40-14]]

^<<v19-40-14,14>>^ Que sejam completamente derrotados e humilhados aqueles que me querem matar! Que fujam, envergonhados, aqueles que se alegram com as minhas aflições!

[[v19-40-15]]

^<<v19-40-15,15>>^ Que caiam na desgraça e fiquem cheios de confusão aqueles que zombam de mim!

[[v19-40-16]]

^<<v19-40-16,16>>^ Que fiquem alegres e contentes todos os que te adoram! E que os que são gratos pela tua ajuda digam sempre: "Como o Senhor  é grande!"

[[v19-40-17]]

^<<v19-40-17,17>>^ Eu sou pobre e necessitado, mas tu, Senhor, cuidas de mim. Tu és a minha ajuda e o meu libertador; não te demores em me socorrer, ó meu Deus!

'''

xref:019-salmos/019-salmos-039.adoc#v19-39-0[&#60; Capítulo Anterior] | <<v19-40-0,Topo>> | xref:019-salmos/019-salmos-041.adoc#v19-41-0[Próximo Capítulo &#62;]