include::./index.adoc[]

[[v19-79-0]]
=== Salmos, 79
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-79-1]]

^<<v19-79-1,1>>^ Ó Deus, os pagãos invadiram a tua terra, profanaram  o teu santo Templo e deixaram Jerusalém em ruínas.

[[v19-79-2]]

^<<v19-79-2,2>>^ Largaram os corpos dos teus servos , dos que foram fiéis a ti, para serem comidos pelas aves e pelos animais selvagens.

[[v19-79-3]]

^<<v19-79-3,3>>^ Derramaram o sangue do teu povo como se fosse água. O sangue correu como água por toda a cidade de Jerusalém, e não sobrou ninguém para sepultar os mortos.

[[v19-79-4]]

^<<v19-79-4,4>>^ As nações vizinhas nos insultam, riem e caçoam de nós.

[[v19-79-5]]

^<<v19-79-5,5>>^ Ó Senhor  Deus, até quando ficarás irado  conosco? Será para sempre? Será que a tua ira continuará a queimar como fogo?

[[v19-79-6]]

^<<v19-79-6,6>>^ Ó Deus, fica irado com as nações que não te adoram, com os povos que te rejeitam!

[[v19-79-7]]

^<<v19-79-7,7>>^ Pois eles mataram o nosso povo e arrasaram o nosso país.

[[v19-79-8]]

^<<v19-79-8,8>>^ Não nos castigues por causa dos pecados dos nossos antepassados, mas tem misericórdia de nós agora, pois estamos completamente desanimados.

[[v19-79-9]]

^<<v19-79-9,9>>^ Ajuda-nos, ó Deus, nosso Salvador; por causa da tua própria honra, salva-nos e esquece os nossos pecados.

[[v19-79-10]]

^<<v19-79-10,10>>^ Por que deixar que as outras nações perguntem: "Onde está o Deus de vocês?" Ó Deus, permite que vejamos o castigo que lhes darás por terem derramado o sangue dos teus servos!

[[v19-79-11]]

^<<v19-79-11,11>>^ Ouve os gemidos dos prisioneiros e, com o teu grande poder, livra os que estão condenados à morte.

[[v19-79-12]]

^<<v19-79-12,12>>^ Ó Senhor, castiga as outras nações sete vezes pelos insultos com que te ofenderam!

[[v19-79-13]]

^<<v19-79-13,13>>^ Então nós, que somos o teu povo, que somos ovelhas do teu rebanho, nós e os nossos descendentes te daremos graças para sempre e cantaremos hinos de louvor a ti hoje e nos tempos que estão por vir.

'''

xref:019-salmos/019-salmos-078.adoc#v19-78-0[&#60; Capítulo Anterior] | <<v19-79-0,Topo>> | xref:019-salmos/019-salmos-080.adoc#v19-80-0[Próximo Capítulo &#62;]