include::./index.adoc[]

[[v19-149-0]]
=== Salmos, 149
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-149-1]]

^<<v19-149-1,1>>^ Aleluia ! Cantem a Deus, o Senhor , uma nova canção. Louvem a Deus na reunião dos seus servos  fiéis.

[[v19-149-2]]

^<<v19-149-2,2>>^ Alegre-se, ó povo de Israel, por causa do seu Criador! Fique contente, ó povo de Jerusalém, por causa do seu Rei!

[[v19-149-3]]

^<<v19-149-3,3>>^ Louvem a Deus, o Senhor , com danças e, em seu louvor, toquem pandeiros e liras .

[[v19-149-4]]

^<<v19-149-4,4>>^ Pois o Senhor  está contente com o seu povo; ele dá aos humildes a honra da vitória.

[[v19-149-5]]

^<<v19-149-5,5>>^ Que os seus servos fiéis se alegrem com a vitória e cantem alegremente nas suas festas!

[[v19-149-6]]

^<<v19-149-6,6>>^ Que eles louvem a Deus, gritando bem alto, com espadas afiadas nas mãos

[[v19-149-7]]

^<<v19-149-7,7>>^ para derrotar as nações e castigar os povos;

[[v19-149-8]]

^<<v19-149-8,8>>^ para prender os seus reis e as suas autoridades com pesadas correntes de ferro;

[[v19-149-9]]

^<<v19-149-9,9>>^ para castigar as nações como Deus mandou! Essa é a vitória dos seus servos fiéis. Aleluia!

'''

xref:019-salmos/019-salmos-148.adoc#v19-148-0[&#60; Capítulo Anterior] | <<v19-149-0,Topo>> | xref:019-salmos/019-salmos-150.adoc#v19-150-0[Próximo Capítulo &#62;]