include::./index.adoc[]

[[v19-11-0]]
=== Salmos, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-11-1]]

^<<v19-11-1,1>>^ Com Deus, o Senhor , estou seguro. Não adianta me dizerem: "Fuja como um pássaro para as montanhas

[[v19-11-2]]

^<<v19-11-2,2>>^ porque os maus já armaram os seus arcos e de tocaia apontam as flechas para atirar nas pessoas direitas.

[[v19-11-3]]

^<<v19-11-3,3>>^ O que pode fazer a pessoa honesta quando as leis  e os bons costumes são desprezados?"

[[v19-11-4]]

^<<v19-11-4,4>>^ O Senhor  Deus está no seu santo Templo; o seu trono está no céu. Ele vê todas as pessoas e sabe o que elas fazem.

[[v19-11-5]]

^<<v19-11-5,5>>^ O Senhor  examina os que lhe obedecem e também aqueles que são maus; com todo o coração ele detesta os que gostam de praticar violências.

[[v19-11-6]]

^<<v19-11-6,6>>^ Deus faz cair enxofre e brasas sobre os maus; ele os castiga com ventos que queimam como o fogo.

[[v19-11-7]]

^<<v19-11-7,7>>^ O Senhor  faz o que é certo e ama a honestidade; as pessoas que são obedientes a ele viverão na sua presença.

'''

xref:019-salmos/019-salmos-010.adoc#v19-10-0[&#60; Capítulo Anterior] | <<v19-11-0,Topo>> | xref:019-salmos/019-salmos-012.adoc#v19-12-0[Próximo Capítulo &#62;]