include::./index.adoc[]

[[v19-34-0]]
=== Salmos, 34
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-34-1]]

^<<v19-34-1,1>>^ Eu sempre darei graças a Deus, o Senhor ; o seu louvor estará nos meus lábios o dia inteiro.

[[v19-34-2]]

^<<v19-34-2,2>>^ Eu o louvarei por causa das coisas que ele tem feito; os que são perseguidos ouvirão isso e se alegrarão.

[[v19-34-3]]

^<<v19-34-3,3>>^ Anunciem comigo a sua grandeza; louvemos juntos o Senhor .

[[v19-34-4]]

^<<v19-34-4,4>>^ Eu pedi a ajuda do Senhor , e ele me respondeu; ele me livrou de todos os meus medos.

[[v19-34-5]]

^<<v19-34-5,5>>^ Os que são perseguidos olham para ele e se alegram; eles nunca ficarão desapontados.

[[v19-34-6]]

^<<v19-34-6,6>>^ Eu, um pobre sofredor, gritei; o Senhor  me ouviu e me livrou das minhas aflições.

[[v19-34-7]]

^<<v19-34-7,7>>^ O Anjo do Senhor  fica em volta daqueles que o temem e os protege do perigo.

[[v19-34-8]]

^<<v19-34-8,8>>^ Procure descobrir, por você mesmo, como o Senhor  Deus é bom. Feliz aquele que encontra segurança nele!

[[v19-34-9]]

^<<v19-34-9,9>>^ Que todos os que se dedicam a Deus o temam, pois aqueles que o temem não têm falta de nada!

[[v19-34-10]]

^<<v19-34-10,10>>^ Até os leões não têm comida e passam fome, porém não falta nada aos que procuram a ajuda do Senhor .

[[v19-34-11]]

^<<v19-34-11,11>>^ Venham, meus jovens amigos, e escutem, que eu os ensinarei a temer a Deus, o Senhor .

[[v19-34-12]]

^<<v19-34-12,12>>^ Vocês querem aproveitar a vida? Querem viver muito e ser felizes?

[[v19-34-13]]

^<<v19-34-13,13>>^ Então procurem não dizer coisas más e não contem mentiras.

[[v19-34-14]]

^<<v19-34-14,14>>^ Afastem-se do mal e façam o bem; procurem a paz e façam tudo para alcançá-la.

[[v19-34-15]]

^<<v19-34-15,15>>^ Deus cuida das pessoas honestas e ouve os seus pedidos.

[[v19-34-16]]

^<<v19-34-16,16>>^ Mas ele é contra os que fazem o mal; e assim, quando morrem, eles são logo esquecidos.

[[v19-34-17]]

^<<v19-34-17,17>>^ Quando as pessoas honestas chamam o Senhor , ele as ouve e as livra de todas as suas aflições.

[[v19-34-18]]

^<<v19-34-18,18>>^ Ele fica perto dos que estão desanimados e salva os que perderam a esperança.

[[v19-34-19]]

^<<v19-34-19,19>>^ Os bons passam por muitas aflições, mas o Senhor  os livra de todas elas.

[[v19-34-20]]

^<<v19-34-20,20>>^ Ele os protege completamente; nenhum dos seus ossos é quebrado.

[[v19-34-21]]

^<<v19-34-21,21>>^ Os maus serão mortos por causa das suas maldades; aqueles que odeiam os bons serão castigados.

[[v19-34-22]]

^<<v19-34-22,22>>^ O Senhor  Deus salva a vida dos seus servos ; aqueles que procuram a sua proteção não serão condenados.

'''

xref:019-salmos/019-salmos-033.adoc#v19-33-0[&#60; Capítulo Anterior] | <<v19-34-0,Topo>> | xref:019-salmos/019-salmos-035.adoc#v19-35-0[Próximo Capítulo &#62;]