include::./index.adoc[]

[[v19-48-0]]
=== Salmos, 48
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-48-1]]

^<<v19-48-1,1>>^ O Senhor  Deus é grande e merece ser louvado na sua cidade, em Sião , o seu monte santo.

[[v19-48-2]]

^<<v19-48-2,2>>^ O monte de Deus é alto e bonito; a cidade do grande Rei é a alegria do mundo inteiro.

[[v19-48-3]]

^<<v19-48-3,3>>^ Deus tem mostrado que ele dá segurança ao povo dentro das fortalezas da cidade.

[[v19-48-4]]

^<<v19-48-4,4>>^ Os reis se reuniram e juntos vieram atacar o monte Sião.

[[v19-48-5]]

^<<v19-48-5,5>>^ Porém, quando viram a cidade, ficaram espantados e fugiram com medo.

[[v19-48-6]]

^<<v19-48-6,6>>^ Eles ficaram apavorados e aflitos como a mulher que está com dores de parto,

[[v19-48-7]]

^<<v19-48-7,7>>^ como marinheiros em grandes navios sacudidos numa tempestade violenta.

[[v19-48-8]]

^<<v19-48-8,8>>^ Temos ouvido falar das coisas que o Senhor  Deus tem feito e agora vimos o que aconteceu na cidade do nosso Deus, o Senhor  Todo-Poderoso. Ele guardará a cidade em segurança para sempre.

[[v19-48-9]]

^<<v19-48-9,9>>^ No teu Templo, ó Deus, ficamos pensando no teu amor.

[[v19-48-10]]

^<<v19-48-10,10>>^ Tu és louvado por todos os povos, e a tua fama se espalha pelo mundo inteiro, pois tu governas com justiça.

[[v19-48-11]]

^<<v19-48-11,11>>^ Alegre-se, povo de Jerusalém! Ó Deus, os teus julgamentos são justos! Alegrem-se com isso, moradores das cidades de Judá!

[[v19-48-12]]

^<<v19-48-12,12>>^ Povo de Deus, ande em volta de Jerusalém e conte as suas torres!

[[v19-48-13]]

^<<v19-48-13,13>>^ Olhem todos com atenção as suas muralhas e examinem as suas fortalezas. Assim vocês poderão dizer aos seus descendentes:

[[v19-48-14]]

^<<v19-48-14,14>>^ "Este Deus é o nosso Deus para sempre. Ele nos guiará eternamente."

'''

xref:019-salmos/019-salmos-047.adoc#v19-47-0[&#60; Capítulo Anterior] | <<v19-48-0,Topo>> | xref:019-salmos/019-salmos-049.adoc#v19-49-0[Próximo Capítulo &#62;]