include::./index.adoc[]

[[v19-113-0]]
=== Salmos, 113
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-113-1]]

^<<v19-113-1,1>>^ Aleluia ! Servos  de Deus, o Senhor , louvem o seu nome!

[[v19-113-2]]

^<<v19-113-2,2>>^ Que o nome do Senhor  seja louvado agora e para sempre!

[[v19-113-3]]

^<<v19-113-3,3>>^ Desde o nascer até o pôr do sol, que o nome do Senhor  seja louvado!

[[v19-113-4]]

^<<v19-113-4,4>>^ O Senhor  governa todas as nações; a sua glória  está acima dos céus.

[[v19-113-5]]

^<<v19-113-5,5>>^ Não há ninguém como o Senhor , nosso Deus, que tem o seu trono nas alturas,

[[v19-113-6]]

^<<v19-113-6,6>>^ mas se inclina para ver o que há no céu e na terra.

[[v19-113-7]]

^<<v19-113-7,7>>^ Ele livra da humilhação os pobres e tira da miséria os necessitados;

[[v19-113-8]]

^<<v19-113-8,8>>^ ele faz com que eles sejam companheiros de governantes, dos governantes do seu povo.

[[v19-113-9]]

^<<v19-113-9,9>>^ Ele faz com que a mulher que não tem filhos seja respeitada no seu lar e a torna feliz, dando-lhe filhos. Aleluia!

'''

xref:019-salmos/019-salmos-112.adoc#v19-112-0[&#60; Capítulo Anterior] | <<v19-113-0,Topo>> | xref:019-salmos/019-salmos-114.adoc#v19-114-0[Próximo Capítulo &#62;]