include::./index.adoc[]

[[v19-56-0]]
=== Salmos, 56
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-56-1]]

^<<v19-56-1,1>>^ Tem misericórdia de mim, ó Deus, pois estou sendo atacado por inimigos que estão sempre me perseguindo!

[[v19-56-2]]

^<<v19-56-2,2>>^ O dia inteiro eles me atacam, e são muitos os que lutam contra mim.

[[v19-56-3]]

^<<v19-56-3,3>>^ Quando estou com medo, eu confio em ti, ó Deus Todo-Poderoso.

[[v19-56-4]]

^<<v19-56-4,4>>^ Confio em Deus e o louvo pelo que ele tem prometido; confio nele e não terei medo de nada. O que podem me fazer simples seres humanos?

[[v19-56-5]]

^<<v19-56-5,5>>^ O dia inteiro os meus inimigos me atrapalham nos meus negócios e só pensam em me prejudicar.

[[v19-56-6]]

^<<v19-56-6,6>>^ Eles se reúnem em lugares escondidos, olham o que estou fazendo e ficam esperando uma oportunidade para me matar.

[[v19-56-7]]

^<<v19-56-7,7>>^ Ó Deus, castiga-os por causa da sua maldade! Mostra a tua ira e derrota essa gente.

[[v19-56-8]]

^<<v19-56-8,8>>^ Tu sabes como estou aflito, pois tens tomado nota de todas as minhas lágrimas. Será que elas não estão escritas no teu livro?

[[v19-56-9]]

^<<v19-56-9,9>>^ Quando eu pedir a tua ajuda, os meus inimigos fugirão. Uma coisa eu sei: Deus está comigo.

[[v19-56-10]]

^<<v19-56-10,10>>^ Eu louvo a promessa de Deus, a promessa de Deus, o Senhor .

[[v19-56-11]]

^<<v19-56-11,11>>^ Confio nele e não terei medo de nada. O que podem me fazer simples seres humanos?

[[v19-56-12]]

^<<v19-56-12,12>>^ Ó Deus, eu te darei o que prometi, eu te darei a minha oferta de louvor

[[v19-56-13]]

^<<v19-56-13,13>>^ porque me salvaste da morte e não deixaste que eu fosse derrotado. Assim, ó Deus, eu ando na tua presença, eu ando na luz da vida.

'''

xref:019-salmos/019-salmos-055.adoc#v19-55-0[&#60; Capítulo Anterior] | <<v19-56-0,Topo>> | xref:019-salmos/019-salmos-057.adoc#v19-57-0[Próximo Capítulo &#62;]