include::./index.adoc[]

[[v19-81-0]]
=== Salmos, 81
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-81-1]]

^<<v19-81-1,1>>^ Cantem com alegria a Deus, o nosso defensor; cantem louvores ao Deus de Jacó.

[[v19-81-2]]

^<<v19-81-2,2>>^ Comecem a música e toquem os tamboris; toquem músicas alegres nas liras e nas harpas .

[[v19-81-3]]

^<<v19-81-3,3>>^ Toquem a trombeta para a festa quando chegar a lua nova e quando for lua cheia.

[[v19-81-4]]

^<<v19-81-4,4>>^ Isso é lei  para Israel, é uma ordem do Deus de Jacó.

[[v19-81-5]]

^<<v19-81-5,5>>^ Quando Deus marchou contra a terra do Egito, ele deu essa lei ao povo de Israel. Ouvi uma voz, que eu não conhecia, dizendo:

[[v19-81-6]]

^<<v19-81-6,6>>^ "Eu tirei das costas de vocês as cargas pesadas, fiz com que vocês ficassem livres de carregar os cestos cheios de tijolos.

[[v19-81-7]]

^<<v19-81-7,7>>^ Quando estavam aflitos, vocês me chamaram, e eu os salvei. Lá de onde eu estava escondido, na tempestade, eu lhes respondi. Eu os pus à prova na fonte de Meribá.

[[v19-81-8]]

^<<v19-81-8,8>>^ Meu povo, escute os meus conselhos! Ó Israel, como eu gostaria que você me ouvisse!

[[v19-81-9]]

^<<v19-81-9,9>>^ Nunca mais sirvam nenhum deus estrangeiro, nem adorem nenhum deus estranho.

[[v19-81-10]]

^<<v19-81-10,10>>^ Eu sou o Senhor , o Deus de vocês, sou aquele que os tirou da terra do Egito. Abram a boca, e eu os alimentarei.

[[v19-81-11]]

^<<v19-81-11,11>>^ "Mas o meu povo não quis me ouvir; Israel não me obedeceu.

[[v19-81-12]]

^<<v19-81-12,12>>^ Portanto, eu deixei que eles andassem nos seus caminhos de teimosia e que fizessem o que queriam.

[[v19-81-13]]

^<<v19-81-13,13>>^ Como gostaria que o meu povo me ouvisse, que o povo de Israel me obedecesse!

[[v19-81-14]]

^<<v19-81-14,14>>^ Eu derrotaria logo os seus inimigos e castigaria todos os seus adversários.

[[v19-81-15]]

^<<v19-81-15,15>>^ Aqueles que me odeiam se curvariam diante de mim, e o castigo deles duraria para sempre.

[[v19-81-16]]

^<<v19-81-16,16>>^ Mas a vocês eu daria o melhor trigo e os alimentaria com mel do campo, até que ficassem satisfeitos."

'''

xref:019-salmos/019-salmos-080.adoc#v19-80-0[&#60; Capítulo Anterior] | <<v19-81-0,Topo>> | xref:019-salmos/019-salmos-082.adoc#v19-82-0[Próximo Capítulo &#62;]