include::./index.adoc[]

[[v19-86-0]]
=== Salmos, 86
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-86-1]]

^<<v19-86-1,1>>^ Ó Senhor  Deus, escuta-me e responde-me, pois estou fraco e necessitado!

[[v19-86-2]]

^<<v19-86-2,2>>^ Salva-me da morte, pois sou fiel a ti; salva-me porque sou teu servo e confio em ti.

[[v19-86-3]]

^<<v19-86-3,3>>^ Tu és o meu Deus. Tem compaixão de mim, Senhor, pois eu oro a ti o dia inteiro!

[[v19-86-4]]

^<<v19-86-4,4>>^ Ó Senhor, alegra o coração deste teu servo, pois os meus pensamentos sobem a ti!

[[v19-86-5]]

^<<v19-86-5,5>>^ Ó Senhor, tu és bom e perdoador e tens muito amor por todos os que oram a ti.

[[v19-86-6]]

^<<v19-86-6,6>>^ Escuta, ó Senhor , a minha oração e ouve os meus gritos pedindo socorro!

[[v19-86-7]]

^<<v19-86-7,7>>^ Em tempos de angústia eu te chamo, pois tu me respondes.

[[v19-86-8]]

^<<v19-86-8,8>>^ Não há nenhum deus como tu, Senhor; não há nenhum que possa fazer o que tu fazes.

[[v19-86-9]]

^<<v19-86-9,9>>^ Todos os povos que criaste virão e se curvarão diante de ti. Eles louvarão a tua grandeza

[[v19-86-10]]

^<<v19-86-10,10>>^ porque tu és poderoso e fazes coisas maravilhosas. Só tu és Deus.

[[v19-86-11]]

^<<v19-86-11,11>>^ Ó Senhor  Deus, ensina-me o que queres que eu faça, e eu te obedecerei fielmente! Ensina-me a te servir com toda a devoção.

[[v19-86-12]]

^<<v19-86-12,12>>^ Senhor, meu Deus, eu te louvarei com todo o coração e anunciarei a tua grandeza para sempre.

[[v19-86-13]]

^<<v19-86-13,13>>^ Como é grande o teu amor por mim! Tu não deixaste que eu fosse levado para o fundo do mundo dos mortos .

[[v19-86-14]]

^<<v19-86-14,14>>^ Ó Deus, estou sendo atacado por gente orgulhosa. Um bando de pessoas violentas está querendo me matar, pessoas que não querem saber de ti.

[[v19-86-15]]

^<<v19-86-15,15>>^ Mas tu, Senhor, és Deus de compaixão e de amor; és sempre paciente, bondoso e fiel.

[[v19-86-16]]

^<<v19-86-16,16>>^ Olha de novo para mim e tem misericórdia de mim; dá-me a tua força e salva-me, pois eu te sirvo, como te serviu também a minha mãe.

[[v19-86-17]]

^<<v19-86-17,17>>^ Ó Senhor  Deus, dá-me uma prova da tua bondade! Então os que me odeiam verão que tu tens me ajudado e consolado e ficarão envergonhados.

'''

xref:019-salmos/019-salmos-085.adoc#v19-85-0[&#60; Capítulo Anterior] | <<v19-86-0,Topo>> | xref:019-salmos/019-salmos-087.adoc#v19-87-0[Próximo Capítulo &#62;]