include::./index.adoc[]

[[v19-95-0]]
=== Salmos, 95
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-95-1]]

^<<v19-95-1,1>>^ Venham todos, e louvemos a Deus, o Senhor ! Cantemos com alegria à rocha que nos salva.

[[v19-95-2]]

^<<v19-95-2,2>>^ Vamos comparecer diante dele com ações de graças, cantando alegres hinos de louvor.

[[v19-95-3]]

^<<v19-95-3,3>>^ Pois o Senhor  é Deus poderoso; é Rei poderoso acima de todos os deuses.

[[v19-95-4]]

^<<v19-95-4,4>>^ Ele reina sobre o mundo inteiro, desde as cavernas mais profundas até os montes mais altos.

[[v19-95-5]]

^<<v19-95-5,5>>^ O Senhor  reina sobre o mar, que ele fez, e também sobre a terra, que ele mesmo formou.

[[v19-95-6]]

^<<v19-95-6,6>>^ Venham, fiquemos de joelhos e adoremos o Senhor . Vamos nos ajoelhar diante do nosso Criador.

[[v19-95-7]]

^<<v19-95-7,7>>^ Ele é o nosso Deus; nós somos o povo que ele guia, somos o rebanho do qual ele cuida. Escutem hoje o que ele nos diz:

[[v19-95-8]]

^<<v19-95-8,8>>^ "Não sejam teimosos, como os seus antepassados foram em Meribá, quando estavam em Massá, no deserto.

[[v19-95-9]]

^<<v19-95-9,9>>^ Ali eles me puseram à prova e me desafiaram, embora tivessem visto o que eu havia feito por eles.

[[v19-95-10]]

^<<v19-95-10,10>>^ Durante quarenta anos, aquele povo me irritou. Então eu disse: ‘Que gente de coração perverso! Eles não querem obedecer aos meus mandamentos!’

[[v19-95-11]]

^<<v19-95-11,11>>^ Fiquei irado  e fiz este juramento: ‘Vocês nunca entrarão na Terra Prometida , onde eu lhes teria dado descanso.’ "

'''

xref:019-salmos/019-salmos-094.adoc#v19-94-0[&#60; Capítulo Anterior] | <<v19-95-0,Topo>> | xref:019-salmos/019-salmos-096.adoc#v19-96-0[Próximo Capítulo &#62;]