include::./index.adoc[]

[[v19-114-0]]
=== Salmos, 114
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-114-1]]

^<<v19-114-1,1>>^ Quando os descendentes de Jacó, o povo de Israel, saíram do Egito, aquela terra estrangeira,

[[v19-114-2]]

^<<v19-114-2,2>>^ Judá se tornou o povo escolhido de Deus, Israel ficou sendo a sua propriedade.

[[v19-114-3]]

^<<v19-114-3,3>>^ O mar Vermelho olhou e fugiu; o rio Jordão parou de correr.

[[v19-114-4]]

^<<v19-114-4,4>>^ As montanhas pularam como carneiros, e os montes saltaram como carneirinhos.

[[v19-114-5]]

^<<v19-114-5,5>>^ Que aconteceu, ó mar, para que você fugisse assim? E, você, rio Jordão, por que parou de correr?

[[v19-114-6]]

^<<v19-114-6,6>>^ Ó montanhas, por que vocês pularam como carneiros? Montes, por que vocês saltaram como carneirinhos?

[[v19-114-7]]

^<<v19-114-7,7>>^ Trema, ó terra, na vinda do Senhor, na presença do Deus de Jacó,

[[v19-114-8]]

^<<v19-114-8,8>>^ pois ele faz com que as rochas virem fontes e transforma as pedras em fontes de água.

'''

xref:019-salmos/019-salmos-113.adoc#v19-113-0[&#60; Capítulo Anterior] | <<v19-114-0,Topo>> | xref:019-salmos/019-salmos-115.adoc#v19-115-0[Próximo Capítulo &#62;]