include::./index.adoc[]

[[v19-97-0]]
=== Salmos, 97
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-97-1]]

^<<v19-97-1,1>>^ O Senhor  Deus é Rei. Alegre-se a terra! Fiquem contentes, ilhas dos mares!

[[v19-97-2]]

^<<v19-97-2,2>>^ Em volta dele há nuvens e escuridão; as bases do seu reinado são a honestidade e a justiça.

[[v19-97-3]]

^<<v19-97-3,3>>^ Na sua frente, vai um fogo que queima os inimigos ao seu redor.

[[v19-97-4]]

^<<v19-97-4,4>>^ Os seus relâmpagos iluminam o mundo; a terra vê e treme.

[[v19-97-5]]

^<<v19-97-5,5>>^ Os montes se derretem como cera diante do Senhor , diante do Senhor de toda a terra.

[[v19-97-6]]

^<<v19-97-6,6>>^ Os céus anunciam a sua justiça, e todos os povos veem a sua glória .

[[v19-97-7]]

^<<v19-97-7,7>>^ Os que adoram imagens ficam envergonhados; passam vergonha os que se gabam dos seus ídolos. Diante de Deus, o Senhor , todos os deuses se curvam.

[[v19-97-8]]

^<<v19-97-8,8>>^ Por causa dos teus julgamentos, ó Senhor , o povo de Jerusalém está contente, e as cidades de Judá se alegram.

[[v19-97-9]]

^<<v19-97-9,9>>^ Ó Senhor , Deus Altíssimo, tu governas o mundo inteiro, tu estás acima de todos os deuses.

[[v19-97-10]]

^<<v19-97-10,10>>^ Vocês, que amam a Deus, o Senhor , odeiem o mal; ele protege a vida dos que lhe são fiéis e os livra do poder dos maus.

[[v19-97-11]]

^<<v19-97-11,11>>^ A luz ilumina a vida dos honestos, e a alegria ilumina o caminho dos que obedecem a Deus.

[[v19-97-12]]

^<<v19-97-12,12>>^ Que o Senhor  seja a alegria de vocês que são obedientes a ele! Que o Santo Deus seja louvado!

'''

xref:019-salmos/019-salmos-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-salmos/019-salmos-098.adoc#v19-98-0[Próximo Capítulo &#62;]