include::./index.adoc[]

[[v19-136-0]]
=== Salmos, 136
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-136-1]]

^<<v19-136-1,1>>^ Deem graças a Deus, o Senhor , porque ele é bom; o seu amor dura para sempre.

[[v19-136-2]]

^<<v19-136-2,2>>^ Deem graças ao mais poderoso de todos os deuses; o seu amor dura para sempre.

[[v19-136-3]]

^<<v19-136-3,3>>^ Deem graças ao mais poderoso de todos os senhores; o seu amor dura para sempre.

[[v19-136-4]]

^<<v19-136-4,4>>^ Somente o Senhor  faz grandes milagres; o seu amor dura para sempre.

[[v19-136-5]]

^<<v19-136-5,5>>^ Pela sua sabedoria, ele fez os céus; o seu amor dura para sempre.

[[v19-136-6]]

^<<v19-136-6,6>>^ Ele pôs a terra sobre as águas profundas; o seu amor dura para sempre.

[[v19-136-7]]

^<<v19-136-7,7>>^ Ele fez o sol e a lua; o seu amor dura para sempre.

[[v19-136-8]]

^<<v19-136-8,8>>^ Fez o sol para governar o dia; o seu amor dura para sempre.

[[v19-136-9]]

^<<v19-136-9,9>>^ Fez a lua e as estrelas para governarem a noite; o seu amor dura para sempre.

[[v19-136-10]]

^<<v19-136-10,10>>^ Em cada lar dos egípcios, Deus matou o primeiro filho; o seu amor dura para sempre.

[[v19-136-11]]

^<<v19-136-11,11>>^ Ele tirou do Egito o povo de Israel; o seu amor dura para sempre.

[[v19-136-12]]

^<<v19-136-12,12>>^ Ele os tirou com a sua mão forte e com o seu braço poderoso; o seu amor dura para sempre.

[[v19-136-13]]

^<<v19-136-13,13>>^ Ele dividiu o mar Vermelho em duas partes; o seu amor dura para sempre.

[[v19-136-14]]

^<<v19-136-14,14>>^ Fez com que o povo de Israel passasse pelo meio do mar; o seu amor dura para sempre.

[[v19-136-15]]

^<<v19-136-15,15>>^ Ali, no mar, ele afogou o rei do Egito e o seu exército; o seu amor dura para sempre.

[[v19-136-16]]

^<<v19-136-16,16>>^ Deus guiou o seu povo pelo deserto; o seu amor dura para sempre.

[[v19-136-17]]

^<<v19-136-17,17>>^ Matou reis poderosos; o seu amor dura para sempre.

[[v19-136-18]]

^<<v19-136-18,18>>^ Matou reis famosos; o seu amor dura para sempre.

[[v19-136-19]]

^<<v19-136-19,19>>^ Matou Seom, o rei dos amorreus; o seu amor dura para sempre.

[[v19-136-20]]

^<<v19-136-20,20>>^ E matou Ogue, rei de Basã; o seu amor dura para sempre.

[[v19-136-21]]

^<<v19-136-21,21>>^ Ele deu ao seu povo as terras desses reis; o seu amor dura para sempre.

[[v19-136-22]]

^<<v19-136-22,22>>^ Deu essas terras ao povo de Israel, seu servo ; o seu amor dura para sempre.

[[v19-136-23]]

^<<v19-136-23,23>>^ Quando fomos derrotados, Deus não esqueceu de nós; o seu amor dura para sempre.

[[v19-136-24]]

^<<v19-136-24,24>>^ Ele nos livrou dos nossos inimigos; o seu amor dura para sempre.

[[v19-136-25]]

^<<v19-136-25,25>>^ Ele dá comida aos seres humanos e aos animais; o seu amor dura para sempre.

[[v19-136-26]]

^<<v19-136-26,26>>^ Deem graças ao Deus do céu; o seu amor dura para sempre.

'''

xref:019-salmos/019-salmos-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-salmos/019-salmos-137.adoc#v19-137-0[Próximo Capítulo &#62;]