include::./index.adoc[]

[[v19-21-0]]
=== Salmos, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-21-1]]

^<<v19-21-1,1>>^ Ó Senhor  Deus, o rei está muito feliz porque lhe deste força; está muito contente porque o tornaste vitorioso.

[[v19-21-2]]

^<<v19-21-2,2>>^ Tu satisfizeste os seus mais profundos desejos e lhe deste o que ele pediu.

[[v19-21-3]]

^<<v19-21-3,3>>^ Tu o recebeste com bênçãos preciosas e puseste uma coroa de ouro na sua cabeça.

[[v19-21-4]]

^<<v19-21-4,4>>^ O rei pediu vida, e tu lhe deste vida longa, sem fim.

[[v19-21-5]]

^<<v19-21-5,5>>^ A glória  do rei é grande porque tu o ajudaste. Tu lhe deste majestade e fama.

[[v19-21-6]]

^<<v19-21-6,6>>^ As tuas bênçãos estão sobre ele para sempre, e a tua presença lhe dá muita alegria.

[[v19-21-7]]

^<<v19-21-7,7>>^ O rei confia no Senhor , o Deus Altíssimo; e, por causa do amor do Senhor , ele será rei para sempre.

[[v19-21-8]]

^<<v19-21-8,8>>^ O rei prenderá os seus inimigos; com a sua força ele prenderá todos os que o odeiam.

[[v19-21-9]]

^<<v19-21-9,9>>^ Ele aparecerá e os destruirá como um fogo devorador. Na sua ira , o Senhor  os devorará, e o fogo acabará com eles.

[[v19-21-10]]

^<<v19-21-10,10>>^ Nenhum dos seus descendentes ficará vivo; o rei matará todos.

[[v19-21-11]]

^<<v19-21-11,11>>^ Os inimigos planejam maldades e traições contra o rei, porém não terão sucesso.

[[v19-21-12]]

^<<v19-21-12,12>>^ Ele atirará as suas flechas contra eles e os fará fugir.

[[v19-21-13]]

^<<v19-21-13,13>>^ Ó Senhor  Deus, nós te louvaremos por causa do teu poder; nós cantaremos e louvaremos a tua força.

'''

xref:019-salmos/019-salmos-020.adoc#v19-20-0[&#60; Capítulo Anterior] | <<v19-21-0,Topo>> | xref:019-salmos/019-salmos-022.adoc#v19-22-0[Próximo Capítulo &#62;]