include::./index.adoc[]

[[v19-6-0]]
=== Salmos, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-6-1]]

^<<v19-6-1,1>>^ Ó Senhor  Deus, não me repreendas quando estiveres irado ! Não me castigues no teu furor.

[[v19-6-2]]

^<<v19-6-2,2>>^ Tem compaixão de mim, pois me sinto fraco. Dá-me saúde, pois o meu corpo está abatido,

[[v19-6-3]]

^<<v19-6-3,3>>^ e a minha alma está muito aflita. Ó Deus, quando virás me curar?

[[v19-6-4]]

^<<v19-6-4,4>>^ Vem salvar a minha vida, ó Senhor  Deus! Por causa do teu amor, livra-me da morte.

[[v19-6-5]]

^<<v19-6-5,5>>^ Pois no mundo dos mortos não és lembrado, e lá ninguém pode te louvar.

[[v19-6-6]]

^<<v19-6-6,6>>^ Estou cansado de chorar. Todas as noites a minha cama se molha de lágrimas, e o meu choro encharca o travesseiro.

[[v19-6-7]]

^<<v19-6-7,7>>^ Por causa dos meus inimigos, os meus olhos estão inchados de tanto chorar, e quase não posso enxergar.

[[v19-6-8]]

^<<v19-6-8,8>>^ Afastem-se de mim, vocês que fazem o mal! O Senhor  Deus me ouve quando choro;

[[v19-6-9]]

^<<v19-6-9,9>>^ ele me escuta quando peço ajuda e atende as minhas orações.

[[v19-6-10]]

^<<v19-6-10,10>>^ Os meus inimigos ficarão envergonhados e apavorados; eles fugirão de repente, em completa confusão.

'''

xref:019-salmos/019-salmos-005.adoc#v19-5-0[&#60; Capítulo Anterior] | <<v19-6-0,Topo>> | xref:019-salmos/019-salmos-007.adoc#v19-7-0[Próximo Capítulo &#62;]