include::./index.adoc[]

[[v19-142-0]]
=== Salmos, 142
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-142-1]]

^<<v19-142-1,1>>^ Eu clamo a Deus, o Senhor , pedindo socorro; eu suplico que me ajude.

[[v19-142-2]]

^<<v19-142-2,2>>^ Levo a ele todas as minhas queixas e lhe conto todos os meus problemas.

[[v19-142-3]]

^<<v19-142-3,3>>^ Quando estou desistindo, ele sabe o que devo fazer. No caminho por onde ando os meus inimigos armam uma armadilha para me pegar.

[[v19-142-4]]

^<<v19-142-4,4>>^ Olho para os lados e não vejo ninguém que me ajude. Não há ninguém para me proteger, não há ninguém que cuide de mim.

[[v19-142-5]]

^<<v19-142-5,5>>^ Ó Senhor , eu grito pedindo a tua ajuda. Ó Deus, tu és o meu protetor, és tudo o que desejo nesta vida.

[[v19-142-6]]

^<<v19-142-6,6>>^ Escuta o meu grito pedindo socorro, pois estou caindo no desespero. Salva-me dos meus inimigos, pois eles são fortes demais para mim.

[[v19-142-7]]

^<<v19-142-7,7>>^ Livra-me do sofrimento, e eu te louvarei na reunião do teu povo porque tu tens sido bom para mim.

'''

xref:019-salmos/019-salmos-141.adoc#v19-141-0[&#60; Capítulo Anterior] | <<v19-142-0,Topo>> | xref:019-salmos/019-salmos-143.adoc#v19-143-0[Próximo Capítulo &#62;]