include::./index.adoc[]

[[v19-66-0]]
=== Salmos, 66
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-66-1]]

^<<v19-66-1,1>>^ Que todos os povos louvem a Deus com gritos de alegria!

[[v19-66-2]]

^<<v19-66-2,2>>^ Cantem hinos de louvor a ele; ofereçam a ele louvores gloriosos .

[[v19-66-3]]

^<<v19-66-3,3>>^ Digam isto a Deus: "Como são espantosas as coisas que fazes! O teu poder é tão grande, que os teus inimigos ficam com medo e se curvam diante de ti.

[[v19-66-4]]

^<<v19-66-4,4>>^ O mundo inteiro te adora e canta louvores a ti; todos cantam hinos em tua honra."

[[v19-66-5]]

^<<v19-66-5,5>>^ Venham e vejam o que Deus tem feito, vejam com espanto as coisas que ele tem feito em favor das pessoas.

[[v19-66-6]]

^<<v19-66-6,6>>^ Ele mudou o mar em terra seca, e os nossos antepassados atravessaram o rio a pé. Ali nos alegramos com o que ele fez.

[[v19-66-7]]

^<<v19-66-7,7>>^ Pelo seu poder, ele governa para sempre, e os seus olhos vigiam as nações. Que ninguém se revolte contra Deus!

[[v19-66-8]]

^<<v19-66-8,8>>^ Que todas as nações louvem o nosso Deus! Que cantem hinos de louvor em voz alta!

[[v19-66-9]]

^<<v19-66-9,9>>^ Ele nos tem mantido vivos e não nos tem deixado cair.

[[v19-66-10]]

^<<v19-66-10,10>>^ Ó Deus, tu nos puseste à prova. Como a prata é provada pelo fogo, assim nos provaste.

[[v19-66-11]]

^<<v19-66-11,11>>^ Tu nos deixaste cair numa armadilha e colocaste cargas pesadas nas nossas costas.

[[v19-66-12]]

^<<v19-66-12,12>>^ Deixaste que os nossos inimigos nos pisassem. Passamos pelo fogo e pela água, mas agora nos trouxeste para um lugar seguro.

[[v19-66-13]]

^<<v19-66-13,13>>^ Levarei à tua casa os sacrifícios que devem ser completamente queimados; eu te darei o que te prometi.

[[v19-66-14]]

^<<v19-66-14,14>>^ Aquilo que prometi, quando estava em aflição, isso mesmo te darei.

[[v19-66-15]]

^<<v19-66-15,15>>^ Levarei ovelhas para serem queimadas no altar; oferecerei sacrifícios de touros e cabritos, e a fumaça subirá até o céu.

[[v19-66-16]]

^<<v19-66-16,16>>^ Todos vocês que temem a Deus , venham e escutem, e eu contarei o que ele tem feito por mim.

[[v19-66-17]]

^<<v19-66-17,17>>^ Eu gritei, pedindo a sua ajuda; então o louvei com hinos.

[[v19-66-18]]

^<<v19-66-18,18>>^ Mas, se eu tivesse guardado maus pensamentos no coração, o Senhor não teria me ouvido.

[[v19-66-19]]

^<<v19-66-19,19>>^ Porém Deus, de fato, me ouviu e respondeu à minha oração.

[[v19-66-20]]

^<<v19-66-20,20>>^ Eu louvo a Deus porque ele não deixou de ouvir a minha oração e nunca me negou o seu amor.

'''

xref:019-salmos/019-salmos-065.adoc#v19-65-0[&#60; Capítulo Anterior] | <<v19-66-0,Topo>> | xref:019-salmos/019-salmos-067.adoc#v19-67-0[Próximo Capítulo &#62;]