include::./index.adoc[]

[[v19-91-0]]
=== Salmos, 91
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-91-1]]

^<<v19-91-1,1>>^ A pessoa que procura segurança no Deus Altíssimo e se abriga na sombra protetora do Todo-Poderoso

[[v19-91-2]]

^<<v19-91-2,2>>^ pode dizer a ele: "Ó Senhor  Deus, tu és o meu defensor e o meu protetor. Tu és o meu Deus; eu confio em ti."

[[v19-91-3]]

^<<v19-91-3,3>>^ Deus livrará você de perigos escondidos e de doenças mortais.

[[v19-91-4]]

^<<v19-91-4,4>>^ Ele o cobrirá com as suas asas, e debaixo delas você estará seguro. A fidelidade de Deus o protegerá como um escudo .

[[v19-91-5]]

^<<v19-91-5,5>>^ Você não terá medo dos perigos da noite nem de assaltos durante o dia.

[[v19-91-6]]

^<<v19-91-6,6>>^ Não terá medo da peste que se espalha na escuridão nem dos males que matam ao meio-dia.

[[v19-91-7]]

^<<v19-91-7,7>>^ Ainda que mil pessoas sejam mortas ao seu lado, e dez mil, ao seu redor, você não sofrerá nada.

[[v19-91-8]]

^<<v19-91-8,8>>^ Você olhará e verá como os maus são castigados.

[[v19-91-9]]

^<<v19-91-9,9>>^ Você fez do Senhor  Deus o seu protetor e, do Altíssimo, o seu defensor;

[[v19-91-10]]

^<<v19-91-10,10>>^ por isso, nenhum desastre lhe acontecerá, e a violência não chegará perto da sua casa.

[[v19-91-11]]

^<<v19-91-11,11>>^ Deus mandará que os anjos dele cuidem de você para protegê-lo aonde quer que você for.

[[v19-91-12]]

^<<v19-91-12,12>>^ Eles vão segurá-lo com as suas mãos, para que nem mesmo os seus pés sejam feridos nas pedras.

[[v19-91-13]]

^<<v19-91-13,13>>^ Com os pés você esmagará leões e cobras, leões ferozes e serpentes venenosas.

[[v19-91-14]]

^<<v19-91-14,14>>^ Deus diz: "Eu salvarei aqueles que me amam e protegerei os que reconhecem que eu sou Deus, o Senhor .

[[v19-91-15]]

^<<v19-91-15,15>>^ Quando eles me chamarem, eu responderei e estarei com eles nas horas de aflição. Eu os livrarei e farei com que sejam respeitados.

[[v19-91-16]]

^<<v19-91-16,16>>^ Como recompensa, eu lhes darei vida longa e mostrarei que sou o seu Salvador."

'''

xref:019-salmos/019-salmos-090.adoc#v19-90-0[&#60; Capítulo Anterior] | <<v19-91-0,Topo>> | xref:019-salmos/019-salmos-092.adoc#v19-92-0[Próximo Capítulo &#62;]