include::./index.adoc[]

[[v19-65-0]]
=== Salmos, 65
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-65-1]]

^<<v19-65-1,1>>^ É justo, ó Deus, que o povo te louve no monte Sião e te dê o que prometeu,

[[v19-65-2]]

^<<v19-65-2,2>>^ pois tu respondes às orações. Pessoas de toda parte virão te adorar

[[v19-65-3]]

^<<v19-65-3,3>>^ por causa dos seus pecados. As nossas faltas nos deixam derrotados, mas tu nos perdoas.

[[v19-65-4]]

^<<v19-65-4,4>>^ Como são felizes aqueles que tu escolhes, aqueles que trazes para viverem no teu Templo! Nós ficaremos contentes com as coisas boas da tua casa, com as bênçãos do teu santo Templo.

[[v19-65-5]]

^<<v19-65-5,5>>^ Ó Deus, tu nos respondes, dando-nos a vitória, e fazes coisas maravilhosas para nos salvar. Os povos do mundo inteiro, até os dos mares distantes, põem a sua esperança em ti.

[[v19-65-6]]

^<<v19-65-6,6>>^ Com o teu poder, puseste as montanhas no lugar, mostrando assim a tua força poderosa.

[[v19-65-7]]

^<<v19-65-7,7>>^ Tu acalmas o rugido dos mares e o barulho das ondas, tu acalmas a gritaria dos povos.

[[v19-65-8]]

^<<v19-65-8,8>>^ Por causa das grandes coisas que tens feito, o mundo todo está cheio de espanto. Por causa das maravilhas que tens feito há gritos de alegria de um lado da terra ao outro.

[[v19-65-9]]

^<<v19-65-9,9>>^ Fazendo chover, mostras o teu cuidado pela terra e a tornas boa e rica. Com as chuvas do céu enches de água os rios, e assim a terra produz alimentos, pois para isso a preparaste.

[[v19-65-10]]

^<<v19-65-10,10>>^ Regas com muitas chuvas as terras aradas, e elas ficam amolecidas pela água. Com as chuvas, amacias bem as terras, e por isso crescem as plantações.

[[v19-65-11]]

^<<v19-65-11,11>>^ Como é grande a colheita que vem da tua bondade! Por onde passas, há fartura.

[[v19-65-12]]

^<<v19-65-12,12>>^ Os pastos estão cobertos de rebanhos, e os montes se enchem de alegria.

[[v19-65-13]]

^<<v19-65-13,13>>^ Os campos estão cobertos de carneiros, e os vales estão cheios de trigo. Tudo grita e canta de alegria.

'''

xref:019-salmos/019-salmos-064.adoc#v19-64-0[&#60; Capítulo Anterior] | <<v19-65-0,Topo>> | xref:019-salmos/019-salmos-066.adoc#v19-66-0[Próximo Capítulo &#62;]