include::./index.adoc[]

[[v19-87-0]]
=== Salmos, 87
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-87-1]]

^<<v19-87-1,1>>^ O Senhor  Deus construiu a sua cidade sobre o monte sagrado ;

[[v19-87-2]]

^<<v19-87-2,2>>^ ele ama a cidade de Jerusalém mais do que qualquer outro lugar de Israel.

[[v19-87-3]]

^<<v19-87-3,3>>^ Ó cidade de Deus, escute estas coisas maravilhosas que ele diz a seu respeito:

[[v19-87-4]]

^<<v19-87-4,4>>^ "Quando eu fizer a lista das nações que me obedecem, vou pôr nela o nome do Egito e da Babilônia. Os povos da Filisteia, de Tiro e da Etiópia eu tratarei como se eles tivessem nascido em Jerusalém."

[[v19-87-5]]

^<<v19-87-5,5>>^ A respeito de Jerusalém as pessoas dirão que todos os povos são dali e que o Deus Altíssimo a tornará uma cidade forte.

[[v19-87-6]]

^<<v19-87-6,6>>^ O Senhor  escreverá uma lista dos povos, e nela todos eles serão cidadãos de Jerusalém.

[[v19-87-7]]

^<<v19-87-7,7>>^ Os que moram ali vão dançar e cantar, dizendo: "A fonte da nossa felicidade, ó Jerusalém, está em você."

'''

xref:019-salmos/019-salmos-086.adoc#v19-86-0[&#60; Capítulo Anterior] | <<v19-87-0,Topo>> | xref:019-salmos/019-salmos-088.adoc#v19-88-0[Próximo Capítulo &#62;]