include::./index.adoc[]

[[v19-137-0]]
=== Salmos, 137
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-137-1]]

^<<v19-137-1,1>>^ Sentados na beira dos rios da Babilônia, chorávamos quando lembrávamos de Jerusalém.

[[v19-137-2]]

^<<v19-137-2,2>>^ Penduramos as nossas liras nas árvores que havia ali.

[[v19-137-3]]

^<<v19-137-3,3>>^ Aqueles que nos levaram como prisioneiros mandavam que cantássemos. Eles diziam: "Cantem para nós as canções de Sião ."

[[v19-137-4]]

^<<v19-137-4,4>>^ Mas, em terra estrangeira, como podemos cantar um hino a Deus, o Senhor ?

[[v19-137-5]]

^<<v19-137-5,5>>^ Que nunca mais eu possa tocar harpa se esquecer de você, ó Jerusalém!

[[v19-137-6]]

^<<v19-137-6,6>>^ Que nunca mais eu possa cantar se não lembrar de você, se não pensar em você como a maior alegria da minha vida!

[[v19-137-7]]

^<<v19-137-7,7>>^ Lembra, Ó Senhor  Deus, do que os edomitas fizeram no dia em que Jerusalém foi conquistada! Lembra de como diziam: "Arrasem Jerusalém até o chão!"

[[v19-137-8]]

^<<v19-137-8,8>>^ Babilônia, você será destruída! Feliz aquele que fizer com você o mesmo que você fez conosco —

[[v19-137-9]]

^<<v19-137-9,9>>^ aquele que pegar as suas crianças e esmagá-las contra as pedras!

'''

xref:019-salmos/019-salmos-136.adoc#v19-136-0[&#60; Capítulo Anterior] | <<v19-137-0,Topo>> | xref:019-salmos/019-salmos-138.adoc#v19-138-0[Próximo Capítulo &#62;]