include::./index.adoc[]

[[v19-12-0]]
=== Salmos, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-12-1]]

^<<v19-12-1,1>>^ Salva-nos, ó Senhor  Deus, pois já não há mais pessoas de confiança, e os que são fiéis a ti desapareceram da terra.

[[v19-12-2]]

^<<v19-12-2,2>>^ Todos dizem mentiras uns aos outros; um engana o outro com bajulações.

[[v19-12-3]]

^<<v19-12-3,3>>^ Ó Senhor , faze com que esses bajuladores se calem! Fecha a boca dessa gente convencida.

[[v19-12-4]]

^<<v19-12-4,4>>^ Eles dizem: "Com as nossas palavras venceremos; ninguém vai tapar a nossa boca. Quem é que manda em nós?"

[[v19-12-5]]

^<<v19-12-5,5>>^ Mas o Senhor  Deus diz: "Agora eu vou agir porque os necessitados estão sendo oprimidos, e os perseguidos gemem de dor. Eu lhes darei a segurança que tanto esperam."

[[v19-12-6]]

^<<v19-12-6,6>>^ As promessas do Senhor merecem confiança; elas são como a prata pura, refinada sete vezes no fogo.

[[v19-12-7]]

^<<v19-12-7,7>>^ Ó Senhor  Deus, guarda-nos sempre bem-protegidos e livra-nos dos maus,

[[v19-12-8]]

^<<v19-12-8,8>>^ pois eles andam por toda parte, e todas as pessoas dão valor àquilo que é mau.

'''

xref:019-salmos/019-salmos-011.adoc#v19-11-0[&#60; Capítulo Anterior] | <<v19-12-0,Topo>> | xref:019-salmos/019-salmos-013.adoc#v19-13-0[Próximo Capítulo &#62;]