include::./index.adoc[]

[[v19-62-0]]
=== Salmos, 62
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-62-1]]

^<<v19-62-1,1>>^ Somente em Deus eu encontro paz; é dele que vem a minha salvação.

[[v19-62-2]]

^<<v19-62-2,2>>^ Somente ele é a rocha que me salva; ele é o meu protetor, e eu nunca serei derrotado.

[[v19-62-3]]

^<<v19-62-3,3>>^ Até quando todos vocês atacarão um homem que é mais fraco do que uma cerca derrubada?

[[v19-62-4]]

^<<v19-62-4,4>>^ Vocês somente querem tirá-lo do seu lugar de honra. Vocês gostam de mentir; dizem coisas boas a respeito dele, mas no coração o amaldiçoam.

[[v19-62-5]]

^<<v19-62-5,5>>^ Somente em Deus eu encontro paz e nele ponho a minha esperança.

[[v19-62-6]]

^<<v19-62-6,6>>^ Somente ele é a rocha que me salva; ele é o meu protetor, e eu não serei abalado.

[[v19-62-7]]

^<<v19-62-7,7>>^ A minha salvação e a minha honra dependem de Deus; ele é a minha rocha poderosa e o meu abrigo.

[[v19-62-8]]

^<<v19-62-8,8>>^ Confie sempre em Deus, meu povo! Abram o coração para Deus, pois ele é o nosso refúgio.

[[v19-62-9]]

^<<v19-62-9,9>>^ Os seres humanos, tanto os pobres como os ricos, são inúteis, são somente um sopro. Se fossem colocados na balança, não pesariam nada; são mais leves do que um sopro.

[[v19-62-10]]

^<<v19-62-10,10>>^ Não confiem na violência, nem esperem ganhar alguma coisa com o roubo. Ainda que as suas riquezas aumentem, não confiem nelas.

[[v19-62-11]]

^<<v19-62-11,11>>^ Mais de uma vez tenho ouvido Deus dizer que o poder é dele

[[v19-62-12]]

^<<v19-62-12,12>>^ e o amor, também. Tu, ó Senhor, recompensas cada um de acordo com o que faz.

'''

xref:019-salmos/019-salmos-061.adoc#v19-61-0[&#60; Capítulo Anterior] | <<v19-62-0,Topo>> | xref:019-salmos/019-salmos-063.adoc#v19-63-0[Próximo Capítulo &#62;]