include::./index.adoc[]

[[v19-92-0]]
=== Salmos, 92
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-92-1]]

^<<v19-92-1,1>>^ Ó Senhor  Deus, como é bom dar-te graças! Como é bom cantar hinos em tua honra, ó Altíssimo!

[[v19-92-2]]

^<<v19-92-2,2>>^ Como é bom anunciar de manhã o teu amor e de noite, a tua fidelidade,

[[v19-92-3]]

^<<v19-92-3,3>>^ com a música de uma harpa de dez cordas e ao som da lira !

[[v19-92-4]]

^<<v19-92-4,4>>^ Ó Senhor  Deus, os teus feitos poderosos me tornam feliz! Eu canto de alegria pelas coisas que fazes.

[[v19-92-5]]

^<<v19-92-5,5>>^ Que grandes coisas tens feito, ó Senhor ! Como é difícil entender os teus pensamentos!

[[v19-92-6]]

^<<v19-92-6,6>>^ Aqui está uma coisa que o tolo não entende, e o ignorante não pode compreender:

[[v19-92-7]]

^<<v19-92-7,7>>^ os que praticam más ações crescem como a erva, e os perversos podem prosperar, porém eles serão completamente destruídos.

[[v19-92-8]]

^<<v19-92-8,8>>^ Pois tu, ó Senhor , estás para sempre acima de tudo e de todos.

[[v19-92-9]]

^<<v19-92-9,9>>^ Nós sabemos que os teus inimigos morrerão e que todos os maus serão derrotados.

[[v19-92-10]]

^<<v19-92-10,10>>^ Tu me tens tornado forte como um touro selvagem e me tens abençoado com a felicidade.

[[v19-92-11]]

^<<v19-92-11,11>>^ Tenho visto a derrota dos meus inimigos e ouvido os gritos dos maus.

[[v19-92-12]]

^<<v19-92-12,12>>^ Os bons florescem como as palmeiras; eles crescem como os cedros dos montes Líbanos.

[[v19-92-13]]

^<<v19-92-13,13>>^ Eles são como árvores plantadas na casa do Senhor , que florescem nos pátios do Templo do nosso Deus.

[[v19-92-14]]

^<<v19-92-14,14>>^ Na velhice, eles ainda produzem frutos; são sempre fortes e cheios de vida.

[[v19-92-15]]

^<<v19-92-15,15>>^ Isso prova que o Senhor  Deus é justo, prova que ele, a minha rocha, não comete injustiça.

'''

xref:019-salmos/019-salmos-091.adoc#v19-91-0[&#60; Capítulo Anterior] | <<v19-92-0,Topo>> | xref:019-salmos/019-salmos-093.adoc#v19-93-0[Próximo Capítulo &#62;]