include::./index.adoc[]

[[v19-37-0]]
=== Salmos, 37
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-37-1]]

^<<v19-37-1,1>>^ Não se aborreça por causa dos maus, nem tenha inveja dos que praticam o mal.

[[v19-37-2]]

^<<v19-37-2,2>>^ Pois eles vão desaparecer logo como a erva, que seca; eles morrerão como as plantas, que murcham.

[[v19-37-3]]

^<<v19-37-3,3>>^ Confie em Deus, o Senhor , e faça o bem e assim more com toda a segurança na Terra Prometida .

[[v19-37-4]]

^<<v19-37-4,4>>^ Que a sua felicidade esteja no Senhor ! Ele lhe dará o que o seu coração deseja.

[[v19-37-5]]

^<<v19-37-5,5>>^ Ponha a sua vida nas mãos do Senhor , confie nele, e ele o ajudará.

[[v19-37-6]]

^<<v19-37-6,6>>^ Ele fará com que a sua honestidade seja como a luz e com que a justiça da sua causa brilhe como o sol do meio-dia.

[[v19-37-7]]

^<<v19-37-7,7>>^ Não se irrite por causa dos que vencem na vida, nem tenha inveja dos que conseguem realizar os seus planos de maldade. Tenha paciência, pois o Senhor  Deus cuidará disso.

[[v19-37-8]]

^<<v19-37-8,8>>^ Não fique com raiva, não fique furioso. Não se aborreça, pois isso será pior para você.

[[v19-37-9]]

^<<v19-37-9,9>>^ Aqueles que confiam em Deus, o Senhor , viverão em segurança na Terra Prometida, porém os maus serão destruídos.

[[v19-37-10]]

^<<v19-37-10,10>>^ Dentro de pouco tempo, os maus desaparecerão; você poderá procurá-los, porém não os encontrará.

[[v19-37-11]]

^<<v19-37-11,11>>^ Mas os humildes viverão em segurança na Terra Prometida e terão alegria, prosperidade e paz.

[[v19-37-12]]

^<<v19-37-12,12>>^ Os maus fazem planos contra os bons e olham com ódio para eles.

[[v19-37-13]]

^<<v19-37-13,13>>^ O Senhor ri dos maus porque sabe que o dia deles está chegando.

[[v19-37-14]]

^<<v19-37-14,14>>^ Os maus puxam da espada e curvam os seus arcos para matar os pobres e os necessitados e para assassinarem os que são honestos.

[[v19-37-15]]

^<<v19-37-15,15>>^ Mas os maus serão mortos pelas suas próprias espadas, e os seus arcos serão quebrados.

[[v19-37-16]]

^<<v19-37-16,16>>^ É melhor o pouco que os bons têm do que as riquezas de muitos maus.

[[v19-37-17]]

^<<v19-37-17,17>>^ Pois o poder dos maus acabará, mas o Senhor  protege os bons.

[[v19-37-18]]

^<<v19-37-18,18>>^ Todos os dias o Senhor  cuida dos que são corretos; a Terra Prometida será deles para sempre.

[[v19-37-19]]

^<<v19-37-19,19>>^ Quando os tempos forem difíceis, eles não sofrerão e terão o que comer em tempos de fome.

[[v19-37-20]]

^<<v19-37-20,20>>^ Porém os maus morrerão; os inimigos de Deus, o Senhor , desaparecerão como as flores do campo, sumirão como a fumaça.

[[v19-37-21]]

^<<v19-37-21,21>>^ Os maus pedem emprestado e não pagam, mas os bons são generosos em dar.

[[v19-37-22]]

^<<v19-37-22,22>>^ Aqueles que são abençoados por Deus viverão em segurança na Terra Prometida, mas os que ele amaldiçoa serão destruídos.

[[v19-37-23]]

^<<v19-37-23,23>>^ O Senhor  nos guia no caminho em que devemos andar e protege aqueles cuja vida é agradável a ele.

[[v19-37-24]]

^<<v19-37-24,24>>^ Se eles caírem, não ficarão caídos porque o Senhor  os ajudará a se levantarem.

[[v19-37-25]]

^<<v19-37-25,25>>^ Fui moço e agora sou velho, mas nunca vi um homem bom abandonado por Deus e nunca vi os seus filhos mendigando comida.

[[v19-37-26]]

^<<v19-37-26,26>>^ Ele sempre é generoso em dar e emprestar, e os seus filhos são uma bênção.

[[v19-37-27]]

^<<v19-37-27,27>>^ Afaste-se do mal e faça o bem, e você sempre morará na Terra Prometida.

[[v19-37-28]]

^<<v19-37-28,28>>^ Pois o Senhor  ama aquilo que é direito e certo e não abandona os seus servos  fiéis. Ele sempre protege o seu povo, mas os descendentes dos maus serão destruídos.

[[v19-37-29]]

^<<v19-37-29,29>>^ Os bons possuirão a Terra Prometida e sempre morarão nela.

[[v19-37-30]]

^<<v19-37-30,30>>^ Eles dizem coisas sábias e sempre falam o que é direito e certo.

[[v19-37-31]]

^<<v19-37-31,31>>^ Guardam no coração a lei  do seu Deus e nunca se afastam dela.

[[v19-37-32]]

^<<v19-37-32,32>>^ Os maus espiam os bons e procuram matá-los.

[[v19-37-33]]

^<<v19-37-33,33>>^ Porém o Senhor  Deus não abandonará os bons nas mãos do inimigo; e, quando forem julgados, não deixará que sejam condenados.

[[v19-37-34]]

^<<v19-37-34,34>>^ Ponham a sua esperança no Senhor e obedeçam aos seus mandamentos. Ele lhes dará a honra de possuírem a Terra Prometida, e vocês verão os maus serem destruídos.

[[v19-37-35]]

^<<v19-37-35,35>>^ Vi um homem mau, um dominador cruel, que era grandioso como um cedro dos montes Líbanos.

[[v19-37-36]]

^<<v19-37-36,36>>^ Porém um dia passei por ali, e ele já havia desaparecido; eu o procurei, porém não pude encontrá-lo.

[[v19-37-37]]

^<<v19-37-37,37>>^ Preste atenção nos bons, e observe os honestos, e você verá que as pessoas que amam a paz deixam descendentes.

[[v19-37-38]]

^<<v19-37-38,38>>^ Mas os que desobedecem às leis de Deus serão completamente destruídos, e os seus descendentes desaparecerão.

[[v19-37-39]]

^<<v19-37-39,39>>^ O Senhor  Deus salva do perigo os que são bons e os protege em tempos de aflição.

[[v19-37-40]]

^<<v19-37-40,40>>^ O Senhor  os ajuda e livra; e, porque eles procuram a sua proteção, ele os salva dos maus.

'''

xref:019-salmos/019-salmos-036.adoc#v19-36-0[&#60; Capítulo Anterior] | <<v19-37-0,Topo>> | xref:019-salmos/019-salmos-038.adoc#v19-38-0[Próximo Capítulo &#62;]