include::./index.adoc[]

[[v19-138-0]]
=== Salmos, 138
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-138-1]]

^<<v19-138-1,1>>^ Ó Senhor  Deus, eu te agradeço de todo o coração; diante de todos os deuses eu canto hinos de louvor a ti.

[[v19-138-2]]

^<<v19-138-2,2>>^ Por causa do teu amor e da tua fidelidade, eu me ajoelho virado para o teu santo Templo e dou graças a ti. Pois tens mostrado que o teu nome e as tuas promessas estão acima de tudo.

[[v19-138-3]]

^<<v19-138-3,3>>^ Quando te chamei, tu me respondeste e, com o teu poder, aumentaste as minhas forças.

[[v19-138-4]]

^<<v19-138-4,4>>^ Ó Senhor  Deus, todos os reis da terra te louvarão quando ouvirem falar das tuas promessas.

[[v19-138-5]]

^<<v19-138-5,5>>^ Eles cantarão a respeito das coisas que tu, ó Senhor , tens feito, pois grande é a tua glória .

[[v19-138-6]]

^<<v19-138-6,6>>^ Tu estás lá nas alturas, mas assim mesmo te interessas pelos humildes, e os orgulhosos não podem se esconder de ti.

[[v19-138-7]]

^<<v19-138-7,7>>^ Quando estou cercado de perigos, tu me dás segurança. A tua força me protege do ódio dos meus inimigos; tu me salvas pelo teu poder.

[[v19-138-8]]

^<<v19-138-8,8>>^ Tu cumprirás tudo o que me prometeste. O teu amor dura para sempre, ó Senhor  Deus. Não abandones o trabalho que começaste.

'''

xref:019-salmos/019-salmos-137.adoc#v19-137-0[&#60; Capítulo Anterior] | <<v19-138-0,Topo>> | xref:019-salmos/019-salmos-139.adoc#v19-139-0[Próximo Capítulo &#62;]