include::./index.adoc[]

[[v19-49-0]]
=== Salmos, 49
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-49-1]]

^<<v19-49-1,1>>^ Povos, escutem bem isto! Ouçam, todos os moradores do mundo,

[[v19-49-2]]

^<<v19-49-2,2>>^ tanto os poderosos como os humildes, tanto os ricos como os pobres!

[[v19-49-3]]

^<<v19-49-3,3>>^ Os meus pensamentos serão claros; falarei palavras de sabedoria.

[[v19-49-4]]

^<<v19-49-4,4>>^ Vou dar atenção aos provérbios e, enquanto toco a minha lira , vou explicá-los.

[[v19-49-5]]

^<<v19-49-5,5>>^ Eu não sinto medo nas horas de perigo, quando os meus inimigos me cercam.

[[v19-49-6]]

^<<v19-49-6,6>>^ Esses perversos confiam nas suas riquezas e se orgulham das suas grandes fortunas.

[[v19-49-7]]

^<<v19-49-7,7>>^ Mas ninguém pode salvar a si mesmo, nem pagar a Deus o preço da sua vida,

[[v19-49-8]]

^<<v19-49-8,8>>^ pois não há dinheiro que pague a vida de alguém. Por mais dinheiro que uma pessoa tenha,

[[v19-49-9]]

^<<v19-49-9,9>>^ isso não garante que ela nunca vá morrer, que ela vá viver para sempre.

[[v19-49-10]]

^<<v19-49-10,10>>^ Todo mundo vê que até os sábios morrem, e morrem também os tolos e os ignorantes. E todos deixam as suas riquezas para os outros.

[[v19-49-11]]

^<<v19-49-11,11>>^ As suas sepulturas são os seus lares perpétuos, onde eles ficam para sempre, ainda que tenham possuído muitas terras.

[[v19-49-12]]

^<<v19-49-12,12>>^ O ser humano, por mais importante que seja, não pode escapar da morte; como os animais morrem, ele também morre.

[[v19-49-13]]

^<<v19-49-13,13>>^ Reparem no que acontece com os que confiam em si mesmos; vejam o fim daqueles que estão satisfeitos com as suas riquezas.

[[v19-49-14]]

^<<v19-49-14,14>>^ O pastor deles — a morte — os leva, e eles são condenados a morrer como se fossem ovelhas. De manhã, as pessoas corretas os vencerão; os corpos deles apodrecerão na sepultura, longe dos seus lares.

[[v19-49-15]]

^<<v19-49-15,15>>^ Porém Deus me livrará do poder da morte, pois ele me receberá.

[[v19-49-16]]

^<<v19-49-16,16>>^ Não se preocupem quando alguém fica rico, e a sua riqueza aumenta cada vez mais.

[[v19-49-17]]

^<<v19-49-17,17>>^ Pois, quando morrer, ele não poderá levar nada; a sua riqueza não irá com ele para a sepultura.

[[v19-49-18]]

^<<v19-49-18,18>>^ Ainda que esteja contente com a sua vida e seja elogiado por ter sucesso,

[[v19-49-19]]

^<<v19-49-19,19>>^ ele, quando morrer, vai reunir-se com os seus antepassados no lugar onde a escuridão dura para sempre.

[[v19-49-20]]

^<<v19-49-20,20>>^ O ser humano, por mais importante que seja, não pode escapar da morte; como os animais morrem, ele também morre.

'''

xref:019-salmos/019-salmos-048.adoc#v19-48-0[&#60; Capítulo Anterior] | <<v19-49-0,Topo>> | xref:019-salmos/019-salmos-050.adoc#v19-50-0[Próximo Capítulo &#62;]