include::./index.adoc[]

[[v19-44-0]]
=== Salmos, 44
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-44-1]]

^<<v19-44-1,1>>^ Ó Deus, nós ouvimos com os nossos próprios ouvidos aquilo que os nossos antepassados nos contaram. Ouvimos falar das grandes coisas que fizeste no tempo deles, há muitos anos.

[[v19-44-2]]

^<<v19-44-2,2>>^ Eles contaram como expulsaste os povos pagãos e puseste o teu povo na terra deles. Contaram como castigaste as outras nações e fizeste o teu povo progredir.

[[v19-44-3]]

^<<v19-44-3,3>>^ Não foi com espadas que os nossos antepassados conquistaram aquela terra; não foi com o seu próprio poder que eles venceram. Eles venceram com o teu poder, com a tua força e com a luz da tua presença. Assim tu mostraste o teu amor por eles.

[[v19-44-4]]

^<<v19-44-4,4>>^ Tu és o meu Rei e o meu Deus. Tu dás a vitória ao teu povo.

[[v19-44-5]]

^<<v19-44-5,5>>^ Com o teu poder vencemos os nossos inimigos e, com a tua presença, derrotamos os nossos adversários.

[[v19-44-6]]

^<<v19-44-6,6>>^ Não é no meu arco que eu confio, e não é a minha espada que me dá a vitória.

[[v19-44-7]]

^<<v19-44-7,7>>^ Pois foste tu que nos livraste dos nossos inimigos e venceste aqueles que nos odeiam.

[[v19-44-8]]

^<<v19-44-8,8>>^ Nós te louvaremos o dia todo; nós te somos gratos para sempre.

[[v19-44-9]]

^<<v19-44-9,9>>^ Mas agora, ó Deus, tu nos rejeitaste e deixaste que fôssemos derrotados, pois já não acompanhas os nossos exércitos.

[[v19-44-10]]

^<<v19-44-10,10>>^ Tu nos fizeste fugir dos nossos inimigos, e eles levaram embora tudo o que tínhamos.

[[v19-44-11]]

^<<v19-44-11,11>>^ Tu nos trataste como se fôssemos ovelhas que vão para o matadouro e nos espalhaste entre as outras nações.

[[v19-44-12]]

^<<v19-44-12,12>>^ Vendeste barato o teu próprio povo, como se nós tivéssemos pouco valor.

[[v19-44-13]]

^<<v19-44-13,13>>^ Os povos vizinhos, vendo o que nos fizeste, caçoam e zombam de nós.

[[v19-44-14]]

^<<v19-44-14,14>>^ Tu nos fizeste motivo de zombaria para as outras nações; os outros povos nos desprezam.

[[v19-44-15]]

^<<v19-44-15,15>>^ Estou sempre humilhado e coberto de vergonha,

[[v19-44-16]]

^<<v19-44-16,16>>^ ouvindo as zombarias dos meus inimigos e os insultos dos que querem se vingar de mim.

[[v19-44-17]]

^<<v19-44-17,17>>^ Tudo isso nos aconteceu, embora não tivéssemos esquecido de ti, nem tivéssemos quebrado a aliança que fizeste com o teu povo.

[[v19-44-18]]

^<<v19-44-18,18>>^ Não fomos infiéis a ti, nem desobedecemos aos teus mandamentos.

[[v19-44-19]]

^<<v19-44-19,19>>^ Porém tu nos jogaste, esmagados, no lugar onde estão os monstros marinhos e nos deixaste na mais profunda escuridão.

[[v19-44-20]]

^<<v19-44-20,20>>^ Se tivéssemos deixado de adorar o nosso Deus e orado a algum deus pagão,

[[v19-44-21]]

^<<v19-44-21,21>>^ tu certamente ficarias sabendo disso, pois conheces os pensamentos secretos das pessoas.

[[v19-44-22]]

^<<v19-44-22,22>>^ Mas por causa de ti estamos em perigo de morte o dia inteiro; somos tratados como ovelhas que vão para o matadouro.

[[v19-44-23]]

^<<v19-44-23,23>>^ Acorda, Senhor! Por que estás dormindo? Levanta-te. Não nos rejeites para sempre.

[[v19-44-24]]

^<<v19-44-24,24>>^ Por que te escondes de nós? Por que esqueces dos nossos sofrimentos e das nossas aflições?

[[v19-44-25]]

^<<v19-44-25,25>>^ Nós estamos abatidos, caídos no chão; estamos vencidos, jogados no pó.

[[v19-44-26]]

^<<v19-44-26,26>>^ Levanta-te e vem ajudar-nos. Salva-nos por causa do teu amor.

'''

xref:019-salmos/019-salmos-043.adoc#v19-43-0[&#60; Capítulo Anterior] | <<v19-44-0,Topo>> | xref:019-salmos/019-salmos-045.adoc#v19-45-0[Próximo Capítulo &#62;]