include::./index.adoc[]

[[v19-64-0]]
=== Salmos, 64
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-64-1]]

^<<v19-64-1,1>>^ Ó Deus, escuta a minha oração, pois estou em dificuldades! Salva a minha vida, pois tenho medo dos meus inimigos.

[[v19-64-2]]

^<<v19-64-2,2>>^ Protege-me dos planos que os maus fazem contra mim; livra-me dos bandos de homens perversos.

[[v19-64-3]]

^<<v19-64-3,3>>^ Os maus afiam a língua como espada e apontam como flechas as suas palavras cheias de veneno.

[[v19-64-4]]

^<<v19-64-4,4>>^ Eles agem depressa para espalhar as suas mentiras vergonhosas e destroem os bons com calúnias covardes.

[[v19-64-5]]

^<<v19-64-5,5>>^ Eles se animam uns aos outros para fazer o mal; falam dos lugares onde vão colocar as suas armadilhas e pensam que ninguém pode vê-los.

[[v19-64-6]]

^<<v19-64-6,6>>^ Fazem planos cheios de maldade e dizem: "Planejamos um crime perfeito." O coração e a mente do ser humano são um mistério.

[[v19-64-7]]

^<<v19-64-7,7>>^ Porém Deus atirará as suas flechas contra eles, e, de repente, ficarão feridos.

[[v19-64-8]]

^<<v19-64-8,8>>^ Deus os destruirá por causa das suas palavras; aqueles que os virem balançarão a cabeça, caçoando deles.

[[v19-64-9]]

^<<v19-64-9,9>>^ Então todas as pessoas ficarão com medo; pensarão no que Deus fez e falarão sobre os seus atos poderosos.

[[v19-64-10]]

^<<v19-64-10,10>>^ A alegria daqueles que obedecem ao Senhor  Deus vem dele; é no Senhor  que eles encontram segurança. Todos eles lhe darão glória .

'''

xref:019-salmos/019-salmos-063.adoc#v19-63-0[&#60; Capítulo Anterior] | <<v19-64-0,Topo>> | xref:019-salmos/019-salmos-065.adoc#v19-65-0[Próximo Capítulo &#62;]