include::./index.adoc[]

[[v19-108-0]]
=== Salmos, 108
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v19-108-1]]

^<<v19-108-1,1>>^ O meu coração está firme, ó Deus, bem firme; eu cantarei hinos em teu louvor. Acorde, meu coração!

[[v19-108-2]]

^<<v19-108-2,2>>^ Minha harpa  e minha lira , acordem! Eu acordarei o sol.

[[v19-108-3]]

^<<v19-108-3,3>>^ Ó Senhor  Deus, eu te darei graças no meio das nações; eu te louvarei entre os povos.

[[v19-108-4]]

^<<v19-108-4,4>>^ O teu amor está acima dos céus, e a tua fidelidade chega até as nuvens.

[[v19-108-5]]

^<<v19-108-5,5>>^ Ó Deus, mostra a tua grandeza nos céus e que a tua glória  brilhe no mundo inteiro!

[[v19-108-6]]

^<<v19-108-6,6>>^ Salva-nos com o teu poder; responde à nossa oração para que o povo que tu amas seja salvo.

[[v19-108-7]]

^<<v19-108-7,7>>^ No seu Templo, Deus disse: "Quando eu vencer, dividirei a cidade de Siquém e repartirei o vale de Sucote entre o meu povo.

[[v19-108-8]]

^<<v19-108-8,8>>^ Gileade é meu, e Manassés, também; Efraim é o meu capacete, e Judá é o meu cetro  de rei.

[[v19-108-9]]

^<<v19-108-9,9>>^ Porém Moabe será a minha bacia de lavar; e eu jogarei as minhas sandálias sobre Edom, como um sinal de que esse país é meu. Eu cantarei a minha vitória sobre os filisteus."

[[v19-108-10]]

^<<v19-108-10,10>>^ Ó Deus, quem me levará para dentro da cidade protegida por muralhas? Quem me guiará até Edom?

[[v19-108-11]]

^<<v19-108-11,11>>^ Será que, de fato, nos rejeitaste? Será que não vais marchar com os nossos exércitos?

[[v19-108-12]]

^<<v19-108-12,12>>^ Ajuda-nos a combater o inimigo, pois o auxílio de seres humanos não vale nada.

[[v19-108-13]]

^<<v19-108-13,13>>^ Com Deus do nosso lado, venceremos; ele derrotará os nossos inimigos.

'''

xref:019-salmos/019-salmos-107.adoc#v19-107-0[&#60; Capítulo Anterior] | <<v19-108-0,Topo>> | xref:019-salmos/019-salmos-109.adoc#v19-109-0[Próximo Capítulo &#62;]