include::./index.adoc[]

[[v55-3-0]]
=== 2 Timóteo, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v55-3-1]]

^<<v55-3-1,1>>^ Lembre disto: nos últimos dias haverá tempos difíceis.

[[v55-3-2]]

^<<v55-3-2,2>>^ Pois muitos serão egoístas, avarentos, orgulhosos, vaidosos, xingadores, ingratos, desobedientes aos seus pais e não terão respeito pela religião.

[[v55-3-3]]

^<<v55-3-3,3>>^ Não terão amor pelos outros e serão duros, caluniadores, incapazes de se controlarem, violentos e inimigos do bem.

[[v55-3-4]]

^<<v55-3-4,4>>^ Serão traidores, atrevidos e cheios de orgulho. Amarão mais os prazeres do que a Deus;

[[v55-3-5]]

^<<v55-3-5,5>>^ parecerão ser seguidores da nossa religião, mas com as suas ações negarão o verdadeiro poder dela. Fique longe dessa gente!

[[v55-3-6]]

^<<v55-3-6,6>>^ Alguns deles entram nas casas e conseguem dominar mulheres fracas, que estão cheias de pecados e que são levadas por todo tipo de desejos.

[[v55-3-7]]

^<<v55-3-7,7>>^ São mulheres que estão sempre tentando aprender, mas nunca chegam a conhecer a verdade.

[[v55-3-8]]

^<<v55-3-8,8>>^ Assim como Janes e Jambres foram contra Moisés, assim também esses homens são contra a verdade. Eles perderam o juízo e fracassaram na fé.

[[v55-3-9]]

^<<v55-3-9,9>>^ Mas não irão longe, pois todos verão como eles são tolos. Foi isso que aconteceu com Janes e Jambres.

[[v55-3-10]]

^<<v55-3-10,10>>^ Mas você tem seguido os meus ensinamentos, a minha maneira de agir e o propósito que tenho na minha vida. E tem seguido também a minha fé, a minha paciência, o meu amor, a minha perseverança,

[[v55-3-11]]

^<<v55-3-11,11>>^ as minhas perseguições e os meus sofrimentos. Você sabe tudo o que me aconteceu nas cidades de Antioquia, de Icônio e de Listra. Que terríveis perseguições eu sofri! Porém o Senhor me livrou de todas elas.

[[v55-3-12]]

^<<v55-3-12,12>>^ Todos os que querem viver a vida cristã unidos com Cristo Jesus serão perseguidos.

[[v55-3-13]]

^<<v55-3-13,13>>^ Porém as pessoas más e fingidas irão de mal a pior, enganando e sendo enganadas.

[[v55-3-14]]

^<<v55-3-14,14>>^ Quanto a você, continue firme nas verdades que aprendeu e em que creu de todo o coração. Você sabe quem foram os seus mestres na fé cristã.

[[v55-3-15]]

^<<v55-3-15,15>>^ E, desde menino, você conhece as Escrituras Sagradas , as quais lhe podem dar a sabedoria que leva à salvação, por meio da fé em Cristo Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ Pois toda a Escritura Sagrada é inspirada por Deus e é útil para ensinar a verdade, condenar o erro, corrigir as faltas e ensinar a maneira certa de viver.

[[v55-3-17]]

^<<v55-3-17,17>>^ E isso para que o servo  de Deus esteja completamente preparado e pronto para fazer todo tipo de boas ações.

'''

xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[Próximo Capítulo &#62;]