include::./index.adoc[]

[[v55-1-0]]
=== 2 Timóteo, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v55-1-1]]

^<<v55-1-1,1>>^ Eu, Paulo, apóstolo  de Cristo Jesus pela vontade de Deus, que fui mandado para anunciar a promessa da vida que temos por estarmos unidos com Cristo Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ escrevo a você, Timóteo, meu querido filho na fé. Que a graça , a misericórdia e a paz de Deus, o Pai, e de Cristo Jesus, o nosso Senhor, estejam com você!

[[v55-1-3]]

^<<v55-1-3,3>>^ Todas as vezes que lembro de você nas minhas orações, de dia e de noite, eu agradeço a Deus, a quem sirvo com a consciência limpa, como também os meus antepassados serviram.

[[v55-1-4]]

^<<v55-1-4,4>>^ Lembro das suas lágrimas e quero muito ver você outra vez para que eu possa ficar cheio de alegria.

[[v55-1-5]]

^<<v55-1-5,5>>^ Lembro da sua fé sincera, a mesma fé que a sua avó Loide e Eunice, a sua mãe, tinham. E tenho a certeza de que é a mesma fé que você tem.

[[v55-1-6]]

^<<v55-1-6,6>>^ Por isso quero que você lembre de conservar vivo o dom  de Deus que você recebeu quando coloquei as mãos sobre você .

[[v55-1-7]]

^<<v55-1-7,7>>^ Pois o Espírito que Deus nos deu não nos torna medrosos; pelo contrário, o Espírito nos enche de poder e de amor e nos torna prudentes.

[[v55-1-8]]

^<<v55-1-8,8>>^ Portanto, não se envergonhe de dar o seu testemunho a favor do nosso Senhor, nem se envergonhe de mim, que estou na cadeia porque sou servo  dele. Pelo contrário, com a força que vem de Deus, esteja pronto para sofrer comigo por amor ao evangelho .

[[v55-1-9]]

^<<v55-1-9,9>>^ Deus nos salvou e nos chamou  para sermos o seu povo. Não foi por causa do que temos feito, mas porque este era o seu plano e por causa da sua graça . Ele nos deu essa graça por meio de Cristo Jesus, antes da criação do mundo.

[[v55-1-10]]

^<<v55-1-10,10>>^ Mas agora ela foi revelada a nós por meio do glorioso  aparecimento de Cristo Jesus, o nosso Salvador. Ele acabou com o poder da morte e, por meio do evangelho, revelou a vida que dura para sempre.

[[v55-1-11]]

^<<v55-1-11,11>>^ Deus me escolheu como apóstolo  e mestre para anunciar o evangelho.

[[v55-1-12]]

^<<v55-1-12,12>>^ É por isso que sofro essas coisas. Mas eu ainda tenho muita confiança, pois sei em quem tenho crido e estou certo de que ele é poderoso para guardar, até aquele dia , aquilo que ele me confiou.

[[v55-1-13]]

^<<v55-1-13,13>>^ Tome como modelo os ensinamentos verdadeiros que eu lhe dei e fique firme na fé e no amor que temos por estarmos unidos com Cristo Jesus.

[[v55-1-14]]

^<<v55-1-14,14>>^ Por meio do poder do Espírito Santo, que vive em nós, guarde esse precioso tesouro que foi entregue a você.

[[v55-1-15]]

^<<v55-1-15,15>>^ Você já sabe que todos os irmãos da província  da Ásia, inclusive Fígelo e Hermógenes, me abandonaram.

[[v55-1-16]]

^<<v55-1-16,16>>^ Que o Senhor seja bondoso com a família de Onesíforo, pois muitas vezes ele me animou e não teve vergonha de mim por eu estar na cadeia!

[[v55-1-17]]

^<<v55-1-17,17>>^ Pelo contrário, logo que chegou a Roma, ele me procurou até me encontrar.

[[v55-1-18]]

^<<v55-1-18,18>>^ Que o Senhor dê a ele a certeza de que naquele dia ele receberá a sua misericórdia! E você sabe melhor do que eu o quanto ele me ajudou em Éfeso.

'''

xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[Próximo Capítulo &#62;]