include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v55-4-1]]

^<<v55-4-1,1>>^ Na presença de Deus e de Cristo Jesus, que julgará todos os seres humanos, tanto os que estiverem vivos como os que estiverem mortos, eu ordeno a você, com toda a firmeza, o seguinte: por causa da vinda de Cristo e do seu Reino ,

[[v55-4-2]]

^<<v55-4-2,2>>^ pregue a mensagem e insista em anunciá-la, seja no tempo certo ou não. Procure convencer, repreenda, anime e ensine com toda a paciência.

[[v55-4-3]]

^<<v55-4-3,3>>^ Pois vai chegar o tempo em que as pessoas não vão dar atenção ao verdadeiro ensinamento, mas seguirão os seus próprios desejos. E arranjarão para si mesmas uma porção de mestres, que vão dizer a elas o que elas querem ouvir.

[[v55-4-4]]

^<<v55-4-4,4>>^ Essas pessoas deixarão de ouvir a verdade para dar atenção às lendas.

[[v55-4-5]]

^<<v55-4-5,5>>^ Mas você, seja moderado em todas as situações. Suporte o sofrimento, faça o trabalho de um pregador do evangelho  e cumpra bem o seu dever de servo  de Deus.

[[v55-4-6]]

^<<v55-4-6,6>>^ Quanto a mim, a hora já chegou de eu ser sacrificado , e já é tempo de deixar esta vida.

[[v55-4-7]]

^<<v55-4-7,7>>^ Fiz o melhor que pude na corrida, cheguei até o fim, conservei a fé.

[[v55-4-8]]

^<<v55-4-8,8>>^ E agora está me esperando o prêmio da vitória, que é dado para quem vive uma vida correta, o prêmio que o Senhor, o justo Juiz, me dará naquele dia , e não somente a mim, mas a todos os que esperam, com amor, a sua vinda.

[[v55-4-9]]

^<<v55-4-9,9>>^ Venha me ver logo que puder.

[[v55-4-10]]

^<<v55-4-10,10>>^ Pois Demas se apaixonou por este mundo, me abandonou e foi para a cidade de Tessalônica. Crescente foi para a província  da Galácia, e Tito, para a região da Dalmácia.

[[v55-4-11]]

^<<v55-4-11,11>>^ Somente Lucas está aqui comigo. Procure Marcos e traga-o com você porque ele pode me ajudar no trabalho.

[[v55-4-12]]

^<<v55-4-12,12>>^ Eu mandei Tíquico para a cidade de Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando você vier, traga a minha capa  que deixei na cidade de Trôade, na casa de Carpo. Traga os livros também, principalmente os de couro.

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o ferreiro, me prejudicou muito; o Senhor lhe dará a sua recompensa de acordo com o que ele fez.

[[v55-4-15]]

^<<v55-4-15,15>>^ Tome cuidado com ele, pois combateu com muita violência a nossa mensagem.

[[v55-4-16]]

^<<v55-4-16,16>>^ Na primeira vez em que fiz a minha defesa diante das autoridades, ninguém ficou comigo; todos me abandonaram. Espero que Deus não ponha isso na conta deles!

[[v55-4-17]]

^<<v55-4-17,17>>^ Mas o Senhor ficou comigo, me deu força para que eu pudesse anunciar a mensagem completa a todos os não judeus e me livrou de ser condenado à morte.

[[v55-4-18]]

^<<v55-4-18,18>>^ O Senhor me livrará de todo mal e me levará em segurança para o seu Reino celestial . A ele seja dada a glória  para todo o sempre! Amém !

[[v55-4-19]]

^<<v55-4-19,19>>^ Saudações a Priscila e ao seu marido Áquila e também à família de Onesíforo.

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto ficou na cidade de Corinto, e eu deixei Trófimo na cidade de Mileto porque ele estava doente.

[[v55-4-21]]

^<<v55-4-21,21>>^ Faça o possível para vir antes do inverno . Os irmãos Êubulo, Pudente, Lino, e a irmã Cláudia e todos os outros irmãos mandam saudações.

[[v55-4-22]]

^<<v55-4-22,22>>^ Timóteo, que o Senhor esteja com o seu espírito! Que a graça  de Deus esteja com vocês!

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]