include::./index.adoc[]

[[v15-3-0]]
=== Esdras, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v15-3-1]]

^<<v15-3-1,1>>^ Quando chegou o sétimo mês e os israelitas já estavam morando nas suas cidades, todo o povo se reuniu em Jerusalém.

[[v15-3-2]]

^<<v15-3-2,2>>^ Então o sacerdote Josué, filho de Jozadaque, e os seus companheiros, os outros sacerdotes, e também Zorobabel, filho de Salatiel, e os seus parentes construíram o altar do Deus de Israel, para oferecer sobre ele os sacrifícios  que manda a Lei  de Moisés, homem de Deus.

[[v15-3-3]]

^<<v15-3-3,3>>^ Mesmo tendo medo da gente daquela região, eles construíram de novo o altar no lugar em que ele estava antes. Então começaram a oferecer sacrifícios sobre ele todas as manhãs e todas as tardes.

[[v15-3-4]]

^<<v15-3-4,4>>^ Além disso, comemoraram a Festa das Barracas  de acordo com a Lei de Moisés, oferecendo cada dia os sacrifícios ordenados para aquele dia.

[[v15-3-5]]

^<<v15-3-5,5>>^ Trouxeram também os sacrifícios que deviam ser completamente queimados diariamente e os que deviam ser apresentados na Festa da Lua Nova  e nas outras festas sagradas. E ofereceram também aquilo que traziam por vontade própria.

[[v15-3-6]]

^<<v15-3-6,6>>^ O povo começou a oferecer sacrifícios ao Senhor  desde o dia primeiro do sétimo mês, antes mesmo que o Templo do Senhor  começasse a ser construído de novo.

[[v15-3-7]]

^<<v15-3-7,7>>^ O povo deu dinheiro para pagar os pedreiros e carpinteiros; e deu comida, bebida e azeite para serem mandados às cidades de Tiro e Sidom. Essas coisas foram trocadas por madeira de cedro, que foi trazida por mar do Líbano até o porto de Jope. Tudo isso foi feito com a permissão de Ciro, rei da Pérsia.

[[v15-3-8]]

^<<v15-3-8,8>>^ E assim, no ano seguinte ao da sua volta, no segundo mês, os israelitas começaram a construir de novo o Templo de Deus, que fica em Jerusalém. Zorobabel, filho de Salatiel, e Josué, filho de Jozadaque, junto com os seus parentes, os sacerdotes e os levitas  e todos os israelitas que haviam voltado para Jerusalém, pegaram firme no trabalho. Todos os levitas maiores de vinte anos foram encarregados de dirigir as obras.

[[v15-3-9]]

^<<v15-3-9,9>>^ Josué e os seus filhos e irmãos formaram um grupo junto com Cadmiel e os seus filhos, que eram descendentes de Hodavias. Esse grupo dirigia os que trabalhavam na construção e era ajudado pelos levitas do grupo de famílias de Henadade.

[[v15-3-10]]

^<<v15-3-10,10>>^ Quando os construtores colocaram os alicerces do Templo, os sacerdotes ficaram de pé, vestidos com roupas especiais para aquela ocasião e com trombetas nas mãos. Os levitas descendentes de Asafe carregavam pratos musicais para louvar a Deus, o Senhor , de acordo com o que Davi, rei de Israel, havia mandado.

[[v15-3-11]]

^<<v15-3-11,11>>^ Uns cantavam louvores e agradeciam ao Senhor , e os outros respondiam. Eles diziam: "O Senhor  é bom, e o seu amor pelo povo de Israel dura para sempre!" E todo o povo gritava bem alto e louvava o Senhor  porque a construção do seu novo Templo já havia começado.

[[v15-3-12]]

^<<v15-3-12,12>>^ Muitos sacerdotes, levitas e chefes de famílias eram velhos e tinham visto o primeiro Templo. Eles choravam alto ao verem que os alicerces do novo Templo haviam sido colocados. Mas os outros que estavam ali gritavam de alegria.

[[v15-3-13]]

^<<v15-3-13,13>>^ E assim ninguém podia saber se o povo gritava de alegria ou se chorava, pois gritavam tão alto, que de longe se ouvia o barulho.

'''

xref:015-esdras/015-esdras-002.adoc#v15-2-0[&#60; Capítulo Anterior] | <<v15-3-0,Topo>> | xref:015-esdras/015-esdras-004.adoc#v15-4-0[Próximo Capítulo &#62;]