include::./index.adoc[]

[[v15-4-0]]
=== Esdras, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v15-4-1]]

^<<v15-4-1,1>>^ Os inimigos das tribos  de Judá e Benjamim souberam que os que haviam voltado da Babilônia estavam construindo de novo o Templo do Senhor , o Deus de Israel.

[[v15-4-2]]

^<<v15-4-2,2>>^ Então foram falar com Zorobabel e com os chefes das famílias. Disseram o seguinte: — Queremos construir o Templo junto com vocês. Nós adoramos o mesmo Deus que vocês e temos oferecido sacrifícios  a ele desde o tempo de Esar-Hadom, rei da Assíria, que nos mandou morar aqui .

[[v15-4-3]]

^<<v15-4-3,3>>^ Porém Zorobabel, Josué e os outros chefes das famílias israelitas responderam: — Não precisamos que vocês nos ajudem a construir um templo para o Senhor , nosso Deus. Nós vamos fazer isso sozinhos, como Ciro, rei da Pérsia, mandou.

[[v15-4-4]]

^<<v15-4-4,4>>^ Então a gente daquela região fez tudo para desanimar os israelitas e para pôr medo neles a fim de parar a construção.

[[v15-4-5]]

^<<v15-4-5,5>>^ Além disso, deram dinheiro a certos funcionários do governo para que estes atrapalhassem os planos dos israelitas. E os inimigos fizeram isso durante todo o tempo em que Ciro foi rei da Pérsia, até o reinado de Dario, rei da Pérsia .

[[v15-4-6]]

^<<v15-4-6,6>>^ No começo do reinado de Xerxes , os inimigos escreveram uma acusação contra os moradores de Judá e de Jerusalém.

[[v15-4-7]]

^<<v15-4-7,7>>^ Bislã, Mitredate, Tabeel e os seus companheiros escreveram uma carta a Artaxerxes , rei da Pérsia. A carta foi escrita em aramaico  e traduzida para a língua persa.

[[v15-4-8]]

^<<v15-4-8,8>>^ Reum, que era o governador, e Sinsai, o escrivão, também escreveram uma carta ao rei Artaxerxes contra os moradores de Jerusalém. A carta dizia:

[[v15-4-9]]

^<<v15-4-9,9>>^ "Esta carta é enviada por Reum, o governador, e Sinsai, o escrivão, junto com os seus companheiros, os juízes e todos os outros funcionários, que são naturais de Ereque, da Babilônia e de Susã, na terra de Elão,

[[v15-4-10]]

^<<v15-4-10,10>>^ e junto com os outros povos que o grande e poderoso Assurbanipal tirou dos seus países e levou para morar na cidade de Samaria e no resto da província  do Eufrates-Oeste ."

[[v15-4-11]]

^<<v15-4-11,11>>^ A carta continuava assim: "Ao rei Artaxerxes, os seus servidores da província do Eufrates-Oeste escrevem o que segue:

[[v15-4-12]]

^<<v15-4-12,12>>^ "Ó rei, levamos ao seu conhecimento que os judeus que o senhor mandou para cá chegaram a Jerusalém e estão construindo de novo essa cidade rebelde e má. Já começaram a levantar as muralhas e logo vão acabar esse trabalho.

[[v15-4-13]]

^<<v15-4-13,13>>^ É bom que o rei também saiba que, se essa cidade for reconstruída, e se as suas muralhas forem levantadas de novo, essa gente não vai querer pagar nenhum imposto nem taxas, e por causa disso o rei terá muito prejuízo.

[[v15-4-14]]

^<<v15-4-14,14>>^ Como nós somos seus servidores, não queremos que o senhor fique prejudicado. Por isso, sugerimos

[[v15-4-15]]

^<<v15-4-15,15>>^ que o senhor mande fazer uma investigação nos arquivos dos seus antepassados. Se fizer isso, descobrirá que Jerusalém é uma cidade rebelde e que, desde os tempos antigos, ela tem dado trabalho aos reis e aos governadores das províncias. Em outros tempos, tem havido revoltas nela, e por isso ela foi destruída.

[[v15-4-16]]

^<<v15-4-16,16>>^ Portanto, ó rei, nós estamos certos de que, se essa cidade for construída de novo, e se as suas muralhas forem consertadas, o senhor não poderá mais controlar a província do Eufrates-Oeste."

[[v15-4-17]]

^<<v15-4-17,17>>^ Então o rei Artaxerxes mandou a seguinte resposta: "A Reum, o governador, a Sinsai, o escrivão, e aos seus companheiros que vivem em Samaria e no resto da província  do Eufrates-Oeste: Saudações.

[[v15-4-18]]

^<<v15-4-18,18>>^ "A carta que vocês mandaram foi traduzida para a língua persa e lida para mim.

[[v15-4-19]]

^<<v15-4-19,19>>^ Então mandei que fizessem uma investigação, e descobriu-se que, desde os tempos antigos, Jerusalém tem se revoltado contra a autoridade do rei e que ela sempre esteve cheia de rebeldes e de criadores de casos.

[[v15-4-20]]

^<<v15-4-20,20>>^ Reis poderosos reinaram ali e governaram toda a província do Eufrates-Oeste, e o povo lhes pagava impostos e taxas.

[[v15-4-21]]

^<<v15-4-21,21>>^ Portanto, deem ordens para que parem as obras. Essa cidade não será construída de novo enquanto eu não mandar.

[[v15-4-22]]

^<<v15-4-22,22>>^ Cumpram essa ordem com todo o cuidado para evitar que eu tenha mais prejuízos."

[[v15-4-23]]

^<<v15-4-23,23>>^ A carta do rei Artaxerxes foi lida para Reum, para Sinsai e para os seus companheiros. Então todos eles foram imediatamente a Jerusalém e, ameaçando os israelitas com armas, os obrigaram a parar as obras.

[[v15-4-24]]

^<<v15-4-24,24>>^ O trabalho da construção do Templo havia sido interrompido e tinha continuado parado até o segundo ano do reinado de Dario, rei da Pérsia .

'''

xref:015-esdras/015-esdras-003.adoc#v15-3-0[&#60; Capítulo Anterior] | <<v15-4-0,Topo>> | xref:015-esdras/015-esdras-005.adoc#v15-5-0[Próximo Capítulo &#62;]