include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v15-8-1]]

^<<v15-8-1,1>>^ Esta é a lista dos chefes de grupos de famílias que estavam na Babilônia e que voltaram com Esdras para Jerusalém quando Artaxerxes era rei:

[[v15-8-2]]

^<<v15-8-2,2>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi; Zacarias, da família de Parós, com cento e cinquenta homens do seu grupo de famílias (havia registro das suas famílias); Elioenai, filho de Zeraías, da família de Paate-Moabe, com duzentos homens; Secanias, filho de Jaziel, da família de Zatu, com trezentos homens; Ebede, filho de Jônatas, da família de Adim, com cinquenta homens; Jesaías, filho de Atalias, da família de Elão, com setenta homens; Zebadias, filho de Micael, da família de Sefatias, com oitenta homens; Obadias, filho de Jeiel, da família de Joabe, com duzentos e dezoito homens; Selomite, filho de Josifias, da família de Bani, com cento e sessenta homens; Zacarias, filho de Bebai, da família de Bebai, com vinte e oito homens; Joanã, filho de Hacatã, da família de Azgade, com cento e dez homens; Elifelete, Jeiel e Semaías, da família de Adonicã, com sessenta homens. Eles foram os últimos a chegar; Utai e Zabude, da família de Bigvai, com setenta homens.

[[v15-8-3]]

^<<v15-8-3,3>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-4]]

^<<v15-8-4,4>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-5]]

^<<v15-8-5,5>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-6]]

^<<v15-8-6,6>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-7]]

^<<v15-8-7,7>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-8]]

^<<v15-8-8,8>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-9]]

^<<v15-8-9,9>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-10]]

^<<v15-8-10,10>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-11]]

^<<v15-8-11,11>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-12]]

^<<v15-8-12,12>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-13]]

^<<v15-8-13,13>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-14]]

^<<v15-8-14,14>>^ Gérson, da família de Fineias; Daniel, da família de Itamar; Hatus, filho de Secanias, da família de Davi;

[[v15-8-15]]

^<<v15-8-15,15>>^ Eu, Esdras, reuni toda essa gente perto do rio que corre para a cidade de Aava, e ficamos acampados ali três dias. Quando examinei o povo com mais cuidado, vi que no meio deles havia sacerdotes, porém não havia nenhum levita .

[[v15-8-16]]

^<<v15-8-16,16>>^ Aí mandei chamar nove líderes: Eliézer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulã. E chamei também dois professores: Joiaribe e Elnatã.

[[v15-8-17]]

^<<v15-8-17,17>>^ Eu mandei que eles fossem procurar Ido, o chefe do lugar chamado Casifia, e dissessem a ele e aos seus colegas servidores do Templo que nos mandassem gente para servir a Deus no Templo.

[[v15-8-18]]

^<<v15-8-18,18>>^ E, porque Deus estava nos abençoando, eles nos mandaram um homem muito capaz, chamado Serebias, levita da família de Mali. Dezoito dos seus filhos e irmãos vieram com ele.

[[v15-8-19]]

^<<v15-8-19,19>>^ Eles também mandaram Hasabias e Jesaías, da família de Merari, com vinte dos seus filhos e irmãos.

[[v15-8-20]]

^<<v15-8-20,20>>^ Vieram também duzentos e vinte servidores do Templo, os quais eram descendentes daqueles que o rei Davi e os seus oficiais haviam escolhido para ajudar os levitas. E fizeram uma lista com os nomes de todos eles.

[[v15-8-21]]

^<<v15-8-21,21>>^ Então, ali perto do rio Aava, dei ordem para que houvesse um dia de jejum. Todos nós deveríamos nos ajoelhar diante do nosso Deus e lhe pedir que nos dirigisse na nossa viagem e nos protegesse, os nossos filhos e tudo o que era nosso.

[[v15-8-22]]

^<<v15-8-22,22>>^ Eu tinha dito ao rei que o nosso Deus protege todos os que confiam nele, porém que a sua força e a sua ira  vão contra aqueles que o abandonam. Por isso, fiquei com vergonha de pedir ao rei uma tropa de soldados da cavalaria para nos defender dos nossos inimigos durante a viagem.

[[v15-8-23]]

^<<v15-8-23,23>>^ Assim nós jejuamos e oramos, pedindo a Deus que nos protegesse, e ele atendeu as nossas orações.

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]