include::./index.adoc[]

[[v15-6-0]]
=== Esdras, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v15-6-1]]

^<<v15-6-1,1>>^ Então o rei Dario mandou que dessem uma busca nos arquivos reais da Babilônia, onde eram guardados os documentos.

[[v15-6-2]]

^<<v15-6-2,2>>^ E na cidade de Ecbatana, na província  da Média, foi encontrado o documento. Nele estava escrito o seguinte:

[[v15-6-3]]

^<<v15-6-3,3>>^ "No primeiro ano do seu reinado, o rei Ciro deu ordem para que o Templo de Jerusalém fosse reconstruído, a fim de ser o lugar onde o povo apresentasse sacrifícios  e ofertas a serem completamente queimadas. O Templo deverá medir vinte e sete metros de altura, por vinte e sete metros de largura.

[[v15-6-4]]

^<<v15-6-4,4>>^ As paredes deverão ser feitas com uma carreira de madeira em cima de cada três carreiras de pedra. Todas as despesas serão pagas pelo governo.

[[v15-6-5]]

^<<v15-6-5,5>>^ "Além disso, todos os objetos de prata e de ouro que o rei Nabucodonosor tirou do Templo de Jerusalém e trouxe para a Babilônia serão devolvidos, cada um para o seu próprio lugar no Templo de Jerusalém."

[[v15-6-6]]

^<<v15-6-6,6>>^ Então o rei Dario mandou a seguinte resposta: "São estas as ordens do rei Dario para Tatenai, governador da província  do Eufrates-Oeste , para Setar-Bozenai e para os seus companheiros oficiais da província do Eufrates-Oeste: "Afastem-se do Templo

[[v15-6-7]]

^<<v15-6-7,7>>^ e não proíbam a sua construção. Deixem que o governador de Judá e os líderes israelitas reconstruam o Templo de Deus no lugar onde ficava o que foi destruído.

[[v15-6-8]]

^<<v15-6-8,8>>^ Por meio desta carta, ordeno que vocês os ajudem na construção. As despesas serão pagas imediatamente para que a obra não pare. O dinheiro para isso será tirado do tesouro real, isto é, dos impostos recebidos na província do Eufrates-Oeste.

[[v15-6-9]]

^<<v15-6-9,9>>^ Deem aos sacerdotes de Jerusalém todos os dias, sem falta, tudo o que eles disserem que precisam: bois novos, carneiros e carneirinhos para serem completamente queimados como ofertas ao Deus do céu; e deem também trigo, sal, vinho e azeite.

[[v15-6-10]]

^<<v15-6-10,10>>^ Isso será feito para que assim eles ofereçam sacrifícios  que agradem ao Deus do céu e orem pedindo as suas bênçãos para mim e para os meus filhos.

[[v15-6-11]]

^<<v15-6-11,11>>^ Se alguma pessoa desobedecer a esta ordem, ordeno também que vocês atravessem o seu corpo com uma viga pontuda, tirada da sua casa. Depois finquem a viga no chão. Além disso, derrubem a sua casa e a façam virar um montão de entulho.

[[v15-6-12]]

^<<v15-6-12,12>>^ Que Deus, que escolheu Jerusalém como o lugar onde deve ser adorado, acabe com qualquer rei ou nação que desobedecer a esta ordem e tentar destruir o Templo de Jerusalém! Eu, Dario, dei esta ordem. Que ela seja obedecida em tudo."

[[v15-6-13]]

^<<v15-6-13,13>>^ Então o governador Tatenai, Setar-Bozenai e os seus companheiros fizeram exatamente o que o rei tinha ordenado.

[[v15-6-14]]

^<<v15-6-14,14>>^ Os líderes israelitas progrediram na construção do Templo, animados pelas mensagens do profeta  Ageu e do profeta Zacarias, filho de Ido. Eles terminaram o Templo, conforme as ordens do Deus de Israel e de Ciro, Dario e Artaxerxes , reis da Pérsia.

[[v15-6-15]]

^<<v15-6-15,15>>^ Acabaram a construção do Templo no dia três do mês de adar , no sexto ano do reinado de Dario .

[[v15-6-16]]

^<<v15-6-16,16>>^ Então o povo de Israel, isto é, os sacerdotes, os levitas  e todos os outros que haviam voltado da Babilônia, fizeram a inauguração do Templo, dedicando-o com alegria à adoração a Deus.

[[v15-6-17]]

^<<v15-6-17,17>>^ Para essa dedicação, eles ofereceram cem touros, duzentos carneiros e quatrocentos carneirinhos como sacrifício  e doze bodes como oferta para tirar pecados, um bode para cada uma das tribos  de Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ Também fizeram a escala dos sacerdotes e dos levitas para os serviços do Templo de Jerusalém, de acordo com as instruções escritas no Livro de Moisés .

[[v15-6-19]]

^<<v15-6-19,19>>^ O povo que havia voltado do cativeiro  na Babilônia comemorou a Festa da Páscoa  no dia catorze do primeiro mês.

[[v15-6-20]]

^<<v15-6-20,20>>^ Todos os sacerdotes e levitas  tinham se purificado  e estavam puros . Eles mataram os animais para os sacrifícios  da Páscoa, em favor de todas as pessoas que haviam voltado, em favor dos seus colegas sacerdotes e também em favor de si mesmos.

[[v15-6-21]]

^<<v15-6-21,21>>^ Todos os israelitas que haviam voltado da Babilônia comeram da carne dos sacrifícios. E todos aqueles que haviam abandonado os costumes pagãos dos povos da terra de Canaã e tinham passado a adorar o Senhor , o Deus de Israel, também comeram.

[[v15-6-22]]

^<<v15-6-22,22>>^ Durante sete dias, eles comemoraram alegremente a Festa dos Pães sem Fermento . Estavam muito contentes porque o Senhor  havia feito o rei da Assíria ficar a favor deles, ajudando-os no trabalho da reconstrução do Templo.

'''

xref:015-esdras/015-esdras-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-esdras/015-esdras-007.adoc#v15-7-0[Próximo Capítulo &#62;]