include::./index.adoc[]

[[v15-7-0]]
=== Esdras, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v15-7-1]]

^<<v15-7-1,1>>^ Alguns anos depois, quando Artaxerxes era rei da Pérsia, um homem chamado Esdras foi da Babilônia para Jerusalém. Ele era descendente de Arão, o Grande Sacerdote . Esdras era filho de Seraías, neto de Azarias, e bisneto de Hilquias;

[[v15-7-2]]

^<<v15-7-2,2>>^ e os seus outros antepassados eram Salum, Zadoque, Aitube,

[[v15-7-3]]

^<<v15-7-3,3>>^ Amariá, Azarias, Meraiote,

[[v15-7-4]]

^<<v15-7-4,4>>^ Zeraías, Uzi, Buqui,

[[v15-7-5]]

^<<v15-7-5,5>>^ Abisua, Fineias e Eleazar, que era filho de Arão, o Grande Sacerdote.

[[v15-7-6]]

^<<v15-7-6,6>>^ Esdras era mestre da Lei  e conhecia muito bem a Lei  de Moisés, dada pelo Senhor , o Deus de Israel. Ele foi falar com o rei Artaxerxes, e este lhe deu tudo o que pediu porque o Senhor  abençoava Esdras. Assim Esdras foi da Babilônia para Jerusalém

[[v15-7-7]]

^<<v15-7-7,7>>^ com um grupo de israelitas, entre os quais havia sacerdotes, levitas  e músicos, guardas e servidores do Templo. Isso foi no sétimo ano do reinado de Artaxerxes.

[[v15-7-8]]

^<<v15-7-8,8>>^ Eles saíram da Babilônia no dia primeiro do primeiro mês e, com a ajuda de Deus, chegaram a Jerusalém no dia primeiro do quinto mês.

[[v15-7-9]]

^<<v15-7-9,9>>^ Eles saíram da Babilônia no dia primeiro do primeiro mês e, com a ajuda de Deus, chegaram a Jerusalém no dia primeiro do quinto mês.

[[v15-7-10]]

^<<v15-7-10,10>>^ Esdras havia dedicado a sua vida a estudar, e a praticar a Lei do Senhor , e a ensinar todos os seus mandamentos ao povo de Israel.

[[v15-7-11]]

^<<v15-7-11,11>>^ Esta é a cópia da carta que o rei Artaxerxes entregou ao sacerdote Esdras, o mestre da Lei , que conhecia bem todas as leis e mandamentos que o Senhor  tinha dado a Israel:

[[v15-7-12]]

^<<v15-7-12,12>>^ "Esta carta de Artaxerxes, o rei dos reis, é para o sacerdote Esdras, o mestre da Lei do Deus do céu : Saudações.

[[v15-7-13]]

^<<v15-7-13,13>>^ Ordeno que, de todo o meu reino, podem ir com você para Jerusalém todos os israelitas que quiserem, isto é, gente do povo, sacerdotes e levitas .

[[v15-7-14]]

^<<v15-7-14,14>>^ Eu, o rei, junto com os meus sete conselheiros, mando que você vá a Jerusalém e a Judá para ver se a Lei do seu Deus, que lhe foi entregue, está sendo bem-obedecida.

[[v15-7-15]]

^<<v15-7-15,15>>^ Leve as ofertas de ouro e de prata que eu e os meus conselheiros queremos dar ao Deus de Israel, que tem o seu Templo em Jerusalém.

[[v15-7-16]]

^<<v15-7-16,16>>^ Leve também toda a prata e ouro que recolheu na província  da Babilônia e as ofertas que o povo israelita e os seus sacerdotes deram para o Templo do seu Deus em Jerusalém.

[[v15-7-17]]

^<<v15-7-17,17>>^ "Use esse dinheiro com cuidado, comprando com ele touros, carneiros, ovelhas, cereais e vinho, para oferecer no altar do Templo de Jerusalém.

[[v15-7-18]]

^<<v15-7-18,18>>^ Com o ouro e a prata que sobrarem, compre qualquer coisa que você e os seus companheiros quiserem, de acordo com a vontade do seu Deus.

[[v15-7-19]]

^<<v15-7-19,19>>^ Os objetos que lhe foram dados para serem usados nos serviços do Templo, você os entregará a Deus em Jerusalém.

[[v15-7-20]]

^<<v15-7-20,20>>^ E qualquer outra coisa que precisar para o Templo será paga pela tesouraria do rei.

[[v15-7-21]]

^<<v15-7-21,21>>^ "Eu, o rei Artaxerxes, ordeno a todos os tesoureiros da província do Eufrates-Oeste que entreguem imediatamente ao sacerdote Esdras, o mestre da Lei do Deus do céu, tudo o que ele pedir,

[[v15-7-22]]

^<<v15-7-22,22>>^ até no máximo três mil e quatrocentos quilos de prata, doze mil e quinhentos quilos de trigo, dois mil litros de vinho, dois mil litros de azeite e sal à vontade.

[[v15-7-23]]

^<<v15-7-23,23>>^ Deverão ser cumpridas com todo o cuidado as ordens que o Deus do céu der a respeito do seu Templo, para que assim eu tenha a certeza de que ele nunca ficará irado  comigo nem com os meus descendentes que forem reis depois de mim.

[[v15-7-24]]

^<<v15-7-24,24>>^ Vocês estão proibidos de cobrar qualquer imposto dos sacerdotes, dos levitas, dos músicos, dos guardas e servidores do Templo ou de qualquer outra pessoa ligada a esse Templo.

[[v15-7-25]]

^<<v15-7-25,25>>^ "E você, Esdras, usando a sabedoria que o seu Deus lhe deu, nomeie administradores e juízes para governarem todo o povo da província do Eufrates-Oeste, isto é, todos os que conhecem as leis do seu Deus; e ensine essas leis aos que não as conhecem.

[[v15-7-26]]

^<<v15-7-26,26>>^ Quem desobedecer às leis do seu Deus ou às leis do reino será castigado imediatamente: será morto, ou expulso do país, ou preso, ou as suas propriedades serão tomadas."

[[v15-7-27]]

^<<v15-7-27,27>>^ Esdras disse: — Louvado seja o Senhor , o Deus dos nossos antepassados, que pôs no coração do rei o desejo de honrar dessa maneira o Templo do Senhor , em Jerusalém!

'''

xref:015-esdras/015-esdras-006.adoc#v15-6-0[&#60; Capítulo Anterior] | <<v15-7-0,Topo>> | xref:015-esdras/015-esdras-008.adoc#v15-8-0[Próximo Capítulo &#62;]