include::./index.adoc[]

[[v15-5-0]]
=== Esdras, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v15-5-1]]

^<<v15-5-1,1>>^ O profeta  Ageu e o profeta Zacarias, filho de Ido, começaram a dar aos israelitas que estavam em Judá e em Jerusalém mensagens que haviam recebido do Deus de Israel.

[[v15-5-2]]

^<<v15-5-2,2>>^ Zorobabel, filho de Salatiel, e Josué, filho de Jozadaque, ouviram as mensagens. Então começaram a reconstruir o Templo de Jerusalém, e os dois profetas os ajudavam.

[[v15-5-3]]

^<<v15-5-3,3>>^ Quase ao mesmo tempo, Tatenai, o governador da província  do Eufrates-Oeste, e Setar-Bozenai e os seus companheiros foram a Jerusalém e perguntaram: — Quem deu ordem para vocês reconstruírem este Templo e consertarem estas muralhas?

[[v15-5-4]]

^<<v15-5-4,4>>^ Eles também perguntaram os nomes dos homens que estavam ajudando a reconstruir o Templo.

[[v15-5-5]]

^<<v15-5-5,5>>^ Mas Deus estava protegendo os líderes israelitas, e por isso os oficiais persas resolveram não fazer nada enquanto não escrevessem sobre aquele assunto ao rei Dario e recebessem uma resposta.

[[v15-5-6]]

^<<v15-5-6,6>>^ O relatório que Tatenai e Setar-Bozenai e os seus companheiros mandaram ao rei foi este:

[[v15-5-7]]

^<<v15-5-7,7>>^ "Ao rei Dario: Que o senhor governe em paz!

[[v15-5-8]]

^<<v15-5-8,8>>^ Levamos ao seu conhecimento que fomos à região de Judá e vimos que o Templo do Grande Deus está sendo construído com enormes blocos de pedra e que as vigas de madeira estão sendo colocadas nas paredes. O trabalho está sendo feito com muito cuidado, e a obra está indo depressa.

[[v15-5-9]]

^<<v15-5-9,9>>^ "Então nós perguntamos aos líderes do povo quem lhes tinha dado ordem para reconstruir o Templo e as muralhas.

[[v15-5-10]]

^<<v15-5-10,10>>^ Também perguntamos os seus nomes, para que pudéssemos informar ao senhor sobre quem são os chefes do trabalho.

[[v15-5-11]]

^<<v15-5-11,11>>^ Eles responderam: ‘Nós somos servos  do Deus do céu e da terra e estamos reconstruindo o Templo que um grande rei de Israel construiu e terminou há muito tempo.

[[v15-5-12]]

^<<v15-5-12,12>>^ Porém os nossos antepassados fizeram o Deus do céu ficar irado , e por isso ele deixou que fôssemos conquistados por Nabucodonosor, rei da Babilônia, que era natural da Caldeia. O Templo foi destruído, e o povo foi levado para a Babilônia.

[[v15-5-13]]

^<<v15-5-13,13>>^ Mas, no primeiro ano do reinado de Ciro como rei da Babilônia, ele mandou que o Templo fosse reconstruído.

[[v15-5-14]]

^<<v15-5-14,14>>^ Também devolveu as vasilhas de ouro e de prata que o rei Nabucodonosor havia tirado do Templo de Jerusalém e colocado no templo de Babilônia. O rei Ciro devolveu essas vasilhas a um homem chamado Sesbazar, que ele havia nomeado governador de Judá.

[[v15-5-15]]

^<<v15-5-15,15>>^ O rei mandou que Sesbazar as levasse de volta para o Templo de Jerusalém. Mandou também que reconstruísse o Templo no mesmo lugar do primeiro.

[[v15-5-16]]

^<<v15-5-16,16>>^ Então Sesbazar veio e colocou os alicerces do Templo. A construção continuou desde aquela época até agora, mas ainda não terminou.’

[[v15-5-17]]

^<<v15-5-17,17>>^ "Portanto, se isso lhe agradar, ó rei, mande agora dar uma busca nos arquivos reais da Babilônia, para saber se o rei Ciro deu ou não ordem para que este Templo fosse reconstruído em Jerusalém. Depois nos informe o que o senhor quer que se faça a respeito desse assunto."

'''

xref:015-esdras/015-esdras-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-esdras/015-esdras-006.adoc#v15-6-0[Próximo Capítulo &#62;]