include::./index.adoc[]

[[v57-1-0]]
=== Filemom, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v57-1-1]]

^<<v57-1-1,1>>^ Eu, Paulo, prisioneiro por causa de Cristo Jesus, junto com o irmão Timóteo, escrevo a você, Filemom, nosso amigo e companheiro de trabalho,

[[v57-1-2]]

^<<v57-1-2,2>>^ e à igreja que se reúne na sua casa. Esta carta vai também para a nossa irmã Áfia e para Arquipo, nosso companheiro de lutas.

[[v57-1-3]]

^<<v57-1-3,3>>^ Que a graça  e a paz de Deus, o nosso Pai, e do Senhor Jesus Cristo estejam com vocês!

[[v57-1-4]]

^<<v57-1-4,4>>^ Meu caro Filemom, sempre que eu oro, lembro de você e agradeço ao meu Deus

[[v57-1-5]]

^<<v57-1-5,5>>^ porque tenho ouvido falar do seu amor por todo o povo de Deus e da fé que você tem no Senhor Jesus.

[[v57-1-6]]

^<<v57-1-6,6>>^ Peço a Deus que a fé que une você a nós faça com que compreendamos mais profundamente todas as bênçãos que temos recebido na nossa vida, por estarmos unidos com Cristo.

[[v57-1-7]]

^<<v57-1-7,7>>^ Meu caro irmão, o seu amor tem me dado grande alegria e muita coragem, pois você tem animado o coração de todo o povo de Deus.

[[v57-1-8]]

^<<v57-1-8,8>>^ Por isso, como seu irmão em Cristo, eu sei que tenho o direito de exigir o que você deve fazer.

[[v57-1-9]]

^<<v57-1-9,9>>^ Mas o amor que tenho por você me obriga a lhe fazer apenas um pedido. E faço isso, embora eu seja Paulo, o representante de Cristo Jesus e agora também prisioneiro por causa dele.

[[v57-1-10]]

^<<v57-1-10,10>>^ Portanto, eu lhe faço um pedido em favor de Onésimo, que é meu filho por estarmos unidos com Cristo, pois, enquanto eu estava na cadeia, tornei-me o pai espiritual dele.

[[v57-1-11]]

^<<v57-1-11,11>>^ Antes ele era inútil para você, mas agora é útil para você e para mim.

[[v57-1-12]]

^<<v57-1-12,12>>^ Eu estou mandando Onésimo de volta para você, e com ele vai o meu coração.

[[v57-1-13]]

^<<v57-1-13,13>>^ Gostaria de obrigá-lo a ficar aqui comigo, enquanto estou nesta cadeia por causa do evangelho , a fim de que ele me ajudasse em lugar de você.

[[v57-1-14]]

^<<v57-1-14,14>>^ Porém não vou fazer nada sem a aprovação de você, para que o favor que eu lhe estou pedindo não seja feito por obrigação, mas por sua livre vontade.

[[v57-1-15]]

^<<v57-1-15,15>>^ Pode ser que Onésimo tenha sido afastado de você por algum tempo a fim de que você o tenha de volta para sempre.

[[v57-1-16]]

^<<v57-1-16,16>>^ Pois agora ele não é mais um escravo, porém muito mais do que isso: é um querido irmão em Cristo. De fato, para mim ele é muito querido. E para você agora ele é mais querido ainda, não só como escravo, mas também como irmão no Senhor.

[[v57-1-17]]

^<<v57-1-17,17>>^ Por isso, se você me considera seu companheiro de trabalho, receba Onésimo de volta como se estivesse recebendo a mim mesmo.

[[v57-1-18]]

^<<v57-1-18,18>>^ Se ele deu algum prejuízo a você ou lhe deve alguma coisa, ponha isso na minha conta.

[[v57-1-19]]

^<<v57-1-19,19>>^ Aqui, com a minha própria mão escrevo isto: Eu, Paulo, pagarei tudo.  É claro que não preciso fazer com que você lembre que me deve a sua própria vida .

[[v57-1-20]]

^<<v57-1-20,20>>^ Portanto, meu irmão, me faça esse favor, por causa do Senhor. Anime o meu coração, como irmão em Cristo.

[[v57-1-21]]

^<<v57-1-21,21>>^ Ao escrever isso, estou certo de que você vai fazer o que lhe estou pedindo e sei até que você fará ainda mais .

[[v57-1-22]]

^<<v57-1-22,22>>^ Peço também que prepare um quarto para mim, pois espero que Deus responda às orações de todos vocês e me deixe ir outra vez até aí.

[[v57-1-23]]

^<<v57-1-23,23>>^ Epafras, o irmão que está na cadeia comigo por causa de Cristo Jesus, envia saudações a você.

[[v57-1-24]]

^<<v57-1-24,24>>^ E Marcos, Aristarco, Demas e Lucas, meus companheiros de trabalho, também enviam saudações.

[[v57-1-25]]

^<<v57-1-25,25>>^ Que a graça  do Senhor Jesus Cristo esteja com vocês!

'''

xref:056-tito/056-tito-003.adoc#v56-3-0[&#60; Capítulo Anterior] | <<v57-1-0,Topo>> | xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[Próximo Capítulo &#62;]