include::./index.adoc[]

[[v39-2-0]]
=== Malaquias, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v39-2-1]]

^<<v39-2-1,1>>^ O Senhor  Todo-Poderoso diz: — Sacerdotes, eu estou falando com vocês.

[[v39-2-2]]

^<<v39-2-2,2>>^ Se não obedecerem ao meu mandamento e se não resolverem me honrar, então eu farei cair sobre vocês uma maldição e amaldiçoarei tudo o que vocês recebem pelo trabalho que fazem. Aliás, já os amaldiçoei porque vocês não resolveram me honrar.

[[v39-2-3]]

^<<v39-2-3,3>>^ Vou castigar os seus filhos e esfregar na cara de vocês as fezes dos animais que vocês oferecem em sacrifício . E além disso vocês serão levados para o lugar onde as fezes são jogadas.

[[v39-2-4]]

^<<v39-2-4,4>>^ Assim vocês saberão que eu estou dando esta ordem a fim de que a minha aliança  com os sacerdotes, os descendentes de Levi, não seja quebrada. Sou eu, o Senhor  Todo-Poderoso, quem está falando.

[[v39-2-5]]

^<<v39-2-5,5>>^ — Na aliança que fiz com eles, eu lhes prometi vida e paz. Fiz o que tinha prometido, para que eles me respeitassem; e, de fato, eles me respeitaram e temeram .

[[v39-2-6]]

^<<v39-2-6,6>>^ Ensinavam sempre o que era direito e nunca o que era errado. Viviam em paz comigo, faziam o que é certo e ajudaram muitos a deixarem o caminho da maldade.

[[v39-2-7]]

^<<v39-2-7,7>>^ Os sacerdotes devem ensinar a verdade a meu respeito, e todos devem pedir conselho a eles para saber o que é direito, pois os sacerdotes são os mensageiros do Senhor  Todo-Poderoso.

[[v39-2-8]]

^<<v39-2-8,8>>^ — Mas agora vocês, sacerdotes, estão saindo do caminho certo, e os seus ensinamentos já fizeram muitas pessoas pecarem. Vocês estão quebrando a aliança que fiz com os sacerdotes.

[[v39-2-9]]

^<<v39-2-9,9>>^ Por isso, eu vou fazer com que o povo os despreze e rejeite, pois vocês não me obedecem e, quando julgam causas, não tratam a todos com justiça. Eu, o Senhor  Todo-Poderoso, estou falando.

[[v39-2-10]]

^<<v39-2-10,10>>^ Não é verdade que todos temos o mesmo Pai? Não fomos todos criados pelo mesmo Deus? Por que, então, enganamos uns aos outros, desprezando assim a aliança  que Deus fez com os nossos antepassados?

[[v39-2-11]]

^<<v39-2-11,11>>^ O povo de Judá tem sido infiel a Deus, e o povo de Israel e os moradores de Jerusalém fizeram coisas nojentas. O povo de Judá profanou  o Templo, que o Senhor  ama, e os homens casaram com mulheres que adoram ídolos.

[[v39-2-12]]

^<<v39-2-12,12>>^ Que o Senhor  expulse do nosso país as pessoas que fazem isso, sejam quem forem, mesmo que apresentem ofertas ao Senhor  Todo-Poderoso!

[[v39-2-13]]

^<<v39-2-13,13>>^ Existe outra coisa que vocês fazem: gemem e choram, cobrindo de lágrimas o altar de Deus porque ele já não aceita mais os sacrifícios  que vocês oferecem.

[[v39-2-14]]

^<<v39-2-14,14>>^ E cada um de vocês pergunta: "Por quê?" É porque Deus sabe que você tem sido infiel à sua esposa, a mulher com quem casou quando era moço. Ela era sua companheira, mas você quebrou a promessa que fez na presença de Deus de que seria fiel a ela.

[[v39-2-15]]

^<<v39-2-15,15>>^ Não é verdade que Deus criou um único ser, feito de carne e de espírito? E o que é que Deus quer dele? Que tenha filhos que sejam dedicados a Deus. Portanto, tenham cuidado para que nenhum de vocês seja infiel à sua mulher.

[[v39-2-16]]

^<<v39-2-16,16>>^ Pois o Senhor  Todo-Poderoso de Israel diz: — Eu odeio o divórcio; eu odeio o homem que faz uma coisa tão cruel assim. Portanto, tenham cuidado, e que ninguém seja infiel à sua mulher.

[[v39-2-17]]

^<<v39-2-17,17>>^ Vocês falam demais, e o Senhor  está cansado de toda essa conversa. Mas vocês ainda perguntam: "Como foi que fizemos com que Deus ficasse cansado?" Foi por dizerem assim: "O Senhor  Deus pensa que os que fazem maldades são bons e, de fato, Deus gosta deles." Ou então vocês perguntam: "Onde está o Deus justo?"

'''

xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[Próximo Capítulo &#62;]