include::./index.adoc[]

[[v39-3-0]]
=== Malaquias, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v39-3-1]]

^<<v39-3-1,1>>^ O Senhor  Todo-Poderoso diz: — Eu enviarei o meu mensageiro para preparar o meu caminho. E o Senhor a quem vocês estão procurando vai chegar de repente ao seu Templo. E está chegando o mensageiro que vocês esperam, aquele que vai trazer a aliança  que farei com vocês.

[[v39-3-2]]

^<<v39-3-2,2>>^ Mas quem poderá aguentar o dia em que ele vier? Quem ficará firme quando ele aparecer? Pois ele será como o fogo, para nos purificar ; será como o sabão, para nos lavar.

[[v39-3-3]]

^<<v39-3-3,3>>^ Ele se sentará para purificar os sacerdotes, os descendentes de Levi, como quem purifica e refina a prata e o ouro no fogo. Assim eles poderão oferecer a Deus os sacrifícios  que ele exige.

[[v39-3-4]]

^<<v39-3-4,4>>^ Então as ofertas trazidas pelo povo de Judá e pelos moradores de Jerusalém agradarão a Deus, como acontecia nos tempos passados.

[[v39-3-5]]

^<<v39-3-5,5>>^ O Senhor  Todo-Poderoso diz ao seu povo: — Eu virei julgá-los. E darei sem demora o meu testemunho contra todos os que não me respeitam, isto é, os feiticeiros, os adúlteros, os que juram falso, os que exploram os trabalhadores e os que negam os direitos das viúvas, dos órfãos e dos estrangeiros que vivem com vocês.

[[v39-3-6]]

^<<v39-3-6,6>>^ O Senhor  diz: — Eu sou o Senhor  e não mudo. É por isso que vocês, os descendentes de Jacó, não foram destruídos.

[[v39-3-7]]

^<<v39-3-7,7>>^ Vocês são como os seus antepassados: abandonam as minhas leis  e não as cumprem. Voltem para mim, e eu voltarei para vocês. Mas vocês perguntam: "Como é que vamos voltar?"

[[v39-3-8]]

^<<v39-3-8,8>>^ Eu pergunto: "Será que alguém pode roubar a Deus?" Mas vocês têm roubado e ainda me perguntam: "Como é que estamos te roubando?" Vocês me roubam nos dízimos  e nas ofertas.

[[v39-3-9]]

^<<v39-3-9,9>>^ Todos vocês estão me roubando, e por isso eu amaldiçoo a nação toda.

[[v39-3-10]]

^<<v39-3-10,10>>^ Eu, o Senhor  Todo-Poderoso, ordeno que tragam todos os seus dízimos aos depósitos do Templo, para que haja bastante comida na minha casa. Ponham-me à prova e verão que eu abrirei as janelas do céu e farei cair sobre vocês as mais ricas bênçãos.

[[v39-3-11]]

^<<v39-3-11,11>>^ Não deixarei que os gafanhotos destruam as suas plantações, e as suas parreiras  darão muitas uvas.

[[v39-3-12]]

^<<v39-3-12,12>>^ Todos os povos dirão que vocês são felizes, pois vocês vivem numa terra boa e rica. Eu, o Senhor  Todo-Poderoso, estou falando.

[[v39-3-13]]

^<<v39-3-13,13>>^ O Senhor  diz: — Vocês falaram mal de mim e ainda perguntam: "O que foi que falamos contra ti?"

[[v39-3-14]]

^<<v39-3-14,14>>^ Vocês dizem: "Não vale a pena servir a Deus. Não adianta nada a gente fazer o que o Senhor  Todo-Poderoso manda ou vestir roupas de luto para mostrar a ele que estamos arrependidos.

[[v39-3-15]]

^<<v39-3-15,15>>^ É fácil notar que os orgulhosos são felizes, e a gente vê que tudo dá certo para os maus; quando põem o Senhor  à prova, eles não são castigados."

[[v39-3-16]]

^<<v39-3-16,16>>^ Então os que temiam  o Senhor  falaram uns com os outros, e ele escutou com atenção o que estavam dizendo. E na presença dele foram escritos num livro os nomes dos que respeitavam a Deus e o adoravam.

[[v39-3-17]]

^<<v39-3-17,17>>^ O Senhor  Todo-Poderoso diz: — Eles serão o meu povo. Quando chegar o dia que estou preparando, eles serão o meu próprio povo. Eu terei compaixão deles como um pai tem compaixão do filho que lhe obedece.

[[v39-3-18]]

^<<v39-3-18,18>>^ E mais uma vez o meu povo verá a diferença entre o que acontece com as pessoas boas e com as más, entre os que me servem e os que não me obedecem.

'''

xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[&#60; Capítulo Anterior] | <<v39-3-0,Topo>> | xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[Próximo Capítulo &#62;]