include::./index.adoc[]

[[v39-1-0]]
=== Malaquias, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v39-1-1]]

^<<v39-1-1,1>>^ Esta é a mensagem que o Senhor  Deus mandou Malaquias entregar ao povo de Israel.

[[v39-1-2]]

^<<v39-1-2,2>>^ O Senhor  diz ao seu povo: — Eu sempre amei vocês. Mas eles perguntam: — Como podemos saber que tu nos amas? Deus responde: — Esaú e Jacó eram irmãos, no entanto, eu tenho amado Jacó e os seus descendentes,

[[v39-1-3]]

^<<v39-1-3,3>>^ mas tenho odiado Esaú e os seus descendentes. Eu fiz com que a região montanhosa de Esaú virasse um deserto, e agora as suas terras só prestam para animais selvagens morarem nelas.

[[v39-1-4]]

^<<v39-1-4,4>>^ Se os descendentes de Esaú, isto é, os edomitas, disserem: "As nossas cidades estão em ruínas, mas nós vamos construí-las de novo", o Senhor  Todo-Poderoso responderá: "Se eles construírem, eu destruirei. A terra deles será chamada de ‘terra da maldade’ e de ‘nação com quem o Senhor  está irado  para sempre’."

[[v39-1-5]]

^<<v39-1-5,5>>^ O povo de Israel vai ver isso acontecer, e todos dirão: — O Senhor  é grande, e o seu poder vai além das fronteiras de Israel!

[[v39-1-6]]

^<<v39-1-6,6>>^ O Senhor  Todo-Poderoso diz aos sacerdotes: — O filho respeita o pai, e o escravo respeita o seu senhor. Se eu sou o pai de vocês, por que é que vocês não me respeitam? Se eu sou o seu senhor, por que não me temem ? Vocês me desprezam, mas mesmo assim perguntam: "Como foi que te desprezamos?"

[[v39-1-7]]

^<<v39-1-7,7>>^ Foi com o alimento impuro  que vocês me ofereceram no altar. E vocês ainda perguntam: "Como é que estamos te ofendendo?" Pois vocês me ofendem quando acham que têm o direito de profanar  o meu altar.

[[v39-1-8]]

^<<v39-1-8,8>>^ E me ofendem também porque pensam que não faz mal me oferecerem animais cegos, aleijados ou doentes. Pois procurem oferecer um animal desses ao governador! Acham que ele o aceitaria com prazer e atenderia os seus pedidos? Eu, o Senhor  Todo-Poderoso, falei.

[[v39-1-9]]

^<<v39-1-9,9>>^ Agora, sacerdotes, orem a Deus e peçam que ele nos abençoe. Mas será que ele vai atender quando vocês estão apresentando ofertas como essas?

[[v39-1-10]]

^<<v39-1-10,10>>^ O Senhor  Todo-Poderoso diz aos sacerdotes: — Gostaria que um de vocês fechasse as portas do Templo. Assim vocês não acenderiam mais fogo inutilmente no meu altar. Eu não estou satisfeito com vocês; não vou aceitar as suas ofertas.

[[v39-1-11]]

^<<v39-1-11,11>>^ Eu sou adorado em todos os países do mundo, e em todos os lugares queimam incenso em minha honra e me oferecem sacrifícios puros . Todos me honram.

[[v39-1-12]]

^<<v39-1-12,12>>^ Mas vocês me ofendem quando pensam que têm o direito de profanar o meu altar e que os sacrifícios que oferecem não valem nada.

[[v39-1-13]]

^<<v39-1-13,13>>^ Vocês dizem: "Já estamos cansados de tudo isso!" e riem de mim e me tratam com desprezo. E ainda me oferecem um animal roubado ou um animal aleijado ou doente. Vocês acham que eu, o Senhor , vou aceitar isso?

[[v39-1-14]]

^<<v39-1-14,14>>^ Maldito seja o mentiroso que me promete um animal perfeito do seu rebanho, mas oferece em sacrifício um animal defeituoso! Eu sou o Rei poderoso, e todas as nações me honram. Eu, o Senhor  Todo-Poderoso, estou falando.

'''

xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[Próximo Capítulo &#62;]