include::./index.adoc[]

[[v25-4-0]]
=== Lamentações, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v25-4-1]]

^<<v25-4-1,1>>^ Como o ouro ficou escuro! Como o ouro puro perdeu o seu brilho! As pedras do Templo estão espalhadas pelas esquinas das ruas!

[[v25-4-2]]

^<<v25-4-2,2>>^ Os moços de Jerusalém eram tão preciosos para nós como o ouro puro, mas agora são tratados como simples potes de barro.

[[v25-4-3]]

^<<v25-4-3,3>>^ Até as lobas dão de mamar às suas crias, mas o meu povo é como os avestruzes, cruéis para os seus filhotes.

[[v25-4-4]]

^<<v25-4-4,4>>^ Os bebês de Jerusalém morrem de sede; as crianças pedem comida, mas ninguém lhes dá nada.

[[v25-4-5]]

^<<v25-4-5,5>>^ Os que antes comiam comidas finas agora morrem de fome pelas ruas; os que vestiam roupas caras agora vivem nos montes de lixo.

[[v25-4-6]]

^<<v25-4-6,6>>^ O meu povo tem sido mais castigado do que os moradores de Sodoma, que foi destruída num momento pela mão de Deus.

[[v25-4-7]]

^<<v25-4-7,7>>^ Os nossos príncipes eram puros como o leite e sem manchas como a neve; eram fortes, cheios de vigor, e os seus olhos brilhavam de saúde.

[[v25-4-8]]

^<<v25-4-8,8>>^ Agora, o seu rosto está preto como carvão, e, quando eles andam pelas ruas, ninguém os conhece. A pele deles secou como a madeira e grudou nos seus ossos.

[[v25-4-9]]

^<<v25-4-9,9>>^ Aqueles que morreram na guerra foram mais felizes do que os que morreram depois, porque estes foram se acabando devagarinho por não terem nada para comer.

[[v25-4-10]]

^<<v25-4-10,10>>^ Quando Jerusalém foi destruída, mulheres que antes eram amorosas cozinharam os seus próprios filhos e os comeram.

[[v25-4-11]]

^<<v25-4-11,11>>^ O Senhor  Deus descarregou o seu furor, derramou o ardor da sua ira . Ele pôs fogo em Jerusalém e a arrasou até o chão.

[[v25-4-12]]

^<<v25-4-12,12>>^ Ninguém neste mundo, nem mesmo os reis, acreditava que algum inimigo conseguisse entrar pelos portões de Jerusalém.

[[v25-4-13]]

^<<v25-4-13,13>>^ Tudo isso aconteceu por causa dos pecados e das maldades dos seus profetas  e dos seus sacerdotes, culpados de causar a morte de pessoas inocentes.

[[v25-4-14]]

^<<v25-4-14,14>>^ Sacerdotes e profetas andavam pelas ruas como cegos, tão sujos de sangue, que ninguém tocava na roupa deles.

[[v25-4-15]]

^<<v25-4-15,15>>^ E o povo gritava: "Fora daqui! Vocês são impuros ! Não encostem a mão em nós!" Quando eles fugiram, andando de país em país, os próprios pagãos disseram: "Esses homens não podem morar aqui."

[[v25-4-16]]

^<<v25-4-16,16>>^ O Senhor  não deu mais atenção a eles, o próprio Deus os espalhou. Ele não teve respeito pelos nossos sacerdotes, nem pena dos nossos líderes.

[[v25-4-17]]

^<<v25-4-17,17>>^ Ficamos olhando até cansar, esperando o socorro que nunca chegou. Confiamos no auxílio de uma nação que não podia ajudar.

[[v25-4-18]]

^<<v25-4-18,18>>^ Os inimigos nos estavam vigiando, de modo que não podíamos andar pelas ruas. Os nossos dias estavam contados, o fim estava perto.

[[v25-4-19]]

^<<v25-4-19,19>>^ Os nossos perseguidores foram mais rápidos do que as águias do céu; eles nos perseguiram nas montanhas e nos atacaram de surpresa no deserto.

[[v25-4-20]]

^<<v25-4-20,20>>^ Eles prenderam aquele que é a fonte da nossa vida, prenderam o rei que o Senhor  havia escolhido, aquele que pensávamos que ia nos defender dos invasores.

[[v25-4-21]]

^<<v25-4-21,21>>^ Vocês, povo de Edom e de Uz, podem rir; alegrem-se enquanto há tempo, pois a sua desgraça também está chegando. Vocês vão ficar bêbados e nus.

[[v25-4-22]]

^<<v25-4-22,22>>^ Jerusalém já recebeu o castigo pelos seus pecados. O Senhor  não deixará que os seus moradores fiquem espalhados em terras estrangeiras. Mas vocês, povo de Edom, serão castigados por Deus; ele fará com que todos fiquem conhecendo os pecados de vocês.

'''

xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[&#60; Capítulo Anterior] | <<v25-4-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[Próximo Capítulo &#62;]