include::./index.adoc[]

[[v25-1-0]]
=== Lamentações, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v25-1-1]]

^<<v25-1-1,1>>^ Como está abandonada Jerusalém, a cidade que antes vivia cheia de gente! Ela era respeitada no mundo inteiro, mas agora parece uma viúva; a rainha entre as nações hoje não passa de uma escrava.

[[v25-1-2]]

^<<v25-1-2,2>>^ Ela chora a noite inteira, as lágrimas correm pelo seu rosto. Dos seus antigos amigos não ficou nenhum para a consolar. Todos eles a traíram e agora são inimigos dela.

[[v25-1-3]]

^<<v25-1-3,3>>^ O povo de Judá foi levado para longe da sua pátria e sofre como escravo em trabalhos forçados. Eles moram em outros países e não têm descanso. Estão cercados pelos seus perseguidores e não podem escapar.

[[v25-1-4]]

^<<v25-1-4,4>>^ As estradas que levam a Sião  estão tristes, pois não há ninguém que vá por elas para as festas religiosas. As moças que cantavam no Templo estão aflitas, e os sacerdotes vivem gemendo. A cidade sofre amargamente, e não há gente para se reunir nas suas praças.

[[v25-1-5]]

^<<v25-1-5,5>>^ Os seus inimigos a dominam, e para eles tudo vai bem. É que o Senhor  Deus fez Jerusalém sofrer por causa dos muitos pecados dos seus moradores. Os seus filhos foram presos pelos inimigos e levados para longe da sua pátria.

[[v25-1-6]]

^<<v25-1-6,6>>^ A beleza de Jerusalém é coisa do passado. As suas autoridades são como corços que estão fracos de fome e fogem, sem forças, dos caçadores.

[[v25-1-7]]

^<<v25-1-7,7>>^ Nestes dias de tristeza e aflição, Jerusalém lembra de todas as riquezas que teve no passado. Ela se recorda de que ninguém veio ajudá-la quando caiu em poder dos inimigos, que zombaram dela na sua queda.

[[v25-1-8]]

^<<v25-1-8,8>>^ Ela perdeu a honra; está nua, e todos a desprezam. Ela vive gemendo e esconde o rosto, envergonhada. Jerusalém se tornou impura , por haver pecado gravemente.

[[v25-1-9]]

^<<v25-1-9,9>>^ Era fácil ver a mancha do seu pecado. Jerusalém não pensou no que poderia acontecer. Ela caiu de modo terrível e não tem quem a console. Os seus inimigos venceram, e ela pede que o Senhor  tenha misericórdia.

[[v25-1-10]]

^<<v25-1-10,10>>^ Os inimigos levaram embora todas as suas riquezas. O povo viu os pagãos entrarem no Templo, coisa que Deus os proibiu de fazer.

[[v25-1-11]]

^<<v25-1-11,11>>^ O povo de Jerusalém anda gemendo, procurando o que comer; eles trocaram as suas riquezas por alimentos para poder continuar a viver. A cidade diz: "Ó Senhor , olha para mim e vê a minha desgraça!"

[[v25-1-12]]

^<<v25-1-12,12>>^ Aos que vão passando, Jerusalém diz: "Olhem para mim! Será que existe uma dor igual à minha? No dia em que ficou irado , o Senhor  me castigou com esta aflição.

[[v25-1-13]]

^<<v25-1-13,13>>^ "Lá de cima, Deus enviou um fogo que queima dentro de mim. Ele me armou uma armadilha e me jogou no chão. Depois, me abandonou num sofrimento que não tem mais fim.

[[v25-1-14]]

^<<v25-1-14,14>>^ "Ele tomou nota dos meus pecados, amarrou-os todos juntos, pendurou-os no meu pescoço, e o peso deles acabou com as minhas forças. O Senhor me entregou aos meus inimigos, e eu não fui capaz de resistir.

[[v25-1-15]]

^<<v25-1-15,15>>^ "O Senhor fez pouco dos meus melhores soldados. Ele mandou um exército para destruir os meus moços e esmagou o meu povo santo como se esmagam as uvas para fazer vinho.

[[v25-1-16]]

^<<v25-1-16,16>>^ "Tudo isso me faz chorar e deixa os meus olhos cheios de lágrimas. Não há ninguém que me console, ninguém que me anime. Os inimigos me derrotaram, e o meu povo ficou no meio de ruínas.

[[v25-1-17]]

^<<v25-1-17,17>>^ "Eu estendo as mãos, mas ninguém quer me ajudar. De todos os lados, o Senhor  mandou inimigos contra mim, e eles me tratam como se eu fosse uma coisa nojenta.

[[v25-1-18]]

^<<v25-1-18,18>>^ "Mas o Senhor  é justo e me castigou, pois eu me revoltei contra os seus mandamentos. Todos os povos, escutem! Vejam a minha dor! As minhas moças e os meus moços foram levados para longe como prisioneiros.

[[v25-1-19]]

^<<v25-1-19,19>>^ "Pedi ajuda aos meus aliados, mas eles me traíram. Os sacerdotes e as autoridades morreram nas minhas ruas, enquanto procuravam comida para poder continuar a viver.

[[v25-1-20]]

^<<v25-1-20,20>>^ "Vê, ó Senhor , a minha aflição; estou profundamente perturbada! A dor aperta o meu coração quando penso que me revoltei contra ti. Há assassinatos nas ruas, e até dentro das casas há mortes.

[[v25-1-21]]

^<<v25-1-21,21>>^ "Ó Deus, ouve os meus gemidos, pois não há ninguém que me console. Todos os meus inimigos sabem da minha desgraça e ficam contentes porque tu me fizeste sofrer. Faze com que venha o dia que prometeste, para que os meus inimigos sofram tanto quanto eu.

[[v25-1-22]]

^<<v25-1-22,22>>^ "Condena-os por causa de todas as suas maldades, castiga-os como me castigaste por causa dos meus pecados. Eu não paro de gemer, e o meu coração está doente."

'''

xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[Próximo Capítulo &#62;]