include::./index.adoc[]

[[v25-3-0]]
=== Lamentações, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v25-3-1]]

^<<v25-3-1,1>>^ Eu sou aquele que sabe o que é sofrer os golpes da ira  de Deus.

[[v25-3-2]]

^<<v25-3-2,2>>^ Ele me levou para a escuridão e me fez andar por caminhos sem luz.

[[v25-3-3]]

^<<v25-3-3,3>>^ Com a sua mão, me bateu muitas vezes, o dia inteiro.

[[v25-3-4]]

^<<v25-3-4,4>>^ Deus fez envelhecer a minha carne e a minha pele e quebrou os meus ossos.

[[v25-3-5]]

^<<v25-3-5,5>>^ Em volta de mim, ele construiu um muro de sofrimento e amargura.

[[v25-3-6]]

^<<v25-3-6,6>>^ Ele me fez morar na escuridão, como se eu estivesse morto há muito tempo.

[[v25-3-7]]

^<<v25-3-7,7>>^ Deus me amarrou com pesadas correntes; estou na prisão e não posso escapar.

[[v25-3-8]]

^<<v25-3-8,8>>^ Grito pedindo socorro, mas ele não quer ouvir a minha oração.

[[v25-3-9]]

^<<v25-3-9,9>>^ Não posso seguir em frente, pois, com grandes blocos de pedra, ele fechou o meu caminho.

[[v25-3-10]]

^<<v25-3-10,10>>^ Deus tem sido para mim como um leão de tocaia, como um urso pronto para atacar.

[[v25-3-11]]

^<<v25-3-11,11>>^ Ele me afastou do caminho, me fez em pedaços e depois me abandonou.

[[v25-3-12]]

^<<v25-3-12,12>>^ Ele armou o seu arco e fez de mim o alvo das suas flechas.

[[v25-3-13]]

^<<v25-3-13,13>>^ As flechas atiradas por Deus entraram fundo na minha carne.

[[v25-3-14]]

^<<v25-3-14,14>>^ O dia inteiro as pessoas riem de mim; elas zombam de mim nas suas canções.

[[v25-3-15]]

^<<v25-3-15,15>>^ Deus me encheu de comidas amargas e me fez beber fel até eu não poder mais.

[[v25-3-16]]

^<<v25-3-16,16>>^ Ele esfregou o meu rosto no chão e quebrou os meus dentes nas pedras.

[[v25-3-17]]

^<<v25-3-17,17>>^ Já não sei mais o que é paz e esqueci o que é felicidade.

[[v25-3-18]]

^<<v25-3-18,18>>^ Não tenho muito tempo de vida, e a minha esperança no Senhor  acabou.

[[v25-3-19]]

^<<v25-3-19,19>>^ Eu lembro da minha tristeza e solidão, das amarguras e dos sofrimentos.

[[v25-3-20]]

^<<v25-3-20,20>>^ Penso sempre nisso e fico abatido.

[[v25-3-21]]

^<<v25-3-21,21>>^ Mas a esperança volta quando penso no seguinte:

[[v25-3-22]]

^<<v25-3-22,22>>^ O amor do Senhor  Deus não se acaba, e a sua bondade não tem fim.

[[v25-3-23]]

^<<v25-3-23,23>>^ Esse amor e essa bondade são novos todas as manhãs; e como é grande a fidelidade do Senhor !

[[v25-3-24]]

^<<v25-3-24,24>>^ Deus é tudo o que tenho; por isso, confio nele.

[[v25-3-25]]

^<<v25-3-25,25>>^ O Senhor  é bom para todos os que confiam nele.

[[v25-3-26]]

^<<v25-3-26,26>>^ O melhor é ter esperança e aguardar em silêncio a ajuda do Senhor .

[[v25-3-27]]

^<<v25-3-27,27>>^ E é bom que as pessoas aprendam a sofrer com paciência desde a sua juventude.

[[v25-3-28]]

^<<v25-3-28,28>>^ Quando Deus nos faz sofrer, devemos ficar sozinhos, pacientes e em silêncio.

[[v25-3-29]]

^<<v25-3-29,29>>^ Devemos nos curvar, humildes, pois ainda pode haver esperança.

[[v25-3-30]]

^<<v25-3-30,30>>^ Quando somos ofendidos, não devemos reagir, mas sim suportar todos os insultos.

[[v25-3-31]]

^<<v25-3-31,31>>^ O Senhor não rejeita ninguém para sempre.

[[v25-3-32]]

^<<v25-3-32,32>>^ Ele pode fazer a gente sofrer, mas também tem compaixão porque o seu amor é imenso.

[[v25-3-33]]

^<<v25-3-33,33>>^ Não é com prazer que ele nos causa sofrimento ou dor.

[[v25-3-34]]

^<<v25-3-34,34>>^ Deus sabe quando neste país os prisioneiros são massacrados sem compaixão.

[[v25-3-35]]

^<<v25-3-35,35>>^ O Deus Altíssimo sabe quando são desrespeitados os direitos humanos, que ele mesmo nos deu.

[[v25-3-36]]

^<<v25-3-36,36>>^ Sim, o Senhor sabe quando torcem a justiça num processo.

[[v25-3-37]]

^<<v25-3-37,37>>^ Ninguém pode fazer acontecer nada se Deus não quiser.

[[v25-3-38]]

^<<v25-3-38,38>>^ Tanto as coisas boas como as más acontecem por ordem do Deus Altíssimo.

[[v25-3-39]]

^<<v25-3-39,39>>^ Por que nos queixarmos da vida quando somos castigados por causa dos nossos pecados?

[[v25-3-40]]

^<<v25-3-40,40>>^ Examinemos seriamente o que temos feito e voltemos para o Senhor .

[[v25-3-41]]

^<<v25-3-41,41>>^ Abramos o nosso coração a Deus, que está no céu, e oremos assim:

[[v25-3-42]]

^<<v25-3-42,42>>^ "Ó Deus, nós pecamos, nos revoltamos, e não nos perdoaste.

[[v25-3-43]]

^<<v25-3-43,43>>^ "Tu ficaste irado conosco, nos perseguiste, nos mataste sem dó nem piedade.

[[v25-3-44]]

^<<v25-3-44,44>>^ Tu te cercaste de nuvens para que as nossas orações não chegassem a ti.

[[v25-3-45]]

^<<v25-3-45,45>>^ Fizeste com que as nações olhassem para nós como se fôssemos um monte de lixo e refugos.

[[v25-3-46]]

^<<v25-3-46,46>>^ "Somos insultados por todos os nossos inimigos.

[[v25-3-47]]

^<<v25-3-47,47>>^ Temos vivido no meio de medos, perigos, desgraças e destruição."

[[v25-3-48]]

^<<v25-3-48,48>>^ Dos meus olhos correm rios de lágrimas por causa da destruição do meu povo.

[[v25-3-49]]

^<<v25-3-49,49>>^ Sem parar, os meus olhos vão derramar lágrimas

[[v25-3-50]]

^<<v25-3-50,50>>^ até que o Senhor  olhe lá do céu e nos veja.

[[v25-3-51]]

^<<v25-3-51,51>>^ O meu coração sofre muito quando penso no que vi acontecer com as mulheres da minha cidade.

[[v25-3-52]]

^<<v25-3-52,52>>^ Os meus inimigos, que não tinham razão para me odiar, me caçaram como se eu fosse um passarinho.

[[v25-3-53]]

^<<v25-3-53,53>>^ Eles me jogaram vivo num poço e o taparam com uma pedra.

[[v25-3-54]]

^<<v25-3-54,54>>^ A água subiu acima da minha cabeça, e eu pensei: "Estou perdido!"

[[v25-3-55]]

^<<v25-3-55,55>>^ Do fundo do poço, gritei pedindo a tua ajuda, ó Senhor .

[[v25-3-56]]

^<<v25-3-56,56>>^ Roguei que me escutasses, e tu ouviste o meu grito.

[[v25-3-57]]

^<<v25-3-57,57>>^ No dia em que te chamei, chegaste perto de mim e disseste: "Não tenha medo!"

[[v25-3-58]]

^<<v25-3-58,58>>^ Ó Senhor, tu vieste me socorrer e salvaste a minha vida.

[[v25-3-59]]

^<<v25-3-59,59>>^ Julga a meu favor, ó Senhor , pois conheces as injustiças que tenho sofrido.

[[v25-3-60]]

^<<v25-3-60,60>>^ Tu sabes como os meus inimigos são vingativos e conheces os planos que fazem contra mim.

[[v25-3-61]]

^<<v25-3-61,61>>^ Ó Senhor  Deus, tu ouviste os seus insultos e conheces todos os seus planos.

[[v25-3-62]]

^<<v25-3-62,62>>^ Tu sabes que o dia inteiro falam contra mim e planejam me prejudicar.

[[v25-3-63]]

^<<v25-3-63,63>>^ Tu vês que, em todos os momentos, eles zombam de mim.

[[v25-3-64]]

^<<v25-3-64,64>>^ Ó Senhor , dá-lhes o que merecem, castiga-os pelo que têm feito.

[[v25-3-65]]

^<<v25-3-65,65>>^ Amaldiçoa-os e faze com que eles caiam no desespero.

[[v25-3-66]]

^<<v25-3-66,66>>^ Persegue-os na tua ira, ó Senhor , e acaba com eles aqui na terra!

'''

xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[&#60; Capítulo Anterior] | <<v25-3-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-004.adoc#v25-4-0[Próximo Capítulo &#62;]