include::./index.adoc[]

[[v25-2-0]]
=== Lamentações, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v25-2-1]]

^<<v25-2-1,1>>^ Quando ficou irado , o Senhor cobriu Jerusalém de escuridão. Ele transformou num monte de ruínas a cidade de Jerusalém, que parecia um céu e que era o orgulho do povo de Israel. No dia da sua ira, Deus abandonou até o seu próprio Templo.

[[v25-2-2]]

^<<v25-2-2,2>>^ Sem dó nem piedade, o Senhor destruiu todas as cidades de Judá e na sua ira acabou completamente com as suas fortalezas. Ele jogou por terra, humilhados, o reino de Judá e as suas autoridades.

[[v25-2-3]]

^<<v25-2-3,3>>^ No calor da sua ira, Deus acabou de uma vez com o poder de Israel. Quando os inimigos chegaram, ele não quis nos ajudar e ainda se jogou contra nós como um fogo que destrói tudo ao seu redor.

[[v25-2-4]]

^<<v25-2-4,4>>^ Como se fosse um inimigo, Deus apontou as suas flechas contra nós e, com a sua força, matou as pessoas mais estimadas do nosso povo. Ele derramou a sua ira, como se fosse fogo, sobre os moradores de Jerusalém.

[[v25-2-5]]

^<<v25-2-5,5>>^ O Senhor é como um inimigo. Ele destruiu Israel, derrubou as suas fortalezas e arrasou os seus palácios, trazendo com isso tristeza e choro sem fim para o povo de Judá.

[[v25-2-6]]

^<<v25-2-6,6>>^ Deus arrasou o seu Templo, como se fosse uma horta, e destruiu o lugar onde o adorávamos. Ele nos fez esquecer as festas religiosas e os sábados. No calor da sua ira, ele rejeitou com desprezo os reis e os sacerdotes.

[[v25-2-7]]

^<<v25-2-7,7>>^ O Senhor desprezou o seu altar, abandonou o seu Templo e deixou que os inimigos derrubassem as suas paredes. Ali eles deram os seus gritos de vitória, como nós fazíamos nos dias de festa.

[[v25-2-8]]

^<<v25-2-8,8>>^ O Senhor  decidiu arrasar as muralhas de Jerusalém. Ele fez o plano de destruição e, sem descanso, o levou até o fim. Muralhas e paredes racharam e vieram abaixo ao mesmo tempo.

[[v25-2-9]]

^<<v25-2-9,9>>^ Os portões da cidade estão enterrados no entulho, e as suas trancas foram despedaçadas. O rei e as autoridades estão espalhados pelas nações pagãs. Não se ensina mais a lei , e os profetas  não recebem mais visões de Deus, o Senhor .

[[v25-2-10]]

^<<v25-2-10,10>>^ Os moradores mais velhos de Jerusalém estão sentados no chão, em silêncio. Em sinal de tristeza, puseram terra na cabeça e vestiram roupa feita de pano grosseiro. As moças estão ajoelhadas, com a cabeça encostada no chão.

[[v25-2-11]]

^<<v25-2-11,11>>^ Os meus olhos estão gastos de tanto chorar; estou muito aflito. A tristeza acabou comigo por causa da destruição do meu povo, e porque vejo crianças e bebês morrendo de fome nas ruas da cidade.

[[v25-2-12]]

^<<v25-2-12,12>>^ Essas crianças dizem: "Mamãe, estou com fome! Mamãe, estou com sede!" Elas caem pelas ruas, como se estivessem feridas, e morrem aos poucos nos braços das mães.

[[v25-2-13]]

^<<v25-2-13,13>>^ Jerusalém querida, o que posso lhe dizer? Como posso consolar você? Nunca ninguém sofreu assim; a sua desgraça é tão grande como o mar. Quem poderá lhe dar esperança?

[[v25-2-14]]

^<<v25-2-14,14>>^ As visões dos seus profetas foram falsas e enganosas. Se eles tivessem condenado abertamente os seus pecados, tudo teria sido diferente e melhor para você. O que esses profetas fizeram foi enganá-la com mentiras.

[[v25-2-15]]

^<<v25-2-15,15>>^ Os que vão passando zombam de você. Eles sacodem a cabeça, dão risadas e perguntam: "É esta a cidade que era chamada de ‘Beleza Perfeita’? É esta o orgulho do mundo inteiro?"

[[v25-2-16]]

^<<v25-2-16,16>>^ Todos os seus inimigos falam contra você e zombam. Com ódio, eles dizem: "Nós destruímos Jerusalém! Chegou o dia que estávamos esperando! Nós vimos tudo o que aconteceu!"

[[v25-2-17]]

^<<v25-2-17,17>>^ O Senhor  fez o que havia planejado; ele cumpriu as ameaças que havia feito há muito tempo. Ele nos destruiu sem dó nem piedade, deixando que os inimigos nos vencessem e se alegrassem com a nossa derrota.

[[v25-2-18]]

^<<v25-2-18,18>>^ Que as suas muralhas, ó Jerusalém, peçam ajuda ao Senhor! Que as suas lágrimas corram dia e noite como um rio! Não descanse; chore sem parar!

[[v25-2-19]]

^<<v25-2-19,19>>^ Levante-se várias vezes de noite para clamar, pedindo ajuda ao Senhor. Derrame o coração na presença dele e peça pela vida dos seus filhos, que morrem de fome nas esquinas das ruas.

[[v25-2-20]]

^<<v25-2-20,20>>^ Olha, ó Senhor  Deus, e pensa: Alguma vez trataste alguém assim? Será que as mães deviam devorar os filhinhos que elas tanto amam? Será que profetas e sacerdotes deviam ser assassinados no próprio Templo?

[[v25-2-21]]

^<<v25-2-21,21>>^ Há mortos, tanto jovens como velhos, largados nas ruas; os meus moços e as minhas moças foram mortos à espada. No dia em que ficaste irado, tu, ó Deus, os mataste sem dó nem piedade.

[[v25-2-22]]

^<<v25-2-22,22>>^ Fizeste chegar, de todos os lados, os meus terríveis inimigos, que vieram como se fosse para uma festa religiosa. Ó Senhor , no dia em que ficaste irado, ninguém escapou, ninguém ficou vivo. Os inimigos destruíram os meus filhos que criei com tanto amor.

'''

xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[&#60; Capítulo Anterior] | <<v25-2-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[Próximo Capítulo &#62;]