include::./index.adoc[]

[[v5-5-0]]
=== Deuteronômio, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-5-1]]

^<<v5-5-1,1>>^ Moisés mandou que o povo se reunisse e falou assim: — Povo de Israel, preste atenção nas leis  e nos mandamentos que estou dando a vocês hoje. Aprendam essas leis e façam tudo para cumpri-las.

[[v5-5-2]]

^<<v5-5-2,2>>^ O Senhor , nosso Deus, fez uma aliança  conosco no monte Sinai.

[[v5-5-3]]

^<<v5-5-3,3>>^ Não foi com os nossos pais que ele fez essa aliança, mas foi conosco, foi com todos os que hoje estamos aqui vivos.

[[v5-5-4]]

^<<v5-5-4,4>>^ Do meio do fogo ali no monte o Senhor  Deus falou com vocês face a face.

[[v5-5-5]]

^<<v5-5-5,5>>^ Vocês ficaram com medo do fogo e não subiram o monte; por isso eu me coloquei entre o Senhor  Deus e vocês. E ele disse:

[[v5-5-6]]

^<<v5-5-6,6>>^ "Meu povo, eu, o Senhor , sou o seu Deus. Eu o tirei do Egito, a terra onde você era escravo.

[[v5-5-7]]

^<<v5-5-7,7>>^ — "Não adore outros deuses; adore somente a mim.

[[v5-5-8]]

^<<v5-5-8,8>>^ — "Não faça imagens de nenhuma coisa que há lá em cima no céu, ou aqui embaixo na terra, ou nas águas debaixo da terra.

[[v5-5-9]]

^<<v5-5-9,9>>^ Não se ajoelhe diante de ídolos, nem os adore, pois eu, o Senhor , sou o seu Deus e não tolero outros deuses. Eu castigo aqueles que me odeiam e castigo também os seus descendentes, até os seus bisnetos e trinetos.

[[v5-5-10]]

^<<v5-5-10,10>>^ Porém sou bondoso com aqueles que me amam e obedecem aos meus mandamentos e abençoo os seus descendentes por milhares de gerações .

[[v5-5-11]]

^<<v5-5-11,11>>^ — "Não use o meu nome sem o respeito que ele merece, pois eu sou o Senhor , o Deus de vocês, e castigo aqueles que desrespeitam o meu nome.

[[v5-5-12]]

^<<v5-5-12,12>>^ — "Guarde o sábado, que é um dia santo, como eu, o Senhor  Deus, mandei.

[[v5-5-13]]

^<<v5-5-13,13>>^ Faça todo o seu trabalho durante seis dias da semana;

[[v5-5-14]]

^<<v5-5-14,14>>^ mas o sétimo dia da semana é o dia de descanso, dedicado a mim, o seu Deus. Não faça nenhum trabalho nesse dia, nem você, nem os seus filhos, nem as suas filhas, nem os seus escravos, nem as suas escravas, nem os seus animais, nem os estrangeiros que vivem na terra de você. Assim como você descansa, os seus escravos também devem descansar.

[[v5-5-15]]

^<<v5-5-15,15>>^ Lembre que você foi escravo no Egito e que eu, o Senhor , seu Deus, o tirei de lá com a minha força e com o meu poder. É por isso que eu mando que você guarde o sábado.

[[v5-5-16]]

^<<v5-5-16,16>>^ — "Respeite o seu pai e a sua mãe, como eu, o seu Deus, estou ordenando, para que você viva muito tempo, e tudo corra bem para você na terra que estou lhe dando.

[[v5-5-17]]

^<<v5-5-17,17>>^ — "Não mate.

[[v5-5-18]]

^<<v5-5-18,18>>^ — "Não cometa adultério.

[[v5-5-19]]

^<<v5-5-19,19>>^ — "Não roube.

[[v5-5-20]]

^<<v5-5-20,20>>^ — "Não dê testemunho falso contra ninguém.

[[v5-5-21]]

^<<v5-5-21,21>>^ — "Não cobice a mulher de outro homem. Não cobice nada que seja de outro homem: a sua casa, as suas terras, os seus escravos, os seus animais ou qualquer outra coisa que seja dele."

[[v5-5-22]]

^<<v5-5-22,22>>^ E Moisés disse: — São esses os mandamentos que o Senhor  Deus deu ao povo de Israel quando todos estavam ao pé do monte Sinai. Do meio do fogo e das nuvens negras ele falou em voz alta e deu somente esses mandamentos e nenhum outro mais. Depois os escreveu em duas placas de pedra e deu para mim.

[[v5-5-23]]

^<<v5-5-23,23>>^ E Moisés continuou, dizendo: — O fogo queimava no alto do monte, e vocês ouviram a voz falar do meio da escuridão. Então os chefes das tribos  e as outras autoridades chegaram perto de mim

[[v5-5-24]]

^<<v5-5-24,24>>^ e me disseram: "O Senhor , nosso Deus, nos mostrou a sua glória  e o seu poder, e nós o ouvimos falar do meio do fogo. Hoje nós vimos que é possível Deus falar com uma pessoa e ela continuar viva.

[[v5-5-25]]

^<<v5-5-25,25>>^ Porém não queremos arriscar a vida outra vez. Esse grande fogo pode nos destruir, e, se nós ouvirmos a voz do Senhor , nosso Deus, sem dúvida morreremos.

[[v5-5-26]]

^<<v5-5-26,26>>^ Nunca houve alguém que continuasse a viver depois de ter ouvido, como nós ouvimos, o Deus vivo falando do meio do fogo.

[[v5-5-27]]

^<<v5-5-27,27>>^ Moisés, volte para o monte e escute o que o Senhor  Deus quer dizer, e depois venha e nos conte tudo aquilo que ele disser. Nós ouviremos com atenção e obedeceremos."

[[v5-5-28]]

^<<v5-5-28,28>>^ — O Senhor  ouviu o que vocês disseram quando estavam falando comigo e me disse: "Eu ouvi o que o povo lhe falou, e tudo o que disseram está certo.

[[v5-5-29]]

^<<v5-5-29,29>>^ Como seria bom se eles sempre pensassem assim, e me respeitassem, e sempre obedecessem a todos os meus mandamentos! Assim tudo daria certo para eles e para os seus descendentes para sempre.

[[v5-5-30]]

^<<v5-5-30,30>>^ Vá, Moisés, e mande que o povo volte para as suas barracas.

[[v5-5-31]]

^<<v5-5-31,31>>^ Mas você fique aqui comigo, e eu lhe direi todas as leis , ordens e mandamentos. Ensine-os ao povo a fim de que eles obedeçam a todas essas leis na terra que eu lhes estou dando para ser deles."

[[v5-5-32]]

^<<v5-5-32,32>>^ — Povo de Israel, faça tudo para cumprir todas as leis que o Senhor , nosso Deus, lhe deu. Nunca deixe de fazer exatamente o que Deus manda

[[v5-5-33]]

^<<v5-5-33,33>>^ e nunca se desvie do caminho que ele lhe mostra. Assim tudo correrá bem para todos vocês, e vocês viverão muitos anos na terra que vão possuir.

'''

xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[&#60; Capítulo Anterior] | <<v5-5-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[Próximo Capítulo &#62;]