include::./index.adoc[]

[[v5-8-0]]
=== Deuteronômio, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-8-1]]

^<<v5-8-1,1>>^ Moisés disse ao povo: — Tenham o cuidado de obedecer a todas as leis  que hoje eu estou dando a vocês, para que vocês vivam e se tornem mais numerosos, e entrem e tomem posse da terra que o Senhor  Deus jurou dar aos nossos antepassados.

[[v5-8-2]]

^<<v5-8-2,2>>^ Lembrem como o nosso Deus guiou vocês pelo deserto esses quarenta anos. Durante essa longa caminhada, Deus os humilhou e os pôs à prova para saber se estavam resolvidos ou não a obedecer aos seus mandamentos.

[[v5-8-3]]

^<<v5-8-3,3>>^ Ele os deixou passar fome e depois lhes deu para comer o maná , uma comida que nem vocês nem os seus antepassados conheciam. Deus fez isso para que soubessem que o ser humano não vive só de pão, mas vive de tudo o que o Senhor  Deus diz.

[[v5-8-4]]

^<<v5-8-4,4>>^ Durante esses quarenta anos as roupas que vocês vestiam não ficaram gastas, e os seus pés não ficaram inchados.

[[v5-8-5]]

^<<v5-8-5,5>>^ Fiquem sabendo que o Senhor , nosso Deus, os corrige como um pai corrige o filho.

[[v5-8-6]]

^<<v5-8-6,6>>^ Obedeçam, pois, aos seus mandamentos, vivam de acordo com os seus ensinamentos e temam  o Senhor , seu Deus.

[[v5-8-7]]

^<<v5-8-7,7>>^ Pois ele os está levando para uma terra boa, cheia de rios, e ribeirões, e de fontes que jorram água pelos vales e pelas montanhas.

[[v5-8-8]]

^<<v5-8-8,8>>^ É uma terra que produz trigo e cevada , uvas, figos e romãs, azeite e mel.

[[v5-8-9]]

^<<v5-8-9,9>>^ É uma terra onde nunca faltará comida ou qualquer outra coisa para vocês, uma terra onde as pedras têm ferro e as montanhas têm minas de cobre.

[[v5-8-10]]

^<<v5-8-10,10>>^ Vocês terão toda a comida que precisarem e louvarão o Senhor , nosso Deus, pela boa terra que lhes deu.

[[v5-8-11]]

^<<v5-8-11,11>>^ — Nunca esqueçam o Senhor , nosso Deus, e tenham o cuidado de obedecer aos seus mandamentos e às suas leis , que hoje eu estou dando a vocês.

[[v5-8-12]]

^<<v5-8-12,12>>^ Naquela terra vocês terão toda a comida que quiserem; construirão casas boas, onde morarão;

[[v5-8-13]]

^<<v5-8-13,13>>^ o seu gado e os seus rebanhos aumentarão; vocês ajuntarão mais prata e ouro e terão tudo de sobra.

[[v5-8-14]]

^<<v5-8-14,14>>^ Então, tomem cuidado para não ficarem orgulhosos e esquecerem o Senhor , nosso Deus, que os tirou do Egito, onde vocês eram escravos.

[[v5-8-15]]

^<<v5-8-15,15>>^ Ele os levou por aquele enorme e perigoso deserto, cheio de cobras venenosas e de escorpiões, e onde não havia água. Mas no deserto Deus fez sair água da rocha bruta, para vocês beberem,

[[v5-8-16]]

^<<v5-8-16,16>>^ e lhes deu para comer o maná , uma comida que os seus antepassados não conheciam. Ele fez tudo isso para humilhá-los e para fazê-los passar por provas a fim de abençoá-los mais tarde.

[[v5-8-17]]

^<<v5-8-17,17>>^ — Portanto, não pensem que foi com a sua própria força e com o seu trabalho que vocês conseguiram todas essas riquezas.

[[v5-8-18]]

^<<v5-8-18,18>>^ Lembrem do Senhor , nosso Deus, pois é ele quem lhes dá força para poderem conseguir riquezas. Vocês estão vendo que assim ele está cumprindo a aliança  feita por meio de juramento com os nossos antepassados.

[[v5-8-19]]

^<<v5-8-19,19>>^ Mas, se vocês esquecerem o Senhor , e adorarem e servirem outros deuses, eu aviso hoje que vocês certamente morrerão.

[[v5-8-20]]

^<<v5-8-20,20>>^ Se não obedecerem ao Senhor , nosso Deus, então vocês morrerão, como vão morrer os povos que Deus vai destruir na presença de vocês.

'''

xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[Próximo Capítulo &#62;]