include::./index.adoc[]

[[v5-1-0]]
=== Deuteronômio, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-1-1]]

^<<v5-1-1,1>>^ Neste livro estão os discursos que Moisés fez ao povo de Israel no deserto que fica a leste do rio Jordão. Os israelitas estavam no vale do rio Jordão, perto da cidade de Sufe. De um lado ficava a cidade de Parã, e do outro, as cidades de Tofel, Labã, Hazerote e Di-Zaabe.

[[v5-1-2]]

^<<v5-1-2,2>>^ (Do monte Sinai até a cidade de Cades-Barneia são onze dias de viagem, pelo caminho que atravessa a região montanhosa de Edom.)

[[v5-1-3]]

^<<v5-1-3,3>>^ Já fazia quarenta anos que o povo de Israel tinha saído do Egito, e no primeiro dia do décimo primeiro mês Moisés disse ao povo tudo o que o Senhor  Deus havia mandado que ele falasse.

[[v5-1-4]]

^<<v5-1-4,4>>^ Isso aconteceu depois que Moisés derrotou Seom, o rei dos amorreus, que morava na cidade de Hesbom, e Ogue, rei de Basã, que morava em Astarote e em Edrei.

[[v5-1-5]]

^<<v5-1-5,5>>^ Quando os israelitas estavam no território de Moabe, no lado leste do rio Jordão, Moisés começou a explicar ao povo a lei  de Deus. Moisés disse:

[[v5-1-6]]

^<<v5-1-6,6>>^ — Quando estávamos ao pé do monte Sinai, o Senhor , nosso Deus, nos falou assim: "Vocês já ficaram bastante tempo neste lugar.

[[v5-1-7]]

^<<v5-1-7,7>>^ Agora saiam daqui e vão caminhando na direção da região montanhosa dos amorreus e de todas as regiões vizinhas no vale do rio Jordão, e na direção das montanhas, da planície de Judá, da região sul e da costa do mar Mediterrâneo. Tomem posse de toda a terra de Canaã até os montes Líbanos, no Norte, e até o grande rio Eufrates, no Leste.

[[v5-1-8]]

^<<v5-1-8,8>>^ Aí está a terra que eu estou dando a vocês. Eu, o Senhor , jurei a Abraão, a Isaque e a Jacó, os antepassados de vocês, que daria essa terra a eles e aos seus descendentes. Portanto, vão e tomem posse dela."

[[v5-1-9]]

^<<v5-1-9,9>>^ Em seguida Moisés disse ao povo: — Quando ainda estávamos ao pé do monte Sinai, eu lhes disse: "Eu sozinho não posso cuidar de vocês.

[[v5-1-10]]

^<<v5-1-10,10>>^ O Senhor , nosso Deus, fez com que vocês aumentassem em número, e hoje são tantos como as estrelas do céu.

[[v5-1-11]]

^<<v5-1-11,11>>^ E que o Senhor , o Deus dos nossos antepassados, faça com que vocês sejam um povo ainda mil vezes maior do que são agora e que ele os abençoe, como prometeu!

[[v5-1-12]]

^<<v5-1-12,12>>^ Mas como é que eu posso, sozinho, aguentar a carga pesada de resolver todas as causas e todas as questões que aparecem no meio do povo?

[[v5-1-13]]

^<<v5-1-13,13>>^ Portanto, de cada tribo  escolham homens sábios, inteligentes e competentes, para que eu os ponha como chefes de vocês."

[[v5-1-14]]

^<<v5-1-14,14>>^ E Moisés continuou: — Vocês responderam que seria bom fazer o que eu tinha dito.

[[v5-1-15]]

^<<v5-1-15,15>>^ Por isso peguei os líderes de cada tribo, homens sábios e competentes, e os coloquei como seus chefes. Alguns eram responsáveis por mil homens; outros, por cem; outros, por cinquenta; e outros, por dez. Além desses, escolhi também outras autoridades para cada tribo.

[[v5-1-16]]

^<<v5-1-16,16>>^ Naquela mesma ocasião dei a seguinte ordem aos juízes: "Julguem todas as causas com justiça, seja entre dois israelitas, seja entre um israelita e um estrangeiro que vive no meio do povo.

[[v5-1-17]]

^<<v5-1-17,17>>^ Sejam honestos e justos nas suas decisões. Tratem todos de modo igual, tanto os humildes como os poderosos. Não tenham medo de ninguém, pois a sentença que vocês derem virá de Deus. Se algum caso for muito difícil para vocês, tragam para mim, que eu o julgarei."

[[v5-1-18]]

^<<v5-1-18,18>>^ — E assim naquele tempo eu lhes dei ordens a respeito de todas as coisas que vocês deviam fazer.

[[v5-1-19]]

^<<v5-1-19,19>>^ Moisés disse também ao povo: — Nós obedecemos à ordem do Senhor , nosso Deus, e partimos do monte Sinai. Vocês viram como era grande e perigoso aquele deserto que atravessamos, quando fomos para a região montanhosa dos amorreus. Finalmente chegamos à cidade de Cades-Barneia.

[[v5-1-20]]

^<<v5-1-20,20>>^ Ali eu disse a vocês: "Agora estamos na região montanhosa dos amorreus, a terra que o nosso Deus nos está dando.

[[v5-1-21]]

^<<v5-1-21,21>>^ Portanto, vão e tomem posse dessa terra que está diante de vocês, como o Senhor , o Deus dos nossos antepassados, mandou. Não tenham medo, nem se assustem."

[[v5-1-22]]

^<<v5-1-22,22>>^ Aí todos vocês chegaram perto de mim e disseram: "Seria bom que mandássemos na frente de nós alguns homens para espionarem a terra e trazerem informações a respeito do caminho que devemos seguir e das cidades que vamos encontrar lá."

[[v5-1-23]]

^<<v5-1-23,23>>^ Eu concordei com a ideia e escolhi doze homens, um de cada tribo .

[[v5-1-24]]

^<<v5-1-24,24>>^ Eles foram até a região montanhosa e chegaram ao vale de Escol. Depois de verem o que havia no vale,

[[v5-1-25]]

^<<v5-1-25,25>>^ eles voltaram, trazendo algumas frutas que encontraram lá. E nos contaram que a terra que o Senhor , nosso Deus, nos estava dando era boa.

[[v5-1-26]]

^<<v5-1-26,26>>^ — Mas vocês desobedeceram à ordem do Senhor  e não quiseram tomar posse da terra.

[[v5-1-27]]

^<<v5-1-27,27>>^ Em vez disso, ficaram nas suas barracas, queixando-se e dizendo: "O Senhor  está com ódio de nós; ele nos trouxe do Egito para sermos derrotados e mortos pelos amorreus.

[[v5-1-28]]

^<<v5-1-28,28>>^ Que terra é essa que temos de conquistar? Nós ficamos com medo quando os nossos espiões disseram que o povo dessa terra é mais numeroso e mais forte do que nós, e que as suas cidades são enormes e protegidas por muralhas que chegam até o céu! E disseram também que viram gigantes lá!"

[[v5-1-29]]

^<<v5-1-29,29>>^ — Então respondi: "Não se assustem, nem tenham medo dessa gente.

[[v5-1-30]]

^<<v5-1-30,30>>^ Pois o Senhor , nosso Deus, vai adiante de nós e ele combaterá por nós. Ele fará a mesma coisa que vocês o viram fazer em nosso favor no Egito

[[v5-1-31]]

^<<v5-1-31,31>>^ e também no deserto. Vocês viram como o nosso Deus nos levou pelo deserto, como um pai leva o seu filho, e nos guiou o tempo todo até que chegamos a este lugar."

[[v5-1-32]]

^<<v5-1-32,32>>^ — Mas mesmo assim vocês não confiaram no Senhor ,

[[v5-1-33]]

^<<v5-1-33,33>>^ que sempre ia adiante de vocês, na coluna de fogo durante a noite e na coluna de nuvem durante o dia. Ele fazia isso para mostrar o lugar onde vocês deviam armar o acampamento e para indicar o caminho que deviam seguir.

[[v5-1-34]]

^<<v5-1-34,34>>^ Moisés continuou: — Quando o Senhor  Deus ouviu as queixas que vocês estavam fazendo, ele ficou irado  e fez este juramento:

[[v5-1-35]]

^<<v5-1-35,35>>^ "Vocês, israelitas, são um povo mau. Por isso nenhum de vocês que é adulto verá a boa terra que eu prometi dar aos seus antepassados.

[[v5-1-36]]

^<<v5-1-36,36>>^ Somente Calebe, filho de Jefoné, verá essa terra. Calebe foi sempre fiel e obediente a mim, o Senhor , e por isso darei a ele e aos seus descendentes a terra por onde ele andou."

[[v5-1-37]]

^<<v5-1-37,37>>^ — E foi por causa de vocês que o Senhor  ficou irado comigo também e me disse: "Você também não vai entrar na Terra Prometida .

[[v5-1-38]]

^<<v5-1-38,38>>^ O seu ajudante, Josué, filho de Num, é que vai entrar. Anime-o, pois ele vai comandar o povo de Israel na conquista da terra."

[[v5-1-39]]

^<<v5-1-39,39>>^ — Depois Deus disse a todos nós: "Os seus filhos são crianças e não sabem a diferença entre o que é certo e o que é errado. E vocês estavam pensando que eles iam cair nas mãos dos inimigos. Mas eles, os seus filhos, entrarão na Terra Prometida. Eu lhes darei essa terra, e eles serão donos dela.

[[v5-1-40]]

^<<v5-1-40,40>>^ Agora continuem caminhando pelo deserto na direção do golfo de Ácaba."

[[v5-1-41]]

^<<v5-1-41,41>>^ — Então vocês responderam: "Moisés, nós pecamos contra Deus, o Senhor . Mas agora estamos resolvidos a obedecer às ordens do nosso Deus e atacar o inimigo." Aí cada um de vocês se aprontou para a batalha, pensando que seria fácil conquistar a região montanhosa.

[[v5-1-42]]

^<<v5-1-42,42>>^ Mas o Senhor  mandou que eu dissesse a vocês: "Não vão lá, nem entrem em nenhum combate, pois eu não irei com vocês, e os seus inimigos os derrotarão."

[[v5-1-43]]

^<<v5-1-43,43>>^ Porém vocês não me deram atenção; pelo contrário, ficaram cheios de orgulho, desobedeceram às ordens de Deus, o Senhor , e invadiram a região montanhosa.

[[v5-1-44]]

^<<v5-1-44,44>>^ Aí os amorreus que moravam naquela região saíram contra vocês, como um enxame de abelhas bravas. Vocês fugiram, e os amorreus os perseguiram até o território de Edom e os derrotaram na cidade de Horma.

[[v5-1-45]]

^<<v5-1-45,45>>^ Então vocês voltaram e clamaram pedindo ajuda ao Senhor , mas ele não lhes deu atenção, nem os atendeu.

[[v5-1-46]]

^<<v5-1-46,46>>^ E depois disso ficamos muito tempo em Cades.

'''

xref:004-numeros/004-numeros-036.adoc#v4-36-0[&#60; Capítulo Anterior] | <<v5-1-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[Próximo Capítulo &#62;]