include::./index.adoc[]

[[v5-10-0]]
=== Deuteronômio, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-10-1]]

^<<v5-10-1,1>>^ Moisés disse ao povo: — Depois disso o Senhor  Deus me disse: "Corte duas placas de pedra, iguais às primeiras, e faça também uma arca  de madeira. Então venha se encontrar comigo no monte,

[[v5-10-2]]

^<<v5-10-2,2>>^ e eu escreverei nas placas aquilo que escrevi naquelas que você quebrou. Depois ponha as placas na arca."

[[v5-10-3]]

^<<v5-10-3,3>>^ — Eu fiz uma arca de madeira de acácia, cortei duas placas de pedra iguais às primeiras e subi o monte, levando-as comigo.

[[v5-10-4]]

^<<v5-10-4,4>>^ Aí Deus, o Senhor , conforme havia feito antes, escreveu nelas os dez mandamentos, os mesmos que tinha dado a vocês quando falou do meio do fogo no alto do monte, naquele dia em que vocês estavam reunidos na presença dele. O Senhor  me entregou as placas,

[[v5-10-5]]

^<<v5-10-5,5>>^ e eu desci do monte. Conforme ele havia ordenado, coloquei as placas na arca que eu havia feito, e elas ainda estão ali.

[[v5-10-6]]

^<<v5-10-6,6>>^ (Os israelitas partiram dos poços de Benê-Jacã e foram até Mosera. Ali Arão morreu e foi sepultado, e o seu filho Eleazar ficou no lugar dele como sacerdote.

[[v5-10-7]]

^<<v5-10-7,7>>^ Depois o povo foi para Gudgoda e dali para Jotbatá, uma região onde há muitos ribeirões.

[[v5-10-8]]

^<<v5-10-8,8>>^ Foi naquela ocasião que o Senhor  Deus escolheu a tribo  de Levi para que os homens dessa tribo levassem a arca da aliança, servissem como sacerdotes e abençoassem o povo em nome de Deus, o Senhor . E eles ainda continuam fazendo tudo isso.

[[v5-10-9]]

^<<v5-10-9,9>>^ Portanto, a tribo de Levi não recebeu terras em Canaã, como as outras tribos receberam. Conforme a promessa do Senhor  Deus, o que essa tribo recebeu foi o direito de os homens servirem como sacerdotes de Deus.)

[[v5-10-10]]

^<<v5-10-10,10>>^ E Moisés continuou, dizendo ao povo: — Eu fiquei no monte quarenta dias e quarenta noites, como na primeira vez. Mais uma vez o Senhor  Deus atendeu o meu pedido e não acabou com vocês.

[[v5-10-11]]

^<<v5-10-11,11>>^ E mandou que eu fosse e os guiasse, para que entrassem e tomassem posse da terra que ele havia jurado dar aos nossos antepassados.

[[v5-10-12]]

^<<v5-10-12,12>>^ — Povo de Israel, escute o que o Senhor  Deus exige de você. Ele quer que vocês o temam  e sigam todas as suas ordens; quer que o amem e que o sirvam com todo o coração e com toda a alma.

[[v5-10-13]]

^<<v5-10-13,13>>^ Obedeçam a todas as leis  de Deus que eu estou dando a vocês hoje, para o seu bem.

[[v5-10-14]]

^<<v5-10-14,14>>^ Os mais altos céus são de Deus, o Senhor ; a ele pertencem a terra e tudo o que nela existe.

[[v5-10-15]]

^<<v5-10-15,15>>^ Mas o amor dele pelos antepassados de vocês foi tão grande, que de todos os povos do mundo ele escolheu vocês, e até o dia de hoje vocês são o seu povo escolhido.

[[v5-10-16]]

^<<v5-10-16,16>>^ Portanto, sejam obedientes a Deus e deixem de ser teimosos.

[[v5-10-17]]

^<<v5-10-17,17>>^ Pois o Senhor , nosso Deus, está acima de todos os deuses e autoridades. Ele é grande, poderoso e causa medo. Ele trata a todos igualmente e não aceita presentes para torcer a justiça.

[[v5-10-18]]

^<<v5-10-18,18>>^ Ele defende os direitos dos órfãos e das viúvas; ele ama os estrangeiros que vivem entre nós e lhes dá comida e roupa.

[[v5-10-19]]

^<<v5-10-19,19>>^ Amem esses estrangeiros, pois vocês foram estrangeiros no Egito.

[[v5-10-20]]

^<<v5-10-20,20>>^ Temam o Senhor , nosso Deus, e adorem somente a ele; fiquem ligados com ele e jurem somente pelo seu nome.

[[v5-10-21]]

^<<v5-10-21,21>>^ Louvem a Deus; ele é o nosso Deus. Vocês viram com os seus próprios olhos as grandes e espantosas coisas que Deus fez em favor de vocês.

[[v5-10-22]]

^<<v5-10-22,22>>^ Quando os nossos antepassados foram para o Egito, eram somente setenta pessoas; mas agora, por causa das bênçãos do Senhor , nosso Deus, vocês são tantos como as estrelas do céu.

'''

xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[Próximo Capítulo &#62;]