include::./index.adoc[]

[[v5-30-0]]
=== Deuteronômio, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-30-1]]

^<<v5-30-1,1>>^ Moisés disse ao povo: — Eu já anunciei a vocês as bênçãos e as maldições que Deus prometeu mandar. Quando ele fizer cair sobre vocês os castigos, e vocês estiverem espalhados por todas as nações onde o Senhor , nosso Deus, os tiver jogado, vocês lembrarão daquelas bênçãos e maldições.

[[v5-30-2]]

^<<v5-30-2,2>>^ Portanto, se vocês e os seus descendentes se voltarem arrependidos para Deus e com todo o coração e com toda a alma obedecerem ao que ele manda fazer, conforme as ordens que hoje eu estou dando a vocês,

[[v5-30-3]]

^<<v5-30-3,3>>^ então o Senhor , nosso Deus, terá pena de vocês. Ele os reunirá de todos os países por onde os tiver espalhado e os trará de volta à pátria.

[[v5-30-4]]

^<<v5-30-4,4>>^ Mesmo que vocês estejam espalhados até os cantos mais distantes do mundo, o Senhor , nosso Deus, os reunirá e os fará voltar

[[v5-30-5]]

^<<v5-30-5,5>>^ para a terra que os antepassados de vocês tinham possuído. Ela será de vocês, e Deus os abençoará ainda mais do que abençoou os seus antepassados.

[[v5-30-6]]

^<<v5-30-6,6>>^ O Senhor , nosso Deus, dará a vocês e aos seus descendentes corações dispostos a obedecer, a fim de que o amem com todo o coração e com toda a alma e assim continuem a viver naquela terra.

[[v5-30-7]]

^<<v5-30-7,7>>^ Com aquelas maldições o Senhor  Deus castigará todos os inimigos, todos os que odeiam e perseguem vocês,

[[v5-30-8]]

^<<v5-30-8,8>>^ e vocês obedecerão de novo a Deus, o Senhor , e cumprirão todos os seus mandamentos que hoje eu estou dando a vocês.

[[v5-30-9]]

^<<v5-30-9,9>>^ Então Deus os abençoará em tudo o que fizerem e lhes dará muitos filhos, muitos animais e boas colheitas. Deus novamente terá prazer em fazê-los prosperar, como fez com os seus antepassados.

[[v5-30-10]]

^<<v5-30-10,10>>^ Isso ele fará se vocês obedecerem ao Senhor , nosso Deus, se cumprirem todas as suas leis  e todos os seus mandamentos que estão escritos neste Livro da Lei  de Deus e se voltarem com todo o coração e com toda a alma para o Senhor , nosso Deus.

[[v5-30-11]]

^<<v5-30-11,11>>^ — Os mandamentos que hoje estou dando a vocês não são difíceis de entender, nem de cumprir.

[[v5-30-12]]

^<<v5-30-12,12>>^ Não estão lá em cima, no céu, de modo que vocês perguntem: "Quem subirá até o céu a fim de nos trazer os mandamentos, para os ouvirmos e cumprirmos?"

[[v5-30-13]]

^<<v5-30-13,13>>^ Nem estão do outro lado do mar, de modo que perguntem: "Quem atravessará o mar a fim de nos trazer os mandamentos, para os ouvirmos e cumprirmos?"

[[v5-30-14]]

^<<v5-30-14,14>>^ Pelo contrário, os mandamentos estão aqui com vocês; vocês os guardam no coração e podem recitá-los e por isso devem cumpri-los.

[[v5-30-15]]

^<<v5-30-15,15>>^ — Hoje estou deixando que vocês escolham entre o bem e o mal, entre a vida e a morte.

[[v5-30-16]]

^<<v5-30-16,16>>^ Se vocês obedecerem aos mandamentos do Senhor , nosso Deus, que hoje eu estou dando a vocês, e o amarem, e andarem no caminho que ele mostra, e cumprirem todas as suas leis  e todos os seus mandamentos, vocês viverão muito tempo na terra que vão invadir e que vai ser de vocês. E Deus os abençoará e lhes dará muitos descendentes.

[[v5-30-17]]

^<<v5-30-17,17>>^ Porém eu lhes afirmo hoje mesmo que, se abandonarem a Deus e não quiserem obedecer e se caírem na tentação de adorar e servir outros deuses, nesse caso vocês serão completamente destruídos e não viverão muito tempo na terra que estão para possuir no outro lado do rio Jordão.

[[v5-30-18]]

^<<v5-30-18,18>>^ Porém eu lhes afirmo hoje mesmo que, se abandonarem a Deus e não quiserem obedecer e se caírem na tentação de adorar e servir outros deuses, nesse caso vocês serão completamente destruídos e não viverão muito tempo na terra que estão para possuir no outro lado do rio Jordão.

[[v5-30-19]]

^<<v5-30-19,19>>^ Neste dia chamo o céu e a terra como testemunhas contra vocês. Eu lhes dou a oportunidade de escolherem entre a vida e a morte, entre a bênção e a maldição. Escolham a vida, para que vocês e os seus descendentes vivam muitos anos.

'''

xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[&#60; Capítulo Anterior] | <<v5-30-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[Próximo Capítulo &#62;]