include::./index.adoc[]

[[v5-23-0]]
=== Deuteronômio, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-23-1]]

^<<v5-23-1,1>>^ Moisés disse ao povo: — Nenhum homem castrado ou que tenha o membro cortado poderá fazer parte do povo de Deus, o Senhor .

[[v5-23-2]]

^<<v5-23-2,2>>^ — Nenhum filho ilegítimo fará parte do povo do Senhor , nem ele nem os seus descendentes até dez gerações .

[[v5-23-3]]

^<<v5-23-3,3>>^ — Nenhum amonita ou moabita, até a décima geração, fará parte do povo de Deus, o Senhor . Eles ficarão de fora

[[v5-23-4]]

^<<v5-23-4,4>>^ porque, quando vocês estavam saindo do Egito, eles não lhes deram comida nem água. E também porque pagaram Balaão, filho de Beor, da cidade de Petor, na Mesopotâmia, para amaldiçoar vocês.

[[v5-23-5]]

^<<v5-23-5,5>>^ Mas o Senhor , nosso Deus, não atendeu o pedido de Balaão; pelo contrário, Deus virou a maldição em bênção porque ama vocês.

[[v5-23-6]]

^<<v5-23-6,6>>^ Nunca façam coisa alguma para o bem ou proveito desses povos.

[[v5-23-7]]

^<<v5-23-7,7>>^ — Não desprezem os edomitas, pois eles são seus parentes ; nem desprezem os egípcios, pois vocês viveram como estrangeiros na terra deles.

[[v5-23-8]]

^<<v5-23-8,8>>^ Dos netos em diante, os descendentes dos edomitas e dos egípcios que morarem na terra de vocês poderão fazer parte do povo de Deus.

[[v5-23-9]]

^<<v5-23-9,9>>^ — Quando estiverem acampados durante uma guerra, procurem evitar qualquer coisa que os torne impuros .

[[v5-23-10]]

^<<v5-23-10,10>>^ Se durante a noite alguém ficar impuro por causa da perda de esperma, sairá do acampamento de manhã.

[[v5-23-11]]

^<<v5-23-11,11>>^ À tarde tomará um banho e ao pôr do sol poderá voltar ao acampamento.

[[v5-23-12]]

^<<v5-23-12,12>>^ — Arranjem um lugar fora do acampamento onde poderão fazer necessidade.

[[v5-23-13]]

^<<v5-23-13,13>>^ Junto com as suas armas levem uma pá e, antes de fazer necessidade, cavem um buraco e depois cubram as fezes com terra.

[[v5-23-14]]

^<<v5-23-14,14>>^ — O Senhor , nosso Deus, está presente no acampamento com vocês, para protegê-los e para fazer com que vocês derrotem os inimigos. Portanto, conservem o acampamento puro  a fim de que Deus não encontre nele nenhuma coisa que o ofenda, para que ele não os abandone e vá embora.

[[v5-23-15]]

^<<v5-23-15,15>>^ — Se um escravo fugir do dono e vier pedir que você lhe dê proteção, não o entregue ao dono.

[[v5-23-16]]

^<<v5-23-16,16>>^ Ele deverá ficar morando em qualquer cidade israelita que quiser e não poderá ser maltratado.

[[v5-23-17]]

^<<v5-23-17,17>>^ — Nenhum israelita, mulher ou homem, praticará a prostituição nos templos pagãos .

[[v5-23-18]]

^<<v5-23-18,18>>^ O dinheiro ganho desse modo não poderá ser levado ao Templo do Senhor  para pagamento de uma promessa feita ao Senhor , nosso Deus. Deus detesta esse dinheiro.

[[v5-23-19]]

^<<v5-23-19,19>>^ — Não cobrem juros quando emprestarem dinheiro, comida ou qualquer outra coisa a um israelita.

[[v5-23-20]]

^<<v5-23-20,20>>^ Vocês poderão cobrar juros dos estrangeiros; mas não cobrem de outro israelita, para que o Senhor , nosso Deus, abençoe tudo o que vocês fizerem na terra que vai ser de vocês.

[[v5-23-21]]

^<<v5-23-21,21>>^ — Quando você fizer uma promessa ao Senhor , nosso Deus, não demore a cumpri-la. Deus exige que a promessa seja cumprida; e é pecado deixar de fazer aquilo que você prometeu.

[[v5-23-22]]

^<<v5-23-22,22>>^ Não é pecado deixar de fazer uma promessa a Deus;

[[v5-23-23]]

^<<v5-23-23,23>>^ mas, se você, por vontade própria, fizer uma promessa, então deverá cumpri-la sem falta.

[[v5-23-24]]

^<<v5-23-24,24>>^ — Quando estiver andando num caminho que atravessa a plantação de uvas de outro israelita, você poderá comer todas as uvas que quiser, porém não carregue uvas num cesto.

[[v5-23-25]]

^<<v5-23-25,25>>^ E, quando estiver atravessando o campo de trigo ou de cevada  que pertence a outro israelita, você poderá comer todas as espigas que puder colher com as mãos; porém não use uma foice para colher as espigas.

'''

xref:005-deuteronomio/005-deuteronomio-022.adoc#v5-22-0[&#60; Capítulo Anterior] | <<v5-23-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-024.adoc#v5-24-0[Próximo Capítulo &#62;]