include::./index.adoc[]

[[v5-34-0]]
=== Deuteronômio, 34
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-34-1]]

^<<v5-34-1,1>>^ Moisés foi das planícies de Moabe até o monte Nebo e subiu ao alto do monte Pisga, na altura de Jericó, que ficava no outro lado do rio. Dali o Senhor  Deus lhe mostrou toda a terra de Canaã, isto é, o território de Gileade até a cidade de Dã, no Norte;

[[v5-34-2]]

^<<v5-34-2,2>>^ o território das tribos  de Naftali, Efraim e Manassés do Oeste; o território de Judá até o mar Mediterrâneo, no Oeste;

[[v5-34-3]]

^<<v5-34-3,3>>^ a região sul e a planície que vai de Zoar até Jericó, a cidade das palmeiras.

[[v5-34-4]]

^<<v5-34-4,4>>^ E Deus disse a Moisés: — Eu jurei a Abraão, a Isaque e a Jacó que daria esta terra aos descendentes deles. Estou deixando que você a veja com os seus próprios olhos, mas você não vai entrar nela.

[[v5-34-5]]

^<<v5-34-5,5>>^ Assim Moisés, servo  do Senhor  Deus, morreu na terra de Moabe, conforme o Senhor  tinha dito.

[[v5-34-6]]

^<<v5-34-6,6>>^ Deus o sepultou ali, num vale que fica em frente da cidade de Bete-Peor. Até hoje ninguém sabe onde ele foi sepultado.

[[v5-34-7]]

^<<v5-34-7,7>>^ Moisés tinha cento e vinte anos quando morreu, mas ainda enxergava bem e tinha boa saúde.

[[v5-34-8]]

^<<v5-34-8,8>>^ Ali nas planícies de Moabe os israelitas choraram a morte de Moisés trinta dias, até terminar o tempo de luto.

[[v5-34-9]]

^<<v5-34-9,9>>^ Moisés havia escolhido Josué, filho de Num, para ficar no seu lugar. Ele pôs as mãos sobre a cabeça de Josué, que assim ficou cheio de sabedoria. Os israelitas obedeceram a Josué e cumpriram todas as leis  que o Senhor  Deus lhes tinha dado por meio de Moisés.

[[v5-34-10]]

^<<v5-34-10,10>>^ Nunca mais apareceu em Israel um profeta  como Moisés, com quem o Senhor  falava face a face.

[[v5-34-11]]

^<<v5-34-11,11>>^ Nunca houve ninguém que fizesse maravilhas e milagres como aqueles que Moisés, obedecendo à ordem do Senhor , fez no Egito contra o seu rei, os seus oficiais e todo o seu povo.

[[v5-34-12]]

^<<v5-34-12,12>>^ Nunca houve outro profeta que fizesse os milagres e as coisas espantosas que Moisés fez com grande poder na presença do povo de Israel.

'''

xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[&#60; Capítulo Anterior] | <<v5-34-0,Topo>> | xref:006-josue/006-josue-001.adoc#v6-1-0[Próximo Capítulo &#62;]