include::./index.adoc[]

[[v5-7-0]]
=== Deuteronômio, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-7-1]]

^<<v5-7-1,1>>^ Moisés disse ao povo: — O Senhor , nosso Deus, fará com que vocês entrem na terra que vão possuir e ele mesmo expulsará os povos que vocês enfrentarem. Conforme vocês forem avançando, Deus derrotará sete povos que são mais numerosos e mais poderosos do que vocês. São eles: os heteus, os girgaseus, os amorreus, os cananeus, os perizeus, os heveus e os jebuseus.

[[v5-7-2]]

^<<v5-7-2,2>>^ O Senhor  entregará esses povos nas suas mãos, e vocês os atacarão e destruirão completamente. Não façam nenhum acordo  de paz com eles, nem tenham pena deles.

[[v5-7-3]]

^<<v5-7-3,3>>^ Não casem com essa gente, nem vocês, nem os seus filhos ou as suas filhas,

[[v5-7-4]]

^<<v5-7-4,4>>^ pois esses povos farão com que os seus filhos rejeitem a Deus e adorem outros deuses. Aí o Senhor  Deus ficará irado  com vocês e os destruirá de uma vez.

[[v5-7-5]]

^<<v5-7-5,5>>^ Portanto, derrubem os altares desses povos, quebrem as colunas do deus Baal , cortem os postes da deusa Aserá  e queimem todas as imagens.

[[v5-7-6]]

^<<v5-7-6,6>>^ Pois vocês são o povo escolhido pelo Senhor , nosso Deus; entre todos os povos da terra ele escolheu vocês para serem somente dele.

[[v5-7-7]]

^<<v5-7-7,7>>^ — O Senhor  Deus os amou e escolheu, não porque vocês são mais numerosos do que outros povos; de fato, vocês são menos numerosos do que qualquer outro povo.

[[v5-7-8]]

^<<v5-7-8,8>>^ Mas o Senhor  os amou e com a sua força os livrou do poder de Faraó, o rei do Egito, onde vocês eram escravos. Ele fez isso para cumprir o juramento que tinha feito aos nossos antepassados.

[[v5-7-9]]

^<<v5-7-9,9>>^ Lembrem que o Senhor , nosso Deus, é o único Deus. Ele é fiel e mantém a sua aliança . Ele continua a amar, por mil gerações , aqueles que o amam e obedecem aos seus mandamentos,

[[v5-7-10]]

^<<v5-7-10,10>>^ porém castiga de uma vez os que o rejeitam. Ele não demora em castigá-los e destruí-los.

[[v5-7-11]]

^<<v5-7-11,11>>^ Obedeçam, pois, às leis  e aos mandamentos que hoje eu estou dando a vocês e façam tudo o que eu mando.

[[v5-7-12]]

^<<v5-7-12,12>>^ — Se vocês derem atenção a essas leis  e as cumprirem fielmente, o Senhor , nosso Deus, manterá a sua aliança  e continuará a amá-los, conforme prometeu aos nossos antepassados.

[[v5-7-13]]

^<<v5-7-13,13>>^ Ele os amará, e abençoará, e fará com que se tornem mais e mais numerosos. Ele lhes dará muitos filhos, boas colheitas de cereais, uvas e azeitonas e muitas crias de gado e de ovelhas. Deus lhes dará todas essas bênçãos na terra que ele vai lhes dar, conforme o juramento que fez aos nossos antepassados.

[[v5-7-14]]

^<<v5-7-14,14>>^ Vocês serão o povo mais abençoado do mundo. Todos terão filhos, e todos os seus animais terão crias.

[[v5-7-15]]

^<<v5-7-15,15>>^ O Senhor  Deus os protegerá de toda enfermidade e nunca os castigará com as terríveis doenças com que castigou os egípcios, como vocês bem sabem. Pelo contrário, ele mandará essas doenças para os povos que odeiam vocês.

[[v5-7-16]]

^<<v5-7-16,16>>^ Acabem com todos os povos que o Senhor , nosso Deus, entregar nas mãos de vocês. Não tenham pena deles, nem adorem os seus deuses, pois isso seria uma armadilha mortal para vocês.

[[v5-7-17]]

^<<v5-7-17,17>>^ — Não fiquem pensando assim: "Estes povos são mais numerosos do que nós; como poderemos derrotá-los?"

[[v5-7-18]]

^<<v5-7-18,18>>^ Não tenham medo deles; lembrem daquilo que o Senhor , nosso Deus, fez com o rei do Egito e com todo o seu povo.

[[v5-7-19]]

^<<v5-7-19,19>>^ Lembrem das pragas, dos milagres e das coisas espantosas que vocês viram e não esqueçam o grande poder com que o Senhor  os tirou do Egito. Pois o Senhor , nosso Deus, fará com esses povos, de quem vocês estão com medo, a mesma coisa que fez com os egípcios.

[[v5-7-20]]

^<<v5-7-20,20>>^ Deus fará com que esses povos fujam apavorados e destruirá os que escaparem e se esconderem de vocês.

[[v5-7-21]]

^<<v5-7-21,21>>^ — Portanto, não tenham medo deles, pois com vocês está o Senhor , nosso Deus, o Deus que é forte e causa medo.

[[v5-7-22]]

^<<v5-7-22,22>>^ Pouco a pouco ele irá expulsando os povos que vocês enfrentarem. Mas vocês não irão destruí-los todos de uma vez; se fizessem isso, o número dos animais selvagens aumentaria, e eles seriam um grande perigo.

[[v5-7-23]]

^<<v5-7-23,23>>^ O Senhor  vai entregar os inimigos nas mãos de vocês e vai deixá-los tão apavorados, que eles serão destruídos.

[[v5-7-24]]

^<<v5-7-24,24>>^ Deus também entregará nas suas mãos os reis desses povos. Vocês os matarão, e ninguém lembrará nem do nome deles. Vocês derrotarão todos os seus inimigos; ninguém poderá resistir.

[[v5-7-25]]

^<<v5-7-25,25>>^ Queimem todas as imagens dos deuses desses povos. Não cobicem a prata e o ouro que estão nas imagens, nem fiquem com eles, pois isso seria uma armadilha mortal para vocês. Para o Senhor , nosso Deus, adorar ídolos é uma coisa nojenta.

[[v5-7-26]]

^<<v5-7-26,26>>^ Não levem nenhum ídolo para dentro de suas casas, pois a maldição que está sobre o ídolo estará também sobre vocês. Detestem e odeiem com todo o coração os ídolos, pois o ídolo é uma coisa amaldiçoada.

'''

xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[&#60; Capítulo Anterior] | <<v5-7-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[Próximo Capítulo &#62;]