include::./index.adoc[]

[[v5-11-0]]
=== Deuteronômio, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-11-1]]

^<<v5-11-1,1>>^ Moisés disse ao povo: — Amem o Senhor , nosso Deus, e sempre obedeçam às suas leis , aos seus mandamentos e às suas ordens.

[[v5-11-2]]

^<<v5-11-2,2>>^ Pensem hoje na grandeza de Deus e naquilo que aprenderam a respeito do seu poder e da sua força. Foram vocês, e não os seus filhos, que viram e conheceram tudo isso.

[[v5-11-3]]

^<<v5-11-3,3>>^ Lembrem dos milagres e de tudo o que o Senhor  Deus fez no Egito contra Faraó, rei do Egito, e contra toda aquela nação.

[[v5-11-4]]

^<<v5-11-4,4>>^ Vocês viram o que Deus fez com o exército dos egípcios e com os seus cavalos e carros de guerra, quando estavam perseguindo vocês. O Senhor  fez com que as águas do mar Vermelho os cobrissem e afogassem, e assim acabou com eles para sempre.

[[v5-11-5]]

^<<v5-11-5,5>>^ Vocês viram o que Deus fez no deserto, durante a viagem até este lugar,

[[v5-11-6]]

^<<v5-11-6,6>>^ e também o que fez com Datã e Abirão, filhos de Eliabe, da tribo  de Rúben. Na presença de todos a terra se abriu e engoliu os dois, junto com as suas famílias, barracas, empregados e animais.

[[v5-11-7]]

^<<v5-11-7,7>>^ E vocês mesmos viram todos os grandes milagres que o Senhor  Deus fez.

[[v5-11-8]]

^<<v5-11-8,8>>^ — Portanto, obedeçam a todas as leis  que hoje estou dando a vocês a fim de que sejam fortes e possam invadir a terra para onde estão indo e tomar posse dela.

[[v5-11-9]]

^<<v5-11-9,9>>^ Assim vocês viverão muitos anos naquela terra boa e rica que o Senhor  Deus jurou dar aos nossos antepassados e aos seus descendentes.

[[v5-11-10]]

^<<v5-11-10,10>>^ A terra que vai ser de vocês não é como o Egito, de onde saíram. Ali, depois de semearem a terra, vocês precisavam trabalhar muito para regar o chão, como se fosse uma horta.

[[v5-11-11]]

^<<v5-11-11,11>>^ Porém a terra que vocês vão possuir é uma terra de montes e vales, onde nunca falta chuva.

[[v5-11-12]]

^<<v5-11-12,12>>^ O Senhor , nosso Deus, cuida daquela terra e nunca a esquece, desde o começo até o fim do ano.

[[v5-11-13]]

^<<v5-11-13,13>>^ Portanto, se vocês obedecerem às leis que eu lhes estou dando hoje, e se amarem o Senhor , nosso Deus, e o servirem com todo o coração e com toda a alma,

[[v5-11-14]]

^<<v5-11-14,14>>^ então ele dará as chuvas no tempo certo, tanto as chuvas do outono como as da primavera. Assim haverá boas colheitas de cereais, de uvas e de azeitonas,

[[v5-11-15]]

^<<v5-11-15,15>>^ e haverá pastos para o gado. Vocês terão toda a comida que precisarem.

[[v5-11-16]]

^<<v5-11-16,16>>^ Tenham cuidado, não deixem que o seu coração seja enganado; não abandonem a Deus para adorar e servir outros deuses.

[[v5-11-17]]

^<<v5-11-17,17>>^ Se fizerem isso, Deus ficará irado  com vocês e não mandará chuvas. Aí a terra não produzirá colheitas, e em pouco tempo vocês desaparecerão da boa terra que o Senhor  está dando a vocês.

[[v5-11-18]]

^<<v5-11-18,18>>^ — Lembrem desses mandamentos e os guardem no seu coração. Amarrem essas leis nos braços e na testa, para que não as esqueçam,

[[v5-11-19]]

^<<v5-11-19,19>>^ e não deixem de ensiná-las aos seus filhos. Repitam essas leis em casa e fora de casa, quando se deitarem e quando se levantarem,

[[v5-11-20]]

^<<v5-11-20,20>>^ e as escrevam nos batentes das portas das suas casas e nos seus portões.

[[v5-11-21]]

^<<v5-11-21,21>>^ Assim vocês e os seus descendentes viverão muitos anos na terra que o Senhor  Deus jurou dar aos nossos antepassados. Enquanto o mundo existir, vocês viverão naquela terra.

[[v5-11-22]]

^<<v5-11-22,22>>^ — Portanto, obedeçam a todas as leis que eu lhes estou dando. Amem o Senhor , nosso Deus, sigam todos os seus mandamentos e fiquem ligados com ele.

[[v5-11-23]]

^<<v5-11-23,23>>^ Se fizerem isso, Deus expulsará todas essas nações, e vocês tomarão posse de uma terra que pertence a povos mais numerosos e mais poderosos do que vocês.

[[v5-11-24]]

^<<v5-11-24,24>>^ Será de vocês toda a terra por onde andarem, desde o deserto, no Sul, até os montes Líbanos, no Norte; desde o rio Eufrates, no Leste, até o mar Mediterrâneo, no Oeste.

[[v5-11-25]]

^<<v5-11-25,25>>^ Vocês nunca serão derrotados, pois o Senhor , nosso Deus, cumprirá o que prometeu e fará com que todos os povos daquela terra fiquem apavorados com vocês.

[[v5-11-26]]

^<<v5-11-26,26>>^ E Moisés disse ao povo: — Hoje vou deixar que vocês escolham se querem bênção ou maldição.

[[v5-11-27]]

^<<v5-11-27,27>>^ Vocês receberão a bênção se obedecerem às leis  do Senhor , nosso Deus, que estou dando a vocês hoje;

[[v5-11-28]]

^<<v5-11-28,28>>^ ou receberão a maldição, se não obedecerem às suas leis, mas rejeitarem os mandamentos que eu lhes estou dando hoje e adorarem outros deuses que vocês não conheciam.

[[v5-11-29]]

^<<v5-11-29,29>>^ Quando o Senhor  Deus os levar para a terra que vão possuir, vocês anunciarão a bênção no monte Gerizim e a maldição no monte Ebal.

[[v5-11-30]]

^<<v5-11-30,30>>^ (Esses dois montes ficam na terra dos cananeus, a oeste do rio Jordão, na região do vale do Jordão. Ficam perto da cidade de Gilgal, não longe das árvores sagradas de Moré.)

[[v5-11-31]]

^<<v5-11-31,31>>^ — Agora vocês vão atravessar o rio Jordão e tomar posse da terra que o Senhor , nosso Deus, lhes está dando. Portanto, depois de invadirem a terra e começarem a morar lá,

[[v5-11-32]]

^<<v5-11-32,32>>^ tenham o cuidado de obedecer a todas as leis e mandamentos que hoje eu estou dando a vocês.

'''

xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[Próximo Capítulo &#62;]