include::./index.adoc[]

[[v5-6-0]]
=== Deuteronômio, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-6-1]]

^<<v5-6-1,1>>^ Moisés disse ao povo: — São esses os mandamentos e as leis  que o Senhor , nosso Deus, mandou que eu ensinasse a vocês. Portanto, obedeçam a esses mandamentos na terra em que vão entrar e que vão possuir.

[[v5-6-2]]

^<<v5-6-2,2>>^ Temam  o Senhor , nosso Deus, vocês, os seus filhos e os seus netos, e cumpram sempre todos os mandamentos e leis que eu lhes estou dando e assim vocês viverão muitos anos.

[[v5-6-3]]

^<<v5-6-3,3>>^ Povo de Israel, tenha o cuidado de cumprir a lei de Deus. Então, conforme disse o Senhor , o Deus dos nossos antepassados, tudo correrá bem para vocês, e vocês se tornarão numerosos naquela terra boa e rica onde vão viver.

[[v5-6-4]]

^<<v5-6-4,4>>^ — Escute, povo de Israel! O Senhor , e somente o Senhor , é o nosso Deus.

[[v5-6-5]]

^<<v5-6-5,5>>^ Portanto, amem o Senhor , nosso Deus, com todo o coração, com toda a alma e com todas as forças.

[[v5-6-6]]

^<<v5-6-6,6>>^ Guardem sempre no coração as leis que eu lhes estou dando hoje

[[v5-6-7]]

^<<v5-6-7,7>>^ e não deixem de ensiná-las aos seus filhos. Repitam essas leis em casa e fora de casa, quando se deitarem e quando se levantarem.

[[v5-6-8]]

^<<v5-6-8,8>>^ Amarrem essas leis nos braços e na testa, para não as esquecerem;

[[v5-6-9]]

^<<v5-6-9,9>>^ e as escrevam nos batentes das portas das suas casas e nos seus portões.

[[v5-6-10]]

^<<v5-6-10,10>>^ Moisés continuou: — O Senhor , nosso Deus, jurou aos nossos antepassados Abraão, Isaque e Jacó que daria essa terra a vocês. É uma terra onde há grandes e ricas cidades, que vocês não construíram;

[[v5-6-11]]

^<<v5-6-11,11>>^ há casas cheias de objetos de valor, que vocês não ajuntaram; poços de água, que vocês não cavaram; e plantações de uvas e de azeitonas, que vocês não plantaram. Quando o Senhor  os levar para essa terra, e vocês tiverem comida à vontade,

[[v5-6-12]]

^<<v5-6-12,12>>^ tenham o cuidado de não esquecerem Deus, que os tirou do Egito, onde vocês eram escravos.

[[v5-6-13]]

^<<v5-6-13,13>>^ Temam  o Senhor , seu Deus, sirvam somente a ele e jurem só pelo nome dele.

[[v5-6-14]]

^<<v5-6-14,14>>^ Não adorem outros deuses, os deuses dos povos vizinhos.

[[v5-6-15]]

^<<v5-6-15,15>>^ Pois o Senhor , nosso Deus, está com vocês e ele não tolera outros deuses. Se vocês os adorarem, o Senhor  ficará irado  com vocês e destruirá vocês completamente.

[[v5-6-16]]

^<<v5-6-16,16>>^ — Não ponham à prova o Senhor , seu Deus, como o puseram à prova em Massá.

[[v5-6-17]]

^<<v5-6-17,17>>^ Obedeçam cuidadosamente a todos os mandamentos e leis  que ele lhes deu.

[[v5-6-18]]

^<<v5-6-18,18>>^ Façam aquilo que Deus acha bom e certo, e assim tudo correrá bem para vocês, e vocês entrarão e tomarão posse da boa terra que o Senhor  jurou dar aos nossos antepassados.

[[v5-6-19]]

^<<v5-6-19,19>>^ E, conforme prometeu, ele expulsará todos os inimigos que vocês enfrentarem.

[[v5-6-20]]

^<<v5-6-20,20>>^ — No futuro os seus filhos perguntarão: "Por que foi que o Senhor , nosso Deus, nos deu estes mandamentos e estas leis?"

[[v5-6-21]]

^<<v5-6-21,21>>^ Aí vocês responderão: "Nós éramos escravos do rei do Egito, mas o Senhor , com o seu grande poder, nos tirou de lá.

[[v5-6-22]]

^<<v5-6-22,22>>^ Nós vimos com os nossos próprios olhos os grandes milagres e as coisas espantosas que Deus fez contra os egípcios e contra o seu rei e toda a gente do seu palácio.

[[v5-6-23]]

^<<v5-6-23,23>>^ E Deus nos tirou do Egito para nos trazer aqui e nos dar esta terra, como havia jurado aos nossos antepassados.

[[v5-6-24]]

^<<v5-6-24,24>>^ Ele nos mandou obedecer a todas estas leis e sempre temer o Senhor , nosso Deus. Se fizermos isso, ele nos guardará de todo mal, como tem feito até hoje, e tudo sempre correrá bem para nós.

[[v5-6-25]]

^<<v5-6-25,25>>^ E, se tivermos o cuidado de obedecer a todas estas leis que o Senhor , nosso Deus, nos deu, a nossa vida agradará a ele."

'''

xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[&#60; Capítulo Anterior] | <<v5-6-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[Próximo Capítulo &#62;]