include::./index.adoc[]

[[v5-14-0]]
=== Deuteronômio, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-14-1]]

^<<v5-14-1,1>>^ Moisés disse ao povo: — Vocês são filhos do Senhor , nosso Deus. Portanto, quando chorarem a morte de alguém, não se cortem, nem rapem a cabeça, como os outros povos fazem.

[[v5-14-2]]

^<<v5-14-2,2>>^ Pois vocês são o povo escolhido pelo Senhor , nosso Deus; entre todos os povos da terra ele os escolheu para serem somente dele.

[[v5-14-3]]

^<<v5-14-3,3>>^ — Não comam nada que seja impuro .

[[v5-14-4]]

^<<v5-14-4,4>>^ Vocês podem comer a carne dos seguintes animais: vacas, carneiros, cabritos,

[[v5-14-5]]

^<<v5-14-5,5>>^ veados, gazelas , corços , cabritos selvagens, antílopes, carneiros selvagens e gamos.

[[v5-14-6]]

^<<v5-14-6,6>>^ Todos esses animais têm o casco dividido em dois, e ruminam, e podem ser comidos.

[[v5-14-7]]

^<<v5-14-7,7>>^ Mas nenhum animal deve ser comido, a não ser que tenha o casco dividido e que rumine. Portanto, não comam camelos, lebres ou coelhos selvagens, pois ruminam, mas não têm o casco dividido. Para vocês esses animais são impuros.

[[v5-14-8]]

^<<v5-14-8,8>>^ Não comam carne de porco. Para vocês os porcos são impuros porque têm o casco dividido, mas não ruminam. Não comam nenhum desses animais, nem toquem neles quando estiverem mortos.

[[v5-14-9]]

^<<v5-14-9,9>>^ — Vocês podem comer qualquer peixe que tenha barbatanas e escamas,

[[v5-14-10]]

^<<v5-14-10,10>>^ mas não podem comer peixes que não tenham barbatanas nem escamas. Para vocês esses peixes são impuros.

[[v5-14-11]]

^<<v5-14-11,11>>^ — Vocês podem comer qualquer ave pura ,

[[v5-14-12]]

^<<v5-14-12,12>>^ porém não comam as seguintes aves : águias, urubus, águias marinhas,

[[v5-14-13]]

^<<v5-14-13,13>>^ açores, falcões,

[[v5-14-14]]

^<<v5-14-14,14>>^ corvos,

[[v5-14-15]]

^<<v5-14-15,15>>^ avestruzes, corujas, gaivotas, gaviões,

[[v5-14-16]]

^<<v5-14-16,16>>^ mochos, íbis, gralhas,

[[v5-14-17]]

^<<v5-14-17,17>>^ pelicanos, abutres, corvos marinhos,

[[v5-14-18]]

^<<v5-14-18,18>>^ cegonhas, garças e poupas; e também morcegos.

[[v5-14-19]]

^<<v5-14-19,19>>^ — Todos os insetos que voam são impuros; vocês não podem comê-los.

[[v5-14-20]]

^<<v5-14-20,20>>^ Mas podem comer todos os insetos puros.

[[v5-14-21]]

^<<v5-14-21,21>>^ — Não comam qualquer animal que tenha tido morte natural. Vocês podem dar o animal aos estrangeiros que moram nas cidades de vocês ou podem vendê-lo a outros estrangeiros. Mas vocês não o podem comer, pois são o povo escolhido pelo Senhor , nosso Deus. — Não cozinhem um cabrito ou um carneirinho no leite da sua própria mãe .

[[v5-14-22]]

^<<v5-14-22,22>>^ — Todos os anos juntem uma décima parte de todas as colheitas

[[v5-14-23]]

^<<v5-14-23,23>>^ e levem até o lugar que o Senhor , nosso Deus, tiver escolhido para nele ser adorado. Ali, na presença do Senhor , nosso Deus, comam aquela décima parte dos cereais, do vinho e do azeite e também a primeira cria das vacas e das ovelhas. Façam isso para aprender a temer a Deus  para sempre.

[[v5-14-24]]

^<<v5-14-24,24>>^ Mas, se o lugar de adoração ficar muito longe, e for impossível levar até lá a décima parte das colheitas com que Deus os abençoou,

[[v5-14-25]]

^<<v5-14-25,25>>^ então façam isto: vendam aquela parte das colheitas, levem o dinheiro até o lugar de adoração que o Senhor  tiver escolhido

[[v5-14-26]]

^<<v5-14-26,26>>^ e ali comprem tudo o que quiserem comer: carne de vaca ou de carneiro, vinho, cerveja ou qualquer outra coisa que desejarem. E ali, na presença do Senhor , nosso Deus, vocês e as suas famílias comam essas coisas e se divirtam à vontade.

[[v5-14-27]]

^<<v5-14-27,27>>^ — Porém não esqueçam os levitas  que moram nas cidades de vocês. Eles não receberão terras em Canaã, como as outras tribos .

[[v5-14-28]]

^<<v5-14-28,28>>^ De três em três anos juntem a décima parte das colheitas daquele ano e guardem nas cidades onde vocês moram.

[[v5-14-29]]

^<<v5-14-29,29>>^ Essa comida é para os levitas, pois eles não têm terras próprias; é também para os estrangeiros, os órfãos e as viúvas que moram nas cidades de vocês. Assim todos eles terão toda a comida que precisarem. Façam isso para que o Senhor , nosso Deus, abençoe todo o trabalho de vocês.

'''

xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[&#60; Capítulo Anterior] | <<v5-14-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[Próximo Capítulo &#62;]