include::./index.adoc[]

[[v5-2-0]]
=== Deuteronômio, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-2-1]]

^<<v5-2-1,1>>^ Moisés disse ao povo: — Então continuamos a viagem pelo deserto na direção do golfo de Ácaba, conforme o Senhor  Deus me havia ordenado. E por muito tempo caminhamos sem rumo pela região montanhosa de Edom.

[[v5-2-2]]

^<<v5-2-2,2>>^ Então o Senhor  me disse:

[[v5-2-3]]

^<<v5-2-3,3>>^ "Já faz muito tempo que vocês andam por aí sem rumo. Agora vão na direção do norte."

[[v5-2-4]]

^<<v5-2-4,4>>^ E Deus ordenou que eu lhes dissesse: "Vocês vão passar pelo país de Edom, que é dos seus parentes , os descendentes de Esaú. Eles ficarão com medo de vocês, mas tomem cuidado

[[v5-2-5]]

^<<v5-2-5,5>>^ para não provocarem uma luta com eles. Eu não darei a vocês nem mesmo um pedacinho da terra deles, pois foi aos descendentes de Esaú que eu dei o território de Edom.

[[v5-2-6]]

^<<v5-2-6,6>>^ Vocês poderão comprar deles a comida e a água que precisarem."

[[v5-2-7]]

^<<v5-2-7,7>>^ — Lembrem que o Senhor , nosso Deus, abençoou tudo o que vocês fizeram. Ele não esqueceu vocês durante os quarenta anos em que caminharam por esse enorme deserto. Ele sempre cuidou de vocês, dando-lhes tudo o que precisavam.

[[v5-2-8]]

^<<v5-2-8,8>>^ — Assim rodeamos o país de Edom, deixando o caminho que vai de Elate e Eziom-Geber até o mar Morto e seguindo o caminho que vai até o deserto de Moabe.

[[v5-2-9]]

^<<v5-2-9,9>>^ E o Senhor  Deus me disse: "Não ataque os moabitas, que são descendentes de Ló, nem entre em luta com eles. Eu dei a eles a cidade de Ar e não darei a você nenhuma parte do país deles."

[[v5-2-10]]

^<<v5-2-10,10>>^ (Antigamente uma raça numerosa de gigantes fortes, chamados emins, vivia em Ar. Eles eram tão altos como os anaquins , outra raça de gigantes.

[[v5-2-11]]

^<<v5-2-11,11>>^ Tanto os anaquins como os emins eram conhecidos como refains ; mas os moabitas os chamavam de emins.

[[v5-2-12]]

^<<v5-2-12,12>>^ Naquele tempo os horeus viviam em Edom, mas os descendentes de Esaú os expulsaram dali, acabaram com eles e ficaram morando no seu território. Os descendentes de Esaú fizeram a mesma coisa que os israelitas fizeram mais tarde, quando estes tomaram posse da terra que o Senhor  lhes tinha dado.)

[[v5-2-13]]

^<<v5-2-13,13>>^ — Depois atravessamos o riacho de Zerede, conforme Deus havia mandado.

[[v5-2-14]]

^<<v5-2-14,14>>^ Isso foi trinta e oito anos depois de termos saído de Cades-Barneia. Durante esses anos aconteceu aquilo que o Senhor  nos tinha dito: morreram todos os homens daquela geração  que tinham idade para ir à guerra.

[[v5-2-15]]

^<<v5-2-15,15>>^ O Senhor  ficou contra eles e os foi matando, até que não sobrou mais nenhum deles no acampamento dos israelitas.

[[v5-2-16]]

^<<v5-2-16,16>>^ — Depois da morte de todos aqueles homens,

[[v5-2-17]]

^<<v5-2-17,17>>^ o Senhor  Deus me disse:

[[v5-2-18]]

^<<v5-2-18,18>>^ "Passe hoje pela cidade de Ar, na fronteira com Moabe.

[[v5-2-19]]

^<<v5-2-19,19>>^ Quando chegar à terra dos amonitas, que são descendentes de Ló, não os ataque, nem entre em luta com eles. Eu entreguei a eles a terra de Amom e não darei a você nenhuma parte do país deles."

[[v5-2-20]]

^<<v5-2-20,20>>^ (Essa região é conhecida também como a terra dos refains, uma raça de gigantes que antigamente moravam ali; os amonitas os chamavam de zanzumins.

[[v5-2-21]]

^<<v5-2-21,21>>^ Havia muitos deles, e eram altos e fortes, como os anaquins. Deus destruiu os zanzumins, e os amonitas ocuparam a região e ficaram morando ali.

[[v5-2-22]]

^<<v5-2-22,22>>^ Deus havia feito a mesma coisa em favor dos edomitas, que são descendentes de Esaú: ele acabou com os horeus, e os edomitas ocuparam a terra deles e ali moram até hoje .

[[v5-2-23]]

^<<v5-2-23,23>>^ Os cretenses fizeram a mesma coisa: eles saíram da ilha de Creta, invadiram a terra dos avins, no litoral do mar Mediterrâneo, e foram na direção do sul até a cidade de Gaza. Os cretenses acabaram com os avins e ficaram morando nas cidades deles.)

[[v5-2-24]]

^<<v5-2-24,24>>^ — Depois que atravessamos o país de Moabe, Deus nos disse: "Continuem avançando e atravessem o rio Arnom, pois eu deixarei que vocês derrotem Seom, o rei dos amorreus, que mora na cidade de Hesbom. Lutem contra Seom e tomem posse da terra dele."

[[v5-2-25]]

^<<v5-2-25,25>>^ E Deus me disse: "De hoje em diante eu vou fazer com que todos os povos do mundo tenham medo de você. Você será famoso, e, quando ouvirem falar a seu respeito, todos ficarão tão assustados, que tremerão de medo."

[[v5-2-26]]

^<<v5-2-26,26>>^ E Moisés continuou, dizendo: — Depois, quando estávamos no deserto de Quedemote, mandei que alguns mensageiros levassem ao rei Seom, que morava na cidade de Hesbom, um tratado de paz, com as seguintes condições:

[[v5-2-27]]

^<<v5-2-27,27>>^ "Pedimos licença para passar pelo seu país. Prometemos andar somente pela estrada, sem sair dela;

[[v5-2-28]]

^<<v5-2-28,28>>^ e também pagaremos pela comida e pela bebida que precisarmos. A única coisa que queremos é licença para passarmos pelo seu país

[[v5-2-29]]

^<<v5-2-29,29>>^ até chegarmos ao rio Jordão. Então atravessaremos o rio para entrar na terra que o Senhor , nosso Deus, nos está dando. Os descendentes de Esaú, que moram em Edom, e os moabitas, que moram em Ar, já nos deram licença para passarmos pelos países deles."

[[v5-2-30]]

^<<v5-2-30,30>>^ Mas o rei Seom não deixou, pois o Senhor , nosso Deus, fez com que Seom ficasse teimoso e rebelde. Deus fez isso para que nós pudéssemos derrotar o rei Seom e conquistar a terra dele, que é nossa até hoje.

[[v5-2-31]]

^<<v5-2-31,31>>^ — Então o Senhor  Deus me disse: "Veja! Eu vou deixar que você derrote Seom; ataque-o imediatamente e tome posse da terra dele."

[[v5-2-32]]

^<<v5-2-32,32>>^ Seom saiu com o seu exército para lutar contra nós na cidade de Jasa.

[[v5-2-33]]

^<<v5-2-33,33>>^ O Senhor , nosso Deus, nos deu a vitória, e nós derrotamos Seom, os seus filhos e todo o seu exército.

[[v5-2-34]]

^<<v5-2-34,34>>^ Além disso conquistamos e destruímos todas as suas cidades e matamos todos os homens, mulheres e crianças. Não escapou ninguém.

[[v5-2-35]]

^<<v5-2-35,35>>^ Mas ficamos com o gado e com os objetos de valor que encontramos nas cidades.

[[v5-2-36]]

^<<v5-2-36,36>>^ O Senhor , nosso Deus, deixou que conquistássemos todas as cidades, desde Aroer, que fica perto do vale do rio Arnom, e desde a cidade que está no vale, até a região de Gileade. Nós conquistamos todas as cidades, mesmo as que tinham muralhas altas e fortes.

[[v5-2-37]]

^<<v5-2-37,37>>^ Não invadimos a terra dos amonitas, nem as cidades que ficam nas margens do rio Jaboque, nem as que ficam na região montanhosa, nem os outros lugares que o Senhor , nosso Deus, havia proibido.

'''

xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[&#60; Capítulo Anterior] | <<v5-2-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[Próximo Capítulo &#62;]