include::./index.adoc[]

[[v5-19-0]]
=== Deuteronômio, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-19-1]]

^<<v5-19-1,1>>^ Moisés disse ao povo: — O Senhor , nosso Deus, vai acabar com os povos que moram na terra que ele vai dar a vocês. Vocês os expulsarão e ficarão morando nas cidades e nas casas deles.

[[v5-19-2]]

^<<v5-19-2,2>>^ Então dividam o país em três partes e em cada uma delas escolham uma cidade para onde seja fácil fugir. E qualquer homem que tenha matado alguém poderá ir para uma daquelas cidades, e ali ninguém poderá matá-lo.

[[v5-19-3]]

^<<v5-19-3,3>>^ Então dividam o país em três partes e em cada uma delas escolham uma cidade para onde seja fácil fugir. E qualquer homem que tenha matado alguém poderá ir para uma daquelas cidades, e ali ninguém poderá matá-lo.

[[v5-19-4]]

^<<v5-19-4,4>>^ — Se um homem, sem querer ou por engano, matar alguém que não era seu inimigo, poderá fugir para uma dessas cidades, onde ninguém poderá matá-lo.

[[v5-19-5]]

^<<v5-19-5,5>>^ Por exemplo, dois companheiros entram no mato para cortar lenha. Um deles, ao cortar uma árvore, dá um golpe tão forte com o machado, que o ferro salta do cabo e bate no companheiro, e ele morre. Então aquele homem irá para uma dessas cidades, e ali ninguém poderá matá-lo.

[[v5-19-6]]

^<<v5-19-6,6>>^ Ora, se houvesse somente uma cidade para fugitivos, ela poderia estar tão longe, que o parente encarregado de vingar aquela morte teria tempo de pegar aquele que matou o companheiro. E o parente estaria tão furioso, que mataria o homem, embora este não merecesse a morte, pois foi sem querer que matou o companheiro.

[[v5-19-7]]

^<<v5-19-7,7>>^ Portanto, eu ordeno que escolham três cidades para fugitivos.

[[v5-19-8]]

^<<v5-19-8,8>>^ — Se o Senhor , nosso Deus, lhes der mais terras, conforme jurou aos nossos antepassados, e der a vocês toda a terra que prometeu a eles,

[[v5-19-9]]

^<<v5-19-9,9>>^ então escolham mais três cidades para fugitivos. (Deus lhes dará mais terras se vocês obedecerem a todos os mandamentos que estou dando a vocês hoje, se amarem o Senhor , nosso Deus, com todo o coração e se nunca se desviarem dos caminhos que ele mostra.)

[[v5-19-10]]

^<<v5-19-10,10>>^ Se escolherem mais essas cidades para fugitivos, então não morrerá nenhum homem inocente na terra que o Senhor  Deus lhes está dando, e vocês não serão culpados da morte de homens inocentes.

[[v5-19-11]]

^<<v5-19-11,11>>^ — Mas pode acontecer que um homem tenha ódio de outro. Ele fica de tocaia e ataca e mata o inimigo. Aí ele vai para uma dessas cidades a fim de não ser morto.

[[v5-19-12]]

^<<v5-19-12,12>>^ Nesse caso, os líderes da cidade em que ele mora mandarão buscá-lo e o entregarão ao parente encarregado de vingar aquela morte, e o criminoso será morto.

[[v5-19-13]]

^<<v5-19-13,13>>^ Não tenham dó nem piedade. Tirem do meio de Israel o criminoso a fim de que tudo corra bem para vocês.

[[v5-19-14]]

^<<v5-19-14,14>>^ — Não mudem de lugar os marcos de divisa do terreno do vizinho. Elas foram colocadas há muito tempo na terra que o Senhor , nosso Deus, está dando a vocês.

[[v5-19-15]]

^<<v5-19-15,15>>^ — Quando alguém for acusado de ter cometido um crime, seja qual for, uma testemunha não basta; é preciso ter pelo menos duas testemunhas para confirmar uma acusação.

[[v5-19-16]]

^<<v5-19-16,16>>^ Se uma testemunha falsa acusar alguém de ter cometido um crime,

[[v5-19-17]]

^<<v5-19-17,17>>^ o acusador e o acusado irão ao lugar de adoração e ali apresentarão o caso aos sacerdotes e aos juízes que estiverem julgando naquele tempo.

[[v5-19-18]]

^<<v5-19-18,18>>^ Estes examinarão o caso com todo o cuidado, e, se for provado que o homem deu testemunho falso contra o seu patrício israelita,

[[v5-19-19]]

^<<v5-19-19,19>>^ será condenado, e o castigo dele será o mesmo que ele queria para o outro. Assim vocês tirarão o mal do meio do povo.

[[v5-19-20]]

^<<v5-19-20,20>>^ Todo o povo de Israel saberá do que aconteceu; todos ficarão com medo, e ninguém se atreverá a praticar uma ação tão má no meio do povo.

'''

xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[&#60; Capítulo Anterior] | <<v5-19-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[Próximo Capítulo &#62;]