include::./index.adoc[]

[[v5-15-0]]
=== Deuteronômio, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-15-1]]

^<<v5-15-1,1>>^ Moisés disse ao povo: — De sete em sete anos todas as dívidas serão perdoadas.

[[v5-15-2]]

^<<v5-15-2,2>>^ Isso será feito assim: quem tiver emprestado dinheiro a outro israelita perdoará a dívida. Ele não exigirá pagamento, pois o Senhor  Deus declara que a dívida foi perdoada.

[[v5-15-3]]

^<<v5-15-3,3>>^ Vocês podem exigir que os estrangeiros paguem, mas devem perdoar as dívidas dos seus patrícios israelitas.

[[v5-15-4]]

^<<v5-15-4,4>>^ — O Senhor , nosso Deus, os abençoará ricamente na terra que lhes vai dar. Portanto, não haverá nenhum israelita pobre,

[[v5-15-5]]

^<<v5-15-5,5>>^ se todos derem atenção ao que o Senhor  ordena e obedecerem a todos os mandamentos que hoje eu estou dando a vocês.

[[v5-15-6]]

^<<v5-15-6,6>>^ Conforme prometeu, o Senhor  Deus os abençoará: vocês emprestarão a muitos povos, mas não tomarão emprestado de ninguém; terão domínio sobre muitos povos, mas não serão dominados por ninguém.

[[v5-15-7]]

^<<v5-15-7,7>>^ — Se houver um israelita pobre em qualquer cidade da terra que o Senhor , nosso Deus, vai dar a vocês, tenham pena dele e o ajudem.

[[v5-15-8]]

^<<v5-15-8,8>>^ Sejam generosos e emprestem todo o dinheiro que ele precisar.

[[v5-15-9]]

^<<v5-15-9,9>>^ Se isso acontecer quando estiver perto o sétimo ano, o ano em que as dívidas são perdoadas, talvez você pense em não ajudar o necessitado. Afaste esse mau pensamento e ajude o seu patrício israelita; se não, ele gritará a Deus contra você, e você será culpado de pecado.

[[v5-15-10]]

^<<v5-15-10,10>>^ Não dê com tristeza no coração, mas seja generoso com ele; assim o Senhor , nosso Deus, abençoará tudo o que você planejar e tudo o que fizer.

[[v5-15-11]]

^<<v5-15-11,11>>^ — Sempre haverá pobres e necessitados no meio do povo, e por isso eu ordeno que vocês sejam generosos com todos eles.

[[v5-15-12]]

^<<v5-15-12,12>>^ — Se um israelita, seja homem ou mulher, for vendido a você como escravo, ele será o seu escravo seis anos; no sétimo ano você lhe dará a liberdade.

[[v5-15-13]]

^<<v5-15-13,13>>^ E, quando ele for embora, não o deixe ir sem lhe dar alguma coisa.

[[v5-15-14]]

^<<v5-15-14,14>>^ Seja generoso com as bênçãos que o Senhor  Deus derramou sobre você: dê ao escravo ovelhas, cereais e vinho.

[[v5-15-15]]

^<<v5-15-15,15>>^ Lembre que você foi escravo no Egito e que o Senhor , nosso Deus, o tirou de lá. É por isso que eu estou dando essa ordem a você hoje.

[[v5-15-16]]

^<<v5-15-16,16>>^ — Mas talvez o escravo goste tanto de você e da sua família e se sinta tão bem na sua casa, que não queira ir embora.

[[v5-15-17]]

^<<v5-15-17,17>>^ Nesse caso você deve levá-lo para a porta da casa e furar a orelha dele com um furador. Então ele será seu escravo por toda a vida. E faça o mesmo com a escrava que quiser ficar.

[[v5-15-18]]

^<<v5-15-18,18>>^ Não fique aborrecido quando você precisar dar a liberdade ao seu escravo. Afinal de contas, ele foi seu escravo seis anos, ganhando metade do que se paga a um empregado. Faça o que eu mando, e o Senhor  Deus abençoará tudo o que você fizer.

[[v5-15-19]]

^<<v5-15-19,19>>^ — A primeira cria das vacas e das ovelhas, se for macho, pertence ao Senhor , nosso Deus. Portanto, não usem no trabalho essas crias das vacas e não cortem a lã dessas crias das ovelhas.

[[v5-15-20]]

^<<v5-15-20,20>>^ Todos os anos levem esses animais para o lugar de adoração escolhido por Deus, o Senhor , e ali, na presença de Deus, vocês e as suas famílias comam a carne deles.

[[v5-15-21]]

^<<v5-15-21,21>>^ Porém, se um desses animais tiver algum defeito, se for cego, ou aleijado, ou tiver outro defeito grave, não poderá ser oferecido em sacrifício  ao Senhor .

[[v5-15-22]]

^<<v5-15-22,22>>^ A carne desse animal deverá ser comida em casa; todos vocês, tanto os que estão puros  como os que estão impuros , poderão comer a carne desses animais defeituosos como se comessem carne de gazela  ou de veado .

[[v5-15-23]]

^<<v5-15-23,23>>^ Porém não comam o sangue; despejem o sangue no chão, como se fosse água.

'''

xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[Próximo Capítulo &#62;]