include::./index.adoc[]

[[v5-26-0]]
=== Deuteronômio, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-26-1]]

^<<v5-26-1,1>>^ Moisés disse ao povo: — Vocês vão tomar posse da terra que o Senhor , nosso Deus, está dando a vocês. Depois de morarem lá algum tempo,

[[v5-26-2]]

^<<v5-26-2,2>>^ cada um deve pegar a primeira parte de todas as colheitas produzidas pela terra que o Senhor  Deus lhe deu, deve colocá-la num cesto e levar para o lugar que Deus tiver escolhido para nele ser adorado.

[[v5-26-3]]

^<<v5-26-3,3>>^ Vá falar com o sacerdote que estiver servindo naquele dia e diga: "Declaro hoje que estou morando na terra que o Senhor , nosso Deus, prometeu dar aos nossos antepassados."

[[v5-26-4]]

^<<v5-26-4,4>>^ Aí o sacerdote pegará o cesto e o colocará na frente do altar do Senhor , nosso Deus.

[[v5-26-5]]

^<<v5-26-5,5>>^ Então, na presença do Senhor , você fará esta declaração: "O meu antepassado foi um arameu que não tinha lugar certo onde morar. Ele foi com a família para o Egito, e ali eles moraram como estrangeiros. Quando chegaram lá, eram poucos, mas aumentaram em número e se tornaram um povo grande e forte.

[[v5-26-6]]

^<<v5-26-6,6>>^ Os egípcios nos maltrataram e nos obrigaram a fazer trabalhos pesados.

[[v5-26-7]]

^<<v5-26-7,7>>^ Então oramos, pedindo socorro ao Senhor , o Deus dos nossos antepassados. Ele nos atendeu e viu a nossa aflição, a nossa miséria e como éramos perseguidos.

[[v5-26-8]]

^<<v5-26-8,8>>^ Com a sua força e com o seu poder ele fez milagres, maravilhas e coisas espantosas, e nos tirou do Egito,

[[v5-26-9]]

^<<v5-26-9,9>>^ e nos trouxe até esta terra que nos deu, uma terra boa e rica.

[[v5-26-10]]

^<<v5-26-10,10>>^ E agora, ó Senhor  Deus, eu te ofereço a primeira parte das colheitas da terra que me deste." — Depois, coloque a oferta diante do Senhor , nosso Deus, e ajoelhe-se na sua presença.

[[v5-26-11]]

^<<v5-26-11,11>>^ Fique alegre por causa de todas as coisas boas que o Senhor  deu a você e à sua família e faça uma festa com os levitas  e com os estrangeiros que moram onde você vive.

[[v5-26-12]]

^<<v5-26-12,12>>^ — De três em três anos junte a décima parte das colheitas daquele ano e dê aos levitas , aos estrangeiros, aos órfãos e às viúvas que moram na sua cidade, para que tenham toda a comida que precisarem.

[[v5-26-13]]

^<<v5-26-13,13>>^ Depois, na presença do Senhor , nosso Deus, você dirá o seguinte: "Entreguei aos levitas, aos estrangeiros, aos órfãos e às viúvas a parte das minhas colheitas que pertence a ti. Obedeci a todos os teus mandamentos; não deixei de cumprir nenhum deles e fiz tudo o que mandaste a respeito do dízimo .

[[v5-26-14]]

^<<v5-26-14,14>>^ Não comi nenhuma porção do dízimo quando estava de luto, não levei nenhuma parte para fora da cidade quando estava impuro , nem dei nenhuma parte como oferta pelos mortos. Fiz tudo o que mandaste, ó Senhor , meu Deus, e obedeci à tua ordem.

[[v5-26-15]]

^<<v5-26-15,15>>^ Olha do céu, onde moras, ó Deus, e abençoa-nos, o teu povo de Israel, e abençoa esta terra boa e rica que nos deste, conforme prometeste aos nossos antepassados."

[[v5-26-16]]

^<<v5-26-16,16>>^ Moisés disse ao povo: — Hoje o Senhor , nosso Deus, está mandando que vocês obedeçam a esses mandamentos; portanto, cumpram as suas leis  com todo o coração e com toda a alma.

[[v5-26-17]]

^<<v5-26-17,17>>^ Hoje vocês afirmaram que o Senhor  é o seu Deus e prometeram andar sempre nos caminhos dele, obedecendo às suas leis e aos seus mandamentos e fazendo tudo o que ele mandar.

[[v5-26-18]]

^<<v5-26-18,18>>^ E hoje o Senhor  Deus declara que, conforme prometeu, vocês são o povo que é somente dele, e ele manda que vocês obedeçam a todos os seus mandamentos.

[[v5-26-19]]

^<<v5-26-19,19>>^ Assim ele vai abençoá-los, dando-lhes mais fama, glória  e honra do que a qualquer outro povo que ele criou. E, conforme ele disse, vocês serão o seu povo escolhido, o povo que é somente dele.

'''

xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[&#60; Capítulo Anterior] | <<v5-26-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[Próximo Capítulo &#62;]