include::./index.adoc[]

[[v5-12-0]]
=== Deuteronômio, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-12-1]]

^<<v5-12-1,1>>^ Moisés disse ao povo: — São estas as leis  e os mandamentos a que vocês deverão obedecer todo o tempo que viverem na terra que o Senhor , o Deus dos nossos antepassados, vai dar a vocês.

[[v5-12-2]]

^<<v5-12-2,2>>^ Depois de expulsarem os povos daquela terra, arrasem completamente todos os lugares onde eles adoram os seus deuses, tanto nas montanhas como nas colinas e debaixo das árvores que dão sombra.

[[v5-12-3]]

^<<v5-12-3,3>>^ Derrubem os altares, quebrem as colunas do deus Baal , cortem os postes da deusa Aserá  e queimem todas as imagens, para que ninguém lembre mais dos deuses daqueles povos.

[[v5-12-4]]

^<<v5-12-4,4>>^ — Não adorem o Senhor , nosso Deus, do jeito que aqueles povos adoram os seus deuses.

[[v5-12-5]]

^<<v5-12-5,5>>^ No território de uma das tribos , o Senhor  Deus escolherá o lugar onde vai morar e onde o povo vai adorá-lo. Vocês irão lá

[[v5-12-6]]

^<<v5-12-6,6>>^ e ali oferecerão em sacrifício  os animais que são queimados no altar e também apresentarão outros sacrifícios. Para esse lugar trarão a décima parte dos animais e das colheitas, as contribuições, as ofertas prometidas, as ofertas feitas por vontade própria e as primeiras crias das vacas e das ovelhas.

[[v5-12-7]]

^<<v5-12-7,7>>^ Ali, na presença do Senhor , nosso Deus, vocês e as suas famílias comerão da carne dos sacrifícios e ficarão alegres porque Deus abençoou todo o trabalho de vocês.

[[v5-12-8]]

^<<v5-12-8,8>>^ — Até agora cada um tem feito tudo como quer; mas, quando chegarem lá, não vai ser assim.

[[v5-12-9]]

^<<v5-12-9,9>>^ Vocês ainda não entraram na terra que o Senhor , nosso Deus, lhes está dando, a terra onde vão viver em paz.

[[v5-12-10]]

^<<v5-12-10,10>>^ Quando atravessarem o rio Jordão e começarem a morar na terra que o Senhor  vai dar a vocês, ele os protegerá de todos os inimigos, e vocês viverão em paz.

[[v5-12-11]]

^<<v5-12-11,11>>^ Então o nosso Deus escolherá o lugar onde ele será adorado, e para lá vocês levarão tudo o que estou ordenando, isto é, os animais que são queimados no altar e os outros sacrifícios, a décima parte dos animais e das colheitas, as contribuições e todas as outras ofertas prometidas a Deus.

[[v5-12-12]]

^<<v5-12-12,12>>^ Na presença do Senhor , nosso Deus, todos se alegrarão: vocês, os seus filhos e as suas filhas, os seus escravos e as suas escravas e os levitas  que estiverem morando nas cidades onde vocês vivem. Eles não receberão terras em Canaã, como as outras tribos vão receber.

[[v5-12-13]]

^<<v5-12-13,13>>^ — Portanto, não ofereçam sacrifícios em qualquer lugar que quiserem,

[[v5-12-14]]

^<<v5-12-14,14>>^ mas somente no lugar que o Senhor  Deus escolher no território de uma das tribos. Ali vocês oferecerão sacrifícios e farão todas as outras coisas que tenho ordenado.

[[v5-12-15]]

^<<v5-12-15,15>>^ Porém, quando vocês quiserem comer carne, poderão comer os seus animais em qualquer lugar onde vocês estiverem morando. Vocês poderão comer tantos animais quantos o Senhor , nosso Deus, lhes der. Todos vocês, quer estejam puros  ou impuros , poderão comê-los, como comeriam carne de gazela  ou de veado .

[[v5-12-16]]

^<<v5-12-16,16>>^ Mas não comam o sangue dos animais; o sangue deve ser despejado no chão, como se fosse água.

[[v5-12-17]]

^<<v5-12-17,17>>^ — Os sacrifícios oferecidos a Deus não podem ser comidos nos lugares onde vocês vão morar. A décima parte dos cereais, do vinho e do azeite; as primeiras crias das vacas e das ovelhas; as ofertas prometidas; as ofertas feitas por vontade própria e qualquer outra oferta

[[v5-12-18]]

^<<v5-12-18,18>>^ todos esses sacrifícios e ofertas vocês poderão comer somente no lugar que o Senhor , nosso Deus, escolher. Ali na presença de Deus todos comerão da carne dos sacrifícios: vocês, os seus filhos e as suas filhas, os seus escravos e as suas escravas e os levitas que estiverem morando nas cidades onde vocês vivem. E todos se alegrarão porque Deus abençoou todo o trabalho de vocês.

[[v5-12-19]]

^<<v5-12-19,19>>^ Lembrem de cuidar dos levitas durante todo o tempo em que vocês viverem naquela terra.

[[v5-12-20]]

^<<v5-12-20,20>>^ — O Senhor , nosso Deus, cumprirá a sua promessa e aumentará o território de vocês. Então poderão comer carne sempre que quiserem.

[[v5-12-21]]

^<<v5-12-21,21>>^ E, se estiverem longe do lugar que o Senhor  tiver escolhido para nele ser adorado, vocês poderão fazer o que eu ordenei: ali onde estiverem morando, poderão matar vacas e ovelhas que Deus lhes tiver dado e comer carne à vontade.

[[v5-12-22]]

^<<v5-12-22,22>>^ Todas as pessoas, tanto as que estão puras como as que estão impuras, poderão comer carne desses animais, como comeriam carne de gazela ou de veado.

[[v5-12-23]]

^<<v5-12-23,23>>^ Mas não comam o sangue: a vida está no sangue, e vocês não devem comer carne com vida.

[[v5-12-24]]

^<<v5-12-24,24>>^ Não comam sangue; despejem o sangue no chão, como se fosse água.

[[v5-12-25]]

^<<v5-12-25,25>>^ Obedeçam a essa lei e façam o que o Senhor  Deus acha certo, e assim vocês e os seus descendentes serão felizes.

[[v5-12-26]]

^<<v5-12-26,26>>^ As coisas dedicadas ao Senhor  Deus e as ofertas prometidas devem ser levadas para o lugar que ele escolher,

[[v5-12-27]]

^<<v5-12-27,27>>^ e ali no altar do Senhor  devem ser oferecidos os animais que são completamente queimados. E ofereçam também em sacrifício os outros animais; despejem o sangue em cima do altar e comam a carne.

[[v5-12-28]]

^<<v5-12-28,28>>^ Obedeçam fielmente a todas essas leis que eu estou dando a vocês e façam tudo o que o Senhor , nosso Deus, acha bom e certo; assim vocês e os seus descendentes serão felizes para sempre.

[[v5-12-29]]

^<<v5-12-29,29>>^ Moisés continuou, dizendo: — O Senhor , nosso Deus, acabará com os povos da terra que vocês vão invadir e que vai ser de vocês.

[[v5-12-30]]

^<<v5-12-30,30>>^ Portanto, quando estiverem morando lá, não imitem aquela gente. Não sigam a religião deles, nem adorem os seus deuses, pois isso seria um pecado mortal.

[[v5-12-31]]

^<<v5-12-31,31>>^ Não adorem o Senhor , nosso Deus, do jeito que aqueles povos adoram os seus deuses, pois ele odeia e detesta tudo o que esses povos fazem nas suas reuniões religiosas. Eles até chegam a oferecer a esses deuses os filhos e as filhas para serem queimados em sacrifício no altar.

[[v5-12-32]]

^<<v5-12-32,32>>^ — Obedeçam a todas as leis  que eu estou dando a vocês, sem acrescentar nem tirar nada.

'''

xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[&#60; Capítulo Anterior] | <<v5-12-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-013.adoc#v5-13-0[Próximo Capítulo &#62;]