include::./index.adoc[]

[[v5-29-0]]
=== Deuteronômio, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-29-1]]

^<<v5-29-1,1>>^ São estas as condições da aliança  que o Senhor  Deus mandou que Moisés fizesse com os israelitas quando estavam na terra de Moabe, além da aliança que havia feito com eles no monte Sinai.

[[v5-29-2]]

^<<v5-29-2,2>>^ Moisés mandou reunir todo o povo. Então lhes disse: — Quando vocês estavam no Egito, viram o que o Senhor  fez com o rei e os seus oficiais e com todo o país.

[[v5-29-3]]

^<<v5-29-3,3>>^ Vocês viram as pragas, os milagres e as outras coisas espantosas que ele fez.

[[v5-29-4]]

^<<v5-29-4,4>>^ Mas até o dia de hoje o Senhor  não deixou que vocês percebessem, ouvissem ou entendessem tudo o que viram.

[[v5-29-5]]

^<<v5-29-5,5>>^ Durante quarenta anos ele os guiou pelo deserto; nesse tempo todo não ficaram gastas as roupas que vocês vestiam, nem as sandálias que calçavam.

[[v5-29-6]]

^<<v5-29-6,6>>^ Vocês não tinham pão para comer, nem vinho ou cerveja para beber, mas Deus lhes deu tudo o que precisavam, a fim de que ficassem sabendo que ele é o Senhor , nosso Deus.

[[v5-29-7]]

^<<v5-29-7,7>>^ Quando chegamos aqui em Moabe, aconteceu que Seom, rei de Hesbom, e Ogue, rei de Basã, saíram com os seus exércitos para lutar contra nós. Nós os derrotamos,

[[v5-29-8]]

^<<v5-29-8,8>>^ ficamos com as terras deles e as repartimos entre as tribos  de Rúben e de Gade e metade da tribo de Manassés.

[[v5-29-9]]

^<<v5-29-9,9>>^ Portanto, cumpram todas as condições desta aliança para que tudo o que fizerem dê certo.

[[v5-29-10]]

^<<v5-29-10,10>>^ — Hoje todos vocês estão aqui na presença do Senhor , nosso Deus: os chefes das tribos, os líderes e as autoridades, todos os homens,

[[v5-29-11]]

^<<v5-29-11,11>>^ as crianças e as mulheres, todos os estrangeiros que moram no acampamento, até os que cortam lenha e os que carregam água.

[[v5-29-12]]

^<<v5-29-12,12>>^ Vocês estão aqui para prometer que vão cumprir a aliança que o Senhor , nosso Deus, jurou que ia fazer. Ele está fazendo esta aliança com vocês hoje

[[v5-29-13]]

^<<v5-29-13,13>>^ para que sejam o seu povo escolhido, e para que ele seja o Deus de vocês, conforme lhes prometeu e conforme o juramento que fez aos nossos antepassados Abraão, Isaque e Jacó.

[[v5-29-14]]

^<<v5-29-14,14>>^ A aliança selada com o juramento de Deus não é feita somente com vocês

[[v5-29-15]]

^<<v5-29-15,15>>^ que estão reunidos hoje aqui na presença do Senhor , nosso Deus; é feita também com todos os seus descendentes que ainda vão nascer.

[[v5-29-16]]

^<<v5-29-16,16>>^ — Vocês lembram da nossa vida no Egito e lembram também dos países que atravessamos.

[[v5-29-17]]

^<<v5-29-17,17>>^ Vocês viram os ídolos nojentos que os povos daqueles países adoram, as imagens de madeira, de pedra, de prata e de ouro.

[[v5-29-18]]

^<<v5-29-18,18>>^ Portanto, que nenhum de vocês, quer seja homem, mulher, família ou tribo, abandone o Senhor , nosso Deus, para adorar os deuses daqueles povos. Isso seria como uma planta que brota e cresce e dá frutas amargas e venenosas.

[[v5-29-19]]

^<<v5-29-19,19>>^ Que ninguém aqui ouça este juramento e depois diga a si mesmo que tudo vai bem e que nenhum mal lhe acontecerá, mesmo que continue na sua maldade! Isso causaria a destruição de todos, tanto dos bons como dos maus.

[[v5-29-20]]

^<<v5-29-20,20>>^ O Senhor  Deus não perdoará quem fizer isso; pelo contrário, descarregará a sua ira  e o seu furor sobre ele e o castigará com todas as maldições que estão escritas neste livro, e ninguém lembrará mais dele.

[[v5-29-21]]

^<<v5-29-21,21>>^ O Senhor  o separará das tribos de Israel e o castigará, conforme todas as maldições que estão na aliança que vem escrita neste Livro da Lei  de Deus.

[[v5-29-22]]

^<<v5-29-22,22>>^ — No futuro os seus descendentes e os estrangeiros que virão de países distantes verão os resultados dos desastres e das doenças que o Senhor  vai mandar a esta nação.

[[v5-29-23]]

^<<v5-29-23,23>>^ O país ficará um deserto, todo coberto de enxofre e de sal. Não haverá plantações nem colheitas, e nenhuma erva crescerá ali. O país vai ficar como as cidades de Sodoma e Gomorra, de Admá e Zeboim, que o Senhor  Deus destruiu quando ficou irado e furioso com elas.

[[v5-29-24]]

^<<v5-29-24,24>>^ Portanto, no futuro os outros povos perguntarão: "Por que Deus fez isso com este país? Por que ficou tão irado e furioso?"

[[v5-29-25]]

^<<v5-29-25,25>>^ E a resposta será: "Deus fez isso porque este povo quebrou a aliança que o Senhor , o Deus dos seus antepassados, fez com eles quando os tirou do Egito.

[[v5-29-26]]

^<<v5-29-26,26>>^ Eles se ajoelharam diante de outros deuses e os adoraram, deuses cujo amor eles não haviam sentido, deuses que Deus não havia indicado para serem adorados pelo seu povo.

[[v5-29-27]]

^<<v5-29-27,27>>^ O Senhor  Deus ficou irado com este povo e por isso castigou o país deles com todas as maldições escritas neste livro.

[[v5-29-28]]

^<<v5-29-28,28>>^ Ele ficou tão irado, tão furioso, que os arrancou da terra onde moravam e os jogou noutra terra, onde estão morando agora."

[[v5-29-29]]

^<<v5-29-29,29>>^ — Há coisas que não sabemos, e elas pertencem ao Senhor , nosso Deus; mas o que ele revelou, isto é, a sua Lei , é para nós e para os nossos descendentes, para sempre. Ele fez isso a fim de que obedecêssemos a todas as suas leis.

'''

xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[&#60; Capítulo Anterior] | <<v5-29-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-030.adoc#v5-30-0[Próximo Capítulo &#62;]