include::./index.adoc[]

[[v5-28-0]]
=== Deuteronômio, 28
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-28-1]]

^<<v5-28-1,1>>^ Moisés disse ao povo: — Se vocês derem atenção a tudo o que o Senhor , nosso Deus, está dizendo a vocês e se obedecerem fielmente a todos os seus mandamentos que eu lhes estou dando hoje, Deus fará com que sejam mais poderosos do que qualquer outra nação do mundo.

[[v5-28-2]]

^<<v5-28-2,2>>^ Obedeçam ao Senhor  Deus, e ele lhes dará todas estas bênçãos:

[[v5-28-3]]

^<<v5-28-3,3>>^ — Deus os abençoará nas cidades e nos campos.

[[v5-28-4]]

^<<v5-28-4,4>>^ — Deus os abençoará dando-lhes muitos filhos, boas colheitas e muitas crias de gado e de ovelhas.

[[v5-28-5]]

^<<v5-28-5,5>>^ — Deus os abençoará com boas colheitas de trigo e de cevada  e com muita comida.

[[v5-28-6]]

^<<v5-28-6,6>>^ — Deus os abençoará em tudo o que fizerem.

[[v5-28-7]]

^<<v5-28-7,7>>^ — Quando os inimigos atacarem, o Senhor  Deus os destruirá na presença de vocês. Eles atacarão juntos, em ordem, mas fugirão para todos os lados, em desordem.

[[v5-28-8]]

^<<v5-28-8,8>>^ — O Senhor , nosso Deus, abençoará vocês em tudo o que fizerem e lhes dará tanto trigo, que os seus depósitos ficarão cheios. Ele os abençoará ricamente na terra que está dando a vocês.

[[v5-28-9]]

^<<v5-28-9,9>>^ — Se obedecerem a todas as leis  do Senhor , nosso Deus, e cumprirem todas as suas ordens, ele fará com que sejam o seu único povo, o povo escolhido, como prometeu com juramento a vocês.

[[v5-28-10]]

^<<v5-28-10,10>>^ Todos os outros povos do mundo verão que vocês pertencem a Deus, o Senhor , e terão medo de vocês.

[[v5-28-11]]

^<<v5-28-11,11>>^ Ele lhes dará muitos filhos, muitos animais e boas colheitas na terra que está dando a vocês, de acordo com o juramento que fez aos nossos antepassados.

[[v5-28-12]]

^<<v5-28-12,12>>^ Deus abrirá o céu, onde guarda as suas ricas bênçãos, e lhes dará chuvas no tempo certo e assim abençoará o trabalho que vocês fizerem. Vocês emprestarão a muitas nações, porém não tomarão emprestado de ninguém.

[[v5-28-13]]

^<<v5-28-13,13>>^ Se obedecerem fielmente a todos os mandamentos do Senhor  Deus que hoje eu estou dando a vocês, ele fará com que fiquem no primeiro lugar entre as nações e não no último; e fará também com que a fama de vocês sempre cresça e nunca diminua.

[[v5-28-14]]

^<<v5-28-14,14>>^ Não se desviem desses mandamentos que hoje eu estou dando a vocês, nem para um lado nem para o outro, e nunca adorem nem sirvam outros deuses.

[[v5-28-15]]

^<<v5-28-15,15>>^ — Porém, se vocês não derem atenção ao que o Senhor , nosso Deus, está mandando e não obedecerem às suas leis e aos seus mandamentos que lhes estou dando hoje, vocês serão castigados com as seguintes maldições:

[[v5-28-16]]

^<<v5-28-16,16>>^ — Deus os amaldiçoará nas cidades e nos campos.

[[v5-28-17]]

^<<v5-28-17,17>>^ — Deus os amaldiçoará dando-lhes pequenas colheitas de trigo e de cevada  e pouco alimento.

[[v5-28-18]]

^<<v5-28-18,18>>^ — Deus os amaldiçoará dando-lhes poucos filhos, colheitas pequenas e poucas crias de gado e de ovelhas.

[[v5-28-19]]

^<<v5-28-19,19>>^ — Deus os amaldiçoará em tudo o que fizerem.

[[v5-28-20]]

^<<v5-28-20,20>>^ — Se vocês abandonarem o Senhor  e começarem a praticar maldades, ele fará cair sobre vocês maldição, confusão e castigo. Ele os amaldiçoará em tudo o que fizerem e acabará logo com vocês.

[[v5-28-21]]

^<<v5-28-21,21>>^ O Senhor  os castigará com doenças e mais doenças, até que todos morram na terra que vão invadir e que vai ser de vocês.

[[v5-28-22]]

^<<v5-28-22,22>>^ Ele os castigará com doenças contagiosas, infecções, inflamações e febres; mandará secas e ventos muito quentes; e fará com que pragas ataquem as plantas. Essas desgraças continuarão até que vocês morram.

[[v5-28-23]]

^<<v5-28-23,23>>^ Não haverá chuva, e o chão ficará duro como ferro.

[[v5-28-24]]

^<<v5-28-24,24>>^ Em vez de chuva, o Senhor  Deus mandará pó e areia sobre a terra, até que vocês sejam destruídos.

[[v5-28-25]]

^<<v5-28-25,25>>^ O Senhor  fará com que sejam derrotados pelos inimigos. Vocês atacarão juntos, em ordem, mas fugirão para todos os lados, em desordem. Todos os povos do mundo ficarão espantados quando souberem do que aconteceu com vocês.

[[v5-28-26]]

^<<v5-28-26,26>>^ Vocês morrerão, e o corpo de vocês servirá de comida para as aves e para os animais ferozes, e ninguém os enxotará.

[[v5-28-27]]

^<<v5-28-27,27>>^ O Senhor  Deus castigará vocês com tumores, como fez com os egípcios; vocês sofrerão de úlceras, chagas e coceiras sem cura.

[[v5-28-28]]

^<<v5-28-28,28>>^ O Senhor  os castigará, fazendo com que fiquem loucos, cegos e confusos.

[[v5-28-29]]

^<<v5-28-29,29>>^ Ao meio-dia vocês andarão sem rumo, como um cego apalpando o caminho. Vocês fracassarão em tudo o que fizerem, serão perseguidos e explorados a vida inteira, e não haverá ninguém que os socorra.

[[v5-28-30]]

^<<v5-28-30,30>>^ — Você contratará casamento, mas outro homem terá relações com a moça; você construirá uma casa, mas não morará nela; plantará uma parreira , mas não colherá as uvas.

[[v5-28-31]]

^<<v5-28-31,31>>^ Você verá o seu gado sendo morto, mas não comerá da carne. Verá outros levarem embora os seus jumentos, e estes não serão devolvidos. Os inimigos levarão as suas ovelhas, e não haverá ninguém para socorrê-lo.

[[v5-28-32]]

^<<v5-28-32,32>>^ — Na presença de vocês, estrangeiros pegarão os seus filhos e as suas filhas e os levarão embora como escravos. Vocês morrerão de saudade deles, mas não poderão fazer nada para trazê-los de volta.

[[v5-28-33]]

^<<v5-28-33,33>>^ Estrangeiros virão e levarão os cereais que com tanto trabalho vocês plantaram e colheram. Todos os dias vocês serão maltratados e perseguidos

[[v5-28-34]]

^<<v5-28-34,34>>^ e ficarão loucos por causa dos maus-tratos que vão receber.

[[v5-28-35]]

^<<v5-28-35,35>>^ O Senhor  Deus os castigará com tumores incuráveis nas pernas; da ponta dos pés até a cabeça, o corpo de vocês ficará coberto de feridas que nunca saram.

[[v5-28-36]]

^<<v5-28-36,36>>^ — O Senhor  Deus levará todos vocês, junto com o rei que tiverem escolhido, para um país estrangeiro, que nem vocês nem os seus antepassados conheciam. Ali vocês adorarão deuses de madeira e de pedra.

[[v5-28-37]]

^<<v5-28-37,37>>^ Os povos dos países para onde o Senhor  os levar ficarão espantados quando souberem do que aconteceu com vocês. Eles falarão mal e zombarão de vocês.

[[v5-28-38]]

^<<v5-28-38,38>>^ — Vocês plantarão muitas sementes, mas a colheita será pequena porque os gafanhotos acabarão com tudo.

[[v5-28-39]]

^<<v5-28-39,39>>^ Vocês farão plantações de uvas e cuidarão delas, mas não colherão as uvas, nem beberão do vinho, pois os bichos acabarão com as plantas.

[[v5-28-40]]

^<<v5-28-40,40>>^ No país inteiro haverá muitas oliveiras, mas vocês não terão azeite para se ungirem , pois as azeitonas cairão das árvores antes de ficarem maduras.

[[v5-28-41]]

^<<v5-28-41,41>>^ Vocês terão filhos e filhas, mas estrangeiros os levarão como prisioneiros.

[[v5-28-42]]

^<<v5-28-42,42>>^ Os gafanhotos destruirão todas as árvores e todas as plantas da terra de vocês.

[[v5-28-43]]

^<<v5-28-43,43>>^ — Os estrangeiros que moram no meio de vocês ficarão cada vez mais poderosos, ao passo que vocês ficarão cada vez mais fracos.

[[v5-28-44]]

^<<v5-28-44,44>>^ Eles emprestarão a vocês, mas não tomarão emprestado de vocês; eles ficarão no primeiro lugar entre as nações, e vocês ficarão no último.

[[v5-28-45]]

^<<v5-28-45,45>>^ Moisés disse ao povo: — Todas essas maldições cairão sobre vocês e os perseguirão até os destruírem completamente. Pois vocês não deram atenção ao que o Senhor , nosso Deus, disse e não obedeceram às leis  e aos mandamentos que deu a vocês.

[[v5-28-46]]

^<<v5-28-46,46>>^ Essas desgraças serão para sempre a prova de que Deus castigou vocês e os seus descendentes.

[[v5-28-47]]

^<<v5-28-47,47>>^ O Senhor  lhes dará tudo o que é bom; mas, se vocês não o servirem com alegria e gratidão,

[[v5-28-48]]

^<<v5-28-48,48>>^ serão escravos dos inimigos que o Senhor  mandará contra vocês. Vocês os servirão com fome e com sede, sem roupa e precisando de tudo. Deus tratará vocês com crueldade até os destruir.

[[v5-28-49]]

^<<v5-28-49,49>>^ — O Senhor  Deus fará vir contra vocês, de longe, lá do fim do mundo, um povo estrangeiro que fala uma língua que vocês não entendem. Eles os atacarão como uma águia.

[[v5-28-50]]

^<<v5-28-50,50>>^ São gente cruel, que não respeita os velhos, nem tem pena dos moços.

[[v5-28-51]]

^<<v5-28-51,51>>^ Eles vão devorar todo o seu gado e todas as suas colheitas, e vocês morrerão de fome. Eles não deixarão para vocês nem cereais, nem vinho, nem azeite, nem crias de vacas e de ovelhas.

[[v5-28-52]]

^<<v5-28-52,52>>^ Cercarão as cidades onde vocês moram, até que caiam as muralhas altas e fortes em que vocês confiavam. Todas as cidades da terra que o Senhor , nosso Deus, lhes deu serão cercadas pelo inimigo.

[[v5-28-53]]

^<<v5-28-53,53>>^ O cerco será terrível. Os moradores das cidades ficarão tão desesperados, que comerão os próprios filhos que Deus lhes deu.

[[v5-28-54]]

^<<v5-28-54,54>>^ A situação será tão terrível, que não haverá nada para comer. Até o homem mais educado e carinhoso ficará tão desesperado, que comerá os próprios filhos, e será tão mau, que não repartirá a carne com os irmãos, nem com a sua querida mulher, nem com os outros filhos.

[[v5-28-55]]

^<<v5-28-55,55>>^ A situação será tão terrível, que não haverá nada para comer. Até o homem mais educado e carinhoso ficará tão desesperado, que comerá os próprios filhos, e será tão mau, que não repartirá a carne com os irmãos, nem com a sua querida mulher, nem com os outros filhos.

[[v5-28-56]]

^<<v5-28-56,56>>^ A situação será tão terrível, que até a mulher mais delicada e carinhosa, que nunca precisou andar a pé quando saía de casa, ficará tão desesperada, que comerá, às escondidas, seu bebê recém-nascido e a placenta também. Ela será tão má, que não dará nenhum pedaço para o seu querido marido, nem para os outros filhos.

[[v5-28-57]]

^<<v5-28-57,57>>^ A situação será tão terrível, que até a mulher mais delicada e carinhosa, que nunca precisou andar a pé quando saía de casa, ficará tão desesperada, que comerá, às escondidas, seu bebê recém-nascido e a placenta também. Ela será tão má, que não dará nenhum pedaço para o seu querido marido, nem para os outros filhos.

[[v5-28-58]]

^<<v5-28-58,58>>^ — Se vocês não cumprirem todas as leis que estão escritas neste livro e se não respeitarem o nome do Senhor , nosso Deus, esse nome que é glorioso  e causa medo,

[[v5-28-59]]

^<<v5-28-59,59>>^ então ele castigará vocês e os seus descendentes com pragas e com doenças terríveis e demoradas.

[[v5-28-60]]

^<<v5-28-60,60>>^ Ele os castigará com as mesmas doenças com que castigou os egípcios, doenças que não têm cura e que deixam vocês com tanto medo.

[[v5-28-61]]

^<<v5-28-61,61>>^ O Senhor  mandará também doenças e pragas que não estão escritas neste Livro da Lei  e os destruirá.

[[v5-28-62]]

^<<v5-28-62,62>>^ Vocês, que já foram tão numerosos como as estrelas do céu, ficarão um punhado de gente porque não obedeceram às ordens do Senhor , nosso Deus.

[[v5-28-63]]

^<<v5-28-63,63>>^ E assim como o Senhor  tinha prazer em abençoá-los e fazer com que aumentassem em número, assim também terá prazer em castigá-los e destruí-los. Vocês serão arrancados da terra que vão invadir e que vai ser de vocês.

[[v5-28-64]]

^<<v5-28-64,64>>^ — O Senhor  Deus os espalhará por todos os países, de uma ponta do mundo à outra. Ali vocês adorarão deuses de madeira e de pedra, que nem vocês nem os seus antepassados conheciam.

[[v5-28-65]]

^<<v5-28-65,65>>^ E também nesses países vocês não terão sossego nem paz; o Senhor  fará com que fiquem cheios de aflição, desespero e medo.

[[v5-28-66]]

^<<v5-28-66,66>>^ A vida de vocês estará sempre em perigo; dia e noite o medo os acompanhará, e vocês ficarão desesperados da vida.

'''

xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[&#60; Capítulo Anterior] | <<v5-28-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[Próximo Capítulo &#62;]