include::./index.adoc[]

[[v5-17-0]]
=== Deuteronômio, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-17-1]]

^<<v5-17-1,1>>^ — Não ofereçam em sacrifício  ao Senhor , nosso Deus, um touro ou uma ovelha que tenha defeitos; Deus detesta isso.

[[v5-17-2]]

^<<v5-17-2,2>>^ — É possível que, em alguma das cidades que o Senhor , nosso Deus, vai dar a vocês, um homem ou uma mulher peque contra Deus e quebre a aliança  feita com ele,

[[v5-17-3]]

^<<v5-17-3,3>>^ isto é, adore outros deuses, ou o sol, ou a lua, ou as estrelas, desobedecendo assim à lei  de Deus.

[[v5-17-4]]

^<<v5-17-4,4>>^ Se souberem que alguém está fazendo isso, examinem o caso com todo o cuidado. Se ficar provado que, de fato, foi cometido um pecado tão grave no meio do povo de Israel,

[[v5-17-5]]

^<<v5-17-5,5>>^ levem a pessoa culpada, seja homem ou mulher, para fora da cidade e a matem a pedradas.

[[v5-17-6]]

^<<v5-17-6,6>>^ Mas é preciso haver pelo menos duas testemunhas para que uma pessoa seja condenada à morte; ninguém pode ser morto se houver somente uma testemunha.

[[v5-17-7]]

^<<v5-17-7,7>>^ As testemunhas serão as primeiras a jogarem pedras no condenado; depois todos os outros devem atirar pedras também. Matem essa pessoa e assim tirarão o mal do meio do povo.

[[v5-17-8]]

^<<v5-17-8,8>>^ — Pode acontecer que numa cidade apareça um caso tão difícil, que o juiz do lugar não possa resolvê-lo. Pode ser um caso de assassinato, ou questão de propriedade, ou caso de violência, ou outra questão qualquer. Quando isso acontecer, vão até o lugar escolhido por Deus, o Senhor , para nele ser adorado

[[v5-17-9]]

^<<v5-17-9,9>>^ e apresentem o caso aos sacerdotes levitas  e ao juiz que estiver resolvendo as questões naquele tempo. Eles julgarão o caso e darão a sua decisão.

[[v5-17-10]]

^<<v5-17-10,10>>^ Vocês farão tudo o que eles mandarem, obedecendo a todas as suas instruções.

[[v5-17-11]]

^<<v5-17-11,11>>^ Aceitem a decisão deles, sigam as suas instruções e cumpram rigorosamente as ordens que eles derem.

[[v5-17-12]]

^<<v5-17-12,12>>^ Mas, se houver alguém tão orgulhoso, que não queira obedecer à decisão do sacerdote ou do juiz, esse alguém será morto, e assim vocês tirarão o mal do meio do povo de Israel.

[[v5-17-13]]

^<<v5-17-13,13>>^ Quando souberem do que aconteceu, todos ficarão com medo, e ninguém mais fará a mesma coisa.

[[v5-17-14]]

^<<v5-17-14,14>>^ — Depois que vocês entrarem na terra que o Senhor , nosso Deus, está dando a vocês e tomarem posse dela e depois que tiverem morado lá algum tempo, vocês vão querer um rei para os governar, como os reis das nações vizinhas.

[[v5-17-15]]

^<<v5-17-15,15>>^ O homem que escolherem para ser o rei deve ser indicado por Deus, o Senhor . Não pode ser estrangeiro; somente um israelita pode ser escolhido como rei.

[[v5-17-16]]

^<<v5-17-16,16>>^ O rei não deverá ter muitos cavalos no seu exército e também não mandará homens ao Egito para comprarem cavalos, pois o Senhor  já disse a vocês que nunca mais voltariam para o Egito.

[[v5-17-17]]

^<<v5-17-17,17>>^ O rei não deverá ter muitas mulheres, pois isso o levaria a abandonar a Deus. E também não ajuntará para si muita prata e ouro.

[[v5-17-18]]

^<<v5-17-18,18>>^ — Quando o rei começar a governar, mandará fazer uma cópia da lei  de Deus que está no livro guardado pelos sacerdotes levitas .

[[v5-17-19]]

^<<v5-17-19,19>>^ Ele deverá ficar com essa cópia e todos os dias da sua vida lerá a lei, para que aprenda a temer  o Senhor , nosso Deus, e para que sempre obedeça fielmente a todas as leis e a todos os mandamentos.

[[v5-17-20]]

^<<v5-17-20,20>>^ Se fizer isso, ele não irá pensar que é mais do que os outros e cumprirá fielmente todas as leis. Assim reinará muitos anos, e os seus descendentes serão reis de Israel por muito tempo.

'''

xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[&#60; Capítulo Anterior] | <<v5-17-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[Próximo Capítulo &#62;]