include::./index.adoc[]

[[v5-9-0]]
=== Deuteronômio, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-9-1]]

^<<v5-9-1,1>>^ Moisés disse ao povo: — Escute, ó povo de Israel! Hoje vocês vão atravessar o rio Jordão e vão tomar posse de uma terra que pertence a povos mais numerosos e mais poderosos do que vocês. As cidades deles são enormes e são protegidas por muralhas que chegam até o céu.

[[v5-9-2]]

^<<v5-9-2,2>>^ Vocês já ouviram falar dos anaquins , uma raça de gigantes fortes que moram naquela terra; pois todos dizem: "Ninguém pode derrotar os anaquins."

[[v5-9-3]]

^<<v5-9-3,3>>^ Mas fiquem certos de que o Senhor , nosso Deus, vai hoje na frente de vocês como um fogo que devora tudo. Ele derrotará e destruirá os povos dessa terra, e assim, conforme o Senhor  Deus prometeu, vocês irão expulsá-los e matá-los depressa.

[[v5-9-4]]

^<<v5-9-4,4>>^ — Mas, depois que o Senhor , nosso Deus, tiver expulsado esses povos da presença de vocês, não fiquem pensando assim: "Deus nos trouxe aqui e nos deu esta terra porque somos bons." Não é por isso; mas Deus vai expulsar esses povos da presença de vocês porque eles são maus.

[[v5-9-5]]

^<<v5-9-5,5>>^ Vocês não vão tomar posse da terra porque são bons e honestos. É por causa da maldade desses povos que Deus vai expulsá-los e também porque o Senhor , nosso Deus, quer cumprir o que prometeu aos nossos antepassados Abraão, Isaque e Jacó.

[[v5-9-6]]

^<<v5-9-6,6>>^ Portanto, fiquem certos de que Deus lhes está dando esta boa terra não porque vocês sejam bons; pelo contrário, vocês são gente teimosa.

[[v5-9-7]]

^<<v5-9-7,7>>^ — Nunca esqueçam que no deserto vocês provocaram tanto a Deus, o Senhor , que ele ficou irado  com vocês. Desde que saíram do Egito até chegarem aqui, vocês têm se revoltado contra Deus.

[[v5-9-8]]

^<<v5-9-8,8>>^ Até mesmo no monte Sinai vocês o provocaram, e ele ficou tão irado, que pensou em destruí-los.

[[v5-9-9]]

^<<v5-9-9,9>>^ Eu subi o monte para receber de Deus as duas placas de pedra, nas quais estava escrita a aliança  que ele fez com vocês. Fiquei ali no monte quarenta dias e quarenta noites e durante todo aquele tempo não comi, nem bebi nada.

[[v5-9-10]]

^<<v5-9-10,10>>^ O Senhor  Deus me deu as duas placas de pedra. Ele mesmo tinha escrito nelas tudo o que tinha dito a vocês do meio do fogo, quando estavam reunidos ao pé do monte.

[[v5-9-11]]

^<<v5-9-11,11>>^ — Foi no fim daqueles quarenta dias que o Senhor  Deus me deu as duas placas da aliança.

[[v5-9-12]]

^<<v5-9-12,12>>^ Aí ele me disse: "Desça logo daqui e volte para onde está o povo que você tirou do Egito, pois eles já cometeram um pecado grave. Bem depressa deixaram de seguir as minhas ordens e já fizeram um ídolo de metal para adorar.

[[v5-9-13]]

^<<v5-9-13,13>>^ Eu sei — Deus continuou — que este povo é teimoso.

[[v5-9-14]]

^<<v5-9-14,14>>^ Portanto, não procure me impedir, pois vou destruí-los, e assim ninguém lembrará mais que existiram. E de você, Moisés, e dos seus descendentes farei uma nação maior e mais poderosa do que a deles."

[[v5-9-15]]

^<<v5-9-15,15>>^ E Moisés continuou: — Aí eu desci do monte, do qual subiam chamas de fogo. Levava comigo as duas placas de pedra, as placas da aliança.

[[v5-9-16]]

^<<v5-9-16,16>>^ Quando cheguei perto de vocês, vi que haviam pecado contra o Senhor , nosso Deus, e que bem depressa haviam deixado de seguir as suas ordens. Vi o bezerro de metal que vocês haviam feito para adorar.

[[v5-9-17]]

^<<v5-9-17,17>>^ Então, na presença de vocês, joguei as placas de pedra no chão e as quebrei.

[[v5-9-18]]

^<<v5-9-18,18>>^ Depois me ajoelhei diante de Deus, o Senhor , e fiquei ali quarenta dias e quarenta noites com o rosto encostado no chão. Como havia feito antes, não comi nem bebi nada durante aquele tempo. Agi dessa maneira porque vocês pecaram contra o Senhor , fazendo o que ele condena e provocando a sua ira.

[[v5-9-19]]

^<<v5-9-19,19>>^ Eu estava com medo da ira e do furor de Deus; ele estava tão irado, que pensava em destruí-los. Porém mais uma vez Deus atendeu o meu pedido.

[[v5-9-20]]

^<<v5-9-20,20>>^ Ele estava irado também com Arão e pensou em matá-lo; por isso orei também em favor de Arão.

[[v5-9-21]]

^<<v5-9-21,21>>^ Aí peguei o bezerro de metal, aquele objeto nojento que vocês tinham feito, e o joguei no fogo. Depois o quebrei em pedaços, moí tudo até virar pó e atirei o pó no ribeirão que corria monte abaixo.

[[v5-9-22]]

^<<v5-9-22,22>>^ — Vocês provocaram, de novo, a ira do Senhor  Deus, em Taberá, em Massá e em Quibrote-Ataavá.

[[v5-9-23]]

^<<v5-9-23,23>>^ E também o provocaram em Cades-Barneia, quando ele mandou que tomassem posse da terra que lhes estava dando. Vocês não confiaram em Deus, mas se revoltaram contra ele e desobedeceram à sua ordem.

[[v5-9-24]]

^<<v5-9-24,24>>^ Desde o dia em que eu os conheci, vocês sempre foram rebeldes contra Deus, o Senhor !

[[v5-9-25]]

^<<v5-9-25,25>>^ E Moisés continuou, dizendo: — Quarenta dias e quarenta noites fiquei ajoelhado, com o rosto encostado no chão, na presença de Deus, o Senhor , pois ele tinha dito que iria destruí-los.

[[v5-9-26]]

^<<v5-9-26,26>>^ E orei assim ao Senhor : "Ó Senhor , meu Deus! Eu te peço que não destruas o teu povo, o teu povo escolhido, que com a tua força e com o teu poder livraste do Egito.

[[v5-9-27]]

^<<v5-9-27,27>>^ Lembra dos teus servos  Abraão, Isaque e Jacó e não dês atenção à teimosia, à maldade e ao pecado deste povo.

[[v5-9-28]]

^<<v5-9-28,28>>^ Pois, se destruíres o teu povo, os egípcios vão dizer que não pudeste levá-lo para a terra que lhe prometeste. Dirão também que odeias este povo e por isso o levaste ao deserto para matá-lo.

[[v5-9-29]]

^<<v5-9-29,29>>^ Mas eles são o teu povo, o teu povo escolhido, que tiraste do Egito com a tua força e com o teu grande poder."

'''

xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[&#60; Capítulo Anterior] | <<v5-9-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[Próximo Capítulo &#62;]