include::./index.adoc[]

[[v5-22-0]]
=== Deuteronômio, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-22-1]]

^<<v5-22-1,1>>^ — Se a vaca ou o carneiro de um israelita fugir do dono, e você vir o animal andando solto, não faça de conta que não viu; leve-o de volta ao dono.

[[v5-22-2]]

^<<v5-22-2,2>>^ Se o dono morar longe ou se você não souber quem é, leve o animal para casa e fique com ele até que o dono venha procurá-lo; então entregue-o a ele.

[[v5-22-3]]

^<<v5-22-3,3>>^ Faça o mesmo com o jumento, a roupa ou qualquer outra coisa que você achar e que for de outro israelita. Não faça de conta que não sabe de nada.

[[v5-22-4]]

^<<v5-22-4,4>>^ — Se o jumento ou o boi que é de outro israelita cair na estrada, e você vir o animal caído ali, não faça de conta que não viu; ajude o dono a pôr o animal de pé.

[[v5-22-5]]

^<<v5-22-5,5>>^ — As mulheres não podem usar roupa de homem, nem os homens usar roupa de mulher; o Senhor , nosso Deus, detesta as pessoas que fazem isso.

[[v5-22-6]]

^<<v5-22-6,6>>^ — Se você encontrar um ninho numa árvore ou caído no chão, e a mãe estiver lá com os filhotes ou com os ovos, não pegue a mãe;

[[v5-22-7]]

^<<v5-22-7,7>>^ leve os filhotes, mas deixe a mãe sair voando a fim de que tudo corra bem para você, e você viva muitos anos.

[[v5-22-8]]

^<<v5-22-8,8>>^ — Quando você construir uma casa, coloque uma grade de madeira em volta do terraço. Assim você não será culpado se alguém cair dali e morrer.

[[v5-22-9]]

^<<v5-22-9,9>>^ — Não plante na sua plantação de uvas qualquer outra coisa; se você fizer isso, estará proibido de aproveitar tanto as uvas como aquilo que as outras plantas produzirem. Você terá de entregar tudo aos sacerdotes.

[[v5-22-10]]

^<<v5-22-10,10>>^ — Não ponha juntos um boi e um jumento para puxarem o arado.

[[v5-22-11]]

^<<v5-22-11,11>>^ — Não vista roupa feita de tecido de lã e de linho misturados.

[[v5-22-12]]

^<<v5-22-12,12>>^ — Ponha pingentes nas quatro pontas da capa  que você usa.

[[v5-22-13]]

^<<v5-22-13,13>>^ — Pode acontecer que um homem case e, depois de ter tido relações com a mulher, não queira mais saber dela.

[[v5-22-14]]

^<<v5-22-14,14>>^ Aí começa a caluniá-la e a dizer mentiras contra ela, afirmando que não era virgem quando casaram.

[[v5-22-15]]

^<<v5-22-15,15>>^ Nesse caso, os pais da moça irão falar com os líderes da cidade e no lugar de julgamento na praça pública mostrarão o lençol com as manchas de sangue que provam que a moça era virgem quando casou.

[[v5-22-16]]

^<<v5-22-16,16>>^ E o pai dirá aos líderes: "Dei minha filha em casamento a este homem, mas ele não quis saber mais dela

[[v5-22-17]]

^<<v5-22-17,17>>^ e começou a caluniá-la, dizendo que ela não era virgem quando casaram. Pois vejam aqui a prova de que minha filha era virgem!" E os pais estenderão o lençol em frente dos líderes.

[[v5-22-18]]

^<<v5-22-18,18>>^ Então estes pegarão o homem, lhe darão chicotadas

[[v5-22-19]]

^<<v5-22-19,19>>^ e o farão pagar uma multa de cem barras de prata. Essa quantia será dada ao pai da moça. O homem será castigado assim porque caluniou uma virgem israelita. Além disso, ela continuará sendo sua mulher, e ele nunca poderá mandá-la embora.

[[v5-22-20]]

^<<v5-22-20,20>>^ — Mas, se for provado que a moça não era virgem,

[[v5-22-21]]

^<<v5-22-21,21>>^ aí os líderes a levarão para perto da porta da casa do pai, e os homens da cidade a matarão a pedradas. Ela fez uma coisa vergonhosa no meio do povo de Israel: antes de casada e enquanto ainda vivia na casa do pai, ela teve relações com um homem. Assim vocês tirarão o mal do meio do povo de Israel.

[[v5-22-22]]

^<<v5-22-22,22>>^ — Se um homem casado for encontrado na cama com a esposa de outro, os dois serão mortos, o homem e a mulher. Assim vocês tirarão o mal do meio do povo de Israel.

[[v5-22-23]]

^<<v5-22-23,23>>^ — Se numa cidade for encontrado um homem tendo relações com uma moça que tenha casamento contratado com outro homem,

[[v5-22-24]]

^<<v5-22-24,24>>^ levem os dois para fora da cidade e ali os matem a pedradas. A moça deve morrer porque não gritou pedindo socorro, e o homem, porque desonrou uma moça prometida a outro. Assim vocês tirarão o mal do meio do povo de Israel.

[[v5-22-25]]

^<<v5-22-25,25>>^ Mas, se foi no campo que o homem forçou a moça, então só ele será morto.

[[v5-22-26]]

^<<v5-22-26,26>>^ Não façam nada com a moça, pois não merece a morte. O caso dela é como o de um homem que é morto por outro: a vítima não tem culpa do crime.

[[v5-22-27]]

^<<v5-22-27,27>>^ O homem forçou a moça no campo; ela gritou pedindo socorro, mas não havia ninguém para socorrê-la.

[[v5-22-28]]

^<<v5-22-28,28>>^ — Se um homem forçar uma virgem que ainda não tenha casamento contratado, e o caso for descoberto,

[[v5-22-29]]

^<<v5-22-29,29>>^ então o homem pagará ao pai da moça cinquenta barras de prata, que é o preço de uma virgem. Ele a forçou, e por isso ela será sua esposa, e ele nunca poderá mandá-la embora.

[[v5-22-30]]

^<<v5-22-30,30>>^ — Nenhum homem terá relações com nenhuma das mulheres do seu pai, pois isso seria uma vergonha para o pai.

'''

xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[Próximo Capítulo &#62;]