include::./index.adoc[]

[[v5-3-0]]
=== Deuteronômio, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-3-1]]

^<<v5-3-1,1>>^ Moisés continuou: — Depois fomos na direção do norte até a região de Basã. E Ogue, rei de Basã, saiu com o seu exército para lutar contra nós na cidade de Edrei.

[[v5-3-2]]

^<<v5-3-2,2>>^ Mas o Senhor  Deus me disse: "Não tenha medo, pois eu farei com que você derrote Ogue e o seu exército, e você vai tomar posse da terra dele. Você será vitorioso, como foi contra Seom, o rei dos amorreus, que morava em Hesbom."

[[v5-3-3]]

^<<v5-3-3,3>>^ — O Senhor , nosso Deus, fez com que derrotássemos Ogue e todo o seu exército, e nós matamos todos, sem deixar ninguém vivo.

[[v5-3-4]]

^<<v5-3-4,4>>^ Também conquistamos todas as cidades de Argobe, a terra da região de Basã que pertencia a Ogue. Eram ao todo sessenta cidades,

[[v5-3-5]]

^<<v5-3-5,5>>^ todas elas protegidas por muralhas altas e com portões reforçados. Conquistamos também muitas cidades que não tinham muralhas.

[[v5-3-6]]

^<<v5-3-6,6>>^ Nós as destruímos completamente e matamos todos os homens, mulheres e crianças, como tínhamos feito na guerra contra Seom, rei de Hesbom.

[[v5-3-7]]

^<<v5-3-7,7>>^ Mas ficamos com o gado e com os objetos de valor que encontramos nas cidades.

[[v5-3-8]]

^<<v5-3-8,8>>^ — Foi assim que conquistamos naquele tempo as terras daqueles dois reis amorreus na região a leste do rio Jordão, desde o rio Arnom até o monte Hermom.

[[v5-3-9]]

^<<v5-3-9,9>>^ (Os sidônios chamam o monte Hermom de Siriom, e os amorreus o chamam de Senir.)

[[v5-3-10]]

^<<v5-3-10,10>>^ Conquistamos todas as cidades do planalto e toda a região de Gileade e de Basã, até as cidades de Salca e Edrei, na parte leste de Basã.

[[v5-3-11]]

^<<v5-3-11,11>>^ (Ogue, rei de Basã, foi o último rei da raça de gigantes chamados refains . A sua cama, feita de ferro, media quatro metros de comprimento por um metro e oitenta de largura, de acordo com a medida usada naquele tempo. A cama ainda está na cidade de Rabá, no país de Amom.)

[[v5-3-12]]

^<<v5-3-12,12>>^ Moisés continuou: — Depois que tomamos posse da região a leste do rio Jordão, dei às tribos  de Rúben e de Gade a região que fica ao norte de Aroer, na beira do vale do rio Arnom, e também metade da região montanhosa de Gileade, com as cidades dali.

[[v5-3-13]]

^<<v5-3-13,13>>^ E para uma metade da tribo de Manassés dei o resto de Gileade e toda a região de Basã, onde Ogue havia sido rei, isto é, a terra de Argobe. (Toda a região de Basã era conhecida como a terra dos refains .

[[v5-3-14]]

^<<v5-3-14,14>>^ Jair, que era descendente de Manassés, conquistou toda a região de Argobe, isto é, Basã, até a fronteira com Gesur e Maacá. Ele pôs o seu nome nas cidades dali, e até hoje  elas são conhecidas como as cidades de Jair.)

[[v5-3-15]]

^<<v5-3-15,15>>^ — Eu dei a região de Gileade ao grupo de famílias de Maquir.

[[v5-3-16]]

^<<v5-3-16,16>>^ E para as tribos de Rúben e de Gade dei o território que vai desde a região de Gileade na direção do sul até o vale do rio Arnom; a divisa fica no meio do vale. Para o norte as suas terras vão até o rio Jaboque, que fica na fronteira com a terra dos amonitas.

[[v5-3-17]]

^<<v5-3-17,17>>^ Para o oeste o seu território vai até o rio Jordão, desde o lago da Galileia, no Norte, até o mar Morto, no Sul, e até o pé do monte Pisga, no Leste.

[[v5-3-18]]

^<<v5-3-18,18>>^ — Foi nessa ocasião que dei às tribos de Rúben e de Gade e à metade leste da tribo de Manassés a seguinte ordem: "O Senhor , nosso Deus, lhes deu essas terras a leste do rio Jordão, e vocês tomaram posse delas. Agora, que os homens peguem as suas armas e atravessem o rio Jordão na frente dos seus patrícios para ajudá-los a tomar posse das terras deles.

[[v5-3-19]]

^<<v5-3-19,19>>^ Mas as mulheres, as crianças e o gado — e eu sei que vocês têm muito gado — ficarão aqui nas cidades que já dei a vocês.

[[v5-3-20]]

^<<v5-3-20,20>>^ Ajudem os seus patrícios até que eles acabem de tomar posse das terras que o Senhor , nosso Deus, está dando a eles a oeste do rio Jordão e até que estejam morando ali em paz, como vocês estão nas suas terras. Aí vocês poderão voltar e morar na terra que eu lhes dei aqui, a leste do Jordão."

[[v5-3-21]]

^<<v5-3-21,21>>^ — Também falei com Josué e disse: "Você viu o que o Senhor  Deus fez com aqueles dois reis, Seom e Ogue. Pois é isso mesmo o que ele fará com os reis de todas as terras que vocês vão invadir.

[[v5-3-22]]

^<<v5-3-22,22>>^ Não tenham medo deles, pois o Senhor , seu Deus, combaterá por vocês."

[[v5-3-23]]

^<<v5-3-23,23>>^ — Nessa ocasião eu também orei a Deus, o Senhor , dizendo:

[[v5-3-24]]

^<<v5-3-24,24>>^ "Ó Senhor , meu Deus, eu sei que começaste a mostrar a tua grandeza e o teu poder a mim, teu servo . Pois não existe outro deus no céu ou na terra que possa fazer coisas tão grandes e maravilhosas como tu tens feito!

[[v5-3-25]]

^<<v5-3-25,25>>^ Peço-te, pois, que me deixes atravessar o rio Jordão e ver a boa terra que fica no outro lado, a bela região montanhosa e os montes Líbanos."

[[v5-3-26]]

^<<v5-3-26,26>>^ — Mas por causa de vocês o Senhor  estava irado  comigo e não atendeu o meu pedido. Pelo contrário, ele disse: "Chega! Não fale mais nisso!

[[v5-3-27]]

^<<v5-3-27,27>>^ Suba o monte Pisga e lá de cima olhe para o norte e para o sul, para o leste e para o oeste. Olhe bem toda a terra, pois você não vai atravessar o rio Jordão.

[[v5-3-28]]

^<<v5-3-28,28>>^ Dê conselhos a Josué; anime-o e encoraje-o, pois ele vai comandar o povo de Israel na conquista desta terra que você está vendo."

[[v5-3-29]]

^<<v5-3-29,29>>^ — Então paramos no vale que fica perto da cidade de Bete-Peor.

'''

xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[Próximo Capítulo &#62;]