include::./index.adoc[]

[[v5-33-0]]
=== Deuteronômio, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-33-1]]

^<<v5-33-1,1>>^ Antes de morrer, Moisés, homem de Deus, deu esta bênção ao povo de Israel.

[[v5-33-2]]

^<<v5-33-2,2>>^ Ele disse: O Senhor  Deus veio do monte Sinai; ele surgiu como o sol por cima de Edom e do monte Parã brilhou sobre o seu povo. Com ele vieram milhares de anjos, e à sua direita havia fogo.

[[v5-33-3]]

^<<v5-33-3,3>>^ O Senhor  ama o seu povo e protege os que são dele. Eles ficam sentados diante dele e aprendem as suas leis .

[[v5-33-4]]

^<<v5-33-4,4>>^ Moisés lhes deu a Lei de Deus, o mais rico tesouro do povo de Israel.

[[v5-33-5]]

^<<v5-33-5,5>>^ O Senhor  Deus se tornou Rei do povo escolhido, quando as tribos  e os seus chefes se reuniram.

[[v5-33-6]]

^<<v5-33-6,6>>^ Moisés disse isto a respeito da tribo de Rúben: "Que Rúben viva e nunca morra! Que o seu povo seja sempre numeroso!"

[[v5-33-7]]

^<<v5-33-7,7>>^ A respeito da tribo de Judá foi isto o que Moisés disse: "Ó Deus, ouve a oração de Judá e junta aquela tribo novamente ao teu povo. Luta a favor deles, ó Deus, e ajuda-os na luta contra os seus inimigos."

[[v5-33-8]]

^<<v5-33-8,8>>^ A respeito da tribo de Levi ele disse: "Ó Deus, tu deste o Tumim e o Urim aos teus servos  que escolheste. Tu os puseste à prova em Massá e perto das fontes de Meribá discutiste com eles.

[[v5-33-9]]

^<<v5-33-9,9>>^ Eles são mais dedicados a ti do que aos seus próprios pais e do que aos seus irmãos e filhos. Eles obedecem às tuas leis e cumprem a tua aliança .

[[v5-33-10]]

^<<v5-33-10,10>>^ Eles ensinarão todas as tuas leis ao povo, queimarão incenso na tua presença e no teu altar oferecerão sacrifícios .

[[v5-33-11]]

^<<v5-33-11,11>>^ Ó Deus, abençoa a tribo de Levi e faze com que ela seja cada vez mais forte. Que tudo o que eles fazem seja agradável a ti! Acaba com os seus inimigos para que nunca mais se levantem."

[[v5-33-12]]

^<<v5-33-12,12>>^ Moisés disse a respeito da tribo de Benjamim: "O Senhor  Deus ama a tribo de Benjamim e sempre a guardará. Deus cuidará deles o dia inteiro, e eles viverão debaixo da sua proteção."

[[v5-33-13]]

^<<v5-33-13,13>>^ A respeito da tribo de José ele disse: "Que o Senhor  Deus abençoe as terras de José, dando-lhes muitas chuvas do céu e fontes das profundezas da terra!

[[v5-33-14]]

^<<v5-33-14,14>>^ Que Deus dê a essas terras frutas amadurecidas pelo sol e as abençoe com boas colheitas!

[[v5-33-15]]

^<<v5-33-15,15>>^ Que os montes antigos produzam ricas colheitas!

[[v5-33-16]]

^<<v5-33-16,16>>^ Que Deus abençoe a terra e tudo o que há nela, dando-lhe tudo o que é bom! Que o Deus que apareceu no espinheiro em fogo seja sempre bondoso para com eles! Que todas essas bênçãos venham sobre a tribo de José, pois ele foi o mais importante dos seus irmãos!

[[v5-33-17]]

^<<v5-33-17,17>>^ Ele tem a beleza de um touro novo e chifres como os de um boi selvagem. Os seus chifres são os milhares de pessoas da tribo de Manassés e os milhares e milhares da tribo de Efraim . Com eles José ataca os seus inimigos e os persegue pelo mundo inteiro."

[[v5-33-18]]

^<<v5-33-18,18>>^ A respeito das tribos de Zebulom e de Issacar foi isto o que Moisés disse: "Que Zebulom fique rico no comércio com outros países, e Issacar enriqueça negociando dentro do país!

[[v5-33-19]]

^<<v5-33-19,19>>^ Eles convidam os povos para virem à sua montanha e ali oferecem os sacrifícios aceitáveis a Deus. Eles aproveitam os enormes recursos do mar e as riquezas das suas praias."

[[v5-33-20]]

^<<v5-33-20,20>>^ A respeito da tribo de Gade ele disse: "Bendito seja Deus, que aumentou as terras de Gade! O povo de Gade espera como um leão para arrancar do inimigo um braço ou mesmo a cabeça.

[[v5-33-21]]

^<<v5-33-21,21>>^ Eles ficaram com a melhor parte da Terra Prometida ; foi-lhes dada a parte que cabe ao chefe. Obedeceram às leis e aos mandamentos do Senhor , quando os líderes do povo se reuniram."

[[v5-33-22]]

^<<v5-33-22,22>>^ A respeito da tribo de Dã ele disse: "Dã é como um leãozinho que vive saltando na terra de Basã."

[[v5-33-23]]

^<<v5-33-23,23>>^ A respeito da tribo de Naftali ele disse: "Deus abençoou ricamente o povo de Naftali; as suas terras vão desde o lago da Galileia até o Sul."

[[v5-33-24]]

^<<v5-33-24,24>>^ A respeito da tribo de Aser ele disse: "De todas as tribos Aser é a mais abençoada. Que o povo de Aser seja muito querido pelas outras tribos, e que nas suas terras haja muitas oliveiras!

[[v5-33-25]]

^<<v5-33-25,25>>^ Que as suas cidades sejam protegidas com portões de ferro, e que os seus moradores vivam sempre em paz!"

[[v5-33-26]]

^<<v5-33-26,26>>^ Povo de Israel, não há outro deus como o nosso Deus! Forte e majestoso, ele atravessa os céus e, montado sobre as nuvens, ele vem nos socorrer.

[[v5-33-27]]

^<<v5-33-27,27>>^ O Deus Eterno é o nosso protetor; ele sempre nos protege com os seus braços. Na nossa presença Deus expulsou os inimigos e mandou que os destruíssemos.

[[v5-33-28]]

^<<v5-33-28,28>>^ O povo de Israel vive sempre seguro, vive em paz numa terra que produz cereais e vinho, onde o orvalho rega o chão.

[[v5-33-29]]

^<<v5-33-29,29>>^ Povo de Israel, como você é feliz! Não há ninguém como você, o povo que o Senhor  Deus salvou. Ele é o seu escudo  e a sua espada, para dar proteção e vitória a você. Israel, os seus inimigos se ajoelharão pedindo misericórdia, e você tomará posse das suas terras.

'''

xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[Próximo Capítulo &#62;]