include::./index.adoc[]

[[v5-13-0]]
=== Deuteronômio, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-13-1]]

^<<v5-13-1,1>>^ — Se aparecer no meio de vocês um profeta  ou alguém que explique sonhos, dizendo que vai acontecer um milagre ou outra coisa espantosa,

[[v5-13-2]]

^<<v5-13-2,2>>^ e, se acontecer aquilo que ele disse, então ele vai procurar levá-los a adorar e servir deuses que vocês não conheciam.

[[v5-13-3]]

^<<v5-13-3,3>>^ Mas não deem atenção a esse profeta ou a essa pessoa que explica sonhos. Pois é assim que o Senhor , nosso Deus, vai pôr vocês à prova, para ver se, de fato, o amam com todo o coração e com toda a alma.

[[v5-13-4]]

^<<v5-13-4,4>>^ Sigam as leis  do Senhor , nosso Deus; temam a Deus , obedeçam aos seus mandamentos e deem atenção a tudo o que ele diz. Adorem somente a Deus e fiquem ligados com ele.

[[v5-13-5]]

^<<v5-13-5,5>>^ E o profeta ou o explicador de sonhos que procurou levá-los a se revoltarem contra Deus será morto. Pois ele procurou desviá-los do caminho indicado pelo Senhor , o Deus que livrou vocês do Egito, onde eram escravos. Matem esse falso profeta e assim tirarão o mal do meio do povo.

[[v5-13-6]]

^<<v5-13-6,6>>^ — Talvez chegue perto de você o seu irmão, ou o seu filho, ou a sua filha, ou a sua querida esposa, ou o seu melhor amigo, procurando em segredo levá-lo a adorar outros deuses que nem você nem os seus antepassados adoravam.

[[v5-13-7]]

^<<v5-13-7,7>>^ Essa pessoa pode procurar levá-lo a adorar os deuses de povos vizinhos ou de povos que vivem longe, em lugares distantes.

[[v5-13-8]]

^<<v5-13-8,8>>^ Não deixe que essa pessoa o convença, nem escute o que ela disser. Não tenha dó nem piedade dela e não procure protegê-la.

[[v5-13-9]]

^<<v5-13-9,9>>^ Mate essa pessoa a pedradas; atire a primeira pedra, e, depois, que todos os outros atirem pedras também.

[[v5-13-10]]

^<<v5-13-10,10>>^ Assim vocês matarão essa pessoa, pois procurou fazer vocês abandonarem o Senhor , nosso Deus, que os livrou do Egito, onde eram escravos.

[[v5-13-11]]

^<<v5-13-11,11>>^ Todo o povo de Israel saberá do que aconteceu; todos ficarão com medo, e ninguém vai querer fazer uma coisa tão má como essa no meio do povo.

[[v5-13-12]]

^<<v5-13-12,12>>^ — Quando vocês estiverem morando nas cidades da terra que o Senhor , nosso Deus, vai lhes dar, talvez vocês ouçam dizer

[[v5-13-13]]

^<<v5-13-13,13>>^ que em certa cidade alguns homens perversos levaram os moradores a adorar deuses que vocês nunca adoraram.

[[v5-13-14]]

^<<v5-13-14,14>>^ Aí vocês deverão examinar o caso com todo o cuidado. Se ficar provado que, de fato, foi cometido um pecado tão grave no meio do povo de Israel,

[[v5-13-15]]

^<<v5-13-15,15>>^ então vocês deverão matar à espada todos os moradores daquela cidade. Matem também os animais e arrasem a cidade.

[[v5-13-16]]

^<<v5-13-16,16>>^ Depois peguem todos os objetos de valor que encontrarem, amontoem na praça e queimem tudo e também a cidade, como oferta ao Senhor , nosso Deus. Vai ficar só um montão de ruínas, e nunca mais será construída uma cidade naquele lugar.

[[v5-13-17]]

^<<v5-13-17,17>>^ Não guardem para vocês nada do que for condenado à destruição. Assim o Senhor  deixará de ficar irado  e terá pena de vocês. Deus terá compaixão e, como jurou aos nossos antepassados, fará com que vocês aumentem em número.

[[v5-13-18]]

^<<v5-13-18,18>>^ O Senhor , nosso Deus, fará isso se vocês derem atenção às suas ordens, se obedecerem a todas as suas leis que eu estou dando a vocês hoje e se fizerem aquilo que ele acha bom.

'''

xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[Próximo Capítulo &#62;]