include::./index.adoc[]

[[v5-24-0]]
=== Deuteronômio, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-24-1]]

^<<v5-24-1,1>>^ Moisés disse ao povo: — Pode acontecer que um homem case, mas depois de algum tempo não goste mais da esposa porque há nela alguma coisa que não agrada a ele. Nesse caso ele deve preparar um documento de divórcio, entregá-lo à esposa e mandá-la embora.

[[v5-24-2]]

^<<v5-24-2,2>>^ Ela irá, e então poderá acontecer que case com outro homem

[[v5-24-3]]

^<<v5-24-3,3>>^ e que este também não goste mais dela e se divorcie; ou então poderá acontecer que ele morra.

[[v5-24-4]]

^<<v5-24-4,4>>^ Em qualquer um desses casos, o primeiro marido não poderá casar de novo com essa mulher; ela é impura  para ele. Casar de novo com ela seria uma ofensa contra Deus, o Senhor . Portanto, não deixem que se cometa um pecado tão grave assim na terra que o Senhor , nosso Deus, lhes está dando para ser de vocês.

[[v5-24-5]]

^<<v5-24-5,5>>^ — Um homem que tenha casado há pouco tempo ficará livre por um ano do serviço militar e de qualquer outro serviço público. Ele tem o direito de ficar em casa um ano, fazendo com que a sua esposa se sinta feliz.

[[v5-24-6]]

^<<v5-24-6,6>>^ — Quando você emprestar alguma coisa a alguém, não aceite como garantia de pagamento as duas pedras de moinho que ele usa para moer o trigo e não pegue nem mesmo só a pedra de cima; pois, se ele não tiver as duas, não poderá moer o trigo e assim morrerá de fome.

[[v5-24-7]]

^<<v5-24-7,7>>^ — Se alguém raptar outro israelita e obrigá-lo a ser seu escravo ou o vender, esse criminoso será morto. Assim vocês tirarão o mal do meio do povo de Israel.

[[v5-24-8]]

^<<v5-24-8,8>>^ — Se você ficar com uma doença contagiosa da pele, siga com todo o cuidado as instruções dos sacerdotes levitas . Obedeça a todas as ordens que eu dei a eles.

[[v5-24-9]]

^<<v5-24-9,9>>^ Não esqueça aquilo que o Senhor , nosso Deus, fez com Míriam quando estávamos saindo do Egito.

[[v5-24-10]]

^<<v5-24-10,10>>^ — Quando você emprestar alguma coisa a outro israelita, e ele prometer como garantia de pagamento a capa  de dormir, não entre na casa dele a fim de pegar a capa,

[[v5-24-11]]

^<<v5-24-11,11>>^ mas espere lá fora até que ele a traga para você.

[[v5-24-12]]

^<<v5-24-12,12>>^ Se ele for pobre, não fique com a capa durante a noite;

[[v5-24-13]]

^<<v5-24-13,13>>^ devolva-a ao dono antes do pôr do sol, para que a use como cobertor. Ele ficará agradecido, e você terá feito aquilo que o Senhor , nosso Deus, acha certo.

[[v5-24-14]]

^<<v5-24-14,14>>^ — Não explore o empregado pobre e humilde, que é pago por dia, seja ele israelita ou um estrangeiro que mora na cidade onde você vive.

[[v5-24-15]]

^<<v5-24-15,15>>^ Pague o salário dele no mesmo dia, antes do pôr do sol, pois ele é pobre e espera ansioso pelo dinheiro. Se você não pagar, ele gritará a Deus, o Senhor , contra você, e você será culpado de pecado.

[[v5-24-16]]

^<<v5-24-16,16>>^ — Os pais não serão mortos por causa de crimes cometidos pelos filhos, nem os filhos por causa de crimes cometidos pelos pais; uma pessoa será morta somente como castigo pelo crime que ela mesma cometeu.

[[v5-24-17]]

^<<v5-24-17,17>>^ — Respeitem os direitos dos órfãos e dos estrangeiros que moram nas cidades de vocês. Não aceitem como garantia de pagamento de uma dívida a roupa da viúva a quem vocês emprestaram alguma coisa.

[[v5-24-18]]

^<<v5-24-18,18>>^ Lembrem que vocês foram escravos no Egito e que o Senhor , nosso Deus, os tirou dali. Por isso eu exijo que obedeçam a essa lei .

[[v5-24-19]]

^<<v5-24-19,19>>^ — Pode acontecer que na colheita do trigo ou da cevada  você esqueça de pegar um feixe de espigas; nesse caso, não volte para pegá-lo, mas deixe-o lá no campo para os estrangeiros, para os órfãos e para as viúvas. Assim o Senhor , nosso Deus, abençoará tudo o que você fizer.

[[v5-24-20]]

^<<v5-24-20,20>>^ Na colheita das azeitonas, depois que você sacudir as oliveiras, não volte para pegar as azeitonas que ficaram nas árvores; deixe-as para os estrangeiros, para os órfãos e para as viúvas.

[[v5-24-21]]

^<<v5-24-21,21>>^ E faça só uma colheita de uvas nas suas plantações; as uvas que ficarem nos pés serão deixadas para os estrangeiros, para os órfãos e para as viúvas.

[[v5-24-22]]

^<<v5-24-22,22>>^ Lembrem que vocês foram escravos no Egito; é por isso que eu exijo que obedeçam a essa lei.

'''

xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[&#60; Capítulo Anterior] | <<v5-24-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[Próximo Capítulo &#62;]