include::./index.adoc[]

[[v5-32-0]]
=== Deuteronômio, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v5-32-1]]

^<<v5-32-1,1>>^ Escutem, ó céu e terra, e deem atenção às minhas palavras.

[[v5-32-2]]

^<<v5-32-2,2>>^ Que o meu ensino seja como a chuva que cai mansamente sobre a terra; que as minhas palavras sejam como o orvalho que se espalha sobre as plantas.

[[v5-32-3]]

^<<v5-32-3,3>>^ Eu louvarei o nome do Senhor . Anunciem a grandeza do nosso Deus!

[[v5-32-4]]

^<<v5-32-4,4>>^ O Senhor  é a nossa rocha; ele é perfeito e justo em tudo o que faz. Ele é fiel e correto e julga com justiça e honestidade.

[[v5-32-5]]

^<<v5-32-5,5>>^ Mas o seu povo se entregou ao pecado e por isso eles não merecem ser filhos dele. São gente pecadora e má.

[[v5-32-6]]

^<<v5-32-6,6>>^ Povo sem juízo e sem sabedoria, é assim que tratam o Senhor  Deus? Ele é o seu Pai, que os criou; foi ele quem fundou e firmou a nação de vocês.

[[v5-32-7]]

^<<v5-32-7,7>>^ Lembrem do passado, daquilo que aconteceu há muitos anos. Perguntem aos seus pais o que foi que aconteceu e peçam aos velhos que lhes contem o que se passou.

[[v5-32-8]]

^<<v5-32-8,8>>^ Quando o Altíssimo separou os povos e deu a cada povo as suas terras, ele marcou as fronteiras das nações, dando a cada uma o seu próprio deus.

[[v5-32-9]]

^<<v5-32-9,9>>^ Mas escolheu Israel para ser o seu povo; os descendentes de Jacó pertencem ao Senhor .

[[v5-32-10]]

^<<v5-32-10,10>>^ Deus os encontrou perdidos no deserto, numa região onde viviam animais ferozes. Chegou perto, cuidou deles e os protegeu como se fossem a menina dos seus olhos.

[[v5-32-11]]

^<<v5-32-11,11>>^ Como a águia ensina os filhotes a voar e com as asas estendidas os pega quando estão caindo, assim o Senhor  Deus cuida do seu povo.

[[v5-32-12]]

^<<v5-32-12,12>>^ Ele os guiou sozinho, sem a ajuda de outro deus.

[[v5-32-13]]

^<<v5-32-13,13>>^ O Senhor  deixou que o seu povo dominasse as montanhas, e eles se alimentaram das plantações dos campos. Deu-lhes mel de abelhas nos rochedos e fez com que as oliveiras produzissem em terreno cheio de pedras.

[[v5-32-14]]

^<<v5-32-14,14>>^ Alimentou-os com leite de vaca e de cabra, deu-lhes a carne dos melhores carneirinhos, carneiros e bodes, o melhor trigo e o vinho mais fino.

[[v5-32-15]]

^<<v5-32-15,15>>^ O povo escolhido ficou rico, mas se revoltou contra Deus. Enriqueceu, progrediu, ficou satisfeito, mas abandonou a Deus, o seu Criador, e rejeitou o seu protetor e Salvador.

[[v5-32-16]]

^<<v5-32-16,16>>^ Com os seus deuses falsos eles provocaram a Deus, adoraram ídolos nojentos, e por isso ele ficou irado .

[[v5-32-17]]

^<<v5-32-17,17>>^ Ofereceram sacrifícios  aos demônios, a deuses falsos que não haviam adorado antes, novos deuses que os seus antepassados não conheciam.

[[v5-32-18]]

^<<v5-32-18,18>>^ Esqueceram o seu protetor; desprezaram o seu Pai e Criador.

[[v5-32-19]]

^<<v5-32-19,19>>^ O Senhor  Deus viu isso, ficou irado e rejeitou os seus filhos e filhas.

[[v5-32-20]]

^<<v5-32-20,20>>^ Ele disse: "Eu os abandonarei e então verei o que vai acontecer com eles, pois são um povo rebelde, são filhos desobedientes.

[[v5-32-21]]

^<<v5-32-21,21>>^ Com as suas imagens provocaram a minha ira, e fiquei com ciúmes dos seus deuses falsos. Portanto, eu farei com que eles fiquem com ciúmes de um povo que não é nação; e, com gente sem juízo, eu provocarei a ira deles.

[[v5-32-22]]

^<<v5-32-22,22>>^ A minha ira se acenderá como fogo e acabará com tudo o que há na terra; ela queimará até o mundo dos mortos e incendiará as bases das montanhas.

[[v5-32-23]]

^<<v5-32-23,23>>^ "Farei cair sobre eles desgraças sem fim e os ferirei com muitos sofrimentos.

[[v5-32-24]]

^<<v5-32-24,24>>^ A fome os matará, febres e doenças sem cura os destruirão. Mandarei animais selvagens para atacá-los e cobras venenosas para picá-los.

[[v5-32-25]]

^<<v5-32-25,25>>^ Fora de casa morrerão na guerra e dentro de casa morrerão de medo. Serão mortos os moços e as moças, as crianças e os velhos também.

[[v5-32-26]]

^<<v5-32-26,26>>^ Eu os poderia ter espalhado pelo mundo inteiro, e todos os esqueceriam.

[[v5-32-27]]

^<<v5-32-27,27>>^ Porém eu não queria que os seus inimigos zombassem e mentissem, dizendo que haviam derrotado o meu povo, afirmando que não fui eu, o Senhor  Deus, quem os destruiu."

[[v5-32-28]]

^<<v5-32-28,28>>^ Israel é um povo sem juízo, um povo que não entende nada.

[[v5-32-29]]

^<<v5-32-29,29>>^ Se eles fossem sábios, entenderiam por que foram derrotados, saberiam qual a razão do seu castigo.

[[v5-32-30]]

^<<v5-32-30,30>>^ Por que foi que mil deles fugiram de um só inimigo, e dez mil foram perseguidos por dois? Foi porque o seu protetor os abandonou; o Senhor  Deus os vendeu aos inimigos.

[[v5-32-31]]

^<<v5-32-31,31>>^ Os deuses dos nossos inimigos não são tão poderosos como o nosso Deus; os próprios inimigos dizem isso.

[[v5-32-32]]

^<<v5-32-32,32>>^ Eles são tão maus como a gente de Sodoma e Gomorra; são como parreiras  que dão uvas que não prestam, uvas amargas e venenosas;

[[v5-32-33]]

^<<v5-32-33,33>>^ são como vinho feito de veneno de cobra, do veneno mortal das serpentes.

[[v5-32-34]]

^<<v5-32-34,34>>^ Deus lembra daquilo que os inimigos fizeram e espera o tempo certo para castigá-los.

[[v5-32-35]]

^<<v5-32-35,35>>^ Deus se vingará; ele acertará contas com eles. Virá o tempo em que os inimigos cairão; o dia da desgraça deles está chegando depressa.

[[v5-32-36]]

^<<v5-32-36,36>>^ O Senhor  Deus terá pena do seu povo quando vir que eles estão fracos. Ele salvará aqueles que o servem, pois todos eles foram derrotados.

[[v5-32-37]]

^<<v5-32-37,37>>^ Então ele perguntará ao seu povo: "Onde estão os seus deuses? Onde está o protetor em quem vocês confiavam?

[[v5-32-38]]

^<<v5-32-38,38>>^ Vocês lhes ofereciam sacrifícios e lhes davam animais e vinho. Pois que agora eles os ajudem, que eles venham socorrê-los!

[[v5-32-39]]

^<<v5-32-39,39>>^ "Saibam todos que eu, somente eu, sou Deus; não há outro deus além de mim. Eu mato e eu faço viver; eu firo e eu curo. Ninguém pode me impedir de fazer o que quero.

[[v5-32-40]]

^<<v5-32-40,40>>^ Agora levanto a mão para o céu e juro pela minha vida eterna que farei isto:

[[v5-32-41]]

^<<v5-32-41,41>>^ Afiarei a minha espada brilhante e começarei a fazer justiça. Vou me vingar dos meus inimigos e castigar os que me odeiam.

[[v5-32-42]]

^<<v5-32-42,42>>^ As minhas flechas ficarão manchadas de sangue, e a minha espada matará os meus inimigos. Não escapará nenhum dos que lutam contra mim; até os prisioneiros serão mortos."

[[v5-32-43]]

^<<v5-32-43,43>>^ Que todas as nações louvem o povo de Deus! Deus se vingará dos que mataram os seus servos . Ele se vingará dos seus inimigos e perdoará os pecados do seu povo.

[[v5-32-44]]

^<<v5-32-44,44>>^ Moisés e Josué, filho de Num, recitaram essa canção inteira na presença do povo.

[[v5-32-45]]

^<<v5-32-45,45>>^ Moisés acabou de ensinar ao povo de Israel toda a lei  de Deus

[[v5-32-46]]

^<<v5-32-46,46>>^ e então disse: — Pensem bem em tudo o que lhes ensinei hoje e mandem que os seus filhos obedeçam a tudo o que está escrito nesta Lei de Deus.

[[v5-32-47]]

^<<v5-32-47,47>>^ Não pensem que esta Lei não vale nada; pelo contrário, é ela que lhes dará vida. Se vocês obedecerem a esta Lei, viverão muitos anos na terra que estão para possuir no outro lado do rio Jordão.

[[v5-32-48]]

^<<v5-32-48,48>>^ Naquele mesmo dia o Senhor  Deus disse a Moisés:

[[v5-32-49]]

^<<v5-32-49,49>>^ — Vá até a serra de Abarim, aqui na terra de Moabe, e suba o monte Nebo, na altura de Jericó, que fica do outro lado do rio. Lá de cima você verá a terra de Canaã, que estou dando ao povo de Israel.

[[v5-32-50]]

^<<v5-32-50,50>>^ Você vai morrer ali no monte, como Arão, o seu irmão, morreu no monte Hor.

[[v5-32-51]]

^<<v5-32-51,51>>^ Vocês dois foram infiéis a mim diante do povo de Israel. Quando estavam perto das fontes de Meribá, não longe da cidade de Cades, no deserto de Zim, vocês dois me desrespeitaram.

[[v5-32-52]]

^<<v5-32-52,52>>^ Por isso você verá de longe a terra que eu estou dando aos israelitas, porém não entrará nela.

'''

xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[Próximo Capítulo &#62;]