include::./index.adoc[]

[[v34-1-0]]
=== Naum, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v34-1-1]]

^<<v34-1-1,1>>^ Esta é a mensagem a respeito de Nínive, que Deus, por meio de uma visão, deu a Naum, que era da cidade de Elcos.

[[v34-1-2]]

^<<v34-1-2,2>>^ O Senhor  é um Deus que não tolera outros deuses, um Deus irado  que se vinga dos seus inimigos. O Senhor  tira vingança dos seus inimigos e na sua ira os castiga.

[[v34-1-3]]

^<<v34-1-3,3>>^ O Senhor  é paciente mas poderoso e não deixa os culpados sem castigo. Ele anda pelo meio de tempestades e de ventos violentos; as nuvens são o pó que os seus pés levantam.

[[v34-1-4]]

^<<v34-1-4,4>>^ Deus repreende o mar, e ele seca; Deus faz os rios ficarem secos. Os pastos de Basã e do monte Carmelo secam, as flores dos montes Líbanos ficam murchas.

[[v34-1-5]]

^<<v34-1-5,5>>^ Na sua presença, as montanhas tremem, e os morros se desfazem. Quando ele aparece, a terra e todos os seus moradores ficam arrasados.

[[v34-1-6]]

^<<v34-1-6,6>>^ Quando o Senhor  está irado, quem pode ficar de pé? Quem pode resistir à sua ira? A sua fúria se derrama como um rio de fogo; diante dele, as pedras se arrebentam.

[[v34-1-7]]

^<<v34-1-7,7>>^ O Senhor  Deus é bom. Em tempos difíceis, ele salva o seu povo e cuida dos que procuram a sua proteção.

[[v34-1-8]]

^<<v34-1-8,8>>^ Como uma enchente, ele acaba com os seus inimigos; ele manda os seus adversários para o mundo dos mortos .

[[v34-1-9]]

^<<v34-1-9,9>>^ O que é que vocês estão planejando contra o Senhor ? Ele os destruirá completamente. Contra Deus ninguém se levanta duas vezes!

[[v34-1-10]]

^<<v34-1-10,10>>^ Como uma moita de espinheiros, como a palha seca, vocês serão completamente destruídos!

[[v34-1-11]]

^<<v34-1-11,11>>^ Da cidade de Nínive, veio o homem de más intenções, que planeja o mal contra Deus, o Senhor .

[[v34-1-12]]

^<<v34-1-12,12>>^ Portanto, o Senhor  diz ao povo de Israel: "Os assírios serão destruídos e desaparecerão, embora sejam fortes e numerosos. Eu deixei que vocês sofressem, mas não farei isso de novo.

[[v34-1-13]]

^<<v34-1-13,13>>^ Eu os salvarei do poder dos assírios; eu os livrarei da escravidão."

[[v34-1-14]]

^<<v34-1-14,14>>^ A respeito do rei da Assíria o Senhor  Deus diz o seguinte: "Ele não terá filhos, e assim o seu nome desaparecerá. Eu destruirei os ídolos e as imagens do templo do seu deus. Vou sepultá-lo, pois ele não vale nada."

[[v34-1-15]]

^<<v34-1-15,15>>^ Vejam! Pelas montanhas vem um mensageiro que traz boas notícias, notícias de paz. Povo de Judá, faça as suas festas e ofereça a Deus aquilo que você prometeu. O país de vocês nunca mais será invadido por gente má; eles foram completamente destruídos.

'''

xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[&#60; Capítulo Anterior] | <<v34-1-0,Topo>> | xref:034-naum/034-naum-002.adoc#v34-2-0[Próximo Capítulo &#62;]