include::./index.adoc[]

[[v34-2-0]]
=== Naum, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v34-2-1]]

^<<v34-2-1,1>>^ O destruidor vai atacar a cidade de Nínive. Ponham guardas nas torres e vigiem as estradas. Chamem todos os soldados e preparem-se para lutar.

[[v34-2-2]]

^<<v34-2-2,2>>^ O Senhor  Deus vai fazer voltar a glória  do povo de Israel; mais uma vez a nação será o que era antes que os inimigos levassem tudo embora e deixassem o país como uma árvore sem galhos.

[[v34-2-3]]

^<<v34-2-3,3>>^ Os soldados inimigos carregam escudos  vermelhos, e os seus uniformes são vermelhos também. Eles se preparam para atacar Nínive. Os seus carros de guerra brilham como fogo, e os cavalos estão impacientes.

[[v34-2-4]]

^<<v34-2-4,4>>^ Os carros de guerra correm rápidos pelas ruas e cruzam as praças em todas as direções. Parecem tochas acesas, correm como relâmpagos.

[[v34-2-5]]

^<<v34-2-5,5>>^ O comandante inimigo dá ordem aos seus oficiais; eles correm até a muralha da cidade e, na sua corrida, empurram uns aos outros. Eles armam barreiras para se protegerem .

[[v34-2-6]]

^<<v34-2-6,6>>^ Abrem-se as comportas do rio, e no palácio reina o terror.

[[v34-2-7]]

^<<v34-2-7,7>>^ A imagem da deusa é levada embora, e as suas sacerdotisas a acompanham chorando; elas gemem como pombas e batem no peito em sinal de tristeza.

[[v34-2-8]]

^<<v34-2-8,8>>^ O povo de Nínive foge como água que escapa de uma represa. "Parem! Parem!" — alguém grita, mas ninguém para de fugir.

[[v34-2-9]]

^<<v34-2-9,9>>^ Peguem a prata! Levem o ouro! A cidade está cheia de riquezas, há milhares de objetos de valor.

[[v34-2-10]]

^<<v34-2-10,10>>^ Nínive: destruída, deserta, despovoada! Corações cheios de medo, joelhos tremendo, rostos pálidos; todos perdem as forças.

[[v34-2-11]]

^<<v34-2-11,11>>^ O que aconteceu com a cidade que era como uma cova de leões? Ali os leõezinhos recebiam comida; os leões e os seus filhotes viviam seguros, e ninguém os espantava.

[[v34-2-12]]

^<<v34-2-12,12>>^ O leão matava algum animal e o repartia com a leoa e os filhotes; a cova ficava cheia de animais mortos.

[[v34-2-13]]

^<<v34-2-13,13>>^ O Senhor  Todo-Poderoso diz o seguinte ao povo de Nínive: — Eu estou contra vocês. Vou queimar os seus carros de guerra, e os seus soldados morrerão na batalha. Levarei embora tudo o que vocês roubaram dos outros, e nunca mais os seus embaixadores irão para outros países.

'''

xref:034-naum/034-naum-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-naum/034-naum-003.adoc#v34-3-0[Próximo Capítulo &#62;]