include::./index.adoc[]

[[v48-3-0]]
=== Gálatas, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v48-3-1]]

^<<v48-3-1,1>>^ Ó gálatas sem juízo! Quem foi que enfeitiçou vocês? Na minha pregação a vocês eu fiz uma descrição perfeita da morte de Jesus Cristo na cruz; por assim dizer, vocês viram Jesus na cruz.

[[v48-3-2]]

^<<v48-3-2,2>>^ Respondam somente isto: vocês receberam o Espírito de Deus por terem feito o que a lei  manda ou por terem ouvido a mensagem do evangelho  e terem crido nela?

[[v48-3-3]]

^<<v48-3-3,3>>^ Como é que vocês podem ter tão pouco juízo? Vocês começaram a sua vida cristã pelo poder do Espírito de Deus e agora querem ir até o fim pelas suas próprias forças?

[[v48-3-4]]

^<<v48-3-4,4>>^ Será que as coisas pelas quais vocês passaram não serviram para nada? Não é possível!

[[v48-3-5]]

^<<v48-3-5,5>>^ Será que, quando Deus dá o seu Espírito e faz milagres entre vocês, é porque vocês fazem o que a lei manda? Não será que é porque vocês ouvem a mensagem e creem nela?

[[v48-3-6]]

^<<v48-3-6,6>>^ Lembrem do que as Escrituras Sagradas  dizem a respeito de Abraão: "Ele creu em Deus, e por isso Deus o aceitou."

[[v48-3-7]]

^<<v48-3-7,7>>^ Portanto, vocês devem saber que os verdadeiros descendentes de Abraão são os que têm fé.

[[v48-3-8]]

^<<v48-3-8,8>>^ Antes que isso acontecesse, as Escrituras viram que Deus ia aceitar os não judeus por meio da fé. Por isso, antes de chegar o tempo, elas anunciaram a boa notícia a Abraão, dizendo: "Por meio de você, Deus abençoará todos os povos."

[[v48-3-9]]

^<<v48-3-9,9>>^ Abraão creu e foi abençoado; portanto, todos os que creem são abençoados como ele foi.

[[v48-3-10]]

^<<v48-3-10,10>>^ Os que confiam na sua obediência à lei estão debaixo da maldição de Deus. Pois as Escrituras Sagradas dizem: "Quem não obedece sempre a tudo o que está escrito no Livro da Lei  está debaixo da maldição de Deus."

[[v48-3-11]]

^<<v48-3-11,11>>^ É claro que ninguém é aceito por Deus por meio da lei, pois as Escrituras dizem: "Viverá aquele que, por meio da fé, é aceito por Deus."

[[v48-3-12]]

^<<v48-3-12,12>>^ Mas a lei não tem nada a ver com a fé. Pelo contrário, como dizem as Escrituras: "Viverá aquele que fizer o que a lei manda."

[[v48-3-13]]

^<<v48-3-13,13>>^ Porém Cristo, tornando-se maldição por nós, nos livrou da maldição imposta pela lei. Como dizem as Escrituras: "Maldito todo aquele que for pendurado numa cruz!"

[[v48-3-14]]

^<<v48-3-14,14>>^ Cristo fez isso para que a bênção que Deus prometeu a Abraão seja dada, por meio de Cristo Jesus, aos não judeus e para que todos nós recebamos por meio da fé o Espírito que Deus prometeu.

[[v48-3-15]]

^<<v48-3-15,15>>^ Meus irmãos, vou usar um exemplo da vida diária: quando duas pessoas combinam alguma coisa e assinam um contrato, ninguém pode quebrá-lo ou acrescentar qualquer coisa a ele.

[[v48-3-16]]

^<<v48-3-16,16>>^ Pois Deus fez as suas promessas a Abraão e ao seu descendente. Quando as Escrituras  dizem que Deus fez as suas promessas a Abraão "e à sua descendência", elas não querem dizer que se trata de muitas pessoas, mas de uma só, isto é, Cristo.

[[v48-3-17]]

^<<v48-3-17,17>>^ O que eu quero dizer é o seguinte: Deus fez uma aliança  com Abraão e prometeu cumpri-la. A lei , que foi dada quatrocentos e trinta anos depois, não pode quebrar aquela aliança, nem anular a promessa de Deus.

[[v48-3-18]]

^<<v48-3-18,18>>^ Porque, se aquilo que Deus dá depende da lei, então o que ele dá já não depende da sua promessa. Mas o que Deus deu a Abraão, ele deu porque havia prometido.

[[v48-3-19]]

^<<v48-3-19,19>>^ Então, por que é que foi dada a lei? Ela foi dada para mostrar as coisas que são contra a vontade de Deus. A lei devia durar até que viesse o descendente de Abraão, pois a promessa foi feita a esse descendente. A lei foi entregue por anjos, e um homem serviu de intermediário.

[[v48-3-20]]

^<<v48-3-20,20>>^ Porém não é preciso haver intermediário quando se está falando de uma só pessoa; e Deus é um só.

[[v48-3-21]]

^<<v48-3-21,21>>^ Será que isso quer dizer que a lei  é contra as promessas de Deus? É claro que não! Porque, se tivesse sido dada uma lei que pudesse dar vida às pessoas, então elas seriam aceitas por Deus por obedecerem a ela.

[[v48-3-22]]

^<<v48-3-22,22>>^ Porém as Escrituras Sagradas  afirmam que o mundo inteiro está dominado pelo pecado, e isso para que as pessoas que creem recebam o que Deus promete aos que têm fé em Jesus Cristo.

[[v48-3-23]]

^<<v48-3-23,23>>^ Mas, antes que chegasse o tempo da fé, nós éramos prisioneiros da lei, até que fosse revelada a fé que devia vir.

[[v48-3-24]]

^<<v48-3-24,24>>^ Assim, a lei ficou tomando conta de nós até que Cristo viesse para podermos ser aceitos por Deus por meio da fé.

[[v48-3-25]]

^<<v48-3-25,25>>^ Agora que chegou o tempo da fé, não precisamos mais da lei para tomar conta de nós.

[[v48-3-26]]

^<<v48-3-26,26>>^ Pois, por meio da fé em Cristo Jesus, todos vocês são filhos de Deus.

[[v48-3-27]]

^<<v48-3-27,27>>^ Porque vocês foram batizados para ficarem unidos com Cristo e assim se revestiram com as qualidades do próprio Cristo.

[[v48-3-28]]

^<<v48-3-28,28>>^ Desse modo não existe diferença entre judeus e não judeus, entre escravos e pessoas livres, entre homens e mulheres: todos vocês são um só por estarem unidos com Cristo Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ E, já que vocês pertencem a Cristo, então são descendentes de Abraão e receberão aquilo que Deus prometeu.

'''

xref:048-galatas/048-galatas-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatas/048-galatas-004.adoc#v48-4-0[Próximo Capítulo &#62;]