include::./index.adoc[]

[[v48-4-0]]
=== Gálatas, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v48-4-1]]

^<<v48-4-1,1>>^ Digo mais isto: enquanto é menor de idade, o filho que vai herdar a propriedade do pai é tratado como escravo, mesmo sendo, de fato, o dono de tudo.

[[v48-4-2]]

^<<v48-4-2,2>>^ Enquanto é menor, há pessoas que tomam conta dele e cuidam dos seus negócios até o tempo marcado pelo pai.

[[v48-4-3]]

^<<v48-4-3,3>>^ Assim também nós, antes de ficarmos adultos espiritualmente, fomos escravos dos poderes espirituais que dominam o mundo .

[[v48-4-4]]

^<<v48-4-4,4>>^ Mas, quando chegou o tempo certo, Deus enviou o seu próprio Filho, que veio como filho de mãe humana e viveu debaixo da lei

[[v48-4-5]]

^<<v48-4-5,5>>^ para libertar os que estavam debaixo da lei, a fim de que nós pudéssemos nos tornar filhos de Deus.

[[v48-4-6]]

^<<v48-4-6,6>>^ E, para mostrar que vocês são seus filhos, Deus enviou o Espírito do seu Filho ao nosso coração, o Espírito que exclama: "Pai, meu Pai."

[[v48-4-7]]

^<<v48-4-7,7>>^ Assim vocês não são mais escravos; vocês são filhos. E, já que são filhos, Deus lhes dará tudo o que ele tem para dar aos seus filhos.

[[v48-4-8]]

^<<v48-4-8,8>>^ No passado vocês não conheciam a Deus e por isso eram escravos de deuses que, de fato, não são deuses.

[[v48-4-9]]

^<<v48-4-9,9>>^ Mas, agora que vocês conhecem a Deus, ou melhor, agora que Deus os conhece, como é que vocês querem voltar para aqueles poderes espirituais fracos e sem valor? Por que querem se tornar escravos deles outra vez?

[[v48-4-10]]

^<<v48-4-10,10>>^ Por que dão tanta importância a certos dias, meses, estações e anos?

[[v48-4-11]]

^<<v48-4-11,11>>^ Estou muito preocupado com vocês! Será que todo o trabalho que tive com vocês não valeu nada?

[[v48-4-12]]

^<<v48-4-12,12>>^ Meus irmãos, peço que sejam como eu. Afinal eu sou como vocês, e vocês não me ofenderam em nada.

[[v48-4-13]]

^<<v48-4-13,13>>^ Lembram por que foi que lhes anunciei pela primeira vez o evangelho ? Foi porque eu estava doente.

[[v48-4-14]]

^<<v48-4-14,14>>^ Mas vocês não me desprezaram, nem me rejeitaram, embora o meu estado de saúde fosse uma dura prova para vocês. Pelo contrário, vocês me receberam como se eu fosse um anjo de Deus ou mesmo como se eu fosse Cristo Jesus.

[[v48-4-15]]

^<<v48-4-15,15>>^ E como vocês estavam felizes! Eu posso afirmar que, se pudessem, vocês teriam arrancado os seus próprios olhos para me dar! O que foi que aconteceu?

[[v48-4-16]]

^<<v48-4-16,16>>^ Será que agora, por ter dito a verdade, eu me tornei inimigo de vocês?

[[v48-4-17]]

^<<v48-4-17,17>>^ Esses homens mostram grande interesse por vocês, mas a intenção deles não é boa. O que eles querem é separar vocês de mim para que vocês sintam por eles o mesmo interesse que eles sentem por vocês.

[[v48-4-18]]

^<<v48-4-18,18>>^ É bom vocês terem um interesse sincero sempre e não somente quando estou com vocês.

[[v48-4-19]]

^<<v48-4-19,19>>^ Meus queridos filhos, eu estou sofrendo por vocês, como uma mulher que tem dores de parto. E continuarei sofrendo até que Cristo esteja vivendo em vocês.

[[v48-4-20]]

^<<v48-4-20,20>>^ Como eu gostaria de estar aí agora para poder falar com vocês de modo diferente! Estou muito preocupado com vocês.

[[v48-4-21]]

^<<v48-4-21,21>>^ Vocês que querem estar debaixo da lei , me digam uma coisa: vocês não estão ouvindo o que a Lei diz?

[[v48-4-22]]

^<<v48-4-22,22>>^ Ela diz que Abraão teve dois filhos: um, de uma escrava, Agar; e outro, de uma mulher livre, Sara.

[[v48-4-23]]

^<<v48-4-23,23>>^ O filho da escrava foi gerado como todas as crianças são geradas, mas o filho da mulher livre foi gerado por causa da promessa de Deus.

[[v48-4-24]]

^<<v48-4-24,24>>^ Isto serve como um símbolo: as duas mulheres representam as duas alianças . Uma aliança é a do monte Sinai e está representada por Agar. Os que são dessa aliança nascem escravos.

[[v48-4-25]]

^<<v48-4-25,25>>^ Pois Agar representa o monte Sinai, na Arábia, e Agar é o símbolo da Jerusalém atual, que é escrava com todo o seu povo.

[[v48-4-26]]

^<<v48-4-26,26>>^ Mas a Jerusalém celestial é livre e ela é a nossa mãe.

[[v48-4-27]]

^<<v48-4-27,27>>^ Pois as Escrituras Sagradas  dizem: "Você, mulher que nunca teve filhos, fique alegre! Você que nunca sentiu dores de parto, grite de alegria! Pois a mulher abandonada terá mais filhos do que a que mora com o marido."

[[v48-4-28]]

^<<v48-4-28,28>>^ Meus irmãos, vocês são como Isaque; são filhos de Deus por causa da promessa divina.

[[v48-4-29]]

^<<v48-4-29,29>>^ Naquela época o filho que havia sido gerado como todas as crianças são geradas perseguiu o que havia sido gerado por causa do Espírito de Deus; e a mesma coisa está acontecendo agora.

[[v48-4-30]]

^<<v48-4-30,30>>^ Mas o que é que as Escrituras Sagradas dizem? Elas dizem: "Mande embora a escrava e o filho dela, pois o filho da escrava não herdará a propriedade do pai, junto com o filho da mulher livre."

[[v48-4-31]]

^<<v48-4-31,31>>^ Portanto, meus irmãos, nós não somos filhos de uma escrava, mas de uma mulher livre.

'''

xref:048-galatas/048-galatas-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-galatas/048-galatas-005.adoc#v48-5-0[Próximo Capítulo &#62;]