include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v48-5-1]]

^<<v48-5-1,1>>^ Cristo nos libertou para que nós sejamos realmente livres. Por isso, continuem firmes como pessoas livres e não se tornem escravos novamente.

[[v48-5-2]]

^<<v48-5-2,2>>^ Prestem atenção! Eu, Paulo, afirmo que, se vocês deixarem que os circuncidem  , então Cristo não tem nenhum valor para vocês.

[[v48-5-3]]

^<<v48-5-3,3>>^ Repito isto mais uma vez para qualquer homem que deixar que o circuncidem: esse homem é obrigado a obedecer a toda a lei .

[[v48-5-4]]

^<<v48-5-4,4>>^ Vocês que querem que Deus os aceite porque obedecem à lei estão separados de Cristo e não têm a graça  de Deus.

[[v48-5-5]]

^<<v48-5-5,5>>^ Mas nós temos a esperança de que Deus nos aceitará, e é isso o que esperamos pelo poder do Espírito de Deus, que age por meio da nossa fé.

[[v48-5-6]]

^<<v48-5-6,6>>^ Pois, quando estamos unidos com Cristo Jesus, não faz diferença nenhuma estar ou não estar circuncidado. O que importa é a fé que age por meio do amor.

[[v48-5-7]]

^<<v48-5-7,7>>^ Vocês estavam indo tão bem! Quem convenceu vocês a deixarem de seguir a verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ É claro que quem os convenceu não foi Deus, que os chamou .

[[v48-5-9]]

^<<v48-5-9,9>>^ Como dizem por aí: "Um pouco de fermento fermenta toda a massa."

[[v48-5-10]]

^<<v48-5-10,10>>^ Mas eu ainda tenho confiança em vocês. A nossa união com o Senhor me dá a certeza de que vocês voltarão a pensar da maneira certa. E também tenho certeza de que o homem que está perturbando vocês, seja ele quem for, será castigado por Deus.

[[v48-5-11]]

^<<v48-5-11,11>>^ Porém, irmãos, se é verdade que eu continuo a anunciar que a circuncisão é necessária, por que é que sou perseguido? Se eu anunciasse isso, então a minha pregação a respeito da cruz de Cristo não causaria dificuldade para ninguém.

[[v48-5-12]]

^<<v48-5-12,12>>^ E, quanto a esses homens que andam perturbando vocês, eu gostaria que se castrassem de uma vez!

[[v48-5-13]]

^<<v48-5-13,13>>^ Porém vocês, irmãos, foram chamados para serem livres. Mas não deixem que essa liberdade se torne uma desculpa para permitir que a natureza humana domine vocês. Pelo contrário, que o amor faça com que vocês sirvam uns aos outros.

[[v48-5-14]]

^<<v48-5-14,14>>^ Pois a lei inteira se resume em um mandamento só: "Ame os outros como você ama a você mesmo."

[[v48-5-15]]

^<<v48-5-15,15>>^ Mas, se vocês agem como animais selvagens, ferindo e prejudicando uns aos outros, então cuidado para não acabarem se matando!

[[v48-5-16]]

^<<v48-5-16,16>>^ Quero dizer a vocês o seguinte: deixem que o Espírito de Deus dirija a vida de vocês e não obedeçam aos desejos da natureza humana.

[[v48-5-17]]

^<<v48-5-17,17>>^ Porque o que a nossa natureza humana quer é contra o que o Espírito quer, e o que o Espírito quer é contra o que a natureza humana quer. Os dois são inimigos, e por isso vocês não podem fazer o que vocês querem.

[[v48-5-18]]

^<<v48-5-18,18>>^ Porém, se é o Espírito de Deus que guia vocês, então vocês não estão debaixo da lei .

[[v48-5-19]]

^<<v48-5-19,19>>^ As coisas que a natureza humana produz são bem-conhecidas. Elas são: a imoralidade sexual, a impureza, as ações indecentes,

[[v48-5-20]]

^<<v48-5-20,20>>^ a adoração de ídolos, as feitiçarias, as inimizades, as brigas, as ciumeiras, os acessos de raiva, a ambição egoísta, a desunião, as divisões,

[[v48-5-21]]

^<<v48-5-21,21>>^ as invejas, as bebedeiras, as farras e outras coisas parecidas com essas. Repito o que já disse: os que fazem essas coisas não receberão o Reino de Deus .

[[v48-5-22]]

^<<v48-5-22,22>>^ Mas o Espírito de Deus produz o amor, a alegria, a paz, a paciência, a delicadeza, a bondade, a fidelidade,

[[v48-5-23]]

^<<v48-5-23,23>>^ a humildade e o domínio próprio. E contra essas coisas não existe lei.

[[v48-5-24]]

^<<v48-5-24,24>>^ As pessoas que pertencem a Cristo Jesus crucificaram a natureza humana delas, junto com todas as paixões e desejos dessa natureza.

[[v48-5-25]]

^<<v48-5-25,25>>^ Que o Espírito de Deus, que nos deu a vida, controle também a nossa vida!

[[v48-5-26]]

^<<v48-5-26,26>>^ Nós não devemos ser orgulhosos, nem provocar ninguém, nem ter inveja uns dos outros.

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]