include::./index.adoc[]

[[v21-8-0]]
=== Eclesiastes, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-8-1]]

^<<v21-8-1,1>>^ Somente os sábios conseguem explicar as coisas. A sabedoria de uma pessoa brilha no seu rosto e a torna simpática mesmo que seja feia.

[[v21-8-2]]

^<<v21-8-2,2>>^ Obedeça às ordens do rei porque você, na presença de Deus, jurou ser fiel a ele.

[[v21-8-3]]

^<<v21-8-3,3>>^ O rei pode fazer tudo o que quiser. Não tenha pressa em sair da presença dele e não insista em fazer uma coisa errada.

[[v21-8-4]]

^<<v21-8-4,4>>^ O rei age com autoridade, e ninguém pode reclamar do que ele faz.

[[v21-8-5]]

^<<v21-8-5,5>>^ Enquanto você obedecer às ordens dele, nenhum mal lhe acontecerá. A pessoa que tem sabedoria sabe como e quando agir.

[[v21-8-6]]

^<<v21-8-6,6>>^ Existe um tempo certo e um modo certo de fazer cada coisa. Mas o nosso grande problema

[[v21-8-7]]

^<<v21-8-7,7>>^ é que não sabemos o que vai acontecer amanhã, e não há ninguém que possa nos contar.

[[v21-8-8]]

^<<v21-8-8,8>>^ Ninguém pode dominar o vento, nem segurá-lo. Assim também ninguém pode evitar a morte, nem deixá-la para outro dia. Nós temos de enfrentar essa batalha, e não há jeito de escapar.

[[v21-8-9]]

^<<v21-8-9,9>>^ Eu vi tudo isso quando pensei nas coisas que acontecem neste mundo. Houve um tempo em que alguns tinham o poder, e outros sofriam, dominados por eles.

[[v21-8-10]]

^<<v21-8-10,10>>^ Eu vi o sepultamento de pessoas más. Na volta do cemitério, notei que eram elogiadas, e isso na mesma cidade onde haviam feito o mal. Isso também é ilusão.

[[v21-8-11]]

^<<v21-8-11,11>>^ Por que será que as pessoas cometem crimes com tanta facilidade? É porque os criminosos não são castigados logo.

[[v21-8-12]]

^<<v21-8-12,12>>^ Um criminoso pode cometer cem crimes e continuar a viver. Sim, eu sei que dizem: "Se você temer a Deus , tudo lhe correrá bem;

[[v21-8-13]]

^<<v21-8-13,13>>^ mas não correrá bem para os maus. A vida deles passa como a sombra: morrerão jovens porque não temem a Deus."

[[v21-8-14]]

^<<v21-8-14,14>>^ Mas isso não tem sentido. Vejam o que acontece no mundo: muitas vezes os bons são castigados, e não os maus; e os maus são premiados, e não os bons. É o que digo: isso também é ilusão.

[[v21-8-15]]

^<<v21-8-15,15>>^ Por isso, estou convencido de que devemos nos divertir porque o único prazer que temos nesta vida é comer, beber e nos divertir. Podemos fazer pelo menos isso enquanto trabalhamos durante a vida que Deus nos deu neste mundo.

[[v21-8-16]]

^<<v21-8-16,16>>^ Todas as vezes que tentei me tornar sábio e entender o que acontece neste mundo, compreendi que a gente pode ficar acordado dia e noite

[[v21-8-17]]

^<<v21-8-17,17>>^ e mesmo assim nunca será capaz de entender o que Deus faz. Por mais que a gente se esforce, nunca entende. Os sábios podem dizer que conseguem compreender, mas na verdade eles também não entendem.

'''

xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[&#60; Capítulo Anterior] | <<v21-8-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[Próximo Capítulo &#62;]