include::./index.adoc[]

[[v21-1-0]]
=== Eclesiastes, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-1-1]]

^<<v21-1-1,1>>^ São estas as palavras do Sábio, que era filho de Davi e rei em Jerusalém.

[[v21-1-2]]

^<<v21-1-2,2>>^ É ilusão, é ilusão, diz o Sábio. Tudo é ilusão.

[[v21-1-3]]

^<<v21-1-3,3>>^ A gente gasta a vida trabalhando, se esforçando e afinal que vantagem leva em tudo isso?

[[v21-1-4]]

^<<v21-1-4,4>>^ Pessoas nascem, pessoas morrem, mas o mundo continua sempre o mesmo.

[[v21-1-5]]

^<<v21-1-5,5>>^ O sol continua a nascer, e a se pôr, e volta ao seu lugar para começar tudo outra vez.

[[v21-1-6]]

^<<v21-1-6,6>>^ O vento sopra para o sul, depois para o norte, dá voltas e mais voltas e acaba no mesmo lugar.

[[v21-1-7]]

^<<v21-1-7,7>>^ Todos os rios correm para o mar, porém o mar não fica cheio. A água volta para onde nascem os rios, e tudo começa outra vez.

[[v21-1-8]]

^<<v21-1-8,8>>^ Todas as coisas levam a gente ao cansaço — um cansaço tão grande, que nem dá para contar. Os nossos olhos não se cansam de ver, nem os nossos ouvidos, de ouvir.

[[v21-1-9]]

^<<v21-1-9,9>>^ O que aconteceu antes vai acontecer outra vez. O que foi feito antes será feito novamente. Não há nada de novo neste mundo.

[[v21-1-10]]

^<<v21-1-10,10>>^ Será que existe alguma coisa de que a gente possa dizer: "Veja! Isto nunca aconteceu no mundo"? Não! Tudo já aconteceu antes, bem antes de nós nascermos.

[[v21-1-11]]

^<<v21-1-11,11>>^ Ninguém lembra do que aconteceu no passado; quem vier depois das coisas que vão acontecer no futuro também não vai lembrar delas.

[[v21-1-12]]

^<<v21-1-12,12>>^ Eu, o Sábio, fui rei de Israel, em Jerusalém.

[[v21-1-13]]

^<<v21-1-13,13>>^ E resolvi examinar e estudar tudo o que se faz neste mundo. Que serviço cansativo é este que Deus nos deu!

[[v21-1-14]]

^<<v21-1-14,14>>^ Eu tenho visto tudo o que se faz neste mundo e digo: tudo é ilusão. É tudo como correr atrás do vento.

[[v21-1-15]]

^<<v21-1-15,15>>^ Ninguém pode endireitar o que é torto, nem fazer contas quando faltam os números.

[[v21-1-16]]

^<<v21-1-16,16>>^ E pensei assim: "Eu me tornei um grande homem, muito mais sábio do que todos os que governaram Jerusalém antes de mim. Eu realmente sei o que é a sabedoria e o que é o conhecimento."

[[v21-1-17]]

^<<v21-1-17,17>>^ Assim, procurei descobrir o que é o conhecimento e a sabedoria, o que é a tolice e a falta de juízo. Mas descobri que isso é o mesmo que correr atrás do vento.

[[v21-1-18]]

^<<v21-1-18,18>>^ Quanto mais sábia é uma pessoa, mais aborrecimentos ela tem; e, quanto mais sabe, mais sofre.

'''

xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]