include::./index.adoc[]

[[v21-4-0]]
=== Eclesiastes, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-4-1]]

^<<v21-4-1,1>>^ Então olhei de novo para toda a injustiça que existe neste mundo. Vi muitos sendo explorados e maltratados. Eles choravam, mas ninguém os ajudava. Ninguém os ajudava porque os seus perseguidores tinham o poder do seu lado.

[[v21-4-2]]

^<<v21-4-2,2>>^ Por isso, cheguei a esta conclusão: aqueles que morreram são mais felizes do que os que continuam vivos.

[[v21-4-3]]

^<<v21-4-3,3>>^ Porém mais felizes do que todos são aqueles que ainda não nasceram e que ainda não viram as injustiças que há neste mundo.

[[v21-4-4]]

^<<v21-4-4,4>>^ Também descobri por que as pessoas se esforçam tanto para ter sucesso no seu trabalho: é porque elas querem ser mais do que os outros. Mas tudo é ilusão. É tudo como correr atrás do vento.

[[v21-4-5]]

^<<v21-4-5,5>>^ Dizem que só mesmo um louco chegaria ao ponto de cruzar os braços e passar fome até morrer.

[[v21-4-6]]

^<<v21-4-6,6>>^ Pode ser. Mas é melhor ter pouco numa das mãos, com paz de espírito, do que estar sempre com as duas mãos cheias de trabalho, tentando pegar o vento.

[[v21-4-7]]

^<<v21-4-7,7>>^ Descobri que na vida existe mais uma coisa que não vale a pena:

[[v21-4-8]]

^<<v21-4-8,8>>^ é o homem viver sozinho, sem amigos, sem filhos, sem irmãos, sempre trabalhando e nunca satisfeito com a riqueza que tem. Para que é que ele trabalha tanto, deixando de aproveitar as coisas boas da vida? Isso também é ilusão, é uma triste maneira de viver.

[[v21-4-9]]

^<<v21-4-9,9>>^ É melhor haver dois do que um, porque duas pessoas trabalhando juntas podem ganhar muito mais.

[[v21-4-10]]

^<<v21-4-10,10>>^ Se uma delas cai, a outra a ajuda a se levantar. Mas, se alguém está sozinho e cai, fica em má situação porque não tem ninguém que o ajude a se levantar.

[[v21-4-11]]

^<<v21-4-11,11>>^ Se faz frio, dois podem dormir juntos e se esquentar; mas um sozinho, como é que vai se esquentar?

[[v21-4-12]]

^<<v21-4-12,12>>^ Dois homens podem resistir a um ataque que derrotaria um deles se estivesse sozinho. Uma corda de três cordões é difícil de arrebentar.

[[v21-4-13]]

^<<v21-4-13,13>>^ O moço pobre mas sábio vale mais do que o rei velho e sem juízo que já não aceita conselhos.

[[v21-4-14]]

^<<v21-4-14,14>>^ Um homem pode muito bem sair da cadeia e se tornar o rei do seu país, mesmo tendo nascido pobre.

[[v21-4-15]]

^<<v21-4-15,15>>^ Eu pensei em todas as pessoas que vivem neste mundo e imaginei que existe entre elas, em algum lugar, um moço que tomará o lugar do rei.

[[v21-4-16]]

^<<v21-4-16,16>>^ O número de pessoas que um rei governa é muito grande; no entanto, quando deixa de ser rei, ninguém é agradecido pelo que ele fez. É tudo ilusão, é tudo como correr atrás do vento.

'''

xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[&#60; Capítulo Anterior] | <<v21-4-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[Próximo Capítulo &#62;]