include::./index.adoc[]

[[v21-5-0]]
=== Eclesiastes, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-5-1]]

^<<v21-5-1,1>>^ Tenha cuidado quando for ao Templo. Não ofereça o seu sacrifício  como fazem os tolos, que nem sabem que não estão fazendo isso da maneira certa. Vá pronto para ouvir e obedecer a Deus.

[[v21-5-2]]

^<<v21-5-2,2>>^ Pense bem antes de falar e não faça a Deus nenhuma promessa apressada. Deus está no céu, e você, aqui na terra; portanto, fale pouco.

[[v21-5-3]]

^<<v21-5-3,3>>^ Quanto mais você se preocupar, mais pesadelos terá; e, quanto mais você falar, mais tolices dirá.

[[v21-5-4]]

^<<v21-5-4,4>>^ Assim, quando você fizer uma promessa a Deus, cumpra logo essa promessa. Ele não gosta de tolos; portanto, faça o que prometeu.

[[v21-5-5]]

^<<v21-5-5,5>>^ É melhor não prometer nada do que fazer uma promessa e não cumprir.

[[v21-5-6]]

^<<v21-5-6,6>>^ Não deixe que as suas próprias palavras o façam pecar. Assim, você não terá de dizer ao sacerdote que o que você queria dizer não era bem aquilo. Para que fazer Deus ficar irado  com você? Por que deixar que ele destrua as coisas que você conseguiu com o seu trabalho?

[[v21-5-7]]

^<<v21-5-7,7>>^ Mesmo nos seus muitos sonhos, em todas as suas ilusões e em tudo o que disser, você deve temer a Deus .

[[v21-5-8]]

^<<v21-5-8,8>>^ Não fique admirado quando você notar em algum lugar o governo fazendo injustiça, perseguindo os pobres e negando os direitos deles. Pois cada autoridade é protegida pela que está acima dela, e as duas são acobertadas pelas autoridades superiores.

[[v21-5-9]]

^<<v21-5-9,9>>^ Elas dizem: "Toda gente tira proveito da terra, mas o rei depende daquilo que recebe das colheitas."

[[v21-5-10]]

^<<v21-5-10,10>>^ Quem ama o dinheiro nunca ficará satisfeito; quem tem a ambição de ficar rico nunca terá tudo o que quer. Isso também é ilusão.

[[v21-5-11]]

^<<v21-5-11,11>>^ Quanto mais rica é a pessoa, mais bocas tem para alimentar. E o que ela ganha com isso é apenas saber que é rica.

[[v21-5-12]]

^<<v21-5-12,12>>^ O trabalhador pode ter pouco ou muito para comer, mas pelo menos dorme bem à noite. Porém o rico se preocupa tanto com as coisas que possui, que nem consegue dormir.

[[v21-5-13]]

^<<v21-5-13,13>>^ Eu tenho visto neste mundo esta coisa triste: algumas pessoas economizam dinheiro e sofrem com isso.

[[v21-5-14]]

^<<v21-5-14,14>>^ Perdem tudo num mau negócio e assim não deixam nada para os filhos.

[[v21-5-15]]

^<<v21-5-15,15>>^ Como entramos neste mundo, assim também saímos, isto é, sem nada. Apesar de todo o nosso trabalho, não podemos levar nada desta vida.

[[v21-5-16]]

^<<v21-5-16,16>>^ Isso também é muito triste! Nós vamos embora deste mundo do mesmo jeito que viemos. Trabalhamos tanto, tentando pegar o vento, e o que é que ganhamos com isso?

[[v21-5-17]]

^<<v21-5-17,17>>^ O que ganhamos é passar a vida na escuridão e na tristeza, preocupados, doentes e amargurados.

[[v21-5-18]]

^<<v21-5-18,18>>^ Então cheguei a esta conclusão: a melhor coisa que uma pessoa pode fazer durante a curta vida que Deus lhe deu é comer e beber e aproveitar bem o que ganhou com o seu trabalho. Essa é a parte que cabe a cada um.

[[v21-5-19]]

^<<v21-5-19,19>>^ Se Deus der a você riquezas e propriedades e deixar que as aproveite, fique contente com o que recebeu e com o seu trabalho. Isso é um presente de Deus.

[[v21-5-20]]

^<<v21-5-20,20>>^ E você não sentirá o tempo passar, pois Deus encherá o seu coração de alegria.

'''

xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[&#60; Capítulo Anterior] | <<v21-5-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[Próximo Capítulo &#62;]