include::./index.adoc[]

[[v21-2-0]]
=== Eclesiastes, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-2-1]]

^<<v21-2-1,1>>^ Então resolvi me divertir e gozar os prazeres da vida. Mas descobri que isso também é ilusão.

[[v21-2-2]]

^<<v21-2-2,2>>^ Cheguei à conclusão de que o riso é tolice e de que o prazer não serve para nada.

[[v21-2-3]]

^<<v21-2-3,3>>^ Procurei ainda descobrir qual a melhor maneira de viver e então resolvi me alegrar com vinho e me divertir. Pensei que talvez fosse essa a melhor coisa que uma pessoa pode fazer durante a sua curta vida aqui na terra.

[[v21-2-4]]

^<<v21-2-4,4>>^ Realizei grandes coisas. Construí casas para mim e fiz plantações de uvas.

[[v21-2-5]]

^<<v21-2-5,5>>^ Plantei jardins e pomares, com todos os tipos de árvores frutíferas.

[[v21-2-6]]

^<<v21-2-6,6>>^ Também construí açudes para regar as plantações.

[[v21-2-7]]

^<<v21-2-7,7>>^ Comprei muitos escravos e além desses tive outros, nascidos na minha casa. Tive mais gado e mais ovelhas do que todas as pessoas que moraram em Jerusalém antes de mim.

[[v21-2-8]]

^<<v21-2-8,8>>^ Também ajuntei para mim prata e ouro dos tesouros dos reis e das terras que governei. Homens e mulheres cantaram para me divertir, e tive todas as mulheres que um homem pode desejar.

[[v21-2-9]]

^<<v21-2-9,9>>^ Sim! Fui grande. Fui mais rico do que todos os que viveram em Jerusalém antes de mim, e nunca me faltou sabedoria.

[[v21-2-10]]

^<<v21-2-10,10>>^ Consegui tudo o que desejei. Não neguei a mim mesmo nenhum tipo de prazer. Eu me sentia feliz com o meu trabalho, e essa era a minha recompensa.

[[v21-2-11]]

^<<v21-2-11,11>>^ Mas, quando pensei em todas as coisas que havia feito e no trabalho que tinha tido para conseguir fazê-las, compreendi que tudo aquilo era ilusão, não tinha nenhum proveito. Era como se eu estivesse correndo atrás do vento.

[[v21-2-12]]

^<<v21-2-12,12>>^ Então comecei a pensar no que é ser sábio e no que é ser tolo ou sem juízo. Por exemplo: será que um rei pode fazer alguma coisa que seja nova? Não! Só pode fazer o que fizeram os reis que reinaram antes dele.

[[v21-2-13]]

^<<v21-2-13,13>>^ E cheguei à conclusão de que a sabedoria é melhor do que a tolice, assim como a luz é melhor do que a escuridão.

[[v21-2-14]]

^<<v21-2-14,14>>^ Os sábios podem ver para onde estão indo, mas os tolos andam na escuridão. Porém eu sei que o mesmo que acontece com os sábios acontece também com os tolos.

[[v21-2-15]]

^<<v21-2-15,15>>^ Aí eu pensei assim: "O que acontece com os tolos vai acontecer comigo também. Então, o que é que eu ganhei sendo tão sábio?" E respondi: "Não ganhei nada!"

[[v21-2-16]]

^<<v21-2-16,16>>^ Ninguém lembra para sempre dos sábios, como ninguém lembra dos tolos. No futuro todos nós seremos esquecidos. Todos morreremos, tanto os sábios como os tolos.

[[v21-2-17]]

^<<v21-2-17,17>>^ Por isso, a vida começou a não valer nada para mim; ela só me havia trazido aborrecimentos. Tudo havia sido ilusão; eu apenas havia corrido atrás do vento.

[[v21-2-18]]

^<<v21-2-18,18>>^ Tudo o que eu tinha e que havia conseguido com o meu trabalho não valia nada para mim. Sabia que teria de deixar tudo para o rei que ficasse no meu lugar.

[[v21-2-19]]

^<<v21-2-19,19>>^ E ele poderia ser um sábio ou um tolo — quem é que sabe? No entanto, ele seria o dono de todas as coisas que eu consegui com o meu trabalho e ficaria com tudo o que a minha sabedoria me deu neste mundo. Tudo é ilusão.

[[v21-2-20]]

^<<v21-2-20,20>>^ Então eu me arrependi de ter trabalhado tanto e fiquei desesperado por causa disso.

[[v21-2-21]]

^<<v21-2-21,21>>^ A gente trabalha com toda a sabedoria, conhecimento e inteligência para conseguir alguma coisa e depois tem de deixar tudo para alguém que não fez nada para merecer aquilo. Isso também é ilusão e não está certo!

[[v21-2-22]]

^<<v21-2-22,22>>^ Nós trabalhamos e nos preocupamos a vida toda e o que é que ganhamos com isso?

[[v21-2-23]]

^<<v21-2-23,23>>^ Tudo o que fazemos na vida não nos traz nada, a não ser preocupações e desgostos. Não podemos descansar, nem de noite. É tudo ilusão.

[[v21-2-24]]

^<<v21-2-24,24>>^ A melhor coisa que alguém pode fazer é comer e beber e se divertir com o dinheiro que ganhou. No entanto, compreendi que mesmo essas coisas vêm de Deus.

[[v21-2-25]]

^<<v21-2-25,25>>^ Sem Deus, como teríamos o que comer ou com que nos divertir?

[[v21-2-26]]

^<<v21-2-26,26>>^ Ele dá sabedoria, conhecimento e felicidade às pessoas de quem ele gosta. Mas Deus faz com que os maus trabalhem, economizem e ajuntem a fim de que a riqueza deles seja dada às pessoas de quem ele gosta mais. Tudo é ilusão. É tudo como correr atrás do vento.

'''

xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]