include::./index.adoc[]

[[v21-12-0]]
=== Eclesiastes, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-12-1]]

^<<v21-12-1,1>>^ Lembre do seu Criador enquanto você ainda é jovem, antes que venham os dias maus e cheguem os anos em que você dirá: "Não tenho mais prazer na vida."

[[v21-12-2]]

^<<v21-12-2,2>>^ Lembre dele antes que chegue o tempo em que você achará que a luz do sol, da lua e das estrelas perdeu o seu brilho e que as nuvens de chuva nunca vão embora.

[[v21-12-3]]

^<<v21-12-3,3>>^ Então os seus braços, que sempre o defenderam, começarão a tremer, e as suas pernas, que agora são fortes, ficarão fracas. Os seus dentes cairão, e sobrarão tão poucos, que você não conseguirá mastigar a sua comida. A sua vista ficará tão fraca, que você não poderá mais ver as coisas claramente.

[[v21-12-4]]

^<<v21-12-4,4>>^ Você ficará surdo e não poderá ouvir o barulho da rua. Você quase não conseguirá ouvir o moinho moendo ou a música tocando. E levantará cedo, quando os passarinhos começam a cantar.

[[v21-12-5]]

^<<v21-12-5,5>>^ Então você terá medo de lugares altos, e até caminhar será perigoso. Os seus cabelos ficarão brancos, e você perderá o gosto pelas coisas. Nós estaremos caminhando para o nosso último descanso; e, quando isso acontecer, haverá gente chorando por nossa causa nas ruas.

[[v21-12-6]]

^<<v21-12-6,6>>^ A vida vai se acabar como uma lamparina de ouro cai e quebra, quando a sua corrente de prata se arrebenta, ou como um pote de barro se despedaça quando a corda do poço se parte.

[[v21-12-7]]

^<<v21-12-7,7>>^ Então o nosso corpo voltará para o pó da terra, de onde veio, e o nosso espírito voltará para Deus, que o deu.

[[v21-12-8]]

^<<v21-12-8,8>>^ É ilusão, é ilusão, diz o Sábio. Tudo é ilusão.

[[v21-12-9]]

^<<v21-12-9,9>>^ O Sábio, usando o seu conhecimento, continuou a ensinar ao povo o que sabia. Ele estudou, examinou e pôs em ordem muitos provérbios.

[[v21-12-10]]

^<<v21-12-10,10>>^ Procurou usar palavras agradáveis, e tudo o que escreveu é verdade.

[[v21-12-11]]

^<<v21-12-11,11>>^ As palavras dos sábios são como pregos bem-pregados; são como as varas pontudas que os pastores usam para guiar as ovelhas. Essas palavras foram dadas por Deus, o único Pastor de todos nós.

[[v21-12-12]]

^<<v21-12-12,12>>^ Filho, há mais uma coisa que eu quero dizer: os livros sempre continuarão a ser escritos; estudar demais cansa a mente.

[[v21-12-13]]

^<<v21-12-13,13>>^ De tudo o que foi dito, a conclusão é esta: tema a Deus  e obedeça aos seus mandamentos porque foi para isso que fomos criados.

[[v21-12-14]]

^<<v21-12-14,14>>^ Nós teremos de prestar contas a Deus de tudo o que fizermos e até daquilo que fizermos em segredo, seja o bem ou o mal.

'''

xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[&#60; Capítulo Anterior] | <<v21-12-0,Topo>> | xref:022-canticos/022-canticos-001.adoc#v22-1-0[Próximo Capítulo &#62;]