include::./index.adoc[]

[[v21-11-0]]
=== Eclesiastes, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-11-1]]

^<<v21-11-1,1>>^ Empregue o seu dinheiro em bons negócios e com o tempo você terá o seu lucro.

[[v21-11-2]]

^<<v21-11-2,2>>^ Aplique-o em vários lugares e em negócios diferentes porque você não sabe que crise poderá acontecer no mundo.

[[v21-11-3]]

^<<v21-11-3,3>>^ Quando as nuvens ficam cheias, a chuva cai. Uma árvore pode cair em qualquer direção, mas, no lugar em que cair, aí ficará.

[[v21-11-4]]

^<<v21-11-4,4>>^ Quem fica esperando que o vento mude e que o tempo fique bom nunca plantará, nem colherá nada.

[[v21-11-5]]

^<<v21-11-5,5>>^ Deus faz todas as coisas. E, como você não pode entender como começa uma nova vida dentro da barriga de uma mulher, assim também não pode entender as coisas que Deus faz.

[[v21-11-6]]

^<<v21-11-6,6>>^ Semeie de manhã e também de tarde porque você não sabe se todas as sementes crescerão bem, nem se uma crescerá melhor do que a outra.

[[v21-11-7]]

^<<v21-11-7,7>>^ Como é agradável a luz do dia, e como é bom ver o sol!

[[v21-11-8]]

^<<v21-11-8,8>>^ Viva alegre durante todos os anos da sua vida. Mas, mesmo que você viva muitos anos, lembre que ficará morto durante muito mais tempo. Tudo o que acontece é ilusão.

[[v21-11-9]]

^<<v21-11-9,9>>^ Jovem, aproveite a sua mocidade e seja feliz enquanto é moço. Faça tudo o que quiser e siga os desejos do seu coração. Mas lembre de uma coisa: Deus o julgará por tudo o que você fizer.

[[v21-11-10]]

^<<v21-11-10,10>>^ Não deixe que nada o preocupe ou faça sofrer, pois a mocidade dura pouco.

'''

xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[&#60; Capítulo Anterior] | <<v21-11-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[Próximo Capítulo &#62;]