include::./index.adoc[]

[[v21-9-0]]
=== Eclesiastes, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-9-1]]

^<<v21-9-1,1>>^ Eu pensei bastante, e me esforcei para entender tudo isso, e cheguei à conclusão de que Deus controla o que as pessoas sábias e honestas fazem e até o amor e o ódio delas. Ninguém sabe nada do que vai acontecer no futuro, mas isso não faz diferença.

[[v21-9-2]]

^<<v21-9-2,2>>^ Pois a mesma coisa acontece com os honestos e os desonestos, os bons e os maus, os religiosos e os não religiosos, os que adoram a Deus e os que não adoram. A mesma coisa acontece com quem é bom e com quem é pecador, com a pessoa que faz juramentos e com a que não faz.

[[v21-9-3]]

^<<v21-9-3,3>>^ A mesma coisa acontece com todos; e isso é o pior de tudo o que acontece neste mundo. O coração das pessoas está cheio de maldade e de loucura; e, de repente, elas morrem.

[[v21-9-4]]

^<<v21-9-4,4>>^ Mas, enquanto se vive neste mundo, existe alguma esperança; porque é melhor ser um cão vivo do que um leão morto.

[[v21-9-5]]

^<<v21-9-5,5>>^ Sim, os vivos sabem que vão morrer, mas os mortos não sabem nada. Eles não vão receber mais nada e estão completamente esquecidos.

[[v21-9-6]]

^<<v21-9-6,6>>^ Os seus amores, os seus ódios, as suas paixões, tudo isso morreu com eles. Nunca mais tomarão parte naquilo que acontece neste mundo.

[[v21-9-7]]

^<<v21-9-7,7>>^ Portanto, vá em frente. Coma com prazer a sua comida e beba alegremente o seu vinho, pois Deus já aceitou com prazer o que você faz.

[[v21-9-8]]

^<<v21-9-8,8>>^ Procure sempre parecer feliz e satisfeito.

[[v21-9-9]]

^<<v21-9-9,9>>^ Enquanto você viver neste mundo de ilusões, aproveite a vida com a mulher que você ama. Pois isso é tudo o que você vai receber pelos seus trabalhos nesta vida dura que Deus lhe deu.

[[v21-9-10]]

^<<v21-9-10,10>>^ Tudo o que você tiver de fazer faça o melhor que puder, pois no mundo dos mortos  não se faz nada, e ali não existe pensamento, nem conhecimento, nem sabedoria. E é para lá que você vai.

[[v21-9-11]]

^<<v21-9-11,11>>^ Eu descobri mais outra coisa neste mundo: nem sempre são os corredores mais velozes que ganham as corridas; nem sempre são os soldados mais valentes que ganham as batalhas. Notei ainda que as pessoas mais sábias nem sempre têm o que comer e que as mais inteligentes nem sempre ficam ricas. Notei também que as pessoas mais capazes nem sempre alcançam altas posições. Tudo depende da sorte e da ocasião.

[[v21-9-12]]

^<<v21-9-12,12>>^ Pois ninguém sabe quando a hora da desgraça vai chegar. Como aves que caem, de repente, na armadilha ou como peixes apanhados na rede, nós também podemos cair na desgraça quando menos esperamos.

[[v21-9-13]]

^<<v21-9-13,13>>^ Há mais uma coisa que eu vi e que é um bom exemplo de como neste mundo não se dá valor à sabedoria.

[[v21-9-14]]

^<<v21-9-14,14>>^ Havia uma pequena cidade onde morava pouca gente. Com o seu exército, um rei poderoso atacou a cidade, construiu rampas de ataque em redor dela e se preparou para derrubar as suas muralhas.

[[v21-9-15]]

^<<v21-9-15,15>>^ Morava ali um homem que era pobre, mas muito inteligente; era tão inteligente, que poderia ter salvado a cidade. Acontece que ninguém lembrou dele.

[[v21-9-16]]

^<<v21-9-16,16>>^ Eu sempre achei que a sabedoria é melhor do que a força; mas ninguém acredita que uma pessoa pobre pode ser sábia e ninguém presta atenção no que ela diz.

[[v21-9-17]]

^<<v21-9-17,17>>^ É melhor ouvir as palavras calmas de uma pessoa sábia do que os gritos de um líder numa reunião de tolos.

[[v21-9-18]]

^<<v21-9-18,18>>^ A sabedoria vale mais do que armas de guerra, mas uma decisão errada pode estragar os melhores planos.

'''

xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[&#60; Capítulo Anterior] | <<v21-9-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[Próximo Capítulo &#62;]