include::./index.adoc[]

[[v21-6-0]]
=== Eclesiastes, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v21-6-1]]

^<<v21-6-1,1>>^ Também tenho visto outra coisa muito triste que acontece neste mundo:

[[v21-6-2]]

^<<v21-6-2,2>>^ Deus dá a alguns tudo o que desejam — riquezas, propriedades e fama. Porém depois não deixa que eles aproveitem nada disso. E é algum estranho quem aproveita, e não ele. Isso também é ilusão e não está certo.

[[v21-6-3]]

^<<v21-6-3,3>>^ Que adianta um homem viver muitos anos e ter cem filhos se não aproveitar as coisas boas da vida e não tiver um sepultamento decente? Eu digo que uma criança que nasce morta tem mais sorte do que ele.

[[v21-6-4]]

^<<v21-6-4,4>>^ É inútil a vinda dessa criança; ela desaparece na escuridão, onde é esquecida.

[[v21-6-5]]

^<<v21-6-5,5>>^ Não chega a ver a luz do dia, nem a saber como é a vida. Mas pelo menos encontra mais descanso do que aquele homem,

[[v21-6-6]]

^<<v21-6-6,6>>^ que poderia ter vivido dois mil anos sem nunca ter aproveitado a vida. E, no fim, não vamos todos para o mesmo lugar?

[[v21-6-7]]

^<<v21-6-7,7>>^ Todos trabalham duro para ter o que comer, mas nunca ficam satisfeitos.

[[v21-6-8]]

^<<v21-6-8,8>>^ Que vantagem tem o sábio sobre o tolo? Que vantagem tem o pobre em saber enfrentar a vida?

[[v21-6-9]]

^<<v21-6-9,9>>^ Isso também é ilusão, é correr atrás do vento. É muito melhor ficar satisfeito com o que se tem do que estar sempre querendo mais.

[[v21-6-10]]

^<<v21-6-10,10>>^ Tudo o que se passa neste mundo já foi resolvido há muito tempo. Antes de uma pessoa nascer, já está decidido o que vai acontecer com ela. E nós sabemos que não podemos discutir com quem é mais forte do que a gente.

[[v21-6-11]]

^<<v21-6-11,11>>^ Uma coisa é certa: quanto mais falamos, mais tolices dizemos; e não ganhamos nada com isso.

[[v21-6-12]]

^<<v21-6-12,12>>^ De fato, como é que podemos saber o que é melhor para nós nesta vida de ilusões, vida que passa como uma sombra? Como podemos saber o que vai acontecer na terra depois da nossa morte?

'''

xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[&#60; Capítulo Anterior] | <<v21-6-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[Próximo Capítulo &#62;]