include::./index.adoc[]

[[v6-4-0]]
=== Josué, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-4-1]]

^<<v6-4-1,1>>^ Quando todo o povo de Israel acabou de atravessar o rio Jordão, o Senhor  disse a Josué:

[[v6-4-2]]

^<<v6-4-2,2>>^ — Escolha doze homens, um de cada tribo ,

[[v6-4-3]]

^<<v6-4-3,3>>^ e dê esta ordem: "Peguem doze pedras do meio do rio Jordão, do lugar onde os sacerdotes ficaram parados. Levem essas pedras e coloquem onde acamparem hoje à noite."

[[v6-4-4]]

^<<v6-4-4,4>>^ Então Josué chamou os doze homens que havia escolhido

[[v6-4-5]]

^<<v6-4-5,5>>^ e disse: — Passem adiante da arca da aliança  do Senhor , o Deus de vocês, e sigam até o meio do Jordão. Cada um ponha no ombro uma pedra, uma para cada tribo de Israel.

[[v6-4-6]]

^<<v6-4-6,6>>^ Essas pedras ajudarão o povo a lembrar daquilo que o Senhor  tem feito. No futuro, quando os seus filhos perguntarem o que essas pedras querem dizer,

[[v6-4-7]]

^<<v6-4-7,7>>^ vocês contarão que as águas do Jordão pararam de correr no dia em que a arca da aliança atravessou o rio. Essas pedras farão com que o povo de Israel lembre sempre desse dia.

[[v6-4-8]]

^<<v6-4-8,8>>^ Os homens fizeram o que Josué mandou. Como o Senhor  Deus tinha dito a Josué, eles pegaram do meio do rio Jordão doze pedras, uma para cada tribo de Israel, e as levaram e colocaram no acampamento.

[[v6-4-9]]

^<<v6-4-9,9>>^ Josué também pôs doze pedras no meio do Jordão, no lugar onde os sacerdotes que carregavam a arca haviam parado. Essas pedras ainda estão lá.

[[v6-4-10]]

^<<v6-4-10,10>>^ Os sacerdotes ficaram parados no meio do Jordão até que foi feito tudo o que o Senhor , por meio de Moisés, havia mandado Josué falar ao povo. Então o povo se apressou e atravessou o rio.

[[v6-4-11]]

^<<v6-4-11,11>>^ Quando todos já haviam passado, a arca da aliança e os sacerdotes também passaram e ficaram na frente do povo.

[[v6-4-12]]

^<<v6-4-12,12>>^ Os homens das tribos de Rúben, de Gade e de Manassés do Leste atravessaram antes do resto do povo, prontos para a batalha, conforme Moisés tinha dito.

[[v6-4-13]]

^<<v6-4-13,13>>^ Mais ou menos quarenta mil homens preparados para guerrear marcharam diante de Deus, o Senhor , indo para o lado da planície de Jericó.

[[v6-4-14]]

^<<v6-4-14,14>>^ Naquele dia o Senhor  fez com que o povo de Israel ficasse sabendo que Josué era um grande homem. E, durante a vida de Josué, eles o respeitaram assim como haviam respeitado a Moisés.

[[v6-4-15]]

^<<v6-4-15,15>>^ E o Senhor  Deus disse a Josué:

[[v6-4-16]]

^<<v6-4-16,16>>^ — Mande sair do rio Jordão os sacerdotes que estão carregando a arca da aliança.

[[v6-4-17]]

^<<v6-4-17,17>>^ Josué fez isso.

[[v6-4-18]]

^<<v6-4-18,18>>^ E, depois que os sacerdotes saíram do Jordão e pisaram a terra seca, o rio começou a correr de novo e cobriu as margens como antes.

[[v6-4-19]]

^<<v6-4-19,19>>^ O povo atravessou o Jordão no dia dez do primeiro mês e acampou em Gilgal, a leste de Jericó.

[[v6-4-20]]

^<<v6-4-20,20>>^ Ali Josué fez um monumento com as doze pedras que havia tirado do Jordão.

[[v6-4-21]]

^<<v6-4-21,21>>^ E disse ao povo de Israel: — Quando no futuro os filhos perguntarem aos pais o que estas pedras querem dizer,

[[v6-4-22]]

^<<v6-4-22,22>>^ vocês explicarão que o povo de Israel atravessou o rio Jordão em terra seca.

[[v6-4-23]]

^<<v6-4-23,23>>^ O Senhor , o Deus de vocês, secou o Jordão para vocês atravessarem, assim como secou o mar Vermelho para nós passarmos.

[[v6-4-24]]

^<<v6-4-24,24>>^ Por causa disso todos os povos da terra vão conhecer o poder do Senhor , o Deus de vocês, e vocês o respeitarão para sempre.

'''

xref:006-josue/006-josue-003.adoc#v6-3-0[&#60; Capítulo Anterior] | <<v6-4-0,Topo>> | xref:006-josue/006-josue-005.adoc#v6-5-0[Próximo Capítulo &#62;]