include::./index.adoc[]

[[v6-12-0]]
=== Josué, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-12-1]]

^<<v6-12-1,1>>^ O povo de Israel havia derrotado os reis que moravam a leste do rio Jordão e ocupado as suas terras. Essas terras iam desde o vale do Arnom, subindo o vale do Jordão, até o monte Hermom. Os reis que os israelitas derrotaram são citados em seguida.

[[v6-12-2]]

^<<v6-12-2,2>>^ O primeiro foi Seom, o rei dos amorreus, que vivia em Hesbom. O reino dele começava em Aroer, na beira do vale do Arnom e na metade do vale, e ia até o rio Jaboque, na divisa da região de Amom. Esse reino ia até a metade de Gileade.

[[v6-12-3]]

^<<v6-12-3,3>>^ Do lado leste do vale do Jordão, o reino de Seom começava no lago da Galileia na direção de Bete-Jesimote, a leste do mar Morto, e ia até o sul, ao pé do monte Pisga.

[[v6-12-4]]

^<<v6-12-4,4>>^ Os israelitas também derrotaram Ogue, rei de Basã, que foi um dos últimos refains . Ele morava em Astarote e Edrei.

[[v6-12-5]]

^<<v6-12-5,5>>^ Do reino dele faziam parte o monte Hermom, Salca e toda a região de Basã, até a divisa com os gesuritas e maacatitas, e também metade de Gileade, até as terras de Seom, rei de Hesbom.

[[v6-12-6]]

^<<v6-12-6,6>>^ Moisés e o povo de Israel os derrotaram. Moisés, servo  do Senhor , deu as terras desses reis às tribos  de Rúben, de Gade e de Manassés do Leste.

[[v6-12-7]]

^<<v6-12-7,7>>^ Josué e o povo de Israel derrotaram todos os reis das terras que ficam a oeste do rio Jordão, desde Baal-Gade, no vale do Líbano, até o monte Halaque, na direção de Seir. Josué dividiu essas terras entre as tribos, para serem delas para sempre.

[[v6-12-8]]

^<<v6-12-8,8>>^ Faziam parte dessas terras a região montanhosa, a planície, o vale do Jordão, a subida das montanhas, o deserto e a região sul. Nessa terra moravam os heteus, os amorreus, os cananeus, os perizeus, os heveus e os jebuseus.

[[v6-12-9]]

^<<v6-12-9,9>>^ Foram derrotados os reis das seguintes cidades: Jericó, Ai (perto de Betel), Jerusalém, Hebrom, Jarmute, Laquis, Eglom, Gezer, Debir, Geder, Horma, Arade, Libna, Adulã, Maquedá, Betel, Tapua, Héfer, Afeca, Lasarom, Madom, Hazor, Sinrom-Merom, Acsafe, Taanaque, Megido, Quedes, Jocneão (na região do Carmelo), Dor (no litoral), Goim (na Galileia) e Tirza — ao todo trinta e um reis.

'''

xref:006-josue/006-josue-011.adoc#v6-11-0[&#60; Capítulo Anterior] | <<v6-12-0,Topo>> | xref:006-josue/006-josue-013.adoc#v6-13-0[Próximo Capítulo &#62;]