include::./index.adoc[]

[[v6-6-0]]
=== Josué, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-6-1]]

^<<v6-6-1,1>>^ Os portões da cidade de Jericó estavam muito bem-fechados, para não deixar que os israelitas entrassem. Ninguém podia entrar, nem sair da cidade.

[[v6-6-2]]

^<<v6-6-2,2>>^ O Senhor  Deus disse a Josué: — Olhe! Eu estou entregando a você a cidade de Jericó, o seu rei e os seus corajosos soldados.

[[v6-6-3]]

^<<v6-6-3,3>>^ Agora você e os soldados israelitas marcharão em volta da cidade uma vez por dia, durante seis dias.

[[v6-6-4]]

^<<v6-6-4,4>>^ Na frente da arca da aliança , irão sete sacerdotes, cada um levando uma corneta de chifre de carneiro. No sétimo dia você e os seus soldados marcharão sete vezes em volta da cidade, e os sacerdotes tocarão as cornetas.

[[v6-6-5]]

^<<v6-6-5,5>>^ Quando eles derem um toque longo, todo o povo gritará bem alto, e então a muralha da cidade cairá. Aí cada um avançará diretamente para a cidade.

[[v6-6-6]]

^<<v6-6-6,6>>^ Josué chamou os sacerdotes e disse: — Carreguem a arca da aliança, e na frente fiquem sete sacerdotes levando cornetas.

[[v6-6-7]]

^<<v6-6-7,7>>^ E disse ao povo: — Comecem a marchar em volta da cidade! E que os soldados marchem na frente da arca da aliança de Deus, o Senhor !

[[v6-6-8]]

^<<v6-6-8,8>>^ Então, seguindo as ordens de Josué, os sete sacerdotes ficaram na frente da arca e começaram a tocar as cornetas.

[[v6-6-9]]

^<<v6-6-9,9>>^ Os soldados iam na frente dos sacerdotes que tocavam cornetas, e um grupo de guardas seguia a arca. Durante esse tempo as cornetas tocavam.

[[v6-6-10]]

^<<v6-6-10,10>>^ Mas Josué tinha dado ordem ao povo para não gritar, nem fazer barulho até que ele mandasse.

[[v6-6-11]]

^<<v6-6-11,11>>^ Aí Josué ordenou que os sacerdotes dessem uma volta ao redor da cidade, carregando a arca da aliança. Depois voltaram ao acampamento e passaram a noite lá.

[[v6-6-12]]

^<<v6-6-12,12>>^ No dia seguinte Josué se levantou de madrugada, e os sacerdotes carregaram a arca.

[[v6-6-13]]

^<<v6-6-13,13>>^ Os sete sacerdotes que levavam as sete cornetas iam na frente, tocando sem parar. Os soldados iam na frente deles, e um grupo de guardas seguia a arca. As cornetas não paravam de tocar.

[[v6-6-14]]

^<<v6-6-14,14>>^ No segundo dia marcharam de novo uma vez em volta da cidade e voltaram ao acampamento. E fizeram isso durante seis dias.

[[v6-6-15]]

^<<v6-6-15,15>>^ No sétimo dia levantaram-se de madrugada e marcharam em volta da cidade sete vezes no mesmo dia. Foi só nesse dia que deram sete voltas em redor da cidade.

[[v6-6-16]]

^<<v6-6-16,16>>^ Na sétima volta, quando os sacerdotes acabaram de tocar as cornetas, Josué disse ao povo: — Gritem agora! O Senhor  Deus está entregando Jericó a vocês!

[[v6-6-17]]

^<<v6-6-17,17>>^ A cidade deve ser destruída, junto com tudo o que há nela, como oferta para Deus. Somente ficará viva a prostituta Raabe e a sua família porque ela escondeu os nossos espiões.

[[v6-6-18]]

^<<v6-6-18,18>>^ Mas não peguem em nada daquilo que vai ser destruído. Se ficarem com qualquer coisa que eu mandei destruir, vocês vão trazer desgraça e destruição ao acampamento israelita.

[[v6-6-19]]

^<<v6-6-19,19>>^ Mas os objetos de prata, ouro, bronze e ferro serão separados para o Senhor  e colocados no seu tesouro.

[[v6-6-20]]

^<<v6-6-20,20>>^ Então os sacerdotes tocaram as cornetas. Logo que o povo ouviu este som, gritou com toda a força, e a muralha caiu. Aí todos subiram, entraram na cidade e a tomaram.

[[v6-6-21]]

^<<v6-6-21,21>>^ E mataram, com as suas espadas, todos os que estavam na cidade: homens e mulheres, crianças e velhos. Também mataram os bois, as ovelhas e os jumentos.

[[v6-6-22]]

^<<v6-6-22,22>>^ Depois Josué disse aos dois homens que haviam servido como espiões: — Entrem na casa de Raabe, a prostituta, e tragam a família dela para fora, conforme vocês prometeram.

[[v6-6-23]]

^<<v6-6-23,23>>^ Eles foram e fizeram sair Raabe, o seu pai, a sua mãe, os seus irmãos e o resto da família. Tiraram todas as pessoas da casa e as puseram do lado de fora do acampamento israelita.

[[v6-6-24]]

^<<v6-6-24,24>>^ Então incendiaram a cidade e queimaram tudo o que havia nela, menos os objetos de ouro, prata, bronze e ferro. Essas coisas foram colocadas no tesouro da casa de Deus, o Senhor .

[[v6-6-25]]

^<<v6-6-25,25>>^ Josué deixou que Raabe, a prostituta, e todos os seus parentes ficassem vivos porque ela havia escondido os espiões que ele havia mandado a Jericó. E os descendentes dela vivem no meio do povo de Israel até hoje .

[[v6-6-26]]

^<<v6-6-26,26>>^ Nessa ocasião Josué amaldiçoou a cidade em nome de Deus, dizendo: — Quem tentar construir de novo esta cidade de Jericó será amaldiçoado pelo Senhor ! Quem puser os alicerces perderá o filho mais velho! Quem colocar os portões perderá o filho mais moço!

[[v6-6-27]]

^<<v6-6-27,27>>^ Assim o Senhor  Deus esteve com Josué, e a fama de Josué se espalhou por todo o país.

'''

xref:006-josue/006-josue-005.adoc#v6-5-0[&#60; Capítulo Anterior] | <<v6-6-0,Topo>> | xref:006-josue/006-josue-007.adoc#v6-7-0[Próximo Capítulo &#62;]