include::./index.adoc[]

[[v6-22-0]]
=== Josué, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-22-1]]

^<<v6-22-1,1>>^ Então Josué reuniu o povo das tribos  de Rúben, de Gade e de Manassés do Leste

[[v6-22-2]]

^<<v6-22-2,2>>^ e disse: — Vocês têm feito tudo o que Moisés, servo  do Senhor , mandou e têm obedecido a todas as minhas ordens também.

[[v6-22-3]]

^<<v6-22-3,3>>^ Durante todo esse tempo, até hoje, vocês não abandonaram os seus irmãos israelitas. Vocês têm obedecido com cuidado aos mandamentos do Senhor .

[[v6-22-4]]

^<<v6-22-4,4>>^ Agora o Senhor , o Deus de vocês, deu aos seus irmãos israelitas a paz, como havia prometido. Voltem, pois, para a terra que vocês conquistaram do outro lado do rio Jordão, a terra que Moisés, servo do Senhor , lhes deu.

[[v6-22-5]]

^<<v6-22-5,5>>^ Obedeçam com muito cuidado ao mandamento e à lei  que Moisés, servo do Senhor , lhes deu. Amem o Senhor , o Deus de vocês, façam a vontade dele, obedeçam aos seus mandamentos, fiquem ligados com ele e o sirvam com todo o coração e com toda a alma.

[[v6-22-6]]

^<<v6-22-6,6>>^ Aí Josué os abençoou e se despediu deles. E eles voltaram para casa.

[[v6-22-7]]

^<<v6-22-7,7>>^ Moisés tinha dado terras a leste do rio Jordão, em Basã, a uma das metades da tribo de Manassés. Mas para a outra metade Josué tinha dado terras a oeste do rio, junto com as outras tribos. Quando Josué se despediu deles, abençoou-os

[[v6-22-8]]

^<<v6-22-8,8>>^ e disse: — Vocês estão voltando para casa muito ricos, com muito gado, prata, ouro, bronze, ferro e grande quantidade de roupas. Repartam com os seus irmãos israelitas aquilo que vocês tomaram dos inimigos.

[[v6-22-9]]

^<<v6-22-9,9>>^ Então o povo das tribos de Rúben, de Gade e de Manassés do Leste voltou para casa. Eles deixaram os outros israelitas em Siló, na terra de Canaã, e foram para Gileade, a terra deles, que haviam conquistado conforme o Senhor  tinha ordenado por meio de Moisés.

[[v6-22-10]]

^<<v6-22-10,10>>^ Quando chegaram a Gelilote, do lado oeste do rio Jordão, as duas tribos  e meia construíram ali um altar grande, que podia ser visto de longe.

[[v6-22-11]]

^<<v6-22-11,11>>^ Os israelitas das outras tribos ouviram falar disso e comentavam: — Escutem! O povo das tribos de Rúben, de Gade e de Manassés do Leste construiu um altar em Gelilote, do nosso lado do rio Jordão!

[[v6-22-12]]

^<<v6-22-12,12>>^ Quando o povo de Israel ouviu isso, todos se reuniram em Siló para fazer guerra contra eles.

[[v6-22-13]]

^<<v6-22-13,13>>^ Então o povo de Israel enviou Fineias, filho do sacerdote Eleazar, à terra de Gileade, para falar com o povo das tribos de Rúben, de Gade e de Manassés do Leste.

[[v6-22-14]]

^<<v6-22-14,14>>^ Junto com Fineias foram dez líderes, um de cada uma das tribos de Israel.

[[v6-22-15]]

^<<v6-22-15,15>>^ Eles foram até a terra de Gileade para falar com o povo de Rúben, de Gade e de Manassés do Leste. Eles disseram:

[[v6-22-16]]

^<<v6-22-16,16>>^ — Todo o povo de Deus reunido mandou dizer isto: "Por que vocês fizeram essa traição contra o Deus de Israel? Por que se revoltaram contra o Senhor , construindo vocês mesmos esse altar? Será que não estão mais seguindo o Senhor ?

[[v6-22-17]]

^<<v6-22-17,17>>^ Vocês não lembram do pecado cometido em Peor, quando o Senhor  castigou o seu povo? Nós ainda estamos sofrendo por causa disso. Será que aquele pecado não bastava?

[[v6-22-18]]

^<<v6-22-18,18>>^ Será que agora vão deixar de seguir o Senhor ? Se hoje vocês se revoltarem contra o Senhor , amanhã ele ficará irado  com todo o povo de Israel.

[[v6-22-19]]

^<<v6-22-19,19>>^ Agora, se acham que a terra de vocês é impura , então passem para cá, para a terra de Deus, o Senhor , onde está a Tenda Sagrada  em que ele mora. Peçam um pedaço de terra aqui do nosso lado. Porém não se revoltem contra o Senhor  nem contra nós, construindo vocês mesmos outro altar além do altar do Senhor , nosso Deus.

[[v6-22-20]]

^<<v6-22-20,20>>^ Lembrem que Acã, filho de Zera, não quis obedecer ao mandamento a respeito das coisas que deviam ser destruídas, e todo o povo de Israel foi castigado por causa disso. E Acã não foi o único que morreu por causa do seu pecado."

[[v6-22-21]]

^<<v6-22-21,21>>^ Então o povo das tribos de Rúben, de Gade e de Manassés do Leste respondeu aos chefes das famílias de Israel:

[[v6-22-22]]

^<<v6-22-22,22>>^ — Deus é o Poderoso! Ele é o Senhor ! Deus é o Poderoso! Ele é o Senhor ! Ele sabe por que fizemos isso, e fiquem sabendo vocês também. Se nós nos revoltamos e se não fomos fiéis ao Senhor , não nos deixem continuar a viver.

[[v6-22-23]]

^<<v6-22-23,23>>^ Nós não construímos o nosso altar para oferecer sacrifícios  a serem completamente queimados, nem para colocar sobre ele ofertas de cereais ou ofertas de paz. Que o Senhor  mesmo nos castigue se construímos este altar para desobedecer a ele!

[[v6-22-24]]

^<<v6-22-24,24>>^ Pelo contrário, fizemos isso porque ficamos com medo de que um dia os descendentes de vocês venham a dizer aos nossos: "Que ligação vocês têm com o Senhor , o Deus de Israel?

[[v6-22-25]]

^<<v6-22-25,25>>^ O Senhor  pôs o rio Jordão como divisa entre nós e vocês, tribos de Rúben e de Gade. Vocês não têm nada a ver com Deus, o Senhor ." E assim os descendentes de vocês poderiam fazer com que os nossos descendentes deixassem de adorar o Senhor .

[[v6-22-26]]

^<<v6-22-26,26>>^ Por isso o altar que construímos não foi para apresentar ofertas a serem completamente queimadas, nem para oferecer sacrifícios.

[[v6-22-27]]

^<<v6-22-27,27>>^ Pelo contrário, queríamos que fosse um sinal para nós, e para vocês, e para os nossos descendentes depois de nós. Seria um sinal para adorarmos o Senhor  com as nossas ofertas a serem completamente queimadas, com sacrifícios de animais e com ofertas de paz. Isso foi feito para evitar que um dia os seus descendentes venham a dizer aos nossos: "Vocês não têm nenhuma ligação com o Senhor ."

[[v6-22-28]]

^<<v6-22-28,28>>^ Nós pensamos que, se um dia isso acontecer, os nossos descendentes poderão dizer: "Vejam! Os nossos antepassados fizeram um altar igual ao altar de Deus, o Senhor . Ele não foi construído a fim de apresentarmos ofertas a serem completamente queimadas nem sacrifícios de animais, mas a fim de ser um sinal para nós e para vocês."

[[v6-22-29]]

^<<v6-22-29,29>>^ Nunca tivemos a intenção de nos revoltar contra o Senhor , nem pensamos em deixar de segui-lo. Nós não iríamos construir um altar para apresentar ofertas a serem completamente queimadas ou ofertas de cereais, nem para oferecer sacrifícios de animais. Nunca faríamos outro altar além do altar do Senhor , nosso Deus, que fica em frente da Tenda onde ele mora.

[[v6-22-30]]

^<<v6-22-30,30>>^ O sacerdote Fineias, os líderes do povo e os chefes das famílias de Israel que estavam com ele ouviram o que disse o povo das tribos de Rúben, de Gade e de Manassés do Leste e ficaram satisfeitos.

[[v6-22-31]]

^<<v6-22-31,31>>^ E Fineias, filho do sacerdote Eleazar, disse ao povo de Rúben, de Gade e de Manassés: — Agora sabemos que o Senhor  está entre nós, pois vocês não se revoltaram contra ele. Vocês salvaram o povo de Israel do castigo do Senhor .

[[v6-22-32]]

^<<v6-22-32,32>>^ Então Fineias e os líderes deixaram a gente de Rúben e de Gade na região de Gileade, voltaram para a terra de Canaã e contaram tudo ao povo de Israel.

[[v6-22-33]]

^<<v6-22-33,33>>^ O que disseram agradou aos israelitas. Então eles louvaram a Deus e não pensaram mais em fazer guerra, nem em destruir a terra onde a gente de Rúben e de Gade estava morando.

[[v6-22-34]]

^<<v6-22-34,34>>^ E a gente das tribos de Rúben e de Gade chamou o altar de "Testemunha" porque disseram: "É uma testemunha entre nós de que o Senhor  é Deus."

'''

xref:006-josue/006-josue-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-josue/006-josue-023.adoc#v6-23-0[Próximo Capítulo &#62;]