include::./index.adoc[]

[[v6-1-0]]
=== Josué, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-1-1]]

^<<v6-1-1,1>>^ Depois que Moisés, servo  do Senhor , morreu, Deus disse ao ajudante de Moisés, chamado Josué, filho de Num:

[[v6-1-2]]

^<<v6-1-2,2>>^ — O meu servo Moisés está morto. Agora você e todo o povo de Israel se preparem para atravessar o rio Jordão e entrar na terra que vou dar a vocês.

[[v6-1-3]]

^<<v6-1-3,3>>^ Como disse a Moisés, eu lhes darei toda a terra que pisarem.

[[v6-1-4]]

^<<v6-1-4,4>>^ Os limites dessa terra serão os seguintes: ao sul, o deserto; e, ao norte, os montes Líbanos; a leste, o grande rio Eufrates e toda a terra dos heteus; e, a oeste, o mar Mediterrâneo.

[[v6-1-5]]

^<<v6-1-5,5>>^ Você nunca será derrotado. Eu estarei com você como estive com Moisés. Nunca o abandonarei.

[[v6-1-6]]

^<<v6-1-6,6>>^ Seja forte e corajoso porque você vai comandar este povo quando eles tomarem posse da terra que prometi aos antepassados deles.

[[v6-1-7]]

^<<v6-1-7,7>>^ Seja forte e muito corajoso. Tome cuidado e viva de acordo com toda a Lei  que o meu servo Moisés lhe deu. Não se desvie dela em nada e você terá sucesso em qualquer lugar para onde for.

[[v6-1-8]]

^<<v6-1-8,8>>^ Fale sempre do que está escrito no Livro da Lei . Estude esse livro dia e noite e se esforce para viver de acordo com tudo o que está escrito nele. Se fizer isso, tudo lhe correrá bem, e você terá sucesso.

[[v6-1-9]]

^<<v6-1-9,9>>^ Lembre da minha ordem: "Seja forte e corajoso! Não fique desanimado, nem tenha medo, porque eu, o Senhor , seu Deus, estarei com você em qualquer lugar para onde você for!"

[[v6-1-10]]

^<<v6-1-10,10>>^ Então Josué ordenou aos líderes israelitas:

[[v6-1-11]]

^<<v6-1-11,11>>^ — Vão pelo meio do acampamento, dando esta ordem ao povo: "Arranjem comida porque daqui a três dias vocês vão atravessar o rio Jordão para tomar posse da terra que o Senhor , nosso Deus, lhes dará."

[[v6-1-12]]

^<<v6-1-12,12>>^ E Josué disse às tribos  de Rúben, de Gade e de Manassés do Leste:

[[v6-1-13]]

^<<v6-1-13,13>>^ — Lembrem da ordem de Moisés, servo  do Senhor : "O Senhor , nosso Deus, dará esta terra a vocês para morarem nela e ali viverem em segurança.

[[v6-1-14]]

^<<v6-1-14,14>>^ As suas mulheres, as crianças e o gado ficarão aqui na terra que Moisés lhes deu a leste do rio Jordão. Mas que os homens peguem as suas armas e atravessem o rio na frente dos seus irmãos israelitas e estejam prontos para ajudá-los na batalha!

[[v6-1-15]]

^<<v6-1-15,15>>^ Eles tomarão posse da terra que o Senhor , nosso Deus, lhes dará e ficarão morando nela. Quando isso acontecer, vocês voltarão para viver na terra que Moisés, servo de Deus, deu a vocês aqui, a leste do Jordão."

[[v6-1-16]]

^<<v6-1-16,16>>^ Então eles responderam a Josué: — Faremos tudo o que você mandou e iremos aonde nos enviar.

[[v6-1-17]]

^<<v6-1-17,17>>^ Assim como sempre obedecemos a Moisés, também obedeceremos a você. Que o Senhor , seu Deus, esteja com você como esteve com Moisés!

[[v6-1-18]]

^<<v6-1-18,18>>^ Quem se revoltar e desobedecer a qualquer ordem sua será morto. Acima de tudo seja forte e corajoso!

'''

xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[&#60; Capítulo Anterior] | <<v6-1-0,Topo>> | xref:006-josue/006-josue-002.adoc#v6-2-0[Próximo Capítulo &#62;]