include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-8-1]]

^<<v6-8-1,1>>^ O Senhor  Deus disse a Josué: — Não tenha medo! Seja corajoso! Marche com todos os seus soldados contra a cidade de Ai. Eu farei com que derrotem o rei de lá. O povo de Ai, a sua cidade e as suas terras serão de vocês.

[[v6-8-2]]

^<<v6-8-2,2>>^ Vocês vão fazer com essa cidade o que fizeram com Jericó, mas desta vez todos os objetos e o gado vão ficar para vocês. Preparem-se para atacar a cidade de surpresa e por trás.

[[v6-8-3]]

^<<v6-8-3,3>>^ Então Josué e todos os soldados se prepararam para marchar contra Ai. Ele escolheu trinta mil homens corajosos e os enviou de noite

[[v6-8-4]]

^<<v6-8-4,4>>^ com estas ordens: — Escondam-se do outro lado da cidade. Não fiquem muito longe e estejam prontos para atacar.

[[v6-8-5]]

^<<v6-8-5,5>>^ Eu e os meus soldados vamos avançar na direção da cidade. Quando os soldados de Ai saírem contra nós, vamos fugir como na primeira vez.

[[v6-8-6]]

^<<v6-8-6,6>>^ Eles vão sair atrás de nós, afastando-se da cidade. Vão pensar que estamos fugindo deles como na primeira vez.

[[v6-8-7]]

^<<v6-8-7,7>>^ Então vocês sairão dos esconderijos e tomarão a cidade. O Senhor , nosso Deus, entregará Ai a vocês.

[[v6-8-8]]

^<<v6-8-8,8>>^ Depois que tomarem a cidade, ponham fogo nela, como o Senhor  mandou. São essas as minhas ordens.

[[v6-8-9]]

^<<v6-8-9,9>>^ Assim Josué enviou os soldados, e eles foram se esconder a oeste de Ai, entre Ai e Betel. Mas Josué passou a noite no acampamento.

[[v6-8-10]]

^<<v6-8-10,10>>^ Levantou-se de madrugada e reuniu os soldados. Ele e os líderes de Israel marcharam na frente do povo na direção de Ai.

[[v6-8-11]]

^<<v6-8-11,11>>^ Os soldados que iam com Josué marcharam na direção do portão principal da cidade e acamparam no lado norte. Havia um vale entre eles e Ai.

[[v6-8-12]]

^<<v6-8-12,12>>^ Josué reuniu uns cinco mil homens e os pôs em esconderijos a oeste, entre Ai e Betel.

[[v6-8-13]]

^<<v6-8-13,13>>^ Os soldados estavam colocados assim para a batalha: o acampamento principal, ao norte da cidade; e os outros, a oeste. E Josué passou a noite no vale.

[[v6-8-14]]

^<<v6-8-14,14>>^ O rei de Ai agiu depressa quando viu os israelitas. Ele e todos os seus soldados saíram de madrugada e foram lutar contra os israelitas no mesmo lugar de antes, em frente do vale do Jordão. Ele não sabia que ia ser atacado por trás.

[[v6-8-15]]

^<<v6-8-15,15>>^ Josué e os seus soldados fingiram que estavam sendo derrotados e fugiram para o deserto.

[[v6-8-16]]

^<<v6-8-16,16>>^ Todos os homens de Ai tinham sido convocados para ir atrás dos israelitas; e, enquanto perseguiam Josué, iam se afastando cada vez mais da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ Todos os homens de Ai saíram atrás dos israelitas, e a cidade ficou aberta, sem ninguém para defendê-la.

[[v6-8-18]]

^<<v6-8-18,18>>^ Então o Senhor  disse a Josué: — Aponte a sua lança na direção de Ai, pois vou dar esta cidade a você. E Josué obedeceu.

[[v6-8-19]]

^<<v6-8-19,19>>^ Quando ele levantou a mão, os homens que estavam escondidos se levantaram depressa, correram, tomaram a cidade e em seguida puseram fogo nela.

[[v6-8-20]]

^<<v6-8-20,20>>^ Quando os homens de Ai olharam para trás, viram a fumaça, que subia para o céu. Porém não puderam fugir para lado nenhum porque os israelitas que haviam corrido para o deserto deram meia-volta e os atacaram.

[[v6-8-21]]

^<<v6-8-21,21>>^ Josué e os seus soldados viram que os outros tinham tomado a cidade e posto fogo nela. Então deram meia-volta e começaram a matar os homens de Ai.

[[v6-8-22]]

^<<v6-8-22,22>>^ Os israelitas que estavam na cidade também saíram para atacar os homens de Ai. Esses homens foram completamente cercados e mortos pelos israelitas;

[[v6-8-23]]

^<<v6-8-23,23>>^ só ficou vivo o rei de Ai, que foi preso e levado a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ Os israelitas mataram todos os inimigos em campo aberto, no deserto onde haviam sido perseguidos. Depois voltaram para Ai e mataram os que estavam lá.

[[v6-8-25]]

^<<v6-8-25,25>>^ Nesse dia foram mortos todos os moradores de Ai — doze mil pessoas.

[[v6-8-26]]

^<<v6-8-26,26>>^ Josué continuou a apontar a lança na direção de Ai e não a abaixou até que todas as pessoas da cidade foram mortas.

[[v6-8-27]]

^<<v6-8-27,27>>^ Os israelitas ficaram com as coisas que pegaram na cidade, como o Senhor  havia ordenado que Josué fizesse.

[[v6-8-28]]

^<<v6-8-28,28>>^ Josué incendiou Ai, que virou um montão de ruínas para sempre, como se pode ver até hoje .

[[v6-8-29]]

^<<v6-8-29,29>>^ Ele enforcou o rei de Ai numa árvore e o deixou ali até de tarde. Ao pôr do sol mandou que tirassem o corpo e o jogassem no portão de entrada da cidade. E o cobriram com um montão de pedras, que está naquele lugar até hoje.

[[v6-8-30]]

^<<v6-8-30,30>>^ Nessa ocasião Josué construiu no monte Ebal um altar ao Senhor , o Deus de Israel.

[[v6-8-31]]

^<<v6-8-31,31>>^ Ele seguiu as ordens que Moisés, servo  do Senhor , tinha dado aos israelitas, como está escrito na Lei  de Moisés: "Faça um altar de pedras brutas, que não foram cortadas com ferramentas." Sobre esse altar apresentaram ao Senhor  ofertas que foram completamente queimadas e ofertas de paz.

[[v6-8-32]]

^<<v6-8-32,32>>^ Ali, na frente do povo, Josué copiou em pedras a lei que Moisés tinha escrito.

[[v6-8-33]]

^<<v6-8-33,33>>^ E todos os israelitas, com os seus líderes, autoridades e juízes e também todos os estrangeiros que viviam no meio deles ficaram de um lado e de outro da arca da aliança . E outros ficaram de frente para os sacerdotes levitas  que carregavam a arca. Metade do povo ficou em frente do monte Gerizim, e a outra metade, em frente do monte Ebal. Moisés, servo do Senhor , tinha dado ordem para o povo se colocar nessa posição na hora de receber a bênção.

[[v6-8-34]]

^<<v6-8-34,34>>^ Então Josué leu em voz alta toda a lei, com as bênçãos e as maldições, como estão escritas no Livro da Lei .

[[v6-8-35]]

^<<v6-8-35,35>>^ Cada um dos mandamentos de Moisés foi lido por Josué para toda a multidão de israelitas e para as mulheres, crianças e estrangeiros que viviam entre eles. Nenhuma palavra deixou de ser lida.

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]