include::./index.adoc[]

[[v6-16-0]]
=== Josué, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-16-1]]

^<<v6-16-1,1>>^ As terras que foram dadas aos descendentes de José iam desde o rio Jordão, perto da cidade de Jericó, até o deserto. De Jericó elas continuavam pela região montanhosa até a cidade de Betel.

[[v6-16-2]]

^<<v6-16-2,2>>^ De Betel a divisa ia até a cidade de Luz, chegando a Atarote, onde viviam os arquitas.

[[v6-16-3]]

^<<v6-16-3,3>>^ Daí seguia para o oeste, na divisa com os jafletitas, até a região de Bete-Horom-de-Baixo. Então ia até Gezer e terminava no mar Mediterrâneo.

[[v6-16-4]]

^<<v6-16-4,4>>^ As tribos  de Manassés e Efraim, descendentes de José, receberam essas terras como sua propriedade.

[[v6-16-5]]

^<<v6-16-5,5>>^ As terras das famílias da tribo  de Efraim são citadas em seguida. A sua divisa a leste era a cidade de Atarote-Adar, até Bete-Horom-de-Cima.

[[v6-16-6]]

^<<v6-16-6,6>>^ Dali ia até o mar Mediterrâneo. Micmeta ficava ao norte. A leste a divisa voltava até a cidade de Taanate-Siló e passava além dela, a leste, indo até Janoa.

[[v6-16-7]]

^<<v6-16-7,7>>^ Daí descia até as cidades de Atarote e Naarate. Chegava até Jericó e terminava no rio Jordão.

[[v6-16-8]]

^<<v6-16-8,8>>^ Para o oeste a divisa ia da cidade de Tapua ao riacho de Caná e terminava no mar Mediterrâneo. Estas foram as terras dadas às famílias da tribo de Efraim para serem propriedade delas.

[[v6-16-9]]

^<<v6-16-9,9>>^ A tribo de Efraim também recebeu alguns povoados e aldeias que estavam dentro das terras da tribo de Manassés.

[[v6-16-10]]

^<<v6-16-10,10>>^ Porém os cananeus que viviam em Gezer não foram expulsos. Eles continuam a viver no meio dos efraimitas até hoje , mas são obrigados a trabalhar como escravos.

'''

xref:006-josue/006-josue-015.adoc#v6-15-0[&#60; Capítulo Anterior] | <<v6-16-0,Topo>> | xref:006-josue/006-josue-017.adoc#v6-17-0[Próximo Capítulo &#62;]