include::./index.adoc[]

[[v6-13-0]]
=== Josué, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-13-1]]

^<<v6-13-1,1>>^ Quando Josué já estava bem velho, o Senhor  disse: — Você já está muito velho, e ainda há muita terra para ser conquistada.

[[v6-13-2]]

^<<v6-13-2,2>>^ Falta conquistar a região dos filisteus e dos gesuritas.

[[v6-13-3]]

^<<v6-13-3,3>>^ (Essa terra, que vai desde o riacho de Sior, na divisa do Egito, até a divisa de Ecrom, no Norte, pertencia aos cananeus; os governadores dos filisteus viviam nas cidades de Gaza, Asdode, Asquelom, Gate e Ecrom.) Falta conquistar a terra de Avim,

[[v6-13-4]]

^<<v6-13-4,4>>^ no Sul, toda a terra dos cananeus e Meara (que pertencia aos sidônios), até Afeca, na divisa com os amorreus.

[[v6-13-5]]

^<<v6-13-5,5>>^ Também falta a terra dos gebalitas; e, na direção do leste, todo o Líbano, desde Baal-Gade, ao pé do monte Hermom, até a subida de Hamate.

[[v6-13-6]]

^<<v6-13-6,6>>^ Finalmente, faltam todos os sidônios que vivem na região montanhosa entre os montes Líbanos e Misrefote-Maim. Eu expulsarei essa gente conforme o povo de Israel for avançando. Divida desde já a terra para que o povo de Israel fique dono dela como mandei antes.

[[v6-13-7]]

^<<v6-13-7,7>>^ Portanto, reparta essa terra entre as outras nove tribos  e a metade oeste da tribo de Manassés. Essa terra será dessas tribos.

[[v6-13-8]]

^<<v6-13-8,8>>^ As tribos  de Rúben e de Gade e a outra metade da tribo de Manassés haviam recebido as suas terras, que ficam a leste do rio Jordão. Era isso que Moisés, servo  do Senhor , lhes tinha dado.

[[v6-13-9]]

^<<v6-13-9,9>>^ As suas terras iam desde Aroer, na beira do vale do Arnom, e desde a cidade que ficava no meio daquele vale, até Dibom, incluindo todo o planalto de Medeba.

[[v6-13-10]]

^<<v6-13-10,10>>^ Faziam parte das suas terras todas as cidades governadas por Seom, o rei dos amorreus, que reinava em Hesbom, e iam até a divisa com os amonitas.

[[v6-13-11]]

^<<v6-13-11,11>>^ As suas terras incluíam ainda Gileade e a região onde os gesuritas e os maacatitas moravam e também todo o monte Hermom e toda a região de Basã até Salca.

[[v6-13-12]]

^<<v6-13-12,12>>^ Incluíam finalmente o reino de Ogue. Ogue, que foi o último dos refains , reinava em Astarote e em Edrei. Moisés tinha derrotado e expulsado esse povo.

[[v6-13-13]]

^<<v6-13-13,13>>^ Mas os gesuritas e os maacatitas não foram expulsos; eles ainda vivem no meio do povo de Israel.

[[v6-13-14]]

^<<v6-13-14,14>>^ Porém Moisés não tinha dado terras à tribo de Levi. As propriedades dos levitas  eram os alimentos trazidos a Deus, o Senhor , como oferta, conforme ele havia ordenado a Moisés.

[[v6-13-15]]

^<<v6-13-15,15>>^ Moisés tinha dado uma parte da terra às famílias da tribo  de Rúben, para ser propriedade delas.

[[v6-13-16]]

^<<v6-13-16,16>>^ Essas terras iam desde Aroer, na beira do vale do Arnom, e desde a cidade que ficava no meio do vale, até Medeba e todo o planalto ao seu redor.

[[v6-13-17]]

^<<v6-13-17,17>>^ Incluíam Hesbom e todas as cidades do planalto, isto é, Dibom, Bamote-Baal, Bete-Baal-Meom,

[[v6-13-18]]

^<<v6-13-18,18>>^ Jasa, Quedemote, Mefaate,

[[v6-13-19]]

^<<v6-13-19,19>>^ Quiriataim, Sibma e Zerete-Saar, no monte do vale.

[[v6-13-20]]

^<<v6-13-20,20>>^ Também Bete-Peor, a subida do monte Pisga, Bete-Jesimote,

[[v6-13-21]]

^<<v6-13-21,21>>^ todas as outras cidades do planalto e todas as cidades de Seom, o rei dos amorreus, que reinou em Hesbom. Moisés havia derrotado o reino de Seom e os príncipes de Midiã: Evi, Requém, Zur, Hur e Reba. Todos esses viviam nessa terra e reinavam dominados por Seom.

[[v6-13-22]]

^<<v6-13-22,22>>^ Entre os que foram mortos pelo povo de Israel estava Balaão, o adivinho, filho de Beor.

[[v6-13-23]]

^<<v6-13-23,23>>^ A oeste a divisa da tribo de Rúben era o rio Jordão. Estas foram as cidades e povoados dados às famílias da tribo de Rúben, para serem propriedade delas.

[[v6-13-24]]

^<<v6-13-24,24>>^ Moisés também tinha dado uma parte da terra às famílias da tribo  de Gade, para ser propriedade delas.

[[v6-13-25]]

^<<v6-13-25,25>>^ As suas terras incluíam Jazer, todas as cidades de Gileade e metade da terra dos amonitas até Aroer, que fica a leste de Rabá.

[[v6-13-26]]

^<<v6-13-26,26>>^ Iam de Hesbom até Ramá-Mispa e Betonim e de Maanaim até a divisa de Lo-Debar.

[[v6-13-27]]

^<<v6-13-27,27>>^ No vale do Jordão, incluíam as cidades de Bete-Arã, Bete-Ninra, Sucote e Zafom e também o resto do reino de Seom, rei de Hesbom. A oeste o limite das terras de Gade era o rio Jordão, até o lago da Galileia, no Norte.

[[v6-13-28]]

^<<v6-13-28,28>>^ Estas foram as cidades e povoados dados às famílias da tribo de Gade, para serem propriedade delas.

[[v6-13-29]]

^<<v6-13-29,29>>^ Moisés tinha dado uma parte da terra às famílias de uma das metades da tribo  de Manassés, para ser propriedade delas.

[[v6-13-30]]

^<<v6-13-30,30>>^ As suas terras começavam na cidade de Maanaim e incluíam toda a região de Basã, que pertencia ao rei Ogue, e também todas as sessenta cidades que eram de Jair, em Basã.

[[v6-13-31]]

^<<v6-13-31,31>>^ Incluíam a metade da região de Gileade, Astarote e Edrei, cidades do reino de Ogue, em Basã. Essas terras foram dadas às famílias de metade dos descendentes de Maquir, filho de Manassés.

[[v6-13-32]]

^<<v6-13-32,32>>^ Assim Moisés, nas planícies de Moabe, tinha dividido a terra que ficava a leste da cidade de Jericó e do rio Jordão.

[[v6-13-33]]

^<<v6-13-33,33>>^ Mas ele não deu nenhuma parte da terra à tribo de Levi, para ser propriedade dela. Moisés disse aos membros dessa tribo que o Senhor , o Deus de Israel, era a propriedade deles.

'''

xref:006-josue/006-josue-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-josue/006-josue-014.adoc#v6-14-0[Próximo Capítulo &#62;]