include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-11-1]]

^<<v6-11-1,1>>^ Essas coisas chegaram aos ouvidos de Jabim, rei de Hazor. E ele mandou mensageiros aos seguintes reis: a Jobabe, rei de Madom; aos reis de Sinrom e Acsafe;

[[v6-11-2]]

^<<v6-11-2,2>>^ aos reis da região montanhosa, ao norte; aos do vale do Jordão, ao sul do lago da Galileia; e aos da planície e do litoral, perto de Dor.

[[v6-11-3]]

^<<v6-11-3,3>>^ Também enviou mensageiros aos cananeus dos dois lados do rio Jordão, aos amorreus, aos heteus, aos perizeus, aos jebuseus da região montanhosa e aos heveus, que viviam ao pé do monte Hermom, na terra de Mispa.

[[v6-11-4]]

^<<v6-11-4,4>>^ Eles foram com todos os seus soldados — um exército com tantos homens quantos são os grãos de areia da praia do mar. Tinham também muitos cavalos e carros de guerra.

[[v6-11-5]]

^<<v6-11-5,5>>^ Todos esses reis juntaram os seus soldados e acamparam perto do riacho de Merom, para lutar contra o povo de Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ O Senhor  Deus disse a Josué: — Não fique com medo deles. Amanhã, a esta mesma hora, eu matarei toda essa gente para Israel. Você aleijará os cavalos deles e queimará os seus carros.

[[v6-11-7]]

^<<v6-11-7,7>>^ Assim Josué e todos os seus soldados atacaram de surpresa perto do riacho de Merom,

[[v6-11-8]]

^<<v6-11-8,8>>^ e o Senhor  Deus deu a vitória aos israelitas. Eles atacaram os inimigos e os perseguiram até a grande Sidom e Misrefote-Maim e até o vale de Mispa, a leste. Continuaram a lutar até matarem todos os inimigos.

[[v6-11-9]]

^<<v6-11-9,9>>^ Josué fez como o Senhor  havia mandado: aleijou os cavalos deles e queimou os seus carros de guerra.

[[v6-11-10]]

^<<v6-11-10,10>>^ Então Josué voltou, tomou a cidade de Hazor e matou o seu rei. Nesse tempo Hazor era o mais poderoso de todos esses reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ Os israelitas mataram todos os moradores, e a cidade foi queimada.

[[v6-11-12]]

^<<v6-11-12,12>>^ Josué tomou todas essas cidades e os seus reis. Matou todos, conforme a ordem de Moisés, servo  do Senhor .

[[v6-11-13]]

^<<v6-11-13,13>>^ Mas os israelitas não queimaram nenhuma das cidades construídas sobre ruínas , a não ser Hazor, que Josué incendiou.

[[v6-11-14]]

^<<v6-11-14,14>>^ Os israelitas ficaram com todos os objetos de valor e com o gado dessas cidades. Mas todas as pessoas foram mortas; não ficou ninguém vivo.

[[v6-11-15]]

^<<v6-11-15,15>>^ O Senhor  tinha dado essas ordens ao seu servo Moisés; Moisés as deu a Josué, e Josué obedeceu. Ele fez tudo o que o Senhor  havia mandado Moisés fazer.

[[v6-11-16]]

^<<v6-11-16,16>>^ Josué tomou toda aquela terra, isto é, a região montanhosa de Judá, toda a região sul, toda a terra de Gosém, as planícies de Judá, o vale do Jordão e também a região montanhosa e as planícies do litoral de Israel.

[[v6-11-17]]

^<<v6-11-17,17>>^ Essa região ia desde o monte Halaque, perto de Seir, até Baal-Gade, no vale do Líbano, ao pé do monte Hermom. Josué matou todos os reis desses lugares

[[v6-11-18]]

^<<v6-11-18,18>>^ nas guerras que fez por longo tempo contra eles.

[[v6-11-19]]

^<<v6-11-19,19>>^ Nenhuma dessas cidades fez acordos  de paz com Israel, a não ser Gibeão, onde moravam alguns heveus. As outras cidades foram tomadas na guerra.

[[v6-11-20]]

^<<v6-11-20,20>>^ O Senhor  Deus fez com que os moradores dessas cidades teimassem em lutar contra o povo de Israel, para que, assim, fossem completamente destruídos e mortos sem dó nem piedade. O Senhor  havia ordenado isso a Moisés.

[[v6-11-21]]

^<<v6-11-21,21>>^ Nessa ocasião Josué foi e acabou com os gigantes anaquins  que viviam nas montanhas: em Hebrom, Debir, Anabe e em toda a região montanhosa de Judá e de Israel. Josué acabou completamente com eles e destruiu as suas cidades.

[[v6-11-22]]

^<<v6-11-22,22>>^ Nenhum dos anaquins ficou na terra de Israel. Somente alguns continuaram a viver nas cidades de Gaza, Gate e Asdode.

[[v6-11-23]]

^<<v6-11-23,23>>^ Como o Senhor  havia ordenado a Moisés, Josué tomou a terra e a deu aos israelitas para ser propriedade deles. Ele dividiu a terra e deu uma parte a cada tribo . E assim a guerra acabou.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]