include::./index.adoc[]

[[v6-21-0]]
=== Josué, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-21-1]]

^<<v6-21-1,1>>^ Os chefes das famílias dos levitas  foram até a cidade de Siló, na terra de Canaã. Ali falaram com o sacerdote Eleazar, com Josué, filho de Num, e com os chefes das famílias de todas as tribos  de Israel. Eles disseram: — O Senhor  Deus ordenou, por meio de Moisés, que nos dessem cidades para morar e também pastos ao redor delas para o nosso gado.

[[v6-21-2]]

^<<v6-21-2,2>>^ Os chefes das famílias dos levitas  foram até a cidade de Siló, na terra de Canaã. Ali falaram com o sacerdote Eleazar, com Josué, filho de Num, e com os chefes das famílias de todas as tribos  de Israel. Eles disseram:

[[v6-21-3]]

^<<v6-21-3,3>>^ E os israelitas, obedecendo à ordem de Deus, o Senhor , deram das suas terras cidades e pastos para os levitas.

[[v6-21-4]]

^<<v6-21-4,4>>^ As famílias dos coatitas foram as primeiras a receber cidades. Os levitas que eram descendentes do sacerdote Arão receberam treze cidades das tribos de Judá, Simeão e Benjamim.

[[v6-21-5]]

^<<v6-21-5,5>>^ Os outros coatitas receberam dez cidades das famílias das tribos de Efraim e de Dã e da metade oeste da tribo de Manassés.

[[v6-21-6]]

^<<v6-21-6,6>>^ Os gersonitas receberam treze cidades das famílias das tribos de Issacar, Aser, Naftali e da metade da tribo de Manassés que estava em Basã, a leste do Jordão.

[[v6-21-7]]

^<<v6-21-7,7>>^ As famílias dos meraritas receberam doze cidades das tribos de Rúben, Gade e Zebulom.

[[v6-21-8]]

^<<v6-21-8,8>>^ O povo de Israel, por meio de sorteio , separou para os levitas essas cidades e os pastos ao redor delas, como o Senhor  havia ordenado por meio de Moisés.

[[v6-21-9]]

^<<v6-21-9,9>>^ São citadas a seguir as cidades das tribos de Judá e de Simeão que foram dadas

[[v6-21-10]]

^<<v6-21-10,10>>^ aos descendentes de Arão que eram do grupo de famílias de Coate, filho de Levi. As terras dos coatitas foram as primeiras a serem sorteadas.

[[v6-21-11]]

^<<v6-21-11,11>>^ Deram a essas famílias a cidade de Quiriate-Arba (Arba foi o pai de Anaque), que é Hebrom, na região montanhosa de Judá, e os pastos ao seu redor.

[[v6-21-12]]

^<<v6-21-12,12>>^ Mas os campos em volta da cidade e os seus povoados tinham sido dados a Calebe, filho de Jefoné, como sua propriedade.

[[v6-21-13]]

^<<v6-21-13,13>>^ Aos descendentes de Arão deram Hebrom com os seus pastos. Esta era uma das cidades para os fugitivos que tivessem matado alguém. Deram também as cidades de Libna,

[[v6-21-14]]

^<<v6-21-14,14>>^ Jatir, Estemoa,

[[v6-21-15]]

^<<v6-21-15,15>>^ Holom, Debir,

[[v6-21-16]]

^<<v6-21-16,16>>^ Aim, Jutá e Bete-Semes, com os seus pastos. Ao todo nove cidades das tribos de Judá e de Simeão.

[[v6-21-17]]

^<<v6-21-17,17>>^ Da tribo de Benjamim deram quatro cidades: Gibeão, Geba,

[[v6-21-18]]

^<<v6-21-18,18>>^ Anatote e Almom.

[[v6-21-19]]

^<<v6-21-19,19>>^ Ao todo foram dadas treze cidades com os seus pastos aos sacerdotes, que eram descendentes de Arão.

[[v6-21-20]]

^<<v6-21-20,20>>^ Para as outras famílias coatitas, que eram levitas, eles deram algumas cidades da tribo de Efraim.

[[v6-21-21]]

^<<v6-21-21,21>>^ Essas famílias receberam Siquém e os seus pastos na região montanhosa de Efraim. Siquém era uma das cidades para os fugitivos que tivessem matado alguém. Os coatitas receberam também Gezer,

[[v6-21-22]]

^<<v6-21-22,22>>^ Quibzaim e Bete-Horom, com os seus pastos. Ao todo quatro cidades.

[[v6-21-23]]

^<<v6-21-23,23>>^ Da tribo de Dã eles receberam quatro cidades: Elteque, Gibetom,

[[v6-21-24]]

^<<v6-21-24,24>>^ Aijalom e Gate-Rimom, com os seus pastos.

[[v6-21-25]]

^<<v6-21-25,25>>^ Da metade oeste da tribo de Manassés eles receberam duas cidades: Taanaque e Gate-Rimom, com os seus pastos.

[[v6-21-26]]

^<<v6-21-26,26>>^ Essas famílias coatitas receberam ao todo dez cidades com os seus pastos.

[[v6-21-27]]

^<<v6-21-27,27>>^ Os gersonitas, que eram outra família de levitas, receberam da metade leste da tribo de Manassés a cidade de Golã, em Basã, com os seus pastos. Esta era uma das cidades para os fugitivos que tivessem matado alguém. Os gersonitas receberam também a cidade de Beesterá com os seus pastos.

[[v6-21-28]]

^<<v6-21-28,28>>^ Da tribo de Issacar eles receberam quatro cidades: Quisião, Daberate,

[[v6-21-29]]

^<<v6-21-29,29>>^ Jarmute e En-Ganim, com os seus pastos.

[[v6-21-30]]

^<<v6-21-30,30>>^ Da tribo de Aser eles receberam quatro cidades: Misal, Abdom,

[[v6-21-31]]

^<<v6-21-31,31>>^ Helcate e Reobe, com os seus pastos.

[[v6-21-32]]

^<<v6-21-32,32>>^ Da tribo de Naftali receberam a cidade de Quedes, na Galileia, com os seus pastos. Quedes era uma cidade para os fugitivos que tivessem matado alguém. Os gersonitas receberam também Hamote-Dor e Cartã, com os seus pastos. Ao todo três cidades.

[[v6-21-33]]

^<<v6-21-33,33>>^ As várias famílias dos gersonitas receberam ao todo treze cidades com os seus pastos.

[[v6-21-34]]

^<<v6-21-34,34>>^ Os outros levitas, isto é, as famílias meraritas, receberam da tribo de Zebulom quatro cidades: Jocneão, Cartá,

[[v6-21-35]]

^<<v6-21-35,35>>^ Dimna e Naalal, com os seus pastos.

[[v6-21-36]]

^<<v6-21-36,36>>^ Da tribo de Rúben eles receberam quatro cidades: Bezer, Jasa,

[[v6-21-37]]

^<<v6-21-37,37>>^ Quedemote e Mefaate, com os seus pastos.

[[v6-21-38]]

^<<v6-21-38,38>>^ Da tribo de Gade eles receberam Ramote, em Gileade, com os seus pastos. Ramote era uma das cidades para os fugitivos que tivessem matado alguém. Os meraritas receberam também Maanaim,

[[v6-21-39]]

^<<v6-21-39,39>>^ Hesbom e Jazer, com os seus pastos. Ao todo quatro cidades.

[[v6-21-40]]

^<<v6-21-40,40>>^ Esses levitas, isto é, as várias famílias meraritas, receberam doze cidades ao todo.

[[v6-21-41]]

^<<v6-21-41,41>>^ Das terras dos israelitas foram dadas aos levitas, ao todo, quarenta e oito cidades com os seus pastos.

[[v6-21-42]]

^<<v6-21-42,42>>^ Cada uma dessas cidades tinha pastos ao seu redor.

[[v6-21-43]]

^<<v6-21-43,43>>^ Assim o Senhor  Deus deu aos israelitas toda a terra que havia prometido aos seus antepassados. E, quando tomaram posse da terra, eles passaram a morar nela.

[[v6-21-44]]

^<<v6-21-44,44>>^ O Senhor  lhes deu paz com os povos vizinhos, conforme havia prometido aos seus antepassados. Nenhum dos inimigos conseguiu resistir, pois o Senhor  deu ao povo de Israel a vitória sobre eles.

'''

xref:006-josue/006-josue-020.adoc#v6-20-0[&#60; Capítulo Anterior] | <<v6-21-0,Topo>> | xref:006-josue/006-josue-022.adoc#v6-22-0[Próximo Capítulo &#62;]