include::./index.adoc[]

[[v6-7-0]]
=== Josué, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-7-1]]

^<<v6-7-1,1>>^ Deus havia ordenado ao povo de Israel que ninguém guardasse nada do que era para ser destruído, mas a ordem foi desobedecida. Acã escondeu algumas coisas, e por isso o Senhor  ficou muito irado  com os israelitas. Acã era filho de Carmi, descendente de Zabdi e descendente de Zera, da tribo  de Judá.

[[v6-7-2]]

^<<v6-7-2,2>>^ Josué enviou alguns homens da cidade de Jericó até Ai, cidade que fica a leste de Betel, perto de Bete-Avém. Ele mandou que fossem ver a terra. Eles foram e examinaram bem a cidade.

[[v6-7-3]]

^<<v6-7-3,3>>^ Então voltaram e deram a Josué o seguinte relatório: — Não é preciso que todo mundo vá. Mande só dois ou três mil homens atacarem Ai porque existe pouca gente lá.

[[v6-7-4]]

^<<v6-7-4,4>>^ Assim foram mais ou menos três mil. Porém os homens de Ai fizeram os israelitas recuarem

[[v6-7-5]]

^<<v6-7-5,5>>^ e mataram uns trinta e seis. E eles perseguiram os israelitas desde o portão da cidade até as pedreiras, matando-os na descida. Então o povo ficou completamente desanimado e perdeu toda a coragem.

[[v6-7-6]]

^<<v6-7-6,6>>^ Em sinal de tristeza, Josué rasgou a sua roupa e se jogou no chão, com o rosto em terra, na frente da arca da aliança  de Deus, o Senhor . Os líderes de Israel fizeram a mesma coisa e ficaram ali com Josué até de tarde. E fizeram como ele: também jogaram terra na cabeça para mostrar que estavam tristes.

[[v6-7-7]]

^<<v6-7-7,7>>^ E Josué disse: — Ó Senhor , meu Deus! Afinal de contas, por que fizeste este povo atravessar o rio Jordão? Foi para nos entregares aos amorreus, e eles nos matarem? Por que não ficamos do outro lado do Jordão?

[[v6-7-8]]

^<<v6-7-8,8>>^ Senhor, peço desculpas, mas já que Israel fugiu do inimigo, o que posso dizer?

[[v6-7-9]]

^<<v6-7-9,9>>^ Os cananeus e todos os outros moradores desta terra vão saber disso. Eles nos cercarão e nos matarão a todos. E neste caso o que farás em favor do teu grande nome?

[[v6-7-10]]

^<<v6-7-10,10>>^ O Senhor  Deus respondeu a Josué: — Levante-se! Por que é que você está aí desse jeito, com a cara no chão?

[[v6-7-11]]

^<<v6-7-11,11>>^ O povo de Israel pecou. Eles quebraram a aliança  que haviam feito comigo, a aliança que eu mandei que guardassem. Ficaram com algumas coisas que eu mandei que fossem destruídas. Eles roubaram essas coisas, mentiram por causa delas e as colocaram no meio da bagagem deles.

[[v6-7-12]]

^<<v6-7-12,12>>^ É por isso que os israelitas não podem enfrentar o inimigo. Fogem dele porque agora eles mesmos estão condenados à destruição. Se vocês não destruírem o que roubaram, eu não continuarei com vocês.

[[v6-7-13]]

^<<v6-7-13,13>>^ Levante-se e vá santificar  o povo. Diga que se purifiquem  para amanhã porque eu, o Senhor , o Deus de Israel, digo isto: "Israelitas, vocês estão guardando algumas coisas que eu mandei destruir. Enquanto não se livrarem delas, vocês não poderão enfrentar os inimigos.

[[v6-7-14]]

^<<v6-7-14,14>>^ Amanhã vocês se apresentarão, tribo por tribo, e haverá sorteio . A tribo que eu indicar virá à frente, grupo de famílias por grupo de famílias. Aí o grupo de famílias que eu indicar virá à frente, família por família. Finalmente a família que eu indicar virá à frente, homem por homem.

[[v6-7-15]]

^<<v6-7-15,15>>^ Então aquele que o sorteio indicar que ficou com essas coisas será queimado: ele, a sua família e tudo o que possui. O que esse homem fez foi terrível: ele quebrou a aliança que o meu povo fez comigo."

[[v6-7-16]]

^<<v6-7-16,16>>^ Então Josué se levantou de madrugada e fez o povo de Israel se apresentar, tribo por tribo. O sorteio indicou a tribo de Judá.

[[v6-7-17]]

^<<v6-7-17,17>>^ Em seguida mandou que se apresentassem os grupos de famílias da tribo de Judá, e o grupo de Zera foi indicado. Aí chamou o grupo de Zera, família por família; e a família de Zabdi foi indicada.

[[v6-7-18]]

^<<v6-7-18,18>>^ Finalmente chamou a família de Zabdi, homem por homem, e Acã foi indicado. Acã era filho de Carmi, descendente de Zabdi, descendente de Zera, da tribo de Judá.

[[v6-7-19]]

^<<v6-7-19,19>>^ E Josué disse a Acã: — Agora, meu filho, confesse a verdade diante do Senhor , o Deus de Israel. Conte-me o que você fez; não procure esconder nada.

[[v6-7-20]]

^<<v6-7-20,20>>^ Acã respondeu: — Sim, eu pequei contra o Senhor , o Deus de Israel. Vou contar o que fiz.

[[v6-7-21]]

^<<v6-7-21,21>>^ Entre as coisas que pegamos, vi uma bela capa  da Babilônia; vi também duzentas barras de prata e uma barra de ouro que pesava mais ou menos meio quilo. Fiquei com tanta vontade de ter aquelas coisas, que guardei para mim. Estão escondidas, enterradas na minha barraca, e a prata está por baixo.

[[v6-7-22]]

^<<v6-7-22,22>>^ Então Josué mandou que alguns homens fossem depressa até a barraca; e eles, de fato, acharam as coisas enterradas e a prata por baixo.

[[v6-7-23]]

^<<v6-7-23,23>>^ Tiraram as coisas da barraca, e levaram a Josué e a todos os israelitas, e puseram tudo na presença de Deus, o Senhor .

[[v6-7-24]]

^<<v6-7-24,24>>^ Aí Josué e todo o povo de Israel pegaram Acã, a prata, a capa, a barra de ouro, os seus filhos e filhas, os seus bois, jumentos, ovelhas, a sua barraca e tudo o que ele tinha e os levaram para o vale da Desgraça.

[[v6-7-25]]

^<<v6-7-25,25>>^ E Josué disse: — Por que é que você fez essa desgraça cair sobre nós? Agora o Senhor  Deus vai fazer a desgraça cair sobre você! Em seguida o povo todo matou Acã a pedradas. Eles apedrejaram e queimaram a sua família e tudo o que ele tinha.

[[v6-7-26]]

^<<v6-7-26,26>>^ E puseram em cima dele um montão de pedras, que está naquele lugar até agora . É por isso que até hoje o nome daquele lugar é vale da Desgraça. Então a ira do Senhor  passou.

'''

xref:006-josue/006-josue-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-josue/006-josue-008.adoc#v6-8-0[Próximo Capítulo &#62;]