include::./index.adoc[]

[[v6-24-0]]
=== Josué, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-24-1]]

^<<v6-24-1,1>>^ Depois Josué reuniu em Siquém todas as tribos  de Israel. Chamou os conselheiros, os líderes, os juízes e os oficiais de Israel, e eles se apresentaram diante de Deus.

[[v6-24-2]]

^<<v6-24-2,2>>^ Então Josué disse a todo o povo: — O Senhor , o Deus de Israel, diz isto: "Há muito tempo, os antepassados de vocês viviam no outro lado do rio Eufrates e adoravam outros deuses. Tera, um desses antepassados, era pai de Abraão e de Naor.

[[v6-24-3]]

^<<v6-24-3,3>>^ Porém eu tirei Abraão da terra que está do outro lado do Eufrates e fiz com que ele andasse por toda a terra de Canaã. Eu lhe dei muitos descendentes: a Abraão eu dei Isaque

[[v6-24-4]]

^<<v6-24-4,4>>^ e a Isaque dei Jacó e Esaú. A Esaú eu dei, para ser sua propriedade, a região montanhosa de Seir; porém Jacó e os seus filhos desceram até o Egito.

[[v6-24-5]]

^<<v6-24-5,5>>^ Depois enviei Moisés e Arão e fiz uma grande destruição no Egito. Nessa ocasião tirei vocês de lá.

[[v6-24-6]]

^<<v6-24-6,6>>^ Fiz com que os seus antepassados saíssem do Egito, e eles chegaram até o mar Vermelho. Mas os egípcios os perseguiram até o mar, com carros de guerra e cavaleiros.

[[v6-24-7]]

^<<v6-24-7,7>>^ Então os israelitas me pediram socorro, e eu fiz com que uma escuridão os escondesse dos egípcios. E mandei que o mar caísse em cima dos egípcios e os cobrisse. Vocês viram o que eu fiz com o Egito. Depois vocês viveram no deserto por muito tempo.

[[v6-24-8]]

^<<v6-24-8,8>>^ — "Então eu os levei para a terra dos amorreus que moravam a leste do rio Jordão. Os amorreus os atacaram, mas eu dei a vitória a vocês. Vocês tomaram posse da terra deles, e eu os destruí diante de vocês.

[[v6-24-9]]

^<<v6-24-9,9>>^ Aí o rei de Moabe, Balaque, filho de Zipor, fez guerra contra Israel. Balaque mandou buscar Balaão, filho de Beor, e pediu que ele amaldiçoasse vocês.

[[v6-24-10]]

^<<v6-24-10,10>>^ Mas eu não quis ouvir Balaão, e assim ele os abençoou, e eu os salvei das mãos de Balaque.

[[v6-24-11]]

^<<v6-24-11,11>>^ Vocês atravessaram o rio Jordão e chegaram até a cidade de Jericó. Os homens de Jericó lutaram contra vocês, e depois também os amorreus, os perizeus, os cananeus, os heteus, os girgaseus, os heveus e os jebuseus. Eu fiz com que vocês vencessem a todos.

[[v6-24-12]]

^<<v6-24-12,12>>^ Antes de vocês chegarem, expulsei os dois reis amorreus, fazendo com que eles fugissem apavorados. Não foi nem pelas espadas nem pelos arcos e flechas de vocês que eles foram expulsos.

[[v6-24-13]]

^<<v6-24-13,13>>^ Eu dei a vocês uma terra em que vocês nunca haviam trabalhado e cidades que não haviam construído. E vocês estão vivendo nessas cidades e comendo uvas e azeitonas de parreiras  e oliveiras que não plantaram."

[[v6-24-14]]

^<<v6-24-14,14>>^ Josué terminou, dizendo: — Portanto, agora temam a Deus , o Senhor . Sejam seus servos  sinceros e fiéis. Esqueçam os deuses que os seus antepassados adoravam na Mesopotâmia e no Egito e sirvam o Senhor .

[[v6-24-15]]

^<<v6-24-15,15>>^ Mas, se vocês não querem ser servos do Senhor , decidam hoje a quem vão servir. Resolvam se vão servir os deuses que os seus antepassados adoravam na terra da Mesopotâmia ou os deuses dos amorreus, na terra de quem vocês estão morando agora. Porém eu e a minha família serviremos a Deus, o Senhor .

[[v6-24-16]]

^<<v6-24-16,16>>^ O povo respondeu: — Nunca poderíamos pensar em abandonar o Senhor  para servir outros deuses!

[[v6-24-17]]

^<<v6-24-17,17>>^ Foi o Senhor , nosso Deus, quem tirou a nós e aos nossos pais da escravidão na terra do Egito. E vimos as grandes coisas que ele fez. Ele nos guardou pelos caminhos por onde andamos e no meio dos países por onde passamos.

[[v6-24-18]]

^<<v6-24-18,18>>^ Conforme íamos avançando, o Senhor  ia expulsando todos aqueles povos e até os amorreus que moravam nesta terra. Portanto, nós também serviremos o Senhor , pois ele é o nosso Deus.

[[v6-24-19]]

^<<v6-24-19,19>>^ Josué disse ao povo: — Vocês não podem servir o Senhor , pois ele é Deus Santo e não tolera aqueles que adoram outros deuses. Ele não perdoará os pecados e as maldades de vocês.

[[v6-24-20]]

^<<v6-24-20,20>>^ Se abandonarem a Deus, o Senhor , e adorarem deuses estrangeiros, ele se voltará contra vocês e os castigará. Ele os destruirá, embora antes tenha sido bom para vocês.

[[v6-24-21]]

^<<v6-24-21,21>>^ O povo respondeu: — Que isso não aconteça! O que nós queremos é servir a Deus, o Senhor .

[[v6-24-22]]

^<<v6-24-22,22>>^ Então Josué disse: — Vocês mesmos são testemunhas de que escolheram servir o Senhor . — Sim, somos testemunhas! — responderam eles.

[[v6-24-23]]

^<<v6-24-23,23>>^ E Josué continuou: — Então joguem fora os deuses estrangeiros que estão com vocês e prometam que serão fiéis ao Senhor , o Deus de Israel.

[[v6-24-24]]

^<<v6-24-24,24>>^ O povo disse a Josué: — Serviremos o Senhor , nosso Deus, e obedeceremos aos seus mandamentos.

[[v6-24-25]]

^<<v6-24-25,25>>^ Assim naquele dia Josué fez um acordo  para o povo e ali em Siquém lhes deu leis  e regulamentos.

[[v6-24-26]]

^<<v6-24-26,26>>^ Josué os escreveu no Livro da Lei  de Deus. Em seguida pegou uma grande pedra e a colocou ali debaixo da árvore sagrada, no lugar onde adoravam a Deus, o Senhor .

[[v6-24-27]]

^<<v6-24-27,27>>^ E disse a todo o povo: — Olhem para esta pedra! Ela será nossa testemunha. Ela ouviu todas as palavras que o Senhor  nos tem falado. E também será testemunha contra vocês, para evitar que abandonem ao seu Deus.

[[v6-24-28]]

^<<v6-24-28,28>>^ Então Josué mandou o povo embora, cada um para a sua propriedade.

[[v6-24-29]]

^<<v6-24-29,29>>^ Depois disso, com a idade de cento e dez anos, morreu Josué, filho de Num e servo  do Senhor .

[[v6-24-30]]

^<<v6-24-30,30>>^ Ele foi sepultado na sua propriedade, em Timnate-Sera, na região montanhosa de Efraim, no lado norte do monte Gaás.

[[v6-24-31]]

^<<v6-24-31,31>>^ O povo de Israel serviu a Deus, o Senhor , enquanto Josué viveu. E também depois da sua morte, enquanto viveram os líderes que sabiam de tudo o que Deus havia feito pelo povo de Israel.

[[v6-24-32]]

^<<v6-24-32,32>>^ O corpo de José, que os israelitas tinham trazido do Egito, foi sepultado em Siquém, no pedaço de terra que Jacó havia comprado dos filhos de Hamor, pai de Siquém, por cem barras de prata . Os descendentes de José receberam essa terra como herança.

[[v6-24-33]]

^<<v6-24-33,33>>^ Eleazar, filho de Arão, também morreu e foi sepultado em Gibeá, na região montanhosa de Efraim. Essa cidade tinha sido dada ao seu filho Fineias.

'''

xref:006-josue/006-josue-023.adoc#v6-23-0[&#60; Capítulo Anterior] | <<v6-24-0,Topo>> | xref:007-juizes/007-juizes-001.adoc#v7-1-0[Próximo Capítulo &#62;]