include::./index.adoc[]

[[v6-5-0]]
=== Josué, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v6-5-1]]

^<<v6-5-1,1>>^ Todos os reis amorreus do lado oeste do rio Jordão e todos os reis cananeus que viviam no litoral do mar Mediterrâneo ficaram sabendo que o Senhor  havia secado o Jordão para o povo de Israel passar. E, como o povo de Israel estava chegando, eles ficaram com medo e perderam toda a coragem.

[[v6-5-2]]

^<<v6-5-2,2>>^ O Senhor  Deus disse a Josué: — Prepare algumas facas de pedra e faça uma segunda cerimônia de circuncisão  no meio do povo.

[[v6-5-3]]

^<<v6-5-3,3>>^ Josué fez as facas e circuncidou os israelitas no monte da Circuncisão.

[[v6-5-4]]

^<<v6-5-4,4>>^ Ele fez isso porque todos os homens que tinham idade para guerrear quando saíram do Egito haviam morrido pelo caminho, no deserto.

[[v6-5-5]]

^<<v6-5-5,5>>^ Todos os homens que saíram do Egito tinham sido circuncidados, mas isso não foi feito com nenhum dos que nasceram durante a viagem pelo deserto.

[[v6-5-6]]

^<<v6-5-6,6>>^ O povo de Israel havia andado quarenta anos pelo deserto. Durante esse tempo todos os homens que saíram do Egito em idade de guerrear tinham morrido porque haviam desobedecido a Deus, o Senhor . Deus tinha dito que não ia deixá-los ver a terra boa e rica que ele havia jurado dar aos seus antepassados.

[[v6-5-7]]

^<<v6-5-7,7>>^ Mas os filhos, que tomaram o lugar dos pais, não haviam sido circuncidados durante a viagem pelo deserto. Esta foi a nova geração  que Josué circuncidou.

[[v6-5-8]]

^<<v6-5-8,8>>^ A nação inteira ficou acampada até que sararam todos os que foram circuncidados.

[[v6-5-9]]

^<<v6-5-9,9>>^ E o Senhor  disse a Josué: — Hoje eu tirei de vocês a vergonha de terem sido escravos no Egito. Foi por isso que chamaram aquele lugar de Gilgal . E este nome continua até hoje .

[[v6-5-10]]

^<<v6-5-10,10>>^ Os israelitas estavam acampados em Gilgal, na planície em volta da cidade de Jericó, e ali comemoraram a Páscoa  na noite do dia catorze do primeiro mês.

[[v6-5-11]]

^<<v6-5-11,11>>^ No dia seguinte comeram alimentos daquela terra: cereais torrados e pão sem fermento .

[[v6-5-12]]

^<<v6-5-12,12>>^ Depois disso os israelitas não tiveram mais o maná  porque ele parou de cair do céu. Desse ano em diante, eles começaram a comer os alimentos da terra de Canaã.

[[v6-5-13]]

^<<v6-5-13,13>>^ Josué estava perto da cidade de Jericó. De repente, viu um homem com uma espada na mão parado na sua frente. Josué chegou perto dele e perguntou: — Você é do nosso exército ou é inimigo?

[[v6-5-14]]

^<<v6-5-14,14>>^ — Não sou nem uma coisa nem outra — respondeu ele. — Estou aqui como comandante do exército de Deus, o Senhor . Josué ajoelhou-se, encostou o rosto no chão e o adorou. E disse: — Estou às suas ordens, meu senhor. O que quer que eu faça?

[[v6-5-15]]

^<<v6-5-15,15>>^ O comandante do exército do Senhor  respondeu: — Tire as sandálias porque a terra que você está pisando é santa. E Josué obedeceu.

'''

xref:006-josue/006-josue-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-josue/006-josue-006.adoc#v6-6-0[Próximo Capítulo &#62;]