include::./index.adoc[]

[[v50-1-0]]
=== Filipenses, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v50-1-1]]

^<<v50-1-1,1>>^ Eu, Paulo, e Timóteo, servos  de Cristo Jesus, escrevemos esta carta para todos os moradores da cidade de Filipos que pertencem ao povo de Deus e que creem em Cristo Jesus e também para os bispos  e diáconos  da igreja.

[[v50-1-2]]

^<<v50-1-2,2>>^ Que a graça  e a paz de Deus, o nosso Pai, e do Senhor Jesus Cristo estejam com vocês!

[[v50-1-3]]

^<<v50-1-3,3>>^ Sempre que penso em vocês, eu agradeço ao meu Deus.

[[v50-1-4]]

^<<v50-1-4,4>>^ E, todas as vezes que oro em favor de vocês, oro com alegria

[[v50-1-5]]

^<<v50-1-5,5>>^ por causa da maneira como vocês me ajudaram no trabalho de anunciar o evangelho , desde o primeiro dia até hoje.

[[v50-1-6]]

^<<v50-1-6,6>>^ Pois eu estou certo de que Deus, que começou esse bom trabalho na vida de vocês, vai continuá-lo até que ele esteja completo no Dia de Cristo Jesus .

[[v50-1-7]]

^<<v50-1-7,7>>^ Vocês estão sempre no meu coração. E é justo que eu me sinta assim a respeito de vocês, pois vocês têm participado comigo desse privilégio que Deus me deu. É isso o que vocês estão fazendo agora que estou na cadeia e foi o mesmo que fizeram quando eu estava livre para defender e anunciar com firmeza o evangelho.

[[v50-1-8]]

^<<v50-1-8,8>>^ Deus é testemunha de que estou dizendo a verdade quando afirmo que o meu grande amor por todos vocês vem do próprio coração de Cristo Jesus.

[[v50-1-9]]

^<<v50-1-9,9>>^ O que eu peço a Deus é que o amor de vocês cresça cada vez mais e que tenham sabedoria e um entendimento completo,

[[v50-1-10]]

^<<v50-1-10,10>>^ a fim de que saibam escolher o melhor. Assim, no dia da vinda de Cristo, vocês estarão livres de toda impureza e de qualquer culpa.

[[v50-1-11]]

^<<v50-1-11,11>>^ A vida de vocês estará cheia das boas qualidades que só Jesus Cristo pode produzir, para a glória  e o louvor de Deus.

[[v50-1-12]]

^<<v50-1-12,12>>^ Meus irmãos, eu quero que vocês saibam que as coisas que me aconteceram ajudaram, de fato, o progresso do evangelho .

[[v50-1-13]]

^<<v50-1-13,13>>^ Pois foi assim que toda a guarda do palácio do Governador e todas as outras pessoas daqui ficaram sabendo que estou na cadeia porque sou servo  de Cristo.

[[v50-1-14]]

^<<v50-1-14,14>>^ E a maioria dos irmãos, vendo que estou na cadeia, tem mais confiança no Senhor. Assim eles têm cada vez mais coragem para anunciar a mensagem de Deus.

[[v50-1-15]]

^<<v50-1-15,15>>^ É verdade que alguns deles anunciam Cristo porque são ciumentos e briguentos; mas outros anunciam com boas intenções.

[[v50-1-16]]

^<<v50-1-16,16>>^ Estes fazem isso por amor, pois sabem que Deus me deu o trabalho de defender o evangelho.

[[v50-1-17]]

^<<v50-1-17,17>>^ Os outros não anunciam Cristo com sinceridade, mas por interesse pessoal. Eles pensam que assim aumentarão os meus sofrimentos enquanto estou na cadeia.

[[v50-1-18]]

^<<v50-1-18,18>>^ Mas isso não tem importância. O que importa é que Cristo está sendo anunciado, seja por maus ou por bons motivos. Por isso estou alegre e vou continuar assim.

[[v50-1-19]]

^<<v50-1-19,19>>^ Pois eu sei que, por meio das orações de vocês e com a ajuda do Espírito de Jesus Cristo, eu serei posto em liberdade.

[[v50-1-20]]

^<<v50-1-20,20>>^ O meu grande desejo e a minha esperança são de nunca falhar no meu dever, para que, sempre e agora ainda mais, eu tenha muita coragem. E assim, em tudo o que eu disser e fizer, tanto na vida como na morte, eu poderei levar outros a reconhecerem a grandeza de Cristo.

[[v50-1-21]]

^<<v50-1-21,21>>^ Pois para mim viver é Cristo, e morrer é lucro.

[[v50-1-22]]

^<<v50-1-22,22>>^ Mas, se eu continuar vivendo, poderei ainda fazer algum trabalho útil. Então não sei o que devo escolher.

[[v50-1-23]]

^<<v50-1-23,23>>^ Estou cercado pelos dois lados, pois quero muito deixar esta vida e estar com Cristo, o que é bem melhor.

[[v50-1-24]]

^<<v50-1-24,24>>^ Porém, por causa de vocês, é muito mais necessário que eu continue a viver.

[[v50-1-25]]

^<<v50-1-25,25>>^ E, como estou certo disso, sei que continuarei vivendo e ficarei com todos vocês para ajudá-los a progredirem e a terem a alegria que vem da fé.

[[v50-1-26]]

^<<v50-1-26,26>>^ Assim, quando eu for visitar vocês outra vez, vocês terão muito mais razão ainda para ficarem orgulhosos de mim, na vida que vocês têm em união com Cristo Jesus.

[[v50-1-27]]

^<<v50-1-27,27>>^ Agora, o mais importante é que vocês vivam de acordo com o evangelho  de Cristo. Desse modo, tanto se eu puder ir visitar vocês como se não puder, eu saberei que vocês continuam firmes e unidos. E saberei também que vocês, por meio da fé que se baseia no evangelho, estão lutando juntos, com um só desejo.

[[v50-1-28]]

^<<v50-1-28,28>>^ Não tenham medo dos seus inimigos. Sejam sempre corajosos, pois isso será uma prova para eles de que serão derrotados e de que vocês serão vencedores. Porque é Deus quem dá a vitória a vocês.

[[v50-1-29]]

^<<v50-1-29,29>>^ Pois ele tem dado a vocês o privilégio de servir a Cristo, não somente crendo nele, mas também sofrendo por ele.

[[v50-1-30]]

^<<v50-1-30,30>>^ Agora vocês podem tomar parte comigo na luta. Como vocês sabem, a luta que vocês viram que tive no passado é a mesma que ainda continua.

'''

xref:049-efesios/049-efesios-006.adoc#v49-6-0[&#60; Capítulo Anterior] | <<v50-1-0,Topo>> | xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[Próximo Capítulo &#62;]