include::./index.adoc[]

[[v50-4-0]]
=== Filipenses, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v50-4-1]]

^<<v50-4-1,1>>^ Meus queridos irmãos, sinto muitas saudades de vocês. Vocês me fazem tão feliz, e eu me orgulho muito de vocês! Portanto, continuem todos firmes, vivendo unidos com o Senhor.

[[v50-4-2]]

^<<v50-4-2,2>>^ Evódia e Síntique, peço, por favor, que procurem viver bem uma com a outra, como irmãs na fé.

[[v50-4-3]]

^<<v50-4-3,3>>^ E a você, meu fiel companheiro de trabalho, peço que ajude essas duas irmãs. Pois elas, junto com Clemente e todos os outros meus companheiros, trabalharam muito para espalhar o evangelho . Os nomes deles estão no Livro da Vida , que pertence a Deus.

[[v50-4-4]]

^<<v50-4-4,4>>^ Tenham sempre alegria, unidos com o Senhor! Repito: tenham alegria!

[[v50-4-5]]

^<<v50-4-5,5>>^ Sejam amáveis com todos. O Senhor virá logo.

[[v50-4-6]]

^<<v50-4-6,6>>^ Não se preocupem com nada, mas em todas as orações peçam a Deus o que vocês precisam e orem sempre com o coração agradecido.

[[v50-4-7]]

^<<v50-4-7,7>>^ E a paz de Deus, que ninguém consegue entender, guardará o coração e a mente de vocês, pois vocês estão unidos com Cristo Jesus.

[[v50-4-8]]

^<<v50-4-8,8>>^ Por último, meus irmãos, encham a mente de vocês com tudo o que é bom e merece elogios, isto é, tudo o que é verdadeiro, digno, correto, puro, agradável e decente.

[[v50-4-9]]

^<<v50-4-9,9>>^ Ponham em prática o que vocês receberam e aprenderam de mim, tanto com as minhas palavras como com as minhas ações. E o Deus que nos dá a paz estará com vocês.

[[v50-4-10]]

^<<v50-4-10,10>>^ Na minha vida em união com o Senhor, fiquei muito alegre porque vocês mostraram de novo o cuidado que têm por mim. Não quero dizer que vocês tivessem deixado de cuidar de mim; é que não tiveram oportunidade de mostrar esse cuidado.

[[v50-4-11]]

^<<v50-4-11,11>>^ Não estou dizendo isso por me sentir abandonado, pois aprendi a estar satisfeito com o que tenho.

[[v50-4-12]]

^<<v50-4-12,12>>^ Sei o que é estar necessitado e sei também o que é ter mais do que é preciso. Aprendi o segredo de me sentir contente em todo lugar e em qualquer situação, quer esteja alimentado ou com fome, quer tenha muito ou tenha pouco.

[[v50-4-13]]

^<<v50-4-13,13>>^ Com a força que Cristo me dá, posso enfrentar qualquer situação.

[[v50-4-14]]

^<<v50-4-14,14>>^ Mesmo assim vocês fizeram bem em me ajudar nas minhas aflições.

[[v50-4-15]]

^<<v50-4-15,15>>^ Vocês, filipenses, sabem muito bem que, quando eu saí da província  da Macedônia, nos primeiros tempos em que anunciei o evangelho , a igreja de vocês foi a única que me ajudou. Vocês foram os únicos que participaram dos meus lucros e dos meus prejuízos.

[[v50-4-16]]

^<<v50-4-16,16>>^ Em Tessalônica, mais de uma vez precisei de auxílio, e vocês o enviaram.

[[v50-4-17]]

^<<v50-4-17,17>>^ Não é que eu só pense em receber ajuda. Pelo contrário, quero ver mais lucros acrescentados à conta de vocês.

[[v50-4-18]]

^<<v50-4-18,18>>^ Aqui está o meu recibo de tudo o que vocês me enviaram e que foi mais do que o necessário. Tenho tudo o que preciso, especialmente agora que Epafrodito me trouxe as coisas que vocês mandaram, as quais são como um perfume suave oferecido a Deus, um sacrifício  que ele aceita e que lhe agrada.

[[v50-4-19]]

^<<v50-4-19,19>>^ E o meu Deus, de acordo com as gloriosas  riquezas que ele tem para oferecer por meio de Cristo Jesus, lhes dará tudo o que vocês precisam.

[[v50-4-20]]

^<<v50-4-20,20>>^ Ao Deus e Pai seja dada glória  para todo o sempre! Amém !

[[v50-4-21]]

^<<v50-4-21,21>>^ Saudações a todo o povo de Deus que pertence a Cristo Jesus. Os irmãos que estão aqui comigo mandam saudações para vocês.

[[v50-4-22]]

^<<v50-4-22,22>>^ Todo o povo de Deus daqui manda saudações, especialmente os do palácio do Imperador .

[[v50-4-23]]

^<<v50-4-23,23>>^ Que a graça  do Senhor Jesus Cristo esteja com todos vocês!

'''

xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[Próximo Capítulo &#62;]