include::./index.adoc[]

[[v50-3-0]]
=== Filipenses, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v50-3-1]]

^<<v50-3-1,1>>^ Para terminar: meus irmãos, sejam alegres por estarem unidos com o Senhor. Não me aborreço de escrever, repetindo o que já escrevi, pois isso contribuirá para a segurança de vocês.

[[v50-3-2]]

^<<v50-3-2,2>>^ Cuidado com os que fazem coisas más, esses cachorros , que insistem em cortar o corpo!

[[v50-3-3]]

^<<v50-3-3,3>>^ Porque os que receberam a verdadeira circuncisão  fomos nós, e não eles. Nós adoramos a Deus por meio do seu Espírito e nos alegramos na vida que temos em união com Cristo Jesus em vez de pormos a nossa confiança em cerimônias religiosas como a circuncisão.

[[v50-3-4]]

^<<v50-3-4,4>>^ É verdade que eu também poderia pôr a minha confiança nessas coisas. Se alguém pensa que pode confiar nelas, eu tenho ainda mais motivos para pensar assim.

[[v50-3-5]]

^<<v50-3-5,5>>^ Fui circuncidado quando tinha oito dias de vida. Sou israelita de nascimento, da tribo  de Benjamim, de sangue hebreu. Quanto à prática da lei , eu era fariseu .

[[v50-3-6]]

^<<v50-3-6,6>>^ E era tão fanático, que persegui a Igreja. Quanto ao cumprimento da vontade de Deus por meio da obediência à lei, ninguém podia me acusar de nada.

[[v50-3-7]]

^<<v50-3-7,7>>^ No passado, todas essas coisas valiam muito para mim; mas agora, por causa de Cristo, considero que não têm nenhum valor.

[[v50-3-8]]

^<<v50-3-8,8>>^ E não somente essas coisas, mas considero tudo uma completa perda, comparado com aquilo que tem muito mais valor, isto é, conhecer completamente Cristo Jesus, o meu Senhor. Eu joguei tudo fora como se fosse lixo, a fim de poder ganhar a Cristo

[[v50-3-9]]

^<<v50-3-9,9>>^ e estar unido com ele. Eu já não procuro mais ser aceito por Deus por causa da minha obediência à lei. Pois agora é por meio da minha fé em Cristo que eu sou aceito; essa aceitação vem de Deus e se baseia na fé.

[[v50-3-10]]

^<<v50-3-10,10>>^ Tudo o que eu quero é conhecer a Cristo e sentir em mim o poder da sua ressurreição. Quero também tomar parte nos seus sofrimentos e me tornar como ele na sua morte,

[[v50-3-11]]

^<<v50-3-11,11>>^ com a esperança de que eu mesmo seja ressuscitado da morte para a vida.

[[v50-3-12]]

^<<v50-3-12,12>>^ Não estou querendo dizer que já consegui tudo o que quero ou que já fiquei perfeito, mas continuo a correr para conquistar o prêmio, pois para isso já fui conquistado por Cristo Jesus.

[[v50-3-13]]

^<<v50-3-13,13>>^ É claro, irmãos, que eu não penso que já consegui isso. Porém uma coisa eu faço: esqueço aquilo que fica para trás e avanço para o que está na minha frente.

[[v50-3-14]]

^<<v50-3-14,14>>^ Corro direto para a linha de chegada a fim de conseguir o prêmio da vitória. Esse prêmio é a nova vida para a qual Deus me chamou  por meio de Cristo Jesus.

[[v50-3-15]]

^<<v50-3-15,15>>^ Todos nós que somos espiritualmente maduros devemos ter essa maneira de pensar. Porém, se alguns de vocês pensam de maneira diferente, Deus vai tornar as coisas claras para vocês.

[[v50-3-16]]

^<<v50-3-16,16>>^ Portanto, vamos em frente, na mesma direção que temos seguido até agora.

[[v50-3-17]]

^<<v50-3-17,17>>^ Meus irmãos, continuem a ser meus imitadores. E olhem com atenção também os que vivem de acordo com o exemplo que temos dado a vocês.

[[v50-3-18]]

^<<v50-3-18,18>>^ Já disse isto muitas vezes e agora repito, chorando: existem muitos que, pela sua maneira de viver, se tornam inimigos da mensagem da morte de Cristo na cruz.

[[v50-3-19]]

^<<v50-3-19,19>>^ Eles vão para a destruição no inferno porque o deus deles são os desejos do corpo. Eles têm orgulho daquilo que devia ser uma vergonha para eles e pensam somente nas coisas que são deste mundo.

[[v50-3-20]]

^<<v50-3-20,20>>^ Mas nós somos cidadãos do céu e estamos esperando ansiosamente o nosso Salvador, o Senhor Jesus Cristo, que virá de lá.

[[v50-3-21]]

^<<v50-3-21,21>>^ Ele transformará o nosso corpo fraco e mortal e fará com que fique igual ao seu próprio corpo glorioso , usando para isso o mesmo poder que ele tem para dominar todas as coisas.

'''

xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[Próximo Capítulo &#62;]