include::./index.adoc[]

[[v50-2-0]]
=== Filipenses, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v50-2-1]]

^<<v50-2-1,1>>^ Por estarem unidos com Cristo, vocês são fortes, o amor dele os anima, e vocês participam do Espírito de Deus. E também são bondosos e misericordiosos uns com os outros.

[[v50-2-2]]

^<<v50-2-2,2>>^ Então peço que me deem a grande satisfação de viverem em harmonia, tendo um mesmo amor e sendo unidos de alma e mente.

[[v50-2-3]]

^<<v50-2-3,3>>^ Não façam nada por interesse pessoal ou por desejos tolos de receber elogios; mas sejam humildes e considerem os outros superiores a vocês mesmos.

[[v50-2-4]]

^<<v50-2-4,4>>^ Que ninguém procure somente os seus próprios interesses, mas também os dos outros.

[[v50-2-5]]

^<<v50-2-5,5>>^ Tenham entre vocês o mesmo modo de pensar que Cristo Jesus tinha:

[[v50-2-6]]

^<<v50-2-6,6>>^ Ele tinha a natureza de Deus, mas não tentou ficar igual a Deus.

[[v50-2-7]]

^<<v50-2-7,7>>^ Pelo contrário, ele abriu mão de tudo o que era seu e tomou a natureza de servo , tornando-se assim igual aos seres humanos. E, vivendo a vida comum de um ser humano,

[[v50-2-8]]

^<<v50-2-8,8>>^ ele foi humilde e obedeceu a Deus até a morte — morte de cruz.

[[v50-2-9]]

^<<v50-2-9,9>>^ Por isso Deus deu a Jesus a mais alta honra e pôs nele o nome que é o mais importante de todos os nomes,

[[v50-2-10]]

^<<v50-2-10,10>>^ para que, em homenagem ao nome de Jesus, todas as criaturas no céu, na terra e no mundo dos mortos , caiam de joelhos

[[v50-2-11]]

^<<v50-2-11,11>>^ e declarem abertamente que Jesus Cristo é o Senhor, para a glória  de Deus, o Pai.

[[v50-2-12]]

^<<v50-2-12,12>>^ Portanto, meus queridos amigos, vocês que me obedeceram sempre quando eu estava aí, devem me obedecer muito mais agora que estou ausente. Continuem trabalhando com respeito e temor a Deus  para completar a salvação de vocês.

[[v50-2-13]]

^<<v50-2-13,13>>^ Pois Deus está sempre agindo em vocês para que obedeçam à vontade dele, tanto no pensamento como nas ações.

[[v50-2-14]]

^<<v50-2-14,14>>^ Façam tudo sem queixas nem discussões

[[v50-2-15]]

^<<v50-2-15,15>>^ para que vocês não tenham nenhuma falha ou mancha. Sejam filhos de Deus, vivendo sem nenhuma culpa no meio de pessoas más, que não querem saber de Deus. No meio delas vocês devem brilhar como as estrelas no céu,

[[v50-2-16]]

^<<v50-2-16,16>>^ entregando a elas a mensagem da vida. Se agirem assim, eu terei motivo de sentir orgulho de vocês no Dia de Cristo , pois isso mostrará que todo o meu esforço e todo o meu trabalho não foram inúteis.

[[v50-2-17]]

^<<v50-2-17,17>>^ Talvez o meu sangue, isto é, a minha vida, seja apresentado como uma oferta junto com o sacrifício  que vocês, por meio da sua fé, oferecem a Deus. Se isso acontecer, ficarei contente e me alegrarei com todos vocês.

[[v50-2-18]]

^<<v50-2-18,18>>^ Do mesmo modo vocês também devem ficar contentes e se alegrar comigo.

[[v50-2-19]]

^<<v50-2-19,19>>^ Se for da vontade do Senhor Jesus, espero poder logo lhes enviar Timóteo para que eu fique animado quando receber notícias de vocês.

[[v50-2-20]]

^<<v50-2-20,20>>^ Pois Timóteo é o único que se preocupa com vocês como eu me preocupo e é o único que, de fato, se interessa pelo bem-estar de vocês.

[[v50-2-21]]

^<<v50-2-21,21>>^ Pois todos os outros se preocupam com os seus próprios interesses e não com os de Jesus Cristo.

[[v50-2-22]]

^<<v50-2-22,22>>^ E vocês sabem muito bem como Timóteo provou o seu valor. Ele e eu, como se fôssemos filho e pai, temos trabalhado juntos no serviço do evangelho .

[[v50-2-23]]

^<<v50-2-23,23>>^ Portanto, espero enviá-lo a vocês logo que eu souber como vão ficar as coisas aqui para mim.

[[v50-2-24]]

^<<v50-2-24,24>>^ E, confiado no Senhor, penso que eu mesmo poderei ir logo até aí.

[[v50-2-25]]

^<<v50-2-25,25>>^ Também acho que é preciso enviar a vocês o nosso irmão Epafrodito, meu companheiro de trabalho e de lutas, o qual vocês enviaram para me trazer a ajuda que eu precisava.

[[v50-2-26]]

^<<v50-2-26,26>>^ Ele tem tido muitas saudades de todos vocês e tem andado muito preocupado por vocês terem sabido que ele estava doente.

[[v50-2-27]]

^<<v50-2-27,27>>^ De fato, ele esteve doente e quase morreu. Mas Deus teve pena dele e não somente dele, mas também de mim; e assim evitou que eu tivesse uma tristeza ainda maior.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso vou mandá-lo de volta a vocês o mais depressa possível para que vocês sintam a alegria de vê-lo novamente e para que eu não fique preocupado.

[[v50-2-29]]

^<<v50-2-29,29>>^ Portanto, recebam Epafrodito com toda a alegria, como se recebe um irmão no Senhor. Respeitem pessoas como ele,

[[v50-2-30]]

^<<v50-2-30,30>>^ pois ele arriscou a sua vida e quase morreu por causa do trabalho de Cristo. Ele fez isso para me dar a ajuda que vocês não podiam me dar pessoalmente.

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]