include::./index.adoc[]

[[v31-1-0]]
=== Obadias, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v31-1-1]]

^<<v31-1-1,1>>^ Esta é a mensagem que o Senhor  Deus deu a Obadias a respeito do país de Edom. O Senhor  mandou um mensageiro a todas as nações, e nós ouvimos a sua mensagem: "Preparem-se! Vamos lutar contra Edom!"

[[v31-1-2]]

^<<v31-1-2,2>>^ O Senhor  diz a Edom: "Eu vou fazer de você uma nação fraca, e ninguém o respeitará.

[[v31-1-3]]

^<<v31-1-3,3>>^ O seu orgulho o enganou. Você vive nas cavernas das rochas, lá no alto das montanhas, e por isso pensa assim: ‘Ninguém é capaz de me derrubar daqui.’

[[v31-1-4]]

^<<v31-1-4,4>>^ Ainda que você voe tão alto como a águia e faça o seu ninho entre as estrelas, eu o derrubarei dali.

[[v31-1-5]]

^<<v31-1-5,5>>^ "Quando ladrões chegam de noite, levam apenas o que lhes interessa. Quando alguém colhe uvas, sempre deixa algumas nas parreiras . Mas os seus inimigos destruíram você completamente!

[[v31-1-6]]

^<<v31-1-6,6>>^ Povo de Edom, todos os seus bens foram roubados; levaram embora todos os seus tesouros.

[[v31-1-7]]

^<<v31-1-7,7>>^ Os seus aliados o traíram e o expulsaram do seu próprio país. Povos com quem você tinha acordos  de paz conquistaram a sua terra. Os seus amigos mais chegados fizeram planos contra você. Eles dizem: ‘Os edomitas são uns tolos!’ "

[[v31-1-8]]

^<<v31-1-8,8>>^ O Senhor  Deus diz: "No dia em que eu castigar Edom, acabarei com todos os seus sábios; não ficará uma só pessoa inteligente no país.

[[v31-1-9]]

^<<v31-1-9,9>>^ Os soldados de Temã tremerão de medo; todos os guerreiros de Edom serão mortos."

[[v31-1-10]]

^<<v31-1-10,10>>^ O Senhor  diz ao povo de Edom: "Vocês maltrataram e mataram os seus irmãos , os descendentes de Jacó. Por isso, vocês serão destruídos, e a desgraça os acompanhará para sempre.

[[v31-1-11]]

^<<v31-1-11,11>>^ Quando o inimigo derrubou os portões de Jerusalém, entrou na cidade e tirou todas as coisas de valor, vocês não se importaram com isso. Quando aqueles estrangeiros tiraram a sorte para ver quem ficava com as riquezas, vocês fizeram a mesma coisa.

[[v31-1-12]]

^<<v31-1-12,12>>^ "Mas vocês não deviam ter ficado alegres com a desgraça dos seus irmãos de Judá; não deviam ter olhado com prazer quando eles foram destruídos; não deviam ter zombado deles quando eles estavam aflitos.

[[v31-1-13]]

^<<v31-1-13,13>>^ Quando o meu povo foi derrotado, vocês não deviam ter entrado em Jerusalém, nem deviam ter ficado alegres com a desgraça deles. Quando eles sofreram a derrota, vocês não deviam ter roubado os seus bens;

[[v31-1-14]]

^<<v31-1-14,14>>^ não deviam ter esperado nas encruzilhadas para matar os que procuravam fugir, nem deviam ter entregado ao inimigo os que escaparam com vida."

[[v31-1-15]]

^<<v31-1-15,15>>^ O Senhor  Deus diz: "Está chegando o dia em que eu vou julgar todas as nações. Aí vocês, edomitas, pagarão pelas suas maldades; aquilo que vocês fizeram com outros será feito com vocês.

[[v31-1-16]]

^<<v31-1-16,16>>^ O meu povo já foi duramente castigado no meu monte santo . Todas as nações vizinhas sofrerão um castigo ainda mais duro; serão castigadas e desaparecerão."

[[v31-1-17]]

^<<v31-1-17,17>>^ O Senhor  diz: "Mas no monte Sião , o lugar santo, alguns conseguirão escapar. O povo de Israel possuirá de novo a terra que eu lhe dei.

[[v31-1-18]]

^<<v31-1-18,18>>^ Os povos de Judá e de Israel serão como labaredas de fogo. Eles destruirão os descendentes de Esaú, como o fogo devora a palha; nenhum dos edomitas escapará. Eu, o Senhor , falei."

[[v31-1-19]]

^<<v31-1-19,19>>^ Os israelitas do sul de Judá conquistarão o país de Edom, e os que moram nas planícies de Judá tomarão posse do território dos filisteus. Os israelitas conquistarão o território de Efraim e de Samaria, e o povo da tribo  de Benjamim tomará a região de Gileade.

[[v31-1-20]]

^<<v31-1-20,20>>^ Os que foram levados como prisioneiros para fora do Reino de Israel voltarão e conquistarão a região da Fenícia até a cidade de Sarepta, no Norte; e os que foram levados de Jerusalém e que estão em Sefarade conquistarão a região do sul de Judá.

[[v31-1-21]]

^<<v31-1-21,21>>^ O povo de Deus, vitorioso, subirá o monte Sião e dali governará o povo de Edom. E o Senhor  será o Rei.

'''

xref:030-amos/030-amos-009.adoc#v30-9-0[&#60; Capítulo Anterior] | <<v31-1-0,Topo>> | xref:032-jonas/032-jonas-001.adoc#v32-1-0[Próximo Capítulo &#62;]