include::./index.adoc[]

[[v26-34-0]]
=== Ezequiel, 34
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-34-1]]

^<<v26-34-1,1>>^ O Senhor  me disse o seguinte:

[[v26-34-2]]

^<<v26-34-2,2>>^ — Homem mortal , fale contra as autoridades que governam o meu povo de Israel. Profetize  contra elas e diga que eu, o Senhor  Deus, estou dizendo o seguinte: "Vocês, autoridades, são os pastores de Israel. Ai de vocês, pois cuidam de vocês mesmos, mas nunca tomam conta do rebanho!

[[v26-34-3]]

^<<v26-34-3,3>>^ Vocês bebem o leite das ovelhas, usam a sua lã para fazer roupas e matam e comem as ovelhas mais bem-tratadas, porém não cuidam do rebanho.

[[v26-34-4]]

^<<v26-34-4,4>>^ Vocês não tratam as fracas, não curam as doentes, não fazem curativos nas machucadas, não vão buscar as que se desviam, nem procuram as que se perdem. Pelo contrário, vocês tratam as ovelhas com violência e crueldade.

[[v26-34-5]]

^<<v26-34-5,5>>^ E, por não terem pastor, elas se espalharam. Animais ferozes mataram e comeram as ovelhas.

[[v26-34-6]]

^<<v26-34-6,6>>^ As minhas ovelhas andam perdidas pelos morros e pelas altas montanhas. Estão espalhadas por toda parte. Ninguém busca essas ovelhas, ninguém procura encontrá-las.

[[v26-34-7]]

^<<v26-34-7,7>>^ — Pois bem, pastores, escutem o que eu, o Senhor  Deus, estou dizendo.

[[v26-34-8]]

^<<v26-34-8,8>>^ Juro pela minha vida que é melhor vocês me escutarem. Por não terem pastor, as minhas ovelhas foram atacadas, mortas e devoradas por animais ferozes. Os meus pastores não foram procurá-las. Eles estavam cuidando de si mesmos e não das ovelhas.

[[v26-34-9]]

^<<v26-34-9,9>>^ Por isso, vocês, pastores, prestem atenção.

[[v26-34-10]]

^<<v26-34-10,10>>^ Eu, o Senhor  Deus, declaro que estou contra vocês. Tirarei de vocês as minhas ovelhas e não deixarei que vocês sejam os seus pastores. E não deixarei que continuem a ser pastores que só cuidam dos seus próprios interesses. Livrarei as minhas ovelhas do poder de vocês para que vocês não possam devorá-las."

[[v26-34-11]]

^<<v26-34-11,11>>^ — Eu, o Senhor  Deus, digo que eu mesmo procurarei e buscarei as minhas ovelhas.

[[v26-34-12]]

^<<v26-34-12,12>>^ Como um pastor busca as suas ovelhas que estão espalhadas, assim eu buscarei as minhas ovelhas e as trarei de volta de todos os lugares por onde foram espalhadas naquele dia de escuridão e desgraça.

[[v26-34-13]]

^<<v26-34-13,13>>^ Eu as tirarei de países estrangeiros, e as ajuntarei, e as trarei de volta à sua própria terra. Eu as levarei para as montanhas de Israel e ali as alimentarei, perto dos ribeirões e em todos os lugares onde o povo vive.

[[v26-34-14]]

^<<v26-34-14,14>>^ Deixarei que elas pastem em bons pastos, nas subidas das montanhas, nos vales e em todos os pastos verdes da terra de Israel.

[[v26-34-15]]

^<<v26-34-15,15>>^ Eu mesmo serei o pastor do meu rebanho e encontrarei um lugar onde as ovelhas possam descansar. Sou eu, o Senhor  Deus, quem está falando.

[[v26-34-16]]

^<<v26-34-16,16>>^ — Procurarei as ovelhas perdidas, trarei de volta as que se desviaram, farei curativo nas machucadas e tratarei das doentes. Mas destruirei as que estão gordas e fortes, porque eu sou um pastor que faz o que é certo.

[[v26-34-17]]

^<<v26-34-17,17>>^ — Eu, o Senhor  Deus, digo o seguinte a vocês, o meu rebanho: "Eu vou julgar cada um de vocês. Vou separar os bons dos maus, as ovelhas dos bodes.

[[v26-34-18]]

^<<v26-34-18,18>>^ Será que vocês não ficam satisfeitos com o melhor pasto? Por que precisam pisar o resto do capim? Vocês bebem a água limpa e sujam com os pés a água que não bebem.

[[v26-34-19]]

^<<v26-34-19,19>>^ As minhas outras ovelhas têm de comer o capim que vocês pisaram e beber a água que vocês sujaram."

[[v26-34-20]]

^<<v26-34-20,20>>^ — Por isso, agora eu, o Senhor  Deus, digo que vou decidir a questão que há entre vocês, ovelhas gordas, e as ovelhas magras.

[[v26-34-21]]

^<<v26-34-21,21>>^ Vocês empurram as doentes para o lado e com chifradas as põem para fora do rebanho.

[[v26-34-22]]

^<<v26-34-22,22>>^ Mas eu vou socorrer as minhas ovelhas e não deixarei mais que sejam maltratadas. Julgarei cada uma delas e separarei as boas das más.

[[v26-34-23]]

^<<v26-34-23,23>>^ Eu darei às minhas ovelhas um rei que será como o meu servo  Davi, para ser o seu único pastor. Ele será o seu pastor e cuidará delas.

[[v26-34-24]]

^<<v26-34-24,24>>^ Eu, o Senhor , serei o Deus delas, e um rei como o meu servo Davi será o seu governador. Sou eu, o Senhor , quem está falando.

[[v26-34-25]]

^<<v26-34-25,25>>^ Farei uma aliança  com elas para garantir que tenham segurança. Acabarei com todos os animais ferozes que há na terra de Israel, e assim as minhas ovelhas poderão viver em segurança nos campos e dormir no mato.

[[v26-34-26]]

^<<v26-34-26,26>>^ — Eu abençoarei as ovelhas e deixarei que vivam em volta do meu monte santo . Quando precisarem, eu as abençoarei com muita chuva.

[[v26-34-27]]

^<<v26-34-27,27>>^ As árvores darão frutas, os campos produzirão colheitas, e todos viverão em segurança na sua própria terra. Quando eu livrar o meu povo daqueles que o escravizaram e quebrar as suas correntes, aí todos ficarão sabendo que eu sou o Senhor .

[[v26-34-28]]

^<<v26-34-28,28>>^ Os pagãos não roubarão o que eles têm, e os animais ferozes não vão matá-los, nem comê-los. Eles viverão em segurança, e ninguém mais fará com que fiquem com medo.

[[v26-34-29]]

^<<v26-34-29,29>>^ Eu lhes darei terras boas e acabarei com a fome que há na terra de Israel. As outras nações não zombarão mais deles.

[[v26-34-30]]

^<<v26-34-30,30>>^ Todos ficarão sabendo que eu protejo Israel e que Israel é o meu povo. Sou eu, o Senhor  Deus, quem está falando.

[[v26-34-31]]

^<<v26-34-31,31>>^ — Vocês, minhas ovelhas, ovelhas que eu alimento, vocês são seres humanos, e eu sou o seu Deus! — diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]