include::./index.adoc[]

[[v26-18-0]]
=== Ezequiel, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-18-1]]

^<<v26-18-1,1>>^ O Senhor  me disse o seguinte:

[[v26-18-2]]

^<<v26-18-2,2>>^ — Por que será que na terra de Israel o povo vive repetindo o ditado que diz: "Os pais comeram uvas verdes, mas foram os dentes dos filhos que ficaram ásperos"?

[[v26-18-3]]

^<<v26-18-3,3>>^ — Juro pela minha vida — diz o Senhor  Deus — que vocês nunca mais repetirão esse ditado em Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Pois a vida de todas as pessoas pertence a mim. Tanto a vida do pai quanto a vida do filho são minhas. A pessoa que pecar é que morrerá.

[[v26-18-5]]

^<<v26-18-5,5>>^ — Imaginem que exista um homem verdadeiramente bom, correto e honesto.

[[v26-18-6]]

^<<v26-18-6,6>>^ Esse homem não adora os ídolos dos israelitas, nem come a carne dos sacrifícios  oferecidos em templos proibidos. Ele não seduz mulheres casadas, nem tem relações com mulher durante as regras.

[[v26-18-7]]

^<<v26-18-7,7>>^ Não engana, nem rouba ninguém. Devolve aquilo que lhe foi dado como garantia de empréstimo. Dá comida a quem tem fome e roupa a quem está nu.

[[v26-18-8]]

^<<v26-18-8,8>>^ Quando empresta, não cobra juros altos. Recusa-se a fazer o mal, e em qualquer questão as suas decisões são justas.

[[v26-18-9]]

^<<v26-18-9,9>>^ Obedece aos meus mandamentos e guarda cuidadosamente as minhas leis . Esse homem é correto e viverá — diz o Senhor  Deus.

[[v26-18-10]]

^<<v26-18-10,10>>^ — Imaginem também que esse homem tenha um filho que rouba, mata e faz coisas

[[v26-18-11]]

^<<v26-18-11,11>>^ que o pai nunca fez. Esse filho come a carne dos sacrifícios oferecidos em templos proibidos e seduz mulheres casadas.

[[v26-18-12]]

^<<v26-18-12,12>>^ Engana os pobres, rouba e fica com aquilo que lhe foi dado como garantia de empréstimo. Ele vai a templos pagãos, adora ídolos nojentos

[[v26-18-13]]

^<<v26-18-13,13>>^ e empresta dinheiro a juros altos. Será que ele vai viver? Não! Não vai! Ele fez todas essas coisas vergonhosas e morrerá por causa delas. Esse filho será culpado da sua própria morte.

[[v26-18-14]]

^<<v26-18-14,14>>^ — Agora, imaginem que, por sua vez, esse filho tenha um filho. Esse filho vê todos os pecados que o pai cometeu, mas não segue o seu exemplo.

[[v26-18-15]]

^<<v26-18-15,15>>^ Não adora os ídolos dos israelitas, nem come a carne dos sacrifícios oferecidos em templos proibidos. Não seduz mulheres casadas

[[v26-18-16]]

^<<v26-18-16,16>>^ e não explora, nem rouba ninguém. Ele devolve aquilo que lhe foi dado como garantia de empréstimo. Dá comida a quem tem fome e roupa a quem está nu.

[[v26-18-17]]

^<<v26-18-17,17>>^ Ele se recusa a fazer o mal e não empresta dinheiro a juros altos. Guarda as minhas leis e obedece aos meus mandamentos. Ele não morrerá por causa dos pecados do pai. É certo que viverá.

[[v26-18-18]]

^<<v26-18-18,18>>^ O pai dele enganou, e roubou, e só prejudicou os outros. Por isso, morreu por causa dos seus próprios pecados.

[[v26-18-19]]

^<<v26-18-19,19>>^ — Mas vocês perguntam: "Por que é que o filho não sofre por causa dos pecados do pai?" A resposta é esta: é porque o filho fez o que era correto e bom. Ele guardou as minhas leis, e as seguiu cuidadosamente, e por isso é certo que viverá.

[[v26-18-20]]

^<<v26-18-20,20>>^ Aquele que peca é que morre. O filho não sofrerá por causa dos pecados do pai, nem o pai, por causa dos pecados do filho. A pessoa boa será recompensada por fazer o bem, e a pessoa má sofrerá pelo mal que praticar.

[[v26-18-21]]

^<<v26-18-21,21>>^ — Se um homem mau parar de pecar, se guardar as minhas leis e se fizer o que é certo e bom, não morrerá; é certo que viverá.

[[v26-18-22]]

^<<v26-18-22,22>>^ Todos os seus pecados serão perdoados, e ele viverá porque fez o que é certo.

[[v26-18-23]]

^<<v26-18-23,23>>^ Vocês pensam que eu gosto de ver um homem mau morrer? — pergunta o Senhor  Deus. — Não! Eu gostaria mais de vê-lo arrepender-se e viver.

[[v26-18-24]]

^<<v26-18-24,24>>^ — Mas, se um homem correto deixar de fazer o bem e começar a fazer todas as coisas más e vergonhosas que os homens maus fazem, será que ele vai continuar a viver? Não! Nenhuma das boas ações que ele praticou será lembrada. Ele morrerá por causa da sua infidelidade e dos seus pecados.

[[v26-18-25]]

^<<v26-18-25,25>>^ — Mas vocês dizem: "O que o Senhor faz não está certo." Escutem aqui, israelitas! Vocês pensam que o meu modo de fazer as coisas não está certo? Pois o modo de vocês é que não está.

[[v26-18-26]]

^<<v26-18-26,26>>^ Quando um homem direito para de fazer o bem, e começa a fazer o mal, e então morre, ele morre por causa do mal que praticou.

[[v26-18-27]]

^<<v26-18-27,27>>^ Quando um homem mau para de pecar e faz o que é certo e bom, ele salvou a sua vida.

[[v26-18-28]]

^<<v26-18-28,28>>^ Ele compreendeu o que estava fazendo e deixou de pecar; por isso, é certo que ele não vai morrer, mas continuará a viver.

[[v26-18-29]]

^<<v26-18-29,29>>^ E vocês, israelitas, dizem: "O que o Senhor faz não está certo." Vocês pensam que o meu modo de fazer as coisas não está certo, não é? Pois é o modo de vocês que não está.

[[v26-18-30]]

^<<v26-18-30,30>>^ — Agora, eu, o Senhor  Deus, estou dizendo a vocês, israelitas, que vou julgar cada um pelo que tem feito. Arrependam-se de todo mal que estão praticando e não deixem que os seus pecados os destruam.

[[v26-18-31]]

^<<v26-18-31,31>>^ Abandonem todo mal que vêm fazendo e criem dentro de vocês mesmos um coração novo e uma mente nova. Israelitas, por que vocês querem morrer?

[[v26-18-32]]

^<<v26-18-32,32>>^ Eu não quero que ninguém morra! — diz o Senhor  Deus. — Portanto, parem de pecar e vivam.

'''

xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]