include::./index.adoc[]

[[v26-16-0]]
=== Ezequiel, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-16-1]]

^<<v26-16-1,1>>^ O Senhor  falou comigo de novo. Ele disse:

[[v26-16-2]]

^<<v26-16-2,2>>^ — Homem mortal , mostre a Jerusalém as coisas nojentas que ela tem feito.

[[v26-16-3]]

^<<v26-16-3,3>>^ Diga a Jerusalém que o Senhor  Deus lhe diz o seguinte: — Você nasceu na terra de Canaã. O seu pai era amorreu, e a sua mãe era heteia .

[[v26-16-4]]

^<<v26-16-4,4>>^ Quando você nasceu, ninguém cortou o cordão do seu umbigo, nem lhe deu banho, nem esfregou sal em você, nem a enrolou em panos.

[[v26-16-5]]

^<<v26-16-5,5>>^ Ninguém teve dó bastante para lhe fazer qualquer uma dessas coisas. Quando você nasceu, ninguém gostava de você, e até a jogaram no mato.

[[v26-16-6]]

^<<v26-16-6,6>>^ — Então passei por perto e vi você rolando no seu próprio sangue. Embora você estivesse coberta de sangue, eu não deixei que morresse.

[[v26-16-7]]

^<<v26-16-7,7>>^ Eu a fiz crescer como uma planta sadia. Você cresceu forte e alta e ficou moça. Os seus seios se formaram, e os seus cabelos ficaram compridos, mas você estava nua.

[[v26-16-8]]

^<<v26-16-8,8>>^ — Quando passei de novo, vi que havia chegado o tempo de você amar. Então cobri o seu corpo nu com a minha capa  e prometi amar você. Sim! Fiz um contrato de casamento com você, e você se tornou minha. Sou eu, o Senhor  Deus, quem está falando.

[[v26-16-9]]

^<<v26-16-9,9>>^ — Eu a lavei com água e limpei o sangue que a cobria. Passei azeite na sua pele.

[[v26-16-10]]

^<<v26-16-10,10>>^ Eu a vesti com roupas bordadas e lhe dei sapatos do melhor couro, um turbante  de linho e uma capa  de seda.

[[v26-16-11]]

^<<v26-16-11,11>>^ Eu a enfeitei com joias — pulseiras e colares.

[[v26-16-12]]

^<<v26-16-12,12>>^ Dei uma argola para o seu nariz, brincos para as suas orelhas e uma linda coroa para a sua cabeça.

[[v26-16-13]]

^<<v26-16-13,13>>^ As suas joias eram de ouro e prata, e você sempre usou vestidos bordados, de linho e de seda. Você comeu pão feito da melhor farinha e tinha mel e azeite à vontade. Você era muito bonita e chegou a ser rainha.

[[v26-16-14]]

^<<v26-16-14,14>>^ Em todas as nações falavam da sua beleza perfeita porque fui eu que a fiz assim tão linda. Sou eu, o Senhor  Deus, quem está falando.

[[v26-16-15]]

^<<v26-16-15,15>>^ — Mas você se aproveitou da sua beleza e da sua fama para dormir com qualquer um que passava .

[[v26-16-16]]

^<<v26-16-16,16>>^ Usou os seus vestidos para enfeitar os seus lugares de adoração e ali você se entregava a qualquer um, como uma prostituta.

[[v26-16-17]]

^<<v26-16-17,17>>^ Você pegou as joias de prata e de ouro que eu lhe tinha dado e com elas fez imagens de seres humanos; você foi infiel a mim, adorando essas imagens.

[[v26-16-18]]

^<<v26-16-18,18>>^ Você pegou os vestidos bordados que lhe dei e com eles vestiu as imagens e ofereceu a elas o azeite e o incenso que eu lhe tinha dado.

[[v26-16-19]]

^<<v26-16-19,19>>^ Eu lhe dei comida: a melhor farinha, azeite e mel, mas você ofereceu tudo isso como sacrifício  para agradar os ídolos. Sou eu, o Senhor  Deus, quem está falando.

[[v26-16-20]]

^<<v26-16-20,20>>^ — Depois, você pegou os nossos filhos e as nossas filhas e os ofereceu como sacrifício aos ídolos. Será que não bastou que você tivesse sido infiel a mim?

[[v26-16-21]]

^<<v26-16-21,21>>^ Será que ainda precisou matar os meus filhos e oferecê-los em sacrifício aos ídolos?

[[v26-16-22]]

^<<v26-16-22,22>>^ Durante a sua vida miserável de prostituta, nem uma vez você lembrou da sua juventude, quando estava nua, rolando no seu próprio sangue.

[[v26-16-23]]

^<<v26-16-23,23>>^ O Senhor  Deus disse: — Ai de você! Sim! Ai de você! Depois de ter feito todo esse mal,

[[v26-16-24]]

^<<v26-16-24,24>>^ você ainda construiu altares em todas as estradas para ali adorar ídolos e praticar a prostituição.

[[v26-16-25]]

^<<v26-16-25,25>>^ Você arrastou a sua beleza pela lama. E se ofereceu a todos os que passavam e se afundou cada vez mais na prostituição e na adoração de ídolos.

[[v26-16-26]]

^<<v26-16-26,26>>^ Você convidou os egípcios, seus vizinhos imorais, para que fossem para a cama com você, e por isso me deixou irado .

[[v26-16-27]]

^<<v26-16-27,27>>^ — Portanto, agora eu levantei a mão para castigá-la e para tirar a parte que você tinha na minha bênção. Eu a entreguei aos filisteus, que a odeiam e que estão com nojo das ações imorais que você tem praticado.

[[v26-16-28]]

^<<v26-16-28,28>>^ — Não satisfeita com tudo isso, você correu atrás dos assírios. Você foi prostituta deles, mas eles também não a deixaram satisfeita.

[[v26-16-29]]

^<<v26-16-29,29>>^ Depois, você serviu de prostituta para os babilônios, aquela nação de comerciantes, mas eles também não a deixaram satisfeita.

[[v26-16-30]]

^<<v26-16-30,30>>^ O Senhor  Deus diz o seguinte: — Você fez tudo isso como uma prostituta sem-vergonha.

[[v26-16-31]]

^<<v26-16-31,31>>^ Em todas as ruas, você construiu altares para ali adorar ídolos e praticar a prostituição. Mas você não faz isso por dinheiro, como uma prostituta qualquer.

[[v26-16-32]]

^<<v26-16-32,32>>^ Você é como a mulher que, em vez de amar o seu marido, comete adultério com estranhos.

[[v26-16-33]]

^<<v26-16-33,33>>^ A prostituta é paga, mas você deu presentes a todos os seus amantes e ainda lhes ofereceu lembranças para que viessem de todas as partes dormir com você.

[[v26-16-34]]

^<<v26-16-34,34>>^ Você é uma prostituta diferente. Ninguém a obrigou a se tornar prostituta. Você não recebe nada, mas paga! Sim! Você é diferente!

[[v26-16-35]]

^<<v26-16-35,35>>^ Por isso, agora, você, prostituta, escute o que o Senhor  Deus diz.

[[v26-16-36]]

^<<v26-16-36,36>>^ E o que ele diz é isto: — Você tirou a roupa, e como prostituta se entregou aos seus amantes e a todos os seus ídolos vergonhosos, e matou os seus filhos em sacrifício  aos ídolos.

[[v26-16-37]]

^<<v26-16-37,37>>^ Por causa disso, eu vou reunir todos os seus antigos amantes, tanto os que você apreciava como os que detestava. Eu os colocarei ao seu redor, em círculo; então arrancarei a sua roupa, e eles verão você nua.

[[v26-16-38]]

^<<v26-16-38,38>>^ Eu a condenarei por adultério e assassinato e na minha ira  e furor vou castigá-la com a morte.

[[v26-16-39]]

^<<v26-16-39,39>>^ Vou entregá-la a eles, e eles derrubarão os altares onde você se entregava à prostituição e onde adorava ídolos. Eles levarão as suas roupas e as suas joias e a deixarão completamente nua.

[[v26-16-40]]

^<<v26-16-40,40>>^ — Eles vão atiçar a multidão para apedrejá-la e com as suas espadas cortarão você em pedaços.

[[v26-16-41]]

^<<v26-16-41,41>>^ Eles destruirão com fogo as suas casas e deixarão que muitas mulheres vejam o seu castigo. Farei com que você deixe de ser prostituta, farei com que deixe de dar presentes aos seus amantes.

[[v26-16-42]]

^<<v26-16-42,42>>^ Aí o meu furor passará, e eu me acalmarei. Não ficarei mais irado, nem terei ciúmes.

[[v26-16-43]]

^<<v26-16-43,43>>^ Você esqueceu como eu a tratei quando era moça e me deixou irado com todas as coisas que fez. Foi por isso que a fiz pagar por tudo. Por que é que, além de todas as coisas nojentas que você fez, ainda foi imoral? Eu, o Senhor  Deus, falei.

[[v26-16-44]]

^<<v26-16-44,44>>^ O Senhor  Deus diz o seguinte: — Jerusalém, os outros usarão este provérbio a respeito de você: "Tal mãe, tal filha."

[[v26-16-45]]

^<<v26-16-45,45>>^ — De fato, você é a filha da sua mãe. Ela detestava o marido e os filhos. Você é como as suas irmãs, que odiavam os seus maridos e os seus filhos. Você e as cidades que são suas irmãs tiveram mãe heteia e pai amorreu .

[[v26-16-46]]

^<<v26-16-46,46>>^ — A sua irmã mais velha é Samaria, no Norte, com os povoados que ficam ao seu redor. A sua irmã mais moça, com os seus povoados, é Sodoma, no Sul.

[[v26-16-47]]

^<<v26-16-47,47>>^ Por acaso, você se contentou em seguir os passos delas e em imitar as coisas nojentas que elas fizeram? Não! Em pouco tempo, você se tornou mais imoral do que elas em tudo o que fazia.

[[v26-16-48]]

^<<v26-16-48,48>>^ — Jerusalém, juro pela minha vida — diz o Senhor  Deus — que a sua irmã Sodoma e os povoados que ficam ao seu redor nunca pecaram tanto quanto você e os seus povoados.

[[v26-16-49]]

^<<v26-16-49,49>>^ Sodoma e as suas filhas eram orgulhosas porque tinham muita comida e viviam no conforto, sem fazer nada; porém não cuidaram dos pobres e dos necessitados.

[[v26-16-50]]

^<<v26-16-50,50>>^ Elas foram orgulhosas e teimosas e fizeram as coisas que eu detesto; por isso, eu as destruí, como você sabe muito bem.

[[v26-16-51]]

^<<v26-16-51,51>>^ — Samaria não cometeu a metade dos pecados que você, Jerusalém, cometeu. Você fez coisas ainda mais vergonhosas do que as suas irmãs Sodoma e Samaria fizeram. Elas até parecem inocentes quando a sua corrupção, Jerusalém, é comparada com a delas.

[[v26-16-52]]

^<<v26-16-52,52>>^ E agora você terá de suportar a sua desgraça. Os seus pecados são mais graves do que os das suas irmãs, tanto que elas até são inocentes em comparação com você. Agora, Jerusalém, fique envergonhada e aguente a sua humilhação, pois você faz com que as suas irmãs pareçam puras.

[[v26-16-53]]

^<<v26-16-53,53>>^ O Senhor  Deus disse a Jerusalém: — Vou trazer progresso de novo para as suas irmãs: para Sodoma e os povoados que ficam ao seu redor e para Samaria e os seus povoados. E vou fazer com que você também prospere.

[[v26-16-54]]

^<<v26-16-54,54>>^ Você terá vergonha de você mesma, e a sua desgraça mostrará às suas irmãs que elas estão em muito boas condições.

[[v26-16-55]]

^<<v26-16-55,55>>^ De novo haverá progresso para elas, e você e os seus povoados também serão reconstruídos.

[[v26-16-56]]

^<<v26-16-56,56>>^ No seu orgulho, você zombou de Sodoma,

[[v26-16-57]]

^<<v26-16-57,57>>^ antes de ser descoberto o mal que você fazia. Agora, você se tornou igual a Sodoma: zombam de você os edomitas, os filisteus e os seus outros vizinhos que a odeiam.

[[v26-16-58]]

^<<v26-16-58,58>>^ Você precisa sofrer pelas coisas imorais e vergonhosas que fez. Eu, o Senhor , falei.

[[v26-16-59]]

^<<v26-16-59,59>>^ O Senhor  Deus diz: — Jerusalém, eu a tratarei como merece, pois você quebrou as suas promessas e não respeitou a aliança .

[[v26-16-60]]

^<<v26-16-60,60>>^ Mas eu manterei a aliança que fiz com você na sua mocidade e farei com você uma aliança que durará para sempre.

[[v26-16-61]]

^<<v26-16-61,61>>^ Você lembrará do que fez e ficará envergonhada de receber de volta a sua irmã mais velha e a sua irmã mais moça. Eu as darei a você como se fossem filhas, embora isso não fizesse parte da nossa aliança.

[[v26-16-62]]

^<<v26-16-62,62>>^ Renovarei a aliança que fiz com você, e você ficará sabendo que eu sou o Senhor .

[[v26-16-63]]

^<<v26-16-63,63>>^ Eu perdoarei todas as coisas más que você fez, porém você lembrará delas e ficará envergonhada demais para dizer qualquer coisa. Eu, o Senhor  Deus, falei.

'''

xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]