include::./index.adoc[]

[[v26-32-0]]
=== Ezequiel, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-32-1]]

^<<v26-32-1,1>>^ No ano décimo segundo do nosso cativeiro , no dia primeiro do décimo segundo mês , o Senhor  me disse o seguinte:

[[v26-32-2]]

^<<v26-32-2,2>>^ — Homem mortal , cante um cântico fúnebre a respeito do rei do Egito. Diga-lhe isto: "Você age como um leão no meio das nações, mas parece mais um crocodilo nadando e agitando a água do rio. Com as suas patas, você turva a água e suja os rios.

[[v26-32-3]]

^<<v26-32-3,3>>^ Quando muitos povos se ajuntarem, eu, o Senhor  Deus, o pegarei na minha rede e deixarei que eles puxem a rede para a praia.

[[v26-32-4]]

^<<v26-32-4,4>>^ Eu o deixarei em lugar seco, eu o jogarei na terra e trarei todos os pássaros e animais do mundo para que comam a sua carne.

[[v26-32-5]]

^<<v26-32-5,5>>^ Cobrirei montanhas e vales com o seu cadáver podre.

[[v26-32-6]]

^<<v26-32-6,6>>^ Ensoparei a terra com o seu sangue, e ele cobrirá as montanhas e encherá os rios.

[[v26-32-7]]

^<<v26-32-7,7>>^ Quando eu destruir você, cobrirei o céu e apagarei as estrelas. Esconderei o sol atrás das nuvens, e a lua não brilhará mais.

[[v26-32-8]]

^<<v26-32-8,8>>^ Apagarei todas as luzes do céu e lançarei o seu país na escuridão. Sou eu, o Senhor  Deus, quem está falando.

[[v26-32-9]]

^<<v26-32-9,9>>^ — "Você será destruído, e eu espalharei essa notícia em países de que você nunca ouviu falar. Aí muitas nações vão ficar em confusão

[[v26-32-10]]

^<<v26-32-10,10>>^ e espantadas com o que eu vou fazer com você. Quando eu agitar a minha espada, os seus reis ficarão apavorados. No dia em que você cair, todos eles tremerão de medo de perder a vida."

[[v26-32-11]]

^<<v26-32-11,11>>^ — O Senhor  Deus continua a dizer ao rei do Egito: "Você enfrentará a espada do rei da Babilônia.

[[v26-32-12]]

^<<v26-32-12,12>>^ Deixarei que os soldados de nações cruéis peguem a espada e matem milhares de egípcios. Eles arrasarão tudo aquilo de que você tem orgulho e matarão o seu povo.

[[v26-32-13]]

^<<v26-32-13,13>>^ Destruirei o seu gado em todos os bebedouros, e não haverá mais gente nem gado para sujar a água.

[[v26-32-14]]

^<<v26-32-14,14>>^ Deixarei que as suas águas assentem e fiquem claras e farei com que os seus rios corram calmamente. Sou eu, o Senhor  Deus, quem está falando.

[[v26-32-15]]

^<<v26-32-15,15>>^ Quando eu fizer o Egito virar um deserto abandonado e destruir todos os que vivem ali, as outras nações ficarão sabendo que eu sou o Senhor ."

[[v26-32-16]]

^<<v26-32-16,16>>^ — Este é o cântico fúnebre que as mulheres das outras nações vão cantar para chorar pelo Egito e por todo o seu povo. Eu, o Senhor  Deus, falei.

[[v26-32-17]]

^<<v26-32-17,17>>^ No ano décimo segundo do nosso cativeiro , no dia quinze do primeiro mês , o Senhor  me disse o seguinte:

[[v26-32-18]]

^<<v26-32-18,18>>^ — Homem mortal , chore pela multidão de gente do Egito. Faça com que eles desçam ao mundo dos mortos  junto com outras nações poderosas.

[[v26-32-19]]

^<<v26-32-19,19>>^ Diga o seguinte: "Será que vocês são mais bonitos do que os outros? Pois vocês vão descer e se deitar nas sepulturas dos maus."

[[v26-32-20]]

^<<v26-32-20,20>>^ — Os egípcios cairão junto com aqueles que são mortos em batalha. Uma espada está preparada para matar toda a gente do Egito.

[[v26-32-21]]

^<<v26-32-21,21>>^ Os heróis mais valentes e os que lutaram pelo Egito recebem os egípcios quando estes entram no mundo dos mortos. Eles gritam: "Esses que não foram circuncidados  morreram na batalha, desceram até aqui e aqui estão deitados."

[[v26-32-22]]

^<<v26-32-22,22>>^ — A Assíria está ali, e em volta dela estão os túmulos dos seus soldados. Eles foram mortos em combate,

[[v26-32-23]]

^<<v26-32-23,23>>^ e os túmulos deles estão nas profundezas do mundo dos mortos. Todos os seus soldados caíram em combate, e os túmulos deles estão em volta do túmulo da Assíria. Mas antes eles haviam feito tremer de medo os que estão vivos.

[[v26-32-24]]

^<<v26-32-24,24>>^ — O país de Elão está ali, e em volta estão os túmulos dos seus soldados. Todos eles foram mortos em combate e, sem terem sido circuncidados, desceram ao mundo dos mortos. Quando estavam vivos, eles espalhavam o terror, mas agora estão mortos e cobertos de vergonha.

[[v26-32-25]]

^<<v26-32-25,25>>^ Elão está deitado no meio dos que foram mortos em combate, e os túmulos dos seus soldados estão em volta dele. Nenhum deles foi circuncidado; todos eles foram mortos em combate. Quando estavam vivos, eles espalhavam o terror, mas agora estão mortos e cobertos de vergonha, fazendo companhia aos que foram mortos em combate.

[[v26-32-26]]

^<<v26-32-26,26>>^ — Os países de Meseque e Tubal estão ali, e em volta estão os túmulos dos seus soldados. Nenhum deles foi circuncidado; todos eles foram mortos em combate. Mas antes eles haviam causado terror na terra dos que estão vivos.

[[v26-32-27]]

^<<v26-32-27,27>>^ Eles não foram sepultados com homenagens como os heróis dos tempos antigos, que desceram ao mundo dos mortos com as suas armas. As suas espadas foram colocadas debaixo das cabeças, e os escudos , em cima dos corpos. Esses heróis tiveram poder para causar terror na terra dos que estão vivos.

[[v26-32-28]]

^<<v26-32-28,28>>^ — Será assim que os egípcios estarão esmagados no meio dos que não foram circuncidados e que morreram em combate.

[[v26-32-29]]

^<<v26-32-29,29>>^ — O país de Edom está ali com os seus reis e autoridades. Eles foram soldados corajosos, mas agora estão deitados no mundo dos mortos, junto com os que não foram circuncidados e que morreram em combate.

[[v26-32-30]]

^<<v26-32-30,30>>^ — Todos os príncipes do Norte e os moradores de Sidom estão no mundo dos mortos; eles morreram sem terem sido circuncidados. O seu poder espalhava o terror, mas agora eles descem sem honra junto com os que foram mortos em combate e que estão deitados ali. Eles tomam parte na desgraça daqueles que descem ao mundo dos mortos.

[[v26-32-31]]

^<<v26-32-31,31>>^ — O rei do Egito os verá e ficará consolado com a morte de todo o seu exército destruído em combate! — diz o Senhor  Deus.

[[v26-32-32]]

^<<v26-32-32,32>>^ — Eu fiz com que o rei do Egito deixasse os vivos apavorados, mas ele e o seu exército serão mortos e ficarão deitados junto com todos os não circuncidados que foram mortos em combate. Eu, o Senhor  Deus, falei.

'''

xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[&#60; Capítulo Anterior] | <<v26-32-0,Topo>> | xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[Próximo Capítulo &#62;]