include::./index.adoc[]

[[v26-30-0]]
=== Ezequiel, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-30-1]]

^<<v26-30-1,1>>^ Novamente o Senhor  falou comigo. Ele disse:

[[v26-30-2]]

^<<v26-30-2,2>>^ — Homem mortal , profetize  e anuncie o que eu, o Senhor  Deus, estou dizendo. Gritem o seguinte: "Dia de terror!

[[v26-30-3]]

^<<v26-30-3,3>>^ O dia está perto, o dia em que o Senhor  vai agir, um dia de nuvens e de castigo para as nações."

[[v26-30-4]]

^<<v26-30-4,4>>^ Haverá guerra no Egito e grande sofrimento na Etiópia. Muitos serão mortos no Egito; o país será roubado e arrasado.

[[v26-30-5]]

^<<v26-30-5,5>>^ Essa guerra também matará os soldados contratados da Etiópia, Lídia, Líbia, Arábia e Cube e até do meu próprio povo.

[[v26-30-6]]

^<<v26-30-6,6>>^ O Senhor  diz: — Desde Migdol, que fica no Norte, até Assuã, que fica no Sul, todos os que defendem o Egito serão mortos em batalha. O orgulhoso exército egípcio será destruído. Sou eu, o Senhor  Deus, quem está falando.

[[v26-30-7]]

^<<v26-30-7,7>>^ O país será o mais deserto do mundo, e as suas cidades serão completamente arrasadas.

[[v26-30-8]]

^<<v26-30-8,8>>^ Quando eu incendiar o Egito, e aqueles que o defendem estiverem mortos, todos ficarão sabendo que eu sou o Senhor .

[[v26-30-9]]

^<<v26-30-9,9>>^ — Quando aquele dia chegar, e o Egito for destruído, mandarei mensageiros em navios para porem medo no povo descuidado da Etiópia, e esse povo ficará apavorado. E aquele dia está chegando!

[[v26-30-10]]

^<<v26-30-10,10>>^ O Senhor  Deus diz: — Usarei Nabucodonosor, rei da Babilônia, para acabar com a riqueza do Egito.

[[v26-30-11]]

^<<v26-30-11,11>>^ Ele e o seu exército violento virão para arrasar o Egito. Eles atacarão com espadas, e a terra dos egípcios ficará cheia de mortos.

[[v26-30-12]]

^<<v26-30-12,12>>^ Secarei o rio Nilo; entregarei o Egito a homens maus. Estrangeiros arrasarão o país todo. Eu, o Senhor , falei.

[[v26-30-13]]

^<<v26-30-13,13>>^ O Senhor  Deus diz: — Também destruirei os ídolos e os falsos deuses de Mênfis. Não ficará ninguém para governar o Egito. Espalharei o terror no meio do povo.

[[v26-30-14]]

^<<v26-30-14,14>>^ Farei com que o Sul do Egito vire um deserto e porei fogo na cidade de Zoã, no Norte. Castigarei Tebas, a capital.

[[v26-30-15]]

^<<v26-30-15,15>>^ Derramarei a minha ira  sobre a cidade de Pelúsio, a grande fortaleza do Egito, e acabarei com a riqueza de Tebas.

[[v26-30-16]]

^<<v26-30-16,16>>^ Incendiarei o Egito, e Pelúsio se retorcerá de dor. As muralhas de Tebas serão derrubadas, e a cidade será inundada.

[[v26-30-17]]

^<<v26-30-17,17>>^ Os moços das cidades de Heliópolis e Bubaste morrerão na guerra, e os outros moradores serão levados presos.

[[v26-30-18]]

^<<v26-30-18,18>>^ Quando eu quebrar o poder do Egito e acabar com a força de que tanto se gaba, a escuridão cairá sobre a cidade de Tafnes. Uma nuvem cobrirá o Egito, e os moradores de todas as suas cidades serão levados prisioneiros.

[[v26-30-19]]

^<<v26-30-19,19>>^ Assim castigarei o Egito, e aí eles ficarão sabendo que eu sou o Senhor .

[[v26-30-20]]

^<<v26-30-20,20>>^ No ano décimo primeiro do nosso cativeiro , no sétimo dia do primeiro mês , o Senhor  falou comigo. Ele disse:

[[v26-30-21]]

^<<v26-30-21,21>>^ — Homem mortal , eu quebrei um dos braços do rei do Egito. Ninguém amarrou o braço dele, nem o pôs numa tipoia a fim de que sarasse e ficasse forte, e assim ele pudesse usar de novo a espada.

[[v26-30-22]]

^<<v26-30-22,22>>^ Agora, eu, o Senhor  Deus, digo isto: "Eu estou contra o rei do Egito. Quebrarei os seus dois braços, tanto o bom como o que já está quebrado, e a espada cairá da mão dele.

[[v26-30-23]]

^<<v26-30-23,23>>^ Espalharei os egípcios pelo mundo inteiro.

[[v26-30-24]]

^<<v26-30-24,24>>^ Aí farei com que os braços do rei da Babilônia fiquem fortes e porei a minha espada nas mãos dele. Porém quebrarei os braços do rei do Egito, e assim ele gemerá e morrerá na frente do seu inimigo.

[[v26-30-25]]

^<<v26-30-25,25>>^ Sim! Farei com que o rei do Egito fique fraco e darei força ao rei da Babilônia. Quando eu lhe der a minha espada, e ele a apontar para o Egito, todos ficarão sabendo que eu sou o Senhor .

[[v26-30-26]]

^<<v26-30-26,26>>^ Espalharei os egípcios pelo mundo. Aí eles ficarão sabendo que eu sou o Senhor ."

'''

xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[&#60; Capítulo Anterior] | <<v26-30-0,Topo>> | xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[Próximo Capítulo &#62;]