include::./index.adoc[]

[[v26-38-0]]
=== Ezequiel, 38
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-38-1]]

^<<v26-38-1,1>>^ O Senhor  me disse o seguinte:

[[v26-38-2]]

^<<v26-38-2,2>>^ — Homem mortal , agora fale contra Gogue , o principal governador das nações de Meseque e Tubal, na terra de Magogue. Profetize  contra ele

[[v26-38-3]]

^<<v26-38-3,3>>^ e diga que eu, o Senhor  Deus, estou contra ele.

[[v26-38-4]]

^<<v26-38-4,4>>^ Eu o farei dar meia-volta, porei uma argola no seu nariz e o arrastarei junto com as suas tropas para longe. Com os seus cavalos e os seus cavaleiros fardados, o seu exército é enorme. E cada soldado carrega um escudo  e está armado com espada.

[[v26-38-5]]

^<<v26-38-5,5>>^ Soldados da Pérsia, Etiópia e Líbia estão com ele, e todos têm escudos e capacetes.

[[v26-38-6]]

^<<v26-38-6,6>>^ Todas as tropas das terras de Gomer e de Bete Togarma, que ficam no Norte, estão com ele, e também soldados de muitas outras nações.

[[v26-38-7]]

^<<v26-38-7,7>>^ Diga que se prepare e que apronte todas as tropas que ele comanda.

[[v26-38-8]]

^<<v26-38-8,8>>^ Depois de muitos anos, eu o mandarei invadir um país onde o povo tem vivido sem medo de guerra, desde quando foram trazidos de volta de muitas nações. Ele invadirá as montanhas de Israel, que tinham estado arrasadas e desertas por tanto tempo, mas onde agora todo o povo vive em segurança.

[[v26-38-9]]

^<<v26-38-9,9>>^ Ele, e o seu exército, e muitas nações que estão com ele atacarão como uma tempestade e cobrirão a terra como uma nuvem.

[[v26-38-10]]

^<<v26-38-10,10>>^ O que o Senhor  Deus diz a Gogue é isto: — Quando chegar aquela hora, você começará a fazer um plano perverso.

[[v26-38-11]]

^<<v26-38-11,11>>^ Você resolverá invadir um país desarmado, onde o povo vive calmo e seguro, em cidades sem muralhas e sem defesa.

[[v26-38-12]]

^<<v26-38-12,12>>^ Você assaltará o povo que vive em cidades já arrasadas e roubará o que há nelas. Os moradores dessas cidades foram tirados do meio das outras nações e reunidos num lugar só; e agora possuem gado e propriedades e vivem no centro do mundo .

[[v26-38-13]]

^<<v26-38-13,13>>^ O povo de Sabá e Dedã e os negociantes e as autoridades da Espanha lhe perguntarão: "Você reuniu o seu exército e atacou para assaltar e levar o que o povo tem? Você está pensando em pegar gado, prata e ouro e outras coisas de valor e ir embora com tudo o que roubar?"

[[v26-38-14]]

^<<v26-38-14,14>>^ Por isso, o Senhor  Deus me mandou falar em seu nome a Gogue e dizer a ele o seguinte: — Naquele tempo, quando o meu povo de Israel estiver vivendo em segurança, você sairá

[[v26-38-15]]

^<<v26-38-15,15>>^ e virá do seu lugar que fica no Norte distante. Você virá comandando um grande e poderoso exército de soldados de muitas nações, e todos a cavalo. Como uma tempestade que passa pela terra, você atacará o meu povo de Israel.

[[v26-38-16]]

^<<v26-38-16,16>>^ Quando chegar a hora, eu o mandarei invadir a minha terra para que as nações fiquem sabendo quem sou e vejam a minha santidade naquilo que estou fazendo por meio de você.

[[v26-38-17]]

^<<v26-38-17,17>>^ Você é aquele de quem falei há muito tempo, quando anunciei por meio dos meus servos, os profetas  de Israel, que no futuro eu iria trazer alguém para atacar o povo de Israel. O Senhor  Deus está falando.

[[v26-38-18]]

^<<v26-38-18,18>>^ O Senhor  Deus diz: — No dia em que Gogue  invadir Israel, eu ficarei furioso.

[[v26-38-19]]

^<<v26-38-19,19>>^ No calor da minha ira , afirmo que naquele dia haverá um forte terremoto na terra de Israel.

[[v26-38-20]]

^<<v26-38-20,20>>^ Todos os peixes e aves, todos os animais grandes e pequenos e todos os seres humanos do mundo inteiro tremerão de medo de mim. As montanhas serão arrasadas, as grandes pedras ficarão em pedaços, e todas as muralhas cairão.

[[v26-38-21]]

^<<v26-38-21,21>>^ Farei cair sobre Gogue todo tipo de desgraças, que o encherão de medo. Sou eu, o Senhor  Deus, quem está falando. Os soldados de Gogue ferirão uns aos outros com as suas espadas.

[[v26-38-22]]

^<<v26-38-22,22>>^ Eu os castigarei com doenças e morte. Derramarei chuvas pesadas, pedras de gelo, fogo e enxofre em cima de Gogue e do seu exército e em cima das muitas nações que estão do lado dele.

[[v26-38-23]]

^<<v26-38-23,23>>^ Desse modo, mostrarei a todas as nações que sou poderoso e santo. Elas ficarão sabendo que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[&#60; Capítulo Anterior] | <<v26-38-0,Topo>> | xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[Próximo Capítulo &#62;]