include::./index.adoc[]

[[v26-46-0]]
=== Ezequiel, 46
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-46-1]]

^<<v26-46-1,1>>^ O Senhor  Deus diz: — O portão do leste que dá para o pátio de dentro deverá ficar fechado nos seis dias úteis, mas será aberto no sábado e na Festa da Lua Nova .

[[v26-46-2]]

^<<v26-46-2,2>>^ O rei irá do pátio de fora para o salão do portão e ficará ao lado do portão. Enquanto isso, os sacerdotes oferecerão os sacrifícios  que serão completamente queimados e também as ofertas de paz. Ali o rei deverá prestar culto e depois sair. O portão deverá ficar aberto até a tarde.

[[v26-46-3]]

^<<v26-46-3,3>>^ No sábado e na Festa da Lua Nova, todo o povo também se curvará e adorará o Senhor  na frente do portão.

[[v26-46-4]]

^<<v26-46-4,4>>^ No sábado, o rei deverá apresentar ao Senhor , como sacrifícios que deverão ser completamente queimados, um carneiro e seis carneirinhos, todos sem defeito.

[[v26-46-5]]

^<<v26-46-5,5>>^ Para cada carneiro que ele trouxer, dará a Deus uma oferta de dezessete litros e meio de cereais. E, junto com cada carneirinho que for oferecido em sacrifício, ele dará o que quiser. Para cada dezessete litros e meio de oferta de cereais, ele deverá trazer três litros de azeite.

[[v26-46-6]]

^<<v26-46-6,6>>^ Na Festa da Lua Nova, ele oferecerá um touro novo, um carneiro e seis carneirinhos, todos sem defeito.

[[v26-46-7]]

^<<v26-46-7,7>>^ Junto com o touro novo e com o carneiro haverá uma oferta de dezessete litros e meio de cereais; e junto com os carneirinhos o rei dará o que quiser. Para cada dezessete litros e meio de cereais, serão oferecidos três litros de azeite.

[[v26-46-8]]

^<<v26-46-8,8>>^ O rei deverá voltar do portão, passando pelo salão, como fez para entrar.

[[v26-46-9]]

^<<v26-46-9,9>>^ — Quando o povo prestar culto ao Senhor  em qualquer festa, os que entrarem pelo portão do norte sairão pelo portão do sul, depois que acabarem de adorar. Aqueles que entrarem pelo portão do sul sairão pelo portão do norte. Ninguém sairá pelo mesmo portão pelo qual entrou, mas pelo portão do lado contrário.

[[v26-46-10]]

^<<v26-46-10,10>>^ O rei entrará quando o povo entrar e sairá quando o povo sair.

[[v26-46-11]]

^<<v26-46-11,11>>^ Nos dias de festa e de comemorações solenes, a oferta de cereais será de dezessete litros e meio por touro ou carneiro. E junto com cada carneirinho o adorador dará o que quiser. Para cada dezessete litros e meio de cereais, serão oferecidos três litros de azeite.

[[v26-46-12]]

^<<v26-46-12,12>>^ — Quando o rei tiver vontade de dar uma oferta ao Senhor , seja uma oferta que deverá ser completamente queimada ou uma oferta de paz, o portão do leste que dá para o pátio de dentro será aberto para ele. Ele fará a oferta do mesmo modo que faz no sábado, e, depois que ele sair, o portão deverá ser fechado.

[[v26-46-13]]

^<<v26-46-13,13>>^ O Senhor  diz: — Todas as manhãs, deverá ser oferecido ao Senhor  um carneirinho de um ano, sem defeito. Essa oferta deverá ser feita todos os dias.

[[v26-46-14]]

^<<v26-46-14,14>>^ Também será feita todas as manhãs a oferta de um quilo e meio de farinha e, junto com ela, um litro de azeite para misturar com a farinha. As leis  para essa oferta ao Senhor  deverão ser obedecidas para sempre.

[[v26-46-15]]

^<<v26-46-15,15>>^ O carneirinho, a farinha e o azeite deverão ser oferecidos ao Senhor  todas as manhãs, para sempre.

[[v26-46-16]]

^<<v26-46-16,16>>^ O Senhor  Deus diz o seguinte: — Se o rei der de presente uma parte das suas terras a um dos seus filhos, essa terra será do filho como parte da propriedade da sua família.

[[v26-46-17]]

^<<v26-46-17,17>>^ Mas, se o rei der de presente uma parte das suas terras a um dos seus servidores, essa terra voltará a ser do rei quando chegar o Ano da Libertação . A terra será dele e depois será dos seus filhos.

[[v26-46-18]]

^<<v26-46-18,18>>^ O rei não deverá tomar nenhuma propriedade do povo. Das suas próprias terras é que ele dará terras aos seus filhos; assim ele não explorará ninguém do meu povo, tomando a sua terra.

[[v26-46-19]]

^<<v26-46-19,19>>^ Depois disso, o homem me levou para a entrada dos cômodos de perto do portão, que ficavam de frente para o norte. São esses os cômodos santos dos sacerdotes. Ele me mostrou um lugar no lado oeste dos cômodos

[[v26-46-20]]

^<<v26-46-20,20>>^ e disse: — Este é o lugar onde os sacerdotes irão cozinhar a carne oferecida como sacrifício  para tirar pecados ou culpas e onde assarão as ofertas de farinha. Assim nenhuma coisa santa será levada para o pátio de fora, onde poderia prejudicar o povo .

[[v26-46-21]]

^<<v26-46-21,21>>^ Então ele me levou para o pátio de fora e me mostrou que em cada uma das áreas dos quatro cantos havia um pátio menor, com vinte metros de comprimento por quinze de largura.

[[v26-46-22]]

^<<v26-46-22,22>>^ Então ele me levou para o pátio de fora e me mostrou que em cada uma das áreas dos quatro cantos havia um pátio menor, com vinte metros de comprimento por quinze de largura.

[[v26-46-23]]

^<<v26-46-23,23>>^ Cada pátio era cercado por um muro de pedra, e, encostados nesses muros, havia fogões.

'''

xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]