include::./index.adoc[]

[[v26-12-0]]
=== Ezequiel, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-12-1]]

^<<v26-12-1,1>>^ O Senhor  falou comigo assim:

[[v26-12-2]]

^<<v26-12-2,2>>^ — Homem mortal , você está vivendo no meio de um povo desobediente. Eles têm olhos, mas não veem nada; têm ouvidos, mas não ouvem nada, pois são rebeldes.

[[v26-12-3]]

^<<v26-12-3,3>>^ — Agora, homem mortal, arrume uma trouxa como se você fosse um refugiado e saia antes do cair da noite. Deixe que todos vejam que você está saindo para ir a algum lugar. Pode ser que aqueles rebeldes o vejam.

[[v26-12-4]]

^<<v26-12-4,4>>^ Para que eles possam vê-lo, arrume durante o dia a sua bagagem de refugiado; e então faça com que eles vejam você partir à noitinha, como quem está indo para o cativeiro .

[[v26-12-5]]

^<<v26-12-5,5>>^ Enquanto eles estiverem olhando, abra um buraco na parede da sua casa e saia por ele com a sua trouxa.

[[v26-12-6]]

^<<v26-12-6,6>>^ Deixe que eles o vejam pôr a trouxa nas costas e saia no escuro, com o rosto coberto, para que você não possa ver aonde vai. O que você fizer será um aviso para os israelitas.

[[v26-12-7]]

^<<v26-12-7,7>>^ Eu fiz o que o Senhor  mandou. Naquele dia, arrumei uma bagagem como se fosse um refugiado. E naquela tarde, quando estava escurecendo, fiz com as minhas próprias mãos um buraco na parede e saí. E eles me viram quando coloquei a trouxa nas costas e fui embora.

[[v26-12-8]]

^<<v26-12-8,8>>^ Na manhã seguinte, o Senhor  me disse:

[[v26-12-9]]

^<<v26-12-9,9>>^ — Homem mortal, esses israelitas rebeldes estão lhe perguntando o que você está fazendo.

[[v26-12-10]]

^<<v26-12-10,10>>^ Agora, diga-lhes aquilo que eu, o Senhor  Deus, estou dizendo a eles. Esta mensagem é para o príncipe que governa em Jerusalém e para todo o povo que mora ali.

[[v26-12-11]]

^<<v26-12-11,11>>^ Diga-lhes que o que você fez é um sinal daquilo que vai acontecer com eles. Serão refugiados, serão levados para o cativeiro.

[[v26-12-12]]

^<<v26-12-12,12>>^ O príncipe que os está governando porá a sua trouxa nas costas no escuro e escapará por um buraco aberto no muro para ele. Ele cobrirá o rosto e não verá para onde estará indo.

[[v26-12-13]]

^<<v26-12-13,13>>^ Mas eu prepararei a minha armadilha e o apanharei nela. Depois, eu o levarei para a cidade de Babilônia, onde ele morrerá sem chegar a vê-la.

[[v26-12-14]]

^<<v26-12-14,14>>^ Espalharei em todas as direções todos os que vivem em volta dele, os seus conselheiros e os seus guardas; e haverá gente procurando matá-los.

[[v26-12-15]]

^<<v26-12-15,15>>^ — Quando eu os espalhar entre as outras nações e por países estrangeiros, eles ficarão sabendo que eu sou o Senhor .

[[v26-12-16]]

^<<v26-12-16,16>>^ Deixarei alguns escaparem da guerra, da fome e das doenças, de modo que, lá no meio das nações, eles compreenderão o quanto as suas ações foram vergonhosas e reconhecerão que eu sou o Senhor .

[[v26-12-17]]

^<<v26-12-17,17>>^ O Senhor  falou assim comigo:

[[v26-12-18]]

^<<v26-12-18,18>>^ — Homem mortal , trema de medo quando você comer e estremeça quando beber.

[[v26-12-19]]

^<<v26-12-19,19>>^ Diga ao povo deste país que esta é a mensagem do Senhor  Deus para a gente de Jerusalém que ainda está vivendo na sua terra. Quando eles comerem, estremecerão; e, quando beberem, tremerão de medo. Tudo o que existe na terra deles será tirado, pois todos os que vivem ali são gente violenta.

[[v26-12-20]]

^<<v26-12-20,20>>^ As cidades que agora estão cheias de gente serão destruídas, e o país vai virar um deserto. Aí eles ficarão sabendo que eu sou o Senhor .

[[v26-12-21]]

^<<v26-12-21,21>>^ O Senhor  falou comigo assim:

[[v26-12-22]]

^<<v26-12-22,22>>^ — Homem mortal , por que é que o povo de Israel repete este provérbio: "O tempo passa, e as profecias  dão em nada"?

[[v26-12-23]]

^<<v26-12-23,23>>^ Agora, diga a essa gente aquilo que eu, o Senhor  Deus, penso a respeito disso. Eu vou acabar com esse provérbio; ele nunca mais será repetido em Israel. Diga isto: "O tempo chegou, e o que foi dito está se cumprindo."

[[v26-12-24]]

^<<v26-12-24,24>>^ — Não haverá mais visões falsas nem profecias enganadoras no meio do povo de Israel.

[[v26-12-25]]

^<<v26-12-25,25>>^ Eu, o Senhor , falarei, e o que eu disser acontecerá. Não haverá mais demoras. Povo rebelde, vocês ainda estarão vivos quando eu fizer o que prometi. Eu, o Senhor  Deus, falei.

[[v26-12-26]]

^<<v26-12-26,26>>^ O Senhor  me disse:

[[v26-12-27]]

^<<v26-12-27,27>>^ — Homem mortal, os israelitas pensam que as visões que você tem e as suas profecias são a respeito de um futuro que está longe.

[[v26-12-28]]

^<<v26-12-28,28>>^ Por isso, diga a eles o que eu, o Senhor  Deus, estou dizendo: "Não haverá mais demoras. O que eu disse vai acontecer." Eu, o Senhor  Deus, falei.

'''

xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[&#60; Capítulo Anterior] | <<v26-12-0,Topo>> | xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[Próximo Capítulo &#62;]