include::./index.adoc[]

[[v26-1-0]]
=== Ezequiel, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-1-1]]

^<<v26-1-1,1>>^ No dia cinco do quarto mês do ano trinta , eu, o sacerdote Ezequiel, filho de Buzi, vivia na Babilônia, na beira do rio Quebar, junto com os judeus que haviam sido levados para lá como prisioneiros. O céu se abriu, e eu tive uma visão de Deus.

[[v26-1-2]]

^<<v26-1-2,2>>^ Quando isso aconteceu, fazia cinco anos que o rei Joaquim estava preso.

[[v26-1-3]]

^<<v26-1-3,3>>^ Ali na Babilônia, na beira do rio Quebar, eu ouvi o Senhor  falar comigo e senti o seu poder.

[[v26-1-4]]

^<<v26-1-4,4>>^ Olhei e vi uma tempestade que vinha do Norte. Raios saíam de uma nuvem enorme. Em volta da nuvem, o céu estava em fogo, e no meio do fogo havia uma coisa que brilhava como bronze.

[[v26-1-5]]

^<<v26-1-5,5>>^ No meio da tempestade, vi o que me pareciam quatro animais. A sua forma era de gente,

[[v26-1-6]]

^<<v26-1-6,6>>^ porém cada um tinha quatro caras e quatro asas.

[[v26-1-7]]

^<<v26-1-7,7>>^ As pernas deles eram retas e tinham cascos que eram parecidos com cascos de touro e que brilhavam como bronze polido.

[[v26-1-8]]

^<<v26-1-8,8>>^ Além das quatro caras e das quatro asas, cada um tinha quatro mãos de gente, uma debaixo de cada asa.

[[v26-1-9]]

^<<v26-1-9,9>>^ Duas asas de cada animal estavam abertas, com as pontas tocando uma na outra. Assim os animais formavam um quadrado e andavam em grupo, sem virar o corpo.

[[v26-1-10]]

^<<v26-1-10,10>>^ Cada animal tinha quatro caras diferentes: na frente, a cara era de gente; do lado direito, era de leão; do lado esquerdo, era de boi; e atrás a cara era de águia.

[[v26-1-11]]

^<<v26-1-11,11>>^ Duas asas de cada animal se abriam para cima e tocavam as pontas das asas dos animais que estavam ao seu lado; e com as outras duas asas eles cobriam o corpo.

[[v26-1-12]]

^<<v26-1-12,12>>^ Cada animal podia olhar para as quatro direções, e por isso o grupo ia aonde queria, sem precisar virar.

[[v26-1-13]]

^<<v26-1-13,13>>^ Entre os animais havia uma coisa que parecia uma tocha acesa e que estava sempre em movimento. O fogo aumentava, e do fogo saíam relâmpagos.

[[v26-1-14]]

^<<v26-1-14,14>>^ E os animais corriam para cá e para lá como relâmpagos.

[[v26-1-15]]

^<<v26-1-15,15>>^ Quando eu estava olhando para os quatro animais, vi quatro rodas no chão, uma ao lado de cada um deles.

[[v26-1-16]]

^<<v26-1-16,16>>^ As quatro rodas eram iguais e brilhavam como pedras preciosas. Dentro de cada roda havia outra roda, atravessada,

[[v26-1-17]]

^<<v26-1-17,17>>^ e assim, sem virar, as rodas podiam rodar em qualquer direção.

[[v26-1-18]]

^<<v26-1-18,18>>^ Os aros das rodas eram cobertos de olhos.

[[v26-1-19]]

^<<v26-1-19,19>>^ Quando os animais andavam, as rodas rodavam ao lado deles; quando os animais subiam da terra, as rodas também subiam.

[[v26-1-20]]

^<<v26-1-20,20>>^ Os animais iam aonde queriam, e as rodas faziam o que os animais faziam porque os animais as controlavam.

[[v26-1-21]]

^<<v26-1-21,21>>^ Assim, toda vez que os animais andavam ou paravam ou subiam do chão, as rodas faziam o mesmo.

[[v26-1-22]]

^<<v26-1-22,22>>^ Acima das cabeças dos animais havia uma coisa que parecia uma cobertura curva feita de cristal brilhante.

[[v26-1-23]]

^<<v26-1-23,23>>^ Debaixo da cobertura, cada animal abria duas asas na direção das asas do outro que estava ao seu lado e cobria o corpo com as outras duas asas.

[[v26-1-24]]

^<<v26-1-24,24>>^ Eu ouvi o barulho das suas asas quando voavam. Era como o rugido do mar, como o barulho de um grande exército, como a voz do Deus Todo-Poderoso. Quando paravam de voar, abaixavam as asas,

[[v26-1-25]]

^<<v26-1-25,25>>^ mas ainda se ouvia um som que vinha de cima da cobertura que estava sobre as cabeças deles.

[[v26-1-26]]

^<<v26-1-26,26>>^ Acima da cobertura curva havia uma coisa parecida com um trono feito de safira . Nele, estava sentado alguém que parecia um homem

[[v26-1-27]]

^<<v26-1-27,27>>^ e que brilhava como se fosse bronze no meio do fogo. Todo ele brilhava com o mesmo clarão de fogo.

[[v26-1-28]]

^<<v26-1-28,28>>^ E a sua luz tinha todas as cores do arco-íris nas nuvens. Esta era a luz brilhante que mostra a presença da glória  do Senhor .

'''

xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[&#60; Capítulo Anterior] | <<v26-1-0,Topo>> | xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[Próximo Capítulo &#62;]