include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-4-1]]

^<<v26-4-1,1>>^ Deus disse: — Homem mortal , pegue um tijolo, ponha na sua frente e faça nele um desenho da cidade de Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ Nesse desenho, a cidade deverá estar cercada pelos inimigos, com rampas e torres de ataque, com um acampamento e com máquinas de derrubar muralhas.

[[v26-4-3]]

^<<v26-4-3,3>>^ Pegue uma frigideira de ferro e ponha como se fosse um muro entre você e a cidade. Vire o rosto na direção da cidade. Ela está cercada, e é você quem a está cercando. Isso será um sinal para o povo de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ — Deite-se do lado esquerdo, que eu vou colocar sobre você a culpa do povo de Israel. Você ficará deitado ali, carregando o pecado deles durante trezentos e noventa dias, porque eu o condenei a um dia para cada ano de castigo do povo.

[[v26-4-5]]

^<<v26-4-5,5>>^ — Deite-se do lado esquerdo, que eu vou colocar sobre você a culpa do povo de Israel. Você ficará deitado ali, carregando o pecado deles durante trezentos e noventa dias, porque eu o condenei a um dia para cada ano de castigo do povo.

[[v26-4-6]]

^<<v26-4-6,6>>^ Quando você terminar isso, vire do lado direito e carregue o pecado de Judá durante quarenta dias, isto é, um dia para cada ano do castigo deles.

[[v26-4-7]]

^<<v26-4-7,7>>^ — Olhe firme para Jerusalém cercada pelos inimigos. Então arregace as mangas e profetize  contra a cidade.

[[v26-4-8]]

^<<v26-4-8,8>>^ Eu vou amarrá-lo, e assim você não poderá virar de um lado para outro até que os inimigos deixem de cercar a cidade.

[[v26-4-9]]

^<<v26-4-9,9>>^ — Agora, pegue trigo, cevada , ervilhas, lentilhas, trigo miúdo e aveia. Misture tudo e faça pão. É isso o que você vai comer durante os trezentos e noventa dias em que estiver deitado do lado esquerdo.

[[v26-4-10]]

^<<v26-4-10,10>>^ Você só vai poder comer quatro pãezinhos por dia e coma aos poucos.

[[v26-4-11]]

^<<v26-4-11,11>>^ A água que beber também será medida: dois copos por dia, para beber aos poucos.

[[v26-4-12]]

^<<v26-4-12,12>>^ Você fará fogo com fezes secas, de gente, assará o pão nas brasas e comerá esse pão em um lugar onde possa ser visto por todos.

[[v26-4-13]]

^<<v26-4-13,13>>^ O Senhor  disse também: — Quando eu espalhar os israelitas por outros países, é assim que eles terão de comer alimentos que a lei  proíbe .

[[v26-4-14]]

^<<v26-4-14,14>>^ Mas eu respondi: — Ó Senhor , meu Deus, isso não! Eu nunca me manchei comendo comida impura . Desde criança, nunca comi carne de nenhum animal que tivesse tido morte natural ou que tivesse sido despedaçado por animais ferozes.

[[v26-4-15]]

^<<v26-4-15,15>>^ Aí o Senhor  disse: — Está bem. Eu vou deixar você usar esterco de vaca para fazer fogo; asse o seu pão em cima dele.

[[v26-4-16]]

^<<v26-4-16,16>>^ E disse mais: — Homem mortal, eu não vou deixar que a cidade de Jerusalém receba pão. Então o povo, aflito, vai racionar a comida e a água.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]