include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-43-1]]

^<<v26-43-1,1>>^ O homem me levou até o portão do lado leste,

[[v26-43-2]]

^<<v26-43-2,2>>^ e eu vi que daquele lado vinha vindo a glória  do Deus de Israel. A voz de Deus parecia o rugido do mar, e a terra ficou iluminada com a sua glória.

[[v26-43-3]]

^<<v26-43-3,3>>^ Essa visão foi parecida com aquela que eu tive quando Deus veio para destruir Jerusalém. Também foi parecida com aquela que eu tive na beira do rio Quebar. Então caí de comprido no chão.

[[v26-43-4]]

^<<v26-43-4,4>>^ A glória do Senhor  passou pelo portão do lado leste e entrou no Templo.

[[v26-43-5]]

^<<v26-43-5,5>>^ Então o Espírito de Deus me levantou e me levou até o pátio de dentro, e eu vi que o Templo estava cheio da glória do Senhor .

[[v26-43-6]]

^<<v26-43-6,6>>^ O homem ficou ali ao meu lado, e eu ouvi o Senhor  me dizer de dentro do Templo:

[[v26-43-7]]

^<<v26-43-7,7>>^ — Homem mortal , o meu trono está neste lugar. Vou morar aqui no meio do povo de Israel e vou governá-lo para sempre. O povo de Israel e os seus reis nunca mais tornarão impuro  o meu santo nome, adorando outros deuses, nem sepultando perto do Templo os corpos dos seus reis.

[[v26-43-8]]

^<<v26-43-8,8>>^ Os reis construíram a entrada e os pilares do seu palácio encostados na entrada e nos pilares do meu Templo, e assim entre nós ficou apenas uma parede. Eles profanaram  o meu santo nome por causa de todas as coisas vergonhosas que fizeram, e por isso na minha ira  eu os destruí.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora, eles que deixem de adorar outros deuses e levem para longe os corpos dos seus reis. Se fizerem isso, eu viverei no meio deles para sempre.

[[v26-43-10]]

^<<v26-43-10,10>>^ E o Senhor  continuou: — Homem mortal, fale com o povo de Israel a respeito do Templo, para que eles estudem a sua planta. Faça com que fiquem envergonhados por causa dos seus pecados.

[[v26-43-11]]

^<<v26-43-11,11>>^ Se eles ficarem com vergonha do que têm feito, explique a planta do Templo para eles, isto é, o seu modelo, as entradas e saídas, as formas, o modo como tudo está arrumado e todas as leis  e regulamentos. Escreva todas essas coisas para que eles possam ver como tudo está arrumado e para que cumpram todos os regulamentos.

[[v26-43-12]]

^<<v26-43-12,12>>^ Esta é a lei do Templo: todo o terreno que fica em volta dele no alto da montanha é santo e sagrado.

[[v26-43-13]]

^<<v26-43-13,13>>^ Seguem as medidas do altar, usando-se as mesmas que foram usadas para medir o Templo. Na base do altar, em toda a volta, havia uma valeta de meio metro de fundura por meio metro de largura. Do lado de fora havia uma beirada de vinte e cinco centímetros de altura.

[[v26-43-14]]

^<<v26-43-14,14>>^ A parte mais baixa do altar tinha um metro de altura. A parte do meio media dois metros de altura e estava afastada meio metro da beirada, em toda a volta. A parte de cima também estava afastada meio metro da beirada, em toda a volta.

[[v26-43-15]]

^<<v26-43-15,15>>^ Essa parte de cima também tinha dois metros de altura, e sobre ela eram queimados os sacrifícios . Os quatro cantos dessa parte eram salientes e virados para cima.

[[v26-43-16]]

^<<v26-43-16,16>>^ A parte de cima do altar era quadrada, medindo seis metros de cada lado.

[[v26-43-17]]

^<<v26-43-17,17>>^ A parte do meio também era quadrada, medindo sete metros de cada lado. Em volta dela havia uma beirada de vinte e cinco centímetros de altura. A valeta media meio metro de largura. Os degraus do altar ficavam no lado leste.

[[v26-43-18]]

^<<v26-43-18,18>>^ O Senhor  Deus me disse: — Homem mortal , escute o que estou lhe dizendo. Quando o altar estiver construído, você vai consagrá-lo, queimando sacrifícios  em cima dele e borrifando nele o sangue dos animais que forem sacrificados.

[[v26-43-19]]

^<<v26-43-19,19>>^ Só os sacerdotes da tribo  de Levi que são descendentes de Zadoque poderão vir até a minha presença para me servir. Eu, o Senhor  Deus, ordeno isso. Você lhes dará um touro novo para oferecerem como sacrifício para tirar pecados.

[[v26-43-20]]

^<<v26-43-20,20>>^ Você pegará um pouco do sangue desse touro e porá nas pontas da parte de cima do altar e nas pontas da parte do meio do altar e em toda a volta das suas beiradas. Dessa maneira, você purificará  o altar e o consagrará.

[[v26-43-21]]

^<<v26-43-21,21>>^ Você pegará o touro que for oferecido como sacrifício para tirar pecados e o queimará no lugar marcado, fora da área do Templo.

[[v26-43-22]]

^<<v26-43-22,22>>^ No dia seguinte, você pegará um bode sem defeito e o oferecerá como sacrifício para tirar pecados. Purifique o altar com o sangue dele, do mesmo modo que você tiver feito com o sangue do touro.

[[v26-43-23]]

^<<v26-43-23,23>>^ Quando terminar essa parte, pegue um touro novo e um carneirinho, os dois sem defeito,

[[v26-43-24]]

^<<v26-43-24,24>>^ e traga-os para mim, o Senhor . Depois de matarem os animais, os sacerdotes espalharão sal sobre eles e os queimarão como oferta para mim.

[[v26-43-25]]

^<<v26-43-25,25>>^ Sete dias em seguida, você oferecerá um bode, um touro e um carneirinho como sacrifícios para tirar pecados. Esses animais não devem ter nenhum defeito.

[[v26-43-26]]

^<<v26-43-26,26>>^ Durante sete dias, os sacerdotes consagrarão o altar e o aprontarão para ser usado.

[[v26-43-27]]

^<<v26-43-27,27>>^ Depois dessa semana, os sacerdotes começarão a oferecer sobre o altar as ofertas que serão completamente queimadas e as ofertas de paz trazidas pelo povo. Então ficarei contente com todos vocês. Eu, o Senhor  Deus, falei.

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]