include::./index.adoc[]

[[v26-44-0]]
=== Ezequiel, 44
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-44-1]]

^<<v26-44-1,1>>^ O homem me levou até o portão de fora, no lado leste da área do Templo. O portão estava fechado.

[[v26-44-2]]

^<<v26-44-2,2>>^ Então o Senhor  me disse: — Este portão ficará fechado; nunca será aberto. Ninguém poderá usá-lo, porque eu, o Senhor , o Deus de Israel, entrei por ele. Deve ficar sempre fechado,

[[v26-44-3]]

^<<v26-44-3,3>>^ mas o rei poderá ir lá para comer uma refeição santa na minha presença. Ele entrará e sairá pelo salão interno desse portão.

[[v26-44-4]]

^<<v26-44-4,4>>^ Então o homem me fez passar pelo portão do norte e me levou para a frente do Templo. Olhei e vi que o Templo estava cheio da glória  do Senhor . Eu me atirei de comprido no chão.

[[v26-44-5]]

^<<v26-44-5,5>>^ Então o Senhor  me disse: — Homem mortal , preste atenção em tudo o que você vir e ouvir. Eu vou lhe dar as leis  e regulamentos do Templo. Note bem quais as pessoas que têm permissão para entrar no Templo e as que não têm.

[[v26-44-6]]

^<<v26-44-6,6>>^ — Diga a esses israelitas rebeldes que eu, o Senhor  Deus, não vou tolerar mais as coisas vergonhosas que eles estão fazendo.

[[v26-44-7]]

^<<v26-44-7,7>>^ Eles têm profanado  o meu Templo, deixando estrangeiros que não foram circuncidados , gente que não me conhece, entrar no pátio do Templo quando a gordura e o sangue dos sacrifícios  estão sendo oferecidos a mim. Assim, fazendo todas essas coisas vergonhosas, o meu povo tem quebrado a minha aliança .

[[v26-44-8]]

^<<v26-44-8,8>>^ Eles deixaram que estrangeiros realizassem no meu Templo as cerimônias sagradas, em vez de eles mesmos fazerem isso.

[[v26-44-9]]

^<<v26-44-9,9>>^ — Eu, o Senhor  Deus, afirmo que nenhum estrangeiro que não foi circuncidado, que não me obedece, entrará no pátio do meu Templo, nem mesmo o estrangeiro que esteja vivendo no meio do povo de Israel.

[[v26-44-10]]

^<<v26-44-10,10>>^ — Os levitas  me abandonaram juntamente com o resto do povo de Israel, e adoraram ídolos, e por isso estão sendo castigados.

[[v26-44-11]]

^<<v26-44-11,11>>^ Eles podem me servir tomando conta dos portões e fazendo os serviços do Templo; podem matar os animais que o povo traz como ofertas para serem completamente queimadas e como sacrifícios. E ficarão no meio do povo prontos para servir.

[[v26-44-12]]

^<<v26-44-12,12>>^ Eles se encarregaram do culto de ídolos para o povo de Israel e assim fizeram os israelitas pecarem; por isso, eu, o Senhor  Deus, juro solenemente que serão castigados.

[[v26-44-13]]

^<<v26-44-13,13>>^ Eles não me servirão como sacerdotes, nem chegarão perto de nada que seja santo para mim, nem entrarão no Lugar Santíssimo . O castigo pelas coisas vergonhosas que eles fizeram é este:

[[v26-44-14]]

^<<v26-44-14,14>>^ eu os encarrego de guardar o Templo e de fazer todos os serviços dele.

[[v26-44-15]]

^<<v26-44-15,15>>^ O Senhor  Deus disse: — Porém, quando todo o resto do povo de Israel se afastou de mim, os sacerdotes da tribo  de Levi que são descendentes de Zadoque continuaram a me servir fielmente no Templo. Agora, eles me servirão e virão até a minha presença para me oferecer a gordura e o sangue dos sacrifícios .

[[v26-44-16]]

^<<v26-44-16,16>>^ Somente eles entrarão no meu Templo, servirão no meu altar e se encarregarão do culto no Templo.

[[v26-44-17]]

^<<v26-44-17,17>>^ Quando entrarem pelo portão do pátio de dentro do Templo, deverão vestir roupas de linho. Quando estiverem de serviço no pátio de dentro ou no Templo, não deverão usar nada que seja feito de lã.

[[v26-44-18]]

^<<v26-44-18,18>>^ Deverão usar turbantes  de linho e calças de linho; mas, para não suarem, não usarão cinto.

[[v26-44-19]]

^<<v26-44-19,19>>^ Antes de saírem para o pátio de fora, onde o povo está, deverão primeiro tirar as roupas que usaram ao servirem no Templo, deixando-as nas salas sagradas. Eles deverão vestir outra roupa a fim de evitar que a sua roupa sagrada prejudique o povo .

[[v26-44-20]]

^<<v26-44-20,20>>^ — Os sacerdotes não devem rapar a cabeça, nem deixar o cabelo ficar comprido, mas devem cortá-lo com decência.

[[v26-44-21]]

^<<v26-44-21,21>>^ Os sacerdotes não beberão vinho antes de entrar no pátio de dentro.

[[v26-44-22]]

^<<v26-44-22,22>>^ O sacerdote não poderá casar nem com viúva nem com mulher divorciada, mas somente com uma virgem israelita ou com a viúva de um sacerdote.

[[v26-44-23]]

^<<v26-44-23,23>>^ — Os sacerdotes ensinarão ao meu povo a diferença entre o que é santo e o que não é e entre o que é puro  e o que é impuro .

[[v26-44-24]]

^<<v26-44-24,24>>^ Quando houver uma questão legal, os sacerdotes decidirão o caso de acordo com as minhas leis . Eles comemorarão as festas religiosas de acordo com as minhas leis e regulamentos e manterão santos os sábados.

[[v26-44-25]]

^<<v26-44-25,25>>^ — O sacerdote não deverá tocar num morto porque, se fizer isso, ficará impuro. Mas poderá tocar no cadáver do pai ou da mãe, ou de um filho, ou de um irmão, ou de uma irmã solteira.

[[v26-44-26]]

^<<v26-44-26,26>>^ Depois que ele se purificar  de novo, deverá esperar sete dias;

[[v26-44-27]]

^<<v26-44-27,27>>^ então entrará no pátio de dentro do Templo e oferecerá um sacrifício pela sua purificação, para que assim possa servir de novo no Templo. Sou eu, o Senhor  Deus, quem está falando.

[[v26-44-28]]

^<<v26-44-28,28>>^ — Os sacerdotes terão uma herança: eu sou a sua herança. Eles não terão propriedades em Israel: eu sou a sua propriedade.

[[v26-44-29]]

^<<v26-44-29,29>>^ As ofertas de cereais e as ofertas feitas para tirar pecados ou culpas serão o alimento dos sacerdotes, e tudo o que for separado para mim em Israel será deles.

[[v26-44-30]]

^<<v26-44-30,30>>^ Os sacerdotes receberão o melhor de todas as primeiras colheitas e de tudo mais que for oferecido a mim. Toda vez que as pessoas assarem pão, darão aos sacerdotes o primeiro pão como oferta, e assim a minha bênção ficará sobre as suas casas.

[[v26-44-31]]

^<<v26-44-31,31>>^ Os sacerdotes não deverão comer nenhum pássaro ou animal que tenha tido morte natural ou que tenha sido morto por outro animal.

'''

xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[&#60; Capítulo Anterior] | <<v26-44-0,Topo>> | xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[Próximo Capítulo &#62;]