include::./index.adoc[]

[[v26-2-0]]
=== Ezequiel, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-2-1]]

^<<v26-2-1,1>>^ Quando vi isso, caí e encostei o rosto no chão. Então ouvi uma voz que dizia: — Homem mortal , fique de pé. Eu quero falar com você.

[[v26-2-2]]

^<<v26-2-2,2>>^ Enquanto a voz falava, o Espírito de Deus entrou em mim e me fez ficar em pé. E eu ouvi a voz dizer:

[[v26-2-3]]

^<<v26-2-3,3>>^ — Homem mortal, eu o estou mandando ao povo de Israel, que se revoltou e se virou contra mim. Eles ainda são rebeldes, como os antepassados deles também eram.

[[v26-2-4]]

^<<v26-2-4,4>>^ São teimosos e não me respeitam. Estou mandando você para dizer a eles aquilo que eu, o Senhor  Deus, quero dizer.

[[v26-2-5]]

^<<v26-2-5,5>>^ Tanto se derem atenção a você como se não derem, eles vão saber que um profeta  esteve no meio deles.

[[v26-2-6]]

^<<v26-2-6,6>>^ — Mas você, homem mortal, não precisa ficar com medo deles, nem do que eles disserem. Eles o desafiarão e desprezarão; viver no meio deles será como viver no meio de escorpiões. Mesmo assim, não tenha medo daqueles rebeldes, nem de qualquer coisa que eles disserem.

[[v26-2-7]]

^<<v26-2-7,7>>^ Diga-lhes tudo o que eu mandar, quer eles lhe deem atenção ou não. Lembre que eles são teimosos.

[[v26-2-8]]

^<<v26-2-8,8>>^ — Homem mortal, preste atenção no que eu estou dizendo. Não seja teimoso como eles. Abra a boca e coma o que vou dar a você.

[[v26-2-9]]

^<<v26-2-9,9>>^ Aí eu vi uma mão que se estendia para mim, segurando um rolo.

[[v26-2-10]]

^<<v26-2-10,10>>^ Ela o desenrolou, e vi que nos dois lados havia coisas escritas. E o que estava escrito eram gritos de dor, lamentos e gemidos.

'''

xref:026-ezequiel/026-ezequiel-001.adoc#v26-1-0[&#60; Capítulo Anterior] | <<v26-2-0,Topo>> | xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[Próximo Capítulo &#62;]