include::./index.adoc[]

[[v26-25-0]]
=== Ezequiel, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-25-1]]

^<<v26-25-1,1>>^ O Senhor  me disse o seguinte:

[[v26-25-2]]

^<<v26-25-2,2>>^ — Homem mortal , agora fale contra o país de Amom.

[[v26-25-3]]

^<<v26-25-3,3>>^ Diga que deem atenção a isto que eu, o Senhor  Deus, estou dizendo: "Vocês ficaram contentes quando viram o meu Templo profanado , quando viram a terra de Israel arrasada e o povo de Judá ser levado para o cativeiro .

[[v26-25-4]]

^<<v26-25-4,4>>^ Por isso, vou deixar que as tribos do deserto oriental conquistem vocês. Esses povos montarão os seus acampamentos no país de vocês e ficarão morando aí. Eles comerão as frutas e beberão o leite que eram de vocês.

[[v26-25-5]]

^<<v26-25-5,5>>^ Transformarei a cidade de Rabá num curral de camelos e toda a terra de Amom num curral de ovelhas, e assim vocês ficarão sabendo que eu sou o Senhor ."

[[v26-25-6]]

^<<v26-25-6,6>>^ — O que o Senhor  Deus está dizendo é isto: "Vocês, amonitas, bateram palmas e pularam de alegria. Vocês desprezaram a terra de Israel.

[[v26-25-7]]

^<<v26-25-7,7>>^ Por isso, eu os entregarei a outras nações para que elas roubem o que vocês têm. Eu os destruirei completamente, de modo que não serão mais uma nação, nem terão mais um país de vocês mesmos. Aí vocês ficarão sabendo que eu sou o Senhor ."

[[v26-25-8]]

^<<v26-25-8,8>>^ O Senhor  Deus disse: — Moabe disse que Judá é como todas as outras nações,

[[v26-25-9]]

^<<v26-25-9,9>>^ e por isso deixarei que as cidades que defendem a fronteira de Moabe sejam atacadas. Entre elas, estarão as mais importantes: Bete-Jesimote, Baal-Meom e Quiriataim.

[[v26-25-10]]

^<<v26-25-10,10>>^ Deixarei que as tribos do deserto oriental conquistem Moabe, juntamente com Amom, e assim Moabe não será mais uma nação.

[[v26-25-11]]

^<<v26-25-11,11>>^ Castigarei Moabe, e os moabitas ficarão sabendo que eu sou o Senhor .

[[v26-25-12]]

^<<v26-25-12,12>>^ O Senhor  Deus disse: — O povo de Edom foi cruel na vingança contra Judá, e essa vingança fez com que a culpa de Edom aumentasse muito.

[[v26-25-13]]

^<<v26-25-13,13>>^ Agora, anuncio que castigarei Edom e matarei ali todos os homens e animais. O povo será morto na batalha, e eu farei Edom virar um deserto, desde a cidade de Temã até Dedã.

[[v26-25-14]]

^<<v26-25-14,14>>^ Por meio do meu povo de Israel, eu me vingarei de Edom; ele fará Edom sentir a fúria da minha ira . Os edomitas saberão o que é sofrer a minha vingança. Eu, o Senhor  Deus, falei.

[[v26-25-15]]

^<<v26-25-15,15>>^ O Senhor  Deus disse: — Os filisteus foram cruéis na vingança contra os seus antigos inimigos e os destruíram com ódio.

[[v26-25-16]]

^<<v26-25-16,16>>^ Agora, eu estou anunciando que atacarei os filisteus e os queretitas e acabarei com eles. Destruirei todos aqueles que forem deixados vivos na planície da Filisteia.

[[v26-25-17]]

^<<v26-25-17,17>>^ Eu os castigarei duramente, e a minha vingança será completa. Aí ficarão sabendo que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]