include::./index.adoc[]

[[v26-6-0]]
=== Ezequiel, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-6-1]]

^<<v26-6-1,1>>^ O Senhor  Deus falou comigo assim:

[[v26-6-2]]

^<<v26-6-2,2>>^ — Homem mortal , olhe para as montanhas de Israel e dê a elas a minha mensagem.

[[v26-6-3]]

^<<v26-6-3,3>>^ Diga que ouçam a palavra do Senhor  Deus, que ouçam aquilo que estou dizendo às montanhas, às colinas, aos desfiladeiros e aos vales: Eu, o Senhor  Deus, mandarei uma espada para destruir os lugares onde o povo adora ídolos.

[[v26-6-4]]

^<<v26-6-4,4>>^ Os altares de sacrifícios  e os altares onde se queima incenso serão derrubados e arrasados. Todas as pessoas dali serão mortas na frente dos seus ídolos.

[[v26-6-5]]

^<<v26-6-5,5>>^ Espalharei os cadáveres do povo de Israel; espalharei os ossos deles em volta dos altares.

[[v26-6-6]]

^<<v26-6-6,6>>^ Todas as cidades de Israel serão arrasadas, e os lugares onde se adoram ídolos serão destruídos. Assim todos os seus altares e os seus ídolos serão quebrados, os seus altares de incenso serão arrebentados, e tudo o que fizeram desaparecerá.

[[v26-6-7]]

^<<v26-6-7,7>>^ Pessoas serão mortas por toda parte, e os que ficarem vivos reconhecerão que eu sou o Senhor .

[[v26-6-8]]

^<<v26-6-8,8>>^ — No entanto, deixarei que alguns escapem da matança e sejam espalhados entre as nações

[[v26-6-9]]

^<<v26-6-9,9>>^ para onde forem levados como prisioneiros. Ali eles lembrarão de mim e saberão que eu os castiguei e os envergonhei porque o seu coração infiel me abandonou, e, em vez de me adorarem, eles preferiram adorar ídolos. E eles odiarão a si mesmos por causa das suas maldades e das coisas nojentas que fizeram.

[[v26-6-10]]

^<<v26-6-10,10>>^ Saberão que eu sou o Senhor  e que as minhas ameaças não foram feitas à toa.

[[v26-6-11]]

^<<v26-6-11,11>>^ O Senhor  Deus disse: — Ezequiel, torça as mãos, bata os pés e grite de tristeza por causa de todas as coisas más e nojentas que os israelitas fizeram. Eles morrerão na guerra, de fome e de doença.

[[v26-6-12]]

^<<v26-6-12,12>>^ Os que estiverem longe ficarão doentes e morrerão; os que estiverem perto serão mortos na guerra. Os que restarem morrerão de fome. Eles sentirão toda a força da minha ira .

[[v26-6-13]]

^<<v26-6-13,13>>^ Corpos de mortos serão espalhados entre os ídolos e em volta dos altares. Esses corpos serão espalhados nos lugares onde o povo queimou sacrifícios  aos seus ídolos, isto é, em todos os lugares altos, no alto de todas as montanhas, debaixo de todas as árvores verdes e de todos os grandes carvalhos. Então todos saberão que eu sou o Senhor .

[[v26-6-14]]

^<<v26-6-14,14>>^ Levantarei a mão e destruirei o país deles. Desde o deserto, no Sul, até a cidade de Ribla, no Norte, eu farei com que a sua terra fique abandonada e não terei pena de nenhum lugar onde os israelitas vivem. Então todos ficarão sabendo que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]