include::./index.adoc[]

[[v26-29-0]]
=== Ezequiel, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-29-1]]

^<<v26-29-1,1>>^ No décimo ano do nosso cativeiro , no dia doze do décimo mês , o Senhor  me disse o seguinte:

[[v26-29-2]]

^<<v26-29-2,2>>^ — Homem mortal , fale contra o rei do Egito . Diga-lhe como ele e toda a terra do Egito serão castigados.

[[v26-29-3]]

^<<v26-29-3,3>>^ Diga que o Senhor  Deus está dizendo isto ao rei do Egito: "Eu estou contra você, crocodilo monstruoso deitado no rio. Você diz que o rio Nilo é seu, que você mesmo o fez.

[[v26-29-4]]

^<<v26-29-4,4>>^ Mas eu porei um gancho no seu focinho e farei com que os peixes do seu rio fiquem agarrados em você. Então eu o puxarei para fora do rio Nilo, com todos os peixes agarrados em você.

[[v26-29-5]]

^<<v26-29-5,5>>^ Eu o jogarei no deserto e todos aqueles peixes também. O seu corpo ficará largado no chão e não será sepultado. Eu o darei às aves e aos animais selvagens como alimento.

[[v26-29-6]]

^<<v26-29-6,6>>^ Assim todo o povo do Egito ficará sabendo que eu sou o Senhor ." O Senhor  diz ao Egito: — Os israelitas se apoiaram em você, mas você foi um bastão fraco.

[[v26-29-7]]

^<<v26-29-7,7>>^ Quando eles se apoiaram, você quebrou, machucou o ombro deles e fez com que torcessem as costas.

[[v26-29-8]]

^<<v26-29-8,8>>^ Por isso, eu, o Senhor  Deus, estou lhe dizendo que farei com que homens o ataquem com espadas, e eles matarão a sua gente e os seus animais.

[[v26-29-9]]

^<<v26-29-9,9>>^ O Egito vai virar um deserto vazio. Aí você ficará sabendo que eu sou o Senhor . — Você disse que o rio Nilo é seu e que foi você que o fez,

[[v26-29-10]]

^<<v26-29-10,10>>^ e por isso eu estou contra você e contra o seu rio Nilo. Farei com que todo o Egito vire um deserto vazio, desde a cidade de Migdol, no Norte, até a cidade de Assuã, no Sul, e até a fronteira da Etiópia.

[[v26-29-11]]

^<<v26-29-11,11>>^ Nenhuma pessoa ou animal passará pelas suas terras. Durante quarenta anos, o Egito ficará sem moradores.

[[v26-29-12]]

^<<v26-29-12,12>>^ Farei do Egito o país mais deserto do mundo. Durante quarenta anos, as cidades do Egito ficarão arrasadas, mais arrasadas do que quaisquer outras cidades. Farei com que os egípcios se tornem refugiados. Fugirão para todos os países e viverão no meio de outros povos.

[[v26-29-13]]

^<<v26-29-13,13>>^ O Senhor  Deus diz: — Depois desses quarenta anos, trarei os egípcios de volta das nações por onde os espalhei.

[[v26-29-14]]

^<<v26-29-14,14>>^ Eu os deixarei viver no Sul do Egito, a região de onde vieram. Ali eles serão um reino pequeno,

[[v26-29-15]]

^<<v26-29-15,15>>^ o mais fraco de todos, e nunca mais dominarão outras nações. Eu os diminuirei tanto, que não serão capazes de dominá-las.

[[v26-29-16]]

^<<v26-29-16,16>>^ Israel nunca mais dependerá da ajuda deles. O que aconteceu com o Egito fará com que o povo de Israel lembre como estava errado em confiar nos egípcios. Então Israel ficará sabendo que eu sou o Senhor  Deus.

[[v26-29-17]]

^<<v26-29-17,17>>^ No ano vigésimo sétimo do nosso cativeiro , no primeiro dia do primeiro mês , o Senhor  falou comigo. Ele disse:

[[v26-29-18]]

^<<v26-29-18,18>>^ — Homem mortal , escute. Nabucodonosor, rei da Babilônia, atacou a cidade de Tiro . Ele obrigou os seus soldados a carregarem tanto peso, que os cabelos deles caíram, e os seus ombros ficaram esfolados. Mas nem o rei nem o seu exército conseguiram nada como pagamento pelos seus esforços.

[[v26-29-19]]

^<<v26-29-19,19>>^ — Agora, eu, o Senhor  Deus, digo isto: "Darei a terra do Egito ao rei Nabucodonosor. Ele vai pegar toda a riqueza do Egito e vai levá-la como pagamento para o seu exército.

[[v26-29-20]]

^<<v26-29-20,20>>^ Eu darei a Nabucodonosor o Egito como pagamento pelos seus serviços, pois o seu exército está trabalhando para mim. Sou eu, o Senhor  Deus, quem está falando."

[[v26-29-21]]

^<<v26-29-21,21>>^ — Quando isso acontecer, farei com que o povo de Israel fique forte. E a você, Ezequiel, vou dar licença para falar onde todos possam ouvi-lo, e assim eles ficarão sabendo que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]