include::./index.adoc[]

[[v26-42-0]]
=== Ezequiel, 42
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-42-1]]

^<<v26-42-1,1>>^ Então o homem me fez sair para o pátio de fora e me levou para o lado norte do Templo, a um edifício que não ficava longe do edifício construído na ponta oeste do Templo.

[[v26-42-2]]

^<<v26-42-2,2>>^ Esse edifício do lado norte media cinquenta metros de comprimento por vinte e cinco de largura.

[[v26-42-3]]

^<<v26-42-3,3>>^ De um lado, dava frente para o espaço de dez metros ao longo do Templo e, do outro lado, dava frente para a calçada do pátio de fora. Tinha três andares, e cada um deles ficava mais para dentro do que o de baixo.

[[v26-42-4]]

^<<v26-42-4,4>>^ No lado norte desse edifício havia uma passagem de cinco metros de largura por cinquenta de comprimento, com entradas desse lado.

[[v26-42-5]]

^<<v26-42-5,5>>^ Os cômodos do andar de cima eram mais estreitos do que os do andar do meio e do térreo porque ficavam mais para dentro.

[[v26-42-6]]

^<<v26-42-6,6>>^ Nos três andares, os cômodos ficavam em terraços e não eram sustentados por colunas como os outros edifícios do pátio.

[[v26-42-7]]

^<<v26-42-7,7>>^ No andar térreo, a parede de fora do edifício media cinquenta metros. Numa metade dessa parede havia cômodos; na outra metade não havia. Todo o andar de cima era dividido em cômodos.

[[v26-42-8]]

^<<v26-42-8,8>>^ No andar térreo, a parede de fora do edifício media cinquenta metros. Numa metade dessa parede havia cômodos; na outra metade não havia. Todo o andar de cima era dividido em cômodos.

[[v26-42-9]]

^<<v26-42-9,9>>^ Na ponta leste do edifício, onde começava a parede, havia, debaixo dos cômodos, uma entrada que dava para o pátio de fora. No lado sul do Templo havia um edifício igual ao anterior, perto do prédio que ficava na ponta oeste do Templo.

[[v26-42-10]]

^<<v26-42-10,10>>^ Na ponta leste do edifício, onde começava a parede, havia, debaixo dos cômodos, uma entrada que dava para o pátio de fora.

[[v26-42-11]]

^<<v26-42-11,11>>^ Na frente dos cômodos havia uma passagem igual à do lado norte. Tinha as mesmas medidas, o mesmo desenho e o mesmo tipo de entradas.

[[v26-42-12]]

^<<v26-42-12,12>>^ Havia, debaixo dos cômodos, uma porta no lado sul do edifício, na ponta leste onde começava a parede.

[[v26-42-13]]

^<<v26-42-13,13>>^ O homem me disse: — Estes dois edifícios são sagrados. Neles, os sacerdotes que entram na presença do Senhor  comem as coisas santíssimas. E, porque os cômodos são santos, os sacerdotes colocarão neles as ofertas santíssimas, isto é, as ofertas de cereais e as ofertas feitas para tirar pecados e culpas.

[[v26-42-14]]

^<<v26-42-14,14>>^ Quando os sacerdotes estiverem no Templo e quiserem sair para o pátio de fora, terão de deixar nesses cômodos as roupas santas que tiverem usado durante o culto religioso. Eles terão de vestir outras roupas antes de saírem para o lugar onde o povo se reúne.

[[v26-42-15]]

^<<v26-42-15,15>>^ Quando acabou de medir por dentro a área do Templo, o homem me fez sair pelo portão do lado leste e então mediu a área por fora.

[[v26-42-16]]

^<<v26-42-16,16>>^ Com a vara de medir, ele mediu o lado leste: tinha duzentos e cinquenta metros.

'''

xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[&#60; Capítulo Anterior] | <<v26-42-0,Topo>> | xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[Próximo Capítulo &#62;]