include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-35-1]]

^<<v26-35-1,1>>^ O Senhor  falou comigo. Ele disse:

[[v26-35-2]]

^<<v26-35-2,2>>^ — Homem mortal , fale contra o país de Edom.

[[v26-35-3]]

^<<v26-35-3,3>>^ Diga ao povo que eu, o Senhor  Deus, estou dizendo o seguinte: "Montanhas de Edom, eu estou contra vocês! Farei de você, Edom, um deserto sem moradores.

[[v26-35-4]]

^<<v26-35-4,4>>^ Deixarei a sua terra e as suas cidades arrasadas e em ruínas. Aí você ficará sabendo que eu sou o Senhor .

[[v26-35-5]]

^<<v26-35-5,5>>^ — "Você sempre tem sido inimigo de Israel. No tempo da desgraça dos israelitas, no tempo do seu castigo final por causa dos seus pecados, você deixou que eles fossem mortos.

[[v26-35-6]]

^<<v26-35-6,6>>^ Por isso, eu, o Senhor  Deus, juro pela minha vida que o seu fim é a morte e que você não poderá escapar. Você é culpado de crime de morte, e a morte o perseguirá.

[[v26-35-7]]

^<<v26-35-7,7>>^ Farei com que a região montanhosa de Edom vire um deserto e matarei todos os que passarem por ali.

[[v26-35-8]]

^<<v26-35-8,8>>^ Cobrirei as montanhas e os morros com cadáveres; os corpos dos que forem mortos em combate encherão os vales e os ribeirões.

[[v26-35-9]]

^<<v26-35-9,9>>^ Farei de você um deserto para sempre, e nunca mais ninguém viverá nas suas cidades. Aí você ficará sabendo que eu sou o Senhor .

[[v26-35-10]]

^<<v26-35-10,10>>^ — "Você disse que a nação de Judá, a nação de Israel e as terras delas são suas e que você vai tomar posse delas, mesmo que eu, o Senhor , esteja ali.

[[v26-35-11]]

^<<v26-35-11,11>>^ Por isso, eu, o Senhor  Deus, juro pela minha vida que o tratarei com a mesma ira , inveja e ódio com que você tratou o meu povo. Eles ficarão sabendo que eu o estou castigando pelo que você fez com eles.

[[v26-35-12]]

^<<v26-35-12,12>>^ E você ficará sabendo que eu, o Senhor , ouvi você dizer com desprezo que as montanhas de Israel estavam arrasadas e que você ia devorá-las.

[[v26-35-13]]

^<<v26-35-13,13>>^ Muitas vezes, eu o ouvi falar contra mim com desprezo."

[[v26-35-14]]

^<<v26-35-14,14>>^ O Senhor  Deus diz: — Eu o arrasarei de tal forma, que o mundo inteiro se alegrará com a sua queda,

[[v26-35-15]]

^<<v26-35-15,15>>^ do mesmo modo que você se alegrou quando a minha propriedade particular, a terra de Israel, virou um deserto. Toda a região montanhosa de Edom se tornará um deserto. Aí todos ficarão sabendo que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]