include::./index.adoc[]

[[v26-33-0]]
=== Ezequiel, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-33-1]]

^<<v26-33-1,1>>^ O Senhor  me disse o seguinte:

[[v26-33-2]]

^<<v26-33-2,2>>^ — Homem mortal , diga ao seu povo o que acontece quando eu faço vir a guerra a um lugar. O povo desse lugar escolhe alguém para ser vigia.

[[v26-33-3]]

^<<v26-33-3,3>>^ Quando vê o inimigo chegando, o vigia dá o alarme para avisar toda a gente.

[[v26-33-4]]

^<<v26-33-4,4>>^ Se alguém ouve o aviso, porém não se importa, e o inimigo vem e o mata, esse alguém é responsável pela sua própria morte.

[[v26-33-5]]

^<<v26-33-5,5>>^ Ele é culpado da sua própria morte porque não se importou com o alarme. Se tivesse se importado, poderia ter escapado.

[[v26-33-6]]

^<<v26-33-6,6>>^ Mas, se o vigia vê o inimigo se aproximando e não dá o alarme, o inimigo vem e mata aqueles pecadores. Nesse caso, eu considerarei o vigia como responsável pela morte deles.

[[v26-33-7]]

^<<v26-33-7,7>>^ — Agora, homem mortal, eu estou pondo você como vigia de toda a nação de Israel. Você dará a eles os avisos que eu lhe der.

[[v26-33-8]]

^<<v26-33-8,8>>^ Se eu disser que um homem mau vai morrer, mas você não o avisar para que mude o seu modo de agir e assim salve a sua vida, aí ele morrerá, sendo ainda pecador. Nesse caso, eu considerarei você como responsável pela morte dele.

[[v26-33-9]]

^<<v26-33-9,9>>^ Porém, se você avisar o homem mau, e ele não parar de pecar, ele morrerá como pecador, mas você viverá.

[[v26-33-10]]

^<<v26-33-10,10>>^ O Senhor  me disse o seguinte: — Homem mortal , repita aos israelitas o que eles andam dizendo: "Os nossos pecados e maldades são um peso para nós. Estamos nos acabando. Como podemos viver?"

[[v26-33-11]]

^<<v26-33-11,11>>^ Diga-lhes que juro pela minha vida que eu, o Senhor  Deus, não me alegro com a morte de um pecador. Eu gostaria que ele parasse de fazer o mal e vivesse. Povo de Israel, pare de fazer o mal. Por que é que vocês estão querendo morrer?

[[v26-33-12]]

^<<v26-33-12,12>>^ — Agora, homem mortal, diga aos israelitas que, quando um homem correto pecar, o bem que ele fez não o salvará. Se um homem mau parar de fazer o mal, ele não será castigado; e, se um homem correto começar a pecar, ele não continuará vivendo.

[[v26-33-13]]

^<<v26-33-13,13>>^ Se eu prometer dar a vida a um homem correto, e se ele começar a pecar porque pensa que a sua bondade passada o salvará, aí eu não lembrarei de nenhuma das boas ações que praticou. Ele morrerá por causa dos seus pecados.

[[v26-33-14]]

^<<v26-33-14,14>>^ Se eu avisar um homem mau, dizendo que vai morrer, e se ele parar de pecar e fizer o que é bom e correto —

[[v26-33-15]]

^<<v26-33-15,15>>^ por exemplo, se devolver o objeto que lhe deram como garantia de pagamento de uma dívida ou se devolver o que roubou — se ele parar de pecar e seguir as leis  que dão vida, ele não morrerá, mas viverá.

[[v26-33-16]]

^<<v26-33-16,16>>^ Eu perdoarei os pecados que cometeu. Ele viverá porque fez o que é bom e correto.

[[v26-33-17]]

^<<v26-33-17,17>>^ — No entanto, o seu povo diz que o que eu, o Senhor, faço não está certo! São eles que não estão certos!

[[v26-33-18]]

^<<v26-33-18,18>>^ Quando um homem correto para de fazer o bem e começa a fazer o mal, ele morrerá por causa disso.

[[v26-33-19]]

^<<v26-33-19,19>>^ Quando um homem mau para de pecar e faz o que é bom e correto, ele salvou a sua vida.

[[v26-33-20]]

^<<v26-33-20,20>>^ Mas você, povo de Israel, diz que o que eu faço não está certo. Eu os julgarei por aquilo que fazem.

[[v26-33-21]]

^<<v26-33-21,21>>^ No ano décimo segundo do nosso cativeiro , no dia cinco do décimo segundo mês , um homem que havia escapado de Jerusalém veio e me contou que a cidade tinha sido tomada.

[[v26-33-22]]

^<<v26-33-22,22>>^ Na noite antes da chegada dele, eu tinha sentido a presença poderosa de Deus, o Senhor . E na manhã seguinte, quando o homem chegou, o Senhor  me deu de novo a fala .

[[v26-33-23]]

^<<v26-33-23,23>>^ O Senhor  me disse o seguinte:

[[v26-33-24]]

^<<v26-33-24,24>>^ — Homem mortal , os moradores das cidades arrasadas na terra de Israel estão dizendo o seguinte: "Abraão era um homem só, e toda esta terra foi dada a ele. Nós somos muitos, e por isso agora a terra é nossa."

[[v26-33-25]]

^<<v26-33-25,25>>^ — Diga a essa gente o que eu, o Senhor  Deus, estou dizendo: "Vocês comem carne com sangue , adoram ídolos e cometem crimes de morte. Por que é que estão pensando que a terra é de vocês?

[[v26-33-26]]

^<<v26-33-26,26>>^ Vocês confiam nas suas espadas. O seu modo de agir é nojento. Todos cometem adultério. Por que estão pensando que a terra é de vocês?"

[[v26-33-27]]

^<<v26-33-27,27>>^ — Diga a essa gente que eu, o Senhor  Deus, estou avisando: Juro que os moradores das cidades arrasadas serão mortos. Os que vivem no campo serão comidos por animais selvagens. Os que estão escondidos nas montanhas e cavernas ficarão doentes e morrerão.

[[v26-33-28]]

^<<v26-33-28,28>>^ Farei com que o país vire um deserto abandonado. O poder de que se orgulhavam acabará. As montanhas de Israel ficarão tão desertas, que ninguém passará por elas.

[[v26-33-29]]

^<<v26-33-29,29>>^ Quando eu castigar o povo pelos seus pecados e fizer com que o país vire um deserto, aí eles ficarão sabendo que eu sou o Senhor .

[[v26-33-30]]

^<<v26-33-30,30>>^ O Senhor  disse: — Homem mortal , quando os seus irmãos israelitas conversam perto das muralhas da cidade ou na porta das suas casas, eles falam de você. Eles dizem: "Vamos saber o que o Senhor  tem para nos dizer agora."

[[v26-33-31]]

^<<v26-33-31,31>>^ Assim o meu povo se ajunta em grande número para ouvir o que você tem para dizer, mas eles não querem pôr em prática o que você diz. "Ele fala bonito" — eles dizem, mas o que querem é ganhar dinheiro.

[[v26-33-32]]

^<<v26-33-32,32>>^ Para eles você não passa de um cantor de canções de amor ou tocador de harpa . Eles ouvem o que você diz, porém não fazem nada daquilo que você manda.

[[v26-33-33]]

^<<v26-33-33,33>>^ Porém, quando acontecer tudo o que você diz — e vai acontecer mesmo —, aí eles ficarão sabendo que um profeta esteve no meio deles.

'''

xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[&#60; Capítulo Anterior] | <<v26-33-0,Topo>> | xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[Próximo Capítulo &#62;]