include::./index.adoc[]

[[v26-17-0]]
=== Ezequiel, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-17-1]]

^<<v26-17-1,1>>^ O Senhor  me disse o seguinte:

[[v26-17-2]]

^<<v26-17-2,2>>^ — Homem mortal , faça para os israelitas uma comparação

[[v26-17-3]]

^<<v26-17-3,3>>^ para que saibam o que eu, o Senhor  Deus, estou dizendo. Era uma vez uma águia gigantesca , de asas enormes, bem abertas, toda coberta de lindas penas. Ela voou para os montes Líbanos e quebrou a ponta de um cedro .

[[v26-17-4]]

^<<v26-17-4,4>>^ Ela levou essa ponta para uma terra de negociantes e a deixou numa cidade de vendedores .

[[v26-17-5]]

^<<v26-17-5,5>>^ Aí ela pegou na terra de Israel a muda de uma planta e a plantou numa terra boa, onde sempre havia água para fazê-la crescer.

[[v26-17-6]]

^<<v26-17-6,6>>^ A planta cresceu e se tornou uma parreira  baixa, mas esparramada. Os galhos se viraram para o lado da águia, e as raízes cresceram bem fundas. A parreira tinha galhos e estava coberta de folhas.

[[v26-17-7]]

^<<v26-17-7,7>>^ — Havia outra águia gigantesca , de asas enormes e muitas penas. A parreira virou as suas raízes e os seus galhos na direção da águia , esperando que ela lhe desse mais água do que havia no pomar onde estava plantada.

[[v26-17-8]]

^<<v26-17-8,8>>^ Mas a parreira tinha sido plantada em terra boa e bem-regada, para que fosse uma ótima planta, coberta de folhas, e que produzisse uvas.

[[v26-17-9]]

^<<v26-17-9,9>>^ — Agora, eu, o Senhor  Deus, pergunto: "Será que essa parreira vai crescer? Será que a primeira águia não vai arrancá-la pelas raízes, apanhar as uvas e quebrar os ramos, deixando-os secar? Não será necessária muita força nem uma nação poderosa para arrancá-la.

[[v26-17-10]]

^<<v26-17-10,10>>^ Sim! Ela está plantada, mas será que vai crescer? Será que não vai secar quando o vento leste a castigar? Será que não vai secar no pomar onde está plantada?"

[[v26-17-11]]

^<<v26-17-11,11>>^ E o Senhor  me disse:

[[v26-17-12]]

^<<v26-17-12,12>>^ — Pergunte a esses rebeldes se entenderam o que essa comparação quer dizer. Diga-lhes que o rei da Babilônia veio a Jerusalém, pegou o rei e os seus oficiais e os levou para a Babilônia.

[[v26-17-13]]

^<<v26-17-13,13>>^ Ele escolheu um homem da família do rei , fez um tratado com ele e o obrigou a jurar que lhe seria fiel. O rei da Babilônia também levou os homens importantes

[[v26-17-14]]

^<<v26-17-14,14>>^ para evitar que a nação se levantasse outra vez e para ter certeza de que o tratado seria cumprido.

[[v26-17-15]]

^<<v26-17-15,15>>^ Mas o rei de Judá se revoltou e enviou mensageiros ao Egito para conseguirem cavalos e um exército numeroso. Será que isso vai dar certo? E quem faz uma coisa dessas, será que vai escapar? Será que pode quebrar o tratado e escapar do castigo?

[[v26-17-16]]

^<<v26-17-16,16>>^ — Juro pela minha vida — diz o Senhor  Deus — que esse rei morrerá na Babilônia, pois quebrou o juramento e o tratado que havia feito com o rei da Babilônia, que o pôs no trono.

[[v26-17-17]]

^<<v26-17-17,17>>^ Nem o poderoso exército do rei do Egito seria capaz de ajudá-lo na guerra, quando os babilônios construírem rampas e torres de ataque a fim de matar muita gente.

[[v26-17-18]]

^<<v26-17-18,18>>^ Ele quebrou o juramento e o tratado que havia feito. E, porque fez todas essas coisas, não escapará.

[[v26-17-19]]

^<<v26-17-19,19>>^ O Senhor  Deus diz: — Juro pela minha vida que eu castigarei o rei por ter quebrado o tratado que pelo meu nome ele jurou guardar.

[[v26-17-20]]

^<<v26-17-20,20>>^ Estenderei uma rede de caçador e o pegarei nela. Eu o levarei à Babilônia e o castigarei ali, pois ele foi infiel a mim.

[[v26-17-21]]

^<<v26-17-21,21>>^ Os seus melhores soldados serão mortos em batalha, e os que ficarem vivos serão espalhados em todas as direções. Aí vocês ficarão sabendo que eu, o Senhor , falei.

[[v26-17-22]]

^<<v26-17-22,22>>^ O Senhor  Deus diz isto: "Tirarei a ponta de um cedro alto ; cortarei um broto novo e o plantarei num monte elevado,

[[v26-17-23]]

^<<v26-17-23,23>>^ no monte mais alto de Israel . Ele soltará galhos, produzirá sementes e se tornará um cedro muito lindo. Pássaros de todo tipo viverão ali e acharão abrigo na sua sombra.

[[v26-17-24]]

^<<v26-17-24,24>>^ Todas as árvores dos campos ficarão sabendo que eu sou o Senhor . Eu derrubo as árvores altas e faço as árvores pequenas crescerem. Eu seco as árvores verdes e faço com que as árvores secas fiquem verdes de novo. — Eu, o Senhor , falei; eu cumprirei o que prometi."

'''

xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[&#60; Capítulo Anterior] | <<v26-17-0,Topo>> | xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[Próximo Capítulo &#62;]