include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-28-1]]

^<<v26-28-1,1>>^ O Senhor  me disse o seguinte:

[[v26-28-2]]

^<<v26-28-2,2>>^ — Homem mortal , diga ao rei da cidade de Tiro que eu, o Senhor  Deus, digo isto a ele: "Cheio de orgulho, você diz que é um deus. E diz que, como deus, você está sentado num trono, cercado pelos mares. Você quer ser um deus, porém é mortal e não divino.

[[v26-28-3]]

^<<v26-28-3,3>>^ Você pensa que é mais sábio do que Danel , pensa que ninguém pode esconder de você nenhum segredo.

[[v26-28-4]]

^<<v26-28-4,4>>^ A sua sabedoria e a sua inteligência o enriqueceram com tesouros de ouro e prata.

[[v26-28-5]]

^<<v26-28-5,5>>^ Você fez bons negócios e continuou aumentando os lucros. E como você tem orgulho da sua riqueza!"

[[v26-28-6]]

^<<v26-28-6,6>>^ — Pois agora eu, o Senhor  Deus, digo isto: "Você pensa que é sábio como um deus,

[[v26-28-7]]

^<<v26-28-7,7>>^ e por isso eu farei com que estrangeiros muito cruéis o ataquem. Eles destruirão todas as riquezas que você conseguiu com a sua inteligência e sabedoria.

[[v26-28-8]]

^<<v26-28-8,8>>^ Eles o matarão e o mandarão para um túmulo de água.

[[v26-28-9]]

^<<v26-28-9,9>>^ Quando eles chegarem para matá-lo, será que você ainda vai dizer que é um deus? Quando enfrentar os seus assassinos, você será mortal e não divino.

[[v26-28-10]]

^<<v26-28-10,10>>^ Você morrerá como um cachorro, nas mãos de estrangeiros pagãos. Eu, o Senhor  Deus, dei esta ordem."

[[v26-28-11]]

^<<v26-28-11,11>>^ O Senhor  falou comigo outra vez. Ele disse:

[[v26-28-12]]

^<<v26-28-12,12>>^ — Homem mortal , cante uma canção de tristeza por causa do fim que o rei de Tiro vai ter. Diga-lhe que eu, o Senhor  Deus, digo isto: "Você era um exemplo de perfeição. Como era sábio e simpático!

[[v26-28-13]]

^<<v26-28-13,13>>^ Você vivia no Éden , o jardim de Deus, e usava pedras preciosas de todo tipo: rubis e diamantes; topázio , berilo , ônix e jaspe ; safiras , esmeraldas e granadas . Você tinha joias de ouro que foram feitas para você no dia em que foi criado.

[[v26-28-14]]

^<<v26-28-14,14>>^ Eu fiz de você um anjo protetor, com as asas abertas. Você vivia no meu monte santo e andava pelo meio de pedras brilhantes.

[[v26-28-15]]

^<<v26-28-15,15>>^ A sua conduta foi perfeita desde o dia em que foi criado, até que você começou a fazer o mal.

[[v26-28-16]]

^<<v26-28-16,16>>^ Você ficou ocupado, comprando e vendendo, e isso o levou à violência e ao pecado. Por isso, anjo protetor, eu o humilhei e expulsei do monte de Deus, do meio das pedras brilhantes.

[[v26-28-17]]

^<<v26-28-17,17>>^ Você ficou orgulhoso por causa da sua beleza, e a sua fama o fez perder o juízo. Então eu o joguei no chão a fim de servir de aviso para outros reis.

[[v26-28-18]]

^<<v26-28-18,18>>^ Você foi tão desonesto nas compras e vendas, que os seus lugares de culto foram profanados . Por isso, pus fogo na cidade e a queimei completamente. Todos os que agora olham para você estão vendo que você virou cinzas.

[[v26-28-19]]

^<<v26-28-19,19>>^ Você está acabado para sempre, e todas as nações que o conheceram estão apavoradas, com medo que aconteça a mesma coisa com elas."

[[v26-28-20]]

^<<v26-28-20,20>>^ O Senhor  me disse:

[[v26-28-21]]

^<<v26-28-21,21>>^ — Homem mortal , fale contra a cidade de Sidom.

[[v26-28-22]]

^<<v26-28-22,22>>^ Diga ao povo dali que eu, o Senhor  Deus, digo o seguinte: "Sidom, eu estou contra você. Por causa daquilo que vou fazer com você, todos me louvarão. Quando eu castigar os seus moradores, todos ficarão sabendo que eu sou o Senhor  e que sou santo.

[[v26-28-23]]

^<<v26-28-23,23>>^ Eu lhe mandarei doenças e farei com que corra sangue nas suas ruas. Você será atacada de todos os lados, e todos os seus moradores serão mortos. Assim você ficará sabendo que eu sou o Senhor ."

[[v26-28-24]]

^<<v26-28-24,24>>^ O Senhor  disse: — Os povos vizinhos que trataram Israel com desprezo nunca mais o ferirão, como se eles fossem espinhos e roseiras bravas. E eles ficarão sabendo que eu sou o Senhor  Deus.

[[v26-28-25]]

^<<v26-28-25,25>>^ O Senhor  Deus disse: — Eu vou trazer de volta o povo de Israel de todos os países por onde os espalhei, e todas as nações ficarão sabendo que eu sou santo. O povo de Israel viverá na sua própria terra, a terra que dei a Jacó, meu servo .

[[v26-28-26]]

^<<v26-28-26,26>>^ Ali eles vão viver em segurança, vão construir casas e fazer plantações de uvas. Eu castigarei todos os seus vizinhos que os trataram com desprezo, e Israel ficará seguro. Aí eles ficarão sabendo que eu sou o Senhor , o Deus de Israel.

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]