include::./index.adoc[]

[[v26-27-0]]
=== Ezequiel, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-27-1]]

^<<v26-27-1,1>>^ O Senhor  me disse o seguinte:

[[v26-27-2]]

^<<v26-27-2,2>>^ — Homem mortal , cante um cântico fúnebre para Tiro,

[[v26-27-3]]

^<<v26-27-3,3>>^ aquela cidade que fica à beira do mar e faz comércio com todos os povos que vivem no litoral. Diga que o Senhor  Deus está dizendo isto: "Tiro, você se orgulhava da sua beleza perfeita.

[[v26-27-4]]

^<<v26-27-4,4>>^ O mar é o seu lar. Os seus construtores a fizeram parecida com um belo navio.

[[v26-27-5]]

^<<v26-27-5,5>>^ Na construção, usaram pinho do monte Hermom e para o mastro usaram um cedro do Líbano.

[[v26-27-6]]

^<<v26-27-6,6>>^ Pegaram carvalho de Basã para fazer os remos. Fizeram o seu convés de pinho de Chipre e o enfeitaram com marfim.

[[v26-27-7]]

^<<v26-27-7,7>>^ As suas velas eram de linho bordado do Egito, velas reconhecidas de longe. Os seus toldos eram de tecido fino, de púrpura  da ilha de Chipre.

[[v26-27-8]]

^<<v26-27-8,8>>^ Ó Tiro, os seus marinheiros eram os seus próprios homens experientes, e os seus remadores eram das cidades de Sidom e de Arvade.

[[v26-27-9]]

^<<v26-27-9,9>>^ Os carpinteiros do navio eram homens de Biblos, bem-preparados. Marinheiros de todos os navios do mar faziam negócios nas suas lojas."

[[v26-27-10]]

^<<v26-27-10,10>>^ — Soldados da Pérsia, Lídia e Líbia serviam no seu exército. Eles penduravam os seus escudos  e capacetes nas suas barracas. Eles conquistaram a glória  para você.

[[v26-27-11]]

^<<v26-27-11,11>>^ Soldados de Arvade ficavam de guarda nas suas muralhas, e homens de Gamade guardavam as suas torres. Eles penduravam os escudos nas suas paredes. Foram estes que fizeram com que você ficasse bonita.

[[v26-27-12]]

^<<v26-27-12,12>>^ — Você fazia negócios na Espanha e em troca das suas muitas mercadorias você recebia prata, ferro, estanho e chumbo.

[[v26-27-13]]

^<<v26-27-13,13>>^ Você fazia negócios na Grécia, Tubal e Meseque e trocava as suas mercadorias por escravos e objetos de bronze.

[[v26-27-14]]

^<<v26-27-14,14>>^ Você trocava as suas mercadorias por cavalos comuns, por cavalos de guerra e por mulas de Bete-Togarma.

[[v26-27-15]]

^<<v26-27-15,15>>^ A gente de Rodes negociava com você. Em troca dos seus artigos, moradores de muitas terras do litoral davam a você marfim e madeira de ébano.

[[v26-27-16]]

^<<v26-27-16,16>>^ O povo da Síria comprava os seus muitos produtos e as suas mercadorias. Em troca das suas mercadorias, eles davam esmeraldas, tecidos de púrpura, bordados, linho fino, corais e rubis.

[[v26-27-17]]

^<<v26-27-17,17>>^ Judá e Israel pagavam as suas mercadorias com trigo de Minite, mel, azeite e especiarias .

[[v26-27-18]]

^<<v26-27-18,18>>^ Damasco negociava com você e em troca dos seus muitos produtos dava vinho de Helbom e lã de Saar.

[[v26-27-19]]

^<<v26-27-19,19>>^ De Uzal traziam para você vinho, ferro trabalhado e especiarias, que trocavam pelos seus artigos.

[[v26-27-20]]

^<<v26-27-20,20>>^ Em troca dos seus produtos, o povo de Dedã oferecia mantas para cavalo.

[[v26-27-21]]

^<<v26-27-21,21>>^ Os árabes e as autoridades de Quedar pagavam as suas mercadorias com carneirinhos, carneiros e bodes.

[[v26-27-22]]

^<<v26-27-22,22>>^ Em troca das suas mercadorias, os negociantes de Sabá e Ramá davam as mais finas especiarias, pedras preciosas e ouro.

[[v26-27-23]]

^<<v26-27-23,23>>^ As cidades de Harã, Cane e Éden, os comerciantes de Sabá, as cidades de Assur e Quilmade — todos faziam negócios com você.

[[v26-27-24]]

^<<v26-27-24,24>>^ Eles lhe vendiam roupas de luxo, tecidos de púrpura, bordados, tapetes de várias cores e cordas e cordões bem-trançados.

[[v26-27-25]]

^<<v26-27-25,25>>^ As suas mercadorias eram levadas em grupos de grandes navios cargueiros. "Tiro, você parecia um navio no mar, carregado com carga pesada.

[[v26-27-26]]

^<<v26-27-26,26>>^ Quando os seus remadores levaram você para o mar alto, o vento leste a fez afundar longe de terra.

[[v26-27-27]]

^<<v26-27-27,27>>^ Toda a riqueza da sua mercadoria, todos os marinheiros da tripulação, os carpinteiros do navio e os seus comerciantes, cada soldado que estava no navio — todos, todos se perderam no mar quando o navio afundou.

[[v26-27-28]]

^<<v26-27-28,28>>^ Os gritos dos marinheiros que se afogavam foram ouvidos até na praia.

[[v26-27-29]]

^<<v26-27-29,29>>^ Todos os navios estão agora abandonados, e todos os marinheiros foram para terra firme.

[[v26-27-30]]

^<<v26-27-30,30>>^ Todos eles choram amargamente por você, jogando pó na cabeça e rolando nas cinzas em sinal de tristeza.

[[v26-27-31]]

^<<v26-27-31,31>>^ Por sua causa, eles rapam a cabeça e vestem roupa feita de pano grosseiro, chorando com o coração amargurado.

[[v26-27-32]]

^<<v26-27-32,32>>^ Eles cantam para você esta canção triste: ‘Quem pode se comparar com Tiro, que agora está em silêncio no meio do mar?

[[v26-27-33]]

^<<v26-27-33,33>>^ Quando as suas mercadorias eram carregadas através dos mares, você satisfazia a muitas nações. Com a riqueza dos seus bens, você enriqueceu os reis da terra.

[[v26-27-34]]

^<<v26-27-34,34>>^ Agora, você está no fundo do mar, está afundada nas profundezas do oceano. Os seus bens e todos aqueles que trabalhavam para você desapareceram junto com você no mar.’ "

[[v26-27-35]]

^<<v26-27-35,35>>^ — Todos os moradores do litoral estão apavorados com o que lhe aconteceu. Até os reis estão apavorados, e o medo está escrito na cara deles.

[[v26-27-36]]

^<<v26-27-36,36>>^ Você se acabou para sempre, e os comerciantes no mundo inteiro estão apavorados, com medo que aconteça com eles o mesmo que aconteceu com você.

'''

xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]