include::./index.adoc[]

[[v26-14-0]]
=== Ezequiel, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-14-1]]

^<<v26-14-1,1>>^ Alguns líderes israelitas vieram me perguntar qual era a vontade do Senhor .

[[v26-14-2]]

^<<v26-14-2,2>>^ Então o Senhor  me disse o seguinte:

[[v26-14-3]]

^<<v26-14-3,3>>^ — Homem mortal , esses homens deram o seu coração aos ídolos e estão deixando que os ídolos os façam pecar. Será que pensam que vou lhes dar alguma resposta?

[[v26-14-4]]

^<<v26-14-4,4>>^ — Pois bem, diga aquilo que eu, o Senhor  Deus, estou lhes dizendo: "Todo israelita que sente no coração a vontade de adorar ídolos, que está permitindo que eles o façam pecar e que vai consultar um profeta  receberá a minha resposta. E será a resposta que os seus muitos ídolos merecem.

[[v26-14-5]]

^<<v26-14-5,5>>^ Todos esses ídolos desviaram o meu povo de mim, porém com a minha resposta espero que ele volte a ser fiel a mim como antes."

[[v26-14-6]]

^<<v26-14-6,6>>^ — Por isso, diga aos israelitas que eu, o Senhor  Deus, estou dizendo o seguinte: "Arrependam-se e abandonem os seus ídolos nojentos."

[[v26-14-7]]

^<<v26-14-7,7>>^ — Quando um israelita ou um estrangeiro que mora em Israel se afastar de mim, e for tentado a adorar ídolos e deixar que eles o façam pecar, e então for consultar um profeta — eu, o Senhor , é que lhe darei a resposta!

[[v26-14-8]]

^<<v26-14-8,8>>^ Eu ficarei contra essa pessoa e farei dela um exemplo. Eu a arrancarei do meio do meu povo, e assim todos ficarão sabendo que eu sou o Senhor .

[[v26-14-9]]

^<<v26-14-9,9>>^ — Se um profeta for enganado e der uma resposta falsa, fui eu, o Senhor , quem o enganou. Eu o tirarei do meio do povo de Israel.

[[v26-14-10]]

^<<v26-14-10,10>>^ Tanto o profeta como aquele que o consultar receberão o mesmo castigo.

[[v26-14-11]]

^<<v26-14-11,11>>^ Farei isso para evitar que os israelitas me abandonem e se manchem com os seus pecados. Eles serão o meu povo, e eu serei o Deus deles. Eu, o Senhor  Deus, falei.

[[v26-14-12]]

^<<v26-14-12,12>>^ O Senhor  me disse o seguinte:

[[v26-14-13]]

^<<v26-14-13,13>>^ — Homem mortal , se uma nação pecar e for infiel a mim, eu levantarei a mão contra ela e destruirei os seus depósitos de alimentos. Farei com que haja fome para matar gente e animais.

[[v26-14-14]]

^<<v26-14-14,14>>^ Mesmo que Noé, Danel e Jó estivessem vivendo ali, a honestidade desses três homens salvaria apenas a vida deles. Eu, o Senhor  Deus, falei.

[[v26-14-15]]

^<<v26-14-15,15>>^ — Se eu mandar animais ferozes para matar as pessoas, e por causa deles a terra ficar tão perigosa, que ninguém possa viajar nela,

[[v26-14-16]]

^<<v26-14-16,16>>^ mesmo que esses três homens estivessem vivendo ali — juro pela minha vida, diz o Senhor  Deus — eles não seriam capazes de salvar nem os seus próprios filhos. Eles salvariam somente a sua própria vida, e a terra viraria um deserto.

[[v26-14-17]]

^<<v26-14-17,17>>^ — Se eu mandar a esse país guerra e armas destruidoras para acabar com pessoas e animais,

[[v26-14-18]]

^<<v26-14-18,18>>^ mesmo que esses três homens estivessem vivendo ali — juro pela minha vida, diz o Senhor  Deus — eles não seriam capazes de salvar nem os seus próprios filhos, mas apenas a sua própria vida.

[[v26-14-19]]

^<<v26-14-19,19>>^ — Se eu mandar uma epidemia a esse país e derramar a minha ira  sobre a terra para tirar muitas vidas, matando gente e animais,

[[v26-14-20]]

^<<v26-14-20,20>>^ mesmo que Noé, Danel e Jó estivessem vivendo ali — juro pela minha vida, diz o Senhor  Deus — eles não seriam capazes de salvar nem os seus próprios filhos. A honestidade deles salvaria apenas a sua própria vida.

[[v26-14-21]]

^<<v26-14-21,21>>^ O Senhor  Deus diz o seguinte: — Vou mandar a Jerusalém os meus quatro castigos mais violentos, isto é, guerra, fome, animais ferozes e doenças, para destruir pessoas e animais.

[[v26-14-22]]

^<<v26-14-22,22>>^ Se alguns escaparem e salvarem os seus filhos, olhem bem para eles quando chegarem. Vocês verão como eles são maus e se convencerão de que o castigo que estou dando a Jerusalém é merecido.

[[v26-14-23]]

^<<v26-14-23,23>>^ Quando virem como eles são maus, vocês se convencerão e ficarão sabendo que houve motivo justo para tudo o que fiz. Eu, o Senhor  Deus, falei.

'''

xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]