include::./index.adoc[]

[[v26-26-0]]
=== Ezequiel, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-26-1]]

^<<v26-26-1,1>>^ No ano décimo primeiro do nosso cativeiro , no primeiro dia do mês, o Senhor  falou comigo de novo. Ele disse:

[[v26-26-2]]

^<<v26-26-2,2>>^ — Homem mortal , o povo da cidade de Tiro está se alegrando por causa de uma coisa. Eles estão gritando: "Jerusalém, a nossa rival no comércio, está arrasada! As suas portas se abriram para nós entrarmos, e com a sua derrota nós vamos enriquecer!"

[[v26-26-3]]

^<<v26-26-3,3>>^ — Agora, o que eu, o Senhor  Deus, estou dizendo é isto: Cidade de Tiro, eu estou contra você. Vou trazer muitas nações para lutarem contra você, e elas virão como as ondas do mar.

[[v26-26-4]]

^<<v26-26-4,4>>^ Elas destruirão as muralhas da sua cidade e derrubarão as suas torres. Aí eu varrerei o pó e deixarei a rocha nua.

[[v26-26-5]]

^<<v26-26-5,5>>^ Os pescadores estenderão as redes para secarem em cima dela, ali no mar , onde se encontra. Sou eu, o Senhor  Deus, quem está falando. As nações vão atacar e roubar Tiro

[[v26-26-6]]

^<<v26-26-6,6>>^ e com as suas espadas vão matar aqueles que vivem nas cidades que estão perto, em terra firme. Aí a cidade de Tiro ficará sabendo que eu sou o Senhor .

[[v26-26-7]]

^<<v26-26-7,7>>^ O Senhor  Deus diz: — Eu vou trazer da Babilônia o rei Nabucodonosor, o mais poderoso de todos os reis, para atacar Tiro. Ele virá do Norte com um forte exército, com cavalos e carros de guerra e com cavalaria.

[[v26-26-8]]

^<<v26-26-8,8>>^ Aqueles que vivem perto, nas cidades que estão em terra firme, serão mortos na batalha. O inimigo cavará trincheiras, fará rampas de ataque e levantará um muro de escudos  contra você.

[[v26-26-9]]

^<<v26-26-9,9>>^ Com máquinas de lançar pedras, eles derrubarão as suas muralhas e com barras de ferro derrubarão as suas torres.

[[v26-26-10]]

^<<v26-26-10,10>>^ Os seus cavalos levantarão nuvens de pó que cobrirão vocês. Quando eles passarem pelos portões da cidade conquistada, o barulho dos cavalos deles puxando carretas e carros de guerra fará tremer as suas muralhas.

[[v26-26-11]]

^<<v26-26-11,11>>^ Os cavaleiros deles invadirão as suas ruas, matando o seu povo à espada. As suas fortes colunas serão jogadas no chão.

[[v26-26-12]]

^<<v26-26-12,12>>^ Os seus inimigos roubarão as suas riquezas e as suas mercadorias. Derrubarão as suas muralhas e arrasarão as suas casas luxuosas. Eles jogarão no mar as pedras, a madeira e o entulho.

[[v26-26-13]]

^<<v26-26-13,13>>^ Acabarei com as suas canções e farei parar a música das suas liras .

[[v26-26-14]]

^<<v26-26-14,14>>^ De você só deixarei uma rocha nua, onde os pescadores estenderão as redes para secarem. A cidade nunca mais será reconstruída. Eu, o Senhor  Deus, estou falando.

[[v26-26-15]]

^<<v26-26-15,15>>^ O Senhor  Deus diz isto à cidade de Tiro: — Quando você for conquistada, o povo que vive no litoral ficará apavorado com os gritos daqueles que forem feridos de morte.

[[v26-26-16]]

^<<v26-26-16,16>>^ Todos os reis das nações do litoral descerão dos seus tronos. Tirarão os seus mantos  e as suas roupas bordadas e, tremendo de medo, sentarão no chão. Quando virem o que aconteceu com você, eles terão tanto pavor, que ficarão tremendo sem parar.

[[v26-26-17]]

^<<v26-26-17,17>>^ Eles cantarão para você este cântico fúnebre: "A cidade famosa está destruída! Os seus navios foram varridos dos mares. O povo desta cidade dominava os mares e metia medo em todos os que viviam no litoral.

[[v26-26-18]]

^<<v26-26-18,18>>^ Agora, no dia em que a cidade caiu, as ilhas estão tremendo, e os seus moradores estão apavorados com tanta destruição."

[[v26-26-19]]

^<<v26-26-19,19>>^ O Senhor  Deus diz: — Farei você virar uma cidade deserta como as cidades arrasadas, onde não mora ninguém. Cobrirei você com as águas profundas do mar.

[[v26-26-20]]

^<<v26-26-20,20>>^ Eu a jogarei no mundo dos mortos , onde você estará com gente que morreu há muito tempo. E a abandonarei nesse mundo que fica debaixo da terra, nesse país de ruínas antigas, e você ficará junto com os mortos. Em você, Tiro, nunca mais morará ninguém, e você não voltará a ocupar o seu lugar no mundo dos vivos.

[[v26-26-21]]

^<<v26-26-21,21>>^ Farei de você um exemplo horrível, e esse será o seu fim. As pessoas vão procurá-la, mas ninguém a encontrará. Eu, o Senhor  Deus, falei.

'''

xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]