include::./index.adoc[]

[[v26-8-0]]
=== Ezequiel, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-8-1]]

^<<v26-8-1,1>>^ Um dia, os líderes do povo de Judá estavam me visitando em casa. Fazia exatamente seis anos, seis meses e cinco dias que eles tinham sido levados como prisioneiros. De repente, o poder do Senhor  Deus veio sobre mim.

[[v26-8-2]]

^<<v26-8-2,2>>^ Olhei e tive uma visão: nela, vi um ser que parecia feito de fogo. Da cintura para baixo, o seu corpo parecia fogo e da cintura para cima brilhava como bronze polido.

[[v26-8-3]]

^<<v26-8-3,3>>^ Ele estendeu o que parecia uma mão e me agarrou pelos cabelos. E nessa visão o Espírito de Deus me levantou bem alto no ar e me levou a Jerusalém. Ele me levou até a parte de dentro do portão norte do Templo, onde havia um ídolo que era uma ofensa contra Deus.

[[v26-8-4]]

^<<v26-8-4,4>>^ Ali, eu vi a glória  do Deus de Israel, como eu tinha visto na minha visão perto do rio Quebar.

[[v26-8-5]]

^<<v26-8-5,5>>^ Deus me disse: — Homem mortal , olhe para o norte. Olhei e ali, perto do altar, na entrada do portão, vi o ídolo que era uma ofensa contra Deus.

[[v26-8-6]]

^<<v26-8-6,6>>^ E Deus me disse: — Homem mortal, você vê o que está acontecendo? Olhe para as coisas nojentas que o povo de Israel está fazendo aqui para me afastar cada vez mais do meu lugar santo. Você verá coisas ainda mais vergonhosas do que essas.

[[v26-8-7]]

^<<v26-8-7,7>>^ Ele me levou até a entrada do pátio de fora e me mostrou um buraco na parede.

[[v26-8-8]]

^<<v26-8-8,8>>^ E disse: — Homem mortal, arrebente esta parede. Arrebentei a parede e encontrei uma porta.

[[v26-8-9]]

^<<v26-8-9,9>>^ Então ele me disse: — Entre e veja as coisas imorais e vergonhosas que estão fazendo aí dentro.

[[v26-8-10]]

^<<v26-8-10,10>>^ Entrei e olhei. As paredes estavam cobertas com desenhos de cobras e outros animais impuros  e de outras coisas que os israelitas estavam adorando.

[[v26-8-11]]

^<<v26-8-11,11>>^ Setenta líderes israelitas se achavam ali, e entre eles estava Jazanias, filho de Safã. Cada um segurava um queimador de incenso, do qual saía fumaça.

[[v26-8-12]]

^<<v26-8-12,12>>^ Aí Deus me perguntou: — Homem mortal, você está vendo o que os líderes israelitas estão fazendo em segredo? Estão prestando culto em um salão cheio de imagens. A desculpa deles é esta: "O Senhor  Deus não está vendo. Ele abandonou o país."

[[v26-8-13]]

^<<v26-8-13,13>>^ Depois, Deus me disse o seguinte: — Você verá esses líderes fazendo coisas ainda mais vergonhosas do que isso.

[[v26-8-14]]

^<<v26-8-14,14>>^ Aí ele me levou até o portão norte do Templo e me mostrou mulheres chorando a morte do deus Tamuz .

[[v26-8-15]]

^<<v26-8-15,15>>^ O Senhor  Deus perguntou: — Homem mortal, você está vendo isso? Pois verá coisas ainda mais vergonhosas.

[[v26-8-16]]

^<<v26-8-16,16>>^ Depois, ele me levou para o pátio interno do Templo. Ali, perto da entrada do Templo, entre o altar e o corredor, havia uns vinte e cinco homens. Estavam de costas para o Templo, virados para o leste, e se curvavam até ao chão, adorando o sol nascente.

[[v26-8-17]]

^<<v26-8-17,17>>^ Então o Senhor  me disse: — Homem mortal, você está vendo isso? Essa gente de Judá faz todas as coisas vergonhosas que você viu aqui e ainda não fica satisfeita. Por causa deles há violência por toda parte, no país inteiro. Além disso, eles vêm e fazem essas coisas aqui no Templo e assim me irritam mais ainda. Veja só como me insultam da pior maneira possível!

[[v26-8-18]]

^<<v26-8-18,18>>^ Por causa disso, eles sentirão toda a força da minha ira . Não deixarei ninguém escapar e não terei pena de ninguém. Eles gritarão com toda a força, pedindo a minha ajuda, mas eu não os atenderei.

'''

xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]