include::./index.adoc[]

[[v26-45-0]]
=== Ezequiel, 45
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-45-1]]

^<<v26-45-1,1>>^ Quando a terra for dividida entre as tribos , uma parte deverá ser separada para Deus, o Senhor . Essa parte medirá doze quilômetros e meio por dez quilômetros e será santa.

[[v26-45-2]]

^<<v26-45-2,2>>^ Nessa área, será reservado para o Templo um terreno quadrado, de duzentos e cinquenta metros de cada lado. Em volta desse terreno haverá um espaço livre de vinte e cinco metros de largura.

[[v26-45-3]]

^<<v26-45-3,3>>^ Da área total será separado um terreno de doze quilômetros e meio de comprimento por cinco de largura. Ali ficará o Templo, que é o lugar mais sagrado de todos.

[[v26-45-4]]

^<<v26-45-4,4>>^ Esta será a parte santa da terra de Israel, separada para os sacerdotes que servem o Senhor  no seu Templo. Ali eles terão as suas casas, e ali ficará a área sagrada do Templo.

[[v26-45-5]]

^<<v26-45-5,5>>^ Além disso, haverá outro terreno de doze quilômetros e meio de comprimento por cinco de largura, separado para ser propriedade dos levitas , que fazem o serviço no Templo. Ali haverá cidades para eles morarem.

[[v26-45-6]]

^<<v26-45-6,6>>^ Ao lado da área santa haverá outra área de doze quilômetros e meio por dois e meio, separada para ser uma cidade em que qualquer israelita poderá morar.

[[v26-45-7]]

^<<v26-45-7,7>>^ Uma parte da terra de Israel será do rei. Partindo da área santa e dos terrenos da cidade, a parte do rei irá na direção oeste até o mar Mediterrâneo, e a leste até a divisa oriental. De leste a oeste, terá o mesmo comprimento de uma das áreas das tribos  de Israel.

[[v26-45-8]]

^<<v26-45-8,8>>^ Esta será a parte que o rei terá na terra de Israel; assim ele nunca mais explorará o povo, porém deixará que o resto do país pertença às tribos de Israel.

[[v26-45-9]]

^<<v26-45-9,9>>^ O Senhor  Deus diz: — Autoridades de Israel, parem de pecar! Deixem a violência! Deixem de explorar o povo! Façam o que é direito e justo! Nunca mais expulsem o meu povo da terra deles! Sou eu, o Senhor  Deus, quem está dizendo isso.

[[v26-45-10]]

^<<v26-45-10,10>>^ — Todos devem usar medidas e pesos certos.

[[v26-45-11]]

^<<v26-45-11,11>>^ — O efa, para medir cereais, deverá ser igual ao bato, que mede líquidos. O padrão é o ômer . Um ômer será igual a dez efas ou dez batos.

[[v26-45-12]]

^<<v26-45-12,12>>^ — O peso de um siclo será igual ao de vinte geras. Uma mina será igual a sessenta siclos.

[[v26-45-13]]

^<<v26-45-13,13>>^ — As suas ofertas deverão ser feitas nas seguintes bases: do trigo que vocês colherem, entreguem uma parte em sessenta; da cevada , a mesma coisa; do azeite, uma parte em cem do que as suas árvores produzirem. Usem o bato como medida. Dez batos são iguais a um ômer ou a um coro.

[[v26-45-14]]

^<<v26-45-14,14>>^ — As suas ofertas deverão ser feitas nas seguintes bases: do trigo que vocês colherem, entreguem uma parte em sessenta; da cevada , a mesma coisa; do azeite, uma parte em cem do que as suas árvores produzirem. Usem o bato como medida. Dez batos são iguais a um ômer ou a um coro.

[[v26-45-15]]

^<<v26-45-15,15>>^ Das ovelhas dos pastos de Israel, entreguem uma de cada duzentas. — Vocês trarão as ofertas de cereais, os animais para serem completamente queimados e os animais para as ofertas de paz a fim de que assim os pecados de vocês sejam perdoados. Eu, o Senhor  Deus, ordeno isso.

[[v26-45-16]]

^<<v26-45-16,16>>^ — Todo o povo do país deverá levar essas ofertas ao rei de Israel.

[[v26-45-17]]

^<<v26-45-17,17>>^ Em favor de toda a nação de Israel, o rei terá o dever de apresentar os animais que serão completamente queimados, as ofertas de cereais e as ofertas de vinho. Ele fará isso nas Festas da Lua Nova , nos sábados e em todas as outras festas. O rei apresentará as ofertas para tirar pecados, as ofertas de cereais, as ofertas a serem completamente queimadas e as ofertas de paz para que os pecados do povo de Israel sejam perdoados.

[[v26-45-18]]

^<<v26-45-18,18>>^ O Senhor  Deus disse: — No primeiro dia do primeiro mês, vocês oferecerão como sacrifício  um touro sem nenhum defeito e purificarão  o Templo.

[[v26-45-19]]

^<<v26-45-19,19>>^ O sacerdote pegará uma parte do sangue do animal apresentado como oferta para tirar pecados e porá esse sangue nos batentes da porta do Templo, nas quatro pontas do altar e nos batentes dos portões do pátio de dentro.

[[v26-45-20]]

^<<v26-45-20,20>>^ No sétimo dia do mês, ele fará a mesma coisa em favor de qualquer pessoa que tenha cometido algum pecado sem intenção ou por ignorância. Assim vocês conservarão santo o Templo.

[[v26-45-21]]

^<<v26-45-21,21>>^ — No dia catorze do primeiro mês, vocês começarão a comemorar a Festa da Páscoa . Durante sete dias, todos comerão pão sem fermento .

[[v26-45-22]]

^<<v26-45-22,22>>^ No primeiro dia da Festa, o rei oferecerá um touro como sacrifício para tirar os seus pecados e os pecados do povo.

[[v26-45-23]]

^<<v26-45-23,23>>^ Em cada um dos sete dias da Festa, ele oferecerá como sacrifício ao Senhor  Deus sete touros e sete carneiros sem defeito e os queimará completamente. E todos os dias também oferecerá como sacrifício um bode como oferta para tirar pecados.

[[v26-45-24]]

^<<v26-45-24,24>>^ Para cada touro e cada carneiro que for oferecido em sacrifício, haverá uma oferta de dezessete litros e meio de cereais e três litros de azeite.

'''

xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[&#60; Capítulo Anterior] | <<v26-45-0,Topo>> | xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[Próximo Capítulo &#62;]