include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-22-1]]

^<<v26-22-1,1>>^ O Senhor  me disse o seguinte:

[[v26-22-2]]

^<<v26-22-2,2>>^ — Homem mortal , você está pronto para julgar a cidade que está cheia de assassinos? Mostre a ela todas as coisas vergonhosas que tem feito.

[[v26-22-3]]

^<<v26-22-3,3>>^ Conte a ela aquilo que eu, o Senhor  Deus, estou dizendo: "Você, cidade assassina, matou muitas pessoas do seu próprio povo e se tornou impura  fazendo ídolos e os adorando, e por isso o tempo do seu castigo está cada vez mais perto.

[[v26-22-4]]

^<<v26-22-4,4>>^ Você é culpada dessas mortes e se tornou impura por causa dos ídolos que fabricou, e por isso o seu dia está chegando, o seu tempo acabou. Foi por isso que deixei as outras nações caçoarem e zombarem de você.

[[v26-22-5]]

^<<v26-22-5,5>>^ Países de perto e de longe caçoam de você por ter fama de cidade de desordeiros.

[[v26-22-6]]

^<<v26-22-6,6>>^ Todas as autoridades de Israel confiam na sua própria força e cometem assassinatos.

[[v26-22-7]]

^<<v26-22-7,7>>^ Na cidade, ninguém honra o pai nem a mãe. Vocês maltratam os estrangeiros que moram no meio de vocês e exploram viúvas e órfãos.

[[v26-22-8]]

^<<v26-22-8,8>>^ Vocês não respeitam os lugares sagrados, nem guardam o sábado.

[[v26-22-9]]

^<<v26-22-9,9>>^ Uns dizem mentiras a respeito dos outros, que por causa disso são mortos. Alguns comem sacrifícios  oferecidos aos ídolos. Outros estão sempre satisfazendo as suas paixões.

[[v26-22-10]]

^<<v26-22-10,10>>^ Outros têm relações sexuais com a mulher do seu próprio pai. Outros ainda obrigam mulheres que estão menstruadas a terem relações com eles.

[[v26-22-11]]

^<<v26-22-11,11>>^ Cometem adultério e seduzem as suas noras ou as suas meias-irmãs.

[[v26-22-12]]

^<<v26-22-12,12>>^ Alguns dos seus moradores matam por dinheiro. Outros emprestam dinheiro a juros e ficam ricos explorando os seus próprios irmãos israelitas. Eles esqueceram de mim. Sou eu, o Senhor  Deus, quem está falando.

[[v26-22-13]]

^<<v26-22-13,13>>^ — "Vou acabar com as suas roubalheiras e com os seus crimes de morte.

[[v26-22-14]]

^<<v26-22-14,14>>^ Vocês pensam que ainda terão alguma coragem ou força bastante para levantar a mão quando eu acabar de agir contra vocês? Eu, o Senhor , estou falando e mantenho a minha palavra.

[[v26-22-15]]

^<<v26-22-15,15>>^ Espalharei o seu povo por todos os países e nações e porei um fim em todas as suas más ações.

[[v26-22-16]]

^<<v26-22-16,16>>^ Assim as outras nações olharão com nojo para vocês, e vocês saberão que eu sou o Senhor ."

[[v26-22-17]]

^<<v26-22-17,17>>^ O Senhor  me disse o seguinte:

[[v26-22-18]]

^<<v26-22-18,18>>^ — Homem mortal , os israelitas não têm valor para mim. Eles são como a mistura de cobre, estanho, ferro e chumbo que sobra depois que a prata é refinada na fornalha.

[[v26-22-19]]

^<<v26-22-19,19>>^ Agora, eu, o Senhor  Deus, estou lhes dizendo que eles são tão inúteis como essa mistura. Reunirei todos em Jerusalém,

[[v26-22-20]]

^<<v26-22-20,20>>^ como se fossem minério de prata, cobre, ferro, chumbo e estanho jogados numa fornalha de refinação. A minha ira  e o meu furor os derreterão assim como o fogo derrete o minério.

[[v26-22-21]]

^<<v26-22-21,21>>^ Sim! Eu os ajuntarei em Jerusalém, porei fogo debaixo deles e os derreterei com a minha ira.

[[v26-22-22]]

^<<v26-22-22,22>>^ Eles se derreterão em Jerusalém assim como a prata é derretida na fornalha e aí ficarão sabendo que eu, o Senhor , derramei sobre eles a minha ira.

[[v26-22-23]]

^<<v26-22-23,23>>^ O Senhor  falou comigo de novo. Ele disse:

[[v26-22-24]]

^<<v26-22-24,24>>^ — Homem mortal , diga aos israelitas que a terra deles é impura  e que eu os estou castigando por causa da minha ira .

[[v26-22-25]]

^<<v26-22-25,25>>^ As suas autoridades são como leões rugindo em cima dos animais que mataram. Matam as pessoas, tiram as suas propriedades e as suas riquezas e, por causa dos seus crimes de morte, deixam viúvas muitas mulheres.

[[v26-22-26]]

^<<v26-22-26,26>>^ Os sacerdotes desobedecem à minha Lei  e não têm respeito por aquilo que é santo. Não fazem diferença entre o que é santo e o que não é. Não ensinam a diferença entre as coisas puras e as impuras  e não respeitam o sábado. Como resultado disso, o povo de Israel não me respeita.

[[v26-22-27]]

^<<v26-22-27,27>>^ As autoridades são como lobos que despedaçam os animais que mataram. Matam para enriquecer.

[[v26-22-28]]

^<<v26-22-28,28>>^ Os profetas  escondem esses pecados como quem pinta de branco uma parede. Eles têm visões falsas e fazem falsas profecias . Afirmam que falam a palavra do Senhor  Deus, mas eu, o Senhor , não falei com eles.

[[v26-22-29]]

^<<v26-22-29,29>>^ Os ricos enganam e roubam. Eles maltratam os pobres e exploram estrangeiros.

[[v26-22-30]]

^<<v26-22-30,30>>^ — Procurei alguém que construísse uma muralha, alguém que ficasse nos lugares onde as muralhas desmoronaram e que defendesse a terra a fim de que a minha ira não a destruísse; porém não encontrei ninguém.

[[v26-22-31]]

^<<v26-22-31,31>>^ Por isso, farei cair o fogo da minha ira sobre eles e os destruirei como castigo pelo que eles têm feito. Eu, o Senhor  Deus, falei.

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]