include::./index.adoc[]

[[v26-23-0]]
=== Ezequiel, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-23-1]]

^<<v26-23-1,1>>^ O Senhor  me disse o seguinte:

[[v26-23-2]]

^<<v26-23-2,2>>^ — Homem mortal , era uma vez duas irmãs

[[v26-23-3]]

^<<v26-23-3,3>>^ que moravam no Egito. Quando eram jovens, elas perderam a virgindade e se tornaram prostitutas.

[[v26-23-4]]

^<<v26-23-4,4>>^ A mais velha se chamava Oolá (que representa Samaria), e a mais nova, Oolibá (que representa Jerusalém). Eu casei com as duas, e elas me deram filhos.

[[v26-23-5]]

^<<v26-23-5,5>>^ Embora fosse minha, Oolá continuou a ser prostituta e estava louca pelos seus amantes da Assíria.

[[v26-23-6]]

^<<v26-23-6,6>>^ Eles eram soldados de uniformes vermelhos, nobres e oficiais graduados, todos eles jovens atraentes, oficiais da cavalaria.

[[v26-23-7]]

^<<v26-23-7,7>>^ Oolá foi prostituta de todos os oficiais assírios, e a paixão dela a levou a se tornar impura , adorando os ídolos assírios.

[[v26-23-8]]

^<<v26-23-8,8>>^ Ela continuou o que havia começado como prostituta, no Egito, onde tinha perdido a virgindade. Desde os seus tempos de mocinha, os homens dormiam com ela e a tratavam como prostituta.

[[v26-23-9]]

^<<v26-23-9,9>>^ Por isso, eu a entreguei aos seus amantes assírios, a quem ela tanto desejava.

[[v26-23-10]]

^<<v26-23-10,10>>^ Eles a deixaram nua, prenderam os seus filhos e filhas e depois a mataram com uma espada. Em toda parte, as mulheres falavam a respeito do fim que ela teve.

[[v26-23-11]]

^<<v26-23-11,11>>^ — Apesar de ter visto isso, Oolibá se tornou uma prostituta ainda mais sem-vergonha e imoral do que a irmã.

[[v26-23-12]]

^<<v26-23-12,12>>^ Ela também se apaixonou pelos nobres e pelos oficiais assírios — soldados de uniformes vistosos — e pelos oficiais da cavalaria, todos eles jovens simpáticos.

[[v26-23-13]]

^<<v26-23-13,13>>^ Vi que ela era totalmente imoral; assim a segunda irmã seguiu o mesmo caminho da primeira.

[[v26-23-14]]

^<<v26-23-14,14>>^ — Oolibá se afundou cada vez mais na imoralidade. Foi atraída pelas figuras esculpidas na parede e pintadas de vermelho vivo. Eram figuras de altos oficiais da Babilônia. Eles usavam cinturões e turbantes  de luxo.

[[v26-23-15]]

^<<v26-23-15,15>>^ — Oolibá se afundou cada vez mais na imoralidade. Foi atraída pelas figuras esculpidas na parede e pintadas de vermelho vivo. Eram figuras de altos oficiais da Babilônia. Eles usavam cinturões e turbantes  de luxo.

[[v26-23-16]]

^<<v26-23-16,16>>^ Logo que viu as figuras desses oficiais, Oolibá apaixonou-se por eles e mandou que mensageiros fossem falar com eles na Babilônia.

[[v26-23-17]]

^<<v26-23-17,17>>^ Os babilônios vieram para ter relações com Oolibá. Eles se aproveitaram dela e cometeram com ela tantas imoralidades, que ela ficou com nojo deles.

[[v26-23-18]]

^<<v26-23-18,18>>^ Oolibá ficou nua em público, e todo o mundo ficou sabendo que era prostituta. Eu fiquei revoltado contra ela, como havia ficado contra a sua irmã.

[[v26-23-19]]

^<<v26-23-19,19>>^ Ela afundou cada vez mais na prostituição, fazendo como nos tempos de moça, quando era prostituta no Egito.

[[v26-23-20]]

^<<v26-23-20,20>>^ Ela ficou apaixonada por homens sensuais, de membros grandes e tão fogosos no seu desejo como jumentos e cavalos.

[[v26-23-21]]

^<<v26-23-21,21>>^ — Assim, Oolibá, você quis repetir a imoralidade dos seus tempos de moça no Egito, quando os homens apalpavam os seus seios, e você perdeu a virgindade.

[[v26-23-22]]

^<<v26-23-22,22>>^ — Por essa razão, eu, o Senhor  Deus, estou dizendo isto a você, Oolibá. Você está enjoada desses amantes, mas eu farei com que eles fiquem com raiva de você e os trarei para que a cerquem.

[[v26-23-23]]

^<<v26-23-23,23>>^ Vou trazer todos os babilônios e todos os caldeus das cidades de Pecode, de Soa e de Coa e todos os assírios. Todos eles são jovens oficiais, nobres e simpáticos. Todos eles são graduados e altos oficiais da cavalaria.

[[v26-23-24]]

^<<v26-23-24,24>>^ Do Norte, eles atacarão, trazendo um grande exército com carros de guerra e carretas de mantimentos. Armados com escudos  e capacetes, eles cercarão você. Eu a entregarei a eles, e eles a julgarão pelas leis  deles.

[[v26-23-25]]

^<<v26-23-25,25>>^ Deixarei que eles a tratem com ódio, pois estou irado  com você. Eles cortarão o seu nariz e as suas orelhas e matarão os seus filhos. Sim! Eles tirarão de você os seus filhos e filhas e os queimarão vivos.

[[v26-23-26]]

^<<v26-23-26,26>>^ Eles arrancarão as suas roupas e tirarão as suas joias.

[[v26-23-27]]

^<<v26-23-27,27>>^ Eu acabarei com a sua imoralidade e com a prostituição que você tem praticado desde que estava no Egito. Nunca mais você olhará para nenhum ídolo, nem pensará mais no Egito.

[[v26-23-28]]

^<<v26-23-28,28>>^ O que o Senhor  Deus diz é isto: — Eu a entregarei nas mãos daqueles que você odeia e de quem você tem nojo.

[[v26-23-29]]

^<<v26-23-29,29>>^ E, porque eles a odeiam, tirarão tudo aquilo que você conseguiu com o seu trabalho e a largarão completamente nua, como se fosse uma prostituta. Por causa da sua imoralidade e da sua prostituição,

[[v26-23-30]]

^<<v26-23-30,30>>^ esses castigos caíram sobre você. Você foi prostituta dos povos e ficou impura  por causa dos ídolos deles.

[[v26-23-31]]

^<<v26-23-31,31>>^ Você seguiu o exemplo da sua irmã; por isso, castigarei você também, como castiguei a sua irmã.

[[v26-23-32]]

^<<v26-23-32,32>>^ O Senhor  Deus diz: "Você beberá o copo da sua irmã, que é largo e fundo. Todos vão caçoar e zombar de você; o copo está cheio.

[[v26-23-33]]

^<<v26-23-33,33>>^ O copo da sua irmã Samaria, cheio de medo e desgraça, vai trazer para você embriaguez e dor.

[[v26-23-34]]

^<<v26-23-34,34>>^ Você beberá até esvaziá-lo. Depois, o quebrará e com os cacos rasgará os seus seios. Eu, o Senhor  Deus, falei."

[[v26-23-35]]

^<<v26-23-35,35>>^ Agora, o que o Senhor  Deus está dizendo é isto: — Você me esqueceu e me virou as costas; portanto, sofrerá por causa da sua imoralidade e da sua prostituição.

[[v26-23-36]]

^<<v26-23-36,36>>^ O Senhor  me disse: — Homem mortal , você está pronto para julgar Oolá e Oolibá? Então acuse-as das coisas vergonhosas que têm feito.

[[v26-23-37]]

^<<v26-23-37,37>>^ Elas cometeram adultério e assassinato. Cometeram adultério com ídolos e mataram filhos que geraram para mim. Elas ofereceram os meus filhos para serem mortos em sacrifício  aos seus ídolos.

[[v26-23-38]]

^<<v26-23-38,38>>^ E isso ainda não foi tudo o que fizeram. Também profanaram  o meu Templo e quebraram o sábado, que eu havia mandado guardar.

[[v26-23-39]]

^<<v26-23-39,39>>^ Mataram os meus filhos como sacrifícios aos ídolos; e naquele mesmo dia vieram ao meu Templo e o profanaram.

[[v26-23-40]]

^<<v26-23-40,40>>^ — Oolá e Oolibá enviaram mensageiros para convidar homens de longe, e eles vieram. Elas tomaram banho, pintaram os olhos e se enfeitaram com joias.

[[v26-23-41]]

^<<v26-23-41,41>>^ Sentaram-se numa bela cama, com uma mesa bem-posta diante delas. E sobre a mesa puseram o incenso e o azeite que eu lhes tinha dado.

[[v26-23-42]]

^<<v26-23-42,42>>^ Então ouviu-se o barulho de uma multidão alegre, e entrou um grupo de homens do deserto. Colocaram pulseiras nos braços das mulheres e lindas coroas nas cabeças.

[[v26-23-43]]

^<<v26-23-43,43>>^ E eu disse a mim mesmo que eles estavam usando como prostituta uma mulher gasta pelo adultério.

[[v26-23-44]]

^<<v26-23-44,44>>^ Muitas vezes, eles voltaram a estar com essas prostitutas. Tornaram a se encontrar com Oolá e Oolibá, essas mulheres imorais.

[[v26-23-45]]

^<<v26-23-45,45>>^ Os homens direitos vão condená-las por adultério e assassinato porque elas adulteram, e as suas mãos derramam sangue.

[[v26-23-46]]

^<<v26-23-46,46>>^ O que o Senhor  Deus diz é isto: — Tragam uma multidão para pôr medo nelas e roubar o que elas têm.

[[v26-23-47]]

^<<v26-23-47,47>>^ Que a multidão jogue pedras nessas duas mulheres e as ataque com espadas, mate os seus filhos e ponha fogo nas suas casas!

[[v26-23-48]]

^<<v26-23-48,48>>^ Acabarei com a imoralidade que há no país inteiro, como um aviso para que nenhuma mulher cometa adultério como essas duas cometeram.

'''

xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]