include::./index.adoc[]

[[v26-48-0]]
=== Ezequiel, 48
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-48-1]]

^<<v26-48-1,1>>^ Ao norte, a fronteira vai para o leste, do mar Mediterrâneo até a cidade de Hetlom, até a subida de Hamate, até a cidade de Enom e até a divisa entre os reinos de Damasco e Hamate. Cada tribo  deverá receber terras que irão desde a fronteira do leste até o mar Mediterrâneo, a oeste, na seguinte ordem do norte para o sul: Dã, Aser, Naftali, Manassés, Efraim, Rúben e Judá.

[[v26-48-2]]

^<<v26-48-2,2>>^ Ao norte, a fronteira vai para o leste, do mar Mediterrâneo até a cidade de Hetlom, até a subida de Hamate, até a cidade de Enom e até a divisa entre os reinos de Damasco e Hamate. Cada tribo  deverá receber terras que irão desde a fronteira do leste até o mar Mediterrâneo, a oeste, na seguinte ordem do norte para o sul: Dã, Aser, Naftali, Manassés, Efraim, Rúben e Judá.

[[v26-48-3]]

^<<v26-48-3,3>>^ Ao norte, a fronteira vai para o leste, do mar Mediterrâneo até a cidade de Hetlom, até a subida de Hamate, até a cidade de Enom e até a divisa entre os reinos de Damasco e Hamate. Cada tribo  deverá receber terras que irão desde a fronteira do leste até o mar Mediterrâneo, a oeste, na seguinte ordem do norte para o sul: Dã, Aser, Naftali, Manassés, Efraim, Rúben e Judá.

[[v26-48-4]]

^<<v26-48-4,4>>^ Ao norte, a fronteira vai para o leste, do mar Mediterrâneo até a cidade de Hetlom, até a subida de Hamate, até a cidade de Enom e até a divisa entre os reinos de Damasco e Hamate. Cada tribo  deverá receber terras que irão desde a fronteira do leste até o mar Mediterrâneo, a oeste, na seguinte ordem do norte para o sul: Dã, Aser, Naftali, Manassés, Efraim, Rúben e Judá.

[[v26-48-5]]

^<<v26-48-5,5>>^ Ao norte, a fronteira vai para o leste, do mar Mediterrâneo até a cidade de Hetlom, até a subida de Hamate, até a cidade de Enom e até a divisa entre os reinos de Damasco e Hamate. Cada tribo  deverá receber terras que irão desde a fronteira do leste até o mar Mediterrâneo, a oeste, na seguinte ordem do norte para o sul: Dã, Aser, Naftali, Manassés, Efraim, Rúben e Judá.

[[v26-48-6]]

^<<v26-48-6,6>>^ Ao norte, a fronteira vai para o leste, do mar Mediterrâneo até a cidade de Hetlom, até a subida de Hamate, até a cidade de Enom e até a divisa entre os reinos de Damasco e Hamate. Cada tribo  deverá receber terras que irão desde a fronteira do leste até o mar Mediterrâneo, a oeste, na seguinte ordem do norte para o sul: Dã, Aser, Naftali, Manassés, Efraim, Rúben e Judá.

[[v26-48-7]]

^<<v26-48-7,7>>^ Ao norte, a fronteira vai para o leste, do mar Mediterrâneo até a cidade de Hetlom, até a subida de Hamate, até a cidade de Enom e até a divisa entre os reinos de Damasco e Hamate. Cada tribo  deverá receber terras que irão desde a fronteira do leste até o mar Mediterrâneo, a oeste, na seguinte ordem do norte para o sul: Dã, Aser, Naftali, Manassés, Efraim, Rúben e Judá.

[[v26-48-8]]

^<<v26-48-8,8>>^ Ao lado do território de Judá, ficará a terra separada para uso especial. De norte a sul, terá doze quilômetros e meio de largura e de leste a oeste terá o mesmo comprimento dos territórios dados às tribos . O Templo ficará nessa área.

[[v26-48-9]]

^<<v26-48-9,9>>^ No centro dessas terras haverá uma área dedicada ao Senhor , com doze quilômetros e meio por dez.

[[v26-48-10]]

^<<v26-48-10,10>>^ Os sacerdotes terão uma parte dessa terra sagrada. Nos lados norte e sul, deverá medir doze quilômetros e meio e nos lados leste e oeste deverá medir cinco. O Templo do Senhor  ficará no meio.

[[v26-48-11]]

^<<v26-48-11,11>>^ Essa área sagrada será para os sacerdotes descendentes de Zadoque. Eles me serviram fielmente e não se juntaram com o resto dos israelitas para fazer o mal, como os outros membros da tribo de Levi fizeram.

[[v26-48-12]]

^<<v26-48-12,12>>^ Por isso, eles terão uma área especial perto da área dos levitas , e será a área mais santa de todas.

[[v26-48-13]]

^<<v26-48-13,13>>^ Os levitas também terão uma área de terra que fará limite com a dos sacerdotes. Terá doze quilômetros e meio por cinco.

[[v26-48-14]]

^<<v26-48-14,14>>^ A terra dedicada ao Senhor  é a melhor de todas, e nenhuma parte dela poderá ser vendida, nem trocada, nem transferida para ninguém. É santa e pertence a Deus.

[[v26-48-15]]

^<<v26-48-15,15>>^ A área que sobrar, de doze quilômetros e meio por dois e meio, não é santa, mas será para uso geral do povo. Eles poderão morar ali e aproveitar a terra. A cidade ficará no centro

[[v26-48-16]]

^<<v26-48-16,16>>^ e será quadrada, medindo dois mil duzentos e cinquenta metros de cada lado.

[[v26-48-17]]

^<<v26-48-17,17>>^ Em toda a volta da cidade, de cada lado, haverá um espaço livre de cento e vinte e cinco metros de largura.

[[v26-48-18]]

^<<v26-48-18,18>>^ A terra que sobrar depois de construída a cidade nas terras ao lado da área sagrada — cinco quilômetros por dois e meio para o leste e cinco quilômetros por dois e meio para o oeste — essa terra será usada pela gente que mora na cidade, para nela fazerem plantações.

[[v26-48-19]]

^<<v26-48-19,19>>^ Quem trabalhar na cidade, seja de que tribo for, poderá cultivar essa terra.

[[v26-48-20]]

^<<v26-48-20,20>>^ Assim a área toda será quadrada, medindo doze quilômetros e meio de cada lado, e incluirá as terras ocupadas pela cidade.

'''

xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]