include::./index.adoc[]

[[v26-7-0]]
=== Ezequiel, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-7-1]]

^<<v26-7-1,1>>^ O Senhor  Deus falou comigo assim:

[[v26-7-2]]

^<<v26-7-2,2>>^ — Homem mortal , é isto o que eu, o Senhor  Deus, estou dizendo à terra de Israel: Tudo está acabado! Este é o fim do país inteiro!

[[v26-7-3]]

^<<v26-7-3,3>>^ — Povo de Israel, o fim chegou. Vocês sentirão a minha ira , pois eu os estou julgando pelo que fizeram. Farei com que vocês sofram porque fizeram coisas imorais.

[[v26-7-4]]

^<<v26-7-4,4>>^ Vou castigá-los sem dó nem piedade. Eu os castigarei pelas coisas nojentas que fizeram, para que vocês fiquem sabendo que eu sou o Senhor .

[[v26-7-5]]

^<<v26-7-5,5>>^ O que o Senhor  Deus diz é isto: — Cairão sobre vocês desastres, um em cima do outro.

[[v26-7-6]]

^<<v26-7-6,6>>^ Tudo está terminado. É o fim. Vocês estão acabados.

[[v26-7-7]]

^<<v26-7-7,7>>^ O fim está chegando para vocês que moram nesta terra. Está se aproximando o tempo em que nos santuários das montanhas não haverá mais festas, mas somente confusão.

[[v26-7-8]]

^<<v26-7-8,8>>^ — Logo vocês vão sentir toda a força da minha ira. Eu estou julgando vocês pelo que têm feito. Farei com que sofram as consequências do seu nojento modo de agir.

[[v26-7-9]]

^<<v26-7-9,9>>^ Não pouparei vocês, nem terei piedade. Eu os castigarei pelas coisas imorais que têm feito, de modo que vocês saberão que eu sou o Senhor  e que sou eu quem os castiga.

[[v26-7-10]]

^<<v26-7-10,10>>^ O dia da desgraça está chegando. Por toda parte há violência. O orgulho cresce.

[[v26-7-11]]

^<<v26-7-11,11>>^ A violência aumenta e é um castigo para a maldade do povo. Tudo o que é deles desaparecerá: a sua riqueza, a sua fama, a sua glória .

[[v26-7-12]]

^<<v26-7-12,12>>^ O tempo está chegando. Está perto o dia em que não adiantará mais comprar, nem vender, pois a ira do Senhor  cairá igualmente sobre todos.

[[v26-7-13]]

^<<v26-7-13,13>>^ Nenhum comerciante viverá o suficiente para tornar a ganhar tudo o que perdeu, pois a ira do Senhor  cairá sobre todos. Os maus não continuarão a viver.

[[v26-7-14]]

^<<v26-7-14,14>>^ São tocadas as cornetas, e todos se preparam. Mas ninguém sai para a guerra porque a ira do Senhor  cairá sobre todos igualmente.

[[v26-7-15]]

^<<v26-7-15,15>>^ Há luta nas ruas, e peste e fome nas casas. Quem estiver no campo morrerá na batalha, e quem estiver na cidade será devorado pela peste e pela fome.

[[v26-7-16]]

^<<v26-7-16,16>>^ Alguns, como pombas dos vales, fugirão para as montanhas. E todos gemerão por causa dos seus pecados.

[[v26-7-17]]

^<<v26-7-17,17>>^ As mãos de todos perderão as forças, e os seus joelhos tremerão.

[[v26-7-18]]

^<<v26-7-18,18>>^ Em sinal de tristeza, eles vestirão roupa feita de pano grosseiro e tremerão como varas verdes. As cabeças deles serão rapadas, e todos passarão vergonha.

[[v26-7-19]]

^<<v26-7-19,19>>^ Jogarão o seu ouro e a sua prata nas ruas como lixo porque, quando Deus ficar enfurecido, nem ouro nem prata poderão salvá-los. Eles não poderão usá-los para satisfazer aos seus desejos ou encherem os seus estômagos. O ouro e a prata os levaram a pecar.

[[v26-7-20]]

^<<v26-7-20,20>>^ Eles se orgulhavam das suas lindas joias, porém as usaram para fazer ídolos nojentos. Foi por isso que Deus fez com que eles ficassem com nojo das suas riquezas.

[[v26-7-21]]

^<<v26-7-21,21>>^ — Eu vou deixar que estrangeiros os roubem! — diz o Senhor . — Os maus pegarão toda a sua riqueza e a tratarão como se fosse uma coisa imunda.

[[v26-7-22]]

^<<v26-7-22,22>>^ Não farei nada quando o meu Templo for desrespeitado, quando ladrões o invadirem e profanarem .

[[v26-7-23]]

^<<v26-7-23,23>>^ — Tudo é confusão. A terra está cheia de assassinos, e as cidades estão cheias de violência.

[[v26-7-24]]

^<<v26-7-24,24>>^ Trarei aqui as nações mais perversas e lhes darei as casas de vocês. Quando eu deixar as nações pagãs profanarem os lugares onde vocês adoram, até os homens fortes perderão a confiança em si mesmos.

[[v26-7-25]]

^<<v26-7-25,25>>^ O desespero está chegando. Vocês procurarão a paz, porém não a encontrarão.

[[v26-7-26]]

^<<v26-7-26,26>>^ Haverá desgraça após desgraça, e más notícias em cima de más notícias. Vocês pedirão que os profetas  expliquem o que eles estão vendo que vai acontecer. Os sacerdotes não terão nada para ensinar ao povo, e os velhos não terão conselhos para dar.

[[v26-7-27]]

^<<v26-7-27,27>>^ O rei chorará, o príncipe perderá as esperanças, e o povo tremerá de medo. Eu castigarei vocês por tudo o que fizeram e os julgarei do modo como vocês julgaram os outros. Isso mostrará que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]