include::./index.adoc[]

[[v26-41-0]]
=== Ezequiel, 41
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-41-1]]

^<<v26-41-1,1>>^ Depois, o homem me levou ao salão central, o Lugar Santo . Ele mediu a passagem que dava para esse salão, e tinha três metros de comprimento

[[v26-41-2]]

^<<v26-41-2,2>>^ por cinco de largura, com paredes de dois metros e meio de cada lado. E mediu o salão, que tinha vinte metros de comprimento por dez de largura.

[[v26-41-3]]

^<<v26-41-3,3>>^ Em seguida, ele foi até o último salão. Mediu a passagem que dava para ele, e tinha um metro de comprimento por três de largura; dos dois lados havia paredes de três metros e meio de grossura.

[[v26-41-4]]

^<<v26-41-4,4>>^ Também mediu o salão; era quadrado, com dez metros de cada lado, e ficava adiante do salão central. Aí o homem me disse: — Este é o Lugar Santíssimo .

[[v26-41-5]]

^<<v26-41-5,5>>^ O homem mediu a grossura da parede interna do Templo, e era de três metros. Em toda a volta do Templo havia uma porção de pequenos cômodos encostados na parede, medindo dois metros de largura cada um.

[[v26-41-6]]

^<<v26-41-6,6>>^ Esses cômodos estavam em três andares, trinta cômodos em cada andar. A parede de fora do Templo ia ficando mais estreita em cada andar, e assim os cômodos estavam encostados na parede, mas não eram presos nela.

[[v26-41-7]]

^<<v26-41-7,7>>^ Portanto, as paredes do Templo, vistas de fora, pareciam ter a mesma grossura de cima abaixo. Havia duas escadarias largas do lado de fora dos cômodos que estavam construídos encostados na parede do Templo, em toda a sua volta. Assim, podia-se subir do térreo ao andar do meio e ao andar de cima.

[[v26-41-8]]

^<<v26-41-8,8>>^ A parede de fora desses cômodos tinha dois metros e meio de grossura. Havia uma porta que dava para os cômodos do lado norte do Templo, e uma que dava para os cômodos do lado sul. Vi que em volta do Templo havia um terraço que media dois metros e meio de largura. Esse terraço estava a três metros acima do chão e ficava no mesmo nível do alicerce dos cômodos que estavam ao lado das paredes do Templo. Em volta do Templo, entre o terraço e os edifícios usados pelos sacerdotes, havia um espaço livre de dez metros de largura.

[[v26-41-9]]

^<<v26-41-9,9>>^ A parede de fora desses cômodos tinha dois metros e meio de grossura. Havia uma porta que dava para os cômodos do lado norte do Templo, e uma que dava para os cômodos do lado sul. Vi que em volta do Templo havia um terraço que media dois metros e meio de largura. Esse terraço estava a três metros acima do chão e ficava no mesmo nível do alicerce dos cômodos que estavam ao lado das paredes do Templo. Em volta do Templo, entre o terraço e os edifícios usados pelos sacerdotes, havia um espaço livre de dez metros de largura.

[[v26-41-10]]

^<<v26-41-10,10>>^ A parede de fora desses cômodos tinha dois metros e meio de grossura. Havia uma porta que dava para os cômodos do lado norte do Templo, e uma que dava para os cômodos do lado sul. Vi que em volta do Templo havia um terraço que media dois metros e meio de largura. Esse terraço estava a três metros acima do chão e ficava no mesmo nível do alicerce dos cômodos que estavam ao lado das paredes do Templo. Em volta do Templo, entre o terraço e os edifícios usados pelos sacerdotes, havia um espaço livre de dez metros de largura.

[[v26-41-11]]

^<<v26-41-11,11>>^ A parede de fora desses cômodos tinha dois metros e meio de grossura. Havia uma porta que dava para os cômodos do lado norte do Templo, e uma que dava para os cômodos do lado sul. Vi que em volta do Templo havia um terraço que media dois metros e meio de largura. Esse terraço estava a três metros acima do chão e ficava no mesmo nível do alicerce dos cômodos que estavam ao lado das paredes do Templo. Em volta do Templo, entre o terraço e os edifícios usados pelos sacerdotes, havia um espaço livre de dez metros de largura.

[[v26-41-12]]

^<<v26-41-12,12>>^ Do lado oeste, no fim do espaço livre, havia um edifício que dava para o Templo. Tinha trinta e cinco metros de um lado e quarenta e cinco do outro. As suas paredes eram de dois metros e meio de grossura em toda a volta.

[[v26-41-13]]

^<<v26-41-13,13>>^ O homem mediu o lado de fora do Templo: tinha cinquenta metros de comprimento. Do fundo do Templo, atravessando o pátio até a ponta do edifício do lado oeste, a distância também era de cinquenta metros.

[[v26-41-14]]

^<<v26-41-14,14>>^ A largura da frente do Templo, junto com o espaço livre dos dois lados, era de cinquenta metros.

[[v26-41-15]]

^<<v26-41-15,15>>^ O homem mediu o comprimento do edifício que ficava do lado oeste do Templo, no fim do espaço livre, e também os seus corredores de cada lado, e esse comprimento também era de cinquenta metros. O salão de entrada do Templo, o Lugar Santo  e o Lugar Santíssimo

[[v26-41-16]]

^<<v26-41-16,16>>^ eram todos forrados de madeira, desde o chão até as janelas. Essas janelas podiam ser cobertas.

[[v26-41-17]]

^<<v26-41-17,17>>^ Por dentro, as paredes do Templo, até o alto das portas, estavam todas cobertas de figuras entalhadas

[[v26-41-18]]

^<<v26-41-18,18>>^ de palmeiras e de animais com asas . Vinha primeiro uma palmeira e depois um animal e continuava assim em toda a volta. Cada animal tinha duas caras:

[[v26-41-19]]

^<<v26-41-19,19>>^ uma cara de homem, virada para a palmeira de um lado, e uma cara de leão, virada para a palmeira do outro lado. Era assim em toda a volta da parede,

[[v26-41-20]]

^<<v26-41-20,20>>^ desde o chão até o alto das portas.

[[v26-41-21]]

^<<v26-41-21,21>>^ Os batentes do Lugar Santo eram quadrados. Na frente da entrada do Lugar Santíssimo  havia uma coisa que parecia

[[v26-41-22]]

^<<v26-41-22,22>>^ um altar de madeira. Tinha um metro e meio de altura por um metro de largura. Os cantos, a base e os lados eram de madeira. O homem me disse: — Esta é a mesa que fica na presença de Deus, o Senhor .

[[v26-41-23]]

^<<v26-41-23,23>>^ Havia uma porta na ponta da passagem que dava para o Lugar Santo , e outra porta na ponta da passagem que dava para o Lugar Santíssimo .

'''

xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[&#60; Capítulo Anterior] | <<v26-41-0,Topo>> | xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[Próximo Capítulo &#62;]