include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-24-1]]

^<<v26-24-1,1>>^ No ano nove do nosso cativeiro , no dia dez do décimo mês , o Senhor  me disse o seguinte:

[[v26-24-2]]

^<<v26-24-2,2>>^ — Homem mortal , escreva a data de hoje porque este é o dia em que o rei da Babilônia está começando o cerco de Jerusalém .

[[v26-24-3]]

^<<v26-24-3,3>>^ Conte ao meu povo rebelde esta comparação que eu, o Senhor  Deus, tenho para eles: "Ponha a panela no fogo e encha com água.

[[v26-24-4]]

^<<v26-24-4,4>>^ Coloque dentro os melhores pedaços de carne — a alcatra e o filé. Encha também a panela com os melhores pedaços de carne com osso.

[[v26-24-5]]

^<<v26-24-5,5>>^ Pegue a carne do melhor carneiro e amontoe lenha debaixo da panela. Deixe a água ferver; ferva os ossos e a carne."

[[v26-24-6]]

^<<v26-24-6,6>>^ Agora, o que o Senhor  Deus está dizendo é isto: — Ai da cidade dos assassinos! É como uma panela enferrujada, que nunca foi lavada. Tira-se de dentro dela a carne, pedaço por pedaço, e não sobra nada.

[[v26-24-7]]

^<<v26-24-7,7>>^ Havia crime de morte na cidade, mas o sangue não foi derramado no chão, onde o pó o poderia esconder . O sangue foi derramado sobre a rocha nua.

[[v26-24-8]]

^<<v26-24-8,8>>^ Deixei o sangue ali, onde não pode ser escondido, onde com ódio está pedindo vingança.

[[v26-24-9]]

^<<v26-24-9,9>>^ Por isso, o Senhor  Deus está dizendo o seguinte: — Ai da cidade dos assassinos! Eu mesmo empilharei lenha para a fogueira.

[[v26-24-10]]

^<<v26-24-10,10>>^ Traga mais lenha! Acenda o fogo! Cozinhe a carne! Deixe o caldo ferver até secar! Que os ossos fiquem torrados!

[[v26-24-11]]

^<<v26-24-11,11>>^ Agora, deixe a panela vazia em cima das brasas até que fique vermelha. Assim o fogo acabará com a ferrugem, e a panela deixará de ser impura .

[[v26-24-12]]

^<<v26-24-12,12>>^ Trabalho perdido! Toda a ferrugem não vai desaparecer nas chamas.

[[v26-24-13]]

^<<v26-24-13,13>>^ Jerusalém, os seus atos imorais mancharam você. Eu tentei purificá-la, mas você continuou impura. Você não será pura de novo até que sinta toda a força da minha ira .

[[v26-24-14]]

^<<v26-24-14,14>>^ Sou eu, o Senhor , quem está falando. Chegou a minha hora de agir. Não esquecerei os seus pecados; não terei dó nem piedade. Você será castigada pelo que tem feito. Eu, o Senhor  Deus, falei.

[[v26-24-15]]

^<<v26-24-15,15>>^ O Senhor  me disse o seguinte:

[[v26-24-16]]

^<<v26-24-16,16>>^ — Homem mortal , com um só golpe, vou levar aquela que você mais ama. Não reclame, não chore, não derrame lágrimas.

[[v26-24-17]]

^<<v26-24-17,17>>^ Não deixe que ninguém ouça os seus gemidos. Não ande sem chapéu ou descalço, como sinal de luto. Não cubra o rosto, nem coma a comida que oferecem nos sepultamentos.

[[v26-24-18]]

^<<v26-24-18,18>>^ De manhã eu estava falando com o povo, e à noite a minha esposa faleceu. No dia seguinte, fiz como o Senhor  havia mandado.

[[v26-24-19]]

^<<v26-24-19,19>>^ Então o povo me perguntou: — Por que você está agindo assim?

[[v26-24-20]]

^<<v26-24-20,20>>^ Aí eu disse: — O Senhor  falou comigo e me disse

[[v26-24-21]]

^<<v26-24-21,21>>^ para dar a vocês, israelitas, esta mensagem: Vocês estão orgulhosos porque o Templo é tão firme. Vocês gostam de olhar para ele e de visitá-lo, porém o Senhor  Deus o tornará impuro. Os seus filhos e filhas que ficaram em Jerusalém serão mortos na guerra.

[[v26-24-22]]

^<<v26-24-22,22>>^ Aí vocês vão fazer como eu fiz. Vocês não cobrirão o rosto, nem comerão a comida que oferecem nos sepultamentos.

[[v26-24-23]]

^<<v26-24-23,23>>^ Vocês não andarão sem chapéu nem descalços; não vão pôr luto, nem vão chorar. Por causa dos seus pecados, vocês se acabarão e ficarão gemendo juntos.

[[v26-24-24]]

^<<v26-24-24,24>>^ Assim eu, Ezequiel, serei um sinal para vocês. Vocês farão tudo o que eu fiz. O Senhor  diz que, quando isso acontecer, vocês ficarão sabendo que ele é o Senhor  Deus.

[[v26-24-25]]

^<<v26-24-25,25>>^ O Senhor  disse: — Agora, homem mortal, vou tirar deles o Templo, que é firme, que era o orgulho e a alegria deles, e que gostavam tanto de admirar e de visitar. E também vou tirar os seus filhos e as suas filhas.

[[v26-24-26]]

^<<v26-24-26,26>>^ No dia em que eu fizer isso, alguém que escapar da destruição virá para contar o que aconteceu.

[[v26-24-27]]

^<<v26-24-27,27>>^ Nesse dia, você poderá falar outra vez e conversar com aquele que escapou. Nesse dia, você será um sinal para os israelitas, e eles ficarão sabendo que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]