include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-5-1]]

^<<v26-5-1,1>>^ Deus disse: — Homem mortal , pegue uma espada afiada e com ela corte a barba e os cabelos. Depois, pese os cabelos e os pelos numa balança e divida-os em três partes.

[[v26-5-2]]

^<<v26-5-2,2>>^ Quando os inimigos deixarem de cercar a cidade, vá ao centro e queime ali uma terça parte desses cabelos e pelos. Depois, ande em volta da cidade e vá picando outra terça parte com a espada. Jogue a última terça parte para o ar, e o vento a levará. Aí eu a atacarei com a minha espada.

[[v26-5-3]]

^<<v26-5-3,3>>^ Guarde alguns fios de cabelo e prenda-os na barra da sua roupa.

[[v26-5-4]]

^<<v26-5-4,4>>^ Então tire dali alguns fios, jogue-os no fogo e deixe queimar. O fogo que sairá deles se espalhará por toda a nação de Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ O Senhor  Deus disse: — Olhe para a cidade de Jerusalém. Eu a coloquei no centro do mundo e pus os outros países em volta dela.

[[v26-5-6]]

^<<v26-5-6,6>>^ Mas Jerusalém se revoltou contra os meus mandamentos e acabou se tornando mais perversa do que as outras nações, mais desobediente do que os povos que estão em volta dela. Jerusalém rejeitou os meus mandamentos e não quis guardar as minhas leis .

[[v26-5-7]]

^<<v26-5-7,7>>^ Agora, Jerusalém, preste atenção no que eu, o Senhor  Deus, estou dizendo. Vocês não obedeceram às minhas leis, nem guardaram os meus mandamentos e por isso têm causado mais confusão do que as nações que estão ao seu redor. Vocês têm seguido os costumes de outras nações.

[[v26-5-8]]

^<<v26-5-8,8>>^ Por isso, eu, o Senhor  Deus, digo que estou contra vocês. Eu os julgarei num lugar onde todos os povos possam ver.

[[v26-5-9]]

^<<v26-5-9,9>>^ Por causa de todas as coisas horríveis que vocês fazem, eu castigarei Jerusalém como nunca fiz antes e como nunca mais farei.

[[v26-5-10]]

^<<v26-5-10,10>>^ Como resultado, em Jerusalém os pais vão devorar os próprios filhos, e os filhos vão devorar os pais. Eu castigarei vocês; e os que ficarem vivos serão espalhados em todas as direções.

[[v26-5-11]]

^<<v26-5-11,11>>^ — Portanto, esta é a palavra do Senhor  Deus: Vocês profanaram  o meu Templo com tudo o que é mau e sujo, e por isso juro pela minha vida que eu os destruirei sem dó nem piedade.

[[v26-5-12]]

^<<v26-5-12,12>>^ Uma terça parte do povo morrerá de peste e de fome dentro da cidade; outra terça parte será morta por espadas fora da cidade; e a outra terça parte eu espalharei aos ventos e a perseguirei com uma espada.

[[v26-5-13]]

^<<v26-5-13,13>>^ — Vocês sentirão toda a força da minha ira  e do meu furor, até que eu fique satisfeito. Quando tudo isso acontecer, vocês ficarão convencidos de que eu, o Senhor , lhes disse todas essas coisas porque fui ofendido pela infidelidade de vocês.

[[v26-5-14]]

^<<v26-5-14,14>>^ Eu farei com que você, Jerusalém, fique arrasada, e por isso as nações ao seu redor e os que passarem por você vão zombar dos seus moradores.

[[v26-5-15]]

^<<v26-5-15,15>>^ — Quando eu ficar irado  e furioso com vocês e castigá-los, todas as nações vizinhas ficarão espantadas. Olharão para vocês com nojo e zombarão.

[[v26-5-16]]

^<<v26-5-16,16>>^ Não vou deixar que vocês recebam comida de fora, e assim morrerão de fome. Vocês sentirão as dores da fome como se fossem flechas pontudas mandadas para destruí-los.

[[v26-5-17]]

^<<v26-5-17,17>>^ Mandarei fome e animais ferozes para matarem os seus filhos e peste, violência e guerra para matarem vocês. Eu, o Senhor , falei.

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]