include::./index.adoc[]

[[v26-20-0]]
=== Ezequiel, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-20-1]]

^<<v26-20-1,1>>^ Passaram sete anos, cinco meses e dez dias desde que os israelitas haviam sido levados para o cativeiro . Então alguns líderes vieram falar comigo para saber a vontade do Senhor . Eles chegaram e se sentaram na minha frente.

[[v26-20-2]]

^<<v26-20-2,2>>^ O Senhor  falou comigo. Ele disse:

[[v26-20-3]]

^<<v26-20-3,3>>^ — Homem mortal , diga a esses líderes que o Senhor  está dizendo isto: Vocês vieram para saber qual é a minha vontade? Pois eu juro pela minha vida que não deixarei que vocês me perguntem nada. Sou eu, o Senhor  Deus, quem está falando.

[[v26-20-4]]

^<<v26-20-4,4>>^ — Homem mortal, você está pronto para julgar essa gente? Então julgue. Faça com que eles lembrem das coisas vergonhosas que os antepassados deles fizeram.

[[v26-20-5]]

^<<v26-20-5,5>>^ Diga tudo o que eu, o Senhor  Deus, estou falando. No dia em que escolhi o povo de Israel, fiz uma promessa a eles. No Egito, mostrei aos israelitas quem eu era e disse: "Eu sou o Senhor , o Deus de vocês."

[[v26-20-6]]

^<<v26-20-6,6>>^ Nessa ocasião, prometi que ia tirá-los do Egito e guiá-los a uma terra que eu havia escolhido para eles, uma terra boa e rica, a melhor de todas.

[[v26-20-7]]

^<<v26-20-7,7>>^ Eu lhes disse: "Joguem fora os ídolos nojentos que vocês amam e não se manchem com os falsos deuses do Egito, pois o Deus de vocês sou eu, o Senhor ."

[[v26-20-8]]

^<<v26-20-8,8>>^ Mas eles se revoltaram contra mim e não quiseram me ouvir. E não jogaram fora os seus ídolos nojentos, nem abandonaram os ídolos do Egito. Eu estava pronto para fazê-los sentir, ali no Egito, a força da minha ira .

[[v26-20-9]]

^<<v26-20-9,9>>^ Porém não fiz isso a fim de não trazer desonra para o meu nome. Pois, na presença do povo no meio do qual os israelitas estavam vivendo, eu havia anunciado que ia tirá-los do Egito.

[[v26-20-10]]

^<<v26-20-10,10>>^ — E assim os tirei do Egito e os levei para o deserto.

[[v26-20-11]]

^<<v26-20-11,11>>^ Eu lhes dei os meus mandamentos e lhes ensinei as minhas leis , que dão vida a quem os cumprir.

[[v26-20-12]]

^<<v26-20-12,12>>^ Como sinal da nossa aliança , mandei que eles guardassem o sábado e assim lembrassem que eu, o Senhor , os separo para que se dediquem somente a mim.

[[v26-20-13]]

^<<v26-20-13,13>>^ Mas também no deserto os israelitas se revoltaram contra mim. Desobedeceram às minhas leis e rejeitaram os meus mandamentos, que dão vida a quem os cumprir. Profanaram  completamente o sábado. Eu estava pronto para fazê-los sentir a força da minha ira  e acabar com eles ali no deserto.

[[v26-20-14]]

^<<v26-20-14,14>>^ E não os destruí a fim de não trazer desonra para o meu nome, pois as outras nações viram que tirei o povo de Israel do Egito.

[[v26-20-15]]

^<<v26-20-15,15>>^ Além disso, no deserto jurei que não os levaria à terra que eu tinha dado a eles, uma terra boa e rica, a melhor de todas.

[[v26-20-16]]

^<<v26-20-16,16>>^ Fiz esse juramento porque eles rejeitaram os meus mandamentos, desobedeceram às minhas leis e profanaram o sábado. Eles tinham prazer em adorar os seus ídolos.

[[v26-20-17]]

^<<v26-20-17,17>>^ — Porém eu tive pena deles e não os matei, nem acabei com eles lá no deserto.

[[v26-20-18]]

^<<v26-20-18,18>>^ Em vez disso, eu disse aos seus filhos: "Não guardem as leis que os seus antepassados fizeram; não sigam os costumes deles, nem se manchem com os seus ídolos.

[[v26-20-19]]

^<<v26-20-19,19>>^ Eu sou o Senhor , o Deus de vocês. Obedeçam às minhas leis e aos meus mandamentos.

[[v26-20-20]]

^<<v26-20-20,20>>^ Façam do sábado um dia sagrado, de modo que seja um sinal da aliança que fizemos. O sábado fará com que lembrem que eu sou o Senhor , o Deus de vocês."

[[v26-20-21]]

^<<v26-20-21,21>>^ — Mas esses filhos também se revoltaram contra mim. Desobedeceram às minhas leis e não guardaram os meus mandamentos, que dão vida a quem os cumprir. Eles profanaram o sábado. Eu estava pronto para fazê-los sentir a força da minha ira, matando todos ali no deserto.

[[v26-20-22]]

^<<v26-20-22,22>>^ Porém não os destruí a fim de não trazer desonra para o meu nome entre as nações que me viram tirar o povo de Israel do Egito.

[[v26-20-23]]

^<<v26-20-23,23>>^ Então fiz um novo juramento no deserto. Jurei que ia espalhar os israelitas pelo mundo inteiro.

[[v26-20-24]]

^<<v26-20-24,24>>^ Fiz isso porque rejeitaram os meus mandamentos, desobedeceram às minhas leis, profanaram o sábado e adoraram os mesmos ídolos que os seus antepassados tinham servido.

[[v26-20-25]]

^<<v26-20-25,25>>^ Então lhes dei leis más e mandamentos que não produzem vida.

[[v26-20-26]]

^<<v26-20-26,26>>^ Deixei que se tornassem impuros , trazendo as suas próprias ofertas; deixei que matassem os seus filhos mais velhos, oferecendo-os em sacrifício . Isso aconteceu para que ficassem cheios de medo e para mostrar que eu sou o Senhor .

[[v26-20-27]]

^<<v26-20-27,27>>^ — Por isso, homem mortal, conte aos israelitas o que eu, o Senhor  Deus, estou dizendo a eles. Os pais deles também me insultaram de outro modo com a sua infidelidade:

[[v26-20-28]]

^<<v26-20-28,28>>^ quando eu os trouxe para a terra que havia jurado dar-lhes, eles viram os montes altos e as árvores que dão sombra e ofereceram sacrifícios em todos eles. Eles me fizeram ficar irado por causa dos sacrifícios que queimaram e das ofertas de bebidas que trouxeram.

[[v26-20-29]]

^<<v26-20-29,29>>^ Eu perguntei: "Que são esses lugares altos aonde vocês vão?" Por isso, desde aquele tempo eles têm sido chamados de "lugares altos".

[[v26-20-30]]

^<<v26-20-30,30>>^ Agora, diga aos israelitas o que estou dizendo. Por que é que vocês precisam cometer os mesmos pecados que os seus antepassados cometeram? Por que têm de correr atrás dos ídolos deles?

[[v26-20-31]]

^<<v26-20-31,31>>^ Até hoje, vocês apresentam as mesmas ofertas e se tornam impuros por causa dos mesmos ídolos, queimando vivos os seus filhos, como sacrifício. E aí vocês, israelitas, ainda vêm me perguntar o que eu quero. Juro pela minha vida, diz o Senhor  Deus, que não deixarei que vocês me perguntem nada.

[[v26-20-32]]

^<<v26-20-32,32>>^ Vocês já resolveram que querem ser como as outras nações, como aquela gente que mora em outros países e adora árvores e pedras. Mas isso nunca acontecerá.

[[v26-20-33]]

^<<v26-20-33,33>>^ — Juro pela minha vida, diz o Senhor  Deus, que governarei vocês com mão forte, com todo o meu poder e a minha ira .

[[v26-20-34]]

^<<v26-20-34,34>>^ Mostrarei a vocês o meu poder e a minha ira quando eu os ajuntar e trouxer de volta de todos os países por onde foram espalhados.

[[v26-20-35]]

^<<v26-20-35,35>>^ Eu os levarei ao "Deserto das Nações" e ali os julgarei cara a cara.

[[v26-20-36]]

^<<v26-20-36,36>>^ Eu os condenarei agora como condenei os seus antepassados no deserto do Sinai! — diz o Senhor  Deus.

[[v26-20-37]]

^<<v26-20-37,37>>^ — Eu os dominarei com firmeza e farei com que obedeçam à minha aliança .

[[v26-20-38]]

^<<v26-20-38,38>>^ Tirarei do meio de vocês os que são rebeldes e pecadores. Eu os tirarei das terras onde agora estão vivendo, porém não os deixarei voltar à terra de Israel. Então eles ficarão sabendo que eu sou o Senhor .

[[v26-20-39]]

^<<v26-20-39,39>>^ O Senhor  Deus diz: — E agora todos vocês, israelitas, continuem a adorar os seus ídolos! Mas aviso que mais tarde terão de me obedecer e nunca mais desonrarão o meu nome, apresentando ofertas aos seus ídolos.

[[v26-20-40]]

^<<v26-20-40,40>>^ Lá na terra de Israel, no meu monte santo , no monte alto de Israel, todos vocês, povo de Israel, me adorarão. Ficarei contente com vocês e esperarei que me tragam os seus sacrifícios, as suas melhores ofertas e os seus presentes santos.

[[v26-20-41]]

^<<v26-20-41,41>>^ Eu farei com que voltem dos países onde estão espalhados, e os ajuntarei, e então aceitarei os sacrifícios que vocês queimam. E assim mostrarei às outras nações que eu sou santo.

[[v26-20-42]]

^<<v26-20-42,42>>^ Quando eu os trouxer de volta a Israel, à terra que prometi dar aos seus antepassados, vocês ficarão sabendo que eu sou o Senhor .

[[v26-20-43]]

^<<v26-20-43,43>>^ Então vocês lembrarão de todas as coisas vergonhosas que fizeram e de como se tornaram impuros . Ficarão com nojo de vocês mesmos, por causa de todas as coisas más que fizeram.

[[v26-20-44]]

^<<v26-20-44,44>>^ Vocês, israelitas, ficarão sabendo que eu sou o Senhor , pois não os trato como merecem por causa das suas ações más e perversas; mas o que faço é para proteger a minha honra. Eu, o Senhor  Deus, falei.

[[v26-20-45]]

^<<v26-20-45,45>>^ O Senhor  me disse o seguinte:

[[v26-20-46]]

^<<v26-20-46,46>>^ — Homem mortal , olhe para o Sul . Fale contra o Sul e profetize  contra a floresta do Sul.

[[v26-20-47]]

^<<v26-20-47,47>>^ Diga a essa floresta que escute, pois o Senhor  Deus está dizendo o seguinte: "Vejam! Estou acendendo um fogo que destruirá todas as árvores secas e todas as árvores verdes daí! Nada poderá apagar as chamas; elas se espalharão do Sul ao Norte e queimarão todos os rostos.

[[v26-20-48]]

^<<v26-20-48,48>>^ Todos verão que fui eu, o Senhor , que acendi esse fogo, fogo que ninguém pode apagar."

[[v26-20-49]]

^<<v26-20-49,49>>^ Eu respondi: — Ó Senhor , meu Deus, não me faça dizer essas coisas, pois todos estão dizendo que eu falo somente por meio de comparações.

'''

xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[&#60; Capítulo Anterior] | <<v26-20-0,Topo>> | xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[Próximo Capítulo &#62;]