include::./index.adoc[]

[[v26-36-0]]
=== Ezequiel, 36
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-36-1]]

^<<v26-36-1,1>>^ O Senhor  disse: — Homem mortal , fale com as montanhas de Israel e diga-lhes que escutem a mensagem que eu,

[[v26-36-2]]

^<<v26-36-2,2>>^ o Senhor  Deus, tenho para elas: "Os inimigos de Israel zombaram de vocês e disseram: Aquelas velhas montanhas são nossas!"

[[v26-36-3]]

^<<v26-36-3,3>>^ — Agora profetize  e anuncie aquilo que eu, o Senhor  Deus, estou dizendo. Quando as nações vizinhas tomaram as montanhas de Israel e roubaram o que havia nelas, todos zombaram dos israelitas.

[[v26-36-4]]

^<<v26-36-4,4>>^ Por isso, agora vocês, montanhas de Israel, ouçam o que eu, o Senhor  Deus, estou dizendo às montanhas e aos morros, aos ribeirões e aos vales, aos lugares arrasados e às cidades desertas que todas as nações vizinhas roubaram e de que zombaram.

[[v26-36-5]]

^<<v26-36-5,5>>^ — Eu, o Senhor  Deus, no calor da minha ira , falei contra essas nações vizinhas e especialmente contra Edom. Com alegria e com desprezo, elas tomaram a minha terra e ficaram com os seus pastos.

[[v26-36-6]]

^<<v26-36-6,6>>^ — Por isso, homem mortal, profetize a respeito da terra de Israel; diga às montanhas, morros, ribeirões e vales o que eu, o Senhor  Deus, estou dizendo com ira e ciúmes por causa da maneira como as nações zombaram deles.

[[v26-36-7]]

^<<v26-36-7,7>>^ — Eu, o Senhor  Deus, juro que as nações vizinhas de Israel cairão na desgraça.

[[v26-36-8]]

^<<v26-36-8,8>>^ Porém nas montanhas de Israel as árvores de novo terão folhas e produzirão frutas para vocês, meu povo de Israel. Logo vocês voltarão para a sua pátria.

[[v26-36-9]]

^<<v26-36-9,9>>^ Eu estou do lado de vocês. E garantirei que a sua terra será arada de novo para que nela sejam feitas plantações.

[[v26-36-10]]

^<<v26-36-10,10>>^ Farei aumentar a população. Vocês viverão nas cidades e construirão de novo tudo o que estava arrasado.

[[v26-36-11]]

^<<v26-36-11,11>>^ Farei com que haja muita gente e muito gado. Entre vocês haverá mais gente do que nunca, e vocês terão muitos filhos. Deixarei que vivam ali como antes e farei com que fiquem mais ricos do que nunca. Aí vocês ficarão sabendo que eu sou o Senhor .

[[v26-36-12]]

^<<v26-36-12,12>>^ Farei com que vocês, meu povo de Israel, vivam de novo na terra. Ela será a terra de vocês e nunca mais deixará que os seus filhos morram de fome.

[[v26-36-13]]

^<<v26-36-13,13>>^ — Eu, o Senhor  Deus, afirmo que, de fato, o povo chama a terra de Israel de "comedora de gente" e diz que ela rouba do país os seus filhos .

[[v26-36-14]]

^<<v26-36-14,14>>^ Mas, de agora em diante, ela não será mais a comedora de gente que rouba de vocês os seus filhos. Sou eu, o Senhor  Deus, quem está falando.

[[v26-36-15]]

^<<v26-36-15,15>>^ A terra não precisará mais de ouvir as nações zombarem, nem fazerem pouco caso dela. A terra não roubará mais do país os seus filhos. Eu, o Senhor  Deus, estou falando.

[[v26-36-16]]

^<<v26-36-16,16>>^ O Senhor  me disse o seguinte:

[[v26-36-17]]

^<<v26-36-17,17>>^ — Homem mortal , quando os israelitas viviam na sua terra, eles a tornaram impura  por causa da sua maneira de viver e de agir. O comportamento deles era tão impuro como a menstruação de uma mulher.

[[v26-36-18]]

^<<v26-36-18,18>>^ Eu os fiz sentir a força da minha ira , por causa dos crimes de morte que haviam cometido na terra e por causa dos ídolos com que eles a tornaram impura.

[[v26-36-19]]

^<<v26-36-19,19>>^ Eu os condenei pela sua maneira de viver e de agir e os espalhei por nações estrangeiras.

[[v26-36-20]]

^<<v26-36-20,20>>^ Mas, em todos os lugares aonde eles foram, só envergonharam o meu santo nome, pois as pessoas diziam: "Esse povo é de Deus, o Senhor , mas eles tiveram de sair da terra que ele mesmo lhes deu."

[[v26-36-21]]

^<<v26-36-21,21>>^ Aí eu me preocupei com o meu santo nome porque os israelitas o profanaram  em todos os lugares aonde foram.

[[v26-36-22]]

^<<v26-36-22,22>>^ — Por isso, dê aos israelitas esta mensagem que eu, o Senhor  Deus, tenho para eles: "O que vou fazer não é por amor de vocês, israelitas, mas por amor do meu santo nome, que vocês profanaram em todas as nações para onde foram.

[[v26-36-23]]

^<<v26-36-23,23>>^ Quando eu mostrar às nações a santidade do meu grande nome — o nome que vocês profanaram no meio deles —, aí eles ficarão sabendo que eu sou o Senhor . Sou eu, o Senhor  Deus, quem está falando. Usarei vocês para mostrar às nações que eu sou santo.

[[v26-36-24]]

^<<v26-36-24,24>>^ Eu os tirarei de todas as nações e países e os trarei de volta para a sua própria terra.

[[v26-36-25]]

^<<v26-36-25,25>>^ Borrifarei água limpa sobre vocês e os purificarei de todos os seus ídolos e de todas as coisas nojentas que vocês têm feito.

[[v26-36-26]]

^<<v26-36-26,26>>^ Eu lhes darei um coração novo e porei em vocês um espírito novo. Tirarei de vocês o coração de pedra, desobediente, e lhes darei um coração bondoso, obediente.

[[v26-36-27]]

^<<v26-36-27,27>>^ Porei o meu Espírito dentro de vocês e farei com que obedeçam às minhas leis  e cumpram todos os mandamentos que lhes dei.

[[v26-36-28]]

^<<v26-36-28,28>>^ Aí vocês viverão na terra que dei aos seus antepassados. Vocês serão o meu povo, e eu serei o seu Deus.

[[v26-36-29]]

^<<v26-36-29,29>>^ Eu os livrarei de todas as coisas que os tornam impuros. Darei ordem para que haja bastante trigo, e assim não haverá mais tempos de fome no meio de vocês.

[[v26-36-30]]

^<<v26-36-30,30>>^ Aumentarei a produção de frutas e das plantações de cereais, de modo que não haverá mais épocas de fome que façam vocês passarem vergonha no meio das outras nações.

[[v26-36-31]]

^<<v26-36-31,31>>^ Vocês lembrarão da sua má conduta e das maldades que cometeram e ficarão aborrecidos com vocês mesmos por causa dos seus pecados e maldades.

[[v26-36-32]]

^<<v26-36-32,32>>^ Povo de Israel, quero que saibam que eu não estou fazendo tudo isso por amor de vocês. Quero que vocês sintam como é vergonhoso e desonroso aquilo que estão fazendo. Eu, o Senhor  Deus, estou falando."

[[v26-36-33]]

^<<v26-36-33,33>>^ O Senhor  Deus diz: — No dia em que eu os purificar de todos os seus pecados, deixarei que construam de novo as suas cidades arrasadas e vivam nelas.

[[v26-36-34]]

^<<v26-36-34,34>>^ Todos os que passavam pelas lavouras de vocês viam que estavam abandonadas e que o capim havia crescido; mas eu deixarei que vocês façam plantações de novo.

[[v26-36-35]]

^<<v26-36-35,35>>^ Todos dirão isto a respeito desta terra: "Ela era um deserto, mas agora ficou igual ao jardim do Éden." Falarão também a respeito das cidades que foram roubadas, destruídas e arrasadas e que naquele tempo estarão cercadas por muralhas e habitadas.

[[v26-36-36]]

^<<v26-36-36,36>>^ Então as nações vizinhas que sobrarem ficarão sabendo que eu, o Senhor , construí de novo as cidades destruídas e fiz novas plantações nas terras abandonadas. Eu, o Senhor , disse que ia fazer isso e farei.

[[v26-36-37]]

^<<v26-36-37,37>>^ O Senhor  Deus diz: — Mais uma vez deixarei que os israelitas peçam a minha ajuda. Deixarei que cresçam em número como se fossem um rebanho de ovelhas.

[[v26-36-38]]

^<<v26-36-38,38>>^ As cidades que agora estão arrasadas ficarão tão cheias de gente como Jerusalém ficava cheia de ovelhas que eram oferecidas em sacrifício  num dia de festa. Aí eles ficarão sabendo que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]