include::./index.adoc[]

[[v26-19-0]]
=== Ezequiel, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-19-1]]

^<<v26-19-1,1>>^ O Senhor  Deus me mandou cantar uma canção de tristeza a respeito de dois reis de Israel:

[[v26-19-2]]

^<<v26-19-2,2>>^ Que leoa era a sua mãe ! Ela andava com o bando e criava os filhotes no meio dos leões.

[[v26-19-3]]

^<<v26-19-3,3>>^ Ela criou um filhote e o ensinou a caçar, e ele se tornou um devorador de gente.

[[v26-19-4]]

^<<v26-19-4,4>>^ As nações ouviram falar dele e o apanharam numa cova. Puseram uma argola no nariz dele e o arrastaram para o Egito.

[[v26-19-5]]

^<<v26-19-5,5>>^ A leoa viu que as suas esperanças estavam perdidas. Aí criou outro filhote , e ele se tornou um leão feroz.

[[v26-19-6]]

^<<v26-19-6,6>>^ Quando já estava crescido, andava com os outros leões. Aprendeu a caçar e se tornou um devorador de gente.

[[v26-19-7]]

^<<v26-19-7,7>>^ Destruiu fortalezas e arrasou cidades. Cada vez que ele rugia, o povo da sua terra tremia de medo.

[[v26-19-8]]

^<<v26-19-8,8>>^ Os povos se reuniram para combatê-lo; veio gente de todos os lados. Estenderam as suas redes de caça e o pegaram na armadilha.

[[v26-19-9]]

^<<v26-19-9,9>>^ Puseram uma argola no nariz dele e o puxaram para dentro de uma gaiola; então o levaram para o rei da Babilônia. Eles o deixaram preso para que nunca mais se ouvisse o seu rugido nos montes de Israel.

[[v26-19-10]]

^<<v26-19-10,10>>^ Israelitas, a mãe de vocês era como uma parreira plantada perto de um ribeirão. Ela estava cheia de galhos e produzia muitas uvas porque havia bastante água.

[[v26-19-11]]

^<<v26-19-11,11>>^ Os seus galhos eram fortes e cresceram até se tornarem cetros  reais. A parreira cresceu tanto, que os seus galhos chegaram até as nuvens; todos viram como era alta e cheia de galhos.

[[v26-19-12]]

^<<v26-19-12,12>>^ Porém mãos furiosas a arrancaram pela raiz e a jogaram no chão. O vento leste secou as suas uvas. Os seus galhos foram quebrados; eles secaram e foram queimados.

[[v26-19-13]]

^<<v26-19-13,13>>^ Agora, a parreira está plantada no deserto, numa terra seca e sem água.

[[v26-19-14]]

^<<v26-19-14,14>>^ O seu tronco pegou fogo; o fogo destruiu os seus galhos e as uvas. Os seus galhos nunca mais serão fortes, nunca mais serão cetros reais. Esta é uma canção de tristeza que tem sido cantada muitas vezes.

'''

xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]