include::./index.adoc[]

[[v26-37-0]]
=== Ezequiel, 37
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-37-1]]

^<<v26-37-1,1>>^ Eu senti a presença poderosa do Senhor , e o seu Espírito me levou e me pôs no meio de um vale onde a terra estava coberta de ossos.

[[v26-37-2]]

^<<v26-37-2,2>>^ Ele me levou para dar uma volta por todos os lugares do vale, e eu pude ver que havia muitos ossos, muitos mesmo, e estavam completamente secos.

[[v26-37-3]]

^<<v26-37-3,3>>^ Então o Senhor  me disse: — Homem mortal , será que esses ossos podem ter vida de novo? Eu respondi: — Senhor , meu Deus, só tu sabes se podem ou não.

[[v26-37-4]]

^<<v26-37-4,4>>^ Ele disse: — Profetize  para esses ossos. Diga a esses ossos secos que deem atenção à mensagem do Senhor .

[[v26-37-5]]

^<<v26-37-5,5>>^ Diga que eu, o Senhor  Deus, estou lhes dizendo isto: "Eu porei respiração dentro de vocês e os farei viver de novo.

[[v26-37-6]]

^<<v26-37-6,6>>^ Eu lhes darei tendões e músculos e os cobrirei de pele. Porei respiração dentro de vocês e os farei viver de novo. Aí vocês ficarão sabendo que eu sou o Senhor ."

[[v26-37-7]]

^<<v26-37-7,7>>^ Então profetizei conforme a ordem que eu havia recebido. Enquanto eu falava, ouvi um barulho. Eram os ossos se ajuntando uns com os outros, cada um no seu próprio lugar.

[[v26-37-8]]

^<<v26-37-8,8>>^ Enquanto eu olhava, os ossos se cobriram de tendões e músculos e depois de pele. Porém não havia respiração nos corpos.

[[v26-37-9]]

^<<v26-37-9,9>>^ Então o Senhor  me disse: — Homem mortal, profetize para o vento . Diga que o Senhor  Deus está mandando que ele venha de todas as direções para soprar sobre esses corpos mortos a fim de que vivam de novo.

[[v26-37-10]]

^<<v26-37-10,10>>^ Então profetizei conforme a ordem que eu havia recebido. A respiração entrou nos corpos, e eles viveram de novo e ficaram de pé. Havia tanta gente, que dava para formar um enorme exército.

[[v26-37-11]]

^<<v26-37-11,11>>^ O Senhor  me disse: — Homem mortal, o povo de Israel é como esses ossos. Dizem que estão secos, sem esperança e sem futuro.

[[v26-37-12]]

^<<v26-37-12,12>>^ Por isso, profetize para o meu povo de Israel e diga-lhes que eu, o Senhor  Deus, abrirei as sepulturas deles, e os tirarei para fora, e os levarei de volta para a terra de Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ Eu vou abrir os túmulos onde o meu povo está sepultado e vou tirá-los para fora; aí ficarão sabendo que eu sou o Senhor .

[[v26-37-14]]

^<<v26-37-14,14>>^ Porei a minha respiração neles, e os farei viver novamente, e os deixarei morar na sua própria terra. Aí ficarão sabendo que eu sou o Senhor . Prometi que faria isso e farei. Eu, o Senhor , falei.

[[v26-37-15]]

^<<v26-37-15,15>>^ O Senhor  falou outra vez comigo. Ele disse:

[[v26-37-16]]

^<<v26-37-16,16>>^ — Homem mortal , pegue uma tabuinha e escreva nela o seguinte: "O Reino de Judá, incluindo as pessoas do Reino de Israel que moram nele." Depois, pegue outra tabuinha e escreva: "O Reino de Israel, representado pela tribo  de Efraim e incluindo todos os outros israelitas que moram nele."

[[v26-37-17]]

^<<v26-37-17,17>>^ Então segure as duas tabuinhas juntas na sua mão de modo que pareçam uma só.

[[v26-37-18]]

^<<v26-37-18,18>>^ Quando o seu povo perguntar o que isso quer dizer,

[[v26-37-19]]

^<<v26-37-19,19>>^ diga que eu, o Senhor  Deus, pegarei a tabuinha que representa Israel e a colocarei junto com a que representa Judá. Das duas tabuinhas farei uma só e a segurarei na minha mão.

[[v26-37-20]]

^<<v26-37-20,20>>^ — Segure na mão as tabuinhas em que você escreveu e deixe que o povo as veja.

[[v26-37-21]]

^<<v26-37-21,21>>^ Então diga-lhes que eu, o Senhor  Deus, tirarei os israelitas do meio das nações para onde foram. Eu os ajuntarei e os levarei de volta à sua própria terra.

[[v26-37-22]]

^<<v26-37-22,22>>^ Farei deles uma só nação na sua terra, nas montanhas de Israel. Eles terão um só rei para governá-los e não serão mais divididos em duas nações, nem separados em dois reinos.

[[v26-37-23]]

^<<v26-37-23,23>>^ Não se mancharão mais com ídolos, nem com ações nojentas, nem com pecados de desobediência. Eu os livrarei de todas as suas maneiras de pecar e de me trair. Eu os purificarei, e eles serão o meu povo, e eu serei o seu Deus.

[[v26-37-24]]

^<<v26-37-24,24>>^ Um rei igual ao meu servo  Davi os governará. Todos terão um só governador e obedecerão fielmente às minhas leis .

[[v26-37-25]]

^<<v26-37-25,25>>^ Viverão na terra que dei ao meu servo Jacó, a terra em que os antepassados deles viveram. Viverão ali para sempre, eles, os seus filhos e todos os seus descendentes. Um rei igual ao meu servo Davi os governará para sempre.

[[v26-37-26]]

^<<v26-37-26,26>>^ Farei com eles uma aliança  que garantirá que viverão para sempre em segurança. Aumentarei a população e porei o meu Templo na terra deles, e ali ficará para sempre.

[[v26-37-27]]

^<<v26-37-27,27>>^ Viverei ali com eles e serei o Deus deles, e eles serão o meu povo.

[[v26-37-28]]

^<<v26-37-28,28>>^ Quando eu puser o meu Templo ali, para eu ficar no meio deles, as nações ficarão sabendo que eu, o Senhor , separei o povo de Israel para ser meu.

'''

xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]