include::./index.adoc[]

[[v26-11-0]]
=== Ezequiel, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-11-1]]

^<<v26-11-1,1>>^ Então o Espírito de Deus me levou pelo ar até o portão leste do Templo. Ali perto, estavam vinte e cinco homens. No meio deles, vi Jazanias, filho de Azur, e Pelatias, filho de Benaías. Os dois eram líderes do povo.

[[v26-11-2]]

^<<v26-11-2,2>>^ Deus me disse: — Homem mortal , são estes os dois homens que fazem planos de maldade e dão maus conselhos nesta cidade.

[[v26-11-3]]

^<<v26-11-3,3>>^ Eles dizem: "Logo vamos construir casas de novo. A cidade é uma panela, e nós somos como a carne lá dentro, mas pelo menos estamos protegidos do fogo."

[[v26-11-4]]

^<<v26-11-4,4>>^ Por isso, homem mortal, profetize  agora contra eles.

[[v26-11-5]]

^<<v26-11-5,5>>^ Aí o Espírito do Senhor  me dominou, e o Senhor  me mandou dar esta mensagem ao povo: — Povo de Israel, eu sei o que vocês estão falando e conheço os planos que estão fazendo.

[[v26-11-6]]

^<<v26-11-6,6>>^ Vocês têm assassinado tanta gente nesta cidade, que as ruas estão cheias de mortos.

[[v26-11-7]]

^<<v26-11-7,7>>^ — Portanto, eu, o Senhor  Deus, lhes digo isto: De fato, esta cidade é uma panela; mas a carne o que é? São os corpos das pessoas que vocês mataram! Mas eu expulsarei vocês da cidade.

[[v26-11-8]]

^<<v26-11-8,8>>^ Vocês têm medo de espadas? Pois trarei homens com espadas para atacá-los.

[[v26-11-9]]

^<<v26-11-9,9>>^ Levarei vocês para fora da cidade e os entregarei na mão de estrangeiros. Eu os condenei à morte,

[[v26-11-10]]

^<<v26-11-10,10>>^ e vocês serão mortos em batalha, no seu próprio país. Então todos ficarão sabendo que eu sou o Senhor .

[[v26-11-11]]

^<<v26-11-11,11>>^ A panela protege a carne, mas esta cidade não os protegerá. Eu os castigarei onde quer que estejam na terra de Israel.

[[v26-11-12]]

^<<v26-11-12,12>>^ Vocês saberão que eu sou o Senhor . Vocês guardaram as leis  das nações vizinhas e ao mesmo tempo quebraram as minhas leis e desobedeceram aos meus mandamentos.

[[v26-11-13]]

^<<v26-11-13,13>>^ Enquanto eu estava profetizando, Pelatias, filho de Benaías, caiu morto. Então me atirei no chão, com o rosto encostado na terra, e gritei: — Ó Senhor , meu Deus, isso não! Será que vais matar todos os israelitas que sobraram?

[[v26-11-14]]

^<<v26-11-14,14>>^ O Senhor  Deus falou comigo assim:

[[v26-11-15]]

^<<v26-11-15,15>>^ — Homem mortal , o povo que mora em Jerusalém está falando a respeito de você e dos seus patrícios, os israelitas que foram levados como prisioneiros para fora do seu país. Eles dizem: "Esses israelitas estão longe demais e não têm um lugar onde adorar o Senhor . Ele nos deu esta terra para ser nossa propriedade."

[[v26-11-16]]

^<<v26-11-16,16>>^ — Agora, vá falar com os seus patrícios que foram levados para fora do seu país e conte a eles o que eu estou dizendo. Fui eu que os mandei para longe, para o meio das outras nações, e os espalhei por outros países. Mas, por um pouco de tempo, nas terras para onde foram, eu mesmo fui para eles um santuário onde podiam me adorar.

[[v26-11-17]]

^<<v26-11-17,17>>^ — Por isso, diga-lhes o que eu, o Senhor  Deus, estou dizendo. Eu os buscarei dos países para onde os espalhei e lhes darei de novo a terra de Israel.

[[v26-11-18]]

^<<v26-11-18,18>>^ Quando voltarem para a sua terra, eles tirarão dela todos os ídolos e acabarão com todos os costumes imorais do povo.

[[v26-11-19]]

^<<v26-11-19,19>>^ Eu lhes darei um coração novo e uma nova mente. Tirarei deles o coração de pedra, desobediente, e lhes darei um coração humano, obediente.

[[v26-11-20]]

^<<v26-11-20,20>>^ Assim eles cumprirão as minhas leis  e obedecerão fielmente a todos os meus mandamentos. Eles serão o meu povo, e eu serei o Deus deles.

[[v26-11-21]]

^<<v26-11-21,21>>^ Mas castigarei os que gostam de adorar ídolos nojentos e de praticar atos imorais. Eu os castigarei pelo que têm feito. Eu, o Senhor  Deus, falei.

[[v26-11-22]]

^<<v26-11-22,22>>^ Os animais com asas começaram a voar, e as rodas foram com eles. A glória do Deus de Israel estava por cima deles.

[[v26-11-23]]

^<<v26-11-23,23>>^ Aí a glória do Senhor  se afastou da cidade e foi parar sobre o monte que está a leste dela.

[[v26-11-24]]

^<<v26-11-24,24>>^ Na visão, o Espírito de Deus me levantou e me levou de volta até a Babilônia, onde estavam os prisioneiros. Aí a visão acabou,

[[v26-11-25]]

^<<v26-11-25,25>>^ e eu contei aos que estavam no cativeiro  tudo o que o Senhor  me havia mostrado.

'''

xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]