include::./index.adoc[]

[[v26-9-0]]
=== Ezequiel, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-9-1]]

^<<v26-9-1,1>>^ Aí ouvi o Senhor  dizer em voz bem alta: — Venham cá vocês, os que vão castigar a cidade. Tragam as suas armas de destruição.

[[v26-9-2]]

^<<v26-9-2,2>>^ Naquele momento, seis homens vieram do Templo, do portão externo que fica ao norte, e cada um carregava uma arma mortal. Com eles estava um homem vestido com uma roupa de linho, que carregava material de escrever. Todos eles vieram e ficaram ao lado do altar de bronze.

[[v26-9-3]]

^<<v26-9-3,3>>^ Então a glória  do Deus de Israel, que estava em cima dos animais com asas , subiu dali e foi para a entrada do Templo. E o Senhor  gritou para o homem vestido com a roupa de linho:

[[v26-9-4]]

^<<v26-9-4,4>>^ — Vá por toda a cidade de Jerusalém e faça um sinal na testa de todas as pessoas que sofrem e se aborrecem por causa de todas as coisas vergonhosas que estão sendo feitas na cidade.

[[v26-9-5]]

^<<v26-9-5,5>>^ E ouvi o Senhor  dizer aos outros homens: — Vão atrás dele pela cidade e matem todos. Não deixem escapar ninguém; não tenham dó de ninguém.

[[v26-9-6]]

^<<v26-9-6,6>>^ Matem os velhos, os moços, as moças, as mães e as crianças. Mas não toquem em quem tiver o sinal na testa. Comecem aqui no meu Templo. Aí eles começaram a matar os líderes que estavam ali na frente do Templo.

[[v26-9-7]]

^<<v26-9-7,7>>^ O Senhor  lhes disse ainda: — Profanem  o Templo! Encham de cadáveres os pátios! Comecem o trabalho! Então eles começaram a matar as pessoas da cidade.

[[v26-9-8]]

^<<v26-9-8,8>>^ Enquanto a matança continuava, fiquei ali sozinho. Eu me atirei no chão, com o rosto encostado na terra, e gritei: — Senhor  Deus, será que estás tão zangado com Jerusalém, que vais matar todos os que foram deixados em Israel?

[[v26-9-9]]

^<<v26-9-9,9>>^ O Senhor  respondeu: — O povo de Israel e de Judá é culpado de pecados terríveis. Eles têm matado pessoas no país inteiro e têm enchido Jerusalém de crimes. Eles dizem: "O Senhor  abandonou o nosso país. O Senhor  não está vendo a gente."

[[v26-9-10]]

^<<v26-9-10,10>>^ Por isso, agora não deixarei escapar ninguém e não terei dó de ninguém. Farei com eles o que fizeram com os outros.

[[v26-9-11]]

^<<v26-9-11,11>>^ Então o homem que vestia a roupa de linho e carregava material de escrever voltou e contou tudo ao Senhor . E disse: — Fiz tudo como mandaste.

'''

xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[&#60; Capítulo Anterior] | <<v26-9-0,Topo>> | xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[Próximo Capítulo &#62;]