include::./index.adoc[]

[[v26-3-0]]
=== Ezequiel, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-3-1]]

^<<v26-3-1,1>>^ Deus disse: — Homem mortal , coma esse rolo; depois, vá e fale ao povo de Israel.

[[v26-3-2]]

^<<v26-3-2,2>>^ Então abri a boca, e ele me deu o rolo para comer.

[[v26-3-3]]

^<<v26-3-3,3>>^ E disse: — Homem mortal, coma esse rolo que lhe estou dando; encha o seu estômago com ele. Eu comi, e era doce como mel.

[[v26-3-4]]

^<<v26-3-4,4>>^ Então Deus disse: — Homem mortal, vá e diga ao povo de Israel o que eu ordenar.

[[v26-3-5]]

^<<v26-3-5,5>>^ Não estou enviando você a uma nação que fala uma língua estrangeira difícil, mas aos israelitas.

[[v26-3-6]]

^<<v26-3-6,6>>^ Se eu o enviasse a grandes nações que falam línguas difíceis que você não pudesse entender, elas dariam atenção a você.

[[v26-3-7]]

^<<v26-3-7,7>>^ Porém o povo de Israel não vai lhe dar atenção, pois eles não querem ouvir o que eu digo. Todos eles são teimosos e rebeldes.

[[v26-3-8]]

^<<v26-3-8,8>>^ Mas agora eu vou fazer com que você se torne tão teimoso e duro como eles.

[[v26-3-9]]

^<<v26-3-9,9>>^ Farei com que você fique tão forte como uma rocha e tão duro como um diamante. Por isso, não tenha medo, nem se assuste com esses rebeldes.

[[v26-3-10]]

^<<v26-3-10,10>>^ E Deus continuou: — Homem mortal, preste bem atenção e lembre tudo o que lhe estou dizendo.

[[v26-3-11]]

^<<v26-3-11,11>>^ Depois, vá falar com os seus patrícios que foram levados para o cativeiro . Diga-lhes o que eu, o Senhor  Deus, estou dizendo, tanto se lhe derem atenção como se não derem.

[[v26-3-12]]

^<<v26-3-12,12>>^ Então o Espírito de Deus me levou para o alto, e ouvi atrás de mim uma voz forte como um trovão. A voz gritava: — Louvem nos altos céus a glória  do Senhor !

[[v26-3-13]]

^<<v26-3-13,13>>^ Ouvi as asas dos animais batendo juntas no ar e também o barulho das rodas, que era tão forte como o de um trovão.

[[v26-3-14]]

^<<v26-3-14,14>>^ Aí o poder do Senhor  me dominou, e o seu Espírito me levou dali; aí eu fiquei zangado e cheio de amargura.

[[v26-3-15]]

^<<v26-3-15,15>>^ Então fui a Tel-Abibe, na beira do rio Quebar, onde estavam vivendo os judeus que haviam sido levados como prisioneiros. E fiquei ali sete dias, espantado com o que tinha visto e ouvido.

[[v26-3-16]]

^<<v26-3-16,16>>^ Depois desses sete dias, o Senhor  Deus falou comigo assim:

[[v26-3-17]]

^<<v26-3-17,17>>^ — Homem mortal , eu o estou pondo como vigia para a nação de Israel. Você entregará a eles os avisos que eu lhe der.

[[v26-3-18]]

^<<v26-3-18,18>>^ Se eu anunciar que um homem mau vai morrer, e você não avisar esse homem para que pare de fazer o mal e assim salve a sua vida, ele morrerá como pecador, e você será o responsável pela morte dele.

[[v26-3-19]]

^<<v26-3-19,19>>^ Se você avisar um homem mau, e ele não deixar de pecar, ele morrerá ainda pecador, mas você não morrerá.

[[v26-3-20]]

^<<v26-3-20,20>>^ — Se um homem direito começar a fazer o mal, e eu o puser em uma situação perigosa, ele morrerá se você não o avisar. Ele morrerá por causa dos pecados dele, e eu não lembrarei do bem que ele fez. E você será responsável pela morte dele.

[[v26-3-21]]

^<<v26-3-21,21>>^ Se você avisar um homem direito para que não peque, e, se ele der atenção a você e não pecar, então ele ficará vivo, e você também não morrerá.

[[v26-3-22]]

^<<v26-3-22,22>>^ Eu senti a presença poderosa do Senhor  Deus e o ouvi dizer o seguinte: — Levante-se e vá até o vale, que eu falarei com você ali.

[[v26-3-23]]

^<<v26-3-23,23>>^ Então fui até o vale e lá vi a glória  do Senhor , como já havia visto na beira do rio Quebar. Eu caí com o rosto no chão,

[[v26-3-24]]

^<<v26-3-24,24>>^ mas o Espírito de Deus entrou em mim e me pôs de pé. E Deus me disse: — Vá para casa e feche-se dentro dela.

[[v26-3-25]]

^<<v26-3-25,25>>^ Você, homem mortal , vai ser amarrado com cordas e não poderá sair.

[[v26-3-26]]

^<<v26-3-26,26>>^ Vou paralisar a sua língua, e você não poderá avisar essa gente rebelde.

[[v26-3-27]]

^<<v26-3-27,27>>^ Depois, quando eu falar de novo com você e lhe devolver a fala, você dirá a esse povo o que eu, o Senhor  Deus, disser. Alguns deles vão ouvir, mas outros não, porque são um povo rebelde.

'''

xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]