include::./index.adoc[]

[[v26-21-0]]
=== Ezequiel, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v26-21-1]]

^<<v26-21-1,1>>^ O Senhor  me disse o seguinte:

[[v26-21-2]]

^<<v26-21-2,2>>^ — Homem mortal , fale contra Jerusalém. Fale contra os lugares onde o povo adora. Avise a terra de Israel

[[v26-21-3]]

^<<v26-21-3,3>>^ que eu, o Senhor , estou dizendo isto: "Eu estou contra vocês. Vou tirar a minha espada e matar todos, tanto os bons como os maus.

[[v26-21-4]]

^<<v26-21-4,4>>^ Usarei a minha espada contra todos, do Sul ao Norte.

[[v26-21-5]]

^<<v26-21-5,5>>^ Todos ficarão sabendo que eu, o Senhor , tirei a minha espada da bainha e que não vou guardá-la."

[[v26-21-6]]

^<<v26-21-6,6>>^ — Homem mortal, fique gemendo como se o seu coração estivesse arrebentando de desespero. Vá para um lugar onde todos possam ver você e solte gemidos de tristeza.

[[v26-21-7]]

^<<v26-21-7,7>>^ Quando perguntarem por que você está gemendo, responda que é por causa daquilo que vai acontecer. Diga que eles perderão a coragem. Os corações deles ficarão cheios de medo, os braços ficarão moles e os joelhos tremerão. O tempo chegou; já está aqui. Eu, o Senhor  Deus, estou falando.

[[v26-21-8]]

^<<v26-21-8,8>>^ O Senhor  me disse o seguinte:

[[v26-21-9]]

^<<v26-21-9,9>>^ — Homem mortal, profetize . Diga ao povo que eu, o Senhor, estou dizendo isto: "A espada, a espada está afiada e brilhando.

[[v26-21-10]]

^<<v26-21-10,10>>^ Ela está afiada para matar e polida para brilhar como relâmpago. Não pode haver alegria, pois o meu povo rejeitou todos os conselhos e castigos.

[[v26-21-11]]

^<<v26-21-11,11>>^ A espada está sendo polida, está pronta para ser usada. Está afiada e polida para ser posta nas mãos de um matador.

[[v26-21-12]]

^<<v26-21-12,12>>^ Grite e solte gemidos, homem mortal; essa espada é para atacar o meu povo e todos os líderes de Israel. Eles serão mortos com todo o resto do meu povo. Bata no peito em sinal de desespero.

[[v26-21-13]]

^<<v26-21-13,13>>^ Estou pondo o meu povo à prova; se não quiserem se arrepender, todas essas coisas acontecerão a eles. Sou eu, o Senhor  Deus, quem está falando."

[[v26-21-14]]

^<<v26-21-14,14>>^ — Agora, homem mortal, profetize. Bata palmas, e a espada ferirá muitas vezes. É uma espada que mata, uma espada que produz terror e matança.

[[v26-21-15]]

^<<v26-21-15,15>>^ Ela faz o meu povo perder a coragem e tropeçar. Estou ameaçando a cidade deles com a espada que brilha como o relâmpago e que está pronta para matar.

[[v26-21-16]]

^<<v26-21-16,16>>^ Espada afiada, corte à direita e à esquerda! Corte em todos os lados para onde você virar.

[[v26-21-17]]

^<<v26-21-17,17>>^ Eu também baterei palmas, e a minha ira  passará. Eu, o Senhor , falei.

[[v26-21-18]]

^<<v26-21-18,18>>^ O Senhor  me disse o seguinte:

[[v26-21-19]]

^<<v26-21-19,19>>^ — Homem mortal , marque duas estradas por onde o rei da Babilônia poderá vir com a sua espada. As duas devem começar no mesmo país. Ponha placas indicando onde as estradas se dividem em duas.

[[v26-21-20]]

^<<v26-21-20,20>>^ Uma placa mostrará ao rei o caminho para a cidade amonita de Rabá, e a outra, para Jerusalém, a cidade cercada de muralhas, que fica em Judá.

[[v26-21-21]]

^<<v26-21-21,21>>^ O rei da Babilônia para na encruzilhada da estrada. E, a fim de saber que caminho tomar, ele sacode as flechas , faz perguntas aos seus deuses e examina o fígado de um animal que foi oferecido em sacrifício .

[[v26-21-22]]

^<<v26-21-22,22>>^ Agora, a sua mão direita está segurando a flecha marcada com a palavra "Jerusalém". É para o rei da Babilônia ir, soltar gritos de guerra, preparar máquinas de derrubar muralhas, colocá-las na frente dos portões e levantar rampas e torres de ataque.

[[v26-21-23]]

^<<v26-21-23,23>>^ O povo de Jerusalém não quer acreditar nisso por causa dos acordos  que eles fizeram. Mas esta profecia  é para fazer com que lembrem dos seus pecados, é um sinal de que serão presos.

[[v26-21-24]]

^<<v26-21-24,24>>^ Isso é o que eu, o Senhor  Deus, estou dizendo. Todos podem ver os seus pecados. Todo o mundo sabe o quanto vocês são culpados. Em cada ação que praticam, vocês mostram os seus pecados. Vocês estão condenados, e eu os entregarei aos seus inimigos.

[[v26-21-25]]

^<<v26-21-25,25>>^ — Você, governador de Israel , é perverso e não teme a Deus , e por isso o seu dia, o dia do seu castigo final, também está chegando.

[[v26-21-26]]

^<<v26-21-26,26>>^ A sua coroa e o seu turbante  serão tirados. As coisas não vão continuar como estão. Os pobres terão poder, e os que estão no poder serão rebaixados.

[[v26-21-27]]

^<<v26-21-27,27>>^ Destruição! Destruição! Sim! Destruirei a cidade. Mas isso não acontecerá até que venha aquele a quem vou entregar a cidade. Eu, o Senhor  Deus, falei.

[[v26-21-28]]

^<<v26-21-28,28>>^ — Homem mortal , profetize . Anuncie aquilo que eu, o Senhor  Deus, estou dizendo aos amonitas, que estão insultando o povo de Israel. Diga isto: "A espada está pronta para destruir; está polida para matar e para brilhar como o relâmpago."

[[v26-21-29]]

^<<v26-21-29,29>>^ — Amonitas, as suas visões são falsas, e as profecias que fazem são mentiras. Vocês são maus e perversos. O seu dia está chegando, o dia do seu castigo final. A espada cairá sobre o pescoço de vocês.

[[v26-21-30]]

^<<v26-21-30,30>>^ — Amonitas, ponham a sua espada na bainha. Eu os julgarei no lugar onde foram criados, na terra onde nasceram.

[[v26-21-31]]

^<<v26-21-31,31>>^ Quando a minha ira  cair sobre vocês, ela os queimará como labaredas de fogo. Eu os entregarei a homens violentos, preparados para destruir.

[[v26-21-32]]

^<<v26-21-32,32>>^ Vocês serão destruídos pelo fogo. O seu sangue será derramado no seu próprio país, e ninguém nunca mais lembrará de vocês. Eu, o Senhor , falei.

'''

xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]