include::./index.adoc[]

[[v61-3-0]]
=== 2 Pedro, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v61-3-1]]

^<<v61-3-1,1>>^ Meus queridos amigos, esta é a segunda carta que estou escrevendo a vocês. Nessas duas cartas, procuro despertar pensamentos puros na mente de vocês, fazendo com que lembrem dessas coisas.

[[v61-3-2]]

^<<v61-3-2,2>>^ Quero que lembrem das palavras ditas há muito tempo pelos santos profetas  e do mandamento do nosso Senhor e Salvador que foi dado a vocês por meio dos apóstolos  que anunciaram o evangelho  a vocês.

[[v61-3-3]]

^<<v61-3-3,3>>^ Primeiro vocês precisam saber que nos últimos dias vão aparecer homens dominados pelas suas próprias paixões. Eles vão zombar de vocês,

[[v61-3-4]]

^<<v61-3-4,4>>^ dizendo: "Ele prometeu vir, não foi? Onde está ele? Os nossos pais morreram, e tudo continua do mesmo jeito que era desde a criação do mundo."

[[v61-3-5]]

^<<v61-3-5,5>>^ Esses zombadores esquecem, de propósito, que há muito tempo Deus deu uma ordem, e os céus e a terra foram criados. Esquecem que a terra foi formada da água e no meio da água

[[v61-3-6]]

^<<v61-3-6,6>>^ e também que pela água do dilúvio o mundo antigo foi destruído.

[[v61-3-7]]

^<<v61-3-7,7>>^ Mas os céus e a terra que agora existem estão sendo guardados pela mesma ordem de Deus a fim de serem destruídos pelo fogo. Estão sendo guardados para o Dia do Julgamento e da destruição dos que não querem saber de Deus.

[[v61-3-8]]

^<<v61-3-8,8>>^ Meus queridos amigos, não esqueçam isto: para o Senhor um dia é como mil anos, e mil anos, como um dia.

[[v61-3-9]]

^<<v61-3-9,9>>^ O Senhor não demora a fazer o que prometeu, como alguns pensam. Pelo contrário, ele tem paciência com vocês porque não quer que ninguém seja destruído, mas deseja que todos se arrependam dos seus pecados.

[[v61-3-10]]

^<<v61-3-10,10>>^ Porém o Dia do Senhor chegará como um ladrão. Naquele dia os céus vão desaparecer com um barulho espantoso, e tudo o que há no Universo  será queimado. A terra e tudo o que existe nela vão sumir.

[[v61-3-11]]

^<<v61-3-11,11>>^ Sabendo que tudo isso vai ser destruído assim, então que tipo de gente vocês precisam ser? A vida de vocês deve ser agradável a Deus e dedicada a ele.

[[v61-3-12]]

^<<v61-3-12,12>>^ Esperem a vinda do Dia de Deus e façam o possível para que venha logo. Naquele dia os céus serão destruídos com fogo, e tudo o que há no Universo ficará derretido.

[[v61-3-13]]

^<<v61-3-13,13>>^ Porém Deus prometeu, e nós estamos esperando um novo céu e uma nova terra, onde tudo será feito de acordo com a vontade dele.

[[v61-3-14]]

^<<v61-3-14,14>>^ Por isso, meus amigos, enquanto vocês esperam aquele dia, façam o possível para estar em paz com Deus, sem mancha e sem culpa diante dele.

[[v61-3-15]]

^<<v61-3-15,15>>^ Lembrem que a paciência do nosso Senhor é uma oportunidade para vocês serem salvos. Pois o nosso querido irmão Paulo, com a sabedoria que Deus lhe deu, escreveu a vocês sobre esse assunto.

[[v61-3-16]]

^<<v61-3-16,16>>^ E foi isso mesmo que ele disse em todas as suas cartas quando escreveu a respeito disso. Nas cartas dele há algumas coisas difíceis de entender, que os ignorantes e os fracos na fé explicam de maneira errada, como fazem também com outras partes das Escrituras Sagradas . E assim eles causam a sua própria destruição.

[[v61-3-17]]

^<<v61-3-17,17>>^ Mas vocês, meus amigos, já sabem disso. Portanto, tomem cuidado para não serem levados pelos erros de pessoas imorais e para não caírem da sua posição segura.

[[v61-3-18]]

^<<v61-3-18,18>>^ Porém continuem a crescer na graça  e no conhecimento do nosso Senhor e Salvador Jesus Cristo. Glória  a ele, agora e para sempre! Amém !

'''

xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[Próximo Capítulo &#62;]