include::./index.adoc[]

[[v38-8-0]]
=== Zacarias, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-8-1]]

^<<v38-8-1,1>>^ O Senhor  Todo-Poderoso falou comigo e disse:

[[v38-8-2]]

^<<v38-8-2,2>>^ — Eu tenho um grande amor por Jerusalém, um amor que me faz ficar irado  contra os seus inimigos.

[[v38-8-3]]

^<<v38-8-3,3>>^ Eu voltarei para Jerusalém e ali morarei. Então Jerusalém será chamada de "Cidade Fiel", e o monte do Senhor  Todo-Poderoso será chamado de " Monte  Santo".

[[v38-8-4]]

^<<v38-8-4,4>>^ Mais uma vez, os velhinhos e as velhinhas, com as suas bengalas na mão, vão se sentar nas praças de Jerusalém.

[[v38-8-5]]

^<<v38-8-5,5>>^ E as praças ficarão cheias de meninos e meninas brincando.

[[v38-8-6]]

^<<v38-8-6,6>>^ Isso pode parecer impossível aos que voltaram do cativeiro  na Babilônia, mas não é impossível para mim, o Senhor  Todo-Poderoso.

[[v38-8-7]]

^<<v38-8-7,7>>^ Vou salvar o meu povo; eu os tirarei dos países do Leste e do Oeste, para onde foram levados como prisioneiros,

[[v38-8-8]]

^<<v38-8-8,8>>^ e os trarei de volta para Jerusalém, onde ficarão morando. Eles serão o meu povo, e eu serei o seu Deus e os governarei com justiça e fidelidade.

[[v38-8-9]]

^<<v38-8-9,9>>^ O Senhor  Todo-Poderoso diz: — Portanto, tenham coragem, todos os que estão ouvindo agora o mesmo que os profetas  disseram quando se começou a reconstrução do Templo do Senhor  Todo-Poderoso e foram colocados os seus alicerces.

[[v38-8-10]]

^<<v38-8-10,10>>^ Pois até aquele tempo não havia dinheiro para pagar os trabalhadores, e os animais de carga não rendiam dinheiro para os seus donos. Havia tantos inimigos, que ninguém vivia seguro, pois eu fiz com que todos fossem inimigos uns dos outros.

[[v38-8-11]]

^<<v38-8-11,11>>^ Mas eu, o Senhor  Todo-Poderoso, prometo que agora não vou tratar os que restam deste povo como fiz no passado.

[[v38-8-12]]

^<<v38-8-12,12>>^ Eles semearão as suas terras em paz; as parreiras  darão uvas, a terra dará boas colheitas, e cairá chuva do céu. Darei tudo isso aos que restarem do meu povo.

[[v38-8-13]]

^<<v38-8-13,13>>^ Moradores de Judá e de Israel! No passado os povos de outras nações maldiziam uns aos outros assim: "Que Deus os castigue como castigou o povo de Judá e de Israel!" Mas eu vou salvar vocês, e no futuro aqueles mesmos povos dirão uns aos outros: "Que Deus os abençoe como abençoou o povo de Judá e de Israel!" Não fiquem com medo! Tenham coragem!

[[v38-8-14]]

^<<v38-8-14,14>>^ O Senhor  Todo-Poderoso diz ao povo: — Quando os seus antepassados me fizeram ficar irado, eu os castiguei, como havia resolvido antes. Não mudei de ideia.

[[v38-8-15]]

^<<v38-8-15,15>>^ E agora resolvi abençoar o povo de Jerusalém e de Judá e não vou mudar de ideia. Portanto, não fiquem com medo.

[[v38-8-16]]

^<<v38-8-16,16>>^ São estas as coisas que vocês devem fazer: digam todos a verdade uns aos outros e decidam com justiça os casos nos tribunais a fim de que haja paz.

[[v38-8-17]]

^<<v38-8-17,17>>^ Porém não façam planos para prejudicar uns aos outros e não jurem falso, pois eu, o Senhor , odeio tudo isso.

[[v38-8-18]]

^<<v38-8-18,18>>^ O Senhor  Todo-Poderoso falou comigo e disse:

[[v38-8-19]]

^<<v38-8-19,19>>^ — Os jejuns do quarto, quinto, sétimo e décimo meses de cada ano vão virar dias de alegria, dias de festa para o povo de Judá. Portanto, amem a verdade e a paz.

[[v38-8-20]]

^<<v38-8-20,20>>^ O Senhor  Todo-Poderoso diz: — Vai chegar o dia em que moradores de muitas cidades virão até Jerusalém.

[[v38-8-21]]

^<<v38-8-21,21>>^ Os moradores de uma cidade dirão aos de outra cidade: "Nós vamos adorar o Senhor  Todo-Poderoso e pedir que ele nos abençoe!" E os outros responderão: "Pois nós vamos com vocês!"

[[v38-8-22]]

^<<v38-8-22,22>>^ Muitos povos e nações poderosas virão a Jerusalém para adorar o Senhor  Todo-Poderoso e pedirem que ele os abençoe.

[[v38-8-23]]

^<<v38-8-23,23>>^ Naqueles dias, dez estrangeiros irão agarrar um judeu para lhe dizer: "Nós queremos seguir a sua religião, pois ouvimos dizer que Deus está com vocês."

'''

xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[Próximo Capítulo &#62;]