include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-2-1]]

^<<v38-2-1,1>>^ Tive ainda outra visão. Vi um homem segurando uma fita de medir

[[v38-2-2]]

^<<v38-2-2,2>>^ e perguntei: — Aonde você vai? Ele respondeu: — Vou medir Jerusalém para saber o seu comprimento e a sua largura.

[[v38-2-3]]

^<<v38-2-3,3>>^ Então vi que o anjo que havia falado comigo ia saindo. Nisso, outro anjo veio se encontrar com ele,

[[v38-2-4]]

^<<v38-2-4,4>>^ e o primeiro anjo disse: — Corra depressa e diga ao rapaz que está com a fita de medir: "Jerusalém terá moradores de novo, e haverá tantas pessoas e tantos animais morando lá, que não será possível construir uma muralha em volta da cidade.

[[v38-2-5]]

^<<v38-2-5,5>>^ Pois o Senhor  Deus promete que ele mesmo será como uma muralha de fogo em volta de Jerusalém e que ele morará na cidade e ali mostrará a sua glória ."

[[v38-2-6]]

^<<v38-2-6,6>>^ O Senhor  Deus diz ao seu povo: — Atenção! Atenção! Vocês que são prisioneiros na Babilônia, fujam. Fujam daquele país do Norte! Eu os espalhei por toda parte, mas agora é hora de vocês voltarem para Jerusalém.

[[v38-2-7]]

^<<v38-2-7,7>>^ O Senhor  Deus diz ao seu povo:

[[v38-2-8]]

^<<v38-2-8,8>>^ Pelo seu poder, o Senhor  Todo-Poderoso me mandou entregar a seguinte mensagem às nações que tinham levado embora toda a riqueza do seu povo: — Quem toca no meu povo toca na menina dos meus olhos.

[[v38-2-9]]

^<<v38-2-9,9>>^ Portanto, eu mesmo lutarei contra vocês. E toda a sua riqueza será levada embora por aqueles que antes eram seus prisioneiros. Quando isso acontecer, o povo saberá que o Senhor  Todo-Poderoso me enviou.

[[v38-2-10]]

^<<v38-2-10,10>>^ O Senhor  Deus diz: — Moradores de Jerusalém, cantem de alegria, pois eu virei morar com vocês!

[[v38-2-11]]

^<<v38-2-11,11>>^ Naquele dia, muitos povos se juntarão a Deus, o Senhor , e serão o seu povo, e ele morará com eles. Aí o povo de Israel saberá que o Senhor  Todo-Poderoso me enviou para falar com eles.

[[v38-2-12]]

^<<v38-2-12,12>>^ Mais uma vez a terra de Judá será a parte especial de Deus na Terra Santa, e Jerusalém será de novo a sua cidade escolhida.

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]