include::./index.adoc[]

[[v38-11-0]]
=== Zacarias, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-11-1]]

^<<v38-11-1,1>>^ Líbano, abra as suas portas para que o fogo acabe com os seus cedros .

[[v38-11-2]]

^<<v38-11-2,2>>^ Chorem, pinheiros, pois os cedros caíram! Aquelas belas árvores foram destruídas! Chorem, carvalhos de Basã, pois a mata virgem foi derrubada!

[[v38-11-3]]

^<<v38-11-3,3>>^ Os pastores gemem e choram, pois os belos pastos foram destruídos. Os leões estão rugindo porque as matas do rio Jordão foram derrubadas.

[[v38-11-4]]

^<<v38-11-4,4>>^ O Senhor , meu Deus, me disse: — Seja um pastor e tome conta das ovelhas que vão ser mortas.

[[v38-11-5]]

^<<v38-11-5,5>>^ Aqueles que compram as ovelhas não são castigados quando as matam e, depois que vendem a carne, dizem: "Graças a Deus! Ficamos ricos!" Nem mesmo os próprios pastores daquelas ovelhas têm pena delas.

[[v38-11-6]]

^<<v38-11-6,6>>^ Também eu não tenho mais compaixão dos moradores de Israel. Vou entregar todos nas mãos dos seus chefes e dos seus reis. Estes arrasarão o país, e eu não livrarei ninguém do poder deles. Eu, o Senhor , estou falando.

[[v38-11-7]]

^<<v38-11-7,7>>^ Portanto, eu fui contratado pelos que compram e vendem ovelhas para cuidar das que iam ser mortas. Peguei dois bordões: um eu chamei de "Bondade" e o outro, de "União". E fiquei tomando conta do rebanho.

[[v38-11-8]]

^<<v38-11-8,8>>^ Em um mês acabei com os três pastores, mas perdi a paciência com as ovelhas, e elas ficaram aborrecidas comigo.

[[v38-11-9]]

^<<v38-11-9,9>>^ Então eu disse a elas: — Eu não serei mais o pastor de vocês. Que morram as que vão morrer! Que sejam mortas as que vão ser mortas! E que as que sobrarem comam umas as outras!

[[v38-11-10]]

^<<v38-11-10,10>>^ Depois, peguei o bastão chamado "Bondade" e o quebrei como sinal de que Deus tinha quebrado a aliança  que havia feito com todos os povos.

[[v38-11-11]]

^<<v38-11-11,11>>^ Portanto, a aliança foi desfeita naquele dia. Aí os negociantes de ovelhas, que estavam me espiando, entenderam que o Senhor  estava falando por meio daquilo que eu fazia.

[[v38-11-12]]

^<<v38-11-12,12>>^ Então eu lhes disse: — Se estiverem satisfeitos, paguem o meu salário; se não, não paguem. E eles me pagaram trinta barras de prata .

[[v38-11-13]]

^<<v38-11-13,13>>^ O Senhor  Deus me disse: — Ponha este dinheiro no tesouro do Templo. Peguei o dinheiro — o ótimo salário que eles achavam que eu merecia — e pus no tesouro do Templo.

[[v38-11-14]]

^<<v38-11-14,14>>^ Depois, quebrei o segundo bastão, chamado "União", como sinal de que estava desfeita a união de irmãos que havia entre Judá e Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ Em seguida, o Senhor  me disse: — Agora, faça o papel de um pastor que não presta.

[[v38-11-16]]

^<<v38-11-16,16>>^ Pois vou pôr um pastor para cuidar do meu rebanho, mas ele não vai se preocupar com as ovelhas que estiverem em perigo, não vai procurar as que se perderem, não vai tratar das que se machucarem, nem vai cuidar das que estiverem cansadas. Pelo contrário, ele comerá a carne das mais gordas e não deixará nem mesmo os cascos!

[[v38-11-17]]

^<<v38-11-17,17>>^ Ai do mau pastor, que abandona o rebanho! Que um dos seus braços e o seu olho direito sejam feridos pela espada! Que o braço fique paralisado, e o olho fique cego!

'''

xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[Próximo Capítulo &#62;]