include::./index.adoc[]

[[v38-7-0]]
=== Zacarias, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-7-1]]

^<<v38-7-1,1>>^ No dia quatro do mês nove, chamado quisleu , do quarto ano do reinado de Dario, o Senhor  Deus me deu uma mensagem.

[[v38-7-2]]

^<<v38-7-2,2>>^ Isso aconteceu quando o povo de Betel enviou Sarezer e Regém-Meleque, com os seus companheiros, ao Templo do Senhor  Todo-Poderoso para pedirem a ajuda dele.

[[v38-7-3]]

^<<v38-7-3,3>>^ E deviam também fazer aos sacerdotes do Templo e aos profetas  a seguinte pergunta: — Faz muitos anos que nós choramos e jejuamos no quinto mês, o mês em que o Templo foi destruído. Devemos continuar fazendo isso?

[[v38-7-4]]

^<<v38-7-4,4>>^ Então o Senhor  Todo-Poderoso falou comigo

[[v38-7-5]]

^<<v38-7-5,5>>^ e mandou que eu dissesse o seguinte ao povo e aos sacerdotes: — Já faz setenta anos que vocês choram e jejuam no quinto mês e também no sétimo. Mas não é em minha honra que vocês fazem isso.

[[v38-7-6]]

^<<v38-7-6,6>>^ E, quando comem e bebem, é só para satisfazer os seus próprios desejos.

[[v38-7-7]]

^<<v38-7-7,7>>^ Essa mensagem foi a mesma que o Senhor  Deus tinha dado antes por meio dos profetas antigos, quando Jerusalém estava em paz e tinha muitos moradores. E o mesmo acontecia nas cidades ao redor e nas cidades da região sul e nas planícies de Judá.

[[v38-7-8]]

^<<v38-7-8,8>>^ O Senhor  Deus falou com Zacarias e disse:

[[v38-7-9]]

^<<v38-7-9,9>>^ — Eu, o Senhor  Todo-Poderoso, tinha ordenado isto ao povo: "Sejam honestos e corretos e tratem uns aos outros com bondade e compaixão.

[[v38-7-10]]

^<<v38-7-10,10>>^ Não explorem as viúvas, nem os órfãos, nem os estrangeiros que moram com vocês, nem os pobres. E não façam planos para prejudicar os seus patrícios."

[[v38-7-11]]

^<<v38-7-11,11>>^ Porém eles se revoltaram e não quiseram obedecer. Viraram as costas para mim e taparam os ouvidos para não ouvir as minhas ordens.

[[v38-7-12]]

^<<v38-7-12,12>>^ Tornaram os corações deles duros como o diamante a fim de não obedecer à Lei  e às mensagens que eu, por meio do meu Espírito, dei aos profetas antigos. Por isso, eu fiquei muito irado  com eles.

[[v38-7-13]]

^<<v38-7-13,13>>^ E assim como eles não quiseram ouvir quando eu falei, assim também eu não vou escutar quando eles orarem a mim. Sou eu, o Senhor  Todo-Poderoso, quem está falando.

[[v38-7-14]]

^<<v38-7-14,14>>^ Como um furacão, eu os espalhei por todos os países estrangeiros, e a terra de onde saíram ficou tão arrasada, que ninguém podia viver lá. Uma terra tão boa e tão rica virou um deserto!

'''

xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[Próximo Capítulo &#62;]