include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-6-1]]

^<<v38-6-1,1>>^ Tive mais uma visão. Vi dois montes feitos de bronze, e do meio deles estavam saindo quatro carros de guerra.

[[v38-6-2]]

^<<v38-6-2,2>>^ O primeiro carro era puxado por cavalos vermelhos; o segundo, por cavalos pretos;

[[v38-6-3]]

^<<v38-6-3,3>>^ o terceiro, por cavalos brancos; e o quarto, por cavalos baios.

[[v38-6-4]]

^<<v38-6-4,4>>^ Perguntei ao anjo: — Meu senhor, o que são estes carros de guerra?

[[v38-6-5]]

^<<v38-6-5,5>>^ Ele respondeu: — São os quatro ventos, que estão saindo da presença do Senhor do mundo inteiro.

[[v38-6-6]]

^<<v38-6-6,6>>^ O carro puxado pelos cavalos pretos vai para a Babilônia, a terra do Norte; o carro puxado pelos cavalos brancos vai para a terra do Oeste; e o carro puxado pelos cavalos baios vai para a terra do Sul.

[[v38-6-7]]

^<<v38-6-7,7>>^ Os cavalos baios saíram, com vontade de correr pelo mundo inteiro. Então o anjo ordenou: — Vão e corram pelo mundo inteiro! E eles fizeram isso.

[[v38-6-8]]

^<<v38-6-8,8>>^ Aí o anjo me chamou e disse: — Os cavalos que foram para a terra do Norte vão fazer parar a ira  do Senhor  contra aquele país.

[[v38-6-9]]

^<<v38-6-9,9>>^ O Senhor  Deus falou comigo. Ele disse:

[[v38-6-10]]

^<<v38-6-10,10>>^ — Vá receber as ofertas feitas por Heldai, Tobias e Jedaías, que voltaram do cativeiro  na Babilônia. Depois, vá logo até a casa de Josias, filho de Sofonias,

[[v38-6-11]]

^<<v38-6-11,11>>^ com a prata e o ouro que você tiver recebido e faça uma coroa. Coloque a coroa na cabeça do Grande Sacerdote  Josué, filho de Jozadaque.

[[v38-6-12]]

^<<v38-6-12,12>>^ E diga a ele que o Senhor  Todo-Poderoso promete o seguinte: "O homem chamado de ‘Ramo Novo’ brotará das suas próprias raízes e construirá de novo o Templo do Senhor .

[[v38-6-13]]

^<<v38-6-13,13>>^ É ele que vai reconstruir o Templo e receber as honrarias que pertencem a um rei. Ele vai sentar no seu trono e reinar. Um sacerdote se sentará no seu próprio trono, e haverá uma paz perfeita entre ‘O Ramo Novo’ e esse sacerdote."

[[v38-6-14]]

^<<v38-6-14,14>>^ Mas depois a coroa será colocada no Templo do Senhor  em memória de Heldai, de Tobias, de Jedaías e de Josias, filho de Sofonias.

[[v38-6-15]]

^<<v38-6-15,15>>^ Pessoas que moram longe de Jerusalém virão ajudar a construir de novo o Templo do Senhor . Aí vocês saberão que o Senhor  Todo-Poderoso me enviou a vocês. Tudo isso acontecerá se obedecerem com todo o coração às leis  do Senhor , o Deus de vocês.

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]