include::./index.adoc[]

[[v38-9-0]]
=== Zacarias, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-9-1]]

^<<v38-9-1,1>>^ Esta é a mensagem de Deus, o Senhor : ele anuncia que a terra de Hadraque e a cidade de Damasco serão castigadas. Tanto as cidades da Síria como as tribos  de Israel são do Senhor .

[[v38-9-2]]

^<<v38-9-2,2>>^ A cidade de Hamate, que fica perto daquelas cidades, também é do Senhor , e as cidades de Tiro e de Sidom, com toda a sua cultura, também são dele.

[[v38-9-3]]

^<<v38-9-3,3>>^ O povo de Tiro construiu fortalezas para se proteger e amontoou tanta prata como se fosse pó e tanto ouro como se fosse lama.

[[v38-9-4]]

^<<v38-9-4,4>>^ Mas o Senhor vai levar tudo embora; ele jogará no mar as riquezas de Tiro, e a cidade será destruída por um incêndio.

[[v38-9-5]]

^<<v38-9-5,5>>^ Quando os moradores da cidade de Asquelom souberem disso, ficarão com medo. O povo de Gaza também vai sofrer muito, e o povo de Ecrom perderá toda a esperança. O rei de Gaza morrerá, e Asquelom ficará sem moradores.

[[v38-9-6]]

^<<v38-9-6,6>>^ Mestiços morarão em Asdode. O Senhor  diz: — Eu vou humilhar esses filisteus orgulhosos.

[[v38-9-7]]

^<<v38-9-7,7>>^ Não vou deixar que comam carne com sangue nem qualquer outra comida impura . Os que sobrarem desse povo serão meus e farão parte da tribo de Judá. Os moradores de Ecrom também farão parte do meu povo, como aconteceu com os jebuseus .

[[v38-9-8]]

^<<v38-9-8,8>>^ Vou defender o meu povo dos seus inimigos e não vou deixar que os exércitos deles invadam a minha terra. Nunca mais haverá um chefe cruel dominando o meu povo, pois eu tenho visto como tem sofrido.

[[v38-9-9]]

^<<v38-9-9,9>>^ Alegre-se muito, povo de Sião ! Moradores de Jerusalém, cantem de alegria, pois o seu rei está chegando. Ele vem triunfante e vitorioso; mas é humilde, e está montado num jumento, num jumentinho, filho de jumenta.

[[v38-9-10]]

^<<v38-9-10,10>>^ Ele acabará com os carros de guerra de Israel e com a cavalaria de Jerusalém; os arcos e as flechas serão destruídos. Ele fará com que as nações vivam em paz; o seu reino irá de um mar a outro, e desde o rio Eufrates até os fins da terra.

[[v38-9-11]]

^<<v38-9-11,11>>^ O Senhor  Deus diz: "Moradores de Jerusalém, eu fiz uma aliança  com vocês, que foi selada  com sangue. Por isso, vou tirar o seu povo do cativeiro , daquele poço sem água.

[[v38-9-12]]

^<<v38-9-12,12>>^ Prisioneiros, voltem para a sua fortaleza; voltem todos os que ainda têm esperança. Pois vou lhes dar duas vezes mais bênçãos do que os castigos que vocês receberam.

[[v38-9-13]]

^<<v38-9-13,13>>^ Vou usar Judá como arco de guerra, e o povo de Israel será as flechas. Os homens de Jerusalém serão a minha espada, e com ela vou fazer guerra contra a Grécia."

[[v38-9-14]]

^<<v38-9-14,14>>^ O Senhor  aparecerá sobre o seu povo e atirará as suas flechas como se fossem relâmpagos. O Senhor  tocará a corneta e avançará no meio das tempestades do Sul.

[[v38-9-15]]

^<<v38-9-15,15>>^ O Senhor  Todo-Poderoso protegerá o seu povo; eles derrotarão os soldados inimigos e destruirão as suas armas; beberão o sangue dos inimigos como se fosse vinho e ficarão cheios como uma taça de vinho quando é derramado em cima do altar.

[[v38-9-16]]

^<<v38-9-16,16>>^ Naquele dia, o Senhor  salvará o seu povo como um pastor salva as suas ovelhas; eles brilharão no seu país como pedras preciosas numa coroa.

[[v38-9-17]]

^<<v38-9-17,17>>^ Como será bom e belo esse país! Haverá trigo e vinho com fartura, e os moços e as moças crescerão fortes e bonitos.

'''

xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[&#60; Capítulo Anterior] | <<v38-9-0,Topo>> | xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[Próximo Capítulo &#62;]