include::./index.adoc[]

[[v38-13-0]]
=== Zacarias, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-13-1]]

^<<v38-13-1,1>>^ — Naquele dia, haverá uma fonte jorrando água, e ali os descendentes de Davi e os outros moradores de Jerusalém poderão se lavar de todos os pecados e de todas as impurezas.

[[v38-13-2]]

^<<v38-13-2,2>>^ E no mesmo dia eu, o Senhor  Todo-Poderoso, farei desaparecer da terra de Israel os nomes dos ídolos, e ninguém lembrará mais deles. Também tirarei do país todos os falsos profetas  e acabarei com a vontade que o povo tem de adorar ídolos.

[[v38-13-3]]

^<<v38-13-3,3>>^ Quando alguém quiser fazer profecias , os próprios pais lhe dirão: "Você vai morrer, pois está dizendo que as suas mentiras são mensagens de Deus, o Senhor !" E os pais matarão o filho à espada quando ele estiver bancando o profeta!

[[v38-13-4]]

^<<v38-13-4,4>>^ Naquele dia, qualquer um que profetizar  terá vergonha da sua visão. Ninguém vestirá uma capa  de peles de animais para fingir que é profeta.

[[v38-13-5]]

^<<v38-13-5,5>>^ Pelo contrário, cada um dirá: "Eu não sou profeta; sou lavrador. Desde criança trabalho na roça."

[[v38-13-6]]

^<<v38-13-6,6>>^ E, se alguém perguntar: "Que ferimentos são esses no seu peito?", ele responderá: "São os ferimentos que recebi na casa dos meus amigos."

[[v38-13-7]]

^<<v38-13-7,7>>^ O Senhor  Todo-Poderoso diz: "Levante-se, espada, e ataque o meu pastor ! Ataque o meu ajudante! Mate o pastor, e as ovelhas serão espalhadas; e eu mesmo atacarei os carneirinhos.

[[v38-13-8]]

^<<v38-13-8,8>>^ Dos moradores de Israel, dois terços morrerão; só um terço sobrará com vida.

[[v38-13-9]]

^<<v38-13-9,9>>^ E estes que sobrarem eu farei passar pelo fogo. Eu os purificarei  como se purifica a prata e os refinarei como se refina o ouro. Aí eles orarão a mim, e eu os atenderei. Direi: ‘Vocês são o meu povo’, e eles responderão: ‘O Senhor  é o nosso Deus.’ "

'''

xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[Próximo Capítulo &#62;]