include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-4-1]]

^<<v38-4-1,1>>^ O anjo que havia falado comigo voltou e me acordou, como se acorda alguém que está dormindo.

[[v38-4-2]]

^<<v38-4-2,2>>^ Ele me perguntou: — O que é que você está vendo? Respondi: — Estou vendo um candelabro  de ouro e em cima dele um vaso para o azeite; há sete lamparinas no candelabro, e há sete tubos por onde o azeite chega até as lamparinas.

[[v38-4-3]]

^<<v38-4-3,3>>^ Perto do candelabro, estou vendo duas oliveiras, uma de cada lado.

[[v38-4-4]]

^<<v38-4-4,4>>^ Aí perguntei ao anjo: — Meu senhor, o que quer dizer isso?

[[v38-4-5]]

^<<v38-4-5,5>>^ — Você não sabe? — ele perguntou. — Não, senhor! — respondi.

[[v38-4-6]]

^<<v38-4-6,6>>^ Depois disso, o anjo mandou que eu entregasse a Zorobabel a seguinte mensagem de Deus, o Senhor : — Não será por meio de um poderoso exército nem pela sua própria força que você fará o que tem de fazer, mas pelo poder do meu Espírito. Sou eu, o Senhor  Todo-Poderoso, quem está falando.

[[v38-4-7]]

^<<v38-4-7,7>>^ — Diante de Zorobabel, altas montanhas vão virar campos planos. Ele vai trazer a pedra mais importante do Templo, e o povo vai gritar: "Que beleza! Que beleza!"

[[v38-4-8]]

^<<v38-4-8,8>>^ O Senhor  falou comigo mais uma vez.

[[v38-4-9]]

^<<v38-4-9,9>>^ Ele disse: — Zorobabel pôs o alicerce deste Templo e ele mesmo vai terminar a construção. Quando isso acontecer, o povo saberá que eu, o Senhor  Todo-Poderoso, enviei você para falar a eles.

[[v38-4-10]]

^<<v38-4-10,10>>^ E os que não deram valor a um começo tão humilde vão ficar alegres quando virem Zorobabel terminando a construção do Templo. — As sete lamparinas representam os sete olhos do Senhor  Deus, que veem tudo o que se passa no mundo inteiro.

[[v38-4-11]]

^<<v38-4-11,11>>^ Aí eu perguntei: — E o que querem dizer as duas oliveiras, uma de cada lado do candelabro?

[[v38-4-12]]

^<<v38-4-12,12>>^ E perguntei também: — E o que querem dizer os dois ramos da oliveira, que estão perto dos dois tubos de ouro por onde passa o azeite?

[[v38-4-13]]

^<<v38-4-13,13>>^ — E você não sabe? — ele perguntou. — Não, senhor! — respondi.

[[v38-4-14]]

^<<v38-4-14,14>>^ Então ele explicou: — Eles representam os dois homens que foram escolhidos e ungidos  para servir o Senhor do mundo inteiro.

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]