include::./index.adoc[]

[[v38-14-0]]
=== Zacarias, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-14-1]]

^<<v38-14-1,1>>^ Está chegando o dia em que o Senhor  Deus julgará as nações. Então a cidade de Jerusalém será conquistada, e os inimigos repartirão entre si tudo o que encontrarem nela.

[[v38-14-2]]

^<<v38-14-2,2>>^ O Senhor  ajuntará todas as nações para atacarem Jerusalém. A cidade será conquistada, tudo o que estiver nas casas será levado embora, as mulheres serão violentadas, e metade dos moradores será levada para o cativeiro . Os outros poderão ficar em Jerusalém.

[[v38-14-3]]

^<<v38-14-3,3>>^ Depois, o Senhor  sairá para lutar contra essas nações, como já lutou no passado.

[[v38-14-4]]

^<<v38-14-4,4>>^ Naquele dia, ele ficará de pé no monte das Oliveiras, a leste de Jerusalém. Então um grande vale, que correrá do leste para o oeste, dividirá o monte das Oliveiras em dois. Metade do monte se afastará para o norte, e a outra metade, para o sul.

[[v38-14-5]]

^<<v38-14-5,5>>^ Vocês fugirão da cidade por esse vale, que irá até Azal. Fugirão como os antepassados de vocês fugiram quando houve um terremoto no tempo do reinado de Uzias, rei de Judá. Então o Senhor , meu Deus, virá com todos os seus anjos.

[[v38-14-6]]

^<<v38-14-6,6>>^ Daquele dia em diante, não fará mais frio, nem haverá geada.

[[v38-14-7]]

^<<v38-14-7,7>>^ E não haverá mais escuridão. Haverá somente dia, pois o sol continuará a brilhar a noite inteira. Mas só o Senhor  Deus sabe quando é que aquele dia vai chegar.

[[v38-14-8]]

^<<v38-14-8,8>>^ Naquele dia, haverá em Jerusalém fontes jorrando água fresca; metade irá para o mar Morto, e a outra metade, para o mar Mediterrâneo. As águas correrão o ano inteiro, tanto no verão como no inverno.

[[v38-14-9]]

^<<v38-14-9,9>>^ O Senhor  Deus será o Rei do mundo inteiro. Ele será o único Deus, e todos o chamarão de Senhor .

[[v38-14-10]]

^<<v38-14-10,10>>^ O país todo virará uma planície, desde Geba, no Norte, até Rimom, ao sul de Jerusalém. E Jerusalém será o lugar mais alto do país; haverá gente morando ali, desde o Portão de Benjamim até o Portão da Esquina, que antes era o Portão Antigo, e desde a Torre de Hananel até os tanques onde é feito o vinho do rei.

[[v38-14-11]]

^<<v38-14-11,11>>^ Nunca mais a cidade será destruída, e os seus moradores viverão seguros.

[[v38-14-12]]

^<<v38-14-12,12>>^ O Senhor  Deus castigará todos os povos que atacarem Jerusalém. Ele mandará uma praga que fará a carne deles apodrecer, estando eles ainda vivos; até os olhos e a língua apodrecerão.

[[v38-14-13]]

^<<v38-14-13,13>>^ Naquele dia, o Senhor  fará com que eles fiquem tão confusos e assustados, que cada um agarrará a pessoa que estiver ao seu lado e a atacará.

[[v38-14-14]]

^<<v38-14-14,14>>^ Até os homens de Judá lutarão contra Jerusalém. Serão levadas embora todas as riquezas das nações vizinhas, isto é, grandes quantidades de ouro, prata e roupa.

[[v38-14-15]]

^<<v38-14-15,15>>^ E a mesma praga que Deus vai mandar contra as pessoas vai atacar também todos os animais dos inimigos, isto é, os cavalos, as mulas, os camelos e os jumentos.

[[v38-14-16]]

^<<v38-14-16,16>>^ Depois disso, todos os que sobrarem das nações que lutarem contra Jerusalém irão uma vez por ano até lá a fim de adorar o Senhor  Todo-Poderoso como rei e para comemorar a Festa das Barracas .

[[v38-14-17]]

^<<v38-14-17,17>>^ Se uma nação não for adorar o Rei, o Senhor  Todo-Poderoso, então não cairá chuva naquele país.

[[v38-14-18]]

^<<v38-14-18,18>>^ Se os egípcios não forem até Jerusalém para comemorar a Festa das Barracas, o Senhor  Deus os castigará com a mesma praga que vai mandar sobre as outras nações.

[[v38-14-19]]

^<<v38-14-19,19>>^ Este será o castigo que Deus vai mandar sobre o Egito e sobre qualquer outra nação que não for até Jerusalém para comemorar a Festa das Barracas.

[[v38-14-20]]

^<<v38-14-20,20>>^ Naquele dia, até nos sininhos das rédeas dos cavalos será escrito isto: "Separado para o Senhor ", e as panelas do Templo serão tão sagradas como as bacias que estão em frente do altar.

[[v38-14-21]]

^<<v38-14-21,21>>^ Em Jerusalém e em Judá, todas as panelas serão separadas para o Senhor  Todo-Poderoso. Quando alguém for ao Templo para oferecer um sacrifício  a Deus, essa pessoa usará as suas panelas para cozinhar a carne que será oferecida. E naquele dia não haverá nenhum vendedor no Templo do Senhor  Todo-Poderoso.

'''

xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[Próximo Capítulo &#62;]