include::./index.adoc[]

[[v38-3-0]]
=== Zacarias, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-3-1]]

^<<v38-3-1,1>>^ Em outra visão, Deus me mostrou o Grande Sacerdote  Josué, que estava de pé em frente do Anjo do Senhor . Satanás estava à direita de Josué, pronto para acusá-lo.

[[v38-3-2]]

^<<v38-3-2,2>>^ O Anjo do Senhor  disse a Satanás: — Que Deus o condene, Satanás! Que o Senhor , que escolheu Jerusalém, o condene! Esse homem é como um tição tirado do fogo.

[[v38-3-3]]

^<<v38-3-3,3>>^ Josué, vestido com roupas sujas, continuava de pé em frente do Anjo.

[[v38-3-4]]

^<<v38-3-4,4>>^ Aí o Anjo disse aos seus ajudantes que tirassem a roupa de Josué e depois lhe disse: — Assim eu tiro os seus pecados e agora vou vesti-lo com roupas de festa.

[[v38-3-5]]

^<<v38-3-5,5>>^ Em seguida, o Anjo mandou que os seus ajudantes pusessem na cabeça de Josué um turbante  que havia sido purificado . Eles puseram o turbante na cabeça dele e o vestiram com roupas de festa; e o Anjo do Senhor  continuava ali de pé.

[[v38-3-6]]

^<<v38-3-6,6>>^ E ele disse a Josué:

[[v38-3-7]]

^<<v38-3-7,7>>^ — O Senhor  Todo-Poderoso lhe diz o seguinte: "Se você obedecer às minhas leis e cumprir os seus deveres conforme eu ordeno, você será o administrador do Templo. Cuidará do santuário e de todos os outros edifícios; e, como estes anjos que estão aqui, você terá o mesmo direito de estar na minha presença.

[[v38-3-8]]

^<<v38-3-8,8>>^ Portanto, escute, Grande Sacerdote  Josué, e escutem também os sacerdotes que estão com você. Vocês todos são um sinal de que eu vou enviar ao meu povo o meu servo  que se chama ‘Ramo Novo’.

[[v38-3-9]]

^<<v38-3-9,9>>^ Coloquei em frente de Josué uma pedra que tinha sete lados. Eu, o Senhor  Todo-Poderoso, vou gravar nela um nome e num só dia vou tirar o pecado deste país.

[[v38-3-10]]

^<<v38-3-10,10>>^ Naquele dia, cada um de vocês poderá convidar os vizinhos para que venham e fiquem à vontade debaixo das parreiras  e das figueiras. Eu, o Senhor  Todo-Poderoso, falei."

'''

xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[Próximo Capítulo &#62;]