include::./index.adoc[]

[[v38-1-0]]
=== Zacarias, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v38-1-1]]

^<<v38-1-1,1>>^ No oitavo mês do segundo ano de Dario como rei da Pérsia, o Senhor  Deus falou com o profeta  Zacarias, filho de Baraquias e neto de Ido. O Deus Todo-Poderoso mandou que ele dissesse ao povo o seguinte:

[[v38-1-2]]

^<<v38-1-2,2>>^ — Eu, o Senhor , fiquei muito irado  com os seus antepassados.

[[v38-1-3]]

^<<v38-1-3,3>>^ Portanto, agora eu digo a vocês: Voltem para mim, e eu, o Senhor  Todo-Poderoso, voltarei para vocês.

[[v38-1-4]]

^<<v38-1-4,4>>^ Não sejam como os seus antepassados, que não deram atenção aos profetas antigos quando eles anunciaram esta minha mensagem: "O Senhor  Todo-Poderoso ordena que vocês deixem de ser maus e que abandonem as suas maldades." Mas eles não me obedeceram.

[[v38-1-5]]

^<<v38-1-5,5>>^ E agora onde estão os seus antepassados? E será que aqueles profetas ainda estão vivos?

[[v38-1-6]]

^<<v38-1-6,6>>^ Por meio dos meus servos , os profetas, eu mandei mensagens e avisos aos antepassados de vocês. Mas eles não deram atenção e por isso foram castigados. Então eles se arrependeram e disseram: "O Senhor  Todo-Poderoso fez o que tinha decidido fazer e nos castigou por causa dos nossos pecados. Ele fez o que merecíamos."

[[v38-1-7]]

^<<v38-1-7,7>>^ No dia vinte e quatro do mês onze, chamado sebate , do segundo ano do reinado de Dario, eu, o profeta Zacarias, filho de Baraquias e neto de Ido, recebi uma mensagem de Deus, o Senhor .

[[v38-1-8]]

^<<v38-1-8,8>>^ Naquela noite, tive uma visão e nela vi um anjo do Senhor  montado num cavalo vermelho. O anjo estava parado num vale, no meio de umas moitas, e atrás dele estavam outros anjos montados, uns em cavalos vermelhos, outros em cavalos baios, e outros em cavalos brancos.

[[v38-1-9]]

^<<v38-1-9,9>>^ Perguntei ao anjo que falava comigo: — Meu senhor, quem são esses anjos montados em cavalos? Ele respondeu: — Eu vou lhe dizer.

[[v38-1-10]]

^<<v38-1-10,10>>^ Aí o anjo que estava no meio das moitas disse: — Eles são os anjos que o Senhor  Deus enviou para andarem pelo mundo inteiro.

[[v38-1-11]]

^<<v38-1-11,11>>^ Então aqueles anjos disseram ao anjo que estava no meio das moitas: — Acabamos de andar por toda a terra e vimos que tudo está calmo e em paz.

[[v38-1-12]]

^<<v38-1-12,12>>^ E o anjo do Senhor  disse: — Ó Senhor  Todo-Poderoso, já faz setenta anos que estás irado  com Jerusalém e com as cidades de Judá. Quanto tempo vai passar até que tenhas compaixão delas?

[[v38-1-13]]

^<<v38-1-13,13>>^ O Senhor  Deus respondeu com carinho ao anjo que estava falando comigo e disse palavras de consolo.

[[v38-1-14]]

^<<v38-1-14,14>>^ Aí o anjo que falava comigo mandou que eu anunciasse em voz alta o seguinte: — Esta é a mensagem do Senhor  Todo-Poderoso: "Eu tenho grande amor por Jerusalém, a minha cidade.

[[v38-1-15]]

^<<v38-1-15,15>>^ E estou muito irado com as nações que vivem sossegadas. Pois, quando eu estava um pouco irado com o meu povo, elas fizeram com que ele sofresse muito.

[[v38-1-16]]

^<<v38-1-16,16>>^ Portanto, cheio de compaixão, voltei para Jerusalém. E eu, o Senhor  Todo-Poderoso, prometo que o Templo e a cidade toda serão construídos de novo."

[[v38-1-17]]

^<<v38-1-17,17>>^ E o anjo me disse também: — Anuncie que o Senhor  Todo-Poderoso diz que as cidades dele terão de novo muitas riquezas. E ele ajudará Jerusalém, que voltará a ser a sua cidade escolhida.

[[v38-1-18]]

^<<v38-1-18,18>>^ Tive outra visão e vi quatro chifres de boi.

[[v38-1-19]]

^<<v38-1-19,19>>^ Perguntei ao anjo que falava comigo: — Que querem dizer estes chifres? Ele respondeu: — Eles representam as nações que espalharam pelo mundo inteiro os moradores de Judá, de Israel e de Jerusalém.

[[v38-1-20]]

^<<v38-1-20,20>>^ Aí o Senhor  Deus me mostrou quatro ferreiros.

[[v38-1-21]]

^<<v38-1-21,21>>^ Eu perguntei: — O que é que eles vêm fazer? Ele respondeu: — Os chifres são as nações que espalharam os moradores de Judá de tal maneira, que ninguém tinha coragem de levantar a cabeça. E agora estes ferreiros representam os que estão vindo para assustar e quebrar aqueles chifres, isto é, aquelas nações que conquistaram a terra de Judá e espalharam o seu povo.

'''

xref:037-ageu/037-ageu-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[Próximo Capítulo &#62;]