include::./index.adoc[]

[[v27-2-0]]
=== Daniel, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-2-1]]

^<<v27-2-1,1>>^ No segundo ano de Nabucodonosor como rei da Babilônia, ele teve uns sonhos que o deixaram tão preocupado, que não podia dormir.

[[v27-2-2]]

^<<v27-2-2,2>>^ Então mandou chamar os sábios, os adivinhos, os feiticeiros e os astrólogos, para que eles explicassem os sonhos. Quando chegaram e se apresentaram diante do rei,

[[v27-2-3]]

^<<v27-2-3,3>>^ ele lhes disse: — Tive um sonho que me deixou muito preocupado e não vou ficar sossegado enquanto não souber o que ele quer dizer.

[[v27-2-4]]

^<<v27-2-4,4>>^ Eles disseram ao rei na língua aramaica  : — Que o rei viva para sempre! Pedimos que o senhor nos conte o sonho e aí nós lhe diremos o que ele quer dizer.

[[v27-2-5]]

^<<v27-2-5,5>>^ Mas o rei respondeu: — Eu já resolvi que vocês têm de me contar o sonho e também explicar o que ele quer dizer. Se não puderem fazer isso, vocês serão todos cortados em pedaços, e as suas casas serão completamente arrasadas.

[[v27-2-6]]

^<<v27-2-6,6>>^ Mas, se me contarem o sonho e explicarem o que ele quer dizer, eu lhes darei presentes, prêmios e muitas honras. Portanto, digam o que foi que eu sonhei e o que o sonho quer dizer.

[[v27-2-7]]

^<<v27-2-7,7>>^ E todos os sábios disseram de novo: — Conte o senhor o sonho, e aí nós lhe diremos o que ele quer dizer.

[[v27-2-8]]

^<<v27-2-8,8>>^ Mas o rei insistiu: — Eu sei o que vocês estão fazendo. Estão é procurando ganhar tempo porque sabem que já resolvi

[[v27-2-9]]

^<<v27-2-9,9>>^ que, se vocês não me contarem o sonho, vou dar a todos o mesmo castigo. Vocês já combinaram me enganar com mentiras e falsidades, esperando que a situação mude. Contem-me o sonho, e então eu saberei que também poderão explicar o que ele quer dizer.

[[v27-2-10]]

^<<v27-2-10,10>>^ Os sábios deram ao rei esta resposta: — Não há ninguém no mundo que seja capaz de fazer o que o senhor quer. Nunca houve nenhum rei, por mais forte e poderoso que fosse, que tivesse exigido uma coisa dessas dos seus sábios, adivinhos ou astrólogos.

[[v27-2-11]]

^<<v27-2-11,11>>^ O que o senhor está querendo é impossível. Não existe quem possa atender o seu pedido, a não ser os deuses, e eles não moram com a gente aqui na terra.

[[v27-2-12]]

^<<v27-2-12,12>>^ O rei ficou tão furioso, que mandou matar todos os sábios da Babilônia.

[[v27-2-13]]

^<<v27-2-13,13>>^ A ordem foi publicada, e então foram buscar Daniel e os seus companheiros para que eles também fossem mortos.

[[v27-2-14]]

^<<v27-2-14,14>>^ Daniel foi procurar Arioque, o chefe da guarda do rei, que tinha recebido ordem para matar todos os sábios da Babilônia. Com muito jeito e cuidado,

[[v27-2-15]]

^<<v27-2-15,15>>^ Daniel perguntou a Arioque: — Por que foi que o rei deu uma ordem tão dura assim? Arioque explicou o que havia acontecido.

[[v27-2-16]]

^<<v27-2-16,16>>^ Então Daniel foi falar com o rei, e este concordou em esperar, a fim de dar tempo a Daniel para explicar o sonho.

[[v27-2-17]]

^<<v27-2-17,17>>^ Depois, Daniel foi para casa e contou tudo aos seus amigos Ananias, Misael e Azarias.

[[v27-2-18]]

^<<v27-2-18,18>>^ Daniel disse que orassem ao Deus do céu, pedindo que tivesse pena deles e lhes mostrasse o que aquele sonho misterioso queria dizer, a fim de que Daniel e os seus amigos não morressem junto com os outros sábios da Babilônia.

[[v27-2-19]]

^<<v27-2-19,19>>^ Naquela noite, Daniel teve uma visão, e nela Deus mostrou o que o sonho queria dizer. Então Daniel agradeceu a Deus,

[[v27-2-20]]

^<<v27-2-20,20>>^ dizendo: "Que o nome de Deus seja louvado para sempre, pois dele são a sabedoria e o poder!

[[v27-2-21]]

^<<v27-2-21,21>>^ É ele quem faz mudar os tempos e as estações; é ele quem põe os reis no poder e os derruba; é ele quem dá sabedoria aos sábios e inteligência aos inteligentes.

[[v27-2-22]]

^<<v27-2-22,22>>^ Ele explica mistérios e segredos e conhece o que está escondido na escuridão, pois com ele mora a luz.

[[v27-2-23]]

^<<v27-2-23,23>>^ Ó Deus dos meus antepassados, eu te agradeço e te louvo, pois me deste sabedoria e poder. Tu respondeste à nossa oração, nos mostrando o que o rei quer saber."

[[v27-2-24]]

^<<v27-2-24,24>>^ Aí Daniel foi procurar Arioque, o oficial que tinha recebido ordem do rei para matar os sábios da Babilônia. Daniel disse: — Arioque, não mate os sábios. Leve-me para falar com o rei, e eu explicarei o sonho que ele teve.

[[v27-2-25]]

^<<v27-2-25,25>>^ Arioque levou Daniel depressa para o lugar onde o rei estava e lhe disse: — Está aqui comigo um dos judeus que trouxemos como prisioneiros e ele vai explicar o sonho que o senhor teve.

[[v27-2-26]]

^<<v27-2-26,26>>^ O rei perguntou a Daniel, que também era chamado de Beltessazar: — Você pode contar o meu sonho e explicar o que ele quer dizer?

[[v27-2-27]]

^<<v27-2-27,27>>^ Daniel respondeu: — Não há sábios, adivinhos, feiticeiros nem astrólogos que possam dar a explicação que o senhor está exigindo.

[[v27-2-28]]

^<<v27-2-28,28>>^ Mas há um Deus no céu, que explica mistérios. Foi por meio do sonho que ele fez o senhor saber o que vai acontecer no futuro. E agora, ó rei, eu vou explicar o sonho e as visões que o senhor teve enquanto dormia.

[[v27-2-29]]

^<<v27-2-29,29>>^ — O senhor estava deitado na sua cama e começou a pensar a respeito do futuro. E aquele que explica mistérios mostrou ao senhor o que vai acontecer.

[[v27-2-30]]

^<<v27-2-30,30>>^ E eu recebi a explicação do mistério, não porque seja o mais sábio de todos os homens, mas a fim de que o senhor saiba o sentido do sonho que teve e o que querem dizer os pensamentos que passaram pela sua mente, ó rei.

[[v27-2-31]]

^<<v27-2-31,31>>^ — O senhor teve uma visão na qual viu uma estátua enorme, de pé, bem na sua frente. A estátua era brilhante, mas metia medo.

[[v27-2-32]]

^<<v27-2-32,32>>^ A cabeça era de ouro puro, o peito e os braços eram de prata, a barriga e os quadris eram de bronze,

[[v27-2-33]]

^<<v27-2-33,33>>^ as pernas eram de ferro, e os pés eram metade de ferro e metade de barro.

[[v27-2-34]]

^<<v27-2-34,34>>^ Enquanto o senhor estava olhando, uma pedra se soltou de uma montanha, sem que ninguém a tivesse empurrado. A pedra caiu em cima dos pés da estátua e os despedaçou.

[[v27-2-35]]

^<<v27-2-35,35>>^ Imediatamente, o ferro, o barro, o bronze, a prata e o ouro viraram pó, como o pó que se vê no verão quando se bate o trigo para separá-lo da palha. O vento levou tudo embora, sem deixar nenhum sinal. Mas a pedra cresceu e se tornou uma grande montanha, que cobriu o mundo inteiro.

[[v27-2-36]]

^<<v27-2-36,36>>^ — Foi este o sonho, e agora vou explicá-lo para o senhor.

[[v27-2-37]]

^<<v27-2-37,37>>^ Ó rei, o senhor é o mais poderoso de todos os reis, e foi o Deus do céu quem o fez rei; ele lhe deu poder, autoridade e honra.

[[v27-2-38]]

^<<v27-2-38,38>>^ Ele deu ao senhor o domínio em todo o mundo sobre os seres humanos, os animais e as aves. O senhor é a cabeça feita de ouro.

[[v27-2-39]]

^<<v27-2-39,39>>^ Depois do seu reino haverá outro, que não será tão poderoso como o seu; e depois desse reino haverá ainda outro, um reino de bronze, que dominará o mundo inteiro.

[[v27-2-40]]

^<<v27-2-40,40>>^ Depois, virá um quarto reino, e este será forte como o ferro, que quebra e despedaça tudo. E assim como o ferro quebra tudo, esse reino destruirá completamente todos os outros reinos do mundo.

[[v27-2-41]]

^<<v27-2-41,41>>^ Na estátua que o senhor viu, os pés e os dedos dos pés eram metade de ferro e metade de barro. Isso quer dizer que esse reino será dividido, mas terá alguma coisa da força do ferro; pois, como o senhor viu, o ferro estava misturado com barro.

[[v27-2-42]]

^<<v27-2-42,42>>^ Os dedos dos pés eram metade de ferro e metade de barro; isso quer dizer que o reino, por um lado, será forte, mas, por outro, será fraco.

[[v27-2-43]]

^<<v27-2-43,43>>^ O senhor, ó rei, viu que o ferro estava misturado com barro, e isso quer dizer que os reis procurarão unir os seus reinos por meio de casamentos. Mas como o ferro e o barro não se unem, assim também esses reinos não ficarão unidos.

[[v27-2-44]]

^<<v27-2-44,44>>^ No tempo desses reis, o Deus do céu fará aparecer um reino que nunca será destruído, nem será conquistado por outro reino. Pelo contrário, esse reino acabará com todos os outros e durará para sempre.

[[v27-2-45]]

^<<v27-2-45,45>>^ É isso o que quer dizer a pedra que o rei viu soltar-se da montanha, sem que ninguém a tivesse empurrado, e que despedaçou a estátua feita de ferro, bronze, prata, barro e ouro. O Grande Deus está revelando ao senhor o que vai acontecer no futuro. Foi este o sonho que o senhor teve, e esta é a explicação certa.

[[v27-2-46]]

^<<v27-2-46,46>>^ Então o rei Nabucodonosor se ajoelhou diante de Daniel, e encostou o rosto no chão, e depois ordenou que fossem apresentados a Daniel sacrifícios  e incenso.

[[v27-2-47]]

^<<v27-2-47,47>>^ E ele disse a Daniel: — O Deus que vocês adoram é, de fato, o mais poderoso de todos os deuses e é o Senhor de todos os reis. Eu sei que é ele quem explica mistérios, pois você me explicou este sonho misterioso.

[[v27-2-48]]

^<<v27-2-48,48>>^ Em seguida, o rei colocou Daniel como alta autoridade do reino e lhe deu também muitos presentes de valor. Ele pôs Daniel como governador da província  da Babilônia e o fez chefe de todos os sábios do país.

[[v27-2-49]]

^<<v27-2-49,49>>^ A pedido de Daniel, o rei pôs Sadraque, Mesaque e Abede-Nego como administradores da província da Babilônia; mas Daniel ficou na corte real.

'''

xref:027-daniel/027-daniel-001.adoc#v27-1-0[&#60; Capítulo Anterior] | <<v27-2-0,Topo>> | xref:027-daniel/027-daniel-003.adoc#v27-3-0[Próximo Capítulo &#62;]