include::./index.adoc[]

[[v27-5-0]]
=== Daniel, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-5-1]]

^<<v27-5-1,1>>^ Certa noite, o rei Belsazar, da Babilônia, deu um banquete, convidou mil autoridades do país e começou a beber vinho com os convidados.

[[v27-5-2]]

^<<v27-5-2,2>>^ Depois de beber bastante, mandou que trouxessem os copos de ouro e de prata que Nabucodonosor, o seu pai, havia tirado do Templo de Jerusalém. Belsazar queria os copos para que ele, os seus convidados de honra, as suas mulheres e as suas concubinas  os usassem para beber vinho.

[[v27-5-3]]

^<<v27-5-3,3>>^ Trouxeram os copos de ouro e todos começaram a beber vinho neles

[[v27-5-4]]

^<<v27-5-4,4>>^ e a louvar os deuses de ouro, de prata, de bronze, de ferro, de madeira e de pedra.

[[v27-5-5]]

^<<v27-5-5,5>>^ De repente, apareceu a mão de um homem e ela começou a escrever na parede branca do salão do banquete, num lugar iluminado pela luz do candelabro . Ao ver a mão, o rei

[[v27-5-6]]

^<<v27-5-6,6>>^ não sabia o que pensar; ficou pálido de medo e começou a tremer da cabeça aos pés.

[[v27-5-7]]

^<<v27-5-7,7>>^ Depois, gritando, ordenou que chamassem os adivinhos, os sábios e os astrólogos. Logo que eles chegaram, Belsazar disse: — Aquele que ler o que está escrito na parede e me explicar o que quer dizer será vestido com roupas de púrpura , receberá uma corrente de ouro para pôr no pescoço e será a terceira autoridade mais importante no meu reino.

[[v27-5-8]]

^<<v27-5-8,8>>^ Todos os sábios entraram no salão, mas nenhum deles pôde ler o que estava escrito na parede, nem explicar ao rei o que aquilo queria dizer.

[[v27-5-9]]

^<<v27-5-9,9>>^ O rei se assustou ainda mais, e o seu rosto ficou mais pálido ainda. E nenhuma das altas autoridades sabia o que fazer.

[[v27-5-10]]

^<<v27-5-10,10>>^ Então a rainha-mãe, que tinha ouvido os gritos do rei e dos seus convidados de honra, entrou no salão e disse ao rei: — Que o rei viva para sempre! Não se assuste, nem fique pálido assim,

[[v27-5-11]]

^<<v27-5-11,11>>^ pois aqui no seu reino há um homem que tem o espírito dos santos deuses. Quando Nabucodonosor, o seu pai, era rei, esse homem provou que era ajuizado, inteligente e sábio, tão sábio como os deuses. E o rei Nabucodonosor pôs esse homem como chefe dos sábios, adivinhos, feiticeiros e astrólogos.

[[v27-5-12]]

^<<v27-5-12,12>>^ Pois Daniel, esse homem a quem o rei deu o nome de Beltessazar, pensa com muita clareza; ele é sábio e inteligente e pode interpretar sonhos, explicar coisas misteriosas e resolver assuntos difíceis. Portanto, chame Daniel, e ele explicará o que está escrito na parede.

[[v27-5-13]]

^<<v27-5-13,13>>^ Levaram Daniel até a presença do rei, e este perguntou: — Você é mesmo aquele Daniel, um dos judeus que o meu pai, o rei Nabucodonosor, trouxe de Judá como prisioneiros?

[[v27-5-14]]

^<<v27-5-14,14>>^ Já me disseram que o espírito dos deuses está em você e que você pensa com muita clareza e é muito inteligente e sábio.

[[v27-5-15]]

^<<v27-5-15,15>>^ Há pouco, estiveram aqui os sábios e os astrólogos, que eu mandei chamar para que lessem as palavras que estão escritas na parede e me explicassem o que elas querem dizer. Porém eles não puderam dar nenhuma explicação.

[[v27-5-16]]

^<<v27-5-16,16>>^ Mas alguém me disse que você pode explicar mistérios e resolver assuntos difíceis. Portanto, se você puder ler o que está escrito e me explicar o que quer dizer, você será vestido com roupas de púrpura , receberá uma corrente de ouro para pôr no pescoço e será a terceira autoridade mais importante do meu reino.

[[v27-5-17]]

^<<v27-5-17,17>>^ Daniel respondeu: — O senhor pode ficar com os seus presentes ou então dá-los a outra pessoa. Mesmo assim, eu vou ler as palavras que estão escritas na parede e vou explicar ao senhor o que elas querem dizer.

[[v27-5-18]]

^<<v27-5-18,18>>^ Ó rei, o Deus Altíssimo deu o reino ao seu pai, o rei Nabucodonosor, e lhe deu também poder, glória  e majestade.

[[v27-5-19]]

^<<v27-5-19,19>>^ O poder que Deus lhe deu era tão grande, que todos os povos do mundo tremiam de medo na presença dele. Se ele queria, matava uma pessoa; ou, se queria, deixava que vivesse. Elevava uns e rebaixava outros.

[[v27-5-20]]

^<<v27-5-20,20>>^ Mas ele ficou tão vaidoso, tão teimoso e tão cheio de si, que foi derrubado do poder e perdeu toda a sua glória.

[[v27-5-21]]

^<<v27-5-21,21>>^ Foi expulso do meio dos seres humanos, perdeu o juízo e agia como um animal. Morava com jumentos selvagens, comia capim como os bois e dormia ao ar livre, ficando molhado pelo sereno. Isso durou até que ele reconheceu que o Deus Altíssimo domina todos os reinos do mundo e coloca como rei quem ele quer.

[[v27-5-22]]

^<<v27-5-22,22>>^ — E o senhor, ó rei Belsazar, filho de Nabucodonosor, sabia de tudo isso, mas mesmo assim não tem sido humilde.

[[v27-5-23]]

^<<v27-5-23,23>>^ Pelo contrário, o senhor desafiou o Rei do céu e mandou trazer os copos que foram tirados do Templo dele, a fim de que o senhor, os seus convidados de honra, as suas mulheres e as suas concubinas  bebessem vinho neles. Além disso, o senhor deu louvores a deuses de prata, de ouro, de bronze, de ferro, de madeira e de pedra, que não veem, não ouvem e não sabem nada. Mas o senhor não deu glória a Deus, aquele que tem o poder de matar ou de deixar viver e que decide tudo o que acontece com o senhor.

[[v27-5-24]]

^<<v27-5-24,24>>^ É por isso que ele mandou essa mão escrever na parede estas palavras:

[[v27-5-25]]

^<<v27-5-25,25>>^ " Mene , Mene , Tequel  e Parsim ".

[[v27-5-26]]

^<<v27-5-26,26>>^ — E agora a explicação. Mene  quer dizer que Deus contou o número dos dias do reinado do senhor e resolveu terminá-lo.

[[v27-5-27]]

^<<v27-5-27,27>>^ Tequel  quer dizer que o senhor foi pesado na balança e pesou muito pouco.

[[v27-5-28]]

^<<v27-5-28,28>>^ Peres  quer dizer que o seu reino será dividido e entregue aos medos e aos persas .

[[v27-5-29]]

^<<v27-5-29,29>>^ Aí o rei Belsazar mandou que vestissem Daniel com roupas de púrpura, pusessem uma corrente de ouro no seu pescoço e anunciassem que dali em diante ele seria a terceira autoridade mais importante do Reino da Babilônia.

[[v27-5-30]]

^<<v27-5-30,30>>^ Naquela mesma noite, Belsazar, o rei da Babilônia, foi morto,

[[v27-5-31]]

^<<v27-5-31,31>>^ e Dario, o rei do país da Média, que tinha sessenta e dois anos de idade, começou a reinar no seu lugar.

'''

xref:027-daniel/027-daniel-004.adoc#v27-4-0[&#60; Capítulo Anterior] | <<v27-5-0,Topo>> | xref:027-daniel/027-daniel-006.adoc#v27-6-0[Próximo Capítulo &#62;]