include::./index.adoc[]

[[v27-1-0]]
=== Daniel, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-1-1]]

^<<v27-1-1,1>>^ No terceiro ano de Jeoaquim como rei de Judá, o rei Nabucodonosor, da Babilônia, atacou Jerusalém, e os seus soldados cercaram a cidade.

[[v27-1-2]]

^<<v27-1-2,2>>^ Deus deixou que Nabucodonosor conquistasse a cidade e também que pegasse alguns objetos de valor que estavam no Templo. Nabucodonosor levou esses objetos para a Babilônia e mandou colocá-los no templo do seu deus, na sala do tesouro.

[[v27-1-3]]

^<<v27-1-3,3>>^ O rei Nabucodonosor chamou Aspenaz, o chefe dos serviços do palácio, e mandou que escolhesse entre os prisioneiros israelitas alguns jovens da família do rei e também das famílias nobres.

[[v27-1-4]]

^<<v27-1-4,4>>^ Todos eles deviam ter boa aparência e não ter nenhum defeito físico; deviam ser inteligentes, instruídos e ser capazes de servir no palácio. E precisariam aprender a língua e estudar os escritos dos babilônios.

[[v27-1-5]]

^<<v27-1-5,5>>^ O rei mandou também que os jovens israelitas recebessem todos os dias a mesma comida e o mesmo vinho que ele, o rei, comia e bebia. Depois de três anos de preparo, esses jovens deviam começar o seu serviço no palácio.

[[v27-1-6]]

^<<v27-1-6,6>>^ Entre os que foram escolhidos estavam Daniel, Ananias, Misael e Azarias, todos da tribo  de Judá.

[[v27-1-7]]

^<<v27-1-7,7>>^ Aspenaz lhes deu outros nomes, isto é, Beltessazar, Sadraque, Mesaque e Abede-Nego.

[[v27-1-8]]

^<<v27-1-8,8>>^ Daniel resolveu que não iria ficar impuro  por comer a comida e beber o vinho que o rei dava; por isso, foi pedir a Aspenaz que o ajudasse a cumprir o que havia resolvido.

[[v27-1-9]]

^<<v27-1-9,9>>^ Deus fez com que Aspenaz fosse bondoso com Daniel e tivesse boa vontade para com ele.

[[v27-1-10]]

^<<v27-1-10,10>>^ Mas Aspenaz tinha medo do rei e por isso disse a Daniel: — Foi o rei, o meu senhor, quem resolveu o que vocês devem comer e beber. Se ele notar que vocês estão menos fortes e sadios do que os outros jovens, ele será capaz de me matar, e vocês serão os culpados.

[[v27-1-11]]

^<<v27-1-11,11>>^ Aí Daniel foi falar com o guarda a quem Aspenaz havia encarregado de cuidar dele, de Ananias, de Misael e de Azarias. Daniel disse a ele:

[[v27-1-12]]

^<<v27-1-12,12>>^ — Quero pedir que o senhor faça uma experiência com a gente. Durante dez dias, dê-nos somente legumes para comer e água para beber.

[[v27-1-13]]

^<<v27-1-13,13>>^ No fim dos dez dias, faça uma comparação entre nós e os jovens que comem a comida do rei. Então, dependendo de como estivermos, o senhor fará com a gente o que quiser.

[[v27-1-14]]

^<<v27-1-14,14>>^ O guarda concordou e durante dez dias fez a experiência com eles.

[[v27-1-15]]

^<<v27-1-15,15>>^ Passados os dez dias, os quatro jovens israelitas estavam mais sadios e mais fortes do que os jovens que comiam a comida do rei.

[[v27-1-16]]

^<<v27-1-16,16>>^ Aí o guarda tirou a comida e o vinho que deviam ser servidos aos quatro jovens e só lhes dava legumes para comer.

[[v27-1-17]]

^<<v27-1-17,17>>^ Deus deu aos quatro jovens um conhecimento profundo dos escritos e das ciências dos babilônios, mas a Daniel deu também o dom  de explicar visões e sonhos.

[[v27-1-18]]

^<<v27-1-18,18>>^ No fim dos três anos de preparo que o rei Nabucodonosor tinha marcado, Aspenaz levou todos os jovens até a presença do rei.

[[v27-1-19]]

^<<v27-1-19,19>>^ Este falou com eles, e entre todos não havia quem se comparasse com Daniel, Ananias, Misael e Azarias. Por isso, ficaram trabalhando no palácio.

[[v27-1-20]]

^<<v27-1-20,20>>^ Todas as vezes que o rei fazia perguntas a respeito de qualquer assunto que exigisse inteligência ou conhecimento, descobria que os quatro eram dez vezes mais inteligentes do que todos os sábios e adivinhos de toda a Babilônia.

[[v27-1-21]]

^<<v27-1-21,21>>^ E Daniel ficou no palácio real até o ano em que o rei Ciro começou a governar a Babilônia .

'''

xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[&#60; Capítulo Anterior] | <<v27-1-0,Topo>> | xref:027-daniel/027-daniel-002.adoc#v27-2-0[Próximo Capítulo &#62;]