include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-8-1]]

^<<v27-8-1,1>>^ No terceiro ano do reinado de Belsazar, eu tive outra visão.

[[v27-8-2]]

^<<v27-8-2,2>>^ Parecia que eu estava na beira do rio Ulai, em Susã, uma cidade cercada de muralhas, que fica na província  de Elão.

[[v27-8-3]]

^<<v27-8-3,3>>^ De repente, vi perto do rio um carneiro que tinha dois chifres compridos. Um deles tinha nascido depois do outro, mas era mais comprido.

[[v27-8-4]]

^<<v27-8-4,4>>^ O carneiro estava dando chifradas para o oeste, para o norte e para o sul, e nenhum animal ou pessoa podia resistir ou escapar dos seus ataques. Ele fazia o que queria e ficava cada vez mais poderoso.

[[v27-8-5]]

^<<v27-8-5,5>>^ Eu estava pensando nisso quando vi um bode que vinha do oeste, correndo tão depressa, que as suas patas nem tocavam o chão. Ele tinha um chifre só, bem grande, que ficava entre os olhos.

[[v27-8-6]]

^<<v27-8-6,6>>^ Correu até o lugar onde estava o carneiro que eu tinha visto perto do rio e o atacou com toda a força.

[[v27-8-7]]

^<<v27-8-7,7>>^ Eu vi o bode, furioso, atacar o carneiro e quebrar os dois chifres dele, pois o carneiro não tinha força para se defender. O bode jogou o carneiro no chão e o pisou com as patas; e ninguém podia salvar o carneiro da fúria do bode.

[[v27-8-8]]

^<<v27-8-8,8>>^ Ele ficou ainda mais poderoso, mas, quando o seu poder chegou ao máximo, o seu chifre foi quebrado, e em lugar dele nasceram quatro chifres compridos, que cresciam para o norte, para o sul, para o leste e para o oeste.

[[v27-8-9]]

^<<v27-8-9,9>>^ De um desses chifres nasceu um chifre pequeno, que foi crescendo e se estendendo para o sul, para o leste e para a Terra Prometida .

[[v27-8-10]]

^<<v27-8-10,10>>^ Cresceu tanto, que chegou até o lugar onde está o exército do céu, que são as estrelas; jogou na terra algumas delas e as pisou.

[[v27-8-11]]

^<<v27-8-11,11>>^ Chegou até a desafiar o comandante desse exército. Acabou com os sacrifícios  diários que eram oferecidos a esse comandante e deixou o seu Templo todo estragado.

[[v27-8-12]]

^<<v27-8-12,12>>^ Em vez do sacrifício diário, foi apresentada uma oferta nojenta. Ele acabou com a verdadeira religião, e tudo o que fez deu certo.

[[v27-8-13]]

^<<v27-8-13,13>>^ Depois, ouvi dois anjos conversando, e um perguntou ao outro: — Quanto tempo vai durar aquilo que apareceu na visão? Por quanto tempo essa oferta nojenta será apresentada em lugar do sacrifício diário? Por quanto tempo ficará estragado o Templo e derrotado o exército do céu?

[[v27-8-14]]

^<<v27-8-14,14>>^ E ouvi a resposta: — Tudo isso vai acontecer depois de duas mil e trezentas tardes e manhãs, e durante esse tempo não serão oferecidos os sacrifícios. Depois disso o Templo será purificado .

[[v27-8-15]]

^<<v27-8-15,15>>^ Eu estava procurando entender o que tinha visto, quando apareceu na minha frente um ser que parecia um homem.

[[v27-8-16]]

^<<v27-8-16,16>>^ E ouvi uma voz humana que vinha do rio Ulai e que gritou assim: — Gabriel, explique a visão a esse homem.

[[v27-8-17]]

^<<v27-8-17,17>>^ Aí Gabriel chegou mais perto de mim, e isso me deixou muito assustado. Eu me ajoelhei e encostei o rosto no chão. E ele disse: — Você, homem mortal , precisa entender a visão, pois ela é a respeito do tempo do fim.

[[v27-8-18]]

^<<v27-8-18,18>>^ Ele ainda falava quando desmaiei e caí de bruços no chão. Mas ele me pegou, me pôs de pé

[[v27-8-19]]

^<<v27-8-19,19>>^ e disse: — Eu vou lhe contar o que vai acontecer quando passar a ira  de Deus, pois essa visão é a respeito do tempo marcado para o fim.

[[v27-8-20]]

^<<v27-8-20,20>>^ O carneiro com dois chifres, que você viu, representa os reis da Média e da Pérsia.

[[v27-8-21]]

^<<v27-8-21,21>>^ O bode é o rei da Grécia, e o seu chifre grande é o primeiro rei desse país.

[[v27-8-22]]

^<<v27-8-22,22>>^ Os quatro chifres que nasceram quando o primeiro chifre foi quebrado representam os quatro reinos em que o país será dividido, mas esses reinos não serão tão poderosos como o primeiro.

[[v27-8-23]]

^<<v27-8-23,23>>^ Quando o fim desses reinos estiver perto, e as suas maldades tiverem chegado ao máximo, aparecerá um rei cruel e enganador.

[[v27-8-24]]

^<<v27-8-24,24>>^ Ele ficará cada vez mais poderoso, mas não pela sua própria força. Causará destruições terríveis, acabará com povos poderosos e também com o povo de Deus. Fará o que quiser e prosperará sempre.

[[v27-8-25]]

^<<v27-8-25,25>>^ Com a sua presença, ele enganará a todos; ficará cada vez mais orgulhoso e matará muitas pessoas à traição. Finalmente, ele desafiará a Deus, o Rei dos reis, mas será destruído sem o uso de força humana.

[[v27-8-26]]

^<<v27-8-26,26>>^ E Gabriel terminou assim: — Você já ouviu a verdadeira explicação dos sacrifícios da tarde e da manhã. Mas não diga a ninguém o que quer dizer a visão que você teve, pois ainda vai demorar muito tempo até que ela se cumpra.

[[v27-8-27]]

^<<v27-8-27,27>>^ Eu, Daniel, passei vários dias abatido e doente. Depois, fiquei bom e comecei a tratar dos negócios do governo. Mas continuei muito preocupado com a visão, pois não conseguia entendê-la.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]