include::./index.adoc[]

[[v27-3-0]]
=== Daniel, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-3-1]]

^<<v27-3-1,1>>^ O rei Nabucodonosor mandou fazer uma estátua que media vinte e sete metros de altura por dois metros e setenta de largura e ordenou que a pusessem na planície de Durá, na província  da Babilônia.

[[v27-3-2]]

^<<v27-3-2,2>>^ Depois, ordenou que todos os governadores regionais, os prefeitos, os governadores das províncias, os juízes, os tesoureiros, os magistrados, os conselheiros e todas as outras autoridades viessem à cerimônia de inauguração da estátua.

[[v27-3-3]]

^<<v27-3-3,3>>^ Todos eles vieram e ficaram de pé em frente da estátua para a cerimônia de inauguração.

[[v27-3-4]]

^<<v27-3-4,4>>^ Aí o encarregado de anunciar o começo da cerimônia disse em voz alta: — Povos de todas as nações, raças e línguas!

[[v27-3-5]]

^<<v27-3-5,5>>^ Quando ouvirem o som das trombetas, das flautas, das cítaras, das liras , das harpas  e dos outros instrumentos musicais, ajoelhem-se todos e adorem a estátua de ouro que o rei Nabucodonosor mandou fazer.

[[v27-3-6]]

^<<v27-3-6,6>>^ Quem não se ajoelhar e não adorar a estátua será jogado na mesma hora numa fornalha acesa.

[[v27-3-7]]

^<<v27-3-7,7>>^ Assim, logo que os instrumentos começaram a tocar, todas as pessoas que estavam ali se ajoelharam e adoraram a estátua de ouro.

[[v27-3-8]]

^<<v27-3-8,8>>^ Foi nessa hora que alguns astrólogos aproveitaram a ocasião para acusar os judeus.

[[v27-3-9]]

^<<v27-3-9,9>>^ Eles disseram ao rei Nabucodonosor: — Que o rei viva para sempre!

[[v27-3-10]]

^<<v27-3-10,10>>^ O senhor deu a seguinte ordem: "Quando ouvirem o som dos instrumentos musicais, todos se ajoelharão e adorarão a estátua de ouro.

[[v27-3-11]]

^<<v27-3-11,11>>^ Quem desobedecer a essa ordem será jogado numa fornalha acesa."

[[v27-3-12]]

^<<v27-3-12,12>>^ Ora, o senhor pôs como administradores da província da Babilônia alguns judeus. Esses judeus — Sadraque, Mesaque e Abede-Nego — não respeitam o senhor, não prestam culto ao deus do senhor, nem adoram a estátua de ouro que o senhor mandou fazer.

[[v27-3-13]]

^<<v27-3-13,13>>^ Ao ouvir isso, Nabucodonosor ficou furioso e mandou chamar Sadraque, Mesaque e Abede-Nego. Eles foram levados para o lugar onde o rei estava,

[[v27-3-14]]

^<<v27-3-14,14>>^ e ele lhes disse: — É verdade que vocês não prestam culto ao meu deus, nem adoram a estátua de ouro que eu mandei fazer?

[[v27-3-15]]

^<<v27-3-15,15>>^ Pois bem! Será que agora vocês estão dispostos a se ajoelhar e a adorar a estátua, logo que os instrumentos musicais começarem a tocar? Se não, vocês serão jogados na mesma hora numa fornalha acesa. E quem é o deus que os poderá salvar?

[[v27-3-16]]

^<<v27-3-16,16>>^ Sadraque, Mesaque e Abede-Nego responderam assim: — Ó rei, nós não vamos nos defender.

[[v27-3-17]]

^<<v27-3-17,17>>^ Pois, se o nosso Deus, a quem adoramos, quiser, ele poderá nos salvar da fornalha e nos livrar do seu poder, ó rei.

[[v27-3-18]]

^<<v27-3-18,18>>^ E mesmo que o nosso Deus não nos salve, o senhor pode ficar sabendo que não prestaremos culto ao seu deus, nem adoraremos a estátua de ouro que o senhor mandou fazer.

[[v27-3-19]]

^<<v27-3-19,19>>^ Ao ouvir isso, Nabucodonosor ficou furioso com os três jovens e, vermelho de raiva, mandou que se esquentasse a fornalha sete vezes mais do que de costume.

[[v27-3-20]]

^<<v27-3-20,20>>^ Depois, mandou que os seus soldados mais fortes amarrassem Sadraque, Mesaque e Abede-Nego e os jogassem na fornalha.

[[v27-3-21]]

^<<v27-3-21,21>>^ Os três jovens, completamente vestidos com os seus mantos , capas , chapéus e todas as outras roupas, foram amarrados e jogados na fornalha.

[[v27-3-22]]

^<<v27-3-22,22>>^ A ordem do rei tinha sido cumprida, e a fornalha estava mais quente do que nunca; por isso, as labaredas mataram os soldados que jogaram os três jovens lá dentro.

[[v27-3-23]]

^<<v27-3-23,23>>^ E, amarrados, Sadraque, Mesaque e Abede-Nego caíram na fornalha.

[[v27-3-24]]

^<<v27-3-24,24>>^ De repente, Nabucodonosor se levantou e perguntou, muito espantado, aos seus conselheiros: — Não foram três os homens que amarramos e jogamos na fornalha? — Sim, senhor! — responderam eles.

[[v27-3-25]]

^<<v27-3-25,25>>^ — Como é, então, que estou vendo quatro homens andando soltos na fornalha? — perguntou o rei. — Eles estão passeando lá dentro, sem sofrerem nada. E o quarto homem parece um anjo.

[[v27-3-26]]

^<<v27-3-26,26>>^ Aí o rei chegou perto da porta da fornalha e gritou: — Sadraque, Mesaque e Abede-Nego, servos  do Deus Altíssimo, saiam daí e venham cá! Os três saíram da fornalha,

[[v27-3-27]]

^<<v27-3-27,27>>^ e todas as autoridades que estavam ali chegaram perto deles e viram que o fogo não havia feito nenhum mal a eles. As labaredas não tinham chamuscado nem um cabelo da sua cabeça, as suas roupas não estavam queimadas, e eles não estavam com cheiro de fumaça.

[[v27-3-28]]

^<<v27-3-28,28>>^ O rei gritou: — Que o Deus de Sadraque, Mesaque e Abede-Nego seja louvado! Ele enviou o seu Anjo e salvou os seus servos, que confiam nele. Eles não cumpriram a minha ordem; pelo contrário, escolheram morrer em vez de se ajoelhar e adorar um deus que não era o deles.

[[v27-3-29]]

^<<v27-3-29,29>>^ Por isso, ordeno que qualquer pessoa, seja qual for a sua raça, nação ou língua, que insultar o nome do Deus de Sadraque, Mesaque e Abede-Nego seja cortada em pedaços e que a sua casa seja completamente arrasada. Pois não há outro Deus que possa salvar como este.

[[v27-3-30]]

^<<v27-3-30,30>>^ Então o rei Nabucodonosor colocou os três jovens em cargos ainda mais importantes na província da Babilônia.

'''

xref:027-daniel/027-daniel-002.adoc#v27-2-0[&#60; Capítulo Anterior] | <<v27-3-0,Topo>> | xref:027-daniel/027-daniel-004.adoc#v27-4-0[Próximo Capítulo &#62;]