include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-12-1]]

^<<v27-12-1,1>>^ E o anjo continuou, dizendo: — Nesse tempo, aparecerá o anjo Miguel, o protetor do povo de Deus. Será um tempo de grandes dificuldades, como nunca aconteceu desde que as nações existem. Mas nesse tempo serão salvos todos os do povo de Deus que tiverem os seus nomes escritos no livro de Deus.

[[v27-12-2]]

^<<v27-12-2,2>>^ Muitos dos que já tiverem morrido viverão de novo: uns terão a vida eterna, e outros sofrerão o castigo eterno e a desgraça eterna.

[[v27-12-3]]

^<<v27-12-3,3>>^ Os mestres sábios, aqueles que ensinaram muitas pessoas a fazer o que é certo, brilharão como as estrelas do céu, com um brilho que nunca se apagará.

[[v27-12-4]]

^<<v27-12-4,4>>^ E você, Daniel, não conte nada disso a ninguém. Feche o livro com um selo  para que fique fechado até o momento final. Muitos correrão de cá para lá, procurando ficar mais sábios.

[[v27-12-5]]

^<<v27-12-5,5>>^ Então eu vi dois anjos de pé na beira do rio, um de um lado, e o outro do outro.

[[v27-12-6]]

^<<v27-12-6,6>>^ Um deles perguntou ao anjo vestido com roupas de linho, que estava rio acima: — Quando é que todas essas coisas maravilhosas vão acontecer?

[[v27-12-7]]

^<<v27-12-7,7>>^ O anjo levantou as mãos para o céu e em nome de Deus, que vive para sempre, disse: — Eu juro que tudo isso vai acontecer daqui a três anos e meio quando terminar a perseguição do povo de Deus.

[[v27-12-8]]

^<<v27-12-8,8>>^ Mas eu não entendi bem e por isso perguntei: — Por favor, me diga como é que tudo isso vai acabar.

[[v27-12-9]]

^<<v27-12-9,9>>^ E ele respondeu: — Agora, Daniel, você pode ir embora, pois tudo isso deve ficar em segredo até o fim.

[[v27-12-10]]

^<<v27-12-10,10>>^ Muitos serão postos à prova, e com isso se purificarão, e se aperfeiçoarão. Os maus continuarão na sua maldade, e nenhum deles entenderá o que está acontecendo, mas os sábios entenderão.

[[v27-12-11]]

^<<v27-12-11,11>>^ Depois que os sacrifícios  diários forem suspensos, e o "grande terror" for colocado no Templo, passarão mil duzentos e noventa dias.

[[v27-12-12]]

^<<v27-12-12,12>>^ Felizes aqueles que continuarem fiéis a Deus por mil trezentos e trinta e cinco dias!

[[v27-12-13]]

^<<v27-12-13,13>>^ — E você, Daniel, continue firme até o fim. Você morrerá, mas no fim ressuscitará para receber a sua recompensa.

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-oseias/028-oseias-001.adoc#v28-1-0[Próximo Capítulo &#62;]