include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-10-1]]

^<<v27-10-1,1>>^ Durante o terceiro ano de Ciro como rei da Pérsia, eu, Daniel, também chamado de Beltessazar, recebi uma mensagem de Deus. A mensagem era verdadeira, mas muito difícil de entender; eu recebi a explicação por meio de uma visão.

[[v27-10-2]]

^<<v27-10-2,2>>^ Naquela ocasião, fiquei de luto por três semanas.

[[v27-10-3]]

^<<v27-10-3,3>>^ Durante aquele tempo, não comi nenhuma comida gostosa nem carne, não bebi vinho e não penteei o cabelo.

[[v27-10-4]]

^<<v27-10-4,4>>^ No dia vinte e quatro do primeiro mês do ano, eu estava na beira do grande rio Tigre,

[[v27-10-5]]

^<<v27-10-5,5>>^ quando, de repente, vi um anjo vestido com roupas de linho e usando um cinto de ouro puro.

[[v27-10-6]]

^<<v27-10-6,6>>^ O seu corpo brilhava como pedras preciosas, o rosto parecia um relâmpago, os olhos eram como tochas acesas, os braços e as pernas brilhavam como bronze polido, e a voz soava como o barulho de uma multidão.

[[v27-10-7]]

^<<v27-10-7,7>>^ Eu fui o único que vi essa visão. Os meus companheiros não viram nada, mas ficaram apavorados, e fugiram, e se esconderam.

[[v27-10-8]]

^<<v27-10-8,8>>^ Eu estava ali sozinho enquanto via essa visão impressionante. Fiquei pálido de medo e perdi as forças.

[[v27-10-9]]

^<<v27-10-9,9>>^ Quando ouvi o anjo falar, desmaiei e caí de bruços no chão.

[[v27-10-10]]

^<<v27-10-10,10>>^ Aí a mão de alguém me levantou, e eu fiquei de joelhos, apoiando-me nas palmas das mãos.

[[v27-10-11]]

^<<v27-10-11,11>>^ E o anjo me disse: — Daniel, Deus o ama muito e me mandou falar com você. Fique de pé e preste atenção no que vou dizer. Então eu fiquei de pé, tremendo dos pés até a cabeça.

[[v27-10-12]]

^<<v27-10-12,12>>^ Aí ele disse: — Não fique com medo, Daniel, pois Deus ouviu a sua oração desde a primeira vez que você se humilhou na presença dele a fim de ganhar sabedoria. Eu vim em resposta à sua oração.

[[v27-10-13]]

^<<v27-10-13,13>>^ O anjo protetor do Reino da Pérsia lutou contra mim durante vinte e um dias. Mas Miguel, um dos anjos-chefes, veio me ajudar, pois eu estava lutando sozinho contra os reis da Pérsia.

[[v27-10-14]]

^<<v27-10-14,14>>^ Agora, eu vim explicar a você o que vai acontecer com o seu povo, pois essa visão é a respeito de coisas futuras.

[[v27-10-15]]

^<<v27-10-15,15>>^ Enquanto ele me dizia isso, eu fiquei calado, olhando para o chão.

[[v27-10-16]]

^<<v27-10-16,16>>^ De repente, um ser parecido com um homem tocou nos meus lábios; aí comecei a falar e disse ao anjo que estava na minha frente: — Meu senhor, essa visão me deixou aflito, e estou me sentindo fraco.

[[v27-10-17]]

^<<v27-10-17,17>>^ Como é que eu, o seu criado, posso falar com o senhor? Estou completamente sem forças e quase não posso respirar.

[[v27-10-18]]

^<<v27-10-18,18>>^ Então ele me tocou de novo, e com isso senti as minhas forças voltarem.

[[v27-10-19]]

^<<v27-10-19,19>>^ Ele disse: — Deus o ama. Portanto, não fique com medo. Que a paz de Deus esteja com você. Anime-se! Tenha coragem! Então eu me senti bem mais forte e respondi: — Fale, pois o senhor me deu novas forças.

[[v27-10-20]]

^<<v27-10-20,20>>^ Ele disse: — Sabe por que eu vim falar com você? Foi para dizer-lhe o que está escrito no Livro da Verdade. Mas agora eu preciso ir lutar contra o anjo protetor da Pérsia. Quando a luta acabar, virá o anjo protetor da Grécia. Mas na minha luta contra eles não há ninguém para me ajudar, a não ser Miguel, o anjo protetor de Israel.

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]