include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-7-1]]

^<<v27-7-1,1>>^ Certa noite, durante o primeiro ano de Belsazar como rei da Babilônia, Daniel se deitou na sua cama e sonhou e no sonho teve visões. Quando acordou, ele escreveu aquilo que tinha sonhado.

[[v27-7-2]]

^<<v27-7-2,2>>^ Aqui está o que ele escreveu: No sonho que tive naquela noite, eu vi os ventos soprando de todas as direções e agitando as águas do mar imenso .

[[v27-7-3]]

^<<v27-7-3,3>>^ De repente, saíram do mar quatro monstros enormes, diferentes uns dos outros.

[[v27-7-4]]

^<<v27-7-4,4>>^ O primeiro parecia um leão, mas tinha asas de águia. Enquanto eu olhava, as suas asas foram arrancadas, e ele foi posto de pé para que andasse como homem. E foi dada a ele uma mente humana.

[[v27-7-5]]

^<<v27-7-5,5>>^ O segundo monstro era parecido com um urso. Ele se levantou nas patas de trás e segurava três costelas na boca. E uma voz lhe dizia: "Vá e coma muita carne."

[[v27-7-6]]

^<<v27-7-6,6>>^ Depois, vi o terceiro monstro, e este era parecido com um leopardo. Ele tinha quatro cabeças e nas costas tinha quatro asas, como asas de ave. A este animal foi dada a autoridade para reinar.

[[v27-7-7]]

^<<v27-7-7,7>>^ O quarto monstro que vi naquela visão era terrível, espantoso e muito forte. Tinha enormes dentes de ferro e com eles despedaçava e devorava as suas vítimas; o que sobrava ele esmagava com as patas. Esse monstro era diferente dos outros três e tinha dez chifres.

[[v27-7-8]]

^<<v27-7-8,8>>^ Eu estava olhando os chifres com atenção e notei outro chifre, menor, que nasceu entre os outros. Três chifres foram arrancados para dar lugar a esse chifre menor, que tinha olhos, como os de gente, e uma boca que falava com muito orgulho.

[[v27-7-9]]

^<<v27-7-9,9>>^ Continuei olhando e vi que foram postos alguns tronos. Num deles, assentou-se aquele que sempre existiu. A sua roupa era branca como a neve, e os seus cabelos eram brancos como a lã. O trono e as suas rodas pareciam labaredas de fogo,

[[v27-7-10]]

^<<v27-7-10,10>>^ e de um lugar em frente do trono saía um rio de fogo. Havia ali milhares de pessoas que adoravam aquele que estava sentado no trono, e muitos milhões estavam de pé na presença dele. Começou o julgamento, e foram abertos os livros.

[[v27-7-11]]

^<<v27-7-11,11>>^ Continuei olhando, pois o chifre pequeno ainda estava dizendo palavras orgulhosas. E vi quando o quarto monstro foi morto; e o seu corpo foi despedaçado e jogado no fogo.

[[v27-7-12]]

^<<v27-7-12,12>>^ Quanto aos outros monstros, o poder que tinham foi tirado deles, mas não foram mortos; foi dado a eles mais um pouco de tempo para viverem.

[[v27-7-13]]

^<<v27-7-13,13>>^ Na mesma visão que tive naquela noite, vi um ser parecido com um homem, que vinha entre as nuvens do céu. Ele foi até o lugar onde estava aquele que sempre existiu e foi apresentado a ele.

[[v27-7-14]]

^<<v27-7-14,14>>^ Deram-lhe o poder, a honra e a autoridade de rei, a fim de que os povos de todas as nações, línguas e raças o servissem. O seu poder é eterno, e o seu reino não terá fim.

[[v27-7-15]]

^<<v27-7-15,15>>^ As visões me espantaram, e eu fiquei preocupado com o que tinha visto.

[[v27-7-16]]

^<<v27-7-16,16>>^ Cheguei perto de um dos que estavam ali e pedi que me explicasse o que eu tinha visto. Então ele explicou assim:

[[v27-7-17]]

^<<v27-7-17,17>>^ — Os quatro monstros enormes são quatro reis que vão dominar o mundo.

[[v27-7-18]]

^<<v27-7-18,18>>^ Mas o reino será dado ao povo do Deus Altíssimo, e esse povo reinará para sempre.

[[v27-7-19]]

^<<v27-7-19,19>>^ Eu quis saber também a explicação a respeito do quarto monstro, que era diferente dos outros três, que era terrível e tinha dentes de ferro e unhas de bronze, que despedaçava e devorava as suas vítimas e que esmagava com as patas aquilo que sobrava.

[[v27-7-20]]

^<<v27-7-20,20>>^ Pedi também que me explicasse os dez chifres que esse monstro tinha na cabeça e o outro chifre que havia crescido, derrubando três chifres; esse chifre, que parecia mais forte do que os outros, tinha olhos e uma boca que falava com muito orgulho.

[[v27-7-21]]

^<<v27-7-21,21>>^ Enquanto eu olhava, esse chifre começou a lutar contra o povo de Deus e estava vencendo,

[[v27-7-22]]

^<<v27-7-22,22>>^ até que chegou aquele que sempre existiu. Ele julgou a favor do povo do Deus Altíssimo, pois havia chegado o tempo de esse povo começar a reinar.

[[v27-7-23]]

^<<v27-7-23,23>>^ A explicação que recebi foi esta: — O quarto monstro é um rei, e o reino dele será bem diferente dos outros. Ele conquistará o mundo inteiro, destruirá todas as nações e as deixará arrasadas.

[[v27-7-24]]

^<<v27-7-24,24>>^ Os dez chifres representam dez reis que governarão esse reino. Depois deles, aparecerá outro rei que será diferente dos primeiros; ele derrotará três reis.

[[v27-7-25]]

^<<v27-7-25,25>>^ Ele falará contra Deus e perseguirá o povo do Deus Altíssimo. Procurará mudar a Lei  de Deus e os tempos das festas religiosas. O povo de Deus será dominado por ele durante três anos e meio.

[[v27-7-26]]

^<<v27-7-26,26>>^ Mas depois disso o tribunal o condenará, e assim ele perderá o seu reino, e o seu poder acabará para sempre.

[[v27-7-27]]

^<<v27-7-27,27>>^ Mas o reino, o poder e a glória  serão dados ao povo do Deus Altíssimo, e eles governarão o mundo inteiro para sempre; todos os outros povos os servirão, todos lhes obedecerão.

[[v27-7-28]]

^<<v27-7-28,28>>^ Aqui termina a explicação. Eu continuei muito preocupado com os meus pensamentos, e o meu rosto ficou pálido. Mas eu não disse nada a ninguém.

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]