include::./index.adoc[]

[[v27-4-0]]
=== Daniel, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v27-4-1]]

^<<v27-4-1,1>>^ O rei Nabucodonosor mandou aos povos de todas as nações, raças e línguas a seguinte mensagem: — Felicidade e paz para todos!

[[v27-4-2]]

^<<v27-4-2,2>>^ Quero que todos saibam dos maravilhosos milagres que o Deus Altíssimo fez em meu favor.

[[v27-4-3]]

^<<v27-4-3,3>>^ Grandes são os seus milagres, e as coisas que ele fez são espantosas! Pois ele é o Rei eterno e reinará para sempre.

[[v27-4-4]]

^<<v27-4-4,4>>^ E continuou: — Eu, Nabucodonosor, vivia sossegado no meu palácio, e tudo ia muito bem.

[[v27-4-5]]

^<<v27-4-5,5>>^ Mas certa noite tive um sonho que me deixou preocupado. Enquanto dormia, ideias e visões horrorosas tomaram conta de mim.

[[v27-4-6]]

^<<v27-4-6,6>>^ Por isso, mandei chamar todos os sábios da Babilônia, para que eles me explicassem o sonho.

[[v27-4-7]]

^<<v27-4-7,7>>^ Vieram então os sábios, os adivinhos, os astrólogos e os feiticeiros, e eu lhes contei o sonho, mas nenhum deles pôde explicá-lo.

[[v27-4-8]]

^<<v27-4-8,8>>^ Finalmente, apresentou-se Daniel, conhecido também como Beltessazar, nome que recebeu em honra do meu deus. O espírito dos santos deuses está nele, e por isso eu lhe contei o meu sonho. Eu disse:

[[v27-4-9]]

^<<v27-4-9,9>>^ "Beltessazar, chefe dos adivinhos, eu sei que o espírito dos santos deuses está em você e que não há mistério que você não possa explicar. Por isso vou lhe contar o sonho e quero que você explique o que ele quer dizer.

[[v27-4-10]]

^<<v27-4-10,10>>^ Eu estava deitado na cama e, de repente, tive uma visão. Nela vi uma árvore muito alta, plantada no centro da terra.

[[v27-4-11]]

^<<v27-4-11,11>>^ A árvore cresceu e cresceu até tocar o céu e era tão grande, que podia ser vista de qualquer lugar do mundo.

[[v27-4-12]]

^<<v27-4-12,12>>^ As suas folhas eram belas, e ela dava tantas frutas, que o mundo todo podia se alimentar delas. Animais selvagens descansavam na sombra da árvore, as aves faziam ninhos nos seus galhos, e todos os seres vivos se alimentavam das suas frutas.

[[v27-4-13]]

^<<v27-4-13,13>>^ Eu ainda estava sonhando, quando, de repente, vi um anjo-vigia que descia do céu

[[v27-4-14]]

^<<v27-4-14,14>>^ e dizia em voz muito alta: ‘Derrubem a árvore, cortem os seus galhos, tirem as folhas e joguem fora as frutas. Espantem os animais que estão descansando na sua sombra e as aves que estão nos seus galhos.

[[v27-4-15]]

^<<v27-4-15,15>>^ Mas deixem ficar o toco e as suas raízes e o amarrem com correntes de ferro e de bronze, no meio do capim bravo, no campo. Assim o sereno cairá sobre esse toco — esse homem —, e ele comerá capim como os animais.

[[v27-4-16]]

^<<v27-4-16,16>>^ Ele perderá o juízo e começará a pensar como animal; sete anos viverá assim.

[[v27-4-17]]

^<<v27-4-17,17>>^ Esta é a sentença dada pelos anjos, pelos anjos-vigias do céu, a fim de que todos saibam que o Deus Altíssimo domina todos os reinos do mundo. Ele dá esses reinos a quem quer, mesmo ao mais humilde de todos os homens.’ "

[[v27-4-18]]

^<<v27-4-18,18>>^ E Nabucodonosor terminou, dizendo: — Foi esse o sonho que eu tive, e nenhum dos meus sábios pôde me explicar o que ele quer dizer. Mas você, Beltessazar, pode dar a explicação porque o espírito dos santos deuses está em você. Portanto, explique o que o sonho quer dizer.

[[v27-4-19]]

^<<v27-4-19,19>>^ Ao ouvir isso, Daniel, também conhecido como Beltessazar, ficou espantado e por alguns instantes não sabia o que pensar. O rei lhe disse: — Beltessazar, não se preocupe com o sonho nem com o que ele quer dizer. Mas Daniel respondeu: — Ó rei, quem dera que o sonho e a sua mensagem não fossem a respeito do senhor, mas a respeito dos seus inimigos!

[[v27-4-20]]

^<<v27-4-20,20>>^ O senhor viu uma árvore que cresceu e cresceu até tocar o céu e que era tão grande, que podia ser vista de qualquer lugar do mundo.

[[v27-4-21]]

^<<v27-4-21,21>>^ As suas folhas eram belas, e ela dava tantas frutas, que o mundo todo podia se alimentar delas. Animais selvagens descansavam na sombra da árvore, e as aves faziam ninhos nos seus galhos.

[[v27-4-22]]

^<<v27-4-22,22>>^ — Aquela árvore, ó rei, é o senhor. Pois o senhor se tornou poderoso, e o seu poder aumentou tanto, que chegou até o céu, e o seu domínio se estendeu pelo mundo inteiro.

[[v27-4-23]]

^<<v27-4-23,23>>^ E o senhor viu também um anjo-vigia descendo do céu e dizendo: "Derrubem a árvore e quebrem todos os seus galhos, mas deixem ficar o toco e as suas raízes e o amarrem com correntes de ferro e de bronze, para que fique no meio do capim bravo, no campo. Assim o sereno cairá sobre esse homem, e ele terá de comer o que os animais comem. Sete anos ele viverá assim."

[[v27-4-24]]

^<<v27-4-24,24>>^ E Daniel continuou: — E agora vou dar a explicação. Este sonho trata da sentença do Deus Altíssimo contra o senhor, ó rei.

[[v27-4-25]]

^<<v27-4-25,25>>^ O senhor será expulso do meio dos seres humanos e ficará morando com os animais selvagens. O senhor comerá capim como os bois, dormirá ao ar livre e ficará molhado pelo sereno. Isso durará sete anos, até que o senhor reconheça que o Deus Altíssimo domina todos os reinos do mundo e coloca como rei o homem que ele quer.

[[v27-4-26]]

^<<v27-4-26,26>>^ A ordem do anjo para que deixassem ficar o toco da árvore com as raízes quer dizer que o senhor será rei de novo, mas só quando confessar que Deus domina o mundo inteiro.

[[v27-4-27]]

^<<v27-4-27,27>>^ Ó rei, aceite o meu conselho. Deixe de pecar e faça o que é certo; acabe com as suas maldades e ajude os pobres. Assim talvez o senhor possa continuar a viver em paz e felicidade.

[[v27-4-28]]

^<<v27-4-28,28>>^ E, de fato, tudo isso aconteceu com o rei Nabucodonosor.

[[v27-4-29]]

^<<v27-4-29,29>>^ Doze meses mais tarde, ele estava passeando no terraço do seu palácio na cidade de Babilônia

[[v27-4-30]]

^<<v27-4-30,30>>^ e disse: — Como é grande a cidade de Babilônia! Com o meu grande poder, eu a construí para ser a capital do meu reino, a fim de mostrar a todos a minha grandeza e a minha glória .

[[v27-4-31]]

^<<v27-4-31,31>>^ O rei ainda estava falando quando veio uma voz do céu, que disse: — Preste atenção, rei Nabucodonosor! Este reino não é mais seu.

[[v27-4-32]]

^<<v27-4-32,32>>^ Você será expulso do meio dos seres humanos, ficará morando com os animais selvagens e comerá capim como os bois. Isso durará sete anos, até que você reconheça que o Deus Altíssimo domina todos os reinos do mundo e coloca como rei quem ele quer.

[[v27-4-33]]

^<<v27-4-33,33>>^ Naquele mesmo instante, cumpriu-se a sentença contra Nabucodonosor. Ele foi expulso do meio dos seres humanos e começou a comer capim como os bois. Dormia ao ar livre e ficava molhado pelo sereno. O seu cabelo ficou comprido, parecido com penas de águia, e as suas unhas cresceram tanto, que pareciam garras de um gavião.

[[v27-4-34]]

^<<v27-4-34,34>>^ O rei disse: — Depois de passados os sete anos, eu olhei para o céu, e o meu juízo voltou. Aí agradeci ao Deus Altíssimo e dei louvor e glória  àquele que vive para sempre. Eu disse: "O poder do Altíssimo é eterno; o seu reino  não terá fim.

[[v27-4-35]]

^<<v27-4-35,35>>^ Para ele, os seres humanos não têm nenhum valor; ele governa todos os anjos do céu e todos os moradores da terra. Não há ninguém que possa impedi-lo de fazer o que quer; não há ninguém que possa obrigá-lo a explicar o que faz."

[[v27-4-36]]

^<<v27-4-36,36>>^ — Logo que o meu juízo voltou — continuou Nabucodonosor —, eu recebi outra vez a minha honra, a minha majestade e a glória do meu reino. Os meus conselheiros e as altas autoridades do meu governo me receberam de volta. Fui rei de novo, com mais poder do que antes.

[[v27-4-37]]

^<<v27-4-37,37>>^ Portanto, eu, o rei Nabucodonosor, agradeço ao Rei do céu e lhe dou louvor e glória. Tudo o que ele faz é certo e justo, e ele pode humilhar qualquer pessoa orgulhosa.

'''

xref:027-daniel/027-daniel-003.adoc#v27-3-0[&#60; Capítulo Anterior] | <<v27-4-0,Topo>> | xref:027-daniel/027-daniel-005.adoc#v27-5-0[Próximo Capítulo &#62;]