include::./index.adoc[]

[[v13-6-0]]
=== 1 Crônicas, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-6-1]]

^<<v13-6-1,1>>^ Levi foi pai de três filhos: Gérson, Coate e Merari.

[[v13-6-2]]

^<<v13-6-2,2>>^ Coate foi pai de quatro filhos: Anrão, Isar, Hebrom e Uziel.

[[v13-6-3]]

^<<v13-6-3,3>>^ Anrão foi pai de dois filhos: Arão e Moisés, e de uma filha chamada Míriam. Arão foi pai de quatro filhos: Nadabe, Abiú, Eleazar e Itamar.

[[v13-6-4]]

^<<v13-6-4,4>>^ Eleazar foi pai de Fineias, e Fineias foi pai de Abisua;

[[v13-6-5]]

^<<v13-6-5,5>>^ Abisua foi pai de Buqui, e Buqui foi pai de Uzi;

[[v13-6-6]]

^<<v13-6-6,6>>^ Uzi foi pai de Zeraías, e Zeraías foi pai de Meraiote;

[[v13-6-7]]

^<<v13-6-7,7>>^ Meraiote foi pai de Amariá, e Amariá foi pai de Aitube;

[[v13-6-8]]

^<<v13-6-8,8>>^ Aitube foi pai de Zadoque, e Zadoque foi pai de Aimaás;

[[v13-6-9]]

^<<v13-6-9,9>>^ Aimaás foi pai de Azarias, e Azarias foi pai de Joanã;

[[v13-6-10]]

^<<v13-6-10,10>>^ Joanã foi pai de Azarias, que serviu como sacerdote no Templo que Salomão construiu em Jerusalém.

[[v13-6-11]]

^<<v13-6-11,11>>^ Azarias foi pai de Amariá, e Amariá foi pai de Aitube;

[[v13-6-12]]

^<<v13-6-12,12>>^ Aitube foi pai de Zadoque, e Zadoque foi pai de Salum;

[[v13-6-13]]

^<<v13-6-13,13>>^ Salum foi pai de Hilquias, e Hilquias foi pai de Azarias;

[[v13-6-14]]

^<<v13-6-14,14>>^ Azarias foi pai de Seraías, e Seraías foi pai de Jeozadaque.

[[v13-6-15]]

^<<v13-6-15,15>>^ Jeozadaque foi levado como prisioneiro junto com os moradores de Judá e de Jerusalém que o Senhor  levou para o cativeiro  por meio do rei Nabucodonosor.

[[v13-6-16]]

^<<v13-6-16,16>>^ Levi foi pai de três filhos: Gérson, Coate e Merari.

[[v13-6-17]]

^<<v13-6-17,17>>^ Gérson foi pai de Libni e Simei.

[[v13-6-18]]

^<<v13-6-18,18>>^ Coate foi pai de Anrão, Isar, Hebrom e Uziel.

[[v13-6-19]]

^<<v13-6-19,19>>^ Merari foi pai de Mali e Musi.

[[v13-6-20]]

^<<v13-6-20,20>>^ Gérson foi pai de Libni, Libni foi pai de Jaate, e Jaate foi pai de Zima;

[[v13-6-21]]

^<<v13-6-21,21>>^ Zima foi pai de Joá, Joá foi pai de Ido, Ido foi pai de Zera, e Zera foi pai de Jeaterai.

[[v13-6-22]]

^<<v13-6-22,22>>^ Coate foi pai de Aminadabe, Aminadabe foi pai de Corá, e Corá foi pai de Assir;

[[v13-6-23]]

^<<v13-6-23,23>>^ Assir foi pai de Elcana, Elcana foi pai de Ebiasafe, e Ebiasafe foi pai de Assir;

[[v13-6-24]]

^<<v13-6-24,24>>^ Assir foi pai de Taate, Taate foi pai de Uriel, Uriel foi pai de Uzias, e Uzias foi pai de Saul.

[[v13-6-25]]

^<<v13-6-25,25>>^ Elcana foi pai de dois filhos: Amasai e Aimote.

[[v13-6-26]]

^<<v13-6-26,26>>^ Aimote foi pai de Elcana, Elcana foi pai de Zofai, e Zofai foi pai de Naate;

[[v13-6-27]]

^<<v13-6-27,27>>^ Naate foi pai de Eliabe, Eliabe foi pai de Jeroão, e Jeroão foi pai de Elcana.

[[v13-6-28]]

^<<v13-6-28,28>>^ Samuel foi pai de dois filhos: Joel, o mais velho, e Abias.

[[v13-6-29]]

^<<v13-6-29,29>>^ Merari foi pai de Mali, Mali foi pai de Libni, Libni foi pai de Simei, e Simei foi pai de Uzá;

[[v13-6-30]]

^<<v13-6-30,30>>^ Uzá foi pai de Simeia, Simeia foi pai de Hagias, e Hagias foi pai de Asaías.

[[v13-6-31]]

^<<v13-6-31,31>>^ São estes os homens que o rei Davi encarregou da música no lugar de adoração em Jerusalém, depois que a arca da aliança  foi colocada lá.

[[v13-6-32]]

^<<v13-6-32,32>>^ Eles se revezavam nos seus deveres na Tenda da Presença de Deus , antes de o rei Salomão construir o Templo.

[[v13-6-33]]

^<<v13-6-33,33>>^ São estes os que ocupavam esse cargo: Do grupo de famílias de Coate: Hemã, o regente do primeiro coro, era filho de Joel, e Joel era filho de Samuel;

[[v13-6-34]]

^<<v13-6-34,34>>^ Samuel era filho de Elcana, Elcana era filho de Jeroão, Jeroão era filho de Eliel, e Eliel era filho de Toá;

[[v13-6-35]]

^<<v13-6-35,35>>^ Toá era filho de Zufe, Zufe era filho de Elcana, Elcana era filho de Maate, e Maate era filho de Amasai;

[[v13-6-36]]

^<<v13-6-36,36>>^ Amasai era filho de Elcana, Elcana era filho de Joel, Joel era filho de Azarias, e Azarias era filho de Sofonias;

[[v13-6-37]]

^<<v13-6-37,37>>^ Sofonias era filho de Taate, Taate era filho de Assir, Assir era filho de Ebiasafe, e Ebiasafe era filho de Corá;

[[v13-6-38]]

^<<v13-6-38,38>>^ Corá era filho de Isar, Isar era filho de Coate, Coate era filho de Levi, e Levi era filho de Jacó.

[[v13-6-39]]

^<<v13-6-39,39>>^ Asafe, o regente do segundo coro, era filho de Berequias, e Berequias era filho de Simeia;

[[v13-6-40]]

^<<v13-6-40,40>>^ Simeia era filho de Micael, Micael era filho de Baaseias, e Baaseias era filho de Malquias;

[[v13-6-41]]

^<<v13-6-41,41>>^ Malquias era filho de Etni, Etni era filho de Zera, e Zera era filho de Adaías;

[[v13-6-42]]

^<<v13-6-42,42>>^ Adaías era filho de Etã, Etã era filho de Zima, e Zima era filho de Simei;

[[v13-6-43]]

^<<v13-6-43,43>>^ Simei era filho de Jaate, Jaate era filho de Gérson, e Gérson era filho de Levi.

[[v13-6-44]]

^<<v13-6-44,44>>^ Etã, do grupo de famílias de Merari, era o regente do terceiro coro. Etã era filho de Quisi, Quisi era filho de Abdi, e Abdi era filho de Maluque;

[[v13-6-45]]

^<<v13-6-45,45>>^ Maluque era filho de Hasabias, Hasabias era filho de Amazias, e Amazias era filho de Hilquias;

[[v13-6-46]]

^<<v13-6-46,46>>^ Hilquias era filho de Anzi, Anzi era filho de Bani, e Bani era filho de Semer;

[[v13-6-47]]

^<<v13-6-47,47>>^ Semer era filho de Mali, Mali era filho de Musi, Musi era filho de Merari, e Merari era filho de Levi.

[[v13-6-48]]

^<<v13-6-48,48>>^ Os seus colegas levitas  estavam encarregados de todos os outros serviços do lugar de adoração em Jerusalém.

[[v13-6-49]]

^<<v13-6-49,49>>^ Arão e os seus filhos apresentavam as ofertas de incenso e ofereciam os sacrifícios  que eram completamente queimados no altar. Eles eram responsáveis por toda a adoração no Lugar Santíssimo  e pelos sacrifícios por meio dos quais Deus perdoava os pecados do povo de Israel. Eles faziam tudo isso de acordo com as instruções dadas por Moisés, servo  de Deus.

[[v13-6-50]]

^<<v13-6-50,50>>^ Arão foi pai de Eleazar, Eleazar foi pai de Fineias, e Fineias foi pai de Abisua;

[[v13-6-51]]

^<<v13-6-51,51>>^ Abisua foi pai de Buqui, Buqui foi pai de Uzi, e Uzi foi pai de Zeraías;

[[v13-6-52]]

^<<v13-6-52,52>>^ Zeraías foi pai de Meraiote, Meraiote foi pai de Amariá, e Amariá foi pai de Aitube;

[[v13-6-53]]

^<<v13-6-53,53>>^ Aitube foi pai de Zadoque, e Zadoque foi pai de Aimaás.

[[v13-6-54]]

^<<v13-6-54,54>>^ Este é o território que foi dado ao grupo de famílias de Coate, descendentes de Arão. Eles receberam a primeira parte da terra dada aos levitas ,

[[v13-6-55]]

^<<v13-6-55,55>>^ isto é, a cidade de Hebrom, no território da tribo  de Judá, e as terras de pastagens que ficavam ao seu redor.

[[v13-6-56]]

^<<v13-6-56,56>>^ Mas os campos e povoados que pertenciam à cidade foram dados a Calebe, filho de Jefoné.

[[v13-6-57]]

^<<v13-6-57,57>>^ As seguintes cidades foram dadas aos descendentes de Arão: Hebrom, que era uma das cidades para fugitivos , e as cidades de Jatir, Libna, Estemoa, Hilém, Debir, Asã e Bete-Semes, com as terras de pastagens que ficavam ao redor delas.

[[v13-6-58]]

^<<v13-6-58,58>>^ As seguintes cidades foram dadas aos descendentes de Arão: Hebrom, que era uma das cidades para fugitivos , e as cidades de Jatir, Libna, Estemoa, Hilém, Debir, Asã e Bete-Semes, com as terras de pastagens que ficavam ao redor delas.

[[v13-6-59]]

^<<v13-6-59,59>>^ As seguintes cidades foram dadas aos descendentes de Arão: Hebrom, que era uma das cidades para fugitivos , e as cidades de Jatir, Libna, Estemoa, Hilém, Debir, Asã e Bete-Semes, com as terras de pastagens que ficavam ao redor delas.

[[v13-6-60]]

^<<v13-6-60,60>>^ No território de Benjamim eles receberam as seguintes cidades com as suas terras de pastagens: Geba, Alemete e Anatote. Isso dava um total de treze cidades, para nelas morarem as famílias que descendiam de Arão.

[[v13-6-61]]

^<<v13-6-61,61>>^ Dez cidades no território de Manassés do Oeste foram dadas por sorteio  ao resto do grupo de famílias de Coate, família por família.

[[v13-6-62]]

^<<v13-6-62,62>>^ Ao grupo de famílias de Gérson, família por família, foram dadas treze cidades nos territórios de Aser, Naftali e Manassés do Leste, na região de Basã.

[[v13-6-63]]

^<<v13-6-63,63>>^ Do mesmo modo, doze cidades nos territórios de Rúben, Gade e Zebulom foram dadas ao grupo de famílias de Merari, família por família.

[[v13-6-64]]

^<<v13-6-64,64>>^ Dessa maneira o povo de Israel deu aos levitas, para nelas morarem, cidades e as terras de pastagens que ficavam ao seu redor.

[[v13-6-65]]

^<<v13-6-65,65>>^ (As cidades que ficavam nos territórios de Judá, Simeão e Benjamim, das quais se falou acima, também foram dadas por sorteio.)

[[v13-6-66]]

^<<v13-6-66,66>>^ Do grupo de famílias de Coate, algumas receberam no território de Efraim as seguintes cidades e terras de pastagens:

[[v13-6-67]]

^<<v13-6-67,67>>^ Siquém, uma cidade para fugitivos que ficava na região montanhosa; Gezer,

[[v13-6-68]]

^<<v13-6-68,68>>^ Jocmeão, Bete-Horom,

[[v13-6-69]]

^<<v13-6-69,69>>^ Aijalom e Gate-Rimom.

[[v13-6-70]]

^<<v13-6-70,70>>^ No território de Manassés do Oeste, eles receberam as cidades de Aner e Bileão, com as terras de pastagens que ficavam ao seu redor.

[[v13-6-71]]

^<<v13-6-71,71>>^ Do grupo de famílias de Gérson, estas receberam as seguintes cidades, com as terras de pastagens que ficavam ao seu redor: No território de Manassés do Leste: Golã, na região de Basã, e Astarote.

[[v13-6-72]]

^<<v13-6-72,72>>^ No território de Issacar: Quedes, Daberate,

[[v13-6-73]]

^<<v13-6-73,73>>^ Ramote e Aném.

[[v13-6-74]]

^<<v13-6-74,74>>^ No território de Aser: Masal, Abdom,

[[v13-6-75]]

^<<v13-6-75,75>>^ Hucoque e Reobe.

[[v13-6-76]]

^<<v13-6-76,76>>^ No território de Naftali: Quedes, na região da Galileia, Hamom e Quiriataim.

[[v13-6-77]]

^<<v13-6-77,77>>^ Do grupo de famílias de Merari, estas receberam as seguintes cidades, com as terras de pastagens que ficavam ao seu redor: No território de Zebulom: Rimono e Tabor.

[[v13-6-78]]

^<<v13-6-78,78>>^ No território de Rúben, a leste do rio Jordão, em frente de Jericó : Bezer, no planalto, Jasa,

[[v13-6-79]]

^<<v13-6-79,79>>^ Quedemote e Mefaate.

'''

xref:013-1-cronicas/013-1-cronicas-005.adoc#v13-5-0[&#60; Capítulo Anterior] | <<v13-6-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-007.adoc#v13-7-0[Próximo Capítulo &#62;]