include::./index.adoc[]

[[v13-15-0]]
=== 1 Crônicas, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-15-1]]

^<<v13-15-1,1>>^ Para o seu próprio uso, Davi construiu casas na Cidade de Davi . Também preparou um lugar para a arca da aliança  de Deus e armou uma barraca para ela.

[[v13-15-2]]

^<<v13-15-2,2>>^ Então disse: — Somente levitas  podem carregar a arca da aliança porque foram eles que o Senhor  Deus escolheu a fim de carregá-la e para servi-lo para sempre.

[[v13-15-3]]

^<<v13-15-3,3>>^ Então Davi chamou todo o povo de Israel a Jerusalém a fim de trazer a arca da aliança para o lugar que ele havia preparado para ela.

[[v13-15-4]]

^<<v13-15-4,4>>^ Em seguida mandou buscar os descendentes de Arão e os levitas.

[[v13-15-5]]

^<<v13-15-5,5>>^ Do grupo de famílias levitas de Coate veio Uriel, chefiando cento e vinte homens do seu grupo de famílias;

[[v13-15-6]]

^<<v13-15-6,6>>^ do grupo de famílias de Merari veio Asaías, chefiando duzentos e vinte homens;

[[v13-15-7]]

^<<v13-15-7,7>>^ do grupo de famílias de Gérson veio Joel, chefiando cento e trinta;

[[v13-15-8]]

^<<v13-15-8,8>>^ do grupo de famílias de Elisafã veio Semaías, chefiando duzentos;

[[v13-15-9]]

^<<v13-15-9,9>>^ do grupo de famílias de Hebrom veio Eliel, chefiando oitenta;

[[v13-15-10]]

^<<v13-15-10,10>>^ e do grupo de famílias de Uziel veio Aminadabe, chefiando cento e doze.

[[v13-15-11]]

^<<v13-15-11,11>>^ Davi chamou os sacerdotes Zadoque e Abiatar e os levitas Uriel, Asaías, Joel, Semaías, Eliel e Aminadabe.

[[v13-15-12]]

^<<v13-15-12,12>>^ Então disse aos levitas: — Vocês são os líderes dos grupos de famílias levitas. Purifiquem-se  e purifiquem os seus irmãos levitas, para que possam trazer a arca da aliança do Senhor , o Deus de Israel, para o lugar que preparei para ela.

[[v13-15-13]]

^<<v13-15-13,13>>^ Não foram vocês que a carregaram da primeira vez, e por isso o Senhor , nosso Deus, nos castigou por não o termos consultado como devíamos.

[[v13-15-14]]

^<<v13-15-14,14>>^ Então os sacerdotes e os levitas se purificaram a fim de carregar a arca da aliança do Senhor , o Deus de Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ Os levitas a carregaram nos ombros pelos cabos, como Deus havia mandado por meio de Moisés.

[[v13-15-16]]

^<<v13-15-16,16>>^ Davi mandou que os líderes dos levitas nomeassem vários levitas para cantar e para tocar música alegre nas harpas , e nas liras , e com os pratos.

[[v13-15-17]]

^<<v13-15-17,17>>^ Dos grupos de famílias de cantores eles escolheram para tocar pratos de metal os seguintes homens: Hemã, filho de Joel; o seu parente Asafe, filho de Berequias; e Etã, filho de Cuchaías, que era do grupo de famílias de Merari. Escolheram os levitas Zacarias, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Maaseias e Benaías para ajudá-los; eles tocavam as harpas, que alcançavam notas altas. Para tocarem as liras, que alcançavam notas baixas, escolheram os seguintes levitas: Matitias, Elifeleu, Micneias, Azazias e os guardas do Templo, Obede-Edom e Jeiel.

[[v13-15-18]]

^<<v13-15-18,18>>^ Dos grupos de famílias de cantores eles escolheram para tocar pratos de metal os seguintes homens: Hemã, filho de Joel; o seu parente Asafe, filho de Berequias; e Etã, filho de Cuchaías, que era do grupo de famílias de Merari. Escolheram os levitas Zacarias, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Maaseias e Benaías para ajudá-los; eles tocavam as harpas, que alcançavam notas altas.

[[v13-15-19]]

^<<v13-15-19,19>>^ Dos grupos de famílias de cantores eles escolheram para tocar pratos de metal os seguintes homens: Hemã, filho de Joel; o seu parente Asafe, filho de Berequias; e Etã, filho de Cuchaías, que era do grupo de famílias de Merari. Escolheram os levitas Zacarias, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Maaseias e Benaías para ajudá-los; eles tocavam as harpas, que alcançavam notas altas.

[[v13-15-20]]

^<<v13-15-20,20>>^ Dos grupos de famílias de cantores eles escolheram para tocar pratos de metal os seguintes homens: Hemã, filho de Joel; o seu parente Asafe, filho de Berequias; e Etã, filho de Cuchaías, que era do grupo de famílias de Merari. Escolheram os levitas Zacarias, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Maaseias e Benaías para ajudá-los; eles tocavam as harpas, que alcançavam notas altas.

[[v13-15-21]]

^<<v13-15-21,21>>^ Dos grupos de famílias de cantores eles escolheram para tocar pratos de metal os seguintes homens: Hemã, filho de Joel; o seu parente Asafe, filho de Berequias; e Etã, filho de Cuchaías, que era do grupo de famílias de Merari. Escolheram os levitas Zacarias, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Maaseias e Benaías para ajudá-los; eles tocavam as harpas, que alcançavam notas altas.

[[v13-15-22]]

^<<v13-15-22,22>>^ Porque era entendido em música, Quenanias foi escolhido para dirigir os músicos levitas.

[[v13-15-23]]

^<<v13-15-23,23>>^ Berequias e Elcana, junto com Obede-Edom e Jeías, foram escolhidos para serem os guardas da arca da aliança. Para tocarem trombeta em frente da arca, foram escolhidos os sacerdotes Sebanias, Josafá, Netanel, Amasai, Zacarias, Benaías e Eliézer.

[[v13-15-24]]

^<<v13-15-24,24>>^ Berequias e Elcana, junto com Obede-Edom e Jeías, foram escolhidos para serem os guardas da arca da aliança. Para tocarem trombeta em frente da arca, foram escolhidos os sacerdotes Sebanias, Josafá, Netanel, Amasai, Zacarias, Benaías e Eliézer.

'''

xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[Próximo Capítulo &#62;]