include::./index.adoc[]

[[v13-18-0]]
=== 1 Crônicas, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-18-1]]

^<<v13-18-1,1>>^ Algum tempo depois, Davi atacou de novo os filisteus e os derrotou. Tomou deles a cidade de Gate e os povoados que ficavam ao seu redor.

[[v13-18-2]]

^<<v13-18-2,2>>^ Também derrotou os moabitas, que ficaram dominados por ele e lhe pagavam impostos.

[[v13-18-3]]

^<<v13-18-3,3>>^ Depois Davi atacou Hadadezer, que era o rei de Zoba, na Síria, perto da região de Hamate. Isso aconteceu quando Hadadezer estava tentando conquistar a região que ficava ao longo do rio Eufrates.

[[v13-18-4]]

^<<v13-18-4,4>>^ Davi tomou de Hadadezer mil carros de guerra e prendeu sete mil cavaleiros e vinte mil soldados de infantaria. Ele também ficou com cavalos suficientes para puxarem cem carros de guerra e aleijou os outros.

[[v13-18-5]]

^<<v13-18-5,5>>^ Os sírios de Damasco foram socorrer Hadadezer, e Davi os atacou e matou vinte e dois mil deles.

[[v13-18-6]]

^<<v13-18-6,6>>^ Em seguida colocou acampamentos militares no território dos sírios de Damasco. Davi os dominou, e eles lhe pagavam impostos. O Senhor  Deus fez com que Davi fosse vitorioso em todos os lugares.

[[v13-18-7]]

^<<v13-18-7,7>>^ Davi tomou dos oficiais de Hadadezer os escudos  de ouro que eles usavam e os levou para Jerusalém.

[[v13-18-8]]

^<<v13-18-8,8>>^ Também tomou uma grande quantidade de bronze das cidades de Tibate e de Cum, que eram governadas por Hadadezer. (Anos mais tarde, Salomão usou esse bronze para fazer o tanque, as colunas e objetos para o Templo.)

[[v13-18-9]]

^<<v13-18-9,9>>^ O rei Toí, da cidade de Hamate, soube que Davi tinha derrotado todo o exército de Hadadezer.

[[v13-18-10]]

^<<v13-18-10,10>>^ Então mandou o seu filho Jorão para cumprimentar Davi e para lhe dar os parabéns por ter vencido Hadadezer. Acontece que Toí havia lutado muitas vezes contra Hadadezer. Jorão levou para Davi objetos de prata, de ouro e de bronze.

[[v13-18-11]]

^<<v13-18-11,11>>^ E o rei Davi os separou para serem usados na adoração a Deus, o Senhor , juntamente com a prata e o ouro que tinha tomado dos povos que havia conquistado, isto é, os edomitas, os moabitas, os amonitas, os filisteus e os amalequitas.

[[v13-18-12]]

^<<v13-18-12,12>>^ Abisai, cuja mãe se chamava Zeruia, derrotou os edomitas no vale do Sal e matou dezoito mil deles.

[[v13-18-13]]

^<<v13-18-13,13>>^ Ele colocou acampamentos militares em todo o país de Edom, e o povo dali ficou debaixo do domínio de Davi. O Senhor  fez com que Davi fosse vitorioso em todos os lugares aonde ia.

[[v13-18-14]]

^<<v13-18-14,14>>^ Davi governou todo o Israel e fez com que o seu povo fosse sempre tratado com justiça.

[[v13-18-15]]

^<<v13-18-15,15>>^ Joabe, irmão de Abisai, era o comandante do exército. Josafá, filho de Ailude, era conselheiro do rei.

[[v13-18-16]]

^<<v13-18-16,16>>^ Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes. Seraías era o escrivão.

[[v13-18-17]]

^<<v13-18-17,17>>^ Benaías, filho de Joiada, era o chefe dos queretitas e dos peletitas . E os filhos do rei Davi tinham as mais altas posições no seu serviço.

'''

xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[Próximo Capítulo &#62;]