include::./index.adoc[]

[[v13-23-0]]
=== 1 Crônicas, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-23-1]]

^<<v13-23-1,1>>^ Quando já estava bem velho, Davi pôs o seu filho Salomão como rei de Israel.

[[v13-23-2]]

^<<v13-23-2,2>>^ O rei Davi reuniu todos os líderes israelitas e todos os sacerdotes e levitas .

[[v13-23-3]]

^<<v13-23-3,3>>^ Foram contados os levitas de trinta anos para cima, e o total foi de trinta e oito mil homens.

[[v13-23-4]]

^<<v13-23-4,4>>^ O rei nomeou vinte e quatro mil deles para administrarem o trabalho de construção do Templo. Nomeou também seis mil para fazerem a escrita e resolverem os problemas que surgissem.

[[v13-23-5]]

^<<v13-23-5,5>>^ E ainda nomeou quatro mil para serem guardas dos portões e quatro mil para louvarem o Senhor  com os instrumentos que o próprio rei tinha mandado fazer para isso.

[[v13-23-6]]

^<<v13-23-6,6>>^ Davi dividiu os levitas de acordo com os seus três grupos de famílias, que descendiam de Gérson, Coate e Merari.

[[v13-23-7]]

^<<v13-23-7,7>>^ Gérson foi pai de dois filhos: Ladã e Simei.

[[v13-23-8]]

^<<v13-23-8,8>>^ Ladã foi pai de três filhos: Jeiel, Zetã e Joel,

[[v13-23-9]]

^<<v13-23-9,9>>^ que foram os chefes dos grupos de famílias descendentes de Ladã. (Simei foi pai de três filhos: Selomite, Haziel e Harã.)

[[v13-23-10]]

^<<v13-23-10,10>>^ Simei foi pai de quatro filhos: Jaate, Ziza, Jeús e Berias, pela ordem de idade. Jeús e Berias não tiveram muitos descendentes e por isso foram contados como um só grupo de famílias.

[[v13-23-11]]

^<<v13-23-11,11>>^ Simei foi pai de quatro filhos: Jaate, Ziza, Jeús e Berias, pela ordem de idade. Jeús e Berias não tiveram muitos descendentes e por isso foram contados como um só grupo de famílias.

[[v13-23-12]]

^<<v13-23-12,12>>^ Coate foi pai de quatro filhos: Anrão, Isar, Hebrom e Uziel.

[[v13-23-13]]

^<<v13-23-13,13>>^ Anrão, o filho mais velho, foi o pai de Arão e Moisés. (Arão e os seus descendentes foram separados para sempre a fim de tomar conta dos objetos sagrados, para queimarem incenso na adoração a Deus, o Senhor , para o servirem e para abençoarem o povo em seu nome.

[[v13-23-14]]

^<<v13-23-14,14>>^ Mas os filhos de Moisés, homem de Deus, foram contados entre os levitas.)

[[v13-23-15]]

^<<v13-23-15,15>>^ Moisés foi pai de dois filhos: Gérson e Eliézer.

[[v13-23-16]]

^<<v13-23-16,16>>^ O líder dos filhos de Gérson foi Sebuel.

[[v13-23-17]]

^<<v13-23-17,17>>^ Eliézer foi pai de somente um filho, chamado Reabias, mas Reabias teve muitos descendentes.

[[v13-23-18]]

^<<v13-23-18,18>>^ Isar, o segundo filho de Coate, foi pai de um filho chamado Selomite, que foi o chefe do seu grupo de famílias.

[[v13-23-19]]

^<<v13-23-19,19>>^ Hebrom, o terceiro filho de Coate, foi pai de quatro filhos: Jerias, Amariá, Jaaziel e Jecameão.

[[v13-23-20]]

^<<v13-23-20,20>>^ Uziel, o quarto filho de Coate, foi pai de dois filhos: Mica e Issias.

[[v13-23-21]]

^<<v13-23-21,21>>^ Merari foi pai de dois filhos: Mali e Musi. Mali também foi pai de dois filhos: Eleazar e Quis,

[[v13-23-22]]

^<<v13-23-22,22>>^ mas Eleazar morreu sem deixar nenhum filho homem; só deixou filhas. Estas casaram com os primos, os filhos de Quis.

[[v13-23-23]]

^<<v13-23-23,23>>^ Musi, o segundo filho de Merari, foi pai de três filhos: Mali, Éder e Jerimote.

[[v13-23-24]]

^<<v13-23-24,24>>^ Foram estes os descendentes de Levi, por famílias e por grupos de famílias, registrados nome por nome. Todos os seus descendentes da idade de vinte anos para cima eram responsáveis pelos serviços do Templo de Deus, o Senhor .

[[v13-23-25]]

^<<v13-23-25,25>>^ Davi disse: — O Senhor , o Deus de Israel, tem dado paz ao seu povo e morará em Jerusalém para sempre.

[[v13-23-26]]

^<<v13-23-26,26>>^ Por isso, os levitas não precisam mais carregar a Tenda da Presença de Deus  nem os objetos usados na adoração.

[[v13-23-27]]

^<<v13-23-27,27>>^ Assim, de acordo com as últimas ordens de Davi, quando completavam vinte anos de idade, os levitas eram registrados para o serviço.

[[v13-23-28]]

^<<v13-23-28,28>>^ Então eram escalados para ajudar os sacerdotes descendentes de Arão na adoração no Templo, para cuidar dos seus pátios e salas e para conservar puro  tudo o que era sagrado;

[[v13-23-29]]

^<<v13-23-29,29>>^ para serem responsáveis pelos pães oferecidos a Deus, pela farinha de trigo usada nas ofertas, pelos pães  achatados feitos sem fermento, pelas ofertas assadas em frigideiras e pela farinha de trigo misturada com azeite. Eram também encarregados de pesar e medir as ofertas para o Templo;

[[v13-23-30]]

^<<v13-23-30,30>>^ de louvar e glorificar o Senhor  todas as manhãs e todas as tardes

[[v13-23-31]]

^<<v13-23-31,31>>^ e sempre que as ofertas a Deus eram queimadas no sábado, na Festa da Lua Nova  e em outras festas. Foram feitas regras a respeito do número de levitas escalados de cada vez para fazerem esse trabalho. Eles ficaram encarregados para sempre da adoração ao Senhor .

'''

xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[Próximo Capítulo &#62;]