include::./index.adoc[]

[[v13-22-0]]
=== 1 Crônicas, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-22-1]]

^<<v13-22-1,1>>^ Então Davi disse: — Neste lugar será construído o Templo de Deus, o Senhor . Neste altar o povo de Israel deverá apresentar sacrifícios  que serão completamente queimados.

[[v13-22-2]]

^<<v13-22-2,2>>^ Davi mandou que fossem reunidos todos os estrangeiros que moravam em Israel e os pôs para trabalhar. Alguns deles preparavam blocos de pedra para a construção do Templo.

[[v13-22-3]]

^<<v13-22-3,3>>^ Davi ajuntou uma grande quantidade de ferro para fazer pregos e braçadeiras para os portões de madeira e ajuntou tanto bronze, que não foi possível pesar.

[[v13-22-4]]

^<<v13-22-4,4>>^ E o povo de Tiro e de Sidom lhe mandou uma grande quantidade de toras de cedro.

[[v13-22-5]]

^<<v13-22-5,5>>^ Davi pensou assim: "O templo que o meu filho Salomão vai construir deverá ser esplêndido e famoso no mundo inteiro. Mas ele é jovem e sem experiência; por isso, eu preciso ajuntar o material necessário para a construção." Por isso, Davi, antes de morrer, ajuntou uma grande quantidade de material.

[[v13-22-6]]

^<<v13-22-6,6>>^ Ele mandou chamar o seu filho Salomão e ordenou que ele construísse um templo para o Senhor , o Deus de Israel.

[[v13-22-7]]

^<<v13-22-7,7>>^ Davi disse: — Meu filho, eu quis construir um templo em honra do Senhor , meu Deus.

[[v13-22-8]]

^<<v13-22-8,8>>^ Mas ele disse que eu havia matado muita gente e feito muitas guerras. Portanto, por causa de todo o derramamento de sangue que eu causei, ele não me deixaria construir um templo para ele.

[[v13-22-9]]

^<<v13-22-9,9>>^ Porém Deus me fez uma promessa. Ele disse: "Você terá um filho que governará em paz porque eu farei com que ele viva em paz com todos os seus inimigos. O seu nome será Salomão porque durante o seu reinado eu darei paz e segurança ao povo de Israel.

[[v13-22-10]]

^<<v13-22-10,10>>^ Ele construirá um templo para mim. Ele será meu filho, e eu serei seu pai. Os seus descendentes governarão Israel para sempre."

[[v13-22-11]]

^<<v13-22-11,11>>^ Davi continuou: — Agora, meu filho, que o Senhor , seu Deus, esteja com você para que você consiga construir um templo para ele, conforme ele prometeu que você faria.

[[v13-22-12]]

^<<v13-22-12,12>>^ E que o Senhor , seu Deus, lhe dê inteligência e sabedoria para que você possa governar o povo de Israel de acordo com a Lei  dele!

[[v13-22-13]]

^<<v13-22-13,13>>^ Se você obedecer a todas as leis que o Senhor  deu a Moisés para o povo de Israel, tudo irá bem para você. Seja forte e corajoso; não desanime, nem tenha medo.

[[v13-22-14]]

^<<v13-22-14,14>>^ Quanto ao Templo, com muito esforço eu ajuntei mais de três mil e quatrocentas toneladas de ouro e mais de trinta e quatro mil toneladas de prata para serem usados na construção. Além disso, há uma quantidade tão grande de bronze e ferro, que nem dá para contar. Também armazenei madeira e pedras preparadas, mas você deve arranjar mais.

[[v13-22-15]]

^<<v13-22-15,15>>^ Para o serviço você tem muitos trabalhadores. Há homens para trabalhar nas pedreiras, e há carpinteiros e pedreiros, e também uma grande quantidade de especialistas em todo tipo de trabalho

[[v13-22-16]]

^<<v13-22-16,16>>^ em ouro, prata, bronze e ferro. Portanto, mãos à obra, e que o Senhor  Deus o ajude!

[[v13-22-17]]

^<<v13-22-17,17>>^ Davi ordenou a todos os líderes de Israel que ajudassem Salomão.

[[v13-22-18]]

^<<v13-22-18,18>>^ Ele disse: — O Senhor , nosso Deus, tem estado com vocês e lhes tem dado paz por todos os lados. Ele deixou que eu conquistasse todos os povos que moravam nesta terra, e agora eles são dominados por vocês e por Deus.

[[v13-22-19]]

^<<v13-22-19,19>>^ Portanto, sirvam o Senhor , seu Deus, com todo o coração e alma. Comecem a construir o Templo para que possam colocar nele a arca da aliança  do Senhor  e os outros objetos usados na sua adoração.

'''

xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[&#60; Capítulo Anterior] | <<v13-22-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-023.adoc#v13-23-0[Próximo Capítulo &#62;]