include::./index.adoc[]

[[v13-29-0]]
=== 1 Crônicas, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-29-1]]

^<<v13-29-1,1>>^ Depois o rei Davi disse a todo o povo: — O meu filho Salomão é o único a quem Deus escolheu, mas ele ainda é jovem e sem experiência. O trabalho a ser feito é enorme porque não se trata da construção de um palácio onde vão morar pessoas, mas de um templo para Deus, o Senhor .

[[v13-29-2]]

^<<v13-29-2,2>>^ Para construir o Templo do meu Deus, preparei com todo o esforço o material necessário, isto é, ouro, prata, bronze, ferro, madeira, pedras de ônix, pedras preciosas, pedras de várias cores para os mosaicos e muito mármore.

[[v13-29-3]]

^<<v13-29-3,3>>^ Mas, além de todos os preparativos que fiz para o Templo, dei também prata e ouro que me pertencem, pois amo o Templo do meu Deus.

[[v13-29-4]]

^<<v13-29-4,4>>^ Dei mais de cem toneladas do mais puro ouro e duzentos e quarenta toneladas de prata pura para revestir as paredes do Templo

[[v13-29-5]]

^<<v13-29-5,5>>^ e para todos os objetos que os artesãos vão fazer. Agora, quem está disposto a dar ofertas ao Senhor  Deus por vontade própria?

[[v13-29-6]]

^<<v13-29-6,6>>^ Então os chefes dos grupos de famílias, as autoridades das tribos , os oficiais do exército e os administradores das propriedades do rei deram de livre vontade

[[v13-29-7]]

^<<v13-29-7,7>>^ para a obra do Templo o seguinte: mais de cento e setenta toneladas de ouro, dez mil barras de ouro, trezentas e quarenta toneladas de prata, seiscentas e quinze toneladas de bronze e três mil quatrocentas e vinte toneladas de ferro.

[[v13-29-8]]

^<<v13-29-8,8>>^ Aqueles que tinham pedras preciosas deram essas pedras para o tesouro do Templo, que era administrado por Jeiel, do grupo de famílias levitas  de Gérson.

[[v13-29-9]]

^<<v13-29-9,9>>^ O povo deu de boa vontade ofertas a Deus, o Senhor , e eles ficaram alegres porque havia sido dado tanto. O rei Davi também ficou muito feliz.

[[v13-29-10]]

^<<v13-29-10,10>>^ Então, ali em frente de todo o povo, o rei Davi louvou a Deus, o Senhor . Ele disse: — Ó Senhor , Deus do nosso antepassado Jacó, bendito sejas para sempre!

[[v13-29-11]]

^<<v13-29-11,11>>^ Tu és grande e poderoso, glorioso , esplêndido e majestoso. Tudo o que existe no céu e na terra pertence a ti; tu és o Rei, o supremo governador de tudo.

[[v13-29-12]]

^<<v13-29-12,12>>^ Toda a riqueza e prosperidade vêm de ti; tu governas todas as coisas com o teu poder e a tua força e podes tornar grande e forte qualquer pessoa.

[[v13-29-13]]

^<<v13-29-13,13>>^ Agora, nosso Deus, nós te agradecemos e louvamos o teu nome glorioso.

[[v13-29-14]]

^<<v13-29-14,14>>^ — No entanto, o meu povo e eu não podemos, de fato, te dar nada, pois tudo vem de ti, e nós somente devolvemos o que já era teu.

[[v13-29-15]]

^<<v13-29-15,15>>^ Tu sabes, ó Senhor , que tanto os nossos antepassados como nós passamos pela vida como estrangeiros, como pessoas que estão de passagem. Os nossos dias são como uma sombra que passa, e não podemos escapar da morte.

[[v13-29-16]]

^<<v13-29-16,16>>^ Ó Senhor , nosso Deus, nós trouxemos toda esta riqueza a fim de construir um templo para honrar o teu santo nome, mas tudo isso veio de ti, e tudo é teu.

[[v13-29-17]]

^<<v13-29-17,17>>^ Eu sei que tu pões à prova os corações e amas as pessoas corretas. Com honestidade e sinceridade, eu te dei de livre vontade tudo isso e vejo com alegria que o teu povo, que está reunido aqui, trouxe de boa vontade ofertas a ti.

[[v13-29-18]]

^<<v13-29-18,18>>^ Ó Senhor , Deus dos nossos antepassados Abraão, Isaque e Jacó, conserva para sempre no coração do teu povo esta disposição e este pensamento e guarda-o fiel a ti.

[[v13-29-19]]

^<<v13-29-19,19>>^ Dá ao meu filho Salomão o desejo de obedecer com todo o coração a todos os teus mandamentos e ordens e a vontade de construir o Templo para o qual fiz estes preparativos.

[[v13-29-20]]

^<<v13-29-20,20>>^ Então Davi disse a todo o povo: — Louvem o Senhor , nosso Deus! E todo o povo louvou o Senhor , o Deus dos seus antepassados; todos se ajoelharam e encostaram o rosto no chão, adorando a Deus e prestando homenagem ao rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ No dia seguinte mataram animais em sacrifício , dedicando-os a Deus, o Senhor , e depois os entregaram ao povo para que os comessem. Além disso, mil touros novos, mil carneiros e mil ovelhas foram completamente queimados no altar. Também trouxeram ofertas de vinho.

[[v13-29-22]]

^<<v13-29-22,22>>^ Naquele dia comeram e beberam com muita alegria na presença de Deus. Depois foi anunciado pela segunda vez que Salomão era rei. Em nome do Senhor  eles o ungiram  como o seu rei e ungiram Zadoque como sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ E assim o rei Salomão sentou-se no trono de Deus, o Senhor , em lugar de Davi, o seu pai. Ele enriqueceu, e todo o povo de Israel lhe obedecia.

[[v13-29-24]]

^<<v13-29-24,24>>^ Todos os oficiais e soldados e até os outros filhos de Davi prometeram ser fiéis a Salomão.

[[v13-29-25]]

^<<v13-29-25,25>>^ O Senhor  fez com que todo o povo respeitasse Salomão e o tornou mais glorioso do que qualquer outro rei que havia governado Israel.

[[v13-29-26]]

^<<v13-29-26,26>>^ Davi, filho de Jessé, governou todo o povo de Israel

[[v13-29-27]]

^<<v13-29-27,27>>^ quarenta anos: sete anos em Hebrom e trinta e três em Jerusalém.

[[v13-29-28]]

^<<v13-29-28,28>>^ Ele morreu bem velho, rico e respeitado, e o seu filho Salomão ficou no lugar dele como rei.

[[v13-29-29]]

^<<v13-29-29,29>>^ A história do rei Davi, do começo ao fim, foi escrita pelos profetas  Samuel, Natã e Gade.

[[v13-29-30]]

^<<v13-29-30,30>>^ Essa história fala do seu governo, do seu poder e de todas as coisas que aconteceram com ele, com Israel e com os países vizinhos de Israel.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]