include::./index.adoc[]

[[v13-13-0]]
=== 1 Crônicas, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-13-1]]

^<<v13-13-1,1>>^ O rei Davi consultou todos os oficiais que comandavam grupos de mil homens e grupos de cem.

[[v13-13-2]]

^<<v13-13-2,2>>^ Depois anunciou a todo o povo de Israel o seguinte: — Se vocês acharem bom, e se isso for da vontade do Senhor , nosso Deus, vamos mandar mensageiros ao resto dos nossos irmãos israelitas e aos sacerdotes e levitas  nas suas cidades, para dizerem a eles que venham se reunir aqui com a gente.

[[v13-13-3]]

^<<v13-13-3,3>>^ Aí nós iremos buscar a arca da aliança , pois ela ficou esquecida durante o reinado de Saul.

[[v13-13-4]]

^<<v13-13-4,4>>^ Essa proposta agradou ao povo, e todos concordaram com ela.

[[v13-13-5]]

^<<v13-13-5,5>>^ Então Davi reuniu todo o povo de Israel, desde a fronteira do Egito, no Sul, até a subida de Hamate, no Norte, a fim de levarem a arca da aliança de Quiriate-Jearim para Jerusalém.

[[v13-13-6]]

^<<v13-13-6,6>>^ Davi e o povo foram até a cidade de Baalá, isto é, Quiriate-Jearim, no território da tribo  de Judá, para tirar dali a arca da aliança de Deus, a qual tem o nome do Senhor , que se assenta no seu trono, acima dos querubins .

[[v13-13-7]]

^<<v13-13-7,7>>^ Colocaram a arca num carro de bois, novo, e a levaram embora da casa de Abinadabe. Uzá e Aiô guiavam o carro.

[[v13-13-8]]

^<<v13-13-8,8>>^ Então Davi e todo o povo começaram a dançar com todas as suas forças em louvor a Deus. Eles cantavam e tocavam instrumentos musicais, isto é, harpas , liras , tambores, pratos e trombetas.

[[v13-13-9]]

^<<v13-13-9,9>>^ Quando chegaram ao campo de debulhar cereais que pertencia a Quidom, os bois tropeçaram. Então Uzá estendeu a mão e segurou a arca da aliança.

[[v13-13-10]]

^<<v13-13-10,10>>^ Na mesma hora, o Senhor  ficou irado  por Uzá ter tocado na arca e o matou. Ele morreu ali, na presença de Deus.

[[v13-13-11]]

^<<v13-13-11,11>>^ Davi ficou furioso porque Deus, na sua ira, havia castigado Uzá; assim até hoje  aquele lugar é chamado de Peres-Uzá .

[[v13-13-12]]

^<<v13-13-12,12>>^ Então Davi ficou com medo de Deus e disse: — E agora como poderei levar comigo a arca da aliança?

[[v13-13-13]]

^<<v13-13-13,13>>^ Assim Davi não levou a arca consigo para a Cidade de Davi . Em vez disso, ele a deixou na casa de um homem chamado Obede-Edom, que era da cidade de Gate.

[[v13-13-14]]

^<<v13-13-14,14>>^ A arca ficou ali três meses, e Deus abençoou a família de Obede-Edom e tudo o que era dele.

'''

xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[&#60; Capítulo Anterior] | <<v13-13-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[Próximo Capítulo &#62;]