include::./index.adoc[]

[[v13-12-0]]
=== 1 Crônicas, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-12-1]]

^<<v13-12-1,1>>^ Davi estava morando na cidade de Ziclague, para onde havia ido a fim de fugir do rei Saul. Ali foram juntar-se a ele alguns soldados corajosos e de confiança.

[[v13-12-2]]

^<<v13-12-2,2>>^ Eles eram da tribo  de Benjamim, como Saul era. Atiravam flechas com o arco e pedras com fundas , tanto com a mão direita como com a esquerda.

[[v13-12-3]]

^<<v13-12-3,3>>^ Os comandantes deles eram Aiezer e Joás, filhos de Semaá, da cidade de Gibeá. Os soldados eram estes: Jeziel e Pelete, filhos de Azmavete; Beraca e Jeú, que era da cidade de Anatote; Ismaías, da cidade de Gibeão, soldado famoso e um dos líderes do grupo chamado "Os Trinta"; Jeremias, Jaaziel, Joanã e Jozabade, que era da cidade de Gedera; Eluzai, Jerimote, Bealias, Semarias e Sefatias, que era da cidade de Harife; Elcana, Issias, Azarel, Joezer e Jasobeão, que eram do grupo de famílias de Corá; Joela e Zebadias, filhos de Jeroão, da cidade de Gedor.

[[v13-12-4]]

^<<v13-12-4,4>>^ Os comandantes deles eram Aiezer e Joás, filhos de Semaá, da cidade de Gibeá.

[[v13-12-5]]

^<<v13-12-5,5>>^ Os comandantes deles eram Aiezer e Joás, filhos de Semaá, da cidade de Gibeá.

[[v13-12-6]]

^<<v13-12-6,6>>^ Os comandantes deles eram Aiezer e Joás, filhos de Semaá, da cidade de Gibeá.

[[v13-12-7]]

^<<v13-12-7,7>>^ Os comandantes deles eram Aiezer e Joás, filhos de Semaá, da cidade de Gibeá.

[[v13-12-8]]

^<<v13-12-8,8>>^ São estes os nomes dos soldados corajosos e treinados da tribo  de Gade que foram juntar-se ao exército de Davi quando ele estava na fortaleza do deserto. Eles sabiam lutar com escudo  e lança e eram ferozes como os leões e ligeiros como as gazelas .

[[v13-12-9]]

^<<v13-12-9,9>>^ Os nomes deles foram escritos numa lista na seguinte ordem: Ézer, Obadias, Eliabe, Mismana, Jeremias, Atai, Eliel, Joanã, Elzabade, Jeremias e Macbanai.

[[v13-12-10]]

^<<v13-12-10,10>>^ Os nomes deles foram escritos numa lista na seguinte ordem:

[[v13-12-11]]

^<<v13-12-11,11>>^ Os nomes deles foram escritos numa lista na seguinte ordem:

[[v13-12-12]]

^<<v13-12-12,12>>^ Os nomes deles foram escritos numa lista na seguinte ordem:

[[v13-12-13]]

^<<v13-12-13,13>>^ Os nomes deles foram escritos numa lista na seguinte ordem:

[[v13-12-14]]

^<<v13-12-14,14>>^ Alguns desses homens da tribo de Gade comandavam mil homens, e outros, cem.

[[v13-12-15]]

^<<v13-12-15,15>>^ Certa vez, no primeiro mês do ano, quando o Jordão alaga as suas margens, eles atravessaram o rio e puseram em fuga o povo que morava nos vales, tanto no lado leste como no lado oeste do rio.

[[v13-12-16]]

^<<v13-12-16,16>>^ Também um grupo de homens das tribos  de Benjamim e Judá foi até a fortaleza onde Davi estava.

[[v13-12-17]]

^<<v13-12-17,17>>^ Davi saiu para encontrar-se com eles e disse: — Se vocês vieram como amigos, para me ajudar, aceito de todo o coração que façam parte do meu grupo. Mas, se vieram para me trair e me entregar aos meus inimigos, embora eu não tenha cometido nenhum crime, o Deus dos nossos antepassados ficará sabendo e castigará vocês.

[[v13-12-18]]

^<<v13-12-18,18>>^ Então o Espírito de Deus tomou conta de Amasai, que depois veio a ser o comandante dos "Trinta", e ele gritou: — Davi, filho de Jessé, nós somos seus! Tudo de bom para você e para aqueles que o ajudam! Deus está do seu lado! Então Davi os recebeu e os colocou como oficiais do seu exército.

'''

xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[&#60; Capítulo Anterior] | <<v13-12-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[Próximo Capítulo &#62;]