include::./index.adoc[]

[[v13-19-0]]
=== 1 Crônicas, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-19-1]]

^<<v13-19-1,1>>^ Algum tempo depois, morreu o rei Naás, do país de Amom, e o seu filho Hanum se tornou rei.

[[v13-19-2]]

^<<v13-19-2,2>>^ Davi disse: — Eu serei bondoso com Hanum, assim como Naás, o seu pai, foi bondoso comigo. Então enviou mensageiros a Hanum, para mostrar a sua amizade. Quando os mensageiros chegaram lá e visitaram o rei Hanum,

[[v13-19-3]]

^<<v13-19-3,3>>^ os líderes amonitas disseram a ele: — O senhor pensa que é em honra do seu pai e para mostrar amizade ao senhor que Davi enviou estes homens? É claro que não! Ele os mandou aqui como espiões a fim de ficarem conhecendo a nossa terra, para poderem conquistá-la.

[[v13-19-4]]

^<<v13-19-4,4>>^ Então Hanum pegou os mensageiros de Davi, raspou a barba deles, cortou as suas roupas até a altura das nádegas e os mandou embora.

[[v13-19-5]]

^<<v13-19-5,5>>^ Eles ficaram tão envergonhados, que não tinham coragem de voltar para casa. Quando Davi soube disso, mandou lhes dizer que ficassem na cidade de Jericó e que só voltassem quando as suas barbas tivessem crescido de novo.

[[v13-19-6]]

^<<v13-19-6,6>>^ O rei Hanum e os amonitas compreenderam que tinham feito de Davi um inimigo. Por isso, contrataram na Mesopotâmia e em Maacá e Zoba, na Síria, carros de guerra e soldados de cavalaria. Pagaram para isso mais de trinta e quatro mil quilos de prata.

[[v13-19-7]]

^<<v13-19-7,7>>^ Os trinta e dois mil carros de guerra que eles haviam contratado e o exército do rei de Maacá foram e acamparam perto da cidade de Medeba. Os amonitas também saíram de todas as suas cidades e se aprontaram para a guerra.

[[v13-19-8]]

^<<v13-19-8,8>>^ Quando Davi soube disso, enviou contra eles Joabe e todo o exército israelita.

[[v13-19-9]]

^<<v13-19-9,9>>^ Os amonitas saíram e tomaram posição na entrada de Rabá, a sua capital; e os reis que haviam ido ajudá-los tomaram posição em campo aberto.

[[v13-19-10]]

^<<v13-19-10,10>>^ Joabe viu que as tropas inimigas atacariam pela frente e por trás. Então escolheu os melhores soldados de Israel e os colocou de frente para os sírios.

[[v13-19-11]]

^<<v13-19-11,11>>^ Deixou o resto das suas tropas debaixo do comando do seu irmão Abisai, que as colocou de frente para os amonitas.

[[v13-19-12]]

^<<v13-19-12,12>>^ E Joabe disse a Abisai: — Se você perceber que os sírios estão me vencendo, venha me ajudar; e, se os amonitas estiverem vencendo você, eu irei ajudá-lo.

[[v13-19-13]]

^<<v13-19-13,13>>^ Seja corajoso! Vamos lutar com firmeza pelo nosso povo e pelas cidades do nosso Deus. E que seja feita a vontade de Deus, o Senhor !

[[v13-19-14]]

^<<v13-19-14,14>>^ Então Joabe e os seus soldados avançaram para atacar, e os sírios fugiram.

[[v13-19-15]]

^<<v13-19-15,15>>^ Os amonitas viram os sírios fugindo, e aí eles também fugiram de Abisai, e voltaram para dentro da cidade. Então Joabe voltou para Jerusalém.

[[v13-19-16]]

^<<v13-19-16,16>>^ Quando os sírios viram que tinham sido vencidos pelos israelitas, mandaram buscar tropas que estavam no lado leste do rio Eufrates. Essas tropas eram dirigidas por Sobaque, o comandante do exército do rei Hadadezer, de Zoba.

[[v13-19-17]]

^<<v13-19-17,17>>^ Quando Davi soube disso, reuniu o exército israelita, atravessou o rio Jordão e colocou as tropas de frente para os sírios. A luta começou,

[[v13-19-18]]

^<<v13-19-18,18>>^ e os israelitas fizeram os sírios fugir. Davi e o seu exército mataram sete mil soldados sírios que guiavam carros de guerra e quarenta mil soldados de infantaria. Também mataram Sobaque, o comandante sírio.

[[v13-19-19]]

^<<v13-19-19,19>>^ Quando os reis que eram chefiados por Hadadezer viram que tinham sido vencidos pelos israelitas, fizeram paz com Davi, ficando debaixo do seu poder. E os sírios nunca mais quiseram ajudar os amonitas.

'''

xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[Próximo Capítulo &#62;]