include::./index.adoc[]

[[v13-9-0]]
=== 1 Crônicas, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-9-1]]

^<<v13-9-1,1>>^ Fizeram uma lista de todo o povo de Israel de acordo com as suas famílias, e isso foi escrito no Livro dos Reis de Israel . O povo de Judá havia sido levado prisioneiro para a Babilônia como castigo pelos seus pecados.

[[v13-9-2]]

^<<v13-9-2,2>>^ Os primeiros que voltaram a morar nas suas propriedades e nas suas cidades foram gente do povo, sacerdotes, levitas  e servidores do Templo.

[[v13-9-3]]

^<<v13-9-3,3>>^ Pessoas das tribos  de Judá, Benjamim, Efraim e Manassés foram morar em Jerusalém.

[[v13-9-4]]

^<<v13-9-4,4>>^ Seiscentas e noventa famílias da tribo de Judá moraram em Jerusalém. O líder dos descendentes de Peres, filho de Judá, foi Utai, filho de Amiúde e neto de Onri. Entre os seus antepassados estavam Inri e Bani. O líder dos descendentes de Selá, filho de Judá, foi Asaías, que era o chefe da sua família. O líder dos descendentes de Zera, filho de Judá, foi Jeuel.

[[v13-9-5]]

^<<v13-9-5,5>>^ Seiscentas e noventa famílias da tribo de Judá moraram em Jerusalém.

[[v13-9-6]]

^<<v13-9-6,6>>^ Seiscentas e noventa famílias da tribo de Judá moraram em Jerusalém.

[[v13-9-7]]

^<<v13-9-7,7>>^ Moravam em Jerusalém os seguintes membros da tribo de Benjamim: Salu, filho de Mesulã, neto de Hodavias e bisneto de Hassenuá; Ibneias, filho de Jeroão; Elá, filho de Uzi e neto de Micri; Mesulã, filho de Sefatias, neto de Reuel e bisneto de Ibnijas.

[[v13-9-8]]

^<<v13-9-8,8>>^ Moravam em Jerusalém os seguintes membros da tribo de Benjamim:

[[v13-9-9]]

^<<v13-9-9,9>>^ Novecentas e cinquenta e seis famílias da tribo de Benjamim moravam em Jerusalém. Todos os homens cujos nomes estão escritos acima eram chefes de famílias.

[[v13-9-10]]

^<<v13-9-10,10>>^ Moravam em Jerusalém os seguintes sacerdotes: Jedaías, Jeoiaribe e Jaquim. Ali morava também Azarias, que era o administrador do Templo; ele era filho de Hilquias, neto de Mesulã, bisneto de Zadoque, trineto de Meraiote e tetraneto de Aitube. Adaías, filho de Jeroão, neto de Pasur e bisneto de Malquias. Masai, filho de Adiel, neto de Jazera, bisneto de Mesulã, trineto de Mesilemite e tetraneto de Imer.

[[v13-9-11]]

^<<v13-9-11,11>>^ Moravam em Jerusalém os seguintes sacerdotes:

[[v13-9-12]]

^<<v13-9-12,12>>^ Moravam em Jerusalém os seguintes sacerdotes:

[[v13-9-13]]

^<<v13-9-13,13>>^ Havia mil setecentos e sessenta sacerdotes que eram chefes de famílias. Eles estavam preparados para fazer todos os trabalhos do Templo.

[[v13-9-14]]

^<<v13-9-14,14>>^ Moravam em Jerusalém os seguintes levitas : Semaías, filho de Hassube, neto de Azricã e bisneto de Hasabias. Ele era do grupo de famílias de Merari. Baquebacar, Heres e Galal. Matanias, filho de Mica, neto de Zicri e bisneto de Asafe. Obadias, filho de Semaías, neto de Galal e bisneto de Jedutum. Berequias, filho de Asa e neto de Elcana, que morava nas terras que pertenciam à cidade de Netofa.

[[v13-9-15]]

^<<v13-9-15,15>>^ Moravam em Jerusalém os seguintes levitas :

[[v13-9-16]]

^<<v13-9-16,16>>^ Moravam em Jerusalém os seguintes levitas :

[[v13-9-17]]

^<<v13-9-17,17>>^ Moravam em Jerusalém os seguintes guardas do Templo: Salum, Acube, Talmom e Aimã. Salum era o chefe deles.

[[v13-9-18]]

^<<v13-9-18,18>>^ Desde aquele tempo até hoje , membros dos seus grupos de famílias têm sido guardas do Portão do Rei , que ficava no lado leste do Templo. Antigamente eles eram os guardas dos portões dos acampamentos dos levitas .

[[v13-9-19]]

^<<v13-9-19,19>>^ Salum, filho de Coré e neto de Ebiasafe, e também os seus parentes do grupo de famílias de Corá eram os encarregados de guardar a entrada da Tenda da Presença de Deus , como os seus antepassados haviam sido quando eram os encarregados do acampamento de Deus, o Senhor .

[[v13-9-20]]

^<<v13-9-20,20>>^ Naquela época, Fineias, filho de Eleazar — que o Senhor  esteja com Fineias! — era o chefe deles.

[[v13-9-21]]

^<<v13-9-21,21>>^ Zacarias, filho de Meselemias, também era guarda da entrada da Tenda da Presença de Deus.

[[v13-9-22]]

^<<v13-9-22,22>>^ Ao todo, duzentos e doze homens foram escolhidos para serem guardas dos portões. Os nomes deles foram escritos numa lista, de acordo com os povoados onde moravam. O rei Davi e o profeta  Samuel é que haviam colocado os antepassados deles nesses cargos de confiança.

[[v13-9-23]]

^<<v13-9-23,23>>^ Eles e os seus descendentes guardavam os portões da área do Templo.

[[v13-9-24]]

^<<v13-9-24,24>>^ Havia um portão de frente para cada uma das direções: norte, sul, leste e oeste, e cada portão tinha um guarda-chefe.

[[v13-9-25]]

^<<v13-9-25,25>>^ Esses guardas eram ajudados pelos seus parentes que moravam nos povoados e que se revezavam no trabalho de sete em sete dias.

[[v13-9-26]]

^<<v13-9-26,26>>^ Os quatro guardas-chefes eram levitas e eram responsáveis por esse trabalho e também vigiavam os cômodos do Templo e as coisas guardadas ali.

[[v13-9-27]]

^<<v13-9-27,27>>^ Eles moravam perto do Templo porque era seu dever guardá-lo e abrir os portões todas as manhãs.

[[v13-9-28]]

^<<v13-9-28,28>>^ Os outros levitas  eram responsáveis pelos objetos usados no culto. Todas as vezes que esses objetos eram usados, eles os contavam quando eram levados e quando eram devolvidos.

[[v13-9-29]]

^<<v13-9-29,29>>^ Também havia levitas encarregados dos outros objetos sagrados e da farinha de trigo, do vinho, do azeite, do incenso e das especiarias .

[[v13-9-30]]

^<<v13-9-30,30>>^ Mas os sacerdotes é que tinham a responsabilidade de misturar as especiarias.

[[v13-9-31]]

^<<v13-9-31,31>>^ Um levita chamado Matitias, que era o filho mais velho de Salum, do grupo de famílias de Corá, era o encarregado de preparar as ofertas de pães .

[[v13-9-32]]

^<<v13-9-32,32>>^ Membros do grupo de famílias de Coate estavam encarregados de fazer todos os sábados os pães sagrados para o Templo.

[[v13-9-33]]

^<<v13-9-33,33>>^ Algumas famílias de levitas eram responsáveis pela música no Templo. Os chefes dessas famílias moravam nos cômodos do Templo e não tinham outros deveres, pois estavam ocupados no seu serviço de dia e de noite.

[[v13-9-34]]

^<<v13-9-34,34>>^ Foram estes os chefes de famílias de levitas, de acordo com a lista dos nomes dos seus antepassados. Eles eram os líderes que moravam em Jerusalém.

[[v13-9-35]]

^<<v13-9-35,35>>^ Jeiel fundou a cidade de Gibeão e ficou morando ali. A sua mulher se chamava Maacá.

[[v13-9-36]]

^<<v13-9-36,36>>^ O seu filho mais velho se chamava Abdom, e os outros eram Zur, Quis, Baal, Ner, Nadabe,

[[v13-9-37]]

^<<v13-9-37,37>>^ Gedor, Aiô, Zacarias e Miclote.

'''

xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[&#60; Capítulo Anterior] | <<v13-9-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[Próximo Capítulo &#62;]