include::./index.adoc[]

[[v13-26-0]]
=== 1 Crônicas, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-26-1]]

^<<v13-26-1,1>>^ Segue a lista dos levitas  que foram escalados para trabalhar como guardas do Templo: Meselemias, filho de Coré, da família de Asafe e do grupo de famílias de Corá.

[[v13-26-2]]

^<<v13-26-2,2>>^ Ele foi pai de sete filhos, que foram os seguintes, por ordem de idade: Zacarias, Jediael, Zebadias, Jatniel,

[[v13-26-3]]

^<<v13-26-3,3>>^ Elão, Joanã e Elioenai.

[[v13-26-4]]

^<<v13-26-4,4>>^ Obede-Edom, a quem Deus abençoou dando oito filhos. Eles foram os seguintes, por ordem de idade: Semaías, Jeozabade, Joá, Sacar, Netanel, Amiel, Issacar e Peuletai.

[[v13-26-5]]

^<<v13-26-5,5>>^ Obede-Edom, a quem Deus abençoou dando oito filhos. Eles foram os seguintes, por ordem de idade: Semaías, Jeozabade, Joá, Sacar, Netanel, Amiel, Issacar e Peuletai.

[[v13-26-6]]

^<<v13-26-6,6>>^ Semaías, o filho mais velho de Obede-Edom, foi pai de seis filhos: Otni, Rafael, Obede, Elzabade, Eliú e Semaquias. Por serem valentes, todos eles eram importantes no seu grupo de famílias; e os dois últimos eram ainda mais valentes do que os outros.

[[v13-26-7]]

^<<v13-26-7,7>>^ Semaías, o filho mais velho de Obede-Edom, foi pai de seis filhos: Otni, Rafael, Obede, Elzabade, Eliú e Semaquias. Por serem valentes, todos eles eram importantes no seu grupo de famílias; e os dois últimos eram ainda mais valentes do que os outros.

[[v13-26-8]]

^<<v13-26-8,8>>^ A família de Obede-Edom forneceu sessenta e dois homens valentes e fortes para trabalharem como guardas do Templo.

[[v13-26-9]]

^<<v13-26-9,9>>^ A família de Meselemias forneceu dezoito homens valentes.

[[v13-26-10]]

^<<v13-26-10,10>>^ Do grupo de famílias de Merari havia Hosa, que foi pai de quatro filhos: Sinri, que foi posto pelo seu pai como chefe, embora não fosse o filho mais velho;

[[v13-26-11]]

^<<v13-26-11,11>>^ Hilquias, Tebalias e Zacarias. Ao todo, treze membros da família de Hosa eram guardas do Templo.

[[v13-26-12]]

^<<v13-26-12,12>>^ Os guardas do Templo foram divididos em grupos, de acordo com as suas famílias, e receberam tarefas no serviço do Templo, como os outros levitas.

[[v13-26-13]]

^<<v13-26-13,13>>^ Fizeram um sorteio  entre as famílias, tanto grandes como pequenas, e assim cada uma foi escalada para tomar conta de um portão.

[[v13-26-14]]

^<<v13-26-14,14>>^ Selemias recebeu por sorteio o portão leste, e o seu filho Zacarias, que sempre dava bons conselhos, recebeu o portão norte.

[[v13-26-15]]

^<<v13-26-15,15>>^ Obede-Edom foi sorteado para o portão sul, e os seus filhos foram sorteados para tomar conta dos depósitos.

[[v13-26-16]]

^<<v13-26-16,16>>^ Supim e Hosa receberam por sorteio o portão oeste e o portão de Salequete, na estrada de cima. O serviço dos guardas foi dividido do seguinte modo:

[[v13-26-17]]

^<<v13-26-17,17>>^ cada dia havia seis guardas no leste, quatro no norte e quatro no sul. Quatro guardas ficavam nos depósitos: dois em cada um.

[[v13-26-18]]

^<<v13-26-18,18>>^ No pátio oeste ficavam quatro guardas perto da estrada, e dois no pátio propriamente dito.

[[v13-26-19]]

^<<v13-26-19,19>>^ Assim ficaram repartidas as tarefas dos guardas que pertenciam ao grupo de famílias de Corá e de Merari.

[[v13-26-20]]

^<<v13-26-20,20>>^ Outros dos seus irmãos levitas estavam encarregados do tesouro do Templo e dos depósitos onde ficavam guardados os presentes oferecidos a Deus.

[[v13-26-21]]

^<<v13-26-21,21>>^ Ladã, um dos filhos de Gérson, foi o antepassado de muitos grupos de famílias, entre eles a família do seu filho Jeieli.

[[v13-26-22]]

^<<v13-26-22,22>>^ Zetã e Joel, os outros dois filhos de Ladã, estavam encarregados do tesouro e dos depósitos do Templo.

[[v13-26-23]]

^<<v13-26-23,23>>^ Os descendentes de Anrão, Isar, Hebrom e Uziel também receberam tarefas.

[[v13-26-24]]

^<<v13-26-24,24>>^ Sebuel, do grupo de famílias de Gérson, filho de Moisés, era o oficial encarregado do tesouro do Templo.

[[v13-26-25]]

^<<v13-26-25,25>>^ Ele era aparentado com Selomite através de Eliézer, irmão de Gérson. Eliézer foi pai de Reabias, Reabias foi pai de Jesaías, Jesaías foi pai de Jorão, Jorão foi pai de Zicri, e Zicri foi pai de Selomite.

[[v13-26-26]]

^<<v13-26-26,26>>^ Selomite e os membros da sua família estavam encarregados de todos os presentes oferecidos a Deus pelo rei Davi, pelos chefes de famílias, pelos líderes de grupos de famílias e pelos oficiais do exército.

[[v13-26-27]]

^<<v13-26-27,27>>^ Esses presentes eram coisas tomadas dos inimigos na guerra e separadas para serem usadas no Templo.

[[v13-26-28]]

^<<v13-26-28,28>>^ Selomite e a sua família estavam encarregados de tudo aquilo que havia sido dedicado para ser usado no Templo. No meio dessas coisas estavam os presentes dados pelo profeta  Samuel, pelo rei Saul, por Abner, filho de Ner, e por Joabe, cuja mãe se chamava Zeruia.

[[v13-26-29]]

^<<v13-26-29,29>>^ Quenanias e os seus filhos, que eram descendentes de Isar, estavam encarregados de escrever o que acontecia e de resolver as questões que surgiam no meio do povo de Israel.

[[v13-26-30]]

^<<v13-26-30,30>>^ Hasabias e mil e setecentos dos seus parentes, todos eles homens de valor, eram descendentes de Hebrom. Eles foram encarregados de cuidar de todos os assuntos, tanto os religiosos como os da vida comum em Israel, no lado oeste do rio Jordão.

'''

xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[Próximo Capítulo &#62;]