include::./index.adoc[]

[[v13-10-0]]
=== 1 Crônicas, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-10-1]]

^<<v13-10-1,1>>^ Os filisteus lutaram contra os israelitas no monte Gilboa. Muitos israelitas foram mortos ali, e o resto fugiu. Entre os que fugiram estavam o rei Saul e os seus filhos.

[[v13-10-2]]

^<<v13-10-2,2>>^ Mas os filisteus os cercaram e mataram Jônatas, Abinadabe e Malquisua, filhos de Saul.

[[v13-10-3]]

^<<v13-10-3,3>>^ A luta estava feroz em volta de Saul, que foi atingido por flechas inimigas e ficou muito ferido.

[[v13-10-4]]

^<<v13-10-4,4>>^ Então disse ao rapaz que carregava as suas armas: — Tire a sua espada e me mate para que esses filisteus pagãos não caçoem de mim. Mas o rapaz estava muito apavorado e não quis fazer isso. Então Saul pegou a sua própria espada e se jogou sobre ela.

[[v13-10-5]]

^<<v13-10-5,5>>^ Quando viu que Saul estava morto, o rapaz também se jogou sobre a sua própria espada e morreu junto com ele.

[[v13-10-6]]

^<<v13-10-6,6>>^ E assim Saul e os seus três filhos morreram juntos, e nenhum dos seus descendentes se tornou rei.

[[v13-10-7]]

^<<v13-10-7,7>>^ Quando os israelitas que moravam no vale de Jezreel souberam que o exército de Israel havia fugido e que Saul e os seus filhos tinham sido mortos, abandonaram as suas cidades e fugiram. Então os filisteus foram e ocuparam aquelas cidades.

[[v13-10-8]]

^<<v13-10-8,8>>^ Um dia depois da batalha, quando os filisteus voltaram lá para tirar dos mortos as coisas de valor, acharam os corpos de Saul e dos seus filhos caídos no monte Gilboa.

[[v13-10-9]]

^<<v13-10-9,9>>^ Então cortaram a cabeça de Saul e pegaram as armas dele. Depois mandaram mensageiros com elas para o território filisteu a fim de darem as boas notícias aos seus ídolos e ao povo.

[[v13-10-10]]

^<<v13-10-10,10>>^ Eles puseram as armas dele num dos seus templos e penduraram a sua cabeça no templo de Dagom, o deus deles.

[[v13-10-11]]

^<<v13-10-11,11>>^ Quando o povo da cidade de Jabes, em Gileade, soube do que os filisteus haviam feito com Saul,

[[v13-10-12]]

^<<v13-10-12,12>>^ os seus moradores mais corajosos foram, pegaram os corpos de Saul e dos seus filhos e os levaram para Jabes. Eles os sepultaram debaixo de um carvalho e jejuaram sete dias.

[[v13-10-13]]

^<<v13-10-13,13>>^ Saul morreu assim porque foi infiel a Deus, o Senhor . Ele desobedeceu aos mandamentos de Deus e consultou os espíritos dos mortos,

[[v13-10-14]]

^<<v13-10-14,14>>^ em vez de consultar o Senhor . Por isso, Deus o matou e entregou o reino a Davi, filho de Jessé.

'''

xref:013-1-cronicas/013-1-cronicas-009.adoc#v13-9-0[&#60; Capítulo Anterior] | <<v13-10-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[Próximo Capítulo &#62;]