include::./index.adoc[]

[[v13-16-0]]
=== 1 Crônicas, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-16-1]]

^<<v13-16-1,1>>^ Levaram a arca da aliança  para a barraca que Davi tinha preparado para ela e a colocaram lá dentro. Então ofereceram a Deus sacrifícios  que foram completamente queimados e ofertas de paz.

[[v13-16-2]]

^<<v13-16-2,2>>^ Depois que Davi acabou de oferecer os sacrifícios, abençoou o povo em nome do Senhor

[[v13-16-3]]

^<<v13-16-3,3>>^ e distribuiu comida a todos. Deu a cada homem e a cada mulher de Israel um pão, um pedaço de carne assada e passas.

[[v13-16-4]]

^<<v13-16-4,4>>^ Davi nomeou alguns levitas  para dirigirem a adoração ao Senhor , o Deus de Israel, cantando e louvando a Deus, em frente da arca da aliança.

[[v13-16-5]]

^<<v13-16-5,5>>^ Asafe foi nomeado o chefe deles, e Zacarias, o seu ajudante. Para tocarem lira , foram nomeados: Jeiel, Semiramote, Jeiel, Matitias, Eliabe, Benaías, Obede-Edom e Jeiel. Para tocar pratos, foi nomeado Asafe,

[[v13-16-6]]

^<<v13-16-6,6>>^ e, para tocarem trombeta todos os dias em frente da arca da aliança, foram nomeados os sacerdotes Benaías e Jaaziel.

[[v13-16-7]]

^<<v13-16-7,7>>^ Foi nesse dia que Davi deu pela primeira vez a Asafe e aos seus colegas levitas a responsabilidade de cantarem louvores a Deus, o Senhor .

[[v13-16-8]]

^<<v13-16-8,8>>^ Agradeçam a Deus, o Senhor , anunciem a sua grandeza e contem às nações as coisas que ele fez.

[[v13-16-9]]

^<<v13-16-9,9>>^ Cantem a Deus, cantem louvores a ele, falem dos seus atos maravilhosos.

[[v13-16-10]]

^<<v13-16-10,10>>^ Tenham orgulho daquilo que o Santo Deus tem feito. Que fique alegre o coração de todos os que adoram ao Senhor !

[[v13-16-11]]

^<<v13-16-11,11>>^ Procurem a ajuda do Senhor ; estejam sempre na sua presença.

[[v13-16-12]]

^<<v13-16-12,12>>^ Vocês, descendentes de Israel, servo  de Deus, vocês, descendentes de Jacó, o escolhido de Deus, lembrem de tudo o que Deus tem feito, lembrem dos seus grandes e maravilhosos milagres e de como tem condenado os nossos inimigos!

[[v13-16-13]]

^<<v13-16-13,13>>^ Vocês, descendentes de Israel, servo  de Deus,

[[v13-16-14]]

^<<v13-16-14,14>>^ Ele é o Senhor , nosso Deus; os seus mandamentos são para o mundo inteiro.

[[v13-16-15]]

^<<v13-16-15,15>>^ Ele sempre lembrará da sua aliança e, por milhares de gerações , cumprirá as suas promessas.

[[v13-16-16]]

^<<v13-16-16,16>>^ Ele será fiel à aliança feita com Abraão e à promessa que fez com juramento a Isaque.

[[v13-16-17]]

^<<v13-16-17,17>>^ Deus fez uma aliança com Jacó para sempre, fez com ele uma aliança eterna.

[[v13-16-18]]

^<<v13-16-18,18>>^ Naquela ocasião Deus disse: "Eu lhe darei a terra de Canaã, e ela será de vocês para sempre."

[[v13-16-19]]

^<<v13-16-19,19>>^ Eles eram muito poucos, eram estrangeiros na Terra Prometida .

[[v13-16-20]]

^<<v13-16-20,20>>^ Andavam de país em país, de reino em reino.

[[v13-16-21]]

^<<v13-16-21,21>>^ Mas Deus não deixou que ninguém os maltratasse e, para protegê-los, avisou reis.

[[v13-16-22]]

^<<v13-16-22,22>>^ Ele disse: "Não toquem nos servos que eu escolhi; não maltratem os meus profetas !"

[[v13-16-23]]

^<<v13-16-23,23>>^ Cantem ao Senhor , todos os povos da terra. Anunciem todos os dias que ele nos salvou.

[[v13-16-24]]

^<<v13-16-24,24>>^ Falem da sua glória  às nações; contem a todos os povos as coisas maravilhosas que ele tem feito.

[[v13-16-25]]

^<<v13-16-25,25>>^ O Senhor  é grande e merece todo o nosso louvor; ele deve ser temido  mais do que todos os deuses.

[[v13-16-26]]

^<<v13-16-26,26>>^ Pois os deuses das outras nações são somente ídolos, mas o Senhor  fez os céus.

[[v13-16-27]]

^<<v13-16-27,27>>^ Ele está cercado de glória e majestade; poder e beleza enchem o seu Templo.

[[v13-16-28]]

^<<v13-16-28,28>>^ Louvem o Senhor , todos os povos da terra! Louvem a sua glória e o seu poder.

[[v13-16-29]]

^<<v13-16-29,29>>^ Deem ao Senhor  a honra que ele merece; tragam uma oferta e entrem nos pátios do seu Templo. Curvem-se diante do Santo Deus quando ele aparecer;

[[v13-16-30]]

^<<v13-16-30,30>>^ trema diante dele, toda a terra. A terra está firme no seu lugar e não pode ser abalada.

[[v13-16-31]]

^<<v13-16-31,31>>^ Alegre-se a terra, e fique contente o céu. Digam em todas as nações: "O Senhor  é Rei!"

[[v13-16-32]]

^<<v13-16-32,32>>^ Ruja o mar e todas as criaturas que nele vivem. Alegrem-se os campos e tudo o que há neles.

[[v13-16-33]]

^<<v13-16-33,33>>^ Então as árvores dos bosques gritarão de alegria diante de Deus, o Senhor , pois ele vem governar a terra.

[[v13-16-34]]

^<<v13-16-34,34>>^ Deem graças ao Senhor  porque ele é bom, e o seu amor dura para sempre.

[[v13-16-35]]

^<<v13-16-35,35>>^ Digam a ele: "Liberta-nos, ó Senhor , nosso Salvador! Ajunta-nos e tira-nos do meio dos pagãos. Assim nós te daremos graças e com prazer te louvaremos, ó Santo Deus."

[[v13-16-36]]

^<<v13-16-36,36>>^ Louvemos o Senhor , o Deus de Israel. Louvem o Senhor  agora e sempre. Então todo o povo disse " amém !" e louvou a Deus, o Senhor .

[[v13-16-37]]

^<<v13-16-37,37>>^ O rei Davi pôs Asafe e os seus colegas levitas  como encarregados permanentes da adoração que era feita no lugar onde a arca da aliança  havia sido colocada. Eles deviam cumprir ali os seus deveres todos os dias.

[[v13-16-38]]

^<<v13-16-38,38>>^ Obede-Edom, filho de Jedutum, e sessenta e oito homens do seu grupo de famílias deviam ser os seus ajudantes. Hosa e Obede-Edom eram os guardas dos portões.

[[v13-16-39]]

^<<v13-16-39,39>>^ Porém o sacerdote Zadoque e os seus colegas estavam encarregados do culto ao Senhor  Deus na Tenda Sagrada , que estava no lugar de adoração em Gibeão.

[[v13-16-40]]

^<<v13-16-40,40>>^ Todas as manhãs e todas as tardes eles deviam oferecer no altar sacrifícios  que seriam completamente queimados, de acordo com o que está escrito na Lei  que o Senhor  deu ao povo de Israel.

[[v13-16-41]]

^<<v13-16-41,41>>^ Estavam ali com eles Hemã e Jedutum e os outros que haviam sido nomeados a fim de cantar louvores ao Senhor  por causa do seu amor que dura para sempre.

[[v13-16-42]]

^<<v13-16-42,42>>^ Hemã e Jedutum também estavam encarregados das trombetas, dos pratos e dos outros instrumentos que eram tocados para acompanhar os hinos de louvor. Os membros do grupo de famílias de Jedutum estavam encarregados de guardar os portões.

'''

xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[&#60; Capítulo Anterior] | <<v13-16-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[Próximo Capítulo &#62;]