include::./index.adoc[]

[[v13-5-0]]
=== 1 Crônicas, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-5-1]]

^<<v13-5-1,1>>^ São estes os descendentes de Rúben, o filho mais velho de Jacó. (Por ter tido relações com uma concubina  do seu pai, Rúben havia perdido os direitos que eram dele como filho mais velho. Esses direitos foram dados a José.

[[v13-5-2]]

^<<v13-5-2,2>>^ Foi a tribo  de Judá que, de fato, se tornou a mais forte, e dela saiu um governador para todas as tribos.)

[[v13-5-3]]

^<<v13-5-3,3>>^ Rúben, o filho mais velho de Jacó, foi pai de quatro filhos: Enoque, Palu, Hezrom e Carmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ Joel foi pai de Semaías, Semaías foi pai de Gogue, Gogue foi pai de Simei,

[[v13-5-5]]

^<<v13-5-5,5>>^ Simei foi pai de Mica, Mica foi pai de Reaías, Reaías foi pai de Baal,

[[v13-5-6]]

^<<v13-5-6,6>>^ Baal foi pai de Beera. Beera, o chefe da tribo, foi levado como prisioneiro por Tiglate-Pileser, rei da Assíria.

[[v13-5-7]]

^<<v13-5-7,7>>^ Foram escritos numa lista os nomes dos seguintes chefes de grupos de famílias da tribo de Rúben: Jeiel, Zacarias,

[[v13-5-8]]

^<<v13-5-8,8>>^ Belá, filho de Azaz e neto de Sema, do grupo de famílias de Joel. Esse grupo de famílias morava em Aroer e na região que ia para o Norte até Nebo e Baal-Meom.

[[v13-5-9]]

^<<v13-5-9,9>>^ Eles tinham grandes rebanhos na região de Gileade e por isso ocuparam a terra na direção leste até o deserto que termina no rio Eufrates.

[[v13-5-10]]

^<<v13-5-10,10>>^ No tempo do rei Saul, a tribo de Rúben atacou e matou os hagaritas e ocupou a terra deles na parte leste de Gileade.

[[v13-5-11]]

^<<v13-5-11,11>>^ A tribo  de Gade morou ao norte das terras da tribo de Rúben, na região de Basã, até Salca, no leste.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel foi o fundador do principal grupo de famílias, e Safã foi o fundador do segundo mais importante grupo de famílias. Janai e Safate foram fundadores de outros grupos de famílias em Basã.

[[v13-5-13]]

^<<v13-5-13,13>>^ Os outros membros da tribo pertenciam aos seguintes sete grupos de famílias: Micael, Mesulã, Seba, Jorai, Jacã, Zia e Héber.

[[v13-5-14]]

^<<v13-5-14,14>>^ Eles eram descendentes de Abiail, filho de Huri, filho de Jaroa, filho de Gileade, filho de Micael, filho de Jesisai, filho de Jado, filho de Buz.

[[v13-5-15]]

^<<v13-5-15,15>>^ Aí, filho de Abdiel e neto de Guni, era o chefe desses grupos de famílias.

[[v13-5-16]]

^<<v13-5-16,16>>^ Eles moravam nas regiões de Basã e de Gileade, nas cidades dali e por todas as terras de pastagens de Sarom.

[[v13-5-17]]

^<<v13-5-17,17>>^ (Estes registros foram feitos no tempo do rei Jotão, de Judá, e do rei Jeroboão, de Israel.)

[[v13-5-18]]

^<<v13-5-18,18>>^ Nas tribos  de Rúben, de Gade e de Manassés do Leste havia quarenta e quatro mil setecentos e sessenta soldados bem-treinados no uso de escudos , espadas e arco e flechas.

[[v13-5-19]]

^<<v13-5-19,19>>^ Eles fizeram guerra contra as tribos hagaritas de Jetur, Nafis e Nodabe.

[[v13-5-20]]

^<<v13-5-20,20>>^ Pediram a ajuda de Deus e confiaram nele, e por isso ele respondeu às suas orações e lhes deu a vitória sobre os hagaritas e os seus aliados.

[[v13-5-21]]

^<<v13-5-21,21>>^ Eles tomaram dos inimigos cinquenta mil camelos, duzentas e cinquenta mil ovelhas e dois mil jumentos e levaram cem mil prisioneiros de guerra.

[[v13-5-22]]

^<<v13-5-22,22>>^ Mataram muitos inimigos porque a guerra era da vontade de Deus. E ficaram morando naquela região até a época em que o povo foi levado como prisioneiro para fora da sua terra .

[[v13-5-23]]

^<<v13-5-23,23>>^ O povo de Manassés do Leste ficou morando na região de Basã até as cidades de Baal-Hermom e Senir e o monte Hermom, no norte. Eles aumentaram muito em número.

[[v13-5-24]]

^<<v13-5-24,24>>^ Estes foram os chefes dos seus grupos de famílias: Éfer, Isi, Eliel, Azriel, Jeremias, Hodavias e Jadiel. Todos eram soldados valentes e chefes famosos dos seus grupos de famílias.

[[v13-5-25]]

^<<v13-5-25,25>>^ Mas o povo não foi fiel ao Deus dos seus antepassados e o abandonou para adorar os deuses das nações que Deus havia expulsado da terra.

[[v13-5-26]]

^<<v13-5-26,26>>^ Por isso, Deus fez com que Pul, rei da Assíria, que também era conhecido como Tiglate-Pileser, invadisse a terra deles. Ele levou embora as tribos  de Rúben, de Gade e de Manassés do Leste e as fez morar nas cidades de Hala, Habor e Hara e na beira do rio Gozã, onde estão até hoje .

'''

xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[Próximo Capítulo &#62;]