include::./index.adoc[]

[[v13-20-0]]
=== 1 Crônicas, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-20-1]]

^<<v13-20-1,1>>^ Na primavera seguinte, na época do ano em que os reis costumam sair para a guerra, Joabe saiu com o seu exército e invadiu o país de Amom. Porém o rei Davi ficou em Jerusalém. O exército israelita cercou, atacou e destruiu a cidade de Rabá.

[[v13-20-2]]

^<<v13-20-2,2>>^ Moloque , o ídolo dos amonitas, tinha uma coroa que pesava mais ou menos trinta e quatro quilos. A coroa era de ouro, e nela havia uma pedra preciosa, que Davi tirou e colocou na sua própria coroa. Davi levou também de Rabá muitas coisas de valor.

[[v13-20-3]]

^<<v13-20-3,3>>^ Ele fez o povo sair da cidade e o obrigou a trabalhar com serras, enxadas e machados. Fez o mesmo em todas as outras cidades de Amom. Então Davi e os seus soldados voltaram para Jerusalém.

[[v13-20-4]]

^<<v13-20-4,4>>^ Algum tempo depois, houve guerra contra os filisteus em Gezer. Isso aconteceu quando Sibecai, da cidade de Husa, matou um gigante chamado Sipai, e os filisteus foram derrotados.

[[v13-20-5]]

^<<v13-20-5,5>>^ Houve outra batalha contra os filisteus, e Elanã, filho de Jair, matou Lami, irmão de Golias, da cidade de Gate. A lança de Lami era enorme, muito grossa e pesada.

[[v13-20-6]]

^<<v13-20-6,6>>^ E houve ainda outra batalha em Gate. Ali havia um descendente dos antigos gigantes que tinha seis dedos em cada mão e em cada pé.

[[v13-20-7]]

^<<v13-20-7,7>>^ Esse gigante desafiou os israelitas, e Jônatas, filho de Simeia, irmão de Davi, o matou.

[[v13-20-8]]

^<<v13-20-8,8>>^ Esses três, que foram mortos por Davi e os seus soldados, eram descendentes dos gigantes da cidade de Gate.

'''

xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[&#60; Capítulo Anterior] | <<v13-20-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[Próximo Capítulo &#62;]