include::./index.adoc[]

[[v13-4-0]]
=== 1 Crônicas, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-4-1]]

^<<v13-4-1,1>>^ São estes os descendentes de Judá: Peres, Hezrom, Carmi, Hur e Sobal.

[[v13-4-2]]

^<<v13-4-2,2>>^ Sobal foi pai de Reaías, Reaías foi pai de Jaate, Jaate foi pai de Aumai e Laade. Aumai e Laade foram os antepassados dos grupos de famílias que moravam em Zora.

[[v13-4-3]]

^<<v13-4-3,3>>^ Hur foi o filho mais velho de Calebe e da sua mulher Efrata, e os seus descendentes fundaram a cidade de Belém. Hur foi pai de três filhos: Etã, Penuel e Ézer. Etã foi pai de três filhos: Jezreel, Isma e Idbas e de uma filha chamada Hazelelponi. Penuel fundou a cidade de Gedor, e Ézer fundou Husa.

[[v13-4-4]]

^<<v13-4-4,4>>^ Hur foi o filho mais velho de Calebe e da sua mulher Efrata, e os seus descendentes fundaram a cidade de Belém. Hur foi pai de três filhos: Etã, Penuel e Ézer. Etã foi pai de três filhos: Jezreel, Isma e Idbas e de uma filha chamada Hazelelponi. Penuel fundou a cidade de Gedor, e Ézer fundou Husa.

[[v13-4-5]]

^<<v13-4-5,5>>^ Asur, que fundou a cidade de Tecoa, teve duas esposas: Helá e Naara.

[[v13-4-6]]

^<<v13-4-6,6>>^ Ele e Naara tiveram quatro filhos: Auzã, Héfer, Temeni e Haastari.

[[v13-4-7]]

^<<v13-4-7,7>>^ Asur e Helá tiveram três filhos: Zerete, Isar e Etnã.

[[v13-4-8]]

^<<v13-4-8,8>>^ Coz foi pai de Anube e Zobeba e foi o antepassado dos grupos de famílias que descendem de Acarel, filho de Harum.

[[v13-4-9]]

^<<v13-4-9,9>>^ Houve um homem chamado Jabes, que foi a pessoa mais respeitada da sua família. A sua mãe pôs nele o nome de Jabes porque ela havia sofrido muito durante o parto.

[[v13-4-10]]

^<<v13-4-10,10>>^ Mas Jabes orou assim ao Deus de Israel: "Ó Deus, abençoa-me e dá-me muitas terras. Fica comigo e livra-me de qualquer coisa que possa me causar dor." E Deus atendeu a sua oração.

[[v13-4-11]]

^<<v13-4-11,11>>^ Quelube, irmão de Suá, foi pai de um filho chamado Meir. Meir foi pai de Estom,

[[v13-4-12]]

^<<v13-4-12,12>>^ e Estom foi pai de três filhos: Bete-Rafa, Paseia e Teína. Teína foi o fundador da cidade de Naás. Os descendentes deles moravam em Reca.

[[v13-4-13]]

^<<v13-4-13,13>>^ Quenaz foi pai de dois filhos: Otoniel e Seraías. Otoniel também foi pai de dois filhos: Hatate e Meonotai.

[[v13-4-14]]

^<<v13-4-14,14>>^ Meonotai foi pai de Ofrá. Seraías foi pai de Joabe, o fundador do vale dos Artesãos, onde todos os homens faziam trabalhos de artesanato.

[[v13-4-15]]

^<<v13-4-15,15>>^ Calebe, filho de Jefoné, foi pai de três filhos: Iru, Elá e Naã. E Elá foi pai de Quenaz.

[[v13-4-16]]

^<<v13-4-16,16>>^ Jealelel foi pai de quatro filhos: Zife, Zifa, Tiria e Asareel.

[[v13-4-17]]

^<<v13-4-17,17>>^ Esdras foi pai de quatro filhos: Jéter, Merede, Éfer e Jalom. Merede casou com Bitia, que era filha do rei do Egito, e eles tiveram uma filha chamada Míriam e dois filhos: Samai e Isba. Isba fundou a cidade de Estemoa.

[[v13-4-18]]

^<<v13-4-18,18>>^ Merede também casou com uma mulher da tribo  de Judá, e eles tiveram três filhos: Jerede, que fundou a cidade de Gedor; Héber, que fundou Socó; e Jecutiel, que fundou Zanoa.

[[v13-4-19]]

^<<v13-4-19,19>>^ Hodias casou com a irmã de Naã. Os seus descendentes fundaram o grupo de famílias de Garmi, que morava na cidade de Queila, e o grupo de famílias de Maacá, que morava em Estemoa.

[[v13-4-20]]

^<<v13-4-20,20>>^ Simão foi pai de quatro filhos: Amnom, Rina, Ben-Hanã e Tilom. Isi foi pai de dois filhos: Zoete e Ben-Zoete.

[[v13-4-21]]

^<<v13-4-21,21>>^ Selá foi um dos filhos de Judá. Um dos descendentes de Selá foi Er, que fundou a cidade de Leca; outro foi Lada, que fundou Maressa. Selá foi também o antepassado dos grupos de famílias que teciam linho e que moravam na cidade de Bete-Asbeia.

[[v13-4-22]]

^<<v13-4-22,22>>^ Foi também o antepassado de Joquim e do povo que morava na cidade de Cozeba. E também de Joás e Sarafe, que casaram com mulheres moabitas e ficaram morando em Belém. (Estes registros são antigos.)

[[v13-4-23]]

^<<v13-4-23,23>>^ Eles eram oleiros que trabalhavam para o rei e moravam nas cidades de Netaim e Gedera.

[[v13-4-24]]

^<<v13-4-24,24>>^ Simeão foi pai de cinco filhos: Nemuel, Jamim, Jaribe, Zera e Saul.

[[v13-4-25]]

^<<v13-4-25,25>>^ Saul foi pai de Salum, Salum foi pai de Mibsão, e Mibsão foi pai de Misma.

[[v13-4-26]]

^<<v13-4-26,26>>^ Misma foi pai de Hamuel, Hamuel foi pai de Zacur, e Zacur foi pai de Simei.

[[v13-4-27]]

^<<v13-4-27,27>>^ Simei foi pai de dezesseis filhos e seis filhas, mas os seus parentes tiveram menos filhos do que ele, e a tribo  de Simeão não cresceu tanto como a tribo de Judá.

[[v13-4-28]]

^<<v13-4-28,28>>^ Até o tempo do rei Davi, os descendentes de Simeão moravam nas seguintes cidades: Berseba, Molada, Hazar-Sual,

[[v13-4-29]]

^<<v13-4-29,29>>^ Bila, Ezém, Tolade,

[[v13-4-30]]

^<<v13-4-30,30>>^ Betuel, Horma, Ziclague,

[[v13-4-31]]

^<<v13-4-31,31>>^ Bete-Marcabote, Hazar-Susim, Bete-Biri e Saaraim.

[[v13-4-32]]

^<<v13-4-32,32>>^ Eles também moravam em mais cinco cidades: Etã, Aim, Rimom, Toquém e Asã,

[[v13-4-33]]

^<<v13-4-33,33>>^ e nos povoados que ficavam ao seu redor, até a cidade de Baal. São essas as suas famílias e os lugares onde moravam.

[[v13-4-34]]

^<<v13-4-34,34>>^ São estes os chefes dos seus grupos de famílias: Mesobabe, Janleque, Josa, filho de Amazias; Joel, Jeú, filho de Josibias, neto de Seraías e bisneto de Asiel; Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaías, Ziza, filho de Sifi, neto de Alom, bisneto de Jedaías, trineto de Sinri e tetraneto de Samaías. As suas famílias continuaram a aumentar, e por isso

[[v13-4-35]]

^<<v13-4-35,35>>^ São estes os chefes dos seus grupos de famílias: Mesobabe, Janleque, Josa, filho de Amazias; Joel, Jeú, filho de Josibias, neto de Seraías e bisneto de Asiel; Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaías, Ziza, filho de Sifi, neto de Alom, bisneto de Jedaías, trineto de Sinri e tetraneto de Samaías.

[[v13-4-36]]

^<<v13-4-36,36>>^ São estes os chefes dos seus grupos de famílias: Mesobabe, Janleque, Josa, filho de Amazias; Joel, Jeú, filho de Josibias, neto de Seraías e bisneto de Asiel; Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaías, Ziza, filho de Sifi, neto de Alom, bisneto de Jedaías, trineto de Sinri e tetraneto de Samaías.

[[v13-4-37]]

^<<v13-4-37,37>>^ São estes os chefes dos seus grupos de famílias: Mesobabe, Janleque, Josa, filho de Amazias; Joel, Jeú, filho de Josibias, neto de Seraías e bisneto de Asiel; Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaías, Ziza, filho de Sifi, neto de Alom, bisneto de Jedaías, trineto de Sinri e tetraneto de Samaías.

[[v13-4-38]]

^<<v13-4-38,38>>^ São estes os chefes dos seus grupos de famílias: Mesobabe, Janleque, Josa, filho de Amazias; Joel, Jeú, filho de Josibias, neto de Seraías e bisneto de Asiel; Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaías, Ziza, filho de Sifi, neto de Alom, bisneto de Jedaías, trineto de Sinri e tetraneto de Samaías.

'''

xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-005.adoc#v13-5-0[Próximo Capítulo &#62;]