include::./index.adoc[]

[[v13-27-0]]
=== 1 Crônicas, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-27-1]]

^<<v13-27-1,1>>^ Esta é a lista dos israelitas chefes de famílias e líderes de grupos de famílias e os seus oficiais que prestavam serviço militar no reino. Cada mês do ano um grupo diferente de vinte e quatro mil homens estava de serviço, dirigidos pelo comandante daquele mês.

[[v13-27-2]]

^<<v13-27-2,2>>^ Os comandantes de cada mês eram os seguintes: Primeiro mês: Jasobeão, filho de Zabdiel. Ele era do grupo de famílias de Peres, uma parte da tribo  de Judá. Segundo mês: Dodai, descendente de Aoí. Miclote era o seu ajudante no comando. Terceiro mês: Benaías, filho do sacerdote Joiada. Benaías era o líder do grupo chamado "Os Trinta", e o seu filho Amizabade ficou no lugar dele como comandante desse grupo. Quarto mês: Asael, irmão de Joabe. Depois o seu filho Zebadias ficou no lugar dele. Quinto mês: Samute, descendente de Isar. Sexto mês: Ira, filho de Iques, da cidade de Tecoa. Sétimo mês: Heles, da tribo de Efraim, que era da cidade de Pelom. Oitavo mês: Sibecai, da cidade de Husa, que era do grupo de famílias de Zera, uma parte da tribo de Judá. Nono mês: Abiezer, da cidade de Anatote, no território da tribo de Benjamim. Décimo mês: Maarai, da cidade de Netofa, que era do grupo de famílias de Zera. Décimo primeiro mês: Benaías, da cidade de Piratom, que ficava no território da tribo de Efraim. Décimo segundo mês: Heldai, da cidade de Netofa, que era descendente de Otoniel.

[[v13-27-3]]

^<<v13-27-3,3>>^ Os comandantes de cada mês eram os seguintes:

[[v13-27-4]]

^<<v13-27-4,4>>^ Os comandantes de cada mês eram os seguintes:

[[v13-27-5]]

^<<v13-27-5,5>>^ Os comandantes de cada mês eram os seguintes:

[[v13-27-6]]

^<<v13-27-6,6>>^ Os comandantes de cada mês eram os seguintes:

[[v13-27-7]]

^<<v13-27-7,7>>^ Os comandantes de cada mês eram os seguintes:

[[v13-27-8]]

^<<v13-27-8,8>>^ Os comandantes de cada mês eram os seguintes:

[[v13-27-9]]

^<<v13-27-9,9>>^ Os comandantes de cada mês eram os seguintes:

'''

xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[Próximo Capítulo &#62;]