include::./index.adoc[]

[[v13-14-0]]
=== 1 Crônicas, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v13-14-1]]

^<<v13-14-1,1>>^ O rei Hirão, da cidade de Tiro, enviou embaixadores a Davi. Ele mandou toras de cedro e também carpinteiros e pedreiros para construírem um palácio para Davi.

[[v13-14-2]]

^<<v13-14-2,2>>^ E assim Davi entendeu que o Senhor  o havia confirmado como rei de Israel e que, por amor ao seu povo, estava fazendo o seu reino progredir.

[[v13-14-3]]

^<<v13-14-3,3>>^ Em Jerusalém, Davi casou com outras mulheres e foi pai de mais filhos e filhas.

[[v13-14-4]]

^<<v13-14-4,4>>^ São estes os nomes dos seus filhos que nasceram em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v13-14-5]]

^<<v13-14-5,5>>^ Ibar, Elisua, Elpelete,

[[v13-14-6]]

^<<v13-14-6,6>>^ Noga, Nefegue, Jafia,

[[v13-14-7]]

^<<v13-14-7,7>>^ Elisama, Beeliada e Elifelete.

[[v13-14-8]]

^<<v13-14-8,8>>^ Quando os filisteus souberam que Davi tinha sido ungido  como rei do país inteiro de Israel, o seu exército saiu para prendê-lo. Davi soube disso e saiu para encontrar-se com eles.

[[v13-14-9]]

^<<v13-14-9,9>>^ Os filisteus chegaram ao vale dos Gigantes e começaram a atacar e a roubar.

[[v13-14-10]]

^<<v13-14-10,10>>^ Então Davi perguntou a Deus: — Devo lutar contra os filisteus? Tu me darás a vitória? — Vá! — disse o Senhor . — Eu lhe darei a vitória.

[[v13-14-11]]

^<<v13-14-11,11>>^ Davi os atacou em Baal-Perazim e os derrotou. Ele disse: — Como se eu fosse uma enchente que derruba tudo, Deus me usou para abrir uma brecha no meio do exército inimigo. Por isso, aquele lugar é chamado de Baal-Perazim .

[[v13-14-12]]

^<<v13-14-12,12>>^ Quando os filisteus fugiram, deixaram os seus ídolos para trás, e Davi ordenou que fossem queimados.

[[v13-14-13]]

^<<v13-14-13,13>>^ Mas logo os filisteus voltaram ao vale e começaram a atacar.

[[v13-14-14]]

^<<v13-14-14,14>>^ Mais uma vez Davi consultou a Deus, e ele respondeu: — Não os ataque daqui. Dê a volta e ataque pelo outro lado, perto das amoreiras.

[[v13-14-15]]

^<<v13-14-15,15>>^ Quando você ouvir o barulho de marcha por cima das amoreiras, ataque-os porque isso quer dizer que eu estou indo na sua frente para derrotar o exército dos filisteus.

[[v13-14-16]]

^<<v13-14-16,16>>^ Davi fez o que Deus havia mandado e obrigou os inimigos a recuar desde Gibeão até Gezer.

[[v13-14-17]]

^<<v13-14-17,17>>^ A fama de Davi se espalhou por toda parte, e o Senhor  fez com que todas as nações ficassem com medo dele.

'''

xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[Próximo Capítulo &#62;]