include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v59-4-1]]

^<<v59-4-1,1>>^ De onde vêm as lutas e as brigas entre vocês? Elas vêm dos maus desejos que estão sempre lutando dentro de vocês.

[[v59-4-2]]

^<<v59-4-2,2>>^ Vocês querem muitas coisas; mas, como não podem tê-las, estão prontos até para matar a fim de consegui-las. Vocês as desejam ardentemente; mas, como não conseguem possuí-las, brigam e lutam. Não conseguem o que querem porque não pedem a Deus.

[[v59-4-3]]

^<<v59-4-3,3>>^ E, quando pedem, não recebem porque os seus motivos são maus. Vocês pedem coisas a fim de usá-las para os seus próprios prazeres.

[[v59-4-4]]

^<<v59-4-4,4>>^ Gente infiel! Será que vocês não sabem que ser amigo do mundo é ser inimigo de Deus? Quem quiser ser amigo do mundo se torna inimigo de Deus.

[[v59-4-5]]

^<<v59-4-5,5>>^ Não pensem que não quer dizer nada esta passagem das Escrituras Sagradas  : "O espírito que Deus pôs em nós está cheio de desejos violentos."

[[v59-4-6]]

^<<v59-4-6,6>>^ Porém a bondade que Deus mostra é ainda mais forte, pois as Escrituras Sagradas dizem: "Deus é contra os orgulhosos, mas é bondoso com os humildes."

[[v59-4-7]]

^<<v59-4-7,7>>^ Portanto, obedeçam a Deus e enfrentem o Diabo, que ele fugirá de vocês.

[[v59-4-8]]

^<<v59-4-8,8>>^ Cheguem perto de Deus, e ele chegará perto de vocês. Lavem as mãos, pecadores! Limpem o coração, hipócritas!

[[v59-4-9]]

^<<v59-4-9,9>>^ Fiquem tristes, gritem e chorem. Mudem as suas risadas em choro e a sua alegria em tristeza.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhem-se diante do Senhor, e ele os colocará numa posição de honra.

[[v59-4-11]]

^<<v59-4-11,11>>^ Meus irmãos, não falem mal uns dos outros. Quem fala mal do seu irmão em Cristo ou o julga está falando mal da lei  e julgando-a. Pois, se você julga a lei, então já não é uma pessoa que obedece à lei, mas é alguém que a julga.

[[v59-4-12]]

^<<v59-4-12,12>>^ Deus é o único que faz as leis e o único juiz. Só ele pode salvar ou destruir. Quem você pensa que é, para julgar os outros?

[[v59-4-13]]

^<<v59-4-13,13>>^ Agora escutem, vocês que dizem: "Hoje ou amanhã iremos a tal cidade e ali ficaremos um ano fazendo negócios e ganhando muito dinheiro!"

[[v59-4-14]]

^<<v59-4-14,14>>^ Vocês não sabem como será a sua vida amanhã, pois vocês são como uma neblina passageira, que aparece por algum tempo e logo depois desaparece.

[[v59-4-15]]

^<<v59-4-15,15>>^ O que vocês deveriam dizer é isto: "Se Deus quiser, estaremos vivos e faremos isto ou aquilo."

[[v59-4-16]]

^<<v59-4-16,16>>^ Porém vocês são orgulhosos e vivem se gabando. Todo esse orgulho é mau.

[[v59-4-17]]

^<<v59-4-17,17>>^ Portanto, comete pecado a pessoa que sabe fazer o bem e não faz.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]