include::./index.adoc[]

[[v59-5-0]]
=== Tiago, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v59-5-1]]

^<<v59-5-1,1>>^ Agora, ricos, escutem! Chorem e gritem pelas desgraças que vocês vão sofrer!

[[v59-5-2]]

^<<v59-5-2,2>>^ As suas riquezas estão podres, e as suas roupas finas estão comidas pelas traças.

[[v59-5-3]]

^<<v59-5-3,3>>^ O seu ouro e a sua prata estão cobertos de ferrugem, e essa ferrugem será testemunha contra vocês e, como fogo, comerá o corpo de vocês. Nestes últimos tempos vocês têm amontoado riquezas

[[v59-5-4]]

^<<v59-5-4,4>>^ e não têm pago os salários das pessoas que trabalham nos seus campos. Escutem as suas reclamações! Os gritos dos que trabalham nas colheitas têm chegado até os ouvidos de Deus, o Senhor Todo-Poderoso.

[[v59-5-5]]

^<<v59-5-5,5>>^ Vocês têm tido uma vida de luxo e prazeres aqui na terra e estão gordos como gado pronto para o matadouro.

[[v59-5-6]]

^<<v59-5-6,6>>^ Vocês têm condenado e matado os inocentes, e eles não podem fazer nada contra vocês.

[[v59-5-7]]

^<<v59-5-7,7>>^ Por isso, irmãos, tenham paciência até que o Senhor venha. Vejam como o lavrador espera com paciência que a sua terra dê colheitas preciosas. Ele espera pacientemente pelas chuvas do outono e da primavera.

[[v59-5-8]]

^<<v59-5-8,8>>^ Vocês também precisam ter paciência. Não desanimem, pois o Senhor virá logo.

[[v59-5-9]]

^<<v59-5-9,9>>^ Irmãos, não se queixem uns dos outros para não serem julgados por Deus. O Juiz está perto, pronto para vir.

[[v59-5-10]]

^<<v59-5-10,10>>^ Lembrem dos profetas  que falaram em nome do Senhor e os tomem como exemplo de paciência nos momentos de sofrimento.

[[v59-5-11]]

^<<v59-5-11,11>>^ E nós achamos que eles foram felizes por terem suportado o sofrimento com paciência. Vocês têm ouvido a respeito da paciência de Jó e sabem como no final Deus o abençoou. Porque o Senhor é cheio de bondade e de misericórdia.

[[v59-5-12]]

^<<v59-5-12,12>>^ Acima de tudo, meus irmãos, quando vocês prometerem alguma coisa, não jurem pelo céu, nem pela terra, nem por nada mais. Digam somente "sim", quando for sim, e "não", quando for não, para que Deus não os condene.

[[v59-5-13]]

^<<v59-5-13,13>>^ Se algum de vocês está sofrendo, ore. Se alguém está contente, cante hinos de agradecimento.

[[v59-5-14]]

^<<v59-5-14,14>>^ Se algum de vocês estiver doente, que chame os presbíteros  da igreja, para que façam oração e ponham azeite na cabeça dessa pessoa em nome do Senhor.

[[v59-5-15]]

^<<v59-5-15,15>>^ Essa oração, feita com fé, salvará a pessoa doente. O Senhor lhe dará saúde e perdoará os pecados que tiver cometido.

[[v59-5-16]]

^<<v59-5-16,16>>^ Portanto, confessem os seus pecados uns aos outros e façam oração uns pelos outros, para que vocês sejam curados. A oração de uma pessoa obediente a Deus tem muito poder.

[[v59-5-17]]

^<<v59-5-17,17>>^ O profeta Elias era um ser humano como nós. Ele orou com fervor para que não chovesse, e durante três anos e meio não choveu sobre a terra.

[[v59-5-18]]

^<<v59-5-18,18>>^ Depois orou outra vez, e então choveu, e a terra deu a sua colheita.

[[v59-5-19]]

^<<v59-5-19,19>>^ Meus irmãos, se algum de vocês se desviar da verdade, e outro o fizer voltar para o bom caminho,

[[v59-5-20]]

^<<v59-5-20,20>>^ lembrem disto: quem fizer um pecador voltar do seu mau caminho salvará da morte esse pecador e fará com que muitos pecados sejam perdoados.

'''

xref:059-tiago/059-tiago-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[Próximo Capítulo &#62;]