include::./index.adoc[]

[[v59-3-0]]
=== Tiago, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v59-3-1]]

^<<v59-3-1,1>>^ Meus irmãos, somente poucos de vocês deveriam se tornar mestres na Igreja, pois vocês sabem que nós, os que ensinamos, seremos julgados com mais rigor do que os outros.

[[v59-3-2]]

^<<v59-3-2,2>>^ Todos nós sempre cometemos erros. Quem não comete nenhum erro no que diz é uma pessoa madura, capaz de controlar todo o seu corpo.

[[v59-3-3]]

^<<v59-3-3,3>>^ Até na boca dos cavalos colocamos um freio para que nos obedeçam e assim fazemos com que vão aonde queremos.

[[v59-3-4]]

^<<v59-3-4,4>>^ Pensem no navio: grande como é, empurrado por ventos fortes, ele é guiado por um pequeno leme e vai aonde o piloto quer.

[[v59-3-5]]

^<<v59-3-5,5>>^ É isto o que acontece com a língua: mesmo pequena, ela se gaba de grandes coisas. Vejam como uma grande floresta pode ser incendiada por uma pequena chama!

[[v59-3-6]]

^<<v59-3-6,6>>^ A língua é um fogo. Ela é um mundo de maldade, ocupa o seu lugar no nosso corpo e espalha o mal em todo o nosso ser. Com o fogo que vem do próprio inferno, ela põe toda a nossa vida em chamas.

[[v59-3-7]]

^<<v59-3-7,7>>^ O ser humano é capaz de dominar todas as criaturas e tem dominado os animais selvagens, os pássaros, os animais que se arrastam pelo chão e os peixes.

[[v59-3-8]]

^<<v59-3-8,8>>^ Mas ninguém ainda foi capaz de dominar a língua. Ela é má, cheia de veneno mortal, e ninguém a pode controlar.

[[v59-3-9]]

^<<v59-3-9,9>>^ Usamos a língua tanto para agradecer ao Senhor e Pai como para amaldiçoar as pessoas, que foram criadas parecidas com Deus.

[[v59-3-10]]

^<<v59-3-10,10>>^ Da mesma boca saem palavras tanto de agradecimento como de maldição. Meus irmãos, isso não deve ser assim.

[[v59-3-11]]

^<<v59-3-11,11>>^ Por acaso pode a mesma fonte jorrar água doce e água amarga?

[[v59-3-12]]

^<<v59-3-12,12>>^ Meus irmãos, por acaso pode uma figueira dar azeitonas ou um pé de uva dar figos? Assim, também, uma fonte de água salgada não pode dar água doce.

[[v59-3-13]]

^<<v59-3-13,13>>^ Existe entre vocês alguém que seja sábio e inteligente? Pois então que prove isso pelo seu bom comportamento e pelas suas ações, praticadas com humildade e sabedoria.

[[v59-3-14]]

^<<v59-3-14,14>>^ Mas, se no coração de vocês existe inveja, amargura e egoísmo, então não mintam contra a verdade, gabando-se de serem sábios.

[[v59-3-15]]

^<<v59-3-15,15>>^ Essa espécie de sabedoria não vem do céu; ela é deste mundo, é da nossa natureza humana e é diabólica.

[[v59-3-16]]

^<<v59-3-16,16>>^ Pois, onde há inveja e egoísmo, há também confusão e todo tipo de coisas más.

[[v59-3-17]]

^<<v59-3-17,17>>^ A sabedoria que vem do céu é antes de tudo pura; e é também pacífica, bondosa e amigável. Ela é cheia de misericórdia, produz uma colheita de boas ações, não trata os outros pela sua aparência e é livre de fingimento.

[[v59-3-18]]

^<<v59-3-18,18>>^ Pois a bondade é a colheita produzida pelas sementes que foram plantadas pelos que trabalham em favor da paz.

'''

xref:059-tiago/059-tiago-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-tiago/059-tiago-004.adoc#v59-4-0[Próximo Capítulo &#62;]