include::./index.adoc[]

[[v59-2-0]]
=== Tiago, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v59-2-1]]

^<<v59-2-1,1>>^ Meus irmãos, vocês que creem no nosso glorioso  Senhor Jesus Cristo, nunca tratem as pessoas de modo diferente por causa da aparência delas.

[[v59-2-2]]

^<<v59-2-2,2>>^ Por exemplo, entra na reunião de vocês um homem com anéis de ouro e bem-vestido, e entra também outro, pobre e vestindo roupas velhas.

[[v59-2-3]]

^<<v59-2-3,3>>^ Digamos que vocês tratam melhor o que está bem-vestido e dizem: "Este é o melhor lugar; sente-se aqui", mas dizem ao pobre: "Fique de pé" ou "Sente-se aí no chão, perto dos meus pés."

[[v59-2-4]]

^<<v59-2-4,4>>^ Nesse caso vocês estão fazendo diferença entre vocês mesmos e estão se baseando em maus motivos para julgar o valor dos outros.

[[v59-2-5]]

^<<v59-2-5,5>>^ Escutem, meus queridos irmãos! Deus escolheu os pobres deste mundo para serem ricos na fé e para possuírem o Reino  que ele prometeu aos que o amam.

[[v59-2-6]]

^<<v59-2-6,6>>^ No entanto, vocês desprezam os pobres. Por acaso, não são os ricos que exploram vocês e os arrastam para serem julgados nos tribunais?

[[v59-2-7]]

^<<v59-2-7,7>>^ São eles que falam mal do bom nome que Deus deu a vocês.

[[v59-2-8]]

^<<v59-2-8,8>>^ Se vocês obedecerem à lei  do Reino, estarão fazendo o que devem, pois nas Escrituras Sagradas  está escrito: "Ame os outros como você ama a você mesmo."

[[v59-2-9]]

^<<v59-2-9,9>>^ Mas, se vocês tratam as pessoas pela aparência, estão pecando, e a lei os condena como culpados.

[[v59-2-10]]

^<<v59-2-10,10>>^ Porque quem quebra um só mandamento da lei é culpado de quebrar todos.

[[v59-2-11]]

^<<v59-2-11,11>>^ Pois o mesmo que disse: "Não cometa adultério" também disse: "Não mate". Mesmo que você não cometa adultério, será culpado de quebrar a lei se matar.

[[v59-2-12]]

^<<v59-2-12,12>>^ Falem e vivam como pessoas que serão julgadas pela lei que nos dá a liberdade.

[[v59-2-13]]

^<<v59-2-13,13>>^ Quando Deus julgar, não terá misericórdia das pessoas que não tiveram misericórdia dos outros. Mas as pessoas que tiveram misericórdia dos outros não serão condenadas no Dia do Juízo Final.

[[v59-2-14]]

^<<v59-2-14,14>>^ Meus irmãos, que adianta alguém dizer que tem fé se ela não vier acompanhada de ações? Será que essa fé pode salvá-lo?

[[v59-2-15]]

^<<v59-2-15,15>>^ Por exemplo, pode haver irmãos ou irmãs que precisam de roupa e que não têm nada para comer.

[[v59-2-16]]

^<<v59-2-16,16>>^ Se vocês não lhes dão o que eles precisam para viver, não adianta nada dizer: "Que Deus os abençoe! Vistam agasalhos e comam bem."

[[v59-2-17]]

^<<v59-2-17,17>>^ Portanto, a fé é assim: se não vier acompanhada de ações, é coisa morta.

[[v59-2-18]]

^<<v59-2-18,18>>^ Mas alguém poderá dizer: "Você tem fé, e eu tenho ações." E eu respondo: "Então me mostre como é possível ter fé sem que ela seja acompanhada de ações. Eu vou lhe mostrar a minha fé por meio das minhas ações."

[[v59-2-19]]

^<<v59-2-19,19>>^ Você crê que há somente um Deus? Ótimo! Os demônios também creem e tremem de medo.

[[v59-2-20]]

^<<v59-2-20,20>>^ Seu tolo! Vou provar-lhe que a fé sem ações não vale nada.

[[v59-2-21]]

^<<v59-2-21,21>>^ Como é que o nosso antepassado Abraão foi aceito por Deus? Foi pelo que fez quando ofereceu o seu filho Isaque sobre o altar.

[[v59-2-22]]

^<<v59-2-22,22>>^ Veja como a sua fé e as suas ações agiram juntas. Por meio das suas ações, a sua fé se tornou completa.

[[v59-2-23]]

^<<v59-2-23,23>>^ Assim aconteceu o que as Escrituras Sagradas  dizem: "Abraão creu em Deus, e por isso Deus o aceitou." E Abraão foi chamado de "amigo de Deus".

[[v59-2-24]]

^<<v59-2-24,24>>^ Assim, vocês veem que a pessoa é aceita por Deus por meio das suas ações e não somente pela fé.

[[v59-2-25]]

^<<v59-2-25,25>>^ Foi o que aconteceu com a prostituta Raabe, quando hospedou os espiões israelitas e os ajudou a sair da cidade por outro caminho. Deus a aceitou pelo que ela fez.

[[v59-2-26]]

^<<v59-2-26,26>>^ Portanto, assim como o corpo sem o espírito está morto, assim também a fé sem ações está morta.

'''

xref:059-tiago/059-tiago-001.adoc#v59-1-0[&#60; Capítulo Anterior] | <<v59-2-0,Topo>> | xref:059-tiago/059-tiago-003.adoc#v59-3-0[Próximo Capítulo &#62;]