include::./index.adoc[]

[[v56-3-0]]
=== Tito, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v56-3-1]]

^<<v56-3-1,1>>^ Recomende aos irmãos que respeitem as ordens dos que governam e das autoridades, que sejam obedientes e estejam prontos a fazer tudo o que é bom.

[[v56-3-2]]

^<<v56-3-2,2>>^ Aconselhe que não falem mal de ninguém, mas que sejam calmos e pacíficos e tratem todos com educação.

[[v56-3-3]]

^<<v56-3-3,3>>^ Pois antigamente nós mesmos não tínhamos juízo e éramos rebeldes e maus. Éramos escravos das paixões e dos prazeres de todo tipo e passávamos a nossa vida no meio da malícia e da inveja. Os outros tinham ódio de nós, e nós tínhamos ódio deles.

[[v56-3-4]]

^<<v56-3-4,4>>^ Porém, quando Deus, o nosso Salvador, mostrou a sua bondade e o seu amor por todos,

[[v56-3-5]]

^<<v56-3-5,5>>^ ele nos salvou porque teve compaixão de nós, e não porque nós tivéssemos feito alguma coisa boa. Ele nos salvou por meio do Espírito Santo, que nos lavou , fazendo com que nascêssemos de novo e dando-nos uma nova vida.

[[v56-3-6]]

^<<v56-3-6,6>>^ Deus derramou com generosidade o seu Espírito Santo sobre nós, por meio de Jesus Cristo, o nosso Salvador.

[[v56-3-7]]

^<<v56-3-7,7>>^ E fez isso para que, pela sua graça , nós sejamos aceitos por Deus e recebamos a vida eterna que esperamos.

[[v56-3-8]]

^<<v56-3-8,8>>^ Esse ensinamento é verdadeiro. Quero que você, Tito, insista nesses assuntos, para que os que creem em Deus se interessem em usar o seu tempo fazendo o bem. Isso é bom e útil para todos.

[[v56-3-9]]

^<<v56-3-9,9>>^ Mas evite as discussões tolas, as longas listas de nomes de antepassados , as brigas e os debates a respeito da lei  dos judeus. Essas coisas são inúteis e sem valor.

[[v56-3-10]]

^<<v56-3-10,10>>^ Se uma pessoa causar divisões entre os irmãos na fé, aconselhe essa pessoa uma ou duas vezes; mas depois disso não tenha nada mais a ver com ela.

[[v56-3-11]]

^<<v56-3-11,11>>^ Pois você sabe que uma pessoa como esta abandonou completamente o evangelho , e os seus pecados provam que ela está errada.

[[v56-3-12]]

^<<v56-3-12,12>>^ Quando eu lhe mandar o irmão Ártemas ou o irmão Tíquico, faça o possível para ir se encontrar comigo na cidade de Nicópolis, pois resolvi passar o inverno lá.

[[v56-3-13]]

^<<v56-3-13,13>>^ Ajude o advogado Zenas e também Apolo em tudo o que você puder a fim de que eles tenham o que precisarem para a viagem.

[[v56-3-14]]

^<<v56-3-14,14>>^ Que a nossa gente aprenda a usar o seu tempo fazendo o bem e ajudando os outros em caso de necessidade, para que assim a vida da nossa gente seja útil!

[[v56-3-15]]

^<<v56-3-15,15>>^ Todos os que estão comigo mandam saudações a você. Dê saudações aos nossos amigos na fé. Que a graça  de Deus esteja com todos vocês!

'''

xref:056-tito/056-tito-002.adoc#v56-2-0[&#60; Capítulo Anterior] | <<v56-3-0,Topo>> | xref:057-filemom/057-filemom-001.adoc#v57-1-0[Próximo Capítulo &#62;]