include::./index.adoc[]

[[v56-1-0]]
=== Tito, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v56-1-1]]

^<<v56-1-1,1>>^ Eu, Paulo, servo  de Deus e apóstolo  de Jesus Cristo, escrevo esta carta. Eu fui escolhido e mandado para ajudar a tornar mais forte a fé que o povo de Deus tem e para fazer com que eles conheçam a verdade ensinada pela nossa religião,

[[v56-1-2]]

^<<v56-1-2,2>>^ que se baseia na esperança de recebermos a vida eterna. Deus, que não mente, nos prometeu essa vida, antes da criação do mundo,

[[v56-1-3]]

^<<v56-1-3,3>>^ e no tempo certo ele a revelou na sua mensagem. Essa mensagem foi entregue a mim, e eu a anuncio por ordem de Deus, o nosso Salvador.

[[v56-1-4]]

^<<v56-1-4,4>>^ Escrevo a você, Tito, meu verdadeiro filho na fé, esta fé que é sua e minha. Que a graça  e a paz de Deus, o Pai, e de Cristo Jesus, o nosso Salvador, estejam com você!

[[v56-1-5]]

^<<v56-1-5,5>>^ Eu o deixei na ilha de Creta para que você pusesse em ordem o que ainda faltava fazer e para nomear em cada cidade os presbíteros  das igrejas. Lembre das minhas ordens:

[[v56-1-6]]

^<<v56-1-6,6>>^ O presbítero deve ser um homem que ninguém possa culpar de nada; deve ter somente uma esposa; os seus filhos devem ser cristãos e não ter fama de maus ou desobedientes.

[[v56-1-7]]

^<<v56-1-7,7>>^ Pois aquele que tem a responsabilidade do trabalho de Deus, como bispo , deve ser um homem que não possa ser culpado de nada. Não deve ser orgulhoso, nem ter mau gênio, não deve ser chegado ao vinho, nem violento, nem ganancioso.

[[v56-1-8]]

^<<v56-1-8,8>>^ Deve estar disposto a hospedar pessoas na sua casa e deve amar o bem. Deve ser prudente, justo, dedicado a Deus e disciplinado.

[[v56-1-9]]

^<<v56-1-9,9>>^ Deve se manter firme na mensagem que merece confiança e que está de acordo com a doutrina. Assim ele poderá animar os outros com o verdadeiro ensinamento e também mostrar o erro dos que são contra esse ensinamento.

[[v56-1-10]]

^<<v56-1-10,10>>^ Pois existem muitos, principalmente os que vieram do Judaísmo, que são revoltados e enganam os outros com as suas tolices.

[[v56-1-11]]

^<<v56-1-11,11>>^ É preciso fazer com que eles parem de falar, pois estão atrapalhando famílias inteiras por ensinarem o que não devem, com a intenção vergonhosa de ganhar dinheiro.

[[v56-1-12]]

^<<v56-1-12,12>>^ Foi justamente um deles, um profeta  da ilha de Creta , quem disse: "Os cretenses só dizem mentiras. São como animais selvagens, são uns preguiçosos que só pensam em comida."

[[v56-1-13]]

^<<v56-1-13,13>>^ E ele tinha razão quando disse isso. Portanto, você tem de repreender duramente esses falsos mestres para que sejam sadios na fé

[[v56-1-14]]

^<<v56-1-14,14>>^ e parem de dar atenção a histórias inventadas por judeus e a ensinamentos humanos que vêm de pessoas que rejeitam a verdade.

[[v56-1-15]]

^<<v56-1-15,15>>^ Tudo é puro para os que são puros; mas nada é puro para os impuros  e descrentes, pois a mente e a consciência deles estão sujas.

[[v56-1-16]]

^<<v56-1-16,16>>^ Eles dizem que conhecem a Deus, mas o que eles fazem mostra que isso não é verdade. Estão cheios de ódio, são rebeldes e não são capazes de fazer nenhuma coisa boa.

'''

xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-tito/056-tito-002.adoc#v56-2-0[Próximo Capítulo &#62;]