include::./index.adoc[]

[[v62-4-0]]
=== 1 João, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v62-4-1]]

^<<v62-4-1,1>>^ Meus queridos amigos, não acreditem em todos os que dizem que têm o Espírito de Deus. Ponham à prova essas pessoas para saber se o espírito que elas têm vem mesmo de Deus; pois muitos falsos profetas  já se espalharam por toda parte.

[[v62-4-2]]

^<<v62-4-2,2>>^ É assim que vocês poderão saber se, de fato, o espírito é de Deus: quem afirma que Jesus Cristo veio como um ser humano tem o Espírito que vem de Deus.

[[v62-4-3]]

^<<v62-4-3,3>>^ Mas quem nega isso a respeito de Jesus não tem o Espírito de Deus; o que ele tem é o espírito do Inimigo de Cristo . Vocês ouviram dizer que esse espírito viria, e agora ele já está no mundo.

[[v62-4-4]]

^<<v62-4-4,4>>^ Meus filhinhos , vocês são de Deus e têm derrotado os falsos profetas. Porque o Espírito que está em vocês é mais forte do que o espírito que está naqueles que pertencem ao mundo.

[[v62-4-5]]

^<<v62-4-5,5>>^ Eles falam das coisas do mundo, e o mundo os ouve porque eles pertencem ao mundo.

[[v62-4-6]]

^<<v62-4-6,6>>^ Mas nós somos de Deus. Quem conhece a Deus nos ouve, mas quem não pertence a Deus não nos ouve. É desse modo, então, que podemos saber a diferença que existe entre o Espírito da verdade e o espírito do erro.

[[v62-4-7]]

^<<v62-4-7,7>>^ Queridos amigos, amemos uns aos outros porque o amor vem de Deus. Quem ama é filho de Deus e conhece a Deus.

[[v62-4-8]]

^<<v62-4-8,8>>^ Quem não ama não o conhece, pois Deus é amor.

[[v62-4-9]]

^<<v62-4-9,9>>^ Foi assim que Deus mostrou o seu amor por nós: ele mandou o seu único Filho ao mundo para que pudéssemos ter vida por meio dele.

[[v62-4-10]]

^<<v62-4-10,10>>^ E o amor é isto: não fomos nós que amamos a Deus, mas foi ele que nos amou e mandou o seu Filho para que, por meio dele, os nossos pecados fossem perdoados.

[[v62-4-11]]

^<<v62-4-11,11>>^ Amigos, se foi assim que Deus nos amou, então nós devemos nos amar uns aos outros.

[[v62-4-12]]

^<<v62-4-12,12>>^ Nunca ninguém viu Deus. Se nos amamos uns aos outros, Deus vive unido conosco, e o seu amor enche completamente o nosso coração.

[[v62-4-13]]

^<<v62-4-13,13>>^ A razão por que podemos ter a certeza de que vivemos unidos com Deus e de que ele vive unido conosco é esta: ele nos deu o seu Espírito.

[[v62-4-14]]

^<<v62-4-14,14>>^ E nós vimos e anunciamos aos outros que o Pai enviou o Filho para ser o Salvador do mundo.

[[v62-4-15]]

^<<v62-4-15,15>>^ Todo aquele que afirma que Jesus é o Filho de Deus, Deus vive unido com ele, e ele vive unido com Deus.

[[v62-4-16]]

^<<v62-4-16,16>>^ E nós mesmos conhecemos o amor que Deus tem por nós e cremos nesse amor. Deus é amor. Aquele que vive no amor vive unido com Deus, e Deus vive unido com ele.

[[v62-4-17]]

^<<v62-4-17,17>>^ Assim o amor em nós é totalmente verdadeiro para que tenhamos coragem no Dia do Juízo, porque a nossa vida neste mundo é como a vida de Cristo.

[[v62-4-18]]

^<<v62-4-18,18>>^ No amor não há medo; o amor que é totalmente verdadeiro afasta o medo. Portanto, aquele que sente medo não tem no seu coração o amor totalmente verdadeiro, porque o medo mostra que existe castigo.

[[v62-4-19]]

^<<v62-4-19,19>>^ Nós amamos porque Deus nos amou primeiro.

[[v62-4-20]]

^<<v62-4-20,20>>^ Se alguém diz: "Eu amo a Deus", mas odeia o seu irmão, é mentiroso. Pois ninguém pode amar a Deus, a quem não vê, se não amar o seu irmão, a quem vê.

[[v62-4-21]]

^<<v62-4-21,21>>^ O mandamento que Cristo nos deu é este: quem ama a Deus, que ame também o seu irmão.

'''

xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[Próximo Capítulo &#62;]