include::./index.adoc[]

[[v62-2-0]]
=== 1 João, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v62-2-1]]

^<<v62-2-1,1>>^ Meus filhinhos , escrevo isso a vocês para que não pequem. Porém, se alguém pecar, temos Jesus Cristo, que faz o que é correto; ele nos defende diante do Pai.

[[v62-2-2]]

^<<v62-2-2,2>>^ É por meio do próprio Jesus Cristo que os nossos pecados são perdoados. E não somente os nossos, mas também os pecados do mundo inteiro.

[[v62-2-3]]

^<<v62-2-3,3>>^ Se obedecemos aos mandamentos de Deus, então temos certeza de que o conhecemos.

[[v62-2-4]]

^<<v62-2-4,4>>^ Se alguém diz: "Eu o conheço", mas não obedece aos seus mandamentos, é mentiroso, e não há verdade nele.

[[v62-2-5]]

^<<v62-2-5,5>>^ Porém, se obedecemos aos ensinamentos de Deus, sabemos que amamos a Deus de todo o nosso coração. É assim que podemos ter certeza de que estamos vivendo unidos com Deus:

[[v62-2-6]]

^<<v62-2-6,6>>^ Quem diz que vive unido com Deus deve viver como Jesus Cristo viveu.

[[v62-2-7]]

^<<v62-2-7,7>>^ Meus queridos amigos, este mandamento que estou dando a vocês não é novo. É o mandamento antigo, aquele que vocês receberam lá no começo. O mandamento antigo é a mensagem que vocês já ouviram.

[[v62-2-8]]

^<<v62-2-8,8>>^ Porém o mandamento que eu estou dando a vocês é novo porque a sua verdade é vista em Cristo e também em vocês. Pois a escuridão está passando, e já está brilhando a verdadeira luz.

[[v62-2-9]]

^<<v62-2-9,9>>^ Quem diz que vive na luz e odeia o seu irmão está na escuridão até agora.

[[v62-2-10]]

^<<v62-2-10,10>>^ Quem ama o seu irmão vive na luz, e não há nessa pessoa nada que leve alguém a pecar.

[[v62-2-11]]

^<<v62-2-11,11>>^ Mas quem odeia o seu irmão está na escuridão, anda nela e não sabe para onde está indo, porque a escuridão não deixa que essa pessoa enxergue.

[[v62-2-12]]

^<<v62-2-12,12>>^ Filhinhos , escrevo a vocês porque os seus pecados são perdoados por causa de Cristo.

[[v62-2-13]]

^<<v62-2-13,13>>^ Pais, escrevo a vocês porque conhecem aquele que existiu desde a criação do mundo . Jovens, escrevo a vocês porque vocês têm vencido o Maligno .

[[v62-2-14]]

^<<v62-2-14,14>>^ Escrevo a vocês, filhinhos, porque conhecem o Pai. Escrevo a vocês, pais, porque conhecem aquele que existiu desde a criação do mundo. Escrevo a vocês, jovens, porque são fortes. A mensagem de Deus vive em vocês, e vocês já venceram o Maligno.

[[v62-2-15]]

^<<v62-2-15,15>>^ Não amem o mundo, nem as coisas que há nele. Se vocês amam o mundo, não amam a Deus, o Pai.

[[v62-2-16]]

^<<v62-2-16,16>>^ Nada que é deste mundo vem do Pai. Os maus desejos da natureza humana, a vontade de ter o que agrada aos olhos e o orgulho pelas coisas da vida, tudo isso não vem do Pai, mas do mundo.

[[v62-2-17]]

^<<v62-2-17,17>>^ E o mundo passa, com tudo aquilo que as pessoas cobiçam; porém aquele que faz a vontade de Deus vive para sempre.

[[v62-2-18]]

^<<v62-2-18,18>>^ Meus filhinhos , o fim está perto. Vocês ouviram dizer que o Inimigo de Cristo vem. Pois agora muitos inimigos de Cristo já têm aparecido, e por isso sabemos que o fim está chegando.

[[v62-2-19]]

^<<v62-2-19,19>>^ De fato, essas pessoas nos deixaram porque não eram do nosso grupo. Se fossem do nosso grupo, teriam ficado conosco. Mas elas nos deixaram para que ficasse bem claro que nenhuma delas pertencia mesmo ao nosso grupo.

[[v62-2-20]]

^<<v62-2-20,20>>^ Porém sobre vocês Cristo tem derramado o Espírito Santo, e por isso todos vocês conhecem a verdade.

[[v62-2-21]]

^<<v62-2-21,21>>^ Portanto, eu escrevo a vocês, mas não é porque não conhecem a verdade. Pelo contrário, é porque a conhecem e sabem que nunca nenhuma mentira vem da verdade.

[[v62-2-22]]

^<<v62-2-22,22>>^ Então quem é mentiroso? É aquele que diz que Jesus não é o Messias . Quem diz isso é o Inimigo de Cristo; ele rejeita tanto o Pai como o Filho.

[[v62-2-23]]

^<<v62-2-23,23>>^ Pois quem rejeita o Filho rejeita também o Pai; e quem aceita o Filho tem também o Pai.

[[v62-2-24]]

^<<v62-2-24,24>>^ Por isso guardem no coração a mensagem que ouviram desde o começo. Se aquilo que ouviram desde o começo ficar no coração de vocês, então viverão sempre unidos com o Filho e com o Pai.

[[v62-2-25]]

^<<v62-2-25,25>>^ E o que o próprio Cristo prometeu dar a todos nós foi isto: a vida eterna.

[[v62-2-26]]

^<<v62-2-26,26>>^ Eu estou escrevendo isso a vocês a respeito dos que estão tentando enganá-los.

[[v62-2-27]]

^<<v62-2-27,27>>^ Mas sobre vocês Cristo tem derramado o seu Espírito. Enquanto o seu Espírito estiver em vocês, não é preciso que ninguém os ensine. Pois o Espírito ensina a respeito de tudo, e os seus ensinamentos não são falsos, mas verdadeiros. Portanto, obedeçam aos ensinamentos do Espírito e continuem unidos com Cristo.

[[v62-2-28]]

^<<v62-2-28,28>>^ Sim, meus filhinhos , continuem unidos com Cristo, para que possamos estar cheios de coragem no dia em que ele vier. Assim não precisaremos ficar com vergonha e nos esconder dele naquele dia.

[[v62-2-29]]

^<<v62-2-29,29>>^ Já que vocês sabem que Cristo sempre fez o que é correto, devem saber também que quem faz o que é correto é filho de Deus.

'''

xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[&#60; Capítulo Anterior] | <<v62-2-0,Topo>> | xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[Próximo Capítulo &#62;]