include::./index.adoc[]

[[v62-1-0]]
=== 1 João, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v62-1-1]]

^<<v62-1-1,1>>^ Estamos escrevendo a vocês a respeito da Palavra da vida, que existiu desde a criação do mundo. Nós a ouvimos e com os nossos próprios olhos a vimos. De fato, nós a vimos, e as nossas mãos tocaram nela.

[[v62-1-2]]

^<<v62-1-2,2>>^ Quando essa vida apareceu, nós a vimos. É por isso que agora falamos dela e anunciamos a vocês a vida eterna que estava com o Pai e que nos foi revelada.

[[v62-1-3]]

^<<v62-1-3,3>>^ Contamos a vocês o que vimos e ouvimos para que vocês estejam unidos conosco, assim como nós estamos unidos com o Pai e com Jesus Cristo, o seu Filho.

[[v62-1-4]]

^<<v62-1-4,4>>^ Escrevemos isso para que a nossa alegria seja completa.

[[v62-1-5]]

^<<v62-1-5,5>>^ A mensagem que Cristo nos deu e que anunciamos a vocês é esta: Deus é luz , e não há nele nenhuma escuridão .

[[v62-1-6]]

^<<v62-1-6,6>>^ Portanto, se dizemos que estamos unidos com Deus e ao mesmo tempo vivemos na escuridão, então estamos mentindo com palavras e ações.

[[v62-1-7]]

^<<v62-1-7,7>>^ Porém, se vivemos na luz, como Deus está na luz, então estamos unidos uns com os outros, e o sangue de Jesus, o seu Filho, nos limpa de todo pecado.

[[v62-1-8]]

^<<v62-1-8,8>>^ Se dizemos que não temos pecados, estamos nos enganando, e não há verdade em nós.

[[v62-1-9]]

^<<v62-1-9,9>>^ Mas, se confessarmos os nossos pecados a Deus, ele cumprirá a sua promessa e fará o que é correto: ele perdoará os nossos pecados e nos limpará de toda maldade.

[[v62-1-10]]

^<<v62-1-10,10>>^ Se dizemos que não temos cometido pecados, fazemos de Deus um mentiroso, e a sua mensagem não está em nós.

'''

xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[Próximo Capítulo &#62;]