include::./index.adoc[]

[[v62-5-0]]
=== 1 João, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v62-5-1]]

^<<v62-5-1,1>>^ Todos aqueles que creem que Jesus é o Messias  são filhos de Deus. E quem ama um pai ama também os filhos desse pai.

[[v62-5-2]]

^<<v62-5-2,2>>^ Nós sabemos que amamos os filhos de Deus quando amamos a Deus e obedecemos aos seus mandamentos.

[[v62-5-3]]

^<<v62-5-3,3>>^ Pois amar a Deus é obedecer aos seus mandamentos. E os seus mandamentos não são difíceis de obedecer

[[v62-5-4]]

^<<v62-5-4,4>>^ porque todo filho de Deus pode vencer o mundo. Assim, com a nossa fé conseguimos a vitória sobre o mundo.

[[v62-5-5]]

^<<v62-5-5,5>>^ Quem pode vencer o mundo? Somente aquele que crê que Jesus é o Filho de Deus.

[[v62-5-6]]

^<<v62-5-6,6>>^ Jesus Cristo é aquele que veio com a água do seu batismo e com o sangue da sua morte. Ele veio com a água e com o sangue e não somente com a água. E o próprio Espírito Santo é testemunha de que isso é verdade porque o Espírito é a verdade.

[[v62-5-7]]

^<<v62-5-7,7>>^ Há três testemunhas:

[[v62-5-8]]

^<<v62-5-8,8>>^ o Espírito, a água e o sangue; e esses três estão de pleno acordo.

[[v62-5-9]]

^<<v62-5-9,9>>^ Nós aceitamos o testemunho dos seres humanos, mas o testemunho de Deus tem mais valor. E esse é o testemunho que Deus deu a respeito do seu Filho.

[[v62-5-10]]

^<<v62-5-10,10>>^ Aquele que crê no Filho de Deus tem esse testemunho no seu próprio coração. Mas quem não crê em Deus faz de Deus um mentiroso, porque não crê no testemunho que Deus deu a respeito do seu Filho.

[[v62-5-11]]

^<<v62-5-11,11>>^ E este é o testemunho: Deus nos deu a vida eterna, e essa vida é nossa por meio do seu Filho.

[[v62-5-12]]

^<<v62-5-12,12>>^ Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida.

[[v62-5-13]]

^<<v62-5-13,13>>^ Eu escrevo essas coisas a vocês que creem no Filho de Deus, para que vocês saibam que têm a vida eterna.

[[v62-5-14]]

^<<v62-5-14,14>>^ Quando estamos na presença de Deus, temos coragem por causa do seguinte: se pedimos alguma coisa de acordo com a sua vontade, temos a certeza de que ele nos ouve.

[[v62-5-15]]

^<<v62-5-15,15>>^ Assim sabemos que ele nos ouve quando lhe pedimos alguma coisa. E, como sabemos que isso é verdade, sabemos também que ele nos dá o que lhe pedimos.

[[v62-5-16]]

^<<v62-5-16,16>>^ Se alguém vê o seu irmão cometer algum pecado que não traz a morte, deve orar a Deus, e ele dará a vida a essa pessoa. Isso, no caso de pecados que não trazem a morte. Mas há pecado que traz a morte, e eu não digo que vocês orem a respeito desse pecado.

[[v62-5-17]]

^<<v62-5-17,17>>^ Toda maldade é pecado; porém há pecados que não trazem a morte.

[[v62-5-18]]

^<<v62-5-18,18>>^ Sabemos que os filhos de Deus não continuam pecando, porque o Filho de Deus os guarda, e o Maligno não pode tocar neles.

[[v62-5-19]]

^<<v62-5-19,19>>^ Sabemos que somos de Deus e que o mundo todo está debaixo do poder do Maligno.

[[v62-5-20]]

^<<v62-5-20,20>>^ Sabemos também que o Filho de Deus já veio e nos deu entendimento para conhecermos o Deus verdadeiro. A nossa vida está unida com o Deus verdadeiro, unida com o seu Filho, Jesus Cristo. Este é o Deus verdadeiro, e esta é a vida eterna.

[[v62-5-21]]

^<<v62-5-21,21>>^ Meus filhinhos , cuidado com os falsos deuses!

'''

xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v62-5-0,Topo>> | xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[Próximo Capítulo &#62;]