include::./index.adoc[]

[[v16-1-0]]
=== Neemias, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-1-1]]

^<<v16-1-1,1>>^ Esta é a história de Neemias, filho de Hacalias. No mês de quisleu , no ano vinte do reinado de Artaxerxes, rei da Pérsia, eu, que me chamo Neemias, estava em Susã, a capital do país.

[[v16-1-2]]

^<<v16-1-2,2>>^ Hanani, um dos meus irmãos, chegou de Judá com um grupo de outros judeus. Então eu pedi notícias da cidade de Jerusalém e dos judeus que haviam voltado do cativeiro  na Babilônia.

[[v16-1-3]]

^<<v16-1-3,3>>^ Eles me contaram que aqueles que não tinham morrido e haviam voltado para a província  de Judá estavam passando por grandes dificuldades. Contaram também que os estrangeiros que moravam ali por perto os desprezavam. Disseram, finalmente, que as muralhas de Jerusalém ainda estavam caídas e que os portões que haviam sido queimados ainda não tinham sido consertados.

[[v16-1-4]]

^<<v16-1-4,4>>^ Quando ouvi isso, eu me sentei e chorei. Durante alguns dias, eu fiquei chorando e não comi nada. E fiz a Deus esta oração:

[[v16-1-5]]

^<<v16-1-5,5>>^ — Ó Senhor , Deus do céu, tu és grande, e nós te tememos ! Tu és fiel e guardas a tua aliança  com aqueles que te amam e obedecem aos teus mandamentos.

[[v16-1-6]]

^<<v16-1-6,6>>^ Olha para mim, ó Deus, e ouve as orações que faço dia e noite em favor dos teus servos , o povo de Israel. Eu confesso que nós, o povo de Israel, temos pecado. Os meus antepassados e eu temos pecado.

[[v16-1-7]]

^<<v16-1-7,7>>^ Com os nossos atos, temos pecado contra ti e não temos obedecido aos teus mandamentos. Não temos obedecido às leis  que nos deste por meio de Moisés, teu servo.

[[v16-1-8]]

^<<v16-1-8,8>>^ Lembra agora do que disseste a ele: "Se vocês, o povo de Israel, forem infiéis a mim, eu os espalharei entre as outras nações.

[[v16-1-9]]

^<<v16-1-9,9>>^ Mas, se depois disso, vocês voltarem para mim e obedecerem aos meus mandamentos, eu os trarei de volta para o lugar que escolhi para ali ser adorado, mesmo que vocês estejam espalhados pelos fins da terra."

[[v16-1-10]]

^<<v16-1-10,10>>^ — Senhor, estes são teus servos, o teu povo. Tu os livraste do cativeiro com o teu grande poder e com a tua força.

[[v16-1-11]]

^<<v16-1-11,11>>^ Ouve agora a minha oração e as orações de todos os outros teus servos que têm prazer em te adorar. Faze com que eu tenha sucesso hoje e que o rei seja bondoso comigo. Nesse tempo eu estava encarregado de servir vinho ao rei.

'''

xref:015-esdras/015-esdras-010.adoc#v15-10-0[&#60; Capítulo Anterior] | <<v16-1-0,Topo>> | xref:016-neemias/016-neemias-002.adoc#v16-2-0[Próximo Capítulo &#62;]