include::./index.adoc[]

[[v16-9-0]]
=== Neemias, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-9-1]]

^<<v16-9-1,1>>^ No dia vinte e quatro desse sétimo mês, o povo de Israel se reuniu para jejuar a fim de mostrar a sua tristeza pelos seus pecados. Eles já haviam se separado de todos os estrangeiros. Em sinal de tristeza, vestiram roupas feitas de pano grosseiro e puseram terra na cabeça. Então se levantaram e começaram a confessar os pecados que eles e os seus antepassados haviam cometido.

[[v16-9-2]]

^<<v16-9-2,2>>^ No dia vinte e quatro desse sétimo mês, o povo de Israel se reuniu para jejuar a fim de mostrar a sua tristeza pelos seus pecados. Eles já haviam se separado de todos os estrangeiros. Em sinal de tristeza, vestiram roupas feitas de pano grosseiro e puseram terra na cabeça. Então se levantaram e começaram a confessar os pecados que eles e os seus antepassados haviam cometido.

[[v16-9-3]]

^<<v16-9-3,3>>^ Durante mais ou menos três horas, a Lei  do Senhor , seu Deus, foi lida para eles. E nas três horas seguintes eles confessaram os seus pecados e adoraram o Senhor .

[[v16-9-4]]

^<<v16-9-4,4>>^ Jesua, Bani, Cadmiel, Sebanias, Buni, Serebias, Bani e Quenani ficaram de pé no estrado dos levitas  e oraram em voz alta ao Senhor , seu Deus.

[[v16-9-5]]

^<<v16-9-5,5>>^ Os levitas Jesua, Cadmiel, Bani, Hasabneias, Serebias, Hodias, Sebanias e Petaías chamaram o povo para adorar a Deus. Eles disseram: "Levantem-se e louvem o Senhor , seu Deus! Louvem a Deus sempre e sempre! Que todos louvem o seu glorioso  nome, embora nenhum louvor humano seja suficiente!"

[[v16-9-6]]

^<<v16-9-6,6>>^ Aí o povo de Israel fez esta oração: "Ó Deus, só tu és o Senhor ! Tu fizeste os céus e as estrelas. Tu fizeste a terra, o mar e tudo o que há neles; tu conservas a todos com vida. Os seres celestiais ajoelham-se e te adoram.

[[v16-9-7]]

^<<v16-9-7,7>>^ "Tu, ó Senhor  Deus, escolheste Abrão e o tiraste de Ur, na Babilônia; tu mudaste o seu nome para Abraão.

[[v16-9-8]]

^<<v16-9-8,8>>^ Viste que ele era fiel a ti e fizeste uma aliança  com ele. Prometeste dar a Abraão a terra dos cananeus, a terra dos heteus e dos amorreus, a terra dos perizeus, dos jebuseus e dos girgaseus, para ser a terra onde os seus descendentes viveriam. Tu cumpriste a tua promessa porque és fiel.

[[v16-9-9]]

^<<v16-9-9,9>>^ "Tu viste como os nossos antepassados sofreram no Egito; ouviste quando eles pediram socorro na beira do mar Vermelho.

[[v16-9-10]]

^<<v16-9-10,10>>^ Tu fizeste milagres maravilhosos contra o rei do Egito, contra os seus oficiais e o povo da sua terra, pois sabias como eles fizeram o teu povo sofrer. Foi assim que ganhaste a fama que tens até hoje.

[[v16-9-11]]

^<<v16-9-11,11>>^ Tu dividiste o mar diante dos nossos antepassados, e assim eles atravessaram em terra seca. Fizeste com que aqueles que os perseguiam se afogassem em águas profundas, como uma pedra que afunda no mar violento.

[[v16-9-12]]

^<<v16-9-12,12>>^ Tu os guiaste com uma nuvem durante o dia e de noite com uma coluna de fogo, para iluminar o caminho por onde deviam ir.

[[v16-9-13]]

^<<v16-9-13,13>>^ Tu desceste do céu no monte Sinai, falaste com o teu povo e lhe deste boas leis  e ensinamentos verdadeiros.

[[v16-9-14]]

^<<v16-9-14,14>>^ Tu lhes disseste que santificassem  o sábado e lhes deste as tuas leis por meio do teu servo  Moisés.

[[v16-9-15]]

^<<v16-9-15,15>>^ Tu lhes deste pão do céu quando estavam com fome e água da rocha quando estavam com sede. Tu mandaste que tomassem posse da terra que havias jurado dar a eles.

[[v16-9-16]]

^<<v16-9-16,16>>^ "Mas os nossos antepassados se tornaram orgulhosos e teimosos e não quiseram obedecer aos teus mandamentos.

[[v16-9-17]]

^<<v16-9-17,17>>^ Eles se recusaram a obedecer. Esqueceram tudo o que fizeste; esqueceram os milagres que havias feito. Em seu orgulho, eles escolheram um chefe que os levaria de volta ao Egito para serem escravos de novo. Mas tu és Deus que perdoa; tu és bondoso e amoroso e demoras a ficar irado . A tua misericórdia é grande, e por isso não os abandonaste.

[[v16-9-18]]

^<<v16-9-18,18>>^ Eles fizeram um touro de metal fundido e disseram que ele era o deus que os havia tirado do Egito. Ó Deus, como eles te insultaram!

[[v16-9-19]]

^<<v16-9-19,19>>^ Mas tu não os abandonaste no deserto, pois a tua misericórdia é grande. Não retiraste nem a nuvem nem o fogo que de dia e de noite mostravam a eles o caminho.

[[v16-9-20]]

^<<v16-9-20,20>>^ Tu lhes deste o teu bom Espírito para lhes ensinar o que deviam fazer; tu os alimentaste com o maná e lhes deste água para matar a sede.

[[v16-9-21]]

^<<v16-9-21,21>>^ Durante quarenta anos no deserto, tu os sustentaste, e nada lhes faltou. As suas roupas não se estragaram, e os seus pés não ficaram inchados.

[[v16-9-22]]

^<<v16-9-22,22>>^ "Tu lhes deste nações e reinos e terras dos povos vizinhos. Os israelitas conquistaram a terra de Hesbom, que era governada por Seom, e a terra de Basã, onde Ogue era o rei.

[[v16-9-23]]

^<<v16-9-23,23>>^ Tu lhes deste tantos descendentes como as estrelas do céu e os trouxeste para viver na terra que havias prometido aos seus antepassados.

[[v16-9-24]]

^<<v16-9-24,24>>^ Eles conquistaram a terra de Canaã; tu derrotaste o povo que morava ali. Deste ao teu povo o poder de fazer o que quisesse com os povos e os reis de Canaã.

[[v16-9-25]]

^<<v16-9-25,25>>^ O teu povo conquistou cidades cercadas de muralhas e tomou terras boas, casas cheias de riquezas, cisternas já escavadas, oliveiras, árvores frutíferas e plantações de uvas. Eles comeram tudo o que quiseram e engordaram; eles aproveitaram todas as boas coisas que lhes deste.

[[v16-9-26]]

^<<v16-9-26,26>>^ "Mas o teu povo se revoltou e te desobedeceu; eles viraram as costas para a tua Lei. Mataram os teus profetas , que os avisaram e lhes disseram que voltassem para ti. O teu povo te insultou muitas vezes.

[[v16-9-27]]

^<<v16-9-27,27>>^ Então deixaste que os inimigos deles os conquistassem e os governassem. Mas no meio da sua aflição eles te pediram socorro, e tu respondeste lá dos céus. Na tua grande misericórdia, tu lhes enviaste líderes que os livraram dos seus inimigos.

[[v16-9-28]]

^<<v16-9-28,28>>^ Quando voltou a paz, o teu povo pecou de novo, e outra vez deixaste que os inimigos deles os conquistassem. E de novo, quando eles se arrependeram e pediram que os salvasses, tu ouviste no céu e, vez após vez, tu os livraste por causa da tua grande misericórdia.

[[v16-9-29]]

^<<v16-9-29,29>>^ Tu os avisaste que deviam obedecer aos teus ensinos; mas no seu orgulho eles rejeitaram os teus mandamentos, pecaram contra a tua lei, embora cumprir a tua lei seja o caminho para a vida. Rebeldes e teimosos, eles se recusaram a obedecer.

[[v16-9-30]]

^<<v16-9-30,30>>^ Ano após ano tu os avisaste, com paciência. Pelo teu Espírito, por meio dos profetas, falaste contra eles, mas o teu povo ficou surdo. Por isso, deixaste que fossem dominados por outras nações.

[[v16-9-31]]

^<<v16-9-31,31>>^ E, mais uma vez, porque a tua misericórdia é grande, tu não os abandonaste, nem os destruíste. Tu és Deus misericordioso e bondoso!

[[v16-9-32]]

^<<v16-9-32,32>>^ "Ó Deus, nosso Deus, como és grande! Como és terrível e poderoso! Tu guardas fielmente as promessas da aliança. Desde o tempo em que os assírios nos dominaram, como temos sofrido! Os nossos reis, as nossas autoridades, os nossos sacerdotes e profetas, os nossos antepassados e todo o nosso povo — todos nós temos sofrido! Lembra das nossas aflições!

[[v16-9-33]]

^<<v16-9-33,33>>^ Tu foste justo em nos castigar; tu tens sido fiel, mesmo quando temos pecado.

[[v16-9-34]]

^<<v16-9-34,34>>^ Os nossos antepassados, os nossos reis, as nossas autoridades e sacerdotes não têm cumprido a tua lei, não têm obedecido aos teus mandamentos e avisos.

[[v16-9-35]]

^<<v16-9-35,35>>^ Com a tua bênção, reis governaram o teu povo, que estava vivendo na terra grande e boa que lhes deste; mas eles não te adoraram, nem se arrependeram das suas más ações.

[[v16-9-36]]

^<<v16-9-36,36>>^ E agora nós somos escravos na terra que nos deste, esta terra boa que nos alimenta.

[[v16-9-37]]

^<<v16-9-37,37>>^ Aquilo que a terra produz vai para os reis que puseste para nos fazer sofrer por causa dos nossos pecados. Eles fazem o que querem conosco e com o nosso gado, e nós estamos profundamente aflitos."

'''

xref:016-neemias/016-neemias-008.adoc#v16-8-0[&#60; Capítulo Anterior] | <<v16-9-0,Topo>> | xref:016-neemias/016-neemias-010.adoc#v16-10-0[Próximo Capítulo &#62;]