include::./index.adoc[]

[[v16-13-0]]
=== Neemias, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-13-1]]

^<<v16-13-1,1>>^ A Lei  de Moisés estava sendo lida em voz alta para o povo. Então chegaram ao trecho que diz que nunca seria permitido que nenhum amonita ou moabita se juntasse ao povo de Deus.

[[v16-13-2]]

^<<v16-13-2,2>>^ Isso porque o povo de Amom e o de Moabe não haviam dado comida nem água aos israelitas na sua viagem quando saíram do Egito. Em vez disso, esses dois povos haviam pago a Balaão para amaldiçoar o povo de Israel. Mas o nosso Deus virou a maldição em bênção.

[[v16-13-3]]

^<<v16-13-3,3>>^ Quando os israelitas ouviram a leitura dessa lei, eles expulsaram os estrangeiros do meio deles.

[[v16-13-4]]

^<<v16-13-4,4>>^ Antes desses acontecimentos, o sacerdote Eliasibe, que era o encarregado dos depósitos do Templo, havia se ligado com Tobias por laços de parentesco.

[[v16-13-5]]

^<<v16-13-5,5>>^ Por isso, havia deixado que Tobias usasse uma sala grande onde antes eram guardadas as ofertas de cereais e de incenso, os objetos usados no Templo, as ofertas para os sacerdotes e a décima parte dos cereais, do vinho e do azeite dados para os levitas , para os músicos e para os guardas do Templo.

[[v16-13-6]]

^<<v16-13-6,6>>^ Porém, quando isso aconteceu, eu não estava em Jerusalém porque, no ano trinta e dois do reinado de Artaxerxes, da Babilônia , eu havia voltado para lá a fim de dar ao rei um relatório. Mas, depois de algum tempo, ele deixou que eu voltasse.

[[v16-13-7]]

^<<v16-13-7,7>>^ Então voltei para Jerusalém e fiquei sabendo do mal que Eliasibe havia feito, deixando que Tobias usasse uma sala do Templo.

[[v16-13-8]]

^<<v16-13-8,8>>^ Eu fiquei tão furioso, que joguei todos os móveis de Tobias para fora da sala.

[[v16-13-9]]

^<<v16-13-9,9>>^ Depois dei ordem para que a sala fosse purificada  e que os objetos do Templo, as ofertas de cereais e o incenso fossem colocados ali de novo.

[[v16-13-10]]

^<<v16-13-10,10>>^ Eu soube também que os músicos do Templo e outros levitas haviam saído de Jerusalém e voltado para as suas fazendas porque o povo não estava dando o suficiente para o sustento deles.

[[v16-13-11]]

^<<v16-13-11,11>>^ Então repreendi as autoridades por deixarem que o Templo ficasse abandonado. Depois trouxe de volta para o Templo os levitas e os músicos e os coloquei de novo nos seus postos.

[[v16-13-12]]

^<<v16-13-12,12>>^ Aí todo o povo de Israel começou de novo a trazer para os depósitos do Templo a décima parte dos cereais, do vinho e do azeite.

[[v16-13-13]]

^<<v16-13-13,13>>^ Eu encarreguei de tomar conta dos depósitos os seguintes homens: o sacerdote Selemias, Zadoque, o escrivão, e um levita chamado Pedaías. E como ajudante deles pus Hanã, filho de Zacur e neto de Matanias. Eu sabia que podia confiar nesses homens e que eles seriam honestos na divisão dos mantimentos com os seus colegas de trabalho.

[[v16-13-14]]

^<<v16-13-14,14>>^ "Ó meu Deus, lembra de todas essas coisas que eu tenho feito pelo teu Templo e pelo seu serviço."

[[v16-13-15]]

^<<v16-13-15,15>>^ Naqueles dias eu vi que em Jerusalém havia gente que no sábado pisava uvas para fazer vinho. Outros, no sábado, carregavam os seus jumentos de cereais, vinho, uvas, figos e outras coisas e levavam para dentro de Jerusalém. Então dei ordem para que não vendessem nada no sábado.

[[v16-13-16]]

^<<v16-13-16,16>>^ Alguns homens da cidade de Tiro que moravam em Jerusalém traziam peixes e todo tipo de mercadorias à cidade para vender ao nosso povo no sábado.

[[v16-13-17]]

^<<v16-13-17,17>>^ Então eu repreendi as autoridades dos judeus e lhes disse: — Vejam só que coisa errada vocês estão fazendo! Vocês estão profanando  o dia do sábado!

[[v16-13-18]]

^<<v16-13-18,18>>^ Foi por isso mesmo que Deus castigou os seus antepassados, deixando que esta cidade fosse destruída. E agora vocês insistem em profanar o sábado, fazendo com que assim Deus fique ainda mais irado  com Israel.

[[v16-13-19]]

^<<v16-13-19,19>>^ Portanto, ordenei que os portões da cidade fossem fechados antes que começasse cada sábado, logo que fosse ficando escuro , e que não fossem abertos de novo até que o sábado terminasse. E coloquei alguns dos meus homens nos portões para que nenhuma carga fosse levada para dentro da cidade no sábado.

[[v16-13-20]]

^<<v16-13-20,20>>^ Uma ou duas vezes, os negociantes que vendiam todo tipo de mercadorias passaram a noite de sexta-feira fora das muralhas da cidade.

[[v16-13-21]]

^<<v16-13-21,21>>^ Mas eu os avisei: — Não adianta vocês passarem a noite do lado de fora das muralhas, esperando pela manhã. Se vocês fizerem isso de novo, eu usarei a força. Daí em diante, eles não voltaram mais no sábado.

[[v16-13-22]]

^<<v16-13-22,22>>^ Eu mandei que os levitas se purificassem e fossem guardar os portões para termos a certeza de que o sábado seria conservado santo. "Ó meu Deus, lembra de mim por isso também e tem piedade de mim por causa do teu grande amor!"

[[v16-13-23]]

^<<v16-13-23,23>>^ Nessa época, descobri também que muitos judeus haviam casado com mulheres de Asdode, de Amom e de Moabe.

[[v16-13-24]]

^<<v16-13-24,24>>^ Metade dos seus filhos falava a língua de Asdode ou outra língua e não sabia falar a língua dos judeus.

[[v16-13-25]]

^<<v16-13-25,25>>^ Eu repreendi aqueles homens e os amaldiçoei; bati neles e arranquei os seus cabelos. E exigi em nome de Deus que fizessem a promessa de que nunca mais nem eles nem os seus filhos casariam com estrangeiras.

[[v16-13-26]]

^<<v16-13-26,26>>^ Eu disse a eles: — Foram mulheres estrangeiras que fizeram o rei Salomão pecar. Ele era mais famoso do que todos os reis das outras nações. Deus o amou e o pôs como rei de todo o povo de Israel, e no entanto ele caiu nesse pecado.

[[v16-13-27]]

^<<v16-13-27,27>>^ Será que nós vamos seguir o exemplo dele e desobedecer ao nosso Deus, casando com mulheres estrangeiras?

[[v16-13-28]]

^<<v16-13-28,28>>^ Joiada era filho de Eliasibe, o Grande Sacerdote . Porém um dos filhos de Joiada havia casado com uma filha de Sambalate, da cidade de Bete-Horom. Por isso, eu expulsei Joiada de Jerusalém.

[[v16-13-29]]

^<<v16-13-29,29>>^ "Ó meu Deus, lembra de como essas pessoas mancharam não somente o ofício de sacerdote como também a aliança  que fizeste com os sacerdotes e com os levitas!"

[[v16-13-30]]

^<<v16-13-30,30>>^ Eu purifiquei o povo de tudo o que era estrangeiro. Fiz regulamentos para os sacerdotes e para os levitas a fim de que cada um soubesse qual era a sua tarefa.

[[v16-13-31]]

^<<v16-13-31,31>>^ Organizei o fornecimento da lenha a ser usada nos sacrifícios , para que fosse trazida no tempo certo. E fiz regulamentos a respeito das ofertas dos primeiros cereais e das primeiras frutas colhidos pelo povo. "Lembra de tudo isso, ó meu Deus, e me abençoa!"

'''

xref:016-neemias/016-neemias-012.adoc#v16-12-0[&#60; Capítulo Anterior] | <<v16-13-0,Topo>> | xref:017-ester/017-ester-001.adoc#v17-1-0[Próximo Capítulo &#62;]