include::./index.adoc[]

[[v16-4-0]]
=== Neemias, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-4-1]]

^<<v16-4-1,1>>^ Quando Sambalate soube que os judeus estavam reconstruindo as muralhas, ficou furioso e começou a caçoar de nós.

[[v16-4-2]]

^<<v16-4-2,2>>^ Diante dos seus companheiros e do exército dos samaritanos , ele disse: — O que é que esses judeus miseráveis estão fazendo? Será que eles pretendem reconstruir a cidade? Será que eles pensam que, oferecendo sacrifícios , poderão acabar o trabalho em um dia? Será que dos montões de entulho e das pedras que foram queimadas eles podem tirar pedras para a construção?

[[v16-4-3]]

^<<v16-4-3,3>>^ Tobias, que era do país de Amom, estava com ele e disse: — Que tipo de muralha eles poderão construir? Até mesmo uma raposa poderia derrubá-la!

[[v16-4-4]]

^<<v16-4-4,4>>^ "Ó nosso Deus, escuta como eles caçoam de nós! Faze que a zombaria caia sobre a cabeça deles mesmos. Que tudo o que eles têm seja roubado, e que eles sejam levados prisioneiros para uma terra estrangeira!

[[v16-4-5]]

^<<v16-4-5,5>>^ Não perdoes o mal que eles fazem e não esqueças os seus pecados, pois insultaram a nós, que estamos construindo."

[[v16-4-6]]

^<<v16-4-6,6>>^ Então continuamos a reconstruir as muralhas, e logo elas já estavam na metade da sua altura total porque o povo estava animado para trabalhar.

[[v16-4-7]]

^<<v16-4-7,7>>^ Sambalate e Tobias e os povos da Arábia, Amom e Asdode ficaram muito zangados quando souberam que nós estávamos continuando o trabalho de reconstrução das muralhas de Jerusalém e que as suas brechas já estavam sendo fechadas.

[[v16-4-8]]

^<<v16-4-8,8>>^ Aí se reuniram e combinaram que viriam juntos atacar Jerusalém e provocar confusão.

[[v16-4-9]]

^<<v16-4-9,9>>^ Mas nós oramos ao nosso Deus e colocamos homens para ficarem de vigia contra eles de dia e de noite.

[[v16-4-10]]

^<<v16-4-10,10>>^ O povo de Judá cantava uma canção assim: "Os carregadores já estão cansados, e ainda há muito entulho para carregar. A construção desta muralha quando vamos terminar?"

[[v16-4-11]]

^<<v16-4-11,11>>^ Os nossos inimigos pensavam que nós não poderíamos vê-los, nem saberíamos o que estava acontecendo até que eles já estivessem quase em cima de nós, nos matando e nos fazendo parar o trabalho.

[[v16-4-12]]

^<<v16-4-12,12>>^ E várias vezes os judeus que moravam entre os nossos inimigos vieram nos avisar dos planos que eles estavam fazendo contra nós.

[[v16-4-13]]

^<<v16-4-13,13>>^ Então eu armei o povo com espadas, lanças e arcos e flechas e os coloquei, por grupos de famílias, atrás da muralha, em todos os lugares onde ela ainda não estava consertada.

[[v16-4-14]]

^<<v16-4-14,14>>^ Eu vi que o povo estava preocupado e por isso disse a eles, e às suas autoridades, e aos seus oficiais: — Não tenham medo dos nossos inimigos. Lembrem como Deus, o Senhor, é grande e terrível e lutem pelos seus patrícios, pelos seus filhos, suas esposas e seus lares.

[[v16-4-15]]

^<<v16-4-15,15>>^ Os nossos inimigos ficaram sabendo que nós havíamos descoberto o que eles estavam planejando e compreenderam que Deus havia atrapalhado os seus planos. Então todos nós voltamos para o nosso trabalho na reconstrução das muralhas.

[[v16-4-16]]

^<<v16-4-16,16>>^ Daí em diante, metade dos homens trabalhava enquanto os outros ficavam de guarda, armados com lanças, escudos , arcos e flechas e armaduras . E as autoridades deram todo o seu apoio às pessoas

[[v16-4-17]]

^<<v16-4-17,17>>^ que estavam reconstruindo a muralha. Cada pessoa carregava materiais de construção numa das mãos e na outra carregava uma arma.

[[v16-4-18]]

^<<v16-4-18,18>>^ E todos os que trabalhavam levavam uma espada na cintura. O vigia, que devia tocar a corneta para dar o alarme, ficava perto de mim.

[[v16-4-19]]

^<<v16-4-19,19>>^ E eu disse ao povo, e aos seus oficiais, e às suas autoridades: — O trabalho é muito espalhado, e por isso nós ficamos muito longe uns dos outros nas muralhas.

[[v16-4-20]]

^<<v16-4-20,20>>^ Se vocês ouvirem a corneta tocando o alarme, reúnam-se em volta de mim. O nosso Deus lutará por nós.

[[v16-4-21]]

^<<v16-4-21,21>>^ E assim, todos os dias, desde o nascer do sol até a hora em que as estrelas apareciam de noite, metade de nós trabalhava nas muralhas enquanto os outros ficavam de guarda, armados com lanças.

[[v16-4-22]]

^<<v16-4-22,22>>^ Nessa mesma época, eu também disse aos encarregados do trabalho que eles e todos os seus ajudantes precisavam passar a noite em Jerusalém, para que assim nós pudéssemos trabalhar de dia e servir como vigias da cidade à noite.

[[v16-4-23]]

^<<v16-4-23,23>>^ Nem eu, nem os meus companheiros, nem nenhum dos meus empregados ou guarda-costas tirávamos as nossas roupas, nem mesmo para dormir. E todos nós estávamos sempre com as nossas armas nas mãos.

'''

xref:016-neemias/016-neemias-003.adoc#v16-3-0[&#60; Capítulo Anterior] | <<v16-4-0,Topo>> | xref:016-neemias/016-neemias-005.adoc#v16-5-0[Próximo Capítulo &#62;]