include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-2-1]]

^<<v16-2-1,1>>^ O que vou contar aconteceu quatro meses mais tarde, no vigésimo ano do reinado de Artaxerxes . Um dia, quando o rei estava jantando, eu peguei vinho e o servi. O rei nunca me havia visto triste

[[v16-2-2]]

^<<v16-2-2,2>>^ e por isso perguntou: — Por que você está triste? Você não está doente; portanto, deve estar se sentindo infeliz. Então eu fiquei com muito medo

[[v16-2-3]]

^<<v16-2-3,3>>^ e respondi: — Que o rei viva para sempre! Como posso deixar de parecer triste, quando a cidade onde os meus antepassados estão sepultados está em ruínas, e os seus portões estão queimados?

[[v16-2-4]]

^<<v16-2-4,4>>^ O rei perguntou: — O que é que você quer? Eu orei ao Deus do céu

[[v16-2-5]]

^<<v16-2-5,5>>^ e depois disse ao rei: — Se o senhor está contente comigo e quiser atender um pedido meu, deixe que eu vá para a terra de Judá a fim de reconstruir a cidade onde os meus antepassados estão sepultados.

[[v16-2-6]]

^<<v16-2-6,6>>^ Aí o rei, tendo a rainha sentada ao seu lado, concordou com o meu pedido. Ele perguntou quanto tempo eu ficaria fora e quando voltaria. E eu disse.

[[v16-2-7]]

^<<v16-2-7,7>>^ Então pedi ao rei um favor: que me desse cartas para os governadores da província  do Eufrates-Oeste , com instruções para que me deixassem passar até chegar à região de Judá.

[[v16-2-8]]

^<<v16-2-8,8>>^ Também pedi uma carta para Asafe, o guarda florestal do rei, mandando que me desse madeira para fazer os portões da fortaleza que protege o Templo e para fazer as muralhas da cidade e a casa onde eu iria morar. E o rei me deu tudo o que pedi, porque Deus estava comigo.

[[v16-2-9]]

^<<v16-2-9,9>>^ O rei mandou que fossem comigo alguns oficiais do exército e uma tropa da cavalaria. Então eu viajei para a província do Eufrates-Oeste e ali entreguei aos governadores as cartas do rei.

[[v16-2-10]]

^<<v16-2-10,10>>^ Mas Sambalate, da cidade de Bete-Horom, e Tobias, um oficial do país de Amom, ficaram muito zangados quando souberam que alguém tinha vindo para ajudar o povo de Israel.

[[v16-2-11]]

^<<v16-2-11,11>>^ Eu cheguei a Jerusalém e durante três dias

[[v16-2-12]]

^<<v16-2-12,12>>^ não contei a ninguém o que pensava fazer pela cidade de acordo com o que Deus havia posto no meu coração. Eu me levantei no meio da noite e saí, junto com alguns dos meus companheiros. Só levei um animal, o jumento que eu montava.

[[v16-2-13]]

^<<v16-2-13,13>>^ Era noite quando eu saí da cidade pelo Portão do Vale, no oeste, e fui para o sul, passando pela Fonte do Dragão, até o Portão do Lixo. Conforme andava, eu ia examinando as muralhas da cidade que haviam sido derrubadas e os portões que haviam sido destruídos pelo fogo.

[[v16-2-14]]

^<<v16-2-14,14>>^ Então virei para o norte e fui para o Portão da Fonte e para a Represa do Rei. Mas o jumento não pôde encontrar lugar para passar pelo entulho.

[[v16-2-15]]

^<<v16-2-15,15>>^ Por isso, fui até o vale do Cedrom e passei por ele, sempre olhando para as muralhas. Então voltei pelo mesmo caminho pelo qual tinha ido e entrei de novo na cidade pelo Portão do Vale.

[[v16-2-16]]

^<<v16-2-16,16>>^ Nenhuma das autoridades da cidade ficou sabendo aonde eu tinha ido, nem o que tinha feito. Até ali, eu não tinha contado nada a nenhum dos judeus — aos sacerdotes, às autoridades, aos oficiais ou a qualquer outra pessoa que iria tomar parte no trabalho.

[[v16-2-17]]

^<<v16-2-17,17>>^ Mas aí eu lhes disse: — Vejam como é difícil a nossa situação! A cidade de Jerusalém está em ruínas, e os seus portões foram destruídos. Vamos construir de novo as muralhas da cidade e acabar com essa vergonha.

[[v16-2-18]]

^<<v16-2-18,18>>^ Então contei a eles como Deus havia me abençoado e me ajudado. E também contei o que o rei me tinha dito. Eles disseram: — Vamos começar a reconstrução! E se aprontaram para começar o trabalho.

[[v16-2-19]]

^<<v16-2-19,19>>^ Porém Sambalate, Tobias e um árabe chamado Gesém souberam do que estávamos fazendo. Eles começaram a rir e a caçoar de nós. E disseram: — O que é que vocês estão fazendo? Vocês vão se revoltar contra o rei?

[[v16-2-20]]

^<<v16-2-20,20>>^ Eu respondi: — O Deus do céu nos dará sucesso. Nós somos servos  dele e vamos começar a construir. Mas vocês não podem ser donos de nenhuma propriedade em Jerusalém, não têm nenhum direito de cidadãos e não têm nenhuma parte nas tradições religiosas do povo de Israel.

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]