include::./index.adoc[]

[[v16-5-0]]
=== Neemias, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-5-1]]

^<<v16-5-1,1>>^ Algum tempo depois, muitas pessoas, tanto homens como mulheres, começaram a reclamar contra os seus patrícios judeus.

[[v16-5-2]]

^<<v16-5-2,2>>^ Alguns diziam: — As nossas famílias são grandes, e precisamos de trigo para nos alimentarmos e continuarmos vivos.

[[v16-5-3]]

^<<v16-5-3,3>>^ Outros diziam: — Para não morrermos de fome, nós tivemos de penhorar os nossos campos, as nossas plantações de uvas e as nossas casas a fim de comprar trigo.

[[v16-5-4]]

^<<v16-5-4,4>>^ E outros, ainda, disseram: — Tivemos de pedir dinheiro emprestado para pagar ao rei os impostos sobre os nossos campos e plantações de uvas.

[[v16-5-5]]

^<<v16-5-5,5>>^ Acontece que nós somos da mesma raça dos nossos patrícios judeus, e os nossos filhos são tão bons como os deles. No entanto, nós temos de fazer com que os nossos filhos trabalhem como escravos. Algumas das nossas filhas já foram vendidas como escravas. Não podemos fazer nada para evitar isso, pois os nossos campos e as nossas plantações de uvas foram tomados de nós.

[[v16-5-6]]

^<<v16-5-6,6>>^ Quando eu, Neemias, ouvi essas queixas, fiquei zangado

[[v16-5-7]]

^<<v16-5-7,7>>^ e resolvi fazer alguma coisa. Repreendi as autoridades do povo e os oficiais e disse: — Vocês estão explorando os seus irmãos! Depois de pensar nisso, eu reuni todo o povo a fim de tratar desse problema

[[v16-5-8]]

^<<v16-5-8,8>>^ e disse: — De acordo com as nossas posses, nós temos comprado dos estrangeiros os nossos patrícios judeus que tiveram de se vender a eles como escravos. E agora vocês, que são judeus, estão forçando os seus próprios patrícios a se venderem a vocês! As autoridades ficaram caladas e não acharam nada para responder.

[[v16-5-9]]

^<<v16-5-9,9>>^ Então eu disse: — O que vocês estão fazendo é errado! Vocês deviam temer a Deus  e fazer o que é direito, em vez de dar aos nossos inimigos, os não judeus, razão para caçoar de nós.

[[v16-5-10]]

^<<v16-5-10,10>>^ Eu, e os meus companheiros, e os homens que trabalham para mim temos emprestado dinheiro e trigo ao povo. E agora vamos perdoar essa dívida.

[[v16-5-11]]

^<<v16-5-11,11>>^ Portanto, vocês também, perdoem todas as dívidas deles — dinheiro, vinho ou azeite. E devolvam agora mesmo os seus campos, as suas plantações de uvas e de oliveiras e as suas casas!

[[v16-5-12]]

^<<v16-5-12,12>>^ As autoridades responderam: — Está bem. Nós vamos fazer o que você está dizendo. Vamos devolver as propriedades e não vamos cobrar as dívidas. Então eu chamei os sacerdotes e fiz as autoridades jurarem que cumpririam essa promessa.

[[v16-5-13]]

^<<v16-5-13,13>>^ Depois tirei a faixa que usava na cintura e a sacudi. E disse: — É assim que Deus vai sacudir qualquer um de vocês que não cumprir a sua promessa. Deus tirará dele a sua casa e tudo o que ele tem e o deixará sem nada. E todos os que estavam ali disseram: — Amém ! Que assim seja! Aí louvaram a Deus, o Senhor . E cumpriram a promessa que haviam feito.

[[v16-5-14]]

^<<v16-5-14,14>>^ Durante os doze anos em que fui governador da terra de Judá, desde o ano vinte do reinado de Artaxerxes até o ano trinta e dois, nem eu nem os meus parentes comemos a comida a que eu tinha direito como governador.

[[v16-5-15]]

^<<v16-5-15,15>>^ Antes de mim, os governadores tinham sido uma carga para o povo e haviam exigido que o povo pagasse quarenta barras de prata por dia a fim de comprar comida e vinho. Até os seus empregados exploravam o povo. Mas eu agi de modo diferente porque temia a Deus .

[[v16-5-16]]

^<<v16-5-16,16>>^ Trabalhei com todas as minhas forças na reconstrução da muralha e não comprei nenhuma propriedade. E todos os meus empregados ajudaram na reconstrução.

[[v16-5-17]]

^<<v16-5-17,17>>^ Também hospedei na minha casa cento e cinquenta judeus e os seus chefes, além de todas as pessoas das nações vizinhas que vinham à minha casa.

[[v16-5-18]]

^<<v16-5-18,18>>^ Todos os dias eu mandava preparar um boi, seis ovelhas das melhores e muitas galinhas. E cada dez dias eu mandava vir uma nova remessa de vinho. Mas eu sabia que o povo tinha de trabalhar no pesado; por isso, não pedi o dinheiro da comida a que eu, como governador, tinha direito.

[[v16-5-19]]

^<<v16-5-19,19>>^ "Ó Deus, eu te peço que leves em conta tudo o que fiz por este povo."

'''

xref:016-neemias/016-neemias-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-neemias/016-neemias-006.adoc#v16-6-0[Próximo Capítulo &#62;]