include::./index.adoc[]

[[v16-6-0]]
=== Neemias, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-6-1]]

^<<v16-6-1,1>>^ Sambalate, Tobias, Gesém e o resto dos nossos inimigos souberam que nós havíamos terminado de reconstruir a muralha e que não havia mais brechas nela, embora ainda não tivéssemos colocado os portões nos seus lugares.

[[v16-6-2]]

^<<v16-6-2,2>>^ Então Sambalate e Gesém me mandaram um recado. Eles queriam que eu fosse me encontrar com eles num dos povoados do vale de Ono. Mas a intenção deles era me fazer algum mal.

[[v16-6-3]]

^<<v16-6-3,3>>^ Aí eu mandei mensageiros a eles com o seguinte recado: — Eu estou fazendo um trabalho importante e não posso descer até aí. Eu não vou deixar este trabalho só para ir falar com vocês.

[[v16-6-4]]

^<<v16-6-4,4>>^ Eles me mandaram o mesmo recado quatro vezes, e eu mandei sempre a mesma resposta.

[[v16-6-5]]

^<<v16-6-5,5>>^ Então Sambalate me mandou o quinto recado, e este veio por escrito. Era uma carta e foi trazida por um dos empregados de Sambalate.

[[v16-6-6]]

^<<v16-6-6,6>>^ A carta, que estava aberta , dizia: "Gesém me disse que entre os povos vizinhos está correndo um boato. Dizem que você e os judeus pretendem fazer uma revolução e que é por isso que estão reconstruindo a muralha. Ele disse também que o seu plano é se tornar o rei deles

[[v16-6-7]]

^<<v16-6-7,7>>^ e que você já arranjou alguns profetas  para dizerem em Jerusalém que você é o rei de Judá. O rei Artaxerxes certamente vai saber disso, e por isso proponho que nós dois nos encontremos para conversar a respeito dessa situação."

[[v16-6-8]]

^<<v16-6-8,8>>^ Eu mandei a seguinte resposta: — Nada do que você está dizendo é verdade. Foi você quem inventou tudo isso.

[[v16-6-9]]

^<<v16-6-9,9>>^ O que eles queriam era nos meter medo para não continuarmos o trabalho. "Agora, ó Deus, aumenta as minhas forças!"

[[v16-6-10]]

^<<v16-6-10,10>>^ Nessa época, Semaías, filho de Delaías e neto de Meetabel, estava proibido de sair de casa, e por isso fui visitá-lo. Ele me disse: — Nós dois precisamos nos esconder juntos no Lugar Santo , no Templo. E vamos fechar as portas porque eles virão matar você. Sim, qualquer noite destas eles virão matá-lo.

[[v16-6-11]]

^<<v16-6-11,11>>^ A isso respondi: — Eu não sou do tipo de homem que foge e se esconde. Você pensa que eu tentaria salvar a minha vida me escondendo no Templo? Eu não vou fazer isso, de jeito nenhum.

[[v16-6-12]]

^<<v16-6-12,12>>^ Quando comecei a pensar nesse assunto, compreendi que Deus não havia falado com Semaías e sim que Tobias e Sambalate haviam pago a ele para me dar aquele conselho.

[[v16-6-13]]

^<<v16-6-13,13>>^ Eles lhe deram dinheiro para me fazer ficar com medo e assim pecar . Aí eles poderiam acabar com o meu bom nome e me humilhar.

[[v16-6-14]]

^<<v16-6-14,14>>^ "Ó meu Deus, lembra do que Tobias e Sambalate fizeram e castiga-os. Lembra também da profetisa Noadias e dos outros profetas que tentaram me fazer ficar com medo."

[[v16-6-15]]

^<<v16-6-15,15>>^ As muralhas foram terminadas no dia vinte e cinco do mês de elul , depois de cinquenta e dois dias de trabalho.

[[v16-6-16]]

^<<v16-6-16,16>>^ Então os nossos inimigos das nações vizinhas souberam disso e ficaram desmoralizados porque todos ficaram sabendo que o trabalho havia sido feito com a ajuda do nosso Deus.

[[v16-6-17]]

^<<v16-6-17,17>>^ Durante esse tempo, as autoridades dos judeus haviam escrito muitas cartas a Tobias e haviam recebido várias cartas dele.

[[v16-6-18]]

^<<v16-6-18,18>>^ Muita gente de Judá estava do lado de Tobias porque ele era genro de um judeu chamado Secanias, filho de Ará. Além disso, o seu filho Joanã havia casado com a filha de Mesulã, filho de Berequias.

[[v16-6-19]]

^<<v16-6-19,19>>^ Na minha frente, falavam das boas coisas que Tobias havia feito e contavam a ele tudo o que eu dizia. E Tobias continuou a me mandar cartas para ver se conseguia me fazer ficar com medo.

'''

xref:016-neemias/016-neemias-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-neemias/016-neemias-007.adoc#v16-7-0[Próximo Capítulo &#62;]