include::./index.adoc[]

[[v16-12-0]]
=== Neemias, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-12-1]]

^<<v16-12-1,1>>^ Esta é a lista dos sacerdotes e levitas  que voltaram do cativeiro  com Zorobabel, filho de Salatiel, e com Josué, o Grande Sacerdote .

[[v16-12-2]]

^<<v16-12-2,2>>^ Sacerdotes: Seraías, Jeremias, Esdras, Amariá, Maluque, Hatus, Secanias, Reum, Meremote, Ido, Ginetoi, Abias, Miamim, Maadias, Bilga, Semaías, Joiaribe, Jedaías, Salu, Amoque, Hilquias e Jedaías. Esses homens foram líderes entre os seus colegas sacerdotes, no tempo de Josué.

[[v16-12-3]]

^<<v16-12-3,3>>^ Sacerdotes: Seraías, Jeremias, Esdras, Amariá, Maluque, Hatus, Secanias, Reum, Meremote, Ido, Ginetoi, Abias, Miamim, Maadias, Bilga, Semaías, Joiaribe, Jedaías, Salu, Amoque, Hilquias e Jedaías.

[[v16-12-4]]

^<<v16-12-4,4>>^ Sacerdotes: Seraías, Jeremias, Esdras, Amariá, Maluque, Hatus, Secanias, Reum, Meremote, Ido, Ginetoi, Abias, Miamim, Maadias, Bilga, Semaías, Joiaribe, Jedaías, Salu, Amoque, Hilquias e Jedaías.

[[v16-12-5]]

^<<v16-12-5,5>>^ Sacerdotes: Seraías, Jeremias, Esdras, Amariá, Maluque, Hatus, Secanias, Reum, Meremote, Ido, Ginetoi, Abias, Miamim, Maadias, Bilga, Semaías, Joiaribe, Jedaías, Salu, Amoque, Hilquias e Jedaías.

[[v16-12-6]]

^<<v16-12-6,6>>^ Sacerdotes: Seraías, Jeremias, Esdras, Amariá, Maluque, Hatus, Secanias, Reum, Meremote, Ido, Ginetoi, Abias, Miamim, Maadias, Bilga, Semaías, Joiaribe, Jedaías, Salu, Amoque, Hilquias e Jedaías.

[[v16-12-7]]

^<<v16-12-7,7>>^ Sacerdotes: Seraías, Jeremias, Esdras, Amariá, Maluque, Hatus, Secanias, Reum, Meremote, Ido, Ginetoi, Abias, Miamim, Maadias, Bilga, Semaías, Joiaribe, Jedaías, Salu, Amoque, Hilquias e Jedaías.

[[v16-12-8]]

^<<v16-12-8,8>>^ Levitas: Estavam encarregados do cântico de hinos de louvor os seguintes: Jesua, Binui, Cadmiel, Serebias, Judá e Matanias.

[[v16-12-9]]

^<<v16-12-9,9>>^ Os seguintes formavam o coro que cantava as respostas: Baquebuquias e Uni e os seus colegas levitas.

[[v16-12-10]]

^<<v16-12-10,10>>^ Josué foi pai de Joiaquim, Joiaquim foi pai de Eliasibe, Eliasibe foi pai de Joiada,

[[v16-12-11]]

^<<v16-12-11,11>>^ Joiada foi pai de Jônatas, e Jônatas foi pai de Jadua.

[[v16-12-12]]

^<<v16-12-12,12>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-13]]

^<<v16-12-13,13>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-14]]

^<<v16-12-14,14>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-15]]

^<<v16-12-15,15>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-16]]

^<<v16-12-16,16>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-17]]

^<<v16-12-17,17>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-18]]

^<<v16-12-18,18>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-19]]

^<<v16-12-19,19>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-20]]

^<<v16-12-20,20>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-21]]

^<<v16-12-21,21>>^ Quando Joiaquim era o Grande Sacerdote , os seguintes sacerdotes eram chefes dos grupos de famílias de sacerdotes:

[[v16-12-22]]

^<<v16-12-22,22>>^ Foi feito um registro dos chefes de famílias de levitas  e das famílias de sacerdotes durante a vida dos seguintes Grandes Sacerdotes: Eliasibe, Joiada, Joanã e Jadua. Esse registro terminou quando Dario era rei da Pérsia.

[[v16-12-23]]

^<<v16-12-23,23>>^ No entanto, os chefes de famílias de levitas foram registrados somente até a época de Joanã, filho de Eliasibe.

[[v16-12-24]]

^<<v16-12-24,24>>^ Os levitas  foram organizados em grupos, que eram dirigidos por Hasabias, Serebias, Jesua, Binui e Cadmiel. O coro estava dividido em dois grupos: um grupo cantava, e o outro respondia. Nos hinos os cantores davam graças a Deus, de acordo com as instruções deixadas pelo rei Davi, homem de Deus.

[[v16-12-25]]

^<<v16-12-25,25>>^ Estavam encarregados de tomar conta dos depósitos que ficavam perto dos portões do Templo os seguintes guardas: Matanias, Baquebuquias, Obadias, Mesulã, Talmom e Acube.

[[v16-12-26]]

^<<v16-12-26,26>>^ Essas pessoas viveram no tempo de Joiaquim, filho de Josué e neto de Jozadaque, e nos dias de Neemias, o governador, e de Esdras, o sacerdote e mestre da Lei .

[[v16-12-27]]

^<<v16-12-27,27>>^ Quando as muralhas da cidade de Jerusalém foram inauguradas, os levitas  foram trazidos de todos os lugares onde estavam morando, para que assim pudessem comemorar a inauguração com hinos de louvor e com música de harpas , de liras  e de pratos musicais.

[[v16-12-28]]

^<<v16-12-28,28>>^ As famílias de cantores levitas se ajuntaram e vieram dos lugares em redor de Jerusalém onde haviam construído as suas casas. Vieram também dos povoados que ficavam ao redor de Netofa

[[v16-12-29]]

^<<v16-12-29,29>>^ e de Bete-Gilgal, Geba e Azmavete.

[[v16-12-30]]

^<<v16-12-30,30>>^ Os sacerdotes e os levitas purificaram-se  a si mesmos e também purificaram o povo, os portões e as muralhas da cidade.

[[v16-12-31]]

^<<v16-12-31,31>>^ Eu, Neemias, mandei que as autoridades de Judá se reunissem em cima da muralha e os organizei em dois grandes grupos para marcharem ao redor da cidade, dando graças a Deus. O primeiro grupo marchava para a direita, em direção ao Portão do Lixo .

'''

xref:016-neemias/016-neemias-011.adoc#v16-11-0[&#60; Capítulo Anterior] | <<v16-12-0,Topo>> | xref:016-neemias/016-neemias-013.adoc#v16-13-0[Próximo Capítulo &#62;]