include::./index.adoc[]

[[v16-7-0]]
=== Neemias, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-7-1]]

^<<v16-7-1,1>>^ Agora as muralhas estavam reconstruídas, e os portões estavam todos colocados nos seus lugares. Foi marcado o trabalho dos guardas do Templo, dos cantores e dos levitas .

[[v16-7-2]]

^<<v16-7-2,2>>^ Para governar a cidade de Jerusalém, eu coloquei dois homens: o meu irmão Hanani e Hananias, o oficial comandante da fortaleza. Hananias era um homem fiel e temia a Deus  mais do que qualquer outro.

[[v16-7-3]]

^<<v16-7-3,3>>^ Eu disse aos dois que só mandassem abrir os portões de Jerusalém quando o sol começasse a esquentar. E que mandassem fechar e trancar os portões antes que os guardas deixassem o serviço, na hora do pôr do sol. Também ordenei que escolhessem guardas entre o povo que morava em Jerusalém. Alguns deles deviam ficar de guarda em certos lugares, e os outros deviam tomar conta da área em frente das suas próprias casas.

[[v16-7-4]]

^<<v16-7-4,4>>^ A cidade de Jerusalém era grande, mas não tinha muitos moradores, e eram poucas as casas que já haviam sido reconstruídas.

[[v16-7-5]]

^<<v16-7-5,5>>^ Deus pôs no meu coração a ideia de reunir todo o povo, e os seus líderes, e as autoridades para verificar os registros das suas famílias. Eu achei o livro de registros do primeiro grupo que havia voltado da Babilônia. São estas as informações que havia no livro:

[[v16-7-6]]

^<<v16-7-6,6>>^ Entre os israelitas que o rei Nabucodonosor, da Babilônia, tinha levado como prisioneiros, havia muitos que eram da província  de Judá. Estes voltaram para Jerusalém e Judá, cada um para a sua própria cidade.

[[v16-7-7]]

^<<v16-7-7,7>>^ Os seus líderes eram Zorobabel, Josué, Neemias, Azarias, Raamias, Naamani, Mordecai, Bilsã, Misperete, Bigvai, Neum e Baaná.

[[v16-7-8]]

^<<v16-7-8,8>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo: Parós: dois mil cento e setenta e dois. Sefatias: trezentos e setenta e dois. Ará: seiscentos e cinquenta e dois. Paate-Moabe (descendentes de Jesua e de Joabe): dois mil oitocentos e dezoito. Elom: mil duzentos e cinquenta e quatro. Zatu: oitocentos e quarenta e cinco. Zacai: setecentos e sessenta. Binui: seiscentos e quarenta e oito. Bebai: seiscentos e vinte e oito. Azgade: dois mil trezentos e vinte e dois. Adonicã: seiscentos e sessenta e sete. Bigvai: dois mil e sessenta e sete. Adim: seiscentos e cinquenta e cinco. Ater (que também era chamado de Ezequias): noventa e oito. Hasum: trezentos e vinte e oito. Besai: trezentos e vinte e quatro. Harife: cento e doze. Gibeão: noventa e cinco.

[[v16-7-9]]

^<<v16-7-9,9>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-10]]

^<<v16-7-10,10>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-11]]

^<<v16-7-11,11>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-12]]

^<<v16-7-12,12>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-13]]

^<<v16-7-13,13>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-14]]

^<<v16-7-14,14>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-15]]

^<<v16-7-15,15>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-16]]

^<<v16-7-16,16>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-17]]

^<<v16-7-17,17>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-18]]

^<<v16-7-18,18>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-19]]

^<<v16-7-19,19>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

[[v16-7-20]]

^<<v16-7-20,20>>^ Esta é a lista dos grupos de famílias do povo de Israel que voltaram da Babilônia, sendo indicados o nome do chefe e o número de pessoas de cada grupo:

'''

xref:016-neemias/016-neemias-006.adoc#v16-6-0[&#60; Capítulo Anterior] | <<v16-7-0,Topo>> | xref:016-neemias/016-neemias-008.adoc#v16-8-0[Próximo Capítulo &#62;]