include::./index.adoc[]

[[v16-8-0]]
=== Neemias, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v16-8-1]]

^<<v16-8-1,1>>^ Já no sétimo mês, todo o povo de Israel estava morando nas suas cidades. No dia primeiro desse mês, todos se reuniram em Jerusalém, na praça em frente ao Portão das Águas. Então pediram a Esdras, o sacerdote e mestre da Lei , que trouxesse o Livro da Lei  que o Senhor  Deus tinha dado ao povo de Israel por meio de Moisés.

[[v16-8-2]]

^<<v16-8-2,2>>^ Esdras levou o livro para o lugar onde o povo estava reunido: os homens, as mulheres e as crianças que já tinham idade para entender.

[[v16-8-3]]

^<<v16-8-3,3>>^ E ali, na praça em frente ao portão, Esdras leu a Lei para o povo, desde o nascer do sol até o meio-dia. E todos ouviram com atenção.

[[v16-8-4]]

^<<v16-8-4,4>>^ Esdras estava de pé num estrado de madeira que havia sido feito para aquela ocasião. À direita de Esdras estavam de pé os seguintes homens: Matitias, Sema, Anaías, Urias, Hilquias e Maaseias. E de pé à sua esquerda estavam: Pedaías, Misael, Malquias, Hasum, Hasbadana, Zacarias e Mesulã.

[[v16-8-5]]

^<<v16-8-5,5>>^ Esdras ficou ali no estrado acima do povo, e todos olhavam para ele. Quando abriu o livro, todos se levantaram,

[[v16-8-6]]

^<<v16-8-6,6>>^ e Esdras disse: — Louvem o Senhor , o grande Deus! Todo o povo levantou os braços e respondeu: — Amém ! Amém! Aí se ajoelharam e, com o rosto encostado na terra, adoraram a Deus, o Senhor .

[[v16-8-7]]

^<<v16-8-7,7>>^ Depois se levantaram e ficaram nos seus lugares. Então os levitas  explicaram a Lei para o povo. Os levitas eram: Jesua, Bani, Serebias, Jamim, Acube, Sabetai, Hodias, Maaseias, Quelita, Azarias, Jozabade, Hanã e Pelaías.

[[v16-8-8]]

^<<v16-8-8,8>>^ Eles iam lendo o Livro da Lei e traduzindo ; e davam explicações para que o povo entendesse o que era lido.

[[v16-8-9]]

^<<v16-8-9,9>>^ Quando ouviram a leitura da Lei, eles ficaram tão comovidos, que começaram a chorar. Então Neemias, o governador, e Esdras, o sacerdote e mestre da Lei, e os levitas que estavam ali explicando a Lei disseram a todo o povo: — Este dia é sagrado para o Senhor , nosso Deus, e por isso vocês não devem se lamentar nem chorar.

[[v16-8-10]]

^<<v16-8-10,10>>^ Vão agora para casa e façam uma festa. Repartam a sua comida e o seu vinho com quem não tiver nada preparado. Este dia é sagrado para o nosso Deus; portanto, não fiquem tristes. A alegria que o Senhor  dá fará com que vocês fiquem fortes.

[[v16-8-11]]

^<<v16-8-11,11>>^ Os levitas foram pelo meio do povo, acalmando-os e dizendo que não ficassem tristes num dia tão santo.

[[v16-8-12]]

^<<v16-8-12,12>>^ Então todos foram para casa, e comeram, e beberam alegremente. E o que eles tinham repartiram com os outros porque entenderam o que havia sido lido para eles.

[[v16-8-13]]

^<<v16-8-13,13>>^ No dia seguinte, os chefes dos grupos de famílias e os sacerdotes e os levitas  foram aonde Esdras estava, a fim de estudarem com ele os ensinamentos da Lei .

[[v16-8-14]]

^<<v16-8-14,14>>^ E acharam escrito nela que o Senhor  Deus havia mandado por meio de Moisés que o povo de Israel morasse em cabanas durante a Festa das Barracas .

[[v16-8-15]]

^<<v16-8-15,15>>^ Então, em toda a cidade de Jerusalém e em todas as outras cidades e povoados, mandaram avisar o seguinte: — Saiam para os morros e tragam galhos de pinheiros, oliveiras, murtas , palmeiras e outras árvores, para fazer cabanas, conforme está escrito na Lei.

[[v16-8-16]]

^<<v16-8-16,16>>^ Então todo o povo saiu e trouxe galhos de árvores. Em seguida eles construíram cabanas no terraço das suas casas, nos seus quintais, nos pátios do Templo, na praça do Portão das Águas e na praça do Portão de Efraim.

[[v16-8-17]]

^<<v16-8-17,17>>^ Todos os que haviam voltado do cativeiro  construíram cabanas e moraram nelas. Desde o tempo de Josué, filho de Num, esta era a primeira vez que faziam isso, e todos estavam muito alegres.

[[v16-8-18]]

^<<v16-8-18,18>>^ Todos os dias, desde o primeiro até o último dia da festa, foi lida uma parte da Lei de Deus. Eles festejaram durante sete dias, e no oitavo dia houve uma reunião solene para terminar a festa, como mandava a Lei.

'''

xref:016-neemias/016-neemias-007.adoc#v16-7-0[&#60; Capítulo Anterior] | <<v16-8-0,Topo>> | xref:016-neemias/016-neemias-009.adoc#v16-9-0[Próximo Capítulo &#62;]