include::./index.adoc[]

[[v4-17-0]]
=== Números, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-17-1]]

^<<v4-17-1,1>>^ O Senhor  Deus disse a Moisés:

[[v4-17-2]]

^<<v4-17-2,2>>^ — Diga aos israelitas que cada um dos chefes de tribo  lhe traga um bastão; serão doze bastões ao todo. Escreva o nome de cada chefe no seu próprio bastão

[[v4-17-3]]

^<<v4-17-3,3>>^ e depois escreva o nome de Arão no bastão que representa a tribo de Levi. Haverá um bastão para cada chefe de tribo.

[[v4-17-4]]

^<<v4-17-4,4>>^ Você colocará os bastões na Tenda Sagrada , em frente da arca da aliança , onde eu me encontro com vocês.

[[v4-17-5]]

^<<v4-17-5,5>>^ Aí o bastão do homem que eu escolher vai brotar. Assim farei com que parem as reclamações que esses israelitas fazem contra mim.

[[v4-17-6]]

^<<v4-17-6,6>>^ Então Moisés falou com os israelitas, e cada um dos seus chefes lhe deu um bastão, um para cada tribo, doze ao todo. E entre os bastões estava aquele que tinha o nome de Arão.

[[v4-17-7]]

^<<v4-17-7,7>>^ Moisés pôs os bastões na Tenda, em frente da arca da aliança de Deus, o Senhor .

[[v4-17-8]]

^<<v4-17-8,8>>^ No dia seguinte Moisés entrou na Tenda e viu que o bastão com o nome de Arão, que representava a tribo de Levi, havia brotado. E tinha brotos, flores e amêndoas maduras.

[[v4-17-9]]

^<<v4-17-9,9>>^ Aí Moisés tirou da presença do Senhor  todos os bastões e levou aos israelitas. Eles viram o que havia acontecido, e cada chefe pegou o seu bastão.

[[v4-17-10]]

^<<v4-17-10,10>>^ O Senhor  Deus disse a Moisés: — Ponha de novo o bastão com o nome de Arão em frente da arca da aliança. Ele ficará ali como um aviso para os israelitas rebeldes. Assim, eles vão parar de reclamar contra mim e não serão mortos.

[[v4-17-11]]

^<<v4-17-11,11>>^ E Moisés fez como o Senhor  havia mandado.

[[v4-17-12]]

^<<v4-17-12,12>>^ Aí o povo de Israel disse a Moisés: — Estamos perdidos! Vamos morrer! Sim, todos nós vamos morrer!

[[v4-17-13]]

^<<v4-17-13,13>>^ Aquele que chegar perto da arca do Senhor  morrerá! É, sim, todos nós vamos morrer!

'''

xref:004-numeros/004-numeros-016.adoc#v4-16-0[&#60; Capítulo Anterior] | <<v4-17-0,Topo>> | xref:004-numeros/004-numeros-018.adoc#v4-18-0[Próximo Capítulo &#62;]