include::./index.adoc[]

[[v4-29-0]]
=== Números, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-29-1]]

^<<v4-29-1,1>>^ O Senhor  deu a Moisés as seguintes ordens para o povo de Israel: — No dia primeiro do sétimo mês vocês se reunirão para adorar o Senhor , e ninguém trabalhará. Nesse dia as trombetas tocarão.

[[v4-29-2]]

^<<v4-29-2,2>>^ Ofereçam a Deus, o Senhor , um sacrifício  que será completamente queimado, que tem um cheiro agradável a ele. Esse sacrifício será de um touro novo, um carneiro e sete carneirinhos de um ano, todos sem defeito.

[[v4-29-3]]

^<<v4-29-3,3>>^ Com cada touro novo, ofereçam três quilos da melhor farinha misturada com azeite. Com cada carneiro, ofereçam dois quilos de farinha misturada com azeite

[[v4-29-4]]

^<<v4-29-4,4>>^ e, com cada carneirinho, um quilo.

[[v4-29-5]]

^<<v4-29-5,5>>^ Ofereçam a Deus também um bode como sacrifício para tirar os pecados do povo.

[[v4-29-6]]

^<<v4-29-6,6>>^ Tragam isso, além da oferta que é completamente queimada em sacrifício no primeiro dia do mês, junto com a sua oferta de cereais, e além da oferta que é completamente queimada todos os dias, junto com a oferta de cereais e a oferta de vinho que a acompanha. Essas ofertas de alimento têm um cheiro agradável ao Senhor .

[[v4-29-7]]

^<<v4-29-7,7>>^ — No dia dez do sétimo mês vocês se reunirão para adorar a Deus. Nesse dia não comam nada e não trabalhem.

[[v4-29-8]]

^<<v4-29-8,8>>^ Deem a Deus, o Senhor , uma oferta que será completamente queimada em sacrifício  e que tem um cheiro agradável a ele. Esse sacrifício será de um touro novo, um carneiro e sete carneirinhos de um ano, todos sem defeito.

[[v4-29-9]]

^<<v4-29-9,9>>^ Com cada touro novo, ofereçam três quilos da melhor farinha misturada com azeite. Com cada carneiro, ofereçam dois quilos de farinha misturada com azeite

[[v4-29-10]]

^<<v4-29-10,10>>^ e, com cada carneirinho, um quilo.

[[v4-29-11]]

^<<v4-29-11,11>>^ Ofereçam também um bode como sacrifício para tirar os pecados, além do bode que é oferecido para purificar  o povo e além do sacrifício que é queimado e que é oferecido todos os dias, junto com a oferta de cereais e a oferta de vinho que o acompanha.

[[v4-29-12]]

^<<v4-29-12,12>>^ — No dia quinze do sétimo mês vocês se reunirão para adorar a Deus. Essa festa em honra do Senhor  Deus deverá durar sete dias.

[[v4-29-13]]

^<<v4-29-13,13>>^ No primeiro dia da festa tragam ao Senhor  uma oferta de alimento que tem um cheiro agradável a ele. Essa oferta será de treze touros novos, dois carneiros e catorze carneirinhos de um ano, todos sem defeito.

[[v4-29-14]]

^<<v4-29-14,14>>^ Com cada touro novo, ofereçam três quilos da melhor farinha misturada com azeite. Com cada carneiro, ofereçam dois quilos de farinha misturada com azeite

[[v4-29-15]]

^<<v4-29-15,15>>^ e, com cada carneirinho, um quilo, junto com as ofertas de vinho que acompanham essa oferta.

[[v4-29-16]]

^<<v4-29-16,16>>^ Ofereçam também um bode como sacrifício  para tirar os pecados do povo. Ofereçam isso, além do sacrifício que é completamente queimado todos os dias, junto com a oferta de cereais e a oferta de vinho que o acompanha.

[[v4-29-17]]

^<<v4-29-17,17>>^ — No segundo dia ofereçam doze touros novos, dois carneiros e catorze carneirinhos de um ano, todos sem defeito.

[[v4-29-18]]

^<<v4-29-18,18>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-19]]

^<<v4-29-19,19>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-20]]

^<<v4-29-20,20>>^ — No terceiro dia ofereçam onze touros novos, dois carneiros e catorze carneirinhos de um ano, todos sem defeito.

[[v4-29-21]]

^<<v4-29-21,21>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-22]]

^<<v4-29-22,22>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-23]]

^<<v4-29-23,23>>^ — No quarto dia ofereçam dez touros novos, dois carneiros e catorze carneirinhos de um ano, todos sem defeito.

[[v4-29-24]]

^<<v4-29-24,24>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-25]]

^<<v4-29-25,25>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-26]]

^<<v4-29-26,26>>^ — No quinto dia ofereçam nove touros novos, dois carneiros e catorze carneirinhos de um ano, todos sem defeito.

[[v4-29-27]]

^<<v4-29-27,27>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-28]]

^<<v4-29-28,28>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-29]]

^<<v4-29-29,29>>^ — No sexto dia ofereçam oito touros novos, dois carneiros e catorze carneirinhos de um ano, todos sem defeito.

[[v4-29-30]]

^<<v4-29-30,30>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-31]]

^<<v4-29-31,31>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

[[v4-29-32]]

^<<v4-29-32,32>>^ — No sétimo dia ofereçam sete touros novos, dois carneiros e catorze carneirinhos de um ano, todos sem defeito.

[[v4-29-33]]

^<<v4-29-33,33>>^ Junto com eles, deem também as outras ofertas que são exigidas para o primeiro dia.

'''

xref:004-numeros/004-numeros-028.adoc#v4-28-0[&#60; Capítulo Anterior] | <<v4-29-0,Topo>> | xref:004-numeros/004-numeros-030.adoc#v4-30-0[Próximo Capítulo &#62;]