include::./index.adoc[]

[[v4-6-0]]
=== Números, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-6-1]]

^<<v4-6-1,1>>^ O Senhor  Deus disse a Moisés:

[[v4-6-2]]

^<<v4-6-2,2>>^ — Fale com os israelitas e diga o seguinte: qualquer homem ou mulher que fizer uma promessa especial de ser nazireu  e dedicar-se ao serviço do Senhor  Deus,

[[v4-6-3]]

^<<v4-6-3,3>>^ não deverá beber vinho nem cerveja. Não deverá beber nenhum tipo de vinho, nem qualquer outra bebida feita de suco de uvas; não comerá uvas frescas nem passas.

[[v4-6-4]]

^<<v4-6-4,4>>^ Enquanto for nazireu, não comerá nada que venha da parreira , nem mesmo as sementes ou as cascas das uvas.

[[v4-6-5]]

^<<v4-6-5,5>>^ — Durante todo o tempo do seu voto de nazireu, não deverá cortar o cabelo, nem fazer a barba. Até acabar o tempo que ele separou para se dedicar ao serviço de Deus, ele se dedicará somente ao Senhor  e deixará crescer completamente o cabelo.

[[v4-6-6]]

^<<v4-6-6,6>>^ O seu cabelo é um sinal da sua dedicação ao serviço de Deus. Por isso ele não deve se tornar impuro , chegando perto de algum morto, mesmo que seja o corpo do seu pai, ou da sua mãe, ou do seu irmão, ou da sua irmã.

[[v4-6-7]]

^<<v4-6-7,7>>^ O seu cabelo é um sinal da sua dedicação ao serviço de Deus. Por isso ele não deve se tornar impuro , chegando perto de algum morto, mesmo que seja o corpo do seu pai, ou da sua mãe, ou do seu irmão, ou da sua irmã.

[[v4-6-8]]

^<<v4-6-8,8>>^ Enquanto for nazireu, ele está separado para o serviço de Deus, o Senhor .

[[v4-6-9]]

^<<v4-6-9,9>>^ — Se alguém morrer de repente perto dele e fizer com que o seu cabelo de nazireu fique impuro, então sete dias depois ele deverá rapar a cabeça e fazer a barba e assim ficará puro.

[[v4-6-10]]

^<<v4-6-10,10>>^ No oitavo dia deverá trazer duas rolas ou dois pombinhos para o sacerdote na entrada da Tenda Sagrada .

[[v4-6-11]]

^<<v4-6-11,11>>^ O sacerdote apresentará um deles como oferta para tirar pecados e o outro como oferta que vai ser completamente queimada, para conseguir o perdão do pecado que cometeu quando chegou perto do morto. Naquele mesmo dia o nazireu dedicará de novo o seu cabelo.

[[v4-6-12]]

^<<v4-6-12,12>>^ Então dedicará de novo ao serviço de Deus, o Senhor , o seu tempo como nazireu. Esse tempo em que o seu cabelo se tornou impuro não será contado. E, como oferta para tirar a culpa, ele trará um carneirinho de um ano.

[[v4-6-13]]

^<<v4-6-13,13>>^ — A lei  para o nazireu, quando chegar o fim do tempo da sua dedicação ao serviço de Deus, será esta: ele irá até a porta da Tenda

[[v4-6-14]]

^<<v4-6-14,14>>^ e entregará a Deus, o Senhor , três animais sem defeito, isto é, um carneirinho de um ano como sacrifício  que vai ser completamente queimado, uma ovelhinha de um ano como sacrifício para tirar pecados e um carneiro como oferta de paz.

[[v4-6-15]]

^<<v4-6-15,15>>^ Ele também oferecerá uma cesta de pães  feitos sem fermento, isto é, pães grandes de farinha misturada com azeite e pães pequenos e achatados, com um pouco de azeite passado por cima; e também apresentará as ofertas de cereais e as ofertas de vinho.

[[v4-6-16]]

^<<v4-6-16,16>>^ — O sacerdote apresentará tudo isso diante de Deus, o Senhor , e oferecerá o seu sacrifício para tirar pecados e a oferta que será completamente queimada.

[[v4-6-17]]

^<<v4-6-17,17>>^ Ele apresentará ao Senhor  o carneiro como oferta de paz e também oferecerá a cesta de pães feitos sem fermento. Ele dará ainda as ofertas de cereais e as ofertas de vinho.

[[v4-6-18]]

^<<v4-6-18,18>>^ Na porta da Tenda o nazireu rapará a cabeça, pegará o cabelo e o colocará no fogo onde está sendo queimada a oferta de paz.

[[v4-6-19]]

^<<v4-6-19,19>>^ — Então, depois que o quarto dianteiro do carneiro estiver assado, o sacerdote o pegará e colocará nas mãos do nazireu, junto com dois pães tirados da cesta, um grande e um pequeno (Isso será feito depois que o nazireu rapar a cabeça.).

[[v4-6-20]]

^<<v4-6-20,20>>^ Depois o sacerdote apresentará essas coisas como uma oferta especial a Deus, o Senhor . São uma oferta sagrada para o sacerdote junto com o peito e a coxa do carneiro, que, pela lei, pertencem ao sacerdote. Depois disso o nazireu poderá beber vinho.

[[v4-6-21]]

^<<v4-6-21,21>>^ — Essa é a lei para quem faz o voto de dedicar-se como nazireu ao serviço de Deus, o Senhor . Porém, se um nazireu prometer uma oferta além do que o seu voto de nazireu exige, então deverá cumprir o que prometeu.

[[v4-6-22]]

^<<v4-6-22,22>>^ O Senhor  Deus disse a Moisés:

[[v4-6-23]]

^<<v4-6-23,23>>^ — Fale com Arão e com os seus filhos e diga-lhes que abençoem o povo de Israel do seguinte modo:

[[v4-6-24]]

^<<v4-6-24,24>>^ "Que o Senhor  os abençoe e os guarde;

[[v4-6-25]]

^<<v4-6-25,25>>^ que o Senhor  os trate com bondade e misericórdia;

[[v4-6-26]]

^<<v4-6-26,26>>^ que o Senhor  olhe para vocês com amor e lhes dê a paz."

'''

xref:004-numeros/004-numeros-005.adoc#v4-5-0[&#60; Capítulo Anterior] | <<v4-6-0,Topo>> | xref:004-numeros/004-numeros-007.adoc#v4-7-0[Próximo Capítulo &#62;]