include::./index.adoc[]

[[v4-12-0]]
=== Números, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-12-1]]

^<<v4-12-1,1>>^ Moisés havia casado com uma mulher da Etiópia, e Míriam e Arão começaram a criticá-lo por causa disso.

[[v4-12-2]]

^<<v4-12-2,2>>^ Eles disseram: — Será que o Senhor  tem falado somente por meio de Moisés? Será que não tem falado também por meio de nós? E o Senhor  ouviu o que eles disseram

[[v4-12-3]]

^<<v4-12-3,3>>^ (Moisés era um homem humilde, o mais humilde do mundo.).

[[v4-12-4]]

^<<v4-12-4,4>>^ Logo em seguida o Senhor  disse a Moisés, a Arão e a Míriam: — Vocês três aí, vão para a Tenda Sagrada . Eles foram,

[[v4-12-5]]

^<<v4-12-5,5>>^ e o Senhor  desceu na coluna de nuvem e ficou na entrada da Tenda. Depois chamou Arão e Míriam e, quando eles chegaram,

[[v4-12-6]]

^<<v4-12-6,6>>^ Deus disse: — Agora escutem o que vou dizer. Quando há profetas  entre vocês, eu apareço a eles em visões e falo com eles em sonhos.

[[v4-12-7]]

^<<v4-12-7,7>>^ Com o meu servo  Moisés é diferente, pois eu o coloquei como responsável por todo o meu povo.

[[v4-12-8]]

^<<v4-12-8,8>>^ Pois eu falo com ele face a face, claramente, e não por meio de comparações; ele até já viu a minha forma! Como é que vocês se atrevem a falar contra o meu servo Moisés?

[[v4-12-9]]

^<<v4-12-9,9>>^ E aí o Senhor  Deus foi embora muito irado  com eles.

[[v4-12-10]]

^<<v4-12-10,10>>^ Assim que Deus saiu, a nuvem que estava sobre a Tenda desapareceu. No mesmo instante Míriam foi atacada por uma terrível doença da pele, que ficou branca como a neve. Arão olhou para Míriam e viu que, de fato, ela estava atacada por aquela doença.

[[v4-12-11]]

^<<v4-12-11,11>>^ Aí Arão disse a Moisés: — Por favor, chefe, eu lhe peço que não nos faça sofrer o castigo por causa desse pecado que cometemos num momento de loucura.

[[v4-12-12]]

^<<v4-12-12,12>>^ Não deixe que Míriam seja como um aborto que nasce com metade do corpo destruído.

[[v4-12-13]]

^<<v4-12-13,13>>^ Então Moisés orou assim a Deus, o Senhor : — Ó Deus, eu te peço que a cures!

[[v4-12-14]]

^<<v4-12-14,14>>^ E o Senhor  respondeu a Moisés: — Se o pai de Míriam tivesse cuspido no rosto dela, ela teria ficado humilhada durante sete dias. Então que ela seja expulsa do acampamento e fique lá fora sete dias; depois será trazida de volta.

[[v4-12-15]]

^<<v4-12-15,15>>^ Assim, Míriam ficou sete dias fora do acampamento. E o povo não partiu dali enquanto ela não foi trazida de novo para o acampamento.

[[v4-12-16]]

^<<v4-12-16,16>>^ Depois disso, o povo saiu de Hazerote e acampou no deserto de Parã.

'''

xref:004-numeros/004-numeros-011.adoc#v4-11-0[&#60; Capítulo Anterior] | <<v4-12-0,Topo>> | xref:004-numeros/004-numeros-013.adoc#v4-13-0[Próximo Capítulo &#62;]