include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-16-1]]

^<<v4-16-1,1>>^ Corá, filho de Isar, do grupo de famílias levitas  de Coate, teve o atrevimento de se revoltar contra Moisés. Ele se juntou com três homens da tribo  de Rúben. Dois deles eram filhos de Eliabe e se chamavam Datã e Abirão; o outro era Om, filho de Pelete. E Corá também chamou mais duzentos e cinquenta israelitas de fama, que eram líderes escolhidos pelo povo.

[[v4-16-2]]

^<<v4-16-2,2>>^ Corá, filho de Isar, do grupo de famílias levitas  de Coate, teve o atrevimento de se revoltar contra Moisés. Ele se juntou com três homens da tribo  de Rúben. Dois deles eram filhos de Eliabe e se chamavam Datã e Abirão; o outro era Om, filho de Pelete. E Corá também chamou mais duzentos e cinquenta israelitas de fama, que eram líderes escolhidos pelo povo.

[[v4-16-3]]

^<<v4-16-3,3>>^ Eles foram juntos falar com Moisés e Arão e disseram: — Agora chega! Todo o povo pertence a Deus, o Senhor . Cada um deles é de Deus, e o Senhor  está no meio deles. Então por que vocês querem mandar no povo de Deus?

[[v4-16-4]]

^<<v4-16-4,4>>^ Quando Moisés ouviu isso, ajoelhou-se, encostou o rosto no chão

[[v4-16-5]]

^<<v4-16-5,5>>^ e disse o seguinte a Corá e a todos os seus seguidores: — Amanhã cedo o Senhor  Deus nos mostrará quem é dele e quem foi separado para o seu serviço. Deus fará com que chegue até o seu altar aquele a quem ele escolheu.

[[v4-16-6]]

^<<v4-16-6,6>>^ Amanhã cedo vocês e os seus seguidores pegarão os queimadores de incenso, colocarão brasas e incenso neles e os levarão para o altar. Então veremos qual de nós o Senhor  escolheu. E agora chega, levitas!

[[v4-16-7]]

^<<v4-16-7,7>>^ Amanhã cedo vocês e os seus seguidores pegarão os queimadores de incenso, colocarão brasas e incenso neles e os levarão para o altar. Então veremos qual de nós o Senhor  escolheu. E agora chega, levitas!

[[v4-16-8]]

^<<v4-16-8,8>>^ Moisés disse também a Corá: — Agora escutem, levitas!

[[v4-16-9]]

^<<v4-16-9,9>>^ O Deus de Israel os separou do resto do povo para poderem chegar perto dele, para fazerem o seu serviço na Tenda  do Senhor  e para realizarem as cerimônias em favor do povo. Será que isso não basta para vocês?

[[v4-16-10]]

^<<v4-16-10,10>>^ Deus deu a você e a todos os outros levitas esse privilégio, e agora vocês estão querendo também ser sacerdotes?

[[v4-16-11]]

^<<v4-16-11,11>>^ Quando vocês reclamam contra Arão, na verdade é contra o Senhor  que você e os seus seguidores estão se revoltando.

[[v4-16-12]]

^<<v4-16-12,12>>^ Então Moisés mandou chamar Datã e Abirão, filhos de Eliabe, mas eles responderam aos mensageiros: — Nós não vamos!

[[v4-16-13]]

^<<v4-16-13,13>>^ Será que não basta você nos ter tirado de uma terra boa e rica a fim de nos fazer morrer neste deserto? E além disso ainda quer mandar em nós?

[[v4-16-14]]

^<<v4-16-14,14>>^ Na verdade você não nos trouxe para uma terra boa e rica, nem nos deu campos e plantações de uvas para serem nossa propriedade; e ainda por cima está querendo nos enganar. Nós não vamos!

[[v4-16-15]]

^<<v4-16-15,15>>^ Então Moisés ficou muito zangado e disse a Deus, o Senhor : — Não aceites as ofertas desses homens. Eu nunca prejudiquei a nenhum deles, nem tirei deles nem mesmo um jumento!

[[v4-16-16]]

^<<v4-16-16,16>>^ Aí Moisés disse a Corá: — Amanhã você e os seus duzentos e cinquenta seguidores venham até a Tenda Sagrada. Arão também estará ali.

[[v4-16-17]]

^<<v4-16-17,17>>^ Cada um de vocês pegará o seu queimador de incenso, colocará incenso nele e o levará até o altar.

[[v4-16-18]]

^<<v4-16-18,18>>^ Assim, cada homem pegou o seu queimador de incenso, pôs brasas e incenso nele, e todos ficaram na entrada da Tenda Sagrada com Moisés e Arão.

[[v4-16-19]]

^<<v4-16-19,19>>^ Então Corá reuniu todo o povo, e eles ficaram diante de Moisés e Arão na entrada da Tenda. De repente, a glória  do Senhor  apareceu a todo o povo,

[[v4-16-20]]

^<<v4-16-20,20>>^ e o Senhor  disse a Moisés e a Arão:

[[v4-16-21]]

^<<v4-16-21,21>>^ — Saiam do meio dessa gente, pois eu vou acabar com eles agora mesmo.

[[v4-16-22]]

^<<v4-16-22,22>>^ Mas Moisés e Arão se ajoelharam, encostaram o rosto no chão e disseram: — Ó Deus, tu dás vida a todos. Será que por causa do pecado de uma só pessoa vais ficar irado  com todo o povo?

[[v4-16-23]]

^<<v4-16-23,23>>^ Então o Senhor  respondeu a Moisés:

[[v4-16-24]]

^<<v4-16-24,24>>^ — Diga ao povo que saia de perto das barracas de Corá, Datã e Abirão.

[[v4-16-25]]

^<<v4-16-25,25>>^ Aí Moisés saiu e, junto com os líderes do povo, foi para onde estavam Datã e Abirão.

[[v4-16-26]]

^<<v4-16-26,26>>^ E Moisés disse ao povo: — Afastem-se das barracas desses homens maus e não toquem em nada que seja deles; se não, vocês também serão destruídos por causa dos pecados deles.

[[v4-16-27]]

^<<v4-16-27,27>>^ Aí o povo se afastou das barracas de Corá, Datã e Abirão. Datã e Abirão saíram e ficaram na entrada da sua barraca, com as suas mulheres e filhos.

[[v4-16-28]]

^<<v4-16-28,28>>^ Então Moisés disse ao povo: — Eu vou dizer como vocês vão ficar sabendo que não fui eu quem resolveu fazer tudo isso. Fiz todas essas coisas porque o Senhor  mandou.

[[v4-16-29]]

^<<v4-16-29,29>>^ Se estes homens tiverem morte natural como todos os outros, sem nenhum castigo de Deus, então o Senhor  não me enviou.

[[v4-16-30]]

^<<v4-16-30,30>>^ Mas, se ele fizer acontecer alguma coisa fora do comum, e se a terra se abrir e engolir essa gente com tudo o que eles têm, e eles descerem vivos para o mundo dos mortos , vocês ficarão sabendo que estes homens rejeitaram o Senhor .

[[v4-16-31]]

^<<v4-16-31,31>>^ E aconteceu que, assim que Moisés acabou de falar, a terra se abriu debaixo deles

[[v4-16-32]]

^<<v4-16-32,32>>^ e os engoliu com as suas famílias, junto com todos os seguidores de Corá e tudo o que eles tinham.

[[v4-16-33]]

^<<v4-16-33,33>>^ Assim, desceram vivos para o mundo dos mortos, eles e tudo o que possuíam. A terra os cobriu, e eles desapareceram.

[[v4-16-34]]

^<<v4-16-34,34>>^ Ao ouvirem os gritos deles, todos os israelitas que estavam ali saíram correndo e gritando: — A terra vai engolir a gente também!

[[v4-16-35]]

^<<v4-16-35,35>>^ Então o Senhor  enviou fogo e matou os duzentos e cinquenta homens que haviam oferecido incenso.

[[v4-16-36]]

^<<v4-16-36,36>>^ Aí o Senhor  Deus disse a Moisés:

[[v4-16-37]]

^<<v4-16-37,37>>^ — Diga a Eleazar, filho do sacerdote Arão, que pegue os queimadores de incenso do meio dos restos do incêndio e espalhe para longe as brasas que ainda estiverem neles, pois os queimadores de incenso são sagrados.

[[v4-16-38]]

^<<v4-16-38,38>>^ Eles ficaram sagrados quando foram oferecidos no altar do Senhor . Portanto, pegue os queimadores de incenso desses homens que foram mortos por causa dos seus pecados e deles faça folhas finas de metal. E com essas folhas prepare uma cobertura para o altar. Isso será um aviso para o povo de Israel.

[[v4-16-39]]

^<<v4-16-39,39>>^ Então o sacerdote Eleazar pegou os queimadores de incenso de metal que os homens que tinham sido mortos haviam trazido e mandou que deles fossem feitas folhas de metal para cobrir o altar.

[[v4-16-40]]

^<<v4-16-40,40>>^ Conforme o Senhor  tinha dito a Moisés, isso ficou sendo um aviso para os israelitas a fim de que nenhuma pessoa que não seja descendente de Arão venha a queimar incenso diante do Senhor  e seja castigada, como aconteceu com Corá e com os seus seguidores.

[[v4-16-41]]

^<<v4-16-41,41>>^ Mas no dia seguinte todos os israelitas começaram a reclamar contra Moisés e Arão, dizendo assim: — Vocês mataram o povo de Deus, o Senhor !

[[v4-16-42]]

^<<v4-16-42,42>>^ Depois que todos se reuniram para protestar contra Moisés e Arão, eles se viraram para a Tenda Sagrada  e viram que a nuvem a estava cobrindo. Então a glória  do Senhor  apareceu.

[[v4-16-43]]

^<<v4-16-43,43>>^ Moisés e Arão foram até a frente da Tenda,

[[v4-16-44]]

^<<v4-16-44,44>>^ e o Senhor  disse a Moisés:

[[v4-16-45]]

^<<v4-16-45,45>>^ — Saiam do meio desse povo, pois vou destruí-lo agora mesmo! Aí Moisés e Arão se ajoelharam e encostaram o rosto no chão.

[[v4-16-46]]

^<<v4-16-46,46>>^ E Moisés disse a Arão: — Pegue o seu queimador de incenso, ponha nele algumas brasas do altar e jogue incenso em cima delas. E vá depressa até o lugar onde o povo está e ofereça o sacrifício  para conseguir o perdão dos pecados deles. Depressa! A ira  do Senhor  apareceu, e já começou a epidemia!

[[v4-16-47]]

^<<v4-16-47,47>>^ Então Arão pegou o queimador de incenso, conforme Moisés havia mandado, e correu para o meio do povo. Quando viu que a epidemia já havia começado, Arão jogou o incenso nas brasas e ofereceu o sacrifício para conseguir o perdão dos pecados do povo.

[[v4-16-48]]

^<<v4-16-48,48>>^ Com isso a epidemia parou, e Arão ficou de pé entre os vivos e os mortos.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]