include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-24-1]]

^<<v4-24-1,1>>^ Desta vez Balaão viu que o Senhor  queria mesmo que ele abençoasse o povo de Israel. Por isso não foi, como antes, procurar sinais para saber qual era a vontade de Deus. Pelo contrário, ele se virou para o deserto

[[v4-24-2]]

^<<v4-24-2,2>>^ e viu o povo de Israel acampado tribo  por tribo. O Espírito de Deus tomou conta de Balaão,

[[v4-24-3]]

^<<v4-24-3,3>>^ e ele fez esta profecia : "Esta é a mensagem de Balaão, filho de Beor, são estas as palavras do homem que pode ver claramente

[[v4-24-4]]

^<<v4-24-4,4>>^ e que pode ouvir o que Deus está dizendo. Eu caio, os meus olhos se abrem, e eu tenho uma visão do Deus Todo-Poderoso.

[[v4-24-5]]

^<<v4-24-5,5>>^ Como é bonito o acampamento do povo de Israel! Como são belas as suas barracas!

[[v4-24-6]]

^<<v4-24-6,6>>^ Elas parecem filas de palmeiras, são como jardins na beira dos rios, como aloés  plantados por Deus, o Senhor , ou como cedros perto das águas.

[[v4-24-7]]

^<<v4-24-7,7>>^ Israel terá muita água para beber e para regar as suas sementeiras. O seu rei será mais poderoso do que Agague, e o seu reino será famoso.

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus tirou os israelitas do Egito e luta por eles como um touro selvagem. Eles devoram as nações inimigas, quebram os ossos dos seus soldados e os matam com as suas flechas.

[[v4-24-9]]

^<<v4-24-9,9>>^ Israel é como um leão poderoso: quando está dormindo, ninguém tem coragem para acordá-lo. Quem abençoar o povo de Israel será abençoado; e quem o amaldiçoar será amaldiçoado."

[[v4-24-10]]

^<<v4-24-10,10>>^ Aí Balaque ficou com muita raiva de Balaão. Com uma das mãos deu um soco na outra em sinal de ódio e disse: — Eu o chamei para amaldiçoar os meus inimigos, mas nestas três vezes você só os abençoou.

[[v4-24-11]]

^<<v4-24-11,11>>^ Agora vá embora para a sua casa. Prometi pagar bem a você, porém o Senhor  Deus não está deixando que você receba o pagamento.

[[v4-24-12]]

^<<v4-24-12,12>>^ Então Balaão respondeu: — Eu disse aos seus mensageiros que,

[[v4-24-13]]

^<<v4-24-13,13>>^ mesmo que você me desse toda a sua prata e todo o seu ouro, eu não poderia desobedecer à ordem de Deus, o Senhor . Eu disse que não faria nada por minha própria conta e somente diria aquilo que o Senhor  me ordenasse.

[[v4-24-14]]

^<<v4-24-14,14>>^ Balaão disse a Balaque: — Agora vou voltar para o meu próprio povo; mas, antes de ir, quero avisá-lo do que os israelitas vão fazer com o seu povo no futuro.

[[v4-24-15]]

^<<v4-24-15,15>>^ Então ele fez esta profecia : "Esta é a mensagem de Balaão, filho de Beor, são estas as palavras do homem que pode ver claramente,

[[v4-24-16]]

^<<v4-24-16,16>>^ que pode ouvir o que Deus está dizendo e receber o conhecimento que vem do Altíssimo. Eu caio, os meus olhos se abrem, e eu tenho uma visão do Deus Todo-Poderoso.

[[v4-24-17]]

^<<v4-24-17,17>>^ Olho para o futuro e vejo o povo de Israel. Um rei, como uma estrela brilhante, vai aparecer naquela nação; como um cometa ele virá de Israel. Ele derrotará os chefes dos moabitas e acabará com esse povo orgulhoso.

[[v4-24-18]]

^<<v4-24-18,18>>^ Ele conquistará os inimigos de Israel, os edomitas, e fará que a terra deles seja sua propriedade. O povo de Israel mostrará a sua força.

[[v4-24-19]]

^<<v4-24-19,19>>^ Dos descendentes de Jacó sairá o dominador que acabará com os que ficarem com vida nas cidades."

[[v4-24-20]]

^<<v4-24-20,20>>^ Aí, em sua visão, Balaão viu os amalequitas e fez esta profecia: "Amaleque era o povo mais poderoso de todos, mas no fim será destruído para sempre."

[[v4-24-21]]

^<<v4-24-21,21>>^ Balaão viu também os queneus e fez esta profecia: "O lugar onde vocês moram é seguro, o seu ninho está colocado na rocha.

[[v4-24-22]]

^<<v4-24-22,22>>^ Mas vocês serão destruídos quando a Assíria os levar como prisioneiros."

[[v4-24-23]]

^<<v4-24-23,23>>^ Balaão fez mais esta profecia: "Quem são estes povos reunidos no Norte?

[[v4-24-24]]

^<<v4-24-24,24>>^ De Chipre virão os inimigos nos seus navios; eles conquistarão a Assíria e Héber, mas depois eles mesmos serão destruídos para sempre."

[[v4-24-25]]

^<<v4-24-25,25>>^ Depois Balaão se aprontou e voltou para casa. E Balaque também foi embora.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]