include::./index.adoc[]

[[v4-32-0]]
=== Números, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-32-1]]

^<<v4-32-1,1>>^ As tribos  de Rúben e de Gade tinham gado em grande quantidade. Quando viram que a terra de Jazer e a terra de Gileade eram boas para a criação de gado,

[[v4-32-2]]

^<<v4-32-2,2>>^ foram falar com Moisés, com o sacerdote Eleazar e com as autoridades do povo. Eles disseram o seguinte:

[[v4-32-3]]

^<<v4-32-3,3>>^ — Esta região que o Senhor  Deus conquistou para os israelitas, isto é, as cidades de Atarote, Dibom, Jazer, Ninra, Hesbom, Eleal, Sebã, Nebo e Beom, é terra boa para a criação de gado. E nós temos muito gado.

[[v4-32-4]]

^<<v4-32-4,4>>^ — Esta região que o Senhor  Deus conquistou para os israelitas, isto é, as cidades de Atarote, Dibom, Jazer, Ninra, Hesbom, Eleal, Sebã, Nebo e Beom, é terra boa para a criação de gado. E nós temos muito gado.

[[v4-32-5]]

^<<v4-32-5,5>>^ Se o senhor está contente com a gente, então nos dê essa terra para ser nossa propriedade e não nos faça ir para o outro lado do rio Jordão.

[[v4-32-6]]

^<<v4-32-6,6>>^ Porém Moisés disse às tribos de Gade e de Rúben: — Vocês querem ficar aqui enquanto os seus patrícios vão para a guerra?

[[v4-32-7]]

^<<v4-32-7,7>>^ Será que vocês querem desanimar o povo de Israel para que não entre na terra que o Senhor  lhe está dando?

[[v4-32-8]]

^<<v4-32-8,8>>^ Os pais de vocês fizeram a mesma coisa quando os enviei de Cades-Barneia para espionar esta terra.

[[v4-32-9]]

^<<v4-32-9,9>>^ Eles chegaram até o vale de Escol e viram a terra; mas, quando voltaram, desanimaram o povo para que não entrasse na terra que o Senhor  lhe estava dando.

[[v4-32-10]]

^<<v4-32-10,10>>^ — Então, naquele dia, o Senhor  ficou muito irado  e disse:

[[v4-32-11]]

^<<v4-32-11,11>>^ "Os homens que vieram do Egito, de vinte anos para cima, deixaram de ser fiéis a mim, e por isso juro que eles não verão a terra que prometi dar a Abraão, a Isaque e a Jacó."

[[v4-32-12]]

^<<v4-32-12,12>>^ Somente Calebe, filho de Jefoné, o quenezeu, e Josué, filho de Num, continuaram fiéis ao Senhor .

[[v4-32-13]]

^<<v4-32-13,13>>^ O Senhor  ficou irado com o povo de Israel e os fez andar pelo deserto quarenta anos, até que morresse toda a gente daquele tempo, isto é, o povo que havia desagradado a Deus, o Senhor .

[[v4-32-14]]

^<<v4-32-14,14>>^ E agora vocês, raça de gente pecadora, estão tomando o lugar dos seus pais a fim de aumentar ainda mais a ira do Senhor  contra o povo de Israel.

[[v4-32-15]]

^<<v4-32-15,15>>^ Se vocês não quiserem segui-lo, ele abandonará novamente todo o povo no deserto, e eles serão destruídos por causa de vocês.

[[v4-32-16]]

^<<v4-32-16,16>>^ Mas a gente das tribos de Rúben e de Gade chegou perto de Moisés e disse: — Nós mesmos vamos construir aqui currais para as nossas ovelhas e vacas e também cidades para as nossas famílias.

[[v4-32-17]]

^<<v4-32-17,17>>^ Depois estaremos prontos para marchar para a guerra na frente dos nossos patrícios israelitas, até fazê-los tomar posse da terra que será deles. Porém as nossas famílias ficarão aqui nas cidades cercadas de muralhas e assim estarão a salvo dos moradores da terra.

[[v4-32-18]]

^<<v4-32-18,18>>^ Não voltaremos para as nossas casas até que todos os outros israelitas tomem posse da terra que será deles.

[[v4-32-19]]

^<<v4-32-19,19>>^ Não tomaremos posse de nenhuma propriedade no meio deles no outro lado do rio Jordão, pois receberemos a nossa parte aqui, a leste do Jordão.

[[v4-32-20]]

^<<v4-32-20,20>>^ Aí Moisés respondeu: — Se vocês vão fazer isso, então na presença de Deus, o Senhor , preparem-se para a batalha.

[[v4-32-21]]

^<<v4-32-21,21>>^ E que todos os seus homens armados atravessem o rio Jordão debaixo das ordens do Senhor , até que os nossos inimigos sejam expulsos diante dele,

[[v4-32-22]]

^<<v4-32-22,22>>^ e nós conquistemos a terra. Depois vocês poderão voltar porque já terão cumprido a sua obrigação para com Deus, o Senhor , e para com os seus patrícios israelitas. E o Senhor  reconhecerá esta terra a leste do rio Jordão como propriedade de vocês.

[[v4-32-23]]

^<<v4-32-23,23>>^ Porém, se vocês não cumprirem o que estão prometendo, estarão pecando contra o Senhor . E fiquem sabendo que vocês serão castigados por causa dos seus próprios pecados.

[[v4-32-24]]

^<<v4-32-24,24>>^ Construam as cidades para as suas famílias e façam currais para as suas ovelhas e vacas. E cumpram o que prometeram.

[[v4-32-25]]

^<<v4-32-25,25>>^ Os homens de Gade e de Rúben disseram a Moisés o seguinte: — Nós faremos o que o senhor mandar.

[[v4-32-26]]

^<<v4-32-26,26>>^ As nossas crianças, as nossas mulheres, as nossas ovelhas, as nossas cabras e todo o gado ficarão aqui nas cidades de Gileade.

[[v4-32-27]]

^<<v4-32-27,27>>^ Mas todos nós estamos prontos para a guerra. Conforme a sua ordem, atravessaremos o Jordão e batalharemos, debaixo do comando do Senhor  Deus.

[[v4-32-28]]

^<<v4-32-28,28>>^ Então Moisés deu ordens a respeito dos homens das tribos de Rúben e de Gade ao sacerdote Eleazar, a Josué, filho de Num, e aos chefes das famílias das tribos dos israelitas.

[[v4-32-29]]

^<<v4-32-29,29>>^ Ele disse assim: — Debaixo do comando de Deus, o Senhor , os homens de Gade e de Rúben deverão atravessar com vocês o rio Jordão, cada um armado para a batalha. Quando vocês tiverem conquistado as terras que ficam no lado oeste do Jordão, deem a região de Gileade para ser propriedade deles.

[[v4-32-30]]

^<<v4-32-30,30>>^ Porém, se eles não atravessarem armados o rio Jordão, junto com vocês, então deverão receber a parte deles na terra de Canaã.

[[v4-32-31]]

^<<v4-32-31,31>>^ Os homens de Gade e de Rúben responderam: — Senhor, nós faremos o que o Senhor  Deus ordenou.

[[v4-32-32]]

^<<v4-32-32,32>>^ Debaixo do comando dele atravessaremos o Jordão, armados, e lutaremos na terra de Canaã; e assim as terras deste lado do rio Jordão serão nossa propriedade.

[[v4-32-33]]

^<<v4-32-33,33>>^ Então Moisés deu às tribos de Gade e de Rúben e a uma metade da tribo de Manassés, filho de José, a região de Seom, o rei dos amorreus, e a região de Ogue, rei de Basã, junto com as cidades e as terras que havia em redor delas.

[[v4-32-34]]

^<<v4-32-34,34>>^ Os homens da tribo de Gade construíram de novo as cidades de Dibom, Atarote, Aroer,

[[v4-32-35]]

^<<v4-32-35,35>>^ Atarote-Sofã, Jazer, Jogbeá,

[[v4-32-36]]

^<<v4-32-36,36>>^ Bete-Ninra e Bete-Harã. Construíram muralhas ao redor delas e também currais.

[[v4-32-37]]

^<<v4-32-37,37>>^ Os homens de Rúben construíram de novo Hesbom, Eleal, Quiriataim,

[[v4-32-38]]

^<<v4-32-38,38>>^ Nebo, Baal-Meom (alguns nomes foram mudados) e Sibma. E deram outros nomes às cidades que eles construíram de novo.

[[v4-32-39]]

^<<v4-32-39,39>>^ O grupo de famílias de Maquir, filho de Manassés, foi para Gileade, e a conquistou, e expulsou os amorreus que estavam ali.

[[v4-32-40]]

^<<v4-32-40,40>>^ Portanto, Moisés deu Gileade ao grupo de famílias de Maquir, e eles moraram ali.

[[v4-32-41]]

^<<v4-32-41,41>>^ Jair, descendente de Manassés, foi e conquistou alguns povoados dos amorreus e os chamou de "povoados de Jair".

'''

xref:004-numeros/004-numeros-031.adoc#v4-31-0[&#60; Capítulo Anterior] | <<v4-32-0,Topo>> | xref:004-numeros/004-numeros-033.adoc#v4-33-0[Próximo Capítulo &#62;]