include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-23-1]]

^<<v4-23-1,1>>^ Então Balaão disse a Balaque: — Construa aqui sete altares e prepare para mim sete touros novos e sete carneiros.

[[v4-23-2]]

^<<v4-23-2,2>>^ Balaque fez como Balaão tinha dito, e os dois ofereceram em sacrifício  um touro novo e um carneiro em cada altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Aí Balaão disse a Balaque: — Fique aí perto da sua oferta queimada, que eu vou até ali. Talvez o Senhor  venha encontrar-se comigo, e eu direi a você tudo o que ele me ordenar. Depois Balaão subiu sozinho até o alto de um monte.

[[v4-23-4]]

^<<v4-23-4,4>>^ Ali Deus se encontrou com Balaão, e este lhe disse: — Construí sete altares e sobre cada um ofereci um touro novo e um carneiro.

[[v4-23-5]]

^<<v4-23-5,5>>^ O Senhor  Deus disse a Balaão o que ele deveria dizer e o mandou voltar e entregar a mensagem a Balaque.

[[v4-23-6]]

^<<v4-23-6,6>>^ Assim, Balaão voltou e encontrou Balaque ainda perto da sua oferta queimada, ele junto com os chefes moabitas.

[[v4-23-7]]

^<<v4-23-7,7>>^ Aí Balaão fez esta profecia : "Balaque, rei de Moabe, me fez vir da Síria; das montanhas do Leste ele me mandou chamar. ‘Venha — ele me disse — e me faça o favor de amaldiçoar o povo de Israel! Sim, amaldiçoe os israelitas!’

[[v4-23-8]]

^<<v4-23-8,8>>^ Como posso amaldiçoar aquele que Deus não amaldiçoou? Como posso condenar aquele que o Senhor  não condenou?

[[v4-23-9]]

^<<v4-23-9,9>>^ Do alto das rochas, na montanha, eu vejo o povo de Israel. Eles vivem sozinhos e acham que são diferentes dos outros povos.

[[v4-23-10]]

^<<v4-23-10,10>>^ Os descendentes de Jacó são como a poeira; são tantos, que não podem ser contados. Gostaria de terminar a minha vida como alguém que pertence ao povo de Deus; quero morrer em paz como as pessoas honestas."

[[v4-23-11]]

^<<v4-23-11,11>>^ Então Balaque disse a Balaão: — O que foi que você me fez? Eu o mandei chamar para amaldiçoar os meus inimigos, mas você somente os abençoou.

[[v4-23-12]]

^<<v4-23-12,12>>^ E ele respondeu: — Eu posso dizer apenas aquilo que o Senhor  me ordena.

[[v4-23-13]]

^<<v4-23-13,13>>^ Aí Balaque disse a Balaão: — Venha comigo para outro lugar, de onde você poderá ver somente alguns israelitas. Amaldiçoe dali essa gente, por favor.

[[v4-23-14]]

^<<v4-23-14,14>>^ Balaque o levou até o campo de Zofim, no alto do monte Pisga. Ali construiu sete altares e em cima de cada altar ofereceu em sacrifício  um touro novo e um carneiro.

[[v4-23-15]]

^<<v4-23-15,15>>^ Então Balaão disse a Balaque: — Fique aqui perto da sua oferta queimada, e eu irei até ali para me encontrar com Deus, o Senhor .

[[v4-23-16]]

^<<v4-23-16,16>>^ O Senhor  se encontrou com Balaão e disse o que ele deveria dizer e o mandou voltar até o lugar onde Balaque estava, a fim de entregar-lhe a mensagem.

[[v4-23-17]]

^<<v4-23-17,17>>^ Assim, Balaão voltou e encontrou Balaque ainda perto da sua oferta queimada, ele junto com os chefes moabitas. Balaque perguntou o que o Senhor  lhe tinha dito,

[[v4-23-18]]

^<<v4-23-18,18>>^ e Balaão fez esta profecia : "Venha, Balaque, filho de Zipor, e escute o que vou dizer.

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é como os homens, que mentem; não é um ser humano, que muda de ideia. Quando foi que Deus prometeu e não cumpriu? Ele diz que faz e faz mesmo.

[[v4-23-20]]

^<<v4-23-20,20>>^ Recebi ordem para abençoar; ele abençoou, e eu não posso mudar nada.

[[v4-23-21]]

^<<v4-23-21,21>>^ Vejo que no futuro do povo de Israel não há desgraça nem sofrimentos. O Senhor , seu Deus, está com eles, e o povo está gritando que o Senhor  é o seu Rei.

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus os tirou do Egito; ele tem a força de um touro selvagem.

[[v4-23-23]]

^<<v4-23-23,23>>^ A feitiçaria e a adivinhação não valem nada contra o povo de Israel. Agora todos dirão a respeito desse povo: ‘Vejam só o que Deus tem feito!’

[[v4-23-24]]

^<<v4-23-24,24>>^ Israel se levanta como uma leoa e se firma como um leão. Ele não descansa até que tenha devorado a presa e bebido o sangue das suas vítimas."

[[v4-23-25]]

^<<v4-23-25,25>>^ Então Balaque disse a Balaão: — Se você não pode amaldiçoar o povo de Israel, pelo menos não o abençoe.

[[v4-23-26]]

^<<v4-23-26,26>>^ Balaão respondeu: — Eu já não disse que só posso fazer o que o Senhor  ordenar?

[[v4-23-27]]

^<<v4-23-27,27>>^ Então Balaque disse a Balaão: — Venha comigo, que eu vou levá-lo a outro lugar. Talvez Deus queira que de lá você amaldiçoe os israelitas.

[[v4-23-28]]

^<<v4-23-28,28>>^ Aí Balaque levou Balaão até o alto do monte Peor, no lado que dá para o deserto.

[[v4-23-29]]

^<<v4-23-29,29>>^ Balaão disse a Balaque: — Construa para mim aqui sete altares e me prepare sete touros novos e sete carneiros.

[[v4-23-30]]

^<<v4-23-30,30>>^ Balaque fez como Balaão havia ordenado e ofereceu em sacrifício  um touro novo e um carneiro em cada altar.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]