include::./index.adoc[]

[[v4-28-0]]
=== Números, 28
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-28-1]]

^<<v4-28-1,1>>^ O Senhor  Deus disse a Moisés:

[[v4-28-2]]

^<<v4-28-2,2>>^ — Mande que os israelitas tragam para mim, no tempo certo, as ofertas de alimento que têm um cheiro que me agrada.

[[v4-28-3]]

^<<v4-28-3,3>>^ — São estas as ofertas de alimento que devem ser apresentadas todos os dias e para sempre: dois carneirinhos de um ano, sem defeito.

[[v4-28-4]]

^<<v4-28-4,4>>^ Um deles será oferecido de manhã, e o outro, à tarde.

[[v4-28-5]]

^<<v4-28-5,5>>^ Junto com cada carneirinho, será oferecido um quilo da melhor farinha de trigo misturada com um litro de azeite.

[[v4-28-6]]

^<<v4-28-6,6>>^ Esse sacrifício  será completamente queimado e deverá ser oferecido todos os dias. É uma oferta de alimento, de cheiro agradável a Deus, o Senhor , que foi apresentada pela primeira vez no monte Sinai.

[[v4-28-7]]

^<<v4-28-7,7>>^ Junto com cada carneirinho, será oferecido um litro de vinho. Esse vinho deverá ser derramado no Lugar Santo , em honra do Senhor .

[[v4-28-8]]

^<<v4-28-8,8>>^ À tarde será oferecido o outro carneirinho, e, junto com ele, a mesma quantidade de farinha, azeite e vinho, como de manhã. Essa é uma oferta de alimento trazida para mim, o Senhor , e o seu cheiro me agrada.

[[v4-28-9]]

^<<v4-28-9,9>>^ — No sábado serão oferecidos dois carneirinhos de um ano, sem defeito, junto com dois quilos da melhor farinha misturada com azeite, como oferta de cereais, e também uma oferta de vinho.

[[v4-28-10]]

^<<v4-28-10,10>>^ Essa oferta completamente queimada será oferecida todo sábado, além da oferta que é completamente queimada todos os dias e entregue junto com a oferta de vinho que a acompanha.

[[v4-28-11]]

^<<v4-28-11,11>>^ — No princípio de cada mês deem a mim, o Senhor , uma oferta que será completamente queimada. Essa oferta será de dois touros novos, um carneiro e sete carneirinhos de um ano, todos sem defeito.

[[v4-28-12]]

^<<v4-28-12,12>>^ Com cada touro novo, ofereçam três quilos da melhor farinha misturada com azeite. Com cada carneiro, ofereçam dois quilos de farinha misturada com azeite

[[v4-28-13]]

^<<v4-28-13,13>>^ e, com cada carneirinho, um quilo. Essas ofertas completamente queimadas são ofertas de alimento e têm um cheiro agradável a mim, o Senhor .

[[v4-28-14]]

^<<v4-28-14,14>>^ A oferta de vinho é assim: dois litros de vinho com cada touro novo, um litro e meio com cada carneiro e um litro com cada carneirinho. São essas as ofertas que serão completamente queimadas no dia primeiro de cada mês, durante o ano inteiro.

[[v4-28-15]]

^<<v4-28-15,15>>^ Além do sacrifício  que é completamente queimado e que é oferecido todos os dias e além da oferta de vinho, ofereçam também ao Senhor  um bode, para tirar os pecados do povo.

[[v4-28-16]]

^<<v4-28-16,16>>^ — A Festa da Páscoa , comemorada em honra do Senhor  Deus cai no dia catorze do primeiro mês.

[[v4-28-17]]

^<<v4-28-17,17>>^ No dia quinze desse mês haverá festa. Durante sete dias vocês comerão pães  feitos sem fermento.

[[v4-28-18]]

^<<v4-28-18,18>>^ No primeiro dia dessa festa ninguém trabalhará; todos se reunirão para adorar a Deus.

[[v4-28-19]]

^<<v4-28-19,19>>^ Ofereçam ao Senhor  um sacrifício  que será completamente queimado, como oferta de alimento. Essa oferta será de dois touros novos, um carneiro e sete carneirinhos de um ano, todos sem defeito.

[[v4-28-20]]

^<<v4-28-20,20>>^ Com cada touro novo, ofereçam três quilos da melhor farinha misturada com azeite. Com cada carneiro, ofereçam dois quilos de farinha misturada com azeite

[[v4-28-21]]

^<<v4-28-21,21>>^ e, com cada carneirinho, um quilo.

[[v4-28-22]]

^<<v4-28-22,22>>^ Ofereçam também a Deus um bode como sacrifício para tirar os pecados do povo.

[[v4-28-23]]

^<<v4-28-23,23>>^ Vocês oferecerão essas coisas, além do sacrifício que é completamente queimado todas as manhãs.

[[v4-28-24]]

^<<v4-28-24,24>>^ Assim, vocês oferecerão ao Senhor  cada dia, durante sete dias, uma oferta de alimento que tem cheiro agradável a ele. Ofereçam isso, além do sacrifício que é completamente queimado todos os dias e além da oferta de vinho.

[[v4-28-25]]

^<<v4-28-25,25>>^ No sétimo dia vocês se reunirão para adorar a Deus, e ninguém trabalhará.

[[v4-28-26]]

^<<v4-28-26,26>>^ — Vocês terão outra festa, chamada " Festa da Colheita " ou "Festa das Semanas". No primeiro dia dessa festa, quando oferecerem a Deus, o Senhor , a nova colheita de cereais, vocês se reunirão para o adorar, e ninguém trabalhará.

[[v4-28-27]]

^<<v4-28-27,27>>^ Ofereçam ao Senhor  um sacrifício  que será completamente queimado, que tem um cheiro agradável a ele. Esse sacrifício será de dois touros novos, um carneiro e sete carneirinhos de um ano, todos sem defeito.

[[v4-28-28]]

^<<v4-28-28,28>>^ Com cada touro novo, ofereçam três quilos da melhor farinha misturada com azeite. Com cada carneiro, ofereçam dois quilos de farinha misturada com azeite

[[v4-28-29]]

^<<v4-28-29,29>>^ e, com cada carneirinho, um quilo.

[[v4-28-30]]

^<<v4-28-30,30>>^ Tragam também um bode como sacrifício para tirar os pecados do povo.

[[v4-28-31]]

^<<v4-28-31,31>>^ Tragam isso e também a oferta de vinho, o sacrifício que é completamente queimado todos os dias e a oferta de cereais.

'''

xref:004-numeros/004-numeros-027.adoc#v4-27-0[&#60; Capítulo Anterior] | <<v4-28-0,Topo>> | xref:004-numeros/004-numeros-029.adoc#v4-29-0[Próximo Capítulo &#62;]