include::./index.adoc[]

[[v4-36-0]]
=== Números, 36
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-36-1]]

^<<v4-36-1,1>>^ Os chefes de família dos grupos de famílias de Gileade, descendentes diretos de Maquir, Manassés e José, foram falar com Moisés e com os outros chefes de famílias israelitas. Eles disseram a Moisés:

[[v4-36-2]]

^<<v4-36-2,2>>^ — O Senhor  Deus ordenou que o senhor distribuísse a terra ao povo por sorteio . Ele também ordenou que o senhor desse a propriedade do nosso parente Zelofeade às suas filhas.

[[v4-36-3]]

^<<v4-36-3,3>>^ Porém, se elas casarem com homens de outra tribo  israelita, a terra que foi dada a elas deixará de pertencer à nossa tribo e passará a ser da tribo daqueles com quem elas casarem. Assim irá diminuindo a parte que nos foi dada por sorteio.

[[v4-36-4]]

^<<v4-36-4,4>>^ Porém, quando chegar o Ano da Libertação, a terra delas ficará definitivamente para a tribo daqueles com quem elas casaram e não será mais nossa.

[[v4-36-5]]

^<<v4-36-5,5>>^ Então Moisés, conforme a ordem do Senhor , respondeu aos israelitas o seguinte: — Os homens da tribo de José têm razão. A ordem do Senhor  para as filhas de Zelofeade é esta:

[[v4-36-6]]

^<<v4-36-6,6>>^ Elas podem casar com quem quiserem, contanto que seja com um homem de uma das famílias da tribo do seu pai.

[[v4-36-7]]

^<<v4-36-7,7>>^ Desse modo as terras dos israelitas não passarão de uma tribo para outra. Pois os israelitas devem ficar ligados cada um à terra da tribo dos seus pais.

[[v4-36-8]]

^<<v4-36-8,8>>^ Todas as moças que tiverem terras numa tribo israelita deverão casar com alguém da família da tribo do seu pai.

[[v4-36-9]]

^<<v4-36-9,9>>^ Desse modo cada israelita herdará a terra dos seus antepassados, e ela não passará de uma tribo para outra. Cada tribo continuará ligada à sua própria terra.

[[v4-36-10]]

^<<v4-36-10,10>>^ Então Macla, Tirza, Hogla, Milca e Noa, filhas de Zelofeade, fizeram como o Senhor  havia ordenado a Moisés e casaram com filhos dos seus tios paternos.

[[v4-36-11]]

^<<v4-36-11,11>>^ Então Macla, Tirza, Hogla, Milca e Noa, filhas de Zelofeade, fizeram como o Senhor  havia ordenado a Moisés e casaram com filhos dos seus tios paternos.

[[v4-36-12]]

^<<v4-36-12,12>>^ Elas casaram dentro dos grupos de famílias da tribo de Manassés, filho de José, e as suas terras ficaram na tribo do pai delas.

'''

xref:004-numeros/004-numeros-035.adoc#v4-35-0[&#60; Capítulo Anterior] | <<v4-36-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[Próximo Capítulo &#62;]