include::./index.adoc[]

[[v4-31-0]]
=== Números, 31
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-31-1]]

^<<v4-31-1,1>>^ O Senhor  Deus disse a Moisés:

[[v4-31-2]]

^<<v4-31-2,2>>^ — Mande que os israelitas se vinguem do mal que os midianitas lhes fizeram. Depois disso você vai morrer.

[[v4-31-3]]

^<<v4-31-3,3>>^ Então Moisés disse ao povo: — Preparem homens para a batalha, ataquem os midianitas e se vinguem deles pelo que fizeram contra Deus, o Senhor .

[[v4-31-4]]

^<<v4-31-4,4>>^ Cada tribo  deve mandar mil soldados para esta guerra.

[[v4-31-5]]

^<<v4-31-5,5>>^ Assim, dos milhares de israelitas foram mandados de cada tribo mil soldados armados, doze mil ao todo.

[[v4-31-6]]

^<<v4-31-6,6>>^ Moisés mandou esses soldados para a batalha, debaixo do comando de Fineias, filho do sacerdote Eleazar, que levou também os objetos sagrados e as cornetas para dar os sinais.

[[v4-31-7]]

^<<v4-31-7,7>>^ Eles atacaram os midianitas, como o Senhor  havia ordenado a Moisés, e mataram todos os homens.

[[v4-31-8]]

^<<v4-31-8,8>>^ Entre os mortos estavam Evi, Requém, Zur, Hur e Reba, os cinco reis midianitas. Também mataram à espada Balaão, filho de Beor.

[[v4-31-9]]

^<<v4-31-9,9>>^ Os israelitas levaram presas as mulheres e as crianças dos midianitas. Pegaram também as suas ovelhas e cabras, o seu gado e todos os seus bens.

[[v4-31-10]]

^<<v4-31-10,10>>^ Incendiaram todas as cidades onde os midianitas moravam e queimaram todos os acampamentos.

[[v4-31-11]]

^<<v4-31-11,11>>^ Eles pegaram o que haviam tomado dos midianitas e também os prisioneiros e os animais

[[v4-31-12]]

^<<v4-31-12,12>>^ e levaram tudo a Moisés, ao sacerdote Eleazar e ao povo de Israel, que estavam acampados nas planícies de Moabe, perto do rio Jordão, na altura de Jericó, que ficava no outro lado do rio.

[[v4-31-13]]

^<<v4-31-13,13>>^ Moisés, o sacerdote Eleazar e todas as autoridades do povo saíram do acampamento e foram ao encontro do exército.

[[v4-31-14]]

^<<v4-31-14,14>>^ Moisés ficou muito zangado com os oficiais que haviam voltado da batalha, isto é, os comandantes dos batalhões e das companhias.

[[v4-31-15]]

^<<v4-31-15,15>>^ Moisés perguntou: — Por que vocês deixaram vivas todas as mulheres?

[[v4-31-16]]

^<<v4-31-16,16>>^ Lembrem que foram as mulheres que, seguindo os conselhos de Balaão, fizeram com que os israelitas fossem infiéis a Deus, o Senhor , adorando o deus Baal-Peor. Foi por isso que houve uma epidemia no meio do povo de Deus.

[[v4-31-17]]

^<<v4-31-17,17>>^ Agora matem todos os meninos e todas as mulheres que não forem virgens.

[[v4-31-18]]

^<<v4-31-18,18>>^ Mas deixem viver todas as meninas e as moças que forem virgens; elas pertencem a vocês.

[[v4-31-19]]

^<<v4-31-19,19>>^ Agora todos os que tiverem matado alguém ou que tiverem tocado em algum morto devem ficar fora do acampamento sete dias. No terceiro dia e no sétimo, vocês e as prisioneiras devem se purificar .

[[v4-31-20]]

^<<v4-31-20,20>>^ Purifiquem também todas as roupas, todos os objetos feitos de couro, tudo o que é feito de pelos de cabra e tudo o que é feito de madeira.

[[v4-31-21]]

^<<v4-31-21,21>>^ Então o sacerdote Eleazar disse aos homens que tinham voltado da batalha: — A lei  que o Senhor  Deus ordenou a Moisés é esta:

[[v4-31-22]]

^<<v4-31-22,22>>^ Tudo o que o fogo não destrói, como ouro, prata, bronze, ferro, estanho e chumbo, deverá ser purificado pelo fogo. Mas tudo o que o fogo pode destruir será purificado com água.

[[v4-31-23]]

^<<v4-31-23,23>>^ Tudo o que o fogo não destrói, como ouro, prata, bronze, ferro, estanho e chumbo, deverá ser purificado pelo fogo. Mas tudo o que o fogo pode destruir será purificado com água.

[[v4-31-24]]

^<<v4-31-24,24>>^ No sétimo dia, para se purificarem, vocês deverão lavar as roupas que estiverem vestindo. Depois disso vocês poderão entrar no acampamento.

[[v4-31-25]]

^<<v4-31-25,25>>^ O Senhor  Deus disse a Moisés:

[[v4-31-26]]

^<<v4-31-26,26>>^ — Você, com a ajuda do sacerdote Eleazar e das autoridades do povo, faça uma lista de tudo o que foi tomado na batalha, incluindo as pessoas e os animais.

[[v4-31-27]]

^<<v4-31-27,27>>^ Divida em duas partes iguais o que foi tomado: uma parte para os soldados e a outra para o resto do povo.

[[v4-31-28]]

^<<v4-31-28,28>>^ Da parte que pertence aos soldados que estiveram na batalha, separe um imposto para Deus, o Senhor : uma pessoa de cada quinhentas e a mesma coisa quanto aos bois, jumentos, ovelhas e cabras.

[[v4-31-29]]

^<<v4-31-29,29>>^ Pegue esse imposto e entregue ao sacerdote Eleazar, como oferta ao Senhor .

[[v4-31-30]]

^<<v4-31-30,30>>^ Da parte que pertence ao povo, pegue um de cada cinquenta, tanto de pessoas como de bois, de jumentos, de ovelhas, de cabras e de qualquer outro animal, e dê aos levitas , que cuidam da Tenda  do Senhor .

[[v4-31-31]]

^<<v4-31-31,31>>^ Moisés e Eleazar fizeram o que o Senhor  havia ordenado.

[[v4-31-32]]

^<<v4-31-32,32>>^ Esta é a lista do que foi tomado pelos soldados, sem contar o que eles pegaram para si mesmos: seiscentas e setenta e cinco mil ovelhas e cabras, setenta e dois mil bois e vacas, sessenta e um mil jumentos e trinta e duas mil pessoas.

[[v4-31-33]]

^<<v4-31-33,33>>^ Esta é a lista do que foi tomado pelos soldados, sem contar o que eles pegaram para si mesmos: seiscentas e setenta e cinco mil ovelhas e cabras, setenta e dois mil bois e vacas, sessenta e um mil jumentos e trinta e duas mil pessoas.

[[v4-31-34]]

^<<v4-31-34,34>>^ Esta é a lista do que foi tomado pelos soldados, sem contar o que eles pegaram para si mesmos: seiscentas e setenta e cinco mil ovelhas e cabras, setenta e dois mil bois e vacas, sessenta e um mil jumentos e trinta e duas mil pessoas.

[[v4-31-35]]

^<<v4-31-35,35>>^ Esta é a lista do que foi tomado pelos soldados, sem contar o que eles pegaram para si mesmos: seiscentas e setenta e cinco mil ovelhas e cabras, setenta e dois mil bois e vacas, sessenta e um mil jumentos e trinta e duas mil pessoas.

[[v4-31-36]]

^<<v4-31-36,36>>^ A metade que ficou para os soldados foi de trezentas e trinta e sete mil e quinhentas ovelhas e cabras, das quais seiscentas e setenta e cinco foram o imposto para Deus, o Senhor ; trinta e seis mil bois e vacas para os soldados, dos quais setenta e dois foram o imposto para o Senhor ; trinta mil e quinhentos jumentos para os soldados, dos quais sessenta e um foram o imposto para Deus; e dezesseis mil virgens para os soldados, das quais trinta e duas foram o imposto para Deus.

[[v4-31-37]]

^<<v4-31-37,37>>^ A metade que ficou para os soldados foi de trezentas e trinta e sete mil e quinhentas ovelhas e cabras, das quais seiscentas e setenta e cinco foram o imposto para Deus, o Senhor ; trinta e seis mil bois e vacas para os soldados, dos quais setenta e dois foram o imposto para o Senhor ; trinta mil e quinhentos jumentos para os soldados, dos quais sessenta e um foram o imposto para Deus; e dezesseis mil virgens para os soldados, das quais trinta e duas foram o imposto para Deus.

[[v4-31-38]]

^<<v4-31-38,38>>^ A metade que ficou para os soldados foi de trezentas e trinta e sete mil e quinhentas ovelhas e cabras, das quais seiscentas e setenta e cinco foram o imposto para Deus, o Senhor ; trinta e seis mil bois e vacas para os soldados, dos quais setenta e dois foram o imposto para o Senhor ; trinta mil e quinhentos jumentos para os soldados, dos quais sessenta e um foram o imposto para Deus; e dezesseis mil virgens para os soldados, das quais trinta e duas foram o imposto para Deus.

[[v4-31-39]]

^<<v4-31-39,39>>^ A metade que ficou para os soldados foi de trezentas e trinta e sete mil e quinhentas ovelhas e cabras, das quais seiscentas e setenta e cinco foram o imposto para Deus, o Senhor ; trinta e seis mil bois e vacas para os soldados, dos quais setenta e dois foram o imposto para o Senhor ; trinta mil e quinhentos jumentos para os soldados, dos quais sessenta e um foram o imposto para Deus; e dezesseis mil virgens para os soldados, das quais trinta e duas foram o imposto para Deus.

[[v4-31-40]]

^<<v4-31-40,40>>^ A metade que ficou para os soldados foi de trezentas e trinta e sete mil e quinhentas ovelhas e cabras, das quais seiscentas e setenta e cinco foram o imposto para Deus, o Senhor ; trinta e seis mil bois e vacas para os soldados, dos quais setenta e dois foram o imposto para o Senhor ; trinta mil e quinhentos jumentos para os soldados, dos quais sessenta e um foram o imposto para Deus; e dezesseis mil virgens para os soldados, das quais trinta e duas foram o imposto para Deus.

[[v4-31-41]]

^<<v4-31-41,41>>^ Assim, Moisés deu a Eleazar o imposto como uma oferta especial a Deus, o Senhor , como o Senhor  havia ordenado.

[[v4-31-42]]

^<<v4-31-42,42>>^ A parte do povo foi igual à parte dos soldados, isto é, trezentas e trinta e sete mil e quinhentas ovelhas e cabras, trinta e seis mil bois e vacas, trinta mil e quinhentos jumentos e dezesseis mil virgens.

'''

xref:004-numeros/004-numeros-030.adoc#v4-30-0[&#60; Capítulo Anterior] | <<v4-31-0,Topo>> | xref:004-numeros/004-numeros-032.adoc#v4-32-0[Próximo Capítulo &#62;]