include::./index.adoc[]

[[v4-15-0]]
=== Números, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-15-1]]

^<<v4-15-1,1>>^ O Senhor  Deus deu a Moisés

[[v4-15-2]]

^<<v4-15-2,2>>^ as seguintes ordens, que deveriam ser obedecidas quando os israelitas entrassem na terra que ele ia dar para eles.

[[v4-15-3]]

^<<v4-15-3,3>>^ Um touro, ou um carneiro, ou uma ovelha, ou um cabrito poderão ser apresentados ao Senhor  como oferta que será completamente queimada, ou como sacrifício  para pagar uma promessa, ou ainda como oferta feita por vontade própria, ou como oferta que será entregue nas festas religiosas nos dias marcados. O cheiro dessas ofertas é agradável ao Senhor .

[[v4-15-4]]

^<<v4-15-4,4>>^ Aquele que apresentar ao Senhor  uma ovelha ou um cabrito como oferta para ser completamente queimada deverá trazer também com cada animal um quilo de farinha fina misturada com um litro e um quarto de azeite e também um litro de vinho.

[[v4-15-5]]

^<<v4-15-5,5>>^ Aquele que apresentar ao Senhor  uma ovelha ou um cabrito como oferta para ser completamente queimada deverá trazer também com cada animal um quilo de farinha fina misturada com um litro e um quarto de azeite e também um litro de vinho.

[[v4-15-6]]

^<<v4-15-6,6>>^ Com cada carneiro que for oferecido, será apresentada uma oferta de cereais de dois quilos de farinha fina misturada com um litro de azeite, e será trazido também

[[v4-15-7]]

^<<v4-15-7,7>>^ um litro e um quarto de vinho. O cheiro desses sacrifícios é agradável ao Senhor .

[[v4-15-8]]

^<<v4-15-8,8>>^ Quando vocês oferecerem um touro novo como oferta que será completamente queimada, ou como oferta especial para pagar uma promessa, ou, ainda, como oferta de paz,

[[v4-15-9]]

^<<v4-15-9,9>>^ deverão apresentar também com o touro uma oferta de cereais de três quilos de farinha fina misturada com um litro e três quartos de azeite

[[v4-15-10]]

^<<v4-15-10,10>>^ e também um litro e três quartos de vinho. O cheiro desse sacrifício é agradável a Deus, o Senhor .

[[v4-15-11]]

^<<v4-15-11,11>>^ É assim que se deverá fazer com todos os touros, carneiros, ovelhas e cabritos.

[[v4-15-12]]

^<<v4-15-12,12>>^ Quando for oferecido mais do que um animal, as ofertas que vêm junto com eles deverão ser aumentadas de acordo com o número dos animais.

[[v4-15-13]]

^<<v4-15-13,13>>^ Todos os israelitas farão isso quando trouxerem as ofertas de alimento que têm um cheiro agradável ao Senhor .

[[v4-15-14]]

^<<v4-15-14,14>>^ No caso dos estrangeiros que estiverem morando com vocês, seja só por algum tempo, seja para sempre, eles farão o mesmo que vocês quando eles apresentarem a Deus, o Senhor , uma oferta de alimento, que tem um cheiro agradável a Deus.

[[v4-15-15]]

^<<v4-15-15,15>>^ A mesma lei  será para vocês e para os estrangeiros que moram com vocês. Esta é uma lei que valerá para sempre para os seus descendentes. Diante do Senhor  a lei será a mesma tanto para vocês como para os estrangeiros.

[[v4-15-16]]

^<<v4-15-16,16>>^ A mesma lei e o mesmo regulamento serão para vocês e para eles.

[[v4-15-17]]

^<<v4-15-17,17>>^ O Senhor  Deus deu a Moisés

[[v4-15-18]]

^<<v4-15-18,18>>^ as seguintes ordens, que deveriam ser obedecidas quando os israelitas entrassem na terra que ele ia dar para eles.

[[v4-15-19]]

^<<v4-15-19,19>>^ Quando vocês comerem o alimento que a terra produz, deverão separar uma parte como oferta especial para o Senhor .

[[v4-15-20]]

^<<v4-15-20,20>>^ Quando vocês fizerem pão, o primeiro pão feito da farinha nova deverá ser apresentado a Deus como oferta especial.

[[v4-15-21]]

^<<v4-15-21,21>>^ Vocês e os seus descendentes darão ao Senhor  essa oferta especial de pão.

[[v4-15-22]]

^<<v4-15-22,22>>^ Pode acontecer que alguém, sem querer, peque e desobedeça a algum desses mandamentos que o Senhor  deu a Moisés.

[[v4-15-23]]

^<<v4-15-23,23>>^ Nesses casos, começando no dia em que o Senhor  deu todos esses mandamentos a Moisés e por todas as gerações  futuras, deverá ser feito o seguinte:

[[v4-15-24]]

^<<v4-15-24,24>>^ Se por ignorância o povo cometer um pecado, então apresentará um touro novo, que será completamente queimado como sacrifício de cheiro agradável ao Senhor , e também as ofertas de cereais e de vinho. Também deverá ser oferecido um bode para tirar o pecado.

[[v4-15-25]]

^<<v4-15-25,25>>^ O sacerdote apresentará o sacrifício em favor de todos os israelitas, para conseguir o perdão dos pecados deles, e eles serão perdoados; pois, sem quererem, cometeram um pecado e apresentaram ao Senhor  uma oferta para tirar o pecado e também uma oferta de alimento.

[[v4-15-26]]

^<<v4-15-26,26>>^ Todos os israelitas e os estrangeiros que moram no meio de vocês serão perdoados, pois foi um erro que todo o povo cometeu sem querer.

[[v4-15-27]]

^<<v4-15-27,27>>^ Se alguma pessoa pecar sem querer, oferecerá uma cabra de um ano como oferta para tirar o pecado.

[[v4-15-28]]

^<<v4-15-28,28>>^ O sacerdote apresentará no altar o sacrifício para conseguir o perdão do pecado que essa pessoa cometeu sem querer, e ela será perdoada.

[[v4-15-29]]

^<<v4-15-29,29>>^ A lei é a mesma para quem pecar sem querer, tanto para os israelitas como para os estrangeiros que moram no meio de vocês.

[[v4-15-30]]

^<<v4-15-30,30>>^ Mas quem pecar de propósito, tanto o israelita de nascimento como o estrangeiro, será culpado de ofender a Deus, o Senhor . Essa pessoa será morta,

[[v4-15-31]]

^<<v4-15-31,31>>^ pois rejeitou o que o Senhor  disse e desobedeceu ao seu mandamento porque quis. Essa pessoa será responsável pela sua própria morte.

[[v4-15-32]]

^<<v4-15-32,32>>^ Quando os israelitas ainda estavam no deserto, encontraram um homem catando lenha no sábado.

[[v4-15-33]]

^<<v4-15-33,33>>^ Os que o viram fazendo isso o levaram até o lugar onde estavam Moisés, Arão e todo o povo.

[[v4-15-34]]

^<<v4-15-34,34>>^ Depois puseram alguns homens para guardá-lo, pois ainda não sabiam o que fazer com ele.

[[v4-15-35]]

^<<v4-15-35,35>>^ Aí o Senhor  Deus disse a Moisés: — Esse homem deve ser morto; que todo o povo o mate a pedradas fora do acampamento!

[[v4-15-36]]

^<<v4-15-36,36>>^ Então, como o Senhor  havia ordenado a Moisés, levaram o homem para fora do acampamento, e todo o povo atirou pedras nele até que ele morreu.

[[v4-15-37]]

^<<v4-15-37,37>>^ O Senhor  Deus disse a Moisés:

[[v4-15-38]]

^<<v4-15-38,38>>^ — Diga aos israelitas que eles e os seus descendentes ponham pingentes nas pontas das suas capas ; e em cada pingente ponham um cordão azul.

[[v4-15-39]]

^<<v4-15-39,39>>^ Quando vocês virem esses pingentes, lembrarão de todos os mandamentos do Senhor . E também praticarão esses mandamentos e não serão infiéis, seguindo os desejos do coração de vocês e dos seus olhos.

[[v4-15-40]]

^<<v4-15-40,40>>^ Os pingentes farão com que vocês lembrem de todos os meus mandamentos e os sigam em tudo. Assim, vocês serão um povo separado só para mim.

'''

xref:004-numeros/004-numeros-014.adoc#v4-14-0[&#60; Capítulo Anterior] | <<v4-15-0,Topo>> | xref:004-numeros/004-numeros-016.adoc#v4-16-0[Próximo Capítulo &#62;]