include::./index.adoc[]

[[v4-20-0]]
=== Números, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-20-1]]

^<<v4-20-1,1>>^ No primeiro mês todo o povo de Israel foi para o deserto de Zim e acampou em Cades. Ali Míriam morreu e foi sepultada.

[[v4-20-2]]

^<<v4-20-2,2>>^ Naquele lugar não havia água; por isso o povo se reuniu e começou a reclamar contra Moisés e Arão.

[[v4-20-3]]

^<<v4-20-3,3>>^ Eles diziam: — Teria sido melhor se tivéssemos morrido na frente de Deus, o Senhor , com os nossos companheiros, os outros israelitas!

[[v4-20-4]]

^<<v4-20-4,4>>^ Por que você trouxe o povo do Senhor  para este deserto? Será que foi para morrermos junto com os nossos animais?

[[v4-20-5]]

^<<v4-20-5,5>>^ Por que você nos trouxe do Egito para este lugar terrível, onde não há cereais, nem figueiras, nem parreiras , nem romãs? E além de tudo não há água para beber!

[[v4-20-6]]

^<<v4-20-6,6>>^ Então Moisés e Arão saíram dali, onde o povo estava, e foram para a porta da Tenda Sagrada . Eles se ajoelharam, encostaram o rosto no chão, e a glória  do Senhor  apareceu.

[[v4-20-7]]

^<<v4-20-7,7>>^ E o Senhor  disse a Moisés:

[[v4-20-8]]

^<<v4-20-8,8>>^ — Pegue o bastão que está em frente da arca da aliança , e depois você e Arão reúnam o povo. E na frente de todos eles deem ordem à rocha, e dela sairá água. Assim, vocês tirarão água da rocha e darão de beber ao povo e também aos animais.

[[v4-20-9]]

^<<v4-20-9,9>>^ Então, como Deus havia ordenado, Moisés pegou o bastão que estava diante de Deus, o Senhor .

[[v4-20-10]]

^<<v4-20-10,10>>^ Moisés e Arão reuniram o povo em frente da rocha, e Moisés disse: — Agora escute, gente rebelde! Será que vamos ter de fazer sair água desta rocha para vocês?

[[v4-20-11]]

^<<v4-20-11,11>>^ Moisés levantou a mão, bateu na rocha duas vezes com o bastão, e saiu muita água. E o povo e os animais beberam.

[[v4-20-12]]

^<<v4-20-12,12>>^ Porém o Senhor  disse a Moisés e a Arão: — Vocês não tiveram fé suficiente para fazer com que o povo de Israel reconhecesse o meu santo poder e por isso vocês não vão levá-los para a terra que prometi dar a eles.

[[v4-20-13]]

^<<v4-20-13,13>>^ Isso aconteceu em Meribá , onde o povo de Israel reclamou contra Deus, o Senhor , e onde Deus lhes deu uma prova do seu santo poder.

[[v4-20-14]]

^<<v4-20-14,14>>^ Da cidade de Cades, Moisés enviou alguns mensageiros que foram dizer ao rei de Edom o seguinte: — Esta mensagem é dos seus parentes , as tribos  de Israel. O senhor conhece todas as dificuldades que temos tido

[[v4-20-15]]

^<<v4-20-15,15>>^ e sabe como os nossos antepassados foram para o Egito, onde vivemos muitos anos. Os egípcios maltrataram os nossos antepassados e a nós,

[[v4-20-16]]

^<<v4-20-16,16>>^ e por isso pedimos a Deus, o Senhor , que nos socorresse. Ele ouviu o nosso pedido e mandou um anjo que nos tirou do Egito. Agora estamos na cidade de Cades, na fronteira do seu país.

[[v4-20-17]]

^<<v4-20-17,17>>^ Por favor, deixe-nos passar pela sua terra. Nós e o nosso gado não sairemos da estrada, nem entraremos nos campos ou nas plantações de uvas de vocês. E não beberemos água dos poços. Enquanto estivermos no seu país, ficaremos na estrada principal.

[[v4-20-18]]

^<<v4-20-18,18>>^ Porém o rei de Edom respondeu: — Nós não vamos deixar que vocês passem pelo nosso país. Se tentarem fazer isso, marcharemos contra vocês e os atacaremos.

[[v4-20-19]]

^<<v4-20-19,19>>^ Então o povo de Israel disse: — Ficaremos na estrada principal e, se nós ou os nossos animais beberem água de vocês, pagaremos o preço dela. Somente queremos passar a pé.

[[v4-20-20]]

^<<v4-20-20,20>>^ O rei de Edom respondeu: — Não. Vocês não passarão! Aí os edomitas vieram com um exército poderoso para atacar o povo de Israel.

[[v4-20-21]]

^<<v4-20-21,21>>^ Assim, os edomitas não deixaram que os israelitas passassem pelo seu país, e por isso os israelitas foram por outro caminho.

[[v4-20-22]]

^<<v4-20-22,22>>^ Todo o povo de Israel saiu da cidade de Cades e chegou até o monte Hor,

[[v4-20-23]]

^<<v4-20-23,23>>^ na fronteira de Edom. Ali o Senhor  Deus disse a Moisés e a Arão:

[[v4-20-24]]

^<<v4-20-24,24>>^ — Arão não entrará na terra que eu prometi dar aos israelitas. Ele vai morrer porque, no caso da água de Meribá, vocês se revoltaram contra as minhas ordens.

[[v4-20-25]]

^<<v4-20-25,25>>^ Traga Arão e Eleazar, o filho dele, e mande que subam o monte Hor.

[[v4-20-26]]

^<<v4-20-26,26>>^ Depois tire as roupas de Arão e vista em Eleazar. Arão vai morrer ali.

[[v4-20-27]]

^<<v4-20-27,27>>^ Moisés fez como o Senhor  havia mandado. Eles subiram o monte Hor diante de todo o povo.

[[v4-20-28]]

^<<v4-20-28,28>>^ Moisés tirou as roupas de sacerdote que Arão vestia e pôs em Eleazar. E Arão morreu bem no alto do monte. Depois Moisés e Eleazar desceram dali.

[[v4-20-29]]

^<<v4-20-29,29>>^ Quando o povo soube que Arão havia morrido, todos ficaram de luto trinta dias.

'''

xref:004-numeros/004-numeros-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numeros/004-numeros-021.adoc#v4-21-0[Próximo Capítulo &#62;]