include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-30-1]]

^<<v4-30-1,1>>^ Moisés disse aos chefes das tribos  dos israelitas o seguinte: — O que o Senhor  Deus ordenou é isto:

[[v4-30-2]]

^<<v4-30-2,2>>^ Quando alguém prometer dar alguma coisa ao Senhor  ou jurar que fará ou deixará de fazer qualquer coisa, deverá cumprir a palavra e fazer tudo o que tiver prometido.

[[v4-30-3]]

^<<v4-30-3,3>>^ — Quando uma moça que ainda estiver morando na casa do seu pai prometer dar alguma coisa a Deus, o Senhor , ou jurar que fará ou deixará de fazer qualquer coisa,

[[v4-30-4]]

^<<v4-30-4,4>>^ se o pai, sabendo disso, não disser nada, então ela deverá fazer tudo o que prometeu ou jurou.

[[v4-30-5]]

^<<v4-30-5,5>>^ Mas, se o pai, logo que souber disso, a proibir de cumprir o que havia prometido, então ela não precisará cumprir a sua palavra. O Senhor  a perdoará, pois o pai não a deixou cumprir o que ela havia prometido.

[[v4-30-6]]

^<<v4-30-6,6>>^ — Se uma moça solteira prometer alguma coisa a Deus, sabendo o que está fazendo ou sem pensar, ou jurar que fará ou deixará de fazer qualquer coisa, e depois casar,

[[v4-30-7]]

^<<v4-30-7,7>>^ e, se o marido, sabendo disso, não disser nada, então ela deverá fazer tudo o que prometeu ou jurou.

[[v4-30-8]]

^<<v4-30-8,8>>^ Mas, se o marido, logo que souber disso, a proibir de cumprir o que tinha prometido, então ela não precisará cumprir a sua palavra. O Senhor  a perdoará.

[[v4-30-9]]

^<<v4-30-9,9>>^ — Tanto as viúvas como as divorciadas deverão dar o que prometeram a Deus, o Senhor , e cumprir o que juraram que fariam ou deixariam de fazer.

[[v4-30-10]]

^<<v4-30-10,10>>^ — Se uma mulher casada prometer alguma coisa a Deus ou jurar que fará ou deixará de fazer qualquer coisa,

[[v4-30-11]]

^<<v4-30-11,11>>^ e, se o marido, sabendo disso, não disser nada, então ela deverá cumprir tudo o que prometeu ou jurou.

[[v4-30-12]]

^<<v4-30-12,12>>^ Mas, se o marido, logo que souber disso, a proibir de cumprir o que prometeu, então ela não precisará cumprir a sua palavra. O Senhor  a perdoará, pois o marido não a deixou cumprir o que ela havia prometido.

[[v4-30-13]]

^<<v4-30-13,13>>^ O marido tem o direito de confirmar ou de anular qualquer promessa ou juramento que ela tenha feito.

[[v4-30-14]]

^<<v4-30-14,14>>^ Mas, se até o dia seguinte o marido não disser nada a ela a respeito do assunto, então ela deverá fazer tudo o que prometeu ou jurou. O marido confirmou o juramento, pois não disse nada a ela logo que soube do caso.

[[v4-30-15]]

^<<v4-30-15,15>>^ Porém, se mais tarde o marido anular o que ela prometeu, será ele o castigado, e não ela.

[[v4-30-16]]

^<<v4-30-16,16>>^ São esses os regulamentos que o Senhor  deu a Moisés a respeito de promessas feitas por moças solteiras e por mulheres casadas.

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]