include::./index.adoc[]

[[v4-22-0]]
=== Números, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-22-1]]

^<<v4-22-1,1>>^ Os israelitas partiram e acamparam nas planícies de Moabe, a leste do rio Jordão e na altura de Jericó, que ficava no outro lado do rio.

[[v4-22-2]]

^<<v4-22-2,2>>^ Quando o rei de Moabe, Balaque, filho de Zipor, soube de tudo o que os israelitas haviam feito com os amorreus,

[[v4-22-3]]

^<<v4-22-3,3>>^ ficou apavorado com os israelitas porque eles eram muitos. De fato, o povo de Moabe ficou com muito medo dos israelitas.

[[v4-22-4]]

^<<v4-22-4,4>>^ Os moabitas disseram aos chefes dos midianitas: — Agora essa multidão vai devorar tudo ao redor de nós, como um boi que come a grama do pasto. Então o rei Balaque

[[v4-22-5]]

^<<v4-22-5,5>>^ mandou chamar Balaão, filho de Beor, que estava em Petor, perto do rio Eufrates, no território de Amave. Os mensageiros foram dizer o seguinte a Balaão: "Um povo inteiro saiu do Egito, está espalhado por toda a terra e agora veio morar perto de mim.

[[v4-22-6]]

^<<v4-22-6,6>>^ Eu lhe peço que venha logo para amaldiçoar esse povo, pois eles são mais poderosos do que eu. Talvez assim eu possa derrotá-los e expulsá-los daqui. Eu sei que, quando você abençoa alguém, esse alguém fica abençoado e, se você amaldiçoa, fica amaldiçoado."

[[v4-22-7]]

^<<v4-22-7,7>>^ Então os chefes moabitas e midianitas foram, levando consigo dinheiro para pagar as maldições. Eles chegaram ao lugar onde Balaão estava e entregaram a mensagem de Balaque.

[[v4-22-8]]

^<<v4-22-8,8>>^ Balaão respondeu o seguinte: — Fiquem aqui esta noite, e amanhã eu contarei a vocês o que o Senhor  me disser. Então os chefes moabitas ficaram com Balaão.

[[v4-22-9]]

^<<v4-22-9,9>>^ Deus veio falar com ele e perguntou: — Quem são esses homens que estão com você?

[[v4-22-10]]

^<<v4-22-10,10>>^ Balaão respondeu: — Balaque, o rei dos moabitas, me mandou dizer

[[v4-22-11]]

^<<v4-22-11,11>>^ que um povo inteiro saiu do Egito e está espalhado por toda a terra. Balaque quer que eu vá agora mesmo e amaldiçoe essa gente, para ver se assim pode derrotá-los e expulsá-los.

[[v4-22-12]]

^<<v4-22-12,12>>^ Deus disse a Balaão: — Não vá com eles, nem amaldiçoe o povo de Israel, pois é um povo abençoado.

[[v4-22-13]]

^<<v4-22-13,13>>^ De manhã Balaão se levantou e disse aos chefes que Balaque tinha enviado: — Voltem para a sua terra, pois o Senhor  não está deixando que eu vá com vocês.

[[v4-22-14]]

^<<v4-22-14,14>>^ Então eles voltaram e foram falar com Balaque. E disseram: — Balaão não quis vir com a gente.

[[v4-22-15]]

^<<v4-22-15,15>>^ Aí Balaque mandou-lhe outros chefes, mais numerosos e mais importantes do que os primeiros.

[[v4-22-16]]

^<<v4-22-16,16>>^ Eles foram falar com Balaão e disseram: — Eu, Balaque, filho de Zipor, peço-lhe que venha logo até aqui!

[[v4-22-17]]

^<<v4-22-17,17>>^ Como pagamento eu lhe darei muitas riquezas e tudo o mais que você quiser. Por favor, venha e me faça o favor de amaldiçoar este povo.

[[v4-22-18]]

^<<v4-22-18,18>>^ Balaão respondeu: — Mesmo que Balaque me desse todo o ouro e toda a prata do seu palácio, eu não poderia fazer coisa alguma, grande ou pequena, que fosse contra as ordens do Senhor , meu Deus.

[[v4-22-19]]

^<<v4-22-19,19>>^ Mas agora peço que vocês também fiquem aqui esta noite para que eu possa saber se o Senhor  tem mais alguma coisa para me dizer.

[[v4-22-20]]

^<<v4-22-20,20>>^ Durante a noite o Senhor  Deus apareceu a Balaão e disse: — Já que esses homens vieram chamá-lo, apronte-se e vá com eles. Mas faça apenas o que eu disser.

[[v4-22-21]]

^<<v4-22-21,21>>^ Portanto, no dia seguinte Balaão se aprontou, pôs os arreios na sua jumenta e foi com os chefes moabitas.

[[v4-22-22]]

^<<v4-22-22,22>>^ Deus ficou irado  porque Balaão foi. Balaão ia montado na sua jumenta, e dois dos seus empregados o acompanhavam. De repente, o Anjo do Senhor  se pôs na frente dele no caminho, para barrar a sua passagem.

[[v4-22-23]]

^<<v4-22-23,23>>^ Quando a jumenta viu o Anjo parado no caminho, com a sua espada na mão, saiu da estrada e foi para o campo. Aí Balaão bateu na jumenta e a trouxe de novo para a estrada.

[[v4-22-24]]

^<<v4-22-24,24>>^ Então o Anjo do Senhor  ficou numa parte estreita do caminho, entre duas plantações de uvas, onde havia um muro de pedra de cada lado.

[[v4-22-25]]

^<<v4-22-25,25>>^ Quando a jumenta viu o Anjo, ela se encostou no muro, apertando o pé de Balaão. Por isso Balaão bateu de novo na jumenta.

[[v4-22-26]]

^<<v4-22-26,26>>^ Depois o Anjo do Senhor  foi adiante e ficou num lugar mais estreito ainda, onde não havia jeito de se desviar nem para a direita nem para a esquerda.

[[v4-22-27]]

^<<v4-22-27,27>>^ A jumenta viu o Anjo e se deitou no chão. Balaão ficou com tanta raiva, que surrou a jumenta com a vara.

[[v4-22-28]]

^<<v4-22-28,28>>^ Aí o Senhor  fez a jumenta falar, e ela disse a Balaão: — O que foi que eu fiz contra você? Por que é que você já me bateu três vezes?

[[v4-22-29]]

^<<v4-22-29,29>>^ Ele respondeu: — Foi porque você caçoou de mim. Se eu tivesse uma espada na mão, mataria você agora mesmo!

[[v4-22-30]]

^<<v4-22-30,30>>^ Então a jumenta disse a Balaão: — Por acaso não sou a sua jumenta, em que você tem montado toda a sua vida? Será que tenho o costume de fazer isso com você? — Não — respondeu ele.

[[v4-22-31]]

^<<v4-22-31,31>>^ Aí o Senhor  Deus fez com que Balaão visse o Anjo, que estava no caminho com a espada na mão. Balaão se ajoelhou e encostou o rosto no chão.

[[v4-22-32]]

^<<v4-22-32,32>>^ O Anjo do Senhor  disse: — Por que você bateu três vezes na jumenta? Eu é que vim como se fosse seu inimigo, para fazer você voltar, pois você não devia estar fazendo esta viagem.

[[v4-22-33]]

^<<v4-22-33,33>>^ Mas a sua jumenta me viu e se desviou três vezes de mim. Se ela não tivesse feito isso, eu já teria matado você, e ela teria ficado viva.

[[v4-22-34]]

^<<v4-22-34,34>>^ Então Balaão disse ao Anjo: — Eu pequei. Não sabia que o senhor estava no caminho para me fazer parar. Porém, se agora o senhor acha que não devo continuar a viagem, eu voltarei para casa.

[[v4-22-35]]

^<<v4-22-35,35>>^ O Anjo respondeu: — Vá com esses homens; mas você falará somente aquilo que eu lhe disser. Assim, Balaão foi com os chefes enviados por Balaque.

[[v4-22-36]]

^<<v4-22-36,36>>^ Quando Balaque soube que Balaão estava chegando, foi encontrar-se com ele em Ar, uma cidade que fica na beira do rio Arnom, na fronteira de Moabe.

[[v4-22-37]]

^<<v4-22-37,37>>^ Balaque perguntou: — Por que você não quis vir quando mandei chamá-lo da primeira vez? Será que você estava pensando que eu não poderia lhe pagar bem?

[[v4-22-38]]

^<<v4-22-38,38>>^ Balaão respondeu: — Mas eu estou aqui com o senhor, não é? Porém não posso dizer nada por minha própria conta; só posso dizer o que Deus ordenar e nada mais.

[[v4-22-39]]

^<<v4-22-39,39>>^ Assim, Balaão foi com Balaque para a cidade de Huzote,

[[v4-22-40]]

^<<v4-22-40,40>>^ onde Balaque ofereceu em sacrifício  touros e ovelhas e deu uma parte da carne a Balaão e aos chefes que estavam com ele.

[[v4-22-41]]

^<<v4-22-41,41>>^ No dia seguinte de manhã, Balaque levou Balaão a Bamote-Baal, de onde Balaão podia ver uma parte do povo de Israel.

'''

xref:004-numeros/004-numeros-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numeros/004-numeros-023.adoc#v4-23-0[Próximo Capítulo &#62;]