include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-4-1]]

^<<v4-4-1,1>>^ O Senhor  Deus disse a Moisés:

[[v4-4-2]]

^<<v4-4-2,2>>^ — Faça a contagem dos levitas  descendentes de Coate, por grupos de famílias e por famílias.

[[v4-4-3]]

^<<v4-4-3,3>>^ E registre todos os homens de trinta a cinquenta anos de idade que tiverem capacidade para trabalhar na Tenda Sagrada .

[[v4-4-4]]

^<<v4-4-4,4>>^ O serviço dos coatitas na Tenda é o de cuidar das coisas santíssimas.

[[v4-4-5]]

^<<v4-4-5,5>>^ — Quando o acampamento for desarmado, Arão e os seus filhos entrarão na Tenda, tirarão a cortina que está em frente da arca da aliança  e cobrirão a arca com ela.

[[v4-4-6]]

^<<v4-4-6,6>>^ Eles porão em cima dela uma coberta feita de peles finas e sobre essa coberta estenderão um pano azul; e depois enfiarão os cabos nas argolas da arca.

[[v4-4-7]]

^<<v4-4-7,7>>^ — Eles estenderão um pano azul em cima da mesa onde são colocados os pães oferecidos ao Senhor  e colocarão sobre ela os pratos, as taças de incenso, as taças das ofertas e os jarros para as ofertas de vinho. Em cima da mesa sempre deverá haver pão.

[[v4-4-8]]

^<<v4-4-8,8>>^ Depois estenderão por cima de tudo isso um pano vermelho. E por cima desse pano colocarão a coberta feita de peles finas; em seguida enfiarão os cabos nas argolas da mesa.

[[v4-4-9]]

^<<v4-4-9,9>>^ — Pegarão um pano azul e cobrirão o candelabro  com as suas lamparinas, as tesouras de cortar pavios de lamparinas, os apagadores e as vasilhas necessárias para distribuir o azeite.

[[v4-4-10]]

^<<v4-4-10,10>>^ Depois embrulharão tudo isso numa coberta feita de peles finas e colocarão sobre os cabos para carregar.

[[v4-4-11]]

^<<v4-4-11,11>>^ Em cima do altar de ouro estenderão um pano azul e por cima colocarão uma coberta feita de peles finas. Em seguida enfiarão os cabos nas argolas do altar.

[[v4-4-12]]

^<<v4-4-12,12>>^ Depois pegarão todos os objetos usados no Lugar Santo , embrulharão num pano azul, cobrirão com uma coberta feita de peles finas e os colocarão sobre os cabos para carregá-los.

[[v4-4-13]]

^<<v4-4-13,13>>^ — Eles tirarão as cinzas do altar e estenderão por cima dele um pano vermelho.

[[v4-4-14]]

^<<v4-4-14,14>>^ Colocarão sobre ele todos os objetos usados no serviço do altar: os braseiros, os garfos, as pás e as bacias. E por cima estenderão uma coberta feita de peles finas. Em seguida colocarão os cabos nas argolas do altar.

[[v4-4-15]]

^<<v4-4-15,15>>^ Quando o acampamento for desarmado, os descendentes de Coate virão para pegar os objetos sagrados somente depois que Arão e os seus filhos tiverem acabado de cobrir a Tenda e todos os seus objetos. O grupo de famílias de Coate não deverá tocar nos objetos sagrados; se fizerem isso, eles morrerão . — São essas as coisas da Tenda que o grupo de famílias de Coate deverá levar.

[[v4-4-16]]

^<<v4-4-16,16>>^ — Eleazar, filho do sacerdote Arão, será o responsável pela Tenda e pelo azeite das lamparinas, pelo incenso, pelas ofertas de cereais e pelo azeite de ungir . Será ele mesmo o responsável pela Tenda e por todos os seus objetos.

[[v4-4-17]]

^<<v4-4-17,17>>^ O Senhor  Deus disse a Moisés e a Arão:

[[v4-4-18]]

^<<v4-4-18,18>>^ — Não deixem que as famílias de Coate morram

[[v4-4-19]]

^<<v4-4-19,19>>^ por chegarem perto desses objetos sagrados. Para evitar que isso aconteça, Arão e os seus filhos entrarão na Tenda e dirão a cada homem o que fazer e o que carregar.

[[v4-4-20]]

^<<v4-4-20,20>>^ Porém os coatitas não deverão entrar, nem por um instante, para ver as coisas santas; se fizerem isso, eles morrerão.

[[v4-4-21]]

^<<v4-4-21,21>>^ O Senhor  Deus disse ainda a Moisés:

[[v4-4-22]]

^<<v4-4-22,22>>^ — Faça a contagem dos descendentes de Gérson, por grupos de famílias e por famílias.

[[v4-4-23]]

^<<v4-4-23,23>>^ E registre todos os homens de trinta a cinquenta anos de idade que tiverem capacidade para trabalhar na Tenda Sagrada .

[[v4-4-24]]

^<<v4-4-24,24>>^ O serviço dos gersonitas é trabalhar na Tenda e carregar cargas.

[[v4-4-25]]

^<<v4-4-25,25>>^ Eles levarão a Tenda, as coberturas de dentro e de fora, a coberta de peles finas e a cortina da entrada.

[[v4-4-26]]

^<<v4-4-26,26>>^ Levarão também as cortinas do pátio, a cortina da porta do pátio que está ao redor da Tenda e do altar, as suas cordas e todos os objetos que precisam para o seu trabalho.

[[v4-4-27]]

^<<v4-4-27,27>>^ Todo o serviço dos gersonitas, o que eles deverão levar e fazer, estará debaixo das ordens de Arão e dos seus filhos. Estes darão ordens a respeito de tudo o que eles devem carregar.

[[v4-4-28]]

^<<v4-4-28,28>>^ É esse o serviço que o grupo de famílias de Gérson fará na Tenda; o serviço será dirigido por Itamar, filho do sacerdote Arão.

[[v4-4-29]]

^<<v4-4-29,29>>^ O Senhor  disse também a Moisés: — Faça a contagem dos descendentes de Merari, por famílias e por grupos de famílias,

[[v4-4-30]]

^<<v4-4-30,30>>^ e registre todos os homens de trinta a cinquenta anos de idade que tiverem capacidade para trabalhar na Tenda Sagrada .

[[v4-4-31]]

^<<v4-4-31,31>>^ O que terão de levar, de acordo com o serviço deles na Tenda, é o seguinte: as tábuas, os cabos, as colunas e as bases da Tenda;

[[v4-4-32]]

^<<v4-4-32,32>>^ as colunas do pátio que fica ao redor da Tenda, as suas bases, as estacas e as cordas, com todos os seus objetos e com tudo o que pertence ao seu serviço. Entregue a cada homem uma lista das coisas que ele deve levar.

[[v4-4-33]]

^<<v4-4-33,33>>^ É essa a responsabilidade do grupo de famílias de Merari, de acordo com o serviço deles na Tenda. Esse serviço será dirigido por Itamar, filho do sacerdote Arão.

[[v4-4-34]]

^<<v4-4-34,34>>^ Conforme o Senhor  havia ordenado, Moisés, Arão e os líderes do povo fizeram a contagem dos três grupos de famílias levitas , isto é, de Coate, de Gérson e de Merari. Eles fizeram isso por grupos menores de famílias e por famílias e registraram todos os homens de trinta a cinquenta anos de idade que tinham capacidade para trabalhar na Tenda Sagrada . O número de coatitas foi de dois mil setecentos e cinquenta homens; de gersonitas, dois mil seiscentos e trinta; e de meraritas, três mil e duzentos. O total de todos eles foi de oito mil quinhentos e oitenta homens.

[[v4-4-35]]

^<<v4-4-35,35>>^ Conforme o Senhor  havia ordenado, Moisés, Arão e os líderes do povo fizeram a contagem dos três grupos de famílias levitas , isto é, de Coate, de Gérson e de Merari. Eles fizeram isso por grupos menores de famílias e por famílias e registraram todos os homens de trinta a cinquenta anos de idade que tinham capacidade para trabalhar na Tenda Sagrada . O número de coatitas foi de dois mil setecentos e cinquenta homens; de gersonitas, dois mil seiscentos e trinta; e de meraritas, três mil e duzentos. O total de todos eles foi de oito mil quinhentos e oitenta homens.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]