include::./index.adoc[]

[[v4-34-0]]
=== Números, 34
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-34-1]]

^<<v4-34-1,1>>^ O Senhor  Deus mandou que Moisés

[[v4-34-2]]

^<<v4-34-2,2>>^ desse aos israelitas as seguintes ordens: — Quando entrarem em Canaã, a terra que estou dando a vocês, as fronteiras serão estas:

[[v4-34-3]]

^<<v4-34-3,3>>^ — A fronteira do Sul irá desde o deserto de Zim ao longo da fronteira de Edom. No Leste ela começará na ponta sul do mar Morto.

[[v4-34-4]]

^<<v4-34-4,4>>^ Depois voltará para o sul, na direção da subida de Acrabim, e passará por Zim até chegar a Cades-Barneia. Em seguida passará por Hazar-Adar até chegar a Azmom

[[v4-34-5]]

^<<v4-34-5,5>>^ e de Azmom até o ribeirão que faz fronteira com o Egito e terminará no mar Mediterrâneo.

[[v4-34-6]]

^<<v4-34-6,6>>^ — A fronteira do Oeste será o mar Mediterrâneo.

[[v4-34-7]]

^<<v4-34-7,7>>^ — A fronteira do Norte irá desde o mar Mediterrâneo até o monte Hor

[[v4-34-8]]

^<<v4-34-8,8>>^ e dali até a subida de Hamate e depois até Zedade.

[[v4-34-9]]

^<<v4-34-9,9>>^ De Zedade, essa fronteira do Norte seguirá até Zifrom e acabará em Hazar-Enã.

[[v4-34-10]]

^<<v4-34-10,10>>^ — A fronteira do Leste irá desde Hazar-Enã até Sefã

[[v4-34-11]]

^<<v4-34-11,11>>^ e de Sefã até Ribla, que fica a leste de Aim. Dali a fronteira descerá pelo leste do lago da Galileia

[[v4-34-12]]

^<<v4-34-12,12>>^ e seguirá pelo rio Jordão até terminar no mar Morto. — Essas serão as quatro fronteiras do país de vocês.

[[v4-34-13]]

^<<v4-34-13,13>>^ Então Moisés deu estas ordens aos israelitas: — Esta é a terra que vocês vão repartir por sorteio , este é o país que o Senhor  Deus mandou dar às nove tribos  e meia.

[[v4-34-14]]

^<<v4-34-14,14>>^ Isso porque as duas tribos e meia, isto é, as tribos de Gade e de Rúben e metade da tribo de Manassés, já receberam, por grupos de famílias, a terra que pertence a elas, no lado leste do rio Jordão, na altura de Jericó, que ficava no outro lado do rio.

[[v4-34-15]]

^<<v4-34-15,15>>^ Isso porque as duas tribos e meia, isto é, as tribos de Gade e de Rúben e metade da tribo de Manassés, já receberam, por grupos de famílias, a terra que pertence a elas, no lado leste do rio Jordão, na altura de Jericó, que ficava no outro lado do rio.

[[v4-34-16]]

^<<v4-34-16,16>>^ O Senhor  Deus disse a Moisés:

[[v4-34-17]]

^<<v4-34-17,17>>^ — O sacerdote Eleazar e Josué, filho de Num, vão repartir a terra entre o povo.

[[v4-34-18]]

^<<v4-34-18,18>>^ Escolham também um chefe de cada tribo  para ajudar a dividi-la.

[[v4-34-19]]

^<<v4-34-19,19>>^ Os homens que devem ser chamados são os seguintes:

'''

xref:004-numeros/004-numeros-033.adoc#v4-33-0[&#60; Capítulo Anterior] | <<v4-34-0,Topo>> | xref:004-numeros/004-numeros-035.adoc#v4-35-0[Próximo Capítulo &#62;]