include::./index.adoc[]

[[v4-13-0]]
=== Números, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-13-1]]

^<<v4-13-1,1>>^ O Senhor  Deus disse a Moisés:

[[v4-13-2]]

^<<v4-13-2,2>>^ — Mande alguns homens para espionar a terra de Canaã, a terra que eu vou dar aos israelitas. Em cada tribo  escolha um homem que seja líder.

[[v4-13-3]]

^<<v4-13-3,3>>^ Do deserto de Parã Moisés enviou os espiões, de acordo com as ordens de Deus, o Senhor . Todos eram chefes de tribos do povo de Israel.

[[v4-13-4]]

^<<v4-13-4,4>>^ São estes os seus nomes:

[[v4-13-5]]

^<<v4-13-5,5>>^ São estes os seus nomes:

[[v4-13-6]]

^<<v4-13-6,6>>^ São estes os seus nomes:

[[v4-13-7]]

^<<v4-13-7,7>>^ São estes os seus nomes:

[[v4-13-8]]

^<<v4-13-8,8>>^ São estes os seus nomes:

[[v4-13-9]]

^<<v4-13-9,9>>^ São estes os seus nomes:

[[v4-13-10]]

^<<v4-13-10,10>>^ São estes os seus nomes:

[[v4-13-11]]

^<<v4-13-11,11>>^ São estes os seus nomes:

[[v4-13-12]]

^<<v4-13-12,12>>^ São estes os seus nomes:

[[v4-13-13]]

^<<v4-13-13,13>>^ São estes os seus nomes:

[[v4-13-14]]

^<<v4-13-14,14>>^ São estes os seus nomes:

[[v4-13-15]]

^<<v4-13-15,15>>^ São estes os seus nomes:

[[v4-13-16]]

^<<v4-13-16,16>>^ São esses os nomes dos homens que Moisés mandou espionar a terra. Ele mudou o nome de Oseias, filho de Num, para Josué.

[[v4-13-17]]

^<<v4-13-17,17>>^ Quando Moisés os mandou espionar a terra de Canaã, disse a esses homens o seguinte: — Vão pela região sul e subam pelas montanhas.

[[v4-13-18]]

^<<v4-13-18,18>>^ Vejam bem que terra é essa. Vejam também se o povo que mora nela é forte ou fraco, se são poucos ou muitos.

[[v4-13-19]]

^<<v4-13-19,19>>^ Vejam se a terra onde esse povo mora é boa ou ruim, se as suas cidades têm muralhas ou não.

[[v4-13-20]]

^<<v4-13-20,20>>^ Examinem também a qualidade da terra, se é boa para plantar ou não. Vejam se há matas. Tenham coragem e tragam algumas frutas da terra (Estava na época da primeira colheita de uvas.).

[[v4-13-21]]

^<<v4-13-21,21>>^ Assim, os homens saíram e espionaram a terra desde o deserto de Zim até Reobe, perto da subida de Hamate.

[[v4-13-22]]

^<<v4-13-22,22>>^ Eles subiram pela região sul e foram até Hebrom. Ali viviam Aimã, Sesai e Talmai, descendentes de uma raça de gigantes chamados anaquins  (Hebrom tinha sido construída sete anos antes de Zoã, no Egito.).

'''

xref:004-numeros/004-numeros-012.adoc#v4-12-0[&#60; Capítulo Anterior] | <<v4-13-0,Topo>> | xref:004-numeros/004-numeros-014.adoc#v4-14-0[Próximo Capítulo &#62;]