include::./index.adoc[]

[[v4-3-0]]
=== Números, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-3-1]]

^<<v4-3-1,1>>^ Eram estes os descendentes de Arão e de Moisés no tempo em que o Senhor  falou com Moisés no monte Sinai.

[[v4-3-2]]

^<<v4-3-2,2>>^ Os nomes dos filhos de Arão são os seguintes: Nadabe, o mais velho; depois Abiú, Eleazar e Itamar.

[[v4-3-3]]

^<<v4-3-3,3>>^ Eles foram ungidos  e ordenados  para servir como sacerdotes.

[[v4-3-4]]

^<<v4-3-4,4>>^ Porém Nadabe e Abiú foram mortos quando, no deserto do Sinai, estavam oferecendo a Deus, o Senhor , fogo que não era sagrado. Eles não tinham filhos, e por isso Eleazar e Itamar serviram como sacerdotes durante a vida de Arão.

[[v4-3-5]]

^<<v4-3-5,5>>^ O Senhor  Deus disse a Moisés:

[[v4-3-6]]

^<<v4-3-6,6>>^ — Mande chamar a tribo  de Levi e ponha os seus membros para ajudarem Arão, o sacerdote, no serviço religioso.

[[v4-3-7]]

^<<v4-3-7,7>>^ Eles farão tudo o que for necessário na Tenda Sagrada  e estarão a serviço dos sacerdotes e de todo o povo.

[[v4-3-8]]

^<<v4-3-8,8>>^ Cuidarão de todos os móveis e objetos da Tenda e cumprirão as suas obrigações para com os israelitas no serviço religioso.

[[v4-3-9]]

^<<v4-3-9,9>>^ A única responsabilidade dos levitas  é servir Arão e os seus descendentes.

[[v4-3-10]]

^<<v4-3-10,10>>^ Mas você ordenará a Arão e aos seus descendentes que cuidem somente dos seus serviços como sacerdotes. Qualquer outro homem que tentar fazer esse serviço será condenado à morte.

[[v4-3-11]]

^<<v4-3-11,11>>^ O Senhor  Deus disse mais a Moisés:

[[v4-3-12]]

^<<v4-3-12,12>>^ — Os levitas agora são meus. Quando matei os primeiros filhos dos egípcios, eu separei para mim todos os primeiros filhos de cada família israelita e as primeiras crias dos animais. E agora, em vez de ter os primeiros filhos do povo de Israel, eu tenho os levitas. Eles são meus. Eu sou Deus, o Senhor .

[[v4-3-13]]

^<<v4-3-13,13>>^ — Os levitas agora são meus. Quando matei os primeiros filhos dos egípcios, eu separei para mim todos os primeiros filhos de cada família israelita e as primeiras crias dos animais. E agora, em vez de ter os primeiros filhos do povo de Israel, eu tenho os levitas. Eles são meus. Eu sou Deus, o Senhor .

[[v4-3-14]]

^<<v4-3-14,14>>^ No deserto do Sinai o Senhor  Deus mandou que Moisés

[[v4-3-15]]

^<<v4-3-15,15>>^ registrasse os levitas  por grupos de famílias e por famílias, todos os do sexo masculino da idade de um mês para cima.

[[v4-3-16]]

^<<v4-3-16,16>>^ E Moisés os contou como o Senhor  havia mandado.

[[v4-3-17]]

^<<v4-3-17,17>>^ Levi tinha três filhos: Gérson, Coate e Merari,

[[v4-3-18]]

^<<v4-3-18,18>>^ que foram os antepassados dos grupos de famílias que têm os nomes deles. Gérson tinha dois filhos: Libni e Simei. Coate tinha quatro filhos: Anrão, Isar, Hebrom e Uziel. E Merari tinha dois filhos: Mali e Musi. Eles são os antepassados das famílias levitas que têm os nomes deles.

[[v4-3-19]]

^<<v4-3-19,19>>^ que foram os antepassados dos grupos de famílias que têm os nomes deles. Gérson tinha dois filhos: Libni e Simei. Coate tinha quatro filhos: Anrão, Isar, Hebrom e Uziel. E Merari tinha dois filhos: Mali e Musi. Eles são os antepassados das famílias levitas que têm os nomes deles.

[[v4-3-20]]

^<<v4-3-20,20>>^ que foram os antepassados dos grupos de famílias que têm os nomes deles. Gérson tinha dois filhos: Libni e Simei. Coate tinha quatro filhos: Anrão, Isar, Hebrom e Uziel. E Merari tinha dois filhos: Mali e Musi. Eles são os antepassados das famílias levitas que têm os nomes deles.

[[v4-3-21]]

^<<v4-3-21,21>>^ O grupo de famílias de Gérson era formado pelas famílias de Libni e de Simei.

[[v4-3-22]]

^<<v4-3-22,22>>^ O número total das pessoas do sexo masculino, contadas uma por uma, da idade de um mês para cima, foi de sete mil e quinhentas.

[[v4-3-23]]

^<<v4-3-23,23>>^ Esse grupo acampava atrás da Tenda , no lado oeste.

[[v4-3-24]]

^<<v4-3-24,24>>^ Eliasafe, filho de Lael, era o chefe desse grupo de famílias.

[[v4-3-25]]

^<<v4-3-25,25>>^ Os gersonitas cuidavam da Tenda, da sua cobertura de dentro, da cobertura de fora, das cortinas da entrada,

[[v4-3-26]]

^<<v4-3-26,26>>^ das cortinas do pátio que fica ao redor da Tenda e do altar e das cortinas da porta do pátio e das suas cordas.

[[v4-3-27]]

^<<v4-3-27,27>>^ O grupo de famílias de Coate era formado pelas famílias de Anrão, Isar, Hebrom e Uziel.

[[v4-3-28]]

^<<v4-3-28,28>>^ O número total das pessoas do sexo masculino, da idade de um mês para cima, foi de oito mil e seiscentas; e essas pessoas tinham de cuidar da Tenda.

[[v4-3-29]]

^<<v4-3-29,29>>^ Esse grupo de famílias, isto é, os coatitas, acampava no lado sul da Tenda.

[[v4-3-30]]

^<<v4-3-30,30>>^ O chefe desse grupo era Elisafã, filho de Uziel.

[[v4-3-31]]

^<<v4-3-31,31>>^ Eles cuidavam da arca da aliança , da mesa, do candelabro , dos altares, dos utensílios do Lugar Santo  e da cortina da entrada do Lugar Santíssimo . Eles cuidavam de todos esses serviços.

[[v4-3-32]]

^<<v4-3-32,32>>^ O líder dos chefes dos levitas era Eleazar, filho do sacerdote Arão. Ele era o chefe dos que faziam o serviço religioso no Lugar Santo.

[[v4-3-33]]

^<<v4-3-33,33>>^ O grupo de famílias de Merari era formado pelas famílias de Mali e Musi.

[[v4-3-34]]

^<<v4-3-34,34>>^ O número total das pessoas do sexo masculino, da idade de um mês para cima, foi de seis mil e duzentas.

[[v4-3-35]]

^<<v4-3-35,35>>^ O chefe do grupo de famílias de Merari era Zuriel, filho de Abiail. Os meraritas acampavam no lado norte da Tenda

[[v4-3-36]]

^<<v4-3-36,36>>^ e cuidavam das tábuas da Tenda, das vigas, das colunas, das bases e de todos os seus utensílios.

[[v4-3-37]]

^<<v4-3-37,37>>^ Cuidavam também das colunas que ficavam no pátio ao redor da Tenda e das suas bases, estacas e cordas.

[[v4-3-38]]

^<<v4-3-38,38>>^ Moisés, Arão e os filhos de Arão acampavam em frente da Tenda, no lado leste. Eles cuidavam dos serviços religiosos no Lugar Santo para o povo de Israel. Porém, se qualquer outro homem tentasse fazer esse serviço, devia ser condenado à morte.

[[v4-3-39]]

^<<v4-3-39,39>>^ Como o Senhor  havia ordenado, Moisés e Arão fizeram uma lista de todos os levitas do sexo masculino, da idade de um mês para cima, conforme os grupos de famílias; o total foi de vinte e dois mil.

[[v4-3-40]]

^<<v4-3-40,40>>^ O Senhor  Deus disse a Moisés: — Registre todos os primeiros filhos israelitas do sexo masculino, de um mês para cima, pois todos eles são meus.

[[v4-3-41]]

^<<v4-3-41,41>>^ Porém no lugar deles eu ponho todos os levitas  para serem meus. Eu sou Deus, o Senhor . Ponha também os animais dos levitas no lugar de todas as primeiras crias dos animais dos outros israelitas.

[[v4-3-42]]

^<<v4-3-42,42>>^ Como o Senhor  havia ordenado, Moisés registrou todos os primeiros filhos dos israelitas.

[[v4-3-43]]

^<<v4-3-43,43>>^ O total dos que foram contados, de um mês para cima, foi de vinte e dois mil duzentos e setenta e três.

[[v4-3-44]]

^<<v4-3-44,44>>^ Depois o Senhor  Deus disse a Moisés:

[[v4-3-45]]

^<<v4-3-45,45>>^ — Ponha os levitas no lugar de todos os primeiros filhos dos outros israelitas e os animais dos levitas, no lugar dos animais dos outros israelitas. Os levitas serão meus. Eu sou Deus, o Senhor .

[[v4-3-46]]

^<<v4-3-46,46>>^ Como os primeiros filhos dos israelitas são duzentos e setenta e três a mais do que os levitas, você deve pagar por eles.

[[v4-3-47]]

^<<v4-3-47,47>>^ Você pagará cinco barras de prata por pessoa e entregará esse dinheiro a Arão e aos seus filhos (De acordo com a tabela oficial, a barra de prata, o siclo, vale vinte geras.).

'''

xref:004-numeros/004-numeros-002.adoc#v4-2-0[&#60; Capítulo Anterior] | <<v4-3-0,Topo>> | xref:004-numeros/004-numeros-004.adoc#v4-4-0[Próximo Capítulo &#62;]