include::./index.adoc[]

[[v4-11-0]]
=== Números, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-11-1]]

^<<v4-11-1,1>>^ Por estarem passando por muitas dificuldades, os israelitas começaram a se queixar a Deus, o Senhor . Quando o Senhor  ouviu as suas reclamações, ficou irado  e fez cair fogo em cima deles. O fogo queimou no meio deles e destruiu uma ponta do acampamento.

[[v4-11-2]]

^<<v4-11-2,2>>^ Então o povo gritou, pedindo socorro a Moisés; Moisés orou ao Senhor , e o fogo se apagou.

[[v4-11-3]]

^<<v4-11-3,3>>^ Aí puseram naquele lugar o nome de Taberá porque ali o fogo do Senhor  havia queimado no meio deles.

[[v4-11-4]]

^<<v4-11-4,4>>^ Havia estrangeiros viajando com os israelitas. Eles estavam com muita vontade de comer carne, e até mesmo os israelitas começaram a reclamar, dizendo: — Ah, se tivéssemos um pouco de carne para comer!

[[v4-11-5]]

^<<v4-11-5,5>>^ No Egito comíamos quanto peixe queríamos, e era de graça. E que saudades dos pepinos, dos melões, das verduras, das cebolas e dos alhos!

[[v4-11-6]]

^<<v4-11-6,6>>^ Mas agora acabaram-se as nossas forças. Não há mais nada para comer, e a única coisa que vemos é esse maná !

[[v4-11-7]]

^<<v4-11-7,7>>^ (O maná era parecido com pequenas sementes brancas, meio amareladas.

[[v4-11-8]]

^<<v4-11-8,8>>^ Ele caía durante a noite, com o orvalho. No dia seguinte de manhã, o povo ia apanhá-lo em volta do acampamento. Eles o moíam em moinhos ou o socavam em pilões, cozinhavam numa panela e faziam pães achatados que tinham gosto de pão assado com azeite.)

[[v4-11-9]]

^<<v4-11-9,9>>^ Ele caía durante a noite, com o orvalho. No dia seguinte de manhã, o povo ia apanhá-lo em volta do acampamento. Eles o moíam em moinhos ou o socavam em pilões, cozinhavam numa panela e faziam pães achatados que tinham gosto de pão assado com azeite.)

[[v4-11-10]]

^<<v4-11-10,10>>^ Então Moisés ouviu o choro do povo. Cada família chorava na entrada da sua barraca. O Senhor  ficou muito irado . E Moisés também ficou aborrecido

[[v4-11-11]]

^<<v4-11-11,11>>^ e disse a Deus, o Senhor : — Por que me tens tratado tão mal? Por que estás aborrecido comigo? Por que me deste um trabalho tão pesado de dirigir todo este povo?

[[v4-11-12]]

^<<v4-11-12,12>>^ Eu não fiz este povo, nem dei à luz esta gente! Por que me pedes que faça como uma babá e os carregue no colo como criancinhas para a terra que juraste dar aos seus antepassados?

[[v4-11-13]]

^<<v4-11-13,13>>^ Onde poderia eu conseguir carne para dar a todo este povo? Eles vêm chorar perto de mim e dizem que querem comer carne.

[[v4-11-14]]

^<<v4-11-14,14>>^ Eu sozinho não posso cuidar de todo este povo; isso é demais para mim!

[[v4-11-15]]

^<<v4-11-15,15>>^ Se vais me tratar desse jeito, tem pena de mim e mata-me! Se gostas de mim, não deixes que eu continue sofrendo deste jeito!

[[v4-11-16]]

^<<v4-11-16,16>>^ O Senhor  Deus respondeu a Moisés: — Reúna para mim setenta homens, que você sabe que são líderes, entre os mais respeitados do povo de Israel; leve-os até a Tenda Sagrada  e fique ali com eles.

[[v4-11-17]]

^<<v4-11-17,17>>^ Então eu descerei e falarei com você ali; tirarei uma parte do Espírito que lhe dei e darei a eles, para que o ajudem no pesado trabalho de cuidar do povo. Assim, você não precisará fazer isso sozinho.

[[v4-11-18]]

^<<v4-11-18,18>>^ Agora diga ao povo o seguinte: "Purifiquem-se para amanhã; vocês vão comer carne. O Senhor  ouviu vocês chorando e dizendo que queriam carne e que passavam bem no Egito. Por isso o Senhor  lhes dará carne, e vocês a comerão.

[[v4-11-19]]

^<<v4-11-19,19>>^ E não comerão só um dia, nem dois, nem cinco, nem dez, nem vinte,

[[v4-11-20]]

^<<v4-11-20,20>>^ mas durante um mês inteiro, até que saia pelos seus narizes, e vocês ficarem com nojo. Pois vocês rejeitaram o Senhor , que está no meio de vocês, e se queixaram, dizendo que nunca deveriam ter saído do Egito."

[[v4-11-21]]

^<<v4-11-21,21>>^ Moisés disse: — Estou levando seiscentos mil homens, e tu dizes que vais dar a essa gente carne para comer o mês inteiro?

[[v4-11-22]]

^<<v4-11-22,22>>^ Onde haveria tantas ovelhas e vacas para matar a fim de que todos ficassem satisfeitos? Será que todos os peixes do mar juntos poderiam alimentar essa gente?

[[v4-11-23]]

^<<v4-11-23,23>>^ Porém o Senhor  Deus respondeu a Moisés: — Será que eu tenho tão pouco poder? Agora mesmo você verá se o que eu disse vai acontecer ou não.

[[v4-11-24]]

^<<v4-11-24,24>>^ Então Moisés saiu e contou ao povo o que o Senhor  tinha dito. Ele reuniu setenta líderes do povo e os pôs ao redor da Tenda.

[[v4-11-25]]

^<<v4-11-25,25>>^ Aí o Senhor  desceu na nuvem e falou com ele. Deus tirou uma parte do Espírito que tinha dado a Moisés e deu aos setenta líderes. Quando o Espírito veio sobre eles, eles começaram a falar alto como profetas ; porém isso durou pouco tempo.

[[v4-11-26]]

^<<v4-11-26,26>>^ Dois dos setenta líderes ficaram no acampamento e não foram até a Tenda Sagrada. Um se chamava Eldade, e o outro, Medade. O Espírito veio sobre eles, e eles também começaram a falar alto como profetas.

[[v4-11-27]]

^<<v4-11-27,27>>^ Então um rapaz foi correndo contar que Eldade e Medade estavam profetizando  no acampamento.

[[v4-11-28]]

^<<v4-11-28,28>>^ Aí Josué, filho de Num, que desde a sua mocidade era auxiliar de Moisés, foi logo dizendo: — Moisés, meu chefe, não deixe que eles façam isso!

[[v4-11-29]]

^<<v4-11-29,29>>^ Moisés respondeu: — Por que você está preocupado com os meus direitos, quando eu é que deveria estar? Eu gostaria que o Senhor  desse o seu Espírito a todo o seu povo e fizesse com que todos fossem profetas!

[[v4-11-30]]

^<<v4-11-30,30>>^ Depois Moisés e os setenta líderes do povo de Israel voltaram para o acampamento.

[[v4-11-31]]

^<<v4-11-31,31>>^ De repente, o Senhor  mandou um vento que trouxe do mar bandos de codornas. Elas caíram no acampamento e em volta, em todas as direções, a uma distância de uns trinta quilômetros; e cobriram o chão em montes de quase um metro de altura.

[[v4-11-32]]

^<<v4-11-32,32>>^ Assim, todo aquele dia, toda aquela noite e todo o dia seguinte o povo trabalhou catando codornas; ninguém juntou menos de mil quilos. E espalharam as codornas ao redor do acampamento para secar.

[[v4-11-33]]

^<<v4-11-33,33>>^ Quando ainda havia muita carne para comer, o Senhor  ficou irado  com o povo e os castigou com uma terrível epidemia, que matou muita gente.

[[v4-11-34]]

^<<v4-11-34,34>>^ Por isso puseram naquele lugar o nome de Quibrote-Ataavá, que quer dizer "As Sepulturas do Desejo"; pois ali foram sepultadas as pessoas que estavam loucas de vontade de comer carne.

'''

xref:004-numeros/004-numeros-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numeros/004-numeros-012.adoc#v4-12-0[Próximo Capítulo &#62;]