include::./index.adoc[]

[[v4-21-0]]
=== Números, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-21-1]]

^<<v4-21-1,1>>^ O rei cananeu de Arade, que morava na região sul de Canaã, soube que o povo de Israel vinha pelo caminho de Atarim. Ele atacou os israelitas e levou alguns deles como prisioneiros.

[[v4-21-2]]

^<<v4-21-2,2>>^ Então o povo de Israel prometeu a Deus, o Senhor , o seguinte: — Se fizeres com que derrotemos este povo, nós destruiremos completamente as suas cidades.

[[v4-21-3]]

^<<v4-21-3,3>>^ O Senhor  ouviu o pedido do povo de Israel e os ajudou a derrotar os cananeus. Assim, os israelitas os destruíram e também destruíram as suas cidades. E deram àquele lugar o nome de Horma .

[[v4-21-4]]

^<<v4-21-4,4>>^ Então os israelitas saíram do monte Hor pelo caminho que vai até o golfo de Ácaba, para dar a volta em redor da região de Edom. Mas no caminho o povo perdeu a paciência

[[v4-21-5]]

^<<v4-21-5,5>>^ e começou a falar contra Deus e contra Moisés. Eles diziam: — Por que Deus e Moisés nos tiraram do Egito? Será que foi para morrermos no deserto, onde não há pão nem água? Já estamos cansados desta comida horrível!

[[v4-21-6]]

^<<v4-21-6,6>>^ Aí o Senhor  Deus mandou cobras venenosas que se espalharam no meio do povo; e elas morderam e mataram muitos israelitas.

[[v4-21-7]]

^<<v4-21-7,7>>^ Então o povo foi falar com Moisés e disse: — Nós pecamos, pois falamos contra Deus, o Senhor , e contra você. Peça a Deus que tire essas cobras que estão no meio da gente. Moisés orou ao Senhor  em favor do povo,

[[v4-21-8]]

^<<v4-21-8,8>>^ e ele disse: — Faça uma cobra de metal e pregue num poste. Quem for mordido deverá olhar para ela e assim ficará curado.

[[v4-21-9]]

^<<v4-21-9,9>>^ Então Moisés fez uma cobra de bronze e pregou num poste. Quando alguém era mordido por uma cobra, olhava para a cobra de bronze e ficava curado.

[[v4-21-10]]

^<<v4-21-10,10>>^ Aí os israelitas partiram e acamparam em Obote.

[[v4-21-11]]

^<<v4-21-11,11>>^ Depois saíram de Obote e acamparam nas ruínas de Abarim, no deserto, a leste do território de Moabe.

[[v4-21-12]]

^<<v4-21-12,12>>^ E partiram dali e acamparam no vale de Zerede.

[[v4-21-13]]

^<<v4-21-13,13>>^ Dali eles saíram e acamparam na margem norte do rio Arnom, no deserto que vai até o território dos amorreus (O rio Arnom é a divisa do território de Moabe com o dos amorreus.).

[[v4-21-14]]

^<<v4-21-14,14>>^ É por isso que O Livro das Batalhas do Senhor  Deus diz assim: "…a cidade de Vaebe, na região de Sufa, e os vales; o rio Arnom

[[v4-21-15]]

^<<v4-21-15,15>>^ e a descida dos vales que vão até a cidade de Ar, na direção da fronteira com Moabe."

[[v4-21-16]]

^<<v4-21-16,16>>^ Dali eles foram para um lugar chamado Beer , onde o Senhor  disse a Moisés: — Reúna o povo, e eu darei água a todos.

[[v4-21-17]]

^<<v4-21-17,17>>^ Então o povo de Israel cantou esta canção: "Ó poço, faça brotar a sua água, e nós a saudaremos com uma canção!

[[v4-21-18]]

^<<v4-21-18,18>>^ Este poço foi cavado pelos líderes, foi aberto pelos chefes do povo, com os seus bastões de comando e com os seus bordões." Do deserto eles foram para Matana.

[[v4-21-19]]

^<<v4-21-19,19>>^ De Matana foram para Naaliel, de Naaliel para Bamote

[[v4-21-20]]

^<<v4-21-20,20>>^ e de Bamote para o vale que fica no território de Moabe, abaixo do pico do monte Pisga, de onde se avista o deserto.

[[v4-21-21]]

^<<v4-21-21,21>>^ Então o povo de Israel mandou mensageiros para dizerem a Seom, o rei dos amorreus, o seguinte:

[[v4-21-22]]

^<<v4-21-22,22>>^ — Deixe-nos passar pelo seu país. Não passaremos pelos campos, nem pelas plantações de uvas. Não beberemos água dos poços; caminharemos somente pela estrada principal até sairmos do seu país.

[[v4-21-23]]

^<<v4-21-23,23>>^ Porém Seom não deixou que o povo de Israel passasse pelo seu país. Pelo contrário, ele reuniu toda a sua gente e saiu para enfrentar o povo de Israel no deserto. Seom foi até Jasa e combateu contra os israelitas.

[[v4-21-24]]

^<<v4-21-24,24>>^ Mas na batalha eles mataram à espada muitos amorreus e tomaram a terra deles, desde o rio Arnom até o rio Jaboque, na fronteira com o país de Amom, na qual havia muralhas.

[[v4-21-25]]

^<<v4-21-25,25>>^ Assim, os israelitas tomaram todas essas cidades dos amorreus e ficaram morando nelas, isto é, em Hesbom e nos povoados que ficavam ao seu redor.

[[v4-21-26]]

^<<v4-21-26,26>>^ Hesbom era a cidade onde morava Seom, o rei dos amorreus. Ele tinha lutado contra o antigo rei moabita que havia tomado toda a sua terra até o rio Arnom.

[[v4-21-27]]

^<<v4-21-27,27>>^ É por isso que os poetas dizem assim: "Venham a Hesbom, a cidade do rei Seom! Ela será construída de novo, a cidade de Seom será bem-construída.

[[v4-21-28]]

^<<v4-21-28,28>>^ Pois saiu fogo de Hesbom, saiu uma chama da cidade do rei Seom. O exército foi o fogo que destruiu a cidade de Ar, em Moabe, e devorou os montes do alto Arnom.

[[v4-21-29]]

^<<v4-21-29,29>>^ Ai de vocês, moradores de Moabe! Adoradores do deus Quemos, vocês estão perdidos! O seu deus deixou que os seus soldados fugissem e que as suas filhas fossem entregues para serem escravas de Seom, o rei dos amorreus.

[[v4-21-30]]

^<<v4-21-30,30>>^ Mas agora acabou o poder de Hesbom; de Hesbom até Dibom, tudo está destruído. Nofa está em ruínas, e o fogo chegou até Medeba."

[[v4-21-31]]

^<<v4-21-31,31>>^ Assim, os israelitas ficaram morando na terra dos amorreus.

[[v4-21-32]]

^<<v4-21-32,32>>^ Depois Moisés mandou gente para espionar a cidade de Jazer. Em seguida conquistaram os povoados que ficavam ao redor de Jazer e expulsaram todos os amorreus que moravam ali.

[[v4-21-33]]

^<<v4-21-33,33>>^ Então os israelitas voltaram e subiram pelo caminho de Basã. E Ogue, rei de Basã, saiu para atacá-los em Edrei.

[[v4-21-34]]

^<<v4-21-34,34>>^ O Senhor  Deus disse a Moisés: — Não tenha medo dele, pois vou entregar nas suas mãos o rei, o seu povo e a sua terra. E você deverá fazer com ele o mesmo que fez com Seom, o rei dos amorreus, que morava em Hesbom.

[[v4-21-35]]

^<<v4-21-35,35>>^ Assim, os israelitas mataram Ogue, os seus filhos e todo o seu povo; não escapou ninguém. E tomaram a terra deles.

'''

xref:004-numeros/004-numeros-020.adoc#v4-20-0[&#60; Capítulo Anterior] | <<v4-21-0,Topo>> | xref:004-numeros/004-numeros-022.adoc#v4-22-0[Próximo Capítulo &#62;]