include::./index.adoc[]

[[v4-14-0]]
=== Números, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-14-1]]

^<<v4-14-1,1>>^ Então, naquela noite, todo o povo gritou e chorou.

[[v4-14-2]]

^<<v4-14-2,2>>^ Todos os israelitas reclamaram contra Moisés e Arão e disseram: — Seria melhor se tivéssemos morrido no Egito ou mesmo neste deserto!

[[v4-14-3]]

^<<v4-14-3,3>>^ Por que será que o Senhor  Deus nos trouxe para esta terra? Nós vamos ser mortos na guerra, e as nossas mulheres e os nossos filhos vão ser presos. Seria bem melhor voltarmos para o Egito!

[[v4-14-4]]

^<<v4-14-4,4>>^ E diziam uns aos outros: — Vamos escolher outro líder e voltemos para o Egito!

[[v4-14-5]]

^<<v4-14-5,5>>^ Então Moisés e Arão se ajoelharam e encostaram o rosto no chão diante de todo o povo.

[[v4-14-6]]

^<<v4-14-6,6>>^ E Josué, filho de Num, e Calebe, filho de Jefoné, dois dos líderes que haviam espionado a terra, rasgaram as suas roupas em sinal de tristeza

[[v4-14-7]]

^<<v4-14-7,7>>^ e disseram ao povo: — A terra que fomos espionar é muito boa mesmo.

[[v4-14-8]]

^<<v4-14-8,8>>^ Se o Senhor  Deus nos ajudar, ele fará com que entremos nela e nos dará aquela terra, uma terra boa e rica.

[[v4-14-9]]

^<<v4-14-9,9>>^ Porém não sejam rebeldes contra o Senhor  e não tenham medo do povo daquela terra. Nós os venceremos com facilidade. O Senhor  está com a gente e derrotou os deuses que os protegiam. Portanto, não tenham medo.

[[v4-14-10]]

^<<v4-14-10,10>>^ Apesar disso o povo ameaçou matá-los a pedradas, mas, de repente, todos viram a glória  do Senhor  aparecer sobre a Tenda Sagrada .

[[v4-14-11]]

^<<v4-14-11,11>>^ O Senhor  Deus disse a Moisés: — Até quando este povo vai me rejeitar? Até quando não vão crer em mim, embora eu tenha feito tantos milagres entre eles?

[[v4-14-12]]

^<<v4-14-12,12>>^ Vou mandar uma epidemia para acabar com eles, porém farei com que os descendentes de você sejam um povo maior e mais forte do que eles.

[[v4-14-13]]

^<<v4-14-13,13>>^ Mas Moisés respondeu ao Senhor : — Com o teu poder tiraste do Egito esta gente. Quando os egípcios souberem do que vais fazer com este povo,

[[v4-14-14]]

^<<v4-14-14,14>>^ eles contarão isso aos moradores desta terra. Estes já sabem que tu, ó Senhor  Deus, estás com a gente e que és visto claramente quando a tua nuvem para sobre nós. E sabem também que vais adiante de nós numa coluna de nuvem de dia e numa coluna de fogo de noite.

[[v4-14-15]]

^<<v4-14-15,15>>^ Se matares o teu povo, as nações que ouviram falar a respeito da tua fama vão dizer

[[v4-14-16]]

^<<v4-14-16,16>>^ que mataste o teu povo no deserto porque não pudeste levá-lo para a terra que prometeste dar a ele.

[[v4-14-17]]

^<<v4-14-17,17>>^ Agora, Senhor, eu te peço que mostres o teu poder e que faças o que prometeste quando disseste:

[[v4-14-18]]

^<<v4-14-18,18>>^ "Eu, o Senhor , tenho paciência e muita compaixão; eu perdoo a maldade e o pecado, porém não trato o culpado como se fosse inocente. Eu faço com que o castigo dos pecados dos pais caia sobre os seus descendentes, até os bisnetos e trinetos."

[[v4-14-19]]

^<<v4-14-19,19>>^ E agora eu te peço, ó Deus, que perdoes o pecado deste povo, de acordo com a tua grande misericórdia, como já tens feito desde o Egito até aqui.

[[v4-14-20]]

^<<v4-14-20,20>>^ O Senhor  Deus disse: — Já que você pediu, eu perdoo.

[[v4-14-21]]

^<<v4-14-21,21>>^ Mas, pela minha vida e pela minha presença gloriosa  que enche toda a terra, juro que

[[v4-14-22]]

^<<v4-14-22,22>>^ nenhum desses homens viverá para entrar naquela terra. Eles viram a minha glória  e os milagres que fiz no Egito e no deserto. No entanto dez vezes puseram à prova a minha paciência e não quiseram me obedecer.

[[v4-14-23]]

^<<v4-14-23,23>>^ Eles nunca entrarão na terra que jurei dar aos seus antepassados. Nenhum daqueles que me abandonaram verá aquela terra.

[[v4-14-24]]

^<<v4-14-24,24>>^ Mas o meu servo  Calebe tem um espírito diferente e sempre tem sido fiel a mim. Por isso eu farei com que ele entre na terra que espionou, e os seus descendentes vão possuir aquela terra.

[[v4-14-25]]

^<<v4-14-25,25>>^ Agora os amalequitas e os cananeus estão morando nos vales; portanto, amanhã voltem e vão para o deserto, na direção do golfo de Ácaba.

[[v4-14-26]]

^<<v4-14-26,26>>^ O Senhor  Deus disse a Moisés e a Arão:

[[v4-14-27]]

^<<v4-14-27,27>>^ — Eu tenho ouvido as reclamações dos israelitas. Até quando vou aguentar esse povo mau, que vive reclamando contra mim?

[[v4-14-28]]

^<<v4-14-28,28>>^ Diga a essa gente o seguinte: "Juro pela minha vida que darei o que vocês me pediram. Sou eu, o Senhor , quem está falando.

[[v4-14-29]]

^<<v4-14-29,29>>^ Vocês serão mortos, e os corpos de vocês serão espalhados pelo deserto. Vocês reclamaram contra mim, e por isso nenhum de vocês que tem vinte anos de idade ou mais entrará naquela terra.

[[v4-14-30]]

^<<v4-14-30,30>>^ Eu jurei que os faria morar lá, mas nenhum de vocês entrará naquela terra, a não ser Calebe, filho de Jefoné, e Josué, filho de Num.

[[v4-14-31]]

^<<v4-14-31,31>>^ Vocês disseram que os seus filhos seriam presos, mas eu vou levar esses filhos para a terra que vocês rejeitaram, e ali será o lar deles.

[[v4-14-32]]

^<<v4-14-32,32>>^ Porém vocês morrerão, e os corpos de vocês ficarão neste deserto,

[[v4-14-33]]

^<<v4-14-33,33>>^ onde os seus filhos vão caminhar quarenta anos. Vocês foram infiéis, e por isso eles vão sofrer, até que todos vocês morram aqui.

[[v4-14-34]]

^<<v4-14-34,34>>^ Quarenta anos vocês vão sofrer por causa dos seus pecados, conforme os quarenta dias que vocês espionaram a terra, um ano para cada dia. Vocês vão saber o que é ficar contra mim.

[[v4-14-35]]

^<<v4-14-35,35>>^ É isto o que vou fazer com todo este povo mau que se revoltou contra mim: todos vocês morrerão e serão destruídos neste deserto. Eu, o Senhor , falei."

[[v4-14-36]]

^<<v4-14-36,36>>^ Os homens que Moisés havia mandado para espionar a terra trouxeram más informações a respeito dela. E, quando voltaram, fizeram com que o povo reclamasse contra Moisés. Por isso o Senhor  fez com que fossem atacados por uma doença, e eles morreram.

[[v4-14-37]]

^<<v4-14-37,37>>^ Os homens que Moisés havia mandado para espionar a terra trouxeram más informações a respeito dela. E, quando voltaram, fizeram com que o povo reclamasse contra Moisés. Por isso o Senhor  fez com que fossem atacados por uma doença, e eles morreram.

[[v4-14-38]]

^<<v4-14-38,38>>^ Dos doze homens que foram espionar a terra, somente Josué e Calebe ficaram vivos.

[[v4-14-39]]

^<<v4-14-39,39>>^ Os israelitas ficaram muito tristes quando Moisés contou o que o Senhor  tinha dito.

[[v4-14-40]]

^<<v4-14-40,40>>^ De manhã bem cedo, começaram a entrar na região montanhosa. Eles diziam: — Agora estamos prontos para ir até o lugar que o Senhor  nos havia prometido. De fato, nós pecamos.

[[v4-14-41]]

^<<v4-14-41,41>>^ Porém Moisés respondeu: — Então por que vocês estão querendo desobedecer à ordem de Deus, o Senhor ? Isso não vai dar certo.

[[v4-14-42]]

^<<v4-14-42,42>>^ Não entrem na região montanhosa. O Senhor  não está com vocês, e os seus inimigos vão derrotá-los.

[[v4-14-43]]

^<<v4-14-43,43>>^ Os amalequitas e os cananeus estão ali para enfrentá-los e matá-los na batalha. O Senhor  não estará com vocês, pois vocês o abandonaram.

[[v4-14-44]]

^<<v4-14-44,44>>^ Mesmo assim os israelitas teimaram em querer entrar na região montanhosa, mas nem a arca da aliança  de Deus, o Senhor , nem Moisés saíram do acampamento.

'''

xref:004-numeros/004-numeros-013.adoc#v4-13-0[&#60; Capítulo Anterior] | <<v4-14-0,Topo>> | xref:004-numeros/004-numeros-015.adoc#v4-15-0[Próximo Capítulo &#62;]