include::./index.adoc[]

[[v4-33-0]]
=== Números, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v4-33-1]]

^<<v4-33-1,1>>^ São estas as caminhadas dos israelitas que saíram do Egito, grupo por grupo, debaixo das ordens de Moisés e Arão.

[[v4-33-2]]

^<<v4-33-2,2>>^ Moisés ia anotando os nomes dos lugares de onde partiam, de acordo com as ordens de Deus, o Senhor . E são estas as caminhadas conforme os lugares de partida:

[[v4-33-3]]

^<<v4-33-3,3>>^ O povo de Israel saiu do Egito no dia quinze do primeiro mês do ano, um dia depois da primeira Páscoa . Eles saíram de Ramessés de maneira vitoriosa, e todos os egípcios os viram.

[[v4-33-4]]

^<<v4-33-4,4>>^ Os egípcios estavam sepultando os seus primeiros filhos que o Senhor  havia matado. Assim, o Senhor  mostrou que era mais poderoso do que os deuses do Egito.

[[v4-33-5]]

^<<v4-33-5,5>>^ Depois de saírem de Ramessés, os israelitas acamparam em Sucote.

[[v4-33-6]]

^<<v4-33-6,6>>^ Saíram de Sucote e acamparam em Etã, que está na beira do deserto.

[[v4-33-7]]

^<<v4-33-7,7>>^ Saíram de Etã e voltaram a Pi-Hairote, que fica a leste de Baal-Zefom, e acamparam perto de Migdol.

[[v4-33-8]]

^<<v4-33-8,8>>^ Saíram de Pi-Hairote e passaram pelo meio do mar Vermelho e chegaram ao deserto de Sur. Caminharam três dias no deserto e acamparam em Mara.

[[v4-33-9]]

^<<v4-33-9,9>>^ Dali foram para Elim e acamparam ali. Em Elim havia doze fontes de água e setenta palmeiras.

[[v4-33-10]]

^<<v4-33-10,10>>^ Saíram de Elim e acamparam perto do golfo de Suez.

[[v4-33-11]]

^<<v4-33-11,11>>^ Partiram dali e acamparam no deserto de Sim.

[[v4-33-12]]

^<<v4-33-12,12>>^ Dali foram até Dofca, onde acamparam.

[[v4-33-13]]

^<<v4-33-13,13>>^ Partiram de Dofca e acamparam em Alus.

[[v4-33-14]]

^<<v4-33-14,14>>^ Depois de Alus, acamparam em Refidim. Porém ali não havia água para o povo beber.

[[v4-33-15]]

^<<v4-33-15,15>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-16]]

^<<v4-33-16,16>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-17]]

^<<v4-33-17,17>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-18]]

^<<v4-33-18,18>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-19]]

^<<v4-33-19,19>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-20]]

^<<v4-33-20,20>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-21]]

^<<v4-33-21,21>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-22]]

^<<v4-33-22,22>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-23]]

^<<v4-33-23,23>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-24]]

^<<v4-33-24,24>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-25]]

^<<v4-33-25,25>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

[[v4-33-26]]

^<<v4-33-26,26>>^ Na caminhada de Refidim até o monte Hor, eles acamparam nos seguintes lugares: deserto do Sinai, Quibrote-Ataavá, Hazerote, Ritma, Rimom-Peres, Libna, Rissa, Queelata, monte Sefer, Harada, Maquelote, Taate, Tera, Mitca, Hasmona, Moserote, Benê-Jaacã, Hor-Hagidgade, Jotbatá, Abrona, Eziom-Geber, deserto de Zim, isto é, Cades, e o monte Hor, que fica na fronteira da terra de Edom.

'''

xref:004-numeros/004-numeros-032.adoc#v4-32-0[&#60; Capítulo Anterior] | <<v4-33-0,Topo>> | xref:004-numeros/004-numeros-034.adoc#v4-34-0[Próximo Capítulo &#62;]