include::./index.adoc[]

[[v11-3-0]]
=== 1 Reis, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-3-1]]

^<<v11-3-1,1>>^ Salomão fez um acordo  com Faraó, rei do Egito, casando com a sua filha. Ele a levou para morar na Cidade de Davi  até que acabasse a construção do seu palácio e a construção do Templo e das muralhas em volta de Jerusalém.

[[v11-3-2]]

^<<v11-3-2,2>>^ Ainda não havia sido construído um templo para Deus, o Senhor , e por isso o povo ainda continuava oferecendo sacrifícios  em vários altares, nos montes.

[[v11-3-3]]

^<<v11-3-3,3>>^ Salomão amava o Senhor  e seguia os conselhos de Davi, seu pai, mas também matava animais e os oferecia em sacrifício em vários altares, nos montes.

[[v11-3-4]]

^<<v11-3-4,4>>^ Certa vez, Salomão foi a Gibeão oferecer sacrifícios porque naquele lugar estava o altar mais famoso de todos. No passado ele havia queimado ali mil animais como sacrifício a Deus.

[[v11-3-5]]

^<<v11-3-5,5>>^ Naquela noite, o Senhor  Deus apareceu num sonho a Salomão e perguntou: — O que você quer que eu lhe dê?

[[v11-3-6]]

^<<v11-3-6,6>>^ Ele respondeu: — Tu sempre mostraste grande amor por Davi, meu pai, teu servo , e ele era bom, fiel e honesto para contigo. Tu continuaste a mostrar a ele o teu grande e constante amor e lhe deste um filho que hoje governa no lugar dele.

[[v11-3-7]]

^<<v11-3-7,7>>^ Ó Senhor  Deus, tu deixaste que eu ficasse como rei no lugar do meu pai, embora eu seja muito jovem e não saiba governar.

[[v11-3-8]]

^<<v11-3-8,8>>^ Aqui estou eu no meio do povo que escolheste para ser teu, um povo que é tão numeroso, que nem pode ser contado.

[[v11-3-9]]

^<<v11-3-9,9>>^ Portanto, dá-me sabedoria para que eu possa governar o teu povo com justiça e saber a diferença entre o bem e o mal. Se não for assim, como é que eu poderei governar este teu grande povo?

[[v11-3-10]]

^<<v11-3-10,10>>^ Deus gostou de Salomão ter pedido isso

[[v11-3-11]]

^<<v11-3-11,11>>^ e disse: — Já que você pediu sabedoria para governar com justiça, em vez de pedir vida longa, ou riquezas, ou a morte dos seus inimigos,

[[v11-3-12]]

^<<v11-3-12,12>>^ eu darei o que você pediu. Darei a você sabedoria e inteligência, como ninguém teve antes de você, nem terá depois.

[[v11-3-13]]

^<<v11-3-13,13>>^ Mas lhe darei também o que não pediu: durante toda a sua vida, você terá riquezas e honras, mais do que qualquer outro rei.

[[v11-3-14]]

^<<v11-3-14,14>>^ E, se você me obedecer e guardar as minhas leis  e os meus mandamentos, como fez Davi, o seu pai, eu lhe darei uma vida longa.

[[v11-3-15]]

^<<v11-3-15,15>>^ Quando acordou, Salomão compreendeu que Deus havia falado com ele no sonho. Então foi para Jerusalém, ficou diante da arca da aliança  e apresentou a Deus ofertas de paz e sacrifícios que foram completamente queimados. Depois deu uma festa para todas as autoridades.

[[v11-3-16]]

^<<v11-3-16,16>>^ Certo dia, duas prostitutas apresentaram-se diante do rei Salomão,

[[v11-3-17]]

^<<v11-3-17,17>>^ e uma delas disse: — Ó rei Salomão! Eu e esta mulher moramos na mesma casa. Eu dei à luz um menino, e ela estava lá comigo.

[[v11-3-18]]

^<<v11-3-18,18>>^ Dois dias depois do nascimento do meu filho, ela também deu à luz um menino. Somente nós duas estávamos na casa; não havia mais ninguém lá.

[[v11-3-19]]

^<<v11-3-19,19>>^ Uma noite, ela rolou sem querer sobre o seu filho e o sufocou.

[[v11-3-20]]

^<<v11-3-20,20>>^ Então levantou-se durante a noite, enquanto eu dormia, pegou o meu filho e o colocou na cama dela. Depois colocou o menino morto nos meus braços.

[[v11-3-21]]

^<<v11-3-21,21>>^ No outro dia de manhã, quando eu me levantei para dar de mamar ao meu filho, vi que estava morto. Porém, quando reparei bem, percebi que não era o meu filho.

[[v11-3-22]]

^<<v11-3-22,22>>^ Mas a outra mulher disse: — Não é verdade. Pelo contrário, meu filho é o que está vivo, e o seu é o que está morto! E a primeira mulher respondeu: — Não é, não! A criança morta é a sua, e a viva é a minha! E foi assim que discutiram na frente do rei.

[[v11-3-23]]

^<<v11-3-23,23>>^ Então o rei Salomão disse: — Cada uma de vocês diz que a criança viva é a sua, e que a morta é da outra.

[[v11-3-24]]

^<<v11-3-24,24>>^ Então mandou buscar uma espada e, quando a trouxeram,

[[v11-3-25]]

^<<v11-3-25,25>>^ disse: — Cortem a criança viva pelo meio e deem metade para cada uma destas mulheres.

[[v11-3-26]]

^<<v11-3-26,26>>^ A verdadeira mãe do menino, com o coração cheio de amor pelo filho, disse: — Por favor, senhor, não mate o meu filho! Entregue-o a esta mulher! Mas a outra disse: — Podem cortá-lo em dois pedaços! Assim ele não será nem meu nem seu.

[[v11-3-27]]

^<<v11-3-27,27>>^ Aí Salomão disse: — Não matem a criança! Entreguem o menino à primeira mulher porque ela é a mãe dele.

[[v11-3-28]]

^<<v11-3-28,28>>^ Todo o povo de Israel soube dessa decisão do rei Salomão, e aí todos sentiram um grande respeito por ele, pois viram que Deus lhe tinha dado sabedoria para julgar com justiça.

'''

xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[Próximo Capítulo &#62;]