include::./index.adoc[]

[[v11-7-0]]
=== 1 Reis, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-7-1]]

^<<v11-7-1,1>>^ Salomão também construiu o seu palácio e levou treze anos para terminá-lo.

[[v11-7-2]]

^<<v11-7-2,2>>^ O Salão da Floresta do Líbano media quarenta e quatro metros de comprimento por vinte e dois de largura, por treze e meio de altura. Ele tinha três fileiras de colunas de cedro, havendo quinze colunas em cada fileira, com vigas de cedro que se apoiavam nelas. O teto era de cedro, estendendo-se até as despensas, que eram apoiadas pelas colunas.

[[v11-7-3]]

^<<v11-7-3,3>>^ O Salão da Floresta do Líbano media quarenta e quatro metros de comprimento por vinte e dois de largura, por treze e meio de altura. Ele tinha três fileiras de colunas de cedro, havendo quinze colunas em cada fileira, com vigas de cedro que se apoiavam nelas. O teto era de cedro, estendendo-se até as despensas, que eram apoiadas pelas colunas.

[[v11-7-4]]

^<<v11-7-4,4>>^ Nas paredes de cada lado havia três fileiras de janelas.

[[v11-7-5]]

^<<v11-7-5,5>>^ Todas as portas e todas as janelas eram quadradas, e as três fileiras de janelas de cada parede ficavam exatamente em frente às fileiras de janelas da parede do outro lado.

[[v11-7-6]]

^<<v11-7-6,6>>^ O Salão das Colunas media vinte e dois metros de comprimento por treze e meio de largura. Ele tinha um pórtico que era coberto e sustentado por colunas.

[[v11-7-7]]

^<<v11-7-7,7>>^ A Sala do Trono, também chamada de Salão do Julgamento, onde Salomão julgava as questões, era forrada de cedro desde o chão até as vigas.

[[v11-7-8]]

^<<v11-7-8,8>>^ Em outro pátio, atrás da Sala do Trono, ficava a casa onde Salomão morava. A construção era do mesmo estilo das outras. Salomão também fez uma casa do mesmo tipo para a sua esposa, a filha do rei do Egito.

[[v11-7-9]]

^<<v11-7-9,9>>^ Todas essas construções e também o grande pátio foram feitos de pedras escolhidas, desde os alicerces até a beira do telhado. As pedras foram preparadas na pedreira e cortadas sob medida, sendo os lados de dentro e de fora cortados com serras.

[[v11-7-10]]

^<<v11-7-10,10>>^ Os alicerces foram feitos com pedras grandes preparadas na pedreira; algumas tinham três metros e meio de comprimento, e outras, quatro metros e meio de comprimento.

[[v11-7-11]]

^<<v11-7-11,11>>^ Por cima delas, foram colocadas pedras caras, cortadas sob medida, e vigas de cedro.

[[v11-7-12]]

^<<v11-7-12,12>>^ O pátio do palácio, o pátio interno do Templo e a sala de entrada do Templo tinham paredes feitas com uma carreira de vigas de cedro para cada três carreiras de pedras cortadas.

[[v11-7-13]]

^<<v11-7-13,13>>^ O rei Salomão mandou buscar um homem chamado Hurã, um artífice que morava na cidade de Tiro e que era especialista em trabalhos de bronze.

[[v11-7-14]]

^<<v11-7-14,14>>^ O seu pai, que já havia morrido, era de Tiro e também havia sido artífice especializado em bronze; a sua mãe era da tribo  de Naftali. Hurã era um artífice inteligente e capaz. Ele aceitou o convite de Salomão e se encarregou de todo o trabalho em bronze.

[[v11-7-15]]

^<<v11-7-15,15>>^ Hurã fundiu duas colunas de bronze, cada uma com oito metros de altura e um metro e setenta de diâmetro, e as colocou na entrada do Templo.

[[v11-7-16]]

^<<v11-7-16,16>>^ Ele fez também dois remates de coluna, cada um com dois metros e vinte de altura, para serem colocados no alto das colunas.

[[v11-7-17]]

^<<v11-7-17,17>>^ O alto de cada coluna era enfeitado com um desenho de correntes entrelaçadas

[[v11-7-18]]

^<<v11-7-18,18>>^ e duas carreiras de romãs feitas de bronze.

[[v11-7-19]]

^<<v11-7-19,19>>^ Os remates das colunas tinham o formato de lírios, mediam um metro e oitenta de altura

[[v11-7-20]]

^<<v11-7-20,20>>^ e foram colocados numa parte redonda que ficava por cima do desenho de correntes. Em cada remate de coluna havia duzentas romãs de bronze colocadas em duas carreiras.

[[v11-7-21]]

^<<v11-7-21,21>>^ Hurã colocou essas duas colunas de bronze na frente da entrada do Templo. A que ficava no lado sul se chamava Jaquim , e a que ficava no lado norte se chamava Boaz .

[[v11-7-22]]

^<<v11-7-22,22>>^ Os remates das colunas em forma de lírios, feitos de bronze, estavam no alto das colunas. E assim foi terminado o trabalho das colunas.

[[v11-7-23]]

^<<v11-7-23,23>>^ Hurã fez um tanque redondo de bronze, com dois metros e vinte de profundidade, quatro metros e quarenta de diâmetro e treze metros e vinte de circunferência.

[[v11-7-24]]

^<<v11-7-24,24>>^ Ao redor da borda de fora do tanque havia duas carreiras de cabaças de bronze que haviam sido fundidas todas em uma só peça junto com o tanque.

[[v11-7-25]]

^<<v11-7-25,25>>^ O tanque se apoiava sobre as costas de doze touros de bronze que olhavam para fora: três olhavam para o norte, três olhavam para o oeste, três olhavam para o sul, e três olhavam para o leste.

[[v11-7-26]]

^<<v11-7-26,26>>^ A grossura das paredes do tanque era de quatro dedos. A sua borda era como a borda de um copo, curvando-se para fora como as pétalas de um lírio. A capacidade do tanque era de mais ou menos quarenta mil litros.

[[v11-7-27]]

^<<v11-7-27,27>>^ Hurã fez também dez carretas de bronze. Cada uma media um metro e oitenta de comprimento, um metro e oitenta de largura e um metro e trinta de altura.

[[v11-7-28]]

^<<v11-7-28,28>>^ Elas foram feitas de painéis quadrados, que eram montados em molduras.

[[v11-7-29]]

^<<v11-7-29,29>>^ Nesses painéis havia figuras de leões, touros e querubins . E, nas molduras acima e abaixo dos leões e dos touros, havia desenhos de espirais em relevo.

[[v11-7-30]]

^<<v11-7-30,30>>^ Cada carreta tinha quatro rodas de bronze, com eixos de bronze. Nos quatro cantos havia apoios de bronze para uma bacia; os apoios eram enfeitados com figuras de espirais em relevo.

[[v11-7-31]]

^<<v11-7-31,31>>^ No alto havia uma guarnição redonda para a bacia. Essa guarnição passava quarenta e cinco centímetros para cima do alto da carreta e dezoito centímetros para baixo, para dentro dela. Ao redor dela havia entalhes.

[[v11-7-32]]

^<<v11-7-32,32>>^ As rodas tinham sessenta e sete centímetros de altura; elas ficavam debaixo dos painéis, e os eixos eram feitos em uma só peça com as carretas.

[[v11-7-33]]

^<<v11-7-33,33>>^ As rodas eram como as rodas de uma carruagem; os seus eixos, bordas, raios e os seus cubos eram todos de bronze.

[[v11-7-34]]

^<<v11-7-34,34>>^ Havia quatro apoios nos cantos, debaixo de cada carreta, os quais formavam uma só peça com a carreta.

[[v11-7-35]]

^<<v11-7-35,35>>^ Havia uma braçadeira de vinte e dois centímetros ao redor do alto de cada carreta; os seus apoios e os painéis formavam uma só peça com a carreta.

[[v11-7-36]]

^<<v11-7-36,36>>^ Os apoios e os painéis eram enfeitados com figuras de querubins, leões e palmeiras, que cobriam todo o espaço que havia; e ao redor dessas figuras havia desenhos em espiral.

[[v11-7-37]]

^<<v11-7-37,37>>^ Foi assim, então, que as carretas foram feitas; todas elas eram iguais, tendo o mesmo tamanho e formato.

[[v11-7-38]]

^<<v11-7-38,38>>^ Hurã fez também dez bacias de bronze, uma para cada carreta. Cada bacia tinha um metro e oitenta de diâmetro, e a sua capacidade era de mais ou menos oitocentos e trinta litros.

[[v11-7-39]]

^<<v11-7-39,39>>^ Ele colocou cinco carretas no lado sul do Templo e as outras cinco no lado norte. O tanque ele colocou no canto sudeste.

[[v11-7-40]]

^<<v11-7-40,40>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo do Senhor . Esta é a lista do que ele fez: duas colunas; dois remates em forma de taças, que ficavam em cima das colunas; desenhos de correntes entrelaçadas de cada remate; quatrocentas romãs de bronze, em duas carreiras de cem, ao redor do desenho de cada remate; dez carretas; dez bacias; um tanque; doze touros que sustentavam o tanque; caldeirões, pás e bacias. Todos os objetos destinados ao Templo que Hurã fez para o rei Salomão eram de bronze polido.

[[v11-7-41]]

^<<v11-7-41,41>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo do Senhor . Esta é a lista do que ele fez:

[[v11-7-42]]

^<<v11-7-42,42>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo do Senhor . Esta é a lista do que ele fez:

[[v11-7-43]]

^<<v11-7-43,43>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo do Senhor . Esta é a lista do que ele fez:

[[v11-7-44]]

^<<v11-7-44,44>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo do Senhor . Esta é a lista do que ele fez:

[[v11-7-45]]

^<<v11-7-45,45>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo do Senhor . Esta é a lista do que ele fez:

'''

xref:011-1-reis/011-1-reis-006.adoc#v11-6-0[&#60; Capítulo Anterior] | <<v11-7-0,Topo>> | xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[Próximo Capítulo &#62;]