include::./index.adoc[]

[[v11-4-0]]
=== 1 Reis, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-4-1]]

^<<v11-4-1,1>>^ Salomão foi rei de todo o povo de Israel.

[[v11-4-2]]

^<<v11-4-2,2>>^ Os seus altos funcionários foram estes: Sacerdote: Azarias, filho de Zadoque.

[[v11-4-3]]

^<<v11-4-3,3>>^ Escrivães: Eliorefe e Aías, filhos de Sisá. Conselheiro do rei: Josafá, filho de Ailude.

[[v11-4-4]]

^<<v11-4-4,4>>^ Comandante do exército: Benaías, filho de Joiada. Sacerdotes: Zadoque e Abiatar.

[[v11-4-5]]

^<<v11-4-5,5>>^ Chefe dos administradores dos distritos: Azarias, filho de Natã. Conselheiro particular do rei: o sacerdote Zabude, filho de Natã.

[[v11-4-6]]

^<<v11-4-6,6>>^ Encarregado dos servidores do palácio: Aisar. Encarregado dos trabalhadores forçados: Adonirão, filho de Abda.

[[v11-4-7]]

^<<v11-4-7,7>>^ Salomão nomeou doze homens como administradores dos distritos de Israel. Eles forneciam alimentos dos seus distritos para o rei e o seu palácio, e cada um deles tinha o dever de fazer isso durante um mês do ano.

[[v11-4-8]]

^<<v11-4-8,8>>^ São estes os nomes desses doze administradores e dos seus distritos: Ben-Hur: a região montanhosa de Efraim.

[[v11-4-9]]

^<<v11-4-9,9>>^ Ben-Dequer: as cidades de Maaz, Saalabim, Bete-Semes, Elom e Bete-Hanã.

[[v11-4-10]]

^<<v11-4-10,10>>^ Ben-Hesede: as cidades de Arubote e Socó e todo o território de Héfer.

[[v11-4-11]]

^<<v11-4-11,11>>^ Ben-Abinadabe, que era casado com Tafate, filha de Salomão: toda a região de Dor.

[[v11-4-12]]

^<<v11-4-12,12>>^ Baaná, filho de Ailude: as cidades de Taanaque, Megido e toda a região que ficava perto de Bete-Sã, perto da cidade de Sartã, ao sul da cidade de Jezreel, até as cidades de Abel-Meolá e Jocmeão.

[[v11-4-13]]

^<<v11-4-13,13>>^ Ben-Geber: a cidade de Ramote, na região de Gileade, e os povoados de Gileade que pertenciam ao grupo de famílias de Jair, descendente de Manassés; e a região de Argobe, em Basã, onde havia ao todo sessenta cidades grandes cercadas de muralhas e com barras de bronze nos portões.

[[v11-4-14]]

^<<v11-4-14,14>>^ Ainadabe, filho de Ido: o distrito de Maanaim.

[[v11-4-15]]

^<<v11-4-15,15>>^ Aimaás, que era casado com Basemate, outra filha de Salomão: o território de Naftali.

[[v11-4-16]]

^<<v11-4-16,16>>^ Baaná, filho de Husai: a região de Aser e a cidade de Bealote.

[[v11-4-17]]

^<<v11-4-17,17>>^ Josafá, filho de Parua: o território de Issacar.

[[v11-4-18]]

^<<v11-4-18,18>>^ Simei, filho de Elá: o território de Benjamim.

[[v11-4-19]]

^<<v11-4-19,19>>^ Geber, filho de Uri: a região de Gileade, que havia sido governada por Seom, o rei dos amorreus, e por Ogue, rei de Basã. No território de Judá também havia um administrador.

[[v11-4-20]]

^<<v11-4-20,20>>^ O povo de Judá e de Israel era tão numeroso como os grãos de areia da praia do mar; eles comiam, bebiam e eram muito felizes.

[[v11-4-21]]

^<<v11-4-21,21>>^ Do reino de Salomão faziam parte todas as nações que havia desde o rio Eufrates até a terra dos filisteus e até a fronteira do Egito. Esses reinos pagavam impostos a Salomão e foram dominados por ele durante toda a sua vida.

[[v11-4-22]]

^<<v11-4-22,22>>^ Os mantimentos que Salomão precisava todos os dias eram: três mil quilos de farinha de trigo e seis mil quilos de farinha de outros cereais;

[[v11-4-23]]

^<<v11-4-23,23>>^ dez bois gordos, vinte bois de pasto e cem carneiros; fora veados, gazelas , corços  e aves domésticas.

[[v11-4-24]]

^<<v11-4-24,24>>^ Salomão dominava toda a região a oeste do rio Eufrates, desde Tifsa, no Eufrates, até a cidade de Gaza, no litoral do mar Mediterrâneo. Todos os reis a oeste do Eufrates eram dominados por ele, e ele estava em paz com todos os países vizinhos.

[[v11-4-25]]

^<<v11-4-25,25>>^ Durante a vida de Salomão o povo de Judá e de Israel viveu em segurança, e de uma ponta do país à outra cada família tinha os seus pés de uvas e de figos.

[[v11-4-26]]

^<<v11-4-26,26>>^ Salomão tinha quatro mil baias para os cavalos dos seus carros de guerra e doze mil cavalos de cavalaria.

[[v11-4-27]]

^<<v11-4-27,27>>^ Os seus doze administradores regionais, cada um no seu mês, forneciam os alimentos que Salomão precisava para si mesmo e para aqueles que comiam no palácio; os administradores não deixavam faltar nada.

[[v11-4-28]]

^<<v11-4-28,28>>^ Cada um também fornecia a sua parte de cevada  e de palha onde eram necessárias para os cavalos que puxavam os carros de guerra e para os animais de trabalho.

[[v11-4-29]]

^<<v11-4-29,29>>^ Deus deu a Salomão sabedoria, entendimento fora do comum e conhecimentos tão grandes, que não podiam ser medidos.

[[v11-4-30]]

^<<v11-4-30,30>>^ Salomão era mais sábio do que qualquer homem do Oriente ou do Egito.

[[v11-4-31]]

^<<v11-4-31,31>>^ Ele era mais sábio do que todos os homens: mais sábio do que Etã, o ezraíta, e do que Hemã, Calcol e Darda, filhos de Maol. E a sua fama se espalhou por todos os países vizinhos.

[[v11-4-32]]

^<<v11-4-32,32>>^ Ele escreveu três mil provérbios e compôs mais de mil canções.

[[v11-4-33]]

^<<v11-4-33,33>>^ Falou de árvores e plantas, desde os cedros do Líbano até o hissopo , que cresce nos muros; ele falou também dos animais, dos pássaros, dos animais que se arrastam pelo chão e dos peixes.

[[v11-4-34]]

^<<v11-4-34,34>>^ Reis do mundo inteiro souberam da sabedoria de Salomão e mandaram pessoas para ouvi-lo.

'''

xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[&#60; Capítulo Anterior] | <<v11-4-0,Topo>> | xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[Próximo Capítulo &#62;]