include::./index.adoc[]

[[v11-5-0]]
=== 1 Reis, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-5-1]]

^<<v11-5-1,1>>^ Hirão, rei de Tiro, sempre havia sido amigo de Davi. Quando soube que Salomão era o rei em lugar do seu pai, enviou embaixadores a ele.

[[v11-5-2]]

^<<v11-5-2,2>>^ Então Salomão mandou a Hirão a seguinte mensagem:

[[v11-5-3]]

^<<v11-5-3,3>>^ "Você sabe que Davi, o meu pai, teve muitas guerras contra as nações ao seu redor. Por isso, ele nunca pôde construir um templo dedicado ao Senhor , seu Deus, enquanto este não fez com que ele derrotasse todos os seus inimigos.

[[v11-5-4]]

^<<v11-5-4,4>>^ Mas agora o Senhor  me deu paz em todas as fronteiras. Eu não tenho inimigos, e não há perigo de ataques.

[[v11-5-5]]

^<<v11-5-5,5>>^ Deus prometeu o seguinte a Davi, o meu pai: ‘O seu filho, que eu vou pôr como rei depois de você, construirá um templo para mim.’ Portanto, eu resolvi construir um templo para a adoração do meu Deus, o Senhor .

[[v11-5-6]]

^<<v11-5-6,6>>^ Por isso, mande cortar cedros do Líbano para mim. Os meus operários trabalharão junto com os seus, e eu pagarei aos seus operários o quanto você quiser. Como você sabe, no meio do meu povo não há quem saiba cortar árvores tão bem como a sua gente da cidade de Sidom."

[[v11-5-7]]

^<<v11-5-7,7>>^ Quando recebeu a mensagem de Salomão, o rei Hirão ficou muito contente e disse: — Louvado seja hoje o Senhor , que deu a Davi um filho cheio de sabedoria para ficar no lugar dele como rei daquela grande nação!

[[v11-5-8]]

^<<v11-5-8,8>>^ Depois mandou dizer a Salomão o seguinte: — Recebi a sua mensagem e vou atender o seu pedido. Vou providenciar os cedros e os pinheiros.

[[v11-5-9]]

^<<v11-5-9,9>>^ Os meus operários levarão as toras do alto dos montes Líbanos até o mar e farão jangadas com elas. Depois as levarão beirando o litoral até o lugar que você escolher. Ali os meus operários desamarrarão as toras, e os seus operários tomarão conta delas. E eu gostaria que você fornecesse a alimentação para os meus operários.

[[v11-5-10]]

^<<v11-5-10,10>>^ E assim Hirão forneceu a Salomão toda a madeira de cedro e de pinho que ele pediu.

[[v11-5-11]]

^<<v11-5-11,11>>^ E cada ano Salomão forneceu a Hirão duas mil toneladas de trigo e quatrocentos mil litros de azeite de oliva puro para alimentar os homens dele.

[[v11-5-12]]

^<<v11-5-12,12>>^ O Senhor  Deus cumpriu a sua promessa e deu sabedoria a Salomão. Havia paz entre Hirão e Salomão, e eles fizeram um acordo  entre si.

[[v11-5-13]]

^<<v11-5-13,13>>^ O rei Salomão convocou em todo o Israel um grupo de trinta mil trabalhadores forçados

[[v11-5-14]]

^<<v11-5-14,14>>^ e pôs Adonirão como chefe deles. Salomão dividiu esses trabalhadores em três grupos de dez mil homens. Cada grupo passava um mês no Líbano e dois meses em casa.

[[v11-5-15]]

^<<v11-5-15,15>>^ Salomão também mandou à região montanhosa oitenta mil homens a fim de cortar pedras e setenta mil homens para carregá-las.

[[v11-5-16]]

^<<v11-5-16,16>>^ Ele colocou três mil e trezentos chefes para dirigir o trabalho deles.

[[v11-5-17]]

^<<v11-5-17,17>>^ Obedecendo às ordens do rei Salomão, eles cortaram grandes pedras de boa qualidade para os alicerces do Templo.

[[v11-5-18]]

^<<v11-5-18,18>>^ Os trabalhadores de Salomão e de Hirão e alguns homens da cidade de Biblos prepararam as pedras e a madeira para a construção do Templo.

'''

xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[&#60; Capítulo Anterior] | <<v11-5-0,Topo>> | xref:011-1-reis/011-1-reis-006.adoc#v11-6-0[Próximo Capítulo &#62;]