include::./index.adoc[]

[[v11-9-0]]
=== 1 Reis, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-9-1]]

^<<v11-9-1,1>>^ Depois que Salomão acabou de construir o Templo e o palácio real e tudo mais que havia planejado construir,

[[v11-9-2]]

^<<v11-9-2,2>>^ o Senhor  Deus apareceu outra vez a ele, como havia aparecido em Gibeão.

[[v11-9-3]]

^<<v11-9-3,3>>^ O Senhor  lhe disse: — Eu ouvi a sua oração e o pedido que você fez na minha presença. Declarei santo este Templo, que você construiu como o lugar onde serei adorado para sempre. Eu tomarei conta dele e sempre o protegerei.

[[v11-9-4]]

^<<v11-9-4,4>>^ Se você me servir com um coração sincero e honesto como Davi, o seu pai, serviu e, se obedecer às minhas leis  e ordens e fizer tudo o que eu mandar,

[[v11-9-5]]

^<<v11-9-5,5>>^ então eu cumprirei a promessa que fiz a Davi, o seu pai, quando lhe disse que Israel sempre seria governado pelos descendentes dele.

[[v11-9-6]]

^<<v11-9-6,6>>^ Mas, se você ou os seus descendentes deixarem de me seguir, se desobedecerem às leis e aos mandamentos que eu lhes dei e se adorarem e servirem outros deuses,

[[v11-9-7]]

^<<v11-9-7,7>>^ então eu arrancarei Israel, o meu povo, da terra que lhe dei. E também abandonarei este Templo que separei para ser o lugar onde devo ser adorado. Aí todos os povos vão desprezar e zombar de Israel.

[[v11-9-8]]

^<<v11-9-8,8>>^ Este Templo virará um monte de ruínas, e todos os que passarem por perto dele ficarão chocados e espantados e perguntarão: "Por que foi que Deus fez isto com esta terra e com este Templo?"

[[v11-9-9]]

^<<v11-9-9,9>>^ E a resposta será: "Foi porque os israelitas abandonaram o Senhor , seu Deus, que tirou os antepassados deles do Egito. Eles seguiram outros deuses, e os adoraram, e os serviram. Foi por isso que o Senhor  fez com que toda esta desgraça caísse sobre eles."

[[v11-9-10]]

^<<v11-9-10,10>>^ Salomão levou vinte anos para construir o Templo e o seu palácio.

[[v11-9-11]]

^<<v11-9-11,11>>^ O rei Hirão, da cidade de Tiro, havia fornecido a ele toda a madeira de cedro e de pinho e todo o ouro que ele precisou para esse trabalho. Depois que terminaram as obras, Salomão deu a Hirão vinte cidades na região da Galileia.

[[v11-9-12]]

^<<v11-9-12,12>>^ Hirão foi vê-las e não gostou delas.

[[v11-9-13]]

^<<v11-9-13,13>>^ Aí disse a Salomão: — Então são estas as cidades que você me deu, meu irmão? Por isso, aquela região é chamada até hoje  de Cabul .

[[v11-9-14]]

^<<v11-9-14,14>>^ Hirão havia mandado para Salomão mais de quatro mil quilos de ouro.

[[v11-9-15]]

^<<v11-9-15,15>>^ O rei Salomão usou trabalhadores forçados para construir o Templo e o seu próprio palácio, para aterrar o lado leste da cidade e para construir as muralhas de Jerusalém. Também usou esses trabalhadores para reconstruir as cidades de Hazor, Megido e Gezer.

[[v11-9-16]]

^<<v11-9-16,16>>^ (Faraó, rei do Egito, havia atacado e conquistado a cidade de Gezer, matando os seus moradores, que eram cananeus, e pondo fogo na cidade. Depois o rei do Egito tinha dado Gezer como presente de casamento à sua filha quando ela casou com Salomão,

[[v11-9-17]]

^<<v11-9-17,17>>^ e Salomão reconstruiu a cidade.) Usando os seus trabalhadores forçados, Salomão também reconstruiu Bete-Horom-de-Baixo,

[[v11-9-18]]

^<<v11-9-18,18>>^ Baalate e Tadmor, no deserto de Judá.

[[v11-9-19]]

^<<v11-9-19,19>>^ Ainda reconstruiu as cidades onde armazenava mantimentos, as cidades onde ficavam os seus cavalos e carros de guerra e tudo mais que ele quis construir em Jerusalém, no Líbano e em outras partes do seu reino.

[[v11-9-20]]

^<<v11-9-20,20>>^ Para esse trabalho forçado, Salomão usou os descendentes do povo de Canaã que os israelitas não haviam matado quando conquistaram o seu país. Entre esses trabalhadores forçados estavam amorreus, heteus, perizeus, heveus e jebuseus. E os descendentes deles continuam escravos até hoje .

[[v11-9-21]]

^<<v11-9-21,21>>^ Para esse trabalho forçado, Salomão usou os descendentes do povo de Canaã que os israelitas não haviam matado quando conquistaram o seu país. Entre esses trabalhadores forçados estavam amorreus, heteus, perizeus, heveus e jebuseus. E os descendentes deles continuam escravos até hoje .

[[v11-9-22]]

^<<v11-9-22,22>>^ Nenhum israelita foi obrigado a trabalhar como escravo. Os israelitas serviram como soldados, oficiais, comandantes, capitães de carros de guerra e cavaleiros.

[[v11-9-23]]

^<<v11-9-23,23>>^ Quinhentos e cinquenta oficiais estavam encarregados dos trabalhadores forçados que eram usados nas várias construções de Salomão.

[[v11-9-24]]

^<<v11-9-24,24>>^ Salomão aterrou o lado leste da cidade depois que a sua esposa, a filha do rei do Egito, se mudou da Cidade de Davi  para o palácio que Salomão havia construído para ela.

[[v11-9-25]]

^<<v11-9-25,25>>^ Três vezes por ano Salomão oferecia sacrifícios  a serem queimados e ofertas de paz no altar que ele havia construído para Deus, o Senhor . Ele também queimava incenso ao Senhor . E assim Salomão terminou a construção do Templo.

[[v11-9-26]]

^<<v11-9-26,26>>^ O rei Salomão também construiu uma frota de navios em Eziom-Geber, que fica perto de Elate, no golfo de Ácaba, no país de Edom.

[[v11-9-27]]

^<<v11-9-27,27>>^ O rei Hirão mandou alguns marinheiros competentes da sua frota de navios para navegarem junto com os homens de Salomão.

'''

xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[Próximo Capítulo &#62;]