include::./index.adoc[]

[[v11-21-0]]
=== 1 Reis, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-21-1]]

^<<v11-21-1,1>>^ Depois disso, aconteceu o seguinte: Acabe, rei de Samaria , tinha um palácio em Jezreel. Perto desse palácio havia uma plantação de uvas que pertencia a um homem chamado Nabote.

[[v11-21-2]]

^<<v11-21-2,2>>^ Certo dia Acabe disse a Nabote: — Dê-me a sua plantação de uvas. Ela fica perto do meu palácio, e eu quero aproveitar o terreno para fazer uma horta. Em troca, eu lhe darei uma plantação de uvas melhor do que a sua ou, se você preferir, eu pagarei um preço justo por ela.

[[v11-21-3]]

^<<v11-21-3,3>>^ — Esta plantação de uvas é uma herança dos meus antepassados! — respondeu Nabote. — Que o Senhor  Deus me livre de entregá-la ao senhor!

[[v11-21-4]]

^<<v11-21-4,4>>^ Acabe foi para casa aborrecido e com raiva por causa do que Nabote tinha dito. Ele se deitou na cama, virado para a parede, e não quis comer nada.

[[v11-21-5]]

^<<v11-21-5,5>>^ Então a sua esposa Jezabel foi falar com ele e perguntou: — Por que você está assim aborrecido? Por que não quer comer?

[[v11-21-6]]

^<<v11-21-6,6>>^ Ele respondeu: — É por causa do que Nabote me falou. Eu lhe disse que queria comprar a sua plantação de uvas ou então, se ele preferisse, eu lhe daria outra em troca. Mas Nabote me disse que não me daria a sua plantação.

[[v11-21-7]]

^<<v11-21-7,7>>^ Então Jezabel disse a Acabe, o seu marido: — Afinal de contas, você é o rei ou não é? Levante-se, anime-se e coma! Eu darei a você a plantação de uvas de Nabote, o homem de Jezreel!

[[v11-21-8]]

^<<v11-21-8,8>>^ Então ela escreveu algumas cartas em nome de Acabe e carimbou-as com o anel-sinete  dele e as mandou para as autoridades e para os líderes de Jezreel.

[[v11-21-9]]

^<<v11-21-9,9>>^ As cartas diziam o seguinte: "Mandem avisar que vai haver um dia de jejum, reúnam todo o povo e ponham Nabote no lugar de honra.

[[v11-21-10]]

^<<v11-21-10,10>>^ Ponham sentados na frente dele dois homens de mau caráter para acusarem Nabote de ter amaldiçoado a Deus e ao rei. Depois levem Nabote para fora da cidade e o matem a pedradas."

[[v11-21-11]]

^<<v11-21-11,11>>^ Os líderes e as autoridades de Jezreel fizeram o que Jezabel havia ordenado.

[[v11-21-12]]

^<<v11-21-12,12>>^ Eles mandaram avisar que ia haver um dia de jejum, reuniram o povo e puseram Nabote no lugar de honra.

[[v11-21-13]]

^<<v11-21-13,13>>^ Então, diante do povo, os dois homens de mau caráter acusaram Nabote de haver amaldiçoado a Deus e ao rei. E assim ele foi levado para fora da cidade e morto a pedradas.

[[v11-21-14]]

^<<v11-21-14,14>>^ Depois mandaram dizer a Jezabel: — Nabote foi morto a pedradas.

[[v11-21-15]]

^<<v11-21-15,15>>^ Logo que Jezabel recebeu o recado, disse a Acabe: — Nabote morreu. Agora vá e tome posse da plantação de uvas que ele não quis vender a você.

[[v11-21-16]]

^<<v11-21-16,16>>^ Logo que soube que Nabote estava morto, Acabe foi até a plantação de uvas e tomou posse dela.

[[v11-21-17]]

^<<v11-21-17,17>>^ Então o Senhor  Deus disse a Elias, o profeta  de Tisbé:

[[v11-21-18]]

^<<v11-21-18,18>>^ — Vá falar com Acabe, rei de Israel, que mora na cidade de Samaria. Você o achará em Jezreel, na plantação de uvas de Nabote. Ele foi até lá para tomar posse dela.

[[v11-21-19]]

^<<v11-21-19,19>>^ Diga a Acabe que eu, o Senhor , estou dizendo a ele: "Você mata o homem e ainda fica com a propriedade dele?" Diga a Acabe que o que eu estou dizendo é isto: "No mesmo lugar onde os cachorros lamberam o sangue de Nabote, eles lamberão o seu próprio sangue."

[[v11-21-20]]

^<<v11-21-20,20>>^ Quando Acabe viu Elias, perguntou: — Você já me achou, meu inimigo? Elias respondeu: — Achei, sim, porque você se entregou completamente a fazer o que o Senhor  Deus considera errado.

[[v11-21-21]]

^<<v11-21-21,21>>^ Por isso, ele lhe diz: "Eu vou fazer com que a desgraça caia sobre você. Vou acabar com você e vou me livrar de todos os homens da sua família, tanto os jovens como os velhos.

[[v11-21-22]]

^<<v11-21-22,22>>^ Vou fazer com a sua família o mesmo que fiz com a família do rei Jeroboão, filho de Nebate, e com a família de Baasa, filho de Aías. Pois você levou o povo de Israel a pecar, e isso me provocou e me fez ficar irado ."

[[v11-21-23]]

^<<v11-21-23,23>>^ Elias continuou, dizendo: — E, quanto a Jezabel, o Senhor  Deus diz que os cachorros comerão o seu corpo na cidade de Jezreel.

[[v11-21-24]]

^<<v11-21-24,24>>^ Os parentes dela que morrerem na cidade serão comidos pelos cachorros, e os que morrerem no campo serão comidos pelos urubus.

[[v11-21-25]]

^<<v11-21-25,25>>^ (Não houve ninguém que tivesse se entregado tão completamente a fazer coisas erradas, que não agradam ao Senhor , como fez Acabe. E tudo ele fez por sugestão da sua esposa Jezabel.

[[v11-21-26]]

^<<v11-21-26,26>>^ Acabe cometeu os pecados mais vergonhosos, adorando ídolos, como haviam feito os amorreus, o povo que o Senhor  havia expulsado do país conforme o povo de Israel tinha ido avançando.)

[[v11-21-27]]

^<<v11-21-27,27>>^ Quando Elias acabou de falar, Acabe rasgou as suas roupas, jogou-as longe e vestiu uma roupa de pano grosseiro. Ele não comia nada, dormia em cima de panos grosseiros e andava triste e abatido.

[[v11-21-28]]

^<<v11-21-28,28>>^ Então o Senhor  Deus disse ao profeta Elias:

[[v11-21-29]]

^<<v11-21-29,29>>^ — Você viu como Acabe se tem humilhado diante de mim? Já que ele está fazendo isso, não será durante a vida dele que vou trazer a desgraça que prometi. Será durante a vida do filho dele que eu vou fazer cair a desgraça sobre a família de Acabe.

'''

xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]