include::./index.adoc[]

[[v11-2-0]]
=== 1 Reis, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-2-1]]

^<<v11-2-1,1>>^ Quando estava chegando o dia da morte de Davi, ele deu conselhos ao seu filho Salomão. Davi disse:

[[v11-2-2]]

^<<v11-2-2,2>>^ — Está chegando o dia da minha morte. Portanto, seja corajoso e seja homem!

[[v11-2-3]]

^<<v11-2-3,3>>^ E faça aquilo que o Senhor , seu Deus, manda. Obedeça a todas as suas leis  e mandamentos, como estão escritos na Lei de Moisés. Assim você será bem-sucedido aonde quer que for e em tudo o que fizer.

[[v11-2-4]]

^<<v11-2-4,4>>^ Se você obedecer ao Senhor  Deus, ele cumprirá a promessa que me fez. Ele me prometeu que os meus descendentes governariam Israel enquanto obedecessem cuidadosamente e fielmente aos seus mandamentos, com todo o seu coração e com toda a sua alma.

[[v11-2-5]]

^<<v11-2-5,5>>^ — Além disso, você sabe o que Joabe, cuja mãe é Zeruia, me fez. Ele matou os dois comandantes do exército de Israel, isto é, Abner, filho de Ner, e Amasa, filho de Jéter. Você sabe como, em tempo de paz, ele os matou para vingar as mortes que eles haviam causado em tempo de guerra. Joabe matou homens inocentes, e agora eu sou o responsável pelo que ele fez e estou sofrendo as consequências.

[[v11-2-6]]

^<<v11-2-6,6>>^ Você sabe o que deve fazer. Não deixe que ele tenha morte natural.

[[v11-2-7]]

^<<v11-2-7,7>>^ — Mas seja bondoso para os filhos de Barzilai, que é de Gileade, e deixe que eles comam à sua mesa, pois foram bons para mim quando eu estava fugindo do seu irmão Absalão. Davi continuou:

[[v11-2-8]]

^<<v11-2-8,8>>^ — E não esqueça Simei, filho de Gera, da cidade de Baurim, no território da tribo  de Benjamim. Ele me amaldiçoou duramente no dia em que fui a Maanaim. Porém, quando eu me encontrei com ele perto do rio Jordão, jurei em nome do Senhor  que não o mandaria matar.

[[v11-2-9]]

^<<v11-2-9,9>>^ Mas você é um homem sábio e não deve deixar que ele fique sem castigo. Você sabe o que deve fazer para que ele morra.

[[v11-2-10]]

^<<v11-2-10,10>>^ Davi morreu e foi sepultado ao lado dos seus antepassados na Cidade de Davi .

[[v11-2-11]]

^<<v11-2-11,11>>^ Ele foi rei de Israel quarenta anos. Governou sete anos em Hebrom e trinta e três anos em Jerusalém.

[[v11-2-12]]

^<<v11-2-12,12>>^ Salomão ficou no lugar de Davi, o seu pai, como rei, e o seu governo se fortaleceu muito.

[[v11-2-13]]

^<<v11-2-13,13>>^ Então Adonias, filho de Hagite, foi visitar Bate-Seba, a mãe de Salomão. Ela perguntou: — A sua visita é de amigo? — É, sim! — respondeu ele.

[[v11-2-14]]

^<<v11-2-14,14>>^ E continuou: — Eu quero lhe dizer uma coisa. — Diga! — disse ela.

[[v11-2-15]]

^<<v11-2-15,15>>^ E Adonias disse: — A senhora sabe que sou eu quem deveria ser o rei e que todos esperavam isso em Israel. Mas as coisas aconteceram de modo diferente, e o meu irmão se tornou rei porque essa era a vontade de Deus, o Senhor .

[[v11-2-16]]

^<<v11-2-16,16>>^ Agora vou lhe fazer só um pedido e peço que a senhora me atenda. — O que você quer? — perguntou Bate-Seba.

[[v11-2-17]]

^<<v11-2-17,17>>^ E ele disse: — Peça ao rei Salomão que me dê Abisague, a moça de Suném, para ser minha mulher. Eu sei que Salomão não deixará de atender um pedido seu.

[[v11-2-18]]

^<<v11-2-18,18>>^ — Está bem! — respondeu ela. — Eu vou falar com o rei por você.

[[v11-2-19]]

^<<v11-2-19,19>>^ Então Bate-Seba foi falar com o rei em favor de Adonias. Salomão se levantou para recebê-la e se inclinou diante dela. Depois sentou-se no seu trono e mandou que trouxessem um trono para Bate-Seba, e ela se sentou do lado direito do rei.

[[v11-2-20]]

^<<v11-2-20,20>>^ Aí Bate-Seba disse: — Tenho um pequeno pedido para lhe fazer. Por favor, não recuse. E o rei disse: — Pode pedir, minha mãe. Eu não recusarei.

[[v11-2-21]]

^<<v11-2-21,21>>^ Bate-Seba disse: — Dê Abisague em casamento ao seu irmão Adonias.

[[v11-2-22]]

^<<v11-2-22,22>>^ — Por que é que a senhora está pedindo Abisague para Adonias? — perguntou Salomão. — A senhora deveria pedir que eu dê a ele também o reino. Afinal, Adonias é o meu irmão mais velho, e o sacerdote Abiatar e Joabe estão do lado dele!

[[v11-2-23]]

^<<v11-2-23,23>>^ Aí Salomão jurou pelo Senhor  Deus assim: — Que Deus me castigue, e em dobro, se eu não fizer Adonias pagar com a vida por ter feito esse pedido!

[[v11-2-24]]

^<<v11-2-24,24>>^ O Senhor  Deus me firmou no trono do meu pai Davi; ele cumpriu a sua promessa e deu o reino a mim e aos meus descendentes. Juro pelo Deus vivo que Adonias morrerá hoje mesmo!

[[v11-2-25]]

^<<v11-2-25,25>>^ Então o rei deu ordem a Benaías, e ele foi, atacou Adonias e o matou.

[[v11-2-26]]

^<<v11-2-26,26>>^ Depois o rei Salomão disse ao sacerdote Abiatar: — Vá para as suas terras em Anatote. Você merece morrer, mas eu não vou mandar matá-lo hoje porque você, quando estava com o meu pai Davi, era o encarregado da arca da aliança  e passou pelas mesmas dificuldades pelas quais o meu pai passou.

[[v11-2-27]]

^<<v11-2-27,27>>^ Depois Salomão dispensou Abiatar do serviço de sacerdote de Deus e assim fez com que acontecesse o que o Senhor  Deus tinha dito em Siló a respeito do sacerdote Eli e dos seus descendentes.

[[v11-2-28]]

^<<v11-2-28,28>>^ Joabe soube do que aconteceu. (Ele havia passado para o lado de Adonias, porém não havia passado para o lado de Absalão.) Então fugiu para a Tenda da Presença do Senhor  Deus e ficou segurando nas pontas do altar .

[[v11-2-29]]

^<<v11-2-29,29>>^ Contaram ao rei Salomão que Joabe havia fugido para a Tenda e estava ao lado do altar. Aí ele mandou um mensageiro perguntar a Joabe por que havia fugido para o altar. Joabe respondeu que havia fugido para o Senhor  Deus porque estava com medo de Salomão. Então Salomão mandou que Benaías fosse matar Joabe.

[[v11-2-30]]

^<<v11-2-30,30>>^ Benaías foi até a Tenda de Deus e disse a Joabe: — O rei mandou você sair daí. — Não saio! — respondeu Joabe. — Eu morrerei aqui. Então Benaías voltou e contou ao rei o que Joabe tinha dito.

[[v11-2-31]]

^<<v11-2-31,31>>^ Aí Salomão ordenou: — Faça o que ele disse. Mate-o e sepulte-o. Assim nem eu nem os descendentes do meu pai Davi seremos mais considerados culpados pelo que Joabe fez quando matou homens inocentes.

[[v11-2-32]]

^<<v11-2-32,32>>^ O Senhor  Deus castigará Joabe pelos assassinatos que cometeu sem o conhecimento do meu pai Davi. Sem o meu pai saber, Joabe matou dois homens que eram inocentes e que eram melhores do que ele: Abner, comandante do exército de Israel, e Amasa, comandante do exército de Judá.

[[v11-2-33]]

^<<v11-2-33,33>>^ O castigo pelo assassinato desses dois homens cairá para sempre sobre Joabe e sobre os seus descendentes. Mas o Senhor  sempre dará prosperidade aos descendentes de Davi que forem reis depois dele.

[[v11-2-34]]

^<<v11-2-34,34>>^ Então Benaías foi até a Tenda de Deus e matou Joabe. Ele foi sepultado na sua propriedade, em campo aberto.

[[v11-2-35]]

^<<v11-2-35,35>>^ O rei pôs Benaías como comandante do exército no lugar de Joabe e colocou o sacerdote Zadoque no lugar de Abiatar.

[[v11-2-36]]

^<<v11-2-36,36>>^ Depois o rei Salomão mandou buscar Simei e disse: — Faça uma casa para você aqui em Jerusalém. Fique morando nela e não saia da cidade.

[[v11-2-37]]

^<<v11-2-37,37>>^ E fique sabendo que, no dia em que você sair e atravessar o ribeirão Cedrom, você será morto, e a culpa será somente sua.

[[v11-2-38]]

^<<v11-2-38,38>>^ — Está bem, ó rei! — respondeu Simei. — Eu prometo fazer o que o senhor está mandando. E ele ficou morando em Jerusalém por muito tempo.

[[v11-2-39]]

^<<v11-2-39,39>>^ Acontece que, três anos depois, dois escravos de Simei fugiram e foram procurar refúgio com o governador da cidade de Gate, que era Aquis, filho de Maacá.

[[v11-2-40]]

^<<v11-2-40,40>>^ Simei ficou sabendo; por isso, selou o seu jumento e foi até Gate falar com Aquis a fim de procurar os seus escravos. Ele os achou e os levou de volta para casa.

[[v11-2-41]]

^<<v11-2-41,41>>^ Quando Salomão soube do que Simei havia feito,

[[v11-2-42]]

^<<v11-2-42,42>>^ mandou buscá-lo e disse: — Eu fiz você jurar em nome do Senhor  que não sairia de Jerusalém. Eu lhe avisei que, se fizesse isso, você certamente morreria. Você concordou com isso e disse que me obedeceria.

[[v11-2-43]]

^<<v11-2-43,43>>^ Então por que é que você quebrou o seu juramento feito em nome do Senhor  e desobedeceu à minha ordem?

[[v11-2-44]]

^<<v11-2-44,44>>^ Você sabe muito bem de todo o mal que fez a Davi, meu pai. O Senhor  Deus fará com que a sua maldade caia sobre você mesmo,

[[v11-2-45]]

^<<v11-2-45,45>>^ porém me abençoará e fará com que o reino de Davi fique seguro para sempre.

[[v11-2-46]]

^<<v11-2-46,46>>^ Aí o rei deu ordem a Benaías, e ele saiu, atacou Simei e o matou. E assim Salomão controlou completamente a situação do seu governo.

'''

xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[Próximo Capítulo &#62;]