include::./index.adoc[]

[[v11-11-0]]
=== 1 Reis, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-11-1]]

^<<v11-11-1,1>>^ Salomão amou muitas mulheres estrangeiras. Além da filha do rei do Egito, ele casou com mulheres heteias e com mulheres dos países de Moabe, Amom, Edom e Sidom.

[[v11-11-2]]

^<<v11-11-2,2>>^ Casou com elas, mesmo sabendo que o Senhor  Deus havia ordenado aos israelitas que não casassem com mulheres estrangeiras porque elas fariam com que os corações deles se voltassem para outros deuses.

[[v11-11-3]]

^<<v11-11-3,3>>^ Salomão casou com setecentas princesas e também teve trezentas concubinas . Elas fizeram com que ele se afastasse de Deus

[[v11-11-4]]

^<<v11-11-4,4>>^ e, quando ele já estava velho, fizeram com que o seu coração se voltasse para deuses estrangeiros. Ele não foi fiel ao Senhor , seu Deus, como Davi, o seu pai, havia sido.

[[v11-11-5]]

^<<v11-11-5,5>>^ Salomão adorou Astarote , a deusa de Sidom, e Moloque , o nojento deus de Amom.

[[v11-11-6]]

^<<v11-11-6,6>>^ Ele pecou contra o Senhor  e não foi fiel a ele como Davi, o seu pai, havia sido.

[[v11-11-7]]

^<<v11-11-7,7>>^ Na montanha que ficava a leste de Jerusalém, ele construiu um lugar para a adoração de Quemos, o nojento deus de Moabe, e um lugar para a adoração de Moloque, o nojento deus de Amom.

[[v11-11-8]]

^<<v11-11-8,8>>^ Também construiu lugares de adoração, onde todas as suas mulheres estrangeiras queimavam incenso e ofereciam sacrifícios  aos seus próprios deuses.

[[v11-11-9]]

^<<v11-11-9,9>>^ O Senhor , o Deus de Israel, havia aparecido a Salomão duas vezes e lhe havia ordenado que não adorasse deuses estrangeiros. Mesmo assim, Salomão não obedeceu ao Senhor , mas afastou-se dele. Por isso, o Senhor  ficou muito irado  com Salomão

[[v11-11-10]]

^<<v11-11-10,10>>^ O Senhor , o Deus de Israel, havia aparecido a Salomão duas vezes e lhe havia ordenado que não adorasse deuses estrangeiros. Mesmo assim, Salomão não obedeceu ao Senhor , mas afastou-se dele. Por isso, o Senhor  ficou muito irado  com Salomão

[[v11-11-11]]

^<<v11-11-11,11>>^ e disse: — Você quebrou a sua aliança  comigo e desobedeceu aos meus mandamentos; por isso, eu vou tirar o reino de você e vou dá-lo a um dos seus oficiais.

[[v11-11-12]]

^<<v11-11-12,12>>^ No entanto, por amor a Davi, o seu pai, eu não farei isso enquanto você estiver vivo, mas durante o reinado do seu filho.

[[v11-11-13]]

^<<v11-11-13,13>>^ E não tomarei dele o reino inteiro, mas deixarei que ele fique com uma tribo  , por causa do meu servo  Davi e por causa de Jerusalém, que escolhi para ser a minha cidade.

[[v11-11-14]]

^<<v11-11-14,14>>^ O Senhor  Deus fez com que Hadade se virasse contra Salomão. Hadade era da família do rei de Edom.

[[v11-11-15]]

^<<v11-11-15,15>>^ Muito antes disso, quando Davi tinha conquistado Edom, Joabe, o comandante do exército de Israel, havia ido até lá para sepultar os mortos. Ele e os seus soldados ficaram ali seis meses e durante esse tempo mataram todos os homens de Edom.

[[v11-11-16]]

^<<v11-11-16,16>>^ Muito antes disso, quando Davi tinha conquistado Edom, Joabe, o comandante do exército de Israel, havia ido até lá para sepultar os mortos. Ele e os seus soldados ficaram ali seis meses e durante esse tempo mataram todos os homens de Edom.

[[v11-11-17]]

^<<v11-11-17,17>>^ Somente escaparam Hadade e alguns escravos edomitas que pertenciam ao seu pai. Eles fugiram para o Egito. Naquele tempo Hadade ainda era menino.

[[v11-11-18]]

^<<v11-11-18,18>>^ Eles saíram de Midiã e foram até Parã, onde alguns homens se juntaram a eles. Então viajaram para o Egito e foram falar com Faraó, rei daquele país. Este deu a Hadade um pedaço de terra e uma casa e lhe forneceu comida.

[[v11-11-19]]

^<<v11-11-19,19>>^ Hadade ganhou a amizade do rei, e ele lhe deu sua cunhada, a irmã da rainha Tafnes, em casamento.

[[v11-11-20]]

^<<v11-11-20,20>>^ A esposa de Hadade deu à luz um filho, chamado Genubate, que foi criado pela rainha no palácio, onde ele morava com os filhos do rei.

[[v11-11-21]]

^<<v11-11-21,21>>^ Um dia, no Egito, Hadade ficou sabendo que Davi tinha morrido e que Joabe, o comandante do seu exército, também estava morto. Então disse ao rei: — Deixe que eu volte para a minha terra.

[[v11-11-22]]

^<<v11-11-22,22>>^ E o rei disse: — Por que você quer voltar? Será que aqui está lhe faltando alguma coisa, e por isso você quer voltar para a sua terra? — Não me falta nada! — respondeu Hadade. — Mas deixe-me ir. Então Hadade voltou para a sua terra. E, como rei de Edom, foi um mau e feroz inimigo de Israel.

[[v11-11-23]]

^<<v11-11-23,23>>^ Deus também fez com que Rezom, filho de Eliada, se virasse contra Salomão. Rezom havia fugido do seu patrão, o rei Hadadezer, de Zoba,

[[v11-11-24]]

^<<v11-11-24,24>>^ e tinha se tornado o chefe de uma turma de bandidos. (Isso aconteceu depois que Davi derrotou Hadadezer e matou os sírios, que eram aliados dele.) Rezom e os seus homens foram morar em Damasco e ali eles o fizeram rei da Síria.

[[v11-11-25]]

^<<v11-11-25,25>>^ Rezom foi inimigo de Israel durante toda a vida de Salomão.

[[v11-11-26]]

^<<v11-11-26,26>>^ Houve outro homem que se virou contra o rei Salomão. Foi Jeroboão, filho de Nebate, que era de Zereda, no território da tribo  de Efraim. Jeroboão era oficial de Salomão, e a sua mãe era uma viúva chamada Zerua.

[[v11-11-27]]

^<<v11-11-27,27>>^ Esta é a história da revolta de Jeroboão: Salomão estava aterrando o lado leste da cidade de Jerusalém e consertando as muralhas da cidade.

[[v11-11-28]]

^<<v11-11-28,28>>^ Jeroboão era um jovem capaz, e Salomão viu que ele trabalhava com vontade. Então o colocou como encarregado de todos os trabalhadores forçados do território das tribos de Manassés e Efraim.

[[v11-11-29]]

^<<v11-11-29,29>>^ Um dia Jeroboão saiu de Jerusalém em viagem, e o profeta  Aías, de Siló, se encontrou com ele sozinho na estrada, no meio do campo.

[[v11-11-30]]

^<<v11-11-30,30>>^ Então Aías tirou a capa  nova que estava usando, cortou-a em doze pedaços

[[v11-11-31]]

^<<v11-11-31,31>>^ e disse a Jeroboão: — Fique com dez pedaços porque o Senhor , o Deus de Israel, está lhe dizendo o seguinte: "Eu vou arrancar o reino da mão de Salomão e vou dar dez tribos a você.

[[v11-11-32]]

^<<v11-11-32,32>>^ Salomão ficará com uma tribo por causa do meu servo  Davi e por causa de Jerusalém, a cidade que escolhi em toda a terra de Israel para ser minha.

[[v11-11-33]]

^<<v11-11-33,33>>^ Vou fazer isso porque Salomão me rejeitou e tem adorado deuses estrangeiros: Astarote , a deusa de Sidom, Quemos, o deus de Moabe, e Moloque , o deus de Amom. Salomão tem me desobedecido; ele tem agido de maneira errada e não tem guardado as minhas leis  e as minhas ordens como Davi, o seu pai, guardou.

[[v11-11-34]]

^<<v11-11-34,34>>^ Mas eu não vou tomar de Salomão o reino todo; vou deixar que ele governe enquanto viver. Eu farei isso por causa de Davi, o meu servo, que escolhi e que obedeceu aos meus mandamentos e leis.

[[v11-11-35]]

^<<v11-11-35,35>>^ Do filho de Salomão eu tomarei o reino e darei a você dez tribos.

[[v11-11-36]]

^<<v11-11-36,36>>^ Mas deixarei que o filho de Salomão fique com uma tribo, para que eu sempre tenha um descendente de Davi reinando em Jerusalém, a cidade que escolhi como o lugar onde devo ser adorado.

[[v11-11-37]]

^<<v11-11-37,37>>^ Jeroboão, eu vou fazer de você o rei de Israel, e você vai governar todo o território que quiser.

[[v11-11-38]]

^<<v11-11-38,38>>^ Se você der atenção a todas as minhas ordens e viver de acordo com a minha vontade, fazendo aquilo que eu aprovo e obedecendo às minhas leis e aos meus mandamentos, como fez o meu servo Davi, então eu sempre estarei com você. Eu farei com que você seja o rei de Israel e, como fiz com Davi, certamente farei com que os seus descendentes governem depois de você.

[[v11-11-39]]

^<<v11-11-39,39>>^ Por causa do pecado de Salomão, eu castigarei os descendentes de Davi, mas isso não será para sempre."

[[v11-11-40]]

^<<v11-11-40,40>>^ Por causa disso, Salomão tentou matar Jeroboão, mas ele fugiu para o Egito. Jeroboão ficou com Sisaque, rei do Egito, e morou lá até a morte de Salomão.

[[v11-11-41]]

^<<v11-11-41,41>>^ Todas as outras coisas que Salomão fez, os seus atos e a sua sabedoria, estão todos registrados na História de Salomão .

'''

xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[Próximo Capítulo &#62;]