include::./index.adoc[]

[[v11-8-0]]
=== 1 Reis, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-8-1]]

^<<v11-8-1,1>>^ Aí o rei Salomão convocou todos os chefes das tribos  e dos grupos de famílias de Israel para irem encontrar-se com ele em Jerusalém a fim de levarem a arca da aliança  de Deus, de Sião , a Cidade de Davi , para o Templo.

[[v11-8-2]]

^<<v11-8-2,2>>^ Todos os israelitas se reuniram durante a Festa das Barracas , no mês de etanim , que é o sétimo mês.

[[v11-8-3]]

^<<v11-8-3,3>>^ Quando todos os chefes chegaram, os sacerdotes pegaram a arca da aliança

[[v11-8-4]]

^<<v11-8-4,4>>^ e a levaram para o Templo. Os levitas  e os sacerdotes levaram também a Tenda da Presença de Deus  com todos os seus equipamentos para o Templo.

[[v11-8-5]]

^<<v11-8-5,5>>^ O rei Salomão e todo o povo de Israel se reuniram em frente da arca da aliança e ofereceram em sacrifício  um grande número de ovelhas e touros, tantos que nem dava para contar.

[[v11-8-6]]

^<<v11-8-6,6>>^ Então os sacerdotes levaram a arca para dentro do Templo e a colocaram onde devia ficar, no Lugar Santíssimo , debaixo das asas dos querubins .

[[v11-8-7]]

^<<v11-8-7,7>>^ Pois as suas asas estendidas cobriam a arca e os seus cabos.

[[v11-8-8]]

^<<v11-8-8,8>>^ As pontas dos cabos podiam ser vistas por qualquer pessoa que ficasse diretamente em frente ao Lugar Santíssimo, mas não podiam ser vistas de nenhum outro lugar. (Os cabos ainda estão ali até hoje .)

[[v11-8-9]]

^<<v11-8-9,9>>^ Dentro da arca estavam somente as duas placas de pedra que Moisés havia colocado ali, quando, no monte Sinai, o Senhor  Deus havia feito uma aliança com os israelitas depois que eles saíram do Egito.

[[v11-8-10]]

^<<v11-8-10,10>>^ Quando os sacerdotes estavam saindo do Lugar Santo , uma nuvem encheu o Templo do Senhor

[[v11-8-11]]

^<<v11-8-11,11>>^ com a glória  do Senhor , e eles não puderam voltar para dentro a fim de realizar os seus atos de culto.

[[v11-8-12]]

^<<v11-8-12,12>>^ Aí Salomão disse: — Tu, ó Senhor , puseste o sol no céu embora tivesses resolvido viver entre as nuvens escuras.

[[v11-8-13]]

^<<v11-8-13,13>>^ Mas agora eu construí para ti uma casa, um lugar onde viverás para sempre.

[[v11-8-14]]

^<<v11-8-14,14>>^ Aí Salomão virou-se, olhou para o povo, que estava todo de pé, e pediu a bênção de Deus para todos.

[[v11-8-15]]

^<<v11-8-15,15>>^ Depois disse: — Bendito seja o Senhor , o Deus de Israel! Pois, pelo seu poder, ele cumpriu a promessa que tinha feito a Davi, o meu pai, quando lhe disse:

[[v11-8-16]]

^<<v11-8-16,16>>^ "Desde o dia em que tirei do Egito o meu povo de Israel, eu não escolhi nenhuma cidade de todas as tribos  da terra de Israel para ali construir um templo a fim de ser adorado nele. Mas escolhi você, Davi, para governar o meu povo."

[[v11-8-17]]

^<<v11-8-17,17>>^ E Salomão continuou: — Davi, o meu pai, tinha planos de construir um templo para a adoração do Senhor , o Deus de Israel,

[[v11-8-18]]

^<<v11-8-18,18>>^ mas o Senhor  lhe disse: "Você fez bem quando planejou construir um templo para mim,

[[v11-8-19]]

^<<v11-8-19,19>>^ mas você não o construirá. Será o seu filho quem construirá o meu Templo."

[[v11-8-20]]

^<<v11-8-20,20>>^ E agora Deus cumpriu a sua promessa. Eu fiquei no lugar do meu pai como rei de Israel e construí o Templo para a adoração do Senhor , o Deus de Israel.

[[v11-8-21]]

^<<v11-8-21,21>>^ Também separei no Templo um lugar para colocar a arca da aliança , onde estão guardadas as placas de pedra da aliança que o Senhor  Deus fez com os nossos antepassados quando os tirou do Egito.

[[v11-8-22]]

^<<v11-8-22,22>>^ Então, na presença de todo o povo reunido, Salomão foi e ficou em frente do altar. Levantou as mãos para o céu

[[v11-8-23]]

^<<v11-8-23,23>>^ e disse: — Ó Senhor , Deus de Israel! Não há Deus igual a ti em cima no céu nem embaixo na terra. Tu cumpres a aliança  que fizeste com o teu povo e lhes mostras o teu amor quando eles, com todo o coração, vivem uma vida de obediência a ti.

[[v11-8-24]]

^<<v11-8-24,24>>^ Pelo teu poder cumpriste a promessa que fizeste a Davi, o meu pai; no dia de hoje todas as palavras da tua promessa foram completamente cumpridas.

[[v11-8-25]]

^<<v11-8-25,25>>^ E agora, ó Senhor , Deus de Israel, eu te peço que cumpras a outra promessa que fizeste ao meu pai quando lhe disseste que sempre haveria um descendente dele governando como rei de Israel, contanto que eles te obedecessem com o mesmo cuidado com que ele obedeceu.

[[v11-8-26]]

^<<v11-8-26,26>>^ Portanto, ó Deus de Israel, faze com que se cumpra aquilo que prometeste a Davi, o meu pai, teu servo .

[[v11-8-27]]

^<<v11-8-27,27>>^ — Mas será que, de fato, ó Deus, tu podes morar no meio de nós, criaturas humanas, aqui na terra? Tu és tão grande, que não cabes nem mesmo no céu; como poderia este Templo que eu construí ser bastante grande para isso?

[[v11-8-28]]

^<<v11-8-28,28>>^ Ó Senhor , meu Deus, eu sou teu servo. Escuta a minha oração e atende os pedidos que te faço hoje.

[[v11-8-29]]

^<<v11-8-29,29>>^ Olha de dia e de noite para este Templo, o lugar que escolheste para nele seres adorado. Ouve-me quando eu orar com o rosto virado para este lugar.

[[v11-8-30]]

^<<v11-8-30,30>>^ Escuta as minhas orações e as orações do teu povo quando eles orarem com o rosto virado para cá. Sim, da tua casa no céu, ouve-nos e perdoa-nos.

[[v11-8-31]]

^<<v11-8-31,31>>^ — Quando alguém for acusado de prejudicar outra pessoa e for trazido até o teu altar neste Templo e jurar que é inocente,

[[v11-8-32]]

^<<v11-8-32,32>>^ ó Senhor , ouve do céu e julga os teus servos. Castiga o culpado como ele merecer e declara que não tem culpa aquele que for inocente, recompensando-o como ele merecer.

[[v11-8-33]]

^<<v11-8-33,33>>^ — Quando, por ter pecado contra ti, o teu povo de Israel for derrotado pelos seus inimigos e, quando ele se virar para ti e vier a este Templo para te louvar e pedir o teu perdão,

[[v11-8-34]]

^<<v11-8-34,34>>^ escuta-o do céu. Perdoa o pecado do teu povo e leva-o de volta para a terra que deste aos seus antepassados.

[[v11-8-35]]

^<<v11-8-35,35>>^ — Quando o céu se fechar, e não chover, porque o teu povo pecou contra ti, e eles se arrependerem e virarem o rosto na direção deste Templo e orarem e te louvarem, depois que os tiveres castigado,

[[v11-8-36]]

^<<v11-8-36,36>>^ escuta-os do céu. Perdoa os pecados do rei e do povo de Israel e ensina-os a fazer o que é direito. Então, ó Deus, faze cair chuva sobre esta tua terra que deste ao teu povo para ser deles para sempre.

[[v11-8-37]]

^<<v11-8-37,37>>^ — Quando nesta terra houver falta de alimentos, ou houver pragas, ou as colheitas forem destruídas por ventos muito quentes ou por bandos de gafanhotos, ou quando o teu povo for atacado pelos seus inimigos, ou quando houver peste ou doença entre o povo,

[[v11-8-38]]

^<<v11-8-38,38>>^ escuta as suas orações. Se alguém do teu povo de Israel, sentindo no seu coração o peso da desgraça, estender as mãos na direção deste Templo e orar,

[[v11-8-39]]

^<<v11-8-39,39>>^ escuta a sua oração. Lá do teu lar no céu, ouve o teu povo, perdoa-o e ajuda-o. Só tu conheces os pensamentos secretos do coração humano. Trata cada pessoa como merecer,

[[v11-8-40]]

^<<v11-8-40,40>>^ para que o teu povo te tema  e te obedeça durante todo o tempo em que eles viverem na terra que deste aos nossos antepassados.

[[v11-8-41]]

^<<v11-8-41,41>>^ — Quando um estrangeiro que vive numa terra bem longe daqui ouvir falar da tua fama e das grandes coisas que tens feito pelo teu povo e vier te adorar e orar a ti com o rosto virado para este Templo,

[[v11-8-42]]

^<<v11-8-42,42>>^ — Quando um estrangeiro que vive numa terra bem longe daqui ouvir falar da tua fama e das grandes coisas que tens feito pelo teu povo e vier te adorar e orar a ti com o rosto virado para este Templo,

[[v11-8-43]]

^<<v11-8-43,43>>^ ouve a sua oração. Lá do céu, onde vives, escuta-o e faze tudo o que ele te pedir, para que todos os povos da terra possam te conhecer e temer, como faz o teu povo de Israel. Então eles ficarão sabendo que este Templo que eu construí é o lugar onde deves ser adorado.

[[v11-8-44]]

^<<v11-8-44,44>>^ — Quando ordenares que o teu povo saia para a guerra contra os seus inimigos, e o teu povo orar a ti, virados para esta cidade que escolheste e para este Templo que construí em honra do teu nome,

[[v11-8-45]]

^<<v11-8-45,45>>^ escuta do céu as suas orações e os seus pedidos. Ouve-os e dá-lhes a vitória.

[[v11-8-46]]

^<<v11-8-46,46>>^ — Quando eles pecarem contra ti — e não há ninguém que não peque — e na tua ira  deixares que os inimigos deles os derrotem e os levem prisioneiros para alguma terra inimiga, longe ou perto daqui,

[[v11-8-47]]

^<<v11-8-47,47>>^ ouve as orações do teu povo. Se ali, naquela terra, eles se arrependerem e orarem a ti, confessando que foram pecadores e maus, escuta as suas orações, ó Senhor .

[[v11-8-48]]

^<<v11-8-48,48>>^ Se naquela terra eles verdadeiramente e sinceramente se arrependerem e orarem a ti, virados na direção desta terra que deste aos nossos antepassados, desta cidade que escolheste e deste Templo que construí em honra do teu nome,

[[v11-8-49]]

^<<v11-8-49,49>>^ escuta as orações deles. Do teu lar no céu ouve-os e dá-lhes a vitória.

[[v11-8-50]]

^<<v11-8-50,50>>^ Perdoa os pecados que o teu povo tem cometido contra ti e a sua revolta contra ti e faze com que os seus inimigos os tratem com bondade.

[[v11-8-51]]

^<<v11-8-51,51>>^ Eles são o teu povo que tiraste daquela fornalha acesa, o Egito.

[[v11-8-52]]

^<<v11-8-52,52>>^ — Ó Senhor , nosso Deus, eu te peço que olhes com simpatia para o teu povo de Israel e para o seu rei e escutes as suas orações sempre que eles te chamarem pedindo ajuda.

[[v11-8-53]]

^<<v11-8-53,53>>^ Tu os escolheste entre todos os povos para serem o teu povo, conforme lhes disseste por meio do teu servo Moisés, quando tiraste do Egito os nossos antepassados.

[[v11-8-54]]

^<<v11-8-54,54>>^ Depois que Salomão acabou de orar ao Senhor  Deus, ele se levantou e ficou em frente do altar, onde havia estado ajoelhado com as mãos levantadas para o céu.

[[v11-8-55]]

^<<v11-8-55,55>>^ Então, em voz alta, pediu as bênçãos de Deus para todo o povo que estava reunido ali. Ele disse:

[[v11-8-56]]

^<<v11-8-56,56>>^ — Bendito seja o Senhor  Deus, que deu paz ao seu povo, como havia prometido! Ele tem cumprido todas as abençoadas promessas que fez por meio do seu servo  Moisés.

[[v11-8-57]]

^<<v11-8-57,57>>^ Que o Senhor , nosso Deus, esteja conosco assim como esteve com os nossos antepassados! Que ele nunca nos deixe, nem nos abandone!

[[v11-8-58]]

^<<v11-8-58,58>>^ Que Deus nos faça obedientes a ele, para que sempre vivamos conforme ele quer, obedecendo a todos os mandamentos, leis  e ensinos que ele deu aos nossos antepassados!

[[v11-8-59]]

^<<v11-8-59,59>>^ Que o Senhor , nosso Deus, lembre sempre desta oração e dos pedidos que eu lhe fiz! Que ele sempre tenha misericórdia do povo de Israel e do seu rei, de acordo com o que precisarem!

[[v11-8-60]]

^<<v11-8-60,60>>^ E assim todas as nações do mundo ficarão sabendo que somente o Senhor  é Deus e que não há nenhum outro.

[[v11-8-61]]

^<<v11-8-61,61>>^ Que vocês sejam sempre fiéis ao Senhor , nosso Deus, obedecendo a todos os seus mandamentos e leis, como fazem hoje!

[[v11-8-62]]

^<<v11-8-62,62>>^ Então o rei Salomão e todo o povo que estava ali ofereceram sacrifícios  a Deus, o Senhor .

[[v11-8-63]]

^<<v11-8-63,63>>^ Ele ofereceu em sacrifício vinte e dois mil bois e cento e vinte mil ovelhas como ofertas de paz. E assim o rei e todo o povo dedicaram o Templo ao serviço do Senhor .

[[v11-8-64]]

^<<v11-8-64,64>>^ Naquele mesmo dia Salomão separou, a fim de ser sagrada para Deus, a parte central do pátio que ficava em frente ao Templo. Ali ele apresentou as ofertas que foram completamente queimadas, as ofertas de cereais e a gordura dos animais que haviam sido trazidos como ofertas de paz. Salomão fez isso porque o altar de bronze era muito pequeno para todas essas ofertas.

[[v11-8-65]]

^<<v11-8-65,65>>^ Naquela ocasião, ali no Templo, Salomão e todo o povo de Israel comemoraram durante sete dias a Festa das Barracas . O povo era uma enorme multidão de pessoas que tinham vindo do país inteiro, desde a subida de Hamate, no Norte, até a fronteira do Egito, no Sul.

'''

xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[Próximo Capítulo &#62;]