include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-18-1]]

^<<v11-18-1,1>>^ Algum tempo depois, no terceiro ano da seca, o Senhor  Deus disse a Elias: — Vá apresentar-se ao rei Acabe, pois eu vou mandar chover.

[[v11-18-2]]

^<<v11-18-2,2>>^ Então Elias saiu para se apresentar a Acabe. A falta de alimentos era muito grande em Samaria,

[[v11-18-3]]

^<<v11-18-3,3>>^ e por isso Acabe mandou chamar Obadias, o administrador do palácio. (Obadias era um fiel adorador do Senhor  Deus

[[v11-18-4]]

^<<v11-18-4,4>>^ e, quando Jezabel estava matando os profetas  do Senhor , Obadias escondeu cem profetas em dois grupos de cinquenta em cavernas e providenciou comida e água para eles.)

[[v11-18-5]]

^<<v11-18-5,5>>^ Acabe disse a Obadias: — Vamos dar uma olhada em todas as fontes e em todos os leitos dos riachos da nossa terra a fim de ver se achamos capim suficiente para conservar vivos os cavalos e as mulas. Pois pode ser que a gente não tenha de matar os nossos animais.

[[v11-18-6]]

^<<v11-18-6,6>>^ Eles combinaram que parte da região cada um devia examinar e saíram, cada um para o seu lado.

[[v11-18-7]]

^<<v11-18-7,7>>^ Obadias estava no caminho quando, de repente, se encontrou com Elias. Ele reconheceu Elias e se ajoelhou diante dele, encostou o rosto no chão e perguntou: — É o senhor mesmo? É o meu senhor Elias?

[[v11-18-8]]

^<<v11-18-8,8>>^ — Sim, eu sou Elias! — respondeu o profeta. — Vá dizer ao seu patrão, o rei, que eu estou aqui.

[[v11-18-9]]

^<<v11-18-9,9>>^ Mas Obadias disse: — O que foi que eu fiz para o senhor querer me pôr em perigo de ser morto pelo rei Acabe?

[[v11-18-10]]

^<<v11-18-10,10>>^ Juro pelo seu Deus vivo, o Senhor , que o rei mandou procurá-lo em todos os países da terra. Sempre que um rei mandava dizer que o senhor não estava no país dele, Acabe pedia a esse rei que jurasse que não havia sido possível encontrá-lo.

[[v11-18-11]]

^<<v11-18-11,11>>^ E agora o senhor quer que eu vá lhe dizer que está aqui?

[[v11-18-12]]

^<<v11-18-12,12>>^ Pode ser que logo que eu sair daqui o Espírito do Senhor  o leve para algum lugar desconhecido. Aí, quando eu contar a Acabe que o senhor está aqui, e ele não puder encontrá-lo, ele me matará. Lembre que desde menino eu tenho sido um fiel adorador de Deus, o Senhor .

[[v11-18-13]]

^<<v11-18-13,13>>^ Por acaso, não lhe contaram que, quando Jezabel estava matando os profetas de Deus, eu escondi cem deles em cavernas, em dois grupos de cinquenta, e providenciei comida e água para eles?

[[v11-18-14]]

^<<v11-18-14,14>>^ Como é então que agora o senhor está me mandando ir dizer ao rei que o senhor está aqui? Ele vai me matar!

[[v11-18-15]]

^<<v11-18-15,15>>^ Elias respondeu: — Pelo Senhor  Todo-Poderoso, a quem sirvo, eu prometo que hoje vou me apresentar ao rei.

[[v11-18-16]]

^<<v11-18-16,16>>^ Então Obadias foi encontrar-se com Acabe e lhe contou o que havia acontecido. Aí Acabe saiu para se encontrar com Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ Quando viu o profeta, Acabe disse: — Então é você que está aí, você, o maior criador de problemas de Israel!

[[v11-18-18]]

^<<v11-18-18,18>>^ — Eu não sou criador de problemas para o povo de Israel! — respondeu Elias. — Você e o seu pai é que são criadores de problemas, pois abandonaram os mandamentos do Senhor  Deus e adoraram as imagens de Baal .

[[v11-18-19]]

^<<v11-18-19,19>>^ Portanto, ordene agora a todo o povo de Israel que vá encontrar-se comigo no monte Carmelo. Mande também os quatrocentos e cinquenta profetas do deus Baal e os quatrocentos profetas da deusa Aserá  que são sustentados pela rainha Jezabel.

[[v11-18-20]]

^<<v11-18-20,20>>^ Então Acabe chamou todos os israelitas e os profetas de Baal para se reunirem no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ Elias chegou perto do povo e disse: — Até quando vocês vão ficar em dúvida sobre o que vão fazer? Se o Senhor  é Deus, adorem o Senhor ; mas, se Baal é Deus, adorem Baal! Porém o povo não respondeu nada.

[[v11-18-22]]

^<<v11-18-22,22>>^ Então Elias disse: — De todos os profetas de Deus, o Senhor , eu fui o único que sobrou, mas os profetas de Baal são quatrocentos e cinquenta.

[[v11-18-23]]

^<<v11-18-23,23>>^ Agora tragam dois touros. Que os profetas de Baal matem um deles, cortem em pedaços e ponham em cima da lenha, mas não ponham fogo! Eu farei a mesma coisa com o outro touro.

[[v11-18-24]]

^<<v11-18-24,24>>^ E aí os profetas de Baal vão orar ao seu deus, e eu orarei ao Senhor . O deus que responder mandando fogo, este é que é Deus. E todo o povo respondeu: — Está bem assim!

[[v11-18-25]]

^<<v11-18-25,25>>^ Então Elias disse aos profetas de Baal: — Já que vocês são tantos, peguem o touro e o preparem primeiro. Orem ao seu deus, porém não ponham fogo na lenha.

[[v11-18-26]]

^<<v11-18-26,26>>^ Os profetas de Baal pegaram o touro que havia sido trazido para eles, e o prepararam, e oraram a Baal desde a manhã até o meio-dia. Eles gritavam assim: — Ó Baal, responde às nossas orações! E ficaram dançando em volta do altar que haviam feito, porém não houve resposta.

[[v11-18-27]]

^<<v11-18-27,27>>^ Ao meio-dia, Elias começou a caçoar deles. Ele dizia: — Orem mais alto, pois ele é deus! Pode ser que esteja meditando ou que tenha ido ao banheiro. Talvez ele tenha viajado ou talvez esteja dormindo, e vocês terão de acordá-lo!

[[v11-18-28]]

^<<v11-18-28,28>>^ Aí os profetas oraram mais alto e começaram a se cortar com facas e punhais, conforme o costume deles, até que o sangue começou a correr.

[[v11-18-29]]

^<<v11-18-29,29>>^ Passou o meio-dia, e eles continuaram a orar e a gritar até a hora do sacrifício  da tarde; porém não se ouviu nenhum som.

[[v11-18-30]]

^<<v11-18-30,30>>^ Então Elias disse ao povo: — Cheguem para mais perto de mim. Todos chegaram mais perto de Elias, e ele começou a consertar o altar do Senhor  Deus, que estava derrubado.

[[v11-18-31]]

^<<v11-18-31,31>>^ Ele pegou doze pedras, uma para cada uma das doze tribos  que tinham os nomes dos filhos de Jacó, o homem a quem o Senhor  tinha dado o nome de Israel.

[[v11-18-32]]

^<<v11-18-32,32>>^ Com essas pedras Elias reconstruiu o altar para a adoração do Senhor . Depois cavou em volta uma valeta em que cabiam mais ou menos doze litros de água.

[[v11-18-33]]

^<<v11-18-33,33>>^ Em seguida colocou lenha no altar, cortou o touro em pedaços e os pôs em cima da lenha.

[[v11-18-34]]

^<<v11-18-34,34>>^ Então disse: — Encham quatro jarras com água e derramem sobre o animal sacrificado e sobre a lenha. Eles fizeram o que Elias estava mandando, e ele disse: — Façam de novo. E eles fizeram. — Façam pela terceira vez! — disse Elias. E eles fizeram.

[[v11-18-35]]

^<<v11-18-35,35>>^ A água correu em volta do altar e encheu a valeta.

[[v11-18-36]]

^<<v11-18-36,36>>^ Quando chegou a hora do sacrifício da tarde, o profeta Elias chegou perto do altar e orou assim: — Ó Senhor , Deus de Abraão, de Isaque e de Jacó! Prova agora que és o Deus de Israel, e que eu sou teu servo , e que fiz tudo isto de acordo com a tua ordem.

[[v11-18-37]]

^<<v11-18-37,37>>^ Responde-me, ó Senhor , responde-me, para que este povo saiba que tu, o Senhor , és Deus e estás trazendo este povo de volta para ti!

[[v11-18-38]]

^<<v11-18-38,38>>^ Então o Senhor  mandou fogo. E o fogo queimou o sacrifício, a lenha, as pedras, a terra e ainda secou a água que estava na valeta.

[[v11-18-39]]

^<<v11-18-39,39>>^ Quando viram isso, os israelitas se ajoelharam, encostaram o rosto no chão e gritaram: — O Senhor  é Deus! Só o Senhor  é Deus!

[[v11-18-40]]

^<<v11-18-40,40>>^ Elias ordenou: — Prendam os profetas de Baal! Não deixem escapar nenhum! Todos foram presos, e Elias fez com que descessem até o riacho de Quisom e ali os matou.

[[v11-18-41]]

^<<v11-18-41,41>>^ Então Elias disse ao rei Acabe: — Agora vá comer, pois eu já estou ouvindo o barulho de muita chuva.

[[v11-18-42]]

^<<v11-18-42,42>>^ Enquanto Acabe foi comer, Elias subiu até o alto do monte Carmelo. Ali ele se inclinou até o chão, pôs a cabeça entre os joelhos

[[v11-18-43]]

^<<v11-18-43,43>>^ e disse ao seu ajudante: — Vá e olhe para o lado do mar. O ajudante foi e voltou dizendo: — Não vi nada. Sete vezes Elias mandou que ele fosse olhar.

[[v11-18-44]]

^<<v11-18-44,44>>^ Na sétima vez, ele voltou e disse: — Eu vi subindo do mar uma nuvem pequena, do tamanho da mão de um homem. Então Elias mandou: — Vá aonde está o rei Acabe e lhe diga que apronte o carro e volte para casa; se não, a chuva não vai deixar.

[[v11-18-45]]

^<<v11-18-45,45>>^ Em pouco tempo o céu se cobriu de nuvens escuras, o vento começou a soprar, e uma chuva pesada começou a cair. Acabe entrou no seu carro e partiu de volta para Jezreel.

[[v11-18-46]]

^<<v11-18-46,46>>^ O poder do Senhor  Deus veio sobre Elias; ele apertou o seu cinto e correu na frente de Acabe todo o caminho até Jezreel.

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]