include::./index.adoc[]

[[v11-13-0]]
=== 1 Reis, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-13-1]]

^<<v11-13-1,1>>^ Por ordem do Senhor  Deus, um profeta  de Judá foi a Betel e chegou ali quando Jeroboão estava diante do altar para oferecer o sacrifício .

[[v11-13-2]]

^<<v11-13-2,2>>^ Seguindo a ordem do Senhor , o profeta falou assim contra o altar: — Ó altar, ó altar! O que o Senhor  Deus diz é isto: "Vai nascer um descendente de Davi que se chamará Josias. Em cima de você, ó altar, ele matará os sacerdotes que servem nos altares pagãos e que oferecem sacrifícios em cima de você. Ele também queimará ossos de gente sobre você."

[[v11-13-3]]

^<<v11-13-3,3>>^ E o profeta continuou: — Este altar cairá em pedaços, e as cinzas que estiverem nele se espalharão. Essa será a prova de que o Senhor  Deus falou por meio de mim.

[[v11-13-4]]

^<<v11-13-4,4>>^ Quando Jeroboão ouviu isso, apontou para o profeta e ordenou: — Prendam este homem! No mesmo instante, o braço do rei ficou paralisado, e ele não pôde fazê-lo voltar à posição normal.

[[v11-13-5]]

^<<v11-13-5,5>>^ E, de repente, o altar caiu em pedaços, e as cinzas se espalharam pelo chão, como o profeta, em nome do Senhor , tinha dito que ia acontecer.

[[v11-13-6]]

^<<v11-13-6,6>>^ Então o rei disse ao profeta: — Por favor, acalme o Senhor , seu Deus, e ore por mim para que ele cure o meu braço. O profeta fez o que o rei pediu, e o braço do rei sarou.

[[v11-13-7]]

^<<v11-13-7,7>>^ Então o rei disse: — Venha comigo até a minha casa e coma alguma coisa. Eu vou recompensar você pelo que fez.

[[v11-13-8]]

^<<v11-13-8,8>>^ Mas o profeta respondeu: — Mesmo que o senhor me desse a metade da sua riqueza, eu não iria com o senhor e não comeria, nem beberia nada neste lugar.

[[v11-13-9]]

^<<v11-13-9,9>>^ O Senhor  Deus mandou que eu não comesse, nem bebesse nada e que não voltasse para casa pelo mesmo caminho por onde vim.

[[v11-13-10]]

^<<v11-13-10,10>>^ E assim ele não voltou pelo mesmo caminho por onde tinha ido, mas voltou por outra estrada.

[[v11-13-11]]

^<<v11-13-11,11>>^ Naquele tempo havia um velho profeta  que morava em Betel. Os seus filhos chegaram e contaram a ele tudo o que o profeta de Judá tinha feito naquele dia em Betel e o que tinha dito ao rei Jeroboão.

[[v11-13-12]]

^<<v11-13-12,12>>^ Então o velho profeta perguntou: — Por onde ele foi embora? E eles lhe mostraram a estrada.

[[v11-13-13]]

^<<v11-13-13,13>>^ Ele pediu que os filhos pusessem a sela no seu jumento, e eles puseram. Então o profeta montou

[[v11-13-14]]

^<<v11-13-14,14>>^ e foi atrás do profeta de Judá. Ele o encontrou sentado debaixo de uma árvore sagrada e perguntou: — Você é o profeta de Judá? — Sou, sim! — respondeu o homem.

[[v11-13-15]]

^<<v11-13-15,15>>^ — Venha até a minha casa e coma alguma coisa comigo — convidou ele.

[[v11-13-16]]

^<<v11-13-16,16>>^ Mas o profeta de Judá respondeu: — Eu não posso ir até a sua casa, nem ficar hospedado lá. E também não vou comer, nem beber nada aqui com você

[[v11-13-17]]

^<<v11-13-17,17>>^ porque o Senhor  Deus mandou que eu não comesse, nem bebesse nada e que não voltasse para casa pelo mesmo caminho por onde vim.

[[v11-13-18]]

^<<v11-13-18,18>>^ Então o velho profeta disse: — Eu também sou profeta como você, e o Senhor  Deus mandou que um anjo me dissesse que levasse você até a minha casa e lhe oferecesse a minha hospitalidade. Mas ele estava mentindo.

[[v11-13-19]]

^<<v11-13-19,19>>^ Então o profeta de Judá foi com o velho profeta para a sua casa e comeu uma refeição com ele.

[[v11-13-20]]

^<<v11-13-20,20>>^ Enquanto estavam sentados à mesa, a palavra do Senhor  veio ao velho profeta,

[[v11-13-21]]

^<<v11-13-21,21>>^ e ele gritou para o profeta de Judá: — O Senhor  Deus diz que você desobedeceu e não fez o que ele mandou.

[[v11-13-22]]

^<<v11-13-22,22>>^ Em vez disso, voltou e comeu uma refeição num lugar onde ele havia mandado que você não comesse. Por causa disso, você será morto, e o seu corpo não será sepultado no túmulo da sua família.

[[v11-13-23]]

^<<v11-13-23,23>>^ Depois que acabaram de comer, o velho profeta selou o jumento para o profeta de Judá,

[[v11-13-24]]

^<<v11-13-24,24>>^ e este foi embora. No caminho, um leão o encontrou e matou. O corpo do profeta ficou jogado na estrada, e o leão e o jumento ficaram parados ali perto dele.

[[v11-13-25]]

^<<v11-13-25,25>>^ Alguns homens passaram por aquele lugar e viram o corpo jogado no caminho e o leão ali do lado. Então foram a Betel e contaram o que tinham visto.

[[v11-13-26]]

^<<v11-13-26,26>>^ Quando o velho profeta soube do que havia acontecido, disse: — Aquele é o profeta que desobedeceu às ordens de Deus, o Senhor . Foi por isso que o Senhor  mandou que um leão o atacasse e matasse, conforme tinha dito que ia fazer.

[[v11-13-27]]

^<<v11-13-27,27>>^ Então disse para os filhos: — Ponham a sela no meu jumento. Eles fizeram o que o pai pediu.

[[v11-13-28]]

^<<v11-13-28,28>>^ Então o velho foi e achou o corpo do profeta caído no caminho e o jumento e o leão parados perto dele. O leão não havia comido o corpo, nem despedaçado o jumento.

[[v11-13-29]]

^<<v11-13-29,29>>^ Aí o velho profeta pegou o corpo, pôs em cima do jumento e o levou de volta para Betel a fim de chorar sobre ele e sepultá-lo.

[[v11-13-30]]

^<<v11-13-30,30>>^ Ele o sepultou no seu próprio túmulo. Então ele e os seus filhos choraram sobre o corpo do profeta e diziam: — Ó meu irmão, meu irmão!

[[v11-13-31]]

^<<v11-13-31,31>>^ Depois do sepultamento, o velho disse aos filhos: — Quando eu morrer, me sepultem neste túmulo e ponham o meu corpo perto do dele.

[[v11-13-32]]

^<<v11-13-32,32>>^ Porque certamente vai se cumprir a ameaça que ele fez por ordem de Deus, o Senhor , contra o altar de Betel e contra os lugares pagãos de adoração que existem nas cidades da região de Samaria.

[[v11-13-33]]

^<<v11-13-33,33>>^ Ainda assim o rei Jeroboão não se arrependeu dos seus maus caminhos, mas continuou a escolher para sacerdotes homens de todo tipo a fim de servirem nos altares dos morros. O rei ordenava  como sacerdote desses altares qualquer um que queria ser sacerdote.

[[v11-13-34]]

^<<v11-13-34,34>>^ Esse seu pecado trouxe desgraça e destruição total para a sua família.

'''

xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[Próximo Capítulo &#62;]