include::./index.adoc[]

[[v11-19-0]]
=== 1 Reis, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-19-1]]

^<<v11-19-1,1>>^ O rei Acabe contou à sua esposa Jezabel tudo o que Elias havia feito e como havia matado à espada todos os profetas  do deus Baal .

[[v11-19-2]]

^<<v11-19-2,2>>^ Aí ela mandou um mensageiro a Elias com o seguinte recado: — Que os deuses me matem, se até amanhã a esta hora eu não fizer com você o mesmo que você fez com os profetas!

[[v11-19-3]]

^<<v11-19-3,3>>^ Elias ficou com medo e, para salvar a vida, fugiu com o seu ajudante para a cidade de Berseba, que ficava na região de Judá. Deixou ali o seu ajudante

[[v11-19-4]]

^<<v11-19-4,4>>^ e foi para o deserto, andando um dia inteiro. Aí parou, sentou-se na sombra de uma árvore e teve vontade de morrer. Então orou assim: — Já chega, ó Senhor  Deus! Acaba agora com a minha vida! Eu sou um fracasso, como foram os meus antepassados .

[[v11-19-5]]

^<<v11-19-5,5>>^ Elias se deitou debaixo da árvore e caiu no sono. De repente, um anjo tocou nele e disse: — Levante-se e coma.

[[v11-19-6]]

^<<v11-19-6,6>>^ Elias olhou em volta e viu perto da sua cabeça um pão assado nas pedras e uma jarra de água. Ele comeu, e bebeu, e dormiu de novo.

[[v11-19-7]]

^<<v11-19-7,7>>^ O anjo do Senhor  Deus voltou e tocou nele pela segunda vez, dizendo: — Levante-se e coma; se não, você não aguentará a viagem.

[[v11-19-8]]

^<<v11-19-8,8>>^ Elias se levantou, comeu e bebeu, e a comida lhe deu força bastante para andar quarenta dias e quarenta noites até o Sinai, o monte sagrado.

[[v11-19-9]]

^<<v11-19-9,9>>^ Ali ele entrou numa caverna para passar a noite, e, de repente, o Senhor  Deus lhe perguntou: — O que você está fazendo aqui, Elias?

[[v11-19-10]]

^<<v11-19-10,10>>^ Ele respondeu: — Ó Senhor , Deus Todo-Poderoso, eu sempre tenho servido a ti e só a ti. Mas o povo de Israel quebrou a sua aliança  contigo, derrubou os teus altares e matou todos os teus profetas. Eu sou o único que sobrou, e eles estão querendo me matar!

[[v11-19-11]]

^<<v11-19-11,11>>^ O Senhor  Deus disse: — Saia e vá ficar diante de mim no alto do monte. Então o Senhor  passou por ali e mandou um vento muito forte, que rachou os morros e quebrou as rochas em pedaços. Mas o Senhor  não estava no vento. Quando o vento parou de soprar, veio um terremoto; porém o Senhor  não estava no terremoto.

[[v11-19-12]]

^<<v11-19-12,12>>^ Depois do terremoto veio um fogo, mas o Senhor  não estava no fogo. E depois do fogo veio um sussurro calmo e suave.

[[v11-19-13]]

^<<v11-19-13,13>>^ Quando Elias ouviu o sussurro, cobriu o rosto com a capa . Então saiu e ficou na entrada da caverna. E uma voz lhe disse: — O que você está fazendo aqui, Elias?

[[v11-19-14]]

^<<v11-19-14,14>>^ Ele respondeu: — Ó Senhor , Deus Todo-Poderoso, eu sempre tenho servido a ti e só a ti. Mas o povo de Israel quebrou a sua aliança contigo, derrubou os teus altares e matou todos os teus profetas. Eu sou o único que sobrou, e eles estão querendo me matar!

[[v11-19-15]]

^<<v11-19-15,15>>^ Então o Senhor  Deus disse: — Volte para o deserto que fica perto de Damasco. Chegando lá, entre na cidade e unja  Hazael como rei da Síria.

[[v11-19-16]]

^<<v11-19-16,16>>^ Unja Jeú, filho de Ninsi, como rei de Israel e unja Eliseu, filho de Safate, de Abel-Meolá, como profeta, para ficar em lugar de você.

[[v11-19-17]]

^<<v11-19-17,17>>^ As pessoas que não forem mortas por Hazael serão mortas por Jeú, e todos os que escaparem de Jeú serão mortos por Eliseu.

[[v11-19-18]]

^<<v11-19-18,18>>^ Mas eu deixarei sete mil pessoas vivas em Israel, isto é, todos aqueles que não adoraram o deus Baal e não beijaram a sua imagem.

[[v11-19-19]]

^<<v11-19-19,19>>^ Elias saiu e encontrou Eliseu, que estava arando a terra. Na frente dele iam doze pares de bois, e ele estava arando com o último par. Elias passou perto de Eliseu e jogou a sua capa  em cima dele.

[[v11-19-20]]

^<<v11-19-20,20>>^ Então Eliseu largou os seus bois, correu atrás de Elias e disse: — Deixe que eu vá beijar o meu pai e a minha mãe e depois eu irei com você. Elias respondeu: — Está bem. Pode ir. Eu não estou impedindo.

[[v11-19-21]]

^<<v11-19-21,21>>^ Aí Eliseu deixou Elias e foi até o lugar onde estavam os dois bois e matou-os. Então fez fogo com a madeira da canga e cozinhou a carne. Depois deu a carne ao povo, e eles comeram. Então saiu, e foi com Elias, e ficou trabalhando como seu ajudante.

'''

xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[Próximo Capítulo &#62;]