include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-14-1]]

^<<v11-14-1,1>>^ Nesse tempo, o filho do rei Jeroboão, que se chamava Abias, ficou doente.

[[v11-14-2]]

^<<v11-14-2,2>>^ Jeroboão disse à sua mulher: — Ponha um disfarce para que ninguém possa reconhecer você e vá até Siló, onde mora Aías, o profeta  que disse que eu seria rei deste povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Leve para ele dez pães, alguns bolos e um jarro de mel. Pergunte o que vai acontecer com o nosso filho, que ele lhe dirá.

[[v11-14-4]]

^<<v11-14-4,4>>^ Então ela foi até a casa de Aías, em Siló. Aías tinha ficado cego por causa da velhice.

[[v11-14-5]]

^<<v11-14-5,5>>^ Mas Deus lhe disse que a mulher de Jeroboão vinha vindo perguntar sobre o filho dela, que estava doente. E Deus disse a Aías o que devia dizer a ela. A mulher de Jeroboão chegou, fazendo de conta que era outra pessoa.

[[v11-14-6]]

^<<v11-14-6,6>>^ Porém, quando ela vinha entrando pela porta, Aías ouviu o barulho dos seus passos e disse: — Entre, mulher de Jeroboão. Por que você está fingindo que é outra pessoa? Eu estou encarregado de lhe dar más notícias.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vá dizer a Jeroboão que o Senhor , o Deus de Israel, manda dizer a ele o seguinte: "Eu escolhi você do meio do povo e o tornei governador do meu povo de Israel.

[[v11-14-8]]

^<<v11-14-8,8>>^ Eu tomei o reino dos descendentes de Davi e dei a você. Mas você não tem sido como o meu servo  Davi, que foi fiel a mim em tudo, que obedeceu aos meus mandamentos e me seguiu com todo o coração, fazendo aquilo que eu aprovo.

[[v11-14-9]]

^<<v11-14-9,9>>^ Você tem pecado muito mais do que todos aqueles que foram reis antes de você. Você me rejeitou e me deixou irado  por ter feito ídolos e imagens de metal para adorar.

[[v11-14-10]]

^<<v11-14-10,10>>^ Por causa disso, eu vou trazer desgraça para a sua família e vou matar todos os seus descendentes do sexo masculino, tanto os jovens como os velhos. Vou varrer a sua família como se varre esterco.

[[v11-14-11]]

^<<v11-14-11,11>>^ As pessoas da sua família que morrerem na cidade serão comidas pelos cachorros e as que morrerem no campo serão comidas pelos urubus. Eu, o Senhor , falei."

[[v11-14-12]]

^<<v11-14-12,12>>^ E Aías ainda disse o seguinte à mulher de Jeroboão: — Agora volte para casa. Assim que você entrar na cidade, o seu filho vai morrer.

[[v11-14-13]]

^<<v11-14-13,13>>^ Todo o povo de Israel vai chorar por ele e vai sepultá-lo. O seu filho vai ser a única pessoa da família de Jeroboão que será sepultada porque ele foi o único de quem o Senhor , o Deus de Israel, se agradou.

[[v11-14-14]]

^<<v11-14-14,14>>^ O Senhor  vai pôr em Israel um rei que acabará com a família de Jeroboão. E já está acontecendo isso.

[[v11-14-15]]

^<<v11-14-15,15>>^ O Senhor  vai castigar o povo de Israel, que vai tremer de medo como varas verdes. Deus vai arrancar o povo de Israel desta terra boa que ele deu aos seus antepassados e vai espalhá-lo para além do rio Eufrates porque eles o deixaram irado, fazendo postes da deusa Aserá  para adorar.

[[v11-14-16]]

^<<v11-14-16,16>>^ Deus vai abandonar Israel porque Jeroboão pecou e fez com que o povo de Israel pecasse.

[[v11-14-17]]

^<<v11-14-17,17>>^ Aí a mulher de Jeroboão saiu e voltou para Tirza. Quando ela pôs os pés em casa, a criança morreu.

[[v11-14-18]]

^<<v11-14-18,18>>^ E todo o povo de Israel chorou pelo menino e o sepultou, conforme o Senhor  Deus tinha dito por meio do seu servo, o profeta Aías.

[[v11-14-19]]

^<<v11-14-19,19>>^ Todas as outras coisas que o rei Jeroboão fez, como guerreou e como governou, tudo isso está escrito na História dos Reis de Israel .

[[v11-14-20]]

^<<v11-14-20,20>>^ Jeroboão foi rei vinte e dois anos. Ele morreu e foi sepultado, e o seu filho Nadabe ficou no lugar dele como rei.

[[v11-14-21]]

^<<v11-14-21,21>>^ Roboão, filho de Salomão, tinha quarenta e um anos de idade quando se tornou rei de Judá. Ele governou dezessete anos em Jerusalém, a cidade que o Senhor  Deus havia escolhido entre todas as cidades da terra de Israel como o lugar onde devia ser adorado. A mãe de Roboão se chamava Naama e era do país de Amom.

[[v11-14-22]]

^<<v11-14-22,22>>^ O povo de Judá pecou contra o Senhor  e deu mais motivos para ele ficar irado  do que todos os seus antepassados haviam dado.

[[v11-14-23]]

^<<v11-14-23,23>>^ Eles construíram altares nos morros para a adoração de falsos deuses e, no alto dos morros e debaixo de árvores que dão sombra, levantaram colunas do deus Baal  e postes da deusa Aserá  para adorar.

[[v11-14-24]]

^<<v11-14-24,24>>^ E havia também homens e mulheres que serviam como prostitutos nesses lugares pagãos de adoração. O povo de Israel fez todas as coisas vergonhosas que faziam os povos que o Senhor  Deus havia expulsado da terra, conforme os israelitas iam avançando para dentro do país.

[[v11-14-25]]

^<<v11-14-25,25>>^ No quinto ano do reinado de Roboão, Sisaque, rei do Egito, atacou Jerusalém.

[[v11-14-26]]

^<<v11-14-26,26>>^ Sisaque levou embora todos os tesouros do Templo e do palácio e também os escudos  de ouro que Salomão havia feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ Para colocar no lugar deles, o rei Roboão fez escudos de bronze e os entregou aos oficiais encarregados de guardar os portões do palácio.

[[v11-14-28]]

^<<v11-14-28,28>>^ Sempre que o rei ia ao Templo, os guardas usavam os escudos e depois os levavam de volta para a sala dos guardas.

[[v11-14-29]]

^<<v11-14-29,29>>^ Todas as outras coisas que o rei Roboão fez estão escritas na História dos Reis de Judá .

[[v11-14-30]]

^<<v11-14-30,30>>^ Durante todo esse tempo, Roboão e Jeroboão estiveram em guerra um contra o outro.

[[v11-14-31]]

^<<v11-14-31,31>>^ Roboão morreu e foi sepultado nos túmulos dos reis, na Cidade de Davi , e o seu filho Abias ficou no lugar dele como rei. (A mãe de Roboão se chamava Naama e era do país de Amom.)

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]