include::./index.adoc[]

[[v11-17-0]]
=== 1 Reis, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-17-1]]

^<<v11-17-1,1>>^ Um profeta  chamado Elias, de Tisbé, na região de Gileade, disse ao rei Acabe: — Em nome do Senhor , o Deus vivo de Israel, de quem sou servo , digo ao senhor que não vai cair orvalho nem chuva durante os próximos anos, até que eu diga para cair orvalho e chuva de novo.

[[v11-17-2]]

^<<v11-17-2,2>>^ Então o Senhor  Deus disse a Elias:

[[v11-17-3]]

^<<v11-17-3,3>>^ — Saia daqui, vá para o leste e esconda-se perto do riacho de Querite, a leste do rio Jordão.

[[v11-17-4]]

^<<v11-17-4,4>>^ Você terá água do riacho para beber; e eu mandei que os corvos levem comida para você ali.

[[v11-17-5]]

^<<v11-17-5,5>>^ Elias obedeceu à ordem do Senhor  e foi e ficou morando perto do riacho de Querite.

[[v11-17-6]]

^<<v11-17-6,6>>^ Ele bebia água do riacho, e os corvos vinham trazer pão e carne todas as manhãs e todas as tardes.

[[v11-17-7]]

^<<v11-17-7,7>>^ Mas algum tempo depois o riacho secou por falta de chuva.

[[v11-17-8]]

^<<v11-17-8,8>>^ Então o Senhor  Deus disse a Elias:

[[v11-17-9]]

^<<v11-17-9,9>>^ — Apronte-se e vá até a cidade de Sarepta, perto de Sidom, e fique lá. Eu mandei que uma viúva que mora ali dê comida para você.

[[v11-17-10]]

^<<v11-17-10,10>>^ Então Elias foi para Sarepta. Quando estava chegando ao portão da cidade, ele encontrou a viúva, que estava catando lenha. Elias disse a ela: — Por favor, me dê um pouco de água para eu beber.

[[v11-17-11]]

^<<v11-17-11,11>>^ Quando ela ia indo buscar a água, ele a chamou e disse: — E traga pão também, por favor.

[[v11-17-12]]

^<<v11-17-12,12>>^ Porém ela respondeu: — Juro pelo seu Deus vivo, o Senhor , que não tenho mais pão. Só tenho um punhado de farinha de trigo numa tigela e um pouco de azeite num jarro. Estou aqui catando uns dois pedaços de pau para cozinhar alguma coisa para mim e para o meu filho. Vamos comer e depois morreremos de fome.

[[v11-17-13]]

^<<v11-17-13,13>>^ — Não se preocupe! — disse Elias. — Vá preparar a sua comida. Mas primeiro faça um pãozinho com a farinha que você tem e traga-o para mim. Depois prepare o resto para você e para o seu filho.

[[v11-17-14]]

^<<v11-17-14,14>>^ Pois o Senhor , o Deus de Israel, diz isto: "Não acabará a farinha da sua tigela, nem faltará azeite no seu jarro até o dia em que eu, o Senhor , fizer cair chuva."

[[v11-17-15]]

^<<v11-17-15,15>>^ Então a viúva foi e fez como Elias tinha dito. E todos eles tiveram comida para muitos dias.

[[v11-17-16]]

^<<v11-17-16,16>>^ Como o Senhor  havia prometido por meio de Elias, não faltou farinha na tigela nem azeite no jarro.

[[v11-17-17]]

^<<v11-17-17,17>>^ Algum tempo depois, o filho da viúva ficou doente. Ele foi ficando cada vez pior e acabou morrendo.

[[v11-17-18]]

^<<v11-17-18,18>>^ Então ela disse a Elias: — Homem de Deus, o que o senhor tem contra mim? Será que o senhor veio aqui para fazer com que Deus lembrasse dos meus pecados e assim provocar a morte do meu filho?

[[v11-17-19]]

^<<v11-17-19,19>>^ — Dê-me o seu filho! — disse Elias. Então pegou o menino dos braços da mãe e o levou para o andar de cima, para o quarto onde estava morando, e o colocou na sua cama.

[[v11-17-20]]

^<<v11-17-20,20>>^ Então orou em voz alta, assim: — Ó Senhor , meu Deus, por que fizeste esta coisa tão terrível para esta viúva? Ela me hospedou, e agora tu mataste o filho dela!

[[v11-17-21]]

^<<v11-17-21,21>>^ Aí Elias se deitou em cima do menino três vezes e orou deste modo: — Ó Senhor , meu Deus, faze com que esta criança viva de novo!

[[v11-17-22]]

^<<v11-17-22,22>>^ E o Senhor  Deus respondeu à oração de Elias. O menino começou a respirar outra vez e tornou a viver.

[[v11-17-23]]

^<<v11-17-23,23>>^ Elias pegou o menino, e o levou para baixo, para a sua mãe, e disse: — Veja! O seu filho está vivo!

[[v11-17-24]]

^<<v11-17-24,24>>^ Então ela disse a Elias: — Agora eu sei que o senhor é um homem de Deus e que Deus realmente fala por meio do senhor!

'''

xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[&#60; Capítulo Anterior] | <<v11-17-0,Topo>> | xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[Próximo Capítulo &#62;]