include::./index.adoc[]

[[v11-15-0]]
=== 1 Reis, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-15-1]]

^<<v11-15-1,1>>^ No ano dezoito do reinado de Jeroboão, filho de Nebate, em Israel, Abias se tornou rei de Judá.

[[v11-15-2]]

^<<v11-15-2,2>>^ Ele governou três anos em Jerusalém. A mãe dele se chamava Maacá e era filha de Absalão.

[[v11-15-3]]

^<<v11-15-3,3>>^ Abias cometeu os mesmos pecados que o seu pai havia cometido e não foi fiel em tudo ao Senhor , seu Deus, como o seu bisavô Davi tinha sido.

[[v11-15-4]]

^<<v11-15-4,4>>^ Mas, por causa de Davi, o Senhor , seu Deus, deu a Abias um filho para governar em Jerusalém depois dele e para conservar Jerusalém em segurança.

[[v11-15-5]]

^<<v11-15-5,5>>^ O Senhor  fez isso porque Davi tinha feito o que lhe agradava e nunca havia desobedecido a nenhum dos seus mandamentos, a não ser no caso de Urias, o heteu.

[[v11-15-6]]

^<<v11-15-6,6>>^ Abias e Jeroboão estiveram sempre em guerra um contra o outro durante o reinado de Abias.

[[v11-15-7]]

^<<v11-15-7,7>>^ Todas as outras coisas que Abias fez estão escritas na História dos Reis de Judá .

[[v11-15-8]]

^<<v11-15-8,8>>^ Abias morreu e foi sepultado na Cidade de Davi , e o seu filho Asa ficou no lugar dele como rei.

[[v11-15-9]]

^<<v11-15-9,9>>^ No ano vinte do reinado de Jeroboão em Israel, Asa se tornou rei de Judá

[[v11-15-10]]

^<<v11-15-10,10>>^ e governou quarenta e um anos em Jerusalém. A sua mãe se chamava Maacá e era filha de Absalão.

[[v11-15-11]]

^<<v11-15-11,11>>^ Asa fez o que agradava ao Senhor  Deus, como havia feito o seu antepassado Davi.

[[v11-15-12]]

^<<v11-15-12,12>>^ Asa expulsou do país todos os que praticavam a prostituição como parte dos cultos pagãos e retirou todos os ídolos feitos por aqueles que haviam sido reis antes dele.

[[v11-15-13]]

^<<v11-15-13,13>>^ Ele tirou a sua mãe Maacá da posição de rainha-mãe porque ela havia mandado fazer uma figura nojenta para servir como poste da deusa Aserá . Asa derrubou esse poste e o queimou no vale do Cedrom.

[[v11-15-14]]

^<<v11-15-14,14>>^ Ele não destruiu todos os lugares pagãos de adoração, porém foi fiel ao Senhor  Deus durante toda a sua vida.

[[v11-15-15]]

^<<v11-15-15,15>>^ Asa colocou no Templo todos os objetos que o seu pai havia separado para Deus e também os objetos de prata e de ouro que ele mesmo havia separado.

[[v11-15-16]]

^<<v11-15-16,16>>^ O rei Asa, de Judá, e o rei Baasa, de Israel, estiveram sempre em guerra um contra o outro durante todo o tempo em que ficaram no poder.

[[v11-15-17]]

^<<v11-15-17,17>>^ Baasa invadiu Judá e começou a cercar de muralhas a cidade de Ramá, para assim controlar o movimento na estrada que ia até Jerusalém.

[[v11-15-18]]

^<<v11-15-18,18>>^ Por isso, o rei Asa pegou toda a prata e todo o ouro que haviam ficado no Templo e no palácio e entregou a alguns dos seus servidores, a fim de que levassem para Damasco e entregassem ao rei Ben-Hadade, que era filho de Tabrimom e neto de Heziom. Junto foi a seguinte mensagem:

[[v11-15-19]]

^<<v11-15-19,19>>^ "Vamos ser aliados como eram os nossos pais. Esta prata e este ouro são um presente para você. Retire agora o apoio que você está dando a Baasa, rei de Israel, para que assim ele tenha de tirar os seus soldados do meu território."

[[v11-15-20]]

^<<v11-15-20,20>>^ O rei Ben-Hadade concordou com a proposta de Asa e mandou que os seus comandantes e os seus exércitos atacassem as cidades de Israel. Eles conquistaram as cidades de Ijom, Dã e Abel-Bete-Maacá, a região que fica perto do lago da Galileia, e todo o território de Naftali.

[[v11-15-21]]

^<<v11-15-21,21>>^ Quando o rei Baasa soube do que havia acontecido, parou de construir as muralhas de Ramá e voltou para Tirza.

[[v11-15-22]]

^<<v11-15-22,22>>^ O rei Asa mandou avisar em toda a região de Judá que todos, sem faltar ninguém, deviam ir ajudar a carregar para fora de Ramá as pedras e a madeira que Baasa havia estado usando para construir as muralhas em volta da cidade. Com esse material, Asa cercou de muralhas a cidade de Mispa e também a cidade de Geba, que ficava no território da tribo  de Benjamim.

[[v11-15-23]]

^<<v11-15-23,23>>^ Todas as outras coisas que o rei Asa fez, os seus atos de coragem e as cidades que ele cercou de muralhas, tudo isso está escrito na História dos Reis de Judá . Na sua velhice ele foi atacado por uma doença nos pés.

[[v11-15-24]]

^<<v11-15-24,24>>^ Asa morreu e foi sepultado nos túmulos dos reis, na Cidade de Davi . O seu filho Josafá ficou como rei no lugar dele.

[[v11-15-25]]

^<<v11-15-25,25>>^ No segundo ano do reinado de Asa em Judá, Nadabe, filho do rei Jeroboão, se tornou rei de Israel. Ele foi rei dois anos.

[[v11-15-26]]

^<<v11-15-26,26>>^ Como havia feito o seu pai antes dele, Nadabe pecou contra Deus e fez com que o povo de Israel também pecasse.

[[v11-15-27]]

^<<v11-15-27,27>>^ Baasa, filho de Aías, da tribo  de Issacar, fez uma conspiração contra Nadabe e o matou no país dos filisteus, em Gibetom, a cidade que Nadabe e o seu exército estavam cercando.

[[v11-15-28]]

^<<v11-15-28,28>>^ Isso aconteceu no terceiro ano do governo do rei Asa em Judá. E assim Baasa ficou no lugar de Nadabe como rei de Israel.

[[v11-15-29]]

^<<v11-15-29,29>>^ Logo que começou a reinar, ele matou as pessoas da família de Jeroboão. E, de acordo com o que o Senhor  Deus tinha dito por meio do seu servo , o profeta  Aías, de Siló, toda a família de Jeroboão foi morta; não escapou ninguém.

[[v11-15-30]]

^<<v11-15-30,30>>^ Isso aconteceu porque Jeroboão havia feito com que o Senhor , o Deus de Israel, ficasse irado  com os pecados que ele cometeu e que fez o povo de Israel cometer.

[[v11-15-31]]

^<<v11-15-31,31>>^ Todas as outras coisas que Nadabe fez estão escritas na História dos Reis de Israel .

[[v11-15-32]]

^<<v11-15-32,32>>^ O rei Asa, de Judá, e o rei Baasa, de Israel, estiveram em guerra um contra o outro durante todo o tempo em que ficaram no poder.

[[v11-15-33]]

^<<v11-15-33,33>>^ No terceiro ano do reinado de Asa em Judá, Baasa, filho de Aías, se tornou rei de todo o povo de Israel e governou vinte e quatro anos em Tirza.

[[v11-15-34]]

^<<v11-15-34,34>>^ Como o rei Jeroboão havia feito antes dele, Baasa pecou contra o Senhor  Deus e fez com que o povo de Israel também pecasse.

'''

xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[&#60; Capítulo Anterior] | <<v11-15-0,Topo>> | xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[Próximo Capítulo &#62;]