include::./index.adoc[]

[[v11-22-0]]
=== 1 Reis, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-22-1]]

^<<v11-22-1,1>>^ Durante os dois anos seguintes houve paz entre Israel e a Síria.

[[v11-22-2]]

^<<v11-22-2,2>>^ Mas, no terceiro ano, Josafá, rei de Judá, foi visitar o rei Acabe, de Israel.

[[v11-22-3]]

^<<v11-22-3,3>>^ Acabe perguntou aos seus oficiais: — Por que é que nós não fizemos nada para tomar de volta do rei da Síria a cidade de Ramote-Gileade? Vocês sabem que aquela cidade é nossa!

[[v11-22-4]]

^<<v11-22-4,4>>^ Então ele perguntou ao rei Josafá: — Você vai comigo atacar Ramote? Josafá respondeu: — Quando você estiver pronto para a batalha, eu também estarei; e assim também os meus soldados e a minha cavalaria.

[[v11-22-5]]

^<<v11-22-5,5>>^ Mas primeiro vamos consultar a Deus, o Senhor .

[[v11-22-6]]

^<<v11-22-6,6>>^ Aí Acabe mandou chamar os profetas , que eram uns quatrocentos, e perguntou: — Devo atacar a cidade de Ramote ou não? Eles responderam: — Ataque, pois Deus lhe dará a vitória.

[[v11-22-7]]

^<<v11-22-7,7>>^ Mas Josafá perguntou: — Não existe aqui mais nenhum profeta para nós consultarmos o Senhor  por meio dele?

[[v11-22-8]]

^<<v11-22-8,8>>^ Acabe respondeu: — Existe outro, que se chama Micaías, filho de Inla. Mas eu tenho ódio dele porque nunca profetiza  para mim o que é bom, mas só o que é ruim. — Não fale desse jeito! — disse Josafá.

[[v11-22-9]]

^<<v11-22-9,9>>^ Então Acabe chamou um oficial e mandou que ele fosse imediatamente buscar Micaías.

[[v11-22-10]]

^<<v11-22-10,10>>^ Os dois reis, usando as suas roupas reais, estavam sentados nos seus tronos, numa praça que ficava perto da entrada do portão de Samaria; e todos os profetas estavam profetizando em frente deles.

[[v11-22-11]]

^<<v11-22-11,11>>^ Um dos profetas, chamado Zedequias, filho de Quenaana, fez uns chifres de ferro e disse a Acabe: — O que o Senhor  Deus está dizendo é isto: "Com estes chifres o senhor lutará contra os sírios e os derrotará completamente."

[[v11-22-12]]

^<<v11-22-12,12>>^ E todos os profetas profetizaram a mesma coisa. Eles diziam: — Marche contra a cidade de Ramote, que o senhor, ó rei, vencerá. O Senhor  Deus lhe dará a vitória.

[[v11-22-13]]

^<<v11-22-13,13>>^ Enquanto isso, o oficial que tinha ido buscar Micaías disse a ele: — Todos os outros profetas profetizaram que o rei terá sucesso. É melhor que você faça o mesmo.

[[v11-22-14]]

^<<v11-22-14,14>>^ Porém Micaías respondeu: — Juro pelo Senhor , o Deus vivo, que eu falarei o que ele mesmo mandar!

[[v11-22-15]]

^<<v11-22-15,15>>^ Quando Micaías chegou ao lugar onde estava o rei Acabe, este perguntou: — Micaías, o rei Josafá e eu devemos atacar a cidade de Ramote ou não? Micaías respondeu: — Ataque, pois o senhor, ó rei, vencerá. O Senhor  Deus lhe dará a vitória…

[[v11-22-16]]

^<<v11-22-16,16>>^ Mas Acabe disse: — Quando você falar comigo em nome do Senhor  Deus, diga a verdade! Quantas vezes preciso dizer isso?

[[v11-22-17]]

^<<v11-22-17,17>>^ Micaías respondeu: — Vejo o exército de Israel espalhado pelos morros como ovelhas sem pastor. E o Senhor  Deus diz: "Estes homens não têm chefe; que eles voltem para casa em paz."

[[v11-22-18]]

^<<v11-22-18,18>>^ Então Acabe disse a Josafá: — Eu não disse que para mim ele nunca profetiza coisas boas? Ele sempre diz alguma coisa ruim!

[[v11-22-19]]

^<<v11-22-19,19>>^ Micaías continuou: — Agora escute o que o Senhor  Deus está dizendo! Eu vi o Senhor  sentado no seu trono no céu, com todos os seus anjos à sua direita e à sua esquerda.

[[v11-22-20]]

^<<v11-22-20,20>>^ Ele perguntou: "Quem enganará Acabe para que ele vá a Ramote e seja morto lá?" Alguns anjos disseram uma coisa, e outros disseram outra,

[[v11-22-21]]

^<<v11-22-21,21>>^ até que um espírito se apresentou e disse: "Eu enganarei Acabe."

[[v11-22-22]]

^<<v11-22-22,22>>^ E Deus perguntou: "Como?", e o espírito respondeu: "Eu irei e farei com que todos os profetas de Acabe digam mentiras." Então Deus ordenou: "Vá e engane Acabe. Você conseguirá."

[[v11-22-23]]

^<<v11-22-23,23>>^ E Micaías terminou, dizendo a Acabe: — O senhor está vendo agora que Deus fez com que todos estes seus profetas mentissem. Mas ele resolveu que vai acontecer uma desgraça com o senhor, ó rei.

[[v11-22-24]]

^<<v11-22-24,24>>^ Então o profeta Zedequias chegou perto de Micaías, deu um tapa na cara dele e perguntou: — Quando foi que o Espírito do Senhor  saiu de mim e falou com você?

[[v11-22-25]]

^<<v11-22-25,25>>^ — Você descobrirá isso quando entrar em algum quarto dos fundos, tentando se esconder! — respondeu Micaías.

[[v11-22-26]]

^<<v11-22-26,26>>^ Aí o rei Acabe deu a seguinte ordem a um dos seus oficiais: — Prenda Micaías e o leve a Amom, o governador da cidade, e ao príncipe Joás.

[[v11-22-27]]

^<<v11-22-27,27>>^ Diga a eles que o joguem na cadeia e o ponham a pão e água até que eu volte são e salvo.

[[v11-22-28]]

^<<v11-22-28,28>>^ Micaías exclamou: — Se o senhor, ó rei, voltar em paz, então, de fato, o Senhor  Deus não falou por meio de mim! E disse também: — Todos aqui deem atenção àquilo que eu profetizei!

[[v11-22-29]]

^<<v11-22-29,29>>^ Assim o rei Acabe, de Israel, e o rei Josafá, de Judá, foram atacar a cidade de Ramote-Gileade.

[[v11-22-30]]

^<<v11-22-30,30>>^ Acabe disse a Josafá: — Quando formos entrar na batalha, eu vou me disfarçar, mas você use as suas roupas de rei. E assim o rei de Israel entrou disfarçado na batalha.

[[v11-22-31]]

^<<v11-22-31,31>>^ O rei da Síria havia mandado que os trinta e dois capitães dos seus carros de guerra não atacassem ninguém, a não ser o rei de Israel.

[[v11-22-32]]

^<<v11-22-32,32>>^ Por isso, quando viram o rei Josafá, pensaram que ele era o rei de Israel e foram atacá-lo. Mas Josafá gritou,

[[v11-22-33]]

^<<v11-22-33,33>>^ e aí eles viram que aquele não era o rei de Israel e pararam de atacá-lo.

[[v11-22-34]]

^<<v11-22-34,34>>^ No entanto, um soldado sírio atirou uma flecha que por acaso atingiu o rei Acabe entre as juntas da sua armadura . Então ele gritou para o condutor do seu carro: — Fui ferido! Dê a volta e me leve para fora da batalha!

[[v11-22-35]]

^<<v11-22-35,35>>^ Enquanto a batalha ficava cada vez mais forte, seguraram o rei Acabe de pé no seu carro de guerra, de frente para os sírios. O sangue dele escorria do seu ferimento para o fundo do carro, e à tarde ele morreu.

[[v11-22-36]]

^<<v11-22-36,36>>^ Ao pôr do sol, foi dada ao exército dos israelitas a seguinte ordem: — Que cada homem volte para a sua própria região e para a sua cidade!

[[v11-22-37]]

^<<v11-22-37,37>>^ E assim morreu o rei Acabe. O seu corpo foi levado para Samaria e sepultado.

[[v11-22-38]]

^<<v11-22-38,38>>^ E, quando lavaram o carro dele na represa de Samaria, os cachorros lamberam o seu sangue, e as prostitutas se lavaram naquela água, como o Senhor  Deus tinha dito que ia acontecer.

[[v11-22-39]]

^<<v11-22-39,39>>^ Todas as outras coisas que o rei Acabe fez e também uma descrição do seu palácio enfeitado de marfim e todas as cidades que ele construiu, tudo isso está escrito na História dos Reis de Israel .

[[v11-22-40]]

^<<v11-22-40,40>>^ Quando Acabe morreu, o seu filho Acazias ficou no lugar dele como rei.

[[v11-22-41]]

^<<v11-22-41,41>>^ No quarto ano do reinado de Acabe em Israel, Josafá, filho de Asa, se tornou rei de Judá

[[v11-22-42]]

^<<v11-22-42,42>>^ com a idade de trinta e cinco anos. Ele governou em Jerusalém vinte e cinco anos. A sua mãe se chamava Azuba e era filha de Sili.

[[v11-22-43]]

^<<v11-22-43,43>>^ Como Asa, o seu pai, havia feito antes dele, Josafá fez o que o Senhor  Deus considerava certo.

[[v11-22-44]]

^<<v11-22-44,44>>^ Mas os lugares pagãos de adoração não foram destruídos, e neles o povo continuou a oferecer sacrifícios  e a queimar incenso.

[[v11-22-45]]

^<<v11-22-45,45>>^ Josafá viveu em paz com o rei de Israel.

[[v11-22-46]]

^<<v11-22-46,46>>^ Todas as outras coisas que Josafá fez, toda a sua coragem e as suas batalhas estão escritas na História dos Reis de Judá .

[[v11-22-47]]

^<<v11-22-47,47>>^ Ele acabou com todos os prostitutos e prostitutas que serviam nos altares pagãos que ainda haviam ficado desde o tempo de Asa, o seu pai.

[[v11-22-48]]

^<<v11-22-48,48>>^ O país de Edom não tinha rei e era governado por um governador nomeado pelo rei de Judá.

[[v11-22-49]]

^<<v11-22-49,49>>^ O rei Josafá construiu grandes navios para navegarem até a terra de Ofir e trazerem ouro; mas eles se quebraram em Eziom-Geber e nunca chegaram a navegar.

[[v11-22-50]]

^<<v11-22-50,50>>^ Então Acazias, filho de Acabe, ofereceu os seus marinheiros para viajarem junto com os marinheiros de Josafá, mas ele não quis.

[[v11-22-51]]

^<<v11-22-51,51>>^ Josafá morreu e foi sepultado nos túmulos dos reis, na Cidade de Davi , e o seu filho Jeorão ficou no lugar dele como rei.

[[v11-22-52]]

^<<v11-22-52,52>>^ No ano dezessete do reinado de Josafá em Judá, Acazias, filho de Acabe, se tornou rei de Israel e governou dois anos em Samaria.

[[v11-22-53]]

^<<v11-22-53,53>>^ Ele pecou contra Deus, seguindo o mau exemplo do seu pai Acabe, da sua mãe Jezabel e do rei Jeroboão, que havia feito o povo de Israel pecar.

[[v11-22-54]]

^<<v11-22-54,54>>^ Acazias adorou e serviu o deus Baal  e, como o seu pai havia feito antes dele, fez com que o Senhor , o Deus de Israel, ficasse irado .

'''

xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[Próximo Capítulo &#62;]