include::./index.adoc[]

[[v11-12-0]]
=== 1 Reis, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-12-1]]

^<<v11-12-1,1>>^ Roboão foi até Siquém, onde todo o povo de Israel se havia reunido para fazê-lo rei.

[[v11-12-2]]

^<<v11-12-2,2>>^ Jeroboão, filho de Nebate, que havia fugido do rei Salomão e ido para o Egito, soube disso e voltou de lá.

[[v11-12-3]]

^<<v11-12-3,3>>^ O povo das tribos  do Norte mandou buscá-lo, e foram todos juntos falar com Roboão. Eles disseram:

[[v11-12-4]]

^<<v11-12-4,4>>^ — Salomão, o seu pai, nos tratou com dureza e nos fez carregar cargas pesadas. Se o senhor tornar essas cargas mais leves e a nossa vida mais fácil, nós seremos seus servidores.

[[v11-12-5]]

^<<v11-12-5,5>>^ Roboão respondeu: — Voltem daqui a três dias, e aí eu darei a minha resposta. Então eles foram embora.

[[v11-12-6]]

^<<v11-12-6,6>>^ O rei Roboão foi falar com os homens mais velhos, que haviam sido os conselheiros do seu pai, e perguntou: — Que resposta vocês me aconselham a dar a este povo?

[[v11-12-7]]

^<<v11-12-7,7>>^ Eles disseram: — Se o senhor quiser servir bem a este povo, dê uma resposta favorável ao pedido deles, que eles serão seus servidores para sempre.

[[v11-12-8]]

^<<v11-12-8,8>>^ Mas Roboão não seguiu o conselho dos homens mais velhos e foi falar com os jovens que haviam crescido junto com ele e que agora eram os seus conselheiros.

[[v11-12-9]]

^<<v11-12-9,9>>^ — Que conselho vocês me dão? — perguntou ele. — O que é que eu digo a este povo que está pedindo que eu torne as suas cargas mais leves?

[[v11-12-10]]

^<<v11-12-10,10>>^ Eles responderam: — Você deve dizer o seguinte: "O meu dedinho é mais grosso do que a cintura do meu pai!

[[v11-12-11]]

^<<v11-12-11,11>>^ Ele fez vocês carregarem cargas pesadas; eu vou aumentar o peso ainda mais. Ele castigou vocês com chicotes; eu vou surrá-los com correias."

[[v11-12-12]]

^<<v11-12-12,12>>^ Três dias depois, Jeroboão e todo o povo foram falar de novo com o rei Roboão, como ele havia mandado.

[[v11-12-13]]

^<<v11-12-13,13>>^ O rei desprezou o conselho dos homens mais velhos e falou duramente com o povo,

[[v11-12-14]]

^<<v11-12-14,14>>^ como os jovens haviam aconselhado. Ele disse: — O meu pai fez vocês carregarem cargas pesadas; eu vou aumentar o peso ainda mais. Ele castigou vocês com chicotes; eu vou surrá-los com correias.

[[v11-12-15]]

^<<v11-12-15,15>>^ Assim o rei Roboão não atendeu o povo. O Senhor  Deus fez com que isso acontecesse para confirmar aquilo que ele, por meio do profeta  Aías, de Siló, tinha dito a Jeroboão, filho de Nebate.

[[v11-12-16]]

^<<v11-12-16,16>>^ Quando os israelitas viram que o rei não ia atender o seu pedido, começaram a gritar: — Abaixo Davi e a sua família! O que foi que eles já fizeram por nós? Homens de Israel, vamos para casa! Que Roboão cuide de si mesmo! E assim os israelitas foram para as suas casas,

[[v11-12-17]]

^<<v11-12-17,17>>^ deixando Roboão como rei somente do povo que morava no território da tribo de Judá.

[[v11-12-18]]

^<<v11-12-18,18>>^ Então o rei Roboão mandou que Adonirão, o encarregado dos trabalhadores forçados, fosse falar com os israelitas, mas eles o mataram a pedradas. Porém Roboão saltou depressa para o seu carro de guerra e fugiu para Jerusalém.

[[v11-12-19]]

^<<v11-12-19,19>>^ Desde aquela época até hoje , o povo de Israel, o Reino do Norte, está revoltado contra os reis descendentes de Davi.

[[v11-12-20]]

^<<v11-12-20,20>>^ O povo de Israel soube que Jeroboão havia voltado do Egito. Então eles o convidaram para uma reunião com todo o povo e o fizeram rei de Israel. Somente a tribo de Judá ficou fiel aos descendentes de Davi.

[[v11-12-21]]

^<<v11-12-21,21>>^ Quando Roboão chegou a Jerusalém, reuniu cento e oitenta mil dos melhores soldados das tribos  de Judá e de Benjamim, pois tinha a intenção de sair para lutar contra as tribos do Norte de Israel e ser o rei delas de novo.

[[v11-12-22]]

^<<v11-12-22,22>>^ Mas o Senhor  falou ao profeta  Semaías e mandou

[[v11-12-23]]

^<<v11-12-23,23>>^ que desse a Roboão e a todo o povo das tribos de Judá e de Benjamim o seguinte recado:

[[v11-12-24]]

^<<v11-12-24,24>>^ "Não ataquem os seus próprios irmãos, o povo de Israel. Voltem todos para casa! Se tudo aconteceu assim, foi porque eu quis." Então eles obedeceram à ordem de Deus, o Senhor , e voltaram para casa.

[[v11-12-25]]

^<<v11-12-25,25>>^ O rei Jeroboão, de Israel, cercou de muralhas a cidade de Siquém, na região montanhosa de Efraim, e morou um pouco de tempo ali. Depois saiu e cercou de muralhas a cidade de Penuel.

[[v11-12-26]]

^<<v11-12-26,26>>^ Então pensou: "Do jeito que as coisas estão, se o meu povo for a Jerusalém oferecer no Templo sacrifícios  ao Senhor  Deus, os corações deles vão cair para o lado de Roboão, rei de Judá, e eles me matarão."

[[v11-12-27]]

^<<v11-12-27,27>>^ Então pensou: "Do jeito que as coisas estão, se o meu povo for a Jerusalém oferecer no Templo sacrifícios  ao Senhor  Deus, os corações deles vão cair para o lado de Roboão, rei de Judá, e eles me matarão."

[[v11-12-28]]

^<<v11-12-28,28>>^ Por isso, ele fez dois touros de ouro e disse ao seu povo: — Já chega de ir a Jerusalém para adorar a Deus. Povo de Israel, aqui estão os seus deuses, que tiraram vocês do Egito!

[[v11-12-29]]

^<<v11-12-29,29>>^ Ele colocou um dos touros de ouro em Betel e o outro em Dã.

[[v11-12-30]]

^<<v11-12-30,30>>^ E assim o povo pecou, indo adorar em Betel e em Dã.

[[v11-12-31]]

^<<v11-12-31,31>>^ Jeroboão também construiu lugares de adoração no alto dos morros e escolheu para sacerdotes homens que não eram da tribo  de Levi.

[[v11-12-32]]

^<<v11-12-32,32>>^ Jeroboão também deu ordem para que houvesse uma festa religiosa no dia quinze do oitavo mês, como a festa que se realizava no Reino de Judá. No altar de Betel ele ofereceu sacrifícios  aos touros de ouro que havia feito e pôs ali em Betel os sacerdotes que serviam nos lugares de adoração que ele havia construído nos morros.

'''

xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[&#60; Capítulo Anterior] | <<v11-12-0,Topo>> | xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[Próximo Capítulo &#62;]