include::./index.adoc[]

[[v11-16-0]]
=== 1 Reis, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-16-1]]

^<<v11-16-1,1>>^ O Senhor  Deus falou com o profeta  Jeú, filho de Hanani, e lhe deu esta mensagem a respeito de Baasa:

[[v11-16-2]]

^<<v11-16-2,2>>^ "Você não era ninguém, mas eu fiz com que você se tornasse o chefe do meu povo de Israel. E agora você pecou como Jeroboão e fez o meu povo pecar. Os pecados deles me fizeram ficar irado ,

[[v11-16-3]]

^<<v11-16-3,3>>^ e por isso vou acabar com você e com a sua família, como fiz com Jeroboão.

[[v11-16-4]]

^<<v11-16-4,4>>^ As pessoas da sua família que morrerem na cidade serão comidas pelos cachorros, e aquelas que morrerem nos campos serão comidas pelos urubus."

[[v11-16-5]]

^<<v11-16-5,5>>^ Todas as outras coisas que Baasa fez e todos os seus atos de coragem estão escritos na História dos Reis de Israel .

[[v11-16-6]]

^<<v11-16-6,6>>^ Baasa morreu e foi sepultado em Tirza, e o seu filho Elá ficou como rei no lugar dele.

[[v11-16-7]]

^<<v11-16-7,7>>^ O profeta Jeú deu aquela mensagem do Senhor  Deus a respeito de Baasa e da sua família por causa dos pecados que Baasa havia cometido contra o Senhor . Ele fez com que o Senhor  ficasse irado não somente por causa do mal que praticou, como o rei Jeroboão havia feito antes dele, mas também porque ele matou toda a família de Jeroboão.

[[v11-16-8]]

^<<v11-16-8,8>>^ No ano vinte e seis do reinado de Asa em Judá, Elá, filho de Baasa, se tornou rei de Israel e governou dois anos em Tirza.

[[v11-16-9]]

^<<v11-16-9,9>>^ Zinri, um dos seus oficiais, que comandava a metade dos seus carros de guerra, fez uma conspiração contra ele. Certo dia em Tirza, Elá estava se embebedando na casa de Arsa, que era o administrador do palácio.

[[v11-16-10]]

^<<v11-16-10,10>>^ Zinri entrou na casa, matou Elá e ficou no lugar dele como rei. Isso aconteceu no ano vinte e sete do reinado de Asa em Judá.

[[v11-16-11]]

^<<v11-16-11,11>>^ Assim que Zinri se tornou rei, matou todas as pessoas da família de Baasa. Todos os seus parentes do sexo masculino e todos os seus amigos foram mortos.

[[v11-16-12]]

^<<v11-16-12,12>>^ E assim Zinri matou toda a família de Baasa, de acordo com aquilo que o Senhor , por meio do profeta  Jeú, tinha dito a respeito de Baasa.

[[v11-16-13]]

^<<v11-16-13,13>>^ Por terem adorado ídolos e por terem feito com que o povo de Israel pecasse, Baasa e o seu filho Elá haviam feito o Senhor , o Deus de Israel, ficar irado .

[[v11-16-14]]

^<<v11-16-14,14>>^ Todas as outras coisas que Elá fez estão escritas na História dos Reis de Israel .

[[v11-16-15]]

^<<v11-16-15,15>>^ No ano vinte e sete do reinado de Asa em Judá, Zinri foi rei de todo o povo de Israel, em Tirza, durante sete dias. Os soldados israelitas estavam cercando a cidade de Gibetom, na terra dos filisteus.

[[v11-16-16]]

^<<v11-16-16,16>>^ Eles souberam que Zinri havia feito uma conspiração contra o rei e que o havia assassinado. Por isso, naquele mesmo dia ali no acampamento, eles escolheram Onri, o comandante do exército, como rei de Israel.

[[v11-16-17]]

^<<v11-16-17,17>>^ Onri e todos os seus soldados saíram de Gibetom e foram cercar a cidade de Tirza.

[[v11-16-18]]

^<<v11-16-18,18>>^ Quando Zinri viu que a cidade havia sido conquistada, foi para a fortaleza interna do palácio, pôs fogo no palácio e morreu queimado.

[[v11-16-19]]

^<<v11-16-19,19>>^ Isso aconteceu por causa dos seus pecados contra Deus, o Senhor . Ele seguiu o exemplo de Jeroboão, que havia sido rei antes dele; Zinri desagradou ao Senhor  por causa dos seus pecados e por ter feito o povo de Israel pecar.

[[v11-16-20]]

^<<v11-16-20,20>>^ Todas as outras coisas que Zinri fez e também a sua conspiração estão escritas na História dos Reis de Israel .

[[v11-16-21]]

^<<v11-16-21,21>>^ O povo de Israel estava dividido em dois partidos. A metade deles queria fazer de Tibni, filho de Ginate, o seu rei, e os outros estavam do lado de Onri.

[[v11-16-22]]

^<<v11-16-22,22>>^ Mas aqueles que estavam a favor de Onri ganharam; Tibni morreu, e Onri se tornou rei.

[[v11-16-23]]

^<<v11-16-23,23>>^ No ano trinta e um do reinado de Asa em Judá, Onri se tornou rei de Israel e governou doze anos. Nos seis primeiros anos ele governou em Tirza.

[[v11-16-24]]

^<<v11-16-24,24>>^ Então comprou o monte de Samaria de um homem chamado Semer por mais ou menos setenta quilos de prata. Onri fez defesas militares no monte, construiu ali uma cidade e a chamou de Samaria, por causa do nome de Semer, que havia sido o primeiro dono do monte.

[[v11-16-25]]

^<<v11-16-25,25>>^ Onri pecou contra o Senhor  Deus mais do que todos aqueles que haviam sido reis antes dele.

[[v11-16-26]]

^<<v11-16-26,26>>^ Como Jeroboão havia feito antes dele, Onri fez com que o Senhor , o Deus de Israel, ficasse irado  por causa dos seus pecados e por fazer o povo de Israel adorar ídolos.

[[v11-16-27]]

^<<v11-16-27,27>>^ Todas as outras coisas que Onri fez e todas as suas realizações estão escritas na História dos Reis de Israel .

[[v11-16-28]]

^<<v11-16-28,28>>^ Onri morreu e foi sepultado em Samaria, e o seu filho Acabe ficou como rei no lugar dele.

[[v11-16-29]]

^<<v11-16-29,29>>^ No ano trinta e oito do reinado de Asa em Judá, Acabe, filho de Onri, se tornou rei de Israel e governou vinte e dois anos em Samaria.

[[v11-16-30]]

^<<v11-16-30,30>>^ Ele pecou contra o Senhor  Deus mais do que qualquer um dos que haviam sido reis antes dele.

[[v11-16-31]]

^<<v11-16-31,31>>^ Não se contentando em pecar como o rei Jeroboão, Acabe fez pior e casou com Jezabel, filha de Etbaal, rei de Sidom, e adorou o deus Baal .

[[v11-16-32]]

^<<v11-16-32,32>>^ Acabe construiu um templo para Baal em Samaria, fez para ele um altar e o colocou no templo.

[[v11-16-33]]

^<<v11-16-33,33>>^ Levantou também um poste da deusa Aserá  e assim fez mais coisas para deixar o Senhor  Deus irado  do que todos os reis de Israel haviam feito antes dele.

[[v11-16-34]]

^<<v11-16-34,34>>^ Durante o reinado de Acabe, Hiel, que era de Betel, reconstruiu a cidade de Jericó. E, como o Senhor  tinha dito por meio de Josué, filho de Num, Hiel perdeu Abirão, o seu filho mais velho, quando colocou os alicerces de Jericó, e perdeu Segube, o seu filho mais novo, quando colocou os portões.

'''

xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[Próximo Capítulo &#62;]