include::./index.adoc[]

[[v11-10-0]]
=== 1 Reis, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v11-10-1]]

^<<v11-10-1,1>>^ A rainha de Sabá ouviu falar da fama de Salomão e foi até Jerusalém a fim de pô-lo à prova com perguntas difíceis.

[[v11-10-2]]

^<<v11-10-2,2>>^ Ela chegou com um grande grupo de servidores e também com camelos carregados de especiarias , pedras preciosas e uma grande quantidade de ouro. Quando se encontrou com Salomão, ela lhe fez todas as perguntas que pôde imaginar.

[[v11-10-3]]

^<<v11-10-3,3>>^ Ele respondeu a todas; não houve nenhuma que fosse difícil demais para ele responder.

[[v11-10-4]]

^<<v11-10-4,4>>^ A rainha de Sabá ouviu a sabedoria de Salomão e viu o palácio que ele havia construído.

[[v11-10-5]]

^<<v11-10-5,5>>^ Ela viu a comida que era servida na mesa dele, viu os apartamentos dos seus altos funcionários, a organização do pessoal que trabalhava no palácio e os uniformes que eles usavam. Viu os empregados que o serviam nas festas e os sacrifícios  que ele oferecia no Templo. Isso tudo a deixou de boca aberta e muito admirada.

[[v11-10-6]]

^<<v11-10-6,6>>^ Então ela disse ao rei Salomão: — Tudo aquilo que eu ouvi no meu país a respeito de você e da sua sabedoria é, de fato, verdade.

[[v11-10-7]]

^<<v11-10-7,7>>^ Porém eu não pude acreditar até que vim e vi com os meus próprios olhos. Acontece que não tinham me contado nem a metade. A sua sabedoria e a sua riqueza são muito maiores do que ouvi dizer.

[[v11-10-8]]

^<<v11-10-8,8>>^ Como são felizes as suas esposas! Que sorte têm os seus servidores, que estão sempre ao seu lado e têm o privilégio de ouvir os seus sábios provérbios!

[[v11-10-9]]

^<<v11-10-9,9>>^ Bendito seja o Senhor , seu Deus, que ficou tão contente com você, que o tornou rei de Israel! O amor dele por Israel é eterno; por isso, ele o tornou rei de Israel, para que você possa manter a lei  e a justiça.

[[v11-10-10]]

^<<v11-10-10,10>>^ Ela entregou ao rei os presentes que havia trazido: mais de quatro mil quilos de ouro e uma grande quantidade de especiarias e pedras preciosas. Nunca mais veio uma quantidade tão grande de especiarias como a que a rainha de Sabá deu a Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ (Os navios de Hirão, que haviam trazido ouro da terra de Ofir, também trouxeram de lá uma grande quantidade de madeira de sândalo e pedras preciosas.

[[v11-10-12]]

^<<v11-10-12,12>>^ Salomão usou a madeira para fazer corrimãos para o Templo e para o palácio e também fez harpas  e liras  para os músicos. Foi a primeira vez que se viu essa madeira em Israel, e até hoje  nunca mais se viu ali madeira igual àquela.)

[[v11-10-13]]

^<<v11-10-13,13>>^ O rei Salomão deu à rainha de Sabá tudo o que ela quis e pediu, além de todos os outros presentes de costume. Então a rainha e os seus servidores voltaram para Sabá, a sua terra.

[[v11-10-14]]

^<<v11-10-14,14>>^ Todos os anos o rei Salomão recebia mais ou menos vinte e três mil quilos de ouro,

[[v11-10-15]]

^<<v11-10-15,15>>^ além dos impostos pagos pelos comerciantes, dos lucros do comércio e dos impostos pagos pelos reis árabes e pelos administradores dos vários distritos do país.

[[v11-10-16]]

^<<v11-10-16,16>>^ Salomão fez duzentos grandes escudos  e mandou folhear cada um com quase sete quilos de ouro.

[[v11-10-17]]

^<<v11-10-17,17>>^ Também fez trezentos escudos menores e folheou cada um com quase dois quilos de ouro. Ele mandou colocar todos esses escudos no Salão da Floresta do Líbano .

[[v11-10-18]]

^<<v11-10-18,18>>^ Salomão também mandou fazer um grande trono, revestido de marfim e de ouro puro.

[[v11-10-19]]

^<<v11-10-19,19>>^ O trono tinha seis degraus, com a figura de um leão nas pontas de cada degrau, isto é, havia doze leões ao todo. Atrás do trono havia uma figura de cabeça de touro e no lado de cada um dos dois braços do trono havia a figura de um leão. Nunca havia existido em outro reino um trono como esse.

[[v11-10-20]]

^<<v11-10-20,20>>^ O trono tinha seis degraus, com a figura de um leão nas pontas de cada degrau, isto é, havia doze leões ao todo. Atrás do trono havia uma figura de cabeça de touro e no lado de cada um dos dois braços do trono havia a figura de um leão. Nunca havia existido em outro reino um trono como esse.

[[v11-10-21]]

^<<v11-10-21,21>>^ Todas as taças que o rei Salomão usava para beber eram de ouro, e todos os objetos do Salão da Floresta do Líbano eram de ouro puro. Não se usou prata porque no tempo de Salomão esse metal era considerado sem valor.

[[v11-10-22]]

^<<v11-10-22,22>>^ Salomão tinha uma frota de navios que viajava junto com a frota de Hirão. Cada três anos a sua frota voltava trazendo ouro, prata, marfim, macacos e micos.

[[v11-10-23]]

^<<v11-10-23,23>>^ O rei Salomão era mais rico e mais sábio do que qualquer outro rei,

[[v11-10-24]]

^<<v11-10-24,24>>^ e pessoas do mundo inteiro queriam ir ouvir a sabedoria que Deus lhe tinha dado.

[[v11-10-25]]

^<<v11-10-25,25>>^ Todos aqueles que chegavam traziam um presente para ele: objetos de prata e de ouro, roupas, armas, especiarias , cavalos e mulas. E foi assim ano após ano.

[[v11-10-26]]

^<<v11-10-26,26>>^ Salomão ajuntou mil e quatrocentos carros de guerra e doze mil cavalos de cavalaria. Espalhou uma parte deles por várias cidades e deixou o resto em Jerusalém.

[[v11-10-27]]

^<<v11-10-27,27>>^ Em Jerusalém, durante o seu reinado, a prata era tão comum como as pedras, e havia tantos cedros como as figueiras bravas que existem nas planícies de Judá.

[[v11-10-28]]

^<<v11-10-28,28>>^ Os agentes do rei controlavam a importação de cavalos de Musri e da Cilícia

'''

xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]