include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-22-1]]

^<<v42-22-1,1>>^ Faltava pouco tempo para a Festa dos Pães sem Fermento , chamada Páscoa .

[[v42-22-2]]

^<<v42-22-2,2>>^ Os chefes dos sacerdotes e os mestres  da Lei procuravam um jeito para matar Jesus em segredo porque tinham medo do povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Então Satanás entrou em Judas, chamado Iscariotes, que era um dos doze discípulos.

[[v42-22-4]]

^<<v42-22-4,4>>^ Judas foi falar com os chefes dos sacerdotes e com os oficiais da guarda do Templo para combinar a maneira como ele ia lhes entregar Jesus.

[[v42-22-5]]

^<<v42-22-5,5>>^ Eles ficaram muito contentes e prometeram dar dinheiro a ele.

[[v42-22-6]]

^<<v42-22-6,6>>^ Judas aceitou e começou a procurar uma oportunidade para entregar Jesus a eles, sem que o povo ficasse sabendo.

[[v42-22-7]]

^<<v42-22-7,7>>^ Chegou o dia da Festa dos Pães sem Fermento , dia em que os judeus matavam carneirinhos para comemorar a Páscoa .

[[v42-22-8]]

^<<v42-22-8,8>>^ Então Jesus deu a Pedro e a João a seguinte ordem: — Vão e preparem para nós o jantar da Páscoa.

[[v42-22-9]]

^<<v42-22-9,9>>^ Eles perguntaram: — Onde o senhor quer que a gente prepare o jantar?

[[v42-22-10]]

^<<v42-22-10,10>>^ Jesus respondeu: — Escutem! Quando entrarem na cidade, um homem carregando um pote de água vai se encontrar com vocês. Sigam esse homem até a casa onde ele entrar

[[v42-22-11]]

^<<v42-22-11,11>>^ e digam ao dono dela: "O Mestre mandou perguntar a você onde fica a sala em que ele e os seus discípulos vão comer o jantar da Páscoa."

[[v42-22-12]]

^<<v42-22-12,12>>^ Então ele mostrará a vocês uma grande sala mobiliada, no andar de cima. Preparem ali o jantar.

[[v42-22-13]]

^<<v42-22-13,13>>^ Os dois discípulos foram até a cidade e encontraram tudo como Jesus tinha dito. Então prepararam o jantar da Páscoa.

[[v42-22-14]]

^<<v42-22-14,14>>^ Quando chegou a hora, Jesus sentou-se à mesa com os apóstolos

[[v42-22-15]]

^<<v42-22-15,15>>^ e lhes disse: — Como tenho desejado comer este jantar da Páscoa  com vocês, antes do meu sofrimento!

[[v42-22-16]]

^<<v42-22-16,16>>^ Pois eu digo a vocês que nunca comerei este jantar até que eu coma o verdadeiro jantar que haverá no Reino de Deus .

[[v42-22-17]]

^<<v42-22-17,17>>^ Então Jesus pegou o cálice de vinho, deu graças a Deus e disse: — Peguem isto e repartam entre vocês.

[[v42-22-18]]

^<<v42-22-18,18>>^ Pois eu afirmo a vocês que nunca mais beberei deste vinho até que chegue o Reino de Deus.

[[v42-22-19]]

^<<v42-22-19,19>>^ Depois pegou o pão e deu graças a Deus. Em seguida partiu o pão e o deu aos apóstolos, dizendo: — Isto é o meu corpo que é entregue em favor de vocês. Façam isto em memória de mim.

[[v42-22-20]]

^<<v42-22-20,20>>^ Depois do jantar, do mesmo modo deu a eles o cálice de vinho, dizendo: — Este cálice é a nova aliança  feita por Deus com o seu povo, aliança que é garantida pelo meu sangue, derramado em favor de vocês.

[[v42-22-21]]

^<<v42-22-21,21>>^ Mas vejam: o traidor está aqui sentado comigo à mesa!

[[v42-22-22]]

^<<v42-22-22,22>>^ Pois o Filho do Homem  vai morrer da maneira como Deus já resolveu. Mas ai daquele que está traindo o Filho do Homem!

[[v42-22-23]]

^<<v42-22-23,23>>^ Então os apóstolos começaram a perguntar uns aos outros quem seria o traidor.

[[v42-22-24]]

^<<v42-22-24,24>>^ Os apóstolos  tiveram uma forte discussão sobre qual deles deveria ser considerado o mais importante.

[[v42-22-25]]

^<<v42-22-25,25>>^ Então Jesus disse: — Os reis deste mundo têm poder sobre o povo, e os governadores são chamados de "Amigos do Povo".

[[v42-22-26]]

^<<v42-22-26,26>>^ Mas entre vocês não pode ser assim. Pelo contrário, o mais importante deve ser como o menos importante; e o que manda deve ser como o que é mandado.

[[v42-22-27]]

^<<v42-22-27,27>>^ Quem é o mais importante? É o que está sentado à mesa para comer ou é o que está servindo? Claro que é o que está sentado à mesa. Mas entre vocês eu sou como aquele que serve.

[[v42-22-28]]

^<<v42-22-28,28>>^ — Vocês têm estado sempre comigo nos meus sofrimentos.

[[v42-22-29]]

^<<v42-22-29,29>>^ Por isso, assim como o meu Pai me deu o direito de governar, eu também dou o mesmo direito a vocês.

[[v42-22-30]]

^<<v42-22-30,30>>^ Vocês vão comer e beber à minha mesa no meu Reino  e sentarão em tronos para julgar as doze tribos  de Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ Jesus continuou: — Simão, Simão, escute bem! Satanás já conseguiu licença para pôr vocês à prova. Ele vai peneirar vocês como o lavrador peneira o trigo a fim de separá-lo da palha.

[[v42-22-32]]

^<<v42-22-32,32>>^ Mas eu tenho orado por você, Simão, para que não lhe falte fé. E, quando você voltar para mim, anime os seus irmãos.

[[v42-22-33]]

^<<v42-22-33,33>>^ Então Pedro disse a Jesus: — Estou pronto para ser preso e morrer com o senhor!

[[v42-22-34]]

^<<v42-22-34,34>>^ Então Jesus afirmou: — Eu digo a você, Pedro, que hoje, antes que o galo cante, você dirá três vezes que não me conhece.

[[v42-22-35]]

^<<v42-22-35,35>>^ Depois Jesus perguntou aos discípulos: — Por acaso faltou a vocês alguma coisa quando eu os enviei sem bolsa, sem sacola e sem sandálias? — Não faltou nada! — responderam eles.

[[v42-22-36]]

^<<v42-22-36,36>>^ Então Jesus disse: — Pois agora quem tem uma bolsa ou sacola deve pegá-la; e quem não tem espada deve vender a capa  e comprar uma.

[[v42-22-37]]

^<<v42-22-37,37>>^ Pois as Escrituras Sagradas  dizem: "Ele foi tratado como se fosse um criminoso." Eu afirmo a vocês que isso precisa acontecer comigo, pois o que está escrito a meu respeito tem de acontecer.

[[v42-22-38]]

^<<v42-22-38,38>>^ Aí os seus discípulos disseram: — Senhor, aqui estão duas espadas. — Basta!  — respondeu ele.

[[v42-22-39]]

^<<v42-22-39,39>>^ Jesus saiu e foi, como de costume, ao monte das Oliveiras; e os seus discípulos foram com ele.

[[v42-22-40]]

^<<v42-22-40,40>>^ Quando chegou ao lugar escolhido, Jesus disse: — Orem pedindo que vocês não sejam tentados.

[[v42-22-41]]

^<<v42-22-41,41>>^ Então se afastou a uma distância de mais ou menos trinta metros. Ajoelhou-se e começou a orar,

[[v42-22-42]]

^<<v42-22-42,42>>^ dizendo: — Pai, se queres, afasta de mim este cálice de sofrimento! Porém que não seja feito o que eu quero, mas o que tu queres.

[[v42-22-43]]

^<<v42-22-43,43>>^ [Então um anjo do céu apareceu e o animava.

[[v42-22-44]]

^<<v42-22-44,44>>^ Cheio de uma grande aflição, Jesus orava com mais força ainda. O seu suor era como gotas de sangue caindo no chão.]

[[v42-22-45]]

^<<v42-22-45,45>>^ Depois de orar, ele se levantou, voltou para o lugar onde os discípulos estavam e os encontrou dormindo, pois a tristeza deles era muito grande.

[[v42-22-46]]

^<<v42-22-46,46>>^ E disse: — Por que vocês estão dormindo? Levantem-se e orem para que não sejam tentados.

[[v42-22-47]]

^<<v42-22-47,47>>^ Jesus ainda estava falando, quando chegou uma multidão. Judas, um dos doze discípulos, que era quem guiava aquela gente, chegou perto de Jesus para beijá-lo.

[[v42-22-48]]

^<<v42-22-48,48>>^ Mas Jesus disse: — Judas, é com um beijo que você trai o Filho do Homem ?

[[v42-22-49]]

^<<v42-22-49,49>>^ Quando os discípulos que estavam com Jesus viram o que ia acontecer, disseram: — Senhor, devemos atacar essa gente com as nossas espadas?

[[v42-22-50]]

^<<v42-22-50,50>>^ Um deles feriu com a espada o empregado do Grande Sacerdote , cortando a sua orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Mas Jesus ordenou: — Parem com isso! Aí tocou na orelha do homem e o curou.

[[v42-22-52]]

^<<v42-22-52,52>>^ Em seguida disse aos chefes dos sacerdotes, aos oficiais da guarda do Templo e aos líderes judeus que tinham vindo para prendê-lo: — Por que vocês vieram com espadas e porretes para me prender como se eu fosse um bandido?

[[v42-22-53]]

^<<v42-22-53,53>>^ Eu estava com vocês todos os dias no pátio do Templo, e vocês não tentaram me prender. Mas esta é a hora de vocês e também a hora do poder da escuridão.

[[v42-22-54]]

^<<v42-22-54,54>>^ Eles prenderam Jesus e o levaram até a casa do Grande Sacerdote . E Pedro os seguia de longe.

[[v42-22-55]]

^<<v42-22-55,55>>^ Quando acenderam uma fogueira no meio do pátio, Pedro foi e sentou-se com os que estavam em volta do fogo.

[[v42-22-56]]

^<<v42-22-56,56>>^ Uma das empregadas o viu sentado ali perto da fogueira, olhou bem para ele e disse: — Este homem também estava com Jesus!

[[v42-22-57]]

^<<v42-22-57,57>>^ Mas Pedro negou, dizendo: — Mulher, eu nem conheço esse homem!

[[v42-22-58]]

^<<v42-22-58,58>>^ Pouco tempo depois, um homem o viu ali e disse: — Você também é um deles! Mas Pedro respondeu: — Homem, eu não sou um deles.

[[v42-22-59]]

^<<v42-22-59,59>>^ Mais ou menos uma hora depois, outro insistiu: — Você estava mesmo com ele porque também é galileu.

[[v42-22-60]]

^<<v42-22-60,60>>^ Mas Pedro respondeu: — Homem, eu não sei do que é que você está falando! Naquele instante, enquanto ele falava, o galo cantou.

[[v42-22-61]]

^<<v42-22-61,61>>^ Então o Senhor virou-se e olhou firme para Pedro, e ele lembrou das palavras que o Senhor lhe tinha dito: "Hoje, antes que o galo cante, você dirá três vezes que não me conhece."

[[v42-22-62]]

^<<v42-22-62,62>>^ Então Pedro saiu dali e chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os homens que estavam guardando Jesus zombavam dele e batiam nele.

[[v42-22-64]]

^<<v42-22-64,64>>^ Taparam os olhos dele e perguntavam: — Quem foi que bateu em você? Adivinhe!

[[v42-22-65]]

^<<v42-22-65,65>>^ E diziam muitas outras coisas para insultá-lo.

[[v42-22-66]]

^<<v42-22-66,66>>^ Quando amanheceu, alguns líderes dos judeus, alguns chefes dos sacerdotes e alguns mestres  da Lei se reuniram. Depois mandaram levar Jesus diante do Conselho Superior .

[[v42-22-67]]

^<<v42-22-67,67>>^ Então lhe disseram: — Diga para nós se você é o Messias . Ele respondeu: — Se eu disser que sim, vocês não vão acreditar.

[[v42-22-68]]

^<<v42-22-68,68>>^ E, se eu fizer uma pergunta, vocês não vão responder.

[[v42-22-69]]

^<<v42-22-69,69>>^ Mas de agora em diante o Filho do Homem  se sentará do lado direito do Deus Todo-Poderoso.

[[v42-22-70]]

^<<v42-22-70,70>>^ Aí todos perguntaram: — Então você é o Filho de Deus? Jesus respondeu: — São vocês que estão dizendo isso.

[[v42-22-71]]

^<<v42-22-71,71>>^ E eles disseram: — Não precisamos mais de testemunhas. Nós mesmos ouvimos o que ele disse.

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]