include::./index.adoc[]

[[v42-12-0]]
=== Lucas, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-12-1]]

^<<v42-12-1,1>>^ Milhares de pessoas se ajuntaram, de tal maneira que umas pisavam as outras. Então Jesus disse primeiro aos discípulos: — Cuidado com o fermento dos fariseus , isto é, com a falsidade deles.

[[v42-12-2]]

^<<v42-12-2,2>>^ Tudo o que está coberto vai ser descoberto, e o que está escondido será conhecido.

[[v42-12-3]]

^<<v42-12-3,3>>^ Assim tudo o que vocês disserem na escuridão será ouvido na luz do dia. E tudo o que disserem em segredo, dentro de um quarto fechado, será anunciado abertamente.

[[v42-12-4]]

^<<v42-12-4,4>>^ Jesus continuou: — Eu afirmo a vocês, meus amigos: não tenham medo daqueles que matam o corpo, mas depois não podem fazer mais nada.

[[v42-12-5]]

^<<v42-12-5,5>>^ Vou mostrar a vocês de quem devem ter medo: tenham medo de Deus, que, depois de matar o corpo, tem poder para jogar a pessoa no inferno. Sim, repito: tenham medo de Deus.

[[v42-12-6]]

^<<v42-12-6,6>>^ — Por acaso não é verdade que cinco passarinhos são vendidos por algumas moedinhas? No entanto Deus não esquece nenhum deles.

[[v42-12-7]]

^<<v42-12-7,7>>^ Até os fios dos cabelos de vocês estão todos contados. Não tenham medo, pois vocês valem mais do que muitos passarinhos!

[[v42-12-8]]

^<<v42-12-8,8>>^ Jesus disse ainda: — Eu digo a vocês que, se alguém afirmar publicamente que é meu, então o Filho do Homem  também afirmará, diante dos anjos de Deus, que essa pessoa é dele.

[[v42-12-9]]

^<<v42-12-9,9>>^ Mas aquele que disser publicamente que não é meu, o Filho do Homem também dirá diante dos anjos de Deus que essa pessoa não é dele.

[[v42-12-10]]

^<<v42-12-10,10>>^ — Quem falar contra o Filho do Homem será perdoado, porém quem blasfemar  contra o Espírito Santo não será perdoado.

[[v42-12-11]]

^<<v42-12-11,11>>^ — Quando levarem vocês para serem julgados nas sinagogas  ou diante dos governadores e autoridades, não fiquem preocupados, pensando como vão se defender ou o que vão dizer.

[[v42-12-12]]

^<<v42-12-12,12>>^ Pois naquela hora o Espírito Santo lhes ensinará o que devem dizer.

[[v42-12-13]]

^<<v42-12-13,13>>^ Um homem que estava no meio da multidão disse a Jesus: — Mestre, mande o meu irmão repartir comigo a herança que o nosso pai nos deixou.

[[v42-12-14]]

^<<v42-12-14,14>>^ Jesus disse: — Homem, quem me deu o direito de julgar ou de repartir propriedades entre vocês?

[[v42-12-15]]

^<<v42-12-15,15>>^ E continuou, dizendo a todos: — Prestem atenção! Tenham cuidado com todo tipo de avareza porque a verdadeira vida de uma pessoa não depende das coisas que ela tem, mesmo que sejam muitas.

[[v42-12-16]]

^<<v42-12-16,16>>^ Então Jesus contou a seguinte parábola : — As terras de um homem rico deram uma grande colheita.

[[v42-12-17]]

^<<v42-12-17,17>>^ Então ele começou a pensar: "Eu não tenho lugar para guardar toda esta colheita. O que é que vou fazer?

[[v42-12-18]]

^<<v42-12-18,18>>^ Ah! Já sei! — disse para si mesmo. — Vou derrubar os meus depósitos de cereais e construir outros maiores ainda. Neles guardarei todas as minhas colheitas junto com tudo o que tenho.

[[v42-12-19]]

^<<v42-12-19,19>>^ Então direi a mim mesmo: ‘Homem feliz! Você tem tudo de bom que precisa para muitos anos. Agora descanse, coma, beba e alegre-se.’ "

[[v42-12-20]]

^<<v42-12-20,20>>^ Mas Deus lhe disse: "Seu tolo! Esta noite você vai morrer; aí quem ficará com tudo o que você guardou?"

[[v42-12-21]]

^<<v42-12-21,21>>^ Jesus concluiu: — Isso é o que acontece com aqueles que juntam riquezas para si mesmos, mas para Deus não são ricos.

[[v42-12-22]]

^<<v42-12-22,22>>^ Então Jesus disse aos seus discípulos: — É por isso que eu digo a vocês: não se preocupem com a comida que precisam para viver nem com a roupa que precisam para se vestir.

[[v42-12-23]]

^<<v42-12-23,23>>^ Pois a vida é mais importante do que a comida, e o corpo é mais importante do que as roupas.

[[v42-12-24]]

^<<v42-12-24,24>>^ Vejam os corvos: não semeiam, não colhem, não têm despensas nem depósitos, mas Deus dá de comer a eles. Será que vocês não valem muito mais do que os pássaros?

[[v42-12-25]]

^<<v42-12-25,25>>^ Qual de vocês pode encompridar a sua vida, por mais que se preocupe com isso?

[[v42-12-26]]

^<<v42-12-26,26>>^ Portanto, se vocês não podem conseguir uma coisa assim tão pequena, por que se preocupam com as outras?

[[v42-12-27]]

^<<v42-12-27,27>>^ Vejam como crescem as flores do campo: elas não trabalham, nem fazem roupas para si mesmas. Mas eu afirmo a vocês que nem mesmo Salomão, sendo tão rico, usava roupas tão bonitas como uma dessas flores.

[[v42-12-28]]

^<<v42-12-28,28>>^ É Deus quem veste a erva do campo, que hoje está aqui e amanhã desaparece, queimada no forno. Então é claro que ele vestirá também vocês, que têm uma fé tão pequena!

[[v42-12-29]]

^<<v42-12-29,29>>^ Portanto, não fiquem aflitos, procurando sempre o que comer ou o que beber.

[[v42-12-30]]

^<<v42-12-30,30>>^ Pois os pagãos deste mundo é que estão sempre procurando todas essas coisas. O Pai de vocês sabe que vocês precisam de tudo isso.

[[v42-12-31]]

^<<v42-12-31,31>>^ Portanto, ponham em primeiro lugar na sua vida o Reino de Deus , e Deus lhes dará todas essas coisas.

[[v42-12-32]]

^<<v42-12-32,32>>^ Jesus continuou: — Meu pequeno rebanho, não tenha medo! Pois o Pai tem prazer em dar o Reino  a vocês.

[[v42-12-33]]

^<<v42-12-33,33>>^ Vendam tudo o que vocês têm e deem o dinheiro aos pobres. Arranjem bolsas que não se estragam e guardem as suas riquezas no céu, onde elas nunca se acabarão; porque lá os ladrões não podem roubá-las, e as traças não podem destruí-las.

[[v42-12-34]]

^<<v42-12-34,34>>^ Pois onde estiverem as suas riquezas, aí estará o coração de vocês.

[[v42-12-35]]

^<<v42-12-35,35>>^ E Jesus disse ainda: — Fiquem preparados para tudo: estejam com a roupa bem presa com o cinto e conservem as lamparinas acesas.

[[v42-12-36]]

^<<v42-12-36,36>>^ Sejam como os empregados que esperam pelo patrão, que vai voltar da festa de casamento. Logo que ele bate na porta, os empregados vão abrir.

[[v42-12-37]]

^<<v42-12-37,37>>^ Felizes aqueles empregados que o patrão encontra acordados e preparados! Eu afirmo a vocês que isto é verdade: o próprio patrão se preparará para servi-los, mandará que se sentem à mesa e ele mesmo os servirá.

[[v42-12-38]]

^<<v42-12-38,38>>^ Eles serão felizes se o patrão os encontrar alertas, mesmo que chegue à meia-noite ou até mais tarde.

[[v42-12-39]]

^<<v42-12-39,39>>^ Lembrem disto: se o dono da casa soubesse a que hora o ladrão viria, não o deixaria arrombar a sua casa.

[[v42-12-40]]

^<<v42-12-40,40>>^ Vocês, também, fiquem alertas, porque o Filho do Homem  vai chegar quando não estiverem esperando.

[[v42-12-41]]

^<<v42-12-41,41>>^ Então Pedro perguntou: — Senhor, essa parábola  é só para nós ou é para todos?

[[v42-12-42]]

^<<v42-12-42,42>>^ O Senhor respondeu: — Quem é, então, o empregado fiel e inteligente? É aquele que o patrão encarrega de tomar conta da casa e de dar comida na hora certa aos outros empregados.

[[v42-12-43]]

^<<v42-12-43,43>>^ Feliz aquele empregado que estiver fazendo isso quando o patrão chegar!

[[v42-12-44]]

^<<v42-12-44,44>>^ Eu afirmo a vocês que, de fato, o patrão vai colocá-lo como encarregado de toda a sua propriedade.

[[v42-12-45]]

^<<v42-12-45,45>>^ Mas imaginem o que acontecerá se aquele empregado pensar que o seu patrão está demorando muito para voltar. E imaginem que esse empregado comece a bater nos outros empregados e empregadas e a comer e a beber até ficar bêbado.

[[v42-12-46]]

^<<v42-12-46,46>>^ Então o patrão voltará no dia em que o empregado menos espera e na hora que ele não sabe. Aí o patrão mandará cortar o empregado em pedaços e o condenará a ir para o lugar aonde os desobedientes vão.

[[v42-12-47]]

^<<v42-12-47,47>>^ — O empregado que sabe qual é a vontade do patrão, mas não se prepara e não faz o que ele quer, será castigado com muitas chicotadas.

[[v42-12-48]]

^<<v42-12-48,48>>^ Mas o empregado que não sabe o que o patrão quer e faz alguma coisa que merece castigo, esse empregado será castigado com poucas chicotadas. Assim será pedido muito de quem recebe muito; e, daquele a quem muito é dado, muito mais será pedido.

[[v42-12-49]]

^<<v42-12-49,49>>^ Jesus continuou: — Eu vim para pôr fogo na terra e como eu gostaria que ele já estivesse aceso!

[[v42-12-50]]

^<<v42-12-50,50>>^ Tenho de receber um batismo e como estou aflito até que isso aconteça!

[[v42-12-51]]

^<<v42-12-51,51>>^ Vocês pensam que eu vim trazer paz ao mundo? Pois eu afirmo a vocês que não vim trazer paz, mas divisão.

[[v42-12-52]]

^<<v42-12-52,52>>^ Porque daqui em diante uma família de cinco pessoas ficará dividida: três contra duas e duas contra três.

[[v42-12-53]]

^<<v42-12-53,53>>^ Os pais vão ficar contra os filhos, e os filhos, contra os pais. As mães vão ficar contra as filhas, e as filhas, contra as mães. As sogras vão ficar contra as noras, e as noras, contra as sogras.

[[v42-12-54]]

^<<v42-12-54,54>>^ Jesus disse também ao povo: — Quando vocês veem uma nuvem subindo no oeste, dizem logo: "Vai chover." E, de fato, chove.

[[v42-12-55]]

^<<v42-12-55,55>>^ E, quando sentem o vento sul soprando, dizem: "Vai fazer calor." E faz mesmo.

[[v42-12-56]]

^<<v42-12-56,56>>^ Hipócritas! Vocês sabem explicar os sinais da terra e do céu. Então por que não sabem explicar o que querem dizer os sinais desta época?

[[v42-12-57]]

^<<v42-12-57,57>>^ E Jesus terminou, dizendo: — Por que é que vocês mesmos não decidem qual é a maneira certa de agir?

[[v42-12-58]]

^<<v42-12-58,58>>^ Se alguém fizer uma acusação contra você e levá-lo ao tribunal, faça o possível para resolver a questão enquanto ainda está no caminho com essa pessoa. Isso para que ela não o leve ao juiz, o juiz o entregue ao guarda, e o guarda ponha você na cadeia.

[[v42-12-59]]

^<<v42-12-59,59>>^ Eu lhe afirmo que você não sairá dali enquanto não pagar a multa toda.

'''

xref:042-lucas/042-lucas-011.adoc#v42-11-0[&#60; Capítulo Anterior] | <<v42-12-0,Topo>> | xref:042-lucas/042-lucas-013.adoc#v42-13-0[Próximo Capítulo &#62;]