include::./index.adoc[]

[[v42-16-0]]
=== Lucas, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-16-1]]

^<<v42-16-1,1>>^ Jesus disse aos seus discípulos: — Havia um homem rico que tinha um administrador que cuidava dos seus bens. Foram dizer a esse homem que o administrador estava desperdiçando o dinheiro dele.

[[v42-16-2]]

^<<v42-16-2,2>>^ Por isso ele o chamou e disse: "Eu andei ouvindo umas coisas a respeito de você. Agora preste contas da sua administração porque você não pode mais continuar como meu administrador."

[[v42-16-3]]

^<<v42-16-3,3>>^ — Aí o administrador pensou: "O patrão está me despedindo. E, agora, o que é que eu vou fazer? Não tenho forças para cavar a terra e tenho vergonha de pedir esmola.

[[v42-16-4]]

^<<v42-16-4,4>>^ Ah! Já sei o que vou fazer… Assim, quando for mandado embora, terei amigos que me receberão nas suas casas."

[[v42-16-5]]

^<<v42-16-5,5>>^ — Então ele chamou todos os devedores do patrão e perguntou para o primeiro: "Quanto é que você está devendo para o meu patrão?"

[[v42-16-6]]

^<<v42-16-6,6>>^ — "Cem barris de azeite!" — respondeu ele. O administrador disse: — "Aqui está a sua conta. Sente-se e escreva cinquenta."

[[v42-16-7]]

^<<v42-16-7,7>>^ — Para o outro ele perguntou: "E você, quanto está devendo?" — "Mil medidas de trigo!" — respondeu ele. — "Escreva oitocentas!" — mandou o administrador.

[[v42-16-8]]

^<<v42-16-8,8>>^ — E o patrão desse administrador desonesto o elogiou pela sua esperteza. E Jesus continuou: — As pessoas deste mundo são muito mais espertas nos seus negócios do que as pessoas que pertencem à luz.

[[v42-16-9]]

^<<v42-16-9,9>>^ Por isso eu digo a vocês: usem as riquezas deste mundo para conseguir amigos a fim de que, quando as riquezas faltarem, eles recebam vocês no lar eterno.

[[v42-16-10]]

^<<v42-16-10,10>>^ Quem é fiel nas coisas pequenas também será nas grandes; e quem é desonesto nas coisas pequenas também será nas grandes.

[[v42-16-11]]

^<<v42-16-11,11>>^ Pois, se vocês não forem honestos com as riquezas deste mundo, quem vai pôr vocês para tomar conta das riquezas verdadeiras?

[[v42-16-12]]

^<<v42-16-12,12>>^ E, se não forem honestos com o que é dos outros, quem lhes dará o que é de vocês?

[[v42-16-13]]

^<<v42-16-13,13>>^ — Um escravo não pode servir a dois donos ao mesmo tempo, pois vai rejeitar um e preferir o outro; ou será fiel a um e desprezará o outro. Vocês não podem servir a Deus e também servir ao dinheiro.

[[v42-16-14]]

^<<v42-16-14,14>>^ Os fariseus  ouviram isso e zombaram de Jesus porque amavam o dinheiro.

[[v42-16-15]]

^<<v42-16-15,15>>^ Então Jesus disse a eles: — Para as pessoas vocês parecem bons, mas Deus conhece o coração de vocês. Pois aquilo que as pessoas acham que vale muito não vale nada para Deus.

[[v42-16-16]]

^<<v42-16-16,16>>^ — A Lei  de Moisés e os ensinamentos dos Profetas  duraram até a época de João Batista. Desde esse tempo a boa notícia do Reino de Deus  está sendo anunciada, e cada um se esforça para entrar nele.

[[v42-16-17]]

^<<v42-16-17,17>>^ — É mais fácil o céu e a terra desaparecerem do que ser tirado um simples acento de qualquer palavra da Lei.

[[v42-16-18]]

^<<v42-16-18,18>>^ — Se um homem se divorciar e casar com outra mulher, comete adultério. E quem casar com a mulher divorciada também comete adultério.

[[v42-16-19]]

^<<v42-16-19,19>>^ Jesus continuou: — Havia um homem rico que vestia roupas muito caras e todos os dias dava uma grande festa.

[[v42-16-20]]

^<<v42-16-20,20>>^ Havia também um homem pobre, chamado Lázaro, que tinha o corpo coberto de feridas, e que costumavam largar perto da casa do rico.

[[v42-16-21]]

^<<v42-16-21,21>>^ Lázaro ficava ali, procurando matar a fome com as migalhas que caíam da mesa do homem rico. E até os cachorros vinham lamber as suas feridas.

[[v42-16-22]]

^<<v42-16-22,22>>^ O pobre morreu e foi levado pelos anjos para junto de Abraão, na festa do céu. O rico também morreu e foi sepultado.

[[v42-16-23]]

^<<v42-16-23,23>>^ Ele sofria muito no mundo dos mortos . Quando olhou, viu lá longe Abraão e Lázaro ao lado dele.

[[v42-16-24]]

^<<v42-16-24,24>>^ Então gritou: "Pai Abraão, tenha pena de mim! Mande que Lázaro molhe o dedo na água e venha refrescar a minha língua porque estou sofrendo muito neste fogo!"

[[v42-16-25]]

^<<v42-16-25,25>>^ — Mas Abraão respondeu: "Meu filho, lembre que você recebeu na sua vida todas as coisas boas, porém Lázaro só recebeu o que era mau. E agora ele está feliz aqui, enquanto você está sofrendo.

[[v42-16-26]]

^<<v42-16-26,26>>^ Além disso, há um grande abismo entre nós, de modo que os que querem atravessar daqui até vocês não podem, como também os daí não podem passar para cá."

[[v42-16-27]]

^<<v42-16-27,27>>^ — O rico disse: "Nesse caso, Pai Abraão, peço que mande Lázaro até a casa do meu pai

[[v42-16-28]]

^<<v42-16-28,28>>^ porque eu tenho cinco irmãos. Deixe que ele vá e os avise para que assim não venham para este lugar de sofrimento."

[[v42-16-29]]

^<<v42-16-29,29>>^ — Mas Abraão respondeu: "Os seus irmãos têm a Lei  de Moisés e os livros dos Profetas  para os avisar. Que eles os escutem!"

[[v42-16-30]]

^<<v42-16-30,30>>^ — "Só isso não basta, Pai Abraão!", respondeu o rico. "Porém, se alguém ressuscitar e for falar com eles, aí eles se arrependerão dos seus pecados."

[[v42-16-31]]

^<<v42-16-31,31>>^ — Mas Abraão respondeu: "Se eles não escutarem Moisés nem os profetas, não crerão, mesmo que alguém ressuscite."

'''

xref:042-lucas/042-lucas-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-lucas/042-lucas-017.adoc#v42-17-0[Próximo Capítulo &#62;]