include::./index.adoc[]

[[v42-6-0]]
=== Lucas, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-6-1]]

^<<v42-6-1,1>>^ Num sábado, Jesus estava atravessando uma plantação de trigo. Os seus discípulos começaram a colher e a debulhar espigas, e a comer os grãos de trigo.

[[v42-6-2]]

^<<v42-6-2,2>>^ Então alguns fariseus  perguntaram: — Por que é que vocês estão fazendo uma coisa que a nossa Lei  proíbe fazer no sábado?

[[v42-6-3]]

^<<v42-6-3,3>>^ Jesus respondeu: — Vocês não leram o que Davi fez, quando ele e os seus companheiros estavam com fome?

[[v42-6-4]]

^<<v42-6-4,4>>^ Ele entrou na casa de Deus, pegou os pães oferecidos a Deus, comeu e deu também aos seus companheiros. No entanto é contra a nossa Lei alguém comer desses pães; somente os sacerdotes têm o direito de fazer isso.

[[v42-6-5]]

^<<v42-6-5,5>>^ E Jesus terminou, dizendo: — O Filho do Homem  tem autoridade sobre o sábado.

[[v42-6-6]]

^<<v42-6-6,6>>^ Num outro sábado Jesus entrou na sinagoga  e começou a ensinar. Estava ali um homem que tinha a mão direita aleijada.

[[v42-6-7]]

^<<v42-6-7,7>>^ Alguns mestres  da Lei e alguns fariseus  ficaram espiando Jesus com atenção para ver se ele ia curar alguém no sábado. Pois queriam arranjar algum motivo para o acusar de desobedecer à Lei .

[[v42-6-8]]

^<<v42-6-8,8>>^ Mas Jesus conhecia os pensamentos deles e por isso disse para o homem que tinha a mão aleijada: — Levante-se e fique em pé aqui na frente. O homem se levantou e ficou em pé.

[[v42-6-9]]

^<<v42-6-9,9>>^ Então Jesus disse: — Eu pergunto a vocês: o que é que a nossa Lei diz sobre o sábado? O que é permitido fazer nesse dia: o bem ou o mal? Salvar alguém da morte ou deixar morrer?

[[v42-6-10]]

^<<v42-6-10,10>>^ Jesus olhou para todos os que estavam em volta dele e disse para o homem: — Estenda a mão! O homem estendeu a mão, e ela sarou.

[[v42-6-11]]

^<<v42-6-11,11>>^ Aí os mestres da Lei e os fariseus ficaram furiosos e começaram a conversar sobre o que poderiam fazer contra Jesus.

[[v42-6-12]]

^<<v42-6-12,12>>^ Naquela ocasião Jesus subiu um monte para orar e passou a noite orando a Deus.

[[v42-6-13]]

^<<v42-6-13,13>>^ Quando amanheceu, chamou os seus discípulos e escolheu doze deles. E deu o nome de apóstolos  a estes doze:

[[v42-6-14]]

^<<v42-6-14,14>>^ Simão, em quem pôs o nome de Pedro, e o seu irmão André; Tiago e João; Filipe e Bartolomeu;

[[v42-6-15]]

^<<v42-6-15,15>>^ Mateus e Tomé; Tiago, filho de Alfeu; Simão, o nacionalista;

[[v42-6-16]]

^<<v42-6-16,16>>^ Judas, filho de Tiago; e Judas Iscariotes, que foi o traidor.

[[v42-6-17]]

^<<v42-6-17,17>>^ Jesus desceu do monte com eles e parou com muitos dos seus seguidores num lugar plano. Uma grande multidão estava ali. Era gente de toda a Judeia, de Jerusalém e das cidades de Tiro e Sidom , que ficam na beira do mar.

[[v42-6-18]]

^<<v42-6-18,18>>^ Eles tinham vindo para ouvir Jesus e para serem curados das suas doenças. Os que estavam atormentados por espíritos maus também vieram e foram curados.

[[v42-6-19]]

^<<v42-6-19,19>>^ Todos queriam tocar em Jesus porque dele saía um poder que curava todas as pessoas.

[[v42-6-20]]

^<<v42-6-20,20>>^ Jesus olhou para os seus discípulos e disse: — Felizes são vocês, os pobres, pois o Reino de Deus  é de vocês.

[[v42-6-21]]

^<<v42-6-21,21>>^ — Felizes são vocês que agora têm fome, pois vão ter fartura. — Felizes são vocês que agora choram, pois vão rir.

[[v42-6-22]]

^<<v42-6-22,22>>^ — Felizes são vocês quando os odiarem, rejeitarem, insultarem e disserem que vocês são maus por serem seguidores do Filho do Homem .

[[v42-6-23]]

^<<v42-6-23,23>>^ Fiquem felizes e muito alegres quando isso acontecer, pois uma grande recompensa está guardada no céu para vocês. Pois os antepassados dessas pessoas fizeram essas mesmas coisas com os profetas .

[[v42-6-24]]

^<<v42-6-24,24>>^ — Mas ai de vocês que agora são ricos, pois já tiveram a sua vida boa.

[[v42-6-25]]

^<<v42-6-25,25>>^ — Ai de vocês que agora têm tudo, pois vão passar fome. — Ai de vocês que agora estão rindo, pois vão chorar e se lamentar.

[[v42-6-26]]

^<<v42-6-26,26>>^ — Ai de vocês quando todos os elogiarem, pois os antepassados dessas pessoas também elogiaram os falsos profetas.

[[v42-6-27]]

^<<v42-6-27,27>>^ — Mas eu digo a vocês que estão me ouvindo: amem os seus inimigos e façam o bem para os que odeiam vocês.

[[v42-6-28]]

^<<v42-6-28,28>>^ Desejem o bem para aqueles que os amaldiçoam e orem em favor daqueles que maltratam vocês.

[[v42-6-29]]

^<<v42-6-29,29>>^ Se alguém lhe der um tapa na cara, vire o outro lado para ele bater também. Se alguém tomar a sua capa , deixe que leve a túnica  também.

[[v42-6-30]]

^<<v42-6-30,30>>^ Dê sempre a qualquer um que lhe pedir alguma coisa; e, quando alguém tirar o que é seu, não peça de volta.

[[v42-6-31]]

^<<v42-6-31,31>>^ Façam aos outros a mesma coisa que querem que eles façam a vocês.

[[v42-6-32]]

^<<v42-6-32,32>>^ — Se vocês amam somente aqueles que os amam, o que é que estão fazendo de mais? Até as pessoas de má fama amam as pessoas que as amam.

[[v42-6-33]]

^<<v42-6-33,33>>^ E, se vocês fazem o bem somente para aqueles que lhes fazem o bem, o que é que estão fazendo de mais? Até as pessoas de má fama fazem isso.

[[v42-6-34]]

^<<v42-6-34,34>>^ E, se vocês emprestam somente para aqueles que vocês acham que vão lhes pagar, o que é que estão fazendo de mais? Até as pessoas de má fama emprestam aos que têm má fama, para receber de volta o que emprestaram.

[[v42-6-35]]

^<<v42-6-35,35>>^ Façam o contrário: amem os seus inimigos e façam o bem para eles. Emprestem e não esperem receber de volta o que emprestaram e assim vocês terão uma grande recompensa e serão filhos do Deus Altíssimo. Façam isso porque ele é bom também para os ingratos e maus.

[[v42-6-36]]

^<<v42-6-36,36>>^ Tenham misericórdia dos outros, assim como o Pai de vocês tem misericórdia de vocês.

[[v42-6-37]]

^<<v42-6-37,37>>^ — Não julguem os outros, e Deus não julgará vocês. Não condenem os outros, e Deus não condenará vocês. Perdoem os outros, e Deus perdoará vocês.

[[v42-6-38]]

^<<v42-6-38,38>>^ Deem aos outros, e Deus dará a vocês. Ele será generoso, e as bênçãos que ele lhes dará serão tantas, que vocês não poderão segurá-las nas suas mãos. A mesma medida que vocês usarem para medir os outros Deus usará para medir vocês.

[[v42-6-39]]

^<<v42-6-39,39>>^ E Jesus fez estas comparações: — Um cego não pode guiar outro cego. Se fizer isso, os dois cairão num buraco.

[[v42-6-40]]

^<<v42-6-40,40>>^ Nenhum aluno é mais importante do que o seu professor. Porém, quando tiver terminado os estudos, o aluno ficará igual ao seu professor.

[[v42-6-41]]

^<<v42-6-41,41>>^ — Por que é que você vê o cisco que está no olho do seu irmão e não repara na trave de madeira que está no seu próprio olho?

[[v42-6-42]]

^<<v42-6-42,42>>^ Como é que você pode dizer ao seu irmão: "Me deixe tirar esse cisco do seu olho", se você não repara na trave que está no seu próprio olho? Hipócrita! Tire primeiro a trave que está no seu olho e então poderá ver bem para tirar o cisco que está no olho do seu irmão.

[[v42-6-43]]

^<<v42-6-43,43>>^ — A árvore boa não dá frutas ruins, assim como a árvore que não presta não dá frutas boas.

[[v42-6-44]]

^<<v42-6-44,44>>^ Pois cada árvore é conhecida pelas frutas que ela produz. Não é possível colher figos de espinheiros, nem colher uvas de pés de urtiga.

[[v42-6-45]]

^<<v42-6-45,45>>^ A pessoa boa tira o bem do depósito de coisas boas que tem no seu coração. E a pessoa má tira o mal do seu depósito de coisas más. Pois a boca fala do que o coração está cheio.

[[v42-6-46]]

^<<v42-6-46,46>>^ — Por que vocês me chamam "Senhor, Senhor" e não fazem o que eu digo?

[[v42-6-47]]

^<<v42-6-47,47>>^ Eu vou mostrar a vocês com quem se parece a pessoa que vem e ouve a minha mensagem e é obediente a ela.

[[v42-6-48]]

^<<v42-6-48,48>>^ Essa pessoa é como um homem que, quando construiu uma casa, cavou bem fundo e pôs o alicerce na rocha. O rio ficou cheio, e as suas águas bateram contra aquela casa; porém ela não se abalou porque havia sido bem-construída.

[[v42-6-49]]

^<<v42-6-49,49>>^ Mas quem ouve a minha mensagem e não é obediente a ela é como o homem que construiu uma casa na terra, sem alicerce. Quando a água bateu contra aquela casa, ela caiu logo e ficou totalmente destruída.

'''

xref:042-lucas/042-lucas-005.adoc#v42-5-0[&#60; Capítulo Anterior] | <<v42-6-0,Topo>> | xref:042-lucas/042-lucas-007.adoc#v42-7-0[Próximo Capítulo &#62;]