include::./index.adoc[]

[[v42-15-0]]
=== Lucas, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-15-1]]

^<<v42-15-1,1>>^ Certa ocasião, muitos cobradores de impostos e outras pessoas de má fama chegaram perto de Jesus para o ouvir.

[[v42-15-2]]

^<<v42-15-2,2>>^ Os fariseus  e os mestres  da Lei criticavam Jesus, dizendo: — Este homem se mistura com gente de má fama e toma refeições com eles.

[[v42-15-3]]

^<<v42-15-3,3>>^ Então Jesus contou esta parábola :

[[v42-15-4]]

^<<v42-15-4,4>>^ — Se algum de vocês tem cem ovelhas e perde uma, por acaso não vai procurá-la? Assim, deixa no campo as outras noventa e nove e vai procurar a ovelha perdida até achá-la.

[[v42-15-5]]

^<<v42-15-5,5>>^ Quando a encontra, fica muito contente e volta com ela nos ombros.

[[v42-15-6]]

^<<v42-15-6,6>>^ Chegando à sua casa, chama os amigos e vizinhos e diz: "Alegrem-se comigo porque achei a minha ovelha perdida."

[[v42-15-7]]

^<<v42-15-7,7>>^ — Pois eu lhes digo que assim também vai haver mais alegria no céu por um pecador que se arrepende dos seus pecados do que por noventa e nove pessoas boas que não precisam se arrepender.

[[v42-15-8]]

^<<v42-15-8,8>>^ Jesus continuou: — Se uma mulher que tem dez moedas de prata perder uma, vai procurá-la, não é? Ela acende uma lamparina, varre a casa e procura com muito cuidado até achá-la.

[[v42-15-9]]

^<<v42-15-9,9>>^ E, quando a encontra, convida as amigas e vizinhas e diz: "Alegrem-se comigo porque achei a minha moeda perdida."

[[v42-15-10]]

^<<v42-15-10,10>>^ — Pois eu digo a vocês que assim também os anjos de Deus se alegrarão por causa de um pecador que se arrepende dos seus pecados.

[[v42-15-11]]

^<<v42-15-11,11>>^ E Jesus disse ainda: — Um homem tinha dois filhos.

[[v42-15-12]]

^<<v42-15-12,12>>^ Certo dia o mais moço disse ao pai: "Pai, quero que o senhor me dê agora a minha parte da herança." — E o pai repartiu os bens entre os dois.

[[v42-15-13]]

^<<v42-15-13,13>>^ Poucos dias depois, o filho mais moço ajuntou tudo o que era seu e partiu para um país que ficava muito longe. Ali viveu uma vida cheia de pecado e desperdiçou tudo o que tinha.

[[v42-15-14]]

^<<v42-15-14,14>>^ — O rapaz já havia gastado tudo, quando houve uma grande fome naquele país, e ele começou a passar necessidade.

[[v42-15-15]]

^<<v42-15-15,15>>^ Então procurou um dos moradores daquela terra e pediu ajuda. Este o mandou para a sua fazenda a fim de tratar dos porcos.

[[v42-15-16]]

^<<v42-15-16,16>>^ Ali, com fome, ele tinha vontade de comer o que os porcos comiam, mas ninguém lhe dava nada.

[[v42-15-17]]

^<<v42-15-17,17>>^ Caindo em si, ele pensou: "Quantos trabalhadores do meu pai têm comida de sobra, e eu estou aqui morrendo de fome!

[[v42-15-18]]

^<<v42-15-18,18>>^ Vou voltar para a casa do meu pai e dizer: ‘Pai, pequei contra Deus e contra o senhor

[[v42-15-19]]

^<<v42-15-19,19>>^ e não mereço mais ser chamado de seu filho. Me aceite como um dos seus trabalhadores.’ "

[[v42-15-20]]

^<<v42-15-20,20>>^ Então saiu dali e voltou para a casa do pai. — Quando o rapaz ainda estava longe de casa, o pai o avistou. E, com muita pena do filho, correu, e o abraçou, e beijou.

[[v42-15-21]]

^<<v42-15-21,21>>^ E o filho disse: "Pai, pequei contra Deus e contra o senhor e não mereço mais ser chamado de seu filho!"

[[v42-15-22]]

^<<v42-15-22,22>>^ — Mas o pai ordenou aos empregados: "Depressa! Tragam a melhor roupa e vistam nele. Ponham um anel no dedo dele e sandálias nos seus pés.

[[v42-15-23]]

^<<v42-15-23,23>>^ Também tragam e matem o bezerro gordo. Vamos começar a festejar

[[v42-15-24]]

^<<v42-15-24,24>>^ porque este meu filho estava morto e viveu de novo; estava perdido e foi achado." — E começaram a festa.

[[v42-15-25]]

^<<v42-15-25,25>>^ — Enquanto isso, o filho mais velho estava no campo. Quando ele voltou e chegou perto da casa, ouviu a música e o barulho da dança.

[[v42-15-26]]

^<<v42-15-26,26>>^ Então chamou um empregado e perguntou: "O que é que está acontecendo?"

[[v42-15-27]]

^<<v42-15-27,27>>^ — O empregado respondeu: "O seu irmão voltou para casa vivo e com saúde. Por isso o seu pai mandou matar o bezerro gordo."

[[v42-15-28]]

^<<v42-15-28,28>>^ — O filho mais velho ficou zangado e não quis entrar. Então o pai veio para fora e insistiu com ele para que entrasse.

[[v42-15-29]]

^<<v42-15-29,29>>^ Mas ele respondeu: "Faz tantos anos que trabalho como um escravo para o senhor e nunca desobedeci a uma ordem sua. Mesmo assim o senhor nunca me deu nem ao menos um cabrito para eu fazer uma festa com os meus amigos.

[[v42-15-30]]

^<<v42-15-30,30>>^ Porém esse seu filho desperdiçou tudo o que era do senhor, gastando dinheiro com prostitutas. E agora ele volta, e o senhor manda matar o bezerro gordo!"

[[v42-15-31]]

^<<v42-15-31,31>>^ — Então o pai respondeu: "Meu filho, você está sempre comigo, e tudo o que é meu é seu.

[[v42-15-32]]

^<<v42-15-32,32>>^ Mas era preciso fazer esta festa para mostrar a nossa alegria. Pois este seu irmão estava morto e viveu de novo; estava perdido e foi achado."

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]