include::./index.adoc[]

[[v42-2-0]]
=== Lucas, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-2-1]]

^<<v42-2-1,1>>^ Naquele tempo o imperador Augusto mandou uma ordem para todos os povos do Império. Todas as pessoas deviam se registrar a fim de ser feita uma contagem da população.

[[v42-2-2]]

^<<v42-2-2,2>>^ Quando foi feito esse primeiro recenseamento, Cirênio era governador da Síria.

[[v42-2-3]]

^<<v42-2-3,3>>^ Então todos foram se registrar, cada um na sua própria cidade.

[[v42-2-4]]

^<<v42-2-4,4>>^ Por isso José foi de Nazaré, na Galileia, para a região da Judeia, a uma cidade chamada Belém, onde tinha nascido o rei Davi. José foi registrar-se lá porque era descendente de Davi.

[[v42-2-5]]

^<<v42-2-5,5>>^ Levou consigo Maria, com quem tinha casamento contratado . Ela estava grávida,

[[v42-2-6]]

^<<v42-2-6,6>>^ e aconteceu que, enquanto se achavam em Belém, chegou o tempo de a criança nascer.

[[v42-2-7]]

^<<v42-2-7,7>>^ Então Maria deu à luz o seu primeiro filho. Enrolou o menino em panos e o deitou numa manjedoura , pois não havia lugar para eles na pensão.

[[v42-2-8]]

^<<v42-2-8,8>>^ Naquela região havia pastores que estavam passando a noite nos campos, tomando conta dos rebanhos de ovelhas.

[[v42-2-9]]

^<<v42-2-9,9>>^ Então um anjo do Senhor apareceu, e a luz gloriosa  do Senhor brilhou por cima dos pastores. Eles ficaram com muito medo,

[[v42-2-10]]

^<<v42-2-10,10>>^ mas o anjo disse: — Não tenham medo! Estou aqui a fim de trazer uma boa notícia para vocês, e ela será motivo de grande alegria também para todo o povo!

[[v42-2-11]]

^<<v42-2-11,11>>^ Hoje mesmo, na cidade de Davi , nasceu o Salvador de vocês — o Messias , o Senhor!

[[v42-2-12]]

^<<v42-2-12,12>>^ Esta será a prova: vocês encontrarão uma criancinha enrolada em panos e deitada numa manjedoura .

[[v42-2-13]]

^<<v42-2-13,13>>^ No mesmo instante apareceu junto com o anjo uma multidão de outros anjos, como se fosse um exército celestial. Eles cantavam hinos de louvor a Deus, dizendo:

[[v42-2-14]]

^<<v42-2-14,14>>^ — Glória  a Deus nas maiores alturas do céu! E paz na terra para as pessoas a quem ele quer bem!

[[v42-2-15]]

^<<v42-2-15,15>>^ Quando os anjos voltaram para o céu, os pastores disseram uns aos outros: — Vamos até Belém para ver o que aconteceu; vamos ver aquilo que o Senhor nos contou.

[[v42-2-16]]

^<<v42-2-16,16>>^ Eles foram depressa, e encontraram Maria e José, e viram o menino deitado na manjedoura.

[[v42-2-17]]

^<<v42-2-17,17>>^ Então contaram o que os anjos tinham dito a respeito dele.

[[v42-2-18]]

^<<v42-2-18,18>>^ Todos os que ouviram o que os pastores disseram ficaram muito admirados.

[[v42-2-19]]

^<<v42-2-19,19>>^ Maria guardava todas essas coisas no seu coração e pensava muito nelas.

[[v42-2-20]]

^<<v42-2-20,20>>^ Então os pastores voltaram para os campos, cantando hinos de louvor a Deus pelo que tinham ouvido e visto. E tudo tinha acontecido como o anjo havia falado.

[[v42-2-21]]

^<<v42-2-21,21>>^ Uma semana depois, quando chegou o dia de circuncidar  o menino, puseram nele o nome de Jesus. Pois o anjo tinha dado esse nome ao menino antes de ele nascer.

[[v42-2-22]]

^<<v42-2-22,22>>^ Chegou o dia de Maria e José cumprirem a cerimônia da purificação , conforme manda a Lei  de Moisés. Então eles levaram a criança para Jerusalém a fim de apresentá-la ao Senhor.

[[v42-2-23]]

^<<v42-2-23,23>>^ Pois está escrito na Lei do Senhor: "Todo primeiro filho será separado e dedicado ao Senhor."

[[v42-2-24]]

^<<v42-2-24,24>>^ Eles foram lá também para oferecer em sacrifício  duas rolinhas ou dois pombinhos, como a Lei do Senhor manda.

[[v42-2-25]]

^<<v42-2-25,25>>^ Em Jerusalém morava um homem chamado Simeão. Ele era bom e piedoso e esperava a salvação do povo de Israel. O Espírito Santo estava com ele,

[[v42-2-26]]

^<<v42-2-26,26>>^ e o próprio Espírito lhe tinha prometido que, antes de morrer, ele iria ver o Messias  enviado pelo Senhor.

[[v42-2-27]]

^<<v42-2-27,27>>^ Guiado pelo Espírito, Simeão foi ao Templo. Quando os pais levaram o menino Jesus ao Templo para fazer o que a Lei manda,

[[v42-2-28]]

^<<v42-2-28,28>>^ Simeão pegou o menino no colo e louvou a Deus. Ele disse:

[[v42-2-29]]

^<<v42-2-29,29>>^ — Agora, Senhor, cumpriste a promessa que fizeste e já podes deixar este teu servo partir em paz.

[[v42-2-30]]

^<<v42-2-30,30>>^ Pois eu já vi com os meus próprios olhos a tua salvação,

[[v42-2-31]]

^<<v42-2-31,31>>^ que preparaste na presença de todos os povos:

[[v42-2-32]]

^<<v42-2-32,32>>^ uma luz para mostrar o teu caminho a todos os que não são judeus e para dar glória  ao teu povo de Israel.

[[v42-2-33]]

^<<v42-2-33,33>>^ O pai e a mãe do menino ficaram admirados com o que Simeão disse a respeito dele.

[[v42-2-34]]

^<<v42-2-34,34>>^ Simeão os abençoou e disse a Maria, a mãe de Jesus: — Este menino foi escolhido por Deus tanto para a destruição como para a salvação de muita gente em Israel. Ele vai ser um sinal de Deus; muitas pessoas falarão contra ele,

[[v42-2-35]]

^<<v42-2-35,35>>^ e assim os pensamentos secretos delas serão conhecidos. E a tristeza, como uma espada afiada, cortará o seu coração, Maria.

[[v42-2-36]]

^<<v42-2-36,36>>^ Havia ali também uma profetisa  chamada Ana, que era viúva e muito idosa. Ela era filha de Fanuel, da tribo  de Aser. Sete anos depois que ela havia casado, o seu marido morreu.

[[v42-2-37]]

^<<v42-2-37,37>>^ Agora ela estava com oitenta e quatro anos de idade. Nunca saía do pátio do Templo e adorava a Deus dia e noite, jejuando e fazendo orações.

[[v42-2-38]]

^<<v42-2-38,38>>^ Naquele momento ela chegou e começou a louvar a Deus e a falar a respeito do menino para todos os que esperavam a libertação de Jerusalém.

[[v42-2-39]]

^<<v42-2-39,39>>^ Quando terminaram de fazer tudo o que a Lei  do Senhor manda, José e Maria voltaram para a Galileia, para a casa deles na cidade de Nazaré.

[[v42-2-40]]

^<<v42-2-40,40>>^ O menino crescia e ficava forte; tinha muita sabedoria e era abençoado por Deus.

[[v42-2-41]]

^<<v42-2-41,41>>^ Todos os anos os pais de Jesus iam a Jerusalém para a Festa da Páscoa .

[[v42-2-42]]

^<<v42-2-42,42>>^ Quando Jesus tinha doze anos, eles foram à Festa, conforme o seu costume.

[[v42-2-43]]

^<<v42-2-43,43>>^ Depois que a Festa acabou, eles começaram a viagem de volta para casa. Mas Jesus tinha ficado em Jerusalém, e os seus pais não sabiam disso.

[[v42-2-44]]

^<<v42-2-44,44>>^ Eles pensavam que ele estivesse no grupo de pessoas que vinha voltando e por isso viajaram o dia todo. Então começaram a procurá-lo entre os parentes e amigos.

[[v42-2-45]]

^<<v42-2-45,45>>^ Como não o encontraram, voltaram a Jerusalém para procurá-lo.

[[v42-2-46]]

^<<v42-2-46,46>>^ Três dias depois encontraram o menino num dos pátios do Templo, sentado no meio dos mestres  da Lei, ouvindo-os e fazendo perguntas a eles.

[[v42-2-47]]

^<<v42-2-47,47>>^ Todos os que o ouviam estavam muito admirados com a sua inteligência e com as respostas que dava.

[[v42-2-48]]

^<<v42-2-48,48>>^ Quando os pais viram o menino, também ficaram admirados. E a sua mãe lhe disse: — Meu filho, por que foi que você fez isso conosco? O seu pai e eu estávamos muito aflitos procurando você.

[[v42-2-49]]

^<<v42-2-49,49>>^ Jesus respondeu: — Por que vocês estavam me procurando? Não sabiam que eu devia estar na casa do meu Pai?

[[v42-2-50]]

^<<v42-2-50,50>>^ Mas eles não entenderam o que ele disse.

[[v42-2-51]]

^<<v42-2-51,51>>^ Então Jesus voltou com os seus pais para Nazaré e continuava a ser obediente a eles. E a sua mãe guardava tudo isso no coração.

[[v42-2-52]]

^<<v42-2-52,52>>^ Conforme crescia, Jesus ia crescendo também em sabedoria, e tanto Deus como as pessoas gostavam cada vez mais dele.

'''

xref:042-lucas/042-lucas-001.adoc#v42-1-0[&#60; Capítulo Anterior] | <<v42-2-0,Topo>> | xref:042-lucas/042-lucas-003.adoc#v42-3-0[Próximo Capítulo &#62;]