include::./index.adoc[]

[[v42-20-0]]
=== Lucas, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-20-1]]

^<<v42-20-1,1>>^ Certo dia, Jesus estava no pátio do Templo ensinando o povo e anunciando o evangelho . Então chegaram ali alguns chefes dos sacerdotes e alguns mestres  da Lei, junto com alguns líderes do povo,

[[v42-20-2]]

^<<v42-20-2,2>>^ e perguntaram: — Diga para nós: com que autoridade você faz essas coisas? Quem lhe deu essa autoridade?

[[v42-20-3]]

^<<v42-20-3,3>>^ Jesus respondeu: — Eu também vou fazer uma pergunta a vocês. Respondam:

[[v42-20-4]]

^<<v42-20-4,4>>^ Quem deu autoridade a João para batizar? Foi Deus ou foram pessoas?

[[v42-20-5]]

^<<v42-20-5,5>>^ Aí eles começaram a dizer uns aos outros: — O que é que vamos dizer? Se dissermos que foi Deus, ele vai perguntar: "Então por que vocês não creram em João?"

[[v42-20-6]]

^<<v42-20-6,6>>^ Mas, se dissermos que foram pessoas, esta multidão vai nos apedrejar, pois eles acham que João era profeta .

[[v42-20-7]]

^<<v42-20-7,7>>^ Por isso responderam: — Nós não sabemos quem deu autoridade a João para batizar.

[[v42-20-8]]

^<<v42-20-8,8>>^ Jesus disse: — Pois então eu também não digo com que autoridade faço essas coisas.

[[v42-20-9]]

^<<v42-20-9,9>>^ Depois Jesus contou esta parábola  para o povo: — Certo homem fez uma plantação de uvas, arrendou-a para uns lavradores e depois foi viajar, ficando fora por muito tempo.

[[v42-20-10]]

^<<v42-20-10,10>>^ Quando chegou o tempo da colheita, ele mandou um empregado para receber a sua parte. Mas os lavradores bateram nele e o mandaram de volta sem nada.

[[v42-20-11]]

^<<v42-20-11,11>>^ O dono mandou outro empregado, mas eles também bateram nele, depois o trataram de modo vergonhoso e o mandaram de volta sem nada.

[[v42-20-12]]

^<<v42-20-12,12>>^ Então ele enviou um terceiro empregado, mas os lavradores também bateram nele e o expulsaram.

[[v42-20-13]]

^<<v42-20-13,13>>^ Aí o dono da plantação pensou: "O que vou fazer? Já sei: vou mandar o meu filho querido. Tenho certeza de que vão respeitá-lo."

[[v42-20-14]]

^<<v42-20-14,14>>^ — Mas, quando os lavradores viram o filho, disseram: "Este é o filho do dono; ele vai herdar a plantação. Vamos matá-lo, e a plantação será nossa."

[[v42-20-15]]

^<<v42-20-15,15>>^ — Então eles jogaram o filho para fora da plantação e o mataram. Aí Jesus perguntou: — E, agora, o que é que o dono da plantação vai fazer?

[[v42-20-16]]

^<<v42-20-16,16>>^ Ele virá, matará aqueles homens e dará a plantação a outros lavradores. Então as pessoas que estavam ouvindo disseram: — Que Deus não permita que isso aconteça!

[[v42-20-17]]

^<<v42-20-17,17>>^ Mas Jesus olhou bem para eles e disse: — As Escrituras Sagradas  afirmam: "A pedra que os construtores rejeitaram veio a ser a mais importante de todas."

[[v42-20-18]]

^<<v42-20-18,18>>^ Quem cair em cima dessa pedra ficará em pedaços. E, se a pedra cair sobre alguém, essa pessoa vai virar pó.

[[v42-20-19]]

^<<v42-20-19,19>>^ Os mestres  da Lei e os chefes dos sacerdotes sabiam que era contra eles que Jesus havia contado essa parábola  e queriam prendê-lo ali mesmo, porém tinham medo do povo.

[[v42-20-20]]

^<<v42-20-20,20>>^ Então começaram a vigiar Jesus. Pagaram alguns homens para fazerem perguntas a ele. Eles deviam fingir que eram sinceros e procurar conseguir alguma prova contra Jesus. Assim os mestres da Lei e os chefes dos sacerdotes teriam uma desculpa para o prender e entregar nas mãos do Governador romano.

[[v42-20-21]]

^<<v42-20-21,21>>^ Esses homens perguntaram: — Mestre, sabemos que aquilo que o senhor diz e ensina é certo. Sabemos também que o senhor não julga pela aparência e ensina a verdade sobre a maneira de viver que Deus exige.

[[v42-20-22]]

^<<v42-20-22,22>>^ Diga: é ou não é contra a nossa Lei  pagar impostos ao Imperador romano?

[[v42-20-23]]

^<<v42-20-23,23>>^ Mas Jesus percebeu a má intenção deles e disse:

[[v42-20-24]]

^<<v42-20-24,24>>^ — Tragam aqui uma moeda. De quem são o nome e a cara que estão gravados nela? — São do Imperador! — responderam eles.

[[v42-20-25]]

^<<v42-20-25,25>>^ Então Jesus disse: — Deem ao Imperador o que é do Imperador e deem a Deus o que é de Deus.

[[v42-20-26]]

^<<v42-20-26,26>>^ Eles não puderam conseguir nenhuma prova contra Jesus diante do povo. Por isso ficaram calados, admirados com a resposta dele.

[[v42-20-27]]

^<<v42-20-27,27>>^ Alguns saduceus , os quais afirmam que ninguém ressuscita, chegaram perto de Jesus

[[v42-20-28]]

^<<v42-20-28,28>>^ e disseram: — Mestre, Moisés escreveu para nós a seguinte lei : "Se um homem morrer e deixar a esposa sem filhos, o irmão dele deve casar com a viúva, para terem filhos, que serão considerados filhos do irmão que morreu."

[[v42-20-29]]

^<<v42-20-29,29>>^ Acontece que havia sete irmãos. O mais velho casou e morreu sem deixar filhos.

[[v42-20-30]]

^<<v42-20-30,30>>^ Então o segundo casou com a viúva,

[[v42-20-31]]

^<<v42-20-31,31>>^ e depois, o terceiro. E assim a mesma coisa aconteceu com os sete irmãos, isto é, todos morreram sem deixar filhos.

[[v42-20-32]]

^<<v42-20-32,32>>^ Depois a mulher também morreu.

[[v42-20-33]]

^<<v42-20-33,33>>^ Portanto, no dia da ressurreição, de qual dos sete a mulher vai ser esposa? Pois todos eles casaram com ela!

[[v42-20-34]]

^<<v42-20-34,34>>^ Jesus respondeu: — Nesta vida os homens e as mulheres casam.

[[v42-20-35]]

^<<v42-20-35,35>>^ Mas as pessoas que merecem alcançar a ressurreição e a vida futura não vão casar lá,

[[v42-20-36]]

^<<v42-20-36,36>>^ pois serão como os anjos e não poderão morrer. Serão filhos de Deus porque ressuscitaram.

[[v42-20-37]]

^<<v42-20-37,37>>^ E Moisés mostra claramente que os mortos serão ressuscitados. Quando fala do espinheiro que estava em fogo, ele escreve que o Senhor é "o Deus de Abraão, o Deus de Isaque e o Deus de Jacó."

[[v42-20-38]]

^<<v42-20-38,38>>^ Isso mostra que Deus é Deus dos vivos e não dos mortos, pois para ele todos estão vivos.

[[v42-20-39]]

^<<v42-20-39,39>>^ Aí alguns mestres  da Lei disseram: — Boa resposta, Mestre!

[[v42-20-40]]

^<<v42-20-40,40>>^ E não tinham coragem de lhe fazer mais perguntas.

[[v42-20-41]]

^<<v42-20-41,41>>^ Em seguida Jesus perguntou a eles: — Como se pode dizer que o Messias  é descendente de Davi?

[[v42-20-42]]

^<<v42-20-42,42>>^ Pois o próprio Davi diz assim no livro de Salmos: "O Senhor Deus disse ao meu Senhor: ‘Sente-se do meu lado direito,

[[v42-20-43]]

^<<v42-20-43,43>>^ até que eu ponha os seus inimigos como estrado debaixo dos seus pés.’ "

[[v42-20-44]]

^<<v42-20-44,44>>^ Se Davi chama o Messias de Senhor, como é que o Messias pode ser descendente de Davi?

[[v42-20-45]]

^<<v42-20-45,45>>^ O povo todo estava escutando, e Jesus disse aos discípulos:

[[v42-20-46]]

^<<v42-20-46,46>>^ — Cuidado com os mestres  da Lei, que gostam de usar capas  compridas e de ser cumprimentados com respeito nas praças. Eles escolhem os lugares de honra nas sinagogas  e os melhores lugares nos banquetes.

[[v42-20-47]]

^<<v42-20-47,47>>^ Exploram as viúvas e roubam os seus bens; e, para disfarçar, fazem orações compridas. Portanto, o castigo que eles vão sofrer será pior ainda!

'''

xref:042-lucas/042-lucas-019.adoc#v42-19-0[&#60; Capítulo Anterior] | <<v42-20-0,Topo>> | xref:042-lucas/042-lucas-021.adoc#v42-21-0[Próximo Capítulo &#62;]