include::./index.adoc[]

[[v42-19-0]]
=== Lucas, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-19-1]]

^<<v42-19-1,1>>^ Jesus entrou em Jericó e estava atravessando a cidade.

[[v42-19-2]]

^<<v42-19-2,2>>^ Morava ali um homem rico, chamado Zaqueu, que era chefe dos cobradores de impostos.

[[v42-19-3]]

^<<v42-19-3,3>>^ Ele estava tentando ver quem era Jesus, mas não podia, por causa da multidão, pois Zaqueu era muito baixo.

[[v42-19-4]]

^<<v42-19-4,4>>^ Então correu adiante da multidão e subiu numa figueira brava para ver Jesus, que devia passar por ali.

[[v42-19-5]]

^<<v42-19-5,5>>^ Quando Jesus chegou àquele lugar, olhou para cima e disse a Zaqueu: — Zaqueu, desça depressa, pois hoje preciso ficar na sua casa.

[[v42-19-6]]

^<<v42-19-6,6>>^ Zaqueu desceu depressa e o recebeu na sua casa, com muita alegria.

[[v42-19-7]]

^<<v42-19-7,7>>^ Todos os que viram isso começaram a resmungar: — Este homem foi se hospedar na casa de um pecador!

[[v42-19-8]]

^<<v42-19-8,8>>^ Zaqueu se levantou e disse ao Senhor: — Escute, Senhor, eu vou dar a metade dos meus bens aos pobres. E, se roubei alguém, vou devolver quatro vezes mais.

[[v42-19-9]]

^<<v42-19-9,9>>^ Então Jesus disse: — Hoje a salvação entrou nesta casa, pois este homem também é descendente de Abraão.

[[v42-19-10]]

^<<v42-19-10,10>>^ Porque o Filho do Homem  veio buscar e salvar quem está perdido.

[[v42-19-11]]

^<<v42-19-11,11>>^ Jesus contou uma parábola  para os que ouviram o que ele tinha dito. Agora ele estava perto de Jerusalém, e por isso eles estavam pensando que o Reino de Deus  ia aparecer logo.

[[v42-19-12]]

^<<v42-19-12,12>>^ Então Jesus disse: — Certo homem de uma família importante foi para um país que ficava bem longe, para lá ser feito rei e depois voltar.

[[v42-19-13]]

^<<v42-19-13,13>>^ Antes de viajar, chamou dez dos seus empregados, deu a cada um uma moeda de ouro e disse: "Vejam o que vocês conseguem ganhar com este dinheiro, até a minha volta."

[[v42-19-14]]

^<<v42-19-14,14>>^ — Acontece que o povo do seu país o odiava e por isso mandou atrás dele uma comissão para dizer que não queriam que aquele homem fosse feito rei deles.

[[v42-19-15]]

^<<v42-19-15,15>>^ — O homem foi feito rei e voltou para casa. Aí mandou chamar os empregados a quem tinha dado o dinheiro, para saber quanto haviam conseguido ganhar.

[[v42-19-16]]

^<<v42-19-16,16>>^ O primeiro chegou e disse: "Patrão, com aquela moeda de ouro que o senhor me deu, eu ganhei dez."

[[v42-19-17]]

^<<v42-19-17,17>>^ — "Muito bem!" — respondeu ele. — "Você é um bom empregado! E, porque foi fiel em coisas pequenas, você vai ser o governador de dez cidades."

[[v42-19-18]]

^<<v42-19-18,18>>^ — O segundo empregado veio e disse: "Patrão, com aquela moeda de ouro que o senhor me deu, eu ganhei cinco."

[[v42-19-19]]

^<<v42-19-19,19>>^ — "Você vai ser o governador de cinco cidades!" — disse o patrão.

[[v42-19-20]]

^<<v42-19-20,20>>^ — O outro empregado chegou e disse: "Patrão, aqui está a sua moeda. Eu a embrulhei num lenço e a escondi.

[[v42-19-21]]

^<<v42-19-21,21>>^ Tive medo do senhor, porque sei que é um homem duro, que tira dos outros o que não é seu e colhe o que não plantou."

[[v42-19-22]]

^<<v42-19-22,22>>^ — Ele respondeu: "Você é um mau empregado! Vou usar as suas próprias palavras para julgá-lo. Você sabia que sou um homem duro, que tiro dos outros o que não é meu e colho o que não plantei.

[[v42-19-23]]

^<<v42-19-23,23>>^ Então por que você não pôs o meu dinheiro no banco? Assim, quando eu voltasse da viagem, receberia o dinheiro com juros."

[[v42-19-24]]

^<<v42-19-24,24>>^ — E disse para os que estavam ali: "Tirem dele a moeda e deem ao que tem dez."

[[v42-19-25]]

^<<v42-19-25,25>>^ Eles responderam: — "Mas ele já tem dez moedas, patrão!"

[[v42-19-26]]

^<<v42-19-26,26>>^ — E o patrão disse: — "Eu afirmo a vocês que aquele que tem muito receberá ainda mais; mas quem não tem, até o pouco que tem será tirado dele.

[[v42-19-27]]

^<<v42-19-27,27>>^ E agora tragam aqui os meus inimigos, que não queriam que eu fosse o rei deles, e os matem na minha frente."

[[v42-19-28]]

^<<v42-19-28,28>>^ Depois de dizer isso, Jesus foi adiante deles para Jerusalém.

[[v42-19-29]]

^<<v42-19-29,29>>^ Quando iam chegando aos povoados de Betfagé e Betânia, que ficam perto do monte das Oliveiras, enviou dois discípulos na frente,

[[v42-19-30]]

^<<v42-19-30,30>>^ com a seguinte ordem: — Vão até o povoado ali adiante. Logo que vocês entrarem lá, encontrarão preso um jumentinho que ainda não foi montado. Desamarrem o animal e o tragam aqui.

[[v42-19-31]]

^<<v42-19-31,31>>^ Se alguém perguntar por que vocês estão fazendo isso, digam que o Mestre precisa dele.

[[v42-19-32]]

^<<v42-19-32,32>>^ Eles foram e acharam tudo como Jesus tinha dito.

[[v42-19-33]]

^<<v42-19-33,33>>^ Quando estavam desamarrando o jumentinho, os donos perguntaram: — Por que é que vocês estão desamarrando o animal?

[[v42-19-34]]

^<<v42-19-34,34>>^ Eles responderam: — O Mestre precisa dele.

[[v42-19-35]]

^<<v42-19-35,35>>^ Então eles levaram o jumentinho para Jesus, puseram as suas capas  sobre o animal e ajudaram Jesus a montar.

[[v42-19-36]]

^<<v42-19-36,36>>^ Conforme ele ia passando, o povo estendia as suas capas no caminho.

[[v42-19-37]]

^<<v42-19-37,37>>^ Quando Jesus chegou perto de Jerusalém, na descida do monte das Oliveiras, uma grande multidão de seguidores ia com ele. E eles, cheios de alegria, começaram a louvar a Deus em voz alta por tudo o que tinham visto.

[[v42-19-38]]

^<<v42-19-38,38>>^ Eles diziam: — Que Deus abençoe o Rei que vem em nome do Senhor! Paz no céu e glória  a Deus!

[[v42-19-39]]

^<<v42-19-39,39>>^ Aí alguns fariseus  que estavam no meio da multidão disseram a Jesus: — Mestre, mande que os seus seguidores calem a boca!

[[v42-19-40]]

^<<v42-19-40,40>>^ Jesus respondeu: — Eu afirmo a vocês que, se eles se calarem, as pedras gritarão!

[[v42-19-41]]

^<<v42-19-41,41>>^ Quando Jesus chegou perto de Jerusalém e viu a cidade, chorou com pena dela

[[v42-19-42]]

^<<v42-19-42,42>>^ e disse: — Ah! Jerusalém! Se hoje mesmo você soubesse o que é preciso para conseguir a paz! Mas agora você não pode ver isso.

[[v42-19-43]]

^<<v42-19-43,43>>^ Pois chegarão os dias em que os inimigos vão cercá-la com rampas de ataque, e vão rodeá-la, e apertá-la de todos os lados.

[[v42-19-44]]

^<<v42-19-44,44>>^ Eles destruirão completamente você e todos os seus moradores. Não ficará uma pedra em cima da outra, porque você não reconheceu o tempo em que Deus veio para salvá-la.

[[v42-19-45]]

^<<v42-19-45,45>>^ Jesus entrou no pátio do Templo e começou a expulsar dali os vendedores.

[[v42-19-46]]

^<<v42-19-46,46>>^ Ele lhes disse: — Nas Escrituras Sagradas  está escrito que Deus disse o seguinte: "A minha casa será uma ‘Casa de oração’." Mas vocês a transformaram num esconderijo de ladrões.

[[v42-19-47]]

^<<v42-19-47,47>>^ Jesus ensinava no pátio do Templo todos os dias. Os chefes dos sacerdotes, os mestres  da Lei e os líderes do povo queriam matá-lo.

[[v42-19-48]]

^<<v42-19-48,48>>^ Mas não achavam jeito de fazer isso, pois todos o escutavam com muita atenção.

'''

xref:042-lucas/042-lucas-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-lucas/042-lucas-020.adoc#v42-20-0[Próximo Capítulo &#62;]