include::./index.adoc[]

[[v42-9-0]]
=== Lucas, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-9-1]]

^<<v42-9-1,1>>^ Jesus chamou os doze discípulos e lhes deu poder e autoridade para expulsar todos os demônios e curar doenças.

[[v42-9-2]]

^<<v42-9-2,2>>^ Então os enviou para anunciarem o Reino de Deus  e curarem os doentes.

[[v42-9-3]]

^<<v42-9-3,3>>^ Ele disse: — Nesta viagem não levem nada: nem bengala para se apoiar, nem sacola, nem comida, nem dinheiro, nem mesmo uma túnica  a mais.

[[v42-9-4]]

^<<v42-9-4,4>>^ Quando vocês entrarem numa cidade, fiquem na casa em que forem recebidos até irem embora daquele lugar.

[[v42-9-5]]

^<<v42-9-5,5>>^ Mas, se forem mal recebidos, saiam logo daquela cidade. E na saída sacudam o pó das suas sandálias, como sinal de protesto contra aquela gente.

[[v42-9-6]]

^<<v42-9-6,6>>^ Os discípulos então saíram de viagem e andaram por todos os povoados, anunciando o evangelho  e curando doentes por toda parte.

[[v42-9-7]]

^<<v42-9-7,7>>^ Herodes, o governador da Galileia, ouviu falar de tudo o que estava acontecendo e ficou sem saber o que pensar. Pois alguns diziam que João Batista tinha sido ressuscitado,

[[v42-9-8]]

^<<v42-9-8,8>>^ outros diziam que Elias tinha aparecido, e outros ainda que um dos antigos profetas  havia ressuscitado.

[[v42-9-9]]

^<<v42-9-9,9>>^ Mas Herodes disse: — Eu mesmo mandei cortar a cabeça de João. Quem será então esse homem de quem ouço falar essas coisas? E Herodes procurava ver Jesus.

[[v42-9-10]]

^<<v42-9-10,10>>^ Os apóstolos  voltaram e contaram a Jesus tudo o que haviam feito. Então ele os levou consigo, e foram sozinhos para o povoado de Betsaida.

[[v42-9-11]]

^<<v42-9-11,11>>^ Mas as multidões souberam disso e o seguiram. E Jesus os recebeu, falou a respeito do Reino de Deus  e curou os que precisavam ser curados.

[[v42-9-12]]

^<<v42-9-12,12>>^ Estava anoitecendo, e por isso os doze apóstolos foram e disseram a Jesus: — Mande esta gente embora. Eles podem ir aos povoados e sítios que ficam por perto daqui e lá encontrarão o que comer e onde ficar, pois este lugar é deserto.

[[v42-9-13]]

^<<v42-9-13,13>>^ Mas Jesus respondeu: — Deem vocês mesmos comida a eles. Os discípulos disseram: — Só temos cinco pães e dois peixes. O senhor quer que a gente vá comprar comida para toda esta multidão?

[[v42-9-14]]

^<<v42-9-14,14>>^ Estavam ali mais ou menos cinco mil homens. Jesus ordenou aos seus discípulos: — Mandem o povo sentar-se em grupos de mais ou menos cinquenta pessoas.

[[v42-9-15]]

^<<v42-9-15,15>>^ Os discípulos obedeceram e mandaram que todos se sentassem.

[[v42-9-16]]

^<<v42-9-16,16>>^ Aí Jesus pegou os cinco pães e os dois peixes, olhou para o céu e deu graças a Deus por eles. Depois partiu os pães e os peixes e os entregou aos discípulos para que eles distribuíssem ao povo.

[[v42-9-17]]

^<<v42-9-17,17>>^ Todos comeram e ficaram satisfeitos, e os discípulos ainda encheram doze cestos com os pedaços que sobraram.

[[v42-9-18]]

^<<v42-9-18,18>>^ Certa vez Jesus estava sozinho, orando, e os discípulos chegaram perto dele. Então ele perguntou: — Quem o povo diz que eu sou?

[[v42-9-19]]

^<<v42-9-19,19>>^ Eles responderam: — Alguns dizem que o senhor é João Batista; outros, que é Elias; e outros, que é um dos profetas  antigos que ressuscitou.

[[v42-9-20]]

^<<v42-9-20,20>>^ — E vocês? Quem vocês dizem que eu sou?  — perguntou Jesus. Pedro respondeu: — O Messias  que Deus enviou.

[[v42-9-21]]

^<<v42-9-21,21>>^ Então Jesus proibiu os discípulos de contarem isso a qualquer pessoa.

[[v42-9-22]]

^<<v42-9-22,22>>^ E continuou: — O Filho do Homem  terá de sofrer muito. Ele será rejeitado pelos líderes judeus, pelos chefes dos sacerdotes e pelos mestres  da Lei. Será morto e, no terceiro dia, será ressuscitado.

[[v42-9-23]]

^<<v42-9-23,23>>^ Depois disse a todos: — Se alguém quer ser meu seguidor, que esqueça os seus próprios interesses, esteja pronto cada dia para morrer como eu vou morrer e me acompanhe.

[[v42-9-24]]

^<<v42-9-24,24>>^ Pois quem põe os seus próprios interesses em primeiro lugar nunca terá a vida verdadeira; mas quem esquece a si mesmo por minha causa terá a vida verdadeira.

[[v42-9-25]]

^<<v42-9-25,25>>^ O que adianta alguém ganhar o mundo inteiro, mas perder a vida verdadeira e ser destruído?

[[v42-9-26]]

^<<v42-9-26,26>>^ Pois, se alguém tiver vergonha de mim e do meu ensinamento, então o Filho do Homem também terá vergonha dessa pessoa, quando ele vier na sua glória  e na glória do Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Eu afirmo a vocês que estão aqui algumas pessoas que não morrerão antes de ver o Reino de Deus .

[[v42-9-28]]

^<<v42-9-28,28>>^ Mais ou menos uma semana depois de ter dito essas coisas, Jesus levou Pedro, João e Tiago e subiu o monte para orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ Enquanto orava, o seu rosto mudou de aparência, e a sua roupa ficou muito branca e brilhante.

[[v42-9-30]]

^<<v42-9-30,30>>^ De repente, dois homens apareceram ali e começaram a falar com ele. Eram Moisés e Elias,

[[v42-9-31]]

^<<v42-9-31,31>>^ que estavam cercados por um brilho celestial. Eles falavam com Jesus a respeito da morte que, de acordo com a vontade de Deus, ele ia sofrer em Jerusalém.

[[v42-9-32]]

^<<v42-9-32,32>>^ Pedro e os seus companheiros estavam dormindo profundamente, mas acordaram e viram a glória  de Jesus e os dois homens que estavam com ele.

[[v42-9-33]]

^<<v42-9-33,33>>^ Quando esses dois homens estavam se afastando de Jesus, Pedro disse: — Mestre, como é bom estarmos aqui! Vamos armar três barracas: uma para o senhor, outra para Moisés e outra para Elias. Pedro não sabia o que estava dizendo.

[[v42-9-34]]

^<<v42-9-34,34>>^ Ele ainda estava falando, quando apareceu uma nuvem e os cobriu. Os discípulos ficaram com medo quando a nuvem desceu sobre eles.

[[v42-9-35]]

^<<v42-9-35,35>>^ E da nuvem veio uma voz, que disse: — Este é o meu Filho, o meu escolhido. Escutem o que ele diz!

[[v42-9-36]]

^<<v42-9-36,36>>^ Quando a voz parou, eles viram que Jesus estava sozinho. Os discípulos ficaram calados e naquela ocasião não disseram nada a ninguém sobre o que tinham visto.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte eles desceram do monte, e uma grande multidão veio se encontrar com Jesus.

[[v42-9-38]]

^<<v42-9-38,38>>^ Aí um homem que estava no meio do povo começou a gritar: — Mestre, peço ao senhor pelo meu filho, o meu único filho!

[[v42-9-39]]

^<<v42-9-39,39>>^ Um espírito mau o agarra, e, de repente, o menino dá um grito e começa a ter convulsões e a espumar pela boca. O espírito o maltrata e não o solta de jeito nenhum.

[[v42-9-40]]

^<<v42-9-40,40>>^ Já pedi aos discípulos do senhor que expulsassem o espírito mau, mas eles não conseguiram.

[[v42-9-41]]

^<<v42-9-41,41>>^ Jesus respondeu: — Gente má e sem fé! Até quando ficarei com vocês? Até quando terei de aguentá-los? Então disse ao homem: — Traga o seu filho aqui.

[[v42-9-42]]

^<<v42-9-42,42>>^ Quando o menino estava chegando, teve um ataque, e o demônio o jogou no chão. Então Jesus deu uma ordem ao espírito mau, curou o menino e o entregou ao pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ E todos ficaram admirados com o grande poder de Deus. Todos estavam admirados com o que Jesus fazia, e ele disse aos discípulos:

[[v42-9-44]]

^<<v42-9-44,44>>^ — Não esqueçam o que vou dizer a vocês: o Filho do Homem  será entregue nas mãos dos homens.

[[v42-9-45]]

^<<v42-9-45,45>>^ Mas eles não entenderam isso, pois o que essas palavras queriam dizer tinha sido escondido deles para que não as entendessem. E eles estavam com medo de fazer perguntas a Jesus sobre o assunto.

[[v42-9-46]]

^<<v42-9-46,46>>^ Os discípulos começaram a conversar sobre qual deles era o mais importante.

[[v42-9-47]]

^<<v42-9-47,47>>^ Mas Jesus sabia o que eles estavam pensando. Então pegou uma criança e a pôs ao seu lado.

[[v42-9-48]]

^<<v42-9-48,48>>^ Aí disse: — Aquele que, por ser meu seguidor, receber esta criança estará recebendo a mim; e quem me receber estará recebendo aquele que me enviou. Pois aquele que é o mais humilde entre vocês, esse é que é o mais importante.

[[v42-9-49]]

^<<v42-9-49,49>>^ João disse: — Mestre, vimos um homem que expulsa demônios pelo poder do nome do senhor, mas nós o proibimos de fazer isso porque ele não é do nosso grupo.

[[v42-9-50]]

^<<v42-9-50,50>>^ Então Jesus disse a João e aos outros discípulos: — Não o proíbam, pois quem não é contra vocês é a favor de vocês.

[[v42-9-51]]

^<<v42-9-51,51>>^ Como estava chegando o tempo de Jesus ir para o céu, ele resolveu ir para Jerusalém.

[[v42-9-52]]

^<<v42-9-52,52>>^ Então mandou que alguns mensageiros fossem na frente. No caminho eles entraram em um povoado da região de Samaria a fim de prepararem um lugar para ele.

[[v42-9-53]]

^<<v42-9-53,53>>^ Mas os moradores dali não quiseram receber Jesus porque viram que ele estava indo para Jerusalém.

[[v42-9-54]]

^<<v42-9-54,54>>^ Quando os seus discípulos Tiago e João viram isso, disseram: — O senhor quer que a gente mande descer fogo do céu para acabar com estas pessoas?

[[v42-9-55]]

^<<v42-9-55,55>>^ Porém Jesus, virando-se para eles, os repreendeu.

[[v42-9-56]]

^<<v42-9-56,56>>^ Então ele e os seus discípulos foram para outro povoado.

[[v42-9-57]]

^<<v42-9-57,57>>^ Quando Jesus e os discípulos iam pelo caminho, um homem disse a Jesus: — Eu estou pronto a seguir o senhor para qualquer lugar onde o senhor for.

[[v42-9-58]]

^<<v42-9-58,58>>^ Então Jesus disse: — As raposas têm as suas covas, e os pássaros, os seus ninhos. Mas o Filho do Homem  não tem onde descansar.

[[v42-9-59]]

^<<v42-9-59,59>>^ Aí ele disse para outro homem: — Venha comigo. Mas ele respondeu: — Senhor, primeiro deixe que eu volte e sepulte o meu pai.

[[v42-9-60]]

^<<v42-9-60,60>>^ Jesus disse: — Deixe que os mortos sepultem os seus mortos. Mas você vá e anuncie o Reino de Deus .

[[v42-9-61]]

^<<v42-9-61,61>>^ Outro homem disse: — Eu seguirei o senhor, mas primeiro deixe que eu vá me despedir da minha família.

[[v42-9-62]]

^<<v42-9-62,62>>^ Jesus respondeu: — Quem começa a arar a terra e olha para trás não serve para o Reino de Deus.

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]