include::./index.adoc[]

[[v42-21-0]]
=== Lucas, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-21-1]]

^<<v42-21-1,1>>^ Jesus estava no pátio do Templo, olhando o que estava acontecendo, e viu os ricos pondo dinheiro na caixa das ofertas.

[[v42-21-2]]

^<<v42-21-2,2>>^ Viu também uma viúva pobre, que pôs ali duas moedinhas de pouco valor.

[[v42-21-3]]

^<<v42-21-3,3>>^ Então ele disse: — Eu afirmo a vocês que esta viúva pobre deu mais do que todos.

[[v42-21-4]]

^<<v42-21-4,4>>^ Porque os outros deram do que estava sobrando. Porém ela, que é tão pobre, deu tudo o que tinha para viver.

[[v42-21-5]]

^<<v42-21-5,5>>^ Algumas pessoas estavam falando de como o Templo era enfeitado com bonitas pedras e com as coisas que tinham sido dadas como ofertas. Então Jesus disse:

[[v42-21-6]]

^<<v42-21-6,6>>^ — Chegará o dia em que tudo isso que vocês estão vendo será destruído. E não ficará uma pedra em cima da outra.

[[v42-21-7]]

^<<v42-21-7,7>>^ Aí eles perguntaram: — Mestre, quando será isso? Que sinal haverá para mostrar quando é que isso vai acontecer?

[[v42-21-8]]

^<<v42-21-8,8>>^ Jesus respondeu: — Tomem cuidado para que ninguém engane vocês. Porque muitos vão aparecer fingindo ser eu, dizendo: "Eu sou o Messias " ou "Já chegou o tempo". Porém não sigam essa gente.

[[v42-21-9]]

^<<v42-21-9,9>>^ Não tenham medo quando ouvirem falar de guerras e de revoluções. Pois é preciso que essas coisas aconteçam primeiro. Mas isso não quer dizer que o fim esteja perto.

[[v42-21-10]]

^<<v42-21-10,10>>^ E continuou: — Uma nação vai guerrear contra outra, e um país atacará outro.

[[v42-21-11]]

^<<v42-21-11,11>>^ Em vários lugares haverá grandes tremores de terra, falta de alimentos e epidemias. Acontecerão coisas terríveis, e grandes sinais serão vistos no céu.

[[v42-21-12]]

^<<v42-21-12,12>>^ — Mas, antes de acontecer tudo isso, vocês serão presos e perseguidos. Vocês serão entregues para serem julgados nas sinagogas  e depois serão jogados na cadeia. Por serem meus seguidores, vocês serão levados aos reis e aos governadores para serem julgados.

[[v42-21-13]]

^<<v42-21-13,13>>^ E isso dará oportunidade a vocês para anunciarem o evangelho .

[[v42-21-14]]

^<<v42-21-14,14>>^ Resolvam desde já que não vão ficar preocupados, antes da hora, com o que dirão para se defender.

[[v42-21-15]]

^<<v42-21-15,15>>^ Porque eu lhes darei palavras e sabedoria que os seus inimigos não poderão resistir, nem negar.

[[v42-21-16]]

^<<v42-21-16,16>>^ Vocês serão entregues às autoridades pelos seus próprios pais, irmãos, parentes e amigos, e alguns de vocês serão mortos.

[[v42-21-17]]

^<<v42-21-17,17>>^ Todos odiarão vocês por serem meus seguidores.

[[v42-21-18]]

^<<v42-21-18,18>>^ Mas nem um fio de cabelo de vocês será perdido.

[[v42-21-19]]

^<<v42-21-19,19>>^ Fiquem firmes, pois assim vocês serão salvos.

[[v42-21-20]]

^<<v42-21-20,20>>^ Jesus disse ainda: — Quando vocês virem a cidade de Jerusalém cercada por exércitos, fiquem sabendo que logo ela será destruída.

[[v42-21-21]]

^<<v42-21-21,21>>^ Então, os que estiverem na região da Judeia, que fujam para os montes. Quem estiver na cidade, que saia logo. E quem estiver no campo, que não entre na cidade.

[[v42-21-22]]

^<<v42-21-22,22>>^ Porque aqueles dias serão os "Dias do Castigo", e neles acontecerá tudo o que as Escrituras Sagradas  dizem.

[[v42-21-23]]

^<<v42-21-23,23>>^ Ai das mulheres grávidas e das mães que ainda estiverem amamentando naqueles dias! Porque virá sobre a terra uma grande aflição, e cairá sobre esta gente um terrível castigo de Deus.

[[v42-21-24]]

^<<v42-21-24,24>>^ Muitos serão mortos à espada, e outros serão levados como prisioneiros para todos os países do mundo. E os não judeus conquistarão Jerusalém, até que termine o tempo de eles fazerem isso.

[[v42-21-25]]

^<<v42-21-25,25>>^ E Jesus continuou: — Haverá sinais no sol, na lua e nas estrelas. E, na terra, todas as nações ficarão desesperadas, com medo do terrível barulho do mar e das ondas.

[[v42-21-26]]

^<<v42-21-26,26>>^ Em todo o mundo muitas pessoas desmaiarão de terror ao pensarem no que vai acontecer, pois os poderes do espaço serão abalados.

[[v42-21-27]]

^<<v42-21-27,27>>^ Então o Filho do Homem  aparecerá descendo numa nuvem, com poder e grande glória .

[[v42-21-28]]

^<<v42-21-28,28>>^ Quando essas coisas começarem a acontecer, fiquem firmes e de cabeça erguida, pois logo vocês serão salvos.

[[v42-21-29]]

^<<v42-21-29,29>>^ Em seguida Jesus fez esta comparação: — Vejam o exemplo da figueira ou de qualquer outra árvore.

[[v42-21-30]]

^<<v42-21-30,30>>^ Quando vocês veem que as suas folhas começam a brotar, vocês já sabem que está chegando o verão.

[[v42-21-31]]

^<<v42-21-31,31>>^ Assim também, quando virem acontecer aquelas coisas, fiquem sabendo que o Reino de Deus  está para chegar.

[[v42-21-32]]

^<<v42-21-32,32>>^ Eu afirmo a vocês que isto é verdade: essas coisas vão acontecer antes de morrerem todos os que agora estão vivos.

[[v42-21-33]]

^<<v42-21-33,33>>^ O céu e a terra desaparecerão, mas as minhas palavras ficarão para sempre.

[[v42-21-34]]

^<<v42-21-34,34>>^ E Jesus terminou, dizendo: — Fiquem alertas! Não deixem que as festas, ou as bebedeiras, ou os problemas desta vida façam vocês ficarem tão ocupados, que aquele dia pegue vocês de surpresa,

[[v42-21-35]]

^<<v42-21-35,35>>^ como se fosse uma armadilha. Pois ele cairá sobre todos no mundo inteiro.

[[v42-21-36]]

^<<v42-21-36,36>>^ Portanto, fiquem vigiando e orem sempre, a fim de poderem escapar de tudo o que vai acontecer e poderem estar de pé na presença do Filho do Homem , quando ele vier.

[[v42-21-37]]

^<<v42-21-37,37>>^ Jesus ensinava no pátio do Templo todos os dias. Mas à noite ia para o monte das Oliveiras e ficava ali até de manhã.

[[v42-21-38]]

^<<v42-21-38,38>>^ E todo o povo ia de madrugada para o Templo a fim de ouvi-lo.

'''

xref:042-lucas/042-lucas-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-lucas/042-lucas-022.adoc#v42-22-0[Próximo Capítulo &#62;]