include::./index.adoc[]

[[v42-1-0]]
=== Lucas, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-1-1]]

^<<v42-1-1,1>>^ Prezado Teófilo, Muitas pessoas têm se esforçado para escrever a história das coisas que aconteceram entre nós.

[[v42-1-2]]

^<<v42-1-2,2>>^ Elas escreveram o que foi contado por aqueles que viram essas coisas desde o começo e anunciaram a mensagem do evangelho .

[[v42-1-3]]

^<<v42-1-3,3>>^ Portanto, Excelência, eu estudei com todo o cuidado como foi que essas coisas aconteceram desde o princípio e achei que seria bom escrever tudo em ordem para o senhor,

[[v42-1-4]]

^<<v42-1-4,4>>^ a fim de que o senhor pudesse conhecer toda a verdade sobre os ensinamentos que recebeu.

[[v42-1-5]]

^<<v42-1-5,5>>^ Quando Herodes era o rei da terra de Israel, havia um sacerdote chamado Zacarias, que era do grupo dos sacerdotes de Abias. A esposa dele se chamava Isabel e também era de uma família de sacerdotes.

[[v42-1-6]]

^<<v42-1-6,6>>^ Esse casal vivia a vida que para Deus é correta, obedecendo fielmente a todas as leis  e mandamentos do Senhor.

[[v42-1-7]]

^<<v42-1-7,7>>^ Mas não tinham filhos porque Isabel não podia ter filhos e porque os dois já eram muito velhos.

[[v42-1-8]]

^<<v42-1-8,8>>^ Certo dia no Templo de Jerusalém, Zacarias estava fazendo o seu trabalho de sacerdote, pois era a sua vez de fazer aquele trabalho diário.

[[v42-1-9]]

^<<v42-1-9,9>>^ Conforme o costume dos sacerdotes, ele havia sido escolhido por sorteio  para queimar o incenso no altar e por isso entrou no Templo do Senhor.

[[v42-1-10]]

^<<v42-1-10,10>>^ Durante o tempo em que o incenso queimava, o povo lá fora fazia orações.

[[v42-1-11]]

^<<v42-1-11,11>>^ Então um anjo do Senhor apareceu em frente de Zacarias, de pé, do lado direito do altar.

[[v42-1-12]]

^<<v42-1-12,12>>^ Quando Zacarias o viu, ficou com medo e não sabia o que fazer.

[[v42-1-13]]

^<<v42-1-13,13>>^ Mas o anjo lhe disse: — Não tenha medo, Zacarias, pois Deus ouviu a sua oração! A sua esposa vai ter um filho, e você porá nele o nome de João.

[[v42-1-14]]

^<<v42-1-14,14>>^ O nascimento dele vai trazer alegria e felicidade para você e para muita gente,

[[v42-1-15]]

^<<v42-1-15,15>>^ pois para o Senhor Deus ele será um grande homem. Ele não deverá beber vinho nem cerveja. Ele será cheio do Espírito Santo desde o nascimento

[[v42-1-16]]

^<<v42-1-16,16>>^ e levará muitos israelitas ao Senhor, o Deus de Israel.

[[v42-1-17]]

^<<v42-1-17,17>>^ Ele será mandado por Deus como mensageiro e será forte e poderoso como o profeta  Elias. Ele fará com que pais e filhos façam as pazes e que os desobedientes voltem a andar no caminho direito. E conseguirá preparar o povo de Israel para a vinda do Senhor.

[[v42-1-18]]

^<<v42-1-18,18>>^ Então Zacarias perguntou ao anjo: — Como é que eu vou saber que isso é verdade? Estou muito velho, e a minha mulher também.

[[v42-1-19]]

^<<v42-1-19,19>>^ O anjo respondeu: — Eu sou Gabriel, servo  de Deus, e ele me mandou falar com você para lhe dar essa boa notícia.

[[v42-1-20]]

^<<v42-1-20,20>>^ Você não está acreditando no que eu disse, mas isso acontecerá no tempo certo. E, porque você não acreditou, você ficará mudo e não poderá falar até o dia em que o seu filho nascer.

[[v42-1-21]]

^<<v42-1-21,21>>^ Enquanto isso, o povo estava esperando Zacarias, e todos estavam admirados com a demora dele no Templo.

[[v42-1-22]]

^<<v42-1-22,22>>^ Quando saiu, Zacarias não podia falar. Então perceberam que ele havia tido uma visão no Templo. Sem poder falar, ele fazia sinais com as mãos para o povo.

[[v42-1-23]]

^<<v42-1-23,23>>^ Quando terminaram os seus dias de serviço no Templo, Zacarias voltou para casa.

[[v42-1-24]]

^<<v42-1-24,24>>^ Pouco tempo depois Isabel, a sua esposa, ficou grávida e durante cinco meses não saiu de casa. E ela disse:

[[v42-1-25]]

^<<v42-1-25,25>>^ — Agora que o Senhor me ajudou, ninguém mais vai me desprezar por eu não ter filhos.

[[v42-1-26]]

^<<v42-1-26,26>>^ Quando Isabel estava no sexto mês de gravidez, Deus enviou o anjo Gabriel a uma cidade da Galileia chamada Nazaré.

[[v42-1-27]]

^<<v42-1-27,27>>^ O anjo levava uma mensagem para uma virgem que tinha casamento contratado com um homem chamado José, descendente do rei Davi. Ela se chamava Maria.

[[v42-1-28]]

^<<v42-1-28,28>>^ O anjo veio e disse: — Que a paz esteja com você, Maria! Você é muito abençoada. O Senhor está com você.

[[v42-1-29]]

^<<v42-1-29,29>>^ Porém Maria, quando ouviu o que o anjo disse, ficou sem saber o que pensar. E, admirada, ficou pensando no que ele queria dizer.

[[v42-1-30]]

^<<v42-1-30,30>>^ Então o anjo continuou: — Não tenha medo, Maria! Deus está contente com você.

[[v42-1-31]]

^<<v42-1-31,31>>^ Você ficará grávida, dará à luz um filho e porá nele o nome de Jesus .

[[v42-1-32]]

^<<v42-1-32,32>>^ Ele será um grande homem e será chamado de Filho do Deus Altíssimo. Deus, o Senhor, vai fazê-lo rei, como foi o antepassado dele, o rei Davi.

[[v42-1-33]]

^<<v42-1-33,33>>^ Ele será para sempre rei dos descendentes de Jacó, e o Reino  dele nunca se acabará.

[[v42-1-34]]

^<<v42-1-34,34>>^ Então Maria disse para o anjo: — Isso não é possível, pois eu sou virgem!

[[v42-1-35]]

^<<v42-1-35,35>>^ O anjo respondeu: — O Espírito Santo virá sobre você, e o poder do Deus Altíssimo a envolverá com a sua sombra. Por isso o menino será chamado de santo e Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ Fique sabendo que a sua parenta Isabel está grávida, mesmo sendo tão idosa. Diziam que ela não podia ter filhos, no entanto agora ela já está no sexto mês de gravidez.

[[v42-1-37]]

^<<v42-1-37,37>>^ Porque para Deus nada é impossível.

[[v42-1-38]]

^<<v42-1-38,38>>^ Maria respondeu: — Eu sou uma serva  de Deus; que aconteça comigo o que o senhor acabou de me dizer! E o anjo foi embora.

[[v42-1-39]]

^<<v42-1-39,39>>^ Alguns dias depois, Maria se aprontou e foi depressa para uma cidade que ficava na região montanhosa da Judeia.

[[v42-1-40]]

^<<v42-1-40,40>>^ Entrou na casa de Zacarias e cumprimentou Isabel.

[[v42-1-41]]

^<<v42-1-41,41>>^ Quando Isabel ouviu a saudação de Maria, a criança se mexeu na barriga dela. Então, cheia do poder do Espírito Santo,

[[v42-1-42]]

^<<v42-1-42,42>>^ Isabel disse bem alto: — Você é a mais abençoada de todas as mulheres, e a criança que você vai ter é abençoada também!

[[v42-1-43]]

^<<v42-1-43,43>>^ Quem sou eu para que a mãe do meu Senhor venha me visitar?!

[[v42-1-44]]

^<<v42-1-44,44>>^ Quando ouvi você me cumprimentar, a criança ficou alegre e se mexeu dentro da minha barriga.

[[v42-1-45]]

^<<v42-1-45,45>>^ Você é abençoada, pois acredita que vai acontecer o que o Senhor lhe disse.

[[v42-1-46]]

^<<v42-1-46,46>>^ Então Maria disse:

[[v42-1-47]]

^<<v42-1-47,47>>^ — A minha alma anuncia a grandeza do Senhor. O meu espírito está alegre por causa de Deus, o meu Salvador.

[[v42-1-48]]

^<<v42-1-48,48>>^ Pois ele lembrou de mim, sua humilde serva ! De agora em diante todos vão me chamar de mulher abençoada,

[[v42-1-49]]

^<<v42-1-49,49>>^ porque o Deus Poderoso fez grandes coisas por mim. O seu nome é santo,

[[v42-1-50]]

^<<v42-1-50,50>>^ e ele mostra a sua bondade a todos os que o temem em todas as gerações .

[[v42-1-51]]

^<<v42-1-51,51>>^ Deus levanta a sua mão poderosa e derrota os orgulhosos com todos os planos deles.

[[v42-1-52]]

^<<v42-1-52,52>>^ Derruba dos seus tronos reis poderosos e põe os humildes em altas posições.

[[v42-1-53]]

^<<v42-1-53,53>>^ Dá fartura aos que têm fome e manda os ricos embora com as mãos vazias.

[[v42-1-54]]

^<<v42-1-54,54>>^ Ele cumpriu as promessas que fez aos nossos antepassados e ajudou o povo de Israel, seu servo. Lembrou de mostrar a sua bondade a Abraão e a todos os seus descendentes, para sempre.

[[v42-1-55]]

^<<v42-1-55,55>>^ Ele cumpriu as promessas

[[v42-1-56]]

^<<v42-1-56,56>>^ Maria ficou mais ou menos três meses com Isabel e depois voltou para casa.

[[v42-1-57]]

^<<v42-1-57,57>>^ Chegou o tempo de Isabel ter a criança, e ela deu à luz um menino.

[[v42-1-58]]

^<<v42-1-58,58>>^ Os vizinhos e parentes ouviram falar da grande bondade do Senhor para com Isabel, e todos ficaram alegres com ela.

[[v42-1-59]]

^<<v42-1-59,59>>^ Quando o menino estava com oito dias, vieram circuncidá-lo  e queriam lhe dar o nome do pai, isto é, Zacarias.

[[v42-1-60]]

^<<v42-1-60,60>>^ Mas a sua mãe disse: — Não. O nome dele vai ser João.

[[v42-1-61]]

^<<v42-1-61,61>>^ Então disseram: — Mas você não tem nenhum parente com esse nome!

[[v42-1-62]]

^<<v42-1-62,62>>^ Aí fizeram sinais ao pai, perguntando que nome ele queria pôr no menino.

[[v42-1-63]]

^<<v42-1-63,63>>^ Zacarias pediu uma tabuinha de escrever e escreveu: "O nome dele é João." E todos ficaram muito admirados.

[[v42-1-64]]

^<<v42-1-64,64>>^ Nesse momento Zacarias pôde falar novamente e começou a louvar a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ Os vizinhos ficaram com muito medo, e as notícias dessas coisas se espalharam por toda a região montanhosa da Judeia.

[[v42-1-66]]

^<<v42-1-66,66>>^ Todos os que ouviam essas coisas e pensavam nelas perguntavam: — O que será que esse menino vai ser? Pois, de fato, o poder do Senhor estava com ele.

[[v42-1-67]]

^<<v42-1-67,67>>^ Zacarias, o pai de João, cheio do Espírito Santo, começou a profetizar . Ele disse:

[[v42-1-68]]

^<<v42-1-68,68>>^ — Louvemos o Senhor, o Deus de Israel, pois ele veio ajudar o seu povo e lhe dar a liberdade.

[[v42-1-69]]

^<<v42-1-69,69>>^ Enviou para nós um poderoso Salvador, aquele que é descendente do seu servo  Davi.

[[v42-1-70]]

^<<v42-1-70,70>>^ Faz muito tempo que Deus disse isso por meio dos seus santos profetas .

[[v42-1-71]]

^<<v42-1-71,71>>^ Ele prometeu nos salvar dos nossos inimigos e nos livrar do poder de todos os que nos odeiam.

[[v42-1-72]]

^<<v42-1-72,72>>^ Disse que ia mostrar a sua bondade aos nossos antepassados e lembrar da sua santa aliança .

[[v42-1-73]]

^<<v42-1-73,73>>^ Ele fez um juramento ao nosso antepassado Abraão; prometeu que nos livraria dos nossos inimigos e que ia nos deixar servi-lo sem medo,

[[v42-1-74]]

^<<v42-1-74,74>>^ Ele fez um juramento

[[v42-1-75]]

^<<v42-1-75,75>>^ para que sejamos somente dele e façamos o que ele quer em todos os dias da nossa vida.

[[v42-1-76]]

^<<v42-1-76,76>>^ E você, menino, será chamado de profeta do Deus Altíssimo e irá adiante do Senhor a fim de preparar o caminho para ele.

[[v42-1-77]]

^<<v42-1-77,77>>^ Você anunciará ao povo de Deus a salvação que virá por meio do perdão dos pecados deles.

[[v42-1-78]]

^<<v42-1-78,78>>^ Pois o nosso Deus é misericordioso e bondoso. Ele fará brilhar sobre nós a sua luz

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]