include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-24-1]]

^<<v42-24-1,1>>^ No domingo bem cedo, as mulheres foram ao túmulo, levando os perfumes que haviam preparado.

[[v42-24-2]]

^<<v42-24-2,2>>^ Elas viram que a pedra tinha sido tirada da entrada do túmulo.

[[v42-24-3]]

^<<v42-24-3,3>>^ Porém, quando entraram, não acharam o corpo do Senhor Jesus

[[v42-24-4]]

^<<v42-24-4,4>>^ e não sabiam o que pensar. De repente, apareceram diante delas dois homens vestidos com roupas muito brilhantes.

[[v42-24-5]]

^<<v42-24-5,5>>^ E elas ficaram com medo, e se ajoelharam, e encostaram o rosto no chão. Então os homens disseram a elas: — Por que é que vocês estão procurando entre os mortos quem está vivo?

[[v42-24-6]]

^<<v42-24-6,6>>^ Ele não está aqui, mas foi ressuscitado. Lembrem que, quando estava na Galileia, ele disse a vocês:

[[v42-24-7]]

^<<v42-24-7,7>>^ "O Filho do Homem  precisa ser entregue aos pecadores, precisa ser crucificado e precisa ressuscitar no terceiro dia".

[[v42-24-8]]

^<<v42-24-8,8>>^ Então as mulheres lembraram das palavras dele

[[v42-24-9]]

^<<v42-24-9,9>>^ e, quando voltaram do túmulo, contaram tudo isso aos onze apóstolos  e a todos os outros.

[[v42-24-10]]

^<<v42-24-10,10>>^ Essas mulheres eram Maria Madalena, Joana e Maria, mãe de Tiago. Estas e as outras mulheres que foram com elas contaram tudo isso aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ Mas eles acharam que o que as mulheres estavam dizendo era tolice e não acreditaram.

[[v42-24-12]]

^<<v42-24-12,12>>^ Porém Pedro se levantou e correu para o túmulo. Abaixou-se para olhar e viu somente os lençóis de linho e nada mais. Aí voltou para casa, admirado com o que havia acontecido.

[[v42-24-13]]

^<<v42-24-13,13>>^ Naquele mesmo dia, dois dos seguidores de Jesus estavam indo para um povoado chamado Emaús, que fica a mais ou menos dez quilômetros de Jerusalém.

[[v42-24-14]]

^<<v42-24-14,14>>^ Eles estavam conversando a respeito de tudo o que havia acontecido.

[[v42-24-15]]

^<<v42-24-15,15>>^ Enquanto conversavam e discutiam, o próprio Jesus chegou perto e começou a caminhar com eles,

[[v42-24-16]]

^<<v42-24-16,16>>^ mas alguma coisa não deixou que eles o reconhecessem.

[[v42-24-17]]

^<<v42-24-17,17>>^ Então Jesus perguntou: — O que é que vocês estão conversando pelo caminho? Eles pararam, com um jeito triste,

[[v42-24-18]]

^<<v42-24-18,18>>^ e um deles, chamado Cleopas, disse: — Será que você é o único morador de Jerusalém que não sabe o que aconteceu lá, nestes últimos dias?

[[v42-24-19]]

^<<v42-24-19,19>>^ — O que foi?  — perguntou ele. Eles responderam: — O que aconteceu com Jesus de Nazaré. Esse homem era profeta  e, para Deus e para todo o povo, ele era poderoso em atos e palavras.

[[v42-24-20]]

^<<v42-24-20,20>>^ Os chefes dos sacerdotes e os nossos líderes o entregaram para ser condenado à morte e o crucificaram.

[[v42-24-21]]

^<<v42-24-21,21>>^ E a nossa esperança era que fosse ele quem iria libertar o povo de Israel. Porém já faz três dias que tudo isso aconteceu.

[[v42-24-22]]

^<<v42-24-22,22>>^ Algumas mulheres do nosso grupo nos deixaram espantados, pois foram de madrugada ao túmulo

[[v42-24-23]]

^<<v42-24-23,23>>^ e não encontraram o corpo dele. Voltaram dizendo que viram anjos e que estes afirmaram que ele está vivo.

[[v42-24-24]]

^<<v42-24-24,24>>^ Alguns do nosso grupo foram ao túmulo e viram que realmente aconteceu o que as mulheres disseram, mas não viram Jesus.

[[v42-24-25]]

^<<v42-24-25,25>>^ Então Jesus lhes disse: — Como vocês demoram a entender e a crer em tudo o que os profetas disseram!

[[v42-24-26]]

^<<v42-24-26,26>>^ Pois era preciso que o Messias  sofresse e assim recebesse de Deus toda a glória .

[[v42-24-27]]

^<<v42-24-27,27>>^ E começou a explicar todas as passagens das Escrituras Sagradas  que falavam dele, iniciando com os livros de Moisés e os escritos de todos os Profetas .

[[v42-24-28]]

^<<v42-24-28,28>>^ Quando chegaram perto do povoado para onde iam, Jesus fez como quem ia para mais longe.

[[v42-24-29]]

^<<v42-24-29,29>>^ Mas eles insistiram com ele para que ficasse, dizendo: — Fique conosco porque já é tarde, e a noite vem chegando. Então Jesus entrou para ficar com os dois.

[[v42-24-30]]

^<<v42-24-30,30>>^ Sentou-se à mesa com eles, pegou o pão e deu graças a Deus. Depois partiu o pão e deu a eles.

[[v42-24-31]]

^<<v42-24-31,31>>^ Aí os olhos deles foram abertos, e eles reconheceram Jesus. Mas ele desapareceu.

[[v42-24-32]]

^<<v42-24-32,32>>^ Então eles disseram um para o outro: — Não parecia que o nosso coração queimava dentro do peito quando ele nos falava na estrada e nos explicava as Escrituras Sagradas?

[[v42-24-33]]

^<<v42-24-33,33>>^ Eles se levantaram logo e voltaram para Jerusalém, onde encontraram os onze apóstolos  reunidos com outros seguidores de Jesus.

[[v42-24-34]]

^<<v42-24-34,34>>^ E os apóstolos diziam: — De fato, o Senhor foi ressuscitado e foi visto por Simão!

[[v42-24-35]]

^<<v42-24-35,35>>^ Então os dois contaram o que havia acontecido na estrada e como tinham reconhecido o Senhor quando ele havia partido o pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Enquanto estavam contando isso, Jesus apareceu de repente no meio deles e disse: — Que a paz esteja com vocês!

[[v42-24-37]]

^<<v42-24-37,37>>^ Eles ficaram assustados e com muito medo e pensaram que estavam vendo um fantasma.

[[v42-24-38]]

^<<v42-24-38,38>>^ Mas ele disse: — Por que vocês estão assustados? Por que há tantas dúvidas na cabeça de vocês?

[[v42-24-39]]

^<<v42-24-39,39>>^ Olhem para as minhas mãos e para os meus pés e vejam que sou eu mesmo. Toquem em mim e vocês vão crer, pois um fantasma não tem carne nem ossos, como vocês estão vendo que eu tenho.

[[v42-24-40]]

^<<v42-24-40,40>>^ Jesus disse isso e mostrou as suas mãos e os seus pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ Eles ainda não acreditavam, pois estavam muito alegres e admirados. Então ele perguntou: — Vocês têm aqui alguma coisa para comer?

[[v42-24-42]]

^<<v42-24-42,42>>^ Eles lhe deram um pedaço de peixe assado,

[[v42-24-43]]

^<<v42-24-43,43>>^ que ele pegou e comeu diante deles.

[[v42-24-44]]

^<<v42-24-44,44>>^ Depois disse: — Enquanto ainda estava com vocês, eu disse que tinha de acontecer tudo o que estava escrito a meu respeito na Lei  de Moisés, nos livros dos Profetas  e nos Salmos.

[[v42-24-45]]

^<<v42-24-45,45>>^ Então Jesus abriu a mente deles para que eles entendessem as Escrituras Sagradas

[[v42-24-46]]

^<<v42-24-46,46>>^ e disse: — O que está escrito é que o Messias  tinha de sofrer e no terceiro dia ressuscitar.

[[v42-24-47]]

^<<v42-24-47,47>>^ E que, em nome dele, a mensagem sobre o arrependimento e o perdão dos pecados seria anunciada a todas as nações, começando em Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ Vocês são testemunhas dessas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ E eu lhes mandarei o que o meu Pai prometeu. Mas esperem aqui em Jerusalém, até que o poder de cima venha sobre vocês.

[[v42-24-50]]

^<<v42-24-50,50>>^ Então Jesus os levou para fora da cidade até o povoado de Betânia. Ali levantou as mãos e os abençoou.

[[v42-24-51]]

^<<v42-24-51,51>>^ Enquanto os estava abençoando, Jesus se afastou deles e foi levado para o céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ Eles o adoraram e voltaram para Jerusalém cheios de alegria.

[[v42-24-53]]

^<<v42-24-53,53>>^ E passavam o tempo todo no pátio do Templo, louvando a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]