include::./index.adoc[]

[[v42-18-0]]
=== Lucas, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-18-1]]

^<<v42-18-1,1>>^ Jesus contou a seguinte parábola , mostrando aos discípulos que deviam orar sempre e nunca desanimar:

[[v42-18-2]]

^<<v42-18-2,2>>^ — Em certa cidade havia um juiz que não temia a Deus  e não respeitava ninguém.

[[v42-18-3]]

^<<v42-18-3,3>>^ Nessa cidade morava uma viúva que sempre o procurava para pedir justiça, dizendo: "Ajude-me e julgue o meu caso contra o meu adversário!"

[[v42-18-4]]

^<<v42-18-4,4>>^ — Durante muito tempo o juiz não quis julgar o caso da viúva, mas afinal pensou assim: "É verdade que eu não temo a Deus e também não respeito ninguém.

[[v42-18-5]]

^<<v42-18-5,5>>^ Porém, como esta viúva continua me aborrecendo, vou dar a sentença a favor dela. Se eu não fizer isso, ela não vai parar de vir me amolar até acabar comigo."

[[v42-18-6]]

^<<v42-18-6,6>>^ E o Senhor continuou: — Prestem atenção naquilo que aquele juiz desonesto disse.

[[v42-18-7]]

^<<v42-18-7,7>>^ Será, então, que Deus não vai fazer justiça a favor do seu próprio povo, que grita por socorro dia e noite? Será que ele vai demorar para ajudá-lo?

[[v42-18-8]]

^<<v42-18-8,8>>^ Eu afirmo a vocês que ele julgará a favor do seu povo e fará isso bem depressa. Mas, quando o Filho do Homem  vier, será que vai encontrar fé na terra?

[[v42-18-9]]

^<<v42-18-9,9>>^ Jesus também contou esta parábola  para os que achavam que eram muito bons e desprezavam os outros:

[[v42-18-10]]

^<<v42-18-10,10>>^ — Dois homens foram ao Templo para orar. Um era fariseu , e o outro, cobrador de impostos.

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu ficou de pé e orou sozinho, assim: "Ó Deus, eu te agradeço porque não sou avarento, nem desonesto, nem imoral como as outras pessoas. Agradeço-te também porque não sou como este cobrador de impostos.

[[v42-18-12]]

^<<v42-18-12,12>>^ Jejuo duas vezes por semana e te dou a décima parte de tudo o que ganho."

[[v42-18-13]]

^<<v42-18-13,13>>^ — Mas o cobrador de impostos ficou de longe e nem levantava o rosto para o céu. Batia no peito e dizia: "Ó Deus, tem pena de mim, pois sou pecador!"

[[v42-18-14]]

^<<v42-18-14,14>>^ E Jesus terminou, dizendo: — Eu afirmo a vocês que foi este homem, e não o outro, que voltou para casa em paz com Deus. Porque quem se engrandece será humilhado, e quem se humilha será engrandecido.

[[v42-18-15]]

^<<v42-18-15,15>>^ Depois disso, algumas pessoas levaram as suas crianças a Jesus para que ele as abençoasse, mas os discípulos viram isso e repreenderam aquelas pessoas.

[[v42-18-16]]

^<<v42-18-16,16>>^ Então Jesus chamou as crianças para perto de si e disse: — Deixem que as crianças venham a mim e não proíbam que elas façam isso, pois o Reino de Deus  é das pessoas que são como estas crianças.

[[v42-18-17]]

^<<v42-18-17,17>>^ Eu afirmo a vocês que isto é verdade: quem não receber o Reino de Deus como uma criança nunca entrará nele.

[[v42-18-18]]

^<<v42-18-18,18>>^ Certo líder judeu perguntou a Jesus: — Bom Mestre, o que devo fazer para conseguir a vida eterna?

[[v42-18-19]]

^<<v42-18-19,19>>^ Jesus respondeu: — Por que você me chama de bom? Só Deus é bom, e mais ninguém.

[[v42-18-20]]

^<<v42-18-20,20>>^ Você conhece os mandamentos: "Não cometa adultério, não mate, não roube, não dê falso testemunho contra ninguém, respeite o seu pai e a sua mãe."

[[v42-18-21]]

^<<v42-18-21,21>>^ O homem respondeu: — Desde criança eu tenho obedecido a todos esses mandamentos.

[[v42-18-22]]

^<<v42-18-22,22>>^ Quando Jesus ouviu isso, disse: — Falta mais uma coisa para você fazer. Venda tudo o que você tem, e dê o dinheiro aos pobres, e assim você terá riquezas no céu. Depois venha e me siga.

[[v42-18-23]]

^<<v42-18-23,23>>^ Quando o homem ouviu isso, ficou muito triste, pois era riquíssimo.

[[v42-18-24]]

^<<v42-18-24,24>>^ Vendo a tristeza dele, Jesus disse: — Como é difícil os ricos entrarem no Reino de Deus !

[[v42-18-25]]

^<<v42-18-25,25>>^ É mais difícil um rico entrar no Reino de Deus do que um camelo passar pelo fundo de uma agulha.

[[v42-18-26]]

^<<v42-18-26,26>>^ Os que ouviram isso perguntaram: — Então, quem é que pode se salvar?

[[v42-18-27]]

^<<v42-18-27,27>>^ Jesus respondeu: — O que é impossível para os seres humanos é possível para Deus.

[[v42-18-28]]

^<<v42-18-28,28>>^ Aí Pedro disse: — Veja! Nós deixamos a nossa família e seguimos o senhor.

[[v42-18-29]]

^<<v42-18-29,29>>^ Jesus respondeu: — Eu afirmo a vocês que isto é verdade: aquele que, por causa do Reino de Deus, deixar casa, esposa, irmãos, parentes ou filhos

[[v42-18-30]]

^<<v42-18-30,30>>^ receberá ainda nesta vida muito mais e, no futuro, receberá a vida eterna.

[[v42-18-31]]

^<<v42-18-31,31>>^ Jesus levou os doze discípulos para um lado e disse: — Escutem! Nós estamos indo para Jerusalém, onde vai acontecer tudo o que os profetas  escreveram sobre o Filho do Homem .

[[v42-18-32]]

^<<v42-18-32,32>>^ Ele será entregue aos não judeus, e estes vão zombar dele, insultá-lo, cuspir nele

[[v42-18-33]]

^<<v42-18-33,33>>^ e bater nele; e depois o matarão. Mas no terceiro dia ele ressuscitará.

[[v42-18-34]]

^<<v42-18-34,34>>^ Os discípulos não entenderam nada do que Jesus disse. O que essas palavras queriam dizer estava escondido deles, e eles não sabiam do que Jesus estava falando.

[[v42-18-35]]

^<<v42-18-35,35>>^ Jesus já estava chegando perto da cidade de Jericó. Acontece que um cego estava sentado na beira do caminho, pedindo esmola.

[[v42-18-36]]

^<<v42-18-36,36>>^ Quando ouviu a multidão passando, ele perguntou o que era aquilo.

[[v42-18-37]]

^<<v42-18-37,37>>^ — É Jesus de Nazaré que está passando! — responderam.

[[v42-18-38]]

^<<v42-18-38,38>>^ Aí o cego começou a gritar: — Jesus, Filho de Davi , tenha pena de mim!

[[v42-18-39]]

^<<v42-18-39,39>>^ As pessoas que iam na frente o repreenderam e mandaram que ele calasse a boca. Mas ele gritava ainda mais: — Filho de Davi, tenha pena de mim!

[[v42-18-40]]

^<<v42-18-40,40>>^ Jesus parou e mandou que trouxessem o cego. Quando ele chegou perto, Jesus perguntou:

[[v42-18-41]]

^<<v42-18-41,41>>^ — O que é que você quer que eu faça? — Senhor, eu quero ver de novo! — respondeu ele.

[[v42-18-42]]

^<<v42-18-42,42>>^ Então Jesus disse: — Veja! Você está curado porque teve fé.

[[v42-18-43]]

^<<v42-18-43,43>>^ No mesmo instante o homem começou a ver e, dando glória  a Deus, foi seguindo Jesus. E todos os que viram isso começaram a louvar a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]