include::./index.adoc[]

[[v42-14-0]]
=== Lucas, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-14-1]]

^<<v42-14-1,1>>^ Num sábado, Jesus entrou na casa de certo líder fariseu  para tomar uma refeição. E as pessoas que estavam ali olhavam para Jesus com muita atenção.

[[v42-14-2]]

^<<v42-14-2,2>>^ Um homem, com as pernas e os braços inchados, chegou perto dele.

[[v42-14-3]]

^<<v42-14-3,3>>^ E Jesus perguntou aos mestres  da Lei e aos fariseus: — A nossa Lei  permite curar no sábado ou não?

[[v42-14-4]]

^<<v42-14-4,4>>^ Mas eles não responderam nada. Então Jesus pegou o homem, curou-o e o mandou embora.

[[v42-14-5]]

^<<v42-14-5,5>>^ Aí disse: — Se um filho ou um boi de algum de vocês cair num poço, será que você não vai tirá-lo logo de lá, mesmo que isso aconteça num sábado?

[[v42-14-6]]

^<<v42-14-6,6>>^ E eles não puderam responder.

[[v42-14-7]]

^<<v42-14-7,7>>^ Certa vez Jesus estava reparando como os convidados escolhiam os melhores lugares à mesa. Então fez esta comparação:

[[v42-14-8]]

^<<v42-14-8,8>>^ — Quando alguém convidá-lo para uma festa de casamento, não sente no melhor lugar. Porque pode ser que alguém mais importante tenha sido convidado.

[[v42-14-9]]

^<<v42-14-9,9>>^ Então quem convidou você e o outro poderá dizer a você: "Dê esse lugar para este aqui." Aí você ficará envergonhado e terá de sentar-se no último lugar.

[[v42-14-10]]

^<<v42-14-10,10>>^ Pelo contrário, quando você for convidado, sente-se no último lugar. Assim quem o convidou vai dizer a você: "Meu amigo, venha sentar-se aqui num lugar melhor." E isso será uma grande honra para você diante de todos os convidados.

[[v42-14-11]]

^<<v42-14-11,11>>^ Porque quem se engrandece será humilhado, mas quem se humilha será engrandecido.

[[v42-14-12]]

^<<v42-14-12,12>>^ Depois Jesus disse ao homem que o havia convidado: — Quando você der um almoço ou um jantar, não convide os seus amigos, nem os seus irmãos, nem os seus parentes, nem os seus vizinhos ricos. Porque certamente eles também o convidarão e assim pagarão a gentileza que você fez.

[[v42-14-13]]

^<<v42-14-13,13>>^ Mas, quando você der uma festa, convide os pobres, os aleijados, os coxos e os cegos

[[v42-14-14]]

^<<v42-14-14,14>>^ e você será abençoado. Pois eles não poderão pagar o que você fez, mas Deus lhe pagará no dia em que as pessoas que fazem o bem ressuscitarem.

[[v42-14-15]]

^<<v42-14-15,15>>^ Um dos que estavam à mesa ouviu isso e disse para Jesus: — Felizes os que irão sentar-se à mesa no Reino de Deus !

[[v42-14-16]]

^<<v42-14-16,16>>^ Então Jesus lhe disse: — Certo homem convidou muita gente para uma festa que ia dar.

[[v42-14-17]]

^<<v42-14-17,17>>^ Quando chegou a hora, mandou o seu empregado dizer aos convidados: "Venham, que tudo já está pronto!"

[[v42-14-18]]

^<<v42-14-18,18>>^ — Mas eles, um por um, começaram a dar desculpas. O primeiro disse ao empregado: "Comprei um sítio e tenho de dar uma olhada nele. Peço que me desculpe."

[[v42-14-19]]

^<<v42-14-19,19>>^ — Outro disse: "Comprei cinco juntas de bois e preciso ver se trabalham bem. Peço que me desculpe."

[[v42-14-20]]

^<<v42-14-20,20>>^ — E outro disse: "Acabei de casar e por isso não posso ir."

[[v42-14-21]]

^<<v42-14-21,21>>^ — O empregado voltou e contou tudo ao patrão. Ele ficou com muita raiva e disse: "Vá depressa pelas ruas e pelos becos da cidade e traga os pobres, os aleijados, os cegos e os coxos."

[[v42-14-22]]

^<<v42-14-22,22>>^ — Mais tarde o empregado disse: "Patrão, já fiz o que o senhor mandou, mas ainda está sobrando lugar."

[[v42-14-23]]

^<<v42-14-23,23>>^ — Aí o patrão respondeu: "Então vá pelas estradas e pelos caminhos e obrigue os que você encontrar ali a virem, a fim de que a minha casa fique cheia.

[[v42-14-24]]

^<<v42-14-24,24>>^ Pois eu afirmo a vocês que nenhum dos que foram convidados provará o meu jantar!"

[[v42-14-25]]

^<<v42-14-25,25>>^ Certa vez uma grande multidão estava acompanhando Jesus. Ele virou-se para eles e disse:

[[v42-14-26]]

^<<v42-14-26,26>>^ — Quem quiser me acompanhar não pode ser meu seguidor se não me amar mais do que ama o seu pai, a sua mãe, a sua esposa, os seus filhos, os seus irmãos, as suas irmãs e até a si mesmo.

[[v42-14-27]]

^<<v42-14-27,27>>^ Não pode ser meu seguidor quem não estiver pronto para morrer como eu vou morrer e me acompanhar.

[[v42-14-28]]

^<<v42-14-28,28>>^ Se um de vocês quer construir uma torre , primeiro senta e calcula quanto vai custar, para ver se o dinheiro dá.

[[v42-14-29]]

^<<v42-14-29,29>>^ Se não fizer isso, ele consegue colocar os alicerces, mas não pode terminar a construção. Aí todos os que virem o que aconteceu vão caçoar dele, dizendo:

[[v42-14-30]]

^<<v42-14-30,30>>^ "Este homem começou a construir, mas não pôde terminar!"

[[v42-14-31]]

^<<v42-14-31,31>>^ — Se um rei que tem dez mil soldados vai partir para combater outro que vem contra ele com vinte mil, ele senta primeiro e vê se está bastante forte para enfrentar o outro.

[[v42-14-32]]

^<<v42-14-32,32>>^ Se não fizer isso, acabará precisando mandar mensageiros ao outro rei, enquanto este ainda estiver longe, para combinar condições de paz. Jesus terminou, dizendo:

[[v42-14-33]]

^<<v42-14-33,33>>^ — Assim nenhum de vocês pode ser meu discípulo se não deixar tudo o que tem.

[[v42-14-34]]

^<<v42-14-34,34>>^ — O sal é uma coisa útil; mas, se perde o gosto, deixa de ser sal.

[[v42-14-35]]

^<<v42-14-35,35>>^ É jogado fora, pois não serve mais nem para a terra nem para o monte de esterco. Se vocês têm ouvidos para ouvirem, então ouçam.

'''

xref:042-lucas/042-lucas-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-lucas/042-lucas-015.adoc#v42-15-0[Próximo Capítulo &#62;]