include::./index.adoc[]

[[v42-17-0]]
=== Lucas, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v42-17-1]]

^<<v42-17-1,1>>^ Jesus disse aos seus discípulos: — Sempre vão acontecer coisas que fazem com que as pessoas caiam em pecado, mas ai do culpado!

[[v42-17-2]]

^<<v42-17-2,2>>^ Seria melhor para essa pessoa que ela fosse jogada no mar com uma grande pedra de moinho amarrada no pescoço do que fazer com que um destes pequeninos peque.

[[v42-17-3]]

^<<v42-17-3,3>>^ Tenham cuidado! Se o seu irmão pecar, repreenda-o; se ele se arrepender, perdoe.

[[v42-17-4]]

^<<v42-17-4,4>>^ Se pecar contra você sete vezes num dia e cada vez vier e disser: "Me arrependo", então perdoe.

[[v42-17-5]]

^<<v42-17-5,5>>^ Os apóstolos  pediram ao Senhor: — Aumente a nossa fé.

[[v42-17-6]]

^<<v42-17-6,6>>^ E ele respondeu: — Se a fé que vocês têm fosse do tamanho de uma semente de mostarda, vocês poderiam dizer a esta figueira brava: "Arranque-se pelas raízes e vá se plantar no mar!" E ela obedeceria.

[[v42-17-7]]

^<<v42-17-7,7>>^ Jesus disse: — Façam de conta que um de vocês tem um empregado que trabalha na lavoura ou cuida das ovelhas. Quando ele volta do campo, será que você vai dizer: "Venha depressa e sente-se à mesa"?

[[v42-17-8]]

^<<v42-17-8,8>>^ Claro que não! Pelo contrário, você dirá: "Prepare o jantar para mim, ponha o avental e me sirva enquanto eu como e bebo. Depois você pode comer e beber."

[[v42-17-9]]

^<<v42-17-9,9>>^ Por acaso o empregado merece agradecimento porque obedeceu às suas ordens?

[[v42-17-10]]

^<<v42-17-10,10>>^ Assim deve ser com vocês. Depois de fazerem tudo o que foi mandado, digam: "Somos empregados que não valem nada porque fizemos somente o nosso dever."

[[v42-17-11]]

^<<v42-17-11,11>>^ Jesus continuava viajando para Jerusalém e passou entre as regiões da Samaria e da Galileia.

[[v42-17-12]]

^<<v42-17-12,12>>^ Quando estava entrando num povoado, dez leprosos foram se encontrar com ele. Eles pararam de longe

[[v42-17-13]]

^<<v42-17-13,13>>^ e gritaram: — Jesus, Mestre, tenha pena de nós!

[[v42-17-14]]

^<<v42-17-14,14>>^ Jesus os viu e disse: — Vão e peçam aos sacerdotes que examinem vocês. Quando iam pelo caminho, eles foram curados.

[[v42-17-15]]

^<<v42-17-15,15>>^ E, quando um deles, que era samaritano , viu que estava curado, voltou louvando a Deus em voz alta.

[[v42-17-16]]

^<<v42-17-16,16>>^ Ajoelhou-se aos pés de Jesus e lhe agradeceu.

[[v42-17-17]]

^<<v42-17-17,17>>^ Jesus disse: — Os homens que foram curados eram dez. Onde estão os outros nove?

[[v42-17-18]]

^<<v42-17-18,18>>^ Por que somente este estrangeiro voltou para louvar a Deus?

[[v42-17-19]]

^<<v42-17-19,19>>^ E Jesus disse a ele: — Levante-se e vá. Você está curado porque teve fé.

[[v42-17-20]]

^<<v42-17-20,20>>^ Alguns fariseus  perguntaram a Jesus quando ia chegar o Reino de Deus . Ele respondeu: — Quando o Reino de Deus chegar, não será uma coisa que se possa ver.

[[v42-17-21]]

^<<v42-17-21,21>>^ Ninguém vai dizer: "Vejam! Está aqui" ou "Está ali". Porque o Reino de Deus está dentro de vocês.

[[v42-17-22]]

^<<v42-17-22,22>>^ Então ele disse aos discípulos: — Chegará o tempo em que vocês vão querer ver um dos dias em que o Filho do Homem  já tiver chegado, mas não verão.

[[v42-17-23]]

^<<v42-17-23,23>>^ Alguns vão dizer a vocês: "Olhem aqui" ou "Olhem ali"; porém não saiam para procurá-lo.

[[v42-17-24]]

^<<v42-17-24,24>>^ Porque, assim como o relâmpago brilha de uma ponta do céu até a outra, assim será no dia em que o Filho do Homem vier.

[[v42-17-25]]

^<<v42-17-25,25>>^ Mas primeiro ele precisa sofrer e ser rejeitado pelo povo de hoje.

[[v42-17-26]]

^<<v42-17-26,26>>^ Como foi no tempo de Noé, assim também será nos dias de antes da vinda do Filho do Homem.

[[v42-17-27]]

^<<v42-17-27,27>>^ Todos comiam e bebiam, e os homens e as mulheres casavam, até o dia em que Noé entrou na barca. Depois veio o dilúvio e matou todos.

[[v42-17-28]]

^<<v42-17-28,28>>^ A mesma coisa aconteceu no tempo de Ló. Todos comiam e bebiam, compravam e vendiam, plantavam e construíam.

[[v42-17-29]]

^<<v42-17-29,29>>^ No dia em que Ló saiu de Sodoma, choveu do céu fogo e enxofre e matou todos.

[[v42-17-30]]

^<<v42-17-30,30>>^ Assim será o dia em que o Filho do Homem aparecer.

[[v42-17-31]]

^<<v42-17-31,31>>^ Aí quem estiver em cima da sua casa, no terraço, desça, e fuja logo, e não perca tempo entrando na casa para pegar as suas coisas. E quem estiver no campo não volte para casa.

[[v42-17-32]]

^<<v42-17-32,32>>^ Lembrem da mulher de Ló.

[[v42-17-33]]

^<<v42-17-33,33>>^ A pessoa que procura os seus próprios interesses nunca terá a vida verdadeira; mas quem esquece a si mesmo terá a vida verdadeira.

[[v42-17-34]]

^<<v42-17-34,34>>^ Naquela noite duas pessoas estarão dormindo numa mesma cama. Eu afirmo a vocês que uma será levada, e a outra, deixada.

[[v42-17-35]]

^<<v42-17-35,35>>^ Duas mulheres estarão moendo trigo juntas: uma será levada, e a outra, deixada.

[[v42-17-36]]

^<<v42-17-36,36>>^ [Naquele dia, dois homens estarão trabalhando na fazenda: um será levado, e o outro, deixado.]

[[v42-17-37]]

^<<v42-17-37,37>>^ Então os discípulos perguntaram: — Senhor, onde vai ser isso? Ele respondeu: — Onde estiver o corpo de um morto, aí se ajuntarão os urubus.

'''

xref:042-lucas/042-lucas-016.adoc#v42-16-0[&#60; Capítulo Anterior] | <<v42-17-0,Topo>> | xref:042-lucas/042-lucas-018.adoc#v42-18-0[Próximo Capítulo &#62;]