include::./index.adoc[]

[[v20-7-0]]
=== Provérbios, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-7-1]]

^<<v20-7-1,1>>^ Filho, lembre do que eu digo e nunca esqueça os meus conselhos.

[[v20-7-2]]

^<<v20-7-2,2>>^ Faça o que eu digo e você viverá. Siga as minhas instruções com o mesmo cuidado com que você protege os olhos.

[[v20-7-3]]

^<<v20-7-3,3>>^ Guarde sempre os meus ensinamentos bem-gravados no coração.

[[v20-7-4]]

^<<v20-7-4,4>>^ Trate a Sabedoria como sua irmã e o Entendimento, como o seu melhor amigo.

[[v20-7-5]]

^<<v20-7-5,5>>^ Eles conservarão você longe das mulheres imorais, das mulheres de palavras sedutoras.

[[v20-7-6]]

^<<v20-7-6,6>>^ Uma vez eu estava olhando pela janela da minha casa

[[v20-7-7]]

^<<v20-7-7,7>>^ e vi vários rapazes sem experiência; mas notei que um deles era mesmo sem juízo.

[[v20-7-8]]

^<<v20-7-8,8>>^ Esse rapaz estava andando pela rua, perto da esquina onde morava uma certa mulher. Ele passava por perto da casa dela,

[[v20-7-9]]

^<<v20-7-9,9>>^ ao anoitecer, quando já estava escuro.

[[v20-7-10]]

^<<v20-7-10,10>>^ E aconteceu que essa mulher foi encontrar-se com ele, vestida como uma prostituta e cheia de malícia.

[[v20-7-11]]

^<<v20-7-11,11>>^ Ela era espalhafatosa e sem-vergonha e estava sempre andando pelas ruas.

[[v20-7-12]]

^<<v20-7-12,12>>^ Ficava esperando em alguma esquina, às vezes numa rua, outras vezes na praça.

[[v20-7-13]]

^<<v20-7-13,13>>^ Ela chegou perto do rapaz, e o abraçou, e beijou. Então, com um olhar atrevido, disse:

[[v20-7-14]]

^<<v20-7-14,14>>^ — Paguei hoje os meus votos, e a carne da oferta de paz está comigo.

[[v20-7-15]]

^<<v20-7-15,15>>^ Por isso saí procurando você. Eu queria encontrá-lo, e você está aqui!

[[v20-7-16]]

^<<v20-7-16,16>>^ Já forrei a minha cama com lençóis de linho colorido do Egito.

[[v20-7-17]]

^<<v20-7-17,17>>^ Eu a perfumei com mirra , aloés  e flor de canela.

[[v20-7-18]]

^<<v20-7-18,18>>^ Venha, vamos amar a noite toda. Passaremos momentos felizes nos braços um do outro.

[[v20-7-19]]

^<<v20-7-19,19>>^ O meu marido não está em casa; ele foi fazer uma longa viagem.

[[v20-7-20]]

^<<v20-7-20,20>>^ Levou bastante dinheiro e só voltará daqui a alguns dias.

[[v20-7-21]]

^<<v20-7-21,21>>^ Assim, ela o tentou com os seus encantos, e ele caiu na sua conversa.

[[v20-7-22]]

^<<v20-7-22,22>>^ E, num instante, lá foi ele com ela, como um boi que vai para o matadouro, como um animal que corre para a armadilha,

[[v20-7-23]]

^<<v20-7-23,23>>^ onde uma flecha atravessará o seu coração. Era como um pássaro que entra num alçapão, sem saber que a sua vida está em perigo.

[[v20-7-24]]

^<<v20-7-24,24>>^ Agora, meu filho, escute! Preste atenção no que vou dizer.

[[v20-7-25]]

^<<v20-7-25,25>>^ Não deixe que uma mulher como essa ganhe o seu coração; não ande atrás dela.

[[v20-7-26]]

^<<v20-7-26,26>>^ Pois ela tem sido a desgraça de muitos homens e tem causado a morte de tantos, que nem dá para contar.

[[v20-7-27]]

^<<v20-7-27,27>>^ Se você for à casa dessa mulher, estará caminhando para o mundo dos mortos , pelo caminho mais curto.

'''

xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[&#60; Capítulo Anterior] | <<v20-7-0,Topo>> | xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[Próximo Capítulo &#62;]