include::./index.adoc[]

[[v20-1-0]]
=== Provérbios, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-1-1]]

^<<v20-1-1,1>>^ Provérbios de Salomão, filho de Davi e rei de Israel.

[[v20-1-2]]

^<<v20-1-2,2>>^ Estes provérbios nos ajudam a dar valor à sabedoria e aos bons conselhos e a entender os pensamentos mais profundos.

[[v20-1-3]]

^<<v20-1-3,3>>^ Eles nos ensinam a vivermos de maneira inteligente e a sermos corretos, justos e honestos.

[[v20-1-4]]

^<<v20-1-4,4>>^ Podem também tornar sábia uma pessoa sem experiência e ensinar os moços a serem ajuizados.

[[v20-1-5]]

^<<v20-1-5,5>>^ Estes provérbios aumentam a sabedoria dos sábios e orientam os instruídos,

[[v20-1-6]]

^<<v20-1-6,6>>^ fazendo que entendam o significado escondido dos provérbios e dos ditados e compreendam os mistérios que os estudiosos procuram explicar.

[[v20-1-7]]

^<<v20-1-7,7>>^ Para ser sábio, é preciso primeiro temer a Deus , o Senhor . Os tolos desprezam a sabedoria e não querem aprender.

[[v20-1-8]]

^<<v20-1-8,8>>^ Meu filho, escute o que o seu pai ensina e preste atenção no que a sua mãe diz.

[[v20-1-9]]

^<<v20-1-9,9>>^ Os ensinamentos deles vão aperfeiçoar o seu caráter, assim como um belo turbante  ou um colar melhoram a sua aparência.

[[v20-1-10]]

^<<v20-1-10,10>>^ Filho, se homens perversos quiserem tentar você, não deixe.

[[v20-1-11]]

^<<v20-1-11,11>>^ Eles poderão dizer: "Venha, vamos matar alguém! Vamos nos divertir atacando pessoas inocentes!

[[v20-1-12]]

^<<v20-1-12,12>>^ Estarão vivas e com saúde quando as encontrarmos, mas nós acabaremos com elas.

[[v20-1-13]]

^<<v20-1-13,13>>^ Acharemos todo tipo de riquezas e encheremos as nossas casas com as coisas roubadas.

[[v20-1-14]]

^<<v20-1-14,14>>^ Venha com a gente, que nós repartiremos o que roubarmos!"

[[v20-1-15]]

^<<v20-1-15,15>>^ Filho, não ande com gente dessa laia. Fique longe deles.

[[v20-1-16]]

^<<v20-1-16,16>>^ Eles têm pressa de fazer o mal e estão sempre prontos para matar.

[[v20-1-17]]

^<<v20-1-17,17>>^ Não adianta armar uma arapuca enquanto o passarinho estiver olhando.

[[v20-1-18]]

^<<v20-1-18,18>>^ No entanto esses homens estão preparando uma armadilha onde eles mesmos morrerão.

[[v20-1-19]]

^<<v20-1-19,19>>^ O que acontece com quem fica rico por meio da violência é isto: acaba sendo morto.

[[v20-1-20]]

^<<v20-1-20,20>>^ Escutem! A Sabedoria está gritando nas ruas e nas praças.

[[v20-1-21]]

^<<v20-1-21,21>>^ Nos portões das cidades e em todos os lugares onde o povo se reúne, ela está gritando alto, assim:

[[v20-1-22]]

^<<v20-1-22,22>>^ — Gente louca! Até quando vocês continuarão nesta loucura? Até quando terão prazer em zombar da sabedoria? Será que nunca aprenderão?

[[v20-1-23]]

^<<v20-1-23,23>>^ Escutem quando eu os corrijo. Eu darei bons conselhos e repartirei a minha sabedoria com vocês.

[[v20-1-24]]

^<<v20-1-24,24>>^ Eu chamei e convidei, mas vocês não me ouviram e não me deram atenção.

[[v20-1-25]]

^<<v20-1-25,25>>^ Vocês rejeitaram todos os meus conselhos e não quiseram que eu os corrigisse.

[[v20-1-26]]

^<<v20-1-26,26>>^ Assim, quando estiverem em dificuldades, eu rirei; e, quando o terror chegar, eu caçoarei de vocês.

[[v20-1-27]]

^<<v20-1-27,27>>^ Zombarei de vocês quando o terror vier como uma tempestade, trazendo fortes ventos de dificuldades. Eu rirei quando estiverem passando por sofrimentos e aflições.

[[v20-1-28]]

^<<v20-1-28,28>>^ Então vocês me chamarão, mas eu, a Sabedoria, não responderei. Vão procurar por toda parte, porém não me encontrarão.

[[v20-1-29]]

^<<v20-1-29,29>>^ Vocês não quiseram a sabedoria e sempre se recusaram a temer a Deus , o Senhor .

[[v20-1-30]]

^<<v20-1-30,30>>^ Não aceitaram os meus conselhos, nem prestaram atenção quando os corrigi.

[[v20-1-31]]

^<<v20-1-31,31>>^ Portanto, receberão o que merecem e ficarão aborrecidos com as coisas que fizeram.

[[v20-1-32]]

^<<v20-1-32,32>>^ Os tolos morrem porque rejeitam a sabedoria; os que não têm juízo são destruídos por estarem satisfeitos consigo mesmos.

[[v20-1-33]]

^<<v20-1-33,33>>^ Mas quem me ouvir terá segurança, viverá tranquilo e não terá motivo para ter medo de nada.

'''

xref:019-salmos/019-salmos-150.adoc#v19-150-0[&#60; Capítulo Anterior] | <<v20-1-0,Topo>> | xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[Próximo Capítulo &#62;]