include::./index.adoc[]

[[v20-4-0]]
=== Provérbios, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-4-1]]

^<<v20-4-1,1>>^ Filhos, escutem o que o seu pai ensina. Prestem atenção e compreenderão as coisas.

[[v20-4-2]]

^<<v20-4-2,2>>^ O que eu ensino é bom; portanto, lembrem dos meus conselhos.

[[v20-4-3]]

^<<v20-4-3,3>>^ Quando eu era menino, filho único dos meus pais,

[[v20-4-4]]

^<<v20-4-4,4>>^ o meu pai me ensinava, dizendo: — Lembre das minhas palavras e nunca as esqueça. Faça o que eu digo e você viverá.

[[v20-4-5]]

^<<v20-4-5,5>>^ Procure conseguir sabedoria e compreensão. Não esqueça, nem se afaste do que eu digo.

[[v20-4-6]]

^<<v20-4-6,6>>^ Não abandone a sabedoria, e ela protegerá você. Ame-a, e ela lhe dará segurança.

[[v20-4-7]]

^<<v20-4-7,7>>^ Para ter sabedoria, é preciso primeiro pagar o seu preço. Use tudo o que você tem para conseguir a compreensão.

[[v20-4-8]]

^<<v20-4-8,8>>^ Ame a sabedoria, e ela o tornará importante; abrace-a e você será respeitado.

[[v20-4-9]]

^<<v20-4-9,9>>^ A sabedoria será para você um enfeite, como se fosse uma linda coroa.

[[v20-4-10]]

^<<v20-4-10,10>>^ Escute, meu filho. Aceite o que estou dizendo e você terá uma vida longa.

[[v20-4-11]]

^<<v20-4-11,11>>^ Eu lhe tenho ensinado o caminho da sabedoria e a maneira certa de viver.

[[v20-4-12]]

^<<v20-4-12,12>>^ Se você andar sabiamente, nada atrapalhará o seu caminho, e você não tropeçará quando correr.

[[v20-4-13]]

^<<v20-4-13,13>>^ Lembre sempre daquilo que aprendeu. A sua educação é a sua vida; guarde-a bem.

[[v20-4-14]]

^<<v20-4-14,14>>^ Não vá aonde vão os maus. Não siga o exemplo deles.

[[v20-4-15]]

^<<v20-4-15,15>>^ Não faça o que eles fazem. Afaste-se do mal. Desvie-se dele e passe de lado.

[[v20-4-16]]

^<<v20-4-16,16>>^ Os maus não podem dormir sem ter feito alguma coisa má; eles ficam acordados até conseguirem prejudicar alguém.

[[v20-4-17]]

^<<v20-4-17,17>>^ Porque para eles a maldade e a violência são comida e bebida.

[[v20-4-18]]

^<<v20-4-18,18>>^ A estrada em que caminham as pessoas direitas é como a luz da aurora, que brilha cada vez mais até ser dia claro.

[[v20-4-19]]

^<<v20-4-19,19>>^ Mas a estrada dos maus é escura como a noite; eles caem e não podem ver no que foi que tropeçaram.

[[v20-4-20]]

^<<v20-4-20,20>>^ Filho, preste atenção no que eu digo. Escute as minhas palavras.

[[v20-4-21]]

^<<v20-4-21,21>>^ Nunca deixe que elas se afastem de você. Lembre delas e ame-as.

[[v20-4-22]]

^<<v20-4-22,22>>^ Elas darão vida longa e saúde a quem entendê-las.

[[v20-4-23]]

^<<v20-4-23,23>>^ Tenha cuidado com o que você pensa, pois a sua vida é dirigida pelos seus pensamentos.

[[v20-4-24]]

^<<v20-4-24,24>>^ Nunca fale mentiras, nem diga palavras perversas.

[[v20-4-25]]

^<<v20-4-25,25>>^ Olhe firme para a frente, com toda a confiança; não abaixe a cabeça, envergonhado.

[[v20-4-26]]

^<<v20-4-26,26>>^ Pense bem no que você vai fazer, e todos os seus planos darão certo.

[[v20-4-27]]

^<<v20-4-27,27>>^ Evite o mal e caminhe sempre em frente; não se desvie nem um só passo do caminho certo.

'''

xref:020-proverbios/020-proverbios-003.adoc#v20-3-0[&#60; Capítulo Anterior] | <<v20-4-0,Topo>> | xref:020-proverbios/020-proverbios-005.adoc#v20-5-0[Próximo Capítulo &#62;]