include::./index.adoc[]

[[v20-29-0]]
=== Provérbios, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-29-1]]

^<<v20-29-1,1>>^ Quem é repreendido muitas vezes e teima em não se corrigir cairá de repente na desgraça e não poderá escapar.

[[v20-29-2]]

^<<v20-29-2,2>>^ Quando os honestos governam, o povo se alegra; mas, quando os maus dominam, o povo reclama.

[[v20-29-3]]

^<<v20-29-3,3>>^ O filho que ama a sabedoria é o orgulho do seu pai. Quem anda com prostitutas desperdiça tudo o que tem.

[[v20-29-4]]

^<<v20-29-4,4>>^ Quando o governo é justo, o país tem segurança; mas, quando o governo cobra impostos demais, a nação acaba na desgraça.

[[v20-29-5]]

^<<v20-29-5,5>>^ Quem bajula os seus amigos está armando uma armadilha para si mesmo.

[[v20-29-6]]

^<<v20-29-6,6>>^ Os maus são apanhados na armadilha dos seus próprios pecados, mas os honestos andam livres e felizes.

[[v20-29-7]]

^<<v20-29-7,7>>^ A pessoa correta se interessa pelos direitos dos pobres, porém os maus não se importam com essas coisas.

[[v20-29-8]]

^<<v20-29-8,8>>^ Os que zombam de tudo põem uma cidade inteira em confusão, mas os sábios mantêm tudo em paz.

[[v20-29-9]]

^<<v20-29-9,9>>^ Quando um homem inteligente discute com um tolo, este somente ri, xinga e causa confusão.

[[v20-29-10]]

^<<v20-29-10,10>>^ Os assassinos odeiam as pessoas direitas, mas os bons protegem a vida delas.

[[v20-29-11]]

^<<v20-29-11,11>>^ O tolo mostra toda a sua raiva, mas quem é sensato se cala e a domina.

[[v20-29-12]]

^<<v20-29-12,12>>^ Quando um governador dá atenção a mentiras, todos os seus auxiliares acabam se tornando maus.

[[v20-29-13]]

^<<v20-29-13,13>>^ O pobre e aquele que o explora só têm uma coisa em comum: o Senhor  Deus lhes deu olhos para verem.

[[v20-29-14]]

^<<v20-29-14,14>>^ As autoridades que defendem o direito dos pobres governam por muito tempo.

[[v20-29-15]]

^<<v20-29-15,15>>^ É bom corrigir e disciplinar a criança. Quando todas as suas vontades são feitas, ela acaba fazendo a sua mãe passar vergonha.

[[v20-29-16]]

^<<v20-29-16,16>>^ Quando os maus estão no poder, o crime aumenta; mas as pessoas honestas viverão o suficiente para ver a queda dos maus.

[[v20-29-17]]

^<<v20-29-17,17>>^ Corrija os seus filhos, e eles serão para você motivo de orgulho e não de vergonha.

[[v20-29-18]]

^<<v20-29-18,18>>^ Um país sem a orientação de Deus é um país sem ordem. Quem guarda a lei  de Deus é feliz.

[[v20-29-19]]

^<<v20-29-19,19>>^ Não adianta nada corrigir um escravo somente com palavras porque, mesmo que ele entenda, não obedecerá.

[[v20-29-20]]

^<<v20-29-20,20>>^ Há mais esperança para um tolo do que para uma pessoa que fala sem pensar.

[[v20-29-21]]

^<<v20-29-21,21>>^ O escravo que é mimado desde criança um dia vai querer ser dono de tudo.

[[v20-29-22]]

^<<v20-29-22,22>>^ A pessoa de mau gênio sempre causa problemas e discórdias.

[[v20-29-23]]

^<<v20-29-23,23>>^ O orgulhoso acaba sendo humilhado, mas quem é humilde será respeitado.

[[v20-29-24]]

^<<v20-29-24,24>>^ O companheiro de um ladrão é o pior inimigo de si mesmo. Se ele disser a verdade no tribunal, será castigado; se não disser, Deus o amaldiçoará.

[[v20-29-25]]

^<<v20-29-25,25>>^ É perigoso ter medo dos outros, mas confiar no Senhor  dá segurança.

[[v20-29-26]]

^<<v20-29-26,26>>^ Todos querem agradar às pessoas importantes, mas o Senhor  dá o que cada um merece.

[[v20-29-27]]

^<<v20-29-27,27>>^ Os homens direitos não toleram os maus, e os perversos não toleram os que vivem honestamente.

'''

xref:020-proverbios/020-proverbios-028.adoc#v20-28-0[&#60; Capítulo Anterior] | <<v20-29-0,Topo>> | xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[Próximo Capítulo &#62;]