include::./index.adoc[]

[[v20-20-0]]
=== Provérbios, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-20-1]]

^<<v20-20-1,1>>^ Quem bebe demais fica barulhento e caçoa dos outros; o escravo da bebida nunca será sábio.

[[v20-20-2]]

^<<v20-20-2,2>>^ A raiva do rei é como o rugido de um leão; quem provoca o rei arrisca a vida.

[[v20-20-3]]

^<<v20-20-3,3>>^ Qualquer tolo pode começar uma briga; quem fica fora dela é que merece elogios.

[[v20-20-4]]

^<<v20-20-4,4>>^ O lavrador preguiçoso, que não ara as suas terras no tempo certo, não terá nada para colher.

[[v20-20-5]]

^<<v20-20-5,5>>^ Os pensamentos de uma pessoa são como água em poço fundo, mas quem é inteligente sabe como tirá-los para fora.

[[v20-20-6]]

^<<v20-20-6,6>>^ Todos dizem que são bons e fiéis, mas tente achar alguém que realmente seja!

[[v20-20-7]]

^<<v20-20-7,7>>^ Como são felizes os filhos de um pai honesto e direito!

[[v20-20-8]]

^<<v20-20-8,8>>^ Quando o rei senta para julgar, ele logo vê o que está errado.

[[v20-20-9]]

^<<v20-20-9,9>>^ Será que alguém pode dizer que tem a consciência limpa e que já se livrou dos seus pecados?

[[v20-20-10]]

^<<v20-20-10,10>>^ O Senhor  Deus detesta quem usa medidas e pesos desonestos.

[[v20-20-11]]

^<<v20-20-11,11>>^ A criança mostra o que é pelo que faz; pelos seus atos a gente pode saber se ela é honesta e boa.

[[v20-20-12]]

^<<v20-20-12,12>>^ O Senhor  nos deu olhos para ver e ouvidos para ouvir.

[[v20-20-13]]

^<<v20-20-13,13>>^ Se você gastar o seu tempo dormindo, acabará pobre; trabalhe e terá comida com fartura.

[[v20-20-14]]

^<<v20-20-14,14>>^ Está muito caro — diz o comprador, mas depois sai e se gaba de ter feito um ótimo negócio.

[[v20-20-15]]

^<<v20-20-15,15>>^ Há muito ouro e muitas pedras preciosas; mas falar com conhecimento, isso, sim, é uma joia de valor.

[[v20-20-16]]

^<<v20-20-16,16>>^ Quem aceita ser fiador de um estranho deve dar a sua roupa como garantia de pagamento.

[[v20-20-17]]

^<<v20-20-17,17>>^ A comida que se consegue desonestamente pode ser muito gostosa, mas depois será como areia na boca.

[[v20-20-18]]

^<<v20-20-18,18>>^ Procure bons conselhos e você terá sucesso; não entre na batalha sem antes fazer planos.

[[v20-20-19]]

^<<v20-20-19,19>>^ O mexeriqueiro espalha os segredos; por isso fique longe de quem fala demais.

[[v20-20-20]]

^<<v20-20-20,20>>^ Se você amaldiçoar os seus pais, a sua vida terminará como uma lâmpada que se apaga na escuridão.

[[v20-20-21]]

^<<v20-20-21,21>>^ A riqueza que é ganha facilmente não faz bem à gente.

[[v20-20-22]]

^<<v20-20-22,22>>^ Não seja vingativo; confie em Deus, o Senhor , e ele fará justiça a você.

[[v20-20-23]]

^<<v20-20-23,23>>^ O Senhor  detesta quem usa medidas e pesos desonestos.

[[v20-20-24]]

^<<v20-20-24,24>>^ Se é o Senhor  quem dirige os nossos passos, como poderemos entender a nossa vida?

[[v20-20-25]]

^<<v20-20-25,25>>^ Pense bem antes de prometer alguma coisa a Deus, pois você poderá se arrepender depois.

[[v20-20-26]]

^<<v20-20-26,26>>^ O rei sábio descobre quem está fazendo o mal e o castiga sem piedade.

[[v20-20-27]]

^<<v20-20-27,27>>^ O Senhor  deu aos seres humanos inteligência e consciência; ninguém pode se esconder de si mesmo.

[[v20-20-28]]

^<<v20-20-28,28>>^ Um governo continuará no poder enquanto for humano, justo e honesto.

[[v20-20-29]]

^<<v20-20-29,29>>^ A beleza dos jovens está na sua força, e o enfeite dos velhos são os seus cabelos brancos.

[[v20-20-30]]

^<<v20-20-30,30>>^ Os castigos curam a maldade da gente e melhoram o nosso caráter.

'''

xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[&#60; Capítulo Anterior] | <<v20-20-0,Topo>> | xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[Próximo Capítulo &#62;]