include::./index.adoc[]

[[v20-10-0]]
=== Provérbios, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-10-1]]

^<<v20-10-1,1>>^ O filho sábio é a alegria do seu pai, mas o filho sem juízo é a tristeza da sua mãe.

[[v20-10-2]]

^<<v20-10-2,2>>^ Aquilo que se consegue com desonestidade não serve de nada, mas a honestidade livra da morte.

[[v20-10-3]]

^<<v20-10-3,3>>^ O Senhor  Deus não deixa que os bons passem fome, mas impede os maus de conseguirem o que tanto querem.

[[v20-10-4]]

^<<v20-10-4,4>>^ O preguiçoso fica pobre, mas quem se esforça no trabalho enriquece.

[[v20-10-5]]

^<<v20-10-5,5>>^ Quem tem juízo colhe no tempo certo, mas quem dorme na época da colheita passa vergonha.

[[v20-10-6]]

^<<v20-10-6,6>>^ Os bons são abençoados. As palavras dos maus escondem a sua violência.

[[v20-10-7]]

^<<v20-10-7,7>>^ Os bons serão lembrados como uma bênção, porém os maus logo serão esquecidos.

[[v20-10-8]]

^<<v20-10-8,8>>^ Quem tem juízo aceita os bons conselhos; quem não tem cuidado com o que diz acaba na desgraça.

[[v20-10-9]]

^<<v20-10-9,9>>^ A pessoa honesta anda em paz e segurança, mas a desonesta será desmascarada.

[[v20-10-10]]

^<<v20-10-10,10>>^ Quem esconde a verdade causa problemas, mas quem critica com franqueza trabalha pela paz.

[[v20-10-11]]

^<<v20-10-11,11>>^ As palavras dos bons são uma fonte de vida, mas as palavras dos maus escondem a sua violência.

[[v20-10-12]]

^<<v20-10-12,12>>^ O ódio provoca brigas, mas o amor perdoa todas as ofensas.

[[v20-10-13]]

^<<v20-10-13,13>>^ A pessoa sábia diz palavras de sabedoria, mas aquela que não tem juízo precisa ser castigada.

[[v20-10-14]]

^<<v20-10-14,14>>^ Os sábios guardam todo o conhecimento que podem, mas o tolo, quando fala, logo traz desgraça.

[[v20-10-15]]

^<<v20-10-15,15>>^ A riqueza protege os ricos, e a pobreza destrói os pobres.

[[v20-10-16]]

^<<v20-10-16,16>>^ O trabalho dos bons produz vida, mas o resultado do pecado é somente mais pecado.

[[v20-10-17]]

^<<v20-10-17,17>>^ Aquele que aceita ser repreendido anda no caminho da vida, mas quem não aceita cai no erro.

[[v20-10-18]]

^<<v20-10-18,18>>^ Com as suas palavras, o mentiroso esconde o seu ódio; quem espalha mexericos não tem juízo.

[[v20-10-19]]

^<<v20-10-19,19>>^ Quanto mais você fala, mais perto está de pecar; se você é sábio, controle a sua língua.

[[v20-10-20]]

^<<v20-10-20,20>>^ As palavras dos bons são como a prata pura; as ideias dos maus não têm valor.

[[v20-10-21]]

^<<v20-10-21,21>>^ As palavras dos bons fazem bem a muita gente, mas a falta de juízo leva à morte.

[[v20-10-22]]

^<<v20-10-22,22>>^ A bênção do Senhor  Deus traz prosperidade, e nenhum esforço pode substituí-la.

[[v20-10-23]]

^<<v20-10-23,23>>^ Para o malvado, fazer o mal é divertimento, mas a pessoa sensata encontra prazer na sabedoria.

[[v20-10-24]]

^<<v20-10-24,24>>^ Quando o mau tem medo de alguma coisa, é isso mesmo o que lhe acontece, mas a pessoa direita consegue o que deseja.

[[v20-10-25]]

^<<v20-10-25,25>>^ Vem a tempestade e acaba com os maus, porém os honestos continuam sempre firmes.

[[v20-10-26]]

^<<v20-10-26,26>>^ Nunca mande um preguiçoso fazer alguma coisa; ele será tão irritante como vinagre nos dentes ou fumaça nos olhos.

[[v20-10-27]]

^<<v20-10-27,27>>^ Quem teme  o Senhor  tem vida longa, porém os maus morrem antes do tempo.

[[v20-10-28]]

^<<v20-10-28,28>>^ A esperança dos bons traz alegria, mas os planos dos maus dão em nada.

[[v20-10-29]]

^<<v20-10-29,29>>^ O Senhor  protege os bons, mas causa a desgraça dos que fazem o mal.

[[v20-10-30]]

^<<v20-10-30,30>>^ As pessoas direitas estarão sempre em segurança, porém os maus não terão onde morar.

[[v20-10-31]]

^<<v20-10-31,31>>^ As pessoas honestas dizem coisas sábias; quem diz coisas perversas recebe um terrível castigo.

[[v20-10-32]]

^<<v20-10-32,32>>^ Os homens direitos sabem dizer coisas agradáveis, porém os maus estão sempre ofendendo os outros.

'''

xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[&#60; Capítulo Anterior] | <<v20-10-0,Topo>> | xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[Próximo Capítulo &#62;]