include::./index.adoc[]

[[v20-21-0]]
=== Provérbios, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-21-1]]

^<<v20-21-1,1>>^ Para o Senhor  Deus, controlar a mente de um rei é tão fácil como dirigir a correnteza de um rio.

[[v20-21-2]]

^<<v20-21-2,2>>^ Se você pensa que tudo o que faz é certo, lembre que o Senhor  julga as suas intenções.

[[v20-21-3]]

^<<v20-21-3,3>>^ Faça o que é direito e justo, pois isso agrada mais a Deus do que lhe oferecer sacrifícios .

[[v20-21-4]]

^<<v20-21-4,4>>^ Os maus são dominados pelo orgulho e pela vaidade, e isso é pecado.

[[v20-21-5]]

^<<v20-21-5,5>>^ Quem planeja com cuidado tem fartura, mas o apressado acaba passando necessidade.

[[v20-21-6]]

^<<v20-21-6,6>>^ A riqueza que é ganha desonestamente acaba logo e é uma armadilha mortal.

[[v20-21-7]]

^<<v20-21-7,7>>^ Os maus são destruídos pela sua própria violência porque se negam a fazer o que é direito.

[[v20-21-8]]

^<<v20-21-8,8>>^ O culpado segue caminhos errados, mas o inocente faz o que é direito.

[[v20-21-9]]

^<<v20-21-9,9>>^ É melhor morar no fundo do quintal do que dentro de casa com uma mulher briguenta.

[[v20-21-10]]

^<<v20-21-10,10>>^ Os maus têm fome do mal; eles não têm pena de ninguém.

[[v20-21-11]]

^<<v20-21-11,11>>^ Quando o zombador é castigado, as pessoas sem experiência aprendem uma lição. Quando se ensina o sábio, o seu conhecimento é aumentado.

[[v20-21-12]]

^<<v20-21-12,12>>^ Deus, que é justo, observa os maus e os faz cair na desgraça.

[[v20-21-13]]

^<<v20-21-13,13>>^ Quem recusar ouvir o grito do pobre também gritará e não será ouvido.

[[v20-21-14]]

^<<v20-21-14,14>>^ Dê um presente em segredo a quem estiver zangado com você, e a raiva dele acabará.

[[v20-21-15]]

^<<v20-21-15,15>>^ Quando se faz justiça, os bons ficam felizes, porém os maus ficam apavorados.

[[v20-21-16]]

^<<v20-21-16,16>>^ Quem se afasta do bom senso está caminhando para a morte.

[[v20-21-17]]

^<<v20-21-17,17>>^ Quem ama os prazeres passará necessidade; quem ama o vinho e a boa comida nunca ficará rico.

[[v20-21-18]]

^<<v20-21-18,18>>^ As pessoas honestas ficam livres da angústia, e os maus sofrem em lugar dos bons.

[[v20-21-19]]

^<<v20-21-19,19>>^ É melhor morar no deserto do que com uma mulher que vive resmungando e se queixando.

[[v20-21-20]]

^<<v20-21-20,20>>^ O homem sensato tem o suficiente para viver na riqueza e na fartura, mas o insensato não, porque gasta tudo o que ganha.

[[v20-21-21]]

^<<v20-21-21,21>>^ Quem é bondoso e direito terá uma vida longa e será tratado com respeito e justiça.

[[v20-21-22]]

^<<v20-21-22,22>>^ Uma pessoa inteligente pode conquistar uma cidade defendida por homens fortes e destruir as muralhas em que eles confiavam.

[[v20-21-23]]

^<<v20-21-23,23>>^ Se você não quer se meter em dificuldades, tome cuidado com o que diz.

[[v20-21-24]]

^<<v20-21-24,24>>^ Chamamos de zombador o homem vaidoso que trata os outros com orgulho e desprezo.

[[v20-21-25]]

^<<v20-21-25,25>>^ O preguiçoso morre desejando muitas coisas porque se nega a trabalhar;

[[v20-21-26]]

^<<v20-21-26,26>>^ ele passa o dia inteiro pensando no que gostaria de ter. Mas a pessoa de caráter tem o que dar e dá com prazer.

[[v20-21-27]]

^<<v20-21-27,27>>^ Deus detesta os sacrifícios que os maus lhe oferecem, especialmente quando oferecem com más intenções.

[[v20-21-28]]

^<<v20-21-28,28>>^ A testemunha falsa será condenada à morte, mas a palavra da pessoa que costuma ouvir bem as coisas será aceita.

[[v20-21-29]]

^<<v20-21-29,29>>^ O homem direito tem confiança em si mesmo, porém o mau só finge que tem.

[[v20-21-30]]

^<<v20-21-30,30>>^ A sabedoria, a inteligência e o entendimento das pessoas não são nada na presença do Senhor .

[[v20-21-31]]

^<<v20-21-31,31>>^ Os homens aprontam os cavalos para a batalha, mas quem dá a vitória é Deus, o Senhor .

'''

xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[&#60; Capítulo Anterior] | <<v20-21-0,Topo>> | xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[Próximo Capítulo &#62;]