include::./index.adoc[]

[[v20-16-0]]
=== Provérbios, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-16-1]]

^<<v20-16-1,1>>^ As pessoas podem fazer seus planos, porém é o Senhor  Deus quem dá a última palavra.

[[v20-16-2]]

^<<v20-16-2,2>>^ Você pode pensar que tudo o que faz é certo, mas o Senhor  julga as suas intenções.

[[v20-16-3]]

^<<v20-16-3,3>>^ Peça a Deus que abençoe os seus planos, e eles darão certo.

[[v20-16-4]]

^<<v20-16-4,4>>^ O Senhor  fez tudo para certos fins, e o fim dos maus é a desgraça.

[[v20-16-5]]

^<<v20-16-5,5>>^ O Senhor  detesta todos os orgulhosos; eles não escaparão do castigo, de jeito nenhum.

[[v20-16-6]]

^<<v20-16-6,6>>^ Quem é bom e fiel recebe o perdão do seu pecado, e quem teme  o Senhor  escapa do mal.

[[v20-16-7]]

^<<v20-16-7,7>>^ Se a nossa maneira de viver agrada a Deus, ele transforma os nossos inimigos em amigos.

[[v20-16-8]]

^<<v20-16-8,8>>^ Ser honesto e ter pouco é melhor do que ter muito lucro com desonestidade.

[[v20-16-9]]

^<<v20-16-9,9>>^ A pessoa faz os seus planos, mas quem dirige a sua vida é Deus, o Senhor .

[[v20-16-10]]

^<<v20-16-10,10>>^ O rei fala com autoridade divina; ele não erra nos seus julgamentos.

[[v20-16-11]]

^<<v20-16-11,11>>^ O Senhor  fez os pesos e as medidas; por isso quer que sejam usados com honestidade.

[[v20-16-12]]

^<<v20-16-12,12>>^ Os reis não toleram o mal porque o que torna forte um governo é a justiça.

[[v20-16-13]]

^<<v20-16-13,13>>^ O rei se alegra em ouvir a verdade e ama os que dizem coisas certas.

[[v20-16-14]]

^<<v20-16-14,14>>^ Quando o rei fica com raiva, há perigo de morte, mas o sábio o acalma.

[[v20-16-15]]

^<<v20-16-15,15>>^ Quando o rei fica contente, há vida; a sua bondade é como a chuva da primavera.

[[v20-16-16]]

^<<v20-16-16,16>>^ É melhor conseguir sabedoria do que ouro; é melhor ter conhecimento do que prata.

[[v20-16-17]]

^<<v20-16-17,17>>^ As pessoas honestas se desviam do caminho do mal; quem tem cuidado com a sua maneira de agir salva a sua vida.

[[v20-16-18]]

^<<v20-16-18,18>>^ O orgulho leva a pessoa à destruição, e a vaidade faz cair na desgraça.

[[v20-16-19]]

^<<v20-16-19,19>>^ É melhor ter um espírito humilde e estar junto com os pobres do que participar das riquezas dos orgulhosos.

[[v20-16-20]]

^<<v20-16-20,20>>^ Quem presta atenção no que lhe ensinam terá sucesso; quem confia no Senhor  será feliz.

[[v20-16-21]]

^<<v20-16-21,21>>^ Quem tem coração sábio é conhecido como uma pessoa compreensiva; quanto mais agradáveis são as suas palavras, mais você consegue convencer os outros.

[[v20-16-22]]

^<<v20-16-22,22>>^ A sabedoria é uma fonte de vida para os sábios, mas os tolos só aprendem tolices.

[[v20-16-23]]

^<<v20-16-23,23>>^ O homem sábio pensa antes de falar; por isso o que ele diz convence mais.

[[v20-16-24]]

^<<v20-16-24,24>>^ As palavras bondosas são como o mel: doces para o paladar e boas para a saúde.

[[v20-16-25]]

^<<v20-16-25,25>>^ Há caminhos que parecem certos, mas podem acabar levando para a morte.

[[v20-16-26]]

^<<v20-16-26,26>>^ O apetite faz o homem trabalhar com vontade, pois ele trabalha para matar a fome.

[[v20-16-27]]

^<<v20-16-27,27>>^ Os maus procuram meios de fazer o mal; até as suas palavras queimam como fogo.

[[v20-16-28]]

^<<v20-16-28,28>>^ Os maus provocam discussões, e quem fala mal dos outros separa os maiores amigos.

[[v20-16-29]]

^<<v20-16-29,29>>^ O homem violento engana os seus amigos e os leva para o mau caminho.

[[v20-16-30]]

^<<v20-16-30,30>>^ Cuidado com quem sorri e pisca maliciosamente; essa pessoa está com más intenções.

[[v20-16-31]]

^<<v20-16-31,31>>^ Uma vida longa é a recompensa das pessoas honestas; os seus cabelos brancos são uma coroa de glória .

[[v20-16-32]]

^<<v20-16-32,32>>^ Vale mais ter paciência do que ser valente; é melhor saber se controlar do que conquistar cidades inteiras.

[[v20-16-33]]

^<<v20-16-33,33>>^ Os homens jogam os dados sagrados para tirar a sorte, mas quem resolve mesmo é Deus, o Senhor .

'''

xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[Próximo Capítulo &#62;]