include::./index.adoc[]

[[v20-9-0]]
=== Provérbios, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-9-1]]

^<<v20-9-1,1>>^ A Sabedoria construiu a sua casa sobre sete colunas.

[[v20-9-2]]

^<<v20-9-2,2>>^ Mandou matar animais para uma festa, preparou vinho e pôs a mesa.

[[v20-9-3]]

^<<v20-9-3,3>>^ Aí mandou as suas empregadas gritarem do lugar mais alto da cidade:

[[v20-9-4]]

^<<v20-9-4,4>>^ "Entre, gente tola!" E disse às pessoas sem juízo:

[[v20-9-5]]

^<<v20-9-5,5>>^ "Venham, comam a minha comida e bebam o vinho que eu preparei.

[[v20-9-6]]

^<<v20-9-6,6>>^ Deixem a companhia dos tolos e vivam. Sigam o caminho do conhecimento."

[[v20-9-7]]

^<<v20-9-7,7>>^ Se você repreender uma pessoa vaidosa, a única coisa que vai conseguir é ser insultado. Se tentar corrigir um homem mau, o que vai conseguir é ser humilhado.

[[v20-9-8]]

^<<v20-9-8,8>>^ Nunca repreenda uma pessoa vaidosa; ela o odiará por isso. Mas, se você corrigir uma pessoa sábia, ela o respeitará.

[[v20-9-9]]

^<<v20-9-9,9>>^ Qualquer coisa que você ensina a uma pessoa sábia torna-a mais sábia ainda. E tudo o que você diz a uma pessoa direita aumenta a sabedoria dela.

[[v20-9-10]]

^<<v20-9-10,10>>^ Para ser sábio, é preciso primeiro temer a Deus , o Senhor . Se você conhece o Deus Santo, então você tem compreensão das coisas.

[[v20-9-11]]

^<<v20-9-11,11>>^ A sabedoria fará com que você viva uma vida mais longa.

[[v20-9-12]]

^<<v20-9-12,12>>^ Se você for sábio, o lucro será seu; se zombar de tudo, você mesmo sofrerá as consequências.

[[v20-9-13]]

^<<v20-9-13,13>>^ A falta de juízo é como uma mulher espalhafatosa, tola e sem-vergonha.

[[v20-9-14]]

^<<v20-9-14,14>>^ Ela senta-se à porta da sua casa ou num banco no lugar mais alto da cidade

[[v20-9-15]]

^<<v20-9-15,15>>^ e grita aos que passam preocupados com os seus negócios:

[[v20-9-16]]

^<<v20-9-16,16>>^ "Entre, gente tola!" E diz às pessoas que não têm juízo:

[[v20-9-17]]

^<<v20-9-17,17>>^ "A água roubada é mais gostosa; o pão furtado é mais saboroso."

[[v20-9-18]]

^<<v20-9-18,18>>^ Mas os convidados dela não sabem que aqueles que vão à sua casa morrem e que os que entraram já estão nas profundezas do mundo dos mortos .

'''

xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[&#60; Capítulo Anterior] | <<v20-9-0,Topo>> | xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[Próximo Capítulo &#62;]