include::./index.adoc[]

[[v20-19-0]]
=== Provérbios, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-19-1]]

^<<v20-19-1,1>>^ É melhor ser pobre e honesto do que mentiroso e tolo.

[[v20-19-2]]

^<<v20-19-2,2>>^ Agir sem pensar não é bom; quem se apressa erra o caminho.

[[v20-19-3]]

^<<v20-19-3,3>>^ A falta de juízo é o que faz a pessoa cair na desgraça; no entanto ela põe a culpa em Deus, o Senhor .

[[v20-19-4]]

^<<v20-19-4,4>>^ Os ricos arranjam muitos amigos, mas o pobre não consegue nem conservar os poucos que tem.

[[v20-19-5]]

^<<v20-19-5,5>>^ A falsa testemunha não poderá escapar do castigo.

[[v20-19-6]]

^<<v20-19-6,6>>^ Todos procuram agradar as pessoas importantes; todos querem ser amigos de quem dá presentes.

[[v20-19-7]]

^<<v20-19-7,7>>^ Se o pobre é desprezado até pelos seus próprios irmãos, não é de admirar que os seus amigos se afastem dele. Ele se cansa de procurar os amigos, mas eles não se importam com ele.

[[v20-19-8]]

^<<v20-19-8,8>>^ Quem procura ter sabedoria ama a sua vida, e quem age com inteligência encontra a felicidade.

[[v20-19-9]]

^<<v20-19-9,9>>^ A falsa testemunha é castigada e certamente será condenada à morte.

[[v20-19-10]]

^<<v20-19-10,10>>^ Não é bom que os tolos vivam no luxo, nem que os escravos governem os príncipes.

[[v20-19-11]]

^<<v20-19-11,11>>^ A pessoa sensata controla o seu gênio, e a sua grandeza é perdoar quem a ofende.

[[v20-19-12]]

^<<v20-19-12,12>>^ A raiva do rei é como o rugido de um leão, mas a sua bondade é como o orvalho sobre as plantas.

[[v20-19-13]]

^<<v20-19-13,13>>^ Um filho sem juízo pode levar o pai à desgraça. Uma esposa que vive resmungando é como água que pinga sem parar.

[[v20-19-14]]

^<<v20-19-14,14>>^ Um homem pode herdar dos seus pais casa e dinheiro, mas só Deus pode dar uma esposa sensata.

[[v20-19-15]]

^<<v20-19-15,15>>^ Quem é preguiçoso e dorminhoco acabará passando fome.

[[v20-19-16]]

^<<v20-19-16,16>>^ Quem obedece às leis  de Deus vive mais; quem despreza os seus ensinamentos morrerá.

[[v20-19-17]]

^<<v20-19-17,17>>^ Ser bondoso com os pobres é emprestar ao Senhor , e ele nos devolve o bem que fazemos.

[[v20-19-18]]

^<<v20-19-18,18>>^ Corrija os seus filhos enquanto eles têm idade para aprender; mas não os mate de pancadas.

[[v20-19-19]]

^<<v20-19-19,19>>^ Deixe que a pessoa de mau gênio sofra as consequências disso, pois, se você a ajudar uma vez, terá de ajudar de novo.

[[v20-19-20]]

^<<v20-19-20,20>>^ Ouça os conselhos e esteja pronto para aprender; assim, um dia você será sábio.

[[v20-19-21]]

^<<v20-19-21,21>>^ As pessoas fazem muitos planos, mas quem decide é Deus, o Senhor .

[[v20-19-22]]

^<<v20-19-22,22>>^ O que se espera de uma pessoa é que seja fiel; é melhor ser pobre do que mentiroso.

[[v20-19-23]]

^<<v20-19-23,23>>^ Quem teme  o Senhor  terá uma vida longa, feliz e tranquila.

[[v20-19-24]]

^<<v20-19-24,24>>^ Existe gente que tem preguiça até de pôr a comida na própria boca.

[[v20-19-25]]

^<<v20-19-25,25>>^ Os orgulhosos devem ser castigados para que as pessoas simples aprendam uma lição de humildade; quem é sábio aprende quando é corrigido.

[[v20-19-26]]

^<<v20-19-26,26>>^ Quem maltrata o seu pai ou toca a sua mãe de casa não tem vergonha e não presta.

[[v20-19-27]]

^<<v20-19-27,27>>^ Filho, se você parar de aprender, logo esquecerá o que sabe.

[[v20-19-28]]

^<<v20-19-28,28>>^ A testemunha de mau caráter zomba da justiça. Os maus têm fome de fazer o mal.

[[v20-19-29]]

^<<v20-19-29,29>>^ Mais cedo ou mais tarde quem zomba dos outros será julgado, e quem não tem juízo será castigado.

'''

xref:020-proverbios/020-proverbios-018.adoc#v20-18-0[&#60; Capítulo Anterior] | <<v20-19-0,Topo>> | xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[Próximo Capítulo &#62;]