include::./index.adoc[]

[[v20-13-0]]
=== Provérbios, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-13-1]]

^<<v20-13-1,1>>^ O filho sábio aceita os ensinamentos do pai, mas o que zomba de tudo nunca reconhece que está errado.

[[v20-13-2]]

^<<v20-13-2,2>>^ Os bons serão recompensados pelo que dizem; os traiçoeiros só desejam a violência.

[[v20-13-3]]

^<<v20-13-3,3>>^ Quem toma cuidado com o que diz está protegendo a sua própria vida, mas quem fala demais destrói a si mesmo.

[[v20-13-4]]

^<<v20-13-4,4>>^ Por mais que o preguiçoso deseje alguma coisa, ele não conseguirá, mas a pessoa esforçada consegue o que deseja.

[[v20-13-5]]

^<<v20-13-5,5>>^ Os homens honestos odeiam a mentira, porém os maus dizem coisas indecentes e vergonhosas.

[[v20-13-6]]

^<<v20-13-6,6>>^ A justiça protege os inocentes, mas a maldade do pecador o leva à desgraça.

[[v20-13-7]]

^<<v20-13-7,7>>^ Algumas pessoas não têm nada, mas fazem de conta que são ricas; outras têm muito dinheiro, mas fingem que são pobres.

[[v20-13-8]]

^<<v20-13-8,8>>^ O rico tem de usar o seu dinheiro para pagar o resgate por sua vida, mas ninguém ameaça o pobre.

[[v20-13-9]]

^<<v20-13-9,9>>^ Os homens corretos são como uma luz brilhante, porém os maus são como uma vela que está se apagando.

[[v20-13-10]]

^<<v20-13-10,10>>^ O orgulho só traz brigas; é mais sábio pedir conselhos.

[[v20-13-11]]

^<<v20-13-11,11>>^ A riqueza que é fácil de ganhar é fácil de perder; quanto mais difícil for para ganhar, mais você terá.

[[v20-13-12]]

^<<v20-13-12,12>>^ A esperança adiada faz o coração ficar doente, mas o desejo realizado enche o coração de vida.

[[v20-13-13]]

^<<v20-13-13,13>>^ Quem despreza os bons conselhos acabará mal, mas quem os segue será recompensado.

[[v20-13-14]]

^<<v20-13-14,14>>^ Os ensinamentos das pessoas sábias são uma fonte de vida; eles ajudam a evitar as armadilhas da morte.

[[v20-13-15]]

^<<v20-13-15,15>>^ Quem tem juízo ganha o respeito de todos, mas quem não merece confiança está caminhando para a desgraça.

[[v20-13-16]]

^<<v20-13-16,16>>^ O homem sensato sempre pensa antes de agir, mas o tolo anuncia a sua ignorância.

[[v20-13-17]]

^<<v20-13-17,17>>^ O mensageiro perverso causa a desgraça, mas o de confiança traz a paz.

[[v20-13-18]]

^<<v20-13-18,18>>^ Quem rejeita a correção acabará pobre e na desgraça, mas quem aceita a repreensão é respeitado.

[[v20-13-19]]

^<<v20-13-19,19>>^ Como é bom conseguir o que a gente deseja! Os que não têm juízo não querem abandonar o mal.

[[v20-13-20]]

^<<v20-13-20,20>>^ Quem anda com os sábios será sábio, mas quem anda com os tolos acabará mal.

[[v20-13-21]]

^<<v20-13-21,21>>^ A desgraça persegue os pecadores por toda parte, porém as pessoas corretas serão recompensadas com a prosperidade.

[[v20-13-22]]

^<<v20-13-22,22>>^ O homem bom terá uma herança para deixar para os seus netos, mas a riqueza dos pecadores ficará para as pessoas honestas.

[[v20-13-23]]

^<<v20-13-23,23>>^ As terras dos pobres produzem boas colheitas, mas os homens desonestos não deixam que elas sejam aproveitadas.

[[v20-13-24]]

^<<v20-13-24,24>>^ Quem não castiga o filho não o ama. Quem ama o filho castiga-o enquanto é tempo.

[[v20-13-25]]

^<<v20-13-25,25>>^ As pessoas direitas têm bastante para comer, porém os maus passam fome.

'''

xref:020-proverbios/020-proverbios-012.adoc#v20-12-0[&#60; Capítulo Anterior] | <<v20-13-0,Topo>> | xref:020-proverbios/020-proverbios-014.adoc#v20-14-0[Próximo Capítulo &#62;]