include::./index.adoc[]

[[v20-22-0]]
=== Provérbios, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-22-1]]

^<<v20-22-1,1>>^ O bom nome vale mais do que muita riqueza; ser estimado é melhor do que ter prata e ouro.

[[v20-22-2]]

^<<v20-22-2,2>>^ Não existe diferença entre o rico e o pobre porque foi o Senhor  Deus quem fez os dois.

[[v20-22-3]]

^<<v20-22-3,3>>^ A pessoa sensata vê o perigo e se esconde; mas a insensata vai em frente e acaba mal.

[[v20-22-4]]

^<<v20-22-4,4>>^ Quem teme  o Senhor  e é humilde consegue riqueza, prestígio e vida longa.

[[v20-22-5]]

^<<v20-22-5,5>>^ No caminho dos maus existem armadilhas e dificuldades; quem dá valor à vida se afasta deles.

[[v20-22-6]]

^<<v20-22-6,6>>^ Eduque a criança no caminho em que deve andar, e até o fim da vida não se desviará dele.

[[v20-22-7]]

^<<v20-22-7,7>>^ Os ricos mandam nos pobres, e quem toma emprestado é escravo de quem empresta.

[[v20-22-8]]

^<<v20-22-8,8>>^ Quem semeia a maldade colhe a desgraça e será castigado pelo seu próprio ódio.

[[v20-22-9]]

^<<v20-22-9,9>>^ Quem é bondoso será abençoado porque reparte a sua comida com os pobres.

[[v20-22-10]]

^<<v20-22-10,10>>^ Mande embora a pessoa orgulhosa, e acabarão os desentendimentos, as discussões e os xingamentos.

[[v20-22-11]]

^<<v20-22-11,11>>^ Quem ama a sinceridade e sabe falar bem terá a amizade do rei.

[[v20-22-12]]

^<<v20-22-12,12>>^ O Senhor  Deus está alerta para defender a verdade e atrapalhar os planos dos mentirosos.

[[v20-22-13]]

^<<v20-22-13,13>>^ O preguiçoso fica em casa e diz: "Se eu sair, o leão me pega."

[[v20-22-14]]

^<<v20-22-14,14>>^ O adultério é uma armadilha onde caem as pessoas que o Senhor  detesta.

[[v20-22-15]]

^<<v20-22-15,15>>^ É natural que as crianças façam tolices, mas a correção as ensinará a se comportarem.

[[v20-22-16]]

^<<v20-22-16,16>>^ Quem enriquece à custa dos pobres ou dando presentes aos ricos acabará ficando pobre.

[[v20-22-17]]

^<<v20-22-17,17>>^ Preste atenção, e eu lhe ensinarei o que os sábios disseram. Estude os seus ensinamentos,

[[v20-22-18]]

^<<v20-22-18,18>>^ e será um prazer para você lembrar deles e recitá-los.

[[v20-22-19]]

^<<v20-22-19,19>>^ Vou lhe ensinar agora estes provérbios para que você ponha a sua confiança em Deus.

[[v20-22-20]]

^<<v20-22-20,20>>^ Tomei nota de trinta provérbios para você. Eles contêm conhecimentos e bons conselhos,

[[v20-22-21]]

^<<v20-22-21,21>>^ que o ajudarão a saber o que é certo e direito. E assim, quando lhe fizerem perguntas, você saberá dar a resposta certa.

[[v20-22-22]]

^<<v20-22-22,22>>^ Não tire vantagem do pobre só porque ele é pobre, nem se aproveite daqueles que não tiverem quem os defenda no tribunal.

[[v20-22-23]]

^<<v20-22-23,23>>^ Pois o Senhor  defenderá a causa deles e ameaçará a vida de quem os ameaçar.

[[v20-22-24]]

^<<v20-22-24,24>>^ Não faça amizade com pessoas grosseiras ou violentas;

[[v20-22-25]]

^<<v20-22-25,25>>^ você poderá pegar os seus maus costumes e depois não conseguirá livrar-se deles.

[[v20-22-26]]

^<<v20-22-26,26>>^ Não aceite ser fiador de ninguém

[[v20-22-27]]

^<<v20-22-27,27>>^ porque, se você não puder pagar a dívida, levarão embora até a sua cama.

[[v20-22-28]]

^<<v20-22-28,28>>^ Não mude de lugar os marcos de divisa de terras que os seus antepassados colocaram.

[[v20-22-29]]

^<<v20-22-29,29>>^ Você conhece alguém que faz bem o seu trabalho? Saiba que ele é melhor do que a maioria e merece estar na companhia de reis.

'''

xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[&#60; Capítulo Anterior] | <<v20-22-0,Topo>> | xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[Próximo Capítulo &#62;]