include::./index.adoc[]

[[v20-12-0]]
=== Provérbios, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-12-1]]

^<<v20-12-1,1>>^ Aquele que quer aprender gosta que lhe digam quando está errado; só o tolo não gosta de ser corrigido.

[[v20-12-2]]

^<<v20-12-2,2>>^ O Senhor  Deus abençoa os bons, mas condena os que planejam o mal.

[[v20-12-3]]

^<<v20-12-3,3>>^ Quem pratica a maldade não tem segurança, mas quem é honesto não será abalado.

[[v20-12-4]]

^<<v20-12-4,4>>^ A boa esposa é o orgulho do marido, mas a esposa que traz vergonha ao marido é como câncer nos ossos dele.

[[v20-12-5]]

^<<v20-12-5,5>>^ Quem é honesto trata todos com sinceridade, mas quem é mau vive enganando os outros.

[[v20-12-6]]

^<<v20-12-6,6>>^ As palavras dos maus são uma armadilha mortal, mas as palavras das pessoas corretas salvam os que estão em perigo.

[[v20-12-7]]

^<<v20-12-7,7>>^ Os maus serão destruídos e não deixarão descendentes, mas a família do homem correto permanecerá.

[[v20-12-8]]

^<<v20-12-8,8>>^ Quem tem compreensão recebe elogios, mas quem tem coração perverso é desprezado.

[[v20-12-9]]

^<<v20-12-9,9>>^ É melhor ser uma pessoa comum e trabalhar para viver do que bancar o rico e passar fome.

[[v20-12-10]]

^<<v20-12-10,10>>^ Os bons cuidam bem dos seus animais, porém o coração dos maus é cruel.

[[v20-12-11]]

^<<v20-12-11,11>>^ Quem cultiva a sua terra tem comida com fartura, mas quem gasta o tempo com coisas sem importância não tem juízo.

[[v20-12-12]]

^<<v20-12-12,12>>^ Os perversos querem viver daquilo que os maus conseguem, mas os bons continuam firmes fazendo o bem.

[[v20-12-13]]

^<<v20-12-13,13>>^ Os maus são apanhados na armadilha das suas próprias palavras, mas os homens direitos conseguem sair das dificuldades.

[[v20-12-14]]

^<<v20-12-14,14>>^ Você será recompensado pelas coisas boas que disser e receberá de volta aquilo que fizer.

[[v20-12-15]]

^<<v20-12-15,15>>^ O tolo pensa que sempre está certo, mas os sábios aceitam conselhos.

[[v20-12-16]]

^<<v20-12-16,16>>^ Quando o tolo é ofendido, logo todos ficam sabendo, mas quem é prudente faz de conta que não foi insultado.

[[v20-12-17]]

^<<v20-12-17,17>>^ Quando a verdade é dita, a justiça é feita; mas a mentira produz a injustiça.

[[v20-12-18]]

^<<v20-12-18,18>>^ As palavras do falador ferem como pontas de espada, mas as palavras do sábio podem curar.

[[v20-12-19]]

^<<v20-12-19,19>>^ A mentira tem vida curta, mas a verdade vive para sempre.

[[v20-12-20]]

^<<v20-12-20,20>>^ Aqueles que planejam o mal acabarão mal, porém os que trabalham para o bem dos outros encontrarão a felicidade.

[[v20-12-21]]

^<<v20-12-21,21>>^ Nada de ruim acontece com os homens honestos, porém os maus só encontram dificuldades.

[[v20-12-22]]

^<<v20-12-22,22>>^ O Senhor  Deus detesta os mentirosos, porém ama os que dizem a verdade.

[[v20-12-23]]

^<<v20-12-23,23>>^ A pessoa prudente esconde a sua sabedoria, mas os tolos anunciam a sua própria ignorância.

[[v20-12-24]]

^<<v20-12-24,24>>^ O homem esforçado mandará nos outros, mas o preguiçoso se tornará escravo.

[[v20-12-25]]

^<<v20-12-25,25>>^ As preocupações roubam a felicidade da gente, mas as palavras amáveis nos alegram.

[[v20-12-26]]

^<<v20-12-26,26>>^ Quem é direito serve de guia para o seu companheiro, porém os maus se perdem pelo caminho.

[[v20-12-27]]

^<<v20-12-27,27>>^ O preguiçoso não consegue o que deseja, mas o homem trabalhador ficará rico.

[[v20-12-28]]

^<<v20-12-28,28>>^ A honradez é o caminho para a vida, mas a falta de juízo é a estrada para a morte.

'''

xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[&#60; Capítulo Anterior] | <<v20-12-0,Topo>> | xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[Próximo Capítulo &#62;]