include::./index.adoc[]

[[v20-8-0]]
=== Provérbios, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v20-8-1]]

^<<v20-8-1,1>>^ Escutem! A Sabedoria está gritando: a Compreensão está chamando em voz alta.

[[v20-8-2]]

^<<v20-8-2,2>>^ A Sabedoria está no alto dos morros, na beira da estrada e nas encruzilhadas dos caminhos.

[[v20-8-3]]

^<<v20-8-3,3>>^ Está na entrada da cidade, perto dos portões, gritando:

[[v20-8-4]]

^<<v20-8-4,4>>^ "Eu estou falando com todos vocês e faço um pedido a todos os moradores da terra.

[[v20-8-5]]

^<<v20-8-5,5>>^ Você é jovem e sem experiência? Aprenda a ser prudente. Você é tolo? Aprenda a ter juízo.

[[v20-8-6]]

^<<v20-8-6,6>>^ Escutem, pois digo coisas importantes; tudo o que eu digo é certo.

[[v20-8-7]]

^<<v20-8-7,7>>^ O que eu digo é verdade, pois odeio a mentira.

[[v20-8-8]]

^<<v20-8-8,8>>^ Tudo o que afirmo é verdadeiro; nada do que falo é enganoso ou falso.

[[v20-8-9]]

^<<v20-8-9,9>>^ Para a pessoa que tem compreensão, tudo é claro; tudo é fácil de entender para quem é bem-informado.

[[v20-8-10]]

^<<v20-8-10,10>>^ Aceite os meus ensinamentos em vez de prata e o meu conhecimento, em lugar de ouro puro.

[[v20-8-11]]

^<<v20-8-11,11>>^ "Eu sou a Sabedoria; sou mais preciosa do que as joias. Tudo o que você deseja não pode se comparar comigo.

[[v20-8-12]]

^<<v20-8-12,12>>^ Eu sou a Sabedoria; tenho compreensão, conhecimento e juízo.

[[v20-8-13]]

^<<v20-8-13,13>>^ Temer  o Senhor  Deus é odiar o mal. Eu odeio o orgulho e a falta de modéstia, os maus caminhos e as palavras falsas.

[[v20-8-14]]

^<<v20-8-14,14>>^ Faço planos e os ponho em prática; tenho inteligência e sou forte.

[[v20-8-15]]

^<<v20-8-15,15>>^ Eu ajudo os reis a governarem e os governantes a fazerem boas leis .

[[v20-8-16]]

^<<v20-8-16,16>>^ Os governadores governam com a minha ajuda, e também todas as autoridades e pessoas importantes da terra.

[[v20-8-17]]

^<<v20-8-17,17>>^ "Eu amo aquele que me ama; e quem me procura acha.

[[v20-8-18]]

^<<v20-8-18,18>>^ Tenho riquezas e honras, prosperidade e justiça.

[[v20-8-19]]

^<<v20-8-19,19>>^ O que eu ofereço vale mais do que o ouro fino e é melhor do que a prata mais pura.

[[v20-8-20]]

^<<v20-8-20,20>>^ Eu ando no caminho da honestidade e sigo os passos da justiça,

[[v20-8-21]]

^<<v20-8-21,21>>^ dando riqueza aos que me amam e enchendo as suas casas de tesouros.

[[v20-8-22]]

^<<v20-8-22,22>>^ "O Senhor  Deus me criou antes de tudo, antes das suas obras mais antigas.

[[v20-8-23]]

^<<v20-8-23,23>>^ Eu fui formada há muito tempo, no começo, antes do princípio do mundo.

[[v20-8-24]]

^<<v20-8-24,24>>^ Nasci antes dos oceanos quando ainda não havia fontes de água.

[[v20-8-25]]

^<<v20-8-25,25>>^ Nasci antes das montanhas, antes de os morros serem colocados nos seus lugares,

[[v20-8-26]]

^<<v20-8-26,26>>^ antes de Deus ter feito a terra e os seus campos ou mesmo o primeiro punhado de terra.

[[v20-8-27]]

^<<v20-8-27,27>>^ Eu estava lá quando ele colocou o céu no seu lugar e estendeu o horizonte sobre o oceano.

[[v20-8-28]]

^<<v20-8-28,28>>^ Estava lá quando ele pôs as nuvens no céu e abriu as fontes do mar,

[[v20-8-29]]

^<<v20-8-29,29>>^ e quando ordenou às águas que não subissem além do que ele havia permitido. Eu estava lá quando ele colocou os alicerces da Terra.

[[v20-8-30]]

^<<v20-8-30,30>>^ Estava ao seu lado como arquiteta e era a sua fonte diária de alegria, sempre feliz na sua presença —

[[v20-8-31]]

^<<v20-8-31,31>>^ feliz com o mundo e contente com a raça humana.

[[v20-8-32]]

^<<v20-8-32,32>>^ "Agora, moços, escutem! Façam o que eu digo e serão felizes.

[[v20-8-33]]

^<<v20-8-33,33>>^ Aprendam o que é ensinado a vocês. Sejam sábios; não abandonem esses ensinamentos.

[[v20-8-34]]

^<<v20-8-34,34>>^ Aquele que me ouve será feliz: aquele que fica todos os dias na minha porta, esperando na entrada da minha casa.

[[v20-8-35]]

^<<v20-8-35,35>>^ Pois quem me encontra encontra a vida, e o Senhor  Deus ficará contente com ele.

[[v20-8-36]]

^<<v20-8-36,36>>^ Mas quem não me encontra prejudica-se a si mesmo; todos os que me odeiam amam a morte."

'''

xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[Próximo Capítulo &#62;]