include::./index.adoc[]

[[v40-12-0]]
=== Mateus, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-12-1]]

^<<v40-12-1,1>>^ Poucos dias depois, num sábado, Jesus estava atravessando uma plantação de trigo. Os seus discípulos estavam com fome e por isso começaram a colher espigas e a comer os grãos de trigo.

[[v40-12-2]]

^<<v40-12-2,2>>^ Quando alguns fariseus  viram aquilo, disseram a Jesus: — Veja! Os seus discípulos estão fazendo uma coisa que a nossa Lei  proíbe fazer no sábado!

[[v40-12-3]]

^<<v40-12-3,3>>^ Então Jesus respondeu: — Vocês não leram o que Davi fez, quando ele e os seus companheiros estavam com fome?

[[v40-12-4]]

^<<v40-12-4,4>>^ Davi entrou na casa de Deus, e ele e os seus companheiros comeram os pães oferecidos a Deus, embora isso fosse contra a Lei. Pois somente os sacerdotes tinham o direito de comer esses pães.

[[v40-12-5]]

^<<v40-12-5,5>>^ Ou vocês não leram na Lei de Moisés que, nos sábados, os sacerdotes quebram a Lei, no Templo, e não são culpados?

[[v40-12-6]]

^<<v40-12-6,6>>^ Eu afirmo a vocês que o que está aqui é mais importante do que o Templo.

[[v40-12-7]]

^<<v40-12-7,7>>^ Se vocês soubessem o que as Escrituras Sagradas  querem dizer quando afirmam: "Eu quero que as pessoas sejam bondosas e não que me ofereçam sacrifícios  de animais", vocês não condenariam os que não têm culpa.

[[v40-12-8]]

^<<v40-12-8,8>>^ Pois o Filho do Homem  tem autoridade sobre o sábado.

[[v40-12-9]]

^<<v40-12-9,9>>^ Jesus saiu dali e foi para uma sinagoga .

[[v40-12-10]]

^<<v40-12-10,10>>^ Estava ali um homem que tinha uma das mãos aleijada. Então algumas pessoas que queriam acusar Jesus de desobedecer à Lei  lhe perguntaram: — É contra a nossa Lei curar no sábado?

[[v40-12-11]]

^<<v40-12-11,11>>^ Jesus respondeu: — Se um de vocês tiver uma ovelha, e no sábado ela cair num buraco, será que ele não vai fazer tudo para tirá-la dali?

[[v40-12-12]]

^<<v40-12-12,12>>^ Pois uma pessoa vale muito mais do que uma ovelha. Portanto, a nossa Lei permite ajudar os outros no sábado.

[[v40-12-13]]

^<<v40-12-13,13>>^ E disse para o homem: — Estenda a mão! Ele estendeu, e ela sarou e ficou igual à outra.

[[v40-12-14]]

^<<v40-12-14,14>>^ Então os fariseus  que estavam ali saíram e começaram a fazer planos para matar Jesus.

[[v40-12-15]]

^<<v40-12-15,15>>^ Quando Jesus soube disso, foi embora dali, e muita gente o seguiu. Ele curou todos os que estavam doentes

[[v40-12-16]]

^<<v40-12-16,16>>^ e mandou que não contassem nada a ninguém a respeito dele.

[[v40-12-17]]

^<<v40-12-17,17>>^ Isso aconteceu para se cumprir o que o profeta  Isaías tinha dito:

[[v40-12-18]]

^<<v40-12-18,18>>^ "Disse Deus: Aqui está o meu servo que escolhi, aquele que amo e que dá muita alegria ao meu coração. Eu porei nele o meu Espírito, e ele anunciará o meu julgamento a todos os povos.

[[v40-12-19]]

^<<v40-12-19,19>>^ Não discutirá, nem gritará, nem fará discursos nas ruas.

[[v40-12-20]]

^<<v40-12-20,20>>^ Não esmagará o galho que está quebrado, nem apagará a luz que já está fraca. Ele agirá assim até que a causa da justiça seja vitoriosa.

[[v40-12-21]]

^<<v40-12-21,21>>^ E todos os povos vão pôr nele a sua esperança."

[[v40-12-22]]

^<<v40-12-22,22>>^ Então levaram a Jesus um homem que era cego e mudo porque estava dominado por um demônio. Jesus o curou, e ele começou a ver e a falar.

[[v40-12-23]]

^<<v40-12-23,23>>^ A multidão ficou admirada e perguntava: — Será que este homem é o Filho de Davi ?

[[v40-12-24]]

^<<v40-12-24,24>>^ Alguns fariseus  ouviram isso e responderam: — É Belzebu , o chefe dos demônios, quem dá poder a este homem para expulsar demônios.

[[v40-12-25]]

^<<v40-12-25,25>>^ Mas Jesus conhecia os pensamentos deles e disse: — O país que se divide em grupos que lutam entre si certamente será destruído. E a cidade ou a família que se divide em grupos que lutam entre si também será destruída.

[[v40-12-26]]

^<<v40-12-26,26>>^ Assim, se no reino de Satanás um grupo está combatendo contra outro, isso quer dizer que esse reino já está dividido e logo vai desaparecer.

[[v40-12-27]]

^<<v40-12-27,27>>^ Vocês dizem que eu expulso demônios porque Belzebu me dá poder para fazer isso. Mas, se é assim, quem dá aos seguidores de vocês o poder para expulsar demônios? Assim, os seus próprios seguidores provam que vocês estão completamente enganados.

[[v40-12-28]]

^<<v40-12-28,28>>^ Na verdade é pelo poder de Deus que eu expulso demônios, e isso prova que o Reino de Deus  já chegou até vocês.

[[v40-12-29]]

^<<v40-12-29,29>>^ — Ninguém pode entrar na casa de um homem forte e roubar os seus bens, sem primeiro amarrá-lo. Somente assim essa pessoa poderá levar as coisas que ele tem em casa.

[[v40-12-30]]

^<<v40-12-30,30>>^ — Quem não é a meu favor é contra mim; e quem não me ajuda a ajuntar está espalhando.

[[v40-12-31]]

^<<v40-12-31,31>>^ Por isso eu afirmo a vocês que as pessoas serão perdoadas por qualquer pecado ou blasfêmia  que disserem contra Deus. Mas quem blasfemar contra o Espírito Santo não será perdoado.

[[v40-12-32]]

^<<v40-12-32,32>>^ Se alguém disser alguma coisa contra o Filho do Homem , será perdoado; mas quem falar contra o Espírito Santo não será perdoado, nem agora nem no futuro.

[[v40-12-33]]

^<<v40-12-33,33>>^ — Vocês só poderão ter frutas boas se tiverem uma árvore boa. Mas, se tiverem uma árvore que não presta, vocês terão frutas que não prestam. Porque é pela qualidade das frutas que sabemos se uma árvore é boa ou não presta.

[[v40-12-34]]

^<<v40-12-34,34>>^ Ninhada de cobras venenosas! Como é que vocês podem dizer coisas boas se são maus? Pois a boca fala do que o coração está cheio.

[[v40-12-35]]

^<<v40-12-35,35>>^ A pessoa boa tira o bem do seu depósito de coisas boas, e a pessoa má tira o mal do seu depósito de coisas más.

[[v40-12-36]]

^<<v40-12-36,36>>^ — Eu afirmo a vocês que, no Dia do Juízo, cada pessoa vai prestar contas de toda palavra inútil que falou.

[[v40-12-37]]

^<<v40-12-37,37>>^ Porque as suas palavras vão servir para julgar se você é inocente ou culpado.

[[v40-12-38]]

^<<v40-12-38,38>>^ Então alguns mestres  da Lei e alguns fariseus  disseram a Jesus: — Mestre, queremos ver o senhor fazer um milagre.

[[v40-12-39]]

^<<v40-12-39,39>>^ Jesus respondeu: — Como as pessoas de hoje são más e sem fé! Vocês estão me pedindo que faça um milagre, mas o milagre do profeta  Jonas é o único sinal que lhes será dado.

[[v40-12-40]]

^<<v40-12-40,40>>^ Porque assim como Jonas ficou três dias e três noites dentro de um grande peixe, assim também o Filho do Homem  ficará três dias e três noites no fundo da terra.

[[v40-12-41]]

^<<v40-12-41,41>>^ No Dia do Juízo o povo de Nínive vai se levantar e acusar vocês, pois eles se arrependeram dos seus pecados quando ouviram a pregação de Jonas. E eu afirmo que o que está aqui é mais importante do que Jonas.

[[v40-12-42]]

^<<v40-12-42,42>>^ No Dia do Juízo a Rainha de Sabá vai se levantar e acusar vocês, pois ela veio de muito longe para ouvir os sábios ensinamentos de Salomão. E eu afirmo que o que está aqui é mais importante do que Salomão.

[[v40-12-43]]

^<<v40-12-43,43>>^ Jesus continuou: — Quando um espírito mau sai de alguém, anda por lugares sem água, procurando onde descansar, mas não encontra.

[[v40-12-44]]

^<<v40-12-44,44>>^ Então diz: "Vou voltar para a minha casa, de onde saí." Aí volta e encontra a casa vazia, limpa e arrumada.

[[v40-12-45]]

^<<v40-12-45,45>>^ Depois sai, vai buscar outros sete espíritos piores ainda, e todos ficam morando ali. Assim a situação daquela pessoa fica pior do que antes. E isso também acontecerá com esta gente má de hoje.

[[v40-12-46]]

^<<v40-12-46,46>>^ Quando Jesus ainda estava falando ao povo, a mãe e os irmãos dele chegaram. Ficaram do lado de fora e pediram para falar com ele.

[[v40-12-47]]

^<<v40-12-47,47>>^ Então alguém disse a Jesus: — Escute! A sua mãe e os seus irmãos estão lá fora e querem falar com o senhor.

[[v40-12-48]]

^<<v40-12-48,48>>^ Jesus perguntou: — Quem é a minha mãe? E quem são os meus irmãos?

[[v40-12-49]]

^<<v40-12-49,49>>^ Então apontou para os seus discípulos e disse: — Vejam! Aqui estão a minha mãe e os meus irmãos.

[[v40-12-50]]

^<<v40-12-50,50>>^ Pois quem faz a vontade do meu Pai, que está no céu, é meu irmão, minha irmã e minha mãe.

'''

xref:040-mateus/040-mateus-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-mateus/040-mateus-013.adoc#v40-13-0[Próximo Capítulo &#62;]