include::./index.adoc[]

[[v40-6-0]]
=== Mateus, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-6-1]]

^<<v40-6-1,1>>^ — Tenham o cuidado de não praticarem os seus deveres religiosos em público a fim de serem vistos pelos outros. Se vocês agirem assim, não receberão nenhuma recompensa do Pai de vocês, que está no céu.

[[v40-6-2]]

^<<v40-6-2,2>>^ — Quando você der alguma coisa a uma pessoa necessitada, não fique contando o que fez, como os hipócritas fazem nas sinagogas  e nas ruas. Eles fazem isso para serem elogiados pelos outros. Eu afirmo a vocês que isto é verdade: eles já receberam a sua recompensa.

[[v40-6-3]]

^<<v40-6-3,3>>^ Mas você, quando ajudar alguma pessoa necessitada, faça isso de tal modo que nem mesmo o seu amigo mais íntimo fique sabendo do que você fez.

[[v40-6-4]]

^<<v40-6-4,4>>^ Isso deve ficar em segredo; e o seu Pai, que vê o que você faz em segredo, lhe dará a recompensa.

[[v40-6-5]]

^<<v40-6-5,5>>^ — Quando vocês orarem, não sejam como os hipócritas. Eles gostam de orar de pé nas sinagogas  e nas esquinas das ruas para serem vistos pelos outros. Eu afirmo a vocês que isto é verdade: eles já receberam a sua recompensa.

[[v40-6-6]]

^<<v40-6-6,6>>^ Mas você, quando orar, vá para o seu quarto, feche a porta e ore ao seu Pai, que não pode ser visto. E o seu Pai, que vê o que você faz em segredo, lhe dará a recompensa.

[[v40-6-7]]

^<<v40-6-7,7>>^ — Nas suas orações, não fiquem repetindo o que vocês já disseram, como fazem os pagãos. Eles pensam que Deus os ouvirá porque fazem orações compridas.

[[v40-6-8]]

^<<v40-6-8,8>>^ Não sejam como eles, pois, antes de vocês pedirem, o Pai de vocês já sabe o que vocês precisam.

[[v40-6-9]]

^<<v40-6-9,9>>^ Portanto, orem assim: "Pai nosso, que estás no céu, que todos reconheçam que o teu nome é santo.

[[v40-6-10]]

^<<v40-6-10,10>>^ Venha o teu Reino . Que a tua vontade seja feita aqui na terra como é feita no céu!

[[v40-6-11]]

^<<v40-6-11,11>>^ Dá-nos hoje o alimento que precisamos.

[[v40-6-12]]

^<<v40-6-12,12>>^ Perdoa as nossas ofensas como também nós perdoamos as pessoas que nos ofenderam.

[[v40-6-13]]

^<<v40-6-13,13>>^ E não deixes que sejamos tentados, mas livra-nos do mal. [Pois teu é o Reino, o poder e a glória , para sempre. Amém !]"

[[v40-6-14]]

^<<v40-6-14,14>>^ — Porque, se vocês perdoarem as pessoas que ofenderem vocês, o Pai de vocês, que está no céu, também perdoará vocês.

[[v40-6-15]]

^<<v40-6-15,15>>^ Mas, se não perdoarem essas pessoas, o Pai de vocês também não perdoará as ofensas de vocês.

[[v40-6-16]]

^<<v40-6-16,16>>^ — Quando vocês jejuarem, não façam uma cara triste como fazem os hipócritas, pois eles fazem isso para todos saberem que eles estão jejuando. Eu afirmo a vocês que isto é verdade: eles já receberam a sua recompensa.

[[v40-6-17]]

^<<v40-6-17,17>>^ Mas você, quando jejuar, lave o rosto e penteie o cabelo

[[v40-6-18]]

^<<v40-6-18,18>>^ para os outros não saberem que você está jejuando. E somente o seu Pai, que não pode ser visto, saberá que você está jejuando. E o seu Pai, que vê o que você faz em segredo, lhe dará a recompensa.

[[v40-6-19]]

^<<v40-6-19,19>>^ — Não ajuntem riquezas aqui na terra, onde as traças e a ferrugem destroem, e onde os ladrões arrombam e roubam.

[[v40-6-20]]

^<<v40-6-20,20>>^ Pelo contrário, ajuntem riquezas no céu, onde as traças e a ferrugem não podem destruí-las, e os ladrões não podem arrombar e roubá-las.

[[v40-6-21]]

^<<v40-6-21,21>>^ Pois onde estiverem as suas riquezas, aí estará o coração de vocês.

[[v40-6-22]]

^<<v40-6-22,22>>^ — Os olhos são como uma luz para o corpo: quando os olhos de vocês são bons, todo o seu corpo fica cheio de luz.

[[v40-6-23]]

^<<v40-6-23,23>>^ Porém, se os seus olhos forem maus, o seu corpo ficará cheio de escuridão. Assim, se a luz que está em você virar escuridão, como será terrível essa escuridão!

[[v40-6-24]]

^<<v40-6-24,24>>^ — Um escravo não pode servir a dois donos ao mesmo tempo, pois vai rejeitar um e preferir o outro; ou será fiel a um e desprezará o outro. Vocês não podem servir a Deus e também servir ao dinheiro.

[[v40-6-25]]

^<<v40-6-25,25>>^ — Por isso eu digo a vocês: não se preocupem com a comida e com a bebida que precisam para viver nem com a roupa que precisam para se vestir. Afinal, será que a vida não é mais importante do que a comida? E será que o corpo não é mais importante do que as roupas?

[[v40-6-26]]

^<<v40-6-26,26>>^ Vejam os passarinhos que voam pelo céu: eles não semeiam, não colhem, nem guardam comida em depósitos. No entanto, o Pai de vocês, que está no céu, dá de comer a eles. Será que vocês não valem muito mais do que os passarinhos?

[[v40-6-27]]

^<<v40-6-27,27>>^ E nenhum de vocês pode encompridar a sua vida, por mais que se preocupe com isso.

[[v40-6-28]]

^<<v40-6-28,28>>^ — E por que vocês se preocupam com roupas? Vejam como crescem as flores do campo: elas não trabalham, nem fazem roupas para si mesmas.

[[v40-6-29]]

^<<v40-6-29,29>>^ Mas eu afirmo a vocês que nem mesmo Salomão, sendo tão rico, usava roupas tão bonitas como essas flores.

[[v40-6-30]]

^<<v40-6-30,30>>^ É Deus quem veste a erva do campo, que hoje dá flor e amanhã desaparece, queimada no forno. Então é claro que ele vestirá também vocês, que têm uma fé tão pequena!

[[v40-6-31]]

^<<v40-6-31,31>>^ Portanto, não fiquem preocupados, perguntando: "Onde é que vamos arranjar comida?" ou "Onde é que vamos arranjar bebida?" ou "Onde é que vamos arranjar roupas?"

[[v40-6-32]]

^<<v40-6-32,32>>^ Pois os pagãos é que estão sempre procurando essas coisas. O Pai de vocês, que está no céu, sabe que vocês precisam de tudo isso.

[[v40-6-33]]

^<<v40-6-33,33>>^ Portanto, ponham em primeiro lugar na sua vida o Reino de Deus  e aquilo que Deus quer, e ele lhes dará todas essas coisas.

[[v40-6-34]]

^<<v40-6-34,34>>^ Por isso, não fiquem preocupados com o dia de amanhã, pois o dia de amanhã trará as suas próprias preocupações. Para cada dia bastam as suas próprias dificuldades.

'''

xref:040-mateus/040-mateus-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-mateus/040-mateus-007.adoc#v40-7-0[Próximo Capítulo &#62;]