include::./index.adoc[]

[[v40-3-0]]
=== Mateus, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-3-1]]

^<<v40-3-1,1>>^ Naquele tempo João Batista foi para o deserto da Judeia e começou a pregar,

[[v40-3-2]]

^<<v40-3-2,2>>^ dizendo: — Arrependam-se dos seus pecados porque o Reino do Céu  está perto!

[[v40-3-3]]

^<<v40-3-3,3>>^ A respeito de João, o profeta  Isaías tinha escrito o seguinte: "Alguém está gritando no deserto: Preparem o caminho para o Senhor passar! Abram estradas retas para ele!"

[[v40-3-4]]

^<<v40-3-4,4>>^ João usava uma roupa feita de pelos de camelo e um cinto de couro e comia gafanhotos e mel do mato.

[[v40-3-5]]

^<<v40-3-5,5>>^ Os moradores de Jerusalém, da região da Judeia e de todos os lugares em volta do rio Jordão iam ouvi-lo.

[[v40-3-6]]

^<<v40-3-6,6>>^ Eles confessavam os seus pecados, e João os batizava no rio Jordão.

[[v40-3-7]]

^<<v40-3-7,7>>^ Quando João viu que muitos fariseus  e saduceus  vinham para serem batizados por ele, disse: — Ninhada de cobras venenosas! Quem disse que vocês escaparão do terrível castigo que Deus vai mandar?

[[v40-3-8]]

^<<v40-3-8,8>>^ Façam coisas que mostrem que vocês se arrependeram dos seus pecados.

[[v40-3-9]]

^<<v40-3-9,9>>^ E não digam uns aos outros: "Abraão é nosso antepassado." Pois eu afirmo a vocês que até destas pedras Deus pode fazer descendentes de Abraão!

[[v40-3-10]]

^<<v40-3-10,10>>^ O machado já está pronto para cortar as árvores pela raiz. Toda árvore que não dá frutas boas será cortada e jogada no fogo.

[[v40-3-11]]

^<<v40-3-11,11>>^ Eu os batizo com água para mostrar que vocês se arrependeram dos seus pecados, mas aquele que virá depois de mim os batizará com o Espírito Santo e fogo. Ele é mais importante do que eu, e não mereço a honra de carregar as sandálias dele.

[[v40-3-12]]

^<<v40-3-12,12>>^ Com a pá que tem na mão ele vai separar o trigo da palha. Guardará o trigo no seu depósito, mas queimará a palha no fogo que nunca se apaga.

[[v40-3-13]]

^<<v40-3-13,13>>^ Naqueles dias, Jesus foi da Galileia até o rio Jordão a fim de ser batizado por João Batista.

[[v40-3-14]]

^<<v40-3-14,14>>^ Mas João tentou convencê-lo a mudar de ideia, dizendo assim: — Eu é que preciso ser batizado por você, e você está querendo que eu o batize?

[[v40-3-15]]

^<<v40-3-15,15>>^ Mas Jesus respondeu: — Deixe que seja assim agora, pois é dessa maneira que faremos tudo o que Deus quer. E João concordou.

[[v40-3-16]]

^<<v40-3-16,16>>^ Logo que foi batizado, Jesus saiu da água. O céu se abriu, e Jesus viu o Espírito de Deus descer como uma pomba e pousar sobre ele.

[[v40-3-17]]

^<<v40-3-17,17>>^ E do céu veio uma voz, que disse: — Este é o meu Filho querido, que me dá muita alegria!

'''

xref:040-mateus/040-mateus-002.adoc#v40-2-0[&#60; Capítulo Anterior] | <<v40-3-0,Topo>> | xref:040-mateus/040-mateus-004.adoc#v40-4-0[Próximo Capítulo &#62;]