include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-27-1]]

^<<v40-27-1,1>>^ Assim que amanheceu, todos os chefes dos sacerdotes e os líderes judeus fizeram os seus planos para conseguir que Jesus fosse morto.

[[v40-27-2]]

^<<v40-27-2,2>>^ Eles o amarraram, levaram e entregaram ao governador Pilatos.

[[v40-27-3]]

^<<v40-27-3,3>>^ Quando Judas, o traidor, viu que Jesus havia sido condenado, sentiu remorso e foi devolver as trinta moedas de prata aos chefes dos sacerdotes e aos líderes judeus,

[[v40-27-4]]

^<<v40-27-4,4>>^ dizendo: — Eu pequei, entregando à morte um homem inocente. Eles responderam: — O que é que nós temos com isso? O problema é seu.

[[v40-27-5]]

^<<v40-27-5,5>>^ Então Judas jogou o dinheiro para dentro do Templo e saiu. Depois foi e se enforcou.

[[v40-27-6]]

^<<v40-27-6,6>>^ Os chefes dos sacerdotes pegaram o dinheiro e disseram: — Isto é dinheiro sujo de sangue, e é contra a nossa Lei  pôr esse dinheiro na caixa das ofertas do Templo.

[[v40-27-7]]

^<<v40-27-7,7>>^ Depois de conversarem sobre o assunto, resolveram usar o dinheiro para comprar o "Campo do Oleiro", a fim de que servisse como cemitério para os não judeus.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso aquele campo é chamado até hoje  de "Campo de Sangue".

[[v40-27-9]]

^<<v40-27-9,9>>^ Assim aconteceu o que o profeta  Jeremias tinha dito: "Eles pegaram as trinta moedas de prata, o preço que o povo de Israel tinha concordado em pagar por ele,

[[v40-27-10]]

^<<v40-27-10,10>>^ e as usaram para comprar o campo do oleiro, como o Senhor me havia mandado fazer."

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus estava em pé diante do Governador, e este o interrogou, dizendo: — Você é o rei dos judeus? Jesus respondeu: — Quem está dizendo isso é o senhor.

[[v40-27-12]]

^<<v40-27-12,12>>^ Mas, quando foi acusado pelos chefes dos sacerdotes e pelos líderes judeus, Jesus não respondeu nada.

[[v40-27-13]]

^<<v40-27-13,13>>^ Então Pilatos disse: — Você não está ouvindo as acusações que estão fazendo contra você?

[[v40-27-14]]

^<<v40-27-14,14>>^ Porém Jesus não disse nada, e o Governador ficou muito admirado com isso.

[[v40-27-15]]

^<<v40-27-15,15>>^ Em toda Festa da Páscoa , Pilatos costumava soltar um dos presos, a pedido do povo.

[[v40-27-16]]

^<<v40-27-16,16>>^ Naquela ocasião estava preso um homem muito conhecido, chamado Jesus Barrabás.

[[v40-27-17]]

^<<v40-27-17,17>>^ Então, quando a multidão se reuniu, Pilatos perguntou: — Quem é que vocês querem que eu solte: Jesus Barrabás ou este Jesus, que é chamado de Messias ?

[[v40-27-18]]

^<<v40-27-18,18>>^ Pilatos sabia muito bem que os líderes judeus haviam entregado Jesus porque tinham inveja dele.

[[v40-27-19]]

^<<v40-27-19,19>>^ Enquanto Pilatos estava sentado no tribunal, a sua esposa lhe mandou o seguinte recado: — Não tenha nada a ver com esse homem inocente porque esta noite, num sonho, eu sofri muito por causa dele.

[[v40-27-20]]

^<<v40-27-20,20>>^ Os chefes dos sacerdotes e os líderes judeus convenceram a multidão a pedir ao governador Pilatos que soltasse Barrabás e condenasse Jesus à morte.

[[v40-27-21]]

^<<v40-27-21,21>>^ Então o Governador perguntou: — Qual dos dois vocês querem que eu solte? — Barrabás! — responderam eles.

[[v40-27-22]]

^<<v40-27-22,22>>^ Pilatos perguntou: — Que farei então com Jesus, que é chamado de Messias? — Crucifica! — responderam todos.

[[v40-27-23]]

^<<v40-27-23,23>>^ Ele perguntou: — Que crime ele cometeu? Aí começaram a gritar bem alto: — Crucifica!

[[v40-27-24]]

^<<v40-27-24,24>>^ Então Pilatos viu que não conseguia nada e que o povo estava começando a se revoltar. Aí mandou trazer água, lavou as mãos diante da multidão e disse: — Eu não sou responsável pela morte deste homem. Isso é com vocês.

[[v40-27-25]]

^<<v40-27-25,25>>^ E toda a multidão respondeu: — Que o castigo por esta morte caia sobre nós e sobre os nossos filhos!

[[v40-27-26]]

^<<v40-27-26,26>>^ Então Pilatos soltou Barrabás, como eles haviam pedido. Depois mandou chicotear Jesus e o entregou para ser crucificado.

[[v40-27-27]]

^<<v40-27-27,27>>^ Depois os soldados de Pilatos levaram Jesus para o Palácio do Governador e reuniram toda a tropa em volta dele.

[[v40-27-28]]

^<<v40-27-28,28>>^ Tiraram a roupa de Jesus e o vestiram com uma capa  vermelha.

[[v40-27-29]]

^<<v40-27-29,29>>^ Fizeram uma coroa de ramos cheios de espinhos, e a puseram na sua cabeça, e colocaram um bastão na sua mão direita. Aí começaram a se ajoelhar diante dele e a caçoar, dizendo: — Viva o Rei dos Judeus!

[[v40-27-30]]

^<<v40-27-30,30>>^ Cuspiam nele, pegavam o bastão e batiam na sua cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Depois de terem caçoado dele, tiraram a capa vermelha e o vestiram com as suas próprias roupas. Em seguida o levaram para o crucificarem.

[[v40-27-32]]

^<<v40-27-32,32>>^ Quando estavam saindo, os soldados encontraram um homem chamado Simão, da cidade de Cirene, e o obrigaram a carregar a cruz de Jesus.

[[v40-27-33]]

^<<v40-27-33,33>>^ Eles chegaram a um lugar chamado Gólgota. (Gólgota quer dizer "Lugar da Caveira".)

[[v40-27-34]]

^<<v40-27-34,34>>^ Ali deram vinho misturado com fel para Jesus beber. Mas, depois que o provou, ele não quis beber.

[[v40-27-35]]

^<<v40-27-35,35>>^ Em seguida os soldados o crucificaram e repartiram as suas roupas entre si, tirando a sorte com dados, para ver qual seria a parte de cada um.

[[v40-27-36]]

^<<v40-27-36,36>>^ Depois disso sentaram ali e ficaram guardando Jesus.

[[v40-27-37]]

^<<v40-27-37,37>>^ Puseram acima da sua cabeça uma tabuleta onde estava escrito como acusação contra ele: "Este é Jesus, o Rei dos Judeus."

[[v40-27-38]]

^<<v40-27-38,38>>^ Com Jesus, crucificaram também dois ladrões: um à sua direita e o outro à sua esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ Os que passavam por ali caçoavam dele, balançavam a cabeça e o insultavam,

[[v40-27-40]]

^<<v40-27-40,40>>^ dizendo assim: — Ei, você que disse que era capaz de destruir o Templo e tornar a construí-lo em três dias! Se você é mesmo o Filho de Deus, desça da cruz e salve-se a si mesmo!

[[v40-27-41]]

^<<v40-27-41,41>>^ Os chefes dos sacerdotes, os mestres  da Lei e os líderes judeus também caçoavam dele, dizendo:

[[v40-27-42]]

^<<v40-27-42,42>>^ — Ele salvou os outros, mas não pode salvar a si mesmo! Ele é o Rei de Israel, não é? Se descer agora mesmo da cruz, nós creremos nele!

[[v40-27-43]]

^<<v40-27-43,43>>^ Ele confiou em Deus e disse que era Filho de Deus. Vamos ver se Deus quer salvá-lo agora!

[[v40-27-44]]

^<<v40-27-44,44>>^ E até os ladrões que foram crucificados com Jesus também o insultavam.

[[v40-27-45]]

^<<v40-27-45,45>>^ Ao meio-dia começou a escurecer, e toda a terra ficou três horas na escuridão.

[[v40-27-46]]

^<<v40-27-46,46>>^ Às três horas da tarde, Jesus gritou bem alto: — "Eli, Eli, lemá sabactani?"  Essas palavras querem dizer: "Meu Deus, meu Deus, por que me abandonaste?"

[[v40-27-47]]

^<<v40-27-47,47>>^ Algumas pessoas que estavam ali ouviram isso e disseram: — Ele está chamando Elias.

[[v40-27-48]]

^<<v40-27-48,48>>^ Uma dessas pessoas correu e molhou uma esponja em vinho comum, pôs na ponta de um bastão e deu para Jesus beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ Mas outros disseram: — Espere. Vamos ver se Elias vem salvá-lo!

[[v40-27-50]]

^<<v40-27-50,50>>^ Aí Jesus deu outro grito forte e morreu.

[[v40-27-51]]

^<<v40-27-51,51>>^ Então a cortina do Templo se rasgou em dois pedaços, de cima até embaixo. A terra tremeu, e as rochas se partiram.

[[v40-27-52]]

^<<v40-27-52,52>>^ Os túmulos se abriram, e muitas pessoas do povo de Deus que haviam morrido foram ressuscitadas

[[v40-27-53]]

^<<v40-27-53,53>>^ e saíram dos túmulos. E, depois da ressurreição de Jesus, entraram em Jerusalém, a Cidade Santa, onde muitos viram essas pessoas.

[[v40-27-54]]

^<<v40-27-54,54>>^ O oficial do exército romano e os seus soldados, que estavam guardando Jesus, viram o terremoto e tudo o que aconteceu. Então ficaram com muito medo e disseram: — De fato, este homem era o Filho de Deus!

[[v40-27-55]]

^<<v40-27-55,55>>^ Algumas mulheres estavam ali, olhando de longe. Eram as que tinham acompanhado Jesus desde a Galileia e o haviam ajudado.

[[v40-27-56]]

^<<v40-27-56,56>>^ Entre elas estavam Maria Madalena; Maria, a mãe de Tiago e de José; e a mãe dos filhos de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ Já era quase noite quando chegou da cidade de Arimateia um homem rico chamado José. Ele também era seguidor de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ José foi e pediu a Pilatos o corpo de Jesus. E Pilatos mandou que o entregassem a ele.

[[v40-27-59]]

^<<v40-27-59,59>>^ Então José pegou o corpo, enrolou num lençol novo de linho

[[v40-27-60]]

^<<v40-27-60,60>>^ e o colocou no seu próprio túmulo, que há pouco tempo havia sido cavado na rocha. Depois rolou uma grande pedra para fechar a entrada do túmulo e foi embora.

[[v40-27-61]]

^<<v40-27-61,61>>^ Maria Madalena e a outra Maria estavam ali, sentadas em frente do túmulo.

[[v40-27-62]]

^<<v40-27-62,62>>^ No dia seguinte, isto é, o dia depois da sexta-feira, os chefes dos sacerdotes e os fariseus  se reuniram com Pilatos

[[v40-27-63]]

^<<v40-27-63,63>>^ e disseram: — Governador, nós lembramos que, quando ainda estava vivo, aquele mentiroso disse: "Depois de três dias eu serei ressuscitado."

[[v40-27-64]]

^<<v40-27-64,64>>^ Portanto, mande vigiar bem o túmulo até o terceiro dia, para os discípulos dele não poderem roubar o corpo e depois dizerem ao povo que ele foi ressuscitado. Pois esta última mentira seria pior do que a primeira.

[[v40-27-65]]

^<<v40-27-65,65>>^ Então Pilatos disse: — Levem estes soldados com vocês e guardem o túmulo o melhor que puderem.

[[v40-27-66]]

^<<v40-27-66,66>>^ Eles foram, puseram um selo  de segurança na pedra e deixaram os soldados ali, guardando o túmulo.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]