include::./index.adoc[]

[[v40-14-0]]
=== Mateus, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-14-1]]

^<<v40-14-1,1>>^ Naquele tempo Herodes, o governador da Galileia, ouviu falar a respeito de Jesus.

[[v40-14-2]]

^<<v40-14-2,2>>^ Então ele disse aos seus funcionários: — Esse homem é João Batista, que foi ressuscitado. Por isso esse homem tem poder para fazer milagres.

[[v40-14-3]]

^<<v40-14-3,3>>^ Pois Herodes tinha mandado prender João, amarrar as suas mãos e jogá-lo na cadeia. Ele havia feito isso por causa de Herodias, esposa do seu irmão Filipe.

[[v40-14-4]]

^<<v40-14-4,4>>^ Pois João Batista tinha dito muitas vezes a Herodes: "Pela nossa Lei  você é proibido de casar com Herodias!"

[[v40-14-5]]

^<<v40-14-5,5>>^ Herodes queria matá-lo, mas tinha medo do povo, pois eles achavam que João era profeta .

[[v40-14-6]]

^<<v40-14-6,6>>^ No dia do aniversário de Herodes, a filha de Herodias dançou diante de todos, e ele gostou tanto,

[[v40-14-7]]

^<<v40-14-7,7>>^ que prometeu à moça: — Juro que darei tudo o que você me pedir!

[[v40-14-8]]

^<<v40-14-8,8>>^ Seguindo o conselho da sua mãe, ela pediu: — Quero a cabeça de João Batista num prato, agora mesmo!

[[v40-14-9]]

^<<v40-14-9,9>>^ O rei Herodes ficou triste, mas, por causa do juramento que havia feito na frente dos convidados, ordenou que o pedido da moça fosse atendido.

[[v40-14-10]]

^<<v40-14-10,10>>^ E mandou que cortassem a cabeça de João Batista, na cadeia.

[[v40-14-11]]

^<<v40-14-11,11>>^ Aí trouxeram a cabeça num prato, entregaram para a moça, e ela a levou para a sua mãe.

[[v40-14-12]]

^<<v40-14-12,12>>^ Então os discípulos de João vieram, levaram o corpo dele e o sepultaram. Depois foram contar isso a Jesus.

[[v40-14-13]]

^<<v40-14-13,13>>^ Ao saber o que havia acontecido, Jesus saiu dali num barco e foi sozinho para um lugar deserto. Mas as multidões souberam onde ele estava, vieram dos seus povoados e o seguiram por terra.

[[v40-14-14]]

^<<v40-14-14,14>>^ Quando Jesus saiu do barco e viu aquela grande multidão, ficou com muita pena deles e curou os doentes que estavam ali.

[[v40-14-15]]

^<<v40-14-15,15>>^ De tardinha, os discípulos chegaram perto de Jesus e disseram: — Já é tarde, e este lugar é deserto. Mande essa gente embora, a fim de que vão aos povoados e comprem alguma coisa para comer.

[[v40-14-16]]

^<<v40-14-16,16>>^ Mas Jesus respondeu: — Eles não precisam ir embora. Deem vocês mesmos comida a eles.

[[v40-14-17]]

^<<v40-14-17,17>>^ Eles disseram: — Só temos aqui cinco pães e dois peixes.

[[v40-14-18]]

^<<v40-14-18,18>>^ — Pois tragam para mim!  — disse Jesus.

[[v40-14-19]]

^<<v40-14-19,19>>^ Então mandou o povo sentar-se na grama. Depois pegou os cinco pães e os dois peixes, olhou para o céu e deu graças a Deus. Partiu os pães, entregou-os aos discípulos, e estes distribuíram ao povo.

[[v40-14-20]]

^<<v40-14-20,20>>^ Todos comeram e ficaram satisfeitos, e os discípulos ainda recolheram doze cestos cheios dos pedaços que sobraram.

[[v40-14-21]]

^<<v40-14-21,21>>^ Os que comeram foram mais ou menos cinco mil homens, sem contar as mulheres e as crianças.

[[v40-14-22]]

^<<v40-14-22,22>>^ Logo depois, Jesus ordenou aos discípulos que subissem no barco e fossem na frente para o lado oeste do lago, enquanto ele mandava o povo embora.

[[v40-14-23]]

^<<v40-14-23,23>>^ Depois de mandar o povo embora, Jesus subiu um monte a fim de orar sozinho. Quando chegou a noite, ele estava ali, sozinho.

[[v40-14-24]]

^<<v40-14-24,24>>^ Naquele momento o barco já estava no meio do lago. E as ondas batiam com força no barco porque o vento soprava contra ele.

[[v40-14-25]]

^<<v40-14-25,25>>^ Já de madrugada, entre as três e as seis horas, Jesus foi até lá, andando em cima da água.

[[v40-14-26]]

^<<v40-14-26,26>>^ Quando os discípulos viram Jesus andando em cima da água, ficaram apavorados e exclamaram: — É um fantasma! E gritaram de medo.

[[v40-14-27]]

^<<v40-14-27,27>>^ Nesse instante Jesus disse: — Coragem! Sou eu! Não tenham medo!

[[v40-14-28]]

^<<v40-14-28,28>>^ Então Pedro disse: — Se é o senhor mesmo, mande que eu vá andando em cima da água até onde o senhor está.

[[v40-14-29]]

^<<v40-14-29,29>>^ — Venha!  — respondeu Jesus. Pedro saiu do barco e começou a andar em cima da água, em direção a Jesus.

[[v40-14-30]]

^<<v40-14-30,30>>^ Porém, quando sentiu a força do vento, ficou com medo e começou a afundar. Então gritou: — Socorro, Senhor!

[[v40-14-31]]

^<<v40-14-31,31>>^ Imediatamente Jesus estendeu a mão, segurou Pedro e disse: — Como é pequena a sua fé! Por que você duvidou?

[[v40-14-32]]

^<<v40-14-32,32>>^ Então os dois subiram no barco, e o vento se acalmou.

[[v40-14-33]]

^<<v40-14-33,33>>^ E os discípulos adoraram Jesus, dizendo: — De fato, o senhor é o Filho de Deus!

[[v40-14-34]]

^<<v40-14-34,34>>^ Jesus e os discípulos atravessaram o lago e chegaram à região de Genesaré.

[[v40-14-35]]

^<<v40-14-35,35>>^ Ali o povo reconheceu Jesus e avisou todos os doentes das regiões vizinhas. Então muitas pessoas levaram doentes a ele,

[[v40-14-36]]

^<<v40-14-36,36>>^ pedindo que deixasse que os doentes pelo menos tocassem na barra da sua roupa. E todos os que tocavam nela ficavam curados.

'''

xref:040-mateus/040-mateus-013.adoc#v40-13-0[&#60; Capítulo Anterior] | <<v40-14-0,Topo>> | xref:040-mateus/040-mateus-015.adoc#v40-15-0[Próximo Capítulo &#62;]