include::./index.adoc[]

[[v40-20-0]]
=== Mateus, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-20-1]]

^<<v40-20-1,1>>^ Jesus disse: — O Reino do Céu  é como o dono de uma plantação de uvas que saiu de manhã bem cedo para contratar trabalhadores para a sua plantação.

[[v40-20-2]]

^<<v40-20-2,2>>^ Ele combinou com eles o salário de costume, isto é, uma moeda de prata por dia, e mandou que fossem trabalhar na sua plantação.

[[v40-20-3]]

^<<v40-20-3,3>>^ Às nove horas, saiu outra vez, foi até a praça do mercado e viu ali alguns homens que não estavam fazendo nada.

[[v40-20-4]]

^<<v40-20-4,4>>^ Então disse: "Vão vocês também trabalhar na minha plantação de uvas, e eu pagarei o que for justo."

[[v40-20-5]]

^<<v40-20-5,5>>^ — E eles foram. Ao meio-dia e às três horas da tarde o dono da plantação fez a mesma coisa com outros trabalhadores.

[[v40-20-6]]

^<<v40-20-6,6>>^ Eram quase cinco horas da tarde quando ele voltou à praça. Viu outros homens que ainda estavam ali e perguntou: "Por que vocês estão o dia todo aqui sem fazer nada?"

[[v40-20-7]]

^<<v40-20-7,7>>^ — "É porque ninguém nos contratou!" — responderam eles. — Então ele disse: "Vão vocês também trabalhar na minha plantação."

[[v40-20-8]]

^<<v40-20-8,8>>^ — No fim do dia, ele disse ao administrador: "Chame os trabalhadores e faça o pagamento, começando com os que foram contratados por último e terminando pelos primeiros."

[[v40-20-9]]

^<<v40-20-9,9>>^ — Os homens que começaram a trabalhar às cinco horas da tarde receberam uma moeda de prata cada um.

[[v40-20-10]]

^<<v40-20-10,10>>^ Então os primeiros que tinham sido contratados pensaram que iam receber mais; porém eles também receberam uma moeda de prata cada um.

[[v40-20-11]]

^<<v40-20-11,11>>^ Pegaram o dinheiro e começaram a resmungar contra o patrão,

[[v40-20-12]]

^<<v40-20-12,12>>^ dizendo: "Estes homens que foram contratados por último trabalharam somente uma hora, mas nós aguentamos o dia todo debaixo deste sol quente. No entanto, o pagamento deles foi igual ao nosso!"

[[v40-20-13]]

^<<v40-20-13,13>>^ — Aí o dono disse a um deles: "Escute, amigo! Eu não fui injusto com você. Você não concordou em trabalhar o dia todo por uma moeda de prata?

[[v40-20-14]]

^<<v40-20-14,14>>^ Pegue o seu pagamento e vá embora. Pois eu quero dar a este homem, que foi contratado por último, o mesmo que dei a você.

[[v40-20-15]]

^<<v40-20-15,15>>^ Por acaso não tenho o direito de fazer o que quero com o meu próprio dinheiro? Ou você está com inveja somente porque fui bom para ele?"

[[v40-20-16]]

^<<v40-20-16,16>>^ E Jesus terminou, dizendo: — Assim, aqueles que são os primeiros serão os últimos, e os últimos serão os primeiros.

[[v40-20-17]]

^<<v40-20-17,17>>^ Quando Jesus estava subindo para Jerusalém, chamou os discípulos para um lado e falou com eles em particular, enquanto caminhavam. Ele disse:

[[v40-20-18]]

^<<v40-20-18,18>>^ — Escutem! Nós estamos indo para Jerusalém, onde o Filho do Homem  será entregue aos chefes dos sacerdotes e aos mestres  da Lei. Eles o condenarão à morte

[[v40-20-19]]

^<<v40-20-19,19>>^ e o entregarão aos não judeus. Estes vão zombar dele, bater nele e crucificá-lo; mas no terceiro dia ele será ressuscitado.

[[v40-20-20]]

^<<v40-20-20,20>>^ Então a mãe dos filhos de Zebedeu chegou com os seus filhos perto de Jesus, curvou-se e pediu a ele um favor.

[[v40-20-21]]

^<<v40-20-21,21>>^ — O que é que você quer?  — perguntou Jesus. Ela respondeu: — Prometa que, quando o senhor se tornar Rei, estes meus dois filhos sentarão à sua direita e à sua esquerda.

[[v40-20-22]]

^<<v40-20-22,22>>^ Jesus disse aos dois filhos dela: — Vocês não sabem o que estão pedindo. Por acaso vocês podem beber o cálice que eu vou beber? — Podemos! — responderam eles.

[[v40-20-23]]

^<<v40-20-23,23>>^ Então Jesus disse: — De fato, vocês beberão o cálice que eu vou beber, mas eu não tenho o direito de escolher quem vai sentar à minha direita e à minha esquerda. Pois foi o meu Pai quem preparou esses lugares e ele os dará a quem quiser.

[[v40-20-24]]

^<<v40-20-24,24>>^ Quando os outros dez discípulos ouviram isso, ficaram zangados com os dois irmãos.

[[v40-20-25]]

^<<v40-20-25,25>>^ Então Jesus chamou todos para perto de si e disse: — Como vocês sabem, os governadores dos povos pagãos têm autoridade sobre eles, e os poderosos mandam neles.

[[v40-20-26]]

^<<v40-20-26,26>>^ Mas entre vocês não pode ser assim. Pelo contrário, quem quiser ser importante, que sirva os outros,

[[v40-20-27]]

^<<v40-20-27,27>>^ e quem quiser ser o primeiro, que seja o escravo de vocês.

[[v40-20-28]]

^<<v40-20-28,28>>^ Porque até o Filho do Homem  não veio para ser servido, mas para servir e dar a sua vida para salvar muita gente.

[[v40-20-29]]

^<<v40-20-29,29>>^ Quando Jesus e os discípulos estavam saindo de Jericó, uma grande multidão seguia Jesus.

[[v40-20-30]]

^<<v40-20-30,30>>^ Dois cegos, sentados na beira do caminho, ouviram alguém dizer que ele estava passando e começaram a gritar: — Senhor, Filho de Davi , tenha pena de nós!

[[v40-20-31]]

^<<v40-20-31,31>>^ A multidão os repreendeu e mandou que calassem a boca, mas eles gritaram ainda mais: — Senhor, Filho de Davi, tenha pena de nós!

[[v40-20-32]]

^<<v40-20-32,32>>^ Então Jesus parou, chamou os cegos e perguntou: — O que é que vocês querem que eu faça?

[[v40-20-33]]

^<<v40-20-33,33>>^ — Senhor, queremos poder enxergar! — responderam eles.

[[v40-20-34]]

^<<v40-20-34,34>>^ Jesus teve pena dos cegos e tocou nos olhos deles. No mesmo instante eles puderam ver e então seguiram Jesus.

'''

xref:040-mateus/040-mateus-019.adoc#v40-19-0[&#60; Capítulo Anterior] | <<v40-20-0,Topo>> | xref:040-mateus/040-mateus-021.adoc#v40-21-0[Próximo Capítulo &#62;]