include::./index.adoc[]

[[v40-25-0]]
=== Mateus, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-25-1]]

^<<v40-25-1,1>>^ Jesus disse: — Naquele dia o Reino do Céu  será como dez moças que pegaram as suas lamparinas e saíram para se encontrar com o noivo .

[[v40-25-2]]

^<<v40-25-2,2>>^ Cinco eram sem juízo, e cinco eram ajuizadas.

[[v40-25-3]]

^<<v40-25-3,3>>^ As moças sem juízo pegaram as suas lamparinas, mas não levaram óleo de reserva.

[[v40-25-4]]

^<<v40-25-4,4>>^ As ajuizadas levaram vasilhas com óleo para as suas lamparinas.

[[v40-25-5]]

^<<v40-25-5,5>>^ Como o noivo estava demorando, as dez moças começaram a cochilar e pegaram no sono.

[[v40-25-6]]

^<<v40-25-6,6>>^ — À meia-noite se ouviu este grito: "O noivo está chegando! Venham se encontrar com ele!"

[[v40-25-7]]

^<<v40-25-7,7>>^ — Então as dez moças acordaram e acenderam as suas lamparinas.

[[v40-25-8]]

^<<v40-25-8,8>>^ Aí as moças sem juízo disseram às outras: "Deem um pouco de óleo para nós, pois as nossas lamparinas estão se apagando."

[[v40-25-9]]

^<<v40-25-9,9>>^ — "De jeito nenhum", responderam as moças ajuizadas. "O óleo que nós temos não dá para nós e para vocês. Se vocês querem óleo, vão comprar!"

[[v40-25-10]]

^<<v40-25-10,10>>^ — Então as moças sem juízo saíram para comprar óleo, e, enquanto estavam fora, o noivo chegou. As cinco moças que estavam com as lamparinas prontas entraram com ele para a festa do casamento, e a porta foi trancada.

[[v40-25-11]]

^<<v40-25-11,11>>^ — Mais tarde as outras chegaram e começaram a gritar: "Senhor, senhor, nos deixe entrar!"

[[v40-25-12]]

^<<v40-25-12,12>>^ — O noivo respondeu: "Eu afirmo a vocês que isto é verdade: eu não sei quem são vocês!"

[[v40-25-13]]

^<<v40-25-13,13>>^ E Jesus terminou, dizendo: — Portanto, fiquem vigiando porque vocês não sabem qual será o dia e a hora.

[[v40-25-14]]

^<<v40-25-14,14>>^ Jesus continuou: — O Reino do Céu  será como um homem que ia fazer uma viagem. Ele chamou os seus empregados e os pôs para tomarem conta da sua propriedade.

[[v40-25-15]]

^<<v40-25-15,15>>^ E lhes deu dinheiro de acordo com a capacidade de cada um: ao primeiro deu quinhentas moedas de ouro; ao segundo deu duzentas; e ao terceiro deu cem. Então foi viajar.

[[v40-25-16]]

^<<v40-25-16,16>>^ O empregado que tinha recebido quinhentas moedas saiu logo, fez negócios com o dinheiro e conseguiu outras quinhentas.

[[v40-25-17]]

^<<v40-25-17,17>>^ Do mesmo modo, o que havia recebido duzentas moedas conseguiu outras duzentas.

[[v40-25-18]]

^<<v40-25-18,18>>^ Mas o que tinha recebido cem moedas saiu, fez um buraco na terra e escondeu o dinheiro do patrão.

[[v40-25-19]]

^<<v40-25-19,19>>^ — Depois de muito tempo, o patrão voltou e fez um acerto de contas com eles.

[[v40-25-20]]

^<<v40-25-20,20>>^ O empregado que havia recebido quinhentas moedas chegou e entregou mais quinhentas, dizendo: "O senhor me deu quinhentas moedas. Veja! Aqui estão mais quinhentas que consegui ganhar."

[[v40-25-21]]

^<<v40-25-21,21>>^ — "Muito bem, empregado bom e fiel", disse o patrão. "Você foi fiel negociando com pouco dinheiro, e por isso vou pôr você para negociar com muito. Venha festejar comigo!"

[[v40-25-22]]

^<<v40-25-22,22>>^ — Então o empregado que havia recebido duzentas moedas chegou e disse: "O senhor me deu duzentas moedas. Veja! Aqui estão mais duzentas que consegui ganhar."

[[v40-25-23]]

^<<v40-25-23,23>>^ — "Muito bem, empregado bom e fiel", disse o patrão. "Você foi fiel negociando com pouco dinheiro, e por isso vou pôr você para negociar com muito. Venha festejar comigo!"

[[v40-25-24]]

^<<v40-25-24,24>>^ — Aí o empregado que havia recebido cem moedas chegou e disse: "Eu sei que o senhor é um homem duro, que colhe onde não plantou e junta onde não semeou.

[[v40-25-25]]

^<<v40-25-25,25>>^ Fiquei com medo e por isso escondi o seu dinheiro na terra. Veja! Aqui está o seu dinheiro."

[[v40-25-26]]

^<<v40-25-26,26>>^ — "Empregado mau e preguiçoso!", disse o patrão. "Você sabia que colho onde não plantei e junto onde não semeei.

[[v40-25-27]]

^<<v40-25-27,27>>^ Por isso você devia ter depositado o meu dinheiro no banco, e, quando eu voltasse, o receberia com juros." — Depois virou-se para os outros empregados e disse:

[[v40-25-28]]

^<<v40-25-28,28>>^ "Tirem dele o dinheiro e deem ao que tem mil moedas.

[[v40-25-29]]

^<<v40-25-29,29>>^ Porque aquele que tem muito receberá mais e assim terá mais ainda; mas quem não tem, até o pouco que tem será tirado dele.

[[v40-25-30]]

^<<v40-25-30,30>>^ E joguem fora, na escuridão, o empregado inútil. Ali ele vai chorar e ranger os dentes de desespero."

[[v40-25-31]]

^<<v40-25-31,31>>^ Jesus terminou, dizendo: — Quando o Filho do Homem  vier como Rei, com todos os anjos, ele se sentará no seu trono real.

[[v40-25-32]]

^<<v40-25-32,32>>^ Todos os povos da terra se reunirão diante dele, e ele separará as pessoas umas das outras, assim como o pastor separa as ovelhas das cabras.

[[v40-25-33]]

^<<v40-25-33,33>>^ Ele porá os bons à sua direita e os outros, à esquerda.

[[v40-25-34]]

^<<v40-25-34,34>>^ Então o Rei dirá aos que estiverem à sua direita: "Venham, vocês que são abençoados pelo meu Pai! Venham e recebam o Reino  que o meu Pai preparou para vocês desde a criação do mundo.

[[v40-25-35]]

^<<v40-25-35,35>>^ Pois eu estava com fome, e vocês me deram comida; estava com sede, e me deram água. Era estrangeiro, e me receberam na sua casa.

[[v40-25-36]]

^<<v40-25-36,36>>^ Estava sem roupa, e me vestiram; estava doente, e cuidaram de mim. Estava na cadeia, e foram me visitar."

[[v40-25-37]]

^<<v40-25-37,37>>^ — Então os bons perguntarão: "Senhor, quando foi que o vimos com fome e lhe demos comida ou com sede e lhe demos água?

[[v40-25-38]]

^<<v40-25-38,38>>^ Quando foi que vimos o senhor como estrangeiro e o recebemos na nossa casa ou sem roupa e o vestimos?

[[v40-25-39]]

^<<v40-25-39,39>>^ Quando foi que vimos o senhor doente ou na cadeia e fomos visitá-lo?"

[[v40-25-40]]

^<<v40-25-40,40>>^ — Aí o Rei responderá: "Eu afirmo a vocês que isto é verdade: quando vocês fizeram isso ao mais humilde dos meus irmãos, foi a mim que fizeram."

[[v40-25-41]]

^<<v40-25-41,41>>^ — Depois ele dirá aos que estiverem à sua esquerda: "Afastem-se de mim, vocês que estão debaixo da maldição de Deus! Vão para o fogo eterno, preparado para o Diabo e os seus anjos!

[[v40-25-42]]

^<<v40-25-42,42>>^ Pois eu estava com fome, e vocês não me deram comida; estava com sede, e não me deram água.

[[v40-25-43]]

^<<v40-25-43,43>>^ Era estrangeiro, e não me receberam na sua casa; estava sem roupa, e não me vestiram. Estava doente e na cadeia, e vocês não cuidaram de mim."

[[v40-25-44]]

^<<v40-25-44,44>>^ — Então eles perguntarão: "Senhor, quando foi que vimos o senhor com fome, ou com sede, ou como estrangeiro, ou sem roupa, ou doente, ou na cadeia e não o ajudamos?"

[[v40-25-45]]

^<<v40-25-45,45>>^ — O Rei responderá: "Eu afirmo a vocês que isto é verdade: todas as vezes que vocês deixaram de ajudar uma destas pessoas mais humildes, foi a mim que deixaram de ajudar."

[[v40-25-46]]

^<<v40-25-46,46>>^ E Jesus terminou assim: — Portanto, estes irão para o castigo eterno, mas os bons irão para a vida eterna.

'''

xref:040-mateus/040-mateus-024.adoc#v40-24-0[&#60; Capítulo Anterior] | <<v40-25-0,Topo>> | xref:040-mateus/040-mateus-026.adoc#v40-26-0[Próximo Capítulo &#62;]