include::./index.adoc[]

[[v40-5-0]]
=== Mateus, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-5-1]]

^<<v40-5-1,1>>^ Quando Jesus viu aquelas multidões, subiu um monte e sentou-se. Os seus discípulos chegaram perto dele,

[[v40-5-2]]

^<<v40-5-2,2>>^ e ele começou a ensiná-los. Jesus disse:

[[v40-5-3]]

^<<v40-5-3,3>>^ — Felizes as pessoas que sabem que são espiritualmente pobres, pois o Reino do Céu  é delas.

[[v40-5-4]]

^<<v40-5-4,4>>^ — Felizes as pessoas que choram, pois Deus as consolará.

[[v40-5-5]]

^<<v40-5-5,5>>^ — Felizes as pessoas humildes, pois receberão o que Deus tem prometido.

[[v40-5-6]]

^<<v40-5-6,6>>^ — Felizes as pessoas que têm fome e sede de fazer a vontade de Deus, pois ele as deixará completamente satisfeitas.

[[v40-5-7]]

^<<v40-5-7,7>>^ — Felizes as pessoas que têm misericórdia dos outros, pois Deus terá misericórdia delas.

[[v40-5-8]]

^<<v40-5-8,8>>^ — Felizes as pessoas que têm o coração puro, pois elas verão a Deus.

[[v40-5-9]]

^<<v40-5-9,9>>^ — Felizes as pessoas que trabalham pela paz, pois Deus as tratará como seus filhos.

[[v40-5-10]]

^<<v40-5-10,10>>^ — Felizes as pessoas que sofrem perseguições por fazerem a vontade de Deus, pois o Reino do Céu é delas.

[[v40-5-11]]

^<<v40-5-11,11>>^ — Felizes são vocês quando os insultam, perseguem e dizem todo tipo de calúnia contra vocês por serem meus seguidores.

[[v40-5-12]]

^<<v40-5-12,12>>^ Fiquem alegres e felizes, pois uma grande recompensa está guardada no céu para vocês. Porque foi assim mesmo que perseguiram os profetas  que viveram antes de vocês.

[[v40-5-13]]

^<<v40-5-13,13>>^ — Vocês são o sal para a humanidade; mas, se o sal perde o gosto, deixa de ser sal e não serve para mais nada. É jogado fora e pisado pelas pessoas que passam.

[[v40-5-14]]

^<<v40-5-14,14>>^ — Vocês são a luz para o mundo. Não se pode esconder uma cidade construída sobre um monte.

[[v40-5-15]]

^<<v40-5-15,15>>^ Ninguém acende uma lamparina para colocá-la debaixo de um cesto. Pelo contrário, ela é colocada no lugar próprio para que ilumine todos os que estão na casa.

[[v40-5-16]]

^<<v40-5-16,16>>^ Assim também a luz de vocês deve brilhar para que os outros vejam as coisas boas que vocês fazem e louvem o Pai de vocês, que está no céu.

[[v40-5-17]]

^<<v40-5-17,17>>^ — Não pensem que eu vim para acabar com a Lei  de Moisés ou com os ensinamentos dos Profetas . Não vim para acabar com eles, mas para dar o seu sentido completo.

[[v40-5-18]]

^<<v40-5-18,18>>^ Eu afirmo a vocês que isto é verdade: enquanto o céu e a terra durarem, nada será tirado da Lei — nem a menor letra, nem qualquer acento. E assim será até o fim de todas as coisas.

[[v40-5-19]]

^<<v40-5-19,19>>^ Portanto, qualquer um que desobedecer ao menor mandamento e ensinar os outros a fazerem o mesmo será considerado o menor no Reino do Céu . Por outro lado, quem obedecer à Lei e ensinar os outros a fazerem o mesmo será considerado grande no Reino do Céu.

[[v40-5-20]]

^<<v40-5-20,20>>^ Pois eu afirmo a vocês que só entrarão no Reino do Céu se forem mais fiéis em fazer a vontade de Deus do que os mestres  da Lei e os fariseus .

[[v40-5-21]]

^<<v40-5-21,21>>^ — Vocês ouviram o que foi dito aos seus antepassados: "Não mate. Quem matar será julgado."

[[v40-5-22]]

^<<v40-5-22,22>>^ Mas eu lhes digo que qualquer um que ficar com raiva do seu irmão será julgado. Quem disser ao seu irmão: "Você não vale nada" será julgado pelo tribunal. E quem chamar o seu irmão de idiota estará em perigo de ir para o fogo do inferno.

[[v40-5-23]]

^<<v40-5-23,23>>^ Portanto, se você estiver oferecendo no altar a sua oferta a Deus e lembrar que o seu irmão tem alguma queixa contra você,

[[v40-5-24]]

^<<v40-5-24,24>>^ deixe a sua oferta ali, na frente do altar, e vá logo fazer as pazes com o seu irmão. Depois volte e ofereça a sua oferta a Deus.

[[v40-5-25]]

^<<v40-5-25,25>>^ — Se alguém fizer uma acusação contra você e levá-lo ao tribunal, entre em acordo com essa pessoa enquanto ainda é tempo, antes de chegarem lá. Porque, depois de chegarem ao tribunal, você será entregue ao juiz, o juiz o entregará ao carcereiro, e você será jogado na cadeia.

[[v40-5-26]]

^<<v40-5-26,26>>^ Eu afirmo a você que isto é verdade: você não sairá dali enquanto não pagar a multa toda.

[[v40-5-27]]

^<<v40-5-27,27>>^ — Vocês ouviram o que foi dito: "Não cometa adultério."

[[v40-5-28]]

^<<v40-5-28,28>>^ Mas eu lhes digo: quem olhar para uma mulher e desejar possuí-la já cometeu adultério no seu coração.

[[v40-5-29]]

^<<v40-5-29,29>>^ Portanto, se o seu olho direito faz com que você peque, arranque-o e jogue-o fora. Pois é melhor perder uma parte do seu corpo do que o corpo inteiro ser atirado no inferno.

[[v40-5-30]]

^<<v40-5-30,30>>^ Se a sua mão direita faz com que você peque, corte-a e jogue-a fora. Pois é melhor perder uma parte do seu corpo do que o corpo inteiro ir para o inferno.

[[v40-5-31]]

^<<v40-5-31,31>>^ — Foi dito também: "Quem mandar a sua esposa embora deverá dar a ela um documento de divórcio."

[[v40-5-32]]

^<<v40-5-32,32>>^ Mas eu lhes digo: todo homem que mandar a sua esposa embora, a não ser em caso de adultério, será culpado de fazer com que ela se torne adúltera, se ela casar de novo. E o homem que casar com ela também cometerá adultério.

[[v40-5-33]]

^<<v40-5-33,33>>^ — Vocês ouviram o que foi dito aos seus antepassados: "Não quebre a sua promessa, mas cumpra o que você jurou ao Senhor que ia fazer."

[[v40-5-34]]

^<<v40-5-34,34>>^ Mas eu lhes digo: não jurem de jeito nenhum. Não jurem pelo céu, pois é o trono de Deus;

[[v40-5-35]]

^<<v40-5-35,35>>^ nem pela terra, pois é o estrado onde ele descansa os seus pés; nem por Jerusalém, pois é a cidade do grande Rei.

[[v40-5-36]]

^<<v40-5-36,36>>^ Não jurem nem mesmo pela sua cabeça, pois vocês não podem fazer com que um só fio dos seus cabelos fique branco ou preto.

[[v40-5-37]]

^<<v40-5-37,37>>^ Que o "sim" de vocês seja sim, e o "não", não, pois qualquer coisa a mais que disserem vem do Maligno .

[[v40-5-38]]

^<<v40-5-38,38>>^ — Vocês ouviram o que foi dito: "Olho por olho, dente por dente."

[[v40-5-39]]

^<<v40-5-39,39>>^ Mas eu lhes digo: não se vinguem dos que fazem mal a vocês. Se alguém lhe der um tapa na cara, vire o outro lado para ele bater também.

[[v40-5-40]]

^<<v40-5-40,40>>^ Se alguém processar você para tomar a sua túnica , deixe que leve também a capa .

[[v40-5-41]]

^<<v40-5-41,41>>^ Se um dos soldados estrangeiros forçá-lo a carregar uma carga um quilômetro, carregue-a dois quilômetros.

[[v40-5-42]]

^<<v40-5-42,42>>^ Se alguém lhe pedir alguma coisa, dê; e, se alguém lhe pedir emprestado, empreste.

[[v40-5-43]]

^<<v40-5-43,43>>^ — Vocês ouviram o que foi dito: "Ame os seus amigos e odeie os seus inimigos."

[[v40-5-44]]

^<<v40-5-44,44>>^ Mas eu lhes digo: amem os seus inimigos e orem pelos que perseguem vocês,

[[v40-5-45]]

^<<v40-5-45,45>>^ para que vocês se tornem filhos do Pai de vocês, que está no céu. Porque ele faz com que o sol brilhe sobre os bons e sobre os maus e dá chuvas tanto para os que fazem o bem como para os que fazem o mal.

[[v40-5-46]]

^<<v40-5-46,46>>^ Se vocês amam somente aqueles que os amam, por que esperam que Deus lhes dê alguma recompensa? Até os cobradores de impostos amam as pessoas que os amam!

[[v40-5-47]]

^<<v40-5-47,47>>^ Se vocês falam somente com os seus amigos, o que é que estão fazendo de mais? Até os pagãos fazem isso!

[[v40-5-48]]

^<<v40-5-48,48>>^ Portanto, sejam perfeitos, assim como é perfeito o Pai de vocês, que está no céu.

'''

xref:040-mateus/040-mateus-004.adoc#v40-4-0[&#60; Capítulo Anterior] | <<v40-5-0,Topo>> | xref:040-mateus/040-mateus-006.adoc#v40-6-0[Próximo Capítulo &#62;]