include::./index.adoc[]

[[v40-11-0]]
=== Mateus, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-11-1]]

^<<v40-11-1,1>>^ Quando acabou de dar essas ordens aos seus doze discípulos, Jesus saiu daquele lugar e foi ensinar e anunciar a sua mensagem nas cidades que ficavam perto dali.

[[v40-11-2]]

^<<v40-11-2,2>>^ João Batista estava na cadeia e, quando ouviu falar do que Cristo fazia, mandou que alguns dos seus discípulos

[[v40-11-3]]

^<<v40-11-3,3>>^ fossem perguntar a ele: — O senhor é aquele que ia chegar ou devemos esperar outro?

[[v40-11-4]]

^<<v40-11-4,4>>^ Jesus respondeu: — Voltem e contem a João o que vocês estão ouvindo e vendo.

[[v40-11-5]]

^<<v40-11-5,5>>^ Digam a ele que os cegos veem, os coxos andam, os leprosos são curados, os surdos ouvem, os mortos são ressuscitados, e os pobres recebem o evangelho .

[[v40-11-6]]

^<<v40-11-6,6>>^ E felizes são aqueles que não abandonam a sua fé em mim!

[[v40-11-7]]

^<<v40-11-7,7>>^ Quando os discípulos de João foram embora, Jesus começou a dizer ao povo o seguinte a respeito de João: — O que vocês foram ver no deserto? Um caniço sacudido pelo vento?

[[v40-11-8]]

^<<v40-11-8,8>>^ O que foram ver? Um homem bem-vestido? Ora, os que se vestem bem moram nos palácios!

[[v40-11-9]]

^<<v40-11-9,9>>^ Então me digam: o que esperavam ver? Um profeta ? Sim. E eu afirmo que vocês viram muito mais do que um profeta.

[[v40-11-10]]

^<<v40-11-10,10>>^ Porque João é aquele a respeito de quem as Escrituras Sagradas  dizem: "Aqui está o meu mensageiro, disse Deus. Eu o enviarei adiante de você para preparar o seu caminho."

[[v40-11-11]]

^<<v40-11-11,11>>^ Eu afirmo a vocês que isto é verdade: de todos os homens que já nasceram, João Batista é o maior. Porém quem é menor no Reino do Céu  é maior do que ele.

[[v40-11-12]]

^<<v40-11-12,12>>^ Desde os dias em que João anunciava a sua mensagem, até hoje, o Reino do Céu tem sido atacado com violência, e as pessoas violentas tentam conquistá-lo.

[[v40-11-13]]

^<<v40-11-13,13>>^ Até o tempo de João, todos os Profetas  e a Lei  de Moisés falaram a respeito do Reino.

[[v40-11-14]]

^<<v40-11-14,14>>^ E, se vocês querem crer na mensagem deles, João é Elias, que estava para vir.

[[v40-11-15]]

^<<v40-11-15,15>>^ Se vocês têm ouvidos para ouvir, então ouçam.

[[v40-11-16]]

^<<v40-11-16,16>>^ — Mas com quem posso comparar as pessoas de hoje? São como crianças sentadas na praça. Um grupo grita para o outro:

[[v40-11-17]]

^<<v40-11-17,17>>^ "Nós tocamos músicas de casamento, mas vocês não dançaram! Cantamos músicas de sepultamento, mas vocês não choraram!"

[[v40-11-18]]

^<<v40-11-18,18>>^ João Batista jejua e não bebe vinho, e todos dizem: "Ele está dominado por um demônio."

[[v40-11-19]]

^<<v40-11-19,19>>^ O Filho do Homem  come e bebe, e todos dizem: "Vejam! Este homem é comilão e beberrão! É amigo dos cobradores de impostos e de outras pessoas de má fama." Porém é pelos seus resultados que a sabedoria de Deus mostra que é verdadeira.

[[v40-11-20]]

^<<v40-11-20,20>>^ Então Jesus começou a acusar as cidades onde tinha feito muitos milagres. Ele fez isso porque os seus moradores não haviam se arrependido dos seus pecados. Jesus disse:

[[v40-11-21]]

^<<v40-11-21,21>>^ — Ai de você, cidade de Corazim! Ai de você, cidade de Betsaida! Porque, se os milagres que foram feitos em vocês tivessem sido feitos nas cidades de Tiro e de Sidom, os seus moradores já teriam abandonado os seus pecados há muito tempo. E, para mostrarem que estavam arrependidos, teriam vestido roupa feita de pano grosseiro e teriam jogado cinzas na cabeça!

[[v40-11-22]]

^<<v40-11-22,22>>^ Pois eu afirmo a vocês que, no Dia do Juízo, Deus terá mais pena de Tiro e de Sidom do que de vocês, Corazim e Betsaida.

[[v40-11-23]]

^<<v40-11-23,23>>^ E você, cidade de Cafarnaum, acha que vai subir até o céu? Pois será jogada no mundo dos mortos ! Porque, se os milagres que foram feitos aí tivessem sido feitos na cidade de Sodoma, ela existiria até hoje.

[[v40-11-24]]

^<<v40-11-24,24>>^ Pois eu afirmo a vocês que, no Dia do Juízo, Deus terá mais pena de Sodoma do que de você, Cafarnaum.

[[v40-11-25]]

^<<v40-11-25,25>>^ Naquela ocasião Jesus disse: — Ó Pai, Senhor do céu e da terra, eu te agradeço porque tens mostrado às pessoas sem instrução aquilo que escondeste dos sábios e dos instruídos!

[[v40-11-26]]

^<<v40-11-26,26>>^ Sim, ó Pai, tu tiveste prazer em fazer isso.

[[v40-11-27]]

^<<v40-11-27,27>>^ — O meu Pai me deu todas as coisas. Ninguém sabe quem é o Filho, a não ser o Pai; e ninguém sabe quem é o Pai, a não ser o Filho e também aqueles a quem o Filho quiser mostrar quem o Pai é.

[[v40-11-28]]

^<<v40-11-28,28>>^ — Venham a mim, todos vocês que estão cansados de carregar as suas pesadas cargas, e eu lhes darei descanso.

[[v40-11-29]]

^<<v40-11-29,29>>^ Sejam meus seguidores e aprendam comigo porque sou bondoso e tenho um coração humilde; e vocês encontrarão descanso.

[[v40-11-30]]

^<<v40-11-30,30>>^ Os deveres que eu exijo de vocês são fáceis, e a carga que eu ponho sobre vocês é leve.

'''

xref:040-mateus/040-mateus-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-mateus/040-mateus-012.adoc#v40-12-0[Próximo Capítulo &#62;]