include::./index.adoc[]

[[v40-16-0]]
=== Mateus, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-16-1]]

^<<v40-16-1,1>>^ Alguns fariseus  e alguns saduceus  foram falar com Jesus. Eles queriam alguma prova contra ele e por isso pediram que ele fizesse um milagre para mostrar que o seu poder vinha mesmo de Deus.

[[v40-16-2]]

^<<v40-16-2,2>>^ Mas Jesus respondeu: — De tardinha, vocês dizem: "Vamos ter bom tempo porque o céu está vermelho."

[[v40-16-3]]

^<<v40-16-3,3>>^ E, de manhã, cedo, dizem: "Vai chover porque o céu está vermelho-escuro." Olhando o céu, vocês sabem como vai ser o tempo. E como é que não sabem explicar o que querem dizer os sinais desta época?

[[v40-16-4]]

^<<v40-16-4,4>>^ Como o povo de hoje é mau e sem fé! Vocês estão me pedindo um milagre, mas o milagre de Jonas é o único sinal que lhes será dado. Então ele saiu e foi embora.

[[v40-16-5]]

^<<v40-16-5,5>>^ Quando os discípulos atravessaram para o lado leste do lago, esqueceram de levar pão.

[[v40-16-6]]

^<<v40-16-6,6>>^ Jesus disse: — Fiquem alertas e tomem cuidado com o fermento dos fariseus  e dos saduceus .

[[v40-16-7]]

^<<v40-16-7,7>>^ Aí os discípulos começaram a dizer uns aos outros: — Ele está dizendo isso porque não trouxemos pão.

[[v40-16-8]]

^<<v40-16-8,8>>^ Jesus ouviu o que eles estavam dizendo e perguntou: — Por que é que vocês estão conversando por não terem pão? Como é pequena a fé que vocês têm!

[[v40-16-9]]

^<<v40-16-9,9>>^ Ainda não entenderam? Não lembram dos cinco pães que eu parti para cinco mil homens? Quantos cestos vocês encheram?

[[v40-16-10]]

^<<v40-16-10,10>>^ E aqueles sete pães para quatro mil homens? Quantos cestos vocês encheram?

[[v40-16-11]]

^<<v40-16-11,11>>^ Vocês não entendem que eu não estou falando a respeito de pães? Tenham cuidado com o fermento dos fariseus e dos saduceus!

[[v40-16-12]]

^<<v40-16-12,12>>^ Então os discípulos entenderam que ele não estava dizendo que tivessem cuidado com o fermento usado no pão, mas com os ensinamentos dos fariseus e dos saduceus.

[[v40-16-13]]

^<<v40-16-13,13>>^ Jesus foi para a região que fica perto da cidade de Cesareia de Filipe. Ali perguntou aos discípulos: — Quem o povo diz que o Filho do Homem  é?

[[v40-16-14]]

^<<v40-16-14,14>>^ Eles responderam: — Alguns dizem que o senhor é João Batista; outros, que é Elias; e outros, que é Jeremias ou algum outro profeta .

[[v40-16-15]]

^<<v40-16-15,15>>^ — E vocês? Quem vocês dizem que eu sou?  — perguntou Jesus.

[[v40-16-16]]

^<<v40-16-16,16>>^ Simão Pedro respondeu: — O senhor é o Messias , o Filho do Deus vivo.

[[v40-16-17]]

^<<v40-16-17,17>>^ Jesus afirmou: — Simão, filho de João, você é feliz porque esta verdade não foi revelada a você por nenhum ser humano, mas veio diretamente do meu Pai, que está no céu.

[[v40-16-18]]

^<<v40-16-18,18>>^ Portanto, eu lhe digo: você é Pedro, e sobre esta pedra construirei a minha Igreja, e nem a morte poderá vencê-la.

[[v40-16-19]]

^<<v40-16-19,19>>^ Eu lhe darei as chaves do Reino do Céu ; o que você proibir na terra será proibido no céu, e o que permitir na terra será permitido no céu.

[[v40-16-20]]

^<<v40-16-20,20>>^ Então Jesus ordenou que os discípulos não contassem a ninguém que ele era o Messias.

[[v40-16-21]]

^<<v40-16-21,21>>^ Daí em diante, Jesus começou a dizer claramente aos discípulos: — Eu preciso ir para Jerusalém, e ali os líderes judeus, os chefes dos sacerdotes e os mestres  da Lei farão com que eu sofra muito. Eu serei morto e, no terceiro dia, serei ressuscitado.

[[v40-16-22]]

^<<v40-16-22,22>>^ Então Pedro o levou para um lado e começou a repreendê-lo, dizendo: — Que Deus não permita! Isso nunca vai acontecer com o senhor!

[[v40-16-23]]

^<<v40-16-23,23>>^ Jesus virou-se e disse a Pedro: — Saia da minha frente, Satanás! Você é como uma pedra no meu caminho para fazer com que eu tropece, pois está pensando como um ser humano pensa e não como Deus pensa.

[[v40-16-24]]

^<<v40-16-24,24>>^ E Jesus disse aos discípulos: — Se alguém quer ser meu seguidor, esqueça os seus próprios interesses, esteja pronto para morrer como eu vou morrer e me acompanhe.

[[v40-16-25]]

^<<v40-16-25,25>>^ Pois quem põe os seus próprios interesses em primeiro lugar nunca terá a vida verdadeira; mas quem esquece a si mesmo por minha causa terá a vida verdadeira.

[[v40-16-26]]

^<<v40-16-26,26>>^ O que adianta alguém ganhar o mundo inteiro, mas perder a vida verdadeira? Pois não há nada que poderá pagar para ter de volta essa vida.

[[v40-16-27]]

^<<v40-16-27,27>>^ Pois o Filho do Homem  virá na glória  do seu Pai com os seus anjos e então recompensará cada um de acordo com o que fez.

[[v40-16-28]]

^<<v40-16-28,28>>^ Eu afirmo a vocês que isto é verdade: estão aqui algumas pessoas que não morrerão antes de verem o Filho do Homem vir como Rei.

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]