include::./index.adoc[]

[[v40-13-0]]
=== Mateus, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-13-1]]

^<<v40-13-1,1>>^ Naquele mesmo dia Jesus saiu de casa, foi para a beira do lago da Galileia, sentou-se ali e começou a ensinar.

[[v40-13-2]]

^<<v40-13-2,2>>^ A multidão que se ajuntou em volta dele era tão grande, que ele entrou num barco e sentou-se; e o povo ficou em pé na praia.

[[v40-13-3]]

^<<v40-13-3,3>>^ Jesus usou parábolas  para ensinar muitas coisas. Ele disse: — Escutem! Certo homem saiu para semear.

[[v40-13-4]]

^<<v40-13-4,4>>^ Quando estava espalhando as sementes, algumas caíram na beira do caminho, e os passarinhos comeram tudo.

[[v40-13-5]]

^<<v40-13-5,5>>^ Outra parte das sementes caiu num lugar onde havia muitas pedras e pouca terra. As sementes brotaram logo porque a terra não era funda.

[[v40-13-6]]

^<<v40-13-6,6>>^ Mas, quando o sol apareceu, queimou as plantas, e elas secaram porque não tinham raízes.

[[v40-13-7]]

^<<v40-13-7,7>>^ Outras sementes caíram no meio de espinhos, que cresceram e sufocaram as plantas.

[[v40-13-8]]

^<<v40-13-8,8>>^ Mas as sementes que caíram em terra boa produziram na base de cem, de sessenta e de trinta grãos por um.

[[v40-13-9]]

^<<v40-13-9,9>>^ E Jesus terminou, dizendo: — Se vocês têm ouvidos para ouvir, então ouçam.

[[v40-13-10]]

^<<v40-13-10,10>>^ Então os discípulos chegaram perto de Jesus e perguntaram: — Por que é que o senhor usa parábolas  para falar com essas pessoas?

[[v40-13-11]]

^<<v40-13-11,11>>^ Jesus respondeu: — A vocês Deus mostra os segredos do Reino do Céu , mas, a elas, não.

[[v40-13-12]]

^<<v40-13-12,12>>^ Pois quem tem receberá mais, para que tenha mais ainda. Mas quem não tem, até o pouco que tem lhe será tirado.

[[v40-13-13]]

^<<v40-13-13,13>>^ É por isso que eu uso parábolas para falar com essas pessoas. Porque elas olham e não enxergam; escutam e não ouvem, nem entendem.

[[v40-13-14]]

^<<v40-13-14,14>>^ E assim acontece com essas pessoas o que disse o profeta  Isaías: "Vocês ouvirão, mas não entenderão; olharão, mas não enxergarão nada.

[[v40-13-15]]

^<<v40-13-15,15>>^ Pois a mente deste povo está fechada: Eles taparam os ouvidos e fecharam os olhos. Se eles não tivessem feito isso, os seus olhos poderiam ver, e os seus ouvidos poderiam ouvir; a sua mente poderia entender, e eles voltariam para mim, e eu os curaria! — disse Deus."

[[v40-13-16]]

^<<v40-13-16,16>>^ Jesus continuou, dizendo: — Mas vocês, como são felizes! Pois os seus olhos veem, e os seus ouvidos ouvem.

[[v40-13-17]]

^<<v40-13-17,17>>^ Eu afirmo a vocês que isto é verdade: muitos profetas e muitas outras pessoas do povo de Deus gostariam de ver o que vocês estão vendo, mas não puderam; e gostariam de ouvir o que vocês estão ouvindo, mas não ouviram.

[[v40-13-18]]

^<<v40-13-18,18>>^ — Então escutem e aprendam o que a parábola  do semeador quer dizer.

[[v40-13-19]]

^<<v40-13-19,19>>^ As pessoas que ouvem a mensagem do Reino , mas não a entendem, são como as sementes que foram semeadas na beira do caminho. O Maligno vem e tira o que foi semeado no coração delas.

[[v40-13-20]]

^<<v40-13-20,20>>^ As sementes que foram semeadas onde havia muitas pedras são as pessoas que ouvem a mensagem e a aceitam logo com alegria,

[[v40-13-21]]

^<<v40-13-21,21>>^ mas duram pouco porque não têm raiz. E, quando por causa da mensagem chegam os sofrimentos e as perseguições, elas logo abandonam a sua fé.

[[v40-13-22]]

^<<v40-13-22,22>>^ Outras pessoas são parecidas com as sementes que foram semeadas no meio dos espinhos. Elas ouvem a mensagem, mas as preocupações deste mundo e a ilusão das riquezas sufocam a mensagem, e essas pessoas não produzem frutos.

[[v40-13-23]]

^<<v40-13-23,23>>^ E as sementes que foram semeadas em terra boa são aquelas pessoas que ouvem, e entendem a mensagem, e produzem uma grande colheita: umas, cem; outras, sessenta; e ainda outras, trinta vezes mais do que foi semeado.

[[v40-13-24]]

^<<v40-13-24,24>>^ Jesus contou outra parábola . Ele disse ao povo: — O Reino do Céu  é como um homem que semeou sementes boas nas suas terras.

[[v40-13-25]]

^<<v40-13-25,25>>^ Certa noite, quando todos estavam dormindo, veio um inimigo, semeou no meio do trigo uma erva ruim, chamada joio, e depois foi embora.

[[v40-13-26]]

^<<v40-13-26,26>>^ Quando as plantas cresceram, e se formaram as espigas, o joio apareceu.

[[v40-13-27]]

^<<v40-13-27,27>>^ Aí os empregados do dono das terras chegaram e disseram: "Patrão, o senhor semeou sementes boas nas suas terras. De onde será que veio este joio?"

[[v40-13-28]]

^<<v40-13-28,28>>^ — "Foi algum inimigo que fez isso!", respondeu ele. — E eles perguntaram: "O senhor quer que a gente arranque o joio?"

[[v40-13-29]]

^<<v40-13-29,29>>^ — "Não", respondeu ele, "porque, quando vocês forem tirar o joio, poderão arrancar também o trigo.

[[v40-13-30]]

^<<v40-13-30,30>>^ Deixem o trigo e o joio crescerem juntos até o tempo da colheita. Então eu direi aos trabalhadores que vão fazer a colheita: ‘Arranquem primeiro o joio e amarrem em feixes para ser queimado. Depois colham o trigo e ponham no meu depósito.’ "

[[v40-13-31]]

^<<v40-13-31,31>>^ Jesus contou outra parábola . Ele disse ao povo: — O Reino do Céu  é como uma semente de mostarda, que um homem pega e semeia na sua terra.

[[v40-13-32]]

^<<v40-13-32,32>>^ Ela é a menor de todas as sementes; mas, quando cresce, torna-se a maior de todas as plantas. Ela até chega a ser uma árvore, de modo que os passarinhos vêm e fazem ninhos nos seus ramos.

[[v40-13-33]]

^<<v40-13-33,33>>^ Jesus contou mais esta parábola  para o povo: — O Reino do Céu  é como o fermento que uma mulher pega e mistura em três medidas de farinha, até que ele se espalhe por toda a massa.

[[v40-13-34]]

^<<v40-13-34,34>>^ Jesus usava parábolas  para dizer tudo isso ao povo. Ele não dizia nada a eles sem ser por meio de parábolas.

[[v40-13-35]]

^<<v40-13-35,35>>^ Isso aconteceu para se cumprir o que o profeta  tinha dito: "Usarei parábolas quando falar com esse povo e explicarei coisas desconhecidas desde a criação do mundo."

[[v40-13-36]]

^<<v40-13-36,36>>^ Então Jesus deixou a multidão e voltou para casa. Os discípulos chegaram perto dele e perguntaram: — Conte para nós o que quer dizer a parábola  do joio.

[[v40-13-37]]

^<<v40-13-37,37>>^ Jesus respondeu: — Quem semeia as sementes boas é o Filho do Homem .

[[v40-13-38]]

^<<v40-13-38,38>>^ O terreno é o mundo. As sementes boas são as pessoas que pertencem ao Reino ; e o joio, as que pertencem ao Maligno .

[[v40-13-39]]

^<<v40-13-39,39>>^ O inimigo que semeia o joio é o próprio Diabo. A colheita é o fim dos tempos, e os que fazem a colheita são os anjos.

[[v40-13-40]]

^<<v40-13-40,40>>^ Assim como o joio é ajuntado e jogado no fogo, assim também será no fim dos tempos.

[[v40-13-41]]

^<<v40-13-41,41>>^ O Filho do Homem mandará os seus anjos, e eles ajuntarão e tirarão do seu Reino todos os que fazem com que os outros pequem e também todos os que praticam o mal.

[[v40-13-42]]

^<<v40-13-42,42>>^ Depois os anjos jogarão essas pessoas na fornalha de fogo, onde vão chorar e ranger os dentes de desespero.

[[v40-13-43]]

^<<v40-13-43,43>>^ Então o povo de Deus brilhará como o sol no Reino do seu Pai. Se vocês têm ouvidos para ouvir, então ouçam.

[[v40-13-44]]

^<<v40-13-44,44>>^ — O Reino do Céu  é como um tesouro escondido num campo, que certo homem acha e esconde de novo. Fica tão feliz, que vende tudo o que tem, e depois volta, e compra o campo.

[[v40-13-45]]

^<<v40-13-45,45>>^ — O Reino do Céu  é também como um comerciante que anda procurando pérolas finas.

[[v40-13-46]]

^<<v40-13-46,46>>^ Quando encontra uma pérola que é mesmo de grande valor, ele vai, vende tudo o que tem e compra a pérola.

[[v40-13-47]]

^<<v40-13-47,47>>^ — O Reino do Céu  é ainda como uma rede que é jogada no lago. Ela apanha peixes de todos os tipos.

[[v40-13-48]]

^<<v40-13-48,48>>^ E, quando está cheia, os pescadores a arrastam para a praia e sentam para separar os peixes: os que prestam são postos dentro dos cestos, e os que não prestam são jogados fora.

[[v40-13-49]]

^<<v40-13-49,49>>^ No fim dos tempos também será assim: os anjos sairão, e separarão as pessoas más das boas,

[[v40-13-50]]

^<<v40-13-50,50>>^ e jogarão as pessoas más na fornalha de fogo. E ali elas vão chorar e ranger os dentes de desespero.

[[v40-13-51]]

^<<v40-13-51,51>>^ Então Jesus perguntou aos discípulos: — Vocês entenderam essas coisas? — Sim! — responderam eles.

[[v40-13-52]]

^<<v40-13-52,52>>^ Jesus disse: — Pois isso quer dizer que todo mestre da Lei  que se torna discípulo no Reino do Céu  é como um pai de família que tira do seu depósito coisas novas e coisas velhas.

[[v40-13-53]]

^<<v40-13-53,53>>^ Quando Jesus acabou de contar essas parábolas , saiu dali

[[v40-13-54]]

^<<v40-13-54,54>>^ e voltou para a cidade de Nazaré, onde ele tinha morado. Ele ensinava na sinagoga , e os que o ouviam ficavam admirados e perguntavam: — De onde vêm a sabedoria dele e o poder que ele tem para fazer milagres?

[[v40-13-55]]

^<<v40-13-55,55>>^ Por acaso ele não é o filho do carpinteiro? A sua mãe não é Maria? Ele não é irmão de Tiago, José, Simão e Judas?

[[v40-13-56]]

^<<v40-13-56,56>>^ Todas as suas irmãs não moram aqui? De onde é que ele consegue tudo isso?

[[v40-13-57]]

^<<v40-13-57,57>>^ Por isso ficaram desiludidos com ele. Mas Jesus disse: — Um profeta  é respeitado em toda parte, menos na sua terra e na sua casa.

[[v40-13-58]]

^<<v40-13-58,58>>^ Jesus não pôde fazer muitos milagres ali porque eles não tinham fé.

'''

xref:040-mateus/040-mateus-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-mateus/040-mateus-014.adoc#v40-14-0[Próximo Capítulo &#62;]