include::./index.adoc[]

[[v40-26-0]]
=== Mateus, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-26-1]]

^<<v40-26-1,1>>^ Quando Jesus acabou de ensinar essas coisas, disse aos discípulos:

[[v40-26-2]]

^<<v40-26-2,2>>^ — Vocês sabem que daqui a dois dias vai ser comemorada a Festa da Páscoa , e o Filho do Homem  será entregue para ser crucificado.

[[v40-26-3]]

^<<v40-26-3,3>>^ Os chefes dos sacerdotes e os líderes judeus se reuniram no palácio de Caifás, o Grande Sacerdote ,

[[v40-26-4]]

^<<v40-26-4,4>>^ e fizeram um plano para prender Jesus em segredo e matá-lo.

[[v40-26-5]]

^<<v40-26-5,5>>^ Eles diziam: — Não vamos fazer isso durante a festa, para não haver uma revolta no meio do povo.

[[v40-26-6]]

^<<v40-26-6,6>>^ Jesus estava no povoado de Betânia, sentado à mesa na casa de Simão, o Leproso. Então uma mulher chegou perto de Jesus com um frasco feito de alabastro , cheio de um perfume muito caro, e derramou o perfume na cabeça dele.

[[v40-26-7]]

^<<v40-26-7,7>>^ Jesus estava no povoado de Betânia, sentado à mesa na casa de Simão, o Leproso. Então uma mulher chegou perto de Jesus com um frasco feito de alabastro , cheio de um perfume muito caro, e derramou o perfume na cabeça dele.

[[v40-26-8]]

^<<v40-26-8,8>>^ Ao verem aquilo, os discípulos ficaram zangados e disseram: — Que desperdício!

[[v40-26-9]]

^<<v40-26-9,9>>^ Esse perfume poderia ter sido vendido por uma fortuna, e o dinheiro, dado aos pobres.

[[v40-26-10]]

^<<v40-26-10,10>>^ Mas Jesus, sabendo o que eles diziam, disse: — Por que vocês estão aborrecendo esta mulher? Ela fez para mim uma coisa muito boa.

[[v40-26-11]]

^<<v40-26-11,11>>^ Pois os pobres estarão sempre com vocês, mas eu não.

[[v40-26-12]]

^<<v40-26-12,12>>^ O que ela fez foi perfumar o meu corpo para o meu sepultamento.

[[v40-26-13]]

^<<v40-26-13,13>>^ Eu afirmo a vocês que isto é verdade: em qualquer lugar do mundo onde o evangelho  for anunciado, será contado o que ela fez, e ela será lembrada.

[[v40-26-14]]

^<<v40-26-14,14>>^ Então um dos doze discípulos, chamado Judas Iscariotes, foi falar com os chefes dos sacerdotes.

[[v40-26-15]]

^<<v40-26-15,15>>^ Ele disse: — Quanto vocês me pagam para eu lhes entregar Jesus? E eles lhe pagaram trinta moedas de prata.

[[v40-26-16]]

^<<v40-26-16,16>>^ E daí em diante Judas ficou procurando uma oportunidade para entregar Jesus.

[[v40-26-17]]

^<<v40-26-17,17>>^ No primeiro dia da Festa dos Pães sem Fermento , os discípulos chegaram perto de Jesus e perguntaram: — Onde é que o senhor quer que a gente prepare o jantar da Páscoa  para o senhor?

[[v40-26-18]]

^<<v40-26-18,18>>^ Ele respondeu: — Vão até a cidade, procurem certo homem e digam: "O Mestre manda dizer: A minha hora chegou. Os meus discípulos e eu vamos comemorar a Páscoa na sua casa."

[[v40-26-19]]

^<<v40-26-19,19>>^ Os discípulos fizeram como Jesus havia mandado e prepararam o jantar da Páscoa.

[[v40-26-20]]

^<<v40-26-20,20>>^ Quando anoiteceu, Jesus e os doze discípulos sentaram para comer.

[[v40-26-21]]

^<<v40-26-21,21>>^ Durante o jantar Jesus disse: — Eu afirmo a vocês que isto é verdade: um de vocês vai me trair.

[[v40-26-22]]

^<<v40-26-22,22>>^ Eles ficaram muito tristes e, um por um, começaram a perguntar: — O senhor não está achando que sou eu; está?

[[v40-26-23]]

^<<v40-26-23,23>>^ Jesus respondeu: — Quem vai me trair é aquele que come no mesmo prato que eu.

[[v40-26-24]]

^<<v40-26-24,24>>^ Pois o Filho do Homem  vai morrer da maneira como dizem as Escrituras Sagradas ; mas ai daquele que está traindo o Filho do Homem! Seria melhor para ele nunca ter nascido!

[[v40-26-25]]

^<<v40-26-25,25>>^ Então Judas, o traidor, perguntou: — Mestre, o senhor não está achando que sou eu; está? Jesus respondeu: — Quem está dizendo isso é você mesmo.

[[v40-26-26]]

^<<v40-26-26,26>>^ Enquanto estavam comendo, Jesus pegou o pão e deu graças a Deus. Depois partiu o pão e o deu aos discípulos, dizendo: — Peguem e comam; isto é o meu corpo.

[[v40-26-27]]

^<<v40-26-27,27>>^ Em seguida, pegou o cálice de vinho e agradeceu a Deus. Depois passou o cálice aos discípulos, dizendo: — Bebam todos vocês

[[v40-26-28]]

^<<v40-26-28,28>>^ porque isto é o meu sangue, que é derramado em favor de muitos para o perdão dos pecados, o sangue que garante a aliança  feita por Deus com o seu povo.

[[v40-26-29]]

^<<v40-26-29,29>>^ Eu afirmo a vocês que nunca mais beberei deste vinho até o dia em que beber com vocês um vinho novo no Reino do meu Pai .

[[v40-26-30]]

^<<v40-26-30,30>>^ Então eles cantaram canções de louvor e foram para o monte das Oliveiras.

[[v40-26-31]]

^<<v40-26-31,31>>^ E Jesus disse aos discípulos: — Esta noite todos vocês vão fugir e me abandonar, pois as Escrituras Sagradas  dizem: "Matarei o pastor, e as ovelhas serão espalhadas."

[[v40-26-32]]

^<<v40-26-32,32>>^ Mas, depois que eu ressuscitar, irei adiante de vocês para a Galileia.

[[v40-26-33]]

^<<v40-26-33,33>>^ Então Pedro disse a Jesus: — Eu nunca abandonarei o senhor, mesmo que todos o abandonem.

[[v40-26-34]]

^<<v40-26-34,34>>^ Mas Jesus lhe disse: — Eu afirmo a você que isto é verdade: nesta mesma noite, antes que o galo cante, você dirá três vezes que não me conhece.

[[v40-26-35]]

^<<v40-26-35,35>>^ Pedro respondeu: — Eu nunca vou dizer que não o conheço, mesmo que eu tenha de morrer com o senhor! E todos os outros discípulos disseram a mesma coisa.

[[v40-26-36]]

^<<v40-26-36,36>>^ Jesus foi com os discípulos para um lugar chamado Getsêmani e lhes disse: — Sentem-se aqui, enquanto eu vou ali orar.

[[v40-26-37]]

^<<v40-26-37,37>>^ Então Jesus foi, levando consigo Pedro e os dois filhos de Zebedeu. Aí ele começou a sentir uma grande tristeza e aflição

[[v40-26-38]]

^<<v40-26-38,38>>^ e disse a eles: — A tristeza que estou sentindo é tão grande, que é capaz de me matar. Fiquem aqui vigiando comigo.

[[v40-26-39]]

^<<v40-26-39,39>>^ Ele foi um pouco mais adiante, ajoelhou-se, encostou o rosto no chão e orou: — Meu Pai, se é possível, afasta de mim este cálice de sofrimento! Porém que não seja feito o que eu quero, mas o que tu queres.

[[v40-26-40]]

^<<v40-26-40,40>>^ Depois voltou e encontrou os três discípulos dormindo. Então disse a Pedro: — Será que vocês não podem vigiar comigo nem uma hora?

[[v40-26-41]]

^<<v40-26-41,41>>^ Vigiem e orem para que não sejam tentados. É fácil querer resistir à tentação; o difícil mesmo é conseguir.

[[v40-26-42]]

^<<v40-26-42,42>>^ Pela segunda vez Jesus foi e orou, dizendo: — Meu Pai, se este cálice de sofrimento não pode ser afastado de mim sem que eu o beba, então que seja feita a tua vontade.

[[v40-26-43]]

^<<v40-26-43,43>>^ Ele voltou de novo e encontrou os discípulos dormindo. Eles estavam com sono e não conseguiam ficar com os olhos abertos.

[[v40-26-44]]

^<<v40-26-44,44>>^ Jesus tornou a sair de perto deles e orou pela terceira vez, dizendo as mesmas palavras.

[[v40-26-45]]

^<<v40-26-45,45>>^ Então voltou até onde os discípulos estavam e perguntou: — Vocês ainda estão dormindo e descansando? Olhem! Chegou a hora, e o Filho do Homem  está sendo entregue nas mãos dos maus.

[[v40-26-46]]

^<<v40-26-46,46>>^ Levantem-se, e vamos embora. Vejam! Aí vem chegando o homem que está me traindo!

[[v40-26-47]]

^<<v40-26-47,47>>^ Jesus ainda estava falando, quando chegou Judas, um dos doze discípulos. Vinha com ele uma grande multidão armada com espadas e porretes, que tinha sido mandada pelos chefes dos sacerdotes e pelos líderes judeus.

[[v40-26-48]]

^<<v40-26-48,48>>^ O traidor tinha combinado com eles um sinal. Ele tinha dito: "Prendam o homem que eu beijar, pois é ele."

[[v40-26-49]]

^<<v40-26-49,49>>^ Judas foi até perto de Jesus e disse: — Mestre, que a paz esteja com o senhor! E o beijou.

[[v40-26-50]]

^<<v40-26-50,50>>^ Jesus respondeu: — Amigo, o que você vai fazer faça agora. Então eles chegaram, prenderam Jesus e o amarraram.

[[v40-26-51]]

^<<v40-26-51,51>>^ Mas um dos que estavam ali com Jesus tirou a espada, atacou um empregado do Grande Sacerdote  e cortou uma orelha dele.

[[v40-26-52]]

^<<v40-26-52,52>>^ Aí Jesus disse: — Guarde a sua espada, pois quem usa uma espada será morto por uma espada.

[[v40-26-53]]

^<<v40-26-53,53>>^ Você não sabe que, se eu pedisse ajuda ao meu Pai, ele me mandaria agora mesmo doze exércitos de anjos?

[[v40-26-54]]

^<<v40-26-54,54>>^ Mas, nesse caso, como poderia se cumprir aquilo que as Escrituras Sagradas  dizem que é preciso acontecer?

[[v40-26-55]]

^<<v40-26-55,55>>^ Depois Jesus disse para aquela gente: — Vocês vêm com espadas e porretes para me prender como se eu fosse um bandido? Eu estava todos os dias ensinando no pátio do Templo, e vocês não me prenderam.

[[v40-26-56]]

^<<v40-26-56,56>>^ Mas tudo isso está acontecendo para se cumprir o que os profetas  escreveram nas Escrituras Sagradas. Então todos os discípulos abandonaram Jesus e fugiram.

[[v40-26-57]]

^<<v40-26-57,57>>^ Os homens que prenderam Jesus o levaram até a casa do Grande Sacerdote  Caifás, onde estavam reunidos alguns mestres  da Lei e alguns líderes judeus.

[[v40-26-58]]

^<<v40-26-58,58>>^ Pedro seguiu Jesus de longe até o pátio da casa do Grande Sacerdote. Entrou e sentou-se com os guardas para ver como aquilo ia terminar.

[[v40-26-59]]

^<<v40-26-59,59>>^ Os chefes dos sacerdotes e todo o Conselho Superior  estavam procurando alguma acusação falsa contra Jesus a fim de o condenar à morte.

[[v40-26-60]]

^<<v40-26-60,60>>^ Mas não puderam encontrar nada contra ele, embora muitos se levantassem para dizer mentiras a respeito dele. Afinal dois homens se apresentaram

[[v40-26-61]]

^<<v40-26-61,61>>^ e disseram: — Este homem afirmou: "Eu posso destruir o Templo de Deus e construí-lo de novo em três dias."

[[v40-26-62]]

^<<v40-26-62,62>>^ Aí o Grande Sacerdote se levantou e perguntou a Jesus: — Você não vai se defender desta acusação?

[[v40-26-63]]

^<<v40-26-63,63>>^ Mas Jesus ficou calado. Então o Grande Sacerdote tornou a perguntar: — Em nome do Deus vivo, eu exijo que você diga para nós: você é o Messias , o Filho de Deus?

[[v40-26-64]]

^<<v40-26-64,64>>^ Jesus respondeu: — Quem está dizendo isso é o senhor. Mas eu afirmo a vocês que de agora em diante vocês verão o Filho do Homem  sentado do lado direito do Deus Todo-Poderoso e descendo nas nuvens do céu!

[[v40-26-65]]

^<<v40-26-65,65>>^ Aí o Grande Sacerdote rasgou as suas próprias roupas e disse: — Ele blasfemou ! Não precisamos mais de testemunhas! Vocês ouviram agora mesmo esta blasfêmia contra Deus!

[[v40-26-66]]

^<<v40-26-66,66>>^ Então, o que resolvem? Eles responderam: — Ele é culpado e deve morrer!

[[v40-26-67]]

^<<v40-26-67,67>>^ Em seguida cuspiram no rosto de Jesus e deram bofetadas nele. E os que batiam nele

[[v40-26-68]]

^<<v40-26-68,68>>^ diziam: — Ei, Messias, adivinhe para nós quem foi que bateu em você!

[[v40-26-69]]

^<<v40-26-69,69>>^ Pedro estava sentado lá fora no pátio, quando uma das empregadas chegou perto dele e disse: — Você também estava com Jesus da Galileia.

[[v40-26-70]]

^<<v40-26-70,70>>^ Mas ele negou diante de todos, dizendo: — Eu não sei do que é que você está falando.

[[v40-26-71]]

^<<v40-26-71,71>>^ Depois foi para a entrada do pátio. Outra empregada o viu e disse às pessoas que estavam ali: — Ele estava com Jesus de Nazaré.

[[v40-26-72]]

^<<v40-26-72,72>>^ Pedro negou outra vez, respondendo: — Juro que não conheço esse homem!

[[v40-26-73]]

^<<v40-26-73,73>>^ Pouco depois, os que estavam ali chegaram perto de Pedro e disseram: — O seu modo de falar mostra que, de fato, você também é um deles.

[[v40-26-74]]

^<<v40-26-74,74>>^ Então Pedro disse: — Juro que não conheço esse homem! Que Deus me castigue se não estou dizendo a verdade! Naquele instante o galo cantou,

'''

xref:040-mateus/040-mateus-025.adoc#v40-25-0[&#60; Capítulo Anterior] | <<v40-26-0,Topo>> | xref:040-mateus/040-mateus-027.adoc#v40-27-0[Próximo Capítulo &#62;]