include::./index.adoc[]

[[v40-24-0]]
=== Mateus, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-24-1]]

^<<v40-24-1,1>>^ Jesus saiu do pátio do Templo, e, quando já estava indo embora, os seus discípulos chegaram perto dele e chamaram a sua atenção para os edifícios do Templo.

[[v40-24-2]]

^<<v40-24-2,2>>^ Então ele disse: — Vocês estão vendo tudo isso? Pois eu afirmo a vocês que isto é verdade: aqui não ficará uma pedra em cima da outra; tudo será destruído!

[[v40-24-3]]

^<<v40-24-3,3>>^ Jesus estava sentado no monte das Oliveiras. Então os discípulos chegaram perto dele e lhe perguntaram em particular: — Conte para nós quando é que isso vai acontecer. Que sinal haverá para mostrar que chegou o tempo de o senhor voltar e de tudo acabar?

[[v40-24-4]]

^<<v40-24-4,4>>^ Jesus respondeu: — Tomem cuidado para que ninguém engane vocês.

[[v40-24-5]]

^<<v40-24-5,5>>^ Porque muitos vão aparecer fingindo ser eu e dizendo: "Eu sou o Messias !" E enganarão muitas pessoas.

[[v40-24-6]]

^<<v40-24-6,6>>^ Não tenham medo quando ouvirem o barulho de batalhas ou notícias de guerras. Tudo isso vai acontecer, mas ainda não será o fim.

[[v40-24-7]]

^<<v40-24-7,7>>^ Uma nação vai guerrear contra outra, e um país atacará outro. Em vários lugares haverá falta de alimentos e tremores de terra.

[[v40-24-8]]

^<<v40-24-8,8>>^ Essas coisas serão como as primeiras dores de parto.

[[v40-24-9]]

^<<v40-24-9,9>>^ — Depois vocês serão presos e entregues para serem maltratados e vocês serão mortos. Todos os odiarão por serem meus seguidores.

[[v40-24-10]]

^<<v40-24-10,10>>^ Nessa época muitos vão abandonar a sua fé e vão trair e odiar uns aos outros.

[[v40-24-11]]

^<<v40-24-11,11>>^ Então muitos falsos profetas  aparecerão e enganarão muita gente.

[[v40-24-12]]

^<<v40-24-12,12>>^ A maldade vai se espalhar tanto, que o amor de muitos esfriará;

[[v40-24-13]]

^<<v40-24-13,13>>^ mas quem ficar firme até o fim será salvo.

[[v40-24-14]]

^<<v40-24-14,14>>^ E a boa notícia sobre o Reino  será anunciada no mundo inteiro como testemunho para toda a humanidade. Então virá o fim.

[[v40-24-15]]

^<<v40-24-15,15>>^ E Jesus continuou: — Vocês verão no Lugar Santo  "o grande terror", de que falou o profeta  Daniel. (Que o leitor entenda o que isso quer dizer!)

[[v40-24-16]]

^<<v40-24-16,16>>^ Então, os que estiverem na região da Judeia, que fujam para os montes.

[[v40-24-17]]

^<<v40-24-17,17>>^ Quem estiver em cima da sua casa, no terraço, que fuja logo e não entre para pegar as suas coisas.

[[v40-24-18]]

^<<v40-24-18,18>>^ E quem estiver no campo, que não volte para casa a fim de buscar as suas roupas.

[[v40-24-19]]

^<<v40-24-19,19>>^ Ai das mulheres grávidas e das mães com criancinhas naqueles dias!

[[v40-24-20]]

^<<v40-24-20,20>>^ Orem a Deus para que vocês não tenham de fugir no inverno ou no sábado .

[[v40-24-21]]

^<<v40-24-21,21>>^ Porque naqueles dias haverá um sofrimento tão grande como nunca houve desde que Deus criou o mundo; e nunca mais acontecerá uma coisa igual.

[[v40-24-22]]

^<<v40-24-22,22>>^ Porém Deus diminuiu esse tempo de sofrimento. Se não fosse assim, ninguém seria salvo. Mas, por causa do povo que Deus escolheu para salvar, esse tempo será diminuído.

[[v40-24-23]]

^<<v40-24-23,23>>^ — Portanto, se alguém disser para vocês: "Vejam! O Messias  está aqui" ou "O Messias está ali", não acreditem.

[[v40-24-24]]

^<<v40-24-24,24>>^ Porque aparecerão falsos profetas e falsos messias, que farão milagres e maravilhas para enganar, se possível, até o povo escolhido de Deus.

[[v40-24-25]]

^<<v40-24-25,25>>^ Prestem atenção! Eu estou lhes dizendo tudo isso, antes que aconteça.

[[v40-24-26]]

^<<v40-24-26,26>>^ — E, se disserem: "Vejam! Ele está no deserto", não vão lá. Ou ainda: "Vejam! Ele está escondido aqui", não acreditem.

[[v40-24-27]]

^<<v40-24-27,27>>^ Porque, assim como o relâmpago risca o céu, do nascente até o poente, assim será a vinda do Filho do Homem .

[[v40-24-28]]

^<<v40-24-28,28>>^ — Onde estiver o corpo de um morto, aí se ajuntarão os urubus.

[[v40-24-29]]

^<<v40-24-29,29>>^ Jesus disse: — Depois daqueles dias de sofrimento, o sol ficará escuro, e a lua não brilhará mais. As estrelas cairão do céu, e os poderes do espaço serão abalados.

[[v40-24-30]]

^<<v40-24-30,30>>^ Então o sinal do Filho do Homem  aparecerá no céu. Todos os povos da terra chorarão e verão o Filho do Homem descendo nas nuvens, com poder e grande glória .

[[v40-24-31]]

^<<v40-24-31,31>>^ A grande trombeta tocará, e ele mandará os seus anjos para os quatro cantos da terra. E os anjos reunirão os escolhidos de Deus de um lado do mundo até o outro.

[[v40-24-32]]

^<<v40-24-32,32>>^ Jesus disse ainda: — Aprendam a lição que a figueira ensina. Quando os seus ramos ficam verdes, e as folhas começam a brotar, vocês sabem que está chegando o verão.

[[v40-24-33]]

^<<v40-24-33,33>>^ Assim também, quando virem acontecer essas coisas, fiquem sabendo que o tempo está perto, pronto para começar.

[[v40-24-34]]

^<<v40-24-34,34>>^ Eu afirmo a vocês que isto é verdade: essas coisas vão acontecer antes de morrerem todos os que agora estão vivos.

[[v40-24-35]]

^<<v40-24-35,35>>^ O céu e a terra desaparecerão, mas as minhas palavras ficarão para sempre.

[[v40-24-36]]

^<<v40-24-36,36>>^ Jesus continuou, dizendo: — Mas ninguém sabe nem o dia nem a hora em que tudo isso vai acontecer, nem os anjos do céu, nem o Filho, mas somente o Pai.

[[v40-24-37]]

^<<v40-24-37,37>>^ A vinda do Filho do Homem  será como aquilo que aconteceu no tempo de Noé.

[[v40-24-38]]

^<<v40-24-38,38>>^ Pois, antes do dilúvio, o povo comia e bebia, e os homens e as mulheres casavam, até o dia em que Noé entrou na barca.

[[v40-24-39]]

^<<v40-24-39,39>>^ Porém não sabiam o que estava acontecendo, até que veio o dilúvio e levou todos. Assim também será a vinda do Filho do Homem.

[[v40-24-40]]

^<<v40-24-40,40>>^ — Naquele dia dois homens estarão trabalhando na fazenda: um será levado, e o outro, deixado.

[[v40-24-41]]

^<<v40-24-41,41>>^ Duas mulheres estarão no moinho moendo trigo: uma será levada, e a outra, deixada.

[[v40-24-42]]

^<<v40-24-42,42>>^ Fiquem vigiando, pois vocês não sabem em que dia vai chegar o seu Senhor.

[[v40-24-43]]

^<<v40-24-43,43>>^ Lembrem disto: se o dono da casa soubesse quando ia chegar o ladrão, ficaria vigiando e não deixaria que a sua casa fosse arrombada.

[[v40-24-44]]

^<<v40-24-44,44>>^ Por isso vocês também fiquem vigiando, pois o Filho do Homem chegará na hora em que vocês não estiverem esperando.

[[v40-24-45]]

^<<v40-24-45,45>>^ Jesus disse ainda: — Sabemos que é o empregado fiel e inteligente que o patrão encarrega de tomar conta dos outros empregados, para dar a eles os mantimentos no tempo certo.

[[v40-24-46]]

^<<v40-24-46,46>>^ Feliz aquele empregado que estiver fazendo isso quando o patrão chegar!

[[v40-24-47]]

^<<v40-24-47,47>>^ Eu afirmo a vocês que isto é verdade: o patrão vai colocá-lo como encarregado de toda a sua propriedade.

[[v40-24-48]]

^<<v40-24-48,48>>^ Mas, se o empregado for mau, pensará assim: "O meu patrão está demorando muito para voltar."

[[v40-24-49]]

^<<v40-24-49,49>>^ Então começará a bater nos seus companheiros, e a comer, e a beber com os bêbados.

[[v40-24-50]]

^<<v40-24-50,50>>^ E o patrão voltará no dia em que o empregado menos espera e na hora que ele não sabe.

[[v40-24-51]]

^<<v40-24-51,51>>^ Aí o patrão mandará cortar o empregado em pedaços e o condenará a ir para o lugar aonde os hipócritas vão. Ali ele vai chorar e ranger os dentes de desespero.

'''

xref:040-mateus/040-mateus-023.adoc#v40-23-0[&#60; Capítulo Anterior] | <<v40-24-0,Topo>> | xref:040-mateus/040-mateus-025.adoc#v40-25-0[Próximo Capítulo &#62;]