include::./index.adoc[]

[[v40-8-0]]
=== Mateus, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-8-1]]

^<<v40-8-1,1>>^ Jesus desceu do monte, e muitas multidões o seguiram.

[[v40-8-2]]

^<<v40-8-2,2>>^ Então um leproso chegou perto dele, ajoelhou-se e disse: — Senhor, eu sei que o senhor pode me curar se quiser.

[[v40-8-3]]

^<<v40-8-3,3>>^ Jesus estendeu a mão, tocou nele e disse: — Sim, eu quero. Você está curado. No mesmo instante ele ficou curado da lepra.

[[v40-8-4]]

^<<v40-8-4,4>>^ Então Jesus lhe disse: — Escute! Não conte isso para ninguém, mas vá pedir ao sacerdote que examine você. Depois, a fim de provar para todos que você está curado, vá oferecer o sacrifício  que Moisés ordenou.

[[v40-8-5]]

^<<v40-8-5,5>>^ Quando Jesus entrou na cidade de Cafarnaum, um oficial romano foi encontrar-se com ele e pediu que curasse o seu empregado.

[[v40-8-6]]

^<<v40-8-6,6>>^ Ele disse: — Senhor, o meu empregado está na minha casa, tão doente, que não pode nem se mexer na cama. Ele está sofrendo demais.

[[v40-8-7]]

^<<v40-8-7,7>>^ — Eu vou lá curá-lo!  — disse Jesus.

[[v40-8-8]]

^<<v40-8-8,8>>^ O oficial romano respondeu: — Não, senhor! Eu não mereço que o senhor entre na minha casa. Dê somente uma ordem, e o meu empregado ficará bom.

[[v40-8-9]]

^<<v40-8-9,9>>^ Eu também estou debaixo da autoridade de oficiais superiores e tenho soldados que obedecem às minhas ordens. Digo para um: "Vá lá", e ele vai. Digo para outro: "Venha cá", e ele vem. E digo também para o meu empregado: "Faça isto", e ele faz.

[[v40-8-10]]

^<<v40-8-10,10>>^ Quando Jesus ouviu isso, ficou muito admirado e disse aos que o seguiam: — Eu afirmo a vocês que isto é verdade: nunca vi tanta fé, nem mesmo entre o povo de Israel!

[[v40-8-11]]

^<<v40-8-11,11>>^ E digo a vocês que muita gente vai chegar do Leste e do Oeste e se sentar à mesa no Reino do Céu  com Abraão, Isaque e Jacó.

[[v40-8-12]]

^<<v40-8-12,12>>^ Mas as pessoas que deviam estar no Reino serão jogadas fora, na escuridão. Ali vão chorar e ranger os dentes de desespero.

[[v40-8-13]]

^<<v40-8-13,13>>^ E Jesus disse ao oficial: — Vá para casa, pois será feito como você crê. E naquele momento o empregado do oficial romano ficou curado.

[[v40-8-14]]

^<<v40-8-14,14>>^ Jesus foi à casa de Pedro e viu a sogra dele de cama, com febre.

[[v40-8-15]]

^<<v40-8-15,15>>^ Jesus tocou na mão dela, e a febre saiu dela. Então ela se levantou e começou a cuidar dele.

[[v40-8-16]]

^<<v40-8-16,16>>^ Depois do pôr do sol, o povo levou até Jesus muitas pessoas que estavam dominadas por demônios. E ele, apenas com uma palavra, expulsava os espíritos maus e curava todas as pessoas que estavam doentes.

[[v40-8-17]]

^<<v40-8-17,17>>^ Jesus fez isso para cumprir o que o profeta  Isaías tinha dito: "Ele levou as nossas doenças e carregou as nossas enfermidades."

[[v40-8-18]]

^<<v40-8-18,18>>^ Jesus viu a multidão em volta dele e mandou os discípulos irem para o lado leste do lago.

[[v40-8-19]]

^<<v40-8-19,19>>^ Um mestre da Lei  chegou perto dele e disse: — Mestre, estou pronto a seguir o senhor para qualquer lugar aonde o senhor for!

[[v40-8-20]]

^<<v40-8-20,20>>^ Jesus respondeu: — As raposas têm as suas covas, e os pássaros, os seus ninhos. Mas o Filho do Homem  não tem onde descansar.

[[v40-8-21]]

^<<v40-8-21,21>>^ E outro, que era seguidor de Jesus, disse: — Senhor, primeiro deixe que eu volte e sepulte o meu pai.

[[v40-8-22]]

^<<v40-8-22,22>>^ Jesus respondeu: — Venha comigo e deixe que os mortos sepultem os seus mortos.

[[v40-8-23]]

^<<v40-8-23,23>>^ Jesus subiu num barco, e os seus discípulos foram com ele.

[[v40-8-24]]

^<<v40-8-24,24>>^ De repente, uma grande tempestade agitou o lago, de tal maneira que as ondas começaram a cobrir o barco. E Jesus estava dormindo.

[[v40-8-25]]

^<<v40-8-25,25>>^ Os discípulos chegaram perto dele e o acordaram, dizendo: — Socorro, Senhor! Nós vamos morrer!

[[v40-8-26]]

^<<v40-8-26,26>>^ — Por que é que vocês são assim tão medrosos?  — respondeu Jesus. — Como é pequena a fé que vocês têm! Ele se levantou, falou duro com o vento e com as ondas, e tudo ficou calmo.

[[v40-8-27]]

^<<v40-8-27,27>>^ Então todos ficaram admirados e disseram: — Que homem é este que manda até no vento e nas ondas?!

[[v40-8-28]]

^<<v40-8-28,28>>^ Quando Jesus chegou à região de Gadara, no lado leste do lago da Galileia, foram se encontrar com ele dois homens que estavam dominados por demônios. Eles vinham do cemitério, onde estavam morando. Eram tão violentos e perigosos, que ninguém se arriscava a passar por aquele caminho.

[[v40-8-29]]

^<<v40-8-29,29>>^ Eles começaram a gritar: — Filho de Deus, o que o senhor quer de nós? O senhor veio aqui para nos castigar antes do tempo?

[[v40-8-30]]

^<<v40-8-30,30>>^ Acontece que perto dali estavam muitos porcos comendo.

[[v40-8-31]]

^<<v40-8-31,31>>^ E os demônios pediram a Jesus com insistência: — Se o senhor vai nos expulsar, nos mande entrar naqueles porcos!

[[v40-8-32]]

^<<v40-8-32,32>>^ — Pois vão!  — disse Jesus. Os demônios foram e entraram nos porcos, e estes se atiraram morro abaixo, para dentro do lago, e se afogaram.

[[v40-8-33]]

^<<v40-8-33,33>>^ Os homens que tomavam conta dos porcos fugiram e chegaram até a cidade. Lá contaram tudo isso e também o que havia acontecido com os dois homens que estavam dominados por demônios.

[[v40-8-34]]

^<<v40-8-34,34>>^ Então todos os moradores daquela cidade saíram para se encontrar com Jesus; e, quando o encontraram, pediram com insistência que fosse embora da terra deles.

'''

xref:040-mateus/040-mateus-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-mateus/040-mateus-009.adoc#v40-9-0[Próximo Capítulo &#62;]