include::./index.adoc[]

[[v40-9-0]]
=== Mateus, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-9-1]]

^<<v40-9-1,1>>^ Jesus entrou num barco, voltou para o lado oeste do lago e chegou à sua cidade .

[[v40-9-2]]

^<<v40-9-2,2>>^ Então algumas pessoas trouxeram um paralítico deitado numa cama. Jesus viu que eles tinham fé e disse ao paralítico: — Coragem, meu filho! Os seus pecados estão perdoados.

[[v40-9-3]]

^<<v40-9-3,3>>^ Aí alguns mestres  da Lei começaram a pensar: — Este homem está blasfemando  contra Deus.

[[v40-9-4]]

^<<v40-9-4,4>>^ Porém Jesus sabia o que eles estavam pensando e disse: — Por que é que vocês estão pensando essas coisas más?

[[v40-9-5]]

^<<v40-9-5,5>>^ O que é mais fácil dizer ao paralítico: "Os seus pecados estão perdoados" ou "Levante-se e ande"?

[[v40-9-6]]

^<<v40-9-6,6>>^ Pois vou mostrar a vocês que eu, o Filho do Homem , tenho poder na terra para perdoar pecados. Então disse ao paralítico: — Levante-se, pegue a sua cama e vá para casa.

[[v40-9-7]]

^<<v40-9-7,7>>^ O homem se levantou e foi para casa.

[[v40-9-8]]

^<<v40-9-8,8>>^ Quando o povo viu isso, ficou com medo e louvou a Deus por dar esse poder a seres humanos.

[[v40-9-9]]

^<<v40-9-9,9>>^ Jesus saiu dali e, no caminho, viu um cobrador de impostos, chamado Mateus, sentado no lugar onde os impostos eram pagos. Jesus lhe disse: — Venha comigo. Mateus se levantou e foi com ele.

[[v40-9-10]]

^<<v40-9-10,10>>^ Mais tarde, enquanto Jesus estava jantando na casa de Mateus, muitos cobradores de impostos e outras pessoas de má fama chegaram e sentaram-se à mesa com Jesus e os seus discípulos.

[[v40-9-11]]

^<<v40-9-11,11>>^ Alguns fariseus  viram isso e perguntaram aos discípulos: — Por que é que o mestre de vocês come com os cobradores de impostos e com outras pessoas de má fama?

[[v40-9-12]]

^<<v40-9-12,12>>^ Jesus ouviu a pergunta e respondeu: — Os que têm saúde não precisam de médico, mas sim os doentes.

[[v40-9-13]]

^<<v40-9-13,13>>^ Vão e procurem entender o que quer dizer este trecho das Escrituras Sagradas : "Eu quero que as pessoas sejam bondosas e não que me ofereçam sacrifícios  de animais." Porque eu vim para chamar  os pecadores e não os bons.

[[v40-9-14]]

^<<v40-9-14,14>>^ Então os discípulos de João Batista chegaram perto de Jesus e perguntaram: — Por que é que nós e os fariseus  jejuamos muitas vezes, mas os discípulos do senhor não jejuam?

[[v40-9-15]]

^<<v40-9-15,15>>^ Jesus respondeu: — Vocês acham que os convidados de um casamento podem estar tristes enquanto o noivo está com eles? Claro que não! Mas chegará o tempo em que o noivo será tirado do meio deles; então sim eles vão jejuar!

[[v40-9-16]]

^<<v40-9-16,16>>^ — Ninguém usa um retalho de pano novo para remendar uma roupa velha; pois o remendo novo encolhe e rasga a roupa velha, aumentando o buraco.

[[v40-9-17]]

^<<v40-9-17,17>>^ Ninguém põe vinho novo em odres  velhos. Se alguém fizer isso, os odres rebentam, o vinho se perde, e os odres ficam estragados. Pelo contrário, o vinho novo é posto em odres novos, e assim não se perdem nem os odres nem o vinho.

[[v40-9-18]]

^<<v40-9-18,18>>^ Enquanto Jesus estava falando ao povo, um chefe religioso chegou perto dele, ajoelhou-se e disse: — A minha filha morreu agora mesmo! Venha e ponha as mãos sobre ela para que viva de novo.

[[v40-9-19]]

^<<v40-9-19,19>>^ Então Jesus foi com ele, e os seus discípulos também foram.

[[v40-9-20]]

^<<v40-9-20,20>>^ Certa mulher, que fazia doze anos que estava com uma hemorragia, veio por trás de Jesus e tocou na barra da capa  dele.

[[v40-9-21]]

^<<v40-9-21,21>>^ Pois ela pensava assim: "Se eu apenas tocar na capa dele, ficarei curada."

[[v40-9-22]]

^<<v40-9-22,22>>^ Jesus virou, viu a mulher e disse: — Coragem, minha filha! Você sarou porque teve fé. E naquele momento a mulher ficou curada.

[[v40-9-23]]

^<<v40-9-23,23>>^ Depois Jesus foi para a casa do chefe religioso. Quando viu os que tocavam música fúnebre e viu a multidão numa confusão geral,

[[v40-9-24]]

^<<v40-9-24,24>>^ disse: — Saiam todos daqui! A menina não morreu; ela está dormindo! Então começaram a caçoar dele.

[[v40-9-25]]

^<<v40-9-25,25>>^ Logo que a multidão saiu, Jesus entrou no quarto em que a menina estava, pegou-a pela mão, e ela se levantou.

[[v40-9-26]]

^<<v40-9-26,26>>^ E a notícia a respeito disso se espalhou por toda aquela região.

[[v40-9-27]]

^<<v40-9-27,27>>^ Jesus saiu daquele lugar, e no caminho dois cegos começaram a segui-lo, gritando: — Filho de Davi , tenha pena de nós!

[[v40-9-28]]

^<<v40-9-28,28>>^ Assim que Jesus entrou em casa, os cegos chegaram perto dele. Então ele perguntou: — Vocês creem que eu posso curar vocês? — Sim, senhor! Nós cremos! — responderam eles.

[[v40-9-29]]

^<<v40-9-29,29>>^ Jesus tocou nos olhos deles e disse: — Então que seja feito como vocês creem!

[[v40-9-30]]

^<<v40-9-30,30>>^ E os olhos deles ficaram curados. Aí Jesus ordenou com severidade: — Não contem isso a ninguém!

[[v40-9-31]]

^<<v40-9-31,31>>^ Porém eles foram embora e espalharam as notícias a respeito de Jesus por toda aquela região.

[[v40-9-32]]

^<<v40-9-32,32>>^ Quando eles foram embora, algumas pessoas levaram a Jesus um homem que não podia falar porque estava dominado por um demônio.

[[v40-9-33]]

^<<v40-9-33,33>>^ Logo que o demônio foi expulso, o homem começou a falar. Todos ficaram admirados e afirmavam: — Nunca vimos em Israel uma coisa assim!

[[v40-9-34]]

^<<v40-9-34,34>>^ Mas os fariseus  diziam: — O chefe dos demônios é quem dá a esse homem poder para expulsar demônios.

[[v40-9-35]]

^<<v40-9-35,35>>^ Jesus andava visitando todas as cidades e povoados. Ele ensinava nas sinagogas , anunciava a boa notícia sobre o Reino  e curava todo tipo de enfermidades e doenças graves das pessoas.

[[v40-9-36]]

^<<v40-9-36,36>>^ Quando Jesus viu a multidão, ficou com muita pena daquela gente porque eles estavam aflitos e abandonados, como ovelhas sem pastor.

[[v40-9-37]]

^<<v40-9-37,37>>^ Então disse aos discípulos: — A colheita é grande mesmo, mas os trabalhadores são poucos.

[[v40-9-38]]

^<<v40-9-38,38>>^ Peçam ao dono da plantação que mande mais trabalhadores para fazerem a colheita.

'''

xref:040-mateus/040-mateus-008.adoc#v40-8-0[&#60; Capítulo Anterior] | <<v40-9-0,Topo>> | xref:040-mateus/040-mateus-010.adoc#v40-10-0[Próximo Capítulo &#62;]