include::./index.adoc[]

[[v40-17-0]]
=== Mateus, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-17-1]]

^<<v40-17-1,1>>^ Seis dias depois, Jesus foi para um monte alto, levando consigo somente Pedro e os irmãos Tiago e João.

[[v40-17-2]]

^<<v40-17-2,2>>^ Ali, eles viram a aparência de Jesus mudar: o seu rosto ficou brilhante como o sol, e as suas roupas ficaram brancas como a luz.

[[v40-17-3]]

^<<v40-17-3,3>>^ E os três discípulos viram Moisés e Elias conversando com Jesus.

[[v40-17-4]]

^<<v40-17-4,4>>^ Então Pedro disse a Jesus: — Como é bom estarmos aqui, Senhor! Se o senhor quiser, eu armarei três barracas neste lugar: uma para o senhor, outra para Moisés e outra para Elias.

[[v40-17-5]]

^<<v40-17-5,5>>^ Enquanto Pedro estava falando, uma nuvem brilhante os cobriu, e dela veio uma voz, que disse: — Este é o meu Filho querido, que me dá muita alegria. Escutem o que ele diz!

[[v40-17-6]]

^<<v40-17-6,6>>^ Quando os discípulos ouviram a voz, ficaram com tanto medo, que se ajoelharam e encostaram o rosto no chão.

[[v40-17-7]]

^<<v40-17-7,7>>^ Jesus veio, tocou neles e disse: — Levantem-se e não tenham medo!

[[v40-17-8]]

^<<v40-17-8,8>>^ Então eles olharam em volta e não viram ninguém, a não ser Jesus.

[[v40-17-9]]

^<<v40-17-9,9>>^ Quando estavam descendo do monte, ele lhes deu esta ordem: — Não contem para ninguém o que viram até que o Filho do Homem  seja ressuscitado.

[[v40-17-10]]

^<<v40-17-10,10>>^ Então os discípulos perguntaram: — Por que os mestres  da Lei dizem que Elias deve vir primeiro?

[[v40-17-11]]

^<<v40-17-11,11>>^ Ele respondeu: — É verdade que Elias vem para preparar tudo;

[[v40-17-12]]

^<<v40-17-12,12>>^ porém eu afirmo a vocês que Elias já veio, e não o reconheceram, mas o maltrataram como quiseram. Assim também maltratarão o Filho do Homem.

[[v40-17-13]]

^<<v40-17-13,13>>^ Então os discípulos entenderam que Jesus estava falando a respeito de João Batista.

[[v40-17-14]]

^<<v40-17-14,14>>^ Quando eles chegaram perto da multidão, um homem foi até perto de Jesus, ajoelhou-se diante dele

[[v40-17-15]]

^<<v40-17-15,15>>^ e disse: — Senhor, tenha pena do meu filho! Ele é epilético e tem ataques tão fortes, que muitas vezes cai no fogo ou na água.

[[v40-17-16]]

^<<v40-17-16,16>>^ Eu o trouxe para os seus discípulos a fim de que eles o curassem, mas eles não conseguiram.

[[v40-17-17]]

^<<v40-17-17,17>>^ Jesus respondeu: — Gente má e sem fé! Até quando ficarei com vocês? Até quando terei de aguentá-los? Tragam o menino aqui!

[[v40-17-18]]

^<<v40-17-18,18>>^ Então deu uma ordem, o demônio saiu, e no mesmo instante o menino ficou curado.

[[v40-17-19]]

^<<v40-17-19,19>>^ Depois os discípulos chegaram perto de Jesus, em particular, e perguntaram: — Por que foi que nós não pudemos expulsar aquele demônio?

[[v40-17-20]]

^<<v40-17-20,20>>^ Jesus respondeu: — Foi porque vocês não têm bastante fé. Eu afirmo a vocês que isto é verdade: se vocês tivessem fé, mesmo que fosse do tamanho de uma semente de mostarda, poderiam dizer a este monte: "Saia daqui e vá para lá", e ele iria. E vocês teriam poder para fazer qualquer coisa!

[[v40-17-21]]

^<<v40-17-21,21>>^ [Mas esse tipo de demônio só pode ser expulso com oração e jejum.]

[[v40-17-22]]

^<<v40-17-22,22>>^ Um dia os discípulos estavam se reunindo na Galileia, e Jesus disse a eles: — O Filho do Homem  será entregue nas mãos dos homens,

[[v40-17-23]]

^<<v40-17-23,23>>^ e eles vão matá-lo; mas três dias depois ele será ressuscitado. E os discípulos ficaram muito tristes.

[[v40-17-24]]

^<<v40-17-24,24>>^ Quando Jesus e os discípulos chegaram à cidade de Cafarnaum, os cobradores do imposto do Templo foram perguntar a Pedro: — O mestre de vocês não paga o imposto do Templo?

[[v40-17-25]]

^<<v40-17-25,25>>^ — Paga, sim! — respondeu Pedro. Depois Pedro entrou em casa, mas, antes que falasse alguma coisa, Jesus disse: — Simão, o que é que você acha? Quem paga impostos e taxas aos reis deste mundo? São os cidadãos do país ou são os estrangeiros?

[[v40-17-26]]

^<<v40-17-26,26>>^ — São os estrangeiros! — respondeu Pedro. — Certo!  — disse Jesus. — Isso quer dizer que os cidadãos não precisam pagar.

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas nós não queremos ofender essa gente. Por isso vá até o lago, jogue o anzol e puxe o primeiro peixe que você fisgar. Na boca dele você encontrará uma moeda. Então vá e pague com ela o meu imposto e o seu.

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]