include::./index.adoc[]

[[v40-21-0]]
=== Mateus, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-21-1]]

^<<v40-21-1,1>>^ Quando Jesus e os discípulos estavam chegando a Jerusalém, pararam no povoado de Betfagé, que fica perto do monte das Oliveiras. Dali Jesus enviou dois discípulos na frente,

[[v40-21-2]]

^<<v40-21-2,2>>^ com a seguinte ordem: — Vão até o povoado que fica ali adiante e, logo que vocês entrarem lá, encontrarão uma jumenta presa e um jumentinho com ela. Desamarrem os dois e os tragam aqui.

[[v40-21-3]]

^<<v40-21-3,3>>^ Se alguém falar alguma coisa, digam que o Mestre precisa deles. Assim deixarão vocês trazerem logo os animais.

[[v40-21-4]]

^<<v40-21-4,4>>^ Isso aconteceu para se cumprir o que o profeta  tinha dito:

[[v40-21-5]]

^<<v40-21-5,5>>^ "Digam ao povo de Jerusalém: Agora o seu rei está chegando. Ele é humilde e está montado num jumento e num jumentinho, filho de jumenta."

[[v40-21-6]]

^<<v40-21-6,6>>^ Então os discípulos foram e fizeram o que Jesus havia mandado.

[[v40-21-7]]

^<<v40-21-7,7>>^ Levaram a jumenta e o jumentinho, jogaram as suas capas  sobre eles, e Jesus montou.

[[v40-21-8]]

^<<v40-21-8,8>>^ Da grande multidão que ia com eles, alguns estendiam as suas capas no chão, e outros espalhavam no chão ramos que tinham cortado das árvores.

[[v40-21-9]]

^<<v40-21-9,9>>^ Tanto os que iam na frente como os que vinham atrás começaram a gritar: — Hosana  ao Filho de Davi ! Que Deus abençoe aquele que vem em nome do Senhor! Hosana a Deus nas alturas do céu!

[[v40-21-10]]

^<<v40-21-10,10>>^ Quando Jesus entrou em Jerusalém, toda a cidade ficou agitada, e o povo perguntava: — Quem é ele?

[[v40-21-11]]

^<<v40-21-11,11>>^ A multidão respondia: — Este é o profeta  Jesus, de Nazaré da Galileia.

[[v40-21-12]]

^<<v40-21-12,12>>^ Jesus entrou no pátio do Templo e expulsou todos os que compravam e vendiam naquele lugar. Derrubou as mesas dos que trocavam dinheiro e as cadeiras dos que vendiam pombas.

[[v40-21-13]]

^<<v40-21-13,13>>^ Ele lhes disse: — Nas Escrituras Sagradas  está escrito que Deus disse o seguinte: "A minha casa será chamada de ‘Casa de Oração’." Mas vocês a transformaram num esconderijo de ladrões!

[[v40-21-14]]

^<<v40-21-14,14>>^ Cegos e coxos iam encontrar Jesus no pátio do Templo, e ele os curava.

[[v40-21-15]]

^<<v40-21-15,15>>^ Os chefes dos sacerdotes e os mestres  da Lei ficaram zangados quando viram as coisas maravilhosas que ele fazia e ouviram as crianças gritando no pátio do Templo: — Hosana  ao Filho de Davi !

[[v40-21-16]]

^<<v40-21-16,16>>^ E eles disseram a Jesus: — Você está ouvindo o que estão dizendo? Jesus respondeu: — Claro que sim! Será que vocês nunca leram a passagem das Escrituras Sagradas que diz: "Deus ensinou as crianças e as criancinhas a oferecerem o louvor perfeito"?

[[v40-21-17]]

^<<v40-21-17,17>>^ Então Jesus os deixou, saiu da cidade e foi para o povoado de Betânia. E passou a noite ali.

[[v40-21-18]]

^<<v40-21-18,18>>^ No dia seguinte, quando estava voltando para a cidade, Jesus teve fome.

[[v40-21-19]]

^<<v40-21-19,19>>^ Ele viu uma figueira na beira da estrada e foi até lá, mas não encontrou nada; só folhas. Aí disse para a figueira: — Nunca mais dê figos! E na mesma hora a figueira secou.

[[v40-21-20]]

^<<v40-21-20,20>>^ Os discípulos viram isso, ficaram muito admirados e disseram: — Como a figueira secou depressa!

[[v40-21-21]]

^<<v40-21-21,21>>^ Então Jesus disse: — Eu afirmo a vocês que isto é verdade: se tiverem fé e não duvidarem, vocês poderão fazer a mesma coisa que eu fiz com esta figueira. E não somente isso, mas vocês poderão dizer a este monte: "Levante-se e jogue-se no mar", e isso acontecerá.

[[v40-21-22]]

^<<v40-21-22,22>>^ Se crerem, receberão tudo o que pedirem em oração.

[[v40-21-23]]

^<<v40-21-23,23>>^ Jesus chegou ao Templo, e, quando já estava ensinando, alguns chefes dos sacerdotes e alguns líderes judeus chegaram perto dele e perguntaram: — Com que autoridade você faz essas coisas? Quem lhe deu essa autoridade?

[[v40-21-24]]

^<<v40-21-24,24>>^ Jesus respondeu: — Eu também vou fazer uma pergunta a vocês. Se me derem a resposta certa, eu direi com que autoridade faço essas coisas.

[[v40-21-25]]

^<<v40-21-25,25>>^ Respondam: quem deu autoridade a João para batizar? Foi Deus ou foram pessoas? Aí eles começaram a dizer uns aos outros: — Se dissermos que foi Deus, ele vai perguntar: "Então por que vocês não creram em João?"

[[v40-21-26]]

^<<v40-21-26,26>>^ Mas, se dissermos que foram pessoas, temos medo do que o povo pode fazer, pois todos acham que João era profeta .

[[v40-21-27]]

^<<v40-21-27,27>>^ Por isso responderam: — Não sabemos. — Então eu também não digo com que autoridade faço essas coisas!  — disse Jesus.

[[v40-21-28]]

^<<v40-21-28,28>>^ Jesus continuou: — E o que é que vocês acham disto? Certo homem tinha dois filhos. Ele foi falar com o mais velho e disse: "Filho, hoje você vai trabalhar na minha plantação de uvas."

[[v40-21-29]]

^<<v40-21-29,29>>^ — Ele respondeu: "Eu não quero ir." Mas depois mudou de ideia e foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ — O pai foi e deu ao outro filho a mesma ordem. E este disse: "Sim, senhor." Mas depois não foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ — Qual deles fez o que o pai queria?  — perguntou Jesus. E eles responderam: — O filho mais velho. Então Jesus disse a eles: — Eu afirmo a vocês que isto é verdade: os cobradores de impostos e as prostitutas estão entrando no Reino de Deus  antes de vocês.

[[v40-21-32]]

^<<v40-21-32,32>>^ Pois João Batista veio para mostrar a vocês o caminho certo, e vocês não creram nele; mas os cobradores de impostos e as prostitutas creram. Porém, mesmo tendo visto isso, vocês não se arrependeram e não creram nele.

[[v40-21-33]]

^<<v40-21-33,33>>^ Jesus disse: — Escutem outra parábola : certo agricultor fez uma plantação de uvas e pôs uma cerca em volta dela. Construiu um tanque para pisar as uvas e fazer vinho e construiu uma torre para o vigia. Em seguida, arrendou a plantação para alguns lavradores e foi viajar.

[[v40-21-34]]

^<<v40-21-34,34>>^ Quando chegou o tempo da colheita, o dono mandou alguns empregados a fim de receber a parte dele.

[[v40-21-35]]

^<<v40-21-35,35>>^ Mas os lavradores agarraram os empregados, bateram num, assassinaram outro e mataram ainda outro a pedradas.

[[v40-21-36]]

^<<v40-21-36,36>>^ Aí o dono mandou mais empregados do que da primeira vez. E os lavradores fizeram a mesma coisa.

[[v40-21-37]]

^<<v40-21-37,37>>^ Depois de tudo isso, ele mandou o seu próprio filho, pensando: "O meu filho eles vão respeitar."

[[v40-21-38]]

^<<v40-21-38,38>>^ Mas, quando os lavradores viram o filho, disseram uns aos outros: "Este é o filho do dono; ele vai herdar a plantação. Vamos matá-lo, e a plantação será nossa."

[[v40-21-39]]

^<<v40-21-39,39>>^ — Então agarraram o filho, e o jogaram para fora da plantação, e o mataram.

[[v40-21-40]]

^<<v40-21-40,40>>^ Aí Jesus perguntou: — E agora, quando o dono da plantação voltar, o que é que ele vai fazer com aqueles lavradores?

[[v40-21-41]]

^<<v40-21-41,41>>^ Eles responderam: — Com certeza ele vai matar aqueles lavradores maus e vai arrendar a plantação a outros. E estes lhe darão a parte da colheita no tempo certo.

[[v40-21-42]]

^<<v40-21-42,42>>^ Jesus então perguntou: — Vocês não leram o que as Escrituras Sagradas  dizem? "A pedra que os construtores rejeitaram veio a ser a mais importante de todas. Isso foi feito pelo Senhor e é uma coisa maravilhosa!"

[[v40-21-43]]

^<<v40-21-43,43>>^ E Jesus terminou: — Eu afirmo a vocês que o Reino de Deus  será tirado de vocês e será dado para as pessoas que produzem os frutos do Reino.

[[v40-21-44]]

^<<v40-21-44,44>>^ Quem cair em cima dessa pedra ficará em pedaços. E, se a pedra cair sobre alguém, essa pessoa vai virar pó.

[[v40-21-45]]

^<<v40-21-45,45>>^ Os chefes dos sacerdotes e os fariseus  ouviram as parábolas que Jesus contou e sabiam que ele estava falando a respeito deles.

[[v40-21-46]]

^<<v40-21-46,46>>^ Por isso queriam prendê-lo, mas tinham medo da multidão porque o povo achava que Jesus era profeta .

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]