include::./index.adoc[]

[[v40-19-0]]
=== Mateus, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-19-1]]

^<<v40-19-1,1>>^ Depois de dizer isso, Jesus saiu da Galileia e foi para a região da Judeia que fica no lado leste do rio Jordão.

[[v40-19-2]]

^<<v40-19-2,2>>^ Uma grande multidão o seguiu, e ali ele curou os doentes.

[[v40-19-3]]

^<<v40-19-3,3>>^ Alguns fariseus  chegaram perto dele e, querendo conseguir alguma prova contra ele, perguntaram: — Será que pela nossa Lei  um homem pode, por qualquer motivo, mandar a sua esposa embora?

[[v40-19-4]]

^<<v40-19-4,4>>^ Jesus respondeu: — Por acaso vocês não leram o trecho das Escrituras  que diz: "No começo o Criador os fez homem e mulher"?

[[v40-19-5]]

^<<v40-19-5,5>>^ E Deus disse: "Por isso o homem deixa o seu pai e a sua mãe para se unir com a sua mulher, e os dois se tornam uma só pessoa."

[[v40-19-6]]

^<<v40-19-6,6>>^ Assim já não são duas pessoas, mas uma só. Portanto, que ninguém separe o que Deus uniu.

[[v40-19-7]]

^<<v40-19-7,7>>^ Os fariseus perguntaram: — Nesse caso, por que é que Moisés permitiu ao homem mandar a sua esposa embora se der a ela um documento de divórcio?

[[v40-19-8]]

^<<v40-19-8,8>>^ Jesus respondeu: — Moisés deu essa permissão por causa da dureza do coração de vocês; mas no princípio da criação não era assim.

[[v40-19-9]]

^<<v40-19-9,9>>^ Portanto, eu afirmo a vocês o seguinte: o homem que mandar a sua esposa embora, a não ser em caso de adultério, se tornará adúltero se casar com outra mulher.

[[v40-19-10]]

^<<v40-19-10,10>>^ Os discípulos de Jesus disseram: — Se é esta a situação entre o homem e a sua esposa, então é melhor não casar.

[[v40-19-11]]

^<<v40-19-11,11>>^ Jesus respondeu: — Este ensinamento não é para todos, mas somente para aqueles a quem Deus o tem dado.

[[v40-19-12]]

^<<v40-19-12,12>>^ Pois há razões diferentes que tornam alguns homens incapazes para o casamento: uns, porque nasceram assim; outros, porque foram castrados; e outros ainda não casam por causa do Reino do Céu . Quem puder, que aceite este ensinamento.

[[v40-19-13]]

^<<v40-19-13,13>>^ Depois disso, algumas pessoas levaram as suas crianças para Jesus pôr as mãos sobre elas e orar, mas os discípulos repreenderam as pessoas que fizeram isso.

[[v40-19-14]]

^<<v40-19-14,14>>^ Aí ele disse: — Deixem que as crianças venham a mim e não proíbam que elas façam isso, pois o Reino do Céu  é das pessoas que são como estas crianças.

[[v40-19-15]]

^<<v40-19-15,15>>^ Então Jesus pôs as mãos sobre elas e foi embora.

[[v40-19-16]]

^<<v40-19-16,16>>^ Certa vez um homem chegou perto de Jesus e perguntou: — Mestre, o que devo fazer de bom para conseguir a vida eterna?

[[v40-19-17]]

^<<v40-19-17,17>>^ Jesus respondeu: — Por que é que você está me perguntando a respeito do que é bom? Bom só existe um. Se você quer entrar na vida eterna, guarde os mandamentos.

[[v40-19-18]]

^<<v40-19-18,18>>^ — Que mandamentos? — perguntou ele. Jesus respondeu: — "Não mate, não cometa adultério, não roube, não dê falso testemunho contra ninguém,

[[v40-19-19]]

^<<v40-19-19,19>>^ respeite o seu pai e a sua mãe e ame os outros como você ama a você mesmo."

[[v40-19-20]]

^<<v40-19-20,20>>^ — Eu tenho obedecido a todos esses mandamentos! — respondeu o moço. — O que mais me falta fazer?

[[v40-19-21]]

^<<v40-19-21,21>>^ Jesus respondeu: — Se você quer ser perfeito, vá, venda tudo o que tem, e dê o dinheiro aos pobres, e assim você terá riquezas no céu. Depois venha e me siga.

[[v40-19-22]]

^<<v40-19-22,22>>^ Quando o moço ouviu isso, foi embora triste, pois era muito rico.

[[v40-19-23]]

^<<v40-19-23,23>>^ Jesus então disse aos discípulos: — Eu afirmo a vocês que isto é verdade: é muito difícil um rico entrar no Reino do Céu .

[[v40-19-24]]

^<<v40-19-24,24>>^ E digo ainda que é mais difícil um rico entrar no Reino de Deus do que um camelo passar pelo fundo de uma agulha.

[[v40-19-25]]

^<<v40-19-25,25>>^ Quando ouviram isso, os discípulos ficaram muito admirados e perguntavam: — Então, quem é que pode se salvar?

[[v40-19-26]]

^<<v40-19-26,26>>^ Jesus olhou para eles e respondeu: — Para os seres humanos isso não é possível; mas, para Deus, tudo é possível.

[[v40-19-27]]

^<<v40-19-27,27>>^ Aí Pedro disse: — Veja! Nós deixamos tudo e seguimos o senhor. O que é que nós vamos ganhar?

[[v40-19-28]]

^<<v40-19-28,28>>^ Jesus respondeu: — Eu afirmo a vocês que isto é verdade: quando chegar o tempo em que Deus vai renovar tudo e o Filho do Homem  se sentar no seu trono glorioso , vocês, os meus discípulos, também vão sentar-se em doze tronos para julgar as doze tribos  do povo de Israel.

[[v40-19-29]]

^<<v40-19-29,29>>^ E todos os que, por minha causa, deixarem casas, irmãos, irmãs, pai, mãe, filhos ou terras receberão cem vezes mais e também a vida eterna.

[[v40-19-30]]

^<<v40-19-30,30>>^ Muitos que agora são os primeiros serão os últimos, e muitos que agora são os últimos serão os primeiros.

'''

xref:040-mateus/040-mateus-018.adoc#v40-18-0[&#60; Capítulo Anterior] | <<v40-19-0,Topo>> | xref:040-mateus/040-mateus-020.adoc#v40-20-0[Próximo Capítulo &#62;]