include::./index.adoc[]

[[v40-15-0]]
=== Mateus, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-15-1]]

^<<v40-15-1,1>>^ Então alguns fariseus  e alguns mestres  da Lei vieram de Jerusalém para falar com Jesus e lhe perguntaram:

[[v40-15-2]]

^<<v40-15-2,2>>^ — Por que é que os seus discípulos comem sem lavar as mãos, desobedecendo assim aos ensinamentos que recebemos dos antigos?

[[v40-15-3]]

^<<v40-15-3,3>>^ Jesus respondeu: — E por que é que vocês desobedecem ao mandamento de Deus e seguem os seus próprios ensinamentos?

[[v40-15-4]]

^<<v40-15-4,4>>^ Pois Deus disse: "Respeite o seu pai e a sua mãe!" E disse também: "Que seja morto aquele que amaldiçoar o seu pai ou a sua mãe!"

[[v40-15-5]]

^<<v40-15-5,5>>^ Mas vocês ensinam que, se alguém tem alguma coisa que poderia usar para ajudar os seus pais, em sinal de respeito, mas diz: "Eu dediquei isto a Deus",

[[v40-15-6]]

^<<v40-15-6,6>>^ então não precisa ajudar os seus pais. Assim vocês desprezam a mensagem de Deus para seguir os seus próprios ensinamentos.

[[v40-15-7]]

^<<v40-15-7,7>>^ Hipócritas! Isaías estava certo quando disse a respeito de vocês o seguinte:

[[v40-15-8]]

^<<v40-15-8,8>>^ "Deus disse: Este povo com a sua boca diz que me respeita, mas na verdade o seu coração está longe de mim.

[[v40-15-9]]

^<<v40-15-9,9>>^ A adoração deste povo é inútil, pois eles ensinam leis  humanas como se fossem meus mandamentos."

[[v40-15-10]]

^<<v40-15-10,10>>^ Jesus chamou a multidão e disse: — Escutem e entendam!

[[v40-15-11]]

^<<v40-15-11,11>>^ Não é o que entra pela boca que faz com que alguém fique impuro . Pelo contrário, o que sai da boca é que pode tornar a pessoa impura.

[[v40-15-12]]

^<<v40-15-12,12>>^ Então os discípulos chegaram perto dele e disseram: — Sabe que os fariseus  ficaram escandalizados com o que o senhor disse?

[[v40-15-13]]

^<<v40-15-13,13>>^ Jesus respondeu: — Toda planta que o meu Pai, que está no céu, não plantou será arrancada.

[[v40-15-14]]

^<<v40-15-14,14>>^ Não se preocupem com os fariseus. São guias cegos. E, quando um cego guia outro, os dois acabam caindo num buraco.

[[v40-15-15]]

^<<v40-15-15,15>>^ Então Pedro pediu: — Explique para nós aquilo que o senhor disse antes.

[[v40-15-16]]

^<<v40-15-16,16>>^ Jesus disse: — Vocês também ainda não entenderam?

[[v40-15-17]]

^<<v40-15-17,17>>^ O que entra pela boca vai para o estômago e depois sai do corpo.

[[v40-15-18]]

^<<v40-15-18,18>>^ Mas o que sai da boca vem do coração. É isso que faz com que a pessoa fique impura.

[[v40-15-19]]

^<<v40-15-19,19>>^ Porque é do coração que vêm os maus pensamentos, os crimes de morte, os adultérios, as imoralidades sexuais, os roubos, as mentiras e as calúnias.

[[v40-15-20]]

^<<v40-15-20,20>>^ São essas coisas que fazem com que alguém fique impuro. Mas comer sem lavar as mãos não torna ninguém impuro.

[[v40-15-21]]

^<<v40-15-21,21>>^ Jesus saiu dali e foi para a região que fica perto das cidades de Tiro e de Sidom .

[[v40-15-22]]

^<<v40-15-22,22>>^ Certa mulher cananeia, que morava naquela terra, chegou perto dele e gritou: — Senhor, Filho de Davi , tenha pena de mim! A minha filha está horrivelmente dominada por um demônio!

[[v40-15-23]]

^<<v40-15-23,23>>^ Mas Jesus não respondeu nada. Então os discípulos chegaram perto dele e disseram: — Mande essa mulher embora, pois ela está vindo atrás de nós, fazendo muito barulho!

[[v40-15-24]]

^<<v40-15-24,24>>^ Jesus respondeu: — Eu fui mandado somente para as ovelhas perdidas do povo de Israel.

[[v40-15-25]]

^<<v40-15-25,25>>^ Então ela veio, ajoelhou-se aos pés dele e disse: — Senhor, me ajude!

[[v40-15-26]]

^<<v40-15-26,26>>^ Jesus disse: — Não está certo tirar o pão dos filhos e jogá-lo para os cachorros.

[[v40-15-27]]

^<<v40-15-27,27>>^ — Sim, senhor, — respondeu a mulher — mas até mesmo os cachorrinhos comem as migalhas que caem debaixo da mesa dos seus donos.

[[v40-15-28]]

^<<v40-15-28,28>>^ — Mulher, você tem muita fé!  — disse Jesus. — Que seja feito o que você quer! E naquele momento a filha dela ficou curada.

[[v40-15-29]]

^<<v40-15-29,29>>^ Jesus saiu dali e foi até o lago da Galileia. Depois subiu um monte e sentou-se ali.

[[v40-15-30]]

^<<v40-15-30,30>>^ E foram até Jesus grandes multidões levando coxos, aleijados, cegos, mudos e muitos outros doentes, que eram colocados aos seus pés. E ele curou todos.

[[v40-15-31]]

^<<v40-15-31,31>>^ O povo ficou admirado quando viu que os mudos falavam, os aleijados estavam curados, os coxos andavam e os cegos enxergavam. E todo o povo louvou ao Deus de Israel.

[[v40-15-32]]

^<<v40-15-32,32>>^ Jesus chamou os seus discípulos e disse: — Estou com pena dessa gente porque já faz três dias que eles estão comigo e não têm nada para comer. Não quero mandá-los embora com fome, pois poderiam cair de fraqueza pelo caminho.

[[v40-15-33]]

^<<v40-15-33,33>>^ Os discípulos perguntaram: — Como vamos encontrar, neste lugar deserto, comida que dê para toda essa gente?

[[v40-15-34]]

^<<v40-15-34,34>>^ — Quantos pães vocês têm?  — perguntou Jesus. — Sete pães e alguns peixinhos! — responderam eles.

[[v40-15-35]]

^<<v40-15-35,35>>^ Aí Jesus mandou o povo sentar-se no chão.

[[v40-15-36]]

^<<v40-15-36,36>>^ Depois pegou os sete pães e os peixes e deu graças a Deus. Então os partiu e os entregou aos discípulos, e eles os distribuíram ao povo.

[[v40-15-37]]

^<<v40-15-37,37>>^ Todos comeram e ficaram satisfeitos; e os discípulos ainda encheram sete cestos com os pedaços que sobraram.

[[v40-15-38]]

^<<v40-15-38,38>>^ Os que comeram foram quatro mil homens, sem contar as mulheres e as crianças.

[[v40-15-39]]

^<<v40-15-39,39>>^ Então Jesus mandou o povo embora, subiu no barco e foi para a região de Magadã .

'''

xref:040-mateus/040-mateus-014.adoc#v40-14-0[&#60; Capítulo Anterior] | <<v40-15-0,Topo>> | xref:040-mateus/040-mateus-016.adoc#v40-16-0[Próximo Capítulo &#62;]