include::./index.adoc[]

[[v40-18-0]]
=== Mateus, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-18-1]]

^<<v40-18-1,1>>^ Naquele momento os discípulos chegaram perto de Jesus e perguntaram: — Quem é o mais importante no Reino do Céu ?

[[v40-18-2]]

^<<v40-18-2,2>>^ Jesus chamou uma criança, colocou-a na frente deles

[[v40-18-3]]

^<<v40-18-3,3>>^ e disse: — Eu afirmo a vocês que isto é verdade: se vocês não mudarem de vida e não ficarem iguais às crianças, nunca entrarão no Reino do Céu.

[[v40-18-4]]

^<<v40-18-4,4>>^ A pessoa mais importante no Reino do Céu é aquela que se humilha e fica igual a esta criança.

[[v40-18-5]]

^<<v40-18-5,5>>^ E aquele que, por ser meu seguidor, receber uma criança como esta estará recebendo a mim.

[[v40-18-6]]

^<<v40-18-6,6>>^ — Quanto a estes pequeninos que creem em mim , se alguém for culpado de um deles me abandonar, seria melhor para essa pessoa que ela fosse jogada no lugar mais fundo do mar, com uma pedra grande amarrada no pescoço.

[[v40-18-7]]

^<<v40-18-7,7>>^ Ai do mundo por causa das coisas que fazem com que as pessoas me abandonem! Essas coisas têm de acontecer, mas ai do culpado!

[[v40-18-8]]

^<<v40-18-8,8>>^ — Se uma das suas mãos ou um dos seus pés faz com que você peque, corte-o e jogue fora! Pois é melhor você entrar na vida eterna sem uma das mãos ou sem um dos pés do que ter as duas mãos e os dois pés e ser jogado no fogo eterno.

[[v40-18-9]]

^<<v40-18-9,9>>^ Se um dos seus olhos faz com que você peque, arranque-o e jogue fora! Pois é melhor você entrar na vida eterna com um olho só do que ter os dois e ser jogado no fogo do inferno.

[[v40-18-10]]

^<<v40-18-10,10>>^ — Cuidado, não desprezem nenhum destes pequeninos! Eu afirmo a vocês que os anjos deles estão sempre na presença do meu Pai, que está no céu.

[[v40-18-11]]

^<<v40-18-11,11>>^ [Porque o Filho do Homem  veio salvar quem está perdido.]

[[v40-18-12]]

^<<v40-18-12,12>>^ — O que é que vocês acham que faz um homem que tem cem ovelhas, e uma delas se perde? Será que não deixa as noventa e nove pastando no monte e vai procurar a ovelha perdida?

[[v40-18-13]]

^<<v40-18-13,13>>^ Eu afirmo a vocês que isto é verdade: quando ele a encontrar, ficará muito mais contente por causa dessa ovelha do que pelas noventa e nove que não se perderam.

[[v40-18-14]]

^<<v40-18-14,14>>^ Assim também o Pai de vocês, que está no céu, não quer que nenhum destes pequeninos se perca.

[[v40-18-15]]

^<<v40-18-15,15>>^ — Se o seu irmão pecar contra você, vá e mostre-lhe o seu erro. Mas faça isso em particular, só entre vocês dois. Se essa pessoa ouvir o seu conselho, então você ganhou de volta o seu irmão.

[[v40-18-16]]

^<<v40-18-16,16>>^ Mas, se não ouvir, leve com você uma ou duas pessoas, para fazer o que mandam as Escrituras Sagradas . Elas dizem: "Qualquer acusação precisa ser confirmada pela palavra de pelo menos duas testemunhas."

[[v40-18-17]]

^<<v40-18-17,17>>^ Mas, se a pessoa que pecou não ouvir essas pessoas, então conte tudo à igreja. E, se ela não ouvir a igreja, trate-a como um pagão ou como um cobrador de impostos.

[[v40-18-18]]

^<<v40-18-18,18>>^ — Eu afirmo a vocês que isto é verdade: o que vocês proibirem na terra será proibido no céu, e o que permitirem na terra será permitido no céu.

[[v40-18-19]]

^<<v40-18-19,19>>^ — E afirmo a vocês que isto também é verdade: todas as vezes que dois de vocês que estão na terra pedirem a mesma coisa em oração, isso será feito pelo meu Pai, que está no céu.

[[v40-18-20]]

^<<v40-18-20,20>>^ Porque, onde dois ou três estão juntos em meu nome, eu estou ali com eles.

[[v40-18-21]]

^<<v40-18-21,21>>^ Então Pedro chegou perto de Jesus e perguntou: — Senhor, quantas vezes devo perdoar o meu irmão que peca contra mim? Sete vezes?

[[v40-18-22]]

^<<v40-18-22,22>>^ — Não!  — respondeu Jesus. — Você não deve perdoar sete vezes, mas setenta e sete vezes.

[[v40-18-23]]

^<<v40-18-23,23>>^ Porque o Reino do Céu  é como um rei que resolveu fazer um acerto de contas com os seus empregados.

[[v40-18-24]]

^<<v40-18-24,24>>^ Logo no começo trouxeram um que lhe devia milhões de moedas de prata.

[[v40-18-25]]

^<<v40-18-25,25>>^ Mas o empregado não tinha dinheiro para pagar. Então, para pagar a dívida, o seu patrão, o rei, ordenou que fossem vendidos como escravos o empregado, a sua esposa e os seus filhos e que fosse vendido também tudo o que ele possuía.

[[v40-18-26]]

^<<v40-18-26,26>>^ Mas o empregado se ajoelhou diante do patrão e pediu: "Tenha paciência comigo, e eu pagarei tudo ao senhor."

[[v40-18-27]]

^<<v40-18-27,27>>^ — O patrão teve pena dele, perdoou a dívida e deixou que ele fosse embora.

[[v40-18-28]]

^<<v40-18-28,28>>^ O empregado saiu e encontrou um dos seus companheiros de trabalho que lhe devia cem moedas de prata. Ele pegou esse companheiro pelo pescoço e começou a sacudi-lo, dizendo: "Pague o que me deve!"

[[v40-18-29]]

^<<v40-18-29,29>>^ — Então o seu companheiro se ajoelhou e pediu: "Tenha paciência comigo, e eu lhe pagarei tudo."

[[v40-18-30]]

^<<v40-18-30,30>>^ — Mas ele não concordou. Pelo contrário, mandou pôr o outro na cadeia até que pagasse a dívida.

[[v40-18-31]]

^<<v40-18-31,31>>^ Quando os outros empregados viram o que havia acontecido, ficaram revoltados e foram contar tudo ao patrão.

[[v40-18-32]]

^<<v40-18-32,32>>^ Aí o patrão chamou aquele empregado e disse: "Empregado miserável! Você me pediu, e por isso eu perdoei tudo o que você me devia.

[[v40-18-33]]

^<<v40-18-33,33>>^ Portanto, você deveria ter pena do seu companheiro, como eu tive pena de você."

[[v40-18-34]]

^<<v40-18-34,34>>^ — O patrão ficou com muita raiva e mandou o empregado para a cadeia a fim de ser castigado até que pagasse toda a dívida.

[[v40-18-35]]

^<<v40-18-35,35>>^ E Jesus terminou, dizendo: — É isso o que o meu Pai, que está no céu, vai fazer com vocês se cada um não perdoar sinceramente o seu irmão.

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]