include::./index.adoc[]

[[v40-28-0]]
=== Mateus, 28
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-28-1]]

^<<v40-28-1,1>>^ Depois do sábado, no domingo bem cedo, Maria Madalena e a outra Maria foram visitar o túmulo.

[[v40-28-2]]

^<<v40-28-2,2>>^ De repente, houve um grande tremor de terra. Um anjo do Senhor desceu do céu, tirou a pedra e sentou-se nela.

[[v40-28-3]]

^<<v40-28-3,3>>^ Ele era parecido com um relâmpago, e as suas roupas eram brancas como a neve.

[[v40-28-4]]

^<<v40-28-4,4>>^ Os guardas tremeram de medo do anjo e ficaram como mortos.

[[v40-28-5]]

^<<v40-28-5,5>>^ Então o anjo disse para as mulheres: — Não tenham medo! Sei que vocês estão procurando Jesus, que foi crucificado,

[[v40-28-6]]

^<<v40-28-6,6>>^ mas ele não está aqui; já foi ressuscitado, como tinha dito. Venham ver o lugar onde ele foi posto.

[[v40-28-7]]

^<<v40-28-7,7>>^ Agora vão depressa e digam aos discípulos dele o seguinte: "Ele foi ressuscitado e vai adiante de vocês para a Galileia. Lá vocês vão vê-lo." Era isso o que eu tinha a dizer para vocês.

[[v40-28-8]]

^<<v40-28-8,8>>^ Elas foram embora depressa do túmulo, pois estavam com medo, mas muito alegres. E correram para contar tudo aos discípulos.

[[v40-28-9]]

^<<v40-28-9,9>>^ De repente, Jesus se encontrou com elas e disse: — Que a paz esteja com vocês! Elas chegaram perto dele, abraçaram os seus pés e o adoraram.

[[v40-28-10]]

^<<v40-28-10,10>>^ Então Jesus disse: — Não tenham medo! Vão dizer aos meus irmãos para irem à Galileia, e eles me verão ali.

[[v40-28-11]]

^<<v40-28-11,11>>^ Enquanto as mulheres ainda estavam no caminho, alguns dos soldados que estavam vigiando o túmulo voltaram para a cidade e contaram aos chefes dos sacerdotes tudo o que havia acontecido.

[[v40-28-12]]

^<<v40-28-12,12>>^ Os chefes se reuniram com os líderes judeus e fizeram os seus planos. Então deram uma grande quantia de dinheiro aos soldados

[[v40-28-13]]

^<<v40-28-13,13>>^ e ordenaram o seguinte: — Digam que os discípulos dele vieram de noite, quando vocês estavam dormindo, e roubaram o corpo.

[[v40-28-14]]

^<<v40-28-14,14>>^ Se o Governador souber disso, nós vamos convencê-lo de que foi isso mesmo o que aconteceu, e vocês não terão nenhum problema.

[[v40-28-15]]

^<<v40-28-15,15>>^ Os soldados pegaram o dinheiro e fizeram o que os chefes dos sacerdotes tinham mandado. E esse boato se espalhou entre os judeus até o dia de hoje .

[[v40-28-16]]

^<<v40-28-16,16>>^ Os onze discípulos foram para a Galileia e chegaram ao monte que Jesus tinha indicado.

[[v40-28-17]]

^<<v40-28-17,17>>^ E, quando viram Jesus, o adoraram; mas alguns tiveram suas dúvidas.

[[v40-28-18]]

^<<v40-28-18,18>>^ Então Jesus chegou perto deles e disse: — Deus me deu todo o poder no céu e na terra.

[[v40-28-19]]

^<<v40-28-19,19>>^ Portanto, vão a todos os povos do mundo e façam com que sejam meus seguidores, batizando esses seguidores em nome do Pai, do Filho e do Espírito Santo

[[v40-28-20]]

^<<v40-28-20,20>>^ e ensinando-os a obedecer a tudo o que tenho ordenado a vocês. E lembrem disto: eu estou com vocês todos os dias, até o fim dos tempos.

'''

xref:040-mateus/040-mateus-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-marcos/041-marcos-001.adoc#v41-1-0[Próximo Capítulo &#62;]