include::./index.adoc[]

[[v40-4-0]]
=== Mateus, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v40-4-1]]

^<<v40-4-1,1>>^ Então o Espírito Santo levou Jesus ao deserto para ser tentado pelo Diabo.

[[v40-4-2]]

^<<v40-4-2,2>>^ E, depois de passar quarenta dias e quarenta noites sem comer, Jesus estava com fome.

[[v40-4-3]]

^<<v40-4-3,3>>^ Então o Diabo chegou perto dele e disse: — Se você é o Filho de Deus, mande que estas pedras virem pão.

[[v40-4-4]]

^<<v40-4-4,4>>^ Jesus respondeu: — As Escrituras Sagradas  afirmam: "O ser humano não vive só de pão, mas vive de tudo o que Deus diz."

[[v40-4-5]]

^<<v40-4-5,5>>^ Em seguida o Diabo levou Jesus até Jerusalém, a Cidade Santa, e o colocou no lugar mais alto do Templo.

[[v40-4-6]]

^<<v40-4-6,6>>^ Então disse: — Se você é o Filho de Deus, jogue-se daqui, pois as Escrituras Sagradas afirmam: "Deus mandará que os seus anjos cuidem de você. Eles vão segurá-lo com as suas mãos, para que nem mesmo os seus pés sejam feridos nas pedras."

[[v40-4-7]]

^<<v40-4-7,7>>^ Jesus respondeu: — Mas as Escrituras Sagradas também dizem: "Não ponha à prova o Senhor, seu Deus."

[[v40-4-8]]

^<<v40-4-8,8>>^ Depois o Diabo levou Jesus para um monte muito alto, mostrou-lhe todos os reinos do mundo e as suas grandezas

[[v40-4-9]]

^<<v40-4-9,9>>^ e disse: — Eu lhe darei tudo isso se você se ajoelhar e me adorar.

[[v40-4-10]]

^<<v40-4-10,10>>^ Jesus respondeu: — Vá embora, Satanás! As Escrituras Sagradas afirmam: "Adore o Senhor, seu Deus, e sirva somente a ele."

[[v40-4-11]]

^<<v40-4-11,11>>^ Então o Diabo foi embora, e vieram anjos e cuidaram de Jesus.

[[v40-4-12]]

^<<v40-4-12,12>>^ Quando Jesus soube que João tinha sido preso, foi para a região da Galileia.

[[v40-4-13]]

^<<v40-4-13,13>>^ Não ficou em Nazaré, mas foi morar na cidade de Cafarnaum, na beira do lago da Galileia, nas regiões de Zebulom e Naftali .

[[v40-4-14]]

^<<v40-4-14,14>>^ Isso aconteceu para se cumprir o que o profeta  Isaías tinha dito:

[[v40-4-15]]

^<<v40-4-15,15>>^ "Terra de Zebulom e terra de Naftali, na direção do mar, do outro lado do rio Jordão, Galileia, onde moram os pagãos!

[[v40-4-16]]

^<<v40-4-16,16>>^ O povo que vive na escuridão verá uma forte luz! E a luz brilhará sobre os que vivem na região escura da morte!"

[[v40-4-17]]

^<<v40-4-17,17>>^ Daí em diante Jesus começou a anunciar a sua mensagem. Ele dizia: — Arrependam-se dos seus pecados porque o Reino do Céu  está perto!

[[v40-4-18]]

^<<v40-4-18,18>>^ Jesus estava andando pela beira do lago da Galileia quando viu dois irmãos que eram pescadores: Simão, também chamado de Pedro, e André. Eles estavam no lago, pescando com redes.

[[v40-4-19]]

^<<v40-4-19,19>>^ Jesus lhes disse: — Venham comigo, que eu ensinarei vocês a pescar gente.

[[v40-4-20]]

^<<v40-4-20,20>>^ Então eles largaram logo as redes e foram com Jesus.

[[v40-4-21]]

^<<v40-4-21,21>>^ Um pouco mais adiante Jesus viu outros dois irmãos, Tiago e João, filhos de Zebedeu. Eles estavam no barco junto com o pai, consertando as redes. Jesus chamou os dois,

[[v40-4-22]]

^<<v40-4-22,22>>^ e, no mesmo instante, eles deixaram o pai e o barco e foram com ele.

[[v40-4-23]]

^<<v40-4-23,23>>^ Jesus andou por toda a Galileia, ensinando nas sinagogas , anunciando a boa notícia do Reino  e curando as enfermidades e as doenças graves do povo.

[[v40-4-24]]

^<<v40-4-24,24>>^ As notícias a respeito dele se espalharam por toda a região da Síria. Por isso o povo levava a Jesus pessoas que sofriam de várias doenças e de todos os tipos de males, isto é, epiléticos, paralíticos e pessoas dominadas por demônios; e ele curava todos.

[[v40-4-25]]

^<<v40-4-25,25>>^ Grandes multidões o seguiam; eram gente da Galileia, das Dez Cidades , de Jerusalém, da Judeia e das regiões que ficam no lado leste do rio Jordão.

'''

xref:040-mateus/040-mateus-003.adoc#v40-3-0[&#60; Capítulo Anterior] | <<v40-4-0,Topo>> | xref:040-mateus/040-mateus-005.adoc#v40-5-0[Próximo Capítulo &#62;]