include::./index.adoc[]

[[v22-6-0]]
=== Cânticos, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v22-6-1]]

^<<v22-6-1,1>>^ Você, a mais bela das mulheres, responda: para onde foi o seu amado? Que caminho ele seguiu? Nós a ajudaremos a encontrá-lo.

[[v22-6-2]]

^<<v22-6-2,2>>^ O meu amor desceu ao seu jardim, aos canteiros perfumosos. Ele está alimentando as suas ovelhas no jardim e colhendo lírios.

[[v22-6-3]]

^<<v22-6-3,3>>^ Eu sou do meu amado, e o meu amado é meu. Ele leva as suas ovelhas para pastarem entre os lírios.

[[v22-6-4]]

^<<v22-6-4,4>>^ Minha querida, você é bonita como a cidade de Jerusalém, encantadora como a cidade de Tirza e impressionante como essas duas cidades.

[[v22-6-5]]

^<<v22-6-5,5>>^ Desvie de mim os seus olhos, pois eles me perturbam. Os seus cabelos ondulados são como um rebanho de cabras descendo as montanhas de Gileade.

[[v22-6-6]]

^<<v22-6-6,6>>^ Os seus dentes são brancos como ovelhas com a lã cortada, que acabaram de ser lavadas. Nenhum deles está faltando, e todos são bem-alinhados.

[[v22-6-7]]

^<<v22-6-7,7>>^ O seu rosto corado brilha atrás do véu.

[[v22-6-8]]

^<<v22-6-8,8>>^ Pode haver sessenta rainhas, oitenta concubinas e muitas moças;

[[v22-6-9]]

^<<v22-6-9,9>>^ mas eu amo somente uma, aquela que é perfeita como uma pomba. Ela é filha única e a querida da sua mãe. Todas as mulheres olham para a minha amada e dizem que ela é feliz; rainhas e concubinas a elogiam e dizem:

[[v22-6-10]]

^<<v22-6-10,10>>^ "Quem é esta que parece o nascer do dia, que é bela como a lua, brilhante como o sol, impressionante como esses dois astros e luminosa como o céu cheio de estrelas?"

[[v22-6-11]]

^<<v22-6-11,11>>^ Eu desci ao jardim das amendoeiras para olhar as plantas novas do vale, para ver se as parreiras  estavam brotando e se as romãzeiras estavam em flor.

[[v22-6-12]]

^<<v22-6-12,12>>^ Eu estou tremendo. Você me deixou ansioso para amar, tão ansioso como um condutor de carros de guerra para entrar na batalha.

[[v22-6-13]]

^<<v22-6-13,13>>^ Volte, volte, sulamita . Volte, volte; nós queremos ver você dançar. Por que vocês querem me ver dançando a dança da noiva?

'''

xref:022-canticos/022-canticos-005.adoc#v22-5-0[&#60; Capítulo Anterior] | <<v22-6-0,Topo>> | xref:022-canticos/022-canticos-007.adoc#v22-7-0[Próximo Capítulo &#62;]