include::./index.adoc[]

[[v22-8-0]]
=== Cânticos, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v22-8-1]]

^<<v22-8-1,1>>^ Que bom seria se você fosse meu irmão, se tivesse sido amamentado por minha mãe! Então, se eu me encontrasse com você na rua, poderia beijá-lo, e ninguém se importaria.

[[v22-8-2]]

^<<v22-8-2,2>>^ Eu o levaria para a casa da minha mãe, e você me ensinaria. Eu lhe daria vinho com especiarias e o meu vinho de romãs para você beber.

[[v22-8-3]]

^<<v22-8-3,3>>^ A sua mão esquerda estaria debaixo da minha cabeça, e a direita me abraçaria.

[[v22-8-4]]

^<<v22-8-4,4>>^ Prometam, mulheres de Jerusalém, que vocês não vão perturbar o nosso amor.

[[v22-8-5]]

^<<v22-8-5,5>>^ Quem é esta que vem subindo do deserto, de braço dado com o seu querido? Debaixo da macieira, eu acordei você, ali, onde você nasceu, no lugar onde a sua mãe o deu à luz.

[[v22-8-6]]

^<<v22-8-6,6>>^ Grave o meu nome no seu coração e no anel que está no seu dedo. O amor é tão poderoso como a morte; e a paixão é tão forte como a sepultura. O amor e a paixão explodem em chamas e queimam como fogo furioso.

[[v22-8-7]]

^<<v22-8-7,7>>^ Nenhuma quantidade de água pode apagar o amor, e nenhum rio pode afogá-lo. Se alguém quisesse comprar o amor e por ele oferecesse as suas riquezas, receberia somente o desprezo.

[[v22-8-8]]

^<<v22-8-8,8>>^ Nós temos uma irmãzinha que ainda tem seios pequenos. O que faremos por nossa irmãzinha quando um rapaz quiser namorá-la?

[[v22-8-9]]

^<<v22-8-9,9>>^ Se ela for uma muralha, nós a defenderemos com uma torre de prata. Se ela for uma porta, nós a reforçaremos com sarrafos de cedro.

[[v22-8-10]]

^<<v22-8-10,10>>^ Eu sou uma muralha, e os meus seios são as suas torres. Por isso, o meu amado está certo de que estou bem protegida e segura.

[[v22-8-11]]

^<<v22-8-11,11>>^ Salomão tinha uma plantação de uvas num lugar chamado Baal-Hamom. Ele escolheu lavradores para cuidarem dela; cada um tinha de lhe pagar mil barras de prata .

[[v22-8-12]]

^<<v22-8-12,12>>^ Eu também tenho uma plantação de uvas e faço dela o que quero. Salomão, venha receber as suas mil barras. Lavradores, venham receber duzentas barras pelo seu trabalho.

[[v22-8-13]]

^<<v22-8-13,13>>^ Minha querida, os meus companheiros estão querendo ouvi-la. Eu também quero ouvir a sua voz no jardim.

[[v22-8-14]]

^<<v22-8-14,14>>^ Venha depressa, meu amado, correndo como uma gazela , como um filhote de corço , que salta sobre os montes perfumosos.

'''

xref:022-canticos/022-canticos-007.adoc#v22-7-0[&#60; Capítulo Anterior] | <<v22-8-0,Topo>> | xref:023-isaias/023-isaias-001.adoc#v23-1-0[Próximo Capítulo &#62;]