include::./index.adoc[]

[[v22-4-0]]
=== Cânticos, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v22-4-1]]

^<<v22-4-1,1>>^ Como você é bela, minha querida! Como você é linda! Como os seus olhos brilham de amor atrás do véu! Os seus cabelos ondulados são como um rebanho de cabras descendo as montanhas de Gileade.

[[v22-4-2]]

^<<v22-4-2,2>>^ Os seus dentes são brancos como ovelhas com a lã cortada, que acabaram de ser lavadas. Nenhum deles está faltando, e todos são bem-alinhados.

[[v22-4-3]]

^<<v22-4-3,3>>^ Os seus lábios são como uma fita vermelha, e a sua boca é linda. O seu rosto corado brilha atrás do véu.

[[v22-4-4]]

^<<v22-4-4,4>>^ Você tem o pescoço roliço e macio, elegante como a torre de Davi, onde estão pendurados mil escudos , parte das armaduras  de soldados valentes.

[[v22-4-5]]

^<<v22-4-5,5>>^ Os seus seios parecem duas crias, crias gêmeas de uma gazela , pastando entre os lírios.

[[v22-4-6]]

^<<v22-4-6,6>>^ Eu irei até a montanha da mirra, até a montanha do incenso, enquanto o dia ainda está fresco e a escuridão está desaparecendo.

[[v22-4-7]]

^<<v22-4-7,7>>^ Como você é linda, minha querida! Como você é perfeita!

[[v22-4-8]]

^<<v22-4-8,8>>^ Desça comigo dos montes Líbanos, minha noiva! Desça do alto dos montes, do Amana, do Senir e do Hermom, onde vivem os leões e os leopardos.

[[v22-4-9]]

^<<v22-4-9,9>>^ Com um só olhar, minha noiva, meu amor, com uma só pérola do seu colar, você me roubou o coração.

[[v22-4-10]]

^<<v22-4-10,10>>^ Como são deliciosas as suas carícias, minha namorada, minha noiva! O seu amor é melhor do que o vinho; o seu perfume é o mais agradável que existe.

[[v22-4-11]]

^<<v22-4-11,11>>^ Os seus lábios têm gosto de mel, minha querida. A sua língua é para mim como leite e mel, e os seus vestidos têm o cheiro dos montes Líbanos.

[[v22-4-12]]

^<<v22-4-12,12>>^ Minha noiva, meu amor, você é como um jardim cercado e fechado; é uma fonte particular.

[[v22-4-13]]

^<<v22-4-13,13>>^ Nesse jardim as plantas crescem bem. Crescem como um pomar de romãs e dão as melhores frutas. Nele existe hena  e nardo ;

[[v22-4-14]]

^<<v22-4-14,14>>^ existe nardo e açafrão , canela e jasmim-azul e todas as espécies de incenso. Há também mirra e aloés e outras plantas perfumosas.

[[v22-4-15]]

^<<v22-4-15,15>>^ Você é a fonte do meu jardim, a corrente de água doce, o ribeirão que corre dos montes Líbanos.

[[v22-4-16]]

^<<v22-4-16,16>>^ Levante-se, vento norte! Venha, vento sul! Sopre sobre o meu jardim e encha o ar de perfume. Deixe que o meu querido venha ao seu jardim e coma as suas melhores frutas.

'''

xref:022-canticos/022-canticos-003.adoc#v22-3-0[&#60; Capítulo Anterior] | <<v22-4-0,Topo>> | xref:022-canticos/022-canticos-005.adoc#v22-5-0[Próximo Capítulo &#62;]