include::./index.adoc[]

[[v22-5-0]]
=== Cânticos, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v22-5-1]]

^<<v22-5-1,1>>^ Já entrei no meu jardim, minha noiva, minha querida. Estou colhendo mirra  e outras plantas perfumosas; estou comendo o meu favo de mel e bebendo o meu vinho e o meu leite. Vocês que se amam, comam e bebam, até ficarem embriagados de amor!

[[v22-5-2]]

^<<v22-5-2,2>>^ Eu dormia, mas o meu coração estava acordado. Então ouvi o meu amado bater na porta. Deixe-me entrar, minha querida, meu amor, minha pombinha sem defeito. A minha cabeça está molhada de sereno, e o meu cabelo está úmido de orvalho.

[[v22-5-3]]

^<<v22-5-3,3>>^ Eu já tirei a roupa; será que preciso me vestir de novo? Já lavei os pés; por que sujá-los outra vez?

[[v22-5-4]]

^<<v22-5-4,4>>^ O meu amor passou a mão pela abertura da porta, e o meu coração estremeceu.

[[v22-5-5]]

^<<v22-5-5,5>>^ Eu já estava pronta para deixar o meu querido entrar. As minhas mãos estavam cobertas de mirra , e os meus dedos também, e eu segurava o trinco da porta.

[[v22-5-6]]

^<<v22-5-6,6>>^ Então abri a porta para o meu amor, mas ele já havia ido embora. Como eu queria ouvir a sua voz! Procurei-o, porém não o pude achar; chamei-o, mas ele não respondeu.

[[v22-5-7]]

^<<v22-5-7,7>>^ Os guardas que patrulhavam a cidade me encontraram; eles me bateram e me machucaram; e os guardas das muralhas da cidade me arrancaram a capa .

[[v22-5-8]]

^<<v22-5-8,8>>^ Prometam, mulheres de Jerusalém: se vocês encontrarem o meu amado, digam que estou morrendo de amor.

[[v22-5-9]]

^<<v22-5-9,9>>^ Você, a mais bela das mulheres, responda: será que o seu amado é melhor do que os outros? O que é que ele tem de tão maravilhoso para fazermos essa promessa a você?

[[v22-5-10]]

^<<v22-5-10,10>>^ Entre dez mil homens, o meu amado é o mais bonito e o mais forte. O seu belo rosto é corado; os seus cabelos são compridos, e ondulados, e pretos como as penas de um corvo.

[[v22-5-11]]

^<<v22-5-11,11>>^ Entre dez mil homens,

[[v22-5-12]]

^<<v22-5-12,12>>^ Os seus olhos são como os olhos das pombas na beira de um riacho; pombas brancas como leite, banhando-se ao lado da correnteza.

[[v22-5-13]]

^<<v22-5-13,13>>^ O seu rosto é bonito como um jardim de plantas perfumosas. Os seus lábios são como lírios que deixam cair pingos de mirra preciosa.

[[v22-5-14]]

^<<v22-5-14,14>>^ As suas mãos são bem-feitas e enfeitadas com anéis de ouro e pedras preciosas. A sua cintura é como marfim polido, coberto de safiras .

[[v22-5-15]]

^<<v22-5-15,15>>^ As suas pernas são colunas de mármore assentadas sobre bases de ouro puro. O meu amado parece um dos montes Líbanos e é elegante como os cedros.

'''

xref:022-canticos/022-canticos-004.adoc#v22-4-0[&#60; Capítulo Anterior] | <<v22-5-0,Topo>> | xref:022-canticos/022-canticos-006.adoc#v22-6-0[Próximo Capítulo &#62;]