include::./index.adoc[]

[[v22-7-0]]
=== Cânticos, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v22-7-1]]

^<<v22-7-1,1>>^ Ó filha de um príncipe, como são bonitos os seus pés calçados de sandálias! As curvas dos seus quadris são como joias, são trabalho de um artista.

[[v22-7-2]]

^<<v22-7-2,2>>^ O seu umbigo é uma taça onde não falta vinho. A sua cintura é como um feixe de trigo cercado de lírios.

[[v22-7-3]]

^<<v22-7-3,3>>^ Os seus seios parecem duas crias, crias gêmeas de uma gazela .

[[v22-7-4]]

^<<v22-7-4,4>>^ O seu pescoço é como uma torre de marfim. Os seus olhos são como os poços que ficam ao lado dos portões da grande cidade de Hesbom. O seu nariz é tão belo como a torre do Líbano, de onde se avista Damasco.

[[v22-7-5]]

^<<v22-7-5,5>>^ A sua cabeça está sempre erguida como o monte Carmelo. Os seus cabelos são como a púrpura ; até um rei ficaria preso nas suas tranças.

[[v22-7-6]]

^<<v22-7-6,6>>^ Como você é linda, minha querida! Como você me dá prazer! Como é agradável a sua presença!

[[v22-7-7]]

^<<v22-7-7,7>>^ Você é tão graciosa como uma palmeira; os seus seios são como cachos de tâmaras .

[[v22-7-8]]

^<<v22-7-8,8>>^ Vou subir na palmeira e colher os seus frutos. Os seus seios são para mim como cachos de uvas. A sua boca tem o perfume das maçãs,

[[v22-7-9]]

^<<v22-7-9,9>>^ e os seus beijos são como vinho delicioso. Então que o meu querido beba suavemente deste vinho que escorre entre os seus lábios e dentes.

[[v22-7-10]]

^<<v22-7-10,10>>^ Eu sou do meu amado, e ele me quer.

[[v22-7-11]]

^<<v22-7-11,11>>^ Venha, querido, vamos para o campo; vamos passar a noite nas plantações de uvas.

[[v22-7-12]]

^<<v22-7-12,12>>^ Vamos levantar cedo e olhar as parreiras , para ver se elas já começaram a brotar. Veremos se as flores estão se abrindo e se as romãzeiras já estão em flor. Ali eu lhe darei o meu amor.

[[v22-7-13]]

^<<v22-7-13,13>>^ Podemos sentir o perfume das mandrágoras . Todas as frutas saborosas estão na nossa porta. Querido, eu guardei para você todo tipo de frutas, as frutas frescas e as secas.

'''

xref:022-canticos/022-canticos-006.adoc#v22-6-0[&#60; Capítulo Anterior] | <<v22-7-0,Topo>> | xref:022-canticos/022-canticos-008.adoc#v22-8-0[Próximo Capítulo &#62;]