include::./index.adoc[]

[[v17-2-0]]
=== Ester, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v17-2-1]]

^<<v17-2-1,1>>^ Mais tarde a raiva do rei já havia passado, mas mesmo assim ele continuava a pensar no que Vasti havia feito e no decreto que ele havia assinado contra ela.

[[v17-2-2]]

^<<v17-2-2,2>>^ Aí alguns dos seus servidores mais íntimos lhe disseram: — Ó rei, mande buscar as mais lindas virgens do reino.

[[v17-2-3]]

^<<v17-2-3,3>>^ Escolha funcionários em todas as províncias  e ordene que tragam as moças mais bonitas para o seu harém  aqui em Susã, a capital. Hegai, o eunuco  responsável pelo harém real, tomará conta delas e fará com que recebam um tratamento de beleza.

[[v17-2-4]]

^<<v17-2-4,4>>^ E então, ó rei, que a moça que mais lhe agradar seja a rainha no lugar de Vasti. O rei gostou da ideia e fez o que lhe sugeriram.

[[v17-2-5]]

^<<v17-2-5,5>>^ Em Susã morava um judeu chamado Mordecai, filho de Jair e descendente de Simei e de Quis, da tribo  de Benjamim.

[[v17-2-6]]

^<<v17-2-6,6>>^ Quando o rei Nabucodonosor, da Babilônia, levou de Jerusalém como prisioneiro o rei Joaquim, de Judá, Mordecai estava entre os prisioneiros que foram levados com Joaquim.

[[v17-2-7]]

^<<v17-2-7,7>>^ Mordecai levou consigo a sua prima Hadassa, isto é, Ester, uma moça bonita e formosa. Os pais dela tinham morrido, e Mordecai havia adotado a menina e a tinha criado como se ela fosse sua filha.

[[v17-2-8]]

^<<v17-2-8,8>>^ Quando o rei mandou anunciar a ordem, muitas moças foram levadas para Susã, a capital, e entregues aos cuidados de Hegai, o chefe do harém do palácio. Uma dessas moças era Ester.

[[v17-2-9]]

^<<v17-2-9,9>>^ Hegai gostou dela, e ela conquistou a simpatia dele. Imediatamente ele começou a providenciar para ela o tratamento de beleza e a comida especial. Arranjou sete das melhores empregadas do palácio para cuidarem dela e colocou Ester e as empregadas nos melhores quartos do harém.

[[v17-2-10]]

^<<v17-2-10,10>>^ Ester fez conforme Mordecai tinha mandado e não disse nada a ninguém a respeito da sua raça e dos seus parentes.

[[v17-2-11]]

^<<v17-2-11,11>>^ Todos os dias Mordecai passeava em frente do pátio do harém para saber como Ester estava passando e o que ia acontecer com ela.

[[v17-2-12]]

^<<v17-2-12,12>>^ O tratamento de beleza das moças durava um ano; durante seis meses eram usados perfumes de mirra  e, no resto do ano, outros perfumes e produtos de beleza. Terminado o tratamento, cada moça era levada ao rei Xerxes.

[[v17-2-13]]

^<<v17-2-13,13>>^ Quando chegava a sua vez de ir do harém até o palácio, cada moça tinha o direito de levar tudo o que quisesse.

[[v17-2-14]]

^<<v17-2-14,14>>^ À tarde, ela ia ao palácio, e na manhã seguinte ia para outro harém, e era entregue aos cuidados de Saasgaz, o eunuco responsável pelas concubinas  do rei. Ela não voltava a se encontrar com o rei, a não ser que ele gostasse dela e mandasse chamá-la pelo nome.

[[v17-2-15]]

^<<v17-2-15,15>>^ Chegou a vez de Ester, filha de Abiail e prima de Mordecai, a moça que Mordecai tinha criado, a moça que conquistava a simpatia de todos os que a conheciam. Quando chegou a sua vez de se encontrar com o rei, ela levou somente aquilo que Hegai, o eunuco responsável pelo harém, havia recomendado.

[[v17-2-16]]

^<<v17-2-16,16>>^ Ester foi levada ao palácio para apresentar-se ao rei Xerxes no mês de tebete , o décimo mês do sétimo ano do seu reinado.

[[v17-2-17]]

^<<v17-2-17,17>>^ Ele gostou dela mais do que de qualquer outra moça, e ela conquistou a simpatia e a admiração dele como nenhuma outra moça havia feito. Ele colocou a coroa na cabeça dela e a fez rainha no lugar de Vasti.

[[v17-2-18]]

^<<v17-2-18,18>>^ Depois ele deu um grande banquete em honra de Ester e convidou todos os oficiais e servidores. Ele decretou que aquele dia fosse feriado no reino inteiro e distribuiu presentes que só um rei poderia oferecer.

[[v17-2-19]]

^<<v17-2-19,19>>^ Durante o tempo em que as moças estavam sendo transferidas para o outro harém , Mordecai tinha sido nomeado pelo rei para ocupar um cargo no governo.

[[v17-2-20]]

^<<v17-2-20,20>>^ Seguindo o conselho de Mordecai, Ester ainda não tinha dito a ninguém que era judia. Ela continuava a obedecer a Mordecai, como tinha feito nos tempos de menina, quando ele a estava criando.

[[v17-2-21]]

^<<v17-2-21,21>>^ Naqueles dias Mordecai, fazendo o seu serviço no palácio, ficou sabendo que Bigtã e Teres, dois eunucos  que eram guardas no palácio, estavam zangados com o rei e planejavam matá-lo.

[[v17-2-22]]

^<<v17-2-22,22>>^ Aí Mordecai contou isso à rainha Ester, e ela disse ao rei o que Mordecai havia descoberto.

[[v17-2-23]]

^<<v17-2-23,23>>^ Houve uma investigação, e descobriu-se que era verdade; então os dois eunucos foram enforcados. E o rei ordenou que fosse registrado um relatório sobre isso no livro em que se escrevia a história do reino.

'''

xref:017-ester/017-ester-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-ester/017-ester-003.adoc#v17-3-0[Próximo Capítulo &#62;]