include::./index.adoc[]

[[v17-3-0]]
=== Ester, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v17-3-1]]

^<<v17-3-1,1>>^ Depois disso, o rei Xerxes colocou um homem chamado Hamã no cargo de primeiro-ministro. Hamã era filho de Hamedata e descendente de Agague .

[[v17-3-2]]

^<<v17-3-2,2>>^ O rei ordenou que todos os funcionários do palácio se curvassem e se ajoelhassem diante de Hamã em sinal de respeito. E todos os funcionários começaram a fazer isso, menos Mordecai; ele não se curvava, nem se ajoelhava.

[[v17-3-3]]

^<<v17-3-3,3>>^ Aí os outros funcionários perguntaram a Mordecai por que ele não obedecia à ordem do rei.

[[v17-3-4]]

^<<v17-3-4,4>>^ Todos os dias eles insistiam com ele para que obedecesse, mas não adiantava. Ele explicava que não obedecia porque era judeu. Então eles foram contar isso a Hamã, para ver se Mordecai continuaria a desobedecer à ordem do rei.

[[v17-3-5]]

^<<v17-3-5,5>>^ Hamã ficou furioso quando viu que Mordecai não se ajoelhava em honra dele.

[[v17-3-6]]

^<<v17-3-6,6>>^ E, quando lhe disseram que Mordecai era judeu, Hamã achou que não bastava matar somente Mordecai; ele fez planos para matar também todos os judeus que havia no reino de Xerxes.

[[v17-3-7]]

^<<v17-3-7,7>>^ No ano doze do reinado de Xerxes, no primeiro mês, o mês de nisã , Hamã ordenou que tirassem a sorte (chamava-se isso de "purim"), para decidir o dia e o mês em que os judeus seriam mortos. Foi sorteado o dia treze do décimo segundo mês, o mês de adar .

[[v17-3-8]]

^<<v17-3-8,8>>^ Hamã foi e disse ao rei: — Por todas as províncias  do reino, está espalhado um povo que segue leis  diferentes das leis dos outros povos. O pior, ó rei, é que eles não obedecem às suas ordens, e por isso não convém que o senhor tolere que eles continuem agindo assim.

[[v17-3-9]]

^<<v17-3-9,9>>^ Se o senhor quiser, assine um decreto ordenando que eles sejam mortos. E eu prometo depositar nos cofres reais trezentos e quarenta e dois mil quilos de prata para pagar as despesas do governo.

[[v17-3-10]]

^<<v17-3-10,10>>^ O rei tirou o seu anel-sinete , que servia para carimbar as suas ordens, e o deu a Hamã, filho de Hamedata e descendente de Agague, o inimigo dos judeus.

[[v17-3-11]]

^<<v17-3-11,11>>^ E o rei lhe disse: — Fique com o seu dinheiro, e essa gente eu entrego nas suas mãos. Faça com eles o que quiser.

[[v17-3-12]]

^<<v17-3-12,12>>^ No dia treze do primeiro mês, Hamã mandou chamar os secretários do palácio e ditou a ordem. Ele ordenou que fosse traduzida para todas as línguas faladas no reino e que cada tradução seguisse a escrita usada em cada província. A ordem devia ser enviada a todos os representantes do rei, aos governadores das províncias e aos chefes dos vários povos. Ela foi escrita em nome do rei, carimbada com o seu anel-sinete

[[v17-3-13]]

^<<v17-3-13,13>>^ e levada por mensageiros a todas as províncias do reino. A ordem era matar todos os judeus num dia só, o dia treze do décimo segundo mês, o mês de adar. Que todos os judeus fossem mortos, sem dó nem piedade: os moços e os velhos, as mulheres e as crianças. E a ordem mandava também que todos os bens dos judeus ficassem para o governo.

[[v17-3-14]]

^<<v17-3-14,14>>^ Em cada província deveria ser feita uma leitura em público dessa ordem, a fim de que, quando chegasse o dia marcado, todos estivessem prontos.

[[v17-3-15]]

^<<v17-3-15,15>>^ O rei deu a ordem, e os mensageiros foram depressa a todas as províncias; e em Susã, a capital, a ordem foi lida em público. O rei e Hamã se assentaram para beber, enquanto a confusão se espalhava pela cidade.

'''

xref:017-ester/017-ester-002.adoc#v17-2-0[&#60; Capítulo Anterior] | <<v17-3-0,Topo>> | xref:017-ester/017-ester-004.adoc#v17-4-0[Próximo Capítulo &#62;]