include::./index.adoc[]

[[v17-7-0]]
=== Ester, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v17-7-1]]

^<<v17-7-1,1>>^ Portanto, o rei e Hamã foram de novo ao banquete da rainha Ester,

[[v17-7-2]]

^<<v17-7-2,2>>^ e novamente, enquanto bebiam vinho, o rei perguntou a Ester: — Qual é o seu pedido? Peça o que quiser, que eu lhe darei, mesmo que seja a metade do meu reino.

[[v17-7-3]]

^<<v17-7-3,3>>^ Ela respondeu: — Se eu puder me valer da bondade do rei, e se for do seu agrado, a única coisa que quero é que o senhor salve a minha vida e a vida do meu povo.

[[v17-7-4]]

^<<v17-7-4,4>>^ Pois o meu povo e eu fomos vendidos para sermos destruídos e mortos. Se fosse somente o caso de sermos todos vendidos como escravos, eu não diria nada, pois não seria justo incomodar o senhor por causa de uma desgraça tão sem importância como esta.

[[v17-7-5]]

^<<v17-7-5,5>>^ O rei Xerxes perguntou à rainha Ester: — Quem é o homem que está pensando em fazer isso e onde está ele?

[[v17-7-6]]

^<<v17-7-6,6>>^ — O nosso inimigo e perseguidor é Hamã, este homem perverso! — respondeu Ester. Cheio de medo, Hamã ficou olhando para o rei e para a rainha.

[[v17-7-7]]

^<<v17-7-7,7>>^ O rei saiu furioso do salão de banquetes e foi para o jardim. Hamã percebeu que o rei havia resolvido castigá-lo e por isso ficou no salão para pedir à rainha que salvasse a sua vida.

[[v17-7-8]]

^<<v17-7-8,8>>^ Ele se jogou no sofá onde Ester estava, para pedir misericórdia, e nesse instante o rei voltou do jardim. Quando viu Hamã, o rei disse: — Será que ele pretende desonrar a rainha aqui no meu palácio e na minha frente? Assim que o rei acabou de falar, os seus servidores particulares cobriram a cabeça de Hamã.

[[v17-7-9]]

^<<v17-7-9,9>>^ Um deles, chamado Harbona, disse: — Perto da casa de Hamã há uma forca de uns vinte metros de altura que ele mandou construir para enforcar Mordecai, o homem que salvou a vida do senhor. — Enforquem Hamã nela! — ordenou o rei.

[[v17-7-10]]

^<<v17-7-10,10>>^ Então enforcaram Hamã na forca que ele tinha construído para enforcar Mordecai. E assim a raiva do rei se acalmou.

'''

xref:017-ester/017-ester-006.adoc#v17-6-0[&#60; Capítulo Anterior] | <<v17-7-0,Topo>> | xref:017-ester/017-ester-008.adoc#v17-8-0[Próximo Capítulo &#62;]