include::./index.adoc[]

[[v17-6-0]]
=== Ester, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v17-6-1]]

^<<v17-6-1,1>>^ Naquela mesma noite, o rei não conseguiu pegar no sono; então mandou buscar o livro em que se escrevia o que acontecia no reino e ordenou que os seus funcionários lessem para ele.

[[v17-6-2]]

^<<v17-6-2,2>>^ A parte que leram contava como Mordecai tinha descoberto o plano para matar o rei, plano este preparado por Bigtã e Teres, os dois eunucos  que eram guardas do palácio.

[[v17-6-3]]

^<<v17-6-3,3>>^ Aí o rei perguntou: — Que homenagens foram prestadas e que prêmios foram dados a Mordecai por ter feito isso? — Nada se fez a esse respeito! — responderam os funcionários.

[[v17-6-4]]

^<<v17-6-4,4>>^ Justamente nesse instante, Hamã entrou no pátio que ficava ao lado dos quartos do rei para lhe pedir que mandasse enforcar Mordecai na forca que ele, Hamã, havia mandado construir. O rei perguntou: — Quem está no pátio?

[[v17-6-5]]

^<<v17-6-5,5>>^ — É Hamã! — responderam os servidores. — Mandem que entre! — ordenou o rei.

[[v17-6-6]]

^<<v17-6-6,6>>^ Hamã entrou, e o rei lhe disse: — Eu quero ter o prazer de prestar homenagens a um certo homem. Diga-me o que devo fazer por ele. Hamã pensou assim: "Quem será esse homem a quem o rei tanto quer honrar? É claro que sou eu!"

[[v17-6-7]]

^<<v17-6-7,7>>^ E Hamã disse ao rei:

[[v17-6-8]]

^<<v17-6-8,8>>^ — Mande trazer as roupas que o senhor usa e também o cavalo que o senhor monta e mande colocar uma coroa real na cabeça do cavalo.

[[v17-6-9]]

^<<v17-6-9,9>>^ Então entregue as roupas e o cavalo a um dos mais altos funcionários do reino e ordene que ele vista as roupas no homem que o senhor deseja honrar. Depois, que ele leve o homem, montado a cavalo, pela praça principal da cidade e que diga em voz alta o seguinte: "É isto o que o rei faz pelo homem a quem ele quer honrar!"

[[v17-6-10]]

^<<v17-6-10,10>>^ Então o rei disse a Hamã: — Vá depressa, e pegue as roupas e o cavalo, e faça com o judeu Mordecai tudo o que você acaba de dizer. Ele costuma ficar sentado na entrada do palácio. Não deixe de fazer nenhuma das coisas que você disse.

[[v17-6-11]]

^<<v17-6-11,11>>^ Hamã foi, pegou as roupas e o cavalo e vestiu as roupas em Mordecai. Depois levou Mordecai, montado a cavalo, pela praça principal da cidade e disse em voz alta: "É isto o que o rei faz pelo homem a quem ele quer honrar!"

[[v17-6-12]]

^<<v17-6-12,12>>^ Depois disso, Mordecai voltou para a entrada do palácio, enquanto que Hamã, envergonhado e triste, correu para casa, escondendo o rosto.

[[v17-6-13]]

^<<v17-6-13,13>>^ Contou à esposa e aos amigos tudo o que tinha acontecido com ele. Então ela e os seus amigos, que eram tão sabidos, disseram: — Você já começou a perder a luta com Mordecai. Ele é judeu, e você não vai ganhar de jeito nenhum. Você vai perder na certa.

[[v17-6-14]]

^<<v17-6-14,14>>^ Eles ainda estavam falando quando os eunucos que estavam ao serviço do rei chegaram e levaram Hamã imediatamente ao banquete que Ester tinha preparado.

'''

xref:017-ester/017-ester-005.adoc#v17-5-0[&#60; Capítulo Anterior] | <<v17-6-0,Topo>> | xref:017-ester/017-ester-007.adoc#v17-7-0[Próximo Capítulo &#62;]