include::./index.adoc[]

[[v17-9-0]]
=== Ester, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v17-9-1]]

^<<v17-9-1,1>>^ Chegou o dia treze do décimo segundo mês, o mês de adar , o dia em que deveria ser cumprida a ordem do rei. Era o dia em que os inimigos dos judeus esperavam dominá-los; mas o que aconteceu foi o contrário: os judeus derrotaram os seus inimigos.

[[v17-9-2]]

^<<v17-9-2,2>>^ Em todas as cidades do reino onde havia judeus, eles se reuniram para atacar os que queriam matá-los. Ninguém podia resistir aos seus ataques, pois todos estavam com medo deles.

[[v17-9-3]]

^<<v17-9-3,3>>^ Todos os oficiais das províncias , isto é, os chefes dos vários povos, os representantes do rei e os governadores das províncias, ajudaram os judeus, pois tinham medo de Mordecai.

[[v17-9-4]]

^<<v17-9-4,4>>^ A fama dele se havia espalhado pelo reino inteiro, e todos sabiam que ele tinha muita autoridade no governo. E o poder de Mordecai ia aumentando cada vez mais.

[[v17-9-5]]

^<<v17-9-5,5>>^ Portanto, os judeus fizeram com os seus inimigos o que queriam. Mataram todos com as suas espadas; não deixaram ninguém escapar.

[[v17-9-6]]

^<<v17-9-6,6>>^ Em Susã, a capital, eles mataram quinhentos homens.

[[v17-9-7]]

^<<v17-9-7,7>>^ Mataram também os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus. Os nomes deles eram Parsandata, Dalfão, Aspatá, Porata, Adalias, Aridata, Parmasta, Arisai, Aridai e Vaizata. Mas os judeus não ficaram com os bens deles.

[[v17-9-8]]

^<<v17-9-8,8>>^ Mataram também os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus. Os nomes deles eram Parsandata, Dalfão, Aspatá, Porata, Adalias, Aridata, Parmasta, Arisai, Aridai e Vaizata. Mas os judeus não ficaram com os bens deles.

[[v17-9-9]]

^<<v17-9-9,9>>^ Mataram também os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus. Os nomes deles eram Parsandata, Dalfão, Aspatá, Porata, Adalias, Aridata, Parmasta, Arisai, Aridai e Vaizata. Mas os judeus não ficaram com os bens deles.

[[v17-9-10]]

^<<v17-9-10,10>>^ Mataram também os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus. Os nomes deles eram Parsandata, Dalfão, Aspatá, Porata, Adalias, Aridata, Parmasta, Arisai, Aridai e Vaizata. Mas os judeus não ficaram com os bens deles.

[[v17-9-11]]

^<<v17-9-11,11>>^ Naquele mesmo dia, o rei foi informado de quantas pessoas haviam sido mortas em Susã.

[[v17-9-12]]

^<<v17-9-12,12>>^ Então disse a Ester: — Aqui em Susã os judeus mataram quinhentos homens e também os dez filhos de Hamã. E, nas províncias, quantos eles terão matado? O que é que você quer agora? É só pedir. Se quiser mais alguma coisa, eu lhe darei.

[[v17-9-13]]

^<<v17-9-13,13>>^ Ester respondeu: — Se for do agrado do rei, dê autorização aos judeus de Susã para fazerem amanhã o mesmo que tinham ordem para fazer hoje. E peço também que os corpos dos dez filhos de Hamã sejam pendurados em forcas.

[[v17-9-14]]

^<<v17-9-14,14>>^ O rei concordou e mandou ler a autorização em público em Susã. E os corpos dos dez filhos de Hamã foram pendurados em forcas.

[[v17-9-15]]

^<<v17-9-15,15>>^ No dia catorze do mês de adar, os judeus de Susã se reuniram e mataram mais trezentos homens na cidade. Mas não ficaram com os bens deles.

[[v17-9-16]]

^<<v17-9-16,16>>^ No dia treze do mês de adar, os judeus das províncias se reuniram e se defenderam. Mataram setenta e cinco mil inimigos e assim se livraram de todos os que os odiavam. Mas não ficaram com os bens dos mortos. No dia catorze, eles descansaram e comemoraram com banquetes e festas.

[[v17-9-17]]

^<<v17-9-17,17>>^ No dia treze do mês de adar, os judeus das províncias se reuniram e se defenderam. Mataram setenta e cinco mil inimigos e assim se livraram de todos os que os odiavam. Mas não ficaram com os bens dos mortos. No dia catorze, eles descansaram e comemoraram com banquetes e festas.

[[v17-9-18]]

^<<v17-9-18,18>>^ Mas em Susã os judeus comemoraram no dia quinze do mês, pois nos dias treze e catorze eles mataram os seus inimigos e só no dia quinze descansaram.

[[v17-9-19]]

^<<v17-9-19,19>>^ É por isso que os judeus que vivem em vilas e povoados comemoram o dia catorze de adar com banquetes e festas e mandam comida uns aos outros.

[[v17-9-20]]

^<<v17-9-20,20>>^ Mordecai escreveu tudo o que havia acontecido e mandou cartas a todos os judeus que moravam em todas as províncias  do reino, tanto aos de perto como aos de longe.

[[v17-9-21]]

^<<v17-9-21,21>>^ Nas cartas ele ordenou que todos os anos eles comemorassem os dias catorze e quinze do mês de adar ,

[[v17-9-22]]

^<<v17-9-22,22>>^ pois foi nestes dias que os judeus se livraram dos seus inimigos, e foi neste mês que a tristeza e o luto se transformaram em alegria e festa. Portanto, que dessem banquetes e festas, mandassem comida uns aos outros e distribuíssem presentes aos pobres.

[[v17-9-23]]

^<<v17-9-23,23>>^ Assim os judeus, de acordo com o que Mordecai tinha escrito, começaram o costume de comemorar esses dias.

[[v17-9-24]]

^<<v17-9-24,24>>^ Hamã, filho de Hamedata, descendente de Agague e inimigo dos judeus, tinha planejado acabar com eles e tinha mandado tirar a sorte (chama-se isso de "purim") para resolver em que dia ia matá-los.

[[v17-9-25]]

^<<v17-9-25,25>>^ Mas Ester foi falar com o rei, e ele ordenou por escrito que o mal que Hamã havia planejado contra os judeus caísse sobre o próprio Hamã. Portanto, enforcaram Hamã e os seus filhos.

[[v17-9-26]]

^<<v17-9-26,26>>^ É por isso que esses dias feriados são chamados de "Purim", que é o plural da palavra "pur" . Como resultado da carta de Mordecai e de tudo o que os judeus tinham visto e das coisas que aconteceram,

[[v17-9-27]]

^<<v17-9-27,27>>^ eles resolveram que eles mesmos, os seus descendentes e os que se convertessem ao Judaísmo seguiriam o costume de comemorar todos os anos esses dois dias, conforme Mordecai havia escrito.

[[v17-9-28]]

^<<v17-9-28,28>>^ Ficou resolvido que daí em diante toda família judaica, em todas as cidades das províncias do reino, comemoraria a Festa de Purim, para que os judeus lembrassem sempre do que havia acontecido. Nunca, em qualquer época, deixariam de comemorar essa festa.

'''

xref:017-ester/017-ester-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-ester/017-ester-010.adoc#v17-10-0[Próximo Capítulo &#62;]