include::./index.adoc[]

[[v17-1-0]]
=== Ester, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v17-1-1]]

^<<v17-1-1,1>>^ Foi no tempo em que Xerxes era rei da Pérsia. A capital era Susã, e o reino se dividia em cento e vinte e sete províncias , que iam desde a Índia até a Etiópia.

[[v17-1-2]]

^<<v17-1-2,2>>^ Foi no tempo em que Xerxes era rei da Pérsia. A capital era Susã, e o reino se dividia em cento e vinte e sete províncias , que iam desde a Índia até a Etiópia.

[[v17-1-3]]

^<<v17-1-3,3>>^ No terceiro ano do seu reinado, o rei deu um banquete para todos os seus oficiais e servidores. Estavam presentes também os chefes dos exércitos da Pérsia e da Média, e os governadores, e a gente da nobreza das províncias.

[[v17-1-4]]

^<<v17-1-4,4>>^ Durante seis meses Xerxes exibiu a todos as riquezas do seu reino e o luxo e o esplendor da sua corte.

[[v17-1-5]]

^<<v17-1-5,5>>^ Depois dos seis meses, o rei ofereceu nos jardins do palácio um banquete para todos os moradores de Susã, tanto os ricos como os pobres. A festa durou uma semana.

[[v17-1-6]]

^<<v17-1-6,6>>^ O pátio estava todo enfeitado com cortinas de algodão brancas e azuis, amarradas com cordões de fino linho vermelho, que estavam presos por argolas de prata a colunas de mármore. O piso era feito de ladrilhos azuis, de mármore branco, de madrepérola e de pedras preciosas. Nesse pátio havia sofás de ouro e de prata.

[[v17-1-7]]

^<<v17-1-7,7>>^ Os convidados tomavam as bebidas em copos de ouro, todos eles diferentes uns dos outros, e o rei mandou que o seu vinho fosse servido à vontade.

[[v17-1-8]]

^<<v17-1-8,8>>^ Todos podiam beber o quanto quisessem; o rei havia ordenado aos empregados do palácio que servissem a todos os hóspedes quanto vinho eles quisessem.

[[v17-1-9]]

^<<v17-1-9,9>>^ A rainha Vasti também ofereceu no palácio real um banquete para todas as mulheres dos convidados.

[[v17-1-10]]

^<<v17-1-10,10>>^ No sétimo dia de banquetes, o rei já havia bebido bastante vinho e estava muito alegre. Aí ele mandou chamar os sete eunucos  que eram os seus servidores particulares. Eles se chamavam Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas.

[[v17-1-11]]

^<<v17-1-11,11>>^ O rei ordenou que eles fossem buscar a rainha Vasti e que ela viesse com a coroa de rainha na cabeça. Ela era muito bonita, e o rei queria que os nobres e os outros convidados admirassem a sua beleza.

[[v17-1-12]]

^<<v17-1-12,12>>^ Mas a rainha não atendeu a ordem do rei, e por isso ele ficou furioso.

[[v17-1-13]]

^<<v17-1-13,13>>^ Antes de tomar qualquer decisão, o rei consultava os entendidos em questões de lei  e de costumes. Portanto, mandou chamar os conselheiros

[[v17-1-14]]

^<<v17-1-14,14>>^ em quem ele tinha mais confiança, isto é, Carsena, Setar, Admata, Társis, Meres, Marsena e Memucã. Estes eram os sete ministros da Pérsia e da Média que ocupavam as mais altas posições no reino e serviam como conselheiros íntimos do rei.

[[v17-1-15]]

^<<v17-1-15,15>>^ Ele perguntou: — Eu, o rei Xerxes, mandei por meio dos meus servidores uma ordem à rainha Vasti, mas ela não obedeceu. De acordo com a lei, o que deve ser feito?

[[v17-1-16]]

^<<v17-1-16,16>>^ Aí Memucã disse ao rei e aos seus ministros: — O que a rainha fez é uma ofensa não somente contra o senhor e os seus ministros, mas também contra os homens de todas as províncias do reino.

[[v17-1-17]]

^<<v17-1-17,17>>^ Pois, quando em todo o reino as mulheres souberem do que a rainha fez, elas irão desprezar os seus maridos. E vão dizer: "O rei Xerxes mandou buscar a rainha Vasti, e ela não foi."

[[v17-1-18]]

^<<v17-1-18,18>>^ Hoje mesmo — continuou Memucã — as mulheres das altas autoridades da Pérsia e da Média vão saber do que a rainha Vasti fez e vão contar aos seus maridos. E por toda parte as mulheres não respeitarão os seus maridos, e os maridos ficarão zangados com as suas mulheres.

[[v17-1-19]]

^<<v17-1-19,19>>^ Portanto, se for da sua vontade, ó rei, assine um decreto proibindo a rainha Vasti de aparecer na presença do senhor. E mande escrever isso nos livros das leis da Pérsia e da Média, para que nunca possa ser anulado. Depois arranje uma mulher que seja melhor do que Vasti, para ser rainha no lugar dela.

[[v17-1-20]]

^<<v17-1-20,20>>^ Quando a ordem do rei for anunciada por todo este enorme reino, então todas as mulheres tratarão com respeito os seus maridos, sejam ricos ou pobres.

[[v17-1-21]]

^<<v17-1-21,21>>^ O rei e os seus ministros gostaram da ideia, e ele fez o que Memucã tinha sugerido.

'''

xref:016-neemias/016-neemias-013.adoc#v16-13-0[&#60; Capítulo Anterior] | <<v17-1-0,Topo>> | xref:017-ester/017-ester-002.adoc#v17-2-0[Próximo Capítulo &#62;]