include::./index.adoc[]

[[v3-1-0]]
=== Levítico, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-1-1]]

^<<v3-1-1,1>>^ O Senhor  Deus chamou Moisés e de dentro da Tenda Sagrada  mandou

[[v3-1-2]]

^<<v3-1-2,2>>^ que ele desse aos israelitas as seguintes leis  a respeito dos sacrifícios : Quando um homem oferecer um animal em sacrifício  a Deus, o Senhor , ele poderá escolhê-lo do seu gado ou do seu rebanho de ovelhas e cabras.

[[v3-1-3]]

^<<v3-1-3,3>>^ Se ele oferecer um animal do seu gado para ser completamente queimado no altar, então deverá ser um touro sem defeito. Para que o Senhor  o aceite, o homem levará o touro até a entrada da Tenda Sagrada .

[[v3-1-4]]

^<<v3-1-4,4>>^ Ali ele porá a mão na cabeça do animal a fim de que seja aceito como sacrifício para conseguir o perdão dos seus pecados.

[[v3-1-5]]

^<<v3-1-5,5>>^ O homem matará o touro ali na frente da Tenda Sagrada, e os sacerdotes, que são descendentes de Arão, oferecerão ao Senhor  o sangue do animal e depois borrifarão com ele os quatro lados do altar que está na frente da Tenda.

[[v3-1-6]]

^<<v3-1-6,6>>^ Em seguida o homem tirará o couro do animal e depois cortará o corpo em pedaços.

[[v3-1-7]]

^<<v3-1-7,7>>^ Os sacerdotes acenderão fogo em cima do altar, arrumarão a lenha sobre o fogo

[[v3-1-8]]

^<<v3-1-8,8>>^ e colocarão sobre ela os pedaços do touro, a cabeça e a gordura que cobre os intestinos.

[[v3-1-9]]

^<<v3-1-9,9>>^ O homem lavará os miúdos e as pernas do animal, que também serão queimados no altar. O sacerdote queimará o touro todo como um sacrifício que tem um cheiro agradável a Deus, o Senhor .

[[v3-1-10]]

^<<v3-1-10,10>>^ Se o homem oferecer em sacrifício a Deus um carneiro ou um cabrito, o animal deverá ser um macho sem defeito.

[[v3-1-11]]

^<<v3-1-11,11>>^ O homem matará o animal na presença do Senhor  no lado norte do altar, e os sacerdotes borrifarão os quatro lados do altar com o sangue.

[[v3-1-12]]

^<<v3-1-12,12>>^ Em seguida ele cortará o animal em pedaços, e o sacerdote os colocará, junto com a cabeça e a gordura que cobre os intestinos, no fogo que está em cima do altar.

[[v3-1-13]]

^<<v3-1-13,13>>^ O dono do animal lavará os miúdos e as pernas, e estes também serão oferecidos em sacrifício. O animal todo será queimado como um sacrifício que tem um cheiro agradável ao Senhor .

[[v3-1-14]]

^<<v3-1-14,14>>^ Se a oferta queimada que o homem oferece ao Senhor  for uma ave, então ele deverá trazer uma rolinha ou um pombinho.

[[v3-1-15]]

^<<v3-1-15,15>>^ O sacerdote levará a ave para o altar, tirará a cabeça e a queimará no altar. Em seguida deixará o sangue da ave escorrer no lado do altar.

[[v3-1-16]]

^<<v3-1-16,16>>^ Depois tirará o papo com o que estiver dentro e o jogará no monte de cinzas que fica no lado leste do altar.

[[v3-1-17]]

^<<v3-1-17,17>>^ Então pegará a ave pelas asas e a abrirá, sem a partir em duas partes, e a queimará no altar. A ave toda será queimada como um sacrifício que tem um cheiro agradável a Deus, o Senhor .

'''

xref:002-exodo/002-exodo-040.adoc#v2-40-0[&#60; Capítulo Anterior] | <<v3-1-0,Topo>> | xref:003-levitico/003-levitico-002.adoc#v3-2-0[Próximo Capítulo &#62;]