include::./index.adoc[]

[[v3-12-0]]
=== Levítico, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-12-1]]

^<<v3-12-1,1>>^ O Senhor  Deus deu a Moisés as seguintes leis

[[v3-12-2]]

^<<v3-12-2,2>>^ para o povo de Israel: Quando uma mulher der à luz um filho, ficará impura  sete dias, como acontece durante a menstruação.

[[v3-12-3]]

^<<v3-12-3,3>>^ No oitavo dia o menino será circuncidado .

[[v3-12-4]]

^<<v3-12-4,4>>^ Depois disso, por causa da perda de sangue, ela ficará impura por mais trinta e três dias. Durante esse tempo ela não poderá tocar em nada sagrado, nem poderá ir até a Tenda Sagrada .

[[v3-12-5]]

^<<v3-12-5,5>>^ Se der à luz uma filha, a mulher ficará impura catorze dias, como acontece durante a menstruação. Depois disso, por causa da perda de sangue, ela ficará impura por mais sessenta e seis dias.

[[v3-12-6]]

^<<v3-12-6,6>>^ Depois desse tempo de purificação , seja no caso de um filho ou de uma filha, a mulher irá até a entrada da Tenda Sagrada e entregará ao sacerdote um carneirinho de um ano como oferta que é completamente queimada e um pombinho ou uma rolinha como oferta para tirar pecados.

[[v3-12-7]]

^<<v3-12-7,7>>^ O sacerdote apresentará a oferta ao Senhor  a fim de conseguir o perdão dos pecados da mulher, e assim ela ficará pura . Esta é a lei  a respeito da mulher que dá à luz.

[[v3-12-8]]

^<<v3-12-8,8>>^ Se não tiver recursos para oferecer um carneirinho, a mulher levará ao sacerdote duas rolinhas ou dois pombinhos; uma das aves será a oferta que é completamente queimada, e a outra será a oferta para tirar pecados. Por meio dessas ofertas o sacerdote conseguirá o perdão dos pecados da mulher, e ela ficará pura.

'''

xref:003-levitico/003-levitico-011.adoc#v3-11-0[&#60; Capítulo Anterior] | <<v3-12-0,Topo>> | xref:003-levitico/003-levitico-013.adoc#v3-13-0[Próximo Capítulo &#62;]