include::./index.adoc[]

[[v3-13-0]]
=== Levítico, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-13-1]]

^<<v3-13-1,1>>^ O Senhor  Deus deu a Moisés e a Arão as seguintes leis :

[[v3-13-2]]

^<<v3-13-2,2>>^ Se uma pessoa tiver na pele uma inchação, tumor ou mancha que vai virando uma doença contagiosa, essa pessoa será levada a Arão, o sacerdote, ou a um dos sacerdotes, que são filhos de Arão.

[[v3-13-3]]

^<<v3-13-3,3>>^ O sacerdote examinará a pele, e, se os pelos da mancha se tornaram brancos, e se parecer que a ferida ficou mais funda do que a pele, então é uma doença contagiosa; o sacerdote declarará que a pessoa é impura .

[[v3-13-4]]

^<<v3-13-4,4>>^ Mas, se a mancha for branca, e se não parecer que ficou mais funda do que a pele, e se os pelos do lugar não se tornaram brancos, então o sacerdote fará com que a pessoa fique no isolamento sete dias.

[[v3-13-5]]

^<<v3-13-5,5>>^ No sétimo dia o sacerdote a examinará de novo e, se na sua opinião a mancha não se espalhou, mas continua como estava, então ele mandará que a pessoa fique no isolamento mais sete dias.

[[v3-13-6]]

^<<v3-13-6,6>>^ No sétimo dia ele examinará a pessoa outra vez; se a mancha estiver desaparecendo e se não tiver se espalhado na pele, então é só um tumor sem importância. A pessoa lavará a roupa que estiver vestindo, e o sacerdote declarará que está pura .

[[v3-13-7]]

^<<v3-13-7,7>>^ Mas, se depois disso a mancha se espalhar na pele, então a pessoa irá outra vez falar com o sacerdote.

[[v3-13-8]]

^<<v3-13-8,8>>^ Ele a examinará e, se a mancha tiver se espalhado, declarará que a pessoa está impura; é um caso de doença contagiosa.

[[v3-13-9]]

^<<v3-13-9,9>>^ Quando alguém tiver uma doença contagiosa da pele, deve ser levado ao sacerdote.

[[v3-13-10]]

^<<v3-13-10,10>>^ Este o examinará, e, se houver na pele um tumor branco, e os pelos do lugar estiverem brancos também, e houver uma ferida aberta no lugar,

[[v3-13-11]]

^<<v3-13-11,11>>^ então é um caso crônico de doença contagiosa. Aí o sacerdote declarará que o doente está impuro e não fará com que ele fique no isolamento , pois não há dúvida de que ele é impuro.

[[v3-13-12]]

^<<v3-13-12,12>>^ Se o sacerdote achar que a doença se espalhou pelo corpo inteiro, da cabeça aos pés,

[[v3-13-13]]

^<<v3-13-13,13>>^ então ele examinará o doente. Se, de fato, a doença se espalhou pelo corpo todo, e a pele se tornou branca, então o homem está puro, e o sacerdote o declarará puro.

[[v3-13-14]]

^<<v3-13-14,14>>^ Porém, quando aparecer uma ferida aberta na pele do doente, ele estará impuro.

[[v3-13-15]]

^<<v3-13-15,15>>^ O sacerdote o examinará outra vez e, se encontrar uma ferida aberta, então declarará que a pessoa está impura. Uma ferida aberta é sinal de doença contagiosa.

[[v3-13-16]]

^<<v3-13-16,16>>^ Mas, quando a ferida sarar e se tornar branca, a pessoa se apresentará ao sacerdote,

[[v3-13-17]]

^<<v3-13-17,17>>^ que a examinará. Se a ferida se tornou branca, então a pessoa está pura, e o sacerdote declarará que está pura.

[[v3-13-18]]

^<<v3-13-18,18>>^ Se alguém tiver um furúnculo que sarou,

[[v3-13-19]]

^<<v3-13-19,19>>^ e ali aparecer um lugar inchado e branco ou uma mancha avermelhada, a pessoa se apresentará ao sacerdote.

[[v3-13-20]]

^<<v3-13-20,20>>^ Ele a examinará e, se parecer que a ferida ficou mais funda do que a pele, e os pelos do lugar se tornaram brancos, então ele declarará que a pessoa está impura. É um caso de doença contagiosa que começou no furúnculo.

[[v3-13-21]]

^<<v3-13-21,21>>^ Mas, se o sacerdote descobrir que os pelos não estão brancos e que a ferida não está mais funda do que a pele, mas já se tornou branca, então ele mandará a pessoa ficar no isolamento sete dias.

[[v3-13-22]]

^<<v3-13-22,22>>^ Se a mancha se espalhou, é um caso de doença contagiosa, e o sacerdote declarará que a pessoa está impura.

[[v3-13-23]]

^<<v3-13-23,23>>^ Mas, se a mancha não se espalhou, mas continua como estava, então é somente a cicatriz que o furúnculo deixou na pele. Portanto, o sacerdote declarará que a pessoa está pura.

[[v3-13-24]]

^<<v3-13-24,24>>^ Se alguém se queimar, e no lugar queimado a ferida virar uma mancha avermelhada ou branca,

[[v3-13-25]]

^<<v3-13-25,25>>^ o sacerdote examinará a mancha. Se os pelos do lugar se tornaram brancos, e a ferida ficou mais funda do que a pele, é uma doença contagiosa que começou com a queimadura, e o sacerdote declarará que a pessoa está impura.

[[v3-13-26]]

^<<v3-13-26,26>>^ Porém, se o sacerdote descobrir que os pelos na ferida não estão brancos, e que a ferida não está mais funda do que a pele, e a sua cor está clara, o sacerdote mandará a pessoa ficar no isolamento sete dias.

[[v3-13-27]]

^<<v3-13-27,27>>^ No sétimo dia o sacerdote a examinará, e, se a mancha tiver se espalhado, então é uma doença contagiosa, e o sacerdote declarará que a pessoa está impura.

[[v3-13-28]]

^<<v3-13-28,28>>^ Porém, se a mancha não se espalhou, mas continua como estava, e a sua cor está clara, então é uma inchação causada pela queimadura. Aí o sacerdote declarará que a pessoa está pura, pois se trata somente de uma cicatriz que a queimadura deixou.

[[v3-13-29]]

^<<v3-13-29,29>>^ Quando um homem ou uma mulher tiver uma doença da pele na cabeça ou no queixo,

[[v3-13-30]]

^<<v3-13-30,30>>^ o sacerdote examinará a pele. Se parecer que a ferida ficou mais funda do que a pele, e, se os cabelos dali estiverem amarelos e forem poucos, é uma doença contagiosa, e o sacerdote declarará que a pessoa está impura.

[[v3-13-31]]

^<<v3-13-31,31>>^ Se o sacerdote achar que a ferida não ficou mais funda do que a pele, e, se não houver nela cabelos escuros, então ele mandará a pessoa ficar no isolamento sete dias.

[[v3-13-32]]

^<<v3-13-32,32>>^ No sétimo dia ele a examinará; se a doença não tiver se espalhado e no lugar não houver cabelos amarelados, e, se a ferida não ficou mais funda do que a pele,

[[v3-13-33]]

^<<v3-13-33,33>>^ então a pessoa rapará a cabeça ou o queixo, sem cortar os cabelos da parte doente. O sacerdote mandará que ela fique no isolamento mais sete dias

[[v3-13-34]]

^<<v3-13-34,34>>^ e no sétimo dia examinará a pele. Se a doença não tiver se espalhado e, se não parecer que ficou mais funda do que a pele, o sacerdote declarará que a pessoa está pura. Ela lavará a roupa que estiver vestindo e estará pura.

[[v3-13-35]]

^<<v3-13-35,35>>^ Mas, se depois disso a infecção se espalhar,

[[v3-13-36]]

^<<v3-13-36,36>>^ então o sacerdote examinará a pessoa. Se ele verificar que, de fato, a infecção se espalhou, não é preciso que ele procure cabelos amarelados; a pessoa está impura.

[[v3-13-37]]

^<<v3-13-37,37>>^ Mas, se na opinião do sacerdote a infecção não se espalhou, e ali estiverem crescendo cabelos escuros, então a infecção sarou. A pessoa está pura, e o sacerdote declarará que ela está pura.

[[v3-13-38]]

^<<v3-13-38,38>>^ Quando um homem ou uma mulher tiver manchas brancas na pele,

[[v3-13-39]]

^<<v3-13-39,39>>^ o sacerdote examinará a pessoa. Se as manchas forem de um branco pálido, é uma coisa sem importância. A pessoa está pura.

[[v3-13-40]]

^<<v3-13-40,40>>^ Se um homem perder cabelos da parte de trás da cabeça ou da parte da frente, ele se torna calvo ou meio calvo, mas não fica impuro.

[[v3-13-41]]

^<<v3-13-41,41>>^ Se um homem perder cabelos da parte de trás da cabeça ou da parte da frente, ele se torna calvo ou meio calvo, mas não fica impuro.

[[v3-13-42]]

^<<v3-13-42,42>>^ Mas, se na parte pelada da cabeça aparecer uma mancha cor de rosa, é uma doença contagiosa.

[[v3-13-43]]

^<<v3-13-43,43>>^ O sacerdote examinará o homem, e, se descobrir uma mancha cor de rosa, como as que aparecem na pele,

[[v3-13-44]]

^<<v3-13-44,44>>^ é uma doença contagiosa. O homem está impuro, e o sacerdote declarará que está impuro por causa da infecção na cabeça.

[[v3-13-45]]

^<<v3-13-45,45>>^ Uma pessoa que sofrer de uma doença contagiosa da pele deverá vestir roupas rasgadas, deixar os cabelos sem pentear, cobrir o rosto da boca para baixo e gritar: "Impuro, impuro!"

[[v3-13-46]]

^<<v3-13-46,46>>^ Enquanto sofrer de uma doença contagiosa, a pessoa continuará impura e precisará morar sozinha, fora do acampamento.

[[v3-13-47]]

^<<v3-13-47,47>>^ Quando aparecer mofo numa roupa feita de lã ou de linho,

[[v3-13-48]]

^<<v3-13-48,48>>^ ou num tecido de linho ou de lã, ou num pedaço de couro, ou num objeto feito de couro,

[[v3-13-49]]

^<<v3-13-49,49>>^ se a mancha for esverdeada ou avermelhada, então é mofo e deve ser mostrado ao sacerdote.

[[v3-13-50]]

^<<v3-13-50,50>>^ O sacerdote examinará o objeto mofado e o colocará durante sete dias num lugar separado.

[[v3-13-51]]

^<<v3-13-51,51>>^ No sétimo dia ele examinará a mancha, e, se ela se tiver espalhado, então o mofo é contagioso, e a roupa, ou o tecido, ou o couro, ou o objeto feito de couro está impuro ,

[[v3-13-52]]

^<<v3-13-52,52>>^ e o sacerdote o queimará. É mofo contagioso e deverá ser destruído pelo fogo.

[[v3-13-53]]

^<<v3-13-53,53>>^ Mas, se o sacerdote examinar a roupa, ou o tecido, ou o objeto de couro e descobrir que a mancha não se espalhou,

[[v3-13-54]]

^<<v3-13-54,54>>^ então mandará lavar o objeto em que está a mancha e o colocará durante mais sete dias num lugar separado.

[[v3-13-55]]

^<<v3-13-55,55>>^ Depois examinará o objeto outra vez, e, se a mancha não mudou de cor, mesmo que não se tenha espalhado, então ele está impuro e precisa ser queimado. É mofo contagioso, esteja na parte da frente ou na parte de trás do objeto.

[[v3-13-56]]

^<<v3-13-56,56>>^ Mas, se o sacerdote descobrir que a mancha perdeu a cor depois de ter sido lavada, então ele rasgará aquela parte da roupa, do couro ou do tecido.

[[v3-13-57]]

^<<v3-13-57,57>>^ Mas, se depois disso o mofo aparecer de novo, então é mofo contagioso, e o objeto deve ser queimado.

[[v3-13-58]]

^<<v3-13-58,58>>^ Se o objeto for lavado, e a mancha desaparecer, então deve ser lavado mais uma vez e aí estará puro .

'''

xref:003-levitico/003-levitico-012.adoc#v3-12-0[&#60; Capítulo Anterior] | <<v3-13-0,Topo>> | xref:003-levitico/003-levitico-014.adoc#v3-14-0[Próximo Capítulo &#62;]