include::./index.adoc[]

[[v3-20-0]]
=== Levítico, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-20-1]]

^<<v3-20-1,1>>^ O Senhor  Deus mandou Moisés

[[v3-20-2]]

^<<v3-20-2,2>>^ dizer ao povo de Israel o seguinte: — Se um israelita ou um estrangeiro que vive no meio do povo de Israel separar um dos seus filhos para servir o deus Moloque , ele deverá ser morto a pedradas pelo povo.

[[v3-20-3]]

^<<v3-20-3,3>>^ Eu ficarei contra esse homem e o expulsarei do meio do povo. Por haver dado um dos seus filhos para o serviço de Moloque, ele tornou impura  a Tenda Sagrada , o lugar onde moro, e profanou  o meu santo nome.

[[v3-20-4]]

^<<v3-20-4,4>>^ E, se o povo não reclamar contra o que esse homem fez e não o matar,

[[v3-20-5]]

^<<v3-20-5,5>>^ eu mesmo ficarei contra ele e contra a sua família. Eu o expulsarei do meio do povo, junto com todos os que seguirem o exemplo dele e adorarem o deus Moloque.

[[v3-20-6]]

^<<v3-20-6,6>>^ — Se alguém procurar a ajuda dos que invocam os espíritos dos mortos e dos que adivinham o futuro, eu ficarei contra essa pessoa por causa desse pecado e a expulsarei do meio do povo.

[[v3-20-7]]

^<<v3-20-7,7>>^ Dediquem-se completamente a mim e sejam santos, pois eu sou o Senhor , o Deus de vocês.

[[v3-20-8]]

^<<v3-20-8,8>>^ Obedeçam às minhas leis . Eu sou o Senhor , e eu os separei dos outros povos para que vocês sejam somente meus.

[[v3-20-9]]

^<<v3-20-9,9>>^ — A pessoa que amaldiçoar o pai ou a mãe será morta; e ela será responsável pela sua própria morte, pois amaldiçoou o pai ou a mãe.

[[v3-20-10]]

^<<v3-20-10,10>>^ — Se um homem cometer adultério com a mulher de outro, ele e a mulher deverão ser mortos.

[[v3-20-11]]

^<<v3-20-11,11>>^ Se um homem tiver relações com uma das mulheres do pai, ele estará desonrando o pai, e ele e a mulher deverão ser mortos; eles serão responsáveis pela sua própria morte.

[[v3-20-12]]

^<<v3-20-12,12>>^ Se um homem tiver relações com a nora, os dois deverão ser mortos por causa desse ato imoral; eles serão responsáveis pela sua própria morte.

[[v3-20-13]]

^<<v3-20-13,13>>^ Se um homem tiver relações com outro homem, os dois deverão ser mortos por causa desse ato nojento; eles serão responsáveis pela sua própria morte.

[[v3-20-14]]

^<<v3-20-14,14>>^ Se um homem casar com uma mulher e também com a mãe dela, isso é uma imoralidade grave, e os três deverão ser queimados vivos; essa imoralidade precisa ser eliminada do meio do povo.

[[v3-20-15]]

^<<v3-20-15,15>>^ Se um homem tiver relações com um animal, os dois deverão ser mortos.

[[v3-20-16]]

^<<v3-20-16,16>>^ Se uma mulher tiver relações com um animal, os dois deverão ser mortos; eles serão responsáveis pela sua própria morte.

[[v3-20-17]]

^<<v3-20-17,17>>^ — Se um homem casar com a irmã, seja por parte só de pai ou por parte de pai e mãe, os dois deverão ser expulsos publicamente do meio do povo. É uma vergonha um homem casar com a irmã; ele merece castigo.

[[v3-20-18]]

^<<v3-20-18,18>>^ Se um homem tiver relações com uma mulher durante a menstruação, os dois deverão ser expulsos do meio do povo. Os dois ficaram impuros , pois quebraram as leis da pureza a respeito da menstruação.

[[v3-20-19]]

^<<v3-20-19,19>>^ Se um homem tiver relações com a tia, os dois merecem castigo, pois são parentes.

[[v3-20-20]]

^<<v3-20-20,20>>^ E o homem que tiver relações com a tia envergonha o tio. O homem e a tia merecem castigo; eles nunca terão filhos.

[[v3-20-21]]

^<<v3-20-21,21>>^ Se um homem tiver relações com a cunhada, ele envergonha o irmão. É uma imoralidade, e os dois morrerão sem terem filhos.

[[v3-20-22]]

^<<v3-20-22,22>>^ — Obedeçam às minhas leis e aos meus mandamentos a fim de que a terra para onde eu os estou levando, a terra que vai ser de vocês, não os expulse.

[[v3-20-23]]

^<<v3-20-23,23>>^ Não imitem os costumes dos povos que eu vou expulsar dali, conforme vocês forem tomando posse da terra. Eu fiquei aborrecido com eles por causa das coisas imorais que faziam.

[[v3-20-24]]

^<<v3-20-24,24>>^ Mas já prometi que vou dar aquela terra a vocês, e vocês possuirão uma terra boa e rica. Eu sou o Senhor , o Deus de vocês; eu os separei dos outros povos.

[[v3-20-25]]

^<<v3-20-25,25>>^ Portanto, façam diferença entre animais e aves puros  e impuros . Sou eu quem decide se um animal, ou uma ave, ou um animal que se arrasta pelo chão é impuro ou não; e eu proibi que vocês comessem qualquer coisa impura, para que também não ficassem impuros.

[[v3-20-26]]

^<<v3-20-26,26>>^ Sejam santos , pois eu, o Senhor , sou santo. E eu os separei dos outros povos para que vocês sejam somente meus.

[[v3-20-27]]

^<<v3-20-27,27>>^ — Qualquer homem ou mulher que invocar os espíritos dos mortos ou praticar feitiçarias deverá ser morto a pedradas. Essa pessoa será responsável pela sua própria morte.

'''

xref:003-levitico/003-levitico-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-levitico/003-levitico-021.adoc#v3-21-0[Próximo Capítulo &#62;]