include::./index.adoc[]

[[v3-16-0]]
=== Levítico, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-16-1]]

^<<v3-16-1,1>>^ Depois que os dois filhos de Arão foram mortos quando apresentavam a Deus, o Senhor , uma oferta de incenso que não estava de acordo com a lei , o Senhor  falou de novo com Moisés.

[[v3-16-2]]

^<<v3-16-2,2>>^ Ele disse: — Diga ao seu irmão Arão que não é a qualquer hora que ele pode entrar no Lugar Santíssimo , que fica atrás da cortina da Tenda Sagrada . Se ele entrar, morrerá, pois é ali que eu apareço numa nuvem acima da tampa da arca da aliança , que é o lugar onde os pecados são perdoados.

[[v3-16-3]]

^<<v3-16-3,3>>^ Arão só poderá entrar no Lugar Santíssimo depois de ter matado um touro novo como oferta para tirar pecados e um carneiro como oferta que será completamente queimada.

[[v3-16-4]]

^<<v3-16-4,4>>^ Antes de entrar, Arão tomará um banho e vestirá as roupas sacerdotais, todas feitas de linho, isto é, os calções, a túnica  e o cinto; e na cabeça ele colocará a mitra , também feita de linho.

[[v3-16-5]]

^<<v3-16-5,5>>^ E Deus deu a Moisés as seguintes leis para o Dia do Perdão : O povo de Israel entregará a Arão dois bodes para a oferta para tirar pecados e um carneiro para a oferta que será completamente queimada.

[[v3-16-6]]

^<<v3-16-6,6>>^ Arão pegará o touro novo da sua própria oferta para tirar pecados e com ela conseguirá o perdão dos seus próprios pecados e dos da sua família.

[[v3-16-7]]

^<<v3-16-7,7>>^ Depois levará os dois bodes até a entrada da Tenda Sagrada. Ali, na presença de Deus, o Senhor ,

[[v3-16-8]]

^<<v3-16-8,8>>^ Arão tirará a sorte entre os dois bodes, usando duas pedras, uma com o nome do Senhor , e a outra com o nome de Azazel .

[[v3-16-9]]

^<<v3-16-9,9>>^ O bode que pertence ao Senhor  será morto por Arão como oferta para tirar pecados,

[[v3-16-10]]

^<<v3-16-10,10>>^ e o bode que pertence a Azazel será oferecido vivo ao Senhor . Depois Arão mandará esse bode para o deserto, a fim de conseguir o perdão dos pecados do povo.

[[v3-16-11]]

^<<v3-16-11,11>>^ Arão pegará o touro novo da sua oferta para tirar pecados e com ela conseguirá o perdão dos seus próprios pecados e dos da sua família. Depois de matar o touro,

[[v3-16-12]]

^<<v3-16-12,12>>^ Arão pegará um queimador de incenso cheio de brasas tiradas do altar que está na presença de Deus, o Senhor , e dois punhados de incenso cheiroso bem moído e entrará no Lugar Santíssimo.

[[v3-16-13]]

^<<v3-16-13,13>>^ Ali, na presença do Senhor , ele porá o incenso no fogo para que a fumaça cubra a tampa da arca da aliança. Assim, Arão não morrerá.

[[v3-16-14]]

^<<v3-16-14,14>>^ Ele pegará um pouco do sangue do touro novo e com o dedo borrifará a parte da tampa que dá para o leste; depois borrifará o sangue sete vezes em frente da arca da aliança.

[[v3-16-15]]

^<<v3-16-15,15>>^ Em seguida Arão matará o bode do sacrifício  para tirar os pecados do povo, levará o sangue para dentro do Lugar Santíssimo e borrifará com ele a tampa da arca e em frente da arca, como fez com o sangue do touro novo.

[[v3-16-16]]

^<<v3-16-16,16>>^ Assim, Arão purificará  o Lugar Santíssimo de todos os pecados, faltas e impurezas do povo de Israel. E fará a mesma coisa para purificar a Tenda Sagrada, que fica no meio do povo impuro .

[[v3-16-17]]

^<<v3-16-17,17>>^ Enquanto Arão estiver no Lugar Santíssimo para fazer a cerimônia de purificação, ninguém deverá entrar na Tenda. Depois que Arão conseguir o perdão dos seus próprios pecados, dos pecados da sua família e dos do povo,

[[v3-16-18]]

^<<v3-16-18,18>>^ então sairá da Tenda, irá até o altar que está em frente dela e fará a cerimônia da purificação do altar. Pegará um pouco do sangue do touro novo e do sangue do bode e o porá nas quatro pontas do altar.

[[v3-16-19]]

^<<v3-16-19,19>>^ Com o dedo borrifará o sangue sete vezes sobre o altar, e assim o purificará das impurezas dos israelitas, e o dedicará ao serviço de Deus.

[[v3-16-20]]

^<<v3-16-20,20>>^ Quando Arão terminar a cerimônia da purificação do Lugar Santíssimo, da Tenda Sagrada e do altar, então pegará o bode para Azazel,

[[v3-16-21]]

^<<v3-16-21,21>>^ porá as mãos na cabeça do animal e confessará todas as culpas e faltas e todos os pecados dos israelitas. Assim, Arão passará para a cabeça do bode os pecados do povo e então mandará o bode para o deserto. Será escolhido um homem para levar o animal,

[[v3-16-22]]

^<<v3-16-22,22>>^ e ele o soltará no deserto. Assim, o bode irá para um lugar onde não mora ninguém, levando os pecados do povo.

[[v3-16-23]]

^<<v3-16-23,23>>^ Em seguida Arão entrará na Tenda, tirará as roupas de sacerdote que havia vestido antes de entrar no Lugar Santíssimo e as deixará ali.

[[v3-16-24]]

^<<v3-16-24,24>>^ Naquele lugar sagrado ele tomará um banho e, depois de se vestir, sairá para apresentar a Deus a sua própria oferta, que será completamente queimada, e a oferta do povo, que também será completamente queimada. Assim, ele conseguirá o perdão dos seus próprios pecados e dos pecados do povo.

[[v3-16-25]]

^<<v3-16-25,25>>^ E queimará no altar a gordura do animal oferecido em sacrifício para tirar pecados.

[[v3-16-26]]

^<<v3-16-26,26>>^ O homem que tiver levado o bode para o deserto deverá lavar a roupa que estiver vestindo e tomar um banho antes de entrar de novo no acampamento.

[[v3-16-27]]

^<<v3-16-27,27>>^ Depois de terminados o sacrifício para tirar os pecados do povo e a cerimônia da purificação do Lugar Santíssimo, feita com o sangue do touro novo e do bode, os corpos desses dois animais serão levados para um lugar fora do acampamento, e o couro, a carne e as tripas serão queimados.

[[v3-16-28]]

^<<v3-16-28,28>>^ O homem que os queimar deverá lavar a roupa que estiver vestindo e tomar um banho antes de entrar de novo no acampamento.

[[v3-16-29]]

^<<v3-16-29,29>>^ A seguinte lei  deverá ser obedecida para sempre: No dia dez do sétimo mês todos os israelitas e os estrangeiros que moram no meio do povo não comerão nada o dia inteiro e não farão nenhum trabalho,

[[v3-16-30]]

^<<v3-16-30,30>>^ pois nesse dia será feito o sacrifício  para conseguir o perdão dos pecados do povo. Assim, o povo ficará puro  na presença de Deus, o Senhor .

[[v3-16-31]]

^<<v3-16-31,31>>^ Este é um dia especial e será para sempre um dia em que ninguém comerá nada, nem trabalhará.

[[v3-16-32]]

^<<v3-16-32,32>>^ O Grande Sacerdote  que for ungido  e ordenado  para tomar o lugar do pai vestirá as roupas sacerdotais de linho

[[v3-16-33]]

^<<v3-16-33,33>>^ e fará a cerimônia para purificar  o Lugar Santíssimo , a Tenda Sagrada , o altar, os sacerdotes e todo o povo.

[[v3-16-34]]

^<<v3-16-34,34>>^ Essa lei será obedecida para sempre, e uma vez por ano haverá a cerimônia para conseguir o perdão dos pecados de todo o povo. E tudo foi feito como o Senhor  havia ordenado a Moisés.

'''

xref:003-levitico/003-levitico-015.adoc#v3-15-0[&#60; Capítulo Anterior] | <<v3-16-0,Topo>> | xref:003-levitico/003-levitico-017.adoc#v3-17-0[Próximo Capítulo &#62;]