include::./index.adoc[]

[[v3-15-0]]
=== Levítico, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-15-1]]

^<<v3-15-1,1>>^ O Senhor  Deus deu a Moisés e a Arão as seguintes leis

[[v3-15-2]]

^<<v3-15-2,2>>^ para o povo de Israel: Quando um homem tiver um corrimento no membro, ele ficará impuro ,

[[v3-15-3]]

^<<v3-15-3,3>>^ tanto se o corrimento vazar do membro como se o corrimento parar nele. De um jeito ou do outro o homem ficará impuro.

[[v3-15-4]]

^<<v3-15-4,4>>^ Qualquer cama em que ele se deitar e tudo aquilo em que se assentar ficarão impuros.

[[v3-15-5]]

^<<v3-15-5,5>>^ Se alguém tocar na cama dele

[[v3-15-6]]

^<<v3-15-6,6>>^ ou se sentar onde ele se sentou, essa pessoa deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impura até o pôr do sol.

[[v3-15-7]]

^<<v3-15-7,7>>^ E quem tocar no homem que tem o corrimento deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impuro até o pôr do sol.

[[v3-15-8]]

^<<v3-15-8,8>>^ Se o homem que tem o corrimento cuspir numa pessoa que está pura , essa pessoa deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impura até o pôr do sol.

[[v3-15-9]]

^<<v3-15-9,9>>^ Qualquer sela que o homem montar se tornará impura.

[[v3-15-10]]

^<<v3-15-10,10>>^ Quem tocar naquilo em que o homem se sentou ficará impuro até o pôr do sol. Se alguém pegar naquilo em que o homem se sentou, deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impuro até o pôr do sol.

[[v3-15-11]]

^<<v3-15-11,11>>^ Se o homem que tem o corrimento tocar numa pessoa sem primeiro lavar as mãos, então aquela pessoa deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impura até o pôr do sol.

[[v3-15-12]]

^<<v3-15-12,12>>^ Qualquer pote de barro que o homem pegar deverá ser quebrado; se for de madeira, deverá ser lavado.

[[v3-15-13]]

^<<v3-15-13,13>>^ Quando o homem sarar, precisará esperar sete dias para se purificar . Passado esse tempo, deverá lavar a roupa que estiver vestindo e tomar um banho em água de uma fonte; então ficará puro .

[[v3-15-14]]

^<<v3-15-14,14>>^ No oitavo dia ele deverá pegar duas rolinhas ou dois pombinhos, ir até a entrada da Tenda Sagrada  e, ali na presença de Deus, o Senhor , entregar as aves ao sacerdote.

[[v3-15-15]]

^<<v3-15-15,15>>^ Este as oferecerá como sacrifício , uma delas como oferta para tirar pecados, e a outra como oferta que será completamente queimada. Assim, na presença do Senhor , o sacerdote fará a cerimônia de purificação, e o homem ficará puro.

[[v3-15-16]]

^<<v3-15-16,16>>^ Quando um homem tiver perda de esperma, deverá tomar um banho e ficará impuro até o pôr do sol.

[[v3-15-17]]

^<<v3-15-17,17>>^ Qualquer roupa ou pedaço de couro em que cair esperma deverá ser lavado e ficará impuro até o pôr do sol.

[[v3-15-18]]

^<<v3-15-18,18>>^ Depois que um homem e uma mulher tiverem relações, os dois deverão tomar um banho e ficarão impuros até o pôr do sol.

[[v3-15-19]]

^<<v3-15-19,19>>^ Quando uma mulher tiver a sua menstruação, ficará impura  sete dias. Quem tocar nela durante esse tempo ficará impuro até o pôr do sol.

[[v3-15-20]]

^<<v3-15-20,20>>^ Qualquer cama em que ela se deitar e qualquer coisa em que se sentar ficarão impuras.

[[v3-15-21]]

^<<v3-15-21,21>>^ Quem tocar na cama em que ela se deitou ou naquilo em que ela se sentou deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impuro até o pôr do sol.

[[v3-15-22]]

^<<v3-15-22,22>>^ Quem tocar na cama em que ela se deitou ou naquilo em que ela se sentou deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impuro até o pôr do sol.

[[v3-15-23]]

^<<v3-15-23,23>>^ Quem tocar na cama em que ela se deitou ou naquilo em que ela se sentou deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impuro até o pôr do sol.

[[v3-15-24]]

^<<v3-15-24,24>>^ E o homem que tiver relações com a mulher durante a menstruação ficará impuro sete dias; e qualquer cama em que ele se deitar ficará impura.

[[v3-15-25]]

^<<v3-15-25,25>>^ A mulher que tiver hemorragia ou que continuar menstruada além do tempo normal ficará impura como durante a menstruação.

[[v3-15-26]]

^<<v3-15-26,26>>^ Qualquer cama em que ela se deitar e qualquer coisa em que se sentar durante esse tempo ficarão impuras.

[[v3-15-27]]

^<<v3-15-27,27>>^ E quem tocar na cama ou naquilo em que ela se sentou ficará impuro e deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impuro até o pôr do sol.

[[v3-15-28]]

^<<v3-15-28,28>>^ Quando a hemorragia parar, ela deverá esperar sete dias e então estará pura .

[[v3-15-29]]

^<<v3-15-29,29>>^ No oitavo dia ela pegará duas rolinhas ou dois pombinhos, irá até a entrada da Tenda Sagrada  e entregará as aves ao sacerdote.

[[v3-15-30]]

^<<v3-15-30,30>>^ Este as oferecerá como sacrifício, uma delas como oferta para tirar pecados, e a outra como oferta que será completamente queimada. Assim, na presença de Deus, o Senhor , o sacerdote fará a cerimônia de purificação , e a mulher ficará pura .

[[v3-15-31]]

^<<v3-15-31,31>>^ Essas leis  são para livrar os israelitas das suas impurezas, a fim de que não morram por tornarem impura a Tenda Sagrada, que fica no meio do acampamento.

'''

xref:003-levitico/003-levitico-014.adoc#v3-14-0[&#60; Capítulo Anterior] | <<v3-15-0,Topo>> | xref:003-levitico/003-levitico-016.adoc#v3-16-0[Próximo Capítulo &#62;]