include::./index.adoc[]

[[v3-8-0]]
=== Levítico, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-8-1]]

^<<v3-8-1,1>>^ O Senhor  Deus disse a Moisés:

[[v3-8-2]]

^<<v3-8-2,2>>^ — Leve Arão e os filhos dele até a entrada da Tenda Sagrada . Pegue as roupas sacerdotais, o azeite de ungir , o touro novo da oferta para tirar pecados, dois carneiros e uma cesta cheia de pães  feitos sem fermento.

[[v3-8-3]]

^<<v3-8-3,3>>^ E mande que o povo todo se reúna em frente da Tenda.

[[v3-8-4]]

^<<v3-8-4,4>>^ Moisés fez o que o Senhor  mandou, e o povo todo se reuniu em frente da Tenda.

[[v3-8-5]]

^<<v3-8-5,5>>^ Aí Moisés lhes disse: — Vou fazer agora o que o Senhor  mandou.

[[v3-8-6]]

^<<v3-8-6,6>>^ Moisés fez com que Arão e os seus filhos chegassem perto dele e mandou que se lavassem.

[[v3-8-7]]

^<<v3-8-7,7>>^ Depois ele vestiu Arão com a túnica , prendeu-a com o cinto e por cima colocou a sobrepeliz . Em seguida pôs o manto sacerdotal  em Arão e o prendeu em volta da cintura com o cinto.

[[v3-8-8]]

^<<v3-8-8,8>>^ Colocou também o peitoral  e nele pôs o Urim e o Tumim .

[[v3-8-9]]

^<<v3-8-9,9>>^ Pôs também a mitra  na cabeça de Arão e na parte da frente da mitra colocou a placa de ouro que era o sinal da ordenação  de Arão como sacerdote. Tudo isso Moisés fez como o Senhor  havia mandado.

[[v3-8-10]]

^<<v3-8-10,10>>^ Em seguida Moisés pegou o azeite sagrado, e ungiu a Tenda Sagrada e tudo o que havia lá dentro, e dessa maneira separou tudo para o serviço de Deus.

[[v3-8-11]]

^<<v3-8-11,11>>^ Sete vezes ele borrifou o altar com o azeite, ungindo assim o altar e todos os seus objetos; ungiu também a pia e a sua base, para dedicá-las a Deus.

[[v3-8-12]]

^<<v3-8-12,12>>^ Depois Moisés derramou o azeite sagrado na cabeça de Arão e assim o ordenou como sacerdote.

[[v3-8-13]]

^<<v3-8-13,13>>^ Em seguida fez com que os filhos de Arão chegassem perto dele. Moisés os vestiu com as túnicas, prendeu-as com os cintos e colocou as mitras na cabeça deles, conforme o Senhor  havia mandado.

[[v3-8-14]]

^<<v3-8-14,14>>^ Então Moisés pegou o bezerro da oferta para tirar pecados, e Arão e os seus filhos puseram as mãos na cabeça do animal.

[[v3-8-15]]

^<<v3-8-15,15>>^ Moisés matou o bezerro, pegou uma parte do sangue e com o dedo pôs o sangue nas quatro pontas do altar. Assim, ele purificou  o altar. Em seguida derramou o resto do sangue na base do altar. Dessa maneira Moisés dedicou e purificou o altar.

[[v3-8-16]]

^<<v3-8-16,16>>^ Depois ele pegou a gordura dos miúdos, a melhor parte do fígado, os rins com a gordura que os cobria e queimou tudo no altar.

[[v3-8-17]]

^<<v3-8-17,17>>^ Levou o resto do animal, incluindo o couro, a carne e as tripas, e queimou tudo num lugar fora do acampamento, conforme o Senhor  havia mandado.

[[v3-8-18]]

^<<v3-8-18,18>>^ Depois Moisés pegou o carneiro que ia ser morto para a oferta queimada, e Arão e os seus filhos puseram as mãos na cabeça do animal.

[[v3-8-19]]

^<<v3-8-19,19>>^ Moisés matou o carneiro e com o sangue borrifou os quatro lados do altar.

[[v3-8-20]]

^<<v3-8-20,20>>^ Ele cortou o animal em pedaços, lavou os miúdos e as pernas traseiras e queimou a cabeça, a gordura e todo o resto do carneiro no altar, como o Senhor  havia mandado. Essa oferta queimada, uma oferta de alimento para o Senhor , produziu um cheiro agradável ao Senhor .

[[v3-8-21]]

^<<v3-8-21,21>>^ Ele cortou o animal em pedaços, lavou os miúdos e as pernas traseiras e queimou a cabeça, a gordura e todo o resto do carneiro no altar, como o Senhor  havia mandado. Essa oferta queimada, uma oferta de alimento para o Senhor , produziu um cheiro agradável ao Senhor .

[[v3-8-22]]

^<<v3-8-22,22>>^ Aí Moisés pegou o outro carneiro, o animal para a ordenação dos sacerdotes, e Arão e os seus filhos puseram as mãos na cabeça do carneiro.

[[v3-8-23]]

^<<v3-8-23,23>>^ Moisés matou o animal e com o dedo pôs uma parte do sangue na ponta da orelha direita de Arão, no dedo polegar da mão direita e no dedão do pé direito.

[[v3-8-24]]

^<<v3-8-24,24>>^ Depois ele fez com que os filhos de Arão chegassem mais perto e pôs sangue na ponta da orelha direita deles, no dedo polegar da mão direita e no dedão do pé direito. Em seguida com o resto do sangue borrifou os quatro lados do altar.

[[v3-8-25]]

^<<v3-8-25,25>>^ Pegou a gordura, o rabo, a gordura que cobria os miúdos, a melhor parte do fígado, os dois rins com a gordura que os cobria e a coxa direita.

[[v3-8-26]]

^<<v3-8-26,26>>^ Pegou também um pão da cesta cheia de pães sem fermento que tinham sido oferecidos a Deus, o Senhor , um pão feito com azeite e um pão pequeno e colocou os três pães sobre a gordura e sobre a coxa direita.

[[v3-8-27]]

^<<v3-8-27,27>>^ Moisés pôs tudo isso nas mãos de Arão e dos seus filhos e apresentou como oferta especial ao Senhor .

[[v3-8-28]]

^<<v3-8-28,28>>^ Depois pegou tudo isso das mãos deles e queimou no altar, em cima da oferta queimada, como uma oferta de ordenação ao sacerdócio. Foi uma oferta de alimento apresentada ao Senhor  e produziu um cheiro agradável a Deus.

[[v3-8-29]]

^<<v3-8-29,29>>^ Em seguida Moisés pegou o peito do animal e o apresentou ao Senhor  como oferta especial. Moisés ficou com essa parte do carneiro, conforme o Senhor  havia mandado.

[[v3-8-30]]

^<<v3-8-30,30>>^ Moisés pegou uma parte do azeite sagrado e uma parte do sangue que estava no altar e os borrifou sobre Arão e a sua roupa e sobre os filhos de Arão e as suas roupas. Assim, ele dedicou ao serviço de Deus Arão e a sua roupa e os filhos de Arão e as suas roupas.

[[v3-8-31]]

^<<v3-8-31,31>>^ Moisés disse a Arão e aos seus filhos: — Levem a carne até a entrada da Tenda Sagrada e ali cozinhem e comam a carne junto com o pão que está na cesta das ofertas feitas para a ordenação. Façam isso conforme as ordens que Deus mandou que eu desse a vocês.

[[v3-8-32]]

^<<v3-8-32,32>>^ Queimem a carne e o pão que sobrarem.

[[v3-8-33]]

^<<v3-8-33,33>>^ Fiquem sete dias ali em frente da Tenda, até se completarem os dias da ordenação ao sacerdócio. São sete dias ao todo.

[[v3-8-34]]

^<<v3-8-34,34>>^ Fizemos hoje o que o Senhor  Deus mandou a fim de conseguir o perdão dos pecados de vocês.

[[v3-8-35]]

^<<v3-8-35,35>>^ Fiquem sete dias e sete noites em frente da Tenda Sagrada. Obedeçam a tudo o que o Senhor  mandou a fim de que não morram. Foi isso o que Deus me mandou dizer.

'''

xref:003-levitico/003-levitico-007.adoc#v3-7-0[&#60; Capítulo Anterior] | <<v3-8-0,Topo>> | xref:003-levitico/003-levitico-009.adoc#v3-9-0[Próximo Capítulo &#62;]