include::./index.adoc[]

[[v3-27-0]]
=== Levítico, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-27-1]]

^<<v3-27-1,1>>^ O Senhor  Deus deu a Moisés

[[v3-27-2]]

^<<v3-27-2,2>>^ as seguintes leis  para o povo de Israel: Quando uma pessoa que foi separada para o serviço do Senhor  Deus quiser ficar livre do seu compromisso, ela pagará um preço certo,

[[v3-27-3]]

^<<v3-27-3,3>>^ de acordo com a tabela oficial. Os homens de vinte a sessenta anos de idade pagarão cinquenta barras de prata ,

[[v3-27-4]]

^<<v3-27-4,4>>^ e as mulheres da mesma idade pagarão trinta.

[[v3-27-5]]

^<<v3-27-5,5>>^ Os jovens de cinco a vinte anos de idade pagarão vinte barras de prata, e as jovens pagarão dez.

[[v3-27-6]]

^<<v3-27-6,6>>^ Os meninos de um mês a cinco anos pagarão cinco barras de prata, e as meninas pagarão três.

[[v3-27-7]]

^<<v3-27-7,7>>^ Os homens de sessenta anos para cima pagarão quinze barras de prata, e as mulheres pagarão dez.

[[v3-27-8]]

^<<v3-27-8,8>>^ Se a pessoa for pobre e não puder pagar a quantia marcada, ela irá falar com o sacerdote, e ele cobrará o que a pessoa puder pagar.

[[v3-27-9]]

^<<v3-27-9,9>>^ Quando alguém promete a Deus, o Senhor , um animal que pode ser oferecido em sacrifício , esse animal é considerado sagrado

[[v3-27-10]]

^<<v3-27-10,10>>^ e não poderá ser trocado por outro, seja melhor ou pior. Mas, se houver troca, então os dois animais pertencem ao Senhor .

[[v3-27-11]]

^<<v3-27-11,11>>^ Se o animal for impuro , isto é, um dos animais que o Senhor  não aceita, então o dono o levará ao sacerdote

[[v3-27-12]]

^<<v3-27-12,12>>^ para que ele veja quanto vale. O sacerdote dará o preço de acordo com a condição do animal.

[[v3-27-13]]

^<<v3-27-13,13>>^ Se o dono quiser tornar a comprar o animal, ele pagará o preço, mais um quinto.

[[v3-27-14]]

^<<v3-27-14,14>>^ Quando alguém dedicar a sua casa a Deus, o Senhor , o sacerdote fará a avaliação da casa de acordo com a sua condição e dará o preço.

[[v3-27-15]]

^<<v3-27-15,15>>^ Se o dono quiser tornar a comprar a casa, pagará o preço, mais um quinto.

[[v3-27-16]]

^<<v3-27-16,16>>^ Se alguém oferecer para o serviço de Deus, o Senhor , uma parte dos terrenos que recebeu do pai, o sacerdote fará a avaliação do terreno de acordo com a quantidade de sementes necessária para semeá-lo, na base de cinquenta barras de prata por cem quilos de cevada .

[[v3-27-17]]

^<<v3-27-17,17>>^ Se ele dedicar o terreno a Deus no Ano da Libertação, o terreno valerá o preço máximo;

[[v3-27-18]]

^<<v3-27-18,18>>^ mas, se for depois do Ano da Libertação, o sacerdote calculará o seu valor, tendo como base os anos que ainda faltarem para o seguinte Ano da Libertação, e assim o preço será mais baixo.

[[v3-27-19]]

^<<v3-27-19,19>>^ Se o dono do terreno quiser tornar a comprá-lo, ele pagará o preço calculado, mais um quinto.

[[v3-27-20]]

^<<v3-27-20,20>>^ Mas, se não quiser tornar a comprá-lo ou se outra pessoa o comprar, ele perderá o direito de tornar a comprá-lo.

[[v3-27-21]]

^<<v3-27-21,21>>^ No Ano da Libertação, quando o terreno ficar livre, ele será oferecido para o serviço de Deus, o Senhor ; é um terreno sagrado que pertence aos sacerdotes.

[[v3-27-22]]

^<<v3-27-22,22>>^ Se alguém oferecer para o serviço de Deus, o Senhor , um terreno que comprou,

[[v3-27-23]]

^<<v3-27-23,23>>^ o sacerdote calculará o valor do terreno, tendo como base os anos que ainda faltarem para o Ano da Libertação. Nesse mesmo dia o homem pagará o preço total e oferecerá o dinheiro para o serviço do Senhor .

[[v3-27-24]]

^<<v3-27-24,24>>^ No seguinte Ano da Libertação o terreno voltará a pertencer ao seu dono, isto é, ao homem que o recebeu como herança.

[[v3-27-25]]

^<<v3-27-25,25>>^ Todos os preços serão calculados de acordo com a tabela oficial; a barra padrão, o siclo, vale vinte geras.

[[v3-27-26]]

^<<v3-27-26,26>>^ A primeira cria das vacas, ovelhas ou cabras pertence a Deus, o Senhor . Portanto, ninguém poderá oferecê-la ao Senhor , pois já pertence a ele.

[[v3-27-27]]

^<<v3-27-27,27>>^ Mas a primeira cria de um animal impuro poderá ser comprada de novo; deverá ser pago o preço da tabela, mais um quinto. Se não for comprada de novo, a cria poderá ser vendida pelo preço da tabela.

[[v3-27-28]]

^<<v3-27-28,28>>^ Ninguém poderá vender ou tornar a comprar uma coisa, seja pessoa, animal ou terreno, que tiver sido dedicada para ser usada somente no serviço de Deus, o Senhor  . É uma coisa sagrada e pertence completamente ao Senhor .

[[v3-27-29]]

^<<v3-27-29,29>>^ Nem mesmo uma pessoa que tenha sido dedicada assim poderá ser comprada de novo; ela será morta.

[[v3-27-30]]

^<<v3-27-30,30>>^ A décima parte das colheitas, tanto dos cereais como das frutas, pertence a Deus, o Senhor , e será dada a ele.

[[v3-27-31]]

^<<v3-27-31,31>>^ Se o dono quiser tornar a comprar alguma porção dessa décima parte, pagará o preço marcado, mais um quinto.

[[v3-27-32]]

^<<v3-27-32,32>>^ De cada dez animais domésticos um pertence a Deus, o Senhor . Quando o dono contar o seu gado e as suas ovelhas e cabras, cada décimo animal pertencerá ao Senhor ,

[[v3-27-33]]

^<<v3-27-33,33>>^ qualquer que seja a condição do animal. O dono não poderá trocar um animal por outro. Mas, se houver troca, então os dois animais pertencem ao Senhor  e não poderão ser comprados de novo.

[[v3-27-34]]

^<<v3-27-34,34>>^ Foram esses os mandamentos que o Senhor  Deus deu a Moisés, no monte Sinai, para o povo de Israel.

'''

xref:003-levitico/003-levitico-026.adoc#v3-26-0[&#60; Capítulo Anterior] | <<v3-27-0,Topo>> | xref:004-numeros/004-numeros-001.adoc#v4-1-0[Próximo Capítulo &#62;]