include::./index.adoc[]

[[v3-14-0]]
=== Levítico, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-14-1]]

^<<v3-14-1,1>>^ O Senhor  Deus deu a Moisés

[[v3-14-2]]

^<<v3-14-2,2>>^ as seguintes leis  a respeito da cerimônia de purificação  das pessoas que sararam de doenças contagiosas da pele: A pessoa será levada ao sacerdote,

[[v3-14-3]]

^<<v3-14-3,3>>^ e este sairá com ela do acampamento e a examinará. Se a pessoa tiver sarado,

[[v3-14-4]]

^<<v3-14-4,4>>^ o sacerdote mandará trazer duas aves puras , um pedaço de madeira de cedro, lã tingida de vermelho e um galho de hissopo .

[[v3-14-5]]

^<<v3-14-5,5>>^ O sacerdote mandará que matem uma das aves em cima de um pote de barro cheio de água tirada de uma fonte.

[[v3-14-6]]

^<<v3-14-6,6>>^ Depois ele pegará a outra ave, o pedaço de madeira de cedro, a lã tingida de vermelho e o hissopo e os mergulhará no sangue da ave que foi morta.

[[v3-14-7]]

^<<v3-14-7,7>>^ Em seguida borrifará com o sangue sete vezes a pessoa que está sendo purificada e declarará que ela está pura. Depois disso o sacerdote soltará no campo a ave viva.

[[v3-14-8]]

^<<v3-14-8,8>>^ Aí a pessoa deverá lavar a roupa que estiver vestindo, rapar todos os cabelos e pelos e tomar um banho; então estará pura. Depois entrará no acampamento, mas deverá ficar sete dias fora da sua barraca.

[[v3-14-9]]

^<<v3-14-9,9>>^ No sétimo dia ela deverá rapar de novo a cabeça, a barba, as sobrancelhas e todos os outros pelos do corpo, lavar a roupa que estiver vestindo e tomar um banho; então estará pura.

[[v3-14-10]]

^<<v3-14-10,10>>^ No dia seguinte a pessoa pegará dois carneirinhos e uma ovelhinha de um ano de idade, todos sem defeito. Para a oferta de cereais ela pegará três quilos de farinha misturada com azeite e mais um quarto de litro de azeite.

[[v3-14-11]]

^<<v3-14-11,11>>^ O sacerdote levará a pessoa e as suas ofertas até a entrada da Tenda Sagrada  e ali, na presença de Deus, o Senhor ,

[[v3-14-12]]

^<<v3-14-12,12>>^ pegará um dos carneirinhos e o azeite, e os oferecerá como sacrifício para tirar culpas. É uma oferta especial ao Senhor  e pertence ao sacerdote.

[[v3-14-13]]

^<<v3-14-13,13>>^ Depois matará o carneirinho num lugar sagrado, onde são mortos os animais das ofertas para tirar culpas e das ofertas que são completamente queimadas. O sacerdote deverá fazer isso porque a oferta para tirar culpas é como a oferta para tirar pecados: é uma coisa muito sagrada e pertence ao sacerdote.

[[v3-14-14]]

^<<v3-14-14,14>>^ O sacerdote pegará um pouco do sangue do animal e com o dedo o passará na ponta da orelha direita, no dedo polegar da mão direita e no dedão do pé direito da pessoa que está sendo purificada.

[[v3-14-15]]

^<<v3-14-15,15>>^ Depois derramará uma parte do azeite na palma da sua mão esquerda,

[[v3-14-16]]

^<<v3-14-16,16>>^ molhará um dedo da mão direita no azeite e o borrifará sete vezes ali na presença do Senhor .

[[v3-14-17]]

^<<v3-14-17,17>>^ Em seguida porá com o dedo um pouco de azeite na pessoa que está sendo purificada, nos mesmos lugares em que pôs o sangue do animal, isto é, na ponta da orelha direita, no dedo polegar da mão direita e no dedão do pé direito.

[[v3-14-18]]

^<<v3-14-18,18>>^ O resto do azeite ele derramará na cabeça da pessoa. Assim, na presença do Senhor , o sacerdote conseguirá o perdão dos pecados daquela pessoa.

[[v3-14-19]]

^<<v3-14-19,19>>^ Depois o sacerdote oferecerá o sacrifício para tirar pecados, conseguindo com isso o perdão dos pecados da pessoa que está sendo purificada. Em seguida ele matará o animal para a oferta que vai ser completamente queimada

[[v3-14-20]]

^<<v3-14-20,20>>^ e o oferecerá no altar, junto com a oferta de cereais. Assim, o sacerdote conseguirá o perdão dos pecados daquela pessoa, e ela estará pura.

[[v3-14-21]]

^<<v3-14-21,21>>^ Se a pessoa for pobre e não puder pagar tudo, ela levará ao sacerdote um carneirinho para a oferta para tirar culpas, que é uma oferta especial dedicada ao Senhor  e que pertence ao sacerdote. Levará só um quilo de farinha misturada com azeite e mais um quarto de litro de azeite

[[v3-14-22]]

^<<v3-14-22,22>>^ e duas rolinhas ou dois pombinhos, conforme as suas posses. Uma das aves será a oferta para tirar pecados, e a outra será a oferta que vai ser completamente queimada.

[[v3-14-23]]

^<<v3-14-23,23>>^ No oitavo dia do tempo da sua purificação, a pessoa levará tudo isso até a entrada da Tenda Sagrada e entregará ao sacerdote. Então ali na presença do Senhor

[[v3-14-24]]

^<<v3-14-24,24>>^ o sacerdote pegará o carneirinho e o azeite e os oferecerá ao Senhor  como uma oferta especial que pertence ao sacerdote.

[[v3-14-25]]

^<<v3-14-25,25>>^ Em seguida matará o carneirinho, pegará um pouco do sangue do animal e com o dedo o colocará na ponta da orelha direita, no dedo polegar da mão direita e no dedão do pé direito da pessoa que está sendo purificada.

[[v3-14-26]]

^<<v3-14-26,26>>^ Depois derramará uma parte do azeite na palma da sua mão esquerda

[[v3-14-27]]

^<<v3-14-27,27>>^ e com um dedo da mão direita borrifará o azeite sete vezes ali na presença de Deus, o Senhor .

[[v3-14-28]]

^<<v3-14-28,28>>^ Então, com o dedo, porá um pouco do azeite na pessoa que está sendo purificada, nos mesmos lugares em que pôs o sangue do animal, isto é, na ponta da orelha direita, no dedo polegar da mão direita e no dedão do pé direito.

[[v3-14-29]]

^<<v3-14-29,29>>^ O resto do azeite ele derramará na cabeça da pessoa e assim na presença do Senhor  conseguirá o perdão dos pecados dela.

[[v3-14-30]]

^<<v3-14-30,30>>^ Depois, conforme as posses dessa pessoa, o sacerdote oferecerá as duas rolinhas ou os dois pombinhos.

[[v3-14-31]]

^<<v3-14-31,31>>^ Uma das aves será a oferta para tirar pecados, e a outra será a oferta que vai ser completamente queimada. Assim, na presença de Deus, o Senhor , o sacerdote conseguirá o perdão dos pecados da pessoa que está sendo purificada.

[[v3-14-32]]

^<<v3-14-32,32>>^ Esta é a lei  para a purificação das pessoas que sararam de uma doença contagiosa da pele, mas que não têm recursos para comprar tudo o que a lei exige.

[[v3-14-33]]

^<<v3-14-33,33>>^ O Senhor  Deus deu a Moisés e a Arão

[[v3-14-34]]

^<<v3-14-34,34>>^ as seguintes leis  a respeito de mofo nas casas. Essas leis deviam ser obedecidas depois que o povo de Israel tivesse entrado na terra de Canaã, que Deus lhes daria para ser deles. Quando Deus fizer aparecer mofo na casa de alguém,

[[v3-14-35]]

^<<v3-14-35,35>>^ o dono irá falar com o sacerdote e dirá que descobriu mofo na sua casa.

[[v3-14-36]]

^<<v3-14-36,36>>^ Antes de ir examiná-la, o sacerdote mandará que tirem tudo da casa; se não, tudo o que estiver lá dentro será considerado impuro . Depois o sacerdote irá até a casa

[[v3-14-37]]

^<<v3-14-37,37>>^ e examinará o mofo. Se houver manchas esverdeadas ou avermelhadas nas paredes, e, se parecer que entraram nas paredes,

[[v3-14-38]]

^<<v3-14-38,38>>^ então o sacerdote sairá da casa e a deixará fechada sete dias.

[[v3-14-39]]

^<<v3-14-39,39>>^ No sétimo dia ele voltará e examinará a casa de novo. Se descobrir que as manchas se espalharam pelas paredes,

[[v3-14-40]]

^<<v3-14-40,40>>^ mandará que tirem as pedras em que está o mofo e as joguem fora da cidade, num lugar impuro.

[[v3-14-41]]

^<<v3-14-41,41>>^ Mandará raspar as paredes de dentro da casa, e o reboco raspado será levado para um lugar impuro fora da cidade.

[[v3-14-42]]

^<<v3-14-42,42>>^ Depois colocarão pedras novas no lugar das que foram tiradas e rebocarão de novo a casa.

[[v3-14-43]]

^<<v3-14-43,43>>^ Se, depois de se fazer tudo isso, aparecer mofo na casa outra vez,

[[v3-14-44]]

^<<v3-14-44,44>>^ o sacerdote a examinará. Se as manchas se tiverem espalhado pelas paredes, é mofo contagioso, e a casa está impura.

[[v3-14-45]]

^<<v3-14-45,45>>^ Ela será derrubada, e as pedras, a madeira e o reboco serão levados para um lugar impuro fora da cidade.

[[v3-14-46]]

^<<v3-14-46,46>>^ Quem entrar na casa durante os sete dias em que estiver fechada ficará impuro até o pôr do sol.

[[v3-14-47]]

^<<v3-14-47,47>>^ E, se nesse tempo alguém se deitar na casa ou comer ali dentro, deverá lavar a roupa que estiver vestindo.

[[v3-14-48]]

^<<v3-14-48,48>>^ Mas, se o sacerdote voltar, e examinar a casa depois de rebocada, e não encontrar mofo nas paredes, ele declarará que ela está pura , pois o mofo desapareceu completamente.

[[v3-14-49]]

^<<v3-14-49,49>>^ A fim de purificar  a casa, o sacerdote pegará duas aves, um pedaço de madeira de cedro, lã tingida de vermelho e um galho de hissopo

[[v3-14-50]]

^<<v3-14-50,50>>^ e matará uma das aves em cima de um pote de barro cheio de água tirada de uma fonte.

[[v3-14-51]]

^<<v3-14-51,51>>^ Depois pegará a outra ave, o pedaço de madeira de cedro, a lã tingida de vermelho e o hissopo, e os mergulhará primeiro no sangue da ave que foi morta e depois na água fresca, e borrifará a casa sete vezes.

[[v3-14-52]]

^<<v3-14-52,52>>^ Assim, ele purificará a casa com o sangue da ave, a água fresca, a ave viva, o pedaço de madeira de cedro, o hissopo e a lã tingida de vermelho.

[[v3-14-53]]

^<<v3-14-53,53>>^ Depois levará a ave viva para fora da cidade e a soltará no campo. Assim, o sacerdote fará a cerimônia de purificação, e a casa ficará pura.

[[v3-14-54]]

^<<v3-14-54,54>>^ São essas as leis para todas as doenças contagiosas da pele e da cabeça; para inchações, tumores e manchas na pele; para o mofo na roupa e nas casas.

[[v3-14-55]]

^<<v3-14-55,55>>^ São essas as leis para todas as doenças contagiosas da pele e da cabeça; para inchações, tumores e manchas na pele; para o mofo na roupa e nas casas.

'''

xref:003-levitico/003-levitico-013.adoc#v3-13-0[&#60; Capítulo Anterior] | <<v3-14-0,Topo>> | xref:003-levitico/003-levitico-015.adoc#v3-15-0[Próximo Capítulo &#62;]