include::./index.adoc[]

[[v3-19-0]]
=== Levítico, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-19-1]]

^<<v3-19-1,1>>^ O Senhor  Deus mandou Moisés

[[v3-19-2]]

^<<v3-19-2,2>>^ dizer ao povo de Israel o seguinte: — Sejam santos , pois eu, o Senhor , o Deus de vocês, sou santo.

[[v3-19-3]]

^<<v3-19-3,3>>^ Cada um respeite a sua mãe e o seu pai, e todos guardem o sábado. Eu sou o Senhor , o Deus de vocês.

[[v3-19-4]]

^<<v3-19-4,4>>^ — Não adorem ídolos, nem façam deuses de metal. Eu sou o Senhor , o Deus de vocês.

[[v3-19-5]]

^<<v3-19-5,5>>^ — Quando matarem um animal para uma oferta de paz, façam como eu mandei, e assim eu aceitarei a oferta.

[[v3-19-6]]

^<<v3-19-6,6>>^ A carne deverá ser comida no dia em que o animal for morto ou então no dia seguinte. Mas, se sobrar carne para o terceiro dia, ela deverá ser queimada,

[[v3-19-7]]

^<<v3-19-7,7>>^ pois ficou impura . Se alguém comer a carne nesse dia, eu não aceitarei a oferta,

[[v3-19-8]]

^<<v3-19-8,8>>^ e a pessoa que comeu deverá ser castigada, pois profanou  aquilo que para mim é sagrado. Essa pessoa será expulsa do meio do povo de Israel.

[[v3-19-9]]

^<<v3-19-9,9>>^ — Quando fizerem a colheita do trigo, não colham as espigas dos pés que ficam na beira do campo, nem voltem atrás para pegar as espigas que não tiverem sido colhidas.

[[v3-19-10]]

^<<v3-19-10,10>>^ E não façam uma segunda colheita nas plantações de uvas, para colher os cachos que ficaram, nem voltem atrás para catar os cachos que tiverem caído no chão. Deixem isso para os pobres e para os estrangeiros. Eu sou o Senhor , o Deus de vocês.

[[v3-19-11]]

^<<v3-19-11,11>>^ — Não roube, não minta e não engane os outros.

[[v3-19-12]]

^<<v3-19-12,12>>^ Não faça juramentos falsos em meu nome, pois isso é profanar o meu nome. Eu sou o Senhor .

[[v3-19-13]]

^<<v3-19-13,13>>^ — Não explore, nem roube os outros. Não segure até o dia seguinte o pagamento do trabalhador diarista.

[[v3-19-14]]

^<<v3-19-14,14>>^ Não amaldiçoe um surdo, nem ponha na frente de um cego alguma coisa que o faça tropeçar. Tenha respeito para comigo, o seu Deus. Eu sou o Senhor .

[[v3-19-15]]

^<<v3-19-15,15>>^ — Quando julgar alguma causa, não seja injusto; não favoreça os humildes, nem procure agradar os poderosos. Julgue todas as causas com justiça.

[[v3-19-16]]

^<<v3-19-16,16>>^ Não ande espalhando mentiras no meio do povo, nem faça uma acusação falsa que possa causar a morte de alguém. Eu sou o Senhor .

[[v3-19-17]]

^<<v3-19-17,17>>^ — Não guarde ódio no coração contra outro israelita, mas corrija-o com franqueza para que você não acabe cometendo um pecado por causa dele.

[[v3-19-18]]

^<<v3-19-18,18>>^ Não se vingue, nem guarde ódio de alguém do seu povo, mas ame os outros como você ama a você mesmo. Eu sou o Senhor .

[[v3-19-19]]

^<<v3-19-19,19>>^ — Obedeçam às minhas leis . Não cruzem animais domésticos de espécies diferentes. Não semeiem tipos diferentes de semente no mesmo campo. Não vistam roupas feitas de tipos diferentes de tecidos.

[[v3-19-20]]

^<<v3-19-20,20>>^ — Se um homem tiver relações com uma escrava que já foi prometida para ser a concubina  de outro homem, mas que ainda não foi comprada, nem posta em liberdade, o homem e a escrava serão castigados, mas não serão mortos, pois ela ainda não estava em liberdade.

[[v3-19-21]]

^<<v3-19-21,21>>^ Nesse caso, para tirar a sua culpa, o homem deverá apresentar como oferta a Deus, o Senhor , um carneiro, que ele levará até a entrada da Tenda Sagrada .

[[v3-19-22]]

^<<v3-19-22,22>>^ Ali, na presença do Senhor , o sacerdote oferecerá o carneiro a Deus e assim conseguirá o perdão do pecado que o homem cometeu.

[[v3-19-23]]

^<<v3-19-23,23>>^ — Quando vocês estiverem morando na terra de Canaã e plantarem árvores frutíferas, não comam as frutas que as árvores derem nos primeiros três anos; essas frutas são impuras.

[[v3-19-24]]

^<<v3-19-24,24>>^ No quarto ano as frutas serão dedicadas a mim, o Senhor , como oferta de louvor.

[[v3-19-25]]

^<<v3-19-25,25>>^ No quinto ano vocês poderão comer as frutas, e assim as árvores produzirão cada vez mais. Eu sou o Senhor , o Deus de vocês.

[[v3-19-26]]

^<<v3-19-26,26>>^ — Não comam carne em que houver sangue. Não procurem adivinhar o futuro, nem façam feitiçarias.

[[v3-19-27]]

^<<v3-19-27,27>>^ Não cortem o cabelo dos lados da cabeça, nem aparem a barba.

[[v3-19-28]]

^<<v3-19-28,28>>^ Quando chorarem a morte de alguém, não se cortem, nem façam marcas no corpo. Eu sou o Senhor .

[[v3-19-29]]

^<<v3-19-29,29>>^ — Não desonrem as suas filhas entregando-as para serem prostitutas nos templos pagãos . Isso encheria a terra de idolatria e de pecado.

[[v3-19-30]]

^<<v3-19-30,30>>^ Guardem o sábado, que é um dia sagrado, e respeitem o lugar onde sou adorado. Eu sou o Senhor .

[[v3-19-31]]

^<<v3-19-31,31>>^ — Não procurem a ajuda dos que invocam os espíritos dos mortos e dos que adivinham o futuro. Isso é pecado e fará com que vocês fiquem impuros. Eu sou o Senhor , o Deus de vocês.

[[v3-19-32]]

^<<v3-19-32,32>>^ — Fiquem de pé na presença das pessoas idosas e as tratem com todo o respeito; e honrem a mim, o Deus de vocês. Eu sou o Senhor .

[[v3-19-33]]

^<<v3-19-33,33>>^ — Não maltratem os estrangeiros que vivem na terra de vocês.

[[v3-19-34]]

^<<v3-19-34,34>>^ Eles devem ser tratados como se fossem israelitas; amem os estrangeiros, pois vocês foram estrangeiros no Egito e devem amá-los como vocês amam a vocês mesmos. Eu sou o Senhor , o Deus de vocês.

[[v3-19-35]]

^<<v3-19-35,35>>^ — Não prejudiquem os outros, usando medidas falsas de comprimento, peso ou capacidade.

[[v3-19-36]]

^<<v3-19-36,36>>^ Usem balanças certas, pesos certos e medidas certas. Eu sou o Senhor , o Deus de vocês. Eu os tirei do Egito.

[[v3-19-37]]

^<<v3-19-37,37>>^ — Obedeçam às minhas leis e aos meus mandamentos. Eu sou o Senhor .

'''

xref:003-levitico/003-levitico-018.adoc#v3-18-0[&#60; Capítulo Anterior] | <<v3-19-0,Topo>> | xref:003-levitico/003-levitico-020.adoc#v3-20-0[Próximo Capítulo &#62;]