include::./index.adoc[]

[[v3-17-0]]
=== Levítico, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-17-1]]

^<<v3-17-1,1>>^ O Senhor  Deus mandou Moisés

[[v3-17-2]]

^<<v3-17-2,2>>^ dar a Arão, aos filhos de Arão e a todo o povo de Israel as seguintes leis :

[[v3-17-3]]

^<<v3-17-3,3>>^ Se um israelita matar um boi, ou um carneirinho, ou um cabrito dentro ou fora do acampamento

[[v3-17-4]]

^<<v3-17-4,4>>^ e não levar o animal até a entrada da Tenda Sagrada  para oferecê-lo como sacrifício  a Deus, o Senhor , esse homem será expulso do meio do povo de Israel. Ele é culpado; é como se tivesse matado uma pessoa.

[[v3-17-5]]

^<<v3-17-5,5>>^ Portanto, os israelitas, em vez de matarem os animais no campo, deverão levá-los ao sacerdote, em frente da Tenda Sagrada. Ali matarão os animais e os apresentarão ao Senhor  como oferta de paz.

[[v3-17-6]]

^<<v3-17-6,6>>^ O sacerdote borrifará com o sangue o altar que fica em frente da Tenda Sagrada e ali queimará a gordura do animal. O cheiro dessa oferta é agradável ao Senhor .

[[v3-17-7]]

^<<v3-17-7,7>>^ Daqui em diante e para sempre, os israelitas nunca mais oferecerão sacrifícios aos demônios do deserto; pois, se fizerem isso, estarão sendo infiéis a Deus.

[[v3-17-8]]

^<<v3-17-8,8>>^ Todos os israelitas e todos os estrangeiros que vivem no meio do povo de Israel apresentarão ao Senhor  as suas ofertas que são completamente queimadas ou qualquer outro sacrifício

[[v3-17-9]]

^<<v3-17-9,9>>^ somente na entrada da Tenda Sagrada e em nenhum outro lugar. Quem desobedecer será expulso do meio do povo.

[[v3-17-10]]

^<<v3-17-10,10>>^ Se um israelita ou um estrangeiro que vive no meio do povo de Israel comer sangue, Deus ficará contra ele e o expulsará do meio do povo.

[[v3-17-11]]

^<<v3-17-11,11>>^ Pois a vida de todo ser vivente está no sangue. É por isso que Deus mandou que o sangue dos animais oferecidos como sacrifício  fosse derramado no altar a fim de conseguir o perdão dos pecados do povo. Pois é o sangue, isto é, a vida, que tira os pecados.

[[v3-17-12]]

^<<v3-17-12,12>>^ Por isso o Senhor  diz que nenhum israelita e nenhum estrangeiro que vive no meio do povo podem comer sangue.

[[v3-17-13]]

^<<v3-17-13,13>>^ Quando um israelita ou um estrangeiro que vive no meio do povo caçar um animal ou uma ave que se pode comer, ele deverá deixar que o sangue corra para o chão e depois deverá cobri-lo com terra.

[[v3-17-14]]

^<<v3-17-14,14>>^ A vida de todo ser vivente está no sangue, e é por isso que Deus diz aos israelitas que não comam o sangue de nenhum animal, pois o sangue é a vida. Quem comer sangue será expulso do meio do povo de Israel.

[[v3-17-15]]

^<<v3-17-15,15>>^ Qualquer um, seja israelita ou estrangeiro, que comer a carne de um animal que tenha tido morte natural ou que tenha sido morto por outros animais deverá lavar a roupa que estiver vestindo e tomar um banho; e ficará impuro  até o pôr do sol. Depois ficará puro  de novo.

[[v3-17-16]]

^<<v3-17-16,16>>^ Mas, se não lavar a roupa e se não tomar um banho, essa pessoa será castigada.

'''

xref:003-levitico/003-levitico-016.adoc#v3-16-0[&#60; Capítulo Anterior] | <<v3-17-0,Topo>> | xref:003-levitico/003-levitico-018.adoc#v3-18-0[Próximo Capítulo &#62;]