include::./index.adoc[]

[[v3-5-0]]
=== Levítico, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-5-1]]

^<<v3-5-1,1>>^ Os casos em que é preciso oferecer sacrifício  são os seguintes: Se alguém for chamado como testemunha, mas não disser aquilo que viu ou que ouviu falar, então será culpado e merecerá castigo.

[[v3-5-2]]

^<<v3-5-2,2>>^ Se alguém, por descuido, tocar em qualquer coisa impura , como, por exemplo, o corpo morto de um animal impuro, seja selvagem ou doméstico, ou de um animal que se arrasta pelo chão, então essa pessoa ficará impura também e será culpada.

[[v3-5-3]]

^<<v3-5-3,3>>^ Se alguém, por descuido, tocar numa coisa impura que venha de uma pessoa, seja o que for, ele ficará impuro e, logo que perceber o que fez, ficará sendo culpado.

[[v3-5-4]]

^<<v3-5-4,4>>^ Se alguém, sem pensar no que está dizendo, jurar que vai fazer alguma coisa, seja boa ou má — um desses juramentos que a gente faz sem pensar — então será culpado logo que compreender o que fez.

[[v3-5-5]]

^<<v3-5-5,5>>^ Portanto, quando alguém for culpado de qualquer uma dessas coisas, deverá confessar o seu pecado

[[v3-5-6]]

^<<v3-5-6,6>>^ e trazer a Deus, o Senhor , um animal como sacrifício para tirar a culpa do pecado que cometeu. O animal deve ser uma ovelha ou uma cabra, e o sacerdote oferecerá o animal em sacrifício para conseguir o perdão do pecado que a pessoa cometeu.

[[v3-5-7]]

^<<v3-5-7,7>>^ Se alguém não tiver recursos para comprar uma ovelha ou uma cabra, então apresentará a Deus, o Senhor , duas rolinhas ou dois pombinhos como oferta para tirar a culpa do pecado que cometeu. Uma das aves será o sacrifício para tirar pecados, e a outra será uma oferta a ser completamente queimada.

[[v3-5-8]]

^<<v3-5-8,8>>^ A pessoa entregará as duas aves ao sacerdote, e este oferecerá primeiro a ave que é o sacrifício para tirar pecados. O sacerdote quebrará o pescoço dela, sem tirar a cabeça,

[[v3-5-9]]

^<<v3-5-9,9>>^ e borrifará o lado do altar com uma parte do sangue. Depois deixará o sangue da ave escorrer na base do altar. Esta é a oferta para tirar pecados.

[[v3-5-10]]

^<<v3-5-10,10>>^ Em seguida o sacerdote oferecerá a outra ave como uma oferta que será completamente queimada, conforme a lei  manda. Assim, o sacerdote oferecerá esse sacrifício para conseguir o perdão de pecados, e a pessoa será perdoada.

[[v3-5-11]]

^<<v3-5-11,11>>^ Se alguém não tiver recursos para comprar duas rolinhas ou dois pombinhos, então trará um quilo da melhor farinha como sua oferta para tirar pecados. Não deverá misturar azeite ou incenso com a farinha, pois é uma oferta para tirar pecados.

[[v3-5-12]]

^<<v3-5-12,12>>^ O sacerdote receberá dessa pessoa a farinha, pegará um punhado e o queimará no altar, em cima das ofertas de alimento apresentadas a Deus, o Senhor . Isso lembra que a oferta toda é dada a Deus. É um sacrifício para tirar pecados.

[[v3-5-13]]

^<<v3-5-13,13>>^ Assim, o sacerdote oferecerá esse sacrifício para conseguir o perdão do pecado que a pessoa cometeu, e ela será perdoada. E, como no caso das ofertas de cereais, o resto da farinha será do sacerdote.

[[v3-5-14]]

^<<v3-5-14,14>>^ O Senhor  Deus deu a Moisés as seguintes ordens:

[[v3-5-15]]

^<<v3-5-15,15>>^ Se alguém, sem querer, cometer o pecado de não entregar as ofertas sagradas que pertencem a Deus, o Senhor , então, para pagar a dívida, a pessoa precisará trazer um carneiro sem defeito para oferecer ao Senhor . O preço do animal será calculado de acordo com a tabela de preços usada no santuário. O animal é um sacrifício  para tirar a culpa da pessoa.

[[v3-5-16]]

^<<v3-5-16,16>>^ Além disso, a pessoa precisará entregar ao sacerdote a oferta sagrada que deixou de pagar, mais um quinto. O sacerdote pegará o carneiro que é dado para tirar a culpa e o oferecerá como sacrifício para conseguir o perdão do pecado que a pessoa cometeu; assim, ela será perdoada.

[[v3-5-17]]

^<<v3-5-17,17>>^ Se alguém, sem querer, pecar e desobedecer a qualquer uma das leis  de Deus, o Senhor , fazendo o que é proibido, ele será considerado culpado e deverá ser castigado.

[[v3-5-18]]

^<<v3-5-18,18>>^ E, para tirar a sua culpa, ele levará um carneiro sem defeito ao sacerdote. O valor do animal será calculado de acordo com a tabela de preços usada no santuário. O sacerdote oferecerá o animal como sacrifício para conseguir o perdão do pecado que a pessoa cometeu sem querer, e ela será perdoada.

[[v3-5-19]]

^<<v3-5-19,19>>^ Ela é culpada de ter pecado contra o Senhor , e essa oferta é para tirar a sua culpa.

'''

xref:003-levitico/003-levitico-004.adoc#v3-4-0[&#60; Capítulo Anterior] | <<v3-5-0,Topo>> | xref:003-levitico/003-levitico-006.adoc#v3-6-0[Próximo Capítulo &#62;]