include::./index.adoc[]

[[v3-11-0]]
=== Levítico, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-11-1]]

^<<v3-11-1,1>>^ O Senhor  Deus deu a Moisés e a Arão

[[v3-11-2]]

^<<v3-11-2,2>>^ as seguintes leis  para os israelitas: Vocês poderão comer a carne de qualquer animal

[[v3-11-3]]

^<<v3-11-3,3>>^ que tem casco dividido e que rumina.

[[v3-11-4]]

^<<v3-11-4,4>>^ Mas não poderão comer camelos, coelhos selvagens ou lebres, pois esses animais ruminam, mas não têm casco dividido. Para vocês esses animais são impuros .

[[v3-11-5]]

^<<v3-11-5,5>>^ Mas não poderão comer camelos, coelhos selvagens ou lebres, pois esses animais ruminam, mas não têm casco dividido. Para vocês esses animais são impuros .

[[v3-11-6]]

^<<v3-11-6,6>>^ Mas não poderão comer camelos, coelhos selvagens ou lebres, pois esses animais ruminam, mas não têm casco dividido. Para vocês esses animais são impuros .

[[v3-11-7]]

^<<v3-11-7,7>>^ É proibido comer carne de porco. Para vocês o porco é impuro, pois tem o casco dividido, mas não rumina.

[[v3-11-8]]

^<<v3-11-8,8>>^ Não comam nenhum desses animais, nem mesmo toquem neles quando estiverem mortos. Todos eles são impuros.

[[v3-11-9]]

^<<v3-11-9,9>>^ Vocês poderão comer qualquer peixe que tem barbatanas e escamas,

[[v3-11-10]]

^<<v3-11-10,10>>^ mas não poderão comer os animais que vivem na água e que não têm barbatanas nem escamas. Esses animais são impuros para vocês;

[[v3-11-11]]

^<<v3-11-11,11>>^ não comam nenhum deles e, mesmo quando eles estiverem mortos, não toquem neles.

[[v3-11-12]]

^<<v3-11-12,12>>^ Qualquer animal que vive na água e que não tem barbatanas nem escamas é impuro.

[[v3-11-13]]

^<<v3-11-13,13>>^ Também são impuras as seguintes aves : águias, urubus, águias-marinhas,

[[v3-11-14]]

^<<v3-11-14,14>>^ açores, falcões,

[[v3-11-15]]

^<<v3-11-15,15>>^ corvos,

[[v3-11-16]]

^<<v3-11-16,16>>^ avestruzes, corujas, gaivotas, gaviões,

[[v3-11-17]]

^<<v3-11-17,17>>^ mochos, corvos-marinhos, íbis,

[[v3-11-18]]

^<<v3-11-18,18>>^ gralhas, pelicanos, abutres,

[[v3-11-19]]

^<<v3-11-19,19>>^ cegonhas, garças e poupas; e também morcegos.

[[v3-11-20]]

^<<v3-11-20,20>>^ É impuro todo inseto que anda e que voa;

[[v3-11-21]]

^<<v3-11-21,21>>^ mas vocês poderão comer os insetos que têm pernas e que saltam.

[[v3-11-22]]

^<<v3-11-22,22>>^ Poderão comer toda espécie de gafanhotos e grilos.

[[v3-11-23]]

^<<v3-11-23,23>>^ Mas todos os outros insetos que andam e que voam são impuros.

[[v3-11-24]]

^<<v3-11-24,24>>^ Ficará impuro até o pôr do sol quem tocar nos seguintes animais depois de mortos: todos os animais com cascos, mas que não têm o casco dividido e não ruminam, e todos os animais de quatro pés que andam sobre as plantas dos pés. Se alguém pegar o corpo de qualquer um deles, terá de lavar a roupa que estiver vestindo e ficará impuro até o pôr do sol. Esses animais são impuros para vocês.

[[v3-11-25]]

^<<v3-11-25,25>>^ Ficará impuro até o pôr do sol quem tocar nos seguintes animais depois de mortos: todos os animais com cascos, mas que não têm o casco dividido e não ruminam, e todos os animais de quatro pés que andam sobre as plantas dos pés. Se alguém pegar o corpo de qualquer um deles, terá de lavar a roupa que estiver vestindo e ficará impuro até o pôr do sol. Esses animais são impuros para vocês.

[[v3-11-26]]

^<<v3-11-26,26>>^ Ficará impuro até o pôr do sol quem tocar nos seguintes animais depois de mortos: todos os animais com cascos, mas que não têm o casco dividido e não ruminam, e todos os animais de quatro pés que andam sobre as plantas dos pés. Se alguém pegar o corpo de qualquer um deles, terá de lavar a roupa que estiver vestindo e ficará impuro até o pôr do sol. Esses animais são impuros para vocês.

[[v3-11-27]]

^<<v3-11-27,27>>^ Ficará impuro até o pôr do sol quem tocar nos seguintes animais depois de mortos: todos os animais com cascos, mas que não têm o casco dividido e não ruminam, e todos os animais de quatro pés que andam sobre as plantas dos pés. Se alguém pegar o corpo de qualquer um deles, terá de lavar a roupa que estiver vestindo e ficará impuro até o pôr do sol. Esses animais são impuros para vocês.

[[v3-11-28]]

^<<v3-11-28,28>>^ Ficará impuro até o pôr do sol quem tocar nos seguintes animais depois de mortos: todos os animais com cascos, mas que não têm o casco dividido e não ruminam, e todos os animais de quatro pés que andam sobre as plantas dos pés. Se alguém pegar o corpo de qualquer um deles, terá de lavar a roupa que estiver vestindo e ficará impuro até o pôr do sol. Esses animais são impuros para vocês.

[[v3-11-29]]

^<<v3-11-29,29>>^ Dos animais que se arrastam pelo chão são impuros os seguintes: todas as espécies de lagartos, lagartixas, ratos, toupeiras e camaleões.

[[v3-11-30]]

^<<v3-11-30,30>>^ Dos animais que se arrastam pelo chão são impuros os seguintes: todas as espécies de lagartos, lagartixas, ratos, toupeiras e camaleões.

[[v3-11-31]]

^<<v3-11-31,31>>^ Ficará impuro até o pôr do sol quem tocar nesses animais depois de mortos.

[[v3-11-32]]

^<<v3-11-32,32>>^ E, se o corpo de qualquer um desses animais cair em cima de alguma coisa, essa coisa ficará impura. Isso inclui qualquer objeto de madeira, tecido, couro ou saco, ou qualquer outra coisa. Para purificar  esse objeto, será preciso colocá-lo na água, mas ele ficará impuro até o pôr do sol.

[[v3-11-33]]

^<<v3-11-33,33>>^ E, se o corpo de um desses animais cair num pote de barro, tudo o que estiver dentro do pote se tornará impuro; será preciso quebrar o pote.

[[v3-11-34]]

^<<v3-11-34,34>>^ E, se a água daquele pote cair em cima de qualquer comida, essa comida ficará impura. E qualquer líquido que estiver no pote ficará impuro também.

[[v3-11-35]]

^<<v3-11-35,35>>^ Se o corpo de um desses animais cair sobre alguma coisa, ela ficará impura. Se for um forno ou um fogão de barro, então ele se tornará impuro e deverá ser quebrado;

[[v3-11-36]]

^<<v3-11-36,36>>^ se for uma fonte ou uma caixa de água, a água ali dentro continuará pura, mas quem tocar no corpo ficará impuro.

[[v3-11-37]]

^<<v3-11-37,37>>^ Se o corpo de um desses animais cair em cima de sementes que vão ser plantadas, elas continuarão puras ;

[[v3-11-38]]

^<<v3-11-38,38>>^ mas, se as sementes estiverem de molho na água, e o corpo cair na água, então elas se tornarão impuras.

[[v3-11-39]]

^<<v3-11-39,39>>^ Se um animal que se pode comer tiver morte natural, a pessoa que tocar no corpo ficará impura até o pôr do sol.

[[v3-11-40]]

^<<v3-11-40,40>>^ E, se alguém comer a carne desse animal, deverá lavar a roupa que estiver vestindo e ficará impuro até o pôr do sol; e, se alguém carregar o corpo do animal, precisará lavar a roupa e ficará impuro até o pôr do sol.

'''

xref:003-levitico/003-levitico-010.adoc#v3-10-0[&#60; Capítulo Anterior] | <<v3-11-0,Topo>> | xref:003-levitico/003-levitico-012.adoc#v3-12-0[Próximo Capítulo &#62;]