include::./index.adoc[]

[[v3-21-0]]
=== Levítico, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-21-1]]

^<<v3-21-1,1>>^ O Senhor  Deus mandou Moisés dizer o seguinte aos sacerdotes, que são descendentes de Arão: — Que nenhum sacerdote fique impuro  por tocar no corpo de um parente morto,

[[v3-21-2]]

^<<v3-21-2,2>>^ a não ser no caso de parentes chegados, isto é, a mãe, o pai, o filho, a filha, o irmão

[[v3-21-3]]

^<<v3-21-3,3>>^ ou a irmã solteira que more com ele.

[[v3-21-4]]

^<<v3-21-4,4>>^ Que ele não fique impuro por causa da morte de uma irmã casada.

[[v3-21-5]]

^<<v3-21-5,5>>^ — Os sacerdotes não podem rapar a cabeça, aparar a barba ou cortar-se em sinal de luto.

[[v3-21-6]]

^<<v3-21-6,6>>^ Eles serão completamente fiéis ao seu Deus e não deverão profanar  o nome de Deus. Eles apresentam os sacrifícios  que são ofertas de alimento para Deus, o Senhor ; portanto, devem ser fiéis a Deus.

[[v3-21-7]]

^<<v3-21-7,7>>^ Eles são separados para o serviço de Deus e por isso não podem casar com uma prostituta ou com uma mulher que não seja virgem ou com uma mulher divorciada.

[[v3-21-8]]

^<<v3-21-8,8>>^ O sacerdote apresenta a Deus as ofertas de alimento, e por isso o povo deve considerá-lo santo. Eu, o Senhor , sou santo e escolhi o povo de Israel para que seja santo .

[[v3-21-9]]

^<<v3-21-9,9>>^ — Se a filha de um sacerdote se desonrar, virando prostituta, ela estará envergonhando o pai e deverá ser queimada viva.

[[v3-21-10]]

^<<v3-21-10,10>>^ — O Grande Sacerdote  foi ordenado  como sacerdote quando o azeite sagrado foi derramado na sua cabeça e quando vestiu as roupas sacerdotais; por isso ele não deve deixar de pentear os cabelos e não deve rasgar as roupas em sinal de luto.

[[v3-21-11]]

^<<v3-21-11,11>>^ Ele não pode tocar num morto, mesmo que seja o seu pai ou a sua mãe. Isso o tornaria impuro,

[[v3-21-12]]

^<<v3-21-12,12>>^ e, quando entrasse de novo na Tenda Sagrada , ele a tornaria impura. Eu sou o Senhor .

[[v3-21-13]]

^<<v3-21-13,13>>^ O Grande Sacerdote só poderá casar com uma virgem;

[[v3-21-14]]

^<<v3-21-14,14>>^ ele não pode casar com uma viúva, ou uma mulher divorciada, ou uma prostituta, ou qualquer outra mulher que não seja virgem. Ele pode casar somente com uma virgem israelita

[[v3-21-15]]

^<<v3-21-15,15>>^ a fim de que os seus descendentes sejam puros . Eu sou o Senhor , e eu o ordenei como sacerdote.

[[v3-21-16]]

^<<v3-21-16,16>>^ O Senhor  Deus disse a Moisés o seguinte:

[[v3-21-17]]

^<<v3-21-17,17>>^ — Diga a Arão que nenhum descendente dele que tiver algum defeito físico poderá me apresentar as ofertas de alimento. Essa lei  valerá para sempre.

[[v3-21-18]]

^<<v3-21-18,18>>^ Nenhum homem com defeito físico poderá apresentar as ofertas: seja cego, aleijado, com defeito no rosto ou com o corpo deformado;

[[v3-21-19]]

^<<v3-21-19,19>>^ ninguém com uma perna ou braço quebrado;

[[v3-21-20]]

^<<v3-21-20,20>>^ ninguém que seja corcunda ou anão; ninguém que tenha doença nos olhos ou que tenha sarna ou outra doença da pele; e ninguém que seja castrado.

[[v3-21-21]]

^<<v3-21-21,21>>^ Nenhum descendente do sacerdote Arão que tiver algum defeito poderá me apresentar as ofertas de alimento; se ele for defeituoso, estará proibido de oferecer o meu alimento.

[[v3-21-22]]

^<<v3-21-22,22>>^ Esse homem poderá comer dessas ofertas, tanto as que são sagradas como as que são muito sagradas;

[[v3-21-23]]

^<<v3-21-23,23>>^ mas ele não poderá chegar perto da cortina do Lugar Santíssimo , nem chegar perto do altar, pois tem um defeito e tornaria impuras essas duas coisas. Eu sou o Senhor , e eu as dediquei a mim.

[[v3-21-24]]

^<<v3-21-24,24>>^ Foi isso o que Moisés disse a Arão, aos filhos de Arão e a todo o povo de Israel.

'''

xref:003-levitico/003-levitico-020.adoc#v3-20-0[&#60; Capítulo Anterior] | <<v3-21-0,Topo>> | xref:003-levitico/003-levitico-022.adoc#v3-22-0[Próximo Capítulo &#62;]