include::./index.adoc[]

[[v3-24-0]]
=== Levítico, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-24-1]]

^<<v3-24-1,1>>^ O Senhor  Deus disse a Moisés o seguinte:

[[v3-24-2]]

^<<v3-24-2,2>>^ — Diga aos israelitas que lhe tragam o melhor azeite, para manter sempre aceso o candelabro  que está na Tenda Sagrada .

[[v3-24-3]]

^<<v3-24-3,3>>^ Todas as tardes Arão acenderá o candelabro e o manterá aceso a noite toda, ali na presença de Deus, o Senhor , do lado de fora da cortina que fica em frente da arca da aliança . Essa lei  deverá ser obedecida por vocês e pelos seus descendentes para sempre.

[[v3-24-4]]

^<<v3-24-4,4>>^ Arão cuidará dos pavios das lamparinas do candelabro de ouro puro, para que fiquem sempre acesas na presença do Senhor .

[[v3-24-5]]

^<<v3-24-5,5>>^ Doze pães, cada um pesando dois quilos, deverão ser feitos da melhor farinha

[[v3-24-6]]

^<<v3-24-6,6>>^ e postos na mesa de ouro puro que fica na presença de Deus, o Senhor . Os pães deverão ser arrumados em duas pilhas, seis pães em cada pilha.

[[v3-24-7]]

^<<v3-24-7,7>>^ Em cima das duas pilhas será colocado incenso puro para lembrar que todos os pães são oferecidos ao Senhor  como oferta de alimento.

[[v3-24-8]]

^<<v3-24-8,8>>^ Todos os sábados, para sempre, o Grande Sacerdote  colocará os pães em ordem na mesa, na presença de Deus, o Senhor . Esses pães representam a aliança eterna dos israelitas com o Senhor

[[v3-24-9]]

^<<v3-24-9,9>>^ e pertencerão para sempre aos sacerdotes, que são descendentes de Arão. Os pães são muito sagrados, pois são uma oferta de alimento dada ao Senhor ; por isso os sacerdotes os comerão num lugar sagrado.

[[v3-24-10]]

^<<v3-24-10,10>>^ Havia entre os israelitas um homem que era filho de um egípcio casado com uma mulher israelita. Ela se chamava Selomite e era filha de Dibri, da tribo  de Dã. Certo dia no acampamento, numa briga com um israelita, esse homem blasfemou  contra o nome de Deus, o Senhor , e o amaldiçoou. Levaram o homem a Moisés

[[v3-24-11]]

^<<v3-24-11,11>>^ Havia entre os israelitas um homem que era filho de um egípcio casado com uma mulher israelita. Ela se chamava Selomite e era filha de Dibri, da tribo  de Dã. Certo dia no acampamento, numa briga com um israelita, esse homem blasfemou  contra o nome de Deus, o Senhor , e o amaldiçoou. Levaram o homem a Moisés

[[v3-24-12]]

^<<v3-24-12,12>>^ e o deixaram preso até que o Senhor  dissesse o que deviam fazer.

[[v3-24-13]]

^<<v3-24-13,13>>^ O Senhor  Deus disse a Moisés:

[[v3-24-14]]

^<<v3-24-14,14>>^ — Leve esse homem para fora do acampamento. As pessoas que o ouviram blasfemar contra mim colocarão as mãos na cabeça dele, e depois o povo todo o matará a pedradas.

[[v3-24-15]]

^<<v3-24-15,15>>^ E diga ao povo: "Quem amaldiçoar o seu Deus pagará por esse pecado

[[v3-24-16]]

^<<v3-24-16,16>>^ e será morto a pedradas por todo o povo. Não importa que seja israelita ou um estrangeiro que mora no meio de vocês; quem blasfemar contra o nome do Senhor  Deus será morto.

[[v3-24-17]]

^<<v3-24-17,17>>^ — "Aquele que matar uma pessoa será morto.

[[v3-24-18]]

^<<v3-24-18,18>>^ Quem matar um animal doméstico de outra pessoa dará ao dono outro animal do mesmo valor, um animal pelo outro.

[[v3-24-19]]

^<<v3-24-19,19>>^ Se alguém ferir outra pessoa, farão com ele a mesma coisa que ele fez:

[[v3-24-20]]

^<<v3-24-20,20>>^ quebradura por quebradura, olho por olho, dente por dente. Ele será ferido do mesmo jeito que feriu o outro.

[[v3-24-21]]

^<<v3-24-21,21>>^ Quem matar um animal doméstico de outra pessoa dará ao dono outro animal. Quem matar uma pessoa será morto.

[[v3-24-22]]

^<<v3-24-22,22>>^ A lei  é a mesma para os estrangeiros que moram no meio de vocês e para os israelitas. Eu sou o Senhor , o Deus de vocês."

'''

xref:003-levitico/003-levitico-023.adoc#v3-23-0[&#60; Capítulo Anterior] | <<v3-24-0,Topo>> | xref:003-levitico/003-levitico-025.adoc#v3-25-0[Próximo Capítulo &#62;]