include::./index.adoc[]

[[v3-25-0]]
=== Levítico, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-25-1]]

^<<v3-25-1,1>>^ O Senhor  Deus falou com Moisés no monte Sinai

[[v3-25-2]]

^<<v3-25-2,2>>^ e mandou que ele desse ao povo de Israel as seguintes leis : Quando vocês entrarem na terra que o Senhor  Deus lhes vai dar, deixem que de sete em sete anos a terra descanse, em honra do Senhor .

[[v3-25-3]]

^<<v3-25-3,3>>^ Durante seis anos semeiem os seus campos, podem as parreiras  e colham as uvas.

[[v3-25-4]]

^<<v3-25-4,4>>^ Mas o sétimo ano será um ano de descanso sagrado para a terra, um descanso dedicado a Deus, o Senhor . Nesse ano ninguém semeará o seu campo, nem podará as suas parreiras.

[[v3-25-5]]

^<<v3-25-5,5>>^ Ninguém colherá o trigo que crescer por si mesmo, nem podará as parreiras, nem colherá as uvas. Será um ano de descanso completo para a terra.

[[v3-25-6]]

^<<v3-25-6,6>>^ Os campos não serão semeados, mas mesmo assim produzirão o bastante para alimentar todos os israelitas, os seus escravos e as suas escravas, os seus empregados, os estrangeiros que vivem no meio do povo

[[v3-25-7]]

^<<v3-25-7,7>>^ e também os animais domésticos e os animais selvagens. Tudo o que a terra produzir servirá de alimento.

[[v3-25-8]]

^<<v3-25-8,8>>^ Contem sete semanas de anos, isto é, sete anos vezes sete, o que dá um total de quarenta e nove anos.

[[v3-25-9]]

^<<v3-25-9,9>>^ Então, no dia dez do sétimo mês, que é o Dia do Perdão , mandem um homem tocar trombeta por todo o país.

[[v3-25-10]]

^<<v3-25-10,10>>^ Pois esse ano, que vem depois de cada quarenta e nove anos, é o ano sagrado da libertação, em que vocês anunciarão liberdade a todos os moradores do país. Nesse ano todos os que tiverem sido vendidos como escravos voltarão livres para as suas famílias, e todos os campos que tiverem sido vendidos voltarão a pertencer ao primeiro dono.

[[v3-25-11]]

^<<v3-25-11,11>>^ Nesse ano ninguém semeará os seus campos, nem colherá o trigo que crescer por si mesmo, nem podará as parreiras , nem colherá as uvas,

[[v3-25-12]]

^<<v3-25-12,12>>^ pois o Ano da Libertação é sagrado para o povo, e nele todos se alimentarão somente daquilo que a terra produzir por si mesma.

[[v3-25-13]]

^<<v3-25-13,13>>^ No Ano da Libertação todas as terras que tiverem sido vendidas voltarão a pertencer ao primeiro dono.

[[v3-25-14]]

^<<v3-25-14,14>>^ Na venda ou na compra de terras, não explorem os outros.

[[v3-25-15]]

^<<v3-25-15,15>>^ O preço será calculado na base do Ano da Libertação; pois o que se vende não são, de fato, as terras, mas as colheitas que elas produzem. Portanto, o comprador descontará do preço o número de colheitas desde o último Ano da Libertação; e o vendedor calculará o preço na base dos anos de colheita que ainda faltam até o seguinte Ano da Libertação. Se ainda forem muitos anos, o preço subirá; se forem poucos, o preço baixará.

[[v3-25-16]]

^<<v3-25-16,16>>^ O preço será calculado na base do Ano da Libertação; pois o que se vende não são, de fato, as terras, mas as colheitas que elas produzem. Portanto, o comprador descontará do preço o número de colheitas desde o último Ano da Libertação; e o vendedor calculará o preço na base dos anos de colheita que ainda faltam até o seguinte Ano da Libertação. Se ainda forem muitos anos, o preço subirá; se forem poucos, o preço baixará.

[[v3-25-17]]

^<<v3-25-17,17>>^ Que ninguém explore os outros; que todos temam a Deus , pois ele é o Senhor , nosso Deus.

[[v3-25-18]]

^<<v3-25-18,18>>^ Obedeçam a todas as leis  e mandamentos de Deus para que vivam em segurança na terra que vai ser de vocês.

[[v3-25-19]]

^<<v3-25-19,19>>^ Ela produzirá as suas colheitas, haverá bastante comida para todos, e todos viverão em segurança.

[[v3-25-20]]

^<<v3-25-20,20>>^ Mas alguém é capaz de perguntar como é que haverá comida durante o sétimo ano, quando ninguém vai semear nem fazer a colheita.

[[v3-25-21]]

^<<v3-25-21,21>>^ A resposta é que Deus abençoará a terra, e no sexto ano ela produzirá colheitas que serão suficientes para três anos.

[[v3-25-22]]

^<<v3-25-22,22>>^ Quando vocês semearem os seus campos no oitavo ano, estarão comendo daquilo que colheram no sexto ano, e haverá bastante para comerem até a colheita do nono ano.

[[v3-25-23]]

^<<v3-25-23,23>>^ A terra é de Deus; portanto, ela não será para sempre daquele que a comprar. Deus é o dono dela, e para ele nós somos estrangeiros que moram por um pouco de tempo na terra dele.

[[v3-25-24]]

^<<v3-25-24,24>>^ Assim, quando um terreno for vendido, o seu antigo dono será o primeiro a ter o direito de tornar a comprá-lo.

[[v3-25-25]]

^<<v3-25-25,25>>^ Se um israelita ficar pobre e precisar vender uma parte das suas terras, o seu parente mais chegado deve tornar a comprar o que ele vendeu.

[[v3-25-26]]

^<<v3-25-26,26>>^ Mas, se ele não tiver um parente que compre as terras, é possível que mais tarde ele mesmo fique rico outra vez, podendo assim tornar a comprar o terreno que vendeu.

[[v3-25-27]]

^<<v3-25-27,27>>^ Ele descontará o valor das colheitas que o terreno tiver produzido desde o último Ano da Libertação e calculará o preço a pagar, tendo como base os anos de colheita que ainda faltarem até o seguinte Ano da Libertação. E assim ele será novamente o dono do terreno.

[[v3-25-28]]

^<<v3-25-28,28>>^ Mas, se ele não tiver o suficiente para tornar a comprar o terreno, então este ficará pertencendo ao comprador até o seguinte Ano da Libertação. Nesse ano o terreno voltará a pertencer ao primeiro dono.

[[v3-25-29]]

^<<v3-25-29,29>>^ Se um homem vender uma casa que fica numa cidade protegida por muralhas, ele terá o direito de tornar a comprar a casa até um ano depois da venda.

[[v3-25-30]]

^<<v3-25-30,30>>^ Mas, se dentro de um ano ele não comprá-la, então ela pertencerá ao comprador e aos seus descendentes para sempre. Nem mesmo no Ano da Libertação a casa voltará a ser do primeiro dono.

[[v3-25-31]]

^<<v3-25-31,31>>^ Porém as casas que ficam em cidades sem muralhas são como os terrenos; o primeiro dono tem o direito de tornar a comprar a casa, e no Ano da Libertação ela volta a ser do primeiro dono.

[[v3-25-32]]

^<<v3-25-32,32>>^ Os levitas  têm sempre o direito de tornar a comprar as suas casas que ficam nas cidades onde moram.

[[v3-25-33]]

^<<v3-25-33,33>>^ Mas, se um levita vender a sua casa numa dessas cidades e não tornar a comprá-la, então no Ano da Libertação a casa volta a ser dele; pois as casas das cidades onde os levitas moram serão sua propriedade permanente no meio do povo de Israel.

[[v3-25-34]]

^<<v3-25-34,34>>^ Mas os campos em volta das cidades onde os levitas moram não podem ser vendidos; eles pertencem aos levitas para sempre.

[[v3-25-35]]

^<<v3-25-35,35>>^ Se um israelita que mora perto de você ficar pobre e não puder sustentar-se, então você tem o dever de tomar conta dele. Ajude-o como se ele fosse um estrangeiro que mora no meio do povo, a fim de que ele continue a morar perto de você.

[[v3-25-36]]

^<<v3-25-36,36>>^ Não cobre juros sobre o dinheiro que você lhe emprestar. Respeite a ordem de Deus para que esse homem continue a morar perto de você.

[[v3-25-37]]

^<<v3-25-37,37>>^ Não cobre juros sobre o que você lhe emprestar, nem tire lucro dos alimentos que você lhe vender.

[[v3-25-38]]

^<<v3-25-38,38>>^ É isso o que o Senhor , nosso Deus, nos manda fazer. Foi ele quem nos tirou do Egito para nos dar a terra de Canaã e para ser o nosso Deus.

[[v3-25-39]]

^<<v3-25-39,39>>^ Se um israelita que mora perto de você ficar tão pobre, que chegue a ponto de ter de se vender a você para ser seu escravo, não o faça trabalhar como escravo.

[[v3-25-40]]

^<<v3-25-40,40>>^ Trate-o como se ele fosse um empregado ou um estrangeiro que mora com você. Ele trabalhará para você até o Ano da Libertação,

[[v3-25-41]]

^<<v3-25-41,41>>^ e nesse ano ele e os seus filhos irão embora e voltarão para a sua própria família e para as terras dos seus antepassados.

[[v3-25-42]]

^<<v3-25-42,42>>^ Os israelitas são escravos do Senhor  Deus, que os tirou do Egito; eles não deverão ser vendidos como escravos.

[[v3-25-43]]

^<<v3-25-43,43>>^ Portanto, não os trate com crueldade, mas respeite a ordem de Deus.

[[v3-25-44]]

^<<v3-25-44,44>>^ Se precisarem de escravos ou escravas, vocês poderão comprá-los dos povos vizinhos do seu país.

[[v3-25-45]]

^<<v3-25-45,45>>^ Também poderão comprar os filhos dos estrangeiros que moram no meio de vocês. Essas crianças que nascerem na terra de Israel poderão ser compradas como escravos,

[[v3-25-46]]

^<<v3-25-46,46>>^ e os seus donos poderão deixá-los como herança aos filhos, a quem esses escravos deverão servir a vida inteira. Mas um israelita não pode ter outro israelita como escravo, nem pode tratá-lo com crueldade.

[[v3-25-47]]

^<<v3-25-47,47>>^ Pode acontecer que um estrangeiro que vive no meio do povo fique rico e que um vizinho israelita fique pobre e se venda como escravo a esse estrangeiro ou a alguém da família dele.

[[v3-25-48]]

^<<v3-25-48,48>>^ Nesse caso, depois de vendido, o israelita tem o direito de ser comprado de novo. Um irmão,

[[v3-25-49]]

^<<v3-25-49,49>>^ um tio, um primo ou outro parente chegado poderá comprá-lo. Ou, se ganhar bastante dinheiro, ele mesmo poderá comprar a sua liberdade.

[[v3-25-50]]

^<<v3-25-50,50>>^ Ele e o homem que o comprou combinarão o preço que deverá ser pago, de acordo com o número de anos desde o ano em que ele se vendeu até o seguinte Ano da Libertação. O cálculo será feito tendo como base o salário que um empregado recebe.

[[v3-25-51]]

^<<v3-25-51,51>>^ Se ainda faltarem muitos anos até o Ano da Libertação, ele pagará uma parte maior do dinheiro que recebeu quando se vendeu;

[[v3-25-52]]

^<<v3-25-52,52>>^ mas, se faltarem poucos anos, a parte será menor.

[[v3-25-53]]

^<<v3-25-53,53>>^ O dono o tratará como se ele fosse um empregado que é contratado para trabalhar por ano. Não deixem que o dono o trate com crueldade.

[[v3-25-54]]

^<<v3-25-54,54>>^ E, se o homem não for libertado por nenhum desses modos, então no seguinte Ano da Libertação ele e os seus filhos ficarão livres.

'''

xref:003-levitico/003-levitico-024.adoc#v3-24-0[&#60; Capítulo Anterior] | <<v3-25-0,Topo>> | xref:003-levitico/003-levitico-026.adoc#v3-26-0[Próximo Capítulo &#62;]