include::./index.adoc[]

[[v3-3-0]]
=== Levítico, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v3-3-1]]

^<<v3-3-1,1>>^ Quando um homem apresentar a Deus, o Senhor , uma oferta de paz, se o animal for tirado do gado, poderá ser um touro ou uma vaca, mas precisará ser sem defeito.

[[v3-3-2]]

^<<v3-3-2,2>>^ Em frente da Tenda Sagrada  o homem porá a mão na cabeça do animal e o matará. Os sacerdotes, que são descendentes de Arão, borrifarão os quatro lados do altar com o sangue.

[[v3-3-3]]

^<<v3-3-3,3>>^ E um dos sacerdotes apresentará ao Senhor  como uma oferta de alimento toda a gordura que cobre os miúdos,

[[v3-3-4]]

^<<v3-3-4,4>>^ os dois rins com a gordura que os cobre e também a melhor parte do fígado, que ele tirará junto com os rins.

[[v3-3-5]]

^<<v3-3-5,5>>^ Os sacerdotes queimarão tudo isso no altar, junto com a oferta queimada que foi posta em cima da lenha que está no altar. É uma oferta de alimento que tem um cheiro agradável a Deus, o Senhor .

[[v3-3-6]]

^<<v3-3-6,6>>^ Se o homem oferecer a Deus, o Senhor , um animal do seu rebanho como oferta de paz, o animal poderá ser macho ou fêmea, mas precisará ser sem defeito.

[[v3-3-7]]

^<<v3-3-7,7>>^ Se a oferta ao Senhor  for um carneirinho,

[[v3-3-8]]

^<<v3-3-8,8>>^ o homem porá a mão na cabeça do animal e o matará em frente da Tenda Sagrada. Os sacerdotes, que são descendentes de Arão, borrifarão os quatro lados do altar com o sangue.

[[v3-3-9]]

^<<v3-3-9,9>>^ Um dos sacerdotes apresentará ao Senhor  como uma oferta de alimento a gordura do animal, o rabo inteiro, que será cortado bem perto da espinha, a gordura que cobre os miúdos,

[[v3-3-10]]

^<<v3-3-10,10>>^ os dois rins e a gordura que os cobre e também a melhor parte do fígado, que ele tirará junto com os rins.

[[v3-3-11]]

^<<v3-3-11,11>>^ E o sacerdote queimará tudo isso no altar como uma oferta de alimento a Deus, o Senhor .

[[v3-3-12]]

^<<v3-3-12,12>>^ Se a oferta ao Senhor  for um cabrito,

[[v3-3-13]]

^<<v3-3-13,13>>^ o homem porá a mão na cabeça do animal e o matará em frente da Tenda Sagrada. Os sacerdotes, que são descendentes de Arão, borrifarão os quatro lados do altar com o sangue.

[[v3-3-14]]

^<<v3-3-14,14>>^ Um dos sacerdotes apresentará ao Senhor  como uma oferta de alimento a gordura que cobre os miúdos do animal,

[[v3-3-15]]

^<<v3-3-15,15>>^ e os dois rins, e a gordura que os cobre, e também a melhor parte do fígado, que ele tirará junto com os rins.

[[v3-3-16]]

^<<v3-3-16,16>>^ E o sacerdote queimará tudo isso no altar como uma oferta de alimento que tem um cheiro agradável. Toda a gordura pertence a Deus, o Senhor .

[[v3-3-17]]

^<<v3-3-17,17>>^ Por isso os israelitas, em todos os lugares onde morarem, não comerão nem a gordura nem o sangue. Essa é uma lei  que deverá ser obedecida para sempre por vocês e pelos seus descendentes.

'''

xref:003-levitico/003-levitico-002.adoc#v3-2-0[&#60; Capítulo Anterior] | <<v3-3-0,Topo>> | xref:003-levitico/003-levitico-004.adoc#v3-4-0[Próximo Capítulo &#62;]