include::./index.adoc[]

[[v28-4-0]]
=== Oséias, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-4-1]]

^<<v28-4-1,1>>^ O Senhor  Deus tem uma acusação a fazer contra o povo que vive neste país. Escutem, israelitas, o que Deus está dizendo: — Não há sinceridade, não há bondade, e ninguém neste país quer saber de Deus.

[[v28-4-2]]

^<<v28-4-2,2>>^ Juram falso, mentem, matam, roubam e cometem adultério. Os crimes e os assassinatos aumentam.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por isso, a terra ficará seca, e tudo o que vive nela morrerá. Morrerão os animais, as aves e até os peixes.

[[v28-4-4]]

^<<v28-4-4,4>>^ O Senhor  Deus diz: — Não acusem nem repreendam o meu povo. A minha acusação é contra vocês, sacerdotes.

[[v28-4-5]]

^<<v28-4-5,5>>^ Dia e noite, vocês andam sem rumo, e os profetas  fazem o mesmo. Vou acabar com Israel, a mãe de vocês.

[[v28-4-6]]

^<<v28-4-6,6>>^ O meu povo não quer saber de mim e por isso está sendo destruído. E vocês, sacerdotes, também não querem saber de mim e esqueceram as minhas leis ; portanto, eu não os aceito mais como meus sacerdotes, nem aceitarei os seus filhos como meus sacerdotes.

[[v28-4-7]]

^<<v28-4-7,7>>^ — Quanto maior é o número de sacerdotes, maior também é o número de pecados que cometem; por isso vou fazer a glória  deles virar desgraça.

[[v28-4-8]]

^<<v28-4-8,8>>^ Eles ganham a vida à custa dos pecados do povo e por causa disso querem que o povo peque.

[[v28-4-9]]

^<<v28-4-9,9>>^ Portanto, os sacerdotes sofrerão o mesmo castigo que vou fazer cair sobre o meu povo. Vou castigá-los, e eles terão de pagar pelo mal que fizeram.

[[v28-4-10]]

^<<v28-4-10,10>>^ Os sacerdotes estão me abandonando e adorando outros deuses. Por isso comerão dos sacrifícios que o povo me oferece, mas não ficarão satisfeitos; adorarão os deuses da fertilidade, mas não terão filhos.

[[v28-4-11]]

^<<v28-4-11,11>>^ Deus diz: — O meu povo está perdendo o juízo porque anda bebendo muito vinho.

[[v28-4-12]]

^<<v28-4-12,12>>^ Pedem a um pedaço de pau que revele o futuro e fazem perguntas a uma coluna de madeira. Eles me abandonaram. Como uma mulher que se torna prostituta, eles me abandonaram e se entregaram a deuses pagãos.

[[v28-4-13]]

^<<v28-4-13,13>>^ Oferecem sacrifícios  nos altares pagãos no alto dos montes e ali queimam incenso debaixo dos carvalhos e de outras árvores cheias de folhas, onde a sombra é tão gostosa. — E assim as suas filhas viram prostitutas, e as suas noras cometem adultério.

[[v28-4-14]]

^<<v28-4-14,14>>^ Mas nem por isso eu as castigarei; pois vocês, homens, têm encontros com prostitutas nos templos pagãos e vão com elas oferecer sacrifícios aos deuses pagãos. E assim um povo sem juízo caminha rápido para a destruição!

[[v28-4-15]]

^<<v28-4-15,15>>^ — O povo de Israel está sendo infiel a mim, mas espero que o povo de Judá não seja culpado do mesmo pecado. Não adorem em Gilgal ou em Bete-Avém , nem façam ali promessas em nome do Senhor  Deus, que vive para sempre.

[[v28-4-16]]

^<<v28-4-16,16>>^ O povo de Israel é teimoso como uma vaca brava. Não posso cuidar do meu povo como um pastor cuida das ovelhas num pasto grande.

[[v28-4-17]]

^<<v28-4-17,17>>^ O meu povo se entrega à adoração de ídolos, e não se pode fazer nada quanto a isso.

[[v28-4-18]]

^<<v28-4-18,18>>^ Eles ficam embriagados e se entregam à imoralidade, levando assim uma vida de desonra.

[[v28-4-19]]

^<<v28-4-19,19>>^ Um vento os carregará para longe, e ficarão com vergonha da sua idolatria.

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]