include::./index.adoc[]

[[v28-2-0]]
=== Oséias, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-2-1]]

^<<v28-2-1,1>>^ Portanto, ponham nos seus irmãos, os israelitas, os nomes de Povo-de-Deus e Amados-por-Deus.

[[v28-2-2]]

^<<v28-2-2,2>>^ O Senhor  Deus disse ao povo: — Acusem a sua mãe, façam denúncia contra ela, pois ela não é mais a minha esposa, e eu não sou mais o seu marido. Peçam que ela pare de cometer adultério e que mande embora os seus amantes.

[[v28-2-3]]

^<<v28-2-3,3>>^ Se ela não fizer isso, eu tirarei toda a sua roupa e a deixarei nua como no dia em que nasceu. Eu farei com que ela fique como um deserto, como uma terra seca, e ela morrerá de sede.

[[v28-2-4]]

^<<v28-2-4,4>>^ E não terei pena dos seus filhos, pois são filhos de uma prostituta.

[[v28-2-5]]

^<<v28-2-5,5>>^ Ela se entregou à prostituição e mostrou que havia perdido toda a vergonha quando disse: "Vou buscar os meus amantes , pois eles me darão comida e bebida, roupas de lã e de linho, azeite e vinho."

[[v28-2-6]]

^<<v28-2-6,6>>^ — Portanto, vou pôr ao redor dela uma cerca de espinhos e vou construir um muro na estrada, para que ela não encontre o caminho.

[[v28-2-7]]

^<<v28-2-7,7>>^ Ela correrá atrás dos seus amantes, mas não os alcançará; irá procurá-los, mas não os encontrará. Então dirá: "Vou voltar para o meu marido, pois, quando vivia com ele, eu era mais feliz do que agora."

[[v28-2-8]]

^<<v28-2-8,8>>^ Ela não compreendeu que fui eu que lhe dei o trigo, o vinho e o azeite; fui eu que lhe dei muitos presentes de prata e de ouro, que ela ofereceu ao deus Baal .

[[v28-2-9]]

^<<v28-2-9,9>>^ Portanto, quando chegar o tempo da colheita, eu tomarei dessa mulher o meu trigo e o meu vinho e levarei embora as roupas de lã e de linho que tinha dado para ela vestir.

[[v28-2-10]]

^<<v28-2-10,10>>^ Agora vou deixá-la completamente nua na frente dos seus amantes, e ninguém a livrará do meu poder.

[[v28-2-11]]

^<<v28-2-11,11>>^ Acabarei com toda a sua alegria: não haverá mais festas anuais ou festas mensais, nem as festas dos sábados, nem qualquer outra festa.

[[v28-2-12]]

^<<v28-2-12,12>>^ Eu destruirei as suas plantações de uvas e as suas figueiras que ela disse que recebeu como pagamento dos seus amantes. Só ficará mato, e os animais selvagens devorarão tudo.

[[v28-2-13]]

^<<v28-2-13,13>>^ Ela me abandonou, adorou as imagens do deus Baal e queimou incenso como oferta a ele. Ela também se enfeitou com anéis e joias e correu atrás dos seus amantes. Por causa de tudo isso, eu a castigarei. Eu, o Senhor , estou falando.

[[v28-2-14]]

^<<v28-2-14,14>>^ Deus disse ao povo de Israel: — Vou seduzir a minha amada e levá-la de novo para o deserto, onde lhe falarei do meu amor.

[[v28-2-15]]

^<<v28-2-15,15>>^ Ali, eu devolverei a ela as suas plantações de uvas e transformarei o vale da Desgraça em uma porta de esperança. Então ela falará comigo como fazia no tempo em que era moça, quando saiu do Egito.

[[v28-2-16]]

^<<v28-2-16,16>>^ Mais uma vez ela me chamará de "Meu marido" em vez de me chamar de "Meu Baal  ".

[[v28-2-17]]

^<<v28-2-17,17>>^ Nunca mais deixarei que ela diga o nome Baal ; nunca mais se falará desse deus. Sou eu, o Senhor , quem está falando.

[[v28-2-18]]

^<<v28-2-18,18>>^ — Naquele dia, farei um acordo com os animais selvagens, com as aves e com as cobras, para que não ataquem a minha amada. Quebrarei as armas de guerra, os arcos e as espadas; não haverá mais guerra, e o meu povo viverá em paz e segurança.

[[v28-2-19]]

^<<v28-2-19,19>>^ — Israel, eu casarei com você, e para sempre você será minha legítima esposa. Eu a tratarei com amor e carinho

[[v28-2-20]]

^<<v28-2-20,20>>^ e serei um marido fiel. Então você se dedicará a mim, o Senhor .

[[v28-2-21]]

^<<v28-2-21,21>>^ Naquele tempo, serei o Deus que atende: atenderei o pedido dos céus; os céus atenderão o pedido da terra, dando-lhe chuvas;

[[v28-2-22]]

^<<v28-2-22,22>>^ e a terra responderá produzindo trigo, uvas e azeitonas. Assim eu atenderei as orações do meu povo de Israel .

[[v28-2-23]]

^<<v28-2-23,23>>^ Plantarei o meu povo na Terra Prometida  para que eles sejam a minha própria plantação. E eu amarei aquela que se chama Não-Amada; para aquele que se chama Não-Meu-Povo eu direi: "Você é o meu povo", e ele responderá: "Tu és o meu Deus".

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]