include::./index.adoc[]

[[v28-12-0]]
=== Oséias, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-12-1]]

^<<v28-12-1,1>>^ O povo de Israel vive praticando maldades e gasta o dia inteiro fazendo coisas que não têm valor. As mentiras e os crimes continuam a aumentar. Israel faz acordos  com a Assíria e manda azeite de presente para o Egito.

[[v28-12-2]]

^<<v28-12-2,2>>^ O Senhor  Deus tem uma acusação contra o povo de Judá e vai castigar o povo de Israel por causa dos seus pecados.

[[v28-12-3]]

^<<v28-12-3,3>>^ Jacó, o antepassado deles, lutou com o seu irmão gêmeo Esaú enquanto os dois ainda estavam na barriga da mãe. Já homem feito, Jacó lutou com Deus;

[[v28-12-4]]

^<<v28-12-4,4>>^ ele lutou com um anjo e venceu. Então chorou e pediu que o anjo o abençoasse. Deus o encontrou em Betel e ali falou com ele.

[[v28-12-5]]

^<<v28-12-5,5>>^ Esse foi o Senhor , o Deus Todo-Poderoso. O seu nome é Senhor !

[[v28-12-6]]

^<<v28-12-6,6>>^ Portanto, povo de Israel, volte de novo ao seu Deus, faça o que é bom e certo e confie sempre nele.

[[v28-12-7]]

^<<v28-12-7,7>>^ O Senhor  Deus diz: — Os israelitas são como os cananeus: são desonestos e usam balanças falsas para explorar os outros.

[[v28-12-8]]

^<<v28-12-8,8>>^ Eles dizem: "É verdade que somos ricos, mas ninguém pode nos acusar de termos ajuntado a nossa riqueza por meios desonestos."

[[v28-12-9]]

^<<v28-12-9,9>>^ Porém eu, o Senhor , sou o Deus de vocês desde que os tirei do Egito; eu farei com que vocês voltem a morar em barracas, como moravam quando me encontrei com vocês no deserto.

[[v28-12-10]]

^<<v28-12-10,10>>^ — Eu falei com os profetas  e lhes dei muitas visões; usei comparações quando falei ao povo por meio dos profetas.

[[v28-12-11]]

^<<v28-12-11,11>>^ Mas o povo de Gileade adora ídolos e por isso vai ser morto. Em Gilgal touros são sacrificados no altar; por isso, os altares vão virar montes de pedras nos campos arados.

[[v28-12-12]]

^<<v28-12-12,12>>^ O nosso antepassado Jacó teve de fugir para a Mesopotâmia e trabalhou como pastor de ovelhas a fim de conseguir uma esposa.

[[v28-12-13]]

^<<v28-12-13,13>>^ Por meio do profeta Moisés, o Senhor  Deus tirou o povo de Israel do Egito e cuidou deles.

[[v28-12-14]]

^<<v28-12-14,14>>^ Com os seus pecados, o povo de Israel provocou a ira  do Senhor ; por isso, ele fará com que paguem pelos crimes que cometeram e os castigará por causa das suas maldades.

'''

xref:028-oseias/028-oseias-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-oseias/028-oseias-013.adoc#v28-13-0[Próximo Capítulo &#62;]