include::./index.adoc[]

[[v28-6-0]]
=== Oséias, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-6-1]]

^<<v28-6-1,1>>^ O povo de Israel diz: — Venham, voltemos todos para Deus, o Senhor . Ele nos feriu, mas com certeza vai nos curar; ele nos castigou, mas certamente nos perdoará.

[[v28-6-2]]

^<<v28-6-2,2>>^ Daqui a uns dois ou três dias, no máximo, ele nos dará novas forças e nos porá de pé, e nós sempre faremos a sua vontade.

[[v28-6-3]]

^<<v28-6-3,3>>^ Vamos nos dedicar mais e mais ao Senhor ! Tão certo como nasce o sol, ele virá nos ajudar; virá tão certamente como vêm as chuvas da primavera, que regam a terra.

[[v28-6-4]]

^<<v28-6-4,4>>^ Mas o Senhor  Deus responde: — O que é que vou fazer com você, Israel? E com você, Judá, o que é que eu faço? Pois o amor de vocês é tão passageiro como a cerração ao nascer do sol; é como o orvalho, que seca logo de manhã.

[[v28-6-5]]

^<<v28-6-5,5>>^ Foi por isso que mandei os meus profetas  anunciar que eu vou castigar e matar vocês. E o que exijo de vocês é claro como a luz do sol.

[[v28-6-6]]

^<<v28-6-6,6>>^ Eu quero que vocês me amem e não que me ofereçam sacrifícios ; em vez de me trazer ofertas queimadas, eu prefiro que o meu povo me obedeça.

[[v28-6-7]]

^<<v28-6-7,7>>^ — Mas na cidade de Adã o meu povo quebrou a aliança  que fiz com ele e ali foi infiel a mim.

[[v28-6-8]]

^<<v28-6-8,8>>^ Gileade é uma cidade cheia de malfeitores e assassinos.

[[v28-6-9]]

^<<v28-6-9,9>>^ Os sacerdotes são como assaltantes que esperam escondidos para roubar os outros. Na estrada que vai para Siquém eles matam e cometem crimes horrorosos.

[[v28-6-10]]

^<<v28-6-10,10>>^ Tenho visto uma coisa horrível na terra de Israel: o meu povo adora ídolos e por isso está impuro .

[[v28-6-11]]

^<<v28-6-11,11>>^ — E já marquei o dia em que vou castigar também o povo de Judá.

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]