include::./index.adoc[]

[[v28-14-0]]
=== Oséias, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-14-1]]

^<<v28-14-1,1>>^ Povo de Israel, volte para o Senhor , seu Deus! Você caiu porque pecou.

[[v28-14-2]]

^<<v28-14-2,2>>^ Voltem para Deus e orem assim: "Perdoa todos os nossos pecados, ouve a nossa oração, e os nossos louvores serão o sacrifício  que te ofereceremos.

[[v28-14-3]]

^<<v28-14-3,3>>^ A Assíria não pode nos salvar, e a cavalaria não pode nos proteger. Nunca mais diremos aos ídolos, feitos por nós mesmos, que eles são o nosso Deus. Tu, ó Deus, és misericordioso e cuidas dos necessitados."

[[v28-14-4]]

^<<v28-14-4,4>>^ O Senhor  Deus diz: "Vou curar o meu povo da sua infidelidade e vou amá-los com todo o meu coração, pois não estou mais irado  com eles.

[[v28-14-5]]

^<<v28-14-5,5>>^ Serei como a chuva para Israel, e ele dará flores, como os lírios. As suas raízes serão profundas como as das árvores do Líbano.

[[v28-14-6]]

^<<v28-14-6,6>>^ Os seus galhos se estenderão, bonitos como os galhos das oliveiras e perfumosos como os cedros do Líbano.

[[v28-14-7]]

^<<v28-14-7,7>>^ Mais uma vez, Israel viverá debaixo da minha proteção; eles crescerão como o trigo, darão frutas como a parreira e serão famosos como o vinho do Líbano.

[[v28-14-8]]

^<<v28-14-8,8>>^ O povo de Israel dirá: ‘Os ídolos não valem nada!’ Sou eu, o Senhor  Deus, que atendo as orações do meu povo; sou eu que tomo conta deles. Como um pinheiro verde, eu lhes dou abrigo, e de mim eles recebem todas as bênçãos."

[[v28-14-9]]

^<<v28-14-9,9>>^ Que as pessoas sábias e ajuizadas entendam a mensagem deste livro e meditem nela! Os caminhos de Deus, o Senhor , são certos; os bons andarão neles, mas os pecadores tropeçarão e cairão.

'''

xref:028-oseias/028-oseias-013.adoc#v28-13-0[&#60; Capítulo Anterior] | <<v28-14-0,Topo>> | xref:029-joel/029-joel-001.adoc#v29-1-0[Próximo Capítulo &#62;]