include::./index.adoc[]

[[v28-5-0]]
=== Oséias, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-5-1]]

^<<v28-5-1,1>>^ — Prestem atenção, sacerdotes! Escutem, israelitas! Ouçam, gente da família do rei! Vocês serão condenados, pois em Mispa foram como uma armadilha, no monte Tabor foram como um laço

[[v28-5-2]]

^<<v28-5-2,2>>^ e no vale das Acácias foram como um poço profundo. Por isso, eu vou castigá-los.

[[v28-5-3]]

^<<v28-5-3,3>>^ Eu sei muito bem o que os israelitas fizeram: eles adoraram deuses pagãos e por isso estão impuros .

[[v28-5-4]]

^<<v28-5-4,4>>^ As más ações do povo de Israel não deixam que eles voltem para o seu Deus. Eles têm tanta vontade de adorar ídolos, que não querem mais saber de Deus, o Senhor .

[[v28-5-5]]

^<<v28-5-5,5>>^ O seu orgulho é prova de que são culpados. Por causa dos seus pecados, eles tropeçam e caem, e o povo de Judá cai com eles.

[[v28-5-6]]

^<<v28-5-6,6>>^ Levam as suas ovelhas e os seus bezerros para oferecê-los em sacrifício  ao Senhor , mas isso não adianta nada. Eles não podem achá-lo, pois ele se afastou deles.

[[v28-5-7]]

^<<v28-5-7,7>>^ Foram infiéis ao Senhor , e os seus filhos são ilegítimos . Portanto, daqui a pouco eles e as suas terras serão destruídos.

[[v28-5-8]]

^<<v28-5-8,8>>^ Toquem as cornetas em Gibeá e em Ramá! Deem o grito de alarme em Bete-Avém ! Estejam alertas, homens da tribo  de Benjamim!

[[v28-5-9]]

^<<v28-5-9,9>>^ Eu já anunciei ao povo de Israel aquilo que certamente vai acontecer: vem aí o dia do castigo, e Israel será destruído.

[[v28-5-10]]

^<<v28-5-10,10>>^ O Senhor  Deus diz: — Os chefes de Judá invadiram Israel e tomaram as suas terras. Por isso, estou irado  e vou castigá-los duramente.

[[v28-5-11]]

^<<v28-5-11,11>>^ O povo de Israel está sendo explorado, e os seus direitos não estão sendo respeitados porque eles insistiram em seguir deuses falsos.

[[v28-5-12]]

^<<v28-5-12,12>>^ Portanto, como a traça eu destruirei Israel e como o câncer acabarei com Judá.

[[v28-5-13]]

^<<v28-5-13,13>>^ — Quando Israel percebeu que estava doente, e Judá notou que também estava ferido, Israel foi procurar a ajuda do poderoso rei da Assíria; mas ele não os pôde curar nem fazer sarar os seus ferimentos.

[[v28-5-14]]

^<<v28-5-14,14>>^ Como um leão, eu atacarei os povos de Israel e de Judá. Eu os farei em pedaços e depois irei embora levando-os comigo. E ninguém os poderá salvar.

[[v28-5-15]]

^<<v28-5-15,15>>^ — Então voltarei para o meu lugar e ali ficarei até que eles reconheçam o seu pecado e, na sua aflição, venham me procurar.

'''

xref:028-oseias/028-oseias-004.adoc#v28-4-0[&#60; Capítulo Anterior] | <<v28-5-0,Topo>> | xref:028-oseias/028-oseias-006.adoc#v28-6-0[Próximo Capítulo &#62;]