include::./index.adoc[]

[[v28-9-0]]
=== Oséias, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-9-1]]

^<<v28-9-1,1>>^ Povo de Israel, deixe de se alegrar, pare de fazer festas como os outros povos fazem. Vocês abandonaram a Deus e adoraram ídolos. Em todos os terreiros onde o trigo é malhado, vocês se venderam como prostitutas ao deus Baal  e gostaram do pagamento que receberam dele.

[[v28-9-2]]

^<<v28-9-2,2>>^ Mas daqui a pouco não haverá trigo nem azeite, e faltará vinho.

[[v28-9-3]]

^<<v28-9-3,3>>^ O povo de Israel não ficará na terra de Deus, o Senhor , mas precisará voltar para o Egito e na Assíria comerá alimentos impuros  .

[[v28-9-4]]

^<<v28-9-4,4>>^ Naqueles países, eles não poderão fazer ofertas de vinho ao Senhor , nem oferecer os sacrifícios  de que ele gosta. A comida que comerem será como a que é servida num velório , e todos os que a comerem ficarão impuros. Não poderão apresentar ofertas de alimento no Templo do Senhor ; só poderão comê-las.

[[v28-9-5]]

^<<v28-9-5,5>>^ E o que é que eles vão fazer quando chegarem os dias das festas realizadas em honra do Senhor ?

[[v28-9-6]]

^<<v28-9-6,6>>^ Vão fugir para não serem destruídos, mas os egípcios os pegarão e os sepultarão na cidade de Mênfis. Os seus preciosos objetos de prata serão cobertos de espinheiros, e o mato tomará conta das suas casas.

[[v28-9-7]]

^<<v28-9-7,7>>^ Está chegando o dia do castigo, o dia em que Deus castigará o seu povo. E que o povo de Israel fique sabendo disso! Mas vocês dizem: "Esse profeta  está maluco! Diz que é inspirado, mas é louco!" Vocês falam assim porque estão cheios de maldade e de ódio.

[[v28-9-8]]

^<<v28-9-8,8>>^ Deus me mandou como profeta para avisar o seu povo, mas em todos os lugares eles armam armadilhas para me pegar. Até no Templo de Deus eles me perseguem!

[[v28-9-9]]

^<<v28-9-9,9>>^ Eles se afundaram tanto no pecado quanto o povo que estava em Gibeá . Deus lembrará dos pecados deles e os castigará.

[[v28-9-10]]

^<<v28-9-10,10>>^ O Senhor  Deus diz: — Quando encontrei Israel pela primeira vez, fiquei alegre como quem acha uvas no deserto e, ao ver os antepassados de vocês, fiquei contente como quem vê os primeiros figos maduros. Mas, quando eles chegaram ao monte Peor, ali começaram a adorar o deus Baal  e se tornaram tão nojentos como os ídolos que eles amaram.

[[v28-9-11]]

^<<v28-9-11,11>>^ A grandeza de Israel irá embora, voando como uma ave. Não nascerão mais crianças: as mulheres não ficarão grávidas e não darão à luz.

[[v28-9-12]]

^<<v28-9-12,12>>^ Ainda que criem filhos, eu os levarei embora; não deixarei nem um só. Ai desse povo quando eu me afastar dele!

[[v28-9-13]]

^<<v28-9-13,13>>^ Eu via Israel como se fosse a cidade de Tiro, plantada num lugar agradável; mas Israel levará os seus filhos para serem mortos.

[[v28-9-14]]

^<<v28-9-14,14>>^ Ó Senhor  Deus, o que é que vais fazer com este povo? Faze com que as mulheres não possam ter filhos! E, se tiverem, seca o seu leite, para que não possam dar de mamar!

[[v28-9-15]]

^<<v28-9-15,15>>^ O Senhor  Deus diz: — Toda a maldade do povo de Israel começou na cidade de Gilgal, e foi ali que comecei a odiá-los. E, por causa dos seus pecados, eu os expulsarei da minha terra. Daqui em diante, não os amarei mais. Todos os seus chefes se revoltaram contra mim.

[[v28-9-16]]

^<<v28-9-16,16>>^ Israel está ferido; é como uma árvore que não dá frutas porque as suas raízes secaram. Mesmo que nasçam crianças, eu matarei esses filhos tão queridos.

[[v28-9-17]]

^<<v28-9-17,17>>^ O meu Deus rejeitará o seu povo porque eles não lhe obedecem. E eles andarão sem rumo entre as outras nações.

'''

xref:028-oseias/028-oseias-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-oseias/028-oseias-010.adoc#v28-10-0[Próximo Capítulo &#62;]