include::./index.adoc[]

[[v28-11-0]]
=== Oséias, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-11-1]]

^<<v28-11-1,1>>^ A respeito do povo de Israel, o Senhor  Deus diz: "Quando Israel era criança, eu já o amava e chamei o meu filho, que estava na terra do Egito.

[[v28-11-2]]

^<<v28-11-2,2>>^ Porém, quanto mais eu o chamava, mais ele se afastava de mim. O meu povo ofereceu sacrifícios  ao deus Baal e queimou incenso em honra dos ídolos.

[[v28-11-3]]

^<<v28-11-3,3>>^ Mas fui eu que ensinei o meu povo a andar; eu os segurei nos meus braços, porém eles não sabiam que era eu que cuidava deles.

[[v28-11-4]]

^<<v28-11-4,4>>^ Com laços de amor e de carinho, eu os trouxe para perto de mim; eu os segurei nos braços como quem pega uma criança no colo. Eu me inclinei e lhes dei de comer."

[[v28-11-5]]

^<<v28-11-5,5>>^ — Eles não querem voltar para mim e por isso irão de novo para o Egito e serão conquistados pela Assíria.

[[v28-11-6]]

^<<v28-11-6,6>>^ Virá a guerra, e os inimigos arrombarão os portões das cidades e as arrasarão. O meu povo será morto por seguir maus conselhos.

[[v28-11-7]]

^<<v28-11-7,7>>^ O meu povo teima em se revoltar contra mim; por isso, eles serão levados como prisioneiros pelo inimigo, e ninguém poderá salvá-los.

[[v28-11-8]]

^<<v28-11-8,8>>^ "Israel, como poderia eu abandoná-lo? Como poderia desampará-lo? Será que eu o destruiria, como destruí Admá? Ou faria com você o que fiz com Zeboim ? Não! Não posso fazer isso, pois o meu coração está comovido, e tenho muita compaixão de você.

[[v28-11-9]]

^<<v28-11-9,9>>^ Não deixarei que a ira  me domine, não destruirei o meu povo outra vez. Pois eu sou Deus e não um ser humano; eu, o Santo Deus, estou no meio do meu povo e não o destruirei novamente."

[[v28-11-10]]

^<<v28-11-10,10>>^ — Quando eu rugir como leão contra os inimigos, o meu povo me seguirá. O meu povo virá correndo do oeste;

[[v28-11-11]]

^<<v28-11-11,11>>^ como pássaros, eles virão depressa do Egito e como pombas virão da Assíria. Eu os farei morar de novo na sua terra. Eu, o Senhor , estou falando.

[[v28-11-12]]

^<<v28-11-12,12>>^ O Senhor  Deus diz: — O povo de Israel me cerca com mentiras e falsidades, e o povo de Judá se revolta contra mim, o Santo Deus, que sou sempre fiel.

'''

xref:028-oseias/028-oseias-010.adoc#v28-10-0[&#60; Capítulo Anterior] | <<v28-11-0,Topo>> | xref:028-oseias/028-oseias-012.adoc#v28-12-0[Próximo Capítulo &#62;]