include::./index.adoc[]

[[v28-8-0]]
=== Oséias, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-8-1]]

^<<v28-8-1,1>>^ O Senhor  Deus diz: — Toquem a corneta! O inimigo ataca a minha terra como uma águia porque o meu povo quebrou a aliança  que fiz com eles e não obedece às minhas leis .

[[v28-8-2]]

^<<v28-8-2,2>>^ Eles oram a mim, dizendo: "Tu és o nosso Deus, e nós somos dedicados a ti."

[[v28-8-3]]

^<<v28-8-3,3>>^ Mas eles rejeitaram o que é bom e por isso serão perseguidos pelo inimigo.

[[v28-8-4]]

^<<v28-8-4,4>>^ — O meu povo escolheu reis sem me consultar e nomeou governadores sem a minha aprovação. Com a sua prata e com o seu ouro, fizeram ídolos e por isso serão destruídos.

[[v28-8-5]]

^<<v28-8-5,5>>^ Eu odeio o bezerro de ouro que o povo da cidade de Samaria adora e estou irado  com eles. Até quando eles vão continuar adorando ídolos?

[[v28-8-6]]

^<<v28-8-6,6>>^ Um israelita fez o bezerro; esta estátua não é Deus e será quebrada em pedaços.

[[v28-8-7]]

^<<v28-8-7,7>>^ Eles semearam ventos e colherão tempestades. O trigo não produzirá espigas; mas, se houver espigas, elas serão devoradas por estrangeiros.

[[v28-8-8]]

^<<v28-8-8,8>>^ Israel está perdido! As outras nações consideram Israel um objeto sem valor.

[[v28-8-9]]

^<<v28-8-9,9>>^ Os israelitas são como um jumento bravo que teima em andar sozinho. Eles foram pedir a ajuda da Assíria e pagaram outras nações para protegê-los.

[[v28-8-10]]

^<<v28-8-10,10>>^ Mas eu vou pegá-los e castigá-los, e por algum tempo eles sofrerão debaixo do poder cruel do imperador da Assíria.

[[v28-8-11]]

^<<v28-8-11,11>>^ — O povo de Israel construiu muitos altares para conseguir o perdão dos seus pecados, mas esses altares só servem para que o povo peque ainda mais.

[[v28-8-12]]

^<<v28-8-12,12>>^ Escrevi milhares de leis para o povo, mas eles as rejeitaram como se não tivessem valor.

[[v28-8-13]]

^<<v28-8-13,13>>^ Eles me oferecem sacrifícios  e gostam de comer dos animais sacrificados. Mas eu, o Senhor  Deus, não estou contente com eles. Eu lembrarei dos seus pecados e os castigarei. Vou mandá-los de volta para o Egito,

[[v28-8-14]]

^<<v28-8-14,14>>^ pois o povo de Israel esqueceu o seu Criador. O povo de Israel construiu palácios, e o povo de Judá construiu cidades cercadas de muralhas; mas eu vou mandar um fogo que queimará as cidades e destruirá as fortalezas.

'''

xref:028-oseias/028-oseias-007.adoc#v28-7-0[&#60; Capítulo Anterior] | <<v28-8-0,Topo>> | xref:028-oseias/028-oseias-009.adoc#v28-9-0[Próximo Capítulo &#62;]