include::./index.adoc[]

[[v28-1-0]]
=== Oséias, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-1-1]]

^<<v28-1-1,1>>^ Esta é a mensagem que o Senhor  Deus deu a Oseias, filho de Beeri, durante os reinados de Uzias, Jotão, Acaz e Ezequias, na terra de Judá, e de Jeroboão, filho de Joás, na terra de Israel.

[[v28-1-2]]

^<<v28-1-2,2>>^ Quando o Senhor  Deus falou pela primeira vez por meio de Oseias ao povo de Israel, ele disse a Oseias: — Vá e case com uma prostituta de um templo pagão ; os filhos que nascerem serão filhos de uma prostituta. Pois o povo de Israel agiu como uma prostituta: eles foram infiéis e me abandonaram.

[[v28-1-3]]

^<<v28-1-3,3>>^ Então Oseias foi e casou com Gomer, filha de Diblaim. Quando nasceu o primeiro filho,

[[v28-1-4]]

^<<v28-1-4,4>>^ o Senhor  Deus disse a Oseias: — Ponha no menino o nome de Jezreel porque daqui a pouco vou castigar o rei de Israel por causa dos crimes de morte que o rei Jeú, o antepassado dele, cometeu em Jezreel. Vou acabar com o Reino de Israel

[[v28-1-5]]

^<<v28-1-5,5>>^ e no vale de Jezreel destruirei o poder militar de Israel.

[[v28-1-6]]

^<<v28-1-6,6>>^ Depois, Gomer deu à luz uma filha, e o Senhor  disse a Oseias: — Ponha na menina o nome de Não-Amada porque eu não terei mais amor pelo povo de Israel e não o perdoarei.

[[v28-1-7]]

^<<v28-1-7,7>>^ Mas continuarei a amar o povo de Judá. Eu mesmo, o Senhor , seu Deus, os salvarei. Porém não farei isso por meio de guerra: não usarei arcos e flechas, nem espadas, nem cavalos de guerra e cavaleiros.

[[v28-1-8]]

^<<v28-1-8,8>>^ Depois que desmamou a filha, Gomer ficou grávida mais uma vez e deu à luz outro filho.

[[v28-1-9]]

^<<v28-1-9,9>>^ E o Senhor  Deus disse a Oseias: — Ponha no menino o nome de Não-Meu-Povo, pois o povo de Israel não é mais o meu povo, e eu não sou mais o Deus deles.

[[v28-1-10]]

^<<v28-1-10,10>>^ Um dia, o povo de Israel será como os grãos de areia do mar; será tão numeroso, que não poderá ser contado, nem medido. E, no mesmo lugar onde Deus disse: "Vocês não são o meu povo", ali ele dirá: "Vocês são os filhos do Deus vivo".

[[v28-1-11]]

^<<v28-1-11,11>>^ Os povos de Judá e de Israel se unirão e juntos escolherão um só chefe. Serão mais uma vez um povo poderoso e rico. Como será grande esse dia, o Dia de Jezreel !

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-oseias/028-oseias-002.adoc#v28-2-0[Próximo Capítulo &#62;]