include::./index.adoc[]

[[v28-13-0]]
=== Oséias, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v28-13-1]]

^<<v28-13-1,1>>^ Antigamente, quando a gente da tribo  de Efraim falava, as outras tribos ficavam com medo, pois todos respeitavam os efraimitas. Mas eles começaram a adorar o deus Baal  e por isso vão morrer.

[[v28-13-2]]

^<<v28-13-2,2>>^ Continuam pecando cada vez mais, fazendo imagens de metal para adorar; essas estátuas de prata são invenção humana, são feitas por homens, e no entanto eles dizem: "Ofereçam sacrifícios  a estes deuses!" E chegam até a beijar esses bezerros de metal!

[[v28-13-3]]

^<<v28-13-3,3>>^ Por isso, essa gente desaparecerá como a cerração ao nascer do sol, ou como o orvalho, que seca logo de manhã, ou como a palha, que o vento leva embora, ou como a fumaça, que sai pela chaminé.

[[v28-13-4]]

^<<v28-13-4,4>>^ O Senhor  Deus diz: — Eu, o Senhor , sou o Deus de vocês desde que os tirei do Egito; eu sou o único Deus que vocês conhecem, o único Deus que os salvou.

[[v28-13-5]]

^<<v28-13-5,5>>^ Eu cuidei de vocês quando estavam no deserto, naquelas terras sem água.

[[v28-13-6]]

^<<v28-13-6,6>>^ Mas, quando entraram na boa terra, vocês tiveram comida de sobra e ficaram satisfeitos; então os corações de vocês se encheram de orgulho, e vocês esqueceram de mim.

[[v28-13-7]]

^<<v28-13-7,7>>^ Portanto, vou atacá-los como um leão; ficarei de tocaia como um leopardo.

[[v28-13-8]]

^<<v28-13-8,8>>^ Como uma ursa de quem roubaram os filhotes, eu sairei contra vocês e quebrarei as suas costelas. Como um leão, eu os devorarei ali mesmo; como uma fera, eu os despedaçarei.

[[v28-13-9]]

^<<v28-13-9,9>>^ Povo de Israel, eu vou acabar com vocês; quem poderá salvá-los?

[[v28-13-10]]

^<<v28-13-10,10>>^ Vocês pediram que eu lhes desse um rei e também chefes em todas as cidades. Mas como é que eles podem salvá-los?

[[v28-13-11]]

^<<v28-13-11,11>>^ Fiquei irado  com vocês e por isso lhes dei reis; e, estando ainda irado, eu os tirei de vocês.

[[v28-13-12]]

^<<v28-13-12,12>>^ — Os pecados de Israel foram anotados, as suas maldades foram escritas.

[[v28-13-13]]

^<<v28-13-13,13>>^ Chegou a hora de Israel começar a viver, mas Israel não quer porque não tem juízo; é como uma criança que na hora de nascer não quer sair da barriga da mãe.

[[v28-13-14]]

^<<v28-13-14,14>>^ Será, então, que eu vou salvar o meu povo da morte? Será que vou livrá-los do mundo dos mortos ? Ó morte, venha com os seus tormentos. Ó mundo dos mortos, venha com os seus castigos! Eu não terei mais compaixão deste povo!

[[v28-13-15]]

^<<v28-13-15,15>>^ Mesmo que Israel cresça como uma planta viçosa, o Senhor  Deus mandará que o inimigo venha do leste, como se fosse o vento quente do deserto, que secará completamente as fontes e as nascentes de água. Todas as riquezas do país serão levadas embora.

[[v28-13-16]]

^<<v28-13-16,16>>^ O povo de Samaria será castigado porque se revoltou contra o seu Deus. Os homens morrerão na guerra, as crianças serão despedaçadas, e as barrigas das mulheres grávidas serão rasgadas.

'''

xref:028-oseias/028-oseias-012.adoc#v28-12-0[&#60; Capítulo Anterior] | <<v28-13-0,Topo>> | xref:028-oseias/028-oseias-014.adoc#v28-14-0[Próximo Capítulo &#62;]