include::./index.adoc[]

[[v41-4-0]]
=== Marcos, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-4-1]]

^<<v41-4-1,1>>^ Jesus começou a ensinar outra vez na beira do lago da Galileia. A multidão que se ajuntou em volta dele era tão grande, que ele entrou e sentou-se num barco perto da praia, onde o povo estava.

[[v41-4-2]]

^<<v41-4-2,2>>^ Jesus usava parábolas  para ensinar muitas coisas. Ele dizia:

[[v41-4-3]]

^<<v41-4-3,3>>^ — Escutem! Certo homem saiu para semear.

[[v41-4-4]]

^<<v41-4-4,4>>^ E, quando estava espalhando as sementes, algumas caíram na beira do caminho, e os passarinhos comeram tudo.

[[v41-4-5]]

^<<v41-4-5,5>>^ Outra parte das sementes caiu num lugar onde havia muitas pedras e pouca terra. As sementes brotaram logo porque a terra não era funda.

[[v41-4-6]]

^<<v41-4-6,6>>^ Mas, quando o sol apareceu, queimou as plantas, e elas secaram porque não tinham raízes.

[[v41-4-7]]

^<<v41-4-7,7>>^ Outras sementes caíram no meio de espinhos, que cresceram e sufocaram as plantas. Por isso nada produziram.

[[v41-4-8]]

^<<v41-4-8,8>>^ Mas as sementes que caíram em terra boa brotaram, cresceram e produziram na base de trinta, sessenta e até cem grãos por um.

[[v41-4-9]]

^<<v41-4-9,9>>^ E Jesus terminou, dizendo: — Se vocês têm ouvidos para ouvir, então ouçam.

[[v41-4-10]]

^<<v41-4-10,10>>^ Quando a multidão foi embora, as pessoas que ficaram ali começaram, junto com os doze discípulos, a fazer perguntas a Jesus sobre parábolas .

[[v41-4-11]]

^<<v41-4-11,11>>^ Jesus disse a eles: — A vocês Deus mostra o segredo do seu Reino . Mas para os que estão fora do Reino tudo é ensinado por meio de parábolas,

[[v41-4-12]]

^<<v41-4-12,12>>^ para que olhem e não enxerguem nada e para que escutem e não entendam; se não, eles voltariam para Deus, e ele os perdoaria.

[[v41-4-13]]

^<<v41-4-13,13>>^ Então Jesus perguntou: — Se vocês não entendem essa parábola , como vão entender as outras?

[[v41-4-14]]

^<<v41-4-14,14>>^ E continuou: — O semeador semeia a mensagem de Deus.

[[v41-4-15]]

^<<v41-4-15,15>>^ Algumas pessoas que a ouvem são como as sementes que caíram na beira do caminho. Logo que ouvem, Satanás vem e tira a mensagem que foi semeada no coração delas.

[[v41-4-16]]

^<<v41-4-16,16>>^ Outras pessoas são como as sementes que foram semeadas onde havia muitas pedras. Quando ouvem a mensagem, elas a aceitam logo com alegria;

[[v41-4-17]]

^<<v41-4-17,17>>^ mas depois de pouco tempo essas pessoas abandonam a mensagem porque ela não criou raízes nelas. E, quando por causa da mensagem chegam os sofrimentos e as perseguições, elas logo abandonam a sua fé.

[[v41-4-18]]

^<<v41-4-18,18>>^ Ainda outras são parecidas com as sementes que foram semeadas no meio dos espinhos. Elas ouvem a mensagem,

[[v41-4-19]]

^<<v41-4-19,19>>^ mas, quando aparecem as preocupações deste mundo, a ilusão das riquezas e outras ambições, estas coisas sufocam a mensagem, e ela não produz frutos.

[[v41-4-20]]

^<<v41-4-20,20>>^ E existem aquelas pessoas que são como as sementes que foram semeadas em terra boa. Elas ouvem, e aceitam a mensagem, e produzem uma grande colheita: umas, trinta; outras, sessenta; e ainda outras, cem vezes mais do que foi semeado.

[[v41-4-21]]

^<<v41-4-21,21>>^ Jesus continuou: — Por acaso alguém acende uma lamparina para colocá-la debaixo de um cesto ou de uma cama? Claro que não! Para iluminar bem, ela deve ser colocada no lugar próprio.

[[v41-4-22]]

^<<v41-4-22,22>>^ Pois tudo o que está escondido será descoberto, e tudo o que está em segredo será conhecido.

[[v41-4-23]]

^<<v41-4-23,23>>^ Se vocês têm ouvidos para ouvir, então ouçam.

[[v41-4-24]]

^<<v41-4-24,24>>^ Disse também: — Cuidado com o que vocês ouvem! Deus usará para julgar vocês a mesma regra que vocês usarem para julgar os outros. E com mais dureza ainda!

[[v41-4-25]]

^<<v41-4-25,25>>^ Quem tem receberá mais; mas quem não tem, até o pouco que tem será tirado dele.

[[v41-4-26]]

^<<v41-4-26,26>>^ Jesus disse: — O Reino de Deus  é como um homem que joga a semente na terra.

[[v41-4-27]]

^<<v41-4-27,27>>^ Quer ele esteja acordado, quer esteja dormindo, ela brota e cresce, sem ele saber como isso acontece.

[[v41-4-28]]

^<<v41-4-28,28>>^ É a própria terra que dá o seu fruto: primeiro aparece a planta, depois a espiga, e, mais tarde, os grãos que enchem a espiga.

[[v41-4-29]]

^<<v41-4-29,29>>^ Quando as espigas ficam maduras, o homem começa a cortá-las com a foice, pois chegou o tempo da colheita.

[[v41-4-30]]

^<<v41-4-30,30>>^ Jesus continuou: — Com o que podemos comparar o Reino de Deus ? Que parábola  podemos usar para isso?

[[v41-4-31]]

^<<v41-4-31,31>>^ Ele é como uma semente de mostarda, que é a menor de todas as sementes.

[[v41-4-32]]

^<<v41-4-32,32>>^ Mas, depois de semeada, cresce muito até ficar a maior de todas as plantas. E os seus ramos são tão grandes, que os passarinhos fazem ninhos entre as suas folhas.

[[v41-4-33]]

^<<v41-4-33,33>>^ Assim, usando muitas parábolas  como estas, Jesus falava ao povo de um modo que eles podiam entender.

[[v41-4-34]]

^<<v41-4-34,34>>^ E só falava com eles usando parábolas, mas explicava tudo em particular aos discípulos.

[[v41-4-35]]

^<<v41-4-35,35>>^ Naquele dia, de tardinha, Jesus disse aos discípulos: — Vamos para o outro lado do lago.

[[v41-4-36]]

^<<v41-4-36,36>>^ Então eles deixaram o povo ali, subiram no barco em que Jesus estava e foram com ele; e outros barcos o acompanharam.

[[v41-4-37]]

^<<v41-4-37,37>>^ De repente, começou a soprar um vento muito forte, e as ondas arrebentavam com tanta força em cima do barco, que ele já estava ficando cheio de água.

[[v41-4-38]]

^<<v41-4-38,38>>^ Jesus estava dormindo na parte detrás do barco, com a cabeça numa almofada. Então os discípulos o acordaram e disseram: — Mestre! Nós vamos morrer! O senhor não se importa com isso?

[[v41-4-39]]

^<<v41-4-39,39>>^ Então ele se levantou, falou duro com o vento e disse ao lago: — Silêncio! Fique quieto! O vento parou, e tudo ficou calmo.

[[v41-4-40]]

^<<v41-4-40,40>>^ Aí ele perguntou: — Por que é que vocês são assim tão medrosos? Vocês ainda não têm fé?

[[v41-4-41]]

^<<v41-4-41,41>>^ E os discípulos, cheios de medo, diziam uns aos outros: — Que homem é este que manda até no vento e nas ondas?!

'''

xref:041-marcos/041-marcos-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-marcos/041-marcos-005.adoc#v41-5-0[Próximo Capítulo &#62;]