include::./index.adoc[]

[[v41-8-0]]
=== Marcos, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-8-1]]

^<<v41-8-1,1>>^ Pouco tempo depois, ajuntou-se outra vez uma grande multidão. Como eles não tinham nada para comer, Jesus chamou os discípulos e disse:

[[v41-8-2]]

^<<v41-8-2,2>>^ — Estou com pena dessa gente porque já faz três dias que eles estão comigo e não têm nada para comer.

[[v41-8-3]]

^<<v41-8-3,3>>^ Se eu os mandar para casa com fome, eles vão cair de fraqueza pelo caminho, pois alguns vieram de longe.

[[v41-8-4]]

^<<v41-8-4,4>>^ Os discípulos perguntaram: — Como vamos encontrar, neste lugar deserto, comida que dê para toda essa gente?

[[v41-8-5]]

^<<v41-8-5,5>>^ — Quantos pães vocês têm?  — perguntou Jesus. — Sete! — responderam eles.

[[v41-8-6]]

^<<v41-8-6,6>>^ Aí Jesus mandou o povo sentar-se no chão. Depois pegou os sete pães e deu graças a Deus. Então os partiu e os entregou aos discípulos, e eles os distribuíram ao povo.

[[v41-8-7]]

^<<v41-8-7,7>>^ Eles tinham também alguns peixinhos. Jesus deu graças a Deus por eles e mandou que os discípulos os distribuíssem.

[[v41-8-8]]

^<<v41-8-8,8>>^ Todos comeram e ficaram satisfeitos; e os discípulos ainda encheram sete cestos com os pedaços que sobraram.

[[v41-8-9]]

^<<v41-8-9,9>>^ As pessoas que comeram eram mais ou menos quatro mil. Jesus mandou o povo embora,

[[v41-8-10]]

^<<v41-8-10,10>>^ e, logo depois, subiu no barco com os seus discípulos, e foi para a região de Dalmanuta.

[[v41-8-11]]

^<<v41-8-11,11>>^ Alguns fariseus  chegaram e começaram a falar com Jesus. Eles queriam conseguir alguma prova contra ele e por isso pediram que ele fizesse um milagre para mostrar que o seu poder vinha mesmo de Deus.

[[v41-8-12]]

^<<v41-8-12,12>>^ Jesus deu um grande suspiro e disse: — Por que as pessoas de hoje pedem um milagre? Eu afirmo a vocês que isto é verdade: nenhum milagre será feito para estas pessoas.

[[v41-8-13]]

^<<v41-8-13,13>>^ Então Jesus foi embora. Ele subiu no barco e voltou para o lado leste do lago.

[[v41-8-14]]

^<<v41-8-14,14>>^ Os discípulos haviam esquecido de levar pão e só tinham um pão no barco.

[[v41-8-15]]

^<<v41-8-15,15>>^ Jesus chamou a atenção deles, dizendo: — Fiquem alertas e tomem cuidado com o fermento dos fariseus  e com o fermento de Herodes!

[[v41-8-16]]

^<<v41-8-16,16>>^ Aí os discípulos começaram a dizer uns aos outros: — Ele está dizendo isso porque não temos pão.

[[v41-8-17]]

^<<v41-8-17,17>>^ Jesus ouviu o que eles estavam dizendo e perguntou: — Por que vocês estão discutindo por não terem pão? Vocês não sabem e não entendem o que eu disse? Por que são tão duros para entender as coisas?

[[v41-8-18]]

^<<v41-8-18,18>>^ Vocês têm olhos e não enxergam? Têm ouvidos e não escutam? Não lembram

[[v41-8-19]]

^<<v41-8-19,19>>^ dos cinco pães que eu parti para cinco mil pessoas? Quantos cestos cheios de pedaços vocês recolheram? Eles responderam: — Doze.

[[v41-8-20]]

^<<v41-8-20,20>>^ Jesus perguntou outra vez: — E, quando eu parti os sete pães para quatro mil pessoas, quantos cestos cheios de pedaços vocês recolheram? Eles responderam: — Sete.

[[v41-8-21]]

^<<v41-8-21,21>>^ Então Jesus perguntou: — Será que vocês ainda não entendem?

[[v41-8-22]]

^<<v41-8-22,22>>^ Depois Jesus e os discípulos chegaram ao povoado de Betsaida. Algumas pessoas trouxeram um cego e pediram a Jesus que tocasse nele.

[[v41-8-23]]

^<<v41-8-23,23>>^ Ele pegou o cego pela mão e o levou para fora do povoado. Então cuspiu, passou a saliva nos olhos do homem, pôs a mão sobre ele e perguntou: — Você está vendo alguma coisa?

[[v41-8-24]]

^<<v41-8-24,24>>^ O homem olhou e disse: — Vejo pessoas; elas parecem árvores, mas estão andando.

[[v41-8-25]]

^<<v41-8-25,25>>^ Jesus pôs outra vez as mãos sobre os olhos dele. Dessa vez o cego olhou firme e ficou curado; aí começou a ver tudo muito bem.

[[v41-8-26]]

^<<v41-8-26,26>>^ Em seguida, Jesus mandou o homem para casa e ordenou: — Não volte para o povoado!

[[v41-8-27]]

^<<v41-8-27,27>>^ Depois Jesus e os seus discípulos foram para os povoados que ficam perto de Cesareia de Filipe. No caminho, ele lhes perguntou: — Quem o povo diz que eu sou?

[[v41-8-28]]

^<<v41-8-28,28>>^ Os discípulos responderam: — Alguns dizem que o senhor é João Batista; outros, que é Elias; e outros, que é um dos profetas .

[[v41-8-29]]

^<<v41-8-29,29>>^ — E vocês? Quem vocês dizem que eu sou?  — perguntou Jesus. — O senhor é o Messias ! — respondeu Pedro.

[[v41-8-30]]

^<<v41-8-30,30>>^ Então Jesus proibiu os discípulos de contarem isso a qualquer pessoa.

[[v41-8-31]]

^<<v41-8-31,31>>^ Jesus começou a ensinar os discípulos, dizendo: — O Filho do Homem  terá de sofrer muito. Ele será rejeitado pelos líderes judeus, pelos chefes dos sacerdotes e pelos mestres  da Lei. Será morto e, três dias depois, ressuscitará.

[[v41-8-32]]

^<<v41-8-32,32>>^ Jesus dizia isso com toda a clareza. Então Pedro o levou para um lado e começou a repreendê-lo.

[[v41-8-33]]

^<<v41-8-33,33>>^ Jesus virou-se, olhou para os discípulos e repreendeu Pedro, dizendo: — Saia da minha frente, Satanás! Você está pensando como um ser humano pensa e não como Deus pensa.

[[v41-8-34]]

^<<v41-8-34,34>>^ Aí Jesus chamou a multidão e os discípulos e disse: — Se alguém quer ser meu seguidor, que esqueça os seus próprios interesses, esteja pronto para morrer como eu vou morrer e me acompanhe.

[[v41-8-35]]

^<<v41-8-35,35>>^ Pois quem põe os seus próprios interesses em primeiro lugar nunca terá a vida verdadeira; mas quem esquece a si mesmo por minha causa e por causa do evangelho  terá a vida verdadeira.

[[v41-8-36]]

^<<v41-8-36,36>>^ O que adianta alguém ganhar o mundo inteiro, mas perder a vida verdadeira?

[[v41-8-37]]

^<<v41-8-37,37>>^ Pois não há nada que poderá pagar para ter de volta essa vida.

[[v41-8-38]]

^<<v41-8-38,38>>^ Portanto, se nesta época de incredulidade e maldade alguém tiver vergonha de mim e dos meus ensinamentos, então o Filho do Homem, quando vier na glória  do seu Pai com os santos anjos, também terá vergonha dessa pessoa.

'''

xref:041-marcos/041-marcos-007.adoc#v41-7-0[&#60; Capítulo Anterior] | <<v41-8-0,Topo>> | xref:041-marcos/041-marcos-009.adoc#v41-9-0[Próximo Capítulo &#62;]