include::./index.adoc[]

[[v41-13-0]]
=== Marcos, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-13-1]]

^<<v41-13-1,1>>^ Quando Jesus estava saindo do pátio do Templo, um discípulo disse: — Mestre, veja que pedras e edifícios impressionantes!

[[v41-13-2]]

^<<v41-13-2,2>>^ Jesus respondeu: — Você está vendo estes enormes edifícios? Pois aqui não ficará uma pedra em cima da outra; tudo será destruído!

[[v41-13-3]]

^<<v41-13-3,3>>^ Jesus estava sentado no monte das Oliveiras, olhando para o Templo, quando Pedro, Tiago, João e André lhe perguntaram em particular:

[[v41-13-4]]

^<<v41-13-4,4>>^ — Conte para nós quando é que isso vai acontecer. Que sinal haverá para mostrar quando é que todas essas coisas vão começar?

[[v41-13-5]]

^<<v41-13-5,5>>^ Então Jesus começou a ensiná-los. Ele disse: — Tomem cuidado para que ninguém engane vocês.

[[v41-13-6]]

^<<v41-13-6,6>>^ Porque muitos vão aparecer fingindo ser eu e dizendo: "Eu sou o Messias !" E enganarão muitas pessoas.

[[v41-13-7]]

^<<v41-13-7,7>>^ Não tenham medo quando ouvirem o barulho de batalhas ou notícias de guerras. Tudo isso vai acontecer, mas ainda não será o fim.

[[v41-13-8]]

^<<v41-13-8,8>>^ Uma nação vai guerrear contra outra, e um país atacará outro. Em vários lugares haverá tremores de terra e falta de alimentos. Essas coisas serão como as primeiras dores de parto.

[[v41-13-9]]

^<<v41-13-9,9>>^ — Vocês precisam ter cuidado porque serão presos e levados aos tribunais e serão chicoteados nas sinagogas . Por serem meus seguidores, vocês serão levados aos governadores e reis para serem julgados e falarão a eles sobre o evangelho .

[[v41-13-10]]

^<<v41-13-10,10>>^ Pois, antes de chegar o fim, o evangelho precisa ser anunciado a todos os povos.

[[v41-13-11]]

^<<v41-13-11,11>>^ Quando prenderem e entregarem vocês às autoridades, não fiquem preocupados, antes da hora, com o que irão dizer. Quando chegar o momento, digam o que Deus lhes der para dizer. Porque as palavras que disserem não serão de vocês mesmos, mas virão do Espírito Santo.

[[v41-13-12]]

^<<v41-13-12,12>>^ Muitos entregarão os seus próprios irmãos para serem mortos, e os pais entregarão os filhos. E os filhos ficarão contra os pais e os matarão.

[[v41-13-13]]

^<<v41-13-13,13>>^ Todos odiarão vocês por serem meus seguidores, mas quem ficar firme até o fim será salvo.

[[v41-13-14]]

^<<v41-13-14,14>>^ E Jesus continuou: — Vocês verão "o grande terror" no lugar onde não deveria estar. (Que o leitor entenda o que isso quer dizer!) Então, os que estiverem na região da Judeia, que fujam para os montes.

[[v41-13-15]]

^<<v41-13-15,15>>^ Quem estiver em cima da sua casa, no terraço, que fuja logo e não entre para pegar nada.

[[v41-13-16]]

^<<v41-13-16,16>>^ E quem estiver no campo, que não volte para casa a fim de buscar as suas roupas.

[[v41-13-17]]

^<<v41-13-17,17>>^ Ai das mulheres grávidas e das mães com criancinhas naqueles dias!

[[v41-13-18]]

^<<v41-13-18,18>>^ Orem a Deus para que isso não aconteça no inverno.

[[v41-13-19]]

^<<v41-13-19,19>>^ Porque naqueles dias haverá um sofrimento tão grande como nunca houve desde que Deus criou o mundo; e nunca mais acontecerá uma coisa igual.

[[v41-13-20]]

^<<v41-13-20,20>>^ Porém o Senhor diminuiu esse tempo de sofrimento. Se não fosse assim, ninguém seria salvo. Mas, por causa do povo que Deus escolheu para salvar, esse tempo já foi diminuído.

[[v41-13-21]]

^<<v41-13-21,21>>^ — Portanto, se alguém disser para vocês: "Vejam! O Messias  está aqui" ou "O Messias está ali", não acreditem.

[[v41-13-22]]

^<<v41-13-22,22>>^ Porque aparecerão falsos profetas  e falsos messias, que farão milagres e maravilhas para enganar, se possível, até o povo escolhido de Deus.

[[v41-13-23]]

^<<v41-13-23,23>>^ Prestem atenção! Eu estou lhes dizendo tudo isso, antes que aconteça.

[[v41-13-24]]

^<<v41-13-24,24>>^ Jesus disse: — Depois daqueles dias de sofrimento, o sol ficará escuro, e a lua não brilhará mais.

[[v41-13-25]]

^<<v41-13-25,25>>^ As estrelas cairão do céu, e os poderes do espaço serão abalados.

[[v41-13-26]]

^<<v41-13-26,26>>^ Então o Filho do Homem  aparecerá descendo nas nuvens, com grande poder e glória .

[[v41-13-27]]

^<<v41-13-27,27>>^ Ele mandará os anjos aos quatro cantos da terra e reunirá os escolhidos de Deus de um lado do mundo até o outro.

[[v41-13-28]]

^<<v41-13-28,28>>^ Jesus disse ainda: — Aprendam a lição que a figueira ensina. Quando os seus ramos ficam verdes, e as folhas começam a brotar, vocês sabem que está chegando o verão.

[[v41-13-29]]

^<<v41-13-29,29>>^ Assim também, quando virem acontecer essas coisas, fiquem sabendo que o tempo está perto, pronto para começar.

[[v41-13-30]]

^<<v41-13-30,30>>^ Eu afirmo a vocês que isto é verdade: essas coisas vão acontecer antes de morrerem todos os que agora estão vivos.

[[v41-13-31]]

^<<v41-13-31,31>>^ O céu e a terra desaparecerão, mas as minhas palavras ficarão para sempre.

[[v41-13-32]]

^<<v41-13-32,32>>^ E Jesus terminou, dizendo: — Mas ninguém sabe nem o dia nem a hora em que tudo isso vai acontecer, nem os anjos do céu, nem o Filho, mas somente o Pai.

[[v41-13-33]]

^<<v41-13-33,33>>^ Vigiem e fiquem alertas, pois vocês não sabem quando chegará a hora.

[[v41-13-34]]

^<<v41-13-34,34>>^ Será como um homem que sai de casa e viaja para longe; mas, antes de ir, dá ordens, distribui o trabalho entre os empregados e manda o porteiro ficar de vigia.

[[v41-13-35]]

^<<v41-13-35,35>>^ Então vigiem, pois vocês não sabem quando o dono da casa vai voltar; se será à tarde, ou à meia-noite, ou de madrugada, ou de manhã.

[[v41-13-36]]

^<<v41-13-36,36>>^ Se ele chegar de repente, que não encontre vocês dormindo!

[[v41-13-37]]

^<<v41-13-37,37>>^ O que eu lhes digo digo a todos: fiquem vigiando!

'''

xref:041-marcos/041-marcos-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-marcos/041-marcos-014.adoc#v41-14-0[Próximo Capítulo &#62;]