include::./index.adoc[]

[[v41-12-0]]
=== Marcos, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-12-1]]

^<<v41-12-1,1>>^ Depois Jesus começou a falar por meio de parábolas . Ele disse: — Certo homem fez uma plantação de uvas e pôs uma cerca em volta dela. Construiu um tanque para pisar as uvas e fazer vinho e construiu uma torre para o vigia. Em seguida, arrendou a plantação para alguns lavradores e foi viajar.

[[v41-12-2]]

^<<v41-12-2,2>>^ Quando chegou o tempo da colheita, o dono enviou um empregado para receber a sua parte.

[[v41-12-3]]

^<<v41-12-3,3>>^ Mas os lavradores agarraram o empregado, bateram nele e o mandaram de volta sem nada.

[[v41-12-4]]

^<<v41-12-4,4>>^ O dono mandou mais um empregado, mas eles bateram na cabeça dele e o trataram de um modo vergonhoso.

[[v41-12-5]]

^<<v41-12-5,5>>^ E ainda outro foi mandado para lá, mas os lavradores o mataram. E o mesmo aconteceu com muitos mais — uns foram surrados, e outros foram mortos.

[[v41-12-6]]

^<<v41-12-6,6>>^ E agora a única pessoa que o dono da plantação tinha para mandar lá era o seu querido filho. Finalmente ele o mandou, pensando assim: "O meu filho eles vão respeitar."

[[v41-12-7]]

^<<v41-12-7,7>>^ Mas os lavradores disseram uns aos outros: "Este é o filho do dono; ele vai herdar a plantação. Vamos matá-lo, e a plantação será nossa."

[[v41-12-8]]

^<<v41-12-8,8>>^ — Então agarraram o filho, e o mataram, e jogaram o corpo para fora da plantação.

[[v41-12-9]]

^<<v41-12-9,9>>^ Aí Jesus perguntou: — E agora, o que é que o dono da plantação vai fazer? Ele virá, matará aqueles homens e entregará a plantação a outros lavradores.

[[v41-12-10]]

^<<v41-12-10,10>>^ Vocês não leram o que as Escrituras Sagradas  dizem? "A pedra que os construtores rejeitaram veio a ser a mais importante de todas.

[[v41-12-11]]

^<<v41-12-11,11>>^ Isso foi feito pelo Senhor e é uma coisa maravilhosa!"

[[v41-12-12]]

^<<v41-12-12,12>>^ Os líderes judeus sabiam que a parábola era contra eles e quiseram prender Jesus, mas tinham medo do povo. Por isso deixaram Jesus em paz e foram embora.

[[v41-12-13]]

^<<v41-12-13,13>>^ Depois mandaram que alguns fariseus  e alguns membros do partido de Herodes fossem falar com Jesus a fim de conseguirem alguma prova contra ele.

[[v41-12-14]]

^<<v41-12-14,14>>^ Eles chegaram e disseram: — Mestre, sabemos que o senhor é honesto e não se importa com a opinião dos outros. O senhor não julga pela aparência, mas ensina a verdade sobre a maneira de viver que Deus exige. Diga: é ou não é contra a nossa Lei  pagar impostos ao Imperador romano? Devemos pagar ou não?

[[v41-12-15]]

^<<v41-12-15,15>>^ Mas Jesus percebeu a malícia deles e respondeu: — Por que é que vocês estão procurando uma prova contra mim? Tragam uma moeda para eu ver.

[[v41-12-16]]

^<<v41-12-16,16>>^ Eles trouxeram, e ele perguntou: — De quem são o nome e a cara que estão gravados nesta moeda? Eles responderam: — São do Imperador.

[[v41-12-17]]

^<<v41-12-17,17>>^ Então Jesus disse: — Deem ao Imperador o que é do Imperador e deem a Deus o que é de Deus. E eles ficaram admirados com Jesus.

[[v41-12-18]]

^<<v41-12-18,18>>^ Alguns saduceus , os quais afirmam que ninguém ressuscita, chegaram perto de Jesus e disseram:

[[v41-12-19]]

^<<v41-12-19,19>>^ — Mestre, Moisés escreveu para nós a seguinte lei : "Se um homem morrer e deixar a esposa sem filhos, o irmão dele deve casar com a viúva, para terem filhos, que serão considerados filhos do irmão que morreu."

[[v41-12-20]]

^<<v41-12-20,20>>^ Acontece que havia sete irmãos. O mais velho casou e morreu sem deixar filhos.

[[v41-12-21]]

^<<v41-12-21,21>>^ O segundo casou com a viúva e morreu sem deixar filhos. Aconteceu a mesma coisa com o terceiro.

[[v41-12-22]]

^<<v41-12-22,22>>^ Afinal, os sete irmãos casaram com a mesma mulher e morreram sem deixar filhos. Depois de todos eles, a mulher também morreu.

[[v41-12-23]]

^<<v41-12-23,23>>^ Portanto, no dia da ressurreição, quando todos os mortos tornarem a viver, de qual dos sete a mulher vai ser esposa? Pois todos eles casaram com ela!

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus respondeu: — Como vocês estão errados, não conhecendo nem as Escrituras Sagradas  nem o poder de Deus.

[[v41-12-25]]

^<<v41-12-25,25>>^ Pois, quando os mortos ressuscitarem, serão como os anjos do céu, e ninguém casará.

[[v41-12-26]]

^<<v41-12-26,26>>^ Vocês nunca leram no Livro de Moisés  o que está escrito sobre a ressurreição? Quando fala do espinheiro que estava em fogo, está escrito que Deus disse a Moisés: "Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó."

[[v41-12-27]]

^<<v41-12-27,27>>^ E Deus não é Deus dos mortos e sim dos vivos. Vocês estão completamente errados!

[[v41-12-28]]

^<<v41-12-28,28>>^ Um mestre da Lei  que estava ali ouviu a discussão. Viu que Jesus tinha dado uma boa resposta e por isso perguntou: — Qual é o mais importante de todos os mandamentos da Lei ?

[[v41-12-29]]

^<<v41-12-29,29>>^ Jesus respondeu: — É este: "Escute, povo de Israel! O Senhor, nosso Deus, é o único Senhor.

[[v41-12-30]]

^<<v41-12-30,30>>^ Ame o Senhor, seu Deus, com todo o coração, com toda a alma, com toda a mente e com todas as forças."

[[v41-12-31]]

^<<v41-12-31,31>>^ E o segundo mais importante é este: "Ame os outros como você ama a você mesmo." Não existe outro mandamento mais importante do que esses dois.

[[v41-12-32]]

^<<v41-12-32,32>>^ Então o mestre da Lei disse a Jesus: — Muito bem, Mestre! O senhor disse a verdade. Ele é o único Deus, e não existe outro além dele.

[[v41-12-33]]

^<<v41-12-33,33>>^ Devemos amar a Deus com todo o nosso coração, com toda a nossa mente e com todas as nossas forças e também devemos amar os outros como amamos a nós mesmos. Pois é melhor obedecer a estes dois mandamentos do que trazer animais para serem queimados no altar e oferecer outros sacrifícios  a Deus.

[[v41-12-34]]

^<<v41-12-34,34>>^ Jesus viu que o mestre da Lei tinha respondido com sabedoria e disse: — Você não está longe do Reino de Deus . Depois disso ninguém tinha coragem de fazer mais perguntas a Jesus.

[[v41-12-35]]

^<<v41-12-35,35>>^ Quando Jesus estava ensinando no pátio do Templo, perguntou: — Como podem os mestres  da Lei ensinar que o Messias  é descendente de Davi?

[[v41-12-36]]

^<<v41-12-36,36>>^ Pois Davi, inspirado pelo Espírito Santo, escreveu: "O Senhor Deus disse ao meu Senhor: ‘Sente-se do meu lado direito, até que eu ponha os seus inimigos debaixo dos seus pés.’ "

[[v41-12-37]]

^<<v41-12-37,37>>^ O próprio Davi chama o Messias de Senhor. Portanto, como é que o Messias pode ser descendente de Davi? Uma grande multidão escutava com prazer o que Jesus ensinava.

[[v41-12-38]]

^<<v41-12-38,38>>^ Ele dizia ao povo: — Cuidado com os mestres  da Lei! Eles gostam de andar para lá e para cá, usando capas  compridas, e gostam de ser cumprimentados com respeito nas praças;

[[v41-12-39]]

^<<v41-12-39,39>>^ preferem os lugares de honra nas sinagogas  e os melhores lugares nos banquetes.

[[v41-12-40]]

^<<v41-12-40,40>>^ Exploram as viúvas e roubam os seus bens; e, para disfarçarem, fazem orações compridas. Portanto, o castigo que eles vão sofrer será pior ainda!

[[v41-12-41]]

^<<v41-12-41,41>>^ Jesus estava no pátio do Templo, sentado perto da caixa das ofertas, olhando com atenção as pessoas que punham dinheiro ali. Muitos ricos davam muito dinheiro.

[[v41-12-42]]

^<<v41-12-42,42>>^ Então chegou uma viúva pobre e pôs na caixa duas moedinhas de pouco valor.

[[v41-12-43]]

^<<v41-12-43,43>>^ Aí Jesus chamou os discípulos e disse: — Eu afirmo a vocês que isto é verdade: esta viúva pobre deu mais do que todos.

[[v41-12-44]]

^<<v41-12-44,44>>^ Porque os outros deram do que estava sobrando. Porém ela, que é tão pobre, deu tudo o que tinha para viver.

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]