include::./index.adoc[]

[[v41-9-0]]
=== Marcos, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-9-1]]

^<<v41-9-1,1>>^ E Jesus terminou, dizendo: — Eu afirmo a vocês que isto é verdade: estão aqui algumas pessoas que não morrerão antes de verem o Reino de Deus  chegar com poder.

[[v41-9-2]]

^<<v41-9-2,2>>^ Seis dias depois, Jesus foi para um monte alto, levando consigo somente Pedro, Tiago e João. Ali, eles viram a aparência de Jesus mudar.

[[v41-9-3]]

^<<v41-9-3,3>>^ A sua roupa ficou muito branca e brilhante, mais do que qualquer lavadeira seria capaz de deixar.

[[v41-9-4]]

^<<v41-9-4,4>>^ E os três discípulos viram Elias e Moisés conversando com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ Então Pedro disse a Jesus: — Mestre, como é bom estarmos aqui! Vamos armar três barracas: uma para o senhor, outra para Moisés e outra para Elias.

[[v41-9-6]]

^<<v41-9-6,6>>^ Pedro não sabia o que deveria dizer, pois ele e os outros dois discípulos estavam apavorados.

[[v41-9-7]]

^<<v41-9-7,7>>^ Logo depois, uma nuvem os cobriu, e dela veio uma voz, que disse: — Este é o meu Filho querido. Escutem o que ele diz!

[[v41-9-8]]

^<<v41-9-8,8>>^ Aí os discípulos olharam em volta e viram somente Jesus com eles.

[[v41-9-9]]

^<<v41-9-9,9>>^ Quando estavam descendo do monte, Jesus mandou que não contassem a ninguém o que tinham visto, até que o Filho do Homem  ressuscitasse.

[[v41-9-10]]

^<<v41-9-10,10>>^ Eles obedeceram à ordem, mas discutiram entre si sobre o que queria dizer essa ressurreição.

[[v41-9-11]]

^<<v41-9-11,11>>^ Então perguntaram a Jesus: — Por que os mestres  da Lei dizem que Elias deve vir primeiro?

[[v41-9-12]]

^<<v41-9-12,12>>^ Ele respondeu: — É verdade que Elias vem primeiro para preparar tudo. Mas por que é que as Escrituras Sagradas  afirmam que o Filho do Homem vai sofrer muito e ser rejeitado?

[[v41-9-13]]

^<<v41-9-13,13>>^ Eu afirmo a vocês que Elias já veio, e o maltrataram como quiseram, conforme as Escrituras dizem a respeito dele.

[[v41-9-14]]

^<<v41-9-14,14>>^ Quando eles chegaram perto dos outros discípulos, viram uma grande multidão em volta deles e alguns mestres  da Lei discutindo com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ Quando o povo viu Jesus, todos ficaram admirados e correram logo para o cumprimentarem.

[[v41-9-16]]

^<<v41-9-16,16>>^ Jesus perguntou aos discípulos: — O que é que vocês estão discutindo com eles?

[[v41-9-17]]

^<<v41-9-17,17>>^ Um homem que estava na multidão respondeu: — Mestre, eu trouxe o meu filho para o senhor, porque ele está dominado por um espírito mau e não pode falar.

[[v41-9-18]]

^<<v41-9-18,18>>^ Sempre que o espírito ataca o meu filho, joga-o no chão, e ele começa a espumar e a ranger os dentes; e ele está ficando cada vez mais fraco. Já pedi aos discípulos do senhor que expulsassem o espírito, mas eles não conseguiram.

[[v41-9-19]]

^<<v41-9-19,19>>^ Jesus disse: — Gente sem fé! Até quando ficarei com vocês? Até quando terei de aguentá-los? Tragam o menino aqui.

[[v41-9-20]]

^<<v41-9-20,20>>^ Quando o levaram, o espírito viu Jesus e sacudiu com força o menino. Ele caiu e começou a rolar no chão, espumando pela boca.

[[v41-9-21]]

^<<v41-9-21,21>>^ Aí Jesus perguntou ao pai: — Quanto tempo faz que o seu filho está assim? O pai respondeu: — Ele está assim desde pequeno.

[[v41-9-22]]

^<<v41-9-22,22>>^ Muitas vezes o espírito o joga no fogo e na água para matá-lo. Mas, se o senhor pode, então nos ajude. Tenha pena de nós!

[[v41-9-23]]

^<<v41-9-23,23>>^ Jesus respondeu: — Se eu posso? Tudo é possível para quem tem fé.

[[v41-9-24]]

^<<v41-9-24,24>>^ Então o pai gritou: — Eu tenho fé! Ajude-me a ter mais fé ainda!

[[v41-9-25]]

^<<v41-9-25,25>>^ Quando Jesus viu que muita gente estava se juntando ao redor dele, ordenou ao espírito mau: — Espírito surdo-mudo, saia desse menino e nunca mais entre nele!

[[v41-9-26]]

^<<v41-9-26,26>>^ O espírito gritou, sacudiu o menino e saiu dele, deixando-o como morto. Por isso todos diziam que ele havia morrido.

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus pegou o menino pela mão e o ajudou a ficar de pé.

[[v41-9-28]]

^<<v41-9-28,28>>^ Quando Jesus entrou em casa, os seus discípulos lhe perguntaram em particular: — Por que foi que nós não pudemos expulsar aquele espírito?

[[v41-9-29]]

^<<v41-9-29,29>>^ Jesus respondeu: — Este tipo de espírito só pode ser expulso com oração.

[[v41-9-30]]

^<<v41-9-30,30>>^ Jesus e os discípulos saíram daquele lugar e continuaram atravessando a Galileia. Jesus não queria que ninguém soubesse onde ele estava

[[v41-9-31]]

^<<v41-9-31,31>>^ porque estava ensinando os discípulos. Ele lhes dizia: — O Filho do Homem  será entregue nas mãos dos homens, e eles vão matá-lo; mas três dias depois ele ressuscitará.

[[v41-9-32]]

^<<v41-9-32,32>>^ Eles não entendiam o que Jesus dizia, mas tinham medo de perguntar.

[[v41-9-33]]

^<<v41-9-33,33>>^ Jesus e os discípulos chegaram à cidade de Cafarnaum. Quando já estavam em casa, Jesus perguntou aos doze discípulos: — O que é que vocês estavam discutindo no caminho?

[[v41-9-34]]

^<<v41-9-34,34>>^ Mas eles ficaram calados porque no caminho tinham discutido sobre qual deles era o mais importante.

[[v41-9-35]]

^<<v41-9-35,35>>^ Jesus sentou-se, chamou os doze e lhes disse: — Se alguém quer ser o primeiro, deve ficar em último lugar e servir a todos.

[[v41-9-36]]

^<<v41-9-36,36>>^ Aí segurou uma criança e a pôs no meio deles. E, abraçando-a, disse aos discípulos:

[[v41-9-37]]

^<<v41-9-37,37>>^ — Aquele que, por ser meu seguidor, receber uma criança como esta estará também me recebendo. E quem me receber não recebe somente a mim, mas também aquele que me enviou.

[[v41-9-38]]

^<<v41-9-38,38>>^ João disse: — Mestre, vimos um homem que expulsa demônios pelo poder do nome do senhor, mas nós o proibimos de fazer isso porque ele não é do nosso grupo.

[[v41-9-39]]

^<<v41-9-39,39>>^ Jesus respondeu: — Não o proíbam, pois não há ninguém que faça milagres pelo poder do meu nome e logo depois seja capaz de falar mal de mim.

[[v41-9-40]]

^<<v41-9-40,40>>^ Porque quem não é contra nós é por nós.

[[v41-9-41]]

^<<v41-9-41,41>>^ Eu afirmo a vocês que isto é verdade: quem der um copo de água a vocês, porque vocês são de Cristo, com toda a certeza receberá a sua recompensa.

[[v41-9-42]]

^<<v41-9-42,42>>^ Jesus continuou: — Quanto a estes pequeninos que creem em mim , se alguém for culpado de um deles me abandonar, seria melhor para essa pessoa que ela fosse jogada no mar, com uma pedra grande amarrada no pescoço.

[[v41-9-43]]

^<<v41-9-43,43>>^ Se uma das suas mãos faz com que você peque, corte-a fora! Pois é melhor você entrar na vida eterna com uma só mão do que ter as duas e ir para o inferno, onde o fogo nunca se apaga.

[[v41-9-44]]

^<<v41-9-44,44>>^ [Ali os vermes que devoram não morrem, e o fogo nunca se apaga.]

[[v41-9-45]]

^<<v41-9-45,45>>^ Se um dos seus pés faz com que você peque, corte-o fora! Pois é melhor você entrar na vida eterna aleijado do que ter os dois pés e ser jogado no inferno.

[[v41-9-46]]

^<<v41-9-46,46>>^ [Ali os vermes que devoram não morrem, e o fogo nunca se apaga.]

[[v41-9-47]]

^<<v41-9-47,47>>^ Se um dos seus olhos faz com que você peque, arranque-o! Pois é melhor você entrar no Reino de Deus  com um olho só do que ter os dois e ser jogado no inferno.

[[v41-9-48]]

^<<v41-9-48,48>>^ Ali os vermes que devoram não morrem, e o fogo nunca se apaga.

[[v41-9-49]]

^<<v41-9-49,49>>^ — Pois todas as pessoas serão purificadas  pelo fogo, assim como os sacrifícios  são purificados pelo sal.

[[v41-9-50]]

^<<v41-9-50,50>>^ O sal é uma coisa útil; mas, se perder o gosto, como é que vocês poderão lhe dar gosto de novo? Tenham sal em vocês mesmos e vivam em paz uns com os outros.

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]