include::./index.adoc[]

[[v41-10-0]]
=== Marcos, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-10-1]]

^<<v41-10-1,1>>^ Jesus saiu daquele lugar e foi para a região da Judeia que fica no lado leste do rio Jordão. Uma grande multidão se ajuntou outra vez em volta dele, e ele ensinava todos, como era o seu costume.

[[v41-10-2]]

^<<v41-10-2,2>>^ Alguns fariseus , querendo conseguir uma prova contra ele, perguntaram: — De acordo com a nossa Lei , um homem pode mandar a sua esposa embora?

[[v41-10-3]]

^<<v41-10-3,3>>^ Jesus respondeu com esta pergunta: — O que foi que Moisés mandou?

[[v41-10-4]]

^<<v41-10-4,4>>^ Eles responderam: — Moisés permitiu ao homem dar à sua esposa um documento de divórcio e mandá-la embora.

[[v41-10-5]]

^<<v41-10-5,5>>^ Então Jesus disse: — Moisés escreveu esse mandamento para vocês por causa da dureza do coração de vocês.

[[v41-10-6]]

^<<v41-10-6,6>>^ Mas no começo, quando foram criadas todas as coisas, foi dito: "Deus os fez homem e mulher.

[[v41-10-7]]

^<<v41-10-7,7>>^ Por isso o homem deixa o seu pai e a sua mãe para se unir com a sua mulher,

[[v41-10-8]]

^<<v41-10-8,8>>^ e os dois se tornam uma só pessoa." Assim, já não são duas pessoas, mas uma só.

[[v41-10-9]]

^<<v41-10-9,9>>^ Portanto, que ninguém separe o que Deus uniu.

[[v41-10-10]]

^<<v41-10-10,10>>^ Quando já estavam em casa, os discípulos tornaram a fazer perguntas sobre esse assunto.

[[v41-10-11]]

^<<v41-10-11,11>>^ E Jesus respondeu: — O homem que mandar a sua esposa embora e casar com outra mulher estará cometendo adultério contra a sua esposa.

[[v41-10-12]]

^<<v41-10-12,12>>^ E, se a mulher mandar o seu marido embora e casar com outro homem, ela também estará cometendo adultério.

[[v41-10-13]]

^<<v41-10-13,13>>^ Depois disso, algumas pessoas levaram as suas crianças a Jesus para que ele as abençoasse, mas os discípulos repreenderam aquelas pessoas.

[[v41-10-14]]

^<<v41-10-14,14>>^ Quando viu isso, Jesus não gostou e disse: — Deixem que as crianças venham a mim e não proíbam que elas façam isso, pois o Reino de Deus  é das pessoas que são como estas crianças.

[[v41-10-15]]

^<<v41-10-15,15>>^ Eu afirmo a vocês que isto é verdade: quem não receber o Reino de Deus como uma criança nunca entrará nele.

[[v41-10-16]]

^<<v41-10-16,16>>^ Então Jesus abraçou as crianças e as abençoou, pondo as mãos sobre elas.

[[v41-10-17]]

^<<v41-10-17,17>>^ Quando Jesus estava saindo de viagem, um homem veio correndo, ajoelhou-se na frente dele e perguntou: — Bom Mestre, o que devo fazer para conseguir a vida eterna?

[[v41-10-18]]

^<<v41-10-18,18>>^ Jesus respondeu: — Por que você me chama de bom? Só Deus é bom, e mais ninguém.

[[v41-10-19]]

^<<v41-10-19,19>>^ Você conhece os mandamentos: "Não mate, não cometa adultério, não roube, não dê falso testemunho contra ninguém, não tire nada dos outros, respeite o seu pai e a sua mãe."

[[v41-10-20]]

^<<v41-10-20,20>>^ — Mestre, desde criança eu tenho obedecido a todos esses mandamentos! — respondeu o homem.

[[v41-10-21]]

^<<v41-10-21,21>>^ Jesus olhou para ele com amor e disse: — Falta mais uma coisa para você fazer: vá, venda tudo o que tem e dê o dinheiro aos pobres e assim você terá riquezas no céu. Depois venha e me siga.

[[v41-10-22]]

^<<v41-10-22,22>>^ Quando o homem ouviu isso, fechou a cara; e, porque era muito rico, foi embora triste.

[[v41-10-23]]

^<<v41-10-23,23>>^ Jesus então olhou para os seus discípulos, que estavam em volta dele, e disse: — Como é difícil os ricos entrarem no Reino de Deus !

[[v41-10-24]]

^<<v41-10-24,24>>^ Quando ouviram isso, os discípulos ficaram espantados, mas Jesus continuou: — Meus filhos, como é difícil entrar no Reino de Deus!

[[v41-10-25]]

^<<v41-10-25,25>>^ É mais difícil um rico entrar no Reino de Deus do que um camelo passar pelo fundo de uma agulha.

[[v41-10-26]]

^<<v41-10-26,26>>^ Quando ouviram isso, os discípulos ficaram espantadíssimos e perguntavam uns aos outros: — Então, quem é que pode se salvar?

[[v41-10-27]]

^<<v41-10-27,27>>^ Jesus olhou para eles e disse: — Para os seres humanos isso não é possível; mas, para Deus, é. Pois, para Deus, tudo é possível.

[[v41-10-28]]

^<<v41-10-28,28>>^ Aí Pedro disse: — Veja! Nós deixamos tudo e seguimos o senhor.

[[v41-10-29]]

^<<v41-10-29,29>>^ Jesus respondeu: — Eu afirmo a vocês que isto é verdade: aquele que, por causa de mim e do evangelho , deixar casa, irmãos, irmãs, mãe, pai, filhos ou terras

[[v41-10-30]]

^<<v41-10-30,30>>^ receberá muito mais, ainda nesta vida. Receberá cem vezes mais casas, irmãos, irmãs, mães, filhos, terras e também perseguições. E no futuro receberá a vida eterna.

[[v41-10-31]]

^<<v41-10-31,31>>^ Muitos que agora são os primeiros serão os últimos, e muitos que agora são os últimos serão os primeiros.

[[v41-10-32]]

^<<v41-10-32,32>>^ Jesus e os discípulos iam pela estrada, subindo para Jerusalém. Ele caminhava na frente, e os discípulos, espantados, iam atrás dele; as outras pessoas que iam com eles estavam com medo. Então Jesus chamou outra vez os discípulos para um lado e começou a falar sobre o que ia acontecer com ele. Jesus disse:

[[v41-10-33]]

^<<v41-10-33,33>>^ — Escutem! Nós estamos indo para Jerusalém, onde o Filho do Homem  será entregue aos chefes dos sacerdotes e aos mestres  da Lei. Eles o condenarão à morte e o entregarão aos não judeus.

[[v41-10-34]]

^<<v41-10-34,34>>^ Estes vão zombar dele, cuspir nele, bater nele e matá-lo; mas três dias depois ele ressuscitará.

[[v41-10-35]]

^<<v41-10-35,35>>^ Depois Tiago e João, filhos de Zebedeu, chegaram perto de Jesus e disseram: — Mestre, queremos lhe pedir um favor.

[[v41-10-36]]

^<<v41-10-36,36>>^ — O que vocês querem que eu faça para vocês?  — perguntou Jesus.

[[v41-10-37]]

^<<v41-10-37,37>>^ Eles responderam: — Quando o senhor sentar-se no trono do seu Reino glorioso , deixe que um de nós se sente à sua direita, e o outro, à sua esquerda.

[[v41-10-38]]

^<<v41-10-38,38>>^ Jesus respondeu: — Vocês não sabem o que estão pedindo. Por acaso vocês podem beber o cálice que eu vou beber e podem ser batizados como eu vou ser batizado?

[[v41-10-39]]

^<<v41-10-39,39>>^ Eles disseram: — Podemos. Então Jesus disse: — De fato, vocês beberão o cálice que eu vou beber e receberão o batismo com que vou ser batizado.

[[v41-10-40]]

^<<v41-10-40,40>>^ Mas eu não tenho o direito de escolher quem vai sentar à minha direita e à minha esquerda. Pois foi Deus quem preparou esses lugares e ele os dará a quem quiser.

[[v41-10-41]]

^<<v41-10-41,41>>^ Quando os outros dez discípulos ouviram isso, começaram a ficar zangados com Tiago e João.

[[v41-10-42]]

^<<v41-10-42,42>>^ Então Jesus chamou todos para perto de si e disse: — Como vocês sabem, os governadores dos povos pagãos têm autoridade sobre eles e mandam neles.

[[v41-10-43]]

^<<v41-10-43,43>>^ Mas entre vocês não pode ser assim. Pelo contrário, quem quiser ser importante, que sirva os outros,

[[v41-10-44]]

^<<v41-10-44,44>>^ e quem quiser ser o primeiro, que seja o escravo de todos.

[[v41-10-45]]

^<<v41-10-45,45>>^ Porque até o Filho do Homem  não veio para ser servido, mas para servir e dar a sua vida para salvar muita gente.

[[v41-10-46]]

^<<v41-10-46,46>>^ Jesus e os discípulos chegaram à cidade de Jericó. Quando ele estava saindo da cidade, com os discípulos e uma grande multidão, encontrou um cego chamado Bartimeu, filho de Timeu. O cego estava sentado na beira do caminho, pedindo esmola.

[[v41-10-47]]

^<<v41-10-47,47>>^ Quando ouviu alguém dizer que era Jesus de Nazaré que estava passando, o cego começou a gritar: — Jesus, Filho de Davi , tenha pena de mim!

[[v41-10-48]]

^<<v41-10-48,48>>^ Muitas pessoas o repreenderam e mandaram que ele calasse a boca, mas ele gritava ainda mais: — Filho de Davi, tenha pena de mim!

[[v41-10-49]]

^<<v41-10-49,49>>^ Então Jesus parou e disse: — Chamem o cego. Eles chamaram e lhe disseram: — Coragem! Levante-se porque ele está chamando você!

[[v41-10-50]]

^<<v41-10-50,50>>^ Então Bartimeu jogou a sua capa  para um lado, levantou-se depressa e foi até o lugar onde Jesus estava.

[[v41-10-51]]

^<<v41-10-51,51>>^ — O que é que você quer que eu faça?  — perguntou Jesus. — Mestre, eu quero ver de novo! — respondeu ele.

[[v41-10-52]]

^<<v41-10-52,52>>^ — Vá; você está curado porque teve fé!  — afirmou Jesus. No mesmo instante, Bartimeu começou a ver de novo e foi seguindo Jesus pelo caminho.

'''

xref:041-marcos/041-marcos-009.adoc#v41-9-0[&#60; Capítulo Anterior] | <<v41-10-0,Topo>> | xref:041-marcos/041-marcos-011.adoc#v41-11-0[Próximo Capítulo &#62;]