include::./index.adoc[]

[[v41-14-0]]
=== Marcos, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-14-1]]

^<<v41-14-1,1>>^ Faltavam dois dias para a Festa da Páscoa  e a Festa dos Pães sem Fermento . Os chefes dos sacerdotes e os mestres  da Lei procuravam um jeito de prender Jesus em segredo e matá-lo.

[[v41-14-2]]

^<<v41-14-2,2>>^ Eles diziam: — Não vamos fazer isso durante a festa, para não haver uma revolta no meio do povo.

[[v41-14-3]]

^<<v41-14-3,3>>^ Jesus estava no povoado de Betânia, sentado à mesa na casa de Simão, o Leproso. Então uma mulher chegou com um frasco feito de alabastro , cheio de perfume de nardo  puro, muito caro. Ela quebrou o gargalo do frasco e derramou o perfume na cabeça de Jesus.

[[v41-14-4]]

^<<v41-14-4,4>>^ Alguns que estavam ali ficaram zangados e disseram uns aos outros: — Que desperdício!

[[v41-14-5]]

^<<v41-14-5,5>>^ Esse perfume poderia ter sido vendido por mais de trezentas moedas de prata , que poderiam ser dadas aos pobres. Eles criticavam a mulher com dureza,

[[v41-14-6]]

^<<v41-14-6,6>>^ mas Jesus disse: — Deixem esta mulher em paz! Por que é que vocês a estão aborrecendo? Ela fez para mim uma coisa muito boa.

[[v41-14-7]]

^<<v41-14-7,7>>^ Pois os pobres estarão sempre com vocês, e, em qualquer ocasião que vocês quiserem, poderão ajudá-los. Mas eu não estarei sempre com vocês.

[[v41-14-8]]

^<<v41-14-8,8>>^ Ela fez tudo o que pôde, pois antes da minha morte veio perfumar o meu corpo para o meu sepultamento.

[[v41-14-9]]

^<<v41-14-9,9>>^ Eu afirmo a vocês que isto é verdade: em qualquer lugar do mundo onde o evangelho  for anunciado, será contado o que ela fez, e ela será lembrada.

[[v41-14-10]]

^<<v41-14-10,10>>^ Judas Iscariotes, que era um dos doze discípulos, foi falar com os chefes dos sacerdotes para combinar como entregaria Jesus a eles.

[[v41-14-11]]

^<<v41-14-11,11>>^ Quando ouviram o que ele disse, eles ficaram muito contentes e prometeram dar dinheiro a ele. Assim Judas começou a procurar uma oportunidade para entregar Jesus.

[[v41-14-12]]

^<<v41-14-12,12>>^ No primeiro dia da Festa dos Pães sem Fermento , em que os judeus matavam carneirinhos para comemorarem a Páscoa , os discípulos perguntaram a Jesus: — Onde é que o senhor quer que a gente prepare o jantar da Páscoa para o senhor?

[[v41-14-13]]

^<<v41-14-13,13>>^ Então Jesus enviou dois discípulos com a seguinte ordem: — Vão até a cidade. Lá irá se encontrar com vocês um homem que estará carregando um pote de água. Vão atrás desse homem

[[v41-14-14]]

^<<v41-14-14,14>>^ e digam ao dono da casa em que ele entrar que o Mestre manda perguntar: "Onde fica a sala em que eu e os meus discípulos vamos comer o jantar da Páscoa?"

[[v41-14-15]]

^<<v41-14-15,15>>^ Então ele mostrará a vocês no andar de cima uma sala grande, mobiliada e arrumada para o jantar. Preparem ali tudo para nós.

[[v41-14-16]]

^<<v41-14-16,16>>^ Os dois discípulos foram até a cidade e encontraram tudo como Jesus tinha dito. Então prepararam o jantar da Páscoa.

[[v41-14-17]]

^<<v41-14-17,17>>^ Quando anoiteceu, Jesus chegou com os doze discípulos.

[[v41-14-18]]

^<<v41-14-18,18>>^ Enquanto estavam à mesa, no meio do jantar, ele disse: — Eu afirmo a vocês que isto é verdade: um de vocês, que está comendo comigo, vai me trair.

[[v41-14-19]]

^<<v41-14-19,19>>^ Eles ficaram tristes e, um por um, começaram a perguntar: — O senhor não está achando que sou eu, está?

[[v41-14-20]]

^<<v41-14-20,20>>^ Jesus respondeu: — É um de vocês. É o que está comendo no mesmo prato que eu.

[[v41-14-21]]

^<<v41-14-21,21>>^ Pois o Filho do Homem  vai morrer da maneira como dizem as Escrituras Sagradas ; mas ai daquele que está traindo o Filho do Homem! Seria melhor para ele nunca ter nascido!

[[v41-14-22]]

^<<v41-14-22,22>>^ Enquanto estavam comendo, Jesus pegou o pão e deu graças a Deus. Depois partiu o pão e o deu aos discípulos, dizendo: — Peguem; isto é o meu corpo.

[[v41-14-23]]

^<<v41-14-23,23>>^ Em seguida, pegou o cálice de vinho e agradeceu a Deus. Depois passou o cálice aos discípulos, e todos beberam do vinho.

[[v41-14-24]]

^<<v41-14-24,24>>^ Então Jesus disse: — Isto é o meu sangue, que é derramado em favor de muitos, o sangue que garante a aliança  feita por Deus com o seu povo.

[[v41-14-25]]

^<<v41-14-25,25>>^ Eu afirmo a vocês que isto é verdade: nunca mais beberei deste vinho até o dia em que beber com vocês um vinho novo no Reino de Deus .

[[v41-14-26]]

^<<v41-14-26,26>>^ Então eles cantaram canções de louvor e foram para o monte das Oliveiras.

[[v41-14-27]]

^<<v41-14-27,27>>^ E Jesus disse aos discípulos: — Todos vocês vão fugir e me abandonar, pois as Escrituras Sagradas  dizem: "Matarei o pastor, e as ovelhas serão espalhadas."

[[v41-14-28]]

^<<v41-14-28,28>>^ Mas, depois que eu for ressuscitado, irei adiante de vocês para a Galileia.

[[v41-14-29]]

^<<v41-14-29,29>>^ Então Pedro disse a Jesus: — Eu nunca abandonarei o senhor, mesmo que todos o abandonem!

[[v41-14-30]]

^<<v41-14-30,30>>^ Mas Jesus lhe disse: — Eu afirmo a você que isto é verdade: nesta mesma noite, antes que o galo cante duas vezes, você dirá três vezes que não me conhece.

[[v41-14-31]]

^<<v41-14-31,31>>^ Mas Pedro repetia com insistência: — Eu nunca vou dizer que não o conheço, mesmo que eu tenha de morrer com o senhor! E todos os outros discípulos disseram a mesma coisa.

[[v41-14-32]]

^<<v41-14-32,32>>^ Jesus e os discípulos foram a um lugar chamado Getsêmani. E Jesus lhes disse: — Sentem-se aqui, enquanto eu vou orar.

[[v41-14-33]]

^<<v41-14-33,33>>^ Então Jesus foi, levando consigo Pedro, Tiago e João. Aí ele começou a sentir uma grande tristeza e aflição

[[v41-14-34]]

^<<v41-14-34,34>>^ e disse a eles: — A tristeza que estou sentindo é tão grande, que é capaz de me matar. Fiquem aqui vigiando.

[[v41-14-35]]

^<<v41-14-35,35>>^ Ele foi um pouco mais adiante, ajoelhou-se, encostou o rosto no chão e pediu a Deus que, se possível, afastasse dele aquela hora de sofrimento.

[[v41-14-36]]

^<<v41-14-36,36>>^ Ele orava assim: — Pai, meu Pai, tu podes fazer todas as coisas! Afasta de mim este cálice de sofrimento. Porém que não seja feito o que eu quero, mas o que tu queres.

[[v41-14-37]]

^<<v41-14-37,37>>^ Depois voltou e encontrou os três discípulos dormindo. Então disse a Pedro: — Simão, você está dormindo? Será que não pode vigiar nem uma hora?

[[v41-14-38]]

^<<v41-14-38,38>>^ Vigiem e orem para que não sejam tentados. É fácil querer resistir à tentação; o difícil mesmo é conseguir.

[[v41-14-39]]

^<<v41-14-39,39>>^ Jesus foi outra vez e orou, dizendo as mesmas palavras.

[[v41-14-40]]

^<<v41-14-40,40>>^ Em seguida, voltou ao lugar onde os discípulos estavam e os encontrou de novo dormindo. Eles estavam com muito sono e não conseguiam ficar com os olhos abertos. E não sabiam o que responder a Jesus.

[[v41-14-41]]

^<<v41-14-41,41>>^ Quando voltou pela terceira vez, Jesus perguntou: — Vocês ainda estão dormindo e descansando? Basta! Chegou a hora, e o Filho do Homem  está sendo entregue nas mãos dos maus.

[[v41-14-42]]

^<<v41-14-42,42>>^ Levantem-se, e vamos embora. Vejam! Aí vem chegando o homem que está me traindo!

[[v41-14-43]]

^<<v41-14-43,43>>^ Jesus ainda estava falando, quando chegou Judas, um dos doze discípulos. Vinha com ele uma multidão armada com espadas e porretes, que tinha sido mandada pelos chefes dos sacerdotes, pelos mestres  da Lei e pelos líderes judeus.

[[v41-14-44]]

^<<v41-14-44,44>>^ O traidor tinha combinado com eles um sinal. Ele tinha dito: "Prendam e levem bem seguro o homem que eu beijar, pois é ele."

[[v41-14-45]]

^<<v41-14-45,45>>^ Logo que chegou perto de Jesus, Judas disse: — Mestre! E o beijou.

[[v41-14-46]]

^<<v41-14-46,46>>^ Então eles pegaram Jesus e o prenderam.

[[v41-14-47]]

^<<v41-14-47,47>>^ Mas um dos que estavam ali tirou a espada, atacou um empregado do Grande Sacerdote  e cortou uma orelha dele.

[[v41-14-48]]

^<<v41-14-48,48>>^ Então Jesus disse para aquela gente: — Vocês vêm com espadas e porretes para me prenderem como se eu fosse um bandido?

[[v41-14-49]]

^<<v41-14-49,49>>^ Eu estava com vocês todos os dias, ensinando no pátio do Templo, e vocês não me prenderam. Mas isso está acontecendo para se cumprir o que as Escrituras Sagradas  dizem.

[[v41-14-50]]

^<<v41-14-50,50>>^ Então todos os discípulos abandonaram Jesus e fugiram.

[[v41-14-51]]

^<<v41-14-51,51>>^ Um jovem, enrolado num lençol, seguia Jesus. Alguns tentaram prendê-lo,

[[v41-14-52]]

^<<v41-14-52,52>>^ mas ele largou o lençol e fugiu nu.

[[v41-14-53]]

^<<v41-14-53,53>>^ Em seguida, levaram Jesus até a casa do Grande Sacerdote , onde estavam reunidos os chefes dos sacerdotes, alguns líderes dos judeus e alguns mestres  da Lei.

[[v41-14-54]]

^<<v41-14-54,54>>^ Pedro seguiu Jesus de longe e entrou no pátio da casa do Grande Sacerdote. Ele sentou-se perto do fogo, com os guardas, para se esquentar.

[[v41-14-55]]

^<<v41-14-55,55>>^ Os chefes dos sacerdotes e todo o Conselho Superior  estavam procurando encontrar alguma acusação contra Jesus a fim de o condenarem à morte. Mas não conseguiram nenhuma.

[[v41-14-56]]

^<<v41-14-56,56>>^ Muitos diziam mentiras contra ele, mas as suas histórias não combinavam umas com as outras.

[[v41-14-57]]

^<<v41-14-57,57>>^ Alguns se levantaram e acusaram Jesus com mentiras. Eles diziam:

[[v41-14-58]]

^<<v41-14-58,58>>^ — Nós ouvimos quando ele disse: "Vou destruir este Templo que foi construído por seres humanos e, em três dias, levantarei outro que não será construído por seres humanos."

[[v41-14-59]]

^<<v41-14-59,59>>^ Mesmo assim as suas histórias não combinavam umas com as outras.

[[v41-14-60]]

^<<v41-14-60,60>>^ Aí o Grande Sacerdote se levantou no meio de todos e perguntou a Jesus: — Você não vai se defender dessa acusação?

[[v41-14-61]]

^<<v41-14-61,61>>^ Mas Jesus ficou calado e não respondeu nada. Então o Grande Sacerdote tornou a perguntar: — Você é o Messias , o Filho do Deus Bendito?

[[v41-14-62]]

^<<v41-14-62,62>>^ Jesus respondeu: — Sou. E vocês verão o Filho do Homem  sentado do lado direito do Deus Todo-Poderoso e descendo com as nuvens do céu!

[[v41-14-63]]

^<<v41-14-63,63>>^ Aí o Grande Sacerdote rasgou as suas próprias roupas e disse: — Não precisamos mais de testemunhas!

[[v41-14-64]]

^<<v41-14-64,64>>^ Vocês ouviram esta blasfêmia  contra Deus! Então, o que resolvem? Todos estavam contra Jesus e aí o condenaram à morte.

[[v41-14-65]]

^<<v41-14-65,65>>^ Então alguns começaram a cuspir nele. Cobriam o rosto dele, davam bofetadas nele e perguntavam: — Quem foi que bateu em você? Adivinhe! E também os guardas o pegaram e lhe deram bofetadas.

[[v41-14-66]]

^<<v41-14-66,66>>^ Pedro ainda estava lá embaixo no pátio, quando apareceu uma das empregadas do Grande Sacerdote .

[[v41-14-67]]

^<<v41-14-67,67>>^ Ela viu Pedro se esquentando perto do fogo, olhou bem para ele e disse: — Você também estava com Jesus de Nazaré.

[[v41-14-68]]

^<<v41-14-68,68>>^ Mas ele negou, dizendo: — Eu não o conheço. Não sei do que é que você está falando. E saiu para o corredor. Naquele momento, o galo cantou.

[[v41-14-69]]

^<<v41-14-69,69>>^ Quando a empregada viu Pedro ali, começou a dizer aos que estavam perto: — Este homem é um deles.

[[v41-14-70]]

^<<v41-14-70,70>>^ Mas ele negou outra vez. Pouco depois, as pessoas que estavam ali disseram de novo a Pedro: — Não há dúvida de que você é um deles, pois você também é da Galileia.

[[v41-14-71]]

^<<v41-14-71,71>>^ Aí Pedro disse: — Juro que não conheço esse homem de quem vocês estão falando! Que Deus me castigue se não estou dizendo a verdade!

[[v41-14-72]]

^<<v41-14-72,72>>^ Naquele instante o galo cantou pela segunda vez, e Pedro lembrou que Jesus lhe tinha dito: "Antes que o galo cante duas vezes, você dirá três vezes que não me conhece." Então Pedro caiu em si e começou a chorar.

'''

xref:041-marcos/041-marcos-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-marcos/041-marcos-015.adoc#v41-15-0[Próximo Capítulo &#62;]