include::./index.adoc[]

[[v41-15-0]]
=== Marcos, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-15-1]]

^<<v41-15-1,1>>^ Assim que amanheceu, os chefes dos sacerdotes se reuniram com os líderes dos judeus, e com os mestres  da Lei, e com todo o Conselho Superior  e fizeram os seus planos. Eles amarraram Jesus, e o levaram, e entregaram a Pilatos.

[[v41-15-2]]

^<<v41-15-2,2>>^ Pilatos perguntou: — Você é o rei dos judeus? — Quem está dizendo isso é o senhor!  — respondeu Jesus.

[[v41-15-3]]

^<<v41-15-3,3>>^ E os chefes dos sacerdotes faziam muitas acusações contra ele.

[[v41-15-4]]

^<<v41-15-4,4>>^ Então Pilatos fez outra pergunta: — Você não vai responder? Veja quantas acusações estão fazendo contra você!

[[v41-15-5]]

^<<v41-15-5,5>>^ Porém Jesus não disse mais nada, e Pilatos ficou muito admirado com isso.

[[v41-15-6]]

^<<v41-15-6,6>>^ Em toda Festa da Páscoa , o Governador costumava soltar um dos presos, a pedido do povo.

[[v41-15-7]]

^<<v41-15-7,7>>^ Naquela ocasião um homem chamado Barrabás estava preso na cadeia junto com alguns homens que tinham matado algumas pessoas numa revolta.

[[v41-15-8]]

^<<v41-15-8,8>>^ A multidão veio e começou a pedir que, como era o costume, Pilatos soltasse um preso.

[[v41-15-9]]

^<<v41-15-9,9>>^ Então ele perguntou: — Vocês querem que eu solte para vocês o rei dos judeus?

[[v41-15-10]]

^<<v41-15-10,10>>^ Ele sabia muito bem que os chefes dos sacerdotes tinham inveja de Jesus e que era por isso que o haviam entregado a ele.

[[v41-15-11]]

^<<v41-15-11,11>>^ Mas os chefes dos sacerdotes atiçaram o povo para que pedisse a Pilatos que, em vez de soltar Jesus, ele soltasse Barrabás.

[[v41-15-12]]

^<<v41-15-12,12>>^ Pilatos falou outra vez com o povo. Ele perguntou: — O que vocês querem que eu faça com este homem que vocês chamam de rei dos judeus?

[[v41-15-13]]

^<<v41-15-13,13>>^ E eles gritaram: — Crucifica!

[[v41-15-14]]

^<<v41-15-14,14>>^ — Que crime ele cometeu? — perguntou Pilatos. Mas eles gritaram ainda mais alto: — Crucifica! Crucifica!

[[v41-15-15]]

^<<v41-15-15,15>>^ Então Pilatos, querendo agradar o povo, soltou Barrabás, como eles haviam pedido. Depois mandou chicotear Jesus e o entregou para ser crucificado.

[[v41-15-16]]

^<<v41-15-16,16>>^ Aí os soldados levaram Jesus para o pátio interno do Palácio do Governador e reuniram toda a tropa.

[[v41-15-17]]

^<<v41-15-17,17>>^ Depois vestiram em Jesus uma capa  vermelha e puseram na cabeça dele uma coroa feita de ramos cheios de espinhos.

[[v41-15-18]]

^<<v41-15-18,18>>^ E começaram a saudá-lo, dizendo: — Viva o Rei dos Judeus!

[[v41-15-19]]

^<<v41-15-19,19>>^ Batiam na cabeça dele com um bastão, cuspiam nele e se ajoelhavam, fingindo que o estavam adorando.

[[v41-15-20]]

^<<v41-15-20,20>>^ Depois de terem caçoado dele, tiraram a capa vermelha e o vestiram com as suas próprias roupas. Em seguida o levaram para fora a fim de o crucificarem.

[[v41-15-21]]

^<<v41-15-21,21>>^ No caminho, os soldados encontraram um homem chamado Simão, que vinha do campo para a cidade. Esse Simão, o pai de Alexandre e Rufo, era da cidade de Cirene. Os soldados obrigaram Simão a carregar a cruz de Jesus

[[v41-15-22]]

^<<v41-15-22,22>>^ e levaram Jesus para um lugar chamado Gólgota. (Gólgota quer dizer "Lugar da Caveira".)

[[v41-15-23]]

^<<v41-15-23,23>>^ Queriam dar a ele vinho misturado com um calmante chamado mirra , mas ele não bebeu.

[[v41-15-24]]

^<<v41-15-24,24>>^ Em seguida os soldados o crucificaram e repartiram as suas roupas entre si, tirando a sorte com dados, para ver qual seria a parte de cada um.

[[v41-15-25]]

^<<v41-15-25,25>>^ Eram nove horas da manhã quando crucificaram Jesus.

[[v41-15-26]]

^<<v41-15-26,26>>^ Puseram em cima da cruz uma tabuleta onde estava escrito como acusação contra ele: "O Rei dos Judeus".

[[v41-15-27]]

^<<v41-15-27,27>>^ Com Jesus, crucificaram também dois ladrões: um à sua direita e o outro à sua esquerda.

[[v41-15-28]]

^<<v41-15-28,28>>^ [Assim se cumpriu o que as Escrituras Sagradas  dizem: "Ele foi tratado como se fosse um criminoso."]

[[v41-15-29]]

^<<v41-15-29,29>>^ Os que passavam por ali caçoavam dele, balançavam a cabeça e o insultavam assim: — Ei, você que disse que era capaz de destruir o Templo e tornar a construí-lo em três dias!

[[v41-15-30]]

^<<v41-15-30,30>>^ Pois desça da cruz e salve-se a si mesmo!

[[v41-15-31]]

^<<v41-15-31,31>>^ Os chefes dos sacerdotes e os mestres  da Lei também caçoavam dele, dizendo: — Ele salvou os outros, mas não pode salvar a si mesmo!

[[v41-15-32]]

^<<v41-15-32,32>>^ Vamos ver o Messias , o Rei de Israel, descer agora da cruz e então creremos nele! E os ladrões que foram crucificados com Jesus também o insultavam.

[[v41-15-33]]

^<<v41-15-33,33>>^ Ao meio-dia começou a escurecer, e toda a terra ficou três horas na escuridão.

[[v41-15-34]]

^<<v41-15-34,34>>^ Às três horas da tarde Jesus gritou bem alto: — "Eloí, Eloí, lemá sabactani?"  Essas palavras querem dizer: "Meu Deus, meu Deus, por que me abandonaste?"

[[v41-15-35]]

^<<v41-15-35,35>>^ Algumas pessoas que estavam ali ouviram isso e disseram: — Escutem! Ele está chamando Elias!

[[v41-15-36]]

^<<v41-15-36,36>>^ Alguém correu e molhou uma esponja em vinho comum, pôs na ponta de um bastão, deu para Jesus beber e disse: — Esperem! Vamos ver se Elias vem tirá-lo da cruz!

[[v41-15-37]]

^<<v41-15-37,37>>^ Aí Jesus deu um grito forte e morreu.

[[v41-15-38]]

^<<v41-15-38,38>>^ Então a cortina do Templo se rasgou em dois pedaços, de cima até embaixo.

[[v41-15-39]]

^<<v41-15-39,39>>^ O oficial do exército romano que estava em frente da cruz, vendo Jesus morrer daquele modo, disse: — De fato, este homem era o Filho de Deus!

[[v41-15-40]]

^<<v41-15-40,40>>^ Algumas mulheres também estavam ali, olhando de longe. Entre elas estavam Maria Madalena, Salomé e Maria, que era mãe de José e de Tiago, o mais moço.

[[v41-15-41]]

^<<v41-15-41,41>>^ Essas mulheres tinham acompanhado e ajudado Jesus quando ele estava na Galileia. Além dessas, estavam ali muitas outras mulheres que tinham ido com ele para Jerusalém.

[[v41-15-42]]

^<<v41-15-42,42>>^ Já era quase noite quando chegou José, que era da cidade de Arimateia. Ele era um homem importante e fazia parte do Conselho Superior . José também esperava a vinda do Reino de Deus . Era o Dia da Preparação , isto é, a véspera do sábado. Por isso José, tomando coragem, foi falar com Pilatos e pediu o corpo de Jesus.

[[v41-15-43]]

^<<v41-15-43,43>>^ Já era quase noite quando chegou José, que era da cidade de Arimateia. Ele era um homem importante e fazia parte do Conselho Superior . José também esperava a vinda do Reino de Deus . Era o Dia da Preparação , isto é, a véspera do sábado. Por isso José, tomando coragem, foi falar com Pilatos e pediu o corpo de Jesus.

[[v41-15-44]]

^<<v41-15-44,44>>^ Pilatos ficou admirado quando soube que Jesus já estava morto. Chamou o oficial romano e perguntou se fazia muito tempo que Jesus tinha morrido.

[[v41-15-45]]

^<<v41-15-45,45>>^ Depois de receber a informação do oficial, Pilatos entregou a José o corpo de Jesus.

[[v41-15-46]]

^<<v41-15-46,46>>^ José comprou um lençol de linho, tirou o corpo da cruz e o enrolou no lençol. Em seguida pôs o corpo num túmulo cavado na rocha e rolou uma grande pedra para fechar a entrada do túmulo.

'''

xref:041-marcos/041-marcos-014.adoc#v41-14-0[&#60; Capítulo Anterior] | <<v41-15-0,Topo>> | xref:041-marcos/041-marcos-016.adoc#v41-16-0[Próximo Capítulo &#62;]