include::./index.adoc[]

[[v41-5-0]]
=== Marcos, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-5-1]]

^<<v41-5-1,1>>^ Jesus e os discípulos chegaram à região de Gerasa, no lado leste do lago da Galileia.

[[v41-5-2]]

^<<v41-5-2,2>>^ Assim que Jesus saiu do barco, foi encontrar-se com ele um homem que estava dominado por um espírito mau.

[[v41-5-3]]

^<<v41-5-3,3>>^ O homem vinha do cemitério, onde estava morando. Ninguém conseguia prendê-lo, nem mesmo usando correntes.

[[v41-5-4]]

^<<v41-5-4,4>>^ Muitas vezes já tinham amarrado as suas mãos e os seus pés com correntes de ferro, mas ele quebrava tudo, e ninguém conseguia dominá-lo.

[[v41-5-5]]

^<<v41-5-5,5>>^ Passava os dias e as noites nos montes e entre os túmulos, gritando e se ferindo de propósito com pedras.

[[v41-5-6]]

^<<v41-5-6,6>>^ Ele viu Jesus de longe, correu, caiu de joelhos diante dele

[[v41-5-7]]

^<<v41-5-7,7>>^ e gritou: — Jesus, Filho do Deus Altíssimo! O que o senhor quer de mim? Em nome de Deus eu peço: não me castigue!

[[v41-5-8]]

^<<v41-5-8,8>>^ Ele disse isso porque Jesus havia mandado: "Espírito mau, saia desse homem!"

[[v41-5-9]]

^<<v41-5-9,9>>^ Jesus perguntou: — Como é que você se chama? Ele respondeu: — O meu nome é Multidão, porque somos muitos.

[[v41-5-10]]

^<<v41-5-10,10>>^ E pedia com muita insistência a Jesus que não expulsasse os espíritos maus para fora daquela região.

[[v41-5-11]]

^<<v41-5-11,11>>^ Acontece que num morro perto dali havia muitos porcos comendo.

[[v41-5-12]]

^<<v41-5-12,12>>^ Os espíritos pediram a Jesus com insistência: — Nos mande ficar naqueles porcos; nos deixe entrar neles!

[[v41-5-13]]

^<<v41-5-13,13>>^ Ele deixou, e os espíritos saíram do homem e entraram nos porcos. E estes, que eram quase dois mil, se atiraram morro abaixo, para dentro do lago, e se afogaram.

[[v41-5-14]]

^<<v41-5-14,14>>^ Os homens que estavam tomando conta dos porcos fugiram e espalharam a notícia na cidade e nos campos. Muita gente foi ver o que havia acontecido.

[[v41-5-15]]

^<<v41-5-15,15>>^ Quando chegaram perto de Jesus, viram o homem que antes estava dominado por demônios; e ficaram espantados porque ele estava sentado, vestido e no seu perfeito juízo.

[[v41-5-16]]

^<<v41-5-16,16>>^ Os que tinham visto tudo aquilo lhes contaram o que havia acontecido com o homem e com os porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ Então começaram a pedir com insistência a Jesus que saísse da terra deles.

[[v41-5-18]]

^<<v41-5-18,18>>^ Quando ele estava entrando no barco, o homem curado pediu com insistência: — Me deixe ir com o senhor!

[[v41-5-19]]

^<<v41-5-19,19>>^ Mas Jesus não deixou e disse: — Volte para casa e conte aos seus parentes o que o Senhor lhe fez e como ele foi bom para você.

[[v41-5-20]]

^<<v41-5-20,20>>^ Então ele foi embora e contava, na região das Dez Cidades , o que Jesus tinha feito por ele. E todos ficavam admirados.

[[v41-5-21]]

^<<v41-5-21,21>>^ Jesus voltou para o lado oeste do lago, e muitas pessoas foram se encontrar com ele na praia.

[[v41-5-22]]

^<<v41-5-22,22>>^ Um homem chamado Jairo, chefe da sinagoga , foi e se jogou aos pés de Jesus,

[[v41-5-23]]

^<<v41-5-23,23>>^ pedindo com muita insistência: — A minha filha está morrendo! Venha comigo e ponha as mãos sobre ela para que sare e viva!

[[v41-5-24]]

^<<v41-5-24,24>>^ E Jesus foi com ele. Uma grande multidão foi junto e o apertava de todos os lados.

[[v41-5-25]]

^<<v41-5-25,25>>^ Chegou ali uma mulher que fazia doze anos que estava com uma hemorragia.

[[v41-5-26]]

^<<v41-5-26,26>>^ Havia gastado tudo o que tinha, tratando-se com muitos médicos. Estes a fizeram sofrer muito; mas, em vez de melhorar, ela havia piorado cada vez mais.

[[v41-5-27]]

^<<v41-5-27,27>>^ Ela havia escutado falar de Jesus; então entrou no meio da multidão e, chegando por trás dele, tocou na sua capa ,

[[v41-5-28]]

^<<v41-5-28,28>>^ pois pensava assim: "Se eu apenas tocar na capa dele, ficarei curada."

[[v41-5-29]]

^<<v41-5-29,29>>^ Logo o sangue parou de escorrer, e ela teve certeza de que estava curada.

[[v41-5-30]]

^<<v41-5-30,30>>^ No mesmo instante Jesus sentiu que dele havia saído poder. Então virou-se no meio da multidão e perguntou: — Quem foi que tocou na minha capa?

[[v41-5-31]]

^<<v41-5-31,31>>^ Os discípulos responderam: — O senhor está vendo como esta gente o está apertando de todos os lados e ainda pergunta isso?

[[v41-5-32]]

^<<v41-5-32,32>>^ Mas Jesus ficou olhando em volta para ver quem tinha feito aquilo.

[[v41-5-33]]

^<<v41-5-33,33>>^ Então a mulher, sabendo o que lhe havia acontecido, atirou-se aos pés dele, tremendo de medo, e contou tudo.

[[v41-5-34]]

^<<v41-5-34,34>>^ E Jesus disse: — Minha filha, você sarou porque teve fé. Vá em paz; você está livre do seu sofrimento.

[[v41-5-35]]

^<<v41-5-35,35>>^ Jesus ainda estava falando, quando chegaram alguns empregados da casa de Jairo e disseram: — Seu Jairo, a menina já morreu. Não aborreça mais o Mestre.

[[v41-5-36]]

^<<v41-5-36,36>>^ Mas Jesus não se importou com a notícia e disse a Jairo: — Não tenha medo; tenha fé!

[[v41-5-37]]

^<<v41-5-37,37>>^ Jesus deixou que fossem com ele Pedro e os irmãos Tiago e João, e ninguém mais.

[[v41-5-38]]

^<<v41-5-38,38>>^ Quando entraram na casa de Jairo, Jesus encontrou ali uma confusão geral, com todos chorando alto e gritando.

[[v41-5-39]]

^<<v41-5-39,39>>^ Então ele disse: — Por que tanto choro e tanta confusão? A menina não morreu; ela está dormindo.

[[v41-5-40]]

^<<v41-5-40,40>>^ Então eles começaram a caçoar dele. Mas Jesus mandou que todos saíssem e, junto com os três discípulos e os pais da menina, entrou no quarto onde ela estava.

[[v41-5-41]]

^<<v41-5-41,41>>^ Pegou-a pela mão e disse: — "Talitá cumi!"  (Isto quer dizer: "Menina, eu digo a você: Levante-se! ")

[[v41-5-42]]

^<<v41-5-42,42>>^ No mesmo instante, a menina, que tinha doze anos, levantou-se e começou a andar. E todos ficaram muito admirados.

[[v41-5-43]]

^<<v41-5-43,43>>^ Então Jesus ordenou que de jeito nenhum espalhassem a notícia dessa cura. E mandou que dessem comida à menina.

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]