include::./index.adoc[]

[[v41-6-0]]
=== Marcos, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-6-1]]

^<<v41-6-1,1>>^ Jesus voltou com os seus discípulos para a cidade de Nazaré, onde ele tinha morado.

[[v41-6-2]]

^<<v41-6-2,2>>^ No sábado começou a ensinar na sinagoga . Muitos que o estavam escutando ficaram admirados e perguntaram: — De onde é que este homem consegue tudo isso? De onde vem a sabedoria dele? Como é que faz esses milagres?

[[v41-6-3]]

^<<v41-6-3,3>>^ Por acaso ele não é o carpinteiro, filho de Maria? Não é irmão de Tiago, José, Judas e Simão? As suas irmãs não moram aqui? Por isso ficaram desiludidos com ele.

[[v41-6-4]]

^<<v41-6-4,4>>^ Mas Jesus disse: — Um profeta  é respeitado em toda parte, menos na sua terra, entre os seus parentes e na sua própria casa.

[[v41-6-5]]

^<<v41-6-5,5>>^ Ele não pôde fazer milagres em Nazaré, a não ser curar alguns doentes, pondo as mãos sobre eles.

[[v41-6-6]]

^<<v41-6-6,6>>^ E ficou admirado com a falta de fé que havia ali. Jesus ensinava nos povoados que havia perto dali.

[[v41-6-7]]

^<<v41-6-7,7>>^ Ele chamou os doze discípulos e os enviou dois a dois, dando-lhes autoridade para expulsar espíritos maus.

[[v41-6-8]]

^<<v41-6-8,8>>^ Deu ordem para não levarem nada na viagem, somente uma bengala para se apoiar. Não deviam levar comida, nem sacola, nem dinheiro.

[[v41-6-9]]

^<<v41-6-9,9>>^ Deviam calçar sandálias e não levar nem uma túnica  a mais.

[[v41-6-10]]

^<<v41-6-10,10>>^ Disse ainda: — Quando vocês entrarem numa cidade, fiquem hospedados na casa em que forem recebidos até saírem daquela cidade.

[[v41-6-11]]

^<<v41-6-11,11>>^ Mas, se em algum lugar as pessoas não quiserem recebê-los, nem ouvi-los, vão embora. E na saída sacudam o pó das suas sandálias, como sinal de protesto contra aquela gente.

[[v41-6-12]]

^<<v41-6-12,12>>^ Então os discípulos foram e anunciaram que todos deviam se arrepender dos seus pecados.

[[v41-6-13]]

^<<v41-6-13,13>>^ Eles expulsavam muitos demônios e curavam muitos doentes, pondo azeite na cabeça deles.

[[v41-6-14]]

^<<v41-6-14,14>>^ O rei Herodes ouviu falar de tudo isso porque a fama de Jesus se havia espalhado por toda parte. Alguns diziam: — Esse homem é João Batista, que foi ressuscitado! Por isso esse homem tem poder para fazer milagres.

[[v41-6-15]]

^<<v41-6-15,15>>^ Outros diziam que ele era Elias. Mas alguns afirmavam: — Ele é profeta , como um daqueles profetas antigos.

[[v41-6-16]]

^<<v41-6-16,16>>^ Quando Herodes ouviu isso, disse: — Ele é João Batista! Eu mandei cortar a cabeça dele, e agora ele foi ressuscitado!

[[v41-6-17]]

^<<v41-6-17,17>>^ Pois tinha sido Herodes mesmo quem havia mandado prender João, amarrar as suas mãos e jogá-lo na cadeia. Ele havia feito isso por causa de Herodias, com quem havia casado, embora ela fosse esposa do seu irmão Filipe.

[[v41-6-18]]

^<<v41-6-18,18>>^ Por isso João tinha dito muitas vezes a Herodes: "Pela nossa Lei  você é proibido de casar com a esposa do seu irmão!"

[[v41-6-19]]

^<<v41-6-19,19>>^ Herodias estava furiosa com João e queria matá-lo. Mas não podia

[[v41-6-20]]

^<<v41-6-20,20>>^ porque Herodes tinha medo dele, pois sabia que ele era um homem bom e dedicado a Deus. Por isso Herodes protegia João. E, quando o ouvia falar, ficava sem saber o que fazer, mas mesmo assim gostava de escutá-lo.

[[v41-6-21]]

^<<v41-6-21,21>>^ Porém no dia do aniversário de Herodes apareceu a ocasião que Herodias estava esperando. Nesse dia Herodes deu um banquete para as pessoas importantes do seu governo: altos funcionários, chefes militares e autoridades da Galileia.

[[v41-6-22]]

^<<v41-6-22,22>>^ Durante o banquete a filha de Herodias entrou no salão e dançou. Herodes e os seus convidados gostaram muito da dança. Então o rei disse à moça: — Peça o que quiser, e eu lhe darei.

[[v41-6-23]]

^<<v41-6-23,23>>^ E jurou: — Prometo que darei o que você pedir, mesmo que seja a metade do meu reino!

[[v41-6-24]]

^<<v41-6-24,24>>^ Ela foi perguntar à sua mãe o que devia pedir. E a mãe respondeu: — Peça a cabeça de João Batista.

[[v41-6-25]]

^<<v41-6-25,25>>^ No mesmo instante a moça voltou depressa aonde estava o rei e pediu: — Quero a cabeça de João Batista num prato, agora mesmo!

[[v41-6-26]]

^<<v41-6-26,26>>^ Herodes ficou muito triste, mas, por causa do juramento que havia feito na frente dos convidados, não pôde deixar de atender o pedido da moça.

[[v41-6-27]]

^<<v41-6-27,27>>^ Mandou imediatamente um soldado da guarda trazer a cabeça de João. O soldado foi à cadeia, cortou a cabeça de João,

[[v41-6-28]]

^<<v41-6-28,28>>^ pôs num prato e deu à moça. E ela a entregou à sua mãe.

[[v41-6-29]]

^<<v41-6-29,29>>^ Quando os discípulos de João souberam disso, vieram, levaram o corpo dele e o sepultaram.

[[v41-6-30]]

^<<v41-6-30,30>>^ Os apóstolos  voltaram e contaram a Jesus tudo o que tinham feito e ensinado.

[[v41-6-31]]

^<<v41-6-31,31>>^ Havia ali tanta gente, chegando e saindo, que Jesus e os apóstolos não tinham tempo nem para comer. Então ele lhes disse: — Venham! Vamos sozinhos para um lugar deserto a fim de descansarmos um pouco.

[[v41-6-32]]

^<<v41-6-32,32>>^ Então foram sozinhos de barco para um lugar deserto.

[[v41-6-33]]

^<<v41-6-33,33>>^ Porém muitas pessoas os viram sair e os reconheceram. De todos os povoados, muitos correram pela margem e chegaram lá antes deles.

[[v41-6-34]]

^<<v41-6-34,34>>^ Quando Jesus desceu do barco, viu a multidão e teve pena daquela gente porque pareciam ovelhas sem pastor. E começou a ensinar muitas coisas.

[[v41-6-35]]

^<<v41-6-35,35>>^ De tardinha, os discípulos chegaram perto de Jesus e disseram: — Já é tarde, e este lugar é deserto.

[[v41-6-36]]

^<<v41-6-36,36>>^ Mande esta gente embora, a fim de que vão aos sítios e povoados de perto daqui e comprem alguma coisa para comer.

[[v41-6-37]]

^<<v41-6-37,37>>^ Mas Jesus respondeu: — Deem vocês mesmos comida a eles. Os discípulos disseram: — Para comprarmos pão para toda esta gente, nós precisaríamos de duzentas moedas de prata .

[[v41-6-38]]

^<<v41-6-38,38>>^ Jesus perguntou: — Quantos pães vocês têm? Vão ver. Os discípulos foram ver e disseram: — Temos cinco pães e dois peixes.

[[v41-6-39]]

^<<v41-6-39,39>>^ Então Jesus mandou o povo sentar-se em grupos na grama verde.

[[v41-6-40]]

^<<v41-6-40,40>>^ Todos se sentaram em grupos de cem e de cinquenta.

[[v41-6-41]]

^<<v41-6-41,41>>^ Aí Jesus pegou os cinco pães e os dois peixes, olhou para o céu e deu graças a Deus. Depois partiu os pães e os entregou aos discípulos para que eles distribuíssem ao povo. E também dividiu os dois peixes com todos.

[[v41-6-42]]

^<<v41-6-42,42>>^ Todos comeram e ficaram satisfeitos.

[[v41-6-43]]

^<<v41-6-43,43>>^ E os discípulos ainda recolheram doze cestos cheios de pedaços de pão e de peixe.

[[v41-6-44]]

^<<v41-6-44,44>>^ Foram cinco mil os homens que comeram os pães.

[[v41-6-45]]

^<<v41-6-45,45>>^ Logo depois, Jesus ordenou aos discípulos que subissem no barco e fossem na frente para o povoado de Betsaida, no lado leste do lago, enquanto ele mandava o povo embora.

[[v41-6-46]]

^<<v41-6-46,46>>^ Depois de se despedir dos discípulos, Jesus subiu um monte a fim de orar ali.

[[v41-6-47]]

^<<v41-6-47,47>>^ Quando chegou a noite, o barco estava no meio do lago, e Jesus estava em terra, sozinho.

[[v41-6-48]]

^<<v41-6-48,48>>^ Ele viu que os discípulos estavam remando com dificuldade porque o vento soprava contra eles. Já de madrugada, entre as três e as seis horas, Jesus foi até lá, andando em cima da água, e ia passar adiante deles.

[[v41-6-49]]

^<<v41-6-49,49>>^ Quando viram Jesus andando em cima da água, os discípulos pensaram que ele era um fantasma e começaram a gritar.

[[v41-6-50]]

^<<v41-6-50,50>>^ Todos ficaram apavorados com o que viram. Mas logo Jesus falou com eles, dizendo: — Coragem, sou eu! Não tenham medo!

[[v41-6-51]]

^<<v41-6-51,51>>^ Aí subiu no barco com eles, e o vento se acalmou. Os discípulos estavam completamente apavorados.

[[v41-6-52]]

^<<v41-6-52,52>>^ É que a mente deles estava fechada, e eles não tinham entendido o milagre dos pães.

[[v41-6-53]]

^<<v41-6-53,53>>^ Jesus e os discípulos atravessaram o lago e chegaram à região de Genesaré, onde amarraram o barco na praia.

[[v41-6-54]]

^<<v41-6-54,54>>^ Quando desceram do barco, o povo logo reconheceu Jesus.

[[v41-6-55]]

^<<v41-6-55,55>>^ Então, eles saíram correndo por toda aquela região, começaram a trazer os doentes em camas e os levavam para o lugar onde sabiam que Jesus estava.

[[v41-6-56]]

^<<v41-6-56,56>>^ Em todos os lugares aonde ele ia, isto é, nos povoados, nas cidades e nas fazendas, punham os doentes nas praças e pediam a Jesus que os deixasse pelo menos tocar na barra da sua roupa. E todos os que tocavam nela ficavam curados.

'''

xref:041-marcos/041-marcos-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-marcos/041-marcos-007.adoc#v41-7-0[Próximo Capítulo &#62;]