include::./index.adoc[]

[[v41-2-0]]
=== Marcos, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-2-1]]

^<<v41-2-1,1>>^ Alguns dias depois, Jesus voltou para a cidade de Cafarnaum, e logo se espalhou a notícia de que ele estava em casa.

[[v41-2-2]]

^<<v41-2-2,2>>^ Muitas pessoas foram até lá, e ajuntou-se tanta gente, que não havia lugar nem mesmo do lado de fora, perto da porta. Enquanto Jesus estava anunciando a mensagem,

[[v41-2-3]]

^<<v41-2-3,3>>^ trouxeram um paralítico. Ele estava sendo carregado por quatro homens,

[[v41-2-4]]

^<<v41-2-4,4>>^ mas, por causa de toda aquela gente, eles não puderam levá-lo até perto de Jesus. Então fizeram um buraco no telhado da casa, em cima do lugar onde Jesus estava, e pela abertura desceram o doente deitado na sua cama.

[[v41-2-5]]

^<<v41-2-5,5>>^ Jesus viu que eles tinham fé e disse ao paralítico: — Meu filho, os seus pecados estão perdoados.

[[v41-2-6]]

^<<v41-2-6,6>>^ Alguns mestres  da Lei que estavam sentados ali começaram a pensar:

[[v41-2-7]]

^<<v41-2-7,7>>^ "O que é isso que esse homem está dizendo? Isso é blasfêmia  contra Deus! Ninguém pode perdoar pecados; só Deus tem esse poder!"

[[v41-2-8]]

^<<v41-2-8,8>>^ No mesmo instante Jesus soube o que eles estavam pensando e disse: — Por que vocês estão pensando essas coisas?

[[v41-2-9]]

^<<v41-2-9,9>>^ O que é mais fácil dizer ao paralítico: "Os seus pecados estão perdoados" ou "Levante-se, pegue a sua cama e ande"?

[[v41-2-10]]

^<<v41-2-10,10>>^ Pois vou mostrar a vocês que eu, o Filho do Homem , tenho poder na terra para perdoar pecados. Então disse ao paralítico:

[[v41-2-11]]

^<<v41-2-11,11>>^ — Eu digo a você: levante-se, pegue a sua cama e vá para casa.

[[v41-2-12]]

^<<v41-2-12,12>>^ No mesmo instante o homem se levantou na frente de todos, pegou a cama e saiu. Todos ficaram muito admirados e louvaram a Deus, dizendo: — Nunca vimos uma coisa assim!

[[v41-2-13]]

^<<v41-2-13,13>>^ Jesus saiu outra vez e foi para o lago da Galileia. Muita gente ia procurá-lo, e ele ensinava a todos.

[[v41-2-14]]

^<<v41-2-14,14>>^ Enquanto estava caminhando, Jesus viu Levi , filho de Alfeu, sentado no lugar onde os impostos eram pagos. Então disse a Levi: — Venha comigo. Levi se levantou e foi com ele.

[[v41-2-15]]

^<<v41-2-15,15>>^ Mais tarde, Jesus estava jantando na casa de Levi. Junto com Jesus e os seus discípulos estavam muitos cobradores de impostos e outras pessoas de má fama que o seguiam.

[[v41-2-16]]

^<<v41-2-16,16>>^ Alguns mestres  da Lei, que eram do partido dos fariseus , vendo Jesus comer com aquela gente e com os cobradores de impostos, perguntaram aos discípulos: — Por que ele come e bebe com essa gente?

[[v41-2-17]]

^<<v41-2-17,17>>^ Jesus ouviu a pergunta e disse aos mestres da Lei: — Os que têm saúde não precisam de médico, mas sim os doentes. Eu vim para chamar  os pecadores e não os bons.

[[v41-2-18]]

^<<v41-2-18,18>>^ Os discípulos de João Batista e os fariseus  estavam jejuando. Algumas pessoas chegaram perto de Jesus e disseram a ele: — Os discípulos de João e os discípulos dos fariseus jejuam. Por que é que os discípulos do senhor não jejuam?

[[v41-2-19]]

^<<v41-2-19,19>>^ Jesus respondeu: — Vocês acham que os convidados de um casamento jejuam enquanto o noivo está com eles? Enquanto ele está presente, é claro que não jejuam!

[[v41-2-20]]

^<<v41-2-20,20>>^ Mas chegará o tempo em que o noivo será tirado do meio deles; então sim eles vão jejuar!

[[v41-2-21]]

^<<v41-2-21,21>>^ — Ninguém usa um retalho de pano novo para remendar uma roupa velha; pois o remendo novo encolhe e rasga a roupa velha, aumentando o buraco.

[[v41-2-22]]

^<<v41-2-22,22>>^ Ninguém põe vinho novo em odres  velhos. Se alguém fizer isso, os odres rebentam, o vinho se perde, e os odres ficam estragados. Por isso, o vinho novo é posto em odres novos.

[[v41-2-23]]

^<<v41-2-23,23>>^ Num sábado, Jesus e os seus discípulos estavam atravessando uma plantação de trigo. Enquanto caminhavam, os discípulos iam colhendo espigas.

[[v41-2-24]]

^<<v41-2-24,24>>^ Então alguns fariseus  perguntaram a Jesus: — Por que é que os seus discípulos estão fazendo uma coisa que a nossa Lei  proíbe fazer no sábado?

[[v41-2-25]]

^<<v41-2-25,25>>^ Jesus respondeu: — Vocês não leram o que Davi fez, quando ele e os seus companheiros não tinham comida e ficaram com fome?

[[v41-2-26]]

^<<v41-2-26,26>>^ Ele entrou na casa de Deus, na época do Grande Sacerdote  Abiatar, comeu os pães oferecidos a Deus e os deu também aos seus companheiros. No entanto, é contra a nossa Lei alguém comer desses pães; somente os sacerdotes têm o direito de fazer isso.

[[v41-2-27]]

^<<v41-2-27,27>>^ E Jesus terminou: — O sábado foi feito para servir as pessoas, e não as pessoas para servirem o sábado.

[[v41-2-28]]

^<<v41-2-28,28>>^ Portanto, o Filho do Homem  tem autoridade até mesmo sobre o sábado.

'''

xref:041-marcos/041-marcos-001.adoc#v41-1-0[&#60; Capítulo Anterior] | <<v41-2-0,Topo>> | xref:041-marcos/041-marcos-003.adoc#v41-3-0[Próximo Capítulo &#62;]