include::./index.adoc[]

[[v41-7-0]]
=== Marcos, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-7-1]]

^<<v41-7-1,1>>^ Alguns fariseus  e alguns mestres  da Lei que tinham vindo de Jerusalém reuniram-se em volta de Jesus.

[[v41-7-2]]

^<<v41-7-2,2>>^ Eles viram que alguns dos discípulos dele estavam comendo com mãos impuras , quer dizer, não tinham lavado as mãos como os fariseus mandavam o povo fazer.

[[v41-7-3]]

^<<v41-7-3,3>>^ (Os judeus, e especialmente os fariseus, seguem os ensinamentos que receberam dos antigos: eles só comem depois de lavar as mãos com bastante cuidado.

[[v41-7-4]]

^<<v41-7-4,4>>^ E, antes de comer, lavam tudo o que vem do mercado. Seguem ainda muitos outros costumes, como a maneira certa de lavar copos, jarros, vasilhas de metal e camas.)

[[v41-7-5]]

^<<v41-7-5,5>>^ Os fariseus e os mestres da Lei perguntaram a Jesus: — Por que é que os seus discípulos não obedecem aos ensinamentos dos antigos e comem sem lavar as mãos?

[[v41-7-6]]

^<<v41-7-6,6>>^ Jesus respondeu: — Hipócritas! Como Isaías estava certo quando falou a respeito de vocês! Ele escreveu assim: "Deus disse: Este povo com a sua boca diz que me respeita, mas na verdade o seu coração está longe de mim.

[[v41-7-7]]

^<<v41-7-7,7>>^ A adoração deste povo é inútil, pois eles ensinam leis  humanas como se fossem mandamentos de Deus."

[[v41-7-8]]

^<<v41-7-8,8>>^ E continuou: — Vocês abandonam o mandamento de Deus e obedecem a ensinamentos humanos.

[[v41-7-9]]

^<<v41-7-9,9>>^ E Jesus terminou, dizendo: — Vocês arranjam sempre um jeito de pôr de lado o mandamento de Deus, para seguir os seus próprios ensinamentos.

[[v41-7-10]]

^<<v41-7-10,10>>^ Pois Moisés ordenou: "Respeite o seu pai e a sua mãe." E disse também: "Que seja morto aquele que amaldiçoar o seu pai ou a sua mãe!"

[[v41-7-11]]

^<<v41-7-11,11>>^ Mas vocês ensinam que, se alguém tem alguma coisa que poderia usar para ajudar os seus pais, mas diz: "Eu dediquei isto a Deus",

[[v41-7-12]]

^<<v41-7-12,12>>^ então ele não precisa ajudar os seus pais.

[[v41-7-13]]

^<<v41-7-13,13>>^ Assim vocês desprezam a palavra de Deus, trocando-a por ensinamentos que passam de pais para filhos. E vocês fazem muitas outras coisas como esta.

[[v41-7-14]]

^<<v41-7-14,14>>^ Jesus chamou outra vez a multidão e disse: — Escutem todos o que eu vou dizer e entendam!

[[v41-7-15]]

^<<v41-7-15,15>>^ Tudo o que vem de fora e entra numa pessoa não faz com que ela fique impura , mas o que sai de dentro, isto é, do coração da pessoa, é que faz com que ela fique impura.

[[v41-7-16]]

^<<v41-7-16,16>>^ [Se vocês têm ouvidos para ouvir, então ouçam.]

[[v41-7-17]]

^<<v41-7-17,17>>^ Quando Jesus se afastou da multidão e entrou em casa, os seus discípulos lhe perguntaram o que queria dizer essa comparação.

[[v41-7-18]]

^<<v41-7-18,18>>^ Então ele disse: — Vocês são como os outros; não entendem nada! Aquilo que entra pela boca da pessoa não pode fazê-la ficar impura,

[[v41-7-19]]

^<<v41-7-19,19>>^ porque não vai para o coração, mas para o estômago, e depois sai do corpo. Com isso Jesus quis dizer que todos os tipos de alimento podem ser comidos.

[[v41-7-20]]

^<<v41-7-20,20>>^ Ele continuou: — O que sai da pessoa é o que a faz ficar impura.

[[v41-7-21]]

^<<v41-7-21,21>>^ Porque é de dentro, do coração, que vêm os maus pensamentos, a imoralidade sexual, os roubos, os crimes de morte,

[[v41-7-22]]

^<<v41-7-22,22>>^ os adultérios, a avareza, as maldades, as mentiras, as imoralidades, a inveja, a calúnia, o orgulho e o falar e agir sem pensar nas consequências.

[[v41-7-23]]

^<<v41-7-23,23>>^ Tudo isso vem de dentro e faz com que as pessoas fiquem impuras.

[[v41-7-24]]

^<<v41-7-24,24>>^ Jesus saiu dali e foi para a região que fica perto da cidade de Tiro. Ele entrou numa casa e não queria que soubessem que estava ali, mas não pôde se esconder.

[[v41-7-25]]

^<<v41-7-25,25>>^ Certa mulher, que tinha uma filha que estava dominada por um espírito mau, ouviu falar a respeito de Jesus. Ela veio e se ajoelhou aos pés dele.

[[v41-7-26]]

^<<v41-7-26,26>>^ Era estrangeira, de nacionalidade siro-fenícia, e pediu que Jesus expulsasse da sua filha o demônio.

[[v41-7-27]]

^<<v41-7-27,27>>^ Mas Jesus lhe disse: — Deixe que os filhos comam primeiro. Não está certo tirar o pão dos filhos e jogá-lo para os cachorros.

[[v41-7-28]]

^<<v41-7-28,28>>^ — Mas, senhor, — respondeu a mulher — até mesmo os cachorrinhos que ficam debaixo da mesa comem as migalhas de pão que as crianças deixam cair.

[[v41-7-29]]

^<<v41-7-29,29>>^ Jesus disse: — Por causa dessa resposta você pode voltar para casa; o demônio já saiu da sua filha.

[[v41-7-30]]

^<<v41-7-30,30>>^ Quando a mulher voltou para casa, encontrou a criança deitada na cama; de fato, o demônio tinha saído dela.

[[v41-7-31]]

^<<v41-7-31,31>>^ Jesus saiu da região que fica perto da cidade de Tiro, passou por Sidom e pela região das Dez Cidades  e chegou ao lago da Galileia.

[[v41-7-32]]

^<<v41-7-32,32>>^ Algumas pessoas trouxeram um homem que era surdo e quase não podia falar e pediram a Jesus que pusesse a mão sobre ele.

[[v41-7-33]]

^<<v41-7-33,33>>^ Jesus o tirou do meio da multidão e pôs os dedos nos ouvidos dele. Em seguida cuspiu e colocou um pouco da saliva na língua do homem.

[[v41-7-34]]

^<<v41-7-34,34>>^ Depois olhou para o céu, deu um suspiro profundo e disse ao homem: — "Efatá!"  (Isto quer dizer: "Abra-se!" )

[[v41-7-35]]

^<<v41-7-35,35>>^ E naquele momento os ouvidos do homem se abriram, a sua língua se soltou, e ele começou a falar sem dificuldade.

[[v41-7-36]]

^<<v41-7-36,36>>^ Jesus ordenou a todos que não contassem para ninguém o que tinha acontecido; porém, quanto mais ele ordenava, mais eles falavam do que havia acontecido.

[[v41-7-37]]

^<<v41-7-37,37>>^ E todas as pessoas que o ouviam ficavam muito admiradas e diziam: — Tudo o que faz ele faz bem; ele até mesmo faz com que os surdos ouçam e os mudos falem!

'''

xref:041-marcos/041-marcos-006.adoc#v41-6-0[&#60; Capítulo Anterior] | <<v41-7-0,Topo>> | xref:041-marcos/041-marcos-008.adoc#v41-8-0[Próximo Capítulo &#62;]