include::./index.adoc[]

[[v41-1-0]]
=== Marcos, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-1-1]]

^<<v41-1-1,1>>^ A boa notícia que fala a respeito de Jesus Cristo, Filho de Deus, começou a ser dada

[[v41-1-2]]

^<<v41-1-2,2>>^ como o profeta  Isaías tinha escrito. Ele escreveu o seguinte: "Deus disse: Eu enviarei o meu mensageiro adiante de você para preparar o seu caminho."

[[v41-1-3]]

^<<v41-1-3,3>>^ E o profeta escreveu também: "Alguém está gritando no deserto: Preparem o caminho para o Senhor passar! Abram estradas retas para ele!"

[[v41-1-4]]

^<<v41-1-4,4>>^ E foi assim que João Batista apareceu no deserto, batizando o povo e anunciando esta mensagem: — Arrependam-se dos seus pecados e sejam batizados, que Deus perdoará vocês.

[[v41-1-5]]

^<<v41-1-5,5>>^ Muitos moradores da região da Judeia e da cidade de Jerusalém iam ouvir João. Eles confessavam os seus pecados, e João os batizava no rio Jordão.

[[v41-1-6]]

^<<v41-1-6,6>>^ Ele usava uma roupa feita de pelos de camelo e um cinto de couro e comia gafanhotos e mel do mato.

[[v41-1-7]]

^<<v41-1-7,7>>^ Ele dizia ao povo: — Depois de mim vem alguém que é mais importante do que eu, e eu não mereço a honra de me abaixar e desamarrar as correias das sandálias dele.

[[v41-1-8]]

^<<v41-1-8,8>>^ Eu batizo vocês com água, mas ele os batizará com o Espírito Santo.

[[v41-1-9]]

^<<v41-1-9,9>>^ Nessa ocasião Jesus veio de Nazaré, uma pequena cidade da região da Galileia, e foi batizado por João Batista no rio Jordão.

[[v41-1-10]]

^<<v41-1-10,10>>^ No momento em que estava saindo da água, Jesus viu o céu se abrir e o Espírito de Deus descer como uma pomba sobre ele.

[[v41-1-11]]

^<<v41-1-11,11>>^ E do céu veio uma voz, que disse: — Tu és o meu Filho querido e me dás muita alegria.

[[v41-1-12]]

^<<v41-1-12,12>>^ Logo depois o Espírito Santo fez com que Jesus fosse para o deserto.

[[v41-1-13]]

^<<v41-1-13,13>>^ Jesus ficou lá durante quarenta dias, sendo tentado por Satanás. Ali havia animais selvagens, e os anjos cuidavam de Jesus.

[[v41-1-14]]

^<<v41-1-14,14>>^ Depois que João foi preso, Jesus seguiu para a região da Galileia e ali anunciava a boa notícia que vem de Deus.

[[v41-1-15]]

^<<v41-1-15,15>>^ Ele dizia: — Chegou a hora, e o Reino de Deus  está perto. Arrependam-se dos seus pecados e creiam no evangelho .

[[v41-1-16]]

^<<v41-1-16,16>>^ Jesus estava andando pela beira do lago da Galileia quando viu dois pescadores. Eram Simão e o seu irmão André, que estavam no lago, pescando com redes.

[[v41-1-17]]

^<<v41-1-17,17>>^ Jesus lhes disse: — Venham comigo, que eu ensinarei vocês a pescar gente.

[[v41-1-18]]

^<<v41-1-18,18>>^ Então eles largaram logo as redes e foram com Jesus.

[[v41-1-19]]

^<<v41-1-19,19>>^ Um pouco mais adiante Jesus viu outros dois irmãos. Eram Tiago e João, filhos de Zebedeu, que estavam no barco deles, consertando as redes.

[[v41-1-20]]

^<<v41-1-20,20>>^ Jesus chamou os dois, e eles deixaram Zebedeu, o seu pai, e os empregados no barco e foram com ele.

[[v41-1-21]]

^<<v41-1-21,21>>^ Jesus e os discípulos chegaram à cidade de Cafarnaum, e, no sábado, ele foi ensinar na sinagoga .

[[v41-1-22]]

^<<v41-1-22,22>>^ As pessoas que o escutavam ficaram muito admiradas com a sua maneira de ensinar. É que Jesus ensinava com a autoridade dele mesmo e não como os mestres  da Lei.

[[v41-1-23]]

^<<v41-1-23,23>>^ Então chegou ali um homem que estava dominado por um espírito mau. O homem gritou:

[[v41-1-24]]

^<<v41-1-24,24>>^ — O que quer de nós, Jesus de Nazaré? Você veio para nos destruir? Sei muito bem quem é você: é o Santo que Deus enviou!

[[v41-1-25]]

^<<v41-1-25,25>>^ Então Jesus ordenou ao espírito mau: — Cale a boca e saia desse homem!

[[v41-1-26]]

^<<v41-1-26,26>>^ Aí o espírito sacudiu o homem com violência e, dando um grito, saiu dele.

[[v41-1-27]]

^<<v41-1-27,27>>^ Todos ficaram espantados e diziam uns para os outros: — Que quer dizer isso? É um novo ensinamento dado com autoridade. Ele manda até nos espíritos maus, e eles obedecem.

[[v41-1-28]]

^<<v41-1-28,28>>^ E a fama de Jesus se espalhou depressa por toda a região da Galileia.

[[v41-1-29]]

^<<v41-1-29,29>>^ Logo depois, Jesus, Simão, André, Tiago e João saíram da sinagoga  e foram até a casa de Simão e de André.

[[v41-1-30]]

^<<v41-1-30,30>>^ A sogra de Simão estava de cama, com febre. Assim que Jesus chegou, contaram a ele que ela estava doente.

[[v41-1-31]]

^<<v41-1-31,31>>^ Ele chegou perto dela, segurou a mão dela e ajudou-a a se levantar. A febre saiu da mulher, e ela começou a cuidar deles.

[[v41-1-32]]

^<<v41-1-32,32>>^ À tarde, depois do pôr do sol , levaram até Jesus todos os doentes e as pessoas que estavam dominadas por demônios.

[[v41-1-33]]

^<<v41-1-33,33>>^ Todo o povo da cidade se reuniu em frente da casa.

[[v41-1-34]]

^<<v41-1-34,34>>^ Jesus curou muitas pessoas de todo tipo de doenças e expulsou muitos demônios. Ele não deixava que os demônios falassem, pois eles sabiam quem Jesus era.

[[v41-1-35]]

^<<v41-1-35,35>>^ De manhã bem cedo, quando ainda estava escuro, Jesus se levantou, saiu da cidade, foi para um lugar deserto e ficou ali orando.

[[v41-1-36]]

^<<v41-1-36,36>>^ Simão e os seus companheiros procuraram Jesus por toda parte.

[[v41-1-37]]

^<<v41-1-37,37>>^ Quando o encontraram, disseram: — Todos estão procurando o senhor.

[[v41-1-38]]

^<<v41-1-38,38>>^ Jesus respondeu: — Vamos aos povoados que ficam perto daqui, para que eu possa anunciar o evangelho  ali também, pois foi para isso que eu vim.

[[v41-1-39]]

^<<v41-1-39,39>>^ Jesus andava por toda a Galileia, anunciando o evangelho nas sinagogas  e expulsando demônios.

[[v41-1-40]]

^<<v41-1-40,40>>^ Um leproso chegou perto de Jesus, ajoelhou-se e disse: — Senhor, eu sei que o senhor pode me curar se quiser.

[[v41-1-41]]

^<<v41-1-41,41>>^ Jesus ficou com muita pena dele, tocou nele e disse: — Sim! Eu quero. Você está curado.

[[v41-1-42]]

^<<v41-1-42,42>>^ No mesmo instante a lepra desapareceu, e ele ficou curado.

[[v41-1-43]]

^<<v41-1-43,43>>^ E Jesus ordenou duramente: — Olhe! Não conte isso para ninguém, mas vá pedir ao sacerdote que examine você. Depois, a fim de provar para todos que você está curado, vá oferecer o sacrifício  que Moisés ordenou. Então Jesus o mandou embora.

[[v41-1-44]]

^<<v41-1-44,44>>^ E Jesus ordenou duramente:

'''

xref:040-mateus/040-mateus-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-marcos/041-marcos-002.adoc#v41-2-0[Próximo Capítulo &#62;]