include::./index.adoc[]

[[v41-16-0]]
=== Marcos, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v41-16-1]]

^<<v41-16-1,1>>^ Depois que terminou o sábado, Maria Madalena, Salomé e Maria, a mãe de Tiago, compraram perfumes para perfumar o corpo de Jesus.

[[v41-16-2]]

^<<v41-16-2,2>>^ No domingo, bem cedo, ao nascer do sol, elas foram ao túmulo.

[[v41-16-3]]

^<<v41-16-3,3>>^ No caminho perguntavam umas às outras: — Quem vai tirar para nós a pedra que fecha a entrada do túmulo?

[[v41-16-4]]

^<<v41-16-4,4>>^ Elas diziam isso porque a pedra era muito grande. Mas, quando olharam, viram que ela já havia sido tirada.

[[v41-16-5]]

^<<v41-16-5,5>>^ Então elas entraram no túmulo e viram um moço vestido de branco sentado no lado direito. Elas ficaram muito assustadas,

[[v41-16-6]]

^<<v41-16-6,6>>^ mas ele disse: — Não se assustem! Sei que vocês estão procurando Jesus de Nazaré, que foi crucificado; mas ele não está aqui, pois já foi ressuscitado. Vejam o lugar onde ele foi posto.

[[v41-16-7]]

^<<v41-16-7,7>>^ Agora vão e deem este recado a Pedro e aos outros discípulos: "Ele vai adiante de vocês para a Galileia. Lá vocês vão vê-lo, como ele mesmo disse."

[[v41-16-8]]

^<<v41-16-8,8>>^ Então elas saíram e fugiram do túmulo, apavoradas e tremendo. E não contaram nada a ninguém porque estavam com muito medo.

[[v41-16-9]]

^<<v41-16-9,9>>^ [Jesus ressuscitou no domingo bem cedo e apareceu primeiro a Maria Madalena, de quem havia expulsado sete demônios.

[[v41-16-10]]

^<<v41-16-10,10>>^ Ela foi contar isso aos companheiros de Jesus, pois eles estavam tristes e chorando.

[[v41-16-11]]

^<<v41-16-11,11>>^ Quando a ouviram dizer que Jesus estava vivo e que tinha aparecido a ela, eles não acreditaram.

[[v41-16-12]]

^<<v41-16-12,12>>^ Depois disso Jesus se apresentou com outra aparência a dois discípulos que iam caminhando para o campo.

[[v41-16-13]]

^<<v41-16-13,13>>^ Eles voltaram e foram contar isso aos outros discípulos, e estes não acreditaram no que os dois disseram.

[[v41-16-14]]

^<<v41-16-14,14>>^ Por último Jesus apareceu aos onze discípulos enquanto eles estavam à mesa, comendo. Ele os repreendeu por não terem fé e por teimarem em não acreditar no que haviam contado os que o tinham visto ressuscitado.

[[v41-16-15]]

^<<v41-16-15,15>>^ Então ele disse: — Vão pelo mundo inteiro e anunciem o evangelho  a todas as pessoas.

[[v41-16-16]]

^<<v41-16-16,16>>^ Quem crer e for batizado será salvo, mas quem não crer será condenado.

[[v41-16-17]]

^<<v41-16-17,17>>^ Aos que crerem será dado o poder de fazer estes milagres: expulsar demônios pelo poder do meu nome e falar novas línguas;

[[v41-16-18]]

^<<v41-16-18,18>>^ se pegarem em cobras ou beberem algum veneno, não sofrerão nenhum mal; e, quando puserem as mãos sobre os doentes, estes ficarão curados.

[[v41-16-19]]

^<<v41-16-19,19>>^ Depois de falar com eles, o Senhor Jesus foi levado para o céu e sentou-se do lado direito de Deus.

[[v41-16-20]]

^<<v41-16-20,20>>^ Os discípulos foram anunciar o evangelho  por toda parte. E o Senhor os ajudava e, por meio de milagres, provava que a mensagem deles era verdadeira.]

'''

xref:041-marcos/041-marcos-015.adoc#v41-15-0[&#60; Capítulo Anterior] | <<v41-16-0,Topo>> | xref:042-lucas/042-lucas-001.adoc#v42-1-0[Próximo Capítulo &#62;]