include::./index.adoc[]

[[v43-18-0]]
=== João, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-18-1]]

^<<v43-18-1,1>>^ Depois de fazer essa oração, Jesus saiu com os discípulos e foi para o outro lado do riacho de Cedrom. Havia ali um jardim, onde Jesus entrou com eles.

[[v43-18-2]]

^<<v43-18-2,2>>^ Judas, o traidor, conhecia aquele lugar porque Jesus tinha se reunido muitas vezes ali com os discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Então Judas foi ao jardim com um grupo de soldados e alguns guardas do Templo mandados pelos chefes dos sacerdotes e pelos fariseus . Eles estavam armados e levavam lanternas e tochas.

[[v43-18-4]]

^<<v43-18-4,4>>^ Jesus sabia de tudo o que lhe ia acontecer. Por isso caminhou na direção deles e perguntou: — Quem é que vocês estão procurando?

[[v43-18-5]]

^<<v43-18-5,5>>^ — Jesus de Nazaré! — responderam. — Sou eu!  — disse Jesus. Judas, o traidor, estava com eles.

[[v43-18-6]]

^<<v43-18-6,6>>^ Quando Jesus disse: "Sou eu", eles recuaram e caíram no chão.

[[v43-18-7]]

^<<v43-18-7,7>>^ Jesus perguntou outra vez: — Quem é que vocês estão procurando? — Jesus de Nazaré! — tornaram a responder.

[[v43-18-8]]

^<<v43-18-8,8>>^ Jesus disse: — Já afirmei que sou eu. Se é a mim que vocês procuram, então deixem que estes outros vão embora!

[[v43-18-9]]

^<<v43-18-9,9>>^ Jesus disse isso para que se cumprisse o que ele tinha dito antes: "Pai, de todos aqueles que me deste, nenhum se perdeu."

[[v43-18-10]]

^<<v43-18-10,10>>^ Aí Simão Pedro tirou a espada, atacou um empregado do Grande Sacerdote  e cortou a orelha direita dele. O nome do empregado era Malco.

[[v43-18-11]]

^<<v43-18-11,11>>^ Mas Jesus disse a Pedro: — Guarde a sua espada! Por acaso você pensa que eu não vou beber o cálice de sofrimento que o Pai me deu?

[[v43-18-12]]

^<<v43-18-12,12>>^ Em seguida os soldados, o comandante e os guardas do Templo prenderam Jesus e o amarraram.

[[v43-18-13]]

^<<v43-18-13,13>>^ Então o levaram primeiro até a casa de Anás. Anás era o sogro de Caifás, que naquele ano era o Grande Sacerdote .

[[v43-18-14]]

^<<v43-18-14,14>>^ Caifás era quem tinha dito aos líderes judeus que era melhor para eles que morresse apenas um homem pelo povo.

[[v43-18-15]]

^<<v43-18-15,15>>^ Simão Pedro foi seguindo Jesus, junto com outro discípulo. Esse discípulo era conhecido do Grande Sacerdote  e por isso conseguiu entrar no pátio da casa dele junto com Jesus.

[[v43-18-16]]

^<<v43-18-16,16>>^ Mas Pedro ficou do lado de fora, perto da porta. O outro discípulo, que era conhecido do Grande Sacerdote, saiu e falou com a empregada que tomava conta da porta. Então ela deixou Pedro entrar

[[v43-18-17]]

^<<v43-18-17,17>>^ e lhe perguntou: — Você não é um dos seguidores daquele homem? — Eu, não! — respondeu ele.

[[v43-18-18]]

^<<v43-18-18,18>>^ Por causa do frio, os empregados e os guardas tinham feito uma fogueira e estavam se aquecendo de pé, em volta dela. Pedro estava de pé, no meio deles, aquecendo-se também.

[[v43-18-19]]

^<<v43-18-19,19>>^ O Grande Sacerdote  fez algumas perguntas a Jesus a respeito dos seus seguidores e dos seus ensinamentos.

[[v43-18-20]]

^<<v43-18-20,20>>^ E Jesus respondeu: — Eu sempre falei a todos publicamente. Ensinava nas sinagogas  e no pátio do Templo, onde o povo se reúne, e nunca disse nada em segredo.

[[v43-18-21]]

^<<v43-18-21,21>>^ Então, por que o senhor está me fazendo essas perguntas? Pergunte aos que me ouviram, pois eles sabem muito bem o que eu disse a eles.

[[v43-18-22]]

^<<v43-18-22,22>>^ Quando Jesus disse isso, um dos guardas do Templo que estavam ali deu-lhe uma bofetada e disse: — Isso é maneira de falar com o Grande Sacerdote?

[[v43-18-23]]

^<<v43-18-23,23>>^ — Se eu disse alguma mentira, prove que menti!  — respondeu Jesus. — Mas, se eu falei a verdade, por que é que você está me batendo?

[[v43-18-24]]

^<<v43-18-24,24>>^ Depois Anás mandou Jesus, ainda amarrado, para Caifás, o Grande Sacerdote.

[[v43-18-25]]

^<<v43-18-25,25>>^ Pedro ainda estava lá, de pé, aquecendo-se perto do fogo. Então lhe perguntaram: — Você não é um dos seguidores daquele homem? — Não, eu não sou! — respondeu ele.

[[v43-18-26]]

^<<v43-18-26,26>>^ Um dos empregados do Grande Sacerdote , parente do homem de quem Pedro tinha cortado a orelha, perguntou: — Será que eu não vi você com ele no jardim?

[[v43-18-27]]

^<<v43-18-27,27>>^ E outra vez Pedro disse que não. E no mesmo instante o galo cantou.

[[v43-18-28]]

^<<v43-18-28,28>>^ Depois levaram Jesus da casa de Caifás para o palácio do Governador romano. Já era de manhã cedo. Os líderes judeus não entraram no palácio porque queriam continuar puros , conforme a religião deles; pois só assim poderiam comer o jantar da Páscoa .

[[v43-18-29]]

^<<v43-18-29,29>>^ Então o governador Pilatos saiu, foi encontrar-se com eles e perguntou: — Que acusação vocês têm contra este homem?

[[v43-18-30]]

^<<v43-18-30,30>>^ Eles responderam: — O senhor acha que nós lhe entregaríamos este homem se ele não tivesse cometido algum crime?

[[v43-18-31]]

^<<v43-18-31,31>>^ Pilatos disse: — Levem este homem e o julguem vocês mesmos, de acordo com a lei  de vocês. Então eles responderam: — Nós não temos o direito de matar ninguém.

[[v43-18-32]]

^<<v43-18-32,32>>^ Isso aconteceu assim para que se cumprisse o que Jesus tinha dito quando falou a respeito de como ia morrer .

[[v43-18-33]]

^<<v43-18-33,33>>^ Pilatos tornou a entrar no palácio, chamou Jesus e perguntou: — Você é o rei dos judeus?

[[v43-18-34]]

^<<v43-18-34,34>>^ Jesus respondeu: — Esta pergunta é do senhor mesmo ou foram outras pessoas que lhe disseram isso a meu respeito?

[[v43-18-35]]

^<<v43-18-35,35>>^ — Por acaso eu sou judeu? — disse Pilatos. — A sua própria gente e os chefes dos sacerdotes é que o entregaram a mim. O que foi que você fez?

[[v43-18-36]]

^<<v43-18-36,36>>^ Jesus respondeu: — O meu Reino  não é deste mundo! Se o meu Reino fosse deste mundo, os meus seguidores lutariam para não deixar que eu fosse entregue aos líderes judeus. Mas o fato é que o meu Reino não é deste mundo!

[[v43-18-37]]

^<<v43-18-37,37>>^ — Então você é rei? — perguntou Pilatos. — É o senhor que está dizendo que eu sou rei!  — respondeu Jesus. — Foi para falar da verdade que eu nasci e vim ao mundo. Quem está do lado da verdade ouve a minha voz.

[[v43-18-38]]

^<<v43-18-38,38>>^ — O que é a verdade? — perguntou Pilatos. Depois de dizer isso, Pilatos saiu outra vez para falar com a multidão e disse: — Não vejo nenhum motivo para condenar este homem.

[[v43-18-39]]

^<<v43-18-39,39>>^ Mas, de acordo com o costume de vocês, eu sempre solto um prisioneiro na ocasião da Páscoa . Vocês querem que eu solte para vocês o rei dos judeus?

[[v43-18-40]]

^<<v43-18-40,40>>^ Todos começaram a gritar: — Não, ele não! Nós queremos que solte Barrabás! Acontece que esse Barrabás era um criminoso.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]