include::./index.adoc[]

[[v43-16-0]]
=== João, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-16-1]]

^<<v43-16-1,1>>^ E Jesus disse ainda: — Eu digo isso para que vocês não abandonem a sua fé.

[[v43-16-2]]

^<<v43-16-2,2>>^ Vocês serão expulsos das sinagogas , e chegará o tempo em que qualquer um que os matar pensará que está fazendo a vontade de Deus.

[[v43-16-3]]

^<<v43-16-3,3>>^ Eles vão fazer essas coisas porque não conhecem nem o Pai nem a mim.

[[v43-16-4]]

^<<v43-16-4,4>>^ Mas eu digo isso para que, quando essas coisas acontecerem, vocês lembrem que eu já os tinha avisado. E Jesus continuou: — Eu não disse isso antes, porque ainda estava com vocês.

[[v43-16-5]]

^<<v43-16-5,5>>^ Porém agora eu vou para junto daquele que me enviou. E nenhum de vocês me pergunta: "Aonde é que o senhor vai?"

[[v43-16-6]]

^<<v43-16-6,6>>^ Mas, porque eu disse isso, o coração de vocês ficou cheio de tristeza.

[[v43-16-7]]

^<<v43-16-7,7>>^ Eu falo a verdade quando digo que é melhor para vocês que eu vá. Pois, se não for, o Auxiliador não virá; mas, se eu for, eu o enviarei a vocês.

[[v43-16-8]]

^<<v43-16-8,8>>^ Quando o Auxiliador vier, ele convencerá as pessoas do mundo de que elas têm uma ideia errada a respeito do pecado e do que é direito e justo e também do julgamento de Deus.

[[v43-16-9]]

^<<v43-16-9,9>>^ As pessoas do mundo estão erradas a respeito do pecado porque não creem em mim;

[[v43-16-10]]

^<<v43-16-10,10>>^ estão erradas a respeito do que é direito e justo porque eu vou para o Pai, e vocês não vão me ver mais.

[[v43-16-11]]

^<<v43-16-11,11>>^ E também estão erradas a respeito do julgamento porque aquele que manda neste mundo já está julgado.

[[v43-16-12]]

^<<v43-16-12,12>>^ — Ainda tenho muitas coisas para lhes dizer, mas vocês não poderiam suportar isso agora.

[[v43-16-13]]

^<<v43-16-13,13>>^ Porém, quando o Espírito da verdade vier, ele ensinará toda a verdade a vocês. O Espírito não falará por si mesmo, mas dirá tudo o que ouviu e anunciará a vocês as coisas que estão para acontecer.

[[v43-16-14]]

^<<v43-16-14,14>>^ Ele vai ficar sabendo o que tenho para dizer, e dirá a vocês, e assim ele trará glória  para mim.

[[v43-16-15]]

^<<v43-16-15,15>>^ Tudo o que o Pai tem é meu. Por isso eu disse que o Espírito vai ficar sabendo o que eu lhe disser e vai anunciar a vocês.

[[v43-16-16]]

^<<v43-16-16,16>>^ E Jesus disse: — Daqui a pouco vocês não vão me ver mais; porém, pouco depois, vão me ver novamente.

[[v43-16-17]]

^<<v43-16-17,17>>^ Alguns dos seus discípulos comentaram: — O que será que ele quer dizer? Ele afirma: "Daqui a pouco vocês não vão me ver mais; porém, pouco depois, vão me ver novamente". E diz também: "É porque vou para o meu Pai".

[[v43-16-18]]

^<<v43-16-18,18>>^ O que quer dizer "pouco depois"? Não entendemos o que isso quer dizer.

[[v43-16-19]]

^<<v43-16-19,19>>^ Jesus, sabendo que eles queriam lhe fazer perguntas, disse: — Eu afirmei que daqui a pouco vocês não vão me ver mais e que pouco depois vão me ver novamente. Por acaso não é a respeito disso que vocês estão fazendo perguntas uns aos outros?

[[v43-16-20]]

^<<v43-16-20,20>>^ Pois eu afirmo a vocês que isto é verdade: vocês vão chorar e ficar tristes, mas as pessoas do mundo ficarão alegres. Vocês ficarão tristes, mas essa tristeza virará alegria.

[[v43-16-21]]

^<<v43-16-21,21>>^ Quando uma mulher está para dar à luz, ela fica triste porque chegou a sua hora de sofrer. Mas, depois que a criança nasce, a mulher fica tão alegre, que nem lembra mais do seu sofrimento.

[[v43-16-22]]

^<<v43-16-22,22>>^ Assim acontece também com vocês: agora estão tristes, mas eu os verei novamente. Aí vocês ficarão cheios de alegria, e ninguém poderá tirar essa alegria de vocês.

[[v43-16-23]]

^<<v43-16-23,23>>^ — Quando chegar aquele dia, vocês não me pedirão nada. E eu afirmo a vocês que isto é verdade: se vocês pedirem ao Pai alguma coisa em meu nome, ele lhes dará.

[[v43-16-24]]

^<<v43-16-24,24>>^ Até agora vocês não pediram nada em meu nome; peçam e receberão para que a alegria de vocês seja completa.

[[v43-16-25]]

^<<v43-16-25,25>>^ E Jesus terminou, dizendo: — Eu digo essas coisas a vocês por meio de comparações. Mas chegará o tempo em que não falarei mais por meio de comparações, pois falarei claramente a vocês a respeito do Pai.

[[v43-16-26]]

^<<v43-16-26,26>>^ Naquele dia vocês pedirão coisas em meu nome. E eu digo que não precisarei pedir ao Pai em favor de vocês,

[[v43-16-27]]

^<<v43-16-27,27>>^ pois o próprio Pai os ama. Ele os ama porque vocês, de fato, me amam e creem que vim de Deus.

[[v43-16-28]]

^<<v43-16-28,28>>^ Eu vim do Pai e entrei no mundo. E agora deixo o mundo e vou para o Pai.

[[v43-16-29]]

^<<v43-16-29,29>>^ Então os seus discípulos disseram: — Agora, sim, o senhor está falando claramente e não por meio de comparações.

[[v43-16-30]]

^<<v43-16-30,30>>^ Sabemos agora que o senhor conhece tudo e não precisa que ninguém lhe faça perguntas. Por isso nós cremos que o senhor veio de Deus.

[[v43-16-31]]

^<<v43-16-31,31>>^ E Jesus respondeu: — Então agora vocês creem?

[[v43-16-32]]

^<<v43-16-32,32>>^ Pois chegou a hora de vocês todos serem espalhados, cada um para a sua casa; e assim vão me deixar sozinho. Mas eu não estou só, pois o Pai está comigo.

[[v43-16-33]]

^<<v43-16-33,33>>^ Eu digo isso para que, por estarem unidos comigo, vocês tenham paz. No mundo vocês vão sofrer; mas tenham coragem. Eu venci o mundo.

'''

xref:043-joao/043-joao-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-joao/043-joao-017.adoc#v43-17-0[Próximo Capítulo &#62;]