include::./index.adoc[]

[[v43-10-0]]
=== João, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-10-1]]

^<<v43-10-1,1>>^ Jesus disse: — Eu afirmo a vocês que isto é verdade: quem não entra no curral das ovelhas pela porta, mas pula o muro é um ladrão e bandido.

[[v43-10-2]]

^<<v43-10-2,2>>^ Mas quem entra pela porta é o pastor do rebanho.

[[v43-10-3]]

^<<v43-10-3,3>>^ O porteiro abre a porta para ele. As ovelhas reconhecem a sua voz quando ele as chama pelo nome, e ele as leva para fora do curral.

[[v43-10-4]]

^<<v43-10-4,4>>^ Quando todas estão do lado de fora, ele vai na frente delas, e elas o seguem porque conhecem a voz dele.

[[v43-10-5]]

^<<v43-10-5,5>>^ Mas de jeito nenhum seguirão um estranho! Pelo contrário, elas fugirão, pois não conhecem a voz de estranhos.

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus fez esta comparação, mas ninguém entendeu o que ele queria dizer.

[[v43-10-7]]

^<<v43-10-7,7>>^ Então Jesus continuou: — Eu afirmo a vocês que isto é verdade: eu sou a porta por onde as ovelhas passam.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos os que vieram antes de mim são ladrões e bandidos, mas as ovelhas não deram atenção à voz deles.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta. Quem entrar por mim será salvo; poderá entrar e sair e achará comida.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão só vem para roubar, matar e destruir; mas eu vim para que as ovelhas tenham vida, a vida completa.

[[v43-10-11]]

^<<v43-10-11,11>>^ — Eu sou o bom pastor; o bom pastor dá a vida pelas ovelhas.

[[v43-10-12]]

^<<v43-10-12,12>>^ Um empregado trabalha somente por dinheiro; ele não é pastor, e as ovelhas não são dele. Por isso, quando vê um lobo chegando, ele abandona as ovelhas e foge. Então o lobo ataca e espalha as ovelhas.

[[v43-10-13]]

^<<v43-10-13,13>>^ O empregado foge porque trabalha somente por dinheiro e não se importa com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ Eu sou o bom pastor. Assim como o Pai me conhece, e eu conheço o Pai, assim também conheço as minhas ovelhas, e elas me conhecem. E estou pronto para morrer por elas.

[[v43-10-15]]

^<<v43-10-15,15>>^ Eu sou o bom pastor. Assim como o Pai me conhece, e eu conheço o Pai, assim também conheço as minhas ovelhas, e elas me conhecem. E estou pronto para morrer por elas.

[[v43-10-16]]

^<<v43-10-16,16>>^ Tenho outras ovelhas que não estão neste curral. Eu preciso trazer essas também, e elas ouvirão a minha voz. Então elas se tornarão um só rebanho com um só pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ — O Pai me ama porque eu dou a minha vida para recebê-la outra vez.

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém tira a minha vida de mim, mas eu a dou por minha própria vontade. Tenho o direito de dá-la e de tornar a recebê-la, pois foi isso o que o meu Pai me mandou fazer.

[[v43-10-19]]

^<<v43-10-19,19>>^ Quando ouviu isso, o povo se dividiu outra vez. Muitos diziam:

[[v43-10-20]]

^<<v43-10-20,20>>^ — Ele está dominado por um demônio! Está louco! Por que é que vocês escutam o que ele diz?

[[v43-10-21]]

^<<v43-10-21,21>>^ Outros afirmavam: — Quem está dominado por um demônio não fala assim! Será que um demônio pode dar vista aos cegos?

[[v43-10-22]]

^<<v43-10-22,22>>^ Era inverno, e em Jerusalém estavam comemorando a Festa da Dedicação .

[[v43-10-23]]

^<<v43-10-23,23>>^ Jesus estava andando pelo pátio do Templo, perto da entrada chamada " Alpendre de Salomão ".

[[v43-10-24]]

^<<v43-10-24,24>>^ Então o povo se ajuntou em volta dele e perguntou: — Até quando você vai nos deixar na dúvida? Diga com franqueza: você é ou não é o Messias ?

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus respondeu: — Eu já disse, mas vocês não acreditaram. As obras que eu faço pelo poder do nome do meu Pai falam a favor de mim,

[[v43-10-26]]

^<<v43-10-26,26>>^ mas vocês não creem porque não são minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ As minhas ovelhas escutam a minha voz; eu as conheço, e elas me seguem.

[[v43-10-28]]

^<<v43-10-28,28>>^ Eu lhes dou a vida eterna, e por isso elas nunca morrerão. Ninguém poderá arrancá-las da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ O poder que o Pai me deu é maior do que tudo, e ninguém pode arrancá-las da mão dele.

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um.

[[v43-10-31]]

^<<v43-10-31,31>>^ Então eles tornaram a pegar pedras para matar Jesus.

[[v43-10-32]]

^<<v43-10-32,32>>^ E ele disse: — Eu fiz diante de vocês muitas coisas boas que o Pai me mandou fazer. Por causa de qual delas vocês querem me matar?

[[v43-10-33]]

^<<v43-10-33,33>>^ Eles responderam: — Não é por causa de nenhuma coisa boa que queremos matá-lo, mas porque, ao dizer isso, você está blasfemando  contra Deus. Pois você, que é apenas um ser humano, está se fazendo de Deus.

[[v43-10-34]]

^<<v43-10-34,34>>^ Então Jesus afirmou: — Na Lei  de vocês está escrito que Deus disse: "Vocês são deuses."

[[v43-10-35]]

^<<v43-10-35,35>>^ Sabemos que as Escrituras Sagradas  sempre dizem a verdade, e sabemos que, de fato, Deus chamou de deuses aqueles que receberam a sua mensagem.

[[v43-10-36]]

^<<v43-10-36,36>>^ Quanto a mim, o Pai me escolheu e me enviou ao mundo. Então por que vocês dizem que blasfemo contra Deus quando afirmo que sou Filho dele?

[[v43-10-37]]

^<<v43-10-37,37>>^ Se não faço o que o meu Pai manda, não creiam em mim.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas, se eu faço, e vocês não creem em mim, então creiam pelo menos nas coisas que faço. E isso para que vocês fiquem sabendo de uma vez por todas que o Pai vive em mim e que eu vivo no Pai.

[[v43-10-39]]

^<<v43-10-39,39>>^ A essa altura tentaram novamente prendê-lo, mas Jesus escapou das mãos deles.

[[v43-10-40]]

^<<v43-10-40,40>>^ Ele voltou de novo para o lado leste do rio Jordão, foi para o lugar onde João Batista tinha batizado antes e ficou lá.

[[v43-10-41]]

^<<v43-10-41,41>>^ E muita gente ia vê-lo, dizendo: — João não fez nenhum milagre, mas tudo o que ele disse sobre Jesus é verdade.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]