include::./index.adoc[]

[[v43-20-0]]
=== João, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-20-1]]

^<<v43-20-1,1>>^ Domingo bem cedo, quando ainda estava escuro, Maria Madalena foi até o túmulo e viu que a pedra que tapava a entrada tinha sido tirada.

[[v43-20-2]]

^<<v43-20-2,2>>^ Então foi correndo até o lugar onde estavam Simão Pedro e outro discípulo, aquele que Jesus amava, e disse: — Tiraram o Senhor Jesus do túmulo, e não sabemos onde o puseram!

[[v43-20-3]]

^<<v43-20-3,3>>^ Então Pedro e o outro discípulo foram até o túmulo.

[[v43-20-4]]

^<<v43-20-4,4>>^ Os dois saíram correndo juntos, mas o outro correu mais depressa do que Pedro e chegou primeiro.

[[v43-20-5]]

^<<v43-20-5,5>>^ Ele se abaixou para olhar lá dentro e viu os lençóis de linho; porém não entrou no túmulo.

[[v43-20-6]]

^<<v43-20-6,6>>^ Mas Pedro, que chegou logo depois, entrou. Ele também viu os lençóis colocados ali

[[v43-20-7]]

^<<v43-20-7,7>>^ e a faixa que tinham posto em volta da cabeça de Jesus. A faixa não estava junto com os lençóis, mas estava enrolada ali ao lado.

[[v43-20-8]]

^<<v43-20-8,8>>^ Aí o outro discípulo, que havia chegado primeiro, também entrou no túmulo. Ele viu e creu.

[[v43-20-9]]

^<<v43-20-9,9>>^ (Eles ainda não tinham entendido as Escrituras Sagradas , que dizem que era preciso que Jesus ressuscitasse.)

[[v43-20-10]]

^<<v43-20-10,10>>^ E os dois voltaram para casa.

[[v43-20-11]]

^<<v43-20-11,11>>^ Maria Madalena tinha ficado perto da entrada do túmulo, chorando. Enquanto chorava, ela se abaixou, olhou para dentro

[[v43-20-12]]

^<<v43-20-12,12>>^ e viu dois anjos vestidos de branco, sentados onde tinha sido posto o corpo de Jesus. Um estava na cabeceira, e o outro, nos pés.

[[v43-20-13]]

^<<v43-20-13,13>>^ Os anjos perguntaram: — Mulher, por que você está chorando? Ela respondeu: — Levaram embora o meu Senhor, e eu não sei onde o puseram!

[[v43-20-14]]

^<<v43-20-14,14>>^ Depois de dizer isso, ela virou para trás e viu Jesus ali de pé, mas não o reconheceu.

[[v43-20-15]]

^<<v43-20-15,15>>^ Então Jesus perguntou: — Mulher, por que você está chorando? Quem é que você está procurando? Ela pensou que ele era o jardineiro e por isso respondeu: — Se o senhor o tirou daqui, diga onde o colocou, e eu irei buscá-lo.

[[v43-20-16]]

^<<v43-20-16,16>>^ — Maria!  — disse Jesus. Ela virou e respondeu em hebraico : — "Rabôni!" (Esta palavra quer dizer "Mestre".)

[[v43-20-17]]

^<<v43-20-17,17>>^ Jesus disse: — Não me segure, pois ainda não subi para o meu Pai. Vá se encontrar com os meus irmãos e diga a eles que eu vou subir para aquele que é o meu Pai e o Pai deles, o meu Deus e o Deus deles.

[[v43-20-18]]

^<<v43-20-18,18>>^ Então Maria Madalena foi e disse aos discípulos de Jesus: — Eu vi o Senhor! E contou o que Jesus lhe tinha dito.

[[v43-20-19]]

^<<v43-20-19,19>>^ Naquele mesmo domingo, à tarde, os discípulos de Jesus estavam reunidos de portas trancadas, com medo dos líderes judeus. Então Jesus chegou, ficou no meio deles e disse: — Que a paz esteja com vocês!

[[v43-20-20]]

^<<v43-20-20,20>>^ Em seguida lhes mostrou as suas mãos e o seu lado. E eles ficaram muito alegres ao verem o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Então Jesus disse de novo: — Que a paz esteja com vocês! Assim como o Pai me enviou, eu também envio vocês.

[[v43-20-22]]

^<<v43-20-22,22>>^ Depois soprou sobre eles e disse: — Recebam o Espírito Santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Se vocês perdoarem os pecados de alguém, esses pecados são perdoados; mas, se não perdoarem, eles não são perdoados.

[[v43-20-24]]

^<<v43-20-24,24>>^ Acontece que Tomé, um dos discípulos, que era chamado de "o Gêmeo", não estava com eles quando Jesus chegou.

[[v43-20-25]]

^<<v43-20-25,25>>^ Então os outros discípulos disseram a Tomé: — Nós vimos o Senhor! Ele respondeu: — Se eu não vir o sinal dos pregos nas mãos dele, e não tocar ali com o meu dedo, e também se não puser a minha mão no lado dele, não vou crer!

[[v43-20-26]]

^<<v43-20-26,26>>^ Uma semana depois, os discípulos de Jesus estavam outra vez reunidos ali com as portas trancadas, e Tomé estava com eles. Jesus chegou, ficou no meio deles e disse: — Que a paz esteja com vocês!

[[v43-20-27]]

^<<v43-20-27,27>>^ Em seguida disse a Tomé: — Veja as minhas mãos e ponha o seu dedo nelas. Estenda a mão e ponha no meu lado. Pare de duvidar e creia!

[[v43-20-28]]

^<<v43-20-28,28>>^ Então Tomé exclamou: — Meu Senhor e meu Deus!

[[v43-20-29]]

^<<v43-20-29,29>>^ — Você creu porque me viu?  — disse Jesus. — Felizes são os que não viram, mas assim mesmo creram!

[[v43-20-30]]

^<<v43-20-30,30>>^ Jesus fez diante dos discípulos muitos outros milagres que não estão escritos neste livro.

[[v43-20-31]]

^<<v43-20-31,31>>^ Mas estes foram escritos para que vocês creiam que Jesus é o Messias , o Filho de Deus. E para que, crendo, tenham vida por meio dele.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]