include::./index.adoc[]

[[v43-14-0]]
=== João, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-14-1]]

^<<v43-14-1,1>>^ Jesus disse: — Não fiquem aflitos. Creiam em Deus e creiam também em mim.

[[v43-14-2]]

^<<v43-14-2,2>>^ Na casa do meu Pai há muitos quartos, e eu vou preparar um lugar para vocês. Se não fosse assim, eu já lhes teria dito.

[[v43-14-3]]

^<<v43-14-3,3>>^ E, depois que eu for e preparar um lugar para vocês, voltarei e os levarei comigo para que onde eu estiver vocês estejam também.

[[v43-14-4]]

^<<v43-14-4,4>>^ E vocês conhecem o caminho para o lugar aonde eu vou.

[[v43-14-5]]

^<<v43-14-5,5>>^ Então Tomé perguntou: — Senhor, nós não sabemos aonde é que o senhor vai. Como podemos saber o caminho?

[[v43-14-6]]

^<<v43-14-6,6>>^ Jesus respondeu: — Eu sou o caminho, a verdade e a vida; ninguém pode chegar até o Pai a não ser por mim.

[[v43-14-7]]

^<<v43-14-7,7>>^ Agora que vocês me conhecem, conhecerão também o meu Pai. E desde agora vocês o conhecem e o têm visto.

[[v43-14-8]]

^<<v43-14-8,8>>^ Filipe disse a Jesus: — Senhor, mostre-nos o Pai, e assim não precisaremos de mais nada.

[[v43-14-9]]

^<<v43-14-9,9>>^ Jesus respondeu: — Faz tanto tempo que estou com vocês, Filipe, e você ainda não me conhece? Quem me vê vê também o Pai. Por que é que você diz: "Mostre-nos o Pai"?

[[v43-14-10]]

^<<v43-14-10,10>>^ Será que você não crê que eu estou no Pai e que o Pai está em mim? Então Jesus disse aos discípulos: — O que eu digo a vocês não digo em meu próprio nome; o Pai, que está em mim, é quem faz o seu trabalho.

[[v43-14-11]]

^<<v43-14-11,11>>^ Creiam no que lhes digo: eu estou no Pai e o Pai está em mim. Se vocês não creem por causa das minhas palavras, creiam pelo menos por causa das coisas que eu faço.

[[v43-14-12]]

^<<v43-14-12,12>>^ Eu afirmo a vocês que isto é verdade: quem crê em mim fará as coisas que eu faço e até maiores do que estas, pois eu vou para o meu Pai.

[[v43-14-13]]

^<<v43-14-13,13>>^ E tudo o que vocês pedirem em meu nome eu farei, a fim de que o Filho revele a natureza gloriosa  do Pai.

[[v43-14-14]]

^<<v43-14-14,14>>^ Eu farei qualquer coisa que vocês me pedirem em meu nome.

[[v43-14-15]]

^<<v43-14-15,15>>^ Jesus continuou: — Se vocês me amam, obedeçam aos meus mandamentos.

[[v43-14-16]]

^<<v43-14-16,16>>^ Eu pedirei ao Pai, e ele lhes dará outro Auxiliador, o Espírito da verdade, para ficar com vocês para sempre.

[[v43-14-17]]

^<<v43-14-17,17>>^ O mundo não pode receber esse Espírito porque não o pode ver, nem conhecer. Mas vocês o conhecem porque ele está com vocês e viverá em vocês.

[[v43-14-18]]

^<<v43-14-18,18>>^ — Não vou deixá-los abandonados, mas voltarei para ficar com vocês.

[[v43-14-19]]

^<<v43-14-19,19>>^ Daqui a pouco o mundo não me verá mais, mas vocês me verão. E, porque eu vivo, vocês também viverão.

[[v43-14-20]]

^<<v43-14-20,20>>^ Quando chegar aquele dia, vocês ficarão sabendo que eu estou no meu Pai e que vocês estão em mim, assim como eu estou em vocês.

[[v43-14-21]]

^<<v43-14-21,21>>^ — A pessoa que aceita e obedece aos meus mandamentos prova que me ama. E a pessoa que me ama será amada pelo meu Pai, e eu também a amarei e lhe mostrarei quem sou.

[[v43-14-22]]

^<<v43-14-22,22>>^ Então Judas, não o Judas Iscariotes, perguntou: — Senhor, como será possível que o senhor mostre somente a nós e não ao mundo quem o senhor é?

[[v43-14-23]]

^<<v43-14-23,23>>^ Jesus respondeu: — A pessoa que me ama obedecerá à minha mensagem, e o meu Pai a amará. E o meu Pai e eu viremos viver com ela.

[[v43-14-24]]

^<<v43-14-24,24>>^ A pessoa que não me ama não obedece à minha mensagem. E a mensagem que vocês estão escutando não é minha, mas do Pai, que me enviou.

[[v43-14-25]]

^<<v43-14-25,25>>^ — Tenho dito isso enquanto estou com vocês.

[[v43-14-26]]

^<<v43-14-26,26>>^ Mas o Auxiliador, o Espírito Santo, que o Pai vai enviar em meu nome, ensinará a vocês todas as coisas e fará com que lembrem de tudo o que eu disse a vocês.

[[v43-14-27]]

^<<v43-14-27,27>>^ — Deixo com vocês a paz. É a minha paz que eu lhes dou; não lhes dou a paz como o mundo a dá. Não fiquem aflitos, nem tenham medo.

[[v43-14-28]]

^<<v43-14-28,28>>^ Vocês ouviram o que eu disse: "Eu vou, mas voltarei para ficar com vocês." Se vocês me amassem, ficariam alegres, sabendo que vou para o Pai, pois o Pai é mais poderoso do que eu.

[[v43-14-29]]

^<<v43-14-29,29>>^ Digo isso agora, antes que essas coisas aconteçam, para que, quando acontecerem, vocês creiam.

[[v43-14-30]]

^<<v43-14-30,30>>^ Não posso continuar a falar com vocês por muito tempo, pois está chegando aquele que manda neste mundo. Ele não tem poder sobre mim;

[[v43-14-31]]

^<<v43-14-31,31>>^ mas o mundo precisa saber que eu amo o Pai e que, por isso, faço tudo o que ele manda. — Levantem-se, vamos sair daqui!

'''

xref:043-joao/043-joao-013.adoc#v43-13-0[&#60; Capítulo Anterior] | <<v43-14-0,Topo>> | xref:043-joao/043-joao-015.adoc#v43-15-0[Próximo Capítulo &#62;]