include::./index.adoc[]

[[v43-21-0]]
=== João, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-21-1]]

^<<v43-21-1,1>>^ Depois disso, Jesus apareceu outra vez aos seus discípulos, na beira do lago da Galileia. Foi assim que aconteceu:

[[v43-21-2]]

^<<v43-21-2,2>>^ Estavam juntos Simão Pedro e Tomé, chamado "o Gêmeo"; Natanael, que era de Caná da Galileia; os filhos de Zebedeu e mais dois discípulos.

[[v43-21-3]]

^<<v43-21-3,3>>^ Simão Pedro disse aos outros: — Eu vou pescar. — Nós também vamos pescar com você! — disseram eles. Então foram todos e subiram no barco, mas naquela noite não pescaram nada.

[[v43-21-4]]

^<<v43-21-4,4>>^ De manhã, quando começava a clarear, Jesus estava na praia. Porém eles não sabiam que era ele.

[[v43-21-5]]

^<<v43-21-5,5>>^ Então Jesus perguntou: — Moços, vocês pescaram alguma coisa? — Nada! — responderam eles.

[[v43-21-6]]

^<<v43-21-6,6>>^ — Joguem a rede do lado direito do barco, que vocês acharão peixe!  — disse Jesus. Eles jogaram a rede e logo depois já não conseguiam puxá-la para dentro do barco, por causa da grande quantidade de peixes que havia nela.

[[v43-21-7]]

^<<v43-21-7,7>>^ Aí o discípulo que Jesus amava disse a Pedro: — É o Senhor Jesus! Quando Simão Pedro ouviu dizer que era o Senhor, vestiu a capa , pois havia tirado a roupa, e se jogou na água.

[[v43-21-8]]

^<<v43-21-8,8>>^ Os outros discípulos foram no barco, puxando a rede com os peixes, pois estavam somente a uns cem metros da praia.

[[v43-21-9]]

^<<v43-21-9,9>>^ Quando saíram do barco, viram ali uma pequena fogueira, com alguns peixes em cima das brasas. E também havia pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Então Jesus disse: — Tragam alguns desses peixes que vocês acabaram de pescar.

[[v43-21-11]]

^<<v43-21-11,11>>^ Aí Simão Pedro subiu no barco e arrastou a rede para a terra. Ela estava cheia, com cento e cinquenta e três peixes grandes, e mesmo assim não se rebentou.

[[v43-21-12]]

^<<v43-21-12,12>>^ Jesus disse: — Venham comer! Nenhum deles tinha coragem de perguntar quem ele era, pois sabiam que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Então Jesus veio, pegou o pão e deu a eles. E fez a mesma coisa com os peixes.

[[v43-21-14]]

^<<v43-21-14,14>>^ Foi esta a terceira vez que Jesus, depois de ter sido ressuscitado, apareceu aos seus discípulos.

[[v43-21-15]]

^<<v43-21-15,15>>^ Quando eles acabaram de comer, Jesus perguntou a Simão Pedro: — Simão, filho de João, você me ama mais do que estes outros me amam? — Sim, o senhor sabe que eu o amo, Senhor! — respondeu ele. Então Jesus lhe disse: — Tome conta das minhas ovelhas!

[[v43-21-16]]

^<<v43-21-16,16>>^ E perguntou pela segunda vez: — Simão, filho de João, você me ama? Pedro respondeu: — Sim, o senhor sabe que eu o amo, Senhor! E Jesus lhe disse outra vez: — Tome conta das minhas ovelhas!

[[v43-21-17]]

^<<v43-21-17,17>>^ E perguntou pela terceira vez: — Simão, filho de João, você me ama? Então Pedro ficou triste por Jesus ter perguntado três vezes: "Você me ama?" E respondeu: — O senhor sabe tudo e sabe que eu o amo, Senhor! E Jesus ordenou: — Tome conta das minhas ovelhas.

[[v43-21-18]]

^<<v43-21-18,18>>^ Quando você era moço, você se aprontava e ia para onde queria. Mas eu afirmo a você que isto é verdade: quando for velho, você estenderá as mãos, alguém vai amarrá-las e o levará para onde você não vai querer ir.

[[v43-21-19]]

^<<v43-21-19,19>>^ Ao dizer isso, Jesus estava dando a entender de que modo Pedro ia morrer e assim fazer com que Deus fosse louvado. Então Jesus disse a Pedro: — Venha comigo!

[[v43-21-20]]

^<<v43-21-20,20>>^ Então Pedro virou para trás e viu que o discípulo que Jesus amava vinha atrás dele. Este era o mesmo que estava ao lado de Jesus durante o jantar da Páscoa  e que havia chegado para mais perto dele e perguntado: "Senhor, quem é o traidor?"

[[v43-21-21]]

^<<v43-21-21,21>>^ Quando Pedro viu aquele discípulo, perguntou a Jesus: — O que diz, Senhor, a respeito deste aqui?

[[v43-21-22]]

^<<v43-21-22,22>>^ Jesus respondeu: — Se eu quiser que ele viva até que eu volte, o que é que você tem com isso? Venha comigo!

[[v43-21-23]]

^<<v43-21-23,23>>^ Então se espalhou entre os seguidores de Jesus a notícia de que aquele discípulo não ia morrer. Mas Jesus não disse isso. Ele apenas disse: "Se eu quiser que ele viva até que eu volte, o que é que você tem com isso?"

[[v43-21-24]]

^<<v43-21-24,24>>^ Este é o discípulo que falou destas coisas e as escreveu. E nós sabemos que o que ele disse é verdade.

[[v43-21-25]]

^<<v43-21-25,25>>^ Ainda há muitas outras coisas que Jesus fez. Se todas elas fossem escritas, uma por uma, acho que nem no mundo inteiro caberiam os livros que seriam escritos.

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]