include::./index.adoc[]

[[v43-9-0]]
=== João, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-9-1]]

^<<v43-9-1,1>>^ Jesus ia caminhando quando viu um homem que tinha nascido cego.

[[v43-9-2]]

^<<v43-9-2,2>>^ Os seus discípulos perguntaram: — Mestre, por que este homem nasceu cego? Foi por causa dos pecados dele ou por causa dos pecados dos pais dele?

[[v43-9-3]]

^<<v43-9-3,3>>^ Jesus respondeu: — Ele é cego, sim, mas não por causa dos pecados dele nem por causa dos pecados dos pais dele. É cego para que o poder de Deus se mostre nele.

[[v43-9-4]]

^<<v43-9-4,4>>^ Precisamos trabalhar enquanto é dia, para fazer as obras daquele que me enviou. Pois está chegando a noite, quando ninguém pode trabalhar.

[[v43-9-5]]

^<<v43-9-5,5>>^ Enquanto estou no mundo, eu sou a luz do mundo.

[[v43-9-6]]

^<<v43-9-6,6>>^ Depois de dizer isso, Jesus cuspiu no chão, fez um pouco de lama com a saliva, passou a lama nos olhos do cego

[[v43-9-7]]

^<<v43-9-7,7>>^ e disse: — Vá lavar o rosto no tanque de Siloé.  (Este nome quer dizer "Aquele que Foi Enviado".) O cego foi, lavou o rosto e voltou vendo.

[[v43-9-8]]

^<<v43-9-8,8>>^ Os seus vizinhos e as pessoas que costumavam vê-lo pedindo esmola perguntavam: — Não é este o homem que ficava sentado pedindo esmola?

[[v43-9-9]]

^<<v43-9-9,9>>^ — É! — diziam alguns. — Não, não é. Mas é parecido com ele! — afirmavam outros. Porém ele dizia: — Sou eu mesmo.

[[v43-9-10]]

^<<v43-9-10,10>>^ — Como é que agora você pode ver? — perguntaram.

[[v43-9-11]]

^<<v43-9-11,11>>^ Ele respondeu: — O homem chamado Jesus fez um pouco de lama, passou a lama nos meus olhos e disse: "Vá ao tanque de Siloé e lave o rosto." Então eu fui, lavei o rosto e fiquei vendo.

[[v43-9-12]]

^<<v43-9-12,12>>^ — Onde está esse homem? — perguntaram. — Não sei! — respondeu ele.

[[v43-9-13]]

^<<v43-9-13,13>>^ Então levaram aos fariseus  o homem que havia sido cego.

[[v43-9-14]]

^<<v43-9-14,14>>^ O dia em que Jesus havia feito lama e curado o homem da cegueira era um sábado.

[[v43-9-15]]

^<<v43-9-15,15>>^ Aí os fariseus também perguntaram como ele tinha sido curado. — Ele pôs lama nos meus olhos, eu lavei o rosto e agora estou vendo — respondeu o homem.

[[v43-9-16]]

^<<v43-9-16,16>>^ Alguns fariseus disseram: — O homem que fez isso não é de Deus porque não respeita a lei  do sábado. E outros perguntaram: — Como pode um pecador fazer milagres tão grandes? E por causa disso houve divisão entre eles.

[[v43-9-17]]

^<<v43-9-17,17>>^ Então os fariseus tornaram a perguntar ao homem: — Você diz que ele curou você da cegueira. E o que é que você diz dele? — Ele é um profeta ! — respondeu o homem.

[[v43-9-18]]

^<<v43-9-18,18>>^ Os líderes judeus não acreditavam que ele tinha sido cego e que agora podia ver. Por isso chamaram os pais dele

[[v43-9-19]]

^<<v43-9-19,19>>^ e perguntaram: — Esse homem é filho de vocês? Vocês dizem que ele nasceu cego. E como é que agora ele está vendo?

[[v43-9-20]]

^<<v43-9-20,20>>^ Os pais responderam: — Sabemos que ele é nosso filho e que nasceu cego.

[[v43-9-21]]

^<<v43-9-21,21>>^ Mas não sabemos como é que ele agora pode ver e não sabemos também quem foi que o curou. Ele é maior de idade; perguntem, e ele mesmo poderá explicar.

[[v43-9-22]]

^<<v43-9-22,22>>^ Os pais disseram isso porque estavam com medo, pois os líderes judeus tinham combinado expulsar da sinagoga  quem afirmasse que Jesus era o Messias .

[[v43-9-23]]

^<<v43-9-23,23>>^ Foi por isso que os pais disseram: "Ele é maior de idade; perguntem a ele."

[[v43-9-24]]

^<<v43-9-24,24>>^ Então os líderes judeus chamaram pela segunda vez o homem que tinha sido cego e disseram: — Jure por Deus que você vai dizer a verdade. Nós sabemos que esse homem é pecador.

[[v43-9-25]]

^<<v43-9-25,25>>^ Ele respondeu: — Se ele é pecador, eu não sei. De uma coisa eu sei: eu era cego e agora vejo!

[[v43-9-26]]

^<<v43-9-26,26>>^ — O que foi que ele fez a você? Como curou você da cegueira? — tornaram a perguntar.

[[v43-9-27]]

^<<v43-9-27,27>>^ O homem respondeu: — Eu já disse, e vocês não acreditaram. Por que querem ouvir isso outra vez? Por acaso vocês também querem ser seguidores dele?

[[v43-9-28]]

^<<v43-9-28,28>>^ Então eles o xingaram e disseram: — Você é que é seguidor dele! Nós somos seguidores de Moisés.

[[v43-9-29]]

^<<v43-9-29,29>>^ Sabemos que Deus falou com Moisés; mas este homem, nós nem mesmo sabemos de onde ele é.

[[v43-9-30]]

^<<v43-9-30,30>>^ Ele respondeu: — Que coisa esquisita! Vocês não sabem de onde ele é, mas ele me curou.

[[v43-9-31]]

^<<v43-9-31,31>>^ Sabemos que Deus não atende pecadores, mas ele atende os que o respeitam e fazem a sua vontade.

[[v43-9-32]]

^<<v43-9-32,32>>^ Desde que o mundo existe, nunca se ouviu dizer que alguém tivesse curado um cego de nascença.

[[v43-9-33]]

^<<v43-9-33,33>>^ Se esse homem não fosse enviado por Deus, não teria podido fazer nada.

[[v43-9-34]]

^<<v43-9-34,34>>^ Eles disseram: — Você nasceu cheio de pecado e é você que quer nos ensinar? E o expulsaram da sinagoga.

[[v43-9-35]]

^<<v43-9-35,35>>^ Jesus ficou sabendo que tinham expulsado o homem da sinagoga . Foi procurá-lo e, quando o encontrou, perguntou: — Você crê no Filho do Homem ?

[[v43-9-36]]

^<<v43-9-36,36>>^ Ele respondeu: — Senhor, quem é o Filho do Homem para que eu creia nele?

[[v43-9-37]]

^<<v43-9-37,37>>^ Jesus disse: — Você já o viu! É ele que está falando com você!

[[v43-9-38]]

^<<v43-9-38,38>>^ — Eu creio, Senhor! — disse o homem. E se ajoelhou diante dele.

[[v43-9-39]]

^<<v43-9-39,39>>^ Então Jesus afirmou: — Eu vim a este mundo para julgar as pessoas, a fim de que os cegos vejam e que fiquem cegos os que veem.

[[v43-9-40]]

^<<v43-9-40,40>>^ Alguns fariseus  que estavam com ele ouviram isso e perguntaram: — Será que isso quer dizer que nós também somos cegos?

[[v43-9-41]]

^<<v43-9-41,41>>^ — Se vocês fossem cegos, não teriam culpa!  — respondeu Jesus. — Mas, como dizem que podem ver, então continuam tendo culpa.

'''

xref:043-joao/043-joao-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-joao/043-joao-010.adoc#v43-10-0[Próximo Capítulo &#62;]