include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-8-1]]

^<<v43-8-1,1>>^ [Depois todos foram para casa, mas Jesus foi para o monte das Oliveiras.

[[v43-8-2]]

^<<v43-8-2,2>>^ De madrugada ele voltou ao pátio do Templo, e o povo se reuniu em volta dele. Jesus estava sentado, ensinando a todos.

[[v43-8-3]]

^<<v43-8-3,3>>^ Aí alguns mestres  da Lei e fariseus  levaram a Jesus uma mulher que tinha sido apanhada em adultério e a obrigaram a ficar de pé no meio de todos.

[[v43-8-4]]

^<<v43-8-4,4>>^ Eles disseram: — Mestre, esta mulher foi apanhada no ato de adultério.

[[v43-8-5]]

^<<v43-8-5,5>>^ De acordo com a Lei  que Moisés nos deu, as mulheres adúlteras devem ser mortas a pedradas. Mas o senhor, o que é que diz sobre isso?

[[v43-8-6]]

^<<v43-8-6,6>>^ Eles fizeram essa pergunta para conseguir uma prova contra Jesus, pois queriam acusá-lo. Mas ele se abaixou e começou a escrever no chão com o dedo.

[[v43-8-7]]

^<<v43-8-7,7>>^ Como eles continuaram a fazer a mesma pergunta, Jesus endireitou o corpo e disse a eles: — Quem de vocês estiver sem pecado, que seja o primeiro a atirar uma pedra nesta mulher!

[[v43-8-8]]

^<<v43-8-8,8>>^ Depois abaixou-se outra vez e continuou a escrever no chão.

[[v43-8-9]]

^<<v43-8-9,9>>^ Quando ouviram isso, todos foram embora, um por um, começando pelos mais velhos. Ficaram só Jesus e a mulher, e ela continuou ali, de pé.

[[v43-8-10]]

^<<v43-8-10,10>>^ Então Jesus endireitou o corpo e disse: — Mulher, onde estão eles? Não ficou ninguém para condenar você?

[[v43-8-11]]

^<<v43-8-11,11>>^ — Ninguém, senhor! — respondeu ela. Jesus disse: — Pois eu também não condeno você. Vá e não peque mais!]

[[v43-8-12]]

^<<v43-8-12,12>>^ De novo Jesus começou a falar com eles e disse: — Eu sou a luz do mundo; quem me segue nunca andará na escuridão, mas terá a luz da vida.

[[v43-8-13]]

^<<v43-8-13,13>>^ Os fariseus  disseram a Jesus: — Agora você está falando a favor de você mesmo. Por isso o que você diz não tem valor.

[[v43-8-14]]

^<<v43-8-14,14>>^ Jesus respondeu: — Embora eu esteja falando a favor de mim mesmo, o que digo tem valor porque é a verdade. Pois eu sei de onde vim e para onde vou, mas vocês não sabem de onde vim, nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vocês julgam de modo puramente humano; mas eu não julgo ninguém.

[[v43-8-16]]

^<<v43-8-16,16>>^ E, se eu julgar, o meu julgamento é verdadeiro porque não julgo sozinho, pois o Pai, que me enviou, está comigo.

[[v43-8-17]]

^<<v43-8-17,17>>^ Na Lei  de vocês está escrito que, quando duas testemunhas concordam, o que dizem é verdade.

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu dou testemunho a respeito de mim mesmo, e o Pai, que me enviou, também dá testemunho a meu respeito.

[[v43-8-19]]

^<<v43-8-19,19>>^ — Onde está o seu pai? — perguntaram. Jesus respondeu: — Vocês não me conhecem e também não conhecem o meu Pai. Se, de fato, me conhecessem, conheceriam também o meu Pai.

[[v43-8-20]]

^<<v43-8-20,20>>^ Jesus disse essas coisas quando estava ensinando no pátio do Templo, perto da caixa das ofertas. Ninguém o prendeu porque ainda não tinha chegado a sua hora.

[[v43-8-21]]

^<<v43-8-21,21>>^ Jesus disse outra vez: — Eu vou embora, e vocês vão me procurar, porém morrerão sem o perdão dos seus pecados. Para onde eu vou vocês não podem ir.

[[v43-8-22]]

^<<v43-8-22,22>>^ Os líderes judeus disseram: — Ele diz que nós não podemos ir para onde ele vai! Será que ele vai se matar?

[[v43-8-23]]

^<<v43-8-23,23>>^ Jesus continuou: — Vocês são daqui debaixo, e eu sou lá de cima. Vocês são deste mundo, mas eu não sou deste mundo.

[[v43-8-24]]

^<<v43-8-24,24>>^ Por isso eu disse que vocês vão morrer sem o perdão dos seus pecados. De fato, morrerão sem o perdão dos seus pecados se não crerem que " Eu Sou Quem Sou ".

[[v43-8-25]]

^<<v43-8-25,25>>^ — Quem é você? — perguntaram a Jesus. Ele respondeu: — Desde o começo eu disse quem sou.

[[v43-8-26]]

^<<v43-8-26,26>>^ Existem muitas coisas a respeito de vocês das quais eu preciso falar e as quais eu preciso julgar. Porém quem me enviou é verdadeiro, e eu digo ao mundo somente o que ele me disse.

[[v43-8-27]]

^<<v43-8-27,27>>^ Eles não entenderam que ele estava falando a respeito do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Por isso Jesus disse: — Quando vocês levantarem o Filho do Homem , saberão que " Eu Sou Quem Sou ". E saberão também que não faço nada por minha conta, mas falo somente o que o meu Pai me ensinou.

[[v43-8-29]]

^<<v43-8-29,29>>^ Quem me enviou está comigo e não me deixou sozinho, pois faço sempre o que lhe agrada.

[[v43-8-30]]

^<<v43-8-30,30>>^ Quando Jesus disse isso, muitos creram nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Então Jesus disse para os que creram nele: — Se vocês continuarem a obedecer aos meus ensinamentos, serão, de fato, meus discípulos

[[v43-8-32]]

^<<v43-8-32,32>>^ e conhecerão a verdade, e a verdade os libertará.

[[v43-8-33]]

^<<v43-8-33,33>>^ Eles responderam: — Nós somos descendentes de Abraão e nunca fomos escravos de ninguém. Como é que você diz que ficaremos livres?

[[v43-8-34]]

^<<v43-8-34,34>>^ Jesus disse a eles: — Eu afirmo a vocês que isto é verdade: quem peca é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ O escravo não fica sempre com a família, mas o filho sempre faz parte da família.

[[v43-8-36]]

^<<v43-8-36,36>>^ Se o Filho os libertar, vocês serão, de fato, livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Eu sei que vocês são descendentes de Abraão; porém estão tentando me matar porque não aceitam os meus ensinamentos.

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu falo das coisas que o meu Pai me mostrou, mas vocês fazem o que aprenderam com o pai de vocês.

[[v43-8-39]]

^<<v43-8-39,39>>^ — O nosso pai é Abraão! — responderam eles. Então Jesus disse: — Se vocês fossem, de fato, filhos de Abraão, fariam o que ele fez.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas eu lhes tenho dito a verdade que ouvi de Deus, e assim mesmo vocês estão tentando me matar. Abraão nunca fez uma coisa assim!

[[v43-8-41]]

^<<v43-8-41,41>>^ Vocês estão fazendo o que o pai de vocês fez. Eles responderam: — Nós não somos filhos ilegítimos; nós temos um Pai, que é Deus!

[[v43-8-42]]

^<<v43-8-42,42>>^ Jesus disse a eles: — Se Deus fosse, de fato, o Pai de vocês, então vocês me amariam, pois eu vim de Deus e agora estou aqui. Eu não vim por minha própria conta, mas foi Deus que me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Por que é que vocês não entendem o que eu digo? É porque não querem ouvir a minha mensagem.

[[v43-8-44]]

^<<v43-8-44,44>>^ Vocês são filhos do Diabo e querem fazer o que o pai de vocês quer. Desde a criação do mundo ele foi assassino e nunca esteve do lado da verdade porque nele não existe verdade. Quando o Diabo mente, está apenas fazendo o que é o seu costume, pois é mentiroso e é o pai de todas as mentiras.

[[v43-8-45]]

^<<v43-8-45,45>>^ Mas, porque eu digo a verdade, vocês não creem em mim.

[[v43-8-46]]

^<<v43-8-46,46>>^ Qual de vocês pode provar que eu tenho algum pecado? Se digo a verdade, por que não creem em mim?

[[v43-8-47]]

^<<v43-8-47,47>>^ A pessoa que é de Deus escuta as palavras de Deus. Vocês não escutam as palavras de Deus porque vocês não são dele.

[[v43-8-48]]

^<<v43-8-48,48>>^ Eles disseram a Jesus: — Por acaso não temos razão quando dizemos que você é samaritano  e está dominado por um demônio?

[[v43-8-49]]

^<<v43-8-49,49>>^ Jesus respondeu: — Eu não estou dominado por nenhum demônio. Respeito o meu Pai, mas vocês me desrespeitam.

[[v43-8-50]]

^<<v43-8-50,50>>^ Não procuro conseguir elogios para mim mesmo; mas existe alguém que procura consegui-los para mim, e ele é o Juiz.

[[v43-8-51]]

^<<v43-8-51,51>>^ Eu afirmo a vocês que isto é verdade: quem obedecer aos meus ensinamentos não morrerá nunca.

[[v43-8-52]]

^<<v43-8-52,52>>^ Então eles disseram: — Agora temos a certeza de que você está dominado por um demônio! Abraão e todos os profetas  morreram, mas você diz: "Quem obedecer aos meus ensinamentos não morrerá nunca."

[[v43-8-53]]

^<<v43-8-53,53>>^ Será que você é mais importante do que Abraão, o nosso pai, que morreu? E os profetas também morreram! Quem você pensa que é?

[[v43-8-54]]

^<<v43-8-54,54>>^ Ele respondeu: — Se eu elogiasse a mim mesmo, os meus elogios não valeriam nada. Quem me elogia é o meu Pai, o mesmo que vocês dizem que é o Deus de vocês.

[[v43-8-55]]

^<<v43-8-55,55>>^ Vocês nunca conheceram a Deus, mas eu o conheço. Se eu disser que não o conheço, serei mentiroso como vocês; mas eu o conheço e obedeço ao que ele manda.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, o pai de vocês, ficou alegre ao ver o tempo da minha vinda. Ele viu esse tempo e ficou feliz.

[[v43-8-57]]

^<<v43-8-57,57>>^ — Você não tem nem cinquenta anos e viu Abraão? — perguntaram eles.

[[v43-8-58]]

^<<v43-8-58,58>>^ — Eu afirmo a vocês que isto é verdade: antes de Abraão nascer, " Eu Sou "!  — respondeu Jesus.

[[v43-8-59]]

^<<v43-8-59,59>>^ Então eles pegaram pedras para atirar em Jesus, mas ele se escondeu e saiu do pátio do Templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]