include::./index.adoc[]

[[v43-11-0]]
=== João, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-11-1]]

^<<v43-11-1,1>>^ Um homem chamado Lázaro estava doente. Ele era do povoado de Betânia, onde Maria e a sua irmã Marta moravam.

[[v43-11-2]]

^<<v43-11-2,2>>^ (Esta Maria era a mesma que pôs perfume nos pés do Senhor Jesus e os enxugou com os seus cabelos. Era o irmão dela, Lázaro, que estava doente.)

[[v43-11-3]]

^<<v43-11-3,3>>^ As duas irmãs mandaram dizer a Jesus: — Senhor, o seu querido amigo Lázaro está doente!

[[v43-11-4]]

^<<v43-11-4,4>>^ Quando Jesus recebeu a notícia, disse: — O resultado final dessa doença não será a morte de Lázaro. Isso está acontecendo para que Deus revele o seu poder glorioso ; e assim, por causa dessa doença, a natureza divina do Filho de Deus será revelada.

[[v43-11-5]]

^<<v43-11-5,5>>^ Jesus amava muito Marta, e a sua irmã, e também Lázaro.

[[v43-11-6]]

^<<v43-11-6,6>>^ Porém quando soube que Lázaro estava doente, ainda ficou dois dias onde estava.

[[v43-11-7]]

^<<v43-11-7,7>>^ Então disse aos seus discípulos: — Vamos voltar para a Judeia.

[[v43-11-8]]

^<<v43-11-8,8>>^ Mas eles disseram: — Mestre, faz tão pouco tempo que o povo de lá queria matá-lo a pedradas, e o senhor quer voltar?

[[v43-11-9]]

^<<v43-11-9,9>>^ Jesus respondeu: — Por acaso o dia não tem doze horas? Se alguém anda de dia não tropeça porque vê a luz deste mundo.

[[v43-11-10]]

^<<v43-11-10,10>>^ Mas, se anda de noite, tropeça porque nele não existe luz.

[[v43-11-11]]

^<<v43-11-11,11>>^ Jesus disse isso e depois continuou: — O nosso amigo Lázaro está dormindo, mas eu vou lá acordá-lo.

[[v43-11-12]]

^<<v43-11-12,12>>^ — Senhor, se ele está dormindo, isso quer dizer que vai ficar bom! — disseram eles.

[[v43-11-13]]

^<<v43-11-13,13>>^ Mas o que Jesus queria dizer era que Lázaro estava morto. Porém eles pensavam que ele estivesse falando do sono natural.

[[v43-11-14]]

^<<v43-11-14,14>>^ Então Jesus disse claramente: — Lázaro morreu,

[[v43-11-15]]

^<<v43-11-15,15>>^ mas eu estou alegre por não ter estado lá com ele, pois assim vocês vão crer. Vamos até a casa dele.

[[v43-11-16]]

^<<v43-11-16,16>>^ Então Tomé, chamado "o Gêmeo", disse aos outros discípulos: — Vamos nós também a fim de morrer com o Mestre!

[[v43-11-17]]

^<<v43-11-17,17>>^ Quando Jesus chegou, já fazia quatro dias que Lázaro havia sido sepultado.

[[v43-11-18]]

^<<v43-11-18,18>>^ Betânia ficava a menos de três quilômetros de Jerusalém,

[[v43-11-19]]

^<<v43-11-19,19>>^ e muitas pessoas tinham vindo visitar Marta e Maria para as consolarem por causa da morte do irmão.

[[v43-11-20]]

^<<v43-11-20,20>>^ Quando Marta soube que Jesus estava chegando, foi encontrar-se com ele. Porém Maria ficou sentada em casa.

[[v43-11-21]]

^<<v43-11-21,21>>^ Então Marta disse a Jesus: — Se o senhor estivesse aqui, o meu irmão não teria morrido!

[[v43-11-22]]

^<<v43-11-22,22>>^ Mas eu sei que, mesmo assim, Deus lhe dará tudo o que o senhor pedir a ele.

[[v43-11-23]]

^<<v43-11-23,23>>^ — O seu irmão vai ressuscitar!  — disse Jesus.

[[v43-11-24]]

^<<v43-11-24,24>>^ Marta respondeu: — Eu sei que ele vai ressuscitar no último dia!

[[v43-11-25]]

^<<v43-11-25,25>>^ Então Jesus afirmou: — Eu sou a ressurreição e a vida. Quem crê em mim, ainda que morra, viverá;

[[v43-11-26]]

^<<v43-11-26,26>>^ e quem vive e crê em mim nunca morrerá. Você acredita nisso?

[[v43-11-27]]

^<<v43-11-27,27>>^ — Sim, senhor! — disse ela. — Eu creio que o senhor é o Messias , o Filho de Deus, que devia vir ao mundo.

[[v43-11-28]]

^<<v43-11-28,28>>^ Depois de dizer isso, Marta foi, chamou Maria, a sua irmã, e lhe disse em particular: — O Mestre chegou e está chamando você.

[[v43-11-29]]

^<<v43-11-29,29>>^ Quando Maria ouviu isso, levantou-se depressa e foi encontrar-se com Jesus.

[[v43-11-30]]

^<<v43-11-30,30>>^ Pois ele não tinha chegado ao povoado, mas ainda estava no lugar onde Marta o havia encontrado.

[[v43-11-31]]

^<<v43-11-31,31>>^ As pessoas que estavam na casa com Maria, consolando-a, viram que ela se levantou e saiu depressa. Então foram atrás dela, pois pensavam que ela ia ao túmulo para chorar ali.

[[v43-11-32]]

^<<v43-11-32,32>>^ Maria chegou ao lugar onde Jesus estava e logo que o viu caiu aos pés dele e disse: — Se o senhor tivesse estado aqui, o meu irmão não teria morrido!

[[v43-11-33]]

^<<v43-11-33,33>>^ Jesus viu Maria chorando e viu as pessoas que estavam com ela chorando também. Então ficou muito comovido e aflito

[[v43-11-34]]

^<<v43-11-34,34>>^ e perguntou: — Onde foi que vocês o sepultaram? — Venha ver, senhor! — responderam.

[[v43-11-35]]

^<<v43-11-35,35>>^ Jesus chorou.

[[v43-11-36]]

^<<v43-11-36,36>>^ Então as pessoas disseram: — Vejam como ele amava Lázaro!

[[v43-11-37]]

^<<v43-11-37,37>>^ Mas algumas delas disseram: — Ele curou o cego. Será que não poderia ter feito alguma coisa para que Lázaro não morresse?

[[v43-11-38]]

^<<v43-11-38,38>>^ Jesus ficou outra vez muito comovido. Ele foi até o túmulo, que era uma gruta com uma pedra colocada na entrada,

[[v43-11-39]]

^<<v43-11-39,39>>^ e ordenou: — Tirem a pedra! Marta, a irmã do morto, disse: — Senhor, ele está cheirando mal, pois já faz quatro dias que foi sepultado!

[[v43-11-40]]

^<<v43-11-40,40>>^ Jesus respondeu: — Eu não lhe disse que, se você crer, você verá a revelação do poder glorioso  de Deus?

[[v43-11-41]]

^<<v43-11-41,41>>^ Então tiraram a pedra. Jesus olhou para o céu e disse: — Pai, eu te agradeço porque me ouviste.

[[v43-11-42]]

^<<v43-11-42,42>>^ Eu sei que sempre me ouves; mas eu estou dizendo isso por causa de toda esta gente que está aqui, para que eles creiam que tu me enviaste.

[[v43-11-43]]

^<<v43-11-43,43>>^ Depois de dizer isso, gritou: — Lázaro, venha para fora!

[[v43-11-44]]

^<<v43-11-44,44>>^ E o morto saiu. Os seus pés e as suas mãos estavam enfaixados com tiras de pano, e o seu rosto estava enrolado com um pano. Então Jesus disse: — Desenrolem as faixas e deixem que ele vá.

[[v43-11-45]]

^<<v43-11-45,45>>^ Muitas pessoas que tinham ido visitar Maria viram o que Jesus tinha feito e creram nele.

[[v43-11-46]]

^<<v43-11-46,46>>^ Mas algumas pessoas voltaram e contaram aos fariseus  o que ele havia feito.

[[v43-11-47]]

^<<v43-11-47,47>>^ Então os fariseus e os chefes dos sacerdotes se reuniram com o Conselho Superior  e disseram: — O que é que nós vamos fazer? Esse homem está fazendo muitos milagres!

[[v43-11-48]]

^<<v43-11-48,48>>^ Se deixarmos que ele continue fazendo essas coisas, todos vão crer nele. Aí as autoridades romanas agirão contra nós e destruirão o Templo e o nosso país.

[[v43-11-49]]

^<<v43-11-49,49>>^ Então Caifás, que naquele ano era o Grande Sacerdote , disse: — Vocês não sabem nada!

[[v43-11-50]]

^<<v43-11-50,50>>^ Será que não entendem que para vocês é melhor que morra apenas um homem pelo povo do que deixar que o país todo seja destruído?

[[v43-11-51]]

^<<v43-11-51,51>>^ Naquele momento Caifás não estava falando por si mesmo. Mas, como ele era o Grande Sacerdote naquele ano, estava profetizando  que Jesus ia morrer pela nação.

[[v43-11-52]]

^<<v43-11-52,52>>^ E não somente pela nação, mas também para reunir em um só corpo todos os filhos de Deus que estão espalhados por toda parte.

[[v43-11-53]]

^<<v43-11-53,53>>^ Então, daquele dia em diante, os líderes judeus fizeram planos para matar Jesus.

[[v43-11-54]]

^<<v43-11-54,54>>^ Por isso ele já não andava publicamente na Judeia, mas foi para uma região perto do deserto, a uma cidade chamada Efraim, e ficou ali com os seus discípulos.

[[v43-11-55]]

^<<v43-11-55,55>>^ Faltava pouco tempo para a Festa da Páscoa . Muitos judeus foram a Jerusalém antes da festa para tomar parte na cerimônia de purificação .

[[v43-11-56]]

^<<v43-11-56,56>>^ Eles procuravam Jesus e, no pátio do Templo, perguntavam uns aos outros: — O que é que vocês acham? Será que ele vem à festa?

[[v43-11-57]]

^<<v43-11-57,57>>^ Os chefes dos sacerdotes e os fariseus queriam prender Jesus. Por isso tinham dado ordem para que, se alguém soubesse, contasse onde ele estava.

'''

xref:043-joao/043-joao-010.adoc#v43-10-0[&#60; Capítulo Anterior] | <<v43-11-0,Topo>> | xref:043-joao/043-joao-012.adoc#v43-12-0[Próximo Capítulo &#62;]