include::./index.adoc[]

[[v43-1-0]]
=== João, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-1-1]]

^<<v43-1-1,1>>^ No começo aquele que é a Palavra já existia. Ele estava com Deus e era Deus.

[[v43-1-2]]

^<<v43-1-2,2>>^ Desde o princípio, a Palavra estava com Deus.

[[v43-1-3]]

^<<v43-1-3,3>>^ Por meio da Palavra, Deus fez todas as coisas, e nada do que existe foi feito sem ela.

[[v43-1-4]]

^<<v43-1-4,4>>^ A Palavra era a fonte da vida, e essa vida trouxe a luz para todas as pessoas.

[[v43-1-5]]

^<<v43-1-5,5>>^ A luz brilha na escuridão, e a escuridão não conseguiu apagá-la.

[[v43-1-6]]

^<<v43-1-6,6>>^ Houve um homem chamado João, que foi enviado por Deus

[[v43-1-7]]

^<<v43-1-7,7>>^ para falar a respeito da luz. Ele veio para que por meio dele todos pudessem ouvir a mensagem e crer nela.

[[v43-1-8]]

^<<v43-1-8,8>>^ João não era a luz, mas veio para falar a respeito da luz,

[[v43-1-9]]

^<<v43-1-9,9>>^ a luz verdadeira que veio ao mundo e ilumina todas as pessoas.

[[v43-1-10]]

^<<v43-1-10,10>>^ A Palavra estava no mundo, e por meio dela Deus fez o mundo, mas o mundo não a conheceu.

[[v43-1-11]]

^<<v43-1-11,11>>^ Aquele que é a Palavra veio para o seu próprio país, mas o seu povo não o recebeu.

[[v43-1-12]]

^<<v43-1-12,12>>^ Porém alguns creram nele e o receberam, e a estes ele deu o direito de se tornarem filhos de Deus.

[[v43-1-13]]

^<<v43-1-13,13>>^ Eles não se tornaram filhos de Deus pelos meios naturais, isto é, não nasceram como nascem os filhos de um pai humano; o próprio Deus é quem foi o Pai deles.

[[v43-1-14]]

^<<v43-1-14,14>>^ A Palavra se tornou um ser humano e morou entre nós, cheia de amor e de verdade. E nós vimos a revelação da sua natureza divina, natureza que ele recebeu como Filho único do Pai.

[[v43-1-15]]

^<<v43-1-15,15>>^ João disse o seguinte a respeito de Jesus: — Este é aquele de quem eu disse: "Ele vem depois de mim, mas é mais importante do que eu, pois antes de eu nascer ele já existia."

[[v43-1-16]]

^<<v43-1-16,16>>^ Porque todos nós temos sido abençoados com as riquezas do seu amor, com bênçãos e mais bênçãos.

[[v43-1-17]]

^<<v43-1-17,17>>^ A lei  foi dada por meio de Moisés, mas o amor e a verdade vieram por meio de Jesus Cristo.

[[v43-1-18]]

^<<v43-1-18,18>>^ Ninguém nunca viu Deus. Somente o Filho único, que é Deus e está ao lado do Pai, foi quem nos mostrou quem é Deus.

[[v43-1-19]]

^<<v43-1-19,19>>^ Os líderes judeus enviaram de Jerusalém alguns sacerdotes e levitas  para perguntarem a João quem ele era.

[[v43-1-20]]

^<<v43-1-20,20>>^ João afirmou claramente: — Eu não sou o Messias .

[[v43-1-21]]

^<<v43-1-21,21>>^ Eles tornaram a perguntar: — Então, quem é você? Você é Elias? — Não, eu não sou! — respondeu João. — Você é o Profeta  que estamos esperando? — Não! — respondeu ele.

[[v43-1-22]]

^<<v43-1-22,22>>^ Aí eles disseram a João: — Diga quem é você para podermos levar uma resposta aos que nos enviaram. O que é que você diz a respeito de você mesmo?

[[v43-1-23]]

^<<v43-1-23,23>>^ João respondeu, citando o profeta  Isaías: — "Eu sou aquele que grita assim no deserto: preparem o caminho para o Senhor passar."

[[v43-1-24]]

^<<v43-1-24,24>>^ Os que foram enviados eram do grupo dos fariseus ;

[[v43-1-25]]

^<<v43-1-25,25>>^ eles perguntaram a João: — Se você não é o Messias, nem Elias, nem o Profeta que estamos esperando, por que é que você batiza?

[[v43-1-26]]

^<<v43-1-26,26>>^ João respondeu: — Eu batizo com água, mas no meio de vocês está alguém que vocês não conhecem.

[[v43-1-27]]

^<<v43-1-27,27>>^ Ele vem depois de mim, mas eu não mereço a honra de desamarrar as correias das sandálias dele.

[[v43-1-28]]

^<<v43-1-28,28>>^ Isso aconteceu no povoado de Betânia, no lado leste do rio Jordão, onde João estava batizando.

[[v43-1-29]]

^<<v43-1-29,29>>^ No dia seguinte, João viu Jesus vindo na direção dele e disse: — Aí está o Cordeiro de Deus, que tira o pecado do mundo!

[[v43-1-30]]

^<<v43-1-30,30>>^ Eu estava falando a respeito dele quando disse: "Depois de mim vem um homem que é mais importante do que eu, pois antes de eu nascer ele já existia."

[[v43-1-31]]

^<<v43-1-31,31>>^ Eu mesmo não sabia quem ele era, mas vim, batizando com água para que o povo de Israel saiba quem ele é.

[[v43-1-32]]

^<<v43-1-32,32>>^ João continuou: — Eu vi o Espírito descer do céu como uma pomba e parar sobre ele.

[[v43-1-33]]

^<<v43-1-33,33>>^ Eu não sabia quem ele era, mas Deus, que me mandou batizar com água, me disse: "Você vai ver o Espírito descer e parar sobre um homem. Esse é quem batiza com o Espírito Santo."

[[v43-1-34]]

^<<v43-1-34,34>>^ E eu vi isso e por esse motivo tenho declarado que ele é o Filho de Deus.

[[v43-1-35]]

^<<v43-1-35,35>>^ No dia seguinte, João estava outra vez ali com dois dos seus discípulos.

[[v43-1-36]]

^<<v43-1-36,36>>^ Quando viu Jesus passar, disse: — Aí está o Cordeiro de Deus!

[[v43-1-37]]

^<<v43-1-37,37>>^ Quando os dois discípulos de João ouviram isso, saíram seguindo Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ Então Jesus olhou para trás, viu que eles o seguiam e perguntou: — O que é que vocês estão procurando? Eles perguntaram: — Rabi, onde é que o senhor mora? ("Rabi" quer dizer "mestre".)

[[v43-1-39]]

^<<v43-1-39,39>>^ — Venham ver!  — disse Jesus. Então eles foram, viram onde Jesus estava morando e ficaram com ele o resto daquele dia. Isso aconteceu mais ou menos às quatro horas da tarde.

[[v43-1-40]]

^<<v43-1-40,40>>^ André, irmão de Simão Pedro, era um dos dois homens que tinham ouvido João falar a respeito de Jesus e por isso o haviam seguido.

[[v43-1-41]]

^<<v43-1-41,41>>^ A primeira coisa que André fez foi procurar o seu irmão Simão e dizer a ele: — Achamos o Messias . ("Messias" quer dizer "Cristo".)

[[v43-1-42]]

^<<v43-1-42,42>>^ Então André levou o seu irmão a Jesus. Jesus olhou para Simão e disse: — Você é Simão, filho de João, mas de agora em diante o seu nome será Cefas.  ("Cefas" é o mesmo que "Pedro" e quer dizer "pedra".)

[[v43-1-43]]

^<<v43-1-43,43>>^ No dia seguinte, Jesus resolveu ir para a região da Galileia. Antes de ir, foi procurar Filipe e disse: — Venha comigo!

[[v43-1-44]]

^<<v43-1-44,44>>^ Filipe era de Betsaida, de onde eram também André e Pedro.

[[v43-1-45]]

^<<v43-1-45,45>>^ Filipe foi procurar Natanael e disse: — Achamos aquele a respeito de quem Moisés escreveu no Livro da Lei  e sobre quem os profetas  também escreveram. É Jesus, filho de José, da cidade de Nazaré.

[[v43-1-46]]

^<<v43-1-46,46>>^ Natanael perguntou: — E será que pode sair alguma coisa boa de Nazaré? — Venha ver! — respondeu Filipe.

[[v43-1-47]]

^<<v43-1-47,47>>^ Quando Jesus viu Natanael chegando, disse a respeito dele: — Aí está um verdadeiro israelita, um homem realmente sincero.

[[v43-1-48]]

^<<v43-1-48,48>>^ Então Natanael perguntou a Jesus: — De onde o senhor me conhece? Jesus respondeu: — Antes que Filipe chamasse você, eu já tinha visto você sentado debaixo daquela figueira.

[[v43-1-49]]

^<<v43-1-49,49>>^ Então Natanael exclamou: — Mestre, o senhor é o Filho de Deus! O senhor é o Rei de Israel!

[[v43-1-50]]

^<<v43-1-50,50>>^ Jesus respondeu: — Você crê em mim só porque eu disse que tinha visto você debaixo da figueira? Pois você verá coisas maiores do que esta.

[[v43-1-51]]

^<<v43-1-51,51>>^ Eu afirmo a vocês que isto é verdade: vocês verão o céu aberto e os anjos de Deus subindo e descendo sobre o Filho do Homem .

'''

xref:042-lucas/042-lucas-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-joao/043-joao-002.adoc#v43-2-0[Próximo Capítulo &#62;]