include::./index.adoc[]

[[v43-19-0]]
=== João, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-19-1]]

^<<v43-19-1,1>>^ Aí Pilatos mandou chicotear Jesus.

[[v43-19-2]]

^<<v43-19-2,2>>^ Depois os soldados fizeram uma coroa de ramos cheios de espinhos, e a puseram na cabeça dele, e o vestiram com uma capa  vermelha.

[[v43-19-3]]

^<<v43-19-3,3>>^ Chegavam perto dele e diziam: — Viva o rei dos judeus! E davam bofetadas nele.

[[v43-19-4]]

^<<v43-19-4,4>>^ Aí Pilatos saiu outra vez e disse para a multidão: — Escutem! Vou trazer o homem aqui para que vocês saibam que não encontro nenhum motivo para condená-lo!

[[v43-19-5]]

^<<v43-19-5,5>>^ Então Jesus saiu com a coroa de espinhos na cabeça e vestido com a capa vermelha. — Vejam! Aqui está o homem! — disse Pilatos.

[[v43-19-6]]

^<<v43-19-6,6>>^ Quando os chefes dos sacerdotes e os guardas do Templo viram Jesus, começaram a gritar: — Crucifica! Crucifica! — Vocês que o levem e o crucifiquem! Eu não encontro nenhum motivo para condenar este homem! — repetiu Pilatos.

[[v43-19-7]]

^<<v43-19-7,7>>^ A multidão respondeu: — Nós temos uma Lei , e ela diz que este homem deve morrer porque afirma que é o Filho de Deus.

[[v43-19-8]]

^<<v43-19-8,8>>^ Quando Pilatos ouviu isso, ficou com mais medo ainda.

[[v43-19-9]]

^<<v43-19-9,9>>^ Entrou outra vez no palácio e perguntou a Jesus: — De onde você é? Mas Jesus não respondeu nada.

[[v43-19-10]]

^<<v43-19-10,10>>^ Então Pilatos disse: — Você não quer falar comigo? Lembre que eu tenho autoridade tanto para soltá-lo como para mandar crucificá-lo.

[[v43-19-11]]

^<<v43-19-11,11>>^ Jesus respondeu: — O senhor só tem autoridade sobre mim porque ela lhe foi dada por Deus. Por isso aquele que me entregou ao senhor é culpado de um pecado maior.

[[v43-19-12]]

^<<v43-19-12,12>>^ Depois disso Pilatos quis soltar Jesus. Mas a multidão gritou: — Se o senhor soltar esse homem, não é amigo do Imperador! Pois quem diz que é rei é inimigo do Imperador!

[[v43-19-13]]

^<<v43-19-13,13>>^ Quando Pilatos ouviu isso, trouxe Jesus para fora e sentou-se no tribunal, no lugar chamado "Calçada de Pedra". (Em hebraico  o nome desse lugar é "Gabatá".)

[[v43-19-14]]

^<<v43-19-14,14>>^ Era quase meio-dia da véspera da Páscoa . Pilatos disse para a multidão: — Aqui está o rei de vocês!

[[v43-19-15]]

^<<v43-19-15,15>>^ Mas eles gritaram: — Mata! Mata! Crucifica! Então Pilatos perguntou: — Querem que eu crucifique o rei de vocês? Mas os chefes dos sacerdotes responderam: — O nosso único rei é o Imperador!

[[v43-19-16]]

^<<v43-19-16,16>>^ Então Pilatos entregou Jesus aos soldados para ser crucificado, e eles o levaram.

[[v43-19-17]]

^<<v43-19-17,17>>^ Jesus saiu carregando ele mesmo a cruz para o lugar chamado Calvário . (Em hebraico  o nome desse lugar é "Gólgota".)

[[v43-19-18]]

^<<v43-19-18,18>>^ Ali os soldados pregaram Jesus na cruz. E crucificaram também outros dois homens, um de cada lado dele.

[[v43-19-19]]

^<<v43-19-19,19>>^ Pilatos mandou escrever um letreiro e colocá-lo na parte de cima da cruz. Nesse letreiro estava escrito em hebraico, latim e grego : "Jesus de Nazaré, Rei dos Judeus". Muitas pessoas leram o letreiro porque o lugar em que Jesus foi crucificado ficava perto da cidade.

[[v43-19-20]]

^<<v43-19-20,20>>^ Pilatos mandou escrever um letreiro e colocá-lo na parte de cima da cruz. Nesse letreiro estava escrito em hebraico, latim e grego : "Jesus de Nazaré, Rei dos Judeus". Muitas pessoas leram o letreiro porque o lugar em que Jesus foi crucificado ficava perto da cidade.

[[v43-19-21]]

^<<v43-19-21,21>>^ Então os chefes dos sacerdotes disseram a Pilatos: — Não escreva: "Rei dos Judeus"; escreva: "Este homem disse: Eu sou o Rei dos Judeus".

[[v43-19-22]]

^<<v43-19-22,22>>^ — O que escrevi escrevi! — respondeu Pilatos.

[[v43-19-23]]

^<<v43-19-23,23>>^ Depois que os soldados crucificaram Jesus, pegaram as roupas dele e dividiram em quatro partes, uma para cada um. Mas a túnica  era sem costura, toda tecida numa só peça de alto a baixo.

[[v43-19-24]]

^<<v43-19-24,24>>^ Por isso os soldados disseram uns aos outros: — Não vamos rasgar a túnica. Vamos tirar a sorte para ver quem fica com ela. Isso aconteceu para que se cumprisse o que as Escrituras Sagradas  dizem: "Repartiram entre si as minhas roupas e fizeram sorteio  da minha túnica." E foi isso o que os soldados fizeram.

[[v43-19-25]]

^<<v43-19-25,25>>^ Perto da cruz de Jesus estavam a sua mãe, e a irmã dela, e Maria, a esposa de Clopas, e também Maria Madalena.

[[v43-19-26]]

^<<v43-19-26,26>>^ Quando Jesus viu a sua mãe e perto dela o discípulo que ele amava, disse a ela: — Este é o seu filho.

[[v43-19-27]]

^<<v43-19-27,27>>^ Em seguida disse a ele: — Esta é a sua mãe. E esse discípulo levou a mãe de Jesus para morar dali em diante na casa dele.

[[v43-19-28]]

^<<v43-19-28,28>>^ Agora Jesus sabia que tudo estava completado. Então, para que se cumprisse o que dizem as Escrituras Sagradas , disse: — Estou com sede!

[[v43-19-29]]

^<<v43-19-29,29>>^ Havia ali uma vasilha cheia de vinho comum. Molharam no vinho uma esponja, puseram a esponja num bastão de hissopo  e a encostaram na boca de Jesus.

[[v43-19-30]]

^<<v43-19-30,30>>^ Quando ele tomou o vinho, disse: — Tudo está completado! Então baixou a cabeça e morreu.

[[v43-19-31]]

^<<v43-19-31,31>>^ Então os líderes judeus pediram a Pilatos que mandasse quebrar as pernas dos que tinham sido crucificados e mandasse tirá-los das cruzes. Pediram isso porque era sexta-feira e não queriam que, no sábado, os corpos ainda estivessem nas cruzes. E aquele sábado era especialmente santo.

[[v43-19-32]]

^<<v43-19-32,32>>^ Os soldados foram e quebraram as pernas do primeiro homem que tinha sido crucificado com Jesus e depois quebraram as pernas do outro.

[[v43-19-33]]

^<<v43-19-33,33>>^ Mas, quando chegaram perto de Jesus, viram que ele já estava morto e não quebraram as suas pernas.

[[v43-19-34]]

^<<v43-19-34,34>>^ Porém um dos soldados furou o lado de Jesus com uma lança. No mesmo instante saiu sangue e água.

[[v43-19-35]]

^<<v43-19-35,35>>^ Quem viu isso contou o que aconteceu para que vocês também creiam. O que ele disse é verdade, e ele sabe que fala a verdade.

[[v43-19-36]]

^<<v43-19-36,36>>^ Isso aconteceu para que se cumprisse o que as Escrituras Sagradas  dizem: "Nenhum dos seus ossos será quebrado."

[[v43-19-37]]

^<<v43-19-37,37>>^ E em outro lugar as Escrituras Sagradas dizem: "Eles olharão para aquele a quem atravessaram com a lança."

[[v43-19-38]]

^<<v43-19-38,38>>^ Depois disso, José, da cidade de Arimateia, pediu licença a Pilatos para levar o corpo de Jesus. (José era seguidor de Jesus, mas em segredo porque tinha medo dos líderes judeus.) Pilatos deu licença, e José foi e retirou o corpo de Jesus.

[[v43-19-39]]

^<<v43-19-39,39>>^ Nicodemos, aquele que tinha ido falar com Jesus à noite, foi com José, levando uns trinta e cinco quilos de uma mistura de aloés  e mirra .

[[v43-19-40]]

^<<v43-19-40,40>>^ Os dois homens pegaram o corpo de Jesus e o enrolaram em lençóis nos quais haviam espalhado essa mistura. Era assim que os judeus preparavam os corpos dos mortos para serem sepultados.

[[v43-19-41]]

^<<v43-19-41,41>>^ No lugar onde Jesus tinha sido crucificado havia um jardim com um túmulo novo onde ninguém ainda tinha sido colocado.

'''

xref:043-joao/043-joao-018.adoc#v43-18-0[&#60; Capítulo Anterior] | <<v43-19-0,Topo>> | xref:043-joao/043-joao-020.adoc#v43-20-0[Próximo Capítulo &#62;]