include::./index.adoc[]

[[v43-4-0]]
=== João, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-4-1]]

^<<v43-4-1,1>>^ Os fariseus  ouviram dizer que Jesus estava ganhando mais discípulos e batizava mais pessoas do que João.

[[v43-4-2]]

^<<v43-4-2,2>>^ (De fato, não era Jesus quem batizava, e sim os seus discípulos.)

[[v43-4-3]]

^<<v43-4-3,3>>^ Quando Jesus ficou sabendo disso, saiu da Judeia e voltou para a Galileia.

[[v43-4-4]]

^<<v43-4-4,4>>^ No caminho, ele tinha de passar pela região da Samaria.

[[v43-4-5]]

^<<v43-4-5,5>>^ Ele chegou a uma cidade da Samaria, chamada Sicar, que ficava perto das terras que Jacó tinha dado ao seu filho José.

[[v43-4-6]]

^<<v43-4-6,6>>^ Ali ficava o poço de Jacó. Era mais ou menos meio-dia quando Jesus, cansado da viagem, sentou-se perto do poço.

[[v43-4-7]]

^<<v43-4-7,7>>^ Uma mulher samaritana  veio tirar água, e Jesus lhe disse: — Por favor, me dê um pouco de água.

[[v43-4-8]]

^<<v43-4-8,8>>^ (Os discípulos de Jesus tinham ido até a cidade comprar comida.)

[[v43-4-9]]

^<<v43-4-9,9>>^ A mulher respondeu: — O senhor é judeu, e eu sou samaritana. Então como é que o senhor me pede água? (Ela disse isso porque os judeus não se dão com os samaritanos.)

[[v43-4-10]]

^<<v43-4-10,10>>^ Então Jesus disse: — Se você soubesse o que Deus pode dar e quem é que está lhe pedindo água, você pediria, e ele lhe daria a água da vida.

[[v43-4-11]]

^<<v43-4-11,11>>^ Ela respondeu: — O senhor não tem balde para tirar água, e o poço é fundo. Como é que vai conseguir essa água da vida?

[[v43-4-12]]

^<<v43-4-12,12>>^ Nosso antepassado Jacó nos deu este poço. Ele, os seus filhos e os seus animais beberam água daqui. Será que o senhor é mais importante do que Jacó?

[[v43-4-13]]

^<<v43-4-13,13>>^ Então Jesus disse: — Quem beber desta água terá sede de novo,

[[v43-4-14]]

^<<v43-4-14,14>>^ mas a pessoa que beber da água que eu lhe der nunca mais terá sede. Porque a água que eu lhe der se tornará nela uma fonte de água que dará vida eterna.

[[v43-4-15]]

^<<v43-4-15,15>>^ Então a mulher pediu: — Por favor, me dê dessa água! Assim eu nunca mais terei sede e não precisarei mais vir aqui buscar água.

[[v43-4-16]]

^<<v43-4-16,16>>^ — Vá chamar o seu marido e volte aqui!  — ordenou Jesus.

[[v43-4-17]]

^<<v43-4-17,17>>^ — Eu não tenho marido! — respondeu a mulher. Então Jesus disse: — Você está certa ao dizer que não tem marido,

[[v43-4-18]]

^<<v43-4-18,18>>^ pois já teve cinco, e este que você tem agora não é, de fato, seu marido. Sim, você falou a verdade.

[[v43-4-19]]

^<<v43-4-19,19>>^ A mulher respondeu: — Agora eu sei que o senhor é um profeta !

[[v43-4-20]]

^<<v43-4-20,20>>^ Os nossos antepassados adoravam a Deus neste monte , mas vocês, judeus, dizem que Jerusalém é o lugar onde devemos adorá-lo.

[[v43-4-21]]

^<<v43-4-21,21>>^ Jesus disse: — Mulher, creia no que eu digo: chegará o tempo em que ninguém vai adorar a Deus nem neste monte nem em Jerusalém.

[[v43-4-22]]

^<<v43-4-22,22>>^ Vocês, samaritanos, não sabem o que adoram, mas nós sabemos o que adoramos porque a salvação vem dos judeus.

[[v43-4-23]]

^<<v43-4-23,23>>^ Mas virá o tempo, e, de fato, já chegou, em que os verdadeiros adoradores vão adorar o Pai em espírito e em verdade. Pois são esses que o Pai quer que o adorem.

[[v43-4-24]]

^<<v43-4-24,24>>^ Deus é Espírito, e por isso os que o adoram devem adorá-lo em espírito e em verdade.

[[v43-4-25]]

^<<v43-4-25,25>>^ A mulher respondeu: — Eu sei que o Messias , chamado Cristo, tem de vir. E, quando ele vier, vai explicar tudo para nós.

[[v43-4-26]]

^<<v43-4-26,26>>^ Então Jesus afirmou: — Pois eu, que estou falando com você, sou o Messias.

[[v43-4-27]]

^<<v43-4-27,27>>^ Naquele momento chegaram os seus discípulos e ficaram admirados, pois ele estava conversando com uma mulher. Mas nenhum deles perguntou à mulher o que ela queria. E também não perguntaram a Jesus por que motivo ele estava falando com ela.

[[v43-4-28]]

^<<v43-4-28,28>>^ Em seguida, a mulher deixou ali o seu pote, voltou até a cidade e disse a todas as pessoas:

[[v43-4-29]]

^<<v43-4-29,29>>^ — Venham ver o homem que disse tudo o que eu tenho feito. Será que ele é o Messias?

[[v43-4-30]]

^<<v43-4-30,30>>^ Muitas pessoas saíram da cidade e foram para o lugar onde Jesus estava.

[[v43-4-31]]

^<<v43-4-31,31>>^ Enquanto isso, os discípulos pediam a Jesus: — Mestre, coma alguma coisa!

[[v43-4-32]]

^<<v43-4-32,32>>^ Jesus respondeu: — Eu tenho para comer uma comida que vocês não conhecem.

[[v43-4-33]]

^<<v43-4-33,33>>^ Então os discípulos começaram a perguntar uns aos outros: — Será que alguém já trouxe comida para ele?

[[v43-4-34]]

^<<v43-4-34,34>>^ — A minha comida  — disse Jesus — é fazer a vontade daquele que me enviou e terminar o trabalho que ele me deu para fazer.

[[v43-4-35]]

^<<v43-4-35,35>>^ Vocês costumam dizer: "Daqui a quatro meses teremos a colheita." Mas olhem e vejam bem os campos: o que foi plantado já está maduro e pronto para a colheita.

[[v43-4-36]]

^<<v43-4-36,36>>^ Quem colhe recebe o seu salário, e o resultado do seu trabalho é a vida eterna para as pessoas. E assim tanto o que semeia como o que colhe se alegrarão juntos.

[[v43-4-37]]

^<<v43-4-37,37>>^ Porque é verdade o que dizem: "Um semeia, e outro colhe."

[[v43-4-38]]

^<<v43-4-38,38>>^ Eu mandei vocês colherem onde não trabalharam; outros trabalharam ali, e vocês aproveitaram o trabalho deles.

[[v43-4-39]]

^<<v43-4-39,39>>^ Muitos samaritanos daquela cidade creram em Jesus porque a mulher tinha dito: "Ele me disse tudo o que eu tenho feito."

[[v43-4-40]]

^<<v43-4-40,40>>^ Quando os samaritanos chegaram ao lugar onde Jesus estava, pediram a ele que ficasse com eles, e Jesus ficou ali dois dias.

[[v43-4-41]]

^<<v43-4-41,41>>^ E muitos outros creram por causa da mensagem dele.

[[v43-4-42]]

^<<v43-4-42,42>>^ Eles diziam à mulher: — Agora não é mais por causa do que você disse que nós cremos, mas porque nós mesmos o ouvimos falar. E sabemos que ele é, de fato, o Salvador do mundo.

[[v43-4-43]]

^<<v43-4-43,43>>^ Depois de ficar dois dias ali, Jesus foi para a região da Galileia.

[[v43-4-44]]

^<<v43-4-44,44>>^ Pois, como ele mesmo disse: "Um profeta  não é respeitado na sua própria terra."

[[v43-4-45]]

^<<v43-4-45,45>>^ Quando chegou à Galileia, os moradores dali o receberam bem. É que eles tinham ido à Festa da Páscoa , em Jerusalém, e tinham visto tudo o que Jesus havia feito lá.

[[v43-4-46]]

^<<v43-4-46,46>>^ Jesus voltou a Caná da Galileia, onde havia transformado água em vinho. Estava ali um alto funcionário público que morava em Cafarnaum. Ele tinha em casa um filho doente.

[[v43-4-47]]

^<<v43-4-47,47>>^ Quando ouviu dizer que Jesus tinha vindo da Judeia para a Galileia, foi pedir a ele que fosse a Cafarnaum e curasse o seu filho, que estava morrendo.

[[v43-4-48]]

^<<v43-4-48,48>>^ Jesus disse ao funcionário: — Vocês só creem quando veem grandes milagres!

[[v43-4-49]]

^<<v43-4-49,49>>^ Ele respondeu: — Senhor, venha depressa, antes que o meu filho morra!

[[v43-4-50]]

^<<v43-4-50,50>>^ — Volte para casa! O seu filho vai viver!  — disse Jesus. Ele creu nas palavras de Jesus e foi embora.

[[v43-4-51]]

^<<v43-4-51,51>>^ No caminho encontrou-se com os seus empregados, que disseram: — O seu filho está vivo!

[[v43-4-52]]

^<<v43-4-52,52>>^ Então ele perguntou a que horas o filho havia começado a melhorar. Os empregados responderam: — Ontem, à uma da tarde, a febre passou.

[[v43-4-53]]

^<<v43-4-53,53>>^ Aí o pai lembrou que havia sido naquela mesma hora que Jesus tinha dito: "O seu filho vai viver." Então ele e toda a família creram em Jesus.

[[v43-4-54]]

^<<v43-4-54,54>>^ Esse foi o segundo milagre que Jesus fez depois de ter ido da Judeia para a Galileia.

'''

xref:043-joao/043-joao-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-joao/043-joao-005.adoc#v43-5-0[Próximo Capítulo &#62;]