include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-13-1]]

^<<v43-13-1,1>>^ Faltava somente um dia para a Festa da Páscoa . Jesus sabia que tinha chegado a hora de deixar este mundo e ir para o Pai. Ele sempre havia amado os seus que estavam neste mundo e os amou até o fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Jesus e os seus discípulos estavam jantando. O Diabo já havia posto na cabeça de Judas, filho de Simão Iscariotes, a ideia de trair Jesus.

[[v43-13-3]]

^<<v43-13-3,3>>^ Jesus sabia que o Pai lhe tinha dado todo o poder. E sabia também que tinha vindo de Deus e ia para Deus.

[[v43-13-4]]

^<<v43-13-4,4>>^ Então se levantou, tirou a sua capa , pegou uma toalha e amarrou na cintura.

[[v43-13-5]]

^<<v43-13-5,5>>^ Em seguida pôs água numa bacia e começou a lavar os pés dos discípulos e a enxugá-los com a toalha.

[[v43-13-6]]

^<<v43-13-6,6>>^ Quando chegou perto de Simão Pedro, este lhe perguntou: — Vai lavar os meus pés, Senhor?

[[v43-13-7]]

^<<v43-13-7,7>>^ Jesus respondeu: — Agora você não entende o que estou fazendo, porém mais tarde vai entender!

[[v43-13-8]]

^<<v43-13-8,8>>^ — O senhor nunca lavará os meus pés! — disse Pedro. — Se eu não lavar, você não será mais meu discípulo!  — respondeu Jesus.

[[v43-13-9]]

^<<v43-13-9,9>>^ — Então, Senhor, não lave somente os meus pés; lave também as minhas mãos e a minha cabeça! — pediu Simão Pedro.

[[v43-13-10]]

^<<v43-13-10,10>>^ Aí Jesus disse: — Quem já tomou banho está completamente limpo e precisa lavar somente os pés. Vocês todos estão limpos, isto é, todos menos um.

[[v43-13-11]]

^<<v43-13-11,11>>^ Jesus sabia quem era o traidor. Foi por isso que disse: "Todos menos um."

[[v43-13-12]]

^<<v43-13-12,12>>^ Depois de lavar os pés dos seus discípulos, Jesus vestiu de novo a capa, sentou-se outra vez à mesa e perguntou: — Vocês entenderam o que eu fiz?

[[v43-13-13]]

^<<v43-13-13,13>>^ Vocês me chamam de "Mestre" e de "Senhor" e têm razão, pois eu sou mesmo.

[[v43-13-14]]

^<<v43-13-14,14>>^ Se eu, o Senhor e o Mestre, lavei os pés de vocês, então vocês devem lavar os pés uns dos outros.

[[v43-13-15]]

^<<v43-13-15,15>>^ Pois eu dei o exemplo para que vocês façam o que eu fiz.

[[v43-13-16]]

^<<v43-13-16,16>>^ Eu afirmo a vocês que isto é verdade: o empregado não é mais importante do que o patrão, e o mensageiro não é mais importante do que aquele que o enviou.

[[v43-13-17]]

^<<v43-13-17,17>>^ Já que vocês conhecem esta verdade, serão felizes se a praticarem.

[[v43-13-18]]

^<<v43-13-18,18>>^ — Não estou falando de vocês todos; eu conheço aqueles que escolhi. Pois tem de se cumprir o que as Escrituras Sagradas  dizem: "Aquele que toma refeições comigo se virou contra mim".

[[v43-13-19]]

^<<v43-13-19,19>>^ Digo isso a vocês agora, antes que aconteça, para que, quando acontecer, vocês creiam que " Eu Sou Quem Sou ".

[[v43-13-20]]

^<<v43-13-20,20>>^ Eu afirmo a vocês que isto é verdade: quem receber aquele que eu enviar estará também me recebendo; e quem me recebe recebe aquele que me enviou.

[[v43-13-21]]

^<<v43-13-21,21>>^ Depois de dizer isso, Jesus ficou muito aflito e declarou abertamente aos discípulos: — Eu afirmo a vocês que isto é verdade: um de vocês vai me trair.

[[v43-13-22]]

^<<v43-13-22,22>>^ Então eles olharam uns para os outros, sem saber de quem ele estava falando.

[[v43-13-23]]

^<<v43-13-23,23>>^ Ao lado de Jesus estava sentado um deles, a quem Jesus amava.

[[v43-13-24]]

^<<v43-13-24,24>>^ Simão Pedro fez um sinal para ele e disse: — Pergunte de quem o Mestre está falando.

[[v43-13-25]]

^<<v43-13-25,25>>^ Então aquele discípulo chegou mais perto de Jesus e perguntou: — Senhor, quem é ele?

[[v43-13-26]]

^<<v43-13-26,26>>^ — É aquele a quem vou dar um pedaço de pão passado no molho!  — respondeu Jesus. Em seguida pegou um pedaço de pão, passou no molho e deu a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ E assim que Judas recebeu o pão, Satanás entrou nele. Então Jesus disse a Judas: — O que você vai fazer faça logo!

[[v43-13-28]]

^<<v43-13-28,28>>^ Nenhum dos que estavam à mesa entendeu por que Jesus disse isso.

[[v43-13-29]]

^<<v43-13-29,29>>^ Como era Judas que tomava conta da bolsa do dinheiro, alguns pensaram que Jesus tinha mandado que ele comprasse alguma coisa para a festa ou desse alguma ajuda aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Judas recebeu o pão e saiu logo. E era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Quando Judas saiu, Jesus disse: — Agora a natureza divina do Filho do Homem  é revelada, e por meio dele é revelada também a natureza gloriosa  de Deus.

[[v43-13-32]]

^<<v43-13-32,32>>^ E, se por meio dele a natureza gloriosa de Deus for revelada, então Deus revelará em si mesmo a natureza divina do Filho do Homem. E Deus fará isso agora mesmo.

[[v43-13-33]]

^<<v43-13-33,33>>^ Meus filhos, não vou ficar com vocês por muito tempo. Vocês vão me procurar, mas eu digo agora o que já disse aos líderes judeus: vocês não podem ir para onde eu vou.

[[v43-13-34]]

^<<v43-13-34,34>>^ Eu lhes dou este novo mandamento: amem uns aos outros. Assim como eu os amei, amem também uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Se tiverem amor uns pelos outros, todos saberão que vocês são meus discípulos.

[[v43-13-36]]

^<<v43-13-36,36>>^ Simão Pedro perguntou a Jesus: — Senhor, para onde é que o senhor vai? Jesus respondeu: — Você não pode ir agora para onde eu vou. Um dia você poderá me seguir!

[[v43-13-37]]

^<<v43-13-37,37>>^ Pedro tornou a perguntar: — Senhor, por que eu não posso segui-lo agora? Eu estou pronto para morrer pelo senhor!

[[v43-13-38]]

^<<v43-13-38,38>>^ — Está mesmo?  — perguntou Jesus. — Pois eu afirmo a você que isto é verdade: antes que o galo cante, você dirá três vezes que não me conhece.

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]