include::./index.adoc[]

[[v43-7-0]]
=== João, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-7-1]]

^<<v43-7-1,1>>^ Depois disso, Jesus começou a andar pela Galileia; ele não queria andar pela Judeia, pois os líderes judeus dali estavam querendo matá-lo.

[[v43-7-2]]

^<<v43-7-2,2>>^ Aconteceu que a festa dos judeus chamada Festa das Barracas  estava perto.

[[v43-7-3]]

^<<v43-7-3,3>>^ Então os irmãos de Jesus disseram a ele: — Saia daqui e vá para a Judeia a fim de que os seus seguidores vejam o que você está fazendo.

[[v43-7-4]]

^<<v43-7-4,4>>^ Pois quem quer ser bem-conhecido não deve esconder o que está fazendo. Já que você faz essas coisas, deixe que todos o conheçam.

[[v43-7-5]]

^<<v43-7-5,5>>^ Até os irmãos de Jesus não criam nele.

[[v43-7-6]]

^<<v43-7-6,6>>^ Ele respondeu: — A minha hora ainda não chegou, mas para vocês qualquer hora serve.

[[v43-7-7]]

^<<v43-7-7,7>>^ O mundo não pode ter ódio de vocês, mas tem ódio de mim porque eu afirmo que o que o mundo faz é mau.

[[v43-7-8]]

^<<v43-7-8,8>>^ Vão vocês à festa, mas eu não vou porque a minha hora ainda não chegou.

[[v43-7-9]]

^<<v43-7-9,9>>^ Jesus disse isso e ficou na Galileia.

[[v43-7-10]]

^<<v43-7-10,10>>^ Depois que os seus irmãos foram à festa, Jesus também foi, mas fez isso em segredo e não publicamente.

[[v43-7-11]]

^<<v43-7-11,11>>^ Os líderes judeus o procuravam na festa e perguntavam: — Onde é que está aquele homem?

[[v43-7-12]]

^<<v43-7-12,12>>^ Na multidão havia muita gente comentando sobre ele. Alguns diziam: — Ele é bom. — Não é não; ele engana o povo! — afirmavam outros.

[[v43-7-13]]

^<<v43-7-13,13>>^ Mas ninguém falava abertamente sobre ele porque todos tinham medo dos líderes judeus.

[[v43-7-14]]

^<<v43-7-14,14>>^ Quando a festa já estava no meio, Jesus foi ao Templo e começou a ensinar.

[[v43-7-15]]

^<<v43-7-15,15>>^ Os líderes judeus ficaram muito admirados e diziam: — Como é que ele sabe tanto sem ter estudado?

[[v43-7-16]]

^<<v43-7-16,16>>^ Jesus disse: — O que eu ensino não vem de mim, mas vem de Deus, que me enviou.

[[v43-7-17]]

^<<v43-7-17,17>>^ Quem quiser fazer a vontade de Deus saberá se o meu ensino vem de Deus ou se falo em meu próprio nome.

[[v43-7-18]]

^<<v43-7-18,18>>^ Quem fala em seu próprio nome está procurando ser elogiado. Mas quem quer conseguir louvores para aquele que o enviou, esse é honesto, e não há falsidade nele.

[[v43-7-19]]

^<<v43-7-19,19>>^ Foi Moisés quem deu a Lei  a vocês, não foi? No entanto nenhum de vocês obedece à Lei. Por que é que vocês estão querendo me matar?

[[v43-7-20]]

^<<v43-7-20,20>>^ A multidão respondeu: — Você está dominado por um demônio! Quem é que está querendo matá-lo?

[[v43-7-21]]

^<<v43-7-21,21>>^ Então Jesus disse: — Eu fiz um milagre, e todos vocês estão admirados por causa disso.

[[v43-7-22]]

^<<v43-7-22,22>>^ Vocês circuncidam  um menino até no sábado porque Moisés mandou fazer isso. Mas a verdade é que a circuncisão não começou com Moisés, mas com os patriarcas .

[[v43-7-23]]

^<<v43-7-23,23>>^ Para não deixarem de cumprir a Lei de Moisés, vocês circuncidam um menino, mesmo no sábado. Então por que ficam com raiva de mim quando eu curo completamente uma pessoa no sábado?

[[v43-7-24]]

^<<v43-7-24,24>>^ Parem de julgar pelas aparências e julguem com justiça.

[[v43-7-25]]

^<<v43-7-25,25>>^ Algumas pessoas que moravam em Jerusalém perguntavam: — Não é este o homem que estão querendo matar?

[[v43-7-26]]

^<<v43-7-26,26>>^ Vejam! Ele está falando em público, e ninguém diz nada contra ele! Será que as autoridades sabem mesmo que ele é o Messias ?

[[v43-7-27]]

^<<v43-7-27,27>>^ No entanto, quando o Messias vier, ninguém saberá de onde ele é; e nós sabemos de onde este homem vem.

[[v43-7-28]]

^<<v43-7-28,28>>^ Quando estava ensinando no pátio do Templo, Jesus disse bem alto: — Será que vocês me conhecem mesmo e sabem de onde eu sou? Eu não vim por minha própria conta. Aquele que me enviou é verdadeiro, porém vocês não o conhecem.

[[v43-7-29]]

^<<v43-7-29,29>>^ Mas eu o conheço porque venho dele e fui mandado por ele.

[[v43-7-30]]

^<<v43-7-30,30>>^ Então quiseram prender Jesus, mas ninguém fez isso porque a sua hora ainda não tinha chegado.

[[v43-7-31]]

^<<v43-7-31,31>>^ Porém muitas pessoas que estavam na multidão creram nele e perguntavam: — Quando o Messias vier, será que vai fazer milagres maiores do que este homem tem feito?

[[v43-7-32]]

^<<v43-7-32,32>>^ Os fariseus  ouviram a multidão comentando essas coisas sobre Jesus, e por isso eles e os chefes dos sacerdotes mandaram guardas para o prenderem.

[[v43-7-33]]

^<<v43-7-33,33>>^ Jesus disse: — Eu vou ficar com vocês só mais um pouco e depois irei para aquele que me enviou.

[[v43-7-34]]

^<<v43-7-34,34>>^ Vocês vão me procurar e não vão me achar, pois não podem ir para onde eu vou.

[[v43-7-35]]

^<<v43-7-35,35>>^ Então os líderes judeus começaram a comentar: — Para onde será que ele vai que não o poderemos achar? Será que ele vai morar com os judeus que moram no estrangeiro? Será que vai ensinar os não judeus?

[[v43-7-36]]

^<<v43-7-36,36>>^ O que será que ele quis dizer quando afirmou: "Vocês vão me procurar e não vão me achar, pois não podem ir para onde eu vou"?

[[v43-7-37]]

^<<v43-7-37,37>>^ O último dia da festa era o mais importante. Naquele dia Jesus se pôs de pé e disse bem alto: — Se alguém tem sede, venha a mim e beba.

[[v43-7-38]]

^<<v43-7-38,38>>^ Como dizem as Escrituras Sagradas : "Rios de água viva vão jorrar do coração de quem crê em mim".

[[v43-7-39]]

^<<v43-7-39,39>>^ Jesus estava falando a respeito do Espírito Santo, que aqueles que criam nele iriam receber. Essas pessoas não tinham recebido o Espírito porque Jesus ainda não havia voltado para a presença gloriosa  de Deus.

[[v43-7-40]]

^<<v43-7-40,40>>^ Muitas pessoas que ouviram essas palavras afirmavam: — De fato, este homem é o Profeta !

[[v43-7-41]]

^<<v43-7-41,41>>^ Outros diziam: — Ele é o Messias ! E ainda outras pessoas perguntavam: — Mas será que o Messias virá da Galileia?

[[v43-7-42]]

^<<v43-7-42,42>>^ As Escrituras Sagradas  dizem que o Messias será descendente de Davi e vai nascer em Belém, onde Davi morou.

[[v43-7-43]]

^<<v43-7-43,43>>^ Então o povo se dividiu por causa dele.

[[v43-7-44]]

^<<v43-7-44,44>>^ Alguns queriam prender Jesus, mas ninguém fez isso.

[[v43-7-45]]

^<<v43-7-45,45>>^ Os guardas voltaram para o lugar onde estavam os chefes dos sacerdotes e os fariseus , e eles perguntaram: — Por que vocês não trouxeram aquele homem?

[[v43-7-46]]

^<<v43-7-46,46>>^ Eles responderam: — Nunca ninguém falou como ele!

[[v43-7-47]]

^<<v43-7-47,47>>^ Então os fariseus disseram aos guardas: — Será que vocês também foram enganados?

[[v43-7-48]]

^<<v43-7-48,48>>^ Por acaso alguma autoridade ou algum fariseu creu nele?

[[v43-7-49]]

^<<v43-7-49,49>>^ Essa gente que não conhece a Lei  está amaldiçoada por Deus.

[[v43-7-50]]

^<<v43-7-50,50>>^ Mas Nicodemos, que era um deles e que certa ocasião havia falado com Jesus, disse:

[[v43-7-51]]

^<<v43-7-51,51>>^ — De acordo com a nossa Lei não podemos condenar um homem sem ouvi-lo primeiro e descobrir o que ele fez.

[[v43-7-52]]

^<<v43-7-52,52>>^ — Por acaso você também é da Galileia? — perguntaram eles. — Estude as Escrituras Sagradas  e verá que da Galileia nunca surgiu nenhum profeta .

'''

xref:043-joao/043-joao-006.adoc#v43-6-0[&#60; Capítulo Anterior] | <<v43-7-0,Topo>> | xref:043-joao/043-joao-008.adoc#v43-8-0[Próximo Capítulo &#62;]