include::./index.adoc[]

[[v43-6-0]]
=== João, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-6-1]]

^<<v43-6-1,1>>^ Depois disso, Jesus atravessou o lago da Galileia, que também é chamado de Tiberíades.

[[v43-6-2]]

^<<v43-6-2,2>>^ Uma grande multidão o seguia porque eles tinham visto os milagres que Jesus tinha feito, curando os doentes.

[[v43-6-3]]

^<<v43-6-3,3>>^ Ele subiu um monte e sentou-se ali com os seus discípulos.

[[v43-6-4]]

^<<v43-6-4,4>>^ A Páscoa , a festa principal dos judeus, estava perto.

[[v43-6-5]]

^<<v43-6-5,5>>^ Jesus olhou em volta de si e viu que uma grande multidão estava chegando perto dele. Então disse a Filipe: — Onde vamos comprar comida para toda esta gente?

[[v43-6-6]]

^<<v43-6-6,6>>^ Ele sabia muito bem o que ia fazer, mas disse isso para ver qual seria a resposta de Filipe.

[[v43-6-7]]

^<<v43-6-7,7>>^ Filipe respondeu assim: — Para cada pessoa poder receber um pouco de pão, nós precisaríamos gastar mais de duzentas moedas de prata .

[[v43-6-8]]

^<<v43-6-8,8>>^ Então um dos discípulos, André, irmão de Simão Pedro, disse:

[[v43-6-9]]

^<<v43-6-9,9>>^ — Está aqui um menino que tem cinco pães de cevada  e dois peixinhos. Mas o que é isso para tanta gente?

[[v43-6-10]]

^<<v43-6-10,10>>^ Jesus disse: — Digam a todos que se sentem no chão. Então todos se sentaram. (Havia muita grama naquele lugar.) Estavam ali quase cinco mil homens.

[[v43-6-11]]

^<<v43-6-11,11>>^ Em seguida Jesus pegou os pães, deu graças a Deus e os repartiu com todos; e fez o mesmo com os peixes. E todos comeram à vontade.

[[v43-6-12]]

^<<v43-6-12,12>>^ Quando já estavam satisfeitos, ele disse aos discípulos: — Recolham os pedaços que sobraram a fim de que não se perca nada.

[[v43-6-13]]

^<<v43-6-13,13>>^ Eles ajuntaram os pedaços e encheram doze cestos com o que sobrou dos cinco pães.

[[v43-6-14]]

^<<v43-6-14,14>>^ Os que viram esse milagre de Jesus disseram: — De fato, este é o Profeta  que devia vir ao mundo!

[[v43-6-15]]

^<<v43-6-15,15>>^ Jesus ficou sabendo que queriam levá-lo à força para o fazerem rei; então voltou sozinho para o monte.

[[v43-6-16]]

^<<v43-6-16,16>>^ De tardinha, os discípulos de Jesus desceram até o lago.

[[v43-6-17]]

^<<v43-6-17,17>>^ Subiram num barco e começaram a atravessar o lago na direção da cidade de Cafarnaum. Quando já estava escuro, Jesus ainda não tinha vindo se encontrar com eles.

[[v43-6-18]]

^<<v43-6-18,18>>^ De repente, um vento forte começou a soprar e a levantar as ondas.

[[v43-6-19]]

^<<v43-6-19,19>>^ Os discípulos já tinham remado uns cinco ou seis quilômetros, quando viram Jesus andando em cima da água e chegando perto do barco. E ficaram com muito medo.

[[v43-6-20]]

^<<v43-6-20,20>>^ Mas Jesus disse: — Não tenham medo, sou eu!

[[v43-6-21]]

^<<v43-6-21,21>>^ Então eles o receberam com prazer no barco e logo chegaram ao lugar para onde estavam indo.

[[v43-6-22]]

^<<v43-6-22,22>>^ No dia seguinte a multidão que estava no lado leste do lago viu que ali só havia um barco pequeno. Sabiam que Jesus não tinha embarcado com os discípulos, pois estes haviam saído sozinhos.

[[v43-6-23]]

^<<v43-6-23,23>>^ Enquanto isso, outros barcos chegaram da cidade de Tiberíades e encostaram perto do lugar onde a multidão tinha comido pão depois de o Senhor Jesus ter dado graças.

[[v43-6-24]]

^<<v43-6-24,24>>^ Quando viram que Jesus e os seus discípulos não estavam ali, subiram nos barcos e saíram para Cafarnaum a fim de procurá-lo.

[[v43-6-25]]

^<<v43-6-25,25>>^ A multidão encontrou Jesus no lado oeste do lago, e perguntaram a ele: — Mestre, quando foi que o senhor chegou aqui?

[[v43-6-26]]

^<<v43-6-26,26>>^ Jesus respondeu: — Eu afirmo a vocês que isto é verdade: vocês estão me procurando porque comeram os pães e ficaram satisfeitos e não porque entenderam os meus milagres.

[[v43-6-27]]

^<<v43-6-27,27>>^ Não trabalhem a fim de conseguir a comida que se estraga, mas a fim de conseguir a comida que dura para a vida eterna. O Filho do Homem  dará essa comida a vocês porque Deus, o Pai, deu provas de que ele tem autoridade.

[[v43-6-28]]

^<<v43-6-28,28>>^ — O que é que Deus quer que a gente faça? — perguntaram eles.

[[v43-6-29]]

^<<v43-6-29,29>>^ — Ele quer que vocês creiam naquele que ele enviou!  — respondeu Jesus.

[[v43-6-30]]

^<<v43-6-30,30>>^ Eles disseram: — Que milagre o senhor vai fazer para a gente ver e crer no senhor? O que é que o senhor pode fazer?

[[v43-6-31]]

^<<v43-6-31,31>>^ Os nossos antepassados comeram o maná  no deserto, como dizem as Escrituras Sagradas : "Do céu ele deu pão para eles comerem."

[[v43-6-32]]

^<<v43-6-32,32>>^ Jesus disse: — Eu afirmo a vocês que isto é verdade: não foi Moisés quem deu a vocês o pão do céu, pois quem dá o verdadeiro pão do céu é o meu Pai.

[[v43-6-33]]

^<<v43-6-33,33>>^ Porque o pão que Deus dá é aquele que desce do céu e dá vida ao mundo.

[[v43-6-34]]

^<<v43-6-34,34>>^ — Queremos que o senhor nos dê sempre desse pão! — pediram eles.

[[v43-6-35]]

^<<v43-6-35,35>>^ Jesus respondeu: — Eu sou o pão da vida. Quem vem a mim nunca mais terá fome, e quem crê em mim nunca mais terá sede.

[[v43-6-36]]

^<<v43-6-36,36>>^ Mas eu já disse que vocês não creem em mim, embora estejam me vendo.

[[v43-6-37]]

^<<v43-6-37,37>>^ Todos aqueles que o Pai me dá virão a mim; e de modo nenhum jogarei fora aqueles que vierem a mim.

[[v43-6-38]]

^<<v43-6-38,38>>^ Pois eu desci do céu para fazer a vontade daquele que me enviou e não para fazer a minha própria vontade.

[[v43-6-39]]

^<<v43-6-39,39>>^ E a vontade de quem me enviou é esta: que nenhum daqueles que o Pai me deu se perca, mas que eu ressuscite todos no último dia.

[[v43-6-40]]

^<<v43-6-40,40>>^ Pois a vontade do meu Pai é que todos os que veem o Filho e creem nele tenham a vida eterna; e no último dia eu os ressuscitarei.

[[v43-6-41]]

^<<v43-6-41,41>>^ Eles começaram a criticar Jesus porque ele tinha dito: "Eu sou o pão que desceu do céu."

[[v43-6-42]]

^<<v43-6-42,42>>^ E diziam: — Este não é Jesus, filho de José? Por acaso nós não conhecemos o pai e a mãe dele? Como é que agora ele diz que desceu do céu?

[[v43-6-43]]

^<<v43-6-43,43>>^ Jesus respondeu: — Parem de resmungar contra mim.

[[v43-6-44]]

^<<v43-6-44,44>>^ Só poderão vir a mim aqueles que forem trazidos pelo Pai, que me enviou, e eu os ressuscitarei no último dia.

[[v43-6-45]]

^<<v43-6-45,45>>^ Nos Profetas  está escrito: "Todos serão ensinados por Deus." E todos os que ouvem o Pai e aprendem com ele vêm a mim.

[[v43-6-46]]

^<<v43-6-46,46>>^ Isso não quer dizer que alguém já tenha visto o Pai, a não ser aquele que vem de Deus; ele já viu o Pai.

[[v43-6-47]]

^<<v43-6-47,47>>^ — Eu afirmo a vocês que isto é verdade: quem crê tem a vida eterna.

[[v43-6-48]]

^<<v43-6-48,48>>^ Eu sou o pão da vida.

[[v43-6-49]]

^<<v43-6-49,49>>^ Os antepassados de vocês comeram o maná no deserto, mas morreram.

[[v43-6-50]]

^<<v43-6-50,50>>^ Aqui está o pão que desce do céu; e quem comer desse pão nunca morrerá.

[[v43-6-51]]

^<<v43-6-51,51>>^ Eu sou o pão vivo que desceu do céu. Se alguém comer desse pão, viverá para sempre. E o pão que eu darei para que o mundo tenha vida é a minha carne.

[[v43-6-52]]

^<<v43-6-52,52>>^ Aí eles começaram a discutir entre si. E perguntavam: — Como é que este homem pode dar a sua própria carne para a gente comer?

[[v43-6-53]]

^<<v43-6-53,53>>^ Então Jesus disse: — Eu afirmo a vocês que isto é verdade: se vocês não comerem a carne do Filho do Homem  e não beberem o seu sangue, vocês não terão vida.

[[v43-6-54]]

^<<v43-6-54,54>>^ Quem come a minha carne e bebe o meu sangue tem a vida eterna, e eu o ressuscitarei no último dia.

[[v43-6-55]]

^<<v43-6-55,55>>^ Pois a minha carne é a comida verdadeira, e o meu sangue é a bebida verdadeira.

[[v43-6-56]]

^<<v43-6-56,56>>^ Quem come a minha carne e bebe o meu sangue vive em mim, e eu vivo nele.

[[v43-6-57]]

^<<v43-6-57,57>>^ O Pai, que tem a vida, foi quem me enviou, e por causa dele eu tenho a vida. Assim, também, quem se alimenta de mim terá vida por minha causa.

[[v43-6-58]]

^<<v43-6-58,58>>^ Este é o pão que desceu do céu. Não é como o pão que os antepassados de vocês comeram e mesmo assim morreram. Quem come deste pão viverá para sempre.

[[v43-6-59]]

^<<v43-6-59,59>>^ Jesus disse isso quando estava ensinando na sinagoga  de Cafarnaum.

[[v43-6-60]]

^<<v43-6-60,60>>^ Muitos seguidores de Jesus ouviram isso e reclamaram: — O que ele ensina é muito difícil! Quem pode aceitar esses ensinamentos?

[[v43-6-61]]

^<<v43-6-61,61>>^ Não disseram nada a Jesus, mas ele sabia que eles estavam resmungando contra ele. Por isso perguntou: — Vocês querem me abandonar por causa disso?

[[v43-6-62]]

^<<v43-6-62,62>>^ E o que aconteceria se vocês vissem o Filho do Homem  subir para onde estava antes?

[[v43-6-63]]

^<<v43-6-63,63>>^ O Espírito de Deus é quem dá a vida, mas o ser humano não pode fazer isso. As palavras que eu lhes disse são espírito e vida,

[[v43-6-64]]

^<<v43-6-64,64>>^ mas mesmo assim alguns de vocês não creem. Jesus disse isso porque já sabia desde o começo quem eram os que não iam crer nele e sabia também quem ia traí-lo.

[[v43-6-65]]

^<<v43-6-65,65>>^ Jesus continuou: — Foi por esse motivo que eu disse a vocês que só pode vir a mim a pessoa que for trazida pelo Pai.

[[v43-6-66]]

^<<v43-6-66,66>>^ Por causa disso muitos seguidores de Jesus o abandonaram e não o acompanhavam mais.

[[v43-6-67]]

^<<v43-6-67,67>>^ Então ele perguntou aos doze discípulos: — Será que vocês também querem ir embora?

[[v43-6-68]]

^<<v43-6-68,68>>^ Simão Pedro respondeu: — Quem é que nós vamos seguir? O senhor tem as palavras que dão vida eterna!

[[v43-6-69]]

^<<v43-6-69,69>>^ E nós cremos e sabemos que o senhor é o Santo que Deus enviou.

[[v43-6-70]]

^<<v43-6-70,70>>^ Jesus disse: — Fui eu que escolhi todos vocês, os doze. No entanto um de vocês é um diabo!

[[v43-6-71]]

^<<v43-6-71,71>>^ Ele estava falando de Judas, filho de Simão Iscariotes. Pois Judas, embora fosse um dos doze discípulos, ia trair Jesus.

'''

xref:043-joao/043-joao-005.adoc#v43-5-0[&#60; Capítulo Anterior] | <<v43-6-0,Topo>> | xref:043-joao/043-joao-007.adoc#v43-7-0[Próximo Capítulo &#62;]