include::./index.adoc[]

[[v43-2-0]]
=== João, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-2-1]]

^<<v43-2-1,1>>^ Dois dias depois, houve um casamento no povoado de Caná, na região da Galileia, e a mãe de Jesus estava ali.

[[v43-2-2]]

^<<v43-2-2,2>>^ Jesus e os seus discípulos também tinham sido convidados para o casamento.

[[v43-2-3]]

^<<v43-2-3,3>>^ Quando acabou o vinho, a mãe de Jesus lhe disse: — O vinho acabou.

[[v43-2-4]]

^<<v43-2-4,4>>^ Jesus respondeu: — Não é preciso que a senhora diga o que eu devo fazer. Ainda não chegou a minha hora.

[[v43-2-5]]

^<<v43-2-5,5>>^ Então ela disse aos empregados: — Façam o que ele mandar.

[[v43-2-6]]

^<<v43-2-6,6>>^ Ali perto estavam seis potes de pedra; em cada um cabiam entre oitenta e cento e vinte litros de água. Os judeus usavam a água que guardavam nesses potes nas suas cerimônias de purificação .

[[v43-2-7]]

^<<v43-2-7,7>>^ Jesus disse aos empregados: — Encham de água estes potes. E eles os encheram até a boca.

[[v43-2-8]]

^<<v43-2-8,8>>^ Em seguida Jesus mandou: — Agora tirem um pouco da água destes potes e levem ao dirigente da festa. E eles levaram.

[[v43-2-9]]

^<<v43-2-9,9>>^ Então o dirigente da festa provou a água, e a água tinha virado vinho. Ele não sabia de onde tinha vindo aquele vinho, mas os empregados sabiam. Por isso ele chamou o noivo

[[v43-2-10]]

^<<v43-2-10,10>>^ e disse: — Todos costumam servir primeiro o vinho bom e, depois que os convidados já beberam muito, servem o vinho comum. Mas você guardou até agora o melhor vinho.

[[v43-2-11]]

^<<v43-2-11,11>>^ Jesus fez esse seu primeiro milagre em Caná da Galileia. Assim ele revelou a sua natureza divina, e os seus discípulos creram nele.

[[v43-2-12]]

^<<v43-2-12,12>>^ Depois disso, Jesus, a sua mãe, os seus irmãos e os seus discípulos foram para a cidade de Cafarnaum e ficaram alguns dias ali.

[[v43-2-13]]

^<<v43-2-13,13>>^ Alguns dias antes da Páscoa  dos judeus, Jesus foi até a cidade de Jerusalém.

[[v43-2-14]]

^<<v43-2-14,14>>^ No pátio do Templo encontrou pessoas vendendo bois, ovelhas e pombas; e viu também os que, sentados às suas mesas, trocavam dinheiro para o povo.

[[v43-2-15]]

^<<v43-2-15,15>>^ Então ele fez um chicote de cordas e expulsou toda aquela gente dali e também as ovelhas e os bois. Virou as mesas dos que trocavam dinheiro, e as moedas se espalharam pelo chão.

[[v43-2-16]]

^<<v43-2-16,16>>^ E disse aos que vendiam pombas: — Tirem tudo isto daqui! Parem de fazer da casa do meu Pai um mercado!

[[v43-2-17]]

^<<v43-2-17,17>>^ Então os discípulos dele lembraram das palavras das Escrituras Sagradas  que dizem: "O meu amor pela tua casa, ó Deus, queima dentro de mim como fogo."

[[v43-2-18]]

^<<v43-2-18,18>>^ Aí os líderes judeus perguntaram: — Que milagre você pode fazer para nos provar que tem autoridade para fazer isso?

[[v43-2-19]]

^<<v43-2-19,19>>^ Jesus respondeu: — Derrubem este Templo, e eu o construirei de novo em três dias!

[[v43-2-20]]

^<<v43-2-20,20>>^ Eles disseram: — A construção deste Templo levou quarenta e seis anos, e você diz que vai construí-lo de novo em três dias?

[[v43-2-21]]

^<<v43-2-21,21>>^ Porém o templo do qual Jesus estava falando era o seu próprio corpo.

[[v43-2-22]]

^<<v43-2-22,22>>^ Quando Jesus foi ressuscitado, os seus discípulos lembraram que ele tinha dito isso e então creram nas Escrituras Sagradas e nas palavras dele.

[[v43-2-23]]

^<<v43-2-23,23>>^ Quando Jesus estava em Jerusalém, durante a Festa da Páscoa , muitos creram nele porque viram os milagres que ele fazia.

[[v43-2-24]]

^<<v43-2-24,24>>^ Mas Jesus não confiava neles, pois os conhecia muito bem.

[[v43-2-25]]

^<<v43-2-25,25>>^ E ninguém precisava falar com ele sobre qualquer pessoa, pois ele sabia o que cada pessoa pensava.

'''

xref:043-joao/043-joao-001.adoc#v43-1-0[&#60; Capítulo Anterior] | <<v43-2-0,Topo>> | xref:043-joao/043-joao-003.adoc#v43-3-0[Próximo Capítulo &#62;]