include::./index.adoc[]

[[v43-15-0]]
=== João, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v43-15-1]]

^<<v43-15-1,1>>^ Jesus disse: — Eu sou a videira  verdadeira, e o meu Pai é o lavrador.

[[v43-15-2]]

^<<v43-15-2,2>>^ Todos os ramos que não dão uvas ele corta, embora eles estejam em mim. Mas os ramos que dão uvas ele poda a fim de que fiquem limpos e deem mais uvas ainda.

[[v43-15-3]]

^<<v43-15-3,3>>^ Vocês já estão limpos por meio dos ensinamentos que eu lhes tenho dado.

[[v43-15-4]]

^<<v43-15-4,4>>^ Continuem unidos comigo, e eu continuarei unido com vocês. Pois, assim como o ramo só dá uvas quando está unido com a planta, assim também vocês só podem dar fruto se ficarem unidos comigo.

[[v43-15-5]]

^<<v43-15-5,5>>^ — Eu sou a videira, e vocês são os ramos. Quem está unido comigo e eu com ele, esse dá muito fruto porque sem mim vocês não podem fazer nada.

[[v43-15-6]]

^<<v43-15-6,6>>^ Quem não ficar unido comigo será jogado fora e secará; será como os ramos secos que são juntados e jogados no fogo, onde são queimados.

[[v43-15-7]]

^<<v43-15-7,7>>^ Se vocês ficarem unidos comigo, e as minhas palavras continuarem em vocês, vocês receberão tudo o que pedirem.

[[v43-15-8]]

^<<v43-15-8,8>>^ E a natureza gloriosa  do meu Pai se revela quando vocês produzem muitos frutos e assim mostram que são meus discípulos.

[[v43-15-9]]

^<<v43-15-9,9>>^ Assim como o meu Pai me ama, eu amo vocês; portanto, continuem unidos comigo por meio do meu amor por vocês.

[[v43-15-10]]

^<<v43-15-10,10>>^ Se obedecerem aos meus mandamentos, eu continuarei amando vocês, assim como eu obedeço aos mandamentos do meu Pai e ele continua a me amar.

[[v43-15-11]]

^<<v43-15-11,11>>^ — Eu estou dizendo isso para que a minha alegria esteja em vocês, e a alegria de vocês seja completa.

[[v43-15-12]]

^<<v43-15-12,12>>^ O meu mandamento é este: amem uns aos outros como eu amo vocês.

[[v43-15-13]]

^<<v43-15-13,13>>^ Ninguém tem mais amor pelos seus amigos do que aquele que dá a sua vida por eles.

[[v43-15-14]]

^<<v43-15-14,14>>^ Vocês são meus amigos se fazem o que eu mando.

[[v43-15-15]]

^<<v43-15-15,15>>^ Eu não chamo mais vocês de empregados, pois o empregado não sabe o que o seu patrão faz; mas chamo vocês de amigos, pois tenho dito a vocês tudo o que ouvi do meu Pai.

[[v43-15-16]]

^<<v43-15-16,16>>^ Não foram vocês que me escolheram; pelo contrário, fui eu que os escolhi para que vão e deem fruto e que esse fruto não se perca. Isso a fim de que o Pai lhes dê tudo o que pedirem em meu nome.

[[v43-15-17]]

^<<v43-15-17,17>>^ O que eu mando a vocês é isto: amem uns aos outros.

[[v43-15-18]]

^<<v43-15-18,18>>^ Jesus continuou: — Se o mundo odeia vocês, lembrem que ele me odiou primeiro.

[[v43-15-19]]

^<<v43-15-19,19>>^ Se vocês fossem do mundo, o mundo os amaria por vocês serem dele. Mas eu os escolhi entre as pessoas do mundo, e vocês não são mais dele. Por isso o mundo odeia vocês.

[[v43-15-20]]

^<<v43-15-20,20>>^ Lembrem do que eu disse: "O empregado não é mais importante do que o patrão". Se as pessoas que são do mundo me perseguiram, também perseguirão vocês; se elas obedeceram aos meus ensinamentos, também obedecerão aos ensinamentos de vocês.

[[v43-15-21]]

^<<v43-15-21,21>>^ Por causa de mim, essas pessoas vão lhes fazer tudo isso porque não conhecem aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Elas não teriam nenhum pecado se eu não tivesse vindo e falado a elas. Mas agora essas pessoas não têm desculpa para o seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Quem me odeia odeia também o meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu não tivesse feito entre elas essas coisas que nenhum outro fez, elas não teriam nenhum pecado. Mas agora viram o que eu fiz e continuam a odiar tanto a mim como o meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Mas isso é para que se cumpra o que está escrito na Lei  deles: "Eles me odiaram sem motivo."

[[v43-15-26]]

^<<v43-15-26,26>>^ — Quando chegar o Auxiliador, o Espírito da verdade, que vem do Pai, ele falará a respeito de mim. E sou eu quem enviará esse Auxiliador a vocês da parte do Pai.

[[v43-15-27]]

^<<v43-15-27,27>>^ E vocês também falarão a meu respeito porque estão comigo desde o começo.

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]