include::./index.adoc[]

[[v36-3-0]]
=== Sofonias, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v36-3-1]]

^<<v36-3-1,1>>^ Ai de Jerusalém, cidade rebelde e cheia de corrupção, que persegue os seus moradores!

[[v36-3-2]]

^<<v36-3-2,2>>^ Jerusalém não escuta o que o Senhor  Deus diz, nem quer que ele a corrija. Não confia no seu Deus, nem procura a sua ajuda.

[[v36-3-3]]

^<<v36-3-3,3>>^ As suas autoridades são como leões que rugem, e os juízes são como lobos ferozes que devoram tudo de uma vez, sem deixar nada para o dia seguinte.

[[v36-3-4]]

^<<v36-3-4,4>>^ Os profetas  são orgulhosos e enganadores. Os sacerdotes profanam  o santuário e desobedecem à lei  de Deus.

[[v36-3-5]]

^<<v36-3-5,5>>^ Mas o Senhor  ainda está na cidade e sempre faz o que é certo e nunca o que é errado. Todas as manhãs, sem falta, ele manda fazer o que é direito; mas os que são maus continuam na mesma e não se sentem envergonhados.

[[v36-3-6]]

^<<v36-3-6,6>>^ O Senhor  Deus diz: — Eu destruí nações, arrasei cidades e deixei em ruínas as torres de vigia e as ruas. As cidades estão desertas; não há mais ninguém morando nelas.

[[v36-3-7]]

^<<v36-3-7,7>>^ Pensei assim: "Agora, o meu povo vai me temer . Eles deixarão que eu os corrija e não esquecerão as muitas vezes em que eu os castiguei." Mas eles se esforçaram ainda mais para fazer tudo o que é mau.

[[v36-3-8]]

^<<v36-3-8,8>>^ Portanto, o Senhor  Deus diz: — Esperem o dia em que vou me levantar e acusar as nações. Decidi reunir todas as nações, todos os reinos, a fim de castigá-los. Eles sentirão a minha ira , pois derramarei o meu furor sobre eles, e o mundo inteiro será destruído pelo fogo da minha ira.

[[v36-3-9]]

^<<v36-3-9,9>>^ — Então farei com que os povos parem de adorar ídolos e adorem somente a mim, o Senhor , e farei também com que todos me obedeçam com a mesma dedicação.

[[v36-3-10]]

^<<v36-3-10,10>>^ E o meu povo que está espalhado pelas nações virá me oferecer sacrifícios ; eles virão até dos lugares mais distantes da Etiópia.

[[v36-3-11]]

^<<v36-3-11,11>>^ Naquele tempo, vocês, o meu povo, não vão sentir mais vergonha por causa das vezes que se revoltaram contra mim. Pois eu farei desaparecer do meio de vocês todos os orgulhosos e vaidosos. Nunca mais vocês vão se sentir orgulhosos no meu monte santo .

[[v36-3-12]]

^<<v36-3-12,12>>^ Deixarei em Jerusalém um povo humilde e ajuizado, que confia em mim.

[[v36-3-13]]

^<<v36-3-13,13>>^ Os que sobrarem do povo de Israel nunca mais farão maldades, não mentirão, nem procurarão enganar ninguém. Terão comida à vontade, estarão seguros e não ficarão com medo de ninguém.

[[v36-3-14]]

^<<v36-3-14,14>>^ Povo de Israel, cante louvores a Deus! Alegrem-se, moradores de Jerusalém, e louvem a Deus com todo o coração!

[[v36-3-15]]

^<<v36-3-15,15>>^ O Senhor  Deus anulou a sentença que havia contra vocês e afastou todos os inimigos do seu povo. O Senhor , o Rei de Israel, está com vocês, e vocês não precisam mais ter medo da desgraça.

[[v36-3-16]]

^<<v36-3-16,16>>^ Chegará o dia em que dirão a Jerusalém: "Não tenha medo, povo de Sião , não desanime, nem perca a coragem.

[[v36-3-17]]

^<<v36-3-17,17>>^ Pois o Senhor , seu Deus, está com vocês; ele é poderoso e os salvará. Deus ficará contente com vocês e por causa do seu amor lhes dará nova vida. Ele cantará e se alegrará,

[[v36-3-18]]

^<<v36-3-18,18>>^ como se faz num dia de festa." O Senhor  Deus diz: "Eu afastarei a ameaça que está sobre vocês e os livrarei da desgraça.

[[v36-3-19]]

^<<v36-3-19,19>>^ Quando chegar aquele dia, castigarei aqueles que os perseguem. Salvarei os aleijados e trarei de volta os que foram espalhados. Vocês foram envergonhados em toda parte, mas depois terão louvor e glória .

[[v36-3-20]]

^<<v36-3-20,20>>^ Quando chegar aquele dia, eu os ajuntarei e os trarei de volta para o seu país. Farei com que prosperem de novo; vocês serão famosos no mundo inteiro, e todos os povos os respeitarão." Eu, o Senhor , falei.

'''

xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[&#60; Capítulo Anterior] | <<v36-3-0,Topo>> | xref:037-ageu/037-ageu-001.adoc#v37-1-0[Próximo Capítulo &#62;]