include::./index.adoc[]

[[v36-1-0]]
=== Sofonias, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v36-1-1]]

^<<v36-1-1,1>>^ Esta é a mensagem que o Senhor  Deus deu a Sofonias, no tempo em que Josias, filho de Amom, era rei de Judá. Sofonias era filho de Cusi, neto de Gedalias, bisneto de Amarias e trineto do rei Ezequias.

[[v36-1-2]]

^<<v36-1-2,2>>^ O Senhor  Deus diz: — Vou acabar com tudo o que existe na terra,

[[v36-1-3]]

^<<v36-1-3,3>>^ isto é, as pessoas, os animais, as aves e os peixes. Eu vou castigar os maus. Acabarei completamente com os seres humanos.

[[v36-1-4]]

^<<v36-1-4,4>>^ — Castigarei o povo da terra de Judá e os moradores de Jerusalém. Farei desaparecer de Jerusalém o que ainda resta da adoração a Baal , e todos esquecerão os sacerdotes que serviam esse deus pagão.

[[v36-1-5]]

^<<v36-1-5,5>>^ Acabarei com todos os que sobem ao terraço, em cima das suas casas, e ali adoram o sol, a lua e as estrelas. E acabarei também com qualquer pessoa que adora a mim, o Senhor , e jura pelo meu nome, mas jura também pelo nome do deus Moloque .

[[v36-1-6]]

^<<v36-1-6,6>>^ Destruirei todos os que se afastam de mim, que não procuram a minha ajuda, nem querem obedecer às minhas leis .

[[v36-1-7]]

^<<v36-1-7,7>>^ Está chegando o dia em que o Senhor  Deus vai julgar o seu povo. Portanto, calem-se todos na sua presença! Ele vai oferecer o seu povo como sacrifício  e já convidou os inimigos para o ajudarem a fazer isso.

[[v36-1-8]]

^<<v36-1-8,8>>^ O Senhor  diz: — Naquele dia, eu vou castigar as autoridades, os filhos do rei e todos os que seguem costumes pagãos.

[[v36-1-9]]

^<<v36-1-9,9>>^ Castigarei também todos os que me adoram como os pagãos adoram os seus deuses e aqueles que enchem o templo do seu deus com presentes que ajuntaram por meio de roubo e violência.

[[v36-1-10]]

^<<v36-1-10,10>>^ — Naquele dia, haverá gritos de dor perto do Portão dos Peixes, na cidade de Jerusalém. Haverá gente gritando por socorro no bairro novo da cidade, e nos montes se ouvirão gritos de desespero.

[[v36-1-11]]

^<<v36-1-11,11>>^ Chorem também, vocês que moram na cidade baixa, pois todos os comerciantes serão mortos!

[[v36-1-12]]

^<<v36-1-12,12>>^ — Naquele dia, eu vou pegar lamparinas e revistar a cidade de Jerusalém. Castigarei todos os que estão tranquilos e satisfeitos, os que pensam assim: "O Senhor  Deus não vai fazer nada; não vai salvar, nem castigar."

[[v36-1-13]]

^<<v36-1-13,13>>^ Por isso, os bens deles serão roubados, e as suas casas serão destruídas. Eles construirão outras, mas não morarão nelas; farão plantações de uvas, mas não beberão o vinho.

[[v36-1-14]]

^<<v36-1-14,14>>^ O grande Dia do Senhor  está perto e vem chegando depressa! Será um dia terrível, em que até os soldados mais valentes gritarão de medo.

[[v36-1-15]]

^<<v36-1-15,15>>^ Será um dia de ira , um dia de aflição e angústia, de ruína e destruição, de escuridão e trevas; será um dia de nuvens escuras e pesadas.

[[v36-1-16]]

^<<v36-1-16,16>>^ Será um dia de sons de corneta e de gritos de batalha de soldados atacando cidades cercadas de muralhas e protegidas por altas torres de vigia.

[[v36-1-17]]

^<<v36-1-17,17>>^ O Senhor  diz: — Farei cair tantas desgraças sobre as pessoas, que elas andarão de um lado para outro como se estivessem cegas. Essa gente pecou contra mim, e por isso o seu sangue será derramado como água, e os seus corpos serão jogados fora como lixo.

[[v36-1-18]]

^<<v36-1-18,18>>^ Naquele dia, nem prata nem ouro os poderão salvar da ira de Deus, o Senhor . O fogo da sua ira furiosa destruirá o mundo inteiro. Ninguém escapará, pois Deus vai acabar de uma só vez com todos os moradores da terra.

'''

xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[&#60; Capítulo Anterior] | <<v36-1-0,Topo>> | xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[Próximo Capítulo &#62;]