include::./index.adoc[]

[[v32-3-0]]
=== Jonas, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v32-3-1]]

^<<v32-3-1,1>>^ Pela segunda vez, o Senhor  Deus disse a Jonas:

[[v32-3-2]]

^<<v32-3-2,2>>^ — Apronte-se, vá à grande cidade de Nínive e anuncie ao povo de lá a mensagem que eu vou dar a você.

[[v32-3-3]]

^<<v32-3-3,3>>^ Jonas se aprontou e foi a Nínive, como o Senhor  Deus havia ordenado. Nínive era tão grande, que uma pessoa levava três dias para atravessá-la a pé.

[[v32-3-4]]

^<<v32-3-4,4>>^ Jonas entrou na cidade, andou um dia inteiro e então começou a anunciar: — Dentro de quarenta dias, Nínive será destruída!

[[v32-3-5]]

^<<v32-3-5,5>>^ Então os moradores de Nínive creram em Deus e resolveram que cada um devia jejuar. E todos, desde os mais importantes até os mais humildes, vestiram roupa feita de pano grosseiro a fim de mostrar que estavam arrependidos.

[[v32-3-6]]

^<<v32-3-6,6>>^ Quando o rei de Nínive soube disso, levantou-se do trono, tirou o manto , vestiu uma roupa feita de pano grosseiro e sentou-se sobre cinzas.

[[v32-3-7]]

^<<v32-3-7,7>>^ Mandou também anunciar ao povo da cidade o seguinte: "Esta é uma ordem do rei e dos seus ministros. Ninguém pode comer nada. Todas as pessoas e também os animais, o gado e as ovelhas estão proibidos de comer e beber.

[[v32-3-8]]

^<<v32-3-8,8>>^ Que todas as pessoas e animais vistam roupas feitas de pano grosseiro! Que cada pessoa ore a Deus com fervor e abandone os seus maus caminhos e as suas maldades!

[[v32-3-9]]

^<<v32-3-9,9>>^ Talvez assim Deus mude de ideia. Talvez o seu furor passe, e assim não morreremos!"

[[v32-3-10]]

^<<v32-3-10,10>>^ Deus viu o que eles fizeram e como abandonaram os seus maus caminhos. Então mudou de ideia e não castigou a cidade como tinha dito que faria.

'''

xref:032-jonas/032-jonas-002.adoc#v32-2-0[&#60; Capítulo Anterior] | <<v32-3-0,Topo>> | xref:032-jonas/032-jonas-004.adoc#v32-4-0[Próximo Capítulo &#62;]