include::./index.adoc[]

[[v32-1-0]]
=== Jonas, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v32-1-1]]

^<<v32-1-1,1>>^ Certo dia, o Senhor  Deus disse a Jonas, filho de Amitai:

[[v32-1-2]]

^<<v32-1-2,2>>^ — Apronte-se, vá à grande cidade de Nínive e grite contra ela, porque a maldade daquela gente chegou aos meus ouvidos.

[[v32-1-3]]

^<<v32-1-3,3>>^ Jonas se aprontou, mas fugiu do Senhor , indo na direção contrária. Ele desceu a Jope e ali encontrou um navio que estava de saída para a Espanha. Pagou a passagem e embarcou a fim de viajar com os marinheiros para a Espanha, para longe do Senhor .

[[v32-1-4]]

^<<v32-1-4,4>>^ No entanto, Deus mandou um forte vento, e houve uma tempestade no mar. Era tão violenta, que o navio estava em perigo de se partir ao meio.

[[v32-1-5]]

^<<v32-1-5,5>>^ Os marinheiros ficaram com muito medo e gritavam por socorro, cada um ao seu deus. E, para que o navio ficasse mais leve, jogaram a carga no mar. Porém Jonas tinha descido ao porão e ali havia se deitado e caído num sono profundo.

[[v32-1-6]]

^<<v32-1-6,6>>^ O capitão do navio o encontrou ali e disse: — Como é que você está aí dormindo? Levante-se e peça socorro ao seu deus. Pode ser que ele tenha pena de nós e não deixe a gente morrer.

[[v32-1-7]]

^<<v32-1-7,7>>^ Os marinheiros disseram uns aos outros: — Vamos tirar a sorte para descobrir quem é o culpado de estarmos neste perigo. Eles fizeram isso, e o nome de Jonas foi sorteado.

[[v32-1-8]]

^<<v32-1-8,8>>^ Então lhe perguntaram: — Agora diga: quem é o culpado de tudo isso? O que você está fazendo aqui? De onde você vem? De que país você é, e qual é o seu povo?

[[v32-1-9]]

^<<v32-1-9,9>>^ — Eu sou hebreu — respondeu Jonas — e adoro o Senhor , o Deus do céu, que fez o mar e a terra.

[[v32-1-10]]

^<<v32-1-10,10>>^ Em seguida, Jonas contou que estava fugindo de Deus, o Senhor . Aí os marinheiros ficaram mais apavorados ainda e disseram: — Veja só o que você fez!

[[v32-1-11]]

^<<v32-1-11,11>>^ A tempestade piorava cada vez mais, de modo que os marinheiros perguntaram a Jonas: — Que devemos fazer com você para que o mar se acalme?

[[v32-1-12]]

^<<v32-1-12,12>>^ Jonas respondeu: — Vocês me peguem e joguem no mar, que ele ficará calmo. Pois eu sei que foi por minha culpa que esta terrível tempestade caiu sobre vocês.

[[v32-1-13]]

^<<v32-1-13,13>>^ Em vez de fazerem isso, os marinheiros começaram a remar com toda a força, tentando levar o navio para a praia; porém não conseguiam nada porque a tempestade piorava ainda mais.

[[v32-1-14]]

^<<v32-1-14,14>>^ Então oraram bem alto, assim: — Ó Senhor  Deus, não nos castigues com a morte, por tirarmos a vida deste homem. Pois és tu, ó Senhor , quem está fazendo isso, e o que está acontecendo é da tua vontade.

[[v32-1-15]]

^<<v32-1-15,15>>^ Em seguida, os marinheiros pegaram Jonas e o jogaram no mar, e logo o mar se acalmou.

[[v32-1-16]]

^<<v32-1-16,16>>^ Eles ficaram com tanto medo do Senhor , que lhe ofereceram um sacrifício  e lhe fizeram promessas.

[[v32-1-17]]

^<<v32-1-17,17>>^ O Senhor  ordenou que um grande peixe engolisse Jonas. E ele ficou dentro do peixe três dias e três noites.

'''

xref:031-obadias/031-obadias-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v32-1-0,Topo>> | xref:032-jonas/032-jonas-002.adoc#v32-2-0[Próximo Capítulo &#62;]