include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-12-1]]

^<<v47-12-1,1>>^ Embora não adiante nada, eu preciso me gabar de mim mesmo. Agora vou falar a respeito das visões e revelações que o Senhor me tem dado.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um cristão que há catorze anos foi levado, de repente, até o mais alto céu. Não sei se isso, de fato, aconteceu ou se ele teve uma visão; somente Deus sabe.

[[v47-12-3]]

^<<v47-12-3,3>>^ Repito: sei que esse homem foi levado, de repente, ao paraíso . Não sei se isso, de fato, aconteceu ou se foi uma visão; somente Deus sabe. E ali ele ouviu coisas que palavras humanas não conseguem contar.

[[v47-12-4]]

^<<v47-12-4,4>>^ Repito: sei que esse homem foi levado, de repente, ao paraíso . Não sei se isso, de fato, aconteceu ou se foi uma visão; somente Deus sabe. E ali ele ouviu coisas que palavras humanas não conseguem contar.

[[v47-12-5]]

^<<v47-12-5,5>>^ Eu me gabarei desse homem. Mas não me gabarei de mim mesmo, a não ser das coisas que mostram as minhas fraquezas.

[[v47-12-6]]

^<<v47-12-6,6>>^ No entanto, se eu quisesse me gabar de mim mesmo, isso não seria uma loucura, porque estaria dizendo a verdade. Mas eu não me gabarei, pois quero que a opinião que as pessoas têm de mim se baseie naquilo que me viram fazer e me ouviram dizer.

[[v47-12-7]]

^<<v47-12-7,7>>^ Mas, para que não ficasse orgulhoso demais por causa das coisas maravilhosas que vi, eu recebi uma doença dolorosa, que é como um espinho no meu corpo. Ela veio como um mensageiro de Satanás para me dar bofetadas e impedir que eu ficasse orgulhoso.

[[v47-12-8]]

^<<v47-12-8,8>>^ Três vezes orei ao Senhor, pedindo que ele me tirasse esse sofrimento.

[[v47-12-9]]

^<<v47-12-9,9>>^ Mas ele me respondeu: "A minha graça  é tudo o que você precisa, pois o meu poder é mais forte quando você está fraco."  Portanto, eu me sinto muito feliz em me gabar das minhas fraquezas, para que assim a proteção do poder de Cristo esteja comigo.

[[v47-12-10]]

^<<v47-12-10,10>>^ Eu me alegro também com as fraquezas, os insultos, os sofrimentos, as perseguições e as dificuldades pelos quais passo por causa de Cristo. Porque, quando perco toda a minha força, então tenho a força de Cristo em mim.

[[v47-12-11]]

^<<v47-12-11,11>>^ Eu estou agindo como um louco, mas foram vocês que me obrigaram a isso. Porque vocês é que deviam falar bem de mim. Pois, mesmo que eu não valha nada, não sou inferior, de modo nenhum, a esses tais "superapóstolos" de vocês.

[[v47-12-12]]

^<<v47-12-12,12>>^ As coisas que provam que, de fato, sou apóstolo  foram feitas entre vocês com muita paciência. Foram sinais, maravilhas e milagres.

[[v47-12-13]]

^<<v47-12-13,13>>^ Como é que vocês foram tratados pior do que as outras igrejas? A única diferença é que eu não exigi que vocês me ajudassem. Por favor, perdoem essa injustiça!

[[v47-12-14]]

^<<v47-12-14,14>>^ Já estou preparado para fazer a minha terceira visita a vocês e novamente não vou exigir que vocês me ajudem. Eu quero vocês e não o dinheiro de vocês. Afinal de contas, são os pais que devem juntar dinheiro para os filhos, e não os filhos, para os pais.

[[v47-12-15]]

^<<v47-12-15,15>>^ Vou ficar contente em gastar tudo o que tenho e até a mim mesmo para ajudá-los. Será que vocês me amarão menos só porque eu os amo tanto?

[[v47-12-16]]

^<<v47-12-16,16>>^ Portanto, vocês vão concordar que eu não exigi nada de vocês. Porém alguém poderá dizer que os enganei e tapeei com mentiras.

[[v47-12-17]]

^<<v47-12-17,17>>^ Por acaso explorei vocês por meio de algum mensageiro que lhes mandei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Eu pedi a Tito que fosse visitá-los e mandei com ele o outro irmão na fé. Por acaso Tito os explorou? Será que nós dois não temos agido do mesmo modo e com o mesmo espírito?

[[v47-12-19]]

^<<v47-12-19,19>>^ Talvez vocês pensem que estamos querendo nos defender diante de vocês, mas não é isso. Falamos como Cristo nos mandaria falar, na presença de Deus. E tudo o que fazemos, queridos amigos, é para ajudar vocês.

[[v47-12-20]]

^<<v47-12-20,20>>^ Tenho medo de que, quando chegar aí, eu os encontre diferentes do que eu gostaria que fossem e que vocês me achem diferente do que gostariam que eu fosse. Tenho medo também de encontrar brigas e ciumeiras, ódio e egoísmo, insultos, falatório, orgulho e desordens.

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]