include::./index.adoc[]

[[v47-4-0]]
=== 2 Coríntios, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-4-1]]

^<<v47-4-1,1>>^ Deus, na sua misericórdia, nos deu essa tarefa, e é por isso que nunca ficamos desanimados.

[[v47-4-2]]

^<<v47-4-2,2>>^ Nós rejeitamos tudo o que é feito escondido e tudo o que é vergonhoso. Não agimos de má-fé, nem falsificamos a mensagem de Deus. Pelo contrário, agimos sempre abertamente, de acordo com a verdade, e assim as pessoas têm uma boa impressão de nós, que vivemos na presença de Deus.

[[v47-4-3]]

^<<v47-4-3,3>>^ Porque, se o evangelho  que anunciamos está escondido, está escondido somente para os que estão se perdendo.

[[v47-4-4]]

^<<v47-4-4,4>>^ Eles não podem crer, pois o deus deste mundo conservou a mente deles na escuridão. Ele não os deixa ver a luz que brilha sobre eles, a luz que vem da boa notícia a respeito da glória  de Cristo, o qual nos mostra como Deus realmente é.

[[v47-4-5]]

^<<v47-4-5,5>>^ Pois nós não anunciamos a nós mesmos; nós anunciamos Jesus Cristo como o Senhor e a nós como servos  de vocês, por causa de Jesus.

[[v47-4-6]]

^<<v47-4-6,6>>^ O Deus que disse: "Que da escuridão brilhe a luz" é o mesmo que fez a luz brilhar no nosso coração. E isso para nos trazer a luz do conhecimento da glória de Deus, que brilha no rosto de Jesus Cristo.

[[v47-4-7]]

^<<v47-4-7,7>>^ Porém nós que temos esse tesouro espiritual somos como potes de barro para que fique claro que o poder supremo pertence a Deus e não a nós.

[[v47-4-8]]

^<<v47-4-8,8>>^ Muitas vezes ficamos aflitos, mas não somos derrotados. Algumas vezes ficamos em dúvida, mas nunca ficamos desesperados.

[[v47-4-9]]

^<<v47-4-9,9>>^ Temos muitos inimigos, mas nunca nos falta um amigo. Às vezes somos gravemente feridos, mas não somos destruídos.

[[v47-4-10]]

^<<v47-4-10,10>>^ Levamos sempre no nosso corpo mortal a morte de Jesus para que também a vida dele seja vista no nosso corpo.

[[v47-4-11]]

^<<v47-4-11,11>>^ Durante a vida inteira estamos sempre em perigo de morte por causa de Jesus, para que a vida dele seja vista neste nosso corpo mortal.

[[v47-4-12]]

^<<v47-4-12,12>>^ De modo que a morte está agindo em nós, e a vida está agindo em vocês.

[[v47-4-13]]

^<<v47-4-13,13>>^ As Escrituras Sagradas  dizem: "Eu cri e por isso falei." Pois assim nós, que temos a mesma fé em Deus, também falamos porque cremos.

[[v47-4-14]]

^<<v47-4-14,14>>^ Pois sabemos que Deus, que ressuscitou o Senhor Jesus, também nos ressuscitará com ele e nos levará, junto com vocês, até a presença dele.

[[v47-4-15]]

^<<v47-4-15,15>>^ Tudo isso aconteceu para o bem de vocês, a fim de que a graça  de Deus alcance um número cada vez maior de pessoas, e estas façam mais orações de agradecimento, para a glória de Deus.

[[v47-4-16]]

^<<v47-4-16,16>>^ Por isso nunca ficamos desanimados. Mesmo que o nosso corpo vá se gastando, o nosso espírito vai se renovando dia a dia.

[[v47-4-17]]

^<<v47-4-17,17>>^ E essa pequena e passageira aflição que sofremos vai nos trazer uma glória  enorme e eterna, muito maior do que o sofrimento.

[[v47-4-18]]

^<<v47-4-18,18>>^ Porque nós não prestamos atenção nas coisas que se veem, mas nas que não se veem. Pois o que pode ser visto dura apenas um pouco, mas o que não pode ser visto dura para sempre.

'''

xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[Próximo Capítulo &#62;]