include::./index.adoc[]

[[v47-3-0]]
=== 2 Coríntios, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-3-1]]

^<<v47-3-1,1>>^ Quando dizemos isso, será que estamos começando a nos elogiar a nós mesmos? Por acaso, como acontece com alguns, nós precisamos entregar cartas de recomendação para vocês ou pedi-las a vocês?

[[v47-3-2]]

^<<v47-3-2,2>>^ Vocês mesmos são a nossa carta, escrita no nosso coração, para ser conhecida e lida por todos.

[[v47-3-3]]

^<<v47-3-3,3>>^ Sim, é claro que vocês são uma carta escrita pelo próprio Cristo e entregue por nós. Ela não foi escrita com tinta, mas com o Espírito do Deus vivo; ela não está gravada em placas de pedra, mas em corações humanos.

[[v47-3-4]]

^<<v47-3-4,4>>^ Dizemos isso por causa da confiança que temos em Deus, por meio de Cristo.

[[v47-3-5]]

^<<v47-3-5,5>>^ Em nós não há nada que nos permita afirmar que somos capazes de fazer esse trabalho, pois a nossa capacidade vem de Deus.

[[v47-3-6]]

^<<v47-3-6,6>>^ É ele quem nos torna capazes de servir à nova aliança , que tem como base não a lei escrita, mas o Espírito de Deus. A lei  escrita mata, mas o Espírito de Deus dá a vida.

[[v47-3-7]]

^<<v47-3-7,7>>^ Quando a lei, que traz a morte, foi gravada em placas de pedra, a glória  de Deus apareceu, e o rosto de Moisés ficou brilhando. O brilho do seu rosto já estava desaparecendo quando ele entregou as placas ao povo de Israel; mas mesmo assim esse brilho era tão forte, que os israelitas não podiam fixar os olhos em Moisés. Se o domínio da lei veio com tanta glória,

[[v47-3-8]]

^<<v47-3-8,8>>^ quanto maior ainda é a glória que acompanha o domínio do Espírito de Deus!

[[v47-3-9]]

^<<v47-3-9,9>>^ A lei, que condena as pessoas, teve glória; porém muito mais glória tem o Espírito, que traz a salvação.

[[v47-3-10]]

^<<v47-3-10,10>>^ Pois a glória que antes era tão grande não é mais nada por causa da glória de agora, que é muito maior.

[[v47-3-11]]

^<<v47-3-11,11>>^ De modo que, se houve glória naquilo que durou somente um pouco de tempo, muito mais glória tem aquilo que dura para sempre.

[[v47-3-12]]

^<<v47-3-12,12>>^ E, porque temos essa esperança, agimos com toda a confiança.

[[v47-3-13]]

^<<v47-3-13,13>>^ Nós não fazemos como Moisés, que cobria o rosto com um véu para que os israelitas não pudessem ver que o seu brilho estava desaparecendo.

[[v47-3-14]]

^<<v47-3-14,14>>^ Mas eles não queriam compreender e, até hoje, quando eles leem os livros da antiga aliança , a mente deles está coberta com o mesmo véu. E esse véu só é tirado quando a pessoa se une com Cristo.

[[v47-3-15]]

^<<v47-3-15,15>>^ Mesmo agora, quando eles leem a Lei de Moisés, o véu ainda cobre a mente deles.

[[v47-3-16]]

^<<v47-3-16,16>>^ Mas o véu pode ser tirado, como dizem as Escrituras Sagradas : "O véu de Moisés foi tirado quando ele se voltou para o Senhor."

[[v47-3-17]]

^<<v47-3-17,17>>^ Aqui a palavra "Senhor" quer dizer o Espírito. E onde o Espírito do Senhor está presente, aí existe liberdade.

[[v47-3-18]]

^<<v47-3-18,18>>^ Portanto, todos nós, com o rosto descoberto, refletimos a glória que vem do Senhor. Essa glória vai ficando cada vez mais brilhante e vai nos tornando cada vez mais parecidos com o Senhor, que é o Espírito.

'''

xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[Próximo Capítulo &#62;]