include::./index.adoc[]

[[v47-11-0]]
=== 2 Coríntios, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-11-1]]

^<<v47-11-1,1>>^ Eu gostaria que vocês me suportassem mesmo quando sou um tanto louco. Por favor, me suportem!

[[v47-11-2]]

^<<v47-11-2,2>>^ O mesmo zelo que Deus tem por vocês eu também tenho. Porque vocês são como uma virgem pura que eu prometi dar em casamento somente a um homem, que é Cristo.

[[v47-11-3]]

^<<v47-11-3,3>>^ Pois, assim como Eva foi enganada pelas mentiras da cobra, eu tenho medo de que a mente de vocês seja corrompida e vocês abandonem a devoção sincera e pura a Cristo.

[[v47-11-4]]

^<<v47-11-4,4>>^ Porque vocês suportam com alegria qualquer um que chega e anuncia um Jesus diferente daquele que nós anunciamos. E aceitam um espírito e um evangelho  completamente diferentes do Espírito de Deus e do evangelho que receberam de nós.

[[v47-11-5]]

^<<v47-11-5,5>>^ Eu não acho que tenho menos valor do que esses tais "superapóstolos"!

[[v47-11-6]]

^<<v47-11-6,6>>^ Talvez eu seja um principiante no falar, mas no conhecimento não sou. Sempre e em todas as situações temos dado provas disso a vocês.

[[v47-11-7]]

^<<v47-11-7,7>>^ Quando anunciei a vocês a boa notícia de Deus, fiz isso completamente de graça. Eu me humilhei para engrandecer vocês. Será que houve algum mal nisso?

[[v47-11-8]]

^<<v47-11-8,8>>^ Enquanto estive trabalhando entre vocês, fui pago por outras igrejas. Por assim dizer, eu estava roubando delas para ajudar vocês.

[[v47-11-9]]

^<<v47-11-9,9>>^ E, durante o tempo em que estive com vocês, quando precisava de alguma coisa, não incomodava ninguém; pois os irmãos que vieram da Macedônia me trouxeram tudo o que eu precisava. O que aconteceu no passado e acontecerá no futuro é isto: eu nunca exigirei que vocês me ajudem.

[[v47-11-10]]

^<<v47-11-10,10>>^ Pela verdade de Cristo, a qual está em mim, eu garanto que ninguém, em nenhum lugar da Acaia, tirará de mim este orgulho de anunciar o evangelho sem cobrar nada.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por que estou dizendo isso? Será que é porque não amo vocês? Deus sabe que os amo!

[[v47-11-12]]

^<<v47-11-12,12>>^ O que estou fazendo agora vou continuar a fazer a fim de evitar que aqueles tais " apóstolos " tenham motivo para se gabar e dizer que fazem um trabalho igual ao nosso.

[[v47-11-13]]

^<<v47-11-13,13>>^ Aqueles homens são apóstolos falsos e não verdadeiros. Eles mentem a respeito dos seus trabalhos e se disfarçam, apresentando-se como verdadeiros apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E isso não é de admirar, pois até Satanás pode se disfarçar e ficar parecendo um anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Portanto, não é nada demais que os servidores dele se disfarcem, apresentando-se como pessoas que fazem o bem. Mas no fim eles receberão exatamente o que as suas ações merecem.

[[v47-11-16]]

^<<v47-11-16,16>>^ Repito: ninguém deve pensar que eu estou louco. Mas, se vocês pensam isso, então me recebam como louco para que assim eu tenha alguma pequena coisa de que me gabar.

[[v47-11-17]]

^<<v47-11-17,17>>^ De fato, o que estou dizendo agora não é o que o Senhor me mandou dizer. Quanto a eu me gabar, estou realmente falando como louco.

[[v47-11-18]]

^<<v47-11-18,18>>^ Já que existem tantas pessoas que se gabam por motivos apenas humanos, eu também vou me gabar de mim mesmo.

[[v47-11-19]]

^<<v47-11-19,19>>^ Vocês são tão sábios e suportam de boa vontade os loucos.

[[v47-11-20]]

^<<v47-11-20,20>>^ Toleram os que mandam em vocês e exploram vocês; toleram os que os enganam, os que os tratam com desprezo e os que lhes dão bofetadas.

[[v47-11-21]]

^<<v47-11-21,21>>^ Tenho até vergonha de confessar que nós fomos tímidos demais e não fomos capazes de fazer coisas como essas. Mas, se os outros se atrevem a se gabar de alguma coisa, eu também vou me atrever, embora isso seja uma loucura.

[[v47-11-22]]

^<<v47-11-22,22>>^ Eles são hebreus? Eu também sou. Eles são israelitas? Eu também sou. Eles são descendentes de Abraão? Eu também sou.

[[v47-11-23]]

^<<v47-11-23,23>>^ Eles são servos  de Cristo? Mas eu sou um servo melhor do que eles, embora, ao dizer isso, eu esteja falando como se fosse louco. Pois eu tenho trabalhado mais do que eles e tenho estado mais vezes na cadeia. Tenho sido chicoteado muito mais do que eles e muitas vezes estive em perigo de morte.

[[v47-11-24]]

^<<v47-11-24,24>>^ Em cinco ocasiões os judeus me deram trinta e nove chicotadas .

[[v47-11-25]]

^<<v47-11-25,25>>^ Três vezes os romanos me bateram com porretes, e uma vez fui apedrejado. Três vezes o navio em que eu estava viajando afundou, e numa dessas vezes passei vinte e quatro horas boiando no mar.

[[v47-11-26]]

^<<v47-11-26,26>>^ Nas muitas viagens que fiz, tenho estado em perigos de inundações e de ladrões; em perigos causados pelos meus patrícios, os judeus, e também pelos não judeus. Tenho estado no meio de perigos nas cidades, nos desertos e em alto-mar; e também em perigos causados por falsos irmãos.

[[v47-11-27]]

^<<v47-11-27,27>>^ Tenho tido trabalhos e canseiras. Muitas vezes tenho ficado sem dormir. Tenho passado fome e sede; têm me faltado casa, comida e roupas.

[[v47-11-28]]

^<<v47-11-28,28>>^ Além dessas e de outras coisas, ainda pesa diariamente sobre mim a preocupação que tenho por todas as igrejas.

[[v47-11-29]]

^<<v47-11-29,29>>^ Quando alguém está fraco, eu também me sinto fraco; e, quando alguém cai em pecado, eu fico muito aflito.

[[v47-11-30]]

^<<v47-11-30,30>>^ Se existe motivo para eu me gabar, então vou me gabar das coisas que mostram a minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai do Senhor Jesus, o Deus que é bendito para sempre, sabe que não estou mentindo.

[[v47-11-32]]

^<<v47-11-32,32>>^ Quando estive na cidade de Damasco, o governador nomeado pelo rei Aretas pôs guardas nos portões da cidade para me prenderem.

[[v47-11-33]]

^<<v47-11-33,33>>^ Porém os meus amigos fizeram com que eu descesse num grande cesto, por uma abertura da muralha, e assim escapei do Governador.

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]