include::./index.adoc[]

[[v47-10-0]]
=== 2 Coríntios, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-10-1]]

^<<v47-10-1,1>>^ Dizem que eu sou humilde quando estou com vocês, mas duro quando estou longe. Pois eu, Paulo, faço este apelo a vocês em nome de Cristo, que foi carinhoso e bondoso.

[[v47-10-2]]

^<<v47-10-2,2>>^ Quando eu for aí, não me obriguem a ser duro. Pois eu tenho certeza de que posso agir com dureza contra os que afirmam que fazemos as coisas por motivos humanos.

[[v47-10-3]]

^<<v47-10-3,3>>^ É claro que somos humanos, mas não lutamos por motivos humanos.

[[v47-10-4]]

^<<v47-10-4,4>>^ As armas que usamos na nossa luta não são do mundo; são armas poderosas de Deus, capazes de destruir fortalezas. E assim destruímos ideias falsas

[[v47-10-5]]

^<<v47-10-5,5>>^ e também todo orgulho humano que não deixa que as pessoas conheçam a Deus. Dominamos todo pensamento humano e fazemos com que ele obedeça a Cristo.

[[v47-10-6]]

^<<v47-10-6,6>>^ E, quando vocês provarem que são obedientes, estaremos prontos para castigar qualquer desobediência.

[[v47-10-7]]

^<<v47-10-7,7>>^ Vocês julgam as coisas pela aparência. Se uma pessoa tem certeza de que pertence a Cristo, deve pensar de novo a respeito disso, pois nós também pertencemos a Cristo, tanto quanto essa pessoa.

[[v47-10-8]]

^<<v47-10-8,8>>^ O Senhor Jesus me deu autoridade sobre vocês, não para destruí-los, mas para fazê-los crescer espiritualmente. E, embora eu tenha me orgulhado um pouco demais da minha autoridade, não tenho nada de que me envergonhar.

[[v47-10-9]]

^<<v47-10-9,9>>^ Não quero que pareça que estou tentando assustar vocês com as minhas cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ Alguém vai dizer: "As cartas de Paulo são severas e duras; mas, quando ele está conosco, é tímido e, quando fala, é um fracasso."

[[v47-10-11]]

^<<v47-10-11,11>>^ Porém essa pessoa deve saber que não existe diferença entre o que escrevemos nas cartas, quando estamos longe, e o que fazemos, quando estamos aí com vocês.

[[v47-10-12]]

^<<v47-10-12,12>>^ É claro que não nos atrevemos a nos igualar ou a nos comparar com aqueles que pensam que são tão importantes. Como são ignorantes! Primeiro eles resolvem quais as medidas que irão usar para se medir e depois eles se julgam de acordo com essas mesmas medidas.

[[v47-10-13]]

^<<v47-10-13,13>>^ Nós não vamos nos orgulhar além de certos limites. Deus é quem põe os limites no nosso campo de trabalho, e ele nos deixou chegar até vocês em Corinto.

[[v47-10-14]]

^<<v47-10-14,14>>^ Desde que vocês estão dentro desses limites, não fomos além deles quando chegamos até aí levando o evangelho  de Cristo.

[[v47-10-15]]

^<<v47-10-15,15>>^ Assim não nos orgulhamos do trabalho que outros têm feito em lugares que vão além dos limites que Deus nos deu. Pelo contrário, esperamos que a fé que vocês têm possa crescer e que nós possamos fazer um trabalho ainda maior entre vocês, sempre dentro dos limites que Deus tem posto para nós.

[[v47-10-16]]

^<<v47-10-16,16>>^ Então poderemos anunciar o evangelho em outras regiões além daquela onde vocês moram. Isso sem entrar em campos de outras pessoas, para não nos orgulharmos do trabalho feito por elas.

[[v47-10-17]]

^<<v47-10-17,17>>^ Como dizem as Escrituras Sagradas : "Quem quiser se orgulhar, que se orgulhe daquilo que o Senhor faz."

[[v47-10-18]]

^<<v47-10-18,18>>^ Pois a pessoa só é aprovada quando o Senhor a aprova e não quando é aprovada por si mesma.

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]