include::./index.adoc[]

[[v47-2-0]]
=== 2 Coríntios, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-2-1]]

^<<v47-2-1,1>>^ Portanto, para não entristecê-los de novo, eu resolvi não ir ver vocês.

[[v47-2-2]]

^<<v47-2-2,2>>^ Pois, se eu entristeço vocês, então quem vai me alegrar? Somente vocês, a quem tenho entristecido!

[[v47-2-3]]

^<<v47-2-3,3>>^ Foi por isso que escrevi aquela carta . O motivo foi que eu não queria ir e ser entristecido pelas próprias pessoas que deveriam me alegrar. Pois eu tenho a certeza de que, quando estou feliz, vocês todos também estão.

[[v47-2-4]]

^<<v47-2-4,4>>^ Eu escrevi aquela carta muito preocupado e triste e derramando muitas lágrimas. Porém não escrevi para fazer com que vocês ficassem tristes, mas para que soubessem do grande amor que tenho por todos vocês.

[[v47-2-5]]

^<<v47-2-5,5>>^ Mas, se alguém fez com que alguma pessoa ficasse triste, não fez isso a mim, mas sim a vocês ou, pelo menos, a alguns de vocês. Escrevo assim para não ser muito duro com esse homem.

[[v47-2-6]]

^<<v47-2-6,6>>^ Basta o castigo que a maioria já deu a ele.

[[v47-2-7]]

^<<v47-2-7,7>>^ Agora vocês devem perdoá-lo e animá-lo para que ele não fique tão triste, que acabe caindo no desespero.

[[v47-2-8]]

^<<v47-2-8,8>>^ Por isso peço que façam com que ele tenha a certeza de que vocês o amam.

[[v47-2-9]]

^<<v47-2-9,9>>^ E foi por isso também que escrevi aquela carta . Eu queria pôr vocês à prova e saber se estão sempre prontos a obedecer aos meus ensinos.

[[v47-2-10]]

^<<v47-2-10,10>>^ Quando vocês perdoam alguém, eu também perdoo. Porque, quando eu perdoo, se é que, de fato, tenho alguma coisa a perdoar, faço isso por causa de vocês, na presença de Cristo,

[[v47-2-11]]

^<<v47-2-11,11>>^ a fim de que Satanás não se aproveite de nós; pois conhecemos bem os planos dele.

[[v47-2-12]]

^<<v47-2-12,12>>^ Quando cheguei à cidade de Trôade para anunciar o evangelho  de Cristo, vi que o Senhor me havia aberto o caminho para o trabalho ali.

[[v47-2-13]]

^<<v47-2-13,13>>^ Mas eu estava muito preocupado porque não tinha conseguido encontrar o nosso irmão Tito. Por isso me despedi dos irmãos dali e fui para a província  da Macedônia.

[[v47-2-14]]

^<<v47-2-14,14>>^ Mas dou graças a Deus porque, unidos com Cristo, somos sempre conduzidos por Deus como prisioneiros no desfile de vitória de Cristo. Como um perfume que se espalha por todos os lugares, somos usados por Deus para que Cristo seja conhecido por todas as pessoas.

[[v47-2-15]]

^<<v47-2-15,15>>^ Porque somos como o cheiro suave do sacrifício  que Cristo oferece a Deus , cheiro que se espalha entre os que estão sendo salvos e os que estão se perdendo.

[[v47-2-16]]

^<<v47-2-16,16>>^ Para os que estão se perdendo, é um mau cheiro que mata; mas, para os que estão sendo salvos, é um perfume muito agradável que dá vida. Então, quem é capaz de realizar um trabalho como esse?

[[v47-2-17]]

^<<v47-2-17,17>>^ Nós não somos como muitas pessoas que entregam a mensagem de Deus como se estivessem fazendo um negócio qualquer. Pelo contrário, foi Deus quem nos enviou, e por isso anunciamos a sua mensagem com sinceridade na presença dele, como mensageiros de Cristo.

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]