include::./index.adoc[]

[[v47-7-0]]
=== 2 Coríntios, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-7-1]]

^<<v47-7-1,1>>^ Meus queridos amigos, todas essas promessas são para nós. Por isso purifiquemos  a nós mesmos de tudo o que torna impuro  o nosso corpo e a nossa alma. E, temendo a Deus , vivamos uma vida completamente dedicada a ele.

[[v47-7-2]]

^<<v47-7-2,2>>^ Deem um lugar para nós no coração de vocês. Nós não prejudicamos ninguém, não causamos a desgraça de ninguém e não procuramos tirar vantagem de ninguém.

[[v47-7-3]]

^<<v47-7-3,3>>^ Não digo isso para condenar vocês. Pois, como eu disse antes, vocês são tão amados por nós, que estamos sempre juntos, tanto para morrer como para viver.

[[v47-7-4]]

^<<v47-7-4,4>>^ Tenho muita confiança em vocês e me orgulho de vocês. No meio de todas as nossas aflições, eu continuo muito animado e cheio de alegria.

[[v47-7-5]]

^<<v47-7-5,5>>^ Mesmo depois de termos chegado à província  da Macedônia, não descansamos nada. Em todos os lugares houve problemas, lutas com os de fora e medo no nosso coração.

[[v47-7-6]]

^<<v47-7-6,6>>^ Porém Deus, que anima os desanimados, nos animou com a chegada de Tito.

[[v47-7-7]]

^<<v47-7-7,7>>^ E não foi somente a chegada dele que nos animou, mas também a informação dada por ele de que vocês o animaram. Ele contou que vocês estão com saudade de mim e disse que estão muito tristes e estão prontos para me defender. Por isso agora estou mais feliz ainda.

[[v47-7-8]]

^<<v47-7-8,8>>^ Não me arrependo de ter escrito aquela carta , embora vocês tenham ficado tristes por causa dela. Quando soube que a carta os deixou tristes por algum tempo, eu poderia ter ficado arrependido.

[[v47-7-9]]

^<<v47-7-9,9>>^ Mas agora estou alegre, não porque vocês ficaram tristes, mas porque aquela tristeza fez com que vocês se arrependessem. Aquela tristeza foi usada por Deus, e assim nós não causamos nenhum mal a vocês.

[[v47-7-10]]

^<<v47-7-10,10>>^ Pois a tristeza que é usada por Deus produz o arrependimento que leva à salvação; e nisso não há motivo para alguém ficar triste. Mas as tristezas deste mundo produzem a morte.

[[v47-7-11]]

^<<v47-7-11,11>>^ Vocês suportaram a tristeza da maneira que agrada a Deus. E vejam agora os resultados: isso fez com que vocês levassem a sério o assunto e resolvessem se defender. Fez também com que vocês ficassem zangados e com medo. Depois ficaram com vontade de me ver e resolveram castigar o culpado. Em tudo isso vocês mostraram que não tiveram nenhuma culpa naquele caso.

[[v47-7-12]]

^<<v47-7-12,12>>^ Portanto, embora tivesse escrito aquela carta, eu não a escrevi por causa de quem ofendeu , nem por causa da pessoa que foi ofendida. Pelo contrário, escrevi a carta para tornar claro a vocês que Deus sabe do grande cuidado que vocês têm por nós.

[[v47-7-13]]

^<<v47-7-13,13>>^ Foi por isso que ficamos animados. Além do ânimo que recebemos, ficamos mais contentes ainda vendo a alegria de Tito; pois todos vocês o têm ajudado a sentir-se bem.

[[v47-7-14]]

^<<v47-7-14,14>>^ Eu havia falado muito bem de vocês a ele, e vocês não me desapontaram. Temos sempre dito a verdade a vocês. Assim também é verdadeiro o elogio que fizemos a Tito a respeito de vocês.

[[v47-7-15]]

^<<v47-7-15,15>>^ E o amor dele por vocês cresce cada vez mais quando ele lembra como vocês todos estavam prontos para obedecer e como o receberam com humildade e respeito.

[[v47-7-16]]

^<<v47-7-16,16>>^ Estou alegre por poder confiar completamente em vocês.

'''

xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[Próximo Capítulo &#62;]