include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-6-1]]

^<<v47-6-1,1>>^ Portanto, nós, como companheiros de trabalho no serviço de Deus, pedimos o seguinte: não deixem que fique sem proveito a graça  de Deus, a qual vocês receberam.

[[v47-6-2]]

^<<v47-6-2,2>>^ Escutem o que Deus diz: "Quando chegou o tempo de mostrar a minha bondade, eu atendi o seu pedido e o socorri quando chegou o dia da salvação." Escutem! Este é o tempo em que Deus mostra a sua bondade. Hoje é o dia de ser salvo.

[[v47-6-3]]

^<<v47-6-3,3>>^ Não queremos que alguém ache defeito no nosso trabalho e por isso fazemos o possível para não atrapalhar ninguém.

[[v47-6-4]]

^<<v47-6-4,4>>^ Pelo contrário, em tudo mostramos que somos servos  de Deus, suportando com muita paciência as aflições, os sofrimentos e as dificuldades.

[[v47-6-5]]

^<<v47-6-5,5>>^ Temos sido chicoteados, presos e agredidos nas agitações populares. Temos trabalhado demais, temos ficado sem dormir e sem comer.

[[v47-6-6]]

^<<v47-6-6,6>>^ Por meio da nossa pureza, conhecimento, paciência e delicadeza, mostramos que somos servos de Deus. Por meio do Espírito Santo, temos mostrado isso pelo nosso amor verdadeiro,

[[v47-6-7]]

^<<v47-6-7,7>>^ pela mensagem da verdade e pelo poder de Deus. Por vivermos em obediência à vontade de Deus, temos as armas que usamos tanto para atacar como para nos defender.

[[v47-6-8]]

^<<v47-6-8,8>>^ Somos elogiados e caluniados; alguns nos insultam, outros falam bem de nós. Somos tratados como mentirosos, mas falamos a verdade;

[[v47-6-9]]

^<<v47-6-9,9>>^ somos tratados como desconhecidos, embora sejamos bem-conhecidos de todos; somos tratados como se estivéssemos mortos, mas, como vocês estão vendo, continuamos vivos. Temos sido castigados, mas não fomos mortos.

[[v47-6-10]]

^<<v47-6-10,10>>^ Às vezes ficamos tristes, outras vezes ficamos alegres. Parecemos pobres, mas enriquecemos muitas pessoas. Parece que não temos nada, mas na verdade possuímos tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Queridos amigos de Corinto, temos falado francamente e temos aberto completamente o nosso coração para vocês.

[[v47-6-12]]

^<<v47-6-12,12>>^ Não temos fechado o nosso coração; vocês é que têm fechado o coração de vocês para nós.

[[v47-6-13]]

^<<v47-6-13,13>>^ Eu falo com vocês como se vocês fossem meus filhos. Tenham por nós os mesmos sentimentos que temos para com vocês e abram completamente o coração de vocês para nós.

[[v47-6-14]]

^<<v47-6-14,14>>^ Não se juntem com descrentes para trabalhar com eles. Pois como é que o certo pode ter alguma coisa a ver com o errado? Como é que a luz e a escuridão podem viver juntas?

[[v47-6-15]]

^<<v47-6-15,15>>^ Como podem Cristo e o Diabo estar de acordo? O que é que um cristão e um descrente têm em comum?

[[v47-6-16]]

^<<v47-6-16,16>>^ Que relação pode haver entre o Templo de Deus e os ídolos? Pois nós somos o templo do Deus vivo, como o próprio Deus já disse: "Eu vou morar e viver com eles. Serei o Deus deles, e eles serão o meu povo."

[[v47-6-17]]

^<<v47-6-17,17>>^ E o Senhor Todo-Poderoso diz: "Saiam do meio dos pagãos e separem-se deles. Não toquem em nada que seja impuro , e então eu aceitarei vocês.

[[v47-6-18]]

^<<v47-6-18,18>>^ Eu serei o pai de vocês, e vocês serão meus filhos e minhas filhas."

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]