include::./index.adoc[]

[[v47-8-0]]
=== 2 Coríntios, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-8-1]]

^<<v47-8-1,1>>^ Irmãos, queremos que vocês saibam o que a graça  de Deus tem feito nas igrejas da província  da Macedônia.

[[v47-8-2]]

^<<v47-8-2,2>>^ Os irmãos dali têm sido muito provados pelas aflições por que têm passado. Mas a alegria deles foi tanta, que, embora sendo muito pobres, eles deram ofertas com grande generosidade.

[[v47-8-3]]

^<<v47-8-3,3>>^ Afirmo a vocês que eles fizeram tudo o que podiam e mais ainda. E, com toda a boa vontade,

[[v47-8-4]]

^<<v47-8-4,4>>^ pediram com insistência que os deixássemos participar da ajuda para o povo de Deus da Judeia e eles insistiram nisso.

[[v47-8-5]]

^<<v47-8-5,5>>^ E fizeram muito mais do que esperávamos. Primeiro, eles deram a si mesmos ao Senhor e depois, pela vontade de Deus, eles se deram a nós também.

[[v47-8-6]]

^<<v47-8-6,6>>^ De modo que pedimos a Tito, que começou a recolher essas ofertas, que continuasse e ajudasse vocês a completarem esse serviço especial de amor.

[[v47-8-7]]

^<<v47-8-7,7>>^ Vocês mostram que, em tudo, são mais ricos do que os outros: na fé, na palavra, no conhecimento, na vontade de ajudar os outros e no nosso amor por vocês. E nesse novo serviço de amor queremos também que façam mais do que os outros.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não estou querendo mandar em vocês. O que eu estou querendo é que conheçam o entusiasmo com que as igrejas da Macedônia deram ofertas, para que assim vocês vejam se o amor de vocês é verdadeiro ou não.

[[v47-8-9]]

^<<v47-8-9,9>>^ Porque vocês já conhecem o grande amor do nosso Senhor Jesus Cristo: ele era rico, mas, por amor a vocês, ele se tornou pobre a fim de que vocês se tornassem ricos por meio da pobreza dele.

[[v47-8-10]]

^<<v47-8-10,10>>^ Minha opinião sobre o assunto é esta: é melhor para vocês que terminem agora o que começaram no ano passado. Vocês foram os primeiros não somente a ajudar, mas também a querer ajudar.

[[v47-8-11]]

^<<v47-8-11,11>>^ Portanto, continuem e completem o trabalho. Façam isso com o mesmo entusiasmo que tiveram no princípio, dando de acordo com o que têm.

[[v47-8-12]]

^<<v47-8-12,12>>^ Porque, se alguém quer dar, Deus aceita a oferta conforme o que a pessoa tem. Deus não pede o que a pessoa não tem.

[[v47-8-13]]

^<<v47-8-13,13>>^ Não estou querendo aliviar os outros e pôr um peso sobre vocês. Já que agora vocês têm bastante, é justo que ajudem os que estão necessitados. Em alguma outra ocasião, se vocês precisarem, e eles tiverem bastante, aí eles poderão ajudá-los. Assim todos são tratados com igualdade.

[[v47-8-14]]

^<<v47-8-14,14>>^ Não estou querendo aliviar os outros e pôr um peso sobre vocês. Já que agora vocês têm bastante, é justo que ajudem os que estão necessitados. Em alguma outra ocasião, se vocês precisarem, e eles tiverem bastante, aí eles poderão ajudá-los. Assim todos são tratados com igualdade.

[[v47-8-15]]

^<<v47-8-15,15>>^ Como dizem as Escrituras Sagradas : "Ao que muito pegou, nada sobrou; ao que pouco pegou, nada faltou."

[[v47-8-16]]

^<<v47-8-16,16>>^ Agradecemos muito a Deus porque pôs no coração de Tito o mesmo desejo que nós temos de ajudar vocês.

[[v47-8-17]]

^<<v47-8-17,17>>^ Ele aceitou o nosso pedido e, como quer ajudá-los, resolveu ir com toda a boa vontade encontrar-se com vocês.

[[v47-8-18]]

^<<v47-8-18,18>>^ Junto com ele estamos enviando o irmão que é muito respeitado em todas as igrejas pelo seu trabalho de anunciar o evangelho .

[[v47-8-19]]

^<<v47-8-19,19>>^ Além disso esse irmão foi escolhido e indicado pelas igrejas para viajar conosco a fim de nos ajudar nesse serviço de amor que fazemos para a glória  do Senhor e também para mostrar que, de fato, queremos ajudar.

[[v47-8-20]]

^<<v47-8-20,20>>^ Queremos evitar assim que outros nos critiquem por causa da maneira pela qual estamos recolhendo essa grande oferta.

[[v47-8-21]]

^<<v47-8-21,21>>^ A nossa vontade é fazer aquilo que tanto o Senhor como as pessoas acham certo.

[[v47-8-22]]

^<<v47-8-22,22>>^ Com eles, estamos enviando outro irmão nosso. Muitas vezes o pusemos à prova e assim sabemos que ele está sempre pronto para ajudar. E, agora que ele tem tanta confiança em vocês, está com muito mais vontade ainda de auxiliar.

[[v47-8-23]]

^<<v47-8-23,23>>^ A respeito de Tito afirmo que ele é meu companheiro de trabalho na ajuda que dou a vocês. E, quanto aos outros irmãos que vão com ele, são representantes das igrejas e trazem glória para Cristo.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]