include::./index.adoc[]

[[v47-1-0]]
=== 2 Coríntios, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v47-1-1]]

^<<v47-1-1,1>>^ Eu, Paulo, apóstolo  de Cristo Jesus pela vontade de Deus, escrevo junto com o nosso irmão Timóteo esta carta à igreja de Deus que está na cidade de Corinto e também a todo o povo de Deus espalhado por toda a província  da Acaia.

[[v47-1-2]]

^<<v47-1-2,2>>^ Que a graça  e a paz de Deus, o nosso Pai, e do Senhor Jesus Cristo estejam com vocês!

[[v47-1-3]]

^<<v47-1-3,3>>^ Louvado seja o Deus e Pai do nosso Senhor Jesus Cristo, o Pai bondoso, o Deus de quem todos recebem ajuda!

[[v47-1-4]]

^<<v47-1-4,4>>^ Ele nos auxilia em todas as nossas aflições para podermos ajudar os que têm as mesmas aflições que nós temos. E nós damos aos outros a mesma ajuda que recebemos de Deus.

[[v47-1-5]]

^<<v47-1-5,5>>^ Porque, assim como tomamos parte nos muitos sofrimentos de Cristo, assim também, por meio dele, participamos da sua grande ajuda.

[[v47-1-6]]

^<<v47-1-6,6>>^ Se sofremos, é para que vocês recebam ajuda e salvação. Se somos ajudados, então vocês também são e recebem forças para suportar com paciência os mesmos sofrimentos que nós suportamos.

[[v47-1-7]]

^<<v47-1-7,7>>^ Desse modo a esperança que temos em vocês está firme. Pois sabemos que, assim como vocês tomam parte nos nossos sofrimentos, assim também recebem a ajuda que Deus dá.

[[v47-1-8]]

^<<v47-1-8,8>>^ Irmãos, queremos que saibam das aflições pelas quais passamos na província  da Ásia. Os sofrimentos que suportamos foram tão grandes e tão duros, que já não tínhamos mais esperança de escapar de lá com vida.

[[v47-1-9]]

^<<v47-1-9,9>>^ Nós nos sentíamos como condenados à morte. Mas isso aconteceu para que aprendêssemos a confiar não em nós mesmos e sim em Deus, que ressuscita os mortos.

[[v47-1-10]]

^<<v47-1-10,10>>^ Ele nos salvou e continuará a nos salvar desses terríveis perigos de morte. Sim, nós temos posto nele a nossa esperança, na certeza de que ele continuará a nos salvar,

[[v47-1-11]]

^<<v47-1-11,11>>^ enquanto vocês nos ajudam, orando por nós. Assim Deus responderá às muitas orações feitas em nosso favor e nos abençoará; e muitos lhe agradecerão as bênçãos que ele nos dará.

[[v47-1-12]]

^<<v47-1-12,12>>^ É disto que temos orgulho: a nossa consciência nos afirma que a nossa maneira de viver no mundo, e especialmente em relação a vocês, tem sido dirigida pela franqueza e sinceridade que Deus nos dá e também pelo poder da sua graça  e não pela sabedoria humana.

[[v47-1-13]]

^<<v47-1-13,13>>^ Pois escrevemos a vocês somente o que vocês podem ler e entender. Agora vocês nos entendem só em parte, mas espero que cheguem a nos compreender completamente, para que, no Dia do nosso Senhor Jesus , vocês tenham orgulho de nós, como nós temos de vocês.

[[v47-1-14]]

^<<v47-1-14,14>>^ Pois escrevemos a vocês somente o que vocês podem ler e entender. Agora vocês nos entendem só em parte, mas espero que cheguem a nos compreender completamente, para que, no Dia do nosso Senhor Jesus , vocês tenham orgulho de nós, como nós temos de vocês.

[[v47-1-15]]

^<<v47-1-15,15>>^ Eu estava tão certo de tudo isso, que no início fiz planos para ir visitar vocês a fim de que vocês pudessem ser abençoados mais uma vez.

[[v47-1-16]]

^<<v47-1-16,16>>^ De fato, eu estava pensando em visitá-los na minha ida para a província  da Macedônia e também na volta, a fim de conseguir ajuda para a minha viagem à Judeia.

[[v47-1-17]]

^<<v47-1-17,17>>^ Será que fui irresponsável quando resolvi fazer isso? Será que, ao fazer os meus planos, penso somente nos meus próprios interesses e por isso digo "sim, sim" e "não, não" ao mesmo tempo?

[[v47-1-18]]

^<<v47-1-18,18>>^ Em nome de Deus, que é verdadeiro, o que prometi a vocês não foi um "sim" e um "não" ao mesmo tempo.

[[v47-1-19]]

^<<v47-1-19,19>>^ Pois Jesus Cristo, o Filho de Deus, que foi anunciado entre vocês por Silas, por Timóteo e por mim mesmo, não é "sim" e "não" ao mesmo tempo. Pelo contrário, ele é o "sim" de Deus

[[v47-1-20]]

^<<v47-1-20,20>>^ porque é o "sim" de todas as promessas de Deus. Por isso dizemos " amém ", por meio de Jesus Cristo, para a glória  de Deus.

[[v47-1-21]]

^<<v47-1-21,21>>^ Pois é o próprio Deus que nos dá, a nós e a vocês, a certeza de que estamos unidos com Cristo. E foi Deus quem nos separou para si mesmo.

[[v47-1-22]]

^<<v47-1-22,22>>^ Como dono ele pôs a sua marca em nós e colocou no nosso coração o Espírito Santo, que é a garantia das coisas que ele guarda para nós.

[[v47-1-23]]

^<<v47-1-23,23>>^ Eu chamo Deus como minha testemunha; ele conhece o meu coração. A fim de evitar aborrecimentos para vocês, resolvi não ir até Corinto.

'''

xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[&#60; Capítulo Anterior] | <<v47-1-0,Topo>> | xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[Próximo Capítulo &#62;]