include::./index.adoc[]

[[v10-8-0]]
=== 2 Samuel, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-8-1]]

^<<v10-8-1,1>>^ Algum tempo depois, Davi atacou os filisteus, derrotou-os e acabou com o poder deles naquela região.

[[v10-8-2]]

^<<v10-8-2,2>>^ Ele também derrotou os moabitas. Fez com que se deitassem no chão, mediu-os com uma corda e matou dois terços deles. Assim os moabitas se tornaram escravos de Davi e lhe pagavam impostos.

[[v10-8-3]]

^<<v10-8-3,3>>^ Então Davi atacou o rei de Zoba, Hadadezer, filho de Reobe, quando este foi tomar de novo as terras que ficam perto do rio Eufrates.

[[v10-8-4]]

^<<v10-8-4,4>>^ Davi prendeu mil e setecentos cavaleiros de Hadadezer e vinte mil dos seus soldados da infantaria; também aleijou os cavalos que puxavam os carros, deixando cavalos somente para cem carros.

[[v10-8-5]]

^<<v10-8-5,5>>^ Os sírios de Damasco foram socorrer Hadadezer, e Davi matou vinte e dois mil deles.

[[v10-8-6]]

^<<v10-8-6,6>>^ Em seguida colocou acampamentos militares na terra deles. Davi os dominou, e eles lhe pagavam impostos. O Senhor  Deus fez com que Davi fosse vitorioso em todos os lugares aonde ia.

[[v10-8-7]]

^<<v10-8-7,7>>^ Davi tomou dos oficiais de Hadadezer os escudos  de ouro que eles usavam e os levou para Jerusalém.

[[v10-8-8]]

^<<v10-8-8,8>>^ Também levou uma grande quantidade de bronze das cidades de Betá e Berotai, que eram governadas por Hadadezer.

[[v10-8-9]]

^<<v10-8-9,9>>^ O rei Toí, da cidade de Hamate, soube que Davi tinha derrotado todo o exército de Hadadezer.

[[v10-8-10]]

^<<v10-8-10,10>>^ Então enviou o seu filho Jorão para cumprimentar Davi e para lhe dar parabéns por ter vencido Hadadezer. Acontece que Toí havia lutado muitas vezes contra Hadadezer. Jorão levou para Davi objetos feitos de prata, de ouro e de bronze.

[[v10-8-11]]

^<<v10-8-11,11>>^ E o rei Davi os separou para serem usados na adoração ao Senhor , juntamente com a prata e o ouro que havia tomado dos povos que havia conquistado,

[[v10-8-12]]

^<<v10-8-12,12>>^ isto é, os edomitas, os moabitas, os amonitas, os filisteus e os amalequitas. E fez a mesma coisa com parte do que havia tirado de Hadadezer.

[[v10-8-13]]

^<<v10-8-13,13>>^ Davi se tornou ainda mais famoso quando voltou depois de ter matado dezoito mil edomitas no vale do Sal.

[[v10-8-14]]

^<<v10-8-14,14>>^ Ele colocou acampamentos militares em todo o país de Edom e dominou o povo dali. O Senhor  Deus fez com que Davi fosse vitorioso em todos os lugares aonde ia.

[[v10-8-15]]

^<<v10-8-15,15>>^ Davi governou todo o povo de Israel e fez com que eles fossem sempre tratados com igualdade e justiça.

[[v10-8-16]]

^<<v10-8-16,16>>^ Joabe, cuja mãe era Zeruia, comandava o seu exército. Josafá, filho de Ailude, era o conselheiro do rei.

[[v10-8-17]]

^<<v10-8-17,17>>^ Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes. Seraías era o escrivão.

[[v10-8-18]]

^<<v10-8-18,18>>^ Benaías, filho de Joiada, era o chefe dos queretitas e dos peletitas . E os filhos de Davi eram sacerdotes.

'''

xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[&#60; Capítulo Anterior] | <<v10-8-0,Topo>> | xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[Próximo Capítulo &#62;]