include::./index.adoc[]

[[v10-6-0]]
=== 2 Samuel, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-6-1]]

^<<v10-6-1,1>>^ Mais uma vez Davi reuniu os melhores soldados de Israel, num total de trinta mil homens.

[[v10-6-2]]

^<<v10-6-2,2>>^ Levou-os à cidade de Baalá, em Judá, para pegarem a arca da aliança , que tem o nome do Senhor  Todo-Poderoso, que se assenta no seu trono, entre os querubins .

[[v10-6-3]]

^<<v10-6-3,3>>^ Colocaram a arca num carro de bois, novo, e a tiraram da casa de Abinadabe, que ficava num monte. Uzá e Aiô, filhos de Abinadabe, guiavam o carro

[[v10-6-4]]

^<<v10-6-4,4>>^ que carregava a arca. Aiô caminhava na frente.

[[v10-6-5]]

^<<v10-6-5,5>>^ Davi e todos os israelitas dançavam e cantavam com todas as suas forças em louvor a Deus, o Senhor . Eles tocavam harpas , liras , tambores, castanholas e pratos.

[[v10-6-6]]

^<<v10-6-6,6>>^ Quando chegaram ao campo de descascar cereais que pertencia a Nacom, os bois tropeçaram. Então Uzá estendeu a mão e segurou a arca da aliança.

[[v10-6-7]]

^<<v10-6-7,7>>^ O Senhor  Deus ficou irado  com Uzá, por sua falta de respeito, e o matou. E Uzá morreu ali, ao lado da arca.

[[v10-6-8]]

^<<v10-6-8,8>>^ Davi ficou furioso porque o Senhor , na sua ira, havia castigado Uzá; assim até hoje  aquele lugar é chamado de Peres-Uzá .

[[v10-6-9]]

^<<v10-6-9,9>>^ Então Davi ficou com medo de Deus, o Senhor , e disse: — E agora como é que poderei levar comigo a arca da aliança?

[[v10-6-10]]

^<<v10-6-10,10>>^ Assim Davi resolveu não levar a arca para a sua cidade de Jerusalém; em vez disso, ele mudou de direção e a levou para a casa de Obede-Edom, que era da cidade de Gate.

[[v10-6-11]]

^<<v10-6-11,11>>^ A arca da aliança ficou ali três meses, e o Senhor  abençoou Obede-Edom e a sua família.

[[v10-6-12]]

^<<v10-6-12,12>>^ O rei Davi soube que, por causa da arca, o Senhor  havia abençoado a família de Obede-Edom e tudo o que ele tinha. Então tirou a arca da casa de Obede-Edom e, com uma grande festa, a levou para a Cidade de Davi .

[[v10-6-13]]

^<<v10-6-13,13>>^ Depois que os homens que carregavam a arca deram seis passos, Davi ofereceu a Deus em sacrifício  um touro e um bezerro gordo.

[[v10-6-14]]

^<<v10-6-14,14>>^ Davi, vestindo um manto sacerdotal  de linho, dançou com todo o entusiasmo em louvor a Deus, o Senhor .

[[v10-6-15]]

^<<v10-6-15,15>>^ E assim ele e todos os israelitas levaram a arca da aliança para Jerusalém, com gritos de alegria e sons de trombetas.

[[v10-6-16]]

^<<v10-6-16,16>>^ Quando a arca estava entrando na cidade, Mical, filha de Saul, olhou pela janela, viu o rei Davi pulando e dançando em louvor ao Senhor . Então sentiu por ele um profundo desprezo.

[[v10-6-17]]

^<<v10-6-17,17>>^ Levaram a arca e a colocaram no seu lugar, na barraca que Davi tinha preparado para ela. Então ele ofereceu a Deus, o Senhor , sacrifícios que foram completamente queimados e ofertas de paz.

[[v10-6-18]]

^<<v10-6-18,18>>^ Quando acabou de oferecer os sacrifícios e as ofertas, Davi abençoou o povo em nome do Senhor  Todo-Poderoso.

[[v10-6-19]]

^<<v10-6-19,19>>^ Depois deu a cada homem e a cada mulher de Israel um pão, um pedaço de carne assada e passas. Em seguida todos foram para casa.

[[v10-6-20]]

^<<v10-6-20,20>>^ Davi voltou para casa a fim de estar com a sua família, e Mical, filha de Saul, saiu para encontrá-lo. Ela disse: — Que bela figura fez hoje o rei de Israel! Parecia um sem-vergonha, mostrando o corpo para as empregadas dos seus funcionários!

[[v10-6-21]]

^<<v10-6-21,21>>^ Davi respondeu: — Eu estava dançando em louvor ao Senhor , que preferiu me escolher em vez de escolher o seu pai e os descendentes dele e me fez o líder de Israel, o seu povo. Pois eu continuarei a dançar em louvor ao Senhor

[[v10-6-22]]

^<<v10-6-22,22>>^ e me humilharei ainda mais diante dele. Você pode pensar que eu não sou nada, mas aquelas moças de quem você falou vão me dar muito valor!

[[v10-6-23]]

^<<v10-6-23,23>>^ E Mical, filha de Saul, nunca teve filhos.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]