include::./index.adoc[]

[[v10-17-0]]
=== 2 Samuel, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-17-1]]

^<<v10-17-1,1>>^ Depois Aitofel disse a Absalão: — Deixe-me escolher doze mil homens, e eu sairei esta noite para perseguir Davi.

[[v10-17-2]]

^<<v10-17-2,2>>^ Eu o atacarei enquanto ele está cansado e desanimado. Ele ficará com medo, e todos os seus homens fugirão. Então matarei somente o rei

[[v10-17-3]]

^<<v10-17-3,3>>^ e trarei de volta todos os homens dele para o senhor, como uma esposa que volta para o seu marido. Já que o senhor quer matar somente um homem, o resto do povo será deixado em paz.

[[v10-17-4]]

^<<v10-17-4,4>>^ Absalão achou que esse conselho era bom, e todos os líderes israelitas também acharam.

[[v10-17-5]]

^<<v10-17-5,5>>^ Aí Absalão disse: — Chamem agora Husai, e vamos ouvir o que ele tem a dizer.

[[v10-17-6]]

^<<v10-17-6,6>>^ Quando Husai chegou, Absalão disse: — O conselho que Aitofel nos deu é este; devemos segui-lo? Se não, diga você o que devemos fazer.

[[v10-17-7]]

^<<v10-17-7,7>>^ Husai respondeu: — Desta vez o conselho de Aitofel não é bom.

[[v10-17-8]]

^<<v10-17-8,8>>^ O senhor sabe que o seu pai Davi e os seus homens são lutadores valentes e que eles estão furiosos como uma ursa na floresta, de quem roubaram os filhotes. O seu pai é um soldado experiente e durante a noite ele não fica com os seus soldados.

[[v10-17-9]]

^<<v10-17-9,9>>^ Agora mesmo ele deve estar escondido numa caverna ou em algum outro lugar. Logo que Davi atacar os seus soldados, todos os que ouvirem falar a respeito disso dirão que os soldados de Absalão foram derrotados.

[[v10-17-10]]

^<<v10-17-10,10>>^ Então até os soldados mais corajosos, mesmo aqueles que são ferozes como leões, ficarão com medo. Pois todos em Israel sabem que o seu pai é um grande soldado e que os homens que estão com ele são lutadores valentes.

[[v10-17-11]]

^<<v10-17-11,11>>^ O meu conselho é que o senhor reúna, de uma ponta a outra do país, todos os israelitas, tantos quantos são os grãos de areia da praia do mar, e que o senhor mesmo os guie na batalha.

[[v10-17-12]]

^<<v10-17-12,12>>^ Onde quer que Davi estiver, nós o encontraremos antes mesmo que ele saiba o que está acontecendo. Assim nem ele nem nenhum dos seus homens escaparão.

[[v10-17-13]]

^<<v10-17-13,13>>^ Se ele fugir para dentro de alguma cidade construída num morro, todo o nosso povo trará cordas, arrasará a cidade e não deixará nem uma pedra lá em cima.

[[v10-17-14]]

^<<v10-17-14,14>>^ Aí Absalão e todos os israelitas disseram: — O conselho de Husai é melhor do que o de Aitofel. O Senhor  Deus havia resolvido que os bons conselhos de Aitofel não seriam seguidos, para que assim o castigo do Senhor  caísse sobre Absalão.

[[v10-17-15]]

^<<v10-17-15,15>>^ Então Husai contou aos sacerdotes Zadoque e Abiatar o conselho que tinha dado a Absalão e aos líderes israelitas e também o conselho que Aitofel tinha dado.

[[v10-17-16]]

^<<v10-17-16,16>>^ E disse: — Agora mandem depressa uma mensagem a Davi dizendo a ele que não passe a noite nos caminhos do deserto. Que Davi atravesse o rio Jordão imediatamente para que ele e os seus homens não sejam todos destruídos!

[[v10-17-17]]

^<<v10-17-17,17>>^ Jônatas e Aimaás estavam esperando perto da fonte de Rogel porque não queriam se arriscar a serem vistos entrando na cidade. Uma empregada ia lá de vez em quando e informava sobre o que estava acontecendo; então eles iam contar ao rei Davi.

[[v10-17-18]]

^<<v10-17-18,18>>^ Mas dessa vez um rapaz os viu e contou a Absalão. Então Jônatas e Aimaás foram depressa para a casa de um certo homem, na cidade de Baurim. Havia um poço perto da casa, e eles entraram dentro dele.

[[v10-17-19]]

^<<v10-17-19,19>>^ A esposa do homem pegou uma coberta, estendeu sobre a boca do poço e em cima dela espalhou cereais socados para que ninguém pudesse perceber nada.

[[v10-17-20]]

^<<v10-17-20,20>>^ Os oficiais de Absalão chegaram lá e perguntaram à mulher: — Onde estão Aimaás e Jônatas? — Eles atravessaram o rio! — respondeu ela. Aí os homens os procuraram, mas não conseguiram achar; então voltaram para Jerusalém.

[[v10-17-21]]

^<<v10-17-21,21>>^ Depois que eles foram embora, Aimaás e Jônatas saíram do poço e foram avisar o rei Davi. Contaram o que Aitofel tinha planejado contra ele e disseram: — Atravesse o rio depressa!

[[v10-17-22]]

^<<v10-17-22,22>>^ Então Davi e os seus homens começaram a atravessar o rio Jordão e, ao nascer do dia, todos eles já haviam atravessado.

[[v10-17-23]]

^<<v10-17-23,23>>^ Quando Aitofel viu que o seu conselho não tinha sido seguido, arreou o seu jumento e voltou para a sua cidade. E, depois de pôr os seus negócios em ordem, enforcou-se. E foi sepultado no túmulo do seu pai.

[[v10-17-24]]

^<<v10-17-24,24>>^ Quando Absalão e os seus soldados atravessaram o rio Jordão, Davi já havia chegado à cidade de Maanaim.

[[v10-17-25]]

^<<v10-17-25,25>>^ Absalão tinha colocado Amasa no comando do seu exército, no lugar de Joabe. Amasa era filho de um homem chamado Itra, o ismaelita; a mãe dele era Abigail, filha de Naás e irmã de Zeruia, a mãe de Joabe.

[[v10-17-26]]

^<<v10-17-26,26>>^ Absalão e os israelitas acamparam na terra de Gileade.

[[v10-17-27]]

^<<v10-17-27,27>>^ Quando Davi chegou a Maanaim, encontrou-se com Sobi, filho de Naás, da cidade de Rabá, em Amom; com Maquir, filho de Amiel, da cidade de Lo-Debar; e com Barzilai, que era da cidade de Rogelim, em Gileade.

[[v10-17-28]]

^<<v10-17-28,28>>^ Eles levaram bacias, vasilhas de barro, camas e também alimentos para Davi e os seus homens. Levaram também trigo, cevada , farinha, feijão, grãos torrados, ervilhas, mel, queijo, coalhada e algumas ovelhas. Eles sabiam que, no deserto Davi, e os seus homens ficariam com fome, com sede e cansados.

'''

xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]