include::./index.adoc[]

[[v10-19-0]]
=== 2 Samuel, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-19-1]]

^<<v10-19-1,1>>^ Contaram a Joabe que o rei Davi estava chorando e se lamentando por causa de Absalão.

[[v10-19-2]]

^<<v10-19-2,2>>^ Assim, naquele dia, a alegria da vitória virou tristeza para toda a tropa de Davi porque eles souberam que o rei estava chorando a morte do seu filho.

[[v10-19-3]]

^<<v10-19-3,3>>^ Eles voltaram e entraram na cidade em silêncio, como fazem os soldados que fogem da batalha, envergonhados.

[[v10-19-4]]

^<<v10-19-4,4>>^ O rei havia coberto o rosto e gritava alto: — Ó meu filho! Meu filho Absalão! Absalão, meu filho!

[[v10-19-5]]

^<<v10-19-5,5>>^ Então Joabe foi à casa do rei e lhe disse: — Hoje o senhor humilhou os seus soldados, aqueles que salvaram a sua vida, a vida dos seus filhos e filhas e a vida das suas esposas e concubinas .

[[v10-19-6]]

^<<v10-19-6,6>>^ O senhor odeia os que o amam e ama aqueles que o odeiam. E mostrou que os seus oficiais e os seus soldados não valem nada para o senhor. Eu estou vendo agora que o senhor ficaria muito feliz se hoje Absalão estivesse vivo e todos nós estivéssemos mortos.

[[v10-19-7]]

^<<v10-19-7,7>>^ Vá agora e dê uma palavra de elogio aos seus soldados. Se não fizer isso, eu juro, em nome de Deus, o Senhor , que amanhã de manhã nenhum deles estará do seu lado. E esse seria o pior desastre de toda a sua vida.

[[v10-19-8]]

^<<v10-19-8,8>>^ Então o rei se levantou e foi sentar-se perto do portão da cidade. Os seus soldados souberam que ele estava lá e se reuniram todos em volta dele. Enquanto isso, todos os israelitas tinham fugido, cada um para a sua casa.

[[v10-19-9]]

^<<v10-19-9,9>>^ E, em todo o país, eles começaram a brigar. Eles diziam: — O rei Davi nos livrou dos nossos inimigos. Ele nos livrou dos filisteus, mas agora fugiu de Absalão e saiu do país.

[[v10-19-10]]

^<<v10-19-10,10>>^ Nós escolhemos Absalão para ser o nosso rei, mas ele morreu na batalha. Então, por que não tentamos trazer o rei Davi de volta?

[[v10-19-11]]

^<<v10-19-11,11>>^ O rei Davi soube do que os israelitas estavam dizendo. Então enviou os sacerdotes Zadoque e Abiatar aos líderes de Judá para perguntarem o seguinte: — Por que vocês seriam os últimos a ajudar a trazer o rei de volta ao seu palácio?

[[v10-19-12]]

^<<v10-19-12,12>>^ Vocês são meus parentes, da minha própria carne e do meu próprio sangue; por que vocês seriam os últimos a ajudar a me trazer de volta?

[[v10-19-13]]

^<<v10-19-13,13>>^ Davi também mandou-os dizer a Amasa: — Você é meu parente. De agora em diante, você será o comandante do exército em lugar de Joabe. Que Deus me mate se eu não fizer isso!

[[v10-19-14]]

^<<v10-19-14,14>>^ Com essas palavras, o rei ganhou o coração de todos os homens de Judá, e eles mandaram lhe dizer que voltasse com todos os seus oficiais.

[[v10-19-15]]

^<<v10-19-15,15>>^ Davi voltou e chegou até o rio Jordão. Os homens da tribo  de Judá foram encontrá-lo em Gilgal, para acompanhá-lo na travessia do rio.

[[v10-19-16]]

^<<v10-19-16,16>>^ Ao mesmo tempo, Simei, o benjamita, filho de Gera, da cidade de Baurim, foi depressa ao rio Jordão para se encontrar com o rei Davi.

[[v10-19-17]]

^<<v10-19-17,17>>^ Mil homens da tribo de Benjamim estavam com Simei. Também Ziba, que trabalhava para a família de Saul, foi ao Jordão com os seus quinze filhos e vinte empregados. Eles chegaram lá antes do rei

[[v10-19-18]]

^<<v10-19-18,18>>^ e atravessaram o Jordão para acompanhar a gente do rei na travessia do rio e fazer tudo o que o rei quisesse. Quando o rei estava se aprontando para atravessar o rio, Simei se jogou no chão, em frente dele,

[[v10-19-19]]

^<<v10-19-19,19>>^ e disse: — Ó rei, eu peço que perdoe o mal que lhe fiz no dia em que o senhor saiu de Jerusalém. Esqueça o que eu fiz; nunca mais pense nisso.

[[v10-19-20]]

^<<v10-19-20,20>>^ Eu sei que fiz uma coisa errada e é por isso que sou a primeira pessoa das tribos do Norte a vir encontrá-lo hoje.

[[v10-19-21]]

^<<v10-19-21,21>>^ Então Abisai, cuja mãe era Zeruia, disse: — Simei deveria morrer por ter amaldiçoado aquele que Deus escolheu como rei.

[[v10-19-22]]

^<<v10-19-22,22>>^ Mas Davi disse a Abisai e ao seu irmão Joabe: — Vocês, filhos de Zeruia, não têm nada a ver com isso! Vocês estão querendo me criar problemas? Agora eu sou o rei de Israel, e nenhum israelita será morto hoje.

[[v10-19-23]]

^<<v10-19-23,23>>^ E disse a Simei: — Eu juro que você não será morto.

[[v10-19-24]]

^<<v10-19-24,24>>^ Mefibosete, o neto de Saul, também desceu para ir ao encontro do rei. Ele não havia lavado os pés, nem aparado a barba, nem lavado as suas roupas desde o dia em que o rei tinha saído de Jerusalém até o dia em que voltou vitorioso.

[[v10-19-25]]

^<<v10-19-25,25>>^ Quando Mefibosete chegou de Jerusalém para se encontrar com o rei, este lhe perguntou: — Mefibosete, por que você não foi comigo?

[[v10-19-26]]

^<<v10-19-26,26>>^ Ele respondeu: — Ó rei, o senhor sabe que sou aleijado. Eu mandei o meu escravo arrear o meu jumento, para que eu pudesse montar e ir com o senhor, mas o meu escravo me traiu.

[[v10-19-27]]

^<<v10-19-27,27>>^ Ele lhe contou mentiras a meu respeito. Mas o senhor é como um anjo de Deus e sabe a verdade; portanto, faça o que achar melhor.

[[v10-19-28]]

^<<v10-19-28,28>>^ Toda a família do meu pai merecia ser morta pelo senhor, mas o senhor me deu o direito de comer junto com o senhor. Eu não tenho o direito de lhe pedir mais nenhum favor.

[[v10-19-29]]

^<<v10-19-29,29>>^ O rei respondeu: — Não diga mais nada. Eu resolvi que a propriedade de Saul será dividida entre você e Ziba.

[[v10-19-30]]

^<<v10-19-30,30>>^ — Que Ziba fique com tudo! — respondeu Mefibosete. — Para mim é suficiente que o senhor tenha voltado em paz para casa.

[[v10-19-31]]

^<<v10-19-31,31>>^ Barzilai, da cidade de Rogelim, que ficava na região de Gileade, também tinha vindo da sua cidade para acompanhar o rei na travessia do rio Jordão.

[[v10-19-32]]

^<<v10-19-32,32>>^ Barzilai era bem velho: tinha oitenta anos de idade. Era muito rico e, quando o rei esteve em Maanaim, ele o havia sustentado.

[[v10-19-33]]

^<<v10-19-33,33>>^ — Barzilai, — disse o rei — venha para Jerusalém e fique comigo, que eu o sustentarei.

[[v10-19-34]]

^<<v10-19-34,34>>^ Mas ele respondeu: — Eu não vou viver muito mais; por que iria para Jerusalém com o senhor?

[[v10-19-35]]

^<<v10-19-35,35>>^ Já tenho oitenta anos e não tenho prazer em mais nada. Não sinto o gosto do que como ou bebo e já não posso ouvir a voz dos cantores. Eu seria somente um peso para o senhor.

[[v10-19-36]]

^<<v10-19-36,36>>^ Não mereço uma recompensa tão grande como essa. Eu irei com o senhor só até um pouco depois do rio Jordão.

[[v10-19-37]]

^<<v10-19-37,37>>^ Deixe-me voltar para casa e morrer perto do túmulo dos meus pais. Mas aqui está Quimã, o meu escravo. Leve-o com o senhor e faça por ele o que achar melhor.

[[v10-19-38]]

^<<v10-19-38,38>>^ O rei respondeu: — Eu o levarei comigo e farei por ele tudo o que você quiser. E farei por você qualquer coisa que me pedir.

[[v10-19-39]]

^<<v10-19-39,39>>^ Então Davi e toda a sua gente atravessaram o rio Jordão. Ele beijou Barzilai e lhe deu a sua bênção, e Barzilai voltou para casa.

[[v10-19-40]]

^<<v10-19-40,40>>^ O rei atravessou o rio acompanhado por todos os homens de Judá e pela metade dos homens de Israel. Dali foi para Gilgal, e Quimã seguiu com ele.

[[v10-19-41]]

^<<v10-19-41,41>>^ Então todos os israelitas foram e disseram a Davi: — Ó rei, por que é que os nossos irmãos, os homens de Judá, se acharam com o direito de trazer o senhor, a sua família e a sua gente para este lado do rio Jordão?

[[v10-19-42]]

^<<v10-19-42,42>>^ Os homens de Judá responderam: — Nós fizemos isso porque o rei é nosso parente. Será que isso é razão para vocês ficarem zangados? Será que o rei pagou pela nossa comida ou nos deu alguma coisa?

[[v10-19-43]]

^<<v10-19-43,43>>^ Os israelitas disseram: — Nós temos dez vezes mais direito sobre o rei Davi do que vocês, embora ele seja seu parente. Por que é que vocês fizeram pouco caso de nós? Afinal de contas, nós fomos os primeiros a falar de trazer o rei de volta! Mas a resposta dos homens de Judá foi ainda mais violenta do que a dos homens de Israel.

'''

xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[&#60; Capítulo Anterior] | <<v10-19-0,Topo>> | xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[Próximo Capítulo &#62;]