include::./index.adoc[]

[[v10-3-0]]
=== 2 Samuel, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-3-1]]

^<<v10-3-1,1>>^ Durou muito tempo a guerra entre os que apoiavam a família de Saul e os que apoiavam Davi. Davi ia ficando cada vez mais forte, e a gente de Saul, cada vez mais fraca.

[[v10-3-2]]

^<<v10-3-2,2>>^ Os filhos de Davi que nasceram na cidade de Hebrom são estes: o primeiro foi Amnom, filho de Ainoã, da cidade de Jezreel.

[[v10-3-3]]

^<<v10-3-3,3>>^ O segundo foi Quileabe, filho de Abigail, viúva de Nabal, da cidade de Carmelo. O terceiro foi Absalão, filho de Maacá, que era filha de Talmai, rei de Gesur.

[[v10-3-4]]

^<<v10-3-4,4>>^ O quarto foi Adonias, filho de Hagite. O quinto foi Sefatias, filho de Abital.

[[v10-3-5]]

^<<v10-3-5,5>>^ O sexto foi Itreão, filho de Eglá, esposa de Davi. Todos esses filhos de Davi nasceram em Hebrom.

[[v10-3-6]]

^<<v10-3-6,6>>^ Enquanto continuava a luta entre os que apoiavam a família de Saul e os que seguiam Davi, Abner ficava cada vez mais poderoso entre a gente de Saul.

[[v10-3-7]]

^<<v10-3-7,7>>^ Um dia Isbosete, filho de Saul, acusou Abner de ter tido relações com uma concubina  de Saul chamada Rispa, filha de Aías.

[[v10-3-8]]

^<<v10-3-8,8>>^ Abner ficou furioso com isso e disse: — Você pensa que eu sou traidor? Pensa que passei para o lado da tribo  de Judá? E continuou: — Desde o começo tenho sido fiel à causa de Saul, o seu pai, aos seus irmãos e aos seus amigos e tenho evitado que você seja derrotado por Davi. No entanto, hoje você me acusa de ser culpado no caso dessa mulher!

[[v10-3-9]]

^<<v10-3-9,9>>^ O Senhor  Deus prometeu a Davi que tiraria o reino de Saul e dos seus descendentes e que tornaria Davi rei tanto de Israel como de Judá, para governar o país inteiro. Que Deus me mate se eu não fizer que isso aconteça!

[[v10-3-10]]

^<<v10-3-10,10>>^ O Senhor  Deus prometeu a Davi que tiraria o reino de Saul e dos seus descendentes e que tornaria Davi rei tanto de Israel como de Judá, para governar o país inteiro. Que Deus me mate se eu não fizer que isso aconteça!

[[v10-3-11]]

^<<v10-3-11,11>>^ Isbosete tinha medo de Abner; por isso, não disse nada.

[[v10-3-12]]

^<<v10-3-12,12>>^ Naquela época Davi estava na cidade de Hebrom, e Abner lhe mandou mensageiros com o seguinte recado: — Quem vai governar esta terra? Faça um acordo  comigo, e eu o ajudarei a levar todo o povo de Israel para o seu lado.

[[v10-3-13]]

^<<v10-3-13,13>>^ Davi respondeu: — Muito bem. Eu farei um acordo com você, porém com uma condição: quando vier falar comigo, você vai me trazer Mical, filha de Saul.

[[v10-3-14]]

^<<v10-3-14,14>>^ Então Davi mandou alguns mensageiros dizerem a Isbosete: — Entregue-me a minha esposa Mical. Eu paguei cem prepúcios  de filisteus para ter o direito de casar com ela.

[[v10-3-15]]

^<<v10-3-15,15>>^ Então Isbosete mandou tirá-la do seu marido Paltiel, filho de Laís.

[[v10-3-16]]

^<<v10-3-16,16>>^ Paltiel seguiu-a chorando pelo caminho, até chegarem à cidade de Baurim. Aí Abner lhe ordenou: — Volte para casa. E ele voltou.

[[v10-3-17]]

^<<v10-3-17,17>>^ Então Abner foi falar com os líderes de Israel. Ele disse: — Há muito tempo que vocês queriam que Davi fosse rei de Israel.

[[v10-3-18]]

^<<v10-3-18,18>>^ Esta é a hora de agir. Lembrem que o Senhor  disse: "Eu usarei o meu servo  Davi para salvar Israel, o meu povo, tanto dos filisteus como de todos os outros inimigos."

[[v10-3-19]]

^<<v10-3-19,19>>^ Abner falou também com o povo da tribo  de Benjamim e depois foi a Hebrom para contar a Davi o que o povo de Benjamim e o povo de Israel tinham resolvido.

[[v10-3-20]]

^<<v10-3-20,20>>^ Abner, com vinte homens, foi a Hebrom para se encontrar com Davi, e este lhe ofereceu uma festa.

[[v10-3-21]]

^<<v10-3-21,21>>^ Abner disse a Davi: — Eu irei agora e conquistarei todo o povo de Israel para o senhor. E eles o aceitarão como rei. Aí o senhor terá o que desejava e governará o país inteiro. Então Davi deixou Abner ir embora em paz.

[[v10-3-22]]

^<<v10-3-22,22>>^ Pouco tempo depois, Joabe e os outros oficiais de Davi voltaram de um ataque rápido, trazendo muitas coisas que haviam tomado dos inimigos. Mas Abner não estava mais em Hebrom com Davi porque este já o havia deixado ir embora em paz.

[[v10-3-23]]

^<<v10-3-23,23>>^ Quando Joabe chegou com os seus soldados, contaram-lhe que Abner havia ido falar com o rei Davi e que este o havia deixado ir embora em paz.

[[v10-3-24]]

^<<v10-3-24,24>>^ Então Joabe foi falar com o rei. Ele disse: — O que foi que o senhor fez? Abner veio aqui, e o senhor deixou que ele fosse embora sem mais nem menos?

[[v10-3-25]]

^<<v10-3-25,25>>^ Ele veio para enganá-lo, para ficar conhecendo todos os lugares aonde o senhor vai e tudo o que faz. E o senhor sabe disso!

[[v10-3-26]]

^<<v10-3-26,26>>^ Logo que saiu de perto de Davi, Joabe mandou mensageiros atrás de Abner. Eles o alcançaram no poço de Sira e o trouxeram de volta. Mas Davi não ficou sabendo disso.

[[v10-3-27]]

^<<v10-3-27,27>>^ Quando Abner chegou a Hebrom, Joabe o levou para o lado do portão, como se quisesse falar com ele em particular, e enfiou um punhal na barriga dele. Assim Abner, filho de Ner, foi assassinado por ter matado Asael, irmão de Joabe.

[[v10-3-28]]

^<<v10-3-28,28>>^ Quando soube disso, Davi disse: — O Senhor  Deus sabe que eu e os meus seguidores não temos nenhuma culpa no assassinato de Abner.

[[v10-3-29]]

^<<v10-3-29,29>>^ Que o castigo por esse crime caia sobre Joabe e toda a sua família! Que nunca faltem na sua família homens que tenham gonorreia ou doença contagiosa de pele, ou que sejam capazes de fazer somente trabalho de mulher, ou que sejam mortos em batalha, ou que não tenham o que comer!

[[v10-3-30]]

^<<v10-3-30,30>>^ Assim Joabe e o seu irmão Abisai assassinaram Abner porque ele havia matado Asael, o irmão deles, na batalha de Gibeão.

[[v10-3-31]]

^<<v10-3-31,31>>^ Então Davi mandou que Joabe e os seus soldados chorassem por Abner e que, em sinal de tristeza, rasgassem as suas roupas e vestissem roupas de luto. E no sepultamento o próprio rei Davi ia caminhando atrás do caixão.

[[v10-3-32]]

^<<v10-3-32,32>>^ Abner foi sepultado em Hebrom, e o rei chorou alto perto do seu túmulo. E todo o povo fez o mesmo.

[[v10-3-33]]

^<<v10-3-33,33>>^ E Davi fez esta lamentação para Abner: "Por que teria Abner de morrer como se fosse um louco?

[[v10-3-34]]

^<<v10-3-34,34>>^ As suas mãos não estavam amarradas, nem estavam atados os seus pés; ele morreu como alguém que é morto por criminosos!" Então o povo chorou novamente por Abner.

[[v10-3-35]]

^<<v10-3-35,35>>^ O povo tentou convencer Davi a comer alguma coisa antes que o dia terminasse, mas ele fez este juramento: — Que Deus me mate se eu comer alguma coisa antes que o dia acabe!

[[v10-3-36]]

^<<v10-3-36,36>>^ O povo ouviu isso e gostou. De fato, o povo gostava de tudo o que o rei fazia.

[[v10-3-37]]

^<<v10-3-37,37>>^ Assim todos os seguidores do rei Davi e todo o povo de Israel entenderam que ele não tinha tomado parte no assassinato de Abner.

[[v10-3-38]]

^<<v10-3-38,38>>^ E ele disse aos seus oficiais: — Fiquem sabendo que hoje morreu um grande líder de Israel.

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]