include::./index.adoc[]

[[v10-13-0]]
=== 2 Samuel, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-13-1]]

^<<v10-13-1,1>>^ Absalão, filho de Davi, tinha uma irmã muito bonita, que se chamava Tamar. Outro filho de Davi, chamado Amnom, apaixonou-se por ela.

[[v10-13-2]]

^<<v10-13-2,2>>^ Ele estava tão apaixonado, que até ficou doente. Amnom pensava que era impossível possuir a sua meia-irmã; ela era virgem e por isso não tinha o direito de se encontrar com nenhum homem.

[[v10-13-3]]

^<<v10-13-3,3>>^ Mas Amnom tinha um amigo muito esperto, chamado Jonadabe, filho de Simeia, irmão de Davi.

[[v10-13-4]]

^<<v10-13-4,4>>^ Jonadabe disse a Amnom: — Você é filho do rei e, no entanto, cada dia está mais triste. Diga-me por quê. — É que estou apaixonado por Tamar, a irmã de Absalão, o meu irmão por parte de pai! — respondeu Amnom.

[[v10-13-5]]

^<<v10-13-5,5>>^ Então Jonadabe disse: — Finja que está doente e vá se deitar. Quando o seu pai vier, diga a ele: "Por favor, deixe que a minha irmã Tamar venha me dar de comer. Que ela prepare a comida aqui onde eu possa vê-la e que ela mesma me sirva a comida."

[[v10-13-6]]

^<<v10-13-6,6>>^ E Amnom se deitou e fingiu que estava doente. O rei Davi foi visitá-lo, e Amnom disse: — Por favor, deixe que Tamar venha e prepare alguns bolos aqui onde eu possa vê-la, e que ela mesma os sirva para mim.

[[v10-13-7]]

^<<v10-13-7,7>>^ Então Davi mandou dizer a Tamar, no palácio: — Vá à casa de Amnom e prepare alguma comida para ele.

[[v10-13-8]]

^<<v10-13-8,8>>^ Ela foi e o encontrou de cama. Aí pegou um pouco de massa, preparou-a e fez alguns bolos ali onde ele podia vê-la. Então assou os bolos

[[v10-13-9]]

^<<v10-13-9,9>>^ e os tirou da forma para Amnom comer. Mas ele não quis e disse: — Mande todo mundo sair. Todos saíram.

[[v10-13-10]]

^<<v10-13-10,10>>^ E Amnom disse a Tamar: — Traga os bolos aqui para a minha cama e sirva-os para mim. Então ela levou os bolos para ele.

[[v10-13-11]]

^<<v10-13-11,11>>^ Quando os ofereceu a Amnom, ele a agarrou e disse: — Deite-se comigo, minha irmã!

[[v10-13-12]]

^<<v10-13-12,12>>^ Porém ela respondeu: — Não, meu irmão! Não me obrigue a fazer isso! Não se faz uma coisa dessas em Israel. Não faça essa loucura!

[[v10-13-13]]

^<<v10-13-13,13>>^ Como eu poderia aparecer depois disso diante dos outros? E você ficaria completamente desmoralizado em Israel. Por favor, fale com o rei, e eu estou certa de que ele me dará a você.

[[v10-13-14]]

^<<v10-13-14,14>>^ Mas Amnom não quis ouvir o que Tamar dizia. E, como era mais forte, ele a forçou e teve relações com ela.

[[v10-13-15]]

^<<v10-13-15,15>>^ Depois teve nojo dela e a odiou ainda mais do que a tinha amado antes. Então disse: — Saia daqui!

[[v10-13-16]]

^<<v10-13-16,16>>^ Tamar respondeu: — Não, meu irmão! Você me mandar embora assim é um crime ainda maior do que o que você acaba de cometer! Mas Amnom não quis escutar o que ela dizia.

[[v10-13-17]]

^<<v10-13-17,17>>^ Chamou o seu empregado particular e disse: — Tire essa mulher da minha frente! Ponha-a para fora e feche a porta!

[[v10-13-18]]

^<<v10-13-18,18>>^ Então o empregado pôs Tamar para fora e fechou a porta. Ela estava usando um vestido longo, de mangas compridas — a roupa que as princesas solteiras usavam naquele tempo.

[[v10-13-19]]

^<<v10-13-19,19>>^ Aí ela pôs cinza na cabeça, rasgou o vestido e saiu gritando, cobrindo o rosto com as mãos.

[[v10-13-20]]

^<<v10-13-20,20>>^ O seu irmão Absalão perguntou: — Amnom fez mal a você? Não conte isso a ninguém, minha irmã. Afinal de contas, ele é seu meio-irmão. Não leve isso muito a sério. Assim Tamar ficou vivendo triste e sozinha na casa de Absalão.

[[v10-13-21]]

^<<v10-13-21,21>>^ Quando o rei Davi soube do que tinha acontecido, ficou furioso.

[[v10-13-22]]

^<<v10-13-22,22>>^ Absalão não disse nem uma palavra a Amnom, mas ficou com ódio dele porque havia forçado a sua irmã Tamar.

[[v10-13-23]]

^<<v10-13-23,23>>^ Dois anos depois, Absalão estava cortando a lã das suas ovelhas em Baal-Hazor, perto da cidade de Efraim, e convidou todos os filhos do rei para irem até lá.

[[v10-13-24]]

^<<v10-13-24,24>>^ Ele foi falar com o rei Davi e disse: — Meu rei, eu estou cortando a lã das minhas ovelhas. Gostaria que o senhor e os seus funcionários também fossem até lá.

[[v10-13-25]]

^<<v10-13-25,25>>^ Davi respondeu: — Não, meu filho. Se todos nós fôssemos, daríamos muito trabalho a você. Absalão insistiu, mas o rei não quis ir e lhe disse que podia ir embora.

[[v10-13-26]]

^<<v10-13-26,26>>^ Mas Absalão disse: — Está bem. Então deixe que pelo menos o meu irmão Amnom vá. — Por que motivo ele iria com você? — perguntou o rei.

[[v10-13-27]]

^<<v10-13-27,27>>^ Mas Absalão continuou a insistir, até que por fim Davi deixou que Amnom e todos os seus outros filhos fossem. Absalão preparou um banquete de rei

[[v10-13-28]]

^<<v10-13-28,28>>^ e deu as seguintes instruções aos seus empregados: — Prestem atenção em Amnom. Quando ele estiver bêbado, eu darei uma ordem, e vocês o matarão. Não tenham medo, pois a responsabilidade será minha. Sejam corajosos e decididos!

[[v10-13-29]]

^<<v10-13-29,29>>^ Os empregados mataram Amnom, como Absalão havia mandado. Então todos os outros filhos de Davi montaram suas mulas e fugiram.

[[v10-13-30]]

^<<v10-13-30,30>>^ Enquanto eles estavam voltando para casa, Davi recebeu esta notícia: "Absalão matou todos os seus filhos; não escapou nenhum!"

[[v10-13-31]]

^<<v10-13-31,31>>^ Então o rei se levantou, rasgou as suas roupas em sinal de tristeza e se jogou no chão. E todos os servidores dele que estavam ali também rasgaram as suas roupas.

[[v10-13-32]]

^<<v10-13-32,32>>^ Mas Jonadabe, filho de Simeia, irmão de Davi, disse: — Senhor, eles não mataram todos os seus filhos. Somente Amnom morreu. Pelo jeito de Absalão, a gente podia ver que ele havia resolvido fazer isso desde o dia em que Amnom forçou a sua irmã Tamar.

[[v10-13-33]]

^<<v10-13-33,33>>^ Por isso, eu não acredito na notícia de que todos os seus filhos morreram; somente Amnom foi morto.

[[v10-13-34]]

^<<v10-13-34,34>>^ Enquanto isso, Absalão fugiu. Naquele momento o soldado que estava de guarda viu muita gente descendo o monte, na estrada de Horonaim. Ele foi até o lugar onde o rei estava e disse: — Alguns homens estão descendo o monte, na estrada de Horonaim.

[[v10-13-35]]

^<<v10-13-35,35>>^ Então Jonadabe disse a Davi: — São os seus filhos que estão voltando, justamente como eu disse.

[[v10-13-36]]

^<<v10-13-36,36>>^ Logo que ele acabou de dizer isso, os filhos de Davi entraram. Eles começaram a chorar alto, e Davi e os seus oficiais também choraram muito.

[[v10-13-37]]

^<<v10-13-37,37>>^ Absalão fugiu e foi ficar com o rei da cidade de Gesur, chamado Talmai, filho de Amiúde. E por muito tempo Davi chorou a morte do seu filho Amnom.

[[v10-13-38]]

^<<v10-13-38,38>>^ Absalão ficou três anos em Gesur.

[[v10-13-39]]

^<<v10-13-39,39>>^ Então o rei Davi começou a sentir muita saudade dele, pois agora já estava conformado com a morte de Amnom.

'''

xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[&#60; Capítulo Anterior] | <<v10-13-0,Topo>> | xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[Próximo Capítulo &#62;]