include::./index.adoc[]

[[v10-10-0]]
=== 2 Samuel, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-10-1]]

^<<v10-10-1,1>>^ Algum tempo depois morreu o rei Naás, do país de Amom, e o seu filho Hanum se tornou rei.

[[v10-10-2]]

^<<v10-10-2,2>>^ E Davi disse: — Eu serei bondoso com Hanum, assim como Naás, o seu pai, foi bondoso comigo. Então enviou mensageiros a Hanum para mostrar a sua amizade. Porém, quando os mensageiros chegaram à cidade de Rabá,

[[v10-10-3]]

^<<v10-10-3,3>>^ as autoridades amonitas disseram ao seu rei: — O senhor pensa que é em honra do seu pai que Davi enviou estes homens para mostrar amizade? É claro que não! Ele os mandou aqui como espiões a fim de conhecerem a cidade, para poderem destruí-la.

[[v10-10-4]]

^<<v10-10-4,4>>^ Então Hanum pegou os mensageiros de Davi, raspou um lado da barba deles, cortou as suas roupas até a altura das nádegas e os mandou embora.

[[v10-10-5]]

^<<v10-10-5,5>>^ Quando Davi soube disso, enviou outros mensageiros para se encontrarem com eles porque eles estavam muito envergonhados. Davi mandou lhes dizer que ficassem na cidade de Jericó e que só voltassem quando as suas barbas tivessem crescido de novo.

[[v10-10-6]]

^<<v10-10-6,6>>^ Os amonitas compreenderam que tinham feito de Davi um inimigo deles. Por isso, contrataram vinte mil soldados sírios das cidades de Bete-Reobe e Zoba. Também contrataram o rei da cidade de Maacá, com mil homens, e doze mil homens da cidade de Tobe.

[[v10-10-7]]

^<<v10-10-7,7>>^ Davi soube disso e enviou contra eles Joabe com todos os melhores soldados do exército israelita.

[[v10-10-8]]

^<<v10-10-8,8>>^ Os amonitas saíram e tomaram posição na entrada da cidade de Rabá enquanto os outros — os sírios de Zoba e de Reobe e os homens de Tobe e Maacá — tomaram posição em campo aberto.

[[v10-10-9]]

^<<v10-10-9,9>>^ Joabe viu que as tropas inimigas os atacariam pela frente e por trás. Então escolheu os melhores soldados de Israel e os colocou de frente para os sírios.

[[v10-10-10]]

^<<v10-10-10,10>>^ Deixou o resto das suas tropas sob o comando do seu irmão Abisai, que as colocou de frente para os amonitas.

[[v10-10-11]]

^<<v10-10-11,11>>^ E Joabe disse a Abisai: — Se você perceber que os sírios estão me vencendo, venha me ajudar; e, se os amonitas estiverem vencendo você, eu irei ajudá-lo.

[[v10-10-12]]

^<<v10-10-12,12>>^ Seja corajoso! Vamos lutar com firmeza pelo nosso povo e pelas cidades do nosso Deus. E que seja feita a vontade de Deus, o Senhor !

[[v10-10-13]]

^<<v10-10-13,13>>^ Então Joabe e os seus soldados avançaram para atacar, e os sírios fugiram.

[[v10-10-14]]

^<<v10-10-14,14>>^ Os amonitas viram os sírios fugindo. Então também fugiram de Abisai e voltaram para dentro da cidade. E Joabe parou de lutar contra os amonitas e voltou para Jerusalém.

[[v10-10-15]]

^<<v10-10-15,15>>^ Quando os sírios viram que tinham sido vencidos pelos israelitas, reuniram de novo todas as suas tropas.

[[v10-10-16]]

^<<v10-10-16,16>>^ O rei Hadadezer mandou chamar os sírios que estavam no lado leste do rio Eufrates. Então eles foram até a cidade de Helã. Na frente deles ia Sobaque, o comandante do exército de Hadadezer.

[[v10-10-17]]

^<<v10-10-17,17>>^ Quando Davi soube disso, reuniu as tropas israelitas, atravessou o rio Jordão e marchou para Helã. Lá os sírios tomaram posição de frente para os israelitas. A luta começou,

[[v10-10-18]]

^<<v10-10-18,18>>^ e os israelitas fizeram os sírios fugir. Davi e os seus soldados mataram setecentos soldados que guiavam carros de guerra e quarenta mil cavaleiros sírios. Feriram também Sobaque, o comandante inimigo, que morreu ali no campo de batalha.

[[v10-10-19]]

^<<v10-10-19,19>>^ Quando os reis que eram chefiados por Hadadezer viram que tinham sido vencidos pelos israelitas, fizeram paz com eles, ficando debaixo do seu poder. E os sírios ficaram com medo de ajudar de novo os amonitas.

'''

xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[&#60; Capítulo Anterior] | <<v10-10-0,Topo>> | xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[Próximo Capítulo &#62;]