include::./index.adoc[]

[[v10-20-0]]
=== 2 Samuel, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-20-1]]

^<<v10-20-1,1>>^ Aconteceu que estava ali um sujeito ordinário, chamado Seba, filho de Bicri, da tribo  de Benjamim. Ele tocou a corneta para reunir o povo e gritou: — Abaixo Davi! Não temos nada a ver com ele! Não adianta nada segui-lo! Homens de Israel, vamos voltar para casa!

[[v10-20-2]]

^<<v10-20-2,2>>^ Então todos os israelitas abandonaram Davi e foram com Seba. Mas os homens de Judá ficaram fiéis a Davi e o seguiram desde o rio Jordão até a cidade de Jerusalém.

[[v10-20-3]]

^<<v10-20-3,3>>^ Davi foi para o seu palácio em Jerusalém e colocou numa casa guardada por soldados as dez concubinas  que havia deixado tomando conta do palácio. Ele lhes deu tudo o que precisavam, porém não teve relações com elas. E elas foram obrigadas a ficar dentro de casa o resto da vida vivendo como viúvas.

[[v10-20-4]]

^<<v10-20-4,4>>^ O rei disse a Amasa: — Convoque todos os homens de Judá e esteja aqui de volta com eles depois de amanhã.

[[v10-20-5]]

^<<v10-20-5,5>>^ Amasa saiu para convocar os homens, porém não voltou no dia que o rei havia marcado.

[[v10-20-6]]

^<<v10-20-6,6>>^ Então Davi disse a Abisai: — Seba vai nos dar mais trabalho do que Absalão. Pegue os meus homens e vá atrás dele; se não, ele poderá tomar algumas cidades cercadas de muralhas e escapar de nós.

[[v10-20-7]]

^<<v10-20-7,7>>^ Então os homens de Joabe, os queretitas e os peletitas e os soldados mais valentes seguiram Abisai. Eles saíram de Jerusalém para perseguir Seba.

[[v10-20-8]]

^<<v10-20-8,8>>^ Quando chegaram à pedra grande, na cidade de Gibeão, Amasa encontrou-se com eles. Joabe estava vestido com roupa de guerra e tinha uma espada na bainha, que levava pendurada no cinto. Quando ele avançou, a espada caiu.

[[v10-20-9]]

^<<v10-20-9,9>>^ Então Joabe disse a Amasa: — Como vai, meu amigo? E pegou na barba de Amasa com a mão direita para beijá-lo.

[[v10-20-10]]

^<<v10-20-10,10>>^ Amasa não reparou que Joabe tinha uma espada na outra mão. Então Joabe enfiou a espada na barriga de Amasa, e os seus intestinos saíram e se esparramaram pelo chão. Ele morreu na mesma hora: Joabe não teve de feri-lo uma segunda vez. Em seguida Joabe e o seu irmão Abisai continuaram a perseguir Seba.

[[v10-20-11]]

^<<v10-20-11,11>>^ Um dos soldados de Joabe ficou perto do corpo de Amasa e gritou: — Todos os que estão do lado de Joabe e são a favor de Davi, sigam Joabe!

[[v10-20-12]]

^<<v10-20-12,12>>^ O corpo de Amasa ficou estendido no meio da estrada, coberto de sangue. O ajudante de Joabe viu que todos estavam parando; então arrastou o corpo para fora da estrada e estendeu um cobertor sobre ele porque todos os que o viam paravam.

[[v10-20-13]]

^<<v10-20-13,13>>^ Depois que o corpo foi tirado da estrada, todos foram com Joabe perseguir Seba.

[[v10-20-14]]

^<<v10-20-14,14>>^ Seba atravessou as terras de todas as tribos de Israel e foi parar na cidade de Abel-Bete-Maacá. Todas as pessoas do grupo de famílias de Bicri se reuniram e foram com ele para dentro da cidade.

[[v10-20-15]]

^<<v10-20-15,15>>^ Os soldados de Joabe chegaram e cercaram a cidade. Eles construíram rampas de terra encostadas nas muralhas e também começaram a cavar debaixo da muralha para fazê-la cair.

[[v10-20-16]]

^<<v10-20-16,16>>^ Havia na cidade uma mulher muito esperta. Ela gritou do muro: — Escutem! Escutem! Digam a Joabe para vir aqui, que eu quero falar com ele!

[[v10-20-17]]

^<<v10-20-17,17>>^ Joabe foi, e ela perguntou: — Você é Joabe? — Sim, sou! — respondeu ele. — Escute, senhor! — disse ela. — Estou escutando! — respondeu ele.

[[v10-20-18]]

^<<v10-20-18,18>>^ Então ela disse: — Antigamente costumavam dizer: "Vão e peçam conselhos na cidade de Abel"; e era assim que resolviam os problemas.

[[v10-20-19]]

^<<v10-20-19,19>>^ A nossa cidade é grande e uma das mais pacíficas e leais de Israel. Por que você está tentando destruí-la? Você quer arrasar o que pertence a Deus, o Senhor ?

[[v10-20-20]]

^<<v10-20-20,20>>^ — Nunca! — respondeu Joabe. — Eu nunca destruirei, nem arrasarei a sua cidade!

[[v10-20-21]]

^<<v10-20-21,21>>^ O nosso plano não é esse. Um homem da região montanhosa de Efraim, chamado Seba, filho de Bicri, começou uma revolta contra Davi, o nosso rei. Entreguem só esse homem, e eu irei embora. — Nós jogaremos a cabeça dele por cima da muralha para você! — disse ela.

[[v10-20-22]]

^<<v10-20-22,22>>^ Aí ela foi dar o seu conselho ao povo da cidade. E eles cortaram a cabeça de Seba e a jogaram por cima do muro para Joabe. Ele tocou a corneta, reuniu os homens, e todos deixaram a cidade e voltaram para casa. E Joabe voltou para perto do rei Davi, em Jerusalém.

[[v10-20-23]]

^<<v10-20-23,23>>^ Joabe era o comandante do exército de Israel; Benaías, filho de Joiada, era o chefe dos queretitas e dos peletitas .

[[v10-20-24]]

^<<v10-20-24,24>>^ Adonirão era responsável pelos homens condenados a trabalhos forçados; Josafá, filho de Ailude, era o conselheiro do rei.

[[v10-20-25]]

^<<v10-20-25,25>>^ Seva era o escrivão. Zadoque e Abiatar eram os sacerdotes.

[[v10-20-26]]

^<<v10-20-26,26>>^ Ira, da cidade de Jair, também era um dos sacerdotes de Davi.

'''

xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[&#60; Capítulo Anterior] | <<v10-20-0,Topo>> | xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[Próximo Capítulo &#62;]