include::./index.adoc[]

[[v10-21-0]]
=== 2 Samuel, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-21-1]]

^<<v10-21-1,1>>^ Durante o reinado de Davi, houve uma grande fome, que durou três anos seguidos. Por isso, Davi consultou a Deus, o Senhor , e ele respondeu: — Saul e a sua família são culpados de assassinato: ele matou o povo de Gibeão.

[[v10-21-2]]

^<<v10-21-2,2>>^ O povo de Gibeão não era israelita. Eles eram um pequeno grupo de amorreus que os israelitas tinham prometido proteger; mas Saul havia tentado acabar com eles por causa do interesse dele pelo bem do povo de Israel e de Judá. Então Davi chamou o povo de Gibeão

[[v10-21-3]]

^<<v10-21-3,3>>^ e disse: — O que posso fazer por vocês? Eu quero pagar pelo mal que lhes foi feito, para que assim vocês abençoem o povo de Deus.

[[v10-21-4]]

^<<v10-21-4,4>>^ Eles responderam: — A nossa questão com Saul e a sua família não pode ser resolvida com ouro nem com prata. E também não queremos matar nenhum israelita. — Então, o que é que querem que eu faça por vocês? — perguntou Davi.

[[v10-21-5]]

^<<v10-21-5,5>>^ Eles responderam: — Saul quis nos destruir para que não sobrasse nenhum de nós em nenhum lugar de Israel.

[[v10-21-6]]

^<<v10-21-6,6>>^ Entregue-nos então sete homens descendentes dele, e nós os enforcaremos diante de Deus, o Senhor , em Gibeá, a cidade onde nasceu Saul, o rei escolhido pelo Senhor . — Eu entregarei! — respondeu o rei.

[[v10-21-7]]

^<<v10-21-7,7>>^ Mas, por causa do juramento que ele e Jônatas tinham feito um ao outro, o rei não deixou que fosse morto Mefibosete, que era filho de Jônatas e neto de Saul.

[[v10-21-8]]

^<<v10-21-8,8>>^ Porém pegou Armoni e Mefibosete — os dois filhos que Rispa, filha de Aías, tinha tido de Saul; pegou também os cinco filhos que Merabe, filha de Saul, tinha tido de Adriel, filho de Barzilai, da cidade de Meolá.

[[v10-21-9]]

^<<v10-21-9,9>>^ E Davi entregou os sete ao povo de Gibeão, e eles os enforcaram no monte, diante do Senhor . E todos os sete morreram juntos. Isso aconteceu no fim da primavera, no começo da colheita da cevada .

[[v10-21-10]]

^<<v10-21-10,10>>^ Então Rispa, concubina  de Saul, pegou um pano grosseiro e com ele fez um abrigo sobre uma rocha. E ficou ali desde o começo da colheita até o dia em que as chuvas do outono caíram sobre os sete corpos. E não deixou que as aves se aproximassem deles de dia nem os animais selvagens de noite.

[[v10-21-11]]

^<<v10-21-11,11>>^ Quando soube o que Rispa tinha feito,

[[v10-21-12]]

^<<v10-21-12,12>>^ Davi foi e tomou dos moradores de Jabes-Gileade os ossos de Saul e do seu filho Jônatas. Os moradores de Jabes haviam retirado os corpos da praça de Bete-Sã, onde os filisteus os tinham pendurado no dia em que mataram Saul no monte Gilboa.

[[v10-21-13]]

^<<v10-21-13,13>>^ Davi então colocou os ossos de Saul e de Jônatas junto com os ossos dos sete homens que haviam sido enforcados.

[[v10-21-14]]

^<<v10-21-14,14>>^ Sepultaram os ossos de Saul e de Jônatas no túmulo de Quis, o pai de Saul, na cidade de Zela, no território da tribo  de Benjamim. Tudo o que o rei mandou foi feito. E depois disso Deus respondeu às orações do povo pelo seu país.

[[v10-21-15]]

^<<v10-21-15,15>>^ Houve outra guerra entre os filisteus e Israel. Davi e os seus soldados foram e lutaram contra os filisteus. Durante a batalha Davi ficou muito cansado.

[[v10-21-16]]

^<<v10-21-16,16>>^ Um gigante chamado Isbi-Benobe tinha uma lança de bronze que pesava mais ou menos cinco quilos e estava usando uma espada nova. Ele pensou que podia matar Davi.

[[v10-21-17]]

^<<v10-21-17,17>>^ Mas Abisai, cuja mãe era Zeruia, socorreu Davi, atacou o filisteu e o matou. Então os soldados de Davi fizeram a promessa de nunca mais deixar que Davi saísse com eles para a guerra. Eles disseram: — O senhor é a esperança de Israel, e nós não queremos perdê-lo.

[[v10-21-18]]

^<<v10-21-18,18>>^ Depois disso houve outra batalha contra os filisteus na cidade de Gobe. E Sibecai, da cidade de Husa, matou um gigante chamado Safe.

[[v10-21-19]]

^<<v10-21-19,19>>^ Houve mais uma batalha contra os filisteus em Gobe, e Elanã, filho de Jair, de Belém, matou Golias, da cidade de Gate. O cabo da lança de Golias era da grossura do eixo de um tear de tecelão.

[[v10-21-20]]

^<<v10-21-20,20>>^ E houve ainda outra batalha em Gate. Ali havia um gigante, descendente dos antigos gigantes, que tinha seis dedos em cada mão e em cada pé.

[[v10-21-21]]

^<<v10-21-21,21>>^ Ele desafiou os israelitas; e Jônatas, filho de Simeia, irmão de Davi, o matou.

[[v10-21-22]]

^<<v10-21-22,22>>^ Esses quatro eram descendentes dos gigantes da cidade de Gate e foram mortos por Davi e os seus soldados.

'''

xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[&#60; Capítulo Anterior] | <<v10-21-0,Topo>> | xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[Próximo Capítulo &#62;]