include::./index.adoc[]

[[v10-7-0]]
=== 2 Samuel, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-7-1]]

^<<v10-7-1,1>>^ O rei Davi conseguiu controlar completamente o seu reino, e o Senhor  Deus o livrou de todos os seus inimigos.

[[v10-7-2]]

^<<v10-7-2,2>>^ Um dia Davi disse ao profeta  Natã: — Veja só! Aqui estou eu, morando numa casa revestida de madeira de cedro, enquanto a arca da aliança  está guardada numa barraca!

[[v10-7-3]]

^<<v10-7-3,3>>^ Natã respondeu: — Faça tudo o que quiser porque o Senhor  Deus está com você.

[[v10-7-4]]

^<<v10-7-4,4>>^ Mas naquela noite o Senhor  disse a Natã:

[[v10-7-5]]

^<<v10-7-5,5>>^ — Vá e diga ao meu servo  Davi que eu mandei dizer o seguinte: "Não é você a pessoa que deve construir um templo para eu morar nele.

[[v10-7-6]]

^<<v10-7-6,6>>^ Desde que tirei do Egito o povo de Israel e até hoje, eu não tenho morado em nenhum templo. Tenho viajado morando numa barraca.

[[v10-7-7]]

^<<v10-7-7,7>>^ Em todas as minhas viagens com o povo de Israel, nunca perguntei aos líderes que escolhi por que razão eles não construíram para mim um templo revestido de cedro."

[[v10-7-8]]

^<<v10-7-8,8>>^ Portanto, diga ao meu servo Davi que eu, o Senhor  Todo-Poderoso, digo o seguinte: "Eu tirei você do trabalho de cuidar de ovelhas nos campos, para que governasse o meu povo de Israel.

[[v10-7-9]]

^<<v10-7-9,9>>^ Estive com você em todos os lugares por onde tem ido e, conforme você foi avançando, eu o defendi de todos os seus inimigos. Eu farei com que você seja famoso, tão famoso quanto os maiores líderes do mundo.

[[v10-7-10]]

^<<v10-7-10,10>>^ Escolhi um lugar para o meu povo de Israel e o fiz morar ali, onde eles viverão em paz. Desde que entraram nesta terra, eles têm sido atacados por povos violentos, mas isso não acontecerá mais. Eu prometo que livrarei você de todos os seus inimigos e que lhe darei descendentes.

[[v10-7-11]]

^<<v10-7-11,11>>^ Escolhi um lugar para o meu povo de Israel e o fiz morar ali, onde eles viverão em paz. Desde que entraram nesta terra, eles têm sido atacados por povos violentos, mas isso não acontecerá mais. Eu prometo que livrarei você de todos os seus inimigos e que lhe darei descendentes.

[[v10-7-12]]

^<<v10-7-12,12>>^ E, quando você morrer e for sepultado ao lado dos seus antepassados, eu colocarei um dos seus filhos como rei e tornarei forte o reino dele.

[[v10-7-13]]

^<<v10-7-13,13>>^ Será ele quem construirá um templo para mim, e eu farei com que os seus descendentes governem para sempre.

[[v10-7-14]]

^<<v10-7-14,14>>^ Eu serei o pai dele, e ele será meu filho. Quando ele errar, eu o castigarei como um pai castiga seu filho.

[[v10-7-15]]

^<<v10-7-15,15>>^ Porém não retirarei dele o meu amor, como fiz com Saul, para que você pudesse ser rei.

[[v10-7-16]]

^<<v10-7-16,16>>^ Você sempre terá descendentes, e eu farei com que o seu reino dure para sempre. E a sua descendência real nunca terminará."

[[v10-7-17]]

^<<v10-7-17,17>>^ E Natã contou a Davi tudo o que Deus lhe havia revelado.

[[v10-7-18]]

^<<v10-7-18,18>>^ O rei Davi entrou na barraca, sentou-se e orou assim: — Ó Senhor , meu Deus, eu não mereço tudo o que fizeste por mim no passado, e a minha família também não merece.

[[v10-7-19]]

^<<v10-7-19,19>>^ E, como se as bênçãos do passado ainda fossem poucas, agora estás fazendo promessas a respeito dos meus descendentes no futuro. E deixaste um homem ver isso, ó Senhor , meu Deus!

[[v10-7-20]]

^<<v10-7-20,20>>^ O que mais posso te dizer? Tu me conheces, pois sou teu servo .

[[v10-7-21]]

^<<v10-7-21,21>>^ Era o teu desejo e propósito fazer isso; e tu me deixaste saber de todas essas grandes coisas.

[[v10-7-22]]

^<<v10-7-22,22>>^ Como és grande, ó Senhor , nosso Deus! Não há ninguém igual a ti; como temos ouvido dizer, somente tu és Deus; não existe outro.

[[v10-7-23]]

^<<v10-7-23,23>>^ Não há nenhuma outra nação na terra como o teu povo de Israel, que libertaste para ser o teu próprio povo. Tu te tornaste famoso e fizeste grandes e maravilhosas coisas por eles. Tu libertaste o teu povo do Egito e expulsaste as outras nações e os seus deuses conforme o teu povo ia avançando.

[[v10-7-24]]

^<<v10-7-24,24>>^ Ó Senhor , tu fizeste com que o teu povo de Israel fosse teu para sempre e te tornaste o seu Deus.

[[v10-7-25]]

^<<v10-7-25,25>>^ — E agora, ó Senhor , nosso Deus, confirma a promessa que fizeste a meu respeito e a respeito da minha família e cumpre o que disseste que ia acontecer.

[[v10-7-26]]

^<<v10-7-26,26>>^ A tua fama será grande, e para sempre as pessoas dirão: "O Senhor  Todo-Poderoso é o Deus de Israel." E tu farás com que sempre haja reis entre os meus descendentes.

[[v10-7-27]]

^<<v10-7-27,27>>^ Senhor  Todo-Poderoso, Deus de Israel! Eu tenho coragem para te fazer esta oração porque revelaste a mim, teu servo , que farás com que os meus descendentes sejam reis.

[[v10-7-28]]

^<<v10-7-28,28>>^ — E mais. Tu, ó Senhor , me fizeste esta maravilhosa promessa, e as tuas promessas sempre se cumprem porque tu és Deus.

'''

xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[&#60; Capítulo Anterior] | <<v10-7-0,Topo>> | xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[Próximo Capítulo &#62;]