include::./index.adoc[]

[[v10-9-0]]
=== 2 Samuel, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-9-1]]

^<<v10-9-1,1>>^ Certo dia Davi perguntou: — Será que alguma pessoa da família de Saul ainda está viva? Se está, eu quero fazer alguma coisa boa para essa pessoa, por causa de Jônatas.

[[v10-9-2]]

^<<v10-9-2,2>>^ Havia um empregado chamado Ziba, da família de Saul. Alguém lhe disse que fosse falar com o rei Davi. — Você é Ziba? — perguntou o rei. — Sim, sou eu mesmo, às suas ordens! — respondeu ele.

[[v10-9-3]]

^<<v10-9-3,3>>^ E o rei lhe perguntou: — Ainda existe alguém da família de Saul para quem eu possa fazer alguma coisa boa, como prometi a Deus? Ziba respondeu: — Sim. Existe um filho de Jônatas. Ele é aleijado dos dois pés.

[[v10-9-4]]

^<<v10-9-4,4>>^ — Onde está ele? — perguntou o rei. — Na casa de Maquir, filho de Amiel, na cidade de Lo-Debar! — respondeu Ziba.

[[v10-9-5]]

^<<v10-9-5,5>>^ Então o rei Davi mandou buscá-lo.

[[v10-9-6]]

^<<v10-9-6,6>>^ Quando Mefibosete, filho de Jônatas e neto de Saul, chegou, ele ajoelhou-se e encostou o rosto no chão diante de Davi em sinal de respeito. Davi disse: — Mefibosete! — Às suas ordens, senhor! — respondeu ele.

[[v10-9-7]]

^<<v10-9-7,7>>^ — Não fique com medo! — disse Davi. — Eu serei bondoso com você por causa de Jônatas, o seu pai. Eu lhe darei de volta todas as terras que pertenciam ao seu avô Saul, e você será sempre bem-vindo à minha mesa.

[[v10-9-8]]

^<<v10-9-8,8>>^ Mefibosete se curvou novamente e respondeu: — Eu não valho mais do que um cachorro morto! Por que o senhor é tão bondoso comigo?

[[v10-9-9]]

^<<v10-9-9,9>>^ Então o rei chamou Ziba, o empregado de Saul, e disse: — Eu estou devolvendo a Mefibosete, o neto do seu patrão, tudo o que pertencia a Saul e à sua família.

[[v10-9-10]]

^<<v10-9-10,10>>^ Você, os seus filhos e os seus empregados cultivarão a terra para a família do seu patrão Saul e farão a colheita para que eles tenham comida. Mas Mefibosete comerá sempre à minha mesa. Ziba tinha quinze filhos e vinte empregados.

[[v10-9-11]]

^<<v10-9-11,11>>^ Ele respondeu: — Farei tudo o que o senhor mandar. Daí em diante Mefibosete passou a comer junto com o rei, como se fosse filho dele.

[[v10-9-12]]

^<<v10-9-12,12>>^ Mefibosete tinha um filho pequeno chamado Mica. Todos os que eram da família de Ziba se tornaram empregados de Mefibosete.

[[v10-9-13]]

^<<v10-9-13,13>>^ Assim Mefibosete, que era aleijado dos dois pés, ficou morando em Jerusalém e todos os dias comia junto com o rei.

'''

xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[&#60; Capítulo Anterior] | <<v10-9-0,Topo>> | xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[Próximo Capítulo &#62;]