include::./index.adoc[]

[[v10-5-0]]
=== 2 Samuel, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-5-1]]

^<<v10-5-1,1>>^ Então todas as tribos  de Israel foram se encontrar com Davi em Hebrom e disseram: — Nós pertencemos ao mesmo povo que você, ó rei.

[[v10-5-2]]

^<<v10-5-2,2>>^ No passado, quando Saul era o nosso rei, você comandou o povo de Israel na batalha. E o Senhor  Deus lhe disse que você seria comandante e governador do povo dele.

[[v10-5-3]]

^<<v10-5-3,3>>^ Assim todos os líderes de Israel foram se encontrar com Davi em Hebrom. Davi fez um acordo  sagrado com eles, e eles o ungiram  rei de Israel.

[[v10-5-4]]

^<<v10-5-4,4>>^ Ele tinha trinta anos de idade quando se tornou rei e reinou quarenta anos.

[[v10-5-5]]

^<<v10-5-5,5>>^ Governou Judá, em Hebrom, sete anos e meio; e governou Israel e Judá, em Jerusalém, trinta e três anos.

[[v10-5-6]]

^<<v10-5-6,6>>^ O rei Davi e os seus soldados foram atacar Jerusalém. Os jebuseus, que eram os moradores da cidade, pensaram que ele não seria capaz de conquistá-la e por isso disseram: — Você nunca entrará aqui. Para fazer você ficar do lado de fora, bastam os cegos e os aleijados.

[[v10-5-7]]

^<<v10-5-7,7>>^ Mas Davi tomou a fortaleza de Sião , e ela passou a ser chamada de " Cidade de Davi ". A coisa aconteceu assim.

[[v10-5-8]]

^<<v10-5-8,8>>^ Naquele dia Davi disse aos seus soldados: — Se alguém quiser matar os jebuseus, aqueles pobres cegos e aleijados, que eu tanto odeio, então que suba pelo túnel da água e os ataque. É por isso que se diz: "Os cegos e os aleijados não podem entrar na casa de Deus."

[[v10-5-9]]

^<<v10-5-9,9>>^ Davi ficou morando na fortaleza e a chamou de Cidade de Davi. Em volta ele construiu defesas que iam desde o aterro que ficava no lado leste da cidade até o palácio.

[[v10-5-10]]

^<<v10-5-10,10>>^ E Davi ia ficando cada vez mais forte porque o Senhor , o Deus Todo-Poderoso, estava com ele.

[[v10-5-11]]

^<<v10-5-11,11>>^ O rei Hirão, da cidade de Tiro, enviou embaixadores a Davi. Ele mandou toras de cedro e também carpinteiros e pedreiros, e eles construíram um palácio para Davi.

[[v10-5-12]]

^<<v10-5-12,12>>^ E assim Davi entendeu que o Senhor  o havia confirmado como rei de Israel e que, por amor ao seu povo, estava fazendo o seu reino progredir.

[[v10-5-13]]

^<<v10-5-13,13>>^ Depois que saiu da cidade de Hebrom, Davi arranjou mais concubinas  e esposas em Jerusalém e com elas teve mais filhos e filhas.

[[v10-5-14]]

^<<v10-5-14,14>>^ Os filhos de Davi que nasceram em Jerusalém foram: Samua, Sobabe, Natã, Salomão,

[[v10-5-15]]

^<<v10-5-15,15>>^ Ibar, Elisua, Nefegue, Jafia,

[[v10-5-16]]

^<<v10-5-16,16>>^ Elisama, Eliada e Elifelete.

[[v10-5-17]]

^<<v10-5-17,17>>^ Quando os filisteus souberam que Davi tinha sido ungido  como rei de Israel, o seu exército saiu para prendê-lo. Quando soube disso, Davi desceu para a fortaleza .

[[v10-5-18]]

^<<v10-5-18,18>>^ Os filisteus chegaram ao vale dos Gigantes e o ocuparam.

[[v10-5-19]]

^<<v10-5-19,19>>^ Aí Davi perguntou a Deus, o Senhor : — Devo lutar contra os filisteus? Tu me darás a vitória? — Vá! — disse o Senhor . — Eu lhe darei a vitória.

[[v10-5-20]]

^<<v10-5-20,20>>^ Então Davi foi até Baal-Perazim e ali venceu os filisteus. Ele disse: — Como uma enchente que derruba tudo, assim o Senhor  abriu uma brecha no meio dos meus inimigos. Por isso, aquele lugar é chamado de Baal-Perazim .

[[v10-5-21]]

^<<v10-5-21,21>>^ Ali os filisteus abandonaram os seus ídolos, e Davi e os seus soldados os levaram embora.

[[v10-5-22]]

^<<v10-5-22,22>>^ Então os filisteus voltaram para o vale dos Gigantes e o ocuparam.

[[v10-5-23]]

^<<v10-5-23,23>>^ Mais uma vez Davi consultou o Senhor , e ele respondeu: — Não os ataque daqui. Dê a volta, vá até as amoreiras e ataque por trás.

[[v10-5-24]]

^<<v10-5-24,24>>^ Quando você ouvir o barulho de marcha por cima das amoreiras, fique pronto para atacar porque isso quer dizer que eu estou indo na sua frente para derrotar o exército dos filisteus.

[[v10-5-25]]

^<<v10-5-25,25>>^ Davi fez o que o Senhor  havia mandado e obrigou os filisteus a recuarem desde Geba até Gezer.

'''

xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[&#60; Capítulo Anterior] | <<v10-5-0,Topo>> | xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[Próximo Capítulo &#62;]