include::./index.adoc[]

[[v10-18-0]]
=== 2 Samuel, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-18-1]]

^<<v10-18-1,1>>^ O rei Davi juntou todos os seus soldados, dividiu-os em grupos de mil e em grupos de cem e colocou oficiais para comandá-los.

[[v10-18-2]]

^<<v10-18-2,2>>^ Então mandou que saíssem em três grupos, um comandado por Joabe, outro por Abisai, irmão de Joabe (a mãe deles era Zeruia), e outro por Itai, da cidade de Gate. E o rei disse aos seus homens: — Eu também irei com vocês.

[[v10-18-3]]

^<<v10-18-3,3>>^ Eles responderam: — O senhor não deve ir. Se formos obrigados a fugir ou se os inimigos matarem a metade do nosso exército, isso não fará nenhuma diferença para eles. Mas o senhor vale por dez mil de nós. Será melhor que o senhor fique aqui na cidade e nos mande socorro.

[[v10-18-4]]

^<<v10-18-4,4>>^ — Eu farei o que vocês acharem melhor! — respondeu o rei. Então ficou ao lado do portão enquanto os seus soldados saíam marchando em grupos de mil e de cem.

[[v10-18-5]]

^<<v10-18-5,5>>^ Ele deu a seguinte ordem a Joabe, Abisai e Itai: — Se vocês gostam de mim, tratem o jovem Absalão com delicadeza. E toda a tropa ouviu Davi dar essa ordem a todos os oficiais.

[[v10-18-6]]

^<<v10-18-6,6>>^ O exército de Davi avançou contra os israelitas no campo e lutou contra eles na floresta de Efraim.

[[v10-18-7]]

^<<v10-18-7,7>>^ E os soldados de Davi derrotaram os israelitas. Foi uma derrota terrível: vinte mil homens foram mortos naquele dia.

[[v10-18-8]]

^<<v10-18-8,8>>^ A luta se espalhou por toda aquela região, e morreram mais homens na floresta do que no campo de batalha.

[[v10-18-9]]

^<<v10-18-9,9>>^ De repente, Absalão se encontrou com alguns dos soldados de Davi. Absalão ia montado numa mula, e, ao passar por baixo de um grande carvalho, a sua cabeça ficou presa nos galhos. A mula continuou a correr, e Absalão ficou pendurado.

[[v10-18-10]]

^<<v10-18-10,10>>^ Um dos homens de Davi viu Absalão e disse a Joabe: — Eu vi Absalão pendurado num carvalho!

[[v10-18-11]]

^<<v10-18-11,11>>^ Joabe disse: — Você viu? Então por que não o matou ali mesmo? Eu teria dado a você dez barras de prata e um cinto.

[[v10-18-12]]

^<<v10-18-12,12>>^ Mas o homem respondeu: — Mesmo que o senhor me desse mil barras de prata, eu não levantaria um dedo contra o filho do rei. Nós todos ouvimos o rei ordenar ao senhor, a Abisai e a Itai: "Se vocês gostam de mim, tratem o jovem Absalão com delicadeza."

[[v10-18-13]]

^<<v10-18-13,13>>^ Se eu tivesse desobedecido e matado Absalão, o rei saberia disso — ele sabe de tudo —, e o senhor não me defenderia.

[[v10-18-14]]

^<<v10-18-14,14>>^ — Não vou perder mais tempo com você! — disse Joabe. Então Joabe pegou três lanças e as enterrou no peito de Absalão enquanto ele ainda estava vivo, pendurado no carvalho.

[[v10-18-15]]

^<<v10-18-15,15>>^ E dez soldados de Joabe cercaram Absalão e acabaram de matá-lo.

[[v10-18-16]]

^<<v10-18-16,16>>^ Aí Joabe tocou a corneta a fim de parar a luta. As suas tropas pararam de perseguir os israelitas e voltaram.

[[v10-18-17]]

^<<v10-18-17,17>>^ Eles pegaram o corpo de Absalão e o jogaram numa cova funda na floresta e o cobriram com uma enorme pilha de pedras. Então todos os israelitas fugiram, cada um para a sua casa.

[[v10-18-18]]

^<<v10-18-18,18>>^ Quando ainda vivia, Absalão construiu um monumento para si mesmo no vale dos Reis porque ele não tinha nenhum filho para manter vivo o seu nome. E deu o seu próprio nome ao monumento, que até hoje  é conhecido como o Monumento de Absalão.

[[v10-18-19]]

^<<v10-18-19,19>>^ Então Aimaás, filho de Zadoque, disse a Joabe: — Deixe que eu vá correndo dar ao rei a notícia de que o Senhor  Deus fez justiça, livrando-o dos seus inimigos.

[[v10-18-20]]

^<<v10-18-20,20>>^ — Não! — respondeu Joabe. — Hoje você não vai levar nenhuma boa notícia. Outro dia você poderá fazer isso, mas hoje não, porque o filho do rei morreu.

[[v10-18-21]]

^<<v10-18-21,21>>^ Então disse ao seu escravo etíope: — Vá você e diga ao rei o que viu. O escravo curvou-se diante de Joabe e saiu correndo.

[[v10-18-22]]

^<<v10-18-22,22>>^ Aimaás insistiu: — Por favor, deixe-me levar as notícias também, não importa o que aconteça. — Por que você quer fazer isso, meu filho? — perguntou Joabe. — Você não receberá nenhuma recompensa por isso.

[[v10-18-23]]

^<<v10-18-23,23>>^ — Aconteça o que acontecer, eu quero ir! — repetiu Aimaás. — Então vá! — respondeu Joabe. Aí ele saiu correndo pela estrada do vale do rio Jordão e passou na frente do escravo etíope.

[[v10-18-24]]

^<<v10-18-24,24>>^ Davi estava sentado entre o portão que dá para fora da cidade e o que dá para dentro. O vigia subiu para o alto da muralha e ficou no terraço do portão. Ele olhou para fora e viu um homem correndo sozinho.

[[v10-18-25]]

^<<v10-18-25,25>>^ Então avisou o rei. E o rei disse: — Se ele está sozinho, vem trazendo boas notícias. E o corredor veio chegando.

[[v10-18-26]]

^<<v10-18-26,26>>^ Então o vigia viu outro homem correndo sozinho e gritou para o guarda do portão: — Veja! Vem vindo outro homem correndo! — Esse também está trazendo boas notícias! — respondeu Davi.

[[v10-18-27]]

^<<v10-18-27,27>>^ O vigia disse: — Pelo jeito de correr, o primeiro homem deve ser Aimaás, filho de Zadoque! — Ele é um bom rapaz — disse o rei — e deve estar trazendo boas notícias.

[[v10-18-28]]

^<<v10-18-28,28>>^ Aimaás gritou para o rei: — Tudo vai bem! Então ajoelhou-se diante dele e encostou o rosto no chão, dizendo: — Que o Senhor , seu Deus, seja louvado, pois lhe deu a vitória sobre aqueles que se revoltaram contra o senhor.

[[v10-18-29]]

^<<v10-18-29,29>>^ — O jovem Absalão está bem? — perguntou o rei. Aimaás respondeu: — No momento em que o seu oficial Joabe me mandou vir, eu vi uma grande agitação, porém não sei dizer o que era.

[[v10-18-30]]

^<<v10-18-30,30>>^ — Fique de lado e espere! — disse o rei. Ele ficou de lado e esperou.

[[v10-18-31]]

^<<v10-18-31,31>>^ Então o mensageiro etíope chegou e disse ao rei: — Ó rei, eu tenho boas notícias para o senhor! Hoje o Senhor  Deus lhe deu a vitória sobre todos os que se revoltaram contra o senhor.

[[v10-18-32]]

^<<v10-18-32,32>>^ — E o jovem Absalão está bem? — perguntou o rei. O mensageiro respondeu: — Eu gostaria que o que aconteceu com ele acontecesse com todos os inimigos do senhor e com todos os que se revoltam contra o senhor.

[[v10-18-33]]

^<<v10-18-33,33>>^ Então o rei ficou profundamente triste. Subiu à sala que ficava por cima do portão e começou a chorar. Ele andava para lá e para cá e gritava: — Ó meu filho! Meu filho Absalão! Absalão, meu filho! Eu preferiria ter morrido no seu lugar, meu filho!

'''

xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]