include::./index.adoc[]

[[v10-16-0]]
=== 2 Samuel, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-16-1]]

^<<v10-16-1,1>>^ Davi passou para o outro lado do monte das Oliveiras e ali se encontrou, de repente, com Ziba, o empregado de Mefibosete. Ele trazia dois jumentos carregados com duzentos pães, cem cachos de passas, cem cachos de frutas frescas e um odre  cheio de vinho.

[[v10-16-2]]

^<<v10-16-2,2>>^ Então o rei Davi lhe perguntou: — O que você vai fazer com tudo isso? Ziba respondeu: — Os jumentos são para a família do rei montar; o pão e as frutas, para os homens comerem; e o vinho é para eles beberem quando ficarem cansados no deserto.

[[v10-16-3]]

^<<v10-16-3,3>>^ — Onde está Mefibosete, o neto do seu patrão Saul? — perguntou o rei. Ziba respondeu: — Ele ficou em Jerusalém porque está convencido de que agora os israelitas vão devolver a ele o reino do seu avô Saul.

[[v10-16-4]]

^<<v10-16-4,4>>^ O rei disse a Ziba: — Tudo o que era de Mefibosete é seu. Ziba respondeu: — Eu me curvo diante do meu rei e senhor e que eu sempre possa agradá-lo!

[[v10-16-5]]

^<<v10-16-5,5>>^ Quando o rei Davi chegou à cidade de Baurim, Simei, filho de Gera, um dos parentes de Saul, foi encontrar-se com ele e começou a amaldiçoá-lo.

[[v10-16-6]]

^<<v10-16-6,6>>^ Simei começou também a jogar pedras em Davi e nos seus oficiais, apesar de o rei estar rodeado pelos seus homens e pelos guardas pessoais.

[[v10-16-7]]

^<<v10-16-7,7>>^ Ele amaldiçoou Davi e disse: — Fora daqui, assassino! Criminoso!

[[v10-16-8]]

^<<v10-16-8,8>>^ Você tomou o reino de Saul. O Senhor  Deus o está castigando por você ter matado tantas pessoas da família de Saul. Agora Deus entregou o reino ao seu filho Absalão, e você está arruinado, seu assassino!

[[v10-16-9]]

^<<v10-16-9,9>>^ Então Abisai, cuja mãe era Zeruia, disse ao rei: — Por que o senhor permite que este cachorro morto o amaldiçoe? Deixe que eu vá lá cortar a cabeça dele!

[[v10-16-10]]

^<<v10-16-10,10>>^ — Vocês, filhos de Zeruia, não têm nada a ver com isso! — respondeu o rei a Abisai e ao seu irmão Joabe. — Se foi o Senhor  Deus quem mandou que este homem me amaldiçoasse, quem tem o direito de perguntar por que é que ele está fazendo isso?

[[v10-16-11]]

^<<v10-16-11,11>>^ E Davi disse a Abisai e a todos os seus oficiais: — Se o meu próprio filho está tentando me matar, por que eu ficaria admirado se este membro da tribo  de Benjamim quisesse fazer o mesmo? Deixem esse homem em paz. Deixem que ele amaldiçoe porque foi o Senhor  quem o mandou fazer isso.

[[v10-16-12]]

^<<v10-16-12,12>>^ Pode ser que o Senhor  olhe para a minha aflição e me dê algumas bênçãos em lugar destas maldições.

[[v10-16-13]]

^<<v10-16-13,13>>^ Então Davi e os seus homens continuaram o seu caminho. Simei também ia ao lado, caminhando pelo monte, amaldiçoando e jogando pedras e terra em Davi.

[[v10-16-14]]

^<<v10-16-14,14>>^ O rei e todos os seus homens chegaram muito cansados ao rio Jordão e descansaram ali.

[[v10-16-15]]

^<<v10-16-15,15>>^ Absalão e todos os israelitas entraram em Jerusalém, e Aitofel estava com eles.

[[v10-16-16]]

^<<v10-16-16,16>>^ Quando Husai, o conselheiro particular de Davi, encontrou Absalão, gritou: — Viva o rei! Viva o rei!

[[v10-16-17]]

^<<v10-16-17,17>>^ E Absalão perguntou: — Onde está a sua fidelidade ao seu amigo? Por que você não foi com ele?

[[v10-16-18]]

^<<v10-16-18,18>>^ Husai respondeu: — Como é que eu poderia fazer isso? Eu sou a favor daquele que foi escolhido por Deus, o Senhor , por este povo e por todos os israelitas. Eu ficarei com o senhor.

[[v10-16-19]]

^<<v10-16-19,19>>^ Afinal de contas, a quem eu deveria servir, a não ser o filho do meu chefe? Assim como servi o seu pai, eu agora o servirei.

[[v10-16-20]]

^<<v10-16-20,20>>^ Aí Absalão disse a Aitofel: — Eu quero o seu conselho. O que devemos fazer?

[[v10-16-21]]

^<<v10-16-21,21>>^ Aitofel respondeu: — Tenha relações com as concubinas  do seu pai, aquelas que ele deixou cuidando do palácio. Assim todos em Israel ficarão sabendo que você se tornou inimigo do seu pai, e os seus seguidores ficarão bem animados.

[[v10-16-22]]

^<<v10-16-22,22>>^ Então armaram uma barraca para Absalão no terraço do palácio, e ali, na frente de todos, ele teve relações com as concubinas do seu pai.

[[v10-16-23]]

^<<v10-16-23,23>>^ Naquela época os conselhos que Aitofel dava eram seguidos como se fossem a própria palavra de Deus; tanto Davi como Absalão os seguiam.

'''

xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[&#60; Capítulo Anterior] | <<v10-16-0,Topo>> | xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[Próximo Capítulo &#62;]