include::./index.adoc[]

[[v10-4-0]]
=== 2 Samuel, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v10-4-1]]

^<<v10-4-1,1>>^ Quando Isbosete, filho de Saul, soube que Abner havia sido assassinado na cidade de Hebrom, perdeu a coragem, e todo o povo de Israel ficou com medo.

[[v10-4-2]]

^<<v10-4-2,2>>^ Havia dois oficiais de Isbosete que comandavam os ataques rápidos ao território inimigo. Eles se chamavam Baaná e Recabe e eram filhos de Rimom, da cidade de Beerote, da tribo  de Benjamim. (A cidade de Beerote é considerada como parte do território de Benjamim.

[[v10-4-3]]

^<<v10-4-3,3>>^ Os antigos moradores de Beerote haviam fugido para a cidade de Gitaim e eles vivem ali como estrangeiros até hoje .)

[[v10-4-4]]

^<<v10-4-4,4>>^ Quando Saul e Jônatas foram mortos em Jezreel, Mefibosete, filho de Jônatas, tinha cinco anos de idade. Ao chegar a notícia da morte de Saul e de Jônatas, a mulher que cuidava de Mefibosete o pegou e fugiu. Mas estava com tanta pressa, que o deixou cair, e ele ficou manco.

[[v10-4-5]]

^<<v10-4-5,5>>^ Recabe e Baaná foram para a casa de Isbosete e chegaram lá quando ele estava tirando a sua soneca depois do almoço.

[[v10-4-6]]

^<<v10-4-6,6>>^ A mulher que estava na porta peneirando trigo havia ficado com sono e estava dormindo. Por isso, Baaná e Recabe entraram em silêncio,

[[v10-4-7]]

^<<v10-4-7,7>>^ foram ao quarto onde Isbosete dormia um sono pesado e o mataram. Então cortaram a cabeça dele e a levaram consigo. Eles caminharam a noite toda pelo vale do rio Jordão.

[[v10-4-8]]

^<<v10-4-8,8>>^ Quando chegaram a Hebrom, mostraram a cabeça de Isbosete ao rei Davi e disseram: — Aqui está a cabeça de Isbosete, filho do seu inimigo Saul, que queria matá-lo. Hoje o Senhor  Deus vingou o rei, meu senhor, de Saul e dos seus descendentes.

[[v10-4-9]]

^<<v10-4-9,9>>^ Davi respondeu: — Eu agarrei e mandei matar o mensageiro que foi ao meu encontro na cidade de Ziclague; pois ele, pensando que estava me dando uma boa notícia, me contou a respeito da morte de Saul. Agora, juro pelo Senhor , o Deus vivo, que me salvou de todos os perigos, que eu castigarei muito mais os homens traiçoeiros que mataram um inocente que estava dormindo na sua própria casa! Agora vou me vingar de vocês por terem matado Isbosete e vou varrer vocês da face da terra.

[[v10-4-10]]

^<<v10-4-10,10>>^ Davi respondeu:

'''

xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[&#60; Capítulo Anterior] | <<v10-4-0,Topo>> | xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[Próximo Capítulo &#62;]