include::./index.adoc[]

[[v30-8-0]]
=== Amós, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-8-1]]

^<<v30-8-1,1>>^ O Senhor  Deus me mostrou numa visão o seguinte: estava ali uma cesta cheia de frutas maduras.

[[v30-8-2]]

^<<v30-8-2,2>>^ Ele me perguntou: — Amós, o que é que você está vendo? — Uma cesta cheia de frutas maduras! — respondi. Então ele me disse: — Chegou o fim para o povo de Israel, que está maduro, pronto para ser arrancado como uma fruta madura. Nunca mais vou mudar de ideia e perdoá-los.

[[v30-8-3]]

^<<v30-8-3,3>>^ Naquele dia, em vez de canções haverá lamentações no palácio. Haverá tantos mortos, que os corpos serão jogados em qualquer lugar. Silêncio! Eu, o Senhor , estou falando.

[[v30-8-4]]

^<<v30-8-4,4>>^ Escutem, vocês que maltratam os necessitados e exploram os humildes aqui neste país.

[[v30-8-5]]

^<<v30-8-5,5>>^ Vocês dizem: "Quem dera que a Festa da Lua Nova  já tivesse terminado para que pudéssemos voltar a vender os cereais! Como seria bom se o sábado já tivesse passado! Aí começaríamos a vender trigo de novo, cobrando preços bem altos, usando pesos e medidas falsos

[[v30-8-6]]

^<<v30-8-6,6>>^ e vendendo trigo que não presta. Os pobres não terão dinheiro para pagar as suas dívidas, nem mesmo os que tomaram dinheiro emprestado para comprar um par de sandálias. Assim eles se venderão a nós e serão nossos escravos!"

[[v30-8-7]]

^<<v30-8-7,7>>^ Portanto, o Senhor , o Deus a quem o povo de Israel louva, faz este juramento: — Nunca esquecerei aquilo que o meu povo tem feito.

[[v30-8-8]]

^<<v30-8-8,8>>^ Por causa disso, a terra tremerá, e todos os seus moradores chorarão de tristeza. A terra subirá e baixará como as águas do rio Nilo.

[[v30-8-9]]

^<<v30-8-9,9>>^ Naquele dia, farei o sol se pôr ao meio-dia, e em pleno dia a terra ficará coberta de escuridão. Sou eu, o Senhor , quem está falando.

[[v30-8-10]]

^<<v30-8-10,10>>^ Transformarei as suas festas em velórios; vocês vão chorar em vez de cantar. Em sinal de luto, vocês vestirão roupa feita de pano grosseiro e raparão a cabeça. Vocês serão como pais chorando a morte do filho único. E tudo terminará em amargura.

[[v30-8-11]]

^<<v30-8-11,11>>^ — Está chegando o dia em que mandarei fome pelo país inteiro. Todos ficarão com fome, mas não por falta de comida, e com sede, mas não por falta de água. Todos terão fome e sede de ouvir a mensagem de Deus, o Senhor .

[[v30-8-12]]

^<<v30-8-12,12>>^ Correrão do mar Morto até o mar Mediterrâneo, irão pelas regiões do Norte e do Leste do país, procurando a mensagem de Deus, o Senhor , mas não a encontrarão.

[[v30-8-13]]

^<<v30-8-13,13>>^ Naquele dia, até moços e moças fortes desmaiarão de sede.

[[v30-8-14]]

^<<v30-8-14,14>>^ Os que juram pelos ídolos de Samaria, os que dizem: "Eu juro pelo deus de Dã" ou: "Eu juro pelo deus de Berseba" — todos eles cairão e nunca mais se levantarão. Eu, o Senhor , estou falando.

'''

xref:030-amos/030-amos-007.adoc#v30-7-0[&#60; Capítulo Anterior] | <<v30-8-0,Topo>> | xref:030-amos/030-amos-009.adoc#v30-9-0[Próximo Capítulo &#62;]