include::./index.adoc[]

[[v30-5-0]]
=== Amós, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-5-1]]

^<<v30-5-1,1>>^ Povo de Israel, escute esta canção triste que eu canto a respeito de você:

[[v30-5-2]]

^<<v30-5-2,2>>^ "Israel, bela e pura como uma virgem, caiu e nunca mais se levantará! Está caída na sua própria terra, e ninguém a ajuda a se levantar!"

[[v30-5-3]]

^<<v30-5-3,3>>^ O Senhor  Deus diz: — Se uma cidade mandar mil homens para a guerra, somente cem voltarão vivos; se mandar cem homens, somente dez voltarão.

[[v30-5-4]]

^<<v30-5-4,4>>^ O Senhor  diz isto ao povo de Israel: — Voltem para mim a fim de que tenham vida.

[[v30-5-5]]

^<<v30-5-5,5>>^ Mas não me procurem em Betel, nem em Gilgal, nem em Berseba, pois o povo de Gilgal será levado como prisioneiro para fora do país, e a cidade de Betel vai ficar em ruínas.

[[v30-5-6]]

^<<v30-5-6,6>>^ Voltem para o Senhor  e vocês viverão. Se não voltarem, ele descerá como fogo para destruir o país de Israel, e em Betel ninguém poderá apagar esse fogo.

[[v30-5-7]]

^<<v30-5-7,7>>^ Em vez de praticarem a justiça, vocês praticam a injustiça, que causa amargura, e não respeitam os direitos dos outros.

[[v30-5-8]]

^<<v30-5-8,8>>^ O Senhor  Deus criou as estrelas, as Sete-Cabrinhas e as Três-Marias. Ele faz a noite virar dia e o dia virar noite. Ele chama as águas do mar e as derrama sobre a terra. O seu nome é Senhor .

[[v30-5-9]]

^<<v30-5-9,9>>^ Ele acaba com os poderosos e destrói as suas fortalezas.

[[v30-5-10]]

^<<v30-5-10,10>>^ Vocês têm ódio daqueles que defendem a justiça e detestam as testemunhas que falam a verdade;

[[v30-5-11]]

^<<v30-5-11,11>>^ vocês exploram os pobres e cobram impostos injustos das suas colheitas. Por isso, vocês não vão viver nas casas luxuosas que construíram, nem chegarão a beber o vinho das belas parreiras  que plantaram.

[[v30-5-12]]

^<<v30-5-12,12>>^ Eu sei das muitas maldades e dos graves pecados que vocês cometem. Vocês maltratam as pessoas honestas, aceitam dinheiro para torcer a justiça e não respeitam os direitos dos pobres.

[[v30-5-13]]

^<<v30-5-13,13>>^ Não admira que num tempo mau como este as pessoas que têm juízo fiquem de boca fechada!

[[v30-5-14]]

^<<v30-5-14,14>>^ Procurem fazer o que é certo e não o que é errado, para que vocês vivam. Assim será verdade o que vocês dizem, isto é, que o Senhor , o Deus Todo-Poderoso, está com vocês.

[[v30-5-15]]

^<<v30-5-15,15>>^ Odeiem aquilo que é mau, amem o que é bom e façam com que os direitos de todos sejam respeitados nos tribunais. Talvez o Senhor , o Deus Todo-Poderoso, tenha compaixão das pessoas do seu povo que escaparem da destruição.

[[v30-5-16]]

^<<v30-5-16,16>>^ O Senhor , o Deus Todo-Poderoso, diz: — Haverá gritos de dor em todas as cidades, e as ruas ficarão cheias de gente chorando. Até lavradores serão chamados para chorar pelos defuntos, junto com as pessoas que são pagas para fazer isso.

[[v30-5-17]]

^<<v30-5-17,17>>^ Haverá choro em todas as plantações de uvas. E tudo isso acontecerá porque eu virei castigá-los. Eu, o Senhor , estou falando.

[[v30-5-18]]

^<<v30-5-18,18>>^ Ai dos que querem que venha o Dia do Senhor ! Por que é que vocês querem esse dia? Pois será um dia de escuridão e não de luz.

[[v30-5-19]]

^<<v30-5-19,19>>^ Será como um homem que foge de um leão e dá de cara com um urso; ou como alguém que entra em casa e encosta a mão na parede e é picado por uma cobra.

[[v30-5-20]]

^<<v30-5-20,20>>^ O Dia do Senhor  não será um dia de luz; pelo contrário, será um dia de trevas, de escuridão total.

[[v30-5-21]]

^<<v30-5-21,21>>^ O Senhor  diz ao seu povo: — Eu odeio, eu detesto as suas festas religiosas; não tolero as suas reuniões solenes.

[[v30-5-22]]

^<<v30-5-22,22>>^ Não aceito animais que são queimados em sacrifício , nem as ofertas de cereais, nem os animais gordos que vocês oferecem como sacrifícios de paz.

[[v30-5-23]]

^<<v30-5-23,23>>^ Parem com o barulho das suas canções religiosas; não quero mais ouvir a música de harpas .

[[v30-5-24]]

^<<v30-5-24,24>>^ Em vez disso, quero que haja tanta justiça como as águas de uma enchente e que a honestidade seja como um rio que não para de correr.

[[v30-5-25]]

^<<v30-5-25,25>>^ — Povo de Israel, por acaso, vocês me apresentaram sacrifícios e ofertas de cereais durante os quarenta anos em que estiveram no deserto?

[[v30-5-26]]

^<<v30-5-26,26>>^ Agora, vocês vão sair carregando as imagens do deus Sicute e da estrela Quium , que vocês fizeram para adorar. Vocês vão carregar essas imagens

[[v30-5-27]]

^<<v30-5-27,27>>^ quando eu os levar como prisioneiros para lá de Damasco. Eu, o Senhor , o Deus Todo-Poderoso, estou falando.

'''

xref:030-amos/030-amos-004.adoc#v30-4-0[&#60; Capítulo Anterior] | <<v30-5-0,Topo>> | xref:030-amos/030-amos-006.adoc#v30-6-0[Próximo Capítulo &#62;]