include::./index.adoc[]

[[v30-1-0]]
=== Amós, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-1-1]]

^<<v30-1-1,1>>^ Esta é a mensagem a respeito do povo de Israel que Deus deu a Amós, pastor de ovelhas da cidade de Tecoa. Isso aconteceu dois anos antes do terremoto, quando Uzias era rei de Judá, e Jeroboão, filho de Joás, era rei de Israel.

[[v30-1-2]]

^<<v30-1-2,2>>^ Amós disse: "Do monte Sião , em Jerusalém, o Senhor  Deus fala alto, e a sua voz parece o trovão. Os pastos murcham, e tudo seca no monte Carmelo."

[[v30-1-3]]

^<<v30-1-3,3>>^ O Senhor  Deus diz: — O povo de Damasco tem cometido tantos pecados, tantos mesmo, que eu tenho de castigá-los. Eles torturaram o povo de Gileade, fazendo passar sobre eles rodas com pontas de ferro.

[[v30-1-4]]

^<<v30-1-4,4>>^ Por isso, eu vou pôr fogo no palácio do rei Hazael, e esse mesmo fogo destruirá também as fortalezas do rei Ben-Hadade.

[[v30-1-5]]

^<<v30-1-5,5>>^ Arrombarei os portões da cidade de Damasco e acabarei com os governadores de Biqueate-Avém e de Bete-Éden. O povo da Síria será levado como prisioneiro para a terra de Quir. Eu, o Senhor , falei.

[[v30-1-6]]

^<<v30-1-6,6>>^ O Senhor  Deus diz: — O povo de Gaza tem cometido tantos pecados, tantos mesmo, que eu tenho de castigá-los. Eles levaram como prisioneiro todo o povo de uma região e os venderam como escravos ao povo de Edom.

[[v30-1-7]]

^<<v30-1-7,7>>^ Por isso, eu vou pôr fogo nas muralhas de Gaza, e esse mesmo fogo destruirá também as fortalezas daquela cidade.

[[v30-1-8]]

^<<v30-1-8,8>>^ Vou acabar com os reis de Asdode e de Asquelom. Destruirei a cidade de Ecrom e acabarei com todos os outros filisteus. Eu, o Senhor , falei.

[[v30-1-9]]

^<<v30-1-9,9>>^ O Senhor  Deus diz: — O povo de Tiro tem cometido tantos pecados, tantos mesmo, que eu tenho de castigá-los. Levaram como prisioneiro para Edom todo o povo de uma região com o qual tinham feito um acordo de amizade.

[[v30-1-10]]

^<<v30-1-10,10>>^ Por isso, eu vou pôr fogo nas muralhas de Tiro, e esse mesmo fogo destruirá também as fortalezas daquela cidade.

[[v30-1-11]]

^<<v30-1-11,11>>^ O Senhor  Deus diz: — O povo do país de Edom tem cometido tantos pecados, tantos mesmo, que eu tenho de castigá-los. Fizeram guerra contra os seus irmãos , os israelitas, e não tiveram dó nem piedade. A raiva dos edomitas não parou, e eles conservaram o seu ódio para sempre.

[[v30-1-12]]

^<<v30-1-12,12>>^ Por isso, eu vou pôr fogo na cidade de Temã, e esse mesmo fogo destruirá também as fortalezas de Bosra.

[[v30-1-13]]

^<<v30-1-13,13>>^ O Senhor  Deus diz: — O povo do país de Amom tem cometido tantos pecados, tantos mesmo, que eu tenho de castigá-los. Na guerra para conquistar mais terras na região de Gileade, eles rasgaram as barrigas de mulheres grávidas.

[[v30-1-14]]

^<<v30-1-14,14>>^ Por isso, eu vou pôr fogo nas muralhas de Rabá, e esse mesmo fogo destruirá também as fortalezas daquela cidade. Haverá batalhas violentas e gritos de homens lutando.

[[v30-1-15]]

^<<v30-1-15,15>>^ O rei e as autoridades serão levados como prisioneiros. Eu, o Senhor , falei.

'''

xref:029-joel/029-joel-003.adoc#v29-3-0[&#60; Capítulo Anterior] | <<v30-1-0,Topo>> | xref:030-amos/030-amos-002.adoc#v30-2-0[Próximo Capítulo &#62;]