include::./index.adoc[]

[[v30-3-0]]
=== Amós, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-3-1]]

^<<v30-3-1,1>>^ Povo de Israel, escute o que o Senhor  Deus disse a respeito de vocês, o povo que ele tirou do Egito:

[[v30-3-2]]

^<<v30-3-2,2>>^ — No mundo inteiro, vocês são o único povo que eu escolhi para ser meu. Por isso, tenho de castigá-los por causa de todos os pecados que vocês cometeram.

[[v30-3-3]]

^<<v30-3-3,3>>^ Por acaso, duas pessoas viajam juntas, sem terem combinado antes?

[[v30-3-4]]

^<<v30-3-4,4>>^ Será que o leão ruge na floresta, sem ter achado algum animal para caçar? Será que o leão novo fica rosnando na caverna, se não tiver pegado nada?

[[v30-3-5]]

^<<v30-3-5,5>>^ Será que um passarinho cai numa armadilha que não estava armada? Será que uma armadilha se desarma sem ter pegado algum animal?

[[v30-3-6]]

^<<v30-3-6,6>>^ Quando tocam a corneta de alarme, será que o povo não fica com medo? Por acaso, cai alguma desgraça sobre uma cidade, sem que o Senhor  Deus a tenha feito acontecer?

[[v30-3-7]]

^<<v30-3-7,7>>^ Por acaso, o Senhor  Deus faz alguma coisa sem revelar aos seus servos , os profetas ?

[[v30-3-8]]

^<<v30-3-8,8>>^ Quando o leão ruge, quem não fica com medo? Quando o Senhor  Deus fala, quem não anuncia a sua mensagem?

[[v30-3-9]]

^<<v30-3-9,9>>^ Anunciem nos palácios de Asdode e do Egito o seguinte: "Reúnam-se nos montes que ficam ao redor de Samaria e vejam a desordem que existe na cidade e os crimes que são cometidos."

[[v30-3-10]]

^<<v30-3-10,10>>^ O Senhor  Deus diz: — O povo de Samaria não sabe fazer nada com honestidade, e os seus palácios estão cheios de coisas roubadas com violência.

[[v30-3-11]]

^<<v30-3-11,11>>^ Por isso, os inimigos cercarão o seu país, destruirão as suas fortalezas e levarão embora tudo o que está nos palácios.

[[v30-3-12]]

^<<v30-3-12,12>>^ O Senhor  Deus diz: — Quando um leão pega uma ovelha, às vezes o pastor somente consegue salvar duas pernas ou uma orelha. Assim também serão salvos somente alguns moradores de Samaria, que agora descansam em camas de luxo.

[[v30-3-13]]

^<<v30-3-13,13>>^ Escutem o que eu digo e acusem o meu povo, os descendentes de Jacó — diz Deus, o Senhor  Todo-Poderoso.

[[v30-3-14]]

^<<v30-3-14,14>>^ — Quando eu castigar o povo de Israel por causa dos seus pecados, destruirei os altares de Betel. As quatro pontas de todos os altares serão quebradas e cairão no chão.

[[v30-3-15]]

^<<v30-3-15,15>>^ Destruirei as casas de inverno e as de verão; as casas luxuosas, as casas enfeitadas de marfim, todas elas serão destruídas. Sou eu, o Senhor , quem está falando.

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]