include::./index.adoc[]

[[v30-6-0]]
=== Amós, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-6-1]]

^<<v30-6-1,1>>^ Ai dos que têm uma vida boa em Jerusalém! Ai de vocês que vivem sossegados em Samaria, vocês que são as autoridades desse grande país de Israel, vocês a quem o povo vai pedir ajuda!

[[v30-6-2]]

^<<v30-6-2,2>>^ Vocês dizem ao povo: "Vão olhar a cidade de Calné, e depois vão até a grande cidade de Hamate, e dali cheguem até a cidade de Gate, na terra dos filisteus. Por acaso, aqueles povos são mais ricos do que nós ou os seus países maiores do que o nosso?"

[[v30-6-3]]

^<<v30-6-3,3>>^ Vocês não querem acreditar que o dia do castigo esteja perto, mas o que vocês estão fazendo vai apressar a chegada de um tempo de violência.

[[v30-6-4]]

^<<v30-6-4,4>>^ Ai de vocês que gostam de banquetes, em que se deitam em sofás luxuosos e comem carne de ovelhas e de bezerros gordos!

[[v30-6-5]]

^<<v30-6-5,5>>^ Vocês fazem músicas como fez o rei Davi e gostam de cantá-las com acompanhamento de harpas .

[[v30-6-6]]

^<<v30-6-6,6>>^ Bebem vinho em taças enormes, usam os perfumes mais caros, mas não se importam com a desgraça do país.

[[v30-6-7]]

^<<v30-6-7,7>>^ Portanto, vocês serão os primeiros a serem levados como prisioneiros para fora do país, e não haverá mais banquetes alegres.

[[v30-6-8]]

^<<v30-6-8,8>>^ O Senhor , o Todo-Poderoso, jurou assim: — Eu vou entregar a cidade de Samaria nas mãos do inimigo, que levará embora tudo o que encontrar. Pois eu odeio o orgulho do povo de Israel, detesto os seus palácios.

[[v30-6-9]]

^<<v30-6-9,9>>^ E vai acontecer que, se houver dez pessoas numa casa, todas morrerão.

[[v30-6-10]]

^<<v30-6-10,10>>^ E, quando alguém chegar para tirar da casa o corpo do seu parente e queimá-lo, perguntará a quem ainda estiver vivo lá dentro: "Tem mais gente aí?" O outro responderá: "Não tem, não." Então o primeiro dirá: "Cale a boca! Não devemos nem dizer o nome do Senhor !"

[[v30-6-11]]

^<<v30-6-11,11>>^ Pois o Senhor  vai dar uma ordem, e todas as casas, as grandes e as pequenas, serão destruídas.

[[v30-6-12]]

^<<v30-6-12,12>>^ Por acaso, podem os cavalos galopar sobre as rochas? Ou será que os bois podem puxar o arado no mar? Claro que não! Mas vocês fazem a honestidade virar veneno e a justiça virar injustiça.

[[v30-6-13]]

^<<v30-6-13,13>>^ Vocês se orgulham de terem derrotado a cidade de Lo-Debar e se gabam, dizendo: "Pela nossa própria força conquistamos Carnaim ."

[[v30-6-14]]

^<<v30-6-14,14>>^ O Senhor , o Deus Todo-Poderoso, diz: — Povo de Israel, vou mandar uma nação invadir o seu país, e todos vocês serão perseguidos desde a subida de Hamate, no Norte, até o riacho Arabá, no Sul.

'''

xref:030-amos/030-amos-005.adoc#v30-5-0[&#60; Capítulo Anterior] | <<v30-6-0,Topo>> | xref:030-amos/030-amos-007.adoc#v30-7-0[Próximo Capítulo &#62;]