include::./index.adoc[]

[[v30-9-0]]
=== Amós, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-9-1]]

^<<v30-9-1,1>>^ Eu vi o Senhor perto do altar . Ele disse : — Dê pancadas nas colunas do templo até que o edifício todo comece a tremer. Deixe cair pedaços das colunas nas cabeças das pessoas que estão lá dentro. Os que escaparem com vida eu matarei na guerra; nenhum deles escapará, nenhum viverá.

[[v30-9-2]]

^<<v30-9-2,2>>^ Mesmo que consigam entrar pela terra adentro e chegar até o mundo dos mortos , eu os tirarei dali; mesmo que subam até o céu, eu os farei descer de lá.

[[v30-9-3]]

^<<v30-9-3,3>>^ Se procurarem se esconder no alto do monte Carmelo, eu irei atrás deles e os pegarei; se eles se esconderem de mim no fundo do mar, eu darei ordem à Serpente do mar , e ela os morderá.

[[v30-9-4]]

^<<v30-9-4,4>>^ Se forem levados como prisioneiros pelo inimigo, eu darei ordem, e eles serão mortos. Pois eu vou cuidar deles, não para protegê-los, mas para destruí-los.

[[v30-9-5]]

^<<v30-9-5,5>>^ O Senhor , o Deus Todo-Poderoso, toca na terra, e ela treme, e todos os seus moradores choram de tristeza. A terra sobe e baixa como as águas do rio Nilo.

[[v30-9-6]]

^<<v30-9-6,6>>^ Deus constrói a sua casa nas alturas e coloca o céu por cima da terra. Ele chama as águas do mar e as derrama sobre a terra. O seu nome é Senhor !

[[v30-9-7]]

^<<v30-9-7,7>>^ O Senhor  Deus diz: — Povo de Israel, eu amo o povo da Etiópia tanto quanto amo vocês. Assim como eu trouxe vocês do Egito, eu também trouxe os filisteus da ilha de Creta e os arameus da terra de Quir.

[[v30-9-8]]

^<<v30-9-8,8>>^ Estou olhando para Israel, este país de pecadores, e vou fazê-lo desaparecer da terra; mas não acabarei com todos os israelitas. Sou eu, o Senhor , quem está falando.

[[v30-9-9]]

^<<v30-9-9,9>>^ — Vou dar ordem e vou separar os bons dos maus em Israel, como quem separa o trigo da casca, sem perder um só grão.

[[v30-9-10]]

^<<v30-9-10,10>>^ Vão morrer na guerra todos os pecadores do meu povo, isto é, todos os que dizem: "Deus não deixará que qualquer desastre chegue perto de nós."

[[v30-9-11]]

^<<v30-9-11,11>>^ O Senhor  Deus diz: — Naquele dia, eu construirei de novo o reino de Davi, que é como uma casa que caiu. Taparei as rachaduras das paredes e levantarei a casa que estava em ruínas, e ela ficará como era antes.

[[v30-9-12]]

^<<v30-9-12,12>>^ Então o meu povo conquistará o que restar do país de Edom e de todas as outras nações que eram minhas. Eu farei com que tudo isso aconteça. Sou eu, o Senhor , quem está falando.

[[v30-9-13]]

^<<v30-9-13,13>>^ — Está chegando o dia em que o trigo crescerá mais depressa do que poderá ser colhido, as parreiras  produzirão uvas mais depressa do que se poderá fazer vinho. As parreiras produzirão tantas uvas, que o vinho vai correr à vontade, como um rio.

[[v30-9-14]]

^<<v30-9-14,14>>^ Trarei o meu povo de volta do cativeiro  para a sua terra. Eles construirão de novo as cidades que estavam em ruínas e morarão nelas. Farão plantações de uvas e beberão do seu vinho; cultivarão pomares e comerão as suas frutas.

[[v30-9-15]]

^<<v30-9-15,15>>^ Plantarei o meu povo na terra que lhes dei, e eles nunca mais serão arrancados dali. Eu, o Senhor , o Deus de vocês, falei.

'''

xref:030-amos/030-amos-008.adoc#v30-8-0[&#60; Capítulo Anterior] | <<v30-9-0,Topo>> | xref:031-obadias/031-obadias-001.adoc#v31-1-0[Próximo Capítulo &#62;]