include::./index.adoc[]

[[v30-2-0]]
=== Amós, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-2-1]]

^<<v30-2-1,1>>^ O Senhor  Deus diz: — O povo de Moabe tem cometido tantos pecados, tantos mesmo, que eu tenho de castigá-los. Profanaram  o corpo do rei de Edom, queimando-o até virar cinza.

[[v30-2-2]]

^<<v30-2-2,2>>^ Por isso, eu vou pôr fogo no país de Moabe, e esse mesmo fogo destruirá também as fortalezas de Queriote. Haverá batalhas violentas, gritos de soldados e som de cornetas, e o povo morrerá.

[[v30-2-3]]

^<<v30-2-3,3>>^ Acabarei com o rei e com as autoridades de Moabe. Eu, o Senhor , falei.

[[v30-2-4]]

^<<v30-2-4,4>>^ O Senhor  Deus diz: — O povo de Judá tem cometido tantos pecados, tantos mesmo, que eu tenho de castigá-los. Eles rejeitaram a minha lei  e desobedeceram aos meus mandamentos. Adoraram os mesmos deuses falsos que os seus antepassados adoraram.

[[v30-2-5]]

^<<v30-2-5,5>>^ Por isso, eu vou pôr fogo na terra de Judá, e esse mesmo fogo destruirá as fortalezas de Jerusalém.

[[v30-2-6]]

^<<v30-2-6,6>>^ O Senhor  Deus diz: — O povo de Israel tem cometido tantos pecados, tantos mesmo, que eu tenho de castigá-los. Vendem como escravos pessoas honestas que não podem pagar as suas dívidas e até aquelas que são tão pobres, que não podem pagar a dívida que fizeram para comprar um par de sandálias.

[[v30-2-7]]

^<<v30-2-7,7>>^ Perseguem e humilham os pobres e fazem injustiças contra as pessoas simples. Pais e filhos têm relações com prostitutas nos templos pagãos e assim envergonham o meu santo nome.

[[v30-2-8]]

^<<v30-2-8,8>>^ Perto de qualquer altar pagão, eles se assentam sobre roupas que receberam como garantia de pagamento de dívidas e comem dos sacrifícios  oferecidos aos ídolos. Para comprar o vinho que bebem no templo do deus deles, usam o dinheiro que receberam de multas injustas.

[[v30-2-9]]

^<<v30-2-9,9>>^ — Será que vocês já esqueceram o que fiz com os amorreus ? Eu destruí aqueles homens que eram altos como os cedros e fortes como os carvalhos. Acabei completamente com eles.

[[v30-2-10]]

^<<v30-2-10,10>>^ Fui eu que tirei vocês do Egito, que os guiei quarenta anos pelo deserto e que lhes dei a terra dos amorreus.

[[v30-2-11]]

^<<v30-2-11,11>>^ Escolhi alguns dos seus filhos para serem profetas  e outros para serem nazireus . Não foi isso mesmo o que eu fiz?

[[v30-2-12]]

^<<v30-2-12,12>>^ Mas vocês dão vinho aos nazireus e proíbem os profetas de anunciar a minha mensagem.

[[v30-2-13]]

^<<v30-2-13,13>>^ Pois bem! Eu vou amontoar castigos em cima de vocês, e vocês vão ranger os dentes, como range uma carroça carregada de trigo.

[[v30-2-14]]

^<<v30-2-14,14>>^ Os que correm depressa não poderão escapar, os fortes perderão toda a força, e os corajosos não salvarão a vida.

[[v30-2-15]]

^<<v30-2-15,15>>^ Os homens armados de arcos e flechas não vencerão, e não escaparão com vida nem os que fugirem a pé, nem os que fugirem montados a cavalo.

[[v30-2-16]]

^<<v30-2-16,16>>^ Naquele dia, até os soldados mais valentes jogarão fora as suas armas e fugirão. Eu, o Senhor , estou falando.

'''

xref:030-amos/030-amos-001.adoc#v30-1-0[&#60; Capítulo Anterior] | <<v30-2-0,Topo>> | xref:030-amos/030-amos-003.adoc#v30-3-0[Próximo Capítulo &#62;]