include::./index.adoc[]

[[v30-7-0]]
=== Amós, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-7-1]]

^<<v30-7-1,1>>^ O Senhor  Deus me mostrou numa visão o seguinte: eu vi Deus criar uma praga de gafanhotos. Isso aconteceu quando já começava a crescer o capim que brota depois da colheita que pertence ao rei.

[[v30-7-2]]

^<<v30-7-2,2>>^ Quando os gafanhotos acabaram de comer todas as plantas, eu disse a Deus, o Senhor : — Eu te peço, ó Deus, que nos perdoes. O teu povo é fraco; como poderemos resistir?

[[v30-7-3]]

^<<v30-7-3,3>>^ Então ele mudou de ideia e respondeu: — O que você viu não acontecerá.

[[v30-7-4]]

^<<v30-7-4,4>>^ O Senhor  Deus me mostrou numa visão outra coisa: eu vi que ele estava pronto para castigar o seu povo com fogo. O fogo secou o grande mar que fica debaixo da terra e estava acabando com as plantações.

[[v30-7-5]]

^<<v30-7-5,5>>^ Aí eu disse a Deus, o Senhor : — Ó Deus, para! O teu povo é fraco; como poderemos resistir?

[[v30-7-6]]

^<<v30-7-6,6>>^ Então ele mudou de ideia e respondeu: — Isso também não acontecerá.

[[v30-7-7]]

^<<v30-7-7,7>>^ O Senhor  me mostrou numa visão isto também: ele estava perto de um muro construído direito, a prumo, e tinha um prumo na mão.

[[v30-7-8]]

^<<v30-7-8,8>>^ Ele me perguntou: — Amós, o que é que você está vendo? — Um prumo! — respondi. Então ele me disse: — Eu vou mostrar que o meu povo não anda direito: é como um muro torto, construído fora de prumo. E nunca mais vou perdoar o meu povo.

[[v30-7-9]]

^<<v30-7-9,9>>^ Todos os templos e os outros lugares de adoração da terra de Israel serão destruídos, e eu vou acabar com o rei Jeroboão e com os seus descendentes.

[[v30-7-10]]

^<<v30-7-10,10>>^ Amazias, o sacerdote de Betel, mandou o seguinte recado a Jeroboão, o rei de Israel: — Amós está planejando uma revolta contra o senhor no meio do povo. O que ele está dizendo põe o país em perigo.

[[v30-7-11]]

^<<v30-7-11,11>>^ Ele anda falando assim: "Jeroboão morrerá numa guerra, e o povo de Israel será levado como prisioneiro para fora do seu país."

[[v30-7-12]]

^<<v30-7-12,12>>^ Depois Amazias disse a Amós: — Fora daqui, seu profeta ! Volte para a sua terra de Judá e ganhe a vida por lá com as suas profecias .

[[v30-7-13]]

^<<v30-7-13,13>>^ Pare de profetizar aqui em Betel, pois este é o santuário onde o rei adora, este é o templo principal do país.

[[v30-7-14]]

^<<v30-7-14,14>>^ Amós respondeu: — Não sou profeta por profissão; não ganho a vida profetizando. Sou pastor de ovelhas e também cuido de figueiras.

[[v30-7-15]]

^<<v30-7-15,15>>^ Mas o Senhor  Deus mandou que eu deixasse os meus rebanhos e viesse anunciar a sua mensagem ao povo de Israel.

[[v30-7-16]]

^<<v30-7-16,16>>^ Portanto, escute a mensagem de Deus, o Senhor . Você, Amazias, diz que eu não devo continuar profetizando contra o povo de Israel.

[[v30-7-17]]

^<<v30-7-17,17>>^ Mas o Senhor  diz a você: "A sua mulher virará prostituta aqui na cidade, e os seus filhos e as suas filhas morrerão na guerra. O seu país será dividido entre outros países, e você morrerá numa terra pagã. E o povo de Israel vai ser levado como prisioneiro para fora da sua terra."

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]