include::./index.adoc[]

[[v30-4-0]]
=== Amós, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v30-4-1]]

^<<v30-4-1,1>>^ — Ouçam isto, mulheres da cidade de Samaria, que estão satisfeitas e gordas como as vacas de Basã! Vocês maltratam os necessitados, exploram os pobres e ficam sempre pedindo aos maridos que lhes tragam mais vinho para beber.

[[v30-4-2]]

^<<v30-4-2,2>>^ Eu, o Senhor , juro pelo meu santo nome que virá o tempo em que vocês serão arrastadas para fora da cidade com anzóis, como se fossem peixes; nenhuma de vocês escapará.

[[v30-4-3]]

^<<v30-4-3,3>>^ Vocês sairão em fila pelas brechas das muralhas e serão jogadas na direção do monte Hermom.

[[v30-4-4]]

^<<v30-4-4,4>>^ O Senhor  Deus diz: — Povo de Israel, vocês querem pecar? Pois vão aos santuários de Betel e de Gilgal e ali pequem à vontade! Todas as manhãs ofereçam sacrifícios  e de três em três dias deem os seus dízimos .

[[v30-4-5]]

^<<v30-4-5,5>>^ Apresentem os pães da oferta de gratidão a Deus e depois saiam para contar a todo mundo que fizeram ofertas de livre e espontânea vontade. E como vocês gostam de fazer isso!

[[v30-4-6]]

^<<v30-4-6,6>>^ — Eu fiz com que faltasse comida em todas as cidades e que todos passassem fome, mas assim mesmo vocês não voltaram para mim.

[[v30-4-7]]

^<<v30-4-7,7>>^ Não deixei que chovesse durante três meses antes das colheitas. Fiz com que caísse chuva numa cidade, mas, em outra, não; choveu numa plantação, mas, em outra, não, e nesta tudo secou.

[[v30-4-8]]

^<<v30-4-8,8>>^ As pessoas iam de cidade em cidade procurando água, mas não achavam o bastante nem para matar a sede. Assim mesmo vocês não voltaram para mim. Sou eu, o Senhor , quem está falando.

[[v30-4-9]]

^<<v30-4-9,9>>^ — Eu os castiguei com ventos muito quentes e com pragas nas plantas; os gafanhotos acabaram com as hortas, com as parreiras , com as figueiras e com as oliveiras. Assim mesmo vocês não voltaram para mim.

[[v30-4-10]]

^<<v30-4-10,10>>^ Fiz cair sobre vocês uma praga como as que mandei contra o Egito. Fiz com que os moços morressem nos campos de batalha e deixei que os inimigos levassem embora os cavalos de guerra. Fiz com que o mau cheiro dos corpos que estavam apodrecendo se espalhasse pelo acampamento. Assim mesmo vocês não voltaram para mim. Sou eu, o Senhor , quem está falando.

[[v30-4-11]]

^<<v30-4-11,11>>^ — Eu destruí cidades, como fiz com Sodoma e com Gomorra; vocês escaparam como se fossem um galho que no último momento é tirado do fogo. Assim mesmo vocês não voltaram para mim.

[[v30-4-12]]

^<<v30-4-12,12>>^ Por isso, povo de Israel, eu os castigarei. E, já que vou castigá-los, preparem-se para se encontrar com o seu Deus. Eu, o Senhor , falei.

[[v30-4-13]]

^<<v30-4-13,13>>^ Foi Deus quem fez as montanhas e criou o vento. Ele revela os seus planos aos seres humanos. Ele faz o dia virar noite e anda por cima das montanhas. Este é o seu nome: o Senhor , o Deus Todo-Poderoso.

'''

xref:030-amos/030-amos-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-amos/030-amos-005.adoc#v30-5-0[Próximo Capítulo &#62;]