include::./index.adoc[]

[[v66-1-0]]
=== Apocalipse, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-1-1]]

^<<v66-1-1,1>>^ Neste livro estão escritas as coisas que Jesus Cristo revelou. Deus lhe deu esta revelação para mostrar aos seus servos  o que precisa acontecer logo. Cristo enviou o seu anjo para que, por meio dele, o seu servo João soubesse dessas coisas.

[[v66-1-2]]

^<<v66-1-2,2>>^ João contou tudo o que viu, e aqui está o que ele contou a respeito da mensagem de Deus e da verdade revelada por Jesus Cristo.

[[v66-1-3]]

^<<v66-1-3,3>>^ Feliz quem lê este livro, e felizes aqueles que ouvem as palavras desta mensagem profética  e obedecem ao que está escrito neste livro! Pois está perto o tempo em que todas essas coisas acontecerão.

[[v66-1-4]]

^<<v66-1-4,4>>^ Eu, João, escrevo às sete igrejas que estão na província  da Ásia. Que a graça  e a paz lhes sejam dadas da parte de Deus, aquele que é, que era e que há de vir; da parte dos sete espíritos que estão diante do seu trono

[[v66-1-5]]

^<<v66-1-5,5>>^ e da parte de Jesus Cristo, a testemunha fiel! Ele é o primeiro Filho, que foi ressuscitado e que governa os reis do mundo inteiro. Ele nos ama, e pela sua morte na cruz nos livrou dos nossos pecados ,

[[v66-1-6]]

^<<v66-1-6,6>>^ e fez de nós um reino de sacerdotes a fim de servirmos ao seu Deus e Pai. A Jesus Cristo sejam dados a glória  e o poder para todo o sempre! Amém !

[[v66-1-7]]

^<<v66-1-7,7>>^ Olhem! Ele vem com as nuvens! Todos o verão, até mesmo os que o atravessaram com a lança. Todos os povos do mundo chorarão por causa dele. Certamente será assim. Amém !

[[v66-1-8]]

^<<v66-1-8,8>>^ Eu sou o Alfa e o Ômega ,  diz o Senhor Deus, o Todo-Poderoso, que é, que era e que há de vir.

[[v66-1-9]]

^<<v66-1-9,9>>^ Eu sou João, irmão de vocês; e, unido com Jesus, tomo parte com vocês no Reino  e também em aguentar o sofrimento com paciência. Eu estava na ilha de Patmos, para onde havia sido levado por ter anunciado a mensagem de Deus e a verdade que Jesus revelou.

[[v66-1-10]]

^<<v66-1-10,10>>^ No dia do Senhor fui dominado pelo Espírito de Deus e ouvi atrás de mim uma voz forte como o som de uma trombeta,

[[v66-1-11]]

^<<v66-1-11,11>>^ que me disse: — Escreva num livro o que você vai ver e mande esse livro às igrejas que estão nestas sete cidades: Éfeso, Esmirna, Pérgamo, Tiatira, Sardes, Filadélfia e Laodiceia.

[[v66-1-12]]

^<<v66-1-12,12>>^ Eu virei para ver quem falava comigo e vi sete candelabros  de ouro.

[[v66-1-13]]

^<<v66-1-13,13>>^ No meio deles estava um ser parecido com um homem, vestindo uma roupa que chegava até os pés e com uma faixa de ouro em volta do peito.

[[v66-1-14]]

^<<v66-1-14,14>>^ Os seus cabelos eram brancos como a lã ou como a neve, e os seus olhos eram brilhantes como o fogo.

[[v66-1-15]]

^<<v66-1-15,15>>^ Os seus pés brilhavam como o bronze refinado na fornalha e depois polido, e a sua voz parecia o barulho de uma grande cachoeira.

[[v66-1-16]]

^<<v66-1-16,16>>^ Na mão direita ele segurava sete estrelas, e da sua boca saía uma espada afiada dos dois lados. O seu rosto brilhava como o sol do meio-dia.

[[v66-1-17]]

^<<v66-1-17,17>>^ Quando eu o vi, caí aos seus pés, como morto. Porém ele pôs a mão direita sobre mim e disse: — Não tenha medo. Eu sou o Primeiro e o Último.

[[v66-1-18]]

^<<v66-1-18,18>>^ Eu sou aquele que vive. Estive morto, mas agora estou vivo para todo o sempre. Tenho autoridade sobre a morte e sobre o mundo dos mortos .

[[v66-1-19]]

^<<v66-1-19,19>>^ Portanto, escreva as coisas que você vai ver, tanto as que estão acontecendo agora como as que vão acontecer depois.

[[v66-1-20]]

^<<v66-1-20,20>>^ O sentido secreto das sete estrelas que você viu na minha mão direita e dos sete candelabros de ouro é este: as sete estrelas são os anjos das sete igrejas, e os sete candelabros são as sete igrejas.

'''

xref:065-judas/065-judas-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[Próximo Capítulo &#62;]