include::./index.adoc[]

[[v66-2-0]]
=== Apocalipse, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-2-1]]

^<<v66-2-1,1>>^ — Ao anjo da igreja de Éfeso escreva o seguinte: "Esta é a mensagem daquele que está segurando as sete estrelas na mão direita e que anda no meio dos sete candelabros  de ouro.

[[v66-2-2]]

^<<v66-2-2,2>>^ Eu sei o que vocês têm feito. Sei que trabalharam muito e aguentaram o sofrimento com paciência. Sei que vocês não podem suportar pessoas más e sei que puseram à prova os que dizem que são apóstolos , mas não são, e assim vocês descobriram que eles são mentirosos.

[[v66-2-3]]

^<<v66-2-3,3>>^ Vocês aguentaram a situação com paciência e sofreram por minha causa, sem desanimarem.

[[v66-2-4]]

^<<v66-2-4,4>>^ Porém tenho uma coisa contra vocês: é que agora vocês não me amam como me amavam no princípio.

[[v66-2-5]]

^<<v66-2-5,5>>^ Lembrem do quanto vocês caíram! Arrependam-se dos seus pecados e façam o que faziam no princípio. Se não se arrependerem, eu virei e tirarei o candelabro de vocês do seu lugar.

[[v66-2-6]]

^<<v66-2-6,6>>^ Mas vocês têm a seu favor isto: odeiam o que os nicolaítas fazem, como eu também odeio.

[[v66-2-7]]

^<<v66-2-7,7>>^ "Portanto, se vocês têm ouvidos para ouvir, então ouçam o que o Espírito de Deus diz às igrejas. "Aos que conseguirem a vitória eu darei o direito de comerem da fruta da árvore da vida, que cresce no jardim de Deus."

[[v66-2-8]]

^<<v66-2-8,8>>^ — Ao anjo da igreja de Esmirna escreva o seguinte: "Esta é a mensagem daquele que é o Primeiro e o Último, que morreu e tornou a viver.

[[v66-2-9]]

^<<v66-2-9,9>>^ Eu sei o que vocês estão sofrendo. Sei que são pobres, mas, de fato, são ricos. Sei como aqueles que afirmam que são judeus, mas não são , falam mal de vocês. Eles são um grupo que pertence a Satanás.

[[v66-2-10]]

^<<v66-2-10,10>>^ Não tenham medo do que vocês vão sofrer. Escutem! O Diabo vai pôr na prisão alguns de vocês para que sejam provados e sofram durante dez dias . Sejam fiéis, mesmo que tenham de morrer; e, como prêmio da vitória, eu lhes darei a vida.

[[v66-2-11]]

^<<v66-2-11,11>>^ "Portanto, se vocês têm ouvidos para ouvir, então ouçam o que o Espírito de Deus diz às igrejas. "Aqueles que conseguirem a vitória não sofrerão o castigo da segunda morte ."

[[v66-2-12]]

^<<v66-2-12,12>>^ — Ao anjo da igreja de Pérgamo escreva o seguinte: "Esta é a mensagem daquele que tem a espada afiada dos dois lados.

[[v66-2-13]]

^<<v66-2-13,13>>^ Eu sei que vocês moram aí onde está o trono de Satanás . Vocês são fiéis e não abandonaram a fé que têm em mim, até mesmo quando Antipas, minha testemunha fiel, foi morto aí em Pérgamo, onde Satanás mora.

[[v66-2-14]]

^<<v66-2-14,14>>^ Mas tenho algumas coisas contra vocês: há entre vocês alguns que seguem o ensinamento de Balaão, que mostrou a Balaque como fazer com que o povo de Israel pecasse, dizendo que os israelitas deviam comer alimentos oferecidos aos ídolos e cometer imoralidades.

[[v66-2-15]]

^<<v66-2-15,15>>^ Assim também estão entre vocês alguns que seguem os ensinamentos dos nicolaítas .

[[v66-2-16]]

^<<v66-2-16,16>>^ Arrependam-se! Se não, eu logo irei até aí e, com a espada que sai da minha boca, lutarei contra essa gente.

[[v66-2-17]]

^<<v66-2-17,17>>^ "Portanto, se vocês têm ouvidos para ouvir, então ouçam o que o Espírito de Deus diz às igrejas. "Aos que conseguirem a vitória eu darei do maná  escondido. E a cada um deles darei uma pedra branca, na qual está escrito um nome novo que ninguém conhece, a não ser quem o recebe."

[[v66-2-18]]

^<<v66-2-18,18>>^ — Ao anjo da igreja de Tiatira escreva o seguinte: "Esta é a mensagem do Filho de Deus, que tem olhos que brilham como o fogo e pés brilhantes como o bronze polido.

[[v66-2-19]]

^<<v66-2-19,19>>^ Eu sei o que vocês estão fazendo. Sei que têm amor, são fiéis, trabalham e aguentam o sofrimento com paciência. Eu sei que vocês estão fazendo mais agora do que no princípio.

[[v66-2-20]]

^<<v66-2-20,20>>^ Porém tenho contra vocês uma coisa: é que toleram Jezabel , aquela mulher que diz que é profetisa . Ela leva os meus servos  para o mau caminho, ensinando-os a cometer imoralidade sexual e a comerem alimentos que foram oferecidos aos ídolos.

[[v66-2-21]]

^<<v66-2-21,21>>^ Eu lhe dei tempo para abandonar os seus pecados, porém ela não quer deixar a imoralidade.

[[v66-2-22]]

^<<v66-2-22,22>>^ Portanto, eu a jogarei numa cama, onde ela e os que com ela cometem adultério sofrerão horrivelmente. Farei isso agora, a não ser que eles se arrependam das coisas más que fizeram junto com ela.

[[v66-2-23]]

^<<v66-2-23,23>>^ Matarei os seguidores dela, e então todas as igrejas saberão que eu sou aquele que conhece os pensamentos e os desejos de todos. Eu pagarei a cada um de vocês de acordo com o que tiver feito.

[[v66-2-24]]

^<<v66-2-24,24>>^ "Porém aí em Tiatira o resto de vocês não seguiu esse mau ensinamento. Vocês não aprenderam o que alguns chamam de ‘os segredos profundos de Satanás’ . Afirmo que não porei mais nenhuma carga sobre vocês.

[[v66-2-25]]

^<<v66-2-25,25>>^ Mas, até que eu venha, guardem bem aquilo que vocês têm.

[[v66-2-26]]

^<<v66-2-26,26>>^ "Aos que conseguirem a vitória e continuarem a fazer até o fim a minha vontade eu darei a mesma autoridade que recebi do meu Pai: autoridade sobre as nações para governá-las com uma barra de ferro e quebrá-las em pedaços como se fossem potes de barro. Eu lhes darei a estrela da manhã .

[[v66-2-27]]

^<<v66-2-27,27>>^ "Aos que conseguirem a vitória e continuarem a fazer até o fim a minha vontade eu darei a mesma autoridade que recebi do meu Pai: autoridade sobre as nações para governá-las com uma barra de ferro e quebrá-las em pedaços como se fossem potes de barro. Eu lhes darei a estrela da manhã .

'''

xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[&#60; Capítulo Anterior] | <<v66-2-0,Topo>> | xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[Próximo Capítulo &#62;]