include::./index.adoc[]

[[v66-22-0]]
=== Apocalipse, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-22-1]]

^<<v66-22-1,1>>^ O anjo também me mostrou o rio da água da vida, brilhante como cristal, que sai do trono de Deus e do Cordeiro

[[v66-22-2]]

^<<v66-22-2,2>>^ e que passa no meio da rua principal da cidade. Em cada lado do rio está a árvore da vida, que dá doze frutas por ano, isto é, uma por mês. E as suas folhas servem para curar as nações.

[[v66-22-3]]

^<<v66-22-3,3>>^ E não haverá na cidade nada que esteja debaixo da maldição de Deus. O trono de Deus e do Cordeiro estará na cidade, e os seus servos  o adorarão.

[[v66-22-4]]

^<<v66-22-4,4>>^ Verão o seu rosto, e na testa terão escrito o nome de Deus.

[[v66-22-5]]

^<<v66-22-5,5>>^ Ali não haverá mais noite, e não precisarão nem da luz de candelabros  nem da luz do sol, pois o Senhor Deus brilhará sobre eles. E reinarão para todo o sempre.

[[v66-22-6]]

^<<v66-22-6,6>>^ Então o anjo me disse: — Essas palavras são verdadeiras e merecem confiança. O Senhor Deus, que dá o seu Espírito aos profetas , enviou o seu anjo para mostrar aos seus servos  as coisas que precisam acontecer logo.

[[v66-22-7]]

^<<v66-22-7,7>>^ — Escutem!  — diz Jesus. — Eu venho logo! Felizes os que obedecem às palavras proféticas  deste livro!

[[v66-22-8]]

^<<v66-22-8,8>>^ Eu, João, ouvi e vi todas essas coisas. E, quando acabei de ouvir e ver, caí de joelhos aos pés do anjo que me mostrou essas coisas e ia adorá-lo.

[[v66-22-9]]

^<<v66-22-9,9>>^ Mas ele me disse: — Não faça isso! Pois eu sou servo de Deus, assim como são você e os seus irmãos, os profetas, e todas as pessoas que obedecem às palavras deste livro. Adore a Deus!

[[v66-22-10]]

^<<v66-22-10,10>>^ E o anjo continuou: — Não faça segredo das palavras proféticas deste livro, pois o tempo de acontecerem essas coisas está perto.

[[v66-22-11]]

^<<v66-22-11,11>>^ Quem é mau, que continue a fazer o mal, e quem é imundo, que continue a ser imundo. Quem é bom, que continue a fazer o bem, e quem é dedicado a Deus, que continue a ser dedicado a Deus.

[[v66-22-12]]

^<<v66-22-12,12>>^ — Escutem!  — diz Jesus. — Eu venho logo! Vou trazer comigo as minhas recompensas, para dá-las a cada um de acordo com o que tem feito.

[[v66-22-13]]

^<<v66-22-13,13>>^ Eu sou o Alfa e o Ômega , o Primeiro e o Último, o Princípio e o Fim.

[[v66-22-14]]

^<<v66-22-14,14>>^ Felizes as pessoas que lavam as suas roupas, pois assim terão o direito de comer a fruta da árvore da vida e de entrar na cidade pelos seus portões!

[[v66-22-15]]

^<<v66-22-15,15>>^ Mas fora da cidade estão os que cometem pecados nojentos, os feiticeiros, os imorais e os assassinos, os que adoram ídolos e os que gostam de mentir por palavras e ações.

[[v66-22-16]]

^<<v66-22-16,16>>^ — Eu, Jesus, enviei o meu anjo para anunciar essas coisas a vocês nas igrejas . Eu sou o famoso descendente do rei Davi. Sou a brilhante estrela da manhã.

[[v66-22-17]]

^<<v66-22-17,17>>^ O Espírito e a Noiva dizem: — Venha! Aquele que ouve isso diga também: — Venha! Aquele que tem sede venha. E quem quiser receba de graça da água da vida.

[[v66-22-18]]

^<<v66-22-18,18>>^ Eu, João, aviso solenemente aos que ouvem as palavras proféticas  deste livro: se alguma pessoa acrescentar a elas alguma coisa, Deus acrescentará ao castigo dela as pragas descritas neste livro.

[[v66-22-19]]

^<<v66-22-19,19>>^ E, se alguma pessoa tirar alguma coisa das palavras proféticas deste livro, Deus tirará dela as bênçãos descritas neste livro, isto é, a sua parte da fruta da árvore da vida e também a sua parte da Cidade Santa.

[[v66-22-20]]

^<<v66-22-20,20>>^ Aquele que dá testemunho de tudo isso diz: — Certamente venho logo! Amém ! Vem, Senhor Jesus!

[[v66-22-21]]

^<<v66-22-21,21>>^ E que a graça  do Senhor Jesus esteja com todos.

'''

xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[&#60; Capítulo Anterior] | <<v66-22-0,Topo>> | **Próximo Capítulo &#62;**