include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-17-1]]

^<<v66-17-1,1>>^ Então um dos sete anjos que tinham as sete taças veio me dizer: — Venha, e eu vou lhe mostrar como será castigada a famosa prostituta, aquela grande cidade que está construída perto de muitos rios.

[[v66-17-2]]

^<<v66-17-2,2>>^ Os reis do mundo inteiro cometeram imoralidade sexual com ela, e os povos do mundo ficaram bêbados com o vinho da sua imoralidade.

[[v66-17-3]]

^<<v66-17-3,3>>^ Então o Espírito de Deus me dominou, e o anjo me levou para um deserto, onde vi uma mulher montada num monstro vermelho. Havia muitas blasfêmias  escritas nele, e ele tinha sete cabeças e dez chifres.

[[v66-17-4]]

^<<v66-17-4,4>>^ A mulher usava um vestido cor de púrpura  e vermelho vivo e estava coberta de enfeites de ouro, de pedras preciosas e pérolas. Na mão ela segurava uma taça de ouro cheia de vinho, que representava as suas práticas indecentes e a imundícia da sua imoralidade.

[[v66-17-5]]

^<<v66-17-5,5>>^ Na sua testa estava escrito um nome que tem um significado secreto: "A grande Babilônia , mãe de todas as prostitutas e de todas as pessoas imorais do mundo."

[[v66-17-6]]

^<<v66-17-6,6>>^ Então vi que a mulher estava embriagada com o sangue do povo de Deus e das pessoas que haviam sido mortas porque tinham sido fiéis a Jesus. Quando a vi, fiquei muito espantado.

[[v66-17-7]]

^<<v66-17-7,7>>^ E o anjo me perguntou: — Por que é que você está assim, tão espantado? Vou lhe contar o significado secreto da mulher e do monstro que a carrega, o qual tem sete cabeças e dez chifres.

[[v66-17-8]]

^<<v66-17-8,8>>^ O monstro que você viu estava vivo, mas agora não vive mais. Ele está para subir do abismo , e dali sairá, e será destruído. Os moradores da terra que desde a criação do mundo não têm os seus nomes escritos no Livro da Vida ficarão espantados quando olharem para o monstro. Ele estava vivo; agora não vive mais, porém tornará a aparecer.

[[v66-17-9]]

^<<v66-17-9,9>>^ — Isto exige sabedoria e entendimento: as sete cabeças são sete montes onde a mulher está sentada. Elas também são sete reis:

[[v66-17-10]]

^<<v66-17-10,10>>^ Cinco já morreram, um está governando, e o outro ainda não apareceu. E, quando aparecer, precisará governar por pouco tempo.

[[v66-17-11]]

^<<v66-17-11,11>>^ E o monstro que já esteve vivo, mas que agora não vive mais, é o oitavo rei, que faz parte dos primeiros sete e que vai ser destruído.

[[v66-17-12]]

^<<v66-17-12,12>>^ — Os dez chifres que você viu são dez reis que ainda não começaram a governar, mas vão receber autoridade para reinar com o monstro durante uma hora .

[[v66-17-13]]

^<<v66-17-13,13>>^ Esses dez estão todos de acordo entre si e dão ao monstro o poder e a autoridade que possuem.

[[v66-17-14]]

^<<v66-17-14,14>>^ Eles lutarão contra o Cordeiro, e ele os vencerá porque é o Senhor dos senhores e o Rei dos reis. E com ele vencerão os seus seguidores, aqueles que são chamados  e fiéis.

[[v66-17-15]]

^<<v66-17-15,15>>^ Então o anjo também me disse: — As águas que você viu, onde a prostituta está sentada, são nações, povos, raças e línguas.

[[v66-17-16]]

^<<v66-17-16,16>>^ Os dez chifres que você viu e o monstro odiarão a prostituta. Eles tirarão tudo o que ela tem e a deixarão nua. Devorarão a sua carne e queimarão o resto no fogo.

[[v66-17-17]]

^<<v66-17-17,17>>^ Os dez reis farão isso porque Deus colocou no coração deles o desejo de fazerem o que ele quer. Assim entre si concordarão em entregar ao monstro a autoridade que eles têm para governar. Isso acontecerá até que se cumpram as palavras de Deus.

[[v66-17-18]]

^<<v66-17-18,18>>^ — A mulher que você viu é a grande cidade que domina os reis do mundo inteiro.

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]