include::./index.adoc[]

[[v66-5-0]]
=== Apocalipse, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-5-1]]

^<<v66-5-1,1>>^ Na mão direita daquele que estava sentado no trono eu vi um livro em forma de rolo. Estava escrito dos dois lados e selado  com sete selos .

[[v66-5-2]]

^<<v66-5-2,2>>^ Vi também um anjo forte, que perguntava bem alto: — Quem é digno de quebrar os selos e abrir o livro?

[[v66-5-3]]

^<<v66-5-3,3>>^ Mas não havia ninguém, nem no céu, nem na terra, nem debaixo da terra que pudesse abrir o livro e ver o que lá estava escrito.

[[v66-5-4]]

^<<v66-5-4,4>>^ Eu chorava muito porque não se podia achar ninguém que fosse digno de abrir o livro ou de ver o que lá estava escrito.

[[v66-5-5]]

^<<v66-5-5,5>>^ Então um dos líderes me disse: — Não chore. Olhe! O Leão da tribo  de Judá, o famoso descendente do rei Davi , conseguiu a vitória e pode quebrar os sete selos e abrir o livro.

[[v66-5-6]]

^<<v66-5-6,6>>^ Então vi um Cordeiro de pé no meio do trono, rodeado pelos quatro seres vivos e pelos líderes. Parecia que o Cordeiro havia sido oferecido em sacrifício . Ele tinha sete chifres e sete olhos, que são os sete espíritos de Deus que foram enviados ao mundo inteiro.

[[v66-5-7]]

^<<v66-5-7,7>>^ O Cordeiro foi e pegou o livro da mão direita daquele que estava sentado no trono.

[[v66-5-8]]

^<<v66-5-8,8>>^ Quando ele fez isso, os quatro seres vivos e os vinte e quatro líderes caíram de joelhos diante dele. Cada um tinha nas mãos uma harpa  e algumas taças de ouro cheias de incenso, que são as orações do povo de Deus.

[[v66-5-9]]

^<<v66-5-9,9>>^ Eles cantavam esta nova canção: "Tu és digno de pegar o livro e de quebrar os selos. Pois foste morto na cruz e, por meio da tua morte, compraste para Deus pessoas de todas as tribos, línguas, nações e raças.

[[v66-5-10]]

^<<v66-5-10,10>>^ Tu fizeste com que essas pessoas fossem um reino de sacerdotes que servem ao nosso Deus; e elas governarão o mundo inteiro."

[[v66-5-11]]

^<<v66-5-11,11>>^ Olhei outra vez e ouvi muitos anjos, milhões e milhões deles! Estavam de pé em volta do trono, dos quatro seres vivos e dos líderes

[[v66-5-12]]

^<<v66-5-12,12>>^ e cantavam com voz forte: "O Cordeiro que foi morto é digno de receber poder, riqueza, sabedoria e força, honra, glória  e louvor."

[[v66-5-13]]

^<<v66-5-13,13>>^ Então ouvi todas as criaturas que há no céu, na terra, debaixo da terra e no mar, isto é, todas as criaturas do Universo , que cantavam: "Ao que está sentado no trono e ao Cordeiro pertencem o louvor, a honra, a glória e o poder para todo o sempre!"

[[v66-5-14]]

^<<v66-5-14,14>>^ Os quatro seres respondiam: " Amém !" E os líderes caíram de joelhos e o adoraram.

'''

xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[Próximo Capítulo &#62;]