include::./index.adoc[]

[[v66-11-0]]
=== Apocalipse, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-11-1]]

^<<v66-11-1,1>>^ Depois disso recebi uma régua de medir, parecida com um caniço, e me disseram: — Levante-se, tire as medidas do Templo de Deus e do altar e conte as pessoas que estão adorando no Templo.

[[v66-11-2]]

^<<v66-11-2,2>>^ Porém não tire as medidas do pátio exterior do Templo, pois esse pátio foi dado aos pagãos, que pisarão a Cidade Santa durante quarenta e dois meses .

[[v66-11-3]]

^<<v66-11-3,3>>^ Eu enviarei as minhas duas testemunhas, vestidas com roupa feita de pano grosseiro, e elas anunciarão a mensagem de Deus durante mil duzentos e sessenta dias.

[[v66-11-4]]

^<<v66-11-4,4>>^ As duas testemunhas são as duas oliveiras e os dois candelabros  que estão em pé diante do Senhor do mundo inteiro.

[[v66-11-5]]

^<<v66-11-5,5>>^ Se os seus inimigos tentam maltratá-las, sai fogo da boca dessas duas testemunhas e acaba com eles. Assim, quem quiser maltratá-las precisa ser morto.

[[v66-11-6]]

^<<v66-11-6,6>>^ Elas têm autoridade para fechar o céu a fim de que não chova durante o tempo em que anunciam a mensagem de Deus. Têm autoridade também sobre as águas para que virem sangue. Têm autoridade ainda para ferir a terra com todo tipo de pragas, quantas vezes quiserem.

[[v66-11-7]]

^<<v66-11-7,7>>^ Quando as duas testemunhas acabarem de anunciar a sua mensagem, o monstro que vem do abismo  lutará contra elas. Ele vencerá e as matará,

[[v66-11-8]]

^<<v66-11-8,8>>^ e os seus corpos ficarão na rua principal da grande cidade onde o Senhor delas foi crucificado. O nome simbólico daquela cidade é Sodoma ou Egito.

[[v66-11-9]]

^<<v66-11-9,9>>^ Durante três dias e meio, os povos de todas as nações, tribos, línguas e raças olharão para esses dois corpos e não deixarão que sejam sepultados.

[[v66-11-10]]

^<<v66-11-10,10>>^ Os povos da terra ficarão felizes com a morte dessas duas testemunhas. Vão comemorar e mandar presentes uns aos outros porque esses dois profetas  trouxeram muito sofrimento para a humanidade.

[[v66-11-11]]

^<<v66-11-11,11>>^ Mas depois desses três dias e meio um sopro de vida veio de Deus e entrou neles, e eles se levantaram. E todas as pessoas que os viram ficaram com um medo terrível.

[[v66-11-12]]

^<<v66-11-12,12>>^ Aí os dois profetas ouviram uma voz forte, que vinha do céu e lhes dizia: — Subam aqui! Enquanto os seus inimigos olhavam, os dois profetas subiram ao céu numa nuvem.

[[v66-11-13]]

^<<v66-11-13,13>>^ Naquele momento houve um violento terremoto. A décima parte da cidade foi destruída, e morreram sete mil pessoas. As outras ficaram com muito medo e louvaram a grandeza do Deus do céu.

[[v66-11-14]]

^<<v66-11-14,14>>^ O segundo "ai" já passou. Mas olhem! O terceiro "ai" virá logo.

[[v66-11-15]]

^<<v66-11-15,15>>^ Então o sétimo anjo tocou a sua trombeta, e houve no céu vozes fortes, que diziam: — O poder para governar o mundo pertence agora a Deus, que é o Senhor nosso, e ao Messias  que ele escolheu. E Deus reinará para todo o sempre!

[[v66-11-16]]

^<<v66-11-16,16>>^ Aí os vinte e quatro líderes, que estavam sentados nos seus tronos diante de Deus, ajoelharam-se, encostaram o rosto no chão e adoraram a Deus,

[[v66-11-17]]

^<<v66-11-17,17>>^ dizendo: — Ó Senhor Deus, Todo-Poderoso, que és e que eras! Nós te damos graças porque tu tens usado o teu grande poder e começaste a reinar.

[[v66-11-18]]

^<<v66-11-18,18>>^ Os pagãos estão muito furiosos porque já chegou o momento de mostrares a tua ira e a hora de os mortos serem julgados. Chegou o momento de recompensares os teus servos , os profetas , e todo o teu povo, e todos os que te temem , tanto os importantes como os humildes. Chegou o momento de destruíres os que matam pessoas na terra!

[[v66-11-19]]

^<<v66-11-19,19>>^ Então se abriu o templo de Deus, que está no céu, e a arca da aliança  foi vista lá dentro. E houve relâmpagos, estrondos, trovões, um terremoto e uma forte chuva de pedra.

'''

xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[Próximo Capítulo &#62;]