include::./index.adoc[]

[[v66-6-0]]
=== Apocalipse, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-6-1]]

^<<v66-6-1,1>>^ Então vi o Cordeiro quebrar o primeiro dos sete selos  e ouvi um dos quatro seres vivos dizer com voz forte como o barulho de um trovão: — Venha!

[[v66-6-2]]

^<<v66-6-2,2>>^ Olhei e vi um cavalo branco. O seu cavaleiro tinha um arco, e lhe deram uma coroa de rei. E ele saiu vencendo e conquistando.

[[v66-6-3]]

^<<v66-6-3,3>>^ Depois o Cordeiro quebrou o segundo selo. E ouvi o segundo ser vivo dizer: — Venha!

[[v66-6-4]]

^<<v66-6-4,4>>^ Aí saiu outro cavalo, que era vermelho. O seu cavaleiro recebeu o poder de trazer a guerra ao mundo a fim de que as pessoas matassem umas às outras. E ele recebeu uma grande espada.

[[v66-6-5]]

^<<v66-6-5,5>>^ Então o Cordeiro quebrou o terceiro selo. E ouvi o terceiro ser vivo dizer: — Venha! Olhei e vi um cavalo preto. O seu cavaleiro tinha uma balança na mão.

[[v66-6-6]]

^<<v66-6-6,6>>^ Ouvi o que parecia ser uma voz, que vinha do meio dos quatro seres vivos e dizia: — Meio quilo de trigo custa o que vocês ganham num dia inteiro de trabalho; e um quilo e meio de cevada  custa a mesma coisa. E não misturem água no vinho, nem falsifiquem o azeite.

[[v66-6-7]]

^<<v66-6-7,7>>^ Depois o Cordeiro quebrou o quarto selo. E ouvi o quarto ser vivo dizer: — Venha!

[[v66-6-8]]

^<<v66-6-8,8>>^ Olhei e vi um cavalo amarelo. O seu cavaleiro se chamava Morte, e o mundo dos mortos  o seguia. Estes receberam poder sobre a quarta parte da terra, para matar por meio de guerras, fome, doenças e animais selvagens.

[[v66-6-9]]

^<<v66-6-9,9>>^ Então o Cordeiro quebrou o quinto selo. E vi debaixo do altar as almas dos que tinham sido mortos porque haviam anunciado a mensagem de Deus e tinham sido fiéis no seu testemunho.

[[v66-6-10]]

^<<v66-6-10,10>>^ Eles gritavam com voz bem forte: — Ó Todo-Poderoso, santo e verdadeiro! Quando julgarás e condenarás os que na terra nos mataram?

[[v66-6-11]]

^<<v66-6-11,11>>^ Cada um deles recebeu uma roupa branca. E foi dito a eles que descansassem um pouco mais, até que se completasse o número dos seus companheiros no trabalho de Cristo, que eram seus irmãos e que iam ser mortos como eles tinham sido.

[[v66-6-12]]

^<<v66-6-12,12>>^ Em seguida vi o Cordeiro quebrar o sexto selo. Houve um violento terremoto, o sol se tornou negro como uma roupa de luto, e a lua ficou toda vermelha como sangue.

[[v66-6-13]]

^<<v66-6-13,13>>^ As estrelas caíram do céu sobre a terra, como os figos verdes caem da figueira sacudida por um vento forte.

[[v66-6-14]]

^<<v66-6-14,14>>^ O céu desapareceu como um rolo de papel que se enrola de novo, e todos os montes e ilhas foram tirados dos seus lugares.

[[v66-6-15]]

^<<v66-6-15,15>>^ Então os reis do mundo inteiro, os governadores e os chefes militares, os ricos e os poderosos e todas as outras pessoas, escravas ou livres, se esconderam nas cavernas e debaixo das rochas das montanhas.

[[v66-6-16]]

^<<v66-6-16,16>>^ E gritavam para os montes e para as rochas: — Caiam sobre nós e nos escondam dos olhos daquele que está sentado no trono e nos protejam da ira  do Cordeiro!

[[v66-6-17]]

^<<v66-6-17,17>>^ Pois já chegou o grande dia da ira deles, e quem poderá aguentá-la?

'''

xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[&#60; Capítulo Anterior] | <<v66-6-0,Topo>> | xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[Próximo Capítulo &#62;]