include::./index.adoc[]

[[v66-16-0]]
=== Apocalipse, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-16-1]]

^<<v66-16-1,1>>^ Depois ouvi uma voz forte falando de dentro do templo, dizendo aos sete anjos: — Vão e derramem sobre a terra as sete taças da ira  de Deus!

[[v66-16-2]]

^<<v66-16-2,2>>^ O primeiro anjo foi e derramou a sua taça sobre a terra. Feridas abertas, terríveis e dolorosas, apareceram naqueles que tinham o sinal do monstro e que haviam adorado a sua imagem.

[[v66-16-3]]

^<<v66-16-3,3>>^ Aí o segundo anjo derramou a sua taça sobre o mar. A água ficou como o sangue de uma pessoa morta, e morreram todos os seres vivos do mar.

[[v66-16-4]]

^<<v66-16-4,4>>^ Então o terceiro anjo derramou a sua taça sobre os rios e nas fontes de água, e eles viraram sangue.

[[v66-16-5]]

^<<v66-16-5,5>>^ Eu ouvi o anjo que tinha autoridade sobre as águas dizer: — Tu és justo nos teus julgamentos, ó Deus santo, que és e que eras!

[[v66-16-6]]

^<<v66-16-6,6>>^ Os maus derramaram o sangue do povo de Deus e dos profetas , e por isso tu lhes deste sangue para beber. Eles estão recebendo o que merecem.

[[v66-16-7]]

^<<v66-16-7,7>>^ Aí ouvi uma voz que vinha do altar. A voz dizia: — Ó Senhor Deus, Todo-Poderoso! Os teus julgamentos são, de fato, verdadeiros e justos!

[[v66-16-8]]

^<<v66-16-8,8>>^ Depois o quarto anjo derramou a sua taça sobre o sol, e ele recebeu licença para queimar as pessoas com fogo.

[[v66-16-9]]

^<<v66-16-9,9>>^ Elas sofreram queimaduras dolorosas causadas por esse fogo e amaldiçoaram o nome de Deus, que tem autoridade sobre essas pragas. Mas não se arrependeram dos seus pecados, nem louvaram a glória  de Deus.

[[v66-16-10]]

^<<v66-16-10,10>>^ Então o quinto anjo derramou a sua taça sobre o trono do monstro, cujo reino ficou na escuridão, e as pessoas mordiam a língua de dor

[[v66-16-11]]

^<<v66-16-11,11>>^ e, por causa das suas dores e feridas, amaldiçoavam o Deus do céu. Porém não abandonaram as coisas más que faziam.

[[v66-16-12]]

^<<v66-16-12,12>>^ Em seguida o sexto anjo derramou a sua taça no grande rio Eufrates . O rio secou a fim de se abrir um caminho para os reis que vêm do Oriente.

[[v66-16-13]]

^<<v66-16-13,13>>^ Então vi três espíritos imundos que pareciam rãs, que saíam da boca do dragão, da boca do monstro e da boca do falso profeta .

[[v66-16-14]]

^<<v66-16-14,14>>^ Eles são os espíritos maus que fazem milagres. Esses três espíritos vão aos reis do mundo inteiro a fim de os ajuntar para a batalha do grande Dia de Deus, o Todo-Poderoso.

[[v66-16-15]]

^<<v66-16-15,15>>^ "Escutem! Eu venho como um ladrão. Feliz aquele que vigia e toma conta da sua roupa, a fim de não andar nu e não ficar envergonhado em público!"

[[v66-16-16]]

^<<v66-16-16,16>>^ Depois os espíritos ajuntaram os reis no lugar que em hebraico  é chamado de "Armagedom ".

[[v66-16-17]]

^<<v66-16-17,17>>^ E por último o sétimo anjo derramou a sua taça no ar. Então uma voz forte veio do trono, no templo, dizendo: — Está feito!

[[v66-16-18]]

^<<v66-16-18,18>>^ Houve relâmpagos, estrondos, trovões e um violento terremoto, tão violento como nunca houve igual desde a criação dos seres humanos. Foi o pior de todos!

[[v66-16-19]]

^<<v66-16-19,19>>^ A grande cidade se quebrou em três partes, e as cidades de todos os países foram destruídas. Deus lembrou da grande Babilônia e lhe deu o vinho da sua taça — o vinho do furor da sua ira .

[[v66-16-20]]

^<<v66-16-20,20>>^ Todas as ilhas desapareceram, e todos os montes sumiram.

[[v66-16-21]]

^<<v66-16-21,21>>^ Chuvas de pedra caíram do céu sobre as pessoas. Eram grandes pedras, que pesavam mais de trinta quilos. E as pessoas amaldiçoaram a Deus por causa da praga de chuvas de pedra, pois ela era terrível.

'''

xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[Próximo Capítulo &#62;]