include::./index.adoc[]

[[v66-9-0]]
=== Apocalipse, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-9-1]]

^<<v66-9-1,1>>^ Depois o quinto anjo tocou a sua trombeta, e eu vi uma estrela que tinha caído do céu na terra, e ela recebeu a chave do abismo .

[[v66-9-2]]

^<<v66-9-2,2>>^ A estrela abriu o poço do abismo, e dele saiu fumaça, como se fosse de uma grande fornalha. E o sol e o ar escureceram com a fumaça que saía do abismo.

[[v66-9-3]]

^<<v66-9-3,3>>^ De dentro da fumaça saíram gafanhotos, que desceram sobre a terra e receberam o mesmo poder que os escorpiões têm.

[[v66-9-4]]

^<<v66-9-4,4>>^ Foi dito aos gafanhotos que não fizessem estragos nas ervas, nem nas árvores, nem em qualquer outra planta; somente podiam ferir as pessoas que não tivessem a marca do sinete  de Deus na testa.

[[v66-9-5]]

^<<v66-9-5,5>>^ Os gafanhotos não tiveram permissão para matar essas pessoas; eles podiam apenas torturá-las durante cinco meses. A dor que causavam nessa tortura era como a dor da picada de um escorpião.

[[v66-9-6]]

^<<v66-9-6,6>>^ Naqueles cinco meses as pessoas procurarão a morte, mas não a encontrarão; vão querer morrer, mas a morte fugirá delas.

[[v66-9-7]]

^<<v66-9-7,7>>^ Os gafanhotos pareciam cavalos prontos para a batalha. Na cabeça tinham uma coisa parecida com uma coroa de ouro, e a cara deles era como o rosto de um ser humano.

[[v66-9-8]]

^<<v66-9-8,8>>^ Os seus cabelos eram como cabelos de mulher, e os dentes eram como dentes de leão.

[[v66-9-9]]

^<<v66-9-9,9>>^ As suas couraças  eram parecidas com couraças de ferro, e o barulho das suas asas era como o barulho de carros puxados por muitos cavalos quando correm para a batalha.

[[v66-9-10]]

^<<v66-9-10,10>>^ Os gafanhotos tinham rabos e ferrões como os de escorpiões, e era com os rabos que tinham o poder de ferir as pessoas por cinco meses.

[[v66-9-11]]

^<<v66-9-11,11>>^ Eles tinham um rei que os governava, que era o anjo que toma conta do abismo. O seu nome em hebraico  é Abadom e em grego  é Apolião (isso quer dizer "O Destruidor").

[[v66-9-12]]

^<<v66-9-12,12>>^ O primeiro "ai" já passou. Depois disso dois outros "ais" devem vir ainda.

[[v66-9-13]]

^<<v66-9-13,13>>^ Então o sexto anjo tocou a sua trombeta, e eu ouvi uma voz que vinha dos quatro cantos do altar de ouro que está diante de Deus.

[[v66-9-14]]

^<<v66-9-14,14>>^ E ao sexto anjo, que tinha nas mãos a trombeta, a voz disse: — Solte os quatro anjos que estão amarrados perto do grande rio Eufrates !

[[v66-9-15]]

^<<v66-9-15,15>>^ Os quatro anjos foram soltos. Eles estavam preparados para essa hora, dia, mês e ano a fim de matar a terça parte da humanidade.

[[v66-9-16]]

^<<v66-9-16,16>>^ E me foi dito que os soldados a cavalo eram duzentos milhões.

[[v66-9-17]]

^<<v66-9-17,17>>^ Na minha visão vi os cavalos e os seus cavaleiros. Os cavaleiros tinham no peito couraças  vermelhas como fogo, azuis como safira  e amarelas como enxofre. A cabeça dos cavalos era como cabeça de leão, e da boca deles saía fogo, fumaça e enxofre.

[[v66-9-18]]

^<<v66-9-18,18>>^ A terça parte da humanidade foi morta por estas três pragas: o fogo, a fumaça e o enxofre que saíam da boca dos cavalos.

[[v66-9-19]]

^<<v66-9-19,19>>^ Pois o poder dos cavalos está na boca deles e também no rabo. O rabo parecia uma cobra com a cabeça na ponta dele, e com ele os cavalos feriam o povo.

[[v66-9-20]]

^<<v66-9-20,20>>^ O resto da humanidade, isto é, todos os que não tinham sido mortos por essas pragas, não abandonou aquilo que eles haviam feito com as suas próprias mãos : eles não pararam de adorar os demônios e os ídolos de ouro, de prata, de bronze, de pedra e de madeira, que não podem ver, nem ouvir, nem andar.

[[v66-9-21]]

^<<v66-9-21,21>>^ Também não se arrependeram dos seus crimes de morte, nem das suas feitiçarias, nem da sua imoralidade sexual, nem dos seus roubos.

'''

xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[Próximo Capítulo &#62;]