include::./index.adoc[]

[[v66-21-0]]
=== Apocalipse, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-21-1]]

^<<v66-21-1,1>>^ Então vi um novo céu e uma nova terra. O primeiro céu e a primeira terra desapareceram, e o mar sumiu.

[[v66-21-2]]

^<<v66-21-2,2>>^ E vi a Cidade Santa, a nova Jerusalém, que descia do céu. Ela vinha de Deus, enfeitada e preparada, vestida como uma noiva que vai se encontrar com o noivo.

[[v66-21-3]]

^<<v66-21-3,3>>^ Ouvi uma voz forte que vinha do trono, a qual disse: — Agora a morada de Deus está entre os seres humanos! Deus vai morar com eles, e eles serão os povos dele. O próprio Deus estará com eles e será o Deus deles.

[[v66-21-4]]

^<<v66-21-4,4>>^ Ele enxugará dos olhos deles todas as lágrimas. Não haverá mais morte, nem tristeza, nem choro, nem dor. As coisas velhas já passaram.

[[v66-21-5]]

^<<v66-21-5,5>>^ Aquele que estava sentado no trono disse: — Agora faço novas todas as coisas! E também me disse: — Escreva isto, pois estas palavras são verdadeiras e merecem confiança.

[[v66-21-6]]

^<<v66-21-6,6>>^ E continuou: — Tudo está feito! Eu sou o Alfa e o Ômega , o Princípio e o Fim. A quem tem sede darei água para beber, de graça, da fonte da água da vida.

[[v66-21-7]]

^<<v66-21-7,7>>^ Aqueles que conseguirem a vitória receberão de mim este presente: eu serei o Deus deles, e eles serão meus filhos.

[[v66-21-8]]

^<<v66-21-8,8>>^ Mas os covardes, os traidores, os que cometem pecados nojentos, os assassinos, os imorais, os que praticam a feitiçaria, os que adoram ídolos e todos os mentirosos, o lugar dessas pessoas é o lago onde queima o fogo e o enxofre, que é a segunda morte.

[[v66-21-9]]

^<<v66-21-9,9>>^ Um dos sete anjos que tinham as sete taças cheias das últimas sete pragas veio e me disse: — Venha, e eu lhe mostrarei a Noiva, a Esposa do Cordeiro.

[[v66-21-10]]

^<<v66-21-10,10>>^ Então o Espírito de Deus me dominou, e o anjo me levou para uma montanha grande e muito alta. Ele me mostrou Jerusalém, a Cidade Santa, que descia do céu e vinha de Deus,

[[v66-21-11]]

^<<v66-21-11,11>>^ brilhando com a glória  de Deus. A cidade brilhava como uma pedra preciosa, como uma pedra de jaspe , clara como cristal.

[[v66-21-12]]

^<<v66-21-12,12>>^ Ela era cercada por uma muralha muito alta e grande, com doze portões, guardados por doze anjos. Nos portões estavam escritos os nomes das doze tribos  do povo de Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ Havia três portões de cada lado: três ao norte, três ao sul, três a leste e três a oeste.

[[v66-21-14]]

^<<v66-21-14,14>>^ A muralha da cidade estava construída sobre doze rochas, nas quais estavam escritos os nomes dos doze apóstolos  do Cordeiro.

[[v66-21-15]]

^<<v66-21-15,15>>^ O anjo que falou comigo levava consigo uma vara de ouro para medir a cidade, os seus portões e a muralha.

[[v66-21-16]]

^<<v66-21-16,16>>^ A cidade era quadrada, pois o seu comprimento era igual à sua largura. O anjo mediu a cidade com a vara de ouro e viu que media dois mil e duzentos quilômetros. O seu comprimento, largura e altura eram iguais.

[[v66-21-17]]

^<<v66-21-17,17>>^ O anjo mediu também a muralha e viu que tinha sessenta e quatro metros de largura, conforme as medidas comuns que o anjo estava usando.

[[v66-21-18]]

^<<v66-21-18,18>>^ A muralha era de jaspe, e a própria cidade era de ouro puro, claro como vidro.

[[v66-21-19]]

^<<v66-21-19,19>>^ As rochas do alicerce da muralha estavam enfeitadas de todo tipo de pedras preciosas. A primeira rocha estava enfeitada de jaspe; a segunda, de safira ; a terceira, de ágata ; a quarta, de esmeralda;

[[v66-21-20]]

^<<v66-21-20,20>>^ a quinta, de sardônica ; a sexta, de sárdio ; a sétima, de crisólito ; a oitava, de berilo ; a nona, de topázio ; a décima, de crisópraso ; a décima primeira, de jacinto ; e a décima segunda, de ametista .

[[v66-21-21]]

^<<v66-21-21,21>>^ Os doze portões são doze pérolas. E cada um desses portões era feito de uma só pérola. A rua principal era de ouro puro, claro como vidro.

[[v66-21-22]]

^<<v66-21-22,22>>^ Não vi nenhum templo na cidade, pois o seu templo é o Senhor Deus, o Todo-Poderoso, e o Cordeiro.

[[v66-21-23]]

^<<v66-21-23,23>>^ A cidade não precisa de sol nem de lua para a iluminarem, pois a glória de Deus brilha sobre ela, e o Cordeiro é o seu candelabro .

[[v66-21-24]]

^<<v66-21-24,24>>^ Os povos do mundo andarão na luz dela, e os reis da terra vão lhe trazer as suas riquezas.

[[v66-21-25]]

^<<v66-21-25,25>>^ Os portões da cidade estarão sempre abertos o dia inteiro. Não se fecharão porque ali não haverá noite.

[[v66-21-26]]

^<<v66-21-26,26>>^ As nações vão trazer os seus tesouros e as suas riquezas para a cidade.

[[v66-21-27]]

^<<v66-21-27,27>>^ Porém nela não entrará nada que seja impuro  nem ninguém que faça coisas vergonhosas ou que conte mentiras. Entrarão na cidade somente as pessoas que têm o seu nome escrito no Livro da Vida , o qual pertence ao Cordeiro.

'''

xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-apocalipse/066-apocalipse-022.adoc#v66-22-0[Próximo Capítulo &#62;]