include::./index.adoc[]

[[v66-18-0]]
=== Apocalipse, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-18-1]]

^<<v66-18-1,1>>^ Depois disso vi outro anjo descendo do céu. Ele tinha um grande poder, e o seu brilho iluminava toda a terra.

[[v66-18-2]]

^<<v66-18-2,2>>^ E gritava com voz forte: — Caiu! Caiu a grande Babilônia ! Agora quem vive ali são os demônios e todos os espíritos imundos. Todos os tipos de aves e feras imundas e nojentas vivem nela.

[[v66-18-3]]

^<<v66-18-3,3>>^ Pois todas as nações beberam do seu vinho, o vinho forte do seu desejo imoral. Os reis do mundo inteiro cometeram imoralidade sexual com ela, e os homens de negócio deste mundo se enriqueceram à custa das práticas sexuais sujas da prostituta.

[[v66-18-4]]

^<<v66-18-4,4>>^ Então ouvi outra voz do céu, que disse: — Saia dessa cidade, meu povo! Saiam todos dela para não tomarem parte nos seus pecados e para não participarem dos seus castigos!

[[v66-18-5]]

^<<v66-18-5,5>>^ Pois os seus pecados estão amontoados até o céu, e Deus lembra das suas maldades.

[[v66-18-6]]

^<<v66-18-6,6>>^ Deem a ela o mesmo que ela deu a vocês; paguem em dobro o que ela fez. Encham a taça dela com bebida duas vezes mais forte do que a bebida que ela preparou para vocês.

[[v66-18-7]]

^<<v66-18-7,7>>^ Deem a ela tanto sofrimento e tristeza quanto luxo e glória ela deu a si mesma. Porque ela pensa assim: "Estou sentada aqui como rainha! Não sou viúva e nunca mais vou sofrer!"

[[v66-18-8]]

^<<v66-18-8,8>>^ Por isso num mesmo dia cairão sobre ela estas pragas: doenças, dor e fome, e ela será queimada no fogo. Pois o Senhor Deus, que a julga, é poderoso.

[[v66-18-9]]

^<<v66-18-9,9>>^ Os reis do mundo inteiro que tomaram parte na imoralidade e na corrupção dela vão gritar e chorar quando virem a fumaça do seu incêndio.

[[v66-18-10]]

^<<v66-18-10,10>>^ Eles ficam de longe porque têm medo de tomar parte no castigo que ela vai sofrer e dizem: — Ai de você! Ai de você, Babilônia, grande e poderosa cidade! Em apenas uma hora você já foi castigada!

[[v66-18-11]]

^<<v66-18-11,11>>^ Os comerciantes do mundo inteiro também gritam e se lamentam por causa dela porque ninguém mais compra os produtos deles.

[[v66-18-12]]

^<<v66-18-12,12>>^ Ninguém compra o seu ouro, prata, pedras preciosas e pérolas; nem o seu linho finíssimo, a sua púrpura , a sua seda e a sua lã vermelha; nem qualquer espécie de madeira rara ou qualquer tipo de objetos feitos de marfim e de madeira cara, de bronze, ferro e mármore;

[[v66-18-13]]

^<<v66-18-13,13>>^ nem canela, cardamomo , incenso, mirra  ou perfumes. Ninguém compra o seu vinho, azeite, farinha de trigo e trigo em grão; nem gado e ovelhas, cavalos e carruagens, nem escravos ou outros seres humanos.

[[v66-18-14]]

^<<v66-18-14,14>>^ Os comerciantes dizem à cidade: — Acabaram todas aquelas coisas boas que você tanto desejava, e você perdeu para sempre toda a riqueza e toda a fama que possuía e não as encontrará mais.

[[v66-18-15]]

^<<v66-18-15,15>>^ E os comerciantes, que se tornaram ricos negociando naquela cidade, ficarão de longe, com medo de serem castigados junto com ela. Eles vão gritar e lamentar assim:

[[v66-18-16]]

^<<v66-18-16,16>>^ — Ai da grande cidade! Ai da cidade que estava vestida de linho finíssimo, de púrpura e de lã vermelha e que se enfeitava com joias de ouro, com pedras preciosas e com pérolas!

[[v66-18-17]]

^<<v66-18-17,17>>^ Em somente uma hora ela perdeu toda a sua riqueza! Todos os capitães de navios e todos os passageiros, marinheiros e outros que ganham a vida no mar ficaram de longe.

[[v66-18-18]]

^<<v66-18-18,18>>^ Então, vendo a fumaça do incêndio da cidade, gritaram: — Nunca houve uma cidade igual a esta grande cidade!

[[v66-18-19]]

^<<v66-18-19,19>>^ Em sinal de tristeza eles jogaram pó sobre a cabeça, choraram e gritaram assim: — Ai da grande cidade! Ai da cidade onde, à custa da sua grande riqueza, se enriqueceram todos os que tinham navios no mar! E em apenas uma hora ela perdeu tudo!

[[v66-18-20]]

^<<v66-18-20,20>>^ Alegrem-se, ó céus, por causa da destruição dessa cidade! Alegrem-se, povo de Deus, apóstolos  e profetas ! Pois Deus a condenou pelo que ela fez a vocês!

[[v66-18-21]]

^<<v66-18-21,21>>^ Então um anjo forte levantou uma pedra do tamanho de uma grande pedra de moinho e a jogou no mar. E disse: — É assim que a grande cidade de Babilônia será jogada fora com violência e nunca mais será vista.

[[v66-18-22]]

^<<v66-18-22,22>>^ A música dos tocadores de harpa , de flauta e de trombeta e as vozes dos cantores nunca mais serão ouvidas em você, e em você nunca mais será encontrado nenhum trabalhador de qualquer ofício, e nunca mais se ouvirá em você o barulho das pedras de moinho!

[[v66-18-23]]

^<<v66-18-23,23>>^ Em você jamais brilhará a luz de uma lamparina, e nunca mais se ouvirá em você a voz dos noivos e das noivas. Os seus comerciantes foram os mais poderosos do mundo, e com feitiçaria você enganou todos os povos da terra.

[[v66-18-24]]

^<<v66-18-24,24>>^ A grande Babilônia foi castigada porque nela foi encontrado o sangue dos profetas, o sangue do povo de Deus e o de todos os que foram assassinados na terra.

'''

xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[Próximo Capítulo &#62;]