include::./index.adoc[]

[[v66-19-0]]
=== Apocalipse, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-19-1]]

^<<v66-19-1,1>>^ Depois disso ouvi no céu uma voz forte como se fosse a de uma grande multidão, que dizia: — Aleluia ! A salvação, a glória  e o poder pertencem ao nosso Deus!

[[v66-19-2]]

^<<v66-19-2,2>>^ Os seus julgamentos são verdadeiros e justos. Ele condenou a famosa prostituta que corrompia a terra com a sua imoralidade. Deus a castigou porque ela havia matado os servos  dele.

[[v66-19-3]]

^<<v66-19-3,3>>^ E a multidão disse outra vez: — Aleluia! A fumaça do incêndio da grande cidade sobe para todo o sempre.

[[v66-19-4]]

^<<v66-19-4,4>>^ Então os vinte e quatro líderes e os quatro seres vivos caíram de joelhos e adoraram a Deus, que estava sentado no trono, e disseram: — Amém ! Aleluia!

[[v66-19-5]]

^<<v66-19-5,5>>^ Então veio do trono o som de uma voz, que dizia: — Louvem o nosso Deus, todos os seus servos , todos os que o temem , tanto as pessoas importantes como as humildes!

[[v66-19-6]]

^<<v66-19-6,6>>^ Aí ouvi um som que parecia a voz de uma grande multidão, como o barulho de uma grande cachoeira ou como fortes trovões, que dizia: — Aleluia ! Pois o Senhor, nosso Deus, o Todo-Poderoso, é Rei!

[[v66-19-7]]

^<<v66-19-7,7>>^ Fiquemos alegres e felizes! Louvemos a sua glória ! Porque chegou a hora da festa de casamento do Cordeiro, e a noiva já se preparou para recebê-lo.

[[v66-19-8]]

^<<v66-19-8,8>>^ A ela foi dado linho finíssimo, linho brilhante e puro para se vestir. O linho são as boas ações do povo de Deus.

[[v66-19-9]]

^<<v66-19-9,9>>^ Então o anjo me disse: — Escreva isto: "Felizes os que foram convidados para a festa de casamento do Cordeiro!" E o anjo disse ainda: — São essas as verdadeiras palavras de Deus.

[[v66-19-10]]

^<<v66-19-10,10>>^ Aí eu me ajoelhei aos pés do anjo para adorá-lo, mas ele me disse: — Não faça isso! Pois eu sou servo de Deus, assim como são você e os seus irmãos que continuam fiéis à verdade revelada por Jesus. Adore a Deus! Pois a verdade revelada por Jesus é a mensagem que o Espírito entrega aos profetas .

[[v66-19-11]]

^<<v66-19-11,11>>^ Em seguida vi o céu aberto, e apareceu um cavalo branco. O seu cavaleiro se chama Fiel e Verdadeiro. Ele julga e combate com justiça.

[[v66-19-12]]

^<<v66-19-12,12>>^ Os seus olhos eram como chamas de fogo, e ele tinha muitas coroas na cabeça. Havia escrito nele um nome que ninguém conhece, a não ser ele mesmo.

[[v66-19-13]]

^<<v66-19-13,13>>^ A sua capa  estava encharcada de sangue. Ele se chama "A Palavra de Deus".

[[v66-19-14]]

^<<v66-19-14,14>>^ Os exércitos do céu o seguiam, montados em cavalos brancos e vestidos de linho branco e puro.

[[v66-19-15]]

^<<v66-19-15,15>>^ Da sua boca saía uma espada afiada, com a qual ele vencerá as nações. Ele as governará com uma barra de ferro e pisará as uvas no tanque do furor da ira  do Deus Todo-Poderoso.

[[v66-19-16]]

^<<v66-19-16,16>>^ Na capa e na perna dele estava escrito este nome: "Rei dos reis e Senhor dos senhores."

[[v66-19-17]]

^<<v66-19-17,17>>^ Então vi um anjo que estava de pé sobre o sol. Ele gritou com voz forte, dizendo o seguinte para todas as aves que estavam voando bem alto: — Venham e se ajuntem para o grande banquete de Deus!

[[v66-19-18]]

^<<v66-19-18,18>>^ Venham e comam a carne de reis, de generais e de soldados, de cavalos e de cavaleiros e de todas as pessoas, sejam escravas ou livres, sejam importantes ou humildes.

[[v66-19-19]]

^<<v66-19-19,19>>^ Depois vi o monstro e os reis do mundo inteiro e os seus exércitos reunidos para lutar contra aquele que estava montado no cavalo e contra o seu exército.

[[v66-19-20]]

^<<v66-19-20,20>>^ O monstro foi feito prisioneiro junto com o falso profeta , que havia feito coisas espantosas na sua presença. Com aquelas coisas ele havia enganado os que tinham o sinal do monstro e os que haviam adorado a imagem do monstro. O monstro e o falso profeta foram jogados vivos no lago de fogo que queima com enxofre .

[[v66-19-21]]

^<<v66-19-21,21>>^ Os seus exércitos foram mortos pela espada que saía da boca daquele que estava montado no cavalo branco. E todas as aves comeram da carne deles até não quererem mais.

'''

xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[&#60; Capítulo Anterior] | <<v66-19-0,Topo>> | xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[Próximo Capítulo &#62;]