include::./index.adoc[]

[[v66-7-0]]
=== Apocalipse, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-7-1]]

^<<v66-7-1,1>>^ Depois disso vi nos quatro cantos do mundo quatro anjos em pé. Eles estavam segurando os quatro ventos da terra a fim de que nenhum vento soprasse sobre ela, nem sobre o mar, nem sobre nenhuma árvore.

[[v66-7-2]]

^<<v66-7-2,2>>^ Então vi outro anjo, que subia do lado leste e que tinha na mão o sinete  do Deus vivo. Ele gritou com voz bem forte para os quatro anjos que tinham recebido o poder de fazer estragos na terra e no mar.

[[v66-7-3]]

^<<v66-7-3,3>>^ O anjo disse: — Não façam estragos na terra, nem no mar, nem nas árvores, até que marquemos com o sinete a testa dos servos  do nosso Deus.

[[v66-7-4]]

^<<v66-7-4,4>>^ Aí me foi dito o número dos que foram marcados: eram cento e quarenta e quatro mil. Eles pertenciam a todas as tribos  do povo de Israel,

[[v66-7-5]]

^<<v66-7-5,5>>^ doze mil de cada tribo: de Judá, Rúben, Gade, Aser, Naftali, Manassés, Simeão, Levi, Issacar, Zebulom, José e Benjamim.

[[v66-7-6]]

^<<v66-7-6,6>>^ doze mil de cada tribo: de Judá, Rúben, Gade, Aser, Naftali, Manassés, Simeão, Levi, Issacar, Zebulom, José e Benjamim.

[[v66-7-7]]

^<<v66-7-7,7>>^ doze mil de cada tribo: de Judá, Rúben, Gade, Aser, Naftali, Manassés, Simeão, Levi, Issacar, Zebulom, José e Benjamim.

[[v66-7-8]]

^<<v66-7-8,8>>^ doze mil de cada tribo: de Judá, Rúben, Gade, Aser, Naftali, Manassés, Simeão, Levi, Issacar, Zebulom, José e Benjamim.

[[v66-7-9]]

^<<v66-7-9,9>>^ Depois disso olhei e vi uma multidão tão grande, que ninguém podia contar. Eram de todas as nações, tribos , raças e línguas. Estavam de pé diante do trono e do Cordeiro, vestidos de roupas brancas, e tinham folhas de palmeira nas mãos.

[[v66-7-10]]

^<<v66-7-10,10>>^ E gritavam bem alto: — Do nosso Deus, que está sentado no trono, e do Cordeiro vem a nossa salvação.

[[v66-7-11]]

^<<v66-7-11,11>>^ Todos os anjos estavam de pé em volta do trono, dos líderes e dos quatro seres vivos. Então eles se jogaram diante do trono, encostaram o rosto no chão e adoraram a Deus,

[[v66-7-12]]

^<<v66-7-12,12>>^ dizendo: — Amém ! Ao nosso Deus pertencem para todo o sempre o louvor, a glória , a sabedoria, a gratidão, a honra, o poder e a força! Amém!

[[v66-7-13]]

^<<v66-7-13,13>>^ Um dos líderes me perguntou: — Quem são estes que estão vestidos de branco? De onde foi que vieram?

[[v66-7-14]]

^<<v66-7-14,14>>^ — Eu não sei. O senhor sabe! — respondi. Então ele me disse: — Estes são os que atravessaram sãos e salvos a grande perseguição. São as pessoas que lavaram as suas roupas no sangue do Cordeiro, e elas ficaram brancas.

'''

xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[&#60; Capítulo Anterior] | <<v66-7-0,Topo>> | xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[Próximo Capítulo &#62;]