include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-12-1]]

^<<v66-12-1,1>>^ Então apareceu no céu um grande e misterioso sinal. Era uma mulher. O seu vestido era o sol, debaixo dos seus pés estava a lua, e ela usava na cabeça uma coroa que tinha doze estrelas.

[[v66-12-2]]

^<<v66-12-2,2>>^ A mulher estava grávida e gritava com dores de parto.

[[v66-12-3]]

^<<v66-12-3,3>>^ E apareceu no céu outro sinal: era um enorme dragão vermelho com sete cabeças e dez chifres e com uma coroa em cada cabeça.

[[v66-12-4]]

^<<v66-12-4,4>>^ Com a cauda ele arrastou do céu a terça parte das estrelas e as jogou sobre a terra. Depois parou diante da mulher grávida a fim de comer a criança logo que ela nascesse.

[[v66-12-5]]

^<<v66-12-5,5>>^ Então a mulher deu à luz um filho, que governará todas as nações com uma barra de ferro. Mas a criança foi tirada e levada para perto de Deus e do seu trono.

[[v66-12-6]]

^<<v66-12-6,6>>^ A mulher fugiu para o deserto, onde Deus havia preparado um lugar para ela. Ali ela será sustentada durante mil duzentos e sessenta dias.

[[v66-12-7]]

^<<v66-12-7,7>>^ Depois houve guerra no céu. Miguel e os seus anjos lutaram contra o dragão, que combateu junto com os seus anjos.

[[v66-12-8]]

^<<v66-12-8,8>>^ Mas o dragão foi vencido, e por isso ele e os seus anjos não puderam mais ficar no céu.

[[v66-12-9]]

^<<v66-12-9,9>>^ O enorme dragão foi lançado fora do céu. Ele é aquela velha cobra, chamada Diabo ou Satanás, que leva todas as pessoas do mundo a pecar. Ele foi jogado sobre a terra, e os seus anjos também foram jogados junto com ele.

[[v66-12-10]]

^<<v66-12-10,10>>^ Então ouvi uma voz forte no céu, que dizia: — Agora chegou a salvação de Deus! Agora Deus mostrou o seu poder como rei! Agora o Messias  que ele escolheu mostrou a sua autoridade! Pois o acusador dos nossos irmãos, que estava diante de Deus para acusá-los dia e noite, foi jogado fora do céu.

[[v66-12-11]]

^<<v66-12-11,11>>^ Os nossos irmãos o derrotaram por meio do sangue do Cordeiro e da mensagem que anunciaram. Eles estavam prontos para dar a sua vida e morrer.

[[v66-12-12]]

^<<v66-12-12,12>>^ Portanto, ó céu e todos vocês que vivem nele, alegrem-se! Mas ai da terra e do mar! Pois o Diabo desceu até vocês e ele está muito furioso porque sabe que tem somente um pouco mais de tempo para agir.

[[v66-12-13]]

^<<v66-12-13,13>>^ Quando o dragão viu que tinha sido jogado sobre a terra, começou a perseguir a mulher que tinha dado à luz o menino.

[[v66-12-14]]

^<<v66-12-14,14>>^ Porém a mulher recebeu as duas asas de uma grande águia para poder voar para o seu lugar no deserto, onde ela será sustentada durante três anos e meio , livre do ataque do dragão.

[[v66-12-15]]

^<<v66-12-15,15>>^ Então o dragão lançou água da sua boca, como se fosse um rio, atrás da mulher, para que ela fosse arrastada pelas águas.

[[v66-12-16]]

^<<v66-12-16,16>>^ Mas a terra ajudou a mulher, pois a própria terra abriu a boca e engoliu a água que tinha saído da boca do dragão.

[[v66-12-17]]

^<<v66-12-17,17>>^ O dragão ficou furioso com a mulher e foi combater contra o resto dos descendentes dela, isto é, aqueles que obedecem aos mandamentos de Deus e são fiéis à verdade revelada por Jesus.

[[v66-12-18]]

^<<v66-12-18,18>>^ E o dragão ficou de pé na praia.

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]