include::./index.adoc[]

[[v66-4-0]]
=== Apocalipse, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-4-1]]

^<<v66-4-1,1>>^ Depois disso, tive outra visão e vi uma porta aberta no céu. E a voz que parecia o som de uma trombeta e que antes havia falado comigo disse: — Suba aqui, e eu mostrarei a você o que precisa acontecer depois disso.

[[v66-4-2]]

^<<v66-4-2,2>>^ Num instante fui dominado pelo Espírito de Deus. E ali no céu estava um trono com alguém sentado nele.

[[v66-4-3]]

^<<v66-4-3,3>>^ O seu rosto brilhava como brilham as pedras de jaspe  e sárdio , e em volta do trono havia um arco-íris que brilhava como uma esmeralda.

[[v66-4-4]]

^<<v66-4-4,4>>^ Ao redor do trono havia outros vinte e quatro tronos, nos quais estavam sentados vinte e quatro líderes , vestidos de branco e com coroas de ouro na cabeça.

[[v66-4-5]]

^<<v66-4-5,5>>^ Do trono saíam relâmpagos, estrondos e trovões. Diante dele havia sete tochas acesas, que são os sete espíritos de Deus.

[[v66-4-6]]

^<<v66-4-6,6>>^ E em frente do trono havia uma coisa parecida com um mar de vidro, claro como cristal. Em volta do trono, em cada um dos seus lados, estavam quatro seres vivos, cobertos de olhos, na frente e atrás.

[[v66-4-7]]

^<<v66-4-7,7>>^ O primeiro desses seres parecia um leão. O segundo parecia um touro. O terceiro tinha a cara parecida com a de um ser humano. E o quarto parecia uma águia voando.

[[v66-4-8]]

^<<v66-4-8,8>>^ Cada um desses quatro seres vivos tinha seis asas, que estavam cobertas de olhos nos dois lados. E dia e noite não paravam de cantar assim: "Santo, santo, santo é o Senhor Deus, o Todo-Poderoso, que era, que é e que há de vir."

[[v66-4-9]]

^<<v66-4-9,9>>^ Cada vez que os quatro seres vivos cantavam hinos de glória , honra e agradecimento ao que está sentado no trono e que vive para todo o sempre,

[[v66-4-10]]

^<<v66-4-10,10>>^ os vinte e quatro líderes caíam de joelhos diante dele e o adoravam. Atiravam as suas coroas diante do trono e diziam:

[[v66-4-11]]

^<<v66-4-11,11>>^ "Senhor nosso e nosso Deus! Tu és digno de receber glória, honra e poder, pois criaste todas as coisas; por tua vontade elas foram criadas e existem."

'''

xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[Próximo Capítulo &#62;]