include::./index.adoc[]

[[v66-10-0]]
=== Apocalipse, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-10-1]]

^<<v66-10-1,1>>^ Então vi outro anjo forte, que estava descendo do céu. A sua roupa era uma nuvem, e ele tinha um arco-íris na cabeça. O seu rosto era como o sol, e as pernas eram como colunas de fogo.

[[v66-10-2]]

^<<v66-10-2,2>>^ O anjo tinha um livrinho aberto na mão. Ele pôs o pé direito sobre o mar e o esquerdo, sobre a terra

[[v66-10-3]]

^<<v66-10-3,3>>^ e gritou com voz muito forte, que parecia o rugido de leões. Depois que gritou, os sete trovões responderam com um estrondo.

[[v66-10-4]]

^<<v66-10-4,4>>^ No momento em que eles falaram, eu ia escrever, mas ouvi uma voz do céu que dizia: — Guarde em segredo o que os sete trovões disseram. Não escreva nada.

[[v66-10-5]]

^<<v66-10-5,5>>^ Depois o anjo que vi em pé sobre o mar e sobre a terra levantou a mão direita para o céu

[[v66-10-6]]

^<<v66-10-6,6>>^ e fez um juramento em nome de Deus, que vive para todo o sempre, que criou o céu, a terra, o mar e tudo o que existe neles. O juramento foi este: — Não vai demorar mais.

[[v66-10-7]]

^<<v66-10-7,7>>^ Quando o sétimo anjo tocar a trombeta, Deus cumprirá o seu plano secreto, como anunciou aos seus servos , os profetas .

[[v66-10-8]]

^<<v66-10-8,8>>^ Então a voz do céu que eu tinha ouvido falou outra vez comigo, dizendo: — Vá até o anjo que está em pé sobre o mar e sobre a terra e pegue o livro aberto que ele tem na mão.

[[v66-10-9]]

^<<v66-10-9,9>>^ Eu fui e pedi ao anjo o livrinho, e ele me disse: — Pegue o livrinho e coma-o. No seu estômago ele ficará azedo, mas na sua boca será doce como mel.

[[v66-10-10]]

^<<v66-10-10,10>>^ Aí peguei o livrinho da mão do anjo e o comi, e na minha boca ele era doce como mel. Mas, depois que o engoli, o meu estômago ficou azedo.

[[v66-10-11]]

^<<v66-10-11,11>>^ Então me disseram: — Você precisa anunciar outra vez a mensagem de Deus a respeito de muitas nações, raças, línguas e reis.

'''

xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[&#60; Capítulo Anterior] | <<v66-10-0,Topo>> | xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[Próximo Capítulo &#62;]