include::./index.adoc[]

[[v66-13-0]]
=== Apocalipse, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-13-1]]

^<<v66-13-1,1>>^ Depois vi um monstro que subia do mar. Ele tinha dez chifres e sete cabeças, uma coroa em cada um dos chifres e nomes, que eram blasfêmias , escritos nas cabeças.

[[v66-13-2]]

^<<v66-13-2,2>>^ O monstro que vi parecia um leopardo; os seus pés eram como os de um urso, e a sua boca era como a de um leão. E ao monstro o dragão deu o seu poder, o seu trono e grande autoridade.

[[v66-13-3]]

^<<v66-13-3,3>>^ Uma das cabeças do monstro parecia que tinha recebido um golpe mortal, mas a ferida havia sarado. O mundo inteiro ficou admirado e seguiu o monstro.

[[v66-13-4]]

^<<v66-13-4,4>>^ Todos adoravam o dragão porque ele tinha dado a sua autoridade ao monstro. Eles adoravam também o monstro, dizendo: — Quem é tão forte como o monstro? Quem pode lutar contra ele?

[[v66-13-5]]

^<<v66-13-5,5>>^ Foi permitido ao monstro se gabar da sua autoridade e dizer blasfêmias contra Deus. E ele recebeu autoridade para agir durante quarenta e dois meses .

[[v66-13-6]]

^<<v66-13-6,6>>^ Ele começou a blasfemar contra Deus, contra o seu nome, contra o lugar onde ele mora e contra todos os que vivem no céu.

[[v66-13-7]]

^<<v66-13-7,7>>^ Foi permitido que ele lutasse contra o povo de Deus e o vencesse. E também recebeu autoridade sobre todas as tribos, nações, línguas e raças.

[[v66-13-8]]

^<<v66-13-8,8>>^ Todos os que vivem na terra o adorarão, menos aqueles que, desde antes da criação do mundo, têm o nome escrito no Livro da Vida , o qual pertence ao Cordeiro, que foi morto.

[[v66-13-9]]

^<<v66-13-9,9>>^ Portanto, se vocês quiserem ouvir, escutem bem isto:

[[v66-13-10]]

^<<v66-13-10,10>>^ Quem tem de ser preso será preso; quem tem de ser morto pela espada será morto pela espada. Isso exige que o povo de Deus aguente o sofrimento com paciência e seja fiel.

[[v66-13-11]]

^<<v66-13-11,11>>^ Então vi outro monstro, que subia da terra. Ele tinha dois chifres parecidos com os de um carneiro, mas falava como um dragão.

[[v66-13-12]]

^<<v66-13-12,12>>^ Usava toda a autoridade do primeiro monstro, na sua presença. Forçava a terra e todos os que moram nela a adorarem o primeiro monstro, aquele cuja ferida mortal havia sido curada.

[[v66-13-13]]

^<<v66-13-13,13>>^ Esse segundo monstro fez coisas espantosas. Fez com que caísse fogo do céu sobre a terra, na presença de todas as pessoas.

[[v66-13-14]]

^<<v66-13-14,14>>^ E enganou todos os povos da terra, por meio das coisas que lhe foi permitido fazer na presença do primeiro monstro. O segundo monstro disse a todos os povos do mundo que fizessem uma imagem em honra ao outro monstro, que havia sido ferido pela espada e não havia morrido.

[[v66-13-15]]

^<<v66-13-15,15>>^ O segundo monstro recebeu poder de soprar vida na imagem do primeiro, para que ela pudesse falar e matar todos os que não a adorassem.

[[v66-13-16]]

^<<v66-13-16,16>>^ Ele obrigou todas as pessoas, importantes e humildes, ricas e pobres, escravas e livres, a terem um sinal na mão direita ou na testa.

[[v66-13-17]]

^<<v66-13-17,17>>^ Ninguém podia comprar ou vender, a não ser que tivesse esse sinal, isto é, o nome do monstro ou o número do nome dele.

[[v66-13-18]]

^<<v66-13-18,18>>^ Isso exige sabedoria. Quem é inteligente pode descobrir o que o número do monstro quer dizer, pois o número representa o nome de um ser humano. O seu número é seiscentos e sessenta e seis.

'''

xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[&#60; Capítulo Anterior] | <<v66-13-0,Topo>> | xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[Próximo Capítulo &#62;]