include::./index.adoc[]

[[v66-20-0]]
=== Apocalipse, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-20-1]]

^<<v66-20-1,1>>^ Então vi descendo do céu um anjo que tinha nas mãos a chave do abismo  e uma corrente pesada.

[[v66-20-2]]

^<<v66-20-2,2>>^ Ele agarrou o dragão, aquela velha cobra que é o Diabo ou Satanás, e o amarrou por mil anos.

[[v66-20-3]]

^<<v66-20-3,3>>^ Então o anjo jogou o Diabo no abismo e trancou e selou  a porta para que ele não enganasse mais as nações até terminarem os mil anos. Depois desses mil anos é preciso que ele seja solto por um pouco de tempo.

[[v66-20-4]]

^<<v66-20-4,4>>^ Em seguida vi alguns tronos, e os que estavam sentados neles receberam o poder de julgar. Vi também as almas das pessoas que tinham sido degoladas porque haviam anunciado a mensagem de Deus e a verdade que Jesus revelou. Elas não tinham adorado o monstro nem a sua imagem, nem tinham recebido o seu sinal na testa ou na mão. Essas pessoas tornaram a viver e reinaram com Cristo durante os mil anos.

[[v66-20-5]]

^<<v66-20-5,5>>^ Os outros mortos não tornaram a viver até que os mil anos terminaram. Esta é a primeira ressurreição.

[[v66-20-6]]

^<<v66-20-6,6>>^ Felizes e abençoadas as pessoas que forem incluídas nessa primeira ressurreição, pois a segunda morte não tem poder sobre elas! Serão sacerdotes de Deus e de Cristo e reinarão com ele durante os mil anos.

[[v66-20-7]]

^<<v66-20-7,7>>^ Depois que os mil anos terminarem, Satanás será solto da sua prisão

[[v66-20-8]]

^<<v66-20-8,8>>^ e sairá para enganar os povos de todas as nações do mundo, isto é, Gogue e Magogue  . Satanás os juntará para a batalha, e eles serão tantos como os grãos de areia da praia do mar.

[[v66-20-9]]

^<<v66-20-9,9>>^ Eles se espalharam pelo mundo e cercaram o acampamento do povo de Deus e a cidade que ele ama , mas um fogo desceu do céu e os destruiu.

[[v66-20-10]]

^<<v66-20-10,10>>^ Aí o Diabo, que os havia enganado, foi jogado no lago de fogo e enxofre, onde o monstro e o falso profeta  já haviam sido lançados. E lá eles serão atormentados para todo o sempre, de dia e de noite.

[[v66-20-11]]

^<<v66-20-11,11>>^ Então vi um grande trono branco e aquele que está sentado nele. A terra e o céu fugiram da sua presença e não foram vistos mais.

[[v66-20-12]]

^<<v66-20-12,12>>^ Vi também os mortos, tanto os importantes como os humildes, que estavam de pé diante do trono. Foram abertos livros, e também foi aberto outro livro, o Livro da Vida . Os mortos foram julgados de acordo com o que cada um havia feito, conforme estava escrito nos livros.

[[v66-20-13]]

^<<v66-20-13,13>>^ Aí o mar entregou os mortos que estavam nele. A morte e o mundo dos mortos  também entregaram os que eles tinham em seu poder. E todos foram julgados de acordo com o que cada um tinha feito.

[[v66-20-14]]

^<<v66-20-14,14>>^ Então a morte e o mundo dos mortos foram jogados no lago de fogo. Esse lago de fogo é a segunda morte.

[[v66-20-15]]

^<<v66-20-15,15>>^ Quem não tinha o seu nome escrito no Livro da Vida foi jogado no lago de fogo.

'''

xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[Próximo Capítulo &#62;]