include::./index.adoc[]

[[v66-8-0]]
=== Apocalipse, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v66-8-1]]

^<<v66-8-1,1>>^ Quando o Cordeiro quebrou o sétimo selo , houve silêncio no céu por mais ou menos meia hora.

[[v66-8-2]]

^<<v66-8-2,2>>^ Então vi os sete anjos que estavam de pé diante de Deus, e eles receberam sete trombetas.

[[v66-8-3]]

^<<v66-8-3,3>>^ Outro anjo veio com um vaso de ouro no qual se queima incenso e ficou de pé ao lado do altar. Ele recebeu muito incenso para juntar com as orações de todo o povo de Deus e oferecê-lo no altar de ouro que está diante do trono.

[[v66-8-4]]

^<<v66-8-4,4>>^ E das mãos do anjo que estava diante de Deus subiu a fumaça do incenso queimado, junto com as orações do povo de Deus.

[[v66-8-5]]

^<<v66-8-5,5>>^ Então o anjo pegou o vaso de incenso, o encheu com fogo do altar e jogou sobre a terra. Houve trovões, estrondos, relâmpagos e um terremoto.

[[v66-8-6]]

^<<v66-8-6,6>>^ Em seguida os sete anjos que tinham as sete trombetas se prepararam para tocar.

[[v66-8-7]]

^<<v66-8-7,7>>^ O primeiro anjo tocou a sua trombeta, e foi lançada sobre a terra uma chuva de pedra e fogo, misturados com sangue. E foi destruída pelo fogo a terça parte da terra, das árvores e também de toda erva verde.

[[v66-8-8]]

^<<v66-8-8,8>>^ Depois o segundo anjo tocou a sua trombeta, e uma coisa que parecia uma grande montanha pegando fogo foi jogada no mar. A terça parte do mar virou sangue,

[[v66-8-9]]

^<<v66-8-9,9>>^ morreu a terça parte dos animais do mar, e foi destruída a terça parte de todos os navios e barcos.

[[v66-8-10]]

^<<v66-8-10,10>>^ Então o terceiro anjo tocou a sua trombeta, e uma grande estrela, queimando como uma tocha, caiu do céu sobre a terça parte dos rios e sobre as fontes de águas.

[[v66-8-11]]

^<<v66-8-11,11>>^ O nome dessa estrela é Amargura. A terça parte das águas se tornou amarga, e por isso muitas pessoas morreram ao beberem daquelas águas.

[[v66-8-12]]

^<<v66-8-12,12>>^ Aí o quarto anjo tocou a sua trombeta, e foi ferida a terça parte do sol, da lua e das estrelas, de modo que perderam a terça parte do seu brilho. Não houve luz durante a terça parte do dia e também da noite.

[[v66-8-13]]

^<<v66-8-13,13>>^ Depois olhei e vi uma águia que voava bem alto no céu. E ouvi a águia dizer com voz forte: — Ai de vocês! Ai de vocês! Ai de vocês que estiverem morando na terra quando se ouvir o som das trombetas que os outros três anjos vão tocar!

'''

xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[&#60; Capítulo Anterior] | <<v66-8-0,Topo>> | xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[Próximo Capítulo &#62;]