include::./index.adoc[]

[[v46-4-0]]
=== 1 Coríntios, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-4-1]]

^<<v46-4-1,1>>^ Vocês nos devem tratar como servidores de Cristo, que foram encarregados de administrar a realização dos planos secretos de Deus.

[[v46-4-2]]

^<<v46-4-2,2>>^ O que se exige de quem tem essa responsabilidade é que seja fiel ao seu Senhor.

[[v46-4-3]]

^<<v46-4-3,3>>^ Mas para mim não tem a menor importância ser julgado por vocês ou por um tribunal humano. Eu não julgo nem a mim mesmo.

[[v46-4-4]]

^<<v46-4-4,4>>^ A minha consciência está limpa, mas isso não prova que sou, de fato, inocente. Quem me julga é o Senhor.

[[v46-4-5]]

^<<v46-4-5,5>>^ Portanto, não julguem ninguém antes da hora; esperem o julgamento final, quando o Senhor vier. Ele trará para a luz os segredos escondidos no escuro e mostrará as intenções que estão no coração das pessoas. Então cada um receberá de Deus os elogios que merece.

[[v46-4-6]]

^<<v46-4-6,6>>^ Meus irmãos, é para instruir vocês que eu tenho aplicado essas lições a mim mesmo e a Apolo. Usei nós dois como um exemplo, para que vocês aprendam o que quer dizer o ditado: "Obedeça ao que está escrito." Ninguém deve se orgulhar de uma pessoa e desprezar outra.

[[v46-4-7]]

^<<v46-4-7,7>>^ Quem é que fez você superior aos outros? Por acaso não foi Deus quem lhe deu tudo o que você tem? Então por que é que você fica todo orgulhoso como se o que você tem não fosse dado por Deus?

[[v46-4-8]]

^<<v46-4-8,8>>^ Pelo que parece, vocês já têm tudo o que precisam! Já são ricos! Vocês já se tornaram reis, e nós, não! Que bom se vocês fossem reis de verdade, para que nós pudéssemos reinar junto com vocês!

[[v46-4-9]]

^<<v46-4-9,9>>^ Porque me parece que Deus pôs a nós, os apóstolos  , no último lugar. Somos como as pessoas condenadas a morrer em público, como espetáculo para o mundo inteiro, tanto para os anjos como para os seres humanos.

[[v46-4-10]]

^<<v46-4-10,10>>^ Por causa de Cristo nós somos loucos, mas vocês são sábios por estarem unidos com ele. Nós somos fracos, e vocês são fortes; vocês são respeitados, e nós somos desprezados.

[[v46-4-11]]

^<<v46-4-11,11>>^ Até agora temos passado fome e sede. Temos nos vestido com trapos, temos recebido bofetadas e não temos lugar certo para morar.

[[v46-4-12]]

^<<v46-4-12,12>>^ Temos nos cansado de trabalhar para nos sustentar. Quando somos amaldiçoados, nós abençoamos. Quando somos perseguidos, aguentamos com paciência.

[[v46-4-13]]

^<<v46-4-13,13>>^ Quando somos insultados, respondemos com palavras delicadas. Somos considerados como lixo, e até agora somos tratados como a imundície deste mundo.

[[v46-4-14]]

^<<v46-4-14,14>>^ Não estou escrevendo essas coisas para envergonhar vocês, mas para ensiná-los como se vocês fossem meus próprios filhos queridos.

[[v46-4-15]]

^<<v46-4-15,15>>^ Mesmo que vocês tivessem milhares de mestres na fé cristã, não poderiam ter mais de um pai. Pois, quando levei a vocês o evangelho , eu me tornei o pai de vocês na vida que vivem em união com Cristo Jesus.

[[v46-4-16]]

^<<v46-4-16,16>>^ Portanto, eu peço que sigam o meu exemplo.

[[v46-4-17]]

^<<v46-4-17,17>>^ Por isso estou enviando para vocês Timóteo, que é meu querido e fiel filho no Senhor. Ele vai ajudá-los a lembrarem dos caminhos que sigo na nova vida que tenho em união com Cristo Jesus, caminhos esses que ensino em todas as igrejas.

[[v46-4-18]]

^<<v46-4-18,18>>^ Alguns de vocês ficaram orgulhosos, certos de que eu não iria visitá-los.

[[v46-4-19]]

^<<v46-4-19,19>>^ Porém, se o Senhor quiser, eu vou visitá-los logo. Então vou saber o que esses orgulhosos são capazes de fazer e não somente o que eles são capazes de dizer.

[[v46-4-20]]

^<<v46-4-20,20>>^ Pois o Reino de Deus  não é coisa de palavras, mas de poder.

[[v46-4-21]]

^<<v46-4-21,21>>^ O que é que vocês preferem: que eu vá até vocês com um chicote ou com o coração cheio de amor e bondade?

'''

xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[Próximo Capítulo &#62;]