include::./index.adoc[]

[[v46-16-0]]
=== 1 Coríntios, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-16-1]]

^<<v46-16-1,1>>^ Agora vou tratar do dinheiro para ajudar o povo de Deus da Judeia. Façam o que eu disse às igrejas da província  da Galácia.

[[v46-16-2]]

^<<v46-16-2,2>>^ Todos os domingos cada um de vocês separe e guarde algum dinheiro, de acordo com o que cada um ganhou. Assim não haverá necessidade de recolher ofertas quando eu chegar.

[[v46-16-3]]

^<<v46-16-3,3>>^ Depois que chegar, eu enviarei, com cartas de apresentação, aqueles que vocês escolherem para levarem a oferta até Jerusalém.

[[v46-16-4]]

^<<v46-16-4,4>>^ Se for conveniente que eu também vá, eles farão a viagem comigo.

[[v46-16-5]]

^<<v46-16-5,5>>^ Eu visitarei vocês depois que tiver passado pela província  da Macedônia, pois vou passar por lá.

[[v46-16-6]]

^<<v46-16-6,6>>^ Pode ser que eu fique algum tempo com vocês, talvez todo o inverno, e assim vocês poderão me ajudar a continuar a minha viagem para onde quer que eu for.

[[v46-16-7]]

^<<v46-16-7,7>>^ Pois eu não quero ver vocês apenas de passagem. Se o Senhor permitir, espero ficar bastante tempo com vocês.

[[v46-16-8]]

^<<v46-16-8,8>>^ Resolvi ficar aqui em Éfeso até o dia de Pentecostes .

[[v46-16-9]]

^<<v46-16-9,9>>^ Pois encontrei aqui ótimas oportunidades para um grande e proveitoso trabalho, embora muita gente esteja contra mim.

[[v46-16-10]]

^<<v46-16-10,10>>^ Se Timóteo chegar aí, façam tudo para que ele se sinta bem entre vocês; pois, assim como eu, ele também está trabalhando para o Senhor.

[[v46-16-11]]

^<<v46-16-11,11>>^ Não deixem que ninguém o despreze. Pelo contrário, vocês devem ajudá-lo a continuar a sua viagem em paz, a fim de que ele volte para cá. Pois estou esperando que ele volte junto com os outros irmãos.

[[v46-16-12]]

^<<v46-16-12,12>>^ Quanto ao irmão Apolo, tenho recomendado muitas vezes que vá visitar vocês com os outros irmãos, mas ele acha que não deve ir agora. Ele irá na primeira oportunidade.

[[v46-16-13]]

^<<v46-16-13,13>>^ Estejam alertas, fiquem firmes na fé, sejam corajosos, sejam fortes.

[[v46-16-14]]

^<<v46-16-14,14>>^ Que tudo o que vocês fizerem seja feito com amor.

[[v46-16-15]]

^<<v46-16-15,15>>^ Vocês conhecem Estéfanas e a família dele. Vocês sabem que eles foram os primeiros cristãos convertidos na província  da Acaia e que eles têm se dedicado ao serviço do povo de Deus. Peço a vocês, meus irmãos,

[[v46-16-16]]

^<<v46-16-16,16>>^ que sigam a orientação deles e dos outros que os ajudam e trabalham com eles.

[[v46-16-17]]

^<<v46-16-17,17>>^ Eu estou alegre com a vinda de Estéfanas, de Fortunato e de Acaico, pois eles fizeram o que vocês, por estarem ausentes, não podiam fazer.

[[v46-16-18]]

^<<v46-16-18,18>>^ Eles me animaram muito, e sei que animaram vocês também. Gente como essa merece elogios.

[[v46-16-19]]

^<<v46-16-19,19>>^ As igrejas da província da Ásia mandam saudações. Áquila e a sua esposa Priscila e a igreja que se reúne na casa deles mandam saudações cristãs a vocês.

[[v46-16-20]]

^<<v46-16-20,20>>^ Todos os irmãos daqui mandam saudações. Cumprimentem uns aos outros com um beijo de irmão.

[[v46-16-21]]

^<<v46-16-21,21>>^ Escrevo isto com a minha própria mão: Saudações de Paulo.

[[v46-16-22]]

^<<v46-16-22,22>>^ Quem não ama o Senhor, que seja amaldiçoado! "Marana tá" — Vem, nosso Senhor !

[[v46-16-23]]

^<<v46-16-23,23>>^ Que a graça  do nosso Senhor Jesus esteja com vocês!

[[v46-16-24]]

^<<v46-16-24,24>>^ E que o meu amor esteja com todos vocês, pois estamos unidos com Cristo Jesus!

'''

xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[&#60; Capítulo Anterior] | <<v46-16-0,Topo>> | xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[Próximo Capítulo &#62;]