include::./index.adoc[]

[[v46-3-0]]
=== 1 Coríntios, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-3-1]]

^<<v46-3-1,1>>^ Na verdade, irmãos, eu não pude falar com vocês como costumo fazer com as pessoas que têm o Espírito de Deus. Tive de falar com vocês como se vocês fossem pessoas do mundo, como se fossem crianças na fé cristã.

[[v46-3-2]]

^<<v46-3-2,2>>^ Tive de alimentá-los com leite e não com comida forte, pois vocês não estavam prontos para isso. E ainda não estão prontos,

[[v46-3-3]]

^<<v46-3-3,3>>^ porque vivem como se fossem pessoas deste mundo. Quando existem ciumeiras e brigas entre vocês, será que isso não prova que vocês são pessoas deste mundo e fazem o que todos fazem?

[[v46-3-4]]

^<<v46-3-4,4>>^ Quando alguém diz: "Eu sou de Paulo", e outro: "Eu sou de Apolo", será que assim não estão agindo como pessoas deste mundo?

[[v46-3-5]]

^<<v46-3-5,5>>^ Afinal de contas, quem é Apolo? E quem é Paulo? Somos somente servidores de Deus, e foi por meio de nós que vocês creram no Senhor. Cada um de nós faz o trabalho que o Senhor lhe deu para fazer:

[[v46-3-6]]

^<<v46-3-6,6>>^ Eu plantei, e Apolo regou a planta, mas foi Deus quem a fez crescer.

[[v46-3-7]]

^<<v46-3-7,7>>^ De modo que não importa nem o que planta nem o que rega, mas sim Deus, que dá o crescimento.

[[v46-3-8]]

^<<v46-3-8,8>>^ Pois não existe diferença entre a pessoa que planta e a pessoa que rega. Deus dará a recompensa de acordo com o trabalho que cada um tiver feito.

[[v46-3-9]]

^<<v46-3-9,9>>^ Porque nós somos companheiros de trabalho no serviço de Deus, e vocês são o terreno no qual Deus faz o seu trabalho. Vocês são também o edifício de Deus.

[[v46-3-10]]

^<<v46-3-10,10>>^ Usando o dom  que Deus me deu, eu faço o trabalho de um construtor competente. Ponho o alicerce, e outro constrói em cima dele; porém cada um deve construir com cuidado.

[[v46-3-11]]

^<<v46-3-11,11>>^ Porque Deus já pôs Jesus Cristo como o único alicerce, e nenhum outro alicerce pode ser colocado.

[[v46-3-12]]

^<<v46-3-12,12>>^ Alguns usam ouro ou prata ou pedras preciosas para construírem em cima do alicerce. E ainda outros usam madeira ou capim ou palha.

[[v46-3-13]]

^<<v46-3-13,13>>^ O Dia de Cristo vai mostrar claramente a qualidade do trabalho de cada um. Pois o fogo daquele dia mostrará o trabalho de cada pessoa: o fogo vai mostrar e provar a verdadeira qualidade do trabalho.

[[v46-3-14]]

^<<v46-3-14,14>>^ Se aquilo que alguém construir em cima do alicerce resistir ao fogo, então o construtor receberá a recompensa.

[[v46-3-15]]

^<<v46-3-15,15>>^ Mas, se o trabalho de alguém for destruído pelo fogo, então esse construtor perderá a recompensa. Porém ele mesmo será salvo, como se tivesse passado pelo fogo para se salvar.

[[v46-3-16]]

^<<v46-3-16,16>>^ Certamente vocês sabem que são o templo de Deus e que o Espírito de Deus vive em vocês.

[[v46-3-17]]

^<<v46-3-17,17>>^ Assim, se alguém destruir o templo de Deus, Deus destruirá essa pessoa. Pois o templo de Deus é santo , e vocês são o seu templo.

[[v46-3-18]]

^<<v46-3-18,18>>^ Que ninguém engane a si mesmo! Se algum de vocês pensa que é sábio conforme a sabedoria humana, então precisa se tornar louco para ser, de fato, sábio.

[[v46-3-19]]

^<<v46-3-19,19>>^ Pois aquilo que este mundo acha que é sabedoria Deus acha que é loucura. Como dizem as Escrituras Sagradas : "Deus pega os sábios nas suas espertezas."

[[v46-3-20]]

^<<v46-3-20,20>>^ E também: "O Senhor sabe que os pensamentos dos sábios não valem nada."

[[v46-3-21]]

^<<v46-3-21,21>>^ Ninguém deve se orgulhar daquilo que as pessoas podem fazer. Pois tudo é de vocês,

[[v46-3-22]]

^<<v46-3-22,22>>^ isto é, Paulo, Apolo, Pedro, este mundo, a vida e a morte, o presente e o futuro. Tudo isso pertence a vocês,

[[v46-3-23]]

^<<v46-3-23,23>>^ e vocês pertencem a Cristo, e Cristo pertence a Deus.

'''

xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[&#60; Capítulo Anterior] | <<v46-3-0,Topo>> | xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[Próximo Capítulo &#62;]