include::./index.adoc[]

[[v46-10-0]]
=== 1 Coríntios, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-10-1]]

^<<v46-10-1,1>>^ Irmãos, eu quero que vocês lembrem do que aconteceu com os nossos antepassados que seguiram Moisés. Todos foram protegidos pela nuvem e passaram pelo mar Vermelho.

[[v46-10-2]]

^<<v46-10-2,2>>^ Como seguidores de Moisés, eles foram batizados na nuvem e no mar.

[[v46-10-3]]

^<<v46-10-3,3>>^ Todos comeram da mesma comida espiritual

[[v46-10-4]]

^<<v46-10-4,4>>^ e beberam da mesma bebida espiritual. Pois bebiam daquela rocha espiritual que ia com eles; e a rocha era Cristo.

[[v46-10-5]]

^<<v46-10-5,5>>^ Mas Deus não ficou contente com a maioria deles, e por isso eles morreram, e os seus corpos ficaram espalhados no deserto.

[[v46-10-6]]

^<<v46-10-6,6>>^ Tudo isso aconteceu a fim de nos servir de exemplo, para nós não querermos coisas más como eles quiseram,

[[v46-10-7]]

^<<v46-10-7,7>>^ nem adorarmos ídolos, como alguns deles adoraram. Como dizem as Escrituras Sagradas : "O povo sentou-se para comer e beber e se levantou para se divertir."

[[v46-10-8]]

^<<v46-10-8,8>>^ Não devemos cometer imoralidade sexual, como alguns deles fizeram. E, porque eles fizeram isso, vinte e três mil deles caíram mortos num dia só.

[[v46-10-9]]

^<<v46-10-9,9>>^ Não devemos pôr à prova a paciência de Cristo, como alguns deles fizeram, e por isso foram mortos pelas cobras.

[[v46-10-10]]

^<<v46-10-10,10>>^ Vocês não devem se queixar, como fizeram alguns deles, e por isso foram destruídos pelo Anjo da Morte.

[[v46-10-11]]

^<<v46-10-11,11>>^ Tudo isso aconteceu com os nossos antepassados a fim de servir de exemplo para os outros, e aquelas coisas foram escritas a fim de servirem de aviso para nós. Pois estamos vivendo no fim dos tempos.

[[v46-10-12]]

^<<v46-10-12,12>>^ Portanto, aquele que pensa que está de pé é melhor ter cuidado para não cair.

[[v46-10-13]]

^<<v46-10-13,13>>^ As tentações que vocês têm de enfrentar são as mesmas que os outros enfrentam; mas Deus cumpre a sua promessa e não deixará que vocês sofram tentações que vocês não têm forças para suportar. Quando uma tentação vier, Deus dará forças a vocês para suportá-la, e assim vocês poderão sair dela.

[[v46-10-14]]

^<<v46-10-14,14>>^ Por isso, meus queridos amigos, fujam da adoração de ídolos.

[[v46-10-15]]

^<<v46-10-15,15>>^ Eu falo com vocês como com pessoas que têm capacidade para entender o que estou afirmando. Julguem vocês mesmos o que eu estou dizendo.

[[v46-10-16]]

^<<v46-10-16,16>>^ Pensem no cálice pelo qual damos graças a Deus na Ceia do Senhor. Será que, quando bebemos desse cálice, não estamos tomando parte no sangue de Cristo? E, quando partimos e comemos o pão, não estamos tomando parte no corpo de Cristo?

[[v46-10-17]]

^<<v46-10-17,17>>^ Mesmo sendo muitos, todos comemos do mesmo pão, que é um só; e por isso somos um só corpo.

[[v46-10-18]]

^<<v46-10-18,18>>^ Pensem no povo de Israel. Aqueles que comem as coisas oferecidas em sacrifícios  tomam parte juntos no sacrifício que é oferecido a Deus no altar.

[[v46-10-19]]

^<<v46-10-19,19>>^ O que é que eu quero dizer com isso? Que o ídolo ou o alimento que é oferecido a ele tem algum valor?

[[v46-10-20]]

^<<v46-10-20,20>>^ É claro que não! O que estou dizendo é que aquilo que é sacrificado nos altares pagãos é oferecido aos demônios e não a Deus. E eu não quero que vocês tomem parte nas coisas dos demônios.

[[v46-10-21]]

^<<v46-10-21,21>>^ Vocês não podem beber do cálice do Senhor e também do cálice dos demônios. Vocês não podem comer na mesa do Senhor e também na mesa dos demônios.

[[v46-10-22]]

^<<v46-10-22,22>>^ Ou será que queremos provocar o Senhor, fazendo com que ele fique com ciúmes? Por acaso vocês pensam que somos mais fortes do que ele?

[[v46-10-23]]

^<<v46-10-23,23>>^ Alguns dizem assim: "Podemos fazer tudo o que queremos." Sim, mas nem tudo é bom. "Podemos fazer tudo o que queremos", mas nem tudo é útil.

[[v46-10-24]]

^<<v46-10-24,24>>^ Ninguém deve buscar os seus próprios interesses e sim os interesses dos outros.

[[v46-10-25]]

^<<v46-10-25,25>>^ Vocês podem comer de tudo o que se vende no açougue, sem terem nenhuma dúvida de consciência.

[[v46-10-26]]

^<<v46-10-26,26>>^ Pois, como dizem as Escrituras Sagradas : "A terra e tudo o que nela existe pertencem ao Senhor."

[[v46-10-27]]

^<<v46-10-27,27>>^ Se alguém que não é cristão convidá-los para comer, e vocês resolverem ir, comam o que for posto na frente de vocês e não façam perguntas por motivo de consciência.

[[v46-10-28]]

^<<v46-10-28,28>>^ Mas, se alguém disser a vocês: "Esta comida foi oferecida aos ídolos", neste caso não comam, por causa daquele que disse isso e também por motivo de consciência.

[[v46-10-29]]

^<<v46-10-29,29>>^ Não estou falando da sua própria consciência, mas da consciência do outro. Mas alguém pode perguntar: "Por que é que a minha liberdade deve ser diminuída pela consciência dos outros?

[[v46-10-30]]

^<<v46-10-30,30>>^ Se eu agradeço a Deus o alimento que como, por que é que sou criticado, se já o agradeci a Deus?"

[[v46-10-31]]

^<<v46-10-31,31>>^ Portanto, quando vocês comem, ou bebem, ou fazem qualquer outra coisa, façam tudo para a glória  de Deus.

[[v46-10-32]]

^<<v46-10-32,32>>^ Vivam de tal maneira que não prejudiquem os judeus, nem os não judeus, nem a Igreja de Deus.

[[v46-10-33]]

^<<v46-10-33,33>>^ Façam como eu. Procuro agradar a todos em tudo o que faço, não pensando no meu próprio bem, mas no bem de todos, a fim de que eles possam ser salvos.

'''

xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[&#60; Capítulo Anterior] | <<v46-10-0,Topo>> | xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[Próximo Capítulo &#62;]