include::./index.adoc[]

[[v46-8-0]]
=== 1 Coríntios, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-8-1]]

^<<v46-8-1,1>>^ Agora vou tratar do problema dos alimentos oferecidos aos ídolos. Na verdade, como se diz, "todos nós temos conhecimento." Porém esse tipo de conhecimento enche a pessoa de orgulho; mas o amor nos faz progredir na fé.

[[v46-8-2]]

^<<v46-8-2,2>>^ A pessoa que pensa que sabe alguma coisa ainda não tem a sabedoria que precisa.

[[v46-8-3]]

^<<v46-8-3,3>>^ Mas quem ama a Deus é conhecido por ele.

[[v46-8-4]]

^<<v46-8-4,4>>^ Quanto a comer alimentos que tenham sido oferecidos aos ídolos, nós sabemos que um ídolo representa alguma coisa que realmente não existe. E sabemos que existe somente um Deus.

[[v46-8-5]]

^<<v46-8-5,5>>^ Pois existem os que são chamados de "deuses", tanto no céu como na terra, como também existem muitos "deuses" e muitos "senhores".

[[v46-8-6]]

^<<v46-8-6,6>>^ Porém para nós existe somente um Deus, o Pai e Criador de todas as coisas, para quem nós vivemos. E existe somente um Senhor, que é Jesus Cristo, por meio de quem todas as coisas foram criadas e por meio de quem nós existimos.

[[v46-8-7]]

^<<v46-8-7,7>>^ Mas nem todos conhecem essa verdade. Existem pessoas tão acostumadas com os ídolos, que até agora comem desses alimentos, pensando que eles pertencem aos ídolos. A consciência dessas pessoas é fraca, e por isso elas se sentem impuras  quando comem desses alimentos.

[[v46-8-8]]

^<<v46-8-8,8>>^ Não é esta ou aquela comida que vai fazer com que Deus nos aceite. Nós não perderemos nada se não comermos e não ganharemos nada se comermos desse alimento.

[[v46-8-9]]

^<<v46-8-9,9>>^ Mas tenham cuidado para que essa liberdade de vocês não faça com que os fracos na fé caiam em pecado.

[[v46-8-10]]

^<<v46-8-10,10>>^ Porque, se uma pessoa que tem a consciência fraca neste assunto vir você, que tem "conhecimento", comendo alimentos no templo de um ídolo, será que essa pessoa não vai querer também comer alimentos oferecidos aos ídolos?

[[v46-8-11]]

^<<v46-8-11,11>>^ Assim este cristão fraco, este seu irmão por quem Cristo morreu, vai se perder por causa do "conhecimento" que você tem.

[[v46-8-12]]

^<<v46-8-12,12>>^ Desse modo, pecando contra o seu irmão e ferindo a consciência dele, você estará pecando contra Cristo.

[[v46-8-13]]

^<<v46-8-13,13>>^ Portanto, se o alimento faz com que o meu irmão peque, nunca mais vou comer carne a fim de que eu não seja a causa do pecado dele.

'''

xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[Próximo Capítulo &#62;]