include::./index.adoc[]

[[v46-15-0]]
=== 1 Coríntios, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-15-1]]

^<<v46-15-1,1>>^ Agora, irmãos, quero que lembrem do evangelho  que eu anunciei a vocês, o qual vocês aceitaram e no qual continuam firmes.

[[v46-15-2]]

^<<v46-15-2,2>>^ A mensagem que anunciei a vocês é o evangelho, por meio do qual vocês são salvos, se continuarem firmes nele. A não ser que não tenha adiantado nada vocês crerem nele.

[[v46-15-3]]

^<<v46-15-3,3>>^ Eu passei para vocês o ensinamento que recebi e que é da mais alta importância: Cristo morreu pelos nossos pecados, como está escrito nas Escrituras Sagradas ;

[[v46-15-4]]

^<<v46-15-4,4>>^ ele foi sepultado e, no terceiro dia, foi ressuscitado, como está escrito nas Escrituras;

[[v46-15-5]]

^<<v46-15-5,5>>^ e apareceu a Pedro e depois aos doze apóstolos .

[[v46-15-6]]

^<<v46-15-6,6>>^ Depois apareceu, de uma só vez, a mais de quinhentos seguidores, dos quais a maior parte ainda vive, mas alguns já morreram.

[[v46-15-7]]

^<<v46-15-7,7>>^ Em seguida apareceu a Tiago e, mais tarde, a todos os apóstolos.

[[v46-15-8]]

^<<v46-15-8,8>>^ Por último, depois de todos, ele apareceu também a mim, como para alguém nascido fora de tempo.

[[v46-15-9]]

^<<v46-15-9,9>>^ De fato, eu sou o menos importante dos apóstolos e até nem mereço ser chamado de apóstolo, pois persegui a Igreja de Deus.

[[v46-15-10]]

^<<v46-15-10,10>>^ Mas pela graça  de Deus sou o que sou, e a graça que ele me deu não ficou sem resultados. Pelo contrário, eu tenho trabalhado muito mais do que todos os outros apóstolos. No entanto não sou eu quem tem feito isso, e sim a graça de Deus que está comigo.

[[v46-15-11]]

^<<v46-15-11,11>>^ Assim, não importa se a mensagem foi entregue por mim ou se foi entregue por eles; o importante é que foi isso que todos nós anunciamos, e foi nisso que vocês creram.

[[v46-15-12]]

^<<v46-15-12,12>>^ Se a nossa mensagem é que Cristo foi ressuscitado, como é que alguns de vocês dizem que os mortos não vão ressuscitar?

[[v46-15-13]]

^<<v46-15-13,13>>^ Se não existe a ressurreição de mortos, então quer dizer que Cristo não foi ressuscitado.

[[v46-15-14]]

^<<v46-15-14,14>>^ E, se Cristo não foi ressuscitado, nós não temos nada para anunciar, e vocês não têm nada para crer.

[[v46-15-15]]

^<<v46-15-15,15>>^ E mais ainda: nesse caso estaríamos mentindo contra Deus, porque afirmamos que ele ressuscitou Cristo. Mas, se é verdade que os mortos não são ressuscitados, então Deus não ressuscitou Cristo.

[[v46-15-16]]

^<<v46-15-16,16>>^ Porque, se os mortos não são ressuscitados, Cristo também não foi ressuscitado.

[[v46-15-17]]

^<<v46-15-17,17>>^ E, se Cristo não foi ressuscitado, a fé que vocês têm é uma ilusão, e vocês continuam perdidos nos seus pecados.

[[v46-15-18]]

^<<v46-15-18,18>>^ Se Cristo não ressuscitou, os que morreram crendo nele estão perdidos.

[[v46-15-19]]

^<<v46-15-19,19>>^ Se a nossa esperança em Cristo só vale para esta vida, nós somos as pessoas mais infelizes deste mundo.

[[v46-15-20]]

^<<v46-15-20,20>>^ Mas a verdade é que Cristo foi ressuscitado, e isso é a garantia de que os que estão mortos também serão ressuscitados.

[[v46-15-21]]

^<<v46-15-21,21>>^ Porque, assim como por meio de um homem veio a morte, assim também por meio de um homem veio a ressurreição.

[[v46-15-22]]

^<<v46-15-22,22>>^ Assim como, por estarem unidos com Adão, todos morrem, assim também, por estarem unidos com Cristo, todos ressuscitarão.

[[v46-15-23]]

^<<v46-15-23,23>>^ Porém cada um será ressuscitado na sua vez: Cristo, o primeiro de todos; depois os que são de Cristo, quando ele vier;

[[v46-15-24]]

^<<v46-15-24,24>>^ e então virá o fim. Cristo destruirá todos os governos espirituais, todas as autoridades e poderes e entregará o Reino  a Deus, o Pai.

[[v46-15-25]]

^<<v46-15-25,25>>^ Pois Cristo tem de reinar até que Deus faça com que ele domine todos os inimigos.

[[v46-15-26]]

^<<v46-15-26,26>>^ O último inimigo que será destruído é a morte.

[[v46-15-27]]

^<<v46-15-27,27>>^ As Escrituras Sagradas  dizem: "Deus pôs todas as coisas debaixo do domínio dele." É claro que dentro das palavras "todas as coisas" não está o próprio Deus, que põe tudo debaixo do domínio de Cristo.

[[v46-15-28]]

^<<v46-15-28,28>>^ Mas, quando tudo for dominado por Cristo, então o próprio Cristo, que é o Filho, se colocará debaixo do domínio de Deus, que pôs todas as coisas debaixo do domínio dele. Então Deus reinará completamente sobre tudo.

[[v46-15-29]]

^<<v46-15-29,29>>^ Pensem agora nas pessoas que são batizadas em favor dos mortos : o que é que elas esperam conseguir? Se os mortos não são ressuscitados, por que é que essas pessoas se batizam em favor deles?

[[v46-15-30]]

^<<v46-15-30,30>>^ E, quanto a nós, por que é que nos colocamos em perigo a toda hora?

[[v46-15-31]]

^<<v46-15-31,31>>^ Irmãos, eu enfrento a morte todos os dias. Se afirmo isso, é pelo orgulho que tenho de vocês, pois estamos todos unidos com Cristo Jesus, o nosso Senhor.

[[v46-15-32]]

^<<v46-15-32,32>>^ Aqui em Éfeso eu lutei contra inimigos como se lutasse contra animais selvagens. E, se fiz isso somente por interesses humanos, o que foi que eu consegui com isso? Se é verdade que os mortos não são ressuscitados, façamos o que diz o ditado: "Comamos e bebamos porque amanhã morreremos."

[[v46-15-33]]

^<<v46-15-33,33>>^ Não se enganem: "As más companhias estragam os bons costumes."

[[v46-15-34]]

^<<v46-15-34,34>>^ Comecem de novo a viver uma vida séria e direita e parem de pecar. Para fazer com que vocês fiquem envergonhados, eu digo o seguinte: alguns de vocês não conhecem a Deus.

[[v46-15-35]]

^<<v46-15-35,35>>^ Mas alguém perguntará: "Como é que os mortos são ressuscitados? Que tipo de corpo eles vão ter?"

[[v46-15-36]]

^<<v46-15-36,36>>^ Seu tolo! Quando você semeia uma semente na terra, ela só brota se morrer.

[[v46-15-37]]

^<<v46-15-37,37>>^ E o que foi semeado é apenas uma semente, talvez um grão de trigo ou outra semente qualquer e não o corpo já formado da planta que vai crescer.

[[v46-15-38]]

^<<v46-15-38,38>>^ Deus dá a essa semente o corpo que ele quer e dá a cada semente um corpo próprio.

[[v46-15-39]]

^<<v46-15-39,39>>^ E a carne dos seres vivos não é toda do mesmo tipo. Os seres humanos têm um tipo de carne; os animais, outro; os pássaros, outro; e os peixes, ainda outro.

[[v46-15-40]]

^<<v46-15-40,40>>^ Há também corpos do céu e corpos da terra. Existe um tipo de beleza que pertence aos corpos celestes, e há outro que pertence aos corpos terrestres.

[[v46-15-41]]

^<<v46-15-41,41>>^ O sol tem o seu próprio brilho; a lua, outro brilho; e as estrelas têm um brilho diferente. E mesmo as estrelas têm diferentes tipos de brilho.

[[v46-15-42]]

^<<v46-15-42,42>>^ Pois será assim quando os mortos ressuscitarem. Quando o corpo é sepultado, é um corpo mortal; mas, quando for ressuscitado, será imortal .

[[v46-15-43]]

^<<v46-15-43,43>>^ Quando ele é sepultado, é feio e fraco; mas, quando for ressuscitado, será bonito e forte.

[[v46-15-44]]

^<<v46-15-44,44>>^ Quando é sepultado, é um corpo material; mas, quando for ressuscitado, será um corpo espiritual. É claro que, se existe um corpo material, então tem de haver também um corpo espiritual.

[[v46-15-45]]

^<<v46-15-45,45>>^ Porque as Escrituras Sagradas  dizem: "Adão, o primeiro homem, foi criado como ser vivo." Mas o último Adão, Jesus Cristo, é o Espírito que dá vida.

[[v46-15-46]]

^<<v46-15-46,46>>^ Não é o espiritual que vem primeiro, mas sim o material; depois é que vem o espiritual.

[[v46-15-47]]

^<<v46-15-47,47>>^ O primeiro homem foi feito do pó da terra; o segundo veio do céu.

[[v46-15-48]]

^<<v46-15-48,48>>^ Os que pertencem à terra são como aquele que foi feito do pó da terra; os que pertencem ao céu são como aquele que veio do céu.

[[v46-15-49]]

^<<v46-15-49,49>>^ Assim como somos parecidos com o homem feito do pó da terra, assim também seremos parecidos com o Homem do céu.

[[v46-15-50]]

^<<v46-15-50,50>>^ Meus irmãos, o que eu quero dizer é isto: o que é feito de carne e de sangue não pode ter parte no Reino de Deus , e o que é mortal não pode ter a imortalidade.

[[v46-15-51]]

^<<v46-15-51,51>>^ Escutem bem este segredo: nem todos vamos morrer , mas todos nós vamos ser transformados, num instante,

[[v46-15-52]]

^<<v46-15-52,52>>^ num abrir e fechar de olhos, quando tocar a última trombeta. Ela tocará, os mortos serão ressuscitados como seres imortais, e todos nós seremos transformados.

[[v46-15-53]]

^<<v46-15-53,53>>^ Pois este corpo mortal precisa se vestir com o que é imortal; este corpo que vai morrer precisa se vestir com o que não pode morrer.

[[v46-15-54]]

^<<v46-15-54,54>>^ Assim, quando este corpo mortal se vestir com o que é imortal, quando este corpo que morre se vestir com o que não pode morrer, então acontecerá o que as Escrituras Sagradas dizem: "A morte está destruída! A vitória é completa!"

[[v46-15-55]]

^<<v46-15-55,55>>^ "Onde está, ó morte, a sua vitória? Onde está, ó morte, o seu poder de ferir?"

[[v46-15-56]]

^<<v46-15-56,56>>^ O que dá à morte o poder de ferir é o pecado, e o que dá ao pecado o poder de ferir é a lei .

[[v46-15-57]]

^<<v46-15-57,57>>^ Mas agradeçamos a Deus, que nos dá a vitória por meio do nosso Senhor Jesus Cristo!

[[v46-15-58]]

^<<v46-15-58,58>>^ Portanto, queridos irmãos, continuem fortes e firmes. Continuem ocupados no trabalho do Senhor, pois vocês sabem que todo o seu esforço nesse trabalho sempre traz proveito.

'''

xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[&#60; Capítulo Anterior] | <<v46-15-0,Topo>> | xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[Próximo Capítulo &#62;]