include::./index.adoc[]

[[v46-13-0]]
=== 1 Coríntios, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-13-1]]

^<<v46-13-1,1>>^ Eu poderia falar todas as línguas que são faladas na terra e até no céu, mas, se não tivesse amor, as minhas palavras seriam como o som de um gongo ou como o barulho de um sino.

[[v46-13-2]]

^<<v46-13-2,2>>^ Poderia ter o dom  de anunciar mensagens de Deus, ter todo o conhecimento, entender todos os segredos e ter tanta fé, que até poderia tirar as montanhas do seu lugar, mas, se não tivesse amor, eu não seria nada.

[[v46-13-3]]

^<<v46-13-3,3>>^ Poderia dar tudo o que tenho e até mesmo entregar o meu corpo para ser queimado, mas, se eu não tivesse amor, isso não me adiantaria nada.

[[v46-13-4]]

^<<v46-13-4,4>>^ Quem ama é paciente e bondoso. Quem ama não é ciumento, nem orgulhoso, nem vaidoso.

[[v46-13-5]]

^<<v46-13-5,5>>^ Quem ama não é grosseiro nem egoísta; não fica irritado, nem guarda mágoas.

[[v46-13-6]]

^<<v46-13-6,6>>^ Quem ama não fica alegre quando alguém faz uma coisa errada, mas se alegra quando alguém faz o que é certo.

[[v46-13-7]]

^<<v46-13-7,7>>^ Quem ama nunca desiste, porém suporta tudo com fé, esperança e paciência.

[[v46-13-8]]

^<<v46-13-8,8>>^ O amor é eterno. Existem mensagens espirituais, porém elas durarão pouco. Existe o dom de falar em línguas estranhas , mas acabará logo. Existe o conhecimento, mas também terminará.

[[v46-13-9]]

^<<v46-13-9,9>>^ Pois os nossos dons de conhecimento e as nossas mensagens espirituais são imperfeitos.

[[v46-13-10]]

^<<v46-13-10,10>>^ Mas, quando vier o que é perfeito, então o que é imperfeito desaparecerá.

[[v46-13-11]]

^<<v46-13-11,11>>^ Quando eu era criança, falava como criança, sentia como criança e pensava como criança. Agora que sou adulto, parei de agir como criança.

[[v46-13-12]]

^<<v46-13-12,12>>^ O que agora vemos é como uma imagem imperfeita num espelho embaçado, mas depois veremos face a face. Agora o meu conhecimento é imperfeito, mas depois conhecerei perfeitamente, assim como sou conhecido por Deus.

[[v46-13-13]]

^<<v46-13-13,13>>^ Portanto, agora existem estas três coisas: a fé, a esperança e o amor. Porém a maior delas é o amor.

'''

xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[&#60; Capítulo Anterior] | <<v46-13-0,Topo>> | xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[Próximo Capítulo &#62;]