include::./index.adoc[]

[[v46-7-0]]
=== 1 Coríntios, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-7-1]]

^<<v46-7-1,1>>^ Agora vou tratar dos assuntos a respeito dos quais vocês me escreveram. Vocês dizem que o homem faz bem em não casar.

[[v46-7-2]]

^<<v46-7-2,2>>^ Mas eu digo: já que existe tanta imoralidade sexual, cada homem deve ter a sua própria esposa, e cada mulher, o seu próprio marido.

[[v46-7-3]]

^<<v46-7-3,3>>^ O homem deve cumprir o seu dever como marido, e a mulher também deve cumprir o seu dever como esposa.

[[v46-7-4]]

^<<v46-7-4,4>>^ A esposa não manda no seu próprio corpo; quem manda é o seu marido. Assim também o marido não manda no seu próprio corpo; quem manda é a sua esposa.

[[v46-7-5]]

^<<v46-7-5,5>>^ Que os dois não se neguem um ao outro, a não ser que concordem em não ter relações por algum tempo a fim de se dedicar à oração. Mas depois devem voltar a ter relações, a fim de não caírem nas tentações de Satanás por não poderem se dominar.

[[v46-7-6]]

^<<v46-7-6,6>>^ Não digo isso como uma ordem, mas como uma sugestão.

[[v46-7-7]]

^<<v46-7-7,7>>^ Realmente, eu gostaria que todos fossem como eu. Porém cada um tem o dom  que Deus lhe deu: um tem este dom, e outro, aquele.

[[v46-7-8]]

^<<v46-7-8,8>>^ Aos solteiros e às viúvas eu digo que seria melhor para eles ficarem sem casar, como eu.

[[v46-7-9]]

^<<v46-7-9,9>>^ Mas, se vocês não podem dominar o desejo sexual, então casem, pois é melhor casar do que ficar queimando de desejo.

[[v46-7-10]]

^<<v46-7-10,10>>^ Para os que já estão casados tenho um mandamento, que não é meu, mas do Senhor: que a mulher não se separe do seu marido.

[[v46-7-11]]

^<<v46-7-11,11>>^ Porém, se ela se separar, que não case de novo ou então que faça as pazes com o marido. E que o homem não se divorcie da sua esposa.

[[v46-7-12]]

^<<v46-7-12,12>>^ Aos outros digo eu mesmo, e não o Senhor: se um homem cristão é casado com uma mulher que não é cristã, e ela concorda em continuar vivendo com ele, que ele não se divorcie dela.

[[v46-7-13]]

^<<v46-7-13,13>>^ E, se uma mulher cristã é casada com um homem que não é cristão, e ele concorda em continuar vivendo com ela, que ela não se divorcie dele.

[[v46-7-14]]

^<<v46-7-14,14>>^ Pois Deus aceita o homem que não é cristão por ele estar unido com a sua esposa cristã; e aceita a mulher que não é cristã por ela estar unida com o seu marido cristão. Se não fosse assim, os filhos deles não pertenceriam a Deus. Mas, sendo assim, eles pertencem.

[[v46-7-15]]

^<<v46-7-15,15>>^ Porém, se o marido não cristão ou a esposa não cristã quiser o divórcio, então que se divorcie. Nesses casos o marido cristão ou a esposa cristã está livre para fazer como quiser, pois Deus chamou  vocês para viverem em paz.

[[v46-7-16]]

^<<v46-7-16,16>>^ Esposa cristã, como é que você pode ter a certeza de que não vai salvar o seu marido? E você, marido cristão, como é que você pode ter a certeza de que não vai salvar a sua esposa?

[[v46-7-17]]

^<<v46-7-17,17>>^ Cada um deve continuar vivendo de acordo com o dom  que o Senhor lhe deu e na condição em que se encontrava quando Deus o chamou . É essa a regra que eu ensino em todas as igrejas.

[[v46-7-18]]

^<<v46-7-18,18>>^ Se um homem judeu, que é circuncidado , aceita o chamado de Deus, ele não deve tirar as marcas da circuncisão. E, se um homem não judeu, que não é circuncidado, aceita o chamado de Deus, ele não deve circuncidar-se.

[[v46-7-19]]

^<<v46-7-19,19>>^ Não faz diferença estar circuncidado ou não; o que importa é obedecer aos mandamentos de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Cada um deve continuar como era quando aceitou o chamado de Deus.

[[v46-7-21]]

^<<v46-7-21,21>>^ Você era escravo quando Deus o chamou? Não se preocupe com isso. Mas, se você pode se tornar livre, então aproveite a oportunidade.

[[v46-7-22]]

^<<v46-7-22,22>>^ Pois o escravo que foi chamado pelo Senhor é agora um homem livre que pertence ao Senhor. Assim também o homem livre que foi chamado por Cristo é escravo de Cristo.

[[v46-7-23]]

^<<v46-7-23,23>>^ Deus comprou vocês por um preço; portanto, não se tornem escravos de seres humanos.

[[v46-7-24]]

^<<v46-7-24,24>>^ Irmãos, cada um deve continuar na presença de Deus assim como era quando Deus o chamou.

[[v46-7-25]]

^<<v46-7-25,25>>^ Para os solteiros, eu não tenho nenhum mandamento do Senhor; porém dou a minha opinião como uma pessoa que, pela misericórdia do Senhor, merece confiança.

[[v46-7-26]]

^<<v46-7-26,26>>^ Por causa dos tempos difíceis em que vivemos, eu penso que é melhor para o homem ficar como está.

[[v46-7-27]]

^<<v46-7-27,27>>^ Você tem esposa? Então não procure se separar dela. Você é solteiro? Então não procure esposa.

[[v46-7-28]]

^<<v46-7-28,28>>^ Porém, se você casar, não estará cometendo pecado. E, se uma moça solteira casar, também não estará cometendo pecado. Mas eu gostaria de poupar vocês dos problemas de cada dia que terão na vida de casados.

[[v46-7-29]]

^<<v46-7-29,29>>^ Irmãos, o que eu quero dizer é isto: não nos resta muito tempo, e daqui em diante os casados devem viver como se não tivessem casado;

[[v46-7-30]]

^<<v46-7-30,30>>^ os que choram, como se não estivessem chorando; os que estão rindo, como se não estivessem rindo; os que compram, como se não fosse deles aquilo que compraram;

[[v46-7-31]]

^<<v46-7-31,31>>^ os que tratam das coisas deste mundo, como se não estivessem ocupados com elas. Pois este mundo, como está agora, não vai durar muito.

[[v46-7-32]]

^<<v46-7-32,32>>^ Eu quero livrá-los de preocupações. O solteiro se interessa pelas coisas do Senhor porque quer agradá-lo.

[[v46-7-33]]

^<<v46-7-33,33>>^ Mas o homem casado se interessa pelas coisas deste mundo porque quer agradar a sua esposa

[[v46-7-34]]

^<<v46-7-34,34>>^ e por isso é puxado para duas direções diferentes. Quanto às mulheres, tanto as viúvas quanto as solteiras, elas estão interessadas nas coisas do Senhor porque querem se dedicar de corpo e alma a ele. Mas a mulher casada se interessa pelas coisas deste mundo porque quer agradar o marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ Eu estou dizendo isso porque quero ajudá-los. Não estou querendo obrigar ninguém a nada. Pelo contrário, quero que façam o que é direito e certo e que se entreguem ao serviço do Senhor com toda a dedicação.

[[v46-7-36]]

^<<v46-7-36,36>>^ Aos que ficaram noivos, mas resolveram não casar mais, eu digo o seguinte: se o rapaz sente que assim não está agindo certo com a sua noiva e acha que a sua paixão por ela ainda é muito forte e que devem casar, então que casem. Não existe pecado nisso.

[[v46-7-37]]

^<<v46-7-37,37>>^ Mas se, pelo contrário, o rapaz não se sente na obrigação de casar, se está mesmo resolvido a ficar solteiro e se é capaz de dominar a sua vontade e já resolveu o que deve fazer, então faz bem em não casar com a moça.

[[v46-7-38]]

^<<v46-7-38,38>>^ Assim quem casa faz bem, mas quem não casa faz melhor ainda.

[[v46-7-39]]

^<<v46-7-39,39>>^ A mulher não está livre enquanto o seu marido estiver vivo. Caso o marido morra, ela fica livre para casar com quem quiser, contanto que case com um cristão.

[[v46-7-40]]

^<<v46-7-40,40>>^ Porém ela será mais feliz se ficar como está. Essa é a minha opinião, e eu acho que também tenho o Espírito de Deus.

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]