include::./index.adoc[]

[[v46-2-0]]
=== 1 Coríntios, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-2-1]]

^<<v46-2-1,1>>^ Meus irmãos, quando fui anunciar a vocês a verdade secreta de Deus, não usei muitas palavras nem grande sabedoria.

[[v46-2-2]]

^<<v46-2-2,2>>^ Porque, quando estive com vocês, resolvi esquecer tudo, a não ser Jesus Cristo e principalmente a sua morte na cruz.

[[v46-2-3]]

^<<v46-2-3,3>>^ Quando visitei vocês, eu estava fraco e tremia de medo.

[[v46-2-4]]

^<<v46-2-4,4>>^ O meu ensinamento e a minha mensagem não foram dados com a linguagem da sabedoria humana, mas com provas firmes do poder do Espírito de Deus.

[[v46-2-5]]

^<<v46-2-5,5>>^ Portanto, a fé que vocês têm não se baseia na sabedoria humana, mas no poder de Deus.

[[v46-2-6]]

^<<v46-2-6,6>>^ Porém, para os que são espiritualmente maduros, anunciamos uma mensagem de sabedoria. Mas não é de uma sabedoria deste mundo nem a dos poderes que o governam e que estão perdendo o seu poder.

[[v46-2-7]]

^<<v46-2-7,7>>^ A sabedoria que anunciamos é a sabedoria secreta de Deus, escondida dos seres humanos, a sabedoria que o próprio Deus, antes mesmo da criação do mundo, já havia escolhido para a nossa glória .

[[v46-2-8]]

^<<v46-2-8,8>>^ Nenhum dos poderes que agora governam o mundo conheceu essa sabedoria. Pois, se a tivessem conhecido, não teriam crucificado o glorioso  Senhor.

[[v46-2-9]]

^<<v46-2-9,9>>^ Porém, como dizem as Escrituras Sagradas : "O que ninguém nunca viu nem ouviu, e o que jamais alguém pensou que podia acontecer, foi isso o que Deus preparou para aqueles que o amam."

[[v46-2-10]]

^<<v46-2-10,10>>^ Mas foi a nós que Deus, por meio do Espírito, revelou o seu segredo. O Espírito Santo examina tudo, até mesmo os planos mais profundos e escondidos de Deus.

[[v46-2-11]]

^<<v46-2-11,11>>^ Quanto ao ser humano, somente o espírito que está nele é que conhece tudo a respeito dele. E, quanto a Deus, somente o seu próprio Espírito conhece tudo a respeito dele.

[[v46-2-12]]

^<<v46-2-12,12>>^ Não foi o espírito deste mundo que nós recebemos, mas o Espírito mandado por Deus, para que possamos entender tudo o que Deus nos tem dado.

[[v46-2-13]]

^<<v46-2-13,13>>^ Portanto, quando falamos, nós usamos palavras ensinadas pelo Espírito de Deus e não palavras ensinadas pela sabedoria humana. Assim explicamos as verdades espirituais aos que são espirituais.

[[v46-2-14]]

^<<v46-2-14,14>>^ Mas quem não tem o Espírito de Deus não pode receber os dons  que vêm do Espírito e, de fato, nem mesmo pode entendê-los. Essas verdades são loucura para essa pessoa porque o sentido delas só pode ser entendido de modo espiritual.

[[v46-2-15]]

^<<v46-2-15,15>>^ A pessoa que tem o Espírito Santo pode julgar o valor de todas as coisas, porém ela mesma não pode ser julgada por ninguém.

[[v46-2-16]]

^<<v46-2-16,16>>^ Como dizem as Escrituras Sagradas: "Quem pode conhecer a mente do Senhor? Quem é capaz de lhe dar conselhos?" Mas nós pensamos como Cristo pensa.

'''

xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[&#60; Capítulo Anterior] | <<v46-2-0,Topo>> | xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[Próximo Capítulo &#62;]