include::./index.adoc[]

[[v46-1-0]]
=== 1 Coríntios, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-1-1]]

^<<v46-1-1,1>>^ Eu, Paulo, que fui chamado pela vontade de Deus para ser apóstolo  de Cristo Jesus, escrevo, junto com o irmão Sóstenes, esta carta à igreja de Deus que está na cidade de Corinto. Escrevo a todos os que, pela sua união com Cristo Jesus, foram chamados para pertencerem ao povo de Deus. Esta carta é também para aqueles que em todos os lugares adoram o nosso Senhor Jesus Cristo, Senhor deles e nosso.

[[v46-1-2]]

^<<v46-1-2,2>>^ Eu, Paulo, que fui chamado pela vontade de Deus para ser apóstolo  de Cristo Jesus, escrevo, junto com o irmão Sóstenes, esta carta à igreja de Deus que está na cidade de Corinto. Escrevo a todos os que, pela sua união com Cristo Jesus, foram chamados para pertencerem ao povo de Deus. Esta carta é também para aqueles que em todos os lugares adoram o nosso Senhor Jesus Cristo, Senhor deles e nosso.

[[v46-1-3]]

^<<v46-1-3,3>>^ Que a graça  e a paz de Deus, o nosso Pai, e do Senhor Jesus Cristo estejam com vocês!

[[v46-1-4]]

^<<v46-1-4,4>>^ Eu sempre agradeço ao meu Deus por causa da graça  que ele tem dado a vocês por meio de Cristo Jesus.

[[v46-1-5]]

^<<v46-1-5,5>>^ Por estarem unidos com Cristo Jesus, vocês foram enriquecidos em tudo, tanto no dom  de anunciar o evangelho  como no dom da sabedoria espiritual.

[[v46-1-6]]

^<<v46-1-6,6>>^ A mensagem a respeito de Cristo está tão firme em vocês,

[[v46-1-7]]

^<<v46-1-7,7>>^ que vocês não têm deixado de receber nenhum dom espiritual enquanto esperam a vinda do nosso Senhor Jesus Cristo.

[[v46-1-8]]

^<<v46-1-8,8>>^ Cristo vai conservá-los firmes até o fim para que no dia da volta do nosso Senhor Jesus Cristo vocês não tenham culpa de nada.

[[v46-1-9]]

^<<v46-1-9,9>>^ Deus é fiel e chamou  vocês para que vivam em união com o seu Filho Jesus Cristo, o nosso Senhor.

[[v46-1-10]]

^<<v46-1-10,10>>^ Irmãos, peço, pela autoridade do nosso Senhor Jesus Cristo, que vocês estejam de acordo no que dizem e que não haja divisões entre vocês. Sejam completamente unidos num só pensamento e numa só intenção.

[[v46-1-11]]

^<<v46-1-11,11>>^ Pois, meus irmãos, algumas pessoas da família de Cloé me contaram que há brigas entre vocês.

[[v46-1-12]]

^<<v46-1-12,12>>^ O que eu quero dizer é isto: cada um de vocês diz uma coisa diferente. Um diz: "Eu sou de Paulo"; outro, "Eu sou de Apolo"; outro, "Eu sou de Pedro"; e ainda outro, "Eu sou de Cristo".

[[v46-1-13]]

^<<v46-1-13,13>>^ Por acaso Cristo foi dividido em várias partes? Será que Paulo morreu crucificado em favor de vocês? Ou será que vocês foram batizados em nome de Paulo?

[[v46-1-14]]

^<<v46-1-14,14>>^ Graças a Deus que eu não batizei nenhum de vocês, a não ser Crispo e Gaio.

[[v46-1-15]]

^<<v46-1-15,15>>^ Assim ninguém pode dizer que vocês foram batizados em meu nome.

[[v46-1-16]]

^<<v46-1-16,16>>^ (Ah! Sim. Batizei também Estéfanas e a família dele, mas não lembro de ter batizado mais ninguém.)

[[v46-1-17]]

^<<v46-1-17,17>>^ Pois Cristo não me enviou para batizar, mas para anunciar o evangelho  e anunciá-lo sem usar a linguagem da sabedoria humana, para não tirar o poder da morte de Cristo na cruz.

[[v46-1-18]]

^<<v46-1-18,18>>^ De fato, a mensagem da morte de Cristo na cruz é loucura para os que estão se perdendo; mas para nós, que estamos sendo salvos, é o poder de Deus.

[[v46-1-19]]

^<<v46-1-19,19>>^ Pois as Escrituras Sagradas  dizem: "Destruirei a sabedoria dos sábios e acabarei com o conhecimento dos instruídos."

[[v46-1-20]]

^<<v46-1-20,20>>^ Então, o que poderão dizer os sábios e os instruídos? O que vão dizer os grandes oradores deste mundo? Deus tem mostrado que a sabedoria deste mundo é loucura.

[[v46-1-21]]

^<<v46-1-21,21>>^ Pois Deus, na sua sabedoria, não deixou que os seres humanos o conhecessem por meio da sabedoria deles. Pelo contrário, resolveu salvar aqueles que creem e fez isso por meio da mensagem que anunciamos, a qual é chamada de "louca".

[[v46-1-22]]

^<<v46-1-22,22>>^ Os judeus pedem milagres como prova, e os não judeus procuram a sabedoria.

[[v46-1-23]]

^<<v46-1-23,23>>^ Mas nós anunciamos o Cristo crucificado — uma mensagem que para os judeus é ofensa e para os não judeus é loucura.

[[v46-1-24]]

^<<v46-1-24,24>>^ Mas para aqueles que Deus tem chamado, tanto judeus como não judeus, Cristo é o poder de Deus e a sabedoria de Deus.

[[v46-1-25]]

^<<v46-1-25,25>>^ Pois aquilo que parece ser a loucura de Deus é mais sábio do que a sabedoria humana, e aquilo que parece ser a fraqueza de Deus é mais forte do que a força humana.

[[v46-1-26]]

^<<v46-1-26,26>>^ Agora, meus irmãos, lembrem do que vocês eram quando Deus os chamou. Do ponto de vista humano poucos de vocês eram sábios ou poderosos ou de famílias importantes.

[[v46-1-27]]

^<<v46-1-27,27>>^ Para envergonhar os sábios, Deus escolheu aquilo que o mundo acha que é loucura; e, para envergonhar os poderosos, ele escolheu o que o mundo acha fraco.

[[v46-1-28]]

^<<v46-1-28,28>>^ Para destruir o que o mundo pensa que é importante, Deus escolheu aquilo que o mundo despreza, acha humilde e diz que não tem valor.

[[v46-1-29]]

^<<v46-1-29,29>>^ Isso quer dizer que ninguém pode ficar orgulhoso, pois sabe que está sendo visto por Deus.

[[v46-1-30]]

^<<v46-1-30,30>>^ Porém Deus uniu vocês com Cristo Jesus e fez com que Cristo seja a nossa sabedoria. E é por meio de Cristo que somos aceitos por Deus, nos tornamos o povo de Deus e somos salvos.

'''

xref:045-romanos/045-romanos-016.adoc#v45-16-0[&#60; Capítulo Anterior] | <<v46-1-0,Topo>> | xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[Próximo Capítulo &#62;]