include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-14-1]]

^<<v46-14-1,1>>^ Portanto, esforcem-se para ter amor. Procurem também ter dons  espirituais, especialmente o de anunciar a mensagem de Deus.

[[v46-14-2]]

^<<v46-14-2,2>>^ Quem fala em línguas estranhas fala a Deus e não às pessoas, pois ninguém o entende. Pelo poder do Espírito Santo ele diz verdades secretas.

[[v46-14-3]]

^<<v46-14-3,3>>^ Porém quem anuncia a mensagem de Deus fala para as pessoas, ajudando-as e dando-lhes coragem e consolo.

[[v46-14-4]]

^<<v46-14-4,4>>^ Quem fala em línguas estranhas ajuda somente a si mesmo, mas quem anuncia a mensagem de Deus ajuda a igreja toda.

[[v46-14-5]]

^<<v46-14-5,5>>^ Eu gostaria que vocês todos falassem em línguas estranhas, mas gostaria ainda mais que tivessem o dom de anunciar a mensagem de Deus. Porque quem anuncia a mensagem de Deus tem mais valor do que quem fala em línguas estranhas, a não ser que esteja ali alguém que possa interpretar o que está sendo dito, para que toda a igreja seja ajudada espiritualmente.

[[v46-14-6]]

^<<v46-14-6,6>>^ Por isso, irmãos, quando eu os visitar, que proveito vocês terão se eu lhes falar em línguas estranhas? É claro que nenhum, a não ser que leve a vocês alguma revelação de Deus, ou algum conhecimento, ou alguma mensagem inspirada, ou algum ensinamento.

[[v46-14-7]]

^<<v46-14-7,7>>^ Por exemplo, além da voz humana, existem os instrumentos musicais, como a flauta e a harpa . Se os sons não saírem com toda a clareza, como poderá alguém saber o que está sendo tocado em um ou outro desses instrumentos?

[[v46-14-8]]

^<<v46-14-8,8>>^ Se quem toca a corneta não der um som bem claro, quem se preparará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Assim, também, como é que os outros vão entender o que vocês estão dizendo se a mensagem por meio de línguas estranhas não for clara? Vocês estariam falando para o vento!

[[v46-14-10]]

^<<v46-14-10,10>>^ No mundo há muitas línguas diferentes, mas cada uma faz sentido.

[[v46-14-11]]

^<<v46-14-11,11>>^ Porém, se eu não entendo a língua na qual alguém está falando comigo, então quem fala essa língua é estrangeiro para mim, e eu sou um estrangeiro para ele.

[[v46-14-12]]

^<<v46-14-12,12>>^ Por isso, já que vocês estão com tanta vontade de ter os dons do Espírito, procurem acima de tudo ter os dons que fazem com que a igreja cresça espiritualmente.

[[v46-14-13]]

^<<v46-14-13,13>>^ Portanto, quem fala em línguas estranhas deve orar pedindo a Deus que lhe dê o dom de interpretar o que elas querem dizer.

[[v46-14-14]]

^<<v46-14-14,14>>^ Porque, se eu orar em línguas estranhas, o meu espírito, de fato, estará orando, mas a minha inteligência não tomará parte nisso.

[[v46-14-15]]

^<<v46-14-15,15>>^ O que vou fazer, então? Vou orar com o meu espírito, mas também vou orar com a minha inteligência; vou cantar com o meu espírito, mas também vou cantar com a minha inteligência.

[[v46-14-16]]

^<<v46-14-16,16>>^ Se você dá graças a Deus em línguas estranhas, como é que uma pessoa simples, que estiver na reunião, poderá dizer " amém " à oração de agradecimento que você fez? Ela não vai conseguir entender nada do que você está dizendo.

[[v46-14-17]]

^<<v46-14-17,17>>^ Mesmo que a sua oração seja muito boa, essa pessoa não receberá nenhuma ajuda.

[[v46-14-18]]

^<<v46-14-18,18>>^ Eu agradeço a Deus porque falo em línguas estranhas muito mais do que vocês.

[[v46-14-19]]

^<<v46-14-19,19>>^ Porém nas reuniões da igreja prefiro dizer cinco palavras que possam ser entendidas, para assim ensinar os outros, do que dizer milhares de palavras em línguas estranhas.

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não pensem como crianças. Sejam como crianças para o que é mau, mas sejam adultos no seu modo de pensar.

[[v46-14-21]]

^<<v46-14-21,21>>^ Nas Escrituras Sagradas  está escrito: "Por meio de pessoas que falam em línguas estranhas eu falarei a este povo — diz o Senhor. — Falarei por meio de lábios estrangeiros, mas assim mesmo o meu povo não me dará atenção."

[[v46-14-22]]

^<<v46-14-22,22>>^ Portanto, o dom de falar em línguas estranhas é um sinal de Deus para os descrentes e não para os cristãos. Mas o dom de anunciar a mensagem de Deus é um sinal para os cristãos e não para os descrentes.

[[v46-14-23]]

^<<v46-14-23,23>>^ Imaginem que a igreja esteja reunida e todos comecem a falar em línguas estranhas. Se chegarem ali algumas pessoas simples ou descrentes, será que não vão dizer que vocês estão loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Mas, se todos estiverem anunciando mensagens de Deus, e entrar ali um descrente ou alguém que seja simples, ele vai ouvir o que vocês estão dizendo e se convencer do seu pecado. E ele será julgado pelo que ouvir,

[[v46-14-25]]

^<<v46-14-25,25>>^ os seus pensamentos secretos serão revelados, e ele vai se ajoelhar e adorar a Deus, dizendo: "Deus está mesmo no meio de vocês!"

[[v46-14-26]]

^<<v46-14-26,26>>^ Portanto, meus irmãos, o que é que deve ser feito? Quando vocês se reúnem na igreja, um irmão tem um hino para cantar; outro, alguma coisa para ensinar; outro, uma revelação de Deus; outro, uma mensagem em línguas estranhas ; e ainda outro, a interpretação dessa mensagem. Que tudo seja feito para o crescimento espiritual da igreja.

[[v46-14-27]]

^<<v46-14-27,27>>^ Se algum de vocês falar em línguas estranhas, então que apenas dois ou três falem, um depois do outro, e que alguém interprete o que está sendo dito.

[[v46-14-28]]

^<<v46-14-28,28>>^ Mas, se não houver ninguém que possa interpretar, então fiquem calados e falem somente consigo mesmos e com Deus.

[[v46-14-29]]

^<<v46-14-29,29>>^ No caso de dois ou três receberem a mensagem de Deus, estes devem falar, e os outros que pensem bem no que eles estão dizendo.

[[v46-14-30]]

^<<v46-14-30,30>>^ Se uma outra pessoa que estiver ali sentada receber a mensagem de Deus, quem estiver falando deve se calar.

[[v46-14-31]]

^<<v46-14-31,31>>^ Vocês todos podem anunciar a mensagem de Deus, um de cada vez, para que todos aprendam e fiquem animados.

[[v46-14-32]]

^<<v46-14-32,32>>^ Quem fala deve controlar o dom  de anunciar a mensagem de Deus,

[[v46-14-33]]

^<<v46-14-33,33>>^ pois Deus não quer que nós vivamos em desordem e sim em paz. Como em todas as igrejas do povo de Deus,

[[v46-14-34]]

^<<v46-14-34,34>>^ as mulheres devem ficar caladas nas reuniões de adoração. Elas não têm permissão para falar. Como diz a Lei , elas não devem ter cargos de direção.

[[v46-14-35]]

^<<v46-14-35,35>>^ Se quiserem saber alguma coisa, que perguntem em casa ao marido. É vergonhoso que uma mulher fale nas reuniões da igreja.

[[v46-14-36]]

^<<v46-14-36,36>>^ Por acaso a mensagem de Deus veio de vocês? Ou será que veio somente para vocês?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém pensa que é mensageiro de Deus ou que tem algum dom espiritual, deve saber que o que estou escrevendo é mandamento do Senhor.

[[v46-14-38]]

^<<v46-14-38,38>>^ Mas, se alguém não der atenção a isso, que ninguém dê atenção a essa pessoa.

[[v46-14-39]]

^<<v46-14-39,39>>^ Assim, meus irmãos, procurem sempre anunciar a mensagem de Deus, mas não proíbam que se fale em línguas estranhas.

[[v46-14-40]]

^<<v46-14-40,40>>^ Portanto, façam tudo com decência e ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]