include::./index.adoc[]

[[v46-6-0]]
=== 1 Coríntios, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-6-1]]

^<<v46-6-1,1>>^ Quando algum de vocês tem uma queixa contra um irmão na fé, como se atreve a pedir justiça a juízes pagãos, em vez de pedir ao povo de Deus que resolva o caso?

[[v46-6-2]]

^<<v46-6-2,2>>^ Será que vocês não sabem que o povo de Deus julgará o mundo? Então, se vocês vão julgar o mundo, será que não são capazes de julgar essas coisas pequenas?

[[v46-6-3]]

^<<v46-6-3,3>>^ Por acaso vocês não sabem que nós julgaremos até mesmo os anjos? Muito mais, então, devemos julgar as coisas desta vida!

[[v46-6-4]]

^<<v46-6-4,4>>^ Portanto, se surgir alguma questão dessas, será que vocês vão procurar pessoas que são desprezadas na igreja para julgarem esses casos?

[[v46-6-5]]

^<<v46-6-5,5>>^ Que vergonha! Será que entre vocês não existe alguém com bastante sabedoria para resolver uma questão entre irmãos?

[[v46-6-6]]

^<<v46-6-6,6>>^ É claro que existe. Mas o que acontece é que um irmão em Cristo leva ao tribunal a sua queixa contra outro irmão e deixa que juízes pagãos julguem o caso.

[[v46-6-7]]

^<<v46-6-7,7>>^ Só o fato de existirem questões entre vocês já mostra que vocês estão falhando completamente. Não seria melhor aguentar a injustiça? Não seria melhor ficar com o prejuízo?

[[v46-6-8]]

^<<v46-6-8,8>>^ Pelo contrário, vocês cometem injustiça, e roubam, e fazem isso tudo contra os seus próprios irmãos!

[[v46-6-9]]

^<<v46-6-9,9>>^ Vocês sabem que os maus não terão parte no Reino de Deus . Não se enganem, pois os imorais, os que adoram ídolos, os adúlteros, os homossexuais,

[[v46-6-10]]

^<<v46-6-10,10>>^ os ladrões, os avarentos, os bêbados, os caluniadores e os assaltantes não terão parte no Reino de Deus.

[[v46-6-11]]

^<<v46-6-11,11>>^ Alguns de vocês eram assim. Mas foram lavados do pecado, separados para pertencer a Deus e aceitos por ele por meio do Senhor Jesus Cristo e pelo Espírito do nosso Deus.

[[v46-6-12]]

^<<v46-6-12,12>>^ Alguém vai dizer: "Eu posso fazer tudo o que quero." Pode, sim, mas nem tudo é bom para você. Eu poderia dizer: "Posso fazer qualquer coisa." Mas não vou deixar que nada me escravize.

[[v46-6-13]]

^<<v46-6-13,13>>^ Outro vai dizer: "O alimento existe para o estômago, e o estômago existe para o alimento." Sim, mas Deus acabará com os dois. O nosso corpo não existe para praticar a imoralidade, mas para servir o Senhor; e o Senhor cuida do nosso corpo.

[[v46-6-14]]

^<<v46-6-14,14>>^ Pelo seu poder Deus ressuscitou o Senhor e também nos ressuscitará a nós.

[[v46-6-15]]

^<<v46-6-15,15>>^ Será que vocês não sabem que o corpo de vocês faz parte do corpo de Cristo? Será que eu vou pegar uma parte do corpo de Cristo e fazer com que ela seja parte do corpo de uma prostituta? É claro que não!

[[v46-6-16]]

^<<v46-6-16,16>>^ Ou será que vocês não sabem que o homem que se une com uma prostituta se torna uma só pessoa com ela? As Escrituras Sagradas  afirmam: "Os dois se tornam uma só pessoa."

[[v46-6-17]]

^<<v46-6-17,17>>^ Porém quem se une com o Senhor se torna, espiritualmente, uma só pessoa com ele.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fujam da imoralidade sexual! Qualquer outro pecado que alguém comete não afeta o corpo, mas a pessoa que comete imoralidade sexual peca contra o seu próprio corpo.

[[v46-6-19]]

^<<v46-6-19,19>>^ Será que vocês não sabem que o corpo de vocês é o templo do Espírito Santo, que vive em vocês e lhes foi dado por Deus? Vocês não pertencem a vocês mesmos, mas a Deus,

[[v46-6-20]]

^<<v46-6-20,20>>^ pois ele os comprou e pagou o preço. Portanto, usem o seu corpo para a glória  dele.

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]