include::./index.adoc[]

[[v46-11-0]]
=== 1 Coríntios, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-11-1]]

^<<v46-11-1,1>>^ Sigam o meu exemplo como eu sigo o exemplo de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ Eu os elogio porque vocês sempre lembram de mim e seguem as instruções que eu passei para vocês.

[[v46-11-3]]

^<<v46-11-3,3>>^ Mas quero que entendam que Cristo tem autoridade sobre todo marido, que o marido tem autoridade sobre a esposa e que Deus tem autoridade sobre Cristo.

[[v46-11-4]]

^<<v46-11-4,4>>^ Se um homem cobre a cabeça quando ora ou anuncia a mensagem de Deus nas reuniões de adoração, ele está ofendendo a honra de Cristo.

[[v46-11-5]]

^<<v46-11-5,5>>^ E, se uma mulher não cobre a cabeça quando ora ou anuncia a mensagem de Deus nas reuniões de adoração, ela está ofendendo a honra do seu marido. Nesse caso, não há nenhuma diferença entre ela e a mulher que tem a cabeça rapada .

[[v46-11-6]]

^<<v46-11-6,6>>^ Se a mulher não cobre a cabeça, então é melhor que ela corte o cabelo de uma vez. Já que é vergonhoso para a mulher rapar a cabeça ou cortar o cabelo, então ela deve cobrir a cabeça.

[[v46-11-7]]

^<<v46-11-7,7>>^ O homem não precisa cobrir a cabeça, pois ele reflete a imagem e a glória  de Deus. Mas a mulher reflete a glória do homem,

[[v46-11-8]]

^<<v46-11-8,8>>^ pois o homem não foi feito da mulher, mas a mulher foi feita do homem.

[[v46-11-9]]

^<<v46-11-9,9>>^ O homem não foi criado por causa da mulher, mas sim a mulher por causa do homem.

[[v46-11-10]]

^<<v46-11-10,10>>^ Portanto, por causa dos anjos , a mulher deve pôr um véu na cabeça para mostrar que está debaixo da autoridade do marido.

[[v46-11-11]]

^<<v46-11-11,11>>^ No entanto, por estarmos unidos com o Senhor, nem a mulher é independente do homem, nem o homem é independente da mulher.

[[v46-11-12]]

^<<v46-11-12,12>>^ Porque assim como a mulher foi feita do homem, assim também o homem nasce da mulher. E tudo vem de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ Julguem vocês mesmos: será que é certo que, num culto de adoração, a mulher ore a Deus sem estar com a cabeça coberta?

[[v46-11-14]]

^<<v46-11-14,14>>^ Pois a própria natureza ensina que o cabelo comprido é uma desonra para o homem,

[[v46-11-15]]

^<<v46-11-15,15>>^ mas para a mulher o cabelo comprido é motivo de orgulho. O cabelo foi dado a ela para lhe servir de véu.

[[v46-11-16]]

^<<v46-11-16,16>>^ Mas, se alguém quer discutir sobre esse assunto, o que eu posso dizer é que nem nós nem as igrejas de Deus temos outro costume nas reuniões de adoração.

[[v46-11-17]]

^<<v46-11-17,17>>^ Nas instruções que agora vou dar a vocês, eu não posso elogiá-los, pois as suas reuniões de adoração fazem mais mal do que bem.

[[v46-11-18]]

^<<v46-11-18,18>>^ Para começar, me contaram que nessas reuniões há grupos de pessoas que estão brigando, e eu creio que em parte isso é verdade.

[[v46-11-19]]

^<<v46-11-19,19>>^ Não há dúvida de que é preciso haver divisões entre vocês para que fique claro quem são os que estão certos.

[[v46-11-20]]

^<<v46-11-20,20>>^ Quando vocês se reúnem, não é a Ceia do Senhor que vocês comem.

[[v46-11-21]]

^<<v46-11-21,21>>^ Pois, na hora de comer, cada um trata de tomar a sua própria refeição . E assim, enquanto uns ficam com fome, outros chegam até a ficar bêbados.

[[v46-11-22]]

^<<v46-11-22,22>>^ Por acaso vocês não têm as suas próprias casas onde podem comer e beber? Ou será que preferem desprezar a Igreja de Deus e envergonhar os que são pobres? O que é que vocês esperam que eu lhes diga? Querem que os elogie? É claro que não vou elogiá-los!

[[v46-11-23]]

^<<v46-11-23,23>>^ Porque eu recebi do Senhor este ensinamento que passei para vocês: que o Senhor Jesus, na noite em que foi traído, pegou o pão

[[v46-11-24]]

^<<v46-11-24,24>>^ e deu graças a Deus. Depois partiu o pão e disse: "Isto é o meu corpo, que é entregue em favor de vocês. Façam isto em memória de mim."

[[v46-11-25]]

^<<v46-11-25,25>>^ Assim também, depois do jantar, ele pegou o cálice e disse: "Este cálice é a nova aliança  feita por Deus com o seu povo, aliança que é garantida pelo meu sangue. Cada vez que vocês beberem deste cálice, façam isso em memória de mim."

[[v46-11-26]]

^<<v46-11-26,26>>^ De maneira que, cada vez que vocês comem deste pão e bebem deste cálice, estão anunciando a morte do Senhor, até que ele venha.

[[v46-11-27]]

^<<v46-11-27,27>>^ Por isso aquele que comer do pão do Senhor ou beber do seu cálice de modo que ofenda a honra do Senhor estará pecando contra o corpo e o sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Portanto, que cada um examine a sua consciência e então coma do pão e beba do cálice.

[[v46-11-29]]

^<<v46-11-29,29>>^ Pois, a pessoa que comer do pão ou beber do cálice sem reconhecer que se trata do corpo do Senhor, estará sendo julgada ao comer e beber para o seu próprio castigo.

[[v46-11-30]]

^<<v46-11-30,30>>^ É por isso que muitos de vocês estão doentes e fracos, e alguns já morreram.

[[v46-11-31]]

^<<v46-11-31,31>>^ Se examinássemos primeiro a nossa consciência, nós não seríamos julgados pelo Senhor.

[[v46-11-32]]

^<<v46-11-32,32>>^ Mas somos julgados e castigados pelo Senhor, para não sermos condenados junto com o mundo.

[[v46-11-33]]

^<<v46-11-33,33>>^ Portanto, meus irmãos, quando vocês se reunirem para a Ceia do Senhor, esperem uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ E, se alguém estiver com fome, que coma em casa, para que Deus não castigue vocês por causa dessas reuniões. Os outros assuntos eu resolverei quando chegar aí.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]