include::./index.adoc[]

[[v46-12-0]]
=== 1 Coríntios, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-12-1]]

^<<v46-12-1,1>>^ Meus irmãos, quero que vocês saibam a verdade a respeito dos dons  que o Espírito Santo dá.

[[v46-12-2]]

^<<v46-12-2,2>>^ Vocês sabem que, quando ainda eram pagãos, vocês eram desviados, de várias maneiras, para a adoração dos ídolos, os quais não têm vida.

[[v46-12-3]]

^<<v46-12-3,3>>^ Por isso precisam compreender que ninguém que diz "Que Jesus seja maldito!" pode estar falando pelo poder do Espírito de Deus. E que ninguém pode dizer "Jesus é Senhor", a não ser que seja guiado pelo Espírito Santo.

[[v46-12-4]]

^<<v46-12-4,4>>^ Existem tipos diferentes de dons espirituais, mas é um só e o mesmo Espírito quem dá esses dons.

[[v46-12-5]]

^<<v46-12-5,5>>^ Existem maneiras diferentes de servir, mas o Senhor que servimos é o mesmo.

[[v46-12-6]]

^<<v46-12-6,6>>^ Há diferentes habilidades para realizar o trabalho, mas é o mesmo Deus quem dá a cada um a habilidade para fazê-lo.

[[v46-12-7]]

^<<v46-12-7,7>>^ Para o bem de todos, Deus dá a cada um alguma prova da presença do Espírito Santo.

[[v46-12-8]]

^<<v46-12-8,8>>^ Para uma pessoa o Espírito dá a mensagem de sabedoria e para outra o mesmo Espírito dá a mensagem de conhecimento.

[[v46-12-9]]

^<<v46-12-9,9>>^ Para uma pessoa o mesmo Espírito dá fé e para outra dá o poder de curar.

[[v46-12-10]]

^<<v46-12-10,10>>^ Uma pessoa recebe do Espírito poder para fazer milagres, e outra recebe o dom de anunciar a mensagem de Deus. Ainda outra pessoa recebe a capacidade para saber a diferença entre os dons que vêm do Espírito e os que não vêm dele. Para uma pessoa o Espírito dá a capacidade de falar em línguas estranhas e para outra ele dá a capacidade de interpretar o que essas línguas querem dizer.

[[v46-12-11]]

^<<v46-12-11,11>>^ Porém é um só e o mesmo Espírito quem faz tudo isso. Ele dá um dom diferente para cada pessoa, conforme ele quer.

[[v46-12-12]]

^<<v46-12-12,12>>^ Cristo é como um corpo, o qual tem muitas partes. E todas as partes, mesmo sendo muitas, formam um só corpo.

[[v46-12-13]]

^<<v46-12-13,13>>^ Assim, também, todos nós, judeus e não judeus, escravos e livres, fomos batizados pelo mesmo Espírito para formar um só corpo. E a todos nós foi dado de beber do mesmo Espírito.

[[v46-12-14]]

^<<v46-12-14,14>>^ Pois o corpo não é feito de uma só parte, mas de muitas.

[[v46-12-15]]

^<<v46-12-15,15>>^ Se o pé disser: "Já que não sou mão, não sou do corpo", nem por isso deixa de ser do corpo.

[[v46-12-16]]

^<<v46-12-16,16>>^ Se o ouvido disser: "Já que não sou olho, não sou do corpo", nem por isso deixa de ser do corpo.

[[v46-12-17]]

^<<v46-12-17,17>>^ Se o corpo todo fosse olho, como poderíamos ouvir? E, se o corpo todo fosse ouvido, como poderíamos cheirar?

[[v46-12-18]]

^<<v46-12-18,18>>^ Assim Deus colocou cada parte diferente do corpo conforme ele quis.

[[v46-12-19]]

^<<v46-12-19,19>>^ Se o corpo todo fosse uma parte só, não existiria corpo.

[[v46-12-20]]

^<<v46-12-20,20>>^ De fato, existem muitas partes, mas um só corpo.

[[v46-12-21]]

^<<v46-12-21,21>>^ Portanto, o olho não pode dizer para a mão: "Eu não preciso de você." E a cabeça não pode dizer para os pés: "Não preciso de vocês."

[[v46-12-22]]

^<<v46-12-22,22>>^ O fato é que as partes do corpo que parecem ser as mais fracas são as mais necessárias,

[[v46-12-23]]

^<<v46-12-23,23>>^ e aquelas que achamos menos honrosas são as que tratamos com mais honra. E as partes que parecem ser feias recebem um cuidado especial,

[[v46-12-24]]

^<<v46-12-24,24>>^ que as outras mais bonitas não precisam. Foi assim que Deus fez o corpo, dando mais honra às partes menos honrosas.

[[v46-12-25]]

^<<v46-12-25,25>>^ Desse modo não existe divisão no corpo, mas todas as suas partes têm o mesmo interesse umas pelas outras.

[[v46-12-26]]

^<<v46-12-26,26>>^ Se uma parte do corpo sofre, todas as outras sofrem com ela. Se uma é elogiada, todas as outras se alegram com ela.

[[v46-12-27]]

^<<v46-12-27,27>>^ Pois bem, vocês são o corpo de Cristo, e cada um é uma parte desse corpo.

[[v46-12-28]]

^<<v46-12-28,28>>^ Na Igreja, Deus pôs tudo no lugar certo: em primeiro lugar, os apóstolos ; em segundo, os profetas ; e, em terceiro, os mestres. Em seguida pôs os que fazem milagres; depois os que têm o dom  de curar, ou de ajudar, ou de liderar, ou de falar em línguas estranhas.

[[v46-12-29]]

^<<v46-12-29,29>>^ Nem todos são apóstolos, ou profetas, ou mestres. Nem todos têm o dom de fazer milagres,

[[v46-12-30]]

^<<v46-12-30,30>>^ nem de curar doenças, nem de falar em línguas estranhas, nem de explicar o que essas línguas querem dizer.

[[v46-12-31]]

^<<v46-12-31,31>>^ Por isso se esforcem para ter os melhores dons. Porém eu vou mostrar a vocês o caminho que é o melhor de todos.

'''

xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[&#60; Capítulo Anterior] | <<v46-12-0,Topo>> | xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[Próximo Capítulo &#62;]