include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-9-1]]

^<<v46-9-1,1>>^ Será que eu não sou um homem livre? Por acaso não sou um apóstolo ? Será que eu não vi Jesus, o nosso Senhor? Por acaso vocês não são o resultado do trabalho que faço para o Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Mesmo que outros não me aceitem como apóstolo, vocês me aceitam! Vocês mesmos, pelo fato de estarem unidos com o Senhor, são a prova de que sou um apóstolo.

[[v46-9-3]]

^<<v46-9-3,3>>^ Quando as pessoas me criticam, eu me defendo, dizendo assim:

[[v46-9-4]]

^<<v46-9-4,4>>^ Será que eu não tenho o direito de receber comida e bebida pelo meu trabalho?

[[v46-9-5]]

^<<v46-9-5,5>>^ Será que nas minhas viagens eu não tenho o direito de levar comigo uma esposa cristã, como fazem os outros apóstolos, os irmãos do Senhor Jesus e também Pedro?

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou será que Barnabé e eu somos os únicos que temos de trabalhar para nos sustentar?

[[v46-9-7]]

^<<v46-9-7,7>>^ Quem já ouviu falar de algum soldado que pagou as suas próprias despesas no exército? Ou qual é o fazendeiro que não come das uvas da sua própria plantação? Ou qual é o pastor que não toma do leite do seu gado?

[[v46-9-8]]

^<<v46-9-8,8>>^ Não pensem que eu me apoio somente nesses exemplos da vida diária, pois a lei  diz a mesma coisa.

[[v46-9-9]]

^<<v46-9-9,9>>^ Na Lei de Moisés está escrito assim: "Não amarre a boca do boi quando ele estiver pisando o trigo." Por acaso Deus está interessado nos bois?

[[v46-9-10]]

^<<v46-9-10,10>>^ Ou foi a nosso respeito que ele disse isso? É claro que isso está escrito em nosso favor! Tanto a pessoa que planta como a que colhe fazem o seu trabalho na esperança de receber a sua parte da colheita.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se temos semeado entre vocês a semente espiritual, será demais se recebermos de vocês alguma recompensa material?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros têm o direito de esperar isso de vocês, será que nós não temos muito mais direito do que eles? No entanto, nós não temos usado esse direito. Pelo contrário, temos aguentado tudo para não atrapalhar o evangelho  de Cristo.

[[v46-9-13]]

^<<v46-9-13,13>>^ Certamente vocês sabem que os que trabalham no Templo é do Templo que recebem os seus alimentos. E sabem também que os que oferecem sacrifícios  no altar recebem uma parte da carne dos animais que são sacrificados ali.

[[v46-9-14]]

^<<v46-9-14,14>>^ Assim o Senhor mandou também que aqueles que anunciam o evangelho vivam do trabalho de anunciar o evangelho.

[[v46-9-15]]

^<<v46-9-15,15>>^ Mas eu não tenho usado nenhum desses direitos, nem estou escrevendo isso agora para exigir esses direitos para mim mesmo. Eu preferiria morrer a fazer isso! E ninguém vai me tirar o orgulho que eu tenho de agir assim!

[[v46-9-16]]

^<<v46-9-16,16>>^ Eu não tenho o direito de ficar orgulhoso por anunciar o evangelho. Afinal de contas, fazer isso é minha obrigação. Ai de mim se não anunciar o evangelho!

[[v46-9-17]]

^<<v46-9-17,17>>^ Por isso, se eu faço o meu trabalho por minha própria vontade, então posso esperar algum pagamento. Porém, se faço como um dever, é porque é um trabalho que Deus me deu para fazer.

[[v46-9-18]]

^<<v46-9-18,18>>^ Nesse caso, qual é o pagamento que recebo? É a satisfação de anunciar o evangelho sem cobrar nada e sem exigir os direitos que tenho como pregador do evangelho.

[[v46-9-19]]

^<<v46-9-19,19>>^ Sou um homem livre; não sou escravo de ninguém. Mas eu me fiz escravo de todos a fim de ganhar para Cristo o maior número possível de pessoas.

[[v46-9-20]]

^<<v46-9-20,20>>^ Quando trabalho entre os judeus, vivo como judeu a fim de ganhá-los para Cristo. Não estou debaixo da Lei  de Moisés; mas, quando trabalho entre os judeus, vivo como se estivesse debaixo dessa Lei para ganhar os judeus para Cristo.

[[v46-9-21]]

^<<v46-9-21,21>>^ Assim também, quando estou entre os não judeus, vivo fora da Lei de Moisés a fim de ganhar os não judeus para Cristo. Isso não quer dizer que eu não obedeço à lei de Deus, pois estou, de fato, debaixo da lei de Cristo.

[[v46-9-22]]

^<<v46-9-22,22>>^ Quando estou entre os fracos na fé, eu me torno fraco também a fim de ganhá-los para Cristo. Assim eu me torno tudo para todos a fim de poder, de qualquer maneira possível, salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Faço tudo isso por causa do evangelho a fim de tomar parte nas suas bênçãos.

[[v46-9-24]]

^<<v46-9-24,24>>^ Vocês sabem que numa corrida, embora todos os corredores tomem parte, somente um ganha o prêmio. Portanto, corram de tal maneira que ganhem o prêmio.

[[v46-9-25]]

^<<v46-9-25,25>>^ Todo atleta que está treinando aguenta exercícios duros porque quer receber uma coroa de folhas de louro, uma coroa que, aliás, não dura muito. Mas nós queremos receber uma coroa que dura para sempre.

[[v46-9-26]]

^<<v46-9-26,26>>^ Por isso corro direto para a linha final. Também sou como um lutador de boxe que não perde nenhum golpe.

[[v46-9-27]]

^<<v46-9-27,27>>^ Eu trato o meu corpo duramente e o obrigo a ser completamente controlado para que, depois de ter chamado outros para entrarem na luta, eu mesmo não venha a ser eliminado dela.

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]