include::./index.adoc[]

[[v46-5-0]]
=== 1 Coríntios, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v46-5-1]]

^<<v46-5-1,1>>^ Agora estão dizendo que há entre vocês uma imoralidade sexual tão grande, que nem mesmo os pagãos seriam capazes de praticar. Fiquei sabendo que certo homem está tendo relações com a própria madrasta!

[[v46-5-2]]

^<<v46-5-2,2>>^ Como é que vocês podem estar tão orgulhosos? Pelo contrário, vocês deviam ficar muito tristes e expulsar do meio de vocês quem está fazendo uma coisa dessas.

[[v46-5-3]]

^<<v46-5-3,3>>^ Quanto a mim, ainda que não esteja presente aí pessoalmente, estou com vocês em espírito. E, agindo como se eu estivesse aí, já julguei, pela autoridade do nosso Senhor Jesus, o homem que está fazendo essa coisa horrível. Quando vocês se reunirem, estarei com vocês em espírito. Então, pelo poder do nosso Senhor Jesus, que estará presente conosco,

[[v46-5-4]]

^<<v46-5-4,4>>^ Quanto a mim, ainda que não esteja presente aí pessoalmente, estou com vocês em espírito. E, agindo como se eu estivesse aí, já julguei, pela autoridade do nosso Senhor Jesus, o homem que está fazendo essa coisa horrível. Quando vocês se reunirem, estarei com vocês em espírito. Então, pelo poder do nosso Senhor Jesus, que estará presente conosco,

[[v46-5-5]]

^<<v46-5-5,5>>^ entreguem esse homem a Satanás, para que o seu corpo seja destruído, mas o seu espírito seja salvo no Dia do Senhor .

[[v46-5-6]]

^<<v46-5-6,6>>^ Não está certo que vocês estejam orgulhosos! Vocês conhecem aquele ditado: "Um pouco de fermento fermenta toda a massa."

[[v46-5-7]]

^<<v46-5-7,7>>^ Joguem fora o velho fermento do pecado para ficarem completamente puros. Aí vocês serão como massa nova e sem fermento, como vocês, de fato, já são. Porque a nossa Festa da Páscoa  está pronta, agora que Cristo, o nosso Cordeiro da Páscoa, já foi oferecido em sacrifício.

[[v46-5-8]]

^<<v46-5-8,8>>^ Então vamos comemorar a nossa Páscoa, não com o pão que leva fermento, o fermento velho do pecado e da imoralidade, mas com o pão sem fermento  , o pão da pureza e da verdade.

[[v46-5-9]]

^<<v46-5-9,9>>^ Na outra carta que escrevi a vocês, eu recomendei que vocês não tivessem nada a ver com gente imoral.

[[v46-5-10]]

^<<v46-5-10,10>>^ Eu não quis dizer que neste mundo vocês devem ficar separados dos pagãos que são imorais, avarentos, ladrões ou que adoram ídolos. Pois, para evitar essas pessoas, vocês teriam de sair deste mundo.

[[v46-5-11]]

^<<v46-5-11,11>>^ O que eu digo é que vocês não devem ter nada a ver com ninguém que se diz irmão na fé, mas é imoral, ou avarento, ou adora ídolos, ou é bêbado, ou difamador, ou ladrão. Com gente assim vocês não devem nem comer uma refeição.

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]