include::./index.adoc[]

[[v9-23-0]]
=== 1 Samuel, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-23-1]]

^<<v9-23-1,1>>^ Davi soube que os filisteus estavam atacando a cidade de Queila e roubando o trigo que havia sido colhido há pouco.

[[v9-23-2]]

^<<v9-23-2,2>>^ Então perguntou a Deus, o Senhor : — Devo ir e atacar os filisteus? — Sim! — respondeu o Senhor . — Ataque-os e salve a cidade de Queila.

[[v9-23-3]]

^<<v9-23-3,3>>^ Mas os homens de Davi disseram: — Nós já estamos com medo de ficar aqui em Judá. Quanto mais de ir a Queila para atacar o exército dos filisteus!

[[v9-23-4]]

^<<v9-23-4,4>>^ Então Davi consultou novamente a Deus, o Senhor , e ele respondeu: — Vá a Queila e ataque porque eu lhe darei a vitória sobre os filisteus.

[[v9-23-5]]

^<<v9-23-5,5>>^ Então Davi e os seus homens foram a Queila e atacaram os filisteus. Mataram muitos deles e tomaram os seus rebanhos. E assim Davi salvou os moradores de Queila.

[[v9-23-6]]

^<<v9-23-6,6>>^ Na ocasião em que Abiatar, filho de Aimeleque, escapou e foi se juntar a Davi em Queila, ele levou o manto sacerdotal .

[[v9-23-7]]

^<<v9-23-7,7>>^ Quando Saul foi avisado de que Davi tinha ido para Queila, disse: — Deus entregou Davi nas minhas mãos. Ele foi para uma cidade cercada de muralhas, com portões reforçados, e assim caiu numa armadilha.

[[v9-23-8]]

^<<v9-23-8,8>>^ Então Saul chamou todos os soldados para a batalha a fim de marchar contra Queila e cercar Davi e os seus homens.

[[v9-23-9]]

^<<v9-23-9,9>>^ Quando Davi soube que Saul estava planejando atacá-lo, disse ao sacerdote Abiatar: — Traga aqui o manto sacerdotal para que possamos consultar a Deus.

[[v9-23-10]]

^<<v9-23-10,10>>^ Então Davi disse: — Ó Senhor , Deus de Israel, eu, o teu servo  Davi, soube que Saul está planejando vir a Queila para destruí-la por minha causa.

[[v9-23-11]]

^<<v9-23-11,11>>^ Será que os moradores de Queila vão me entregar nas mãos de Saul? Será que Saul virá mesmo, como ouvi dizer? Ó Senhor , Deus de Israel, peço-te que me respondas! — Saul virá! — respondeu o Senhor .

[[v9-23-12]]

^<<v9-23-12,12>>^ — E será que os moradores de Queila vão entregar a mim e também os meus homens a Saul? — perguntou Davi. — Sim, vão! — respondeu o Senhor .

[[v9-23-13]]

^<<v9-23-13,13>>^ Então Davi e os seus homens — mais ou menos seiscentos — saíram imediatamente de Queila e seguiram sem rumo certo. Quando Saul ficou sabendo que Davi tinha fugido de Queila, abandonou o seu plano.

[[v9-23-14]]

^<<v9-23-14,14>>^ Davi se escondeu nas fortalezas da região deserta e montanhosa que fica perto de Zife. Saul continuava a procurá-lo todos os dias, mas Deus não entregou Davi a ele.

[[v9-23-15]]

^<<v9-23-15,15>>^ E Davi estava com medo porque Saul tinha saído para matá-lo. Davi passou a viver em Horesa, no deserto que fica perto de Zife.

[[v9-23-16]]

^<<v9-23-16,16>>^ Jônatas foi encontrar-se com ele ali e lhe deu coragem para confiar na proteção de Deus.

[[v9-23-17]]

^<<v9-23-17,17>>^ Jônatas disse: — Não tenha medo. Saul, o meu pai, não conseguirá causar-lhe nenhum mal. Você será o rei de Israel, e eu ocuparei o segundo lugar no seu governo. E o meu pai sabe muito bem disso.

[[v9-23-18]]

^<<v9-23-18,18>>^ E ali, na presença de Deus, o Senhor , os dois renovaram a sua promessa de amizade. Davi ficou em Horesa, e Jônatas voltou para casa.

[[v9-23-19]]

^<<v9-23-19,19>>^ Algumas pessoas de Zife foram a Gibeá e disseram a Saul: — Davi está escondido na nossa terra, em Horesa, no monte Haquila, ao sul de Jesimom.

[[v9-23-20]]

^<<v9-23-20,20>>^ Nós sabemos que o senhor quer muito prendê-lo. Venha com a gente, que nós lhe entregaremos Davi.

[[v9-23-21]]

^<<v9-23-21,21>>^ Saul respondeu: — Que o Senhor  abençoe vocês por serem tão bondosos comigo!

[[v9-23-22]]

^<<v9-23-22,22>>^ Vão e se informem novamente. Descubram com certeza onde Davi está e quem o viu ali. Dizem que ele é muito esperto.

[[v9-23-23]]

^<<v9-23-23,23>>^ Descubram exatamente os lugares onde ele se esconde e voltem aqui sem falta. Então irei com vocês e, se ele estiver lá, eu o pegarei ainda que tenha de procurar em toda a terra de Judá.

[[v9-23-24]]

^<<v9-23-24,24>>^ Então eles voltaram para Zife, adiante de Saul. Davi e os seus homens estavam no deserto de Maom, num vale seco ao sul de Jesimom.

[[v9-23-25]]

^<<v9-23-25,25>>^ Saul e os seus soldados foram procurar Davi. Mas Davi ficou sabendo e foi para uma passagem nas rochas do deserto de Maom e ficou ali. Quando Saul soube disso, foi atrás de Davi.

[[v9-23-26]]

^<<v9-23-26,26>>^ Saul e os seus soldados estavam de um lado do monte, e Davi e os seus, do outro. Estes fugiram depressa para escapar de Saul e dos seus soldados, que os estavam cercando para prendê-los.

[[v9-23-27]]

^<<v9-23-27,27>>^ Mas justamente nesse momento um mensageiro chegou e disse a Saul: — Volte imediatamente! Os filisteus estão invadindo o país!

[[v9-23-28]]

^<<v9-23-28,28>>^ Então Saul parou de perseguir Davi e foi lutar contra os filisteus. É por isso que aquele lugar é chamado de "Rocha da Separação".

[[v9-23-29]]

^<<v9-23-29,29>>^ Davi saiu e foi para os lugares protegidos da região da fonte de Gedi.

'''

xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[&#60; Capítulo Anterior] | <<v9-23-0,Topo>> | xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[Próximo Capítulo &#62;]