include::./index.adoc[]

[[v9-20-0]]
=== 1 Samuel, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-20-1]]

^<<v9-20-1,1>>^ Então Davi fugiu da casa dos profetas , em Ramá, foi até o lugar onde Jônatas estava e disse: — O que foi que eu fiz? Qual foi o meu crime? Que mal fiz eu ao seu pai, para ele querer me matar?

[[v9-20-2]]

^<<v9-20-2,2>>^ Jônatas respondeu: — Que Deus não permita que você morra! O meu pai me conta tudo o que faz, seja importante ou não. Ele não esconderia isso de mim. Isso não é bem assim!

[[v9-20-3]]

^<<v9-20-3,3>>^ Mas Davi respondeu: — O seu pai sabe muito bem o quanto você gosta de mim. Por isso, resolveu não deixar que você fique sabendo dos planos dele, para você não sofrer muito. Eu juro pela sua vida e pela vida de Deus, o Senhor , que estou bem perto da morte!

[[v9-20-4]]

^<<v9-20-4,4>>^ — O que você quer que eu faça? — perguntou Jônatas.

[[v9-20-5]]

^<<v9-20-5,5>>^ Davi respondeu: — Amanhã é a Festa da Lua Nova , e eu deveria ir sem falta ao jantar do rei. Mas, se você deixar, eu irei me esconder no campo até depois de amanhã à noite.

[[v9-20-6]]

^<<v9-20-6,6>>^ Se o seu pai notar que eu não estou à mesa, diga que eu pedi a você para me deixar ir com urgência a Belém, pois está na época de toda a minha família oferecer lá o sacrifício  anual.

[[v9-20-7]]

^<<v9-20-7,7>>^ Se ele disser: "Está bem", eu estarei salvo. Mas, se ele ficar com raiva, então você ficará sabendo que ele está com más intenções.

[[v9-20-8]]

^<<v9-20-8,8>>^ Peço que você me faça este favor e cumpra assim a promessa sagrada que me fez. Porém, se eu sou culpado, mate-me você mesmo! Por que deixar o seu pai fazer isso?

[[v9-20-9]]

^<<v9-20-9,9>>^ — Nem pense numa coisa dessas! — respondeu Jônatas. — Se eu soubesse que o meu pai estava mesmo resolvido a acabar com você, acha que eu não o avisaria?

[[v9-20-10]]

^<<v9-20-10,10>>^ Então Davi perguntou: — E, se o seu pai responder com raiva, quem vai me avisar?

[[v9-20-11]]

^<<v9-20-11,11>>^ Jônatas respondeu: — Venha comigo, vamos até o campo. Eles foram,

[[v9-20-12]]

^<<v9-20-12,12>>^ e Jônatas disse a Davi: — Que o Senhor , o Deus de Israel, seja nossa testemunha. Amanhã e depois de amanhã, a esta hora, eu vou fazer algumas perguntas ao meu pai. Se a intenção dele para com você for boa, eu lhe mandarei dizer.

[[v9-20-13]]

^<<v9-20-13,13>>^ Mas, se ele tiver a intenção de fazer alguma coisa contra você, que o Senhor  Deus me mate se eu não enviar uma mensagem a você e não deixá-lo ir embora são e salvo! Que o Senhor  esteja com você, assim como esteve com o meu pai!

[[v9-20-14]]

^<<v9-20-14,14>>^ E agora, se eu continuar vivo, cumpra a sua promessa sagrada e seja fiel a mim. Mas, se eu morrer,

[[v9-20-15]]

^<<v9-20-15,15>>^ trate sempre a minha família com bondade. E, quando o Senhor  destruir completamente todos os nossos inimigos,

[[v9-20-16]]

^<<v9-20-16,16>>^ que nós não quebremos a promessa que fizemos um ao outro. Se você a quebrar, Deus o castigará.

[[v9-20-17]]

^<<v9-20-17,17>>^ Novamente Jônatas fez um juramento de amizade a Davi, pois ele amava Davi como a si mesmo.

[[v9-20-18]]

^<<v9-20-18,18>>^ E disse a Davi: — Amanhã é a Festa da Lua Nova, e, se você não estiver lá, a sua falta será notada.

[[v9-20-19]]

^<<v9-20-19,19>>^ Depois de amanhã a sua falta será notada ainda mais. Assim vá para o lugar onde você se escondeu da outra vez e fique atrás do monte de pedras que há ali.

[[v9-20-20]]

^<<v9-20-20,20>>^ Então eu atirarei três flechas, como se o monte de pedras fosse um alvo.

[[v9-20-21]]

^<<v9-20-21,21>>^ Aí direi ao meu empregado para ir buscá-las. Se eu disser a ele: "Olhe, as flechas estão para cá de você, pegue-as" — isso quer dizer que tudo está bem, e você pode sair. Eu juro por Deus, o Senhor , que nesse caso você não estará em perigo.

[[v9-20-22]]

^<<v9-20-22,22>>^ Mas, se disser a ele: "As flechas estão mais para lá de você" — então fuja, pois o Senhor  estará mandando que você vá.

[[v9-20-23]]

^<<v9-20-23,23>>^ Quanto à promessa que fizemos um ao outro, o Senhor  Deus nos ajudará a cumpri-la para sempre.

[[v9-20-24]]

^<<v9-20-24,24>>^ Então Davi se escondeu no campo. O rei Saul chegou para a Festa da Lua Nova

[[v9-20-25]]

^<<v9-20-25,25>>^ e sentou-se para comer no lugar de costume, perto da parede. Abner sentou-se ao lado de Saul, e Jônatas, na sua frente. Mas o lugar de Davi ficou vazio.

[[v9-20-26]]

^<<v9-20-26,26>>^ Naquele dia Saul não disse nada porque pensou: "Deve ter acontecido alguma coisa com ele, e de certo ele não passou pela cerimônia de purificação ."

[[v9-20-27]]

^<<v9-20-27,27>>^ No dia seguinte, o segundo dia da Festa da Lua Nova, o lugar de Davi continuava desocupado. Aí Saul perguntou a Jônatas: — Por que Davi não veio comer nem ontem nem hoje?

[[v9-20-28]]

^<<v9-20-28,28>>^ Jônatas respondeu: — Ele me pediu licença para ir a Belém.

[[v9-20-29]]

^<<v9-20-29,29>>^ Ele me disse: "Deixe-me ir a Belém porque a minha família está lá fazendo a festa do sacrifício, e o meu irmão mandou que eu também fosse. Se você é meu amigo, deixe que eu vá ver os meus parentes." E Jônatas continuou: — É por isso que ele não está no seu lugar, à mesa.

[[v9-20-30]]

^<<v9-20-30,30>>^ Então Saul ficou muito zangado com Jônatas e disse: — Seu filho de uma mulher à toa! Agora eu sei que você passou para o lado de Davi, trazendo desonra para você e para a sua mãe!

[[v9-20-31]]

^<<v9-20-31,31>>^ Enquanto Davi for vivo, você não será rei deste país. Vá agora e traga-o aqui porque é preciso que ele morra!

[[v9-20-32]]

^<<v9-20-32,32>>^ — Por que é que ele deve morrer? — perguntou Jônatas. — O que foi que ele fez?

[[v9-20-33]]

^<<v9-20-33,33>>^ Então Saul atirou a sua lança contra Jônatas para matá-lo. E assim Jônatas compreendeu que o seu pai estava mesmo resolvido a matar Davi.

[[v9-20-34]]

^<<v9-20-34,34>>^ Jônatas levantou-se furioso da mesa e não comeu nada naquele dia, o segundo dia da Festa da Lua Nova. Ele estava muito sentido porque Saul tinha insultado Davi.

[[v9-20-35]]

^<<v9-20-35,35>>^ Na manhã seguinte ele foi ao campo a fim de encontrar Davi, como tinham combinado. Levou consigo um rapazinho

[[v9-20-36]]

^<<v9-20-36,36>>^ e disse: — Corra e vá buscar as flechas que eu atirar. O rapaz correu, e Jônatas atirou uma flecha que passou além dele.

[[v9-20-37]]

^<<v9-20-37,37>>^ Quando o rapaz chegou ao lugar onde a flecha tinha caído, Jônatas gritou: — A flecha caiu mais para lá de você!

[[v9-20-38]]

^<<v9-20-38,38>>^ Não fique aí parado! Ande logo! O rapaz pegou as flechas e voltou para perto do seu patrão,

[[v9-20-39]]

^<<v9-20-39,39>>^ não sabendo o que queria dizer tudo aquilo — somente Jônatas e Davi sabiam.

[[v9-20-40]]

^<<v9-20-40,40>>^ Aí Jônatas entregou as suas armas ao rapaz e mandou que as levasse de volta para a cidade.

[[v9-20-41]]

^<<v9-20-41,41>>^ Depois que o rapaz foi embora, Davi saiu de trás do monte de pedras, jogou-se no chão e encostou o rosto na terra três vezes. Então eles se beijaram chorando. E a tristeza de Davi era maior do que a de Jônatas.

[[v9-20-42]]

^<<v9-20-42,42>>^ Aí Jônatas disse a Davi: — Deus esteja com você! O Senhor  Deus fará com que você, e eu, e os seus descendentes, e os meus cumpramos sempre a promessa sagrada que nós fizemos um ao outro. Então Davi partiu, e Jônatas voltou para a cidade.

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]