include::./index.adoc[]

[[v9-22-0]]
=== 1 Samuel, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-22-1]]

^<<v9-22-1,1>>^ Davi fugiu da cidade de Gate e foi para uma caverna perto da cidade de Adulã. Quando os seus irmãos e o resto da família souberam que ele estava lá, foram ficar com ele.

[[v9-22-2]]

^<<v9-22-2,2>>^ E todos os homens que estavam em dificuldades, ou com dívidas, ou insatisfeitos também foram, e Davi se tornou o chefe deles. Havia com ele mais ou menos quatrocentos homens.

[[v9-22-3]]

^<<v9-22-3,3>>^ Aí Davi saiu dali, foi para Mispa, em Moabe, e disse ao rei daquele país: — Por favor, deixe que o meu pai e a minha mãe venham para cá e fiquem com você até que eu saiba o que Deus vai fazer por mim.

[[v9-22-4]]

^<<v9-22-4,4>>^ Davi deixou os pais com o rei de Moabe, e eles ficaram ali enquanto Davi esteve escondido na fortaleza.

[[v9-22-5]]

^<<v9-22-5,5>>^ O profeta  Gade foi para o lugar onde Davi estava e disse: — Não fique aqui. Vá logo para a terra de Judá. Então Davi saiu e foi para a floresta de Herete.

[[v9-22-6]]

^<<v9-22-6,6>>^ Saul estava em Gibeá, num morro, sentado debaixo de uma árvore, com a lança na mão. Todos os seus oficiais estavam ao redor dele. E lhe contaram que Davi e os seus homens estavam em certo lugar.

[[v9-22-7]]

^<<v9-22-7,7>>^ Então Saul disse aos seus oficiais: — Ouçam, homens da tribo  de Benjamim! Vocês pensam que Davi lhes dará campos e plantações de uvas e os fará capitães e tenentes do seu exército?

[[v9-22-8]]

^<<v9-22-8,8>>^ É por isso que vocês estão fazendo planos contra mim? Nenhum de vocês me contou que o meu próprio filho fez um acordo  com Davi. Ninguém se preocupa comigo. Ninguém me diz que Davi, um dos meus próprios homens, está agora mesmo procurando uma oportunidade para me matar e que foi o meu próprio filho quem o pôs contra mim!

[[v9-22-9]]

^<<v9-22-9,9>>^ Doegue, do país de Edom, estava ali com os oficiais de Saul e disse: — Eu vi quando Davi foi falar com Aimeleque, filho de Aitube, em Nobe.

[[v9-22-10]]

^<<v9-22-10,10>>^ Aimeleque perguntou a Deus, o Senhor , o que Davi devia fazer. E também deu a Davi comida e a espada de Golias, o filisteu.

[[v9-22-11]]

^<<v9-22-11,11>>^ Então o rei Saul mandou chamar Aimeleque e todos os seus parentes, que também eram sacerdotes em Nobe, e eles foram para o lugar onde ele estava.

[[v9-22-12]]

^<<v9-22-12,12>>^ Saul disse a Aimeleque: — Escute, Aimeleque! — Às suas ordens, senhor! — respondeu ele.

[[v9-22-13]]

^<<v9-22-13,13>>^ Saul lhe perguntou: — Por que é que você e Davi se juntaram para fazer planos contra mim? Por que você lhe deu comida e uma espada e perguntou a Deus o que ele devia fazer? Agora Davi se virou contra mim e está esperando a hora de me atacar.

[[v9-22-14]]

^<<v9-22-14,14>>^ Aimeleque respondeu: — Davi é o oficial mais fiel que o senhor tem! Ele é o seu próprio genro, capitão da sua guarda pessoal e muito respeitado por todas as autoridades do país.

[[v9-22-15]]

^<<v9-22-15,15>>^ Será que esta foi a primeira vez que eu perguntei a Deus o que Davi devia fazer? Claro que não! O senhor não deve acusar a mim nem ninguém da minha família de estarmos fazendo planos contra o senhor. Não sei nada a respeito disso!

[[v9-22-16]]

^<<v9-22-16,16>>^ Então o rei disse: — Aimeleque, você e os seus parentes vão morrer.

[[v9-22-17]]

^<<v9-22-17,17>>^ Em seguida disse aos guardas que estavam ali perto: — Matem os sacerdotes de Deus, o Senhor ! Eles se juntaram com Davi e não me disseram que ele havia fugido, embora soubessem disso o tempo todo. Mas os guardas se recusaram a levantar a mão para matar os sacerdotes do Senhor .

[[v9-22-18]]

^<<v9-22-18,18>>^ Então Saul disse a Doegue: — Mate-os você! E Doegue os matou. Nesse dia ele matou oitenta e cinco sacerdotes de Deus.

[[v9-22-19]]

^<<v9-22-19,19>>^ Saul também mandou matar todos os outros moradores de Nobe, a cidade dos sacerdotes: homens e mulheres, meninos e criancinhas, o gado, jumentos e ovelhas — todos foram mortos.

[[v9-22-20]]

^<<v9-22-20,20>>^ Mas Abiatar, um dos filhos de Aimeleque, escapou e foi para o lugar onde Davi estava.

[[v9-22-21]]

^<<v9-22-21,21>>^ Ele contou que Saul havia matado os sacerdotes de Deus, o Senhor .

[[v9-22-22]]

^<<v9-22-22,22>>^ Então Davi disse a Abiatar: — Naquele dia, quando vi Doegue lá, eu sabia que ele não deixaria de contar tudo a Saul. Assim, eu sou culpado da morte de todos os seus parentes.

[[v9-22-23]]

^<<v9-22-23,23>>^ Fique comigo e não tenha medo. Saul quer matar a nós dois, mas comigo você estará livre de perigo.

'''

xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[&#60; Capítulo Anterior] | <<v9-22-0,Topo>> | xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[Próximo Capítulo &#62;]