include::./index.adoc[]

[[v9-7-0]]
=== 1 Samuel, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-7-1]]

^<<v9-7-1,1>>^ Então os homens da cidade de Jearim foram até lá e levaram a arca  do Senhor . Eles a colocaram na casa de Abinadabe, que ficava num morro. E escolheram e separaram o seu filho Eleazar para tomar conta dela.

[[v9-7-2]]

^<<v9-7-2,2>>^ A arca da aliança  ficou na cidade de Jearim bastante tempo, isto é, mais ou menos vinte anos. Durante esse tempo todos os israelitas oravam a Deus, o Senhor , pedindo ajuda.

[[v9-7-3]]

^<<v9-7-3,3>>^ Samuel disse ao povo de Israel: — Se vocês querem com todo o coração voltar a Deus, o Senhor , joguem fora todos os deuses estrangeiros e as imagens da deusa Astarote . Dediquem-se completamente ao Senhor  e adorem somente a ele. E ele livrará vocês do poder dos filisteus.

[[v9-7-4]]

^<<v9-7-4,4>>^ Aí os israelitas jogaram fora as suas várias imagens de Baal  e também as de Astarote  e adoraram somente a Deus, o Senhor .

[[v9-7-5]]

^<<v9-7-5,5>>^ Então Samuel mandou que todos os israelitas se reunissem em Mispa. E prometeu que ali oraria por eles ao Senhor .

[[v9-7-6]]

^<<v9-7-6,6>>^ Assim todos eles se reuniram em Mispa. Tiraram água e a derramaram em oferta ao Senhor , jejuaram o dia todo e disseram: — Nós pecamos contra Deus, o Senhor . E ali em Mispa Samuel julgava e governava o povo de Israel.

[[v9-7-7]]

^<<v9-7-7,7>>^ Quando os filisteus souberam que os israelitas haviam se reunido em Mispa, os cinco governadores filisteus saíram com os seus homens para atacá-los. Os israelitas souberam disso e ficaram com medo.

[[v9-7-8]]

^<<v9-7-8,8>>^ E disseram a Samuel: — Não pare de orar ao Senhor , nosso Deus, pedindo que ele nos livre do domínio dos filisteus.

[[v9-7-9]]

^<<v9-7-9,9>>^ Então Samuel matou um carneirinho e queimou todo ele como sacrifício  a Deus, o Senhor . Pediu que o Senhor  ajudasse o povo de Israel, e ele respondeu à sua oração.

[[v9-7-10]]

^<<v9-7-10,10>>^ Enquanto Samuel estava oferecendo o sacrifício, os filisteus avançaram contra os israelitas. Mas o Senhor  os atacou com fortes trovoadas. Então eles ficaram em completa confusão e fugiram.

[[v9-7-11]]

^<<v9-7-11,11>>^ Os israelitas saíram de Mispa e perseguiram os filisteus até Bete-Car, matando-os pelo caminho.

[[v9-7-12]]

^<<v9-7-12,12>>^ Aí Samuel pegou uma pedra, pôs entre Mispa e Sem e disse: — Até aqui o Senhor  Deus nos ajudou. Por isso deu a ela o nome de Ebenézer .

[[v9-7-13]]

^<<v9-7-13,13>>^ Assim os filisteus foram derrotados, e o Senhor  Deus não deixou que eles invadissem a terra de Israel enquanto Samuel viveu.

[[v9-7-14]]

^<<v9-7-14,14>>^ Todas as cidades que os filisteus haviam tomado, desde Ecrom até Gate, foram devolvidas ao povo de Israel. Dessa maneira os israelitas receberam de volta toda a sua terra. E também houve paz entre os israelitas e os amorreus.

[[v9-7-15]]

^<<v9-7-15,15>>^ Até o fim da sua vida Samuel foi chefe e juiz do povo de Israel.

[[v9-7-16]]

^<<v9-7-16,16>>^ Todos os anos ele ia a Betel, Gilgal e Mispa e nesses lugares resolvia as questões que o povo lhe apresentava.

[[v9-7-17]]

^<<v9-7-17,17>>^ Depois voltava para a sua casa na cidade de Ramá, onde também era juiz. E em Ramá Samuel construiu um altar para Deus, o Senhor .

'''

xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[&#60; Capítulo Anterior] | <<v9-7-0,Topo>> | xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[Próximo Capítulo &#62;]