include::./index.adoc[]

[[v9-8-0]]
=== 1 Samuel, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-8-1]]

^<<v9-8-1,1>>^ Quando Samuel ficou velho, pôs os seus filhos como juízes de Israel.

[[v9-8-2]]

^<<v9-8-2,2>>^ O seu filho mais velho se chamava Joel, e o mais novo, Abias. Eles eram juízes na cidade de Berseba.

[[v9-8-3]]

^<<v9-8-3,3>>^ Porém não seguiram o exemplo do pai. Estavam interessados somente em ganhar dinheiro, aceitavam dinheiro por fora e não decidiam os casos com justiça.

[[v9-8-4]]

^<<v9-8-4,4>>^ Então todos os líderes de Israel se reuniram e foram falar com Samuel, em Ramá.

[[v9-8-5]]

^<<v9-8-5,5>>^ Eles disseram: — Olhe! Você já está ficando velho, e os seus filhos não seguem o seu exemplo. Por isso, queremos que nos arranje um rei para nos governar, como acontece em outros países.

[[v9-8-6]]

^<<v9-8-6,6>>^ Samuel não gostou do pedido deles. Então orou a Deus, o Senhor ,

[[v9-8-7]]

^<<v9-8-7,7>>^ e ele respondeu assim: — Atenda o pedido do povo. Não é só você que eles rejeitaram; eles rejeitaram a mim como Rei.

[[v9-8-8]]

^<<v9-8-8,8>>^ Desde que eu os trouxe do Egito, eles sempre me têm abandonado e têm adorado outros deuses. Agora estão fazendo com você o que sempre fizeram comigo.

[[v9-8-9]]

^<<v9-8-9,9>>^ Portanto, atenda o pedido deles. Mas avise essa gente, explicando com toda a clareza como o rei vai tratá-los.

[[v9-8-10]]

^<<v9-8-10,10>>^ Então Samuel explicou ao povo tudo o que o Senhor  lhe tinha dito.

[[v9-8-11]]

^<<v9-8-11,11>>^ Ele disse: — O rei os tratará assim: tomará os filhos de vocês para serem soldados; porá alguns para servirem nos seus carros de guerra, outros na cavalaria e outros para correrem adiante dos carros.

[[v9-8-12]]

^<<v9-8-12,12>>^ Colocará alguns deles como oficiais encarregados de mil soldados, e outros encarregados de cinquenta. Os seus filhos terão de cultivar as terras dele, fazer as suas colheitas e fabricar as suas armas e equipamentos para os seus carros de guerra.

[[v9-8-13]]

^<<v9-8-13,13>>^ As filhas de vocês terão de preparar os perfumes do rei e trabalhar como suas cozinheiras e padeiras.

[[v9-8-14]]

^<<v9-8-14,14>>^ Ele tomará de vocês os melhores campos, plantações de uvas, bosques de oliveiras e dará tudo aos seus funcionários.

[[v9-8-15]]

^<<v9-8-15,15>>^ Ficará com a décima parte dos cereais e das uvas, para dar aos funcionários da corte e aos outros funcionários.

[[v9-8-16]]

^<<v9-8-16,16>>^ Tomará também os empregados de vocês, o melhor gado e os melhores jumentos, para trabalharem para ele.

[[v9-8-17]]

^<<v9-8-17,17>>^ E ficará com a décima parte dos rebanhos de vocês. E vocês serão seus escravos.

[[v9-8-18]]

^<<v9-8-18,18>>^ Quando isso acontecer, vocês chorarão amargamente por causa do rei que escolheram, porém o Senhor  Deus não ouvirá as suas queixas.

[[v9-8-19]]

^<<v9-8-19,19>>^ Mas o povo não se importou com o aviso de Samuel. Pelo contrário, eles disseram: — Não adianta. Nós queremos um rei.

[[v9-8-20]]

^<<v9-8-20,20>>^ Queremos ser como as outras nações: queremos ter um rei para nos governar, para nos dirigir na guerra e lutar em nossas batalhas.

[[v9-8-21]]

^<<v9-8-21,21>>^ Samuel ouviu o que eles disseram e então foi e contou tudo a Deus, o Senhor .

[[v9-8-22]]

^<<v9-8-22,22>>^ Ele respondeu: — Faça o que eles querem. Dê a eles um rei. Aí Samuel pediu a todos os homens de Israel que voltassem para casa.

'''

xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[&#60; Capítulo Anterior] | <<v9-8-0,Topo>> | xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[Próximo Capítulo &#62;]