include::./index.adoc[]

[[v9-5-0]]
=== 1 Samuel, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-5-1]]

^<<v9-5-1,1>>^ Depois de tomarem a arca  de Deus, os filisteus a levaram de Ebenézer para a cidade de Asdode.

[[v9-5-2]]

^<<v9-5-2,2>>^ Eles a colocaram no templo do seu deus Dagom, perto da sua imagem.

[[v9-5-3]]

^<<v9-5-3,3>>^ No dia seguinte, de manhã, os moradores de Asdode viram que a imagem de Dagom estava caída de cara no chão, na frente da arca da aliança. Então eles pegaram a imagem e a puseram de volta no seu lugar.

[[v9-5-4]]

^<<v9-5-4,4>>^ No dia seguinte, de manhã, viram que ela estava caída de novo na frente da arca. A cabeça e os dois braços da imagem estavam quebrados, caídos na soleira da porta; somente o corpo estava inteiro.

[[v9-5-5]]

^<<v9-5-5,5>>^ É por isso que até hoje  os sacerdotes de Dagom e todos os que o adoram em Asdode não pisam aquele lugar.

[[v9-5-6]]

^<<v9-5-6,6>>^ E o Senhor  Deus castigou duramente o povo de Asdode. Fez com que todo o povo dali e da vizinhança ficasse cheio de tumores.

[[v9-5-7]]

^<<v9-5-7,7>>^ Quando eles viram isso, disseram: — O Deus de Israel está castigando a nós e ao nosso deus Dagom. Não podemos mais deixar que a arca do Deus de Israel fique aqui.

[[v9-5-8]]

^<<v9-5-8,8>>^ Então mandaram que alguns mensageiros fossem chamar todos os cinco governadores filisteus e lhes perguntaram: — Que vamos fazer com a arca do Deus de Israel? — Levem para a cidade de Gate! — responderam eles. Então os filisteus a levaram para lá.

[[v9-5-9]]

^<<v9-5-9,9>>^ Mas, depois que a arca chegou ali, o Senhor  Deus castigou a cidade e pôs medo nos seus moradores. Apareceram tumores em todas as pessoas da cidade, tanto nas mais importantes como nas mais humildes.

[[v9-5-10]]

^<<v9-5-10,10>>^ Então enviaram a arca da aliança para a cidade de Ecrom. Quando a arca chegou lá, o povo começou a gritar: — Trouxeram a arca do Deus de Israel para cá; eles querem acabar com a gente!

[[v9-5-11]]

^<<v9-5-11,11>>^ Então mandaram que alguns mensageiros dissessem a todos os governadores filisteus: — Mandem a arca do Deus de Israel de volta ao seu lugar, para que ela não mate a nós e às nossas famílias. Houve morte e destruição em toda a cidade, por causa do castigo severo de Deus.

[[v9-5-12]]

^<<v9-5-12,12>>^ Os que não morreram ficaram cheios de tumores, e os gritos dos moradores da cidade subiram até o céu.

'''

xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[&#60; Capítulo Anterior] | <<v9-5-0,Topo>> | xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[Próximo Capítulo &#62;]