include::./index.adoc[]

[[v9-18-0]]
=== 1 Samuel, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-18-1]]

^<<v9-18-1,1>>^ Saul e Davi terminaram a sua conversa. Jônatas, filho de Saul, começou a sentir uma profunda amizade por Davi e veio a amá-lo como a si mesmo.

[[v9-18-2]]

^<<v9-18-2,2>>^ Daquele dia em diante Saul levou Davi para a sua casa e não deixou que voltasse para a casa do seu pai.

[[v9-18-3]]

^<<v9-18-3,3>>^ Jônatas e Davi fizeram um juramento de amizade, pois Jônatas tinha grande amor por Davi.

[[v9-18-4]]

^<<v9-18-4,4>>^ Ele tirou a capa  que estava usando e a deu a Davi. Deu também a sua túnica militar, a espada, o arco e o cinto.

[[v9-18-5]]

^<<v9-18-5,5>>^ Davi saiu-se bem em todos os lugares aonde Saul o enviou. Então Saul o promoveu a comandante do seu exército. E isso agradou a todo o exército, inclusive aos outros oficiais.

[[v9-18-6]]

^<<v9-18-6,6>>^ Quando os soldados estavam voltando para casa depois de Davi ter matado Golias, as mulheres de todas as cidades de Israel saíram para encontrar o rei Saul. Elas cantavam canções alegres, dançavam e tocavam pandeiro e lira .

[[v9-18-7]]

^<<v9-18-7,7>>^ Alegravam-se e cantavam assim: "Saul matou mil; Davi matou dez mil!"

[[v9-18-8]]

^<<v9-18-8,8>>^ E Saul não gostou disso. Ficou muito zangado e disse: — Para mim as mulheres deram mil, mas para Davi deram dez mil. A única coisa que está faltando agora é ele ser rei!

[[v9-18-9]]

^<<v9-18-9,9>>^ E desse dia em diante Saul começou a ter ciúme de Davi e a desconfiar dele.

[[v9-18-10]]

^<<v9-18-10,10>>^ No dia seguinte, um espírito mau mandado por Deus dominou Saul, e ele começou a agir como louco dentro de casa. Davi estava tocando lira, como fazia todos os dias, e Saul estava segurando uma lança.

[[v9-18-11]]

^<<v9-18-11,11>>^ Então Saul pensou assim: — Vou espetar Davi na parede. E atirou a lança contra ele, duas vezes. Porém nas duas vezes Davi se desviou.

[[v9-18-12]]

^<<v9-18-12,12>>^ O Senhor  estava com Davi e havia abandonado Saul; por isso, Saul tinha medo de Davi.

[[v9-18-13]]

^<<v9-18-13,13>>^ Então Saul o afastou de si, pondo-o como oficial comandante de mil homens. Davi comandava os seus soldados na batalha,

[[v9-18-14]]

^<<v9-18-14,14>>^ e tudo o que fazia dava certo, pois o Senhor  estava com ele.

[[v9-18-15]]

^<<v9-18-15,15>>^ Saul viu o sucesso de Davi e ficou ainda com mais medo dele.

[[v9-18-16]]

^<<v9-18-16,16>>^ Mas em Israel e em Judá todos amavam Davi porque ele era um líder corajoso.

[[v9-18-17]]

^<<v9-18-17,17>>^ Então Saul disse a Davi: — Aqui está Merabe, a minha filha mais velha. Eu a darei em casamento a você, com a condição de que você me sirva como soldado valente e fiel e lute nas batalhas de Deus, o Senhor . Saul pensava que desta maneira os filisteus matariam Davi e assim não teria ele mesmo de fazer isso.

[[v9-18-18]]

^<<v9-18-18,18>>^ Davi respondeu: — Quem sou eu, e quem é a minha família em Israel para que eu seja genro do rei?

[[v9-18-19]]

^<<v9-18-19,19>>^ Mas, quando chegou a época de Merabe ser dada em casamento a Davi, ela foi dada a um homem chamado Adriel, da cidade de Meolá.

[[v9-18-20]]

^<<v9-18-20,20>>^ Porém Mical, a outra filha de Saul, apaixonou-se por Davi. E, quando Saul soube disso, ficou contente.

[[v9-18-21]]

^<<v9-18-21,21>>^ Ele pensou: — Vou dar Mical em casamento a Davi, e ela servirá como uma armadilha para que ele seja morto pelos filisteus. Então, pela segunda vez, Saul disse a Davi: — Você será meu genro.

[[v9-18-22]]

^<<v9-18-22,22>>^ Ele mandou que os seus oficiais conversassem em particular com Davi e dissessem a ele: — O rei e todos os oficiais gostam de você. Esta é uma boa ocasião para você casar com a filha dele.

[[v9-18-23]]

^<<v9-18-23,23>>^ Então eles falaram com Davi, e ele respondeu: — Ser genro do rei é uma honra grande demais para uma pessoa pobre e sem valor como eu.

[[v9-18-24]]

^<<v9-18-24,24>>^ Os oficiais contaram a Saul o que Davi tinha dito,

[[v9-18-25]]

^<<v9-18-25,25>>^ e ele ordenou que dissessem o seguinte a Davi: — Tudo o que o rei quer de você em pagamento pela noiva são os prepúcios  de cem filisteus mortos, como vingança contra os inimigos dele. Saul tinha planejado isso porque assim Davi seria morto pelos filisteus.

[[v9-18-26]]

^<<v9-18-26,26>>^ Os oficiais contaram a Davi o que Saul tinha dito, e ele ficou entusiasmado com a ideia de ser genro do rei. Antes do dia marcado para o casamento,

[[v9-18-27]]

^<<v9-18-27,27>>^ Davi e os seus soldados foram e mataram duzentos filisteus. Aí Davi levou ao rei os prepúcios dos filisteus mortos e os contou na presença dele, para que assim se tornasse seu genro. Então Saul deu a sua filha Mical em casamento a Davi.

[[v9-18-28]]

^<<v9-18-28,28>>^ Saul viu e reconheceu que o Senhor  estava com Davi e que a sua filha Mical o amava.

[[v9-18-29]]

^<<v9-18-29,29>>^ Por isso, ficou com mais medo ainda de Davi e pelo resto da sua vida foi seu inimigo.

[[v9-18-30]]

^<<v9-18-30,30>>^ Todas as vezes que os exércitos filisteus saíam para lutar, Davi conseguia mais vitórias do que todos os outros oficiais de Saul e assim ficou muito famoso.

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]