include::./index.adoc[]

[[v9-26-0]]
=== 1 Samuel, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-26-1]]

^<<v9-26-1,1>>^ Alguns moradores de Zife foram a Gibeá e contaram a Saul que Davi estava escondido no monte Haquila, em frente de Jesimom.

[[v9-26-2]]

^<<v9-26-2,2>>^ Então Saul partiu imediatamente para o deserto de Zife com três mil dos melhores soldados de Israel a fim de procurar Davi.

[[v9-26-3]]

^<<v9-26-3,3>>^ Eles acamparam no monte Haquila, em frente de Jesimom. Davi estava no deserto e ouviu dizer que Saul tinha vindo atrás dele.

[[v9-26-4]]

^<<v9-26-4,4>>^ Aí enviou alguns espiões e ficou sabendo que Saul, de fato, estava ali.

[[v9-26-5]]

^<<v9-26-5,5>>^ Imediatamente foi até lá e encontrou o lugar onde dormiam Saul e Abner, filho de Ner, comandante do seu exército. Saul dormia dentro do acampamento, e os seus soldados acampavam em volta dele.

[[v9-26-6]]

^<<v9-26-6,6>>^ Então Davi perguntou ao heteu Aimeleque e a Abisai, cuja mãe era Zeruia e cujo irmão era Joabe: — Quem de vocês vai comigo ao acampamento de Saul? — Eu vou! — respondeu Abisai.

[[v9-26-7]]

^<<v9-26-7,7>>^ Assim, naquela noite, Davi e Abisai entraram no acampamento de Saul. E o encontraram dormindo no centro do acampamento, com a sua lança fincada no chão, perto da sua cabeça. Abner e os soldados dormiam em volta de Saul.

[[v9-26-8]]

^<<v9-26-8,8>>^ Então Abisai disse a Davi: — Esta noite Deus colocou o seu inimigo nas suas mãos. Agora deixe que eu atravesse Saul com a lança dele e o espete no chão com um só golpe. Não precisarei dar dois golpes!

[[v9-26-9]]

^<<v9-26-9,9>>^ Mas Davi respondeu: — Não o mate, pois o Senhor  Deus castigará quem levantar a mão para matar o rei que ele escolheu.

[[v9-26-10]]

^<<v9-26-10,10>>^ Tão certo como o Senhor  Deus está vivo, assim ele mesmo matará Saul, seja quando chegar o seu dia de morrer, seja numa batalha!

[[v9-26-11]]

^<<v9-26-11,11>>^ O Senhor  me livre de levantar a mão contra quem ele escolheu como rei! Vamos pegar o jarro de água e a lança dele e vamos embora.

[[v9-26-12]]

^<<v9-26-12,12>>^ Então Davi pegou a lança e o jarro de água que estavam ao lado da cabeça de Saul e foi embora com Abisai. Ninguém os viu, nem soube o que havia acontecido. E ninguém acordou. Todos estavam dormindo profundamente porque o Senhor  tinha feito com que todos eles caíssem num sono profundo.

[[v9-26-13]]

^<<v9-26-13,13>>^ Aí Davi passou para o outro lado do vale, foi até o alto do monte, a uma boa distância deles,

[[v9-26-14]]

^<<v9-26-14,14>>^ e gritou para Abner e para os soldados de Saul: — Abner, você está me ouvindo? — Quem é que está gritando para o rei? — perguntou Abner.

[[v9-26-15]]

^<<v9-26-15,15>>^ Davi respondeu: — Você é homem ou não é? Você não é o melhor soldado de Israel? Então por que não protegeu o seu chefe, o rei? Agora mesmo alguém entrou no acampamento para matar o rei, o seu chefe.

[[v9-26-16]]

^<<v9-26-16,16>>^ Você falhou, Abner! Eu juro pelo Senhor , o Deus vivo, que vocês todos morrerão, pois não protegeram o seu chefe, que o Senhor  Deus fez rei. Escutem! Onde está a lança do rei? Onde está o jarro de água que estava ao lado da cabeça dele?

[[v9-26-17]]

^<<v9-26-17,17>>^ Saul reconheceu a voz de Davi e perguntou: — Davi, é você, meu filho? — Sim, senhor! — respondeu Davi.

[[v9-26-18]]

^<<v9-26-18,18>>^ — Por que é que o senhor continua a perseguir este seu criado? O que foi que eu fiz? Qual foi o crime que cometi?

[[v9-26-19]]

^<<v9-26-19,19>>^ Ó rei, escute o que eu tenho a dizer. Se foi Deus que fez o senhor se virar contra mim, ele mudará de ideia se lhe for feita uma oferta. Mas, se foram certas pessoas que fizeram isso, que a maldição de Deus caia sobre elas! Pois me expulsaram da terra do Senhor  Deus para uma terra onde posso adorar somente deuses estrangeiros.

[[v9-26-20]]

^<<v9-26-20,20>>^ Não me deixe ser morto em terra estrangeira, longe do Senhor  Deus! Por que o rei de Israel viria aqui? Para procurar uma pulga como eu? Por que me caçaria como se eu fosse um pássaro selvagem?

[[v9-26-21]]

^<<v9-26-21,21>>^ Saul respondeu: — Eu errei. Volte, meu filho Davi! Nunca mais eu lhe farei nenhum mal, pois esta noite você respeitou a minha vida. Tenho sido um louco e cometi um grande erro!

[[v9-26-22]]

^<<v9-26-22,22>>^ Então Davi disse: — Aqui está a sua lança, senhor. Que um dos seus homens venha buscá-la!

[[v9-26-23]]

^<<v9-26-23,23>>^ O Senhor  Deus recompensa aqueles que são fiéis e corretos. Hoje ele colocou o senhor nas minhas mãos, mas eu não levantei a mão para matar aquele que Deus escolheu como rei.

[[v9-26-24]]

^<<v9-26-24,24>>^ Assim como eu hoje respeitei a sua vida, que o Senhor  faça o mesmo comigo e me livre de todas as dificuldades!

[[v9-26-25]]

^<<v9-26-25,25>>^ E Saul respondeu a Davi: — Deus o abençoe, meu filho! Tudo o que você fizer dará certo! Então Davi foi embora, e Saul voltou para casa.

'''

xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[&#60; Capítulo Anterior] | <<v9-26-0,Topo>> | xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[Próximo Capítulo &#62;]