include::./index.adoc[]

[[v9-30-0]]
=== 1 Samuel, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-30-1]]

^<<v9-30-1,1>>^ Dois dias depois, Davi e os seus homens chegaram a Ziclague, a sua cidade. Enquanto ele havia estado fora, os amalequitas tinham invadido o Sul da terra de Judá e atacado Ziclague. Eles queimaram a cidade

[[v9-30-2]]

^<<v9-30-2,2>>^ e prenderam todas as mulheres. Não mataram ninguém, mas foram embora e levaram todos como prisioneiros.

[[v9-30-3]]

^<<v9-30-3,3>>^ Quando Davi e os seus homens chegaram, viram que a cidade tinha sido queimada e que as suas mulheres, os seus filhos e as suas filhas haviam sido levados embora.

[[v9-30-4]]

^<<v9-30-4,4>>^ Então Davi e os seus homens começaram a chorar e choraram até ficarem sem forças.

[[v9-30-5]]

^<<v9-30-5,5>>^ As duas mulheres de Davi, Ainoã, de Jezreel, e Abigail, viúva de Nabal, da cidade de Carmelo, também haviam sido levadas.

[[v9-30-6]]

^<<v9-30-6,6>>^ Davi ficou então numa situação muito difícil, pois os seus homens estavam tão amargurados por ficarem sem os seus filhos, que falavam até em matá-lo a pedradas. Mas o Senhor , seu Deus, lhe deu coragem.

[[v9-30-7]]

^<<v9-30-7,7>>^ E ele disse ao sacerdote Abiatar, filho de Aimeleque: — Traga aqui o manto sacerdotal  para que possamos consultar a Deus. E Abiatar trouxe.

[[v9-30-8]]

^<<v9-30-8,8>>^ Então Davi perguntou a Deus, o Senhor : — Devo ir atrás desses invasores? Conseguirei pegá-los? Deus respondeu: — Vá atrás deles. Você os pegará e libertará os prisioneiros.

[[v9-30-9]]

^<<v9-30-9,9>>^ Então Davi e os seus seiscentos homens saíram, e, quando chegaram ao ribeirão de Besor, alguns deles ficaram ali.

[[v9-30-10]]

^<<v9-30-10,10>>^ Davi continuou o seu caminho com quatrocentos homens. Os outros duzentos estavam cansados demais para atravessar o ribeirão e por isso ficaram para trás.

[[v9-30-11]]

^<<v9-30-11,11>>^ Os homens de Davi acharam no campo um rapaz egípcio e o levaram a Davi. Deram ao rapaz comida, água,

[[v9-30-12]]

^<<v9-30-12,12>>^ figos secos e dois cachos de passas. Ele havia ficado três dias e três noites sem comer, nem beber. Mas, depois de comer, as suas forças voltaram.

[[v9-30-13]]

^<<v9-30-13,13>>^ Então Davi perguntou: — Quem é o seu dono? De onde você é? — Eu sou egípcio e sou escravo de um amalequita! — respondeu ele. — O meu dono me deixou aqui há três dias porque fiquei doente.

[[v9-30-14]]

^<<v9-30-14,14>>^ Nós invadimos a terra dos queretitas, a região Sul de Judá e o território do grupo de famílias de Calebe e queimamos a cidade de Ziclague.

[[v9-30-15]]

^<<v9-30-15,15>>^ Então Davi lhe perguntou: — Você pode me levar até onde os amalequitas estão? — Sim, — respondeu ele — se o senhor prometer em nome de Deus que não me matará, nem me entregará ao meu dono.

[[v9-30-16]]

^<<v9-30-16,16>>^ Então ele levou Davi. Os amalequitas estavam espalhados por toda a região, comendo, bebendo e festejando por causa da grande quantidade de coisas que haviam tomado na terra dos filisteus e na terra de Judá.

[[v9-30-17]]

^<<v9-30-17,17>>^ No dia seguinte ao amanhecer, Davi os atacou e lutou até o anoitecer. E nenhum deles escapou, a não ser quatrocentos rapazes que montaram camelos e fugiram.

[[v9-30-18]]

^<<v9-30-18,18>>^ Davi salvou todos os que tinham sido levados como prisioneiros, incluindo as suas duas mulheres, e trouxe de volta tudo o que os amalequitas haviam tomado.

[[v9-30-19]]

^<<v9-30-19,19>>^ Não ficou faltando nada: Davi levou de volta todos os filhos e todas as filhas dos seus homens e todas as coisas, grandes e pequenas, que os amalequitas haviam tomado.

[[v9-30-20]]

^<<v9-30-20,20>>^ Levou também todas as ovelhas e todo o gado. Então os homens de Davi levaram a ele os seus animais e disseram: — Estes animais são seus.

[[v9-30-21]]

^<<v9-30-21,21>>^ Aí Davi voltou para o lugar onde estavam os duzentos homens que não tinham ido com ele e haviam ficado atrás, no ribeirão de Besor, por estarem muito cansados. Eles saíram ao encontro de Davi e dos seus homens. Davi chegou perto deles e os cumprimentou.

[[v9-30-22]]

^<<v9-30-22,22>>^ Mas alguns homens ordinários e de mau caráter que tinham ido com Davi disseram: — Eles não foram conosco; por isso, não lhes daremos nada do que trouxemos. Eles podem pegar as suas mulheres e os seus filhos e ir embora.

[[v9-30-23]]

^<<v9-30-23,23>>^ Mas Davi respondeu: — Meus irmãos, vocês não podem fazer isso com o que o Senhor  Deus nos deu! Ele nos salvou e nos deu a vitória sobre os inimigos.

[[v9-30-24]]

^<<v9-30-24,24>>^ Ninguém pode concordar com o que vocês estão dizendo! Tudo deve ser repartido em partes iguais: quem ficou atrás com a bagagem deve receber o mesmo que aquele que lutou na batalha.

[[v9-30-25]]

^<<v9-30-25,25>>^ Davi fez desta ordem uma lei . E até hoje  ela é seguida em Israel.

[[v9-30-26]]

^<<v9-30-26,26>>^ Quando Davi voltou para Ziclague, pegou parte do que havia tomado dos inimigos e mandou para os seus amigos, os líderes de Judá, com esta mensagem: — Este é um presente para vocês, tirado das coisas que nós tomamos dos inimigos de Deus, o Senhor .

[[v9-30-27]]

^<<v9-30-27,27>>^ Davi mandou presentes aos líderes das seguintes cidades: Betel, Ramá, que fica ao sul de Judá, Jatir,

[[v9-30-28]]

^<<v9-30-28,28>>^ Aroer, Sifmote, Estemoa,

[[v9-30-29]]

^<<v9-30-29,29>>^ Racal, Horma, Borasã, Atace, Hebrom; e também às cidades das tribos dos jerameelitas e dos queneus — todos os lugares onde Davi e os seus homens haviam estado.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]