include::./index.adoc[]

[[v9-14-0]]
=== 1 Samuel, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-14-1]]

^<<v9-14-1,1>>^ Um dia Jônatas disse ao rapaz que carregava as suas armas: — Vamos até o acampamento filisteu, que está no outro lado do desfiladeiro. Mas Jônatas não contou ao pai o que ia fazer.

[[v9-14-2]]

^<<v9-14-2,2>>^ Saul estava em Migrom, perto de Gibeá, acampado debaixo de um pé de romã. Com ele estavam mais ou menos seiscentos homens.

[[v9-14-3]]

^<<v9-14-3,3>>^ O sacerdote que usava o manto sacerdotal  era Aías, filho de Aitube e sobrinho de Icabô. (Icabô era filho de Fineias e neto de Eli, que havia sido sacerdote do Senhor  Deus em Siló.) Os homens não sabiam que Jônatas havia saído do acampamento.

[[v9-14-4]]

^<<v9-14-4,4>>^ No desfiladeiro que Jônatas tinha de atravessar para chegar ao acampamento dos filisteus, havia duas grandes pedras, uma de cada lado da passagem. Uma era chamada de Bosês, e a outra, de Senê.

[[v9-14-5]]

^<<v9-14-5,5>>^ Uma estava no lado norte do desfiladeiro, de frente para Micmás, e a outra, no lado sul, de frente para Geba.

[[v9-14-6]]

^<<v9-14-6,6>>^ Jônatas disse ao rapaz que o acompanhava: — Vamos até o acampamento desses filisteus pagãos. Pode ser que o Senhor  nos ajude. E, se ele nos ajudar, nada poderá impedi-lo de nos dar a vitória, ainda que sejamos poucos.

[[v9-14-7]]

^<<v9-14-7,7>>^ O rapaz respondeu: — Faça o que achar melhor! Eu estou com o senhor.

[[v9-14-8]]

^<<v9-14-8,8>>^ — Muito bem! — respondeu Jônatas. — Vamos até lá e deixemos que aqueles homens nos vejam.

[[v9-14-9]]

^<<v9-14-9,9>>^ Se eles disserem para ficarmos parados até que cheguem perto de nós, nós obedeceremos.

[[v9-14-10]]

^<<v9-14-10,10>>^ Mas, se disserem para irmos até o lugar onde eles estão, nós iremos, pois isso será o sinal de que o Senhor  Deus nos deu a vitória.

[[v9-14-11]]

^<<v9-14-11,11>>^ Aí os dois deixaram que os filisteus os vissem. E estes disseram: — Vejam! Alguns hebreus estão saindo das tocas onde estavam escondidos.

[[v9-14-12]]

^<<v9-14-12,12>>^ Então os soldados filisteus chamaram Jônatas e o rapaz: — Subam até aqui! Queremos mostrar uma coisa a vocês. Jônatas disse ao rapaz: — Siga-me, pois o Senhor  Deus deu ao povo de Israel a vitória sobre os filisteus.

[[v9-14-13]]

^<<v9-14-13,13>>^ Ele subiu engatinhando, e o rapaz o seguiu. Jônatas ia atacando e derrubando os filisteus, e o rapaz os ia matando.

[[v9-14-14]]

^<<v9-14-14,14>>^ Nesse primeiro ataque eles mataram cerca de vinte homens, em uma área de mais ou menos mil e duzentos metros quadrados.

[[v9-14-15]]

^<<v9-14-15,15>>^ Todos os filisteus que estavam no acampamento ficaram apavorados. Os patrulheiros e os soldados do acampamento tremeram de medo. A terra também tremeu, e houve uma grande confusão.

[[v9-14-16]]

^<<v9-14-16,16>>^ Os espiões de Saul que estavam em Gibeá, no território da tribo  de Benjamim, viram que os filisteus estavam tontos, correndo para cá e para lá.

[[v9-14-17]]

^<<v9-14-17,17>>^ Então Saul disse aos seus oficiais: — Contem os nossos soldados e vejam quem está faltando. Eles contaram e descobriram que estavam faltando Jônatas e o rapaz que carregava as suas armas.

[[v9-14-18]]

^<<v9-14-18,18>>^ Aí Saul disse a Aías, o sacerdote: — Traga aqui a arca da aliança . Ele disse isso porque naquele tempo a arca ia na frente do povo de Israel.

[[v9-14-19]]

^<<v9-14-19,19>>^ Enquanto Saul falava com o sacerdote, a confusão no acampamento filisteu aumentava cada vez mais. Então Saul disse ao sacerdote: — Você não precisa mais consultar o Senhor .

[[v9-14-20]]

^<<v9-14-20,20>>^ Aí ele e os seus homens entraram na batalha contra os filisteus. Estes, em completa confusão, estavam lutando uns contra os outros.

[[v9-14-21]]

^<<v9-14-21,21>>^ Os hebreus que haviam passado para o lado dos filisteus e tinham ido para o acampamento com eles mudaram de lado outra vez e se juntaram com Saul e Jônatas.

[[v9-14-22]]

^<<v9-14-22,22>>^ Os israelitas que estavam escondidos nas montanhas de Efraim também souberam que os filisteus estavam fugindo. Eles se reuniram e atacaram os filisteus,

[[v9-14-23]]

^<<v9-14-23,23>>^ lutando todo o caminho até além de Bete-Avém. E o Senhor  Deus deu naquele dia a vitória ao povo de Israel.

[[v9-14-24]]

^<<v9-14-24,24>>^ Naquele dia os israelitas estavam fracos de fome porque Saul havia feito este juramento: "Quem comer qualquer coisa hoje, antes de eu me vingar dos meus inimigos, será amaldiçoado." Por isso, ninguém tinha comido nada o dia inteiro.

[[v9-14-25]]

^<<v9-14-25,25>>^ Todos eles chegaram a um bosque e ali acharam mel por toda parte.

[[v9-14-26]]

^<<v9-14-26,26>>^ As árvores estavam cheias de mel, mas ninguém comeu nada porque eles estavam com medo do juramento de Saul.

[[v9-14-27]]

^<<v9-14-27,27>>^ Mas Jônatas não tinha ouvido o seu pai dar a ordem ao povo. Por isso, estendeu o bastão que tinha na mão, molhou a ponta num favo e comeu um pouco de mel. E logo se sentiu melhor.

[[v9-14-28]]

^<<v9-14-28,28>>^ Mas um dos homens disse: — Todos estão fracos de fome porque o seu pai nos ameaçou, dizendo: "Quem comer qualquer coisa hoje será amaldiçoado!"

[[v9-14-29]]

^<<v9-14-29,29>>^ Então Jônatas respondeu: — O meu pai fez uma coisa terrível com o nosso povo. Vejam como estou me sentindo melhor depois de comer um pouco deste mel!

[[v9-14-30]]

^<<v9-14-30,30>>^ Teria sido bem melhor se hoje o nosso povo tivesse comido o alimento que tomou do inimigo quando o derrotou. Imaginem quantos filisteus mais eles teriam matado!

[[v9-14-31]]

^<<v9-14-31,31>>^ Naquele dia os israelitas derrotaram os filisteus, lutando desde Micmás até Aijalom. A essa altura os israelitas estavam muito fracos de fome.

[[v9-14-32]]

^<<v9-14-32,32>>^ Por isso, avançaram sobre o que haviam tirado dos inimigos, isto é, as ovelhas, as vacas e os bezerros, e os mataram ali mesmo e comeram a carne com o sangue.

[[v9-14-33]]

^<<v9-14-33,33>>^ Aí alguém foi dizer a Saul: — Olhe! O povo está pecando contra Deus, comendo carne sem primeiro deixar escorrer o sangue. Saul gritou: — Isso é traição! Rolem aqui para mim uma pedra grande.

[[v9-14-34]]

^<<v9-14-34,34>>^ E ordenou ainda: — Vão para o meio do povo e digam a eles que tragam aqui o seu gado e as suas ovelhas. E que os matem e os comam aqui. E que não pequem contra Deus, comendo carne com sangue. Por isso, naquela noite, todos trouxeram o seu gado e o mataram ali.

[[v9-14-35]]

^<<v9-14-35,35>>^ E Saul construiu um altar para o Senhor  Deus, e esse foi o primeiro que ele construiu.

[[v9-14-36]]

^<<v9-14-36,36>>^ Aí Saul disse aos seus soldados: — Vamos descer de noite e atacar os filisteus. Até o amanhecer nós tomaremos tudo o que eles têm e não deixaremos nenhum filisteu vivo. Eles responderam: — Faça o que achar melhor. Mas o sacerdote disse: — Primeiro vamos consultar a Deus.

[[v9-14-37]]

^<<v9-14-37,37>>^ Aí Saul perguntou a Deus: — Devo atacar os filisteus? Tu darás a vitória ao povo de Israel? Mas naquele dia Deus não respondeu nada.

[[v9-14-38]]

^<<v9-14-38,38>>^ Então Saul disse aos oficiais: — Venham aqui e descubram que pecado foi cometido hoje.

[[v9-14-39]]

^<<v9-14-39,39>>^ Eu prometo pelo Senhor , o Deus vivo, o Salvador de Israel, que, mesmo que o culpado seja o meu filho Jônatas, eu o matarei. Mas ninguém respondeu nada.

[[v9-14-40]]

^<<v9-14-40,40>>^ Então Saul ordenou: — Fiquem todos de um lado. Eu e o meu filho Jônatas ficaremos do outro. — Faça o que achar melhor! — responderam eles.

[[v9-14-41]]

^<<v9-14-41,41>>^ Então Saul disse ao Senhor , o Deus de Israel: — Ó Deus, por que não me respondeste hoje? Ó Senhor , Deus de Israel, responde por meio do sorteio . Se a culpa for minha ou de Jônatas, responde pela pedra marcada Urim ; mas, se a culpa for de Israel, o teu povo, responde pela pedra marcada Tumim. E a resposta indicou Jônatas e Saul e não os soldados.

[[v9-14-42]]

^<<v9-14-42,42>>^ Então Saul disse: — Façam o sorteio para saber se a culpa é minha ou do meu filho Jônatas. E Jônatas foi indicado.

[[v9-14-43]]

^<<v9-14-43,43>>^ Então Saul perguntou: — O que foi que você fez? — Eu comi um pouco de mel que tirei com a ponta do bastão que eu tinha na mão! — respondeu Jônatas. — E estou aqui, pronto para morrer.

[[v9-14-44]]

^<<v9-14-44,44>>^ — Que Deus me mate se você não for morto! — disse Saul.

[[v9-14-45]]

^<<v9-14-45,45>>^ Mas os soldados responderam: — Isso, nunca! Jônatas, que deu esta grande vitória ao povo de Israel, não deve morrer. Nós prometemos pelo Senhor , o Deus vivo, que ele não vai perder nem um fio de cabelo. O que ele fez hoje foi conseguido com a ajuda de Deus. E assim os soldados salvaram Jônatas da morte.

[[v9-14-46]]

^<<v9-14-46,46>>^ Saul parou de perseguir os filisteus, e eles voltaram para a sua terra.

[[v9-14-47]]

^<<v9-14-47,47>>^ Depois que se tornou o rei de Israel, Saul lutou contra todos os povos vizinhos que eram seus inimigos: os povos de Moabe, de Amom e de Edom, os reis de Zoba e os filisteus. E em toda parte em que lutava era vitorioso.

[[v9-14-48]]

^<<v9-14-48,48>>^ Saul lutou corajosamente e venceu os amalequitas. E defendeu o povo de Israel de todos os ataques.

[[v9-14-49]]

^<<v9-14-49,49>>^ Saul tinha três filhos homens: Jônatas, Isvi e Malquisua. A sua filha mais velha chamava-se Merabe, e a mais nova, Mical.

[[v9-14-50]]

^<<v9-14-50,50>>^ A sua mulher chamava-se Ainoã e era filha de Aimaás. O comandante do exército de Saul era o seu primo Abner, filho de seu tio Ner.

[[v9-14-51]]

^<<v9-14-51,51>>^ Quis, o pai de Saul, e Ner, o pai de Abner, eram filhos de Abiel.

[[v9-14-52]]

^<<v9-14-52,52>>^ Durante toda a sua vida Saul lutou ferozmente contra os filisteus. E, sempre que encontrava um homem forte e valente, ele o alistava no seu exército.

'''

xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[&#60; Capítulo Anterior] | <<v9-14-0,Topo>> | xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[Próximo Capítulo &#62;]