include::./index.adoc[]

[[v9-13-0]]
=== 1 Samuel, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-13-1]]

^<<v9-13-1,1>>^ Saul já era adulto quando se tornou rei e governou o povo de Israel dois anos .

[[v9-13-2]]

^<<v9-13-2,2>>^ Ele escolheu três mil israelitas e mandou todos os outros de volta para casa. Dois mil estavam na cidade de Micmás e na região montanhosa de Betel. Mil homens ficaram com o seu filho Jônatas, na cidade de Gibeá, no território da tribo  de Benjamim.

[[v9-13-3]]

^<<v9-13-3,3>>^ Jônatas matou o comandante filisteu, em Geba, e os filisteus ficaram sabendo disso. Aí Saul mandou mensageiros para tocarem corneta por todo o país, chamando os hebreus para a guerra.

[[v9-13-4]]

^<<v9-13-4,4>>^ E todo o povo ouviu esta mensagem: "Saul matou o comandante dos filisteus, e agora eles estão com ódio dos israelitas." Então o povo respondeu ao chamado e foi juntar-se a Saul, em Gilgal.

[[v9-13-5]]

^<<v9-13-5,5>>^ Os filisteus se reuniram para lutar contra os israelitas. Eles tinham trinta mil carros de guerra, seis mil cavaleiros e tantos soldados quantos os grãos de areia da praia do mar. Foram até Micmás, a leste da cidade de Bete-Avém, e acamparam ali.

[[v9-13-6]]

^<<v9-13-6,6>>^ Os israelitas perceberam que estavam sem saída e numa situação muito difícil. Alguns se esconderam em cavernas e em buracos, e outros, entre rochas, em covas e em poços.

[[v9-13-7]]

^<<v9-13-7,7>>^ Outros ainda atravessaram o rio Jordão e foram para as terras de Gade e de Gileade. Saul havia ficado em Gilgal, e o povo dali estava apavorado.

[[v9-13-8]]

^<<v9-13-8,8>>^ Seguindo as instruções de Samuel, Saul esperou sete dias, mas Samuel não foi até lá. E o povo começou a abandonar Saul e sair dali.

[[v9-13-9]]

^<<v9-13-9,9>>^ Então Saul lhes disse: — Tragam os animais para o sacrifício  que é completamente queimado e para as ofertas de paz. Ele ofereceu o sacrifício,

[[v9-13-10]]

^<<v9-13-10,10>>^ e, quando estava terminando, Samuel chegou. Saul foi ao encontro dele, para o cumprimentar,

[[v9-13-11]]

^<<v9-13-11,11>>^ mas Samuel disse: — O que foi que você fez? Saul respondeu: — Eu percebi que o povo estava me abandonando e indo embora. Você também não veio como havia prometido, e os filisteus já estavam reunidos em Micmás.

[[v9-13-12]]

^<<v9-13-12,12>>^ Aí eu pensei: "Os filisteus vão descer a Gilgal para me atacar, e eu ainda não tentei conseguir a ajuda de Deus, o Senhor ." Então achei que tinha de oferecer o sacrifício.

[[v9-13-13]]

^<<v9-13-13,13>>^ — O que você fez foi uma loucura! — respondeu Samuel. — Você não obedeceu à ordem do Senhor , nosso Deus. Se tivesse obedecido, ele teria deixado que você e os seus descendentes governassem o povo de Israel para sempre.

[[v9-13-14]]

^<<v9-13-14,14>>^ Mas agora você não continuará a governar. Você desobedeceu ao Senhor , e por isso ele vai encontrar um homem do tipo que ele quer e o fará chefe deste povo.

[[v9-13-15]]

^<<v9-13-15,15>>^ Aí Samuel saiu de Gilgal e foi embora. Saul, acompanhado pelo resto do povo, também deixou Gilgal e foi para junto dos seus soldados, em Gibeá, no território da tribo de Benjamim. Então ele fez uma contagem dos seus soldados: eram mais ou menos seiscentos homens.

[[v9-13-16]]

^<<v9-13-16,16>>^ Saul, o seu filho Jônatas e os seus homens ficaram em Geba, no território de Benjamim. Os filisteus estavam acampados em Micmás.

[[v9-13-17]]

^<<v9-13-17,17>>^ Os soldados filisteus saíram para patrulhar em três grupos: um grupo foi na direção de Ofra, na terra de Sual,

[[v9-13-18]]

^<<v9-13-18,18>>^ o outro seguiu rumo a Bete-Horom, e o terceiro, na direção do monte de onde se avista o vale de Zeboim e o deserto.

[[v9-13-19]]

^<<v9-13-19,19>>^ Os filisteus haviam proibido os hebreus de fazerem espadas e lanças. Por isso, não havia nenhum ferreiro na terra de Israel.

[[v9-13-20]]

^<<v9-13-20,20>>^ Assim, quando os arados, as enxadas, os machados e as foices dos israelitas precisavam ser amolados, eles os levavam aos filisteus.

[[v9-13-21]]

^<<v9-13-21,21>>^ Estes cobravam caro dos israelitas para afiar machados e ferrões de tocar bois e mais caro ainda para afiar arados e enxadas.

[[v9-13-22]]

^<<v9-13-22,22>>^ Por isso, no dia da batalha, nenhum soldado israelita tinha nem espada nem lança; só Saul e o seu filho Jônatas é que tinham.

[[v9-13-23]]

^<<v9-13-23,23>>^ Os filisteus mandaram um grupo de soldados para defender o desfiladeiro de Micmás.

'''

xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[&#60; Capítulo Anterior] | <<v9-13-0,Topo>> | xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[Próximo Capítulo &#62;]