include::./index.adoc[]

[[v9-21-0]]
=== 1 Samuel, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-21-1]]

^<<v9-21-1,1>>^ Davi foi falar com o sacerdote Aimeleque, em Nobe. O sacerdote saiu tremendo para se encontrar com Davi e disse: — Por que é que você veio aqui sozinho?

[[v9-21-2]]

^<<v9-21-2,2>>^ Davi respondeu: — Estou aqui a serviço do rei. Ele ordenou que eu não deixasse ninguém saber o que ele me mandou fazer. Por isso, mandei que os meus soldados fossem encontrar-se comigo em certo lugar.

[[v9-21-3]]

^<<v9-21-3,3>>^ Agora diga: o que é que você tem para comer? Me dê uns cinco pães ou qualquer outra coisa que você tiver.

[[v9-21-4]]

^<<v9-21-4,4>>^ O sacerdote disse: — Eu não tenho pão comum; só pão sagrado. Você pode levá-lo, se é que já faz algum tempo que os seus soldados não tiveram relações sexuais.

[[v9-21-5]]

^<<v9-21-5,5>>^ Davi respondeu: — Claro que não tiveram. Nós não estivemos com nenhuma mulher. Os meus homens sempre se mantêm puros  quando saímos em missão comum. Quanto mais agora que estamos em missão especial!

[[v9-21-6]]

^<<v9-21-6,6>>^ Então o sacerdote deu a Davi os pães sagrados porque ele só tinha os pães que haviam sido oferecidos a Deus, o Senhor . Esses pães tinham sido tirados da mesa sagrada e trocados por pães frescos.

[[v9-21-7]]

^<<v9-21-7,7>>^ Acontece que Doegue, o edomita, que era o chefe dos pastores de Saul, estava ali naquele dia porque tinha de cumprir um dever religioso.

[[v9-21-8]]

^<<v9-21-8,8>>^ Davi disse a Aimeleque: — Você tem uma espada ou uma lança para me dar? Eu não trouxe a minha espada nem outra arma. Por causa das ordens do rei, eu saí com muita pressa.

[[v9-21-9]]

^<<v9-21-9,9>>^ Aimeleque respondeu: — Tenho a espada de Golias, o filisteu, que você matou no vale do Carvalho. Ela está atrás do manto sacerdotal , enrolada num pano. Leve-a se quiser. É a única arma que há aqui. Davi disse: — Não existe espada melhor do que essa. Pode me dar.

[[v9-21-10]]

^<<v9-21-10,10>>^ Então Davi saiu, fugindo de Saul, e foi procurar Aquis, o governador da cidade de Gate.

[[v9-21-11]]

^<<v9-21-11,11>>^ As autoridades da cidade disseram a Aquis: — Não há dúvida de que este é Davi, o rei da terra de Israel. A respeito dele as mulheres cantavam enquanto dançavam: "Saul matou mil; Davi matou dez mil!"

[[v9-21-12]]

^<<v9-21-12,12>>^ Davi assustou-se com as palavras deles e ficou com muito medo de Aquis.

[[v9-21-13]]

^<<v9-21-13,13>>^ Então, na frente de todos eles, fez de conta que estava louco. Quando tentaram segurá-lo, ele começou a agir como doido: rabiscava os portões da cidade e deixava escorrer saliva pela barba.

[[v9-21-14]]

^<<v9-21-14,14>>^ Então Aquis disse aos seus oficiais: — Este homem está louco! Por que o trouxeram para cá?

[[v9-21-15]]

^<<v9-21-15,15>>^ Será que já não tenho bastantes loucos em volta de mim? Por que trazem outro doido para a minha própria casa, a fim de me aborrecer com as suas loucuras?

'''

xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[&#60; Capítulo Anterior] | <<v9-21-0,Topo>> | xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[Próximo Capítulo &#62;]