include::./index.adoc[]

[[v9-31-0]]
=== 1 Samuel, 31
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-31-1]]

^<<v9-31-1,1>>^ Os filisteus lutaram contra os israelitas no monte Gilboa. Muitos israelitas foram mortos ali, e o resto fugiu.

[[v9-31-2]]

^<<v9-31-2,2>>^ Os filisteus cercaram Saul e os seus filhos e mataram Jônatas, Abinadabe e Malquisua, os filhos de Saul.

[[v9-31-3]]

^<<v9-31-3,3>>^ A luta estava feroz em volta de Saul. Ele foi atingido por flechas inimigas e ficou muito ferido.

[[v9-31-4]]

^<<v9-31-4,4>>^ Então disse ao rapaz que carregava as suas armas: — Tire a sua espada e me mate para que esses filisteus pagãos não caçoem de mim e me matem. Mas o rapaz estava muito apavorado e não quis fazer isso. Então Saul pegou a sua própria espada e se jogou sobre ela.

[[v9-31-5]]

^<<v9-31-5,5>>^ Quando viu que Saul estava morto, o rapaz também se jogou sobre a sua própria espada e morreu junto com ele.

[[v9-31-6]]

^<<v9-31-6,6>>^ E assim morreram naquele dia Saul, os seus três filhos, o rapaz e todos os soldados de Saul.

[[v9-31-7]]

^<<v9-31-7,7>>^ Quando os israelitas que moravam no outro lado do vale de Jezreel e a leste do rio Jordão viram que o exército israelita havia fugido e que Saul e os seus filhos tinham sido mortos, abandonaram as suas cidades e fugiram. Então os filisteus foram e ocuparam aquelas cidades.

[[v9-31-8]]

^<<v9-31-8,8>>^ Um dia depois da batalha, quando os filisteus voltaram lá para tirar dos mortos as coisas de valor, acharam os corpos de Saul e dos seus três filhos caídos no monte Gilboa.

[[v9-31-9]]

^<<v9-31-9,9>>^ Então cortaram a cabeça de Saul e tiraram a sua armadura . Depois mandaram mensageiros com elas para a sua terra, para darem as boas notícias aos seus ídolos e ao povo.

[[v9-31-10]]

^<<v9-31-10,10>>^ Eles puseram as armas de Saul no templo da deusa Astarote  e pregaram o corpo dele na muralha da cidade de Bete-Sã.

[[v9-31-11]]

^<<v9-31-11,11>>^ Quando o povo de Jabes, na região de Gileade, soube do que os filisteus haviam feito com Saul,

[[v9-31-12]]

^<<v9-31-12,12>>^ os seus moradores mais corajosos saíram e marcharam a noite inteira, até chegarem a Bete-Sã. Tiraram da muralha os corpos de Saul e dos seus três filhos, levaram de volta para Jabes e ali os queimaram.

[[v9-31-13]]

^<<v9-31-13,13>>^ Então pegaram os ossos e sepultaram na cidade, debaixo de uma árvore de tâmaras . E jejuaram sete dias.

'''

xref:009-1-samuel/009-1-samuel-030.adoc#v9-30-0[&#60; Capítulo Anterior] | <<v9-31-0,Topo>> | xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[Próximo Capítulo &#62;]