include::./index.adoc[]

[[v9-9-0]]
=== 1 Samuel, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-9-1]]

^<<v9-9-1,1>>^ Havia um homem chamado Quis, que era da tribo  de Benjamim. Ele era filho de Abiel, neto de Zeror, bisneto de Becorate e trineto de Afias. Quis era rico e importante.

[[v9-9-2]]

^<<v9-9-2,2>>^ Tinha um filho jovem e bonito, chamado Saul. Não havia ninguém mais bonito do que ele entre todos os israelitas. Além disso era mais alto do que todos. Quando estava no meio do povo, ele aparecia dos ombros para cima.

[[v9-9-3]]

^<<v9-9-3,3>>^ E aconteceu que algumas jumentas que pertenciam a Quis, o pai de Saul, se perderam. Então ele disse a Saul: — Filho, leve com você um dos nossos empregados e vá procurar as jumentas.

[[v9-9-4]]

^<<v9-9-4,4>>^ Eles foram por toda a região montanhosa de Efraim e pela terra de Salisa, porém não acharam as jumentas. Então procuraram na terra de Saalim, porém elas não estavam lá. Aí procuraram no território da tribo de Benjamim, mas também não as encontraram.

[[v9-9-5]]

^<<v9-9-5,5>>^ Quando entraram na terra de Zufe, Saul disse ao empregado: — Vamos voltar para casa; se não, em vez de se preocupar com as jumentas, o meu pai vai acabar se preocupando com a gente.

[[v9-9-6]]

^<<v9-9-6,6>>^ O empregado respondeu: — Espere. Nesta cidade mora um homem santo que é muito respeitado porque tudo o que ele diz acontece. Vamos falar com ele. Talvez ele possa nos dizer onde podemos encontrar as jumentas.

[[v9-9-7]]

^<<v9-9-7,7>>^ Saul perguntou: — Se formos lá, o que vamos levar para ele? Não há comida nas nossas sacolas, e não temos nada para lhe dar. Ou será que temos?

[[v9-9-8]]

^<<v9-9-8,8>>^ O empregado respondeu: — Tenho uma pequena quantia de prata que posso dar a ele para que nos conte onde poderemos achar as jumentas.

[[v9-9-9]]

^<<v9-9-9,9>>^ — É uma boa ideia! — respondeu Saul. — Vamos. Então eles foram à cidade onde o homem santo morava. Quando estavam subindo o morro para chegar à cidade, encontraram algumas moças que estavam saindo para tirar água. Eles perguntaram: — O vidente  está na cidade? (Antigamente, quando alguém queria fazer uma pergunta a Deus, costumava dizer: "Vamos falar com o vidente." Porque naquele tempo os profetas  eram chamados de videntes.)

[[v9-9-10]]

^<<v9-9-10,10>>^ — É uma boa ideia! — respondeu Saul. — Vamos.

[[v9-9-11]]

^<<v9-9-11,11>>^ — É uma boa ideia! — respondeu Saul. — Vamos.

[[v9-9-12]]

^<<v9-9-12,12>>^ — Ele está, sim! — responderam elas. — Olhem! Ali vai ele, ali na frente. Andem depressa. Ele está entrando na cidade porque o povo vai oferecer hoje um sacrifício  no altar do monte.

[[v9-9-13]]

^<<v9-9-13,13>>^ Assim que entrarem na cidade, vocês o encontrarão antes que ele suba o monte para comer. O povo não começa a comer antes que ele chegue lá, pois primeiro ele tem de abençoar o sacrifício. Só depois é que os convidados podem comer. Subam lá agora e logo vocês o encontrarão.

[[v9-9-14]]

^<<v9-9-14,14>>^ Então eles foram até a cidade. Quando iam entrando, viram Samuel, que saía para subir até o lugar de adoração.

[[v9-9-15]]

^<<v9-9-15,15>>^ Um dia antes de Saul chegar, o Senhor  Deus tinha dito a Samuel:

[[v9-9-16]]

^<<v9-9-16,16>>^ — Amanhã, a esta hora, eu vou enviar a você um homem da tribo de Benjamim. Você o ungirá  para ser o governador do meu povo de Israel. Ele libertará o povo do domínio dos filisteus. Eu tenho visto o sofrimento do meu povo e ouvido os seus pedidos de ajuda.

[[v9-9-17]]

^<<v9-9-17,17>>^ Quando Samuel viu Saul, o Senhor  lhe disse: — Este é o homem de quem lhe falei. Ele governará o meu povo.

[[v9-9-18]]

^<<v9-9-18,18>>^ Saul foi encontrar-se com Samuel, perto do portão, e perguntou: — Por favor, onde mora o vidente?

[[v9-9-19]]

^<<v9-9-19,19>>^ Samuel respondeu: — Eu sou o vidente. Vá adiante de mim até o lugar de adoração. Vocês dois vão jantar comigo hoje. Amanhã cedo eu responderei a todas as suas perguntas, e então vocês poderão ir embora.

[[v9-9-20]]

^<<v9-9-20,20>>^ E não se preocupe com as jumentas que se perderam há três dias, pois elas já foram encontradas. Afinal, quem é que o povo de Israel está querendo? Eles querem é você — você e a família do seu pai.

[[v9-9-21]]

^<<v9-9-21,21>>^ Saul respondeu: — Eu sou da tribo de Benjamim, a menor de Israel, e a minha família é a menos importante da tribo. Então por que o senhor está falando comigo desse jeito?

[[v9-9-22]]

^<<v9-9-22,22>>^ Aí Samuel levou Saul e o seu empregado para o salão de festas e pediu que os dois sentassem à cabeceira da mesa. Ao redor dessa mesa estavam sentados mais ou menos trinta convidados.

[[v9-9-23]]

^<<v9-9-23,23>>^ E Samuel disse ao cozinheiro: — Traga aquele pedaço de carne que eu lhe entreguei e pedi para deixar reservado.

[[v9-9-24]]

^<<v9-9-24,24>>^ O cozinheiro pegou o melhor pedaço da perna e o pôs na frente de Saul. Samuel disse: — Olhe! Aqui está o pedaço que foi reservado para você. Coma-o, pois foi guardado para você comer nesta ocasião em que convidei o povo. E assim, naquele dia, Saul jantou com Samuel.

[[v9-9-25]]

^<<v9-9-25,25>>^ Depois os dois desceram do lugar de adoração para a cidade. Aí arrumaram uma cama para Saul no terraço,

'''

xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[&#60; Capítulo Anterior] | <<v9-9-0,Topo>> | xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[Próximo Capítulo &#62;]