include::./index.adoc[]

[[v9-16-0]]
=== 1 Samuel, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-16-1]]

^<<v9-16-1,1>>^ O Senhor  Deus disse a Samuel: — Até quando você vai continuar a ter pena de Saul? Eu não quero mais que ele seja rei de Israel. Encha um chifre com azeite e leve com você. Depois vá a Belém, até a casa de um homem chamado Jessé, pois eu escolhi um dos filhos dele para ser rei.

[[v9-16-2]]

^<<v9-16-2,2>>^ — Como posso fazer isso? — respondeu Samuel. — Se Saul souber disso, ele me mata! O Senhor  Deus respondeu: — Leve um bezerro e diga que você foi lá para oferecer um sacrifício  ao Senhor .

[[v9-16-3]]

^<<v9-16-3,3>>^ Convide Jessé para o sacrifício, e depois eu lhe digo o que fazer. Você ungirá  como rei aquele que eu indicar.

[[v9-16-4]]

^<<v9-16-4,4>>^ Samuel fez o que o Senhor  Deus havia mandado e foi a Belém. Quando chegou lá, os líderes da cidade foram tremendo encontrá-lo e perguntaram: — A sua visita é de paz?

[[v9-16-5]]

^<<v9-16-5,5>>^ — Sim! — respondeu ele. — Eu vim oferecer um sacrifício a Deus. Purifiquem-se  e venham comigo. Ele mandou que Jessé e os seus filhos se purificassem e os convidou para o sacrifício.

[[v9-16-6]]

^<<v9-16-6,6>>^ Quando eles chegaram, Samuel viu Eliabe, um dos filhos de Jessé, e pensou: — Este homem que está aqui na presença de Deus, o Senhor , certamente é aquele que o Senhor  escolheu.

[[v9-16-7]]

^<<v9-16-7,7>>^ Mas o Senhor  disse: — Não se impressione com a aparência nem com a altura deste homem. Eu o rejeitei porque não julgo como as pessoas julgam. Elas olham para a aparência, mas eu vejo o coração.

[[v9-16-8]]

^<<v9-16-8,8>>^ Então Jessé chamou o seu filho Abinadabe e o levou a Samuel. Mas Samuel disse: — Este também não foi escolhido pelo Senhor .

[[v9-16-9]]

^<<v9-16-9,9>>^ Aí Jessé trouxe o seu filho Simeia. E Samuel disse: — O Senhor  Deus também não escolheu este.

[[v9-16-10]]

^<<v9-16-10,10>>^ Assim Jessé apresentou a Samuel sete dos seus filhos. E Samuel disse: — O Senhor  Deus não escolheu nenhum destes.

[[v9-16-11]]

^<<v9-16-11,11>>^ E perguntou a Jessé: — Você não tem mais nenhum filho? Jessé respondeu: — Tenho mais um, o caçula, mas ele está fora, tomando conta das ovelhas. — Então mande chamá-lo! — disse Samuel. — Nós não vamos oferecer o sacrifício enquanto ele não vier.

[[v9-16-12]]

^<<v9-16-12,12>>^ Aí Jessé mandou buscá-lo. Era um belo rapaz, saudável e de olhos brilhantes. E o Senhor  disse a Samuel: — É este mesmo. Unja-o.

[[v9-16-13]]

^<<v9-16-13,13>>^ Samuel pegou o chifre cheio de azeite e ungiu Davi na frente dos seus irmãos. E o Espírito do Senhor  dominou Davi e daquele dia em diante ficou com ele. E Samuel voltou para Ramá.

[[v9-16-14]]

^<<v9-16-14,14>>^ O Espírito do Senhor  saiu de Saul, e um espírito mau, mandado por Deus, começou a atormentá-lo.

[[v9-16-15]]

^<<v9-16-15,15>>^ Então os empregados de Saul lhe disseram: — Sabemos que um espírito mau mandado por Deus está atormentando o senhor.

[[v9-16-16]]

^<<v9-16-16,16>>^ Mande, e nós iremos procurar um homem que saiba tocar lira . Assim, quando o espírito mau vier sobre o senhor, o homem tocará a lira, e o senhor ficará bom de novo.

[[v9-16-17]]

^<<v9-16-17,17>>^ E Saul ordenou: — Procurem um homem que toque bem lira e o tragam aqui.

[[v9-16-18]]

^<<v9-16-18,18>>^ Um dos empregados respondeu: — Jessé, da cidade de Belém, tem um filho que é bom músico. Ele também é valente, bom soldado, fala bem, tem boa aparência, e o Senhor  Deus está com ele.

[[v9-16-19]]

^<<v9-16-19,19>>^ Aí Saul enviou mensageiros com este recado para Jessé: — Mande-me o seu filho Davi, aquele que toma conta das ovelhas.

[[v9-16-20]]

^<<v9-16-20,20>>^ Então Jessé mandou Davi a Saul, e Davi levou de presente um odre  cheio de vinho, um cabrito e um jumento carregado de pão.

[[v9-16-21]]

^<<v9-16-21,21>>^ Davi foi e ficou trabalhando para Saul. Este gostou muito de Davi e o escolheu para carregar as suas armas.

[[v9-16-22]]

^<<v9-16-22,22>>^ E mandou a seguinte mensagem a Jessé: — Eu gostei de Davi. Deixe que ele fique aqui a meu serviço.

[[v9-16-23]]

^<<v9-16-23,23>>^ Daí em diante, toda vez que o espírito mau mandado por Deus vinha sobre Saul, Davi pegava a sua lira e tocava. O espírito mau saía de Saul, e ele se sentia melhor e ficava bom novamente.

'''

xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[&#60; Capítulo Anterior] | <<v9-16-0,Topo>> | xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[Próximo Capítulo &#62;]