include::./index.adoc[]

[[v9-24-0]]
=== 1 Samuel, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-24-1]]

^<<v9-24-1,1>>^ Quando Saul voltou da luta contra os filisteus, soube que Davi estava na região deserta que fica perto da fonte de Gedi.

[[v9-24-2]]

^<<v9-24-2,2>>^ Então escolheu três mil dos melhores soldados de Israel e foi com eles procurar Davi e os seus homens a leste das Rochas dos Cabritos Selvagens.

[[v9-24-3]]

^<<v9-24-3,3>>^ Saul chegou a uma caverna junto de alguns currais de ovelhas, perto da estrada, e entrou ali para satisfazer as suas necessidades. Aconteceu que Davi e os seus homens estavam escondidos mais no fundo da caverna.

[[v9-24-4]]

^<<v9-24-4,4>>^ Então eles disseram a Davi: — Esta é a sua oportunidade! O Senhor  Deus disse que lhe entregaria o seu inimigo e que você poderia fazer com ele o que quisesse. Então Davi se arrastou de mansinho até onde estava Saul e cortou um pedaço da capa  dele, sem que ele percebesse.

[[v9-24-5]]

^<<v9-24-5,5>>^ Mas aí a consciência de Davi começou a doer porque ele havia cortado um pedaço da roupa de Saul.

[[v9-24-6]]

^<<v9-24-6,6>>^ Então disse aos seus homens: — O Senhor  Deus me livre de fazer algum mal ao meu senhor, que ele escolheu como rei! Eu não devo atacá-lo de jeito nenhum porque ele é o rei escolhido pelo Senhor .

[[v9-24-7]]

^<<v9-24-7,7>>^ Assim Davi convenceu os seus homens de que eles não deviam atacar Saul. Então Saul levantou-se, saiu da caverna e seguiu o seu caminho.

[[v9-24-8]]

^<<v9-24-8,8>>^ Davi saiu atrás dele e gritou: — Rei Saul! Ele virou-se, e Davi, em sinal de respeito, se ajoelhou e encostou o rosto no chão.

[[v9-24-9]]

^<<v9-24-9,9>>^ Então disse: — Por que é que o senhor dá atenção às pessoas que dizem que eu quero prejudicá-lo?

[[v9-24-10]]

^<<v9-24-10,10>>^ O senhor pode ver por si mesmo que hoje na caverna o Senhor  Deus o entregou a mim. Alguns me disseram que o matasse, mas eu não quis fazer isso. E disse que não levantaria um dedo contra o senhor, pois o Senhor  o escolheu para ser rei.

[[v9-24-11]]

^<<v9-24-11,11>>^ Veja, meu pai, veja o pedaço da sua capa que está na minha mão! Eu cortei o pano, mas não matei o senhor. Isso prova que eu não penso em me revoltar contra o senhor, nem em fazer-lhe nenhum mal. Eu sabia muito bem que o senhor está procurando me matar, mas mesmo assim eu não o ataquei!

[[v9-24-12]]

^<<v9-24-12,12>>^ Que o Senhor  julgue qual de nós dois está errado! E que ele castigue o senhor pelo que fez contra mim, pois eu não vou atacá-lo de jeito nenhum!

[[v9-24-13]]

^<<v9-24-13,13>>^ Como diz o velho ditado: "O mal vem dos maus." Mas eu não lhe farei nenhum mal.

[[v9-24-14]]

^<<v9-24-14,14>>^ Vejam o que o rei de Israel está tentando matar! Vejam só o que ele está caçando: um cachorro morto, uma pulga!

[[v9-24-15]]

^<<v9-24-15,15>>^ O Senhor  Deus vai julgar e decidir qual de nós dois está errado. Que ele me julgue, me defenda e me livre do senhor!

[[v9-24-16]]

^<<v9-24-16,16>>^ Quando Davi acabou de falar, Saul disse: — É você mesmo, meu filho Davi? E Saul começou a chorar.

[[v9-24-17]]

^<<v9-24-17,17>>^ Então disse a Davi: — Você está certo, e eu estou errado. Você tem sido muito bom para mim enquanto que eu lhe tenho feito muito mal.

[[v9-24-18]]

^<<v9-24-18,18>>^ Hoje você mostrou o quanto é bom para mim, pois não me matou, embora o Senhor  me tivesse entregado a você.

[[v9-24-19]]

^<<v9-24-19,19>>^ Será que alguém, depois de pegar o seu inimigo, o deixa ir embora são e salvo? Que o Senhor  o abençoe pelo que você fez por mim hoje!

[[v9-24-20]]

^<<v9-24-20,20>>^ Agora estou certo de que você será rei de Israel e de que durante o seu governo o reino continuará firme.

[[v9-24-21]]

^<<v9-24-21,21>>^ Mas jure em nome do Senhor  que você não acabará com os meus descendentes, e assim o meu nome e o nome da minha família não serão esquecidos.

[[v9-24-22]]

^<<v9-24-22,22>>^ E Davi jurou. Então Saul foi para casa, e Davi e os seus homens voltaram para a fortaleza.

'''

xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[&#60; Capítulo Anterior] | <<v9-24-0,Topo>> | xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[Próximo Capítulo &#62;]