include::./index.adoc[]

[[v9-1-0]]
=== 1 Samuel, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v9-1-1]]

^<<v9-1-1,1>>^ Havia um homem da tribo  de Efraim, chamado Elcana, que vivia na cidade de Ramá, na região montanhosa de Efraim. Ele era filho de Jeroão, neto de Eliú, bisneto de Toú e trineto de Zufe.

[[v9-1-2]]

^<<v9-1-2,2>>^ Elcana tinha duas mulheres, Ana e Penina. Penina tinha filhos, porém Ana não tinha.

[[v9-1-3]]

^<<v9-1-3,3>>^ Todos os anos Elcana saía da sua cidade e ia a Siló a fim de adorar e oferecer sacrifícios  ao Senhor  Todo-Poderoso. Hofni e Fineias, os filhos de Eli, eram sacerdotes do Senhor  Deus, em Siló.

[[v9-1-4]]

^<<v9-1-4,4>>^ Cada vez que Elcana oferecia o seu sacrifício, ele dava uma parte para Penina e outra para todos os seus filhos e filhas.

[[v9-1-5]]

^<<v9-1-5,5>>^ Mas para Ana ele dava duas vezes mais. Elcana a amava muito, embora o Senhor  não permitisse que ela tivesse filhos.

[[v9-1-6]]

^<<v9-1-6,6>>^ Penina, sua rival, provocava e humilhava Ana porque o Senhor  não permitia que ela tivesse filhos.

[[v9-1-7]]

^<<v9-1-7,7>>^ Isso acontecia ano após ano. Sempre que iam ao santuário do Senhor , Penina irritava tanto Ana, que ela ficava só chorando e não comia nada.

[[v9-1-8]]

^<<v9-1-8,8>>^ Um dia o seu marido Elcana lhe perguntou: — Ana, por que você está chorando? Por que não come? Por que está sempre triste? Por acaso, eu não sou melhor para você do que dez filhos?

[[v9-1-9]]

^<<v9-1-9,9>>^ Certa vez eles estavam em Siló e tinham acabado de comer. Eli, o sacerdote, estava sentado na sua cadeira, na porta da Tenda Sagrada .

[[v9-1-10]]

^<<v9-1-10,10>>^ Aí Ana se levantou aflita e, chorando muito, orou a Deus, o Senhor .

[[v9-1-11]]

^<<v9-1-11,11>>^ E fez esta promessa solene: — Ó Senhor  Todo-Poderoso, olha para mim, tua serva ! Vê a minha aflição e lembra de mim! Não esqueças a tua serva! Se tu me deres um filho, prometo que o dedicarei a ti por toda a vida e que nunca ele cortará o cabelo .

[[v9-1-12]]

^<<v9-1-12,12>>^ Ana continuou orando ao Senhor  durante tanto tempo, que Eli começou a prestar atenção nela

[[v9-1-13]]

^<<v9-1-13,13>>^ e notou que os seus lábios se mexiam, porém não saía nenhum som. Ana estava orando em silêncio, mas Eli pensou que ela estava bêbada

[[v9-1-14]]

^<<v9-1-14,14>>^ e disse: — Até quando você vai ficar embriagada? Veja se para de beber!

[[v9-1-15]]

^<<v9-1-15,15>>^ — Senhor — respondeu ela —, eu não estou bêbada. Não bebi nem vinho nem cerveja. Estou desesperada e estava orando, contando a minha aflição ao Senhor .

[[v9-1-16]]

^<<v9-1-16,16>>^ Não pense que sou uma mulher sem moral. Eu estava orando daquele jeito porque sou muito infeliz e sofredora.

[[v9-1-17]]

^<<v9-1-17,17>>^ Então Eli disse: — Vá em paz. Que o Deus de Israel lhe dê o que você pediu!

[[v9-1-18]]

^<<v9-1-18,18>>^ — Que o senhor sempre pense bem de mim! — respondeu ela. E saiu. Então comeu alguma coisa e já não estava tão triste.

[[v9-1-19]]

^<<v9-1-19,19>>^ Na manhã seguinte Elcana e a sua família se levantaram cedo e adoraram a Deus, o Senhor . Aí voltaram para casa, em Ramá. Elcana teve relações com a sua esposa Ana, e o Senhor  respondeu à oração dela.

[[v9-1-20]]

^<<v9-1-20,20>>^ Ela ficou grávida e, no tempo certo, deu à luz um filho. Pôs nele o nome de Samuel e explicou: — Eu pedi esse filho a Deus, o Senhor .

[[v9-1-21]]

^<<v9-1-21,21>>^ Elcana e a sua família foram a Siló para oferecer ao Senhor  o sacrifício  anual e o sacrifício especial que ele havia prometido.

[[v9-1-22]]

^<<v9-1-22,22>>^ Ana, porém, não foi. Ela disse ao marido: — Assim que o menino for desmamado, eu o levarei ao santuário de Deus, o Senhor , para que ele fique lá toda a sua vida.

[[v9-1-23]]

^<<v9-1-23,23>>^ Elcana respondeu: — Faça o que achar melhor. Fique em casa até que ele seja desmamado. E o Senhor  faça com que, de fato, se cumpra a promessa que você fez. Então Ana ficou em casa e amamentou o filho.

[[v9-1-24]]

^<<v9-1-24,24>>^ Depois que ele foi desmamado, ela o levou a Siló. Levou também um touro de três anos, dez quilos de farinha e um odre  cheio de vinho. Samuel era muito novo quando a sua mãe o levou à casa do Senhor , em Siló.

[[v9-1-25]]

^<<v9-1-25,25>>^ Os pais de Samuel ofereceram o touro em sacrifício e levaram o menino para Eli.

[[v9-1-26]]

^<<v9-1-26,26>>^ Ana disse: — Meu senhor, juro pela sua vida que sou aquela mulher que o senhor viu aqui de pé, orando.

[[v9-1-27]]

^<<v9-1-27,27>>^ Eu pedi esta criança a Deus, o Senhor , e ele me deu o que pedi.

[[v9-1-28]]

^<<v9-1-28,28>>^ Por isso agora eu estou dedicando este menino ao Senhor . Enquanto ele viver, pertencerá ao Senhor . Então eles adoraram a Deus ali.

'''

xref:008-rute/008-rute-004.adoc#v8-4-0[&#60; Capítulo Anterior] | <<v9-1-0,Topo>> | xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[Próximo Capítulo &#62;]