include::./index.adoc[]

[[v8-3-0]]
=== Rute, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v8-3-1]]

^<<v8-3-1,1>>^ Um dia Noemi disse a Rute: — Minha filha, preciso arranjar um marido para você, a fim de que você tenha um lar.

[[v8-3-2]]

^<<v8-3-2,2>>^ Você lembra que Boaz, o homem que a deixou trabalhar com as suas empregadas, é um dos nossos parentes? Pois bem! Esta noite ele vai debulhar a cevada .

[[v8-3-3]]

^<<v8-3-3,3>>^ Faça o seguinte: lave-se, ponha perfume e vista o seu melhor vestido. Depois vá até o lugar onde Boaz está trabalhando, mas não o deixe saber que você está ali, até que ele acabe de comer e de beber.

[[v8-3-4]]

^<<v8-3-4,4>>^ Quando Boaz for dormir, olhe bem onde ele vai se deitar. Então vá, levante a coberta dos pés dele e deite-se ali. Ele dirá o que você deve fazer.

[[v8-3-5]]

^<<v8-3-5,5>>^ Rute respondeu: — Vou fazer tudo o que a senhora disse.

[[v8-3-6]]

^<<v8-3-6,6>>^ Ela foi ao lugar onde debulhavam as espigas e fez tudo o que a sua sogra havia mandado.

[[v8-3-7]]

^<<v8-3-7,7>>^ Quando Boaz acabou de comer e de beber, ficou um pouco alegre e foi dormir perto de um monte de cevada. Então Rute veio de mansinho, levantou a coberta dos pés dele e se deitou ali.

[[v8-3-8]]

^<<v8-3-8,8>>^ No meio da noite ele acordou de repente, sentou-se e ficou muito admirado de encontrar uma mulher deitada perto dos seus pés.

[[v8-3-9]]

^<<v8-3-9,9>>^ Ele perguntou: — Quem é você? — Eu sou Rute, a sua empregada! — respondeu ela. — O senhor é nosso parente chegado e por isso tem o dever de me proteger.

[[v8-3-10]]

^<<v8-3-10,10>>^ Boaz respondeu: — Que o Senhor  a abençoe, minha filha! Você está mostrando maior lealdade à família do seu sogro naquilo que está fazendo agora do que naquilo que fez pela sua sogra. Pois você não foi procurar um homem mais moço, fosse rico ou fosse pobre.

[[v8-3-11]]

^<<v8-3-11,11>>^ Agora, minha filha, não tenha medo. Na cidade toda gente sabe que você é uma mulher direita. Vou fazer tudo o que me pede.

[[v8-3-12]]

^<<v8-3-12,12>>^ De fato, sou seu parente chegado e sou responsável por você. Mas acontece que há um homem que também é seu parente e até mais chegado do que eu.

[[v8-3-13]]

^<<v8-3-13,13>>^ Fique aqui o resto da noite, e de manhã nós veremos se ele quer ser responsável por você. Se ele quiser, muito bem; mas, se não quiser, prometo por Deus, o Senhor , que ficarei com essa responsabilidade. Agora deite-se e durma de novo.

[[v8-3-14]]

^<<v8-3-14,14>>^ Então Rute passou o resto da noite deitada aos pés dele. Enquanto ainda estava escuro, ela se levantou para não ser vista, pois Boaz não queria que ninguém soubesse que uma mulher havia ido lá.

[[v8-3-15]]

^<<v8-3-15,15>>^ Então Boaz disse: — Tire a sua capa  e estenda no chão. Ela estendeu, e ele despejou na capa uns vinte quilos de cevada e a ajudou a pôr no ombro. Aí Rute voltou para a cidade.

[[v8-3-16]]

^<<v8-3-16,16>>^ Quando ela chegou a casa, a sua sogra perguntou: — Como foram as coisas, minha filha? Rute contou tudo o que Boaz tinha feito por ela. E disse ainda:

[[v8-3-17]]

^<<v8-3-17,17>>^ — Ele também me deu toda esta cevada e disse: "Não volte para casa sem levar alguma coisa para a sua sogra."

[[v8-3-18]]

^<<v8-3-18,18>>^ Então Noemi disse: — Agora, minha filha, tenha paciência e espere para ver o que vai acontecer. Pois Boaz não vai descansar enquanto não resolver esse assunto, ainda hoje.

'''

xref:008-rute/008-rute-002.adoc#v8-2-0[&#60; Capítulo Anterior] | <<v8-3-0,Topo>> | xref:008-rute/008-rute-004.adoc#v8-4-0[Próximo Capítulo &#62;]