include::./index.adoc[]

[[v8-4-0]]
=== Rute, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v8-4-1]]

^<<v8-4-1,1>>^ Boaz foi até a praça que ficava ao lado do portão da cidade e sentou-se ali. Nesse momento apareceu o parente mais chegado de Elimeleque, aquele de quem Boaz havia falado. E Boaz lhe disse: — Meu amigo, venha aqui e sente-se. Ele foi e sentou-se.

[[v8-4-2]]

^<<v8-4-2,2>>^ Então Boaz chamou dez pessoas importantes da cidade e disse: — Sentem-se aqui. Eles se sentaram,

[[v8-4-3]]

^<<v8-4-3,3>>^ e Boaz disse ao seu parente: — Noemi voltou do país de Moabe e está querendo vender as terras que eram do nosso parente Elimeleque.

[[v8-4-4]]

^<<v8-4-4,4>>^ Então eu resolvi conversar com você sobre este assunto. Agora, se você quiser, compre essas terras na presença das autoridades do nosso povo e dos homens que estão sentados aqui. Mas, se não quiser, diga, pois o direito de comprar essas terras é primeiro seu e depois, meu. O homem respondeu: — Eu compro as terras.

[[v8-4-5]]

^<<v8-4-5,5>>^ Aí Boaz disse: — Se você comprar as terras de Noemi, também terá de casar com Rute, a viúva moabita, para que as terras fiquem com a família do falecido.

[[v8-4-6]]

^<<v8-4-6,6>>^ Então o homem respondeu: — Nesse caso, não vou usar o meu direito de comprar as terras, pois correria o risco de prejudicar a minha própria herança . Use você o meu direito; eu prefiro não fazer isso.

[[v8-4-7]]

^<<v8-4-7,7>>^ Compre você as terras. Em seguida tirou a sandália e deu a Boaz. (Antigamente, em Israel, para fechar um negócio de compra ou troca de propriedades, uma pessoa entregava à outra a sua sandália.)

[[v8-4-8]]

^<<v8-4-8,8>>^ Compre você as terras.

[[v8-4-9]]

^<<v8-4-9,9>>^ Aí Boaz disse às autoridades e a todo o povo: — Hoje vocês são testemunhas de que eu comprei de Noemi tudo o que era de Elimeleque, e de Quiliom, e de Malom.

[[v8-4-10]]

^<<v8-4-10,10>>^ Também casarei com Rute, a moabita, viúva de Malom, para que a propriedade continue com a família do falecido. Assim o nome de Malom será sempre lembrado no meio deste povo e na sua cidade natal. Hoje vocês são testemunhas disso.

[[v8-4-11]]

^<<v8-4-11,11>>^ Todos responderam: — Sim, nós somos testemunhas. E as autoridades disseram a Boaz: — O Senhor  faça com que essa mulher, que veio para o seu lar, seja como Raquel e Leia, que deram muitos filhos a Jacó, tornando-se assim as mães da nação israelita! Que você seja rico e famoso em Belém-Efrata!

[[v8-4-12]]

^<<v8-4-12,12>>^ Que os filhos que o Senhor  lhe der neste casamento façam com que a sua família seja como a família de Peres, filho de Judá e de Tamar!

[[v8-4-13]]

^<<v8-4-13,13>>^ Então Boaz levou Rute para casa, para ser a sua mulher. Eles tiveram relações, e o Senhor  deu a Rute a bênção de ficar grávida, e ela deu à luz um filho.

[[v8-4-14]]

^<<v8-4-14,14>>^ E as mulheres disseram a Noemi: — Louvado seja o Senhor , que lhe deu hoje um neto para cuidar de você! Que este menino venha a ser famoso em Israel!

[[v8-4-15]]

^<<v8-4-15,15>>^ Que ele seja um consolo para o seu coração e lhe dê segurança na velhice! A sua nora, a mãe do menino, a ama; e ela vale para você mais do que sete filhos.

[[v8-4-16]]

^<<v8-4-16,16>>^ Noemi pegou o menino no colo e cuidou dele.

[[v8-4-17]]

^<<v8-4-17,17>>^ Ao vê-lo, as mulheres da vizinhança diziam: — Nasceu um filho para Noemi! E lhe deram o nome de Obede. Obede veio a ser o pai de Jessé, que foi o pai do rei Davi.

'''

xref:008-rute/008-rute-003.adoc#v8-3-0[&#60; Capítulo Anterior] | <<v8-4-0,Topo>> | xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[Próximo Capítulo &#62;]