include::./index.adoc[]

[[v8-1-0]]
=== Rute, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v8-1-1]]

^<<v8-1-1,1>>^ No tempo em que Israel era governado por juízes, houve uma grande fome naquele país. Por isso um homem de Belém, cidade da região de Judá, foi com a sua mulher e os seus dois filhos morar por algum tempo num país chamado Moabe.

[[v8-1-2]]

^<<v8-1-2,2>>^ O nome desse homem era Elimeleque, e o da sua mulher, Noemi. Os dois filhos se chamavam Malom e Quiliom. Essa família era de Efrata, um povoado que ficava perto de Belém de Judá. Eles foram para Moabe e ficaram morando ali.

[[v8-1-3]]

^<<v8-1-3,3>>^ Algum tempo depois, Elimeleque morreu, e Noemi ficou com os dois filhos,

[[v8-1-4]]

^<<v8-1-4,4>>^ que casaram com moças moabitas. O nome de uma delas era Orfa, e o da outra, Rute. Quando já fazia quase dez anos que estavam morando ali,

[[v8-1-5]]

^<<v8-1-5,5>>^ Malom e Quiliom também morreram. E Noemi ficou só, sem os filhos e sem o marido.

[[v8-1-6]]

^<<v8-1-6,6>>^ Um dia Noemi soube que o Senhor  tinha ajudado o seu povo, dando-lhe boas colheitas. Então ela se aprontou para sair de Moabe com as suas noras.

[[v8-1-7]]

^<<v8-1-7,7>>^ Elas saíram a fim de voltar para Judá, mas no caminho

[[v8-1-8]]

^<<v8-1-8,8>>^ Noemi disse às noras: — Voltem para casa e fiquem com as suas mães. Que o Senhor  seja bom para vocês, assim como vocês foram boas para mim e para os falecidos!

[[v8-1-9]]

^<<v8-1-9,9>>^ O Senhor  permita que vocês casem de novo e cada uma tenha o seu lar! Então Noemi se despediu das suas noras com um beijo. Porém elas começaram a chorar alto

[[v8-1-10]]

^<<v8-1-10,10>>^ e disseram: — Não! Nós não voltaremos. Nós iremos com a senhora e ficaremos com o seu povo.

[[v8-1-11]]

^<<v8-1-11,11>>^ Mas Noemi respondeu: — Voltem, minhas filhas. Por que querem ir comigo? Vocês acham que eu ainda poderei ter filhos para casarem com vocês?

[[v8-1-12]]

^<<v8-1-12,12>>^ Voltem para casa porque já estou muito velha para casar de novo. Pois, ainda que eu tivesse esperança de casar outra vez ou mesmo que casasse esta noite e chegasse a ter filhos,

[[v8-1-13]]

^<<v8-1-13,13>>^ será que vocês iriam esperar até que eles crescessem para vocês casarem com eles? É claro que não, minhas filhas! O Senhor  está contra mim, e isso me deixa muito triste, pois vocês também estão sofrendo.

[[v8-1-14]]

^<<v8-1-14,14>>^ Aí elas começaram a chorar alto outra vez. Então Orfa se despediu da sua sogra com um beijo e voltou para o seu povo. Mas Rute ficou.

[[v8-1-15]]

^<<v8-1-15,15>>^ — Veja! — disse Noemi. — A sua cunhada voltou para o seu povo e para os seus deuses. Volte você também para casa com ela.

[[v8-1-16]]

^<<v8-1-16,16>>^ Porém Rute respondeu: — Não me proíba de ir com a senhora, nem me peça para abandoná-la! Onde a senhora for, eu irei; e onde morar, eu também morarei. O seu povo será o meu povo, e o seu Deus será o meu Deus.

[[v8-1-17]]

^<<v8-1-17,17>>^ Onde a senhora morrer, eu morrerei também e ali serei sepultada. Que o Senhor  me castigue se qualquer coisa, a não ser a morte, me separar da senhora!

[[v8-1-18]]

^<<v8-1-18,18>>^ Como Noemi viu que Rute estava mesmo resolvida a ir com ela, não disse mais nada.

[[v8-1-19]]

^<<v8-1-19,19>>^ E elas continuaram a viagem até Belém. Quando chegaram lá, toda a cidade ficou agitada por causa delas. E as mulheres perguntavam: — Esta é a Noemi?

[[v8-1-20]]

^<<v8-1-20,20>>^ Porém ela respondia: — Não me chamem de Noemi, a Feliz. Chamem de Mara , a Amargurada, porque o Deus Todo-Poderoso me deu muita amargura.

[[v8-1-21]]

^<<v8-1-21,21>>^ Quando saí daqui, eu tinha tudo, mas o Senhor  me fez voltar sem nada. Então, por que me chamar de Feliz, se o Deus Todo-Poderoso me fez sofrer e me deu tanta aflição?

[[v8-1-22]]

^<<v8-1-22,22>>^ E foi assim que Noemi voltou de Moabe, com Rute, a sua nora moabita. Elas chegaram a Belém quando a colheita de cevada  estava começando.

'''

xref:007-juizes/007-juizes-021.adoc#v7-21-0[&#60; Capítulo Anterior] | <<v8-1-0,Topo>> | xref:008-rute/008-rute-002.adoc#v8-2-0[Próximo Capítulo &#62;]