include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-7-1]]

^<<v12-7-1,1>>^ Eliseu respondeu: — Escute o que o Senhor  diz: "Amanhã a esta hora, você poderá comprar em Samaria três quilos e meio do melhor trigo ou sete quilos de cevada  por uma barra de prata."

[[v12-7-2]]

^<<v12-7-2,2>>^ O ajudante pessoal do rei disse a Eliseu: — Mesmo que o Senhor  Deus abrisse janelas no céu e fizesse cair trigo e cevada, isso nunca poderia acontecer! Eliseu respondeu: — Com os seus próprios olhos você vai ver isso acontecer, mas não vai comer.

[[v12-7-3]]

^<<v12-7-3,3>>^ Quatro homens que sofriam de uma doença contagiosa da pele estavam do lado de fora dos portões da cidade de Samaria. Eles disseram uns aos outros: — Por que ficamos aqui sentados esperando a morte?

[[v12-7-4]]

^<<v12-7-4,4>>^ Não vale a pena entrar na cidade porque lá iríamos morrer de fome; mas, se ficarmos aqui, também morreremos. Vamos então para o acampamento dos sírios. Se eles nos deixarem viver, ficaremos vivos; se nos matarem, bem, nós vamos morrer de qualquer jeito mesmo.

[[v12-7-5]]

^<<v12-7-5,5>>^ E assim, quando começou a escurecer, eles foram até o acampamento dos sírios. Porém, quando chegaram, não havia ninguém lá.

[[v12-7-6]]

^<<v12-7-6,6>>^ Deus havia feito com que os sírios ouvissem um barulho que parecia o de um grande exército, com cavalos e carros de guerra. Então eles pensaram que o rei de Israel havia pago os reis dos heteus e dos egípcios e os seus exércitos para os atacarem.

[[v12-7-7]]

^<<v12-7-7,7>>^ Por isso, ao anoitecer, os sírios haviam fugido para salvar a sua vida, abandonando as barracas, os cavalos e jumentos e deixando o acampamento como estava.

[[v12-7-8]]

^<<v12-7-8,8>>^ Quando os quatro homens chegaram ao acampamento, entraram numa barraca, comeram e beberam do que havia ali e pegaram a prata, o ouro e as roupas que acharam. Depois saíram e esconderam tudo. Aí voltaram, entraram em outra barraca e fizeram a mesma coisa.

[[v12-7-9]]

^<<v12-7-9,9>>^ Mas então disseram: — Nós não estamos agindo bem! Temos boas notícias e não devíamos ficar calados. Se esperarmos até amanhã para contar, certamente seremos castigados. Vamos agora mesmo contar isso lá no palácio.

[[v12-7-10]]

^<<v12-7-10,10>>^ Então saíram do acampamento dos sírios, voltaram para Samaria e gritaram para os guardas que estavam nos portões: — Nós fomos até o acampamento dos sírios e não vimos, nem ouvimos ninguém. Os cavalos e os jumentos estão lá amarrados, e as barracas estão do mesmo jeito que os sírios deixaram!

[[v12-7-11]]

^<<v12-7-11,11>>^ Os guardas anunciaram a notícia, e ela foi contada no palácio.

[[v12-7-12]]

^<<v12-7-12,12>>^ Ainda era de noite, mas o rei se levantou e disse aos seus oficiais: — Vou dizer a vocês o que foi que os sírios planejaram. Eles sabem que nós não temos nenhuma comida e por isso saíram do acampamento e foram se esconder no campo. Eles pensam que nós vamos sair da cidade para procurar comida e aí nos pegarão vivos e conquistarão a cidade.

[[v12-7-13]]

^<<v12-7-13,13>>^ Um dos oficiais disse: — Os que ficaram aqui na cidade vão morrer de qualquer jeito, como alguns já morreram. Portanto, deixe que nós mandemos alguns homens com cinco dos cavalos que restaram, para assim podermos descobrir o que foi que aconteceu.

[[v12-7-14]]

^<<v12-7-14,14>>^ Eles escolheram alguns homens, e o rei os mandou em dois carros de guerra com ordem para descobrirem o que havia acontecido com o exército dos sírios.

[[v12-7-15]]

^<<v12-7-15,15>>^ Os homens foram até o rio Jordão e viram por toda a estrada as roupas e as armas que os sírios tinham abandonado enquanto fugiam. Então voltaram e contaram ao rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ O povo de Samaria saiu e avançou nas coisas que tinha no acampamento dos sírios. E, conforme o Senhor  tinha dito, três quilos e meio do melhor trigo ou sete quilos de cevada  foram vendidos por uma barra de prata.

[[v12-7-17]]

^<<v12-7-17,17>>^ Acontece que o rei de Israel tinha colocado o seu ajudante pessoal como encarregado do portão da cidade. Esse oficial foi atropelado pelo povo e morreu, como Eliseu tinha dito quando o rei tinha ido falar com ele.

[[v12-7-18]]

^<<v12-7-18,18>>^ Eliseu tinha dito ao rei que no dia seguinte, naquela hora, três quilos e meio do melhor trigo ou sete quilos de cevada seriam vendidos em Samaria por uma barra de prata,

[[v12-7-19]]

^<<v12-7-19,19>>^ e o oficial havia respondido: "Mesmo que o Senhor  Deus abrisse janelas no céu e fizesse cair trigo e cevada, isso nunca poderia acontecer!" E Eliseu havia respondido: "Com os seus próprios olhos você vai ver isso acontecer, mas não vai comer."

[[v12-7-20]]

^<<v12-7-20,20>>^ E foi exatamente isso o que aconteceu com ele: morreu pisado pelo povo no portão da cidade.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]