include::./index.adoc[]

[[v12-16-0]]
=== 2 Reis, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-16-1]]

^<<v12-16-1,1>>^ No ano dezessete do reinado de Peca, filho de Remalias, em Israel, Acaz, filho de Jotão, se tornou rei de Judá.

[[v12-16-2]]

^<<v12-16-2,2>>^ Acaz começou a reinar quando tinha vinte anos de idade. Ele governou dezesseis anos em Jerusalém. Acaz não seguiu o bom exemplo do seu antepassado, o rei Davi; pelo contrário, fez o que não agrada ao Senhor , seu Deus,

[[v12-16-3]]

^<<v12-16-3,3>>^ e seguiu o exemplo dos reis de Israel. Ele chegou até a oferecer o próprio filho, queimando-o como oferta aos ídolos, seguindo o nojento costume dos povos que o Senhor  havia expulsado da Terra Prometida  conforme os israelitas avançavam.

[[v12-16-4]]

^<<v12-16-4,4>>^ Acaz ofereceu sacrifícios  e queimou incenso nos lugares pagãos de adoração, nos morros e debaixo de todas as árvores que dão sombra.

[[v12-16-5]]

^<<v12-16-5,5>>^ Rezim, rei da Síria, e o rei Peca, de Israel, atacaram e cercaram a cidade de Jerusalém, porém não puderam derrotar Acaz.

[[v12-16-6]]

^<<v12-16-6,6>>^ Nessa mesma época o rei de Edom reconquistou a cidade de Elate e expulsou os judeus que moravam lá. Os edomitas foram para Elate e ainda moram lá.

[[v12-16-7]]

^<<v12-16-7,7>>^ Acaz mandou alguns mensageiros a Tiglate-Pileser, rei da Assíria, para entregarem a ele esta mensagem: "Eu sou seu criado e seu filho. Venha me salvar dos reis da Síria e de Israel, que estão me atacando."

[[v12-16-8]]

^<<v12-16-8,8>>^ Acaz pegou a prata e o ouro do Templo e o tesouro do palácio e mandou de presente ao rei da Assíria.

[[v12-16-9]]

^<<v12-16-9,9>>^ Em resposta ao pedido de Acaz, o rei da Assíria marchou com o seu exército para a cidade de Damasco, conquistou-a, matou o rei Rezim e levou o povo para Quir como prisioneiro.

[[v12-16-10]]

^<<v12-16-10,10>>^ O rei Acaz foi a Damasco para se encontrar com o rei Tiglate-Pileser e viu o altar que havia ali. Então mandou para o sacerdote Urias o desenho e o modelo do altar, com todos os detalhes.

[[v12-16-11]]

^<<v12-16-11,11>>^ E Urias construiu um altar, seguindo todas as instruções que o rei Acaz havia mandado de Damasco, e terminou o trabalho antes que Acaz voltasse.

[[v12-16-12]]

^<<v12-16-12,12>>^ Ao chegar de Damasco, Acaz viu que o altar estava pronto,

[[v12-16-13]]

^<<v12-16-13,13>>^ e então queimou sobre ele sacrifícios de animais, ofertas de cereais, e derramou em cima dele uma oferta de vinho e o sangue de uma oferta de paz.

[[v12-16-14]]

^<<v12-16-14,14>>^ O altar de bronze, que era dedicado ao Senhor  Deus, ficava entre o novo altar e o Templo, e por isso Acaz o mudou para o lado norte do seu novo altar.

[[v12-16-15]]

^<<v12-16-15,15>>^ Então deu a Urias a seguinte ordem: — Use este meu altar grande para as ofertas que são completamente queimadas de manhã e para a oferta de cereais da tarde, para as ofertas que são completamente queimadas e as ofertas de cereais do rei e do povo e também para as ofertas de vinho do povo. Derrame sobre o altar o sangue de todos os animais que forem sacrificados. Mas deixe o altar de bronze a fim de que eu o use para adivinhações.

[[v12-16-16]]

^<<v12-16-16,16>>^ E Urias fez o que o rei mandou.

[[v12-16-17]]

^<<v12-16-17,17>>^ O rei Acaz desmontou as carretas de bronze que eram usadas no Templo e tirou as bacias que estavam em cima delas. Tirou também o tanque de bronze de cima das costas dos doze touros e colocou-o sobre uma base de pedra.

[[v12-16-18]]

^<<v12-16-18,18>>^ E, para agradar o rei da Assíria, Acaz também tirou do Templo a plataforma onde ficava o trono real e fechou a entrada particular por onde os reis entravam no Templo.

[[v12-16-19]]

^<<v12-16-19,19>>^ Todas as outras coisas que o rei Acaz fez estão escritas na História dos Reis de Judá .

[[v12-16-20]]

^<<v12-16-20,20>>^ Acaz morreu e foi sepultado nos túmulos dos reis, na Cidade de Davi , e o seu filho Ezequias ficou no lugar dele como rei.

'''

xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[&#60; Capítulo Anterior] | <<v12-16-0,Topo>> | xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[Próximo Capítulo &#62;]