include::./index.adoc[]

[[v12-2-0]]
=== 2 Reis, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-2-1]]

^<<v12-2-1,1>>^ Chegou o tempo de o Senhor  Deus levar Elias para o céu num redemoinho. Elias saiu de Gilgal junto com Eliseu

[[v12-2-2]]

^<<v12-2-2,2>>^ e no caminho Elias disse: — Fique aqui porque o Senhor  me mandou ir até Betel. Mas Eliseu disse: — Juro pelo Senhor  Deus e pelo senhor que eu não o deixarei. E assim os dois foram até Betel.

[[v12-2-3]]

^<<v12-2-3,3>>^ Um grupo de profetas  que morava ali foi falar com Eliseu e lhe perguntou: — Você sabe que hoje o Senhor  vai levar o seu mestre para longe de você? — Sim, eu sei! — respondeu Eliseu. — Mas não vamos falar nisso.

[[v12-2-4]]

^<<v12-2-4,4>>^ Então Elias disse a Eliseu: — Fique aqui porque o Senhor  me mandou ir até Jericó. Mas Eliseu disse: — Juro pelo Senhor  Deus e pelo senhor que eu não o deixarei. E assim os dois foram até Jericó.

[[v12-2-5]]

^<<v12-2-5,5>>^ Um grupo de profetas que morava ali foi falar com Eliseu e perguntou: — Você sabe que hoje o Senhor  vai levar o seu mestre para longe de você? — Sim, eu sei! — respondeu Eliseu. — Mas não vamos falar nisso.

[[v12-2-6]]

^<<v12-2-6,6>>^ Aí Elias disse a Eliseu: — Fique aqui porque o Senhor  me mandou ir até o rio Jordão. Mas Eliseu disse: — Juro pelo Senhor  Deus e pelo senhor que não o deixarei. Então eles saíram,

[[v12-2-7]]

^<<v12-2-7,7>>^ e cinquenta profetas os seguiram até o rio Jordão. Elias e Eliseu pararam perto do rio, e os profetas ficaram olhando de longe.

[[v12-2-8]]

^<<v12-2-8,8>>^ Aí Elias tirou a sua capa , enrolou-a e bateu com ela na água. A água se abriu, e ele e Eliseu passaram para o outro lado, andando em terra seca.

[[v12-2-9]]

^<<v12-2-9,9>>^ Ali Elias disse a Eliseu: — Diga o que você quer que eu faça por você antes que eu seja levado embora. Eliseu disse: — Quero receber como herança duas vezes mais poder do que os outros profetas vão receber .

[[v12-2-10]]

^<<v12-2-10,10>>^ Elias disse: — Esse pedido é difícil de atender. Mas você receberá o que está me pedindo se me vir quando eu estiver sendo levado para longe. Se você não me vir, não receberá.

[[v12-2-11]]

^<<v12-2-11,11>>^ E assim foram andando e conversando. De repente, um carro de fogo puxado por cavalos de fogo os separou um do outro, e Elias foi levado para o céu num redemoinho.

[[v12-2-12]]

^<<v12-2-12,12>>^ Eliseu viu o que aconteceu e gritou: — Meu pai, meu pai! O senhor sempre foi como um exército para defender Israel! E nunca mais ele viu Elias. Muito triste, Eliseu rasgou a sua capa pelo meio.

[[v12-2-13]]

^<<v12-2-13,13>>^ Depois pegou a capa de Elias, que havia caído, voltou para a beira do rio Jordão e parou ali.

[[v12-2-14]]

^<<v12-2-14,14>>^ Então bateu na água com a capa de Elias e disse: — Onde está o Senhor , o Deus de Elias? Aí bateu de novo na água, e ela se abriu, e ele passou para o outro lado.

[[v12-2-15]]

^<<v12-2-15,15>>^ Os cinquenta profetas de Jericó viram isso e disseram: — O poder de Elias está com Eliseu! Então foram encontrar-se com ele, ajoelharam-se diante dele

[[v12-2-16]]

^<<v12-2-16,16>>^ e disseram: — Nós que estamos aqui somos cinquenta homens fortes. Deixe que vamos procurar o seu mestre. Talvez o Espírito do Senhor  Deus o tenha carregado e deixado em alguma montanha ou em algum vale. — Não! Vocês não devem ir! — respondeu Eliseu.

[[v12-2-17]]

^<<v12-2-17,17>>^ Mas eles insistiram, até que ele mudou de ideia e deixou que fossem. Os cinquenta foram e durante três dias procuraram Elias por toda parte, porém não o acharam.

[[v12-2-18]]

^<<v12-2-18,18>>^ Então voltaram a Jericó, onde Eliseu estava esperando. Eliseu disse: — Eu não falei para vocês não irem?

[[v12-2-19]]

^<<v12-2-19,19>>^ Alguns homens de Jericó foram falar com Eliseu e disseram: — Como o senhor sabe, esta cidade é boa, mas a água não presta e provoca abortos.

[[v12-2-20]]

^<<v12-2-20,20>>^ Então Eliseu mandou: — Ponham um pouco de sal num prato novo e tragam para mim. Eles levaram,

[[v12-2-21]]

^<<v12-2-21,21>>^ e Eliseu foi até a fonte, jogou o sal na água e disse: — O que o Senhor  Deus diz é isto: "Eu fiz esta água ficar pura, e ela não provocará mais mortes nem abortos."

[[v12-2-22]]

^<<v12-2-22,22>>^ E aquela água ficou pura até hoje , como Eliseu disse que ia ficar.

[[v12-2-23]]

^<<v12-2-23,23>>^ Eliseu saiu de Jericó para ir a Betel. Ele ia andando pela estrada, quando alguns rapazes saíram de uma cidade e começaram a caçoar dele, gritando assim: — Ô seu careca, fora daqui!

[[v12-2-24]]

^<<v12-2-24,24>>^ Eliseu virou para trás, olhou firme para os rapazes e os amaldiçoou em nome de Deus, o Senhor . Então duas ursas saíram do mato e despedaçaram quarenta e dois deles.

[[v12-2-25]]

^<<v12-2-25,25>>^ Dali Eliseu foi até o monte Carmelo e depois voltou para Samaria.

'''

xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]