include::./index.adoc[]

[[v12-14-0]]
=== 2 Reis, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-14-1]]

^<<v12-14-1,1>>^ No segundo ano do reinado de Jeoás, filho de Jeoacaz, em Israel, Amazias, filho de Joás, se tornou rei de Judá.

[[v12-14-2]]

^<<v12-14-2,2>>^ Quando isso aconteceu, Amazias tinha vinte e cinco anos. Ele governou vinte e nove anos em Jerusalém. A mãe dele se chamava Jeoadã e era da cidade de Jerusalém.

[[v12-14-3]]

^<<v12-14-3,3>>^ Amazias fez o que é agradável a Deus, o Senhor , porém não foi tão correto como o seu antepassado, o rei Davi; pelo contrário, fez aquilo que o seu pai Joás havia feito.

[[v12-14-4]]

^<<v12-14-4,4>>^ Ele não derrubou os lugares pagãos de adoração, e o povo continuou a oferecer sacrifícios  e a queimar incenso nesses lugares.

[[v12-14-5]]

^<<v12-14-5,5>>^ Assim que se firmou no poder, Amazias mandou matar os oficiais que haviam assassinado o seu pai, o rei.

[[v12-14-6]]

^<<v12-14-6,6>>^ No entanto, não matou os filhos deles, mas seguiu o que o Senhor  havia mandado na Lei  de Moisés: "Os pais não serão mortos por causa de crimes cometidos pelos filhos, nem os filhos, por causa de crimes cometidos pelos pais; uma pessoa será morta somente como castigo pelo crime que ela mesma cometeu."

[[v12-14-7]]

^<<v12-14-7,7>>^ No vale do Sal, Amazias matou dez mil soldados do país de Edom; ele conquistou na guerra a cidade de Selá e pôs nela o nome de Jocteel, e assim é conhecida até hoje .

[[v12-14-8]]

^<<v12-14-8,8>>^ Então Amazias mandou mensageiros ao rei Jeoás, de Israel, desafiando-o para uma batalha.

[[v12-14-9]]

^<<v12-14-9,9>>^ Mas o rei Jeoás respondeu assim: — Uma vez um espinheiro dos montes Líbanos mandou a seguinte mensagem para um cedro: "Dê a sua filha em casamento para o meu filho." Mas um animal selvagem passou por ali e pisou em cima do espinheiro.

[[v12-14-10]]

^<<v12-14-10,10>>^ De fato, você, Amazias, venceu os edomitas e por isso está todo orgulhoso. Alegre-se com a sua fama e fique em casa. Para que arranjar um problema que trará somente a desgraça para você e para o seu povo?

[[v12-14-11]]

^<<v12-14-11,11>>^ Mas Amazias não quis atendê-lo. Então o rei Jeoás saiu com os seus soldados e lutou contra ele em Bete-Semes, na região de Judá.

[[v12-14-12]]

^<<v12-14-12,12>>^ O exército de Amazias foi derrotado, e todos os seus soldados fugiram para casa.

[[v12-14-13]]

^<<v12-14-13,13>>^ Jeoás prendeu Amazias em Bete-Semes, avançou para Jerusalém e derrubou as muralhas da cidade desde o Portão de Efraim até o Portão da Esquina, um trecho de mais ou menos duzentos metros.

[[v12-14-14]]

^<<v12-14-14,14>>^ Ele pegou toda a prata e todo o ouro que achou, pegou todos os objetos do Templo e todos os tesouros do palácio e também levou reféns . E voltou para Samaria.

[[v12-14-15]]

^<<v12-14-15,15>>^ Todas as outras coisas que Jeoás fez e também a sua coragem na batalha contra o rei Amazias, de Judá, estão escritas na História dos Reis de Israel .

[[v12-14-16]]

^<<v12-14-16,16>>^ Jeoás morreu e foi sepultado nos túmulos dos reis, em Samaria, e o seu filho Jeroboão II ficou no lugar dele como rei.

[[v12-14-17]]

^<<v12-14-17,17>>^ O rei Amazias, de Judá, viveu quinze anos depois da morte do rei de Israel, Jeoás, filho de Jeoacaz.

[[v12-14-18]]

^<<v12-14-18,18>>^ Todas as outras coisas que Amazias fez estão escritas na História dos Reis de Judá .

[[v12-14-19]]

^<<v12-14-19,19>>^ Houve uma conspiração em Jerusalém para matar Amazias, e por isso ele fugiu para a cidade de Laquis; mas os seus inimigos o seguiram até lá e o mataram.

[[v12-14-20]]

^<<v12-14-20,20>>^ O seu corpo foi levado de volta para Jerusalém num cavalo e foi sepultado nos túmulos dos reis, na Cidade de Davi .

[[v12-14-21]]

^<<v12-14-21,21>>^ Então o povo pôs no seu lugar como rei o seu filho Uzias , que tinha dezesseis anos de idade.

[[v12-14-22]]

^<<v12-14-22,22>>^ Depois da morte do seu pai, Uzias reconquistou e construiu de novo a cidade de Elate.

[[v12-14-23]]

^<<v12-14-23,23>>^ No ano quinze do reinado de Amazias, filho de Joás, em Judá, Jeroboão II, filho de Jeoás, se tornou rei de Israel e governou quarenta e um anos em Samaria.

[[v12-14-24]]

^<<v12-14-24,24>>^ Jeroboão II fez coisas erradas, que não agradam a Deus, o Senhor . Não abandonou aqueles mesmos pecados que Jeroboão, filho de Nebate, havia feito o povo de Israel cometer no passado.

[[v12-14-25]]

^<<v12-14-25,25>>^ Jeroboão II conquistou de novo todo o território que havia sido de Israel, desde a subida de Hamate, no Norte, até o mar Morto, no Sul. O Senhor , o Deus de Israel, havia prometido isso por meio do seu servo , o profeta  Jonas, filho de Amitai, que era de Gate-Hefer.

[[v12-14-26]]

^<<v12-14-26,26>>^ O Senhor  Deus viu o terrível sofrimento dos israelitas; não havia ninguém, ninguém mesmo, que os ajudasse.

[[v12-14-27]]

^<<v12-14-27,27>>^ Mas o Senhor  não tinha a intenção de destruir o povo de Israel completamente e para sempre; por isso, ele os livrou por meio do rei Jeroboão II.

[[v12-14-28]]

^<<v12-14-28,28>>^ Todas as outras coisas que Jeroboão II fez, o seu poder, como ele lutou e como conquistou de novo as cidades de Damasco e Hamate para Israel, tudo está escrito na História dos Reis de Israel .

[[v12-14-29]]

^<<v12-14-29,29>>^ Jeroboão II morreu e foi sepultado nos túmulos dos reis, e o seu filho Zacarias ficou no lugar dele como rei.

'''

xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[Próximo Capítulo &#62;]