include::./index.adoc[]

[[v12-12-0]]
=== 2 Reis, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-12-1]]

^<<v12-12-1,1>>^ No sétimo ano do reinado de Jeú, de Israel, Joás se tornou rei de Judá. Ele governou em Jerusalém quarenta anos. A mãe dele se chamava Zíbia e era da cidade de Berseba.

[[v12-12-2]]

^<<v12-12-2,2>>^ Durante toda a sua vida Joás fez o que agrada a Deus, o Senhor , pois o sacerdote Joiada o aconselhava.

[[v12-12-3]]

^<<v12-12-3,3>>^ No entanto, os lugares pagãos de adoração não foram destruídos, e o povo continuou a oferecer sacrifícios  e a queimar incenso ali.

[[v12-12-4]]

^<<v12-12-4,4>>^ Joás chamou os sacerdotes e mandou que eles juntassem todo o dinheiro recolhido no Templo, isto é, os pagamentos pelos sacrifícios, os impostos do Templo, o dinheiro das promessas e as ofertas voluntárias.

[[v12-12-5]]

^<<v12-12-5,5>>^ Cada sacerdote era responsável pelo dinheiro trazido pelas pessoas que ele servia, e o dinheiro era para ser usado nos consertos do Templo.

[[v12-12-6]]

^<<v12-12-6,6>>^ Mas, no ano vinte e três do reinado de Joás, os sacerdotes ainda não haviam feito nenhum conserto.

[[v12-12-7]]

^<<v12-12-7,7>>^ Por isso Joás chamou Joiada e os outros sacerdotes e lhes perguntou: — Por que vocês não estão consertando o Templo? De agora em diante, não fiquem com o dinheiro que receberem, mas entreguem para que os consertos possam ser feitos.

[[v12-12-8]]

^<<v12-12-8,8>>^ Os sacerdotes concordaram com isso e também concordaram em não ficarem encarregados de fazer os consertos no Templo.

[[v12-12-9]]

^<<v12-12-9,9>>^ Então Joiada pegou uma caixa, fez uma abertura na tampa e pôs a caixa perto do altar, do lado direito de quem entra no Templo. Os sacerdotes que tomavam conta da entrada punham na caixa todo o dinheiro dado pelos adoradores.

[[v12-12-10]]

^<<v12-12-10,10>>^ Quando viam que já havia muito dinheiro na caixa, o secretário do rei e o Grande Sacerdote  vinham, contavam o dinheiro e o punham em sacos.

[[v12-12-11]]

^<<v12-12-11,11>>^ Depois de registrarem a quantia certa, eles entregavam o dinheiro aos homens que estavam encarregados do trabalho no Templo, e estes pagavam os carpinteiros, os construtores,

[[v12-12-12]]

^<<v12-12-12,12>>^ os pedreiros e os cortadores de pedras. Também compravam a madeira e as pedras para os consertos e pagavam todas as outras despesas necessárias.

[[v12-12-13]]

^<<v12-12-13,13>>^ No entanto, nenhuma parte do dinheiro era usada para se fazerem taças de prata, bacias, trombetas, tesouras de aparar pavios de lamparinas ou qualquer outro objeto de prata ou de ouro.

[[v12-12-14]]

^<<v12-12-14,14>>^ Todo o dinheiro era usado para pagar os trabalhadores e para comprar o material dos consertos.

[[v12-12-15]]

^<<v12-12-15,15>>^ Os homens encarregados do trabalho eram honestos em tudo, e por isso não havia necessidade de pedir que prestassem contas do dinheiro.

[[v12-12-16]]

^<<v12-12-16,16>>^ O dinheiro das ofertas para tirar culpas e das ofertas para tirar pecados não era colocado na caixa, mas ficava com os sacerdotes.

[[v12-12-17]]

^<<v12-12-17,17>>^ Nessa época o rei Hazael, da Síria, atacou a cidade de Gate e a conquistou; depois resolveu atacar Jerusalém.

[[v12-12-18]]

^<<v12-12-18,18>>^ O rei Joás, de Judá, pegou todas as ofertas que Josafá, Jeorão e Acazias, que haviam sido reis antes dele, haviam separado para Deus, o Senhor . Junto com essas ofertas ele pôs as suas próprias ofertas e todo o ouro que havia no tesouro do Templo e do palácio e mandou tudo como presente para o rei Hazael. Então Hazael desistiu de atacar Jerusalém.

[[v12-12-19]]

^<<v12-12-19,19>>^ Todas as outras coisas que o rei Joás fez estão escritas na História dos Reis de Judá .

[[v12-12-20]]

^<<v12-12-20,20>>^ Os oficiais do rei Joás fizeram uma revolta contra ele. Então dois deles, Jozacar, filho de Simeate, e Jozabade, filho de Somer, o mataram na casa construída no aterro que havia sido feito no lado leste da cidade de Jerusalém, na estrada que desce para a cidade de Sila. Joás foi sepultado nos túmulos dos reis, na Cidade de Davi , e o seu filho Amazias ficou no lugar dele como rei.

'''

xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[Próximo Capítulo &#62;]