include::./index.adoc[]

[[v12-5-0]]
=== 2 Reis, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-5-1]]

^<<v12-5-1,1>>^ Naamã, o comandante do exército da Síria, era muito respeitado e estimado pelo rei do seu país porque, por meio de Naamã, o Senhor  Deus tinha dado a vitória ao exército dos sírios. Ele era um soldado valente, mas sofria de uma terrível doença da pele.

[[v12-5-2]]

^<<v12-5-2,2>>^ Num dos seus ataques contra Israel, os sírios haviam levado como prisioneira uma menina israelita, que ficou sendo escrava da mulher de Naamã.

[[v12-5-3]]

^<<v12-5-3,3>>^ Um dia a menina disse à patroa: — Eu gostaria que o meu patrão fosse falar com o profeta  que mora em Samaria, pois ele o curaria da sua doença.

[[v12-5-4]]

^<<v12-5-4,4>>^ Então Naamã foi falar com o rei e contou o que a menina tinha dito.

[[v12-5-5]]

^<<v12-5-5,5>>^ E o rei ordenou: — Vá falar com o rei de Israel e entregue esta carta a ele. Então Naamã saiu, levando uns trezentos e cinquenta quilos de prata, e uns setenta quilos de ouro, e dez mudas de roupas finas.

[[v12-5-6]]

^<<v12-5-6,6>>^ A carta que ele levava dizia assim: "Esta carta é para apresentar Naamã, que é meu oficial. Eu quero que você o cure."

[[v12-5-7]]

^<<v12-5-7,7>>^ Quando o rei de Israel leu a carta, rasgou as suas roupas em sinal de medo e exclamou: — Como é que o rei da Síria quer que eu cure este homem? Será que ele pensa que eu sou Deus e que tenho o poder de dar a vida e de tirá-la? Ele está querendo briga!

[[v12-5-8]]

^<<v12-5-8,8>>^ O profeta Eliseu soube do que havia acontecido e mandou dizer ao rei: — Por que o senhor está tão preocupado? Mande que esse homem venha falar comigo, e eu mostrarei a ele que há um profeta em Israel!

[[v12-5-9]]

^<<v12-5-9,9>>^ Então Naamã foi com os seus cavalos e carros e parou na porta da casa de Eliseu.

[[v12-5-10]]

^<<v12-5-10,10>>^ Eliseu mandou que um empregado saísse e dissesse a ele que fosse se lavar sete vezes no rio Jordão, pois assim ficaria completamente curado da sua doença.

[[v12-5-11]]

^<<v12-5-11,11>>^ Mas Naamã ficou muito zangado e disse: — Eu pensava que pelo menos o profeta ia sair e falar comigo e que oraria ao Senhor , seu Deus, e que passaria a mão sobre o lugar doente e me curaria!

[[v12-5-12]]

^<<v12-5-12,12>>^ Além disso, por acaso, os rios Abana e Farpar, em Damasco, não são melhores do que qualquer rio da terra de Israel? Será que eu não poderia me lavar neles e ficar curado? E foi embora muito bravo.

[[v12-5-13]]

^<<v12-5-13,13>>^ Então os seus empregados foram até o lugar onde ele estava e disseram: — Se o profeta mandasse o senhor fazer alguma coisa difícil, por acaso, o senhor não faria? Por que é que o senhor não pode ir se lavar, como ele disse, e ficar curado?

[[v12-5-14]]

^<<v12-5-14,14>>^ Então Naamã desceu até o rio Jordão e mergulhou sete vezes, como Eliseu tinha dito. E ficou completamente curado. A sua carne ficou firme e sadia como a de uma criança.

[[v12-5-15]]

^<<v12-5-15,15>>^ Depois ele voltou com todos os seus homens até o lugar onde Eliseu estava e disse: — Agora eu sei que no mundo inteiro não existe nenhum deus, a não ser o Deus de Israel. Aceite um presente meu, por favor.

[[v12-5-16]]

^<<v12-5-16,16>>^ Eliseu respondeu: — Juro pelo Senhor , o Deus vivo, a quem sirvo, que não aceitarei nenhum presente. Naamã insistiu com ele para que aceitasse, mas ele não quis.

[[v12-5-17]]

^<<v12-5-17,17>>^ Aí Naamã disse: — Já que o senhor não quer aceitar o meu presente, então deixe que eu leve para casa duas mulas carregadas de terra , pois de agora em diante eu não vou oferecer sacrifícios  e ofertas que são completamente queimadas a nenhum deus, a não ser a Deus, o Senhor .

[[v12-5-18]]

^<<v12-5-18,18>>^ Mas eu gostaria que ele me perdoasse uma coisa, que é a seguinte: quando eu tiver de acompanhar o meu rei ao templo de Rimom, o deus da Síria, para ali adorar, eu vou ter de adorá-lo também. Que o Senhor  Deus me perdoe por isso!

[[v12-5-19]]

^<<v12-5-19,19>>^ Eliseu disse: — Adeus! Boa viagem! Quando Naamã já estava um pouco longe,

[[v12-5-20]]

^<<v12-5-20,20>>^ Geazi, o empregado de Eliseu, começou a pensar: — O meu patrão deixou que Naamã fosse embora sem pagar nada. Ele devia ter aceitado o que o sírio estava oferecendo. Juro pelo Senhor , o Deus vivo, que vou correr atrás dele e receber alguma coisa!

[[v12-5-21]]

^<<v12-5-21,21>>^ Então Geazi saiu correndo. Quando Naamã viu que um homem vinha correndo atrás dele, desceu do carro e perguntou: — Aconteceu alguma coisa?

[[v12-5-22]]

^<<v12-5-22,22>>^ — Não! — respondeu Geazi. — Mas o meu patrão mandou dizer que agora mesmo chegaram dois membros de um grupo de profetas  da região montanhosa de Efraim. Então ele gostaria que o senhor desse a ele uns trinta quilos de prata e duas mudas de roupas finas.

[[v12-5-23]]

^<<v12-5-23,23>>^ Naamã disse: — Por favor, leve sessenta quilos de prata. E insistiu com ele. Então pôs a prata em dois sacos, entregou a prata e as duas mudas de roupas finas a dois dos seus empregados e mandou que eles fossem na frente de Geazi.

[[v12-5-24]]

^<<v12-5-24,24>>^ Quando eles chegaram ao morro onde Eliseu morava, Geazi pegou os dois sacos e carregou-os para dentro de casa. Depois mandou embora os empregados de Naamã,

[[v12-5-25]]

^<<v12-5-25,25>>^ entrou em casa de novo e foi falar com Eliseu. Este perguntou: — Onde é que você foi? — Eu não fui a lugar nenhum! — respondeu Geazi.

[[v12-5-26]]

^<<v12-5-26,26>>^ Mas Eliseu disse: — O meu espírito estava com você quando aquele homem desceu do carro para falar com você. Esta não era ocasião para você aceitar dinheiro e roupas, plantações de oliveiras e de uvas, ovelhas e gado ou empregados e empregadas.

[[v12-5-27]]

^<<v12-5-27,27>>^ Portanto, a doença de Naamã vai pegar em você, e os seus descendentes a terão para sempre. Quando saiu dali Geazi tinha pegado a doença, e a sua pele estava branca como a neve.

'''

xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[Próximo Capítulo &#62;]