include::./index.adoc[]

[[v12-11-0]]
=== 2 Reis, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-11-1]]

^<<v12-11-1,1>>^ Assim que Atalia, a mãe do rei Acazias, soube da morte do filho, deu ordem para que todas as pessoas da família real fossem mortas.

[[v12-11-2]]

^<<v12-11-2,2>>^ Somente Joás, filho de Acazias, escapou. Ele ia ser morto junto com os outros, mas foi salvo pela sua tia Jeoseba, que era filha do rei Jeorão e meia-irmã de Acazias. Ela levou Joás e a sua babá para um quarto do Templo e o escondeu de Atalia. Assim ele não foi morto.

[[v12-11-3]]

^<<v12-11-3,3>>^ Durante seis anos Jeoseba cuidou do menino e o conservou escondido no Templo, enquanto Atalia era a rainha.

[[v12-11-4]]

^<<v12-11-4,4>>^ Mas no sétimo ano o sacerdote Joiada mandou chamar os oficiais encarregados dos guarda-costas e dos guardas do palácio e disse que viessem ao Templo. Ali ele fez com que jurassem concordar com o que ele havia planejado fazer. Então lhes mostrou Joás, o filho do rei Acazias,

[[v12-11-5]]

^<<v12-11-5,5>>^ e deu a eles as seguintes ordens: — Quando vocês ficarem de serviço no sábado, a terça parte deve guardar o palácio;

[[v12-11-6]]

^<<v12-11-6,6>>^ a outra terça parte deve ficar de guarda no Portão Sur, e a outra terça parte deve ficar no portão, atrás dos outros guardas.

[[v12-11-7]]

^<<v12-11-7,7>>^ Os dois grupos que deixarem o serviço no sábado ficarão de guarda no Templo para proteger o rei.

[[v12-11-8]]

^<<v12-11-8,8>>^ Vocês devem guardar o rei Joás com as espadas na mão e ir com ele a qualquer lugar aonde ele for. Qualquer pessoa que chegar perto de vocês deve ser morta.

[[v12-11-9]]

^<<v12-11-9,9>>^ Os oficiais obedeceram à ordem de Joiada e levaram a ele os seus soldados, isto é, os que saíam do serviço no sábado e os que entravam de serviço no sábado.

[[v12-11-10]]

^<<v12-11-10,10>>^ Joiada entregou aos oficiais as lanças e os escudos  que tinham sido do rei Davi e que haviam ficado guardados no Templo.

[[v12-11-11]]

^<<v12-11-11,11>>^ Ele pôs os soldados armados com espadas por toda a frente do Templo, para protegerem o rei.

[[v12-11-12]]

^<<v12-11-12,12>>^ Então Joiada levou Joás para fora, colocou a coroa na cabeça dele e lhe deu uma cópia da Lei . Aí Joás foi ungido  e apresentado como rei. O povo bateu palmas e gritou: — Viva o rei!

[[v12-11-13]]

^<<v12-11-13,13>>^ A rainha Atalia ouviu o barulho que os guardas e o povo faziam e foi até o Templo, onde todos estavam reunidos.

[[v12-11-14]]

^<<v12-11-14,14>>^ Ela viu o novo rei perto da coluna, na entrada do Templo, conforme era o costume. Ele estava rodeado pelos oficiais e pelos corneteiros, e todo o povo estava gritando de alegria e tocando trombetas. Em sinal de desespero Atalia rasgou as suas roupas e gritou: — Traição! Traição!

[[v12-11-15]]

^<<v12-11-15,15>>^ O sacerdote Joiada não queria que Atalia fosse morta na área do Templo e por isso deu aos oficiais do exército a seguinte ordem: — Levem a rainha para fora, passando pelo meio das filas de guardas, e matem qualquer pessoa que tentar salvá-la.

[[v12-11-16]]

^<<v12-11-16,16>>^ Então eles a prenderam e levaram para o palácio. E ali, no Portão dos Cavalos, ela foi morta.

[[v12-11-17]]

^<<v12-11-17,17>>^ O sacerdote Joiada fez uma aliança entre o Senhor  Deus, e o rei, e o povo, a fim de que eles fossem o povo de Deus. Fez também um acordo  entre o rei e o povo.

[[v12-11-18]]

^<<v12-11-18,18>>^ Então o povo foi até o templo do deus Baal  e o derrubou. Eles despedaçaram os altares e os ídolos e ali, em frente dos altares, mataram Matã, o sacerdote de Baal. Joiada pôs guardas no Templo,

[[v12-11-19]]

^<<v12-11-19,19>>^ e então ele, os oficiais, a guarda pessoal do rei e os guardas do palácio levaram o rei do Templo para o palácio, e o povo todo foi atrás. Joás entrou pelo Portão da Guarda e sentou-se no trono.

[[v12-11-20]]

^<<v12-11-20,20>>^ Todo o povo estava feliz, e a cidade de Jerusalém ficou calma depois que Atalia foi morta no palácio.

[[v12-11-21]]

^<<v12-11-21,21>>^ Joás tinha sete anos de idade quando se tornou rei.

'''

xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[&#60; Capítulo Anterior] | <<v12-11-0,Topo>> | xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[Próximo Capítulo &#62;]