include::./index.adoc[]

[[v12-24-0]]
=== 2 Reis, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-24-1]]

^<<v12-24-1,1>>^ Durante o reinado de Jeoaquim, o rei Nabucodonosor, da Babilônia, invadiu Judá, e durante três anos Jeoaquim foi dominado por ele, mas depois se revoltou.

[[v12-24-2]]

^<<v12-24-2,2>>^ Para destruir Judá, o Senhor  Deus fez conforme tinha dito pelos seus servos , os profetas , isto é, ele mandou contra Jeoaquim bandos armados de babilônios, sírios, moabitas e amonitas.

[[v12-24-3]]

^<<v12-24-3,3>>^ Isso aconteceu com Judá por ordem do Senhor  para expulsar o povo de Judá da sua presença, por causa de todos os pecados que o rei Manassés havia cometido

[[v12-24-4]]

^<<v12-24-4,4>>^ e principalmente por causa de todas as pessoas inocentes que ele havia matado. O Senhor  não quis perdoar Manassés por esse pecado.

[[v12-24-5]]

^<<v12-24-5,5>>^ Tudo o que Jeoaquim fez está escrito na História dos Reis de Judá .

[[v12-24-6]]

^<<v12-24-6,6>>^ Jeoaquim morreu, e o seu filho Joaquim ficou no lugar dele como rei.

[[v12-24-7]]

^<<v12-24-7,7>>^ O rei do Egito nunca mais saiu da sua terra com o seu exército, pois o rei da Babilônia havia conquistado todas as terras que tinham sido do Egito, desde o rio Eufrates até a fronteira norte do Egito.

[[v12-24-8]]

^<<v12-24-8,8>>^ Joaquim tinha dezoito anos de idade quando se tornou rei de Judá. Ele governou três meses em Jerusalém. A mãe dele se chamava Neústa e era filha de Elnatã, de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ Seguindo o exemplo do seu pai, Joaquim fez coisas erradas, que não agradam a Deus, o Senhor .

[[v12-24-10]]

^<<v12-24-10,10>>^ Foi durante o reinado de Joaquim que o exército da Babilônia, comandado pelos oficiais do rei Nabucodonosor, marchou contra Jerusalém e cercou a cidade.

[[v12-24-11]]

^<<v12-24-11,11>>^ Enquanto a cidade estava cercada, o próprio rei Nabucodonosor foi até lá,

[[v12-24-12]]

^<<v12-24-12,12>>^ e o rei Joaquim, a sua mãe, os seus filhos, os seus oficiais e os funcionários do palácio se entregaram aos babilônios. No oitavo ano do reinado de Nabucodonosor, ele levou Joaquim como prisioneiro.

[[v12-24-13]]

^<<v12-24-13,13>>^ Também levou para a Babilônia todos os tesouros do Templo e do palácio. Conforme o Senhor  tinha dito, Nabucodonosor quebrou todos os objetos de ouro que o rei Salomão tinha feito para serem usados no Templo.

[[v12-24-14]]

^<<v12-24-14,14>>^ Nabucodonosor levou como prisioneiros toda a gente de Jerusalém, todos os príncipes e todos os cidadãos mais importantes, dez mil pessoas ao todo. Levou também todos os artesãos, incluindo os ferreiros. Ficaram em Judá somente as pessoas mais pobres.

[[v12-24-15]]

^<<v12-24-15,15>>^ Nabucodonosor levou Joaquim para a Babilônia como prisioneiro, junto com a mãe dele, as suas esposas, os seus oficiais e as pessoas mais importantes de Judá.

[[v12-24-16]]

^<<v12-24-16,16>>^ Nabucodonosor mandou todos os homens importantes para a Babilônia, sete mil ao todo, e mil artesãos, incluindo os ferreiros, todos eles treinados para lutar na guerra.

[[v12-24-17]]

^<<v12-24-17,17>>^ Nabucodonosor colocou Matanias, o tio de Joaquim, como rei de Judá e mudou o nome dele para Zedequias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Zedequias tinha vinte e um anos de idade quando se tornou rei de Judá. Ele governou onze anos em Jerusalém. A mãe dele se chamava Hamutal e era filha de Jeremias, da cidade de Libna.

[[v12-24-19]]

^<<v12-24-19,19>>^ O rei Zedequias fez coisas erradas, que não agradam a Deus, o Senhor , como o rei Joaquim havia feito.

[[v12-24-20]]

^<<v12-24-20,20>>^ O Senhor  ficou tão irado  contra o povo de Jerusalém e de Judá, que os afastou da sua presença.

'''

xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]