include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-21-1]]

^<<v12-21-1,1>>^ Manassés tinha doze anos de idade quando se tornou rei de Judá. Ele governou cinquenta e cinco anos em Jerusalém. A mãe dele se chamava Hefziba.

[[v12-21-2]]

^<<v12-21-2,2>>^ Manassés pecou contra Deus, o Senhor , seguindo os costumes nojentos das nações que o Senhor  havia expulsado da terra conforme o povo de Israel avançava.

[[v12-21-3]]

^<<v12-21-3,3>>^ Ele construiu de novo os lugares pagãos de adoração que Ezequias, o seu pai, havia destruído. Construiu altares para a adoração do deus Baal  e fez um poste da deusa Aserá , como Acabe, rei de Israel, havia feito. Manassés também adorou as estrelas

[[v12-21-4]]

^<<v12-21-4,4>>^ e construiu altares pagãos no Templo onde, conforme o Senhor  Deus tinha dito, ele devia ser adorado.

[[v12-21-5]]

^<<v12-21-5,5>>^ Nos dois pátios do Templo, Manassés construiu altares para a adoração das estrelas.

[[v12-21-6]]

^<<v12-21-6,6>>^ Queimou o seu filho em sacrifício , fazia adivinhações e feitiçarias e consultava adivinhos e médiuns. Pecou muito contra Deus, o Senhor , e fez com que ele ficasse irado .

[[v12-21-7]]

^<<v12-21-7,7>>^ Manassés colocou uma imagem esculpida da deusa Aserá no Templo, o lugar a respeito do qual o Senhor  tinha dito o seguinte a Davi e ao seu filho Salomão: "Em todo o território das doze tribos  de Israel, escolhi este Templo, aqui em Jerusalém, para ser o lugar onde serei adorado para sempre.

[[v12-21-8]]

^<<v12-21-8,8>>^ E, se o povo de Israel obedecer a todos os meus mandamentos e fizer tudo o que manda a Lei  que o meu servo  Moisés deu a eles, então eu não deixarei que sejam expulsos da terra que dei aos seus antepassados."

[[v12-21-9]]

^<<v12-21-9,9>>^ Mas o povo de Judá não obedeceu a Deus, e Manassés os levou a cometer pecados ainda piores do que aqueles cometidos pelas nações que o Senhor  Deus havia destruído conforme o seu povo ia avançando.

[[v12-21-10]]

^<<v12-21-10,10>>^ Por meio dos seus servos, os profetas , o Senhor  Deus disse:

[[v12-21-11]]

^<<v12-21-11,11>>^ — O rei Manassés, de Judá, tem feito essas coisas nojentas, coisas muito piores do que aquelas que os amorreus fizeram, e com os seus ídolos levou o povo de Judá a pecar.

[[v12-21-12]]

^<<v12-21-12,12>>^ Por isso, eu, o Senhor , o Deus de Israel, vou fazer cair sobre Jerusalém e sobre Judá uma desgraça tão grande, que todos aqueles que ouvirem contar a respeito dela ficarão espantados.

[[v12-21-13]]

^<<v12-21-13,13>>^ Eu castigarei Jerusalém como fiz com a cidade de Samaria e como fiz com o rei Acabe, de Israel, e com os seus descendentes. Deixarei Jerusalém limpa do seu povo, tão limpa como um prato que foi esfregado e virado de boca para baixo.

[[v12-21-14]]

^<<v12-21-14,14>>^ Eu abandonarei as pessoas que não tiverem morrido e as entregarei aos seus inimigos, que as prenderão e que roubarão tudo o que houver na sua terra.

[[v12-21-15]]

^<<v12-21-15,15>>^ Farei isso com o meu povo porque eles têm feito coisas erradas, que não me agradam, e me têm deixado irado desde o tempo em que os antepassados deles saíram do Egito até hoje.

[[v12-21-16]]

^<<v12-21-16,16>>^ Manassés matou tantas pessoas inocentes, que as ruas de Jerusalém ficaram alagadas de sangue. Além disso, ele cometeu o pecado de levar o povo de Judá a adorar ídolos, fazendo o que é errado, o que não agrada a Deus, o Senhor .

[[v12-21-17]]

^<<v12-21-17,17>>^ Todas as outras coisas que Manassés fez e também os pecados que ele cometeu, tudo isso está escrito na História dos Reis de Judá .

[[v12-21-18]]

^<<v12-21-18,18>>^ Manassés morreu e foi sepultado no jardim do palácio, o jardim de Uzá, e o seu filho Amom ficou no lugar dele como rei.

[[v12-21-19]]

^<<v12-21-19,19>>^ Amom tinha vinte e dois anos de idade quando se tornou rei de Judá. Ele governou dois anos em Jerusalém. A mãe dele se chamava Mesulemete e era filha de Haruz, da cidade de Jotbatá.

[[v12-21-20]]

^<<v12-21-20,20>>^ Como o seu pai Manassés, Amom fez coisas erradas, que não agradam a Deus, o Senhor .

[[v12-21-21]]

^<<v12-21-21,21>>^ Ele imitou as ações do seu pai e adorou e serviu os ídolos que o seu pai havia adorado.

[[v12-21-22]]

^<<v12-21-22,22>>^ Assim Amom abandonou o Senhor , o Deus dos seus antepassados, e foi desobediente a ele.

[[v12-21-23]]

^<<v12-21-23,23>>^ Os oficiais de Amom fizeram uma revolta contra ele e o mataram no palácio.

[[v12-21-24]]

^<<v12-21-24,24>>^ Mas o povo de Judá matou todos os que haviam feito a revolta contra Amom e pôs o seu filho Josias como rei.

[[v12-21-25]]

^<<v12-21-25,25>>^ Todas as outras coisas que Amom fez estão escritas na História dos Reis de Judá .

[[v12-21-26]]

^<<v12-21-26,26>>^ Amom foi sepultado no seu túmulo, no jardim de Uzá, e o seu filho Josias ficou no lugar dele como rei.

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]