include::./index.adoc[]

[[v12-6-0]]
=== 2 Reis, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-6-1]]

^<<v12-6-1,1>>^ Eliseu dirigia um grupo de profetas . Um dia eles lhe pediram: — O lugar onde moramos com você é muito pequeno.

[[v12-6-2]]

^<<v12-6-2,2>>^ Dê licença para irmos até o rio Jordão a fim de cortar algumas árvores. Com elas construiremos uma casa para a gente morar. — Podem ir! — respondeu Eliseu.

[[v12-6-3]]

^<<v12-6-3,3>>^ Um dos profetas insistiu que Eliseu fosse com eles. Eliseu aceitou,

[[v12-6-4]]

^<<v12-6-4,4>>^ e eles saíram juntos. Quando chegaram ao Jordão, começaram a trabalhar.

[[v12-6-5]]

^<<v12-6-5,5>>^ Um deles estava cortando uma árvore, quando, de repente, o ferro do seu machado escapou do cabo e caiu na água. — O que vou fazer, senhor? — gritou ele para Eliseu. — O machado era emprestado!

[[v12-6-6]]

^<<v12-6-6,6>>^ — Onde foi que ele caiu? — perguntou Eliseu. O homem mostrou o lugar. Então Eliseu cortou um pedaço de pau, jogou na água e fez o machado boiar.

[[v12-6-7]]

^<<v12-6-7,7>>^ — Pegue-o! — mandou ele. E o homem esticou o braço e o pegou.

[[v12-6-8]]

^<<v12-6-8,8>>^ O rei da Síria estava em guerra contra Israel. Ele pediu conselho aos seus oficiais e escolheu um lugar para armar o seu acampamento.

[[v12-6-9]]

^<<v12-6-9,9>>^ Mas o profeta  Eliseu mandou um recado ao rei de Israel, avisando-lhe que não fosse para perto daquele lugar, pois os sírios estavam ali esperando escondidos para atacá-lo.

[[v12-6-10]]

^<<v12-6-10,10>>^ Então o rei de Israel avisou os homens que moravam naquele lugar, e eles ficaram alerta. Isso aconteceu várias vezes.

[[v12-6-11]]

^<<v12-6-11,11>>^ O rei da Síria ficou muito aborrecido; então chamou os seus oficiais e lhes perguntou: — Qual de vocês está do lado do rei de Israel?

[[v12-6-12]]

^<<v12-6-12,12>>^ Um deles respondeu: — Nenhum de nós, ó rei. O profeta Eliseu é quem conta ao rei de Israel tudo o que o senhor fala até mesmo dentro do seu próprio quarto.

[[v12-6-13]]

^<<v12-6-13,13>>^ Então o rei ordenou: — Descubram onde ele está, que eu o prenderei. Contaram-lhe que Eliseu estava em Dotã,

[[v12-6-14]]

^<<v12-6-14,14>>^ e ele mandou para lá uma grande tropa de soldados com cavalos e carros de guerra. Eles chegaram de noite à cidade e a cercaram.

[[v12-6-15]]

^<<v12-6-15,15>>^ No dia seguinte cedinho, o empregado de Eliseu levantou-se e saiu de casa. Aí viu as tropas sírias com os seus cavalos e carros de guerra, cercando a cidade. Então entrou em casa e disse a Eliseu: — Senhor, nós estamos perdidos! O que vamos fazer?

[[v12-6-16]]

^<<v12-6-16,16>>^ Eliseu disse: — Não tenha medo, pois aqueles que estão conosco são mais numerosos do que os que estão com eles.

[[v12-6-17]]

^<<v12-6-17,17>>^ Então orou assim: — Ó Senhor  Deus, abre os olhos do meu empregado e deixa que ele veja! Deus respondeu à oração dele. Aí o empregado de Eliseu olhou para cima e viu que ao redor de Eliseu o morro estava coberto de cavalos e carros de fogo.

[[v12-6-18]]

^<<v12-6-18,18>>^ Quando os sírios atacaram, Eliseu orou assim: — Ó Senhor  Deus, faze com que esses homens fiquem cegos! Deus respondeu à oração de Eliseu e fez com que os sírios ficassem cegos.

[[v12-6-19]]

^<<v12-6-19,19>>^ Então Eliseu foi falar com eles e disse: — Vocês estão no caminho errado; esta cidade não é a que estão procurando. Venham comigo, que eu vou levar vocês até o homem que estão procurando. E os guiou até a cidade de Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ Logo que eles entraram na cidade, Eliseu orou assim: — Ó Senhor  Deus, abre os olhos deles e deixa que eles vejam. Então Deus fez com que os sírios enxergassem de novo, e eles viram que estavam dentro da cidade de Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ Quando o rei de Israel viu os sírios, perguntou a Eliseu: — Devo matá-los, senhor? Devo matá-los?

[[v12-6-22]]

^<<v12-6-22,22>>^ — Não! De jeito nenhum! — respondeu ele. — Por acaso, o senhor mata os soldados que são feitos prisioneiros na guerra? Dê de comer e de beber a estes aqui e deixe que voltem para o rei deles.

[[v12-6-23]]

^<<v12-6-23,23>>^ Então o rei de Israel mandou fazer uma grande festa para aqueles sírios. E, depois que comeram e beberam, ele os mandou de volta para o rei da Síria. Daí em diante os sírios pararam de atacar a terra de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ Algum tempo depois, o rei Ben-Hadade, da Síria, levou todo o seu exército para lutar contra Israel e cercou a cidade de Samaria.

[[v12-6-25]]

^<<v12-6-25,25>>^ Por causa disso, a falta de alimentos naquela cidade foi tão grande, que uma cabeça de jumento custava oitenta barras de prata, e duzentos gramas de esterco de pomba custavam cinco barras de prata.

[[v12-6-26]]

^<<v12-6-26,26>>^ Certo dia o rei de Israel estava passando por cima da muralha da cidade, quando uma mulher gritou para ele: — Ó rei, meu senhor, me ajude!

[[v12-6-27]]

^<<v12-6-27,27>>^ Ele respondeu: — Se o Senhor  Deus não ajudar você, como é que eu posso ajudá-la? Você pensa que eu tenho trigo ou vinho?

[[v12-6-28]]

^<<v12-6-28,28>>^ Mas diga qual é o seu problema. Ela respondeu: — Outro dia esta mulher me disse: "Vamos comer o seu filho hoje e amanhã comeremos o meu."

[[v12-6-29]]

^<<v12-6-29,29>>^ Então nós cozinhamos o meu filho e o comemos. No dia seguinte eu disse que era a vez de comermos o filho dela, mas ela o escondeu!

[[v12-6-30]]

^<<v12-6-30,30>>^ Ao ouvir isso, o rei rasgou as suas roupas em sinal de desgosto, e as pessoas que estavam perto da muralha viram que por baixo das suas roupas ele estava vestido com roupa de pano grosseiro.

[[v12-6-31]]

^<<v12-6-31,31>>^ E o rei gritou: — Que Deus me mate se, antes que o dia acabe, eu não mandar cortar a cabeça de Eliseu, filho da Safate!

[[v12-6-32]]

^<<v12-6-32,32>>^ E mandou que um mensageiro fosse buscá-lo. Enquanto isso, Eliseu estava em casa com alguns líderes do povo que haviam ido visitá-lo. Antes que o mensageiro do rei chegasse, Eliseu disse aos líderes: — Aquele assassino está mandando alguém para me matar. Por isso, quando ele chegar, fechem a porta e não deixem que entre. O próprio rei virá logo depois dele.

[[v12-6-33]]

^<<v12-6-33,33>>^ Eliseu ainda estava falando com eles, quando o rei chegou e disse: — Foi o Senhor  Deus quem fez cair toda esta desgraça sobre nós. Por que iria eu ficar mais tempo esperando que ele fizesse alguma coisa?

'''

xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]