include::./index.adoc[]

[[v12-1-0]]
=== 2 Reis, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-1-1]]

^<<v12-1-1,1>>^ Depois da morte do rei Acabe, de Israel, o país de Moabe se revoltou contra Israel.

[[v12-1-2]]

^<<v12-1-2,2>>^ O rei Acazias, que ficou no lugar de Acabe, caiu do terraço do alto do seu palácio em Samaria e ficou muito ferido. Então mandou que alguns mensageiros fossem consultar Baal-Zebube, o deus da cidade filisteia de Ecrom, a fim de saber se ia sarar.

[[v12-1-3]]

^<<v12-1-3,3>>^ Mas um anjo do Senhor  mandou que Elias, o profeta  de Tisbé, fosse encontrar-se com os mensageiros do rei Acazias e lhes perguntasse assim: "Por que vocês estão indo consultar Baal-Zebube, o deus de Ecrom? Por acaso, pensam que não há Deus em Israel?

[[v12-1-4]]

^<<v12-1-4,4>>^ Digam ao rei que o Senhor  Deus diz: ‘Você não vai sarar dos seus ferimentos; você vai morrer!’ " Elias fez o que Deus havia mandado,

[[v12-1-5]]

^<<v12-1-5,5>>^ e os mensageiros voltaram para o lugar onde o rei estava. Ele perguntou: — Por que vocês voltaram?

[[v12-1-6]]

^<<v12-1-6,6>>^ Eles responderam: — Um homem se encontrou com a gente e disse que voltássemos e disséssemos que o Senhor  manda perguntar o seguinte: "Por que é que você está mandando mensageiros para consultarem Baal-Zebube, o deus de Ecrom? Será que você pensa que não há Deus em Israel? Você não vai sarar dos seus ferimentos; você vai morrer!"

[[v12-1-7]]

^<<v12-1-7,7>>^ — Como era o homem que lhes disse isso? — perguntou o rei.

[[v12-1-8]]

^<<v12-1-8,8>>^ E eles responderam: — Ele estava usando uma capa  de pele de animais, amarrada com um cinto de couro. — É Elias, o profeta de Tisbé! — disse o rei.

[[v12-1-9]]

^<<v12-1-9,9>>^ Então mandou que um oficial fosse com cinquenta soldados prender Elias. O oficial o encontrou sentado no alto de um morro e disse: — Homem de Deus, o rei mandou você descer daí.

[[v12-1-10]]

^<<v12-1-10,10>>^ Elias respondeu: — Se eu sou um homem de Deus, que venha fogo do céu e mate você e os seus soldados! No mesmo instante desceu fogo do céu e matou o oficial e os seus soldados.

[[v12-1-11]]

^<<v12-1-11,11>>^ O rei enviou outro oficial com cinquenta soldados. Ele subiu e disse a Elias: — Homem de Deus, o rei ordenou que você desça daí agora mesmo!

[[v12-1-12]]

^<<v12-1-12,12>>^ Elias respondeu: — Se eu sou um homem de Deus, que venha fogo do céu e mate você e os seus soldados! No mesmo instante o fogo de Deus desceu e matou o oficial e os seus soldados.

[[v12-1-13]]

^<<v12-1-13,13>>^ Mais uma vez o rei mandou um oficial com cinquenta soldados. Ele subiu o morro, ajoelhou-se em frente de Elias e pediu: — Homem de Deus, por favor, não acabe com a minha vida nem com a vida destes cinquenta homens!

[[v12-1-14]]

^<<v12-1-14,14>>^ Os outros dois oficiais e os seus soldados foram mortos pelo fogo do céu; mas tenha dó de mim, por favor!

[[v12-1-15]]

^<<v12-1-15,15>>^ O anjo do Senhor  disse a Elias: — Desça com ele e não tenha medo. Então Elias foi junto com o oficial falar com o rei

[[v12-1-16]]

^<<v12-1-16,16>>^ e disse: — O Senhor  Deus diz assim: "Ó rei, você agiu como se em Israel não houvesse Deus para consultar e mandou mensageiros para consultarem Baal-Zebube, o deus de Ecrom. Por isso, você não vai ficar bom; você vai morrer!"

[[v12-1-17]]

^<<v12-1-17,17>>^ E Acazias morreu, como o Senhor  tinha dito por meio de Elias. Acazias não tinha filhos, e por isso o seu irmão Jorão ficou no lugar dele como rei. Isso aconteceu no segundo ano do reinado de Jeorão, filho de Josafá, rei de Judá.

[[v12-1-18]]

^<<v12-1-18,18>>^ Todas as outras coisas que o rei Acazias fez estão escritas na História dos Reis de Israel .

'''

xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[&#60; Capítulo Anterior] | <<v12-1-0,Topo>> | xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[Próximo Capítulo &#62;]