include::./index.adoc[]

[[v12-25-0]]
=== 2 Reis, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-25-1]]

^<<v12-25-1,1>>^ Zedequias se revoltou contra o rei Nabucodonosor, da Babilônia. Então Nabucodonosor veio com todo o seu exército e atacou a cidade de Jerusalém no dia dez do décimo mês do ano nove do reinado de Zedequias. Eles acamparam fora da cidade e construíram rampas de ataque ao redor dela.

[[v12-25-2]]

^<<v12-25-2,2>>^ Ficaram cercando a cidade até o ano onze do reinado de Zedequias.

[[v12-25-3]]

^<<v12-25-3,3>>^ No dia nove do quarto mês do mesmo ano, quando a cidade estava apertada pela fome, e não havia comida para o povo,

[[v12-25-4]]

^<<v12-25-4,4>>^ os babilônios conseguiram abrir uma brecha na muralha da cidade. Embora eles estivessem em volta da cidade, todos os soldados israelitas fugiram durante a noite. Eles saíram pelo caminho do jardim do rei, foram pelo portão que ligava as duas muralhas e fugiram na direção do vale do Jordão.

[[v12-25-5]]

^<<v12-25-5,5>>^ Mas o exército dos babilônios perseguiu o rei Zedequias, alcançou-o na planície de Jericó, e todos os seus soldados o abandonaram.

[[v12-25-6]]

^<<v12-25-6,6>>^ Zedequias foi preso e levado para o rei da Babilônia, que estava na cidade de Ribla. Ali Nabucodonosor pronunciou a sua sentença contra Zedequias.

[[v12-25-7]]

^<<v12-25-7,7>>^ Mataram os seus filhos na frente dele. Então Nabucodonosor mandou furar os olhos de Zedequias e prendê-lo com correntes de bronze; depois o levaram para a Babilônia.

[[v12-25-8]]

^<<v12-25-8,8>>^ No dia sete do quinto mês do ano dezenove do reinado de Nabucodonosor, da Babilônia, Nebuzaradã, conselheiro do rei e comandante-geral do seu exército, entrou em Jerusalém.

[[v12-25-9]]

^<<v12-25-9,9>>^ Ele incendiou o Templo, o palácio do rei e as casas de todas as pessoas importantes de Jerusalém,

[[v12-25-10]]

^<<v12-25-10,10>>^ e os seus soldados derrubaram as muralhas da cidade.

[[v12-25-11]]

^<<v12-25-11,11>>^ Então Nebuzaradã levou para a Babilônia as pessoas que haviam sido deixadas na cidade, o resto dos operários especializados e aqueles que haviam passado para o lado dos babilônios.

[[v12-25-12]]

^<<v12-25-12,12>>^ Mas deixou em Judá algumas das pessoas mais pobres e as pôs para trabalhar nas plantações de uvas e nos campos.

[[v12-25-13]]

^<<v12-25-13,13>>^ Os babilônios quebraram as colunas de bronze e as carretas que estavam no Templo e também o grande tanque de bronze. Então levaram todo o bronze para a Babilônia.

[[v12-25-14]]

^<<v12-25-14,14>>^ Também levaram embora as pás e as vasilhas usadas para carregar as cinzas do altar. Levaram ainda as tesouras de cortar pavios de lamparinas, as vasilhas de queimar incenso e todos os outros objetos de bronze usados no serviço do Templo.

[[v12-25-15]]

^<<v12-25-15,15>>^ Nebuzaradã levou embora tudo o que era feito de ouro ou de prata, incluindo as vasilhas pequenas e os pratos de carregar brasas.

[[v12-25-16]]

^<<v12-25-16,16>>^ Não foi possível calcular o peso dos objetos de bronze que o rei Salomão havia feito para o Templo, isto é, as duas colunas, as carretas e o grande tanque, pois eram pesados demais.

[[v12-25-17]]

^<<v12-25-17,17>>^ As duas colunas eram iguais, e cada uma tinha oito metros de altura, com um remate de bronze no alto, que media um metro e trinta de altura. Em toda a volta do remate havia um enfeite rendilhado e com romãs de bronze.

[[v12-25-18]]

^<<v12-25-18,18>>^ Nebuzaradã, o comandante-geral do exército babilônio, também levou como prisioneiros Seraías, o Grande Sacerdote , e Sofonias, o segundo sacerdote, e os três outros oficiais de importância do Templo.

[[v12-25-19]]

^<<v12-25-19,19>>^ Da cidade ele levou o oficial que tinha sido o comandante das tropas, cinco conselheiros do rei que ainda estavam lá, o oficial encarregado de alistar homens para o exército e mais sessenta homens importantes.

[[v12-25-20]]

^<<v12-25-20,20>>^ Nebuzaradã os levou ao rei da Babilônia, que estava na cidade de Ribla,

[[v12-25-21]]

^<<v12-25-21,21>>^ na terra de Hamate. Ali o rei mandou surrá-los e depois matá-los. Assim o povo de Judá foi levado como prisioneiro para fora da sua terra.

[[v12-25-22]]

^<<v12-25-22,22>>^ O rei Nabucodonosor, da Babilônia, colocou Gedalias, filho de Aicã e neto de Safã, como governador de Judá e o encarregou de todos aqueles que não haviam sido levados para a Babilônia.

[[v12-25-23]]

^<<v12-25-23,23>>^ Os oficiais e os soldados israelitas que não se haviam entregado souberam disso e foram se encontrar com Gedalias em Mispa. Esses oficiais eram: Ismael, filho de Netanias; Joanã, filho de Careá; Seraías, filho de Tanumete, da cidade de Netofa; e Jazanias, de Maacá.

[[v12-25-24]]

^<<v12-25-24,24>>^ Gedalias disse a eles: — Eu dou a minha palavra que vocês não precisam ter medo dos oficiais babilônios. Fiquem morando nesta terra, trabalhem para o rei da Babilônia, e tudo correrá bem para vocês.

[[v12-25-25]]

^<<v12-25-25,25>>^ Porém, no sétimo mês daquele ano, Ismael, filho de Netanias e neto de Elisama, que era da família do rei, foi até Mispa com dez homens, atacou Gedalias e o matou. Também matou os israelitas e babilônios que estavam ali com ele.

[[v12-25-26]]

^<<v12-25-26,26>>^ Então todos os israelitas, tanto os mais importantes como os mais humildes, junto com os oficiais do exército, saíram e foram para o Egito, pois estavam com medo dos babilônios.

[[v12-25-27]]

^<<v12-25-27,27>>^ No ano em que Evil-Merodaque se tornou rei da Babilônia, ele foi bondoso com o rei Joaquim, de Judá, e o libertou da prisão. Isso aconteceu trinta e sete anos, onze meses e vinte e sete dias depois que Joaquim havia sido levado como prisioneiro.

[[v12-25-28]]

^<<v12-25-28,28>>^ Evil-Merodaque tratou Joaquim com bondade e lhe deu uma posição mais alta do que a dos outros reis que eram prisioneiros com ele na Babilônia.

[[v12-25-29]]

^<<v12-25-29,29>>^ E assim deixaram que Joaquim tirasse as suas roupas de prisioneiro e vestisse as suas próprias roupas e comesse junto com o rei pelo resto da sua vida.

[[v12-25-30]]

^<<v12-25-30,30>>^ E todos os dias, enquanto viveu, recebeu do rei uma pensão para o seu sustento.

'''

xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[&#60; Capítulo Anterior] | <<v12-25-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[Próximo Capítulo &#62;]