include::./index.adoc[]

[[v12-18-0]]
=== 2 Reis, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-18-1]]

^<<v12-18-1,1>>^ No terceiro ano do reinado de Oseias, filho de Elá, como rei de Israel, Ezequias, filho de Acaz, se tornou rei de Judá.

[[v12-18-2]]

^<<v12-18-2,2>>^ Quando isso aconteceu, Ezequias tinha vinte e cinco anos de idade. Ele governou vinte e nove anos em Jerusalém. A sua mãe se chamava Abia e era filha de Zacarias.

[[v12-18-3]]

^<<v12-18-3,3>>^ Seguindo o exemplo do seu antepassado, o rei Davi, Ezequias fez aquilo que agrada a Deus, o Senhor .

[[v12-18-4]]

^<<v12-18-4,4>>^ Ele destruiu os lugares pagãos de adoração, quebrou as colunas do deus Baal  e derrubou os postes da deusa Aserá . Também fez em pedaços a cobra de bronze que Moisés havia feito e que era chamada de Neustã. Até aquela época o povo de Israel queimava incenso em honra dela.

[[v12-18-5]]

^<<v12-18-5,5>>^ Ezequias confiou no Senhor , o Deus de Israel; Judá nunca teve um rei como ele, nem antes nem depois daquela época.

[[v12-18-6]]

^<<v12-18-6,6>>^ Ezequias ficou ligado com o Senhor  e nunca desobedeceu a ele, mas guardou cuidadosamente todos os mandamentos que o Senhor  Deus tinha dado a Moisés.

[[v12-18-7]]

^<<v12-18-7,7>>^ Por isso, o Senhor  estava com ele, e ele teve sucesso em tudo o que fez. Ezequias se revoltou contra o rei da Assíria e não quis ser dominado por ele.

[[v12-18-8]]

^<<v12-18-8,8>>^ Venceu os filisteus, invadiu o seu território, desde o menor povoado até a maior cidade, e atacou a cidade de Gaza e a região ao seu redor.

[[v12-18-9]]

^<<v12-18-9,9>>^ No quarto ano do reinado de Ezequias, que era o sétimo ano do reinado de Oseias, filho de Elá, como rei de Israel, o rei Salmaneser, da Assíria, invadiu Israel, e o seu exército cercou a cidade de Samaria.

[[v12-18-10]]

^<<v12-18-10,10>>^ No terceiro ano do cerco, Samaria foi conquistada. Isso aconteceu no sexto ano do reinado de Ezequias, que era o nono ano do reinado de Oseias.

[[v12-18-11]]

^<<v12-18-11,11>>^ O rei da Assíria levou os israelitas como prisioneiros para a sua terra; mandou que alguns deles fossem morar na cidade de Hala, outros, perto do rio Habor, no distrito de Gozã, e ainda outros, nas cidades da Média.

[[v12-18-12]]

^<<v12-18-12,12>>^ Essas coisas aconteceram porque os israelitas não obedeceram ao Senhor , o Deus deles, mas quebraram a aliança  que o Senhor  havia feito com eles e desobedeceram a todas as leis  dadas por Moisés, servo  do Senhor . Eles não quiseram atender, nem obedecer.

[[v12-18-13]]

^<<v12-18-13,13>>^ No ano catorze do reinado de Ezequias, de Judá, Senaqueribe, rei da Assíria, atacou todas as cidades de Judá que eram cercadas de muralhas e as conquistou.

[[v12-18-14]]

^<<v12-18-14,14>>^ Ezequias mandou uma mensagem a Senaqueribe, que estava em Laquis. A mensagem foi esta: "Eu errei. Por favor, saia do meu país, que eu pagarei tudo o que o senhor exigir." O rei mandou uma resposta, dizendo que Ezequias devia lhe mandar dez mil quilos de prata e mil quilos de ouro.

[[v12-18-15]]

^<<v12-18-15,15>>^ Então Ezequias mandou para ele toda a prata do Templo e do tesouro do palácio.

[[v12-18-16]]

^<<v12-18-16,16>>^ Ele também arrancou o ouro das portas do Templo e o ouro com que ele mesmo havia revestido os batentes e mandou tudo para Senaqueribe.

[[v12-18-17]]

^<<v12-18-17,17>>^ Mas o rei da Assíria mandou de Laquis um grande exército para atacar Ezequias em Jerusalém. O exército era comandado pelos seus três mais altos oficiais. Quando chegaram a Jerusalém, eles ocuparam a estrada onde os tintureiros trabalham, perto do canal que traz água do açude de cima.

[[v12-18-18]]

^<<v12-18-18,18>>^ Então os oficiais mandaram chamar o rei Ezequias, e três autoridades de Judá saíram para falar com eles. Eram Eliaquim, filho de Hilquias, que era o encarregado do palácio, Sebna, o escrivão, e Joá, filho de Asafe, que era o conselheiro do rei.

[[v12-18-19]]

^<<v12-18-19,19>>^ Um dos oficiais assírios lhes disse: — Levem para Ezequias esta mensagem do grande rei, o rei da Assíria: "Em que você está baseando a sua confiança?

[[v12-18-20]]

^<<v12-18-20,20>>^ Você está pensando que as palavras podem tomar o lugar da experiência militar e da força? Quem você pensa que vai ajudá-lo na sua revolta contra o rei da Assíria?

[[v12-18-21]]

^<<v12-18-21,21>>^ Você está confiando na ajuda do Egito, mas isso é o mesmo que usar um caniço como bengala, isto é, ele vai quebrar e furar a sua mão. Assim é Faraó, rei do Egito, para aqueles que confiam nele.

[[v12-18-22]]

^<<v12-18-22,22>>^ Ou, por acaso, você vai me dizer que confia no Senhor , seu Deus? E não foram os santuários e os altares do Senhor  que Ezequias destruiu quando mandou que o povo de Judá e de Jerusalém adorasse somente no altar de Jerusalém?

[[v12-18-23]]

^<<v12-18-23,23>>^ Eu vou fazer um trato com você em nome do rei da Assíria. Eu lhe darei dois mil cavalos se você puder arranjar homens suficientes para montá-los.

[[v12-18-24]]

^<<v12-18-24,24>>^ Você não poderia vencer nem o oficial assírio menos graduado e, no entanto, espera que os egípcios lhe mandem carros de guerra e cavalaria!

[[v12-18-25]]

^<<v12-18-25,25>>^ Você pensa que eu ataquei e destruí o seu país sem a ajuda de Deus, o Senhor ? Foi ele mesmo quem me mandou atacá-lo e destruí-lo!"

[[v12-18-26]]

^<<v12-18-26,26>>^ Então Eliaquim, Sebna e Joá disseram ao oficial: — Fale em aramaico , pois nós entendemos. Não fale em hebraico , pois todas as pessoas que estão nas muralhas estão escutando.

[[v12-18-27]]

^<<v12-18-27,27>>^ Ele respondeu: — Vocês pensam que o rei me mandou dizer todas essas coisas somente para vocês e para o seu rei? Não! Não foi só isso. Eu estou falando também com as pessoas que estão sentadas nas muralhas e que terão de comer as suas próprias fezes e beber a sua própria urina; e vocês também vão fazer isso.

[[v12-18-28]]

^<<v12-18-28,28>>^ Então o oficial ficou de pé e gritou em hebraico: — Escutem o que o grande rei, o rei da Assíria, está dizendo a vocês!

[[v12-18-29]]

^<<v12-18-29,29>>^ Ele mandou avisar que não deixem que Ezequias os engane, pois ele não poderá salvá-los.

[[v12-18-30]]

^<<v12-18-30,30>>^ E não deixem que ele os convença a confiar em Deus, o Senhor . Não pensem que o Senhor  os salvará e não deixará que o nosso exército assírio conquiste a cidade de vocês.

[[v12-18-31]]

^<<v12-18-31,31>>^ Não deem atenção a Ezequias. O rei da Assíria manda que vocês saiam da cidade e se entreguem. Vocês terão licença para comer uvas das suas próprias parreiras  e figos das suas figueiras e para beber água dos seus próprios poços,

[[v12-18-32]]

^<<v12-18-32,32>>^ até que o rei os leve para morar num país parecido com o de vocês, onde há plantações de uvas para fazer vinho e onde há trigo para fazer pão. É uma terra de oliveiras, azeite e mel. Se fizerem o que ele está mandando, vocês não morrerão, mas viverão. Não deixem que Ezequias os engane, fazendo vocês pensarem que o Senhor  vai salvá-los.

[[v12-18-33]]

^<<v12-18-33,33>>^ Será que os deuses das outras nações as salvaram do rei da Assíria?

[[v12-18-34]]

^<<v12-18-34,34>>^ Onde estão agora os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim, de Hena e de Iva? Será que os deuses de Samaria salvaram Samaria do meu poder?

[[v12-18-35]]

^<<v12-18-35,35>>^ Quando foi que os deuses de todos esses países os salvaram do nosso rei? O que é, então, que faz vocês pensarem que o Senhor  pode salvar Jerusalém do poder dele?

[[v12-18-36]]

^<<v12-18-36,36>>^ Mas o povo ficou calado, de acordo com a ordem do rei Ezequias; eles não disseram nem uma só palavra.

[[v12-18-37]]

^<<v12-18-37,37>>^ Então Eliaquim, Sebna e Joá rasgaram as suas roupas em sinal de tristeza e foram contar ao rei aquilo que o oficial assírio tinha dito.

'''

xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[Próximo Capítulo &#62;]