include::./index.adoc[]

[[v12-19-0]]
=== 2 Reis, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-19-1]]

^<<v12-19-1,1>>^ Assim que o rei Ezequias ouviu o que eles contaram, rasgou as suas roupas em sinal de tristeza, vestiu uma roupa feita de pano grosseiro e foi para o Templo do Senhor .

[[v12-19-2]]

^<<v12-19-2,2>>^ Ele mandou que Eliaquim, o encarregado do palácio, Sebna, o escrivão, e os sacerdotes mais velhos fossem falar com o profeta  Isaías, filho de Amoz. Eles também estavam vestindo roupas de pano grosseiro.

[[v12-19-3]]

^<<v12-19-3,3>>^ A mensagem que o rei mandou entregar a Isaías foi esta: "Hoje é um dia de sofrimento; nós estamos sendo castigados e estamos envergonhados. Somos como uma mulher que está para dar à luz, mas não tem forças para isso.

[[v12-19-4]]

^<<v12-19-4,4>>^ O rei da Assíria nos mandou o chefe do seu exército para insultar o Deus vivo. Que o Senhor , nosso Deus, escute esses insultos e castigue quem os disse! Portanto, ore a Deus pelas pessoas do nosso povo que ainda estão vivas."

[[v12-19-5]]

^<<v12-19-5,5>>^ Os funcionários do rei Ezequias levaram a mensagem,

[[v12-19-6]]

^<<v12-19-6,6>>^ e Isaías mandou esta resposta: "O Senhor  Deus diz que o senhor não deve deixar que os assírios o assustem, dizendo que Deus não pode salvá-lo.

[[v12-19-7]]

^<<v12-19-7,7>>^ Deus vai fazer o rei assírio ouvir uma notícia que o fará voltar para a terra dele, e Deus vai fazer com que ele seja morto ali."

[[v12-19-8]]

^<<v12-19-8,8>>^ O oficial assírio soube que o rei da Assíria havia saído de Laquis e que estava lutando contra a cidade de Libna. Então foi até lá para falar com ele.

[[v12-19-9]]

^<<v12-19-9,9>>^ Os assírios souberam que o exército dos egípcios, comandado pelo rei Tiraca, da Etiópia, vinha vindo para atacá-los. Quando o rei da Assíria soube disso, mandou uma carta para o rei Ezequias, de Judá.

[[v12-19-10]]

^<<v12-19-10,10>>^ A carta dizia assim: "O seu deus, em quem você confia, lhe disse que Jerusalém não vai cair nas minhas mãos; mas não deixe que ele o engane.

[[v12-19-11]]

^<<v12-19-11,11>>^ Você já ouviu falar daquilo que um rei assírio faz com qualquer país que ele resolve destruir? Por acaso, você pensa que poderá escapar?

[[v12-19-12]]

^<<v12-19-12,12>>^ Os meus antepassados destruíram as cidades de Gozã, Harã e Rezefe e mataram o povo de Éden, que morava em Telassar, e nenhum dos seus deuses os pôde salvar.

[[v12-19-13]]

^<<v12-19-13,13>>^ Onde estão os reis das cidades de Hamate, Arpade, Sefarvaim, Hena e Iva?"

[[v12-19-14]]

^<<v12-19-14,14>>^ O rei Ezequias recebeu a carta das mãos dos mensageiros e a leu. Então foi até o Templo, pôs a carta ali, na presença de Deus, o Senhor ,

[[v12-19-15]]

^<<v12-19-15,15>>^ e orou assim: — Ó Senhor , Deus de Israel, que estás sentado no teu trono que fica acima dos querubins ! Só tu és Deus e governas todos os reinos do mundo. Tu fizeste os céus e a terra.

[[v12-19-16]]

^<<v12-19-16,16>>^ Ó Senhor , olha para o que está acontecendo com a gente. Escuta todas as coisas que Senaqueribe está dizendo a fim de insultar a ti, o Deus vivo.

[[v12-19-17]]

^<<v12-19-17,17>>^ Todos nós sabemos, ó Senhor , que os reis da Assíria destruíram muitas nações, arrasaram as suas terras

[[v12-19-18]]

^<<v12-19-18,18>>^ e queimaram os seus deuses, que não eram deuses de verdade e sim imagens de madeira e de pedra feitas por mãos humanas.

[[v12-19-19]]

^<<v12-19-19,19>>^ Agora, ó Senhor , nosso Deus, salva-nos dos assírios, para que todas as nações do mundo fiquem sabendo que só tu, ó Senhor , és Deus.

[[v12-19-20]]

^<<v12-19-20,20>>^ Então Isaías mandou uma mensagem para o rei Ezequias. Nela, ele dizia que, em resposta à oração do rei,

[[v12-19-21]]

^<<v12-19-21,21>>^ o Senhor , o Deus de Israel, tinha dito o seguinte: "A cidade de Jerusalém ri e caçoa de você, Senaqueribe.

[[v12-19-22]]

^<<v12-19-22,22>>^ Contra quem você pensa que falou? Para quem você olhou com orgulho? A quem você pensa que ofendeu e insultou? Você fez tudo isso contra mim, o Santo Deus de Israel.

[[v12-19-23]]

^<<v12-19-23,23>>^ Você me mandou os seus mensageiros para se gabarem de que com os seus muitos carros de guerra você conquistou as mais altas montanhas do Líbano. Você se gabou de ter cortado os mais altos cedros e os melhores ciprestes e de ter chegado até os lugares mais distantes das lindas florestas.

[[v12-19-24]]

^<<v12-19-24,24>>^ Você se gabou de ter cavado poços em terras estrangeiras e de ter bebido da água deles. Gabou-se também de que os pés dos seus soldados fizeram secar o rio Nilo.

[[v12-19-25]]

^<<v12-19-25,25>>^ "Por acaso, você não sabe que fui eu que planejei tudo isso há muito tempo e agora fiz tudo acontecer? Eu dei a você o poder de fazer cidades cercadas de muralhas virarem montões de entulho.

[[v12-19-26]]

^<<v12-19-26,26>>^ Por isso, os seus moradores ficaram fracos e andavam cheios de medo e de vergonha. Eles ficaram como o capim do campo e a erva verde e como a erva que cresce nos telhados, quando o vento quente do leste sopra e os faz secar.

[[v12-19-27]]

^<<v12-19-27,27>>^ "Mas eu o conheço muito bem; sei o que você faz e aonde vai. Sei que você me odeia.

[[v12-19-28]]

^<<v12-19-28,28>>^ Eu soube do seu ódio e do seu orgulho, e agora vou pôr uma argola no seu nariz e um freio na sua boca, e farei você voltar pelo mesmo caminho por onde veio."

[[v12-19-29]]

^<<v12-19-29,29>>^ Depois Isaías disse ao rei Ezequias: — Este é o sinal daquilo que vai acontecer: neste ano e no ano que vem, vocês terão para comer somente aquilo que nascer por si mesmo, sem ser plantado. Mas no ano seguinte vocês poderão semear e colher cereais, plantar parreiras  e comer as uvas.

[[v12-19-30]]

^<<v12-19-30,30>>^ As pessoas de Judá que não tiverem morrido vão florescer como plantas que firmam as suas raízes na terra e dão frutas.

[[v12-19-31]]

^<<v12-19-31,31>>^ Pois ficará gente em Jerusalém e no monte Sião  porque o Senhor  Deus resolveu fazer com que isso aconteça.

[[v12-19-32]]

^<<v12-19-32,32>>^ Isaías continuou: — Portanto, o Senhor  Deus diz o seguinte a respeito do rei da Assíria: "Ele não entrará nesta cidade e não atirará uma só flecha contra ela. Nenhum soldado com escudo  chegará perto da cidade, e não serão construídas rampas de ataque ao redor dela.

[[v12-19-33]]

^<<v12-19-33,33>>^ O rei da Assíria vai voltar pelo mesmo caminho por onde veio, sem ter entrado nesta cidade.

[[v12-19-34]]

^<<v12-19-34,34>>^ Eu defenderei e protegerei esta cidade por causa da minha honra e por causa da promessa que fiz ao meu servo  Davi. Eu, o Senhor , falei."

[[v12-19-35]]

^<<v12-19-35,35>>^ Naquela noite o Anjo do Senhor  foi até o acampamento dos assírios e matou cento e oitenta e cinco mil soldados. De manhã, os que sobraram viram os corpos dos mortos.

[[v12-19-36]]

^<<v12-19-36,36>>^ Então Senaqueribe, rei da Assíria, se retirou, voltou para Nínive e ficou lá.

[[v12-19-37]]

^<<v12-19-37,37>>^ Certo dia, quando ele estava adorando no templo do seu deus Nisroque, os seus filhos Adrameleque e Sarezer o mataram à espada e fugiram para a terra de Ararate. Outro filho seu, chamado Esar-Hadom, ficou no lugar dele como rei.

'''

xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[&#60; Capítulo Anterior] | <<v12-19-0,Topo>> | xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[Próximo Capítulo &#62;]