include::./index.adoc[]

[[v12-15-0]]
=== 2 Reis, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-15-1]]

^<<v12-15-1,1>>^ No ano vinte e sete do reinado de Jeroboão II de Israel, Uzias , filho de Amazias, se tornou rei de Judá

[[v12-15-2]]

^<<v12-15-2,2>>^ com a idade de dezesseis anos. Ele governou cinquenta e dois anos em Jerusalém. A sua mãe se chamava Jecolias e era da cidade de Jerusalém.

[[v12-15-3]]

^<<v12-15-3,3>>^ Seguindo o exemplo do seu pai, Uzias fez aquilo que agrada a Deus, o Senhor .

[[v12-15-4]]

^<<v12-15-4,4>>^ Mas os lugares pagãos de adoração não foram destruídos, e o povo continuou a oferecer sacrifícios  e a queimar incenso naqueles lugares.

[[v12-15-5]]

^<<v12-15-5,5>>^ O Senhor  Deus feriu o rei Uzias, e ele ficou sofrendo de uma doença contagiosa da pele até o fim da sua vida. Ele morava numa casa separada, e era o seu filho Jotão quem cuidava das coisas do governo e reinava no país.

[[v12-15-6]]

^<<v12-15-6,6>>^ Todas as outras coisas que Uzias fez estão escritas na História dos Reis de Judá .

[[v12-15-7]]

^<<v12-15-7,7>>^ Uzias morreu e foi sepultado nos túmulos dos reis, na Cidade de Davi , e o seu filho Jotão ficou no lugar dele como rei.

[[v12-15-8]]

^<<v12-15-8,8>>^ No ano trinta e oito do reinado de Uzias, de Judá, Zacarias, filho de Jeroboão II, se tornou rei de Israel e governou seis meses em Samaria.

[[v12-15-9]]

^<<v12-15-9,9>>^ Como aqueles que haviam sido reis antes dele, Zacarias fez coisas erradas, que não agradam a Deus, o Senhor . Ele não abandonou aqueles mesmos pecados que o rei Jeroboão, filho de Nebate, havia feito o povo de Israel cometer no passado.

[[v12-15-10]]

^<<v12-15-10,10>>^ Salum, filho de Jabes, fez uma revolta contra o rei Zacarias, matou-o na cidade de Ibleão e ficou no lugar dele como rei.

[[v12-15-11]]

^<<v12-15-11,11>>^ Todas as outras coisas que Zacarias fez estão escritas na História dos Reis de Israel .

[[v12-15-12]]

^<<v12-15-12,12>>^ E assim foi cumprida a promessa que o Senhor  havia feito ao rei Jeú: "Os seus descendentes serão reis de Israel até a quarta geração  ."

[[v12-15-13]]

^<<v12-15-13,13>>^ No ano trinta e nove do reinado de Uzias, de Judá, Salum, filho de Jabes, se tornou rei de Israel e governou um mês em Samaria.

[[v12-15-14]]

^<<v12-15-14,14>>^ Menaém, filho de Gadi, foi da cidade de Tirza até Samaria, matou Salum e ficou no lugar dele como rei.

[[v12-15-15]]

^<<v12-15-15,15>>^ Todas as outras coisas que Salum fez e também a história da sua revolta, tudo está escrito na História dos Reis de Israel .

[[v12-15-16]]

^<<v12-15-16,16>>^ Menaém destruiu a cidade de Tapua, matou os seus moradores e arrasou a região vizinha até Tirza; ele fez isso porque a cidade não se entregou a ele. Menaém mandou rasgar a barriga de todas as mulheres grávidas.

[[v12-15-17]]

^<<v12-15-17,17>>^ No ano trinta e nove do reinado de Uzias, de Judá, Menaém, filho de Gadi, se tornou rei de Israel e governou dez anos em Samaria.

[[v12-15-18]]

^<<v12-15-18,18>>^ Ele fez coisas erradas, que não agradam a Deus, o Senhor . Nunca abandonou aqueles mesmos pecados que Jeroboão, filho de Nebate, havia feito o povo de Israel cometer no passado.

[[v12-15-19]]

^<<v12-15-19,19>>^ Tiglate-Pileser , rei da Assíria, invadiu a terra de Israel, e Menaém lhe entregou trinta e quatro toneladas de prata para que ele o ajudasse a se firmar no poder.

[[v12-15-20]]

^<<v12-15-20,20>>^ Para conseguir esse dinheiro, Menaém obrigou os homens ricos de Israel a contribuírem com cinquenta barras de prata cada um. E assim Tiglate-Pileser voltou para a sua terra.

[[v12-15-21]]

^<<v12-15-21,21>>^ Todas as outras coisas que Menaém fez estão escritas na História dos Reis de Israel .

[[v12-15-22]]

^<<v12-15-22,22>>^ Ele morreu e foi sepultado, e o seu filho Pecaías ficou no lugar dele como rei.

[[v12-15-23]]

^<<v12-15-23,23>>^ No ano cinquenta do reinado de Uzias, de Judá, Pecaías, filho de Menaém, se tornou rei de Israel e governou dois anos em Samaria.

[[v12-15-24]]

^<<v12-15-24,24>>^ Ele fez coisas erradas, que não agradam a Deus, o Senhor , e nunca abandonou aqueles mesmos pecados que Jeroboão, filho de Nebate, havia feito o povo de Israel cometer no passado.

[[v12-15-25]]

^<<v12-15-25,25>>^ Um oficial do exército de Pecaías, chamado Peca, filho de Remalias, junto com cinquenta homens de Gileade, fez uma revolta, matou Pecaías na fortaleza do palácio de Samaria e ficou no lugar dele como rei.

[[v12-15-26]]

^<<v12-15-26,26>>^ Todas as outras coisas que Pecaías fez estão escritas na História dos Reis de Israel .

[[v12-15-27]]

^<<v12-15-27,27>>^ No ano cinquenta e dois do reinado de Uzias, de Judá, Peca, filho de Remalias, se tornou rei de Israel e governou vinte anos em Samaria.

[[v12-15-28]]

^<<v12-15-28,28>>^ Ele fez coisas erradas, que não agradam a Deus, o Senhor , e nunca abandonou aqueles mesmos pecados que Jeroboão, filho de Nebate, havia feito o povo de Israel cometer no passado.

[[v12-15-29]]

^<<v12-15-29,29>>^ Foi durante o reinado de Peca que Tiglate-Pileser, rei da Assíria, conquistou as cidades de Ijom, Abel-Bete-Maacá, Janoa, Quedes, Hazor e as regiões de Gileade, Galileia e Naftali e levou os seus moradores como prisioneiros para a Assíria.

[[v12-15-30]]

^<<v12-15-30,30>>^ No ano vinte do reinado de Jotão, filho de Uzias, como rei de Judá, Oseias, filho de Elá, fez uma revolta contra o rei Peca, matou-o e ficou no lugar dele como rei.

[[v12-15-31]]

^<<v12-15-31,31>>^ Todas as outras coisas que Peca fez estão escritas na História dos Reis de Israel .

[[v12-15-32]]

^<<v12-15-32,32>>^ No segundo ano do reinado de Peca, filho de Remalias, como rei de Israel, Jotão, filho de Uzias, se tornou rei de Judá

[[v12-15-33]]

^<<v12-15-33,33>>^ com a idade de vinte e cinco anos. Ele governou dezesseis anos em Jerusalém. A sua mãe se chamava Jerusa e era filha de Zadoque.

[[v12-15-34]]

^<<v12-15-34,34>>^ Seguindo o exemplo de Uzias, o seu pai, Jotão fez aquilo que agrada a Deus, o Senhor .

[[v12-15-35]]

^<<v12-15-35,35>>^ Mas os lugares pagãos de adoração não foram destruídos, e o povo continuou a oferecer sacrifícios  e a queimar incenso naqueles lugares. Foi Jotão quem construiu o Portão Norte do Templo.

[[v12-15-36]]

^<<v12-15-36,36>>^ Todas as outras coisas que Jotão fez estão escritas na História dos Reis de Judá .

[[v12-15-37]]

^<<v12-15-37,37>>^ Foi durante o reinado dele que pela primeira vez o Senhor  mandou Rezim, rei da Síria, e Peca, rei de Israel, atacar Judá.

[[v12-15-38]]

^<<v12-15-38,38>>^ Jotão morreu e foi sepultado nos túmulos dos reis, na Cidade de Davi , e o seu filho Acaz ficou no lugar dele como rei.

'''

xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[&#60; Capítulo Anterior] | <<v12-15-0,Topo>> | xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[Próximo Capítulo &#62;]