include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-8-1]]

^<<v12-8-1,1>>^ Eliseu tinha dito à mulher que morava em Suném, a mãe do menino que ele tinha ressuscitado, que o Senhor  Deus tinha avisado que ia haver uma grande falta de alimentos. Disse também que a fome ia durar sete anos naquela terra e, por isso, ela devia sair de lá com a sua família e ir morar em outro lugar.

[[v12-8-2]]

^<<v12-8-2,2>>^ Ela havia seguido o conselho do profeta  e tinha ido com a sua família morar na terra dos filisteus, onde ficou sete anos.

[[v12-8-3]]

^<<v12-8-3,3>>^ Quando passaram os sete anos, ela voltou para Israel e foi falar com o rei a fim de pedir que devolvessem a sua casa e as suas terras.

[[v12-8-4]]

^<<v12-8-4,4>>^ O rei estava falando com Geazi, o empregado de Eliseu, pois queria saber dos milagres que Eliseu havia feito.

[[v12-8-5]]

^<<v12-8-5,5>>^ Geazi estava contando ao rei como Eliseu havia feito um morto viver de novo. Nesse momento a mulher chegou para fazer o seu pedido ao rei. Então Geazi disse: — Ó rei, aqui está a mulher, e aqui está o filho dela que Eliseu ressuscitou.

[[v12-8-6]]

^<<v12-8-6,6>>^ O rei fez perguntas à mulher, e ela confirmou a história de Geazi. Então o rei chamou um oficial e lhe disse que devolvesse à mulher tudo o que era dela e também o valor de todas as colheitas que as suas terras haviam produzido durante os sete anos em que ela havia estado fora.

[[v12-8-7]]

^<<v12-8-7,7>>^ Eliseu foi até a cidade de Damasco numa época em que o rei Ben-Hadade, da Síria, estava doente. Quando o rei soube que Eliseu estava lá,

[[v12-8-8]]

^<<v12-8-8,8>>^ disse a Hazael, um dos seus oficiais: — Leve um presente para o profeta  e peça a ele que consulte a Deus, o Senhor , para saber se vou ficar bom.

[[v12-8-9]]

^<<v12-8-9,9>>^ Então Hazael carregou quarenta camelos com todos os tipos dos mais finos produtos de Damasco e foi falar com Eliseu. Quando se encontrou com ele, disse: — O rei Ben-Hadade, que é como se fosse seu filho, mandou perguntar ao senhor se ele vai ficar bom da sua doença.

[[v12-8-10]]

^<<v12-8-10,10>>^ Eliseu disse: — O Senhor  Deus me disse que o rei vai morrer; mas diga a ele que ele vai ficar bom.

[[v12-8-11]]

^<<v12-8-11,11>>^ E ficou olhando firmemente para Hazael durante tanto tempo, que ele ficou sem jeito. De repente, Eliseu começou a chorar,

[[v12-8-12]]

^<<v12-8-12,12>>^ e Hazael perguntou: — Por que é que o senhor está chorando? Eliseu respondeu: — Porque sei das coisas terríveis que você vai fazer contra o povo de Israel. E continuou: — Você vai pôr fogo nas fortalezas de Israel, vai matar os moços, esmagar as crianças e rasgar a barriga das mulheres grávidas.

[[v12-8-13]]

^<<v12-8-13,13>>^ — Como poderia eu chegar a ser tão poderoso? — perguntou Hazael. — Eu não sou ninguém! — O Senhor  Deus me mostrou que você vai ser o rei da Síria! — respondeu Eliseu.

[[v12-8-14]]

^<<v12-8-14,14>>^ Hazael voltou até o lugar onde estava o rei Ben-Hadade, e este lhe perguntou: — O que foi que Eliseu disse? — Ele disse que o senhor vai ficar bom, com certeza! — respondeu Hazael.

[[v12-8-15]]

^<<v12-8-15,15>>^ Mas no dia seguinte Hazael pegou um cobertor, molhou-o bem e com ele sufocou o rei. E Hazael ficou no lugar de Ben-Hadade como rei da Síria.

[[v12-8-16]]

^<<v12-8-16,16>>^ No quinto ano do reinado de Jorão, filho de Acabe, como rei de Israel, Jeorão, filho de Josafá, se tornou rei de Judá.

[[v12-8-17]]

^<<v12-8-17,17>>^ Quando isso aconteceu, Jeorão tinha trinta e dois anos de idade. Ele governou oito anos em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ A mulher dele era filha do rei Acabe, de Israel, e Jeorão seguiu os maus caminhos de Acabe e dos outros reis de Israel, como a família de Acabe havia feito. Jeorão pecou contra Deus, o Senhor ,

[[v12-8-19]]

^<<v12-8-19,19>>^ mas o Senhor  não quis destruir Judá, pois havia feito uma aliança  com o seu servo  Davi, prometendo que os seus descendentes sempre seriam reis.

[[v12-8-20]]

^<<v12-8-20,20>>^ Durante o reinado de Jeorão, o país de Edom se revoltou contra Judá e se tornou independente.

[[v12-8-21]]

^<<v12-8-21,21>>^ Por isso, Jeorão saiu com todos os seus carros de guerra e foi até Zair; ali eles foram cercados pelos edomitas. Para escapar, Jeorão e os comandantes dos seus carros de guerra atacaram os edomitas durante a noite, e os soldados de Jeorão fugiram para as suas casas.

[[v12-8-22]]

^<<v12-8-22,22>>^ Desse tempo em diante, Edom ficou independente de Judá. Nessa mesma época a cidade de Libna também se revoltou.

[[v12-8-23]]

^<<v12-8-23,23>>^ Todas as outras coisas que Jeorão fez estão escritas na História dos Reis de Judá .

[[v12-8-24]]

^<<v12-8-24,24>>^ Jeorão morreu e foi sepultado nos túmulos dos reis, na Cidade de Davi , e o seu filho Acazias ficou no lugar dele como rei.

[[v12-8-25]]

^<<v12-8-25,25>>^ No ano doze do reinado de Jorão, filho de Acabe, como rei de Israel, Acazias, filho de Jeorão, se tornou rei de Judá.

[[v12-8-26]]

^<<v12-8-26,26>>^ Quando isso aconteceu, Acazias tinha vinte e dois anos de idade. Ele governou um ano em Jerusalém. A mãe dele se chamava Atalia e era filha do rei Onri, de Israel.

[[v12-8-27]]

^<<v12-8-27,27>>^ Por ser aparentado com o rei Acabe pelo casamento, Acazias seguiu o exemplo da família de Acabe e pecou contra Deus, o Senhor .

[[v12-8-28]]

^<<v12-8-28,28>>^ O rei Acazias se juntou com o rei Jorão, de Israel, a fim de guerrear contra o rei Hazael, da Síria. Os exércitos deles lutaram em Ramote-Gileade, e Jorão foi ferido na batalha.

[[v12-8-29]]

^<<v12-8-29,29>>^ Então ele voltou para a cidade de Jezreel a fim de tratar dos ferimentos, e Acazias foi até lá para visitá-lo.

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]