include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-9-1]]

^<<v12-9-1,1>>^ Enquanto isso, o profeta  Eliseu chamou um dos jovens profetas e disse: — Apronte-se e vá até Ramote-Gileade. Leve este jarro de azeite

[[v12-9-2]]

^<<v12-9-2,2>>^ e, quando chegar lá, procure Jeú, filho de Josafá e neto de Ninsi. Leve-o para outra sala, longe dos seus companheiros.

[[v12-9-3]]

^<<v12-9-3,3>>^ Aí derrame azeite na cabeça dele e diga: "O Senhor  Deus anuncia que o está ungindo  para ser rei de Israel." Depois saia de lá o mais depressa que puder.

[[v12-9-4]]

^<<v12-9-4,4>>^ Então o jovem profeta foi até Ramote-Gileade

[[v12-9-5]]

^<<v12-9-5,5>>^ e lá encontrou reunidos os oficiais do exército. Ele disse: — Eu trouxe uma mensagem para o senhor. Jeú perguntou: — Com qual de nós você está falando? — Com o senhor mesmo! — respondeu ele.

[[v12-9-6]]

^<<v12-9-6,6>>^ Então os dois foram para uma sala, e o jovem profeta derramou azeite na cabeça de Jeú e disse: — O Senhor , o Deus de Israel, anuncia isto: "Eu estou ungindo você para ser o rei do meu povo de Israel.

[[v12-9-7]]

^<<v12-9-7,7>>^ Você deve matar o seu chefe, o rei Jorão, filho de Acabe, para que assim eu castigue Jezabel por haver assassinado os meus profetas e os meus outros servos .

[[v12-9-8]]

^<<v12-9-8,8>>^ Toda a família e todos os descendentes de Acabe devem morrer. Eu vou acabar com todos os homens da família dele, tanto os jovens como os velhos.

[[v12-9-9]]

^<<v12-9-9,9>>^ Vou tratar a família dele como tratei as famílias do rei Jeroboão, filho de Nebate, e do rei Baasa, filho de Aías.

[[v12-9-10]]

^<<v12-9-10,10>>^ Jezabel não será sepultada; o seu corpo será comido pelos cachorros perto da cidade de Jezreel." Depois de dizer isso, o jovem profeta saiu da sala e fugiu.

[[v12-9-11]]

^<<v12-9-11,11>>^ Jeú voltou para o lugar onde estavam os seus companheiros, e eles perguntaram: — Tudo bem? O que aquele louco queria com você? — Vocês sabem muito bem o que ele queria! — respondeu Jeú.

[[v12-9-12]]

^<<v12-9-12,12>>^ — Não sabemos, não! — disseram eles. — Conte o que ele disse. Jeú contou: — Ele me disse que o Senhor  Deus anuncia isto: "Eu estou ungindo você, Jeú, para ser o rei de Israel."

[[v12-9-13]]

^<<v12-9-13,13>>^ No mesmo instante, eles estenderam as suas capas  sobre os degraus para Jeú passar, tocaram a corneta e gritaram: — Jeú é o rei!

[[v12-9-14]]

^<<v12-9-14,14>>^ Então Jeú fez uma revolta contra o rei Jorão. Jorão estava em Jezreel tratando dos ferimentos que havia recebido em Ramote-Gileade, na batalha contra o rei Hazael, da Síria. Por isso, Jeú disse aos seus colegas oficiais: — Se vocês estão do meu lado, não deixem que ninguém saia escondido de Ramote-Gileade para ir avisar os moradores de Jezreel.

[[v12-9-15]]

^<<v12-9-15,15>>^ Então Jeú fez uma revolta contra o rei Jorão. Jorão estava em Jezreel tratando dos ferimentos que havia recebido em Ramote-Gileade, na batalha contra o rei Hazael, da Síria. Por isso, Jeú disse aos seus colegas oficiais:

[[v12-9-16]]

^<<v12-9-16,16>>^ Então subiu no seu carro de guerra e saiu para Jezreel. Jorão ainda não tinha sarado, e o rei Acazias, de Judá, se encontrava ali fazendo-lhe uma visita.

[[v12-9-17]]

^<<v12-9-17,17>>^ Um guarda que estava na torre de vigia de Jezreel viu Jeú e os seus soldados chegando e gritou: — Vejo alguns homens chegando a cavalo! Aí Jorão disse: — Mande um homem a cavalo para descobrir se são amigos ou inimigos.

[[v12-9-18]]

^<<v12-9-18,18>>^ O mensageiro foi encontrar-se com Jeú e disse: — O rei quer saber se o senhor vem como amigo. — Isso não é da sua conta! — respondeu Jeú. E mandou: — Passe para trás de mim. O guarda que estava na torre de vigia contou que o mensageiro havia se encontrado com o grupo, porém não estava voltando.

[[v12-9-19]]

^<<v12-9-19,19>>^ Outro mensageiro foi mandado e fez a mesma pergunta a Jeú. E novamente ele respondeu: "Isso não é da sua conta! Passe para trás de mim."

[[v12-9-20]]

^<<v12-9-20,20>>^ Novamente o guarda contou que o mensageiro havia chegado até o grupo, porém não estava voltando. E disse também: — O chefe do grupo está guiando o seu carro de guerra como um louco, exatamente como Jeú faz!

[[v12-9-21]]

^<<v12-9-21,21>>^ — Aprontem o meu carro de guerra! — ordenou o rei Jorão. O carro foi preparado, e então ele e o rei Acazias saíram, cada um no seu carro, para ir ao encontro de Jeú. Eles se encontraram com ele no campo que havia sido de Nabote. Aí Jorão perguntou:

[[v12-9-22]]

^<<v12-9-22,22>>^ — Você veio como amigo? Jeú respondeu: — Como podemos ser amigos quando ainda continuam as feitiçarias e a adoração de ídolos que Jezabel, a sua mãe, começou?

[[v12-9-23]]

^<<v12-9-23,23>>^ Então Jorão virou o seu carro e fugiu, gritando para Acazias: — É uma traição, Acazias!

[[v12-9-24]]

^<<v12-9-24,24>>^ Mas Jeú puxou a corda do seu arco com toda a força e atirou uma flecha, que feriu Jorão nas costas. A flecha atravessou o coração, e ele caiu morto no seu carro de guerra.

[[v12-9-25]]

^<<v12-9-25,25>>^ Aí Jeú disse a Bidcar, o seu ajudante: — Pegue o corpo dele e jogue no campo que era de Nabote. Lembre que, quando nós dois estávamos juntos andando a cavalo atrás de Acabe, pai de Jorão, o Senhor  Deus disse estas palavras contra Acabe:

[[v12-9-26]]

^<<v12-9-26,26>>^ "Ontem eu vi o assassinato de Nabote e dos seus filhos. E prometo que castigarei você aqui, neste mesmo campo." E Jeú ordenou ao seu ajudante: — Pegue o corpo de Jorão e jogue no campo que era de Nabote, para que assim seja cumprida a promessa de Deus, o Senhor .

[[v12-9-27]]

^<<v12-9-27,27>>^ O rei Acazias, de Judá, viu o que tinha acontecido e fugiu no seu carro na direção da cidade de Bete-Hagã. Mas Jeú o perseguiu e disse aos seus soldados: — Matem Acazias também! E eles o feriram quando ele ia no seu carro pela estrada que sobe para Gur, perto da cidade de Ibleão. Mas Acazias conseguiu fugir até a cidade de Megido, onde morreu.

[[v12-9-28]]

^<<v12-9-28,28>>^ Os seus oficiais levaram o corpo de volta para Jerusalém e o sepultaram nos túmulos dos reis, na Cidade de Davi .

[[v12-9-29]]

^<<v12-9-29,29>>^ Acazias havia começado a reinar em Judá no ano onze do reinado de Jorão, filho de Acabe, em Israel.

[[v12-9-30]]

^<<v12-9-30,30>>^ Jeú chegou a Jezreel, e Jezabel ficou sabendo disso. Então pintou os olhos, penteou os cabelos e ficou numa janela do palácio, olhando para a rua.

[[v12-9-31]]

^<<v12-9-31,31>>^ Quando Jeú entrou pelo portão do palácio, ela gritou: — Olá, Zinri , assassino do seu senhor!

[[v12-9-32]]

^<<v12-9-32,32>>^ Jeú olhou para cima e gritou: — Quem está do meu lado? Dois ou três oficiais do palácio olharam para ele de uma janela,

[[v12-9-33]]

^<<v12-9-33,33>>^ e Jeú lhes disse: — Joguem essa mulher daí! Eles a jogaram, e o sangue dela respingou a parede e os cavalos. Jeú passou por cima dela com os cavalos e o carro

[[v12-9-34]]

^<<v12-9-34,34>>^ e entrou no palácio. E, depois que comeu e bebeu, disse: — Peguem aquela maldita e a sepultem. Afinal de contas, ela é filha de um rei.

[[v12-9-35]]

^<<v12-9-35,35>>^ Mas os homens que saíram para sepultá-la só encontraram a caveira e os ossos das mãos e pés.

[[v12-9-36]]

^<<v12-9-36,36>>^ Então eles voltaram, contaram a Jeú, e este disse: — Foi isto o que o Senhor  Deus disse que ia acontecer quando falou por meio do seu servo  Elias, da cidade de Tisbé: "Os cachorros comerão o corpo de Jezabel perto da cidade de Jezreel.

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]