include::./index.adoc[]

[[v12-10-0]]
=== 2 Reis, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-10-1]]

^<<v12-10-1,1>>^ Na cidade de Samaria moravam setenta filhos do rei Acabe. Jeú escreveu cartas e as mandou às autoridades da cidade, aos líderes e às pessoas que tomavam conta dos filhos de Acabe. A carta dizia assim:

[[v12-10-2]]

^<<v12-10-2,2>>^ "Vocês estão encarregados de tomar conta dos filhos do rei e têm carros de guerra, cavalos, armas e cidades cercadas de muralhas. Portanto, assim que receberem esta carta,

[[v12-10-3]]

^<<v12-10-3,3>>^ escolham o melhor e o mais capaz dos filhos do rei, ponham no trono do pai e lutem para defendê-lo."

[[v12-10-4]]

^<<v12-10-4,4>>^ As autoridades de Samaria ficaram apavoradas e disseram: — Como poderemos ir contra Jeú, se nem o rei Jorão nem o rei Acazias conseguiram fazer isso?

[[v12-10-5]]

^<<v12-10-5,5>>^ Aí o oficial encarregado do palácio e o oficial encarregado da cidade, junto com os líderes e as pessoas que tomavam conta dos filhos de Acabe, mandaram a Jeú esta mensagem: "Nós somos seus criados e estamos prontos para fazer tudo o que o senhor disser. Porém não vamos colocar ninguém como rei; faça o que achar melhor."

[[v12-10-6]]

^<<v12-10-6,6>>^ Então Jeú escreveu outra carta, em que dizia o seguinte: "Se vocês estão do meu lado e estão prontos para seguir as minhas ordens, tragam as cabeças dos filhos do rei Acabe para mim, aqui em Jezreel, amanhã a esta hora." Os setenta filhos de Acabe moravam com os principais cidadãos de Samaria, que os estavam criando.

[[v12-10-7]]

^<<v12-10-7,7>>^ Quando receberam a carta de Jeú, os líderes de Samaria mataram todos os setenta príncipes. Depois puseram as cabeças deles em cestos e as mandaram para Jeú, em Jezreel.

[[v12-10-8]]

^<<v12-10-8,8>>^ Foram contar a Jeú que as cabeças dos filhos de Acabe haviam sido trazidas. Então Jeú ordenou: — Façam com elas dois montões no portão da cidade e deixem que fiquem lá até amanhã cedo.

[[v12-10-9]]

^<<v12-10-9,9>>^ Ele saiu de manhã, foi até o portão e disse ao povo que estava ali: — Fui eu que fiz uma revolta contra o rei Jorão e o matei; vocês não são culpados disso. Mas quem foi que matou todos estes?

[[v12-10-10]]

^<<v12-10-10,10>>^ Isso prova que vai acontecer tudo aquilo que o Senhor  Deus disse a respeito dos descendentes de Acabe. O Senhor  fez aquilo que prometeu por meio do seu servo  Elias.

[[v12-10-11]]

^<<v12-10-11,11>>^ Então Jeú mandou matar todos os outros parentes de Acabe que moravam em Jezreel e também todas as autoridades do seu governo, amigos íntimos e sacerdotes. Não escapou nenhum deles.

[[v12-10-12]]

^<<v12-10-12,12>>^ Jeú saiu de Jezreel para ir até Samaria. No caminho, num lugar chamado "Campo dos Pastores",

[[v12-10-13]]

^<<v12-10-13,13>>^ ele encontrou alguns parentes do falecido rei Acazias, de Judá, e lhes perguntou: — Quem são vocês? Eles responderam: — Somos parentes de Acazias. Estamos indo para Jezreel a fim de cumprimentar os filhos da rainha Jezabel e o resto da família do rei.

[[v12-10-14]]

^<<v12-10-14,14>>^ Então Jeú ordenou aos seus homens: — Peguem essa gente! Quero todos vivos! Eles os prenderam e os mataram perto de um poço que havia ali. Eram quarenta e dois ao todo, e nenhum deles foi deixado vivo.

[[v12-10-15]]

^<<v12-10-15,15>>^ Jeú saiu dali e no caminho encontrou-se com Jonadabe, filho de Recabe, que havia ido falar com ele. Jeú o cumprimentou e disse: — Será que nós dois estamos pensando do mesmo jeito? — Sim! — respondeu Jonadabe. — Então me dê a sua mão! — disse Jeú. Eles apertaram as mãos, e Jeú ajudou Jonadabe a subir no seu carro de guerra.

[[v12-10-16]]

^<<v12-10-16,16>>^ Jeú disse: — Venha comigo e veja você mesmo como sou dedicado a Deus, o Senhor . E Jeú o levou no seu carro para Samaria.

[[v12-10-17]]

^<<v12-10-17,17>>^ Quando chegaram lá, Jeú matou todos os parentes de Acabe. Não deixou nenhum vivo, conforme o Senhor  tinha dito a Elias que ia acontecer.

[[v12-10-18]]

^<<v12-10-18,18>>^ Jeú reuniu o povo de Samaria e disse: — O rei Acabe serviu pouco o deus Baal , mas eu o servirei muito.

[[v12-10-19]]

^<<v12-10-19,19>>^ Portanto, reúnam agora todos os profetas  de Baal, todos os seus adoradores e todos os seus sacerdotes. Que não falte nenhum, pois eu vou oferecer um grande sacrifício  a Baal, e quem não vier será morto! Mas esse era um jeito de Jeú enganar os adoradores de Baal para poder matá-los.

[[v12-10-20]]

^<<v12-10-20,20>>^ Então Jeú deu a seguinte ordem: — Anunciem um dia de adoração em honra do deus Baal! O aviso foi feito,

[[v12-10-21]]

^<<v12-10-21,21>>^ e Jeú mandou mensageiros por toda a terra de Israel. Então vieram todos os adoradores de Baal; não faltou nenhum. Eles entraram no templo de Baal, que ficou completamente cheio.

[[v12-10-22]]

^<<v12-10-22,22>>^ Então Jeú mandou que o sacerdote encarregado dos mantos  sagrados trouxesse os mantos e os entregasse aos adoradores.

[[v12-10-23]]

^<<v12-10-23,23>>^ Depois disso, Jeú entrou no templo com Jonadabe, filho de Recabe, e disse às pessoas que estavam ali: — Vejam bem que somente adoradores de Baal estejam aqui e que nenhum adorador de Deus, o Senhor , tenha entrado.

[[v12-10-24]]

^<<v12-10-24,24>>^ Aí ele e Jonadabe entraram para oferecer sacrifícios e queimar ofertas a Baal. Jeú havia mandado que oitenta homens ficassem do lado de fora, dando-lhes a seguinte ordem: — Matem todas essas pessoas que vou entregar a vocês; quem deixar uma delas escapar pagará com a vida por isso!

[[v12-10-25]]

^<<v12-10-25,25>>^ Assim que Jeú apresentou as ofertas, disse aos guardas e aos oficiais: — Entrem e matem todos; não deixem que nenhum escape! Eles entraram com as espadas na mão, mataram todos e jogaram os corpos para fora. Então entraram no santuário interior do templo,

[[v12-10-26]]

^<<v12-10-26,26>>^ levaram para fora as colunas que estavam no templo de Baal e as queimaram.

[[v12-10-27]]

^<<v12-10-27,27>>^ Também destruíram a coluna de Baal e o seu templo e fizeram esse templo virar uma privada, que existe até hoje .

[[v12-10-28]]

^<<v12-10-28,28>>^ Foi assim que Jeú acabou com a adoração de Baal em Israel.

[[v12-10-29]]

^<<v12-10-29,29>>^ Mas ele não abandonou os pecados do rei Jeroboão, filho de Nebate, que levou o povo de Israel a cometer o pecado de adorar os touros de ouro que ele havia colocado em Betel e em Dã.

[[v12-10-30]]

^<<v12-10-30,30>>^ O Senhor  Deus disse a Jeú: — Você fez com os descendentes de Acabe tudo aquilo que eu queria que fizesse. Por isso, prometo que até a quarta geração  os seus descendentes serão reis de Israel.

[[v12-10-31]]

^<<v12-10-31,31>>^ Mas Jeú não obedeceu de todo o seu coração à Lei  do Senhor , o Deus de Israel, nem abandonou aqueles mesmos pecados que Jeroboão havia feito o povo de Israel cometer no passado.

[[v12-10-32]]

^<<v12-10-32,32>>^ Nesse tempo o Senhor  Deus começou a diminuir o território de Israel. O rei Hazael, da Síria, conquistou todas as terras israelitas

[[v12-10-33]]

^<<v12-10-33,33>>^ que ficavam a leste do rio Jordão, até a cidade de Aroer, no rio Arnom, no Sul. Isso incluía as regiões de Gileade e Basã, onde moravam as tribos  de Gade, Rúben e Manassés do Leste.

[[v12-10-34]]

^<<v12-10-34,34>>^ Todas as outras coisas que Jeú fez e também os seus atos de coragem estão escritos na História dos Reis de Israel .

[[v12-10-35]]

^<<v12-10-35,35>>^ Ele morreu e foi sepultado em Samaria, e o seu filho Jeoacaz ficou no lugar dele como rei.

[[v12-10-36]]

^<<v12-10-36,36>>^ Jeú governou vinte e oito anos em Samaria como rei de Israel.

'''

xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[Próximo Capítulo &#62;]