include::./index.adoc[]

[[v12-23-0]]
=== 2 Reis, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v12-23-1]]

^<<v12-23-1,1>>^ O rei Josias ordenou que todos os líderes de Judá e de Jerusalém se reunissem com ele,

[[v12-23-2]]

^<<v12-23-2,2>>^ e eles foram todos juntos até o Templo, acompanhados pelos sacerdotes, pelos profetas  e por todo o resto do povo, tanto os mais importantes como os mais humildes. Então o rei leu diante deles todo o Livro da Aliança  que havia sido achado no Templo.

[[v12-23-3]]

^<<v12-23-3,3>>^ Ele ficou perto da coluna real, em pé, e fez com Deus, o Senhor , uma aliança pela qual eles lhe obedeceriam e guardariam as suas leis  e mandamentos com todo o coração e com toda a alma. E também cumpririam tudo o que a aliança mandava fazer, como estava escrito no livro. E todo o povo prometeu cumprir a aliança.

[[v12-23-4]]

^<<v12-23-4,4>>^ Então Josias ordenou a Hilquias, o Grande Sacerdote , aos sacerdotes-ajudantes e aos guardas que estavam de serviço na entrada do Templo que tirassem para fora do Templo todos os objetos usados na adoração do deus Baal , da deusa Aserá  e das estrelas. O rei queimou todos esses objetos fora da cidade, perto do vale do Cedrom, e mandou que levassem as cinzas para Betel.

[[v12-23-5]]

^<<v12-23-5,5>>^ Retirou do serviço os sacerdotes pagãos que os reis de Judá haviam nomeado para oferecer sacrifícios sobre os altares dedicados aos ídolos, nas cidades de Judá e nos lugares de perto de Jerusalém. Também retirou todos os sacerdotes que ofereciam sacrifícios ao deus Baal, ao sol, à lua, aos planetas e às estrelas.

[[v12-23-6]]

^<<v12-23-6,6>>^ Ele retirou do Templo o poste da deusa Aserá e o levou para fora da cidade, para o vale do Cedrom. Ali ele o queimou e fez virar cinza, que espalhou no cemitério público.

[[v12-23-7]]

^<<v12-23-7,7>>^ Ele destruiu os quartos do Templo onde ficavam os prostitutos . Era nesse lugar que as mulheres teciam as roupas usadas na adoração da deusa Aserá.

[[v12-23-8]]

^<<v12-23-8,8>>^ O rei Josias levou para Jerusalém os sacerdotes que estavam nas cidades de Judá e, por todo o país, desde Geba até Berseba, ele profanou  os altares onde esses sacerdotes haviam oferecido sacrifícios . O rei também derrubou os altares dedicados aos demônios do deserto. Esses altares ficavam perto do portão construído por Josué, o governador da cidade. O portão ficava à esquerda de quem entrava na cidade pelo portão principal.

[[v12-23-9]]

^<<v12-23-9,9>>^ Esses sacerdotes estavam proibidos de oferecer sacrifícios no Templo de Deus, o Senhor , mas podiam comer os pães sem fermento  junto com os outros sacerdotes.

[[v12-23-10]]

^<<v12-23-10,10>>^ O rei Josias também profanou Tofete, o lugar pagão de adoração que ficava no vale do Hinom, para que ninguém queimasse o seu filho ou filha como sacrifício ao deus Moloque .

[[v12-23-11]]

^<<v12-23-11,11>>^ Ele também retirou os cavalos que os reis de Judá haviam dedicado à adoração do sol e queimou os carros usados nessa adoração. Esses carros ficavam guardados no pátio do Templo, perto do portão e perto do quarto de Natã-Meleque, um alto funcionário.

[[v12-23-12]]

^<<v12-23-12,12>>^ O rei Josias derrubou os altares que os reis de Judá haviam construído no terraço do palácio, sobre a sala do rei Acaz, e também destruiu os altares construídos pelo rei Manassés nos dois pátios do Templo. Ele os fez em pedaços e jogou no vale do Cedrom.

[[v12-23-13]]

^<<v12-23-13,13>>^ Josias profanou também os altares que o rei Salomão havia construído a leste de Jerusalém, ao sul do monte das Oliveiras , para a adoração de Astarote , a nojenta deusa dos sidônios, para a adoração de Quemos, o nojento deus dos moabitas, e para a adoração de Moloque, o nojento deus dos amonitas.

[[v12-23-14]]

^<<v12-23-14,14>>^ O rei Josias fez em pedaços as colunas do deus Baal, derrubou os postes da deusa Aserá  e cobriu de ossos de gente o lugar onde eles haviam estado.

[[v12-23-15]]

^<<v12-23-15,15>>^ Josias também derrubou o lugar de adoração que ficava em Betel e que havia sido construído pelo rei Jeroboão, filho de Nebate, que tinha feito o povo de Israel pecar. Josias derrubou o altar, quebrou as suas pedras em pedaços e as esmigalhou até virarem pó. Ele também queimou o poste da deusa Aserá.

[[v12-23-16]]

^<<v12-23-16,16>>^ Então Josias olhou em redor e viu algumas sepulturas ali no morro; mandou que tirassem delas os ossos e os queimou sobre o altar. Dessa maneira ele profanou o altar, fazendo aquilo que o profeta tinha dito que ia acontecer, isso há muito tempo, quando o rei Jeroboão estava perto do altar, durante uma festa. O rei Josias olhou em redor e viu a sepultura do profeta que havia feito aquela profecia .

[[v12-23-17]]

^<<v12-23-17,17>>^ Então perguntou: — Que sepultura é esta? O povo de Betel respondeu: — É a sepultura do profeta que veio de Judá e profetizou  as coisas que o senhor acabou de fazer com este altar.

[[v12-23-18]]

^<<v12-23-18,18>>^ — Deixem a sepultura como está! — ordenou Josias. — Não mexam nos ossos dele. E assim os ossos daquele profeta ficaram junto com os ossos do profeta que tinha vindo de Samaria.

[[v12-23-19]]

^<<v12-23-19,19>>^ Em todas as cidades de Israel, Josias derrubou todos os lugares pagãos de adoração que haviam sido construídos pelos reis de Israel e que haviam provocado a ira  do Senhor . Com todos esses altares ele fez aquilo que havia feito em Betel.

[[v12-23-20]]

^<<v12-23-20,20>>^ E também matou todos os sacerdotes pagãos sobre os altares onde eles haviam oferecido sacrifícios e queimou ossos de gente em todos os altares. Depois voltou para Jerusalém.

[[v12-23-21]]

^<<v12-23-21,21>>^ O rei Josias ordenou que todo o povo comemorasse a Festa da Páscoa  em honra do Senhor , o Deus deles, conforme estava escrito no Livro da Aliança .

[[v12-23-22]]

^<<v12-23-22,22>>^ Desde a época em que os juízes governavam o país, nunca havia sido feita uma Festa da Páscoa como essa, por nenhum dos reis de Israel ou de Judá.

[[v12-23-23]]

^<<v12-23-23,23>>^ Foi no ano dezoito do reinado de Josias que essa Páscoa foi festejada em Jerusalém, em honra de Deus, o Senhor .

[[v12-23-24]]

^<<v12-23-24,24>>^ A fim de cumprir as leis  escritas no livro que Hilquias, o Grande Sacerdote , havia achado no Templo, o rei Josias retirou de Jerusalém e do resto de Judá todos os médiuns e adivinhos e todos os deuses do lar, os ídolos e todos os outros objetos de adoração pagã.

[[v12-23-25]]

^<<v12-23-25,25>>^ Não houve antes nenhum rei como ele, que servisse a Deus, o Senhor , com todo o seu coração, mente e força, obedecendo a toda a Lei de Moisés; e depois nunca houve outro rei igual a ele.

[[v12-23-26]]

^<<v12-23-26,26>>^ Mas a ira  terrível do Senhor  havia sido provocada contra Judá por causa das coisas que o rei Manassés havia feito e essa ira ainda não havia passado.

[[v12-23-27]]

^<<v12-23-27,27>>^ O Senhor  disse: — Eu farei com Judá o mesmo que fiz com Israel: expulsarei da minha presença o povo de Judá e rejeitarei Jerusalém, a cidade que escolhi, e o Templo, o lugar onde eu disse que seria adorado.

[[v12-23-28]]

^<<v12-23-28,28>>^ Todas as outras coisas que o rei Josias fez estão escritas na História dos Reis de Judá .

[[v12-23-29]]

^<<v12-23-29,29>>^ Durante o reinado de Josias, Faraó Neco, rei do Egito, levou o seu exército até o rio Eufrates para ajudar o rei da Assíria. O rei Josias saiu para lutar contra o rei Neco, em Megido, e foi morto em batalha.

[[v12-23-30]]

^<<v12-23-30,30>>^ Os seus oficiais puseram o corpo dele num carro de guerra e o levaram de volta para Jerusalém, onde foi sepultado no seu túmulo. O povo de Judá escolheu Joacaz, filho de Josias, e o ungiu  como rei em lugar do seu pai.

[[v12-23-31]]

^<<v12-23-31,31>>^ Joacaz tinha vinte e três anos de idade quando se tornou rei de Judá. Ele governou três meses em Jerusalém. A mãe dele se chamava Hamutal e era filha de Jeremias, da cidade de Libna.

[[v12-23-32]]

^<<v12-23-32,32>>^ Seguindo o exemplo dos seus antepassados, Joacaz fez coisas erradas, que não agradam a Deus, o Senhor .

[[v12-23-33]]

^<<v12-23-33,33>>^ O seu reinado acabou quando o rei Neco mandou prendê-lo em Ribla, na terra de Hamate, e obrigou o povo de Judá a entregar três mil e quatrocentos quilos de prata e trinta e quatro quilos de ouro.

[[v12-23-34]]

^<<v12-23-34,34>>^ Faraó Neco pôs Eliaquim, filho de Josias, como rei de Judá, no lugar de Josias, o seu pai, e mudou o nome dele para Jeoaquim. Joacaz foi levado pelo rei Neco para o Egito e morreu ali.

[[v12-23-35]]

^<<v12-23-35,35>>^ O rei Jeoaquim cobrou do povo um imposto de acordo com as posses deles, a fim de juntar a prata e o ouro necessários para pagar o que o rei do Egito havia exigido.

[[v12-23-36]]

^<<v12-23-36,36>>^ Jeoaquim tinha vinte e cinco anos de idade quando se tornou rei de Judá. Ele governou onze anos em Jerusalém. A mãe dele se chamava Zebida e era filha de Pedaías, da cidade de Ruma.

[[v12-23-37]]

^<<v12-23-37,37>>^ Seguindo o exemplo dos seus antepassados, Jeoaquim fez coisas erradas, que não agradam a Deus, o Senhor .

'''

xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[&#60; Capítulo Anterior] | <<v12-23-0,Topo>> | xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[Próximo Capítulo &#62;]