include::./index.adoc[]

[[v1-5-0]]
=== Gênesis, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-5-1]]

^<<v1-5-1,1>>^ Esta é a lista dos descendentes de Adão. Quando criou os seres humanos, Deus os fez parecidos com ele.

[[v1-5-2]]

^<<v1-5-2,2>>^ Deus os criou homem e mulher, e os abençoou, e lhes deu o nome de "humanidade" .

[[v1-5-3]]

^<<v1-5-3,3>>^ Com a idade de cento e trinta anos, Adão foi pai de um filho que era parecido com ele; e pôs nele o nome de Sete.

[[v1-5-4]]

^<<v1-5-4,4>>^ Depois disso Adão viveu mais oitocentos anos. Ele foi pai de outros filhos e filhas

[[v1-5-5]]

^<<v1-5-5,5>>^ e morreu com novecentos e trinta anos de idade.

[[v1-5-6]]

^<<v1-5-6,6>>^ Quando Sete completou cento e cinco anos, nasceu o seu filho Enos.

[[v1-5-7]]

^<<v1-5-7,7>>^ Depois disso Sete viveu mais oitocentos e sete anos. Ele foi pai de outros filhos e filhas

[[v1-5-8]]

^<<v1-5-8,8>>^ e morreu com novecentos e doze anos de idade.

[[v1-5-9]]

^<<v1-5-9,9>>^ Quando Enos tinha noventa anos, nasceu o seu filho Cainã.

[[v1-5-10]]

^<<v1-5-10,10>>^ Depois disso Enos viveu mais oitocentos e quinze anos. Ele foi pai de outros filhos e filhas

[[v1-5-11]]

^<<v1-5-11,11>>^ e morreu com novecentos e cinco anos de idade.

[[v1-5-12]]

^<<v1-5-12,12>>^ Quando Cainã tinha setenta anos, o seu filho Maalalel nasceu.

[[v1-5-13]]

^<<v1-5-13,13>>^ Depois disso Cainã viveu mais oitocentos e quarenta anos. Ele foi pai de outros filhos e filhas

[[v1-5-14]]

^<<v1-5-14,14>>^ e morreu com novecentos e dez anos de idade.

[[v1-5-15]]

^<<v1-5-15,15>>^ Quando Maalalel tinha sessenta e cinco anos, nasceu o seu filho Jarede.

[[v1-5-16]]

^<<v1-5-16,16>>^ Depois disso Maalalel viveu mais oitocentos e trinta anos. Ele foi pai de outros filhos e filhas

[[v1-5-17]]

^<<v1-5-17,17>>^ e morreu com oitocentos e noventa e cinco anos de idade.

[[v1-5-18]]

^<<v1-5-18,18>>^ Jarede tinha cento e sessenta e dois anos quando o seu filho Enoque nasceu.

[[v1-5-19]]

^<<v1-5-19,19>>^ Depois disso Jarede viveu mais oitocentos anos. Ele foi pai de outros filhos e filhas

[[v1-5-20]]

^<<v1-5-20,20>>^ e morreu com novecentos e sessenta e dois anos de idade.

[[v1-5-21]]

^<<v1-5-21,21>>^ Quando Enoque tinha sessenta e cinco anos, o seu filho Matusalém nasceu.

[[v1-5-22]]

^<<v1-5-22,22>>^ Depois disso Enoque viveu em comunhão com Deus durante trezentos anos e foi pai de outros filhos e filhas.

[[v1-5-23]]

^<<v1-5-23,23>>^ Enoque viveu trezentos e sessenta e cinco anos.

[[v1-5-24]]

^<<v1-5-24,24>>^ Ele viveu sempre em comunhão com Deus e um dia desapareceu, pois Deus o levou.

[[v1-5-25]]

^<<v1-5-25,25>>^ Quando Matusalém tinha cento e oitenta e sete anos, o seu filho Lameque nasceu.

[[v1-5-26]]

^<<v1-5-26,26>>^ Depois disso Matusalém viveu mais setecentos e oitenta e dois anos. Ele foi pai de outros filhos e filhas

[[v1-5-27]]

^<<v1-5-27,27>>^ e morreu com novecentos e sessenta e nove anos de idade.

[[v1-5-28]]

^<<v1-5-28,28>>^ Quando Lameque tinha cento e oitenta e dois anos, foi pai de um filho

[[v1-5-29]]

^<<v1-5-29,29>>^ e disse: — O Senhor  Deus amaldiçoou a terra, e por isso o nosso trabalho é pesado; mas este menino vai trazer descanso para nós. E Lameque pôs no filho o nome de Noé .

[[v1-5-30]]

^<<v1-5-30,30>>^ Depois disso Lameque viveu mais quinhentos e noventa e cinco anos. Ele foi pai de outros filhos e filhas

[[v1-5-31]]

^<<v1-5-31,31>>^ e morreu com setecentos e setenta e sete anos de idade.

[[v1-5-32]]

^<<v1-5-32,32>>^ Depois que completou quinhentos anos de idade, Noé foi pai de três filhos: Sem, Cam e Jafé.

'''

xref:001-genesis/001-genesis-004.adoc#v1-4-0[&#60; Capítulo Anterior] | <<v1-5-0,Topo>> | xref:001-genesis/001-genesis-006.adoc#v1-6-0[Próximo Capítulo &#62;]