include::./index.adoc[]

[[v1-4-0]]
=== Gênesis, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-4-1]]

^<<v1-4-1,1>>^ Adão teve relações com Eva, a sua mulher, e ela ficou grávida. Eva deu à luz um filho e disse: — Com a ajuda de Deus, o Senhor , tive um filho homem. E ela pôs nele o nome de Caim .

[[v1-4-2]]

^<<v1-4-2,2>>^ Depois teve outro filho, chamado Abel, irmão de Caim. Abel era pastor de ovelhas, e Caim era agricultor.

[[v1-4-3]]

^<<v1-4-3,3>>^ O tempo passou. Um dia Caim pegou alguns produtos da terra e os ofereceu a Deus, o Senhor .

[[v1-4-4]]

^<<v1-4-4,4>>^ Abel, por sua vez, pegou o primeiro carneirinho nascido no seu rebanho, matou-o e ofereceu as melhores partes ao Senhor . O Senhor  ficou contente com Abel e com a sua oferta,

[[v1-4-5]]

^<<v1-4-5,5>>^ mas rejeitou Caim e a sua oferta. Caim ficou furioso e fechou a cara.

[[v1-4-6]]

^<<v1-4-6,6>>^ Então o Senhor  disse: — Por que você está com raiva? Por que anda carrancudo?

[[v1-4-7]]

^<<v1-4-7,7>>^ Se tivesse feito o que é certo, você estaria sorrindo; mas você agiu mal, e por isso o pecado está na porta, à sua espera. Ele quer dominá-lo, mas você precisa vencê-lo.

[[v1-4-8]]

^<<v1-4-8,8>>^ Aí Caim disse a Abel, o seu irmão: — Vamos até o campo. Quando os dois estavam no campo, Caim atacou Abel, o seu irmão, e o matou.

[[v1-4-9]]

^<<v1-4-9,9>>^ Mais tarde o Senhor  perguntou a Caim: — Onde está Abel, o seu irmão? — Não sei — respondeu Caim. — Por acaso eu sou o guarda do meu irmão?

[[v1-4-10]]

^<<v1-4-10,10>>^ Então Deus disse: — Por que você fez isso? Da terra, o sangue do seu irmão está gritando, pedindo vingança.

[[v1-4-11]]

^<<v1-4-11,11>>^ Por isso você será amaldiçoado e não poderá mais cultivar a terra. Pois, quando você matou o seu irmão, a terra abriu a boca para beber o sangue dele.

[[v1-4-12]]

^<<v1-4-12,12>>^ Quando você preparar a terra para plantar, ela não produzirá nada. Você vai andar pelo mundo sempre fugindo.

[[v1-4-13]]

^<<v1-4-13,13>>^ Caim disse a Deus, o Senhor : — Eu não vou poder aguentar esse castigo tão pesado.

[[v1-4-14]]

^<<v1-4-14,14>>^ Hoje tu estás me expulsando desta terra. Terei de andar pelo mundo sempre fugindo e me escondendo da tua presença. E qualquer pessoa que me encontrar vai querer me matar.

[[v1-4-15]]

^<<v1-4-15,15>>^ Mas o Senhor  respondeu: — Isso não vai acontecer. Pois, se alguém matar você, serão mortas sete pessoas da família dele, como vingança. Em seguida o Senhor  pôs um sinal em Caim para que, se alguém o encontrasse, não o matasse.

[[v1-4-16]]

^<<v1-4-16,16>>^ Então Caim saiu da presença do Senhor  e foi morar na região de Node , que fica a leste do Éden.

[[v1-4-17]]

^<<v1-4-17,17>>^ Caim e a sua mulher tiveram um filho e lhe deram o nome de Enoque. Mais tarde Caim construiu uma cidade e a chamou de Enoque, o nome do seu filho.

[[v1-4-18]]

^<<v1-4-18,18>>^ Enoque foi pai de Irade, que foi pai de Meujael, que foi pai de Metusael, que foi pai de Lameque.

[[v1-4-19]]

^<<v1-4-19,19>>^ Lameque teve duas mulheres: uma delas se chamava Ada, e a outra, Zilá.

[[v1-4-20]]

^<<v1-4-20,20>>^ Ada teve um filho chamado Jabal, que foi o antepassado dos que criam gado e vivem em barracas.

[[v1-4-21]]

^<<v1-4-21,21>>^ Jabal tinha um irmão chamado Jubal, que foi o antepassado de todos os músicos que tocam lira  e flauta.

[[v1-4-22]]

^<<v1-4-22,22>>^ Zilá, por sua vez, teve um filho chamado Tubalcaim, que era ferreiro e fazia objetos de bronze e de ferro. Tubalcaim tinha uma irmã chamada Naama.

[[v1-4-23]]

^<<v1-4-23,23>>^ Certo dia Lameque disse às suas mulheres: "Ada e Zilá, escutem-me; mulheres de Lameque, marquem bem o que eu digo. Matei um homem porque me feriu, matei um moço porque me machucou.

[[v1-4-24]]

^<<v1-4-24,24>>^ Se são mortas sete pessoas para pagar pela morte de Caim, então, se alguém me matar, serão mortas setenta e sete pessoas da família do assassino."

[[v1-4-25]]

^<<v1-4-25,25>>^ Adão e a sua mulher tiveram outro filho. Ela disse: — Deus me deu outro filho para ficar em lugar de Abel, que foi morto por Caim. E pôs nele o nome de Sete .

[[v1-4-26]]

^<<v1-4-26,26>>^ Sete foi pai de um filho e o chamou de Enos. Foi nesse tempo que o nome Senhor  começou a ser usado no culto de adoração a Deus.

'''

xref:001-genesis/001-genesis-003.adoc#v1-3-0[&#60; Capítulo Anterior] | <<v1-4-0,Topo>> | xref:001-genesis/001-genesis-005.adoc#v1-5-0[Próximo Capítulo &#62;]