include::./index.adoc[]

[[v1-49-0]]
=== Gênesis, 49
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-49-1]]

^<<v1-49-1,1>>^ Jacó chamou os seus filhos e disse: — Fiquem em volta de mim, e eu lhes direi o que vai acontecer com vocês no futuro.

[[v1-49-2]]

^<<v1-49-2,2>>^ "Fiquem reunidos em volta de mim para ouvir, filhos de Jacó; escutem o que diz Israel, o seu pai.

[[v1-49-3]]

^<<v1-49-3,3>>^ "Rúben, você é o meu filho mais velho. Você é a minha força, o primeiro fruto do meu vigor, o mais orgulhoso e o mais forte dos meus filhos.

[[v1-49-4]]

^<<v1-49-4,4>>^ Você é violento como a correnteza, porém não será o mais importante, pois dormiu com a minha concubina , desonrando assim a cama do seu pai.

[[v1-49-5]]

^<<v1-49-5,5>>^ "Simeão e Levi são irmãos; com as suas armas praticam violências.

[[v1-49-6]]

^<<v1-49-6,6>>^ Não estarei presente quando fizerem planos, não tomarei parte nas suas reuniões, pois no seu furor mataram homens e por brincadeira aleijaram touros.

[[v1-49-7]]

^<<v1-49-7,7>>^ Maldito seja o furor deles, pois é violento! Maldita seja a sua ira, pois é cruel! Eu os dividirei na terra de Israel, eu os espalharei no meio do seu povo.

[[v1-49-8]]

^<<v1-49-8,8>>^ "Judá, os seus irmãos o louvarão e se curvarão na sua frente. Você segurará os inimigos pelo pescoço.

[[v1-49-9]]

^<<v1-49-9,9>>^ O meu filho Judá é como um leãozinho quando mata a sua vítima; ele se agacha e se deita como um leão e como uma leoa. Quem tem a coragem de mexer com ele?

[[v1-49-10]]

^<<v1-49-10,10>>^ Judá vai segurar o cetro  de rei, e os seus descendentes sempre governarão. As nações lhe trarão presentes, os povos lhe obedecerão.

[[v1-49-11]]

^<<v1-49-11,11>>^ Ele amarra o seu jumentinho numa parreira , na melhor parreira que há. Ele lava as suas roupas no vinho, lava a sua capa  no vinho cor de sangue.

[[v1-49-12]]

^<<v1-49-12,12>>^ Os seus olhos estão vermelhos de beber vinho, os seus dentes estão brancos de beber leite.

[[v1-49-13]]

^<<v1-49-13,13>>^ "Zebulom morará no litoral, onde haverá portos para navios. A sua fronteira chegará até Sidom.

[[v1-49-14]]

^<<v1-49-14,14>>^ "Issacar é como um jumento forte, deitado entre as suas cargas.

[[v1-49-15]]

^<<v1-49-15,15>>^ Quando viu que o país era bom e agradável para descansar, ele se abaixou para que colocassem a carga nas suas costas e, sem reclamar, trabalhou como um escravo.

[[v1-49-16]]

^<<v1-49-16,16>>^ "Dã governará a sua própria gente; será como as outras tribos  de Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Dã será como uma cobra na beira da estrada, como uma serpente venenosa no caminho, que morde a pata do cavalo, fazendo cair para trás o seu cavaleiro.

[[v1-49-18]]

^<<v1-49-18,18>>^ "Ó Senhor , meu Deus, espero que me salves!

[[v1-49-19]]

^<<v1-49-19,19>>^ "Gade será atacado por um bando de ladrões, mas depois ele os perseguirá.

[[v1-49-20]]

^<<v1-49-20,20>>^ "A terra de Aser produzirá bons alimentos, dará alimentos que só reis merecem.

[[v1-49-21]]

^<<v1-49-21,21>>^ "Naftali é como uma corça  solta que tem lindos filhotes.

[[v1-49-22]]

^<<v1-49-22,22>>^ "José é como uma planta perto de uma fonte; ela dá muita fruta, e os seus galhos sobem pelo muro.

[[v1-49-23]]

^<<v1-49-23,23>>^ Os inimigos o atacam com violência e o perseguem com os seus arcos e flechas.

[[v1-49-24]]

^<<v1-49-24,24>>^ Porém o seu arco ficou firme, e os seus braços continuaram fortes pela força do Poderoso de Jacó, pelo nome do Pastor, a Rocha de Israel.

[[v1-49-25]]

^<<v1-49-25,25>>^ O Deus do seu pai ajudará José, o Todo-Poderoso lhe dará bênçãos — bênçãos do alto céu, bênçãos de águas que ficam debaixo da terra, bênçãos de muitos animais e muitos filhos,

[[v1-49-26]]

^<<v1-49-26,26>>^ bênçãos de cereais e de flores, bênçãos de montanhas antigas, coisas deliciosas dos montes eternos. Que todas essas bênçãos estejam sobre a cabeça de José, sobre a testa daquele que foi escolhido entre os seus irmãos.

[[v1-49-27]]

^<<v1-49-27,27>>^ "Benjamim é como um lobo feroz; de manhã devorará a vítima e de tarde repartirá as sobras."

[[v1-49-28]]

^<<v1-49-28,28>>^ São essas as doze tribos de Israel, e foram essas as palavras que o pai disse aos seus filhos quando os abençoou; a cada um deu uma bênção especial.

[[v1-49-29]]

^<<v1-49-29,29>>^ Então Jacó deu aos filhos a seguinte ordem: — Eu estou para morrer e me reunir com o meu povo no mundo dos mortos . Sepultem-me onde estão sepultados os meus antepassados, na caverna que fica nas terras de Efrom, o heteu,

[[v1-49-30]]

^<<v1-49-30,30>>^ em Macpela, a leste de Manre, no país de Canaã. Abraão comprou de Efrom essa caverna e o terreno onde ela fica, para ser a sepultura da família.

[[v1-49-31]]

^<<v1-49-31,31>>^ Ali estão sepultados Abraão e Sara, a sua mulher; Isaque e a sua mulher Rebeca; e ali eu sepultei Leia.

[[v1-49-32]]

^<<v1-49-32,32>>^ O terreno e a caverna foram comprados dos heteus.

[[v1-49-33]]

^<<v1-49-33,33>>^ Quando acabou de dar essa ordem aos filhos, Jacó deitou-se de novo na cama e morreu, indo reunir-se assim com o seu povo no mundo dos mortos.

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]