include::./index.adoc[]

[[v1-30-0]]
=== Gênesis, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-30-1]]

^<<v1-30-1,1>>^ Quando Raquel percebeu que não podia ter filhos, ficou com inveja da sua irmã Leia e disse ao marido: — Dê-me filhos; se não, eu morro!

[[v1-30-2]]

^<<v1-30-2,2>>^ Jacó ficou zangado com Raquel e disse: — Você está pensando que eu sou Deus? É ele quem não deixa você ter filhos.

[[v1-30-3]]

^<<v1-30-3,3>>^ Então Raquel disse: — Aqui está a minha escrava Bila; tenha relações com ela. Quando ela tiver um filho, será como se fosse meu. Desse modo eu serei mãe por meio dela .

[[v1-30-4]]

^<<v1-30-4,4>>^ Assim, Raquel deu a Jacó a sua escrava Bila para ser sua concubina , e ele teve relações com ela.

[[v1-30-5]]

^<<v1-30-5,5>>^ Bila ficou grávida e deu a Jacó um filho.

[[v1-30-6]]

^<<v1-30-6,6>>^ Então Raquel disse: — Este menino vai se chamar Dã porque Deus foi justo comigo. Ele ouviu a minha oração e me deu um filho.

[[v1-30-7]]

^<<v1-30-7,7>>^ Bila ficou grávida outra vez e deu a Jacó outro filho.

[[v1-30-8]]

^<<v1-30-8,8>>^ Aí Raquel disse: — O nome deste menino será Naftali porque lutei muito contra minha irmã e venci.

[[v1-30-9]]

^<<v1-30-9,9>>^ Quando Leia percebeu que não ia ter mais filhos, deu a sua escrava Zilpa a Jacó para ser sua concubina.

[[v1-30-10]]

^<<v1-30-10,10>>^ E Zilpa deu a Jacó um filho.

[[v1-30-11]]

^<<v1-30-11,11>>^ Então Leia disse: — Que sorte! Este menino vai se chamar Gade .

[[v1-30-12]]

^<<v1-30-12,12>>^ Depois Zilpa deu a Jacó outro filho,

[[v1-30-13]]

^<<v1-30-13,13>>^ e Leia disse: — Como sou feliz! Agora as mulheres dirão que sou feliz. Por isso o menino se chamará Aser .

[[v1-30-14]]

^<<v1-30-14,14>>^ Um dia, no tempo da colheita do trigo, Rúben foi ao campo. Ali achou umas mandrágoras e as levou para Leia, a sua mãe. Quando Raquel viu isso, disse a Leia: — Por favor, dê-me algumas das mandrágoras que o seu filho trouxe.

[[v1-30-15]]

^<<v1-30-15,15>>^ Leia respondeu: — Será que você acha que tomar o meu marido de mim ainda é pouco? Agora vai querer tomar também as mandrágoras que o meu filho me deu? Aí Raquel disse: — Vamos fazer uma troca: você me dá as mandrágoras, e eu deixo que você durma com Jacó esta noite.

[[v1-30-16]]

^<<v1-30-16,16>>^ De tardinha, quando Jacó chegou do campo, Leia foi encontrar-se com ele e disse: — Esta noite você vai dormir comigo porque eu paguei para isso com as mandrágoras que o meu filho achou. Naquela noite Jacó teve relações com ela.

[[v1-30-17]]

^<<v1-30-17,17>>^ Deus ouviu a oração de Leia, e ela ficou grávida e deu a Jacó um quinto filho.

[[v1-30-18]]

^<<v1-30-18,18>>^ Então Leia disse: — Este menino se chamará Issacar , pois Deus me recompensou por ter dado a minha escrava ao meu marido.

[[v1-30-19]]

^<<v1-30-19,19>>^ Depois Leia engravidou pela sexta vez e deu a Jacó mais um filho.

[[v1-30-20]]

^<<v1-30-20,20>>^ E disse: — Deus me deu um belo presente. Agora o meu marido vai ficar comigo porque lhe dei seis filhos. Por isso ela pôs nele o nome de Zebulom .

[[v1-30-21]]

^<<v1-30-21,21>>^ Por último Leia teve uma filha e lhe deu o nome de Dina.

[[v1-30-22]]

^<<v1-30-22,22>>^ Então Deus lembrou de Raquel. Ele ouviu a sua oração e fez com que ela pudesse ter filhos.

[[v1-30-23]]

^<<v1-30-23,23>>^ Ela engravidou e deu à luz um filho. Então disse: — Deus não deixou que eu continuasse envergonhada por não ter filhos.

[[v1-30-24]]

^<<v1-30-24,24>>^ Que o Senhor  Deus me dê mais um filho. Por isso ela pôs nele o nome de José .

[[v1-30-25]]

^<<v1-30-25,25>>^ Depois do nascimento de José, Jacó disse a Labão: — Deixe-me voltar para a minha terra.

[[v1-30-26]]

^<<v1-30-26,26>>^ Dê-me os meus filhos e as minhas mulheres, que eu ganhei trabalhando para o senhor, e eu irei embora. O senhor sabe muito bem quanto eu o tenho servido.

[[v1-30-27]]

^<<v1-30-27,27>>^ Labão respondeu: — Fique comigo, por favor, pois por meio de adivinhações fiquei sabendo que o Senhor  Deus está me abençoando por causa de você.

[[v1-30-28]]

^<<v1-30-28,28>>^ Diga quanto quer ganhar, que eu pagarei.

[[v1-30-29]]

^<<v1-30-29,29>>^ Então Jacó disse: — O senhor sabe como tenho trabalhado e como tenho cuidado dos seus animais.

[[v1-30-30]]

^<<v1-30-30,30>>^ Antes de eu chegar, o senhor tinha pouco, mas depois tudo aumentou muito. E Deus tem abençoado o senhor em todos os lugares por onde eu tenho andado. Mas agora preciso cuidar da minha própria família.

[[v1-30-31]]

^<<v1-30-31,31>>^ — Quanto você quer que eu lhe pague? — insistiu Labão. Jacó respondeu: — Não quero salário. Eu continuarei a cuidar das suas ovelhas se o senhor concordar com a proposta que vou fazer.

[[v1-30-32]]

^<<v1-30-32,32>>^ Hoje vou passar por todo o seu rebanho a fim de separar para mim todos os carneirinhos pretos e todos os cabritos malhados e com manchas. É só isso que eu quero como salário.

[[v1-30-33]]

^<<v1-30-33,33>>^ No futuro será fácil o senhor saber se eu tenho sido honesto. Na hora de conferir o meu salário, se houver no meu rebanho carneirinhos que não sejam pretos e cabritos que não sejam malhados ou não tenham manchas, o senhor saberá que fui eu que roubei.

[[v1-30-34]]

^<<v1-30-34,34>>^ Labão concordou, dizendo: — Está bem. Aceito a sua proposta.

[[v1-30-35]]

^<<v1-30-35,35>>^ Mas naquele mesmo dia Labão separou para si todos os cabritos que tinham listas ou manchas, todas as cabras malhadas e as manchadas ou que tinham algum branco e todos os carneirinhos pretos. Ele os entregou aos seus filhos para cuidarem deles

[[v1-30-36]]

^<<v1-30-36,36>>^ e se afastou de Jacó a uma distância de três dias de viagem. E Jacó ficou cuidando dos outros animais de Labão.

[[v1-30-37]]

^<<v1-30-37,37>>^ Então Jacó pegou galhos verdes de choupo, de amendoeira e de plátano e descascou-os, fazendo aparecer listas brancas.

[[v1-30-38]]

^<<v1-30-38,38>>^ Ele pôs esses galhos na frente dos animais, nos bebedouros onde iam beber. Ele fez isso porque eles cruzavam quando iam beber.

[[v1-30-39]]

^<<v1-30-39,39>>^ E, como cruzavam diante dos galhos, as ovelhas davam crias listadas, com manchas e malhadas.

[[v1-30-40]]

^<<v1-30-40,40>>^ Jacó separou as ovelhas dos bodes e fez com que olhassem na direção dos animais listados e dos animais pretos do rebanho de Labão. Assim, Jacó foi formando o seu próprio rebanho, separando-o dos animais de Labão.

[[v1-30-41]]

^<<v1-30-41,41>>^ Quando os animais fortes estavam cruzando, Jacó punha os galhos das árvores na frente deles nos bebedouros, e assim eles cruzavam perto dos galhos.

[[v1-30-42]]

^<<v1-30-42,42>>^ Mas na frente dos animais fracos Jacó não punha os galhos. Por isso os animais fracos ficavam para Labão, e os mais fortes ficavam para Jacó.

[[v1-30-43]]

^<<v1-30-43,43>>^ Desse modo ele ficou muito rico e chegou a ter muitas ovelhas e cabras, escravos, escravas, camelos e jumentos.

'''

xref:001-genesis/001-genesis-029.adoc#v1-29-0[&#60; Capítulo Anterior] | <<v1-30-0,Topo>> | xref:001-genesis/001-genesis-031.adoc#v1-31-0[Próximo Capítulo &#62;]