include::./index.adoc[]

[[v1-26-0]]
=== Gênesis, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-26-1]]

^<<v1-26-1,1>>^ Naquela região houve uma época de falta de alimentos, como tinha acontecido antes, no tempo de Abraão. Por isso Isaque foi até a cidade de Gerar, onde vivia Abimeleque, o rei dos filisteus.

[[v1-26-2]]

^<<v1-26-2,2>>^ Ali o Senhor  Deus apareceu a Isaque e disse: — Não vá para o Egito. Fique na terra que eu vou lhe mostrar.

[[v1-26-3]]

^<<v1-26-3,3>>^ Por enquanto fique morando neste lugar, e eu estarei com você e o abençoarei. Darei aos seus descendentes todas estas terras e assim cumprirei o juramento que fiz a Abraão, o seu pai.

[[v1-26-4]]

^<<v1-26-4,4>>^ Farei com que os seus descendentes sejam tão numerosos quanto as estrelas do céu e lhes darei todas estas terras. Por meio dos seus descendentes eu abençoarei todas as nações do mundo,

[[v1-26-5]]

^<<v1-26-5,5>>^ pois Abraão me obedeceu e cumpriu as minhas ordens, os meus mandamentos, as minhas leis  e os meus ensinamentos.

[[v1-26-6]]

^<<v1-26-6,6>>^ Assim, Isaque ficou morando em Gerar.

[[v1-26-7]]

^<<v1-26-7,7>>^ Quando os homens do lugar lhe fizeram perguntas sobre a sua mulher, ele disse que ela era sua irmã. Rebeca era muito bonita, e Isaque tinha medo de dizer que ela era a sua mulher, pois pensava que os homens do lugar o matariam para ficarem com ela.

[[v1-26-8]]

^<<v1-26-8,8>>^ Isaque ficou ali muito tempo. Um dia Abimeleque, o rei dos filisteus, olhou por uma janela e viu Isaque acariciando Rebeca, a sua mulher.

[[v1-26-9]]

^<<v1-26-9,9>>^ Então Abimeleque mandou chamar Isaque e perguntou: — Ela é a sua mulher, não é verdade? Por que você disse que ela era sua irmã? — É que eu pensei que me matariam se eu dissesse que ela era a minha mulher — respondeu Isaque.

[[v1-26-10]]

^<<v1-26-10,10>>^ Aí Abimeleque disse: — Por que você nos fez isso? Um de nós poderia facilmente ter ido para a cama com ela, e você teria feito com que a culpa caísse sobre nós.

[[v1-26-11]]

^<<v1-26-11,11>>^ Então Abimeleque mandou a todo o seu povo o seguinte aviso: "Se alguém tratar mal este homem ou a sua mulher, será morto."

[[v1-26-12]]

^<<v1-26-12,12>>^ Naquele ano Isaque fez plantações ali e colheu cem vezes mais do que semeou, pois o Senhor  Deus o abençoou.

[[v1-26-13]]

^<<v1-26-13,13>>^ Ele foi enriquecendo cada vez mais e se tornou muito rico e poderoso.

[[v1-26-14]]

^<<v1-26-14,14>>^ Isaque tinha tantas ovelhas e cabras, tanto gado e tantos empregados, que os filisteus acabaram ficando com inveja dele.

[[v1-26-15]]

^<<v1-26-15,15>>^ Por isso eles entupiram com terra todos os poços que os empregados de Abraão, o pai de Isaque, haviam cavado no tempo em que Abraão ainda estava vivo.

[[v1-26-16]]

^<<v1-26-16,16>>^ Até que um dia Abimeleque disse a Isaque: — Vá embora da nossa terra. Você ficou muito mais poderoso do que nós.

[[v1-26-17]]

^<<v1-26-17,17>>^ Isaque saiu dali, armou as suas barracas no vale de Gerar e ficou morando ali por algum tempo.

[[v1-26-18]]

^<<v1-26-18,18>>^ Ele tornou a abrir os poços que haviam sido cavados no tempo de Abraão e que os filisteus haviam tapado depois da sua morte. E Isaque pôs nos poços os mesmos nomes que o seu pai havia posto.

[[v1-26-19]]

^<<v1-26-19,19>>^ Um dia os empregados de Isaque estavam no vale abrindo um poço e acharam uma mina de água.

[[v1-26-20]]

^<<v1-26-20,20>>^ Os pastores de Gerar discutiram com os pastores de Isaque, afirmando que a água era deles. Por isso Isaque deu a esse poço o nome de "Discussão".

[[v1-26-21]]

^<<v1-26-21,21>>^ Depois os empregados de Isaque abriram outro poço e por causa dele também houve discussão. Então Isaque pôs nele o nome de "Inimizade".

[[v1-26-22]]

^<<v1-26-22,22>>^ Isaque saiu dali e abriu outro poço. E, como não houve discussão por causa desse, ele o chamou de "Lugar Espaçoso". Ele disse: — Agora o Senhor  Deus nos deu um lugar espaçoso para viver nesta terra, e aqui vamos ficar à vontade.

[[v1-26-23]]

^<<v1-26-23,23>>^ Dali Isaque foi para Berseba.

[[v1-26-24]]

^<<v1-26-24,24>>^ Naquela noite o Senhor  apareceu a ele e disse: — Eu sou o Deus de Abraão, o seu pai. Não tenha medo, pois eu estou com você. Por causa do meu servo  Abraão, eu abençoarei você e farei com que os seus descendentes sejam muitos.

[[v1-26-25]]

^<<v1-26-25,25>>^ Isaque construiu um altar ali e adorou a Deus, o Senhor . Ele armou as suas barracas naquele lugar, e ali os seus empregados cavaram outro poço.

[[v1-26-26]]

^<<v1-26-26,26>>^ Certo dia Abimeleque saiu de Gerar e foi conversar com Isaque. Com ele foram o seu amigo Auzate e Ficol, o comandante do seu exército.

[[v1-26-27]]

^<<v1-26-27,27>>^ Isaque perguntou: — Por que é que vocês vieram falar comigo, se têm ódio de mim e até me expulsaram da sua terra?

[[v1-26-28]]

^<<v1-26-28,28>>^ Eles responderam: — Agora nós sabemos que o Senhor  Deus está com você e pensamos que deveríamos fazer um trato com você, selado  com juramento. O trato é este:

[[v1-26-29]]

^<<v1-26-29,29>>^ Você não nos fará nenhum mal, assim como nós não fizemos nenhum mal a você. Nós fomos bondosos para você e deixamos que fosse embora em paz. Agora está claro que o Senhor  o tem abençoado.

[[v1-26-30]]

^<<v1-26-30,30>>^ Então Isaque preparou um banquete, e todos eles comeram e beberam.

[[v1-26-31]]

^<<v1-26-31,31>>^ No dia seguinte eles se levantaram bem cedo e fizeram o trato, e cada um fez o seu juramento. Isaque se despediu deles, e eles foram embora como seus amigos.

[[v1-26-32]]

^<<v1-26-32,32>>^ Nesse mesmo dia os empregados de Isaque foram dar-lhe a notícia de que haviam encontrado água no poço que estavam cavando.

[[v1-26-33]]

^<<v1-26-33,33>>^ Isaque pôs nesse poço o nome de Seba, e por isso até hoje  o nome daquela cidade é Berseba .

[[v1-26-34]]

^<<v1-26-34,34>>^ Quando tinha quarenta anos, Esaú casou com Judite, filha de Beeri, e com Basemate, filha de Elom, duas moças heteias.

[[v1-26-35]]

^<<v1-26-35,35>>^ Essas duas mulheres amarguraram a vida de Isaque e de Rebeca.

'''

xref:001-genesis/001-genesis-025.adoc#v1-25-0[&#60; Capítulo Anterior] | <<v1-26-0,Topo>> | xref:001-genesis/001-genesis-027.adoc#v1-27-0[Próximo Capítulo &#62;]