include::./index.adoc[]

[[v1-47-0]]
=== Gênesis, 47
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-47-1]]

^<<v1-47-1,1>>^ Então José foi dar a notícia ao rei. Ele disse: — O meu pai e os meus irmãos vieram da terra de Canaã e estão na região de Gosém com as suas ovelhas e cabras, o seu gado e tudo o que têm.

[[v1-47-2]]

^<<v1-47-2,2>>^ Depois levou cinco dos seus irmãos e os apresentou ao rei.

[[v1-47-3]]

^<<v1-47-3,3>>^ O rei perguntou: — Qual é o trabalho de vocês? Eles responderam: — Senhor, nós somos criadores de ovelhas, como foram os nossos antepassados.

[[v1-47-4]]

^<<v1-47-4,4>>^ Viemos morar neste país porque na terra de Canaã não há pastos para os animais, e a fome lá está terrível. Por favor, deixe que a gente fique morando na região de Gosém.

[[v1-47-5]]

^<<v1-47-5,5>>^ O rei disse a José: — Agora que o seu pai e os seus irmãos vieram ficar com você,

[[v1-47-6]]

^<<v1-47-6,6>>^ a terra do Egito está às ordens deles. Dê a eles a região de Gosém, que é a melhor do país, para que fiquem morando lá. E, se na sua opinião houver entre eles homens capazes, ponha-os como chefes dos que cuidam do meu gado.

[[v1-47-7]]

^<<v1-47-7,7>>^ Depois José levou Jacó, o seu pai, e o apresentou ao rei. Jacó deu a sua bênção ao rei,

[[v1-47-8]]

^<<v1-47-8,8>>^ e este perguntou: — Qual é a sua idade?

[[v1-47-9]]

^<<v1-47-9,9>>^ Jacó respondeu: — Já estou com cento e trinta anos de idade e sempre tenho andado de um lado para outro. A minha vida tem passado rapidamente, e muitos anos foram difíceis. E eu não tenho conseguido viver tanto quanto os meus antepassados, que tiveram uma vida tão dura como a que eu tive.

[[v1-47-10]]

^<<v1-47-10,10>>^ Jacó deu a sua bênção ao rei e foi embora.

[[v1-47-11]]

^<<v1-47-11,11>>^ E José deu ao pai e aos irmãos terras na melhor região do Egito, perto da cidade de Ramessés, como o rei havia ordenado. Essas terras se tornaram propriedade deles, e eles ficaram morando ali.

[[v1-47-12]]

^<<v1-47-12,12>>^ José dava mantimentos ao pai, aos irmãos e aos parentes, conforme as necessidades de cada família.

[[v1-47-13]]

^<<v1-47-13,13>>^ Não havia alimento em lugar nenhum, e a fome aumentava cada vez mais. Os moradores do Egito e de Canaã ficaram fracos de tanto passar fome.

[[v1-47-14]]

^<<v1-47-14,14>>^ O povo comprava mantimentos, e José ajuntava todo o dinheiro e o levava para o palácio.

[[v1-47-15]]

^<<v1-47-15,15>>^ Quando acabou todo o dinheiro do Egito e de Canaã, os egípcios foram falar com José. Eles disseram: — Por favor, nos dê comida! Não nos deixe morrer só porque o nosso dinheiro acabou!

[[v1-47-16]]

^<<v1-47-16,16>>^ José respondeu: — Se vocês não têm mais dinheiro, tragam o seu gado, que eu trocarei por mantimento.

[[v1-47-17]]

^<<v1-47-17,17>>^ Os egípcios levaram a José cavalos, ovelhas, cabras, bois e jumentos, e em troca ele lhes deu mantimento durante todo aquele ano.

[[v1-47-18]]

^<<v1-47-18,18>>^ O ano passou, e no ano seguinte foram dizer a José:

[[v1-47-19]]

^<<v1-47-19,19>>^ — Senhor, não podemos esconder o fato de que o nosso dinheiro acabou e que os nossos animais agora são seus. Não temos mais nada para entregar a não ser os nossos corpos e as nossas terras. Não deixe a gente morrer. Compre a nós e as nossas terras em troca de alimentos. Seremos escravos do rei, e ele será dono das nossas terras. Dê-nos mantimento para que possamos viver e também sementes para plantarmos, e assim a terra não se tornará um deserto.

[[v1-47-20]]

^<<v1-47-20,20>>^ Então José comprou todas as terras do Egito para o rei. Todos os egípcios tiveram de vender as suas terras, pois a fome era terrível. Assim, a terra ficou sendo do rei,

[[v1-47-21]]

^<<v1-47-21,21>>^ e José fez dos egípcios escravos no país inteiro.

[[v1-47-22]]

^<<v1-47-22,22>>^ José só não comprou as terras dos sacerdotes. Eles não tiveram de vendê-las, pois o rei lhes dava certa quantidade de alimentos; e assim eles tinham o que comer.

[[v1-47-23]]

^<<v1-47-23,23>>^ Então José disse ao povo: — Agora vocês e as suas terras são do rei, pois eu os comprei para ele. Peguem aqui sementes para semearem nos campos.

[[v1-47-24]]

^<<v1-47-24,24>>^ Do que colherem, deem a quinta parte ao rei; usem as outras quatro partes para semear e para alimentar vocês, os seus filhos e as pessoas que moram com vocês.

[[v1-47-25]]

^<<v1-47-25,25>>^ Eles responderam: — O senhor salvou a nossa vida e tem sido bom para nós. Seremos escravos do rei.

[[v1-47-26]]

^<<v1-47-26,26>>^ Assim, José fez uma lei  que existe até hoje . A lei é a seguinte: em todo o Egito a quinta parte das colheitas pertence ao rei. Só as terras dos sacerdotes não ficaram para o rei.

[[v1-47-27]]

^<<v1-47-27,27>>^ Os israelitas ficaram vivendo no Egito, na região de Gosém, onde compraram terras e tiveram muitos filhos.

[[v1-47-28]]

^<<v1-47-28,28>>^ Jacó viveu dezessete anos no Egito, chegando à idade de cento e quarenta e sete anos.

[[v1-47-29]]

^<<v1-47-29,29>>^ Quando sentiu que ia morrer, Jacó mandou chamar o seu filho José e disse: — Se lhe posso pedir um favor, ponha a mão por baixo da minha coxa e jure que será fiel e honesto comigo nisto que vou pedir: não me sepulte no Egito.

[[v1-47-30]]

^<<v1-47-30,30>>^ Quando eu morrer, tire o meu corpo do Egito e me coloque na sepultura dos meus antepassados, a fim de que eu descanse com eles. José respondeu: — Eu farei o que o senhor está pedindo.

[[v1-47-31]]

^<<v1-47-31,31>>^ — Então jure — disse Jacó. José jurou, e aí Jacó se inclinou sobre a cabeceira da cama e orou.

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]