include::./index.adoc[]

[[v1-17-0]]
=== Gênesis, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-17-1]]

^<<v1-17-1,1>>^ Quando Abrão tinha noventa e nove anos, o Senhor  Deus apareceu a ele e disse: — Eu sou o Deus Todo-Poderoso. Viva uma vida de comunhão comigo e seja obediente a mim em tudo.

[[v1-17-2]]

^<<v1-17-2,2>>^ Eu farei a minha aliança  com você e lhe darei muitos descendentes.

[[v1-17-3]]

^<<v1-17-3,3>>^ Então Abrão se ajoelhou, encostou o rosto no chão, e Deus lhe disse:

[[v1-17-4]]

^<<v1-17-4,4>>^ — Eu faço com você esta aliança: prometo que você será o pai de muitas nações.

[[v1-17-5]]

^<<v1-17-5,5>>^ Daqui em diante o seu nome será Abraão e não Abrão , pois eu vou fazer com que você seja pai de muitas nações.

[[v1-17-6]]

^<<v1-17-6,6>>^ Farei com que os seus descendentes sejam muito numerosos, e alguns deles serão reis.

[[v1-17-7]]

^<<v1-17-7,7>>^ A aliança que estou fazendo para sempre com você e com os seus descendentes é a seguinte: eu serei para sempre o Deus de você e o Deus dos seus descendentes.

[[v1-17-8]]

^<<v1-17-8,8>>^ Darei a você e a eles a terra onde você está morando como estrangeiro. Toda a terra de Canaã será para sempre dos seus descendentes, e eu serei o Deus deles.

[[v1-17-9]]

^<<v1-17-9,9>>^ Deus continuou: — Você, Abraão, será fiel à minha aliança, você e os seus descendentes, para sempre.

[[v1-17-10]]

^<<v1-17-10,10>>^ Pela aliança que estou fazendo com você e com os seus descendentes, todos os homens entre vocês deverão ser circuncidados .

[[v1-17-11]]

^<<v1-17-11,11>>^ A circuncisão servirá como sinal da aliança que há entre mim e vocês.

[[v1-17-12]]

^<<v1-17-12,12>>^ De hoje em diante vocês circuncidarão todos os meninos oito dias depois de nascidos, e também os escravos que nascerem nas casas de vocês, e os que forem comprados de estrangeiros.

[[v1-17-13]]

^<<v1-17-13,13>>^ Tanto uns como outros deverão ser circuncidados, sem falta. Esse será um sinal que vai ficar no seu corpo para mostrar que a minha aliança com vocês é para sempre.

[[v1-17-14]]

^<<v1-17-14,14>>^ Quem não for circuncidado não poderá morar no meio de vocês, pois não respeitou a minha aliança.

[[v1-17-15]]

^<<v1-17-15,15>>^ Depois Deus disse a Abraão: — De hoje em diante não chame mais a sua mulher de Sarai, mas de Sara .

[[v1-17-16]]

^<<v1-17-16,16>>^ Eu a abençoarei e darei a você um filho, que nascerá dela. Sim, eu a abençoarei, e ela será mãe de nações; e haverá reis entre os seus descendentes.

[[v1-17-17]]

^<<v1-17-17,17>>^ Abraão se ajoelhou, encostou o rosto no chão e começou a rir ao pensar assim: "Por acaso um homem de cem anos pode ser pai? E será que Sara, com os seus noventa anos, poderá ter um filho?"

[[v1-17-18]]

^<<v1-17-18,18>>^ Então Abraão disse a Deus o seguinte: — Quem dera que Ismael vivesse abençoado por ti!

[[v1-17-19]]

^<<v1-17-19,19>>^ Mas Deus respondeu: — O que eu disse foi que Sara, a sua mulher, lhe dará um filho. E você o chamará de Isaque . Eu manterei a minha aliança com ele e com os seus descendentes, para sempre.

[[v1-17-20]]

^<<v1-17-20,20>>^ Também ouvi o seu pedido a respeito de Ismael; e eu o abençoarei e lhe darei muitos filhos e muitos descendentes. Ele será pai de doze príncipes, e eu farei com que os descendentes dele sejam uma grande nação.

[[v1-17-21]]

^<<v1-17-21,21>>^ Mas a minha aliança eu manterei com Isaque, o seu filho, que Sara dará à luz nesta mesma época, no ano que vem.

[[v1-17-22]]

^<<v1-17-22,22>>^ Quando acabou de falar com Abraão, Deus subiu e o deixou.

[[v1-17-23]]

^<<v1-17-23,23>>^ Naquele mesmo dia Abraão fez como Deus havia mandado. Ele circuncidou o seu filho Ismael e todos os outros homens da sua casa, incluindo os escravos nascidos na sua casa e os que tinham sido comprados de estrangeiros.

[[v1-17-24]]

^<<v1-17-24,24>>^ Abraão tinha noventa e nove anos quando foi circuncidado,

[[v1-17-25]]

^<<v1-17-25,25>>^ e o seu filho Ismael tinha treze.

[[v1-17-26]]

^<<v1-17-26,26>>^ Os dois foram circuncidados no mesmo dia.

[[v1-17-27]]

^<<v1-17-27,27>>^ E foram circuncidados também todos os escravos de Abraão, tanto os nascidos na sua casa como os que tinham sido comprados de estrangeiros.

'''

xref:001-genesis/001-genesis-016.adoc#v1-16-0[&#60; Capítulo Anterior] | <<v1-17-0,Topo>> | xref:001-genesis/001-genesis-018.adoc#v1-18-0[Próximo Capítulo &#62;]