include::./index.adoc[]

[[v1-24-0]]
=== Gênesis, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-24-1]]

^<<v1-24-1,1>>^ Abraão já estava bem velho, e o Senhor  Deus o havia abençoado em tudo.

[[v1-24-2]]

^<<v1-24-2,2>>^ Um dia ele chamou o seu empregado mais antigo, que tomava conta de tudo o que ele tinha, e disse: — Ponha a mão por baixo da minha coxa e faça um juramento.

[[v1-24-3]]

^<<v1-24-3,3>>^ Jure pelo Senhor , o Deus do céu e da terra, que você não deixará que o meu filho Isaque case com nenhuma mulher deste país de Canaã, onde estou morando.

[[v1-24-4]]

^<<v1-24-4,4>>^ Vá até a minha terra e escolha no meio dos meus parentes uma esposa para Isaque.

[[v1-24-5]]

^<<v1-24-5,5>>^ O empregado perguntou: — E o que é que eu faço se a moça não quiser vir comigo? Devo levar o seu filho de volta para a terra de onde o senhor veio?

[[v1-24-6]]

^<<v1-24-6,6>>^ Abraão respondeu: — Não! Não faça o meu filho voltar para lá, de jeito nenhum!

[[v1-24-7]]

^<<v1-24-7,7>>^ O Senhor , o Deus do céu, me tirou da casa do meu pai e da terra dos meus parentes e jurou que daria esta terra aos meus descendentes. Ele vai enviar o seu Anjo para guiá-lo, e assim você conseguirá arranjar uma mulher para o meu filho.

[[v1-24-8]]

^<<v1-24-8,8>>^ Se a moça não quiser vir, você ficará livre deste juramento. Porém não leve o meu filho de volta para lá, de jeito nenhum.

[[v1-24-9]]

^<<v1-24-9,9>>^ Então o empregado pôs a mão por baixo da coxa de Abraão e jurou que faria o que ele havia ordenado.

[[v1-24-10]]

^<<v1-24-10,10>>^ Em seguida o empregado pegou dez camelos de Abraão e uma porção de presentes e foi até a cidade onde Naor havia morado, na Mesopotâmia.

[[v1-24-11]]

^<<v1-24-11,11>>^ Quando o empregado chegou, fez os camelos se ajoelharem perto do poço, fora da cidade. Era de tardinha, a hora em que as mulheres vinham buscar água.

[[v1-24-12]]

^<<v1-24-12,12>>^ Aí ele orou assim: — Ó Senhor , Deus do meu patrão Abraão, faze com que tudo dê certo e sê bondoso para o meu patrão.

[[v1-24-13]]

^<<v1-24-13,13>>^ Eu estou aqui perto do poço aonde as moças da cidade vêm para tirar água.

[[v1-24-14]]

^<<v1-24-14,14>>^ Vou dizer a uma delas: "Por favor, abaixe o seu pote para que eu beba um pouco de água." Se ela disser assim: "Beba, e eu vou dar água também para os seus camelos", que seja essa a moça que escolheste para o teu servo  Isaque. Se isso acontecer, ficarei sabendo que foste bondoso para o meu patrão.

[[v1-24-15]]

^<<v1-24-15,15>>^ Ele nem havia acabado a oração, quando Rebeca veio, carregando o seu pote no ombro. Ela era filha de Betuel, que era filho de Milca e de Naor, o irmão de Abraão.

[[v1-24-16]]

^<<v1-24-16,16>>^ Rebeca era uma linda moça, ainda virgem; nenhum homem havia tocado nela. Ela desceu até o poço, encheu o seu pote e subiu.

[[v1-24-17]]

^<<v1-24-17,17>>^ Então o empregado de Abraão foi correndo se encontrar com ela e disse: — Por favor, deixe que eu beba um pouco da água do seu pote.

[[v1-24-18]]

^<<v1-24-18,18>>^ — O senhor pode beber — respondeu ela. E rapidamente abaixou o pote e o segurou enquanto ele bebia.

[[v1-24-19]]

^<<v1-24-19,19>>^ Depois de lhe dar de beber, a moça disse: — Vou tirar água também para os seus camelos e lhes darei de beber o quanto quiserem.

[[v1-24-20]]

^<<v1-24-20,20>>^ Rapidamente ela despejou a água no bebedouro e correu várias vezes ao poço a fim de tirar água para todos os camelos.

[[v1-24-21]]

^<<v1-24-21,21>>^ Enquanto isso o homem, sem dizer nada, ficou observando a moça para saber se o Senhor  Deus havia ou não abençoado a sua viagem.

[[v1-24-22]]

^<<v1-24-22,22>>^ Quando os camelos acabaram de beber, o homem pegou uma argola de ouro, que pesava seis gramas, e colocou no nariz dela. E também lhe deu duas pulseiras de ouro, que pesavam mais de cem gramas.

[[v1-24-23]]

^<<v1-24-23,23>>^ Em seguida perguntou: — Por favor, diga quem é o seu pai. Será que na casa dele há lugar para os meus homens e eu passarmos a noite?

[[v1-24-24]]

^<<v1-24-24,24>>^ Ela respondeu: — Eu sou filha de Betuel, filho de Milca e de Naor.

[[v1-24-25]]

^<<v1-24-25,25>>^ Na nossa casa há lugar para dormir e também bastante palha e capim para os camelos.

[[v1-24-26]]

^<<v1-24-26,26>>^ Então o homem se ajoelhou e adorou a Deus, o Senhor .

[[v1-24-27]]

^<<v1-24-27,27>>^ Ele disse: — Bendito seja o Senhor , o Deus de Abraão, o meu patrão! Pois foi fiel e bondoso com ele, guiando-me diretamente até a casa dos seus parentes.

[[v1-24-28]]

^<<v1-24-28,28>>^ A moça foi correndo para a casa da sua mãe e contou o que havia acontecido.

[[v1-24-29]]

^<<v1-24-29,29>>^ Rebeca tinha um irmão chamado Labão, o qual viu a argola no nariz da irmã e as pulseiras nos seus braços e a ouviu contar o que o homem tinha dito para ela. Labão saiu correndo e foi buscar o empregado de Abraão, que havia ficado de pé, ao lado dos camelos, ali perto do poço.

[[v1-24-30]]

^<<v1-24-30,30>>^ Rebeca tinha um irmão chamado Labão, o qual viu a argola no nariz da irmã e as pulseiras nos seus braços e a ouviu contar o que o homem tinha dito para ela. Labão saiu correndo e foi buscar o empregado de Abraão, que havia ficado de pé, ao lado dos camelos, ali perto do poço.

[[v1-24-31]]

^<<v1-24-31,31>>^ Labão disse: — Venha comigo, homem abençoado por Deus, o Senhor . Por que você está aí fora? Já preparei a casa e também o lugar para os camelos.

[[v1-24-32]]

^<<v1-24-32,32>>^ Então o homem entrou na casa. Labão tirou a carga dos camelos e lhes deu palha e capim. Depois trouxe água para que o empregado de Abraão e os seus companheiros lavassem os pés.

[[v1-24-33]]

^<<v1-24-33,33>>^ Quando trouxeram a comida, o homem disse: — Eu não vou comer enquanto não disser o que tenho para dizer. — Fale — disse Labão.

[[v1-24-34]]

^<<v1-24-34,34>>^ Então ele disse o seguinte: — Eu sou empregado de Abraão.

[[v1-24-35]]

^<<v1-24-35,35>>^ O Senhor  Deus abençoou muito o meu patrão, e ele ficou rico. O Senhor  lhe deu rebanhos de ovelhas e cabras, gado, prata, ouro, escravos e escravas, camelos e jumentos.

[[v1-24-36]]

^<<v1-24-36,36>>^ Sara, a sua mulher, mesmo depois de velha, deu um filho ao meu patrão, e o filho herdará tudo o que o pai tem.

[[v1-24-37]]

^<<v1-24-37,37>>^ O meu patrão me fez jurar que eu faria o que ele ordenasse e me disse: "Não deixe que o meu filho case com nenhuma mulher deste país de Canaã, onde estou morando.

[[v1-24-38]]

^<<v1-24-38,38>>^ Vá até o lugar onde mora a família do meu pai e no meio dos meus parentes escolha uma mulher para ele."

[[v1-24-39]]

^<<v1-24-39,39>>^ Então eu lhe perguntei: "E o que é que eu faço se a moça não quiser vir comigo?"

[[v1-24-40]]

^<<v1-24-40,40>>^ Ele me respondeu: "Eu tenho obedecido fielmente a Deus, o Senhor . Ele enviará o seu Anjo para estar com você, e tudo dará certo. No meio da minha gente, na família do meu pai, você escolherá uma mulher para o meu filho.

[[v1-24-41]]

^<<v1-24-41,41>>^ Se você falar com os meus parentes, e eles não quiserem dar a moça, então você ficará livre do juramento que me fez."

[[v1-24-42]]

^<<v1-24-42,42>>^ — E foi assim que hoje cheguei ao poço e disse a Deus o seguinte: "Ó Senhor , ó Deus de Abraão, o meu patrão, eu peço que aquilo que vou fazer dê certo.

[[v1-24-43]]

^<<v1-24-43,43>>^ Eu estou aqui ao lado do poço. Quando uma moça vier tirar água, eu vou pedir que me dê de beber da água do seu pote.

[[v1-24-44]]

^<<v1-24-44,44>>^ Se ela concordar e também se oferecer para tirar água para os meus camelos, que seja essa a que escolheste para ser mulher do filho do meu patrão."

[[v1-24-45]]

^<<v1-24-45,45>>^ Eu nem havia acabado de fazer essa oração em silêncio, quando Rebeca veio com um pote no ombro, desceu até o poço e tirou água. Aí eu disse: "Dê-me um pouco de água, por favor."

[[v1-24-46]]

^<<v1-24-46,46>>^ Ela abaixou depressa o seu pote e disse: "Pode beber, e vou dar de beber também aos seus camelos." Então eu bebi, e ela deu água também aos camelos.

[[v1-24-47]]

^<<v1-24-47,47>>^ Em seguida perguntei: "Quem é o seu pai?" Ela respondeu: "Eu sou filha de Betuel, filho de Milca e de Naor." Então coloquei uma argola no nariz dela e duas pulseiras nos seus braços.

[[v1-24-48]]

^<<v1-24-48,48>>^ Eu me ajoelhei e adorei a Deus. E louvei o Senhor , o Deus de Abraão, o meu patrão, que me guiou diretamente aos seus parentes a fim de que eu levasse a filha do irmão do meu patrão para o seu filho.

[[v1-24-49]]

^<<v1-24-49,49>>^ Agora, digam se vocês vão ser bondosos e sinceros com o meu patrão; se não, digam também, para que eu resolva o que fazer.

[[v1-24-50]]

^<<v1-24-50,50>>^ Labão e Betuel responderam: — Tudo isso vem de Deus, o Senhor , e por isso não podemos dizer nada, nem a favor nem contra.

[[v1-24-51]]

^<<v1-24-51,51>>^ Aqui está Rebeca; leve-a com você. Que ela seja a mulher do filho do seu patrão, como o Senhor  Deus já disse.

[[v1-24-52]]

^<<v1-24-52,52>>^ Quando o empregado de Abraão ouviu essas palavras, ajoelhou-se, encostou o rosto no chão e adorou a Deus, o Senhor .

[[v1-24-53]]

^<<v1-24-53,53>>^ Em seguida pegou vários objetos de prata e de ouro e vestidos e os deu a Rebeca. E também deu presentes caros ao irmão e à mãe dela.

[[v1-24-54]]

^<<v1-24-54,54>>^ Então ele e os seus companheiros comeram e beberam, e passaram a noite ali. No outro dia de manhã, quando se levantaram, o empregado disse: — Deixem que eu volte para a casa do meu patrão.

[[v1-24-55]]

^<<v1-24-55,55>>^ Mas o irmão e a mãe de Rebeca disseram: — É melhor que ela fique com a gente alguns dias, talvez uns dez, e depois poderá ir.

[[v1-24-56]]

^<<v1-24-56,56>>^ Mas o empregado respondeu: — Não me façam ficar aqui. O Senhor  Deus fez com que a minha viagem desse certo; deixem que eu volte para a casa do meu patrão.

[[v1-24-57]]

^<<v1-24-57,57>>^ Então eles disseram: — Vamos chamar Rebeca para ver o que ela diz.

[[v1-24-58]]

^<<v1-24-58,58>>^ Eles chamaram a moça e lhe perguntaram: — Você quer ir com este homem? — Quero — respondeu ela.

[[v1-24-59]]

^<<v1-24-59,59>>^ Aí deixaram que Rebeca e a mulher que havia sido sua babá fossem com o empregado de Abraão e os seus companheiros.

[[v1-24-60]]

^<<v1-24-60,60>>^ E abençoaram Rebeca, dizendo: "Que você, nossa irmã, seja mãe de milhões! Que os seus descendentes conquistem as cidades dos seus inimigos!"

[[v1-24-61]]

^<<v1-24-61,61>>^ Então Rebeca e as suas empregadas se prepararam, montaram os camelos e seguiram o empregado de Abraão. E assim eles foram embora.

[[v1-24-62]]

^<<v1-24-62,62>>^ Isaque tinha vindo ao deserto onde ficava o "Poço Daquele que Vive e Me Vê", pois morava no sul de Canaã.

[[v1-24-63]]

^<<v1-24-63,63>>^ Ele havia saído à tardinha para dar um passeio pelo campo, quando viu que vinham vindo camelos.

[[v1-24-64]]

^<<v1-24-64,64>>^ Rebeca também olhou e, quando viu Isaque, desceu do camelo

[[v1-24-65]]

^<<v1-24-65,65>>^ e perguntou ao empregado: — Quem é aquele homem que vem andando pelo campo na nossa direção? — É o meu patrão — respondeu ele. Aí ela pegou o véu e cobriu o rosto.

[[v1-24-66]]

^<<v1-24-66,66>>^ O empregado contou a Isaque tudo o que havia feito.

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]