include::./index.adoc[]

[[v1-34-0]]
=== Gênesis, 34
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-34-1]]

^<<v1-34-1,1>>^ Certa vez Dina, a filha de Jacó e de Leia, foi fazer uma visita a algumas moças daquele lugar.

[[v1-34-2]]

^<<v1-34-2,2>>^ Hamor, o heveu, que era chefe daquela região, tinha um filho chamado Siquém. Este viu Dina, pegou-a e a forçou a ter relações com ele.

[[v1-34-3]]

^<<v1-34-3,3>>^ E ele a achou tão atraente, que se apaixonou por ela e procurou fazer com que ela o amasse.

[[v1-34-4]]

^<<v1-34-4,4>>^ Depois disse ao seu pai: — Peça esta moça em casamento para mim.

[[v1-34-5]]

^<<v1-34-5,5>>^ Jacó ficou sabendo que Siquém havia desonrado a sua filha Dina. Porém, como os seus filhos estavam no campo com o gado, não disse nada até que eles voltaram para casa.

[[v1-34-6]]

^<<v1-34-6,6>>^ Enquanto isso, Hamor, o pai de Siquém, foi falar com Jacó.

[[v1-34-7]]

^<<v1-34-7,7>>^ Quando os filhos de Jacó chegaram do campo e souberam do caso, ficaram indignados e furiosos, pois Siquém havia feito uma coisa vergonhosa em Israel, desonrando a filha de Jacó. Isso era uma coisa que não se devia fazer.

[[v1-34-8]]

^<<v1-34-8,8>>^ Mas Hamor lhes disse: — O meu filho Siquém está apaixonado pela filha de vocês. Eu peço que vocês deixem que ela case com ele.

[[v1-34-9]]

^<<v1-34-9,9>>^ Fiquemos parentes; nós casaremos com as filhas de vocês, e vocês casarão com as nossas.

[[v1-34-10]]

^<<v1-34-10,10>>^ Fiquem aqui com a gente, morando na nossa região. Comprem terras onde quiserem e façam negócios por aqui.

[[v1-34-11]]

^<<v1-34-11,11>>^ Depois Siquém disse ao pai e aos irmãos de Dina: — Façam este favor para mim, e eu lhes darei o que quiserem.

[[v1-34-12]]

^<<v1-34-12,12>>^ Peçam os presentes que quiserem e digam quanto querem que eu pague pela moça, mas deixem que ela case comigo.

[[v1-34-13]]

^<<v1-34-13,13>>^ Como Siquém havia desonrado a irmã deles, os filhos de Jacó foram falsos na resposta que deram a ele e ao seu pai Hamor.

[[v1-34-14]]

^<<v1-34-14,14>>^ Eles disseram assim: — Não podemos deixar que a nossa irmã case com um homem que não tenha sido circuncidado , pois isso seria uma vergonha para nós.

[[v1-34-15]]

^<<v1-34-15,15>>^ Só podemos aceitar com esta condição: que vocês fiquem como nós, quer dizer, que todos os seus homens sejam circuncidados.

[[v1-34-16]]

^<<v1-34-16,16>>^ Aí, sim, vocês poderão casar com as nossas filhas, e nós casaremos com as filhas de vocês. Nós viveremos no meio de vocês, e seremos todos um povo só.

[[v1-34-17]]

^<<v1-34-17,17>>^ Mas, se vocês não aceitarem a nossa condição e não quiserem ser circuncidados, nós iremos embora e levaremos a nossa irmã.

[[v1-34-18]]

^<<v1-34-18,18>>^ Hamor e o seu filho Siquém concordaram com a condição.

[[v1-34-19]]

^<<v1-34-19,19>>^ Sem perda de tempo, o moço foi circuncidado, pois estava apaixonado pela filha de Jacó. E Siquém era a pessoa mais respeitada na família do seu pai.

[[v1-34-20]]

^<<v1-34-20,20>>^ Depois Hamor e o seu filho Siquém foram até o portão da cidade, onde eram tratados os negócios, e disseram aos moradores da cidade:

[[v1-34-21]]

^<<v1-34-21,21>>^ — Essa gente é amiga. Vamos deixar que eles fiquem morando e negociando aqui, pois há terras que chegam para eles. Nós poderemos casar com as filhas deles, e eles poderão casar com as nossas.

[[v1-34-22]]

^<<v1-34-22,22>>^ Mas eles só concordam em viver entre nós e se tornar um só povo com a gente se aceitarmos esta condição: todos os nossos homens precisam ser circuncidados, como eles são.

[[v1-34-23]]

^<<v1-34-23,23>>^ E será que não ficaremos com todo o gado deles e com tudo o que eles têm? É só aceitarmos a condição, e eles ficarão morando entre nós.

[[v1-34-24]]

^<<v1-34-24,24>>^ Todos os homens maiores de idade concordaram com Hamor e com o seu filho Siquém e foram circuncidados.

[[v1-34-25]]

^<<v1-34-25,25>>^ Três dias depois, quando os homens sentiam fortes dores, dois filhos de Jacó, Simeão e Levi, irmãos de Dina, pegaram as suas espadas, entraram na cidade sem ninguém notar e mataram todos os homens.

[[v1-34-26]]

^<<v1-34-26,26>>^ E Hamor e Siquém também foram mortos. Em seguida Simeão e Levi tiraram Dina da casa de Siquém e saíram.

[[v1-34-27]]

^<<v1-34-27,27>>^ Depois da matança os outros filhos de Jacó roubaram as coisas de valor que havia na cidade para se vingar da desonra da sua irmã.

[[v1-34-28]]

^<<v1-34-28,28>>^ Eles levaram as ovelhas e as cabras, o gado, os jumentos e tudo o que havia na cidade e no campo.

[[v1-34-29]]

^<<v1-34-29,29>>^ Tiraram das casas todas as coisas de valor e levaram como prisioneiras as mulheres e as crianças.

[[v1-34-30]]

^<<v1-34-30,30>>^ Então Jacó disse a Simeão e a Levi: — Vocês me puseram numa situação difícil. Agora os cananeus, os perizeus e todos os moradores destas terras vão ficar com ódio de mim. Eu não tenho muitos homens. Se eles se ajuntarem e me atacarem, a minha família inteira será morta.

[[v1-34-31]]

^<<v1-34-31,31>>^ Mas eles responderam: — Nós não podíamos deixar que a nossa irmã fosse tratada como uma prostituta.

'''

xref:001-genesis/001-genesis-033.adoc#v1-33-0[&#60; Capítulo Anterior] | <<v1-34-0,Topo>> | xref:001-genesis/001-genesis-035.adoc#v1-35-0[Próximo Capítulo &#62;]