include::./index.adoc[]

[[v1-2-0]]
=== Gênesis, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-2-1]]

^<<v1-2-1,1>>^ Assim terminou a criação do céu, e da terra, e de tudo o que há neles.

[[v1-2-2]]

^<<v1-2-2,2>>^ No sétimo dia Deus acabou de fazer todas as coisas e descansou de todo o trabalho que havia feito.

[[v1-2-3]]

^<<v1-2-3,3>>^ Então abençoou o sétimo dia e o separou como um dia sagrado, pois nesse dia ele acabou de fazer todas as coisas e descansou.

[[v1-2-4]]

^<<v1-2-4,4>>^ E foi assim que o céu e a terra foram criados. Quando o Senhor  Deus fez o céu e a terra,

[[v1-2-5]]

^<<v1-2-5,5>>^ não haviam brotado nem capim nem plantas, pois o Senhor  ainda não tinha mandado chuvas, e não havia ninguém para cultivar a terra.

[[v1-2-6]]

^<<v1-2-6,6>>^ Mas da terra saía uma corrente de água que regava o chão.

[[v1-2-7]]

^<<v1-2-7,7>>^ Então, do pó da terra, o Senhor  formou o ser humano . O Senhor  soprou no nariz dele uma respiração de vida, e assim ele se tornou um ser vivo.

[[v1-2-8]]

^<<v1-2-8,8>>^ Depois o Senhor  Deus plantou um jardim na região do Éden, no Leste, e ali pôs o ser humano que ele havia formado.

[[v1-2-9]]

^<<v1-2-9,9>>^ O Senhor  fez com que ali crescessem árvores lindas de todos os tipos, que davam frutas boas de se comer. No meio do jardim ficava a árvore que dá vida e também a árvore que dá o conhecimento do bem e do mal.

[[v1-2-10]]

^<<v1-2-10,10>>^ No Éden nascia um rio que regava o jardim e que, saindo dali, se dividia, formando quatro rios.

[[v1-2-11]]

^<<v1-2-11,11>>^ O primeiro é o Pisom, que rodeia a região de Havilá, onde há ouro.

[[v1-2-12]]

^<<v1-2-12,12>>^ O ouro dessa região é puro, e ali também há um perfume raro e pedras preciosas.

[[v1-2-13]]

^<<v1-2-13,13>>^ O segundo rio se chama Giom; ele dá volta por toda a região de Cuche.

[[v1-2-14]]

^<<v1-2-14,14>>^ O terceiro rio é o Tigre, que passa a leste da Assíria. E o quarto rio é o Eufrates.

[[v1-2-15]]

^<<v1-2-15,15>>^ Então o Senhor  Deus pôs o homem no jardim do Éden, para cuidar dele e nele fazer plantações.

[[v1-2-16]]

^<<v1-2-16,16>>^ E o Senhor  deu ao homem a seguinte ordem: — Você pode comer as frutas de qualquer árvore do jardim,

[[v1-2-17]]

^<<v1-2-17,17>>^ menos da árvore que dá o conhecimento do bem e do mal. Não coma a fruta dessa árvore; pois, no dia em que você a comer, certamente morrerá.

[[v1-2-18]]

^<<v1-2-18,18>>^ Depois o Senhor  disse: — Não é bom que o homem viva sozinho. Vou fazer para ele alguém que o ajude como se fosse a sua outra metade.

[[v1-2-19]]

^<<v1-2-19,19>>^ Depois que o Senhor  Deus formou da terra todos os animais selvagens e todas as aves, ele os levou ao homem para que pusesse nome neles. E eles ficaram com o nome que o homem lhes deu.

[[v1-2-20]]

^<<v1-2-20,20>>^ Ele pôs nomes nas aves e em todos os animais domésticos e selvagens. Mas para Adão não se achava uma ajudadora que fosse como a sua outra metade.

[[v1-2-21]]

^<<v1-2-21,21>>^ Então o Senhor  Deus fez com que o homem caísse num sono profundo. Enquanto ele dormia, Deus tirou uma das suas costelas e fechou a carne naquele lugar.

[[v1-2-22]]

^<<v1-2-22,22>>^ Dessa costela o Senhor  formou uma mulher e a levou ao homem.

[[v1-2-23]]

^<<v1-2-23,23>>^ Então o homem disse: "Agora sim! Esta é carne da minha carne e osso dos meus ossos. Ela será chamada de ‘mulher’ porque Deus a tirou do homem ."

[[v1-2-24]]

^<<v1-2-24,24>>^ É por isso que o homem deixa o seu pai e a sua mãe para se unir com a sua mulher, e os dois se tornam uma só pessoa.

[[v1-2-25]]

^<<v1-2-25,25>>^ Tanto o homem como a sua mulher estavam nus, mas não sentiam vergonha.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]