include::./index.adoc[]

[[v1-21-0]]
=== Gênesis, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-21-1]]

^<<v1-21-1,1>>^ De acordo com a sua promessa, o Senhor  Deus abençoou Sara.

[[v1-21-2]]

^<<v1-21-2,2>>^ Ela ficou grávida e, na velhice de Abraão, lhe deu um filho. O menino nasceu no tempo que Deus havia marcado,

[[v1-21-3]]

^<<v1-21-3,3>>^ e Abraão pôs nele o nome de Isaque.

[[v1-21-4]]

^<<v1-21-4,4>>^ Quando Isaque tinha oito dias, Abraão o circuncidou , como Deus havia mandado.

[[v1-21-5]]

^<<v1-21-5,5>>^ Quando Isaque nasceu, Abraão tinha cem anos.

[[v1-21-6]]

^<<v1-21-6,6>>^ Então Sara disse: — Deus me deu motivo para rir . E todos os que ouvirem essa história vão rir comigo.

[[v1-21-7]]

^<<v1-21-7,7>>^ E disse também: — Quem diria a Abraão que Sara daria de mamar? No entanto, apesar de ele estar velho, eu lhe dei um filho.

[[v1-21-8]]

^<<v1-21-8,8>>^ O menino cresceu e foi desmamado. E, no dia em que o menino foi desmamado, Abraão deu uma grande festa.

[[v1-21-9]]

^<<v1-21-9,9>>^ Certo dia Ismael, o filho de Abraão e da egípcia Agar, estava brincando com Isaque, o filho de Sara.

[[v1-21-10]]

^<<v1-21-10,10>>^ Quando Sara viu isso, disse a Abraão: — Mande embora essa escrava e o filho dela, pois o filho dessa escrava não será herdeiro junto com Isaque, o meu filho.

[[v1-21-11]]

^<<v1-21-11,11>>^ Abraão ficou muito preocupado com isso, pois Ismael também era seu filho.

[[v1-21-12]]

^<<v1-21-12,12>>^ Mas Deus disse: — Abraão, não se preocupe com o menino, nem com a sua escrava. Faça tudo o que Sara disser, pois você terá descendentes por meio de Isaque.

[[v1-21-13]]

^<<v1-21-13,13>>^ O filho da escrava é seu filho também, e por isso farei com que os descendentes dele sejam uma grande nação.

[[v1-21-14]]

^<<v1-21-14,14>>^ No dia seguinte Abraão se levantou de madrugada e deu para Agar comida e um odre  cheio de água. Pôs o menino nos ombros dela e mandou que fosse embora. E Agar foi embora, andando sem direção pelo deserto de Berseba.

[[v1-21-15]]

^<<v1-21-15,15>>^ Quando acabou a água do odre, ela deixou o menino debaixo de uma arvorezinha

[[v1-21-16]]

^<<v1-21-16,16>>^ e foi sentar-se a uns cem metros dali. Ela estava pensando: "Não suporto ver o meu filho morrer." Ela ficou ali sentada, e o menino começou a chorar.

[[v1-21-17]]

^<<v1-21-17,17>>^ Deus ouviu o choro do menino; e, lá do céu, o Anjo de Deus chamou Agar e disse: — Por que é que você está preocupada, Agar? Não tenha medo, pois Deus ouviu o choro do menino aí onde ele está.

[[v1-21-18]]

^<<v1-21-18,18>>^ Vamos! Levante o menino e pegue-o pela mão. Eu farei dos seus descendentes uma grande nação.

[[v1-21-19]]

^<<v1-21-19,19>>^ Então Deus abriu os olhos de Agar, e ela viu um poço. Ela foi, encheu o odre de água e deu para Ismael beber.

[[v1-21-20]]

^<<v1-21-20,20>>^ Protegido por Deus, o menino cresceu. Ismael ficou morando no deserto de Parã e se tornou um bom atirador de flechas.

[[v1-21-21]]

^<<v1-21-21,21>>^ E a sua mãe arranjou uma mulher egípcia para ele.

[[v1-21-22]]

^<<v1-21-22,22>>^ Por esse tempo Abimeleque foi conversar com Abraão. Ficol, comandante do seu exército, foi com ele. Abimeleque disse a Abraão: — Deus está com você em tudo o que você faz.

[[v1-21-23]]

^<<v1-21-23,23>>^ Portanto, aqui neste lugar, jure por Deus que não vai enganar nem a mim, nem aos meus filhos, nem aos meus descendentes. Eu tenho sido sincero com você; por isso prometa que será sincero comigo e fiel a esta terra em que está morando.

[[v1-21-24]]

^<<v1-21-24,24>>^ — Eu juro — disse Abraão.

[[v1-21-25]]

^<<v1-21-25,25>>^ Abraão fez uma reclamação a Abimeleque por causa de um poço que os empregados de Abimeleque haviam tomado à força.

[[v1-21-26]]

^<<v1-21-26,26>>^ Abimeleque explicou: — Não sei quem fez isso. Você nunca me falou nada, e esta é a primeira vez que estou ouvindo falar desse assunto.

[[v1-21-27]]

^<<v1-21-27,27>>^ Aí Abraão pegou algumas ovelhas e alguns bois e deu a Abimeleque, e os dois fizeram um trato.

[[v1-21-28]]

^<<v1-21-28,28>>^ Abraão separou sete ovelhinhas do seu rebanho,

[[v1-21-29]]

^<<v1-21-29,29>>^ e Abimeleque perguntou: — Por que você separou estas sete ovelhinhas?

[[v1-21-30]]

^<<v1-21-30,30>>^ Abraão respondeu: — Elas são um presente para você. Ao receber estas sete ovelhinhas, você estará concordando que fui eu quem cavou este poço.

[[v1-21-31]]

^<<v1-21-31,31>>^ Por isso aquele lugar ficou sendo chamado de Berseba , pois ali os dois fizeram um juramento.

[[v1-21-32]]

^<<v1-21-32,32>>^ Depois de fazerem esse trato em Berseba, Abimeleque e Ficol voltaram para a Filisteia.

[[v1-21-33]]

^<<v1-21-33,33>>^ Abraão plantou uma árvore em Berseba e ali adorou o Senhor , o Deus Eterno.

[[v1-21-34]]

^<<v1-21-34,34>>^ E Abraão ficou morando muito tempo na Filisteia.

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]