include::./index.adoc[]

[[v1-46-0]]
=== Gênesis, 46
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-46-1]]

^<<v1-46-1,1>>^ Jacó partiu com tudo o que tinha e foi até Berseba, onde ofereceu sacrifícios  ao Deus de Isaque, o seu pai.

[[v1-46-2]]

^<<v1-46-2,2>>^ Naquela noite Deus falou com ele numa visão e o chamou assim: — Jacó, Jacó! — Eu estou aqui — respondeu ele.

[[v1-46-3]]

^<<v1-46-3,3>>^ Deus disse: — Eu sou Deus, o Deus do seu pai. Não tenha medo de ir para o Egito, pois ali eu farei com que os seus descendentes se tornem uma grande nação.

[[v1-46-4]]

^<<v1-46-4,4>>^ Eu irei para o Egito com você e trarei os seus descendentes de volta para esta terra. E, quando você morrer, José estará ao seu lado.

[[v1-46-5]]

^<<v1-46-5,5>>^ Então Jacó partiu de Berseba. Nas carretas que o rei do Egito havia mandado, os filhos de Jacó levaram o pai, as esposas deles e os seus filhos pequenos.

[[v1-46-6]]

^<<v1-46-6,6>>^ Jacó e todos os seus foram para o Egito, levando o seu gado e todas as coisas que haviam conseguido em Canaã.

[[v1-46-7]]

^<<v1-46-7,7>>^ Jacó levou consigo todos os seus descendentes, isto é, filhos e filhas, netos e netas.

[[v1-46-8]]

^<<v1-46-8,8>>^ Os israelitas que foram para o Egito, isto é, Jacó e os seus descendentes, são os seguintes: Rúben, o filho mais velho de Jacó,

[[v1-46-9]]

^<<v1-46-9,9>>^ e os filhos de Rúben: Enoque, Palu, Hezrom e Carmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ Simeão e os seus filhos Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, que era filho de uma mulher de Canaã.

[[v1-46-11]]

^<<v1-46-11,11>>^ Levi e os seus filhos Gérson, Coate e Merari.

[[v1-46-12]]

^<<v1-46-12,12>>^ Judá e os seus filhos Selá, Peres e Zera (Os outros dois filhos, Er e Onã, haviam morrido em Canaã.). Os filhos de Peres foram Hezrom e Hamul.

[[v1-46-13]]

^<<v1-46-13,13>>^ Issacar e os seus filhos Tolá, Puá, Jasube e Sinrom.

[[v1-46-14]]

^<<v1-46-14,14>>^ Zebulom e os seus filhos Serede, Elom e Jaleel.

[[v1-46-15]]

^<<v1-46-15,15>>^ Esses foram os filhos que Leia deu a Jacó na Mesopotâmia, além da sua filha Dina. Os descendentes de Jacó e Leia eram trinta e três.

[[v1-46-16]]

^<<v1-46-16,16>>^ Gade e os seus filhos Zifião, Hagui, Suni, Esbom, Eri, Arodi e Areli.

[[v1-46-17]]

^<<v1-46-17,17>>^ Aser e os seus filhos Imna, Isva, Isvi e Berias e a irmã deles, que se chamava Sera. Os filhos de Berias eram Héber e Malquiel.

[[v1-46-18]]

^<<v1-46-18,18>>^ Esses dezesseis foram os descendentes de Jacó e Zilpa, a escrava que Labão deu à sua filha Leia.

[[v1-46-19]]

^<<v1-46-19,19>>^ Raquel, mulher de Jacó, lhe tinha dado dois filhos: José e Benjamim.

[[v1-46-20]]

^<<v1-46-20,20>>^ Os filhos de José com Asenate foram Manassés e Efraim, que nasceram no Egito. Asenate era filha de Potífera, sacerdote da cidade de Heliópolis.

[[v1-46-21]]

^<<v1-46-21,21>>^ Os filhos de Benjamim foram Belá, Bequer, Asbel, Gera, Naamã, Eí, Rôs, Mupim, Hupim e Arde.

[[v1-46-22]]

^<<v1-46-22,22>>^ Esses catorze foram os descendentes de Jacó e Raquel.

[[v1-46-23]]

^<<v1-46-23,23>>^ Dã e o seu filho Husim.

[[v1-46-24]]

^<<v1-46-24,24>>^ Naftali e os seus filhos Jazeel, Guni, Jezer e Silém.

[[v1-46-25]]

^<<v1-46-25,25>>^ Esses sete foram os descendentes de Jacó e Bila, a escrava que Labão deu à sua filha Raquel.

[[v1-46-26]]

^<<v1-46-26,26>>^ Ao todo foram para o Egito sessenta e seis descendentes diretos de Jacó, sem contar as mulheres dos seus filhos.

[[v1-46-27]]

^<<v1-46-27,27>>^ Os dois filhos de José nasceram no Egito. Assim, foi de setenta o total de pessoas da família de Jacó que foram para o Egito.

[[v1-46-28]]

^<<v1-46-28,28>>^ Jacó mandou que Judá fosse na frente para pedir a José que viesse encontrá-los em Gosém. Quando eles chegaram,

[[v1-46-29]]

^<<v1-46-29,29>>^ José mandou aprontar o seu carro e foi para Gosém a fim de se encontrar com o pai. Quando se encontraram, José o abraçou e chorou abraçado com ele por muito tempo.

[[v1-46-30]]

^<<v1-46-30,30>>^ Então Jacó disse: — Já posso morrer, agora que já vi você e sei que está vivo!

[[v1-46-31]]

^<<v1-46-31,31>>^ Depois José disse aos irmãos e à família do pai: — Eu vou falar com o rei do Egito e vou lhe dar a notícia de que os meus irmãos e os parentes do meu pai, que moravam em Canaã, vieram para ficar comigo.

[[v1-46-32]]

^<<v1-46-32,32>>^ Vou dizer ao rei que vocês são criadores de ovelhas e cabras e cuidam de gado. Direi que trouxeram as suas ovelhas, o gado e tudo o que têm.

[[v1-46-33]]

^<<v1-46-33,33>>^ Quando o rei lhes perguntar qual é a profissão de vocês,

[[v1-46-34]]

^<<v1-46-34,34>>^ digam que a vida inteira vocês têm sido criadores de ovelhas, como foram os seus antepassados. Assim, vocês poderão ficar morando na região de Gosém, pois os egípcios detestam os pastores de ovelhas.

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]