include::./index.adoc[]

[[v1-50-0]]
=== Gênesis, 50
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-50-1]]

^<<v1-50-1,1>>^ José se atirou sobre o pai, chorando e beijando o seu rosto.

[[v1-50-2]]

^<<v1-50-2,2>>^ Ele deu ordem aos médicos que estavam ao seu serviço para embalsamarem o corpo do seu pai, e assim eles fizeram.

[[v1-50-3]]

^<<v1-50-3,3>>^ Gastaram quarenta dias para fazer isso, o tempo normal para embalsamar um corpo. E os egípcios ficaram de luto setenta dias.

[[v1-50-4]]

^<<v1-50-4,4>>^ Quando passou o tempo do luto, José falou com os altos funcionários do palácio do rei do Egito. Ele disse: — Façam o favor de levar ao rei a seguinte mensagem:

[[v1-50-5]]

^<<v1-50-5,5>>^ "Quando o meu pai estava para morrer, ele me fez jurar que eu o sepultaria no túmulo que ele mesmo preparou no país de Canaã. Por favor, deixe-me ir sepultar o meu pai, que depois eu voltarei."

[[v1-50-6]]

^<<v1-50-6,6>>^ O rei respondeu: — Vá e sepulte o seu pai, como ele fez você jurar que faria.

[[v1-50-7]]

^<<v1-50-7,7>>^ E assim José foi sepultar o seu pai. Com ele foram as autoridades ligadas ao rei, os altos funcionários do palácio e todos os líderes do Egito.

[[v1-50-8]]

^<<v1-50-8,8>>^ Foram também as famílias de José, dos seus irmãos e de Jacó. Deixaram na terra de Gosém somente as crianças pequenas, as ovelhas, as cabras e o gado.

[[v1-50-9]]

^<<v1-50-9,9>>^ Também foram homens a cavalo e em carretas, de modo que o grupo era muito grande.

[[v1-50-10]]

^<<v1-50-10,10>>^ Quando chegaram a Atade, que fica a leste do rio Jordão, fizeram uma cerimônia de sepultamento num terreiro onde o trigo é malhado. Ali choraram muito alto durante sete dias.

[[v1-50-11]]

^<<v1-50-11,11>>^ Quando os moradores de Canaã viram tanta gente chorando, disseram: "Como é impressionante o choro desses egípcios!" Por isso puseram naquele lugar o nome de Abel-Misraim .

[[v1-50-12]]

^<<v1-50-12,12>>^ Assim, os filhos de Jacó fizeram com o seu pai tudo o que ele havia ordenado.

[[v1-50-13]]

^<<v1-50-13,13>>^ Eles levaram o seu corpo até Canaã e o sepultaram na caverna de Macpela, a leste de Manre, no terreno que Abraão havia comprado de Efrom, o heteu, para ser a sepultura da família.

[[v1-50-14]]

^<<v1-50-14,14>>^ Depois do sepultamento, José voltou para o Egito com os irmãos e com todos os que o haviam acompanhado.

[[v1-50-15]]

^<<v1-50-15,15>>^ Depois da morte do pai, os irmãos de José disseram: — Talvez José tenha ódio de nós e vá se vingar de todo o mal que lhe fizemos.

[[v1-50-16]]

^<<v1-50-16,16>>^ Então mandaram dizer a José: — Antes que o seu pai morresse,

[[v1-50-17]]

^<<v1-50-17,17>>^ ele mandou que pedíssemos a você o seguinte: "Por favor, perdoe a maldade e o pecado dos seus irmãos, que o maltrataram." Portanto, pedimos que perdoe a nossa maldade, pois somos servos  do Deus do seu pai. Quando recebeu essa mensagem, José chorou.

[[v1-50-18]]

^<<v1-50-18,18>>^ Depois os próprios irmãos vieram, se curvaram diante dele e disseram: — Aqui estamos; somos seus criados.

[[v1-50-19]]

^<<v1-50-19,19>>^ Mas José respondeu: — Não tenham medo; eu não posso me colocar no lugar de Deus.

[[v1-50-20]]

^<<v1-50-20,20>>^ É verdade que vocês planejaram aquela maldade contra mim, mas Deus mudou o mal em bem para fazer o que hoje estamos vendo, isto é, salvar a vida de muita gente.

[[v1-50-21]]

^<<v1-50-21,21>>^ Não tenham medo. Eu cuidarei de vocês e dos seus filhos. Assim, ele os acalmou com palavras carinhosas, que tocaram o coração deles.

[[v1-50-22]]

^<<v1-50-22,22>>^ José ficou morando no Egito, ele e a família do seu pai. José viveu cento e dez anos

[[v1-50-23]]

^<<v1-50-23,23>>^ e chegou a ver os netos de Efraim. Ele também pegou no colo, como membros da família, os filhos do seu neto Maquir, que era filho de Manassés.

[[v1-50-24]]

^<<v1-50-24,24>>^ Certo dia José disse aos irmãos: — Eu vou morrer logo, mas estou certo de que Deus virá ajudá-los e os levará deste país para a terra que ele jurou dar a Abraão, a Isaque e a Jacó.

[[v1-50-25]]

^<<v1-50-25,25>>^ Então José pediu à sua gente que fizesse um juramento. Ele disse: — Estou certo de que Deus virá ajudar vocês. Quando isso acontecer, levem o meu corpo com vocês.

[[v1-50-26]]

^<<v1-50-26,26>>^ José morreu com cento e dez anos. O seu corpo foi embalsamado e posto num caixão, no Egito.

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodo/002-exodo-001.adoc#v2-1-0[Próximo Capítulo &#62;]