include::./index.adoc[]

[[v1-1-0]]
=== Gênesis, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-1-1]]

^<<v1-1-1,1>>^ No começo Deus criou os céus e a terra.

[[v1-1-2]]

^<<v1-1-2,2>>^ A terra era um vazio, sem nenhum ser vivente, e estava coberta por um mar profundo. A escuridão cobria o mar, e o Espírito de Deus se movia por cima da água.

[[v1-1-3]]

^<<v1-1-3,3>>^ Então Deus disse: — Que haja luz! E a luz começou a existir.

[[v1-1-4]]

^<<v1-1-4,4>>^ Deus viu que a luz era boa e a separou da escuridão.

[[v1-1-5]]

^<<v1-1-5,5>>^ Deus pôs na luz o nome de "dia" e na escuridão pôs o nome de "noite". A noite passou, e veio a manhã. Esse foi o primeiro dia.

[[v1-1-6]]

^<<v1-1-6,6>>^ Então Deus disse: — Que haja no meio da água uma divisão para separá-la em duas partes!

[[v1-1-7]]

^<<v1-1-7,7>>^ E assim aconteceu. Deus fez uma divisão que separou a água em duas partes: uma parte ficou do lado de baixo da divisão, e a outra parte ficou do lado de cima.

[[v1-1-8]]

^<<v1-1-8,8>>^ Nessa divisão Deus pôs o nome de "céu". A noite passou, e veio a manhã. Esse foi o segundo dia.

[[v1-1-9]]

^<<v1-1-9,9>>^ Aí Deus disse: — Que a água que está debaixo do céu se ajunte num só lugar a fim de que apareça a terra seca! E assim aconteceu.

[[v1-1-10]]

^<<v1-1-10,10>>^ Deus pôs na parte seca o nome de "terra" e nas águas que se haviam ajuntado ele pôs o nome de "mares". E Deus viu que o que havia feito era bom.

[[v1-1-11]]

^<<v1-1-11,11>>^ Em seguida ele disse: — Que a terra produza todo tipo de vegetais, isto é, plantas que deem sementes e árvores que deem frutas! E assim aconteceu.

[[v1-1-12]]

^<<v1-1-12,12>>^ A terra produziu todo tipo de vegetais: plantas que dão sementes e árvores que dão frutas. E Deus viu que o que havia feito era bom.

[[v1-1-13]]

^<<v1-1-13,13>>^ A noite passou, e veio a manhã. Esse foi o terceiro dia.

[[v1-1-14]]

^<<v1-1-14,14>>^ Então Deus disse: — Que haja luzes no céu para separarem o dia da noite e para marcarem os dias, os anos e as estações!

[[v1-1-15]]

^<<v1-1-15,15>>^ Essas luzes brilharão no céu para iluminar a terra. E assim aconteceu.

[[v1-1-16]]

^<<v1-1-16,16>>^ Deus fez as duas grandes luzes: a maior para governar o dia e a menor para governar a noite. E fez também as estrelas.

[[v1-1-17]]

^<<v1-1-17,17>>^ Deus pôs essas luzes no céu para iluminarem a terra,

[[v1-1-18]]

^<<v1-1-18,18>>^ para governarem o dia e a noite e para separarem a luz da escuridão. E Deus viu que o que havia feito era bom.

[[v1-1-19]]

^<<v1-1-19,19>>^ A noite passou, e veio a manhã. Esse foi o quarto dia.

[[v1-1-20]]

^<<v1-1-20,20>>^ Depois Deus disse: — Que as águas fiquem cheias de todo tipo de seres vivos, e que na terra haja aves que voem no ar!

[[v1-1-21]]

^<<v1-1-21,21>>^ Assim Deus criou os grandes monstros do mar, e todas as espécies de seres vivos que em grande quantidade se movem nas águas, e criou também todas as espécies de aves. E Deus viu que o que havia feito era bom.

[[v1-1-22]]

^<<v1-1-22,22>>^ Ele abençoou os seres vivos do mar e disse: — Aumentem muito em número e encham as águas dos mares! E que as aves se multipliquem na terra!

[[v1-1-23]]

^<<v1-1-23,23>>^ A noite passou, e veio a manhã. Esse foi o quinto dia.

[[v1-1-24]]

^<<v1-1-24,24>>^ Então Deus disse: — Que a terra produza todo tipo de animais: domésticos, selvagens e os que se arrastam pelo chão, cada um de acordo com a sua espécie! E assim aconteceu.

[[v1-1-25]]

^<<v1-1-25,25>>^ Deus fez os animais, cada um de acordo com a sua espécie: os animais domésticos, os selvagens e os que se arrastam pelo chão. E Deus viu que o que havia feito era bom.

[[v1-1-26]]

^<<v1-1-26,26>>^ Aí ele disse: — Agora vamos fazer os seres humanos, que serão como nós, que se parecerão conosco. Eles terão poder sobre os peixes, sobre as aves, sobre os animais domésticos e selvagens e sobre os animais que se arrastam pelo chão.

[[v1-1-27]]

^<<v1-1-27,27>>^ Assim Deus criou os seres humanos; ele os criou parecidos com Deus. Ele os criou homem e mulher

[[v1-1-28]]

^<<v1-1-28,28>>^ e os abençoou, dizendo: — Tenham muitos e muitos filhos; espalhem-se por toda a terra e a dominem. E tenham poder sobre os peixes do mar, sobre as aves que voam no ar e sobre os animais que se arrastam pelo chão.

[[v1-1-29]]

^<<v1-1-29,29>>^ Para vocês se alimentarem, eu lhes dou todas as plantas que produzem sementes e todas as árvores que dão frutas.

[[v1-1-30]]

^<<v1-1-30,30>>^ Mas, para todos os animais selvagens, para as aves e para os animais que se arrastam pelo chão, dou capim e verduras como alimento. E assim aconteceu.

[[v1-1-31]]

^<<v1-1-31,31>>^ E Deus viu que tudo o que havia feito era muito bom. A noite passou, e veio a manhã. Esse foi o sexto dia.

'''

**&#60; Capítulo Anterior** | <<v1-1-0,Topo>> | xref:001-genesis/001-genesis-002.adoc#v1-2-0[Próximo Capítulo &#62;]