include::./index.adoc[]

[[v1-27-0]]
=== Gênesis, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-27-1]]

^<<v1-27-1,1>>^ Isaque já estava bem velho e havia ficado cego. Um dia ele chamou Esaú, o seu filho mais velho, e disse: — Meu filho! — Estou aqui, pai — respondeu ele.

[[v1-27-2]]

^<<v1-27-2,2>>^ O pai lhe disse: — Você está vendo que estou velho e um dia desses vou morrer.

[[v1-27-3]]

^<<v1-27-3,3>>^ Pegue o seu arco e as suas flechas, vá até o campo e cace um animal.

[[v1-27-4]]

^<<v1-27-4,4>>^ Prepare uma comida saborosa, como eu gosto, e traga aqui para mim. Depois de comer, eu lhe darei a minha bênção, antes de morrer.

[[v1-27-5]]

^<<v1-27-5,5>>^ Acontece que Rebeca escutou o que Isaque disse a Esaú. Por isso, quando ele saiu para caçar,

[[v1-27-6]]

^<<v1-27-6,6>>^ ela disse a Jacó: — Escutei agora mesmo uma conversa do seu pai com o seu irmão Esaú. O seu pai disse assim:

[[v1-27-7]]

^<<v1-27-7,7>>^ "Vá caçar um animal e prepare uma comida saborosa para mim. Depois de comer, eu lhe darei a minha bênção na presença de Deus, o Senhor , antes de morrer."

[[v1-27-8]]

^<<v1-27-8,8>>^ Agora, meu filho — continuou Rebeca — escute bem e faça o que eu vou dizer.

[[v1-27-9]]

^<<v1-27-9,9>>^ Vá ao lugar onde estão os nossos animais e traga dois cabritos dos melhores. Eu vou preparar uma comida saborosa, como o seu pai gosta,

[[v1-27-10]]

^<<v1-27-10,10>>^ e você vai levá-la para ele comer. Depois o seu pai vai abençoar você, antes que ele morra.

[[v1-27-11]]

^<<v1-27-11,11>>^ Aí Jacó disse à mãe: — O meu irmão é muito peludo, e eu não.

[[v1-27-12]]

^<<v1-27-12,12>>^ Se o meu pai me apalpar e descobrir que sou eu, ele vai saber que eu estou tentando enganá-lo. Então ele vai me amaldiçoar em vez de me abençoar.

[[v1-27-13]]

^<<v1-27-13,13>>^ Mas a mãe respondeu: — Nesse caso, que a maldição caia sobre mim, meu filho. Faça exatamente o que eu disse: vá e traga os cabritos para mim.

[[v1-27-14]]

^<<v1-27-14,14>>^ Jacó foi, pegou os cabritos e os levou à mãe, e ela preparou uma comida saborosa, como Isaque gostava.

[[v1-27-15]]

^<<v1-27-15,15>>^ Depois ela pegou a melhor roupa de Esaú, que estava guardada em casa, e com ela vestiu Jacó.

[[v1-27-16]]

^<<v1-27-16,16>>^ Com a pele dos cabritos ela cobriu as mãos e o pescoço de Jacó, que não tinha pelos.

[[v1-27-17]]

^<<v1-27-17,17>>^ Depois entregou a Jacó a comida gostosa e o pão que ela havia feito.

[[v1-27-18]]

^<<v1-27-18,18>>^ Então Jacó foi até onde o pai estava e disse: — Pai! — Aqui estou — respondeu ele. — Quem é você, meu filho?

[[v1-27-19]]

^<<v1-27-19,19>>^ — Eu sou Esaú, o seu filho mais velho — disse Jacó. — Já fiz o que o senhor mandou. Levante-se, por favor; sente-se, coma da carne do animal que cacei e depois me abençoe.

[[v1-27-20]]

^<<v1-27-20,20>>^ Aí Isaque perguntou: — Mas como foi que você achou a caça tão depressa, meu filho? Jacó respondeu: — O Senhor , seu Deus, me ajudou.

[[v1-27-21]]

^<<v1-27-21,21>>^ Então Isaque disse a Jacó: — Chegue mais perto para que eu possa apalpar você. Assim vou saber se você é Esaú mesmo ou não.

[[v1-27-22]]

^<<v1-27-22,22>>^ Jacó chegou perto de Isaque, e ele o apalpou e disse: — A sua voz é a voz de Jacó, mas as mãos parecem as mãos de Esaú.

[[v1-27-23]]

^<<v1-27-23,23>>^ Assim, Isaque não reconheceu que era Jacó, pois as suas mãos estavam peludas como as de Esaú, e por isso ele o abençoou.

[[v1-27-24]]

^<<v1-27-24,24>>^ Mas, antes de abençoá-lo, perguntou mais uma vez: — Você é mesmo o meu filho Esaú? — Sou, sim — respondeu Jacó.

[[v1-27-25]]

^<<v1-27-25,25>>^ Então o pai disse: — Traga a carne da caça para que eu coma. Depois eu o abençoarei. Jacó serviu a comida ao seu pai e também trouxe vinho. Isaque comeu, e bebeu,

[[v1-27-26]]

^<<v1-27-26,26>>^ e depois disse: — Venha cá, meu filho, e me dê um beijo.

[[v1-27-27]]

^<<v1-27-27,27>>^ Jacó chegou perto e beijou o pai. Quando sentiu o cheiro da roupa que Jacó estava usando, Isaque o abençoou e disse assim: "Ah! O cheiro do meu filho é como o cheiro de um campo que o Senhor  Deus abençoou.

[[v1-27-28]]

^<<v1-27-28,28>>^ Meu filho, que Deus lhe dê o orvalho do céu; que os seus campos produzam boas colheitas e fartura de trigo e vinho.

[[v1-27-29]]

^<<v1-27-29,29>>^ Que nações sejam dominadas por você, e que você seja respeitado pelos povos. Que você mande nos seus parentes, e que os descendentes da sua mãe o tratem com respeito. Malditos sejam aqueles que o amaldiçoarem, e que sejam abençoados os que o abençoarem!"

[[v1-27-30]]

^<<v1-27-30,30>>^ Isaque acabou de dar a bênção, e Jacó ia saindo, quando Esaú chegou, vindo da caçada.

[[v1-27-31]]

^<<v1-27-31,31>>^ Ele também fez uma comida gostosa e levou para o pai. Aí disse: — Levante-se, por favor, coma da caça que eu matei e depois me abençoe.

[[v1-27-32]]

^<<v1-27-32,32>>^ Então Isaque perguntou: — Quem é você? — Eu sou Esaú, o seu filho mais velho.

[[v1-27-33]]

^<<v1-27-33,33>>^ Isaque ficou agitado e começou a tremer muito. E disse: — Então quem foi que caçou um animal e trouxe para mim? Eu comi antes que você chegasse e dei àquele homem a minha bênção. Ele é quem será abençoado.

[[v1-27-34]]

^<<v1-27-34,34>>^ Quando Esaú ouviu isso, deu um grito cheio de amargura e disse: — Meu pai, dê a sua bênção para mim também!

[[v1-27-35]]

^<<v1-27-35,35>>^ Porém Isaque respondeu: — O seu irmão veio, me enganou e ficou com a bênção que era sua.

[[v1-27-36]]

^<<v1-27-36,36>>^ Esaú disse: — Esta é a segunda vez que ele me engana. Foi com razão que puseram nele o nome de Jacó . Primeiro ele me tirou os direitos de filho mais velho e agora tirou a bênção que era minha. Pai, será que o senhor não guardou nenhuma bênção para mim?

[[v1-27-37]]

^<<v1-27-37,37>>^ Isaque respondeu: — Eu já dei a Jacó autoridade sobre você e fiz com que todos os parentes de Jacó sejam escravos dele. Também disse que ele terá muito trigo e muito vinho. Agora não posso fazer nada por você, meu filho.

[[v1-27-38]]

^<<v1-27-38,38>>^ Porém Esaú insistiu: — Será que o senhor tem só uma bênção? Abençoe também a mim, meu pai. E começou a chorar alto.

[[v1-27-39]]

^<<v1-27-39,39>>^ Então Isaque disse: "Você viverá longe de terras boas e longe do orvalho que cai do céu.

[[v1-27-40]]

^<<v1-27-40,40>>^ Você viverá pela sua espada e será empregado do seu irmão. Porém, quando você se revoltar, se livrará dele."

[[v1-27-41]]

^<<v1-27-41,41>>^ Esaú ficou com ódio de Jacó porque o seu pai tinha dado a ele a bênção. Então pensou assim: "O meu pai vai morrer logo. Quando acabarem os dias de luto, vou matar o meu irmão."

[[v1-27-42]]

^<<v1-27-42,42>>^ Rebeca ficou sabendo do plano de Esaú e mandou chamar Jacó. Ela disse: — Escute aqui! O seu irmão Esaú está planejando se vingar de você; ele quer matá-lo.

[[v1-27-43]]

^<<v1-27-43,43>>^ Por isso, meu filho, preste atenção. Vá agora mesmo para a casa de Labão, o meu irmão, que mora em Harã.

[[v1-27-44]]

^<<v1-27-44,44>>^ Fique algum tempo lá com ele, até que passe o ódio do seu irmão,

[[v1-27-45]]

^<<v1-27-45,45>>^ e ele esqueça aquilo que você lhe fez. Nessa ocasião eu mandarei alguém para trazer você de volta. Não quero perder os meus dois filhos num dia só!

[[v1-27-46]]

^<<v1-27-46,46>>^ Depois Rebeca foi falar com Isaque e disse: — Estou aborrecida da vida por causa dessas mulheres heteias com quem Esaú casou. Se Jacó também casar com uma dessas heteias, será melhor que eu morra.

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]