include::./index.adoc[]

[[v1-13-0]]
=== Gênesis, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-13-1]]

^<<v1-13-1,1>>^ Abrão saiu do Egito com a sua mulher e com tudo o que tinha e foi para o sul de Canaã. E Ló, o seu sobrinho, foi com ele.

[[v1-13-2]]

^<<v1-13-2,2>>^ Abrão era muito rico; tinha gado, prata e ouro.

[[v1-13-3]]

^<<v1-13-3,3>>^ Ele foi de um lugar para outro até chegar à cidade de Betel; e dali foi para o lugar que fica entre Betel e Ai, onde já havia acampado antes.

[[v1-13-4]]

^<<v1-13-4,4>>^ Abrão chegou ao altar que ele havia construído e adorou a Deus, o Senhor .

[[v1-13-5]]

^<<v1-13-5,5>>^ Ló, que ia com Abrão, também levava ovelhas, cabras, gado, empregados e a sua família.

[[v1-13-6]]

^<<v1-13-6,6>>^ Não havia pastos que dessem para os dois ficarem juntos, pois eles tinham muitos animais.

[[v1-13-7]]

^<<v1-13-7,7>>^ Por isso os homens que cuidavam dos animais de Abrão brigavam com os que tomavam conta dos animais de Ló. E nesse tempo os cananeus e os perizeus ainda estavam vivendo ali.

[[v1-13-8]]

^<<v1-13-8,8>>^ Um dia Abrão disse a Ló: — Nós somos parentes chegados, e não é bom que a gente fique brigando, nem que os meus empregados briguem com os seus.

[[v1-13-9]]

^<<v1-13-9,9>>^ Vamos nos separar. Escolha! A terra está aí, toda ela. Se você for para a esquerda, eu irei para a direita; se você for para a direita, eu irei para a esquerda.

[[v1-13-10]]

^<<v1-13-10,10>>^ Ló olhou em volta e viu que o vale do Jordão, até chegar à cidade de Zoar, tinha bastante água. Era como o Jardim do Senhor  ou como a terra do Egito. O vale era assim antes de o Senhor  haver destruído as cidades de Sodoma e de Gomorra.

[[v1-13-11]]

^<<v1-13-11,11>>^ Ló escolheu todo o vale do Jordão e foi na direção leste. E assim os dois se separaram.

[[v1-13-12]]

^<<v1-13-12,12>>^ Abrão ficou na terra de Canaã, e Ló foi morar nas cidades do vale. Ló foi acampando até chegar a Sodoma,

[[v1-13-13]]

^<<v1-13-13,13>>^ onde vivia uma gente má, que cometia pecados horríveis contra o Senhor .

[[v1-13-14]]

^<<v1-13-14,14>>^ Depois que Ló foi embora, o Senhor  Deus disse a Abrão: — De onde você está, olhe bem para o norte e para o sul, para o leste e para o oeste.

[[v1-13-15]]

^<<v1-13-15,15>>^ Eu vou dar a você e aos seus descendentes, para sempre, toda a terra que você está vendo.

[[v1-13-16]]

^<<v1-13-16,16>>^ Farei com que os seus descendentes sejam tantos como o pó da terra. Assim como ninguém pode contar os grãozinhos de pó, assim também não será possível contar os seus descendentes.

[[v1-13-17]]

^<<v1-13-17,17>>^ Agora vá e ande por esta terra, de norte a sul e de leste a oeste, pois eu a darei a você.

[[v1-13-18]]

^<<v1-13-18,18>>^ Assim, Abrão desarmou o seu acampamento e foi morar perto das árvores sagradas de Manre, na cidade de Hebrom. E ali Abrão construiu um altar para Deus, o Senhor .

'''

xref:001-genesis/001-genesis-012.adoc#v1-12-0[&#60; Capítulo Anterior] | <<v1-13-0,Topo>> | xref:001-genesis/001-genesis-014.adoc#v1-14-0[Próximo Capítulo &#62;]