include::./index.adoc[]

[[v1-39-0]]
=== Gênesis, 39
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-39-1]]

^<<v1-39-1,1>>^ José foi levado para o Egito, onde os ismaelitas o venderam a um egípcio chamado Potifar, um oficial que era o capitão da guarda do palácio.

[[v1-39-2]]

^<<v1-39-2,2>>^ O Senhor  Deus estava com José. Ele morava na casa do seu dono e ia muito bem em tudo.

[[v1-39-3]]

^<<v1-39-3,3>>^ O dono de José viu que o Senhor  estava com ele e o abençoava em tudo o que fazia.

[[v1-39-4]]

^<<v1-39-4,4>>^ Assim, José ganhou a simpatia do seu dono, que o pôs como seu ajudante particular. Potifar deu a José a responsabilidade de cuidar da sua casa e tomar conta de tudo o que era seu.

[[v1-39-5]]

^<<v1-39-5,5>>^ Dali em diante, por causa de José, o Senhor  abençoou o lar do egípcio e também tudo o que ele tinha em casa e no campo.

[[v1-39-6]]

^<<v1-39-6,6>>^ Potifar entregou nas mãos de José tudo o que tinha e não se preocupava com nada, a não ser com a comida que comia. José era um belo tipo de homem e simpático.

[[v1-39-7]]

^<<v1-39-7,7>>^ Algum tempo depois, a mulher do seu dono começou a cobiçar José. Um dia ela disse: — Venha, vamos para a cama.

[[v1-39-8]]

^<<v1-39-8,8>>^ Ele recusou, dizendo assim: — Escute! O meu dono não precisa se preocupar com nada nesta casa, pois eu estou aqui. Ele me pôs como responsável por tudo o que tem.

[[v1-39-9]]

^<<v1-39-9,9>>^ Nesta casa eu mando tanto quanto ele. Aqui eu posso ter o que quiser, menos a senhora, pois é mulher dele. Sendo assim, como poderia eu fazer uma coisa tão imoral e pecar contra Deus?

[[v1-39-10]]

^<<v1-39-10,10>>^ Todos os dias ela insistia que ele fosse para a cama com ela, mas José não concordava e também evitava estar perto dela.

[[v1-39-11]]

^<<v1-39-11,11>>^ Mas um dia, como de costume, ele entrou na casa para fazer o seu trabalho, e nenhum empregado estava ali.

[[v1-39-12]]

^<<v1-39-12,12>>^ Então ela o agarrou pela capa  e disse: — Venha, vamos para a cama. Mas ele escapou e correu para fora, deixando a capa nas mãos dela.

[[v1-39-13]]

^<<v1-39-13,13>>^ Quando notou que, ao fugir, ele havia deixado a capa nas suas mãos,

[[v1-39-14]]

^<<v1-39-14,14>>^ a mulher chamou os empregados da casa e disse: — Vejam só! Este hebreu, que o meu marido trouxe para casa, está nos insultando. Ele entrou no meu quarto e quis ter relações comigo, mas eu gritei o mais alto que pude.

[[v1-39-15]]

^<<v1-39-15,15>>^ Logo que comecei a gritar bem alto, ele fugiu, deixando a sua capa no meu quarto.

[[v1-39-16]]

^<<v1-39-16,16>>^ Ela guardou a capa até que o dono de José voltou.

[[v1-39-17]]

^<<v1-39-17,17>>^ Aí contou a mesma história, assim: — Esse escravo hebreu, que você trouxe para casa, entrou no meu quarto e quis abusar de mim.

[[v1-39-18]]

^<<v1-39-18,18>>^ Mas eu gritei bem alto, e ele correu para fora, deixando a sua capa no meu quarto.

[[v1-39-19]]

^<<v1-39-19,19>>^ Veja só de que jeito o seu escravo me tratou! Quando ouviu essa história, o dono de José ficou com muita raiva.

[[v1-39-20]]

^<<v1-39-20,20>>^ Ele agarrou José e o pôs na cadeia onde ficavam os presos do rei. E José ficou ali.

[[v1-39-21]]

^<<v1-39-21,21>>^ Mas o Senhor  estava com ele e o abençoou, de modo que ele conquistou a simpatia do carcereiro.

[[v1-39-22]]

^<<v1-39-22,22>>^ Este pôs José como encarregado de todos os outros presos, e era ele quem mandava em tudo o que se fazia na cadeia.

[[v1-39-23]]

^<<v1-39-23,23>>^ O carcereiro não se preocupava com nada do que estava entregue a José, pois o Senhor  estava com ele e o abençoava em tudo o que fazia.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]