include::./index.adoc[]

[[v1-37-0]]
=== Gênesis, 37
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-37-1]]

^<<v1-37-1,1>>^ Jacó ficou morando na terra de Canaã, onde o seu pai tinha vivido.

[[v1-37-2]]

^<<v1-37-2,2>>^ Esta é a história da família de Jacó. Quando José era um jovem de dezessete anos, cuidava das ovelhas e das cabras, junto com os seus irmãos, os filhos de Bila e de Zilpa, que eram mulheres do seu pai. E José contava ao pai as coisas erradas que os seus irmãos faziam.

[[v1-37-3]]

^<<v1-37-3,3>>^ Jacó já era velho quando José nasceu e por isso ele o amava mais do que a todos os seus outros filhos. Jacó mandou fazer para José uma túnica  longa, de mangas compridas.

[[v1-37-4]]

^<<v1-37-4,4>>^ Os irmãos viam que o pai amava mais a José do que a eles e por isso tinham ódio dele e eram grosseiros quando falavam com ele.

[[v1-37-5]]

^<<v1-37-5,5>>^ Certa vez José teve um sonho e o contou aos seus irmãos. Aí é que ficaram com mais raiva dele

[[v1-37-6]]

^<<v1-37-6,6>>^ porque ele disse assim: — Escutem, que eu vou contar o sonho que tive.

[[v1-37-7]]

^<<v1-37-7,7>>^ Sonhei que estávamos no campo amarrando feixes de trigo. De repente, o meu feixe ficou de pé, e os feixes de vocês se colocaram em volta do meu e se curvavam diante dele.

[[v1-37-8]]

^<<v1-37-8,8>>^ Então os irmãos perguntaram: — Quer dizer que você vai ser nosso rei e que vai mandar em nós? E ficaram com mais ódio dele ainda por causa dos seus sonhos e do jeito que ele os contava.

[[v1-37-9]]

^<<v1-37-9,9>>^ Depois José sonhou outra vez e contou também esse sonho aos seus irmãos. Ele disse assim: — Eu tive outro sonho. Desta vez o sol, a lua e onze estrelas se curvaram diante de mim.

[[v1-37-10]]

^<<v1-37-10,10>>^ Quando José contou esse sonho ao pai e aos irmãos, o pai o repreendeu e disse: — O que quer dizer esse sonho que você teve? Por acaso a sua mãe, os seus irmãos e eu vamos nos ajoelhar diante de você e encostar o rosto no chão?

[[v1-37-11]]

^<<v1-37-11,11>>^ Os irmãos de José tinham inveja dele, mas o seu pai ficou pensando no caso.

[[v1-37-12]]

^<<v1-37-12,12>>^ Um dia os irmãos de José levaram as ovelhas e as cabras do seu pai até os pastos que ficavam perto da cidade de Siquém.

[[v1-37-13]]

^<<v1-37-13,13>>^ Então Jacó disse a José: — Venha cá. Vou mandar você até Siquém, onde os seus irmãos estão cuidando das ovelhas e das cabras. — Estou pronto para ir — respondeu José.

[[v1-37-14]]

^<<v1-37-14,14>>^ Jacó disse: — Vá lá e veja se os seus irmãos e os animais vão bem e me traga notícias. Então dali, do vale de Hebrom, Jacó mandou que José fosse até Siquém, e ele foi. Quando chegou lá,

[[v1-37-15]]

^<<v1-37-15,15>>^ ele foi andando pelo campo. Aí um homem o viu e perguntou: — O que você está procurando?

[[v1-37-16]]

^<<v1-37-16,16>>^ — Estou procurando os meus irmãos — respondeu José. — Eles estão por aí, em algum pasto, cuidando das ovelhas e das cabras. O senhor sabe aonde foram?

[[v1-37-17]]

^<<v1-37-17,17>>^ O homem respondeu: — Eles já foram embora daqui. Eu ouvi quando disseram que iam para Dotã. Aí José foi procurar os seus irmãos e os achou em Dotã.

[[v1-37-18]]

^<<v1-37-18,18>>^ Eles viram José de longe e, antes que chegasse perto, começaram a fazer planos para matá-lo.

[[v1-37-19]]

^<<v1-37-19,19>>^ Eles disseram: — Lá vem o sonhador!

[[v1-37-20]]

^<<v1-37-20,20>>^ Venham, vamos matá-lo agora. Depois jogaremos o corpo num poço seco e diremos que um animal selvagem o devorou. Assim, veremos no que vão dar os sonhos dele.

[[v1-37-21]]

^<<v1-37-21,21>>^ Quando Rúben ouviu isso, quis salvá-lo dos seus irmãos e disse: — Não vamos matá-lo.

[[v1-37-22]]

^<<v1-37-22,22>>^ Não derramem sangue. Vocês podem jogá-lo neste poço, aqui no deserto, mas não o machuquem. Rúben disse isso porque planejava salvá-lo dos irmãos e mandá-lo de volta ao pai.

[[v1-37-23]]

^<<v1-37-23,23>>^ Quando José chegou ao lugar onde os seus irmãos estavam, eles arrancaram dele a túnica  longa, de mangas compridas, que ele estava vestindo.

[[v1-37-24]]

^<<v1-37-24,24>>^ Depois o pegaram e o jogaram no poço, que estava vazio e seco.

[[v1-37-25]]

^<<v1-37-25,25>>^ E sentaram-se para comer. De repente, viram que ia passando uma caravana  de ismaelitas que vinha de Gileade e ia para o Egito. Os seus camelos estavam carregados de perfumes e de especiarias .

[[v1-37-26]]

^<<v1-37-26,26>>^ Aí Judá disse aos irmãos: — O que vamos ganhar se matarmos o nosso irmão e depois escondermos a sua morte?

[[v1-37-27]]

^<<v1-37-27,27>>^ Em vez de o matarmos, vamos vendê-lo a esses ismaelitas. Afinal de contas ele é nosso irmão, é do nosso sangue. Os irmãos concordaram.

[[v1-37-28]]

^<<v1-37-28,28>>^ Quando alguns negociantes midianitas passaram por ali, os irmãos de José o tiraram do poço e o venderam aos ismaelitas por vinte barras de prata. E os ismaelitas levaram José para o Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Quando Rúben voltou ao poço e viu que José não estava lá dentro, rasgou as suas roupas em sinal de tristeza.

[[v1-37-30]]

^<<v1-37-30,30>>^ Ele voltou para o lugar onde os seus irmãos estavam e disse: — O rapaz não está mais lá! E agora o que é que eu vou fazer?

[[v1-37-31]]

^<<v1-37-31,31>>^ Então os irmãos mataram um cabrito e com o sangue mancharam a túnica de José.

[[v1-37-32]]

^<<v1-37-32,32>>^ Depois levaram a túnica ao pai e disseram: — Achamos isso aí. Será que é a túnica do seu filho?

[[v1-37-33]]

^<<v1-37-33,33>>^ Jacó a reconheceu e disse: — Sim, é a túnica do meu filho! Certamente algum animal selvagem o despedaçou e devorou.

[[v1-37-34]]

^<<v1-37-34,34>>^ Então, em sinal de tristeza, Jacó rasgou as suas roupas e vestiu roupa de luto. E durante muito tempo ficou de luto pelo seu filho.

[[v1-37-35]]

^<<v1-37-35,35>>^ Todos os seus filhos e filhas tentaram consolá-lo, mas ele não quis ser consolado e disse: — Vou ficar de luto por meu filho até que vá me encontrar com ele no mundo dos mortos . E continuou de luto por seu filho José.

[[v1-37-36]]

^<<v1-37-36,36>>^ Enquanto isso, os midianitas venderam José a Potifar, oficial e capitão da guarda do rei do Egito.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]