include::./index.adoc[]

[[v1-12-0]]
=== Gênesis, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-12-1]]

^<<v1-12-1,1>>^ Certo dia o Senhor  Deus disse a Abrão: — Saia da sua terra, do meio dos seus parentes e da casa do seu pai e vá para uma terra que eu lhe mostrarei.

[[v1-12-2]]

^<<v1-12-2,2>>^ Os seus descendentes vão formar uma grande nação. Eu o abençoarei, o seu nome será famoso, e você será uma bênção para os outros.

[[v1-12-3]]

^<<v1-12-3,3>>^ Abençoarei os que o abençoarem e amaldiçoarei os que o amaldiçoarem. E por meio de você eu abençoarei todos os povos do mundo.

[[v1-12-4]]

^<<v1-12-4,4>>^ Abrão tinha setenta e cinco anos quando partiu de Harã, como o Senhor  havia ordenado. E Ló foi com ele.

[[v1-12-5]]

^<<v1-12-5,5>>^ Abrão levou a sua mulher Sarai, o seu sobrinho Ló, filho do seu irmão, e todas as riquezas e escravos que havia conseguido em Harã. Quando chegaram a Canaã,

[[v1-12-6]]

^<<v1-12-6,6>>^ Abrão atravessou o país até que chegou a Siquém, um lugar santo, onde ficava a árvore sagrada de Moré. Naquele tempo os cananeus viviam nessa região.

[[v1-12-7]]

^<<v1-12-7,7>>^ Ali o Senhor  apareceu a Abrão e disse: — Eu vou dar esta terra aos seus descendentes. Naquele lugar Abrão construiu um altar a Deus, o Senhor , pois ali o Senhor  havia aparecido a ele.

[[v1-12-8]]

^<<v1-12-8,8>>^ Depois disso Abrão foi para a região montanhosa que fica a leste da cidade de Betel e ali armou o seu acampamento. Betel ficava a oeste do acampamento, e a cidade de Ai ficava a leste. Também nesse lugar Abrão construiu um altar e adorou o Senhor .

[[v1-12-9]]

^<<v1-12-9,9>>^ Dali ele foi andando de um lugar para outro, sempre na direção sul da terra de Canaã.

[[v1-12-10]]

^<<v1-12-10,10>>^ Naquele tempo houve em Canaã uma fome tão grande, que Abrão foi morar por algum tempo no Egito.

[[v1-12-11]]

^<<v1-12-11,11>>^ Quando ia chegando ao Egito, Abrão disse a Sarai, a sua mulher: — Escute! Você é uma mulher muito bonita,

[[v1-12-12]]

^<<v1-12-12,12>>^ e, quando os egípcios a virem, vão dizer: "Essa aí é a mulher dele." Por isso me matarão e deixarão que você viva.

[[v1-12-13]]

^<<v1-12-13,13>>^ Diga, então, que você é minha irmã. Assim, por sua causa, eles me deixarão viver e me tratarão bem.

[[v1-12-14]]

^<<v1-12-14,14>>^ Quando Abrão chegou ao Egito, os egípcios viram que Sarai, a sua mulher, era, de fato, muito bonita.

[[v1-12-15]]

^<<v1-12-15,15>>^ Alguns altos funcionários do rei do Egito também a viram e contaram a ele como era linda aquela mulher. Por isso ela foi levada para o palácio do rei.

[[v1-12-16]]

^<<v1-12-16,16>>^ Por causa dela o rei tratou bem Abrão e lhe deu ovelhas, bois, jumentos, escravos e escravas, jumentas e camelos.

[[v1-12-17]]

^<<v1-12-17,17>>^ Mas, por causa de Sarai, o Senhor  Deus castigou o rei e a sua família com doenças horríveis.

[[v1-12-18]]

^<<v1-12-18,18>>^ Por isso o rei mandou chamar Abrão e perguntou: — Por que você me fez uma coisa dessas? Por que não me disse que ela é a sua mulher?

[[v1-12-19]]

^<<v1-12-19,19>>^ Você disse que ela era sua irmã, e por isso eu casei com ela. Portanto, aqui está a sua mulher; saia daqui com ela!

[[v1-12-20]]

^<<v1-12-20,20>>^ Então o rei deu ordem, e os seus guardas levaram Abrão para fora do Egito, junto com a sua mulher e com todas as coisas que eram dele.

'''

xref:001-genesis/001-genesis-011.adoc#v1-11-0[&#60; Capítulo Anterior] | <<v1-12-0,Topo>> | xref:001-genesis/001-genesis-013.adoc#v1-13-0[Próximo Capítulo &#62;]