include::./index.adoc[]

[[v1-42-0]]
=== Gênesis, 42
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-42-1]]

^<<v1-42-1,1>>^ Quando Jacó soube que havia mantimentos no Egito, disse aos filhos: — Por que vocês estão aí de braços cruzados?

[[v1-42-2]]

^<<v1-42-2,2>>^ Ouvi dizer que no Egito há mantimentos. Vão até lá e comprem cereais para não morrermos de fome.

[[v1-42-3]]

^<<v1-42-3,3>>^ Então os dez irmãos de José por parte de pai foram até o Egito para comprar mantimentos.

[[v1-42-4]]

^<<v1-42-4,4>>^ Mas Jacó não deixou que Benjamim, o irmão de José por parte de pai e de mãe, fosse com eles; ele tinha medo de que lhe acontecesse alguma desgraça.

[[v1-42-5]]

^<<v1-42-5,5>>^ Os filhos de Jacó foram comprar mantimentos junto com outras pessoas, pois em todo o país de Canaã havia fome.

[[v1-42-6]]

^<<v1-42-6,6>>^ Como governador do Egito, era José quem vendia cereais às pessoas que vinham de outras terras. Quando os irmãos de José chegaram, eles se ajoelharam na frente dele e encostaram o rosto no chão.

[[v1-42-7]]

^<<v1-42-7,7>>^ Logo que José viu os seus irmãos, ele os reconheceu, mas fez de conta que não os conhecia. E lhes perguntou com voz dura: — Vocês, de onde vêm? — Da terra de Canaã — responderam. — Queremos comprar mantimentos.

[[v1-42-8]]

^<<v1-42-8,8>>^ José reconheceu os seus irmãos, mas eles não o reconheceram.

[[v1-42-9]]

^<<v1-42-9,9>>^ Então José lembrou dos sonhos que tinha tido a respeito deles e disse: — Vocês são espiões que vieram para ver os pontos fracos do nosso país.

[[v1-42-10]]

^<<v1-42-10,10>>^ Eles responderam: — De modo nenhum, senhor. Nós, os seus criados, viemos para comprar mantimentos.

[[v1-42-11]]

^<<v1-42-11,11>>^ Somos filhos de um mesmo pai. Nós não somos espiões, senhor! Somos gente honesta.

[[v1-42-12]]

^<<v1-42-12,12>>^ — Não acredito — disse José. — Vocês vieram para ver os pontos fracos do nosso país.

[[v1-42-13]]

^<<v1-42-13,13>>^ Eles disseram: — Nós moramos em Canaã. Somos ao todo doze irmãos, filhos do mesmo pai. Mas um irmão desapareceu, e o mais novo está neste momento com o nosso pai.

[[v1-42-14]]

^<<v1-42-14,14>>^ José respondeu: — É como eu disse: vocês são espiões.

[[v1-42-15]]

^<<v1-42-15,15>>^ E o jeito de provar que vocês estão dizendo a verdade é este: enquanto o irmão mais moço de vocês não vier para cá, vocês não sairão daqui. Isso eu juro pela vida do rei!

[[v1-42-16]]

^<<v1-42-16,16>>^ Um de vocês irá buscá-lo, mas os outros ficarão presos até que fique provado se estão ou não dizendo a verdade. Se não estão, é que vocês são espiões. Juro pela vida do rei!

[[v1-42-17]]

^<<v1-42-17,17>>^ E os pôs na cadeia por três dias.

[[v1-42-18]]

^<<v1-42-18,18>>^ No terceiro dia José disse a eles: — Eu sou uma pessoa que teme a Deus . Vou deixar que vocês fiquem vivos, mas com uma condição.

[[v1-42-19]]

^<<v1-42-19,19>>^ Se, de fato, são pessoas honestas, que um de vocês fique aqui na cadeia, e que os outros voltem para casa, levando mantimentos para matar a fome das suas famílias.

[[v1-42-20]]

^<<v1-42-20,20>>^ Depois tragam aqui o seu irmão mais moço. Isso provará se vocês estão ou não dizendo a verdade; e, se estiverem, não serão mortos. Eles concordaram

[[v1-42-21]]

^<<v1-42-21,21>>^ e disseram uns aos outros: — De fato, nós agora estamos sofrendo por causa daquilo que fizemos com o nosso irmão. Nós vimos a sua aflição quando pedia que tivéssemos pena dele, porém não nos importamos. Por isso agora é a nossa vez de ficarmos aflitos.

[[v1-42-22]]

^<<v1-42-22,22>>^ E Rúben disse assim: — Eu bem que disse que não maltratassem o rapaz, mas vocês não quiseram me ouvir. Por isso agora estamos pagando pela morte dele.

[[v1-42-23]]

^<<v1-42-23,23>>^ Eles não sabiam que José estava entendendo o que diziam, pois ele tinha estado falando com eles por meio de um intérprete.

[[v1-42-24]]

^<<v1-42-24,24>>^ José saiu de perto deles e começou a chorar. Quando pôde falar outra vez, voltou, separou Simeão e mandou que fosse amarrado na presença deles.

[[v1-42-25]]

^<<v1-42-25,25>>^ José mandou que os empregados enchessem de mantimentos os sacos que os irmãos haviam trazido e que devolvessem o dinheiro de cada um, colocando-o nos sacos de mantimentos. E também que lhes dessem comida para a viagem. E assim foi feito.

[[v1-42-26]]

^<<v1-42-26,26>>^ Os irmãos de José carregaram os jumentos com os mantimentos que haviam comprado e foram embora.

[[v1-42-27]]

^<<v1-42-27,27>>^ Quando chegaram ao lugar onde iam passar a noite, um deles abriu um saco para dar comida ao seu animal e viu que o seu dinheiro estava ali na boca do saco de mantimentos.

[[v1-42-28]]

^<<v1-42-28,28>>^ Ele disse aos irmãos: — Vejam só! O meu dinheiro está aqui no meu saco de mantimentos! Eles devolveram! Todos ficaram muito assustados e, tremendo de medo, perguntavam uns aos outros: — O que será isso que Deus fez com a gente?

[[v1-42-29]]

^<<v1-42-29,29>>^ Quando chegaram a Canaã, contaram a Jacó, o seu pai, tudo o que havia acontecido com eles. E disseram:

[[v1-42-30]]

^<<v1-42-30,30>>^ — Aquele homem, o governador do Egito, tratou a gente com brutalidade e nos acusou de termos ido ao seu país como espiões.

[[v1-42-31]]

^<<v1-42-31,31>>^ Nós respondemos: "Somos homens honestos; não somos espiões.

[[v1-42-32]]

^<<v1-42-32,32>>^ Somos ao todo doze irmãos, filhos do mesmo pai. Mas um dos nossos irmãos desapareceu, e o mais novo está neste momento com o nosso pai em Canaã."

[[v1-42-33]]

^<<v1-42-33,33>>^ O governador respondeu: "Eu tenho um jeito de descobrir se vocês são homens honestos. Um de vocês ficará aqui comigo, e os outros vão voltar, levando um pouco de mantimento para as suas famílias, que estão passando fome.

[[v1-42-34]]

^<<v1-42-34,34>>^ Mas tragam aqui para mim o seu irmão mais novo. Assim, eu ficarei sabendo que vocês não são espiões, mas homens honestos. Aí entregarei o irmão de vocês, e vocês poderão ficar aqui negociando."

[[v1-42-35]]

^<<v1-42-35,35>>^ Aconteceu que, quando despejaram os mantimentos, cada um achou na boca do saco um saquinho com o seu dinheiro. Quando eles e o seu pai viram o dinheiro, ficaram com medo.

[[v1-42-36]]

^<<v1-42-36,36>>^ Então Jacó disse: — Vocês querem que eu perca todos os meus filhos? José não está com a gente, e Simeão também não está. Agora vocês querem levar Benjamim, e quem sofre com tudo isso sou eu!

[[v1-42-37]]

^<<v1-42-37,37>>^ Aí Rúben disse ao pai: — Deixe que eu tome conta de Benjamim; eu o trarei de volta para o senhor. Se não trouxer, o senhor pode matar os meus dois filhos.

[[v1-42-38]]

^<<v1-42-38,38>>^ Jacó respondeu: — O meu filho não vai com vocês. José, o irmão dele, está morto, e só ficou Benjamim. Alguma coisa poderia acontecer com ele na viagem que vão fazer, e assim vocês matariam de tristeza este velho.

'''

xref:001-genesis/001-genesis-041.adoc#v1-41-0[&#60; Capítulo Anterior] | <<v1-42-0,Topo>> | xref:001-genesis/001-genesis-043.adoc#v1-43-0[Próximo Capítulo &#62;]