include::./index.adoc[]

[[v1-43-0]]
=== Gênesis, 43
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-43-1]]

^<<v1-43-1,1>>^ A fome continuava muito grande em Canaã.

[[v1-43-2]]

^<<v1-43-2,2>>^ Quando as famílias de Jacó e dos seus filhos comeram todo o mantimento que tinha sido trazido do Egito, Jacó disse aos filhos: — Voltem ao Egito e comprem mais um pouco de alimento para nós.

[[v1-43-3]]

^<<v1-43-3,3>>^ Mas Judá lembrou: — Aquele homem deixou bem claro que, se o nosso irmão não fosse junto com a gente, ele não nos receberia.

[[v1-43-4]]

^<<v1-43-4,4>>^ Se o senhor deixar que ele vá, nós iremos comprar mantimentos para o senhor.

[[v1-43-5]]

^<<v1-43-5,5>>^ Se o senhor não deixar, não iremos. Aquele homem disse assim: "Eu só os receberei se vocês trouxerem o seu irmão mais novo."

[[v1-43-6]]

^<<v1-43-6,6>>^ Jacó disse: — Por que vocês fizeram cair tamanha desgraça sobre mim? Por que foram dizer ao tal homem que tinham outro irmão?

[[v1-43-7]]

^<<v1-43-7,7>>^ Eles responderam: — Aquele homem fez muitas perguntas a respeito de nós e da nossa família. Ele perguntou: "O pai de vocês ainda está vivo? Vocês têm mais um irmão?" Nós tivemos de responder às perguntas dele. Por acaso podíamos adivinhar que ele ia pedir que levássemos o nosso irmão?

[[v1-43-8]]

^<<v1-43-8,8>>^ Aí Judá disse ao pai: — Deixe o rapaz por minha conta. Nós partiremos agora mesmo, e assim ninguém morrerá: nem nós, nem o senhor, nem os nossos filhinhos.

[[v1-43-9]]

^<<v1-43-9,9>>^ Eu fico responsável por Benjamim. Se eu não o trouxer de volta são e salvo, o senhor poderá pôr a culpa em mim. Serei culpado diante do senhor pelo resto da minha vida.

[[v1-43-10]]

^<<v1-43-10,10>>^ Se não tivéssemos demorado tanto, já teríamos ido e voltado duas vezes.

[[v1-43-11]]

^<<v1-43-11,11>>^ Então o pai disse: — Já que não existe outro jeito, façam o seguinte: ponham nos sacos alguns presentes para aquele homem. Levem os melhores produtos desta terra: um pouco de bálsamo, um pouco de mel, especiarias , nozes e amêndoas.

[[v1-43-12]]

^<<v1-43-12,12>>^ Levem também o dinheiro em dobro, pois vocês precisam devolver a quantia que foi encontrada na boca dos sacos de mantimentos que vocês trouxeram. Deve ter havido algum engano.

[[v1-43-13]]

^<<v1-43-13,13>>^ Levem o irmão de vocês e vão depressa encontrar-se outra vez com aquele homem.

[[v1-43-14]]

^<<v1-43-14,14>>^ Que o Deus Todo-Poderoso faça com que ele tenha pena de vocês e deixe que o seu outro irmão e Benjamim voltem para casa. Quanto a mim, se tenho de perder os meus filhos, o que é que eu posso fazer?

[[v1-43-15]]

^<<v1-43-15,15>>^ Assim, os filhos de Jacó pegaram os presentes e o dinheiro em dobro e foram para o Egito, levando Benjamim. Logo que chegaram, foram falar com José.

[[v1-43-16]]

^<<v1-43-16,16>>^ Quando José viu que Benjamim estava com eles, disse ao funcionário administrador da sua casa: — Leve esses homens até a minha casa. Mate um animal e prepare tudo, pois eles vão almoçar comigo hoje, ao meio-dia.

[[v1-43-17]]

^<<v1-43-17,17>>^ O administrador cumpriu a ordem e levou os irmãos até a casa de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Quando chegaram lá, eles ficaram com medo e disseram uns aos outros: — Trouxeram a gente para cá por causa do dinheiro que da outra vez foi colocado de volta nos sacos de mantimentos. Com certeza eles vão nos atacar, vão tomar de nós os nossos jumentos e obrigar a gente a trabalhar como escravos.

[[v1-43-19]]

^<<v1-43-19,19>>^ Assim que chegaram à porta da casa, disseram ao administrador:

[[v1-43-20]]

^<<v1-43-20,20>>^ — Por favor, senhor! Já viemos aqui uma vez para comprar mantimentos.

[[v1-43-21]]

^<<v1-43-21,21>>^ Porém, quando chegamos ao lugar onde íamos passar a noite, abrimos os sacos de mantimentos, e na boca dos sacos cada um encontrou o seu dinheiro, sem faltar nada. Trouxemos esse dinheiro de volta

[[v1-43-22]]

^<<v1-43-22,22>>^ e também temos mais dinheiro aqui para comprar mantimentos. Nós não sabemos quem colocou o dinheiro nos sacos de mantimentos.

[[v1-43-23]]

^<<v1-43-23,23>>^ Aí o administrador respondeu: — Fiquem tranquilos, não tenham medo. O Deus de vocês e do seu pai deve ter posto o dinheiro nos sacos de mantimentos para vocês, pois eu recebi o dinheiro que pagaram. O administrador trouxe Simeão ao lugar onde eles estavam.

[[v1-43-24]]

^<<v1-43-24,24>>^ Depois os levou para dentro da casa, deu água para lavarem os pés e também deu de comer aos jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ Os irmãos prepararam os presentes que iam entregar a José quando ele viesse ao meio-dia, pois já sabiam que iam almoçar ali.

[[v1-43-26]]

^<<v1-43-26,26>>^ Quando José chegou à sua casa, eles lhe entregaram os presentes que haviam trazido, se ajoelharam na frente dele e encostaram o rosto no chão.

[[v1-43-27]]

^<<v1-43-27,27>>^ José perguntou como iam passando e depois disse: — E como vai o pai de vocês, aquele velho de quem me falaram? Ele ainda vive?

[[v1-43-28]]

^<<v1-43-28,28>>^ Eles responderam: — O seu humilde criado, o nosso pai, ainda está vivo e vai passando bem.

[[v1-43-29]]

^<<v1-43-29,29>>^ José olhou em volta e, quando viu Benjamim, o seu irmão por parte de pai e mãe, disse: — É esse o irmão mais moço de vocês, de quem me falaram? Que Deus o abençoe, meu filho!

[[v1-43-30]]

^<<v1-43-30,30>>^ Ao ver o seu irmão, José ficou tão emocionado, que teve vontade de chorar. Então foi para o seu quarto e ali chorou.

[[v1-43-31]]

^<<v1-43-31,31>>^ Quando conseguiu se controlar, lavou o rosto e saiu. E disse: — Sirvam o almoço.

[[v1-43-32]]

^<<v1-43-32,32>>^ Serviram o almoço a José numa mesa e aos seus irmãos em outra. E havia ainda outra mesa para os egípcios que estavam ali, pois estes, por motivos religiosos, eram proibidos de comer junto com os israelitas.

[[v1-43-33]]

^<<v1-43-33,33>>^ Os irmãos se sentaram de frente para José. Eles foram colocados por ordem de idade, desde o mais velho até o mais moço. Quando viram isso, eles começaram a olhar uns para os outros, muito admirados.

[[v1-43-34]]

^<<v1-43-34,34>>^ Serviram a eles da mesma comida que foi servida a José e deram a Benjamim cinco vezes mais comida do que aos outros. E eles beberam com José até ficarem alegres.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]