include::./index.adoc[]

[[v1-48-0]]
=== Gênesis, 48
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-48-1]]

^<<v1-48-1,1>>^ Algum tempo depois disseram a José que o seu pai estava doente. Então José foi visitá-lo, levando consigo os seus dois filhos, Efraim e Manassés.

[[v1-48-2]]

^<<v1-48-2,2>>^ Alguém foi dizer a Jacó: — O seu filho José veio visitá-lo. Jacó fez um esforço e se sentou na cama.

[[v1-48-3]]

^<<v1-48-3,3>>^ Aí disse a José: — O Deus Todo-Poderoso me apareceu na cidade de Luz , lá na terra de Canaã, e me abençoou.

[[v1-48-4]]

^<<v1-48-4,4>>^ Ele me disse: "Eu farei com que você tenha muitos filhos, e os seus descendentes formarão muitas nações. Eu darei esta terra aos seus descendentes para ser propriedade deles para sempre."

[[v1-48-5]]

^<<v1-48-5,5>>^ E Jacó continuou dizendo a José: — Agora, os seus filhos Efraim e Manassés, que nasceram aqui no Egito antes de eu vir para cá, esses dois me pertencem. Efraim e Manassés são meus tanto como Rúben e Simeão.

[[v1-48-6]]

^<<v1-48-6,6>>^ Se você tiver outros filhos, eles serão seus e, por serem irmãos de Efraim e de Manassés, terão parte na herança deles.

[[v1-48-7]]

^<<v1-48-7,7>>^ Estou fazendo isso por causa de Raquel, a sua mãe. Nós estávamos voltando da Mesopotâmia, quando, para minha infelicidade, ela morreu no país de Canaã, pouco antes de chegarmos a Efrata. Eu a sepultei ali, na beira do caminho (Efrata é agora conhecida como Belém.).

[[v1-48-8]]

^<<v1-48-8,8>>^ Quando Jacó viu os filhos de José, perguntou: — E esses, quem são?

[[v1-48-9]]

^<<v1-48-9,9>>^ — São os filhos que Deus me deu aqui no Egito — respondeu José. Jacó disse: — Ponha-os perto de mim para que eu lhes dê a minha bênção.

[[v1-48-10]]

^<<v1-48-10,10>>^ Por causa da velhice a vista de Jacó estava fraca, e ele não podia ver bem. José levou os rapazes para perto dele, e ele os abraçou e beijou.

[[v1-48-11]]

^<<v1-48-11,11>>^ Jacó disse a José: — Eu pensei que nunca mais ia ver você, e agora Deus me deixou ver até os seus filhos.

[[v1-48-12]]

^<<v1-48-12,12>>^ Então José tirou os dois do colo do seu pai, ajoelhou-se e encostou o rosto no chão.

[[v1-48-13]]

^<<v1-48-13,13>>^ Em seguida pegou Efraim com a mão direita e Manassés com a mão esquerda e fez com que ficassem perto de Jacó. Dessa maneira Efraim ficou do lado esquerdo de Jacó, e Manassés, do seu lado direito.

[[v1-48-14]]

^<<v1-48-14,14>>^ Jacó estendeu os braços e cruzou-os, pondo a mão direita sobre a cabeça de Efraim, embora fosse o mais moço, e a mão esquerda sobre a cabeça de Manassés, que era o mais velho.

[[v1-48-15]]

^<<v1-48-15,15>>^ Em seguida deu a sua bênção a José, dizendo assim: "Ó Deus, a quem os meus pais Abraão e Isaque serviram, abençoa estes rapazes. Abençoa-os, ó Deus, tu que me tens guiado como um pastor durante toda a minha vida até hoje.

[[v1-48-16]]

^<<v1-48-16,16>>^ Que os abençoe o Anjo que me tem livrado de todo mal! Que o meu nome seja lembrado por meio deles e também o nome dos meus pais Abraão e Isaque! Que eles tenham muitos filhos e muitos descendentes neste mundo!"

[[v1-48-17]]

^<<v1-48-17,17>>^ José não gostou quando viu o seu pai colocar a mão direita sobre a cabeça de Efraim; por isso pegou a mão dele para tirá-la da cabeça de Efraim e colocá-la sobre a de Manassés.

[[v1-48-18]]

^<<v1-48-18,18>>^ E explicou: — Não, pai; assim não. Este aqui é o filho mais velho; ponha a mão direita sobre a cabeça dele.

[[v1-48-19]]

^<<v1-48-19,19>>^ Mas Jacó não quis e disse: — Eu sei, filho, eu sei. Os descendentes de Manassés também serão um grande povo. Mas o irmão mais moço será mais importante do que ele, e os seus descendentes formarão muitas nações.

[[v1-48-20]]

^<<v1-48-20,20>>^ Desse modo Jacó os abençoou naquele dia, dizendo: — Os israelitas usarão os nomes de vocês para dar a bênção. Eles vão dizer assim: "Que Deus faça com você como fez com Efraim e com Manassés." Dessa maneira Jacó pôs Efraim antes de Manassés.

[[v1-48-21]]

^<<v1-48-21,21>>^ Aí disse a José: — Como você está vendo, eu vou morrer. Mas Deus estará com vocês e os levará de volta para a terra dos seus antepassados.

[[v1-48-22]]

^<<v1-48-22,22>>^ Eu dou Siquém a você e não aos seus irmãos. Siquém é aquela região que tomei dos amorreus, lutando com a minha espada e o meu arco.

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]