include::./index.adoc[]

[[v1-41-0]]
=== Gênesis, 41
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-41-1]]

^<<v1-41-1,1>>^ Dois anos se passaram. Um dia o rei do Egito sonhou que estava de pé na beira do rio Nilo.

[[v1-41-2]]

^<<v1-41-2,2>>^ De repente, saíram do rio sete vacas bonitas e gordas, que começaram a comer o capim da beira do rio.

[[v1-41-3]]

^<<v1-41-3,3>>^ Logo em seguida saíram do rio outras sete vacas, feias e magras, que foram ficar perto das primeiras vacas, na beira do rio.

[[v1-41-4]]

^<<v1-41-4,4>>^ E as vacas feias e magras engoliram as bonitas e gordas. Aí o rei acordou.

[[v1-41-5]]

^<<v1-41-5,5>>^ Mas tornou a dormir e teve outro sonho. Desta vez ele viu sete espigas de trigo que saíam de um mesmo pé; elas eram boas e cheias de grãos.

[[v1-41-6]]

^<<v1-41-6,6>>^ Depois saíram sete espigas secas e queimadas pelo vento quente do deserto

[[v1-41-7]]

^<<v1-41-7,7>>^ e elas engoliram as sete espigas cheias e boas. O rei acordou: tinha sido um sonho.

[[v1-41-8]]

^<<v1-41-8,8>>^ De manhã ele estava muito preocupado e por isso mandou chamar todos os adivinhos e todos os sábios do Egito. O rei contou os seus sonhos, mas nenhum dos sábios foi capaz de dar a explicação.

[[v1-41-9]]

^<<v1-41-9,9>>^ Então o chefe dos copeiros disse ao rei: — Chegou a hora de confessar um erro que cometi.

[[v1-41-10]]

^<<v1-41-10,10>>^ Um dia o senhor ficou com raiva de mim e do chefe dos padeiros e nos mandou para a cadeia, na casa do capitão da guarda.

[[v1-41-11]]

^<<v1-41-11,11>>^ Certa noite cada um de nós teve um sonho, e cada sonho queria dizer uma coisa.

[[v1-41-12]]

^<<v1-41-12,12>>^ Lá na cadeia estava com a gente um moço hebreu, que era escravo do capitão da guarda. Contamos a esse moço os nossos sonhos, e ele explicou o que queriam dizer.

[[v1-41-13]]

^<<v1-41-13,13>>^ E tudo deu certo, exatamente como ele havia falado. Eu voltei para o meu serviço, e o padeiro foi enforcado.

[[v1-41-14]]

^<<v1-41-14,14>>^ Então o rei mandou chamar José, e foram depressa tirá-lo da cadeia. Ele fez a barba, trocou de roupa e se apresentou ao rei.

[[v1-41-15]]

^<<v1-41-15,15>>^ Então o rei disse: — Eu tive um sonho que ninguém conseguiu explicar. Ouvi dizer que você é capaz de explicar sonhos.

[[v1-41-16]]

^<<v1-41-16,16>>^ — Isso não depende de mim — respondeu José. — É Deus quem vai dar uma resposta para o bem do senhor, ó rei.

[[v1-41-17]]

^<<v1-41-17,17>>^ Aí o rei disse: — Sonhei que estava de pé na beira do rio Nilo.

[[v1-41-18]]

^<<v1-41-18,18>>^ De repente, saíram do rio sete vacas bonitas e gordas, que começaram a comer o capim da beira do rio.

[[v1-41-19]]

^<<v1-41-19,19>>^ Depois saíram do rio outras sete vacas, mas estas eram feias e magras. Em toda a minha vida eu nunca vi no Egito vacas tão feias como aquelas.

[[v1-41-20]]

^<<v1-41-20,20>>^ E as vacas feias e magras engoliram as bonitas e gordas,

[[v1-41-21]]

^<<v1-41-21,21>>^ mas nem dava para notar isso, pois elas continuavam tão feias como antes. Então eu acordei.

[[v1-41-22]]

^<<v1-41-22,22>>^ Depois tive outro sonho. Eu vi sete espigas de trigo boas e cheias de grãos, as quais saíam de um mesmo pé.

[[v1-41-23]]

^<<v1-41-23,23>>^ Depois saíram sete espigas secas e queimadas pelo vento quente do deserto

[[v1-41-24]]

^<<v1-41-24,24>>^ e elas engoliram as sete espigas cheias e boas. Eu contei os sonhos aos adivinhos, mas nenhum deles foi capaz de explicá-los.

[[v1-41-25]]

^<<v1-41-25,25>>^ Então José disse ao rei: — Os dois sonhos querem dizer a mesma coisa. Por meio deles Deus está dizendo ao senhor o que ele vai fazer.

[[v1-41-26]]

^<<v1-41-26,26>>^ As sete vacas bonitas são sete anos, e as sete espigas boas também são. Os dois sonhos querem dizer uma coisa só.

[[v1-41-27]]

^<<v1-41-27,27>>^ As sete vacas magras e feias que saíram do rio depois das bonitas e também as sete espigas secas e queimadas pelo vento quente do deserto são sete anos em que vai faltar comida.

[[v1-41-28]]

^<<v1-41-28,28>>^ É exatamente como eu disse: Deus mostrou ao senhor, ó rei, o que ele vai fazer.

[[v1-41-29]]

^<<v1-41-29,29>>^ Virão sete anos em que vai haver muito alimento em todo o Egito.

[[v1-41-30]]

^<<v1-41-30,30>>^ Depois virão sete anos de fome.

[[v1-41-31]]

^<<v1-41-31,31>>^ E a fome será tão terrível, que ninguém lembrará do tempo em que houve muito alimento no Egito.

[[v1-41-32]]

^<<v1-41-32,32>>^ A repetição do sonho quer dizer que Deus resolveu fazer isso e vai fazer logo.

[[v1-41-33]]

^<<v1-41-33,33>>^ E José continuou: — Portanto, será bom que o senhor, ó rei, escolha um homem inteligente e sábio e o ponha para dirigir o país.

[[v1-41-34]]

^<<v1-41-34,34>>^ O rei também deve escolher homens que ficarão encarregados de viajar por todo o país para recolher a quinta parte de todas as colheitas, durante os sete anos em que elas forem boas.

[[v1-41-35]]

^<<v1-41-35,35>>^ Durante os anos bons que estão chegando, esses homens ajuntarão todo o trigo que puderem e o guardarão em armazéns nas cidades, sendo tudo controlado pelo senhor.

[[v1-41-36]]

^<<v1-41-36,36>>^ Assim, o mantimento servirá para abastecer o país durante os sete anos de fome no Egito, e o povo não morrerá de fome.

[[v1-41-37]]

^<<v1-41-37,37>>^ O conselho de José agradou ao rei e aos seus funcionários.

[[v1-41-38]]

^<<v1-41-38,38>>^ E o rei lhes disse: — Não poderíamos achar ninguém melhor para dirigir o país do que José, um homem em quem está o Espírito de Deus.

[[v1-41-39]]

^<<v1-41-39,39>>^ Depois virou-se para José e disse: — Deus lhe mostrou tudo isso, e assim está claro que não há ninguém que tenha mais capacidade e sabedoria do que você.

[[v1-41-40]]

^<<v1-41-40,40>>^ Você vai ficar encarregado do meu palácio, e todo o meu povo obedecerá às suas ordens. Só eu terei mais autoridade do que você, pois sou o rei.

[[v1-41-41]]

^<<v1-41-41,41>>^ Neste momento eu o ponho como governador de todo o Egito.

[[v1-41-42]]

^<<v1-41-42,42>>^ Então o rei tirou do dedo o seu anel-sinete  e o colocou no dedo de José. Em seguida mandou que o vestissem com roupas de linho fino e pôs uma corrente de ouro no pescoço dele.

[[v1-41-43]]

^<<v1-41-43,43>>^ Depois fez com que José subisse no carro reservado para a maior autoridade do Egito depois do rei e mandou que os seus homens fossem na frente dele, gritando: "Abram caminho!" Assim, José foi posto como governador de todo o Egito.

[[v1-41-44]]

^<<v1-41-44,44>>^ O rei disse a José: — Eu sou o rei, mas sem a sua licença ninguém poderá fazer nada em toda a terra do Egito.

[[v1-41-45]]

^<<v1-41-45,45>>^ O rei pôs em José o nome de Zafenate Paneia e lhe deu como esposa Asenate, filha de Potífera, que era sacerdote da cidade de Heliópolis. José tinha trinta anos quando entrou para o serviço do rei do Egito. Ele saiu da presença do rei e viajou por todo o Egito.

[[v1-41-46]]

^<<v1-41-46,46>>^ O rei pôs em José o nome de Zafenate Paneia e lhe deu como esposa Asenate, filha de Potífera, que era sacerdote da cidade de Heliópolis.

[[v1-41-47]]

^<<v1-41-47,47>>^ Durante os sete anos de fartura a terra produziu cereais em grande quantidade.

[[v1-41-48]]

^<<v1-41-48,48>>^ E José ajuntou todos os cereais e os guardou em armazéns nas cidades, ficando em cada cidade os cereais colhidos nos campos vizinhos.

[[v1-41-49]]

^<<v1-41-49,49>>^ José ajuntou tanto mantimento, que desistiu de pesar, pois não dava mais: parecia a areia da praia do mar.

[[v1-41-50]]

^<<v1-41-50,50>>^ Antes de começarem os anos de fome, José teve dois filhos com a sua mulher Asenate.

[[v1-41-51]]

^<<v1-41-51,51>>^ Pôs no primeiro o nome de Manassés e explicou assim: "Deus me fez esquecer todos os meus sofrimentos e toda a família do meu pai."

[[v1-41-52]]

^<<v1-41-52,52>>^ No segundo filho pôs o nome de Efraim e disse: "Deus me deu filhos no país onde tenho sofrido."

[[v1-41-53]]

^<<v1-41-53,53>>^ Então acabaram-se os sete anos de fartura no Egito,

[[v1-41-54]]

^<<v1-41-54,54>>^ e, como José tinha dito, começaram os sete anos de fome. Nos outros países o povo passava fome, mas em todo o Egito havia o que comer.

[[v1-41-55]]

^<<v1-41-55,55>>^ Quando os egípcios começaram a passar fome, foram pedir alimentos ao rei. Ele disse: — Vão falar com José e façam o que ele disser.

[[v1-41-56]]

^<<v1-41-56,56>>^ Quando a fome aumentou no país inteiro, José abriu todos os armazéns e começou a vender cereais aos egípcios.

'''

xref:001-genesis/001-genesis-040.adoc#v1-40-0[&#60; Capítulo Anterior] | <<v1-41-0,Topo>> | xref:001-genesis/001-genesis-042.adoc#v1-42-0[Próximo Capítulo &#62;]