include::./index.adoc[]

[[v1-20-0]]
=== Gênesis, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-20-1]]

^<<v1-20-1,1>>^ Abraão saiu de Manre, foi para o sul do país de Canaã e ficou morando entre Cades e Sur. Mais tarde, quando estava morando em Gerar,

[[v1-20-2]]

^<<v1-20-2,2>>^ Abraão dizia que Sara era sua irmã. Então Abimeleque, rei de Gerar, mandou que trouxessem Sara para o seu palácio.

[[v1-20-3]]

^<<v1-20-3,3>>^ Mas de noite, num sonho, Deus apareceu a Abimeleque e disse: — Você vai ser castigado com a morte porque a mulher que mandou buscar é casada.

[[v1-20-4]]

^<<v1-20-4,4>>^ Abimeleque ainda não havia tocado em Sara e por isso disse: — Senhor, eu estou inocente! Será que vais destruir a mim e ao meu povo?

[[v1-20-5]]

^<<v1-20-5,5>>^ O próprio Abraão disse que Sara é irmã dele, e ela disse a mesma coisa. O que eu fiz foi de boa fé e não sou culpado.

[[v1-20-6]]

^<<v1-20-6,6>>^ No sonho Deus respondeu: — Eu sei que você fez tudo de boa fé. Portanto, para que você não pecasse contra mim, eu não deixei que você tocasse nela.

[[v1-20-7]]

^<<v1-20-7,7>>^ Agora devolva a mulher ao marido dela. Ele é profeta  e orará para que você não morra. Mas, se a mulher não for devolvida, eu estou avisando que certamente você morrerá, você e todos os seus.

[[v1-20-8]]

^<<v1-20-8,8>>^ No dia seguinte Abimeleque levantou-se bem cedo, chamou todos os seus servidores e lhes contou o que havia acontecido. E eles ficaram com muito medo.

[[v1-20-9]]

^<<v1-20-9,9>>^ Em seguida Abimeleque chamou Abraão e disse: — Veja o que você fez! Que mal eu lhe causei para que você fizesse cair sobre mim e sobre o meu país a culpa de um pecado tão grande? Isso não é coisa que se faça.

[[v1-20-10]]

^<<v1-20-10,10>>^ O que é que você estava pensando quando fez isso?

[[v1-20-11]]

^<<v1-20-11,11>>^ Abraão respondeu: — Eu pensei que neste lugar ninguém respeitasse a Deus e que me matariam para ficar com a minha mulher.

[[v1-20-12]]

^<<v1-20-12,12>>^ Além disso Sara é, de fato, minha irmã, mas só por parte de pai. Sendo assim, eu pude casar com ela.

[[v1-20-13]]

^<<v1-20-13,13>>^ Quando Deus me tirou da casa do meu pai e me fez andar por terras estrangeiras, eu disse a Sara: "Em todo lugar aonde formos, faça-me o favor de dizer que sou seu irmão."

[[v1-20-14]]

^<<v1-20-14,14>>^ Então Abimeleque devolveu Sara a Abraão. Além disso lhe deu ovelhas, bois, escravos e escravas.

[[v1-20-15]]

^<<v1-20-15,15>>^ E disse: — Olhe, Abraão, aí estão as minhas terras. More onde quiser.

[[v1-20-16]]

^<<v1-20-16,16>>^ E Abimeleque disse a Sara o seguinte: — Estou dando ao seu irmão onze quilos e meio de prata para que os que estão com você saibam que você está inocente. Assim, todos saberão que você não fez nada de errado.

[[v1-20-17]]

^<<v1-20-17,17>>^ Por causa do que tinha acontecido com Sara, a mulher de Abraão, o Senhor  Deus havia feito com que nenhuma das mulheres do palácio de Abimeleque pudesse ter filhos. Aí Abraão orou em favor de Abimeleque, e Deus o curou. E também curou a mulher dele e as suas escravas, e assim puderam ter filhos novamente.

'''

xref:001-genesis/001-genesis-019.adoc#v1-19-0[&#60; Capítulo Anterior] | <<v1-20-0,Topo>> | xref:001-genesis/001-genesis-021.adoc#v1-21-0[Próximo Capítulo &#62;]