include::./index.adoc[]

[[v1-3-0]]
=== Gênesis, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-3-1]]

^<<v1-3-1,1>>^ A cobra era o animal mais esperto que o Senhor  Deus havia feito. Ela perguntou à mulher: — É verdade que Deus mandou que vocês não comessem as frutas de nenhuma árvore do jardim?

[[v1-3-2]]

^<<v1-3-2,2>>^ A mulher respondeu: — Podemos comer as frutas de qualquer árvore,

[[v1-3-3]]

^<<v1-3-3,3>>^ menos a fruta da árvore que fica no meio do jardim. Deus nos disse que não devemos comer dessa fruta, nem tocar nela. Se fizermos isso, morreremos.

[[v1-3-4]]

^<<v1-3-4,4>>^ Mas a cobra afirmou: — Vocês não morrerão coisa nenhuma!

[[v1-3-5]]

^<<v1-3-5,5>>^ Deus disse isso porque sabe que, quando vocês comerem a fruta dessa árvore, os seus olhos se abrirão, e vocês serão como Deus, conhecendo o bem e o mal.

[[v1-3-6]]

^<<v1-3-6,6>>^ A mulher viu que a árvore era bonita e que as suas frutas eram boas de se comer. E ela pensou como seria bom ter entendimento. Aí apanhou uma fruta e comeu; e deu ao seu marido, e ele também comeu.

[[v1-3-7]]

^<<v1-3-7,7>>^ Nesse momento os olhos dos dois se abriram, e eles perceberam que estavam nus. Então costuraram umas folhas de figueira para usar como tangas.

[[v1-3-8]]

^<<v1-3-8,8>>^ Naquele dia, quando soprava o vento suave da tarde, o homem e a sua mulher ouviram a voz do Senhor  Deus, que estava passeando pelo jardim. Então se esconderam dele, no meio das árvores.

[[v1-3-9]]

^<<v1-3-9,9>>^ Mas o Senhor  Deus chamou o homem e perguntou: — Onde é que você está?

[[v1-3-10]]

^<<v1-3-10,10>>^ O homem respondeu: — Eu ouvi a tua voz, quando estavas passeando pelo jardim, e fiquei com medo porque estava nu. Por isso me escondi.

[[v1-3-11]]

^<<v1-3-11,11>>^ Aí Deus perguntou: — E quem foi que lhe disse que você estava nu? Por acaso você comeu a fruta da árvore que eu o proibi de comer?

[[v1-3-12]]

^<<v1-3-12,12>>^ O homem disse: — A mulher que me deste para ser a minha companheira me deu a fruta, e eu comi.

[[v1-3-13]]

^<<v1-3-13,13>>^ Então o Senhor  Deus perguntou à mulher: — Por que você fez isso? A mulher respondeu: — A cobra me enganou, e eu comi.

[[v1-3-14]]

^<<v1-3-14,14>>^ Então o Senhor  Deus disse à cobra: — Por causa do que você fez você será castigada. Entre todos os animais só você receberá esta maldição: de hoje em diante você vai andar se arrastando pelo chão e vai comer o pó da terra.

[[v1-3-15]]

^<<v1-3-15,15>>^ Eu farei com que você e a mulher sejam inimigas uma da outra, e assim também serão inimigas a sua descendência e a descendência dela. Esta esmagará a sua cabeça, e você picará o calcanhar da descendência dela.

[[v1-3-16]]

^<<v1-3-16,16>>^ Para a mulher Deus disse: — Vou aumentar o seu sofrimento na gravidez, e com muita dor você dará à luz filhos. Apesar disso, você terá desejo de estar com o seu marido, e ele a dominará.

[[v1-3-17]]

^<<v1-3-17,17>>^ E para Adão Deus disse o seguinte: — Você fez o que a sua mulher disse e comeu a fruta da árvore que eu o proibi de comer. Por causa do que você fez, a terra será maldita. Você terá de trabalhar duramente a vida inteira a fim de que a terra produza alimento suficiente para você.

[[v1-3-18]]

^<<v1-3-18,18>>^ Ela lhe dará mato e espinhos, e você terá de comer ervas do campo.

[[v1-3-19]]

^<<v1-3-19,19>>^ Terá de trabalhar no pesado e suar para fazer com que a terra produza algum alimento; isso até que você volte para a terra, pois dela você foi formado. Você foi feito de terra e vai virar terra outra vez.

[[v1-3-20]]

^<<v1-3-20,20>>^ O homem pôs na sua mulher o nome de Eva por ser ela a mãe de todos os seres humanos.

[[v1-3-21]]

^<<v1-3-21,21>>^ E o Senhor  Deus fez roupas de peles de animais para Adão e a sua mulher se vestirem.

[[v1-3-22]]

^<<v1-3-22,22>>^ Então o Senhor  Deus disse o seguinte: — Agora o homem se tornou como um de nós, pois conhece o bem e o mal. Ele não deve comer a fruta da árvore da vida e viver para sempre.

[[v1-3-23]]

^<<v1-3-23,23>>^ Por isso o Senhor  Deus expulsou o homem do jardim do Éden e fez com que ele cultivasse a terra da qual havia sido formado.

[[v1-3-24]]

^<<v1-3-24,24>>^ Deus expulsou o homem e no lado leste do jardim pôs os querubins  e uma espada de fogo que dava voltas em todas as direções. Deus fez isso para que ninguém chegasse perto da árvore da vida.

'''

xref:001-genesis/001-genesis-002.adoc#v1-2-0[&#60; Capítulo Anterior] | <<v1-3-0,Topo>> | xref:001-genesis/001-genesis-004.adoc#v1-4-0[Próximo Capítulo &#62;]