include::./index.adoc[]

[[v1-44-0]]
=== Gênesis, 44
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-44-1]]

^<<v1-44-1,1>>^ Depois disso José deu ao administrador da sua casa a seguinte ordem: — Encha de mantimento os sacos que esses homens trouxeram, o quanto puderem carregar, e ponha na boca dos sacos o dinheiro de cada um.

[[v1-44-2]]

^<<v1-44-2,2>>^ E, na boca do saco de mantimentos que pertence ao irmão mais moço, ponha o meu copo de prata, junto com o dinheiro que ele pagou pelo seu mantimento. O administrador fez tudo como José havia mandado.

[[v1-44-3]]

^<<v1-44-3,3>>^ De manhã bem cedo os irmãos de José saíram de viagem, com os seus jumentos.

[[v1-44-4]]

^<<v1-44-4,4>>^ Quando eles já tinham saído da cidade, mas ainda não estavam longe, José disse ao seu administrador: — Vá depressa atrás daqueles homens e, quando os alcançar, diga o seguinte: "Por que vocês pagaram o bem com o mal?

[[v1-44-5]]

^<<v1-44-5,5>>^ Por que roubaram o copo de prata do meu patrão? Ele usa esse copo para beber e para adivinhar as coisas. Vocês cometeram um crime."

[[v1-44-6]]

^<<v1-44-6,6>>^ Quando o administrador os alcançou e disse o que José havia ordenado,

[[v1-44-7]]

^<<v1-44-7,7>>^ eles responderam: — Por que o senhor está falando desse jeito? Nós não seríamos capazes de fazer uma coisa dessas!

[[v1-44-8]]

^<<v1-44-8,8>>^ Nós lhe trouxemos de volta do país de Canaã o dinheiro que encontramos na boca dos sacos de mantimentos de cada um de nós. Então por que iríamos roubar prata ou ouro da casa do seu patrão?

[[v1-44-9]]

^<<v1-44-9,9>>^ Se o senhor encontrar o copo com algum de nós, ele será morto, e nós ficaremos seus escravos.

[[v1-44-10]]

^<<v1-44-10,10>>^ O administrador disse: — Concordo com vocês, mas só aquele com quem estiver o copo é que será meu escravo; os outros poderão ir embora.

[[v1-44-11]]

^<<v1-44-11,11>>^ Então eles puseram depressa os sacos de mantimentos no chão, e cada um abriu o seu.

[[v1-44-12]]

^<<v1-44-12,12>>^ O administrador de José procurou em cada saco de mantimentos, começando pelo do mais velho até o do mais moço; e o copo foi encontrado na boca do saco de mantimentos de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Então os irmãos rasgaram as suas roupas em sinal de tristeza, colocaram de novo as cargas em cima dos jumentos e voltaram para a cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ Quando Judá e os seus irmãos chegaram à casa de José, ele ainda estava ali. Eles se ajoelharam na frente dele e encostaram o rosto no chão.

[[v1-44-15]]

^<<v1-44-15,15>>^ Aí José perguntou: — Por que foi que vocês fizeram isso? Vocês não sabiam que um homem como eu é capaz de adivinhar as coisas?

[[v1-44-16]]

^<<v1-44-16,16>>^ Judá respondeu: — Senhor, o que podemos falar ou responder? Como podemos provar que somos inocentes? Deus descobriu o nosso pecado. Aqui estamos e somos todos seus escravos, nós e aquele com quem estava o copo.

[[v1-44-17]]

^<<v1-44-17,17>>^ José disse: — De jeito nenhum! Eu nunca faria uma coisa dessas! Só aquele que estava com o meu copo é que será meu escravo. Os outros podem voltar em paz para a casa do pai.

[[v1-44-18]]

^<<v1-44-18,18>>^ Então Judá chegou perto de José e disse: — Senhor, me dê licença para lhe falar com franqueza. Não fique aborrecido comigo, pois o senhor é como se fosse o próprio rei.

[[v1-44-19]]

^<<v1-44-19,19>>^ O senhor perguntou: "Vocês têm pai ou outro irmão?"

[[v1-44-20]]

^<<v1-44-20,20>>^ Nós respondemos assim: "Temos pai, já velho, e um irmão mais moço, que nasceu quando o nosso pai já estava velho. O irmão do rapazinho morreu. Agora ele é o único filho da sua mãe que está vivo, e o seu pai o ama muito."

[[v1-44-21]]

^<<v1-44-21,21>>^ Aí o senhor nos disse para trazer o rapazinho porque desejava vê-lo.

[[v1-44-22]]

^<<v1-44-22,22>>^ Nós respondemos que ele não podia deixar o seu pai, pois, se deixasse, o seu pai morreria.

[[v1-44-23]]

^<<v1-44-23,23>>^ Mas o senhor disse que, se ele não viesse, o senhor não nos receberia.

[[v1-44-24]]

^<<v1-44-24,24>>^ — Quando chegamos à nossa casa, contamos ao nosso pai tudo o que o senhor tinha dito.

[[v1-44-25]]

^<<v1-44-25,25>>^ Depois ele nos mandou voltar para comprarmos mais mantimentos.

[[v1-44-26]]

^<<v1-44-26,26>>^ Nós respondemos: "Não podemos ir; não seremos recebidos por aquele homem se o nosso irmão mais moço não for com a gente. Nós só vamos se o nosso irmão mais moço for junto."

[[v1-44-27]]

^<<v1-44-27,27>>^ Então o nosso pai disse: "Vocês sabem que a minha mulher Raquel me deu dois filhos.

[[v1-44-28]]

^<<v1-44-28,28>>^ Um deles já me deixou; eu nunca mais o vi. Deve ter sido despedaçado por animais selvagens.

[[v1-44-29]]

^<<v1-44-29,29>>^ E, se agora vocês me tirarem este também, e alguma desgraça acontecer com ele, vocês matarão de tristeza este velho."

[[v1-44-30]]

^<<v1-44-30,30>>^ — Agora, senhor — continuou Judá — se eu voltar para casa sem o rapaz, logo que o meu pai perceber isso, vai morrer. A vida dele está ligada com a vida do rapaz, e nós seríamos culpados de matar de tristeza o nosso pai, que está velho.

[[v1-44-31]]

^<<v1-44-31,31>>^ — Agora, senhor — continuou Judá — se eu voltar para casa sem o rapaz, logo que o meu pai perceber isso, vai morrer. A vida dele está ligada com a vida do rapaz, e nós seríamos culpados de matar de tristeza o nosso pai, que está velho.

[[v1-44-32]]

^<<v1-44-32,32>>^ E tem mais: eu garanti ao meu pai que seria responsável pelo rapaz. Eu disse assim: "Se eu não lhe trouxer o rapaz de volta, serei culpado diante do senhor pelo resto da minha vida."

[[v1-44-33]]

^<<v1-44-33,33>>^ Por isso agora eu peço ao senhor que me deixe ficar aqui como seu escravo em lugar do rapaz. E permita que ele volte com os seus irmãos.

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]