include::./index.adoc[]

[[v1-15-0]]
=== Gênesis, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-15-1]]

^<<v1-15-1,1>>^ Depois disso Abrão teve uma visão, e nela o Senhor  lhe disse: — Abrão, não tenha medo. Eu o protegerei de todo perigo e lhe darei uma grande recompensa.

[[v1-15-2]]

^<<v1-15-2,2>>^ Abrão respondeu: — Ó Senhor , meu Deus! De que vale a tua recompensa se eu continuo sem filhos? Eliézer, de Damasco, é quem vai herdar tudo o que tenho.

[[v1-15-3]]

^<<v1-15-3,3>>^ Tu não me deste filhos, e por isso um dos meus empregados, nascido na minha casa, será o meu herdeiro.

[[v1-15-4]]

^<<v1-15-4,4>>^ Então o Senhor  falou de novo e disse: — O seu próprio filho será o seu herdeiro, e não o seu empregado Eliézer.

[[v1-15-5]]

^<<v1-15-5,5>>^ Aí o Senhor  levou Abrão para fora e disse: — Olhe para o céu e conte as estrelas se puder. Pois bem! Será esse o número dos seus descendentes.

[[v1-15-6]]

^<<v1-15-6,6>>^ Abrão creu em Deus, o Senhor , e por isso o Senhor  o aceitou.

[[v1-15-7]]

^<<v1-15-7,7>>^ O Senhor  disse também: — Eu sou Deus, o Senhor ; eu o tirei da Babilônia, da cidade de Ur, a fim de lhe dar esta terra para ser sua propriedade.

[[v1-15-8]]

^<<v1-15-8,8>>^ — Ó Senhor , meu Deus! — disse Abrão. — Como posso ter certeza de que esta terra será minha?

[[v1-15-9]]

^<<v1-15-9,9>>^ O Senhor  respondeu: — Traga para mim uma vaca, uma cabra e uma ovelha, todas de três anos, e também uma rolinha e um pombo.

[[v1-15-10]]

^<<v1-15-10,10>>^ Abrão levou esses animais para o Senhor , cortou-os pelo meio e colocou as metades uma em frente à outra, em duas fileiras; porém as aves ele não cortou.

[[v1-15-11]]

^<<v1-15-11,11>>^ Então os urubus começaram a descer sobre os animais mortos, mas Abrão os enxotava.

[[v1-15-12]]

^<<v1-15-12,12>>^ Quando começou a anoitecer, Abrão caiu num sono profundo. De repente, ficou com medo, e o pavor tomou conta dele.

[[v1-15-13]]

^<<v1-15-13,13>>^ Então o Senhor  disse: — Fique sabendo, com certeza, que os seus descendentes viverão num país estrangeiro; ali serão escravos e serão maltratados durante quatrocentos anos.

[[v1-15-14]]

^<<v1-15-14,14>>^ Mas eu castigarei a nação que os escravizar. E os seus descendentes, Abrão, sairão livres, levando muitas riquezas.

[[v1-15-15]]

^<<v1-15-15,15>>^ Você terá uma velhice abençoada, morrerá em paz, será sepultado e irá se reunir com os seus antepassados no mundo dos mortos .

[[v1-15-16]]

^<<v1-15-16,16>>^ Depois de quatro gerações , os seus descendentes voltarão para cá; pois eu não expulsarei os amorreus até que eles se tornem tão maus, que mereçam ser castigados.

[[v1-15-17]]

^<<v1-15-17,17>>^ A noite caiu, e veio a escuridão. De repente, apareceu um braseiro, que soltava fumaça, e uma tocha de fogo. E o braseiro e a tocha passaram pelo meio dos animais partidos.

[[v1-15-18]]

^<<v1-15-18,18>>^ Nessa mesma ocasião o Senhor  Deus fez uma aliança  com Abrão. Ele disse: — Prometo dar aos seus descendentes esta terra, desde a fronteira com o Egito até o rio Eufrates,

[[v1-15-19]]

^<<v1-15-19,19>>^ incluindo as terras dos queneus, dos quenezeus, dos cadmoneus,

[[v1-15-20]]

^<<v1-15-20,20>>^ dos heteus, dos perizeus, dos refains ,

[[v1-15-21]]

^<<v1-15-21,21>>^ dos amorreus, dos cananeus, dos girgaseus e dos jebuseus.

'''

xref:001-genesis/001-genesis-014.adoc#v1-14-0[&#60; Capítulo Anterior] | <<v1-15-0,Topo>> | xref:001-genesis/001-genesis-016.adoc#v1-16-0[Próximo Capítulo &#62;]