include::./index.adoc[]

[[v1-32-0]]
=== Gênesis, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-32-1]]

^<<v1-32-1,1>>^ Jacó estava continuando a sua viagem quando alguns anjos de Deus foram encontrar-se com ele.

[[v1-32-2]]

^<<v1-32-2,2>>^ Quando Jacó os viu, disse: — Este é o acampamento de Deus. Por isso pôs naquele lugar o nome de Maanaim .

[[v1-32-3]]

^<<v1-32-3,3>>^ Jacó mandou mensageiros para a região de Seir, também chamada de Edom, a fim de se encontrarem com Esaú

[[v1-32-4]]

^<<v1-32-4,4>>^ e lhe darem esta mensagem: "Eu, Jacó, estou às suas ordens para servi-lo. Durante todo esse tempo morei com Labão.

[[v1-32-5]]

^<<v1-32-5,5>>^ Tenho gado, jumentos, ovelhas, cabras, escravos e escravas. Estou mandando este recado ao senhor, esperando ser bem-recebido."

[[v1-32-6]]

^<<v1-32-6,6>>^ Os mensageiros voltaram e disseram: — Estivemos com Esaú, o seu irmão. Ele já vem vindo para se encontrar com o senhor. E vem com quatrocentos homens.

[[v1-32-7]]

^<<v1-32-7,7>>^ Quando Jacó ouviu isso, teve muito medo e ficou preocupado. Então dividiu em dois grupos a gente que estava com ele e também as ovelhas, as cabras, o gado e os camelos.

[[v1-32-8]]

^<<v1-32-8,8>>^ Ele pensou que, se Esaú viesse e atacasse um grupo, o outro poderia escapar.

[[v1-32-9]]

^<<v1-32-9,9>>^ Depois Jacó fez esta oração: — Ouve-me, ó Senhor , Deus do meu avô Abraão e de Isaque, o meu pai! Tu me mandaste voltar para a minha terra e para os meus parentes, prometendo que tudo correria bem para mim.

[[v1-32-10]]

^<<v1-32-10,10>>^ Eu, teu servo , não mereço toda a bondade e fidelidade com que me tens tratado. Quando atravessei o rio Jordão, eu tinha apenas um bastão e agora estou voltando com estes dois grupos de pessoas e animais.

[[v1-32-11]]

^<<v1-32-11,11>>^ Ó Senhor , eu te peço que me salves do meu irmão Esaú. Tenho medo de que ele venha e me mate e também as mulheres e as crianças.

[[v1-32-12]]

^<<v1-32-12,12>>^ Lembra que prometeste que tudo me correria bem e que os meus descendentes seriam como a areia da praia, tantos que ninguém poderia contar.

[[v1-32-13]]

^<<v1-32-13,13>>^ Naquela noite Jacó dormiu ali. Depois ele escolheu alguns dos seus animais para dar de presente a Esaú.

[[v1-32-14]]

^<<v1-32-14,14>>^ Escolheu duzentas cabras e vinte bodes, duzentas ovelhas e vinte carneiros,

[[v1-32-15]]

^<<v1-32-15,15>>^ trinta camelas com as suas crias, que ainda mamavam, quarenta vacas e dez touros, e vinte jumentas e dez jumentos.

[[v1-32-16]]

^<<v1-32-16,16>>^ Jacó dividiu esses animais em grupos e pôs um empregado para tomar conta de cada grupo. E deu esta ordem: — Vocês vão na frente, deixando um espaço entre os grupos.

[[v1-32-17]]

^<<v1-32-17,17>>^ Jacó disse ao primeiro empregado: — Quando o meu irmão Esaú se encontrar com você, ele vai perguntar: "Quem é o seu patrão? Aonde você vai? E de quem são esses animais que você vai levando?"

[[v1-32-18]]

^<<v1-32-18,18>>^ Então responda assim: "Estes animais são do seu criado Jacó. São um presente que ele está enviando ao seu patrão Esaú. E ele também vem vindo aí atrás."

[[v1-32-19]]

^<<v1-32-19,19>>^ Também ao segundo, e ao terceiro, e a todos os outros que tomavam conta dos grupos, Jacó disse: — Quando vocês se encontrarem com Esaú, digam a mesma coisa.

[[v1-32-20]]

^<<v1-32-20,20>>^ E não esqueçam de dizer isto: "O seu criado Jacó vem vindo aí atrás." É que Jacó estava pensando assim: "Vou acalmar Esaú com os presentes que irão na minha frente. E, quando nos encontrarmos, talvez ele me perdoe."

[[v1-32-21]]

^<<v1-32-21,21>>^ Desse modo Jacó mandou os presentes na frente e passou aquela noite no acampamento.

[[v1-32-22]]

^<<v1-32-22,22>>^ Naquela mesma noite Jacó se levantou e atravessou o rio Jaboque, levando consigo as suas duas mulheres, as suas duas concubinas  e os seus onze filhos.

[[v1-32-23]]

^<<v1-32-23,23>>^ Depois que as pessoas passaram, Jacó fez com que também passasse tudo o que era seu;

[[v1-32-24]]

^<<v1-32-24,24>>^ mas ele ficou para trás, sozinho. Aí veio um homem que lutou com ele até o dia amanhecer.

[[v1-32-25]]

^<<v1-32-25,25>>^ Quando o homem viu que não podia vencer, deu um golpe na junta da coxa de Jacó, de modo que ela ficou fora do lugar.

[[v1-32-26]]

^<<v1-32-26,26>>^ Então o homem disse: — Solte-me, pois já está amanhecendo. — Não solto enquanto o senhor não me abençoar — respondeu Jacó.

[[v1-32-27]]

^<<v1-32-27,27>>^ Aí o homem perguntou: — Como você se chama? — Jacó — respondeu ele.

[[v1-32-28]]

^<<v1-32-28,28>>^ Então o homem disse: — O seu nome não será mais Jacó. Você lutou com Deus e com os homens e venceu; por isso o seu nome será Israel .

[[v1-32-29]]

^<<v1-32-29,29>>^ — Agora diga-me o seu nome — pediu Jacó. O homem respondeu: — Por que você quer saber o meu nome? E ali ele abençoou Jacó.

[[v1-32-30]]

^<<v1-32-30,30>>^ Então Jacó disse: — Eu vi Deus face a face, mas ainda estou vivo. Por isso ele pôs naquele lugar o nome de Peniel .

[[v1-32-31]]

^<<v1-32-31,31>>^ O sol nasceu quando Jacó estava saindo de Peniel, e ele ia mancando por causa do golpe que havia levado na coxa.

[[v1-32-32]]

^<<v1-32-32,32>>^ Até hoje  os descendentes de Israel não comem o músculo que fica na junta da coxa, pois foi nessa parte do corpo que ele recebeu o golpe.

'''

xref:001-genesis/001-genesis-031.adoc#v1-31-0[&#60; Capítulo Anterior] | <<v1-32-0,Topo>> | xref:001-genesis/001-genesis-033.adoc#v1-33-0[Próximo Capítulo &#62;]