include::./index.adoc[]

[[v1-19-0]]
=== Gênesis, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-19-1]]

^<<v1-19-1,1>>^ Estava anoitecendo quando os dois anjos chegaram a Sodoma. Ló estava sentado perto do portão de entrada da cidade. Quando viu os anjos, levantou-se e foi recebê-los. Ajoelhou-se, encostou o rosto no chão

[[v1-19-2]]

^<<v1-19-2,2>>^ e disse: — Senhores, estou aqui para servi-los; por favor, aceitem o meu convite e venham se hospedar na minha casa. Os senhores podem lavar os pés e passar a noite ali. Depois se levantarão bem cedo e continuarão a sua viagem. Eles disseram: — Não; nós vamos passar a noite na praça.

[[v1-19-3]]

^<<v1-19-3,3>>^ Mas Ló insistiu tanto, que eles aceitaram e foram com ele para a sua casa. Ló mandou preparar um bom jantar e assar pães sem fermento. E os visitantes jantaram.

[[v1-19-4]]

^<<v1-19-4,4>>^ Mas, antes que eles fossem dormir, todos os homens de Sodoma, tanto os moços como os velhos, cercaram a casa.

[[v1-19-5]]

^<<v1-19-5,5>>^ Eles chamaram Ló e perguntaram: — Onde estão os homens que entraram na sua casa esta noite? Traga-os aqui fora para nós, pois queremos ter relações com eles.

[[v1-19-6]]

^<<v1-19-6,6>>^ Ló saiu para falar com os homens. Ele fechou bem a porta

[[v1-19-7]]

^<<v1-19-7,7>>^ e disse: — Por favor, meus amigos, não cometam esse crime!

[[v1-19-8]]

^<<v1-19-8,8>>^ Prestem atenção! Tenho duas filhas que ainda são virgens. Vou trazê-las aqui fora para vocês. Façam com elas o que quiserem. Porém não façam nada com esses homens, pois são meus hóspedes, e eu tenho o dever de protegê-los.

[[v1-19-9]]

^<<v1-19-9,9>>^ Mas eles responderam: — Saia da nossa frente! E diziam uns aos outros: — Esse homem é estrangeiro e quer mandar em nós! Depois, virando-se para Ló, disseram: — Pois agora vamos fazer com você pior ainda do que íamos fazer com os seus hóspedes. Os homens de Sodoma se atiraram contra Ló e chegaram perto da porta para arrombá-la.

[[v1-19-10]]

^<<v1-19-10,10>>^ Mas os visitantes pegaram Ló, e o puxaram para dentro da casa, e fecharam a porta.

[[v1-19-11]]

^<<v1-19-11,11>>^ Em seguida eles fizeram que os homens, tanto os moços como os velhos, que estavam do lado de fora, ficassem cegos; e assim não conseguiram encontrar a porta.

[[v1-19-12]]

^<<v1-19-12,12>>^ Então os visitantes disseram a Ló: — Tem mais gente sua aqui? Pegue os seus filhos, as suas filhas, os seus genros e outros parentes que você tiver na cidade e tire todos daqui,

[[v1-19-13]]

^<<v1-19-13,13>>^ pois nós vamos destruir este lugar. O Senhor  Deus tem ouvido as terríveis acusações que há contra essa gente e por isso nos mandou para destruirmos Sodoma.

[[v1-19-14]]

^<<v1-19-14,14>>^ Então Ló saiu e foi falar com os homens que iam casar com as suas filhas. Ele disse: — Arrumem-se depressa e saiam daqui porque o Senhor  vai destruir a cidade! Mas eles pensaram que Ló estivesse brincando.

[[v1-19-15]]

^<<v1-19-15,15>>^ De madrugada os anjos insistiram com Ló, dizendo: — Arrume-se depressa, pegue a sua mulher e as suas duas filhas e saia daqui, para que vocês não morram quando a cidade for destruída.

[[v1-19-16]]

^<<v1-19-16,16>>^ E, como ele estava demorando, os anjos pegaram pela mão Ló, a sua mulher e as suas filhas e os levaram para fora da cidade, pois o Senhor  teve compaixão de Ló.

[[v1-19-17]]

^<<v1-19-17,17>>^ Então um dos anjos disse a Ló: — Agora corra e salve a sua vida! Não olhe para trás, nem pare neste vale. Fuja para a montanha; se não, você vai morrer.

[[v1-19-18]]

^<<v1-19-18,18>>^ Mas Ló respondeu: — Senhor, não me obrigue a fazer isso, por favor!

[[v1-19-19]]

^<<v1-19-19,19>>^ O senhor me fez um grande favor e teve pena de mim, salvando a minha vida. Mas a montanha fica muito longe daqui, e a destruição vai me alcançar e acabar comigo antes que eu chegue lá.

[[v1-19-20]]

^<<v1-19-20,20>>^ Está vendo aquela cidadezinha ali? Ela fica perto. Deixe que eu fuja para lá a fim de salvar a minha vida. Veja que é uma cidade bem pequena.

[[v1-19-21]]

^<<v1-19-21,21>>^ Então o anjo disse: — Está bem; concordo. Eu não destruirei aquela cidade.

[[v1-19-22]]

^<<v1-19-22,22>>^ Agora vá depressa, pois eu não poderei fazer nada enquanto você não chegar lá. Ló tinha dito que a cidade era bem pequena, e por isso ela recebeu o nome de Zoar .

[[v1-19-23]]

^<<v1-19-23,23>>^ Ló chegou a Zoar depois que o sol já havia saído.

[[v1-19-24]]

^<<v1-19-24,24>>^ De repente, lá do céu, o Senhor  Deus fez chover fogo e enxofre sobre Sodoma e Gomorra.

[[v1-19-25]]

^<<v1-19-25,25>>^ Ele destruiu essas duas cidades, e também todo o vale e os seus moradores, e acabou com todas as plantas e árvores daquela região.

[[v1-19-26]]

^<<v1-19-26,26>>^ E aconteceu que a mulher de Ló olhou para trás e virou uma estátua de sal.

[[v1-19-27]]

^<<v1-19-27,27>>^ No dia seguinte Abraão se levantou de madrugada e foi até o lugar onde havia falado com Deus, o Senhor .

[[v1-19-28]]

^<<v1-19-28,28>>^ Abraão olhou na direção de Sodoma, de Gomorra e de todo o vale e viu que da terra subia fumaça, como se fosse a fumaça de uma grande fornalha.

[[v1-19-29]]

^<<v1-19-29,29>>^ Foi assim que Deus destruiu as cidades do vale. Mas ele pensou em Abraão e fez com que Ló escapasse da destruição das cidades onde havia morado.

[[v1-19-30]]

^<<v1-19-30,30>>^ Ló teve medo de ficar morando em Zoar e por isso foi para as montanhas, junto com as duas filhas. Ali os três viviam numa caverna.

[[v1-19-31]]

^<<v1-19-31,31>>^ Certo dia a filha mais velha disse à mais nova: — O nosso pai já está ficando velho, e não há nenhum outro homem nesta região. Assim não podemos casar e ter filhos, como é costume em toda parte.

[[v1-19-32]]

^<<v1-19-32,32>>^ Venha cá, vamos dar vinho a papai até que fique bêbado. Então nós nos deitaremos com ele e assim teremos filhos dele.

[[v1-19-33]]

^<<v1-19-33,33>>^ Naquela mesma noite elas deram vinho ao pai, e a filha mais velha teve relações com ele. Mas ele estava tão bêbado, que não percebeu nada.

[[v1-19-34]]

^<<v1-19-34,34>>^ No dia seguinte a filha mais velha disse à irmã: — Eu dormi ontem à noite com papai. Vamos embebedá-lo de novo hoje à noite, e você vai dormir com ele. Assim, nós duas teremos filhos com ele e conservaremos a sua descendência.

[[v1-19-35]]

^<<v1-19-35,35>>^ Nessa noite tornaram a dar vinho ao pai, e a filha mais nova teve relações com ele. De novo ele estava tão bêbado, que não percebeu nada.

[[v1-19-36]]

^<<v1-19-36,36>>^ Assim, as duas filhas de Ló ficaram grávidas do próprio pai.

[[v1-19-37]]

^<<v1-19-37,37>>^ A mais velha teve um filho, a quem deu o nome de Moabe . Ele foi o pai dos moabitas de hoje .

[[v1-19-38]]

^<<v1-19-38,38>>^ A mais nova também teve um filho e pôs nele o nome de Ben-Ami . Ele foi o pai dos amonitas de hoje.

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]