include::./index.adoc[]

[[v1-45-0]]
=== Gênesis, 45
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-45-1]]

^<<v1-45-1,1>>^ José não conseguiu mais controlar a sua emoção diante dos seus empregados, de modo que gritou: — Saiam todos daqui! Por isso nenhum dos empregados estava ali quando José contou aos irmãos quem ele era.

[[v1-45-2]]

^<<v1-45-2,2>>^ Ele começou a chorar tão alto, que os egípcios ouviram, e a notícia chegou até o palácio do rei.

[[v1-45-3]]

^<<v1-45-3,3>>^ José disse aos irmãos: — Eu sou José. O meu pai ainda está vivo? Quando os irmãos ouviram isso, ficaram tão assustados, que não puderam responder nada.

[[v1-45-4]]

^<<v1-45-4,4>>^ E José disse: — Cheguem mais perto de mim, por favor. Eles chegaram, e ele continuou: — Eu sou o seu irmão José, aquele que vocês venderam a fim de ser trazido para o Egito.

[[v1-45-5]]

^<<v1-45-5,5>>^ Agora não fiquem tristes nem aborrecidos com vocês mesmos por terem me vendido a fim de ser trazido para cá. Foi para salvar vidas que Deus me enviou na frente de vocês.

[[v1-45-6]]

^<<v1-45-6,6>>^ Já houve dois anos de fome no mundo, e ainda haverá mais cinco anos em que ninguém vai preparar a terra, nem colher.

[[v1-45-7]]

^<<v1-45-7,7>>^ Deus me enviou na frente de vocês a fim de que ele, de um modo maravilhoso, salvasse a vida de vocês aqui neste país e garantisse que teriam descendentes.

[[v1-45-8]]

^<<v1-45-8,8>>^ Portanto, não foram vocês que me mandaram para cá, mas foi Deus. Ele me pôs como o mais alto ministro do rei. Eu tomo conta do palácio dele e sou o governador de todo o Egito.

[[v1-45-9]]

^<<v1-45-9,9>>^ — Agora voltem depressa para casa e digam ao meu pai que o seu filho José manda lhe dizer o seguinte: "Deus me fez governador de todo o Egito. Venha me ver logo; não demore.

[[v1-45-10]]

^<<v1-45-10,10>>^ O senhor morará na região de Gosém e assim ficará perto de mim — o senhor, os seus filhos, os seus netos, as suas ovelhas, as suas cabras, o seu gado e tudo o que é seu.

[[v1-45-11]]

^<<v1-45-11,11>>^ A fome ainda vai durar mais cinco anos, e em Gosém eu darei mantimentos ao senhor, à sua família e aos seus animais. Assim não lhes faltará nada."

[[v1-45-12]]

^<<v1-45-12,12>>^ José continuou: — Todos vocês e Benjamim, o meu irmão, podem ver que sou eu mesmo, José, quem está falando.

[[v1-45-13]]

^<<v1-45-13,13>>^ Contem ao meu pai como sou poderoso aqui no Egito, contem tudo o que têm visto. Vão depressa e tragam o meu pai para cá.

[[v1-45-14]]

^<<v1-45-14,14>>^ José abraçou o seu irmão Benjamim e começou a chorar. E, abraçado com José, Benjamim também chorou.

[[v1-45-15]]

^<<v1-45-15,15>>^ Então, ainda chorando, José abraçou e beijou cada um dos seus irmãos. Depois disso os irmãos começaram a falar com ele.

[[v1-45-16]]

^<<v1-45-16,16>>^ A notícia de que os irmãos de José tinham vindo chegou até o palácio do rei do Egito, e ele e os seus servidores ficaram contentes com isso.

[[v1-45-17]]

^<<v1-45-17,17>>^ O rei disse a José: — Diga aos seus irmãos que carreguem os animais e voltem para a terra de Canaã.

[[v1-45-18]]

^<<v1-45-18,18>>^ E me tragam o pai deles e as famílias deles. Eu lhes darei as melhores terras que há no Egito, e eles comerão o que este país produz de melhor.

[[v1-45-19]]

^<<v1-45-19,19>>^ Que os seus irmãos levem daqui do Egito carretas para trazerem as mulheres, as crianças pequenas e também o pai deles.

[[v1-45-20]]

^<<v1-45-20,20>>^ E não se preocupem por deixarem para trás as coisas que têm, pois o melhor que há na terra do Egito será deles.

[[v1-45-21]]

^<<v1-45-21,21>>^ Os filhos de Jacó fizeram isso. José lhes deu carretas, como o rei havia mandado, e mantimento para a viagem.

[[v1-45-22]]

^<<v1-45-22,22>>^ Também lhes deu roupas novas, mas a Benjamim deu trezentas barras de prata e cinco mudas de roupas.

[[v1-45-23]]

^<<v1-45-23,23>>^ Para o pai, José mandou dez jumentos carregados das melhores coisas do Egito e dez jumentos carregados de trigo, pão e outros mantimentos para a viagem.

[[v1-45-24]]

^<<v1-45-24,24>>^ Os irmãos se despediram, e na hora de partir José aconselhou: — Não briguem pelo caminho.

[[v1-45-25]]

^<<v1-45-25,25>>^ Eles saíram do Egito e, quando chegaram a Canaã, foram à casa de Jacó, o seu pai.

[[v1-45-26]]

^<<v1-45-26,26>>^ Então lhe disseram: — José está vivo! Ele é o governador de todo o Egito! Jacó quase desmaiou e não podia acreditar.

[[v1-45-27]]

^<<v1-45-27,27>>^ Porém, quando lhe contaram tudo o que José tinha dito, e quando viu as carretas que havia mandado para levá-lo para o Egito, Jacó ficou muito animado.

[[v1-45-28]]

^<<v1-45-28,28>>^ E disse: — Já chega! O meu filho José ainda está vivo. Quero vê-lo antes de eu morrer.

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]