include::./index.adoc[]

[[v1-31-0]]
=== Gênesis, 31
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-31-1]]

^<<v1-31-1,1>>^ Jacó ficou sabendo que os filhos de Labão andavam dizendo o seguinte: — Jacó está tirando tudo o que é do nosso pai. É às custas do nosso pai que ele está ficando rico.

[[v1-31-2]]

^<<v1-31-2,2>>^ Jacó também notou que Labão já não se mostrava tão amigo como antes.

[[v1-31-3]]

^<<v1-31-3,3>>^ Então o Senhor  Deus disse a Jacó: — Volte para a terra dos seus pais, onde estão os seus parentes. Eu estarei com você.

[[v1-31-4]]

^<<v1-31-4,4>>^ Aí Jacó mandou chamar Raquel e Leia para que viessem ao campo, onde ele estava com as suas ovelhas e cabras.

[[v1-31-5]]

^<<v1-31-5,5>>^ Quando chegaram, ele disse: — Tenho reparado que o pai de vocês já não se mostra tão meu amigo como antes; mas o Deus do meu pai tem estado comigo.

[[v1-31-6]]

^<<v1-31-6,6>>^ Vocês sabem muito bem que tenho me esforçado muito, trabalhando para o pai de vocês.

[[v1-31-7]]

^<<v1-31-7,7>>^ Mas ele me tem enganado e já mudou o meu salário umas dez vezes. Porém Deus não deixou que ele me prejudicasse.

[[v1-31-8]]

^<<v1-31-8,8>>^ Quando ele dizia: "Os cabritos com manchas serão o seu salário", aí as fêmeas tinham crias manchadas. E, quando ele dizia: "Os cabritos listados serão o seu salário", aí as crias saíam todas listadas.

[[v1-31-9]]

^<<v1-31-9,9>>^ Foi assim que Deus tirou os rebanhos do pai de vocês e os deu a mim.

[[v1-31-10]]

^<<v1-31-10,10>>^ — Um dia, quando os animais estavam no tempo do cruzamento, eu tive um sonho. Eu vi que os bodes que cobriam as fêmeas eram listados, malhados e manchados.

[[v1-31-11]]

^<<v1-31-11,11>>^ O Anjo de Deus me chamou pelo nome, e eu respondi: "Aqui estou."

[[v1-31-12]]

^<<v1-31-12,12>>^ Então ele continuou: "Veja! Todos os bodes que estão cruzando são listados, malhados e manchados. Eu estou fazendo com que isso aconteça porque tenho visto o que Labão está fazendo com você.

[[v1-31-13]]

^<<v1-31-13,13>>^ Eu sou o Deus que apareceu a você em Betel, onde você me dedicou uma pedra, derramando azeite sobre ela, e onde você me fez uma promessa. Agora prepare-se, saia desta terra e volte para a terra onde você nasceu."

[[v1-31-14]]

^<<v1-31-14,14>>^ Então Raquel e Leia responderam: — Não sobrou nada para herdarmos do nosso pai.

[[v1-31-15]]

^<<v1-31-15,15>>^ Ele nos trata como se fôssemos estrangeiras. Ele até nos vendeu e depois gastou todo o dinheiro que recebeu como pagamento.

[[v1-31-16]]

^<<v1-31-16,16>>^ Toda a riqueza que Deus tirou do nosso pai é nossa e dos nossos filhos. Portanto, faça tudo o que Deus mandou.

[[v1-31-17]]

^<<v1-31-17,17>>^ Jacó se preparou para voltar a Canaã, onde morava Isaque, o seu pai. Fez com que os seus filhos e as suas mulheres montassem os camelos, ajuntou tudo o que tinha e partiu, levando todos os animais que havia conseguido com o seu trabalho na Mesopotâmia.

[[v1-31-18]]

^<<v1-31-18,18>>^ Jacó se preparou para voltar a Canaã, onde morava Isaque, o seu pai. Fez com que os seus filhos e as suas mulheres montassem os camelos, ajuntou tudo o que tinha e partiu, levando todos os animais que havia conseguido com o seu trabalho na Mesopotâmia.

[[v1-31-19]]

^<<v1-31-19,19>>^ Labão, o pai de Raquel, havia ido para outro lugar a fim de cortar a lã das suas ovelhas; e, enquanto ele estava fora, Raquel roubou as imagens dos deuses da casa dele.

[[v1-31-20]]

^<<v1-31-20,20>>^ Foi assim que Jacó, sem avisar que ia embora, enganou Labão, o arameu,

[[v1-31-21]]

^<<v1-31-21,21>>^ fugindo com tudo o que tinha. Atravessou o rio Eufrates e foi na direção da região montanhosa de Gileade.

[[v1-31-22]]

^<<v1-31-22,22>>^ Três dias depois Labão ficou sabendo que Jacó havia fugido.

[[v1-31-23]]

^<<v1-31-23,23>>^ Ele reuniu os seus parentes e foi atrás de Jacó. Sete dias depois, Labão alcançou Jacó na região montanhosa de Gileade.

[[v1-31-24]]

^<<v1-31-24,24>>^ Naquela noite Deus apareceu num sonho a Labão, o arameu, e disse: — Cuidado! Não faça nada a Jacó.

[[v1-31-25]]

^<<v1-31-25,25>>^ Labão alcançou Jacó na região montanhosa de Gileade, onde ele estava acampado. E Labão e os seus parentes acamparam no mesmo lugar.

[[v1-31-26]]

^<<v1-31-26,26>>^ Aí Labão disse a Jacó: — Por que foi que você me enganou, levando as minhas filhas como se fossem prisioneiras de guerra?

[[v1-31-27]]

^<<v1-31-27,27>>^ Por que você me enganou, fugindo desse jeito, sem me dizer nada? Se você tivesse falado comigo, eu teria preparado uma festa alegre de despedida, com canções acompanhadas de pandeiros e de liras .

[[v1-31-28]]

^<<v1-31-28,28>>^ Você nem me deixou beijar os meus netos e as minhas filhas. O que você fez foi coisa de gente sem juízo.

[[v1-31-29]]

^<<v1-31-29,29>>^ Eu poderia ter feito muito mal a vocês, mas na noite passada o Deus do seu pai me disse assim: "Cuidado! Não faça nada a Jacó."

[[v1-31-30]]

^<<v1-31-30,30>>^ Eu sei que você foi embora porque tinha saudades de casa. Mas por que foi que você roubou as imagens dos deuses da minha casa?

[[v1-31-31]]

^<<v1-31-31,31>>^ Jacó respondeu: — Eu fiquei com medo, pois pensei que o senhor ia me tirar as suas filhas à força.

[[v1-31-32]]

^<<v1-31-32,32>>^ Mas, se o senhor achar as suas imagens com alguém aqui, essa pessoa será morta. Os nossos parentes são testemunhas: se o senhor encontrar aqui qualquer coisa que seja sua, pode levar. Acontece que Jacó não sabia que Raquel havia roubado as imagens.

[[v1-31-33]]

^<<v1-31-33,33>>^ Labão entrou na barraca de Jacó, depois na de Leia e depois na das duas escravas, porém não encontrou as suas imagens. Então foi para a barraca de Raquel.

[[v1-31-34]]

^<<v1-31-34,34>>^ Aí ele procurou em toda parte, porém não achou nada, pois Raquel havia posto as imagens numa sela de camelo e estava sentada em cima.

[[v1-31-35]]

^<<v1-31-35,35>>^ Ela disse ao pai: — O senhor não fique zangado comigo por eu não me levantar, mas é que estou menstruada. Foi assim que Labão procurou as suas imagens, sem as encontrar.

[[v1-31-36]]

^<<v1-31-36,36>>^ Aí Jacó ficou zangado. Ele disse a Labão: — O que foi que eu fiz de errado? Qual foi a lei  que eu quebrei para o senhor me perseguir com tanta raiva?

[[v1-31-37]]

^<<v1-31-37,37>>^ Agora que mexeu em todas as minhas coisas, será que encontrou alguns objetos que são seus? Pois ponha esses objetos aqui, na frente dos meus parentes e dos seus, para que eles julguem qual de nós dois está com a razão.

[[v1-31-38]]

^<<v1-31-38,38>>^ Durante os vinte anos que trabalhei para o senhor, as suas ovelhas e as suas cabras nunca tiveram abortos, e eu não comi um só carneiro do seu rebanho.

[[v1-31-39]]

^<<v1-31-39,39>>^ Nunca lhe trouxe os animais que as feras mataram, mas eu mesmo pagava o prejuízo. O senhor me cobrava qualquer animal que fosse roubado de dia ou de noite.

[[v1-31-40]]

^<<v1-31-40,40>>^ A minha vida era assim: de dia o calor me castigava, e de noite eu morria de frio. E quantas noites eu passei sem dormir!

[[v1-31-41]]

^<<v1-31-41,41>>^ Fiquei vinte anos na sua casa. Trabalhei catorze anos para conseguir as suas duas filhas e seis anos para conseguir os seus animais. E, ainda por cima, o senhor mudou o meu salário umas dez vezes.

[[v1-31-42]]

^<<v1-31-42,42>>^ Se o Deus dos meus antepassados — o Deus de Abraão, o Deus a quem Isaque temia  — não tivesse estado comigo, o senhor teria me mandado embora com as mãos vazias. Mas Deus viu o meu sofrimento e o trabalho que tive e ontem à noite ele resolveu a questão.

[[v1-31-43]]

^<<v1-31-43,43>>^ Labão respondeu a Jacó assim: — Estas filhas são minhas, os netos são meus, estes animais são meus, e tudo o que você está vendo é meu. Agora, como não posso fazer nada para ficar com as minhas filhas e com os filhos que elas tiveram,

[[v1-31-44]]

^<<v1-31-44,44>>^ estou disposto a fazer um trato com você. Vamos fazer aqui um montão de pedras para que lembremos desse trato.

[[v1-31-45]]

^<<v1-31-45,45>>^ Então Jacó pegou uma pedra e a pôs de pé como se fosse um pilar.

[[v1-31-46]]

^<<v1-31-46,46>>^ Depois disse aos seus parentes que ajuntassem e amontoassem pedras. Eles fizeram um montão de pedras e depois tomaram uma refeição ali do lado dele.

[[v1-31-47]]

^<<v1-31-47,47>>^ Labão pôs naquele lugar o nome de Jegar-Saaduta , e Jacó o chamou de Galeede .

[[v1-31-48]]

^<<v1-31-48,48>>^ Depois Labão disse: — Este montão de pedras servirá para que nós dois lembremos desse trato. Foi por isso que aquele lugar recebeu o nome de Galeede.

[[v1-31-49]]

^<<v1-31-49,49>>^ E também teve o nome de Mispa porque Labão disse: — Que o Senhor  Deus fique nos vigiando quando estivermos separados um do outro!

[[v1-31-50]]

^<<v1-31-50,50>>^ Se você maltratar as minhas filhas ou se você casar com outras mulheres, mesmo que eu não saiba o que está acontecendo, lembre que Deus está nos vigiando.

[[v1-31-51]]

^<<v1-31-51,51>>^ Aqui estão as pedras e o pilar que coloquei entre nós dois.

[[v1-31-52]]

^<<v1-31-52,52>>^ O montão de pedras e o pilar são para lembrarmos desse trato. Eu nunca passarei para lá deste pilar para atacá-lo, e você não passará para cá deste montão de pedras e deste pilar para me atacar.

[[v1-31-53]]

^<<v1-31-53,53>>^ O Deus de Abraão e o Deus de Naor será juiz entre nós. Então Jacó fez um juramento em nome do Deus a quem Isaque, o seu pai, temia .

[[v1-31-54]]

^<<v1-31-54,54>>^ Ele ofereceu um animal em sacrifício  ali na montanha e convidou os seus parentes para uma refeição. Naquela noite eles comeram e dormiram ali na montanha.

'''

xref:001-genesis/001-genesis-030.adoc#v1-30-0[&#60; Capítulo Anterior] | <<v1-31-0,Topo>> | xref:001-genesis/001-genesis-032.adoc#v1-32-0[Próximo Capítulo &#62;]