include::./index.adoc[]

[[v1-25-0]]
=== Gênesis, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-25-1]]

^<<v1-25-1,1>>^ Abraão casou com outra mulher, que se chamava Quetura,

[[v1-25-2]]

^<<v1-25-2,2>>^ e ela lhe deu os seguintes filhos: Zinrã, Jocsã, Medã, Midiã, Isbaque e Sua.

[[v1-25-3]]

^<<v1-25-3,3>>^ Jocsã foi o pai de Seba e de Dedã. Os descendentes de Dedã foram os assureus, os letuseus e os leumeus.

[[v1-25-4]]

^<<v1-25-4,4>>^ Os filhos de Midiã foram Efa, Éfer, Enoque, Abida e Elda. Todos esses foram descendentes de Quetura.

[[v1-25-5]]

^<<v1-25-5,5>>^ Abraão deixou tudo o que tinha para Isaque,

[[v1-25-6]]

^<<v1-25-6,6>>^ mas deu presentes para os filhos das suas concubinas . E, antes de morrer, separou-os de Isaque e mandou que fossem morar na terra do Oriente.

[[v1-25-7]]

^<<v1-25-7,7>>^ Abraão viveu cento e setenta e cinco anos.

[[v1-25-8]]

^<<v1-25-8,8>>^ Ele morreu bem velho e foi reunir-se com os seus antepassados no mundo dos mortos .

[[v1-25-9]]

^<<v1-25-9,9>>^ Os seus filhos Isaque e Ismael o sepultaram na caverna de Macpela, que fica a leste de Manre, no campo de Efrom, que era filho de Zoar, o heteu.

[[v1-25-10]]

^<<v1-25-10,10>>^ Este era o campo que Abraão havia comprado dos heteus; Abraão e Sara foram sepultados ali.

[[v1-25-11]]

^<<v1-25-11,11>>^ Depois da morte de Abraão, Deus abençoou Isaque, o filho dele, que morava perto do "Poço Daquele que Vive e Me Vê".

[[v1-25-12]]

^<<v1-25-12,12>>^ Ismael, o filho de Abraão e de Agar, a escrava egípcia de Sara, foi pai dos seguintes filhos,

[[v1-25-13]]

^<<v1-25-13,13>>^ por ordem de nascimento: Nebaiote, o filho mais velho, e em seguida Quedar, Abdeel, Mibsão,

[[v1-25-14]]

^<<v1-25-14,14>>^ Misma, Dumá, Massá,

[[v1-25-15]]

^<<v1-25-15,15>>^ Hadade, Tema, Jetur, Nafis e Quedemá.

[[v1-25-16]]

^<<v1-25-16,16>>^ São esses os doze filhos de Ismael; as suas terras e os seus acampamentos receberam os nomes deles. Cada um era chefe da sua própria tribo.

[[v1-25-17]]

^<<v1-25-17,17>>^ Ismael tinha cento e trinta e sete anos quando morreu, indo reunir-se assim com os seus antepassados no mundo dos mortos .

[[v1-25-18]]

^<<v1-25-18,18>>^ Os descendentes de Ismael viveram na região que fica entre Havilá e Sur, a leste do Egito, ao longo da estrada que vai para a Assíria. Eles viviam separados dos outros descendentes de Abraão.

[[v1-25-19]]

^<<v1-25-19,19>>^ Esta é a história de Isaque, filho de Abraão.

[[v1-25-20]]

^<<v1-25-20,20>>^ Isaque tinha quarenta anos quando casou com Rebeca, filha de Betuel e irmã de Labão. Eles eram arameus e moravam na Mesopotâmia.

[[v1-25-21]]

^<<v1-25-21,21>>^ Rebeca não podia ter filhos, e por isso Isaque orou a Deus, o Senhor , em favor dela. O Senhor  ouviu a oração dele, e Rebeca ficou grávida.

[[v1-25-22]]

^<<v1-25-22,22>>^ Na barriga dela havia gêmeos, e eles lutavam um com o outro. Ela pensou assim: "Por que está me acontecendo uma coisa dessas?" Então foi perguntar a Deus, o Senhor ,

[[v1-25-23]]

^<<v1-25-23,23>>^ e ele respondeu: "No seu ventre há duas nações; você dará à luz dois povos inimigos. Um será mais forte do que o outro, e o mais velho será dominado pelo mais moço."

[[v1-25-24]]

^<<v1-25-24,24>>^ Chegou o tempo de Rebeca dar à luz, e ela teve dois meninos.

[[v1-25-25]]

^<<v1-25-25,25>>^ O que nasceu primeiro era vermelho e peludo como um casaco de pele; por isso lhe deram o nome de Esaú .

[[v1-25-26]]

^<<v1-25-26,26>>^ O segundo nasceu agarrando o calcanhar de Esaú com uma das mãos, e por isso lhe deram o nome de Jacó . Isaque tinha sessenta anos quando Rebeca teve os gêmeos.

[[v1-25-27]]

^<<v1-25-27,27>>^ Os meninos cresceram. Esaú gostava de viver no campo e se tornou um bom caçador. Jacó, pelo contrário, era um homem sossegado, que gostava de ficar em casa.

[[v1-25-28]]

^<<v1-25-28,28>>^ Isaque amava mais Esaú porque gostava de comer da carne dos animais que ele caçava. Rebeca, por sua vez, preferia Jacó.

[[v1-25-29]]

^<<v1-25-29,29>>^ Um dia, quando Jacó estava cozinhando um ensopado, Esaú chegou do campo, muito cansado,

[[v1-25-30]]

^<<v1-25-30,30>>^ e foi dizendo: — Estou morrendo de fome. Por favor, me deixe comer dessa coisa vermelha aí (Por isso puseram em Esaú o nome de Edom .).

[[v1-25-31]]

^<<v1-25-31,31>>^ Jacó respondeu: — Sim, eu deixo; mas só se você passar para mim os seus direitos de filho mais velho .

[[v1-25-32]]

^<<v1-25-32,32>>^ Esaú disse: — Está bem. Eu estou quase morrendo; que valor têm para mim esses direitos de filho mais velho?

[[v1-25-33]]

^<<v1-25-33,33>>^ — Então jure primeiro — disse Jacó. Esaú fez um juramento e assim passou a Jacó os seus direitos de filho mais velho.

[[v1-25-34]]

^<<v1-25-34,34>>^ Aí Jacó lhe deu pão e o ensopado. Quando Esaú acabou de comer e de beber, levantou-se e foi embora. Foi assim que ele desprezou os seus direitos de filho mais velho.

'''

xref:001-genesis/001-genesis-024.adoc#v1-24-0[&#60; Capítulo Anterior] | <<v1-25-0,Topo>> | xref:001-genesis/001-genesis-026.adoc#v1-26-0[Próximo Capítulo &#62;]