include::./index.adoc[]

[[v1-29-0]]
=== Gênesis, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-29-1]]

^<<v1-29-1,1>>^ Jacó continuou a sua viagem e chegou à terra do Oriente.

[[v1-29-2]]

^<<v1-29-2,2>>^ De repente, ele olhou e viu no campo um poço; em volta dele estavam três pastores, cada um com as suas ovelhas e cabras. A água para os animais era tirada desse poço, que era tapado com uma grande pedra.

[[v1-29-3]]

^<<v1-29-3,3>>^ Quando todos os pastores se ajuntavam ali com os seus animais, então tiravam a pedra para dar água às ovelhas e cabras. Depois tornavam a pôr a pedra na boca do poço.

[[v1-29-4]]

^<<v1-29-4,4>>^ Jacó perguntou aos pastores: — De onde são vocês, meus amigos? — Somos de Harã — responderam eles.

[[v1-29-5]]

^<<v1-29-5,5>>^ Em seguida perguntou: — Vocês conhecem Labão, filho de Naor? — Conhecemos, sim — disseram.

[[v1-29-6]]

^<<v1-29-6,6>>^ — Ele vai bem? — perguntou Jacó. Eles responderam: — Sim, vai bem. Olhe! Raquel, a filha dele, vem vindo aí com as ovelhas.

[[v1-29-7]]

^<<v1-29-7,7>>^ Então Jacó disse: — Ainda é dia, e é muito cedo para recolher as ovelhas. Por que vocês não lhes dão água e as levam de volta para pastar?

[[v1-29-8]]

^<<v1-29-8,8>>^ Eles responderam: — Não podemos. Temos de esperar que todas as ovelhas e cabras estejam aqui e a pedra seja tirada da boca do poço. Aí daremos água para elas.

[[v1-29-9]]

^<<v1-29-9,9>>^ Jacó ainda estava falando com eles quando Raquel, que era pastora de ovelhas, chegou com os animais do seu pai.

[[v1-29-10]]

^<<v1-29-10,10>>^ Logo que Jacó a viu com as ovelhas e cabras do seu tio Labão, ele foi, e tirou a pedra da boca do poço, e deu água para os animais.

[[v1-29-11]]

^<<v1-29-11,11>>^ Depois ele beijou Raquel e, muito emocionado, começou a chorar.

[[v1-29-12]]

^<<v1-29-12,12>>^ E disse: — Eu sou parente do seu pai; sou filho de Rebeca. Raquel foi correndo contar tudo ao pai.

[[v1-29-13]]

^<<v1-29-13,13>>^ Ele ouviu as novidades a respeito do seu sobrinho e logo saiu correndo. Quando encontrou Jacó, Labão o abraçou, e beijou, e o levou para casa. Jacó lhe contou tudo o que havia acontecido,

[[v1-29-14]]

^<<v1-29-14,14>>^ e aí Labão disse: — Sim, de fato, você é da minha própria carne e sangue. Jacó ficou na casa do seu tio um mês inteiro.

[[v1-29-15]]

^<<v1-29-15,15>>^ Aí Labão disse: — Não está certo você trabalhar de graça para mim só porque é meu parente. Quanto você quer ganhar?

[[v1-29-16]]

^<<v1-29-16,16>>^ Acontece que Labão tinha duas filhas. A mais velha se chamava Leia, e a mais moça, Raquel.

[[v1-29-17]]

^<<v1-29-17,17>>^ Leia tinha olhos meigos, mas Raquel era bonita de rosto e de corpo.

[[v1-29-18]]

^<<v1-29-18,18>>^ Como Jacó estava apaixonado por Raquel, respondeu: — Trabalharei sete anos para o senhor a fim de poder casar com Raquel.

[[v1-29-19]]

^<<v1-29-19,19>>^ Labão disse: — Eu prefiro dá-la a você em vez de a um estranho. Fique aqui comigo.

[[v1-29-20]]

^<<v1-29-20,20>>^ Assim, Jacó trabalhou sete anos para poder ter Raquel. Mas, porque ele a amava, esses anos pareceram poucos dias.

[[v1-29-21]]

^<<v1-29-21,21>>^ Quando passaram os sete anos, Jacó disse a Labão: — Dê-me a minha mulher. O tempo combinado já passou, e eu quero casar com ela.

[[v1-29-22]]

^<<v1-29-22,22>>^ Labão deu uma festa de casamento e convidou toda a gente do lugar.

[[v1-29-23]]

^<<v1-29-23,23>>^ Mas naquela noite Labão pegou Leia e a entregou a Jacó, e ele teve relações com ela

[[v1-29-24]]

^<<v1-29-24,24>>^ (Labão tinha dado a sua escrava Zilpa a Leia para ser escrava dela.).

[[v1-29-25]]

^<<v1-29-25,25>>^ Só na manhã seguinte Jacó descobriu que havia dormido com Leia. Por isso foi reclamar com Labão. Ele disse: — Por que o senhor me fez uma coisa dessas? Eu trabalhei para ficar com Raquel. Por que foi que o senhor me enganou?

[[v1-29-26]]

^<<v1-29-26,26>>^ Labão respondeu: — Aqui na nossa terra não é costume a filha mais moça casar antes da mais velha.

[[v1-29-27]]

^<<v1-29-27,27>>^ Espere até que termine a semana de festas do casamento. Aí, se você prometer que vai trabalhar para mim outros sete anos, eu lhe darei Raquel.

[[v1-29-28]]

^<<v1-29-28,28>>^ Jacó concordou, e, quando terminou a semana de festas do casamento de Leia, Labão lhe deu a sua filha Raquel como esposa

[[v1-29-29]]

^<<v1-29-29,29>>^ (Labão tinha dado a sua escrava Bila a Raquel para ser escrava dela.).

[[v1-29-30]]

^<<v1-29-30,30>>^ Jacó também teve relações com Raquel; e ele amava Raquel muito mais do que amava Leia. E ficou trabalhando para Labão mais sete anos.

[[v1-29-31]]

^<<v1-29-31,31>>^ Quando o Senhor  Deus viu que Jacó desprezava Leia, fez com que ela pudesse ter filhos, mas Raquel não podia ter filhos.

[[v1-29-32]]

^<<v1-29-32,32>>^ Leia ficou grávida e deu à luz um filho; e pôs nele o nome de Rúben . Ela explicou assim: — O Senhor  viu que eu estava triste, mas agora o meu marido vai me amar.

[[v1-29-33]]

^<<v1-29-33,33>>^ Leia ficou grávida outra vez e teve outro filho, a quem deu o nome de Simeão . E disse: — O Senhor  ouviu que eu era desprezada e por isso me deu mais este filho.

[[v1-29-34]]

^<<v1-29-34,34>>^ Leia engravidou ainda outra vez e teve mais um filho, a quem chamou de Levi , pois disse assim: — Agora o meu marido ficará mais unido comigo, pois já lhe dei três filhos.

[[v1-29-35]]

^<<v1-29-35,35>>^ Leia ficou grávida mais uma vez e teve outro filho. A esse deu o nome de Judá e disse: — Desta vez louvarei a Deus, o Senhor . Depois disso não teve mais filhos.

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]