include::./index.adoc[]

[[v1-14-0]]
=== Gênesis, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-14-1]]

^<<v1-14-1,1>>^ Nesse tempo Anrafel era rei de Sinar, Arioque era rei de Elasar, Quedorlaomer era rei de Elão, e Tidal era rei de Goim.

[[v1-14-2]]

^<<v1-14-2,2>>^ Esses quatro fizeram guerra contra os seguintes reis: Bera, de Sodoma; Birsa, de Gomorra; Sinabe, de Admá; Semeber, de Zeboim; e contra o rei de Bela, cidade que também se chamava Zoar.

[[v1-14-3]]

^<<v1-14-3,3>>^ Esses cinco reis juntaram os seus exércitos no vale de Sidim, onde fica o mar Morto.

[[v1-14-4]]

^<<v1-14-4,4>>^ O rei Quedorlaomer os havia dominado por doze anos, mas no décimo terceiro ano eles se revoltaram contra ele.

[[v1-14-5]]

^<<v1-14-5,5>>^ No décimo quarto ano Quedorlaomer e os seus aliados derrotaram os refains  em Asterote-Carnaim, os zuzins em Hã, os emins em Savé-Quiriataim

[[v1-14-6]]

^<<v1-14-6,6>>^ e os horeus nas montanhas de Seir, perseguindo-os até El-Parã, onde começa o deserto.

[[v1-14-7]]

^<<v1-14-7,7>>^ Depois voltaram até Cades, que naquele tempo se chamava En-Mispate. Eles arrasaram a terra dos amalequitas e derrotaram os amorreus que viviam em Hazazão-Tamar.

[[v1-14-8]]

^<<v1-14-8,8>>^ Então os reis de Sodoma, de Gomorra, de Admá, de Zeboim e de Bela saíram com os seus exércitos para o vale de Sidim a fim de lutar

[[v1-14-9]]

^<<v1-14-9,9>>^ contra os reis de Elão, de Goim, de Sinar e de Elasar. Eram quatro reis contra cinco.

[[v1-14-10]]

^<<v1-14-10,10>>^ Acontece que o vale de Sidim era cheio de buracos em que havia piche; e, quando tentaram fugir da batalha, os reis de Sodoma e de Gomorra caíram nesses buracos. Mas os outros reis fugiram para as montanhas.

[[v1-14-11]]

^<<v1-14-11,11>>^ Os quatro reis pegaram todo o mantimento e os objetos de valor que havia em Sodoma e em Gomorra e foram embora.

[[v1-14-12]]

^<<v1-14-12,12>>^ Ló, o sobrinho de Abrão, vivia em Sodoma e por isso também foi levado como prisioneiro. E levaram também tudo o que era dele.

[[v1-14-13]]

^<<v1-14-13,13>>^ Mas um homem escapou e foi contar tudo a Abrão, o hebreu, que morava perto das árvores sagradas que pertenciam a Manre, o amorreu. Manre e os seus irmãos Escol e Aner eram aliados de Abrão.

[[v1-14-14]]

^<<v1-14-14,14>>^ Quando Abrão ficou sabendo que o seu sobrinho tinha sido levado como prisioneiro, reuniu os seus homens treinados para a guerra, todos eles nascidos na sua casa. Eram trezentos e dezoito ao todo. Abrão foi com eles, perseguindo os quatro reis até a cidade de Dã.

[[v1-14-15]]

^<<v1-14-15,15>>^ Ali Abrão dividiu os seus homens em dois grupos, atacou os inimigos de noite e os derrotou. Ele continuou a persegui-los até Hoba, que fica ao norte da cidade de Damasco,

[[v1-14-16]]

^<<v1-14-16,16>>^ e trouxe de volta tudo o que os inimigos haviam levado. Abrão trouxe também o seu sobrinho Ló, e tudo o que era dele, e também as suas mulheres, e o resto da sua gente.

[[v1-14-17]]

^<<v1-14-17,17>>^ Depois de haver derrotado Quedorlaomer e os outros reis, Abrão estava voltando para casa quando o rei de Sodoma foi encontrar-se com ele no vale de Savé, também chamado de vale do Rei.

[[v1-14-18]]

^<<v1-14-18,18>>^ E Melquisedeque, que era rei de Salém e sacerdote do Deus Altíssimo, trouxe pão e vinho.

[[v1-14-19]]

^<<v1-14-19,19>>^ Melquisedeque abençoou Abrão, dizendo: "Abrão seja abençoado pelo Deus Altíssimo, que criou o céu e a terra!

[[v1-14-20]]

^<<v1-14-20,20>>^ Seja louvado o Deus Altíssimo, que entregou os inimigos de você nas suas mãos!" Aí Abrão deu a Melquisedeque a décima parte de tudo o que havia trazido de volta.

[[v1-14-21]]

^<<v1-14-21,21>>^ Depois o rei de Sodoma disse a Abrão: — Fique com as coisas e me devolva somente as pessoas.

[[v1-14-22]]

^<<v1-14-22,22>>^ Mas Abrão respondeu: — Eu levanto a mão diante do Senhor , o Deus Altíssimo, criador do céu e da terra,

[[v1-14-23]]

^<<v1-14-23,23>>^ e juro que não ficarei com nada do que é seu, nem um fio de linha ou uma tira de sandália. Assim você nunca poderá dizer: "Eu fiz com que Abrão ficasse rico."

[[v1-14-24]]

^<<v1-14-24,24>>^ Não quero nada para mim, a não ser a comida que os meus empregados comeram. Mas os meus aliados Aner, Escol e Manre podem ficar com a parte deles.

'''

xref:001-genesis/001-genesis-013.adoc#v1-13-0[&#60; Capítulo Anterior] | <<v1-14-0,Topo>> | xref:001-genesis/001-genesis-015.adoc#v1-15-0[Próximo Capítulo &#62;]