include::./index.adoc[]

[[v1-36-0]]
=== Gênesis, 36
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v1-36-1]]

^<<v1-36-1,1>>^ São estes os descendentes de Esaú, também chamado de Edom.

[[v1-36-2]]

^<<v1-36-2,2>>^ Esaú casou com duas mulheres do país de Canaã, isto é, com Ada, filha de Elom, o heteu; e com Oolibama, filha de Aná e neta de Zibeão, o heveu.

[[v1-36-3]]

^<<v1-36-3,3>>^ Esaú casou também com Basemate, filha de Ismael e irmã de Nebaiote.

[[v1-36-4]]

^<<v1-36-4,4>>^ Ada foi mãe de Elifaz, Basemate foi mãe de Reuel,

[[v1-36-5]]

^<<v1-36-5,5>>^ e Oolibama foi mãe de Jeús, Jalã e Corá. Esses foram os filhos de Esaú que nasceram quando ele estava morando na terra de Canaã.

[[v1-36-6]]

^<<v1-36-6,6>>^ Depois Esaú foi para outro lugar com as suas mulheres, os seus filhos, as suas filhas e toda a gente da sua casa, separando-se assim do seu irmão Jacó. Esaú levou consigo todas as suas ovelhas e cabras, todo o seu gado e tudo o que havia conseguido no país de Canaã.

[[v1-36-7]]

^<<v1-36-7,7>>^ Esaú saiu dali porque a terra em que ele e Jacó estavam morando era pequena demais para os dois; eles tinham muito gado e por isso não podiam ficar juntos.

[[v1-36-8]]

^<<v1-36-8,8>>^ Portanto, Esaú, também chamado de Edom, foi morar na região montanhosa de Seir.

[[v1-36-9]]

^<<v1-36-9,9>>^ Segue a lista dos descendentes de Esaú, o antepassado dos edomitas, que vivem na região montanhosa de Edom, também chamada de Seir.

[[v1-36-10]]

^<<v1-36-10,10>>^ Ada, mulher de Esaú, teve um filho chamado Elifaz; os filhos de Elifaz foram cinco: Temã, Omar, Zefo, Gaetã e Quenaz. Com a sua concubina  Timna, Elifaz teve Amaleque. Basemate, outra mulher de Esaú, teve um filho chamado Reuel; e Reuel foi pai de quatro filhos: Naate, Zera, Sama e Miza.

[[v1-36-11]]

^<<v1-36-11,11>>^ Ada, mulher de Esaú, teve um filho chamado Elifaz; os filhos de Elifaz foram cinco: Temã, Omar, Zefo, Gaetã e Quenaz. Com a sua concubina  Timna, Elifaz teve Amaleque.

[[v1-36-12]]

^<<v1-36-12,12>>^ Ada, mulher de Esaú, teve um filho chamado Elifaz; os filhos de Elifaz foram cinco: Temã, Omar, Zefo, Gaetã e Quenaz. Com a sua concubina  Timna, Elifaz teve Amaleque.

[[v1-36-13]]

^<<v1-36-13,13>>^ Ada, mulher de Esaú, teve um filho chamado Elifaz; os filhos de Elifaz foram cinco: Temã, Omar, Zefo, Gaetã e Quenaz. Com a sua concubina  Timna, Elifaz teve Amaleque.

[[v1-36-14]]

^<<v1-36-14,14>>^ Esaú tinha outra mulher chamada Oolibama, filha de Aná e neta de Zibeão. Os filhos dela foram Jeús, Jalã e Corá.

[[v1-36-15]]

^<<v1-36-15,15>>^ Segue a lista das tribos que descendem de Esaú. De Elifaz, o filho mais velho de Esaú, descendem as seguintes tribos: Temã, Omar, Zefo, Quenaz,

[[v1-36-16]]

^<<v1-36-16,16>>^ Corá, Gaetã e Amaleque. Estes foram descendentes de Ada, mulher de Esaú.

[[v1-36-17]]

^<<v1-36-17,17>>^ De Reuel descendem as seguintes tribos: Naate, Zera, Sama e Miza. Estes foram descendentes de Basemate, outra mulher de Esaú.

[[v1-36-18]]

^<<v1-36-18,18>>^ De Esaú com sua outra mulher chamada Oolibama, filha de Aná, descendem as seguintes tribos: Jeús, Jalã e Corá.

[[v1-36-19]]

^<<v1-36-19,19>>^ Todas essas tribos são descendentes de Esaú.

[[v1-36-20]]

^<<v1-36-20,20>>^ As primeiras tribos que moraram na terra de Edom eram descendentes de Lotã, Sobal, Zibeão, Aná, Disom, Eser e Disã, todos eles filhos de Seir, o horeu.

[[v1-36-21]]

^<<v1-36-21,21>>^ As primeiras tribos que moraram na terra de Edom eram descendentes de Lotã, Sobal, Zibeão, Aná, Disom, Eser e Disã, todos eles filhos de Seir, o horeu.

[[v1-36-22]]

^<<v1-36-22,22>>^ Lotã foi o pai dos grupos de famílias de Hori e de Homã. Lotã tinha uma irmã chamada Timna.

[[v1-36-23]]

^<<v1-36-23,23>>^ Sobal foi o antepassado dos grupos de famílias de Alvã, Manaate, Ebal, Sefô e Onã.

[[v1-36-24]]

^<<v1-36-24,24>>^ Zibeão foi pai de dois filhos: Aías e Aná. Este foi o Aná que descobriu as fontes de água quente no deserto, quando estava tomando conta dos jumentos do pai.

[[v1-36-25]]

^<<v1-36-25,25>>^ Aná foi o pai de Disom, que foi o pai dos grupos de famílias de Hendã, Esbã, Itrã e Querã. Aná também foi pai de uma filha chamada Oolibama.

[[v1-36-26]]

^<<v1-36-26,26>>^ Aná foi o pai de Disom, que foi o pai dos grupos de famílias de Hendã, Esbã, Itrã e Querã. Aná também foi pai de uma filha chamada Oolibama.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]