include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v51-4-1]]

^<<v51-4-1,1>>^ Donos de escravos, sejam justos e honestos na maneira de tratar os seus escravos. Lembrem que vocês também têm um Senhor no céu.

[[v51-4-2]]

^<<v51-4-2,2>>^ Continuem firmes na oração, sempre alertas ao orarem e dando graças a Deus.

[[v51-4-3]]

^<<v51-4-3,3>>^ Orem também por nós a fim de que Deus nos dê uma boa oportunidade para anunciar a sua mensagem, que trata do segredo de Cristo . Pois é por causa dessa mensagem que estou na cadeia.

[[v51-4-4]]

^<<v51-4-4,4>>^ Portanto, orem para que eu faça com que o segredo de Cristo seja bem-conhecido, como é o meu dever.

[[v51-4-5]]

^<<v51-4-5,5>>^ Sejam sábios na sua maneira de agir com os que não creem e aproveitem bem o tempo que passarem com eles.

[[v51-4-6]]

^<<v51-4-6,6>>^ Que as suas conversas sejam sempre agradáveis e de bom gosto, e que vocês saibam também como responder a cada pessoa!

[[v51-4-7]]

^<<v51-4-7,7>>^ Tíquico, nosso querido irmão, trabalhador fiel e companheiro no serviço do Senhor, levará a vocês todas as notícias minhas.

[[v51-4-8]]

^<<v51-4-8,8>>^ Eu o estou enviando para contar como todos nós vamos indo e assim animar vocês.

[[v51-4-9]]

^<<v51-4-9,9>>^ Com ele vai Onésimo, o querido e fiel irmão, que é da igreja de vocês. Eles vão lhes contar tudo o que está acontecendo aqui.

[[v51-4-10]]

^<<v51-4-10,10>>^ Aristarco, que está na cadeia comigo, lhes manda saudações; e também Marcos, o primo de Barnabé. Vocês já têm orientação a respeito de Marcos, para recebê-lo bem, se ele passar por aí.

[[v51-4-11]]

^<<v51-4-11,11>>^ Josué, chamado "o Justo", também manda saudações. Esses três são os únicos judeus convertidos  que trabalham comigo para o Reino de Deus  e eles têm me ajudado muito.

[[v51-4-12]]

^<<v51-4-12,12>>^ Epafras, outro que é da igreja de vocês e é servo  de Cristo Jesus, também manda saudações. Ele sempre ora com fervor por vocês. Ele pede a Deus que faça com que vocês sejam sempre firmes, espiritualmente maduros e prontos para cumprir tudo o que Deus quer.

[[v51-4-13]]

^<<v51-4-13,13>>^ Eu posso afirmar que ele tem trabalhado muito em favor de vocês e pela gente de Laodiceia e de Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Lucas, o nosso querido médico, e o irmão Demas mandam saudações.

[[v51-4-15]]

^<<v51-4-15,15>>^ Mandamos saudações aos irmãos que moram em Laodiceia. Saudações também para Ninfa e para a igreja que se reúne na casa dela.

[[v51-4-16]]

^<<v51-4-16,16>>^ Peço que, depois de lerem esta carta, vocês a mandem para Laodiceia a fim de que os irmãos de lá também a leiam. E vocês leiam a carta que vai chegar de Laodiceia .

[[v51-4-17]]

^<<v51-4-17,17>>^ E digam isto a Arquipo: procure cumprir bem a tarefa que você recebeu no serviço do Senhor.

[[v51-4-18]]

^<<v51-4-18,18>>^ Com a minha própria mão escrevo isto: Saudações de Paulo.  Não esqueçam que estou na cadeia. Que a graça  de Deus esteja com vocês!

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]