include::./index.adoc[]

[[v51-3-0]]
=== Colossenses, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v51-3-1]]

^<<v51-3-1,1>>^ Vocês foram ressuscitados com Cristo. Portanto, ponham o seu interesse nas coisas que são do céu, onde Cristo está sentado ao lado direito de Deus.

[[v51-3-2]]

^<<v51-3-2,2>>^ Pensem nas coisas lá do alto e não nas que são aqui da terra.

[[v51-3-3]]

^<<v51-3-3,3>>^ Porque vocês já morreram, e a vida de vocês está escondida com Cristo, que está unido com Deus.

[[v51-3-4]]

^<<v51-3-4,4>>^ Cristo é a verdadeira vida de vocês, e, quando ele aparecer, vocês aparecerão com ele e tomarão parte na sua glória .

[[v51-3-5]]

^<<v51-3-5,5>>^ Portanto, matem os desejos deste mundo que agem em vocês, isto é, a imoralidade sexual, a indecência, as paixões más, os maus desejos e a cobiça, porque a cobiça é um tipo de idolatria.

[[v51-3-6]]

^<<v51-3-6,6>>^ Pois é por causa dessas coisas que o castigo de Deus cairá sobre os que não lhe obedecem.

[[v51-3-7]]

^<<v51-3-7,7>>^ Antigamente a vida de vocês era dominada por esses desejos, e vocês viviam de acordo com eles.

[[v51-3-8]]

^<<v51-3-8,8>>^ Mas agora livrem-se de tudo isto: da raiva, da paixão e dos sentimentos de ódio. E que não saia da boca de vocês nenhum insulto e nenhuma conversa indecente.

[[v51-3-9]]

^<<v51-3-9,9>>^ Não mintam uns para os outros, pois vocês já deixaram de lado a natureza velha com os seus costumes

[[v51-3-10]]

^<<v51-3-10,10>>^ e se vestiram com uma nova natureza. Essa natureza é a nova pessoa que Deus, o seu criador, está sempre renovando para que ela se torne parecida com ele, a fim de fazer com que vocês o conheçam completamente.

[[v51-3-11]]

^<<v51-3-11,11>>^ Como resultado disso, já não existem mais judeus e não judeus, circuncidados  e não circuncidados, não civilizados, selvagens, escravos ou pessoas livres, mas Cristo é tudo e está em todos.

[[v51-3-12]]

^<<v51-3-12,12>>^ Vocês são o povo de Deus. Ele os amou e os escolheu para serem dele. Portanto, vistam-se de misericórdia, de bondade, de humildade, de delicadeza e de paciência.

[[v51-3-13]]

^<<v51-3-13,13>>^ Não fiquem irritados uns com os outros e perdoem uns aos outros, caso alguém tenha alguma queixa contra outra pessoa. Assim como o Senhor perdoou vocês, perdoem uns aos outros.

[[v51-3-14]]

^<<v51-3-14,14>>^ E, acima de tudo, tenham amor, pois o amor une perfeitamente todas as coisas.

[[v51-3-15]]

^<<v51-3-15,15>>^ E que a paz que Cristo dá dirija vocês nas suas decisões, pois foi para essa paz que Deus os chamou a fim de formarem um só corpo. E sejam agradecidos.

[[v51-3-16]]

^<<v51-3-16,16>>^ Que a mensagem de Cristo, com toda a sua riqueza, viva no coração de vocês! Ensinem e instruam uns aos outros com toda a sabedoria. Cantem salmos, hinos e canções espirituais; louvem a Deus, com gratidão no coração.

[[v51-3-17]]

^<<v51-3-17,17>>^ E tudo o que vocês fizerem ou disserem, façam em nome do Senhor Jesus e por meio dele agradeçam a Deus, o Pai.

[[v51-3-18]]

^<<v51-3-18,18>>^ Esposa, obedeça ao seu marido, pois é o que você deve fazer por ser cristã.

[[v51-3-19]]

^<<v51-3-19,19>>^ Marido, ame a sua esposa e não seja grosseiro com ela.

[[v51-3-20]]

^<<v51-3-20,20>>^ Filhos, o dever cristão de vocês é obedecer sempre ao seu pai e à sua mãe porque Deus gosta disso.

[[v51-3-21]]

^<<v51-3-21,21>>^ Pais, não irritem os seus filhos, para que eles não fiquem desanimados.

[[v51-3-22]]

^<<v51-3-22,22>>^ Escravos, em tudo obedeçam àqueles que são seus donos aqui na terra. Não obedeçam só quando eles estiverem vendo vocês, procurando com isso conseguir a aprovação deles. Mas obedeçam com sinceridade, por causa do temor  que vocês têm pelo Senhor.

[[v51-3-23]]

^<<v51-3-23,23>>^ O que vocês fizerem façam de todo o coração, como se estivessem servindo o Senhor e não as pessoas.

[[v51-3-24]]

^<<v51-3-24,24>>^ Lembrem que o Senhor lhes dará como recompensa aquilo que ele tem guardado para o seu povo, pois o verdadeiro Senhor que vocês servem é Cristo.

[[v51-3-25]]

^<<v51-3-25,25>>^ E quem faz o mal, seja quem for, pagará pelo mal que faz. Pois, quando Deus julga, ele não faz diferença entre pessoas.

'''

xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[Próximo Capítulo &#62;]