include::./index.adoc[]

[[v51-1-0]]
=== Colossenses, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v51-1-1]]

^<<v51-1-1,1>>^ Eu, Paulo, apóstolo  de Cristo Jesus pela vontade de Deus, escrevo junto com o irmão Timóteo esta carta

[[v51-1-2]]

^<<v51-1-2,2>>^ ao povo de Deus que mora na cidade de Colossos, os nossos fiéis irmãos em Cristo. Que a graça  e a paz de Deus, o nosso Pai, estejam com vocês!

[[v51-1-3]]

^<<v51-1-3,3>>^ Sempre que oramos por vocês, damos graças a Deus, o Pai do nosso Senhor Jesus Cristo.

[[v51-1-4]]

^<<v51-1-4,4>>^ Pois ficamos sabendo da fé que vocês têm em Cristo Jesus e também do amor que vocês têm por todo o povo de Deus.

[[v51-1-5]]

^<<v51-1-5,5>>^ Quando a verdadeira mensagem, a boa notícia do evangelho , chegou a vocês pela primeira vez, vocês ouviram falar a respeito da esperança que o evangelho oferece. Por isso, a fé e o amor que vocês têm são baseados naquilo que esperam e que está guardado para vocês no céu.

[[v51-1-6]]

^<<v51-1-6,6>>^ Essa boa notícia que vocês receberam está trazendo muitas bênçãos e vai se espalhando pelo mundo inteiro. E foi isso mesmo que aconteceu com vocês, desde o dia em que pela primeira vez ouviram falar a respeito da graça  de Deus e a conheceram de verdade.

[[v51-1-7]]

^<<v51-1-7,7>>^ Tudo isso vocês aprenderam com Epafras, nosso querido companheiro de trabalho, o qual presta serviço em favor de vocês como um fiel servidor de Cristo.

[[v51-1-8]]

^<<v51-1-8,8>>^ Foi ele quem nos contou do amor que o Espírito de Deus deu a vocês.

[[v51-1-9]]

^<<v51-1-9,9>>^ Por esse motivo, desde o dia em que ficamos sabendo de tudo isso, nunca paramos de orar em favor de vocês. Pedimos a Deus que encha vocês com o conhecimento da sua vontade e com toda a sabedoria e compreensão que o Espírito de Deus dá.

[[v51-1-10]]

^<<v51-1-10,10>>^ Desse modo, vocês poderão viver como o Senhor quer e fazer sempre o que agrada a ele. Vocês vão fazer todo tipo de boas ações e também vão conhecer a Deus cada vez mais.

[[v51-1-11]]

^<<v51-1-11,11>>^ Pedimos a Deus que vocês se tornem fortes com toda a força que vem do glorioso  poder dele, para que possam suportar tudo com paciência.

[[v51-1-12]]

^<<v51-1-12,12>>^ E agradeçam, com alegria, ao Pai, que os tornou capazes de participar daquilo que ele guardou no Reino  da luz para o seu povo.

[[v51-1-13]]

^<<v51-1-13,13>>^ Ele nos libertou do poder da escuridão e nos trouxe em segurança para o Reino do seu Filho amado.

[[v51-1-14]]

^<<v51-1-14,14>>^ É ele quem nos liberta, e é por meio dele que os nossos pecados são perdoados.

[[v51-1-15]]

^<<v51-1-15,15>>^ Ele, o primeiro Filho, é a revelação visível do Deus invisível; ele é superior a todas as coisas criadas.

[[v51-1-16]]

^<<v51-1-16,16>>^ Pois, por meio dele, Deus criou tudo, no céu e na terra, tanto o que se vê como o que não se vê, inclusive todos os poderes espirituais , as forças, os governos e as autoridades. Por meio dele e para ele, Deus criou todo o Universo .

[[v51-1-17]]

^<<v51-1-17,17>>^ Antes de tudo, ele já existia, e, por estarem unidas com ele, todas as coisas são conservadas em ordem e harmonia.

[[v51-1-18]]

^<<v51-1-18,18>>^ Ele é a cabeça do corpo, que é a Igreja, e é ele quem dá vida ao corpo. Ele é o primeiro Filho, que foi ressuscitado para que somente ele tivesse o primeiro lugar em tudo.

[[v51-1-19]]

^<<v51-1-19,19>>^ Pois é pela própria vontade de Deus que o Filho tem em si mesmo a natureza completa de Deus.

[[v51-1-20]]

^<<v51-1-20,20>>^ Portanto, por meio do Filho, Deus resolveu trazer o Universo de volta para si mesmo. Ele trouxe a paz por meio da morte do seu Filho na cruz e assim trouxe de volta para si mesmo todas as coisas, tanto na terra como no céu.

[[v51-1-21]]

^<<v51-1-21,21>>^ Antes, vocês estavam longe de Deus e eram inimigos dele por causa das coisas más que vocês faziam e pensavam.

[[v51-1-22]]

^<<v51-1-22,22>>^ Mas agora, por meio da morte do seu Filho na cruz, Deus fez com que vocês ficassem seus amigos a fim de trazê-los à sua presença para serem somente dele, não tendo mancha nem culpa.

[[v51-1-23]]

^<<v51-1-23,23>>^ Mas é preciso que vocês continuem fiéis, firmados sobre um alicerce seguro, sem se afastar da esperança que receberam quando ouviram a boa notícia do evangelho . Foi desse evangelho que eu, Paulo, me tornei servo , e é esse evangelho que tem sido anunciado no mundo inteiro.

[[v51-1-24]]

^<<v51-1-24,24>>^ Agora eu me sinto feliz pelo que tenho sofrido por vocês. Pois o que eu sofro no meu corpo pela Igreja, que é o corpo de Cristo, está ajudando a completar os sofrimentos de Cristo em favor dela.

[[v51-1-25]]

^<<v51-1-25,25>>^ E Deus me escolheu para ser servo  da Igreja e me deu uma missão que devo cumprir em favor de vocês. Essa missão é anunciar, de modo completo, a mensagem dele.

[[v51-1-26]]

^<<v51-1-26,26>>^ Essa mensagem é o segredo que ele escondeu de toda a humanidade durante os séculos passados, porém que agora ele revelou ao seu povo.

[[v51-1-27]]

^<<v51-1-27,27>>^ O plano de Deus é fazer com que o seu povo conheça esse maravilhoso e glorioso  segredo que ele tem para revelar a todos os povos. E o segredo é este: Cristo está em vocês, o que lhes dá a firme esperança de que vocês tomarão parte na glória  de Deus.

[[v51-1-28]]

^<<v51-1-28,28>>^ Assim nós anunciamos Cristo a todas as pessoas. Com toda a sabedoria possível, aconselhamos e ensinamos cada pessoa, a fim de levar todos à presença de Deus como pessoas espiritualmente adultas e unidas com Cristo.

[[v51-1-29]]

^<<v51-1-29,29>>^ É para realizar essa tarefa que eu trabalho e luto com a força de Cristo, que está agindo poderosamente em mim.

'''

xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[Próximo Capítulo &#62;]