include::./index.adoc[]

[[v51-2-0]]
=== Colossenses, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v51-2-1]]

^<<v51-2-1,1>>^ Pois quero que saibam o quanto eu tenho trabalhado por vocês, e pelos que moram em Laodiceia , e por muitos outros que não me conhecem pessoalmente.

[[v51-2-2]]

^<<v51-2-2,2>>^ Eu trabalho para que o coração deles se encha de coragem e eles sejam unidos em amor e assim fiquem completamente enriquecidos com a segurança que é dada pela verdadeira compreensão do segredo de Deus. Esse segredo é Cristo,

[[v51-2-3]]

^<<v51-2-3,3>>^ o qual é a chave que abre todos os tesouros escondidos do conhecimento e da sabedoria que vêm de Deus.

[[v51-2-4]]

^<<v51-2-4,4>>^ Eu digo isso a vocês para que não deixem que ninguém os engane com explicações falsas, mesmo que pareçam muito boas.

[[v51-2-5]]

^<<v51-2-5,5>>^ Porque, embora no corpo eu esteja longe, em espírito eu estou com vocês. E fico alegre em saber que vocês estão unidos e firmes na fé em Cristo.

[[v51-2-6]]

^<<v51-2-6,6>>^ Portanto, já que vocês aceitaram Cristo Jesus como Senhor, vivam unidos com ele.

[[v51-2-7]]

^<<v51-2-7,7>>^ Estejam enraizados nele, construam a sua vida sobre ele e se tornem mais fortes na fé, como foi ensinado a vocês. E deem sempre graças a Deus.

[[v51-2-8]]

^<<v51-2-8,8>>^ Tenham cuidado para que ninguém os torne escravos por meio de argumentos sem valor, que vêm da sabedoria humana. Essas coisas vêm dos ensinamentos de criaturas humanas e dos espíritos que dominam o Universo  e não de Cristo.

[[v51-2-9]]

^<<v51-2-9,9>>^ Pois em Cristo, como ser humano, está presente toda a natureza de Deus,

[[v51-2-10]]

^<<v51-2-10,10>>^ e, por estarem unidos com Cristo, vocês também têm essa natureza. Ele domina todos os poderes e autoridades espirituais .

[[v51-2-11]]

^<<v51-2-11,11>>^ Por estarem unidos com Cristo, vocês foram circuncidados  não com a circuncisão que é feita no corpo, mas com a circuncisão feita por Cristo, pela qual somos libertados do poder da natureza pecadora.

[[v51-2-12]]

^<<v51-2-12,12>>^ Pois, quando vocês foram batizados, foram sepultados com Cristo; e no batismo também foram ressuscitados com ele por meio da fé que vocês têm no grande poder de Deus, o mesmo Deus que ressuscitou Cristo.

[[v51-2-13]]

^<<v51-2-13,13>>^ Antigamente vocês estavam espiritualmente mortos por causa dos seus pecados e porque eram não judeus e não tinham a lei . Mas agora Deus os ressuscitou junto com Cristo. Deus perdoou todos os nossos pecados

[[v51-2-14]]

^<<v51-2-14,14>>^ e anulou a conta da nossa dívida, com os seus regulamentos que nós éramos obrigados a obedecer. Ele acabou com essa conta, pregando-a na cruz.

[[v51-2-15]]

^<<v51-2-15,15>>^ E foi na cruz que Cristo se livrou do poder dos governos e das autoridades espirituais . Ele humilhou esses poderes publicamente, levando-os prisioneiros no seu desfile de vitória .

[[v51-2-16]]

^<<v51-2-16,16>>^ Portanto, que ninguém faça para vocês leis sobre o que devem comer ou beber, ou sobre os dias santos, e a Festa da Lua Nova , e o sábado.

[[v51-2-17]]

^<<v51-2-17,17>>^ Tudo isso é apenas uma sombra daquilo que virá; a realidade é Cristo.

[[v51-2-18]]

^<<v51-2-18,18>>^ Não deixem que ninguém os humilhe, afirmando que é melhor do que vocês porque diz ter visões e insiste numa falsa humildade e na adoração de anjos. Essas pessoas não têm nenhum motivo para estarem cheias de si, pois estão pensando como qualquer outra criatura humana pensa.

[[v51-2-19]]

^<<v51-2-19,19>>^ Elas não estão ligadas a Cristo, que é a cabeça. Cristo controla o corpo todo, o alimenta e mantém unido por meio das juntas e ligamentos, e assim o corpo cresce como Deus quer que cresça.

[[v51-2-20]]

^<<v51-2-20,20>>^ Vocês morreram com Cristo e por isso estão livres dos espíritos maus que dominam o Universo  . Então, por que é que vocês estão vivendo como se fossem deste mundo? Não obedeçam mais a regras como estas:

[[v51-2-21]]

^<<v51-2-21,21>>^ "Não toque nesta coisa", "não prove aquela", "não pegue naquela".

[[v51-2-22]]

^<<v51-2-22,22>>^ Todas essas proibições têm a ver com coisas que se tornam inúteis depois de usadas. São apenas regras e ensinamentos que as pessoas inventam.

[[v51-2-23]]

^<<v51-2-23,23>>^ De fato, essas regras parecem ser sábias, ao exigirem a adoração forçada dos anjos, a falsa humildade e um modo duro de tratar o corpo. Mas tudo isso não tem nenhum valor para controlar as paixões que levam à imoralidade.

'''

xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[&#60; Capítulo Anterior] | <<v51-2-0,Topo>> | xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[Próximo Capítulo &#62;]