include::./index.adoc[]

[[v35-1-0]]
=== Habacuque, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v35-1-1]]

^<<v35-1-1,1>>^ Esta é a mensagem que Deus, por meio de uma visão, deu a Habacuque.

[[v35-1-2]]

^<<v35-1-2,2>>^ Ó Senhor  Deus, até quando clamarei pedindo ajuda, e tu não me atenderás? Até quando gritarei: "Violência!", e tu não nos salvarás?

[[v35-1-3]]

^<<v35-1-3,3>>^ Por que me fazes ver tanta maldade? Por que toleras a injustiça? Estou cercado de destruição e violência; há brigas e lutas por toda parte.

[[v35-1-4]]

^<<v35-1-4,4>>^ Por isso, ninguém obedece à lei , e a justiça nunca vence. Os maus levam vantagem sobre os bons, e a justiça é torcida.

[[v35-1-5]]

^<<v35-1-5,5>>^ O Senhor  diz ao seu povo: "Olhem as nações em volta de vocês e fiquem admirados e assustados. Pois o que vou fazer agora é uma coisa em que vocês não acreditariam, mesmo que alguém contasse.

[[v35-1-6]]

^<<v35-1-6,6>>^ Estou atiçando os babilônios, aquele povo cruel e violento, sempre pronto a marchar pelo mundo inteiro, a fim de conquistar as terras dos outros.

[[v35-1-7]]

^<<v35-1-7,7>>^ "Eles espalham o medo e o terror e fazem valer as suas próprias ordens e leis .

[[v35-1-8]]

^<<v35-1-8,8>>^ Os seus cavalos são mais rápidos do que os leopardos, são mais ferozes do que os lobos do deserto. Os seus cavaleiros avançam montados; eles vêm correndo de longe, rápidos como a águia quando se joga sobre o animal que ela está caçando.

[[v35-1-9]]

^<<v35-1-9,9>>^ Os soldados avançam, ansiosos para conquistar; conforme avançam, vão espalhando o terror. Os seus prisioneiros são muitos; são mais numerosos do que os grãos de areia da praia.

[[v35-1-10]]

^<<v35-1-10,10>>^ Os soldados babilônios zombam dos reis e caçoam dos governadores. Eles riem das fortalezas; levantam uma rampa de ataque e as conquistam.

[[v35-1-11]]

^<<v35-1-11,11>>^ Depois, vão em frente, como o vento que passa; eles não adoram outro deus senão a sua própria força."

[[v35-1-12]]

^<<v35-1-12,12>>^ Tu sempre exististe, ó Senhor . Ó meu Santo Deus, tu és imortal . Tu és o nosso protetor. Ó Senhor , tu escolheste os babilônios e lhes deste forças para nos castigar.

[[v35-1-13]]

^<<v35-1-13,13>>^ Mas como podes tolerar esses traidores, essa gente má? Os teus olhos são puros demais para olhar o mal; tu não suportas ver as pessoas cometendo maldades. Como é, então, que ficas calado quando esses malvados matam pessoas que são melhores do que eles?

[[v35-1-14]]

^<<v35-1-14,14>>^ Por que tratas os seres humanos como se fossem peixes, como se fossem animais que não têm chefe?

[[v35-1-15]]

^<<v35-1-15,15>>^ Pois os babilônios pegam outros povos como os pescadores pegam peixes. Com os seus anzóis e redes pegam os povos e os arrastam para terra. Aí se alegram e ficam contentes.

[[v35-1-16]]

^<<v35-1-16,16>>^ Oferecem sacrifícios  às redes e apresentam ofertas aos anzóis, pois é por causa deles que os pescadores ficam ricos e têm muito que comer.

[[v35-1-17]]

^<<v35-1-17,17>>^ Será que os babilônios nunca deixarão de lutar e, sem dó nem piedade, continuarão a matar os povos?

'''

xref:034-naum/034-naum-003.adoc#v34-3-0[&#60; Capítulo Anterior] | <<v35-1-0,Topo>> | xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[Próximo Capítulo &#62;]