include::./index.adoc[]

[[v35-3-0]]
=== Habacuque, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v35-3-1]]

^<<v35-3-1,1>>^ Esta é uma oração do profeta  Habacuque, feita em forma de hino.

[[v35-3-2]]

^<<v35-3-2,2>>^ Ó Senhor , ouvi falar do que tens feito e estou cheio de temor . Faze agora, em nosso tempo, as coisas maravilhosas que fizeste no passado, para que nós também as vejamos. Mesmo que estejas irado , tem compaixão de nós!

[[v35-3-3]]

^<<v35-3-3,3>>^ Deus vem vindo da terra de Edom, o Santo Deus vem do monte Parã. A sua glória  cobre os céus, e na terra todos o louvam.

[[v35-3-4]]

^<<v35-3-4,4>>^ Ele brilha como a luz, e raios de luz saltam da sua mão, onde se esconde o seu poder.

[[v35-3-5]]

^<<v35-3-5,5>>^ Na frente dele vão pragas terríveis, e atrás vêm doenças mortais.

[[v35-3-6]]

^<<v35-3-6,6>>^ Ele para, e a terra treme; ele olha para as nações, e elas ficam com medo. Os montes antigos se abalam, caem as velhas montanhas por onde ele tem andado desde a eternidade.

[[v35-3-7]]

^<<v35-3-7,7>>^ Vi que os povos de Cuchã estão aflitos e que os moradores de Midiã estão com medo.

[[v35-3-8]]

^<<v35-3-8,8>>^ É contra os rios, ó Senhor , que estás irado? É contra o mar que estás furioso? É por isso que montas os teus cavalos e vens vitorioso no teu carro de guerra?

[[v35-3-9]]

^<<v35-3-9,9>>^ Pegas o teu arco e te preparas para atirar as tuas flechas. Tu cavas a terra com enchentes.

[[v35-3-10]]

^<<v35-3-10,10>>^ As montanhas te viram e tremeram; uma tromba-d'água caiu do céu. As águas debaixo da terra rugiram; as suas ondas imensas se levantaram.

[[v35-3-11]]

^<<v35-3-11,11>>^ O sol e a lua deixaram de brilhar quando viram o brilho das tuas flechas e a luz brilhante da tua lança.

[[v35-3-12]]

^<<v35-3-12,12>>^ Na tua ira, marchaste pela terra inteira, na tua fúria, pisaste as nações.

[[v35-3-13]]

^<<v35-3-13,13>>^ Saíste para salvar o teu povo, para salvar o rei que escolheste. Feriste o chefe dos maus e acabaste completamente com o seu exército.

[[v35-3-14]]

^<<v35-3-14,14>>^ Com as tuas flechas, mataste o comandante dos soldados quando avançavam como uma tempestade para nos atacar; eles vinham orgulhosos, querendo nos destruir como quem mata um pobre em segredo.

[[v35-3-15]]

^<<v35-3-15,15>>^ Montado nos teus cavalos marchaste pelo mar, pelas ondas furiosas do mar.

[[v35-3-16]]

^<<v35-3-16,16>>^ Quando ouvi tudo isso, fiquei assustado, e os meus lábios tremeram de medo. Perdi todas as forças e não pude ficar de pé. Portanto, vou esperar, tranquilo, o dia em que Deus castigará aqueles que nos atacam.

[[v35-3-17]]

^<<v35-3-17,17>>^ Ainda que as figueiras não produzam frutas, e as parreiras  não deem uvas; ainda que não haja azeitonas para apanhar nem trigo para colher; ainda que não haja mais ovelhas nos campos nem gado nos currais,

[[v35-3-18]]

^<<v35-3-18,18>>^ mesmo assim eu darei graças ao Senhor e louvarei a Deus, o meu Salvador.

[[v35-3-19]]

^<<v35-3-19,19>>^ O Senhor  Deus é a minha força. Ele torna o meu andar firme como o de uma corça e me leva para as montanhas, onde estarei seguro.

'''

xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[Próximo Capítulo &#62;]