include::./index.adoc[]

[[v35-2-0]]
=== Habacuque, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v35-2-1]]

^<<v35-2-1,1>>^ Vou subir a minha torre de vigia e vou esperar com atenção o que Deus vai dizer e como vai responder à minha queixa.

[[v35-2-2]]

^<<v35-2-2,2>>^ E o Senhor  Deus disse: "Escreva em tábuas a visão que você vai ter, escreva com clareza o que vou lhe mostrar, para que possa ser lido com facilidade.

[[v35-2-3]]

^<<v35-2-3,3>>^ Ainda não chegou o tempo certo para que a visão se cumpra; porém ela se cumprirá sem falta. O tempo certo vai chegar logo; portanto, espere, ainda que pareça demorar, pois a visão virá no momento exato.

[[v35-2-4]]

^<<v35-2-4,4>>^ A mensagem é esta: Os maus não terão segurança, mas as pessoas corretas viverão por serem fiéis a Deus."

[[v35-2-5]]

^<<v35-2-5,5>>^ De fato, a riqueza engana, e as pessoas orgulhosas nunca têm sossego. A sua ganância não tem fim. Elas nunca estão satisfeitas: como o mundo dos mortos , sempre querem mais.

[[v35-2-6]]

^<<v35-2-6,6>>^ Mas os povos conquistados desprezam os babilônios e zombam deles, dizendo: "Ai de vocês que ficam ricos pegando coisas que não lhes pertencem! Até quando vão enriquecer obrigando os seus devedores a pagarem as dívidas?"

[[v35-2-7]]

^<<v35-2-7,7>>^ De repente, vocês, os babilônios, serão os devedores; aí os seus credores os forçarão a pagar as dívidas e com juros. Eles vão atacá-los, e vocês ficarão com medo; eles levarão embora tudo o que é de vocês.

[[v35-2-8]]

^<<v35-2-8,8>>^ Vocês roubaram as riquezas dos povos de muitos países, e agora eles vão fazer o mesmo com vocês. Vocês vão pagar pelos crimes e pelas violências que cometeram contra os povos do mundo e contra as suas cidades.

[[v35-2-9]]

^<<v35-2-9,9>>^ Ai de você, babilônio cruel, que encheu a sua casa com o que roubou dos outros! Com isso, você quis se proteger de todo perigo e escapar dos seus inimigos.

[[v35-2-10]]

^<<v35-2-10,10>>^ Mas os seus planos trouxeram vergonha para a sua família, e, ao destruir muitos povos, você pôs a sua própria vida em perigo.

[[v35-2-11]]

^<<v35-2-11,11>>^ Até as pedras das paredes e a madeira das vigas gritam contra você!

[[v35-2-12]]

^<<v35-2-12,12>>^ Ai de você, pois construiu a sua cidade sobre um alicerce de crime e de injustiças!

[[v35-2-13]]

^<<v35-2-13,13>>^ Todo o trabalho forçado dos povos que você conquistou não vai adiantar nada, e o que eles construíram vai ser destruído pelo fogo. Foi o Senhor  Todo-Poderoso quem fez isso.

[[v35-2-14]]

^<<v35-2-14,14>>^ E a terra ficará cheia do conhecimento da glória  do Senhor , assim como as águas enchem o mar.

[[v35-2-15]]

^<<v35-2-15,15>>^ Ai de você, pois dá ao seu companheiro vinho misturado com drogas! Ele fica bêbado, tira a roupa, e todos o veem nu .

[[v35-2-16]]

^<<v35-2-16,16>>^ É você que vai perder a sua honra e ficar coberto de vergonha. Pois o Senhor  vai fazer você beber do copo da sua ira , e você também ficará bêbado. Em vez de receber homenagens, você será humilhado.

[[v35-2-17]]

^<<v35-2-17,17>>^ Você destruiu as árvores dos montes Líbanos e agora será destruído; você matou os animais e agora vai ficar com medo deles. Isso acontecerá por causa dos crimes e das violências que você cometeu contra os povos do mundo e contra as suas cidades.

[[v35-2-18]]

^<<v35-2-18,18>>^ Que valor tem um ídolo? Um ídolo não é mais do que uma imagem feita por um homem e que só serve para enganar. Os ídolos não podem falar; como é que alguém pode confiar num ídolo que ele mesmo fez?

[[v35-2-19]]

^<<v35-2-19,19>>^ Ai de você que diz a um ídolo de madeira: "Acorde!" e que ordena a um ídolo de pedra: "Fique de pé!" Será que um ídolo pode entregar alguma mensagem? Não! Não pode. Ele está todo coberto de ouro e de prata, mas é uma coisa morta.

[[v35-2-20]]

^<<v35-2-20,20>>^ O Senhor  está no seu santo Templo; que todos se calem na sua presença.

'''

xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[Próximo Capítulo &#62;]