include::./index.adoc[]

[[v33-1-0]]
=== Miquéias, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v33-1-1]]

^<<v33-1-1,1>>^ Esta é a mensagem que o Senhor  Deus deu a Miqueias, da cidade de Moresete. Miqueias teve estas visões a respeito das cidades de Samaria e de Jerusalém durante os reinados de Jotão, Acaz e Ezequias na terra de Judá.

[[v33-1-2]]

^<<v33-1-2,2>>^ Escutem, todos os povos; prestem atenção, todos os moradores da terra! O Senhor  vai ser testemunha contra vocês; do seu templo no céu, ele falará.

[[v33-1-3]]

^<<v33-1-3,3>>^ Ele descerá do lugar onde mora e caminhará sobre as montanhas.

[[v33-1-4]]

^<<v33-1-4,4>>^ Debaixo dos seus pés, as montanhas se desfazem; são como cera que se derrete no fogo. Os vales se abrem, como se uma enchente os cortasse ao meio.

[[v33-1-5]]

^<<v33-1-5,5>>^ Tudo isso acontecerá porque o povo de Israel pecou e se revoltou contra Deus. Quem é culpado da revolta de Israel? É o povo de Samaria! E quem é responsável por haver santuários pagãos em Judá? É o povo de Jerusalém!

[[v33-1-6]]

^<<v33-1-6,6>>^ Por isso, o Senhor  diz: — Eu farei com que a cidade de Samaria vire um montão de ruínas em campo aberto; farei com que seja um lugar para plantação de uvas. Farei com que as pedras da cidade rolem monte abaixo e que os alicerces das casas de Samaria fiquem aparecendo.

[[v33-1-7]]

^<<v33-1-7,7>>^ Todas as imagens serão destruídas, toda a riqueza conseguida à custa das prostitutas dos seus templos pagãos será queimada, e todos os ídolos virarão um monte de ruínas. Tudo o que foi comprado com o dinheiro das prostitutas será usado para pagar as prostitutas em outros templos pagãos.

[[v33-1-8]]

^<<v33-1-8,8>>^ Por isso, eu choro e grito de dor e em sinal de tristeza ando descalço e nu, uivando como uma raposa e soltando gritos de dor como uma avestruz.

[[v33-1-9]]

^<<v33-1-9,9>>^ Pois os ferimentos do povo de Samaria não podem ser curados; a destruição já atingiu Judá e está perto de Jerusalém, onde vive o meu povo.

[[v33-1-10]]

^<<v33-1-10,10>>^ Não contem em Gate a nossa derrota, nem comecem a chorar. Povo de Bete-Leafra , role no chão em sinal de desespero!

[[v33-1-11]]

^<<v33-1-11,11>>^ Moradores de Safir, vão nus e envergonhados para o cativeiro ! Os que vivem em Zaanã não devem sair da cidade; quando ouvirem o povo de Bete-Esel chorar, vocês saberão que eles não os podem ajudar.

[[v33-1-12]]

^<<v33-1-12,12>>^ Os que moram em Marote esperam ansiosos por socorro, pois o Senhor  fez a desgraça chegar bem perto de Jerusalém.

[[v33-1-13]]

^<<v33-1-13,13>>^ Moradores de Laquis, atrelem os cavalos aos carros! Vocês fizeram o mesmo que os israelitas, isto é, levaram o povo de Jerusalém ao pecado.

[[v33-1-14]]

^<<v33-1-14,14>>^ Portanto, povo de Judá, diga adeus à cidade de Moresete-Gate. O povo da cidade de Aczibe será uma armadilha para os reis de Israel.

[[v33-1-15]]

^<<v33-1-15,15>>^ O Senhor  Deus diz: — Vou entregar a cidade de Maressa nas mãos do inimigo, e as autoridades de Israel irão se esconder na caverna que fica perto da cidade de Adulã.

[[v33-1-16]]

^<<v33-1-16,16>>^ Povo de Judá, corte os cabelos e rape a cabeça em sinal de tristeza, pois os seus filhos queridos serão levados como prisioneiros para longe da sua pátria.

'''

xref:032-jonas/032-jonas-004.adoc#v32-4-0[&#60; Capítulo Anterior] | <<v33-1-0,Topo>> | xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[Próximo Capítulo &#62;]