include::./index.adoc[]

[[v33-5-0]]
=== Miquéias, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v33-5-1]]

^<<v33-5-1,1>>^ Povo de Jerusalém, prepare-se para se defender, pois as tropas inimigas estão cercando a cidade e querem matar o rei de Israel!

[[v33-5-2]]

^<<v33-5-2,2>>^ O Senhor  Deus diz: — Belém-Efrata, você é uma das menores cidades de Judá, mas do seu meio farei sair aquele que será o rei de Israel. Ele será descendente de uma família que começou em tempos antigos, num passado muito distante.

[[v33-5-3]]

^<<v33-5-3,3>>^ Deus vai entregar os israelitas nas mãos do inimigo, que os dominará até que nasça o filho da mulher que está para dar à luz. Então os israelitas que estão no cativeiro  voltarão a se reunir com os seus patrícios na Terra Prometida .

[[v33-5-4]]

^<<v33-5-4,4>>^ O rei virá e será o pastor do seu povo, governando-o com a força que o Senhor  lhe dará e em nome do Senhor , o seu glorioso  Deus. O seu povo viverá em segurança, pois o seu poder alcançará os lugares mais distantes do mundo.

[[v33-5-5]]

^<<v33-5-5,5>>^ E ele trará a paz. Quando os assírios invadirem o nosso país e conquistarem as nossas fortalezas, nós mandaremos para lutar contra eles os nossos líderes mais importantes.

[[v33-5-6]]

^<<v33-5-6,6>>^ Estes invadirão a terra de Ninrode, isto é, a Assíria, e a conquistarão. E assim, quando os assírios atacarem o nosso país, o rei nos salvará.

[[v33-5-7]]

^<<v33-5-7,7>>^ Os israelitas que continuarem vivos serão para os outros povos como o sereno que o Senhor  manda sobre a terra, como a chuva que cai nas plantas. Eles contarão com a ajuda de Deus e não com a dos seres humanos.

[[v33-5-8]]

^<<v33-5-8,8>>^ Os israelitas que continuarem vivos serão no meio dos outros povos como um leão entre os animais selvagens, como um leão novo que ataca um rebanho de ovelhas e as agarra e despedaça, sem que ninguém as possa salvar.

[[v33-5-9]]

^<<v33-5-9,9>>^ Assim o povo de Israel conquistará e matará todos os seus inimigos.

[[v33-5-10]]

^<<v33-5-10,10>>^ O Senhor  diz ao povo de Israel: — Naquele dia, matarei os seus cavalos e destruirei os seus carros de guerra.

[[v33-5-11]]

^<<v33-5-11,11>>^ Deixarei em ruínas as cidades e derrubarei as fortalezas.

[[v33-5-12]]

^<<v33-5-12,12>>^ Acabarei com as suas feitiçarias e os deixarei sem adivinhos.

[[v33-5-13]]

^<<v33-5-13,13>>^ Destruirei os seus ídolos e as colunas do deus Baal , e vocês nunca mais adorarão objetos feitos por vocês mesmos.

[[v33-5-14]]

^<<v33-5-14,14>>^ Derrubarei todos os postes da deusa Aserá  e destruirei as cidades.

[[v33-5-15]]

^<<v33-5-15,15>>^ Na minha ira , no meu furor, eu me vingarei de todas as nações que me desobedeceram.

'''

xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[Próximo Capítulo &#62;]