include::./index.adoc[]

[[v33-6-0]]
=== Miquéias, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v33-6-1]]

^<<v33-6-1,1>>^ Escutem a acusação que o Senhor  Deus vai fazer contra o seu povo! Levanta-te, ó Deus, e faze a tua acusação; e que as montanhas e os montes ouçam o que dizes.

[[v33-6-2]]

^<<v33-6-2,2>>^ Ó montanhas, ó alicerces firmes da terra, escutem a acusação que o Senhor  faz contra Israel. Pois ele tem uma questão para resolver com o seu povo; ele vai acusar o povo de Israel.

[[v33-6-3]]

^<<v33-6-3,3>>^ O Senhor  diz: — Meu povo, o que foi que eu fiz de errado? Será que exigi demais de vocês? Respondam!

[[v33-6-4]]

^<<v33-6-4,4>>^ Eu os tirei do Egito, salvando-os da escravidão, e enviei Moisés, Arão e Míriam para os guiar pelo deserto.

[[v33-6-5]]

^<<v33-6-5,5>>^ Meu povo, lembre dos planos que Balaque, rei de Moabe, fez contra vocês e da resposta que Balaão, filho de Beor, lhe deu. Lembrem de tudo o que aconteceu desde que saíram do acampamento do vale das Acácias até que chegaram à cidade de Gilgal. Não esqueçam nunca as vitórias que eu, o Senhor , consegui.

[[v33-6-6]]

^<<v33-6-6,6>>^ O que é que eu levarei quando for adorar o Senhor ? O que oferecerei ao Deus Altíssimo? Será que deverei apresentar a Deus bezerros de um ano para serem completamente queimados?

[[v33-6-7]]

^<<v33-6-7,7>>^ Será que o Senhor  ficará contente se eu oferecer milhares de carneiros ou milhares e milhares de rios de azeite? Será que deverei oferecer o meu filho mais velho como sacrifício  para pagar os meus pecados e as minhas maldades?

[[v33-6-8]]

^<<v33-6-8,8>>^ O Senhor  já nos mostrou o que é bom, ele já disse o que exige de nós. O que ele quer é que façamos o que é direito, que amemos uns aos outros com dedicação e que vivamos em humilde obediência ao nosso Deus.

[[v33-6-9]]

^<<v33-6-9,9>>^ O Senhor  está falando com a cidade de Jerusalém, e os que são sábios ouvem com respeito o que Deus está dizendo. Ele diz: — Tribo  de Judá e moradores de Jerusalém, escutem!

[[v33-6-10]]

^<<v33-6-10,10>>^ Nas casas dos maus há riquezas que eles ajuntaram desonestamente. Eles usam medidas falsas, que eu detesto.

[[v33-6-11]]

^<<v33-6-11,11>>^ Como posso perdoar pessoas que usam balanças falsas e pesos falsos?

[[v33-6-12]]

^<<v33-6-12,12>>^ Em Jerusalém, as pessoas ricas exploram os outros, e todos os seus moradores são mentirosos e trapaceiros.

[[v33-6-13]]

^<<v33-6-13,13>>^ Por isso, já comecei a castigar vocês; e, por causa dos seus pecados, vou acabar com vocês.

[[v33-6-14]]

^<<v33-6-14,14>>^ Vocês não terão comida suficiente e estarão sempre passando fome. Procurarão ajuntar riquezas, mas não poderão guardar nada; e, se guardarem alguma coisa, farei com que seja destruída na guerra.

[[v33-6-15]]

^<<v33-6-15,15>>^ Plantarão, mas não comerão nada; esmagarão as azeitonas, mas não chegarão a usar o azeite; pisarão as uvas, mas não beberão o vinho.

[[v33-6-16]]

^<<v33-6-16,16>>^ Tudo isso vai acontecer porque vocês imitaram os maus costumes e as maldades do rei Onri e do seu filho, o rei Acabe, e seguiram os conselhos deles. Por isso, vou destruir Jerusalém, e todo mundo vai zombar dos moradores da cidade. Vocês serão insultados por todos os povos.

'''

xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[Próximo Capítulo &#62;]