include::./index.adoc[]

[[v33-4-0]]
=== Miquéias, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v33-4-1]]

^<<v33-4-1,1>>^ No futuro, o monte do Templo do Senhor será o mais alto de todos, ficando acima de todos os montes. Todas as nações irão correndo para lá,

[[v33-4-2]]

^<<v33-4-2,2>>^ e esses povos dirão: "Vamos subir o monte do Senhor , vamos ao Templo do Deus de Israel. Ele nos ensinará o que devemos fazer, e nós andaremos nos seus caminhos. Pois os ensinamentos do Senhor  vêm de Jerusalém; é do monte Sião que ele fala ao seu povo."

[[v33-4-3]]

^<<v33-4-3,3>>^ Ele será juiz entre muitos povos e decidirá questões entre grandes nações distantes. Os povos transformarão as suas espadas em arados e as suas lanças em foices. Nunca mais as nações farão guerra, nem se prepararão novamente para batalhas.

[[v33-4-4]]

^<<v33-4-4,4>>^ Todos viverão seguros, e cada um descansará calmamente debaixo das suas figueiras e das suas parreiras . Esta é a promessa do Senhor  Todo-Poderoso.

[[v33-4-5]]

^<<v33-4-5,5>>^ As outras nações adoram e obedecem aos seus deuses; mas, quanto a nós, o Senhor  é o nosso Deus, e nós o adoraremos e lhe obedeceremos para sempre.

[[v33-4-6]]

^<<v33-4-6,6>>^ O Senhor  Deus diz: — Virá o dia em que eu reunirei aqueles que sofrem, todos os que eu castiguei, quando os expulsei da sua pátria.

[[v33-4-7]]

^<<v33-4-7,7>>^ Trarei de volta dos países distantes todos os que estiverem vivos e farei deles uma nação poderosa. Eu, o Senhor , reinarei no monte Sião , e, daquele tempo em diante e para sempre, eles serão novamente o meu povo.

[[v33-4-8]]

^<<v33-4-8,8>>^ E Jerusalém, o lugar de onde eu, como pastor de ovelhas, olho e cuido do meu povo, voltará a ser a capital do país, a cidade mais importante de Israel.

[[v33-4-9]]

^<<v33-4-9,9>>^ Jerusalém, por que é que você está chorando como uma mulher que está com dores de parto? Será que é porque você não tem rei e os seus conselheiros morreram?

[[v33-4-10]]

^<<v33-4-10,10>>^ Jerusalém, torça-se de dor e grite como uma mulher que está dando à luz, pois os seus moradores vão sair e morar nos campos e depois irão até a Babilônia. Mas o Senhor  os salvará e os livrará do poder dos inimigos.

[[v33-4-11]]

^<<v33-4-11,11>>^ Muitas nações se reuniram para atacar Jerusalém. Essa gente diz: "Jerusalém deve ser destruída e profanada !"

[[v33-4-12]]

^<<v33-4-12,12>>^ Mas eles não sabem o que o Senhor  está pensando e planejando. Não sabem que ele os reuniu para os castigar, como se ajuntam as espigas para pisá-las e separar o trigo da palha.

[[v33-4-13]]

^<<v33-4-13,13>>^ O Senhor  Deus diz: — Povo de Jerusalém, levante-se e ataque os inimigos! Eu darei a vocês a força de um touro com chifres de ferro e cascos de bronze. Vocês destruirão muitos povos e oferecerão a mim, o Senhor do mundo inteiro, as riquezas que eles conquistaram pela força.

'''

xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[Próximo Capítulo &#62;]