include::./index.adoc[]

[[v33-3-0]]
=== Miquéias, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v33-3-1]]

^<<v33-3-1,1>>^ Escutem, líderes e autoridades de Israel! Vocês deviam praticar a justiça

[[v33-3-2]]

^<<v33-3-2,2>>^ e, no entanto, odeiam o bem e amam o mal. Vocês tiram a pele do meu povo e arrancam a carne dos seus ossos.

[[v33-3-3]]

^<<v33-3-3,3>>^ Vocês devoram o meu povo: arrancam a pele, quebram os ossos e cortam a carne em pedaços, como se faz com a carne que vai ser cozinhada.

[[v33-3-4]]

^<<v33-3-4,4>>^ Virá o dia em que vocês clamarão ao Senhor  Deus, mas ele não os atenderá; vocês fazem o que é mau, e por isso ele não ouvirá as suas orações.

[[v33-3-5]]

^<<v33-3-5,5>>^ Os profetas  enganam o povo. Para os que lhes pagam eles prometem paz, mas ameaçam com guerra os que não lhes dão nada. O Senhor  diz a esses profetas:

[[v33-3-6]]

^<<v33-3-6,6>>^ — Em vez de visões vocês terão a escuridão, e em vez de revelações haverá somente trevas para vocês. A luz do dia vai desaparecer para vocês, e a escuridão da noite cairá sobre vocês.

[[v33-3-7]]

^<<v33-3-7,7>>^ Os adivinhos e os que dizem o que vai acontecer no futuro passarão vergonha. Não receberão resposta de Deus e por isso ficarão desmoralizados.

[[v33-3-8]]

^<<v33-3-8,8>>^ Mas, quanto a mim, o Espírito do Senhor  me dá poder, amor pela justiça e coragem para condenar os pecados e as maldades do povo de Israel.

[[v33-3-9]]

^<<v33-3-9,9>>^ Escutem, líderes e autoridades de Israel! Vocês odeiam o que é bom e torcem a justiça.

[[v33-3-10]]

^<<v33-3-10,10>>^ Vocês estão construindo Jerusalém, a cidade santa, sobre um alicerce de injustiças e de crimes de sangue.

[[v33-3-11]]

^<<v33-3-11,11>>^ As autoridades de Jerusalém aceitam dinheiro para torcer a justiça, os sacerdotes cobram para ensinar a Lei , e os profetas exigem pagamento para adivinhar o futuro. Mas mesmo assim eles afirmam que recebem ajuda de Deus. Eles dizem: "Nenhum mal vai acontecer porque o Senhor  está do nosso lado."

[[v33-3-12]]

^<<v33-3-12,12>>^ Portanto, por causa de vocês, Jerusalém vai virar um montão de pedras, o monte Sião  vai ser arado como um campo, e o lugar onde fica o Templo se tornará uma floresta.

'''

xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[&#60; Capítulo Anterior] | <<v33-3-0,Topo>> | xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[Próximo Capítulo &#62;]