include::./index.adoc[]

[[v33-7-0]]
=== Miquéias, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v33-7-1]]

^<<v33-7-1,1>>^ Ai de mim! Sou como um homem faminto que depois da colheita procura figos nas figueiras e uvas nas parreiras , mas não encontra nada porque todas as uvas e todos os figos maduros foram colhidos.

[[v33-7-2]]

^<<v33-7-2,2>>^ No país inteiro não há uma só pessoa honesta, nem uma que obedeça a Deus. Todos estão procurando matar os outros; cada um procura pôr o seu patrício na cadeia.

[[v33-7-3]]

^<<v33-7-3,3>>^ Todos estão prontos para fazer o que é mau. Autoridades exigem dinheiro por fora, e juízes recebem presentes para torcer a justiça. Os poderosos contam como vão satisfazer os seus maus desejos. Todos planejam fazer coisas más.

[[v33-7-4]]

^<<v33-7-4,4>>^ Mesmo as melhores pessoas, as que são mais honestas, não valem mais do que espinheiros. Mas está chegando o dia em que Deus vai castigá-los, conforme os vigias dele, isto é, os profetas , anunciaram. Naquele dia, haverá confusão geral.

[[v33-7-5]]

^<<v33-7-5,5>>^ Não acreditem nos vizinhos, nem confiem nos amigos. Cada um tome cuidado até com o que diz à sua mulher.

[[v33-7-6]]

^<<v33-7-6,6>>^ Pois hoje em dia os filhos desprezam os pais, as filhas desobedecem às mães, e as noras brigam com as sogras; e os piores inimigos de qualquer pessoa são os próprios parentes.

[[v33-7-7]]

^<<v33-7-7,7>>^ Eu, porém, ponho a minha esperança em Deus, o Senhor , e confio firmemente que ele me salvará. O meu Deus me atenderá.

[[v33-7-8]]

^<<v33-7-8,8>>^ Inimigos, não zombem de nós! De fato, caímos, mas ficaremos novamente de pé; agora, estamos na escuridão, mas o Senhor  será a nossa luz.

[[v33-7-9]]

^<<v33-7-9,9>>^ Nós pecamos contra Deus e agora teremos de suportar a sua ira . Mas ele vai julgar a nossa causa e nos fará justiça. Ele nos levará para a luz, e nós seremos salvos.

[[v33-7-10]]

^<<v33-7-10,10>>^ Quando os nossos inimigos virem isso, ficarão envergonhados, pois disseram: "Onde está o Senhor , o Deus de vocês?" E agora vamos ter o prazer de vê-los derrotados; eles serão pisados como a lama das ruas.

[[v33-7-11]]

^<<v33-7-11,11>>^ Povo de Jerusalém, está chegando o tempo de construir de novo as muralhas da cidade e de mudar para mais longe as fronteiras do país.

[[v33-7-12]]

^<<v33-7-12,12>>^ Naquele dia, os nossos patrícios voltarão para Jerusalém. Eles virão da Assíria, do Egito e da região do rio Eufrates; virão dos mares e das montanhas mais distantes.

[[v33-7-13]]

^<<v33-7-13,13>>^ Mas o mundo inteiro vai virar um deserto por causa dos pecados dos seus moradores.

[[v33-7-14]]

^<<v33-7-14,14>>^ Ó Deus, nosso pastor, cuida de nós, o teu rebanho. Pois vivemos isolados numa floresta cercada de terras boas e férteis. Como fizeste no passado, leva-nos agora para os bons pastos de Basã e de Gileade.

[[v33-7-15]]

^<<v33-7-15,15>>^ Faze milagres a nosso favor, como fizeste quando nos tiraste do Egito.

[[v33-7-16]]

^<<v33-7-16,16>>^ Nações poderosas verão isso e, apesar de todo o seu poder, ficarão envergonhadas. Os outros povos ficarão com medo, fecharão a boca e taparão os ouvidos.

[[v33-7-17]]

^<<v33-7-17,17>>^ Eles se arrastarão no pó como cobras, como animais que se arrastam pelo chão. Tremendo de medo, eles sairão das suas fortalezas e, cheios de temor , voltarão para o Senhor , nosso Deus.

[[v33-7-18]]

^<<v33-7-18,18>>^ Ó Deus, não há outro deus como tu, pois perdoas os pecados e as maldades daqueles do teu povo que ficaram vivos. Tu não continuas irado  para sempre, mas tens prazer em nos mostrar sempre o teu amor.

[[v33-7-19]]

^<<v33-7-19,19>>^ Novamente, terás compaixão de nós; acabarás com as nossas maldades e jogarás os nossos pecados no fundo do mar.

[[v33-7-20]]

^<<v33-7-20,20>>^ Como prometeste antigamente aos nossos antepassados, tu serás fiel e mostrarás o teu amor a nós, os descendentes de Abraão e de Jacó.

'''

xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:034-naum/034-naum-001.adoc#v34-1-0[Próximo Capítulo &#62;]