include::./index.adoc[]

[[v33-2-0]]
=== Miquéias, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v33-2-1]]

^<<v33-2-1,1>>^ Ai daqueles que antes de se levantarem de manhã já fazem planos para explorar e maltratar os outros! E logo que se levantam fazem o que querem, pois são poderosos!

[[v33-2-2]]

^<<v33-2-2,2>>^ Quando querem terrenos ou casas, eles os tomam. Maltratam os outros e não respeitam a família nem a propriedade de ninguém.

[[v33-2-3]]

^<<v33-2-3,3>>^ Por isso, o Senhor  diz: — Vou fazer a desgraça cair sobre vocês, e vocês não escaparão. Será um tempo de sofrimento, e vocês não andarão mais tão cheios de orgulho.

[[v33-2-4]]

^<<v33-2-4,4>>^ Quando aquele dia chegar, outros vão inventar um provérbio a respeito de vocês e cantarão esta canção triste: "Estamos completamente arruinados! O Senhor  tirou a nossa terra, ele tirou o que era nosso e deu aos que nos conquistaram."

[[v33-2-5]]

^<<v33-2-5,5>>^ Portanto, quando a Terra Prometida  for repartida de novo entre o povo do Senhor  Deus, nenhum de vocês receberá nem uma parte dela.

[[v33-2-6]]

^<<v33-2-6,6>>^ O povo me diz: — Pare com essas profecias ! Não diga isso! Não é possível que Deus faça a desgraça cair sobre a gente!

[[v33-2-7]]

^<<v33-2-7,7>>^ Será que o povo de Israel está amaldiçoado? Será que o Senhor  está irritado? É assim que ele age? O Senhor  Deus diz: — De fato, as minhas palavras fazem bem aos que são bons.

[[v33-2-8]]

^<<v33-2-8,8>>^ Mas vocês, como se fossem inimigos, atacaram o meu povo. Os homens voltam da guerra, pensando que estão sãos e salvos, mas vocês roubam as suas roupas.

[[v33-2-9]]

^<<v33-2-9,9>>^ Vocês expulsam dos seus lares queridos as mulheres do meu povo, e assim os filhos delas perdem para sempre as bênçãos que prometi.

[[v33-2-10]]

^<<v33-2-10,10>>^ Saiam daqui! Vão embora! Pois não é este o lugar onde vocês vão descansar em paz. Aqui há tanta gente desonesta e sem-vergonha, que a destruição vai ser total.

[[v33-2-11]]

^<<v33-2-11,11>>^ O profeta  que essa gente prefere é aquele que anda pregando mentiras e falsidades, prometendo vinho e cerveja para todos.

[[v33-2-12]]

^<<v33-2-12,12>>^ O Senhor  diz ao povo de Israel: — Eu reunirei todos vocês que restarem e os trarei de volta para a Terra Prometida , como o pastor leva as ovelhas para o pasto ou as recolhe no curral. E mais uma vez as cidades do país ficarão movimentadas e cheias de gente.

[[v33-2-13]]

^<<v33-2-13,13>>^ Deus abrirá caminho para o seu povo, e eles sairão livres pelos portões da cidade. O Rei, o Senhor , irá na frente, e todos o seguirão.

'''

xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[Próximo Capítulo &#62;]