include::./index.adoc[]

[[v49-1-0]]
=== Efésios, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v49-1-1]]

^<<v49-1-1,1>>^ Eu, Paulo, apóstolo  de Cristo Jesus pela vontade de Deus, escrevo esta carta ao povo de Deus da cidade de Éfeso, o povo que é fiel por estar unido com Cristo Jesus.

[[v49-1-2]]

^<<v49-1-2,2>>^ Que a graça  e a paz de Deus, o nosso Pai, e do Senhor Jesus Cristo estejam com vocês!

[[v49-1-3]]

^<<v49-1-3,3>>^ Agradeçamos ao Deus e Pai do nosso Senhor Jesus Cristo, pois ele nos tem abençoado por estarmos unidos com Cristo, dando-nos todos os dons  espirituais do mundo celestial.

[[v49-1-4]]

^<<v49-1-4,4>>^ Antes da criação do mundo, Deus já nos havia escolhido para sermos dele por meio da nossa união com Cristo, a fim de pertencermos somente a Deus e nos apresentarmos diante dele sem culpa. Por causa do seu amor por nós,

[[v49-1-5]]

^<<v49-1-5,5>>^ Deus já havia resolvido que nos tornaria seus filhos, por meio de Jesus Cristo, pois este era o seu prazer e a sua vontade.

[[v49-1-6]]

^<<v49-1-6,6>>^ Portanto, louvemos a Deus pela sua gloriosa graça , que ele nos deu gratuitamente por meio do seu querido Filho.

[[v49-1-7]]

^<<v49-1-7,7>>^ Pois, pela morte de Cristo na cruz, nós somos libertados, isto é, os nossos pecados são perdoados. Como é maravilhosa a graça de Deus,

[[v49-1-8]]

^<<v49-1-8,8>>^ que ele nos deu com tanta fartura! Deus, em toda a sua sabedoria e entendimento,

[[v49-1-9]]

^<<v49-1-9,9>>^ fez o que havia resolvido e nos revelou o plano secreto que tinha decidido realizar por meio de Cristo.

[[v49-1-10]]

^<<v49-1-10,10>>^ Esse plano é unir, no tempo certo, debaixo da autoridade de Cristo, tudo o que existe no céu e na terra.

[[v49-1-11]]

^<<v49-1-11,11>>^ Todas as coisas são feitas de acordo com o plano e com a decisão de Deus. De acordo com a sua vontade e com aquilo que ele havia resolvido desde o princípio, Deus nos escolheu para sermos o seu povo, por meio da nossa união com Cristo.

[[v49-1-12]]

^<<v49-1-12,12>>^ Portanto, digo que nós , que fomos os primeiros a pôr a nossa esperança em Cristo, louvemos a glória  de Deus.

[[v49-1-13]]

^<<v49-1-13,13>>^ A mesma coisa aconteceu também com vocês . Quando ouviram a verdadeira mensagem, a boa notícia que trouxe para vocês a salvação, vocês creram em Cristo. E Deus pôs em vocês a sua marca de proprietário quando lhes deu o Espírito Santo, que ele havia prometido.

[[v49-1-14]]

^<<v49-1-14,14>>^ O Espírito Santo é a garantia de que receberemos o que Deus prometeu ao seu povo, e isso nos dá a certeza de que Deus dará liberdade completa aos que são seus. Portanto, louvemos a sua glória.

[[v49-1-15]]

^<<v49-1-15,15>>^ Por isso, desde que ouvi falar da fé que vocês têm no Senhor Jesus e do amor que vocês têm por todos os irmãos na fé,

[[v49-1-16]]

^<<v49-1-16,16>>^ não paro de agradecer a Deus por causa de vocês. Eu sempre lembro de vocês nas minhas orações.

[[v49-1-17]]

^<<v49-1-17,17>>^ E peço ao Deus do nosso Senhor Jesus Cristo, o Pai glorioso , que dê a vocês o seu Espírito, o Espírito que os tornará sábios e revelará Deus a vocês, para que assim vocês o conheçam como devem conhecer.

[[v49-1-18]]

^<<v49-1-18,18>>^ Peço que Deus abra a mente de vocês para que vejam a luz dele e conheçam a esperança para a qual ele os chamou . E também para que saibam como são maravilhosas as bênçãos que ele prometeu ao seu povo

[[v49-1-19]]

^<<v49-1-19,19>>^ e como é grande o seu poder que age em nós, os que cremos nele. Esse poder que age em nós é a mesma força poderosa

[[v49-1-20]]

^<<v49-1-20,20>>^ que ele usou quando ressuscitou Cristo e fez com que ele se sentasse ao seu lado direito no mundo celestial.

[[v49-1-21]]

^<<v49-1-21,21>>^ Cristo reina sobre todos os governos celestiais, autoridades, forças e poderes . Ele tem um título que está acima de todos os títulos das autoridades que existem neste mundo e no mundo que há de vir.

[[v49-1-22]]

^<<v49-1-22,22>>^ Deus colocou todas as coisas debaixo da autoridade de Cristo e deu Cristo à Igreja como o único Senhor de tudo.

[[v49-1-23]]

^<<v49-1-23,23>>^ A Igreja é o corpo de Cristo; ela completa Cristo, o qual completa todas as coisas em todos os lugares.

'''

xref:048-galatas/048-galatas-006.adoc#v48-6-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-efesios/049-efesios-002.adoc#v49-2-0[Próximo Capítulo &#62;]