include::./index.adoc[]

[[v49-6-0]]
=== Efésios, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v49-6-1]]

^<<v49-6-1,1>>^ Filhos, o dever cristão de vocês é obedecer ao seu pai e à sua mãe, pois isso é certo.

[[v49-6-2]]

^<<v49-6-2,2>>^ Como dizem as Escrituras : "Respeite o seu pai e a sua mãe." E esse é o primeiro mandamento que tem uma promessa, a qual é:

[[v49-6-3]]

^<<v49-6-3,3>>^ "Faça isso a fim de que tudo corra bem para você, e você viva muito tempo na terra."

[[v49-6-4]]

^<<v49-6-4,4>>^ Pais, não tratem os seus filhos de um jeito que faça com que eles fiquem irritados. Pelo contrário, vocês devem criá-los com a disciplina e os ensinamentos cristãos.

[[v49-6-5]]

^<<v49-6-5,5>>^ Escravos, obedeçam com medo e respeito àqueles que são seus donos aqui na terra. E façam isso com sinceridade, como se estivessem servindo a Cristo.

[[v49-6-6]]

^<<v49-6-6,6>>^ Não obedeçam aos seus donos só quando eles estiverem vendo vocês, somente para conseguir a aprovação deles. Mas, como escravos de Cristo, façam de todo o coração o que Deus quer.

[[v49-6-7]]

^<<v49-6-7,7>>^ Trabalhem com prazer, como se vocês estivessem trabalhando para o Senhor e não para pessoas.

[[v49-6-8]]

^<<v49-6-8,8>>^ Lembrem que cada pessoa, seja escrava ou livre, será recompensada pelo Senhor de acordo com o que fizer.

[[v49-6-9]]

^<<v49-6-9,9>>^ Donos de escravos, tratem os seus escravos também com respeito e parem de ameaçá-los com castigos. Lembrem que vocês e os seus escravos pertencem ao mesmo Senhor, que está no céu, o qual trata a todos igualmente.

[[v49-6-10]]

^<<v49-6-10,10>>^ Para terminar: tornem-se cada vez mais fortes, vivendo unidos com o Senhor e recebendo a força do seu grande poder.

[[v49-6-11]]

^<<v49-6-11,11>>^ Vistam-se com toda a armadura  que Deus dá a vocês, para ficarem firmes contra as armadilhas do Diabo.

[[v49-6-12]]

^<<v49-6-12,12>>^ Pois nós não estamos lutando contra seres humanos, mas contra as forças espirituais do mal que vivem nas alturas, isto é, os governos, as autoridades e os poderes que dominam completamente este mundo de escuridão .

[[v49-6-13]]

^<<v49-6-13,13>>^ Por isso peguem agora a armadura que Deus lhes dá. Assim, quando chegar o dia de enfrentarem as forças do mal, vocês poderão resistir aos ataques do inimigo e, depois de lutarem até o fim, vocês continuarão firmes, sem recuar.

[[v49-6-14]]

^<<v49-6-14,14>>^ Portanto, estejam preparados. Usem a verdade como cinturão. Vistam-se com a couraça  da justiça

[[v49-6-15]]

^<<v49-6-15,15>>^ e calcem, como sapatos, a prontidão para anunciar a boa notícia de paz.

[[v49-6-16]]

^<<v49-6-16,16>>^ E levem sempre a fé como escudo , para poderem se proteger de todos os dardos  de fogo do Maligno .

[[v49-6-17]]

^<<v49-6-17,17>>^ Recebam a salvação como capacete e a palavra de Deus como a espada que o Espírito Santo lhes dá.

[[v49-6-18]]

^<<v49-6-18,18>>^ Façam tudo isso orando a Deus e pedindo a ajuda dele. Orem sempre, guiados pelo Espírito de Deus. Fiquem alertas. Não desanimem e orem sempre por todo o povo de Deus.

[[v49-6-19]]

^<<v49-6-19,19>>^ E orem também por mim, a fim de que Deus me dê a mensagem certa para que, quando eu falar, fale com coragem e torne conhecido o segredo do evangelho  .

[[v49-6-20]]

^<<v49-6-20,20>>^ Eu sou embaixador a serviço desse evangelho, embora esteja agora na cadeia. Portanto, orem para que eu seja corajoso e anuncie o evangelho como devo anunciar.

[[v49-6-21]]

^<<v49-6-21,21>>^ Tíquico, nosso querido irmão e fiel servo  no trabalho do Senhor, lhes dará todas as notícias a meu respeito, para que vocês possam saber como estou passando.

[[v49-6-22]]

^<<v49-6-22,22>>^ Eu o estou enviando a vocês para que ele conte como todos nós aqui estamos passando, a fim de que vocês fiquem animados com as informações que ele vai dar.

[[v49-6-23]]

^<<v49-6-23,23>>^ Que Deus, o Pai, e o Senhor Jesus Cristo deem a todos os irmãos paz e amor, com fé!

[[v49-6-24]]

^<<v49-6-24,24>>^ E que a graça  de Deus esteja com todos os que amam o nosso Senhor Jesus Cristo com um amor que não tem fim!

'''

xref:049-efesios/049-efesios-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[Próximo Capítulo &#62;]