include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v49-4-1]]

^<<v49-4-1,1>>^ Por isso eu, que estou preso porque sirvo o Senhor Jesus Cristo, peço a vocês que vivam de uma maneira que esteja de acordo com o que Deus quis quando chamou  vocês.

[[v49-4-2]]

^<<v49-4-2,2>>^ Sejam sempre humildes, bem-educados e pacientes, suportando uns aos outros com amor.

[[v49-4-3]]

^<<v49-4-3,3>>^ Façam tudo para conservar, por meio da paz que une vocês, a união que o Espírito dá.

[[v49-4-4]]

^<<v49-4-4,4>>^ Há um só corpo, e um só Espírito, e uma só esperança, para a qual Deus chamou vocês.

[[v49-4-5]]

^<<v49-4-5,5>>^ Há um só Senhor, uma só fé e um só batismo.

[[v49-4-6]]

^<<v49-4-6,6>>^ E há somente um Deus e Pai de todos, que é o Senhor de todos, que age por meio de todos e está em todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ Porém cada um de nós recebeu um dom  especial, de acordo com o que Cristo deu.

[[v49-4-8]]

^<<v49-4-8,8>>^ Como dizem as Escrituras Sagradas : "Quando ele subiu aos lugares mais altos, levou consigo muitos prisioneiros e deu dons às pessoas."

[[v49-4-9]]

^<<v49-4-9,9>>^ O que quer dizer "ele subiu"? Quer dizer que ele também desceu até os lugares mais baixos da terra, isto é, até o mundo dos mortos .

[[v49-4-10]]

^<<v49-4-10,10>>^ Assim, quem desceu é o mesmo que subiu, acima e além dos céus, para encher todo o Universo  com a sua presença.

[[v49-4-11]]

^<<v49-4-11,11>>^ Foi ele quem "deu dons às pessoas". Ele escolheu alguns para serem apóstolos , outros para profetas , outros para evangelistas e ainda outros para pastores e mestres da Igreja.

[[v49-4-12]]

^<<v49-4-12,12>>^ Ele fez isso para preparar o povo de Deus para o serviço cristão, a fim de construir o corpo de Cristo.

[[v49-4-13]]

^<<v49-4-13,13>>^ Desse modo todos nós chegaremos a ser um na nossa fé e no nosso conhecimento do Filho de Deus. E assim seremos pessoas maduras e alcançaremos a altura espiritual de Cristo.

[[v49-4-14]]

^<<v49-4-14,14>>^ Então não seremos mais como crianças, arrastados pelas ondas e empurrados por qualquer vento de ensinamentos de pessoas falsas. Essas pessoas inventam mentiras e, por meio delas, levam outros para caminhos errados.

[[v49-4-15]]

^<<v49-4-15,15>>^ Pelo contrário, falando a verdade com espírito de amor, cresçamos em tudo até alcançarmos a altura espiritual de Cristo, que é a cabeça.

[[v49-4-16]]

^<<v49-4-16,16>>^ É ele quem faz com que o corpo todo fique bem-ajustado e todas as partes fiquem ligadas entre si por meio da união de todas elas. E, assim, cada parte funciona bem, e o corpo todo cresce e se desenvolve por meio do amor.

[[v49-4-17]]

^<<v49-4-17,17>>^ Portanto, em nome do Senhor eu digo e insisto no seguinte: não vivam mais como os pagãos, pois os pensamentos deles não têm valor,

[[v49-4-18]]

^<<v49-4-18,18>>^ e a mente deles está na escuridão. Eles não têm parte na vida que Deus dá porque são completamente ignorantes e teimosos.

[[v49-4-19]]

^<<v49-4-19,19>>^ Eles perderam toda a vergonha e se entregaram totalmente aos vícios; eles não têm nenhum controle e fazem todo tipo de coisas indecentes.

[[v49-4-20]]

^<<v49-4-20,20>>^ Mas não foi essa a maneira de viver que vocês aprenderam como seguidores de Cristo.

[[v49-4-21]]

^<<v49-4-21,21>>^ Com certeza vocês ouviram falar dele e, como seus seguidores, aprenderam a verdade que está em Jesus.

[[v49-4-22]]

^<<v49-4-22,22>>^ Portanto, abandonem a velha natureza de vocês, que fazia com que vocês vivessem uma vida de pecados e que estava sendo destruída pelos seus desejos enganosos.

[[v49-4-23]]

^<<v49-4-23,23>>^ É preciso que o coração e a mente de vocês sejam completamente renovados.

[[v49-4-24]]

^<<v49-4-24,24>>^ Vistam-se com a nova natureza, criada por Deus, que é parecida com a sua própria natureza e que se mostra na vida verdadeira, a qual é correta e dedicada a ele.

[[v49-4-25]]

^<<v49-4-25,25>>^ Por isso não mintam mais. Que cada um diga a verdade para o seu irmão na fé, pois todos nós somos membros do corpo de Cristo!

[[v49-4-26]]

^<<v49-4-26,26>>^ Se vocês ficarem com raiva, não deixem que isso faça com que pequem e não fiquem o dia inteiro com raiva.

[[v49-4-27]]

^<<v49-4-27,27>>^ Não deem ao Diabo oportunidade para tentar vocês.

[[v49-4-28]]

^<<v49-4-28,28>>^ Quem roubava que não roube mais, porém comece a trabalhar a fim de viver honestamente e poder ajudar os pobres.

[[v49-4-29]]

^<<v49-4-29,29>>^ Não digam palavras que fazem mal aos outros, mas usem apenas palavras boas, que ajudam os outros a crescer na fé e a conseguir o que necessitam, para que as coisas que vocês dizem façam bem aos que ouvem.

[[v49-4-30]]

^<<v49-4-30,30>>^ E não façam com que o Espírito Santo de Deus fique triste. Pois o Espírito é a marca de propriedade de Deus colocada em vocês, a qual é a garantia de que chegará o dia em que Deus os libertará.

[[v49-4-31]]

^<<v49-4-31,31>>^ Abandonem toda amargura, todo ódio e toda raiva. Nada de gritarias, insultos e maldades!

[[v49-4-32]]

^<<v49-4-32,32>>^ Pelo contrário, sejam bons e atenciosos uns para com os outros. E perdoem uns aos outros, assim como Deus, por meio de Cristo, perdoou vocês.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]