include::./index.adoc[]

[[v49-2-0]]
=== Efésios, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v49-2-1]]

^<<v49-2-1,1>>^ Antigamente, por terem desobedecido a Deus e por terem cometido pecados, vocês estavam espiritualmente mortos.

[[v49-2-2]]

^<<v49-2-2,2>>^ Naquele tempo vocês seguiam o mau caminho deste mundo e faziam a vontade daquele que governa os poderes espirituais do espaço, o espírito que agora controla os que desobedecem a Deus.

[[v49-2-3]]

^<<v49-2-3,3>>^ De fato, todos nós éramos como eles e vivíamos de acordo com a nossa natureza humana , fazendo o que o nosso corpo e a nossa mente queriam. Assim, porque somos seres humanos como os outros, nós também estávamos destinados a sofrer o castigo de Deus.

[[v49-2-4]]

^<<v49-2-4,4>>^ Mas a misericórdia de Deus é muito grande, e o seu amor por nós é tanto,

[[v49-2-5]]

^<<v49-2-5,5>>^ que, quando estávamos espiritualmente mortos por causa da nossa desobediência, ele nos trouxe para a vida que temos em união com Cristo. Pela graça  de Deus vocês são salvos.

[[v49-2-6]]

^<<v49-2-6,6>>^ Por estarmos unidos com Cristo Jesus, Deus nos ressuscitou com ele para reinarmos com ele no mundo celestial.

[[v49-2-7]]

^<<v49-2-7,7>>^ Deus fez isso para mostrar, em todos os tempos do futuro, a imensa grandeza da sua graça, que é nossa por meio do amor que ele nos mostrou por meio de Cristo Jesus.

[[v49-2-8]]

^<<v49-2-8,8>>^ Pois pela graça de Deus vocês são salvos por meio da fé. Isso não vem de vocês, mas é um presente dado por Deus.

[[v49-2-9]]

^<<v49-2-9,9>>^ A salvação não é o resultado dos esforços de vocês; portanto, ninguém pode se orgulhar de tê-la.

[[v49-2-10]]

^<<v49-2-10,10>>^ Pois foi Deus quem nos fez o que somos agora; em nossa união com Cristo Jesus, ele nos criou para que fizéssemos as boas obras que ele já havia preparado para nós.

[[v49-2-11]]

^<<v49-2-11,11>>^ Lembrem que vocês, os não judeus, eram chamados de incircuncidados  pelos judeus, que chamam a si mesmos de circuncidados por praticar a circuncisão . Lembrem do que vocês eram no passado.

[[v49-2-12]]

^<<v49-2-12,12>>^ Naquele tempo vocês estavam separados de Cristo; eram estrangeiros e não pertenciam ao povo escolhido de Deus. Não tinham parte nas suas alianças  , que eram baseadas nas promessas de Deus para o seu povo. E neste mundo viviam sem esperança e sem Deus.

[[v49-2-13]]

^<<v49-2-13,13>>^ Mas agora, unidos com Cristo Jesus, vocês, que estavam longe de Deus, foram trazidos para perto dele pela morte de Cristo na cruz.

[[v49-2-14]]

^<<v49-2-14,14>>^ Pois foi Cristo quem nos trouxe a paz, tornando os judeus e os não judeus um só povo. Por meio do sacrifício  do seu corpo, ele derrubou o muro de inimizade que separava os judeus dos não judeus.

[[v49-2-15]]

^<<v49-2-15,15>>^ Ele acabou com a lei , juntamente com os seus mandamentos e regulamentos; e dos dois povos formou um só povo, novo e unido com ele. Foi assim que ele trouxe a paz.

[[v49-2-16]]

^<<v49-2-16,16>>^ Pela sua morte na cruz, Cristo destruiu a inimizade que havia entre os dois povos. Por meio da cruz, ele os uniu em um só corpo e os levou de volta para Deus.

[[v49-2-17]]

^<<v49-2-17,17>>^ Assim Cristo veio e anunciou a todos a boa notícia de paz, tanto a vocês, os não judeus, que estavam longe de Deus, como aos judeus, que estavam perto dele.

[[v49-2-18]]

^<<v49-2-18,18>>^ É por meio de Cristo que todos nós, judeus e não judeus, podemos ir, pelo poder de um só Espírito, até a presença do Pai.

[[v49-2-19]]

^<<v49-2-19,19>>^ Portanto, vocês, os não judeus, não são mais estrangeiros nem visitantes. Agora vocês são cidadãos que pertencem ao povo de Deus e são membros da família dele.

[[v49-2-20]]

^<<v49-2-20,20>>^ Vocês são como um edifício e estão construídos sobre o alicerce que os apóstolos  e os profetas  colocaram. E a pedra fundamental desse edifício é o próprio Cristo Jesus.

[[v49-2-21]]

^<<v49-2-21,21>>^ Ele mantém o edifício todo bem firme e faz com que cresça como um templo dedicado ao Senhor.

[[v49-2-22]]

^<<v49-2-22,22>>^ Assim vocês também, unidos com Cristo, estão sendo construídos, junto com os outros, para se tornarem uma casa onde Deus vive por meio do seu Espírito.

'''

xref:049-efesios/049-efesios-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-efesios/049-efesios-003.adoc#v49-3-0[Próximo Capítulo &#62;]