include::./index.adoc[]

[[v49-3-0]]
=== Efésios, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v49-3-1]]

^<<v49-3-1,1>>^ Por essa razão eu oro a Deus, eu, Paulo, que estou preso por causa de Cristo Jesus para o bem de vocês, os não judeus.

[[v49-3-2]]

^<<v49-3-2,2>>^ Com certeza vocês já sabem que Deus, por causa da sua graça , me deu esse trabalho para o bem de vocês.

[[v49-3-3]]

^<<v49-3-3,3>>^ Deus me revelou o seu plano secreto e fez com que eu o conhecesse. (Eu escrevi isso em poucas palavras,

[[v49-3-4]]

^<<v49-3-4,4>>^ e, se vocês lerem o que escrevi, poderão saber como entendo o segredo de Cristo.)

[[v49-3-5]]

^<<v49-3-5,5>>^ No passado esse segredo não foi contado aos seres humanos, mas agora, por meio do seu Espírito, Deus o revelou aos seus santos apóstolos  e profetas .

[[v49-3-6]]

^<<v49-3-6,6>>^ O segredo é este: por meio do evangelho  os não judeus participam com os judeus das bênçãos divinas. Eles são membros do mesmo corpo e participam da promessa que Deus fez por meio de Cristo Jesus.

[[v49-3-7]]

^<<v49-3-7,7>>^ Graças ao dom  que Deus, na sua bondade, me deu, e, pela ação do seu poder, eu fui colocado como servo  do evangelho.

[[v49-3-8]]

^<<v49-3-8,8>>^ Eu sou menos do que o menor de todos os que pertencem a Deus, mas mesmo assim ele me deu este privilégio de anunciar aos não judeus a boa notícia das imensas riquezas de Cristo.

[[v49-3-9]]

^<<v49-3-9,9>>^ E também me deu o privilégio de fazer com que todos vejam como se realiza o plano secreto de Deus. Deus, que criou tudo, escondeu esse segredo durante os tempos passados.

[[v49-3-10]]

^<<v49-3-10,10>>^ E isso aconteceu a fim de que agora, por meio da Igreja, as autoridades e os poderes angélicos do mundo celestial conheçam a sabedoria de Deus em todas as suas diferentes formas.

[[v49-3-11]]

^<<v49-3-11,11>>^ Deus fez isso de acordo com o seu propósito eterno, que ele realizou por meio de Cristo Jesus, o nosso Senhor.

[[v49-3-12]]

^<<v49-3-12,12>>^ Por estarmos unidos com Cristo, por meio da nossa fé nele, nós temos a coragem de nos apresentarmos na presença de Deus com toda a confiança.

[[v49-3-13]]

^<<v49-3-13,13>>^ Portanto, eu lhes peço que não desanimem por causa dos meus sofrimentos por vocês, pois eles lhes trazem benefício.

[[v49-3-14]]

^<<v49-3-14,14>>^ Por esse motivo, eu me ajoelho diante do Pai,

[[v49-3-15]]

^<<v49-3-15,15>>^ de quem todas as famílias no céu e na terra recebem o seu verdadeiro nome.

[[v49-3-16]]

^<<v49-3-16,16>>^ E peço a Deus que, da riqueza da sua glória , ele, por meio do seu Espírito, dê a vocês poder para que sejam espiritualmente fortes.

[[v49-3-17]]

^<<v49-3-17,17>>^ Peço também que, por meio da fé, Cristo viva no coração de vocês. E oro para que vocês tenham raízes e alicerces no amor,

[[v49-3-18]]

^<<v49-3-18,18>>^ para que assim, junto com todo o povo de Deus, vocês possam compreender o amor de Cristo em toda a sua largura, comprimento, altura e profundidade.

[[v49-3-19]]

^<<v49-3-19,19>>^ Sim, embora seja impossível conhecê-lo perfeitamente, peço que vocês venham a conhecê-lo, para que assim Deus encha completamente o ser de vocês com a sua natureza.

[[v49-3-20]]

^<<v49-3-20,20>>^ E agora, que a glória seja dada a Deus, o qual, por meio do seu poder que age em nós, pode fazer muito mais do que nós pedimos ou até pensamos!

[[v49-3-21]]

^<<v49-3-21,21>>^ Glória a Deus por meio da Igreja e por meio de Cristo Jesus, por todos os tempos e para todo o sempre! Amém !

'''

xref:049-efesios/049-efesios-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-efesios/049-efesios-004.adoc#v49-4-0[Próximo Capítulo &#62;]