include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v37-1-1]]

^<<v37-1-1,1>>^ No segundo ano do reinado de Dario, rei da Pérsia, no primeiro dia do sexto mês, o Senhor  Deus mandou uma mensagem por meio do profeta  Ageu. Essa mensagem era para o governador de Judá, Zorobabel, filho de Salatiel, e para o Grande Sacerdote  Josué, filho de Jozadaque.

[[v37-1-2]]

^<<v37-1-2,2>>^ O Senhor  Todo-Poderoso disse o seguinte: — O povo está dizendo que ainda não chegou o tempo de reconstruir o Templo.

[[v37-1-3]]

^<<v37-1-3,3>>^ Por isso, o Senhor  falou assim por meio do profeta Ageu:

[[v37-1-4]]

^<<v37-1-4,4>>^ — Povo de Judá, será que fica bem vocês viverem em casas luxuosas enquanto o meu Templo continua destruído?

[[v37-1-5]]

^<<v37-1-5,5>>^ Pensem bem no que tem acontecido com vocês.

[[v37-1-6]]

^<<v37-1-6,6>>^ Vocês semearam muitas sementes, mas colheram pouco; têm comida, mas não é suficiente para matar a fome; têm vinho, mas não dá para ficarem bêbados; têm roupas, porém elas não chegam para os proteger do frio; e o salário que o trabalhador recebe não dá para viver.

[[v37-1-7]]

^<<v37-1-7,7>>^ Por isso o Senhor  Todo-Poderoso diz: — Pensem bem no que tem acontecido com vocês.

[[v37-1-8]]

^<<v37-1-8,8>>^ Agora, vão até as montanhas, tragam madeira e construam de novo o Templo. Eu ficarei muito contente com esse Templo e ali serei adorado e honrado.

[[v37-1-9]]

^<<v37-1-9,9>>^ — Vocês esperavam colheitas grandes, porém elas foram pequenas. E, quando estavam levando para casa o pouco que colheram, eu soprei tudo para longe. E por que foi que eu, o Senhor  Todo-Poderoso, fiz isso? Foi porque vocês só vivem cuidando das suas próprias casas, mas não se importam com a minha Casa, que está destruída.

[[v37-1-10]]

^<<v37-1-10,10>>^ É por isso que não chove e os campos não produzem colheitas.

[[v37-1-11]]

^<<v37-1-11,11>>^ Eu fiz com que houvesse seca nos campos e nas montanhas; fiz com que a seca atingisse as plantações de cereais, as parreiras , as oliveiras e todas as outras plantações do país. Ela castigou as pessoas, os animais e todas as plantações.

[[v37-1-12]]

^<<v37-1-12,12>>^ Então Zorobabel, filho de Salatiel, e o Grande Sacerdote  Josué, filho de Jozadaque, e todos os que haviam voltado do cativeiro  na Babilônia temeram a Deus  e obedeceram à mensagem que o Senhor , o Deus deles, tinha mandado por meio do profeta  Ageu.

[[v37-1-13]]

^<<v37-1-13,13>>^ E assim Ageu, o mensageiro de Deus, falou e entregou ao povo de Judá a seguinte mensagem: — Eu estarei com vocês. Eu, o Senhor , falei.

[[v37-1-14]]

^<<v37-1-14,14>>^ O Senhor  deu coragem e ânimo ao governador de Judá, Zorobabel, filho de Salatiel, ao Grande Sacerdote Josué, filho de Jozadaque, e a todos os que haviam voltado do cativeiro na Babilônia. Eles foram e começaram a trabalhar no Templo do seu Deus, o Senhor  Todo-Poderoso,

[[v37-1-15]]

^<<v37-1-15,15>>^ no dia vinte e quatro do sexto mês do segundo ano do reinado de Dario.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]