include::./index.adoc[]

[[v37-2-0]]
=== Ageu, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v37-2-1]]

^<<v37-2-1,1>>^ Neste segundo ano do reinado de Dario, rei da Pérsia, no dia vinte e um do sétimo mês, o Senhor  falou de novo com o profeta  Ageu. Deus mandou

[[v37-2-2]]

^<<v37-2-2,2>>^ que ele fosse falar com o governador de Judá, Zorobabel, filho de Salatiel, com o Grande Sacerdote  Josué, filho de Jozadaque, e com todo o povo e lhes dissesse o seguinte:

[[v37-2-3]]

^<<v37-2-3,3>>^ — Deve haver alguém aqui que viu o Templo quando ele ainda era belo . Mas vejam como está agora! Não lhes parece que não vale nada mesmo?

[[v37-2-4]]

^<<v37-2-4,4>>^ No entanto tenham coragem! Coragem, Zorobabel! Coragem, Josué! Coragem, toda a gente deste país! Trabalhem todos, pois eu, o Senhor  Todo-Poderoso, estou com vocês.

[[v37-2-5]]

^<<v37-2-5,5>>^ Conforme a aliança  que fiz com o meu povo quando o tirei do Egito, o meu Espírito sempre está com vocês. Portanto, não fiquem com medo.

[[v37-2-6]]

^<<v37-2-6,6>>^ — Pois é isto o que eu, o Senhor  Todo-Poderoso, digo: Daqui a pouco farei com que tremam o céu e a terra, o mar e a terra firme.

[[v37-2-7]]

^<<v37-2-7,7>>^ Vou fazer com que tremam todas as nações, e as suas riquezas serão trazidas para o meu Templo aqui em Jerusalém. E assim encherei o meu Templo de beleza.

[[v37-2-8]]

^<<v37-2-8,8>>^ Toda a prata e todo o ouro do mundo são meus.

[[v37-2-9]]

^<<v37-2-9,9>>^ Então o novo Templo será ainda mais belo do que o primeiro, e dali eu darei prosperidade e paz ao meu povo. Eu, o Senhor  Todo-Poderoso, falei.

[[v37-2-10]]

^<<v37-2-10,10>>^ Neste mesmo ano, no dia vinte e quatro do nono mês, o Senhor  falou de novo com o profeta  Ageu.

[[v37-2-11]]

^<<v37-2-11,11>>^ O Senhor  Todo-Poderoso disse: — Vá falar com os sacerdotes e peça a opinião deles a respeito da seguinte questão:

[[v37-2-12]]

^<<v37-2-12,12>>^ Suponham que alguém esteja levando na dobra da sua capa  um pedaço da carne que foi oferecida em sacrifício  a Deus. Então, se a capa tocar num pão, ou num cozido, ou em vinho, ou em azeite, ou em qualquer outra comida, isso quer dizer que estas coisas também ficarão puras ? Ageu fez a pergunta, e os sacerdotes disseram que não.

[[v37-2-13]]

^<<v37-2-13,13>>^ Aí Ageu perguntou aos sacerdotes: — E, se alguém ficou impuro  por ter tocado num defunto e depois tocar em qualquer uma daquelas comidas, isso quer dizer que elas também ficam impuras? Os sacerdotes responderam: — Sim! Elas ficam impuras.

[[v37-2-14]]

^<<v37-2-14,14>>^ Então Ageu disse: — O Senhor  diz que é exatamente isso o que acontece com esse povo. Para Deus, são impuros todo o povo deste país, tudo o que eles fazem e todos os sacrifícios que são oferecidos no altar.

[[v37-2-15]]

^<<v37-2-15,15>>^ O Senhor  Deus diz: — Pensem bem em tudo o que aconteceu desde aquele dia. Antes de vocês terem começado a construção do Templo,

[[v37-2-16]]

^<<v37-2-16,16>>^ o que é que acontecia? Se alguém ia até um depósito procurando duzentos quilos de trigo, encontrava só cem quilos; se fosse até o lugar onde se faz vinho querendo cem litros, encontrava somente quarenta.

[[v37-2-17]]

^<<v37-2-17,17>>^ Eu os castiguei com ventos muito quentes, com pragas nas plantas e com chuvas de pedra e assim destruí todas as suas plantações; mas mesmo assim vocês não voltaram para mim.

[[v37-2-18]]

^<<v37-2-18,18>>^ Hoje mesmo, no dia vinte e quatro do nono mês, vocês acabaram de construir o alicerce do Templo. E vejam bem o que vai acontecer daqui em diante.

[[v37-2-19]]

^<<v37-2-19,19>>^ Mesmo que agora não haja trigo nos depósitos, mesmo que as parreiras , as figueiras, as romãzeiras e as oliveiras não tenham produzido nada, de hoje em diante eu os abençoarei.

[[v37-2-20]]

^<<v37-2-20,20>>^ Naquele mesmo dia, o dia vinte e quatro do nono mês, o Senhor  falou de novo com Ageu

[[v37-2-21]]

^<<v37-2-21,21>>^ e mandou que ele dissesse a Zorobabel, o governador de Judá, o seguinte: — Eu vou fazer tremer o céu e a terra;

[[v37-2-22]]

^<<v37-2-22,22>>^ vou derrubar os tronos dos reis e acabar com o poder de todos eles. Vou destruir os carros de guerra e os que andam neles, e os cavalos também morrerão; os cavaleiros matarão uns aos outros.

[[v37-2-23]]

^<<v37-2-23,23>>^ E, quando aquele dia chegar, eu farei com que, em meu nome, você governe o meu povo, pois você, Zorobabel, filho de Salatiel, é o meu servo  escolhido. Eu, o Senhor  Todo-Poderoso, falei.

'''

xref:037-ageu/037-ageu-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[Próximo Capítulo &#62;]