include::./index.adoc[]

[[v60-3-0]]
=== 1 Pedro, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v60-3-1]]

^<<v60-3-1,1>>^ Assim também você, esposa, deve obedecer ao seu marido a fim de que, se ele não crê na mensagem de Deus, seja levado a crer pelo modo de você agir. Não será preciso dizer nada

[[v60-3-2]]

^<<v60-3-2,2>>^ porque ele verá como a conduta de você é honesta e respeitosa.

[[v60-3-3]]

^<<v60-3-3,3>>^ Não procure ficar bonita usando enfeites, penteados exagerados, joias ou vestidos caros.

[[v60-3-4]]

^<<v60-3-4,4>>^ Pelo contrário, a beleza de você deve estar no coração, pois ela não se perde; ela é a beleza de um espírito calmo e delicado, que tem muito valor para Deus.

[[v60-3-5]]

^<<v60-3-5,5>>^ Porque era assim que costumavam se enfeitar as mulheres do passado, as mulheres que eram dedicadas a Deus e que punham a sua esperança nele. Elas eram obedientes ao seu marido.

[[v60-3-6]]

^<<v60-3-6,6>>^ Sara foi assim; ela obedecia a Abraão e o chamava de "meu senhor". Você será agora sua filha se praticar o bem e não tiver medo de nada.

[[v60-3-7]]

^<<v60-3-7,7>>^ Também você, marido, na vida em comum com a esposa, reconheça que a mulher é o sexo mais fraco e que por isso deve ser tratada com respeito. Porque a esposa também vai receber, junto com você, o dom  da vida, que é dado por Deus. Aja assim para que nada atrapalhe as orações de vocês.

[[v60-3-8]]

^<<v60-3-8,8>>^ Finalmente, que todos vocês tenham o mesmo modo de pensar e de sentir. Amem uns aos outros e sejam educados e humildes uns com os outros.

[[v60-3-9]]

^<<v60-3-9,9>>^ Não paguem mal com mal, nem ofensa com ofensa. Pelo contrário, paguem a ofensa com uma bênção porque, quando Deus os chamou , ele prometeu dar uma bênção a vocês.

[[v60-3-10]]

^<<v60-3-10,10>>^ Como dizem as Escrituras Sagradas : "Quem quiser gozar a vida e ter dias felizes não fale coisas más e não conte mentiras.

[[v60-3-11]]

^<<v60-3-11,11>>^ Afaste-se do mal e faça o bem; procure a paz e faça tudo para alcançá-la.

[[v60-3-12]]

^<<v60-3-12,12>>^ Pois o Senhor olha com atenção as pessoas honestas e ouve os seus pedidos, porém é contra os que fazem o mal."

[[v60-3-13]]

^<<v60-3-13,13>>^ Se, de fato, vocês quiserem fazer o bem, quem lhes fará o mal?

[[v60-3-14]]

^<<v60-3-14,14>>^ Como vocês serão felizes se tiverem de sofrer por fazerem o que é certo! Não tenham medo de ninguém, nem fiquem preocupados.

[[v60-3-15]]

^<<v60-3-15,15>>^ Tenham no coração de vocês respeito por Cristo e o tratem como Senhor. Estejam sempre prontos para responder a qualquer pessoa que pedir que expliquem a esperança que vocês têm.

[[v60-3-16]]

^<<v60-3-16,16>>^ Porém façam isso com educação e respeito. Tenham sempre a consciência limpa. Assim, quando vocês forem insultados, os que falarem mal da boa conduta de vocês como seguidores de Cristo ficarão envergonhados.

[[v60-3-17]]

^<<v60-3-17,17>>^ Porque é melhor sofrer por fazer o bem, se for esta a vontade de Deus, do que por fazer o mal.

[[v60-3-18]]

^<<v60-3-18,18>>^ Pois o próprio Cristo sofreu uma vez por todas pelos pecados, um homem bom em favor dos maus, para levar vocês a Deus. Ele morreu no corpo, mas foi ressuscitado no espírito,

[[v60-3-19]]

^<<v60-3-19,19>>^ e no espírito foi e pregou aos espíritos que estavam presos .

[[v60-3-20]]

^<<v60-3-20,20>>^ Estes eram os espíritos daqueles que não tinham obedecido a Deus, quando ele ficou esperando com paciência nos dias em que Noé estava construindo a barca. As poucas pessoas que estavam nela, oito ao todo, foram salvas pela água.

[[v60-3-21]]

^<<v60-3-21,21>>^ Aquela água representava o batismo, que agora salva vocês. Esse batismo não é lavar a sujeira do corpo, mas é o compromisso feito com Deus, o qual vem de uma consciência limpa. Essa salvação vem por meio da ressurreição de Jesus Cristo,

[[v60-3-22]]

^<<v60-3-22,22>>^ que foi para o céu e está do lado direito de Deus, governando os anjos, as autoridades e os poderes do céu .

'''

xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[&#60; Capítulo Anterior] | <<v60-3-0,Topo>> | xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[Próximo Capítulo &#62;]