include::./index.adoc[]

[[v60-5-0]]
=== 1 Pedro, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v60-5-1]]

^<<v60-5-1,1>>^ Eu, que também sou presbítero , dou agora conselhos aos outros presbíteros que estão entre vocês. Sou uma testemunha dos sofrimentos de Cristo e vou tomar parte na glória  que será revelada.

[[v60-5-2]]

^<<v60-5-2,2>>^ Aconselho que cuidem bem do rebanho que Deus lhes deu e façam isso de boa vontade, como Deus quer, e não de má vontade. Não façam o seu trabalho para ganhar dinheiro, mas com o verdadeiro desejo de servir.

[[v60-5-3]]

^<<v60-5-3,3>>^ Não procurem dominar os que foram entregues aos cuidados de vocês, mas sejam um exemplo para o rebanho.

[[v60-5-4]]

^<<v60-5-4,4>>^ E, quando o Grande Pastor aparecer, vocês receberão a coroa gloriosa , que nunca perde o seu brilho.

[[v60-5-5]]

^<<v60-5-5,5>>^ E vocês, jovens, sejam obedientes aos mais velhos. Que todos prestem serviços uns aos outros com humildade, pois as Escrituras Sagradas  dizem: "Deus é contra os orgulhosos, mas é bondoso com os humildes!"

[[v60-5-6]]

^<<v60-5-6,6>>^ Portanto, sejam humildes debaixo da poderosa mão de Deus para que ele os honre no tempo certo.

[[v60-5-7]]

^<<v60-5-7,7>>^ Entreguem todas as suas preocupações a Deus, pois ele cuida de vocês.

[[v60-5-8]]

^<<v60-5-8,8>>^ Estejam alertas e fiquem vigiando porque o inimigo de vocês, o Diabo, anda por aí como um leão que ruge, procurando alguém para devorar.

[[v60-5-9]]

^<<v60-5-9,9>>^ Fiquem firmes na fé e enfrentem o Diabo porque vocês sabem que no mundo inteiro os seus irmãos na fé estão passando pelos mesmos sofrimentos.

[[v60-5-10]]

^<<v60-5-10,10>>^ Mas, depois de sofrerem por um pouco de tempo, o Deus que tem por nós um amor sem limites e que chamou  vocês para tomarem parte na sua eterna glória, por estarem unidos com Cristo, ele mesmo os aperfeiçoará e dará firmeza, força e verdadeira segurança.

[[v60-5-11]]

^<<v60-5-11,11>>^ A ele seja o poder para sempre! Amém !

[[v60-5-12]]

^<<v60-5-12,12>>^ Escrevo para vocês esta pequena carta com a ajuda de Silas, a quem eu considero um fiel irmão na fé. Quero animá-los e dar o meu testemunho de que as bênçãos que vocês têm recebido são uma prova verdadeira da graça  de Deus. Continuem firmes, pois, nessa graça.

[[v60-5-13]]

^<<v60-5-13,13>>^ A igreja que está em Babilônia , escolhida também por Deus, manda saudações. O meu filho Marcos também manda saudações.

[[v60-5-14]]

^<<v60-5-14,14>>^ Cumprimentem uns aos outros com um beijo de irmão. Que a paz esteja com todos vocês que pertencem a Cristo!

'''

xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[&#60; Capítulo Anterior] | <<v60-5-0,Topo>> | xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[Próximo Capítulo &#62;]