include::./index.adoc[]

[[v60-2-0]]
=== 1 Pedro, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v60-2-1]]

^<<v60-2-1,1>>^ Portanto, abandonem tudo o que é mau, toda mentira, fingimento, inveja e críticas injustas.

[[v60-2-2]]

^<<v60-2-2,2>>^ Sejam como criancinhas recém-nascidas, desejando sempre o puro leite espiritual, para que, bebendo dele, vocês possam crescer e ser salvos.

[[v60-2-3]]

^<<v60-2-3,3>>^ Pois, como dizem as Escrituras Sagradas : "Vocês já descobriram por vocês mesmos que o Senhor é bom."

[[v60-2-4]]

^<<v60-2-4,4>>^ Cheguem perto dele, a pedra viva que os seres humanos rejeitaram como inútil, mas que Deus escolheu como de grande valor.

[[v60-2-5]]

^<<v60-2-5,5>>^ Vocês, também, como pedras vivas, deixem que Deus os use na construção de um templo espiritual onde vocês servirão como sacerdotes dedicados a Deus. E isso para que, por meio de Jesus Cristo, ofereçam sacrifícios  que Deus aceite.

[[v60-2-6]]

^<<v60-2-6,6>>^ Pois as Escrituras Sagradas dizem: "Eu escolhi uma pedra de muito valor, que agora ponho em Sião como a pedra principal do alicerce. Quem crer nela não ficará desiludido."

[[v60-2-7]]

^<<v60-2-7,7>>^ Essa pedra é de muito valor para vocês, os que creem. Mas, para os que não creem, "A pedra que os construtores rejeitaram veio a ser a mais importante de todas."

[[v60-2-8]]

^<<v60-2-8,8>>^ E em outra parte as Escrituras Sagradas dizem: "Esta é a pedra em que as pessoas vão tropeçar, a rocha que vai fazê-las cair." Essas pessoas tropeçaram porque não creram na mensagem, de acordo com a vontade de Deus para elas.

[[v60-2-9]]

^<<v60-2-9,9>>^ Mas vocês são a raça escolhida, os sacerdotes do Rei, a nação completamente dedicada a Deus, o povo que pertence a ele. Vocês foram escolhidos para anunciar os atos poderosos de Deus, que os chamou  da escuridão para a sua maravilhosa luz.

[[v60-2-10]]

^<<v60-2-10,10>>^ Antes, vocês não eram o povo de Deus, mas agora são o seu povo; antes, não conheciam a misericórdia de Deus, mas agora já receberam a sua misericórdia.

[[v60-2-11]]

^<<v60-2-11,11>>^ Queridos amigos, lembrem que vocês são estrangeiros de passagem por este mundo. Peço, portanto, que evitem as paixões carnais que estão sempre em guerra contra a alma.

[[v60-2-12]]

^<<v60-2-12,12>>^ A conduta de vocês entre os pagãos deve ser boa, para que, quando eles os acusarem de criminosos, tenham de reconhecer que vocês praticam boas ações, e assim louvem a Deus no dia da sua vinda.

[[v60-2-13]]

^<<v60-2-13,13>>^ Por causa do Senhor, sejam obedientes a toda autoridade humana: ao Imperador , que é a mais alta autoridade;

[[v60-2-14]]

^<<v60-2-14,14>>^ e aos governadores , que são escolhidos por ele para castigar os criminosos e elogiar os que fazem o bem.

[[v60-2-15]]

^<<v60-2-15,15>>^ Pois Deus quer que vocês façam o bem para que os ignorantes e tolos não tenham nada que dizer contra vocês.

[[v60-2-16]]

^<<v60-2-16,16>>^ Vivam como pessoas livres. Não usem a liberdade para encobrir o mal, mas vivam como escravos de Deus.

[[v60-2-17]]

^<<v60-2-17,17>>^ Respeitem todas as pessoas, amem os seus irmãos na fé, temam a Deus  e respeitem o Imperador.

[[v60-2-18]]

^<<v60-2-18,18>>^ Vocês, empregados, sejam obedientes aos seus patrões e os respeitem, não somente os que são bons e compreensivos, mas também aqueles que os tratam mal.

[[v60-2-19]]

^<<v60-2-19,19>>^ Se vocês suportarem sofrimentos injustos, sabendo que esta é a vontade de Deus, ele abençoará vocês por causa disso.

[[v60-2-20]]

^<<v60-2-20,20>>^ Pois, se vocês fazem o mal e são castigados, qual é o merecimento de suportarem com paciência o castigo? Mas, se vocês sofrem por terem feito o bem e suportam esse sofrimento com paciência, Deus os abençoará por causa disso,

[[v60-2-21]]

^<<v60-2-21,21>>^ pois foi para isso que ele os chamou . O próprio Cristo sofreu por vocês e deixou o exemplo, para que sigam os seus passos.

[[v60-2-22]]

^<<v60-2-22,22>>^ Ele não cometeu nenhum pecado, e nunca disse uma só mentira.

[[v60-2-23]]

^<<v60-2-23,23>>^ Quando foi insultado, não respondeu com insultos. Quando sofreu, não ameaçou, mas pôs a sua esperança em Deus, o justo Juiz.

[[v60-2-24]]

^<<v60-2-24,24>>^ O próprio Cristo levou os nossos pecados no seu corpo sobre a cruz a fim de que morrêssemos para o pecado e vivêssemos uma vida correta. Por meio dos ferimentos dele vocês foram curados.

[[v60-2-25]]

^<<v60-2-25,25>>^ Vocês eram como ovelhas que haviam perdido o caminho, mas agora foram trazidos de volta para seguir o Pastor, que cuida da vida espiritual de vocês.

'''

xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[Próximo Capítulo &#62;]