include::./index.adoc[]

[[v60-1-0]]
=== 1 Pedro, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v60-1-1]]

^<<v60-1-1,1>>^ Eu, Pedro, apóstolo  de Jesus Cristo, escrevo esta carta ao povo de Deus que vive espalhado nas províncias  do Ponto, Galácia, Capadócia, Ásia e Bitínia .

[[v60-1-2]]

^<<v60-1-2,2>>^ Vocês foram escolhidos de acordo com o propósito de Deus, o Pai. E pelo Espírito de Deus vocês foram feitos um povo dedicado a ele a fim de obedecerem a Jesus Cristo e ficarem purificados  pelo seu sangue. Que vocês tenham, mais e mais, a graça  e a paz de Deus!

[[v60-1-3]]

^<<v60-1-3,3>>^ Louvemos ao Deus e Pai do nosso Senhor Jesus Cristo! Por causa da sua grande misericórdia, ele nos deu uma nova vida pela ressurreição de Jesus Cristo. Por isso o nosso coração está cheio de uma esperança viva.

[[v60-1-4]]

^<<v60-1-4,4>>^ Assim esperamos possuir as ricas bênçãos que Deus guarda para o seu povo. Ele as guarda no céu, onde elas não perdem o valor e não podem se estragar, nem ser destruídas.

[[v60-1-5]]

^<<v60-1-5,5>>^ Essas bênçãos são para vocês que, por meio da fé, são guardados pelo poder de Deus para a salvação que está pronta para ser revelada no fim dos tempos.

[[v60-1-6]]

^<<v60-1-6,6>>^ Alegrem-se por isso, se bem que agora é possível que vocês fiquem tristes por algum tempo, por causa dos muitos tipos de provações que vocês estão sofrendo.

[[v60-1-7]]

^<<v60-1-7,7>>^ Essas provações são para mostrar que a fé que vocês têm é verdadeira. Pois até o ouro, que pode ser destruído, é provado pelo fogo. Da mesma maneira, a fé que vocês têm, que vale muito mais do que o ouro, precisa ser provada para que continue firme. E assim vocês receberão aprovação, glória  e honra, no dia em que Jesus Cristo for revelado.

[[v60-1-8]]

^<<v60-1-8,8>>^ Vocês o amam, mesmo sem o terem visto, e creem nele, mesmo que não o estejam vendo agora. Assim vocês se alegram com uma alegria tão grande e gloriosa , que as palavras não podem descrever.

[[v60-1-9]]

^<<v60-1-9,9>>^ Vocês têm essa alegria porque estão recebendo a sua salvação, que é o resultado da fé que possuem.

[[v60-1-10]]

^<<v60-1-10,10>>^ Foi a respeito dessa salvação que os profetas  perguntaram e procuraram saber com muito cuidado. Eles profetizaram a respeito da salvação que Deus ia dar a vocês

[[v60-1-11]]

^<<v60-1-11,11>>^ e procuraram saber em que tempo e como essa salvação ia acontecer. O Espírito de Cristo, que estava neles, indicava esse tempo, ao predizer os sofrimentos que Cristo teria de suportar e a glória que viria depois.

[[v60-1-12]]

^<<v60-1-12,12>>^ Quando os profetas falaram a respeito das verdades que vocês têm ouvido agora, Deus revelou a eles que o trabalho que faziam não era para o benefício deles, mas para o bem de vocês. Os mensageiros do evangelho , que falaram pelo poder do Espírito Santo, mandado do céu, anunciaram a vocês essas verdades. Essas são coisas que até os anjos gostariam de entender.

[[v60-1-13]]

^<<v60-1-13,13>>^ Portanto, estejam prontos para agir. Continuem alertas e ponham toda a sua esperança na bênção que será dada a vocês quando Jesus Cristo for revelado.

[[v60-1-14]]

^<<v60-1-14,14>>^ Sejam obedientes a Deus e não deixem que a vida de vocês seja dominada por aqueles desejos que vocês tinham quando ainda eram ignorantes.

[[v60-1-15]]

^<<v60-1-15,15>>^ Pelo contrário, sejam santos em tudo o que fizerem, assim como Deus, que os chamou , é santo .

[[v60-1-16]]

^<<v60-1-16,16>>^ Porque as Escrituras Sagradas  dizem: "Sejam santos porque eu sou santo."

[[v60-1-17]]

^<<v60-1-17,17>>^ Quando oram a Deus, vocês o chamam de Pai, ele que julga com igualdade as pessoas, de acordo com o que cada uma tem feito. Portanto, durante o resto da vida de vocês aqui na terra tenham respeito a ele.

[[v60-1-18]]

^<<v60-1-18,18>>^ Pois vocês sabem o preço que foi pago para livrá-los da vida inútil que herdaram dos seus antepassados. Esse preço não foi uma coisa que perde o seu valor como o ouro ou a prata.

[[v60-1-19]]

^<<v60-1-19,19>>^ Vocês foram libertados pelo precioso sangue de Cristo, que era como um cordeiro sem defeito nem mancha.

[[v60-1-20]]

^<<v60-1-20,20>>^ Ele foi escolhido por Deus antes da criação do mundo e foi revelado nestes últimos tempos em benefício de vocês.

[[v60-1-21]]

^<<v60-1-21,21>>^ Por meio dele vocês creem em Deus, que o ressuscitou e lhe deu glória . Assim a fé e a esperança que vocês têm estão firmadas em Deus.

[[v60-1-22]]

^<<v60-1-22,22>>^ Agora que vocês já se purificaram  pela obediência à verdade e agora que já têm um amor sincero pelos irmãos na fé, amem uns aos outros com todas as forças e com um coração puro.

[[v60-1-23]]

^<<v60-1-23,23>>^ Pois vocês, pela viva e eterna palavra de Deus, nasceram de novo como filhos de um Pai que é imortal  e não de pais mortais.

[[v60-1-24]]

^<<v60-1-24,24>>^ Como dizem as Escrituras Sagradas: "Todos os seres humanos são como a erva do campo, e a grandeza deles é como a flor da erva. A erva seca, e a flor cai,

[[v60-1-25]]

^<<v60-1-25,25>>^ mas a palavra do Senhor dura para sempre." Esta é a palavra que o evangelho  trouxe para vocês.

'''

xref:059-tiago/059-tiago-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[Próximo Capítulo &#62;]