include::./index.adoc[]

[[v45-16-0]]
=== Romanos, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-16-1]]

^<<v45-16-1,1>>^ Eu recomendo a vocês a nossa irmã Febe, que é diaconisa  da igreja de Cencreia.

[[v45-16-2]]

^<<v45-16-2,2>>^ Recebam essa irmã em nome do Senhor, como deve fazer o povo de Deus. Deem a ela toda a ajuda que precisar, pois ela tem ajudado muita gente e a mim também.

[[v45-16-3]]

^<<v45-16-3,3>>^ Mando saudações a Priscila e ao seu marido Áquila, meus companheiros no serviço de Cristo Jesus.

[[v45-16-4]]

^<<v45-16-4,4>>^ Eles arriscaram a sua vida por mim. Sou muito agradecido a eles; e não somente eu, mas também todas as igrejas dos que não são judeus.

[[v45-16-5]]

^<<v45-16-5,5>>^ Saudações também à igreja que se reúne na casa deles. Saudações ao meu querido amigo Epêneto, que foi o primeiro a crer em Cristo na província  da Ásia.

[[v45-16-6]]

^<<v45-16-6,6>>^ Saudações a Maria, que tem trabalhado muito por vocês.

[[v45-16-7]]

^<<v45-16-7,7>>^ Saudações a Andrônico e à irmã Júnia, meus patrícios judeus, que estiveram comigo na prisão. Eles são apóstolos  bem-conhecidos e se tornaram cristãos antes de mim.

[[v45-16-8]]

^<<v45-16-8,8>>^ Saudações a Amplíato, meu querido irmão no Senhor.

[[v45-16-9]]

^<<v45-16-9,9>>^ E também a Urbano, nosso companheiro de trabalho no serviço de Cristo, e ao meu querido amigo Estáquis.

[[v45-16-10]]

^<<v45-16-10,10>>^ Saudações a Apeles, um irmão que tem dado muitas provas da sua fé em Cristo. Saudações ao pessoal da família de Aristóbulo.

[[v45-16-11]]

^<<v45-16-11,11>>^ Saudações a Herodião, meu patrício judeu, e aos irmãos no Senhor da família de Narciso.

[[v45-16-12]]

^<<v45-16-12,12>>^ Saudações a Trifena e a Trifosa, irmãs que trabalham no serviço do Senhor, e à minha querida amiga Pérside, que também tem trabalhado muito para o Senhor.

[[v45-16-13]]

^<<v45-16-13,13>>^ Mando saudações a Rufo, trabalhador que tem se destacado no serviço do Senhor, e à mãe dele, que sempre me tratou como filho.

[[v45-16-14]]

^<<v45-16-14,14>>^ Saudações aos irmãos Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e a todos os irmãos que estão com eles.

[[v45-16-15]]

^<<v45-16-15,15>>^ Saudações a Filólogo e a Júlia; a Nereu e à sua irmã; ao irmão Olimpas e a todas as pessoas do povo de Deus que estão com eles.

[[v45-16-16]]

^<<v45-16-16,16>>^ Cumprimentem uns aos outros com um beijo de irmão. Todas as igrejas de Cristo mandam saudações a vocês.

[[v45-16-17]]

^<<v45-16-17,17>>^ Meus irmãos, peço que tomem cuidado com as pessoas que provocam divisões, que atrapalham os outros na fé e que vão contra o ensinamento que vocês receberam. Afastem-se dessas pessoas

[[v45-16-18]]

^<<v45-16-18,18>>^ porque os que fazem essas coisas não estão servindo a Cristo, o nosso Senhor, mas a si mesmos. Por meio de conversa macia e com bajulação, eles enganam o coração das pessoas simples.

[[v45-16-19]]

^<<v45-16-19,19>>^ Todos sabem como vocês têm sido fiéis ao evangelho , e por isso eu me alegro por causa de vocês. Quero que sejam sábios a respeito do que é bom e não tenham nada a ver com o que é mau.

[[v45-16-20]]

^<<v45-16-20,20>>^ E Deus, a nossa fonte de paz, logo esmagará Satanás debaixo dos pés de vocês. Que a graça  do nosso Senhor Jesus esteja com vocês!

[[v45-16-21]]

^<<v45-16-21,21>>^ Timóteo, meu companheiro de trabalho, manda saudações a vocês. Lúcio, Jasão e Sosípatro, meus patrícios judeus, também mandam saudações.

[[v45-16-22]]

^<<v45-16-22,22>>^ Eu, Tércio, que escrevi esta carta que Paulo ditou para mim, mando saudações a vocês.

[[v45-16-23]]

^<<v45-16-23,23>>^ O meu hospedeiro Gaio, em casa de quem a igreja daqui se reúne, manda saudações a vocês. Erasto, o tesoureiro da cidade, e o nosso irmão Quarto também mandam saudações.

[[v45-16-24]]

^<<v45-16-24,24>>^ [Que a graça do nosso Senhor Jesus Cristo esteja com todos vocês. Amém .]

[[v45-16-25]]

^<<v45-16-25,25>>^ Louvemos a Deus! Pois ele pode conservar vocês firmes na fé, de acordo com o evangelho  que eu anuncio, isto é, a mensagem a respeito de Jesus Cristo. E de acordo também com a verdade secreta que nunca foi revelada no passado.

[[v45-16-26]]

^<<v45-16-26,26>>^ Porém essa verdade foi revelada agora por meio daquilo que os profetas  escreveram. E, por ordem do Deus eterno, ela se tornou conhecida em todas as nações, para que todos creiam e obedeçam.

[[v45-16-27]]

^<<v45-16-27,27>>^ Ao Deus único e sábio seja dada glória  para sempre, por meio de Jesus Cristo! Amém !

'''

xref:045-romanos/045-romanos-015.adoc#v45-15-0[&#60; Capítulo Anterior] | <<v45-16-0,Topo>> | xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[Próximo Capítulo &#62;]