include::./index.adoc[]

[[v45-10-0]]
=== Romanos, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-10-1]]

^<<v45-10-1,1>>^ Meus irmãos, desejo de todo o coração que o meu próprio povo seja salvo. E peço a Deus em favor deles

[[v45-10-2]]

^<<v45-10-2,2>>^ porque eu sou testemunha de que eles são muito dedicados a Deus. Mas a dedicação deles não está baseada no verdadeiro conhecimento,

[[v45-10-3]]

^<<v45-10-3,3>>^ pois eles não conhecem a maneira como Deus aceita as pessoas e assim têm procurado conseguir isso da sua própria maneira. Eles rejeitaram o modo de Deus aceitar as pessoas.

[[v45-10-4]]

^<<v45-10-4,4>>^ Porque, com Cristo, a lei  chegou ao fim, e assim os que creem é que são aceitos por Deus.

[[v45-10-5]]

^<<v45-10-5,5>>^ Pois o que Moisés escreveu a respeito de as pessoas serem aceitas por Deus pela obediência à lei  foi isto: "Viverá aquele que fizer o que a lei manda."

[[v45-10-6]]

^<<v45-10-6,6>>^ Porém, quanto a ser aceito por Deus por meio da fé, Moisés diz o seguinte: "Não fique pensando assim: quem vai subir até o céu?", isto é, para trazer Cristo do céu.

[[v45-10-7]]

^<<v45-10-7,7>>^ "Nem pergunte: quem descerá ao mundo lá de baixo?", isto é, para fazer com que Cristo suba do mundo dos mortos .

[[v45-10-8]]

^<<v45-10-8,8>>^ O que Moisés diz é isto: "A mensagem de Deus está perto de você, nos seus lábios e no seu coração" — isto é, a mensagem de fé que anunciamos.

[[v45-10-9]]

^<<v45-10-9,9>>^ Se você disser com a sua boca: "Jesus é Senhor" e no seu coração crer que Deus ressuscitou Jesus, você será salvo.

[[v45-10-10]]

^<<v45-10-10,10>>^ Porque nós cremos com o coração e somos aceitos por Deus; falamos com a boca e assim somos salvos.

[[v45-10-11]]

^<<v45-10-11,11>>^ Porque as Escrituras Sagradas  dizem: "Quem crer nele não ficará desiludido."

[[v45-10-12]]

^<<v45-10-12,12>>^ Isso vale para todos, pois não existe nenhuma diferença entre judeus e não judeus. Deus é o mesmo Senhor de todos e abençoa generosamente todos os que pedem a sua ajuda.

[[v45-10-13]]

^<<v45-10-13,13>>^ Como dizem as Escrituras Sagradas: "Todos os que pedirem a ajuda do Senhor serão salvos."

[[v45-10-14]]

^<<v45-10-14,14>>^ Mas como é que as pessoas irão pedir, se não crerem nele? E como poderão crer, se não ouvirem a mensagem? E como poderão ouvir, se a mensagem não for anunciada?

[[v45-10-15]]

^<<v45-10-15,15>>^ E como é que a mensagem será anunciada, se não forem enviados mensageiros? As Escrituras Sagradas dizem: "Como é bonito ver os mensageiros trazendo boas notícias!"

[[v45-10-16]]

^<<v45-10-16,16>>^ Mas nem todos aceitam a boa notícia do evangelho . Foi Isaías quem disse: "Senhor, quem creu na nossa mensagem?"

[[v45-10-17]]

^<<v45-10-17,17>>^ Portanto, a fé vem por ouvir a mensagem, e a mensagem vem por meio da pregação a respeito de Cristo.

[[v45-10-18]]

^<<v45-10-18,18>>^ Mas eu pergunto: será que eles não ouviram a mensagem? É claro que ouviram! Como dizem as Escrituras: "A voz deles se espalhou pelo mundo inteiro; as suas palavras alcançaram a terra toda."

[[v45-10-19]]

^<<v45-10-19,19>>^ Eu pergunto ainda: será que o povo de Israel não soube disso? Moisés foi o primeiro a dar uma resposta. Ele disse: "Eu farei com que vocês fiquem com ciúmes de um povo que não é uma nação; farei com que fiquem com raiva de uma nação de gente sem juízo."

[[v45-10-20]]

^<<v45-10-20,20>>^ E Isaías foi mais corajoso ao anunciar o que Deus disse: "Eu fui achado por aqueles que não me procuravam e apareci aos que não perguntavam por mim."

[[v45-10-21]]

^<<v45-10-21,21>>^ Mas, a respeito de Israel, Deus disse: "O dia inteiro eu abri os braços, pronto para receber um povo desobediente e rebelde."

'''

xref:045-romanos/045-romanos-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romanos/045-romanos-011.adoc#v45-11-0[Próximo Capítulo &#62;]