include::./index.adoc[]

[[v45-8-0]]
=== Romanos, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-8-1]]

^<<v45-8-1,1>>^ Agora já não existe nenhuma condenação para as pessoas que estão unidas com Cristo Jesus.

[[v45-8-2]]

^<<v45-8-2,2>>^ Pois a lei do Espírito de Deus, que nos trouxe vida por estarmos unidos com Cristo Jesus, livrou você da lei do pecado e da morte.

[[v45-8-3]]

^<<v45-8-3,3>>^ Deus fez o que a lei  não pôde fazer porque a natureza humana era fraca. Deus condenou o pecado na natureza humana , enviando o seu próprio Filho, que veio na forma da nossa natureza pecaminosa a fim de acabar com o pecado.

[[v45-8-4]]

^<<v45-8-4,4>>^ Deus fez isso para que as ordens justas da lei pudessem ser completamente cumpridas por nós, que vivemos de acordo com o Espírito de Deus e não de acordo com a natureza humana.

[[v45-8-5]]

^<<v45-8-5,5>>^ Porque as pessoas que vivem de acordo com a natureza humana têm a sua mente controlada por essa mesma natureza. Mas as que vivem de acordo com o Espírito de Deus têm a sua mente controlada pelo Espírito.

[[v45-8-6]]

^<<v45-8-6,6>>^ As pessoas que têm a mente controlada pela natureza humana acabarão morrendo espiritualmente; mas as que têm a mente controlada pelo Espírito de Deus terão a vida eterna e a paz.

[[v45-8-7]]

^<<v45-8-7,7>>^ Por isso as pessoas que têm a mente controlada pela natureza humana se tornam inimigas de Deus, pois não obedecem à lei de Deus e, de fato, não podem obedecer a ela.

[[v45-8-8]]

^<<v45-8-8,8>>^ As pessoas que vivem de acordo com a sua natureza humana não podem agradar a Deus.

[[v45-8-9]]

^<<v45-8-9,9>>^ Vocês, porém, não vivem como manda a natureza humana, mas como o Espírito de Deus quer, se é que o Espírito de Deus vive realmente em vocês. Quem não tem o Espírito de Cristo não pertence a ele.

[[v45-8-10]]

^<<v45-8-10,10>>^ Mas, se Cristo vive em vocês, então, embora o corpo de vocês vá morrer por causa do pecado, o Espírito de Deus é vida para vocês porque vocês foram aceitos por Deus.

[[v45-8-11]]

^<<v45-8-11,11>>^ Se em vocês vive o Espírito daquele que ressuscitou Jesus, então aquele que ressuscitou Jesus Cristo dará também vida ao corpo mortal de vocês, por meio do seu Espírito, que vive em vocês.

[[v45-8-12]]

^<<v45-8-12,12>>^ Portanto, meus irmãos, nós temos uma obrigação, que é a de não vivermos de acordo com a nossa natureza humana.

[[v45-8-13]]

^<<v45-8-13,13>>^ Porque, se vocês viverem de acordo com a natureza humana, vocês morrerão espiritualmente; mas, se pelo Espírito de Deus vocês matarem as suas ações pecaminosas, vocês viverão espiritualmente.

[[v45-8-14]]

^<<v45-8-14,14>>^ Pois aqueles que são guiados pelo Espírito de Deus são filhos de Deus.

[[v45-8-15]]

^<<v45-8-15,15>>^ Porque o Espírito que vocês receberam de Deus não torna vocês escravos e não faz com que tenham medo. Pelo contrário, o Espírito torna vocês filhos de Deus; e pelo poder do Espírito dizemos com fervor a Deus: "Pai, meu Pai!"

[[v45-8-16]]

^<<v45-8-16,16>>^ O Espírito de Deus se une com o nosso espírito para afirmar que somos filhos de Deus.

[[v45-8-17]]

^<<v45-8-17,17>>^ Nós somos seus filhos, e por isso receberemos as bênçãos que ele guarda para o seu povo, e também receberemos com Cristo aquilo que Deus tem guardado para ele. Porque, se tomamos parte nos sofrimentos de Cristo, também tomaremos parte na sua glória .

[[v45-8-18]]

^<<v45-8-18,18>>^ Eu penso que o que sofremos durante a nossa vida não pode ser comparado, de modo nenhum, com a glória  que nos será revelada no futuro.

[[v45-8-19]]

^<<v45-8-19,19>>^ O Universo  todo espera com muita impaciência o momento em que Deus vai revelar o que os seus filhos realmente são.

[[v45-8-20]]

^<<v45-8-20,20>>^ Pois o Universo se tornou inútil, não pela sua própria vontade, mas porque Deus quis que fosse assim. Porém existe esta esperança:

[[v45-8-21]]

^<<v45-8-21,21>>^ Um dia o próprio Universo ficará livre do poder destruidor que o mantém escravo e tomará parte na gloriosa  liberdade dos filhos de Deus.

[[v45-8-22]]

^<<v45-8-22,22>>^ Pois sabemos que até agora o Universo todo geme e sofre como uma mulher que está em trabalho de parto.

[[v45-8-23]]

^<<v45-8-23,23>>^ E não somente o Universo, mas nós, que temos o Espírito Santo como o primeiro presente que recebemos de Deus, nós também gememos dentro de nós mesmos enquanto esperamos que Deus faça com que sejamos seus filhos e nos liberte completamente.

[[v45-8-24]]

^<<v45-8-24,24>>^ Pois foi por meio da esperança que fomos salvos. Mas, se já estamos vendo aquilo que esperamos, então isso não é mais uma esperança. Pois quem é que fica esperando por alguma coisa que está vendo?

[[v45-8-25]]

^<<v45-8-25,25>>^ Porém, se estamos esperando alguma coisa que ainda não podemos ver, então esperamos com paciência.

[[v45-8-26]]

^<<v45-8-26,26>>^ Assim também o Espírito de Deus vem nos ajudar na nossa fraqueza. Pois não sabemos como devemos orar, mas o Espírito de Deus, com gemidos que não podem ser explicados por palavras, pede a Deus em nosso favor.

[[v45-8-27]]

^<<v45-8-27,27>>^ E Deus, que vê o que está dentro do coração, sabe qual é o pensamento do Espírito. Porque o Espírito pede em favor do povo de Deus e pede de acordo com a vontade de Deus.

[[v45-8-28]]

^<<v45-8-28,28>>^ Pois sabemos que todas as coisas trabalham juntas para o bem daqueles que amam a Deus, daqueles a quem ele chamou  de acordo com o seu plano.

[[v45-8-29]]

^<<v45-8-29,29>>^ Porque aqueles que já tinham sido escolhidos por Deus ele também separou a fim de se tornarem parecidos com o seu Filho. Ele fez isso para que o Filho fosse o primeiro entre muitos irmãos.

[[v45-8-30]]

^<<v45-8-30,30>>^ Assim Deus chamou os que havia separado. Não somente os chamou, mas também os aceitou; e não somente os aceitou, mas também repartiu a sua glória com eles.

[[v45-8-31]]

^<<v45-8-31,31>>^ Diante de tudo isso, o que mais podemos dizer? Se Deus está do nosso lado, quem poderá nos vencer? Ninguém!

[[v45-8-32]]

^<<v45-8-32,32>>^ Porque ele nem mesmo deixou de entregar o próprio Filho, mas o ofereceu por todos nós! Se ele nos deu o seu Filho, será que não nos dará também todas as coisas?

[[v45-8-33]]

^<<v45-8-33,33>>^ Quem acusará aqueles que Deus escolheu? Ninguém! Porque o próprio Deus declara que eles não são culpados.

[[v45-8-34]]

^<<v45-8-34,34>>^ Será que alguém poderá condená-los? Ninguém! Pois foi Cristo Jesus quem morreu, ou melhor, quem foi ressuscitado e está à direita de Deus. E ele pede a Deus em favor de nós.

[[v45-8-35]]

^<<v45-8-35,35>>^ Então quem pode nos separar do amor de Cristo? Serão os sofrimentos, as dificuldades, a perseguição, a fome, a pobreza, o perigo ou a morte?

[[v45-8-36]]

^<<v45-8-36,36>>^ Como dizem as Escrituras Sagradas : "Por causa de ti estamos em perigo de morte o dia inteiro; somos tratados como ovelhas que vão para o matadouro."

[[v45-8-37]]

^<<v45-8-37,37>>^ Em todas essas situações temos a vitória completa por meio daquele que nos amou.

[[v45-8-38]]

^<<v45-8-38,38>>^ Pois eu tenho a certeza de que nada pode nos separar do amor de Deus: nem a morte, nem a vida; nem os anjos, nem outras autoridades ou poderes celestiais ; nem o presente, nem o futuro;

[[v45-8-39]]

^<<v45-8-39,39>>^ nem o mundo lá de cima, nem o mundo lá de baixo. Em todo o Universo  não há nada que possa nos separar do amor de Deus, que é nosso por meio de Cristo Jesus, o nosso Senhor.

'''

xref:045-romanos/045-romanos-007.adoc#v45-7-0[&#60; Capítulo Anterior] | <<v45-8-0,Topo>> | xref:045-romanos/045-romanos-009.adoc#v45-9-0[Próximo Capítulo &#62;]