include::./index.adoc[]

[[v45-3-0]]
=== Romanos, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-3-1]]

^<<v45-3-1,1>>^ Então qual é a vantagem de ser judeu? Será que ser circuncidado  tem algum valor?

[[v45-3-2]]

^<<v45-3-2,2>>^ Tem, sim, e de muitas maneiras! E a primeira vantagem é que Deus entregou a sua mensagem aos cuidados dos judeus.

[[v45-3-3]]

^<<v45-3-3,3>>^ Mas, se alguns não foram fiéis, será que por isso Deus vai ser infiel?

[[v45-3-4]]

^<<v45-3-4,4>>^ De modo nenhum! Que Deus continue a ser verdadeiro, mesmo que todas as pessoas sejam mentirosas. Como dizem as Escrituras Sagradas  a respeito dele: "Que fique provado que tu tens razão quando falas e que sejas vencedor quando fores julgado."

[[v45-3-5]]

^<<v45-3-5,5>>^ Mas, se as injustiças que cometemos servem para mostrar que Deus age com justiça, o que é que podemos dizer? Que Deus é injusto quando nos castiga? (Eu falo aqui como as pessoas costumam falar.)

[[v45-3-6]]

^<<v45-3-6,6>>^ É claro que não! Se Deus não fosse justo, como poderia julgar o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ Mas digamos que a minha mentira faz com que a verdade de Deus fique mais clara, aumentando assim a glória  dele. Nesse caso, por que é que devo ainda ser condenado como pecador?

[[v45-3-8]]

^<<v45-3-8,8>>^ Então por que não dizer: "Façamos o mal para que desse mal venha o bem"? Na verdade alguns têm me caluniado, dizendo que eu afirmo isso. Porém eles serão condenados como merecem.

[[v45-3-9]]

^<<v45-3-9,9>>^ Então será que nós, os judeus, estamos em melhor situação do que os não judeus? De modo nenhum! Já mostrei que todos, judeus e não judeus, estão debaixo do poder do pecado.

[[v45-3-10]]

^<<v45-3-10,10>>^ Como dizem as Escrituras Sagradas: "Não há uma só pessoa que faça o que é certo;

[[v45-3-11]]

^<<v45-3-11,11>>^ não há ninguém que tenha juízo; não há ninguém que adore a Deus.

[[v45-3-12]]

^<<v45-3-12,12>>^ Todos se desviaram do caminho certo, todos se perderam. Não há mais ninguém que faça o bem, não há ninguém mesmo.

[[v45-3-13]]

^<<v45-3-13,13>>^ Todos mentem e enganam sem parar. Da língua deles saem mentiras perversas, e dos seus lábios saem palavras de morte, como se fossem veneno de cobra.

[[v45-3-14]]

^<<v45-3-14,14>>^ A boca deles está cheia de terríveis maldições.

[[v45-3-15]]

^<<v45-3-15,15>>^ Eles se apressam para matar.

[[v45-3-16]]

^<<v45-3-16,16>>^ Por onde passam, deixam a destruição e a desgraça.

[[v45-3-17]]

^<<v45-3-17,17>>^ Não conhecem o caminho da paz

[[v45-3-18]]

^<<v45-3-18,18>>^ e não aprenderam a temer a Deus ."

[[v45-3-19]]

^<<v45-3-19,19>>^ Nós sabemos que tudo o que a lei  diz é dito para os que vivem debaixo da lei. Isso a fim de que todos parem de se justificar e a fim de que todas as pessoas do mundo fiquem debaixo do julgamento de Deus.

[[v45-3-20]]

^<<v45-3-20,20>>^ Pois ninguém é aceito por Deus por fazer o que a lei manda, porque a lei faz com que as pessoas saibam que são pecadoras.

[[v45-3-21]]

^<<v45-3-21,21>>^ Mas agora Deus já mostrou que o meio pelo qual ele aceita as pessoas não tem nada a ver com lei . A Lei de Moisés e os Profetas  dão testemunho do seguinte:

[[v45-3-22]]

^<<v45-3-22,22>>^ Deus aceita as pessoas por meio da fé que elas têm em Jesus Cristo. É assim que ele trata todos os que creem, pois não existe nenhuma diferença entre as pessoas.

[[v45-3-23]]

^<<v45-3-23,23>>^ Todos pecaram e estão afastados da presença gloriosa  de Deus.

[[v45-3-24]]

^<<v45-3-24,24>>^ Mas, pela sua graça  e sem exigir nada, Deus aceita todos por meio de Cristo Jesus, que os salva.

[[v45-3-25]]

^<<v45-3-25,25>>^ Deus ofereceu Cristo como sacrifício  para que, pela sua morte na cruz, Cristo se tornasse o meio de as pessoas receberem o perdão dos seus pecados, pela fé nele. Deus quis mostrar com isso que ele é justo. No passado ele foi paciente e não castigou as pessoas por causa dos seus pecados; mas agora, pelo sacrifício de Cristo, Deus mostra que é justo. Assim ele é justo e aceita os que creem em Jesus.

[[v45-3-26]]

^<<v45-3-26,26>>^ Deus ofereceu Cristo como sacrifício  para que, pela sua morte na cruz, Cristo se tornasse o meio de as pessoas receberem o perdão dos seus pecados, pela fé nele. Deus quis mostrar com isso que ele é justo. No passado ele foi paciente e não castigou as pessoas por causa dos seus pecados; mas agora, pelo sacrifício de Cristo, Deus mostra que é justo. Assim ele é justo e aceita os que creem em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Será que temos motivo para ficarmos orgulhosos? De modo nenhum! E por que não? Será que é porque obedecemos à lei? Não; não é. É porque cremos em Cristo.

[[v45-3-28]]

^<<v45-3-28,28>>^ Assim percebemos que a pessoa é aceita por Deus pela fé e não por fazer o que a lei manda.

[[v45-3-29]]

^<<v45-3-29,29>>^ Ou será que Deus é somente Deus dos judeus? Será que não é também Deus dos não judeus? Claro que é!

[[v45-3-30]]

^<<v45-3-30,30>>^ Deus é um só e aceitará os judeus na base da sua fé e também aceitará os não judeus por meio da fé que eles têm.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]