include::./index.adoc[]

[[v45-6-0]]
=== Romanos, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-6-1]]

^<<v45-6-1,1>>^ Portanto, o que vamos dizer? Será que devemos continuar vivendo no pecado para que a graça  de Deus aumente ainda mais?

[[v45-6-2]]

^<<v45-6-2,2>>^ É claro que não! Nós já morremos para o pecado; então como podemos continuar vivendo nele?

[[v45-6-3]]

^<<v45-6-3,3>>^ Com certeza vocês sabem que, quando fomos batizados para ficarmos unidos com Cristo Jesus, fomos batizados para ficarmos unidos também com a sua morte.

[[v45-6-4]]

^<<v45-6-4,4>>^ Assim, quando fomos batizados, fomos sepultados com ele por termos morrido junto com ele. E isso para que, assim como Cristo foi ressuscitado pelo poder glorioso  do Pai, assim também nós vivamos uma vida nova.

[[v45-6-5]]

^<<v45-6-5,5>>^ Pois, se fomos unidos com ele por uma morte igual à dele, assim também seremos unidos com ele por uma ressurreição igual à dele.

[[v45-6-6]]

^<<v45-6-6,6>>^ Pois sabemos que a nossa velha natureza pecadora já foi morta com Cristo na cruz a fim de que o nosso eu pecador fosse morto, e assim não sejamos mais escravos do pecado.

[[v45-6-7]]

^<<v45-6-7,7>>^ Pois quem morre fica livre do poder do pecado.

[[v45-6-8]]

^<<v45-6-8,8>>^ Se já morremos com Cristo, cremos que também viveremos com ele.

[[v45-6-9]]

^<<v45-6-9,9>>^ Sabemos que Cristo foi ressuscitado e nunca mais morrerá, pois a morte não tem mais poder sobre ele.

[[v45-6-10]]

^<<v45-6-10,10>>^ A sua morte foi uma morte para o pecado e valeu de uma vez por todas. E a vida que ele vive agora é uma vida para Deus.

[[v45-6-11]]

^<<v45-6-11,11>>^ Assim também vocês devem se considerar mortos para o pecado; mas, por estarem unidos com Cristo Jesus, devem se considerar vivos para Deus.

[[v45-6-12]]

^<<v45-6-12,12>>^ Portanto, não deixem que o pecado domine o corpo mortal de vocês e faça com que vocês obedeçam aos desejos pecaminosos da natureza humana.

[[v45-6-13]]

^<<v45-6-13,13>>^ E também não entreguem nenhuma parte do corpo de vocês ao pecado, para que ele a use a fim de fazer o que é mau. Pelo contrário, como pessoas que foram trazidas da morte para a vida, entreguem-se completamente a Deus, para que ele use vocês a fim de fazerem o que é direito.

[[v45-6-14]]

^<<v45-6-14,14>>^ O pecado não dominará vocês, pois vocês não são mais controlados pela lei , mas pela graça de Deus.

[[v45-6-15]]

^<<v45-6-15,15>>^ O que é que isso quer dizer? Vamos continuar pecando porque não somos mais controlados pela lei , mas pela graça  de Deus? É claro que não!

[[v45-6-16]]

^<<v45-6-16,16>>^ Pois vocês sabem muito bem que, quando se entregam a alguma pessoa para serem escravos dela, são, de fato, escravos dessa pessoa a quem vocês obedecem. Assim sendo, vocês podem obedecer ao pecado, que produz a morte, ou podem obedecer a Deus e ser aceitos por ele.

[[v45-6-17]]

^<<v45-6-17,17>>^ Mas damos graças a Deus porque vocês, que antes eram escravos do pecado, agora já obedecem de todo o coração às verdades que estão nos ensinamentos que receberam.

[[v45-6-18]]

^<<v45-6-18,18>>^ Vocês foram libertados do pecado e se tornaram escravos de Deus para fazer o que é direito.

[[v45-6-19]]

^<<v45-6-19,19>>^ Falo com palavras bem simples porque vocês ainda são fracos. No passado vocês se entregaram inteiramente como escravos da imoralidade e da maldade para servir o mal. Entreguem-se agora inteiramente como escravos daquilo que é direito para viver uma vida dedicada a Deus.

[[v45-6-20]]

^<<v45-6-20,20>>^ Quando eram escravos do pecado, vocês não faziam o que é direito.

[[v45-6-21]]

^<<v45-6-21,21>>^ Porém o que é que vocês receberam de bom quando faziam aquelas coisas de que agora têm vergonha? Pois o resultado de tudo aquilo é a morte.

[[v45-6-22]]

^<<v45-6-22,22>>^ Mas agora vocês foram libertados do pecado e são escravos de Deus. Com isso vocês ganham uma vida completamente dedicada a ele, e o resultado é que vocês terão a vida eterna.

[[v45-6-23]]

^<<v45-6-23,23>>^ Pois o salário do pecado é a morte, mas o presente gratuito de Deus é a vida eterna, que temos em união com Cristo Jesus, o nosso Senhor.

'''

xref:045-romanos/045-romanos-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romanos/045-romanos-007.adoc#v45-7-0[Próximo Capítulo &#62;]