include::./index.adoc[]

[[v45-14-0]]
=== Romanos, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-14-1]]

^<<v45-14-1,1>>^ Aceitem entre vocês quem é fraco na fé sem criticar as opiniões dessa pessoa.

[[v45-14-2]]

^<<v45-14-2,2>>^ Por exemplo, algumas pessoas creem que podem comer de tudo, mas quem é fraco na fé come somente verduras e legumes.

[[v45-14-3]]

^<<v45-14-3,3>>^ Quem come de tudo não deve desprezar quem não faz isso, e quem só come verduras e legumes não deve condenar quem come de tudo, pois Deus o aceitou.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem é você para julgar o escravo de alguém? Se ele vai vencer ou fracassar, isso é da conta do dono dele. E ele vai vencer porque o Senhor pode fazê-lo vencer.

[[v45-14-5]]

^<<v45-14-5,5>>^ Algumas pessoas pensam que certos dias são mais importantes do que outros, enquanto que outras pessoas pensam que todos os dias são iguais. Cada um deve estar bem firme nas suas opiniões.

[[v45-14-6]]

^<<v45-14-6,6>>^ Quem dá mais valor a certo dia faz isso para honrar o Senhor. E também quem come de tudo faz isso para honrar o Senhor, pois agradece a Deus o alimento. E quem evita comer certas coisas faz isso para honrar o Senhor e dá graças a Deus.

[[v45-14-7]]

^<<v45-14-7,7>>^ Porque nenhum de nós vive para si mesmo e nenhum de nós morre para si mesmo.

[[v45-14-8]]

^<<v45-14-8,8>>^ Se vivemos, é para o Senhor que vivemos; e, se morremos, também é para o Senhor que morremos. Assim, tanto se vivemos como se morremos, somos do Senhor.

[[v45-14-9]]

^<<v45-14-9,9>>^ Pois Cristo morreu e viveu de novo para ser o senhor tanto dos mortos como dos vivos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Portanto, por que é que você, que só come verduras e legumes, condena o seu irmão? E, você, que come de tudo, por que despreza o seu irmão? Pois todos nós estaremos diante de Deus para sermos julgados por ele.

[[v45-14-11]]

^<<v45-14-11,11>>^ É isto o que as Escrituras Sagradas  dizem: "Juro pela minha vida, diz o Senhor, que todos se ajoelharão diante de mim e todos afirmarão que eu sou Deus."

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, cada um de nós prestará contas de si mesmo a Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Por isso paremos de criticar uns aos outros. Pelo contrário, cada um de vocês resolva não fazer nada que leve o seu irmão a tropeçar ou cair em pecado.

[[v45-14-14]]

^<<v45-14-14,14>>^ Por estar unido com o Senhor Jesus, eu estou convencido de que nada é impuro  em si mesmo. Mas, se alguém pensa que alguma coisa é impura, então ela fica impura para ele.

[[v45-14-15]]

^<<v45-14-15,15>>^ Se você faz com que um irmão fique triste por causa do que você come, então você não está agindo com amor. Não deixe que a pessoa por quem Cristo morreu se perca por causa da comida que você come.

[[v45-14-16]]

^<<v45-14-16,16>>^ Não deem motivo para os outros falarem mal daquilo que vocês acham bom.

[[v45-14-17]]

^<<v45-14-17,17>>^ Pois o Reino de Deus  não é uma questão de comida ou de bebida, mas de viver corretamente, em paz e com a alegria que o Espírito Santo dá.

[[v45-14-18]]

^<<v45-14-18,18>>^ E quem serve a Cristo dessa maneira agrada a Deus e é aprovado por todos.

[[v45-14-19]]

^<<v45-14-19,19>>^ Por isso procuremos sempre as coisas que trazem a paz e que nos ajudam a fortalecer uns aos outros na fé.

[[v45-14-20]]

^<<v45-14-20,20>>^ Por uma questão de comida, não destrua o que Deus fez. Todos os alimentos podem ser comidos, mas é errado comer alguma coisa quando isso faz com que outra pessoa caia em pecado.

[[v45-14-21]]

^<<v45-14-21,21>>^ O que está certo é não comer carne, não beber vinho, nem fazer qualquer outra coisa que leve um irmão a cair em pecado.

[[v45-14-22]]

^<<v45-14-22,22>>^ Mas guarde entre você mesmo e Deus o que você crê a respeito desse assunto. Feliz a pessoa que não é condenada pela consciência quando faz o que acha que deve fazer!

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas quem tem dúvidas a respeito do que come é condenado por Deus quando come, pois aquilo que ele faz não se baseia na fé. E o que não se baseia na fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]