include::./index.adoc[]

[[v45-7-0]]
=== Romanos, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-7-1]]

^<<v45-7-1,1>>^ Meus irmãos, vocês todos podem compreender muito bem o que vou dizer. Vocês conhecem as leis  e sabem que elas só têm poder sobre uma pessoa enquanto essa pessoa está viva.

[[v45-7-2]]

^<<v45-7-2,2>>^ Por exemplo, a mulher casada está ligada pela lei ao marido enquanto ele estiver vivo; mas, se ele morrer, ela estará livre da lei que a liga ao marido.

[[v45-7-3]]

^<<v45-7-3,3>>^ De modo que, se ela viver com outro homem enquanto o marido estiver vivo, ela será chamada de adúltera. Mas, se o marido morrer, ela estará legalmente livre e não cometerá adultério se casar com outro homem.

[[v45-7-4]]

^<<v45-7-4,4>>^ O mesmo acontece com vocês, meus irmãos. Do ponto de vista da lei, vocês também já morreram, pois são parte do corpo de Cristo. E agora pertencem a ele, que foi ressuscitado para que nós possamos viver uma vida útil no serviço de Deus.

[[v45-7-5]]

^<<v45-7-5,5>>^ Pois, quando vivíamos de acordo com a nossa natureza humana, os maus desejos despertados pela lei agiam em todo o nosso ser e nos levavam para a morte.

[[v45-7-6]]

^<<v45-7-6,6>>^ Porém agora estamos livres da lei porque já morremos para aquilo que nos mantinha prisioneiros. Por isso somos livres para servir a Deus não da maneira antiga, obedecendo à lei escrita, mas da maneira nova, obedecendo ao Espírito de Deus.

[[v45-7-7]]

^<<v45-7-7,7>>^ O que vamos dizer então? Que a própria lei  é pecado? É claro que não! Mas foi a lei que me fez saber o que é pecado. Pois eu não saberia o que é a cobiça se a lei não tivesse dito: "Não cobice."

[[v45-7-8]]

^<<v45-7-8,8>>^ Porém o pecado se aproveitou dessa lei para despertar em mim todo tipo de cobiça. Porque, se não existe a lei, o pecado é uma coisa morta.

[[v45-7-9]]

^<<v45-7-9,9>>^ Pois houve um tempo em que eu não conhecia a lei e estava vivo. Mas, quando fiquei conhecendo o mandamento, o pecado começou a viver,

[[v45-7-10]]

^<<v45-7-10,10>>^ e eu morri. E o próprio mandamento que me devia trazer a vida me trouxe a morte.

[[v45-7-11]]

^<<v45-7-11,11>>^ Porque o pecado, aproveitando a oportunidade dada pelo mandamento, me enganou e, por meio do mandamento, me matou.

[[v45-7-12]]

^<<v45-7-12,12>>^ Assim a lei vem de Deus; e o mandamento também vem de Deus, diz o que é certo e é bom.

[[v45-7-13]]

^<<v45-7-13,13>>^ Então será que o que é bom me levou à morte? É claro que não! Foi o pecado que fez isso. Pois o pecado, usando o que é bom, me trouxe a morte para que ficasse bem claro aquilo que o pecado realmente é. E assim, por meio do mandamento, o pecado se mostrou mais terrível ainda.

[[v45-7-14]]

^<<v45-7-14,14>>^ Sabemos que a lei  é divina; mas eu sou humano e fraco e fui vendido ao pecado para ser seu escravo.

[[v45-7-15]]

^<<v45-7-15,15>>^ Eu não entendo o que faço, pois não faço o que gostaria de fazer. Pelo contrário, faço justamente aquilo que odeio.

[[v45-7-16]]

^<<v45-7-16,16>>^ Se faço o que não quero, isso prova que reconheço que a lei diz o que é certo.

[[v45-7-17]]

^<<v45-7-17,17>>^ E isso mostra que, de fato, já não sou eu quem faz isso, mas o pecado que vive em mim é que faz.

[[v45-7-18]]

^<<v45-7-18,18>>^ Pois eu sei que aquilo que é bom não vive em mim, isto é, na minha natureza humana. Porque, mesmo tendo dentro de mim a vontade de fazer o bem, eu não consigo fazê-lo.

[[v45-7-19]]

^<<v45-7-19,19>>^ Pois não faço o bem que quero, mas justamente o mal que não quero fazer é que eu faço.

[[v45-7-20]]

^<<v45-7-20,20>>^ Mas, se faço o que não quero, já não sou eu quem faz isso, mas o pecado que vive em mim é que faz.

[[v45-7-21]]

^<<v45-7-21,21>>^ Assim eu sei que o que acontece comigo é isto: quando quero fazer o que é bom, só consigo fazer o que é mau.

[[v45-7-22]]

^<<v45-7-22,22>>^ Dentro de mim eu sei que gosto da lei de Deus.

[[v45-7-23]]

^<<v45-7-23,23>>^ Mas vejo uma lei diferente agindo naquilo que faço, uma lei que luta contra aquela que a minha mente aprova. Ela me torna prisioneiro da lei do pecado que age no meu corpo.

[[v45-7-24]]

^<<v45-7-24,24>>^ Como sou infeliz! Quem me livrará deste corpo que me leva para a morte?

[[v45-7-25]]

^<<v45-7-25,25>>^ Que Deus seja louvado, pois ele fará isso por meio do nosso Senhor Jesus Cristo! Portanto, esta é a minha situação: no meu pensamento eu sirvo à lei de Deus, mas na prática sirvo à lei do pecado.

'''

xref:045-romanos/045-romanos-006.adoc#v45-6-0[&#60; Capítulo Anterior] | <<v45-7-0,Topo>> | xref:045-romanos/045-romanos-008.adoc#v45-8-0[Próximo Capítulo &#62;]