include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-13-1]]

^<<v45-13-1,1>>^ Obedeçam às autoridades, todos vocês. Pois nenhuma autoridade existe sem a permissão de Deus, e as que existem foram colocadas nos seus lugares por ele.

[[v45-13-2]]

^<<v45-13-2,2>>^ Assim quem se revolta contra as autoridades está se revoltando contra o que Deus ordenou, e os que agem desse modo serão condenados.

[[v45-13-3]]

^<<v45-13-3,3>>^ Somente os que fazem o mal devem ter medo dos governantes, e não os que fazem o bem. Se você não quiser ter medo das autoridades, então faça o que é bom, e elas o elogiarão.

[[v45-13-4]]

^<<v45-13-4,4>>^ Porque as autoridades estão a serviço de Deus para o bem de você. Mas, se você faz o mal, então tenha medo, pois as autoridades, de fato, têm poder para castigar. Elas estão a serviço de Deus e trazem o castigo dele sobre os que fazem o mal.

[[v45-13-5]]

^<<v45-13-5,5>>^ É por isso que você deve obedecer às autoridades; não somente por causa do castigo de Deus, mas também porque a sua consciência manda que você faça isso.

[[v45-13-6]]

^<<v45-13-6,6>>^ É por isso também que vocês pagam impostos. Pois, quando as autoridades cumprem os seus deveres, elas estão a serviço de Deus.

[[v45-13-7]]

^<<v45-13-7,7>>^ Portanto, paguem ao governo o que é devido. Paguem todos os seus impostos e respeitem e honrem todas as autoridades.

[[v45-13-8]]

^<<v45-13-8,8>>^ Não fiquem devendo nada a ninguém. A única dívida que vocês devem ter é a de amar uns aos outros. Quem ama os outros está obedecendo à lei .

[[v45-13-9]]

^<<v45-13-9,9>>^ Os seguintes mandamentos: "Não cometa adultério, não mate, não roube, não cobice" — esses e ainda outros mais são resumidos num mandamento só: "Ame os outros como você ama a você mesmo."

[[v45-13-10]]

^<<v45-13-10,10>>^ Quem ama os outros não faz mal a eles. Portanto, amar é obedecer a toda a lei.

[[v45-13-11]]

^<<v45-13-11,11>>^ Vocês precisam fazer todas essas coisas porque sabem em que tempo nós estamos vivendo; chegou a hora de vocês acordarem, pois o momento de sermos salvos está mais perto agora do que quando começamos a crer.

[[v45-13-12]]

^<<v45-13-12,12>>^ A noite está terminando, e o dia vem chegando. Por isso paremos de fazer o que pertence à escuridão e peguemos as armas espirituais para lutar na luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Vivamos decentemente, como pessoas que vivem na luz do dia. Nada de farras ou bebedeiras, nem imoralidade ou indecência, nem brigas ou ciúmes.

[[v45-13-14]]

^<<v45-13-14,14>>^ Mas tenham as qualidades que o Senhor Jesus Cristo tem e não procurem satisfazer os maus desejos da natureza humana de vocês.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]