include::./index.adoc[]

[[v45-1-0]]
=== Romanos, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-1-1]]

^<<v45-1-1,1>>^ Eu, Paulo, servo  de Cristo Jesus, escrevo esta carta. Deus me chamou  e me separou para ser seu apóstolo , a fim de que eu anuncie a boa notícia do evangelho  de Deus.

[[v45-1-2]]

^<<v45-1-2,2>>^ Há muito tempo essa boa notícia foi prometida por Deus, por meio dos seus profetas , e escrita nas Escrituras Sagradas .

[[v45-1-3]]

^<<v45-1-3,3>>^ Ela fala a respeito do Filho de Deus, o nosso Senhor Jesus Cristo, o qual, como ser humano, foi descendente do rei Davi. E, quanto à sua santidade divina, a sua ressurreição provou, com grande poder, que ele é o Filho de Deus.

[[v45-1-4]]

^<<v45-1-4,4>>^ Ela fala a respeito do Filho de Deus, o nosso Senhor Jesus Cristo, o qual, como ser humano, foi descendente do rei Davi. E, quanto à sua santidade divina, a sua ressurreição provou, com grande poder, que ele é o Filho de Deus.

[[v45-1-5]]

^<<v45-1-5,5>>^ Por meio de Cristo, Deus me deu a honra de ser apóstolo no serviço de Cristo para levar pessoas de todas as nações a crerem em Cristo e a serem obedientes a ele.

[[v45-1-6]]

^<<v45-1-6,6>>^ Entre essas pessoas estão vocês que moram em Roma, a quem Deus tem chamado para pertencerem a Jesus Cristo.

[[v45-1-7]]

^<<v45-1-7,7>>^ Por isso eu escrevo a todos vocês que estão em Roma, todos vocês a quem Deus ama e a quem tem chamado para serem o seu próprio povo. Que a graça  e a paz de Deus, o nosso Pai, e do Senhor Jesus Cristo estejam com vocês!

[[v45-1-8]]

^<<v45-1-8,8>>^ Em primeiro lugar, por meio de Jesus Cristo dou graças ao meu Deus por todos vocês, pois no mundo inteiro se ouve falar a respeito da fé que vocês têm.

[[v45-1-9]]

^<<v45-1-9,9>>^ Eu sirvo a Deus com todo o meu coração, anunciando a boa notícia a respeito do seu Filho; Deus é testemunha de que digo a verdade. Ele sabe que eu sempre lembro de vocês

[[v45-1-10]]

^<<v45-1-10,10>>^ e oro por vocês. E peço a Deus que, se for da sua vontade, ele faça com que agora eu possa ir visitá-los.

[[v45-1-11]]

^<<v45-1-11,11>>^ Pois eu quero muito vê-los, a fim de repartir bênçãos espirituais com vocês para fortalecê-los,

[[v45-1-12]]

^<<v45-1-12,12>>^ quer dizer, para que nos animemos uns aos outros por meio da fé que vocês e eu temos.

[[v45-1-13]]

^<<v45-1-13,13>>^ Meus irmãos, quero que saibam que muitas vezes resolvi ir visitá-los, mas fui impedido até agora de fazer isso. Pois eu gostaria que o meu trabalho produzisse resultados entre vocês também, como tem acontecido entre outros não judeus.

[[v45-1-14]]

^<<v45-1-14,14>>^ Pois é meu dever pregar a todos, tanto aos civilizados como aos não civilizados, tanto aos instruídos como aos sem instrução.

[[v45-1-15]]

^<<v45-1-15,15>>^ É por isso que eu quero anunciar o evangelho  também a vocês que moram em Roma.

[[v45-1-16]]

^<<v45-1-16,16>>^ Eu não me envergonho do evangelho, pois ele é o poder de Deus para salvar todos os que creem, primeiro os judeus e também os não judeus.

[[v45-1-17]]

^<<v45-1-17,17>>^ Pois o evangelho mostra como é que Deus nos aceita: é por meio da fé, do começo ao fim. Como dizem as Escrituras Sagradas : "Viverá aquele que, por meio da fé, é aceito por Deus."

[[v45-1-18]]

^<<v45-1-18,18>>^ Do céu Deus revela a sua ira  contra todos os pecados e todas as maldades das pessoas que, por meio das suas más ações, não deixam que os outros conheçam a verdade a respeito de Deus.

[[v45-1-19]]

^<<v45-1-19,19>>^ Deus castiga essas pessoas porque o que se pode conhecer a respeito de Deus está bem claro para elas, pois foi o próprio Deus que lhes mostrou isso.

[[v45-1-20]]

^<<v45-1-20,20>>^ Desde que Deus criou o mundo, as suas qualidades invisíveis, isto é, o seu poder eterno e a sua natureza divina, têm sido vistas claramente. Os seres humanos podem ver tudo isso nas coisas que Deus tem feito e, portanto, eles não têm desculpa nenhuma.

[[v45-1-21]]

^<<v45-1-21,21>>^ Eles sabem quem Deus é, mas não lhe dão a glória  que ele merece e não lhe são agradecidos. Pelo contrário, os seus pensamentos se tornaram tolos, e a sua mente vazia está coberta de escuridão.

[[v45-1-22]]

^<<v45-1-22,22>>^ Eles dizem que são sábios, mas são tolos.

[[v45-1-23]]

^<<v45-1-23,23>>^ Em vez de adorarem ao Deus imortal , adoram ídolos que se parecem com seres humanos, ou com pássaros, ou com animais de quatro patas, ou com animais que se arrastam pelo chão.

[[v45-1-24]]

^<<v45-1-24,24>>^ Por isso Deus entregou os seres humanos aos desejos do coração deles para fazerem coisas sujas e para terem relações vergonhosas uns com os outros.

[[v45-1-25]]

^<<v45-1-25,25>>^ Eles trocam a verdade sobre Deus pela mentira e adoram e servem as coisas que Deus criou, em vez de adorarem e servirem o próprio Criador, que deve ser louvado para sempre. Amém !

[[v45-1-26]]

^<<v45-1-26,26>>^ Por causa das coisas que essas pessoas fazem, Deus as entregou a paixões vergonhosas. Pois até as mulheres trocam as relações naturais pelas que são contra a natureza.

[[v45-1-27]]

^<<v45-1-27,27>>^ E também os homens deixam as relações naturais com as mulheres e se queimam de paixão uns pelos outros. Homens têm relações vergonhosas uns com os outros e por isso recebem em si mesmos o castigo que merecem por causa dos seus erros.

[[v45-1-28]]

^<<v45-1-28,28>>^ E, como não querem saber do verdadeiro conhecimento a respeito de Deus, ele entregou os seres humanos aos seus maus pensamentos, de modo que eles fazem o que não devem.

[[v45-1-29]]

^<<v45-1-29,29>>^ Estão cheios de todo tipo de perversidade, maldade, ganância, vícios, ciúmes, crimes de morte, brigas, mentiras e malícia. Caluniam

[[v45-1-30]]

^<<v45-1-30,30>>^ e falam mal uns dos outros. Têm ódio de Deus e são atrevidos, orgulhosos e vaidosos. Inventam maneiras de fazer o mal, desobedecem aos pais,

[[v45-1-31]]

^<<v45-1-31,31>>^ são imorais, não cumprem a palavra, não têm amor por ninguém e não têm pena dos outros.

'''

xref:044-atos/044-atos-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romanos/045-romanos-002.adoc#v45-2-0[Próximo Capítulo &#62;]