include::./index.adoc[]

[[v45-12-0]]
=== Romanos, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-12-1]]

^<<v45-12-1,1>>^ Portanto, meus irmãos, por causa da grande misericórdia divina, peço que vocês se ofereçam completamente a Deus como um sacrifício  vivo, dedicado ao seu serviço e agradável a ele. Esta é a verdadeira adoração que vocês devem oferecer a Deus.

[[v45-12-2]]

^<<v45-12-2,2>>^ Não vivam como vivem as pessoas deste mundo, mas deixem que Deus os transforme por meio de uma completa mudança da mente de vocês. Assim vocês conhecerão a vontade de Deus, isto é, aquilo que é bom, perfeito e agradável a ele.

[[v45-12-3]]

^<<v45-12-3,3>>^ Por causa da bondade de Deus para comigo, me chamando  para ser apóstolo , eu digo a todos vocês que não se achem melhores do que realmente são. Pelo contrário, pensem com humildade a respeito de vocês mesmos, e cada um julgue a si mesmo conforme a fé que Deus lhe deu.

[[v45-12-4]]

^<<v45-12-4,4>>^ Porque, assim como em um só corpo temos muitas partes, e todas elas têm funções diferentes,

[[v45-12-5]]

^<<v45-12-5,5>>^ assim também nós, embora sejamos muitos, somos um só corpo por estarmos unidos com Cristo. E todos estamos unidos uns com os outros como partes diferentes de um só corpo.

[[v45-12-6]]

^<<v45-12-6,6>>^ Portanto, usemos os nossos diferentes dons  de acordo com a graça  que Deus nos deu. Se o dom que recebemos é o de anunciar a mensagem de Deus, façamos isso de acordo com a fé que temos.

[[v45-12-7]]

^<<v45-12-7,7>>^ Se é o dom de servir, então devemos servir; se é o de ensinar, então ensinemos;

[[v45-12-8]]

^<<v45-12-8,8>>^ se é o dom de animar os outros, então animemos. Quem reparte com os outros o que tem, que faça isso com generosidade. Quem tem autoridade, que use a sua autoridade com todo o cuidado. Quem ajuda os outros, que ajude com alegria.

[[v45-12-9]]

^<<v45-12-9,9>>^ Que o amor de vocês não seja fingido. Odeiem o mal e sigam o que é bom.

[[v45-12-10]]

^<<v45-12-10,10>>^ Amem uns aos outros com o amor de irmãos em Cristo e se esforcem para tratar uns aos outros com respeito.

[[v45-12-11]]

^<<v45-12-11,11>>^ Trabalhem com entusiasmo e não sejam preguiçosos. Sirvam o Senhor com o coração cheio de fervor.

[[v45-12-12]]

^<<v45-12-12,12>>^ Que a esperança que vocês têm os mantenha alegres; aguentem com paciência os sofrimentos e orem sempre.

[[v45-12-13]]

^<<v45-12-13,13>>^ Repartam com os irmãos necessitados o que vocês têm e recebam os estrangeiros nas suas casas.

[[v45-12-14]]

^<<v45-12-14,14>>^ Peçam que Deus abençoe os que perseguem vocês. Sim, peçam que ele abençoe e não que amaldiçoe.

[[v45-12-15]]

^<<v45-12-15,15>>^ Alegrem-se com os que se alegram e chorem com os que choram.

[[v45-12-16]]

^<<v45-12-16,16>>^ Tenham por todos o mesmo cuidado. Não sejam orgulhosos, mas aceitem serviços humildes. Que nenhum de vocês fique pensando que é sábio!

[[v45-12-17]]

^<<v45-12-17,17>>^ Não paguem a ninguém o mal com o mal. Procurem agir de tal maneira que vocês recebam a aprovação dos outros.

[[v45-12-18]]

^<<v45-12-18,18>>^ No que depender de vocês, façam todo o possível para viver em paz com todas as pessoas.

[[v45-12-19]]

^<<v45-12-19,19>>^ Meus queridos irmãos, nunca se vinguem de ninguém; pelo contrário, deixem que seja Deus quem dê o castigo. Pois as Escrituras Sagradas  dizem: "Eu me vingarei, eu acertarei contas com eles, diz o Senhor."

[[v45-12-20]]

^<<v45-12-20,20>>^ Mas façam como dizem as Escrituras: "Se o seu inimigo estiver com fome, dê comida a ele; se estiver com sede, dê água. Porque assim você o fará queimar de remorso e vergonha."

[[v45-12-21]]

^<<v45-12-21,21>>^ Não deixem que o mal vença vocês, mas vençam o mal com o bem.

'''

xref:045-romanos/045-romanos-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romanos/045-romanos-013.adoc#v45-13-0[Próximo Capítulo &#62;]