include::./index.adoc[]

[[v45-2-0]]
=== Romanos, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-2-1]]

^<<v45-2-1,1>>^ Meu amigo, não importa quem você seja, você não tem desculpa quando julga os outros. Pois, quando você os julga, mas faz as mesmas coisas que eles fazem, você está condenando a você mesmo.

[[v45-2-2]]

^<<v45-2-2,2>>^ Nós sabemos que Deus é justo quando condena os que fazem essas coisas.

[[v45-2-3]]

^<<v45-2-3,3>>^ Mas você, que faz as mesmas coisas que condena nos outros, será que você pensa que escapará do julgamento de Deus?

[[v45-2-4]]

^<<v45-2-4,4>>^ Ou será que você despreza a grande bondade, a tolerância e a paciência de Deus? Você sabe muito bem que ele é bom e que quer fazer com que você mude de vida.

[[v45-2-5]]

^<<v45-2-5,5>>^ Mas o seu coração é duro e teimoso. Por isso você está aumentando ainda mais o castigo que vai sofrer no dia em que forem revelados a ira  e os julgamentos justos de Deus,

[[v45-2-6]]

^<<v45-2-6,6>>^ pois ele recompensará cada um de acordo com o que fez.

[[v45-2-7]]

^<<v45-2-7,7>>^ Deus dará a vida eterna às pessoas que perseveram em fazer o bem e buscam a glória , a honra e a vida imortal .

[[v45-2-8]]

^<<v45-2-8,8>>^ Mas fará cair a sua ira e o seu castigo sobre os egoístas e sobre os que rejeitam o que é justo a fim de seguir o que é mau.

[[v45-2-9]]

^<<v45-2-9,9>>^ Haverá sofrimentos e aflições para todos os que fazem o mal, primeiro para os judeus e também para os não judeus.

[[v45-2-10]]

^<<v45-2-10,10>>^ Mas Deus dará glória, honra e paz a todos os que fazem o bem, primeiro aos judeus e também aos não judeus.

[[v45-2-11]]

^<<v45-2-11,11>>^ Pois ele trata a todos com igualdade.

[[v45-2-12]]

^<<v45-2-12,12>>^ Todos aqueles que pecam sem conhecer a lei  de Deus se perderão sem essa lei; mas todos aqueles que pecam conhecendo a lei serão julgados por ela.

[[v45-2-13]]

^<<v45-2-13,13>>^ Porque as pessoas que Deus aceita não são aquelas que somente ouvem a lei, mas aquelas que fazem o que a lei manda.

[[v45-2-14]]

^<<v45-2-14,14>>^ Os não judeus não têm a lei. Mas, quando fazem pela sua própria vontade o que a lei manda, eles são a sua própria lei, embora não tenham a lei.

[[v45-2-15]]

^<<v45-2-15,15>>^ Eles mostram, pela sua maneira de agir, que têm a lei escrita no seu coração. A própria consciência deles mostra que isso é verdade, e os seus pensamentos, que às vezes os acusam e às vezes os defendem, também mostram isso.

[[v45-2-16]]

^<<v45-2-16,16>>^ E, de acordo com o evangelho  que eu anuncio, assim será naquele dia em que Deus, por meio de Cristo Jesus, julgará os pensamentos secretos de todas as pessoas.

[[v45-2-17]]

^<<v45-2-17,17>>^ O que dizer de você? Você diz que é judeu, confia na lei  e se orgulha do Deus que você adora.

[[v45-2-18]]

^<<v45-2-18,18>>^ Você sabe o que Deus quer que você faça e aprende na lei a escolher o que é certo.

[[v45-2-19]]

^<<v45-2-19,19>>^ Você tem a certeza de que é guia dos cegos, luz para os que estão na escuridão,

[[v45-2-20]]

^<<v45-2-20,20>>^ orientador dos que não têm instrução e professor dos jovens. Você está certo de que encontra na lei a apresentação completa do conhecimento e da verdade.

[[v45-2-21]]

^<<v45-2-21,21>>^ Você, que ensina os outros, por que é que não ensina a você mesmo? Se afirma que não se deve roubar, por que é que você mesmo rouba?

[[v45-2-22]]

^<<v45-2-22,22>>^ Se você diz que não se deve cometer adultério, por que é que você mesmo comete adultério? Você odeia os ídolos, mas rouba as coisas dos templos.

[[v45-2-23]]

^<<v45-2-23,23>>^ Você se orgulha de ter a lei de Deus, mas você é uma vergonha para Deus porque desobedece à sua lei.

[[v45-2-24]]

^<<v45-2-24,24>>^ Pois as Escrituras Sagradas  dizem: "Os não judeus falam mal de Deus por causa de vocês, os judeus."

[[v45-2-25]]

^<<v45-2-25,25>>^ A circuncisão  tem valor se você, que é judeu, obedecer à lei; porém, se não obedecer, é como se você não tivesse sido circuncidado.

[[v45-2-26]]

^<<v45-2-26,26>>^ E, se um homem que não foi circuncidado obedecer aos mandamentos da lei, Deus o tratará como se ele fosse circuncidado.

[[v45-2-27]]

^<<v45-2-27,27>>^ Assim vocês, judeus, serão condenados pelos não judeus, pois vocês desobedecem à lei apesar de terem essa lei escrita e de serem circuncidados, enquanto que os não judeus obedecem à lei, embora não sejam circuncidados.

[[v45-2-28]]

^<<v45-2-28,28>>^ Portanto, eu pergunto: quem é judeu de fato e circuncidado de verdade? É claro que não é aquele que é judeu somente por fora e circuncidado só no corpo.

[[v45-2-29]]

^<<v45-2-29,29>>^ Pelo contrário, o verdadeiro judeu é aquele que é judeu por dentro, aquele que tem o coração circuncidado; e isso é uma coisa que o Espírito de Deus faz e que a lei escrita não pode fazer. E o louvor que essa pessoa recebe não vem de seres humanos, mas vem de Deus.

'''

xref:045-romanos/045-romanos-001.adoc#v45-1-0[&#60; Capítulo Anterior] | <<v45-2-0,Topo>> | xref:045-romanos/045-romanos-003.adoc#v45-3-0[Próximo Capítulo &#62;]