include::./index.adoc[]

[[v45-9-0]]
=== Romanos, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-9-1]]

^<<v45-9-1,1>>^ O que eu digo é verdade. Sou de Cristo e não minto; pois a minha consciência, que é controlada pelo Espírito Santo, também me afirma que não estou mentindo.

[[v45-9-2]]

^<<v45-9-2,2>>^ Sinto uma grande tristeza e uma dor sem fim no coração

[[v45-9-3]]

^<<v45-9-3,3>>^ por causa do meu povo, que é minha raça e meu sangue. Para o bem desse povo, eu mesmo poderia desejar receber a maldição de Deus e ficar separado de Cristo.

[[v45-9-4]]

^<<v45-9-4,4>>^ Eles são o povo escolhido por Deus; ele os tornou seus filhos e repartiu a sua glória  com eles. Deus fez suas alianças  com eles e lhes deu a lei , a verdadeira maneira de adorar e as promessas.

[[v45-9-5]]

^<<v45-9-5,5>>^ Eles são descendentes dos patriarcas ; e, como ser humano, Cristo pertence à raça deles. Que Cristo, que é o Deus que governa todos, seja louvado para sempre! Amém !

[[v45-9-6]]

^<<v45-9-6,6>>^ Eu não estou dizendo que a promessa de Deus tenha falhado. De fato, nem todos os israelitas fazem parte do povo de Deus.

[[v45-9-7]]

^<<v45-9-7,7>>^ Nem todos os descendentes de Abraão são filhos de Deus. Pois Deus disse a Abraão: "Por meio de Isaque é que você terá os descendentes que eu lhe prometi."

[[v45-9-8]]

^<<v45-9-8,8>>^ Isso quer dizer que os que são considerados como os verdadeiros descendentes de Abraão são aqueles que nasceram como resultado da promessa de Deus, e não os que nasceram de modo natural .

[[v45-9-9]]

^<<v45-9-9,9>>^ Pois, quando fez a promessa, Deus disse a Abraão o seguinte: "No tempo certo eu voltarei, e Sara, sua mulher, terá um filho."

[[v45-9-10]]

^<<v45-9-10,10>>^ E mais ainda: os dois filhos de Rebeca tinham o mesmo pai, o nosso antepassado Isaque.

[[v45-9-11]]

^<<v45-9-11,11>>^ Mas, para que a escolha de um deles fosse completamente de acordo com o plano de Deus, o próprio Deus disse a Rebeca: "O mais velho será dominado pelo mais moço." Disse isso antes de eles nascerem e antes de fazerem qualquer coisa, boa ou má. Assim ficou confirmado que é de acordo com o seu plano que Deus escolhe aqueles que ele quer chamar , sem levar em conta o que eles tenham feito.

[[v45-9-12]]

^<<v45-9-12,12>>^ Mas, para que a escolha de um deles fosse completamente de acordo com o plano de Deus, o próprio Deus disse a Rebeca: "O mais velho será dominado pelo mais moço." Disse isso antes de eles nascerem e antes de fazerem qualquer coisa, boa ou má. Assim ficou confirmado que é de acordo com o seu plano que Deus escolhe aqueles que ele quer chamar , sem levar em conta o que eles tenham feito.

[[v45-9-13]]

^<<v45-9-13,13>>^ Como dizem as Escrituras Sagradas : "Eu escolhi Jacó, mas rejeitei Esaú."

[[v45-9-14]]

^<<v45-9-14,14>>^ O que vamos dizer, então? Que Deus é injusto? De modo nenhum!

[[v45-9-15]]

^<<v45-9-15,15>>^ Pois ele disse a Moisés: "Terei misericórdia de quem eu quiser; terei pena de quem eu desejar."

[[v45-9-16]]

^<<v45-9-16,16>>^ Portanto, tudo isso depende não do que as pessoas querem ou fazem, mas somente da misericórdia de Deus.

[[v45-9-17]]

^<<v45-9-17,17>>^ Porque, como está escrito nas Escrituras Sagradas, Deus disse a Faraó: "Foi para isto mesmo que eu pus você como rei, para mostrar o meu poder e fazer com que o meu nome seja conhecido no mundo inteiro."

[[v45-9-18]]

^<<v45-9-18,18>>^ Portanto, Deus tem misericórdia de quem ele quer e endurece o coração de quem ele quer.

[[v45-9-19]]

^<<v45-9-19,19>>^ Algum de vocês vai me dizer: "Se é assim, como é que Deus pode encontrar culpa nas pessoas? Quem pode ir contra a vontade de Deus?"

[[v45-9-20]]

^<<v45-9-20,20>>^ Mas quem é você, meu amigo, para discutir com Deus? Será que um pote de barro pode perguntar a quem o fez: "Por que você me fez assim?"

[[v45-9-21]]

^<<v45-9-21,21>>^ Pois o homem que faz o pote tem o direito de usar o barro como quer. Do mesmo barro ele pode fazer dois potes: um pote para uso especial e outro para uso comum.

[[v45-9-22]]

^<<v45-9-22,22>>^ E foi isso o que Deus fez. Ele quis mostrar a sua ira  e tornar bem-conhecido o seu poder. Assim suportou com muita paciência os que mereciam o castigo e que iam ser destruídos.

[[v45-9-23]]

^<<v45-9-23,23>>^ Ele quis também mostrar como é grande a sua glória , que ele derramou sobre nós, que somos aqueles de quem ele teve pena e a quem ele já havia preparado para receberem a sua glória.

[[v45-9-24]]

^<<v45-9-24,24>>^ Pois nós somos aqueles que Deus chamou , não somente os que são judeus, mas também os não judeus.

[[v45-9-25]]

^<<v45-9-25,25>>^ Isso é o que ele diz no Livro de Oseias: "Aqueles que não eram meu povo eu chamarei de ‘meu Povo’. A nação que eu não amava chamarei de ‘minha Amada’.

[[v45-9-26]]

^<<v45-9-26,26>>^ E no mesmo lugar onde foi dito: ‘Vocês não são o meu povo’, ali eles serão chamados de ‘os filhos do Deus vivo’."

[[v45-9-27]]

^<<v45-9-27,27>>^ E Isaías disse a respeito de Israel: "Mesmo que o povo de Israel seja tão numeroso como os grãos de areia da praia do mar, somente alguns deles serão salvos.

[[v45-9-28]]

^<<v45-9-28,28>>^ Pois o Senhor julgará logo e de uma vez o mundo inteiro."

[[v45-9-29]]

^<<v45-9-29,29>>^ Como o próprio Isaías tinha dito antes: "Se o Senhor Todo-Poderoso não nos tivesse deixado alguns descendentes, seríamos agora como a cidade de Sodoma, estaríamos destruídos como Gomorra."

[[v45-9-30]]

^<<v45-9-30,30>>^ O que vamos dizer, então? Vamos dizer isto: os não judeus, que não procuravam ser aceitos por Deus, foram aceitos por meio da fé.

[[v45-9-31]]

^<<v45-9-31,31>>^ Porém o povo de Israel, que procurava uma lei  para ser aceito por Deus, não encontrou o que estava procurando.

[[v45-9-32]]

^<<v45-9-32,32>>^ E por que não? Porque eles procuravam alcançar isso por meio das suas ações e não por meio da fé. Eles tropeçaram na "pedra de tropeço",

'''

xref:045-romanos/045-romanos-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romanos/045-romanos-010.adoc#v45-10-0[Próximo Capítulo &#62;]