include::./index.adoc[]

[[v45-15-0]]
=== Romanos, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v45-15-1]]

^<<v45-15-1,1>>^ Nós que somos fortes na fé devemos ajudar os fracos a carregarem as suas cargas e não devemos agradar a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Pelo contrário, cada um de nós deve agradar o seu irmão, para o bem dele, a fim de que ele cresça na fé.

[[v45-15-3]]

^<<v45-15-3,3>>^ Pois nem o próprio Cristo procurou agradar a si mesmo; pelo contrário, como dizem as Escrituras Sagradas : "As ofensas daqueles que te insultaram caíram sobre mim."

[[v45-15-4]]

^<<v45-15-4,4>>^ Porque tudo o que está nas Escrituras foi escrito para nos ensinar, a fim de que tenhamos esperança por meio da paciência e da coragem que as Escrituras nos dão.

[[v45-15-5]]

^<<v45-15-5,5>>^ Que Deus, que é quem dá paciência e coragem, ajude vocês a viverem bem uns com os outros, seguindo o exemplo de Cristo Jesus!

[[v45-15-6]]

^<<v45-15-6,6>>^ E isso para que vocês, todos juntos, como se fossem uma só pessoa, louvem ao Deus e Pai do nosso Senhor Jesus Cristo.

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto, aceitem uns aos outros para a glória  de Deus, assim como Cristo aceitou vocês.

[[v45-15-8]]

^<<v45-15-8,8>>^ Pois eu lhes digo que Cristo se tornou servo  dos judeus a fim de mostrar que Deus é fiel, para fazer com que se cumprissem as promessas feitas por Deus aos patriarcas

[[v45-15-9]]

^<<v45-15-9,9>>^ e para fazer com que os não judeus louvassem a Deus pela sua bondade. Como dizem as Escrituras Sagradas : "Por isso eu te louvarei entre os que não são judeus e cantarei louvores a ti."

[[v45-15-10]]

^<<v45-15-10,10>>^ Elas dizem também: "Vocês que não são judeus, alegrem-se com o povo escolhido de Deus!"

[[v45-15-11]]

^<<v45-15-11,11>>^ E dizem ainda: "Todos os que não são judeus, louvem o Senhor! Que todos os povos o louvem!"

[[v45-15-12]]

^<<v45-15-12,12>>^ E também Isaías diz: "Virá um descendente do rei Davi, filho de Jessé; ele aparecerá para governar os que não são judeus, e eles terão esperança nele."

[[v45-15-13]]

^<<v45-15-13,13>>^ Que Deus, que nos dá essa esperança, encha vocês de alegria e de paz, por meio da fé que vocês têm nele, a fim de que a esperança de vocês aumente pelo poder do Espírito Santo!

[[v45-15-14]]

^<<v45-15-14,14>>^ Meus irmãos, estou certo de que vocês estão cheios de bondade, sabem tudo o que é preciso saber e são capazes de dar conselhos uns aos outros.

[[v45-15-15]]

^<<v45-15-15,15>>^ Porém nesta carta me atrevi a escrever com toda a franqueza para fazer com que vocês lembrem de coisas que já sabem. Eu escrevi assim por causa do privilégio que Deus me deu

[[v45-15-16]]

^<<v45-15-16,16>>^ de ser servo  de Cristo Jesus para trabalhar em favor dos que não são judeus. Eu sirvo como sacerdote ao anunciar o evangelho  que vem de Deus. E faço isso para que os não judeus sejam uma oferta que Deus aceite, dedicada a ele pelo Espírito Santo.

[[v45-15-17]]

^<<v45-15-17,17>>^ Portanto, por estar unido com Cristo Jesus, posso me orgulhar do serviço que faço para Deus.

[[v45-15-18]]

^<<v45-15-18,18>>^ Eu me atreverei a falar somente do que Cristo tem feito por meio de mim a fim de levar os não judeus a obedecerem a Deus. E isso tem sido feito por meio de palavras e de ações,

[[v45-15-19]]

^<<v45-15-19,19>>^ pelo poder de sinais e milagres e pelo poder do Espírito de Deus. Assim, viajando desde Jerusalém até a província  da Ilíria, tenho anunciado de modo completo o evangelho a respeito de Cristo.

[[v45-15-20]]

^<<v45-15-20,20>>^ Para não construir sobre alicerces colocados por outros, tenho me esforçado sempre para anunciar o evangelho nos lugares onde ainda não se falou de Cristo.

[[v45-15-21]]

^<<v45-15-21,21>>^ Como dizem as Escrituras Sagradas : "Aqueles que nunca ouviram falar a respeito dele o verão, e os que não tinham ouvido falar sobre ele o entenderão."

[[v45-15-22]]

^<<v45-15-22,22>>^ Por essa razão muitas vezes eu quis visitá-los, mas isso não me foi possível.

[[v45-15-23]]

^<<v45-15-23,23>>^ Porém, já que terminei o meu trabalho nessas regiões e como há muitos anos tenho pensado em ver vocês,

[[v45-15-24]]

^<<v45-15-24,24>>^ espero fazer isso agora. Gostaria de vê-los quando fizer a minha viagem para a Espanha. Gostaria também que vocês me ajudassem a ir até lá, depois de eu ter o prazer de estar com vocês por algum tempo.

[[v45-15-25]]

^<<v45-15-25,25>>^ Mas agora vou a Jerusalém a serviço do povo de Deus que vive ali.

[[v45-15-26]]

^<<v45-15-26,26>>^ Pois as igrejas das províncias  da Macedônia e da Acaia resolveram dar uma oferta para ajudar as pessoas do povo de Deus em Jerusalém que estão necessitadas.

[[v45-15-27]]

^<<v45-15-27,27>>^ Os próprios cristãos da Macedônia e da Acaia resolveram fazer isso; mas, de fato, eles têm a obrigação de ajudar aqueles necessitados. Os judeus repartiram os seus bens espirituais com os que não são judeus, e por isso os não judeus devem prestar, com os seus bens materiais, esse serviço cristão aos judeus.

[[v45-15-28]]

^<<v45-15-28,28>>^ Depois que eu terminar esse trabalho e que entregar toda a oferta que foi recolhida para eles, viajarei para a Espanha e no caminho visitarei vocês.

[[v45-15-29]]

^<<v45-15-29,29>>^ E sei que, quando for visitá-los, levarei comigo muitas bênçãos de Cristo.

[[v45-15-30]]

^<<v45-15-30,30>>^ Eu peço, irmãos, pelo nosso Senhor Jesus Cristo e pelo amor que o Espírito dá, que me ajudem, orando com fervor por mim.

[[v45-15-31]]

^<<v45-15-31,31>>^ Orem para que eu escape das pessoas da Judeia que não creem em Cristo e também para que a ajuda que eu vou levar a Jerusalém seja bem-aceita pelo povo de Deus que vive ali.

[[v45-15-32]]

^<<v45-15-32,32>>^ E assim, se Deus quiser, chegarei aí em Roma cheio de alegria e lhes farei uma visita que me dará um novo ânimo.

[[v45-15-33]]

^<<v45-15-33,33>>^ E que Deus, a nossa fonte de paz, esteja com todos vocês! Amém !

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]