include::./index.adoc[]

[[v52-3-0]]
=== 1 Tessalonicenses, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v52-3-1]]

^<<v52-3-1,1>>^ Então não pudemos aguentar mais sem ter notícias de vocês. Por isso Silas e eu resolvemos ficar sozinhos em Atenas

[[v52-3-2]]

^<<v52-3-2,2>>^ e enviar a vocês o nosso irmão Timóteo. Ele tem trabalhado conosco no serviço de Deus, anunciando o evangelho  de Cristo. Nós o enviamos para animar e ajudar vocês na fé,

[[v52-3-3]]

^<<v52-3-3,3>>^ a fim de que ninguém fique desanimado por causa das perseguições. Vocês mesmos sabem muito bem que elas fazem parte daquilo que Deus quer para nós.

[[v52-3-4]]

^<<v52-3-4,4>>^ Pois, quando estávamos com vocês, nós os avisamos que íamos ser perseguidos; e, como vocês sabem, isso aconteceu mesmo.

[[v52-3-5]]

^<<v52-3-5,5>>^ Por isso não pude aguentar mais sem ter notícias de vocês e enviei Timóteo para saber como vai a fé que vocês têm. É que eu tinha medo de que o Diabo os tivesse tentado de tal modo, que todo o nosso trabalho tivesse ficado inútil.

[[v52-3-6]]

^<<v52-3-6,6>>^ Agora Timóteo já voltou daí de Tessalônica e nos trouxe boas notícias a respeito da fé que vocês têm em Deus e do amor que vocês têm uns pelos outros. Ele nos contou que vocês sempre lembram de nós com carinho e que têm tanta vontade de nos ver como nós temos de ver vocês.

[[v52-3-7]]

^<<v52-3-7,7>>^ Assim, irmãos, em todas as nossas dificuldades e sofrimentos o que nos animou foi a fé que vocês têm.

[[v52-3-8]]

^<<v52-3-8,8>>^ Agora nós nos sentimos com mais vida porque sabemos que vocês continuam a viver firmes por estarem unidos com o Senhor.

[[v52-3-9]]

^<<v52-3-9,9>>^ E assim podemos dar graças a Deus por vocês. Agradecemos a alegria que temos diante do nosso Deus por causa de vocês.

[[v52-3-10]]

^<<v52-3-10,10>>^ Dia e noite pedimos a ele de todo o coração que nos deixe ir vê-los pessoalmente para podermos completar o que ainda falta na fé que vocês têm.

[[v52-3-11]]

^<<v52-3-11,11>>^ Que o próprio Deus, o nosso Pai, e o nosso Senhor Jesus preparem o nosso caminho para podermos ir visitar vocês!

[[v52-3-12]]

^<<v52-3-12,12>>^ Que o Senhor faça com que cresça cada vez mais o amor que vocês têm uns pelos outros e por todas as pessoas, e que esse amor se torne igual ao nosso amor por vocês!

[[v52-3-13]]

^<<v52-3-13,13>>^ Desse modo Deus dará força ao coração de vocês, e vocês serão completamente dedicados a ele e estarão sem culpa na presença do nosso Deus e Pai, quando o nosso Senhor Jesus vier com todos os que são dele. Amém !

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[&#60; Capítulo Anterior] | <<v52-3-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[Próximo Capítulo &#62;]