include::./index.adoc[]

[[v52-4-0]]
=== 1 Tessalonicenses, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v52-4-1]]

^<<v52-4-1,1>>^ Finalmente, irmãos, vocês aprenderam de nós como devem viver para agradar a Deus; e é assim mesmo que vocês têm vivido. E agora pedimos e aconselhamos, em nome do Senhor Jesus, que façam ainda mais.

[[v52-4-2]]

^<<v52-4-2,2>>^ Pois vocês conhecem os ensinamentos que demos pela autoridade do Senhor Jesus.

[[v52-4-3]]

^<<v52-4-3,3>>^ O que Deus quer de vocês é isto: que sejam completamente dedicados a ele e que fiquem livres da imoralidade.

[[v52-4-4]]

^<<v52-4-4,4>>^ Que cada um saiba viver com a sua esposa de um modo que agrade a Deus, com todo o respeito

[[v52-4-5]]

^<<v52-4-5,5>>^ e não com paixões sexuais baixas, como fazem os incrédulos, que não conhecem a Deus.

[[v52-4-6]]

^<<v52-4-6,6>>^ Nesse assunto, que ninguém prejudique o seu irmão, nem desrespeite os seus direitos! Pois, como nós já lhes dissemos e avisamos, o Senhor castigará duramente os que fazem essas coisas.

[[v52-4-7]]

^<<v52-4-7,7>>^ Deus não nos chamou para vivermos na imoralidade, mas para sermos completamente dedicados a ele.

[[v52-4-8]]

^<<v52-4-8,8>>^ Portanto, quem rejeita esse ensinamento não está rejeitando um ser humano, mas a Deus, que dá a vocês o seu Espírito Santo.

[[v52-4-9]]

^<<v52-4-9,9>>^ Não há necessidade de lhes escrever a respeito do amor pelos irmãos na fé, pois o próprio Deus lhes ensinou que vocês devem amar uns aos outros.

[[v52-4-10]]

^<<v52-4-10,10>>^ Pois é esse o amor que vocês têm mostrado a todos os irmãos que vivem em toda a província  da Macedônia. Portanto, meus irmãos, pedimos que façam ainda mais:

[[v52-4-11]]

^<<v52-4-11,11>>^ procurem viver em paz, tratem dos seus próprios assuntos e vivam do seu próprio trabalho, como já dissemos antes.

[[v52-4-12]]

^<<v52-4-12,12>>^ Assim, aqueles que não são cristãos os respeitarão, e vocês não precisarão viver às custas de ninguém.

[[v52-4-13]]

^<<v52-4-13,13>>^ Irmãos, queremos que vocês saibam a verdade a respeito dos que já morreram, para que não fiquem tristes como ficam aqueles que não têm esperança.

[[v52-4-14]]

^<<v52-4-14,14>>^ Nós cremos que Jesus morreu e ressuscitou; e assim cremos também que, depois que Jesus vier, Deus o levará de volta e, junto com ele, levará os que morreram crendo nele.

[[v52-4-15]]

^<<v52-4-15,15>>^ De acordo com o ensinamento do Senhor, afirmamos a vocês o seguinte: nós, os que estivermos vivos no dia da vinda do Senhor, não iremos antes daqueles que já morreram.

[[v52-4-16]]

^<<v52-4-16,16>>^ Porque haverá o grito de comando, e a voz do arcanjo , e o som da trombeta de Deus, e então o próprio Senhor descerá do céu. Aqueles que morreram crendo em Cristo ressuscitarão primeiro.

[[v52-4-17]]

^<<v52-4-17,17>>^ Então nós, os que estivermos vivos, seremos levados nas nuvens, junto com eles, para nos encontrarmos com o Senhor no ar. E assim ficaremos para sempre com o Senhor.

[[v52-4-18]]

^<<v52-4-18,18>>^ Portanto, animem uns aos outros com essas palavras.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[&#60; Capítulo Anterior] | <<v52-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[Próximo Capítulo &#62;]