include::./index.adoc[]

[[v52-5-0]]
=== 1 Tessalonicenses, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v52-5-1]]

^<<v52-5-1,1>>^ Irmãos, vocês não precisam que eu lhes escreva a respeito de quando e como essas coisas vão acontecer.

[[v52-5-2]]

^<<v52-5-2,2>>^ Pois vocês sabem muito bem que o Dia do Senhor virá como um ladrão, na calada da noite.

[[v52-5-3]]

^<<v52-5-3,3>>^ Quando as pessoas começarem a dizer: "Tudo está calmo e seguro", então é que, de repente, a destruição cairá sobre elas. As pessoas não poderão escapar, pois será como uma mulher que está sentindo as dores de parto.

[[v52-5-4]]

^<<v52-5-4,4>>^ Mas vocês, irmãos, não estão na escuridão, e o Dia do Senhor não deverá pegá-los como um ladrão, que ataca de surpresa.

[[v52-5-5]]

^<<v52-5-5,5>>^ Todos vocês são da luz e do dia. Nós não somos da noite nem da escuridão.

[[v52-5-6]]

^<<v52-5-6,6>>^ Por isso não vamos ficar dormindo, como os outros, mas vamos estar acordados e em nosso perfeito juízo.

[[v52-5-7]]

^<<v52-5-7,7>>^ Os que dormem dormem de noite, e os que bebem é de noite que ficam bêbados.

[[v52-5-8]]

^<<v52-5-8,8>>^ Mas nós, que somos do dia, devemos estar em nosso perfeito juízo. Nós devemos usar a fé e o amor como couraça  e a nossa esperança de salvação como capacete.

[[v52-5-9]]

^<<v52-5-9,9>>^ Deus não nos escolheu para sofrermos o castigo da sua ira , mas para nos dar a salvação por meio do nosso Senhor Jesus Cristo,

[[v52-5-10]]

^<<v52-5-10,10>>^ que morreu por nós para podermos viver com ele, tanto se estivermos vivos como se estivermos mortos quando ele vier.

[[v52-5-11]]

^<<v52-5-11,11>>^ Portanto, animem e ajudem uns aos outros, como vocês têm feito até agora.

[[v52-5-12]]

^<<v52-5-12,12>>^ Irmãos, pedimos a vocês que respeitem aqueles que trabalham entre vocês, isto é, aqueles que foram escolhidos pelo Senhor para guiá-los e ensiná-los.

[[v52-5-13]]

^<<v52-5-13,13>>^ Tratem essas pessoas com o maior respeito e amor, por causa do trabalho que fazem. E vivam em paz uns com os outros.

[[v52-5-14]]

^<<v52-5-14,14>>^ Pedimos a vocês, irmãos, que aconselhem com firmeza os preguiçosos, deem coragem aos tímidos, ajudem os fracos na fé e tenham paciência com todos.

[[v52-5-15]]

^<<v52-5-15,15>>^ Tomem cuidado para que ninguém pague o mal com o mal. Pelo contrário, procurem em todas as ocasiões fazer o bem uns aos outros e também aos que não são irmãos na fé.

[[v52-5-16]]

^<<v52-5-16,16>>^ Estejam sempre alegres,

[[v52-5-17]]

^<<v52-5-17,17>>^ orem sempre

[[v52-5-18]]

^<<v52-5-18,18>>^ e sejam agradecidos a Deus em todas as ocasiões. Isso é o que Deus quer de vocês por estarem unidos com Cristo Jesus.

[[v52-5-19]]

^<<v52-5-19,19>>^ Não atrapalhem a ação do Espírito Santo.

[[v52-5-20]]

^<<v52-5-20,20>>^ Não desprezem as profecias .

[[v52-5-21]]

^<<v52-5-21,21>>^ Examinem tudo, fiquem com o que é bom

[[v52-5-22]]

^<<v52-5-22,22>>^ e evitem todo tipo de mal.

[[v52-5-23]]

^<<v52-5-23,23>>^ Que Deus, que nos dá a paz, faça com que vocês sejam completamente dedicados a ele. E que ele conserve o espírito, a alma e o corpo de vocês livres de toda mancha, para o dia em que vier o nosso Senhor Jesus Cristo.

[[v52-5-24]]

^<<v52-5-24,24>>^ Aquele que os chama  é fiel e fará isso.

[[v52-5-25]]

^<<v52-5-25,25>>^ Irmãos, lembrem de nós nas suas orações.

[[v52-5-26]]

^<<v52-5-26,26>>^ Cumprimentem todos os cristãos com um beijo de irmão.

[[v52-5-27]]

^<<v52-5-27,27>>^ Peço com insistência, pela autoridade do Senhor, que esta carta seja lida para todos os irmãos.

[[v52-5-28]]

^<<v52-5-28,28>>^ Que a graça  do nosso Senhor Jesus Cristo esteja com vocês!

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[&#60; Capítulo Anterior] | <<v52-5-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[Próximo Capítulo &#62;]