include::./index.adoc[]

[[v52-2-0]]
=== 1 Tessalonicenses, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v52-2-1]]

^<<v52-2-1,1>>^ Vocês sabem muito bem, irmãos, que a nossa visita não ficou sem proveito.

[[v52-2-2]]

^<<v52-2-2,2>>^ Sabem também como fomos maltratados e insultados na cidade de Filipos, antes de chegarmos aí em Tessalônica. Fomos muito combatidos, mas o nosso Deus nos deu coragem para anunciar a vocês a boa notícia que vem dele.

[[v52-2-3]]

^<<v52-2-3,3>>^ Aquilo que anunciamos a vocês não se baseia em erros ou em má intenção; e também não tentamos enganar ninguém.

[[v52-2-4]]

^<<v52-2-4,4>>^ Pelo contrário, sempre falamos como Deus quer que falemos, porque ele nos aprovou e nos deu a tarefa de anunciar o evangelho . Não queremos agradar as pessoas, mas a Deus, que põe à prova as nossas intenções.

[[v52-2-5]]

^<<v52-2-5,5>>^ Pois vocês sabem muito bem que não usamos palavras bonitas para enganar vocês, nem procuramos tapear vocês para conseguir dinheiro. Deus é testemunha disso.

[[v52-2-6]]

^<<v52-2-6,6>>^ Nunca procuramos elogios de ninguém, nem de vocês nem de outros.

[[v52-2-7]]

^<<v52-2-7,7>>^ No entanto, tínhamos o direito de exigir de vocês alguma coisa, por sermos apóstolos  de Cristo. Mas, quando estivemos com vocês, nós fomos como crianças, fomos como uma mãe ao cuidar dos seus filhos.

[[v52-2-8]]

^<<v52-2-8,8>>^ Nós os amávamos tanto, que gostaríamos de ter dado a vocês não somente a boa notícia que vem de Deus, mas até mesmo a nossa própria vida. Como nós os amávamos!

[[v52-2-9]]

^<<v52-2-9,9>>^ Irmãos, vocês com certeza lembram de como trabalhamos e lutamos para ganhar o nosso sustento. Trabalhávamos de dia e de noite a fim de não sermos uma carga para vocês, enquanto anunciávamos a vocês a boa notícia que vem de Deus.

[[v52-2-10]]

^<<v52-2-10,10>>^ Vocês são nossas testemunhas e Deus também de que o nosso comportamento entre vocês que creram foi limpo, correto e sem nenhuma falha.

[[v52-2-11]]

^<<v52-2-11,11>>^ Vocês sabem que tratamos cada um como um pai trata os seus filhos.

[[v52-2-12]]

^<<v52-2-12,12>>^ Nós os animamos e aconselhamos para que vocês vivessem de uma maneira que agrade a Deus, que os chama  para terem parte no seu Reino  e na sua glória .

[[v52-2-13]]

^<<v52-2-13,13>>^ E existe outra razão pela qual sempre damos graças a Deus. Quando levamos a vocês a mensagem de Deus, vocês a ouviram e aceitaram. Não a aceitaram como uma mensagem que vem de pessoas, mas como a mensagem que vem de Deus, o que, de fato, ela é. Pois Deus está agindo em vocês, os que creem.

[[v52-2-14]]

^<<v52-2-14,14>>^ Meus irmãos, o que aconteceu com vocês já havia acontecido também com as igrejas de Deus na Judeia, com o povo dali que pertence a Cristo Jesus. Vocês foram perseguidos pelos seus próprios patrícios do mesmo modo que os cristãos da Judeia foram perseguidos pelos judeus.

[[v52-2-15]]

^<<v52-2-15,15>>^ Foram os judeus que mataram o Senhor Jesus e os profetas  e também nos perseguiram. Eles desagradam a Deus e são inimigos de todos.

[[v52-2-16]]

^<<v52-2-16,16>>^ Tentam até nos impedir de anunciarmos a mensagem de salvação aos não judeus. Com isso eles completam o total dos pecados que eles têm cometido. Mas agora o castigo de Deus caiu finalmente sobre eles.

[[v52-2-17]]

^<<v52-2-17,17>>^ Irmãos, nós tivemos de nos separar de vocês por algum tempo. Estamos longe dos olhos, mas perto do coração. Sentimos muitas saudades de vocês e gostaríamos de vê-los outra vez.

[[v52-2-18]]

^<<v52-2-18,18>>^ Por isso quisemos ir até aí e fazer uma visita a vocês. Pelo menos eu, Paulo, quis fazer isso mais de uma vez, mas Satanás não nos deixou.

[[v52-2-19]]

^<<v52-2-19,19>>^ Afinal, quando o nosso Senhor Jesus vier, vocês e ninguém mais são de modo todo especial a nossa esperança, a nossa alegria e o nosso motivo de satisfação, diante dele, pela nossa vitória.

[[v52-2-20]]

^<<v52-2-20,20>>^ Sim, vocês são o nosso orgulho e a nossa alegria!

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[Próximo Capítulo &#62;]