include::./index.adoc[]

[[v18-10-0]]
=== Jó, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-10-1]]

^<<v18-10-1,1>>^ "Estou cansado de viver. Vou me desabafar e falar da amargura que tenho no coração.

[[v18-10-2]]

^<<v18-10-2,2>>^ Ó Deus, não me condenes! Dize-me de que me acusas!

[[v18-10-3]]

^<<v18-10-3,3>>^ Tu mesmo me criaste. Como, então, podes ter prazer em me maltratar e desprezar e em aprovar os planos dos maus?

[[v18-10-4]]

^<<v18-10-4,4>>^ Por acaso, tens olhos, como nós? Será que vês as coisas como nós vemos?

[[v18-10-5]]

^<<v18-10-5,5>>^ Por acaso, a tua vida é tão curta como a nossa? Será que vives tão pouco quanto os seres humanos?

[[v18-10-6]]

^<<v18-10-6,6>>^ Então por que procuras saber de todos os meus pecados? Por que te informas das maldades que cometi?

[[v18-10-7]]

^<<v18-10-7,7>>^ Pois sabes que não sou culpado e que ninguém pode me salvar das tuas mãos.

[[v18-10-8]]

^<<v18-10-8,8>>^ "As tuas mãos me fizeram, me deram forma e agora essas mesmas mãos me destroem.

[[v18-10-9]]

^<<v18-10-9,9>>^ Lembra que me fizeste de barro; vais me fazer virar pó outra vez?

[[v18-10-10]]

^<<v18-10-10,10>>^ Tu fizeste com que o meu pai e a minha mãe me gerassem, que me dessem a vida.

[[v18-10-11]]

^<<v18-10-11,11>>^ Formaste o meu corpo de ossos e nervos e os cobriste com carne e pele.

[[v18-10-12]]

^<<v18-10-12,12>>^ Tu me deste vida e me deste amor, e os teus cuidados me conservam vivo.

[[v18-10-13]]

^<<v18-10-13,13>>^ Mas agora sei que no teu coração tinhas este plano secreto:

[[v18-10-14]]

^<<v18-10-14,14>>^ tu querias ver se eu ia pecar para depois me negares o teu perdão.

[[v18-10-15]]

^<<v18-10-15,15>>^ Se sou culpado, estou perdido; se sou inocente, não tenho coragem para levantar a cabeça, pois fico envergonhado quando olho para a minha desgraça.

[[v18-10-16]]

^<<v18-10-16,16>>^ Se levanto a cabeça, orgulhoso da minha inocência, tu, como um leão, me persegues; e até fazes milagres para me destruir.

[[v18-10-17]]

^<<v18-10-17,17>>^ Tu sempre tens testemunhas que me acusam; a tua ira  contra mim vai aumentando, e tu me atacas sem parar, como se fosses um exército.

[[v18-10-18]]

^<<v18-10-18,18>>^ "Ó Deus, por que me deixaste nascer? Eu deveria ter morrido antes mesmo que alguém me visse.

[[v18-10-19]]

^<<v18-10-19,19>>^ Eu teria ido do ventre da minha mãe para a sepultura, teria sido como se nunca tivesse existido.

[[v18-10-20]]

^<<v18-10-20,20>>^ A minha vida está chegando ao fim. Então me deixa em paz! Deixa que eu tenha um pouco de alegria

[[v18-10-21]]

^<<v18-10-21,21>>^ antes que me vá na viagem que não tem volta, antes que vá para o país da escuridão e das trevas,

[[v18-10-22]]

^<<v18-10-22,22>>^ para o país das sombras e da desordem, onde a própria luz é como a escuridão."

'''

xref:018-jo/018-jo-009.adoc#v18-9-0[&#60; Capítulo Anterior] | <<v18-10-0,Topo>> | xref:018-jo/018-jo-011.adoc#v18-11-0[Próximo Capítulo &#62;]