include::./index.adoc[]

[[v18-17-0]]
=== Jó, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-17-1]]

^<<v18-17-1,1>>^ Quase não posso respirar. A minha vida está se acabando; o que me espera agora é a sepultura.

[[v18-17-2]]

^<<v18-17-2,2>>^ Estou cercado de zombadores e sou obrigado a aguentar os seus desaforos.

[[v18-17-3]]

^<<v18-17-3,3>>^ "Ó Deus, só tu podes garantir o meu livramento; quem mais tenho eu para ser meu fiador?

[[v18-17-4]]

^<<v18-17-4,4>>^ Tu fechaste a mente desses zombadores para que não entendessem as coisas; não deixes que eles me derrotem.

[[v18-17-5]]

^<<v18-17-5,5>>^ Como diz o ditado: ‘Passarão fome os filhos daqueles que por dinheiro traem os seus amigos.’

[[v18-17-6]]

^<<v18-17-6,6>>^ As pessoas usam esse ditado contra mim e vêm cuspir na minha cara.

[[v18-17-7]]

^<<v18-17-7,7>>^ Estou ficando cego de tanto sofrer, e o meu corpo é apenas uma sombra.

[[v18-17-8]]

^<<v18-17-8,8>>^ Ao verem isso, os homens direitos ficam horrorizados e me condenam como se eu fosse um ateu.

[[v18-17-9]]

^<<v18-17-9,9>>^ E esses homens honestos e respeitáveis ficam firmes na sua opinião, cada vez mais convencidos de estarem certos.

[[v18-17-10]]

^<<v18-17-10,10>>^ Mas, se voltassem aqui, eu não acharia entre eles nenhum que fosse sábio.

[[v18-17-11]]

^<<v18-17-11,11>>^ "A minha vida vai passando; os meus planos fracassaram, e as esperanças do meu coração se foram.

[[v18-17-12]]

^<<v18-17-12,12>>^ Os meus amigos dizem que a noite é dia; apesar da escuridão, eles afirmam que a luz está perto.

[[v18-17-13]]

^<<v18-17-13,13>>^ A minha casa será no mundo dos mortos , onde vou me deitar e dormir na escuridão.

[[v18-17-14]]

^<<v18-17-14,14>>^ Direi que a sepultura é o meu pai e que os vermes são a minha mãe e as minhas irmãs.

[[v18-17-15]]

^<<v18-17-15,15>>^ Se é assim, onde está a minha esperança? Há alguém que possa ver esperança para mim?

[[v18-17-16]]

^<<v18-17-16,16>>^ Será que ela vai descer aos quartos do mundo dos mortos, para juntos descansarmos debaixo da terra?"

'''

xref:018-jo/018-jo-016.adoc#v18-16-0[&#60; Capítulo Anterior] | <<v18-17-0,Topo>> | xref:018-jo/018-jo-018.adoc#v18-18-0[Próximo Capítulo &#62;]