include::./index.adoc[]

[[v18-29-0]]
=== Jó, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-29-1]]

^<<v18-29-1,1>>^ E Jó continuou a sua fala e disse:

[[v18-29-2]]

^<<v18-29-2,2>>^ "Ah! Se eu pudesse voltar meses atrás, para os dias em que Deus me protegia!

[[v18-29-3]]

^<<v18-29-3,3>>^ Naquele tempo, Deus iluminava o meu caminho, e com a sua luz eu podia andar na escuridão.

[[v18-29-4]]

^<<v18-29-4,4>>^ Naqueles dias, eu estava bem de vida, e a amizade de Deus era a proteção do meu lar.

[[v18-29-5]]

^<<v18-29-5,5>>^ O Todo-Poderoso estava comigo, e os meus filhos viviam ao meu redor.

[[v18-29-6]]

^<<v18-29-6,6>>^ Em casa sempre havia leite à vontade e também azeite, tirado das oliveiras plantadas entre as pedras.

[[v18-29-7]]

^<<v18-29-7,7>>^ Quando eu saía para a reunião do tribunal e me assentava entre os juízes,

[[v18-29-8]]

^<<v18-29-8,8>>^ os moços me viam e abriam passagem, e os idosos se punham de pé.

[[v18-29-9]]

^<<v18-29-9,9>>^ As pessoas mais importantes paravam de falar e ficavam em silêncio.

[[v18-29-10]]

^<<v18-29-10,10>>^ As autoridades se calavam; não diziam mais nada.

[[v18-29-11]]

^<<v18-29-11,11>>^ "Quem me ouvia falar me dava parabéns; os que me viam falavam bem de mim,

[[v18-29-12]]

^<<v18-29-12,12>>^ pois eu ajudava os pobres que pediam ajuda e cuidava dos órfãos que não tinham quem os protegesse.

[[v18-29-13]]

^<<v18-29-13,13>>^ Pessoas que estavam na miséria me abençoavam, e as viúvas se alegravam com o meu auxílio.

[[v18-29-14]]

^<<v18-29-14,14>>^ A minha justiça e a minha honestidade faziam parte de mim; eram como a roupa que eu uso todos os dias.

[[v18-29-15]]

^<<v18-29-15,15>>^ Eu era olhos para os cegos e pés para os aleijados.

[[v18-29-16]]

^<<v18-29-16,16>>^ Era pai dos pobres e defensor dos direitos dos estrangeiros.

[[v18-29-17]]

^<<v18-29-17,17>>^ Eu acabava com o poder dos exploradores e livrava das suas garras as vítimas.

[[v18-29-18]]

^<<v18-29-18,18>>^ "Eu pensava assim: ‘Vou viver uma vida longa e morrer em casa, com todo o conforto.

[[v18-29-19]]

^<<v18-29-19,19>>^ Serei como uma árvore de raízes que chegam até a água, uma árvore que todas as noites é molhada pelo orvalho.

[[v18-29-20]]

^<<v18-29-20,20>>^ Todos só falarão bem de mim, e eu serei sempre vigoroso e forte.’

[[v18-29-21]]

^<<v18-29-21,21>>^ Todas as pessoas me davam atenção e em silêncio escutavam os meus conselhos.

[[v18-29-22]]

^<<v18-29-22,22>>^ Quando acabava de falar, ninguém discordava. As minhas palavras entravam na cabeça deles como se fossem gotas de água na areia.

[[v18-29-23]]

^<<v18-29-23,23>>^ Todos as esperavam ansiosos, como se espera a chuva no tempo de calor.

[[v18-29-24]]

^<<v18-29-24,24>>^ Eu sorria para aqueles que tinham perdido a esperança; o meu rosto alegre lhes dava coragem.

[[v18-29-25]]

^<<v18-29-25,25>>^ Eu era como um chefe, decidindo o que eles deviam fazer; eu os dirigia como um rei à frente do seu exército e os consolava nas horas de aflição.

'''

xref:018-jo/018-jo-028.adoc#v18-28-0[&#60; Capítulo Anterior] | <<v18-29-0,Topo>> | xref:018-jo/018-jo-030.adoc#v18-30-0[Próximo Capítulo &#62;]