include::./index.adoc[]

[[v18-8-0]]
=== Jó, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-8-1]]

^<<v18-8-1,1>>^ Então Bildade, da região de Sua, em resposta disse:

[[v18-8-2]]

^<<v18-8-2,2>>^ "Até quando você, Jó, vai falar assim? Até quando as suas palavras serão como um vento forte?

[[v18-8-3]]

^<<v18-8-3,3>>^ Será que Deus torceria a justiça? Será que o Todo-Poderoso faria o que não é direito?

[[v18-8-4]]

^<<v18-8-4,4>>^ Decerto os seus filhos pecaram contra Deus, e ele os castigou como mereciam.

[[v18-8-5]]

^<<v18-8-5,5>>^ Agora volte para Deus e ore ao Todo-Poderoso.

[[v18-8-6]]

^<<v18-8-6,6>>^ Se você é mesmo puro e honesto, Deus virá logo ajudá-lo e lhe dará de novo o lar que você merece.

[[v18-8-7]]

^<<v18-8-7,7>>^ A riqueza que você perdeu não será nada comparada com o que Deus lhe dará depois.

[[v18-8-8]]

^<<v18-8-8,8>>^ "Faça perguntas aos nossos antepassados; aprenda com a experiência deles.

[[v18-8-9]]

^<<v18-8-9,9>>^ Pois nós nascemos ontem e não sabemos nada; os nossos dias na terra passam como a sombra.

[[v18-8-10]]

^<<v18-8-10,10>>^ Deixe que os nossos antepassados falem a você e o ensinem. Da sua experiência eles dirão isto:

[[v18-8-11]]

^<<v18-8-11,11>>^ ‘Será que a taboa pode crescer fora do brejo ou o junco  viver sem água?

[[v18-8-12]]

^<<v18-8-12,12>>^ Verdes ainda e mesmo sem serem cortados, eles secam antes das outras ervas.

[[v18-8-13]]

^<<v18-8-13,13>>^ Assim acontece com os que esquecem de Deus; assim dá em nada a esperança dos maus.

[[v18-8-14]]

^<<v18-8-14,14>>^ A segurança deles é um fio de linha; a sua confiança é como uma teia de aranha.

[[v18-8-15]]

^<<v18-8-15,15>>^ Eles se apoiam na teia, mas ela não aguenta; agarram o fio, mas não conseguem ficar de pé.’

[[v18-8-16]]

^<<v18-8-16,16>>^ "Os maus crescem como ervas ao sol que se espalham pelo jardim.

[[v18-8-17]]

^<<v18-8-17,17>>^ As suas raízes se enroscam nas pedras, se agarram nas rochas,

[[v18-8-18]]

^<<v18-8-18,18>>^ mas, se alguém as arranca, ninguém vai nem saber que estiveram naquele lugar.

[[v18-8-19]]

^<<v18-8-19,19>>^ É nisso que dá a vida alegre dos maus; chegam outras pessoas e tomam o lugar deles.

[[v18-8-20]]

^<<v18-8-20,20>>^ "Esteja certo de que Deus não abandona as pessoas honestas, nem dá a mão para ajudar os maus.

[[v18-8-21]]

^<<v18-8-21,21>>^ Ele fará você rir de novo e dar gritos de alegria;

[[v18-8-22]]

^<<v18-8-22,22>>^ mas os seus inimigos vão viver na confusão, e as casas dos maus serão destruídas."

'''

xref:018-jo/018-jo-007.adoc#v18-7-0[&#60; Capítulo Anterior] | <<v18-8-0,Topo>> | xref:018-jo/018-jo-009.adoc#v18-9-0[Próximo Capítulo &#62;]