include::./index.adoc[]

[[v18-19-0]]
=== Jó, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-19-1]]

^<<v18-19-1,1>>^ Então em resposta Jó disse:

[[v18-19-2]]

^<<v18-19-2,2>>^ "Até quando vocês vão ficar me atormentando e me ferindo com as suas palavras?

[[v18-19-3]]

^<<v18-19-3,3>>^ Vocês já me insultaram várias vezes. Será que não se envergonham de me tratar tão mal?

[[v18-19-4]]

^<<v18-19-4,4>>^ Mesmo que eu fosse culpado, será que o meu erro prejudicaria vocês?

[[v18-19-5]]

^<<v18-19-5,5>>^ Vocês pensam que são melhores do que eu e acham que a minha desgraça prova que sou culpado.

[[v18-19-6]]

^<<v18-19-6,6>>^ "Pois fiquem sabendo que Deus foi injusto comigo; foi ele que armou uma armadilha para me pegar.

[[v18-19-7]]

^<<v18-19-7,7>>^ Eu protesto contra a sua violência, mas ninguém me ouve; eu peço ajuda, porém não existe justiça.

[[v18-19-8]]

^<<v18-19-8,8>>^ Deus fechou o meu caminho com um muro, de modo que não consigo passar; ele cobriu de escuridão os meus caminhos.

[[v18-19-9]]

^<<v18-19-9,9>>^ Deus tirou toda a minha riqueza e destruiu a boa fama que eu tinha.

[[v18-19-10]]

^<<v18-19-10,10>>^ Ele me atacou por todos os lados até acabar comigo e arrancou pelas raízes a minha esperança.

[[v18-19-11]]

^<<v18-19-11,11>>^ A sua ira  contra mim queimou como fogo; ele me tratou como se eu fosse um inimigo.

[[v18-19-12]]

^<<v18-19-12,12>>^ Ele me atacou com desgraças; como se fossem tropas, elas cavaram trincheiras e acamparam em volta da minha casa.

[[v18-19-13]]

^<<v18-19-13,13>>^ "Deus fez com que os meus irmãos me abandonassem; os meus conhecidos me tratam como se eu fosse um estranho.

[[v18-19-14]]

^<<v18-19-14,14>>^ Os meus parentes se afastaram; os meus amigos não lembram mais de mim.

[[v18-19-15]]

^<<v18-19-15,15>>^ Os meus hóspedes fazem de conta que não me conhecem; as minhas empregadas me tratam como se eu fosse um estrangeiro.

[[v18-19-16]]

^<<v18-19-16,16>>^ Chamo um empregado, e ele não me atende, nem mesmo quando peço alguma coisa por favor.

[[v18-19-17]]

^<<v18-19-17,17>>^ A minha mulher não tolera o mau cheiro da minha boca; os meus irmãos têm nojo de mim.

[[v18-19-18]]

^<<v18-19-18,18>>^ Até as crianças me desprezam; assim que me levanto, já estão zombando de mim.

[[v18-19-19]]

^<<v18-19-19,19>>^ Todos os meus amigos íntimos me detestam; as pessoas que eu mais estimo estão contra mim.

[[v18-19-20]]

^<<v18-19-20,20>>^ Virei pele e osso; mal consigo ir vivendo.

[[v18-19-21]]

^<<v18-19-21,21>>^ Meus amigos, tenham pena de mim, pois foi a mão de Deus que me feriu.

[[v18-19-22]]

^<<v18-19-22,22>>^ Por que vocês me perseguem como Deus me persegue? Por que não param de me atormentar?

[[v18-19-23]]

^<<v18-19-23,23>>^ "Como gostaria que as minhas palavras fossem escritas, que fossem escritas num livro!

[[v18-19-24]]

^<<v18-19-24,24>>^ Ou que com uma ponteira de ferro elas fossem gravadas para sempre no chumbo ou na pedra!

[[v18-19-25]]

^<<v18-19-25,25>>^ Pois eu sei que o meu defensor vive; no fim, ele virá me defender aqui na terra.

[[v18-19-26]]

^<<v18-19-26,26>>^ Mesmo que a minha pele seja toda comida pela doença, ainda neste corpo eu verei a Deus.

[[v18-19-27]]

^<<v18-19-27,27>>^ Eu o verei com os meus olhos; os meus olhos o verão, e ele não será um estranho para mim. E desejo tanto que isso aconteça!

[[v18-19-28]]

^<<v18-19-28,28>>^ "Vocês dizem: ‘Como foi que nós o atormentamos? A causa desta desgraça está nele mesmo.’

[[v18-19-29]]

^<<v18-19-29,29>>^ Mas tenham medo da espada, a espada com que Deus castiga a maldade. Fiquem sabendo que há alguém que nos julga."

'''

xref:018-jo/018-jo-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-jo/018-jo-020.adoc#v18-20-0[Próximo Capítulo &#62;]