include::./index.adoc[]

[[v18-35-0]]
=== Jó, 35
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-35-1]]

^<<v18-35-1,1>>^ Em seguida Eliú disse:

[[v18-35-2]]

^<<v18-35-2,2>>^ "Jó, você não tem o direito de dizer que para Deus você é inocente

[[v18-35-3]]

^<<v18-35-3,3>>^ e também não pode perguntar assim: ‘Ó Deus, será que te sentes mal com o meu pecado? E que vantagem tenho se não pecar?’

[[v18-35-4]]

^<<v18-35-4,4>>^ Pois eu vou responder a você e também aos seus amigos.

[[v18-35-5]]

^<<v18-35-5,5>>^ "Olhe para o céu e veja como as nuvens estão muito acima de você.

[[v18-35-6]]

^<<v18-35-6,6>>^ Se você peca, isso não atinge a Deus lá no alto; as suas faltas, por muitas que sejam, não vão prejudicar a Deus.

[[v18-35-7]]

^<<v18-35-7,7>>^ Se você faz o bem, não está ajudando a Deus; ele não precisa de nada que é seu.

[[v18-35-8]]

^<<v18-35-8,8>>^ São os outros que sofrem por causa dos pecados que você comete; e também são eles que são ajudados quando você pratica o bem.

[[v18-35-9]]

^<<v18-35-9,9>>^ "Os homens, quando são perseguidos por todos os lados, gemem e gritam, pedindo que alguém os livre das mãos dos poderosos;

[[v18-35-10]]

^<<v18-35-10,10>>^ porém não voltam para Deus, o seu Criador, que dá forças nas horas mais escuras.

[[v18-35-11]]

^<<v18-35-11,11>>^ Eles não voltam para Deus, que os torna sábios, mais sábios do que as aves e os animais.

[[v18-35-12]]

^<<v18-35-12,12>>^ Eles gritam por socorro, mas Deus não responde porque são orgulhosos e maus.

[[v18-35-13]]

^<<v18-35-13,13>>^ Mas é falso dizer que Deus não ouve ou que o Todo-Poderoso não vê.

[[v18-35-14]]

^<<v18-35-14,14>>^ "Jó, você diz que não pode ver a Deus; mas espere com paciência, pois a sua causa está com ele.

[[v18-35-15]]

^<<v18-35-15,15>>^ Você pensa que Deus não castiga, que ele não presta muita atenção no pecado.

[[v18-35-16]]

^<<v18-35-16,16>>^ Não adianta nada continuar o seu discurso; você fala muito, porém não sabe o que está dizendo."

'''

xref:018-jo/018-jo-034.adoc#v18-34-0[&#60; Capítulo Anterior] | <<v18-35-0,Topo>> | xref:018-jo/018-jo-036.adoc#v18-36-0[Próximo Capítulo &#62;]