include::./index.adoc[]

[[v18-38-0]]
=== Jó, 38
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-38-1]]

^<<v18-38-1,1>>^ Depois disso, do meio da tempestade, o Senhor  deu a Jó a seguinte resposta:

[[v18-38-2]]

^<<v18-38-2,2>>^ "As suas palavras só mostram a sua ignorância; quem é você para pôr em dúvida a minha sabedoria?

[[v18-38-3]]

^<<v18-38-3,3>>^ Mostre agora que é valente e responda às perguntas que lhe vou fazer.

[[v18-38-4]]

^<<v18-38-4,4>>^ "Onde é que você estava quando criei o mundo? Se você é tão inteligente, explique isso.

[[v18-38-5]]

^<<v18-38-5,5>>^ Você sabe quem resolveu qual seria o tamanho do mundo e quem foi que fez as medições?

[[v18-38-6]]

^<<v18-38-6,6>>^ Em cima de que estão firmadas as colunas que sustentam a terra? Quem foi que assentou a pedra principal do alicerce do mundo?

[[v18-38-7]]

^<<v18-38-7,7>>^ Na manhã da criação, as estrelas cantavam em coro, e os servidores celestiais soltavam gritos de alegria.

[[v18-38-8]]

^<<v18-38-8,8>>^ "Quando o Mar jorrou do ventre da terra, quem foi que fechou os portões para segurá-lo?

[[v18-38-9]]

^<<v18-38-9,9>>^ Fui eu que cobri o Mar com as nuvens e o envolvi com a escuridão.

[[v18-38-10]]

^<<v18-38-10,10>>^ Marquei os seus limites e fechei com trancas as suas portas.

[[v18-38-11]]

^<<v18-38-11,11>>^ E eu lhe disse: ‘Você chegará até este ponto e daqui não passará. As suas altas ondas pararão aqui.’

[[v18-38-12]]

^<<v18-38-12,12>>^ "Jó, alguma vez na sua vida você ordenou que viesse a madrugada e assim começasse um novo dia?

[[v18-38-13]]

^<<v18-38-13,13>>^ Você alguma vez mandou que a luz se espalhasse sobre a terra, sacudindo os perversos e os expulsando dos seus esconderijos?

[[v18-38-14]]

^<<v18-38-14,14>>^ A luz do dia mostra as formas das montanhas e dos vales, como se fossem as dobras de um vestido ou as marcas de um sinete  no barro.

[[v18-38-15]]

^<<v18-38-15,15>>^ Essa luz é clara demais para os perversos e os impede de praticar a violência.

[[v18-38-16]]

^<<v18-38-16,16>>^ "Jó, você já visitou as nascentes do mar? Já passeou pelo fundo do oceano?

[[v18-38-17]]

^<<v18-38-17,17>>^ Alguém já lhe mostrou os portões do mundo dos mortos , aquele mundo de escuridão sem fim?

[[v18-38-18]]

^<<v18-38-18,18>>^ Você tem alguma ideia da largura da terra? Responda, se é que você sabe tudo isso.

[[v18-38-19]]

^<<v18-38-19,19>>^ "De onde vem a luz, e qual é a origem da escuridão?

[[v18-38-20]]

^<<v18-38-20,20>>^ Você sabe mostrar a elas até onde devem chegar e depois fazer com que voltem outra vez ao ponto de partida?

[[v18-38-21]]

^<<v18-38-21,21>>^ Sim, você deve saber, pois é bem idoso e já havia nascido quando o mundo foi criado…

[[v18-38-22]]

^<<v18-38-22,22>>^ "Você alguma vez visitou os depósitos onde eu guardo a neve e as chuvas de pedra,

[[v18-38-23]]

^<<v18-38-23,23>>^ que ficam reservadas para tempos de sofrimento e para dias de lutas e de guerras?

[[v18-38-24]]

^<<v18-38-24,24>>^ Você já esteve no lugar onde nasce o sol ou no ponto onde começa a soprar o vento leste?

[[v18-38-25]]

^<<v18-38-25,25>>^ "Quem foi que abriu um canal para deixar cair os aguaceiros e marcou o caminho por onde a tempestade deve passar?

[[v18-38-26]]

^<<v18-38-26,26>>^ Quem faz a chuva cair no deserto, em lugares onde ninguém mora?

[[v18-38-27]]

^<<v18-38-27,27>>^ Quem rega as terras secas e despovoadas, fazendo nascer nelas o capim?

[[v18-38-28]]

^<<v18-38-28,28>>^ Será que a chuva e o orvalho têm pai?

[[v18-38-29]]

^<<v18-38-29,29>>^ E quem é a mãe do gelo e da geada,

[[v18-38-30]]

^<<v18-38-30,30>>^ que faz com que as águas virem pedra e que o mar fique coberto por uma camada de gelo?

[[v18-38-31]]

^<<v18-38-31,31>>^ "Será que você pode amarrar com uma corda as estrelas das Sete-Cabrinhas ou soltar as correntes que prendem as Três-Marias?

[[v18-38-32]]

^<<v18-38-32,32>>^ Você pode fazer aparecer a estrela-d'alva, ou guiar a Ursa Maior e a Ursa Menor?

[[v18-38-33]]

^<<v18-38-33,33>>^ Você conhece as leis  que governam o céu e sabe como devem ser aplicadas na terra?

[[v18-38-34]]

^<<v18-38-34,34>>^ "Será que a sua voz pode chegar até as nuvens e mandar que caia tanta chuva, que você fique coberto por um dilúvio?

[[v18-38-35]]

^<<v18-38-35,35>>^ Você pode fazer com que os raios apareçam e venham dizer-lhe: ‘Estamos às suas ordens?’

[[v18-38-36]]

^<<v18-38-36,36>>^ Quem deu sabedoria às aves, como o íbis, que anuncia as enchentes do rio Nilo, ou como o galo, que canta antes da chuva?

[[v18-38-37]]

^<<v18-38-37,37>>^ Quem é capaz de contar as nuvens? Quem pode derramar a sua água em forma de chuva,

[[v18-38-38]]

^<<v18-38-38,38>>^ que faz o pó virar barro, ligando os torrões uns aos outros?

[[v18-38-39]]

^<<v18-38-39,39>>^ "Será que é você quem dá de comer às leoas e mata a fome dos leõezinhos,

[[v18-38-40]]

^<<v18-38-40,40>>^ quando estão escondidos nas suas covas ou ficam de tocaia nas moitas?

[[v18-38-41]]

^<<v18-38-41,41>>^ Quem é que alimenta os corvos, quando andam de um lado para outro com fome, quando os seus filhotes gritam a mim pedindo comida?

'''

xref:018-jo/018-jo-037.adoc#v18-37-0[&#60; Capítulo Anterior] | <<v18-38-0,Topo>> | xref:018-jo/018-jo-039.adoc#v18-39-0[Próximo Capítulo &#62;]