include::./index.adoc[]

[[v18-24-0]]
=== Jó, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-24-1]]

^<<v18-24-1,1>>^ "Por que o Todo-Poderoso não marca um dia para julgar, um dia para fazer justiça aos que são dele?

[[v18-24-2]]

^<<v18-24-2,2>>^ Há homens que mudam os marcos de divisa para aumentar as suas terras; eles roubam ovelhas e as põem no meio das suas.

[[v18-24-3]]

^<<v18-24-3,3>>^ Levam jumentos que pertencem a órfãos e ficam com o boi de uma viúva como garantia de pagamento de empréstimo.

[[v18-24-4]]

^<<v18-24-4,4>>^ Eles não respeitam os direitos dos pobres e forçam os necessitados a correr e se esconder.

[[v18-24-5]]

^<<v18-24-5,5>>^ "Como se fossem jumentos selvagens, os pobres andam pelo deserto procurando alimento para os filhos.

[[v18-24-6]]

^<<v18-24-6,6>>^ Os pobres precisam trabalhar nas colheitas dos maus e apanham uvas para eles.

[[v18-24-7]]

^<<v18-24-7,7>>^ Não têm cobertas para se cobrir de noite, não têm nada que os proteja do frio.

[[v18-24-8]]

^<<v18-24-8,8>>^ Nas montanhas são encharcados pelas chuvas e procuram abrigo nas rochas.

[[v18-24-9]]

^<<v18-24-9,9>>^ Os perversos pegam orfãozinhos e fazem deles escravos e recebem os filhos dos necessitados como pagamento de dívidas.

[[v18-24-10]]

^<<v18-24-10,10>>^ Os pobres andam por aí quase nus e passam fome enquanto trabalham na colheita do trigo.

[[v18-24-11]]

^<<v18-24-11,11>>^ Eles movem as pedras dos moinhos dos maus para fazer azeite e pisam as suas uvas para fazer vinho, mas morrem de sede durante esse trabalho.

[[v18-24-12]]

^<<v18-24-12,12>>^ Os feridos e os que estão morrendo gritam nas cidades, mas Deus não escuta os seus gritos pedindo socorro.

[[v18-24-13]]

^<<v18-24-13,13>>^ "Os perversos odeiam a luz; em todos os seus caminhos, em tudo o que fazem, não querem saber dela.

[[v18-24-14]]

^<<v18-24-14,14>>^ O assassino se levanta de madrugada para matar o pobre e de noite vira ladrão.

[[v18-24-15]]

^<<v18-24-15,15>>^ O adúltero espera o cair da noite e cobre o rosto para que ninguém o veja.

[[v18-24-16]]

^<<v18-24-16,16>>^ Os ladrões invadem de noite as casas; eles não saem de dia, pois não querem nada com a luz.

[[v18-24-17]]

^<<v18-24-17,17>>^ Eles têm medo da luz do dia, mas a escuridão não os deixa apavorados."

[[v18-24-18]]

^<<v18-24-18,18>>^ "O homem mau é arrastado pela enchente. As suas terras são amaldiçoadas por Deus, e ele não volta a trabalhar na sua plantação de uvas.

[[v18-24-19]]

^<<v18-24-19,19>>^ Como a neve se derrete no tempo seco e no calor, assim também o pecador desaparece da terra dos vivos.

[[v18-24-20]]

^<<v18-24-20,20>>^ A própria mãe não lembra dele. Os vermes o devoram com gosto, e ele é esquecido por todos. O pecador é destruído como uma árvore que cai.

[[v18-24-21]]

^<<v18-24-21,21>>^ Isso acontece porque ele nunca ajudou as viúvas, nem teve pena das mulheres que não podem ter filhos.

[[v18-24-22]]

^<<v18-24-22,22>>^ Deus, com o seu poder, destrói os maus; ele age e acaba com a vida dos perversos.

[[v18-24-23]]

^<<v18-24-23,23>>^ Deus deixa que vivam seguros, mas fica sempre de olho neles.

[[v18-24-24]]

^<<v18-24-24,24>>^ Durante algum tempo, os perversos prosperam, mas num instante secam como o capim, são cortados como as espigas de trigo.

[[v18-24-25]]

^<<v18-24-25,25>>^ Quem pode dizer que essas coisas não são assim? Será que alguém pode provar que não estou dizendo a verdade?"

'''

xref:018-jo/018-jo-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-jo/018-jo-025.adoc#v18-25-0[Próximo Capítulo &#62;]