include::./index.adoc[]

[[v18-41-0]]
=== Jó, 41
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-41-1]]

^<<v18-41-1,1>>^ "E, quanto ao monstro Leviatã , será que você pode pescá-lo com um anzol ou amarrar a sua língua com uma corda?

[[v18-41-2]]

^<<v18-41-2,2>>^ Você é capaz de passar uma corda pelo nariz dele ou furar o seu queixo com um gancho?

[[v18-41-3]]

^<<v18-41-3,3>>^ Será que ele vai pedir que você o solte ou implorar que tenha dó dele?

[[v18-41-4]]

^<<v18-41-4,4>>^ Será que ele vai fazer um trato com você, prometendo trabalhar para você o resto da vida?

[[v18-41-5]]

^<<v18-41-5,5>>^ Será que você vai brincar com ele, como se fosse um passarinho? Você vai amarrá-lo, a fim de servir como um brinquedo para as suas empregadas?

[[v18-41-6]]

^<<v18-41-6,6>>^ Será ele vendido por um grupo de pescadores? Será que para isso o cortarão em pedaços?

[[v18-41-7]]

^<<v18-41-7,7>>^ Será que você pode enterrar lanças no seu couro ou fincar arpões de pesca na sua cabeça?

[[v18-41-8]]

^<<v18-41-8,8>>^ Tente encostar a mão nele, e será uma vez só, pois você nunca mais esquecerá a luta.

[[v18-41-9]]

^<<v18-41-9,9>>^ Só de olhar para o monstro Leviatã as pessoas perdem toda a coragem e desmaiam de medo.

[[v18-41-10]]

^<<v18-41-10,10>>^ Se alguém o provoca, ele fica furioso. Quem se arriscaria a desafiá-lo?

[[v18-41-11]]

^<<v18-41-11,11>>^ Quem pode enfrentá-lo sem sair ferido? Ninguém, no mundo inteiro.

[[v18-41-12]]

^<<v18-41-12,12>>^ "Agora vou falar das pernas do Leviatã, do seu tamanho e da sua força sem igual.

[[v18-41-13]]

^<<v18-41-13,13>>^ Quem pode arrancar o couro que o cobre ou furar a sua dupla couraça ?

[[v18-41-14]]

^<<v18-41-14,14>>^ Quem é capaz de fazê-lo abrir a sua queixada rodeada de dentes terríveis?

[[v18-41-15]]

^<<v18-41-15,15>>^ As suas costas são cobertas de fileiras de escamas ligadas umas com as outras e duras como pedras.

[[v18-41-16]]

^<<v18-41-16,16>>^ Estão coladas tão bem umas nas outras, que nem o ar passa entre elas.

[[v18-41-17]]

^<<v18-41-17,17>>^ Estão ligadas entre si e bem-coladas, de modo que ninguém pode separá-las.

[[v18-41-18]]

^<<v18-41-18,18>>^ Quando o Leviatã espirra, saem faíscas; os seus olhos brilham como o sol ao amanhecer.

[[v18-41-19]]

^<<v18-41-19,19>>^ A sua boca lança chamas, e dela saltam faíscas de fogo.

[[v18-41-20]]

^<<v18-41-20,20>>^ O seu nariz solta fumaça, como a de galhos que queimam debaixo de uma panela.

[[v18-41-21]]

^<<v18-41-21,21>>^ O seu sopro acende o fogo, e da sua boca saem chamas.

[[v18-41-22]]

^<<v18-41-22,22>>^ A sua força está no pescoço, e a cara dele mete medo em todo mundo.

[[v18-41-23]]

^<<v18-41-23,23>>^ No seu couro não existe ponto fraco; ele é firme e duro como ferro.

[[v18-41-24]]

^<<v18-41-24,24>>^ O seu coração cruel não tem medo; é duro como uma pedra de moinho.

[[v18-41-25]]

^<<v18-41-25,25>>^ Quando ele se levanta, até os mais fortes ficam apavorados; o medo os impede de agir.

[[v18-41-26]]

^<<v18-41-26,26>>^ Não há espada que consiga feri-lo, nem lança, nem flecha, nem arpão.

[[v18-41-27]]

^<<v18-41-27,27>>^ Para ele, o ferro é como palha, e o bronze, como pau podre.

[[v18-41-28]]

^<<v18-41-28,28>>^ As flechas não o fazem fugir. Jogar pedras nele é como jogar capim.

[[v18-41-29]]

^<<v18-41-29,29>>^ Bater nele com um porrete é o mesmo que bater com uma torcida de palha; ele zomba dos homens que lhe atiram lanças.

[[v18-41-30]]

^<<v18-41-30,30>>^ A sua barriga é coberta de cacos pontudos, que reviram a lama como se fossem uma grade de ferro.

[[v18-41-31]]

^<<v18-41-31,31>>^ Ele agita o mar e o faz ficar como água que ferve na panela, como o óleo fervendo no caldeirão.

[[v18-41-32]]

^<<v18-41-32,32>>^ Ele vai deixando na água um rastro luminoso, como se o mar tivesse uma cabeleira branca.

[[v18-41-33]]

^<<v18-41-33,33>>^ Não há nada neste mundo que se compare com ele, pois foi feito para não ter medo.

[[v18-41-34]]

^<<v18-41-34,34>>^ O Leviatã olha para tudo com desprezo e entre todas as feras orgulhosas ele é rei."

'''

xref:018-jo/018-jo-040.adoc#v18-40-0[&#60; Capítulo Anterior] | <<v18-41-0,Topo>> | xref:018-jo/018-jo-042.adoc#v18-42-0[Próximo Capítulo &#62;]