include::./index.adoc[]

[[v18-28-0]]
=== Jó, 28
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-28-1]]

^<<v18-28-1,1>>^ Há minas de onde se tira a prata, há lugares onde se refina o ouro.

[[v18-28-2]]

^<<v18-28-2,2>>^ O ferro é tirado da terra, e das pedras se derrete o cobre.

[[v18-28-3]]

^<<v18-28-3,3>>^ Os mineiros levam luz para debaixo da terra; eles exploram lugares profundos e ali, na escuridão, procuram minérios.

[[v18-28-4]]

^<<v18-28-4,4>>^ Longe das cidades, em lugares por onde ninguém passa, eles abrem os poços das minas. E trabalham na solidão, pendurados e balançando de um lado para outro.

[[v18-28-5]]

^<<v18-28-5,5>>^ Por cima deles, a terra produz trigo e por baixo está toda rasgada e esmigalhada.

[[v18-28-6]]

^<<v18-28-6,6>>^ As suas pedras contêm safiras , e no seu pó se encontra ouro.

[[v18-28-7]]

^<<v18-28-7,7>>^ As águias não veem o caminho que desce para as minas, e os falcões também não o conhecem.

[[v18-28-8]]

^<<v18-28-8,8>>^ Os leões e outros animais ferozes nunca descem por esse caminho.

[[v18-28-9]]

^<<v18-28-9,9>>^ Os homens cavam as rochas mais duras e cortam as montanhas até o chão.

[[v18-28-10]]

^<<v18-28-10,10>>^ Eles furam túneis nas pedras, com olhos abertos para tudo o que é precioso.

[[v18-28-11]]

^<<v18-28-11,11>>^ Eles cavam até chegar às nascentes dos rios e trazem para a luz o que estava escondido.

[[v18-28-12]]

^<<v18-28-12,12>>^ Mas onde pode ser achada a sabedoria? Em que lugar está a inteligência?

[[v18-28-13]]

^<<v18-28-13,13>>^ Os seres humanos não conhecem o valor da sabedoria e não a encontram neste mundo.

[[v18-28-14]]

^<<v18-28-14,14>>^ O Oceano afirma: "Aqui não está", e o Mar diz: "Aqui também não."

[[v18-28-15]]

^<<v18-28-15,15>>^ Ela não pode ser comprada com ouro, nem trocada por prata.

[[v18-28-16]]

^<<v18-28-16,16>>^ Não se compra a sabedoria com o ouro mais puro, nem com pedras preciosas, como a ágata  ou a safira .

[[v18-28-17]]

^<<v18-28-17,17>>^ Ela vale mais do que o ouro ou o vidro; não se pode trocá-la por joias de ouro puro.

[[v18-28-18]]

^<<v18-28-18,18>>^ Do coral e do cristal nem se fala; a sabedoria é mais valiosa do que as pérolas.

[[v18-28-19]]

^<<v18-28-19,19>>^ O topázio  da Etiópia não se compara com ela; e ela não pode ser comprada com o ouro mais puro.

[[v18-28-20]]

^<<v18-28-20,20>>^ De onde vem, então, a sabedoria? Em que lugar está a inteligência?

[[v18-28-21]]

^<<v18-28-21,21>>^ Nenhum ser vivo pode vê-la, nem mesmo as aves que voam no céu.

[[v18-28-22]]

^<<v18-28-22,22>>^ Até a Destruição e a Morte dizem: "Nós apenas ouvimos falar dela."

[[v18-28-23]]

^<<v18-28-23,23>>^ Só Deus conhece o caminho; só ele sabe onde está a sabedoria

[[v18-28-24]]

^<<v18-28-24,24>>^ porque a sua vista alcança os lugares mais distantes do mundo; ele vê tudo o que acontece aqui na terra.

[[v18-28-25]]

^<<v18-28-25,25>>^ Quando Deus regulou a força dos ventos e marcou o tamanho do mar;

[[v18-28-26]]

^<<v18-28-26,26>>^ quando decidiu onde a chuva devia cair e por onde a tempestade devia passar;

[[v18-28-27]]

^<<v18-28-27,27>>^ foi então que ele viu a sabedoria, e a examinou, e aprovou.

[[v18-28-28]]

^<<v18-28-28,28>>^ E ele disse aos seres humanos: "Para ser sábio, é preciso temer  o Senhor; para ter compreensão, é necessário afastar-se do mal."

'''

xref:018-jo/018-jo-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-jo/018-jo-029.adoc#v18-29-0[Próximo Capítulo &#62;]