include::./index.adoc[]

[[v18-9-0]]
=== Jó, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-9-1]]

^<<v18-9-1,1>>^ Então em resposta Jó disse:

[[v18-9-2]]

^<<v18-9-2,2>>^ "Eu sei muito bem que as coisas são assim. Mas como é que uma pessoa pode provar a Deus que ela está com a razão?

[[v18-9-3]]

^<<v18-9-3,3>>^ Quem se atreve a discutir com Deus? Ele pode fazer mil perguntas a que ninguém é capaz de responder.

[[v18-9-4]]

^<<v18-9-4,4>>^ A sua sabedoria é profunda, e o seu poder é grande; quem pode desafiá-lo e vencer?

[[v18-9-5]]

^<<v18-9-5,5>>^ Sem aviso ele muda de lugar os montes e na sua ira  os destrói.

[[v18-9-6]]

^<<v18-9-6,6>>^ Deus manda terremotos, e o chão treme; ele abala as colunas que sustentam a terra.

[[v18-9-7]]

^<<v18-9-7,7>>^ Deus dá ordem, e o sol não nasce; ele apaga a luz das estrelas.

[[v18-9-8]]

^<<v18-9-8,8>>^ Deus sozinho estendeu o céu; ele pisou sobre as costas do Mar .

[[v18-9-9]]

^<<v18-9-9,9>>^ Deus criou as estrelas em grupos: a Ursa Maior, as Três-Marias e as Sete-Cabrinhas, e fez também as estrelas do Sul.

[[v18-9-10]]

^<<v18-9-10,10>>^ Deus faz coisas grandes e maravilhosas, e os seus milagres não têm fim.

[[v18-9-11]]

^<<v18-9-11,11>>^ Deus passa perto de mim, e eu não vejo; ele vai andando, e eu não percebo.

[[v18-9-12]]

^<<v18-9-12,12>>^ Se Deus quer ficar com alguma coisa, quem pode impedi-lo? Quem se atreve a perguntar: ‘O que estás fazendo?’

[[v18-9-13]]

^<<v18-9-13,13>>^ Deus não volta atrás na sua ira; a seus pés caem derrotados os aliados do monstro Raabe .

[[v18-9-14]]

^<<v18-9-14,14>>^ "Quem sou eu, então, para responder a Deus? Onde vou achar palavras para discutir com ele?

[[v18-9-15]]

^<<v18-9-15,15>>^ Ainda que eu tivesse razão, eu não responderia. Ele é o meu juiz; só posso pedir misericórdia.

[[v18-9-16]]

^<<v18-9-16,16>>^ Ainda que eu o chamasse ao tribunal, e ele se apresentasse, não acredito que ouviria o meu caso.

[[v18-9-17]]

^<<v18-9-17,17>>^ Deus me esmaga com uma tempestade e sem motivo aumenta as minhas feridas.

[[v18-9-18]]

^<<v18-9-18,18>>^ Ele não me deixa nem respirar e enche de amargura a minha vida.

[[v18-9-19]]

^<<v18-9-19,19>>^ Farei uso da força? Ele é o forte. Chamarei Deus ao tribunal? E quem o obrigaria a comparecer?

[[v18-9-20]]

^<<v18-9-20,20>>^ Sou inocente e sincero, mas as minhas palavras me condenariam e me declarariam culpado.

[[v18-9-21]]

^<<v18-9-21,21>>^ Sou inocente, mas não me importo com isso; estou cansado de viver.

[[v18-9-22]]

^<<v18-9-22,22>>^ Para mim, é tudo a mesma coisa; por isso, digo que Deus destrói tanto os bons como os maus.

[[v18-9-23]]

^<<v18-9-23,23>>^ Se, de repente, uma desgraça mata pessoas inocentes, Deus ri.

[[v18-9-24]]

^<<v18-9-24,24>>^ Deus entregou o mundo nas mãos dos maus e cobriu os olhos dos juízes com uma venda. E, se não foi Deus quem fez isso, então quem foi?

[[v18-9-25]]

^<<v18-9-25,25>>^ "Os meus dias correm mais depressa do que um atleta; eles fogem sem ter visto a felicidade.

[[v18-9-26]]

^<<v18-9-26,26>>^ A minha vida passa como um barco ligeiro, como uma águia quando se lança sobre um coelho.

[[v18-9-27]]

^<<v18-9-27,27>>^ Posso tentar esquecer as minhas queixas, posso deixar o meu ar triste e voltar a ser alegre,

[[v18-9-28]]

^<<v18-9-28,28>>^ mas logo os meus sofrimentos me deixam apavorado, pois sei que Deus não acredita que eu seja inocente.

[[v18-9-29]]

^<<v18-9-29,29>>^ E, se ele acha que sou culpado, não adianta nada lutar.

[[v18-9-30]]

^<<v18-9-30,30>>^ O sabão não pode lavar os meus pecados; o sabão mais forte não pode limpar o mal que cometi.

[[v18-9-31]]

^<<v18-9-31,31>>^ Deus me joga na lama, e até a minha roupa tem nojo de mim.

[[v18-9-32]]

^<<v18-9-32,32>>^ Deus não é um ser humano, como eu, e por isso não posso responder-lhe, nem podemos resolver a nossa questão no tribunal.

[[v18-9-33]]

^<<v18-9-33,33>>^ Para nós dois não há um juiz que possa julgar a mim e a Deus.

[[v18-9-34]]

^<<v18-9-34,34>>^ Ó Deus, para de me castigar! Não me enchas de medo com os teus terrores!

[[v18-9-35]]

^<<v18-9-35,35>>^ Então eu falarei e não terei medo, pois a minha consciência não me acusa.

'''

xref:018-jo/018-jo-008.adoc#v18-8-0[&#60; Capítulo Anterior] | <<v18-9-0,Topo>> | xref:018-jo/018-jo-010.adoc#v18-10-0[Próximo Capítulo &#62;]