include::./index.adoc[]

[[v18-1-0]]
=== Jó, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-1-1]]

^<<v18-1-1,1>>^ Na terra de Uz morava um homem chamado Jó. Ele era bom e honesto, temia a Deus  e procurava não fazer nada que fosse errado.

[[v18-1-2]]

^<<v18-1-2,2>>^ Jó tinha sete filhos e três filhas

[[v18-1-3]]

^<<v18-1-3,3>>^ e era dono de sete mil ovelhas, três mil camelos, mil bois e quinhentas jumentas. Tinha também um grande número de escravos. Enfim, Jó era o homem mais rico de todo o Oriente.

[[v18-1-4]]

^<<v18-1-4,4>>^ Os filhos de Jó iam às casas uns dos outros e davam banquetes, cada um por sua vez. E as três irmãs eram sempre convidadas para esses comes e bebes.

[[v18-1-5]]

^<<v18-1-5,5>>^ Quando terminava uma rodada de banquetes, Jó se levantava de madrugada e oferecia sacrifícios  em favor de cada um dos seus filhos, para purificá-los . Jó sempre fazia isso porque pensava que um dos filhos poderia ter pecado, ofendendo a Deus em pensamento.

[[v18-1-6]]

^<<v18-1-6,6>>^ Chegou o dia em que os servidores celestiais vieram apresentar-se diante de Deus, o Senhor , e no meio deles veio também Satanás .

[[v18-1-7]]

^<<v18-1-7,7>>^ O Senhor  perguntou: — De onde você vem vindo? Satanás respondeu: — Estive dando uma volta pela terra, passeando por aqui e por ali.

[[v18-1-8]]

^<<v18-1-8,8>>^ Aí o Senhor  disse: — Você notou o meu servo  Jó? No mundo inteiro não há ninguém tão bom e honesto como ele. Ele me teme  e procura não fazer nada que seja errado.

[[v18-1-9]]

^<<v18-1-9,9>>^ Satanás respondeu: — Será que não é por interesse próprio que Jó te teme?

[[v18-1-10]]

^<<v18-1-10,10>>^ Tu não deixas que nenhum mal aconteça a ele, à sua família e a tudo o que ele tem. Abençoas tudo o que Jó faz, e no país inteiro ele é o homem que tem mais cabeças de gado.

[[v18-1-11]]

^<<v18-1-11,11>>^ Mas, se tirares tudo o que é dele, verás que ele te amaldiçoará sem nenhum respeito.

[[v18-1-12]]

^<<v18-1-12,12>>^ O Senhor  disse a Satanás: — Pois bem. Faça o que quiser com tudo o que Jó tem, mas não faça nenhum mal a ele mesmo. Então Satanás saiu da presença do Senhor .

[[v18-1-13]]

^<<v18-1-13,13>>^ Um dia, enquanto os filhos e as filhas de Jó estavam num banquete na casa do irmão mais velho,

[[v18-1-14]]

^<<v18-1-14,14>>^ chegou à casa de Jó um dos seus empregados, que disse: — Nós estávamos arando a terra com os bois, e as jumentas estavam pastando ali perto.

[[v18-1-15]]

^<<v18-1-15,15>>^ De repente, os sabeus nos atacaram e levaram tudo. Eles mataram à espada os empregados, e só eu consegui escapar para trazer a notícia.

[[v18-1-16]]

^<<v18-1-16,16>>^ Enquanto este ainda estava falando, veio outro empregado e disse: — Raios caíram do céu e mataram todas as ovelhas e os pastores. Só eu consegui escapar para trazer a notícia.

[[v18-1-17]]

^<<v18-1-17,17>>^ Enquanto este ainda estava falando, chegou um terceiro, que disse: — Três bandos de caldeus nos atacaram e levaram os camelos. Eles mataram à espada os empregados, e só eu consegui escapar para trazer a notícia.

[[v18-1-18]]

^<<v18-1-18,18>>^ Enquanto este ainda estava falando, chegou mais um, que disse a Jó: — Os seus filhos e as suas filhas estavam no meio de um banquete na casa do seu filho mais velho.

[[v18-1-19]]

^<<v18-1-19,19>>^ De repente, veio do deserto um vento muito forte que soprou contra a casa, e ela caiu em cima dos seus filhos. Todos eles morreram; só eu consegui escapar para trazer a notícia.

[[v18-1-20]]

^<<v18-1-20,20>>^ Então Jó se levantou e, em sinal de tristeza, rasgou as suas roupas e rapou a cabeça. Depois ajoelhou-se, encostou o rosto no chão e adorou a Deus.

[[v18-1-21]]

^<<v18-1-21,21>>^ Aí disse assim: — Nasci nu, sem nada, e sem nada vou morrer. O Senhor  deu, o Senhor  tirou; louvado seja o seu nome!

[[v18-1-22]]

^<<v18-1-22,22>>^ Assim, apesar de tudo o que havia acontecido, Jó não pecou, nem pôs a culpa em Deus.

'''

xref:017-ester/017-ester-010.adoc#v17-10-0[&#60; Capítulo Anterior] | <<v18-1-0,Topo>> | xref:018-jo/018-jo-002.adoc#v18-2-0[Próximo Capítulo &#62;]