include::./index.adoc[]

[[v18-5-0]]
=== Jó, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-5-1]]

^<<v18-5-1,1>>^ "Grite, Jó! Veja se alguém responde. Que anjo você vai chamar?

[[v18-5-2]]

^<<v18-5-2,2>>^ Ficar desgostoso e amargurado é loucura, é falta de juízo, que leva à morte.

[[v18-5-3]]

^<<v18-5-3,3>>^ Uma vez vi um homem sem juízo que parecia estar progredindo na vida, mas eu amaldiçoei a família dele.

[[v18-5-4]]

^<<v18-5-4,4>>^ Os seus filhos não têm segurança; nos tribunais são condenados injustamente, e não há ninguém que os defenda.

[[v18-5-5]]

^<<v18-5-5,5>>^ Os famintos ficam cobiçando as suas riquezas; devoram as suas colheitas, pegando até o trigo que nasce entre os espinhos.

[[v18-5-6]]

^<<v18-5-6,6>>^ A aflição não brota da terra; a desgraça não nasce do chão:

[[v18-5-7]]

^<<v18-5-7,7>>^ somos nós mesmos que causamos o sofrimento, tão certo como as faíscas das brasas voam para cima.

[[v18-5-8]]

^<<v18-5-8,8>>^ "Jó, se eu fosse você, voltaria para Deus e entregaria o meu problema a ele.

[[v18-5-9]]

^<<v18-5-9,9>>^ Nós não podemos entender as coisas maravilhosas que ele faz, e os seus milagres não têm fim.

[[v18-5-10]]

^<<v18-5-10,10>>^ Deus dá chuva à terra; ele faz a água cair sobre os campos.

[[v18-5-11]]

^<<v18-5-11,11>>^ Deus põe os humildes nas alturas, põe num lugar seguro os que choram.

[[v18-5-12]]

^<<v18-5-12,12>>^ Deus faz com que os planos dos espertos falhem e que as suas ações fracassem;

[[v18-5-13]]

^<<v18-5-13,13>>^ ele pega os sábios nas suas espertezas e acaba com as suas intrigas.

[[v18-5-14]]

^<<v18-5-14,14>>^ Em pleno dia eles ficam no escuro e ao meio-dia andam às cegas, apalpando como se fosse noite.

[[v18-5-15]]

^<<v18-5-15,15>>^ Deus salva da morte os pobres; ele livra os necessitados das mãos dos poderosos.

[[v18-5-16]]

^<<v18-5-16,16>>^ Deus dá esperança aos fracos e tapa a boca dos maus.

[[v18-5-17]]

^<<v18-5-17,17>>^ "Feliz é aquele a quem Deus corrige! Por isso, não despreze o castigo do Deus Todo-Poderoso.

[[v18-5-18]]

^<<v18-5-18,18>>^ Deus fere, mas ele mesmo faz o curativo; ele machuca, mas as suas mãos curam.

[[v18-5-19]]

^<<v18-5-19,19>>^ Vez após vez Deus salvará você do perigo e não deixará que nenhum mal lhe aconteça.

[[v18-5-20]]

^<<v18-5-20,20>>^ Em tempo de fome, Deus não deixará que você morra e em tempo de guerra ele o salvará da espada.

[[v18-5-21]]

^<<v18-5-21,21>>^ Ele o protegerá das más línguas, e você não terá medo quando houver destruição.

[[v18-5-22]]

^<<v18-5-22,22>>^ Você se rirá quando houver violência e faltarem alimentos e não terá medo dos animais selvagens.

[[v18-5-23]]

^<<v18-5-23,23>>^ Nos seus campos as pedras não estorvarão o arado, e os animais selvagens não o atacarão.

[[v18-5-24]]

^<<v18-5-24,24>>^ Na sua casa você viverá em paz e, quando contar as suas coisas, não vai achar falta de nada.

[[v18-5-25]]

^<<v18-5-25,25>>^ Você terá muitos filhos, e os seus descendentes serão tantos como as folhas de capim no pasto.

[[v18-5-26]]

^<<v18-5-26,26>>^ Você vai morrer velho e forte, como um feixe de trigo colhido no tempo certo.

[[v18-5-27]]

^<<v18-5-27,27>>^ Jó, a vida nos ensina que é assim. Esta é a verdade; pense nisso para o seu próprio bem."

'''

xref:018-jo/018-jo-004.adoc#v18-4-0[&#60; Capítulo Anterior] | <<v18-5-0,Topo>> | xref:018-jo/018-jo-006.adoc#v18-6-0[Próximo Capítulo &#62;]