include::./index.adoc[]

[[v18-27-0]]
=== Jó, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-27-1]]

^<<v18-27-1,1>>^ E Jó continuou em sua fala e disse:

[[v18-27-2]]

^<<v18-27-2,2>>^ "Juro por Deus, pelo Todo-Poderoso, que não quer me fazer justiça e que enche de amargura o meu coração,

[[v18-27-3]]

^<<v18-27-3,3>>^ juro que, enquanto ele me der forças para respirar,

[[v18-27-4]]

^<<v18-27-4,4>>^ os meus lábios nunca dirão coisas más, e a minha língua não contará mentiras.

[[v18-27-5]]

^<<v18-27-5,5>>^ Nunca direi que vocês têm razão de me acusar; enquanto viver, insistirei na minha inocência.

[[v18-27-6]]

^<<v18-27-6,6>>^ Fico firme e não desisto de dizer que estou certo, pois a minha consciência nunca me acusou.

[[v18-27-7]]

^<<v18-27-7,7>>^ "Que todos os que são contra mim, os que são meus inimigos, sejam castigados como os maus, como os perversos!

[[v18-27-8]]

^<<v18-27-8,8>>^ Que esperança terão os ateus quando Deus lhes tirar a vida?

[[v18-27-9]]

^<<v18-27-9,9>>^ Quando estiverem em dificuldades, ele não ouvirá os seus gritos,

[[v18-27-10]]

^<<v18-27-10,10>>^ pois Deus não é a alegria deles, e eles nunca fizeram orações ao Todo-Poderoso.

[[v18-27-11]]

^<<v18-27-11,11>>^ "Vou ensinar a vocês como é grande o poder de Deus, vou explicar os planos do Todo-Poderoso.

[[v18-27-12]]

^<<v18-27-12,12>>^ Não, não é preciso, pois vocês todos já viram isso. Então por que é que ficam aí dizendo bobagens?"

[[v18-27-13]]

^<<v18-27-13,13>>^ "Vou dizer como Deus, o Todo-Poderoso, castiga os homens maus e violentos.

[[v18-27-14]]

^<<v18-27-14,14>>^ As suas crianças passarão fome, e os seus filhos, mesmo que sejam muitos, morrerão na guerra;

[[v18-27-15]]

^<<v18-27-15,15>>^ os que ficarem vivos morrerão de doença, e as suas viúvas não chorarão por eles.

[[v18-27-16]]

^<<v18-27-16,16>>^ "O perverso pode ajuntar prata aos montes, pode ter muita roupa, muita mesmo,

[[v18-27-17]]

^<<v18-27-17,17>>^ mas algum dia uma pessoa direita usará essas roupas, e um homem honesto ficará com a prata.

[[v18-27-18]]

^<<v18-27-18,18>>^ A casa que o homem mau constrói dura tão pouco tempo como uma teia de aranha ou como a cabana de um vigia numa plantação.

[[v18-27-19]]

^<<v18-27-19,19>>^ O homem mau vai rico para a cama, mas é pela última vez, pois, quando acorda, a sua riqueza já se foi.

[[v18-27-20]]

^<<v18-27-20,20>>^ O terror o arrasará como se fosse uma enchente, e de noite a tempestade o jogará longe.

[[v18-27-21]]

^<<v18-27-21,21>>^ O vento violento do Leste o arrancará da sua casa,

[[v18-27-22]]

^<<v18-27-22,22>>^ soprando contra ele sem piedade, enquanto ele faz tudo para escapar.

[[v18-27-23]]

^<<v18-27-23,23>>^ Ele corre, e o vento assobia e o apavora com o seu poder destruidor."

'''

xref:018-jo/018-jo-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-jo/018-jo-028.adoc#v18-28-0[Próximo Capítulo &#62;]