include::./index.adoc[]

[[v18-32-0]]
=== Jó, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-32-1]]

^<<v18-32-1,1>>^ Jó estava convencido da sua inocência, e por isso os três amigos desistiram de continuar a discutir com ele.

[[v18-32-2]]

^<<v18-32-2,2>>^ Acontece que ali estava um homem chamado Eliú, filho de Baraquel e descendente de Buz, do grupo de famílias de Rão. Eliú ficou muito zangado com Jó porque este dizia que era inocente e que Deus era culpado.

[[v18-32-3]]

^<<v18-32-3,3>>^ E também ficou zangado com os três amigos porque eles não puderam responder a Jó, dando assim a ideia de que Deus estava errado.

[[v18-32-4]]

^<<v18-32-4,4>>^ Eliú esperou para falar no fim, pois os outros eram mais velhos do que ele.

[[v18-32-5]]

^<<v18-32-5,5>>^ Quando viu que eles não souberam como responder a Jó, Eliú ficou zangado.

[[v18-32-6]]

^<<v18-32-6,6>>^ Então Eliú, filho de Baraquel e descendente de Buz, disse: "Eu sou moço, e vocês são idosos. Foi por isso que não me atrevi a dar a minha opinião.

[[v18-32-7]]

^<<v18-32-7,7>>^ Pensei assim: ‘Que fale a voz da experiência, que os muitos anos mostrem a sua sabedoria!’

[[v18-32-8]]

^<<v18-32-8,8>>^ Mas acontece que dentro das pessoas há um espírito, há um sopro do Todo-Poderoso que dá sabedoria.

[[v18-32-9]]

^<<v18-32-9,9>>^ Nós não ficamos mais sábios com a idade, nem sempre os velhos sabem o que é certo.

[[v18-32-10]]

^<<v18-32-10,10>>^ Portanto, escutem o que digo, pois eu também vou dar a minha opinião.

[[v18-32-11]]

^<<v18-32-11,11>>^ "Esperei que vocês falassem e escutei as suas razões. Enquanto vocês escolhiam as melhores palavras,

[[v18-32-12]]

^<<v18-32-12,12>>^ eu prestava toda a atenção. Mas nenhum de vocês convenceu Jó, nem deu resposta às suas palavras.

[[v18-32-13]]

^<<v18-32-13,13>>^ Como é que vocês podem dizer que descobriram a sabedoria? É Deus, e não um ser humano, quem terá de dar resposta a Jó.

[[v18-32-14]]

^<<v18-32-14,14>>^ Eu nunca teria respondido como vocês; mas Jó estava falando com vocês e não comigo.

[[v18-32-15]]

^<<v18-32-15,15>>^ "Jó, estes três estão derrotados e não têm mais palavras para continuar a discutir.

[[v18-32-16]]

^<<v18-32-16,16>>^ Eles já pararam; não falam mais. Será que devo continuar esperando enquanto estão calados?

[[v18-32-17]]

^<<v18-32-17,17>>^ Não! Eu darei a minha resposta agora e direi o que penso sobre o assunto.

[[v18-32-18]]

^<<v18-32-18,18>>^ Tenho muito o que falar e já não consigo mais ficar calado.

[[v18-32-19]]

^<<v18-32-19,19>>^ Se eu não falar, sou capaz de estourar como um odre  cheio de vinho novo.

[[v18-32-20]]

^<<v18-32-20,20>>^ Não aguento mais; preciso desabafar, quero dar a minha opinião.

[[v18-32-21]]

^<<v18-32-21,21>>^ Não vou tomar partido nesta discussão e não vou adular ninguém.

[[v18-32-22]]

^<<v18-32-22,22>>^ Eu não costumo bajular; e, se bajulasse, o Criador logo me castigaria.

'''

xref:018-jo/018-jo-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-jo/018-jo-033.adoc#v18-33-0[Próximo Capítulo &#62;]