include::./index.adoc[]

[[v18-3-0]]
=== Jó, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-3-1]]

^<<v18-3-1,1>>^ Finalmente Jó quebrou o silêncio e amaldiçoou o dia do seu nascimento. Jó disse:

[[v18-3-2]]

^<<v18-3-2,2>>^ Finalmente Jó quebrou o silêncio e amaldiçoou o dia do seu nascimento. Jó disse:

[[v18-3-3]]

^<<v18-3-3,3>>^ "Maldito o dia em que nasci! Maldita a noite em que disseram: ‘Já nasceu! É homem!’

[[v18-3-4]]

^<<v18-3-4,4>>^ Que aquele dia vire escuridão! Que Deus, lá do alto, não se importe com ele, e que nunca mais a luz o ilumine!

[[v18-3-5]]

^<<v18-3-5,5>>^ Que a escuridão e as trevas o dominem; que as nuvens o cubram e apaguem a luz do sol!

[[v18-3-6]]

^<<v18-3-6,6>>^ Que aquela noite fique sempre escura e que desapareça do calendário!

[[v18-3-7]]

^<<v18-3-7,7>>^ Que seja solitária e triste aquela noite, e que nela não se escutem gritos de alegria!

[[v18-3-8]]

^<<v18-3-8,8>>^ Que seja amaldiçoada pelos feiticeiros, aqueles que têm poder sobre o monstro Leviatã !

[[v18-3-9]]

^<<v18-3-9,9>>^ Que escureçam as estrelas da sua manhã; que ela espere a luz, e a luz não venha; e que a sua madrugada não chegue,

[[v18-3-10]]

^<<v18-3-10,10>>^ pois ela deixou que minha mãe me desse à luz e não me poupou de todo este sofrimento!

[[v18-3-11]]

^<<v18-3-11,11>>^ "Por que não nasci morto? Por que não morri ao nascer?

[[v18-3-12]]

^<<v18-3-12,12>>^ Por que a minha mãe me segurou no colo? Por que me deu o seio e me amamentou?

[[v18-3-13]]

^<<v18-3-13,13>>^ Se eu tivesse morrido naquele momento, agora estaria dormindo, descansando em paz.

[[v18-3-14]]

^<<v18-3-14,14>>^ Estaria com reis e altas autoridades que reconstruíram palácios antigos

[[v18-3-15]]

^<<v18-3-15,15>>^ ou estaria com governadores que encheram as suas casas de ouro e de prata.

[[v18-3-16]]

^<<v18-3-16,16>>^ Se a minha mãe tivesse tido um aborto, às escondidas, eu não teria existido e seria como as crianças que nunca viram a luz do dia.

[[v18-3-17]]

^<<v18-3-17,17>>^ Na sepultura acaba a agitação dos maus, e ali repousam os que estão cansados.

[[v18-3-18]]

^<<v18-3-18,18>>^ Ali os prisioneiros descansam juntos e já não ouvem mais os gritos do capataz.

[[v18-3-19]]

^<<v18-3-19,19>>^ Ali estão os importantes e os humildes, e os escravos ficam livres dos seus donos.

[[v18-3-20]]

^<<v18-3-20,20>>^ "Por que os infelizes continuam vendo a luz? Por que deixar que vivam os que têm o coração amargurado?

[[v18-3-21]]

^<<v18-3-21,21>>^ Eles esperam a morte, e ela não vem, embora a desejem mais do que riquezas.

[[v18-3-22]]

^<<v18-3-22,22>>^ Eles ficam muito alegres e felizes quando por fim descem para a sepultura.

[[v18-3-23]]

^<<v18-3-23,23>>^ Deus os faz caminhar às cegas e os cerca de todos os lados.

[[v18-3-24]]

^<<v18-3-24,24>>^ "Em vez de comer, eu choro, e os meus gemidos se derramam como água.

[[v18-3-25]]

^<<v18-3-25,25>>^ Aquilo que eu temia foi o que aconteceu, e o que mais me dava medo me atingiu.

'''

xref:018-jo/018-jo-002.adoc#v18-2-0[&#60; Capítulo Anterior] | <<v18-3-0,Topo>> | xref:018-jo/018-jo-004.adoc#v18-4-0[Próximo Capítulo &#62;]