include::./index.adoc[]

[[v18-42-0]]
=== Jó, 42
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-42-1]]

^<<v18-42-1,1>>^ Então, em resposta ao Senhor , Jó disse:

[[v18-42-2]]

^<<v18-42-2,2>>^ "Eu reconheço que para ti nada é impossível e que nenhum dos teus planos pode ser impedido.

[[v18-42-3]]

^<<v18-42-3,3>>^ Tu me perguntaste como me atrevi a pôr em dúvida a tua sabedoria, visto que sou tão ignorante. É que falei de coisas que eu não compreendia, coisas que eram maravilhosas demais para mim e que eu não podia entender.

[[v18-42-4]]

^<<v18-42-4,4>>^ Tu me mandaste escutar o que estavas dizendo e responder às tuas perguntas.

[[v18-42-5]]

^<<v18-42-5,5>>^ Antes eu te conhecia só por ouvir falar, mas agora eu te vejo com os meus próprios olhos.

[[v18-42-6]]

^<<v18-42-6,6>>^ Por isso, estou envergonhado de tudo o que disse e me arrependo, sentado aqui no chão, num monte de cinzas."

[[v18-42-7]]

^<<v18-42-7,7>>^ Depois que acabou de falar com Jó, o Senhor  disse a Elifaz, da região de Temã: — Estou muito irado  com você e com os seus dois amigos, pois vocês não falaram a verdade a meu respeito, como o meu servo  Jó falou.

[[v18-42-8]]

^<<v18-42-8,8>>^ Agora peguem sete touros e sete carneiros, levem a Jó e ofereçam como sacrifício  em favor de vocês. O meu servo Jó orará por vocês, e eu aceitarei a sua oração e não os castigarei como merecem, embora vocês não tenham falado a verdade a meu respeito, como Jó falou.

[[v18-42-9]]

^<<v18-42-9,9>>^ Então Elifaz, que era da região de Temã, Bildade, que era da região de Sua, e Zofar, que era da região de Naamá, foram e fizeram o que o Senhor  havia mandado, e ele aceitou a oração de Jó.

[[v18-42-10]]

^<<v18-42-10,10>>^ Depois que Jó acabou de orar pelos seus três amigos, o Senhor  fez com que ele ficasse rico de novo e lhe deu em dobro tudo o que tinha tido antes.

[[v18-42-11]]

^<<v18-42-11,11>>^ Todos os seus irmãos e irmãs e todos os seus amigos foram visitá-lo e tomaram parte num banquete na casa dele. Falaram de como estavam tristes pelo que lhe havia acontecido e o consolaram por todas as desgraças que o Senhor  havia feito cair sobre ele. E cada um lhe deu dinheiro e um anel de ouro.

[[v18-42-12]]

^<<v18-42-12,12>>^ O Senhor  abençoou a última parte da vida de Jó mais do que a primeira. Ele chegou a ter catorze mil ovelhas, seis mil camelos, dois mil bois e mil jumentas.

[[v18-42-13]]

^<<v18-42-13,13>>^ Também foi pai de sete filhos e três filhas.

[[v18-42-14]]

^<<v18-42-14,14>>^ À primeira deu o nome de Jemima; à segunda chamou de Cássia; e à terceira, de Querém-Hapuque .

[[v18-42-15]]

^<<v18-42-15,15>>^ No mundo inteiro não havia mulheres tão lindas como as filhas de Jó. E o pai as fez herdeiras dos seus bens, junto com os seus irmãos.

[[v18-42-16]]

^<<v18-42-16,16>>^ Depois disso, Jó ainda viveu cento e quarenta anos, o bastante para ver netos e bisnetos.

[[v18-42-17]]

^<<v18-42-17,17>>^ E morreu bem velho.

'''

xref:018-jo/018-jo-041.adoc#v18-41-0[&#60; Capítulo Anterior] | <<v18-42-0,Topo>> | xref:019-salmos/019-salmos-001.adoc#v19-1-0[Próximo Capítulo &#62;]