include::./index.adoc[]

[[v18-14-0]]
=== Jó, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-14-1]]

^<<v18-14-1,1>>^ "Todos somos fracos desde o nascimento; a nossa vida é curta e muito agitada.

[[v18-14-2]]

^<<v18-14-2,2>>^ O ser humano é como a flor que se abre e logo murcha; como uma sombra ele passa e desaparece.

[[v18-14-3]]

^<<v18-14-3,3>>^ Nada somos; então por que nos dás atenção? E quem sou eu para que me leves ao tribunal?

[[v18-14-4]]

^<<v18-14-4,4>>^ O ser humano, que é impuro, nunca produz nada que seja puro.

[[v18-14-5]]

^<<v18-14-5,5>>^ Tu já marcaste quantos meses e dias cada um vai viver; isso está resolvido, e ninguém pode mudar.

[[v18-14-6]]

^<<v18-14-6,6>>^ Para de olhar para nós e deixa-nos em paz, até que o nosso dia chegue ao fim, como chega ao fim o dia de um trabalhador.

[[v18-14-7]]

^<<v18-14-7,7>>^ "Para uma árvore há esperança; se for cortada, brota de novo e torna a viver.

[[v18-14-8]]

^<<v18-14-8,8>>^ Mesmo que as suas raízes envelheçam, e o seu toco morra na terra,

[[v18-14-9]]

^<<v18-14-9,9>>^ basta um pouco de água, e ela brota, soltando galhos como uma planta nova.

[[v18-14-10]]

^<<v18-14-10,10>>^ Mas, quando alguém morre, está acabado; depois de entregar a alma, para onde vai?

[[v18-14-11]]

^<<v18-14-11,11>>^ "Como lagoas que secam, como rios que deixam de correr,

[[v18-14-12]]

^<<v18-14-12,12>>^ assim, enquanto o céu existir, todos vamos morrer. Vamos dormir o sono da morte, para nunca mais levantar.

[[v18-14-13]]

^<<v18-14-13,13>>^ "Ah! Se tu me pusesses no mundo dos mortos e ali me escondesses até que a tua ira  passasse e então marcasses um prazo para lembrares de mim!

[[v18-14-14]]

^<<v18-14-14,14>>^ Mas será que alguém tornará a viver depois de ter morrido? Eu, porém, esperarei por melhores tempos, até que as minhas lutas acabem.

[[v18-14-15]]

^<<v18-14-15,15>>^ Então me chamarás, e eu responderei; e tu ficarás contente comigo, pois me criaste.

[[v18-14-16]]

^<<v18-14-16,16>>^ Cuidarás para que eu não erre, em vez de ficares espiando para me veres pecar.

[[v18-14-17]]

^<<v18-14-17,17>>^ Esquecerás os meus pecados e apagarás os meus erros.

[[v18-14-18]]

^<<v18-14-18,18>>^ "Mas assim como as montanhas vão se desmoronando, e as rochas saem dos seus lugares;

[[v18-14-19]]

^<<v18-14-19,19>>^ e assim como as águas escavam as pedras, e as correntezas levam a terra, assim tu acabas com a esperança do ser humano.

[[v18-14-20]]

^<<v18-14-20,20>>^ Tu o derrotas, ele se vai para sempre, e mudas a sua aparência quando o despedes deste mundo.

[[v18-14-21]]

^<<v18-14-21,21>>^ Se os seus filhos recebem homenagens, ele não fica sabendo e, se caem na desgraça, ele não tem notícia.

[[v18-14-22]]

^<<v18-14-22,22>>^ Ele sente apenas as dores do seu próprio corpo e a agonia do seu espírito."

'''

xref:018-jo/018-jo-013.adoc#v18-13-0[&#60; Capítulo Anterior] | <<v18-14-0,Topo>> | xref:018-jo/018-jo-015.adoc#v18-15-0[Próximo Capítulo &#62;]