include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-13-1]]

^<<v18-13-1,1>>^ "Eu vi tudo isso com os meus próprios olhos; escutei tudo com os meus ouvidos e entendi.

[[v18-13-2]]

^<<v18-13-2,2>>^ Meus amigos, eu não sou menos do que vocês: eu também sei o que vocês sabem.

[[v18-13-3]]

^<<v18-13-3,3>>^ Mas quero falar com o Deus Todo-Poderoso e discutir com ele a minha questão.

[[v18-13-4]]

^<<v18-13-4,4>>^ Vocês disfarçam a sua ignorância com mentiras; são como médicos que não curam ninguém.

[[v18-13-5]]

^<<v18-13-5,5>>^ Ah! Se vocês ficassem calados, poderiam passar por sábios!

[[v18-13-6]]

^<<v18-13-6,6>>^ "Escutem agora a minha defesa, prestem atenção às minhas razões.

[[v18-13-7]]

^<<v18-13-7,7>>^ Será que para defender a Deus vocês vão dizer mentiras? Vão falar palavras enganosas a favor dele?

[[v18-13-8]]

^<<v18-13-8,8>>^ Será que vocês vão ficar do lado dele? Vão defender a causa dele no tribunal?

[[v18-13-9]]

^<<v18-13-9,9>>^ Por acaso, seria bom que ele os examinasse? Vocês pensam que podem enganar a Deus como enganam as pessoas?

[[v18-13-10]]

^<<v18-13-10,10>>^ Se vocês forem injustos, mesmo em segredo, ele certamente os repreenderá;

[[v18-13-11]]

^<<v18-13-11,11>>^ a sua grandeza os encherá de medo, e os seus terrores cairão sobre vocês.

[[v18-13-12]]

^<<v18-13-12,12>>^ As explicações antigas que vocês lembram são como cinza, não valem nada; as suas defesas são fracas como torres de barro.

[[v18-13-13]]

^<<v18-13-13,13>>^ "Fiquem calados, que eu vou falar, aconteça o que acontecer.

[[v18-13-14]]

^<<v18-13-14,14>>^ Estou pronto para arriscar a vida, pronto para enfrentar a morte.

[[v18-13-15]]

^<<v18-13-15,15>>^ Não tenho mais esperança, pois Deus me matará; mas assim mesmo defenderei a minha causa diante dele.

[[v18-13-16]]

^<<v18-13-16,16>>^ Talvez esta coragem venha a salvar-me, pois nenhuma pessoa má iria até a presença dele.

[[v18-13-17]]

^<<v18-13-17,17>>^ Ouçam com atenção o que estou dizendo; escutem as minhas explicações.

[[v18-13-18]]

^<<v18-13-18,18>>^ Estou pronto para defender a minha causa e sei que estou com a razão.

[[v18-13-19]]

^<<v18-13-19,19>>^ "Mas, se Deus disser: ‘Quem se atreve a discutir comigo no tribunal?’, então terei de me calar e morrer.

[[v18-13-20]]

^<<v18-13-20,20>>^ Ó Deus, eu te peço apenas duas coisas e assim não me esconderei de ti:

[[v18-13-21]]

^<<v18-13-21,21>>^ não me castigues mais e não me faças sentir tanto medo.

[[v18-13-22]]

^<<v18-13-22,22>>^ "Ó Deus, chama-me ao tribunal, e eu responderei; ou eu falarei primeiro, e tu responderás.

[[v18-13-23]]

^<<v18-13-23,23>>^ Quantas faltas e pecados cometi? De que erros e pecados sou acusado?

[[v18-13-24]]

^<<v18-13-24,24>>^ "Por que te escondes de mim? Por que me tratas como inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Eu sou como a folha levada pelo vento: por que me assustas? Sou como a palha seca: por que me persegues?

[[v18-13-26]]

^<<v18-13-26,26>>^ "Tu escreves duras acusações contra mim e queres que eu pague pelos erros da minha mocidade.

[[v18-13-27]]

^<<v18-13-27,27>>^ Prendes os meus pés com correntes, vigias todos os meus passos e examinas os rastos que deixo no caminho.

[[v18-13-28]]

^<<v18-13-28,28>>^ Assim, vou me acabando como madeira bichada, como uma roupa comida pela traça.

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]