include::./index.adoc[]

[[v18-16-0]]
=== Jó, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-16-1]]

^<<v18-16-1,1>>^ Então em resposta Jó disse:

[[v18-16-2]]

^<<v18-16-2,2>>^ "Já ouvi tudo isso antes; em vez de me consolarem, vocês me atormentam.

[[v18-16-3]]

^<<v18-16-3,3>>^ Será que essas palavras ocas não têm fim? Por que vocês não param de me provocar?

[[v18-16-4]]

^<<v18-16-4,4>>^ Se vocês estivessem no meu lugar, eu também poderia dizer o que estão dizendo. Eu balançaria a cabeça, com um jeito de sábio, e os esmagaria com um montão de palavras.

[[v18-16-5]]

^<<v18-16-5,5>>^ Ou poderia dizer palavras de ânimo e consolo para diminuir os seus sofrimentos.

[[v18-16-6]]

^<<v18-16-6,6>>^ Mas, se falo, a minha dor não se acalma, e, se me calo, o meu sofrimento não diminui.

[[v18-16-7]]

^<<v18-16-7,7>>^ "Tu, ó Deus, me deixaste sem forças e destruíste toda a minha família.

[[v18-16-8]]

^<<v18-16-8,8>>^ Tu me puseste numa prisão, e por isso me acusam. Virei pele e osso, e por isso os outros pensam que sou culpado.

[[v18-16-9]]

^<<v18-16-9,9>>^ "Na sua ira  Deus me arrasou completamente; ele olha para mim com ódio e, como uma fera, me persegue e ameaça.

[[v18-16-10]]

^<<v18-16-10,10>>^ Todos me ameaçam, abrem a boca para zombar de mim e me dão bofetadas para me humilhar.

[[v18-16-11]]

^<<v18-16-11,11>>^ Deus me entregou a homens perversos; ele me fez cair nas mãos de gente má.

[[v18-16-12]]

^<<v18-16-12,12>>^ Eu vivia em paz, mas ele me esmagou; Deus me pegou pela garganta e me quebrou. Ele fez de mim o seu alvo

[[v18-16-13]]

^<<v18-16-13,13>>^ e de todos os lados disparou as suas flechas; elas atravessaram os meus rins, sem dó nem piedade, e também a minha bílis correu pelo chão.

[[v18-16-14]]

^<<v18-16-14,14>>^ Como um soldado, ele avançou contra mim e me arrebentou todo, com golpes e mais golpes.

[[v18-16-15]]

^<<v18-16-15,15>>^ "Em sinal de tristeza, vesti uma roupa feita de pano grosseiro e, humilhado, sentei-me no pó.

[[v18-16-16]]

^<<v18-16-16,16>>^ Tenho chorado tanto, que o meu rosto está queimando, e estou com olheiras fundas e escuras.

[[v18-16-17]]

^<<v18-16-17,17>>^ No entanto, nunca fui violento, e as minhas orações sempre foram sinceras.

[[v18-16-18]]

^<<v18-16-18,18>>^ "Ó terra, não esconda as injustiças que fizeram contra mim! Não deixe que seja abafado o meu grito pedindo justiça!

[[v18-16-19]]

^<<v18-16-19,19>>^ Eu sei que no céu tenho quem me defenda; o meu advogado lá está.

[[v18-16-20]]

^<<v18-16-20,20>>^ Os meus amigos zombam de mim; e eu me volto para Deus com lágrimas nos olhos.

[[v18-16-21]]

^<<v18-16-21,21>>^ Assim como alguém defende o seu amigo, eu preciso de quem defenda o meu direito diante de Deus.

[[v18-16-22]]

^<<v18-16-22,22>>^ Os meus anos de vida estão contados, e eu vou pelo caminho que não tem retorno.

'''

xref:018-jo/018-jo-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:018-jo/018-jo-017.adoc#v18-17-0[Próximo Capítulo &#62;]