include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-36-1]]

^<<v18-36-1,1>>^ Eliú continuou a falar. Ele disse:

[[v18-36-2]]

^<<v18-36-2,2>>^ "Jó, tenha um pouco mais de paciência, pois ainda vou lhe mostrar que tenho outras coisas a dizer a favor de Deus.

[[v18-36-3]]

^<<v18-36-3,3>>^ Usarei os meus profundos conhecimentos para mostrar que Deus, o meu Criador, é justo.

[[v18-36-4]]

^<<v18-36-4,4>>^ Tudo o que vou dizer é verdade; quem está falando com você é realmente um sábio.

[[v18-36-5]]

^<<v18-36-5,5>>^ "Como Deus é poderoso! Ele não despreza ninguém. Deus sabe todas as coisas.

[[v18-36-6]]

^<<v18-36-6,6>>^ Ele não deixa que os maus continuem vivendo e sempre trata os pobres com justiça.

[[v18-36-7]]

^<<v18-36-7,7>>^ Deus protege os homens corretos, deixa que eles governem como reis e assim tenham uma alta posição para sempre.

[[v18-36-8]]

^<<v18-36-8,8>>^ Mas, se alguns são presos com correntes ou são amarrados com as cordas dos sofrimentos,

[[v18-36-9]]

^<<v18-36-9,9>>^ então Deus lhes mostra que isso é por causa do que fizeram, que é o castigo pelos seus pecados e pelo seu orgulho.

[[v18-36-10]]

^<<v18-36-10,10>>^ Deus faz com que escutem os seus avisos e manda que abandonem o pecado.

[[v18-36-11]]

^<<v18-36-11,11>>^ Se obedecem a Deus e o adoram, então têm paz e prosperidade até o fim da vida.

[[v18-36-12]]

^<<v18-36-12,12>>^ Mas, se não se importam com Deus, então morrem na ignorância, atravessam o rio e entram no mundo dos mortos .

[[v18-36-13]]

^<<v18-36-13,13>>^ "Aqueles que têm um coração perverso guardam raiva e, mesmo quando são castigados, não clamam pedindo socorro.

[[v18-36-14]]

^<<v18-36-14,14>>^ Desonram o seu corpo entre si e morrem em plena mocidade.

[[v18-36-15]]

^<<v18-36-15,15>>^ Mas Deus nos ensina por meio do sofrimento e usa a aflição para abrir os nossos olhos.

[[v18-36-16]]

^<<v18-36-16,16>>^ "Jó, Deus o livrou dos perigos e o deixou viver em segurança. À sua mesa sempre se comeu do bom e do melhor.

[[v18-36-17]]

^<<v18-36-17,17>>^ Mas você foi julgado e condenado e agora está recebendo o castigo que merece.

[[v18-36-18]]

^<<v18-36-18,18>>^ Cuidado, não aceite dinheiro para torcer a justiça, não deixe que as muitas riquezas o seduzam.

[[v18-36-19]]

^<<v18-36-19,19>>^ Não adianta nada gritar pedindo socorro; todo o seu poder não tem nenhum valor agora.

[[v18-36-20]]

^<<v18-36-20,20>>^ Não fique desejando que chegue a noite em que as nações serão destruídas.

[[v18-36-21]]

^<<v18-36-21,21>>^ Você está sofrendo por causa da sua maldade; cuidado, não se volte para ela!

[[v18-36-22]]

^<<v18-36-22,22>>^ "Como é grande o poder de Deus! Quem é capaz de governar tão bem como ele?

[[v18-36-23]]

^<<v18-36-23,23>>^ Ninguém pode dar ordens a Deus, nem acusá-lo de praticar o mal.

[[v18-36-24]]

^<<v18-36-24,24>>^ O mundo inteiro o louva pelo que ele faz, e você também não esqueça de louvá-lo.

[[v18-36-25]]

^<<v18-36-25,25>>^ Mesmo de longe todos nós vemos e admiramos o que Deus está fazendo.

[[v18-36-26]]

^<<v18-36-26,26>>^ Ele é grande demais para que o possamos conhecer; nós não podemos calcular quantos anos já viveu.

[[v18-36-27]]

^<<v18-36-27,27>>^ "Deus faz com que a água da terra suba para um depósito e depois a transforma em gotas de chuva.

[[v18-36-28]]

^<<v18-36-28,28>>^ As nuvens derramam a água, que cai em aguaceiros sobre a terra.

[[v18-36-29]]

^<<v18-36-29,29>>^ Quem entende o movimento das nuvens ou o barulho dos trovões no céu, onde Deus mora?

[[v18-36-30]]

^<<v18-36-30,30>>^ Deus espalha relâmpagos em volta de si, mas o fundo do mar continua escuro.

[[v18-36-31]]

^<<v18-36-31,31>>^ É assim que Deus alimenta os povos e lhes dá comida à vontade.

[[v18-36-32]]

^<<v18-36-32,32>>^ Ele pega o raio com as mãos e manda que atinja o alvo.

[[v18-36-33]]

^<<v18-36-33,33>>^ O gado sente que a tempestade está perto, e o trovão avisa que ela vem aí.

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]