include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-22-1]]

^<<v18-22-1,1>>^ Então Elifaz, da região de Temã, em resposta disse:

[[v18-22-2]]

^<<v18-22-2,2>>^ "Será que uma pessoa, por mais sábia que seja, poderia ser útil para Deus?

[[v18-22-3]]

^<<v18-22-3,3>>^ Será que interessa ao Todo-Poderoso que você seja honesto? Que lucro tem ele se você é correto em todas as coisas?

[[v18-22-4]]

^<<v18-22-4,4>>^ Se ele o castiga e o chama para prestar contas, não é porque você o adora com todo o respeito,

[[v18-22-5]]

^<<v18-22-5,5>>^ mas sim porque cometeu muitos pecados, e as suas maldades não têm conta.

[[v18-22-6]]

^<<v18-22-6,6>>^ Como garantia de um pequeno empréstimo, você ficava com as roupas dos seus patrícios e assim os deixava nus.

[[v18-22-7]]

^<<v18-22-7,7>>^ Você não dava água para as pessoas cansadas nem comida aos que tinham fome.

[[v18-22-8]]

^<<v18-22-8,8>>^ Você usou a sua posição e o seu poder para se tornar o dono da terra.

[[v18-22-9]]

^<<v18-22-9,9>>^ Você roubou e maltratou os órfãos e nunca ajudou as viúvas.

[[v18-22-10]]

^<<v18-22-10,10>>^ Por isso, agora você está cercado de perigos, e, de repente, o medo toma conta de você.

[[v18-22-11]]

^<<v18-22-11,11>>^ A escuridão é tanta, que você não enxerga nada, e uma enchente o arrasta.

[[v18-22-12]]

^<<v18-22-12,12>>^ "Deus está nas alturas do céu; ele olha para baixo e vê as estrelas, embora elas estejam lá no alto.

[[v18-22-13]]

^<<v18-22-13,13>>^ Mas você pergunta: ‘Será que Deus sabe alguma coisa? As nuvens escuras ficam no meio; como é que ele pode nos julgar?’

[[v18-22-14]]

^<<v18-22-14,14>>^ Jó, você acha que as grossas nuvens não deixam que Deus nos veja, quando ele está passeando pelo céu?

[[v18-22-15]]

^<<v18-22-15,15>>^ "Será que você quer andar nos caminhos que os maus têm seguido desde os tempos antigos?

[[v18-22-16]]

^<<v18-22-16,16>>^ Eles morreram de repente, como se fossem levados por uma enchente.

[[v18-22-17]]

^<<v18-22-17,17>>^ A Deus eles diziam: ‘Deixa-nos em paz!’ E comentavam: ‘O que pode o Todo-Poderoso fazer em nosso favor?’

[[v18-22-18]]

^<<v18-22-18,18>>^ Foi Deus quem encheu de coisas boas as casas dos maus, porém eu não quero pensar como eles.

[[v18-22-19]]

^<<v18-22-19,19>>^ As pessoas honestas ficam alegres, e as corretas riem,

[[v18-22-20]]

^<<v18-22-20,20>>^ ao verem que as riquezas dos maus são destruídas e que as sobras são devoradas pelo fogo.

[[v18-22-21]]

^<<v18-22-21,21>>^ "Jó, faça as pazes com Deus, deixe de tratá-lo como inimigo, e assim ele dará a você tudo o que há de bom.

[[v18-22-22]]

^<<v18-22-22,22>>^ Deixe que Deus o ensine e guarde as palavras dele no seu coração.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se você voltar para o Todo-Poderoso e se humilhar, se você acabar com a maldade que há na sua casa,

[[v18-22-24]]

^<<v18-22-24,24>>^ se o ouro mais precioso não tiver valor para você e for como o pó ou as pedrinhas do ribeirão,

[[v18-22-25]]

^<<v18-22-25,25>>^ então o Todo-Poderoso será o seu ouro puro, será a sua prata mais preciosa.

[[v18-22-26]]

^<<v18-22-26,26>>^ Ele será a sua alegria, e você poderá olhar para ele com confiança.

[[v18-22-27]]

^<<v18-22-27,27>>^ Ele ouvirá as suas orações, e você lhe dará o que prometer.

[[v18-22-28]]

^<<v18-22-28,28>>^ Tudo o que você fizer dará certo, e a luz brilhará no seu caminho.

[[v18-22-29]]

^<<v18-22-29,29>>^ Deus rebaixa os orgulhosos, mas salva os humildes.

[[v18-22-30]]

^<<v18-22-30,30>>^ Ele o salvará se você for inocente, se for correto em tudo o que fizer."

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]