include::./index.adoc[]

[[v18-2-0]]
=== Jó, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-2-1]]

^<<v18-2-1,1>>^ Chegou de novo o dia em que os servidores celestiais vieram apresentar-se diante de Deus, o Senhor , e Satanás também veio no meio deles.

[[v18-2-2]]

^<<v18-2-2,2>>^ O Senhor  perguntou: — De onde você vem vindo? Satanás respondeu: — Estive dando uma volta pela terra, passeando por aqui e por ali.

[[v18-2-3]]

^<<v18-2-3,3>>^ Aí o Senhor  disse: — Você viu o meu servo  Jó? No mundo inteiro não há ninguém tão bom e tão honesto como ele. Ele me teme  e procura não fazer nada que seja errado. No entanto, você me convenceu, e eu o deixei desgraçar Jó, embora não houvesse motivo para isso. Mesmo assim, ele continua firme e sincero como sempre.

[[v18-2-4]]

^<<v18-2-4,4>>^ Satanás respondeu: — É só tocar na pele dele para ver o que acontece. As pessoas não se importam de perder tudo desde que conservem a própria vida.

[[v18-2-5]]

^<<v18-2-5,5>>^ Agora, se estenderes a mão e ferires o corpo dele, verás como ele, sem nenhum respeito, te amaldiçoará.

[[v18-2-6]]

^<<v18-2-6,6>>^ O Senhor  disse a Satanás: — Pois bem. Faça o que quiser com Jó, mas não o mate.

[[v18-2-7]]

^<<v18-2-7,7>>^ Aí Satanás saiu da presença do Senhor  e fez com que o corpo de Jó ficasse coberto de feridas horríveis, desde as solas dos pés até o alto da cabeça.

[[v18-2-8]]

^<<v18-2-8,8>>^ Jó sentou-se num monte de cinza e pegou um caco para se coçar.

[[v18-2-9]]

^<<v18-2-9,9>>^ E a mulher dele disse: — Você ainda continua sendo bom? Amaldiçoe a Deus e morra!

[[v18-2-10]]

^<<v18-2-10,10>>^ Jó respondeu: — Você está dizendo uma bobagem! Se recebemos de Deus as coisas boas, por que não vamos aceitar também as desgraças? Assim, apesar de tudo, Jó não pecou, nem disse uma só palavra contra Deus.

[[v18-2-11]]

^<<v18-2-11,11>>^ Jó tinha três amigos: Elifaz, da região de Temã; Bildade, da região de Sua; e Zofar, da região de Naamá. Eles ficaram sabendo das desgraças que haviam acontecido a Jó e combinaram fazer-lhe uma visita para falar de como estavam tristes pelo que lhe havia acontecido e para consolá-lo.

[[v18-2-12]]

^<<v18-2-12,12>>^ De longe eles não reconheceram Jó, mas depois, quando viram que era ele, começaram a chorar e a gritar. Em sinal de tristeza, rasgaram as suas roupas e jogaram pó para o ar e sobre a cabeça.

[[v18-2-13]]

^<<v18-2-13,13>>^ Em seguida sentaram-se no chão ao lado dele e ficaram ali sete dias e sete noites; e não disseram nada, pois viam que Jó estava sofrendo muito.

'''

xref:018-jo/018-jo-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-jo/018-jo-003.adoc#v18-3-0[Próximo Capítulo &#62;]