include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-11-1]]

^<<v18-11-1,1>>^ Então Zofar, da região de Naamá, em resposta disse:

[[v18-11-2]]

^<<v18-11-2,2>>^ "Será que todo esse palavrório vai ficar sem resposta? Por acaso, quem fala muito é quem tem razão?

[[v18-11-3]]

^<<v18-11-3,3>>^ Jó, você pensa que não temos resposta? Pensa que as suas zombarias vão nos fazer calar a boca?

[[v18-11-4]]

^<<v18-11-4,4>>^ Você diz que o seu modo de pensar está certo e afirma que é inocente diante de Deus.

[[v18-11-5]]

^<<v18-11-5,5>>^ Eu gostaria que Deus falasse e lhe desse uma resposta!

[[v18-11-6]]

^<<v18-11-6,6>>^ Ele lhe ensinaria os segredos da sabedoria, pois há mistérios na explicação das coisas. Assim, você veria que Deus o está castigando menos do que você merece.

[[v18-11-7]]

^<<v18-11-7,7>>^ "Você pensa que pode descobrir os segredos de Deus e conhecer completamente o Todo-Poderoso?

[[v18-11-8]]

^<<v18-11-8,8>>^ O céu não é limite para Deus, mas você não pode chegar até lá; Deus conhece o mundo dos mortos , mas você não conhece.

[[v18-11-9]]

^<<v18-11-9,9>>^ Ele é maior do que a terra, mais vasto do que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ Se Deus passar e prender alguém e o levar para ser julgado, quem o poderá impedir?

[[v18-11-11]]

^<<v18-11-11,11>>^ Deus conhece as pessoas que não valem nada; ele nunca deixa de ver as suas maldades.

[[v18-11-12]]

^<<v18-11-12,12>>^ No dia em que os jumentos selvagens nascerem mansos, as pessoas sem juízo vão ter sabedoria.

[[v18-11-13]]

^<<v18-11-13,13>>^ "Jó, vire o coração para Deus e ore com as mãos estendidas para ele.

[[v18-11-14]]

^<<v18-11-14,14>>^ Abandone o pecado que mancha as suas mãos e não deixe que a maldade more na sua casa.

[[v18-11-15]]

^<<v18-11-15,15>>^ Então você andará de cabeça erguida, puro, firme e sem medo.

[[v18-11-16]]

^<<v18-11-16,16>>^ Você não lembrará dos seus sofrimentos, que serão como águas passadas que a gente esquece.

[[v18-11-17]]

^<<v18-11-17,17>>^ A sua vida brilhará mais do que o sol do meio-dia, e as suas horas mais escuras serão claras como o amanhecer.

[[v18-11-18]]

^<<v18-11-18,18>>^ Você viverá seguro e cheio de esperança; Deus o protegerá, e você dormirá tranquilo.

[[v18-11-19]]

^<<v18-11-19,19>>^ Quando você estiver descansando, nada o assustará; e muita gente virá lhe pedir ajuda.

[[v18-11-20]]

^<<v18-11-20,20>>^ Porém os maus olharão em redor desesperados e não acharão lugar para onde fugir; para eles a morte será a única esperança."

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]