include::./index.adoc[]

[[v18-6-0]]
=== Jó, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-6-1]]

^<<v18-6-1,1>>^ Então em resposta Jó disse:

[[v18-6-2]]

^<<v18-6-2,2>>^ "Ah! Se a minha desgraça e os meus sofrimentos fossem postos numa balança,

[[v18-6-3]]

^<<v18-6-3,3>>^ com certeza pesariam mais do que a areia do mar. E foi por isso que falei com violência.

[[v18-6-4]]

^<<v18-6-4,4>>^ As flechas venenosas do Deus Todo-Poderoso estão fincadas em mim, e o veneno entra na minha alma. Com os seus ataques, Deus me tem enchido de terror.

[[v18-6-5]]

^<<v18-6-5,5>>^ O jumento fica contente quando come capim, e o boi não reclama quando tem pasto.

[[v18-6-6]]

^<<v18-6-6,6>>^ Mas quem gosta de comida sem sal? Que gosto tem a clara do ovo?

[[v18-6-7]]

^<<v18-6-7,7>>^ Não tenho apetite para comer essas coisas, e tudo o que como me faz mal.

[[v18-6-8]]

^<<v18-6-8,8>>^ "Ah! Se Deus me desse o que estou pedindo! Ah! Se Deus respondesse à minha oração!

[[v18-6-9]]

^<<v18-6-9,9>>^ Então ele me tiraria a vida; ele me atacaria e acabaria comigo!

[[v18-6-10]]

^<<v18-6-10,10>>^ Se eu soubesse que Deus faria isso, daria pulos de alegria, mesmo sofrendo muita dor. Pois Deus é santo, e eu nunca fui contra as suas decisões.

[[v18-6-11]]

^<<v18-6-11,11>>^ Onde estão as minhas forças para resistir? Por que viver, se não há esperança?

[[v18-6-12]]

^<<v18-6-12,12>>^ Será que sou forte como a pedra? Será que o meu corpo é de bronze?

[[v18-6-13]]

^<<v18-6-13,13>>^ Não sou capaz de me ajudar a mim mesmo, e não há ninguém que me socorra.

[[v18-6-14]]

^<<v18-6-14,14>>^ "Uma pessoa desesperada merece a compaixão dos seus amigos, mesmo que tenha deixado de temer ao Deus Todo-Poderoso.

[[v18-6-15]]

^<<v18-6-15,15>>^ Mas eu não pude contar com vocês, meus amigos, que me desapontaram como um riacho que seca no verão.

[[v18-6-16]]

^<<v18-6-16,16>>^ Primeiro ele está cheio de gelo e de neve,

[[v18-6-17]]

^<<v18-6-17,17>>^ mas depois vira água, que vai sumindo no calor, até que no fim o seu leito fica seco e duro.

[[v18-6-18]]

^<<v18-6-18,18>>^ As caravanas  se perdem procurando água; avançam pelo deserto e ali morrem.

[[v18-6-19]]

^<<v18-6-19,19>>^ Aquelas que vêm de Temá e de Sabá procuram esses ribeirões, cheias de esperança,

[[v18-6-20]]

^<<v18-6-20,20>>^ porém, quando chegam, todos ficam desapontados, e a sua esperança morre ali.

[[v18-6-21]]

^<<v18-6-21,21>>^ Vocês são como esses ribeirões; vocês veem a minha miséria e ficam com medo.

[[v18-6-22]]

^<<v18-6-22,22>>^ Por acaso, pedi que vocês me dessem qualquer coisa? Ou que me oferecessem um presente?

[[v18-6-23]]

^<<v18-6-23,23>>^ Será que pedi que me salvassem de um inimigo ou que me livrassem das mãos dos bandidos?

[[v18-6-24]]

^<<v18-6-24,24>>^ "Ensinem-me, que eu ficarei calado; mostrem os erros que cometi.

[[v18-6-25]]

^<<v18-6-25,25>>^ Quem fala a verdade convence, mas a acusação de vocês não prova nada.

[[v18-6-26]]

^<<v18-6-26,26>>^ Será que vocês querem criticar o que eu digo, querem tratar as palavras de um homem desesperado como se elas fossem vento?

[[v18-6-27]]

^<<v18-6-27,27>>^ Vocês seriam capazes de vender um órfão em leilão; vocês venderiam até mesmo um amigo!

[[v18-6-28]]

^<<v18-6-28,28>>^ Olhem bem nos meus olhos e digam se estou mentindo.

[[v18-6-29]]

^<<v18-6-29,29>>^ Retirem o que disseram; não sejam injustos. Não me condenem; eu estou com a razão.

[[v18-6-30]]

^<<v18-6-30,30>>^ Vocês pensam que sou mentiroso? Será que não sei o que é certo e o que é errado?

'''

xref:018-jo/018-jo-005.adoc#v18-5-0[&#60; Capítulo Anterior] | <<v18-6-0,Topo>> | xref:018-jo/018-jo-007.adoc#v18-7-0[Próximo Capítulo &#62;]