include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-33-1]]

^<<v18-33-1,1>>^ "Por isso, Jó, escute as minhas palavras e preste atenção em tudo o que vou dizer.

[[v18-33-2]]

^<<v18-33-2,2>>^ Estou pronto para começar e vou falar o que penso.

[[v18-33-3]]

^<<v18-33-3,3>>^ Darei a minha opinião com franqueza; as minhas palavras serão sinceras, vindas do coração.

[[v18-33-4]]

^<<v18-33-4,4>>^ Pois foi o Espírito de Deus que me fez, e é o sopro do Todo-Poderoso que me dá vida.

[[v18-33-5]]

^<<v18-33-5,5>>^ "Responda-me, se for capaz; prepare-se para discutir comigo.

[[v18-33-6]]

^<<v18-33-6,6>>^ Para Deus você e eu somos iguais; eu também fui formado do barro.

[[v18-33-7]]

^<<v18-33-7,7>>^ Por isso, não tenha medo de mim; a minha intenção não é esmagar você.

[[v18-33-8]]

^<<v18-33-8,8>>^ "Creio que ouvi você dizer o seguinte:

[[v18-33-9]]

^<<v18-33-9,9>>^ ‘Não sou culpado; não fiz nada de errado. Estou inocente; não cometi nenhum pecado.

[[v18-33-10]]

^<<v18-33-10,10>>^ É Deus quem inventa motivos para me atacar; ele me trata como se eu fosse um inimigo.

[[v18-33-11]]

^<<v18-33-11,11>>^ Ele amarrou os meus pés com correntes e fica vigiando tudo o que eu faço.’

[[v18-33-12]]

^<<v18-33-12,12>>^ "Mas eu lhe digo que você não tem razão, pois Deus é maior do que as criaturas humanas.

[[v18-33-13]]

^<<v18-33-13,13>>^ Por que você acusa Deus, afirmando que ele não dá atenção às nossas queixas?

[[v18-33-14]]

^<<v18-33-14,14>>^ Deus fala de várias maneiras, porém nós não lhe damos atenção.

[[v18-33-15]]

^<<v18-33-15,15>>^ De noite, na cama, quando dormimos um sono profundo, ele fala por meio de sonhos ou de visões.

[[v18-33-16]]

^<<v18-33-16,16>>^ Deus fala aos nossos ouvidos, e os seus avisos nos enchem de medo.

[[v18-33-17]]

^<<v18-33-17,17>>^ Ele fala com a gente para que deixemos de pecar e para que não nos tornemos orgulhosos.

[[v18-33-18]]

^<<v18-33-18,18>>^ Assim, ele nos livra da morte e não deixa que nos joguem na sepultura.

[[v18-33-19]]

^<<v18-33-19,19>>^ "Outras vezes, Deus castiga com doenças e com fortes dores que não passam.

[[v18-33-20]]

^<<v18-33-20,20>>^ O doente perde o apetite e não quer nem ver as comidas mais gostosas.

[[v18-33-21]]

^<<v18-33-21,21>>^ Ele emagrece, vai se acabando e no fim vira pele e osso.

[[v18-33-22]]

^<<v18-33-22,22>>^ Ele está às portas da morte; logo será levado para a sepultura.

[[v18-33-23]]

^<<v18-33-23,23>>^ "Pode ser que ele venha a ser socorrido por um anjo, um dos milhares de anjos de Deus, que ensinam a gente a fazer o que é certo.

[[v18-33-24]]

^<<v18-33-24,24>>^ O anjo terá pena dele e pedirá a Deus: ‘Solta-o! Ele não deve descer ao mundo dos mortos . Aqui está o pagamento do seu resgate.’

[[v18-33-25]]

^<<v18-33-25,25>>^ Então ele terá saúde novamente, e o seu corpo será forte como era na juventude.

[[v18-33-26]]

^<<v18-33-26,26>>^ Quando orar, Deus o atenderá. Ele o adorará com alegria, e Deus o aceitará de novo como um homem direito.

[[v18-33-27]]

^<<v18-33-27,27>>^ Ele dirá a todos: ‘Pequei, cometi injustiças, mas Deus não me castigou.

[[v18-33-28]]

^<<v18-33-28,28>>^ Ele me salvou da morte; eu ainda posso ver a luz.’

[[v18-33-29]]

^<<v18-33-29,29>>^ "Deus faz tudo isso com a gente e faz várias vezes.

[[v18-33-30]]

^<<v18-33-30,30>>^ Ele não deixa que morramos, e assim continuamos a ser iluminados pela luz da vida.

[[v18-33-31]]

^<<v18-33-31,31>>^ "Agora, Jó, escute com atenção; fique calado, pois vou falar.

[[v18-33-32]]

^<<v18-33-32,32>>^ Se você tem alguma coisa a dizer, responda, pois eu gostaria de lhe dar razão.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não, fique calado e escute, que eu lhe ensinarei como ser sábio."

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]