include::./index.adoc[]

[[v18-30-0]]
=== Jó, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-30-1]]

^<<v18-30-1,1>>^ "Mas agora homens mais moços do que eu zombam de mim. Os pais deles não valem nada; eu não poria essa gente nem com os cachorros que cuidam do meu rebanho.

[[v18-30-2]]

^<<v18-30-2,2>>^ De que me serviria a força dos seus braços? São homens magros,

[[v18-30-3]]

^<<v18-30-3,3>>^ enfraquecidos de tanto passar fome e miséria. À noite, na solidão de lugares desertos, eles têm de roer raízes secas.

[[v18-30-4]]

^<<v18-30-4,4>>^ Pegam ervas e cascas de árvores e se alimentam de raízes que não servem para comer.

[[v18-30-5]]

^<<v18-30-5,5>>^ São expulsos do meio das pessoas, que os espantam, aos gritos, como se eles fossem ladrões.

[[v18-30-6]]

^<<v18-30-6,6>>^ Têm de morar em barrancos medonhos, em cavernas ou nas rochas.

[[v18-30-7]]

^<<v18-30-7,7>>^ Uivam no meio das moitas e se ajuntam debaixo dos espinheiros.

[[v18-30-8]]

^<<v18-30-8,8>>^ Raça inútil, gente sem nome, são enxotados do país.

[[v18-30-9]]

^<<v18-30-9,9>>^ "Mas agora essa gente vem e zomba de mim; para eles eu não passo de uma piada.

[[v18-30-10]]

^<<v18-30-10,10>>^ Sentem nojo de mim e se afastam e chegam até a me cuspir na cara.

[[v18-30-11]]

^<<v18-30-11,11>>^ Deus me enfraqueceu e me humilhou, e por isso, furiosos, eles se viram contra mim.

[[v18-30-12]]

^<<v18-30-12,12>>^ Essa raça de gente ruim me ataca, me faz correr e procura acabar comigo.

[[v18-30-13]]

^<<v18-30-13,13>>^ Eles não deixam que eu fuja, procuram me destruir, e ninguém os faz parar.

[[v18-30-14]]

^<<v18-30-14,14>>^ Entram por uma brecha da muralha e no meio das ruínas se jogam contra mim.

[[v18-30-15]]

^<<v18-30-15,15>>^ Eu fico apavorado. A minha honra foi como que varrida para longe pelo vento; a minha prosperidade passou como se fosse uma nuvem.

[[v18-30-16]]

^<<v18-30-16,16>>^ "Agora já não tenho vontade de viver; o desespero tomou conta de mim.

[[v18-30-17]]

^<<v18-30-17,17>>^ De noite os ossos me doem muito; a dor que me atormenta não para.

[[v18-30-18]]

^<<v18-30-18,18>>^ Deus me agarrou pela garganta com tanta violência, que desarrumou a minha roupa.

[[v18-30-19]]

^<<v18-30-19,19>>^ Ele me atirou na lama; eu não valho mais do que o pó ou a cinza.

[[v18-30-20]]

^<<v18-30-20,20>>^ "Ó Deus, eu clamo pedindo a tua ajuda, e não me respondes; eu oro a ti, e não te importas comigo.

[[v18-30-21]]

^<<v18-30-21,21>>^ Tu me tratas com crueldade e me persegues com todo o teu poder.

[[v18-30-22]]

^<<v18-30-22,22>>^ Fazes com que o vento me carregue e numa tempestade violenta me jogas de um lado para outro.

[[v18-30-23]]

^<<v18-30-23,23>>^ Bem sei que me levarás à Terra da Morte, o lugar de encontro marcado para todos os vivos.

[[v18-30-24]]

^<<v18-30-24,24>>^ Por que atacas um homem arruinado, que não pode fazer nada, a não ser pedir piedade?

[[v18-30-25]]

^<<v18-30-25,25>>^ Por acaso, não chorei com as pessoas aflitas? Será que não tive pena dos pobres?

[[v18-30-26]]

^<<v18-30-26,26>>^ Eu esperava a felicidade, e veio a desgraça; eu aguardava a luz, e chegou a escuridão.

[[v18-30-27]]

^<<v18-30-27,27>>^ "O meu coração está agitado e não descansa; só tenho vivido dias de aflição.

[[v18-30-28]]

^<<v18-30-28,28>>^ Levo uma vida triste, como um dia sem sol; eu me levanto diante de todos e peço ajuda.

[[v18-30-29]]

^<<v18-30-29,29>>^ A minha voz é um gemido triste, como os uivos do lobo ou os gritos do avestruz.

[[v18-30-30]]

^<<v18-30-30,30>>^ A minha pele está ficando preta, e o meu corpo queima de febre.

[[v18-30-31]]

^<<v18-30-31,31>>^ Eu costumava ouvir a música alegre de liras  e flautas, mas agora só escuto gente chorando e soluçando.

'''

xref:018-jo/018-jo-029.adoc#v18-29-0[&#60; Capítulo Anterior] | <<v18-30-0,Topo>> | xref:018-jo/018-jo-031.adoc#v18-31-0[Próximo Capítulo &#62;]