include::./index.adoc[]

[[v18-26-0]]
=== Jó, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v18-26-1]]

^<<v18-26-1,1>>^ Então Jó em resposta disse:

[[v18-26-2]]

^<<v18-26-2,2>>^ "Bildade, eu estou fraco, sem forças; como você me ajuda e me consola!…

[[v18-26-3]]

^<<v18-26-3,3>>^ Como você é bom para dar conselhos e gastar a sua sabedoria com um ignorante como eu!

[[v18-26-4]]

^<<v18-26-4,4>>^ Quem foi que o ajudou a dizer essas palavras? Quem o inspirou a falar assim?"

[[v18-26-5]]

^<<v18-26-5,5>>^ "Os mortos tremem de medo nas águas debaixo da terra.

[[v18-26-6]]

^<<v18-26-6,6>>^ Para Deus o mundo dos mortos  é aberto; não há cobertura que o impeça de ver o que lá acontece.

[[v18-26-7]]

^<<v18-26-7,7>>^ Deus estendeu o céu sobre o vazio e suspendeu a terra por cima do nada.

[[v18-26-8]]

^<<v18-26-8,8>>^ Ele prende a água nas nuvens, e elas não se rasgam com o seu peso.

[[v18-26-9]]

^<<v18-26-9,9>>^ Ele cobre a cara da lua cheia, estendendo sobre ela uma nuvem.

[[v18-26-10]]

^<<v18-26-10,10>>^ Deus separou a luz da escuridão por meio de um círculo desenhado no mar.

[[v18-26-11]]

^<<v18-26-11,11>>^ Quando ele ameaça as colunas que sustentam o céu, elas se assustam e tremem de medo.

[[v18-26-12]]

^<<v18-26-12,12>>^ Com o seu poder, Deus dominou o Mar ; com a sua inteligência, derrotou o monstro Raabe .

[[v18-26-13]]

^<<v18-26-13,13>>^ Com o seu sopro, Deus limpou o céu e, com a sua mão, matou a Serpente fugitiva .

[[v18-26-14]]

^<<v18-26-14,14>>^ Mas essas coisas são apenas uma amostra, um eco bem fraco do que Deus é capaz de fazer. Quem pode compreender a verdadeira grandeza do seu poder?"

'''

xref:018-jo/018-jo-025.adoc#v18-25-0[&#60; Capítulo Anterior] | <<v18-26-0,Topo>> | xref:018-jo/018-jo-027.adoc#v18-27-0[Próximo Capítulo &#62;]