include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v54-2-1]]

^<<v54-2-1,1>>^ Em primeiro lugar peço que sejam feitos orações, pedidos, súplicas e ações de graças a Deus em favor de todas as pessoas.

[[v54-2-2]]

^<<v54-2-2,2>>^ Orem pelos reis e por todos os outros que têm autoridade, para que possamos viver uma vida calma e pacífica, com dedicação a Deus e respeito aos outros.

[[v54-2-3]]

^<<v54-2-3,3>>^ Isso é bom, e Deus, o nosso Salvador, gosta disso.

[[v54-2-4]]

^<<v54-2-4,4>>^ Ele quer que todos sejam salvos e venham a conhecer a verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Pois existe um só Deus e uma só pessoa que une Deus com os seres humanos — o ser humano Cristo Jesus,

[[v54-2-6]]

^<<v54-2-6,6>>^ que deu a sua vida para que todos fiquem livres dos seus pecados. Esta foi a prova, dada no tempo certo, de que Deus quer que todos sejam salvos.

[[v54-2-7]]

^<<v54-2-7,7>>^ E eu fui escolhido como apóstolo  e mestre dos não judeus para anunciar a mensagem da fé e da verdade. Eu não estou mentindo; estou dizendo a verdade.

[[v54-2-8]]

^<<v54-2-8,8>>^ Quero que em todos os lugares os homens orem, homens dedicados a Deus; e que, ao orarem, eles levantem as mãos, sem ódio e sem brigas.

[[v54-2-9]]

^<<v54-2-9,9>>^ Quero também que as mulheres sejam sensatas e usem roupas decentes e simples. Que elas se enfeitem, mas não com penteados complicados, nem com joias de ouro ou de pérolas, nem com roupas caras!

[[v54-2-10]]

^<<v54-2-10,10>>^ Que se enfeitem com boas ações, como devem fazer as mulheres que dizem que são dedicadas a Deus!

[[v54-2-11]]

^<<v54-2-11,11>>^ As mulheres devem aprender em silêncio e com toda a humildade.

[[v54-2-12]]

^<<v54-2-12,12>>^ Não permito que as mulheres ensinem ou tenham autoridade sobre os homens; elas devem ficar em silêncio.

[[v54-2-13]]

^<<v54-2-13,13>>^ Pois Adão foi criado primeiro, e depois Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ E não foi Adão quem foi enganado; a mulher é que foi enganada e desobedeceu à lei  de Deus.

[[v54-2-15]]

^<<v54-2-15,15>>^ Mas a mulher será salva tendo filhos se ela, com pureza, continuar na fé, no amor e na dedicação a Deus.

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]