include::./index.adoc[]

[[v54-5-0]]
=== 1 Timóteo, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v54-5-1]]

^<<v54-5-1,1>>^ Não repreenda um homem mais velho, mas o aconselhe como se ele fosse o seu pai. Trate os homens mais jovens como irmãos,

[[v54-5-2]]

^<<v54-5-2,2>>^ as mulheres idosas, como mães e as mulheres jovens, como irmãs, com toda a pureza.

[[v54-5-3]]

^<<v54-5-3,3>>^ Cuide das viúvas que não tenham ninguém para ajudá-las.

[[v54-5-4]]

^<<v54-5-4,4>>^ Mas, se alguma viúva tem filhos ou netos, são eles que devem primeiro aprender a cumprir os seus deveres religiosos, cuidando da sua própria família. Assim eles pagarão o que receberam dos seus pais e avós, pois Deus gosta disso.

[[v54-5-5]]

^<<v54-5-5,5>>^ A verdadeira viúva, aquela que não tem ninguém para cuidar dela, põe a sua esperança em Deus e ora, de dia e de noite, pedindo a ajuda dele.

[[v54-5-6]]

^<<v54-5-6,6>>^ Porém a viúva que se entrega ao prazer está morta em vida.

[[v54-5-7]]

^<<v54-5-7,7>>^ Timóteo, mande que as viúvas façam o que eu aconselho para que ninguém possa culpá-las de nada.

[[v54-5-8]]

^<<v54-5-8,8>>^ Porém aquele que não cuida dos seus parentes, especialmente dos da sua própria família, negou a fé e é pior do que os que não creem.

[[v54-5-9]]

^<<v54-5-9,9>>^ Coloque na lista das viúvas somente a que tiver mais de sessenta anos e que tiver casado uma vez só.

[[v54-5-10]]

^<<v54-5-10,10>>^ Ela deve ser conhecida como uma mulher que sempre praticou boas ações, criou bem os filhos, hospedou pessoas na sua casa, prestou serviços humildes aos que pertencem ao povo de Deus, ajudou os necessitados, enfim, fez todo tipo de coisas boas.

[[v54-5-11]]

^<<v54-5-11,11>>^ Mas não ponha na lista as viúvas mais jovens; porque, quando os seus desejos fazem com que queiram casar de novo, elas abandonam a Cristo.

[[v54-5-12]]

^<<v54-5-12,12>>^ E assim elas se tornam culpadas de quebrar a primeira promessa que fizeram a ele .

[[v54-5-13]]

^<<v54-5-13,13>>^ Além disso, elas se acostumam a não fazer nada e a andar de casa em casa; e, pior ainda, aprendem a ser mexeriqueiras, metendo-se em tudo e falando coisas que não devem.

[[v54-5-14]]

^<<v54-5-14,14>>^ Por isso, eu quero que as viúvas mais novas casem, tenham filhos e cuidem da sua casa, para que os nossos inimigos não tenham motivos para falar mal de nós.

[[v54-5-15]]

^<<v54-5-15,15>>^ Pois algumas viúvas já se desviaram e seguiram Satanás.

[[v54-5-16]]

^<<v54-5-16,16>>^ Se alguma mulher cristã tem viúvas na sua família, ela deve ajudá-las. Que ela não ponha essa carga sobre a igreja, para que a igreja possa cuidar das viúvas que não tenham ninguém que as ajude!

[[v54-5-17]]

^<<v54-5-17,17>>^ Os presbíteros  que fazem um bom trabalho na igreja merecem pagamento em dobro, especialmente os que se esforçam na pregação do evangelho  e no ensino cristão.

[[v54-5-18]]

^<<v54-5-18,18>>^ Pois as Escrituras Sagradas  dizem: "Não amarre a boca do boi quando ele estiver pisando o trigo." E dizem ainda: "O trabalhador merece o seu salário."

[[v54-5-19]]

^<<v54-5-19,19>>^ Não aceite nenhuma acusação contra qualquer presbítero, a não ser que ela seja feita por duas testemunhas, pelo menos.

[[v54-5-20]]

^<<v54-5-20,20>>^ Repreenda publicamente os presbíteros que cometem pecados, para que os outros fiquem com medo.

[[v54-5-21]]

^<<v54-5-21,21>>^ Na presença de Deus, de Cristo Jesus e dos santos anjos, eu peço e insisto no seguinte: em tudo o que você fizer, obedeça a estas instruções, sem preconceito contra ninguém e sem favorecer nenhuma pessoa.

[[v54-5-22]]

^<<v54-5-22,22>>^ Não tenha pressa de colocar as mãos sobre alguém para dedicá-lo ao serviço do Senhor. Não tome parte nos pecados dos outros. Conserve-se puro.

[[v54-5-23]]

^<<v54-5-23,23>>^ Já que muitas vezes você tem ficado doente do estômago, não beba somente água, mas beba também um pouco de vinho.

[[v54-5-24]]

^<<v54-5-24,24>>^ Os pecados de algumas pessoas podem ser vistos claramente, antes mesmo de elas serem julgadas. Mas os pecados de outras pessoas só são vistos depois.

[[v54-5-25]]

^<<v54-5-25,25>>^ Assim também as boas ações são vistas claramente e mesmo aquelas que são difíceis de ver não poderão ficar escondidas para sempre.

'''

xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[Próximo Capítulo &#62;]