include::./index.adoc[]

[[v54-3-0]]
=== 1 Timóteo, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v54-3-1]]

^<<v54-3-1,1>>^ Este ensinamento é verdadeiro: se alguém quer muito ser bispo  na Igreja, está desejando um trabalho excelente.

[[v54-3-2]]

^<<v54-3-2,2>>^ O bispo deve ser um homem que ninguém possa culpar de nada. Deve ter somente uma esposa, ser moderado, prudente e simples. Deve estar disposto a hospedar pessoas na sua casa e ter capacidade para ensinar.

[[v54-3-3]]

^<<v54-3-3,3>>^ Não pode ser chegado ao vinho nem briguento, mas deve ser pacífico e calmo. Não deve amar o dinheiro.

[[v54-3-4]]

^<<v54-3-4,4>>^ Deve ser um bom chefe da sua própria família e saber educar os seus filhos de maneira que eles lhe obedeçam com todo o respeito.

[[v54-3-5]]

^<<v54-3-5,5>>^ Pois, se alguém não sabe governar a sua própria família, como poderá cuidar da Igreja de Deus?

[[v54-3-6]]

^<<v54-3-6,6>>^ O bispo não deve ser alguém convertido  há pouco tempo; se for, ele ficará cheio de orgulho e será condenado como o Diabo foi.

[[v54-3-7]]

^<<v54-3-7,7>>^ É preciso que o bispo seja respeitado pelos de fora da Igreja, para que não fique desmoralizado e não caia na armadilha do Diabo.

[[v54-3-8]]

^<<v54-3-8,8>>^ Do mesmo modo, os diáconos  devem ser homens de palavra e sérios. Não devem beber muito vinho, nem ser gananciosos.

[[v54-3-9]]

^<<v54-3-9,9>>^ Eles devem se apegar à verdade revelada da fé e ter sempre a consciência limpa.

[[v54-3-10]]

^<<v54-3-10,10>>^ Primeiro devem ser provados e depois, se forem aprovados, que sirvam a Igreja.

[[v54-3-11]]

^<<v54-3-11,11>>^ A esposa do diácono também deve ser respeitável e não deve ser faladeira. Ela precisa ser moderada e fiel em tudo.

[[v54-3-12]]

^<<v54-3-12,12>>^ O diácono deve ter somente uma esposa e ser capaz de governar bem os seus filhos e toda a sua família.

[[v54-3-13]]

^<<v54-3-13,13>>^ Pois os diáconos que fazem um bom trabalho conquistam o respeito dos irmãos na fé e são capazes de falar com coragem sobre a sua fé em Cristo Jesus.

[[v54-3-14]]

^<<v54-3-14,14>>^ Escrevo essas coisas a você, esperando ir vê-lo logo.

[[v54-3-15]]

^<<v54-3-15,15>>^ Mas, se eu demorar, esta carta vai lhe dizer como devemos agir na família de Deus, que é a Igreja do Deus vivo, a qual é a coluna e o alicerce da verdade.

[[v54-3-16]]

^<<v54-3-16,16>>^ Sem nenhuma dúvida, é grandiosa a verdade revelada da nossa religião. Essa verdade é a seguinte: "Ele se tornou um ser humano, foi aprovado pelo Espírito de Deus, foi visto pelos anjos, foi anunciado entre as nações, foi aceito com fé por muitos no mundo inteiro e foi levado para a glória ."

'''

xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[&#60; Capítulo Anterior] | <<v54-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[Próximo Capítulo &#62;]