include::./index.adoc[]

[[v54-1-0]]
=== 1 Timóteo, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v54-1-1]]

^<<v54-1-1,1>>^ Eu, Paulo, apóstolo  de Cristo Jesus por ordem de Deus, o nosso Salvador, e de Cristo Jesus, a nossa esperança,

[[v54-1-2]]

^<<v54-1-2,2>>^ escrevo a você, Timóteo, meu verdadeiro filho na fé. Que a graça , a misericórdia e a paz de Deus, o Pai, e de Cristo Jesus, o nosso Senhor, estejam com você!

[[v54-1-3]]

^<<v54-1-3,3>>^ Peço que você continue na cidade de Éfeso, como já pedi quando estava indo para a província  da Macedônia. Existem aí nessa cidade alguns que estão ensinando doutrinas falsas, e você precisa fazer com que eles parem com isso.

[[v54-1-4]]

^<<v54-1-4,4>>^ Diga a essa gente que deixe de lado as lendas e as longas listas de nomes de antepassados , pois essas coisas só produzem discussões. Elas não têm nada a ver com o plano de Deus, que é conhecido somente por meio da fé.

[[v54-1-5]]

^<<v54-1-5,5>>^ Essa ordem está sendo dada a fim de que amemos uns aos outros com um amor que vem de um coração puro, de uma consciência limpa e de uma fé verdadeira.

[[v54-1-6]]

^<<v54-1-6,6>>^ Alguns abandonaram essas coisas e se perderam em discussões inúteis.

[[v54-1-7]]

^<<v54-1-7,7>>^ Eles querem ser mestres  da Lei de Deus, mas não entendem nem o que eles mesmos dizem, nem aquilo que falam com tanta certeza.

[[v54-1-8]]

^<<v54-1-8,8>>^ Sabemos que a lei de Deus é boa, se for usada como se deve.

[[v54-1-9]]

^<<v54-1-9,9>>^ Devemos lembrar, é claro, que as leis são feitas não para as pessoas corretas, mas para os marginais e os criminosos, os ateus e os que praticam o mal e para os que não respeitam a Deus nem a religião. São feitas também para os que matam os seus pais e para outros assassinos.

[[v54-1-10]]

^<<v54-1-10,10>>^ E para os imorais, os homossexuais, os sequestradores, os mentirosos, os que dão falso testemunho e para os que fazem qualquer outra coisa que é contra o verdadeiro ensinamento.

[[v54-1-11]]

^<<v54-1-11,11>>^ Esse ensinamento se encontra no evangelho  que Deus me encarregou de anunciar, isto é, na boa notícia que vem do Deus bendito e glorioso .

[[v54-1-12]]

^<<v54-1-12,12>>^ Agradeço a Cristo Jesus, o nosso Senhor, que me tem dado forças para cumprir a minha missão. Eu lhe agradeço porque ele achou que eu era merecedor e porque me escolheu para servi-lo.

[[v54-1-13]]

^<<v54-1-13,13>>^ Ele fez isso apesar de eu ter dito blasfêmias  contra ele no passado e de o ter perseguido e insultado. Mas Deus teve misericórdia de mim, pois eu não tinha fé e por isso não sabia o que estava fazendo.

[[v54-1-14]]

^<<v54-1-14,14>>^ E o nosso Senhor derramou a sua imensa graça  sobre mim e me deu a fé e o amor que temos por estarmos unidos com Cristo Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ O ensinamento verdadeiro e que deve ser crido e aceito de todo o coração é este: Cristo Jesus veio ao mundo para salvar os pecadores, dos quais eu sou o pior.

[[v54-1-16]]

^<<v54-1-16,16>>^ Mas foi por esse mesmo motivo que Deus teve misericórdia de mim, para que Cristo Jesus pudesse mostrar toda a sua paciência comigo. E isso ficará como exemplo para todos os que, no futuro, vão crer nele e receber a vida eterna.

[[v54-1-17]]

^<<v54-1-17,17>>^ Ao Rei eterno, imortal  e invisível, o único Deus — a ele sejam dadas a honra e a glória , para todo o sempre! Amém !

[[v54-1-18]]

^<<v54-1-18,18>>^ Timóteo, meu filho, eu entrego essa ordem a você. Ela está de acordo com as palavras da profecia  , ditas há muito tempo a respeito de você. Que essas palavras sejam as suas armas para que você possa combater bem!

[[v54-1-19]]

^<<v54-1-19,19>>^ Conserve a sua fé e mantenha a sua consciência limpa. Algumas pessoas não têm escutado a sua própria consciência, e isso tem causado a destruição da sua fé.

[[v54-1-20]]

^<<v54-1-20,20>>^ Entre elas estão Himeneu e Alexandre, que eu já entreguei a Satanás para que aprendessem a não blasfemar  mais.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[Próximo Capítulo &#62;]