include::./index.adoc[]

[[v44-28-0]]
=== Atos, 28
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-28-1]]

^<<v44-28-1,1>>^ Quando já estávamos em terra, sãos e salvos, soubemos que a ilha se chamava Malta.

[[v44-28-2]]

^<<v44-28-2,2>>^ Os moradores dali nos trataram com muita bondade. Como estava chovendo e fazia frio, acenderam uma grande fogueira.

[[v44-28-3]]

^<<v44-28-3,3>>^ Paulo ajuntou um feixe de gravetos e os estava jogando no fogo, quando uma cobra, fugindo do calor, agarrou-se na mão dele.

[[v44-28-4]]

^<<v44-28-4,4>>^ Os moradores da ilha viram a cobra pendurada na mão de Paulo e comentaram: — Este homem deve ser um assassino. Pois ele escapou do mar, mas mesmo assim a justiça divina não vai deixá-lo viver.

[[v44-28-5]]

^<<v44-28-5,5>>^ Mas Paulo sacudiu a cobra para dentro do fogo e não sentiu nada.

[[v44-28-6]]

^<<v44-28-6,6>>^ Eles pensavam que ele ia ficar inchado ou que ia cair morto de repente. Porém, depois de esperar bastante tempo, vendo que não acontecia nada, mudaram de ideia e começaram a dizer que ele era um deus.

[[v44-28-7]]

^<<v44-28-7,7>>^ Perto daquele lugar havia algumas terras que pertenciam a Públio, o chefe daquela ilha. Ele nos recebeu muito bem, e durante três dias nós fomos seus hóspedes.

[[v44-28-8]]

^<<v44-28-8,8>>^ O pai dele estava de cama, doente com febre e disenteria. Paulo entrou no quarto, fez uma oração, pôs as mãos sobre ele e o curou.

[[v44-28-9]]

^<<v44-28-9,9>>^ Depois disso os outros doentes da ilha vieram e também foram curados.

[[v44-28-10]]

^<<v44-28-10,10>>^ Eles mostraram muito respeito por nós e, quando embarcamos, puseram no navio tudo o que precisávamos para a viagem.

[[v44-28-11]]

^<<v44-28-11,11>>^ Depois de ficarmos três meses na ilha, embarcamos num navio da cidade de Alexandria, que tinha na proa a figura dos deuses gêmeos Castor e Pólux. O navio tinha passado o inverno na ilha.

[[v44-28-12]]

^<<v44-28-12,12>>^ Nós chegamos à cidade de Siracusa, onde ficamos três dias.

[[v44-28-13]]

^<<v44-28-13,13>>^ Dali seguimos viagem e chegamos à cidade de Régio. No dia seguinte o vento começou a soprar do sul, e em dois dias chegamos a Pozuoli.

[[v44-28-14]]

^<<v44-28-14,14>>^ Nessa cidade encontramos alguns cristãos que nos pediram que ficássemos com eles uma semana. E assim chegamos a Roma.

[[v44-28-15]]

^<<v44-28-15,15>>^ Os irmãos de Roma tinham recebido a notícia da nossa chegada e foram se encontrar conosco nos povoados de Praça de Ápio e de Três Vendas. Ao ver esses irmãos, Paulo agradeceu a Deus e se animou.

[[v44-28-16]]

^<<v44-28-16,16>>^ Quando entramos em Roma, Paulo recebeu permissão para morar por sua conta, guardado por um soldado.

[[v44-28-17]]

^<<v44-28-17,17>>^ Três dias depois, Paulo convidou os líderes dos judeus de Roma para se encontrarem com ele. Quando estavam reunidos, ele disse: — Meus irmãos, eu não fiz nada contra o nosso povo, nem contra os costumes que recebemos dos nossos antepassados. Mesmo assim eu fui preso em Jerusalém e entregue aos romanos.

[[v44-28-18]]

^<<v44-28-18,18>>^ Eles me interrogaram e queriam me soltar, pois não acharam nenhum motivo para me condenar à morte.

[[v44-28-19]]

^<<v44-28-19,19>>^ Mas os judeus não queriam que me soltassem. Por isso fui obrigado a pedir para ser julgado pelo Imperador, embora eu não tenha nenhuma acusação para fazer contra o meu próprio povo.

[[v44-28-20]]

^<<v44-28-20,20>>^ Foi por esse motivo que pedi para ver vocês e conversarmos. Estou preso com estas correntes de ferro por causa daquele que o povo de Israel espera.

[[v44-28-21]]

^<<v44-28-21,21>>^ Então eles disseram: — Nós não recebemos nenhuma carta da Judeia a seu respeito. Também nenhum dos nossos irmãos veio de lá com qualquer notícia ou para falar mal de você.

[[v44-28-22]]

^<<v44-28-22,22>>^ Mas gostaríamos de ouvir você dizer o que pensa, pois sabemos que, de fato, em todos os lugares falam contra essa seita à qual você pertence.

[[v44-28-23]]

^<<v44-28-23,23>>^ Então marcaram um dia com Paulo. Nesse dia, muitos deles foram ao lugar onde Paulo estava. Desde a manhã até a noite ele lhes anunciou e explicou a mensagem sobre o Reino de Deus . E, por meio da Lei  de Moisés e dos livros dos Profetas , procurou convencê-los a respeito de Jesus.

[[v44-28-24]]

^<<v44-28-24,24>>^ Alguns aceitaram as suas palavras, mas outros não creram.

[[v44-28-25]]

^<<v44-28-25,25>>^ Então todos foram embora, conversando entre si. Mas, antes que saíssem, Paulo ainda disse mais uma coisa: — O Espírito Santo tinha razão quando falou por meio do profeta Isaías aos antepassados de vocês.

[[v44-28-26]]

^<<v44-28-26,26>>^ Pois ele disse a Isaías: "Vá e diga a esta gente: Vocês ouvirão, mas não entenderão; olharão, mas não enxergarão nada.

[[v44-28-27]]

^<<v44-28-27,27>>^ Pois a mente deste povo está fechada; eles taparam os ouvidos e fecharam os olhos. Se eles não tivessem feito isso, os seus olhos poderiam ver, e os seus ouvidos poderiam ouvir; a sua mente poderia entender, e eles voltariam para mim, e eu os curaria — disse Deus."

[[v44-28-28]]

^<<v44-28-28,28>>^ E Paulo terminou, dizendo: — Pois fiquem sabendo que Deus mandou a mensagem de salvação para os não judeus! E eles escutarão!

[[v44-28-29]]

^<<v44-28-29,29>>^ [Depois que Paulo disse isso, os judeus foram embora, discutindo com violência.]

[[v44-28-30]]

^<<v44-28-30,30>>^ Durante dois anos Paulo morou ali numa casa alugada e recebia todos os que iam vê-lo.

[[v44-28-31]]

^<<v44-28-31,31>>^ Ele anunciava o Reino de Deus e ensinava a respeito do Senhor Jesus Cristo, falando com toda a coragem e liberdade.

'''

xref:044-atos/044-atos-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romanos/045-romanos-001.adoc#v45-1-0[Próximo Capítulo &#62;]