include::./index.adoc[]

[[v44-2-0]]
=== Atos, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-2-1]]

^<<v44-2-1,1>>^ Quando chegou o dia de Pentecostes , todos os seguidores de Jesus estavam reunidos no mesmo lugar.

[[v44-2-2]]

^<<v44-2-2,2>>^ De repente, veio do céu um barulho que parecia o de um vento soprando muito forte e esse barulho encheu toda a casa onde estavam sentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ Então todos viram umas coisas parecidas com chamas, que se espalharam como línguas de fogo; e cada pessoa foi tocada por uma dessas línguas.

[[v44-2-4]]

^<<v44-2-4,4>>^ Todos ficaram cheios do Espírito Santo e começaram a falar em outras línguas, de acordo com o poder que o Espírito dava a cada pessoa.

[[v44-2-5]]

^<<v44-2-5,5>>^ Estavam morando ali em Jerusalém judeus religiosos vindos de todas as nações do mundo.

[[v44-2-6]]

^<<v44-2-6,6>>^ Quando ouviram aquele barulho, uma multidão deles se ajuntou, e todos ficaram muito admirados porque cada um podia entender na sua própria língua o que os seguidores de Jesus estavam dizendo.

[[v44-2-7]]

^<<v44-2-7,7>>^ A multidão ficou admirada e espantada e comentava: — Estas pessoas que estão falando assim são da Galileia!

[[v44-2-8]]

^<<v44-2-8,8>>^ Como é que cada um de nós as ouvimos falar na nossa própria língua?

[[v44-2-9]]

^<<v44-2-9,9>>^ Nós somos da Pártia, da Média, do Elão, da Mesopotâmia, da Judeia, da Capadócia, do Ponto, da província  da Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ da Frígia, da Panfília, do Egito e das regiões da Líbia que ficam perto de Cirene. Alguns de nós são de Roma.

[[v44-2-11]]

^<<v44-2-11,11>>^ Uns são judeus, e outros, convertidos ao Judaísmo. Alguns são de Creta, e outros, da Arábia. E como é que todos estamos ouvindo essa gente falar em nossa própria língua a respeito das grandes coisas que Deus tem feito?

[[v44-2-12]]

^<<v44-2-12,12>>^ Todos estavam admirados, sem saberem o que pensar, e perguntavam uns aos outros: — O que será que isso quer dizer?

[[v44-2-13]]

^<<v44-2-13,13>>^ Mas outros zombavam, dizendo: — Esse pessoal está bêbado!

[[v44-2-14]]

^<<v44-2-14,14>>^ Então Pedro se levantou, junto com os outros onze apóstolos , e em voz bem alta começou a dizer à multidão: — Meus amigos judeus e todos vocês que moram em Jerusalém, prestem atenção e escutem o que eu vou dizer!

[[v44-2-15]]

^<<v44-2-15,15>>^ Estas pessoas não estão bêbadas, como vocês estão pensando, pois são apenas nove horas da manhã.

[[v44-2-16]]

^<<v44-2-16,16>>^ O que, de fato, está acontecendo é o que o profeta  Joel disse:

[[v44-2-17]]

^<<v44-2-17,17>>^ "É isto o que eu vou fazer nos últimos dias — diz Deus: Derramarei o meu Espírito sobre todas as pessoas. Os filhos e as filhas de vocês anunciarão a minha mensagem; os moços terão visões, e os velhos sonharão .

[[v44-2-18]]

^<<v44-2-18,18>>^ Sim, eu derramarei o meu Espírito sobre os meus servos  e as minhas servas, e naqueles dias eles também anunciarão a minha mensagem.

[[v44-2-19]]

^<<v44-2-19,19>>^ Em cima, no céu, farei com que apareçam coisas espantosas; e embaixo, na terra, farei milagres. Haverá sangue, e fogo, e nuvens de fumaça;

[[v44-2-20]]

^<<v44-2-20,20>>^ o sol ficará escuro, e a lua se tornará cor de sangue, antes que chegue o grande e glorioso Dia do Senhor.

[[v44-2-21]]

^<<v44-2-21,21>>^ Então todos os que pedirem a ajuda do Senhor serão salvos."

[[v44-2-22]]

^<<v44-2-22,22>>^ Pedro continuou: — Homens de Israel, escutem o que eu vou dizer. Deus mostrou a vocês que Jesus de Nazaré era um homem aprovado por ele. Pois, por meio de Jesus, Deus fez milagres, maravilhas e coisas extraordinárias no meio de vocês, como vocês sabem muito bem.

[[v44-2-23]]

^<<v44-2-23,23>>^ Deus, por sua própria vontade e sabedoria, já havia resolvido que Jesus seria entregue nas mãos de vocês. E vocês mesmos o mataram por mãos de homens maus, que o crucificaram.

[[v44-2-24]]

^<<v44-2-24,24>>^ Mas Deus ressuscitou Jesus, livrando-o do poder da morte, porque não era possível que a morte o dominasse.

[[v44-2-25]]

^<<v44-2-25,25>>^ Pois Davi disse a respeito de Jesus o seguinte: "Eu via sempre o Senhor comigo porque ele está ao meu lado direito, para que nada me deixe abalado.

[[v44-2-26]]

^<<v44-2-26,26>>^ Por isso o meu coração está feliz, e as minhas palavras são palavras de alegria; e eu, um ser mortal, vou descansar cheio de esperança,

[[v44-2-27]]

^<<v44-2-27,27>>^ pois tu, Senhor, não me abandonarás no mundo dos mortos . Eu tenho te servido fielmente, e por isso não deixarás que eu apodreça na sepultura.

[[v44-2-28]]

^<<v44-2-28,28>>^ Tu me tens ensinado os caminhos que levam à vida, e a tua presença me encherá de alegria."

[[v44-2-29]]

^<<v44-2-29,29>>^ E Pedro disse mais isto: — Meus irmãos, eu preciso falar claramente com vocês a respeito do patriarca  Davi. Esse grande líder morreu e foi sepultado, e o seu túmulo se encontra aqui até hoje.

[[v44-2-30]]

^<<v44-2-30,30>>^ Ele era profeta e sabia que Deus lhe havia jurado que um dos seus descendentes seria rei, como ele.

[[v44-2-31]]

^<<v44-2-31,31>>^ Davi sabia o que Deus ia fazer e por isso falou a respeito da ressurreição do Messias . Davi disse: "Ele não foi abandonado no mundo dos mortos, nem o seu corpo apodreceu na sepultura."

[[v44-2-32]]

^<<v44-2-32,32>>^ Deus ressuscitou este Jesus, e todos nós somos testemunhas disso.

[[v44-2-33]]

^<<v44-2-33,33>>^ Pois Jesus foi levado para sentar-se ao lado direito de Deus, o seu Pai, o qual lhe deu o Espírito Santo, como havia prometido. E Jesus derramou sobre nós esse Espírito, conforme vocês estão vendo e ouvindo agora.

[[v44-2-34]]

^<<v44-2-34,34>>^ Pois Davi não subiu para o céu, mas ele mesmo afirmou: "O Senhor Deus disse ao meu Senhor: ‘Sente-se do meu lado direito,

[[v44-2-35]]

^<<v44-2-35,35>>^ até que eu ponha os seus inimigos como estrado debaixo dos seus pés.’ "

[[v44-2-36]]

^<<v44-2-36,36>>^ Todo o povo de Israel deve ficar bem certo de que este Jesus que vocês crucificaram é aquele que Deus tornou Senhor e Messias.

[[v44-2-37]]

^<<v44-2-37,37>>^ Quando ouviram isso, todos ficaram muito aflitos e perguntaram a Pedro e aos outros apóstolos: — Irmãos, o que devemos fazer?

[[v44-2-38]]

^<<v44-2-38,38>>^ Pedro respondeu: — Arrependam-se, e cada um de vocês seja batizado em nome de Jesus Cristo para que os seus pecados sejam perdoados, e vocês receberão de Deus o Espírito Santo.

[[v44-2-39]]

^<<v44-2-39,39>>^ Pois essa promessa é para vocês, para os seus filhos e para todos os que estão longe, isto é, para todos aqueles que o Senhor, nosso Deus, chamar .

[[v44-2-40]]

^<<v44-2-40,40>>^ Pedro continuou a dar o seu testemunho e, com muitas outras explicações, procurou convencê-los, dizendo: — Saiam do meio dessa gente má e salvem-se!

[[v44-2-41]]

^<<v44-2-41,41>>^ Muitos acreditaram na mensagem de Pedro e foram batizados. Naquele dia quase três mil se juntaram ao grupo dos seguidores de Jesus.

[[v44-2-42]]

^<<v44-2-42,42>>^ E todos continuavam firmes, seguindo os ensinamentos dos apóstolos, vivendo em amor cristão, partindo o pão juntos e fazendo orações.

[[v44-2-43]]

^<<v44-2-43,43>>^ Os apóstolos  faziam muitos milagres e maravilhas, e por isso todas as pessoas estavam cheias de temor .

[[v44-2-44]]

^<<v44-2-44,44>>^ Todos os que criam estavam juntos e unidos e repartiam uns com os outros o que tinham.

[[v44-2-45]]

^<<v44-2-45,45>>^ Vendiam as suas propriedades e outras coisas e dividiam o dinheiro com todos, de acordo com a necessidade de cada um.

[[v44-2-46]]

^<<v44-2-46,46>>^ Todos os dias, unidos, se reuniam no pátio do Templo. E nas suas casas partiam o pão e participavam das refeições com alegria e humildade.

[[v44-2-47]]

^<<v44-2-47,47>>^ Louvavam a Deus por tudo e eram estimados por todos. E cada dia o Senhor juntava ao grupo as pessoas que iam sendo salvas.

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]