include::./index.adoc[]

[[v44-22-0]]
=== Atos, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-22-1]]

^<<v44-22-1,1>>^ — Meus senhores, irmãos e pais, escutem o que eu vou dizer a vocês em minha defesa!

[[v44-22-2]]

^<<v44-22-2,2>>^ Quando o ouviram falar em hebraico , eles ficaram mais quietos ainda. Então Paulo disse:

[[v44-22-3]]

^<<v44-22-3,3>>^ — Eu sou judeu, nascido em Tarso, na região da Cilícia, mas fui criado aqui em Jerusalém como aluno de Gamaliel. Fui educado muito rigorosamente dentro da lei  dos nossos antepassados. Eu era muito dedicado a Deus, como todos vocês aqui também são.

[[v44-22-4]]

^<<v44-22-4,4>>^ Persegui os que seguiam este Caminho  e fiz com que alguns fossem condenados à morte. Prendi homens e mulheres e os joguei na cadeia.

[[v44-22-5]]

^<<v44-22-5,5>>^ O Grande Sacerdote  e todo o Conselho Superior  podem provar que estou dizendo a verdade, pois eu recebi cartas deles, escritas para os irmãos judeus que moram em Damasco. E fui até lá para prender os seguidores deste Caminho e trazê-los presos com correntes a Jerusalém, a fim de serem castigados.

[[v44-22-6]]

^<<v44-22-6,6>>^ E Paulo continuou: — Eu estava viajando, já perto de Damasco, e era mais ou menos meio-dia. De repente, uma forte luz que vinha do céu brilhou em volta de mim.

[[v44-22-7]]

^<<v44-22-7,7>>^ Eu caí no chão e ouvi uma voz que me dizia: "Saulo, Saulo, por que você me persegue?"

[[v44-22-8]]

^<<v44-22-8,8>>^ — Então eu perguntei: "Quem é o senhor?" — "Eu sou Jesus de Nazaré, aquele que você persegue!"  — respondeu ele.

[[v44-22-9]]

^<<v44-22-9,9>>^ — Os homens que viajavam comigo viram a luz, porém não ouviram a voz de quem falava comigo.

[[v44-22-10]]

^<<v44-22-10,10>>^ Eu perguntei: "Senhor, o que devo fazer?" — E o Senhor respondeu: "Levante-se e entre na cidade de Damasco. Ali alguém vai lhe dizer tudo o que Deus quer que você faça."

[[v44-22-11]]

^<<v44-22-11,11>>^ — Aquela luz brilhante tinha me deixado cego. Por isso os meus companheiros me pegaram pela mão e me levaram até Damasco.

[[v44-22-12]]

^<<v44-22-12,12>>^ Havia ali um homem chamado Ananias. Ele era religioso, obedecia à nossa Lei , e todos os judeus que moravam em Damasco o respeitavam.

[[v44-22-13]]

^<<v44-22-13,13>>^ Esse homem veio me procurar, chegou perto de mim e disse: "Irmão Saulo, veja de novo!" — No mesmo instante comecei a ver de novo e olhei para ele.

[[v44-22-14]]

^<<v44-22-14,14>>^ Então ele disse: "Saulo, o Deus dos nossos antepassados escolheu você para conhecer a vontade dele, para ver o seu Bom Servo  e para ouvir o Servo falar com você pessoalmente.

[[v44-22-15]]

^<<v44-22-15,15>>^ Pois você será testemunha dele para dizer a todos aquilo que você tem visto e ouvido.

[[v44-22-16]]

^<<v44-22-16,16>>^ E agora não espere mais. Levante-se, peça a ajuda do Senhor e seja batizado, e os seus pecados serão perdoados."

[[v44-22-17]]

^<<v44-22-17,17>>^ E Paulo terminou, dizendo: — Então eu voltei para Jerusalém. Quando estava orando no Templo, tive uma visão.

[[v44-22-18]]

^<<v44-22-18,18>>^ Vi o Senhor, e ele me disse: "Saia depressa de Jerusalém porque as pessoas daqui não aceitarão o que você vai dizer a meu respeito."

[[v44-22-19]]

^<<v44-22-19,19>>^ — Eu respondi: "Senhor, eles sabem muito bem que eu ia às sinagogas , e prendia os que criam em ti, e batia neles.

[[v44-22-20]]

^<<v44-22-20,20>>^ Quando estavam matando Estêvão, que falava a respeito de ti, ó Senhor, eu estava ali, concordando com aquele crime. E até tomei conta das capas  dos assassinos dele."

[[v44-22-21]]

^<<v44-22-21,21>>^ — Aí o Senhor disse: "Vá, pois eu vou enviá-lo para bem longe; vou enviá-lo aos não judeus."

[[v44-22-22]]

^<<v44-22-22,22>>^ A multidão ficou ouvindo Paulo até que ele disse isso, mas aí eles começaram a gritar com toda a força: — Matem esse homem! — Ele não merece viver!

[[v44-22-23]]

^<<v44-22-23,23>>^ Eles gritavam, sacudiam as capas no ar e jogavam poeira para cima.

[[v44-22-24]]

^<<v44-22-24,24>>^ Então o comandante mandou que os seus soldados levassem Paulo para dentro da fortaleza. Mandou também que o chicoteassem para que ele contasse por que a multidão estava gritando contra ele.

[[v44-22-25]]

^<<v44-22-25,25>>^ Porém, quando o estavam amarrando para chicoteá-lo, Paulo perguntou ao oficial romano que estava perto dele: — Será que vocês têm o direito de chicotear um cidadão romano, especialmente um que não foi condenado por nenhum crime?

[[v44-22-26]]

^<<v44-22-26,26>>^ Quando o oficial ouviu isso, foi falar com o comandante e disse: — O que é que o senhor vai fazer? Aquele homem é cidadão romano!

[[v44-22-27]]

^<<v44-22-27,27>>^ Então o comandante foi falar com Paulo e perguntou: — Me diga uma coisa: você é mesmo cidadão romano? — Sou! — respondeu Paulo.

[[v44-22-28]]

^<<v44-22-28,28>>^ Aí o comandante disse: — Eu também sou, e isso me custou muito dinheiro. Paulo respondeu: — Pois eu sou cidadão romano de nascimento.

[[v44-22-29]]

^<<v44-22-29,29>>^ Imediatamente os homens que iam chicoteá-lo recuaram. E o próprio comandante ficou com medo ao saber que Paulo era cidadão romano e ele tinha mandado amarrá-lo.

[[v44-22-30]]

^<<v44-22-30,30>>^ O comandante queria saber com certeza por que os judeus estavam acusando Paulo. Então, no dia seguinte, mandou que tirassem as correntes que o prendiam e ordenou que os chefes dos sacerdotes e todo o Conselho Superior  se reunissem. Depois mandou que trouxessem Paulo e o colocassem em frente deles.

'''

xref:044-atos/044-atos-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-atos/044-atos-023.adoc#v44-23-0[Próximo Capítulo &#62;]