include::./index.adoc[]

[[v44-24-0]]
=== Atos, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-24-1]]

^<<v44-24-1,1>>^ Cinco dias depois o Grande Sacerdote  Ananias foi até Cesareia com alguns líderes do povo e com um advogado chamado Tértulo. Eles se apresentaram ao governador Félix para fazer acusações contra Paulo.

[[v44-24-2]]

^<<v44-24-2,2>>^ Depois que Paulo foi chamado, Tértulo começou a acusação, dizendo: — Excelentíssimo Senhor Governador, o seu governo nos tem trazido um longo tempo de paz, e graças à sua sábia administração muitas reformas necessárias estão sendo feitas para o bem deste povo.

[[v44-24-3]]

^<<v44-24-3,3>>^ Somos muito agradecidos por tudo aquilo que temos recebido em todas as ocasiões e em todos os lugares.

[[v44-24-4]]

^<<v44-24-4,4>>^ Mas não quero tomar muito do seu tempo e por isso peço que tenha a bondade de nos escutar apenas um pouco mais.

[[v44-24-5]]

^<<v44-24-5,5>>^ Nós achamos, de fato, que este homem é uma peste. Ele provoca desordens entre os judeus do mundo inteiro e é também o líder do partido dos nazarenos.

[[v44-24-6]]

^<<v44-24-6,6>>^ Além disso tentou profanar  o Templo, e então nós o prendemos. Nós íamos julgá-lo de acordo com a nossa Lei ,

[[v44-24-7]]

^<<v44-24-7,7>>^ mas o comandante Lísias veio e o tirou de nós à força.

[[v44-24-8]]

^<<v44-24-8,8>>^ Aí o próprio Lísias mandou que os acusadores viessem até aqui e fizessem a acusação diante do senhor. Se o senhor fizer perguntas a este homem, ele mesmo confirmará todas as acusações que estamos fazendo contra ele.

[[v44-24-9]]

^<<v44-24-9,9>>^ Então os judeus concordaram, dizendo que tudo era verdade.

[[v44-24-10]]

^<<v44-24-10,10>>^ O Governador fez sinal para que Paulo falasse. Então ele disse: — Eu sei que há muitos anos o senhor é juiz do povo judeu e por isso eu me sinto à vontade para fazer a minha defesa na sua presença.

[[v44-24-11]]

^<<v44-24-11,11>>^ Como o senhor mesmo pode comprovar, faz apenas doze dias que fui a Jerusalém para adorar a Deus.

[[v44-24-12]]

^<<v44-24-12,12>>^ Os judeus não me viram discutindo com ninguém nos pátios do Templo, nem agitando o povo nas suas sinagogas  ou em qualquer outro lugar da cidade.

[[v44-24-13]]

^<<v44-24-13,13>>^ E eles não podem provar nenhuma das acusações que agora estão fazendo contra mim.

[[v44-24-14]]

^<<v44-24-14,14>>^ Porém uma coisa confesso ao senhor: eu sigo o Caminho  que os judeus dizem ser falso; mas é desse modo que sirvo ao Deus dos nossos antepassados. Creio em tudo o que está escrito na Lei  de Moisés e nos livros dos Profetas .

[[v44-24-15]]

^<<v44-24-15,15>>^ Eu e os meus acusadores temos esta mesma esperança em Deus: todos vão ressuscitar, tanto os bons como os maus.

[[v44-24-16]]

^<<v44-24-16,16>>^ Por isso faço tudo para sempre ter a consciência limpa diante de Deus e das pessoas.

[[v44-24-17]]

^<<v44-24-17,17>>^ E Paulo continuou: — Depois de ter ficado fora de Jerusalém durante alguns anos, voltei para lá a fim de levar algum dinheiro para o meu próprio povo e para oferecer sacrifícios .

[[v44-24-18]]

^<<v44-24-18,18>>^ Quando estava fazendo isso, depois de eu ter acabado a cerimônia de purificação , alguns judeus me encontraram na área do Templo . Não havia muita gente comigo nem desordem.

[[v44-24-19]]

^<<v44-24-19,19>>^ Porém alguns judeus da província  da Ásia estavam lá. São eles que devem se apresentar diante do senhor e fazer as acusações, se é que têm alguma coisa contra mim.

[[v44-24-20]]

^<<v44-24-20,20>>^ Ou então que estes homens que estão aqui digam se, quando eu estive diante do Conselho Superior , eles me acharam culpado de qualquer crime.

[[v44-24-21]]

^<<v44-24-21,21>>^ Quando estava de pé diante deles, eu apenas disse em voz alta: "Hoje estou sendo julgado por vocês porque creio que os mortos vão ressuscitar."

[[v44-24-22]]

^<<v44-24-22,22>>^ Então Félix, que estava bem-informado a respeito do Caminho, deixou a questão para depois, dizendo a eles: — Quando o comandante Lísias chegar, eu resolverei o caso de vocês.

[[v44-24-23]]

^<<v44-24-23,23>>^ Ele mandou que o oficial pusesse um guarda para tomar conta de Paulo e ordenou que lhe dessem alguma liberdade e licença para receber ajuda dos amigos.

[[v44-24-24]]

^<<v44-24-24,24>>^ Alguns dias mais tarde Félix veio com Drusila, a sua esposa, que era judia. Mandou chamar Paulo e o ouviu falar a respeito da fé em Cristo Jesus.

[[v44-24-25]]

^<<v44-24-25,25>>^ Mas, quando Paulo começou a falar sobre uma vida correta, o domínio próprio e o Dia do Juízo Final, Félix ficou com medo e disse: — Agora pode ir. Quando eu puder, chamarei você de novo.

[[v44-24-26]]

^<<v44-24-26,26>>^ Além disso Félix esperava que Paulo lhe desse algum dinheiro. Por isso o chamava muitas vezes e conversava com ele.

[[v44-24-27]]

^<<v44-24-27,27>>^ Dois anos depois Pórcio Festo ficou no lugar de Félix como governador. Félix queria agradar os judeus; por isso, ao sair, deixou Paulo na prisão.

'''

xref:044-atos/044-atos-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-atos/044-atos-025.adoc#v44-25-0[Próximo Capítulo &#62;]