include::./index.adoc[]

[[v44-27-0]]
=== Atos, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-27-1]]

^<<v44-27-1,1>>^ Ficou resolvido que devíamos embarcar para a Itália. Então entregaram Paulo e os outros presos a Júlio, um oficial romano que era do batalhão chamado "Batalhão do Imperador".

[[v44-27-2]]

^<<v44-27-2,2>>^ Nós embarcamos num navio da cidade de Adramítio, que estava pronto para navegar para os portos da província  da Ásia. E assim começamos a viagem. Aristarco, um macedônio da cidade de Tessalônica, estava conosco.

[[v44-27-3]]

^<<v44-27-3,3>>^ No dia seguinte chegamos ao porto de Sidom. Júlio tratava Paulo com bondade e lhe deu licença para ir ver os seus amigos e receber deles o que precisava.

[[v44-27-4]]

^<<v44-27-4,4>>^ Depois de sairmos de Sidom, navegamos ao norte da ilha de Chipre a fim de evitar os ventos que estavam soprando contra nós.

[[v44-27-5]]

^<<v44-27-5,5>>^ Atravessamos o mar em frente ao litoral da região da Cilícia e província da Panfília e chegamos a Mirra, uma cidade da província da Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ Ali o oficial romano encontrou um navio da cidade de Alexandria, que ia para a Itália, e nos fez embarcar nele.

[[v44-27-7]]

^<<v44-27-7,7>>^ Navegamos bem devagar vários dias e com grande dificuldade chegamos em frente da cidade de Cnido. Como o vento não nos deixava continuar naquela direção, passamos pelo cabo Salmona da ilha de Creta e seguimos pelo lado sul daquela ilha, o qual é protegido dos ventos.

[[v44-27-8]]

^<<v44-27-8,8>>^ Assim fomos navegando bem perto do litoral e, ainda com dificuldade, chegamos a um lugar chamado "Bons Portos", perto da cidade de Laseia.

[[v44-27-9]]

^<<v44-27-9,9>>^ Ficamos ali muito tempo, e tornou-se perigoso continuar a viagem porque o inverno estava chegando . Então Paulo avisou:

[[v44-27-10]]

^<<v44-27-10,10>>^ — Homens, estou vendo que daqui para diante a nossa viagem será perigosa. Haverá grandes prejuízos não somente com o navio e com a sua carga, mas também haverá perda de vidas.

[[v44-27-11]]

^<<v44-27-11,11>>^ Mas o oficial romano tinha mais confiança no capitão e no dono do navio do que em Paulo.

[[v44-27-12]]

^<<v44-27-12,12>>^ O porto não era bom para passar o inverno. Por isso a maioria achava que devíamos sair dali e tentar chegar a Fênix. Essa cidade é um porto de Creta que tem um lado para o sudoeste e o outro para o noroeste. E eles achavam que poderíamos passar o inverno ali.

[[v44-27-13]]

^<<v44-27-13,13>>^ Começou a soprar do sul um vento fraco, e por isso eles pensaram que podiam fazer o que tinham planejado. Levantamos âncora e fomos navegando o mais perto possível do litoral de Creta.

[[v44-27-14]]

^<<v44-27-14,14>>^ Mas, de repente, um vento muito forte, chamado "Nordeste", veio da ilha

[[v44-27-15]]

^<<v44-27-15,15>>^ e arrastou o navio de tal maneira, que não pudemos fazer com que ele seguisse na direção certa. Por isso desistimos e deixamos que o vento nos levasse.

[[v44-27-16]]

^<<v44-27-16,16>>^ Para escaparmos do vento, passamos ao sul de uma pequena ilha chamada Cauda. Ali, com muita dificuldade, conseguimos recolher o bote do navio.

[[v44-27-17]]

^<<v44-27-17,17>>^ Os marinheiros levantaram o bote para dentro do navio e amarraram o casco do navio com cordas grossas. Estavam com medo de que o navio fosse arrastado para os bancos de areia que ficam perto do litoral da Líbia. Então desceram as velas e deixaram que o navio fosse levado pelo vento.

[[v44-27-18]]

^<<v44-27-18,18>>^ E a terrível tempestade continuou. No dia seguinte começaram a jogar a carga no mar.

[[v44-27-19]]

^<<v44-27-19,19>>^ E, no outro dia, os marinheiros, com as próprias mãos, jogaram no mar uma parte do equipamento do navio.

[[v44-27-20]]

^<<v44-27-20,20>>^ Durante muitos dias não pudemos ver o sol nem as estrelas, e o vento continuava soprando forte. Finalmente perdemos toda a esperança de nos salvarmos.

[[v44-27-21]]

^<<v44-27-21,21>>^ Fazia muito tempo que eles não comiam nada. Então Paulo ficou de pé no meio deles e disse: — Homens, vocês deviam ter dado atenção ao que eu disse e ter ficado em Creta; e assim não teríamos tido toda esta perda e este prejuízo.

[[v44-27-22]]

^<<v44-27-22,22>>^ Mas agora peço que tenham coragem. Ninguém vai morrer; vamos perder somente o navio.

[[v44-27-23]]

^<<v44-27-23,23>>^ Digo isso porque, na noite passada, um anjo do Deus a quem pertenço e sirvo apareceu a mim

[[v44-27-24]]

^<<v44-27-24,24>>^ e disse: "Paulo, não tenha medo! Você precisa ir até a presença do Imperador. E Deus, na sua bondade, já lhe deu a vida de todos os que estão viajando com você."

[[v44-27-25]]

^<<v44-27-25,25>>^ Por isso, homens, tenham coragem! Eu confio em Deus e estou certo de que ele vai fazer o que me disse.

[[v44-27-26]]

^<<v44-27-26,26>>^ Porém vamos ser arrastados para alguma ilha.

[[v44-27-27]]

^<<v44-27-27,27>>^ Duas semanas depois, à noite, continuávamos sendo levados pela tempestade no mar Mediterrâneo. Mais ou menos à meia-noite, os marinheiros começaram a sentir que estávamos chegando perto de terra.

[[v44-27-28]]

^<<v44-27-28,28>>^ Então jogaram no mar uma corda com um peso na ponta e viram que a água ali tinha trinta e seis metros de fundura. Mais adiante tornaram a medir, e deu vinte e sete metros.

[[v44-27-29]]

^<<v44-27-29,29>>^ Eles ficaram com muito medo de que o navio fosse bater contra as rochas. Por isso jogaram quatro âncoras da parte de trás do navio e oraram para que amanhecesse logo.

[[v44-27-30]]

^<<v44-27-30,30>>^ Aí os marinheiros tentaram escapar do navio. Baixaram o bote no mar, fingindo que iam jogar âncoras da parte da frente do navio.

[[v44-27-31]]

^<<v44-27-31,31>>^ Então Paulo disse ao oficial romano e aos soldados: — Se os marinheiros não ficarem no navio, vocês não poderão se salvar.

[[v44-27-32]]

^<<v44-27-32,32>>^ Aí os soldados cortaram as cordas que prendiam o bote e o largaram no mar.

[[v44-27-33]]

^<<v44-27-33,33>>^ De madrugada Paulo pediu a todos que comessem alguma coisa e disse: — Já faz catorze dias que vocês estão esperando e durante este tempo não comeram nada.

[[v44-27-34]]

^<<v44-27-34,34>>^ Agora comam alguma coisa, por favor. Vocês precisam se alimentar para poder continuar vivendo. Pois ninguém vai perder nem mesmo um fio de cabelo.

[[v44-27-35]]

^<<v44-27-35,35>>^ Em seguida Paulo pegou pão e deu graças a Deus diante de todos. Depois partiu o pão e começou a comer.

[[v44-27-36]]

^<<v44-27-36,36>>^ Então eles ficaram com mais coragem e também comeram.

[[v44-27-37]]

^<<v44-27-37,37>>^ No navio éramos ao todo duzentas e setenta e seis pessoas.

[[v44-27-38]]

^<<v44-27-38,38>>^ Depois que todos comeram, jogaram o trigo no mar para que o navio ficasse mais leve.

[[v44-27-39]]

^<<v44-27-39,39>>^ Quando amanheceu, os marinheiros não reconheceram a terra, mas viram uma baía onde havia uma praia. Então resolveram fazer o possível para encalhar o navio lá.

[[v44-27-40]]

^<<v44-27-40,40>>^ Eles cortaram as cordas das âncoras, e as largaram no mar, e desamarraram os lemes. Em seguida suspenderam a vela do lado dianteiro, para que pudessem seguir na direção da praia.

[[v44-27-41]]

^<<v44-27-41,41>>^ Mas o navio bateu num banco de areia e ficou encalhado. A parte da frente ficou presa, e a de trás começou a ser arrebentada pela força das ondas.

[[v44-27-42]]

^<<v44-27-42,42>>^ Os soldados combinaram matar todos os prisioneiros, para que nenhum pudesse chegar até a praia e fugir.

[[v44-27-43]]

^<<v44-27-43,43>>^ Mas o oficial romano queria salvar Paulo e não deixou que fizessem isso. Pelo contrário, mandou que todos os que soubessem nadar fossem os primeiros a se jogar na água e a nadar até a praia.

[[v44-27-44]]

^<<v44-27-44,44>>^ E mandou também que os outros se salvassem, segurando-se em tábuas ou em pedaços do navio. E foi assim que todos nós chegamos a terra sãos e salvos.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]