include::./index.adoc[]

[[v44-15-0]]
=== Atos, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-15-1]]

^<<v44-15-1,1>>^ Alguns homens foram da região da Judeia para a cidade de Antioquia e começaram a ensinar aos irmãos que eles não poderiam ser salvos se não fossem circuncidados , como manda a Lei  de Moisés.

[[v44-15-2]]

^<<v44-15-2,2>>^ Paulo e Barnabé não concordaram e tiveram uma discussão muito forte com eles a respeito disso. Aí foi resolvido que Paulo e Barnabé e mais alguns irmãos fossem para Jerusalém, a fim de estudar esse assunto com os apóstolos  e os presbíteros  da igreja.

[[v44-15-3]]

^<<v44-15-3,3>>^ Então a igreja de Antioquia mandou que eles fossem. Eles passaram pelas regiões da Fenícia e da Samaria, contando como os não judeus estavam se convertendo  a Deus. E todos os irmãos ficaram muito alegres com essa notícia.

[[v44-15-4]]

^<<v44-15-4,4>>^ Quando chegaram a Jerusalém, foram recebidos pela igreja, pelos apóstolos e pelos presbíteros e lhes contaram tudo o que Deus havia feito por meio deles.

[[v44-15-5]]

^<<v44-15-5,5>>^ Mas alguns membros do partido dos fariseus  que também haviam crido se levantaram e disseram: — Os não judeus têm de ser circuncidados e têm de obedecer à Lei de Moisés.

[[v44-15-6]]

^<<v44-15-6,6>>^ Então os apóstolos e os presbíteros se reuniram para estudar o assunto.

[[v44-15-7]]

^<<v44-15-7,7>>^ Depois de muita discussão, Pedro se levantou e disse: — Meus irmãos, vocês sabem que há muito tempo Deus me escolheu entre vocês para anunciar o evangelho  aos não judeus a fim de que eles pudessem ouvir e crer.

[[v44-15-8]]

^<<v44-15-8,8>>^ E Deus, que conhece o coração de todos, mostrou que aceita os não judeus, pois deu o Espírito Santo também a eles, assim como tinha dado a nós.

[[v44-15-9]]

^<<v44-15-9,9>>^ Deus não fez nenhuma diferença entre nós e eles; ele perdoou os pecados deles porque eles creram.

[[v44-15-10]]

^<<v44-15-10,10>>^ Então por que é que vocês estão querendo pôr Deus à prova, colocando uma carga nas costas dos que agora estão crendo? E essa carga nem nós nem os nossos antepassados pudemos carregar.

[[v44-15-11]]

^<<v44-15-11,11>>^ Pelo contrário, por meio da graça  do Senhor Jesus, nós, judeus, cremos e somos salvos do mesmo modo que os não judeus.

[[v44-15-12]]

^<<v44-15-12,12>>^ Então todos os que estavam ali ficaram calados e escutaram Barnabé e Paulo contarem todos os milagres e maravilhas que Deus tinha feito por meio deles entre os não judeus.

[[v44-15-13]]

^<<v44-15-13,13>>^ Quando eles terminaram de falar, Tiago disse: — Meus irmãos, escutem!

[[v44-15-14]]

^<<v44-15-14,14>>^ Simão acabou de explicar como Deus primeiro mostrou o seu cuidado pelos não judeus, escolhendo do meio deles um povo que seria dele.

[[v44-15-15]]

^<<v44-15-15,15>>^ As palavras dos profetas  estão bem de acordo com isso, pois as Escrituras Sagradas  dizem:

[[v44-15-16]]

^<<v44-15-16,16>>^ "Depois disso eu voltarei — diz o Senhor — e construirei de novo o reino de Davi, que é como uma casa que caiu. Juntarei de novo os pedaços dela e tornarei a levantá-la.

[[v44-15-17]]

^<<v44-15-17,17>>^ Assim todas as outras pessoas, todos os outros povos que eu chamei para serem meus, vão procurar conhecer o Senhor. Assim diz o Senhor,

[[v44-15-18]]

^<<v44-15-18,18>>^ que anunciou essas coisas desde os tempos antigos."

[[v44-15-19]]

^<<v44-15-19,19>>^ E Tiago continuou: — A minha opinião é esta: eu acho que não devemos atrapalhar os não judeus que estão se convertendo a Deus.

[[v44-15-20]]

^<<v44-15-20,20>>^ Penso que devemos escrever a eles uma carta, dizendo que não comam a carne de animais que foram oferecidos em sacrifício  aos ídolos, que não pratiquem imoralidade sexual, que não comam a carne de nenhum animal que tenha sido estrangulado e que não comam sangue.

[[v44-15-21]]

^<<v44-15-21,21>>^ Pois, desde os tempos antigos, a Lei de Moisés tem sido lida todos os sábados nas sinagogas , e as suas palavras são anunciadas em todas as cidades.

[[v44-15-22]]

^<<v44-15-22,22>>^ Então os apóstolos  e os presbíteros , com o apoio de toda a igreja, resolveram escolher entre eles alguns homens e mandá-los para Antioquia com Paulo e Barnabé. Os escolhidos foram Judas, chamado Barsabás, e Silas. Esses dois homens eram muito respeitados pelos membros da igreja.

[[v44-15-23]]

^<<v44-15-23,23>>^ E mandaram por eles a seguinte carta: "Nós, os apóstolos e os presbíteros, irmãos de vocês, mandamos saudações aos nossos irmãos não judeus que vivem em Antioquia e na província  da Síria e na região da Cilícia.

[[v44-15-24]]

^<<v44-15-24,24>>^ "Soubemos que alguns do nosso grupo foram até aí e disseram coisas que criaram problemas para vocês. Porém não foi com a nossa autorização que eles fizeram isso.

[[v44-15-25]]

^<<v44-15-25,25>>^ Portanto, nós todos resolvemos, sem nenhum voto contra, escolher alguns homens e mandá-los a vocês. Eles vão com os nossos queridos irmãos Barnabé e Paulo,

[[v44-15-26]]

^<<v44-15-26,26>>^ que têm arriscado a sua vida a serviço do nosso Senhor Jesus Cristo.

[[v44-15-27]]

^<<v44-15-27,27>>^ Estamos enviando, então, Judas e Silas para falarem pessoalmente com vocês sobre estas coisas que estamos escrevendo.

[[v44-15-28]]

^<<v44-15-28,28>>^ Porque o Espírito Santo e nós mesmos resolvemos não pôr nenhuma carga sobre vocês, a não ser estas proibições que são, de fato, necessárias:

[[v44-15-29]]

^<<v44-15-29,29>>^ não comam a carne de nenhum animal que tenha sido oferecido em sacrifício  aos ídolos; não comam o sangue nem a carne de nenhum animal que tenha sido estrangulado; e não pratiquem imoralidade sexual. Vocês agirão muito bem se não fizerem essas coisas. Saúde a todos!"

[[v44-15-30]]

^<<v44-15-30,30>>^ Então mandaram que os quatro partissem, e eles foram para Antioquia. Lá reuniram os cristãos e entregaram a carta.

[[v44-15-31]]

^<<v44-15-31,31>>^ Quando estes a leram, ficaram muito alegres com as palavras de ânimo que havia nela.

[[v44-15-32]]

^<<v44-15-32,32>>^ Judas e Silas, que eram profetas , falaram muito com os irmãos, dando-lhes assim ânimo e força.

[[v44-15-33]]

^<<v44-15-33,33>>^ Eles passaram algum tempo ali, e depois os irmãos, fazendo votos de boa viagem, os mandaram de volta para aqueles que os tinham enviado.

[[v44-15-34]]

^<<v44-15-34,34>>^ [Porém Silas achou melhor ficar ali.]

[[v44-15-35]]

^<<v44-15-35,35>>^ Mas Paulo e Barnabé ficaram algum tempo em Antioquia. Eles e muitos outros cristãos ensinavam e anunciavam a palavra do Senhor.

[[v44-15-36]]

^<<v44-15-36,36>>^ Algum tempo depois, Paulo disse a Barnabé: — Vamos voltar e visitar os irmãos em todas as cidades onde já anunciamos a palavra do Senhor. Vamos ver se eles estão bem.

[[v44-15-37]]

^<<v44-15-37,37>>^ Barnabé queria levar João Marcos.

[[v44-15-38]]

^<<v44-15-38,38>>^ Porém Paulo não queria, pois Marcos não tinha ficado com eles até o fim da primeira viagem missionária, mas os havia deixado na província  da Panfília.

[[v44-15-39]]

^<<v44-15-39,39>>^ Por isso eles tiveram uma discussão tão forte, que se separaram. Barnabé levou João Marcos consigo e embarcou para a ilha de Chipre,

[[v44-15-40]]

^<<v44-15-40,40>>^ enquanto que Paulo escolheu Silas e seguiu viagem, depois que os irmãos o entregaram aos cuidados do Senhor.

[[v44-15-41]]

^<<v44-15-41,41>>^ E Paulo atravessou a província da Síria e a região da Cilícia, dando força às igrejas.

'''

xref:044-atos/044-atos-014.adoc#v44-14-0[&#60; Capítulo Anterior] | <<v44-15-0,Topo>> | xref:044-atos/044-atos-016.adoc#v44-16-0[Próximo Capítulo &#62;]