include::./index.adoc[]

[[v44-6-0]]
=== Atos, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-6-1]]

^<<v44-6-1,1>>^ Algum tempo depois, o número de judeus que se tornaram seguidores de Jesus aumentou muito, e os que tinham sido criados fora da terra de Israel começaram a se queixar dos que tinham sido criados em Israel. A queixa deles era que as viúvas do seu grupo estavam sendo esquecidas na distribuição diária de dinheiro.

[[v44-6-2]]

^<<v44-6-2,2>>^ Então os doze apóstolos  reuniram todo o grupo de seguidores e disseram: — Não está certo nós deixarmos de anunciar a palavra de Deus para tratarmos de dinheiro.

[[v44-6-3]]

^<<v44-6-3,3>>^ Por isso, irmãos, escolham entre vocês sete homens de confiança, cheios do Espírito Santo e de sabedoria, e nós entregaremos esse serviço a eles.

[[v44-6-4]]

^<<v44-6-4,4>>^ Assim nós poderemos continuar usando todo o nosso tempo na oração e no trabalho de anunciar a palavra de Deus.

[[v44-6-5]]

^<<v44-6-5,5>>^ Todos concordaram com a proposta dos apóstolos. Então escolheram Estêvão, um homem cheio de fé e do Espírito Santo, e também Filipe, Prócoro, Nicanor, Timom, Pármenas e Nicolau de Antioquia, um não judeu que antes tinha se convertido ao Judaísmo.

[[v44-6-6]]

^<<v44-6-6,6>>^ Esses homens foram levados aos apóstolos, que oraram e puseram as mãos sobre a cabeça deles.

[[v44-6-7]]

^<<v44-6-7,7>>^ A palavra de Deus continuava a se espalhar. Em Jerusalém o número dos seguidores de Jesus crescia cada vez mais, e era grande o número de sacerdotes judeus que aceitavam a fé cristã.

[[v44-6-8]]

^<<v44-6-8,8>>^ Estêvão, um homem muito abençoado por Deus e cheio de poder, fazia grandes maravilhas e milagres entre o povo.

[[v44-6-9]]

^<<v44-6-9,9>>^ Mas ficaram contra ele alguns membros da "Sinagoga dos Homens Livres ", que era a sinagoga  dos judeus que tinham vindo das cidades de Cirene e Alexandria. Estes e outros judeus da região da Cilícia e da província  da Ásia começaram a discutir com Estêvão.

[[v44-6-10]]

^<<v44-6-10,10>>^ Mas o Espírito de Deus dava tanta sabedoria a Estêvão, que ele ganhava todas as discussões.

[[v44-6-11]]

^<<v44-6-11,11>>^ Então eles pagaram algumas pessoas para dizerem: — Nós ouvimos este homem dizer blasfêmias  contra Moisés e contra Deus!

[[v44-6-12]]

^<<v44-6-12,12>>^ Dessa maneira eles atiçaram o povo, os líderes e os mestres  da Lei. Depois foram, agarraram Estêvão e o levaram ao Conselho Superior .

[[v44-6-13]]

^<<v44-6-13,13>>^ Então arranjaram alguns homens para dizerem mentiras a respeito dele. Essas pessoas afirmaram o seguinte: — Este homem não para de falar contra o nosso santo Templo e contra a Lei  de Moisés.

[[v44-6-14]]

^<<v44-6-14,14>>^ Nós o ouvimos quando ele dizia que esse Jesus de Nazaré vai destruir o Templo e mudar todos os costumes que Moisés nos deu.

[[v44-6-15]]

^<<v44-6-15,15>>^ Todos os que estavam sentados na sala do Conselho Superior olhavam firmemente para Estêvão e viram que o rosto dele parecia o rosto de um anjo.

'''

xref:044-atos/044-atos-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-atos/044-atos-007.adoc#v44-7-0[Próximo Capítulo &#62;]