include::./index.adoc[]

[[v44-8-0]]
=== Atos, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-8-1]]

^<<v44-8-1,1>>^ E Saulo aprovou a morte de Estêvão. Naquele mesmo dia a igreja de Jerusalém começou a sofrer uma grande perseguição. E todos os cristãos, menos os apóstolos , foram espalhados pelas regiões da Judeia e da Samaria.

[[v44-8-2]]

^<<v44-8-2,2>>^ Alguns homens religiosos sepultaram Estêvão e choraram muito por causa da sua morte.

[[v44-8-3]]

^<<v44-8-3,3>>^ Porém Saulo se esforçava para acabar com a igreja. Ele ia de casa em casa, arrastava homens e mulheres e os jogava na cadeia.

[[v44-8-4]]

^<<v44-8-4,4>>^ Aqueles que tinham sido espalhados anunciavam o evangelho  por toda parte.

[[v44-8-5]]

^<<v44-8-5,5>>^ Filipe foi até a capital da Samaria e anunciava Cristo às pessoas dali,

[[v44-8-6]]

^<<v44-8-6,6>>^ e as multidões ouviam com atenção o que ele dizia. Todos o escutavam e viam os milagres que ele fazia.

[[v44-8-7]]

^<<v44-8-7,7>>^ Os espíritos maus, gritando, saíam de muitas pessoas, e muitos coxos e paralíticos eram curados.

[[v44-8-8]]

^<<v44-8-8,8>>^ E assim o povo daquela cidade ficou muito alegre.

[[v44-8-9]]

^<<v44-8-9,9>>^ Morava ali um homem chamado Simão, que desde algum tempo atrás fazia feitiçaria entre os samaritanos  e os havia deixado muito admirados. Ele se fazia de importante,

[[v44-8-10]]

^<<v44-8-10,10>>^ e os moradores de Samaria, desde os mais importantes até os mais humildes, escutavam com muita atenção o que ele dizia. Eles afirmavam: — Este homem é o poder de Deus! Ele é "o Grande Poder"!

[[v44-8-11]]

^<<v44-8-11,11>>^ Eles davam atenção ao que Simão fazia porque durante muito tempo ele os havia deixado assombrados com as suas feitiçarias.

[[v44-8-12]]

^<<v44-8-12,12>>^ Mas eles acreditaram na mensagem de Filipe a respeito da boa notícia do Reino de Deus  e a respeito de Jesus Cristo e foram batizados, tanto homens como mulheres.

[[v44-8-13]]

^<<v44-8-13,13>>^ O próprio Simão também creu. E, depois de ser batizado, acompanhava Filipe de perto, muito admirado com os grandes milagres e maravilhas que ele fazia.

[[v44-8-14]]

^<<v44-8-14,14>>^ Os apóstolos , que estavam em Jerusalém, ficaram sabendo que o povo de Samaria também havia recebido a palavra de Deus e por isso mandaram Pedro e João para lá.

[[v44-8-15]]

^<<v44-8-15,15>>^ Quando os dois chegaram, oraram para que a gente de Samaria recebesse o Espírito Santo,

[[v44-8-16]]

^<<v44-8-16,16>>^ pois o Espírito ainda não tinha descido sobre nenhum deles. Eles apenas haviam sido batizados em nome do Senhor Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Aí Pedro e João puseram as mãos sobre eles, e assim eles receberam o Espírito Santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ Simão viu que, quando os apóstolos punham as mãos sobre as pessoas, Deus dava a elas o Espírito Santo. Por isso ofereceu dinheiro a Pedro e a João,

[[v44-8-19]]

^<<v44-8-19,19>>^ dizendo: — Quero que vocês me deem também esse poder. Assim, quando eu puser as mãos sobre alguém, essa pessoa receberá o Espírito Santo.

[[v44-8-20]]

^<<v44-8-20,20>>^ Então Pedro respondeu: — Que Deus mande você e o seu dinheiro para o inferno! Você pensa que pode conseguir com dinheiro o dom  de Deus?

[[v44-8-21]]

^<<v44-8-21,21>>^ Você não tem direito de tomar parte no nosso trabalho porque o seu coração não é honesto diante de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Arrependa-se, deixe o seu plano perverso e peça ao Senhor que o perdoe por essa má intenção.

[[v44-8-23]]

^<<v44-8-23,23>>^ Vejo que você está cheio de inveja, uma inveja amarga como fel, e vejo também que você está preso pelo pecado.

[[v44-8-24]]

^<<v44-8-24,24>>^ Aí Simão disse a Pedro e a João: — Por favor, peçam ao Senhor por mim para que não aconteça comigo nada do que vocês disseram.

[[v44-8-25]]

^<<v44-8-25,25>>^ Depois de terem dado o seu testemunho e de terem pregado a palavra do Senhor, Pedro e João voltaram para Jerusalém. No caminho eles espalhavam o evangelho  em muitos povoados da Samaria.

[[v44-8-26]]

^<<v44-8-26,26>>^ Um anjo do Senhor disse a Filipe: — Apronte-se e vá para o Sul, pelo caminho que vai de Jerusalém até a cidade de Gaza. (Pouca gente passava por aquele caminho.)

[[v44-8-27]]

^<<v44-8-27,27>>^ Filipe se aprontou e foi. No caminho ele viu um eunuco  da Etiópia, que estava voltando para o seu país. Esse homem era alto funcionário, tesoureiro e administrador das finanças da rainha da Etiópia. Ele tinha ido a Jerusalém para adorar a Deus. Na volta, sentado na sua carruagem, ele estava lendo o livro do profeta  Isaías.

[[v44-8-28]]

^<<v44-8-28,28>>^ Filipe se aprontou e foi. No caminho ele viu um eunuco  da Etiópia, que estava voltando para o seu país. Esse homem era alto funcionário, tesoureiro e administrador das finanças da rainha da Etiópia. Ele tinha ido a Jerusalém para adorar a Deus. Na volta, sentado na sua carruagem, ele estava lendo o livro do profeta  Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ Então o Espírito Santo disse a Filipe: — Chegue perto dessa carruagem e acompanhe-a.

[[v44-8-30]]

^<<v44-8-30,30>>^ Filipe correu para perto da carruagem e ouviu o funcionário lendo o livro do profeta Isaías. Aí perguntou: — O senhor entende o que está lendo?

[[v44-8-31]]

^<<v44-8-31,31>>^ — Como posso entender se ninguém me explica? — respondeu o funcionário. Então convidou Filipe para subir e sentar-se com ele na carruagem.

[[v44-8-32]]

^<<v44-8-32,32>>^ A parte das Escrituras Sagradas  que o funcionário estava lendo era esta: "Ele era como um cordeiro que é levado para ser morto; era como uma ovelha que fica muda quando cortam a sua lã. Ele não disse nada.

[[v44-8-33]]

^<<v44-8-33,33>>^ Foi humilhado, e foram injustos com ele. Ninguém poderá falar a respeito de descendentes dele, já que a sua vida na terra chegou ao fim."

[[v44-8-34]]

^<<v44-8-34,34>>^ O funcionário perguntou a Filipe: — Por favor, me explique uma coisa! De quem é que o profeta está falando isso? É dele mesmo ou de outro?

[[v44-8-35]]

^<<v44-8-35,35>>^ Então, começando com aquela parte das Escrituras, Filipe anunciou ao funcionário a boa notícia a respeito de Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Enquanto estavam viajando, chegaram a um lugar onde havia água. Então o funcionário disse: — Veja! Aqui tem água. Será que eu não posso ser batizado?

[[v44-8-37]]

^<<v44-8-37,37>>^ [Filipe respondeu: — Se o senhor crê de todo o coração, é claro que pode. E o funcionário disse: — Sim, eu creio que Jesus Cristo é o Filho de Deus.]

[[v44-8-38]]

^<<v44-8-38,38>>^ Ele mandou parar a carruagem, os dois entraram na água, e Filipe o batizou ali.

[[v44-8-39]]

^<<v44-8-39,39>>^ Quando eles estavam saindo da água, o Espírito do Senhor levou Filipe embora. O funcionário não viu mais Filipe, porém continuou a sua viagem, cheio de alegria.

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]