include::./index.adoc[]

[[v44-18-0]]
=== Atos, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-18-1]]

^<<v44-18-1,1>>^ Depois disso, Paulo saiu de Atenas e foi para a cidade de Corinto.

[[v44-18-2]]

^<<v44-18-2,2>>^ Encontrou ali um judeu chamado Áquila, que era da província  do Ponto. Fazia pouco tempo que ele tinha chegado da Itália com Priscila, a sua esposa. Eles tinham saído de lá porque o imperador Cláudio havia mandado que todos os judeus fossem embora de Roma. Paulo foi visitá-los

[[v44-18-3]]

^<<v44-18-3,3>>^ e acabou ficando ali para trabalhar com eles, porque a profissão de Paulo e a deles era a mesma, isto é, fazer barracas.

[[v44-18-4]]

^<<v44-18-4,4>>^ E todos os sábados ele falava na sinagoga  e procurava convencer os judeus e os não judeus.

[[v44-18-5]]

^<<v44-18-5,5>>^ Depois que Silas e Timóteo chegaram da província da Macedônia, Paulo começou a dar todo o seu tempo para anunciar a mensagem. Ele afirmava aos judeus que Jesus é o Messias .

[[v44-18-6]]

^<<v44-18-6,6>>^ Mas alguns deles ficaram contra Paulo e o xingaram. Então, em sinal de protesto, ele sacudiu o pó das suas roupas e disse: — Se vocês se perderem, os culpados serão vocês mesmos. A responsabilidade não será minha. De agora em diante vou anunciar a mensagem aos não judeus.

[[v44-18-7]]

^<<v44-18-7,7>>^ Então ele saiu de lá e foi morar na casa de um homem chamado Tício Justo, um não judeu que adorava a Deus. A casa dele ficava ao lado da sinagoga.

[[v44-18-8]]

^<<v44-18-8,8>>^ Crispo, que era o chefe da sinagoga, também creu no Senhor Jesus, e todas as pessoas da sua casa também creram. Muitas pessoas da cidade de Corinto ouviram a mensagem, creram e foram batizadas.

[[v44-18-9]]

^<<v44-18-9,9>>^ Certa noite Paulo teve uma visão, e nela o Senhor disse: — Não tenha medo, continue falando e não se cale,

[[v44-18-10]]

^<<v44-18-10,10>>^ porque eu estou com você. Ninguém poderá lhe fazer nenhum mal, pois muitas pessoas desta cidade são minhas.

[[v44-18-11]]

^<<v44-18-11,11>>^ E Paulo ficou ali um ano e meio, ensinando a palavra de Deus àquela gente.

[[v44-18-12]]

^<<v44-18-12,12>>^ Quando Gálio se tornou o governador da província da Acaia, os judeus se juntaram contra Paulo. Eles o agarraram, o levaram ao tribunal

[[v44-18-13]]

^<<v44-18-13,13>>^ e disseram ao Governador: — Este homem está querendo convencer o povo a adorar a Deus de um modo que é contra a nossa lei .

[[v44-18-14]]

^<<v44-18-14,14>>^ Quando Paulo ia falar, Gálio disse aos judeus: — Judeus, se isso fosse alguma falta grave ou um grande crime, seria justo que eu tivesse paciência para escutá-los.

[[v44-18-15]]

^<<v44-18-15,15>>^ Mas, como é só uma questão de palavras, de nomes e da própria lei de vocês, resolvam vocês mesmos. Eu não vou ser juiz nesses assuntos.

[[v44-18-16]]

^<<v44-18-16,16>>^ Em seguida os expulsou do tribunal.

[[v44-18-17]]

^<<v44-18-17,17>>^ Então eles agarraram Sóstenes, o chefe da sinagoga, e o surraram diante do tribunal. Porém Gálio não se importou com isso.

[[v44-18-18]]

^<<v44-18-18,18>>^ Paulo ficou muitos dias com os cristãos em Corinto. Depois se despediu deles e embarcou num navio para a província  da Síria, junto com Priscila e o seu marido Áquila. Antes de embarcar em Cencreia, ele rapou a cabeça como sinal de que havia cumprido uma promessa que tinha feito a Deus.

[[v44-18-19]]

^<<v44-18-19,19>>^ Eles chegaram à cidade de Éfeso, e Priscila e Áquila ficaram ali. Paulo entrou na sinagoga  e falou com os judeus.

[[v44-18-20]]

^<<v44-18-20,20>>^ Então lhe pediram que ficasse com eles mais tempo, porém ele não quis.

[[v44-18-21]]

^<<v44-18-21,21>>^ E, quando foi embora, disse: — Eu voltarei, se Deus quiser. Então Paulo embarcou e partiu de Éfeso.

[[v44-18-22]]

^<<v44-18-22,22>>^ Quando desembarcou em Cesareia, foi logo para Jerusalém. Ali ele fez uma curta visita à igreja e depois seguiu para Antioquia da Síria.

[[v44-18-23]]

^<<v44-18-23,23>>^ Depois de ficar algum tempo em Antioquia, ele foi embora. Atravessou a província da Galácia e o distrito da Frígia, indo de um lugar para outro e animando todos os cristãos.

[[v44-18-24]]

^<<v44-18-24,24>>^ Um judeu chamado Apolo, nascido na cidade de Alexandria, havia chegado a Éfeso. Ele falava muito bem e tinha um conhecimento profundo das Escrituras Sagradas .

[[v44-18-25]]

^<<v44-18-25,25>>^ Era também instruído no Caminho do Senhor , falava com grande entusiasmo, e o seu ensinamento a respeito de Jesus era correto; porém conhecia somente o batismo de João.

[[v44-18-26]]

^<<v44-18-26,26>>^ Ele começou a falar com coragem na sinagoga . Priscila e o seu marido Áquila o ouviram falar; então o levaram para a casa deles e lhe explicaram melhor o Caminho de Deus.

[[v44-18-27]]

^<<v44-18-27,27>>^ Quando Apolo resolveu ir para a província  da Acaia, os cristãos de Éfeso o animaram e escreveram cartas para os irmãos de lá, pedindo que o recebessem bem. Chegando lá, ele ajudou muito aqueles que, pela graça  de Deus, haviam crido.

[[v44-18-28]]

^<<v44-18-28,28>>^ Pois Apolo, com argumentos fortes, derrotava os judeus nas discussões públicas, provando pelas Escrituras Sagradas que Jesus é o Messias .

'''

xref:044-atos/044-atos-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-atos/044-atos-019.adoc#v44-19-0[Próximo Capítulo &#62;]