include::./index.adoc[]

[[v44-7-0]]
=== Atos, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-7-1]]

^<<v44-7-1,1>>^ O Grande Sacerdote  perguntou a Estêvão: — O que essas pessoas estão dizendo é verdade?

[[v44-7-2]]

^<<v44-7-2,2>>^ Estêvão respondeu: — Irmãos e pais, escutem! O glorioso  Deus apareceu ao nosso antepassado Abraão quando este morava na região da Mesopotâmia, antes de ir morar na cidade de Harã.

[[v44-7-3]]

^<<v44-7-3,3>>^ E Deus lhe disse: "Saia da sua terra e do meio dos seus parentes e vá para uma terra que eu lhe mostrarei."

[[v44-7-4]]

^<<v44-7-4,4>>^ Então ele saiu da Caldeia e foi morar em Harã. Depois que o pai dele morreu, Deus trouxe Abraão para esta terra onde vocês agora estão morando.

[[v44-7-5]]

^<<v44-7-5,5>>^ Ele não deu a Abraão nem mesmo um palmo desta terra, mas prometeu que ia lhe dar toda esta terra e que depois ela seria dos seus descendentes. Quando Deus fez essa promessa, Abraão ainda não tinha filhos.

[[v44-7-6]]

^<<v44-7-6,6>>^ Ele disse a Abraão: "Os seus descendentes vão viver como estrangeiros em outra terra. Ali eles serão escravos e serão maltratados durante quatrocentos anos."

[[v44-7-7]]

^<<v44-7-7,7>>^ — E Deus disse ainda: "Eu castigarei a nação que os escravizar. Depois disso eles voltarão daquela terra e me adorarão neste lugar."

[[v44-7-8]]

^<<v44-7-8,8>>^ Deus deu a Abraão a cerimônia da circuncisão  como prova da aliança  que fez com ele. Por isso Abraão circuncidou o seu filho Isaque uma semana depois do seu nascimento. Isaque circuncidou o seu filho Jacó, e Jacó fez o mesmo com os seus doze filhos, os patriarcas .

[[v44-7-9]]

^<<v44-7-9,9>>^ Estêvão continuou: — Os irmãos de José tinham inveja dele e o venderam para ser escravo no Egito. Mas Deus estava com ele

[[v44-7-10]]

^<<v44-7-10,10>>^ e o livrou de todas as suas aflições. Quando José apareceu diante de Faraó, rei do Egito, Deus lhe deu sabedoria e modos agradáveis. E Faraó o nomeou governador do Egito e do palácio do rei.

[[v44-7-11]]

^<<v44-7-11,11>>^ Depois houve falta de alimentos e muito sofrimento no Egito e em Canaã, e os nossos antepassados não tinham mais o que comer.

[[v44-7-12]]

^<<v44-7-12,12>>^ Mais tarde, Jacó ouviu dizer que no Egito havia trigo e mandou pela primeira vez os nossos antepassados até lá.

[[v44-7-13]]

^<<v44-7-13,13>>^ Na segunda vez José contou aos seus irmãos quem ele era, e Faraó ficou sabendo da família de José.

[[v44-7-14]]

^<<v44-7-14,14>>^ Então José mandou buscar o seu pai Jacó e todos os seus parentes, a fim de irem para o Egito; eram setenta e cinco pessoas ao todo.

[[v44-7-15]]

^<<v44-7-15,15>>^ Jacó foi para o Egito, e ali ele e os nossos antepassados ficaram morando até o dia da morte deles.

[[v44-7-16]]

^<<v44-7-16,16>>^ Depois os corpos deles foram trazidos para Siquém e postos no túmulo que Abraão tinha comprado dos descendentes de Hamor por um certo preço.

[[v44-7-17]]

^<<v44-7-17,17>>^ — Quando estava chegando o tempo de Deus cumprir o juramento que havia feito a Abraão, o nosso povo tinha aumentado muito no Egito.

[[v44-7-18]]

^<<v44-7-18,18>>^ Então um rei que não sabia nada a respeito de José começou a governar o Egito.

[[v44-7-19]]

^<<v44-7-19,19>>^ Esse rei enganou e maltratou os nossos antepassados, a ponto de obrigá-los a abandonar as suas próprias criancinhas para que elas morressem.

[[v44-7-20]]

^<<v44-7-20,20>>^ Nesse tempo nasceu Moisés, que era uma linda criança, e durante três meses os seus pais cuidaram dele em casa.

[[v44-7-21]]

^<<v44-7-21,21>>^ Mas, quando tiveram de abandoná-lo, a filha do rei o adotou e criou como seu próprio filho.

[[v44-7-22]]

^<<v44-7-22,22>>^ E assim ele foi instruído em toda a ciência dos egípcios e se tornou um homem que falava e agia com autoridade.

[[v44-7-23]]

^<<v44-7-23,23>>^ Estêvão disse ainda: — Quando Moisés já estava com quarenta anos, resolveu ir ver a sua gente, os israelitas.

[[v44-7-24]]

^<<v44-7-24,24>>^ Ali viu um egípcio maltratando um homem do seu povo. Então defendeu o israelita e o vingou, matando o egípcio.

[[v44-7-25]]

^<<v44-7-25,25>>^ Moisés pensava que os israelitas entenderiam que Deus ia libertá-los por meio dele, mas eles não entenderam.

[[v44-7-26]]

^<<v44-7-26,26>>^ No dia seguinte Moisés viu dois israelitas brigando. E, tentando apartar a briga, disse: "Homens, escutem! Vocês são irmãos; por que estão brigando?"

[[v44-7-27]]

^<<v44-7-27,27>>^ — Mas aquele que estava maltratando o outro empurrou Moisés para um lado e disse: "Quem pôs você como nosso chefe ou nosso juiz?

[[v44-7-28]]

^<<v44-7-28,28>>^ Você está querendo me matar como matou o egípcio ontem?"

[[v44-7-29]]

^<<v44-7-29,29>>^ Quando Moisés ouviu isso, fugiu do Egito e foi morar na terra de Midiã, e ali nasceram dois filhos dele.

[[v44-7-30]]

^<<v44-7-30,30>>^ — Quarenta anos mais tarde, quando Moisés estava no deserto, perto do monte Sinai, um anjo apareceu a ele, no meio do fogo de um espinheiro que estava queimando.

[[v44-7-31]]

^<<v44-7-31,31>>^ Moisés ficou admirado com o que estava vendo e chegou perto para ver melhor. Então ouviu a voz do Senhor, que disse:

[[v44-7-32]]

^<<v44-7-32,32>>^ "Eu sou o Deus dos seus antepassados, o Deus de Abraão, de Isaque e de Jacó." Moisés tremia de medo e não tinha coragem de olhar.

[[v44-7-33]]

^<<v44-7-33,33>>^ Então o Senhor disse: "Tire as sandálias, pois o lugar onde você está é um lugar sagrado.

[[v44-7-34]]

^<<v44-7-34,34>>^ Eu tenho visto como o meu povo está sendo maltratado no Egito; tenho ouvido os gemidos deles e desci para libertá-los. Agora vou mandar você para o Egito."

[[v44-7-35]]

^<<v44-7-35,35>>^ E Estêvão continuou: — Esse mesmo Moisés foi rejeitado pelo povo de Israel. Eles lhe perguntaram: "Quem pôs você como nosso chefe ou nosso juiz?" Deus enviou esse Moisés como líder e libertador, com a ajuda do anjo que apareceu no espinheiro.

[[v44-7-36]]

^<<v44-7-36,36>>^ Foi ele quem tirou os israelitas do Egito, fazendo milagres e maravilhas naquela terra, e também no mar Vermelho, e no deserto, durante quarenta anos.

[[v44-7-37]]

^<<v44-7-37,37>>^ Foi esse mesmo Moisés quem disse aos israelitas: "Do meio de vocês Deus escolherá e enviará para vocês um profeta , assim como ele me enviou."

[[v44-7-38]]

^<<v44-7-38,38>>^ Foi Moisés quem esteve com os israelitas reunidos no deserto; ele esteve lá com os nossos antepassados e com o anjo que falou com ele no monte Sinai. E foi Moisés quem recebeu e nos entregou as mensagens vivas de Deus.

[[v44-7-39]]

^<<v44-7-39,39>>^ — Os nossos antepassados não quiseram obedecer a Moisés, mas o rejeitaram e queriam voltar para o Egito.

[[v44-7-40]]

^<<v44-7-40,40>>^ Eles disseram a Arão: "Faça para nós deuses que irão à nossa frente. Não sabemos o que aconteceu com Moisés, aquele homem que nos tirou do Egito."

[[v44-7-41]]

^<<v44-7-41,41>>^ Então fizeram uma imagem em forma de bezerro e mataram animais para oferecer a ela como sacrifício . Depois deram uma festa em honra da imagem que eles mesmos tinham feito.

[[v44-7-42]]

^<<v44-7-42,42>>^ Mas Deus se afastou deles e deixou que adorassem as estrelas do céu, como está escrito no Livro dos Profetas : "Ó povo de Israel, não foi para mim que vocês mataram e ofereceram animais em sacrifício durante quarenta anos no deserto.

[[v44-7-43]]

^<<v44-7-43,43>>^ Vocês carregaram a barraca do deus Moloque e também a imagem da estrela de Raifã , o deus de vocês. Esses eram ídolos que vocês tinham feito para adorar. Por isso vou mandar vocês para além da Babilônia."

[[v44-7-44]]

^<<v44-7-44,44>>^ — No deserto, os nossos antepassados tinham consigo a Tenda da Presença de Deus . Essa Tenda foi feita como Deus tinha mandado Moisés fazer, de acordo com o modelo que Deus lhe havia mostrado.

[[v44-7-45]]

^<<v44-7-45,45>>^ Eles tinham recebido a Tenda dos seus antepassados e a levaram quando foram com Josué e conquistaram as terras das nações que Deus expulsou de diante deles. A Tenda ficou lá com eles até o tempo de Davi.

[[v44-7-46]]

^<<v44-7-46,46>>^ Davi recebeu a aprovação de Deus e pediu licença para construir uma casa para o Deus de Jacó.

[[v44-7-47]]

^<<v44-7-47,47>>^ Mas foi Salomão quem construiu a casa de Deus.

[[v44-7-48]]

^<<v44-7-48,48>>^ — Porém o Altíssimo não mora em casas construídas por seres humanos. Como disse o profeta:

[[v44-7-49]]

^<<v44-7-49,49>>^ "O céu é o meu trono, diz o Senhor, e a terra é o estrado onde descanso os meus pés. Que tipo de casa vocês poderiam construir para mim? Como conseguiriam construir um lugar onde eu pudesse morar?

[[v44-7-50]]

^<<v44-7-50,50>>^ Por acaso não fui eu quem fez todas as coisas?"

[[v44-7-51]]

^<<v44-7-51,51>>^ E Estêvão terminou, dizendo: — Como vocês são teimosos! Como são duros de coração e surdos para ouvir a mensagem de Deus! Vocês sempre têm rejeitado o Espírito Santo, como os seus antepassados rejeitaram.

[[v44-7-52]]

^<<v44-7-52,52>>^ Qual foi o profeta que os antepassados de vocês não perseguiram? Eles mataram os mensageiros de Deus que no passado anunciaram a vinda do Bom Servo . E agora vocês o traíram e o mataram.

[[v44-7-53]]

^<<v44-7-53,53>>^ Vocês receberam a lei  por meio de anjos e não têm obedecido a essa lei.

[[v44-7-54]]

^<<v44-7-54,54>>^ Quando os membros do Conselho Superior  acabaram de ouvir o que Estêvão tinha dito, ficaram furiosos e rangeram os dentes contra ele.

[[v44-7-55]]

^<<v44-7-55,55>>^ Mas Estêvão, cheio do Espírito Santo, olhou firmemente para o céu e viu a glória  de Deus. E viu também Jesus em pé, ao lado direito de Deus.

[[v44-7-56]]

^<<v44-7-56,56>>^ Então disse: — Olhem! Eu estou vendo o céu aberto e o Filho do Homem  em pé, ao lado direito de Deus.

[[v44-7-57]]

^<<v44-7-57,57>>^ Mas eles taparam os ouvidos e, gritando bem alto, avançaram todos juntos contra Estêvão.

[[v44-7-58]]

^<<v44-7-58,58>>^ Depois o jogaram para fora da cidade e o apedrejaram. E as testemunhas deixaram um moço chamado Saulo tomando conta das suas capas .

[[v44-7-59]]

^<<v44-7-59,59>>^ Enquanto eles atiravam as pedras, Estêvão chamava Jesus, dizendo: — Senhor Jesus, recebe o meu espírito!

[[v44-7-60]]

^<<v44-7-60,60>>^ Depois, ajoelhou-se e gritou com voz bem forte: — Senhor, não condenes esta gente por causa deste pecado! E, depois que disse isso, ele morreu.

'''

xref:044-atos/044-atos-006.adoc#v44-6-0[&#60; Capítulo Anterior] | <<v44-7-0,Topo>> | xref:044-atos/044-atos-008.adoc#v44-8-0[Próximo Capítulo &#62;]