include::./index.adoc[]

[[v44-19-0]]
=== Atos, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-19-1]]

^<<v44-19-1,1>>^ Enquanto Apolo estava na cidade de Corinto, Paulo viajou pelo interior da província  da Ásia e chegou a Éfeso. Ali encontrou alguns cristãos

[[v44-19-2]]

^<<v44-19-2,2>>^ e perguntou: — Quando vocês creram, vocês receberam o Espírito Santo? Eles responderam: — Nós nem mesmo sabíamos que existe o Espírito Santo.

[[v44-19-3]]

^<<v44-19-3,3>>^ — Então que tipo de batismo vocês receberam? — perguntou Paulo. — O batismo de João Batista! — responderam.

[[v44-19-4]]

^<<v44-19-4,4>>^ Então Paulo disse: — João batizava aqueles que se arrependiam dos seus pecados. E também dizia ao povo de Israel que eles deviam crer naquele que havia de vir depois dele, isto é, em Jesus.

[[v44-19-5]]

^<<v44-19-5,5>>^ Depois de ouvirem isso, aqueles homens foram batizados em nome do Senhor Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ Aí Paulo pôs as mãos sobre eles, e o Espírito Santo veio sobre eles. Então começaram a falar em línguas estranhas e a anunciar também a mensagem de Deus.

[[v44-19-7]]

^<<v44-19-7,7>>^ Esses homens eram mais ou menos doze.

[[v44-19-8]]

^<<v44-19-8,8>>^ Durante três meses Paulo foi à sinagoga  e falou com coragem ao povo. Ele conversava com eles e tentava convencê-los a respeito do Reino de Deus .

[[v44-19-9]]

^<<v44-19-9,9>>^ Mas alguns eram teimosos, não acreditavam e, em frente de todos, ainda falavam mal do Caminho do Senhor . Então Paulo abandonou a sinagoga, levando os cristãos consigo, e começou a falar diariamente na escola de um homem chamado Tirano.

[[v44-19-10]]

^<<v44-19-10,10>>^ Ele fez isso durante dois anos, até que todos os moradores da província  da Ásia, tanto os judeus como os não judeus, ouviram a mensagem do Senhor.

[[v44-19-11]]

^<<v44-19-11,11>>^ Deus fazia milagres extraordinários por meio de Paulo,

[[v44-19-12]]

^<<v44-19-12,12>>^ tanto que as pessoas pegavam lenços e aventais que ele usava e os levavam para os doentes tocarem. E, quando estes tocavam neles, ficavam curados; e de outras pessoas saíam os espíritos maus.

[[v44-19-13]]

^<<v44-19-13,13>>^ Alguns judeus que andavam de um lugar para outro, expulsando espíritos maus, quiseram usar também o nome do Senhor Jesus para expulsar os espíritos maus, dizendo a eles: — Pelo poder do nome de Jesus, o mesmo que Paulo anuncia, eu mando que vocês saiam!

[[v44-19-14]]

^<<v44-19-14,14>>^ Os homens que faziam isso eram os sete filhos de um judeu chamado Ceva, que era Grande Sacerdote .

[[v44-19-15]]

^<<v44-19-15,15>>^ Mas certa vez um espírito mau disse a eles: — Eu conheço Jesus e sei quem é Paulo. Mas vocês, quem são?

[[v44-19-16]]

^<<v44-19-16,16>>^ Então o homem que estava dominado pelo espírito mau os atacou e bateu neles com tanta violência, que eles fugiram daquela casa feridos e com as roupas rasgadas.

[[v44-19-17]]

^<<v44-19-17,17>>^ E todos os que moravam em Éfeso, judeus e não judeus, souberam disso. Eles ficaram com muito medo, e o nome do Senhor Jesus se tornou mais respeitado ainda.

[[v44-19-18]]

^<<v44-19-18,18>>^ Então muitos dos que creram vinham e confessavam publicamente as coisas más que haviam feito.

[[v44-19-19]]

^<<v44-19-19,19>>^ E muitos daqueles que praticavam feitiçaria ajuntaram os seus livros e os trouxeram para queimar diante de todos. Quando calcularam o preço dos livros queimados, o total chegou a cinquenta mil moedas de prata .

[[v44-19-20]]

^<<v44-19-20,20>>^ Assim, de maneira poderosa, a mensagem do Senhor era anunciada e se espalhava cada vez mais.

[[v44-19-21]]

^<<v44-19-21,21>>^ Depois desses acontecimentos, Paulo resolveu passar pelas províncias  da Macedônia e da Acaia e ir até Jerusalém. Ele dizia: — Depois que eu visitar Jerusalém, preciso ir a Roma.

[[v44-19-22]]

^<<v44-19-22,22>>^ Então Paulo enviou para a Macedônia dois dos seus ajudantes, Timóteo e Erasto, mas ele ficou mais algum tempo na província da Ásia.

[[v44-19-23]]

^<<v44-19-23,23>>^ Foi nessa ocasião que houve na cidade de Éfeso uma grande desordem por causa do Caminho do Senhor .

[[v44-19-24]]

^<<v44-19-24,24>>^ Um ourives chamado Demétrio fazia pequenos modelos de prata do templo da deusa Diana, e o seu negócio dava muito lucro aos que trabalhavam com ele.

[[v44-19-25]]

^<<v44-19-25,25>>^ Então ele chamou estes e outros da mesma profissão e disse: — Meus amigos, vocês sabem que a nossa riqueza vem deste nosso ofício.

[[v44-19-26]]

^<<v44-19-26,26>>^ Vocês mesmos podem ver e ouvir o que esse tal de Paulo está fazendo. Ele afirma que os deuses feitos por mãos humanas não são deuses de verdade. E está conseguindo convencer muita gente, tanto daqui como de quase toda a província da Ásia.

[[v44-19-27]]

^<<v44-19-27,27>>^ Assim nós estamos correndo o perigo de ver o povo rejeitar o nosso negócio. E não é só isso. Existe o perigo de o templo da grande deusa Diana não ficar valendo mais nada e também de ser destruída a grandeza dessa deusa adorada por todos na Ásia e no mundo inteiro.

[[v44-19-28]]

^<<v44-19-28,28>>^ Quando a multidão ouviu isso, ficou furiosa e começou a gritar: — Viva a grande Diana de Éfeso!

[[v44-19-29]]

^<<v44-19-29,29>>^ E a confusão se espalhou por toda a cidade. A multidão agarrou Gaio e Aristarco, dois macedônios que viajavam com Paulo, e os arrastou até o teatro.

[[v44-19-30]]

^<<v44-19-30,30>>^ Paulo queria falar ao povo, mas os irmãos não deixaram.

[[v44-19-31]]

^<<v44-19-31,31>>^ Alguns altos funcionários daquela província, que eram amigos de Paulo, mandaram a ele um recado, pedindo que não fosse ao teatro.

[[v44-19-32]]

^<<v44-19-32,32>>^ Naquela altura dos acontecimentos a multidão que se achava no teatro estava em completa desordem: uns gritavam uma coisa, e outros gritavam outra, pois a maioria nem sabia por que estava ali.

[[v44-19-33]]

^<<v44-19-33,33>>^ Algumas pessoas ficaram pensando que Alexandre era o culpado, pois os judeus o obrigaram a ir e ficar lá na frente. Aí Alexandre fez um sinal com a mão e tentou falar para se defender diante do povo.

[[v44-19-34]]

^<<v44-19-34,34>>^ Mas, quando perceberam que ele era judeu, ficaram gritando todos juntos a mesma coisa durante duas horas: — Viva a grande Diana de Éfeso!

[[v44-19-35]]

^<<v44-19-35,35>>^ Finalmente o secretário da prefeitura da cidade conseguiu acalmar o povo. Ele disse o seguinte: — Cidadãos de Éfeso! Todos sabem que a nossa cidade é a guardadora do templo da grande Diana e da pedra sagrada que caiu do céu.

[[v44-19-36]]

^<<v44-19-36,36>>^ Ninguém pode negar isso. Assim fiquem calmos e não façam nada sem pensar bem.

[[v44-19-37]]

^<<v44-19-37,37>>^ Vocês trouxeram aqui estes homens, mas eles não assaltaram o templo, nem ofenderam a nossa deusa.

[[v44-19-38]]

^<<v44-19-38,38>>^ Se Demétrio e os seus ajudantes têm alguma acusação contra alguém, eles podem apresentar suas acusações no tribunal, pois para isso há dias certos de reunião, e também existem os governadores.

[[v44-19-39]]

^<<v44-19-39,39>>^ Porém, se vocês querem mais alguma coisa, isso será tratado na reunião do povo, convocada de acordo com a lei .

[[v44-19-40]]

^<<v44-19-40,40>>^ Pois corremos o risco de sermos acusados de revolta, por causa do que está acontecendo hoje. Não há motivo para toda esta confusão. E nós não poderíamos justificar tudo isso.

[[v44-19-41]]

^<<v44-19-41,41>>^ Depois de dizer essas palavras, ele terminou a reunião.

'''

xref:044-atos/044-atos-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-atos/044-atos-020.adoc#v44-20-0[Próximo Capítulo &#62;]