include::./index.adoc[]

[[v44-25-0]]
=== Atos, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-25-1]]

^<<v44-25-1,1>>^ Três dias depois de chegar àquela província , Festo saiu da cidade de Cesareia e foi até Jerusalém.

[[v44-25-2]]

^<<v44-25-2,2>>^ Os chefes dos sacerdotes e os líderes judeus apresentaram lá as suas acusações contra Paulo e pediram a Festo

[[v44-25-3]]

^<<v44-25-3,3>>^ o favor de mandar trazer Paulo para Jerusalém. É que eles tinham combinado matar Paulo no caminho.

[[v44-25-4]]

^<<v44-25-4,4>>^ Mas Festo respondeu: — Paulo está preso em Cesareia, e eu logo voltarei para lá.

[[v44-25-5]]

^<<v44-25-5,5>>^ Que os líderes de vocês me acompanhem até lá e o acusem, se é que ele fez algum mal.

[[v44-25-6]]

^<<v44-25-6,6>>^ Festo passou oito ou dez dias entre eles e depois voltou para Cesareia. No dia seguinte sentou-se no tribunal e mandou que trouxessem Paulo.

[[v44-25-7]]

^<<v44-25-7,7>>^ Quando Paulo chegou, os judeus que tinham vindo de Jerusalém ficaram em volta dele e começaram a fazer muitas acusações graves, mas não conseguiram provar nada.

[[v44-25-8]]

^<<v44-25-8,8>>^ Então Paulo se defendeu, dizendo: — Eu não fiz nada contra a lei  dos judeus, nem contra o Templo, nem contra o Imperador.

[[v44-25-9]]

^<<v44-25-9,9>>^ Festo, querendo agradar os judeus, perguntou a Paulo: — Você não quer ir a Jerusalém e ser julgado lá por mim a respeito destas coisas?

[[v44-25-10]]

^<<v44-25-10,10>>^ Paulo respondeu: — Estou diante do tribunal do Imperador romano, e é aqui que devo ser julgado. Não fiz mal nenhum aos judeus, como o senhor sabe muito bem.

[[v44-25-11]]

^<<v44-25-11,11>>^ Se não respeitei a lei ou se fiz alguma coisa que mereça a pena de morte, estou pronto para morrer. Mas, se o que dizem contra mim não é verdade, ninguém pode me entregar a eles. Portanto, apelo para o Imperador.

[[v44-25-12]]

^<<v44-25-12,12>>^ Então Festo, depois de conversar com os seus conselheiros, disse: — Já que você apelou para o Imperador, então irá para o Imperador.

[[v44-25-13]]

^<<v44-25-13,13>>^ Alguns dias depois o rei Agripa e Berenice, sua irmã, chegaram a Cesareia para cumprimentar Festo.

[[v44-25-14]]

^<<v44-25-14,14>>^ Quando já fazia alguns dias que eles estavam lá, Festo contou ao rei o caso de Paulo. Ele disse: — Está aqui um homem que Félix deixou como prisioneiro.

[[v44-25-15]]

^<<v44-25-15,15>>^ Quando fui a Jerusalém, os chefes dos sacerdotes e os líderes dos judeus fizeram acusações contra ele e me pediram que o condenasse.

[[v44-25-16]]

^<<v44-25-16,16>>^ Mas eu lhes disse que os romanos não costumam condenar ninguém sem primeiro colocar os acusadores diante do acusado, dando a este a oportunidade de se defender.

[[v44-25-17]]

^<<v44-25-17,17>>^ Por isso, quando eles vieram até aqui, não perdi tempo, e, logo no dia seguinte, sentei no tribunal, e mandei que trouxessem o homem.

[[v44-25-18]]

^<<v44-25-18,18>>^ Os seus inimigos chegaram, mas não o acusaram de nenhum crime grave como pensei que iam fazer.

[[v44-25-19]]

^<<v44-25-19,19>>^ A única acusação que tinham contra ele era a respeito da própria religião deles e também sobre um homem que já morreu, chamado Jesus. Paulo afirma que esse homem está vivo.

[[v44-25-20]]

^<<v44-25-20,20>>^ Eu não sabia como conseguir informações sobre esse assunto. Por isso perguntei a Paulo se queria ir a Jerusalém para ser julgado lá a respeito dessas acusações.

[[v44-25-21]]

^<<v44-25-21,21>>^ Mas Paulo apelou para o Imperador e pediu para ficar preso até que o Imperador resolvesse o seu caso. Então mandei os guardas tomarem conta dele até que eu pudesse mandá-lo para o Imperador.

[[v44-25-22]]

^<<v44-25-22,22>>^ Aí Agripa disse a Festo: — Eu gostaria de ouvir esse homem. — Amanhã o senhor vai ouvi-lo! — respondeu Festo.

[[v44-25-23]]

^<<v44-25-23,23>>^ No dia seguinte Agripa e Berenice chegaram com grande cerimônia e pompa. Entraram na sala de audiências com os chefes militares e os homens mais importantes da cidade. Festo mandou que trouxessem Paulo

[[v44-25-24]]

^<<v44-25-24,24>>^ e disse: — Rei Agripa e todos os que estão aqui, vejam este homem! É contra ele que todos os judeus, tanto daqui como de Jerusalém, estão fazendo acusações diante de mim. Eles insistem em dizer que este homem deve morrer,

[[v44-25-25]]

^<<v44-25-25,25>>^ mas eu acho que ele não fez nada para ser condenado à morte. Como ele mesmo pediu para ser julgado pelo Imperador, resolvi atendê-lo.

[[v44-25-26]]

^<<v44-25-26,26>>^ Porém até agora não sei bem o que escrever a respeito dele ao Imperador. Então eu o trouxe aqui, diante dos senhores — e especialmente do senhor, rei Agripa — a fim de lhe fazer perguntas. Assim terei alguma coisa para escrever.

[[v44-25-27]]

^<<v44-25-27,27>>^ Pois acho absurdo mandar um prisioneiro sem explicar claramente as acusações que existem contra ele.

'''

xref:044-atos/044-atos-024.adoc#v44-24-0[&#60; Capítulo Anterior] | <<v44-25-0,Topo>> | xref:044-atos/044-atos-026.adoc#v44-26-0[Próximo Capítulo &#62;]