include::./index.adoc[]

[[v44-9-0]]
=== Atos, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-9-1]]

^<<v44-9-1,1>>^ Enquanto isso, Saulo não parava de ameaçar de morte os seguidores do Senhor Jesus. Ele foi falar com o Grande Sacerdote

[[v44-9-2]]

^<<v44-9-2,2>>^ e pediu cartas de apresentação para as sinagogas  da cidade de Damasco. Com esses documentos Saulo poderia prender e levar para Jerusalém os seguidores do Caminho do Senhor  que moravam ali, tanto os homens como as mulheres.

[[v44-9-3]]

^<<v44-9-3,3>>^ Mas na estrada de Damasco, quando Saulo já estava perto daquela cidade, de repente, uma luz que vinha do céu brilhou em volta dele.

[[v44-9-4]]

^<<v44-9-4,4>>^ Ele caiu no chão e ouviu uma voz que dizia: — Saulo, Saulo, por que você me persegue?

[[v44-9-5]]

^<<v44-9-5,5>>^ — Quem é o senhor? — perguntou ele. A voz respondeu: — Eu sou Jesus, aquele que você persegue.

[[v44-9-6]]

^<<v44-9-6,6>>^ Mas levante-se, entre na cidade, e ali dirão a você o que deve fazer.

[[v44-9-7]]

^<<v44-9-7,7>>^ Os homens que estavam viajando com Saulo ficaram parados sem poder dizer nada. Eles ouviram a voz, mas não viram ninguém.

[[v44-9-8]]

^<<v44-9-8,8>>^ Saulo se levantou do chão e abriu os olhos, mas não podia ver nada. Então eles o pegaram pela mão e o levaram para Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ Ele ficou três dias sem poder ver e durante esses dias não comeu nem bebeu nada.

[[v44-9-10]]

^<<v44-9-10,10>>^ Em Damasco morava um seguidor de Jesus chamado Ananias. Ele teve uma visão, e nela apareceu o Senhor, chamando: — Ananias! Ele respondeu: — Aqui estou, Senhor!

[[v44-9-11]]

^<<v44-9-11,11>>^ E o Senhor lhe disse: — Apronte-se, e vá até a casa de Judas, na rua Direita, e procure um homem chamado Saulo, da cidade de Tarso. Ele está orando

[[v44-9-12]]

^<<v44-9-12,12>>^ e teve uma visão. Nela apareceu um homem chamado Ananias, que entrou e pôs as mãos sobre ele a fim de que ele pudesse ver de novo.

[[v44-9-13]]

^<<v44-9-13,13>>^ Ananias respondeu: — Senhor, muita gente tem me falado a respeito desse homem e de todas as maldades que ele fez em Jerusalém com os que creem no Senhor.

[[v44-9-14]]

^<<v44-9-14,14>>^ E agora ele veio aqui a Damasco com autorização dos chefes dos sacerdotes para prender todos os que te adoram.

[[v44-9-15]]

^<<v44-9-15,15>>^ Mas o Senhor disse a Ananias: — Vá, pois eu escolhi esse homem para trabalhar para mim, a fim de que ele anuncie o meu nome aos não judeus, aos reis e ao povo de Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ Eu mesmo vou mostrar a Saulo tudo o que ele terá de sofrer por minha causa.

[[v44-9-17]]

^<<v44-9-17,17>>^ Então Ananias foi, entrou na casa de Judas, pôs as mãos sobre Saulo e disse: — Saulo, meu irmão, o Senhor que me mandou aqui é o mesmo Jesus que você viu na estrada de Damasco. Ele me mandou para que você veja de novo e fique cheio do Espírito Santo.

[[v44-9-18]]

^<<v44-9-18,18>>^ No mesmo instante umas coisas parecidas com escamas caíram dos olhos de Saulo, e ele pôde ver de novo. Ele se levantou e foi batizado;

[[v44-9-19]]

^<<v44-9-19,19>>^ depois ele comeu alguma coisa e ficou forte como antes. Saulo ficou alguns dias com os seguidores de Jesus em Damasco.

[[v44-9-20]]

^<<v44-9-20,20>>^ E começou imediatamente a anunciar Jesus nas sinagogas , dizendo: — Jesus é o Filho de Deus.

[[v44-9-21]]

^<<v44-9-21,21>>^ Todos os que ouviam Saulo ficavam admirados e perguntavam: — Não é este o homem que em Jerusalém estava matando todos os seguidores de Jesus? Não foi ele que veio até aqui para prender e levar essa gente aos chefes dos sacerdotes?

[[v44-9-22]]

^<<v44-9-22,22>>^ Mas as mensagens de Saulo se tornavam cada vez mais poderosas. E as provas que ele apresentava de que Jesus era o Messias  eram tão fortes, que os judeus que moravam em Damasco não sabiam o que dizer.

[[v44-9-23]]

^<<v44-9-23,23>>^ Muitos dias depois, os judeus de Damasco se reuniram e resolveram matá-lo,

[[v44-9-24]]

^<<v44-9-24,24>>^ mas Saulo ficou sabendo do plano deles. Eles vigiavam os portões da cidade dia e noite para o matar.

[[v44-9-25]]

^<<v44-9-25,25>>^ Mas certa noite os seguidores de Saulo o puseram dentro de um cesto e o desceram por uma abertura que havia na muralha da cidade.

[[v44-9-26]]

^<<v44-9-26,26>>^ Saulo foi para Jerusalém e tentou juntar-se aos seguidores de Jesus. Porém todos tinham medo dele porque não acreditavam que ele também era seguidor de Jesus.

[[v44-9-27]]

^<<v44-9-27,27>>^ Então Barnabé veio ajudá-lo e o apresentou aos apóstolos . E lhes contou como Saulo tinha visto o Senhor no caminho e como o Senhor havia falado com ele. Barnabé também contou como, em Damasco, Saulo, pelo poder do nome de Jesus, havia anunciado corajosamente o evangelho .

[[v44-9-28]]

^<<v44-9-28,28>>^ Depois disso Saulo ficou com eles, andando por toda parte em Jerusalém; e, pelo poder do nome do Senhor, ele anunciava corajosamente o evangelho.

[[v44-9-29]]

^<<v44-9-29,29>>^ Ele também conversava e discutia com os judeus que tinham sido criados fora da terra de Israel, mas eles procuravam um jeito de matá-lo.

[[v44-9-30]]

^<<v44-9-30,30>>^ Quando os irmãos souberam disso, levaram Saulo até a cidade de Cesareia e depois o mandaram para a cidade de Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ Em toda a região da Judeia, Galileia e Samaria, a Igreja estava em paz. Ela ficava cada vez mais forte, crescia em número de pessoas com a ajuda do Espírito Santo e mostrava grande respeito pelo Senhor Jesus.

[[v44-9-32]]

^<<v44-9-32,32>>^ Pedro viajava por toda parte. Um dia foi visitar o povo de Deus que morava na cidade de Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ Encontrou ali um homem chamado Eneias, que era paralítico e fazia oito anos que não saía da cama.

[[v44-9-34]]

^<<v44-9-34,34>>^ Pedro lhe disse: — Eneias, Jesus Cristo já curou você. Levante-se e arrume a sua cama. Na mesma hora Eneias se levantou.

[[v44-9-35]]

^<<v44-9-35,35>>^ Então todos os moradores da cidade de Lida e da região de Sarom viram isso e se converteram  ao Senhor.

[[v44-9-36]]

^<<v44-9-36,36>>^ Na cidade de Jope havia uma seguidora de Jesus chamada Tabita. (Este nome em grego  é Dorcas .) Ela usava todo o seu tempo fazendo o bem e ajudando os pobres.

[[v44-9-37]]

^<<v44-9-37,37>>^ Naqueles dias Dorcas ficou doente e morreu. Lavaram o corpo dela e depois o puseram num quarto do andar de cima.

[[v44-9-38]]

^<<v44-9-38,38>>^ Jope ficava perto de Lida. Quando os seguidores de Jesus em Jope souberam que Pedro estava em Lida, enviaram dois homens para levar-lhe o seguinte recado: — Por favor, venha depressa até Jope!

[[v44-9-39]]

^<<v44-9-39,39>>^ Então Pedro se aprontou e foi com eles. Quando chegou lá, eles o levaram para o quarto de cima. Todas as viúvas ficaram em volta dele, chorando e mostrando os vestidos e as outras roupas que Dorcas havia feito quando ainda vivia.

[[v44-9-40]]

^<<v44-9-40,40>>^ Então Pedro mandou que todos saíssem do quarto e em seguida se ajoelhou e orou. Depois virou-se para o corpo de Dorcas e disse: — Tabita, levante-se! Ela abriu os olhos e, quando viu Pedro, sentou-se.

[[v44-9-41]]

^<<v44-9-41,41>>^ Pedro pegou-a pela mão e ajudou-a a ficar de pé. Em seguida chamou toda a gente da igreja, inclusive as viúvas, e a entregou a eles viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ As notícias a respeito disso se espalharam por toda a cidade de Jope, e muitos creram no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ E Pedro ficou lá muitos dias, na casa de um curtidor de couros chamado Simão.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]