include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-10-1]]

^<<v44-10-1,1>>^ Na cidade de Cesareia havia um homem chamado Cornélio, que era comandante de um batalhão romano chamado "Batalhão Italiano".

[[v44-10-2]]

^<<v44-10-2,2>>^ Ele era um homem religioso; ele e todas as pessoas da sua casa adoravam a Deus. Cornélio ajudava muito os judeus pobres e orava sempre a Deus.

[[v44-10-3]]

^<<v44-10-3,3>>^ Um dia, ali pelas três horas da tarde , Cornélio teve uma visão. Ele viu claramente um anjo de Deus, que chegou perto dele e disse: — Cornélio!

[[v44-10-4]]

^<<v44-10-4,4>>^ Ele ficou olhando para o anjo e, com muito medo, perguntou: — O que é, senhor? O anjo respondeu: — Deus aceitou as suas orações e a ajuda que você tem dado aos pobres e ele não esqueceu você.

[[v44-10-5]]

^<<v44-10-5,5>>^ Agora mande alguns homens até a cidade de Jope para buscarem o homem chamado Simão Pedro.

[[v44-10-6]]

^<<v44-10-6,6>>^ Ele está hospedado na casa de outro Simão, um curtidor de couros que mora na beira do mar.

[[v44-10-7]]

^<<v44-10-7,7>>^ Quando o anjo foi embora, Cornélio imediatamente chamou dois empregados e um soldado que estava a seu serviço e que era um homem religioso.

[[v44-10-8]]

^<<v44-10-8,8>>^ Cornélio contou a eles tudo o que havia acontecido e mandou que fossem a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, ao meio-dia, Pedro subiu ao terraço para orar. Enquanto isso, os homens vinham pelo caminho, já perto de Jope.

[[v44-10-10]]

^<<v44-10-10,10>>^ Pedro ficou com fome e quis comer alguma coisa. Enquanto o almoço estava sendo feito, ele teve uma visão.

[[v44-10-11]]

^<<v44-10-11,11>>^ Viu o céu aberto e uma coisa parecida com um grande lençol amarrado pelas quatro pontas, que descia até o chão.

[[v44-10-12]]

^<<v44-10-12,12>>^ Dentro daquilo havia todos os tipos de animais de quatro patas, de animais que se arrastam pelo chão e de aves.

[[v44-10-13]]

^<<v44-10-13,13>>^ Então Pedro ouviu uma voz, que dizia: — Pedro, levante-se! Mate e coma!

[[v44-10-14]]

^<<v44-10-14,14>>^ Pedro respondeu: — De jeito nenhum, Senhor! Eu nunca comi nenhuma coisa que a lei  considera suja ou impura !

[[v44-10-15]]

^<<v44-10-15,15>>^ A voz falou de novo com ele: — Não chame de impuro aquilo que Deus purificou.

[[v44-10-16]]

^<<v44-10-16,16>>^ Isso aconteceu três vezes. Em seguida a coisa que parecia um lençol foi levada de volta para o céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Pedro começou a perguntar a si mesmo o que aquela visão queria dizer. E naquele momento os homens que Cornélio havia mandado já tinham se informado sobre onde ficava a casa de Simão e estavam na porta.

[[v44-10-18]]

^<<v44-10-18,18>>^ Eles chamaram alguém da casa e perguntaram: — Por acaso um homem chamado Simão Pedro está hospedado aqui?

[[v44-10-19]]

^<<v44-10-19,19>>^ Pedro ainda estava pensando na visão, quando o Espírito Santo disse: — Escute! Estão aí três homens procurando você.

[[v44-10-20]]

^<<v44-10-20,20>>^ Agora apronte-se, desça e vá com eles. Vá tranquilo porque fui eu que mandei que eles viessem aqui.

[[v44-10-21]]

^<<v44-10-21,21>>^ Então Pedro desceu e disse aos homens: — Eu sou a pessoa que vocês estão procurando. Por que vieram aqui?

[[v44-10-22]]

^<<v44-10-22,22>>^ Eles responderam: — Nós fomos mandados pelo comandante Cornélio. Ele é um homem bom, teme a Deus  e é muito respeitado por todos os judeus. Um anjo de Deus mandou que ele pedisse a você que fosse até a casa dele para que ele ouvisse o que você vai dizer.

[[v44-10-23]]

^<<v44-10-23,23>>^ Então Pedro convidou os homens para entrarem, e os hospedou ali naquela noite. No dia seguinte Pedro se aprontou e foi com eles, e alguns irmãos que moravam em Jope também foram.

[[v44-10-24]]

^<<v44-10-24,24>>^ No outro dia chegaram à cidade de Cesareia. Cornélio e os parentes e amigos mais íntimos que ele tinha convidado já estavam esperando Pedro.

[[v44-10-25]]

^<<v44-10-25,25>>^ Quando Pedro ia entrando, Cornélio veio ao seu encontro, ajoelhou-se e curvou a cabeça diante dele.

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro fez com que ele se levantasse e disse: — Fique de pé, pois eu sou apenas um homem como você.

[[v44-10-27]]

^<<v44-10-27,27>>^ Enquanto conversava com Cornélio, Pedro entrou na casa e encontrou muita gente reunida ali.

[[v44-10-28]]

^<<v44-10-28,28>>^ Então disse a todos: — Vocês sabem muito bem que a religião dos judeus não permite que eles façam amizade com não judeus ou entrem nas casas deles. Mas Deus me mostrou que eu não devo chamar ninguém de impuro ou de sujo.

[[v44-10-29]]

^<<v44-10-29,29>>^ Por isso, quando vocês me chamaram, eu vim de boa vontade. Agora quero saber por que foi que vocês mandaram me chamar.

[[v44-10-30]]

^<<v44-10-30,30>>^ Cornélio respondeu: — Três dias atrás, às três horas da tarde, eu estava orando aqui em casa. De repente, um homem vestido com roupas brancas apareceu na minha frente

[[v44-10-31]]

^<<v44-10-31,31>>^ e disse: "Cornélio, Deus ouviu as suas orações e lembrou do que você tem feito para ajudar os pobres.

[[v44-10-32]]

^<<v44-10-32,32>>^ Mande alguém até Jope a fim de buscar Simão, que também é chamado de Pedro. Ele está hospedado na casa de Simão, o curtidor, que mora na beira do mar."

[[v44-10-33]]

^<<v44-10-33,33>>^ Então eu mandei chamar você logo, e você fez muito bem em vir. Agora estamos todos reunidos aqui na presença de Deus, prontos para ouvir o que o Senhor mandou você dizer.

[[v44-10-34]]

^<<v44-10-34,34>>^ Então Pedro começou a falar. Ele disse: — Agora eu sei que, de fato, Deus trata a todos de modo igual,

[[v44-10-35]]

^<<v44-10-35,35>>^ pois ele aceita todos os que o temem  e fazem o que é direito, seja qual for a sua raça.

[[v44-10-36]]

^<<v44-10-36,36>>^ Vocês conhecem a mensagem que Deus mandou ao povo de Israel, anunciando a boa notícia de paz por meio de Jesus Cristo, que é o Senhor de todos.

[[v44-10-37]]

^<<v44-10-37,37>>^ Vocês sabem o que aconteceu em toda a terra de Israel, começando na Galileia, depois que João pregou a sua mensagem a respeito do batismo.

[[v44-10-38]]

^<<v44-10-38,38>>^ Sabem também como Deus derramou o Espírito Santo sobre Jesus de Nazaré e lhe deu poder. Jesus andou por toda parte fazendo o bem e curando todos os que eram dominados pelo Diabo, porque Deus estava com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ Nós somos testemunhas de tudo o que ele fez na terra de Israel, inclusive em Jerusalém. E depois o mataram, pregando-o numa cruz.

[[v44-10-40]]

^<<v44-10-40,40>>^ Pedro continuou: — Porém Deus ressuscitou Jesus no terceiro dia e também fez com que ele aparecesse a nós.

[[v44-10-41]]

^<<v44-10-41,41>>^ Ele não foi visto por todo o povo, mas somente por nós, que somos as testemunhas que Deus já havia escolhido. Nós comemos e bebemos com ele depois que Deus o ressuscitou.

[[v44-10-42]]

^<<v44-10-42,42>>^ Jesus nos mandou anunciar o evangelho  ao povo e testemunhar que ele foi posto por Deus como Juiz dos vivos e dos mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ Todos os profetas  falaram a respeito de Jesus, dizendo que os que creem nele recebem, por meio dele, o perdão dos pecados.

[[v44-10-44]]

^<<v44-10-44,44>>^ Quando Pedro ainda estava falando, o Espírito Santo desceu sobre todos os que estavam ouvindo a mensagem.

[[v44-10-45]]

^<<v44-10-45,45>>^ Os judeus seguidores de Jesus que tinham vindo de Jope com Pedro ficaram admirados por Deus ter derramado o dom  do Espírito Santo sobre os não judeus.

[[v44-10-46]]

^<<v44-10-46,46>>^ Pois eles ouviam os não judeus falarem em línguas estranhas e louvarem a grandeza de Deus. Então Pedro disse:

[[v44-10-47]]

^<<v44-10-47,47>>^ — Estas pessoas receberam o Espírito Santo como nós também recebemos. Será que alguém vai proibir que sejam batizadas com água?

[[v44-10-48]]

^<<v44-10-48,48>>^ Então mandou que aquelas pessoas fossem batizadas em nome de Jesus Cristo. E elas pediram a Pedro que ficasse ali alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]