include::./index.adoc[]

[[v44-21-0]]
=== Atos, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-21-1]]

^<<v44-21-1,1>>^ Nós nos despedimos deles e fomos embora, navegando diretamente para a ilha de Cós. No dia seguinte paramos no porto de Rodes e dali continuamos até a cidade de Pátara,

[[v44-21-2]]

^<<v44-21-2,2>>^ onde encontramos um navio que ia para a Fenícia. Então embarcamos nele e seguimos viagem.

[[v44-21-3]]

^<<v44-21-3,3>>^ Quando já podíamos ver a ilha de Chipre, navegamos ao sul daquela ilha e seguimos em direção à província  da Síria. Chegamos à cidade de Tiro, onde desembarcamos, pois o navio precisava ser descarregado.

[[v44-21-4]]

^<<v44-21-4,4>>^ Naquela cidade encontramos alguns cristãos e ficamos com eles uma semana. Então, avisados pelo Espírito Santo, eles disseram a Paulo que não fosse para Jerusalém.

[[v44-21-5]]

^<<v44-21-5,5>>^ Mas, quando chegou o dia de irmos embora, nós continuamos a nossa viagem. Aí aqueles irmãos, com as esposas e filhos, nos acompanharam até fora da cidade; e todos nós nos ajoelhamos ali na praia e oramos.

[[v44-21-6]]

^<<v44-21-6,6>>^ Depois de nos despedirmos, embarcamos no navio, e eles voltaram para casa.

[[v44-21-7]]

^<<v44-21-7,7>>^ Seguimos viagem, navegando da cidade de Tiro para Ptolemaida. Ali encontramos e cumprimentamos os irmãos e passamos um dia com eles.

[[v44-21-8]]

^<<v44-21-8,8>>^ No dia seguinte partimos e chegamos à cidade de Cesareia. Ali fomos para a casa do evangelista Filipe e ficamos com ele. Filipe era um dos sete homens que haviam sido escolhidos em Jerusalém.

[[v44-21-9]]

^<<v44-21-9,9>>^ Ele tinha quatro filhas solteiras que profetizavam.

[[v44-21-10]]

^<<v44-21-10,10>>^ Alguns dias depois da nossa chegada, um profeta  chamado Ágabo veio da região da Judeia.

[[v44-21-11]]

^<<v44-21-11,11>>^ Ele chegou perto de nós, pegou o cinto de Paulo, amarrou os próprios pés e as próprias mãos e disse: — O Espírito Santo diz isto: em Jerusalém o dono deste cinto será amarrado assim pelos judeus e será entregue nas mãos dos não judeus.

[[v44-21-12]]

^<<v44-21-12,12>>^ Quando ouvimos isso, nós e os irmãos de Cesareia pedimos com insistência a Paulo que não fosse para Jerusalém.

[[v44-21-13]]

^<<v44-21-13,13>>^ Mas ele respondeu: — Por que vocês choram assim e me deixam tão triste? Eu estou pronto não somente para ser amarrado, mas até para morrer em Jerusalém pela causa do Senhor Jesus.

[[v44-21-14]]

^<<v44-21-14,14>>^ E não conseguimos convencê-lo a não ir. Então desistimos e dissemos: — Que seja feita a vontade do Senhor!

[[v44-21-15]]

^<<v44-21-15,15>>^ Depois de passarmos alguns dias ali, juntamos as nossas coisas e fomos para Jerusalém.

[[v44-21-16]]

^<<v44-21-16,16>>^ Alguns irmãos da cidade de Cesareia nos acompanharam e nos levaram à casa onde íamos ficar hospedados. O dono da casa era Menasom, natural da ilha de Chipre. Fazia muito tempo que ele era cristão.

[[v44-21-17]]

^<<v44-21-17,17>>^ Quando chegamos a Jerusalém, os irmãos nos receberam com muita alegria.

[[v44-21-18]]

^<<v44-21-18,18>>^ No dia seguinte Paulo foi conosco até a casa de Tiago para se encontrar com ele. E todos os presbíteros  da igreja estavam presentes ali.

[[v44-21-19]]

^<<v44-21-19,19>>^ Então Paulo os cumprimentou e deu um relatório completo de tudo o que Deus tinha feito por meio dele entre os não judeus.

[[v44-21-20]]

^<<v44-21-20,20>>^ Depois de o ouvirem, todos eles deram graças a Deus e disseram a Paulo: — Veja bem, irmão! Há milhares de judeus que se tornaram cristãos e todos eles são fiéis à Lei  de Moisés.

[[v44-21-21]]

^<<v44-21-21,21>>^ Eles ouviram dizer que você ensina os judeus que moram em outros países a abandonarem a Lei, dizendo a eles que não circuncidem  os seus filhos, nem respeitem os costumes dos judeus.

[[v44-21-22]]

^<<v44-21-22,22>>^ O que vamos fazer? Com certeza eles já ouviram dizer que você chegou.

[[v44-21-23]]

^<<v44-21-23,23>>^ Portanto, faça o que vamos dizer: estão aqui entre nós quatro homens que têm de cumprir uma promessa a Deus.

[[v44-21-24]]

^<<v44-21-24,24>>^ Então vá, tome parte com eles na cerimônia de purificação  e pague a despesa para que eles possam rapar a cabeça . Assim todos saberão que não é verdade o que se diz de você. Pelo contrário, vão ficar sabendo que, de fato, você vive de acordo com a Lei de Moisés.

[[v44-21-25]]

^<<v44-21-25,25>>^ Mas, quanto aos não judeus que se tornaram cristãos, nós já mandamos uma carta a eles, dizendo o seguinte: "Não comam carne de animais que foram oferecidos em sacrifício  aos ídolos, nem sangue, nem carne de nenhum animal que tenha sido estrangulado. E também não pratiquem imoralidade sexual."

[[v44-21-26]]

^<<v44-21-26,26>>^ Então Paulo falou com os quatro homens e, no dia seguinte, tomou parte com eles na cerimônia de purificação. Depois entrou na área do Templo para avisar quando iam terminar os dias da purificação, isto é, a ocasião em que cada um dos quatro homens deveria oferecer o seu sacrifício.

[[v44-21-27]]

^<<v44-21-27,27>>^ Quando os sete dias da purificação  estavam para acabar, alguns judeus da província  da Ásia viram Paulo na área do Templo . Então atiçaram a multidão, agarraram Paulo

[[v44-21-28]]

^<<v44-21-28,28>>^ e começaram a gritar: — Israelitas, nos ajudem! Este é o homem que vai pelo mundo inteiro falando a todas as pessoas e dizendo mentiras contra o povo de Israel, a Lei  de Moisés e este Templo. E agora ele está trazendo não judeus para dentro da área do Templo, profanando  assim este lugar santo.

[[v44-21-29]]

^<<v44-21-29,29>>^ Eles disseram isso porque tinham visto Trófimo, que era de Éfeso, na cidade com Paulo. E pensavam que Paulo o havia levado para dentro da área do Templo.

[[v44-21-30]]

^<<v44-21-30,30>>^ A confusão se espalhou por toda a cidade, e o povo veio correndo de todos os lados. Eles agarraram Paulo, e o arrastaram para fora da área do Templo, e fecharam os portões.

[[v44-21-31]]

^<<v44-21-31,31>>^ Quando a multidão já ia matar Paulo, o comandante das tropas romanas recebeu a notícia de que toda a cidade de Jerusalém estava em revolta.

[[v44-21-32]]

^<<v44-21-32,32>>^ Então reuniu depressa alguns oficiais e soldados e correu para o meio do povo. Quando a multidão viu o comandante e os soldados, parou logo de bater em Paulo.

[[v44-21-33]]

^<<v44-21-33,33>>^ Aí o comandante chegou perto de Paulo, prendeu-o e mandou amarrá-lo com duas correntes. Depois perguntou: — Quem é este homem? O que foi que ele fez?

[[v44-21-34]]

^<<v44-21-34,34>>^ Mas na multidão uns gritavam uma coisa, outros gritavam outra. A desordem era tão grande, que o comandante não pôde descobrir o que havia acontecido. Então mandou que os soldados levassem Paulo para dentro da fortaleza .

[[v44-21-35]]

^<<v44-21-35,35>>^ Quando chegaram perto da escada, os soldados tiveram de carregar Paulo por causa da violência da multidão

[[v44-21-36]]

^<<v44-21-36,36>>^ que vinha atrás, gritando: — Mata! Mata!

[[v44-21-37]]

^<<v44-21-37,37>>^ Quando iam levar Paulo para dentro da fortaleza, ele disse ao comandante: — Me dê licença para falar uma coisa com o senhor. O comandante perguntou: — Você sabe falar grego ?

[[v44-21-38]]

^<<v44-21-38,38>>^ Por acaso você é aquele egípcio que algum tempo atrás começou uma revolução e levou quatro mil terroristas armados para o deserto?

[[v44-21-39]]

^<<v44-21-39,39>>^ Paulo respondeu: — Eu sou judeu, nascido em Tarso, cidade muito importante da região da Cilícia. Por favor, me deixe falar com o povo.

[[v44-21-40]]

^<<v44-21-40,40>>^ Então o comandante deixou. Paulo ficou de pé na escadaria e fez um sinal com a mão para o povo, pedindo silêncio. Quando todos ficaram calados, Paulo começou a falar em hebraico . Ele disse:

'''

xref:044-atos/044-atos-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-atos/044-atos-022.adoc#v44-22-0[Próximo Capítulo &#62;]