include::./index.adoc[]

[[v44-1-0]]
=== Atos, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-1-1]]

^<<v44-1-1,1>>^ Prezado Teófilo, No primeiro livro que escrevi, contei tudo o que Jesus fez e ensinou, desde o começo do seu trabalho

[[v44-1-2]]

^<<v44-1-2,2>>^ até o dia em que ele foi levado para o céu. Antes de ir para o céu, ele deu ordens, pelo poder do Espírito Santo, aos homens que ele havia escolhido como apóstolos .

[[v44-1-3]]

^<<v44-1-3,3>>^ Depois da sua morte, Jesus apareceu a eles de muitas maneiras, durante quarenta dias, provando, sem deixar dúvida nenhuma, que estava vivo. Os apóstolos viram Jesus, e ele conversava com eles a respeito do Reino de Deus .

[[v44-1-4]]

^<<v44-1-4,4>>^ Um dia, quando estava com os apóstolos, Jesus deu esta ordem: — Fiquem em Jerusalém e esperem até que o Pai lhes dê o que prometeu, conforme eu disse a vocês.

[[v44-1-5]]

^<<v44-1-5,5>>^ Pois, de fato, João batizou com água, mas daqui a poucos dias vocês serão batizados com o Espírito Santo.

[[v44-1-6]]

^<<v44-1-6,6>>^ Certa vez, os apóstolos  estavam reunidos com Jesus. Então lhe perguntaram: — É agora que o senhor vai devolver o Reino  para o povo de Israel?

[[v44-1-7]]

^<<v44-1-7,7>>^ Jesus respondeu: — Não cabe a vocês saber a ocasião ou o dia que o Pai marcou com a sua própria autoridade.

[[v44-1-8]]

^<<v44-1-8,8>>^ Porém, quando o Espírito Santo descer sobre vocês, vocês receberão poder e serão minhas testemunhas em Jerusalém, em toda a Judeia e Samaria e até nos lugares mais distantes da terra.

[[v44-1-9]]

^<<v44-1-9,9>>^ Depois de ter dito isso, Jesus foi levado para o céu diante deles. Então uma nuvem o cobriu, e eles não puderam vê-lo mais.

[[v44-1-10]]

^<<v44-1-10,10>>^ Eles ainda estavam olhando firme para o céu enquanto Jesus subia, quando dois homens vestidos de branco apareceram perto deles

[[v44-1-11]]

^<<v44-1-11,11>>^ e disseram: — Homens da Galileia, por que vocês estão aí olhando para o céu? Esse Jesus que estava com vocês e que foi levado para o céu voltará do mesmo modo que vocês o viram subir.

[[v44-1-12]]

^<<v44-1-12,12>>^ Então os apóstolos  desceram o monte das Oliveiras e voltaram para Jerusalém (o monte fica mais ou menos a um quilômetro da cidade).

[[v44-1-13]]

^<<v44-1-13,13>>^ Quando chegaram à cidade, eles foram até a sala onde estavam hospedados, a qual ficava no andar de cima da casa. Os apóstolos eram estes: Pedro, João, Tiago, André, Filipe, Tomé, Bartolomeu, Mateus, Tiago, filho de Alfeu, Simão, o nacionalista, e Judas, filho de Tiago.

[[v44-1-14]]

^<<v44-1-14,14>>^ Eles sempre se reuniam todos juntos para orar com as mulheres, a mãe de Jesus e os irmãos dele.

[[v44-1-15]]

^<<v44-1-15,15>>^ Num desses dias de reunião, estavam presentes mais ou menos cento e vinte seguidores de Jesus. Nessa reunião Pedro se levantou e disse:

[[v44-1-16]]

^<<v44-1-16,16>>^ — Meus irmãos, tinha de acontecer aquilo que o Espírito Santo, por meio de Davi, disse nas Escrituras Sagradas  a respeito de Judas, que foi o guia daqueles que prenderam Jesus.

[[v44-1-17]]

^<<v44-1-17,17>>^ Judas era do nosso grupo e foi escolhido para tomar parte no nosso trabalho.

[[v44-1-18]]

^<<v44-1-18,18>>^ (Com o dinheiro que tinha recebido pelo seu crime, Judas comprou um terreno. Nesse terreno ele caiu e se arrebentou, e os seus intestinos se esparramaram.

[[v44-1-19]]

^<<v44-1-19,19>>^ Todos os moradores de Jerusalém ficaram sabendo disso. Por isso deram àquele terreno o nome de "Aceldama", que na língua deles quer dizer "Campo de Sangue.")

[[v44-1-20]]

^<<v44-1-20,20>>^ E Pedro continuou: — Isto é o que está escrito no Livro dos Salmos: "Que a casa dele fique abandonada, e ninguém mais more nela!" — E também diz: "Que outra pessoa faça o trabalho que ele fazia!"

[[v44-1-21]]

^<<v44-1-21,21>>^ — Portanto, precisamos escolher outro homem para pertencer ao nosso grupo e ser testemunha junto conosco da ressurreição do Senhor Jesus. Deve ser um daqueles que nos acompanharam durante o tempo em que o Senhor Jesus andou entre nós, desde que foi batizado por João até o dia em que foi levado para o céu.

[[v44-1-22]]

^<<v44-1-22,22>>^ — Portanto, precisamos escolher outro homem para pertencer ao nosso grupo e ser testemunha junto conosco da ressurreição do Senhor Jesus. Deve ser um daqueles que nos acompanharam durante o tempo em que o Senhor Jesus andou entre nós, desde que foi batizado por João até o dia em que foi levado para o céu.

[[v44-1-23]]

^<<v44-1-23,23>>^ E foram apresentados dois homens: José, chamado Barsabás, que tinha o apelido de Justo, e Matias.

[[v44-1-24]]

^<<v44-1-24,24>>^ Em seguida oraram, dizendo: — Senhor, tu conheces o coração de todos. Mostra agora qual dos dois escolheste

[[v44-1-25]]

^<<v44-1-25,25>>^ para trabalhar conosco como apóstolo, pois Judas abandonou este trabalho e foi para o lugar que ele merecia.

'''

xref:043-joao/043-joao-021.adoc#v43-21-0[&#60; Capítulo Anterior] | <<v44-1-0,Topo>> | xref:044-atos/044-atos-002.adoc#v44-2-0[Próximo Capítulo &#62;]