include::./index.adoc[]

[[v44-20-0]]
=== Atos, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-20-1]]

^<<v44-20-1,1>>^ Quando acabou a confusão, Paulo mandou chamar os irmãos e falou com eles para animá-los. Então se despediu deles e foi para a província  da Macedônia.

[[v44-20-2]]

^<<v44-20-2,2>>^ Atravessou aquelas regiões, animando muito com as suas mensagens os cristãos. Aí chegou à província da Acaia,

[[v44-20-3]]

^<<v44-20-3,3>>^ onde ficou três meses. Quando já estava pronto para ir à província da Síria, soube que os judeus estavam fazendo planos contra ele. Então resolveu voltar pela Macedônia.

[[v44-20-4]]

^<<v44-20-4,4>>^ Foram com ele as seguintes pessoas: Sópatro, filho de Pirro, da cidade de Bereia; Aristarco e Segundo, de Tessalônica; Gaio, de Derbe; Timóteo; e também Tíquico e Trófimo, que eram da província da Ásia.

[[v44-20-5]]

^<<v44-20-5,5>>^ Eles foram na frente e nos esperaram na cidade de Trôade.

[[v44-20-6]]

^<<v44-20-6,6>>^ Depois da Festa dos Pães sem Fermento , nós partimos da cidade de Filipos. Cinco dias depois nos encontramos com eles em Trôade e ficamos ali uma semana.

[[v44-20-7]]

^<<v44-20-7,7>>^ No sábado à noite nós nos reunimos com os irmãos para partir o pão . Paulo falou nessa reunião e continuou falando até a meia-noite, pois ia viajar no dia seguinte.

[[v44-20-8]]

^<<v44-20-8,8>>^ Havia muitas lamparinas acesas na sala onde nós estávamos reunidos, a qual ficava no terceiro andar da casa.

[[v44-20-9]]

^<<v44-20-9,9>>^ Um moço chamado Êutico estava sentado numa janela. E, como Paulo continuasse falando durante muito tempo, o sono do moço foi aumentando. De repente, ele dormiu e caiu da janela. Quando o levantaram, estava morto.

[[v44-20-10]]

^<<v44-20-10,10>>^ Então Paulo desceu, abaixou-se, abraçou o moço e disse: — Não se assustem, pois ele está vivo.

[[v44-20-11]]

^<<v44-20-11,11>>^ Em seguida Paulo subiu de novo, partiu o pão e comeu. Falou ainda muito tempo, até de manhã, e depois foi embora.

[[v44-20-12]]

^<<v44-20-12,12>>^ Aí levaram o moço, vivo, para a casa dele, e isso os deixou muito animados.

[[v44-20-13]]

^<<v44-20-13,13>>^ Nós fomos na frente e embarcamos no navio que nos levou até o porto de Assôs, onde devíamos esperar Paulo. Ele mandou que fizéssemos isso porque queria ir por terra até lá.

[[v44-20-14]]

^<<v44-20-14,14>>^ Quando ele se encontrou conosco em Assôs, nós o recebemos no navio e seguimos viagem até a cidade de Mitilene.

[[v44-20-15]]

^<<v44-20-15,15>>^ Então partimos dali e, no dia seguinte, passamos perto da ilha de Quios. No outro dia já estávamos na ilha de Samos e um dia depois chegamos ao porto de Mileto.

[[v44-20-16]]

^<<v44-20-16,16>>^ Paulo tinha resolvido não parar na cidade de Éfeso para não ficar muito tempo na província  da Ásia. Ele estava com pressa, pois queria chegar a Jerusalém, se possível, antes do dia de Pentecostes .

[[v44-20-17]]

^<<v44-20-17,17>>^ Em Mileto Paulo mandou chamar os presbíteros  da igreja de Éfeso para se encontrarem com ele.

[[v44-20-18]]

^<<v44-20-18,18>>^ Quando eles chegaram, Paulo disse: — Vocês sabem como foi que passei todo o tempo que estivemos juntos, desde o primeiro dia em que cheguei à província  da Ásia.

[[v44-20-19]]

^<<v44-20-19,19>>^ Fiz o meu trabalho como servo  do Senhor, com toda a humildade e com lágrimas. E isso apesar dos tempos difíceis que tive, por causa dos judeus que se juntavam contra mim.

[[v44-20-20]]

^<<v44-20-20,20>>^ Vocês também sabem que fiz tudo para ajudar vocês, anunciando o evangelho  e ensinando publicamente e nas casas.

[[v44-20-21]]

^<<v44-20-21,21>>^ Eu disse com firmeza aos judeus e aos não judeus que eles deviam se arrepender dos seus pecados, voltar para Deus e crer no nosso Senhor Jesus.

[[v44-20-22]]

^<<v44-20-22,22>>^ Agora eu vou para Jerusalém, obedecendo ao Espírito Santo, sem saber o que vai me acontecer lá.

[[v44-20-23]]

^<<v44-20-23,23>>^ Sei somente que em todas as cidades o Espírito Santo tem me avisado que prisões e sofrimentos estão me esperando.

[[v44-20-24]]

^<<v44-20-24,24>>^ Mas eu não dou valor à minha própria vida. O importante é que eu complete a minha missão e termine o trabalho que o Senhor Jesus me deu para fazer. E a missão é esta: anunciar a boa notícia da graça  de Deus.

[[v44-20-25]]

^<<v44-20-25,25>>^ — Eu tenho estado entre vocês, anunciando o Reino de Deus , e agora sei que vocês não vão me ver mais.

[[v44-20-26]]

^<<v44-20-26,26>>^ Por isso, com toda a certeza eu afirmo hoje que, se algum de vocês se perder, eu não sou o responsável.

[[v44-20-27]]

^<<v44-20-27,27>>^ Pois não deixei de lhes anunciar todo o plano de Deus.

[[v44-20-28]]

^<<v44-20-28,28>>^ Cuidem de vocês mesmos e de todo o rebanho que o Espírito Santo entregou aos seus cuidados, como pastores da Igreja de Deus, que ele comprou por meio do sangue do seu próprio Filho.

[[v44-20-29]]

^<<v44-20-29,29>>^ Pois eu sei que, depois que eu for, aparecerão lobos ferozes no meio de vocês e eles não terão pena do rebanho.

[[v44-20-30]]

^<<v44-20-30,30>>^ E chegará o tempo em que alguns de vocês contarão mentiras, procurando levar os irmãos para o seu lado.

[[v44-20-31]]

^<<v44-20-31,31>>^ Portanto, fiquem vigiando e lembrem que durante três anos, de dia e de noite, eu, chorando, não parei de ensinar cada um de vocês.

[[v44-20-32]]

^<<v44-20-32,32>>^ — E agora eu os entrego aos cuidados de Deus e da palavra da sua graça. Pois ele pode ajudá-los a progredir espiritualmente e pode dar-lhes as bênçãos que guarda para todo o seu povo.

[[v44-20-33]]

^<<v44-20-33,33>>^ Não cobicei nem a prata, nem o ouro, nem as roupas de ninguém.

[[v44-20-34]]

^<<v44-20-34,34>>^ Pelo contrário, vocês sabem que eu trabalhei com as minhas próprias mãos e consegui tudo o que eu e os meus companheiros de trabalho precisávamos.

[[v44-20-35]]

^<<v44-20-35,35>>^ Em tudo tenho mostrado a vocês que é trabalhando assim que podemos ajudar os necessitados. Lembrem das palavras do Senhor Jesus: "É mais feliz quem dá do que quem recebe."

[[v44-20-36]]

^<<v44-20-36,36>>^ Quando Paulo acabou de falar, ajoelhou-se com os irmãos e orou.

[[v44-20-37]]

^<<v44-20-37,37>>^ Então todos choraram muito e abraçaram e beijaram Paulo.

[[v44-20-38]]

^<<v44-20-38,38>>^ Estavam tristes, especialmente porque ele lhes tinha dito que nunca mais iam vê-lo. Então eles o acompanharam até o navio.

'''

xref:044-atos/044-atos-019.adoc#v44-19-0[&#60; Capítulo Anterior] | <<v44-20-0,Topo>> | xref:044-atos/044-atos-021.adoc#v44-21-0[Próximo Capítulo &#62;]