include::./index.adoc[]

[[v44-26-0]]
=== Atos, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-26-1]]

^<<v44-26-1,1>>^ Agripa disse a Paulo: — Você pode apresentar a sua defesa. Então Paulo estendeu a mão e fez a sua defesa, dizendo o seguinte:

[[v44-26-2]]

^<<v44-26-2,2>>^ — Rei Agripa, eu me sinto muito feliz em poder estar hoje diante do senhor para me defender de tudo o que os judeus me acusam.

[[v44-26-3]]

^<<v44-26-3,3>>^ E especialmente feliz porque o senhor conhece muito bem todos os costumes e questões dos judeus. Portanto, peço que o senhor me escute com paciência.

[[v44-26-4]]

^<<v44-26-4,4>>^ — Todos os judeus sabem como tenho vivido no meio do meu povo e também em Jerusalém, desde a minha juventude até hoje.

[[v44-26-5]]

^<<v44-26-5,5>>^ Eles sempre souberam — e podem confirmar isso se quiserem — que desde o começo fui membro do partido dos fariseus , o mais rigoroso da nossa religião.

[[v44-26-6]]

^<<v44-26-6,6>>^ E agora estou aqui sendo julgado porque tenho esperança na promessa que Deus fez aos nossos antepassados.

[[v44-26-7]]

^<<v44-26-7,7>>^ Todas as tribos  do nosso povo, que adoram a Deus dia e noite, também esperam ver o cumprimento dessa promessa. É por causa dessa esperança, ó rei, que estou sendo acusado pelos judeus.

[[v44-26-8]]

^<<v44-26-8,8>>^ Por que é que vocês, judeus, acham impossível crer que Deus ressuscita os mortos?

[[v44-26-9]]

^<<v44-26-9,9>>^ E Paulo disse ainda: — Eu mesmo pensava que devia fazer tudo o que pudesse contra a causa de Jesus de Nazaré.

[[v44-26-10]]

^<<v44-26-10,10>>^ E foi o que fiz em Jerusalém. Recebi autorização dos chefes dos sacerdotes e prendi muitos seguidores de Jesus. Quando eram condenados à morte, eu também votava contra eles.

[[v44-26-11]]

^<<v44-26-11,11>>^ Durante muito tempo eu os castiguei em todas as sinagogas  e os forcei a negar a sua fé. Tinha tanto ódio deles, que até fui a outras cidades para persegui-los.

[[v44-26-12]]

^<<v44-26-12,12>>^ E Paulo continuou: — Foi por isso que viajei para a cidade de Damasco, levando autorização e ordens dos chefes dos sacerdotes.

[[v44-26-13]]

^<<v44-26-13,13>>^ Mas aconteceu, ó rei, que na estrada, ao meio-dia, veio do céu uma luz mais brilhante do que o sol, a qual brilhou em volta de mim e dos homens que estavam viajando comigo.

[[v44-26-14]]

^<<v44-26-14,14>>^ Todos nós caímos no chão, e eu ouvi uma voz me dizer em hebraico : "Saulo, Saulo! Por que você me persegue? Não adianta você se revoltar contra mim."

[[v44-26-15]]

^<<v44-26-15,15>>^ — Então eu perguntei: "Quem é o senhor?" — E o Senhor respondeu: "Eu sou Jesus, aquele que você persegue.

[[v44-26-16]]

^<<v44-26-16,16>>^ Mas levante-se e fique de pé. Eu apareci a você para o escolher como meu servo , a fim de que você conte aos outros o que viu hoje e anuncie o que lhe vou mostrar depois.

[[v44-26-17]]

^<<v44-26-17,17>>^ Vou livrar você dos judeus e também dos não judeus, a quem vou enviá-lo.

[[v44-26-18]]

^<<v44-26-18,18>>^ Você vai abrir os olhos deles a fim de que eles saiam da escuridão para a luz e do poder de Satanás para Deus. Então, por meio da fé em mim, eles serão perdoados dos seus pecados e passarão a ser parte do povo escolhido de Deus."

[[v44-26-19]]

^<<v44-26-19,19>>^ E Paulo terminou, dizendo: — Portanto, ó rei Agripa, eu não desobedeci à visão que veio do céu.

[[v44-26-20]]

^<<v44-26-20,20>>^ Anunciei a mensagem primeiro em Damasco e depois em Jerusalém, em toda a região da Judeia e entre os não judeus. Eu dizia a todos que eles precisavam abandonar os seus pecados, voltar para Deus e fazer coisas que mostrassem que estavam, de fato, arrependidos.

[[v44-26-21]]

^<<v44-26-21,21>>^ Foi por isso que alguns judeus me agarraram quando eu estava no pátio do Templo e quiseram me matar.

[[v44-26-22]]

^<<v44-26-22,22>>^ Mas até hoje Deus tem me ajudado, e por isso estou aqui trazendo a sua mensagem a todos, tanto aos humildes como aos importantes. Pois eu digo a mesma coisa que os profetas  e Moisés disseram que ia acontecer.

[[v44-26-23]]

^<<v44-26-23,23>>^ Eles afirmaram que o Messias  precisava sofrer e ser o primeiro a ressuscitar, para anunciar a luz da salvação tanto aos judeus como aos não judeus.

[[v44-26-24]]

^<<v44-26-24,24>>^ Quando Paulo estava se defendendo assim, Festo gritou: — Paulo, você está louco! Estudou tanto, que acabou perdendo o juízo!

[[v44-26-25]]

^<<v44-26-25,25>>^ Paulo respondeu: — Eu não estou louco, Excelência; estou em perfeito juízo e digo a verdade.

[[v44-26-26]]

^<<v44-26-26,26>>^ Eu posso falar diante do rei Agripa com toda a coragem porque tenho a certeza de que ele conhece todas essas coisas muito bem, pois não aconteceram em nenhum lugar escondido.

[[v44-26-27]]

^<<v44-26-27,27>>^ Então Paulo disse ao rei: — Rei Agripa, o senhor crê nos profetas? Eu sei que crê!

[[v44-26-28]]

^<<v44-26-28,28>>^ Agripa respondeu: — Você pensa que assim, em tão pouco tempo, vai me tornar cristão?

[[v44-26-29]]

^<<v44-26-29,29>>^ Paulo disse: — Pois eu pediria a Deus que, em pouco ou muito tempo, não somente o senhor, mas todos os que estão me ouvindo hoje chegassem a ser como eu, mas sem estas correntes.

[[v44-26-30]]

^<<v44-26-30,30>>^ Aí o rei Agripa, o Governador, Berenice e todos os que estavam com eles se levantaram

[[v44-26-31]]

^<<v44-26-31,31>>^ e saíram, comentando: — Este homem não fez nada para merecer a morte, nem para estar preso.

[[v44-26-32]]

^<<v44-26-32,32>>^ Então Agripa disse a Festo: — Ele já podia estar solto se não tivesse pedido para ser julgado pelo Imperador.

'''

xref:044-atos/044-atos-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-atos/044-atos-027.adoc#v44-27-0[Próximo Capítulo &#62;]