include::./index.adoc[]

[[v44-12-0]]
=== Atos, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-12-1]]

^<<v44-12-1,1>>^ Por essa época o rei Herodes começou a perseguir algumas pessoas da igreja.

[[v44-12-2]]

^<<v44-12-2,2>>^ Ele mandou matar à espada Tiago, o irmão de João.

[[v44-12-3]]

^<<v44-12-3,3>>^ Quando viu que isso agradou os judeus, mandou também prender Pedro. Isso aconteceu durante a Festa dos Pães sem Fermento .

[[v44-12-4]]

^<<v44-12-4,4>>^ Depois que prendeu Pedro, Herodes o colocou na cadeia e pôs quatro grupos de soldados, com quatro em cada grupo, para guardá-lo. É que Herodes queria apresentá-lo ao povo depois do dia da Páscoa .

[[v44-12-5]]

^<<v44-12-5,5>>^ E assim Pedro estava preso e era vigiado pelos guardas; mas a igreja continuava a orar com fervor por ele.

[[v44-12-6]]

^<<v44-12-6,6>>^ Na noite antes do dia em que Herodes ia apresentá-lo ao povo, Pedro estava dormindo, preso com duas correntes, entre dois soldados; e havia guardas de vigia no portão da cadeia.

[[v44-12-7]]

^<<v44-12-7,7>>^ De repente, apareceu um anjo do Senhor, e uma luz brilhou dentro da cela. O anjo tocou no ombro de Pedro, acordou-o e disse: — Levante-se depressa! Então as correntes caíram das mãos dele.

[[v44-12-8]]

^<<v44-12-8,8>>^ — Aperte o cinto e amarre as sandálias! — disse o anjo. E Pedro fez o que o anjo mandou. — Ponha a capa  e venha comigo! — ordenou o anjo.

[[v44-12-9]]

^<<v44-12-9,9>>^ Pedro saiu da cadeia e foi seguindo o anjo. Porém não sabia se, de fato, o anjo o estava libertando. Ele pensava que aquilo era uma visão.

[[v44-12-10]]

^<<v44-12-10,10>>^ Eles passaram pelo primeiro e pelo segundo posto da guarda e chegaram ao portão de ferro que dava para a rua. O portão se abriu sozinho, e eles saíram. Andaram por uma rua, e, de repente, o anjo foi embora.

[[v44-12-11]]

^<<v44-12-11,11>>^ Então Pedro compreendeu o que estava acontecendo e disse: — Agora sei que, de fato, o Senhor mandou o seu anjo e me livrou do poder de Herodes e de tudo o que os judeus tinham a intenção de me fazer.

[[v44-12-12]]

^<<v44-12-12,12>>^ Quando Pedro entendeu o que havia acontecido, foi para a casa de Maria, a mãe de João Marcos. Muitas pessoas estavam reunidas ali, orando.

[[v44-12-13]]

^<<v44-12-13,13>>^ Ele bateu na porta da frente, e a empregada, que se chamava Rode, foi ver quem era.

[[v44-12-14]]

^<<v44-12-14,14>>^ Quando reconheceu a voz de Pedro, ficou tão contente, que, em vez de abrir a porta, voltou correndo para contar que Pedro estava lá fora.

[[v44-12-15]]

^<<v44-12-15,15>>^ Então eles disseram: — Você está maluca! Porém ela insistiu que era verdade. Aí eles disseram: — É o anjo dele!

[[v44-12-16]]

^<<v44-12-16,16>>^ Enquanto isso, Pedro continuava batendo. Finalmente eles abriram a porta e, quando viram que era Pedro mesmo, ficaram muito assustados.

[[v44-12-17]]

^<<v44-12-17,17>>^ Ele fez um sinal com a mão para que ficassem quietos e contou como o Senhor o tinha tirado da prisão. — Contem isso a Tiago e aos outros irmãos! — disse ele. Em seguida saiu dali e foi para outro lugar.

[[v44-12-18]]

^<<v44-12-18,18>>^ Quando amanheceu, houve uma grande confusão entre os soldados, pois eles não sabiam o que tinha acontecido com Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ Herodes mandou que o procurassem, mas não o acharam. Então, depois de fazer perguntas aos guardas, mandou matá-los. Depois disso, Herodes saiu da região da Judeia e ficou algum tempo na cidade de Cesareia.

[[v44-12-20]]

^<<v44-12-20,20>>^ O rei Herodes estava com muita raiva dos moradores das cidades de Tiro e de Sidom. Então eles formaram um grupo e foram falar com Herodes. Primeiro conseguiram o apoio de Blasto, que era um alto funcionário do palácio. Aí pediram ao rei Herodes que fizesse as pazes com eles, pois os alimentos que a região deles recebia vinham do país do rei.

[[v44-12-21]]

^<<v44-12-21,21>>^ Herodes marcou um dia com eles e nesse dia vestiu a sua roupa de rei, sentou-se no trono e começou a fazer um discurso.

[[v44-12-22]]

^<<v44-12-22,22>>^ E o povo gritava: — É um deus e não um homem que está falando!

[[v44-12-23]]

^<<v44-12-23,23>>^ No mesmo instante um anjo do Senhor feriu Herodes, pois ele aceitou a honra que só Deus merece. E ele morreu, comido por vermes.

[[v44-12-24]]

^<<v44-12-24,24>>^ Porém a palavra de Deus era anunciada em toda parte e ia se espalhando.

[[v44-12-25]]

^<<v44-12-25,25>>^ Barnabé e Saulo terminaram o seu trabalho e voltaram de Jerusalém, trazendo João Marcos consigo.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]