include::./index.adoc[]

[[v44-5-0]]
=== Atos, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-5-1]]

^<<v44-5-1,1>>^ Mas um homem chamado Ananias, casado com uma mulher que se chamava Safira, vendeu um terreno

[[v44-5-2]]

^<<v44-5-2,2>>^ e só entregou uma parte do dinheiro aos apóstolos , ficando com o resto. E Safira sabia disso.

[[v44-5-3]]

^<<v44-5-3,3>>^ Então Pedro disse a Ananias: — Por que você deixou Satanás dominar o seu coração? Por que mentiu para o Espírito Santo? Por que você ficou com uma parte do dinheiro que recebeu pela venda daquele terreno?

[[v44-5-4]]

^<<v44-5-4,4>>^ Antes de você vendê-lo, ele era seu; e, depois de vender, o dinheiro também era seu. Então por que resolveu fazer isso? Você não mentiu para seres humanos — mentiu para Deus!

[[v44-5-5]]

^<<v44-5-5,5>>^ Assim que ouviu isso, Ananias caiu morto; e todos os que souberam do que havia acontecido ficaram com muito medo.

[[v44-5-6]]

^<<v44-5-6,6>>^ Então vieram alguns moços, cobriram o corpo de Ananias, levaram para fora e o sepultaram.

[[v44-5-7]]

^<<v44-5-7,7>>^ A mulher de Ananias chegou umas três horas depois, sem saber do que havia acontecido com o marido.

[[v44-5-8]]

^<<v44-5-8,8>>^ Aí Pedro perguntou a ela: — Me diga! Foi por este preço que você e o seu marido venderam o terreno? — Foi! — respondeu ela.

[[v44-5-9]]

^<<v44-5-9,9>>^ Então Pedro disse: — Por que você e o seu marido resolveram pôr à prova o Espírito do Senhor? Os moços que acabaram de sepultar o seu marido já estão lá na porta e agora vão levar você também.

[[v44-5-10]]

^<<v44-5-10,10>>^ No mesmo instante ela caiu morta aos pés de Pedro. Os moços entraram e, vendo que ela estava morta, levaram o corpo dela e o sepultaram ao lado do marido.

[[v44-5-11]]

^<<v44-5-11,11>>^ E toda a igreja e todos aqueles que souberam disso ficaram apavorados.

[[v44-5-12]]

^<<v44-5-12,12>>^ Os apóstolos  faziam muitos milagres e maravilhas entre o povo, e os seguidores de Jesus se reuniam no Alpendre de Salomão .

[[v44-5-13]]

^<<v44-5-13,13>>^ Ninguém de fora tinha coragem de se juntar ao grupo deles, mas o povo falava muito bem deles.

[[v44-5-14]]

^<<v44-5-14,14>>^ Uma multidão de homens e mulheres também creu no Senhor e veio aumentar ainda mais o grupo.

[[v44-5-15]]

^<<v44-5-15,15>>^ Por causa dos milagres que os apóstolos faziam, as pessoas punham os doentes nas ruas, em camas e esteiras. Faziam isso para que, quando Pedro passasse, pelo menos a sua sombra cobrisse alguns deles.

[[v44-5-16]]

^<<v44-5-16,16>>^ Multidões vinham das cidades vizinhas de Jerusalém trazendo os seus doentes e os que eram dominados por espíritos maus, e todos eram curados.

[[v44-5-17]]

^<<v44-5-17,17>>^ Então o Grande Sacerdote  e todos os seus companheiros, que eram do partido dos saduceus , ficaram com inveja dos apóstolos  e resolveram fazer alguma coisa.

[[v44-5-18]]

^<<v44-5-18,18>>^ Prenderam os apóstolos e os puseram na cadeia.

[[v44-5-19]]

^<<v44-5-19,19>>^ Mas naquela noite um anjo do Senhor abriu os portões da cadeia, levou os apóstolos para fora e disse:

[[v44-5-20]]

^<<v44-5-20,20>>^ — Vão para o Templo e anunciem ao povo tudo a respeito desta nova vida.

[[v44-5-21]]

^<<v44-5-21,21>>^ Os apóstolos obedeceram e no dia seguinte, bem cedo, entraram no pátio do Templo e começaram a ensinar. Então o Grande Sacerdote e os seus companheiros chamaram os líderes do povo para uma reunião do Conselho Superior . Depois mandaram que alguns guardas do Templo fossem buscar os apóstolos na cadeia.

[[v44-5-22]]

^<<v44-5-22,22>>^ Porém, quando os guardas chegaram lá, não encontraram os apóstolos. Então voltaram para o lugar onde o Conselho estava reunido

[[v44-5-23]]

^<<v44-5-23,23>>^ e disseram: — Nós fomos até lá e encontramos a cadeia bem-fechada, e os guardas vigiando os portões; mas, quando os abrimos, não achamos ninguém lá dentro.

[[v44-5-24]]

^<<v44-5-24,24>>^ Quando os chefes dos sacerdotes e o chefe da guarda do Templo ouviram isso, ficaram sem saber o que pensar sobre o que havia acontecido com os apóstolos.

[[v44-5-25]]

^<<v44-5-25,25>>^ Nesse momento chegou alguém, dizendo: — Escutem! Os homens que vocês prenderam estão lá no pátio do Templo ensinando o povo!

[[v44-5-26]]

^<<v44-5-26,26>>^ Então o chefe da guarda do Templo e os seus homens saíram e trouxeram os apóstolos. Mas não os maltrataram porque tinham medo de serem apedrejados pelo povo.

[[v44-5-27]]

^<<v44-5-27,27>>^ Depois puseram os apóstolos em frente do Conselho. E o Grande Sacerdote disse:

[[v44-5-28]]

^<<v44-5-28,28>>^ — Nós ordenamos que vocês não ensinassem nada a respeito daquele homem. E o que foi que vocês fizeram? Espalharam esse ensinamento por toda a cidade de Jerusalém e ainda querem nos culpar pela morte dele!

[[v44-5-29]]

^<<v44-5-29,29>>^ Então Pedro e os outros apóstolos responderam: — Nós devemos obedecer a Deus e não às pessoas.

[[v44-5-30]]

^<<v44-5-30,30>>^ Os senhores crucificaram Jesus, mas o Deus dos nossos antepassados o ressuscitou.

[[v44-5-31]]

^<<v44-5-31,31>>^ E Deus o colocou à sua direita como Líder e Salvador, para dar ao povo de Israel oportunidade de se arrepender e receber o perdão dos seus pecados.

[[v44-5-32]]

^<<v44-5-32,32>>^ Nós somos testemunhas de tudo isso — nós e o Espírito Santo, que Deus dá aos que lhe obedecem.

[[v44-5-33]]

^<<v44-5-33,33>>^ Quando os membros do Conselho ouviram isso, ficaram com tanta raiva, que resolveram matar os apóstolos.

[[v44-5-34]]

^<<v44-5-34,34>>^ Mas levantou-se um dos membros do Conselho, um fariseu  chamado Gamaliel, que era um mestre da Lei  respeitado por todos. Ele mandou que levassem os apóstolos para fora e os deixassem ali um pouco.

[[v44-5-35]]

^<<v44-5-35,35>>^ Então disse ao Conselho: — Homens de Israel, cuidado com o que vão fazer com estes homens.

[[v44-5-36]]

^<<v44-5-36,36>>^ Há pouco tempo apareceu um homem chamado Teudas, que se dizia muito importante e que com isso conseguiu reunir quatrocentos seguidores. Mas ele foi morto, todos os seus seguidores foram espalhados, e a revolta dele fracassou.

[[v44-5-37]]

^<<v44-5-37,37>>^ Depois disso apareceu Judas, o Galileu, na época do recenseamento. Este também conseguiu juntar muita gente, mas foi morto, e todos os seus seguidores foram espalhados.

[[v44-5-38]]

^<<v44-5-38,38>>^ Portanto, neste caso de agora, não façam nada contra estes homens. Deixem que vão embora porque, se este plano ou este trabalho vem de seres humanos, ele desaparecerá.

[[v44-5-39]]

^<<v44-5-39,39>>^ Mas, se vem de Deus, vocês não poderão destruí-lo, pois neste caso estariam lutando contra Deus. E o Conselho aceitou a opinião de Gamaliel.

[[v44-5-40]]

^<<v44-5-40,40>>^ Então chamaram os apóstolos e os chicotearam; e aí mandaram que nunca mais falassem nada a respeito de Jesus. Depois os soltaram.

[[v44-5-41]]

^<<v44-5-41,41>>^ Os apóstolos saíram do Conselho muito alegres porque Deus havia achado que eles eram dignos de serem insultados por serem seguidores de Jesus.

[[v44-5-42]]

^<<v44-5-42,42>>^ E, todos os dias, no pátio do Templo e de casa em casa, eles continuavam a ensinar e a anunciar a boa notícia a respeito de Jesus, o Messias .

'''

xref:044-atos/044-atos-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-atos/044-atos-006.adoc#v44-6-0[Próximo Capítulo &#62;]