include::./index.adoc[]

[[v44-14-0]]
=== Atos, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-14-1]]

^<<v44-14-1,1>>^ A mesma coisa aconteceu na cidade de Icônio. Paulo e Barnabé entraram na sinagoga  e falaram de tal maneira, que muitos judeus e não judeus creram.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus que não creram atiçaram os não judeus contra os cristãos.

[[v44-14-3]]

^<<v44-14-3,3>>^ Os apóstolos  ficaram muito tempo em Icônio, falando com coragem a respeito do Senhor Jesus. E o Senhor mostrava que a mensagem deles sobre a sua graça  era verdadeira, pois ele dava a eles o poder de fazer milagres e maravilhas.

[[v44-14-4]]

^<<v44-14-4,4>>^ Os moradores da cidade estavam divididos: alguns apoiavam os judeus, e outros eram a favor dos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ Então os não judeus e os judeus, juntos com os seus chefes, resolveram maltratar os apóstolos e matá-los a pedradas.

[[v44-14-6]]

^<<v44-14-6,6>>^ Quando Paulo e Barnabé souberam disso, fugiram para Listra e Derbe, cidades do distrito da Licaônia, e para as regiões vizinhas.

[[v44-14-7]]

^<<v44-14-7,7>>^ E ali anunciaram o evangelho .

[[v44-14-8]]

^<<v44-14-8,8>>^ Na cidade de Listra havia um homem que estava sempre sentado porque era aleijado dos pés. Ele havia nascido aleijado e nunca tinha andado.

[[v44-14-9]]

^<<v44-14-9,9>>^ Esse homem ouviu as palavras de Paulo, e Paulo viu que ele cria que podia ser curado. Então olhou firmemente para ele

[[v44-14-10]]

^<<v44-14-10,10>>^ e disse em voz alta: — Levante-se e fique de pé! O homem pulou de pé e começou a andar.

[[v44-14-11]]

^<<v44-14-11,11>>^ Quando o povo viu o que Paulo havia feito, começou a gritar na sua própria língua: — Os deuses tomaram a forma de homens e desceram até nós!

[[v44-14-12]]

^<<v44-14-12,12>>^ Eles deram o nome de Júpiter a Barnabé e o de Mercúrio a Paulo, porque era Paulo quem falava.

[[v44-14-13]]

^<<v44-14-13,13>>^ O templo de Júpiter ficava na entrada da cidade, e o sacerdote desse deus trouxe bois e coroas de flores para o portão da cidade. Ele e o povo queriam matar os animais numa cerimônia religiosa e oferecê-los em sacrifício  a Barnabé e a Paulo.

[[v44-14-14]]

^<<v44-14-14,14>>^ Quando os dois apóstolos  souberam disso, rasgaram as suas roupas, correram para o meio da multidão e gritaram:

[[v44-14-15]]

^<<v44-14-15,15>>^ — Amigos, por que vocês estão fazendo isso? Nós somos apenas seres humanos, como vocês. Estamos aqui anunciando o evangelho  a vocês para que abandonem essas coisas que não servem para nada. Convertam-se ao Deus vivo, que fez o céu, a terra, o mar e tudo o que existe neles.

[[v44-14-16]]

^<<v44-14-16,16>>^ No passado Deus deixou que todos os povos andassem nos seus próprios caminhos.

[[v44-14-17]]

^<<v44-14-17,17>>^ Mas Deus sempre mostra quem ele é por meio das coisas boas que faz: é ele quem manda as chuvas do céu e as colheitas no tempo certo; é ele quem dá também alimento para vocês e enche o coração de vocês de alegria.

[[v44-14-18]]

^<<v44-14-18,18>>^ Mesmo depois de terem dito isso, os apóstolos tiveram muita dificuldade para evitar que o povo matasse os animais em sacrifício a eles.

[[v44-14-19]]

^<<v44-14-19,19>>^ Alguns judeus que tinham vindo das cidades de Antioquia e de Icônio conseguiram o apoio da multidão, apedrejaram Paulo e o arrastaram para fora da cidade, porque pensavam que ele tinha morrido.

[[v44-14-20]]

^<<v44-14-20,20>>^ Mas, quando os cristãos se ajuntaram em volta dele, ele se levantou e entrou na cidade de novo. E no dia seguinte Paulo e Barnabé partiram para a cidade de Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ Paulo e Barnabé anunciaram o evangelho  em Derbe, e muitos moradores daquela cidade se tornaram seguidores de Jesus. Depois voltaram para as cidades de Listra, Icônio e Antioquia da Pisídia.

[[v44-14-22]]

^<<v44-14-22,22>>^ Eles animavam os cristãos e lhes davam coragem para ficarem firmes na fé. E também ensinavam que era preciso passar por muitos sofrimentos para poder entrar no Reino de Deus .

[[v44-14-23]]

^<<v44-14-23,23>>^ Em cada igreja os apóstolos  escolhiam presbíteros . Eles oravam, jejuavam e entregavam os presbíteros à proteção do Senhor, em quem estes haviam crido.

[[v44-14-24]]

^<<v44-14-24,24>>^ Então Paulo e Barnabé atravessaram o distrito da Pisídia e chegaram até a província  da Panfília.

[[v44-14-25]]

^<<v44-14-25,25>>^ Anunciaram a palavra em Perge e depois foram para o porto de Atália.

[[v44-14-26]]

^<<v44-14-26,26>>^ Dali foram de navio para Antioquia da Síria, onde eles haviam sido entregues aos cuidados de Deus, para o trabalho que agora estavam terminando.

[[v44-14-27]]

^<<v44-14-27,27>>^ Quando chegaram lá, reuniram as pessoas da igreja e contaram tudo o que Deus havia feito por meio deles. E contaram como ele tinha aberto o caminho para que os não judeus também cressem.

[[v44-14-28]]

^<<v44-14-28,28>>^ E ficaram muito tempo ali com os seguidores de Jesus.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]