include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-16-1]]

^<<v44-16-1,1>>^ Paulo chegou às cidades de Derbe e Listra. Em Listra morava um cristão chamado Timóteo. A mãe dele, uma cristã, era da raça dos judeus, mas o pai dele não era judeu.

[[v44-16-2]]

^<<v44-16-2,2>>^ Todos os irmãos que moravam em Listra e Icônio falavam bem de Timóteo.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo quis levá-lo consigo e por isso o circuncidou , pois todos os judeus que moravam naqueles lugares sabiam que o pai de Timóteo não era judeu.

[[v44-16-4]]

^<<v44-16-4,4>>^ Nas cidades por onde passavam, eles diziam aos cristãos quais as decisões que tinham sido tomadas pelos apóstolos  e pelos presbíteros  da igreja de Jerusalém e aconselhavam que eles obedecessem a essas decisões.

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim as igrejas ficavam mais fortes na fé, e o número de cristãos aumentava cada dia mais.

[[v44-16-6]]

^<<v44-16-6,6>>^ Como o Espírito Santo não deixou que anunciassem a palavra na província  da Ásia, eles atravessaram a região da Frígia-Galácia.

[[v44-16-7]]

^<<v44-16-7,7>>^ Quando chegaram perto do distrito da Mísia, tentaram ir para a província da Bitínia, mas o Espírito de Jesus não deixou.

[[v44-16-8]]

^<<v44-16-8,8>>^ Então atravessaram a Mísia e chegaram à cidade de Trôade.

[[v44-16-9]]

^<<v44-16-9,9>>^ Naquela noite Paulo teve uma visão. Ele viu um homem da província da Macedônia, que estava de pé e lhe pedia: "Venha para a Macedônia e nos ajude!"

[[v44-16-10]]

^<<v44-16-10,10>>^ Logo depois dessa visão, nós resolvemos partir logo para a Macedônia, pois estávamos certos de que Deus nos havia chamado para anunciar o evangelho  ao povo dali.

[[v44-16-11]]

^<<v44-16-11,11>>^ Nós embarcamos em Trôade e fomos diretamente para a ilha de Samotrácia. No dia seguinte chegamos ao porto de Neápolis.

[[v44-16-12]]

^<<v44-16-12,12>>^ Dali fomos a Filipos, que é uma cidade do primeiro distrito da província  da Macedônia e também colônia romana, onde ficamos vários dias.

[[v44-16-13]]

^<<v44-16-13,13>>^ No sábado saímos da cidade e fomos para a beira do rio, pois pensávamos que ali devia haver um lugar de oração para os judeus. Sentamos e começamos a conversar com as mulheres que estavam reunidas lá.

[[v44-16-14]]

^<<v44-16-14,14>>^ Uma daquelas mulheres que estavam nos ouvindo era Lídia, uma vendedora de púrpura , da cidade de Tiatira. Ela adorava a Deus, e o Senhor abriu a mente dela para que compreendesse o que Paulo dizia.

[[v44-16-15]]

^<<v44-16-15,15>>^ Ela e as pessoas da sua casa foram batizadas. Depois Lídia nos convidou, dizendo: — Venham ficar na minha casa, se é que vocês acham que, de fato, eu creio no Senhor. Assim ela nos convenceu a ficar na casa dela.

[[v44-16-16]]

^<<v44-16-16,16>>^ Certo dia, quando estávamos indo para o lugar de oração, veio ao nosso encontro uma escrava. Essa moça estava dominada por um espírito mau que adivinhava o futuro, e os seus donos ganhavam muito dinheiro com as adivinhações que ela fazia.

[[v44-16-17]]

^<<v44-16-17,17>>^ A moça começou a nos seguir, gritando assim: — Estes homens são servos  do Deus Altíssimo e anunciam como vocês podem ser salvos!

[[v44-16-18]]

^<<v44-16-18,18>>^ Ela fez isso muitos dias. Por fim Paulo se aborreceu, virou-se para ela e ordenou ao espírito: — Pelo poder do nome de Jesus Cristo, eu mando que você saia desta moça! E, no mesmo instante, o espírito saiu.

[[v44-16-19]]

^<<v44-16-19,19>>^ Quando os donos da moça viram que não iam poder mais ganhar dinheiro com as adivinhações dela, agarraram Paulo e Silas e os arrastaram até a praça pública, diante das autoridades.

[[v44-16-20]]

^<<v44-16-20,20>>^ Eles os apresentaram a essas autoridades romanas e disseram: — Estes homens são judeus e estão provocando desordem na nossa cidade.

[[v44-16-21]]

^<<v44-16-21,21>>^ Estão ensinando costumes que são contra a nossa lei . Nós, que somos romanos, não podemos aceitar esses costumes.

[[v44-16-22]]

^<<v44-16-22,22>>^ Aí uma multidão se ajuntou para atacar Paulo e Silas. As autoridades mandaram que tirassem as roupas deles e os surrassem com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ Depois de baterem muito neles, as autoridades jogaram os dois na cadeia e deram ordem ao carcereiro para guardá-los com toda a segurança.

[[v44-16-24]]

^<<v44-16-24,24>>^ Depois de receber essa ordem, o carcereiro os jogou numa cela que ficava no fundo da cadeia e prendeu os pés deles entre dois blocos de madeira.

[[v44-16-25]]

^<<v44-16-25,25>>^ Mais ou menos à meia-noite, Paulo e Silas estavam orando e cantando hinos a Deus, e os outros presos escutavam.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente, o chão tremeu tanto, que abalou os alicerces da cadeia. Naquele instante todas as portas se abriram, e as correntes que prendiam os presos se arrebentaram.

[[v44-16-27]]

^<<v44-16-27,27>>^ Aí o carcereiro acordou. Quando viu que os portões da cadeia estavam abertos, pensou que os prisioneiros tinham fugido. Então puxou a espada e ia se matar,

[[v44-16-28]]

^<<v44-16-28,28>>^ mas Paulo gritou bem alto: — Não faça isso! Todos nós estamos aqui!

[[v44-16-29]]

^<<v44-16-29,29>>^ Aí o carcereiro pediu que lhe trouxessem uma luz, entrou depressa na cela e se ajoelhou, tremendo, aos pés de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ Depois levou os dois para fora e perguntou: — Senhores, o que devo fazer para ser salvo?

[[v44-16-31]]

^<<v44-16-31,31>>^ Eles responderam: — Creia no Senhor Jesus e você será salvo — você e as pessoas da sua casa.

[[v44-16-32]]

^<<v44-16-32,32>>^ Então eles anunciaram a palavra do Senhor ao carcereiro e a todas as pessoas da casa dele.

[[v44-16-33]]

^<<v44-16-33,33>>^ Naquela mesma hora da noite, o carcereiro começou a cuidar deles, lavando os ferimentos da surra que haviam levado. Logo depois ele e todas as pessoas da sua casa foram batizados.

[[v44-16-34]]

^<<v44-16-34,34>>^ Em seguida ele levou Paulo e Silas para a sua casa e lhes deu comida. O carcereiro e as pessoas da sua casa ficaram cheios de alegria porque agora criam em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando amanheceu, as autoridades romanas mandaram alguns policiais com a seguinte ordem para o carcereiro: "Solte esses homens."

[[v44-16-36]]

^<<v44-16-36,36>>^ Então o carcereiro disse a Paulo: — As autoridades mandaram soltá-los. Podem ir embora em paz.

[[v44-16-37]]

^<<v44-16-37,37>>^ Mas Paulo disse aos policiais: — Eu e Silas somos cidadãos romanos e, mesmo assim, sem termos sido julgados, fomos surrados em público. E depois nos jogaram na cadeia. E agora querem nos mandar embora assim em segredo? Isso não! Que as próprias autoridades romanas venham aqui e nos soltem!

[[v44-16-38]]

^<<v44-16-38,38>>^ Os policiais foram contar às autoridades romanas o que Paulo tinha dito. Quando as autoridades souberam que Paulo e Silas eram cidadãos romanos, ficaram com medo

[[v44-16-39]]

^<<v44-16-39,39>>^ e foram lhes pedir desculpas. Então os tiraram da prisão e pediram que fossem embora da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Paulo e Silas saíram da cadeia e foram para a casa de Lídia. Ali encontraram-se com os irmãos, animaram a todos e depois foram embora.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]