include::./index.adoc[]

[[v44-23-0]]
=== Atos, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v44-23-1]]

^<<v44-23-1,1>>^ Então Paulo olhou firmemente para os membros do Conselho e disse: — Meus irmãos, tenho vivido até hoje com a consciência limpa diante de Deus.

[[v44-23-2]]

^<<v44-23-2,2>>^ Mas Ananias, o Grande Sacerdote , mandou que os homens que estavam perto de Paulo dessem um tapa na boca dele.

[[v44-23-3]]

^<<v44-23-3,3>>^ Aí Paulo disse a Ananias: — Hipócrita, Deus o castigará por isso! Você está sentado aí para me julgar de acordo com a Lei , não é? Então como é que mandou bater em mim? Isso é contra a Lei!

[[v44-23-4]]

^<<v44-23-4,4>>^ Os homens que estavam perto de Paulo perguntaram: — Você está insultando o Grande Sacerdote, o servo  de Deus?

[[v44-23-5]]

^<<v44-23-5,5>>^ Paulo respondeu: — Meus irmãos, eu não sabia que ele é o Grande Sacerdote. Pois as Escrituras Sagradas  dizem: "Não fale mal de nenhuma das autoridades do seu povo."

[[v44-23-6]]

^<<v44-23-6,6>>^ Quando Paulo percebeu que alguns do Conselho eram do partido dos saduceus  e outros do partido dos fariseus , disse bem alto: — Meus irmãos, eu sou fariseu e filho de fariseus. Estou aqui sendo julgado porque creio que os mortos vão ressuscitar.

[[v44-23-7]]

^<<v44-23-7,7>>^ Assim que ele disse isso, os fariseus e os saduceus começaram a discutir, e o Conselho se dividiu.

[[v44-23-8]]

^<<v44-23-8,8>>^ É que os saduceus não creem que os mortos vão ressuscitar, nem que existem anjos ou espíritos; mas os fariseus creem nessas coisas.

[[v44-23-9]]

^<<v44-23-9,9>>^ E assim a gritaria aumentou ainda mais. Então alguns mestres  da Lei que pertenciam ao partido dos fariseus se levantaram e protestaram. Eles disseram: — Não vemos nenhum mal neste homem. Pode ser mesmo que um anjo ou um espírito tenha falado com ele.

[[v44-23-10]]

^<<v44-23-10,10>>^ A briga chegou a tal ponto, que o comandante ficou com medo de que Paulo fosse despedaçado por eles. Por isso mandou os guardas descerem para tirar Paulo do meio deles e o levar de volta para a fortaleza.

[[v44-23-11]]

^<<v44-23-11,11>>^ Na noite seguinte o Senhor Jesus apareceu a Paulo e disse: — Tenha coragem, Paulo! Você falou a meu respeito aqui em Jerusalém e vai falar também em Roma.

[[v44-23-12]]

^<<v44-23-12,12>>^ Na manhã seguinte alguns judeus se ajuntaram e juraram que não iam comer nem beber nada enquanto não matassem Paulo.

[[v44-23-13]]

^<<v44-23-13,13>>^ Os homens que combinaram fazer isso eram mais de quarenta.

[[v44-23-14]]

^<<v44-23-14,14>>^ Eles foram falar com os chefes dos sacerdotes e com os líderes do povo e disseram: — Nós fizemos o seguinte juramento: "Que Deus nos amaldiçoe se comermos ou bebermos qualquer coisa enquanto não matarmos Paulo."

[[v44-23-15]]

^<<v44-23-15,15>>^ Agora vocês e o Conselho Superior , mandem pedir ao comandante que traga Paulo aqui. Digam que estão querendo examinar melhor o caso dele. Então, antes que ele chegue, nós estaremos prontos para matá-lo.

[[v44-23-16]]

^<<v44-23-16,16>>^ Mas o filho da irmã de Paulo ficou sabendo do plano; ele entrou na fortaleza e contou tudo a Paulo.

[[v44-23-17]]

^<<v44-23-17,17>>^ Então Paulo chamou um dos oficiais e disse: — Leve este moço ao comandante. Ele tem uma coisa para contar a ele.

[[v44-23-18]]

^<<v44-23-18,18>>^ O oficial levou o moço ao comandante e disse: — Aquele preso que se chama Paulo mandou me chamar e pediu que eu trouxesse este moço porque ele tem uma informação para o senhor.

[[v44-23-19]]

^<<v44-23-19,19>>^ O comandante pegou o moço pela mão, levou-o para um lado e perguntou: — O que é que você tem para me contar?

[[v44-23-20]]

^<<v44-23-20,20>>^ Ele respondeu: — Alguns judeus combinaram pedir ao senhor que leve Paulo amanhã ao Conselho Superior, com a desculpa de quererem examinar melhor o caso dele.

[[v44-23-21]]

^<<v44-23-21,21>>^ Mas não acredite nisso, pois mais de quarenta deles vão ficar escondidos esperando Paulo para o matar. Todos eles fizeram este juramento: "Que Deus nos amaldiçoe se comermos ou bebermos qualquer coisa antes de termos matado Paulo." Eles estão prontos para cumprir o juramento e esperam apenas saber o que o senhor vai resolver.

[[v44-23-22]]

^<<v44-23-22,22>>^ Então o comandante respondeu: — Não diga a ninguém que você me contou isso. E mandou que o moço fosse embora.

[[v44-23-23]]

^<<v44-23-23,23>>^ Então o comandante chamou dois oficiais e disse: — Arranjem duzentos soldados, e mais setenta cavaleiros, e duzentos lanceiros para ir até a cidade de Cesareia. Estejam prontos para sair daqui às nove horas da noite.

[[v44-23-24]]

^<<v44-23-24,24>>^ Preparem também cavalos para Paulo montar e o levem com toda a segurança para o governador Félix.

[[v44-23-25]]

^<<v44-23-25,25>>^ Depois o comandante escreveu uma carta que dizia o seguinte:

[[v44-23-26]]

^<<v44-23-26,26>>^ "Excelentíssimo Governador Félix, "Saudações.

[[v44-23-27]]

^<<v44-23-27,27>>^ "Alguns judeus agarraram este homem e quase o mataram. Quando soube que ele era cidadão romano, eu fui com os meus soldados e não deixei que ele fosse morto.

[[v44-23-28]]

^<<v44-23-28,28>>^ Eu queria saber por que o estavam acusando e por isso resolvi levá-lo diante do Conselho Superior  dos judeus.

[[v44-23-29]]

^<<v44-23-29,29>>^ Então descobri que ele não tinha feito nada para merecer a prisão ou a morte. A acusação contra ele era a respeito da própria lei  deles.

[[v44-23-30]]

^<<v44-23-30,30>>^ Quando fui informado de que havia um plano para matá-lo, resolvi mandá-lo ao senhor. E disse para aqueles judeus que fizessem as acusações na sua presença. "Saúde. "Cláudio Lísias."

[[v44-23-31]]

^<<v44-23-31,31>>^ Então os soldados cumpriram as ordens. Pegaram Paulo e o levaram durante a noite até a cidade de Antipátride.

[[v44-23-32]]

^<<v44-23-32,32>>^ No dia seguinte os soldados voltaram para a fortaleza, deixando que os cavaleiros continuassem a viagem com Paulo.

[[v44-23-33]]

^<<v44-23-33,33>>^ Eles o levaram para a cidade de Cesareia, deram a carta ao Governador e lhe entregaram Paulo.

[[v44-23-34]]

^<<v44-23-34,34>>^ O Governador leu a carta e perguntou a Paulo de onde ele era. Quando soube que era da região da Cilícia,

[[v44-23-35]]

^<<v44-23-35,35>>^ disse: — Quando os seus acusadores chegarem, eu ouvirei o que você tem para dizer. Em seguida mandou que ele ficasse preso no palácio do Governador .

'''

xref:044-atos/044-atos-022.adoc#v44-22-0[&#60; Capítulo Anterior] | <<v44-23-0,Topo>> | xref:044-atos/044-atos-024.adoc#v44-24-0[Próximo Capítulo &#62;]