include::./index.adoc[]

[[v14-15-0]]
=== 2 Crônicas, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-15-1]]

^<<v14-15-1,1>>^ O Espírito de Deus desceu sobre Azarias, filho de Odede,

[[v14-15-2]]

^<<v14-15-2,2>>^ e ele foi falar com Asa. E disse: — Rei Asa e todo o povo de Judá e de Benjamim, escutem! O Senhor  Deus está com vocês, se é que vocês estão com ele. Se o procurarem, ele deixará que vocês o achem; mas, se o rejeitarem, ele também os rejeitará.

[[v14-15-3]]

^<<v14-15-3,3>>^ Durante muito tempo, os israelitas não adoraram o verdadeiro Deus, nem tiveram sacerdotes que os ensinassem, nem tiveram a Lei  de Deus.

[[v14-15-4]]

^<<v14-15-4,4>>^ Mas, quando vieram tempos difíceis, eles voltaram para o Senhor , o Deus de Israel; eles o procuraram e o encontraram.

[[v14-15-5]]

^<<v14-15-5,5>>^ Naqueles tempos, ninguém vivia sossegado; em todos os países havia desordem.

[[v14-15-6]]

^<<v14-15-6,6>>^ Nações e cidades atacavam e destruíam umas às outras, pois Deus estava fazendo cair sobre elas todo tipo de sofrimento.

[[v14-15-7]]

^<<v14-15-7,7>>^ Mas sejam fortes e não fiquem desanimados, pois vocês serão bem-sucedidos em tudo o que fizerem.

[[v14-15-8]]

^<<v14-15-8,8>>^ Asa ouviu essa mensagem, isto é, a profecia  de Azarias, filho de Odede, e ficou cheio de coragem. Acabou com todos os ídolos nojentos que havia em Judá e em Benjamim e também nas cidades que ele tinha conquistado na região montanhosa de Efraim e consertou o altar do Senhor  Deus, que estava no pátio em frente do Templo.

[[v14-15-9]]

^<<v14-15-9,9>>^ Depois mandou chamar todo o povo das tribos  de Judá e de Benjamim, como também todas as pessoas das tribos de Efraim, de Manassés e de Simeão que estavam morando em Judá. Pois muitas pessoas dessas tribos viram que o Senhor  estava com o rei Asa e por isso vieram para o seu lado.

[[v14-15-10]]

^<<v14-15-10,10>>^ Todos eles se reuniram em Jerusalém no terceiro mês do ano quinze do reinado de Asa.

[[v14-15-11]]

^<<v14-15-11,11>>^ Naquele dia ofereceram em sacrifício  ao Senhor  setecentos touros e sete mil ovelhas que eles haviam tomado nas batalhas.

[[v14-15-12]]

^<<v14-15-12,12>>^ Fizeram uma aliança  com o Senhor , o Deus dos seus antepassados, prometendo adorá-lo com todo o coração e com toda a alma.

[[v14-15-13]]

^<<v14-15-13,13>>^ Juraram também que seriam mortos todos os que não quisessem adorá-lo, tanto crianças como adultos, tanto homens como mulheres.

[[v14-15-14]]

^<<v14-15-14,14>>^ Em voz alta juraram a Deus, o Senhor , que seriam fiéis à aliança e depois deram gritos de alegria e tocaram trombetas e cornetas.

[[v14-15-15]]

^<<v14-15-15,15>>^ O povo de Judá ficou alegre por causa desse juramento, que tinha feito com todo o coração. E, por terem procurado o Senhor  com toda a boa vontade, ele deixou que o achassem e permitiu que vivessem em paz com todos os povos vizinhos.

[[v14-15-16]]

^<<v14-15-16,16>>^ Asa também tirou a sua mãe Maacá da posição de rainha-mãe porque ela havia mandado fazer uma figura imoral para servir como poste da deusa Aserá . Asa derrubou o ídolo, o reduziu a pó e queimou no vale do Cedrom.

[[v14-15-17]]

^<<v14-15-17,17>>^ Ele não destruiu todos os lugares pagãos de adoração, porém foi fiel a Deus toda a sua vida.

[[v14-15-18]]

^<<v14-15-18,18>>^ Ele colocou no Templo todos os objetos que o seu pai havia separado para o Senhor  Deus e também os objetos de prata e de ouro que ele mesmo havia separado.

[[v14-15-19]]

^<<v14-15-19,19>>^ E não houve mais guerra até o ano trinta e cinco do seu reinado.

'''

xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[&#60; Capítulo Anterior] | <<v14-15-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[Próximo Capítulo &#62;]