include::./index.adoc[]

[[v14-26-0]]
=== 2 Crônicas, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-26-1]]

^<<v14-26-1,1>>^ No lugar de Amazias o povo de Judá pôs como rei o seu filho Uzias, que tinha dezesseis anos de idade.

[[v14-26-2]]

^<<v14-26-2,2>>^ Depois da morte do pai, Uzias reconquistou e construiu de novo a cidade de Elate.

[[v14-26-3]]

^<<v14-26-3,3>>^ Uzias se tornou rei aos dezesseis anos de idade. Ele governou cinquenta e dois anos em Jerusalém. A sua mãe se chamava Jecolias e era da cidade de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ Seguindo o exemplo do seu pai, Uzias fez aquilo que agrada a Deus, o Senhor .

[[v14-26-5]]

^<<v14-26-5,5>>^ Enquanto Zacarias viveu, Uzias serviu a Deus fielmente, pois Zacarias o ensinou a respeitar o Senhor . Durante esse tempo Deus o abençoou.

[[v14-26-6]]

^<<v14-26-6,6>>^ Uzias fez guerra contra os filisteus e derrubou as muralhas das cidades de Gate, de Jâmnia e de Asdode; depois construiu cidades protegidas por muralhas perto de Asdode e em outros lugares da região dos filisteus.

[[v14-26-7]]

^<<v14-26-7,7>>^ Deus o ajudou a derrotar os filisteus, os árabes que moravam em Gur-Baal e os meunitas.

[[v14-26-8]]

^<<v14-26-8,8>>^ O poder de Uzias aumentou, e a sua fama se espalhou até o Egito; e os amonitas lhe pagavam impostos.

[[v14-26-9]]

^<<v14-26-9,9>>^ A fim de tornar mais fortes as muralhas de Jerusalém, Uzias construiu torres no Portão da Esquina, no Portão do Vale e no lugar onde a muralha faz esquina.

[[v14-26-10]]

^<<v14-26-10,10>>^ Construiu também torres de vigia nos campos e abriu uma porção de poços, pois tinha muito gado, tanto nas planícies como nos planaltos de Judá. Tinha também homens trabalhando nas plantações de uvas e nas hortas das regiões montanhosas e nos campos férteis, pois se interessava pela agricultura.

[[v14-26-11]]

^<<v14-26-11,11>>^ Uzias tinha um exército de homens prontos para a guerra; eles marchavam para a batalha em grupos organizados de acordo com as listas que estavam aos cuidados do escrivão Jeiel e do oficial Maaseias. O chefe desses dois homens era Hananias, um dos generais do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O exército era comandado por dois mil e seiscentos chefes de famílias, todos eles soldados valentes.

[[v14-26-13]]

^<<v14-26-13,13>>^ Eles comandavam um exército poderoso de trezentos e sete mil e quinhentos soldados, que estava à disposição do rei nas suas lutas contra os seus inimigos.

[[v14-26-14]]

^<<v14-26-14,14>>^ Uzias armou os seus soldados com escudos , lanças, capacetes, couraças , arcos e flechas, e fundas  para atirar pedras.

[[v14-26-15]]

^<<v14-26-15,15>>^ Em Jerusalém os seus engenheiros construíram máquinas de guerra que eram postas nas torres e nas esquinas das muralhas, a fim de atirarem flechas e pedras grandes. A fama de Uzias se espalhou por toda parte. E ele se tornou muito poderoso, pois Deus o ajudava.

[[v14-26-16]]

^<<v14-26-16,16>>^ Porém, quando se tornou assim poderoso, Uzias ficou cheio de orgulho, e essa foi a sua desgraça. Ele pecou contra o Senhor , seu Deus, pois entrou no Templo para queimar incenso no altar do incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ O Grande Sacerdote  Azarias e oitenta sacerdotes corajosos entraram atrás do rei

[[v14-26-18]]

^<<v14-26-18,18>>^ e o enfrentaram, dizendo: — Ó rei, o senhor não pode queimar incenso ao Senhor  Deus. Só têm esse direito os sacerdotes, os descendentes de Arão, que foram separados para este serviço. Saia deste Lugar Santo , pois o senhor pecou contra Deus, e por isso ele não vai abençoá-lo.

[[v14-26-19]]

^<<v14-26-19,19>>^ Ao ouvir isso, Uzias ficou furioso com os sacerdotes. Ele estava ali no Templo, perto do altar do incenso, segurando o queimador de incenso. E, no momento em que ficou furioso, uma doença contagiosa da pele apareceu na sua testa.

[[v14-26-20]]

^<<v14-26-20,20>>^ Azarias e os sacerdotes, vendo que ele estava com aquela terrível doença, o expulsaram imediatamente do Templo. E ele mesmo tratou de sair depressa, pois o Senhor  Deus o havia castigado.

[[v14-26-21]]

^<<v14-26-21,21>>^ O rei Uzias sofreu dessa doença até morrer. E, por ter ficado impuro , ele morava numa casa separada e ficou proibido de entrar no Templo. O seu filho Jotão era quem mandava no palácio e governava o país.

[[v14-26-22]]

^<<v14-26-22,22>>^ Todas as outras coisas que Uzias fez, desde o começo até o fim do seu reinado, foram escritas pelo profeta  Isaías, filho de Amoz.

[[v14-26-23]]

^<<v14-26-23,23>>^ Uzias morreu e foi sepultado no cemitério dos reis em Jerusalém, mas não nos túmulos dos reis, por causa da sua doença. E o seu filho Jotão ficou no lugar dele como rei.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]