include::./index.adoc[]

[[v14-19-0]]
=== 2 Crônicas, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-19-1]]

^<<v14-19-1,1>>^ Josafá, rei de Judá, voltou são e salvo para o seu palácio, em Jerusalém.

[[v14-19-2]]

^<<v14-19-2,2>>^ O profeta  Jeú, filho de Hanani, foi encontrar-se com o rei e disse: — Por que é que o senhor ajuda os maus e é amigo dos inimigos de Deus? Por causa disso, o Senhor  Deus vai castigá-lo.

[[v14-19-3]]

^<<v14-19-3,3>>^ Mas é verdade que o senhor fez coisas boas: acabou com os postes da deusa Aserá  do país e procurou com todo o coração conhecer a vontade de Deus.

[[v14-19-4]]

^<<v14-19-4,4>>^ Josafá continuou morando em Jerusalém, mas tinha o costume de visitar o povo no país inteiro, desde Berseba, no Sul, até a região montanhosa de Efraim, no Norte. Ele fez com que o povo se voltasse para o Senhor , o Deus dos antepassados deles.

[[v14-19-5]]

^<<v14-19-5,5>>^ Colocou juízes em todas as cidades de Judá protegidas por muralhas

[[v14-19-6]]

^<<v14-19-6,6>>^ e lhes deu a seguinte ordem: — Tenham cuidado quando decidirem algum caso, pois o que vocês fazem é em nome de Deus, o Senhor , e não em nome de criaturas humanas. E, quando julgarem as questões, Deus estará com vocês.

[[v14-19-7]]

^<<v14-19-7,7>>^ Portanto, respeitem a Deus e tenham cuidado com o que vão fazer, pois o Senhor , nosso Deus, não tolera os que cometem injustiça, nem os que usam dois pesos e duas medidas nos julgamentos, nem os que aceitam dinheiro para torcer a justiça.

[[v14-19-8]]

^<<v14-19-8,8>>^ Em Jerusalém Josafá colocou alguns levitas , sacerdotes e chefes de famílias para julgarem os assuntos religiosos e as causas dos moradores da cidade.

[[v14-19-9]]

^<<v14-19-9,9>>^ Ele lhes deu a seguinte ordem: — Cumpram com honestidade todos os seus deveres para com Deus, o Senhor , respeitando-o e obedecendo-lhe com todo o coração.

[[v14-19-10]]

^<<v14-19-10,10>>^ Quando os seus patrícios das cidades de Judá apresentarem a vocês causas de morte ou qualquer caso de desobediência às leis , estatutos e regulamentos, avisem a eles que não cometam pecados contra o Senhor , a fim de que ele não castigue vocês e os seus patrícios. Se derem esse aviso, vocês não serão culpados.

[[v14-19-11]]

^<<v14-19-11,11>>^ O Grande Sacerdote  Amariá terá a última palavra nas questões religiosas, e o governador de Judá, Zebadias, filho de Ismael, terá a última palavra em casos não religiosos. Os levitas ajudarão nos serviços do tribunal. Coragem, pois, e mãos à obra! E que o Senhor  Deus esteja com os que fazem o que é direito!

'''

xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[&#60; Capítulo Anterior] | <<v14-19-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[Próximo Capítulo &#62;]