include::./index.adoc[]

[[v14-21-0]]
=== 2 Crônicas, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-21-1]]

^<<v14-21-1,1>>^ Josafá morreu e foi sepultado nos túmulos dos reis, na Cidade de Davi , e o seu filho Jeorão ficou no lugar dele como rei.

[[v14-21-2]]

^<<v14-21-2,2>>^ Jeorão, filho do rei Josafá, de Judá, tinha seis irmãos, que se chamavam Azarias, Jeiel, Zacarias, Azarias, Micael e Sefatias.

[[v14-21-3]]

^<<v14-21-3,3>>^ Josafá deu a eles muitos presentes de prata e ouro e objetos de valor. E a cada um entregou o governo de uma das cidades de Judá que eram protegidas por muralhas. Mas ele escolheu Jeorão, o filho mais velho, para ser o rei depois dele.

[[v14-21-4]]

^<<v14-21-4,4>>^ Quando se tornou rei, Jeorão se firmou no poder e então mandou matar todos os seus irmãos e também algumas das altas autoridades de Israel.

[[v14-21-5]]

^<<v14-21-5,5>>^ Jeorão tinha trinta e dois anos de idade quando se tornou rei e governou oito anos em Jerusalém.

[[v14-21-6]]

^<<v14-21-6,6>>^ A mulher dele era filha do rei Acabe, de Israel, e por isso Jeorão seguiu os maus caminhos de Acabe e dos outros reis de Israel. Jeorão pecou contra Deus, o Senhor ,

[[v14-21-7]]

^<<v14-21-7,7>>^ mas o Senhor  não quis acabar com os descendentes do rei Davi, pois havia feito uma aliança  com Davi, prometendo que os seus descendentes sempre seriam reis.

[[v14-21-8]]

^<<v14-21-8,8>>^ Durante o reinado de Jeorão, o país de Edom se revoltou contra Judá e se tornou independente.

[[v14-21-9]]

^<<v14-21-9,9>>^ Por isso, Jeorão e os seus oficiais, com os seus carros de guerra, invadiram Edom e ali foram cercados pelos edomitas. Jeorão e os seus comandantes dos carros de guerra atacaram os edomitas durante a noite e escaparam.

[[v14-21-10]]

^<<v14-21-10,10>>^ Desse tempo até hoje , Edom ficou independente de Judá. Nessa mesma época, a cidade de Libna também se revoltou porque Jeorão tinha abandonado o Senhor , o Deus dos seus antepassados.

[[v14-21-11]]

^<<v14-21-11,11>>^ Ele construiu lugares pagãos de adoração nas montanhas de Judá, levou os moradores de Jerusalém a adorarem ídolos e fez o povo de Judá abandonar a Deus.

[[v14-21-12]]

^<<v14-21-12,12>>^ Aí o profeta  Elias escreveu a Jeorão uma carta, na qual dizia o seguinte: "É isto o que diz o Senhor , o Deus do seu antepassado Davi: ‘Você não seguiu o bom exemplo do seu pai, o rei Josafá, nem do seu avô, o rei Asa,

[[v14-21-13]]

^<<v14-21-13,13>>^ mas seguiu o mau exemplo dos reis de Israel. Você levou o povo de Judá e os moradores de Jerusalém a adorarem ídolos, como fazem os reis de Israel. E também matou os seus próprios irmãos, que eram melhores do que você.

[[v14-21-14]]

^<<v14-21-14,14>>^ Por isso, o Senhor  Deus vai fazer cair um castigo terrível sobre o povo de Judá e sobre os filhos e as mulheres que você tem e vai destruir tudo o que é seu.

[[v14-21-15]]

^<<v14-21-15,15>>^ E você mesmo vai ter uma doença intestinal muito séria, que irá piorando cada vez mais, até que os seus intestinos saiam do corpo.’ "

[[v14-21-16]]

^<<v14-21-16,16>>^ O Senhor  Deus fez com que os filisteus e os árabes que eram vizinhos dos etíopes que moravam no litoral ficassem furiosos com Jeorão.

[[v14-21-17]]

^<<v14-21-17,17>>^ Eles invadiram o país de Judá, derrotaram Jeorão e levaram embora todos os bens do palácio e também os filhos e as mulheres de Jeorão. Deixaram somente Acazias, o seu filho mais moço.

[[v14-21-18]]

^<<v14-21-18,18>>^ Depois de tudo isso, o Senhor  castigou Jeorão com uma doença intestinal incurável.

[[v14-21-19]]

^<<v14-21-19,19>>^ Ele foi piorando cada vez mais, até que depois de dois anos os intestinos saíram do corpo dele, e Jeorão morreu, sofrendo dores terríveis. O povo não acendeu uma fogueira em honra dele, como havia feito para os seus antepassados.

[[v14-21-20]]

^<<v14-21-20,20>>^ Jeorão tinha trinta e dois anos de idade quando se tornou rei de Judá. Ele governou em Jerusalém oito anos. Quando morreu, ninguém sentiu falta dele; ele foi sepultado na Cidade de Davi , mas não nos túmulos dos reis.

'''

xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[&#60; Capítulo Anterior] | <<v14-21-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[Próximo Capítulo &#62;]