include::./index.adoc[]

[[v14-7-0]]
=== 2 Crônicas, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-7-1]]

^<<v14-7-1,1>>^ Quando Salomão terminou a oração, desceu fogo do céu e queimou completamente o animal oferecido em sacrifício  e os outros sacrifícios que tinham sido oferecidos; e a glória  do Senhor  Deus encheu o Templo.

[[v14-7-2]]

^<<v14-7-2,2>>^ E, por causa dessa luz, os sacerdotes não puderam entrar no Templo.

[[v14-7-3]]

^<<v14-7-3,3>>^ Ao verem o fogo descer e a glória do Senhor  encher o Templo, todos os israelitas que estavam ali no pátio se ajoelharam e encostaram o rosto no chão. Eles adoraram a Deus e o louvaram, dizendo: "Louvem a Deus, o Senhor , porque ele é bom, e porque o seu amor dura para sempre."

[[v14-7-4]]

^<<v14-7-4,4>>^ Então o rei e todo o povo ofereceram sacrifícios ao Senhor .

[[v14-7-5]]

^<<v14-7-5,5>>^ Salomão ofereceu em sacrifício vinte e dois mil bois e cento e vinte mil ovelhas. Assim o rei e o povo dedicaram o Templo ao serviço de Deus.

[[v14-7-6]]

^<<v14-7-6,6>>^ Os sacerdotes estavam nos seus lugares, e os levitas  também, com os instrumentos de música sagrada que o rei Davi tinha feito para eles tocarem acompanhando o cântico "O Seu Amor É Eterno". Era assim que eles executavam os cânticos de louvor feitos por Davi. Todos os israelitas ficaram de pé enquanto os sacerdotes, que estavam em frente dos levitas, tocavam as trombetas.

[[v14-7-7]]

^<<v14-7-7,7>>^ Salomão dedicou também ao serviço de Deus a parte central do pátio que ficava em frente do Templo; ali ele apresentou as ofertas que foram completamente queimadas e a gordura dos animais que haviam sido oferecidos nas ofertas de paz. Salomão fez isso porque o altar de bronze era muito pequeno para os sacrifícios que eram completamente queimados, para as ofertas de cereais e para a gordura das ofertas de paz.

[[v14-7-8]]

^<<v14-7-8,8>>^ Depois Salomão e todo o povo de Israel comemoraram durante sete dias a festa da dedicação do altar. Estava ali uma enorme multidão, pessoas que tinham vindo do país inteiro, desde a subida de Hamate, no Norte, até a fronteira do Egito, no Sul.

[[v14-7-9]]

^<<v14-7-9,9>>^ No dia seguinte, começaram a comemorar a Festa das Barracas , que também durou uma semana. E no dia seguinte fizeram uma grande festa de encerramento.

[[v14-7-10]]

^<<v14-7-10,10>>^ No outro dia, o dia vinte e três do sétimo mês, o rei mandou o povo para casa. Todos foram embora felizes e alegres por causa de todas as coisas boas que o Senhor  Deus tinha dado a Davi, a Salomão e ao seu povo de Israel.

[[v14-7-11]]

^<<v14-7-11,11>>^ Assim Salomão acabou de construir o Templo e o palácio real; todos os seus planos para a construção do Templo e do palácio deram certo.

[[v14-7-12]]

^<<v14-7-12,12>>^ Então o Senhor  Deus apareceu de noite a Salomão e disse: — Eu ouvi a sua oração e escolhi este Templo para ser o lugar onde serão oferecidos os sacrifícios .

[[v14-7-13]]

^<<v14-7-13,13>>^ Quando eu fechar o céu e não deixar que chova, ou ordenar aos gafanhotos que destruam as colheitas, ou mandar uma peste atacar o povo,

[[v14-7-14]]

^<<v14-7-14,14>>^ então, se o meu povo, que pertence somente a mim, se arrepender, abandonar os seus pecados e orar a mim, eu os ouvirei do céu, perdoarei os seus pecados e farei o país progredir de novo.

[[v14-7-15]]

^<<v14-7-15,15>>^ Escutarei com atenção as orações que forem feitas neste Templo,

[[v14-7-16]]

^<<v14-7-16,16>>^ pois é o Templo que escolhi e separei para ser o lugar onde deverei ser adorado para sempre. Eu tomarei conta dele e sempre o protegerei.

[[v14-7-17]]

^<<v14-7-17,17>>^ — E se você, Salomão, me servir fielmente, como fez Davi, o seu pai, e se obedecer às minhas leis  e ordens e fizer tudo o que eu mandar,

[[v14-7-18]]

^<<v14-7-18,18>>^ então eu firmarei o seu poder como rei, cumprindo assim a aliança  que fiz com Davi quando lhe disse que Israel sempre seria governado pelos descendentes dele.

[[v14-7-19]]

^<<v14-7-19,19>>^ Mas, se você e o seu povo deixarem de me seguir, se desobedecerem às leis e aos mandamentos que lhes dei e se adorarem e servirem outros deuses,

[[v14-7-20]]

^<<v14-7-20,20>>^ então eu os arrancarei da terra que lhes dei. E também abandonarei este Templo, que separei para ser o lugar onde devo ser adorado. Aí todos os povos vão desprezar e zombar do Templo,

[[v14-7-21]]

^<<v14-7-21,21>>^ que agora é tão glorioso . Todos os que passarem por perto dele ficarão chocados e perguntarão: "Por que foi que Deus fez isso com esta terra e com este Templo?"

[[v14-7-22]]

^<<v14-7-22,22>>^ E a resposta será: "Foi porque os israelitas abandonaram o Senhor , seu Deus, que tirou do Egito os antepassados deles. Eles seguiram outros deuses e os adoraram e os serviram. Foi por isso que o Senhor  fez com que toda esta desgraça caísse sobre eles."

'''

xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[Próximo Capítulo &#62;]