include::./index.adoc[]

[[v14-22-0]]
=== 2 Crônicas, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-22-1]]

^<<v14-22-1,1>>^ Os moradores de Jerusalém puseram Acazias, o filho mais moço de Jeorão, como rei no lugar do seu pai. Isso porque o bando de árabes que havia invadido o acampamento tinha matado todos os filhos de Jeorão, menos Acazias. Assim Acazias se tornou rei de Judá

[[v14-22-2]]

^<<v14-22-2,2>>^ aos vinte e dois anos de idade. Ele governou em Jerusalém um ano.

[[v14-22-3]]

^<<v14-22-3,3>>^ A mãe dele se chamava Atalia e era filha do rei Acabe e neta do rei Onri, de Israel. Ela dava maus conselhos a Acazias, e assim ele seguiu o péssimo exemplo da família de Acabe.

[[v14-22-4]]

^<<v14-22-4,4>>^ Como a família de Acabe havia feito, ele pecou contra Deus, o Senhor , porque, depois da morte do seu pai, outras pessoas da família de Acabe foram os seus conselheiros.

[[v14-22-5]]

^<<v14-22-5,5>>^ Seguindo os conselhos que eles davam, Acazias se juntou com o rei de Israel, Jorão, filho de Acabe, e foi até Ramote-Gileade para lutar contra o rei Hazael, da Síria. Jorão foi ferido na batalha

[[v14-22-6]]

^<<v14-22-6,6>>^ e voltou para a cidade de Jezreel a fim de tratar os seus ferimentos. E Acazias foi até lá visitá-lo.

[[v14-22-7]]

^<<v14-22-7,7>>^ Deus havia decidido que Acazias iria morrer nessa visita a Jorão. Logo que chegou, Acazias foi com Jorão encontrar-se com Jeú, filho de Ninsi, a quem o Senhor  Deus havia escolhido para acabar com a família de Acabe.

[[v14-22-8]]

^<<v14-22-8,8>>^ Jeú estava executando a condenação divina contra a família de Acabe quando encontrou alguns chefes de Judá e alguns sobrinhos do rei Acazias, que estavam ao serviço do rei; e Jeú os matou.

[[v14-22-9]]

^<<v14-22-9,9>>^ Depois ele mandou procurar Acazias, que foi encontrado na cidade de Samaria, onde estava se escondendo. Entregaram Acazias a Jeú e o mataram. Mas eles o sepultaram porque era neto do rei Josafá, que havia se esforçado para servir com todo o coração a Deus, o Senhor . E agora não havia nenhuma outra pessoa da família de Acazias que pudesse ser rei.

[[v14-22-10]]

^<<v14-22-10,10>>^ Assim que Atalia, a mãe do rei Acazias, soube da morte do filho, deu ordem para que todas as pessoas da família real fossem mortas.

[[v14-22-11]]

^<<v14-22-11,11>>^ Somente Joás, filho de Acazias, escapou. Ele ia ser morto com os outros, mas foi salvo por sua tia Jeoseba, que era filha do rei Jeorão, meia-irmã de Acazias e mulher do sacerdote Joiada. Ela levou Joás e a sua babá para um quarto do Templo e o escondeu de Atalia. Assim ele não foi morto.

[[v14-22-12]]

^<<v14-22-12,12>>^ Durante seis anos, Joás ficou ali escondido com as pessoas que o protegiam. Enquanto isso, Atalia governava o país.

'''

xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[Próximo Capítulo &#62;]