include::./index.adoc[]

[[v14-34-0]]
=== 2 Crônicas, 34
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-34-1]]

^<<v14-34-1,1>>^ Josias tinha oito anos de idade quando se tornou rei de Judá. Ele governou trinta e um anos em Jerusalém.

[[v14-34-2]]

^<<v14-34-2,2>>^ Josias fez o que agrada a Deus, o Senhor ; seguiu o exemplo do seu antepassado, o rei Davi, e não se desviou nem para um lado nem para o outro.

[[v14-34-3]]

^<<v14-34-3,3>>^ No oitavo ano do seu reinado, quando era ainda bem moço, Josias começou a adorar o Deus do seu antepassado Davi. E quatro anos mais tarde começou a purificar  a terra de Judá e a cidade de Jerusalém, destruindo os lugares pagãos de adoração, os postes da deusa Aserá  e as outras imagens de pedra e de metal.

[[v14-34-4]]

^<<v14-34-4,4>>^ Na presença dele, foram derrubados os altares do deus Baal , e ele mesmo quebrou os altares de incenso que estavam em cima deles. Quebrou também os postes da deusa Aserá e as outras imagens de pedra e de metal, os esmigalhou até virarem pó e espalhou o pó em cima das sepulturas das pessoas que tinham oferecido sacrifícios  a esses ídolos.

[[v14-34-5]]

^<<v14-34-5,5>>^ Depois queimou os ossos dos sacerdotes pagãos nos altares onde eles haviam oferecido sacrifícios. Assim Josias purificou Judá e Jerusalém.

[[v14-34-6]]

^<<v14-34-6,6>>^ Ele fez a mesma coisa nas cidades das tribos  de Manassés, de Efraim, de Simeão e até de Naftali e nas ruínas ao redor daquelas cidades.

[[v14-34-7]]

^<<v14-34-7,7>>^ Ele andou por todo o país de Israel, derrubando os altares, os postes da deusa Aserá e os outros ídolos, esmigalhando-os até virarem pó e quebrando todos os altares de incenso. Depois voltou para Jerusalém.

[[v14-34-8]]

^<<v14-34-8,8>>^ No ano dezoito do seu reinado, depois de ter purificado  o país e o Templo, Josias enviou os seguintes homens para fazerem os consertos no Templo: Safã, filho de Azalias; Maaseias, o governador de Jerusalém; e o conselheiro do rei, Joá, filho de Joacaz.

[[v14-34-9]]

^<<v14-34-9,9>>^ Eles foram falar com o Grande Sacerdote  Hilquias e lhe entregaram o dinheiro que os levitas  tinham recebido e trazido ao Templo. Esse dinheiro tinha sido dado por gente das tribos  de Manassés e de Efraim e do resto do Reino de Israel, e também por gente das tribos de Judá e de Benjamim e pelos moradores de Jerusalém.

[[v14-34-10]]

^<<v14-34-10,10>>^ O dinheiro foi entregue aos homens que estavam encarregados dos consertos, e estes o usaram para pagar os trabalhadores que estavam reconstruindo e consertando o Templo.

[[v14-34-11]]

^<<v14-34-11,11>>^ Deram o dinheiro aos carpinteiros e aos construtores para comprarem pedras trabalhadas e madeira para as vigas e para os outros consertos que deviam ser feitos nos edifícios que os reis de Judá haviam deixado cair aos pedaços.

[[v14-34-12]]

^<<v14-34-12,12>>^ Os trabalhadores eram honestos em tudo, e os seus chefes eram quatro levitas: Jaate e Obadias, do grupo de Merari, e Zacarias e Mesulã, do grupo de Coate. Eles eram chefes também dos guardas dos portões e de todos os outros homens que trabalhavam no Templo. Todos os levitas sabiam tocar bem instrumentos musicais, e alguns deles eram escrivães, outros eram fiscais, e outros eram guardas dos portões.

[[v14-34-13]]

^<<v14-34-13,13>>^ Os trabalhadores eram honestos em tudo, e os seus chefes eram quatro levitas: Jaate e Obadias, do grupo de Merari, e Zacarias e Mesulã, do grupo de Coate. Eles eram chefes também dos guardas dos portões e de todos os outros homens que trabalhavam no Templo. Todos os levitas sabiam tocar bem instrumentos musicais, e alguns deles eram escrivães, outros eram fiscais, e outros eram guardas dos portões.

[[v14-34-14]]

^<<v14-34-14,14>>^ Enquanto entregavam o dinheiro que havia sido dado para o Templo, Hilquias achou o Livro da Lei  de Deus, a Lei que o Senhor  tinha dado por meio de Moisés.

[[v14-34-15]]

^<<v14-34-15,15>>^ Hilquias disse a Safã, o escrivão: — Achei o Livro da Lei aqui no Templo. E deu o livro a Safã.

[[v14-34-16]]

^<<v14-34-16,16>>^ Este o levou ao rei e prestou o seu relatório, dizendo: — Nós, seus servidores, fizemos tudo o que o senhor mandou.

[[v14-34-17]]

^<<v14-34-17,17>>^ Pegamos o dinheiro que estava no Templo e o entregamos aos trabalhadores e aos seus chefes.

[[v14-34-18]]

^<<v14-34-18,18>>^ Safã disse também: — Tenho aqui comigo um livro que Hilquias me entregou. E leu o livro em voz alta para o rei.

[[v14-34-19]]

^<<v14-34-19,19>>^ Quando ouviu o que o livro dizia, o rei rasgou as suas roupas em sinal de tristeza.

[[v14-34-20]]

^<<v14-34-20,20>>^ Então deu a Hilquias e a Aicã, filho de Safã, e a Abdom, filho de Micaías, e a Safã, o escrivão, e a Asaías, o servidor do rei, a seguinte ordem:

[[v14-34-21]]

^<<v14-34-21,21>>^ — Vão consultar a Deus, o Senhor , por mim e por todo o povo de Israel e de Judá a respeito dos ensinamentos deste livro. Deus está muito irado  conosco porque os nossos antepassados não obedeceram às ordens do Senhor , nem fizeram o que este livro manda.

[[v14-34-22]]

^<<v14-34-22,22>>^ Então Hilquias e os homens que o rei tinha enviado foram falar com uma profetisa  chamada Hulda, que morava no bairro novo de Jerusalém. O marido dela, que se chamava Salum, filho de Ticva e neto de Harás, era o encarregado da rouparia do Templo. Eles contaram a Hulda o que havia acontecido,

[[v14-34-23]]

^<<v14-34-23,23>>^ e ela lhes disse que voltassem e dessem ao rei a seguinte mensagem de Deus:

[[v14-34-24]]

^<<v14-34-24,24>>^ — Eu, o Senhor , o Deus de Israel, vou castigar a cidade de Jerusalém e todo o seu povo com todos os castigos escritos no livro que foi lido para o rei de Judá.

[[v14-34-25]]

^<<v14-34-25,25>>^ Eles me abandonaram e têm oferecido sacrifícios  a outros deuses e assim me fizeram ficar irado por causa de todas as coisas que têm feito. A minha ira se acendeu contra Jerusalém e não vai se apagar.

[[v14-34-26]]

^<<v14-34-26,26>>^ Eu, o Senhor , o Deus de Israel, digo isto ao rei: "Você ouviu o que está escrito no livro,

[[v14-34-27]]

^<<v14-34-27,27>>^ e se arrependeu, e se humilhou diante de mim, rasgando as suas roupas e chorando quando ouviu como ameacei castigar a cidade de Jerusalém e o seu povo. Eu ouvi a sua oração

[[v14-34-28]]

^<<v14-34-28,28>>^ e por isso só depois da sua morte é que vou castigar Jerusalém e o seu povo. Vou deixar que você morra em paz." Então os homens levaram ao rei essa resposta.

[[v14-34-29]]

^<<v14-34-29,29>>^ O rei Josias mandou que todos os líderes de Judá e de Jerusalém se reunissem,

[[v14-34-30]]

^<<v14-34-30,30>>^ e todos foram juntos até o Templo, acompanhados pelos sacerdotes, pelos levitas  e por todo o resto do povo de Jerusalém e de Judá, desde os mais importantes até os mais humildes. Então o rei leu diante deles todo o Livro da Aliança , que havia sido achado no Templo.

[[v14-34-31]]

^<<v14-34-31,31>>^ Ele ficou perto da coluna real, em pé, e fez com Deus, o Senhor , uma aliança pela qual eles lhe obedeceriam e guardariam as suas leis  e mandamentos com todo o coração e com toda a alma. E também cumpririam tudo o que a aliança mandava fazer, como estava escrito no livro.

[[v14-34-32]]

^<<v14-34-32,32>>^ Então Josias fez com que todo o povo de Jerusalém e da tribo  de Benjamim prometesse ser fiel à aliança. Assim os moradores de Jerusalém foram fiéis à aliança feita com o Deus dos seus antepassados.

'''

xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[Próximo Capítulo &#62;]