include::./index.adoc[]

[[v14-8-0]]
=== 2 Crônicas, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-8-1]]

^<<v14-8-1,1>>^ Salomão levou vinte anos para construir o Templo e o seu próprio palácio.

[[v14-8-2]]

^<<v14-8-2,2>>^ Ele também reconstruiu as cidades que Hirão, rei de Tiro, lhe tinha dado e mandou israelitas morarem nelas.

[[v14-8-3]]

^<<v14-8-3,3>>^ Depois Salomão atacou e conquistou a cidade de Hamate-Zoba.

[[v14-8-4]]

^<<v14-8-4,4>>^ Reconstruiu a cidade de Tadmor, no deserto, e todas as cidades da região de Hamate onde ele guardava os mantimentos.

[[v14-8-5]]

^<<v14-8-5,5>>^ Reconstruiu também a Bete-Horom-de-Cima e a Bete-Horom-de-Baixo, que eram cidades protegidas por muralhas e por portões com trancas,

[[v14-8-6]]

^<<v14-8-6,6>>^ a cidade de Baalate, todas as cidades onde ele guardava os seus mantimentos e as cidades onde ficavam os seus carros de guerra e os seus cavalos. Além disso, Salomão construiu tudo mais que quis em Jerusalém, no Líbano e em outras partes do seu reino.

[[v14-8-7]]

^<<v14-8-7,7>>^ Tudo o que Salomão construiu foi feito com trabalho forçado. Para isso ele usou os descendentes do povo de Canaã que os israelitas não haviam matado quando conquistaram o seu país. Entre esses trabalhadores forçados, estavam heteus, amorreus, perizeus, heveus e jebuseus. E os descendentes deles continuam como escravos até hoje .

[[v14-8-8]]

^<<v14-8-8,8>>^ Tudo o que Salomão construiu foi feito com trabalho forçado. Para isso ele usou os descendentes do povo de Canaã que os israelitas não haviam matado quando conquistaram o seu país. Entre esses trabalhadores forçados, estavam heteus, amorreus, perizeus, heveus e jebuseus. E os descendentes deles continuam como escravos até hoje .

[[v14-8-9]]

^<<v14-8-9,9>>^ Nenhum israelita foi obrigado a trabalhar como escravo. Os israelitas serviram como soldados, oficiais, capitães de carros de guerra e cavaleiros.

[[v14-8-10]]

^<<v14-8-10,10>>^ Havia duzentos e cinquenta oficiais que estavam encarregados dos trabalhadores forçados que eram usados nas várias construções de Salomão.

[[v14-8-11]]

^<<v14-8-11,11>>^ Salomão trouxe a sua esposa egípcia, a filha do rei do Egito, da Cidade de Davi  para o palácio que ele, Salomão, havia construído para ela. Ele disse: — Ela não pode morar no palácio de Davi, o rei de Israel, pois qualquer lugar em que esteve a arca da aliança  é sagrado.

[[v14-8-12]]

^<<v14-8-12,12>>^ Salomão ofereceu a Deus, o Senhor , sacrifícios  que foram completamente queimados no altar que ele havia construído para o Senhor  em frente do Templo.

[[v14-8-13]]

^<<v14-8-13,13>>^ Ele ofereceu os sacrifícios de acordo com o que o mandamento de Moisés ordenava fazer nos dias santos, isto é, nos sábados, nas Festas da Lua Nova  e nas três festas anuais, que eram a Festa dos Pães sem Fermento , a Festa da Colheita  e a Festa das Barracas .

[[v14-8-14]]

^<<v14-8-14,14>>^ De acordo com a orientação dada por Davi, o seu pai, Salomão organizou os sacerdotes em grupos para fazerem o trabalho e também os levitas , que cantavam louvores a Deus e ajudavam os sacerdotes no trabalho de todos os dias. Também organizou os guardas em grupos, para os vários portões do Templo, tudo de acordo com as ordens de Davi, homem de Deus.

[[v14-8-15]]

^<<v14-8-15,15>>^ Os sacerdotes e os levitas obedeceram rigorosamente às ordens de Davi a respeito de todos os seus deveres e também a respeito da sala do tesouro do Templo.

[[v14-8-16]]

^<<v14-8-16,16>>^ Agora estava terminado tudo o que Salomão construiu, desde a colocação da pedra fundamental do Templo até o fim da sua construção. O Templo estava pronto.

[[v14-8-17]]

^<<v14-8-17,17>>^ Depois Salomão foi até os portos de Eziom-Geber e Elate, no golfo de Ácaba, no país de Edom.

'''

xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[&#60; Capítulo Anterior] | <<v14-8-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[Próximo Capítulo &#62;]