include::./index.adoc[]

[[v14-25-0]]
=== 2 Crônicas, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-25-1]]

^<<v14-25-1,1>>^ Amazias tinha vinte e cinco anos de idade quando se tornou rei de Judá. Ele governou vinte e nove anos em Jerusalém. A mãe dele se chamava Jeoadã e era da cidade de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ Amazias fez o que é agradável a Deus, o Senhor , mas não foi sincero.

[[v14-25-3]]

^<<v14-25-3,3>>^ Logo que se firmou no poder, ele mandou matar os oficiais que haviam assassinado o seu pai, o rei.

[[v14-25-4]]

^<<v14-25-4,4>>^ No entanto, não mandou matar os filhos deles, mas seguiu o que o Senhor  havia ordenado na Lei  de Moisés: "Os pais não serão mortos por causa de crimes cometidos pelos filhos, nem os filhos, por causa de crimes cometidos pelos pais; uma pessoa será morta somente como castigo pelo crime que ela mesma cometeu."

[[v14-25-5]]

^<<v14-25-5,5>>^ Amazias mandou chamar todos os homens que tinham vinte anos de idade para cima das tribos  de Judá e de Benjamim. Ele os organizou em grupos de mil e de cem, segundo as famílias a que pertenciam, e os pôs debaixo do comando de oficiais. Eram trezentos mil homens; todos eram soldados corajosos e experientes, armados com lanças e escudos .

[[v14-25-6]]

^<<v14-25-6,6>>^ Além destes, Amazias contratou cem mil soldados de Israel por uns três mil e quatrocentos quilos de prata.

[[v14-25-7]]

^<<v14-25-7,7>>^ Mas um profeta  foi falar com Amazias e disse: — Ó rei, não leve esses soldados, pois o Senhor  Deus não está com esses homens do Reino do Norte.

[[v14-25-8]]

^<<v14-25-8,8>>^ Mas, se o senhor achar que com eles o seu exército ficará mais forte, então Deus fará com que o senhor seja vencido pelos inimigos, pois ele tem poder para dar a vitória ou a derrota.

[[v14-25-9]]

^<<v14-25-9,9>>^ Amazias perguntou: — Mas o que vai acontecer com toda aquela prata que paguei para que os soldados de Israel lutassem do meu lado? O profeta respondeu: — O Senhor  Deus pode lhe dar muito mais do que isso!

[[v14-25-10]]

^<<v14-25-10,10>>^ Então Amazias mandou os soldados do Reino do Norte de volta para casa. E eles foram embora, furiosos com o povo de Judá.

[[v14-25-11]]

^<<v14-25-11,11>>^ Amazias tomou coragem e foi com o seu exército até o vale do Sal, onde matou dez mil edomitas.

[[v14-25-12]]

^<<v14-25-12,12>>^ Outros dez mil foram presos pelos soldados de Amazias e levados até o alto de um rochedo; dali eles foram jogados e morreram esmigalhados lá em baixo.

[[v14-25-13]]

^<<v14-25-13,13>>^ Enquanto isso, os soldados israelitas que Amazias tinha mandado embora atacaram as cidades de Judá que ficavam entre Samaria e Bete-Horom; mataram três mil pessoas e levaram consigo muitas coisas.

[[v14-25-14]]

^<<v14-25-14,14>>^ Depois de ter derrotado os edomitas, Amazias voltou para Jerusalém, trazendo consigo os ídolos deles. Ele fez desses ídolos os seus próprios deuses, e os adorou, e queimou incenso a eles.

[[v14-25-15]]

^<<v14-25-15,15>>^ O Senhor  Deus ficou irado  com Amazias e enviou um profeta, que lhe disse o seguinte: — Por que o senhor está adorando esses deuses estrangeiros que não puderam salvar o povo deles das mãos do senhor?

[[v14-25-16]]

^<<v14-25-16,16>>^ Mas o rei o interrompeu, dizendo: — Desde quando eu coloquei você como meu conselheiro? Cale a boca! Se não, vou mandar matá-lo. O profeta se calou, mas antes disse: — Eu sei que Deus decidiu destruí-lo, pois o senhor fez tudo isso e não deu atenção ao meu conselho.

[[v14-25-17]]

^<<v14-25-17,17>>^ Depois de consultar os seus conselheiros, o rei Amazias mandou mensageiros ao rei de Israel, Jeoás, que era filho de Jeoacaz e neto de Jeú, desafiando-o para uma batalha.

[[v14-25-18]]

^<<v14-25-18,18>>^ Mas o rei Jeoás respondeu assim: — Uma vez um espinheiro dos montes Líbanos mandou a seguinte mensagem para um cedro: "Dê a sua filha em casamento para o meu filho." Mas um animal selvagem passou por ali e pisou em cima do espinheiro.

[[v14-25-19]]

^<<v14-25-19,19>>^ De fato, você, Amazias, venceu os edomitas e por isso está todo orgulhoso. Alegre-se com a sua fama e fique em casa. Para que arranjar um problema que trará somente a desgraça para você e para o seu povo?

[[v14-25-20]]

^<<v14-25-20,20>>^ Mas Amazias não quis atendê-lo, pois era da vontade de Deus que Amazias e o seu povo fossem presos pelos seus inimigos por terem adorado os deuses dos edomitas.

[[v14-25-21]]

^<<v14-25-21,21>>^ Então o rei Jeoás saiu com os seus soldados e lutou contra Amazias em Bete-Semes, na região de Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ O exército de Amazias foi derrotado, e todos os seus soldados fugiram para casa.

[[v14-25-23]]

^<<v14-25-23,23>>^ Jeoás prendeu Amazias em Bete-Semes e o levou para Jerusalém, onde derrubou as muralhas da cidade desde o Portão de Efraim até o Portão da Esquina, um trecho de mais ou menos duzentos metros.

[[v14-25-24]]

^<<v14-25-24,24>>^ Ele pegou toda a prata e todo o ouro que achou, pegou todos os objetos do Templo que estavam sendo guardados pelos descendentes de Obede-Edom e todos os tesouros do palácio e também levou reféns . E voltou para Samaria.

[[v14-25-25]]

^<<v14-25-25,25>>^ O rei Amazias, de Judá, viveu quinze anos depois da morte do rei de Israel, Jeoás, filho de Jeoacaz.

[[v14-25-26]]

^<<v14-25-26,26>>^ Todas as outras coisas que Amazias fez, desde o começo até o fim do seu reinado, estão escritas na História dos Reis de Judá e de Israel .

[[v14-25-27]]

^<<v14-25-27,27>>^ Depois que Amazias se revoltou contra Deus, o Senhor , houve uma conspiração em Jerusalém para matá-lo, e por isso ele fugiu para a cidade de Laquis; mas os seus inimigos o seguiram até lá e o mataram.

[[v14-25-28]]

^<<v14-25-28,28>>^ O seu corpo foi levado de volta para Jerusalém num cavalo e foi sepultado nos túmulos dos reis, na Cidade de Davi .

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]