include::./index.adoc[]

[[v14-11-0]]
=== 2 Crônicas, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-11-1]]

^<<v14-11-1,1>>^ Quando Roboão chegou a Jerusalém, reuniu cento e oitenta mil dos melhores soldados das tribos  de Judá e de Benjamim, pois tinha a intenção de lutar contra as tribos do Reino do Norte e ser o rei delas de novo.

[[v14-11-2]]

^<<v14-11-2,2>>^ Mas o Senhor  Deus falou ao profeta  Semaías e mandou

[[v14-11-3]]

^<<v14-11-3,3>>^ que desse ao rei Roboão e a todo o povo das tribos de Judá e de Benjamim o seguinte recado:

[[v14-11-4]]

^<<v14-11-4,4>>^ "Não ataquem os seus próprios irmãos, o povo de Israel. Voltem todos para casa! Se tudo aconteceu assim, foi porque eu, o Senhor  Deus, quis." Então eles obedeceram à ordem do Senhor  e não foram lutar contra Jeroboão.

[[v14-11-5]]

^<<v14-11-5,5>>^ Roboão ficou morando em Jerusalém e, para defender o país, construiu muralhas e fortalezas nas seguintes cidades de Judá e de Benjamim:

[[v14-11-6]]

^<<v14-11-6,6>>^ Belém, Etã, Tecoa,

[[v14-11-7]]

^<<v14-11-7,7>>^ Bete-Zur, Socó, Adulã,

[[v14-11-8]]

^<<v14-11-8,8>>^ Gate, Maressa, Zife,

[[v14-11-9]]

^<<v14-11-9,9>>^ Adoraim, Laquis, Azeca,

[[v14-11-10]]

^<<v14-11-10,10>>^ Zora, Aijalom e Hebrom.

[[v14-11-11]]

^<<v14-11-11,11>>^ Roboão colocou comandantes nessas cidades-fortaleza e nelas armazenou cereais, azeite e vinho.

[[v14-11-12]]

^<<v14-11-12,12>>^ Também colocou escudos  e lanças em todas elas e com isso as tornou muito fortes. Assim Roboão pôde dominar os territórios de Judá e de Benjamim.

[[v14-11-13]]

^<<v14-11-13,13>>^ De todas as partes de Israel, no Norte, sacerdotes e levitas  foram até Jerusalém.

[[v14-11-14]]

^<<v14-11-14,14>>^ Os levitas abandonaram as suas terras de pastagem e as suas outras posses e foram para Judá e para Jerusalém; pois Jeroboão, rei de Israel, e os seus sucessores não deixavam que eles servissem a Deus, o Senhor , como sacerdotes.

[[v14-11-15]]

^<<v14-11-15,15>>^ Jeroboão escolheu os seus próprios sacerdotes para oferecerem sacrifícios  em altares pagãos e adorarem demônios e as imagens de touros que ele tinha mandado fazer.

[[v14-11-16]]

^<<v14-11-16,16>>^ Pessoas de todas as tribos  de Israel que, com todo o coração, queriam adorar o Senhor , o Deus de Israel, seguiram os levitas até Jerusalém para oferecer sacrifícios ao Senhor , o Deus dos seus antepassados.

[[v14-11-17]]

^<<v14-11-17,17>>^ Isso serviu para tornar mais forte o Reino de Judá e firmar o poder de Roboão, filho de Salomão, como rei durante os três anos em que ele seguiu o exemplo de Davi e de Salomão.

[[v14-11-18]]

^<<v14-11-18,18>>^ Roboão casou com Maalate; o pai dela era Jerimote, filho de Davi, e a mãe era Abiail, filha de Eliabe e neta de Jessé.

[[v14-11-19]]

^<<v14-11-19,19>>^ Maalate teve três filhos: Jeús, Semarias e Zaão.

[[v14-11-20]]

^<<v14-11-20,20>>^ Depois Roboão casou com Maacá, filha de Absalão, e ela teve quatro filhos: Abias, Atai, Ziza e Selomite.

[[v14-11-21]]

^<<v14-11-21,21>>^ Roboão teve ao todo dezoito mulheres e sessenta concubinas , que lhe deram vinte e oito filhos e sessenta filhas. Ele amava Maacá mais do que as outras mulheres e concubinas

[[v14-11-22]]

^<<v14-11-22,22>>^ e por isso escolheu Abias, o filho dela, para ser o príncipe herdeiro, que ficaria no lugar dele como rei de Judá.

[[v14-11-23]]

^<<v14-11-23,23>>^ Roboão também teve a boa ideia de espalhar os seus outros filhos pelas cidades-fortaleza de Judá e de Benjamim. Deu-lhes grandes quantidades de alimentos e também arranjou muitas mulheres para eles.

'''

xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[Próximo Capítulo &#62;]