include::./index.adoc[]

[[v14-35-0]]
=== 2 Crônicas, 35
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-35-1]]

^<<v14-35-1,1>>^ Josias comemorou em Jerusalém a Festa da Páscoa  em honra de Deus, o Senhor ; no dia catorze do primeiro mês, foram mortos os carneiros para a festa.

[[v14-35-2]]

^<<v14-35-2,2>>^ Ele pôs os sacerdotes nos seus lugares de serviço no Templo e os animou a fazerem bem o seu trabalho.

[[v14-35-3]]

^<<v14-35-3,3>>^ Depois mandou chamar os levitas , que ensinavam a Lei  de Deus a todos os israelitas e que eram separados para o serviço do Senhor , e lhes disse: — Ponham a arca da aliança  no Templo construído pelo rei Salomão, filho de Davi; daqui em diante, vocês não precisarão carregá-la nos ombros. Dediquem-se ao serviço do Senhor , nosso Deus, e do seu povo de Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ Organizem-se para o serviço por grupos e por famílias, de acordo com as ordens escritas pelo rei Davi, de Israel, e pelo seu filho Salomão.

[[v14-35-5]]

^<<v14-35-5,5>>^ Os grupos devem ser organizados de acordo com os grupos de famílias do nosso povo, a fim de que haja um grupo de levitas à disposição de cada grupo de famílias.

[[v14-35-6]]

^<<v14-35-6,6>>^ Matem os carneiros para a Páscoa, purifiquem-se  e preparem a Festa a fim de que os seus irmãos, os outros israelitas, comemorem a Páscoa de acordo com as ordens que Deus nos deu por meio de Moisés.

[[v14-35-7]]

^<<v14-35-7,7>>^ Do seu gado e dos seus rebanhos, o rei Josias deu ao povo os animais para a Festa da Páscoa: trinta mil carneiros e cabritos e três mil touros.

[[v14-35-8]]

^<<v14-35-8,8>>^ As autoridades também deram ofertas ao povo, aos sacerdotes e aos levitas. E Hilquias, Zacarias e Jeiel, os administradores do Templo, deram aos sacerdotes dois mil e seiscentos carneiros e cabritos e trezentos touros para os sacrifícios  da Páscoa.

[[v14-35-9]]

^<<v14-35-9,9>>^ Os chefes dos levitas, Conanias, os seus irmãos Semaías e Netanel, e também Hasabias, Jeiel e Jozabade deram aos levitas cinco mil carneiros e cabritos e quinhentos touros para a Páscoa.

[[v14-35-10]]

^<<v14-35-10,10>>^ Quando tudo estava pronto para a Festa, os sacerdotes foram para os seus lugares, e os levitas se juntaram em grupos, de acordo com o que o rei havia ordenado.

[[v14-35-11]]

^<<v14-35-11,11>>^ Aí foram mortos os carneiros e os cabritos; os levitas tiravam a pele dos animais, davam o sangue aos sacerdotes, e estes borrifavam o altar com ele.

[[v14-35-12]]

^<<v14-35-12,12>>^ Entregaram ao povo, segundo os grupos de famílias, a gordura dos animais que seria queimada como sacrifício  a Deus, o Senhor , de acordo com o que a Lei de Moisés manda. E fizeram a mesma coisa com os touros.

[[v14-35-13]]

^<<v14-35-13,13>>^ Depois assaram os animais de acordo com a lei; cozinharam as outras ofertas sagradas em panelas, caldeirões e frigideiras e distribuíram rapidamente para todo o povo.

[[v14-35-14]]

^<<v14-35-14,14>>^ Em seguida, os levitas prepararam o que era deles e dos sacerdotes, os descendentes de Arão. Os levitas precisaram fazer isso porque os sacerdotes ficaram ocupados até a noite, oferecendo a Deus os animais que eram completamente queimados e a gordura.

[[v14-35-15]]

^<<v14-35-15,15>>^ Os cantores do grupo de Asafe estavam nos seus lugares, de acordo com as ordens do rei Davi e de Asafe, de Hemã e de Jedutum, o profeta  do rei. Os guardas também estavam nos seus lugares guardando os portões do Templo. Nenhum deles precisou abandonar o seu posto, pois os seus colegas, os outros levitas, prepararam a parte dos sacrifícios que era deles.

[[v14-35-16]]

^<<v14-35-16,16>>^ Assim tudo foi feito naquele dia para a adoração de Deus, o Senhor , como o rei Josias havia ordenado: comemoraram a Festa da Páscoa em honra do Senhor  e apresentaram as ofertas que eram completamente queimadas no altar.

[[v14-35-17]]

^<<v14-35-17,17>>^ Durante sete dias, todos os israelitas que estavam em Jerusalém tomaram parte na Festa da Páscoa e na Festa dos Pães sem Fermento .

[[v14-35-18]]

^<<v14-35-18,18>>^ Desde o tempo do profeta Samuel, os israelitas nunca haviam comemorado uma Festa da Páscoa como esta. Nenhum outro rei de Israel comemorou a Festa como Josias fez com os sacerdotes e os levitas, com o povo de Judá e de Israel que estava presente e com os moradores de Jerusalém.

[[v14-35-19]]

^<<v14-35-19,19>>^ Foi no ano dezoito do seu reinado que essa Páscoa foi comemorada.

[[v14-35-20]]

^<<v14-35-20,20>>^ Depois de tudo isso, quando Josias já havia acabado de pôr em ordem o Templo e o culto, o rei Neco, do Egito, marchou com o seu exército para lutar em Carquemis, que ficava na beira do rio Eufrates. Josias saiu com o seu exército para lutar contra ele,

[[v14-35-21]]

^<<v14-35-21,21>>^ mas Neco lhe mandou a seguinte mensagem: — Rei de Judá, você não tem nada a ver com esta luta. Eu não vim lutar contra você, mas contra os meus inimigos, e Deus mandou que eu me apressasse. Deus está comigo; portanto, se você lutar contra Deus, ele o destruirá.

[[v14-35-22]]

^<<v14-35-22,22>>^ Mas Josias não voltou atrás; ele não quis dar atenção ao aviso que Deus estava dando por meio do rei Neco. Pelo contrário, ele se disfarçou e marchou para lutar contra Neco no vale de Megido.

[[v14-35-23]]

^<<v14-35-23,23>>^ Os soldados egípcios atiraram flechas contra Josias, e ele gritou para os seus oficiais: — Estou gravemente ferido! Tirem-me daqui!

[[v14-35-24]]

^<<v14-35-24,24>>^ Os oficiais o tiraram do seu carro de guerra, e o puseram em outro carro, e o levaram para Jerusalém. Josias morreu e foi sepultado nos túmulos dos reis. Todo o povo de Judá e de Jerusalém chorou a morte dele.

[[v14-35-25]]

^<<v14-35-25,25>>^ O profeta  Jeremias compôs uma lamentação em honra de Josias. Até hoje  os cantores e as cantoras cantam essa canção quando choram a morte de Josias. Já se tornou costume em Israel cantar essas canções, que se acham na coleção de lamentações.

[[v14-35-26]]

^<<v14-35-26,26>>^ Josias fez muitas outras coisas e praticou atos de bondade em obediência à Lei  de Deus, o Senhor .

[[v14-35-27]]

^<<v14-35-27,27>>^ Tudo o que ele fez, desde o começo até o fim do seu reinado, está escrito na História dos Reis de Israel e de Judá .

'''

xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[Próximo Capítulo &#62;]