include::./index.adoc[]

[[v14-9-0]]
=== 2 Crônicas, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-9-1]]

^<<v14-9-1,1>>^ A rainha de Sabá ouviu falar da fama de Salomão e foi até Jerusalém a fim de pô-lo à prova com perguntas difíceis. Ela chegou com um grande grupo de servidores e também camelos carregados de especiarias , uma grande quantidade de ouro e de pedras preciosas. Quando se encontrou com Salomão, ela lhe fez todas as perguntas que pôde imaginar.

[[v14-9-2]]

^<<v14-9-2,2>>^ Ele respondeu a todas; não houve nenhuma que fosse difícil demais para ele responder.

[[v14-9-3]]

^<<v14-9-3,3>>^ A rainha de Sabá ouviu a sabedoria de Salomão e viu o palácio que ele havia construído.

[[v14-9-4]]

^<<v14-9-4,4>>^ Ela viu a comida que era servida na mesa dele, viu os apartamentos dos seus altos funcionários, a organização do pessoal que trabalhava no palácio e os uniformes que eles usavam. Viu os empregados que o serviam nos banquetes e os seus uniformes e os sacrifícios  que ele oferecia no Templo. Isso tudo a deixou de boca aberta e muito admirada.

[[v14-9-5]]

^<<v14-9-5,5>>^ Então ela disse ao rei Salomão: — Tudo aquilo que eu ouvi no meu país a respeito de você e da sua sabedoria é, de fato, verdade.

[[v14-9-6]]

^<<v14-9-6,6>>^ Porém eu não pude acreditar até que vim e vi com os meus próprios olhos. Acontece que não tinham me contado nem a metade da sua sabedoria; ela vai muito além daquilo que ouvi dizer.

[[v14-9-7]]

^<<v14-9-7,7>>^ Que sorte têm estes seus servidores, que estão sempre ao seu lado e têm o privilégio de ouvir os seus sábios provérbios!

[[v14-9-8]]

^<<v14-9-8,8>>^ Bendito seja o Senhor , seu Deus, que ficou tão contente com você, que o tornou rei de Israel para governar em nome dele! O amor dele pelo povo de Israel é eterno, e ele quer conservar este povo para sempre como uma nação e por isso ele o fez rei de Israel, para que você possa manter a lei  e a justiça.

[[v14-9-9]]

^<<v14-9-9,9>>^ Ela entregou ao rei os presentes que havia trazido: mais de quatro mil quilos de ouro e uma grande quantidade de especiarias e de pedras preciosas. Nunca houve especiarias tão finas como as que a rainha de Sabá deu ao rei Salomão.

[[v14-9-10]]

^<<v14-9-10,10>>^ (Os homens do rei Hirão e do rei Salomão que haviam trazido ouro da terra de Ofir também trouxeram madeira de sândalo e pedras preciosas.

[[v14-9-11]]

^<<v14-9-11,11>>^ Salomão usou a madeira para fazer degraus para o Templo e para o palácio e também fez harpas  e liras  para os músicos. Nunca tinham sido vistos em Jerusalém instrumentos musicais tão bonitos.)

[[v14-9-12]]

^<<v14-9-12,12>>^ O rei Salomão deu à rainha de Sabá tudo o que ela quis e pediu, além dos presentes que lhe deu em troca dos presentes que ela havia trazido para ele. Então a rainha e os seus servidores voltaram para Sabá, a sua terra.

[[v14-9-13]]

^<<v14-9-13,13>>^ Todos os anos o rei Salomão recebia mais ou menos vinte e três mil quilos de ouro,

[[v14-9-14]]

^<<v14-9-14,14>>^ além dos impostos pagos pelos comerciantes e vendedores. Também os reis árabes e os administradores dos vários distritos do país lhe traziam prata e ouro.

[[v14-9-15]]

^<<v14-9-15,15>>^ Salomão fez duzentos grandes escudos  e mandou folhear cada um com quase sete quilos de ouro.

[[v14-9-16]]

^<<v14-9-16,16>>^ Também fez trezentos escudos menores e folheou cada um com quase três quilos e meio de ouro. Ele mandou colocar todos esses escudos no Salão da Floresta do Líbano .

[[v14-9-17]]

^<<v14-9-17,17>>^ Salomão também mandou fazer um grande trono, revestido de marfim e de ouro puro.

[[v14-9-18]]

^<<v14-9-18,18>>^ O trono tinha seis degraus, e ligado ao trono havia um estrado revestido de ouro. O trono tinha dois braços, e no lado de cada braço havia a figura de um leão.

[[v14-9-19]]

^<<v14-9-19,19>>^ Havia também a figura de um leão nas pontas de cada degrau, isto é, havia doze leões ao todo. Nunca tinha sido feito em qualquer outro reino um trono como este.

[[v14-9-20]]

^<<v14-9-20,20>>^ Todas as taças que o rei Salomão usava para beber eram de ouro, e todos os objetos do Salão da Floresta do Líbano eram de ouro puro. No tempo de Salomão a prata era considerada sem valor.

[[v14-9-21]]

^<<v14-9-21,21>>^ Salomão tinha uma frota de navios que viajava até a Espanha junto com a frota do rei Hirão. Cada três anos a sua frota voltava trazendo ouro, prata, marfim, macacos e micos.

[[v14-9-22]]

^<<v14-9-22,22>>^ O rei Salomão era mais rico e mais sábio do que qualquer outro rei,

[[v14-9-23]]

^<<v14-9-23,23>>^ e todos os outros reis queriam ir ouvir a sabedoria que Deus lhe tinha dado.

[[v14-9-24]]

^<<v14-9-24,24>>^ Todos os que chegavam traziam um presente para ele: objetos de prata e de ouro, roupas, armas, especiarias , cavalos e mulas. E era assim ano após ano.

[[v14-9-25]]

^<<v14-9-25,25>>^ Salomão tinha quatro mil cocheiras para os seus carros de guerra e para os seus cavalos e também possuía doze mil cavalos de cavalaria. Ele deixou em Jerusalém uma parte deles e espalhou o resto por várias cidades que haviam sido preparadas para isso.

[[v14-9-26]]

^<<v14-9-26,26>>^ Ele dominava todos os reis que havia desde o rio Eufrates até a terra dos filisteus e até a fronteira do Egito.

[[v14-9-27]]

^<<v14-9-27,27>>^ Em Jerusalém, durante o seu reinado, a prata era tão comum como as pedras, e havia tantos cedros como as figueiras bravas que existem nas planícies de Judá.

[[v14-9-28]]

^<<v14-9-28,28>>^ Ele importava cavalos de Musri e de todos os outros países.

[[v14-9-29]]

^<<v14-9-29,29>>^ Todas as outras coisas que Salomão fez, do princípio do seu reinado até o fim, estão escritas nos livros História do Profeta Natã , Profecia de Aías, de Siló , e Visões do Profeta Ido ; esse último livro fala também do rei Jeroboão, filho de Nebate.

[[v14-9-30]]

^<<v14-9-30,30>>^ Salomão governou quarenta anos em Jerusalém como rei de toda a terra de Israel.

[[v14-9-31]]

^<<v14-9-31,31>>^ Ele morreu e foi sepultado na Cidade de Davi , e o seu filho Roboão ficou no lugar dele como rei.

'''

xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[Próximo Capítulo &#62;]