include::./index.adoc[]

[[v14-12-0]]
=== 2 Crônicas, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-12-1]]

^<<v14-12-1,1>>^ Logo que Roboão firmou o seu poder como rei de Judá, ele e todo o seu povo deixaram de obedecer à Lei  de Deus, o Senhor .

[[v14-12-2]]

^<<v14-12-2,2>>^ Eles foram infiéis a Deus, e por isso no quinto ano do reinado de Roboão, Sisaque, rei do Egito, atacou Jerusalém.

[[v14-12-3]]

^<<v14-12-3,3>>^ Ele tinha mil e duzentos carros de guerra, sessenta mil cavaleiros e um exército enorme de líbios, suquitas e etíopes; eram tantos, que não podiam ser contados.

[[v14-12-4]]

^<<v14-12-4,4>>^ Sisaque conquistou as cidades-fortaleza de Judá e marchou contra Jerusalém.

[[v14-12-5]]

^<<v14-12-5,5>>^ Aí o profeta  Semaías foi falar com Roboão e com as altas autoridades do país, que se haviam ajuntado em Jerusalém, fugindo de Sisaque. Semaías disse: — Esta é a mensagem de Deus, o Senhor : "Vocês me abandonaram, e por isso eu os estou entregando nas mãos de Sisaque."

[[v14-12-6]]

^<<v14-12-6,6>>^ Então o rei e as autoridades confessaram o seu pecado e disseram: — O Senhor  Deus é justo!

[[v14-12-7]]

^<<v14-12-7,7>>^ Quando o Senhor  viu que eles se haviam arrependido, disse a Semaías: — Eles se arrependeram, e por isso não vou destruí-los. Daqui a pouco vou salvá-los. Eu não vou usar Sisaque para descarregar a minha ira  sobre os moradores de Jerusalém.

[[v14-12-8]]

^<<v14-12-8,8>>^ Mas vou deixar que Sisaque os domine a fim de que eles vejam qual é a diferença entre servir a mim e servir reis estrangeiros.

[[v14-12-9]]

^<<v14-12-9,9>>^ Então o rei Sisaque atacou Jerusalém e a tomou; levou embora todos os tesouros do Templo e do palácio e também os escudos  de ouro que Salomão havia feito.

[[v14-12-10]]

^<<v14-12-10,10>>^ Para colocar no lugar deles, o rei Roboão fez escudos de bronze e os entregou aos oficiais encarregados de guardar os portões do palácio.

[[v14-12-11]]

^<<v14-12-11,11>>^ Todas as vezes que o rei ia ao Templo, os guardas pegavam e carregavam os escudos e depois os levavam de volta para a sala dos guardas.

[[v14-12-12]]

^<<v14-12-12,12>>^ Assim Deus acalmou a sua ira e não destruiu Roboão, pois Roboão se arrependeu. E além disso havia gente boa na terra de Judá.

[[v14-12-13]]

^<<v14-12-13,13>>^ O rei Roboão foi ficando cada vez mais forte e continuou a reinar em Jerusalém. Ele tinha quarenta e um anos de idade quando se tornou rei. E governou dezessete anos em Jerusalém, a cidade que o Senhor  Deus havia escolhido entre todas as tribos  da terra de Israel como o lugar onde devia ser adorado. A mãe de Roboão era Naama, do país de Amom.

[[v14-12-14]]

^<<v14-12-14,14>>^ Roboão fez o que era errado, pois não procurou com todo o coração conhecer a vontade de Deus, o Senhor .

[[v14-12-15]]

^<<v14-12-15,15>>^ Todas as outras coisas que Roboão fez, do princípio até o fim do seu reinado, estão escritas na História do Profeta Semaías  e na História do Profeta Ido , conforme está registrado na lista dos antepassados de Roboão. Durante todo esse tempo, Roboão e Jeroboão estiveram em guerra um contra o outro.

[[v14-12-16]]

^<<v14-12-16,16>>^ Ele morreu e foi sepultado na Cidade de Davi , e o seu filho Abias ficou no lugar dele como rei.

'''

xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[&#60; Capítulo Anterior] | <<v14-12-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[Próximo Capítulo &#62;]