include::./index.adoc[]

[[v14-20-0]]
=== 2 Crônicas, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-20-1]]

^<<v14-20-1,1>>^ Algum tempo depois, os exércitos dos moabitas e dos amonitas, junto com os meunitas, invadiram o país de Judá.

[[v14-20-2]]

^<<v14-20-2,2>>^ Alguns homens vieram e disseram a Josafá: — Um exército enorme do país de Edom veio do outro lado do mar Morto para atacar o senhor. Eles já conquistaram a cidade de Hazazão-Tamar. (Hazazão-Tamar e Fonte de Gedi são o mesmo lugar.)

[[v14-20-3]]

^<<v14-20-3,3>>^ Josafá ficou com medo e orou a Deus, o Senhor , pedindo socorro. Depois deu ordem para que todo o povo de Judá jejuasse.

[[v14-20-4]]

^<<v14-20-4,4>>^ Todos se reuniram para pedir socorro ao Senhor ; de todas as cidades do país o povo veio a Jerusalém.

[[v14-20-5]]

^<<v14-20-5,5>>^ A gente de Judá e de Jerusalém se reuniu no pátio novo do Templo, e Josafá se pôs de pé no meio deles

[[v14-20-6]]

^<<v14-20-6,6>>^ e orou assim: — Ó Senhor , Deus dos nossos antepassados! Tu és o Deus do céu e governas todas as nações do mundo. Tu és forte e poderoso, e ninguém pode resistir ao teu poder.

[[v14-20-7]]

^<<v14-20-7,7>>^ Tu és o nosso Deus; expulsaste os moradores desta terra de diante do teu povo de Israel e deste a terra deles para sempre a nós, os descendentes de Abraão, teu amigo.

[[v14-20-8]]

^<<v14-20-8,8>>^ O teu povo tem morado nesta terra, e aqui construímos um Templo em tua honra. Nós dissemos assim:

[[v14-20-9]]

^<<v14-20-9,9>>^ "Se alguma desgraça cair sobre nós como castigo, seja guerra, ou doenças, ou falta de alimentos, então nos ajuntaremos em frente deste Templo, onde tu moras, e no nosso sofrimento clamaremos a ti pedindo socorro, e tu atenderás o nosso pedido."

[[v14-20-10]]

^<<v14-20-10,10>>^ — Agora os amonitas e os moabitas, junto com os edomitas, invadiram o nosso país. Quando os nossos antepassados estavam vindo do Egito, tu não os deixaste invadir as terras daqueles povos. Por isso, os nossos antepassados se desviaram delas e não destruíram aqueles povos.

[[v14-20-11]]

^<<v14-20-11,11>>^ Mas agora eles nos pagam assim: estão nos atacando para nos expulsar da terra que nos deste para sempre.

[[v14-20-12]]

^<<v14-20-12,12>>^ Ó nosso Deus, castiga essa gente, pois não somos bastante fortes para resistir a esse enorme exército que está avançando contra nós. Não sabemos o que fazer e olhamos para ti, pedindo socorro!

[[v14-20-13]]

^<<v14-20-13,13>>^ Todos os homens de Judá estavam ali de pé em frente do Templo, junto com as suas mulheres e os seus filhos e até as crianças de colo.

[[v14-20-14]]

^<<v14-20-14,14>>^ De repente, o Espírito de Deus desceu sobre um levita  que estava ali no meio do povo. Chamava-se Jaaziel e era descendente de Asafe. Jaaziel era filho de Zacarias, neto de Benaías, bisneto de Jeiel e trineto de Matanias.

[[v14-20-15]]

^<<v14-20-15,15>>^ Jaaziel disse: — Povo de Judá, moradores de Jerusalém e rei Josafá, prestem atenção! Escutem isto que o Senhor  Deus diz: "Não se assustem, não fiquem com medo deste enorme exército, pois a batalha não é contra vocês, mas contra mim.

[[v14-20-16]]

^<<v14-20-16,16>>^ Amanhã vocês os atacarão quando eles vierem pela subida de Zis. Vocês se encontrarão com eles no fim do vale que dá para o deserto de Jeruel.

[[v14-20-17]]

^<<v14-20-17,17>>^ Quando os encontrarem, vocês não precisarão lutar. Fiquem parados ali e verão como o Senhor  Deus salvará vocês. Povo de Judá e moradores de Jerusalém, não se assustem, nem fiquem com medo; marchem contra os inimigos amanhã, pois eu, o Senhor , estarei com vocês."

[[v14-20-18]]

^<<v14-20-18,18>>^ Então o rei Josafá se ajoelhou e encostou o rosto no chão; e todo o povo de Judá e os moradores de Jerusalém também se ajoelharam na presença de Deus, o Senhor , e o adoraram.

[[v14-20-19]]

^<<v14-20-19,19>>^ Aí os levitas que eram descendentes de Coate e de Corá começaram a louvar o Senhor , o Deus de Israel, em voz bem alta.

[[v14-20-20]]

^<<v14-20-20,20>>^ Na manhã seguinte, todos se levantaram cedo e foram para o deserto de Tecoa. Ao saírem, Josafá ficou de pé e disse: — Povo de Judá e moradores de Jerusalém, escutem! Confiem no Senhor , seu Deus, e estarão seguros; confiem nos profetas  dele, e tudo o que vocês fizerem dará certo.

[[v14-20-21]]

^<<v14-20-21,21>>^ Depois de consultar o povo, Josafá ordenou que alguns cantores vestissem roupas sagradas e marchassem à frente do exército, louvando a Deus e cantando assim: "Louvem a Deus, o Senhor , porque o seu amor dura para sempre."

[[v14-20-22]]

^<<v14-20-22,22>>^ Logo que começaram a cantar, o Senhor  Deus causou confusão entre os moabitas, os amonitas e os edomitas, e eles foram derrotados.

[[v14-20-23]]

^<<v14-20-23,23>>^ Os amonitas e os moabitas atacaram os edomitas e os destruíram completamente; depois os amonitas lutaram contra os moabitas, e os dois lados também acabaram se destruindo.

[[v14-20-24]]

^<<v14-20-24,24>>^ Quando o exército de Judá chegou a um lugar alto no deserto, eles viram o chão coberto de mortos; ninguém tinha escapado com vida.

[[v14-20-25]]

^<<v14-20-25,25>>^ Aí Josafá e os seus soldados avançaram e começaram a pegar tudo o que havia no acampamento inimigo. Encontraram muitos animais de carga, armas, roupas e objetos de valor. Levaram três dias pegando as coisas, mas havia tanto, que não puderam levar tudo.

[[v14-20-26]]

^<<v14-20-26,26>>^ No quarto dia, todos se reuniram no vale de Beraca e louvaram o Senhor . É por isso que aquele lugar se chama vale de Beraca até hoje .

[[v14-20-27]]

^<<v14-20-27,27>>^ Depois os soldados de Judá e de Jerusalém, com Josafá à frente, voltaram alegres para Jerusalém. Estavam contentes porque o Senhor  Deus lhes tinha dado a vitória na luta contra os seus inimigos.

[[v14-20-28]]

^<<v14-20-28,28>>^ Quando chegaram a Jerusalém, foram até o Templo, ao som de música de harpas , liras  e trombetas.

[[v14-20-29]]

^<<v14-20-29,29>>^ Quando os outros povos souberam que o Senhor  havia derrotado os inimigos de Israel, ficaram todos com medo.

[[v14-20-30]]

^<<v14-20-30,30>>^ Assim o reinado de Josafá continuou tranquilo, pois Deus lhe deu paz com todas as nações vizinhas.

[[v14-20-31]]

^<<v14-20-31,31>>^ Josafá tinha trinta e cinco anos de idade quando se tornou rei de Judá. Ele governou em Jerusalém vinte e cinco anos. A sua mãe se chamava Azuba e era filha de Sili.

[[v14-20-32]]

^<<v14-20-32,32>>^ Como Asa, o seu pai, havia feito antes dele, Josafá fez o que o Senhor  Deus considera certo.

[[v14-20-33]]

^<<v14-20-33,33>>^ Mas os lugares pagãos de adoração não foram destruídos, pois o povo ainda não tinha resolvido adorar somente o Deus dos seus antepassados.

[[v14-20-34]]

^<<v14-20-34,34>>^ Todas as outras coisas que Josafá fez, desde o começo até o fim do seu reinado, estão escritas na História de Jeú, filho de Hanani , que faz parte da História dos Reis de Israel .

[[v14-20-35]]

^<<v14-20-35,35>>^ Mais tarde, o rei Josafá se tornou aliado de Acazias, rei de Israel, que vivia uma vida cheia de maldade.

[[v14-20-36]]

^<<v14-20-36,36>>^ Eles fizeram um acordo  para construírem navios que fossem até a Espanha; os navios foram construídos em Eziom-Geber.

[[v14-20-37]]

^<<v14-20-37,37>>^ Mas Eliézer, filho de Dodavá, profetizou  contra Josafá o seguinte: — O Senhor  Deus vai destruir o que o senhor construiu porque o senhor se tornou aliado de Acazias. Os navios se quebraram e não puderam ir até a Espanha.

'''

xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[&#60; Capítulo Anterior] | <<v14-20-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[Próximo Capítulo &#62;]