include::./index.adoc[]

[[v14-6-0]]
=== 2 Crônicas, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-6-1]]

^<<v14-6-1,1>>^ Então Salomão orou assim: "Ó Senhor  Deus, tu resolveste viver entre as nuvens escuras.

[[v14-6-2]]

^<<v14-6-2,2>>^ Mas agora eu construí para ti uma casa, um lugar onde viverás para sempre."

[[v14-6-3]]

^<<v14-6-3,3>>^ Aí Salomão virou, olhou para o povo, que estava todo de pé, e pediu a bênção de Deus para todos.

[[v14-6-4]]

^<<v14-6-4,4>>^ Depois disse: — Bendito seja o Senhor , o Deus de Israel! Pois pelo seu poder ele cumpriu a promessa que tinha feito a Davi, o meu pai, quando lhe disse:

[[v14-6-5]]

^<<v14-6-5,5>>^ "Desde o dia em que tirei o meu povo do Egito, eu não escolhi nenhuma cidade de todas as tribos  da terra de Israel para ali construir um templo a fim de ser adorado nele, nem escolhi nenhum homem para governar o meu povo de Israel.

[[v14-6-6]]

^<<v14-6-6,6>>^ Mas agora escolhi Jerusalém como o lugar onde serei adorado e escolhi você, Davi, para governar o meu povo."

[[v14-6-7]]

^<<v14-6-7,7>>^ E Salomão continuou: — Davi, o meu pai, tinha planos de construir um templo para a adoração do Senhor , o Deus de Israel,

[[v14-6-8]]

^<<v14-6-8,8>>^ mas o Senhor  lhe disse: "Você fez bem quando planejou construir um templo para mim,

[[v14-6-9]]

^<<v14-6-9,9>>^ mas você não o construirá. Será o seu filho quem construirá o meu Templo."

[[v14-6-10]]

^<<v14-6-10,10>>^ E agora o Senhor  cumpriu a sua promessa. Eu fiquei no lugar do meu pai como rei de Israel e construí o Templo para a adoração do Senhor , o Deus de Israel.

[[v14-6-11]]

^<<v14-6-11,11>>^ Ali eu coloquei a arca da aliança , onde estão guardadas as placas de pedra da aliança que o Senhor  Deus fez com o povo de Israel.

[[v14-6-12]]

^<<v14-6-12,12>>^ Então, na presença de todo o povo, Salomão foi, ficou em frente do altar e levantou as mãos.

[[v14-6-13]]

^<<v14-6-13,13>>^ Ele havia mandado construir no pátio do Templo um estrado quadrado de bronze que media dois metros e vinte em cada lado e um metro e trinta de altura. Ele subiu no estrado e, na presença de todo o povo, se ajoelhou, levantou as mãos para o céu

[[v14-6-14]]

^<<v14-6-14,14>>^ e orou assim: — Ó Senhor , Deus de Israel! Não há Deus igual a ti no céu ou na terra. Tu és fiel à aliança  que fizeste com o teu povo e lhes mostras o teu amor quando eles, com todo o coração, vivem uma vida de obediência a ti.

[[v14-6-15]]

^<<v14-6-15,15>>^ Pelo teu poder cumpriste a promessa que fizeste a Davi, o meu pai; no dia de hoje, todas as palavras da tua promessa foram completamente cumpridas.

[[v14-6-16]]

^<<v14-6-16,16>>^ E agora, ó Senhor , Deus de Israel, eu te peço que cumpras a outra promessa que fizeste ao meu pai, quando lhe disseste que sempre haveria um descendente dele governando como rei de Israel, contanto que eles te obedecessem com o mesmo cuidado com que ele obedeceu.

[[v14-6-17]]

^<<v14-6-17,17>>^ Portanto, ó Deus de Israel, faze com que se cumpra aquilo que prometeste a teu servo  Davi.

[[v14-6-18]]

^<<v14-6-18,18>>^ — Mas será que, de fato, ó Deus, tu podes morar no meio de nós, criaturas humanas, aqui na terra? Tu és tão grande, que não cabes nem mesmo no céu. Como poderia este Templo que eu construí ser bastante grande para isso?

[[v14-6-19]]

^<<v14-6-19,19>>^ Ó Senhor , meu Deus, eu sou teu servo. Escuta a minha oração e atende os pedidos que te faço.

[[v14-6-20]]

^<<v14-6-20,20>>^ Olha de dia e de noite para este Templo, o lugar que escolheste para nele seres adorado. Ouve-me quando eu orar com o rosto virado para este lugar.

[[v14-6-21]]

^<<v14-6-21,21>>^ Escuta as minhas orações e as orações do teu povo quando eles orarem com o rosto virado para cá. Sim, da tua casa no céu, ouve-nos e perdoa-nos.

[[v14-6-22]]

^<<v14-6-22,22>>^ — Quando alguém for acusado de prejudicar outra pessoa e for trazido até o teu altar neste Templo e jurar que é inocente,

[[v14-6-23]]

^<<v14-6-23,23>>^ ó Deus, ouve do céu e julga os teus servos. Castiga o culpado como ele merecer e declara que não tem culpa aquele que for inocente, recompensando-o como ele merecer.

[[v14-6-24]]

^<<v14-6-24,24>>^ — Quando, por ter pecado contra ti, o teu povo de Israel for derrotado pelos seus inimigos e quando ele se virar para ti e vier a este Templo para te louvar e pedir o teu perdão,

[[v14-6-25]]

^<<v14-6-25,25>>^ escuta-o do céu. Perdoa o pecado do teu povo e leva-o de volta para a terra que deste a eles e aos seus antepassados.

[[v14-6-26]]

^<<v14-6-26,26>>^ — Quando o céu se fechar e não chover porque o teu povo pecou contra ti, e então eles se arrependerem, e virarem o rosto na direção deste Templo, e orarem e te louvarem, depois que os tiveres castigado,

[[v14-6-27]]

^<<v14-6-27,27>>^ escuta-os do céu. Perdoa os pecados dos teus servos, o povo de Israel, e ensina-os a fazer o que é direito. Então, ó Deus, faze cair chuva sobre esta tua terra que deste ao teu povo para ser deles para sempre.

[[v14-6-28]]

^<<v14-6-28,28>>^ — Quando nesta terra houver falta de alimento ou houver pragas, ou as colheitas forem destruídas por ventos muito quentes ou por bandos de gafanhotos, ou quando o teu povo for atacado pelos seus inimigos, ou quando houver peste ou doença entre o povo,

[[v14-6-29]]

^<<v14-6-29,29>>^ escuta as suas orações. Se alguém do teu povo de Israel, sentindo o peso da sua desgraça e do seu sofrimento, estender as mãos na direção deste Templo e orar,

[[v14-6-30]]

^<<v14-6-30,30>>^ escuta a sua oração. Ouve o teu povo do teu lar no céu e perdoa-o e ajuda-o. Só tu conheces os pensamentos secretos do coração humano. Trata cada pessoa como merecer,

[[v14-6-31]]

^<<v14-6-31,31>>^ para que o teu povo te tema  e te obedeça todo o tempo em que eles viverem na terra que deste aos nossos antepassados.

[[v14-6-32]]

^<<v14-6-32,32>>^ — Quando um estrangeiro que viver numa terra bem longe daqui ouvir falar da tua fama e das grandes coisas que tens feito e vier te adorar e orar com o rosto virado para este Templo,

[[v14-6-33]]

^<<v14-6-33,33>>^ ouve a sua oração. Lá do céu, onde vives, escuta-o e faze tudo o que ele te pedir, para que todos os povos da terra possam te conhecer e temer, como faz o teu povo de Israel. Então eles ficarão sabendo que este Templo que eu construí é o lugar onde deves ser adorado.

[[v14-6-34]]

^<<v14-6-34,34>>^ — Quando ordenares que o teu povo saia para a guerra contra os seus inimigos, e o teu povo orar a ti, virado para esta cidade que escolheste e para este Templo que construí em honra do teu nome,

[[v14-6-35]]

^<<v14-6-35,35>>^ escuta do céu as suas orações e os seus pedidos. Ouve-os e dá-lhes a vitória.

[[v14-6-36]]

^<<v14-6-36,36>>^ — Quando o teu povo pecar contra ti — e não há ninguém que não peque —, e na tua ira  deixares que os seus inimigos os derrotem e os levem como prisioneiros para alguma terra inimiga, longe ou perto daqui,

[[v14-6-37]]

^<<v14-6-37,37>>^ escuta as orações do teu povo. Se ali, naquela terra, eles se arrependerem e orarem a ti, confessando que foram pecadores e maus, ouve as suas orações, ó Deus.

[[v14-6-38]]

^<<v14-6-38,38>>^ Se naquela terra eles verdadeiramente e sinceramente se arrependerem e orarem a ti, virados na direção desta terra que deste aos nossos antepassados, desta cidade que escolheste e deste Templo que construí em honra do teu nome,

[[v14-6-39]]

^<<v14-6-39,39>>^ escuta as orações deles. Do teu lar no céu, ouve-os e dá-lhes a vitória. Perdoa os pecados que o teu povo tem cometido contra ti.

[[v14-6-40]]

^<<v14-6-40,40>>^ — Agora, ó meu Deus, olha para nós com simpatia e ouve as orações que forem feitas neste lugar.

[[v14-6-41]]

^<<v14-6-41,41>>^ Levanta-te, ó Senhor  Deus, e vem para o teu lugar de descanso, junto com a arca da aliança, que representa o teu poder. Que os teus sacerdotes façam sempre o que tu queres, e que todo o povo fique alegre por causa da tua bondade!

[[v14-6-42]]

^<<v14-6-42,42>>^ Ó Senhor  Deus, não rejeites o rei que escolheste. Lembra do teu amor para com teu servo Davi.

'''

xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[Próximo Capítulo &#62;]