include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-4-1]]

^<<v14-4-1,1>>^ Salomão mandou fazer um altar de bronze, de nove metros de comprimento por nove de largura e quatro e meio de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ Também mandou fazer um tanque redondo de bronze, com dois metros e vinte e cinco de profundidade, quatro metros e meio de diâmetro e treze metros e meio de circunferência.

[[v14-4-3]]

^<<v14-4-3,3>>^ Ao redor da borda de fora do tanque, que media treze metros e meio, havia duas carreiras de figuras de touros de bronze, que tinham sido fundidas todas em uma só peça junto com o tanque.

[[v14-4-4]]

^<<v14-4-4,4>>^ O tanque se apoiava sobre as costas de doze touros de bronze que olhavam para fora: três olhavam para o norte; três, para o oeste; três, para o sul; e três, para o leste.

[[v14-4-5]]

^<<v14-4-5,5>>^ A grossura das paredes do tanque era de quatro dedos. A sua borda era como a borda de um copo, curvando-se para fora como as pétalas de um lírio. A capacidade do tanque era de mais ou menos sessenta mil litros.

[[v14-4-6]]

^<<v14-4-6,6>>^ Fizeram também dez bacias, nas quais era lavado tudo o que se usava para os sacrifícios  dos animais. Cinco bacias foram colocadas no lado sul do Templo e cinco, no lado norte. A água do tanque era para os sacerdotes se lavarem.

[[v14-4-7]]

^<<v14-4-7,7>>^ Fizeram dez candelabros  de ouro, como havia sido ordenado. Eles foram colocados no Templo: cinco, no lado sul e cinco, no lado norte.

[[v14-4-8]]

^<<v14-4-8,8>>^ Fizeram também dez mesas, que foram postas no Templo: cinco, no lado sul e cinco, no lado norte. Fizeram também cem vasilhas de ouro.

[[v14-4-9]]

^<<v14-4-9,9>>^ Construíram o pátio interno, para os sacerdotes, e o pátio principal. As portas dos pátios foram revestidas de bronze.

[[v14-4-10]]

^<<v14-4-10,10>>^ O tanque foi colocado no canto sudeste do Templo.

[[v14-4-11]]

^<<v14-4-11,11>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo de Deus. Esta é a lista do que ele fez: duas colunas; dois remates em forma de taças, que ficavam no alto das colunas; desenhos de correntes entrelaçadas de cada remate; quatrocentas romãs de bronze, em duas carreiras ao redor do desenho de cada remate; dez carretas; dez bacias; um tanque; doze touros que sustentavam o tanque; panelas, pás e garfos. Como Salomão havia ordenado, Hurã, o mestre artesão, fez de bronze polido todas as panelas, pás e garfos para o Templo de Deus, o Senhor .

[[v14-4-12]]

^<<v14-4-12,12>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo de Deus. Esta é a lista do que ele fez:

[[v14-4-13]]

^<<v14-4-13,13>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo de Deus. Esta é a lista do que ele fez:

[[v14-4-14]]

^<<v14-4-14,14>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo de Deus. Esta é a lista do que ele fez:

[[v14-4-15]]

^<<v14-4-15,15>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo de Deus. Esta é a lista do que ele fez:

[[v14-4-16]]

^<<v14-4-16,16>>^ Hurã fez também caldeirões, pás e bacias e assim terminou todo o trabalho encomendado pelo rei Salomão para o Templo de Deus. Esta é a lista do que ele fez:

[[v14-4-17]]

^<<v14-4-17,17>>^ O rei mandou que tudo fosse feito na fundição que ficava entre Sucote e Zereda, no vale do rio Jordão.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]