include::./index.adoc[]

[[v14-14-0]]
=== 2 Crônicas, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-14-1]]

^<<v14-14-1,1>>^ O rei Abias morreu e foi sepultado na Cidade de Davi , e o seu filho Asa ficou no lugar dele como rei. Durante o reinado de Asa houve dez anos de paz na terra de Judá.

[[v14-14-2]]

^<<v14-14-2,2>>^ Asa fez o que era bom e direito e assim agradou ao Senhor , seu Deus.

[[v14-14-3]]

^<<v14-14-3,3>>^ Proibiu os sacrifícios  nos altares dos deuses estrangeiros e os cultos nos lugares pagãos de adoração, derrubou as colunas do deus Baal  e cortou os postes da deusa Aserá .

[[v14-14-4]]

^<<v14-14-4,4>>^ Ordenou ao povo de Judá que adorasse somente o Senhor , o Deus dos antepassados deles, e obedecesse às suas leis  e mandamentos.

[[v14-14-5]]

^<<v14-14-5,5>>^ Proibiu o culto nos lugares pagãos em todas as cidades de Judá e destruiu os altares de incenso. E durante o seu reinado houve paz.

[[v14-14-6]]

^<<v14-14-6,6>>^ Asa construiu muralhas e fortalezas nas cidades, e durante o seu reinado nenhum inimigo guerreou contra ele, pois o Senhor  Deus fez com que houvesse paz.

[[v14-14-7]]

^<<v14-14-7,7>>^ Asa disse ao povo de Judá: — Enquanto não há perigo de guerra, vamos construir nas cidades muralhas, fortalezas e portões com trancas. Pois temos adorado o Senhor , nosso Deus, e temos procurado obedecer ao que ele manda. É por isso que ele nos tem deixado viver em paz com todos os povos vizinhos. Portanto, tudo isso foi construído, e houve progresso.

[[v14-14-8]]

^<<v14-14-8,8>>^ O rei Asa tinha um exército de trezentos mil homens de Judá armados com escudos  e lanças e duzentos e oitenta mil homens de Benjamim armados com escudos e arcos e flechas. Todos eram soldados valentes.

[[v14-14-9]]

^<<v14-14-9,9>>^ Um etíope chamado Zera marchou contra Judá com um exército de um milhão de homens e trezentos carros de guerra e avançou até a cidade de Maressa.

[[v14-14-10]]

^<<v14-14-10,10>>^ Asa saiu para lutar contra ele, e os dois exércitos se prepararam para a batalha no vale de Zefata, perto de Maressa.

[[v14-14-11]]

^<<v14-14-11,11>>^ Aí Asa pediu socorro ao Senhor , seu Deus, dizendo: — Ó Deus, tu podes socorrer tanto os fortes como os fracos. Ajuda-nos, ó Senhor , nosso Deus, pois confiamos em ti e em teu nome estamos aqui para lutar contra este grande exército. Tu, ó Senhor , és o nosso Deus. Ninguém pode resistir ao teu poder!

[[v14-14-12]]

^<<v14-14-12,12>>^ Quando Asa e os seus soldados atacaram, Deus derrotou os etíopes, e eles fugiram,

[[v14-14-13]]

^<<v14-14-13,13>>^ sendo perseguidos por Asa e pelo seu exército até Gerar. Todos os etíopes foram mortos; não ficou nem um só com vida, pois foram derrotados por Deus, o Senhor , e pelo seu exército. Os soldados de Asa carregaram consigo tudo o que puderam.

[[v14-14-14]]

^<<v14-14-14,14>>^ Depois atacaram e invadiram as cidades que ficavam perto de Gerar, pois todos os moradores estavam com medo de Deus. E os soldados de Asa pegaram todas as riquezas que havia nessas cidades.

[[v14-14-15]]

^<<v14-14-15,15>>^ Atacaram também os acampamentos onde havia rebanhos, pegaram muitas ovelhas e camelos e depois voltaram para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]