include::./index.adoc[]

[[v14-28-0]]
=== 2 Crônicas, 28
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-28-1]]

^<<v14-28-1,1>>^ Acaz tinha vinte anos de idade quando se tornou rei de Judá. Ele governou dezesseis anos em Jerusalém. Acaz não seguiu o bom exemplo do seu antepassado, o rei Davi; pelo contrário, fez aquilo que não agrada ao Senhor , seu Deus,

[[v14-28-2]]

^<<v14-28-2,2>>^ e seguiu o exemplo dos reis de Israel. Fez imagens de metal do deus Baal

[[v14-28-3]]

^<<v14-28-3,3>>^ e queimou incenso no vale de Ben-Hinom. Chegou até a oferecer os seus próprios filhos, queimando-os como oferta aos ídolos, de acordo com o nojento costume dos povos que o Senhor  Deus havia expulsado da terra conforme os israelitas avançavam.

[[v14-28-4]]

^<<v14-28-4,4>>^ Acaz também ofereceu sacrifícios  e queimou incenso nos lugares pagãos de adoração, nos morros e debaixo de todas as árvores que dão sombra.

[[v14-28-5]]

^<<v14-28-5,5>>^ Por isso, o Senhor , o Deus de Acaz, deixou que o rei sírio o vencesse. Os sírios derrotaram o exército de Acaz e levaram muitos judeus como prisioneiros para Damasco. E Deus também deixou que Acaz sofresse uma grande derrota na guerra contra o rei de Israel.

[[v14-28-6]]

^<<v14-28-6,6>>^ Em um só dia, o rei de Israel, Peca, filho de Remalias, matou cento e vinte mil soldados valentes do exército de Acaz. Deus fez isso porque o povo de Judá havia abandonado o Senhor , o Deus dos seus antepassados.

[[v14-28-7]]

^<<v14-28-7,7>>^ Zicri, um valente soldado de Israel, matou Maaseias, filho do rei Acaz; matou também Azricã, o chefe do palácio, e Elcana, o primeiro-ministro do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ Da terra de Judá os israelitas levaram como prisioneiros muitos dos seus patrícios, isto é, duzentas mil mulheres e crianças. Pegaram também muitos objetos de valor e os levaram consigo para a cidade de Samaria.

[[v14-28-9]]

^<<v14-28-9,9>>^ Odede, um profeta  do Senhor  Deus, estava em Samaria e foi encontrar-se com o exército israelita, que estava voltando para lá. Odede disse a eles: — O Senhor , o Deus dos seus antepassados, ficou irado  com o povo de Judá e deixou que vocês o derrotassem. Mas vocês mataram aquela gente com tanta raiva, que Deus ficou sabendo disso.

[[v14-28-10]]

^<<v14-28-10,10>>^ Agora vocês estão querendo fazer com que os homens e as mulheres de Judá e de Jerusalém se tornem seus escravos. Será que vocês não sabem que vocês pecaram contra o Senhor , seu Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Portanto, ouçam o que eu estou dizendo. Levem de volta os seus patrícios, esses prisioneiros que vocês trouxeram, pois Deus está muito irado com vocês.

[[v14-28-12]]

^<<v14-28-12,12>>^ Então quatro das altas autoridades de Israel, isto é, Azarias, filho de Joanã; Berequias, filho de Mesilemote; Jeizquias, filho de Salum; e Amasa, filho de Hadlai, também ficaram contra o que o exército israelita tinha feito.

[[v14-28-13]]

^<<v14-28-13,13>>^ Eles disseram: — Não tragam esses prisioneiros para cá! Já pecamos muito contra Deus, o Senhor , e o que vocês estão querendo fazer agora nos tornaria ainda mais culpados diante de Deus. Ele já está muito irado com a gente!

[[v14-28-14]]

^<<v14-28-14,14>>^ Aí os soldados israelitas largaram os prisioneiros e as coisas que tinham trazido de Judá, entregando-os ao povo e às autoridades.

[[v14-28-15]]

^<<v14-28-15,15>>^ Os quatro homens já citados foram escolhidos para cuidar dos prisioneiros. Das coisas que tinham sido trazidas de Judá, eles pegaram roupas e sandálias e deram aos que precisavam. Depois deram de comer e de beber a todos eles e cuidaram dos seus ferimentos. Em seguida, levaram todos os prisioneiros de volta para a sua terra e os deixaram em Jericó, a cidade das palmeiras. Os que estavam muito fracos foram montados em jumentos. Então os israelitas voltaram para Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Nessa mesma época, o rei Acaz mandou pedir socorro ao rei da Assíria

[[v14-28-17]]

^<<v14-28-17,17>>^ porque mais uma vez os edomitas tinham invadido o país de Judá e haviam derrotado o exército de Acaz e levado alguns prisioneiros.

[[v14-28-18]]

^<<v14-28-18,18>>^ Ao mesmo tempo, os filisteus estavam atacando as cidades que ficavam nas planícies e no sul de Judá, conquistando Bete-Semes, Aijalom e Gederote e também as cidades de Socó, Timna e Ginzo, com os povoados que ficavam ao redor. Tendo conquistado essas cidades, os filisteus começaram a morar nelas.

[[v14-28-19]]

^<<v14-28-19,19>>^ Deus fez o país de Judá sofrer esta humilhação por causa do rei Acaz, pois ele havia levado o povo de Judá a cometer imoralidades e ele mesmo havia desobedecido a Deus, o Senhor .

[[v14-28-20]]

^<<v14-28-20,20>>^ O rei Tiglate-Pileser, da Assíria, marchou com o seu exército contra Acaz e, em vez de ajudá-lo, o deixou numa situação mais difícil ainda.

[[v14-28-21]]

^<<v14-28-21,21>>^ Acaz pegou objetos de valor do Templo, do palácio e das casas das altas autoridades e os deu ao rei da Assíria; porém isso não adiantou nada.

[[v14-28-22]]

^<<v14-28-22,22>>^ Quando as suas dificuldades aumentaram, o rei Acaz cometeu pecados piores contra Deus, o Senhor . Acaz era assim mesmo!

[[v14-28-23]]

^<<v14-28-23,23>>^ Ofereceu sacrifícios  aos deuses da Síria, mas esses mesmos deuses foram a causa da sua derrota. Ele disse: — Os deuses da Síria ajudaram os reis sírios; portanto, vou lhes oferecer sacrifícios, e eles me ajudarão também. Mas eles trouxeram desgraça para o rei e para todo o país.

[[v14-28-24]]

^<<v14-28-24,24>>^ Acaz pegou os objetos do Templo e os quebrou em pedaços. Fechou os portões do pátio do Templo e mandou construir altares em todas as esquinas de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ E mandou construir em todas as cidades de Judá lugares pagãos de adoração, onde se queimava incenso a deuses estrangeiros. Assim ele fez com que o Senhor , o Deus dos seus antepassados, ficasse muito irado .

[[v14-28-26]]

^<<v14-28-26,26>>^ Todas as outras coisas que o rei Acaz fez, desde o começo até o fim do seu reinado, estão escritas na História dos Reis de Judá e de Israel .

[[v14-28-27]]

^<<v14-28-27,27>>^ Acaz morreu e foi sepultado na cidade de Jerusalém, mas não nos túmulos dos reis; e o seu filho Ezequias ficou no lugar dele como rei.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]