include::./index.adoc[]

[[v14-10-0]]
=== 2 Crônicas, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-10-1]]

^<<v14-10-1,1>>^ Roboão foi até Siquém, onde todo o povo de Israel se havia reunido para fazê-lo rei.

[[v14-10-2]]

^<<v14-10-2,2>>^ Jeroboão, filho de Nebate, que havia fugido do rei Salomão e ido para o Egito, soube disso e voltou de lá.

[[v14-10-3]]

^<<v14-10-3,3>>^ O povo das tribos  do Norte mandou buscá-lo, e foram todos juntos falar com Roboão. Eles disseram:

[[v14-10-4]]

^<<v14-10-4,4>>^ — Salomão, o seu pai, nos tratou com dureza e nos fez carregar cargas pesadas. Se o senhor tornar essas cargas mais leves e a nossa vida mais fácil, nós seremos seus servidores.

[[v14-10-5]]

^<<v14-10-5,5>>^ Roboão respondeu: — Voltem daqui a três dias, e aí eu darei a minha resposta. Então eles foram embora.

[[v14-10-6]]

^<<v14-10-6,6>>^ O rei Roboão foi falar com os homens mais velhos, que haviam sido conselheiros do seu pai, e perguntou: — Que resposta vocês me aconselham a dar a este povo?

[[v14-10-7]]

^<<v14-10-7,7>>^ Eles disseram: — Se o senhor for bondoso, se tratá-los bem e der uma resposta favorável ao pedido deles, então eles serão seus servidores para sempre.

[[v14-10-8]]

^<<v14-10-8,8>>^ Mas Roboão não seguiu o conselho dos homens mais velhos e foi falar com os jovens que haviam crescido junto com ele e que agora eram os seus conselheiros.

[[v14-10-9]]

^<<v14-10-9,9>>^ — Que conselho vocês me dão? — perguntou ele. — O que é que eu digo a esse povo que está pedindo para que eu torne as suas cargas mais leves?

[[v14-10-10]]

^<<v14-10-10,10>>^ Eles responderam: — Você deve dizer o seguinte: "O meu dedinho é mais grosso do que a cintura do meu pai!

[[v14-10-11]]

^<<v14-10-11,11>>^ Ele fez vocês carregarem cargas pesadas; eu vou aumentar o peso ainda mais. Ele castigou vocês com chicotes; eu vou surrá-los com correias."

[[v14-10-12]]

^<<v14-10-12,12>>^ Três dias depois, Jeroboão e todo o povo foram falar de novo com o rei Roboão, como ele havia mandado.

[[v14-10-13]]

^<<v14-10-13,13>>^ O rei desprezou o conselho dos homens mais velhos e falou duramente com o povo,

[[v14-10-14]]

^<<v14-10-14,14>>^ como os jovens haviam aconselhado. Ele disse: — O meu pai fez vocês carregarem cargas pesadas; eu vou aumentar o peso ainda mais. Ele castigou vocês com chicotes; eu vou surrá-los com correias.

[[v14-10-15]]

^<<v14-10-15,15>>^ Assim o rei Roboão não atendeu o povo. O Senhor  Deus fez isso acontecer para confirmar aquilo que ele, por meio do profeta  Aías, de Siló, tinha dito a Jeroboão, filho de Nebate.

[[v14-10-16]]

^<<v14-10-16,16>>^ Quando os israelitas viram que o rei não ia atender o seu pedido, começaram a gritar: — Abaixo Davi e a sua família! O que foi que eles já fizeram por nós? Homens de Israel, vamos para casa! Que Roboão cuide de si mesmo! E assim os israelitas voltaram para as suas casas,

[[v14-10-17]]

^<<v14-10-17,17>>^ deixando Roboão como rei somente do povo que morava no território da tribo de Judá.

[[v14-10-18]]

^<<v14-10-18,18>>^ Então o rei Roboão mandou que Adonirão, o encarregado dos trabalhadores forçados, fosse falar com os israelitas, mas eles o mataram a pedradas. Porém Roboão subiu depressa no seu carro de guerra e fugiu para Jerusalém.

[[v14-10-19]]

^<<v14-10-19,19>>^ Desde aquela época até hoje , o povo de Israel, o Reino do Norte, está revoltado contra os reis descendentes de Davi.

'''

xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[&#60; Capítulo Anterior] | <<v14-10-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[Próximo Capítulo &#62;]