include::./index.adoc[]

[[v14-32-0]]
=== 2 Crônicas, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-32-1]]

^<<v14-32-1,1>>^ Depois de tudo isso e dessas provas de fidelidade que o rei Ezequias deu, Senaqueribe, rei da Assíria, invadiu o país de Judá. O seu exército cercou as cidades protegidas por muralhas, procurando conquistá-las.

[[v14-32-2]]

^<<v14-32-2,2>>^ Quando Ezequias viu que Senaqueribe estava planejando atacar Jerusalém também,

[[v14-32-3]]

^<<v14-32-3,3>>^ consultou os seus chefes militares e civis e propôs que tapassem as fontes de água que ficavam fora da cidade; e eles concordaram com o plano.

[[v14-32-4]]

^<<v14-32-4,4>>^ Muita gente se ajuntou, e foram tapar todas as fontes e também o canal que atravessava aquela região. Isso foi feito para que os assírios encontrassem pouca água quando chegassem perto da cidade.

[[v14-32-5]]

^<<v14-32-5,5>>^ Ezequias se animou e consertou a muralha da cidade, construiu torres em cima dela e levantou outra muralha ao redor da que já existia. Também construiu defesas no aterro que havia sido feito no lado leste, na Cidade de Davi ; e mandou fazer muitas lanças e escudos .

[[v14-32-6]]

^<<v14-32-6,6>>^ Colocou oficiais no comando de todos os homens da cidade, mandou os oficiais se reunirem na praça do portão de entrada da cidade e disse:

[[v14-32-7]]

^<<v14-32-7,7>>^ — Sejam fortes e corajosos! Não fiquem assustados, nem tenham medo do rei da Assíria e do seu enorme exército. Pois aquele que está do nosso lado é mais poderoso do que o que está do lado dele.

[[v14-32-8]]

^<<v14-32-8,8>>^ Ele só conta com a força dos homens, mas do nosso lado está o Senhor , nosso Deus, para nos ajudar e para guerrear por nós. E o povo ficou animado ao ouvir as palavras do rei Ezequias.

[[v14-32-9]]

^<<v14-32-9,9>>^ Algum tempo depois, Senaqueribe, rei da Assíria, junto com o seu exército estava cercando a cidade de Laquis. Ele enviou alguns oficiais a Jerusalém para entregarem ao rei Ezequias a seguinte mensagem:

[[v14-32-10]]

^<<v14-32-10,10>>^ "Eu, Senaqueribe, rei da Assíria, quero saber como é que vocês, moradores de Jerusalém, podem se sentir seguros ficando aí enquanto o exército inimigo está cercando a cidade.

[[v14-32-11]]

^<<v14-32-11,11>>^ Ezequias diz que o Senhor , o Deus de vocês, os livrará das minhas mãos; mas ele os está enganando, e vocês morrerão de fome e de sede.

[[v14-32-12]]

^<<v14-32-12,12>>^ Pois foi o próprio Ezequias que acabou com os lugares de adoração e com os altares desse Deus e disse ao povo de Judá e aos moradores de Jerusalém que adorassem a Deus diante de um altar só e queimassem incenso somente naquele altar.

[[v14-32-13]]

^<<v14-32-13,13>>^ Será que vocês não sabem o que eu e os meus antepassados fizemos com os povos de outras nações? Vocês pensam que os deuses daquelas nações foram capazes de salvá-las das minhas mãos?

[[v14-32-14]]

^<<v14-32-14,14>>^ Não houve nenhum deus das nações que os meus antepassados conquistaram que fosse capaz de salvar o seu povo do meu poder. Então por que é que vocês pensam que o seu Deus pode salvá-los das minhas mãos?

[[v14-32-15]]

^<<v14-32-15,15>>^ Portanto, não deixem que Ezequias os engane assim. Não se iludam, não acreditem nele. Nunca houve nenhum deus que pudesse salvar o seu povo do poder dos meus antepassados ou do meu poder. Muito menos o Deus de vocês poderá salvá-los!"

[[v14-32-16]]

^<<v14-32-16,16>>^ Os oficiais assírios disseram coisas ainda piores contra Deus, o Senhor , e contra o seu servo  Ezequias.

[[v14-32-17]]

^<<v14-32-17,17>>^ E Senaqueribe escreveu cartas em que insultava o Senhor , o Deus de Israel, dizendo o seguinte contra ele: "Os deuses de outras nações não salvaram os seus povos das minhas mãos; assim também o Deus de Ezequias não salvará o seu povo das minhas mãos."

[[v14-32-18]]

^<<v14-32-18,18>>^ Os oficiais gritaram isso em hebraico  aos moradores de Jerusalém que estavam em cima da muralha da cidade, a fim de assustá-los e deixá-los apavorados e assim poder conquistar a cidade.

[[v14-32-19]]

^<<v14-32-19,19>>^ Os oficiais falaram a respeito do Deus de Jerusalém como se ele fosse como os deuses de outros povos, que são ídolos feitos por mãos humanas.

[[v14-32-20]]

^<<v14-32-20,20>>^ Aí o rei Ezequias e o profeta  Isaías, filho de Amoz, oraram a Deus e pediram a sua ajuda.

[[v14-32-21]]

^<<v14-32-21,21>>^ Então o Senhor  Deus enviou um anjo que matou todos os soldados e todos os oficiais do exército assírio. O rei Senaqueribe voltou envergonhado para o seu país. Certo dia, quando estava adorando no templo do seu deus, alguns dos seus filhos o mataram à espada.

[[v14-32-22]]

^<<v14-32-22,22>>^ Foi assim que o Senhor  Deus salvou Ezequias e os moradores de Jerusalém das mãos de Senaqueribe, rei da Assíria, e das mãos de todos os outros inimigos. E Deus deu ao seu povo paz com todos os países vizinhos.

[[v14-32-23]]

^<<v14-32-23,23>>^ Muitas pessoas iam a Jerusalém levando ofertas ao Senhor  e ricos presentes para o rei Ezequias, de Judá. Daquela época em diante, a fama de Ezequias foi crescendo em todas as nações.

[[v14-32-24]]

^<<v14-32-24,24>>^ Por esse tempo, o rei Ezequias ficou doente e quase morreu. Então orou a Deus, o Senhor , e Deus respondeu, dando um sinal para provar que ele ficaria bom.

[[v14-32-25]]

^<<v14-32-25,25>>^ Deus foi bondoso com Ezequias, mas ele não lhe agradeceu, pois era orgulhoso. Por isso, Deus ficou irado  com ele, com o povo de Judá e com os moradores de Jerusalém.

[[v14-32-26]]

^<<v14-32-26,26>>^ Aí Ezequias se arrependeu do seu orgulho, como também os moradores de Jerusalém, e assim o Senhor  só castigou o povo depois da morte de Ezequias.

[[v14-32-27]]

^<<v14-32-27,27>>^ Ezequias ficou muito rico e recebeu muitas homenagens. Construiu depósitos para guardar a prata, o ouro, as pedras preciosas, as especiarias , os escudos  e os outros objetos de valor que possuía.

[[v14-32-28]]

^<<v14-32-28,28>>^ Construiu também armazéns para os cereais, o vinho e o azeite, estrebarias para o gado e currais para os carneiros.

[[v14-32-29]]

^<<v14-32-29,29>>^ Ezequias também construiu cidades. Ele se tornou dono de muito gado e de muitos carneiros, pois Deus lhe deu muitas riquezas.

[[v14-32-30]]

^<<v14-32-30,30>>^ Foi Ezequias quem mandou tapar a saída de cima da fonte de Giom e cavar no lado oeste de Jerusalém um túnel para levar água para dentro da cidade. Tudo o que Ezequias fez deu certo.

[[v14-32-31]]

^<<v14-32-31,31>>^ Quando as altas autoridades da Babilônia enviaram mensageiros a Ezequias para fazerem perguntas sobre o milagre que havia acontecido em Judá, Deus não o ajudou, pois queria pô-lo à prova a fim de descobrir o que estava no fundo do seu coração.

[[v14-32-32]]

^<<v14-32-32,32>>^ Tudo o mais que Ezequias fez, inclusive as coisas que fez como prova da sua dedicação a Deus, está escrito na Visão do Profeta Isaías, Filho de Amoz , e na História dos Reis de Judá e de Israel .

[[v14-32-33]]

^<<v14-32-33,33>>^ Ezequias morreu e foi sepultado na parte de cima dos túmulos dos reis, que eram descendentes de Davi. Quando ele morreu, o povo de Judá e os moradores de Jerusalém lhe prestaram homenagens. E o seu filho Manassés ficou no lugar dele como rei.

'''

xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[Próximo Capítulo &#62;]