include::./index.adoc[]

[[v14-30-0]]
=== 2 Crônicas, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-30-1]]

^<<v14-30-1,1>>^ Depois disso, o rei Ezequias enviou mensageiros por toda a terra de Israel e de Judá e mandou cartas para o povo das tribos  de Efraim e de Manassés, convidando todos para virem ao Templo em Jerusalém a fim de comemorar a Festa da Páscoa  em honra do Senhor , o Deus de Israel.

[[v14-30-2]]

^<<v14-30-2,2>>^ O rei, as altas autoridades e os moradores de Jerusalém tinham concordado em comemorar essa festa no segundo mês do ano

[[v14-30-3]]

^<<v14-30-3,3>>^ porque não tinham podido fazê-lo no tempo marcado, isto é, no primeiro mês. Isso porque os sacerdotes que se haviam purificado  eram poucos, e o povo não se havia reunido em Jerusalém.

[[v14-30-4]]

^<<v14-30-4,4>>^ O rei e o povo acharam bom o seu plano.

[[v14-30-5]]

^<<v14-30-5,5>>^ Resolveram espalhar a notícia pelo país inteiro, desde a cidade de Berseba, no Sul, até a tribo de Dã, no Norte, convidando todos para virem a Jerusalém a fim de tomar parte na Festa da Páscoa em honra do Senhor , o Deus de Israel. Pois já fazia muito tempo que a Páscoa não era comemorada de acordo com o que estava escrito na Lei .

[[v14-30-6]]

^<<v14-30-6,6>>^ Os mensageiros obedeceram à ordem do rei e levaram as cartas do rei e também as cartas das altas autoridades por toda a terra de Israel e de Judá. Elas diziam assim: "Povo de Israel, voltem para o Senhor , o Deus de Abraão, de Isaque e de Jacó, e assim ele voltará para vocês que escaparam do poder dos reis da Assíria.

[[v14-30-7]]

^<<v14-30-7,7>>^ Não sejam como os seus antepassados e como os seus patrícios, que foram infiéis ao Senhor , o Deus dos nossos antepassados. Foi por isso que ele os destruiu, como vocês estão vendo.

[[v14-30-8]]

^<<v14-30-8,8>>^ Não sejam teimosos como os seus antepassados, mas sejam obedientes ao Senhor . Venham ao Templo, que ele separou para a sua adoração para sempre, e adorem a Deus a fim de que ele pare de ficar irado  com vocês.

[[v14-30-9]]

^<<v14-30-9,9>>^ Se vocês voltarem para Deus, então os inimigos que levaram os seus parentes e os seus filhos como prisioneiros terão pena deles e os deixarão voltar para casa. Pois o Senhor , nosso Deus, é bondoso e misericordioso e os aceitará se vocês voltarem para ele."

[[v14-30-10]]

^<<v14-30-10,10>>^ Os mensageiros foram por todas as cidades das tribos de Efraim e de Manassés, chegando até o território da tribo de Zebulom, no Norte; mas todos riram e caçoaram deles.

[[v14-30-11]]

^<<v14-30-11,11>>^ Porém algumas pessoas das tribos de Aser, de Manassés e de Zebulom se arrependeram e foram até Jerusalém.

[[v14-30-12]]

^<<v14-30-12,12>>^ E em Judá Deus fez com que todo o povo cumprisse o que o rei e as altas autoridades tinham ordenado, obedecendo à ordem de Deus, o Senhor .

[[v14-30-13]]

^<<v14-30-13,13>>^ Portanto, no segundo mês do ano, muitas pessoas foram até Jerusalém para comemorar a Festa dos Pães sem Fermento . Era uma multidão enorme.

[[v14-30-14]]

^<<v14-30-14,14>>^ Pegaram os altares onde eram oferecidos sacrifícios  e também os altares onde era queimado incenso e os jogaram no vale do Cedrom.

[[v14-30-15]]

^<<v14-30-15,15>>^ No dia catorze do segundo mês, mataram os carneiros para a Festa da Páscoa. Os sacerdotes e os levitas  ficaram com vergonha e por isso se purificaram e levaram ao Templo sacrifícios para serem completamente queimados.

[[v14-30-16]]

^<<v14-30-16,16>>^ Foram para os seus lugares no Templo, de acordo com o que mandava a Lei de Moisés, homem de Deus. Os levitas davam o sangue dos animais aos sacerdotes, e estes borrifavam o altar.

[[v14-30-17]]

^<<v14-30-17,17>>^ Havia ali muitas pessoas que estavam impuras , e por isso os levitas precisaram matar os carneiros que essas pessoas ofereciam, a fim de dedicá-los a Deus, o Senhor .

[[v14-30-18]]

^<<v14-30-18,18>>^ Pois muitas pessoas das tribos de Efraim, de Manassés, de Issacar e de Zebulom haviam comido o jantar da Páscoa sem terem se purificado, como manda a Lei de Deus. Mas Ezequias orou em favor delas, dizendo: — Ó Deus bondoso, perdoa todos

[[v14-30-19]]

^<<v14-30-19,19>>^ os que com todo o coração te adoram a ti, o Senhor , o Deus dos nossos antepassados. Perdoa-os, ó Senhor , ainda que eles não se tenham purificado de acordo com a lei do Templo.

[[v14-30-20]]

^<<v14-30-20,20>>^ O Senhor  Deus atendeu o pedido de Ezequias e perdoou o povo.

[[v14-30-21]]

^<<v14-30-21,21>>^ Durante sete dias, todos os israelitas que estavam em Jerusalém comemoraram com grande alegria a Festa dos Pães sem Fermento. Todos os dias os sacerdotes e os levitas louvaram a Deus, tocando bem alto os instrumentos musicais sagrados.

[[v14-30-22]]

^<<v14-30-22,22>>^ Ezequias elogiou todos os levitas que haviam dirigido tão bem o culto de adoração. Durante sete dias, todos tomaram parte na Festa, apresentaram as ofertas de paz e louvaram o Senhor , o Deus dos seus antepassados.

[[v14-30-23]]

^<<v14-30-23,23>>^ Aí concordaram em festejar mais sete dias e assim fizeram com muita alegria.

[[v14-30-24]]

^<<v14-30-24,24>>^ O rei Ezequias deu ao povo mil touros novos e sete mil carneiros, e as altas autoridades deram mil touros novos e dez mil carneiros para a Festa. E muitos sacerdotes se purificaram.

[[v14-30-25]]

^<<v14-30-25,25>>^ Assim todo mundo ficou alegre — o povo de Judá, os sacerdotes, os levitas, as pessoas que tinham vindo da terra de Israel e os estrangeiros que moravam em Israel e em Judá.

[[v14-30-26]]

^<<v14-30-26,26>>^ Houve grande alegria em toda a cidade de Jerusalém, pois desde o tempo de Salomão, rei de Israel e filho de Davi, nunca havia acontecido uma coisa assim.

[[v14-30-27]]

^<<v14-30-27,27>>^ Os sacerdotes e os levitas, de pé, pediram as bênçãos de Deus para o povo. E Deus, no seu santo lar no céu, ouviu a oração e atendeu o pedido deles.

'''

xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[&#60; Capítulo Anterior] | <<v14-30-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[Próximo Capítulo &#62;]