include::./index.adoc[]

[[v14-16-0]]
=== 2 Crônicas, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-16-1]]

^<<v14-16-1,1>>^ No ano trinta e seis do reinado de Asa, Baasa, rei de Israel, invadiu Judá e começou a cercar de muralhas a cidade de Ramá, para assim controlar o movimento na estrada que ia até Jerusalém.

[[v14-16-2]]

^<<v14-16-2,2>>^ Por isso, o rei Asa pegou prata e ouro do Templo e do palácio e entregou a alguns dos seus servidores a fim de que levassem para Damasco e dessem ao rei Ben-Hadade, da Síria. Junto foi a seguinte mensagem:

[[v14-16-3]]

^<<v14-16-3,3>>^ "Vamos ser aliados como eram os nossos pais. Esta prata e este ouro são para você. Retire agora o apoio que você está dando a Baasa, rei de Israel, para que assim ele tenha de tirar os seus soldados do meu país."

[[v14-16-4]]

^<<v14-16-4,4>>^ O rei Ben-Hadade concordou com a proposta de Asa e mandou que os seus comandantes e os seus exércitos atacassem as cidades de Israel. Eles conquistaram Ijom, Dã e Abel-Maim e todas as cidades-armazém do território de Naftali.

[[v14-16-5]]

^<<v14-16-5,5>>^ Quando o rei Baasa soube do que havia acontecido, parou de construir as muralhas de Ramá.

[[v14-16-6]]

^<<v14-16-6,6>>^ Aí o rei Asa mandou chamar todo o povo de Judá, e eles levaram dali as pedras e a madeira que Baasa havia estado usando para construir as muralhas em volta de Ramá. Com esse material Asa construiu muralhas em volta de Geba e de Mispa.

[[v14-16-7]]

^<<v14-16-7,7>>^ Por esse tempo, o profeta  Hanani foi falar com o rei Asa, de Judá, e disse: — O senhor confiou no rei da Síria, em vez de confiar no Senhor , seu Deus, e por isso o exército do rei de Israel conseguiu fugir.

[[v14-16-8]]

^<<v14-16-8,8>>^ Não é verdade que os soldados da Etiópia e da Líbia formaram um enorme exército, com muitos carros de guerra e cavaleiros? No entanto, o senhor confiou em Deus, o Senhor , e ele lhe deu a vitória.

[[v14-16-9]]

^<<v14-16-9,9>>^ Deus está sempre vigiando tudo o que acontece no mundo a fim de dar forças a todos os que são fiéis a ele com todo o coração. Desta vez o senhor fez uma loucura e por isso, de agora em diante, o senhor vai estar sempre em guerra.

[[v14-16-10]]

^<<v14-16-10,10>>^ Asa ficou tão zangado com o profeta, que mandou amarrá-lo com correntes e metê-lo na prisão. E foi nesse tempo também que Asa perseguiu algumas pessoas do seu próprio povo.

[[v14-16-11]]

^<<v14-16-11,11>>^ Todas as outras coisas que o rei Asa fez, desde o princípio do seu reinado até o fim, estão escritas na História dos Reis de Judá e de Israel .

[[v14-16-12]]

^<<v14-16-12,12>>^ No ano trinta e nove do seu reinado, ele foi atacado por uma doença muito grave nos pés; mesmo assim não pediu socorro a Deus, o Senhor , mas confiou nos médicos.

[[v14-16-13]]

^<<v14-16-13,13>>^ No ano quarenta e um do seu reinado, Asa morreu

[[v14-16-14]]

^<<v14-16-14,14>>^ e foi sepultado no túmulo que ele tinha mandado cavar na Cidade de Davi . Encheram o túmulo de perfumes e de várias especiarias , que tinham sido preparados com muita arte, e colocaram o corpo ali dentro. Depois fizeram uma enorme fogueira em honra dele.

'''

xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[Próximo Capítulo &#62;]