include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-13-1]]

^<<v14-13-1,1>>^ No ano dezoito do reinado de Jeroboão em Israel, Abias se tornou rei de Judá

[[v14-13-2]]

^<<v14-13-2,2>>^ e governou três anos em Jerusalém. A sua mãe se chamava Micaía e era filha de Uriel, da cidade de Gibeá. Houve uma guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ Abias foi à batalha com um exército de quatrocentos mil soldados valentes, e Jeroboão levou para a luta oitocentos mil soldados valentes.

[[v14-13-4]]

^<<v14-13-4,4>>^ Abias subiu o monte Zemaraim, na região montanhosa de Efraim, e do alto do monte gritou para Jeroboão e os seus soldados: — Escutem!

[[v14-13-5]]

^<<v14-13-5,5>>^ Será que vocês não sabem que o Senhor , o Deus de Israel, fez uma aliança  eterna com Davi, prometendo que ele e os seus filhos sempre seriam os reis de Israel?

[[v14-13-6]]

^<<v14-13-6,6>>^ Mas Jeroboão, filho de Nebate, servidor de Salomão, filho de Davi, se revoltou contra o seu rei.

[[v14-13-7]]

^<<v14-13-7,7>>^ E uns homens maus e vadios se juntaram a Jeroboão, e eles desafiaram Roboão, filho de Salomão. Roboão era jovem e tímido e não pôde resistir.

[[v14-13-8]]

^<<v14-13-8,8>>^ Vocês são um exército enorme e têm os touros de ouro que Jeroboão fez para serem os seus deuses. Pensam que por causa disso vocês podem ir contra o poder que o Senhor  Deus deu aos descendentes do rei Davi?

[[v14-13-9]]

^<<v14-13-9,9>>^ Vocês expulsaram os sacerdotes de Deus, os descendentes de Arão, e os levitas  e escolheram os seus próprios sacerdotes, como os povos pagãos fazem. Qualquer um que aparece com um touro ou sete carneiros pode se tornar sacerdote de deuses falsos.

[[v14-13-10]]

^<<v14-13-10,10>>^ — Quanto a nós, o Senhor  é o nosso Deus, e nunca o rejeitamos. Os nossos sacerdotes são descendentes de Arão; eles servem a Deus e são ajudados pelos levitas.

[[v14-13-11]]

^<<v14-13-11,11>>^ Todos os dias, de manhã e à tarde, eles apresentam a Deus sacrifícios  que são completamente queimados, oferecem incenso cheiroso, colocam os pães sagrados na mesa pura  e à tardinha acendem as lamparinas do candelabro  de ouro. Pois nós obedecemos às leis  do Senhor , nosso Deus, mas vocês o rejeitaram.

[[v14-13-12]]

^<<v14-13-12,12>>^ Deus está conosco e vai à nossa frente, e os seus sacerdotes estão prontos para tocar as cornetas a fim de começar a batalha. Povo de Israel, não lutem contra o Senhor , o Deus dos seus antepassados! Vocês não podem vencer!

[[v14-13-13]]

^<<v14-13-13,13>>^ Mas Jeroboão tinha mandado parte do seu exército ficar atrás dos soldados de Abias; o resto ficou na frente deles.

[[v14-13-14]]

^<<v14-13-14,14>>^ Quando os soldados de Abias olharam para trás e viram que estavam cercados pelos soldados de Jeroboão, gritaram a Deus pedindo socorro. Os sacerdotes tocaram as cornetas,

[[v14-13-15]]

^<<v14-13-15,15>>^ os soldados de Abias gritaram, e Deus derrotou Jeroboão e o seu exército diante de Abias e o seu exército.

[[v14-13-16]]

^<<v14-13-16,16>>^ Os soldados de Israel fugiram dos de Judá, pois Deus lhes deu a vitória.

[[v14-13-17]]

^<<v14-13-17,17>>^ Quinhentos mil dos soldados de Israel foram mortos por Abias e os seus soldados; foi uma matança enorme.

[[v14-13-18]]

^<<v14-13-18,18>>^ Assim os soldados de Israel foram derrotados, e os de Judá venceram, pois confiaram no Senhor , o Deus dos seus antepassados.

[[v14-13-19]]

^<<v14-13-19,19>>^ Abias perseguiu Jeroboão e o resto do seu exército e conquistou as cidades de Betel, Jesana e Efrom e os povoados que ficavam perto delas.

[[v14-13-20]]

^<<v14-13-20,20>>^ Durante o reinado de Abias, Jeroboão nunca voltou a governar. Finalmente a ira  de Deus atingiu Jeroboão, e ele morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Abias foi ficando cada vez mais poderoso. Ele casou com catorze mulheres e foi pai de vinte e dois filhos e dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ O resto da história de Abias, tudo o que ele fez e disse, está escrito na História do Profeta Ido .

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]