include::./index.adoc[]

[[v14-33-0]]
=== 2 Crônicas, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-33-1]]

^<<v14-33-1,1>>^ Manassés tinha doze anos de idade quando se tornou rei de Judá. Ele governou cinquenta e cinco anos em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ Manassés pecou contra Deus, o Senhor , seguindo os costumes nojentos das nações que o Senhor  havia expulsado da terra conforme o povo de Israel avançava.

[[v14-33-3]]

^<<v14-33-3,3>>^ Ele construiu de novo os lugares pagãos de adoração que Ezequias, o seu pai, havia destruído. Construiu altares para a adoração do deus Baal , fez postes da deusa Aserá  e adorou as estrelas.

[[v14-33-4]]

^<<v14-33-4,4>>^ Construiu altares pagãos no Templo onde, conforme o Senhor  tinha dito, ele devia ser adorado para sempre.

[[v14-33-5]]

^<<v14-33-5,5>>^ Nos dois pátios do Templo, Manassés construiu altares para a adoração das estrelas.

[[v14-33-6]]

^<<v14-33-6,6>>^ Queimou os seus filhos em sacrifício  no vale de Ben-Hinom, fazia adivinhações, praticava magia e feitiçarias e consultava adivinhos e médiuns. Pecou muito contra Deus, o Senhor , e fez com que ele ficasse irado .

[[v14-33-7]]

^<<v14-33-7,7>>^ Manassés colocou uma imagem esculpida da deusa Aserá no Templo, o lugar a respeito do qual o Senhor  tinha dito a Davi e ao seu filho Salomão o seguinte: "Em todo o território das doze tribos  de Israel, escolhi este Templo, aqui em Jerusalém, para ser o lugar onde serei adorado para sempre.

[[v14-33-8]]

^<<v14-33-8,8>>^ E, se o povo de Israel obedecer a todos os meus mandamentos e fizer tudo o que manda a Lei  que Moisés deu a eles, então eu não deixarei que sejam expulsos da terra que dei aos seus antepassados."

[[v14-33-9]]

^<<v14-33-9,9>>^ Manassés levou o povo de Judá e os moradores de Jerusalém a cometerem pecados ainda piores do que aqueles cometidos pelas nações que o Senhor  Deus havia expulsado da terra conforme o seu povo ia avançando.

[[v14-33-10]]

^<<v14-33-10,10>>^ O Senhor  Deus falou com Manassés e com o seu povo, mas eles não lhe deram atenção.

[[v14-33-11]]

^<<v14-33-11,11>>^ Por isso, Deus deixou que os comandantes do exército assírio invadissem o país de Judá. Eles prenderam Manassés com ganchos, amarraram com correntes e o levaram como prisioneiro para a Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ No seu sofrimento Manassés orou com fervor ao Senhor , seu Deus; cheio de humildade, ele se arrependeu diante do Deus dos seus antepassados.

[[v14-33-13]]

^<<v14-33-13,13>>^ Deus ouviu a sua oração e atendeu o seu pedido, deixando que ele voltasse para Jerusalém e fosse rei de novo. Aí Manassés declarou que o Senhor  é Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ Depois disso, Manassés construiu uma muralha muito alta em volta da Cidade de Davi . A muralha começava no vale que ficava a oeste da fonte de Giom, continuava na direção norte até o Portão do Peixe e passava ao redor da parte da cidade chamada Ofel. Manassés também colocou chefes militares no comando de todas as cidades de Judá que eram protegidas por muralhas.

[[v14-33-15]]

^<<v14-33-15,15>>^ Ele tirou do Templo as imagens dos deuses pagãos e o ídolo que havia colocado lá, derrubou os altares que havia mandado construir no monte onde ficava o Templo e em outros lugares de Jerusalém e os jogou fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ Consertou o altar do Senhor , ofereceu nele ofertas de paz e ofertas de gratidão e ordenou ao povo de Judá que adorasse o Senhor , o Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ O povo continuou a oferecer sacrifícios  nos altares pagãos, mas os oferecia somente ao Senhor , seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ Todas as outras coisas que Manassés fez, a sua oração a Deus e as mensagens dos profetas  que falaram com ele em nome do Senhor , o Deus de Israel, tudo isso está escrito na História dos Reis de Israel .

[[v14-33-19]]

^<<v14-33-19,19>>^ A oração de Manassés, a resposta de Deus e todos os pecados que Manassés cometeu antes de se arrepender, isto é, a adoração de ídolos, os lugares pagãos de adoração que construiu, os postes da deusa Aserá  e as imagens que mandou fazer, tudo isso está escrito na História dos Profetas .

[[v14-33-20]]

^<<v14-33-20,20>>^ Manassés morreu e foi sepultado no jardim do palácio, e o seu filho Amom ficou no lugar dele como rei.

[[v14-33-21]]

^<<v14-33-21,21>>^ Amom tinha vinte e dois anos de idade quando se tornou rei de Judá. Ele governou dois anos em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ Como Manassés, o seu pai, Amom pecou contra Deus, o Senhor . Ofereceu sacrifícios  a todos os ídolos que o seu pai havia feito e os adorou.

[[v14-33-23]]

^<<v14-33-23,23>>^ Mas ele não se arrependeu, como o seu pai. Pelo contrário, Amom continuou pecando cada vez mais.

[[v14-33-24]]

^<<v14-33-24,24>>^ Os oficiais de Amom fizeram uma revolta contra ele e o mataram no palácio.

[[v14-33-25]]

^<<v14-33-25,25>>^ Porém o povo de Judá matou todos os que haviam feito a revolta contra Amom e pôs o seu filho Josias no lugar dele como rei.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]