include::./index.adoc[]

[[v14-17-0]]
=== 2 Crônicas, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v14-17-1]]

^<<v14-17-1,1>>^ Josafá ficou no lugar de Asa, o seu pai, como rei de Judá e se preparou para se defender do Reino de Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ Colocou soldados em todas as cidades de Judá que eram protegidas por muralhas e também pôs acampamentos militares em todo o território de Judá e nas cidades de Efraim que Asa, o seu pai, havia conquistado.

[[v14-17-3]]

^<<v14-17-3,3>>^ O Senhor  Deus abençoou Josafá porque ele agiu como o seu pai tinha agido no princípio do seu reinado. Ele não adorou o deus Baal ,

[[v14-17-4]]

^<<v14-17-4,4>>^ mas adorou o Deus do seu pai e obedeceu aos seus mandamentos, em vez de seguir o mau exemplo dos reis de Israel.

[[v14-17-5]]

^<<v14-17-5,5>>^ O Senhor  firmou o poder de Josafá como rei, e todos em Judá lhe davam presentes. Assim Josafá ficou muito rico e famoso.

[[v14-17-6]]

^<<v14-17-6,6>>^ Continuou cada vez mais decidido a obedecer às leis  de Deus e acabou com os lugares pagãos de adoração e os postes da deusa Aserá  que havia no país de Judá.

[[v14-17-7]]

^<<v14-17-7,7>>^ No terceiro ano do seu reinado, Josafá enviou as seguintes autoridades para ensinarem a Lei de Deus nas cidades de Judá: Ben-Hail, Obadias, Zacarias, Netanel e Micaías.

[[v14-17-8]]

^<<v14-17-8,8>>^ Junto com eles foram os seguintes levitas : Semaías, Netanias, Zebadias, Asael, Semiramote, Jônatas, Adonias, Tobias e Tobe-Adonias. Os sacerdotes Elisama e Jeorão também foram.

[[v14-17-9]]

^<<v14-17-9,9>>^ Levaram consigo o Livro da Lei  de Deus, o Senhor , e foram por todas as cidades de Judá, ensinando a Lei a todo o povo.

[[v14-17-10]]

^<<v14-17-10,10>>^ O Senhor  Deus fez com que todos os povos vizinhos de Judá ficassem com medo de Josafá, e por isso eles não fizeram guerra contra ele.

[[v14-17-11]]

^<<v14-17-11,11>>^ Alguns filisteus trouxeram presentes e prata para Josafá, como imposto, e alguns árabes trouxeram sete mil e setecentas ovelhas e sete mil e setecentos bodes.

[[v14-17-12]]

^<<v14-17-12,12>>^ Josafá foi ficando cada vez mais forte e construiu fortalezas e cidades-armazém,

[[v14-17-13]]

^<<v14-17-13,13>>^ onde ajuntou grande quantidade de mantimentos. Em Jerusalém ele colocou oficiais valentes e experimentados.

[[v14-17-14]]

^<<v14-17-14,14>>^ Esta é a lista desses oficiais, de acordo com os grupos de famílias que eles comandavam: Adna era o comandante das tropas das famílias de Judá e comandava trezentos mil soldados.

[[v14-17-15]]

^<<v14-17-15,15>>^ Em seguida, vinha Joanã, que comandava duzentos e oitenta mil homens;

[[v14-17-16]]

^<<v14-17-16,16>>^ e depois vinha Amasias, filho de Zicri, que comandava duzentos mil homens. Amasias tinha se apresentado de livre e espontânea vontade para servir a Deus, o Senhor .

[[v14-17-17]]

^<<v14-17-17,17>>^ O comandante dos soldados das famílias de Benjamim era Eliada, um oficial valente; ele comandava duzentos mil homens armados de escudos  e arcos e flechas.

[[v14-17-18]]

^<<v14-17-18,18>>^ Finalmente vinha Jozabade, que comandava cento e oitenta mil homens armados.

[[v14-17-19]]

^<<v14-17-19,19>>^ Todos estes estavam ao serviço de Josafá em Jerusalém; além destes, ele havia colocado outros soldados em todas as cidades de Judá que eram protegidas por muralhas.

'''

xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[Próximo Capítulo &#62;]