include::./index.adoc[]

[[v2-29-0]]
=== Êxodo, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-29-1]]

^<<v2-29-1,1>>^ O Senhor  disse a Moisés: — A fim de separar Arão e os seus filhos como sacerdotes para o meu serviço, faça o seguinte: pegue um touro novo e dois carneiros sem defeito.

[[v2-29-2]]

^<<v2-29-2,2>>^ Pegue farinha de trigo e faça alguns pães  com azeite e outros sem azeite, todos sem fermento. Faça também alguns pães achatados e passe azeite em cima.

[[v2-29-3]]

^<<v2-29-3,3>>^ Ponha tudo isso numa cesta e ofereça a mim quando você fizer o sacrifício  do touro novo e dos dois carneiros.

[[v2-29-4]]

^<<v2-29-4,4>>^ — Traga Arão e os filhos dele para a entrada da Tenda da Minha Presença  e mande que eles se lavem.

[[v2-29-5]]

^<<v2-29-5,5>>^ Depois vista Arão com as suas roupas de sacerdote, isto é, a túnica , o manto sacerdotal , a sobrepeliz , o peitoral  e o cinto que passa pela cintura do manto.

[[v2-29-6]]

^<<v2-29-6,6>>^ Ponha nele a mitra  e amarre nela a placa sagrada em que estão gravadas as palavras "Separado para o Senhor ".

[[v2-29-7]]

^<<v2-29-7,7>>^ Em seguida ponha na cabeça dele o azeite de ungir.

[[v2-29-8]]

^<<v2-29-8,8>>^ — Traga os filhos de Arão e vista túnicas neles.

[[v2-29-9]]

^<<v2-29-9,9>>^ Ponha faixas em volta da sua cintura e mitra na sua cabeça. É assim que você consagrará Arão e os seus filhos. Ele e os seus descendentes deverão me servir para sempre como sacerdotes.

[[v2-29-10]]

^<<v2-29-10,10>>^ — Traga também o touro novo para a frente da Tenda da Minha Presença, e Arão e os seus filhos porão as mãos na cabeça dele.

[[v2-29-11]]

^<<v2-29-11,11>>^ Mate o touro ali na minha presença, na entrada da Tenda.

[[v2-29-12]]

^<<v2-29-12,12>>^ Depois pegue o sangue do touro e, com o dedo, ponha sobre as pontas do altar e derrame o resto na base do altar.

[[v2-29-13]]

^<<v2-29-13,13>>^ Em seguida queime no altar, como oferta para mim, as seguintes partes do animal: toda a gordura que cobre os miúdos, a melhor parte do fígado, os dois rins e a gordura que os cobre.

[[v2-29-14]]

^<<v2-29-14,14>>^ Mas queime fora do acampamento a carne do animal, o couro e as tripas. Essa é uma oferta para tirar os pecados dos sacerdotes.

[[v2-29-15]]

^<<v2-29-15,15>>^ — Depois pegue um dos carneiros, e Arão e os seus filhos porão as mãos na cabeça dele.

[[v2-29-16]]

^<<v2-29-16,16>>^ Mate o carneiro, pegue o sangue e com ele borrife os quatro lados do altar.

[[v2-29-17]]

^<<v2-29-17,17>>^ Corte o carneiro em pedaços, lave os miúdos e as pernas traseiras e ponha em cima da cabeça e dos outros pedaços.

[[v2-29-18]]

^<<v2-29-18,18>>^ Queime o carneiro inteiro em cima do altar como uma oferta de alimento. O cheiro dessa oferta me agrada.

[[v2-29-19]]

^<<v2-29-19,19>>^ — Depois pegue o outro carneiro, e Arão e os seus filhos porão as mãos na cabeça dele.

[[v2-29-20]]

^<<v2-29-20,20>>^ Mate esse carneiro e ponha uma parte do sangue dele na ponta da orelha direita de Arão e na ponta da orelha direita dos seus filhos. Também ponha o sangue sobre o dedo polegar da mão direita deles e sobre o dedão do pé direito; e com o resto do sangue borrife os quatro lados do altar.

[[v2-29-21]]

^<<v2-29-21,21>>^ Pegue um pouco do sangue que está no altar e o azeite de ungir e com eles borrife Arão, e as suas roupas, e os seus filhos, e as roupas deles. Então ele, os seus filhos e as roupas de todos eles estarão separados para mim.

[[v2-29-22]]

^<<v2-29-22,22>>^ Esse carneiro é oferecido para a ordenação  dos sacerdotes. Retire a gordura desse carneiro, o rabo, a gordura que cobre os miúdos, a melhor parte do fígado, os dois rins com a gordura que os cobre e a coxa direita.

[[v2-29-23]]

^<<v2-29-23,23>>^ — Da cesta de pães sem fermento que foram oferecidos a mim, pegue um pão de cada tipo: um pão feito com azeite, outro pão sem azeite e um pão achatado.

[[v2-29-24]]

^<<v2-29-24,24>>^ Ponha esses pães nas mãos de Arão e dos filhos dele e faça com que eles os separem para mim como oferta especial.

[[v2-29-25]]

^<<v2-29-25,25>>^ Depois pegue os pães das suas mãos e queime em cima do altar, como alimento oferecido a mim. O cheiro dessa oferta me agrada.

[[v2-29-26]]

^<<v2-29-26,26>>^ Pegue o peito do carneiro e o separe para mim como oferta especial. Essa parte do animal ficará para você.

[[v2-29-27]]

^<<v2-29-27,27>>^ — Na cerimônia de ordenação de um sacerdote, o peito e a coxa do carneiro deverão ser separados para mim como oferta especial e deverão ser dados para os sacerdotes.

[[v2-29-28]]

^<<v2-29-28,28>>^ As ofertas de paz dos israelitas serão feitas assim, para sempre. O peito e a coxa do animal pertencem aos sacerdotes. Essa é a oferta do povo para mim, o Senhor .

[[v2-29-29]]

^<<v2-29-29,29>>^ — Depois da morte do sacerdote Arão, as suas roupas passarão para os seus filhos, e eles as usarão quando forem ordenados.

[[v2-29-30]]

^<<v2-29-30,30>>^ O filho de Arão que ficar no lugar dele como sacerdote e que entrar na Tenda da Minha Presença para servir no Lugar Santo  deverá usar essas roupas sete dias.

[[v2-29-31]]

^<<v2-29-31,31>>^ — A carne do carneiro usado na ordenação de Arão e dos seus filhos deverá ser cozida num lugar sagrado.

[[v2-29-32]]

^<<v2-29-32,32>>^ Na entrada da Tenda da Minha Presença eles deverão comer essa carne com o pão que ficar na cesta.

[[v2-29-33]]

^<<v2-29-33,33>>^ Quando eles forem ordenados, comerão o que foi oferecido como sacrifício para tirar os seus pecados. Somente os sacerdotes poderão comer esse alimento, pois ele é sagrado.

[[v2-29-34]]

^<<v2-29-34,34>>^ Por isso a carne ou o pão que não forem comidos naquele mesmo dia deverão ser queimados. Não deverão ser comidos, pois são sagrados.

[[v2-29-35]]

^<<v2-29-35,35>>^ — Conforme eu mandei, faça durante sete dias as cerimônias para ordenar Arão e os seus filhos.

[[v2-29-36]]

^<<v2-29-36,36>>^ Cada dia ofereça um touro novo como sacrifício para conseguir o perdão dos pecados de todos. Com um sacrifício para tirar pecados você purificará  o altar e depois o ungirá a fim de torná-lo santo.

[[v2-29-37]]

^<<v2-29-37,37>>^ Faça isso todos os dias, durante sete dias. Então o altar ficará completamente santo, e qualquer pessoa ou coisa que tocar nele sofrerá por causa do poder da sua santidade.

[[v2-29-38]]

^<<v2-29-38,38>>^ — Todos os dias, e para sempre, sacrifique dois carneirinhos de um ano.

[[v2-29-39]]

^<<v2-29-39,39>>^ Sacrifique um deles de manhã e o outro à tarde.

[[v2-29-40]]

^<<v2-29-40,40>>^ Junto com o primeiro carneirinho ofereça um quilo de farinha de trigo misturada com um litro de azeite. E, como oferta, derrame um litro de vinho.

[[v2-29-41]]

^<<v2-29-41,41>>^ À tarde ofereça outro carneirinho e junto com ele a mesma quantidade de farinha, azeite e vinho, como de manhã. Essa é uma oferta de alimento trazida para mim, o Senhor , e o seu cheiro me agrada.

[[v2-29-42]]

^<<v2-29-42,42>>^ E essa oferta a ser queimada deve ser oferecida para sempre na minha presença, na entrada da Tenda da Minha Presença . Ali eu me encontrarei com o meu povo e falarei com você.

[[v2-29-43]]

^<<v2-29-43,43>>^ Ali me encontrarei com o povo de Israel, e a minha glória  fará com que esse lugar fique santo.

[[v2-29-44]]

^<<v2-29-44,44>>^ Eu farei com que a Tenda e o altar fiquem santos e separarei Arão e os seus filhos para me servirem como sacerdotes.

[[v2-29-45]]

^<<v2-29-45,45>>^ Morarei no meio do povo de Israel e serei o Deus deles.

[[v2-29-46]]

^<<v2-29-46,46>>^ Eles ficarão sabendo que eu, o Senhor , sou o Deus que os tirou do Egito para morar entre eles. Eu sou o Senhor , o Deus deles.

'''

xref:002-exodo/002-exodo-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodo/002-exodo-030.adoc#v2-30-0[Próximo Capítulo &#62;]