include::./index.adoc[]

[[v2-39-0]]
=== Êxodo, 39
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-39-1]]

^<<v2-39-1,1>>^ Com fios de lã azul, púrpura  e vermelha foram feitas as roupas sagradas que os sacerdotes deveriam usar quando servissem no Lugar Santo . As roupas de sacerdote para Arão foram feitas como o Senhor  havia ordenado a Moisés.

[[v2-39-2]]

^<<v2-39-2,2>>^ Fizeram o manto sacerdotal  de fios de lã azul, púrpura  e vermelha, de linho fino e de fios de ouro.

[[v2-39-3]]

^<<v2-39-3,3>>^ Fizeram lâminas finas de ouro batido, que foram cortadas em fios para serem tecidos com o linho fino e com os fios de lã azul, púrpura e vermelha.

[[v2-39-4]]

^<<v2-39-4,4>>^ Fizeram duas alças para o manto, as quais foram presas nos seus dois lados.

[[v2-39-5]]

^<<v2-39-5,5>>^ O cinto, que passava pela cintura do manto, formava uma só peça com ele e era feito dos mesmos materiais, como o Senhor  havia ordenado a Moisés.

[[v2-39-6]]

^<<v2-39-6,6>>^ As pedras de ágata  foram preparadas e montadas em engastes de ouro. E, com muita habilidade, gravaram nas pedras os nomes dos filhos de Jacó.

[[v2-39-7]]

^<<v2-39-7,7>>^ Colocaram essas pedras nas alças do manto sacerdotal para representarem as doze tribos  do povo de Israel, como o Senhor  havia ordenado a Moisés.

[[v2-39-8]]

^<<v2-39-8,8>>^ O peitoral  foi feito como o manto sacerdotal . Eles o fizeram de fios de lã azul, púrpura  e vermelha e de linho fino enfeitado com bordados.

[[v2-39-9]]

^<<v2-39-9,9>>^ O peitoral era quadrado e dobrado em dois. Media um palmo de comprimento por um palmo de largura.

[[v2-39-10]]

^<<v2-39-10,10>>^ Nele foram colocadas quatro carreiras de pedras preciosas. Na primeira puseram um rubi, um topázio  e uma granada ;

[[v2-39-11]]

^<<v2-39-11,11>>^ na segunda carreira puseram uma esmeralda, uma safira  e um diamante;

[[v2-39-12]]

^<<v2-39-12,12>>^ na terceira puseram uma turquesa, uma ágata  e uma ametista ;

[[v2-39-13]]

^<<v2-39-13,13>>^ e na quarta, um berilo , um ônix e um jaspe . Essas pedras foram montadas em engastes de ouro.

[[v2-39-14]]

^<<v2-39-14,14>>^ Em cada uma dessas pedras estava gravado o nome de um dos filhos de Jacó, para representar as doze tribos  de Israel.

[[v2-39-15]]

^<<v2-39-15,15>>^ Com fios de ouro puro trançados fizeram cordões para o peitoral.

[[v2-39-16]]

^<<v2-39-16,16>>^ Fizeram também duas argolas de ouro e as prenderam nas pontas da parte de cima do peitoral.

[[v2-39-17]]

^<<v2-39-17,17>>^ Passaram os dois cordões de ouro nas duas argolas

[[v2-39-18]]

^<<v2-39-18,18>>^ e prenderam as duas pontas dos cordões nos dois engastes de ouro do peitoral, que foram presos nas duas alças do manto, na parte da frente.

[[v2-39-19]]

^<<v2-39-19,19>>^ Fizeram outras duas argolas de ouro e as prenderam nas duas pontas de baixo do peitoral, na borda do lado de dentro do manto.

[[v2-39-20]]

^<<v2-39-20,20>>^ Fizeram mais duas argolas de ouro e as prenderam nas pontas das duas alças do manto, embaixo, na frente dele, perto da costura e acima do cinto.

[[v2-39-21]]

^<<v2-39-21,21>>^ Como o Senhor  havia ordenado a Moisés, com um cordão azul eles prenderam as argolas do peitoral nas argolas do manto para que o peitoral ficasse preso acima do cinto e não se soltasse.

[[v2-39-22]]

^<<v2-39-22,22>>^ A sobrepeliz, roupa que vai por cima do manto sacerdotal , era tecida inteiramente de fios de lã azul.

[[v2-39-23]]

^<<v2-39-23,23>>^ No meio dela havia uma abertura para a cabeça. Essa abertura era rematada com uma tira de malha para que não se rasgasse.

[[v2-39-24]]

^<<v2-39-24,24>>^ Em volta de toda a barra da sobrepeliz colocaram aplicações em forma de romãs, feitas de linho fino e de fios de lã azul, púrpura  e vermelha.

[[v2-39-25]]

^<<v2-39-25,25>>^ Fizeram também sininhos de ouro puro e os puseram entre uma romã e outra.

[[v2-39-26]]

^<<v2-39-26,26>>^ Desse modo a barra da sobrepeliz ficou enfeitada com uma carreira de sininhos intercalados com romãs, da seguinte maneira: um sininho, uma romã, outro sininho, outra romã, conforme o Senhor  havia ordenado a Moisés.

[[v2-39-27]]

^<<v2-39-27,27>>^ Fizeram túnicas  de linho para Arão e os seus filhos,

[[v2-39-28]]

^<<v2-39-28,28>>^ e a mitra , os chapéus, os calções de linho

[[v2-39-29]]

^<<v2-39-29,29>>^ e o cinto tecido de linho fino e de fios de lã azul, púrpura e vermelha, enfeitado com bordados, conforme o Senhor  havia ordenado a Moisés.

[[v2-39-30]]

^<<v2-39-30,30>>^ Fizeram ainda de ouro puro uma placa para a coroa sagrada e nela gravaram a seguinte frase: "Separado para o Senhor ."

[[v2-39-31]]

^<<v2-39-31,31>>^ E amarraram a placa com um cordão de lã azul, para prendê-la na parte de cima da mitra, como o Senhor  havia ordenado a Moisés.

[[v2-39-32]]

^<<v2-39-32,32>>^ Todo o trabalho da Tenda da Presença de Deus  foi acabado. Os israelitas fizeram tudo como o Senhor  havia ordenado a Moisés.

[[v2-39-33]]

^<<v2-39-33,33>>^ Eles levaram a Moisés a Tenda e todo o seu equipamento, os prendedores, as armações, as travessas, os postes e as bases.

[[v2-39-34]]

^<<v2-39-34,34>>^ Levaram a cobertura de peles de carneiro tingidas de vermelho, a cobertura de peles finas, a cortina que separava o Lugar Santíssimo  do Lugar Santo ,

[[v2-39-35]]

^<<v2-39-35,35>>^ a arca da aliança  com as placas de pedra, os cabos e a tampa da arca.

[[v2-39-36]]

^<<v2-39-36,36>>^ Levaram a mesa e todo o seu equipamento; os pães oferecidos a Deus;

[[v2-39-37]]

^<<v2-39-37,37>>^ o candelabro  de ouro puro, as suas lamparinas, todo o seu equipamento e o azeite para as lamparinas.

[[v2-39-38]]

^<<v2-39-38,38>>^ Levaram o altar de ouro, o azeite de ungir , o incenso cheiroso, a cortina da entrada da Tenda,

[[v2-39-39]]

^<<v2-39-39,39>>^ o altar de bronze com a sua grelha, os seus cabos e todo o seu equipamento; e a pia com o seu suporte.

[[v2-39-40]]

^<<v2-39-40,40>>^ Levaram as cortinas do pátio, os seus postes e as suas bases; a cortina da entrada do pátio e as suas cordas; as estacas da Tenda e todo o equipamento para ser usado nela.

[[v2-39-41]]

^<<v2-39-41,41>>^ Levaram as roupas vistosas para os sacerdotes usarem no Lugar Santo, isto é, as roupas sagradas do sacerdote Arão e dos seus filhos.

[[v2-39-42]]

^<<v2-39-42,42>>^ Os israelitas fizeram todo o trabalho como o Senhor  havia ordenado a Moisés.

[[v2-39-43]]

^<<v2-39-43,43>>^ Moisés examinou cada coisa e viu que eles tinham feito tudo de acordo com o que o Senhor  havia ordenado. Então Moisés os abençoou.

'''

xref:002-exodo/002-exodo-038.adoc#v2-38-0[&#60; Capítulo Anterior] | <<v2-39-0,Topo>> | xref:002-exodo/002-exodo-040.adoc#v2-40-0[Próximo Capítulo &#62;]