include::./index.adoc[]

[[v2-4-0]]
=== Êxodo, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-4-1]]

^<<v2-4-1,1>>^ Aí Moisés respondeu a Deus, o Senhor : — Mas os israelitas não vão acreditar em mim, nem vão dar atenção ao que eu falar e vão dizer que o Senhor  não me apareceu.

[[v2-4-2]]

^<<v2-4-2,2>>^ Então o Senhor  perguntou: — O que é isso que você tem na mão? — Um bastão — respondeu Moisés.

[[v2-4-3]]

^<<v2-4-3,3>>^ Deus disse: — Jogue-o no chão. Ele jogou, e o bastão virou uma cobra. E Moisés fugiu dela.

[[v2-4-4]]

^<<v2-4-4,4>>^ Aí o Senhor  ordenou a Moisés: — Estenda a mão e pegue a cobra pelo rabo. Moisés estendeu a mão e pegou a cobra pelo rabo, e de novo ela virou um bastão na mão dele.

[[v2-4-5]]

^<<v2-4-5,5>>^ Então o Senhor  disse: — Faça isso para provar aos israelitas que o Senhor , o Deus dos seus antepassados, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó, apareceu a você.

[[v2-4-6]]

^<<v2-4-6,6>>^ E o Senhor  continuou: — Agora ponha a mão no peito. Moisés obedeceu. E, quando tirou a mão do peito, ela estava leprosa, branca como a neve.

[[v2-4-7]]

^<<v2-4-7,7>>^ — Ponha outra vez a mão no peito — ordenou Deus, o Senhor . Ele pôs a mão no peito novamente. E, quando a tirou, ela estava tão boa como o resto do corpo.

[[v2-4-8]]

^<<v2-4-8,8>>^ Então o Senhor  lhe disse: — Se com o primeiro milagre os israelitas não acreditarem em você e não se convencerem, então com o segundo vão acreditar.

[[v2-4-9]]

^<<v2-4-9,9>>^ Mas, se com esses dois milagres ainda não crerem e não quiserem ouvir o que você disser, tire água do rio Nilo e derrame no chão, que ela virará sangue.

[[v2-4-10]]

^<<v2-4-10,10>>^ Moisés respondeu ao Senhor : — Ó Senhor, eu nunca tive facilidade para falar, nem antes nem agora, depois que começaste a falar comigo. Quando começo a falar, eu sempre me atrapalho.

[[v2-4-11]]

^<<v2-4-11,11>>^ Porém o Senhor  lhe disse: — Quem dá a boca ao ser humano? Quem faz com que ele seja surdo ou mudo? Quem lhe dá a vista ou faz com que fique cego? Sou eu, Deus, o Senhor .

[[v2-4-12]]

^<<v2-4-12,12>>^ Agora vá, pois eu o ajudarei a falar e lhe direi o que deve dizer.

[[v2-4-13]]

^<<v2-4-13,13>>^ Aí Moisés pediu: — Não, Senhor. Por favor, manda outra pessoa.

[[v2-4-14]]

^<<v2-4-14,14>>^ Então o Senhor  ficou irritado com Moisés e disse: — Por acaso Arão, o levita , não é seu irmão? Eu sei que ele tem facilidade para falar. Além disso, ele está vindo para se encontrar com você e vai ficar contente ao vê-lo.

[[v2-4-15]]

^<<v2-4-15,15>>^ Você falará com Arão e lhe dirá o que ele deve dizer. Eu os ajudarei a falar e direi o que vocês devem fazer.

[[v2-4-16]]

^<<v2-4-16,16>>^ Arão falará ao povo em seu lugar. Ele será o seu representante e falará ao povo por você. E você será como Deus para ele, explicando o que ele deve dizer.

[[v2-4-17]]

^<<v2-4-17,17>>^ Leve este bastão porque é com ele que você vai fazer os milagres.

[[v2-4-18]]

^<<v2-4-18,18>>^ Então Moisés voltou para a casa de Jetro , o seu sogro, e disse: — Deixe que eu volte para visitar os meus parentes no Egito. Quero ver se eles ainda vivem. — Vá em paz — respondeu Jetro.

[[v2-4-19]]

^<<v2-4-19,19>>^ Quando Moisés ainda estava na região de Midiã, o Senhor  Deus lhe tinha dito: — Volte para o Egito, pois todos os que queriam matá-lo já morreram.

[[v2-4-20]]

^<<v2-4-20,20>>^ Então Moisés fez com que a sua mulher e os seus filhos montassem um jumento e começou com eles a sua viagem de volta para o Egito. Moisés tinha na mão o bastão que Deus havia mandado que ele levasse.

[[v2-4-21]]

^<<v2-4-21,21>>^ E mais uma vez o Senhor  disse a Moisés: — Eu lhe dei poder para fazer muitos milagres. Quando você voltar para o Egito, esteja pronto para fazê-los diante do rei daquela terra. Mas eu vou fazer com que ele fique teimoso e não deixe o povo de Israel sair de lá.

[[v2-4-22]]

^<<v2-4-22,22>>^ Então você lhe dirá que eu, o Senhor , digo o seguinte: "Israel é o meu primeiro filho.

[[v2-4-23]]

^<<v2-4-23,23>>^ Já lhe disse que deixe o meu filho sair a fim de me adorar. Mas você não deixou, e por isso eu vou matar o seu filho mais velho."

[[v2-4-24]]

^<<v2-4-24,24>>^ Durante a viagem para o Egito, num lugar onde Moisés e a sua família estavam passando a noite, o Senhor  se encontrou com Moisés e procurou matá-lo.

[[v2-4-25]]

^<<v2-4-25,25>>^ Aí Zípora, a sua mulher, pegou uma pedra afiada, cortou o prepúcio  do seu filho e com ele tocou o pé de Moisés. E disse: — Você é um marido de sangue para mim.

[[v2-4-26]]

^<<v2-4-26,26>>^ Ela disse isso por causa da circuncisão . E assim o Senhor  deixou Moisés viver.

[[v2-4-27]]

^<<v2-4-27,27>>^ Nesse meio tempo o Senhor  disse a Arão: — Vá se encontrar com Moisés no deserto. Ele foi, e se encontrou com Moisés no monte sagrado , e o beijou.

[[v2-4-28]]

^<<v2-4-28,28>>^ Moisés contou a Arão tudo o que o Senhor  tinha dito quando havia mandado que ele voltasse para o Egito e falou também dos milagres que Deus tinha ordenado que ele fizesse.

[[v2-4-29]]

^<<v2-4-29,29>>^ Aí Moisés e Arão foram para o Egito e reuniram todos os líderes do povo de Israel.

[[v2-4-30]]

^<<v2-4-30,30>>^ Arão contou-lhes tudo o que o Senhor  Deus tinha dito a Moisés, e em seguida Moisés fez os milagres diante do povo.

[[v2-4-31]]

^<<v2-4-31,31>>^ Todos acreditaram e, quando souberam que o Senhor  tinha vindo até eles e tinha visto como estavam sendo maltratados, eles se curvaram e adoraram a Deus.

'''

xref:002-exodo/002-exodo-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodo/002-exodo-005.adoc#v2-5-0[Próximo Capítulo &#62;]