include::./index.adoc[]

[[v2-31-0]]
=== Êxodo, 31
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-31-1]]

^<<v2-31-1,1>>^ O Senhor  Deus disse a Moisés:

[[v2-31-2]]

^<<v2-31-2,2>>^ — Eu escolhi Bezalel, filho de Uri e neto de Hur, da tribo  de Judá,

[[v2-31-3]]

^<<v2-31-3,3>>^ e o enchi com o meu Espírito. Eu lhe dei inteligência, competência e habilidade para fazer todo tipo de trabalho artístico;

[[v2-31-4]]

^<<v2-31-4,4>>^ para fazer desenhos e trabalhar em ouro, prata e bronze;

[[v2-31-5]]

^<<v2-31-5,5>>^ para lapidar e montar pedras preciosas; para entalhar madeira; e para fazer todo tipo de artesanato.

[[v2-31-6]]

^<<v2-31-6,6>>^ Escolhi Aoliabe, filho de Aisamaque, da tribo de Dã, para trabalhar com ele. Dei também capacidade a todos os homens habilidosos para fazerem todas as seguintes coisas que eu mandei:

[[v2-31-7]]

^<<v2-31-7,7>>^ a Tenda da Minha Presença , a arca da aliança  e a sua tampa, todos os objetos da Tenda,

[[v2-31-8]]

^<<v2-31-8,8>>^ a mesa com as suas vasilhas, o candelabro  de ouro puro com todo o seu equipamento, o altar de queimar incenso,

[[v2-31-9]]

^<<v2-31-9,9>>^ o altar de queimar as ofertas, junto com todo o seu equipamento, a pia com o seu suporte,

[[v2-31-10]]

^<<v2-31-10,10>>^ as roupas de tecido fino, as roupas sagradas que os sacerdotes Arão e os seus filhos usarão quando servirem como sacerdotes,

[[v2-31-11]]

^<<v2-31-11,11>>^ o azeite de ungir  e o incenso cheiroso para o Lugar Santo . Todas essas coisas deverão ser feitas exatamente como eu ordenei.

[[v2-31-12]]

^<<v2-31-12,12>>^ O Senhor  Deus mandou que Moisés

[[v2-31-13]]

^<<v2-31-13,13>>^ dissesse ao povo de Israel o seguinte: — Guardem o sábado, o meu dia de descanso, pois é um sinal de união entre mim e vocês para sempre, a fim de mostrar que eu, o Senhor , os separei para serem o meu próprio povo.

[[v2-31-14]]

^<<v2-31-14,14>>^ Portanto, guardem o dia de descanso porque ele é sagrado para vocês. Quem não o guardar, mas trabalhar nesse dia, deverá ser morto.

[[v2-31-15]]

^<<v2-31-15,15>>^ Vocês têm seis dias para trabalhar, porém o sétimo dia é o dia solene de descanso, separado para mim. Quem fizer qualquer serviço nesse dia deverá ser morto.

[[v2-31-16]]

^<<v2-31-16,16>>^ O povo de Israel deverá guardar esse dia como um sinal da aliança .

[[v2-31-17]]

^<<v2-31-17,17>>^ É um sinal de união para sempre entre mim e o povo de Israel porque eu, o Senhor , fiz o céu e a terra em seis dias e no sétimo dia parei de trabalhar e descansei.

[[v2-31-18]]

^<<v2-31-18,18>>^ Quando Deus acabou de falar com Moisés no monte Sinai, entregou a ele as duas placas de pedra onde o próprio Deus havia escrito os mandamentos.

'''

xref:002-exodo/002-exodo-030.adoc#v2-30-0[&#60; Capítulo Anterior] | <<v2-31-0,Topo>> | xref:002-exodo/002-exodo-032.adoc#v2-32-0[Próximo Capítulo &#62;]