include::./index.adoc[]

[[v2-1-0]]
=== Êxodo, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-1-1]]

^<<v2-1-1,1>>^ São estes os nomes dos filhos de Jacó que foram com ele para o Egito, cada um com a sua família:

[[v2-1-2]]

^<<v2-1-2,2>>^ Rúben, Simeão, Levi, Judá,

[[v2-1-3]]

^<<v2-1-3,3>>^ Issacar, Zebulom, Benjamim,

[[v2-1-4]]

^<<v2-1-4,4>>^ Dã, Naftali, Gade e Aser.

[[v2-1-5]]

^<<v2-1-5,5>>^ Os descendentes diretos de Jacó eram setenta pessoas ao todo. José, o outro filho, já estava no Egito.

[[v2-1-6]]

^<<v2-1-6,6>>^ Mais tarde José e todos os seus irmãos morreram, e também todos os outros daquela geração .

[[v2-1-7]]

^<<v2-1-7,7>>^ Mas os descendentes de Jacó, os israelitas, tiveram muitos filhos e aumentaram tanto, que se tornaram poderosos. E eles se espalharam por todo o Egito.

[[v2-1-8]]

^<<v2-1-8,8>>^ Depois o Egito teve um novo rei que não sabia nada a respeito de José.

[[v2-1-9]]

^<<v2-1-9,9>>^ Ele disse ao seu povo: — Vejam! O povo de Israel é forte e está aumentando mais depressa do que nós.

[[v2-1-10]]

^<<v2-1-10,10>>^ Em caso de guerra, eles poderiam se unir com os nossos inimigos, lutariam contra nós e sairiam do país. Precisamos achar um jeito de não deixar que eles se tornem ainda mais numerosos.

[[v2-1-11]]

^<<v2-1-11,11>>^ Por isso os egípcios puseram feitores para maltratar os israelitas com trabalhos pesados. E assim os israelitas construíram as cidades de Pitom e Ramessés, onde o rei do Egito guardava as colheitas de cereais.

[[v2-1-12]]

^<<v2-1-12,12>>^ Porém quanto mais os egípcios maltratavam os israelitas, tanto mais eles aumentavam. Os egípcios ficaram com medo deles

[[v2-1-13]]

^<<v2-1-13,13>>^ e os tornaram escravos, tratando-os com brutalidade.

[[v2-1-14]]

^<<v2-1-14,14>>^ Fizeram com que a vida deles se tornasse amarga, obrigando-os a fazer trabalhos pesados na fabricação de tijolos, nas construções e nas plantações. Em todos os serviços que os israelitas faziam, eles eram tratados com crueldade.

[[v2-1-15]]

^<<v2-1-15,15>>^ O rei do Egito deu a Sifrá e a Puá, que eram parteiras das mulheres israelitas, a seguinte ordem:

[[v2-1-16]]

^<<v2-1-16,16>>^ — Quando vocês forem ajudar as mulheres israelitas nos seus partos, façam o seguinte: se nascer um menino, matem; mas, se nascer uma menina, deixem que viva.

[[v2-1-17]]

^<<v2-1-17,17>>^ Porém as parteiras temiam a Deus  e não fizeram o que o rei do Egito havia mandado. Pelo contrário, deixaram que os meninos vivessem.

[[v2-1-18]]

^<<v2-1-18,18>>^ Então o rei mandou chamar as parteiras e perguntou: — Por que vocês estão fazendo isso? Por que estão deixando que os meninos vivam?

[[v2-1-19]]

^<<v2-1-19,19>>^ Elas responderam: — É que as mulheres israelitas não são como as egípcias. Elas dão à luz com facilidade, e as crianças nascem antes que a parteira chegue.

[[v2-1-20]]

^<<v2-1-20,20>>^ As parteiras temiam a Deus, e por isso ele foi bom para elas e fez com que tivessem as suas próprias famílias. E o povo de Israel aumentou e se tornou muito forte.

[[v2-1-21]]

^<<v2-1-21,21>>^ As parteiras temiam a Deus, e por isso ele foi bom para elas e fez com que tivessem as suas próprias famílias.

'''

xref:001-genesis/001-genesis-050.adoc#v1-50-0[&#60; Capítulo Anterior] | <<v2-1-0,Topo>> | xref:002-exodo/002-exodo-002.adoc#v2-2-0[Próximo Capítulo &#62;]