include::./index.adoc[]

[[v2-12-0]]
=== Êxodo, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-12-1]]

^<<v2-12-1,1>>^ O Senhor  Deus falou com Moisés e Arão no Egito. Ele disse:

[[v2-12-2]]

^<<v2-12-2,2>>^ — Este mês será para vocês o primeiro mês do ano.

[[v2-12-3]]

^<<v2-12-3,3>>^ Diga a todo o povo israelita o seguinte: no dia dez deste mês cada pai de família escolherá um carneirinho ou um cabrito para a sua família, isto é, um animal para cada casa.

[[v2-12-4]]

^<<v2-12-4,4>>^ Se a família for pequena demais para comer o animal inteiro, então o dono da casa e o seu vizinho mais próximo o comerão juntos, repartindo-o de acordo com o número de pessoas e a quantidade que cada um puder comer.

[[v2-12-5]]

^<<v2-12-5,5>>^ O animal deverá ser um carneirinho ou um cabrito sem defeito, de um ano.

[[v2-12-6]]

^<<v2-12-6,6>>^ Vocês o guardarão até o dia catorze deste mês, e na tarde desse dia todo o povo israelita matará os animais.

[[v2-12-7]]

^<<v2-12-7,7>>^ Pegarão um pouco do sangue e o passarão nos batentes dos lados e de cima das portas das casas onde os animais vão ser comidos.

[[v2-12-8]]

^<<v2-12-8,8>>^ Nessa noite a carne deverá ser assada na brasa e comida com pães sem fermento  e com ervas amargas.

[[v2-12-9]]

^<<v2-12-9,9>>^ A carne não deverá ser comida crua nem cozida; o animal inteiro, incluindo a cabeça, as pernas e os miúdos, será assado na brasa.

[[v2-12-10]]

^<<v2-12-10,10>>^ Não deixem nada para o dia seguinte e queimem o que sobrar.

[[v2-12-11]]

^<<v2-12-11,11>>^ Já vestidos, calçados e segurando o bastão, comam depressa o animal. Esta é a Páscoa  de Deus, o Senhor .

[[v2-12-12]]

^<<v2-12-12,12>>^ — Nessa noite eu passarei pela terra do Egito e matarei todos os primeiros filhos, tanto das pessoas como dos animais. E castigarei todos os deuses do Egito. Eu sou o Senhor .

[[v2-12-13]]

^<<v2-12-13,13>>^ O sangue nos batentes das portas será um sinal para marcar as casas onde vocês moram. Quando estiver castigando o Egito, eu verei o sangue e então passarei por vocês sem parar, para que não sejam destruídos por essa praga.

[[v2-12-14]]

^<<v2-12-14,14>>^ Comemorem esse dia como festa religiosa para lembrar que eu, o Senhor , fiz isso. Vocês e os seus descendentes devem comemorar a Festa da Páscoa para sempre.

[[v2-12-15]]

^<<v2-12-15,15>>^ — Durante sete dias vocês comerão pão sem fermento . Por isso, no primeiro dia tirem o fermento das suas casas. Pois qualquer pessoa que comer pão feito com fermento, desde o primeiro até o sétimo dia, será expulsa do meio do povo de Israel.

[[v2-12-16]]

^<<v2-12-16,16>>^ No primeiro dia e também no sétimo, façam uma reunião para adorar a Deus. Nenhum trabalho será feito nesses dias, a não ser para preparar comida.

[[v2-12-17]]

^<<v2-12-17,17>>^ Comemorem a Festa dos Pães sem Fermento  no aniversário do dia em que eu tirei do Egito as tribos  do povo de Israel. Essa comemoração será uma lei  permanente, que passará de pais a filhos.

[[v2-12-18]]

^<<v2-12-18,18>>^ Desde a tarde do dia catorze do primeiro mês até a tarde do dia vinte e um do mesmo mês, o pão que vocês comerem será feito sem fermento.

[[v2-12-19]]

^<<v2-12-19,19>>^ Durante esses sete dias não haverá fermento nas suas casas, pois quem comer pão com fermento, seja um estrangeiro que estiver vivendo no país, seja um israelita, será expulso do meio do povo de Israel.

[[v2-12-20]]

^<<v2-12-20,20>>^ Portanto, nesses dias não comam nada que tenha fermento. Em todas as suas casas só será comido pão sem fermento.

[[v2-12-21]]

^<<v2-12-21,21>>^ Moisés mandou chamar todos os líderes do povo e disse: — Escolham carneiros ou cabritos e os matem para que todas as famílias israelitas possam comemorar a Páscoa .

[[v2-12-22]]

^<<v2-12-22,22>>^ Peguem um galho de hissopo  e o molhem no sangue que estiver na bacia e passem nos batentes dos lados e de cima da porta das suas casas. E que ninguém saia de casa durante toda a noite.

[[v2-12-23]]

^<<v2-12-23,23>>^ Quando o Senhor  passar para matar os egípcios, verá o sangue ali nos batentes e não deixará que o Anjo da Morte entre nas suas casas para matá-los.

[[v2-12-24]]

^<<v2-12-24,24>>^ Vocês e os seus descendentes devem obedecer a essa ordem para sempre.

[[v2-12-25]]

^<<v2-12-25,25>>^ Quando entrarem na terra que o Senhor  lhes dará, como prometeu, vocês deverão continuar realizando essa cerimônia religiosa.

[[v2-12-26]]

^<<v2-12-26,26>>^ Quando os seus filhos perguntarem: "O que quer dizer essa cerimônia?",

[[v2-12-27]]

^<<v2-12-27,27>>^ vocês responderão: "É o sacrifício  da Páscoa em honra do Senhor  Deus, pois no Egito ele passou pelas casas dos israelitas e não parou. O Senhor  matou os egípcios, mas não matou as nossas famílias." Então os israelitas se ajoelharam e adoraram a Deus, o Senhor .

[[v2-12-28]]

^<<v2-12-28,28>>^ Depois foram e fizeram tudo o que ele havia ordenado a Moisés e Arão.

[[v2-12-29]]

^<<v2-12-29,29>>^ À meia-noite, o Senhor  Deus matou os filhos mais velhos de todas as famílias do Egito, desde o filho do rei, que era o herdeiro do trono, até o filho do prisioneiro que estava na cadeia; e matou também a primeira cria dos animais.

[[v2-12-30]]

^<<v2-12-30,30>>^ Naquela noite o rei, os seus funcionários e todos os outros egípcios saíram da cama. É que em todo o Egito havia gente chorando e gritando, pois em todas as casas havia um filho morto.

[[v2-12-31]]

^<<v2-12-31,31>>^ Nessa mesma noite o rei mandou chamar Moisés e Arão e lhes disse: — Saiam daqui, vocês e todos os outros israelitas! Deixem o meu país. Vão adorar a Deus, o Senhor , como vocês pediram.

[[v2-12-32]]

^<<v2-12-32,32>>^ Peguem as suas ovelhas e cabras e o seu gado e vão embora. E peçam a Deus que me abençoe.

[[v2-12-33]]

^<<v2-12-33,33>>^ Os egípcios insistiram com os israelitas para que saíssem do país o mais depressa possível. Eles diziam: — Se vocês não saírem, todos nós morreremos!

[[v2-12-34]]

^<<v2-12-34,34>>^ Assim, cada família israelita pegou a massa de pão sem fermento , pôs numa bacia, embrulhou a bacia num pano e carregou no ombro.

[[v2-12-35]]

^<<v2-12-35,35>>^ Os israelitas fizeram como Moisés havia ordenado e pediram aos egípcios joias de prata e de ouro e roupas.

[[v2-12-36]]

^<<v2-12-36,36>>^ O Senhor  Deus fez com que os egípcios dessem de boa vontade aos israelitas tudo o que eles pediam. Assim o povo de Israel tomou as riquezas dos egípcios.

[[v2-12-37]]

^<<v2-12-37,37>>^ Os israelitas saíram a pé de Ramessés e foram para Sucote. Eram mais ou menos seiscentos mil homens, sem contar as mulheres, as crianças e os velhos.

[[v2-12-38]]

^<<v2-12-38,38>>^ Com eles foram muitas outras pessoas, e também muitas ovelhas e cabras, e muito gado.

[[v2-12-39]]

^<<v2-12-39,39>>^ Os israelitas fizeram pão sem fermento com a massa que haviam levado do Egito, pois os egípcios os haviam expulsado do país tão de repente, que eles não tinham tido tempo de preparar comida, nem de preparar massa com fermento.

[[v2-12-40]]

^<<v2-12-40,40>>^ Os israelitas tinham vivido no Egito quatrocentos e trinta anos.

[[v2-12-41]]

^<<v2-12-41,41>>^ No dia em que terminaram os quatrocentos e trinta anos, todas as tribos  do povo de Deus, o Senhor , saíram do Egito.

[[v2-12-42]]

^<<v2-12-42,42>>^ Essa foi a noite em que o Senhor  ficou vigiando para tirá-los do Egito. Ela é dedicada ao Senhor  para sempre, como a noite que deverá ser comemorada por todos os israelitas.

[[v2-12-43]]

^<<v2-12-43,43>>^ O Senhor  Deus disse a Moisés e a Arão: — Esta é a lei  para a Páscoa : nenhum estrangeiro poderá comer a refeição da Páscoa.

[[v2-12-44]]

^<<v2-12-44,44>>^ Porém todo escravo comprado poderá comer dela depois de ser circuncidado .

[[v2-12-45]]

^<<v2-12-45,45>>^ Os estrangeiros, tanto os que estiverem de passagem como os que estiverem vivendo no país, vivendo de salário, não poderão tomar essa refeição.

[[v2-12-46]]

^<<v2-12-46,46>>^ Ela deverá ser comida na casa onde foi preparada: não será tirada dali. E não quebrem nenhum osso do animal.

[[v2-12-47]]

^<<v2-12-47,47>>^ Todo o povo de Israel deve comemorar essa festa religiosa.

[[v2-12-48]]

^<<v2-12-48,48>>^ Não poderão tomar parte nela os homens que não tiverem sido circuncidados. Porém, se algum estrangeiro estiver morando com vocês e quiser comemorar a Páscoa em honra do Senhor , vocês deverão primeiro circuncidá-lo e também todos os outros homens e meninos da sua família. Depois ele poderá tomar parte na comemoração e será como se fosse uma pessoa nascida em Israel.

[[v2-12-49]]

^<<v2-12-49,49>>^ A mesma lei será para os israelitas nascidos no país e para os estrangeiros que vivem entre vocês.

[[v2-12-50]]

^<<v2-12-50,50>>^ Todos os israelitas obedeceram e fizeram o que o Senhor  havia ordenado a Moisés e a Arão.

[[v2-12-51]]

^<<v2-12-51,51>>^ Naquele dia o Senhor  tirou do Egito as tribos  do povo de Israel.

'''

xref:002-exodo/002-exodo-011.adoc#v2-11-0[&#60; Capítulo Anterior] | <<v2-12-0,Topo>> | xref:002-exodo/002-exodo-013.adoc#v2-13-0[Próximo Capítulo &#62;]