include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-6-1]]

^<<v2-6-1,1>>^ Então o Senhor  Deus respondeu a Moisés: — Agora você verá o que vou fazer com o rei do Egito. Eu vou obrigá-lo a deixar que o meu povo vá embora. Sim, eu o forçarei a expulsar os israelitas do seu país.

[[v2-6-2]]

^<<v2-6-2,2>>^ Deus disse a Moisés: — Eu sou o Senhor .

[[v2-6-3]]

^<<v2-6-3,3>>^ Eu apareci a Abraão, a Isaque e a Jacó como o Deus Todo-Poderoso, porém não deixei que me conhecessem pelo meu nome de Senhor .

[[v2-6-4]]

^<<v2-6-4,4>>^ Fiz uma aliança  com eles e prometi dar-lhes a terra de Canaã, onde tinham vivido como estrangeiros.

[[v2-6-5]]

^<<v2-6-5,5>>^ Agora eu ouvi os gemidos dos israelitas, que estão sendo escravizados pelos egípcios, e lembrei da aliança que fiz com eles.

[[v2-6-6]]

^<<v2-6-6,6>>^ Portanto, diga aos israelitas o seguinte: "Eu sou o Senhor . Vou livrá-los da escravidão do Egito. Estenderei o braço poderoso para fazer cair sobre os egípcios um castigo horrível e salvarei vocês.

[[v2-6-7]]

^<<v2-6-7,7>>^ Farei com que vocês sejam o meu povo e eu serei o seu Deus. Vocês ficarão sabendo que eu sou o Senhor , seu Deus, o Deus que os vai livrar da escravidão no Egito.

[[v2-6-8]]

^<<v2-6-8,8>>^ Eu os levarei para a terra que jurei que daria a Abraão, a Isaque e a Jacó. E eu darei essa terra para ser propriedade de vocês. Eu sou o Senhor ."

[[v2-6-9]]

^<<v2-6-9,9>>^ Moisés repetiu essas palavras aos israelitas, mas eles não quiseram ouvi-lo, pois estavam desanimados por causa da dureza da sua escravidão.

[[v2-6-10]]

^<<v2-6-10,10>>^ Então o Senhor  disse a Moisés:

[[v2-6-11]]

^<<v2-6-11,11>>^ — Vá dizer a Faraó, rei do Egito, que deixe que os israelitas saiam do país.

[[v2-6-12]]

^<<v2-6-12,12>>^ Porém Moisés respondeu ao Senhor : — Se até os israelitas não querem me dar atenção, o rei também não vai querer. Eu não tenho facilidade para falar.

[[v2-6-13]]

^<<v2-6-13,13>>^ No entanto o Senhor  ordenou que Moisés e Arão dissessem aos israelitas e a Faraó, rei do Egito, que eles dois tinham ordem para tirar do país o povo de Israel.

[[v2-6-14]]

^<<v2-6-14,14>>^ Esta é a lista dos grupos de famílias dos antepassados de Moisés e Arão: Rúben, o primeiro filho de Jacó, foi pai de quatro filhos: Enoque, Palu, Hezrom e Carmi. São esses os grupos de famílias de Rúben.

[[v2-6-15]]

^<<v2-6-15,15>>^ Simeão foi pai de seis filhos: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, filho de uma mulher cananeia. São esses os grupos de famílias de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ Levi foi pai de três filhos: Gérson, Coate e Merari. Levi viveu cento e trinta e sete anos.

[[v2-6-17]]

^<<v2-6-17,17>>^ Gérson foi pai de dois filhos: Libni e Simei, e eles tiveram muitos descendentes.

[[v2-6-18]]

^<<v2-6-18,18>>^ São estes os filhos de Coate: Anrão, Isar, Hebrom e Uziel. Coate viveu cento e trinta e três anos.

[[v2-6-19]]

^<<v2-6-19,19>>^ Merari foi pai de dois filhos: Mali e Musi. São esses os grupos de famílias de Levi, com os seus descendentes.

[[v2-6-20]]

^<<v2-6-20,20>>^ Anrão casou com Joquebede, sua tia por parte de pai, e ela lhe deu dois filhos: Arão e Moisés. Anrão viveu cento e trinta e sete anos.

[[v2-6-21]]

^<<v2-6-21,21>>^ Isar foi pai de três filhos: Corá, Nefegue e Zicri.

[[v2-6-22]]

^<<v2-6-22,22>>^ Uziel também foi pai de três filhos: Misael, Elzafã e Sitri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Arão casou com Eliseba, filha de Aminadabe e irmã de Nasom. Ela lhe deu quatro filhos: Nadabe, Abiú, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ Corá foi pai de três filhos: Assir, Elcana e Abiasafe. São esses os grupos de famílias de Corá.

[[v2-6-25]]

^<<v2-6-25,25>>^ Eleazar, filho de Arão, casou com uma das filhas de Putiel, e ela lhe deu um filho, chamado Fineias. São esses os chefes das famílias e dos grupos de famílias da tribo  de Levi.

[[v2-6-26]]

^<<v2-6-26,26>>^ Arão e Moisés foram os que receberam do Senhor  Deus esta ordem: "Tirem do Egito as tribos de Israel."

[[v2-6-27]]

^<<v2-6-27,27>>^ Foram eles que falaram com Faraó, rei do Egito, a fim de tirar de lá os israelitas.

[[v2-6-28]]

^<<v2-6-28,28>>^ Quando o Senhor  falou com Moisés, no Egito,

[[v2-6-29]]

^<<v2-6-29,29>>^ ele disse: — Eu sou o Senhor . Diga a Faraó, rei do Egito, tudo o que vou dizer a você.

[[v2-6-30]]

^<<v2-6-30,30>>^ Porém Moisés respondeu: — Ó Senhor , eu não tenho facilidade para falar. Como é que o rei vai me ouvir?

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]