include::./index.adoc[]

[[v2-22-0]]
=== Êxodo, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-22-1]]

^<<v2-22-1,1>>^ — Se alguém roubar um boi ou uma ovelha e matar ou vender o animal, pagará cinco bois por um boi e quatro ovelhas por uma ovelha.

[[v2-22-2]]

^<<v2-22-2,2>>^ Quem roubou deverá pagar por aquilo que roubou. Se não tiver com que pagar, então deverá ser vendido como escravo para pagar por aquilo que roubou. Se o animal roubado, seja boi, jumento ou ovelha, for encontrado vivo com a pessoa que o roubou, ela pagará dois por um. — Se um ladrão for apanhado roubando de noite uma casa e for morto, quem o matar não será culpado pela morte do ladrão. Mas, se isso acontecer durante o dia, ele será culpado de assassinato.

[[v2-22-3]]

^<<v2-22-3,3>>^ Quem roubou deverá pagar por aquilo que roubou. Se não tiver com que pagar, então deverá ser vendido como escravo para pagar por aquilo que roubou. Se o animal roubado, seja boi, jumento ou ovelha, for encontrado vivo com a pessoa que o roubou, ela pagará dois por um.

[[v2-22-4]]

^<<v2-22-4,4>>^ Quem roubou deverá pagar por aquilo que roubou. Se não tiver com que pagar, então deverá ser vendido como escravo para pagar por aquilo que roubou. Se o animal roubado, seja boi, jumento ou ovelha, for encontrado vivo com a pessoa que o roubou, ela pagará dois por um.

[[v2-22-5]]

^<<v2-22-5,5>>^ — Se alguém deixar que os seus animais pastem num campo ou numa plantação de uvas, ou se os largar para comerem as colheitas de outras pessoas, esse alguém pagará com o melhor do seu próprio campo ou com o melhor da sua própria plantação de uvas.

[[v2-22-6]]

^<<v2-22-6,6>>^ — Se alguém acender uma fogueira no seu campo, e o fogo pegar nos espinheiros e se espalhar pelo campo de outro homem e destruir os feixes de trigo ou as plantações que já estiverem maduras, aquele que acendeu a fogueira pagará todos os prejuízos.

[[v2-22-7]]

^<<v2-22-7,7>>^ — Se alguém receber de outra pessoa dinheiro ou objetos para serem guardados, e isso for roubado da sua casa, o ladrão, se for achado, pagará o dobro.

[[v2-22-8]]

^<<v2-22-8,8>>^ Mas, se o ladrão não for encontrado, o dono da casa será levado ao lugar de adoração e ali deverá jurar que não roubou o que lhe foi dado para guardar.

[[v2-22-9]]

^<<v2-22-9,9>>^ — Se uma pessoa ficar com um boi, um jumento, uma ovelha, roupas ou qualquer coisa perdida, e aparecer alguém dizendo que é o dono, o caso deverá ser levado até o lugar de adoração. Aquele que Deus declarar culpado pagará ao dono o dobro.

[[v2-22-10]]

^<<v2-22-10,10>>^ — Se alguém entregar um animal para o seu vizinho tomar conta, seja jumento, boi, ovelha ou outro animal qualquer, e o animal morrer ou ficar aleijado, ou se for roubado sem que ninguém veja o roubo,

[[v2-22-11]]

^<<v2-22-11,11>>^ o homem que tomou conta deverá jurar em nome de Deus, o Senhor , que não roubou o animal. Se o animal não tiver sido roubado, o dono aceitará o juramento, e o outro não precisará pagar nada.

[[v2-22-12]]

^<<v2-22-12,12>>^ Porém, se, de fato, o animal tiver sido roubado, então o outro terá de pagar ao dono pelo animal.

[[v2-22-13]]

^<<v2-22-13,13>>^ Se o animal tiver sido morto por animais selvagens, o outro terá de trazer como prova o que sobrou e não pagará nada pelo animal morto.

[[v2-22-14]]

^<<v2-22-14,14>>^ — Se alguém pedir emprestado um animal, e este ficar doente ou morrer quando o seu dono não estiver presente, quem pediu emprestado deverá pagar o preço dele.

[[v2-22-15]]

^<<v2-22-15,15>>^ Mas, se isso acontecer quando o dono estiver presente, o outro não precisará pagar nada. Se o animal tiver sido alugado, só será pago o aluguel.

[[v2-22-16]]

^<<v2-22-16,16>>^ — Se um homem seduzir uma virgem que não estava com casamento contratado, ele pagará o dote da moça e casará com ela.

[[v2-22-17]]

^<<v2-22-17,17>>^ Porém, se o pai dela não quiser que a moça case com ele, então ele pagará ao pai uma quantia em dinheiro, de acordo com o preço de uma noiva virgem.

[[v2-22-18]]

^<<v2-22-18,18>>^ — Mate toda mulher que fizer feitiçaria.

[[v2-22-19]]

^<<v2-22-19,19>>^ — Quem tiver relações sexuais com um animal será morto.

[[v2-22-20]]

^<<v2-22-20,20>>^ — Condene à morte toda pessoa que oferecer sacrifícios  a qualquer outro deus e não somente a mim, o Senhor .

[[v2-22-21]]

^<<v2-22-21,21>>^ — Não maltratem, nem persigam um estrangeiro que estiver morando na terra de vocês. Lembrem que vocês foram estrangeiros no Egito.

[[v2-22-22]]

^<<v2-22-22,22>>^ Não maltratem as viúvas nem os órfãos.

[[v2-22-23]]

^<<v2-22-23,23>>^ Se vocês os maltratarem, eu, o Senhor , os atenderei quando eles pedirem socorro.

[[v2-22-24]]

^<<v2-22-24,24>>^ Eu ficarei irado  e matarei vocês na guerra. As suas mulheres ficarão viúvas, e os seus filhos ficarão órfãos.

[[v2-22-25]]

^<<v2-22-25,25>>^ — Se você emprestar dinheiro a algum pobre do meu povo, não faça como o agiota, que cobra juros.

[[v2-22-26]]

^<<v2-22-26,26>>^ Se você receber a capa  do seu vizinho como garantia de uma dívida, devolva-a antes que anoiteça.

[[v2-22-27]]

^<<v2-22-27,27>>^ Pois a capa é a única coisa que ele tem com que se cobrir quando dorme, para esquentar o corpo. Sem a capa, ele não tem nada com que se cobrir. Quando ele clamar a mim pedindo ajuda, eu o atenderei, pois sou bondoso.

[[v2-22-28]]

^<<v2-22-28,28>>^ — Não rogue pragas contra Deus e não amaldiçoe nenhuma das autoridades do seu povo.

[[v2-22-29]]

^<<v2-22-29,29>>^ — Traga-me no tempo certo as ofertas de cereais, de vinho e de azeite. — Entregue-me o seu primeiro filho.

'''

xref:002-exodo/002-exodo-021.adoc#v2-21-0[&#60; Capítulo Anterior] | <<v2-22-0,Topo>> | xref:002-exodo/002-exodo-023.adoc#v2-23-0[Próximo Capítulo &#62;]