include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-18-1]]

^<<v2-18-1,1>>^ Jetro, o sacerdote de Midiã e sogro de Moisés, soube de tudo o que Deus havia feito por Moisés e pelo povo de Israel. E soube também como o Senhor  havia tirado do Egito os israelitas.

[[v2-18-2]]

^<<v2-18-2,2>>^ Então ele foi para o lugar onde Moisés estava, levando Zípora, a mulher de Moisés. Moisés havia mandado Zípora e os dois filhos dela para a casa de Jetro.

[[v2-18-3]]

^<<v2-18-3,3>>^ O nome de um deles era Gérson , pois Moisés tinha dito: "Sou hóspede em terra estrangeira."

[[v2-18-4]]

^<<v2-18-4,4>>^ O nome do outro era Eliézer , pois Moisés tinha dito: "O Deus do meu pai me ajudou e não deixou que eu fosse morto pelo rei do Egito."

[[v2-18-5]]

^<<v2-18-5,5>>^ Jetro, o sogro de Moisés, foi com a mulher e os dois filhos de Moisés para o deserto onde Moisés estava acampado, no monte sagrado .

[[v2-18-6]]

^<<v2-18-6,6>>^ Ele havia mandado um recado a Moisés, dizendo que estava chegando, com a mulher e os filhos dele.

[[v2-18-7]]

^<<v2-18-7,7>>^ Então Moisés saiu para se encontrar com Jetro, curvou-se em sinal de respeito e o beijou. Cada um perguntou ao outro se ia bem de saúde, e depois eles entraram na barraca de Moisés.

[[v2-18-8]]

^<<v2-18-8,8>>^ Ele contou ao sogro tudo o que o Senhor  Deus, por causa do seu amor pelo povo de Israel, tinha feito com o rei do Egito e com os egípcios. Falou também a respeito das dificuldades que o povo havia tido no caminho e como o Senhor  os havia socorrido.

[[v2-18-9]]

^<<v2-18-9,9>>^ Jetro ficou muito contente com tudo o que o Senhor  havia feito pelo povo de Israel, tirando-o do Egito.

[[v2-18-10]]

^<<v2-18-10,10>>^ E disse: — Louvado seja o Senhor  Deus, que libertou vocês das mãos dos egípcios e do seu rei!

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora sei que o Senhor  é mais poderoso do que todos os deuses, pois livrou os israelitas do poder dos egípcios, quando eles os trataram com tanto desprezo.

[[v2-18-12]]

^<<v2-18-12,12>>^ Em seguida Jetro trouxe uma oferta para ser completamente queimada e animais para serem mortos como sacrifício  a Deus. Arão e todos os líderes do povo de Israel foram com ele para comer a refeição sagrada.

[[v2-18-13]]

^<<v2-18-13,13>>^ No dia seguinte Moisés sentou-se para julgar as questões do povo e ficou ocupado desde a manhã até a noite.

[[v2-18-14]]

^<<v2-18-14,14>>^ Quando Jetro viu tudo o que Moisés estava fazendo, perguntou: — Por que você está agindo assim? Por que está resolvendo sozinho os problemas do povo, com todas essas pessoas em pé ao seu redor, desde a manhã até a noite?

[[v2-18-15]]

^<<v2-18-15,15>>^ Moisés respondeu: — Eu tenho de fazer isso porque as pessoas vêm falar comigo para saber o que Deus quer.

[[v2-18-16]]

^<<v2-18-16,16>>^ Quando duas pessoas têm uma questão, elas vêm falar comigo para que eu resolva quem está certo. E explico os mandamentos e as leis  de Deus a todos.

[[v2-18-17]]

^<<v2-18-17,17>>^ Então Jetro disse: — O que você está fazendo não está certo.

[[v2-18-18]]

^<<v2-18-18,18>>^ Desse jeito você vai ficar cansado demais, e o povo também. Isso é muito trabalho para você fazer sozinho.

[[v2-18-19]]

^<<v2-18-19,19>>^ Agora escute o meu conselho, e Deus o ajudará. Está certo que você represente o povo diante de Deus e também que leve a ele os problemas deles.

[[v2-18-20]]

^<<v2-18-20,20>>^ Você deve ensinar-lhes as leis de Deus e explicar o que devem fazer e como devem viver.

[[v2-18-21]]

^<<v2-18-21,21>>^ Mas você deve escolher alguns homens capazes e colocá-los como chefes do povo: chefes de mil, de cem, de cinquenta e de dez. Devem ser homens que temam a Deus , que mereçam confiança e que sejam honestos em tudo.

[[v2-18-22]]

^<<v2-18-22,22>>^ Serão eles que sempre julgarão as questões do povo. Os casos mais difíceis serão trazidos a você, mas os mais fáceis eles mesmos poderão resolver. Assim será melhor para você, pois eles o ajudarão nesse trabalho pesado.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se você fizer isso, e se for essa a ordem de Deus, você não ficará cansado, e todas essas pessoas poderão ir para casa com as suas questões resolvidas.

[[v2-18-24]]

^<<v2-18-24,24>>^ Moisés aceitou o conselho de Jetro

[[v2-18-25]]

^<<v2-18-25,25>>^ e escolheu homens capazes entre todos os israelitas. Ele os colocou como chefes de mil, de cem, de cinquenta e de dez.

[[v2-18-26]]

^<<v2-18-26,26>>^ Eles sempre julgaram as questões do povo, resolvendo as mais fáceis e trazendo para Moisés as mais difíceis.

[[v2-18-27]]

^<<v2-18-27,27>>^ Então Moisés se despediu de Jetro, e Jetro voltou para casa.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]