include::./index.adoc[]

[[v2-25-0]]
=== Êxodo, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-25-1]]

^<<v2-25-1,1>>^ O Senhor  Deus disse a Moisés:

[[v2-25-2]]

^<<v2-25-2,2>>^ — Diga aos israelitas que me deem uma oferta. Receba as ofertas que eles quiserem dar de bom coração.

[[v2-25-3]]

^<<v2-25-3,3>>^ Essas ofertas podem ser ouro, prata ou bronze;

[[v2-25-4]]

^<<v2-25-4,4>>^ fios de lã azul, púrpura  e vermelha; linho fino; tecido feito de pelos de cabra;

[[v2-25-5]]

^<<v2-25-5,5>>^ peles de carneiro tingidas de vermelho e peles finas; madeira de acácia;

[[v2-25-6]]

^<<v2-25-6,6>>^ azeite para lamparinas; especiarias  para a preparação do azeite de ungir  e para o incenso de cheiro agradável;

[[v2-25-7]]

^<<v2-25-7,7>>^ pedras de ônix e outras pedras de valor para serem colocadas no manto sacerdotal  e no peitoral  do Grande Sacerdote .

[[v2-25-8]]

^<<v2-25-8,8>>^ Os israelitas deverão fazer uma Tenda Sagrada  para mim a fim de que eu possa morar no meio deles.

[[v2-25-9]]

^<<v2-25-9,9>>^ — E você, Moisés, faça a Tenda e todos os seus móveis de acordo com o modelo que eu vou lhe mostrar.

[[v2-25-10]]

^<<v2-25-10,10>>^ — Diga aos israelitas que façam uma arca  de madeira de acácia, de um metro e dez de comprimento por sessenta e seis centímetros de largura e sessenta e seis de altura.

[[v2-25-11]]

^<<v2-25-11,11>>^ Revistam de ouro puro essa caixa, por dentro e por fora. E em toda a volta coloquem um remate de ouro.

[[v2-25-12]]

^<<v2-25-12,12>>^ Façam também quatro argolas de ouro e ponham nos quatro pés, ficando duas argolas de cada lado.

[[v2-25-13]]

^<<v2-25-13,13>>^ Façam cabos de madeira de acácia e revistam de ouro.

[[v2-25-14]]

^<<v2-25-14,14>>^ Enfiem os cabos nas argolas nos lados da arca, para que ela possa ser carregada.

[[v2-25-15]]

^<<v2-25-15,15>>^ Os cabos ficarão nas argolas da arca e não serão tirados dela.

[[v2-25-16]]

^<<v2-25-16,16>>^ Eu lhe darei as duas placas de pedra, onde estão escritos os mandamentos; e você porá essas placas na arca.

[[v2-25-17]]

^<<v2-25-17,17>>^ — Faça também uma tampa de ouro puro, de um metro e dez de comprimento por sessenta e seis centímetros de largura.

[[v2-25-18]]

^<<v2-25-18,18>>^ Faça dois querubins  de ouro batido,

[[v2-25-19]]

^<<v2-25-19,19>>^ um para cada ponta da tampa. Isso deve ser feito de modo que os querubins formem uma só peça com a tampa.

[[v2-25-20]]

^<<v2-25-20,20>>^ Os querubins ficarão de frente um para o outro, olhando para a tampa. As suas asas ficarão abertas, cobrindo a tampa.

[[v2-25-21]]

^<<v2-25-21,21>>^ Coloque dentro da arca as duas placas de pedra que eu vou lhe dar e ponha a tampa na arca.

[[v2-25-22]]

^<<v2-25-22,22>>^ Ali eu me encontrarei com você e, de cima da tampa, do meio dos dois querubins, eu lhe darei as minhas leis  para o povo de Israel.

[[v2-25-23]]

^<<v2-25-23,23>>^ — Você deverá fazer também uma mesa de madeira de acácia, com as seguintes medidas: oitenta e oito centímetros de comprimento por quarenta e quatro de largura e sessenta e seis de altura.

[[v2-25-24]]

^<<v2-25-24,24>>^ Revista de ouro puro a mesa e coloque um remate de ouro em volta dela.

[[v2-25-25]]

^<<v2-25-25,25>>^ Em volta da mesa faça um friso de quatro dedos de largura e um remate de ouro em volta do friso.

[[v2-25-26]]

^<<v2-25-26,26>>^ Faça também quatro argolas de ouro e ponha nos quatro cantos, perto dos quatro pés.

[[v2-25-27]]

^<<v2-25-27,27>>^ Perto do friso deverão ser colocadas as argolas por onde passam os cabos para se carregar a mesa.

[[v2-25-28]]

^<<v2-25-28,28>>^ Esses cabos deverão ser feitos de madeira de acácia e revestidos de ouro. A mesa será carregada por esses cabos.

[[v2-25-29]]

^<<v2-25-29,29>>^ Faça os pratos, os copos, as taças e as jarras que serão usados para as ofertas de vinho. Tudo isso deverá ser feito de ouro puro.

[[v2-25-30]]

^<<v2-25-30,30>>^ A mesa será colocada na frente da arca da aliança , e em cima da mesa estarão sempre os pães sagrados que são oferecidos a mim.

[[v2-25-31]]

^<<v2-25-31,31>>^ — Faça um candelabro  de ouro puro. A sua base e a sua haste deverão ser de ouro batido. As flores que enfeitarão o candelabro, com os seus botões e as suas pétalas, formarão uma só peça com ele.

[[v2-25-32]]

^<<v2-25-32,32>>^ Dos seus lados sairão seis braços, três de um lado e três do outro.

[[v2-25-33]]

^<<v2-25-33,33>>^ Cada um dos seis braços deverá ter três flores com o formato de flor de amendoeira, com os seus botões e as suas pétalas.

[[v2-25-34]]

^<<v2-25-34,34>>^ — A haste do candelabro deverá ter quatro flores com o formato de flor de amendoeira, com os seus botões e as suas pétalas.

[[v2-25-35]]

^<<v2-25-35,35>>^ Debaixo de cada um dos três pares de braços deverá haver um botão de amendoeira.

[[v2-25-36]]

^<<v2-25-36,36>>^ Os botões, os braços e o candelabro deverão formar uma só peça de ouro puro batido.

[[v2-25-37]]

^<<v2-25-37,37>>^ Faça sete lamparinas para o candelabro e coloque-as na parte de cima, de maneira que iluminem a frente dele.

[[v2-25-38]]

^<<v2-25-38,38>>^ As tesouras de cortar os pavios das lamparinas e os cinzeiros deverão ser de ouro puro.

[[v2-25-39]]

^<<v2-25-39,39>>^ Use trinta e quatro quilos de ouro puro para fazer o candelabro e todas as peças que o acompanham.

[[v2-25-40]]

^<<v2-25-40,40>>^ — E tenha o cuidado de fazer tudo de acordo com o modelo que eu lhe mostrei no monte.

'''

xref:002-exodo/002-exodo-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodo/002-exodo-026.adoc#v2-26-0[Próximo Capítulo &#62;]