include::./index.adoc[]

[[v2-2-0]]
=== Êxodo, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-2-1]]

^<<v2-2-1,1>>^ Um homem e uma mulher da tribo  de Levi casaram.

[[v2-2-2]]

^<<v2-2-2,2>>^ A mulher ficou grávida e deu à luz um filho. Ela viu que o menino era muito bonito e então o escondeu durante três meses.

[[v2-2-3]]

^<<v2-2-3,3>>^ Como não podia escondê-lo por mais tempo, ela pegou uma cesta de junco , tapou os buracos com betume  e piche, pôs nela o menino e deixou a cesta entre os juncos, na beira do rio.

[[v2-2-4]]

^<<v2-2-4,4>>^ A irmã do menino ficou de longe, para ver o que ia acontecer com ele.

[[v2-2-5]]

^<<v2-2-5,5>>^ A filha do rei do Egito foi até o rio e estava tomando banho enquanto as suas empregadas passeavam ali pela margem. De repente, ela viu a cesta no meio da moita de juncos e mandou que uma das suas escravas fosse buscá-la.

[[v2-2-6]]

^<<v2-2-6,6>>^ A princesa abriu a cesta e viu um bebê chorando. Ela ficou com muita pena dele e disse: — Este é um menino israelita.

[[v2-2-7]]

^<<v2-2-7,7>>^ Então a irmã da criança perguntou à princesa: — Quer que eu vá chamar uma mulher israelita para amamentar e criar esta criança para a senhora?

[[v2-2-8]]

^<<v2-2-8,8>>^ — Vá — respondeu a princesa. Então a moça foi e trouxe a própria mãe do menino.

[[v2-2-9]]

^<<v2-2-9,9>>^ Aí a princesa lhe disse: — Leve este menino e o crie para mim, que eu pagarei pelo seu trabalho. A mulher levou o menino e o criou.

[[v2-2-10]]

^<<v2-2-10,10>>^ Quando ele já estava grande, ela o levou à filha do rei, que o adotou como filho. Ela pôs nele o nome de Moisés e disse: — Eu o tirei da água.

[[v2-2-11]]

^<<v2-2-11,11>>^ Moisés já era homem feito. Um dia ele saiu para visitar o seu povo e viu como os israelitas eram obrigados a fazer trabalhos pesados. Viu também um egípcio batendo num israelita, um patrício seu.

[[v2-2-12]]

^<<v2-2-12,12>>^ Moisés olhou para os lados e, vendo que não havia ninguém ali, matou o egípcio e escondeu o corpo na areia.

[[v2-2-13]]

^<<v2-2-13,13>>^ No dia seguinte voltou e viu dois israelitas brigando. Então perguntou ao que maltratava o outro: — Por que você está batendo no seu patrício?

[[v2-2-14]]

^<<v2-2-14,14>>^ O homem respondeu: — Quem pôs você como nosso chefe ou nosso juiz? Você está querendo me matar como matou o egípcio? Então Moisés ficou com medo e pensou: "Já descobriram o que eu fiz."

[[v2-2-15]]

^<<v2-2-15,15>>^ Quando o rei do Egito soube do que Moisés havia feito, quis matá-lo; porém ele fugiu e foi morar na terra de Midiã. Jetro , o sacerdote de Midiã, tinha sete filhas. Certo dia, quando Moisés estava sentado perto de um poço, elas vieram tirar água e encheram os bebedouros para dar de beber às ovelhas e às cabras do seu pai.

[[v2-2-16]]

^<<v2-2-16,16>>^ Quando o rei do Egito soube do que Moisés havia feito, quis matá-lo; porém ele fugiu e foi morar na terra de Midiã.

[[v2-2-17]]

^<<v2-2-17,17>>^ Então chegaram alguns pastores e começaram a enxotar as moças dali. Porém Moisés se levantou, e as defendeu, e deu água aos animais.

[[v2-2-18]]

^<<v2-2-18,18>>^ Quando elas voltaram ao lugar onde o seu pai estava, ele perguntou: — Por que é que vocês voltaram tão cedo hoje?

[[v2-2-19]]

^<<v2-2-19,19>>^ Elas responderam: — Um egípcio nos defendeu dos pastores, tirou água para nós e ainda deu água para os nossos animais.

[[v2-2-20]]

^<<v2-2-20,20>>^ — E onde está ele? — perguntou Jetro. — Por que vocês o deixaram lá? Vão chamá-lo para que venha jantar com a gente.

[[v2-2-21]]

^<<v2-2-21,21>>^ Depois Jetro convidou Moisés para ficar morando ali, e ele aceitou. Então Jetro lhe deu a sua filha Zípora em casamento.

[[v2-2-22]]

^<<v2-2-22,22>>^ Quando ela teve um filho, Moisés pôs nele o nome de Gérson e disse: — Sou hóspede em terra estrangeira.

[[v2-2-23]]

^<<v2-2-23,23>>^ Alguns anos depois o rei do Egito morreu, mas os israelitas continuaram gemendo por causa da sua escravidão. Eles gritavam pedindo socorro, e os seus pedidos chegaram até Deus.

[[v2-2-24]]

^<<v2-2-24,24>>^ Deus ouviu os gemidos deles e lembrou da aliança  que havia feito com Abraão, com Isaque e com Jacó.

'''

xref:002-exodo/002-exodo-001.adoc#v2-1-0[&#60; Capítulo Anterior] | <<v2-2-0,Topo>> | xref:002-exodo/002-exodo-003.adoc#v2-3-0[Próximo Capítulo &#62;]