include::./index.adoc[]

[[v2-9-0]]
=== Êxodo, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-9-1]]

^<<v2-9-1,1>>^ O Senhor  Deus disse a Moisés: — Vá falar com o rei e diga que o Senhor , o Deus dos hebreus, diz o seguinte: "Deixe que o meu povo saia do país a fim de me adorar.

[[v2-9-2]]

^<<v2-9-2,2>>^ Pois, se você não deixar e continuar impedindo que ele vá,

[[v2-9-3]]

^<<v2-9-3,3>>^ eu o castigarei com uma doença horrível, que atacará todos os seus animais, isto é, os cavalos, os jumentos, os camelos, o gado, as ovelhas e as cabras.

[[v2-9-4]]

^<<v2-9-4,4>>^ Farei diferença entre os animais dos israelitas e os dos egípcios, e não morrerá nenhum animal dos israelitas.

[[v2-9-5]]

^<<v2-9-5,5>>^ Eu, o Senhor , marquei um prazo: farei isso amanhã."

[[v2-9-6]]

^<<v2-9-6,6>>^ No dia seguinte o Senhor  fez como tinha dito, e todos os animais dos egípcios morreram; porém não morreu nenhum dos animais dos israelitas.

[[v2-9-7]]

^<<v2-9-7,7>>^ O rei mandou ver o que havia acontecido e foi informado de que não havia morrido nenhum animal dos israelitas. Apesar disso o rei continuou teimando e não deixou o povo ir.

[[v2-9-8]]

^<<v2-9-8,8>>^ Então o Senhor  Deus disse a Moisés e a Arão: — Peguem punhados de cinza de um forno, e que Moisés jogue essa cinza para o ar diante do rei do Egito.

[[v2-9-9]]

^<<v2-9-9,9>>^ Ela se espalhará como um pó fino sobre toda a terra do Egito, e em todos os lugares a cinza produzirá tumores que se abrirão em úlceras nas pessoas e nos animais.

[[v2-9-10]]

^<<v2-9-10,10>>^ Assim, Moisés e Arão pegaram cinza e ficaram de pé na frente do rei. Moisés jogou a cinza para cima, e ela produziu tumores, que viraram úlceras nas pessoas e nos animais.

[[v2-9-11]]

^<<v2-9-11,11>>^ Os mágicos não puderam aparecer diante de Moisés porque eles e todos os outros egípcios estavam cobertos de tumores.

[[v2-9-12]]

^<<v2-9-12,12>>^ Porém o Senhor  Deus fez com que o rei continuasse teimando. E, como o Senhor  tinha dito a Moisés, o rei não atendeu o pedido de Moisés e Arão.

[[v2-9-13]]

^<<v2-9-13,13>>^ O Senhor  Deus disse a Moisés: — Amanhã cedo vá se encontrar com o rei e diga-lhe que o Senhor , o Deus dos hebreus, diz o seguinte: "Deixe que o meu povo saia do país a fim de me adorar.

[[v2-9-14]]

^<<v2-9-14,14>>^ Pois desta vez eu vou fazer todas as minhas pragas caírem sobre você, sobre os seus funcionários e sobre o seu povo, para que você fique sabendo que em todo o mundo não há ninguém como eu.

[[v2-9-15]]

^<<v2-9-15,15>>^ Se eu tivesse atacado você e o seu povo com doenças, você já teria sido completamente destruído.

[[v2-9-16]]

^<<v2-9-16,16>>^ Mas estou deixando que você viva para mostrar a você o meu poder e para fazer com que o meu nome seja conhecido no mundo inteiro.

[[v2-9-17]]

^<<v2-9-17,17>>^ Você ainda continua orgulhoso e não quer deixar o meu povo ir.

[[v2-9-18]]

^<<v2-9-18,18>>^ Porém amanhã a esta hora eu vou fazer cair uma chuva de pedra tão forte como nunca houve igual em toda a história do Egito.

[[v2-9-19]]

^<<v2-9-19,19>>^ Portanto, agora mande recolher o seu gado e tudo o que você tem no campo. Se as pessoas e os animais que estiverem no campo não forem para casa, quando cair a chuva de pedra, todos eles morrerão."

[[v2-9-20]]

^<<v2-9-20,20>>^ Alguns funcionários do rei ficaram com medo daquilo que o Senhor  tinha dito e levaram os seus escravos e os seus animais para os abrigos.

[[v2-9-21]]

^<<v2-9-21,21>>^ Mas os que não deram atenção ao que o Senhor  tinha dito deixaram os seus escravos e os seus animais nos campos.

[[v2-9-22]]

^<<v2-9-22,22>>^ Então o Senhor  Deus disse a Moisés: — Levante a mão para o céu, e cairá chuva de pedra em toda a terra do Egito. Cairá sobre o povo, sobre os animais e sobre todas as plantas do campo.

[[v2-9-23]]

^<<v2-9-23,23>>^ Moisés levantou o bastão para o céu, e o Senhor  mandou trovões, chuva de pedra e raios sobre o país. Ele fez cair

[[v2-9-24]]

^<<v2-9-24,24>>^ uma pesada chuva de pedra sobre todo o Egito, e a chuva e os raios caíram sem parar. Essa foi a pior tempestade que o Egito já teve em toda a sua história.

[[v2-9-25]]

^<<v2-9-25,25>>^ Em todo o Egito a chuva de pedra acabou com tudo o que estava no campo, incluindo as pessoas e os animais. Destruiu todas as plantas e quebrou todas as árvores.

[[v2-9-26]]

^<<v2-9-26,26>>^ Somente na região de Gosém, onde estavam os israelitas, a chuva de pedra não caiu.

[[v2-9-27]]

^<<v2-9-27,27>>^ Então o rei mandou chamar Moisés e Arão e disse: — Desta vez eu pequei. O Senhor  Deus é justo; eu e o meu povo somos culpados.

[[v2-9-28]]

^<<v2-9-28,28>>^ Orem ao Senhor . Chega de trovões e de chuva de pedra! Eu os deixarei ir; vocês não precisam esperar mais.

[[v2-9-29]]

^<<v2-9-29,29>>^ Moisés respondeu: — Quando sair da cidade, eu levantarei as mãos em oração a Deus, o Senhor . Os trovões vão parar, e não haverá mais chuva de pedra. Isso para que o senhor, ó rei, fique sabendo que a terra é de Deus.

[[v2-9-30]]

^<<v2-9-30,30>>^ Mas eu sei que o senhor e os seus funcionários ainda não temem a Deus , o Senhor .

[[v2-9-31]]

^<<v2-9-31,31>>^ O linho e a cevada  foram destruídos, pois a cevada já estava com espigas, e o linho estava em flor.

[[v2-9-32]]

^<<v2-9-32,32>>^ Porém o trigo e o centeio não foram destruídos, pois ainda não haviam brotado.

[[v2-9-33]]

^<<v2-9-33,33>>^ Depois de ter estado com o rei, Moisés saiu da cidade e levantou as mãos em oração a Deus, o Senhor . Aí os trovões, a chuva e a chuva de pedra pararam.

[[v2-9-34]]

^<<v2-9-34,34>>^ Porém, quando o rei viu que tinha parado de chover e que não trovejava mais, nem caía chuva de pedra, ele tornou a pecar. Ele e os seus funcionários continuaram teimando. E, como o Senhor  tinha dito por meio de Moisés, o rei não deixou que os israelitas fossem embora.

'''

xref:002-exodo/002-exodo-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodo/002-exodo-010.adoc#v2-10-0[Próximo Capítulo &#62;]