include::./index.adoc[]

[[v2-10-0]]
=== Êxodo, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-10-1]]

^<<v2-10-1,1>>^ O Senhor  Deus disse a Moisés: — Vá falar com o rei, pois eu fiz com que ele e os seus funcionários continuassem teimando, para que eu pudesse fazer esses milagres no meio deles.

[[v2-10-2]]

^<<v2-10-2,2>>^ E também para que você pudesse contar aos seus filhos e aos seus netos como eu zombei dos egípcios e quantas coisas espantosas fiz no meio deles. Assim vocês ficarão sabendo que eu sou Deus, o Senhor .

[[v2-10-3]]

^<<v2-10-3,3>>^ Moisés e Arão foram falar com o rei do Egito e lhe disseram: — O Senhor , o Deus dos hebreus, diz isto: "Até quando você vai continuar não querendo se humilhar diante de mim? Deixe que o meu povo saia do país a fim de me adorar.

[[v2-10-4]]

^<<v2-10-4,4>>^ Se não, amanhã eu vou trazer gafanhotos para o seu país.

[[v2-10-5]]

^<<v2-10-5,5>>^ O chão não poderá mais ser visto, pois eles cobrirão a terra do Egito. Eles comerão tudo o que a chuva de pedra não destruiu e até as árvores que sobraram.

[[v2-10-6]]

^<<v2-10-6,6>>^ Eles encherão as suas casas, as casas de todos os seus funcionários e de todo o seu povo. E essa desgraça será pior do que tudo o que os seus pais e os seus antepassados já viram!" Moisés disse isso e saiu do palácio.

[[v2-10-7]]

^<<v2-10-7,7>>^ Então os funcionários do palácio disseram ao rei: — Até quando esse sujeito vai ser um perigo para nós? Deixe que os homens vão embora, para adorarem o Senhor , o Deus deles. Por acaso o senhor não sabe que o Egito está arrasado?

[[v2-10-8]]

^<<v2-10-8,8>>^ Aí Moisés e Arão foram levados de novo até a presença do rei, e este lhes disse: — Vocês podem ir adorar o Senhor , seu Deus. Mas eu quero saber quem é que vai.

[[v2-10-9]]

^<<v2-10-9,9>>^ Moisés respondeu: — Iremos todos nós, com as nossas crianças e os nossos velhos. Levaremos os nossos filhos e filhas, as nossas ovelhas e cabras e o nosso gado, pois temos de dar uma festa em honra de Deus, o Senhor .

[[v2-10-10]]

^<<v2-10-10,10>>^ Então o rei disse: — Pois que o Senhor  vá com vocês! Mas não vou deixar, de jeito nenhum, que vocês levem as suas mulheres e os seus filhos! É claro que vocês estão planejando uma revolução.

[[v2-10-11]]

^<<v2-10-11,11>>^ Não! Somente os homens podem ir adorar ao Senhor , se é isso o que vocês querem. E Arão e Moisés foram expulsos da presença do rei.

[[v2-10-12]]

^<<v2-10-12,12>>^ Aí o Senhor  Deus disse a Moisés: — Estenda a mão sobre o Egito para que venham gafanhotos. Eles virão e comerão todas as plantas da terra, tudo o que a chuva de pedra não destruiu.

[[v2-10-13]]

^<<v2-10-13,13>>^ Moisés estendeu o bastão sobre o Egito, e o Senhor  mandou do Leste um vento que soprou sobre o país o dia inteiro e a noite inteira. Quando amanheceu, o vento tinha trazido os gafanhotos.

[[v2-10-14]]

^<<v2-10-14,14>>^ Eles se espalharam sobre todo o Egito e invadiram toda aquela região em quantidades enormes, como nunca havia acontecido antes e nunca mais acontecerá.

[[v2-10-15]]

^<<v2-10-15,15>>^ Eles cobriram de tal maneira o chão, que este ficou preto. Devoraram toda a vegetação e todas as frutas das árvores que haviam sobrado da chuva de pedra. Em todo o Egito não sobrou nada verde nas árvores e nas plantas.

[[v2-10-16]]

^<<v2-10-16,16>>^ Então o rei mandou chamar imediatamente Moisés e Arão e lhes disse: — Eu pequei contra o Senhor , seu Deus, e contra vocês.

[[v2-10-17]]

^<<v2-10-17,17>>^ Agora peço que perdoem o meu pecado ainda esta vez e que orem ao Senhor , seu Deus, para que ele tire de mim este castigo terrível.

[[v2-10-18]]

^<<v2-10-18,18>>^ Moisés saiu do palácio e orou a Deus, o Senhor .

[[v2-10-19]]

^<<v2-10-19,19>>^ Aí o Senhor  fez soprar um vento oeste muito forte, que levantou os gafanhotos e os jogou no mar Vermelho; e não ficou um só gafanhoto em todo o Egito.

[[v2-10-20]]

^<<v2-10-20,20>>^ Porém o Senhor  fez com que o rei continuasse teimando, e este não deixou que os israelitas fossem embora.

[[v2-10-21]]

^<<v2-10-21,21>>^ Então o Senhor  Deus disse a Moisés: — Levante a mão para o céu a fim de que em todo o Egito haja uma escuridão tão grossa, que possa até ser tocada.

[[v2-10-22]]

^<<v2-10-22,22>>^ Moisés levantou a mão para o céu, e durante três dias uma grande escuridão cobriu todo o Egito.

[[v2-10-23]]

^<<v2-10-23,23>>^ Os egípcios não podiam ver uns aos outros, e naqueles dias ninguém saiu de casa. Porém em todas as casas dos israelitas havia claridade.

[[v2-10-24]]

^<<v2-10-24,24>>^ Aí o rei mandou chamar Moisés e lhe disse: — Vocês podem ir adorar a Deus, o Senhor . Levem também as suas mulheres e os seus filhos, mas as ovelhas, as cabras e o gado ficarão aqui.

[[v2-10-25]]

^<<v2-10-25,25>>^ Moisés respondeu: — Nesse caso o senhor deveria nos dar os animais para oferecermos em sacrifício  e queimarmos em honra do Senhor , nosso Deus.

[[v2-10-26]]

^<<v2-10-26,26>>^ Nós não queremos isso. Nós vamos levar também os nossos animais, e não ficará nenhum, pois temos de escolher alguns para usá-los na adoração a Deus, o Senhor . Enquanto não chegarmos lá, não saberemos quais os animais que deveremos oferecer em sacrifício ao Senhor .

[[v2-10-27]]

^<<v2-10-27,27>>^ Porém o Senhor  fez com que o rei continuasse teimando, e este não deixou que os israelitas saíssem do Egito.

[[v2-10-28]]

^<<v2-10-28,28>>^ O rei disse a Moisés: — Saia da minha presença e nunca mais apareça aqui! Pois, no dia em que tornar a me ver, você morrerá!

[[v2-10-29]]

^<<v2-10-29,29>>^ — O senhor está certo — respondeu Moisés. — Nunca mais eu o verei.

'''

xref:002-exodo/002-exodo-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodo/002-exodo-011.adoc#v2-11-0[Próximo Capítulo &#62;]