include::./index.adoc[]

[[v2-38-0]]
=== Êxodo, 38
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-38-1]]

^<<v2-38-1,1>>^ Para os sacrifícios  que eram completamente queimados, Bezalel fez um altar de madeira de acácia. O tampo do altar era quadrado, medindo dois metros e vinte de comprimento por dois metros e vinte de largura; e o altar media um metro e trinta de altura.

[[v2-38-2]]

^<<v2-38-2,2>>^ Bezalel fez quatro pontas para os quatro cantos do altar. Essas quatro pontas formavam uma só peça com o altar. E ele o revestiu todo de bronze.

[[v2-38-3]]

^<<v2-38-3,3>>^ Fez também todas as peças para serem usadas no altar, isto é, as vasilhas, as pás, as bacias, os garfos e os braseiros. Todas essas peças foram feitas de bronze.

[[v2-38-4]]

^<<v2-38-4,4>>^ Ele fez uma grelha de bronze em forma de rede e a colocou debaixo da beirada do altar, de modo que a grelha chegava até a metade da altura do altar.

[[v2-38-5]]

^<<v2-38-5,5>>^ Fez quatro argolas para os quatro cantos da grelha, para enfiar nelas os cabos.

[[v2-38-6]]

^<<v2-38-6,6>>^ Os cabos foram feitos de madeira de acácia e revestidos de bronze.

[[v2-38-7]]

^<<v2-38-7,7>>^ Depois Bezalel enfiou os cabos nas argolas nos dois lados do altar. O altar foi feito de madeira e era oco.

[[v2-38-8]]

^<<v2-38-8,8>>^ Com os espelhos de bronze das mulheres que faziam serviços na entrada da Tenda da Presença de Deus , Bezalel fez a pia e a sua base.

[[v2-38-9]]

^<<v2-38-9,9>>^ Para a Tenda da Presença de Deus , Bezalel fez um pátio cercado de cortinas de linho fino. No lado sul as cortinas tinham quarenta e quatro metros de comprimento.

[[v2-38-10]]

^<<v2-38-10,10>>^ Elas eram sustentadas por vinte postes de bronze com bases também de bronze. Os ganchos dos postes e os suportes das cortinas eram de prata.

[[v2-38-11]]

^<<v2-38-11,11>>^ Bezalel fez a mesma coisa no lado norte do pátio.

[[v2-38-12]]

^<<v2-38-12,12>>^ O pátio tinha vinte e dois metros de largura; portanto, nos lados oeste e leste as cortinas tinham vinte e dois metros de comprimento. Para sustentarem as cortinas, havia dez postes e dez bases; os ganchos e os suportes eram de prata. A entrada do pátio ficava no lado leste.

[[v2-38-13]]

^<<v2-38-13,13>>^ O pátio tinha vinte e dois metros de largura; portanto, nos lados oeste e leste as cortinas tinham vinte e dois metros de comprimento. Para sustentarem as cortinas, havia dez postes e dez bases; os ganchos e os suportes eram de prata. A entrada do pátio ficava no lado leste.

[[v2-38-14]]

^<<v2-38-14,14>>^ De cada lado da entrada havia cortinas de seis metros e sessenta de comprimento, com três postes e três bases para sustentarem as cortinas.

[[v2-38-15]]

^<<v2-38-15,15>>^ De cada lado da entrada havia cortinas de seis metros e sessenta de comprimento, com três postes e três bases para sustentarem as cortinas.

[[v2-38-16]]

^<<v2-38-16,16>>^ Todas as cortinas que ficavam em volta do pátio eram de linho fino.

[[v2-38-17]]

^<<v2-38-17,17>>^ As bases das colunas eram de bronze, e os ganchos, os suportes e a parte de cima dos postes eram de prata. E todos os postes em volta do pátio eram unidos por suportes de prata.

[[v2-38-18]]

^<<v2-38-18,18>>^ A cortina da entrada do pátio era de tecido feito de linho fino e de fios de lã azul, púrpura  e vermelha, enfeitada com bordados. O comprimento dessa cortina era de oito metros e oitenta, e a altura, de dois metros e vinte, como as cortinas do pátio.

[[v2-38-19]]

^<<v2-38-19,19>>^ Ela era sustentada por quatro postes com bases de bronze. Os ganchos, a parte de cima dos postes e os suportes eram de prata.

[[v2-38-20]]

^<<v2-38-20,20>>^ Todas as estacas da Tenda e do pátio eram de bronze.

[[v2-38-21]]

^<<v2-38-21,21>>^ A seguir vem a lista da quantidade dos metais usados na Tenda da Presença de Deus , onde estavam guardadas as duas placas de pedra, com os dez mandamentos. Moisés mandou fazer a lista, e ela foi preparada pelos levitas  dirigidos por Itamar, filho do sacerdote Arão.

[[v2-38-22]]

^<<v2-38-22,22>>^ Bezalel, filho de Uri e neto de Hur, da tribo  de Judá, fez tudo o que o Senhor  havia ordenado a Moisés.

[[v2-38-23]]

^<<v2-38-23,23>>^ O seu ajudante foi Aoliabe, filho de Aisamaque, da tribo de Dã. Aoliabe era gravador, desenhista e tecia linho fino e fios de lã azul, púrpura  e vermelha.

[[v2-38-24]]

^<<v2-38-24,24>>^ Todo o ouro que havia sido oferecido ao Senhor  para a Tenda Sagrada pesava mil quilos, de acordo com a tabela oficial.

[[v2-38-25]]

^<<v2-38-25,25>>^ A prata da contagem do povo pesava três mil quatrocentos e trinta quilos, de acordo com a tabela oficial.

[[v2-38-26]]

^<<v2-38-26,26>>^ Essa quantia foi igual ao total pago por todos os homens alistados na contagem do povo; e cada homem pagava a importância exigida , pesada de acordo com a tabela oficial. Foram alistados na contagem seiscentos e três mil quinhentos e cinquenta homens de vinte anos para cima.

[[v2-38-27]]

^<<v2-38-27,27>>^ Foram usados três mil e quatrocentos quilos de prata para fazer as cem bases da Tenda Sagrada e da cortina, isto é, trinta e quatro quilos para cada base.

[[v2-38-28]]

^<<v2-38-28,28>>^ Com os trinta quilos de prata que sobraram, Bezalel fez os cabos, os ganchos para os postes e a parte de cima dos postes.

[[v2-38-29]]

^<<v2-38-29,29>>^ O bronze que foi oferecido a Deus dava um total de dois mil quatrocentos e vinte e cinco quilos.

'''

xref:002-exodo/002-exodo-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodo/002-exodo-039.adoc#v2-39-0[Próximo Capítulo &#62;]