include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-37-1]]

^<<v2-37-1,1>>^ Bezalel fez a arca da aliança  de madeira de acácia; a arca media um metro e dez de comprimento por sessenta e seis centímetros de largura e sessenta e seis de altura.

[[v2-37-2]]

^<<v2-37-2,2>>^ Ele a revestiu de ouro puro por dentro e por fora e pôs em toda a volta um remate de ouro.

[[v2-37-3]]

^<<v2-37-3,3>>^ Fez quatro argolas de ouro e as colocou nos quatro pés da arca, ficando duas argolas de cada lado.

[[v2-37-4]]

^<<v2-37-4,4>>^ Ele fez cabos de madeira de acácia e os revestiu de ouro.

[[v2-37-5]]

^<<v2-37-5,5>>^ Depois enfiou os cabos nas argolas nos dois lados da arca, para que pudesse ser carregada.

[[v2-37-6]]

^<<v2-37-6,6>>^ Bezalel fez uma tampa de ouro puro de um metro e dez de comprimento por sessenta e seis centímetros de largura.

[[v2-37-7]]

^<<v2-37-7,7>>^ Ele fez dois querubins  de ouro batido,

[[v2-37-8]]

^<<v2-37-8,8>>^ um para cada ponta da tampa. Ele os fez de tal modo, que formavam uma só peça com a tampa.

[[v2-37-9]]

^<<v2-37-9,9>>^ Os querubins ficavam de frente um para o outro, olhando para a tampa, e as suas asas abertas cobriam a tampa.

[[v2-37-10]]

^<<v2-37-10,10>>^ Bezalel fez uma mesa de madeira de acácia, com as seguintes medidas: oitenta e oito centímetros de comprimento por quarenta e quatro de largura e sessenta e seis de altura.

[[v2-37-11]]

^<<v2-37-11,11>>^ Ele revestiu de ouro puro a mesa e colocou um remate de ouro em volta dela.

[[v2-37-12]]

^<<v2-37-12,12>>^ Também fez em volta da mesa um friso de quatro dedos de largura e pôs um remate de ouro em volta do friso.

[[v2-37-13]]

^<<v2-37-13,13>>^ Fez quatro argolas de ouro e as pôs nos quatro cantos, perto dos quatro pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ Perto do friso estavam as argolas por onde passavam os cabos que eram usados para se carregar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Ele fez os cabos de madeira de acácia e os revestiu de ouro.

[[v2-37-16]]

^<<v2-37-16,16>>^ Fez também de ouro puro as vasilhas para a mesa, isto é, os pratos, os copos, as taças e as jarras que eram usados para as ofertas de vinho.

[[v2-37-17]]

^<<v2-37-17,17>>^ Bezalel fez de ouro puro batido o candelabro , a sua base e a sua haste. As flores que enfeitavam o candelabro, com os seus botões e as suas pétalas, formavam uma só peça com ele.

[[v2-37-18]]

^<<v2-37-18,18>>^ Dos seus lados saíam seis braços, três de um lado e três do outro.

[[v2-37-19]]

^<<v2-37-19,19>>^ Cada um dos seis braços tinha três flores com o formato de flor de amendoeira, com os seus botões e as suas pétalas.

[[v2-37-20]]

^<<v2-37-20,20>>^ A haste do candelabro tinha quatro flores com o formato de flor de amendoeira, com os seus botões e as suas pétalas.

[[v2-37-21]]

^<<v2-37-21,21>>^ Havia um botão de amendoeira debaixo de cada um dos três pares de braços.

[[v2-37-22]]

^<<v2-37-22,22>>^ Os botões, os braços e o candelabro formavam uma só peça de ouro puro batido.

[[v2-37-23]]

^<<v2-37-23,23>>^ Bezalel também fez sete lamparinas para o candelabro; as tesouras de cortar os pavios das lamparinas e os cinzeiros eram de ouro puro.

[[v2-37-24]]

^<<v2-37-24,24>>^ Ele usou trinta e quatro quilos de ouro puro para fazer o candelabro e todas as peças que o acompanhavam.

[[v2-37-25]]

^<<v2-37-25,25>>^ Bezalel fez um altar de madeira de acácia para queimar incenso em cima dele. O altar era quadrado, medindo quarenta e cinco centímetros de comprimento por quarenta e cinco de largura; e tinha noventa centímetros de altura. As pontas, nos quatro cantos, formavam uma só peça com o altar.

[[v2-37-26]]

^<<v2-37-26,26>>^ Bezalel revestiu de ouro puro a tampa, os quatro lados e as pontas e colocou um remate de ouro em volta do altar.

[[v2-37-27]]

^<<v2-37-27,27>>^ Também fez duas argolas de ouro e as colocou debaixo do remate, uma de cada lado. Por dentro das argolas passavam os cabos que eram usados para carregar o altar.

[[v2-37-28]]

^<<v2-37-28,28>>^ Os cabos foram feitos de madeira de acácia e revestidos de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Bezalel preparou o azeite sagrado de ungir  e o incenso puro de cheiro agradável, misturado como perfume.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]