include::./index.adoc[]

[[v2-34-0]]
=== Êxodo, 34
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-34-1]]

^<<v2-34-1,1>>^ O Senhor  Deus disse a Moisés: — Corte duas placas de pedra iguais àquelas que você quebrou, e eu escreverei nelas as mesmas palavras que estavam nas primeiras.

[[v2-34-2]]

^<<v2-34-2,2>>^ Amanhã cedo esteja pronto para subir o monte Sinai a fim de se encontrar comigo ali no alto do monte.

[[v2-34-3]]

^<<v2-34-3,3>>^ Ninguém deverá subir com você; ninguém deverá estar em qualquer parte do monte. As ovelhas, as cabras e o gado não deverão ficar pastando perto do monte.

[[v2-34-4]]

^<<v2-34-4,4>>^ Então Moisés cortou outras duas placas de pedra, iguais às primeiras, e, no dia seguinte, como o Senhor  havia ordenado, ele se levantou bem cedo e subiu o monte Sinai, levando consigo as duas placas.

[[v2-34-5]]

^<<v2-34-5,5>>^ O Senhor  desceu numa nuvem, ficou ali com Moisés e disse qual era o seu nome, isto é, o Senhor .

[[v2-34-6]]

^<<v2-34-6,6>>^ Então Deus passou diante de Moisés e disse em voz alta: — Eu sou o Senhor , o Deus Eterno! Eu tenho compaixão e misericórdia, não fico irado  com facilidade, e a minha fidelidade e o meu amor são tão grandes, que não podem ser medidos.

[[v2-34-7]]

^<<v2-34-7,7>>^ Cumpro a minha promessa a milhares de gerações  e perdoo o mal e o pecado. Porém não deixo de castigar os seus filhos e até os netos, os bisnetos e os trinetos pelos pecados dos pais.

[[v2-34-8]]

^<<v2-34-8,8>>^ Moisés se ajoelhou, encostou o rosto no chão e adorou a Deus.

[[v2-34-9]]

^<<v2-34-9,9>>^ Ele disse: — Ó Senhor, se estás, de fato, contente comigo, eu te peço que vás conosco. Este povo é teimoso, mas perdoa o nosso pecado e a nossa maldade e aceita-nos como o teu povo.

[[v2-34-10]]

^<<v2-34-10,10>>^ O Senhor  Deus disse a Moisés: — Eu estou fazendo agora uma aliança  com o seu povo. Na presença deles farei maravilhas como nunca foram feitas em toda a terra e em nenhuma nação. Todo o povo verá que milagres eu, o Senhor , posso fazer, pois vou realizar uma coisa terrível em favor de vocês.

[[v2-34-11]]

^<<v2-34-11,11>>^ Obedeçam às leis  que estou dando a vocês hoje. Conforme vocês forem avançando, eu expulsarei os amorreus, os cananeus, os heteus, os perizeus, os heveus e os jebuseus.

[[v2-34-12]]

^<<v2-34-12,12>>^ Não façam nenhum acordo  com os moradores da terra para onde vocês vão, pois isso poderia ser uma armadilha mortal para vocês.

[[v2-34-13]]

^<<v2-34-13,13>>^ Pelo contrário, derrubem os altares deles, destruam as colunas do deus Baal  e cortem os postes da deusa Aserá .

[[v2-34-14]]

^<<v2-34-14,14>>^ — Não adorem nenhum outro deus, pois eu, o Senhor , me chamo Deus Exigente e exijo que vocês adorem somente a mim.

[[v2-34-15]]

^<<v2-34-15,15>>^ Não façam acordos com os moradores da terra que vai ser de vocês. Nos seus cultos eles adoram deuses pagãos e lhes oferecem sacrifícios . Eles vão convidar vocês para as suas reuniões religiosas, e vocês poderão ficar tentados a comer os alimentos que eles oferecem aos seus deuses.

[[v2-34-16]]

^<<v2-34-16,16>>^ Os filhos de vocês poderiam casar com mulheres estrangeiras, e elas fariam com que vocês fossem infiéis a mim e adorassem os deuses pagãos que elas adoram.

[[v2-34-17]]

^<<v2-34-17,17>>^ — Não façam deuses de metal, nem os adorem.

[[v2-34-18]]

^<<v2-34-18,18>>^ — Comemorem a Festa dos Pães sem Fermento . Como lhes ordenei, comam pão sem fermento  durante sete dias no mês de abibe , que é o tempo certo, pois foi nesse mês que vocês saíram do Egito.

[[v2-34-19]]

^<<v2-34-19,19>>^ — Todo primeiro filho é meu e também o primeiro filhote macho dos animais domésticos.

[[v2-34-20]]

^<<v2-34-20,20>>^ Mas, se vocês quiserem ficar com o primeiro filhote macho de uma jumenta, ofereçam-me um carneiro; se não quiserem, quebrem o pescoço do jumentinho. Para ficarem com todo primeiro filho de vocês, paguem o preço determinado . — Ninguém deverá aparecer diante de mim sem trazer uma oferta.

[[v2-34-21]]

^<<v2-34-21,21>>^ — Vocês têm seis dias para trabalhar, porém não trabalhem no sétimo dia, nem mesmo no tempo de arar ou de fazer a colheita.

[[v2-34-22]]

^<<v2-34-22,22>>^ — Comemorem a Festa da Colheita  quando começarem a fazer a primeira colheita do trigo. E comemorem a Festa das Barracas  no outono, quando vocês colherem as suas frutas.

[[v2-34-23]]

^<<v2-34-23,23>>^ — Três vezes por ano todos os homens israelitas deverão ir adorar a mim, o Senhor , o Deus do povo de Israel.

[[v2-34-24]]

^<<v2-34-24,24>>^ Eu vou expulsar as outras nações que estão diante de vocês e assim aumentarei o seu território; então ninguém tentará conquistar a terra de vocês durante as três festas, quando vocês vierem me adorar.

[[v2-34-25]]

^<<v2-34-25,25>>^ — Quando me oferecerem um animal em sacrifício, não tragam pão feito com fermento, nem guardem para o dia seguinte o que sobrar do animal oferecido na Festa da Páscoa .

[[v2-34-26]]

^<<v2-34-26,26>>^ — Todos os anos levem à casa do Senhor , seu Deus, os primeiros cereais que vocês colherem. — Não cozinhem um cabrito ou um carneirinho no leite da sua própria mãe .

[[v2-34-27]]

^<<v2-34-27,27>>^ O Senhor  Deus disse ainda a Moisés: — Escreva essas palavras porque é com base nelas que estou fazendo uma aliança com você e com o povo de Israel.

[[v2-34-28]]

^<<v2-34-28,28>>^ Moisés ficou ali com Deus, o Senhor , quarenta dias e quarenta noites e durante esse tempo não comeu nem bebeu nada. Ele escreveu nas placas de pedra as palavras da aliança, isto é, os dez mandamentos.

[[v2-34-29]]

^<<v2-34-29,29>>^ Quando Moisés desceu do monte Sinai, carregando as duas placas da aliança , o seu rosto estava brilhando, pois ele havia falado com Deus. Mas ele não sabia disso.

[[v2-34-30]]

^<<v2-34-30,30>>^ Arão e todo o povo ficaram com medo de chegar perto de Moisés quando viram o seu rosto brilhando.

[[v2-34-31]]

^<<v2-34-31,31>>^ Porém Moisés os chamou, e Arão e todos os líderes do povo chegaram perto dele, e ele falou com todos.

[[v2-34-32]]

^<<v2-34-32,32>>^ Depois disso todo o povo de Israel se reuniu em volta de Moisés, e ele lhes entregou todas as leis  que o Senhor  Deus lhe tinha dado no monte Sinai.

[[v2-34-33]]

^<<v2-34-33,33>>^ Quando Moisés acabou de falar com eles, ele cobriu o rosto com um véu.

[[v2-34-34]]

^<<v2-34-34,34>>^ Sempre que entrava na Tenda Sagrada  para falar com o Senhor , Moisés tirava o véu. Quando saía, ele contava ao povo de Israel tudo o que Deus lhe havia mandado dizer,

[[v2-34-35]]

^<<v2-34-35,35>>^ e o povo via que o seu rosto continuava brilhando. Porém Moisés cobria de novo o rosto com o véu até que entrava de novo na Tenda para falar com Deus.

'''

xref:002-exodo/002-exodo-033.adoc#v2-33-0[&#60; Capítulo Anterior] | <<v2-34-0,Topo>> | xref:002-exodo/002-exodo-035.adoc#v2-35-0[Próximo Capítulo &#62;]