include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-35-1]]

^<<v2-35-1,1>>^ Moisés reuniu todo o povo de Israel e lhe disse: — É isto o que o Senhor  mandou vocês fazerem:

[[v2-35-2]]

^<<v2-35-2,2>>^ vocês têm seis dias para trabalhar, porém o sétimo dia deve ser sagrado, um dia solene dedicado ao Senhor . Qualquer pessoa que fizer algum trabalho nesse dia deverá ser morta.

[[v2-35-3]]

^<<v2-35-3,3>>^ No sábado, nem mesmo acendam fogo nas suas casas.

[[v2-35-4]]

^<<v2-35-4,4>>^ Moisés disse a todo o povo de Israel: — É isto o que o Senhor  ordenou:

[[v2-35-5]]

^<<v2-35-5,5>>^ façam uma oferta ao Senhor . Quem quiser fazer isso deverá trazer uma oferta de ouro, prata ou bronze;

[[v2-35-6]]

^<<v2-35-6,6>>^ fios de lã azul, púrpura  e vermelha; linho fino; tecido feito de pelos de cabra;

[[v2-35-7]]

^<<v2-35-7,7>>^ peles de carneiro tingidas de vermelho e peles finas; madeira de acácia;

[[v2-35-8]]

^<<v2-35-8,8>>^ azeite para lamparinas; especiarias  para a preparação do azeite de ungir  e para o incenso de cheiro agradável;

[[v2-35-9]]

^<<v2-35-9,9>>^ pedras de ônix e outras pedras de valor para serem colocadas no manto sacerdotal  e no peitoral  do Grande Sacerdote .

[[v2-35-10]]

^<<v2-35-10,10>>^ — Todos os homens habilidosos deverão vir e fazer tudo o que o Senhor  mandou,

[[v2-35-11]]

^<<v2-35-11,11>>^ isto é, a Tenda , as suas coberturas (a de dentro e a de fora), os prendedores, as armações, as travessas, os postes e as bases;

[[v2-35-12]]

^<<v2-35-12,12>>^ a arca da aliança , os seus cabos de madeira, a sua tampa e a cortina para separar o Lugar Santíssimo  do Lugar Santo ;

[[v2-35-13]]

^<<v2-35-13,13>>^ a mesa, os seus cabos e todo o seu equipamento; os pães oferecidos a Deus;

[[v2-35-14]]

^<<v2-35-14,14>>^ o candelabro  e o seu equipamento; as lamparinas com o seu azeite;

[[v2-35-15]]

^<<v2-35-15,15>>^ o altar de queimar incenso e os seus cabos; o azeite de ungir ; o incenso cheiroso; a cortina para a entrada da Tenda;

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar de queimar as ofertas e a sua grelha de bronze; os cabos e o resto do equipamento do altar; a pia com o seu suporte;

[[v2-35-17]]

^<<v2-35-17,17>>^ a cortina do pátio, os seus postes e as suas bases; a cortina da entrada do pátio;

[[v2-35-18]]

^<<v2-35-18,18>>^ as estacas e as cordas da Tenda, e as estacas e as cordas do pátio;

[[v2-35-19]]

^<<v2-35-19,19>>^ e as roupas que os sacerdotes usarão quando servirem no Lugar Santo, isto é, as roupas sagradas de Arão e dos seus filhos.

[[v2-35-20]]

^<<v2-35-20,20>>^ Então o povo de Israel foi para casa,

[[v2-35-21]]

^<<v2-35-21,21>>^ e todos os que, de fato, queriam voltaram trazendo uma oferta para o Senhor , a fim de que a Tenda da Presença de Deus , o Senhor , fosse construída. Eles trouxeram tudo o que era necessário para a adoração e para fazer as roupas dos sacerdotes.

[[v2-35-22]]

^<<v2-35-22,22>>^ Vieram homens e mulheres, todos com muita boa vontade, e trouxeram fivelas, brincos, anéis, pulseiras e todo tipo de objetos de ouro. E essas ofertas foram dedicadas ao Senhor .

[[v2-35-23]]

^<<v2-35-23,23>>^ E também trouxeram como oferta linho fino, fios de lã azul, púrpura  e vermelha, tecido feito de pelos de cabra, peles de carneiro tingidas de vermelho e peles finas.

[[v2-35-24]]

^<<v2-35-24,24>>^ Todos os que podiam dar trouxeram prata e bronze como oferta ao Senhor , e também os que tinham madeira de acácia que podia ser usada para qualquer trabalho.

[[v2-35-25]]

^<<v2-35-25,25>>^ Todas as mulheres habilidosas trouxeram o que haviam feito: fios de linho fino e fios de lã azul, púrpura e vermelha.

[[v2-35-26]]

^<<v2-35-26,26>>^ Elas também fizeram tecidos de pelos de cabra.

[[v2-35-27]]

^<<v2-35-27,27>>^ Os líderes trouxeram pedras de ônix e outras pedras de valor para serem colocadas no manto sacerdotal  e no peitoral  do Grande Sacerdote .

[[v2-35-28]]

^<<v2-35-28,28>>^ E trouxeram também especiarias  e o azeite para as lamparinas, para ungir  e para o incenso cheiroso.

[[v2-35-29]]

^<<v2-35-29,29>>^ Todos os israelitas trouxeram de muita boa vontade as suas ofertas a Deus, o Senhor , para o trabalho que ele, por meio de Moisés, havia ordenado que fosse feito.

[[v2-35-30]]

^<<v2-35-30,30>>^ Moisés disse ao povo de Israel: — O Senhor  Deus escolheu Bezalel, filho de Uri e neto de Hur, da tribo  de Judá.

[[v2-35-31]]

^<<v2-35-31,31>>^ Deus o encheu com o seu Espírito e lhe deu inteligência, competência e habilidade para fazer todo tipo de trabalho artístico;

[[v2-35-32]]

^<<v2-35-32,32>>^ para fazer desenhos e trabalhar em ouro, prata e bronze;

[[v2-35-33]]

^<<v2-35-33,33>>^ para lapidar e montar pedras preciosas; para entalhar madeira; e para fazer todo tipo de artesanato.

[[v2-35-34]]

^<<v2-35-34,34>>^ O Senhor  deu a Bezalel e a Aoliabe, filho de Aisamaque, da tribo de Dã, o dom  de ensinar os outros.

[[v2-35-35]]

^<<v2-35-35,35>>^ Ele lhes deu habilidade para fazerem todos os trabalhos de gravador e de desenhista, para tecerem linho fino e fios de lã azul, púrpura  e vermelha e para fazerem outros tecidos. Eles têm habilidade para todo tipo de trabalho e para fazer desenhos.

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]