include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-14-1]]

^<<v2-14-1,1>>^ O Senhor  Deus disse a Moisés:

[[v2-14-2]]

^<<v2-14-2,2>>^ — Diga aos israelitas que voltem e acampem em frente de Pi-Hairote, entre Migdol e o mar Vermelho, perto de Baal-Zefom.

[[v2-14-3]]

^<<v2-14-3,3>>^ Assim o rei do Egito vai pensar que os israelitas estão andando sem rumo, perdidos no deserto.

[[v2-14-4]]

^<<v2-14-4,4>>^ Eu farei com que o rei continue teimoso e persiga vocês. Então eu derrotarei o rei e o seu exército, mostrando assim o meu poder. E os egípcios ficarão sabendo que eu sou Deus, o Senhor . E os israelitas obedeceram.

[[v2-14-5]]

^<<v2-14-5,5>>^ Quando contaram ao rei do Egito que os israelitas tinham fugido, ele e os seus funcionários mudaram de ideia e disseram: — Vejam só o que fizemos! Deixamos que os nossos escravos, os israelitas, fugissem de nós!

[[v2-14-6]]

^<<v2-14-6,6>>^ Então o rei mandou preparar o seu carro de guerra e o seu exército.

[[v2-14-7]]

^<<v2-14-7,7>>^ Ele saiu com todos os carros de guerra, incluindo os seiscentos melhores, que eram comandados pelos seus oficiais.

[[v2-14-8]]

^<<v2-14-8,8>>^ O Senhor  fez com que Faraó, rei do Egito, continuasse teimando, e ele foi atrás dos israelitas, que estavam saindo de maneira vitoriosa.

[[v2-14-9]]

^<<v2-14-9,9>>^ Os egípcios, com todos os seus cavalos, carros de guerra e cavaleiros, saíram atrás dos israelitas e os alcançaram onde eles estavam acampados, na beira do mar Vermelho, perto de Pi-Hairote e de Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ Quando os israelitas viram o rei e o seu exército marchando contra eles, ficaram apavorados e gritaram pedindo a ajuda de Deus, o Senhor .

[[v2-14-11]]

^<<v2-14-11,11>>^ E disseram a Moisés: — Será que não havia sepulturas no Egito? Por que você nos trouxe para morrermos aqui no deserto? Veja só o que você fez, nos tirando do Egito!

[[v2-14-12]]

^<<v2-14-12,12>>^ O que foi que lhe dissemos no Egito? Pedimos que nos deixasse em paz, trabalhando como escravos para os egípcios. Pois é melhor ser escravo dos egípcios do que morrer aqui no deserto!

[[v2-14-13]]

^<<v2-14-13,13>>^ Porém Moisés respondeu: — Não tenham medo. Fiquem firmes e vocês verão que o Senhor  vai salvá-los hoje. Nunca mais vocês vão ver esses egípcios.

[[v2-14-14]]

^<<v2-14-14,14>>^ Vocês não terão de fazer nada: o Senhor  lutará por vocês.

[[v2-14-15]]

^<<v2-14-15,15>>^ O Senhor  disse a Moisés: — Por que você está me pedindo ajuda? Diga ao povo que marche.

[[v2-14-16]]

^<<v2-14-16,16>>^ Levante o bastão e o estenda sobre o mar. A água se dividirá, e os israelitas poderão passar em terra seca, pelo meio do mar.

[[v2-14-17]]

^<<v2-14-17,17>>^ Eu farei com que os egípcios fiquem ainda mais teimosos, e eles entrarão no mar atrás dos israelitas. E eu ficarei famoso quando derrotar o rei do Egito, todo o seu exército, os seus carros de guerra e os seus cavaleiros.

[[v2-14-18]]

^<<v2-14-18,18>>^ Quando eu derrotar os egípcios, eles saberão que eu sou Deus, o Senhor .

[[v2-14-19]]

^<<v2-14-19,19>>^ Então o Anjo de Deus, que ia na frente dos israelitas, mudou de lugar e passou para trás. Também a coluna de nuvem saiu da frente deles e foi para trás,

[[v2-14-20]]

^<<v2-14-20,20>>^ ficando entre os egípcios e os israelitas. A nuvem era escura para os egípcios, porém iluminava o povo de Israel. Assim, durante a noite inteira, o exército egípcio não conseguiu chegar perto dos israelitas.

[[v2-14-21]]

^<<v2-14-21,21>>^ Moisés estendeu a mão sobre o mar, e Deus, o Senhor , com um vento leste muito forte, fez com que o mar recuasse. O vento soprou a noite inteira e fez o mar virar terra seca. As águas foram divididas,

[[v2-14-22]]

^<<v2-14-22,22>>^ e os israelitas passaram pelo mar em terra seca, com muralhas de água nos dois lados.

[[v2-14-23]]

^<<v2-14-23,23>>^ Os egípcios os perseguiram e foram atrás deles até o meio do mar com todos os seus cavalos, carros de guerra e cavaleiros.

[[v2-14-24]]

^<<v2-14-24,24>>^ Logo antes de amanhecer, da coluna de fogo e de nuvem o Senhor  olhou para o exército dos egípcios e fez com que eles ficassem apavorados.

[[v2-14-25]]

^<<v2-14-25,25>>^ Os carros de guerra andavam com grande dificuldade, pois Deus fez com que as rodas ficassem atoladas. Então os egípcios disseram: — Vamos fugir dos israelitas! O Senhor  está lutando a favor deles e contra nós.

[[v2-14-26]]

^<<v2-14-26,26>>^ Então o Senhor  Deus disse a Moisés: — Estenda a mão sobre o mar para que as águas voltem e cubram os egípcios, os seus carros de guerra e os seus cavaleiros.

[[v2-14-27]]

^<<v2-14-27,27>>^ Moisés estendeu a mão sobre o mar, e, quando amanheceu, o mar voltou ao normal. Os egípcios tentaram escapar das águas, porém o Senhor  os jogou dentro do mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ As águas voltaram e cobriram os carros de guerra, os cavaleiros e todo o exército egípcio que havia perseguido os israelitas no mar. E não sobrou nenhum egípcio com vida.

[[v2-14-29]]

^<<v2-14-29,29>>^ Mas os israelitas atravessaram o mar em terra seca, com muralhas de água nos dois lados.

[[v2-14-30]]

^<<v2-14-30,30>>^ Naquele dia o Senhor  salvou o povo de Israel dos egípcios, e os israelitas os viram mortos na praia.

[[v2-14-31]]

^<<v2-14-31,31>>^ Quando viram o poder com que o Senhor  havia derrotado os egípcios, os israelitas o temeram . E creram em Deus, o Senhor , e no seu servo  Moisés.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]