include::./index.adoc[]

[[v2-23-0]]
=== Êxodo, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-23-1]]

^<<v2-23-1,1>>^ — Não espalhe notícias falsas e não minta no tribunal para ajudar alguém.

[[v2-23-2]]

^<<v2-23-2,2>>^ Não siga a maioria quando ela faz o que é errado e não dê testemunho falso para ajudar a maioria a torcer a justiça.

[[v2-23-3]]

^<<v2-23-3,3>>^ Não faça injustiça, nem mesmo para favorecer o pobre.

[[v2-23-4]]

^<<v2-23-4,4>>^ — Se você vir o boi ou o jumento do seu inimigo andando perdido, leve-o de volta para ele.

[[v2-23-5]]

^<<v2-23-5,5>>^ Se o jumento dele cair debaixo da carga, não o deixe ali, mas ajude o dono a pôr o animal de pé.

[[v2-23-6]]

^<<v2-23-6,6>>^ — Quando um pobre comparecer ao tribunal, não cometa injustiça contra ele.

[[v2-23-7]]

^<<v2-23-7,7>>^ Não faça acusações falsas, nem condene à morte uma pessoa inocente. Pois eu condenarei aquele que fizer essas coisas más.

[[v2-23-8]]

^<<v2-23-8,8>>^ Não aceite dinheiro para torcer a justiça, pois esse dinheiro faz com que as pessoas fiquem cegas e não vejam o que é direito, prejudicando assim a causa daqueles que são inocentes.

[[v2-23-9]]

^<<v2-23-9,9>>^ — Não maltratem os estrangeiros que moram no meio de vocês. Vocês sabem como eles sofrem por serem estrangeiros, pois vocês foram estrangeiros no Egito.

[[v2-23-10]]

^<<v2-23-10,10>>^ — Durante seis anos você semeará as suas terras e colherá o que elas produzirem.

[[v2-23-11]]

^<<v2-23-11,11>>^ Porém no sétimo ano deixe que a terra descanse e não colha nada que crescer nela. Mas os pobres poderão comer o que crescer ali, e os animais selvagens comerão o que sobrar. Faça isso também com as suas plantações de uvas e de azeitonas.

[[v2-23-12]]

^<<v2-23-12,12>>^ — Trabalhe seis dias por semana, mas no sétimo dia não faça nenhum trabalho para que os seus escravos, os seus animais e os estrangeiros que trabalham para você possam descansar.

[[v2-23-13]]

^<<v2-23-13,13>>^ — Deem atenção a tudo o que eu, o Senhor , tenho dito a vocês. Não façam orações a outros deuses, nem mesmo falem os nomes deles.

[[v2-23-14]]

^<<v2-23-14,14>>^ — Três vezes por ano vocês comemorarão uma festa em minha honra.

[[v2-23-15]]

^<<v2-23-15,15>>^ No mês de abibe , o mês em que vocês saíram do Egito, comemorem a Festa dos Pães sem Fermento  como eu ordenei. Durante os sete dias da festa não comam pão feito com fermento. Que ninguém venha me adorar sem trazer uma oferta.

[[v2-23-16]]

^<<v2-23-16,16>>^ — Comemorem a Festa da Colheita  logo que vocês começarem a colher o que plantaram. — Comemorem a Festa das Barracas  no outono, quando vocês colherem as uvas e as frutas dos pomares.

[[v2-23-17]]

^<<v2-23-17,17>>^ Três vezes por ano, nessas três festas, todos os homens devem vir adorar a mim, o Senhor  Deus.

[[v2-23-18]]

^<<v2-23-18,18>>^ — Quando vocês oferecerem um animal em sacrifício  a mim, não me tragam pão feito com fermento. A gordura dos animais mortos nos sacrifícios, durante as minhas festas, deverá ser queimada no mesmo dia.

[[v2-23-19]]

^<<v2-23-19,19>>^ — Todos os anos tragam à casa do Senhor , seu Deus, os primeiros cereais que colherem. — Não cozinhem um cabrito ou um carneirinho no leite da sua própria mãe .

[[v2-23-20]]

^<<v2-23-20,20>>^ — Eu enviarei um anjo adiante de vocês para protegê-los na viagem e para levá-los ao lugar que lhes preparei.

[[v2-23-21]]

^<<v2-23-21,21>>^ Deem atenção e obedeçam ao anjo. Não se revoltem contra ele, pois ele age em meu nome e não perdoará revoltas.

[[v2-23-22]]

^<<v2-23-22,22>>^ Se vocês lhe obedecerem e fizerem tudo o que ele mandar, eu lutarei contra todos os inimigos de vocês.

[[v2-23-23]]

^<<v2-23-23,23>>^ O meu anjo irá adiante de vocês e os levará até a terra dos amorreus, dos heteus, dos perizeus, dos cananeus, dos heveus e dos jebuseus. E eu destruirei todos esses povos.

[[v2-23-24]]

^<<v2-23-24,24>>^ Não se curvem diante dos deuses deles, nem os adorem, e não sigam os seus costumes religiosos. Destruam os deuses deles e quebrem as colunas do deus Baal .

[[v2-23-25]]

^<<v2-23-25,25>>^ Se vocês adorarem a mim, o Senhor , seu Deus, eu os abençoarei, dando-lhes comida e água, e tirarei de vocês todas as doenças.

[[v2-23-26]]

^<<v2-23-26,26>>^ Na terra de vocês nenhuma mulher terá aborto, nem ficará sem ter filhos. E eu darei a vocês uma vida longa.

[[v2-23-27]]

^<<v2-23-27,27>>^ — Farei com que os povos que são contra vocês tenham medo de mim. Farei com que haja confusão entre os povos contra quem vocês vão lutar e farei com que os inimigos fujam de vocês.

[[v2-23-28]]

^<<v2-23-28,28>>^ Farei com que os seus inimigos fiquem apavorados. E, quando vocês forem avançando, eu expulsarei os heveus, os cananeus e os heteus.

[[v2-23-29]]

^<<v2-23-29,29>>^ Não os expulsarei num ano só; se eu fizesse isso, a terra ficaria deserta, e os animais selvagens se tornariam numerosos demais, prejudicando vocês.

[[v2-23-30]]

^<<v2-23-30,30>>^ Pelo contrário, eu expulsarei esses povos pouco a pouco, até que vocês se tornem mais numerosos e tomem posse da terra.

[[v2-23-31]]

^<<v2-23-31,31>>^ Farei com que os limites da terra de vocês vão desde o golfo de Ácaba até o rio Eufrates e do mar Mediterrâneo até o deserto. Eu lhes darei poder para dominarem os povos daquelas terras, e vocês irão avançando e os expulsando.

[[v2-23-32]]

^<<v2-23-32,32>>^ Não façam nenhum acordo  com eles, nem com os seus deuses.

[[v2-23-33]]

^<<v2-23-33,33>>^ Não deixem que esses povos vivam na terra de vocês. Se deixarem, eles farão com que vocês pequem contra mim. Se vocês adorarem os deuses deles, isso será uma armadilha mortal para vocês.

'''

xref:002-exodo/002-exodo-022.adoc#v2-22-0[&#60; Capítulo Anterior] | <<v2-23-0,Topo>> | xref:002-exodo/002-exodo-024.adoc#v2-24-0[Próximo Capítulo &#62;]