include::./index.adoc[]

[[v2-5-0]]
=== Êxodo, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-5-1]]

^<<v2-5-1,1>>^ Depois Moisés e Arão foram falar com o rei do Egito e disseram: — O Senhor , o Deus do povo de Israel, disse: "Deixe que o meu povo vá ao deserto a fim de fazer ali uma festa em minha honra."

[[v2-5-2]]

^<<v2-5-2,2>>^ — Quem é o Senhor ? — perguntou o rei. — Por que devo ouvi-lo e deixar que o povo de Israel vá ao deserto? Eu não conheço o Senhor  e não vou deixar que os israelitas saiam daqui.

[[v2-5-3]]

^<<v2-5-3,3>>^ Moisés e Arão responderam: — O Deus dos hebreus veio falar conosco. Por isso deixe-nos viajar três dias pelo deserto a fim de oferecermos sacrifícios  ao Senhor , nosso Deus. Se não formos, ele nos matará com doenças e na guerra.

[[v2-5-4]]

^<<v2-5-4,4>>^ Aí o rei do Egito disse a Moisés e a Arão: — Por que vocês estão atrapalhando o trabalho do povo? Façam com que aqueles escravos voltem ao trabalho!

[[v2-5-5]]

^<<v2-5-5,5>>^ Ele disse também: — Agora que há tantos israelitas no país, vocês querem que eles deixem de trabalhar?

[[v2-5-6]]

^<<v2-5-6,6>>^ Naquele mesmo dia o rei deu aos feitores e aos chefes de turmas a seguinte ordem:

[[v2-5-7]]

^<<v2-5-7,7>>^ — Daqui em diante vocês não vão mais dar palha ao povo, para fazer tijolos. Que eles mesmos ajuntem a palha.

[[v2-5-8]]

^<<v2-5-8,8>>^ Mas vocês exijam que eles façam a mesma quantidade de tijolos, nem um tijolo a menos. São uns preguiçosos e é por isso que gritam: "Vamos oferecer sacrifícios ao nosso Deus!"

[[v2-5-9]]

^<<v2-5-9,9>>^ Façam essa gente trabalhar mais duro ainda e os mantenham ocupados, a fim de que não tenham tempo de ouvir mentiras.

[[v2-5-10]]

^<<v2-5-10,10>>^ Então os feitores e os chefes de turmas saíram e foram dizer ao povo o seguinte: — O rei disse que não vai mais fornecer palha a vocês.

[[v2-5-11]]

^<<v2-5-11,11>>^ Ele manda que vocês vão ajuntar palha onde puderem achar. Mas terão de continuar fazendo a mesma quantidade de tijolos.

[[v2-5-12]]

^<<v2-5-12,12>>^ Por isso o povo se espalhou por toda a terra do Egito, ajuntando a palha que sobrava das colheitas.

[[v2-5-13]]

^<<v2-5-13,13>>^ Os feitores forçavam os israelitas a fazer todos os dias a mesma quantidade de tijolos que costumavam fazer quando recebiam palha.

[[v2-5-14]]

^<<v2-5-14,14>>^ Os feitores batiam nos israelitas chefes de turmas que haviam sido encarregados do trabalho e perguntavam: — Por que vocês não estão fazendo a mesma quantidade de tijolos que faziam antes?

[[v2-5-15]]

^<<v2-5-15,15>>^ Então os israelitas chefes de turmas foram se queixar ao rei. Eles disseram: — Por que é que o senhor nos trata assim, nós que somos seus empregados?

[[v2-5-16]]

^<<v2-5-16,16>>^ Agora não nos dão mais palha, mas exigem que continuemos fazendo tijolos! Além disso batem em nós; no entanto, os seus feitores é que são os culpados.

[[v2-5-17]]

^<<v2-5-17,17>>^ Mas o rei respondeu: — Vocês são uns preguiçosos e não querem trabalhar. É por isso que estão me pedindo que os deixe ir oferecer sacrifícios a Deus, o Senhor .

[[v2-5-18]]

^<<v2-5-18,18>>^ Voltem ao trabalho. Vocês não receberão palha, mas terão de fazer a mesma quantidade de tijolos.

[[v2-5-19]]

^<<v2-5-19,19>>^ Os israelitas chefes de turmas viram que estavam numa situação difícil, quando lhes foi dito que fizessem todos os dias a mesma quantidade de tijolos que faziam antes.

[[v2-5-20]]

^<<v2-5-20,20>>^ Depois de falarem com o rei, eles se encontraram com Moisés e Arão, que os estavam esperando,

[[v2-5-21]]

^<<v2-5-21,21>>^ e lhes disseram: — O Senhor  Deus está vendo o que vocês estão fazendo e os castigará; pois, por causa de vocês, o rei e os seus funcionários estão com ódio de nós. Vocês deram a eles um motivo para nos matarem!

[[v2-5-22]]

^<<v2-5-22,22>>^ Moisés falou outra vez com Deus, o Senhor . Ele disse: — Ó Senhor, por que tratas tão mal este povo? Por que me mandaste para cá?

[[v2-5-23]]

^<<v2-5-23,23>>^ Pois, desde que vim falar em teu nome com o rei do Egito, ele tem maltratado este povo. E tu não fizeste nada para ajudá-los.

'''

xref:002-exodo/002-exodo-004.adoc#v2-4-0[&#60; Capítulo Anterior] | <<v2-5-0,Topo>> | xref:002-exodo/002-exodo-006.adoc#v2-6-0[Próximo Capítulo &#62;]