include::./index.adoc[]

[[v2-21-0]]
=== Êxodo, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-21-1]]

^<<v2-21-1,1>>^ Deus ordenou a Moisés que desse aos israelitas estas leis :

[[v2-21-2]]

^<<v2-21-2,2>>^ — Se você comprar um escravo israelita, ele deverá trabalhar seis anos para você. Mas no sétimo ano ele ficará livre, sem ter de pagar nada.

[[v2-21-3]]

^<<v2-21-3,3>>^ Se ele era solteiro quando se tornou seu escravo, não levará a mulher quando for embora. Mas, se era casado, então poderá levar a mulher.

[[v2-21-4]]

^<<v2-21-4,4>>^ Se o dono do escravo lhe der uma mulher, e ela der à luz filhos e filhas, a mulher e os filhos serão do dono, e o escravo irá embora sozinho.

[[v2-21-5]]

^<<v2-21-5,5>>^ Se o escravo disser que ama a sua mulher, os seus filhos e o seu dono e não quiser ser posto em liberdade,

[[v2-21-6]]

^<<v2-21-6,6>>^ então o dono o levará ao lugar de adoração. Ali ele o encostará na porta ou no batente da porta e furará a orelha dele com um furador. Então ele será seu escravo por toda a vida.

[[v2-21-7]]

^<<v2-21-7,7>>^ — Se um homem vender a sua filha para ser escrava, ela não ficará livre como ficam os escravos do sexo masculino.

[[v2-21-8]]

^<<v2-21-8,8>>^ Se um homem a comprar e disser que quer casar com ela, mas depois não gostar dela, ele terá de vendê-la novamente ao pai dela. O seu dono não poderá vendê-la a estrangeiros, pois ele não agiu direito com ela.

[[v2-21-9]]

^<<v2-21-9,9>>^ Se alguém comprar uma escrava para fazê-la casar com seu filho, deverá tratá-la como se fosse sua filha.

[[v2-21-10]]

^<<v2-21-10,10>>^ Se um homem casar com uma segunda mulher, deverá continuar a dar à primeira a mesma quantidade de alimentos e de roupas e os mesmos direitos que ela possuía antes.

[[v2-21-11]]

^<<v2-21-11,11>>^ Se ele não cumprir essas três coisas, ela poderá sair livre, sem ter de pagar nada.

[[v2-21-12]]

^<<v2-21-12,12>>^ — Deverá ser morto todo aquele que ferir uma pessoa de modo que ela morra.

[[v2-21-13]]

^<<v2-21-13,13>>^ Porém, se foi apenas um acidente, não tendo havido intenção de matar, então aquele que matou deverá fugir para um lugar que eu escolherei e ali ele ficará livre.

[[v2-21-14]]

^<<v2-21-14,14>>^ Mas, se um homem ficar com raiva e matar outro de propósito, deverá ser morto, ainda que ele tenha fugido para o meu altar a fim de se salvar.

[[v2-21-15]]

^<<v2-21-15,15>>^ — Quem bater no pai ou na mãe será morto.

[[v2-21-16]]

^<<v2-21-16,16>>^ — Quem levar à força uma pessoa para vendê-la ou para ficar com ela como escrava será morto.

[[v2-21-17]]

^<<v2-21-17,17>>^ — Quem amaldiçoar o pai ou a mãe será morto.

[[v2-21-18]]

^<<v2-21-18,18>>^ — Se durante uma briga um homem ferir o outro com uma pedra ou com um soco, ele não será castigado se aquele que foi ferido não morrer. Mas, se este ficar de cama,

[[v2-21-19]]

^<<v2-21-19,19>>^ e mais tarde se levantar, e começar a andar fora da casa com a ajuda de uma bengala, então aquele que o feriu terá de pagar o tempo que o outro perdeu e também as despesas do tratamento.

[[v2-21-20]]

^<<v2-21-20,20>>^ — Se alguém ferir a pauladas o seu escravo, e ele morrer na hora, o que bateu será castigado. Mas, se o escravo morrer só um ou dois dias depois, o dono não será castigado. Pois a perda do escravo já é um castigo para o dono. Essa lei  vale também para as escravas.

[[v2-21-21]]

^<<v2-21-21,21>>^ — Se alguém ferir a pauladas o seu escravo, e ele morrer na hora, o que bateu será castigado. Mas, se o escravo morrer só um ou dois dias depois, o dono não será castigado. Pois a perda do escravo já é um castigo para o dono. Essa lei  vale também para as escravas.

[[v2-21-22]]

^<<v2-21-22,22>>^ — Se alguns homens estiverem brigando e ferirem uma mulher grávida, e por causa disso ela perder a criança, mas sem maior prejuízo para a sua saúde, aquele que a feriu será obrigado a pagar o que o marido dela exigir, de acordo com o que os juízes decidirem.

[[v2-21-23]]

^<<v2-21-23,23>>^ Mas, se a mulher for ferida gravemente, o castigo será vida por vida,

[[v2-21-24]]

^<<v2-21-24,24>>^ olho por olho, dente por dente, mão por mão, pé por pé,

[[v2-21-25]]

^<<v2-21-25,25>>^ queimadura por queimadura, ferimento por ferimento, machucadura por machucadura.

[[v2-21-26]]

^<<v2-21-26,26>>^ — Se alguém ferir o olho do seu escravo, e ele perder a vista, o escravo terá de ser libertado como pagamento pelo olho perdido. E, se alguém quebrar um dente do seu escravo, ele terá de ser libertado como pagamento pelo dente. Essa lei vale também para as escravas.

[[v2-21-27]]

^<<v2-21-27,27>>^ — Se alguém ferir o olho do seu escravo, e ele perder a vista, o escravo terá de ser libertado como pagamento pelo olho perdido. E, se alguém quebrar um dente do seu escravo, ele terá de ser libertado como pagamento pelo dente. Essa lei vale também para as escravas.

[[v2-21-28]]

^<<v2-21-28,28>>^ — Se um boi chifrar um homem ou uma mulher, e a pessoa morrer, o boi deverá ser morto a pedradas, e ninguém comerá a sua carne. Mas o dono do boi não será castigado.

[[v2-21-29]]

^<<v2-21-29,29>>^ Porém, se o boi tinha o costume de chifrar as pessoas, e o seu dono sabia disso e não o prendeu, e o boi matar algum homem ou alguma mulher, o boi será morto a pedradas. E o seu dono também será morto.

[[v2-21-30]]

^<<v2-21-30,30>>^ No entanto, se deixarem que o dono pague uma multa para salvar a sua vida, então ele terá de pagar tudo o que for exigido.

[[v2-21-31]]

^<<v2-21-31,31>>^ Se um boi matar um menino ou uma menina, o dono será julgado por esta mesma lei .

[[v2-21-32]]

^<<v2-21-32,32>>^ Se um boi chifrar um escravo ou uma escrava, o dono receberá como pagamento trinta barras de prata, e o boi será morto a pedradas.

[[v2-21-33]]

^<<v2-21-33,33>>^ — Se alguém tirar a tampa de um poço ou se cavar um poço e não o tapar, e nele cair um boi ou um jumento,

[[v2-21-34]]

^<<v2-21-34,34>>^ essa pessoa terá de pagar ao dono o preço do animal. Ela fará o pagamento em dinheiro, porém o animal morto será seu.

'''

xref:002-exodo/002-exodo-020.adoc#v2-20-0[&#60; Capítulo Anterior] | <<v2-21-0,Topo>> | xref:002-exodo/002-exodo-022.adoc#v2-22-0[Próximo Capítulo &#62;]