include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-30-1]]

^<<v2-30-1,1>>^ O Senhor  Deus disse a Moisés: — Faça também um altar de madeira de acácia para queimar incenso em cima dele.

[[v2-30-2]]

^<<v2-30-2,2>>^ Esse altar será quadrado, medindo quarenta e cinco centímetros de comprimento por quarenta e cinco de largura; e terá noventa centímetros de altura. Nos quatro cantos haverá pontas, que formarão uma só peça com o altar.

[[v2-30-3]]

^<<v2-30-3,3>>^ A tampa, os quatro lados e as pontas deverão ser revestidos de ouro puro. E ponha um remate de ouro em volta do altar.

[[v2-30-4]]

^<<v2-30-4,4>>^ Ponha também duas argolas de ouro debaixo do remate, uma de cada lado. Por dentro dessas argolas passarão os cabos com que se carregará o altar.

[[v2-30-5]]

^<<v2-30-5,5>>^ Esses cabos deverão ser feitos de madeira de acácia e revestidos de ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ Ponha o altar em frente da cortina que ficará diante da arca da aliança . Ali eu me encontrarei com você.

[[v2-30-7]]

^<<v2-30-7,7>>^ De manhã, quando Arão for cuidar das lamparinas, ele deverá queimar incenso cheiroso.

[[v2-30-8]]

^<<v2-30-8,8>>^ Ao anoitecer, quando for acender as lamparinas, ele deverá fazer a mesma coisa. Essa oferta de incenso continuará para sempre, de geração  em geração.

[[v2-30-9]]

^<<v2-30-9,9>>^ Nesse altar não ofereçam incenso comum, nem animais, nem cereais e não derramem ofertas de vinho sobre ele.

[[v2-30-10]]

^<<v2-30-10,10>>^ Uma vez por ano Arão fará uma cerimônia de purificação  do altar, pondo nas suas quatro pontas o sangue do animal sacrificado para tirar os pecados do povo. Isso deverá ser feito para sempre, uma vez por ano. Esse altar deverá ser completamente santo, separado para mim, o Senhor .

[[v2-30-11]]

^<<v2-30-11,11>>^ O Senhor  Deus disse a Moisés:

[[v2-30-12]]

^<<v2-30-12,12>>^ — Quando você fizer a contagem do povo, cada israelita me pagará uma certa quantia pela sua vida, para que não lhe aconteça nenhum desastre enquanto a contagem estiver sendo feita.

[[v2-30-13]]

^<<v2-30-13,13>>^ Cada pessoa que for contada deverá pagar a quantia de prata exigida , pesada de acordo com a tabela oficial. Esse pagamento é para mim, o Senhor .

[[v2-30-14]]

^<<v2-30-14,14>>^ Quem for contado, isto é, cada homem de vinte anos para cima, pagará essa quantia.

[[v2-30-15]]

^<<v2-30-15,15>>^ Quando pagarem pela sua vida, o rico não precisará pagar mais do que a quantia exigida, nem o pobre pagará menos.

[[v2-30-16]]

^<<v2-30-16,16>>^ Você receberá do povo de Israel essa prata e a usará para o serviço da Tenda da Minha Presença . Esse imposto será o pagamento pela vida dos israelitas, e eu lembrarei de protegê-los.

[[v2-30-17]]

^<<v2-30-17,17>>^ O Senhor  Deus disse a Moisés:

[[v2-30-18]]

^<<v2-30-18,18>>^ — Faça uma pia de bronze com a base também de bronze. Coloque a pia entre a Tenda  e o altar e ponha água dentro dela.

[[v2-30-19]]

^<<v2-30-19,19>>^ Arão e os seus filhos usarão essa água para lavar as mãos e os pés,

[[v2-30-20]]

^<<v2-30-20,20>>^ antes de entrarem na Tenda ou antes de chegarem perto do altar para apresentar a oferta de alimento. Assim eles não serão mortos.

[[v2-30-21]]

^<<v2-30-21,21>>^ Eles deverão lavar as mãos e os pés para que não morram. Essa é uma lei  que deverá ser obedecida para sempre por eles e pelos seus descendentes.

[[v2-30-22]]

^<<v2-30-22,22>>^ O Senhor  Deus disse a Moisés:

[[v2-30-23]]

^<<v2-30-23,23>>^ — Escolha as especiarias  mais cheirosas para fazer o azeite sagrado de ungir , seguindo a arte dos perfumistas. Em três litros e meio de azeite misture o seguinte: seis quilos de mirra  líquida, três quilos de canela, três quilos de cana cheirosa  e seis quilos de cássia, tudo pesado de acordo com a tabela oficial.

[[v2-30-24]]

^<<v2-30-24,24>>^ — Escolha as especiarias  mais cheirosas para fazer o azeite sagrado de ungir , seguindo a arte dos perfumistas. Em três litros e meio de azeite misture o seguinte: seis quilos de mirra  líquida, três quilos de canela, três quilos de cana cheirosa  e seis quilos de cássia, tudo pesado de acordo com a tabela oficial.

[[v2-30-25]]

^<<v2-30-25,25>>^ — Escolha as especiarias  mais cheirosas para fazer o azeite sagrado de ungir , seguindo a arte dos perfumistas. Em três litros e meio de azeite misture o seguinte: seis quilos de mirra  líquida, três quilos de canela, três quilos de cana cheirosa  e seis quilos de cássia, tudo pesado de acordo com a tabela oficial.

[[v2-30-26]]

^<<v2-30-26,26>>^ Use esse azeite para ungir a Tenda da Minha Presença , a arca da aliança ,

[[v2-30-27]]

^<<v2-30-27,27>>^ a mesa e todo o seu equipamento, o candelabro  e o seu equipamento, o altar de queimar incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ o altar de queimar ofertas, junto com todo o seu equipamento, e a pia com o seu suporte.

[[v2-30-29]]

^<<v2-30-29,29>>^ Assim você consagrará todas essas coisas, e elas ficarão completamente santas. E qualquer pessoa ou coisa que tocar nelas sofrerá por causa do poder da sua santidade.

[[v2-30-30]]

^<<v2-30-30,30>>^ Você ungirá também Arão e os filhos dele e os separará para me servirem como sacerdotes.

[[v2-30-31]]

^<<v2-30-31,31>>^ Diga ao povo de Israel o seguinte: "Esse azeite de ungir deverá ser usado para sempre no meu serviço religioso.

[[v2-30-32]]

^<<v2-30-32,32>>^ Não deverá ser usado no corpo de quem não for sacerdote. E vocês não deverão usar a fórmula desse azeite para qualquer outra mistura igual a essa. Esse azeite é sagrado e assim ele deverá ser tratado.

[[v2-30-33]]

^<<v2-30-33,33>>^ Qualquer pessoa que preparar um azeite igual a esse ou usá-lo em quem não for sacerdote deverá ser expulsa do meio do meu povo."

[[v2-30-34]]

^<<v2-30-34,34>>^ O Senhor  Deus disse a Moisés: — Faça o incenso sagrado conforme a arte dos perfumistas. Misture, em partes iguais, as seguintes especiarias  cheirosas: benjoim , ônica , resina medicinal e incenso puro. E ponha sal a fim de conservá-lo puro e santo.

[[v2-30-35]]

^<<v2-30-35,35>>^ O Senhor  Deus disse a Moisés:

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]