include::./index.adoc[]

[[v2-17-0]]
=== Êxodo, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-17-1]]

^<<v2-17-1,1>>^ O povo de Israel saiu do deserto de Sim, caminhando de um lugar para outro, de acordo com as ordens de Deus, o Senhor . Eles acamparam em Refidim, mas ali não havia água para beber.

[[v2-17-2]]

^<<v2-17-2,2>>^ Então reclamaram contra Moisés e lhe disseram: — Dê-nos água para beber. Moisés respondeu: — Por que vocês estão reclamando? Por que estão pondo o Senhor  à prova?

[[v2-17-3]]

^<<v2-17-3,3>>^ Mas o povo estava com muita sede e continuava reclamando e gritando contra Moisés. Eles diziam: — Por que você nos tirou do Egito? Será que foi para nos matar de sede, a nós, aos nossos filhos e às nossas ovelhas e cabras?

[[v2-17-4]]

^<<v2-17-4,4>>^ Então Moisés clamou pedindo a ajuda de Deus, o Senhor . Ele disse: — O que é que eu faço com este povo? Mais um pouco, e eles vão querer me matar a pedradas.

[[v2-17-5]]

^<<v2-17-5,5>>^ O Senhor  disse a Moisés: — Escolha entre eles alguns líderes e passe com eles na frente do povo. Leve também o bastão com o qual você bateu no rio Nilo.

[[v2-17-6]]

^<<v2-17-6,6>>^ Eu estarei diante de você em cima de uma rocha, ali no monte Sinai. Bata na rocha, e dela sairá água para o povo beber. E Moisés fez isso na presença dos líderes do povo de Israel.

[[v2-17-7]]

^<<v2-17-7,7>>^ Então deram àquele lugar os nomes de Massá e de Meribá , pois os israelitas reclamaram contra Moisés e puseram o Senhor  à prova, perguntando: — O Senhor  está com a gente ou não?

[[v2-17-8]]

^<<v2-17-8,8>>^ Os amalequitas vieram e atacaram os israelitas em Refidim.

[[v2-17-9]]

^<<v2-17-9,9>>^ Então Moisés deu a Josué a seguinte ordem: — Escolha alguns homens e amanhã cedo vá com eles lutar por nós contra os amalequitas. Eu ficarei no alto do monte, segurando o bastão de Deus.

[[v2-17-10]]

^<<v2-17-10,10>>^ Josué fez o que Moisés havia ordenado e foi combater os amalequitas. Enquanto isso, Moisés, Arão e Hur subiram até o alto do monte.

[[v2-17-11]]

^<<v2-17-11,11>>^ Quando Moisés ficava com os braços levantados, os israelitas venciam. Porém, quando ele abaixava os braços, eram os amalequitas que venciam.

[[v2-17-12]]

^<<v2-17-12,12>>^ Quando os braços de Moisés ficaram cansados, Arão e Hur pegaram uma pedra e a puseram perto dele para que Moisés se sentasse. E os dois, um de cada lado, seguravam os braços de Moisés. Desse modo os seus braços ficaram levantados até o pôr do sol.

[[v2-17-13]]

^<<v2-17-13,13>>^ E assim Josué derrotou completamente os amalequitas.

[[v2-17-14]]

^<<v2-17-14,14>>^ Então o Senhor  Deus disse a Moisés: — Escreva um relatório dessa vitória a fim de que ela seja lembrada. Diga a Josué que eu vou destruir completamente os amalequitas.

[[v2-17-15]]

^<<v2-17-15,15>>^ Moisés construiu um altar e lhe deu o seguinte nome: "O Senhor  Deus é a minha bandeira."

[[v2-17-16]]

^<<v2-17-16,16>>^ Depois disse: — Segurem bem alto a bandeira do Senhor ! O Senhor  combaterá para sempre os amalequitas!

'''

xref:002-exodo/002-exodo-016.adoc#v2-16-0[&#60; Capítulo Anterior] | <<v2-17-0,Topo>> | xref:002-exodo/002-exodo-018.adoc#v2-18-0[Próximo Capítulo &#62;]