include::./index.adoc[]

[[v2-8-0]]
=== Êxodo, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-8-1]]

^<<v2-8-1,1>>^ Depois o Senhor  Deus disse a Moisés: — Vá falar com o rei e diga que o Senhor  está dizendo a ele o seguinte: "Deixe que o meu povo saia do país a fim de me adorar.

[[v2-8-2]]

^<<v2-8-2,2>>^ Se você não deixar, eu castigarei o seu país, cobrindo-o de rãs.

[[v2-8-3]]

^<<v2-8-3,3>>^ O rio Nilo ficará cheio de rãs, e elas sairão dele e entrarão no palácio do rei, no seu quarto, na sua cama, nas casas dos seus funcionários e do seu povo e até dentro dos fornos e das bacias de amassar pão.

[[v2-8-4]]

^<<v2-8-4,4>>^ As rãs pularão em cima de você, do seu povo e de todos os seus funcionários."

[[v2-8-5]]

^<<v2-8-5,5>>^ O Senhor  Deus disse ainda a Moisés: — Diga a Arão que estenda o bastão sobre os rios, os canais e os poços e faça com que as rãs saiam das águas e cubram a terra do Egito.

[[v2-8-6]]

^<<v2-8-6,6>>^ Aí Arão estendeu a mão sobre as águas do Egito, e as rãs saíram das águas e cobriram todo o país.

[[v2-8-7]]

^<<v2-8-7,7>>^ Porém os mágicos, com as suas artes, fizeram a mesma coisa; eles também trouxeram rãs sobre a terra do Egito.

[[v2-8-8]]

^<<v2-8-8,8>>^ Então o rei mandou chamar Moisés e Arão e lhes disse: — Peçam ao Senhor  Deus que livre a mim e o meu povo dessas rãs, e eu deixarei que o seu povo vá e ofereça sacrifícios  a ele.

[[v2-8-9]]

^<<v2-8-9,9>>^ Moisés respondeu: — Terei muito prazer em levar o seu pedido. Diga quando é que o senhor quer que eu peça a Deus em seu favor, em favor dos seus funcionários e do seu povo, para que as rãs sumam do seu palácio e das casas e fiquem somente no rio.

[[v2-8-10]]

^<<v2-8-10,10>>^ O rei respondeu: — Orem por mim amanhã. E Moisés disse: — Ó rei, vou fazer como pediu, e assim o senhor ficará sabendo que não há outro deus como o Senhor , nosso Deus.

[[v2-8-11]]

^<<v2-8-11,11>>^ O senhor, os seus funcionários e o seu povo ficarão livres das rãs; só no rio Nilo é que haverá rãs.

[[v2-8-12]]

^<<v2-8-12,12>>^ Moisés e Arão saíram do palácio do rei. Depois Moisés pediu ao Senhor  Deus que retirasse as rãs que ele havia mandado contra o rei.

[[v2-8-13]]

^<<v2-8-13,13>>^ E o Senhor  atendeu o seu pedido: as rãs que estavam nas casas, nos quintais e nos campos morreram.

[[v2-8-14]]

^<<v2-8-14,14>>^ Os egípcios fizeram muitos montes de rãs, e um cheiro horrível se espalhou pelo país inteiro.

[[v2-8-15]]

^<<v2-8-15,15>>^ Quando o rei viu que as rãs tinham morrido, continuou teimando, como o Senhor  tinha dito, e não atendeu o pedido de Moisés e Arão.

[[v2-8-16]]

^<<v2-8-16,16>>^ O Senhor  Deus disse a Moisés: — Diga a Arão que bata na terra com o bastão para que em todo o Egito o pó vire piolhos.

[[v2-8-17]]

^<<v2-8-17,17>>^ E Arão bateu na terra com o bastão, e todo o pó do Egito virou piolhos, que cobriram as pessoas e os animais.

[[v2-8-18]]

^<<v2-8-18,18>>^ Os mágicos tentaram fazer aparecer piolhos, mas não conseguiram. E as pessoas e os animais continuaram cobertos de piolhos.

[[v2-8-19]]

^<<v2-8-19,19>>^ Então os mágicos disseram ao rei: — Foi Deus quem fez isso! Mas o rei continuou teimando, como o Senhor  tinha dito, e não atendeu o pedido de Moisés e Arão.

[[v2-8-20]]

^<<v2-8-20,20>>^ O Senhor  Deus disse a Moisés: — Amanhã cedo, quando o rei for até a beira do rio, vá falar com ele e diga-lhe que eu, o Senhor , digo o seguinte: "Deixe que o meu povo saia do país a fim de me adorar.

[[v2-8-21]]

^<<v2-8-21,21>>^ Se você não deixar, eu mandarei moscas para castigar você, os seus funcionários e o seu povo. As casas dos egípcios ficarão cheias de moscas, e o chão ficará coberto com elas.

[[v2-8-22]]

^<<v2-8-22,22>>^ Mas naquele dia separarei a região de Gosém, onde mora o meu povo, para que ali não haja moscas. Assim, você ficará sabendo que eu, o Senhor , estou aqui neste país.

[[v2-8-23]]

^<<v2-8-23,23>>^ Farei diferença entre o meu povo e o seu povo. Este milagre vai acontecer amanhã."

[[v2-8-24]]

^<<v2-8-24,24>>^ Assim fez Deus, o Senhor , e entraram grandes enxames de moscas no palácio do rei e nas casas dos seus funcionários. E, por causa das moscas, houve muito prejuízo no Egito inteiro.

[[v2-8-25]]

^<<v2-8-25,25>>^ Então o rei chamou Moisés e Arão e disse: — Vão oferecer sacrifícios  ao seu Deus, porém façam isso aqui mesmo, no Egito.

[[v2-8-26]]

^<<v2-8-26,26>>^ Moisés respondeu: — Isso não daria certo, pois os animais que oferecemos em sacrifício ao Senhor , nosso Deus, são sagrados para os egípcios. Se eles virem a gente matar os animais que eles adoram, com certeza nos matarão a pedradas.

[[v2-8-27]]

^<<v2-8-27,27>>^ Nós temos de caminhar três dias pelo deserto até chegarmos ao lugar onde vamos oferecer sacrifícios ao Senhor , nosso Deus, como ele mesmo nos ordenou.

[[v2-8-28]]

^<<v2-8-28,28>>^ Então o rei disse: — Se vocês não forem muito longe, eu os deixarei ir ao deserto oferecer sacrifícios ao Senhor , seu Deus. Orem também por mim.

[[v2-8-29]]

^<<v2-8-29,29>>^ Moisés respondeu: — Logo que eu sair daqui, vou orar a Deus para que estes enxames de moscas deixem o senhor, os seus funcionários e o seu povo. Mas o senhor não deve nos enganar outra vez, proibindo que o povo vá oferecer sacrifícios a Deus, o Senhor .

[[v2-8-30]]

^<<v2-8-30,30>>^ Então Moisés saiu do palácio e orou a Deus, o Senhor .

[[v2-8-31]]

^<<v2-8-31,31>>^ O Senhor  fez o que Moisés havia pedido: ele fez com que as moscas deixassem o rei, os seus funcionários e o seu povo. Não ficou uma só mosca.

[[v2-8-32]]

^<<v2-8-32,32>>^ Mas ainda dessa vez o rei continuou teimando e não deixou o povo ir.

'''

xref:002-exodo/002-exodo-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodo/002-exodo-009.adoc#v2-9-0[Próximo Capítulo &#62;]