include::./index.adoc[]

[[v2-33-0]]
=== Êxodo, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-33-1]]

^<<v2-33-1,1>>^ O Senhor  Deus disse a Moisés: — Saiam deste lugar, você e o povo que você tirou do Egito, e vão para a terra que eu jurei dar a Abraão, a Isaque, a Jacó e aos seus descendentes.

[[v2-33-2]]

^<<v2-33-2,2>>^ Eu mandarei um anjo para guiar você e expulsarei os cananeus, os amorreus, os heteus, os perizeus, os heveus e os jebuseus.

[[v2-33-3]]

^<<v2-33-3,3>>^ Vocês irão para uma terra boa e rica. Porém eu não irei, pois vocês são um povo teimoso, e eu os poderia destruir no caminho.

[[v2-33-4]]

^<<v2-33-4,4>>^ Quando Moisés deu essa mensagem aos israelitas, eles começaram a chorar, e ninguém usou as suas joias.

[[v2-33-5]]

^<<v2-33-5,5>>^ Então o Senhor  mandou que Moisés dissesse a eles: — Vocês são um povo teimoso. Se eu fosse junto com vocês, mesmo que fosse por apenas um momento, eu os destruiria completamente. Agora tirem as suas joias, e eu vou resolver o que fazer com vocês.

[[v2-33-6]]

^<<v2-33-6,6>>^ Assim, depois que os israelitas saíram do monte Sinai, não usaram mais joias.

[[v2-33-7]]

^<<v2-33-7,7>>^ Sempre que o povo de Israel acampava, Moisés costumava armar a Tenda Sagrada  a certa distância fora do acampamento. Ela era chamada de "Tenda da Presença de Deus", e quem quisesse consultar o Senhor  ia até lá.

[[v2-33-8]]

^<<v2-33-8,8>>^ Quando Moisés saía para ir à Tenda, o povo ficava na porta das suas barracas olhando Moisés até que ele entrasse.

[[v2-33-9]]

^<<v2-33-9,9>>^ Depois que ele entrava, uma coluna de nuvem descia e parava na porta da Tenda; e da nuvem o Senhor  falava com Moisés.

[[v2-33-10]]

^<<v2-33-10,10>>^ Logo que o povo via a coluna de nuvem na porta da Tenda, todos se ajoelhavam.

[[v2-33-11]]

^<<v2-33-11,11>>^ O Senhor  Deus falava com Moisés face a face, como alguém que conversa com um amigo. Depois Moisés voltava para o acampamento. Porém Josué, filho de Num, o moço que era o auxiliar de Moisés, ficava na Tenda.

[[v2-33-12]]

^<<v2-33-12,12>>^ Moisés disse a Deus, o Senhor : — É verdade que me mandaste guiar este povo para aquela terra, porém não me disseste quem é que irá comigo. Disseste que me conheces bem e que estás contente comigo.

[[v2-33-13]]

^<<v2-33-13,13>>^ Agora, se isso é assim mesmo, fala-me dos teus planos para que eu possa te servir e continuar a te agradar. Lembra que escolheste esta nação para ser tua.

[[v2-33-14]]

^<<v2-33-14,14>>^ Deus disse: — Eu irei com você e lhe darei a vitória.

[[v2-33-15]]

^<<v2-33-15,15>>^ Então Moisés respondeu: — Se não fores com o teu povo, não nos faças sair deste lugar.

[[v2-33-16]]

^<<v2-33-16,16>>^ Como é que os outros povos poderão saber que estás contente com o teu povo e comigo, se não fores conosco? A tua presença é que mostrará que somos diferentes dos outros povos da terra.

[[v2-33-17]]

^<<v2-33-17,17>>^ O Senhor  Deus disse a Moisés: — Vou atender o seu pedido porque conheço você bem, e você conseguiu a minha aprovação.

[[v2-33-18]]

^<<v2-33-18,18>>^ Aí Moisés suplicou: — Por favor, deixa que eu veja a tua glória .

[[v2-33-19]]

^<<v2-33-19,19>>^ Deus respondeu: — Eu farei com que todo o meu brilho passe diante de você e direi qual é o meu nome sagrado. Eu sou o Senhor  e terei compaixão de quem eu quiser e terei misericórdia de quem eu desejar.

[[v2-33-20]]

^<<v2-33-20,20>>^ E disse ainda: — Não vou deixar que você veja o meu rosto, pois ninguém pode ver o meu rosto e continuar vivo.

[[v2-33-21]]

^<<v2-33-21,21>>^ Mas aqui há um lugar perto de mim, onde você poderá ficar em cima de uma rocha.

[[v2-33-22]]

^<<v2-33-22,22>>^ Quando a minha glória passar, eu porei você numa rachadura da rocha e o cobrirei com a minha mão até que eu passe.

[[v2-33-23]]

^<<v2-33-23,23>>^ Depois tirarei a mão, e você me verá pelas costas, porém não verá o meu rosto.

'''

xref:002-exodo/002-exodo-032.adoc#v2-32-0[&#60; Capítulo Anterior] | <<v2-33-0,Topo>> | xref:002-exodo/002-exodo-034.adoc#v2-34-0[Próximo Capítulo &#62;]