include::./index.adoc[]

[[v2-13-0]]
=== Êxodo, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-13-1]]

^<<v2-13-1,1>>^ O Senhor  Deus disse a Moisés:

[[v2-13-2]]

^<<v2-13-2,2>>^ — Separe para mim todo primeiro filho. Todo primeiro filho homem dos israelitas e todo primeiro filhote macho dos animais domésticos são meus.

[[v2-13-3]]

^<<v2-13-3,3>>^ Moisés disse ao povo: — Lembrem deste dia, o dia em que vocês saíram do Egito, onde eram escravos. Este é o dia em que o Senhor  os tirou de lá pelo seu grande poder. Portanto, não comam pão feito com fermento.

[[v2-13-4]]

^<<v2-13-4,4>>^ Vocês estão saindo do Egito neste dia, no primeiro mês, o mês de abibe .

[[v2-13-5]]

^<<v2-13-5,5>>^ O Senhor  jurou aos seus antepassados que daria a vocês a terra dos cananeus, dos heteus, dos amorreus, dos heveus e dos jebuseus. É uma terra boa e rica. Quando ele os levar para aquela terra, vocês deverão comemorar essa festa religiosa no primeiro mês de cada ano.

[[v2-13-6]]

^<<v2-13-6,6>>^ Durante sete dias vocês comerão pão sem fermento ; e no sétimo dia haverá uma festa religiosa em honra do Senhor .

[[v2-13-7]]

^<<v2-13-7,7>>^ Nesses sete dias vocês comerão pão sem fermento. Em toda a sua terra não deverá haver fermento, nem pão feito com fermento.

[[v2-13-8]]

^<<v2-13-8,8>>^ Nesse dia vocês contarão aos seus filhos que estão fazendo isso por causa daquilo que o Senhor  fez por vocês quando saíram do Egito.

[[v2-13-9]]

^<<v2-13-9,9>>^ Essa festa será como um sinal para vocês, como se fosse uma coisa amarrada na mão ou na testa, e os ajudará a lembrarem de recitar e de estudar a lei  de Deus, o Senhor ; pois com grande poder ele os tirou do Egito.

[[v2-13-10]]

^<<v2-13-10,10>>^ Portanto, comemorem essa festa religiosa no dia certo, todos os anos.

[[v2-13-11]]

^<<v2-13-11,11>>^ — O Senhor  Deus fará com que vocês entrem na terra dos cananeus, conforme ele jurou a vocês e aos seus antepassados. Quando ele lhes der essa terra,

[[v2-13-12]]

^<<v2-13-12,12>>^ vocês darão ao Senhor  todo primeiro filho homem. Todo primeiro filhote macho também pertencerá a ele.

[[v2-13-13]]

^<<v2-13-13,13>>^ Mas, se quiserem ficar com o primeiro filhote macho de uma jumenta, ofereçam a Deus um carneiro; se não quiserem, quebrem o pescoço do jumentinho. Fiquem com todo primeiro filho homem de vocês, pagando por ele o preço determinado .

[[v2-13-14]]

^<<v2-13-14,14>>^ No futuro, quando os seus filhos perguntarem o que isso quer dizer, vocês responderão: "Com grande poder o Senhor  nos tirou do Egito, onde éramos escravos.

[[v2-13-15]]

^<<v2-13-15,15>>^ Quando o rei do Egito teimou em não nos deixar sair, o Senhor  matou todos os primeiros filhos no Egito, tanto das pessoas como dos animais. É por isso que oferecemos ao Senhor  em sacrifício  todo primeiro filhote macho. Mas pagamos o preço determinado para ficar com os nossos primeiros filhos.

[[v2-13-16]]

^<<v2-13-16,16>>^ Isso será como uma lembrança, como alguma coisa amarrada nas mãos ou na testa. E nos fará lembrar que com o seu grande poder o Senhor  nos tirou do Egito."

[[v2-13-17]]

^<<v2-13-17,17>>^ Quando o rei deixou que o povo israelita saísse do Egito, Deus não os levou pelo caminho que vai pelo país dos filisteus, embora fosse o mais curto. Deus pensou assim: "Não quero que os israelitas mudem de ideia e voltem para o Egito, quando virem que terão de guerrear."

[[v2-13-18]]

^<<v2-13-18,18>>^ Por isso Deus fez com que o povo desse uma volta pelo caminho do deserto, na direção do mar Vermelho. Os israelitas saíram do Egito armados para guerrear.

[[v2-13-19]]

^<<v2-13-19,19>>^ Moisés levou o corpo de José, pois José havia feito os israelitas jurarem que fariam isso. Ele tinha dito: "Quando Deus os libertar, levem daqui o meu corpo."

[[v2-13-20]]

^<<v2-13-20,20>>^ Os israelitas saíram de Sucote e acamparam em Etã, onde começa o deserto.

[[v2-13-21]]

^<<v2-13-21,21>>^ Durante o dia o Senhor  ia na frente deles numa coluna de nuvem, para lhes mostrar o caminho. Durante a noite ele ia na frente deles numa coluna de fogo, para iluminar o caminho, a fim de que pudessem andar de dia e de noite.

[[v2-13-22]]

^<<v2-13-22,22>>^ A coluna de nuvem sempre ia adiante deles durante o dia, e a coluna de fogo ia durante a noite.

'''

xref:002-exodo/002-exodo-012.adoc#v2-12-0[&#60; Capítulo Anterior] | <<v2-13-0,Topo>> | xref:002-exodo/002-exodo-014.adoc#v2-14-0[Próximo Capítulo &#62;]