include::./index.adoc[]

[[v2-7-0]]
=== Êxodo, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-7-1]]

^<<v2-7-1,1>>^ Então o Senhor  Deus disse a Moisés: — Vou fazer com que você seja como Deus para o rei; e Arão, o seu irmão, falará por você como profeta .

[[v2-7-2]]

^<<v2-7-2,2>>^ Você dirá a Arão tudo o que eu mandar, e ele falará com o rei, pedindo que deixe os israelitas saírem da terra dele.

[[v2-7-3]]

^<<v2-7-3,3>>^ Mas eu vou fazer com que o rei fique teimoso e farei muitos milagres e coisas espantosas no Egito.

[[v2-7-4]]

^<<v2-7-4,4>>^ O rei não vai ouvir vocês. Porém eu farei com que caia sobre ele um castigo terrível e levarei para fora do Egito os meus exércitos, isto é, o povo de Israel.

[[v2-7-5]]

^<<v2-7-5,5>>^ Quando eu levantar a mão contra os egípcios e tirar do meio deles os israelitas, os egípcios ficarão sabendo que eu sou o Senhor .

[[v2-7-6]]

^<<v2-7-6,6>>^ Moisés e Arão fizeram tudo como o Senhor  havia mandado.

[[v2-7-7]]

^<<v2-7-7,7>>^ Quando falaram com o rei do Egito, Moisés tinha oitenta anos, e Arão, oitenta e três.

[[v2-7-8]]

^<<v2-7-8,8>>^ O Senhor  Deus disse a Moisés e a Arão:

[[v2-7-9]]

^<<v2-7-9,9>>^ — Se o rei do Egito mandar que vocês façam um milagre, você, Moisés, dirá a Arão que pegue o bastão e o jogue no chão na frente do rei. O bastão virará uma cobra.

[[v2-7-10]]

^<<v2-7-10,10>>^ Aí Moisés e Arão foram se encontrar com o rei e fizeram como o Senhor  havia mandado. Arão jogou o bastão diante do rei e dos seus funcionários, e o bastão virou uma cobra.

[[v2-7-11]]

^<<v2-7-11,11>>^ Então o rei mandou vir os sábios e os mágicos, e com a sua mágica eles fizeram a mesma coisa.

[[v2-7-12]]

^<<v2-7-12,12>>^ Cada um deles jogou a sua vara de mágico no chão, e elas viraram cobras. Porém o bastão de Arão engoliu as varas de mágico deles.

[[v2-7-13]]

^<<v2-7-13,13>>^ No entanto, como o Senhor  tinha dito, o rei continuou teimando e não atendeu o pedido de Moisés e Arão.

[[v2-7-14]]

^<<v2-7-14,14>>^ Então o Senhor  Deus disse a Moisés: — O rei está teimando e não quer deixar o povo sair do Egito.

[[v2-7-15]]

^<<v2-7-15,15>>^ Vá procurá-lo amanhã cedo, quando ele for até o rio Nilo. Pegue o bastão que virou cobra e espere o rei na beira do rio.

[[v2-7-16]]

^<<v2-7-16,16>>^ E diga-lhe o seguinte: "O Senhor , o Deus dos hebreus, me mandou dizer-lhe que deixasse o povo dele ir embora para adorá-lo no deserto. Porém até agora o senhor não obedeceu à ordem de Deus.

[[v2-7-17]]

^<<v2-7-17,17>>^ Portanto, Deus lhe diz que, por causa daquilo que ele vai fazer agora, o senhor vai saber que ele é Deus, o Senhor . Ó rei, agora eu vou bater na água do rio com este bastão que estou segurando, e a água vai virar sangue.

[[v2-7-18]]

^<<v2-7-18,18>>^ Os peixes que estão no rio vão morrer, e o rio vai cheirar tão mal, que os egípcios terão nojo de beber água dele."

[[v2-7-19]]

^<<v2-7-19,19>>^ E o Senhor  disse também a Moisés: — Diga a Arão que pegue o bastão e estenda a mão sobre os rios, os canais, os poços e os reservatórios, para que as suas águas virem sangue. Assim, haverá sangue até nas tigelas de madeira e nas jarras de pedra.

[[v2-7-20]]

^<<v2-7-20,20>>^ Moisés e Arão fizeram como o Senhor  havia mandado. Na frente do rei e dos seus funcionários, Arão levantou o bastão e bateu no rio, e a água virou sangue.

[[v2-7-21]]

^<<v2-7-21,21>>^ Os peixes morreram, e o rio cheirou tão mal, que os egípcios não podiam beber água dele. E em todo o Egito houve sangue.

[[v2-7-22]]

^<<v2-7-22,22>>^ Porém, com as suas artes, os mágicos do Egito fizeram a mesma coisa. E assim o rei continuou teimando. Como o Senhor  tinha dito, ele não atendeu o pedido de Moisés e Arão.

[[v2-7-23]]

^<<v2-7-23,23>>^ Pelo contrário, ele voltou para o seu palácio, sem se preocupar com o que havia acontecido.

[[v2-7-24]]

^<<v2-7-24,24>>^ Todos os egípcios cavaram buracos na beira do rio para beber água limpa, pois não podiam beber da água do rio.

[[v2-7-25]]

^<<v2-7-25,25>>^ E passaram sete dias, depois que o Senhor  Deus bateu nas águas do rio.

'''

xref:002-exodo/002-exodo-006.adoc#v2-6-0[&#60; Capítulo Anterior] | <<v2-7-0,Topo>> | xref:002-exodo/002-exodo-008.adoc#v2-8-0[Próximo Capítulo &#62;]