include::./index.adoc[]

[[v2-40-0]]
=== Êxodo, 40
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-40-1]]

^<<v2-40-1,1>>^ O Senhor  Deus disse a Moisés:

[[v2-40-2]]

^<<v2-40-2,2>>^ — No dia primeiro do primeiro mês, arme a Tenda da Presença de Deus .

[[v2-40-3]]

^<<v2-40-3,3>>^ Coloque na Tenda a arca da aliança , onde estão guardadas as placas com os dez mandamentos; e ponha a cortina na frente da arca.

[[v2-40-4]]

^<<v2-40-4,4>>^ Ponha dentro da Tenda a mesa e coloque em ordem as coisas que estão sobre ela. Ponha dentro da Tenda o candelabro  e monte as lamparinas.

[[v2-40-5]]

^<<v2-40-5,5>>^ Ponha o altar de ouro para queimar incenso na frente da arca da aliança e pendure a cortina na entrada da Tenda.

[[v2-40-6]]

^<<v2-40-6,6>>^ E na frente da Tenda coloque o altar de queimar os sacrifícios .

[[v2-40-7]]

^<<v2-40-7,7>>^ Ponha a pia entre a Tenda e o altar e encha com água.

[[v2-40-8]]

^<<v2-40-8,8>>^ Depois arme o pátio ao redor da Tenda e pendure a cortina na sua entrada.

[[v2-40-9]]

^<<v2-40-9,9>>^ — Então pegue o azeite de ungir  e unja a Tenda e tudo o que estiver nela; desse modo, você a separará para mim, e ela ficará sagrada.

[[v2-40-10]]

^<<v2-40-10,10>>^ Depois você ungirá o altar das ofertas a ser completamente queimadas e todos os seus utensílios; assim o altar ficará separado para mim e será muito sagrado.

[[v2-40-11]]

^<<v2-40-11,11>>^ Do mesmo jeito você ungirá a pia com o seu suporte e a separará para mim.

[[v2-40-12]]

^<<v2-40-12,12>>^ — Leve Arão e os filhos dele para a entrada da Tenda e mande que se lavem.

[[v2-40-13]]

^<<v2-40-13,13>>^ Vista Arão com as suas roupas de sacerdote, unja-o e o separe para mim a fim de que me sirva como sacerdote.

[[v2-40-14]]

^<<v2-40-14,14>>^ Traga os filhos dele e vista neles as túnicas .

[[v2-40-15]]

^<<v2-40-15,15>>^ Em seguida você os ungirá, como ungiu o pai deles, para que me sirvam como sacerdotes. Isso fará com que sejam sacerdotes para sempre.

[[v2-40-16]]

^<<v2-40-16,16>>^ Moisés fez tudo como o Senhor  havia ordenado.

[[v2-40-17]]

^<<v2-40-17,17>>^ E assim, no dia primeiro do primeiro mês, quase um ano depois que os israelitas saíram do Egito, a Tenda da Presença de Deus foi armada.

[[v2-40-18]]

^<<v2-40-18,18>>^ Moisés colocou as bases, as armações e as travessas e levantou os postes.

[[v2-40-19]]

^<<v2-40-19,19>>^ Ele estendeu a cobertura sobre a Tenda e colocou a cobertura de fora por cima dela, como o Senhor  havia ordenado.

[[v2-40-20]]

^<<v2-40-20,20>>^ Depois pegou as duas placas de pedra e as colocou dentro da arca da aliança. Enfiou os cabos nas argolas da arca e colocou a tampa nela.

[[v2-40-21]]

^<<v2-40-21,21>>^ Então pôs a arca na Tenda e, como o Senhor  havia ordenado, pendurou a cortina entre o Lugar Santo  e o Lugar Santíssimo  para que ninguém pudesse ver a arca.

[[v2-40-22]]

^<<v2-40-22,22>>^ Moisés pôs a mesa na Tenda, no lado norte, do lado de fora da cortina,

[[v2-40-23]]

^<<v2-40-23,23>>^ e colocou sobre ela os pães oferecidos a Deus, o Senhor , como ele havia ordenado.

[[v2-40-24]]

^<<v2-40-24,24>>^ Moisés pôs o candelabro na Tenda, no lado sul, em frente da mesa

[[v2-40-25]]

^<<v2-40-25,25>>^ e ali, na presença do Senhor , ele acendeu as lamparinas, como o Senhor  havia ordenado.

[[v2-40-26]]

^<<v2-40-26,26>>^ Pôs o altar de ouro na Tenda, em frente da cortina,

[[v2-40-27]]

^<<v2-40-27,27>>^ e queimou o incenso cheiroso, como o Senhor  havia ordenado.

[[v2-40-28]]

^<<v2-40-28,28>>^ Pendurou a cortina na entrada da Tenda

[[v2-40-29]]

^<<v2-40-29,29>>^ e ali, em frente da cortina, colocou o altar para as ofertas que seriam completamente queimadas. Em cima do altar ele apresentou as ofertas a serem queimadas e as ofertas de cereais, como o Senhor  havia ordenado.

[[v2-40-30]]

^<<v2-40-30,30>>^ Pôs a pia entre a Tenda e o altar e a encheu com água.

[[v2-40-31]]

^<<v2-40-31,31>>^ Nela Moisés, Arão e os filhos de Arão lavavam os pés

[[v2-40-32]]

^<<v2-40-32,32>>^ todas as vezes que entravam na Tenda ou iam até o altar, como o Senhor  havia ordenado.

[[v2-40-33]]

^<<v2-40-33,33>>^ Moisés armou o pátio em volta da Tenda e do altar e pendurou a cortina na entrada do pátio. E assim ele terminou todo o trabalho.

[[v2-40-34]]

^<<v2-40-34,34>>^ Então a nuvem cobriu a Tenda , e ela ficou cheia da glória  de Deus, o Senhor ;

[[v2-40-35]]

^<<v2-40-35,35>>^ por isso Moisés não pôde entrar nela.

[[v2-40-36]]

^<<v2-40-36,36>>^ Os israelitas levavam o seu acampamento de um lugar para outro somente quando a nuvem se levantava de cima da Tenda.

[[v2-40-37]]

^<<v2-40-37,37>>^ Mas, se a nuvem não se levantava, os israelitas não saíam dali até o dia em que ela se levantava.

[[v2-40-38]]

^<<v2-40-38,38>>^ Em todas as suas viagens, eles podiam ver, durante o dia, a nuvem da presença do Senhor  em cima da Tenda; e, durante a noite, viam o fogo queimando em cima dela.

'''

xref:002-exodo/002-exodo-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-levitico/003-levitico-001.adoc#v3-1-0[Próximo Capítulo &#62;]