include::./index.adoc[]

[[v2-28-0]]
=== Êxodo, 28
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v2-28-1]]

^<<v2-28-1,1>>^ O Senhor  disse a Moisés: — Mande chamar o seu irmão Arão e os filhos dele, Nadabe, Abiú, Eleazar e Itamar. Separe-os do povo de Israel para que me sirvam como sacerdotes.

[[v2-28-2]]

^<<v2-28-2,2>>^ Faça roupas de sacerdote para o seu irmão a fim de darem a ele dignidade e beleza.

[[v2-28-3]]

^<<v2-28-3,3>>^ Chame todas as pessoas a quem eu dei habilidade e mande que façam as roupas de Arão, para que ele seja consagrado como meu sacerdote.

[[v2-28-4]]

^<<v2-28-4,4>>^ Mande que façam um peitoral , um manto sacerdotal , uma sobrepeliz , uma túnica  bordada, uma mitra  e um cinto. Essas pessoas farão roupas de sacerdote para o seu irmão Arão e os filhos dele, a fim de que eles me sirvam como sacerdotes.

[[v2-28-5]]

^<<v2-28-5,5>>^ Esses artesãos deverão usar fios de lã azul, púrpura  e vermelha, fios de ouro e linho fino.

[[v2-28-6]]

^<<v2-28-6,6>>^ — Os artesãos farão o manto sacerdotal  de fios de lã azul, púrpura  e vermelha, de linho fino e de fios de ouro e o enfeitarão com bordados.

[[v2-28-7]]

^<<v2-28-7,7>>^ Nas duas pontas do manto haverá duas alças que deverão ser presas nos dois lados do manto.

[[v2-28-8]]

^<<v2-28-8,8>>^ O cinto que passará pela cintura do manto para prendê-lo será feito dos mesmos materiais do manto, formando com ele uma só peça.

[[v2-28-9]]

^<<v2-28-9,9>>^ Pegue duas pedras de ágata  e grave nelas os nomes dos filhos de Jacó,

[[v2-28-10]]

^<<v2-28-10,10>>^ seis nomes numa pedra e seis nomes na outra, por ordem de idade.

[[v2-28-11]]

^<<v2-28-11,11>>^ Escolha um bom ourives para gravar nas duas pedras os nomes dos filhos de Jacó e para montar as pedras em engastes de ouro.

[[v2-28-12]]

^<<v2-28-12,12>>^ Coloque essas duas pedras nas alças do manto sacerdotal para representarem as doze tribos  do povo de Israel. Assim, Arão levará nos ombros esses nomes para que eu, o Senhor , sempre lembre do meu povo.

[[v2-28-13]]

^<<v2-28-13,13>>^ Faça dois engastes de ouro

[[v2-28-14]]

^<<v2-28-14,14>>^ e duas correntes de ouro puro entrelaçadas em forma de cordão, que você prenderá nos engastes.

[[v2-28-15]]

^<<v2-28-15,15>>^ — Faça um peitoral , que o Grande Sacerdote  usará para descobrir a vontade de Deus. Como o manto sacerdotal , o peitoral também será feito de fios de lã azul, púrpura  e vermelha e de linho fino enfeitado com bordados.

[[v2-28-16]]

^<<v2-28-16,16>>^ O peitoral será quadrado e dobrado em dois. Terá um palmo de comprimento e um palmo de largura.

[[v2-28-17]]

^<<v2-28-17,17>>^ Coloque nele quatro carreiras de pedras preciosas. Na primeira carreira ponha um rubi, um topázio  e uma granada .

[[v2-28-18]]

^<<v2-28-18,18>>^ Na segunda carreira ponha uma esmeralda, uma safira  e um diamante.

[[v2-28-19]]

^<<v2-28-19,19>>^ A terceira carreira terá uma turquesa, uma ágata  e uma ametista .

[[v2-28-20]]

^<<v2-28-20,20>>^ A quarta carreira terá um berilo , um ônix e um jaspe . As pedras deverão ser montadas em engastes de ouro.

[[v2-28-21]]

^<<v2-28-21,21>>^ Em cada uma dessas doze pedras será gravado o nome de um dos filhos de Jacó para representar as doze tribos  de Israel.

[[v2-28-22]]

^<<v2-28-22,22>>^ Com fios de ouro puro trançados faça cordões para o peitoral.

[[v2-28-23]]

^<<v2-28-23,23>>^ Faça também duas argolas de ouro e as prenda nas pontas da parte de cima do peitoral.

[[v2-28-24]]

^<<v2-28-24,24>>^ Passe os dois cordões de ouro nas duas argolas

[[v2-28-25]]

^<<v2-28-25,25>>^ e prenda as duas pontas dos cordões nos dois engastes de ouro do peitoral, que serão presos nas duas alças do manto, na parte da frente.

[[v2-28-26]]

^<<v2-28-26,26>>^ Faça outras duas argolas de ouro, que serão presas nas duas pontas de baixo do peitoral, na borda do lado de dentro do manto.

[[v2-28-27]]

^<<v2-28-27,27>>^ Faça ainda mais duas argolas de ouro e prenda-as nas pontas das duas alças do manto, em baixo, na frente dele, perto da costura e acima do cinto.

[[v2-28-28]]

^<<v2-28-28,28>>^ Com um cordão azul prenda as argolas do peitoral nas argolas do manto, para que o peitoral fique preso acima do cinto e não se solte.

[[v2-28-29]]

^<<v2-28-29,29>>^ — Quando entrar no Lugar Santo , Arão usará esse peitoral, gravado com os nomes das tribos do povo de Israel para que eu, o Senhor , sempre lembre do meu povo.

[[v2-28-30]]

^<<v2-28-30,30>>^ Ponha o Urim e o Tumim  no peitoral para que estejam em cima do coração de Arão quando ele estiver na minha presença. Nessas ocasiões Arão deverá usar o peitoral para que ele possa saber o que eu quero que o povo de Israel faça.

[[v2-28-31]]

^<<v2-28-31,31>>^ — A sobrepeliz, roupa que vai por cima do manto sacerdotal , será tecida inteiramente de fios de lã azul.

[[v2-28-32]]

^<<v2-28-32,32>>^ Nela haverá uma abertura para passar a cabeça. Essa abertura será rematada com uma tira de malha para que não se rasgue.

[[v2-28-33]]

^<<v2-28-33,33>>^ Em volta de toda a barra coloque aplicações em forma de romãs, feitas de fios de lã azul, púrpura  e vermelha. Entre uma romã e outra ponha sininhos de ouro.

[[v2-28-34]]

^<<v2-28-34,34>>^ Em volta de toda a barra coloque aplicações em forma de romãs, feitas de fios de lã azul, púrpura  e vermelha. Entre uma romã e outra ponha sininhos de ouro.

[[v2-28-35]]

^<<v2-28-35,35>>^ Arão deverá usar essa sobrepeliz quando estiver servindo como sacerdote, tanto quando estiver na minha presença no Lugar Santo  como quando sair dele. Nessas ocasiões, o som dos sininhos será ouvido, e Arão não será morto.

[[v2-28-36]]

^<<v2-28-36,36>>^ — Faça também uma placa de ouro puro e grave nela a seguinte frase: "Separado para o Senhor ."

[[v2-28-37]]

^<<v2-28-37,37>>^ Amarre essa placa na frente da mitra , com um cordão de lã azul.

[[v2-28-38]]

^<<v2-28-38,38>>^ Arão deverá usá-la na testa para que eu, o Senhor , aceite todas as ofertas que os israelitas me trouxerem, e para que eles não sejam culpados se cometerem algum erro ao oferecê-las a mim.

[[v2-28-39]]

^<<v2-28-39,39>>^ — Você tecerá para o sacerdote uma túnica  de linho fino, uma mitra de linho fino e um cinto bordado.

[[v2-28-40]]

^<<v2-28-40,40>>^ — Para os filhos de Arão faça túnicas, cintos e mitras a fim de lhes darem dignidade e beleza.

[[v2-28-41]]

^<<v2-28-41,41>>^ Com essas roupas vista o seu irmão Arão e os filhos dele. Depois consagre-os e dedique-os, derramando azeite na cabeça deles, para que me sirvam como sacerdotes.

[[v2-28-42]]

^<<v2-28-42,42>>^ Faça calções de linho para cobrir a nudez deles, calções que vão da cintura até as coxas.

'''

xref:002-exodo/002-exodo-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodo/002-exodo-029.adoc#v2-29-0[Próximo Capítulo &#62;]