include::./index.adoc[]

[[v7-5-0]]
=== Juízes, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-5-1]]

^<<v7-5-1,1>>^ Naquele dia Débora e Baraque, filho de Abinoão, cantaram assim:

[[v7-5-2]]

^<<v7-5-2,2>>^ Louvem a Deus, o Senhor ! Os israelitas resolveram lutar, e o povo se apresentou alegremente!

[[v7-5-3]]

^<<v7-5-3,3>>^ Ouçam, reis! Prestem atenção, governadores! Eu tocarei música e cantarei ao Senhor , o Deus de Israel!

[[v7-5-4]]

^<<v7-5-4,4>>^ Ó Senhor  Deus, quando saíste das montanhas de Seir, quando vieste da região de Edom, a terra tremeu, e as chuvas caíram do céu. Sim, caiu muita água das nuvens.

[[v7-5-5]]

^<<v7-5-5,5>>^ As montanhas tremeram diante do Senhor , o Deus do monte Sinai, diante do Senhor , o Deus de Israel.

[[v7-5-6]]

^<<v7-5-6,6>>^ Nos dias de Sangar, filho de Anate, nos dias de Jael, as estradas estavam desertas, e os viajantes usavam os desvios.

[[v7-5-7]]

^<<v7-5-7,7>>^ Nas cidades de Israel não havia ninguém; elas ficaram vazias até que você, Débora, veio, para ser mãe de Israel.

[[v7-5-8]]

^<<v7-5-8,8>>^ Os israelitas escolheram novos deuses, e então houve guerra no país. E dos quarenta mil homens de Israel nenhum carregava escudo  ou lança!

[[v7-5-9]]

^<<v7-5-9,9>>^ O meu coração está com os comandantes de Israel, com o povo que se ofereceu alegremente. Louvem a Deus, o Senhor !

[[v7-5-10]]

^<<v7-5-10,10>>^ Falem disso, vocês que montam jumentos brancos, sentados nas suas selas, e os que viajam a pé.

[[v7-5-11]]

^<<v7-5-11,11>>^ Escutem! A multidão barulhenta em volta dos poços está falando das vitórias do Senhor , das vitórias do povo de Israel! Então o povo do Senhor  desceu para as suas cidades.

[[v7-5-12]]

^<<v7-5-12,12>>^ Levante-se, Débora, levante-se! Levante-se! Cante uma canção! Levante-se! Marche, Baraque, filho de Abinoão, e leve presos os que o prenderam!

[[v7-5-13]]

^<<v7-5-13,13>>^ Então os que tinham fé foram para onde estavam os seus chefes, e o povo de Deus, o Senhor , pronto para lutar, foi encontrar-se com Baraque.

[[v7-5-14]]

^<<v7-5-14,14>>^ Eles saíram de Efraim e foram para o vale, atrás da tribo  de Benjamim e do seu povo. De Maquir desceram os comandantes, e de Zebulom vieram os oficiais.

[[v7-5-15]]

^<<v7-5-15,15>>^ Os chefes de Issacar foram com Débora. Sim, a tribo de Issacar foi, e Baraque também. Eles o seguiram até o vale. Mas a tribo de Rúben estava dividida; eles discutiram e não foram.

[[v7-5-16]]

^<<v7-5-16,16>>^ Por que resolveram ficar lá com as ovelhas? Será que foi para ouvir os pastores chamarem o rebanho? Sim, a tribo de Rúben estava dividida; eles discutiram e não foram.

[[v7-5-17]]

^<<v7-5-17,17>>^ A tribo de Gade ficou a leste do rio Jordão, e a tribo de Dã, nas pastagens. A tribo de Aser parou perto do mar e ficou na beira das praias.

[[v7-5-18]]

^<<v7-5-18,18>>^ Mas o povo de Zebulom e de Naftali arriscou a sua vida no campo de batalha.

[[v7-5-19]]

^<<v7-5-19,19>>^ Os reis vieram e lutaram em Taanaque, perto do riacho de Megido. Os reis de Canaã lutaram, mas não tomaram dos inimigos nenhuma prata.

[[v7-5-20]]

^<<v7-5-20,20>>^ Até as estrelas lutaram: enquanto caminhavam pelo céu, elas lutaram contra Sísera.

[[v7-5-21]]

^<<v7-5-21,21>>^ Os inimigos foram arrastados por uma enchente do rio Quisom, o velho rio Quisom. Eu marcharei, marcharei com firmeza!

[[v7-5-22]]

^<<v7-5-22,22>>^ Então os cavalos galoparam e galoparam, socando a terra com os seus cascos.

[[v7-5-23]]

^<<v7-5-23,23>>^ "Amaldiçoem a cidade de Meroz", diz o Anjo do Senhor ; "amaldiçoem, amaldiçoem os seus moradores, pois eles não vieram ajudar o Senhor , não vieram como soldados para lutar por ele."

[[v7-5-24]]

^<<v7-5-24,24>>^ A mais feliz das mulheres é Jael, a mulher de Héber, o queneu. Ela é a mais feliz das mulheres que vivem em barracas.

[[v7-5-25]]

^<<v7-5-25,25>>^ Sísera pediu água, porém ela lhe deu leite; trouxe nata para ele numa linda taça.

[[v7-5-26]]

^<<v7-5-26,26>>^ Pegou a estaca com uma das mãos e a marreta com a outra. Deu um golpe em Sísera e esmagou a sua cabeça; furou e quebrou a sua cabeça em pedaços.

[[v7-5-27]]

^<<v7-5-27,27>>^ Ele caiu de joelhos, tombou e ficou estendido a seus pés. A seus pés ele caiu de joelhos e tombou; ele caiu morto no chão.

[[v7-5-28]]

^<<v7-5-28,28>>^ A mãe de Sísera olhou pela janela da sua casa; olhou bem, pela grade da janela, e disse: "Por que o seu carro demora tanto para chegar? Por que os seus cavalos andam tão devagar?"

[[v7-5-29]]

^<<v7-5-29,29>>^ As suas acompanhantes mais sábias respondiam, e ela repetia para si mesma:

[[v7-5-30]]

^<<v7-5-30,30>>^ "Eles devem estar dividindo as coisas que tomaram: uma ou duas moças para cada soldado, roupas luxuosas para Sísera e panos bordados para o pescoço da rainha."

[[v7-5-31]]

^<<v7-5-31,31>>^ Assim, ó Senhor  Deus, morram todos os teus inimigos, porém que os teus amigos brilhem como a forte luz do sol nascente! E houve paz no país durante quarenta anos.

'''

xref:007-juizes/007-juizes-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-juizes/007-juizes-006.adoc#v7-6-0[Próximo Capítulo &#62;]