include::./index.adoc[]

[[v7-12-0]]
=== Juízes, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-12-1]]

^<<v7-12-1,1>>^ Os homens da tribo  de Efraim se reuniram para lutar. Eles atravessaram o rio Jordão para o lado de Zafom e disseram a Jefté: — Por que é que você saiu para combater os amonitas e não nos chamou para irmos também? Por causa disso nós vamos queimar a sua casa com você dentro!

[[v7-12-2]]

^<<v7-12-2,2>>^ Mas Jefté respondeu: — Eu e o meu povo tínhamos uma briga séria com os amonitas. Chamei vocês, mas vocês não me livraram deles.

[[v7-12-3]]

^<<v7-12-3,3>>^ Quando vi que vocês não iam me ajudar, arrisquei a vida e fui combater contra eles. E o Senhor  Deus me deu a vitória. Então por que é que vocês vêm agora lutar contra mim?

[[v7-12-4]]

^<<v7-12-4,4>>^ Aí Jefté juntou todos os homens de Gileade. Eles guerrearam contra os homens de Efraim e os derrotaram. Fizeram isso porque os efraimitas tinham dito: "Vocês, gileaditas que moram nas terras de Efraim e de Manassés, são desertores de Efraim."

[[v7-12-5]]

^<<v7-12-5,5>>^ Para não deixar que os efraimitas passassem, os gileaditas tomaram os lugares onde o rio Jordão podia ser atravessado. Quando algum efraimita que estava tentando escapar pedia para atravessar o rio, os homens de Gileade perguntavam: — Você é efraimita? Se ele respondia que não,

[[v7-12-6]]

^<<v7-12-6,6>>^ eles o mandavam dizer a palavra "Chibolete". Mas, se ele dizia "Sibolete" porque não podia falar direito a palavra, então o agarravam e matavam ali mesmo, na beira do rio Jordão. Naquela ocasião foram mortos quarenta e dois mil efraimitas.

[[v7-12-7]]

^<<v7-12-7,7>>^ Jefté, o gileadita, governou Israel durante seis anos. Então morreu e foi sepultado na sua cidade natal, em Gileade.

[[v7-12-8]]

^<<v7-12-8,8>>^ Depois de Jefté, Ibsã, da cidade de Belém, governou o povo de Israel.

[[v7-12-9]]

^<<v7-12-9,9>>^ Ele tinha trinta filhos e trinta filhas. Deixou que as trinta filhas casassem com rapazes de fora do seu grupo de famílias e trouxe trinta moças de fora para casarem com os seus filhos. Ibsã governou Israel sete anos.

[[v7-12-10]]

^<<v7-12-10,10>>^ Então morreu e foi sepultado em Belém.

[[v7-12-11]]

^<<v7-12-11,11>>^ Depois de Ibsã, Elom, que era da tribo  de Zebulom, governou Israel dez anos.

[[v7-12-12]]

^<<v7-12-12,12>>^ Então morreu e foi sepultado em Aijalom, na terra de Zebulom.

[[v7-12-13]]

^<<v7-12-13,13>>^ Depois de Elom, Abdom governou o povo de Israel. Ele era filho de Hilel, da cidade de Piratom.

[[v7-12-14]]

^<<v7-12-14,14>>^ Abdom tinha quarenta filhos e trinta netos, que montavam setenta jumentos. Ele governou Israel oito anos.

[[v7-12-15]]

^<<v7-12-15,15>>^ Então morreu e foi sepultado em Piratom, que fica na terra de Efraim, na região montanhosa dos amalequitas.

'''

xref:007-juizes/007-juizes-011.adoc#v7-11-0[&#60; Capítulo Anterior] | <<v7-12-0,Topo>> | xref:007-juizes/007-juizes-013.adoc#v7-13-0[Próximo Capítulo &#62;]