include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-6-1]]

^<<v7-6-1,1>>^ O povo de Israel pecou contra Deus, o Senhor , e por isso ele deixou que o povo de Midiã os dominasse durante sete anos.

[[v7-6-2]]

^<<v7-6-2,2>>^ Os israelitas se escondiam dos midianitas em cavernas e em outros lugares seguros nas montanhas porque os midianitas eram mais fortes do que eles.

[[v7-6-3]]

^<<v7-6-3,3>>^ Todas as vezes que os israelitas semeavam, os midianitas vinham com os amalequitas e os povos do deserto e os atacavam.

[[v7-6-4]]

^<<v7-6-4,4>>^ Acampavam na terra e destruíam as suas colheitas até o sul, perto de Gaza. Não deixavam nada para os israelitas viverem — nem ao menos uma ovelha, uma vaca ou um jumento.

[[v7-6-5]]

^<<v7-6-5,5>>^ Chegavam com o seu gado e as suas barracas e eram tão numerosos como gafanhotos. Eles e os seus camelos eram tantos, que nem dava para contar. Vinham para destruir a terra,

[[v7-6-6]]

^<<v7-6-6,6>>^ e o povo de Israel não podia com eles. Então os israelitas pediram socorro a Deus, o Senhor .

[[v7-6-7]]

^<<v7-6-7,7>>^ Quando eles oraram ao Senhor  por causa dos midianitas,

[[v7-6-8]]

^<<v7-6-8,8>>^ ele mandou um profeta , que lhes disse: — Assim diz o Senhor , o Deus de Israel: "Eu tirei vocês da escravidão do Egito.

[[v7-6-9]]

^<<v7-6-9,9>>^ Eu os livrei dos egípcios e dos que lutaram contra vocês aqui, nesta terra. Expulsei os seus inimigos e dei a vocês a terra deles.

[[v7-6-10]]

^<<v7-6-10,10>>^ Eu disse que sou o Senhor , o Deus de vocês, e que vocês não deviam adorar os deuses dos amorreus, que viviam nesta terra. Mas vocês não quiseram me ouvir."

[[v7-6-11]]

^<<v7-6-11,11>>^ Então o Anjo do Senhor  veio e sentou-se debaixo de um carvalho que havia perto do povoado de Ofra. Esse carvalho pertencia a Joás, que era da família de Abiezer. O seu filho, Gideão, estava malhando trigo no tanque de pisar uvas, escondido, para que os midianitas não o encontrassem.

[[v7-6-12]]

^<<v7-6-12,12>>^ Então o Anjo do Senhor  apareceu a ele e disse: — Você é corajoso, e o Senhor  está com você!

[[v7-6-13]]

^<<v7-6-13,13>>^ Gideão respondeu: — Se o Senhor  Deus está com o nosso povo, por que está acontecendo tudo isso com a gente? Onde estão aquelas coisas maravilhosas que os nossos antepassados nos contaram que o Senhor  costumava fazer quando nos trouxe do Egito? Ele nos abandonou e nos entregou aos midianitas.

[[v7-6-14]]

^<<v7-6-14,14>>^ Então o Senhor  Deus ordenou a Gideão: — Vá com toda a sua força e livre o povo de Israel dos midianitas. Sou eu quem está mandando que você vá.

[[v7-6-15]]

^<<v7-6-15,15>>^ Gideão respondeu: — Senhor, como posso libertar Israel? A minha família é a mais pobre da tribo  de Manassés, e eu sou a pessoa menos importante da minha família.

[[v7-6-16]]

^<<v7-6-16,16>>^ Mas o Senhor  disse: — Você pode fazer isso porque eu o ajudarei. Você esmagará todos os midianitas como se eles fossem um só homem.

[[v7-6-17]]

^<<v7-6-17,17>>^ Gideão respondeu: — Se tu estás contente comigo, então dá-me uma prova de que és tu mesmo que estás falando.

[[v7-6-18]]

^<<v7-6-18,18>>^ E, por favor, não vás embora até que eu te traga uma oferta. — Eu ficarei aqui até você voltar! — disse Deus.

[[v7-6-19]]

^<<v7-6-19,19>>^ Então Gideão entrou, cozinhou um cabrito e fez pão sem fermento  com mais ou menos dez quilos de farinha. Pôs a comida numa cesta e pôs o caldo numa panela. Levou tudo e entregou ao Anjo do Senhor , que estava debaixo do carvalho.

[[v7-6-20]]

^<<v7-6-20,20>>^ Então o Anjo ordenou: — Ponha a carne e o pão nesta pedra e derrame o caldo em cima. Gideão fez o que ele mandou.

[[v7-6-21]]

^<<v7-6-21,21>>^ Em seguida o Anjo estendeu o bastão que tinha na mão e tocou com a sua ponta a carne e o pão. Então saiu fogo da pedra e queimou a carne e o pão. E o Anjo desapareceu.

[[v7-6-22]]

^<<v7-6-22,22>>^ Aí Gideão compreendeu que era mesmo o Anjo do Senhor  que ele tinha visto. E disse, apavorado: — Ai de mim, Senhor , meu Deus! Eu vi o Anjo do Senhor  face a face!

[[v7-6-23]]

^<<v7-6-23,23>>^ Mas o Senhor  respondeu: — Não fique com medo. Tudo está bem. Você não morrerá.

[[v7-6-24]]

^<<v7-6-24,24>>^ Gideão construiu ali um altar para Deus, o Senhor , e o chamou de "O Senhor  é paz". E até hoje  esse altar está em Ofra, cidade que pertence às famílias de Abiezer.

[[v7-6-25]]

^<<v7-6-25,25>>^ Naquela noite o Senhor  disse a Gideão: — Leve o touro que pertence a seu pai e outro touro de sete anos e derrube o altar do deus Baal  que é do seu pai e também o poste da deusa Aserá  que está ao seu lado.

[[v7-6-26]]

^<<v7-6-26,26>>^ Nesse lugar alto e seguro, faça para o Senhor , seu Deus, um altar de pedras bem-arrumadas. Depois pegue o segundo touro e a madeira do poste de Aserá arrancado e queime tudo no altar como sacrifício .

[[v7-6-27]]

^<<v7-6-27,27>>^ Gideão levou dez dos seus empregados e fez o que o Senhor  tinha dito. Porém, como estava com medo da sua família e do povo da cidade, em vez de fazer isso de dia, fez de noite.

[[v7-6-28]]

^<<v7-6-28,28>>^ De madrugada, quando os homens da cidade se levantaram, acharam o altar de Baal  e o poste da deusa Aserá derrubados e o segundo touro queimado no altar que tinha sido construído ali.

[[v7-6-29]]

^<<v7-6-29,29>>^ E perguntavam: — Quem será que fez isso? Procuraram saber e descobriram que tinha sido Gideão, filho de Joás.

[[v7-6-30]]

^<<v7-6-30,30>>^ Então disseram a Joás: — Traga o seu filho aqui para ser morto, porque ele derrubou o altar de Baal e o poste da deusa Aserá.

[[v7-6-31]]

^<<v7-6-31,31>>^ Mas Joás disse a todos os que estavam ali reunidos contra ele: — Vocês estão defendendo Baal? Quem o defender será morto antes do amanhecer. Se Baal é deus, que ele mesmo se defenda. O altar dele é que foi derrubado.

[[v7-6-32]]

^<<v7-6-32,32>>^ Daquele dia em diante, Gideão passou a ser chamado de Jerubaal , pois Joás tinha dito: "Que Baal mesmo se defenda. O altar dele é que foi derrubado."

[[v7-6-33]]

^<<v7-6-33,33>>^ Então todos os midianitas, os amalequitas e os povos do deserto se juntaram, e atravessaram o rio Jordão, e acamparam no vale de Jezreel.

[[v7-6-34]]

^<<v7-6-34,34>>^ E o Espírito do Senhor  dominou Gideão. Ele tocou uma corneta feita de chifre de carneiro, e os homens do grupo de famílias de Abiezer foram juntar-se a ele.

[[v7-6-35]]

^<<v7-6-35,35>>^ Gideão enviou também mensageiros para chamar os homens das tribos  de Manassés, de Aser, de Zebulom e de Naftali. E eles também foram se juntar a ele.

[[v7-6-36]]

^<<v7-6-36,36>>^ Então Gideão disse: — Ó Deus, tu disseste que queres me usar para libertar o povo de Israel.

[[v7-6-37]]

^<<v7-6-37,37>>^ Pois bem. Vou pôr um pouco de lã no lugar onde malhamos o trigo. Se de manhã o orvalho tiver molhado somente a lã, e o chão em volta dela estiver seco, então poderei ficar certo de que tu realmente me usarás para libertar Israel.

[[v7-6-38]]

^<<v7-6-38,38>>^ O que ele disse aconteceu. Na manhã seguinte Gideão se levantou, espremeu a lã, e dela saiu água que deu para encher uma tigela.

[[v7-6-39]]

^<<v7-6-39,39>>^ Então ele pediu a Deus: — Não fiques zangado comigo. Mas deixa que eu fale só mais uma vez. Deixa, por favor, que eu faça mais uma prova com a lã. Que desta vez a lã fique seca, e que haja orvalho somente no chão em volta dela!

[[v7-6-40]]

^<<v7-6-40,40>>^ E Deus fez isso naquela noite. A lã ficou seca, e o chão em volta ficou coberto de orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]