include::./index.adoc[]

[[v7-19-0]]
=== Juízes, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-19-1]]

^<<v7-19-1,1>>^ Naqueles dias em que Israel não tinha rei, um levita  foi morar bem longe, na região montanhosa de Efraim. Ele arranjou uma jovem de Belém de Judá para ser a sua concubina .

[[v7-19-2]]

^<<v7-19-2,2>>^ Porém ela brigou com ele e voltou para a casa do seu pai, em Belém. E ficou lá durante quatro meses.

[[v7-19-3]]

^<<v7-19-3,3>>^ Então o homem resolveu ir a Belém atrás dela, para tentar convencê-la a voltar. Ele foi com o seu empregado e levou dois jumentos. E a moça o recebeu na casa do seu pai. Quando o pai da moça viu o levita, recebeu-o com alegria

[[v7-19-4]]

^<<v7-19-4,4>>^ e insistiu para que ficasse na sua casa. E ele ficou ali três dias. Assim o casal tomou as suas refeições e passou as noites ali.

[[v7-19-5]]

^<<v7-19-5,5>>^ No quarto dia eles se levantaram cedo e se aprontaram para ir embora. Mas o pai da moça disse ao levita: — Coma alguma coisa antes de ir e assim você se sentirá melhor. Você pode ir mais tarde.

[[v7-19-6]]

^<<v7-19-6,6>>^ Então os dois homens se sentaram, e comeram, e beberam juntos. Aí o pai da moça disse: — Por favor, fique mais uma noite e divirta-se.

[[v7-19-7]]

^<<v7-19-7,7>>^ O homem se levantou para sair, mas o pai da moça insistiu muito que ele ficasse. E assim o levita passou outra noite ali.

[[v7-19-8]]

^<<v7-19-8,8>>^ No quinto dia, bem cedo, ele se levantou para ir, mas o pai da moça pediu: — Por favor, coma alguma coisa. Espere até mais tarde. E os dois homens comeram juntos.

[[v7-19-9]]

^<<v7-19-9,9>>^ Quando o homem, a moça e o empregado iam saindo, o pai disse: — Olhe! Agora já é quase noite. É melhor você ficar para passar a noite aqui. Logo vai ficar escuro. Fique aqui e divirta-se. Amanhã você poderá se levantar cedo e viajar de volta para casa.

[[v7-19-10]]

^<<v7-19-10,10>>^ Mas o levita não quis passar lá mais outra noite e partiu de viagem com a sua concubina, levando dois jumentos arreados. Já era quase noite quando chegaram perto da cidade de Jebus, isto é, Jerusalém. Então o empregado disse ao patrão: — Por que não paramos e passamos a noite nesta cidade dos jebuseus ?

[[v7-19-11]]

^<<v7-19-11,11>>^ Mas o levita não quis passar lá mais outra noite e partiu de viagem com a sua concubina, levando dois jumentos arreados. Já era quase noite quando chegaram perto da cidade de Jebus, isto é, Jerusalém. Então o empregado disse ao patrão:

[[v7-19-12]]

^<<v7-19-12,12>>^ Mas o patrão respondeu: — Não vamos parar numa cidade onde o povo não é israelita. Vamos continuar até Gibeá.

[[v7-19-13]]

^<<v7-19-13,13>>^ É melhor a gente andar mais um pouco e passar a noite em Gibeá ou Ramá.

[[v7-19-14]]

^<<v7-19-14,14>>^ Então passaram pela cidade de Jebus e continuaram a viagem. O sol já se havia escondido quando eles chegaram a Gibeá, cidade da tribo  de Benjamim.

[[v7-19-15]]

^<<v7-19-15,15>>^ Aí saíram da estrada para passar a noite na cidade. O levita chegou e se sentou na praça. Mas ninguém o convidou para dormir na sua casa.

[[v7-19-16]]

^<<v7-19-16,16>>^ E aconteceu que passou por ali um velho que estava voltando do seu trabalho na roça. Ele era da região montanhosa de Efraim, mas estava morando em Gibeá. O povo dali era da tribo de Benjamim.

[[v7-19-17]]

^<<v7-19-17,17>>^ O velho viu o viajante na praça e perguntou: — De onde você é? Para onde vai?

[[v7-19-18]]

^<<v7-19-18,18>>^ O levita respondeu: — Eu estou viajando de Belém de Judá para bem longe, para a região montanhosa de Efraim, onde moro. Fui a Belém e agora estou voltando para casa, mas ninguém me ofereceu hospedagem para esta noite.

[[v7-19-19]]

^<<v7-19-19,19>>^ Nós temos alimento e palha para os jumentos, e pão e vinho para mim, para a minha concubina e para o meu empregado. Temos tudo o que precisamos.

[[v7-19-20]]

^<<v7-19-20,20>>^ O velho disse: — Venham comigo; vocês serão bem-recebidos na minha casa. Eu cuidarei de vocês. Por favor, não passem a noite na praça.

[[v7-19-21]]

^<<v7-19-21,21>>^ Então ele os levou para a sua casa e deu de comer aos jumentos. Os seus hóspedes lavaram os pés, comeram e beberam.

[[v7-19-22]]

^<<v7-19-22,22>>^ Enquanto eles conversavam alegremente, alguns homens imorais daquela cidade cercaram a casa e começaram a bater na porta. E disseram ao velho: — Traga para fora o homem que está na sua casa! Nós queremos ter relações com ele.

[[v7-19-23]]

^<<v7-19-23,23>>^ Aí o velho saiu e disse: — Não, meus amigos! Por favor, não façam essa coisa tão má e tão imoral! Este homem é meu hóspede.

[[v7-19-24]]

^<<v7-19-24,24>>^ Olhem! Estão aqui a minha filha virgem e a concubina dele. Eu vou pôr as duas para fora, e vocês poderão fazer com elas o que quiserem. Mas não façam essa coisa horrível com este homem!

[[v7-19-25]]

^<<v7-19-25,25>>^ Mas eles não quiseram ouvi-lo. Então o levita pegou a sua concubina, a pôs para fora e a entregou a eles. E eles a forçaram, e abusaram dela a noite toda, e só a deixaram de manhã.

[[v7-19-26]]

^<<v7-19-26,26>>^ Ao amanhecer a mulher veio e caiu na frente da casa onde o seu marido estava. E ficou ali até clarear o dia.

[[v7-19-27]]

^<<v7-19-27,27>>^ De manhã o marido se levantou para continuar a viagem. Quando abriu a porta, achou a sua concubina caída em frente da casa, com as mãos na soleira da porta.

[[v7-19-28]]

^<<v7-19-28,28>>^ Aí lhe disse: — Levante-se! Vamos embora! Porém não teve resposta. Então pôs o corpo dela atravessado sobre o jumento e seguiu viagem para casa.

[[v7-19-29]]

^<<v7-19-29,29>>^ Quando chegou lá, entrou, pegou uma faca e cortou o corpo da concubina em doze pedaços. Depois mandou um pedaço para cada uma das doze tribos de Israel.

'''

xref:007-juizes/007-juizes-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-juizes/007-juizes-020.adoc#v7-20-0[Próximo Capítulo &#62;]