include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-1-1]]

^<<v7-1-1,1>>^ Depois que Josué morreu, o povo de Israel perguntou a Deus, o Senhor : — Qual das nossas tribos  vai ser a primeira a atacar os cananeus?

[[v7-1-2]]

^<<v7-1-2,2>>^ O Senhor  respondeu: — O povo de Judá vai primeiro porque eu lhe dei a terra.

[[v7-1-3]]

^<<v7-1-3,3>>^ Então o povo de Judá disse ao povo de Simeão: — Vamos juntos à terra que nos foi dada e lutemos contra os cananeus. Depois iremos juntos à terra que for dada a vocês. Assim as tribos de Simeão

[[v7-1-4]]

^<<v7-1-4,4>>^ e de Judá foram guerrear juntas. E o Senhor  Deus lhes deu a vitória sobre os cananeus e os perizeus, e eles mataram dez mil homens em Bezeque.

[[v7-1-5]]

^<<v7-1-5,5>>^ Nesse lugar encontraram Adoni-Bezeque e lutaram contra ele. E eles derrotaram os cananeus e os perizeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Adoni-Bezeque fugiu, mas eles o perseguiram e prenderam. E cortaram os polegares das suas mãos e os dedões dos seus pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Então Adoni-Bezeque disse: — Eu mandei cortar os polegares das mãos e os dedões dos pés de setenta reis, e eles apanhavam migalhas debaixo da minha mesa. Agora Deus fez comigo o mesmo que eu fiz com eles. Então levaram Adoni-Bezeque para a cidade de Jerusalém, e ele morreu ali.

[[v7-1-8]]

^<<v7-1-8,8>>^ Os homens de Judá atacaram Jerusalém e a conquistaram. Mataram os seus moradores e puseram fogo na cidade.

[[v7-1-9]]

^<<v7-1-9,9>>^ Depois foram lutar contra os cananeus que moravam nas montanhas, no deserto do Sul e nas planícies de Judá.

[[v7-1-10]]

^<<v7-1-10,10>>^ Também atacaram os cananeus que moravam na cidade de Hebrom, que antes era chamada de Quiriate-Arba. E venceram Sesai, Aimã e Talmai, que eram filhos de Anaque.

[[v7-1-11]]

^<<v7-1-11,11>>^ Dali marcharam contra os moradores de Debir, que também era chamada de Quiriate-Sefer.

[[v7-1-12]]

^<<v7-1-12,12>>^ Então Calebe disse: — Eu darei a minha filha Acsa em casamento ao homem que conseguir tomar Quiriate-Sefer.

[[v7-1-13]]

^<<v7-1-13,13>>^ Otoniel conquistou a cidade. Ele era filho de Quenaz, o irmão mais novo de Calebe. Então Calebe lhe deu a sua filha Acsa em casamento.

[[v7-1-14]]

^<<v7-1-14,14>>^ Quando Acsa foi morar com Otoniel, ela insistiu com ele que pedisse ao pai dela algumas terras. Acsa foi para o lugar onde Calebe estava, e, quando ela desceu do jumento, o seu pai perguntou: — O que é que você quer?

[[v7-1-15]]

^<<v7-1-15,15>>^ — Eu quero um presente! — respondeu ela. — Já que o senhor me deu uma terra seca, me dê também algumas fontes de água. Então Calebe lhe deu as fontes que ficavam nas terras altas e nas baixas.

[[v7-1-16]]

^<<v7-1-16,16>>^ Os descendentes do sogro de Moisés, que era queneu, saíram com o povo de Judá e foram de Jericó, a cidade das palmeiras, para o deserto de Judá, que fica ao sul de Arade. E ali viveram com os amalequitas.

[[v7-1-17]]

^<<v7-1-17,17>>^ O povo de Judá e o de Simeão se juntaram e atacaram os cananeus da cidade de Zefate. Em nome de Deus, eles destruíram completamente a cidade e mudaram o seu nome para Horma .

[[v7-1-18]]

^<<v7-1-18,18>>^ Eles não tomaram Gaza, Asquelom e Ecrom e os seus territórios vizinhos.

[[v7-1-19]]

^<<v7-1-19,19>>^ O Senhor  Deus ajudou o povo de Judá, e eles conquistaram a região das montanhas. Mas não puderam expulsar os moradores do litoral porque estes tinham carros de ferro.

[[v7-1-20]]

^<<v7-1-20,20>>^ Como Moisés havia mandado, a cidade de Hebrom foi dada a Calebe. E ele pôs para fora dali os três filhos de Anaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ Mas o povo da tribo  de Benjamim não expulsou os jebuseus que moravam na cidade de Jerusalém. E os jebuseus dali vivem com o povo de Benjamim até hoje .

[[v7-1-22]]

^<<v7-1-22,22>>^ O povo das tribos  de José, isto é, Efraim e Manassés, também saiu. Eles atacaram a cidade de Betel, que antigamente era chamada de Luz. E o Senhor  os ajudou. Eles mandaram espiões à cidade;

[[v7-1-23]]

^<<v7-1-23,23>>^ O povo das tribos  de José, isto é, Efraim e Manassés, também saiu. Eles atacaram a cidade de Betel, que antigamente era chamada de Luz. E o Senhor  os ajudou. Eles mandaram espiões à cidade;

[[v7-1-24]]

^<<v7-1-24,24>>^ estes viram um homem que ia saindo e lhe disseram: — Como podemos entrar na cidade? Diga, e não mataremos você.

[[v7-1-25]]

^<<v7-1-25,25>>^ Então ele mostrou a entrada. Eles entraram e mataram todos os moradores da cidade, menos aquele homem e toda a sua família.

[[v7-1-26]]

^<<v7-1-26,26>>^ Então ele foi para a terra dos heteus, construiu ali uma cidade e lhe deu o nome de Luz. E esse é o seu nome até hoje .

[[v7-1-27]]

^<<v7-1-27,27>>^ A tribo  de Manassés não expulsou o povo que morava nas cidades de Bete-Sã, Taanaque, Dor, Ibleão, Megido e nos seus povoados. Os cananeus continuaram a viver nelas.

[[v7-1-28]]

^<<v7-1-28,28>>^ Quando os israelitas ficaram mais fortes, obrigaram os cananeus a trabalhar para eles, mas não expulsaram todos.

[[v7-1-29]]

^<<v7-1-29,29>>^ A tribo de Efraim não expulsou os cananeus que moravam na cidade de Gezer, e assim os cananeus ficaram vivendo ali com eles.

[[v7-1-30]]

^<<v7-1-30,30>>^ A tribo de Zebulom não expulsou o povo que vivia nas cidades de Quitrom e Naalol. Os cananeus viveram com eles, mas eram obrigados a trabalhar para eles.

[[v7-1-31]]

^<<v7-1-31,31>>^ A tribo de Aser não expulsou o povo que vivia nas cidades de Aco, Sidom, Alabe, Aczibe, Helba, Afeca e Reobe.

[[v7-1-32]]

^<<v7-1-32,32>>^ O povo de Aser viveu com os cananeus que moravam ali, pois eles não tinham sido expulsos.

[[v7-1-33]]

^<<v7-1-33,33>>^ A tribo de Naftali não expulsou o povo que morava nas cidades de Bete-Semes e Bete-Anate. Os cananeus viveram com o povo de Naftali, mas eram obrigados a trabalhar para eles.

[[v7-1-34]]

^<<v7-1-34,34>>^ Os amorreus forçaram a tribo de Dã a se retirar para as montanhas e não os deixavam descer ao vale.

[[v7-1-35]]

^<<v7-1-35,35>>^ Os amorreus ficaram vivendo nas montanhas de Heres, em Aijalom e em Saalabim, mas o povo da tribo de José os dominou e os forçou a trabalhar para eles.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]