include::./index.adoc[]

[[v7-7-0]]
=== Juízes, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-7-1]]

^<<v7-7-1,1>>^ Jerubaal, isto é, Gideão, e todos os homens que estavam com ele se levantaram de madrugada e foram acampar perto da fonte de Harode. O acampamento dos midianitas ficava no vale, no lado norte, perto do monte Moré.

[[v7-7-2]]

^<<v7-7-2,2>>^ O Senhor  Deus disse a Gideão: — Você tem gente demais, e por isso não posso deixar que vocês derrotem os midianitas. Se eu deixasse, vocês poderiam pensar que venceram sem a minha ajuda.

[[v7-7-3]]

^<<v7-7-3,3>>^ Anuncie ao povo o seguinte: "Quem estiver com medo, que saia do monte Gilboa e volte para casa." Gideão anunciou, e vinte e dois mil homens voltaram. Mas dez mil ficaram.

[[v7-7-4]]

^<<v7-7-4,4>>^ E o Senhor  disse a Gideão: — Ainda é gente demais. Leve todos até as águas, e ali eu separarei os que irão com você. Se eu disser que um homem deve ir com você, ele irá. Se disser que outro não deve ir, ele não irá.

[[v7-7-5]]

^<<v7-7-5,5>>^ Aí Gideão fez com que os homens descessem até as águas. E o Senhor  Deus lhe disse: — Todos os homens que lamberem a água com a língua, como fazem os cachorros, devem ser separados dos que se ajoelharem para beber.

[[v7-7-6]]

^<<v7-7-6,6>>^ Trezentos homens juntaram água nas mãos e lamberam. Todos os outros se ajoelharam para beber.

[[v7-7-7]]

^<<v7-7-7,7>>^ Aí o Senhor  disse a Gideão: — Com estes trezentos homens que lamberam a água, eu libertarei vocês e lhes darei a vitória sobre os midianitas. Diga aos outros que voltem para casa.

[[v7-7-8]]

^<<v7-7-8,8>>^ Então Gideão mandou todos os outros israelitas para casa, menos aqueles trezentos. Mas estes ficaram com toda a comida e todas as cornetas. O acampamento dos midianitas estava abaixo deles, no vale.

[[v7-7-9]]

^<<v7-7-9,9>>^ Naquela noite o Senhor  Deus disse a Gideão: — Levante-se e ataque o acampamento dos midianitas. Eu já dei a vitória a você.

[[v7-7-10]]

^<<v7-7-10,10>>^ Mas, se você estiver com medo de atacar, desça até o acampamento deles. Leve junto Purá, o seu ajudante.

[[v7-7-11]]

^<<v7-7-11,11>>^ Você vai ouvir o que eles estão dizendo e então terá coragem para atacar o acampamento. Gideão e Purá desceram até bem perto do acampamento inimigo.

[[v7-7-12]]

^<<v7-7-12,12>>^ Os midianitas, os amalequitas e os povos do deserto estavam espalhados no vale, como uma nuvem de gafanhotos. Eles e os seus camelos eram tantos como os grãos de areia da praia do mar.

[[v7-7-13]]

^<<v7-7-13,13>>^ Quando Gideão chegou, ouviu um homem contando o seu sonho a um amigo. Ele dizia: — Eu sonhei que um pão de cevada  rolou para dentro do nosso acampamento. Veio e bateu numa barraca. Ela caiu, virou no avesso e ficou estendida no chão.

[[v7-7-14]]

^<<v7-7-14,14>>^ O amigo respondeu: — É a espada de Gideão, o israelita, o filho de Joás! Isso quer dizer que Deus entregou a ele o nosso povo e todo o nosso exército!

[[v7-7-15]]

^<<v7-7-15,15>>^ Quando Gideão ouviu esse sonho e entendeu o que ele queria dizer, ajoelhou-se e adorou a Deus. Então voltou para o acampamento israelita e disse: — Levantem-se! O Senhor  Deus entregou o exército dos midianitas nas mãos de vocês!

[[v7-7-16]]

^<<v7-7-16,16>>^ Gideão separou os trezentos em três grupos e deu a cada homem uma corneta de chifre de carneiro e um jarro com uma tocha dentro.

[[v7-7-17]]

^<<v7-7-17,17>>^ E disse: — Olhem para mim! E, quando eu chegar perto do acampamento inimigo, façam o que eu fizer.

[[v7-7-18]]

^<<v7-7-18,18>>^ Quando eu e o meu grupo tocarmos as cornetas, então vocês, que estarão cercando o acampamento, toquem as cornetas e gritem: "Pelo Senhor  e por Gideão!"

[[v7-7-19]]

^<<v7-7-19,19>>^ Um pouco antes da meia-noite, na hora de ser trocada a guarda, Gideão e os seus cem homens chegaram bem perto do acampamento. Então tocaram as cornetas e quebraram os jarros que levavam.

[[v7-7-20]]

^<<v7-7-20,20>>^ Os três grupos tocaram as cornetas e quebraram os jarros. Eles seguravam a tocha na mão esquerda e a corneta na direita e gritavam: "Uma espada pelo Senhor  e por Gideão!"

[[v7-7-21]]

^<<v7-7-21,21>>^ E cada um ficou parado no seu lugar em volta do acampamento. Então todo o exército inimigo fugiu, gritando.

[[v7-7-22]]

^<<v7-7-22,22>>^ Enquanto os trezentos homens tocavam as cornetas, o Senhor  Deus fez com que os homens do acampamento atacassem uns aos outros com as suas espadas. Eles fugiram na direção de Zererá e foram a Bete-Sita e até a divisa de Abel-Meolá, perto de Tabate.

[[v7-7-23]]

^<<v7-7-23,23>>^ Então os homens das tribos  de Naftali, de Aser e das duas metades da tribo de Manassés foram chamados e perseguiram os midianitas.

[[v7-7-24]]

^<<v7-7-24,24>>^ Gideão enviou mensageiros para dizerem a todos os que moravam na região montanhosa de Efraim: — Desçam e lutem contra os midianitas. Defendam o rio Jordão e os seus riachos até Bete-Bara e não deixem os midianitas atravessarem. Então os homens de Efraim foram e defenderam o rio Jordão e os seus riachos até Bete-Bara.

[[v7-7-25]]

^<<v7-7-25,25>>^ Eles prenderam Orebe e Zeebe, os dois chefes midianitas. Mataram Orebe na pedra de Orebe e mataram Zeebe no seu tanque de pisar uvas. Continuaram a perseguir os midianitas e levaram a cabeça de Orebe e a de Zeebe para Gideão, que estava a leste do rio Jordão.

'''

xref:007-juizes/007-juizes-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-juizes/007-juizes-008.adoc#v7-8-0[Próximo Capítulo &#62;]