include::./index.adoc[]

[[v7-4-0]]
=== Juízes, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-4-1]]

^<<v7-4-1,1>>^ Depois que Eúde morreu, o povo de Israel pecou novamente contra Deus, o Senhor .

[[v7-4-2]]

^<<v7-4-2,2>>^ Por isso o Senhor  deixou que eles fossem conquistados por Jabim, rei de Canaã, que governava a cidade de Hazor. O comandante do seu exército era Sísera, que morava em Harosete-Hagojim.

[[v7-4-3]]

^<<v7-4-3,3>>^ Jabim tinha novecentos carros de ferro. Durante vinte anos ele maltratou o povo de Israel sem dó nem piedade. Então o povo de Israel pediu socorro a Deus, o Senhor .

[[v7-4-4]]

^<<v7-4-4,4>>^ Débora, mulher de Lapidote, era profetisa . Era também juíza dos israelitas naquele tempo.

[[v7-4-5]]

^<<v7-4-5,5>>^ Havia uma palmeira entre Ramá e Betel, na região montanhosa de Efraim. Débora sentava-se debaixo dela, e os israelitas vinham até ali para que ela julgasse as questões que eles traziam.

[[v7-4-6]]

^<<v7-4-6,6>>^ Ela mandou chamar Baraque, filho de Abinoão, que estava na cidade de Quedes, no território da tribo  de Naftali, e lhe disse: — O Senhor , o Deus de Israel, está lhe dando esta ordem: "Escolha dez mil homens das tribos de Naftali e Zebulom e os leve ao monte Tabor.

[[v7-4-7]]

^<<v7-4-7,7>>^ Eu vou trazer Sísera, o comandante do exército de Jabim, até o rio Quisom para lutar contra você. Ele virá com seus carros de ferro e soldados, mas eu farei com que você o vença."

[[v7-4-8]]

^<<v7-4-8,8>>^ Então Baraque disse a Débora: — Só irei se você for comigo. Se você não for, eu também não irei.

[[v7-4-9]]

^<<v7-4-9,9>>^ Ela respondeu: — Está bem! Eu vou com você. Mas você não ficará com as honras da vitória, pois o Senhor  Deus entregará Sísera nas mãos de uma mulher. E Débora foi com Baraque para Quedes.

[[v7-4-10]]

^<<v7-4-10,10>>^ Baraque convocou as tribos de Zebulom e Naftali para a cidade de Quedes, e dez mil homens o seguiram. E Débora foi com ele.

[[v7-4-11]]

^<<v7-4-11,11>>^ Acontece que Héber, o queneu, havia se separado dos outros queneus, os descendentes de Hobabe, cunhado de Moisés. Ele havia armado as suas barracas perto do carvalho de Zaananim, que não ficava longe de Quedes.

[[v7-4-12]]

^<<v7-4-12,12>>^ Avisaram Sísera que Baraque, filho de Abinoão, havia subido ao monte Tabor.

[[v7-4-13]]

^<<v7-4-13,13>>^ Então ele mandou vir os seus novecentos carros de ferro e todos os seus homens e os fez ir de Harosete-Hagojim até o rio Quisom.

[[v7-4-14]]

^<<v7-4-14,14>>^ Então Débora disse a Baraque: — Vá agora porque é hoje que o Senhor  lhe dará a vitória sobre Sísera. O Senhor  está com você! Então Baraque desceu do monte Tabor com os seus dez mil homens.

[[v7-4-15]]

^<<v7-4-15,15>>^ Quando Baraque apareceu com o seu exército, o Senhor  fez com que houvesse uma grande confusão no meio dos soldados e dos carros de Sísera. Aí Sísera desceu do seu carro e fugiu a pé.

[[v7-4-16]]

^<<v7-4-16,16>>^ Mas Baraque perseguiu os carros e o exército até Harosete-Hagojim. Todo o exército de Sísera foi destruído; ninguém escapou.

[[v7-4-17]]

^<<v7-4-17,17>>^ Porém Sísera fugiu para a barraca de Jael, mulher de Héber, o queneu. Ele fez isso porque Jabim, rei de Hazor, estava em paz com a família de Héber.

[[v7-4-18]]

^<<v7-4-18,18>>^ Jael saiu da barraca para encontrar Sísera e lhe disse: — Entre, meu senhor. Entre na minha barraca. Não tenha medo. Então ele entrou, e Jael o cobriu com um tapete.

[[v7-4-19]]

^<<v7-4-19,19>>^ E Sísera pediu a ela: — Por favor, me dê um pouco de água porque estou com muita sede. Ela abriu um odre  de leite e lhe deu de beber. Depois cobriu Sísera de novo.

[[v7-4-20]]

^<<v7-4-20,20>>^ E ele disse: — Fique na porta da barraca e, se alguma pessoa vier e perguntar se há alguém aqui, diga que não.

[[v7-4-21]]

^<<v7-4-21,21>>^ Sísera estava muito cansado e caiu num sono profundo. Aí Jael pegou um martelo e uma estaca da barraca, entrou de mansinho e fincou a estaca na cabeça dele, na fonte. A estaca atravessou a cabeça e entrou na terra. E ele morreu.

[[v7-4-22]]

^<<v7-4-22,22>>^ Quando Baraque chegou, perseguindo Sísera, Jael saiu para encontrá-lo e disse: — Venha cá, e eu lhe mostro o homem que você está procurando. Então Baraque foi com ela e encontrou Sísera no chão, morto, com a estaca atravessada na cabeça.

[[v7-4-23]]

^<<v7-4-23,23>>^ Naquele dia Deus fez com que os israelitas derrotassem Jabim, o rei cananeu.

[[v7-4-24]]

^<<v7-4-24,24>>^ E eles continuaram atacando Jabim cada vez mais, até acabarem com ele.

'''

xref:007-juizes/007-juizes-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-juizes/007-juizes-005.adoc#v7-5-0[Próximo Capítulo &#62;]