include::./index.adoc[]

[[v7-16-0]]
=== Juízes, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-16-1]]

^<<v7-16-1,1>>^ Dali Sansão foi até a cidade de Gaza. Lá viu uma prostituta e teve relações com ela.

[[v7-16-2]]

^<<v7-16-2,2>>^ O povo de Gaza soube que Sansão estava lá. Então eles cercaram o lugar e ficaram a noite toda esperando Sansão no portão da cidade. Ficaram em silêncio, pensando: — Vamos esperar o amanhecer. Então nós o matamos.

[[v7-16-3]]

^<<v7-16-3,3>>^ Mas Sansão ficou deitado somente até a meia-noite. Depois se levantou e arrancou o portão da cidade, com os batentes e as trancas. Pôs tudo nos ombros e carregou para o alto do monte que está em frente da cidade de Hebrom.

[[v7-16-4]]

^<<v7-16-4,4>>^ Depois disso Sansão se apaixonou por uma mulher chamada Dalila, que morava no vale de Soreque.

[[v7-16-5]]

^<<v7-16-5,5>>^ Então os governadores das cinco cidades dos filisteus foram falar com ela. Eles disseram assim: — Dê um jeito de Sansão contar a você por que ele é tão forte e como é que o poderemos dominar, amarrar e deixar sem defesa. Se você fizer isso, cada um de nós lhe dará mil e cem barras de prata.

[[v7-16-6]]

^<<v7-16-6,6>>^ Então Dalila pediu a Sansão: — Por favor, me conte o segredo da sua força. Se alguém quiser amarrar você e deixar sem defesa, o que é que ele deve fazer?

[[v7-16-7]]

^<<v7-16-7,7>>^ Sansão respondeu: — Se me amarrarem com sete cordas de arco, novas, que ainda não secaram, eu ficarei fraco e serei como qualquer um.

[[v7-16-8]]

^<<v7-16-8,8>>^ Aí os governadores dos filisteus trouxeram para Dalila sete cordas de arco, novas, que ainda não estavam secas, e ela amarrou Sansão.

[[v7-16-9]]

^<<v7-16-9,9>>^ Dalila havia deixado alguns homens escondidos, esperando no outro quarto. Então gritou: — Sansão! Os filisteus estão chegando! E ele arrebentou as cordas de arco, como se fossem fios de linha queimada. Assim eles continuaram sem saber qual era o segredo da força de Sansão.

[[v7-16-10]]

^<<v7-16-10,10>>^ Então Dalila lhe disse: — Até agora você mentiu e caçoou de mim. Por favor, me diga como é que alguém pode amarrar você.

[[v7-16-11]]

^<<v7-16-11,11>>^ Sansão respondeu: — Se me amarrarem com cordas novas, que nunca foram usadas, ficarei fraco e serei como qualquer um.

[[v7-16-12]]

^<<v7-16-12,12>>^ Aí Dalila pegou cordas novas e amarrou os braços dele. Depois gritou: — Sansão! Os filisteus estão chegando! Os homens estavam novamente escondidos, esperando no outro quarto. Mas Sansão arrebentou as cordas como se fossem fios de linha.

[[v7-16-13]]

^<<v7-16-13,13>>^ E Dalila disse: — Você continua mentindo e caçoando de mim. Diga como é que alguém pode amarrar você. Ele respondeu: — Se você tecer num tear as sete tranças do meu cabelo e prendê-las com um prego grande de madeira, eu ficarei fraco e serei como qualquer um.

[[v7-16-14]]

^<<v7-16-14,14>>^ Então Dalila fez com que Sansão dormisse. Quando ele adormeceu, ela pegou e teceu as sete tranças dele num tear e prendeu-as com um prego grande de madeira. Depois gritou: — Sansão! Os filisteus estão chegando! Mas ele se levantou, arrancou o prego e tirou o cabelo do tear.

[[v7-16-15]]

^<<v7-16-15,15>>^ Então ela disse: — Por que você diz que me ama se isso não é verdade? Você me fez de boba três vezes e até agora não me contou por que é tão forte.

[[v7-16-16]]

^<<v7-16-16,16>>^ E ela continuou a perguntar isso todos os dias. Sansão ficou tão cansado com a insistência dela, que já não aguentava mais.

[[v7-16-17]]

^<<v7-16-17,17>>^ E acabou lhe contando a verdade: — O meu cabelo nunca foi cortado! — disse ele. — Eu fui dedicado a Deus como nazireu  desde que nasci. Se o meu cabelo for cortado, perderei a minha força, ficarei fraco e serei como qualquer um.

[[v7-16-18]]

^<<v7-16-18,18>>^ Quando Dalila percebeu que ele tinha dito a verdade, mandou o seguinte recado aos governadores filisteus: — Voltem de novo. Agora ele me disse a verdade. Então eles vieram e trouxeram o dinheiro.

[[v7-16-19]]

^<<v7-16-19,19>>^ Ela fez com que Sansão dormisse no seu colo. Em seguida chamou um homem, e ele cortou as sete tranças de Sansão. Aí Dalila começou a provocá-lo, mas ele havia perdido a sua força.

[[v7-16-20]]

^<<v7-16-20,20>>^ Ela gritou: — Sansão! Os filisteus estão chegando! Ele se levantou e pensou: "Eu me livrarei como sempre." Sansão não sabia que o Senhor  o havia abandonado.

[[v7-16-21]]

^<<v7-16-21,21>>^ Os filisteus o pegaram e furaram os seus olhos. Então o levaram para Gaza e o prenderam com correntes de bronze. E o puseram para trabalhar na prisão, virando um moinho.

[[v7-16-22]]

^<<v7-16-22,22>>^ Mas o seu cabelo começou a crescer de novo.

[[v7-16-23]]

^<<v7-16-23,23>>^ Os governadores filisteus se reuniram para fazer uma festa e oferecer um grande sacrifício  ao seu deus Dagom. Eles cantavam: "O nosso deus entregou o nosso inimigo Sansão nas nossas mãos!"

[[v7-16-24]]

^<<v7-16-24,24>>^ E o povo, quando viu Sansão, cantou louvores ao deus Dagom, assim: "O nosso deus entregou nas nossas mãos o inimigo que destruía a nossa terra e matava muitos dos nossos."

[[v7-16-25]]

^<<v7-16-25,25>>^ E, no meio daquela alegria, disseram: — Chamem Sansão, para ele nos divertir. Trouxeram Sansão para fora da cadeia e se divertiram à custa dele. Depois o colocaram entre as colunas do templo.

[[v7-16-26]]

^<<v7-16-26,26>>^ Então Sansão pediu ao rapaz que o guiava pela mão: — Deixe-me tocar nas colunas que sustentam o templo para que eu possa me encostar nelas.

[[v7-16-27]]

^<<v7-16-27,27>>^ O templo estava cheio de homens e mulheres. Os cinco governadores filisteus estavam lá. Havia no terraço mais ou menos três mil homens e mulheres olhando para Sansão e se divertindo à custa dele.

[[v7-16-28]]

^<<v7-16-28,28>>^ E Sansão orou ao Senhor , dizendo: — Ó Senhor , meu Deus, peço que lembres de mim. Por favor, dá-me força só mais esta vez. Deixa que eu, de uma só vez, me vingue dos filisteus, por terem furado os meus olhos.

[[v7-16-29]]

^<<v7-16-29,29>>^ Então agarrou as duas colunas do meio, que sustentavam o templo. Com a mão direita numa coluna e a esquerda na outra, jogou todo o seu peso contra elas

[[v7-16-30]]

^<<v7-16-30,30>>^ e gritou: — Que eu morra com os filisteus! Em seguida deu um empurrão com toda a força, e o templo caiu sobre os governadores e todas as outras pessoas. E assim Sansão matou mais gente na sua morte do que durante a sua vida.

[[v7-16-31]]

^<<v7-16-31,31>>^ Os irmãos de Sansão e toda a sua família foram buscar o seu corpo. Eles o levaram e sepultaram entre Zora e Estaol, no túmulo de Manoá, o seu pai. Sansão havia governado o povo de Israel durante vinte anos.

'''

xref:007-juizes/007-juizes-015.adoc#v7-15-0[&#60; Capítulo Anterior] | <<v7-16-0,Topo>> | xref:007-juizes/007-juizes-017.adoc#v7-17-0[Próximo Capítulo &#62;]