include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-2-1]]

^<<v7-2-1,1>>^ O Anjo do Senhor  foi de Gilgal a Boquim e disse aos israelitas: — Eu tirei vocês da terra do Egito e os trouxe à terra que havia prometido aos seus pais. Eu disse: "Nunca quebrarei a aliança  que fiz com vocês.

[[v7-2-2]]

^<<v7-2-2,2>>^ Não façam nenhum acordo  com os moradores desta terra. Pelo contrário, derrubem os altares deles." Mas vocês não fizeram o que eu disse. Em vez disso, vejam o que fizeram!

[[v7-2-3]]

^<<v7-2-3,3>>^ Agora eu digo que não tirarei este povo do caminho de vocês. Eles serão seus inimigos, e os deuses deles vão ser tentações para vocês.

[[v7-2-4]]

^<<v7-2-4,4>>^ Quando o Anjo terminou de falar, todo o povo de Israel começou a chorar.

[[v7-2-5]]

^<<v7-2-5,5>>^ Por isso aquele lugar é chamado de Boquim . E ali eles ofereceram sacrifícios  a Deus, o Senhor .

[[v7-2-6]]

^<<v7-2-6,6>>^ Josué mandou embora todo o povo de Israel, e cada homem foi tomar conta do seu pedaço de terra.

[[v7-2-7]]

^<<v7-2-7,7>>^ O povo de Israel serviu a Deus, o Senhor , enquanto Josué viveu. Depois que ele morreu, eles ainda continuaram a servir o Senhor  enquanto viveram os líderes que tinham visto tudo o que o Senhor  havia feito por Israel.

[[v7-2-8]]

^<<v7-2-8,8>>^ Josué, filho de Num, servo  do Senhor , morreu com a idade de cento e dez anos.

[[v7-2-9]]

^<<v7-2-9,9>>^ Ele foi sepultado no seu próprio pedaço de terra, em Timnate-Heres, na região montanhosa de Efraim, ao norte do monte Gaás.

[[v7-2-10]]

^<<v7-2-10,10>>^ Todas as pessoas daquela geração  também morreram e os seus filhos esqueceram o Senhor  e as coisas que ele havia feito pelo povo de Israel.

[[v7-2-11]]

^<<v7-2-11,11>>^ Então o povo de Israel pecou contra Deus, o Senhor , adorando os deuses dos cananeus.

[[v7-2-12]]

^<<v7-2-12,12>>^ Eles deixaram de adorar o Senhor , o Deus dos seus antepassados, que os havia tirado do Egito. Começaram a seguir outros deuses, os deuses dos povos que viviam ao seu redor. Eles adoraram esses deuses e assim fizeram o Senhor  ficar muito irado .

[[v7-2-13]]

^<<v7-2-13,13>>^ Abandonaram a Deus, o Senhor , e adoraram Baal  e Astarote .

[[v7-2-14]]

^<<v7-2-14,14>>^ O Senhor  ficou muito irado com o povo de Israel e deixou que eles fossem atacados e roubados por povos vizinhos. Ele entregou os israelitas nas mãos dos inimigos que viviam ao redor, e por isso eles não puderam mais resistir.

[[v7-2-15]]

^<<v7-2-15,15>>^ Sempre que saíam para lutar, o Senhor  ficava contra eles, como tinha dito. Assim eles ficaram numa situação muito difícil.

[[v7-2-16]]

^<<v7-2-16,16>>^ Então o Senhor  Deus deu ao povo de Israel líderes fortes, chamados juízes, que os salvaram dos que os atacavam e roubavam.

[[v7-2-17]]

^<<v7-2-17,17>>^ Mas eles não deram atenção a esses líderes. Continuaram a desprezar a Deus e a adorar outros deuses. Os pais deles haviam obedecido aos mandamentos do Senhor , mas eles não obedeceram.

[[v7-2-18]]

^<<v7-2-18,18>>^ O Senhor  lhes dava um líder e o ajudava. Enquanto esse líder vivia, o Senhor  salvava o povo dos seus inimigos. Ele tinha pena dos israelitas porque eles sofriam na escravidão.

[[v7-2-19]]

^<<v7-2-19,19>>^ Mas, quando o líder morria, eles voltavam a viver como antes e se tornavam ainda piores do que os seus pais. Iam atrás de outros deuses, e os serviam, e adoravam. Teimavam em continuar nos seus maus caminhos.

[[v7-2-20]]

^<<v7-2-20,20>>^ Por isso o Senhor  Deus ficou muito irado com o povo de Israel e disse: — Esta nação quebrou a aliança  que eu mandei que os seus antepassados guardassem. E, porque eles não me têm obedecido,

[[v7-2-21]]

^<<v7-2-21,21>>^ não expulsarei mais desta terra nenhuma das nações que Josué deixou quando morreu.

[[v7-2-22]]

^<<v7-2-22,22>>^ Assim verei se os israelitas seguirão fielmente os meus caminhos, como os seus antepassados seguiram.

[[v7-2-23]]

^<<v7-2-23,23>>^ Assim o Senhor  não expulsou logo da terra as nações que ele não tinha entregado a Josué, mas deixou que ficassem ali.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]