include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-9-1]]

^<<v7-9-1,1>>^ Abimeleque, filho de Gideão, foi à cidade de Siquém, onde viviam todos os parentes da sua mãe. Ele pediu

[[v7-9-2]]

^<<v7-9-2,2>>^ que eles perguntassem aos homens de Siquém: — O que é que vocês preferem: ser governados pelos setenta filhos de Gideão ou por um só homem? Lembrem que Abimeleque é do mesmo sangue de vocês.

[[v7-9-3]]

^<<v7-9-3,3>>^ Então os parentes da sua mãe falaram sobre isso com os homens de Siquém, e eles resolveram seguir Abimeleque porque era parente deles.

[[v7-9-4]]

^<<v7-9-4,4>>^ Deram a ele oitocentos gramas de prata tirados do templo de Baal-Berite. Com essa prata Abimeleque contratou alguns homens ordinários para o seguirem.

[[v7-9-5]]

^<<v7-9-5,5>>^ Abimeleque foi para a casa do seu pai em Ofra e ali, em cima de uma só pedra, ele matou os seus setenta irmãos, os filhos de Gideão. Mas Jotão, o filho mais moço, se escondeu e por isso não foi assassinado.

[[v7-9-6]]

^<<v7-9-6,6>>^ Então todos os homens de Siquém e de Bete-Milo se reuniram na árvore sagrada de Siquém e ali fizeram de Abimeleque o seu rei.

[[v7-9-7]]

^<<v7-9-7,7>>^ Quando Jotão soube disso, subiu até o alto do monte Gerizim e gritou para eles: — Homens de Siquém, me escutem, e Deus escutará vocês!

[[v7-9-8]]

^<<v7-9-8,8>>^ Aí Jotão disse: — Uma vez as árvores resolveram procurar um rei para elas. Então disseram à oliveira: "Seja o nosso rei."

[[v7-9-9]]

^<<v7-9-9,9>>^ E a oliveira respondeu: "Para governar vocês, eu teria de parar de dar o meu azeite, usado para honrar os deuses e os seres humanos."

[[v7-9-10]]

^<<v7-9-10,10>>^ — Aí as árvores pediram à figueira: "Venha ser o nosso rei."

[[v7-9-11]]

^<<v7-9-11,11>>^ Mas a figueira respondeu: "Para governar vocês, eu teria de parar de dar os meus figos tão doces."

[[v7-9-12]]

^<<v7-9-12,12>>^ — Então as árvores disseram à parreira : "Venha ser o nosso rei."

[[v7-9-13]]

^<<v7-9-13,13>>^ Mas a parreira respondeu: "Para governar vocês, eu teria de parar de dar o meu vinho, que alegra os deuses e os seres humanos."

[[v7-9-14]]

^<<v7-9-14,14>>^ — Aí todas as árvores pediram ao espinheiro: "Venha ser o nosso rei."

[[v7-9-15]]

^<<v7-9-15,15>>^ E o espinheiro respondeu: "Se vocês querem mesmo me fazer o seu rei, venham e fiquem debaixo da minha sombra. Se vocês não fizerem isso, sairá fogo do espinheiro e queimará os cedros do Líbano."

[[v7-9-16]]

^<<v7-9-16,16>>^ E Jotão continuou: — Será que vocês foram sinceros e honestos quando fizeram de Abimeleque um rei? E será que vocês trataram Gideão e a sua família com decência e de acordo com o que ele merecia?

[[v7-9-17]]

^<<v7-9-17,17>>^ Lembrem que o meu pai lutou por vocês. Ele arriscou a vida para salvá-los dos midianitas.

[[v7-9-18]]

^<<v7-9-18,18>>^ Mas hoje vocês estão contra a família do meu pai. Vocês mataram os seus setenta filhos em cima de uma só pedra! E depois fizeram do seu filho Abimeleque, que é filho de uma escrava, o rei de Siquém. Fizeram isso somente porque ele é parente de vocês.

[[v7-9-19]]

^<<v7-9-19,19>>^ Agora, se o que vocês fizeram hoje com Gideão e a sua família foi sincero e honesto, então sejam felizes com Abimeleque, e que ele seja feliz com vocês!

[[v7-9-20]]

^<<v7-9-20,20>>^ Mas, se não, que de Abimeleque saia fogo e queime os homens de Siquém e de Bete-Milo! E que saia fogo dos homens de Siquém e de Bete-Milo e queime Abimeleque!

[[v7-9-21]]

^<<v7-9-21,21>>^ Aí Jotão fugiu e foi viver em Beer porque estava com medo do seu irmão Abimeleque.

[[v7-9-22]]

^<<v7-9-22,22>>^ Abimeleque governou o povo de Israel durante três anos.

[[v7-9-23]]

^<<v7-9-23,23>>^ Então Deus fez com que Abimeleque e os homens de Siquém se odiassem. E eles se revoltaram contra Abimeleque.

[[v7-9-24]]

^<<v7-9-24,24>>^ Isso aconteceu para que Abimeleque e os homens de Siquém, que o haviam ajudado a matar os setenta filhos de Gideão, pagassem pelo seu crime.

[[v7-9-25]]

^<<v7-9-25,25>>^ Os moradores de Siquém puseram homens escondidos no alto das montanhas para matar Abimeleque. Eles assaltavam todos os que passavam por aquele caminho. E Abimeleque soube disso.

[[v7-9-26]]

^<<v7-9-26,26>>^ Gaal, filho de Ebede, foi com os seus irmãos para Siquém, e os homens dali confiaram nele.

[[v7-9-27]]

^<<v7-9-27,27>>^ Eles foram até as suas plantações, apanharam uvas e prepararam vinho. Então fizeram uma festa. Depois entraram no templo do seu deus, comeram, beberam e amaldiçoaram Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ Aí Gaal disse: — Por que estamos sendo dominados por Abimeleque? Que tipo de homens somos nós, os homens de Siquém? E quem é ele? É o filho de Gideão. No entanto, Zebul recebe ordens dele. Por que devemos ser dominados por ele? Sejam fiéis ao seu antepassado Hamor, pai de Siquém.

[[v7-9-29]]

^<<v7-9-29,29>>^ Ah! Se eu fosse o líder deste povo! Expulsaria Abimeleque e diria: "Já que o seu exército é tão grande, então saia e lute!"

[[v7-9-30]]

^<<v7-9-30,30>>^ Zebul, o governador da cidade, ficou com muita raiva quando soube o que Gaal tinha dito.

[[v7-9-31]]

^<<v7-9-31,31>>^ E mandou mensageiros a Abimeleque, que estava em Arumá, para dizerem a ele: — Gaal, filho de Ebede, e os seus irmãos vieram a Siquém e estão atiçando o povo da cidade contra você.

[[v7-9-32]]

^<<v7-9-32,32>>^ Por isso faça o seguinte: durante a noite você e os seus homens saiam e se escondam nos campos.

[[v7-9-33]]

^<<v7-9-33,33>>^ Amanhã levantem-se ao nascer do sol e ataquem de surpresa a cidade. E, quando Gaal e os seus homens saírem para lutar, ataquem com tudo o que vocês tiverem!

[[v7-9-34]]

^<<v7-9-34,34>>^ Então Abimeleque e todos os seus homens saíram durante a noite e se esconderam fora de Siquém, divididos em quatro grupos.

[[v7-9-35]]

^<<v7-9-35,35>>^ Gaal se levantou e foi para o portão da cidade. Aí Abimeleque e os seus homens saíram de onde estavam escondidos.

[[v7-9-36]]

^<<v7-9-36,36>>^ Quando Gaal os viu, disse a Zebul: — Veja! Vem gente descendo do alto das montanhas! Mas Zebul respondeu: — Não são homens. São as sombras das montanhas.

[[v7-9-37]]

^<<v7-9-37,37>>^ Porém Gaal disse: — Veja! Vem gente descendo bem na nossa frente, e um grupo vem vindo da árvore sagrada.

[[v7-9-38]]

^<<v7-9-38,38>>^ Então Zebul disse: — Onde foi parar toda a sua conversa? Não foi você quem perguntou por que devíamos servir Abimeleque? Pois são estes os homens de quem você estava caçoando. Saia agora e lute contra eles.

[[v7-9-39]]

^<<v7-9-39,39>>^ Aí Gaal saiu na frente dos homens de Siquém e lutou contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ Abimeleque o atacou, e Gaal fugiu. Muitos homens caíram feridos, até perto do portão da cidade.

[[v7-9-41]]

^<<v7-9-41,41>>^ Então Abimeleque voltou para Arumá, e Zebul foi até Siquém e expulsou de lá Gaal e os seus irmãos.

[[v7-9-42]]

^<<v7-9-42,42>>^ No dia seguinte o povo de Siquém saiu para os campos. E Abimeleque ficou sabendo disso.

[[v7-9-43]]

^<<v7-9-43,43>>^ Então ele dividiu os seus homens em três grupos e os deixou escondidos no campo, esperando. Quando Abimeleque viu o povo saindo da cidade, saiu de onde estava escondido e os matou.

[[v7-9-44]]

^<<v7-9-44,44>>^ Abimeleque e o seu grupo atacaram de surpresa e tomaram conta do portão da cidade. Os outros dois grupos atacaram o povo que estava nos campos e mataram todos.

[[v7-9-45]]

^<<v7-9-45,45>>^ Abimeleque combateu os homens da cidade o dia todo. Tomou a cidade e matou os seus moradores. Então destruiu a cidade e espalhou sal no chão.

[[v7-9-46]]

^<<v7-9-46,46>>^ Quando os chefes de Torre de Siquém souberam disso, foram todos para a fortaleza do templo de Baal-Berite para ficar em segurança.

[[v7-9-47]]

^<<v7-9-47,47>>^ Mas Abimeleque soube que eles estavam reunidos lá.

[[v7-9-48]]

^<<v7-9-48,48>>^ Aí subiu o monte Salmom com os seus homens. Pegou um machado, cortou um galho de árvore e o pôs no ombro. Disse aos homens para fazerem depressa a mesma coisa.

[[v7-9-49]]

^<<v7-9-49,49>>^ E cada um deles cortou um galho de árvore. Depois eles seguiram Abimeleque e fizeram uma pilha de galhos encostados na fortaleza. Em seguida puseram fogo nos galhos e queimaram a fortaleza com toda a gente dentro. Assim morreram todos os moradores de Torre de Siquém, mais ou menos mil homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ Depois Abimeleque foi a Tebes, cercou a cidade e a conquistou.

[[v7-9-51]]

^<<v7-9-51,51>>^ Em Tebes havia uma forte torre. Todos os homens e mulheres e os líderes da cidade correram e entraram nela. Fecharam as portas e foram para o terraço.

[[v7-9-52]]

^<<v7-9-52,52>>^ Abimeleque avançou, atacou a torre e chegou até a porta, para pôr fogo nela.

[[v7-9-53]]

^<<v7-9-53,53>>^ Mas uma mulher jogou uma pedra de moinho na cabeça dele e quebrou o seu crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Aí ele chamou depressa o moço que carregava as suas armas e disse: — Tire a sua espada e me mate. Não quero que digam que fui morto por uma mulher. Então o rapaz tirou a espada e o matou.

[[v7-9-55]]

^<<v7-9-55,55>>^ Quando os israelitas viram que Abimeleque estava morto, voltaram todos para casa.

[[v7-9-56]]

^<<v7-9-56,56>>^ E assim Deus castigou Abimeleque pelo crime que havia cometido contra o seu pai — o crime de matar os seus setenta irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ E, como castigo pela maldade dos homens de Siquém, Deus fez com que eles sofressem. E assim aconteceu o que Jotão, filho de Gideão, tinha dito que ia acontecer quando os amaldiçoou.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]