include::./index.adoc[]

[[v7-8-0]]
=== Juízes, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-8-1]]

^<<v7-8-1,1>>^ Os homens da tribo  de Efraim disseram a Gideão: — Por que você não nos chamou quando foi lutar contra os midianitas? Por que fez isso com a gente? E tiveram uma discussão muito forte com Gideão.

[[v7-8-2]]

^<<v7-8-2,2>>^ Mas ele lhes disse: — O que eu fiz com os midianitas não é nada comparado com o que vocês fizeram. Até aquilo que o menor dos homens de Efraim fez tem mais valor do que aquilo que todos os homens do grupo de famílias de Abiezer fizeram.

[[v7-8-3]]

^<<v7-8-3,3>>^ Deus entregou Orebe e Zeebe, os chefes midianitas, a vocês. Que foi que eu fiz, que possa ser comparado com isso? Quando Gideão disse isso, os homens de Efraim ficaram menos zangados.

[[v7-8-4]]

^<<v7-8-4,4>>^ Gideão e os seus trezentos homens foram até o rio Jordão e o atravessaram. Eles estavam muito cansados, mas continuaram a perseguir o inimigo.

[[v7-8-5]]

^<<v7-8-5,5>>^ Então Gideão fez aos homens da cidade de Sucote o seguinte pedido: — Estou perseguindo os chefes midianitas Zeba e Salmuna, e os meus homens estão muito cansados. Por favor, deem comida para eles.

[[v7-8-6]]

^<<v7-8-6,6>>^ Mas os chefes de Sucote responderam: — Por que devemos dar comida para o seu exército? Você ainda não prendeu Zeba e Salmuna!

[[v7-8-7]]

^<<v7-8-7,7>>^ Aí Gideão disse: — Está bem. Mas, quando o Senhor  me entregar Zeba e Salmuna, eu rasgarei a carne de vocês com os espinhos das plantas do deserto.

[[v7-8-8]]

^<<v7-8-8,8>>^ Gideão foi a Penuel e fez o mesmo pedido aos homens dali. Mas os homens de Penuel lhe deram a mesma resposta que os homens de Sucote tinham dado.

[[v7-8-9]]

^<<v7-8-9,9>>^ Aí Gideão disse: — Quando eu voltar são e salvo, derrubarei esta torre!

[[v7-8-10]]

^<<v7-8-10,10>>^ Zeba e Salmuna estavam em Carcor com seu exército. De todo o exército dos povos do deserto, restavam apenas quinze mil homens. Cento e vinte mil tinham sido mortos.

[[v7-8-11]]

^<<v7-8-11,11>>^ Gideão foi pelo caminho que rodeava o deserto, a leste de Noba e Jogbeá, e atacou de surpresa o exército inimigo.

[[v7-8-12]]

^<<v7-8-12,12>>^ Zeba e Salmuna, os dois chefes midianitas, fugiram. Mas ele os perseguiu e os prendeu. E o exército inteiro foi derrotado.

[[v7-8-13]]

^<<v7-8-13,13>>^ Gideão, filho de Joás, voltou da batalha pela subida de Heres.

[[v7-8-14]]

^<<v7-8-14,14>>^ Prendeu um moço de Sucote e lhe fez perguntas. Então o rapaz escreveu para Gideão os nomes dos setenta e sete chefes e líderes de Sucote.

[[v7-8-15]]

^<<v7-8-15,15>>^ Aí Gideão foi falar com os homens de Sucote e disse: — Vocês lembram de quando me desprezaram? Vocês disseram que não iam dar comida para o meu exército cansado porque eu ainda não tinha prendido Zeba e Salmuna. Muito bem, aqui estão eles!

[[v7-8-16]]

^<<v7-8-16,16>>^ Então pegou espinhos das plantas do deserto e com eles castigou os chefes de Sucote.

[[v7-8-17]]

^<<v7-8-17,17>>^ Também derrubou a torre de Penuel e matou os homens daquela cidade.

[[v7-8-18]]

^<<v7-8-18,18>>^ Aí perguntou a Zeba e Salmuna: — Com quem se pareciam os homens que vocês mataram em Tabor? E eles responderam: — Pareciam com você. Todos tinham jeito de príncipe.

[[v7-8-19]]

^<<v7-8-19,19>>^ Gideão disse: — Eles eram meus irmãos, filhos da minha mãe. Juro pelo Senhor  Deus que, se vocês não os tivessem matado, eu também não mataria vocês.

[[v7-8-20]]

^<<v7-8-20,20>>^ E disse a Jéter, o seu filho mais velho: — Levante-se e mate-os. Mas o rapaz não tirou a sua espada. Ele estava com medo, pois ainda era muito novo.

[[v7-8-21]]

^<<v7-8-21,21>>^ Então Zeba e Salmuna disseram a Gideão: — Venha você mesmo nos matar porque para isso é preciso ter coragem de homem. Aí Gideão matou Zeba e Salmuna e pegou os enfeites em forma de meia-lua que estavam no pescoço dos seus camelos.

[[v7-8-22]]

^<<v7-8-22,22>>^ Os homens de Israel disseram a Gideão: — Você nos salvou dos midianitas. Portanto, seja nosso governador. E, depois de você, o seu filho e o seu neto.

[[v7-8-23]]

^<<v7-8-23,23>>^ Gideão respondeu: — Eu não serei governador de vocês, e o meu filho também não. O Senhor  Deus é quem será o governador de vocês.

[[v7-8-24]]

^<<v7-8-24,24>>^ E continuou: — Mas vou fazer um pedido: cada um me dê um dos brincos que tirou dos vencidos. Os midianitas usavam argolas de ouro nas orelhas porque eram gente do deserto.

[[v7-8-25]]

^<<v7-8-25,25>>^ Os homens de Gideão responderam: — Nós os daremos com prazer a você. Então estenderam uma capa , e cada um pôs nela os brincos que tinha tomado dos midianitas.

[[v7-8-26]]

^<<v7-8-26,26>>^ Os brincos de ouro que Gideão pediu pesaram quase trinta quilos. Isso fora os enfeites, os colares e as roupas de púrpura  que os chefes de Midiã usavam. E sem contar também os enfeites que estavam no pescoço dos seus camelos.

[[v7-8-27]]

^<<v7-8-27,27>>^ Com o ouro Gideão fez um ídolo e o colocou em Ofra, a sua cidade. Então todos os israelitas abandonaram a Deus e iam lá para adorar o ídolo. E isso foi uma armadilha para Gideão e a sua gente.

[[v7-8-28]]

^<<v7-8-28,28>>^ Os midianitas foram derrotados pelos israelitas e por muito tempo deixaram de ser uma ameaça para eles. E a terra ficou em paz durante quarenta anos enquanto Gideão viveu.

[[v7-8-29]]

^<<v7-8-29,29>>^ Gideão voltou e ficou morando na sua própria casa.

[[v7-8-30]]

^<<v7-8-30,30>>^ Ele foi pai de setenta filhos, pois tinha muitas mulheres.

[[v7-8-31]]

^<<v7-8-31,31>>^ Ele também teve uma concubina  em Siquém, e ela lhe deu um filho. Gideão pôs nele o nome de Abimeleque.

[[v7-8-32]]

^<<v7-8-32,32>>^ Gideão, filho de Joás, morreu bem velho e foi sepultado no túmulo de Joás, o seu pai, em Ofra, a cidade do grupo de famílias de Abiezer.

[[v7-8-33]]

^<<v7-8-33,33>>^ Depois que Gideão morreu, o povo de Israel abandonou a Deus novamente e adorou os deuses dos cananeus. Eles adotaram Baal-Berite como o seu deus.

[[v7-8-34]]

^<<v7-8-34,34>>^ Não serviram por muito tempo ao Senhor  Deus, que os havia livrado de todos os inimigos que viviam ao redor deles.

[[v7-8-35]]

^<<v7-8-35,35>>^ E também não foram agradecidos à família de Gideão por tudo de bom que ele havia feito para o povo de Israel.

'''

xref:007-juizes/007-juizes-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-juizes/007-juizes-009.adoc#v7-9-0[Próximo Capítulo &#62;]