include::./index.adoc[]

[[v7-14-0]]
=== Juízes, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-14-1]]

^<<v7-14-1,1>>^ Sansão desceu até a cidade de Timna e ali viu uma moça filisteia.

[[v7-14-2]]

^<<v7-14-2,2>>^ Voltou para casa e disse ao seu pai e à sua mãe: — Eu vi em Timna uma jovem filisteia. Peçam essa moça para mim porque eu quero casar com ela.

[[v7-14-3]]

^<<v7-14-3,3>>^ Mas o seu pai e a sua mãe responderam: — Por que é que você foi procurar mulher no meio dos filisteus, aquela gente que não pratica a circuncisão ? Será que você não podia achar mulher no meio dos nossos parentes ou entre o nosso povo? Mas Sansão disse ao seu pai: — É aquela a moça que eu quero. É dela que eu gosto.

[[v7-14-4]]

^<<v7-14-4,4>>^ O seu pai e a sua mãe não sabiam que era o Senhor  Deus que estava orientando Sansão para fazer aquilo. Deus estava procurando uma oportunidade para atacar os filisteus, que naquele tempo dominavam o povo de Israel.

[[v7-14-5]]

^<<v7-14-5,5>>^ Sansão desceu com os seus pais até a cidade de Timna. Quando estavam passando pelas plantações de uvas de Timna, um leão novo veio rugindo para cima dele.

[[v7-14-6]]

^<<v7-14-6,6>>^ Mas o Espírito do Senhor  fez com que Sansão ficasse forte. Com as suas próprias mãos, Sansão despedaçou o leão, como se fosse um cabrito. Porém não contou nem ao seu pai nem à sua mãe o que havia feito.

[[v7-14-7]]

^<<v7-14-7,7>>^ Então ele foi conversar com a moça e gostou dela.

[[v7-14-8]]

^<<v7-14-8,8>>^ Poucos dias depois Sansão voltou lá para casar com ela. Saiu da estrada para dar uma olhada no leão que havia matado. E ficou espantado ao ver um enxame de abelhas e mel dentro do corpo do animal morto.

[[v7-14-9]]

^<<v7-14-9,9>>^ Então tirou mel com as mãos e saiu comendo. Foi até onde estavam o seu pai e a sua mãe e lhes deu um pouco. E eles comeram. Porém Sansão não lhes contou que havia tirado o mel do corpo do leão.

[[v7-14-10]]

^<<v7-14-10,10>>^ O pai de Sansão foi à casa da moça, e Sansão deu um banquete ali, como era o costume dos moços.

[[v7-14-11]]

^<<v7-14-11,11>>^ Quando os filisteus o viram, trouxeram trinta rapazes para festejar com ele.

[[v7-14-12]]

^<<v7-14-12,12>>^ E Sansão lhes disse: — Eu tenho uma adivinhação para vocês. Aposto trinta túnicas  de linho puro e trinta roupas finas que, antes de se passarem os sete dias da festa de casamento, vocês não me darão a resposta. Eles responderam: — Diga qual é a adivinhação.

[[v7-14-13]]

^<<v7-14-13,13>>^ E Sansão lhes disse:

[[v7-14-14]]

^<<v7-14-14,14>>^ Sansão disse: "Do que come saiu comida, e do forte saiu doçura." Três dias depois eles ainda não haviam encontrado a resposta para a adivinhação.

[[v7-14-15]]

^<<v7-14-15,15>>^ No quarto dia disseram à mulher de Sansão: — Dê um jeito de fazer o seu marido dar a resposta da adivinhação. Se você não fizer isso, nós vamos pôr fogo na casa do seu pai e vamos queimar você junto. Vocês só nos convidaram para poder nos roubar, não foi?

[[v7-14-16]]

^<<v7-14-16,16>>^ Aí a mulher de Sansão lhe disse, chorando: — Você não me ama! Você me odeia! Você deu uma adivinhação aos meus amigos e não me contou a resposta! — Eu não contei nem para o meu pai nem para a minha mãe! — respondeu ele. — Por que acha que eu iria contar para você?

[[v7-14-17]]

^<<v7-14-17,17>>^ Então ela chorou durante os outros dias da festa. No sétimo dia, como a mulher não parava de insistir, ele disse a resposta. E ela contou aos seus amigos.

[[v7-14-18]]

^<<v7-14-18,18>>^ Assim, no sétimo dia, antes de anoitecer, os homens da cidade disseram a Sansão: "Que coisa é mais doce do que o mel? E o que é mais forte do que o leão?" Sansão respondeu: — Se vocês não tivessem conversado com a minha mulher, não saberiam agora a resposta.

[[v7-14-19]]

^<<v7-14-19,19>>^ Então o Espírito do Senhor  fez com que Sansão ficasse forte, e ele desceu até Asquelom e ali matou trinta homens. Tirou as roupas finas que eles vestiam e as deu aos rapazes que tinham respondido à adivinhação. Depois voltou para a casa do seu pai, furioso com o que havia acontecido.

'''

xref:007-juizes/007-juizes-013.adoc#v7-13-0[&#60; Capítulo Anterior] | <<v7-14-0,Topo>> | xref:007-juizes/007-juizes-015.adoc#v7-15-0[Próximo Capítulo &#62;]