include::./index.adoc[]

[[v7-15-0]]
=== Juízes, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-15-1]]

^<<v7-15-1,1>>^ Algum tempo depois, durante a colheita do trigo, Sansão foi visitar a sua mulher e levou para ela um cabrito. E disse ao pai dela: — Quero entrar no quarto da minha mulher. Mas o pai não deixou

[[v7-15-2]]

^<<v7-15-2,2>>^ e respondeu: — Eu pensei que você a odiava, e por isso a dei em casamento ao seu amigo. Mas a irmã menor é ainda mais bonita. Se você quiser, pode ficar com ela.

[[v7-15-3]]

^<<v7-15-3,3>>^ Sansão disse: — Desta vez eu não sou responsável pelo que fizer com os filisteus.

[[v7-15-4]]

^<<v7-15-4,4>>^ Então caçou trezentas raposas, amarrou-as duas a duas pelos rabos e prendeu em cada par de rabos uma tocha.

[[v7-15-5]]

^<<v7-15-5,5>>^ Pôs fogo nas tochas e soltou as raposas nas plantações de trigo dos filisteus. E o fogo queimou não só o trigo que já havia sido colhido, mas também o que ainda estava nas plantações. Também os bosques de oliveiras foram queimados.

[[v7-15-6]]

^<<v7-15-6,6>>^ E os filisteus perguntaram: — Quem foi que fez isso? E ficaram sabendo que Sansão tinha feito aquilo porque o seu sogro havia tomado a mulher dele e dado ao seu amigo. Então os filisteus foram e queimaram viva a mulher de Sansão e a família dela.

[[v7-15-7]]

^<<v7-15-7,7>>^ Aí Sansão disse: — Então é assim que vocês fazem? Pois eu juro que não descansarei até que paguem por isso!

[[v7-15-8]]

^<<v7-15-8,8>>^ E atacou furiosamente, matando muitos deles. Depois saiu de lá e foi para a caverna da rocha de Etã.

[[v7-15-9]]

^<<v7-15-9,9>>^ Os filisteus foram, acamparam em Judá e atacaram a cidade de Leí .

[[v7-15-10]]

^<<v7-15-10,10>>^ Os homens de Judá perguntaram aos filisteus: — Por que foi que vocês nos atacaram? E eles responderam: — Viemos até aqui para prender Sansão e fazer com ele o mesmo que ele fez com a gente.

[[v7-15-11]]

^<<v7-15-11,11>>^ Então três mil homens de Judá foram falar com Sansão na caverna da rocha de Etã. E disseram: — Você não sabe que os filisteus mandam em nós? Por que você foi fazer aquilo? — Eu fiz com eles o que eles fizeram comigo! — respondeu Sansão.

[[v7-15-12]]

^<<v7-15-12,12>>^ — Nós viemos até aqui para amarrar e entregar você aos filisteus! — disseram eles. Sansão respondeu: — Prometam que vocês não me matarão.

[[v7-15-13]]

^<<v7-15-13,13>>^ — Prometemos! — disseram eles. — Nós vamos somente amarrar você e entregar aos filisteus. Não vamos matá-lo. Então o amarraram com duas cordas novas e o fizeram sair da caverna.

[[v7-15-14]]

^<<v7-15-14,14>>^ Quando Sansão chegou a Leí, os filisteus, gritando, vieram encontrá-lo. Mas o Espírito do Senhor  fez com que Sansão ficasse forte. E ele arrebentou as cordas que amarravam os seus braços e as suas mãos, como se fossem fios de linha queimados.

[[v7-15-15]]

^<<v7-15-15,15>>^ Encontrou por ali uma queixada de jumento que ainda não estava seca. Pegou a queixada e com ela matou mil homens.

[[v7-15-16]]

^<<v7-15-16,16>>^ Aí começou a cantar assim: "Com a queixada de um jumento, matei mil homens. Com a queixada de um jumento, fiz montões e montões de corpos ."

[[v7-15-17]]

^<<v7-15-17,17>>^ Depois jogou fora a queixada. E aquele lugar foi chamado de "monte da Queixada".

[[v7-15-18]]

^<<v7-15-18,18>>^ Sansão ficou com muita sede e fez esta oração a Deus, o Senhor : — Tu me deste esta grande vitória. Será que agora vais deixar que eu morra de sede e caia nas mãos desta gente que não pratica a circuncisão ?

[[v7-15-19]]

^<<v7-15-19,19>>^ Então, na cidade de Leí, Deus abriu um buraco, e dele saiu água. Sansão bebeu daquela água e sentiu-se bem melhor. Aquela fonte foi chamada de En-Hacoré e existe até hoje .

[[v7-15-20]]

^<<v7-15-20,20>>^ Sansão governou o povo de Israel vinte anos, na época em que os filisteus dominavam aquela terra.

'''

xref:007-juizes/007-juizes-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-juizes/007-juizes-016.adoc#v7-16-0[Próximo Capítulo &#62;]