include::./index.adoc[]

[[v7-13-0]]
=== Juízes, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-13-1]]

^<<v7-13-1,1>>^ Os israelitas pecaram outra vez contra Deus, o Senhor , e por isso ele deixou que sofressem quarenta anos nas mãos dos filisteus.

[[v7-13-2]]

^<<v7-13-2,2>>^ Havia um homem chamado Manoá, que era da cidade de Zora e pertencia à tribo  de Dã. A sua mulher não podia ter filhos.

[[v7-13-3]]

^<<v7-13-3,3>>^ O Anjo do Senhor  apareceu a ela e disse: — Você não podia ter filhos e por isso nunca foi mãe. Mas agora você ficará grávida e terá um filho.

[[v7-13-4]]

^<<v7-13-4,4>>^ Não tome vinho nem cerveja e não coma nenhuma comida proibida

[[v7-13-5]]

^<<v7-13-5,5>>^ porque você ficará grávida e dará à luz um filho. Não corte nunca o cabelo dele, pois ele será consagrado a Deus como nazireu  desde o dia do seu nascimento. Ele vai começar a livrar o povo de Israel do poder dos filisteus.

[[v7-13-6]]

^<<v7-13-6,6>>^ Então a mulher procurou o marido e disse: — Um homem de Deus falou comigo. Ele parecia um anjo de Deus, e isso me deixou apavorada. Eu não perguntei de onde ele vinha, e ele não me disse como se chamava.

[[v7-13-7]]

^<<v7-13-7,7>>^ Mas prometeu que eu ficarei grávida e que terei um filho. E mandou que eu não beba vinho nem cerveja e não coma nenhuma comida proibida, pois o menino será dedicado a Deus como nazireu por toda a vida.

[[v7-13-8]]

^<<v7-13-8,8>>^ Então Manoá orou ao Senhor , dizendo: — Ó meu Deus, peço que mandes de volta o homem de Deus que enviaste, para ele nos dizer o que devemos fazer com o menino quando nascer.

[[v7-13-9]]

^<<v7-13-9,9>>^ Deus fez o que Manoá pediu: o Anjo apareceu de novo à sua mulher quando ela estava sentada no campo. E o marido não estava por perto.

[[v7-13-10]]

^<<v7-13-10,10>>^ Então ela correu depressa para o lugar onde ele estava e disse: — O homem que falou comigo outro dia apareceu novamente.

[[v7-13-11]]

^<<v7-13-11,11>>^ Manoá se levantou e seguiu a mulher. Foi até onde estava o homem e perguntou: — Você é o homem que falou com a minha mulher? — Sim! — respondeu ele.

[[v7-13-12]]

^<<v7-13-12,12>>^ Então Manoá disse: — Quando acontecer o que você falou, como é que o menino deverá agir? O que deverá fazer?

[[v7-13-13]]

^<<v7-13-13,13>>^ O Anjo do Senhor  respondeu: — A sua mulher deve fazer tudo o que eu já disse a ela.

[[v7-13-14]]

^<<v7-13-14,14>>^ Não vai comer nada que seja feito de uvas. Não vai tomar nem vinho nem cerveja e não vai comer nenhuma comida proibida. Ela deve fazer tudo o que eu disse.

[[v7-13-15]]

^<<v7-13-15,15>>^ Manoá não sabia que aquele era o Anjo do Senhor . E disse: — Por favor, não vá embora ainda. Espere, que nós vamos cozinhar um cabrito para você. — Se eu ficar, não comerei a sua comida! — respondeu o Anjo. — Mas, se você quiser prepará-la, então queime-a como oferta ao Senhor .

[[v7-13-16]]

^<<v7-13-16,16>>^ Manoá não sabia que aquele era o Anjo do Senhor . E disse:

[[v7-13-17]]

^<<v7-13-17,17>>^ Manoá disse: — Qual é o seu nome? Nós precisamos saber para poder prestar-lhe uma homenagem quando acontecer aquilo que você disse.

[[v7-13-18]]

^<<v7-13-18,18>>^ — Por que você quer saber o meu nome? — perguntou o Anjo. — O meu nome é um mistério.

[[v7-13-19]]

^<<v7-13-19,19>>^ Então Manoá pegou o cabrito e cereais e os ofereceu numa pedra ao Senhor , o Deus dos mistérios.

[[v7-13-20]]

^<<v7-13-20,20>>^ Enquanto as chamas subiam do altar, Manoá e a sua mulher viram o Anjo do Senhor  subir para o céu, no meio das chamas. Aí se ajoelharam e encostaram o rosto no chão.

[[v7-13-21]]

^<<v7-13-21,21>>^ Manoá e a sua mulher nunca mais viram o Anjo. E Manoá compreendeu que aquele homem era o Anjo do Senhor .

[[v7-13-22]]

^<<v7-13-22,22>>^ Então disse à mulher: — Nós vamos morrer porque vimos Deus!

[[v7-13-23]]

^<<v7-13-23,23>>^ Porém ela respondeu: — Se o Senhor  nos quisesse matar, não teria aceitado nossas ofertas. Ele não nos teria mostrado tudo isso, nem falado todas essas coisas.

[[v7-13-24]]

^<<v7-13-24,24>>^ A mulher de Manoá deu à luz um filho e pôs nele o nome de Sansão. O menino cresceu, e o Senhor  o abençoou.

'''

xref:007-juizes/007-juizes-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-juizes/007-juizes-014.adoc#v7-14-0[Próximo Capítulo &#62;]