include::./index.adoc[]

[[v7-10-0]]
=== Juízes, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-10-1]]

^<<v7-10-1,1>>^ Depois de Abimeleque, Tolá, filho de Puá e neto de Dodo, veio libertar o povo de Israel. Ele era da tribo  de Issacar e morava na cidade de Samir, na região montanhosa de Efraim.

[[v7-10-2]]

^<<v7-10-2,2>>^ Tolá foi líder de Israel durante vinte e três anos. Depois morreu e foi sepultado em Samir.

[[v7-10-3]]

^<<v7-10-3,3>>^ Em seguida apareceu Jair, da terra de Gileade. Jair foi líder de Israel durante vinte e dois anos.

[[v7-10-4]]

^<<v7-10-4,4>>^ Ele tinha trinta filhos, que montavam trinta jumentos. Os seus filhos tinham trinta cidades na região de Gileade. Elas são chamadas até hoje  de "cidades de Jair".

[[v7-10-5]]

^<<v7-10-5,5>>^ Jair morreu e foi sepultado em Camom.

[[v7-10-6]]

^<<v7-10-6,6>>^ E mais uma vez os israelitas pecaram contra Deus, o Senhor . Adoraram o deus Baal  de várias cidades, a deusa Astarote  e também os deuses da Síria, de Sidom, de Moabe, de Amom e dos filisteus. Eles abandonaram o Senhor  e deixaram de adorá-lo.

[[v7-10-7]]

^<<v7-10-7,7>>^ Então ele ficou muito irado  com os israelitas e deixou que sofressem nas mãos dos filisteus e dos amonitas.

[[v7-10-8]]

^<<v7-10-8,8>>^ Naquele mesmo ano eles derrotaram os israelitas e os escravizaram. Durante dezoito anos eles escravizaram todos os israelitas que viviam em Gileade, a leste do rio Jordão, na terra dos amorreus.

[[v7-10-9]]

^<<v7-10-9,9>>^ Os amonitas também atravessaram o rio Jordão para lutar contra as tribos  de Judá, de Benjamim e de Efraim. E assim Israel passava por uma grande aflição.

[[v7-10-10]]

^<<v7-10-10,10>>^ Então os israelitas pediram socorro a Deus, o Senhor , orando assim: — Nosso Deus, nós pecamos contra ti porque te deixamos e adoramos os deuses dos cananeus.

[[v7-10-11]]

^<<v7-10-11,11>>^ E o Senhor  respondeu: — No passado os egípcios, os amorreus, os amonitas, os filisteus,

[[v7-10-12]]

^<<v7-10-12,12>>^ os sidônios, os amalequitas e os maonitas escravizaram vocês, e vocês me pediram socorro. E eu os salvei deles.

[[v7-10-13]]

^<<v7-10-13,13>>^ Mas assim mesmo vocês me abandonaram e adoraram outros deuses. Por isso eu não vou mais ajudá-los.

[[v7-10-14]]

^<<v7-10-14,14>>^ Agora peçam socorro aos deuses que vocês escolheram. Que eles os ajudem quando vocês estiverem em dificuldades!

[[v7-10-15]]

^<<v7-10-15,15>>^ Mas o povo de Israel respondeu: — De fato, nós pecamos. Faze de nós o que quiseres. Mas salva-nos hoje, por favor.

[[v7-10-16]]

^<<v7-10-16,16>>^ Então eles jogaram fora os seus deuses estrangeiros e adoraram a Deus, o Senhor . E ele teve pena deles por causa da situação difícil em que estavam.

[[v7-10-17]]

^<<v7-10-17,17>>^ Então o exército amonita veio e acampou em Mispa.

[[v7-10-18]]

^<<v7-10-18,18>>^ E os chefes e o povo de Gileade combinaram que o homem que comandasse os israelitas na luta contra os amonitas seria o chefe dos moradores de Gileade.

'''

xref:007-juizes/007-juizes-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-juizes/007-juizes-011.adoc#v7-11-0[Próximo Capítulo &#62;]