include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-21-1]]

^<<v7-21-1,1>>^ O povo de Israel havia feito em Mispa este juramento a Deus: — Nenhum de nós deixará que um homem da tribo  de Benjamim case com uma das nossas filhas.

[[v7-21-2]]

^<<v7-21-2,2>>^ O povo foi a Betel e ficou ali na presença de Deus até a tarde. Eles choraram amargamente, em voz alta,

[[v7-21-3]]

^<<v7-21-3,3>>^ dizendo: — Ó Senhor , Deus de Israel, por que aconteceu isso? Por que está faltando uma das nossas tribos?

[[v7-21-4]]

^<<v7-21-4,4>>^ O povo se levantou bem cedo na manhã seguinte e construiu ali um altar. Apresentaram ofertas que foram completamente queimadas e sacrifícios  de paz.

[[v7-21-5]]

^<<v7-21-5,5>>^ E perguntaram: — De todas as tribos de Israel, quem foi que não subiu para aquela reunião na presença do Senhor  Deus, em Mispa? Eles tinham feito um juramento muito sério: quem faltasse à reunião em Mispa seria morto.

[[v7-21-6]]

^<<v7-21-6,6>>^ O povo de Israel teve muita pena dos seus irmãos da tribo de Benjamim e disse: — Hoje Israel perdeu uma das suas tribos.

[[v7-21-7]]

^<<v7-21-7,7>>^ O que faremos para arranjar esposas para os que ficaram? Pois juramos ao Senhor  que não daríamos a eles nenhuma das nossas filhas.

[[v7-21-8]]

^<<v7-21-8,8>>^ Então perguntaram: — De todas as tribos de Israel, quem não compareceu diante do Senhor  em Mispa? E ficaram sabendo que, de Jabes-Gileade, ninguém havia tomado parte na reunião.

[[v7-21-9]]

^<<v7-21-9,9>>^ Quando fizeram a chamada do povo, ninguém de Jabes-Gileade estava lá.

[[v7-21-10]]

^<<v7-21-10,10>>^ Então todos concordaram em mandar para lá doze mil homens, dos mais corajosos, com estas ordens: — Vão e matem os moradores de Jabes-Gileade, tanto homens como mulheres e crianças.

[[v7-21-11]]

^<<v7-21-11,11>>^ Façam isto: matem todos os homens e todas as mulheres que não forem virgens.

[[v7-21-12]]

^<<v7-21-12,12>>^ E eles encontraram quatrocentas virgens em Jabes-Gileade e as levaram ao acampamento de Siló, que fica na terra de Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Então todos concordaram em mandar mensageiros aos benjamitas, na rocha de Rimom, para fazer uma proposta de paz.

[[v7-21-14]]

^<<v7-21-14,14>>^ Aí os benjamitas voltaram e receberam aquelas quatrocentas moças de Jabes-Gileade. Porém não havia moças em número suficiente para todos.

[[v7-21-15]]

^<<v7-21-15,15>>^ Então o povo ficou com pena dos benjamitas, pois pela vontade do Senhor  estava faltando uma das tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ Aí os chefes do povo de Israel disseram: — Não há mais mulheres na tribo de Benjamim. O que vamos fazer para arranjar esposas para os que ficaram?

[[v7-21-17]]

^<<v7-21-17,17>>^ O povo de Israel não deve perder uma das suas doze tribos. Temos de achar um jeito de a tribo de Benjamim não acabar.

[[v7-21-18]]

^<<v7-21-18,18>>^ Porém não podemos deixar que eles casem com as nossas filhas. Eles falavam isso porque o povo de Israel havia amaldiçoado quem deixasse um benjamita casar com a sua filha.

[[v7-21-19]]

^<<v7-21-19,19>>^ Então disseram: — A festa anual do Senhor , na cidade de Siló, está perto. (Siló fica ao norte de Betel, ao sul de Lebona e a leste da estrada que vai de Betel a Siquém.)

[[v7-21-20]]

^<<v7-21-20,20>>^ E os chefes do povo de Israel disseram aos benjamitas: — Vão, escondam-se nas plantações de uvas

[[v7-21-21]]

^<<v7-21-21,21>>^ e fiquem vigiando. Durante a festa, quando as moças de Siló saírem dançando, vocês também saiam das plantações de uvas. E cada um agarre uma das moças e leve embora para a terra de Benjamim.

[[v7-21-22]]

^<<v7-21-22,22>>^ Assim, quando os pais ou irmãos delas vierem se queixar, nós poderemos dizer: "Por favor, deixem que elas fiquem, pois na batalha contra Jabes-Gileade não conseguimos mulheres para todos os benjamitas. E vocês não serão culpados de quebrarem a promessa, pois não deram as suas filhas a eles: elas foram roubadas."

[[v7-21-23]]

^<<v7-21-23,23>>^ E assim fizeram os benjamitas. Cada um deles escolheu uma esposa entre as moças que estavam dançando e a levou embora. Então voltaram para a sua terra, construíram de novo as suas cidades e ficaram morando ali.

[[v7-21-24]]

^<<v7-21-24,24>>^ Enquanto isso, os outros israelitas saíram, e cada um voltou para a sua tribo, a sua família e as suas terras.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naquele tempo não havia rei em Israel, e cada um fazia o que bem queria.

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]