include::./index.adoc[]

[[v7-20-0]]
=== Juízes, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-20-1]]

^<<v7-20-1,1>>^ Por causa disso todo o povo de Israel, desde Dã, no Norte, até Berseba, no Sul, e Gileade, no Leste, se reuniu em Mispa. Eles se reuniram na presença de Deus, o Senhor , como se fossem uma só pessoa.

[[v7-20-2]]

^<<v7-20-2,2>>^ Os chefes de todas as tribos  de Israel estavam presentes nessa reunião do povo de Deus. Havia quatrocentos mil homens a pé, treinados para a guerra.

[[v7-20-3]]

^<<v7-20-3,3>>^ E o povo de Benjamim soube que todos os outros israelitas haviam subido até Mispa e que eles queriam saber como aquele crime havia sido cometido.

[[v7-20-4]]

^<<v7-20-4,4>>^ Então o levita , marido da mulher assassinada, explicou: — Cheguei com a minha concubina  a Gibeá, no território da tribo de Benjamim, para passar a noite.

[[v7-20-5]]

^<<v7-20-5,5>>^ Os homens de Gibeá vieram de noite e cercaram a casa. Eles queriam me matar. Em vez disso abusaram da minha concubina, e ela morreu.

[[v7-20-6]]

^<<v7-20-6,6>>^ Então eu peguei o corpo dela, cortei em pedaços e mandei um pedaço para cada uma das doze tribos de Israel. Aquela gente cometeu um crime horrível no meio do nosso povo.

[[v7-20-7]]

^<<v7-20-7,7>>^ Todos vocês que estão aqui são israelitas. Vamos resolver agora o que fazer.

[[v7-20-8]]

^<<v7-20-8,8>>^ Todo o povo de Israel se levantou ao mesmo tempo e disse: — Nenhum de nós, nem os que moram em casas, nem os que moram em barracas, voltará para casa.

[[v7-20-9]]

^<<v7-20-9,9>>^ Vamos escolher alguns homens para atacar Gibeá.

[[v7-20-10]]

^<<v7-20-10,10>>^ A décima parte dos homens de Israel vai arranjar comida para os que vão lutar. Os outros vão castigar os moradores de Gibeá pelo crime horrível que cometeram em Israel.

[[v7-20-11]]

^<<v7-20-11,11>>^ Então todo o povo de Israel se reuniu como se fosse uma só pessoa para atacar a cidade de Gibeá.

[[v7-20-12]]

^<<v7-20-12,12>>^ As tribos israelitas mandaram que mensageiros fossem por toda a tribo de Benjamim e dissessem: — Que crime horrível vocês cometeram!

[[v7-20-13]]

^<<v7-20-13,13>>^ Exigimos que vocês nos entreguem agora esses homens imorais para que nós os matemos. Assim tiraremos esse mal do meio do povo de Israel. Mas o povo de Benjamim não deu atenção aos outros israelitas.

[[v7-20-14]]

^<<v7-20-14,14>>^ Eles saíram de todas as suas cidades e foram para Gibeá a fim de lutar contra o resto do povo de Israel.

[[v7-20-15]]

^<<v7-20-15,15>>^ Naquele dia eles convocaram das suas cidades vinte e seis mil soldados. Depois os moradores de Gibeá reuniram mais setecentos homens especialmente escolhidos,

[[v7-20-16]]

^<<v7-20-16,16>>^ que eram canhotos. Qualquer um deles podia atirar com funda  uma pedra num fio de cabelo, sem nunca errar.

[[v7-20-17]]

^<<v7-20-17,17>>^ E os outros israelitas que iam lutar contra a tribo de Benjamim reuniram quatrocentos mil soldados treinados.

[[v7-20-18]]

^<<v7-20-18,18>>^ Os israelitas foram ao lugar de adoração, em Betel, e ali perguntaram a Deus: — Qual das nossas tribos  atacará primeiro a tribo de Benjamim? E o Senhor  respondeu: — A tribo de Judá.

[[v7-20-19]]

^<<v7-20-19,19>>^ Na manhã seguinte os israelitas subiram e acamparam perto da cidade de Gibeá.

[[v7-20-20]]

^<<v7-20-20,20>>^ Saíram para combater contra a tribo de Benjamim e puseram os soldados em posição de ataque, de frente para a cidade.

[[v7-20-21]]

^<<v7-20-21,21>>^ Então o exército de Benjamim saiu da cidade. E, antes de terminar o dia, eles mataram vinte e dois mil soldados israelitas.

[[v7-20-22]]

^<<v7-20-22,22>>^ Aí o povo de Israel foi para o lugar de adoração e, na presença do Senhor , chorou até a tarde. E eles perguntaram ao Senhor : — Devemos ir combater outra vez os nossos irmãos da tribo de Benjamim? E Deus respondeu: — Sim. Então o exército israelita se animou de novo. E eles puseram os seus soldados em posição de combate novamente, no mesmo lugar em que haviam lutado no dia anterior.

[[v7-20-23]]

^<<v7-20-23,23>>^ Aí o povo de Israel foi para o lugar de adoração e, na presença do Senhor , chorou até a tarde. E eles perguntaram ao Senhor :

[[v7-20-24]]

^<<v7-20-24,24>>^ Os israelitas marcharam contra a tribo de Benjamim pela segunda vez.

[[v7-20-25]]

^<<v7-20-25,25>>^ E pela segunda vez os soldados de Benjamim saíram de Gibeá. E dessa vez mataram dezoito mil soldados israelitas treinados.

[[v7-20-26]]

^<<v7-20-26,26>>^ Então todo o povo de Israel subiu de novo até Betel para chorar. Ficaram ali na presença de Deus, o Senhor , e não comeram nada até a tarde. E apresentaram ao Senhor  ofertas que foram completamente queimadas e sacrifícios  de paz.

[[v7-20-27]]

^<<v7-20-27,27>>^ Eles fizeram uma pergunta ao Senhor . (Acontece que naqueles dias a arca da aliança  estava ali em Betel.

[[v7-20-28]]

^<<v7-20-28,28>>^ E Fineias, filho de Eleazar e neto de Arão, estava encarregado de cuidar dela.) A pergunta que eles fizeram foi esta: — Devemos sair mais uma vez para combater os nossos irmãos da tribo de Benjamim ou devemos desistir? O Senhor  respondeu: — Combatam porque amanhã eu farei com que vocês os derrotem.

[[v7-20-29]]

^<<v7-20-29,29>>^ Então os israelitas puseram alguns soldados escondidos em volta de Gibeá.

[[v7-20-30]]

^<<v7-20-30,30>>^ No terceiro dia marcharam de novo contra o exército da tribo de Benjamim. Os seus soldados ficaram em posição de batalha, de frente para Gibeá, como tinham feito antes.

[[v7-20-31]]

^<<v7-20-31,31>>^ Os soldados de Benjamim saíram para combater e se afastaram da cidade. Como haviam feito antes, começaram a matar algumas pessoas na estrada de Betel, na estrada de Gibeá e em campo aberto. Mataram mais ou menos trinta israelitas.

[[v7-20-32]]

^<<v7-20-32,32>>^ E diziam: — Nós já os derrotamos, como das outras vezes. Mas os israelitas disseram: — Vamos recuar e fazer com que eles se afastem da cidade e venham para as estradas.

[[v7-20-33]]

^<<v7-20-33,33>>^ Então a maior parte do exército israelita saiu dali e tornou a se juntar em Baal-Tamar. Mas os homens que cercavam a cidade saíram de repente dos lugares onde estavam escondidos na planície de Gibeá.

[[v7-20-34]]

^<<v7-20-34,34>>^ Dez mil dos melhores soldados israelitas atacaram Gibeá, e o combate foi duro. Os benjamitas não imaginavam que iam ser destruídos.

[[v7-20-35]]

^<<v7-20-35,35>>^ O Senhor  Deus fez com que os israelitas derrotassem o exército de Benjamim. E naquele dia os israelitas mataram vinte e cinco mil e cem inimigos.

[[v7-20-36]]

^<<v7-20-36,36>>^ Então os benjamitas compreenderam que estavam vencidos. Os israelitas tinham se retirado durante a luta contra os benjamitas porque confiavam nos homens que haviam colocado escondidos em volta de Gibeá.

[[v7-20-37]]

^<<v7-20-37,37>>^ Esses homens avançaram depressa na direção de Gibeá, espalharam-se e mataram todas as pessoas da cidade.

[[v7-20-38]]

^<<v7-20-38,38>>^ O exército israelita e os homens que estavam escondidos tinham combinado um sinal: quando vissem uma grande nuvem de fumaça subindo da cidade,

[[v7-20-39]]

^<<v7-20-39,39>>^ os israelitas que estavam fora, no campo de batalha, deviam dar meia-volta e atacar. Até aquele momento os benjamitas já haviam matado uns trinta israelitas e diziam: — Sim. Já os derrotamos, como das outras vezes.

[[v7-20-40]]

^<<v7-20-40,40>>^ Então o sinal apareceu: uma nuvem de fumaça começou a subir da cidade. Os benjamitas olharam para trás e ficaram muito espantados quando viram a cidade inteira pegando fogo.

[[v7-20-41]]

^<<v7-20-41,41>>^ Então os homens de Israel deram meia-volta, e os benjamitas ficaram apavorados porque viram que iam ser destruídos.

[[v7-20-42]]

^<<v7-20-42,42>>^ Eles fugiram e correram na direção do deserto, mas não puderam escapar. Foram cercados pela maior parte do exército israelita e também pelos soldados que vinham da cidade e foram destruídos.

[[v7-20-43]]

^<<v7-20-43,43>>^ Os israelitas cercaram os inimigos, e os perseguiram sem parar até um lugar a leste de Gibeá, e os iam matando pelo caminho.

[[v7-20-44]]

^<<v7-20-44,44>>^ Dezoito mil dos melhores soldados benjamitas foram mortos.

[[v7-20-45]]

^<<v7-20-45,45>>^ Os outros fugiram na direção do deserto, para a rocha de Rimom. Cinco mil foram mortos nas estradas. Os israelitas perseguiram o resto e assim mataram mais dois mil homens.

[[v7-20-46]]

^<<v7-20-46,46>>^ Ao todo vinte e cinco mil benjamitas foram mortos naquele dia, todos eles soldados valentes.

[[v7-20-47]]

^<<v7-20-47,47>>^ Porém seiscentos homens fugiram para o deserto, para a rocha de Rimom, e ficaram lá quatro meses.

'''

xref:007-juizes/007-juizes-019.adoc#v7-19-0[&#60; Capítulo Anterior] | <<v7-20-0,Topo>> | xref:007-juizes/007-juizes-021.adoc#v7-21-0[Próximo Capítulo &#62;]