include::./index.adoc[]

[[v7-3-0]]
=== Juízes, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-3-1]]

^<<v7-3-1,1>>^ O Senhor  Deus deixou alguns povos na terra para pôr à prova os israelitas que não haviam tomado parte nas guerras de Canaã.

[[v7-3-2]]

^<<v7-3-2,2>>^ Ele fez isso somente para ensinar todos os israelitas a guerrear, especialmente aqueles que nunca haviam estado numa batalha.

[[v7-3-3]]

^<<v7-3-3,3>>^ Os povos que ficaram na terra foram: os moradores das cinco cidades dos filisteus, todos os cananeus, os sidônios e os heveus que viviam nos montes Líbanos, desde o monte Baal-Hermom até a subida de Hamate.

[[v7-3-4]]

^<<v7-3-4,4>>^ Eles ficaram para pôr à prova o povo de Israel a fim de que o Senhor  visse se eles iam ou não obedecer aos mandamentos que lhes tinha dado por meio de Moisés.

[[v7-3-5]]

^<<v7-3-5,5>>^ Assim o povo de Israel ficou morando no meio dos cananeus, dos heteus, dos amorreus, dos perizeus, dos heveus e dos jebuseus.

[[v7-3-6]]

^<<v7-3-6,6>>^ E os israelitas casaram com essa gente e adoraram os seus deuses.

[[v7-3-7]]

^<<v7-3-7,7>>^ O povo de Israel esqueceu o Senhor , seu Deus. Pecou contra ele e adorou os deuses dos cananeus e os postes da deusa Aserá .

[[v7-3-8]]

^<<v7-3-8,8>>^ Por isso o Senhor  ficou muito irado  com Israel e deixou que Cuchã-Risataim, rei da Mesopotâmia, os conquistasse. E o povo de Israel foi dominado por ele durante oito anos.

[[v7-3-9]]

^<<v7-3-9,9>>^ Então os israelitas pediram socorro ao Senhor , e ele mandou um homem para libertá-los. Esse homem foi Otoniel, filho de Quenaz, o irmão mais novo de Calebe.

[[v7-3-10]]

^<<v7-3-10,10>>^ Ele foi guiado pelo Espírito de Deus, o Senhor , e se tornou o líder de Israel. Otoniel foi para a guerra, e o Senhor  fez com que ele vencesse o rei da Mesopotâmia.

[[v7-3-11]]

^<<v7-3-11,11>>^ Depois disso Otoniel ainda viveu quarenta anos, e durante todo esse tempo a terra de Israel ficou em paz.

[[v7-3-12]]

^<<v7-3-12,12>>^ Depois da morte de Otoniel, o povo de Israel pecou outra vez contra Deus, o Senhor . Por causa disso o Senhor  fez com que Eglom, rei de Moabe, ficasse mais forte do que eles.

[[v7-3-13]]

^<<v7-3-13,13>>^ Eglom se juntou com os amonitas e os amalequitas, e eles atacaram Israel e tomaram Jericó, a cidade das palmeiras.

[[v7-3-14]]

^<<v7-3-14,14>>^ O povo de Israel foi dominado por Eglom durante dezoito anos.

[[v7-3-15]]

^<<v7-3-15,15>>^ Então os israelitas pediram outra vez socorro ao Senhor , e ele mandou outro homem para libertá-los. Foi Eúde, filho de Gera, da tribo  de Benjamim. Eúde era canhoto. O povo de Israel mandou-o levar o pagamento dos impostos para Eglom, rei de Moabe.

[[v7-3-16]]

^<<v7-3-16,16>>^ Então Eúde fez um grande punhal, de mais ou menos meio metro de comprimento. Ele amarrou o punhal debaixo da roupa, do lado direito,

[[v7-3-17]]

^<<v7-3-17,17>>^ e foi levar os impostos a Eglom, que era muito gordo.

[[v7-3-18]]

^<<v7-3-18,18>>^ Depois de entregá-los, Eúde mandou embora os carregadores.

[[v7-3-19]]

^<<v7-3-19,19>>^ Mas ele voltou do lugar onde estavam as imagens de pedra, perto de Gilgal, e disse ao rei: — Ó rei, tenho uma informação secreta para lhe dar. Então o rei ordenou que todos os outros saíssem da sala. E todos saíram.

[[v7-3-20]]

^<<v7-3-20,20>>^ O rei estava sentado na sua sala de verão, no terraço. Eúde chegou perto dele e disse: — Tenho um recado de Deus para o senhor. O rei se levantou.

[[v7-3-21]]

^<<v7-3-21,21>>^ Então Eúde, com a mão esquerda, tirou o punhal que estava no seu lado direito e o enterrou na barriga de Eglom.

[[v7-3-22]]

^<<v7-3-22,22>>^ O punhal entrou até o cabo, e a gordura o cobriu porque Eúde não o tirou da barriga do rei. E a ponta do punhal apareceu entre as suas pernas.

[[v7-3-23]]

^<<v7-3-23,23>>^ Em seguida Eúde trancou as portas, saiu pela janela

[[v7-3-24]]

^<<v7-3-24,24>>^ e foi embora. Aí os empregados chegaram e viram que as portas estavam trancadas. Então pensaram que o rei tinha ido ao banheiro.

[[v7-3-25]]

^<<v7-3-25,25>>^ Esperaram muito tempo, mas, como ele não abria a porta, pegaram a chave e a abriram. E o rei estava morto, caído no chão.

[[v7-3-26]]

^<<v7-3-26,26>>^ Enquanto eles estavam esperando, Eúde fugiu. Passou pelas imagens de pedra e foi para Seirá.

[[v7-3-27]]

^<<v7-3-27,27>>^ Quando chegou lá, nas montanhas de Efraim, ele tocou uma corneta de chifre de carneiro para chamar os homens de Israel para a luta. Ele os guiou montanha abaixo,

[[v7-3-28]]

^<<v7-3-28,28>>^ dizendo: — Sigam-me. O Senhor  Deus deu a vocês a vitória sobre os inimigos, os moabitas. Então os israelitas o seguiram e tomaram o lugar onde os moabitas costumavam atravessar o rio Jordão. E não deixaram ninguém atravessar.

[[v7-3-29]]

^<<v7-3-29,29>>^ Nessa batalha eles mataram mais ou menos dez mil soldados moabitas, todos fortes e valentes. E nem um escapou.

[[v7-3-30]]

^<<v7-3-30,30>>^ Assim os israelitas derrotaram Moabe naquele dia. E houve paz na terra de Israel durante oitenta anos.

[[v7-3-31]]

^<<v7-3-31,31>>^ O líder seguinte foi Sangar, filho de Anate. Ele matou seiscentos filisteus com um ferrão de tocar bois. E assim ele também libertou o povo de Israel.

'''

xref:007-juizes/007-juizes-002.adoc#v7-2-0[&#60; Capítulo Anterior] | <<v7-3-0,Topo>> | xref:007-juizes/007-juizes-004.adoc#v7-4-0[Próximo Capítulo &#62;]