include::./index.adoc[]

[[v7-11-0]]
=== Juízes, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v7-11-1]]

^<<v7-11-1,1>>^ Jefté, da região de Gileade, era um soldado valente. O seu pai se chamava Gileade, e a sua mãe era uma prostituta.

[[v7-11-2]]

^<<v7-11-2,2>>^ A esposa de Gileade também teve filhos. Quando cresceram, eles expulsaram Jefté, dizendo: — Você não vai herdar nada do nosso pai porque é filho de outra mulher.

[[v7-11-3]]

^<<v7-11-3,3>>^ Jefté fugiu dos seus irmãos e foi morar na terra de Tobe. Lá alguns homens ordinários se juntaram a ele, e andavam juntos.

[[v7-11-4]]

^<<v7-11-4,4>>^ Algum tempo depois os amonitas foram guerrear contra o povo de Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ Quando isso aconteceu, os chefes de Gileade foram buscar Jefté na terra de Tobe

[[v7-11-6]]

^<<v7-11-6,6>>^ e disseram: — Venha com a gente e seja o nosso chefe na guerra contra os amonitas.

[[v7-11-7]]

^<<v7-11-7,7>>^ Jefté respondeu: — Eu sei que vocês me odeiam; e odeiam tanto, que me fizeram sair da casa do meu pai. Como é que vocês vêm me pedir ajuda, agora que estão em dificuldade?

[[v7-11-8]]

^<<v7-11-8,8>>^ — Nós viemos falar com você porque queremos que comande todo o povo de Gileade na luta contra os amonitas! — responderam eles.

[[v7-11-9]]

^<<v7-11-9,9>>^ Jefté disse: — Se me levarem de volta para casa a fim de lutar contra os amonitas, e se o Senhor  Deus me der a vitória, eu serei o governador de vocês. Está certo?

[[v7-11-10]]

^<<v7-11-10,10>>^ Eles responderam: — Sim. Nós faremos como você diz. O Senhor  é a nossa testemunha.

[[v7-11-11]]

^<<v7-11-11,11>>^ Aí Jefté foi com os chefes de Gileade, e o povo o colocou como governador e chefe. E em Mispa, na presença do Senhor , Jefté fez o povo jurar que faria tudo o que havia sido dito.

[[v7-11-12]]

^<<v7-11-12,12>>^ Então Jefté enviou mensageiros ao rei dos amonitas. Os mensageiros disseram: — O que é que vocês têm contra mim? Por que invadiram o meu país?

[[v7-11-13]]

^<<v7-11-13,13>>^ O rei dos amonitas respondeu: — Quando os israelitas saíram do Egito, tomaram a minha terra, desde o rio Arnom até os rios Jaboque e Jordão. Agora, sem luta, vocês devem devolver a minha terra.

[[v7-11-14]]

^<<v7-11-14,14>>^ Jefté mandou outros mensageiros ao rei dos amonitas

[[v7-11-15]]

^<<v7-11-15,15>>^ com a seguinte resposta: — O povo de Israel não tomou a terra de Moabe nem a terra de Amom.

[[v7-11-16]]

^<<v7-11-16,16>>^ Quando os israelitas saíram do Egito, foram pelo deserto até o golfo de Ácaba e daí até Cades.

[[v7-11-17]]

^<<v7-11-17,17>>^ Eles mandaram mensageiros ao rei dos edomitas, pedindo licença para passar pelas suas terras, mas ele não deixou. Então os israelitas pediram a mesma coisa ao rei de Moabe, porém ele também não deixou. Por isso os israelitas ficaram em Cades.

[[v7-11-18]]

^<<v7-11-18,18>>^ — Eles foram pelo deserto. Rodearam a terra dos edomitas e dos moabitas e chegaram até a parte leste de Moabe, no outro lado do rio Arnom. Acamparam ali, mas não atravessaram o rio porque estava na fronteira de Moabe.

[[v7-11-19]]

^<<v7-11-19,19>>^ Aí os israelitas mandaram mensageiros a Seom, o rei amorreu de Hesbom, e pediram licença para atravessar aquele país a fim de poderem chegar à sua terra.

[[v7-11-20]]

^<<v7-11-20,20>>^ Mas Seom não deixou. Levou todo o seu exército, acampou em Jasa e atacou o povo de Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ Mas o Senhor , o Deus de Israel, fez com que os israelitas derrotassem Seom e todos os seus homens. E assim os israelitas conquistaram toda a terra que era dos amorreus.

[[v7-11-22]]

^<<v7-11-22,22>>^ Tomaram toda a terra dos amorreus: desde o rio Arnom, ao Sul, até o rio Jaboque, ao Norte; e, desde o deserto, a Leste, até o rio Jordão, a Oeste.

[[v7-11-23]]

^<<v7-11-23,23>>^ Assim, foi o Senhor , o Deus de Israel, quem expulsou os amorreus para o seu povo, os israelitas.

[[v7-11-24]]

^<<v7-11-24,24>>^ E agora vocês querem tentar tomar a terra de volta? Podem ficar com tudo o que Quemos, o deus de vocês, lhes deu. — Mas nós vamos ficar com tudo o que o Senhor , nosso Deus, conquistou para nós.

[[v7-11-25]]

^<<v7-11-25,25>>^ Você pensa que é melhor do que Balaque, filho de Zipor, que era rei de Moabe? Será que alguma vez ele desafiou Israel? Quando foi que ele guerreou contra nós?

[[v7-11-26]]

^<<v7-11-26,26>>^ Durante trezentos anos o povo de Israel morou em Hesbom e Aroer. Morou também nas cidades vizinhas e em todas as outras cidades das margens do rio Arnom. Por que foi que vocês não tomaram essas cidades de volta durante todo esse tempo?

[[v7-11-27]]

^<<v7-11-27,27>>^ Não! Eu não fiz nada de errado contra vocês. Vocês é que fazem mal, querendo lutar contra mim. O Senhor  é o juiz. Ele decidirá hoje entre os israelitas e os amonitas.

[[v7-11-28]]

^<<v7-11-28,28>>^ Mas o rei dos amonitas não quis ouvir a mensagem que Jefté havia mandado.

[[v7-11-29]]

^<<v7-11-29,29>>^ Então o Espírito do Senhor  dominou Jefté, e ele atravessou Gileade e Manassés e voltou para Mispa, em Gileade. Dali foi para Amom

[[v7-11-30]]

^<<v7-11-30,30>>^ e prometeu ao Senhor  o seguinte: — Se fizeres com que eu vença os amonitas,

[[v7-11-31]]

^<<v7-11-31,31>>^ eu queimarei em sacrifício  aquele que sair primeiro da minha casa para me encontrar quando eu voltar da guerra. Eu o oferecerei em sacrifício a ti.

[[v7-11-32]]

^<<v7-11-32,32>>^ Então Jefté atravessou o rio para lutar contra os amonitas, e o Senhor  lhe deu a vitória.

[[v7-11-33]]

^<<v7-11-33,33>>^ Ele derrotou os amonitas desde Aroer até perto de Minite — vinte cidades ao todo — e continuou até Abel-Queramim. Houve uma grande matança, e os israelitas derrotaram os amonitas.

[[v7-11-34]]

^<<v7-11-34,34>>^ Quando Jefté voltou para a sua casa, em Mispa, a sua filha saiu ao seu encontro, dançando e tocando pandeiro. Era filha única; ele não tinha mais nenhuma filha ou filho.

[[v7-11-35]]

^<<v7-11-35,35>>^ Quando Jefté a viu, ficou desesperado, rasgou as suas roupas e disse: — Ah! Minha filha! Você está partindo o meu coração! Por que tem de ser você quem me vai fazer sofrer? Eu fiz uma promessa a Deus, o Senhor , e não posso voltar atrás.

[[v7-11-36]]

^<<v7-11-36,36>>^ Ela respondeu: — Se o senhor fez uma promessa ao Senhor  Deus, faça de mim o que prometeu. Pois o Senhor  Deus deixou que o senhor se vingasse dos nossos inimigos, os amonitas.

[[v7-11-37]]

^<<v7-11-37,37>>^ E continuou: — Só peço uma coisa: deixe que eu vá com as minhas amigas pelos montes e chore durante dois meses porque nunca chegarei a ser mãe.

[[v7-11-38]]

^<<v7-11-38,38>>^ E o pai deixou que ela fosse por dois meses. Então ela e as suas amigas saíram pelas montanhas, chorando porque ela nunca chegaria a ser mãe.

[[v7-11-39]]

^<<v7-11-39,39>>^ Depois dos dois meses, ela voltou para o pai. E ele fez o que havia prometido a Deus. Assim ela morreu virgem. Daí veio o costume de as mulheres israelitas

[[v7-11-40]]

^<<v7-11-40,40>>^ saírem durante quatro dias, todos os anos, para chorar pela filha de Jefté, o gileadita.

'''

xref:007-juizes/007-juizes-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-juizes/007-juizes-012.adoc#v7-12-0[Próximo Capítulo &#62;]