include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v29-3-1]]

^<<v29-3-1,1>>^ O Senhor  Deus diz: — Naquele tempo, farei com que o povo de Jerusalém e de Judá prospere de novo.

[[v29-3-2]]

^<<v29-3-2,2>>^ Então ajuntarei os povos de todos os países e os levarei para o vale de Josafá e ali os julgarei. Eu farei isso por causa das maldades que praticaram contra o povo de Israel, o meu povo escolhido: espalharam os israelitas por vários países e dividiram entre si o meu país.

[[v29-3-3]]

^<<v29-3-3,3>>^ Tiraram a sorte para ver quem ficava com os prisioneiros do meu povo; venderam meninos e meninas como escravos e gastaram o dinheiro com prostitutas e com vinho.

[[v29-3-4]]

^<<v29-3-4,4>>^ — Povos de Tiro e de Sidom e de toda a Filisteia, o que é que vocês querem de mim? Estão querendo se vingar? Se é isso que querem, então eu também estou pronto para me vingar de vocês!

[[v29-3-5]]

^<<v29-3-5,5>>^ Pois vocês roubaram a minha prata e o meu ouro e puseram toda essa riqueza nos seus templos.

[[v29-3-6]]

^<<v29-3-6,6>>^ Vocês levaram o povo de Judá e os moradores de Jerusalém para longe das suas terras e os venderam como escravos aos gregos .

[[v29-3-7]]

^<<v29-3-7,7>>^ Eu vou trazer o meu povo de volta daqueles lugares distantes e farei com vocês o mesmo que vocês fizeram com eles.

[[v29-3-8]]

^<<v29-3-8,8>>^ Farei com que os filhos e as filhas de vocês sejam vendidos como escravos ao povo de Judá, que os venderá aos sabeus, povo de um país que fica muito longe daqui. Sou eu, o Senhor , quem está falando.

[[v29-3-9]]

^<<v29-3-9,9>>^ — Anunciem isto às nações: "Preparem-se para uma guerra santa , chamem os soldados; que todos eles se apresentem e se aprontem para a batalha.

[[v29-3-10]]

^<<v29-3-10,10>>^ Transformem os seus arados em espadas e das suas foices façam lanças. Que até os fracos digam que são valentes!

[[v29-3-11]]

^<<v29-3-11,11>>^ Venham depressa, todas as nações vizinhas, e reúnam-se no vale. Que até os pacíficos virem soldados!

[[v29-3-12]]

^<<v29-3-12,12>>^ "Preparem-se, povos de todas as nações, e venham para o vale de Josafá , pois ali eu, o Senhor , vou julgar todas as nações vizinhas.

[[v29-3-13]]

^<<v29-3-13,13>>^ Os pecados dessas nações são tantos, que elas vão ser cortadas como o trigo maduro no tempo da colheita; elas vão ser pisadas como as uvas são pisadas nos tanques até o vinho derramar."

[[v29-3-14]]

^<<v29-3-14,14>>^ Multidões e mais multidões enchem o vale da Decisão; está perto o Dia do Senhor , no vale da Decisão.

[[v29-3-15]]

^<<v29-3-15,15>>^ O sol e a lua ficam escuros, e as estrelas deixam de brilhar.

[[v29-3-16]]

^<<v29-3-16,16>>^ Do monte Sião , o Senhor  fala alto, a sua voz parece o trovão. De Jerusalém, ouve-se o estrondo da voz de Deus, e os céus e a terra tremem! Mas ele defende e protege o povo de Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ Deus diz ao seu povo: "Assim vocês vão ficar sabendo que eu sou o Senhor , o Deus de vocês. Eu moro em Sião, o meu monte santo. Jerusalém será uma cidade santa, e os estrangeiros nunca mais a conquistarão.

[[v29-3-18]]

^<<v29-3-18,18>>^ "Naquele tempo, os morros estarão cobertos de parreiras , haverá vacas pastando por todos os montes, e muita água vai correr nos ribeirões da terra de Judá. Do meu Templo, sairá um rio que regará o vale das Acácias.

[[v29-3-19]]

^<<v29-3-19,19>>^ O Egito ficará abandonado, e Edom parecerá um deserto, pois eles invadiram a terra de Judá e mataram pessoas inocentes.

[[v29-3-20]]

^<<v29-3-20,20>>^ Eu vingarei a morte dessas pessoas e castigarei os culpados. Mas sempre haverá gente vivendo em Judá e em Jerusalém, e eu, o Senhor , morarei no monte Sião."

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]