include::./index.adoc[]

[[v29-1-0]]
=== Joel, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v29-1-1]]

^<<v29-1-1,1>>^ Esta é a mensagem que o Senhor  Deus deu a Joel, filho de Petuel.

[[v29-1-2]]

^<<v29-1-2,2>>^ Prestem atenção, velhos! Escute, povo de Judá! Já aconteceu alguma coisa tão terrível como esta, em nossos dias ou no tempo dos nossos antepassados?

[[v29-1-3]]

^<<v29-1-3,3>>^ Digam aos seus filhos o que aconteceu; que eles contem aos seus filhos, e que estes falem sobre isso à geração  seguinte.

[[v29-1-4]]

^<<v29-1-4,4>>^ Vieram nuvens e mais nuvens de gafanhotos, e comeram todas as plantações. O que os primeiros gafanhotos deixaram foi devorado pelos que vieram depois.

[[v29-1-5]]

^<<v29-1-5,5>>^ Acordem, beberrões! Acordem e chorem, vocês que gostam de vinho, pois as uvas foram destruídas, e não haverá vinho novo para beber.

[[v29-1-6]]

^<<v29-1-6,6>>^ Vieram os gafanhotos, como um exército enorme e poderoso, e invadiram o meu país. Os seus dentes eram como os de um leão e afiados como dentes de uma leoa.

[[v29-1-7]]

^<<v29-1-7,7>>^ Destruíram as nossas parreiras e acabaram com as nossas figueiras. Arrancaram as cascas das árvores, deixando os galhos completamente brancos.

[[v29-1-8]]

^<<v29-1-8,8>>^ Chorem como uma jovem vestida de luto, que chora a morte do seu noivo.

[[v29-1-9]]

^<<v29-1-9,9>>^ Os sacerdotes, os servos  de Deus, choram no Templo do Senhor porque não há mais ofertas de alimento nem de vinho.

[[v29-1-10]]

^<<v29-1-10,10>>^ Os campos estão arrasados, a terra está de luto, pois os cereais foram destruídos, e as parreiras e as oliveiras secaram.

[[v29-1-11]]

^<<v29-1-11,11>>^ Fiquem desesperados, vocês que trabalham nos campos; chorem, vocês que cuidam das parreiras; pois não há trigo nem cevada . Todas as colheitas foram destruídas.

[[v29-1-12]]

^<<v29-1-12,12>>^ As parreiras e as figueiras secaram; estão secas as romãzeiras, as palmeiras, as macieiras e todas as outras árvores frutíferas. O povo todo está triste.

[[v29-1-13]]

^<<v29-1-13,13>>^ Sacerdotes, vocês que apresentam as ofertas no altar, vistam roupa feita de pano grosseiro e chorem. Servos do meu Deus, venham ao pátio do Templo e chorem a noite inteira. Pois na casa do nosso Deus não há mais ofertas de alimento nem de vinho.

[[v29-1-14]]

^<<v29-1-14,14>>^ Convoquem uma reunião no Templo e anunciem um dia de jejum. Reúnam as autoridades e todo o povo de Judá no Templo do Senhor , nosso Deus, e orem a ele pedindo socorro.

[[v29-1-15]]

^<<v29-1-15,15>>^ Ah! Está chegando o Dia do Senhor , em que o Todo-Poderoso vai trazer destruição. Será um dia de terror!

[[v29-1-16]]

^<<v29-1-16,16>>^ Sem podermos fazer nada, vimos as nossas plantações serem destruídas. No Templo do nosso Deus não há alegria nem festa.

[[v29-1-17]]

^<<v29-1-17,17>>^ Nos campos secos, as sementes não brotam; não há colheita de trigo, e os depósitos de cereais estão caindo aos pedaços.

[[v29-1-18]]

^<<v29-1-18,18>>^ O gado está mugindo de fome, e os bois andam tontos de um lado para o outro porque não há pasto. As ovelhas também estão morrendo.

[[v29-1-19]]

^<<v29-1-19,19>>^ Eu clamo a ti, ó Senhor ! As árvores e os pastos estão secos, como se um fogo tivesse queimado tudo.

[[v29-1-20]]

^<<v29-1-20,20>>^ Até os animais selvagens pedem socorro a ti porque os rios secaram, e por toda parte a seca acabou com o capim.

'''

xref:028-oseias/028-oseias-014.adoc#v28-14-0[&#60; Capítulo Anterior] | <<v29-1-0,Topo>> | xref:029-joel/029-joel-002.adoc#v29-2-0[Próximo Capítulo &#62;]