include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v29-2-1]]

^<<v29-2-1,1>>^ Toquem as cornetas no monte Sião , deem um grito de alarme no monte de Deus! Trema de medo, povo de Judá, pois está chegando o Dia do Senhor .

[[v29-2-2]]

^<<v29-2-2,2>>^ Será um dia de escuridão e trevas, um dia de nuvens negras. Os gafanhotos avançam como um exército enorme e poderoso, como uma nuvem escura que cobre as montanhas. Nunca houve uma coisa assim no passado e no futuro nunca mais haverá.

[[v29-2-3]]

^<<v29-2-3,3>>^ Eles devoram tudo, como se fossem fogo, como o fogo que queima e destrói. Antes de chegarem, a terra é como um paraíso; mas, depois de passarem, ela parece um deserto. Os gafanhotos acabam com tudo!

[[v29-2-4]]

^<<v29-2-4,4>>^ Eles parecem cavalos e correm como cavalos de guerra.

[[v29-2-5]]

^<<v29-2-5,5>>^ Vêm saltando no alto das montanhas, fazendo barulho como carros de guerra, como galhos secos estalando no fogo. São como um enorme exército posto em ordem de combate.

[[v29-2-6]]

^<<v29-2-6,6>>^ Eles vão avançando, e todo mundo treme, todos ficam pálidos de medo.

[[v29-2-7]]

^<<v29-2-7,7>>^ Eles atacam como soldados valentes; correm, sobem pelos muros e continuam sempre avançando. Marcham em linha reta

[[v29-2-8]]

^<<v29-2-8,8>>^ e não empurram uns aos outros, pois cada um segue o seu caminho. Marcham sempre em frente, e não há armas que possam fazê-los parar.

[[v29-2-9]]

^<<v29-2-9,9>>^ Eles atacam a cidade, sobem pelas paredes das casas e entram pelas janelas como ladrões.

[[v29-2-10]]

^<<v29-2-10,10>>^ Avançam sem parar, e a terra treme, o céu estremece, o sol e a lua se escurecem, e as estrelas deixam de brilhar.

[[v29-2-11]]

^<<v29-2-11,11>>^ À frente do seu exército, o Senhor  dá ordens em alta voz. O exército é enorme, e os soldados são valentes! Como é terrível o Dia do Senhor ! Quem poderá suportá-lo?

[[v29-2-12]]

^<<v29-2-12,12>>^ O Senhor  Deus diz: "Mas agora voltem para mim com todo o coração, jejuando, chorando e se lamentando.

[[v29-2-13]]

^<<v29-2-13,13>>^ Em sinal de arrependimento, não rasguem as roupas, mas sim o coração." Voltem para o Senhor , nosso Deus, pois ele é bondoso e misericordioso; é paciente e muito amoroso e está sempre pronto a mudar de ideia e não castigar.

[[v29-2-14]]

^<<v29-2-14,14>>^ Talvez o Senhor , nosso Deus, mude de ideia e abençoe o seu povo, dando-lhe boas colheitas. Então vocês poderão apresentar a Deus ofertas de alimento e de vinho.

[[v29-2-15]]

^<<v29-2-15,15>>^ Toquem as trombetas no monte Sião ! Anunciem um dia santo de jejum e convoquem o povo para se reunir no Templo!

[[v29-2-16]]

^<<v29-2-16,16>>^ Reúnam todo o povo e mandem que eles se purifiquem . Que venham todos, velhos e crianças e até as criancinhas de peito! Que os recém-casados saiam de casa e venham ao Templo também!

[[v29-2-17]]

^<<v29-2-17,17>>^ E vocês, sacerdotes, que no pátio do Templo servem a Deus, o Senhor , chorem e façam esta oração: "Ó Deus, não castigues o teu povo! Não nos humilhes diante dos outros povos para que eles não caçoem de nós e perguntem: ‘Onde está o Deus de vocês?’ "

[[v29-2-18]]

^<<v29-2-18,18>>^ Então o Senhor  mostrou o seu grande amor para com a sua terra e teve pena do seu povo.

[[v29-2-19]]

^<<v29-2-19,19>>^ E respondeu: "Agora, vou lhes dar cereais, vinho e azeite; assim vocês comerão e ficarão satisfeitos. Nunca mais deixarei que os outros povos caçoem de vocês.

[[v29-2-20]]

^<<v29-2-20,20>>^ Enxotarei para longe de vocês a praga de gafanhotos que vem do Norte e os jogarei no deserto. Os gafanhotos que vêm na frente serão jogados no mar Morto, e os que vêm atrás cairão no mar Mediterrâneo. Os gafanhotos mortos, aos montões, vão apodrecer e cheirar mal. Eu vou fazer grandes coisas!

[[v29-2-21]]

^<<v29-2-21,21>>^ "Alegrem-se, ó campos, e não tenham medo, pois eu, o Senhor , fiz grandes coisas!

[[v29-2-22]]

^<<v29-2-22,22>>^ Animais selvagens, não fiquem com medo, pois o capim vai ficar verde, as árvores darão frutas, e haverá muito figo e muita uva.

[[v29-2-23]]

^<<v29-2-23,23>>^ "Alegrem-se, moradores de Jerusalém, pois eu, o Senhor , o Deus de vocês, fiz grandes coisas. Eu lhes dei chuvas no tempo certo, as do outono e as da primavera, muita chuva, como no passado.

[[v29-2-24]]

^<<v29-2-24,24>>^ A colheita de trigo será boa, e haverá muito vinho e muito azeite.

[[v29-2-25]]

^<<v29-2-25,25>>^ Devolverei tudo o que vocês perderam quando eu mandei as enormes nuvens de gafanhotos, que, como exércitos, destruíram as colheitas.

[[v29-2-26]]

^<<v29-2-26,26>>^ Vocês terão comida até não querer mais e louvarão o Senhor , seu Deus, que derramou tantas bênçãos sobre vocês. E o meu povo nunca mais será humilhado.

[[v29-2-27]]

^<<v29-2-27,27>>^ Vocês ficarão sabendo que eu estou com vocês; saberão que eu, o Senhor , sou o seu Deus e que não há nenhum outro Deus. E o meu povo nunca mais será humilhado."

[[v29-2-28]]

^<<v29-2-28,28>>^ O Senhor  diz ao seu povo: "Depois disso, eu derramarei o meu Espírito sobre todas as pessoas: os filhos e as filhas de vocês anunciarão a minha mensagem; os velhos sonharão, e os moços terão visões.

[[v29-2-29]]

^<<v29-2-29,29>>^ Até sobre os escravos e as escravas eu derramarei o meu Espírito naqueles dias.

[[v29-2-30]]

^<<v29-2-30,30>>^ Farei com que apareçam coisas espantosas no céu e na terra: haverá sangue, e fogo, e nuvens de fumaça.

[[v29-2-31]]

^<<v29-2-31,31>>^ O sol ficará escuro, e a lua se tornará cor de sangue, antes que chegue o grande e terrível Dia do Senhor ."

[[v29-2-32]]

^<<v29-2-32,32>>^ Então todo aquele que pedir a ajuda do Senhor  será salvo. Pois o Senhor  prometeu que todos os que não tiverem sido destruídos estarão no monte Sião, em Jerusalém. Aqueles que o Senhor  escolheu serão salvos.

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]