include::./index.adoc[]

[[v23-42-0]]
=== Isaías, 42
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-42-1]]

^<<v23-42-1,1>>^ O Senhor  Deus diz: "Aqui está o meu servo , a quem eu fortaleço, o meu escolhido, que dá muita alegria ao meu coração. Pus nele o meu Espírito, e ele anunciará a minha vontade a todos os povos.

[[v23-42-2]]

^<<v23-42-2,2>>^ Não gritará, não clamará, não fará discursos nas ruas.

[[v23-42-3]]

^<<v23-42-3,3>>^ Não esmagará um galho que está quebrado, nem apagará a luz que já está fraca. Com toda a dedicação, ele anunciará a minha vontade.

[[v23-42-4]]

^<<v23-42-4,4>>^ Não se cansará, nem desanimará, mas continuará firme até que todos aceitem a minha vontade. As nações distantes estão esperando para receber os seus ensinamentos."

[[v23-42-5]]

^<<v23-42-5,5>>^ O Senhor  Deus criou os céus e os estendeu; formou a terra e tudo o que nela existe e deu vida e fôlego a todos os seus moradores. E agora o Senhor  diz ao seu servo:

[[v23-42-6]]

^<<v23-42-6,6>>^ "Eu, o Senhor , o chamei e o peguei pela mão, para que haja salvação por meio de você. Eu o criei e o enviei como garantia da aliança  que vou fazer com o meu povo, como a luz da salvação que darei aos outros povos;

[[v23-42-7]]

^<<v23-42-7,7>>^ para abrir os olhos dos cegos, pôr em liberdade os prisioneiros e soltar os que estão em prisões escuras.

[[v23-42-8]]

^<<v23-42-8,8>>^ Eu sou o Senhor : este é o meu nome, e não permito que as imagens recebam o louvor que somente eu mereço."

[[v23-42-9]]

^<<v23-42-9,9>>^ Deus diz ao seu povo: "As coisas que prometi no passado já se cumpriram, e agora vou lhes anunciar coisas novas, para que vocês as saibam antes mesmo que elas aconteçam."

[[v23-42-10]]

^<<v23-42-10,10>>^ Cantem ao Senhor  uma nova canção! Que ele seja louvado no mundo inteiro: pelos que navegam nos mares, pelas criaturas que vivem nas águas do mar e pelos povos de todas as nações distantes!

[[v23-42-11]]

^<<v23-42-11,11>>^ Que no deserto e nas suas cidades Deus seja louvado, e que os moradores de Quedar o louvem! Moradores de Selá, alegrem-se e cantem no alto das montanhas!

[[v23-42-12]]

^<<v23-42-12,12>>^ Que o Senhor  Deus seja louvado, e que a sua glória  seja anunciada no mundo inteiro!

[[v23-42-13]]

^<<v23-42-13,13>>^ O Senhor  se prepara para a guerra e sai pronto para lutar, como um soldado valente. Com toda a força, ele solta o grito de batalha e com o seu poder derrota os seus inimigos.

[[v23-42-14]]

^<<v23-42-14,14>>^ O Senhor  diz: "Por muito tempo, eu não disse nada, fiquei calado e não respondi; mas agora vou gritar como uma mulher em dores de parto, vou me lamentar e clamar.

[[v23-42-15]]

^<<v23-42-15,15>>^ Vou destruir os morros e as montanhas e fazer secar todas as plantas e árvores. Farei com que os rios virem desertos e com que todos os poços fiquem secos.

[[v23-42-16]]

^<<v23-42-16,16>>^ Guiarei os cegos por um caminho que não conhecem, por uma estrada que eles nunca pisaram antes. A escuridão que os cerca eu farei virar luz e aplanarei os caminhos ásperos. São estas as minhas promessas, e eu as cumprirei sem falta.

[[v23-42-17]]

^<<v23-42-17,17>>^ Mas serão derrotados e humilhados todos os que confiam em ídolos, todos os que dizem às imagens: ‘Vocês são os nossos deuses.’ "

[[v23-42-18]]

^<<v23-42-18,18>>^ O Senhor  diz: "Escute, gente surda! Olhe bem, gente cega!

[[v23-42-19]]

^<<v23-42-19,19>>^ Ninguém é tão cego como o povo de Israel, o meu servo , ou tão surdo como esse povo que estou enviando. Não há quem seja tão cego como o meu mensageiro, nem tão surdo como o servo do Senhor .

[[v23-42-20]]

^<<v23-42-20,20>>^ Povo de Israel, você tem visto muitas coisas, mas não entendeu nenhuma delas; você tem ouvido muitas coisas, mas não aprendeu nada."

[[v23-42-21]]

^<<v23-42-21,21>>^ O Senhor  é o Deus que salva o seu povo e por isso quis que eles conhecessem e respeitassem a sua lei .

[[v23-42-22]]

^<<v23-42-22,22>>^ Mas eles foram assaltados e roubados; foram postos na prisão e trancados nas celas. Os seus inimigos os levaram como prisioneiros, e não há ninguém que os ponha em liberdade.

[[v23-42-23]]

^<<v23-42-23,23>>^ Ah! Se um de vocês desse atenção ao que estou dizendo, se daqui em diante alguém escutasse com cuidado!

[[v23-42-24]]

^<<v23-42-24,24>>^ Quem foi que entregou o povo de Israel aos seus inimigos? Quem foi que deixou que ele fosse roubado? Foi o próprio Senhor , contra quem temos pecado! Não quisemos seguir os seus caminhos, nem obedecer às suas leis.

[[v23-42-25]]

^<<v23-42-25,25>>^ Por isso, ele derramou sobre nós a sua ira e nos castigou com uma guerra violenta. A sua ira queimou como fogo em volta de nós, mas mesmo assim ninguém se importou; nenhum de nós conseguiu aprender nada.

'''

xref:023-isaias/023-isaias-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaias/023-isaias-043.adoc#v23-43-0[Próximo Capítulo &#62;]