include::./index.adoc[]

[[v23-11-0]]
=== Isaías, 11
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-11-1]]

^<<v23-11-1,1>>^ Virá um descendente do rei Davi, filho de Jessé, que será como um ramo que brota de um toco, como um broto que surge das raízes.

[[v23-11-2]]

^<<v23-11-2,2>>^ O Espírito do Senhor  estará sobre ele e lhe dará sabedoria e conhecimento, capacidade e poder. Ele temerá  o Senhor , conhecerá a sua vontade

[[v23-11-3]]

^<<v23-11-3,3>>^ e terá prazer em obedecer-lhe. Ele não julgará pela aparência, nem decidirá somente por ouvir dizer.

[[v23-11-4]]

^<<v23-11-4,4>>^ Mas com justiça julgará os necessitados e defenderá os direitos dos pobres. As suas palavras serão como uma vara para castigar o país, e com o seu sopro ele matará os maus.

[[v23-11-5]]

^<<v23-11-5,5>>^ Com justiça e com honestidade, ele governará o seu povo.

[[v23-11-6]]

^<<v23-11-6,6>>^ Lobos e ovelhas viverão em paz, leopardos e cabritinhos descansarão juntos. Bezerros e leões comerão uns com os outros, e crianças pequenas os guiarão.

[[v23-11-7]]

^<<v23-11-7,7>>^ Vacas e ursas pastarão juntas, e os seus filhotes descansarão no mesmo lugar; os leões comerão capim como os bois.

[[v23-11-8]]

^<<v23-11-8,8>>^ Criancinhas brincarão perto de cobras e não serão picadas, mesmo que enfiem a mão nas suas covas.

[[v23-11-9]]

^<<v23-11-9,9>>^ Em Sião , o monte sagrado, não acontecerá nada de mau ou perigoso, pois a terra ficará cheia do conhecimento da glória  do Senhor assim como as águas enchem o mar.

[[v23-11-10]]

^<<v23-11-10,10>>^ Naquele dia, o descendente de Davi, filho de Jessé, será como uma bandeira para as nações. Os povos passarão para o lado dele, e da cidade onde ele reina brilhará a glória  de Deus.

[[v23-11-11]]

^<<v23-11-11,11>>^ Naquele dia, o Senhor, com a sua mão poderosa, trará de volta para a sua terra as pessoas do seu povo que ainda estiverem na Assíria, no Egito, em Patros, na Etiópia, em Elão, na Babilônia, em Hamate, no litoral do mar Mediterrâneo e nas ilhas.

[[v23-11-12]]

^<<v23-11-12,12>>^ Deus levantará uma bandeira como um sinal para ajuntar os povos de Israel e de Judá que estiverem espalhados pelos quatro cantos do mundo; ele os trará de volta para a sua terra.

[[v23-11-13]]

^<<v23-11-13,13>>^ O povo de Israel não terá mais ciúmes do povo de Judá, e o povo de Judá não será mais inimigo do povo de Israel.

[[v23-11-14]]

^<<v23-11-14,14>>^ Os dois povos atacarão juntos a Filisteia, que fica a oeste; eles conquistarão os povos que moram no Leste e ficarão com as suas riquezas. Derrotarão os edomitas, os moabitas e os amonitas.

[[v23-11-15]]

^<<v23-11-15,15>>^ O Senhor  Deus secará o golfo de Suez e enviará um forte vento contra o rio Eufrates. Deixará que sobrem somente sete ribeirões que qualquer um poderá atravessar a pé.

[[v23-11-16]]

^<<v23-11-16,16>>^ Assim como houve uma estrada para os israelitas que saíram do Egito, também haverá uma estrada boa saindo da Assíria, e por ela passarão as pessoas do meu povo que estiverem vivas.

'''

xref:023-isaias/023-isaias-010.adoc#v23-10-0[&#60; Capítulo Anterior] | <<v23-11-0,Topo>> | xref:023-isaias/023-isaias-012.adoc#v23-12-0[Próximo Capítulo &#62;]