include::./index.adoc[]

[[v23-59-0]]
=== Isaías, 59
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-59-1]]

^<<v23-59-1,1>>^ Vocês estão pensando que o Senhor  perdeu a força e não pode nos salvar? Ou pensam que ele está surdo e não pode nos ouvir?

[[v23-59-2]]

^<<v23-59-2,2>>^ Pois são os pecados de vocês que os separam do seu Deus, são as suas maldades que fazem com que ele se esconda de vocês e não atenda as suas orações.

[[v23-59-3]]

^<<v23-59-3,3>>^ Vocês têm as mãos manchadas de sangue e os dedos sujos de crimes; vocês só sabem contar mentiras, e os seus lábios estão sempre dizendo coisas que não prestam.

[[v23-59-4]]

^<<v23-59-4,4>>^ Não é para procurar a justiça que vão ao tribunal, e ninguém diz a verdade ao juiz. Todos confiam em mentiras e falsidades; inventam maldades e praticam crimes.

[[v23-59-5]]

^<<v23-59-5,5>>^ Os seus planos perversos são como os ovos de uma cobra venenosa: quem come os ovos morre, e, se um se quebra, dele sai outra cobra venenosa. Os seus planos não prestam para nada; parecem teias de aranha;

[[v23-59-6]]

^<<v23-59-6,6>>^ elas não servem para fazer roupa, e ninguém pode se vestir com elas. Tudo o que vocês fazem é mau, todas as suas ações são criminosas.

[[v23-59-7]]

^<<v23-59-7,7>>^ Vocês correm para fazer o que é errado e se apressam para matar pessoas inocentes; vocês pensam somente em maltratar os outros e, por onde passam, deixam a destruição e a desgraça.

[[v23-59-8]]

^<<v23-59-8,8>>^ Não conhecem o caminho da paz, e todas as suas ações são injustas. Vocês preferem seguir caminhos errados e por isso não têm segurança.

[[v23-59-9]]

^<<v23-59-9,9>>^ Deus ainda não nos salvou, pois temos pecado, e por isso ele demora em nos socorrer. Procuramos a luz, mas só encontramos a escuridão; buscamos lugares claros, mas continuamos nas trevas.

[[v23-59-10]]

^<<v23-59-10,10>>^ Andamos apalpando as paredes como se fôssemos cegos, como se não tivéssemos olhos; ao meio-dia tropeçamos como se fosse de noite e, em plena flor da idade, parecemos mortos.

[[v23-59-11]]

^<<v23-59-11,11>>^ Rugimos como ursos assustados, gememos como pombas; esperamos a salvação, porém ela demora; desejamos socorro, mas ele está longe de nós.

[[v23-59-12]]

^<<v23-59-12,12>>^ Temos pecado muito contra ti, ó Deus, e os nossos pecados nos acusam. Não podemos esquecer as nossas maldades; reconhecemos que somos culpados.

[[v23-59-13]]

^<<v23-59-13,13>>^ Não temos sido fiéis, temos nos revoltado contra ti e nos afastado de ti, o nosso Deus. Temos falado de crimes e de revoltas e temos feito planos para enganar os outros.

[[v23-59-14]]

^<<v23-59-14,14>>^ A justiça é posta de lado, e o direito é afastado. A verdade anda tropeçando no tribunal, e a honestidade não consegue chegar até lá.

[[v23-59-15]]

^<<v23-59-15,15>>^ A verdade desapareceu, e os que procuram ser honestos são perseguidos. O Senhor  se desgostou ao ver que não havia justiça.

[[v23-59-16]]

^<<v23-59-16,16>>^ Ele ficou espantado quando viu que não havia ninguém que socorresse o seu povo. Então com a sua própria força ele venceu e, por ser o Deus justo, conseguiu a vitória.

[[v23-59-17]]

^<<v23-59-17,17>>^ O Senhor  vestiu a couraça  da justiça e pôs na cabeça o capacete da salvação; a vingança lhe serviu de roupa, a sua ira  foi a capa  que usou.

[[v23-59-18]]

^<<v23-59-18,18>>^ Ele dará a cada um o castigo que merece. Na sua ira, castigará os seus inimigos, e povos de países distantes receberão o que merecem.

[[v23-59-19]]

^<<v23-59-19,19>>^ Todos, desde o Leste até o Oeste, temerão  o Senhor  e o seu poder. Pois ele virá como uma forte correnteza que é levada por um vento furioso.

[[v23-59-20]]

^<<v23-59-20,20>>^ O Senhor  Deus diz: "Eu virei a Sião  como Redentor para salvar as pessoas do meu povo que se arrependerem."

[[v23-59-21]]

^<<v23-59-21,21>>^ O Senhor  diz ao seu povo: — Esta é a aliança  que vou fazer com vocês: o meu Espírito, que eu lhes dei, e os meus ensinamentos, que eu lhes entreguei, ficarão com vocês para sempre. Vocês os ensinarão aos seus filhos e aos seus descendentes, agora e para sempre. Eu, o Senhor , falei.

'''

xref:023-isaias/023-isaias-058.adoc#v23-58-0[&#60; Capítulo Anterior] | <<v23-59-0,Topo>> | xref:023-isaias/023-isaias-060.adoc#v23-60-0[Próximo Capítulo &#62;]