include::./index.adoc[]

[[v23-25-0]]
=== Isaías, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-25-1]]

^<<v23-25-1,1>>^ Ó Senhor , tu és o meu Deus. Eu te adorarei e louvarei o teu nome, pois tens feito coisas maravilhosas; tens cumprido fielmente os planos seguros que há muito tempo decidiste fazer.

[[v23-25-2]]

^<<v23-25-2,2>>^ Deixaste as cidades dos nossos inimigos em ruínas, as cidades cercadas de muralhas foram arrasadas. Destruíste os seus palácios, e nunca mais eles serão reconstruídos.

[[v23-25-3]]

^<<v23-25-3,3>>^ Por isso, povos poderosos te louvarão, e tu serás temido  nas cidades onde mora gente cruel.

[[v23-25-4]]

^<<v23-25-4,4>>^ Pois tens sido o protetor dos pobres, o defensor dos necessitados, um abrigo na tempestade e uma sombra no calor. A fúria de homens violentos é como uma tempestade de inverno,

[[v23-25-5]]

^<<v23-25-5,5>>^ como o calor do deserto. Mas tu tapas a boca dos estrangeiros. Como uma nuvem diminui o calor num dia quente, assim tu calaste os gritos de vitória de homens violentos.

[[v23-25-6]]

^<<v23-25-6,6>>^ No monte Sião , o Senhor  Todo-Poderoso vai dar um banquete para todos os povos do mundo; nele haverá as melhores comidas e os vinhos mais finos.

[[v23-25-7]]

^<<v23-25-7,7>>^ E ali ele acabará com a nuvem de tristeza e de choro que cobre todas as nações.

[[v23-25-8]]

^<<v23-25-8,8>>^ O Senhor  Deus acabará para sempre com a morte. Ele enxugará as lágrimas dos olhos de todos e fará desaparecer do mundo inteiro a vergonha que o seu povo está passando. O Senhor  falou.

[[v23-25-9]]

^<<v23-25-9,9>>^ Naquele dia, todos dirão: — Ele é o nosso Deus. Nós pusemos a nossa esperança nele, e ele nos salvou. Ele é o Senhor , e nós confiamos nele. Vamos cantar e nos alegrar porque ele nos socorreu.

[[v23-25-10]]

^<<v23-25-10,10>>^ O Senhor  Deus protegerá o monte Sião , mas o país de Moabe será pisado como se pisa a palha de um depósito de esterco.

[[v23-25-11]]

^<<v23-25-11,11>>^ Os moabitas estenderão os braços como quem está tentando nadar; mas, apesar de todo o seu esforço, os moabitas orgulhosos serão humilhados por Deus.

[[v23-25-12]]

^<<v23-25-12,12>>^ Ele derrubará as altas e fortes muralhas de Moabe e as deixará completamente arrasadas.

'''

xref:023-isaias/023-isaias-024.adoc#v23-24-0[&#60; Capítulo Anterior] | <<v23-25-0,Topo>> | xref:023-isaias/023-isaias-026.adoc#v23-26-0[Próximo Capítulo &#62;]