include::./index.adoc[]

[[v23-47-0]]
=== Isaías, 47
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-47-1]]

^<<v23-47-1,1>>^ O Senhor  diz: "Babilônia, desça do seu trono e sente-se no pó. Você era como uma virgem, bela, delicada e mimada; mas nunca mais será assim.

[[v23-47-2]]

^<<v23-47-2,2>>^ Agora, você é uma escrava: pegue o moinho e comece a moer a farinha. Tire o véu, levante a saia e, de pernas de fora, atravesse os rios .

[[v23-47-3]]

^<<v23-47-3,3>>^ Todos a verão sem roupa, completamente nua . Eu vou me vingar de você, e ninguém poderá me impedir."

[[v23-47-4]]

^<<v23-47-4,4>>^ O nosso Salvador é o Senhor  Todo-Poderoso, o Santo Deus de Israel.

[[v23-47-5]]

^<<v23-47-5,5>>^ Ele diz à Babilônia: "Sente-se e fique calada; vá para um lugar escuro, pois nunca mais você será chamada de ‘Rainha das Nações’.

[[v23-47-6]]

^<<v23-47-6,6>>^ Eu estava irado  com o meu povo, o meu povo escolhido; por isso, o humilhei e o entreguei nas suas mãos. Mas você não foi bondosa com ele; pelo contrário, tratou até mesmo os velhos com crueldade.

[[v23-47-7]]

^<<v23-47-7,7>>^ Você imaginou que seria rainha para sempre e não levou a sério o que estava acontecendo, nem pensou como tudo ia acabar.

[[v23-47-8]]

^<<v23-47-8,8>>^ Você ama a imoralidade e pensa que não corre nenhum perigo. Você diz assim: ‘Não há ninguém tão importante como eu; não há ninguém igual a mim. Nunca ficarei viúva, nem perderei nenhum dos meus filhos.’ "Mas agora escute o que eu lhe digo:

[[v23-47-9]]

^<<v23-47-9,9>>^ Eu sei que você sabe fazer despachos e que as suas feitiçarias são poderosas; mas tudo isso não adiantará nada. De repente, no mesmo dia, você vai ficar viúva e vai perder os filhos.

[[v23-47-10]]

^<<v23-47-10,10>>^ Você se sentia segura na sua maldade e imaginava que ninguém via o que você estava fazendo. Foram a sua sabedoria e o seu conhecimento que a enganaram. Você pensava assim: ‘Não há ninguém tão importante como eu.’

[[v23-47-11]]

^<<v23-47-11,11>>^ Por isso, cairá a desgraça sobre você, e as suas feitiçarias não valerão nada. A sua destruição está chegando, e não haverá jeito de escapar dela. Será uma desgraça como você não imaginava e virá quando você menos estiver esperando.

[[v23-47-12]]

^<<v23-47-12,12>>^ Fique com os despachos e as feitiçarias que você tem praticado desde que era jovem. É possível que eles a ajudem e que com eles você assuste os seus inimigos.

[[v23-47-13]]

^<<v23-47-13,13>>^ Apesar de todos os conselheiros que tem, você não poderá escapar. Que os seus astrólogos se apresentem e a ajudem! Eles estudam o céu e ficam olhando para as estrelas a fim de dizer, todos os meses, o que vai acontecer com você.

[[v23-47-14]]

^<<v23-47-14,14>>^ Pois eles são como palha; o fogo os destruirá, e eles não poderão se salvar. Pois este não é um foguinho daqueles que a gente faz para se esquentar, sentando-se bem perto dele.

[[v23-47-15]]

^<<v23-47-15,15>>^ É isso o que acontecerá com os seus adivinhos, com os quais você tem lidado toda a sua vida. Todos eles irão embora, cada um seguindo o seu próprio caminho; nenhum deles poderá salvar você."

'''

xref:023-isaias/023-isaias-046.adoc#v23-46-0[&#60; Capítulo Anterior] | <<v23-47-0,Topo>> | xref:023-isaias/023-isaias-048.adoc#v23-48-0[Próximo Capítulo &#62;]