include::./index.adoc[]

[[v23-24-0]]
=== Isaías, 24
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-24-1]]

^<<v23-24-1,1>>^ Atenção! O Senhor  vai arrasar a terra e fazê-la virar um deserto; vai estragar a terra e espalhar os seus moradores.

[[v23-24-2]]

^<<v23-24-2,2>>^ A mesma coisa acontecerá com todos: o povo comum e os sacerdotes, os empregados e os seus patrões, as empregadas e as suas patroas, os que compram e os que vendem, os que emprestam e os que tomam emprestado.

[[v23-24-3]]

^<<v23-24-3,3>>^ A terra ficará completamente arrasada e destruída, pois o Senhor  prometeu fazer isso.

[[v23-24-4]]

^<<v23-24-4,4>>^ A terra vai secando e murchando, o mundo inteiro vai se acabando, os céus e a terra vão se desfazendo.

[[v23-24-5]]

^<<v23-24-5,5>>^ A terra está impura  por causa dos seus moradores, pois eles desobedeceram às leis  e aos mandamentos de Deus e quebraram a aliança  que devia durar para sempre.

[[v23-24-6]]

^<<v23-24-6,6>>^ Por isso, Deus está amaldiçoando e destruindo a terra, e os seus moradores estão pagando pelos seus pecados; um fogo devorador os está queimando, e poucos escapam com vida.

[[v23-24-7]]

^<<v23-24-7,7>>^ As parreiras  estão murchando, e há falta de vinho. E todos os que estavam alegres gemem de tristeza.

[[v23-24-8]]

^<<v23-24-8,8>>^ Não se ouve mais o barulho dos pandeiros nem a música alegre das liras ; os que faziam festas e cantavam estão calados.

[[v23-24-9]]

^<<v23-24-9,9>>^ Já não se bebe vinho nas festas; as bebidas têm um gosto amargo.

[[v23-24-10]]

^<<v23-24-10,10>>^ A cidade vazia está em ruínas; os moradores trancam as portas das suas casas e não deixam ninguém entrar.

[[v23-24-11]]

^<<v23-24-11,11>>^ Por causa da falta de vinho, o povo grita nas ruas. Toda a alegria desapareceu; ela foi expulsa da terra.

[[v23-24-12]]

^<<v23-24-12,12>>^ A cidade está em ruínas, os portões estão em pedaços.

[[v23-24-13]]

^<<v23-24-13,13>>^ Assim como poucas azeitonas ficam nas oliveiras e poucas uvas ficam nas parreiras depois de terminada a colheita, assim também em todos os países do mundo poucas pessoas ficarão com vida.

[[v23-24-14]]

^<<v23-24-14,14>>^ Os que ficarem com vida cantarão de alegria; os que moram no Oeste proclamarão a grandeza do Senhor ,

[[v23-24-15]]

^<<v23-24-15,15>>^ e os que moram no Leste o louvarão. Os que moram no litoral louvarão o nome do Senhor , o Deus de Israel.

[[v23-24-16]]

^<<v23-24-16,16>>^ Dos lugares mais distantes do mundo, ouvimos a canção de louvor ao Deus justo. Mas eu disse: "Ai de mim! Que desgraça! Já não aguento mais! Os traidores continuam a trair; há falsidade por toda parte!"

[[v23-24-17]]

^<<v23-24-17,17>>^ Escutem, todos os povos! Como animais vocês serão perseguidos pelos caçadores; covas e armadilhas esperam por vocês.

[[v23-24-18]]

^<<v23-24-18,18>>^ Aquele que escapar dos caçadores cairá numa cova, e quem sair da cova será apanhado numa armadilha. As represas do céu vão se abrir, os alicerces da terra serão abalados.

[[v23-24-19]]

^<<v23-24-19,19>>^ A terra vai tremer e se rachar; ela ficará completamente despedaçada.

[[v23-24-20]]

^<<v23-24-20,20>>^ A terra andará cambaleando como um bêbado; será sacudida de um lado para outro como uma barraca na ventania. Os pecados que a terra carrega são tão pesados, que ela cai e não consegue se levantar.

[[v23-24-21]]

^<<v23-24-21,21>>^ Naquele dia, o Senhor  castigará os poderes do céu e também os reis do mundo, na terra.

[[v23-24-22]]

^<<v23-24-22,22>>^ Ele os ajuntará e os jogará numa cova; ali ficarão presos por muito tempo e depois serão castigados.

[[v23-24-23]]

^<<v23-24-23,23>>^ A lua terá vergonha de brilhar, e o sol ficará pálido de medo porque o Senhor  Todo-Poderoso reinará no monte Sião , em Jerusalém. E, na presença dos líderes do seu povo, ele mostrará a sua glória .

'''

xref:023-isaias/023-isaias-023.adoc#v23-23-0[&#60; Capítulo Anterior] | <<v23-24-0,Topo>> | xref:023-isaias/023-isaias-025.adoc#v23-25-0[Próximo Capítulo &#62;]