include::./index.adoc[]

[[v23-35-0]]
=== Isaías, 35
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-35-1]]

^<<v23-35-1,1>>^ O deserto se alegrará, e crescerão flores nas terras secas;

[[v23-35-2]]

^<<v23-35-2,2>>^ cheio de flores, o deserto cantará de alegria. Deus o tornará tão belo como os montes Líbanos, tão fértil como o monte Carmelo e o vale de Sarom. Todos verão a glória  do Senhor , verão a grandeza do nosso Deus.

[[v23-35-3]]

^<<v23-35-3,3>>^ Fortaleçam as mãos cansadas, deem firmeza aos joelhos fracos.

[[v23-35-4]]

^<<v23-35-4,4>>^ Digam aos desanimados: "Não tenham medo; animem-se, pois o nosso Deus está aqui. Ele vem para nos salvar, ele vem para castigar os nossos inimigos."

[[v23-35-5]]

^<<v23-35-5,5>>^ Então os cegos verão, e os surdos ouvirão;

[[v23-35-6]]

^<<v23-35-6,6>>^ os aleijados pularão e dançarão, e os mudos cantarão de alegria. Pois fontes brotarão no deserto, e rios correrão pelas terras secas.

[[v23-35-7]]

^<<v23-35-7,7>>^ A areia quente do deserto virará um lago, e haverá muitas fontes nas terras secas. Os lugares onde agora vivem os animais do deserto virarão brejos onde crescerão taboas e juncos .

[[v23-35-8]]

^<<v23-35-8,8>>^ Haverá ali uma estrada que será chamada de "Caminho da Santidade". Nela, não caminharão os impuros , pois ela pertence somente ao povo de Deus. Até os tolos andarão nela e não se perderão.

[[v23-35-9]]

^<<v23-35-9,9>>^ Nesse caminho, não haverá leões, animais selvagens não passarão por ele; ali andarão somente os salvos.

[[v23-35-10]]

^<<v23-35-10,10>>^ Aqueles a quem o Senhor  salvar voltarão para casa, voltarão cantando para Jerusalém e ali viverão felizes para sempre. A alegria e a felicidade os acompanharão, e não haverá mais tristeza nem choro.

'''

xref:023-isaias/023-isaias-034.adoc#v23-34-0[&#60; Capítulo Anterior] | <<v23-35-0,Topo>> | xref:023-isaias/023-isaias-036.adoc#v23-36-0[Próximo Capítulo &#62;]