include::./index.adoc[]

[[v23-3-0]]
=== Isaías, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-3-1]]

^<<v23-3-1,1>>^ Cuidado! O Senhor , o Deus Todo-Poderoso, vai tirar de Jerusalém e de Judá todo o sustento e todo o mantimento; não haverá nem comida nem água.

[[v23-3-2]]

^<<v23-3-2,2>>^ Ele vai tirar também todas as pessoas importantes: os homens corajosos e os soldados, os juízes e os profetas , os adivinhos e os sábios,

[[v23-3-3]]

^<<v23-3-3,3>>^ os oficiais do exército e as autoridades civis, os conselheiros e todos os feiticeiros.

[[v23-3-4]]

^<<v23-3-4,4>>^ O Senhor  escolherá meninos para governar o seu povo; o poder ficará nas mãos de crianças.

[[v23-3-5]]

^<<v23-3-5,5>>^ Todos perseguirão uns aos outros, cada um explorará o seu vizinho. Os jovens não respeitarão os velhos, e gente que não vale nada desprezará as pessoas honestas.

[[v23-3-6]]

^<<v23-3-6,6>>^ Naquele dia, uma pessoa agarrará um dos seus parentes e lhe dirá: "Você pelo menos tem roupas para vestir. Então venha ser o nosso chefe e governe este montão de ruínas!"

[[v23-3-7]]

^<<v23-3-7,7>>^ Mas o outro responderá: "Eu não posso ajudá-lo. Não tenho nem comida nem roupa na minha casa. Você não vai me fazer virar chefe do nosso povo!"

[[v23-3-8]]

^<<v23-3-8,8>>^ Jerusalém está arrasada, a terra de Judá está em ruínas. Pois com as suas palavras e as suas ações o povo desafia o Senhor e ofende a sua gloriosa  presença.

[[v23-3-9]]

^<<v23-3-9,9>>^ Eles não tratam os outros com igualdade, e isso prova que estão errados. Pecam abertamente como os moradores de Sodoma; não procuram esconder os seus pecados. Ai deles, pois estão trazendo sobre si mesmos o castigo da sua própria maldade!

[[v23-3-10]]

^<<v23-3-10,10>>^ Felizes são as pessoas honestas, pois tudo dará certo para elas, e elas ficarão satisfeitas com aquilo que ganharem com o seu trabalho!

[[v23-3-11]]

^<<v23-3-11,11>>^ Ai dos maus, pois tudo correrá mal para eles! O mal que fizeram aos outros será feito contra eles.

[[v23-3-12]]

^<<v23-3-12,12>>^ Crianças governam o meu povo; o poder está nas mãos das mulheres. Meu povo, as autoridades estão enganando vocês, estão lhes mostrando o caminho errado.

[[v23-3-13]]

^<<v23-3-13,13>>^ O Senhor  Deus vai apresentar a sua causa; ele está pronto para julgar o seu povo.

[[v23-3-14]]

^<<v23-3-14,14>>^ Contra as autoridades e os líderes, ele fará esta acusação: "Foram vocês que acabaram com Israel, a minha plantação de uvas! As suas casas estão cheias das coisas que vocês roubaram dos pobres!

[[v23-3-15]]

^<<v23-3-15,15>>^ Com que direito vocês esmagam o meu povo e exploram os pobres?" É o Senhor , o Deus Todo-Poderoso, quem está falando.

[[v23-3-16]]

^<<v23-3-16,16>>^ O Senhor  Deus disse: "Vejam como as mulheres de Jerusalém são vaidosas! Andam com o nariz para cima, dão olhares atrevidos e caminham com passos curtos, fazendo barulho com os enfeites dos tornozelos.

[[v23-3-17]]

^<<v23-3-17,17>>^ Por isso, eu, o Senhor , vou castigá-las: raparei a sua cabeça e as deixarei carecas."

[[v23-3-18]]

^<<v23-3-18,18>>^ Naquele dia, o Senhor tirará das mulheres de Jerusalém todos os seus enfeites: os que elas usam nos tornozelos e na cabeça, os colares,

[[v23-3-19]]

^<<v23-3-19,19>>^ os brincos e as pulseiras. Tirará os véus,

[[v23-3-20]]

^<<v23-3-20,20>>^ os chapéus e os enfeites para os braços e os cintos e faixas. Tirará os frascos de perfume, os talismãs ,

[[v23-3-21]]

^<<v23-3-21,21>>^ os anéis e as argolas de usar no nariz;

[[v23-3-22]]

^<<v23-3-22,22>>^ os vestidos luxuosos, os mantos , os xales e as bolsas;

[[v23-3-23]]

^<<v23-3-23,23>>^ as saias transparentes, os lenços de linho, os turbantes  e as mantilhas.

[[v23-3-24]]

^<<v23-3-24,24>>^ Em vez de andarem perfumadas, elas vão cheirar mal; em vez de cintos finos, usarão cordas grosseiras. Não farão penteados bonitos, mas ficarão carecas. Não usarão roupas finas, mas roupas feitas de pano grosseiro. A beleza delas vai virar uma feiura de dar vergonha!

[[v23-3-25]]

^<<v23-3-25,25>>^ Os homens de Jerusalém serão mortos na guerra; até os mais valentes morrerão.

[[v23-3-26]]

^<<v23-3-26,26>>^ A cidade ficará de luto e chorará como se fosse uma mulher sentada no chão, completamente abandonada.

'''

xref:023-isaias/023-isaias-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaias/023-isaias-004.adoc#v23-4-0[Próximo Capítulo &#62;]