include::./index.adoc[]

[[v23-9-0]]
=== Isaías, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-9-1]]

^<<v23-9-1,1>>^ Mas a aflição dos que estiverem sofrendo vai acabar. No passado, Deus humilhou a terra das tribos  de Zebulom e de Naftali, mas no futuro ele tornará famosa essa região, que vai desde o mar Mediterrâneo até a terra que fica no lado leste do rio Jordão, isto é, a Galileia dos pagãos.

[[v23-9-2]]

^<<v23-9-2,2>>^ O povo que andava na escuridão viu uma forte luz; a luz brilhou sobre os que viviam nas trevas.

[[v23-9-3]]

^<<v23-9-3,3>>^ Tu, ó Deus, aumentaste esse povo e lhe deste muita felicidade. Eles se alegram pelo que tens feito, como se alegram os que fazem as colheitas ou como os que repartem as riquezas tomadas na guerra.

[[v23-9-4]]

^<<v23-9-4,4>>^ Tu arrebentaste as suas correntes de escravos, quebraste o bastão com que eram castigados; acabaste com o inimigo que os dominava, assim como no passado acabaste com os midianitas.

[[v23-9-5]]

^<<v23-9-5,5>>^ As botas barulhentas dos soldados e todas as suas roupas sujas de sangue serão completamente destruídas pelo fogo.

[[v23-9-6]]

^<<v23-9-6,6>>^ Pois já nasceu uma criança, Deus nos mandou um menino que será o nosso rei. Ele será chamado de "Conselheiro Maravilhoso", "Deus Poderoso", "Pai Eterno", "Príncipe da Paz".

[[v23-9-7]]

^<<v23-9-7,7>>^ Ele será descendente do rei Davi; o seu poder como rei crescerá, e haverá paz em todo o seu reino. As bases do seu governo serão a justiça e o direito, desde o começo e para sempre. No seu grande amor, o Senhor  Todo-Poderoso fará com que tudo isso aconteça.

[[v23-9-8]]

^<<v23-9-8,8>>^ Deus anuncia que vai castigar o povo de Israel, os descendentes de Jacó.

[[v23-9-9]]

^<<v23-9-9,9>>^ Todo o povo de Israel e todos os moradores de Samaria sabem o que ele vai fazer. Orgulhosos e vaidosos, eles dizem:

[[v23-9-10]]

^<<v23-9-10,10>>^ "Caíram as casas feitas de tijolos, mas nós as construiremos de novo com pedras; as vigas de madeira de figueira brava foram cortadas, mas agora vamos usar vigas de cedro."

[[v23-9-11]]

^<<v23-9-11,11>>^ Por isso, o Senhor  atiça os inimigos deles e manda que os ataquem.

[[v23-9-12]]

^<<v23-9-12,12>>^ A Síria, a leste, e a Filisteia, a oeste, abriram a sua boca para devorar o povo de Israel. Mesmo assim a ira  de Deus não passou; a sua mão continua levantada para castigar.

[[v23-9-13]]

^<<v23-9-13,13>>^ O Senhor  Todo-Poderoso castigou o seu povo, mas eles não se arrependeram, não voltaram para Deus.

[[v23-9-14]]

^<<v23-9-14,14>>^ Portanto, num dia só, o Senhor vai cortar a cabeça e o rabo do Reino de Israel, como se faz com um animal; vai derrubar as palmeiras e os juncos .

[[v23-9-15]]

^<<v23-9-15,15>>^ (Os mais velhos e os mais respeitados são a cabeça; os profetas  que anunciam mentiras são o rabo.)

[[v23-9-16]]

^<<v23-9-16,16>>^ As autoridades guiaram o povo por caminhos errados, e por isso o povo anda perdido.

[[v23-9-17]]

^<<v23-9-17,17>>^ Portanto, o Senhor não terá pena dos jovens, nem terá compaixão dos órfãos e das viúvas. Pois ninguém crê em Deus; todos são maus e falam tolices. Mesmo assim, a ira de Deus não passou; a sua mão continua levantada para castigar.

[[v23-9-18]]

^<<v23-9-18,18>>^ A maldade do povo queima como o fogo que destrói o mato e os espinheiros. É como um incêndio na floresta, que faz subir nuvens de fumaça.

[[v23-9-19]]

^<<v23-9-19,19>>^ O Senhor  Todo-Poderoso está irado, e por isso a terra está sendo queimada, e o povo está sendo destruído. Ninguém tem pena dos outros.

[[v23-9-20]]

^<<v23-9-20,20>>^ Comem até a carne dos seus próprios filhos! Cada um devora a comida que consegue arranjar, mas assim mesmo continua com fome.

[[v23-9-21]]

^<<v23-9-21,21>>^ O povo da tribo de Manassés ataca o de Efraim, o povo da tribo de Efraim ataca o de Manassés, e os dois juntos atacam o povo de Judá. Mesmo assim, a ira de Deus não passou; a sua mão continua levantada para castigar.

'''

xref:023-isaias/023-isaias-008.adoc#v23-8-0[&#60; Capítulo Anterior] | <<v23-9-0,Topo>> | xref:023-isaias/023-isaias-010.adoc#v23-10-0[Próximo Capítulo &#62;]