include::./index.adoc[]

[[v23-13-0]]
=== Isaías, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-13-1]]

^<<v23-13-1,1>>^ Esta é a mensagem a respeito da Babilônia que Isaías, filho de Amoz, recebeu numa visão:

[[v23-13-2]]

^<<v23-13-2,2>>^ Em cima de um monte pelado, levantem a bandeira de guerra! Deem ordem para os inimigos atacarem e levantem a mão como sinal para que eles entrem pelos portões da cidade majestosa.

[[v23-13-3]]

^<<v23-13-3,3>>^ O Senhor  está chamando os seus soldados fiéis, os seus homens valentes, que se alegram com a vitória. Ele os está chamando para que castiguem aqueles com quem ele está irado .

[[v23-13-4]]

^<<v23-13-4,4>>^ Ouve-se uma gritaria nas montanhas! São exércitos que estão se ajuntando! Soldados de muitas nações se reúnem para a guerra; o Senhor  Todo-Poderoso está preparando um exército para a batalha.

[[v23-13-5]]

^<<v23-13-5,5>>^ As tropas vêm da Pérsia, um país distante, vêm lá do fim do mundo. Na sua ira, o Senhor vai usá-las para destruir a Babilônia inteira.

[[v23-13-6]]

^<<v23-13-6,6>>^ Chorem e gritem, pois está chegando o Dia do Senhor ; a destruição enviada pelo Todo-Poderoso está perto!

[[v23-13-7]]

^<<v23-13-7,7>>^ Os braços de todos ficarão sem força, e de medo os corações deles baterão mais rápido,

[[v23-13-8]]

^<<v23-13-8,8>>^ pois o pavor tomará conta deles. Sofrerão e chorarão como uma mulher com dores de parto, se torcerão como uma mulher que está dando à luz. Olharão uns para os outros, cheios de medo, e os rostos deles ficarão vermelhos de vergonha.

[[v23-13-9]]

^<<v23-13-9,9>>^ Está chegando o Dia do Senhor , dia terrível da sua ira violenta e furiosa. A terra será arrasada, e os pecadores serão mortos.

[[v23-13-10]]

^<<v23-13-10,10>>^ Todas as estrelas deixarão de brilhar; logo ao nascer, o sol ficará escuro, e a lua também não brilhará mais.

[[v23-13-11]]

^<<v23-13-11,11>>^ O Senhor  Deus diz: "Eu vou castigar o mundo por causa das suas maldades; vou castigar as pessoas perversas por causa dos seus pecados. Acabarei com o orgulho dos vaidosos e humilharei as pessoas violentas.

[[v23-13-12]]

^<<v23-13-12,12>>^ Quando eu acabar de castigá-los, as pessoas que ficarem vivas serão mais raras do que o ouro, do que o ouro puro de Ofir.

[[v23-13-13]]

^<<v23-13-13,13>>^ No dia em que eu, o Senhor  Todo-Poderoso, mostrar a minha ira e o meu furor, farei com que os céus tremam e com que a terra saia do seu lugar.

[[v23-13-14]]

^<<v23-13-14,14>>^ "Os estrangeiros que moram na Babilônia fugirão e voltarão para os seus próprios países. Serão como gazelas  que fogem dos caçadores, como ovelhas que não têm pastor.

[[v23-13-15]]

^<<v23-13-15,15>>^ Os que forem alcançados e forem presos serão mortos à espada.

[[v23-13-16]]

^<<v23-13-16,16>>^ Diante dos seus próprios olhos, os seus filhos serão esmagados, as suas casas serão assaltadas, e as suas mulheres, violentadas.

[[v23-13-17]]

^<<v23-13-17,17>>^ "Contra os babilônios vou atiçar os medos , um povo que não faz caso de prata nem de ouro.

[[v23-13-18]]

^<<v23-13-18,18>>^ Com as suas flechas, eles matarão os jovens; matarão crianças e bebês sem dó nem piedade.

[[v23-13-19]]

^<<v23-13-19,19>>^ Babilônia é a glória  e o orgulho do seu povo, a mais bela cidade de todos os reinos; mas ela vai ficar como Sodoma e Gomorra quando eu as destruí.

[[v23-13-20]]

^<<v23-13-20,20>>^ Babilônia ficará completamente vazia, e nunca mais ninguém morará ali. Os viajantes árabes não armarão ali as suas barracas, e nenhum pastor levará as suas ovelhas para pastarem lá.

[[v23-13-21]]

^<<v23-13-21,21>>^ Os animais do deserto viverão na cidade, e as casas ficarão cheias de corujas; avestruzes morarão ali, e cabras selvagens saltarão entre as ruínas.

[[v23-13-22]]

^<<v23-13-22,22>>^ Nas torres e nos palácios, uivarão as hienas e as raposas. Está chegando a hora da Babilônia; os seus dias já estão contados."

'''

xref:023-isaias/023-isaias-012.adoc#v23-12-0[&#60; Capítulo Anterior] | <<v23-13-0,Topo>> | xref:023-isaias/023-isaias-014.adoc#v23-14-0[Próximo Capítulo &#62;]