include::./index.adoc[]

[[v23-46-0]]
=== Isaías, 46
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-46-1]]

^<<v23-46-1,1>>^ "Os deuses Bel e Nebo se inclinam e caem no chão. Esses ídolos são colocados nas costas de animais de carga; são um peso enorme para os animais cansados.

[[v23-46-2]]

^<<v23-46-2,2>>^ Os deuses se inclinam e caem; eles não podem se salvar e são levados pelos inimigos.

[[v23-46-3]]

^<<v23-46-3,3>>^ "Escute, povo de Israel; escutem, todos os descendentes de Jacó que ficaram vivos! Desde que vocês nasceram, eu os tenho carregado; sempre cuidei de vocês.

[[v23-46-4]]

^<<v23-46-4,4>>^ E, quando ficarem velhos, eu serei o mesmo Deus; cuidarei de vocês quando tiverem cabelos brancos. Eu os criei e os carregarei; eu os ajudarei e salvarei.

[[v23-46-5]]

^<<v23-46-5,5>>^ "Com quem é que vocês podem me comparar? Quem é parecido comigo?

[[v23-46-6]]

^<<v23-46-6,6>>^ Há gente que pega uma boa porção do seu ouro e uma enorme quantidade da sua prata e paga um ourives para que com esse ouro e com essa prata ele faça um deus. E depois se ajoelham diante desse deus e o adoram.

[[v23-46-7]]

^<<v23-46-7,7>>^ Então carregam a imagem nas costas e a colocam no seu lugar; e ali ela fica, sem poder se mexer. Se pedirem socorro à imagem, ela não atende; ela não pode livrá-los das suas dificuldades.

[[v23-46-8]]

^<<v23-46-8,8>>^ "Pecadores, lembrem disso: pensem bem e tenham juízo.

[[v23-46-9]]

^<<v23-46-9,9>>^ Lembrem do que aconteceu no passado e reconheçam que só eu sou Deus, que não há nenhum outro como eu.

[[v23-46-10]]

^<<v23-46-10,10>>^ Desde o princípio, anunciei as coisas do futuro; há muito tempo, eu disse o que ia acontecer. Afirmei que o meu plano seria cumprido, que eu faria tudo o que havia resolvido fazer.

[[v23-46-11]]

^<<v23-46-11,11>>^ Estou chamando um homem para que venha do Oriente; de um país distante, ele vem rápido como uma águia para fazer o que eu ordeno. Vou cumprir o que prometi; vou fazer o que planejei.

[[v23-46-12]]

^<<v23-46-12,12>>^ "Gente teimosa, escute aqui! Vocês pensam que a sua salvação vai demorar.

[[v23-46-13]]

^<<v23-46-13,13>>^ Mas eu vou fazer chegar logo a salvação que prometi; ela não vai demorar, e em breve eu conseguirei a vitória. Eu salvarei os moradores de Sião e repartirei com o povo de Israel a minha grandeza."

'''

xref:023-isaias/023-isaias-045.adoc#v23-45-0[&#60; Capítulo Anterior] | <<v23-46-0,Topo>> | xref:023-isaias/023-isaias-047.adoc#v23-47-0[Próximo Capítulo &#62;]