include::./index.adoc[]

[[v23-6-0]]
=== Isaías, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-6-1]]

^<<v23-6-1,1>>^ No ano em que o rei Uzias morreu, eu vi o Senhor sentado num trono alto e elevado. O seu manto  se estendia pelo Templo inteiro,

[[v23-6-2]]

^<<v23-6-2,2>>^ e em volta dele estavam serafins . Cada um deles tinha seis asas: com duas eles cobriam o rosto, com duas cobriam o corpo e com as outras duas voavam.

[[v23-6-3]]

^<<v23-6-3,3>>^ Eles diziam em voz alta uns para os outros: "Santo, santo, santo é o Senhor  Todo-Poderoso; a sua presença gloriosa  enche o mundo inteiro!"

[[v23-6-4]]

^<<v23-6-4,4>>^ O barulho das vozes dos serafins fez tremer os alicerces do Templo, que foi ficando cheio de fumaça.

[[v23-6-5]]

^<<v23-6-5,5>>^ Então eu disse: — Ai de mim! Estou perdido! Pois os meus lábios são impuros , e moro no meio de um povo que também tem lábios impuros. E com os meus próprios olhos vi o Rei, o Senhor  Todo-Poderoso!

[[v23-6-6]]

^<<v23-6-6,6>>^ Aí um dos serafins voou para mim, segurando com uma tenaz uma brasa que havia tirado do altar.

[[v23-6-7]]

^<<v23-6-7,7>>^ Ele tocou a minha boca com a brasa e disse: — Agora que esta brasa tocou os seus lábios, as suas culpas estão tiradas, e os seus pecados estão perdoados.

[[v23-6-8]]

^<<v23-6-8,8>>^ Em seguida, ouvi o Senhor dizer: — Quem é que eu vou enviar? Quem será o nosso mensageiro? Então respondi: — Aqui estou eu. Envia-me a mim!

[[v23-6-9]]

^<<v23-6-9,9>>^ O Senhor  Deus me disse: — Vá e diga ao povo o seguinte: "Vocês podem escutar o quanto quiserem, mas não vão entender nada; podem olhar bem, mas não enxergarão nada."

[[v23-6-10]]

^<<v23-6-10,10>>^ Isaías, faça com que esse povo fique com a mente fechada, com os ouvidos surdos e com os olhos cegos, a fim de que não possam ver, nem ouvir, nem entender. Pois, se pudessem, eles voltariam para mim e seriam curados.

[[v23-6-11]]

^<<v23-6-11,11>>^ — Até quando isso vai durar? — eu perguntei. Ele respondeu: — Até que as cidades sejam destruídas e fiquem sem moradores, as casas fiquem completamente vazias, e os campos sejam arrasados.

[[v23-6-12]]

^<<v23-6-12,12>>^ Eu, o Senhor , mandarei o povo para longe deste país, e as cidades ficarão vazias.

[[v23-6-13]]

^<<v23-6-13,13>>^ E, mesmo que fique no país uma pessoa em dez, ela também será morta. Os que restarem serão como o toco de um carvalho que foi cortado. O toco representa um novo começo para o povo de Deus.

'''

xref:023-isaias/023-isaias-005.adoc#v23-5-0[&#60; Capítulo Anterior] | <<v23-6-0,Topo>> | xref:023-isaias/023-isaias-007.adoc#v23-7-0[Próximo Capítulo &#62;]