include::./index.adoc[]

[[v23-57-0]]
=== Isaías, 57
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-57-1]]

^<<v23-57-1,1>>^ "As pessoas direitas morrem, e ninguém se importa; os bons desaparecem, e ninguém percebe. É o poder do mal que os leva embora,

[[v23-57-2]]

^<<v23-57-2,2>>^ mas eles encontram a paz. Os que vivem uma vida correta descansam em paz na sepultura."

[[v23-57-3]]

^<<v23-57-3,3>>^ O Senhor  Deus diz: "Venham cá para serem julgados, seus filhos de uma feiticeira, raça de adúlteros e prostitutas!

[[v23-57-4]]

^<<v23-57-4,4>>^ De quem é que vocês estão zombando? De quem é que caçoam com essas caretas? Vocês são pecadores e mentirosos.

[[v23-57-5]]

^<<v23-57-5,5>>^ "Debaixo das árvores sagradas, vocês se entregam à imoralidade para adorar os deuses da fertilidade. E nas fendas das rochas, perto dos ribeirões, vocês oferecem os seus filhos em sacrifício  aos deuses pagãos.

[[v23-57-6]]

^<<v23-57-6,6>>^ Vocês pegam pedras lisas dos riachos, para serem os deuses que vocês adoram, e apresentam a elas ofertas de vinho e de cereais. Vocês estão pensando que isso me agrada?

[[v23-57-7]]

^<<v23-57-7,7>>^ Vocês vão para o alto das montanhas, e ali praticam atos imorais, e oferecem sacrifícios aos deuses pagãos.

[[v23-57-8]]

^<<v23-57-8,8>>^ Vocês colocam os seus ídolos indecentes atrás da porta das suas casas. Esquecem de mim, tiram a roupa e deitam-se na cama com os seus amantes, a quem pagarem para dormir com vocês; e então satisfazem os seus desejos impuros .

[[v23-57-9]]

^<<v23-57-9,9>>^ "Vocês pegaram azeite e muitos perfumes e foram adorar o deus Moloque . Enviaram mensageiros por toda parte à procura de deuses para adorar, e esses mensageiros foram até o mundo dos mortos .

[[v23-57-10]]

^<<v23-57-10,10>>^ Vocês se cansaram de tanto viajar, mas não ficaram desanimados. As suas imagens nojentas lhes deram forças, e por isso vocês não desistiram.

[[v23-57-11]]

^<<v23-57-11,11>>^ "Vocês têm tanto medo desses deuses! Mas quem são eles para que vocês me contem mentiras e me esqueçam completamente? Será que é porque eu fiquei calado tanto tempo, que vocês não me temem ?

[[v23-57-12]]

^<<v23-57-12,12>>^ Eu vou mostrar a todos o que vocês fazem, essas ações que vocês acham certas; mas elas não adiantarão nada.

[[v23-57-13]]

^<<v23-57-13,13>>^ Quando vocês gritarem pedindo ajuda, os seus muitos deuses não os atenderão. O vento levará esses deuses para longe, um sopro os fará desaparecer. Mas os que confiam em mim morarão na Terra Prometida ; o meu monte santo  será deles."

[[v23-57-14]]

^<<v23-57-14,14>>^ O Senhor  diz: "Preparem o caminho, aplanem a estrada, para que o meu povo possa voltar para mim."

[[v23-57-15]]

^<<v23-57-15,15>>^ Pois o Altíssimo, o Santo Deus, o Deus que vive para sempre, diz: "Eu moro num lugar alto e sagrado, mas moro também com os humildes e os aflitos, para dar esperança aos humildes e aos aflitos, novas forças.

[[v23-57-16]]

^<<v23-57-16,16>>^ Não continuarei repreendendo o meu povo e não ficarei irado  para sempre; se não, morreriam os seres que eu criei, aqueles a quem dei o sopro da vida.

[[v23-57-17]]

^<<v23-57-17,17>>^ Por causa do pecado e da cobiça do meu povo, eu fiquei irado com eles e os castiguei. Na minha ira, eu me afastei deles, mas mesmo assim eles continuaram teimosos e seguiram o seu próprio caminho.

[[v23-57-18]]

^<<v23-57-18,18>>^ "Tenho visto como eles agem, mas eu os curarei e os guiarei; eu os consolarei. Nos lábios dos que choram,

[[v23-57-19]]

^<<v23-57-19,19>>^ colocarei palavras de louvor. A todos ofereço a paz, paz aos que estão perto e aos que estão longe; eu os curarei.

[[v23-57-20]]

^<<v23-57-20,20>>^ Porém os maus são como o mar agitado: as suas ondas não se acalmam e trazem lama e sujeira para a terra.

[[v23-57-21]]

^<<v23-57-21,21>>^ Não há segurança para esses pecadores." O meu Deus falou.

'''

xref:023-isaias/023-isaias-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaias/023-isaias-058.adoc#v23-58-0[Próximo Capítulo &#62;]