include::./index.adoc[]

[[v23-32-0]]
=== Isaías, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-32-1]]

^<<v23-32-1,1>>^ Virá o dia em que um rei reinará com justiça e as autoridades governarão com honestidade.

[[v23-32-2]]

^<<v23-32-2,2>>^ Todas elas protegerão o povo como um abrigo protege contra a tempestade e o vento; elas serão como rios numa terra seca, como a sombra de uma grande rocha no deserto.

[[v23-32-3]]

^<<v23-32-3,3>>^ Então todos poderão ver claramente de novo e de novo ouvirão tudo facilmente;

[[v23-32-4]]

^<<v23-32-4,4>>^ serão ajuizados, entenderão as coisas e poderão falar com clareza e inteligência.

[[v23-32-5]]

^<<v23-32-5,5>>^ Ninguém dirá que um sem-vergonha é uma pessoa de valor, nem que o malandro merece respeito.

[[v23-32-6]]

^<<v23-32-6,6>>^ Pois o sem-vergonha diz mentiras e está sempre planejando fazer maldades. O que ele diz a respeito do Senhor  é falso; ele faz estas coisas que Deus detesta: nega comida aos que têm fome e água aos que estão com sede.

[[v23-32-7]]

^<<v23-32-7,7>>^ O malandro faz trapaças; inventa mentiras para prejudicar a causa dos pobres, mesmo quando eles têm razão.

[[v23-32-8]]

^<<v23-32-8,8>>^ Mas quem é direito faz planos honestos e é correto em tudo o que faz.

[[v23-32-9]]

^<<v23-32-9,9>>^ Mulheres desocupadas, escutem o que eu vou dizer; prestem atenção, mulheres que não se preocupam com nada!

[[v23-32-10]]

^<<v23-32-10,10>>^ Daqui a pouco mais de um ano, vocês ficarão aflitas, pois não haverá colheita de uvas.

[[v23-32-11]]

^<<v23-32-11,11>>^ Vocês têm tido uma vida sem preocupações, mas agora tremam e fiquem aflitas. Tirem as suas roupas e vistam roupas feitas de pano grosseiro.

[[v23-32-12]]

^<<v23-32-12,12>>^ Batam no peito em sinal de tristeza; chorem porque as terras boas e as parreiras  carregadas de uvas foram destruídas.

[[v23-32-13]]

^<<v23-32-13,13>>^ Espinheiros e mato crescerão na terra do meu povo. Chorem por causa da cidade que era tão alegre, por causa das casas que estavam cheias de pessoas felizes!

[[v23-32-14]]

^<<v23-32-14,14>>^ O palácio será abandonado, a cidade ficará vazia, e as fortalezas virarão montes de ruínas para sempre. Ali os jumentos selvagens andarão à vontade, e os rebanhos pastarão.

[[v23-32-15]]

^<<v23-32-15,15>>^ Mas Deus derramará sobre nós o seu Espírito; então o deserto virará um campo fértil, e as terras cultivadas darão melhores colheitas.

[[v23-32-16]]

^<<v23-32-16,16>>^ No país, haverá justiça por toda parte; todos farão o que é direito.

[[v23-32-17]]

^<<v23-32-17,17>>^ A justiça trará paz e tranquilidade, trará segurança que durará para sempre.

[[v23-32-18]]

^<<v23-32-18,18>>^ O meu povo viverá em lugares seguros; todos estarão em paz e segurança nas suas casas.

[[v23-32-19]]

^<<v23-32-19,19>>^ (Uma chuva de pedra destruirá a floresta, e a cidade será arrasada.)

[[v23-32-20]]

^<<v23-32-20,20>>^ Todos vocês serão felizes; terão muita água para as suas plantações e pastos seguros para os seus jumentos e o seu gado.

'''

xref:023-isaias/023-isaias-031.adoc#v23-31-0[&#60; Capítulo Anterior] | <<v23-32-0,Topo>> | xref:023-isaias/023-isaias-033.adoc#v23-33-0[Próximo Capítulo &#62;]