include::./index.adoc[]

[[v23-8-0]]
=== Isaías, 8
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-8-1]]

^<<v23-8-1,1>>^ O Senhor  Deus me disse: — Pegue uma tabuleta grande e escreva nela, em letras bem grandes, o seguinte: "Maer-Salal-Hás-Baz" .

[[v23-8-2]]

^<<v23-8-2,2>>^ E procure dois homens de confiança, isto é, o sacerdote Urias e Zacarias, filho de Jeberequias, para servirem de testemunhas.

[[v23-8-3]]

^<<v23-8-3,3>>^ Algum tempo depois, a minha mulher, a profetisa , ficou grávida e deu à luz um filho. Aí o Senhor  me disse: — Ponha nele o nome de Maer-Salal-Hás-Baz.

[[v23-8-4]]

^<<v23-8-4,4>>^ Pois, antes que ele aprenda a dizer "papai" ou "mamãe", o rei da Assíria levará embora todas as riquezas de Damasco e de Samaria.

[[v23-8-5]]

^<<v23-8-5,5>>^ O Senhor  falou comigo de novo. Ele disse:

[[v23-8-6]]

^<<v23-8-6,6>>^ — Esse povo não quis as águas calmas do riacho de Siloé e está tremendo de medo do rei Rezim e do rei Peca.

[[v23-8-7]]

^<<v23-8-7,7>>^ Por isso, eu, o Senhor , vou trazer o rei da Assíria e o seu poderoso exército para atacarem esse povo. Eles avançarão como uma enchente do rio Eufrates que sobe acima das margens de todos os canais e de todos os rios que desembocam nele.

[[v23-8-8]]

^<<v23-8-8,8>>^ Eles invadirão a terra de Judá como as águas de uma enchente que cobrem tudo e sobem até o pescoço da gente. Mas Deus está com o seu povo. As suas asas abertas protegem a Terra Prometida .

[[v23-8-9]]

^<<v23-8-9,9>>^ Reúnam-se, povos, mas fiquem com medo! Escutem, todos os países distantes! Preparem-se para a guerra, mas vocês serão derrotados! Sim, preparem-se para a guerra, mas vocês serão derrotados!

[[v23-8-10]]

^<<v23-8-10,10>>^ Façam planos, mas eles não darão certo. Resolvam o que quiserem, mas tudo fracassará, pois Deus está conosco.

[[v23-8-11]]

^<<v23-8-11,11>>^ O Senhor  Deus pôs a sua poderosa mão sobre mim e avisou a mim e aos meus seguidores que não andássemos no caminho que o povo estava seguindo. Ele nos disse:

[[v23-8-12]]

^<<v23-8-12,12>>^ — Não pensem que tudo o que o povo chama de revolução seja revolução mesmo. Não fiquem assustados, nem tenham medo daquilo de que o povo tem medo.

[[v23-8-13]]

^<<v23-8-13,13>>^ Pelo contrário, fiquem assustados por minha causa e tenham medo de mim, pois eu, o Senhor  Todo-Poderoso, sou santo.

[[v23-8-14]]

^<<v23-8-14,14>>^ Eu serei um templo para abrigar vocês; serei também uma pedra e uma rocha que fará com que os povos de Judá e de Israel tropecem e caiam; serei uma armadilha e um laço para pegar os moradores de Jerusalém.

[[v23-8-15]]

^<<v23-8-15,15>>^ Muitos tropeçarão, cairão e se despedaçarão; ficarão presos nessa armadilha.

[[v23-8-16]]

^<<v23-8-16,16>>^ Eu disse aos meus seguidores: — Guardem a mensagem e lembrem dos ensinamentos que o Senhor  me deu.

[[v23-8-17]]

^<<v23-8-17,17>>^ Ele se escondeu do seu povo, mas eu confio nele e nele ponho a minha esperança.

[[v23-8-18]]

^<<v23-8-18,18>>^ — Aqui estou eu com os filhos que o Senhor  Deus me deu. O Senhor  Todo-Poderoso, que mora no monte Sião , nos enviou para sermos sinais que causem espanto ao povo de Israel.

[[v23-8-19]]

^<<v23-8-19,19>>^ — Algumas pessoas vão pedir que vocês consultem os adivinhos e os médiuns, que cochicham e falam baixinho. Essas pessoas dirão: "Precisamos receber mensagens dos espíritos, precisamos consultar os mortos em favor dos vivos!"

[[v23-8-20]]

^<<v23-8-20,20>>^ Mas vocês respondam assim: "O que devemos fazer é consultar a lei  e os ensinamentos de Deus. O que os médiuns dizem não tem nenhum valor."

[[v23-8-21]]

^<<v23-8-21,21>>^ O povo andará de um lugar para outro, sem rumo, desanimado e com fome. Por causa da fome, ficarão com raiva e amaldiçoarão o seu rei e o seu Deus. Olharão para o céu

[[v23-8-22]]

^<<v23-8-22,22>>^ e depois para a terra e verão somente sofrimento e escuridão, trevas e angústia; porém não poderão escapar delas.

'''

xref:023-isaias/023-isaias-007.adoc#v23-7-0[&#60; Capítulo Anterior] | <<v23-8-0,Topo>> | xref:023-isaias/023-isaias-009.adoc#v23-9-0[Próximo Capítulo &#62;]