include::./index.adoc[]

[[v23-37-0]]
=== Isaías, 37
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-37-1]]

^<<v23-37-1,1>>^ Assim que o rei Ezequias ouviu o que eles contaram, rasgou as suas roupas em sinal de tristeza, vestiu uma roupa feita de pano grosseiro e foi para o Templo do Senhor .

[[v23-37-2]]

^<<v23-37-2,2>>^ Ele mandou que Eliaquim, o encarregado do palácio, Sebna, o escrivão, e os sacerdotes mais idosos fossem falar com o profeta Isaías, filho de Amoz. Eles também estavam vestindo roupa feita de pano grosseiro.

[[v23-37-3]]

^<<v23-37-3,3>>^ A mensagem que o rei mandou entregar a Isaías foi esta: "Hoje, é um dia de sofrimento; nós estamos sendo castigados e estamos envergonhados. Somos como uma mulher que está para dar à luz, mas não tem forças para isso.

[[v23-37-4]]

^<<v23-37-4,4>>^ O rei da Assíria nos mandou o chefe do seu exército para insultar o Deus vivo. Que o Senhor , nosso Deus, ouça esses insultos e castigue quem os disse! Portanto, ore a Deus pelas pessoas do nosso povo que ainda estão vivas."

[[v23-37-5]]

^<<v23-37-5,5>>^ Isaías recebeu a mensagem do rei Ezequias

[[v23-37-6]]

^<<v23-37-6,6>>^ e mandou esta resposta: "O Senhor  Deus diz que o senhor não deve deixar que os assírios o assustem, dizendo que Deus não pode salvá-lo.

[[v23-37-7]]

^<<v23-37-7,7>>^ Deus vai fazer o rei da Assíria ouvir uma notícia que o fará voltar para a terra dele e Deus vai fazer com que ele seja morto ali."

[[v23-37-8]]

^<<v23-37-8,8>>^ O oficial assírio soube que o rei da Assíria havia saído de Laquis e que estava lutando contra a cidade de Libna. Portanto, foi até lá para falar com ele.

[[v23-37-9]]

^<<v23-37-9,9>>^ O rei ouviu dizer que o exército dos egípcios, comandado pelo rei Tiraca, da Etiópia, vinha vindo para atacá-lo. Então mandou uma carta para o rei Ezequias, de Judá.

[[v23-37-10]]

^<<v23-37-10,10>>^ A carta dizia assim: "O seu deus, em quem você confia, lhe disse que Jerusalém não vai cair nas minhas mãos; mas não deixe que ele o engane.

[[v23-37-11]]

^<<v23-37-11,11>>^ Você já ouviu falar daquilo que um rei assírio faz com qualquer país que ele resolve destruir? Por acaso, você pensa que poderá escapar?

[[v23-37-12]]

^<<v23-37-12,12>>^ Os meus antepassados destruíram as cidades de Gozã, Harã e Rezefe e mataram o povo de Éden, que morava em Telassar, e nenhum dos seus deuses os pôde salvar.

[[v23-37-13]]

^<<v23-37-13,13>>^ Onde estão os reis das cidades de Hamate, de Arpade, de Sefarvaim, de Hena e de Iva?"

[[v23-37-14]]

^<<v23-37-14,14>>^ O rei Ezequias recebeu a carta das mãos dos mensageiros e a leu. Depois, foi até o Templo, pôs a carta ali, na presença de Deus, o Senhor ,

[[v23-37-15]]

^<<v23-37-15,15>>^ e orou assim:

[[v23-37-16]]

^<<v23-37-16,16>>^ — Ó Senhor  Todo-Poderoso, Deus de Israel, que estás sentado no teu trono que fica acima dos querubins ! Só tu és Deus e governas todos os reinos do mundo. Tu criaste o céu e a terra.

[[v23-37-17]]

^<<v23-37-17,17>>^ Ó Senhor , olha para o que está acontecendo com a gente. Escuta todas as coisas que Senaqueribe está dizendo a fim de insultar a ti, o Deus vivo.

[[v23-37-18]]

^<<v23-37-18,18>>^ Todos nós sabemos, ó Deus, que os reis da Assíria destruíram muitas nações, arrasaram as suas terras

[[v23-37-19]]

^<<v23-37-19,19>>^ e queimaram os seus deuses, que não eram deuses de verdade e sim imagens de madeira e de pedra, feitas por mãos humanas.

[[v23-37-20]]

^<<v23-37-20,20>>^ Agora, ó Senhor , nosso Deus, salva-nos dos assírios, a fim de que todas as nações do mundo fiquem sabendo que só tu, ó Senhor , és Deus.

[[v23-37-21]]

^<<v23-37-21,21>>^ Então Isaías mandou uma mensagem para o rei Ezequias. Nela, ele dizia que em resposta à oração do rei,

[[v23-37-22]]

^<<v23-37-22,22>>^ o Senhor , o Deus de Israel, tinha dito o seguinte: "A cidade de Jerusalém ri e caçoa de você, Senaqueribe.

[[v23-37-23]]

^<<v23-37-23,23>>^ A quem você pensa que ofendeu e insultou? De quem zombou? Você fez tudo isso contra mim, o Santo Deus de Israel.

[[v23-37-24]]

^<<v23-37-24,24>>^ Você me mandou os seus oficiais para se gabarem de que com os seus muitos carros de guerra você conquistou as mais altas montanhas do Líbano. Você se gabou de ter cortado os mais altos cedros e os melhores ciprestes e de ter chegado até os lugares mais distantes das florestas.

[[v23-37-25]]

^<<v23-37-25,25>>^ Você se gabou de ter cavado poços em terras estrangeiras e de ter bebido água deles. Gabou-se também de que os pés dos seus soldados fizeram secar o rio Nilo.

[[v23-37-26]]

^<<v23-37-26,26>>^ "Por acaso, você não sabe que fui eu que planejei tudo isso há muito tempo e agora fiz tudo acontecer? Eu dei a você o poder de fazer cidades cercadas de muralhas virarem montões de entulho.

[[v23-37-27]]

^<<v23-37-27,27>>^ Por isso, os seus moradores ficaram fracos e andaram cheios de medo e de vergonha. Eles ficaram como o capim do campo e a erva verde e como a erva que cresce nos telhados e que seca quando o vento quente do leste sopra nele.

[[v23-37-28]]

^<<v23-37-28,28>>^ "Mas eu conheço você muito bem; sei o que você faz e aonde vai. Sei que você me odeia.

[[v23-37-29]]

^<<v23-37-29,29>>^ Eu soube do seu ódio e do seu orgulho, e agora vou pôr uma argola no seu nariz e um freio na sua boca, e farei você voltar pelo mesmo caminho por onde veio."

[[v23-37-30]]

^<<v23-37-30,30>>^ Então Isaías disse ao rei Ezequias: — Este é o sinal daquilo que vai acontecer: neste ano e no ano que vem, vocês terão para comer somente o que nascer por si mesmo, sem ser plantado. Mas no ano seguinte vocês poderão semear e colher cereais e também plantar parreiras  e comer as uvas.

[[v23-37-31]]

^<<v23-37-31,31>>^ As pessoas de Judá que não tiverem morrido vão florescer como plantas que firmam as suas raízes na terra e dão frutas.

[[v23-37-32]]

^<<v23-37-32,32>>^ Pois ficará gente em Jerusalém e no monte Sião  porque o Senhor  Todo-Poderoso resolveu fazer com que isso aconteça.

[[v23-37-33]]

^<<v23-37-33,33>>^ Isaías continuou: — Portanto, o Senhor  diz o seguinte a respeito do rei da Assíria: "Ele não entrará nesta cidade e não atirará uma só flecha contra ela. Nenhum soldado com escudo  chegará perto da cidade, e não serão construídas rampas de ataque ao redor dela.

[[v23-37-34]]

^<<v23-37-34,34>>^ O rei da Assíria vai voltar pelo mesmo caminho por onde veio, sem ter entrado nesta cidade.

[[v23-37-35]]

^<<v23-37-35,35>>^ Eu defenderei e protegerei esta cidade por causa da minha honra e por causa da promessa que fiz ao meu servo  Davi. Eu, o Senhor , falei."

[[v23-37-36]]

^<<v23-37-36,36>>^ Então o Anjo do Senhor  foi até o acampamento dos assírios e matou cento e oitenta e cinco mil soldados. De manhã, os que sobraram viram os corpos dos mortos.

[[v23-37-37]]

^<<v23-37-37,37>>^ Aí Senaqueribe, o rei da Assíria, se retirou, voltou para Nínive e ficou lá.

[[v23-37-38]]

^<<v23-37-38,38>>^ Certo dia, quando ele estava adorando no templo do seu deus Nisroque, os seus filhos Adrameleque e Sarezer o mataram à espada e fugiram para a terra de Ararate. Outro filho seu, chamado Esar-Hadom, ficou no lugar dele como rei.

'''

xref:023-isaias/023-isaias-036.adoc#v23-36-0[&#60; Capítulo Anterior] | <<v23-37-0,Topo>> | xref:023-isaias/023-isaias-038.adoc#v23-38-0[Próximo Capítulo &#62;]