include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-65-1]]

^<<v23-65-1,1>>^ O Senhor  Deus disse: "Eu estava pronto para atender o meu povo, mas eles não pediram a minha ajuda; estava pronto para ser achado, mas eles não me procuraram. A um povo que não orou a mim, eu disse: ‘Estou aqui! Estou aqui!’

[[v23-65-2]]

^<<v23-65-2,2>>^ O dia inteiro eu abri os braços, pronto para receber um povo rebelde, um povo que anda no caminho do mal, seguindo sempre os seus próprios caprichos.

[[v23-65-3]]

^<<v23-65-3,3>>^ Essa gente vive me provocando abertamente; eles oferecem sacrifícios  em jardins sagrados e queimam incenso sobre altares pagãos.

[[v23-65-4]]

^<<v23-65-4,4>>^ Eles vão aos cemitérios para consultar os mortos e passam as noites em lugares desertos para receber visões. Comem carne de porco e enchem os seus pratos de comida impura .

[[v23-65-5]]

^<<v23-65-5,5>>^ Depois, dizem aos outros: ‘Parem! Não nos toquem, pois somos mais santos do que vocês.’ Essa gente me faz ficar irado ; a minha ira é como um fogo que não se apaga.

[[v23-65-6]]

^<<v23-65-6,6>>^ Tudo o que eles fazem está escrito no meu livro, e não descansarei até castigá-los. Eu farei com que eles paguem pelos seus pecados

[[v23-65-7]]

^<<v23-65-7,7>>^ e também pelos pecados dos seus antepassados. Eles queimaram incenso sobre altares pagãos, nos montes, e me ofenderam com esses sacrifícios. Por isso, farei com que eles paguem pelos seus pecados, por todos eles, um por um." O Senhor  falou.

[[v23-65-8]]

^<<v23-65-8,8>>^ O Senhor  diz: "Quando alguém encontra algumas uvas cheias de suco numa parreira , diz: ‘Não vamos destruí-las, pois o vinho que fizermos com elas será uma bênção para nós.’ Assim também, por amor dos meus servos , eu não destruirei todo o meu povo.

[[v23-65-9]]

^<<v23-65-9,9>>^ Farei com que os descendentes de Jacó e o povo da tribo  de Judá tenham muitos descendentes e com que sejam donos da minha terra. O meu povo escolhido será dono da Terra Prometida e sempre viverá nela.

[[v23-65-10]]

^<<v23-65-10,10>>^ E, se o meu povo procurar fazer a minha vontade, a planície de Sarom servirá de pasto para as suas ovelhas, e o seu gado pastará no vale da Desgraça.

[[v23-65-11]]

^<<v23-65-11,11>>^ "Mas alguns de vocês se afastam de mim; desprezam o meu monte santo e fazem ofertas de comida e de vinho a Gade e a Meni, os deuses da sorte e do destino.

[[v23-65-12]]

^<<v23-65-12,12>>^ Pois então o destino de vocês será morrer à espada; eu farei com que todos fiquem de joelhos para serem mortos. Pois eu os chamei, mas vocês não responderam; eu lhes falei, mas vocês não deram atenção. Pelo contrário, fizeram o que me desagrada, escolheram coisas que me aborrecem."

[[v23-65-13]]

^<<v23-65-13,13>>^ Portanto, o Senhor  Deus diz: "Aqueles que me servem terão comida e bebida, mas vocês passarão fome e sede; eles serão felizes, mas vocês serão humilhados;

[[v23-65-14]]

^<<v23-65-14,14>>^ eles cantarão, cheios de alegria, mas vocês gemerão de tristeza, chorarão com o coração cheio de angústia.

[[v23-65-15]]

^<<v23-65-15,15>>^ "Eu, o Senhor  Deus, os matarei. E os meus servos, o meu povo escolhido, usarão os nomes de vocês para rogar pragas. Mas nos meus servos eu porei um novo nome.

[[v23-65-16]]

^<<v23-65-16,16>>^ Qualquer pessoa na Terra Prometida que pedir uma bênção vai pedi-la ao Deus fiel; e quem fizer uma promessa a fará em nome do Deus fiel." O Senhor  diz ao seu povo: "Vocês esquecerão as desgraças que sofreram, e eu também não lembrarei mais delas.

[[v23-65-17]]

^<<v23-65-17,17>>^ Pois eu estou criando um novo céu e uma nova terra; o passado será esquecido, e ninguém lembrará mais dele.

[[v23-65-18]]

^<<v23-65-18,18>>^ Alegrem-se, fiquem felizes para sempre com aquilo que eu vou criar; pois vou encher de alegria a cidade de Jerusalém e vou dar muita felicidade ao seu povo.

[[v23-65-19]]

^<<v23-65-19,19>>^ Eu ficarei contente com Jerusalém, e o meu povo me encherá de alegria. Nunca mais se ouvirá em Jerusalém nem barulho de choro nem gritos de aflição.

[[v23-65-20]]

^<<v23-65-20,20>>^ Nunca mais morrerão ali criancinhas de poucos dias; ninguém morrerá antes de ficar bem velho. Morrer aos cem anos será morrer moço, e não chegar aos cem anos será uma maldição.

[[v23-65-21]]

^<<v23-65-21,21>>^ "Vocês construirão casas e morarão nelas, farão plantações de uvas e beberão do seu vinho.

[[v23-65-22]]

^<<v23-65-22,22>>^ Não construirão casas para outros morarem nelas, nem farão plantações de uvas para outros beberem do seu vinho. O meu povo viverá muitos anos, como as árvores, e todos terão o prazer de aproveitar as coisas que eles mesmos fizeram.

[[v23-65-23]]

^<<v23-65-23,23>>^ Todo o seu trabalho dará certo, e os seus filhos não acabarão na desgraça; pois eles e os seus descendentes serão a raça que eu abençoarei para sempre.

[[v23-65-24]]

^<<v23-65-24,24>>^ Antes mesmo que me chamem, eu os atenderei; antes mesmo de acabarem de falar, eu responderei.

[[v23-65-25]]

^<<v23-65-25,25>>^ Os lobos e os carneirinhos pastarão juntos, os leões comerão palha como os bois, e as cobras não atacarão mais ninguém. E no meu monte santo não acontecerá nada que seja mau ou perigoso." O Senhor  falou.

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]