include::./index.adoc[]

[[v23-31-0]]
=== Isaías, 31
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-31-1]]

^<<v23-31-1,1>>^ Ai dos que vão para o Egito procurando ajuda! Eles confiam num povo que tem muitos cavalos e carros de guerra, num país que tem cavaleiros valentes, mas não confiam no Santo Deus de Israel, não pedem ajuda ao Senhor .

[[v23-31-2]]

^<<v23-31-2,2>>^ Porém o Senhor  é sábio e sabe fazer com que a desgraça venha; ele sempre cumpre o que promete. Por isso, ele ficará contra os que praticam o mal, contra todos os que ajudam as pessoas perversas.

[[v23-31-3]]

^<<v23-31-3,3>>^ Os egípcios não são deuses! Eles são apenas seres humanos, e os seus cavalos são apenas animais mortais; não são espíritos imortais . E, quando o Senhor  levantar a mão para castigá-los, todos cairão mortos de uma só vez, tanto o Egito, a nação forte, como Judá, a nação fraca.

[[v23-31-4]]

^<<v23-31-4,4>>^ O Senhor  Deus falou comigo e disse: "Um leão que pega e mata uma ovelha não se assusta, nem foge quando os pastores vêm gritando, mesmo que sejam muitos e gritem bem alto. Assim também eu, o Senhor  Todo-Poderoso, não me assustarei quando descer para lutar no monte Sião .

[[v23-31-5]]

^<<v23-31-5,5>>^ Como uma ave fica voando por cima do seu ninho para protegê-lo, assim eu, o Senhor  Todo-Poderoso, protegerei Jerusalém; eu salvarei a cidade e livrarei o meu povo."

[[v23-31-6]]

^<<v23-31-6,6>>^ Povo de Israel, vocês se afastaram para longe de Deus; mas agora arrependam-se e voltem para ele.

[[v23-31-7]]

^<<v23-31-7,7>>^ Naquele dia, todos vocês jogarão fora as suas imagens revestidas de prata e de ouro, que só servem para fazer vocês pecarem.

[[v23-31-8]]

^<<v23-31-8,8>>^ O Senhor  diz: "Uma espada derrotará os assírios, uma espada os matará; mas não será a espada de um ser humano. Eles fugirão da batalha, e os seus jovens serão feitos escravos.

[[v23-31-9]]

^<<v23-31-9,9>>^ O rei fugirá apavorado, e os oficiais, cheios de medo, abandonarão as suas bandeiras." Assim fala o Senhor , que em Jerusalém tem o seu altar, onde sacrifícios  são queimados.

'''

xref:023-isaias/023-isaias-030.adoc#v23-30-0[&#60; Capítulo Anterior] | <<v23-31-0,Topo>> | xref:023-isaias/023-isaias-032.adoc#v23-32-0[Próximo Capítulo &#62;]