include::./index.adoc[]

[[v23-45-0]]
=== Isaías, 45
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-45-1]]

^<<v23-45-1,1>>^ O Senhor ungiu  Ciro como rei. Ele o pegou pela mão direita e lhe deu poder para conquistar nações e derrotar reis. Para que Ciro entre nas cidades, o Senhor  abre os portões, e ninguém pode fechá-los de novo. O Senhor  Deus diz a Ciro:

[[v23-45-2]]

^<<v23-45-2,2>>^ "Eu irei na sua frente e aplanarei as montanhas; arrebentarei portões de bronze e quebrarei as suas trancas de ferro.

[[v23-45-3]]

^<<v23-45-3,3>>^ Eu lhe darei tesouros escondidos, riquezas guardadas em lugares secretos a fim de que você saiba que eu sou o Senhor , o Deus de Israel, que o chama pelo nome.

[[v23-45-4]]

^<<v23-45-4,4>>^ Eu o estou chamando  para que você ajude o povo de Israel, o meu povo escolhido. E, embora você não me conheça, eu lhe dou um título de honra.

[[v23-45-5]]

^<<v23-45-5,5>>^ "Eu, e somente eu, sou o Senhor ; não há outro deus além de mim. Embora você não me conheça, eu lhe dou força para lutar.

[[v23-45-6]]

^<<v23-45-6,6>>^ Faço isso para que, de leste a oeste, o mundo inteiro saiba que além de mim não existe outro deus. Eu, e somente eu, sou o Senhor .

[[v23-45-7]]

^<<v23-45-7,7>>^ Eu sou o Criador da luz e da escuridão e mando bênçãos e maldições; eu, o Senhor , faço tudo isso.

[[v23-45-8]]

^<<v23-45-8,8>>^ "Assim como a chuva vem de cima, eu enviarei do céu a minha vitória. A terra se abrirá para recebê-la e fará brotar a salvação e a liberdade. Eu, o Senhor , farei isso."

[[v23-45-9]]

^<<v23-45-9,9>>^ Um vaso de barro não briga com quem o fez. O barro não pergunta ao oleiro: "O que é que você está fazendo?", nem diz: "Você não sabe trabalhar."

[[v23-45-10]]

^<<v23-45-10,10>>^ E um filho não se atreve a dizer aos seus pais: "Por que vocês fizeram com que eu viesse ao mundo?"

[[v23-45-11]]

^<<v23-45-11,11>>^ O Senhor , o Santo Deus de Israel, o seu Criador, diz: "Por acaso, vocês vão exigir que eu explique como cuido dos meus filhos? Vocês querem me ensinar a fazer as coisas?

[[v23-45-12]]

^<<v23-45-12,12>>^ Fui eu que fiz a terra e criei os seres humanos para morarem nela. Com as minhas próprias mãos, estendi o céu e ordenei que o sol, a lua e as estrelas aparecessem.

[[v23-45-13]]

^<<v23-45-13,13>>^ Eu mesmo ordenei a Ciro que começasse a agir e lhe prometi a vitória. Eu aplanarei os caminhos por onde ele vai passar. Ele reconstruirá Jerusalém, a minha cidade, e porá em liberdade o meu povo que está no cativeiro , sem exigir nenhum pagamento para fazer isso. Sou eu, o Senhor  Todo-Poderoso, quem está falando."

[[v23-45-14]]

^<<v23-45-14,14>>^ O Senhor  diz ao povo de Israel: "Vocês ficarão com as riquezas do Egito, da Etiópia e dos moradores de Sebá, aquela gente alta. Vocês os derrotarão, e eles serão os seus escravos; e, presos com correntes, irão andando atrás de vocês. Eles se ajoelharão na frente de vocês e declararão humildemente: ‘Deus está com vocês, e não há outro deus além dele.’ "

[[v23-45-15]]

^<<v23-45-15,15>>^ O Deus de Israel, que salva o seu povo, é um Deus que se esconde das pessoas.

[[v23-45-16]]

^<<v23-45-16,16>>^ Os que fazem imagens serão humilhados, todos eles passarão vergonha.

[[v23-45-17]]

^<<v23-45-17,17>>^ Mas o povo de Israel foi salvo pelo Senhor ; ele os salvou para sempre, e eles nunca serão humilhados, nem passarão vergonha.

[[v23-45-18]]

^<<v23-45-18,18>>^ O Senhor , que criou os céus, é o único Deus. Ele fez a terra, e lhe deu forma, e a colocou no seu lugar. Ele não a criou para que ficasse vazia, mas para que houvesse moradores nela. O Senhor  Deus diz: "Eu sou o Senhor , e não há outro deus.

[[v23-45-19]]

^<<v23-45-19,19>>^ Eu não falei em segredo, não falei num lugar escuro e não disse ao povo de Israel que me procurasse num lugar deserto. Eu, o Senhor , falo a verdade, e o que digo sempre merece confiança."

[[v23-45-20]]

^<<v23-45-20,20>>^ O Senhor  Deus diz: "Venham e ajuntem-se, todos os povos que escaparam com vida , e apresentem-se no tribunal. Não sabem nada as pessoas que oram a deuses que não podem salvá-las, pessoas que fazem procissões, carregando as suas imagens de madeira.

[[v23-45-21]]

^<<v23-45-21,21>>^ Falem logo e apresentem as suas razões; consultem uns aos outros, se quiserem. Quem foi que anunciou há muito tempo as coisas que iam acontecer? Não fui eu mesmo, o Senhor ? Pois não há outro deus além de mim; eu sou o único Deus, o Deus fiel que salva o seu povo.

[[v23-45-22]]

^<<v23-45-22,22>>^ "Povos do mundo inteiro, voltem para mim, e eu os salvarei, pois eu sou Deus, e não há nenhum outro.

[[v23-45-23]]

^<<v23-45-23,23>>^ Fiz um juramento no meu próprio nome; o que eu digo é verdade e nunca deixará de acontecer. Juro que todos se ajoelharão diante de mim e prometerão ser fiéis a mim.

[[v23-45-24]]

^<<v23-45-24,24>>^ Declararão que somente eu, o Senhor , posso dar poder e vitória. Todos os que me têm combatido ficarão humilhados e envergonhados na minha presença.

[[v23-45-25]]

^<<v23-45-25,25>>^ Mas eu, o Senhor , darei a vitória ao meu povo, e eles me louvarão."

'''

xref:023-isaias/023-isaias-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaias/023-isaias-046.adoc#v23-46-0[Próximo Capítulo &#62;]