include::./index.adoc[]

[[v23-29-0]]
=== Isaías, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-29-1]]

^<<v23-29-1,1>>^ Ai de Jerusalém, o altar de Deus , a cidade onde o rei Davi armou o seu acampamento! Deixem passar alguns anos com as suas festas religiosas,

[[v23-29-2]]

^<<v23-29-2,2>>^ e então Deus castigará a cidade que se chama "O Altar de Deus". Os seus moradores chorarão e se lamentarão; a cidade ficará parecendo um altar coberto de sangue.

[[v23-29-3]]

^<<v23-29-3,3>>^ Deus enviará um exército para atacar a cidade; os soldados inimigos a cercarão e levantarão rampas de ataque contra as muralhas.

[[v23-29-4]]

^<<v23-29-4,4>>^ A cidade será arrasada, e os seus moradores ficarão caídos no chão; falarão como se fossem espíritos, cochichando e murmurando como fantasmas.

[[v23-29-5]]

^<<v23-29-5,5>>^ Mas, de repente, num instante, o Senhor  Todo-Poderoso atacará os inimigos, aquela multidão de estrangeiros. Com trovões, terremotos e estrondos, com ventanias, tempestades e fogo devorador, ele fará os inimigos virarem um pó fino; eles serão como a palha que o vento carrega.

[[v23-29-6]]

^<<v23-29-6,6>>^ Mas, de repente, num instante,

[[v23-29-7]]

^<<v23-29-7,7>>^ Aí todos os inimigos que estiverem atacando "O Altar de Deus", todos os exércitos que estiverem cercando a cidade com rampas de ataque desaparecerão como se fossem um sonho ou uma visão.

[[v23-29-8]]

^<<v23-29-8,8>>^ Todas as nações que atacarem o monte Sião serão como um homem faminto que sonha que está comendo e acorda ainda com fome; serão como uma pessoa sedenta que sonha que está bebendo água e acorda ainda com sede.

[[v23-29-9]]

^<<v23-29-9,9>>^ Continuem sendo tolos, se quiserem! Continuem cegos, se preferirem! E, sem terem tomado vinho ou cerveja, fiquem bêbados e andem por aí tontos.

[[v23-29-10]]

^<<v23-29-10,10>>^ Pois o Senhor  Deus fez com que vocês caíssem num sono profundo; ele cobriu as cabeças de vocês e fechou os seus olhos. As cabeças e os olhos são os profetas , que não veem as visões que Deus envia.

[[v23-29-11]]

^<<v23-29-11,11>>^ Agora, para vocês, todas as visões são como se fossem uma mensagem escrita num livro fechado e lacrado. Se levarem o livro para alguém que sabe ler e pedirem que leia a mensagem, a pessoa dirá: "Não posso; o livro está lacrado."

[[v23-29-12]]

^<<v23-29-12,12>>^ E, se pedirem a alguém que não sabe ler, a pessoa dirá: "Não sei ler."

[[v23-29-13]]

^<<v23-29-13,13>>^ O Senhor diz: "Esse povo ora a mim com a boca e me louva com os lábios, mas o seu coração está longe de mim. A religião que eles praticam não passa de doutrinas e ensinamentos humanos que eles só sabem repetir de cor.

[[v23-29-14]]

^<<v23-29-14,14>>^ Por isso, mais uma vez vou deixar esse povo espantado com as coisas estranhas e terríveis que farei no meio dele. Com toda a sua sabedoria, os seus sábios não poderão explicá-las, e o conhecimento dos que são instruídos não adiantará nada."

[[v23-29-15]]

^<<v23-29-15,15>>^ Ai dos que escondem os seus planos do Senhor , que fazem as suas maldades na escuridão e dizem: "Ninguém nos pode ver! Ninguém sabe o que estamos fazendo!"

[[v23-29-16]]

^<<v23-29-16,16>>^ Vocês invertem as coisas, como se o barro valesse mais do que o oleiro! O pote não vai dizer ao homem que o fez: "Você não me fez." Uma vasilha não dirá ao oleiro: "Você não sabe o que está fazendo."

[[v23-29-17]]

^<<v23-29-17,17>>^ Daqui a pouco, as matas virgens vão virar jardins, e os jardins voltarão a ser mato.

[[v23-29-18]]

^<<v23-29-18,18>>^ Naquele dia, os surdos ouvirão a mensagem que será lida no livro fechado e lacrado, e os cegos ficarão livres da escuridão e poderão ver.

[[v23-29-19]]

^<<v23-29-19,19>>^ O Senhor  dará alegria aos necessitados, o Santo Deus de Israel fará com que os pobres fiquem alegres.

[[v23-29-20]]

^<<v23-29-20,20>>^ Pois Deus acabará com os que exploram o seu povo; os que zombam de Deus serão destruídos, e os que fazem planos para prejudicar os outros desaparecerão.

[[v23-29-21]]

^<<v23-29-21,21>>^ Deus acabará com os que acusam os outros falsamente; acabará com os que procuram enganar os juízes e com os que, por meio de mentiras, conseguem que os inocentes sejam condenados.

[[v23-29-22]]

^<<v23-29-22,22>>^ Portanto, o Senhor , que livrou Abraão de perigos, diz o seguinte a respeito do povo de Israel: "O meu povo não ficará desiludido outra vez, eles nunca mais sentirão vergonha.

[[v23-29-23]]

^<<v23-29-23,23>>^ Pois, quando virem o que vou fazer no meio deles, confessarão que o meu nome é santo, reconhecerão que eu sou o Santo Deus de Israel e me temerão .

'''

xref:023-isaias/023-isaias-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaias/023-isaias-030.adoc#v23-30-0[Próximo Capítulo &#62;]