include::./index.adoc[]

[[v23-10-0]]
=== Isaías, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-10-1]]

^<<v23-10-1,1>>^ Ai de vocês que fazem leis  injustas, leis para explorar o povo!

[[v23-10-2]]

^<<v23-10-2,2>>^ Vocês não defendem os direitos dos pobres nem as causas dos necessitados e exploram as viúvas e os órfãos.

[[v23-10-3]]

^<<v23-10-3,3>>^ O que vocês vão fazer no dia do castigo, quando de um país distante vier a desgraça? A quem vão pedir socorro? Onde esconderão as suas riquezas?

[[v23-10-4]]

^<<v23-10-4,4>>^ Vocês serão levados como prisioneiros, serão mortos na batalha. Mesmo assim, a ira  de Deus não passou; a sua mão continua levantada para castigar.

[[v23-10-5]]

^<<v23-10-5,5>>^ O Senhor  disse: "Ai do rei da Assíria! Ele é o bastão que eu uso para castigar aqueles com quem estou irado.

[[v23-10-6]]

^<<v23-10-6,6>>^ Eu estou mandando que ele ataque um povo pagão, um povo com quem estou irado. Estou ordenando que leve embora tudo o que é deles e que os pise como se fossem a lama das ruas.

[[v23-10-7]]

^<<v23-10-7,7>>^ Mas o rei da Assíria quer mais do que isso; ele tem os seus próprios planos. Só pensa em conquistar muitas nações e destruí-las completamente.

[[v23-10-8]]

^<<v23-10-8,8>>^ Ele diz: ‘Todos os meus comandantes são reis!

[[v23-10-9]]

^<<v23-10-9,9>>^ Tenho conquistado muitas cidades: Calno e Carquemis, Hamate e Arpade; e também conquistei Samaria e Damasco.

[[v23-10-10]]

^<<v23-10-10,10>>^ Já derrotei reinos pagãos, onde o povo adorava muitos ídolos, mais ídolos do que há em Jerusalém ou em Samaria.

[[v23-10-11]]

^<<v23-10-11,11>>^ Já destruí Samaria e os seus ídolos e farei o mesmo com Jerusalém e com os seus ídolos.’ "

[[v23-10-12]]

^<<v23-10-12,12>>^ Quando o Senhor terminar tudo o que está planejando fazer no monte Sião  e em Jerusalém, então ele vai castigar o rei da Assíria, aquele homem orgulhoso e vaidoso.

[[v23-10-13]]

^<<v23-10-13,13>>^ Pois o rei diz: "Fiz tudo isso com a minha própria força e com a minha sabedoria, pois sou inteligente. Mudei de lugar as fronteiras dos países e fiquei com todas as suas riquezas; como se fosse um touro, eu pisei os seus moradores.

[[v23-10-14]]

^<<v23-10-14,14>>^ Eu levei comigo as riquezas das outras nações, como alguém que tira os ovos de um ninho abandonado. Não houve ninguém que batesse as asas, ninguém que desse um pio."

[[v23-10-15]]

^<<v23-10-15,15>>^ Mas será que o machado pensa que é mais importante do que o homem que o usa? Ou será que a serra imagina que vale mais do que a pessoa que serra com ela? Será que um bastão, um simples pedaço de madeira, é capaz de levantar um homem?

[[v23-10-16]]

^<<v23-10-16,16>>^ Por isso, o Senhor , o Deus Todo-Poderoso, enviará contra os fortes soldados assírios uma doença que os deixará sem forças. Mandará uma febre que, como fogo, queimará os corpos deles.

[[v23-10-17]]

^<<v23-10-17,17>>^ O Santo Deus, a Luz de Israel, será um fogo que, num dia só, queimará o mato e os espinheiros da Assíria.

[[v23-10-18]]

^<<v23-10-18,18>>^ O Senhor  destruirá completamente as florestas e as plantações; será como uma doença mortal que acaba matando a pessoa.

[[v23-10-19]]

^<<v23-10-19,19>>^ As árvores que sobrarem serão tão poucas, que até uma criança será capaz de contá-las.

[[v23-10-20]]

^<<v23-10-20,20>>^ Naquele dia, os poucos israelitas que ficarem vivos não vão confiar mais nos assírios, que os fizeram sofrer. Eles vão pôr toda a sua confiança no Senhor , o Santo Deus de Israel.

[[v23-10-21]]

^<<v23-10-21,21>>^ Alguns israelitas voltarão para o poderoso Deus.

[[v23-10-22]]

^<<v23-10-22,22>>^ Mesmo que agora o povo de Israel seja tão numeroso como os grãos de areia da praia do mar, somente alguns voltarão. Deus já decidiu destruir o seu povo; a justiça virá como se fosse uma enchente.

[[v23-10-23]]

^<<v23-10-23,23>>^ Pois o Senhor , o Deus Todo-Poderoso, decidiu destruir este país inteiro e ele fará o que decidiu fazer.

[[v23-10-24]]

^<<v23-10-24,24>>^ Portanto, o Senhor , o Deus Todo-Poderoso, diz ao seu povo, que mora em Sião : — Meu povo, não fique com medo dos assírios quando eles castigarem e maltratarem vocês como os egípcios fizeram.

[[v23-10-25]]

^<<v23-10-25,25>>^ Pois daqui a pouco deixarei de castigar vocês e na minha ira  destruirei os assírios.

[[v23-10-26]]

^<<v23-10-26,26>>^ Eu, o Senhor  Todo-Poderoso, castigarei os assírios com o meu chicote como fiz com os midianitas perto da pedra de Orebe. Eu os castigarei como castiguei o Egito.

[[v23-10-27]]

^<<v23-10-27,27>>^ Naquele dia, eu livrarei vocês da escravidão e tirarei a pesada carga que os assírios puseram nas suas costas. Os inimigos vêm da direção de Rimom,

[[v23-10-28]]

^<<v23-10-28,28>>^ já conquistaram a cidade de Ai , passaram por Migrom e deixaram a bagagem em Micmás.

[[v23-10-29]]

^<<v23-10-29,29>>^ Atravessaram a passagem entre as montanhas e à noite estão acampando em Geba. Os moradores de Ramá estão tremendo de medo, e os de Gibeá, a cidade do rei Saul, já fugiram.

[[v23-10-30]]

^<<v23-10-30,30>>^ Gritem, moradores de Galim! Escute os gritos, gente de Laís! Responda, povo de Anatote!

[[v23-10-31]]

^<<v23-10-31,31>>^ Os moradores de Madmena estão fugindo, fogem também os de Gebim.

[[v23-10-32]]

^<<v23-10-32,32>>^ Hoje mesmo os inimigos chegam até a cidade de Nobe e dali ameaçam o monte Sião , a cidade de Jerusalém.

[[v23-10-33]]

^<<v23-10-33,33>>^ Mas o Senhor , o Deus Todo-Poderoso, derrubará e humilhará os assírios mais orgulhosos como se cortam os galhos altos de uma árvore ou como se derrubam árvores enormes.

[[v23-10-34]]

^<<v23-10-34,34>>^ Com o seu machado, ele derrubará as árvores da floresta, e elas cairão como caem as belas árvores do Líbano.

'''

xref:023-isaias/023-isaias-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaias/023-isaias-011.adoc#v23-11-0[Próximo Capítulo &#62;]