include::./index.adoc[]

[[v23-56-0]]
=== Isaías, 56
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-56-1]]

^<<v23-56-1,1>>^ O Senhor  Deus diz ao seu povo: "Sigam a justiça e façam o que é direito, pois daqui a pouco eu vou livrá-los, mostrando assim o meu poder salvador.

[[v23-56-2]]

^<<v23-56-2,2>>^ Felizes são os que obedecem às leis  a respeito do sábado! Felizes os que não praticam o que é mau!"

[[v23-56-3]]

^<<v23-56-3,3>>^ O estrangeiro que adora o Senhor não deve dizer: "O Senhor  vai me expulsar do seu povo." E um eunuco  não deve pensar: "Eu não posso ter filhos e por isso não posso pertencer ao povo de Deus."

[[v23-56-4]]

^<<v23-56-4,4>>^ Pois o Senhor  diz aos eunucos: "Obedeçam às leis a respeito do sábado, façam aquilo que me agrada e sejam fiéis à minha aliança .

[[v23-56-5]]

^<<v23-56-5,5>>^ Se um eunuco fizer isso, eu lhe darei uma coisa melhor do que filhos e filhas. Eu farei com que o seu nome seja escrito no meu Templo, e ele fará parte do meu povo para sempre; o seu nome nunca será esquecido."

[[v23-56-6]]

^<<v23-56-6,6>>^ E aos estrangeiros que adoram o Senhor , que o amam e o servem fielmente, o Senhor  Deus diz: "Se vocês obedecerem às leis a respeito do sábado e forem fiéis à minha aliança,

[[v23-56-7]]

^<<v23-56-7,7>>^ eu os levarei ao meu monte santo , e vocês ficarão felizes na minha casa de oração. Eu aceitarei os sacrifícios  e as ofertas que vocês apresentarem no meu altar. Pois a minha casa será chamada de ‘Casa de Oração’ para todos os povos.

[[v23-56-8]]

^<<v23-56-8,8>>^ Vou trazer ainda outros para a terra de Israel e juntá-los ao meu povo que eu já trouxe de volta." É isso o que diz o Senhor  Deus, que trouxe de volta para a terra de Israel o seu povo que era prisioneiro em terras estrangeiras.

[[v23-56-9]]

^<<v23-56-9,9>>^ O Senhor  Deus diz: "Venham, animais selvagens , venham e devorem o rebanho .

[[v23-56-10]]

^<<v23-56-10,10>>^ Os guardas do meu povo são cegos; eles não veem nada. Todos são como cachorros mudos, que não podem latir; estão sempre deitados, dormindo; são uns preguiçosos que só gostam de dormir e sonhar.

[[v23-56-11]]

^<<v23-56-11,11>>^ Esses cachorros são gulosos e sempre querem mais comida. Os pastores do meu rebanho não entendem nada; todos seguem os seus próprios caminhos e procuram os seus próprios interesses.

[[v23-56-12]]

^<<v23-56-12,12>>^ Eles dizem uns aos outros: ‘Vamos procurar vinho e cerveja e cair na bebedeira. Amanhã, faremos a mesma coisa, e ainda mais do que hoje!’

'''

xref:023-isaias/023-isaias-055.adoc#v23-55-0[&#60; Capítulo Anterior] | <<v23-56-0,Topo>> | xref:023-isaias/023-isaias-057.adoc#v23-57-0[Próximo Capítulo &#62;]