include::./index.adoc[]

[[v23-33-0]]
=== Isaías, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-33-1]]

^<<v23-33-1,1>>^ Ai de você, inimigo destruidor que nunca foi destruído! Ai de você, traidor que nunca foi traído! Quando você acabar de destruir, será destruído; quando acabar de trair, será traído.

[[v23-33-2]]

^<<v23-33-2,2>>^ Ó Senhor  Deus, tem compaixão de nós, pois esperamos que nos ajudes. Sê o nosso protetor todos os dias, sê o nosso Salvador em tempos de dificuldades.

[[v23-33-3]]

^<<v23-33-3,3>>^ Os povos fogem quando ouvem o estrondo da tua voz. Quando ages, as nações se espalham,

[[v23-33-4]]

^<<v23-33-4,4>>^ e os inimigos delas, como uma nuvem de gafanhotos, levam embora tudo o que elas têm.

[[v23-33-5]]

^<<v23-33-5,5>>^ O Senhor  é majestoso, pois mora nas alturas; ele encherá Sião  de justiça e de honestidade

[[v23-33-6]]

^<<v23-33-6,6>>^ e fará com que o seu povo viva em segurança, dando-lhe salvação completa, sabedoria e conhecimento. O temor  do Senhor  é o tesouro mais precioso que o seu povo tem.

[[v23-33-7]]

^<<v23-33-7,7>>^ Os soldados valentes estão se lamentando nas ruas, e os embaixadores que procuravam fazer a paz choram amargamente.

[[v23-33-8]]

^<<v23-33-8,8>>^ As estradas estão vazias, ninguém viaja por elas. Os acordos  são quebrados, os tratados são desfeitos; ninguém é respeitado.

[[v23-33-9]]

^<<v23-33-9,9>>^ As terras do país vão se gastando e se desfazendo; as florestas dos montes Líbanos estão secas, o vale de Sarom virou um deserto, e na região de Basã e no monte Carmelo as árvores perderam as suas folhas.

[[v23-33-10]]

^<<v23-33-10,10>>^ O Senhor  diz aos povos: "Agora, eu vou agir; vou mostrar o meu poder e a minha grandeza.

[[v23-33-11]]

^<<v23-33-11,11>>^ O que vocês inventam vale menos do que a palha; o que vocês planejam é tão sem valor como o lixo. O meu sopro, como um fogo, os destruirá.

[[v23-33-12]]

^<<v23-33-12,12>>^ Vocês vão virar cinzas; queimarão como espinhos jogados no fogo.

[[v23-33-13]]

^<<v23-33-13,13>>^ Vocês todos, os que estão longe e os que estão perto, escutem o que eu fiz e reconheçam o meu poder!"

[[v23-33-14]]

^<<v23-33-14,14>>^ Em Sião, os pecadores tremem de medo; cheios de pavor, eles perguntam: "Quem poderá viver perto desse fogo devorador, perto dessas chamas que não param de queimar?"

[[v23-33-15]]

^<<v23-33-15,15>>^ Somente poderá fazer isso quem age corretamente e sempre diz a verdade; que não fica rico à custa dos fracos, nem aceita dinheiro para torcer a justiça; que não se junta com os que planejam crimes de morte, nem concorda com os planos dos maus.

[[v23-33-16]]

^<<v23-33-16,16>>^ Quem age assim viverá seguro, e em fortalezas feitas de pedras ele encontrará refúgio; ele sempre terá comida, e nunca lhe faltará água para beber.

[[v23-33-17]]

^<<v23-33-17,17>>^ Mais uma vez vocês verão um rei com toda a sua glória , governando um país imenso.

[[v23-33-18]]

^<<v23-33-18,18>>^ Vocês pensarão no medo que sentiram no passado e perguntarão: "Onde estão aqueles que nos forçavam a pagar tributos, aqueles que cobravam os impostos? Onde estão os que controlavam as nossas fortalezas?"

[[v23-33-19]]

^<<v23-33-19,19>>^ Vocês nunca mais verão aquele povo orgulhoso, aquela gente que fala uma língua estranha, uma língua difícil que ninguém entende.

[[v23-33-20]]

^<<v23-33-20,20>>^ Vejam Sião , a cidade onde fazemos as nossas festas! Jerusalém será uma cidade segura, será como uma barraca que não pode ser mudada de lugar; nenhuma das suas estacas será arrancada, e nenhuma das suas cordas será arrebentada.

[[v23-33-21]]

^<<v23-33-21,21>>^ Ali estará conosco o Senhor , o nosso glorioso  Deus. Jerusalém será um lugar de grandes rios e ribeirões, mas neles não navegarão os barcos dos inimigos nem os seus grandes navios a vela.

[[v23-33-22]]

^<<v23-33-22,22>>^ As cordas desses navios estão frouxas: o mastro não fica firme, e as velas não podem ser estendidas. Assim pegaremos todas as riquezas do inimigo; serão tantas, que até os aleijados conseguirão pegar a sua parte. Pois o Senhor  é o nosso Juiz, é ele quem nos governa; o Senhor  é o nosso Rei, é ele quem vai nos salvar.

[[v23-33-23]]

^<<v23-33-23,23>>^ As cordas desses navios estão frouxas:

'''

xref:023-isaias/023-isaias-032.adoc#v23-32-0[&#60; Capítulo Anterior] | <<v23-33-0,Topo>> | xref:023-isaias/023-isaias-034.adoc#v23-34-0[Próximo Capítulo &#62;]