include::./index.adoc[]

[[v23-64-0]]
=== Isaías, 64
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-64-1]]

^<<v23-64-1,1>>^ Como gostaríamos que tu rasgasses os céus e descesses, fazendo as montanhas tremerem diante de ti!

[[v23-64-2]]

^<<v23-64-2,2>>^ Elas seriam como a água que ferve em cima de um fogo forte. Os teus inimigos reconheceriam a tua fama e tremeriam de medo diante de ti.

[[v23-64-3]]

^<<v23-64-3,3>>^ Quando fizeste coisas maravilhosas, que nós nem esperávamos, tu desceste do céu, e as montanhas tremeram diante de ti.

[[v23-64-4]]

^<<v23-64-4,4>>^ Nunca ninguém viu ou ouviu falar de outro deus além de ti, de um deus que faz coisas assim em favor dos que confiam nele.

[[v23-64-5]]

^<<v23-64-5,5>>^ Tu aceitas os que fazem com prazer o que é direito, os que lembram de viver de acordo com a tua vontade. Tu estavas irado conosco, mas nós continuamos a pecar; só seremos salvos se andarmos nos caminhos antigos.

[[v23-64-6]]

^<<v23-64-6,6>>^ Todos nós nos tornamos impuros , todas as nossas boas ações são como trapos sujos. Somos como folhas secas; e os nossos pecados, como uma ventania, nos carregam para longe.

[[v23-64-7]]

^<<v23-64-7,7>>^ Não há mais ninguém que ore a ti, ninguém que procure a tua ajuda. Por causa dos nossos pecados, tu te escondeste de nós e nos abandonaste.

[[v23-64-8]]

^<<v23-64-8,8>>^ Mas tu, ó Senhor  Deus, és o nosso Pai; nós somos o barro, tu és o oleiro, todos nós fomos feitos por ti.

[[v23-64-9]]

^<<v23-64-9,9>>^ Não continues tão irado, ó Senhor , nem lembres para sempre os nossos pecados. Não esqueças que somos o teu povo.

[[v23-64-10]]

^<<v23-64-10,10>>^ As tuas santas cidades viraram um deserto, Jerusalém está arrasada, o monte Sião  está abandonado.

[[v23-64-11]]

^<<v23-64-11,11>>^ O nosso belo e sagrado Templo, onde os nossos antepassados te louvaram, foi destruído pelo fogo. Tudo o que amávamos está em ruínas!

[[v23-64-12]]

^<<v23-64-12,12>>^ Vendo tudo isso, ó Senhor , não vais fazer nada? Será que vais ficar calado e nos castigar mais ainda?

'''

xref:023-isaias/023-isaias-063.adoc#v23-63-0[&#60; Capítulo Anterior] | <<v23-64-0,Topo>> | xref:023-isaias/023-isaias-065.adoc#v23-65-0[Próximo Capítulo &#62;]