include::./index.adoc[]

[[v23-4-0]]
=== Isaías, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-4-1]]

^<<v23-4-1,1>>^ Naquele dia, sete mulheres agarrarão um homem e dirão: "Nós pagaremos a nossa própria comida e a nossa roupa. Mas deixe-nos dizer que você é o nosso marido, para que fiquemos livres da vergonha de sermos solteiras."

[[v23-4-2]]

^<<v23-4-2,2>>^ Naquele dia, o "Ramo Novo" que o Senhor  Deus plantar crescerá forte e bonito, e os moradores de Israel que continuarem vivos ficarão alegres e orgulhosos por causa das ricas bênçãos que vão receber.

[[v23-4-3]]

^<<v23-4-3,3>>^ Aqueles de Jerusalém que Deus escolher para continuarem vivos serão chamados de "Povo Santo".

[[v23-4-4]]

^<<v23-4-4,4>>^ O Senhor julgará e castigará Sião ; ele purificará a cidade de toda a impureza e de todos os seus crimes de morte.

[[v23-4-5]]

^<<v23-4-5,5>>^ Então sobre o monte Sião e sobre o povo ali reunido o Senhor  estenderá uma nuvem durante o dia e chamas de fogo e fumaça durante a noite. A glória  de Deus cobrirá e protegerá o seu povo.

[[v23-4-6]]

^<<v23-4-6,6>>^ De dia, ela será uma sombra, para protegê-los do calor; e, quando vierem as chuvas e as tempestades, será também um abrigo e uma proteção.

'''

xref:023-isaias/023-isaias-003.adoc#v23-3-0[&#60; Capítulo Anterior] | <<v23-4-0,Topo>> | xref:023-isaias/023-isaias-005.adoc#v23-5-0[Próximo Capítulo &#62;]