include::./index.adoc[]

[[v23-30-0]]
=== Isaías, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-30-1]]

^<<v23-30-1,1>>^ O Senhor  Deus diz: "Ai dos meus filhos que se revoltam contra mim, que fazem planos sem me consultarem e assinam acordos  sem a minha aprovação! Assim amontoam pecado em cima de pecado.

[[v23-30-2]]

^<<v23-30-2,2>>^ Pois, sem me pedirem licença, as autoridades de Judá foram ao Egito pedir socorro ao seu rei, pois confiavam no seu poder para proteger Judá.

[[v23-30-3]]

^<<v23-30-3,3>>^ Mas em vez de socorro virá a desilusão, e em vez de proteção haverá humilhação.

[[v23-30-4]]

^<<v23-30-4,4>>^ Os embaixadores de Judá já chegaram ao Egito, às cidades de Zoã e de Hanes.

[[v23-30-5]]

^<<v23-30-5,5>>^ Mas eles só sentirão vergonha, pois os egípcios não os ajudarão em nada; pelo contrário, serão motivo de vergonha e humilhação."

[[v23-30-6]]

^<<v23-30-6,6>>^ Esta é a mensagem de Deus a respeito das feras da região Sul . "Os embaixadores atravessam uma região perigosa e difícil, onde há leões, cobras e dragões voadores. Nas costas dos seus jumentos e dos seus camelos, vão os presentes e as riquezas que eles levam para um povo que não pode socorrê-los;

[[v23-30-7]]

^<<v23-30-7,7>>^ pois a ajuda do Egito não vale nada. Por isso, estou pondo no Egito o apelido de ‘O Dragão Manso’."

[[v23-30-8]]

^<<v23-30-8,8>>^ O Senhor  Deus me disse: "Escreva a mensagem numa tábua a fim de que fique registrada para sempre como testemunha eterna contra o povo.

[[v23-30-9]]

^<<v23-30-9,9>>^ Pois são gente rebelde, pessoas mentirosas, que não querem ouvir a lei  do Senhor .

[[v23-30-10]]

^<<v23-30-10,10>>^ Eles pedem aos videntes  que não tenham visões e dizem aos profetas : ‘Não nos anunciem a verdade; inventem coisas que nos agradem.

[[v23-30-11]]

^<<v23-30-11,11>>^ Deem o fora! Parem de nos amolar! Não nos falem mais a respeito do Santo Deus de Israel!’ "

[[v23-30-12]]

^<<v23-30-12,12>>^ Por isso, o Santo Deus de Israel diz ao seu povo: "Vocês rejeitam a minha mensagem e põem a sua confiança e a sua fé na violência e na mentira.

[[v23-30-13]]

^<<v23-30-13,13>>^ Portanto, esse pecado vai trazer a ruína para vocês; ele será como uma brecha que vai se abrindo num muro alto: de repente, o muro desmorona e cai no chão.

[[v23-30-14]]

^<<v23-30-14,14>>^ Vocês serão completamente destruídos, como um vaso de barro que se quebra: não sobra nem um caco que sirva para tirar brasas do fogo ou para tirar água do poço."

[[v23-30-15]]

^<<v23-30-15,15>>^ O Senhor , o Santo Deus de Israel, diz ao seu povo: "Se voltarem para mim e ficarem calmos, vocês serão salvos; fiquem tranquilos e confiem em mim, e eu lhes darei a vitória. Mas vocês não quiseram fazer o que eu disse.

[[v23-30-16]]

^<<v23-30-16,16>>^ Pelo contrário, disseram assim: ‘Não! Nós vamos montar cavalos ligeiros e assim escaparemos do inimigo!’ Pois fujam, se puderem; mas os cavalos dos inimigos são mais ligeiros do que os seus.

[[v23-30-17]]

^<<v23-30-17,17>>^ Mil de vocês fugirão de um só inimigo que os atacar, cinco inimigos farão com que todos vocês fujam. Os poucos que restarem parecerão um mastro de bandeira sozinho no alto de um morro."

[[v23-30-18]]

^<<v23-30-18,18>>^ No entanto, o Senhor  continua esperando porque ele quer ser bondoso e ter compaixão de vocês; pois ele é Deus que faz o que é direito. Felizes são aqueles que põem a sua esperança nele!

[[v23-30-19]]

^<<v23-30-19,19>>^ Povo de Jerusalém, moradores de Sião , vocês não vão chorar mais. Quando vocês clamarem pedindo socorro, o Senhor  Deus ficará com pena de vocês; ele os ouvirá e atenderá.

[[v23-30-20]]

^<<v23-30-20,20>>^ O Senhor lhes dará o pão de dores e a água do sofrimento, mas não se esconderá de vocês. Ele é o seu mestre, e vocês o encontrarão quando quiserem.

[[v23-30-21]]

^<<v23-30-21,21>>^ Se vocês se desviarem do caminho, indo para a direita ou para a esquerda, ouvirão a voz dele atrás de vocês, dizendo: "O caminho certo é este; andem nele."

[[v23-30-22]]

^<<v23-30-22,22>>^ Vocês pegarão as suas imagens revestidas de prata e os seus ídolos folheados a ouro e os jogarão fora como se fossem coisas impuras . Vocês dirão a eles: "Fora daqui!"

[[v23-30-23]]

^<<v23-30-23,23>>^ Quando vocês espalharem as sementes nos seus campos, o Senhor  mandará chuva, e as colheitas serão boas. Haverá muito pasto para o gado,

[[v23-30-24]]

^<<v23-30-24,24>>^ e os bois e jumentos que vocês usam para arar os campos comerão da melhor ração, preparada cuidadosamente e misturada com sal.

[[v23-30-25]]

^<<v23-30-25,25>>^ Quando chegar o dia em que os inimigos forem mortos e as suas fortalezas destruídas, rios e riachos jorrarão de todos os morros e de todas as montanhas.

[[v23-30-26]]

^<<v23-30-26,26>>^ Quando o Senhor  tratar as feridas do seu povo e curar os ferimentos que ele mesmo causou, a lua brilhará tanto como o sol, e a luz do sol será sete vezes mais forte, como se num só dia brilhasse a luz de sete dias.

[[v23-30-27]]

^<<v23-30-27,27>>^ Atenção! O Senhor  Deus vem de longe; é ele mesmo que vem! Ele chega furioso, no meio de grossas nuvens de fumaça. Cheio de ira , ele fala; as suas palavras são como um fogo devorador.

[[v23-30-28]]

^<<v23-30-28,28>>^ O sopro do Senhor  é como uma enchente que sobe até o pescoço das pessoas. O Senhor  peneira os povos como se fossem trigo, e os joga fora como se fossem palha. Ele põe freios na sua boca e os leva por caminhos errados.

[[v23-30-29]]

^<<v23-30-29,29>>^ Mas vocês cantarão de alegria como fazem nas noites das festas sagradas; vocês ficarão felizes como os que, ao som da música de flautas, sobem o monte sagrado  para adorar o Senhor , o forte protetor de Israel.

[[v23-30-30]]

^<<v23-30-30,30>>^ A voz majestosa do Senhor  será ouvida por todos, e ele mostrará a sua ira furiosa. Haverá fogo devorador, trombas-d'água, tempestades e chuvas de pedra; e ele levantará o forte braço para castigar.

[[v23-30-31]]

^<<v23-30-31,31>>^ Os assírios ficarão apavorados ao ouvirem a voz do Senhor , ao sentirem o peso do seu castigo.

[[v23-30-32]]

^<<v23-30-32,32>>^ Ao som de tambores e de liras , o Senhor  surrará os assírios com o seu bastão; ele mesmo lutará contra eles.

[[v23-30-33]]

^<<v23-30-33,33>>^ Há muito tempo está preparada para o rei da Assíria uma fogueira em que ele será queimado. Ela está num lugar fundo e largo, e há bastante lenha para queimar. Como um rio de enxofre, o sopro do Senhor  porá fogo na lenha.

'''

xref:023-isaias/023-isaias-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaias/023-isaias-031.adoc#v23-31-0[Próximo Capítulo &#62;]