include::./index.adoc[]

[[v23-27-0]]
=== Isaías, 27
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-27-1]]

^<<v23-27-1,1>>^ Naquele dia, o Senhor  pegará a espada, a sua espada enorme, forte e pesada, e ferirá o monstro Leviatã, a serpente que se torce e se enrola; o Senhor  matará o monstro que vive no mar.

[[v23-27-2]]

^<<v23-27-2,2>>^ Naquele dia, o Senhor  dirá: "Cantem louvores à minha bela plantação de uvas !

[[v23-27-3]]

^<<v23-27-3,3>>^ Eu cuido dela e sempre a rego; eu a vigio de dia e de noite para que ninguém a estrague.

[[v23-27-4]]

^<<v23-27-4,4>>^ Não estou mais irado  com ela; se os espinheiros e o mato a ameaçarem, eu os atacarei e destruirei com fogo.

[[v23-27-5]]

^<<v23-27-5,5>>^ Se os inimigos do meu povo querem a minha proteção, então que façam as pazes comigo, sim, que façam as pazes comigo."

[[v23-27-6]]

^<<v23-27-6,6>>^ Chegará o dia em que o povo de Israel, como uma árvore viçosa, criará raízes, brotará, e florescerá, e dará frutas que encherão o mundo inteiro.

[[v23-27-7]]

^<<v23-27-7,7>>^ O Senhor  não castigou os israelitas tão duramente como castigou os inimigos deles; os israelitas que Deus matou foram poucos, mas os assassinos deles que ele matou foram muitos.

[[v23-27-8]]

^<<v23-27-8,8>>^ Ele castigou o seu povo, enviando-os como prisioneiros para outro país. Ele os expulsou com o seu sopro forte, tão forte como o vento leste.

[[v23-27-9]]

^<<v23-27-9,9>>^ Mas os pecados do povo serão perdoados, e a sua culpa será tirada. Isso acontecerá quando o povo destruir os altares pagãos e fizer as suas pedras virarem pó, como se fossem pedras de cal, e quando destruir todos os postes da deusa Aserá  e os altares de incenso.

[[v23-27-10]]

^<<v23-27-10,10>>^ A cidade protegida por muralhas está vazia; ninguém mais mora ali, e ela parece um deserto. Virou pasto para o gado, onde os animais pastam e descansam.

[[v23-27-11]]

^<<v23-27-11,11>>^ Os galhos das árvores estão secos e quebrados; as mulheres os apanham para fazer fogo. Esse povo não entende nada, e por isso Deus, o seu Criador, não terá dó nem piedade deles.

[[v23-27-12]]

^<<v23-27-12,12>>^ Naquele dia, o Senhor  Deus vai tirar o seu povo do meio de todos os outros povos, desde o rio Eufrates até a fronteira do Egito. Como o trigo é malhado e os grãos são separados da palha, assim os israelitas serão todos separados e ajuntados um por um.

[[v23-27-13]]

^<<v23-27-13,13>>^ Naquele dia, uma grande trombeta será tocada, e os israelitas que estavam perdidos na Assíria e os que tinham sido levados como prisioneiros para o Egito voltarão para a sua terra e adorarão a Deus, o Senhor , no monte sagrado  de Jerusalém.

'''

xref:023-isaias/023-isaias-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaias/023-isaias-028.adoc#v23-28-0[Próximo Capítulo &#62;]