include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-50-1]]

^<<v23-50-1,1>>^ O Senhor  Deus diz ao seu povo: "Será que vocês acham que eu os mandei embora como um homem manda embora a sua mulher ? Então onde está o documento de divórcio? Ou acham que eu os vendi como escravos a fim de pagar as minhas dívidas? Não! Vocês foram levados prisioneiros por causa dos seus pecados; eu os mandei embora por causa das suas maldades.

[[v23-50-2]]

^<<v23-50-2,2>>^ Por que é que ninguém foi me encontrar quando eu vim salvá-los? Por que ninguém respondeu quando eu chamei? Será que agora não tenho poder para salvá-los? Será que já perdi toda a minha força? Não! É só eu dar uma ordem, e o mar seca. Faço os rios virarem um deserto; assim, por falta de água, os peixes morrem de sede e começam a cheirar mal.

[[v23-50-3]]

^<<v23-50-3,3>>^ Posso cobrir de escuridão o céu, posso fazê-lo vestir roupa de luto."

[[v23-50-4]]

^<<v23-50-4,4>>^ O Senhor  Deus me ensina o que devo dizer a fim de animar os que estão cansados. Todas as manhãs, ele faz com que eu tenha vontade de ouvir com atenção o que ele vai dizer.

[[v23-50-5]]

^<<v23-50-5,5>>^ O Senhor  Deus me deu entendimento, e eu não me revoltei, nem fugi dele.

[[v23-50-6]]

^<<v23-50-6,6>>^ Ofereci as minhas costas aos que me batiam e o rosto aos que arrancavam a minha barba. Não tentei me esconder quando me xingavam e cuspiam no meu rosto.

[[v23-50-7]]

^<<v23-50-7,7>>^ Mas eu não me sinto envergonhado, pois o Senhor  Deus me ajuda. Por isso, eu fico firme como uma rocha e sei que não serei humilhado,

[[v23-50-8]]

^<<v23-50-8,8>>^ pois o meu defensor está perto. Alguém tem uma causa contra mim? Então vamos juntos ao tribunal. Alguém quer me processar? Que venha e apresente a sua acusação!

[[v23-50-9]]

^<<v23-50-9,9>>^ O Senhor  Deus é quem me defende, e por isso ninguém poderá me condenar. Todos os meus inimigos desaparecerão; serão como um vestido que as traças destruíram.

[[v23-50-10]]

^<<v23-50-10,10>>^ Escutem, vocês que temem  o Senhor e obedecem às ordens do seu servo : se o caminho em que andam é escuro, sem nenhum raio de luz, confiem no Senhor , ponham a sua esperança no seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ Mas vocês que acendem uma fogueira e se armam com flechas incendiárias, todos vocês cairão no fogo que acenderam e serão mortos pelas suas próprias flechas. O Senhor  mandará esse castigo; um sofrimento horrível os espera.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]