include::./index.adoc[]

[[v23-61-0]]
=== Isaías, 61
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-61-1]]

^<<v23-61-1,1>>^ O Senhor  Deus me deu o seu Espírito, pois ele me escolheu para levar boas notícias aos pobres. Ele me enviou para animar os aflitos, para anunciar a libertação aos escravos e a liberdade para os que estão na prisão.

[[v23-61-2]]

^<<v23-61-2,2>>^ Ele me enviou para anunciar que chegou o tempo em que o Senhor  salvará o seu povo, que chegou o dia em que o nosso Deus se vingará dos seus inimigos. Ele me enviou para consolar os que choram,

[[v23-61-3]]

^<<v23-61-3,3>>^ para dar aos que choram em Sião uma coroa de alegria, em vez de tristeza, um perfume de felicidade, em vez de lágrimas, e roupas de festa, em vez de luto. Eles farão o que é direito; serão como árvores que o Senhor  plantou para mostrar a todos a sua glória .

[[v23-61-4]]

^<<v23-61-4,4>>^ Eles reconstruirão casas que haviam caído e cidades que tinham sido arrasadas e que há muitos anos estavam em ruínas.

[[v23-61-5]]

^<<v23-61-5,5>>^ Meu povo, estrangeiros virão e cuidarão das suas ovelhas, das suas plantações e das suas parreiras .

[[v23-61-6]]

^<<v23-61-6,6>>^ E vocês serão conhecidos como sacerdotes do Senhor , como servos  do nosso Deus. As riquezas das outras nações serão de vocês, e vocês se orgulharão de serem donos dessa imensa fortuna.

[[v23-61-7]]

^<<v23-61-7,7>>^ A vergonha e a desgraça que vocês passaram eram duas vezes mais do que mereciam; mas agora vocês viverão no seu país, onde receberão o dobro de riquezas e serão felizes para sempre.

[[v23-61-8]]

^<<v23-61-8,8>>^ O Senhor  diz: "Eu amo a justiça e odeio o roubo e o crime. Serei fiel, e darei ao meu povo a sua recompensa, e farei com ele uma aliança  eterna.

[[v23-61-9]]

^<<v23-61-9,9>>^ Os seus descendentes serão famosos em todas as nações; todos os que os virem reconhecerão que eles são um povo que eu abençoei."

[[v23-61-10]]

^<<v23-61-10,10>>^ Nós nos alegraremos e cantaremos um hino de louvor por causa daquilo que o Senhor , nosso Deus, fez. Ele nos vestiu com a roupa da salvação e com a capa  da vitória. Somos como um noivo que põe um turbante  de festa na cabeça, como uma noiva enfeitada com joias.

[[v23-61-11]]

^<<v23-61-11,11>>^ Assim como a terra faz crescer as árvores, e no jardim o chão faz brotar o que foi semeado, também o Senhor  Deus fará com que brote a sua salvação. E todas as nações cantarão hinos de louvor a ele.

'''

xref:023-isaias/023-isaias-060.adoc#v23-60-0[&#60; Capítulo Anterior] | <<v23-61-0,Topo>> | xref:023-isaias/023-isaias-062.adoc#v23-62-0[Próximo Capítulo &#62;]