include::./index.adoc[]

[[v23-40-0]]
=== Isaías, 40
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-40-1]]

^<<v23-40-1,1>>^ O Senhor , nosso Deus, diz: "Consolem, consolem o meu povo.

[[v23-40-2]]

^<<v23-40-2,2>>^ Falem carinhosamente aos moradores de Jerusalém e digam-lhes que já terminou a sua escravidão e que os seus pecados foram perdoados. Eles receberam de mim duas vezes mais castigos do que os pecados que cometeram."

[[v23-40-3]]

^<<v23-40-3,3>>^ Alguém está gritando: "Preparem no deserto um caminho para o Senhor , abram ali uma estrada reta para o nosso Deus passar!

[[v23-40-4]]

^<<v23-40-4,4>>^ Todos os vales serão aterrados, e todos os morros e montes serão aplanados; os terrenos cheios de altos e baixos ficarão planos, e as regiões montanhosas virarão planícies.

[[v23-40-5]]

^<<v23-40-5,5>>^ Então o Senhor  mostrará a sua glória , e toda a humanidade a verá. O próprio Senhor  Deus prometeu que vai fazer isso."

[[v23-40-6]]

^<<v23-40-6,6>>^ Alguém diz: "Anuncie a mensagem!" "O que devo anunciar?" — eu pergunto. "Anuncie que todos os seres humanos são como a erva do campo e toda a força deles é como uma flor do mato.

[[v23-40-7]]

^<<v23-40-7,7>>^ A erva seca, e as flores caem quando o sopro do Senhor  passa por elas. De fato, o povo é como a erva.

[[v23-40-8]]

^<<v23-40-8,8>>^ A erva seca, a flor cai, mas a palavra do nosso Deus dura para sempre."

[[v23-40-9]]

^<<v23-40-9,9>>^ Você, mensageiro de boas notícias para Jerusalém, suba um alto monte; você, mensageiro de boas notícias para Sião , entregue a sua mensagem em voz alta. Fale sem medo com as cidades de Judá e anuncie bem alto: "O seu Deus está chegando!"

[[v23-40-10]]

^<<v23-40-10,10>>^ O Senhor  Deus vem vindo cheio de força; com o seu braço poderoso, ele conseguiu a vitória. E ele traz consigo o povo que ele salvou.

[[v23-40-11]]

^<<v23-40-11,11>>^ Como um pastor cuida do seu rebanho, assim o Senhor  cuidará do seu povo; ele juntará os carneirinhos, e os carregará no colo, e guiará com carinho as ovelhas que estão amamentando.

[[v23-40-12]]

^<<v23-40-12,12>>^ Quem mediu a água do mar com as conchas das mãos ou mediu o céu com os dedos? Quem, usando uma vasilha, calculou quanta terra existe no mundo inteiro ou pesou as montanhas e os morros numa balança?

[[v23-40-13]]

^<<v23-40-13,13>>^ Quem pode conhecer a mente do Senhor ? Quem é capaz de lhe dar conselhos?

[[v23-40-14]]

^<<v23-40-14,14>>^ Quem lhe deu lições ou ensinamentos? Quem lhe ensinou a julgar com justiça ou quis fazê-lo aprender mais coisas ou procurou lhe mostrar como ser sábio?

[[v23-40-15]]

^<<v23-40-15,15>>^ Para o Senhor , todas as nações do mundo são como uma gota de água num balde, como um grão de poeira na balança; ele carrega as ilhas distantes como se fossem um grão de areia.

[[v23-40-16]]

^<<v23-40-16,16>>^ Em toda a região do Líbano, não há animais suficientes para um sacrifício  como Deus merece, nem árvores que cheguem para os queimar.

[[v23-40-17]]

^<<v23-40-17,17>>^ Para ele, as nações não são nada; na presença dele, elas não têm nenhum valor.

[[v23-40-18]]

^<<v23-40-18,18>>^ Com quem Deus pode ser comparado? Com o que ele se parece?

[[v23-40-19]]

^<<v23-40-19,19>>^ Ele não é como uma imagem feita por um artista, que um ourives reveste de ouro e cobre de enfeites de prata.

[[v23-40-20]]

^<<v23-40-20,20>>^ Quem não pode comprar ouro ou prata escolhe madeira de lei e procura um artista competente que faça uma imagem que fique firme no seu lugar.

[[v23-40-21]]

^<<v23-40-21,21>>^ Será que vocês não sabem? Será que nunca ouviram falar disso? Não lhes contaram há muito tempo como o mundo foi criado?

[[v23-40-22]]

^<<v23-40-22,22>>^ O Criador de todas as coisas é aquele que se assenta no seu trono no céu; ele está tão longe da terra, que os seres humanos lhe parecem tão pequenos como formigas. Foi ele quem estendeu os céus como um véu, quem os armou como uma barraca para neles morar.

[[v23-40-23]]

^<<v23-40-23,23>>^ É ele quem rebaixa reis poderosos e tira altas autoridades do poder.

[[v23-40-24]]

^<<v23-40-24,24>>^ Eles são como plantas que brotaram há pouco e quase não têm raízes. Quando Deus sopra neles, eles murcham, e a ventania os leva para longe, como se fossem palha.

[[v23-40-25]]

^<<v23-40-25,25>>^ Com quem vocês vão comparar o Santo Deus? Quem é igual a ele?

[[v23-40-26]]

^<<v23-40-26,26>>^ Olhem para o céu e vejam as estrelas. Quem foi que as criou? Foi aquele que as faz sair em ordem como um exército; ele sabe quantas são e chama cada uma pelo seu nome. A sua força e o seu poder são tão grandes, que nenhuma delas deixa de responder.

[[v23-40-27]]

^<<v23-40-27,27>>^ Povo de Israel, por que você se queixa, dizendo: "O Senhor  não se importa conosco, o nosso Deus não se interessa pela nossa situação"?

[[v23-40-28]]

^<<v23-40-28,28>>^ Será que vocês não sabem? Será que nunca ouviram falar disso? O Senhor  é o Deus Eterno, ele criou o mundo inteiro. Ele não se cansa, não fica fatigado; ninguém pode medir a sua sabedoria.

[[v23-40-29]]

^<<v23-40-29,29>>^ Aos cansados ele dá novas forças e enche de energia os fracos.

[[v23-40-30]]

^<<v23-40-30,30>>^ Até os jovens se cansam, e os moços tropeçam e caem;

[[v23-40-31]]

^<<v23-40-31,31>>^ mas os que confiam no Senhor recebem sempre novas forças. Voam nas alturas como águias, correm e não perdem as forças, andam e não se cansam.

'''

xref:023-isaias/023-isaias-039.adoc#v23-39-0[&#60; Capítulo Anterior] | <<v23-40-0,Topo>> | xref:023-isaias/023-isaias-041.adoc#v23-41-0[Próximo Capítulo &#62;]