include::./index.adoc[]

[[v23-63-0]]
=== Isaías, 63
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-63-1]]

^<<v23-63-1,1>>^ "Quem é este que vem da cidade de Bosra, a capital de Edom? Quem é este, vestido de roupas vermelhas, luxuosas, que vem marchando forte e poderoso?" "Sou eu — diz o Senhor  — que anuncio a vitória, que sou poderoso para salvar."

[[v23-63-2]]

^<<v23-63-2,2>>^ "Mas por que é que a tua roupa está vermelha? Por que é que parece a roupa de quem pisa uvas para fazer vinho?"

[[v23-63-3]]

^<<v23-63-3,3>>^ O Senhor  responde: "Eu pisei as nações como quem pisa uvas no tanque, e não havia ninguém para me ajudar. Na minha ira  e no meu furor, eu pisei e esmaguei as nações; o seu sangue manchou a minha roupa, que ficou tingida de vermelho.

[[v23-63-4]]

^<<v23-63-4,4>>^ Eu havia resolvido que já era tempo de me vingar dos meus inimigos, que havia chegado o dia em que eu deveria salvar o meu povo.

[[v23-63-5]]

^<<v23-63-5,5>>^ Olhei, mas não havia ninguém que me ajudasse, fiquei admirado ao ver que não havia quem me apoiasse. Então consegui a vitória com o meu próprio poder, e a minha ira me encheu de força.

[[v23-63-6]]

^<<v23-63-6,6>>^ Na minha ira, pisei os povos; no meu furor, os esmaguei e derramei o seu sangue no chão."

[[v23-63-7]]

^<<v23-63-7,7>>^ Anunciarei o amor de Deus, o Senhor , e darei graças por tudo o que ele tem feito; pois o Senhor  nos abençoou ricamente, ele mostrou grande bondade para com o seu povo por causa da sua compaixão e do seu grande amor.

[[v23-63-8]]

^<<v23-63-8,8>>^ O Senhor  disse: "Eles são o meu povo, são filhos que nunca me trairão." E por isso ele os livrou

[[v23-63-9]]

^<<v23-63-9,9>>^ de todos os seus sofrimentos. Quem os salvou foi ele mesmo, e não um anjo ou qualquer outro mensageiro. Por causa do seu amor e da sua compaixão, ele os salvou. E todos os dias, ano após ano, ele os pegava e carregava no colo.

[[v23-63-10]]

^<<v23-63-10,10>>^ Mas eles se revoltaram contra Deus e ofenderam o seu santo Espírito. Por isso, Deus se tornou inimigo deles e começou a lutar contra eles.

[[v23-63-11]]

^<<v23-63-11,11>>^ Então eles lembraram do passado, lembraram de Moisés, servo  de Deus, e perguntaram: "Onde está o Senhor , que salvou do mar o seu povo, que salvou o seu rebanho e Moisés, que era o pastor? Onde está aquele que pôs o seu Espírito em Moisés,

[[v23-63-12]]

^<<v23-63-12,12>>^ que fez com que o seu grande poder estivesse sempre com ele? A fim de conquistar fama eterna, o Senhor  dividiu o mar na frente do seu povo

[[v23-63-13]]

^<<v23-63-13,13>>^ e o fez passar pelas águas profundas. Eles passaram seguros, como cavalos selvagens que não tropeçam,

[[v23-63-14]]

^<<v23-63-14,14>>^ como o gado que desce calmamente para os vales. O Espírito do Senhor  os estava levando para um lugar de descanso." Foi assim, ó Senhor , que guiaste o teu povo e conseguiste para ti mesmo um nome famoso.

[[v23-63-15]]

^<<v23-63-15,15>>^ Ó Deus, olha para nós lá do céu, lá do lugar santo e glorioso  onde moras. Onde está o teu poder e o teu cuidado por nós? Não retires de nós o teu amor e a tua compaixão,

[[v23-63-16]]

^<<v23-63-16,16>>^ pois tu és o nosso Pai. Os nossos antepassados Abraão e Jacó não se importam conosco, não fazem caso de nós. Mas tu, ó Senhor  Deus, és o nosso Pai, e desde o princípio nós te chamamos de "O nosso Salvador".

[[v23-63-17]]

^<<v23-63-17,17>>^ Ó Deus, por que fazes com que nos desviemos dos teus caminhos e tornas o nosso coração duro, para que não te temamos ? Volta para nós, ó Deus, pois somos os teus servos, somos o povo que escolheste.

[[v23-63-18]]

^<<v23-63-18,18>>^ Por um pouco de tempo, nós, o teu povo santo, fomos donos do teu Templo, mas agora ele é pisado pelos nossos inimigos.

[[v23-63-19]]

^<<v23-63-19,19>>^ Tu nos tratas como se nunca tivesses sido o nosso governador, como se nós nunca tivéssemos sido o teu povo.

'''

xref:023-isaias/023-isaias-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaias/023-isaias-064.adoc#v23-64-0[Próximo Capítulo &#62;]