include::./index.adoc[]

[[v23-53-0]]
=== Isaías, 53
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-53-1]]

^<<v23-53-1,1>>^ O povo diz: "Quem poderia crer naquilo que acabamos de ouvir? Quem diria que o Senhor  estava agindo?

[[v23-53-2]]

^<<v23-53-2,2>>^ Pois o Senhor  quis que o seu servo  aparecesse como uma plantinha que brota e vai crescendo em terra seca. Ele não era bonito nem simpático, nem tinha nenhuma beleza que chamasse a nossa atenção ou que nos agradasse.

[[v23-53-3]]

^<<v23-53-3,3>>^ Ele foi rejeitado e desprezado por todos; ele suportou dores e sofrimentos sem fim. Era como alguém que não queremos ver; nós nem mesmo olhávamos para ele e o desprezávamos.

[[v23-53-4]]

^<<v23-53-4,4>>^ "No entanto, era o nosso sofrimento que ele estava carregando, era a nossa dor que ele estava suportando. E nós pensávamos que era por causa das suas próprias culpas que Deus o estava castigando, que Deus o estava maltratando e ferindo.

[[v23-53-5]]

^<<v23-53-5,5>>^ Porém ele estava sofrendo por causa dos nossos pecados, estava sendo castigado por causa das nossas maldades. Nós somos curados pelo castigo que ele sofreu, somos sarados pelos ferimentos que ele recebeu.

[[v23-53-6]]

^<<v23-53-6,6>>^ Todos nós éramos como ovelhas que se haviam perdido; cada um de nós seguia o seu próprio caminho. Mas o Senhor  castigou o seu servo; fez com que ele sofresse o castigo que nós merecíamos.

[[v23-53-7]]

^<<v23-53-7,7>>^ "Ele foi maltratado, mas aguentou tudo humildemente e não disse uma só palavra. Ficou calado como um cordeiro que vai ser morto, como uma ovelha quando cortam a sua lã.

[[v23-53-8]]

^<<v23-53-8,8>>^ Foi preso, condenado e levado para ser morto, e ninguém se importou com o que ia acontecer com ele. Ele foi expulso do mundo dos vivos, foi morto por causa dos pecados do nosso povo.

[[v23-53-9]]

^<<v23-53-9,9>>^ Foi sepultado ao lado de criminosos, foi enterrado com os ricos, embora nunca tivesse cometido crime nenhum, nem tivesse dito uma só mentira."

[[v23-53-10]]

^<<v23-53-10,10>>^ O Senhor  Deus diz: "Eu quis maltratá-lo, quis fazê-lo sofrer. Ele ofereceu a sua vida como sacrifício  para tirar pecados e por isso terá uma vida longa e verá os seus descendentes. Ele fará com que o meu plano dê certo.

[[v23-53-11]]

^<<v23-53-11,11>>^ Depois de tanto sofrimento, ele será feliz; por causa da sua dedicação, ele ficará completamente satisfeito. O meu servo não tem pecado, mas ele sofrerá o castigo que muitos merecem, e assim os pecados deles serão perdoados.

[[v23-53-12]]

^<<v23-53-12,12>>^ Por isso, eu lhe darei um lugar de honra; ele receberá a sua recompensa junto com os grandes e os poderosos. Pois ele deu a sua própria vida e foi tratado como se fosse um criminoso. Ele levou a culpa dos pecados de muitos e orou pedindo que eles fossem perdoados."

'''

xref:023-isaias/023-isaias-052.adoc#v23-52-0[&#60; Capítulo Anterior] | <<v23-53-0,Topo>> | xref:023-isaias/023-isaias-054.adoc#v23-54-0[Próximo Capítulo &#62;]