include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-23-1]]

^<<v23-23-1,1>>^ Esta é a mensagem contra Tiro: Chorem, marinheiros que estão em alto-mar, pois a cidade de Tiro está arrasada! Não há nenhuma casa de pé, e o porto foi destruído. Vocês receberam essa notícia na ilha de Chipre.

[[v23-23-2]]

^<<v23-23-2,2>>^ Soltem gemidos de tristeza, vocês, moradores do litoral, negociantes de Sidom! Os seus viajantes atravessavam o mar,

[[v23-23-3]]

^<<v23-23-3,3>>^ navegavam nos oceanos imensos. Do rio Nilo, no Egito, vinham os cereais que vocês vendiam a todas as nações, tirando disso grandes lucros.

[[v23-23-4]]

^<<v23-23-4,4>>^ Fique envergonhada, cidade de Sidom, e você também, Tiro, fortaleza da beira do mar! Pois o mar disse : "Nunca tive dores de parto, nem dei à luz; nunca criei filhos ou filhas."

[[v23-23-5]]

^<<v23-23-5,5>>^ E o povo do Egito ficará aflito quando souber o que aconteceu com Tiro.

[[v23-23-6]]

^<<v23-23-6,6>>^ Moradores da Fenícia, chorem de dor! Fujam para a Espanha!

[[v23-23-7]]

^<<v23-23-7,7>>^ Será esta a alegre cidade de Tiro, que foi fundada há séculos? Será esta a cidade que enviou os seus filhos para fundarem colônias em regiões distantes?

[[v23-23-8]]

^<<v23-23-8,8>>^ Tiro era uma cidade importante; os seus negociantes eram como príncipes, os seus comerciantes eram respeitados no mundo inteiro. Quem foi que planejou tudo isso contra Tiro?

[[v23-23-9]]

^<<v23-23-9,9>>^ Foi o Senhor  Todo-Poderoso que fez esses planos a fim de humilhar os orgulhosos e rebaixar os mais poderosos do mundo.

[[v23-23-10]]

^<<v23-23-10,10>>^ Moradores das colônias que ficam na Espanha, cultivem as suas terras como se faz nas margens do rio Nilo. Pois o porto de vocês já não existe mais.

[[v23-23-11]]

^<<v23-23-11,11>>^ O Senhor  levantou a mão para castigar o mar; ele derrubou reinos e deu ordem para que as fortalezas da Fenícia fossem destruídas.

[[v23-23-12]]

^<<v23-23-12,12>>^ Ele disse a Sidom: "Pobre cidade, tão perseguida, pare de se divertir! Mesmo que os seus moradores fujam para Chipre, não ficarão seguros."

[[v23-23-13]]

^<<v23-23-13,13>>^ Vejam esta cidade, que agora está arrasada! Foram os babilônios, e não os assírios, que construíram rampas de ataque em volta dela, destruíram as suas fortalezas e deixaram tudo em ruínas.

[[v23-23-14]]

^<<v23-23-14,14>>^ Chorem, marinheiros que estão em alto-mar! A cidade de Tiro foi destruída, e agora vocês não têm um porto seguro.

[[v23-23-15]]

^<<v23-23-15,15>>^ Está chegando o tempo em que Tiro ficará esquecida por setenta anos, que é o tempo de vida de um rei. Mas, depois desses setenta anos, Tiro será como a prostituta daquela canção que diz assim:

[[v23-23-16]]

^<<v23-23-16,16>>^ "Ó prostituta, esquecida por todos, pegue a harpa  e dê voltas pela cidade. Toque música bonita e cante as suas canções, para que todos lembrem de novo de você."

[[v23-23-17]]

^<<v23-23-17,17>>^ Depois desses setenta anos, o Senhor  lembrará outra vez da cidade de Tiro, e ela voltará a ser prostituta, vendendo-se a todas as nações do mundo.

[[v23-23-18]]

^<<v23-23-18,18>>^ Mas o dinheiro que ela ganhar com a sua profissão será dedicado a Deus, o Senhor . Ela não poderá ficar com esse dinheiro; aqueles que adoram o Senhor  o usarão para comprar muita comida e roupas finas.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]