include::./index.adoc[]

[[v23-17-0]]
=== Isaías, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-17-1]]

^<<v23-17-1,1>>^ Esta é a mensagem contra a Síria: "Damasco não será mais uma cidade; ela vai virar um montão de ruínas.

[[v23-17-2]]

^<<v23-17-2,2>>^ As cidades da Síria ficarão abandonadas para sempre; os rebanhos irão até lá para descansar, e ninguém os espantará dali.

[[v23-17-3]]

^<<v23-17-3,3>>^ As fortalezas de Israel serão destruídas, e a Síria deixará de ser um reino. Os sírios que não forem mortos serão como o povo de Israel: eles viverão na miséria. Sou eu, o Senhor  Todo-Poderoso, quem está falando.

[[v23-17-4]]

^<<v23-17-4,4>>^ "Está chegando o dia em que Israel perderá todo o seu poder, e todas as suas riquezas acabarão.

[[v23-17-5]]

^<<v23-17-5,5>>^ Naquele dia, o país ficará parecido com um campo depois que todo o trigo foi colhido ou como o vale dos Gigantes depois de colhidas todas as espigas.

[[v23-17-6]]

^<<v23-17-6,6>>^ Mas umas poucas pessoas ficarão vivas, e Israel será como uma oliveira depois da colheita. Depois que a oliveira é sacudida, ainda fica com duas ou três azeitonas nos galhos mais altos ou umas quatro ou cinco nos galhos de baixo. Eu, o Senhor , o Deus de Israel, estou falando."

[[v23-17-7]]

^<<v23-17-7,7>>^ Naquele dia, as pessoas olharão para o seu Criador a fim de pedir ajuda; todos se voltarão para o Santo Deus de Israel.

[[v23-17-8]]

^<<v23-17-8,8>>^ Não confiarão mais nos altares que eles construíram, nem nas imagens que eles mesmos fizeram, nem nos postes da deusa Aserá , nem nos altares de queimar incenso.

[[v23-17-9]]

^<<v23-17-9,9>>^ Naquele dia, as cidades protegidas por muralhas ficarão desertas como as cidades que os heveus e os amorreus abandonaram quando os israelitas invadiram a sua terra; tudo será arrasado.

[[v23-17-10]]

^<<v23-17-10,10>>^ Povo de Israel, vocês esqueceram o seu Deus, que os salvou, e não lembram mais do seu forte protetor. Vocês plantam jardins sagrados em honra dos deuses pagãos.

[[v23-17-11]]

^<<v23-17-11,11>>^ Mas ainda que as plantas desses jardins brotem e floresçam no mesmo dia em que forem plantadas, ainda assim não haverá colheitas nos campos quando chegar o dia de sofrimento e de dor sem cura.

[[v23-17-12]]

^<<v23-17-12,12>>^ Escutem o barulho de muitas nações que se agitam e se revoltam; parece o rugido do mar, parece o estrondo de ondas violentas.

[[v23-17-13]]

^<<v23-17-13,13>>^ Os povos rugem como o mar, mas Deus os repreenderá, e eles fugirão. Serão como a palha que o vento leva pelos montes ou como o pó que a ventania espalha.

[[v23-17-14]]

^<<v23-17-14,14>>^ Ao pôr do sol, metem medo, mas de manhã já não existem mais. É isso o que vai acontecer com os nossos inimigos, que arrasam a nossa terra e levam embora todos os nossos bens.

'''

xref:023-isaias/023-isaias-016.adoc#v23-16-0[&#60; Capítulo Anterior] | <<v23-17-0,Topo>> | xref:023-isaias/023-isaias-018.adoc#v23-18-0[Próximo Capítulo &#62;]