include::./index.adoc[]

[[v23-36-0]]
=== Isaías, 36
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-36-1]]

^<<v23-36-1,1>>^ No ano catorze do reinado de Ezequias, de Judá, Senaqueribe, o rei da Assíria, atacou todas as cidades de Judá que eram protegidas por muralhas e as conquistou.

[[v23-36-2]]

^<<v23-36-2,2>>^ Depois, ele mandou que o comandante do seu exército fosse de Laquis a Jerusalém com uma enorme força militar para exigir que o rei Ezequias se entregasse. O comandante ocupou a estrada onde os tintureiros trabalham, perto do canal que traz água do açude de cima.

[[v23-36-3]]

^<<v23-36-3,3>>^ Três autoridades de Judá saíram para se encontrar com ele: o encarregado do palácio, Eliaquim, filho de Hilquias; o escrivão, Sebna; e o conselheiro do rei, Joá, filho de Asafe.

[[v23-36-4]]

^<<v23-36-4,4>>^ O oficial assírio lhes disse: — Levem para Ezequias esta mensagem do grande rei, o rei da Assíria: "Em que você está baseando a sua confiança?

[[v23-36-5]]

^<<v23-36-5,5>>^ Será que você pensa que as palavras podem tomar o lugar da experiência militar e da força? Quem você pensa que vai ajudá-lo na sua revolta contra o rei da Assíria?

[[v23-36-6]]

^<<v23-36-6,6>>^ Você está confiando na ajuda do Egito, mas isso é o mesmo que usar um caniço como bengala, isto é, ele vai quebrar e furar a sua mão. Assim é Faraó, rei do Egito, para aqueles que confiam nele.

[[v23-36-7]]

^<<v23-36-7,7>>^ Ou, por acaso, você vai me dizer que confia no Senhor , seu Deus? E não foram os santuários e os altares do Senhor  que Ezequias destruiu quando mandou que o povo de Judá e de Jerusalém adorasse num só altar?

[[v23-36-8]]

^<<v23-36-8,8>>^ Eu vou fazer um trato com você em nome do rei. Eu lhe darei dois mil cavalos se você puder arranjar homens suficientes para montá-los.

[[v23-36-9]]

^<<v23-36-9,9>>^ Você não poderia vencer nem mesmo o oficial assírio menos graduado e, no entanto, espera que os egípcios lhe mandem carros de guerra e cavalaria!

[[v23-36-10]]

^<<v23-36-10,10>>^ Você pensa que eu ataquei e destruí o seu país sem a ajuda de Deus, o Senhor ? Foi o próprio Deus quem me mandou atacá-lo e destruí-lo!"

[[v23-36-11]]

^<<v23-36-11,11>>^ Então Eliaquim, Sebna e Joá disseram ao oficial: — Senhor, fale em aramaico , por favor, pois nós entendemos. Não fale em hebraico  porque todas as pessoas que estão nas muralhas estão escutando.

[[v23-36-12]]

^<<v23-36-12,12>>^ Ele respondeu: — Vocês pensam que o rei me mandou dizer todas essas coisas somente para vocês e para o seu rei? Não! Eu estou falando também com as pessoas que estão sentadas nas muralhas e que terão de comer as suas próprias fezes e beber a sua própria urina; e vocês também vão fazer isso.

[[v23-36-13]]

^<<v23-36-13,13>>^ Então o oficial ficou de pé e gritou em hebraico: — Escutem o que o grande rei, o rei da Assíria, está dizendo a vocês!

[[v23-36-14]]

^<<v23-36-14,14>>^ Ele mandou avisar que não deixem que Ezequias os engane, pois ele não poderá salvá-los.

[[v23-36-15]]

^<<v23-36-15,15>>^ E não deixem que ele os convença a confiar no Senhor . Não pensem que Deus os salvará e não deixará que o nosso exército assírio conquiste a cidade de vocês.

[[v23-36-16]]

^<<v23-36-16,16>>^ Não deem atenção a Ezequias. O rei manda que vocês saiam da cidade e se entreguem. Vocês terão licença para comer uvas das suas próprias parreiras  e figos das suas figueiras e para beber água dos seus próprios poços,

[[v23-36-17]]

^<<v23-36-17,17>>^ até que o rei os leve para morar num país parecido com o de vocês, onde há plantações de uvas para dar vinho e onde há trigo para fazer pão.

[[v23-36-18]]

^<<v23-36-18,18>>^ Não deixem que Ezequias os engane, fazendo vocês pensarem que Deus vai salvá-los. Será que os deuses das outras nações as salvaram do rei da Assíria?

[[v23-36-19]]

^<<v23-36-19,19>>^ Onde estão agora os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim? Será que eles salvaram Samaria do meu poder?

[[v23-36-20]]

^<<v23-36-20,20>>^ Quando foi que os deuses de todos esses países os salvaram do nosso rei? O que é, então, que faz vocês pensarem que o Senhor  pode salvar Jerusalém do poder dele?

[[v23-36-21]]

^<<v23-36-21,21>>^ Mas o povo ficou calado, como o rei Ezequias havia mandado; eles não disseram nem uma só palavra.

[[v23-36-22]]

^<<v23-36-22,22>>^ Então Eliaquim, Sebna e Joá rasgaram as suas roupas em sinal de tristeza e foram contar ao rei aquilo que o oficial assírio tinha dito.

'''

xref:023-isaias/023-isaias-035.adoc#v23-35-0[&#60; Capítulo Anterior] | <<v23-36-0,Topo>> | xref:023-isaias/023-isaias-037.adoc#v23-37-0[Próximo Capítulo &#62;]