include::./index.adoc[]

[[v23-60-0]]
=== Isaías, 60
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-60-1]]

^<<v23-60-1,1>>^ Levante-se, Jerusalém! Que o seu rosto brilhe de alegria, pois já chegou a sua luz! A glória  do Senhor  está brilhando sobre você.

[[v23-60-2]]

^<<v23-60-2,2>>^ A terra está coberta de escuridão, os povos vivem nas trevas, mas a luz do Senhor  está brilhando sobre você; sobre você aparece a glória de Deus.

[[v23-60-3]]

^<<v23-60-3,3>>^ Atraídos pela sua luz, Jerusalém, os povos do mundo virão; o brilho do seu novo dia fará com que os reis cheguem até você.

[[v23-60-4]]

^<<v23-60-4,4>>^ Jerusalém, olhe em redor e veja o que está acontecendo! Os seus filhos estão voltando, eles estão chegando! Os seus filhos vêm de longe, as suas filhas vêm nos braços das mães.

[[v23-60-5]]

^<<v23-60-5,5>>^ Quando você vir isso, ficará radiante de alegria; cheio de emoção, o seu coração baterá forte. Os povos que vivem no outro lado do mar virão, trazendo todas as suas riquezas para você.

[[v23-60-6]]

^<<v23-60-6,6>>^ Os povos de Midiã e de Efa chegarão com enormes caravanas  de camelos; virá também o povo de Sabá, trazendo ouro e incenso. Todos eles anunciarão as grandes coisas que o Senhor  fez.

[[v23-60-7]]

^<<v23-60-7,7>>^ De Quedar e de Nebaiote, virão carneiros que serão oferecidos no altar de Deus como sacrifícios  que agradam a ele. O Senhor  fará com que o seu lindo Templo seja mais belo ainda.

[[v23-60-8]]

^<<v23-60-8,8>>^ Que navios são esses que vêm deslizando como nuvens, como pombas voltando ao pombal?

[[v23-60-9]]

^<<v23-60-9,9>>^ São navios que vêm de longe; os maiores vêm na frente, trazendo o povo de Deus de volta para o seu país. Trazem também prata e ouro para oferecer ao Senhor , o Santo Deus de Israel, que deu a vocês, o seu povo, muita glória.

[[v23-60-10]]

^<<v23-60-10,10>>^ O Senhor  diz a Jerusalém: "Estrangeiros reconstruirão as suas muralhas, e os reis deles trabalharão para você. Eu estava irado  e por isso a castiguei, mas eu a amo e tenho compaixão de você.

[[v23-60-11]]

^<<v23-60-11,11>>^ Os seus portões ficarão sempre abertos, não serão fechados nem de dia nem de noite, para que as nações, guiadas pelos seus reis, tragam as suas riquezas para você.

[[v23-60-12]]

^<<v23-60-12,12>>^ As nações que não a servirem serão destruídas; elas serão completamente arrasadas.

[[v23-60-13]]

^<<v23-60-13,13>>^ "Cipreste, pinheiro e zimbro, que são as melhores madeiras do Líbano, serão trazidos para você a fim de tornarem ainda mais belo o meu Templo, o estrado onde descanso os meus pés.

[[v23-60-14]]

^<<v23-60-14,14>>^ Também virão os filhos dos reis que a exploraram e maltrataram e se ajoelharão em frente de você; todos os que a desprezaram virão até você e encostarão o rosto no chão. Você será chamada de ‘Cidade do Senhor ’, a ‘ Sião  do Santo Deus de Israel’.

[[v23-60-15]]

^<<v23-60-15,15>>^ "Nunca mais você será odiada, nunca mais será uma cidade abandonada, sem moradores; eu farei com que você seja bela e poderosa, com que seja para sempre uma cidade alegre.

[[v23-60-16]]

^<<v23-60-16,16>>^ Nações e reis estrangeiros cuidarão de você, como a mãe que dá de mamar ao filho. Então você ficará sabendo que eu, o Senhor , sou o seu Salvador, que eu, o Poderoso Deus de Israel, sou o seu Redentor.

[[v23-60-17]]

^<<v23-60-17,17>>^ "Em vez de bronze, eu trarei ouro para você, e prata, em vez de ferro; trarei bronze e ferro, em vez de madeira e pedras. Farei com que a paz seja o seu rei e com que a justiça a governe.

[[v23-60-18]]

^<<v23-60-18,18>>^ Nunca mais haverá violência na sua terra; o seu país não será destruído e arrasado novamente; você chamará as suas muralhas de ‘Salvação’ e os seus portões de ‘Louvor a Deus’.

[[v23-60-19]]

^<<v23-60-19,19>>^ "Nunca mais o sol a iluminará de dia, nem a lua, de noite; pois eu, o Senhor , serei para sempre a sua luz, e a minha glória brilhará sobre você.

[[v23-60-20]]

^<<v23-60-20,20>>^ Eu serei o seu sol e a sua lua, um sol que nunca se põe, uma lua que não para de brilhar. A minha luz brilhará sobre você para sempre, e os seus dias de luto chegarão ao fim.

[[v23-60-21]]

^<<v23-60-21,21>>^ O seu povo fará o que é direito e para sempre será dono da Terra Prometida . Eles são a planta que eu plantei; com as minhas próprias mãos, eu os fiz para que eles mostrem a todos a minha grandeza.

[[v23-60-22]]

^<<v23-60-22,22>>^ Este punhado de gente será um povo numeroso; esta nação, tão pequena, será a mais poderosa de todas. Eu sou o Senhor e logo, no tempo certo, farei com que isso aconteça."

'''

xref:023-isaias/023-isaias-059.adoc#v23-59-0[&#60; Capítulo Anterior] | <<v23-60-0,Topo>> | xref:023-isaias/023-isaias-061.adoc#v23-61-0[Próximo Capítulo &#62;]