include::./index.adoc[]

[[v23-62-0]]
=== Isaías, 62
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-62-1]]

^<<v23-62-1,1>>^ Eu amo Sião  e por isso não me calarei; não descansarei até que a sua vitória brilhe como o sol, e a sua salvação brilhe como uma tocha acesa.

[[v23-62-2]]

^<<v23-62-2,2>>^ Jerusalém, todas as nações verão a sua vitória, todos os reis ficarão admirados com a sua beleza. Você terá um novo nome, um nome que o Senhor  lhe dará.

[[v23-62-3]]

^<<v23-62-3,3>>^ Você será como uma bela coroa que pertence ao Senhor , seu Deus.

[[v23-62-4]]

^<<v23-62-4,4>>^ Nunca mais a chamarão de "Abandonada", e a sua terra não será mais chamada de "Arrasada". Você será chamada de "Minha querida", e a sua terra, de "Minha esposa". Pois o Senhor  está contente com você, e a sua terra será a esposa dele.

[[v23-62-5]]

^<<v23-62-5,5>>^ Assim como um moço casa com a sua noiva, também aquele que a construiu casará com você; assim como o noivo fica feliz com a noiva, também o seu Deus se alegrará com você.

[[v23-62-6]]

^<<v23-62-6,6>>^ Nas muralhas de Jerusalém, o Senhor  colocou vigias, que não deverão ficar calados nem de dia nem de noite. Vocês, vigias, que fazem com que Deus lembre das suas promessas, não descansem,

[[v23-62-7]]

^<<v23-62-7,7>>^ nem deixem que ele descanse até que tenha reconstruído Jerusalém, fazendo dela uma cidade elogiada no mundo inteiro.

[[v23-62-8]]

^<<v23-62-8,8>>^ Com o seu forte braço direito levantado, o Senhor  fez ao seu povo este juramento: "Nunca mais deixarei que o seu trigo seja comido pelos seus inimigos, nem permitirei que o seu vinho, que vocês fizeram com tanto trabalho, seja bebido por estrangeiros.

[[v23-62-9]]

^<<v23-62-9,9>>^ Vocês mesmos colherão o seu trigo, comerão o pão e louvarão a mim, o Senhor . Vocês mesmos colherão as suas uvas e beberão o vinho nos pátios do meu Templo."

[[v23-62-10]]

^<<v23-62-10,10>>^ Moradores de Jerusalém, saiam da cidade e preparem o caminho para o seu povo que está voltando. Aplanem a estrada, tirem todas as pedras e levantem uma bandeira como sinal para que todos os povos saibam o que está acontecendo.

[[v23-62-11]]

^<<v23-62-11,11>>^ Pelo mundo inteiro, o Senhor  anunciou esta mensagem: "Digam ao povo de Jerusalém que o seu Salvador está chegando. Ele traz consigo o povo que ele salvou."

[[v23-62-12]]

^<<v23-62-12,12>>^ Vocês serão chamados de "Povo Santo", o "Povo que o Senhor  Salvou". Jerusalém será chamada de "Aquela que Deus Ama", "Cidade que Deus não Abandonou".

'''

xref:023-isaias/023-isaias-061.adoc#v23-61-0[&#60; Capítulo Anterior] | <<v23-62-0,Topo>> | xref:023-isaias/023-isaias-063.adoc#v23-63-0[Próximo Capítulo &#62;]