include::./index.adoc[]

[[v23-7-0]]
=== Isaías, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-7-1]]

^<<v23-7-1,1>>^ No tempo em que Acaz, filho de Jotão e neto de Uzias, era rei de Judá, Rezim, rei da Síria, e Peca, filho de Remalias, rei de Israel, atacaram a cidade de Jerusalém, mas não puderam conquistá-la.

[[v23-7-2]]

^<<v23-7-2,2>>^ Quando o rei Acaz soube que os sírios haviam feito um acordo  com os israelitas, ele e todo o seu povo ficaram com tanto medo, que tremiam como varas verdes.

[[v23-7-3]]

^<<v23-7-3,3>>^ O Senhor  Deus disse a Isaías: — Vá com o seu filho Sear-Jasube encontrar-se com o rei Acaz. Ele estará na estrada onde os tintureiros trabalham, perto do canal que traz água do açude de cima.

[[v23-7-4]]

^<<v23-7-4,4>>^ Diga ao rei que fique alerta, mas que não perca a calma; que não tenha medo, nem fique desanimado por causa do ódio do rei Rezim, dos sírios e do rei Peca. Eles são menos perigosos do que dois tições soltando fumaça.

[[v23-7-5]]

^<<v23-7-5,5>>^ Os sírios, junto com o rei Peca e os israelitas, estão fazendo planos para prejudicar o rei Acaz. Eles combinaram o seguinte:

[[v23-7-6]]

^<<v23-7-6,6>>^ "Vamos atacar o Reino de Judá, conquistar o seu povo e forçá-lo a aceitar o filho de Tabeal como rei."

[[v23-7-7]]

^<<v23-7-7,7>>^ — Porém eu, o Senhor , afirmo que isso não acontecerá.

[[v23-7-8]]

^<<v23-7-8,8>>^ Pois a Síria não é mais forte do que Damasco, a sua capital, e Damasco não é mais forte do que o rei Rezim. A terra de Israel não é mais forte do que Samaria, a sua capital, e Samaria não é mais forte do que o rei Peca. Mas daqui a sessenta e cinco anos Israel será destruído e deixará de existir como nação. — Se vocês não tiverem uma fé firme, não poderão ficar firmes.

[[v23-7-9]]

^<<v23-7-9,9>>^ Pois a Síria não é mais forte do que Damasco, a sua capital, e Damasco não é mais forte do que o rei Rezim. A terra de Israel não é mais forte do que Samaria, a sua capital, e Samaria não é mais forte do que o rei Peca. Mas daqui a sessenta e cinco anos Israel será destruído e deixará de existir como nação.

[[v23-7-10]]

^<<v23-7-10,10>>^ O Senhor  Deus enviou ao rei Acaz esta outra mensagem:

[[v23-7-11]]

^<<v23-7-11,11>>^ — Peça ao Senhor , seu Deus, que lhe dê um sinal. Esse sinal poderá vir das profundezas do mundo dos mortos  ou das alturas do céu.

[[v23-7-12]]

^<<v23-7-12,12>>^ Mas Acaz respondeu: — Não vou pedir sinal nenhum. Não vou pôr o Senhor  à prova.

[[v23-7-13]]

^<<v23-7-13,13>>^ Então Isaías disse: — Escutem, descendentes do rei Davi! Será que não basta vocês abusarem da paciência das pessoas? Precisam abusar também da paciência do meu Deus?

[[v23-7-14]]

^<<v23-7-14,14>>^ Pois o Senhor mesmo lhes dará um sinal: a jovem que está grávida dará à luz um filho e porá nele o nome de Emanuel .

[[v23-7-15]]

^<<v23-7-15,15>>^ Quando ele chegar à idade de saber escolher o bem e rejeitar o mal, o povo estará comendo coalhada e mel .

[[v23-7-16]]

^<<v23-7-16,16>>^ Mas, mesmo antes desse tempo, ó rei Acaz, as terras daqueles dois reis que lhe causaram tanto medo ficarão completamente abandonadas.

[[v23-7-17]]

^<<v23-7-17,17>>^ — O Senhor  Deus vai trazer sofrimento para o senhor, ó rei, para as pessoas da sua família e para o seu povo. Ele fará isso por meio do rei da Assíria, e o sofrimento que esse rei vai causar será o pior que já houve desde que o Reino de Israel se separou do Reino de Judá.

[[v23-7-18]]

^<<v23-7-18,18>>^ Quando chegar aquele dia, o Senhor  Deus vai assobiar e chamar os egípcios para que venham, como se fossem moscas, dos lugares mais distantes do rio Nilo. E assobiará também para que os assírios, como um enxame de abelhas, venham da sua terra.

[[v23-7-19]]

^<<v23-7-19,19>>^ Eles virão e, como enxames, pousarão nos vales mais profundos, nas fendas das rochas, e em todos os espinheiros e em todos os lugares onde o gado bebe água.

[[v23-7-20]]

^<<v23-7-20,20>>^ — Naquele dia, o Senhor vai contratar um barbeiro que vive na região que fica no outro lado do rio Eufrates, isto é, o rei da Assíria. Ele virá e rapará a barba, os cabelos e os pelos do corpo de todos .

[[v23-7-21]]

^<<v23-7-21,21>>^ — Naquele dia, quem ficar com uma vaca nova e duas cabras

[[v23-7-22]]

^<<v23-7-22,22>>^ terá tanto leite, que poderá comer coalhada. E todos os que ficarem com vida no país comerão coalhada e mel.

[[v23-7-23]]

^<<v23-7-23,23>>^ — Naquele dia, o que antes era uma plantação com mil pés de uva, valendo mil barras de prata, virará um terreno cheio de mato e de espinheiros.

[[v23-7-24]]

^<<v23-7-24,24>>^ O país todo ficará coberto de espinheiros, e os homens irão ali caçar com arco e flechas.

'''

xref:023-isaias/023-isaias-006.adoc#v23-6-0[&#60; Capítulo Anterior] | <<v23-7-0,Topo>> | xref:023-isaias/023-isaias-008.adoc#v23-8-0[Próximo Capítulo &#62;]