include::./index.adoc[]

[[v23-22-0]]
=== Isaías, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-22-1]]

^<<v23-22-1,1>>^ Esta é a mensagem a respeito do vale da Visão: Por que é que vocês estão nos terraços,

[[v23-22-2]]

^<<v23-22-2,2>>^ gritando e festejando? Por que a cidade está toda alvoroçada e alegre? Os soldados de Jerusalém que morreram nesta guerra não foram mortos em batalha.

[[v23-22-3]]

^<<v23-22-3,3>>^ Todos os seus oficiais fugiram e foram presos antes de terem atirado uma só flecha. Até os que fugiram para muito longe também foram presos.

[[v23-22-4]]

^<<v23-22-4,4>>^ Por isso, eu disse: "Vão embora; deixem-me chorar amargamente. Não tentem me consolar por causa da desgraça do meu povo."

[[v23-22-5]]

^<<v23-22-5,5>>^ Pois o Senhor , o Deus Todo-Poderoso, nos enviou aquele dia, um dia de terror, de confusão e de derrota no vale da Visão. As muralhas da cidade foram derrubadas, e os gritos dos seus moradores foram ouvidos nas montanhas.

[[v23-22-6]]

^<<v23-22-6,6>>^ Nos seus cavalos e carros de guerra, e armados com arcos e flechas, os soldados do país de Elão vieram nos atacar. Os soldados de Quir também vieram com os seus escudos .

[[v23-22-7]]

^<<v23-22-7,7>>^ Os vales de Judá estavam cheios de carros de guerra; a cavalaria dos inimigos estava em frente dos portões de Jerusalém.

[[v23-22-8]]

^<<v23-22-8,8>>^ Judá não tinha nenhum meio de se defender. Naquele dia, vocês foram buscar as armas que estavam guardadas no Salão da Floresta ,

[[v23-22-9]]

^<<v23-22-9,9>>^ examinaram as muralhas para marcar os lugares onde havia brechas e encheram de água o açude que ficava dentro da cidade.

[[v23-22-10]]

^<<v23-22-10,10>>^ Examinaram as casas de Jerusalém e derrubaram algumas delas a fim de usar as pedras na reconstrução das muralhas.

[[v23-22-11]]

^<<v23-22-11,11>>^ Entre as duas muralhas, vocês construíram um reservatório para guardar a água que vinha do açude velho. Porém vocês não deram atenção a Deus, que há muito tempo já havia planejado todas essas coisas; não confiaram naquele que fez tudo isso acontecer.

[[v23-22-12]]

^<<v23-22-12,12>>^ O Senhor , o Deus Todo-Poderoso, os estava convidando a chorar e se lamentar, a rapar os cabelos e vestir roupas feitas de pano grosseiro em sinal de tristeza.

[[v23-22-13]]

^<<v23-22-13,13>>^ Em vez disso, vocês se divertiram e festejaram, mataram touros e ovelhas, comeram e beberam vinho à vontade. Vocês diziam: "Comamos e bebamos porque amanhã morreremos."

[[v23-22-14]]

^<<v23-22-14,14>>^ O Senhor  Todo-Poderoso se revelou a mim e me disse: — Não perdoarei essa maldade que eles fizeram; todos morrerão sem serem perdoados. Eu, o Senhor , o Deus Todo-Poderoso, falei.

[[v23-22-15]]

^<<v23-22-15,15>>^ O Senhor , o Deus Todo-Poderoso, ordenou que eu fosse falar com Sebna, o administrador do palácio do rei, e lhe dissesse o seguinte:

[[v23-22-16]]

^<<v23-22-16,16>>^ — O que é que você está fazendo? Quem disse que você tinha o direito de cavar a sua sepultura na rocha, no lugar mais alto do monte?

[[v23-22-17]]

^<<v23-22-17,17>>^ Você é poderoso, mas o Senhor  vai agarrá-lo e, com toda a força, vai jogá-lo longe.

[[v23-22-18]]

^<<v23-22-18,18>>^ Ele vai pegá-lo como quem pega uma bola e vai jogá-lo longe, num país enorme. Ali você morrerá perto dos seus carros de guerra, que o enchiam de tanto orgulho. Pois você é uma vergonha para o seu patrão, o rei de Judá.

[[v23-22-19]]

^<<v23-22-19,19>>^ O Senhor  Deus disse a Sebna: — Eu vou tirar você da sua alta posição e vou rebaixá-lo.

[[v23-22-20]]

^<<v23-22-20,20>>^ Então chamarei o meu servo  Eliaquim, filho de Hilquias;

[[v23-22-21]]

^<<v23-22-21,21>>^ eu o vestirei com a roupa de administrador, e lhe darei o cinto que você usava, e passarei para ele toda a autoridade que você tinha. Eliaquim será como um pai para os moradores de Jerusalém e para o povo de Judá.

[[v23-22-22]]

^<<v23-22-22,22>>^ Darei a ele as chaves do cargo que ele ocupará como o homem mais poderoso do país, logo abaixo do rei. O que ele abrir ninguém fechará, e o que ele fechar ninguém abrirá.

[[v23-22-23]]

^<<v23-22-23,23>>^ Eu o firmarei no seu lugar, como uma estaca que foi fincada firmemente no chão, e toda a sua família se sentirá honrada por causa dele.

[[v23-22-24]]

^<<v23-22-24,24>>^ Mas os seus parentes, desde os mais importantes até os mais humildes, vão se tornar uma carga pesada para ele, pois viverão às suas custas. Eles serão como canecas, vasos e jarros pendurados numa estaca.

[[v23-22-25]]

^<<v23-22-25,25>>^ E assim como a estaca quebra com todo esse peso, assim Eliaquim perderá a sua posição, e todos os seus parentes ficarão sem recursos. Eu, o Senhor  Todo-Poderoso, falei.

'''

xref:023-isaias/023-isaias-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaias/023-isaias-023.adoc#v23-23-0[Próximo Capítulo &#62;]