include::./index.adoc[]

[[v23-43-0]]
=== Isaías, 43
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-43-1]]

^<<v23-43-1,1>>^ Mas agora, povo de Israel, o Senhor  Deus, que o criou, diz: "Não tenha medo, pois eu o salvarei; eu o chamei pelo seu nome, e você é meu.

[[v23-43-2]]

^<<v23-43-2,2>>^ Quando você atravessar águas profundas, eu estarei ao seu lado, e você não se afogará. Quando passar pelo meio do fogo, as chamas não o queimarão.

[[v23-43-3]]

^<<v23-43-3,3>>^ Pois eu sou o Senhor , seu Deus, o Santo Deus de Israel, o seu Salvador. Dei como pagamento o Egito, a Etiópia e Seba a fim de que você fosse meu.

[[v23-43-4]]

^<<v23-43-4,4>>^ Para libertar você, entrego nações inteiras como o preço do resgate, pois para mim você vale muito. Você é o povo que eu amo, um povo que merece muita honra.

[[v23-43-5]]

^<<v23-43-5,5>>^ Não tenha medo, pois eu estou com você. "Do Leste e do Oeste levarei o meu povo de volta para o seu país.

[[v23-43-6]]

^<<v23-43-6,6>>^ Ordenarei ao Norte que os deixe sair e direi ao Sul que não os segure. Dos lugares mais distantes do mundo deixem que os meus filhos e as minhas filhas voltem para casa!

[[v23-43-7]]

^<<v23-43-7,7>>^ Todos eles são o meu próprio povo; eu os criei e lhes dei vida a fim de que mostrem a minha grandeza."

[[v23-43-8]]

^<<v23-43-8,8>>^ O Senhor  Deus diz: "Tragam o meu povo para ser julgado. Eles têm olhos, mas não veem, têm ouvidos, mas não ouvem.

[[v23-43-9]]

^<<v23-43-9,9>>^ Reúnam-se no tribunal, todas as nações, ajuntem-se, todos os povos. Por acaso, um dos seus deuses anunciou o que ia acontecer? Algum deles disse o que está acontecendo agora? Que eles tragam as suas testemunhas e provem que estão certos, a fim de que todos digam: ‘É verdade mesmo!’ "

[[v23-43-10]]

^<<v23-43-10,10>>^ O Senhor  diz: "Povo de Israel, você é a minha testemunha; você é o servo  que eu escolhi para que me conheça, e creia em mim, e entenda que eu sou o único Deus. Antes de mim, não houve nenhum outro deus e nunca haverá outro depois.

[[v23-43-11]]

^<<v23-43-11,11>>^ Eu, só eu, sou o Senhor , somente eu posso salvar vocês.

[[v23-43-12]]

^<<v23-43-12,12>>^ Fui eu quem prometeu salvá-los e, de fato, foi isso que fiz. E vocês são testemunhas de que não foi outro deus que fez isso.

[[v23-43-13]]

^<<v23-43-13,13>>^ Eu sou Deus e sempre serei. Ninguém pode escapar do meu poder e ninguém pode desfazer o que eu faço."

[[v23-43-14]]

^<<v23-43-14,14>>^ O Senhor , o Santo Deus de Israel, o Deus que salva, diz ao seu povo: "Por causa do meu amor por vocês, enviarei contra a Babilônia um exército que conquistará a cidade, e os gritos de alegria dos babilônios virarão choro.

[[v23-43-15]]

^<<v23-43-15,15>>^ Eu sou o Senhor , o Santo Deus de vocês, o Criador de Israel e o seu Rei."

[[v23-43-16]]

^<<v23-43-16,16>>^ Há muito tempo, o Senhor  abriu um caminho no mar, uma estrada no meio das águas perigosas.

[[v23-43-17]]

^<<v23-43-17,17>>^ Ele derrotou um poderoso exército, um exército de carros e cavalos de guerra. Eles caíram para nunca mais se levantar; acabaram-se como um pavio que está se apagando.

[[v23-43-18]]

^<<v23-43-18,18>>^ Mas agora o Senhor  Deus diz ao seu povo: "Não fiquem lembrando do que aconteceu no passado, não continuem pensando nas coisas que fiz há muito tempo.

[[v23-43-19]]

^<<v23-43-19,19>>^ Pois agora vou fazer uma coisa nova, que logo vai acontecer, e, de repente, vocês a verão. Prepararei um caminho no deserto e farei com que estradas passem em terras secas.

[[v23-43-20]]

^<<v23-43-20,20>>^ Serei louvado pelos animais selvagens, pelos chacais e pelos avestruzes. Pois farei com que jorrem fontes no deserto e com que rios corram pelas terras secas, para dar de beber ao meu povo escolhido.

[[v23-43-21]]

^<<v23-43-21,21>>^ Este é o povo que criei para que fosse meu a fim de que desse louvores ao meu nome."

[[v23-43-22]]

^<<v23-43-22,22>>^ O Senhor  diz ao seu povo: "Vocês se enjoaram de mim e pararam de me adorar.

[[v23-43-23]]

^<<v23-43-23,23>>^ Vocês não me ofereceram carneiros para serem queimados em sacrifício , nem me honraram com outros sacrifícios. Eu não os obriguei a me apresentarem ofertas de cereais, nem fiquei exigindo que me oferecessem incenso.

[[v23-43-24]]

^<<v23-43-24,24>>^ Vocês não foram obrigados a comprar plantas cheirosas para apresentá-las a mim, nem tiveram de me oferecer a gordura dos animais para me agradar. Pelo contrário, vocês me cansaram com os seus pecados e me aborreceram com as suas maldades.

[[v23-43-25]]

^<<v23-43-25,25>>^ "Mas eu — eu mesmo — sou o seu Deus e por isso perdoo os seus pecados e os esqueço.

[[v23-43-26]]

^<<v23-43-26,26>>^ Meu povo, se você tem uma causa contra mim, vamos juntos ao tribunal! Apresente as suas provas, e veremos se você tem razão.

[[v23-43-27]]

^<<v23-43-27,27>>^ O pai da sua raça pecou; os seus profetas  também pecaram contra mim,

[[v23-43-28]]

^<<v23-43-28,28>>^ e as suas autoridades profanaram  o meu Templo. Por isso, eu deixei que Israel fosse destruído, deixei que o meu próprio povo fosse humilhado."

'''

xref:023-isaias/023-isaias-042.adoc#v23-42-0[&#60; Capítulo Anterior] | <<v23-43-0,Topo>> | xref:023-isaias/023-isaias-044.adoc#v23-44-0[Próximo Capítulo &#62;]