include::./index.adoc[]

[[v23-48-0]]
=== Isaías, 48
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-48-1]]

^<<v23-48-1,1>>^ Povo de Israel, escute! Escutem, descendentes de Judá! Vocês juram pelo nome do Senhor e dizem que adoram ao Deus de Israel, mas nisso não são honestos nem sinceros.

[[v23-48-2]]

^<<v23-48-2,2>>^ Vocês dizem que são moradores da cidade santa e que confiam no Deus de Israel, naquele que se chama Senhor  Todo-Poderoso.

[[v23-48-3]]

^<<v23-48-3,3>>^ O Senhor  diz a vocês: "Há muito tempo, eu falei de coisas do futuro, disse claramente o que ia acontecer. De repente, agi, e tudo aconteceu como eu tinha dito.

[[v23-48-4]]

^<<v23-48-4,4>>^ Eu sabia que vocês são teimosos, que são duros como o ferro ou o bronze.

[[v23-48-5]]

^<<v23-48-5,5>>^ Por isso, falei dessas coisas há muito tempo; antes que elas acontecessem, eu as havia anunciado a vocês. Portanto, vocês não podem dizer que foram as suas imagens e os seus ídolos que fizeram essas coisas acontecerem.

[[v23-48-6]]

^<<v23-48-6,6>>^ "Tudo aconteceu como eu tinha dito, e vocês precisam reconhecer que falei a verdade. Mas agora vou falar de coisas novas, de coisas secretas, que vocês ainda não conhecem.

[[v23-48-7]]

^<<v23-48-7,7>>^ Só agora é que vou fazer com que aconteçam; vocês nunca tinham ouvido falar nelas e assim não podem dizer que já as conheciam.

[[v23-48-8]]

^<<v23-48-8,8>>^ Eu sabia que não podia confiar em vocês; sabia muito bem que sempre foram rebeldes. Por isso, vocês não tinham ouvido essas coisas, não sabiam que elas iam acontecer.

[[v23-48-9]]

^<<v23-48-9,9>>^ "Eu poderia ter descarregado a minha ira  sobre vocês e os poderia ter destruído completamente, mas isso teria trazido desonra para o meu nome. Portanto, tive paciência com vocês, pois eu sou Deus e mereço que me louvem.

[[v23-48-10]]

^<<v23-48-10,10>>^ Eu os fiz sofrer, mas foi para purificá-los, como a prata é purificada na fornalha.

[[v23-48-11]]

^<<v23-48-11,11>>^ É por amor ao meu próprio nome que vou agir; não permito que o meu nome seja profanado . Não deixo que nenhum outro deus receba o louvor que somente eu mereço."

[[v23-48-12]]

^<<v23-48-12,12>>^ O Senhor  Deus diz: "Escute, povo de Israel, o povo que eu escolhi! Eu, o Senhor , sou o único Deus: sou o primeiro e o último.

[[v23-48-13]]

^<<v23-48-13,13>>^ Com as minhas mãos, coloquei a terra no seu lugar e estendi o céu. Dei uma ordem, e eles começaram a existir.

[[v23-48-14]]

^<<v23-48-14,14>>^ "Reúnam-se todos e escutem! Nenhum dos deuses anunciou que ia acontecer isto: o homem que eu, o Senhor , amo fará o que eu quero e com o meu poder atacará a Babilônia.

[[v23-48-15]]

^<<v23-48-15,15>>^ Fui eu mesmo quem o chamou; dei a ordem, e ele veio. Eu farei com que tudo o que ele fizer dê certo.

[[v23-48-16]]

^<<v23-48-16,16>>^ Agora, venham cá e escutem o que estou dizendo: desde o princípio, nunca falei em segredo e tenho governado todas as coisas desde que começaram." Agora, o Senhor  Deus me deu o seu Espírito e me enviou .

[[v23-48-17]]

^<<v23-48-17,17>>^ O Senhor , o Santo Deus de Israel, o seu Salvador, diz ao seu povo: "Eu sou o Senhor , seu Deus. Eu os ensino para o seu próprio bem e os guio no caminho que devem seguir.

[[v23-48-18]]

^<<v23-48-18,18>>^ Ah! Se vocês tivessem obedecido aos meus mandamentos! A sua prosperidade iria aumentando como se fosse uma enchente, e as suas vitórias teriam sido constantes, tão constantes como as ondas do mar.

[[v23-48-19]]

^<<v23-48-19,19>>^ Os seus descendentes seriam tantos como os grãos de areia da praia do mar; eu nunca os esqueceria, e eles estariam sempre na minha presença."

[[v23-48-20]]

^<<v23-48-20,20>>^ Saiam da Babilônia, fujam de lá! Com gritos de alegria, anunciem esta boa notícia ao mundo inteiro: "O Senhor  salvou o seu servo , o povo de Israel!"

[[v23-48-21]]

^<<v23-48-21,21>>^ Quando Deus guiou o seu povo pelo deserto, ninguém ficou com sede; ele fez com que corresse água da rocha, ele partiu a rocha, e a água jorrou.

[[v23-48-22]]

^<<v23-48-22,22>>^ Mas o Senhor  diz aos que praticam o mal: "Para vocês não há segurança."

'''

xref:023-isaias/023-isaias-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaias/023-isaias-049.adoc#v23-49-0[Próximo Capítulo &#62;]