include::./index.adoc[]

[[v23-41-0]]
=== Isaías, 41
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-41-1]]

^<<v23-41-1,1>>^ O Senhor  Deus diz: "Povos das nações distantes, calem-se e escutem! Renovem as suas forças e venham prontos para defender a sua causa. Vamos nos reunir para resolver com quem está a razão.

[[v23-41-2]]

^<<v23-41-2,2>>^ "Quem foi que trouxe do Oriente esse rei que sempre sai vitorioso? Quem fez com que ele derrotasse as nações e com que reis fossem vencidos por ele? Com a sua espada e as suas flechas, ele os faz virar pó e faz com que fujam como se fossem a palha que é levada pelo vento.

[[v23-41-3]]

^<<v23-41-3,3>>^ Ele os persegue e avança seguro; ele anda tão depressa, que os seus pés quase não tocam no chão.

[[v23-41-4]]

^<<v23-41-4,4>>^ Quem planejou isso e fez com que tudo acontecesse? Quem resolveu o que se passaria no mundo desde o princípio? Fui eu, o Senhor , que estava lá quando tudo começou e que lá estarei quando tudo terminar."

[[v23-41-5]]

^<<v23-41-5,5>>^ As nações distantes viram o que aconteceu, e todos os povos tremeram de medo. Então se juntaram e vieram.

[[v23-41-6]]

^<<v23-41-6,6>>^ Os que fazem imagens se ajudam uns aos outros, cada um procura animar o seu companheiro.

[[v23-41-7]]

^<<v23-41-7,7>>^ O escultor anima o ourives; aquele que bate o ferro com o martelo elogia o que solda o ídolo. E diz: "Que trabalho bem-feito!" E com pregos fixam a imagem no lugar para que não caia.

[[v23-41-8]]

^<<v23-41-8,8>>^ O Senhor  diz ao povo de Israel: "Você é o meu servo , o povo que eu escolhi; vocês são descendentes de Abraão, meu amigo.

[[v23-41-9]]

^<<v23-41-9,9>>^ Eu os trouxe dos fins da terra, dos lugares mais distantes do mundo, e lhes disse: ‘Vocês são os meus servos.’ Eu os escolhi e nunca os rejeitei.

[[v23-41-10]]

^<<v23-41-10,10>>^ Não fiquem com medo, pois estou com vocês; não se apavorem, pois eu sou o seu Deus. Eu lhes dou forças e os ajudo; eu os protejo com a minha forte mão.

[[v23-41-11]]

^<<v23-41-11,11>>^ "Todos os seus inimigos serão derrotados e humilhados; todos os que lutam contra vocês serão destruídos e morrerão.

[[v23-41-12]]

^<<v23-41-12,12>>^ Se vocês procurarem os seus inimigos, não os acharão, pois todos eles terão desaparecido.

[[v23-41-13]]

^<<v23-41-13,13>>^ Eu sou o Senhor , o Deus de vocês; eu os seguro pela mão e lhes digo: ‘Não fiquem com medo, pois eu os ajudo.’ "

[[v23-41-14]]

^<<v23-41-14,14>>^ O Senhor  diz ao seu povo: "Você é pequeno e fraquinho, mas não tenha medo, pois eu, o Santo Deus de Israel, sou o seu Salvador e o protegerei.

[[v23-41-15]]

^<<v23-41-15,15>>^ Farei com que você seja como uma máquina de debulhar trigo, que tem pontas de ferro novas e afiadas: você passará sobre os montes, eles virarão pó, e as montanhas ficarão como palha.

[[v23-41-16]]

^<<v23-41-16,16>>^ Você os jogará para cima, o vento os levará, e a ventania os espalhará. Então você ficará alegre porque eu, o Senhor , sou o seu Deus, e você louvará a mim, o Santo Deus de Israel.

[[v23-41-17]]

^<<v23-41-17,17>>^ "Quando o meu povo, pobre e necessitado, procurar água e não encontrar; quando a boca deles estiver seca de sede, eu, o Senhor , os atenderei, eu, o Deus de Israel, não os abandonarei.

[[v23-41-18]]

^<<v23-41-18,18>>^ Farei com que brotem fontes nos vales e com que rios corram pelas montanhas onde não há plantas. Farei com que os desertos virem lagos e com que nas terras secas haja muitos poços.

[[v23-41-19]]

^<<v23-41-19,19>>^ Plantarei árvores no deserto: cedros, acácias, murtas  e oliveiras; nas terras secas, farei crescer pinheiros, junto com os zimbros e ciprestes.

[[v23-41-20]]

^<<v23-41-20,20>>^ Todos verão o que aconteceu e ficarão sabendo que fui eu, o Senhor , quem fez isso. Todos pensarão bem e entenderão que tudo isso foi feito pelo Santo Deus de Israel."

[[v23-41-21]]

^<<v23-41-21,21>>^ O Senhor , o Rei de Israel, diz: "Deuses das nações, venham apresentar a sua causa e fazer a sua defesa.

[[v23-41-22]]

^<<v23-41-22,22>>^ Venham e nos digam o que vai acontecer; expliquem também as profecias  que vocês fizeram no passado, para que nós fiquemos sabendo se elas se cumpriram. Ou então digam o que vai acontecer no futuro, e assim nós poderemos ver se vai dar certo.

[[v23-41-23]]

^<<v23-41-23,23>>^ Anunciem as coisas que vão acontecer daqui em diante a fim de provar que vocês são deuses de fato. Façam o que quiserem, seja bom ou seja mau, para que fiquemos com medo e cheios de pavor.

[[v23-41-24]]

^<<v23-41-24,24>>^ Mas vocês não são nada! Vocês não podem fazer nada! Eu detesto aqueles que os adoram!

[[v23-41-25]]

^<<v23-41-25,25>>^ "Fui eu que chamei um homem que mora no Oriente ; ele confia em mim e vem do Norte para atacar os seus inimigos. Ele pisa em cima de reis como se fossem lama; ele os trata como um oleiro que amassa o barro com os pés.

[[v23-41-26]]

^<<v23-41-26,26>>^ Será que algum de vocês anunciou que isso ia acontecer, para que nós ficássemos sabendo? Algum deus falou disso no passado para que nós disséssemos: ‘Ele tinha razão’? Nenhuma imagem anunciou nada a respeito disso, nenhuma nos avisou; não ouvimos vocês dizerem nem uma só palavra.

[[v23-41-27]]

^<<v23-41-27,27>>^ Pois eu anunciei isso a Sião  desde o começo, eu mandei um mensageiro espalhar essas boas notícias em Jerusalém.

[[v23-41-28]]

^<<v23-41-28,28>>^ Eu procuro os deuses, mas nenhum deles aparece; nenhum deles pode dar explicações ou responder às perguntas que faço.

[[v23-41-29]]

^<<v23-41-29,29>>^ Eles não são nada! Eles não podem fazer nada! Essas imagens são coisas sem vida e sem valor."

'''

xref:023-isaias/023-isaias-040.adoc#v23-40-0[&#60; Capítulo Anterior] | <<v23-41-0,Topo>> | xref:023-isaias/023-isaias-042.adoc#v23-42-0[Próximo Capítulo &#62;]