include::./index.adoc[]

[[v23-54-0]]
=== Isaías, 54
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-54-1]]

^<<v23-54-1,1>>^ Jerusalém, você nunca teve filhos, você nunca sentiu dores de parto, mas agora cante e grite de alegria, pois o Senhor  diz: "A mulher abandonada terá mais filhos do que a que mora com o marido."

[[v23-54-2]]

^<<v23-54-2,2>>^ Aumente a sua barraca, torne ainda maior o lugar onde você mora e não faça economia nisso. Encompride as cordas da barraca e pregue bem as estacas.

[[v23-54-3]]

^<<v23-54-3,3>>^ Pois você vai estender as suas fronteiras para todos os lados; o seu povo será novamente dono das regiões que os seus inimigos conquistaram, e cidades desertas ficarão cheias de gente.

[[v23-54-4]]

^<<v23-54-4,4>>^ Não tenha medo, pois você não ficará envergonhada; não se assuste, pois você não será humilhada. Você esquecerá como foi humilhada quando era jovem , não lembrará mais da desgraça da sua viuvez .

[[v23-54-5]]

^<<v23-54-5,5>>^ Pois o seu Criador, o Senhor  Todo-Poderoso, será seu marido; o Santo Deus de Israel, o Deus do mundo inteiro, a salvará.

[[v23-54-6]]

^<<v23-54-6,6>>^ Você estava aflita como uma mulher abandonada pelo marido, mas o Senhor  a está chamando de volta. O seu Deus diz: "Será que alguém poderia mandar embora a mulher com quem casou quando era jovem?

[[v23-54-7]]

^<<v23-54-7,7>>^ Eu a abandonei, mas só por um momento, e agora, com grande amor, eu a receberei de volta.

[[v23-54-8]]

^<<v23-54-8,8>>^ Na minha ira  e no meu furor, eu me escondi de você por um momento; mas com amor eterno eu terei compaixão de você." É isso o que diz o Senhor , o seu Salvador.

[[v23-54-9]]

^<<v23-54-9,9>>^ O Senhor  Deus diz: "No tempo do dilúvio, eu jurei a Noé que nunca mais as águas cobririam a terra; assim eu juro agora que nunca mais ficarei irado com você, que jamais a castigarei de novo.

[[v23-54-10]]

^<<v23-54-10,10>>^ As montanhas podem desaparecer, os montes podem se desfazer, mas o meu amor por você não acabará nunca, e a minha aliança  de paz com você nunca será quebrada." É isso o que diz o Senhor , que tem amor por você.

[[v23-54-11]]

^<<v23-54-11,11>>^ O Senhor  Deus diz: "Ó Jerusalém, aflita e castigada pela tempestade, sem ninguém que a console! Eu a reconstruirei com pedras preciosas, e os seus alicerces serão de safiras .

[[v23-54-12]]

^<<v23-54-12,12>>^ As suas torres serão de rubis, os seus portões serão de berilo , as suas muralhas, de pedras preciosas.

[[v23-54-13]]

^<<v23-54-13,13>>^ Eu mesmo ensinarei todos os seus moradores, e eles viverão em paz e segurança.

[[v23-54-14]]

^<<v23-54-14,14>>^ Você será fundada sobre a justiça e por isso viverá segura, livre para sempre da violência e do terror.

[[v23-54-15]]

^<<v23-54-15,15>>^ Se alguém a atacar, não será por minha ordem; você derrotará todos os que lutarem contra você.

[[v23-54-16]]

^<<v23-54-16,16>>^ "Eu crio o ferreiro, que sopra as brasas e fabrica armas de guerra. Eu crio também o soldado, que usa as armas para destruir e matar.

[[v23-54-17]]

^<<v23-54-17,17>>^ Mas nenhuma arma poderá derrotar você, e, se alguém for ao tribunal para acusá-la, você não será condenada. O que eu faço pelos meus servos  é isto: eu lhes dou a vitória." O Senhor  falou.

'''

xref:023-isaias/023-isaias-053.adoc#v23-53-0[&#60; Capítulo Anterior] | <<v23-54-0,Topo>> | xref:023-isaias/023-isaias-055.adoc#v23-55-0[Próximo Capítulo &#62;]