include::./index.adoc[]

[[v23-51-0]]
=== Isaías, 51
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-51-1]]

^<<v23-51-1,1>>^ O Senhor  Deus diz: "Escutem, os que procuram a salvação, os que pedem a minha ajuda! Lembrem da rocha da qual foram cortados, da pedreira de onde foram tirados.

[[v23-51-2]]

^<<v23-51-2,2>>^ Pensem no seu antepassado Abraão e em Sara, de quem vocês são descendentes. Abraão não tinha filhos quando eu o chamei, mas eu o abençoei e lhe dei muitos descendentes.

[[v23-51-3]]

^<<v23-51-3,3>>^ Eu, o Senhor , terei compaixão de Jerusalém e de todas as suas casas que estão em ruínas. Eu farei com que as suas terras secas virem um jardim, como o jardim que plantei na região do Éden. Ali haverá alegria e felicidade, haverá música e cânticos de louvor a mim.

[[v23-51-4]]

^<<v23-51-4,4>>^ "Escute, meu povo, dê atenção ao que eu vou dizer: Vou dar as minhas leis  às nações, e os meus mandamentos serão uma luz para os povos.

[[v23-51-5]]

^<<v23-51-5,5>>^ Virei logo salvá-los; está chegando o dia da minha vitória, e eu governarei todos os povos. Nações distantes esperam por mim e confiam em mim para protegê-las.

[[v23-51-6]]

^<<v23-51-6,6>>^ Olhem para o céu, lá em cima, olhem para a terra, aqui embaixo. O céu desaparecerá como fumaça, a terra ficará gasta como uma roupa velha, e os seus moradores morrerão como se fossem moscas. Mas a minha vitória será total, o meu poder durará para sempre.

[[v23-51-7]]

^<<v23-51-7,7>>^ "Escutem, vocês que sabem o que é direito, que têm a minha lei no seu coração! Não fiquem com medo quando forem ofendidos, não se aborreçam quando os outros zombarem de vocês.

[[v23-51-8]]

^<<v23-51-8,8>>^ Pois eles desaparecerão como uma roupa de lã destruída pelas traças. Mas a minha vitória será total, o meu poder durará para sempre."

[[v23-51-9]]

^<<v23-51-9,9>>^ Acorda, ó Senhor , acorda! Salva-nos com o teu grande poder, como fizeste antigamente, no tempo dos nossos antepassados. Tu cortaste Raabe em pedaços, tu mataste aquele monstro do mar.

[[v23-51-10]]

^<<v23-51-10,10>>^ Tu fizeste o mar secar, secaste as águas profundas; no meio do mar, abriste um caminho para que por ele passasse o povo que salvaste.

[[v23-51-11]]

^<<v23-51-11,11>>^ Aqueles a quem o Senhor  salvar voltarão para casa, voltarão cantando para Jerusalém e ali viverão felizes para sempre. A alegria e a felicidade os acompanharão, e não haverá mais tristeza nem choro.

[[v23-51-12]]

^<<v23-51-12,12>>^ O Senhor  diz ao seu povo: "Eu, eu mesmo, lhes dou forças. Então, por que vocês têm medo de pessoas, de seres mortais que não duram mais do que a palha?

[[v23-51-13]]

^<<v23-51-13,13>>^ Por que esquecem o Senhor , o seu Criador, aquele que estendeu o céu e firmou a terra? Por que estão sempre com medo de inimigos cruéis, que os perseguem e estão prontos para destruí-los? Que pode fazer a fúria deles contra vocês?

[[v23-51-14]]

^<<v23-51-14,14>>^ Logo os prisioneiros serão postos em liberdade; eles não morrerão, nem passarão fome.

[[v23-51-15]]

^<<v23-51-15,15>>^ "Eu, o Senhor , sou o Deus de vocês. Eu agito o mar e faço as suas ondas rugirem. O meu nome é Senhor , o Todo-Poderoso.

[[v23-51-16]]

^<<v23-51-16,16>>^ Eu dei a vocês os meus ensinamentos e com a minha mão eu os protejo. Eu, que estendi o céu e firmei a terra, digo aos moradores de Jerusalém: ‘Vocês são o meu povo.’ "

[[v23-51-17]]

^<<v23-51-17,17>>^ Acorde, Jerusalém, acorde e levante-se! O Senhor  fez com que você bebesse o vinho da sua ira ; você bebeu tudo e ficou bêbada.

[[v23-51-18]]

^<<v23-51-18,18>>^ De todos os seus filhos, de todos aqueles que você criou, não houve um só que pegasse você pela mão e que a ajudasse a andar.

[[v23-51-19]]

^<<v23-51-19,19>>^ Você sofreu duas desgraças: a sua terra foi arrasada pelos inimigos, e a guerra e a fome mataram os seus moradores. Quem tem pena de você? Quem procura consolá-la?

[[v23-51-20]]

^<<v23-51-20,20>>^ Os seus moradores desmaiam de fome e estão caídos nas esquinas das ruas; são como carneiros selvagens presos nas redes dos caçadores. Eles caíram por causa da ira do Senhor , por causa do castigo do seu Deus.

[[v23-51-21]]

^<<v23-51-21,21>>^ Pobre Jerusalém! Você está bêbada, mas não por ter bebido vinho.

[[v23-51-22]]

^<<v23-51-22,22>>^ Agora, escute o que diz o seu Senhor e Deus, aquele que vai defender a causa do seu povo. O Senhor  diz: "Agora estou tirando das suas mãos o copo cheio da minha ira, o copo que fez você ficar bêbada. Você nunca mais beberá dele.

[[v23-51-23]]

^<<v23-51-23,23>>^ Darei esse copo aos seus inimigos, aos que lhe disseram: ‘Deite-se no chão, que vamos pisar em cima de você.’ Você se deitou, e eles a pisaram, como se você fosse o pó da rua."

'''

xref:023-isaias/023-isaias-050.adoc#v23-50-0[&#60; Capítulo Anterior] | <<v23-51-0,Topo>> | xref:023-isaias/023-isaias-052.adoc#v23-52-0[Próximo Capítulo &#62;]