include::./index.adoc[]

[[v23-26-0]]
=== Isaías, 26
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-26-1]]

^<<v23-26-1,1>>^ Naquele dia, o povo de Judá cantará este hino: A nossa cidade é forte! Deus nos protege com altas muralhas.

[[v23-26-2]]

^<<v23-26-2,2>>^ Abram os portões da cidade e deixem entrar o povo que é fiel a Deus e que faz o que é direito.

[[v23-26-3]]

^<<v23-26-3,3>>^ Tu, ó Senhor , dás paz e prosperidade às pessoas que têm uma fé firme, às pessoas que confiam em ti.

[[v23-26-4]]

^<<v23-26-4,4>>^ Confiem sempre no Senhor , pois ele é o nosso eterno abrigo.

[[v23-26-5]]

^<<v23-26-5,5>>^ Ele rebaixou os vaidosos e humilhou a cidade orgulhosa em que moravam. Ele derrubou e arrasou a cidade deles,

[[v23-26-6]]

^<<v23-26-6,6>>^ e agora os pobres e os necessitados pisam as suas ruínas.

[[v23-26-7]]

^<<v23-26-7,7>>^ O caminho das pessoas direitas é fácil; tu, ó Deus justo, tornas plano o caminho por onde elas andam.

[[v23-26-8]]

^<<v23-26-8,8>>^ Ó Senhor , nós seguimos o caminho das tuas leis e em ti pomos a nossa esperança; o nosso maior desejo é conhecer-te e pensar em ti.

[[v23-26-9]]

^<<v23-26-9,9>>^ Com todo o meu coração, quero estar contigo de noite; com todo o meu ser, procuro conhecer a tua vontade. Pois, quando julgas e castigas o mundo, os seus moradores aprendem o que é justiça.

[[v23-26-10]]

^<<v23-26-10,10>>^ Ainda que tenhas compaixão dos maus, mesmo assim eles não aprendem a fazer o que é certo. Mesmo aqui neste país onde o povo é direito, eles continuam a fazer o que é mau e não se importam com a grandeza de Deus, o Senhor .

[[v23-26-11]]

^<<v23-26-11,11>>^ Ó Senhor , tu tens a mão levantada para castigar, mas os teus inimigos não notam isso. Porém, quando virem o grande amor que tens pelo teu povo, então ficarão envergonhados. Que o fogo da tua ira  os devore!

[[v23-26-12]]

^<<v23-26-12,12>>^ Ó Senhor , tu nos fazes prosperar; tudo o que conseguimos é feito por ti.

[[v23-26-13]]

^<<v23-26-13,13>>^ Ó Senhor , nosso Deus, temos sido dominados por outros povos e pelos seus deuses, mas confessamos que só tu és o nosso Deus.

[[v23-26-14]]

^<<v23-26-14,14>>^ Aqueles povos estão mortos, não voltarão a viver; são somente sombras, não ressuscitarão. Pois tu os castigaste e destruíste, e ninguém lembra mais deles.

[[v23-26-15]]

^<<v23-26-15,15>>^ Tu, ó Senhor , fizeste a nossa nação ficar maior; aumentaste o território do nosso país, e isso trouxe glória  para o teu nome.

[[v23-26-16]]

^<<v23-26-16,16>>^ Castigaste o teu povo, ó Senhor ; na nossa aflição, oramos a ti.

[[v23-26-17]]

^<<v23-26-17,17>>^ Como uma mulher que está dando à luz se torce e grita de dor, assim estávamos nós por causa de ti, ó Senhor .

[[v23-26-18]]

^<<v23-26-18,18>>^ Nós sofremos dores de parto e nos torcemos, mas não demos nada à luz. Não conseguimos nenhuma vitória para o nosso país, nem fizemos aumentar o número de pessoas na terra.

[[v23-26-19]]

^<<v23-26-19,19>>^ Os mortos do nosso povo voltarão a viver; os seus corpos ressuscitarão. Os que estão no mundo dos mortos acordarão e cantarão de alegria. Como o orvalho que tu envias dá vida à terra, assim de dentro da terra os mortos sairão vivos.

[[v23-26-20]]

^<<v23-26-20,20>>^ Meu povo, vão para as suas casas e tranquem as portas; escondam-se por algum tempo até que passe a ira  de Deus.

[[v23-26-21]]

^<<v23-26-21,21>>^ Porque o Senhor  Deus virá da sua morada, no céu, a fim de castigar os moradores da terra por causa dos seus pecados. Pois a terra não esconderá mais os que foram mortos, mas deixará que apareçam todos os crimes de sangue.

'''

xref:023-isaias/023-isaias-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaias/023-isaias-027.adoc#v23-27-0[Próximo Capítulo &#62;]