include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-5-1]]

^<<v23-5-1,1>>^ Vou cantar agora para o meu amigo uma canção a respeito da sua plantação de uvas. O meu amigo fez essa plantação num lugar onde a terra era boa.

[[v23-5-2]]

^<<v23-5-2,2>>^ Ele cavou o chão, tirou as pedras e plantou as melhores mudas de uva. No centro do terreno, ele construiu uma torre para o vigia e fez também um tanque para esmagar as uvas. Esperava que as parreiras  dessem uvas boas, mas deram somente uvas azedas.

[[v23-5-3]]

^<<v23-5-3,3>>^ Agora o meu amigo diz: "Moradores de Jerusalém e povo de Judá, digam se a culpa é minha ou da minha plantação de uvas.

[[v23-5-4]]

^<<v23-5-4,4>>^ Fiz por ela tudo o que podia; então, por que produziu uvas azedas em vez das uvas doces que eu esperava?

[[v23-5-5]]

^<<v23-5-5,5>>^ "Agora eu lhes digo o que vou fazer com a minha plantação de uvas: vou tirar a cerca e derrubar os muros que a protegem e vou deixar que os animais invadam a plantação e acabem com as parreiras.

[[v23-5-6]]

^<<v23-5-6,6>>^ A plantação ficará abandonada; as parreiras não serão podadas, e a terra não será cultivada; o mato e os espinheiros tomarão conta dela. Também darei ordem às nuvens para que não deixem cair chuva na minha plantação."

[[v23-5-7]]

^<<v23-5-7,7>>^ A plantação de uvas do Senhor  Todo-Poderoso, as parreiras de que ele tanto gosta são o povo de Israel e o povo de Judá. Deus esperava que eles obedecessem à sua lei , mas ele os viu cometendo crimes de morte; esperava que fizessem o que é direito, mas só ouviu as suas vítimas gritando por socorro.

[[v23-5-8]]

^<<v23-5-8,8>>^ Ai de vocês que compram casas e mais casas, que se tornam donos de mais e mais terrenos! Daqui a pouco não haverá mais lugar para os outros morarem, e vocês serão os únicos moradores do país.

[[v23-5-9]]

^<<v23-5-9,9>>^ Ouvi o Senhor  Todo-Poderoso dizer isto: "As grandes e belas mansões serão destruídas, e ninguém ficará morando nelas.

[[v23-5-10]]

^<<v23-5-10,10>>^ Um alqueire de parreiras dará somente uns vinte litros de vinho, e cem quilos de sementes produzirão somente dez quilos de trigo."

[[v23-5-11]]

^<<v23-5-11,11>>^ Ai dos que passam o dia inteiro bebendo cerveja e vinho, desde a madrugada até tarde da noite, e ficam completamente bêbados!

[[v23-5-12]]

^<<v23-5-12,12>>^ Nas suas festas há música de harpas  e de liras , de pandeiros e de flautas e muito vinho para beber. Eles não se importam com os planos de Deus, o Senhor , nem levam em conta o que ele está fazendo.

[[v23-5-13]]

^<<v23-5-13,13>>^ Portanto, por causa da sua desobediência, o meu povo será levado prisioneiro para fora do país. O povo e as autoridades morrerão de fome e de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ O mundo dos mortos , como se fosse uma fera faminta, abrirá a sua boca enorme e engolirá o povo e as autoridades, toda essa gente que vive nas farras e nas orgias.

[[v23-5-15]]

^<<v23-5-15,15>>^ Todos ficarão envergonhados, e os orgulhosos serão humilhados.

[[v23-5-16]]

^<<v23-5-16,16>>^ Mas o Senhor  Todo-Poderoso fará o que é direito e assim mostrará a sua grandeza; Deus fará o que é certo, e assim todos ficarão sabendo que ele é santo.

[[v23-5-17]]

^<<v23-5-17,17>>^ As cidades virarão montões de ruínas, e ali as ovelhas e os cabritinhos encontrarão pasto.

[[v23-5-18]]

^<<v23-5-18,18>>^ Ai dos que se amarram aos seus pecados com mentiras! Eles andam arrastando a sua maldade como quem puxa um carro

[[v23-5-19]]

^<<v23-5-19,19>>^ e dizem: "Que Deus se apresse e faça logo o que vai fazer para que nós fiquemos sabendo o que é! Que o Santo Deus de Israel realize depressa os seus planos para que nós possamos conhecê-los!"

[[v23-5-20]]

^<<v23-5-20,20>>^ Ai dos que chamam de mau aquilo que é bom e que chamam de bom aquilo que é mau; que fazem a luz virar escuridão e a escuridão virar luz; que fazem o amargo ficar doce e o que é doce ficar amargo!

[[v23-5-21]]

^<<v23-5-21,21>>^ Ai dos que acham que são sábios, dos que pensam que sabem tudo!

[[v23-5-22]]

^<<v23-5-22,22>>^ Ai dos que são campeões de beber vinho, que vencem apostas de misturar bebidas alcoólicas;

[[v23-5-23]]

^<<v23-5-23,23>>^ que aceitam dinheiro para torcer a justiça, deixando livres os culpados e condenando os inocentes!

[[v23-5-24]]

^<<v23-5-24,24>>^ Portanto, assim como o fogo queima a palha, e as chamas acabam com a grama seca, assim também vocês desaparecerão. Serão como plantas cujas raízes ficam podres e cujas flores são levadas pelo vento como se fossem pó. Pois vocês desobedeceram às leis  do Senhor  Todo-Poderoso e desprezaram os mandamentos do Santo Deus de Israel.

[[v23-5-25]]

^<<v23-5-25,25>>^ Por isso, o Senhor  ficou irado  com o seu povo; ele levantou a mão e os castigou. As montanhas tremeram, e os corpos dos mortos ficaram largados nas ruas como lixo. Mesmo assim, a ira de Deus não passou; a sua mão continua levantada para castigar.

[[v23-5-26]]

^<<v23-5-26,26>>^ O Senhor  levanta uma bandeira para chamar uma nação que fica lá no fim do mundo; com um assobio, ele chama o povo daquele país distante, e eles vêm correndo com muita rapidez.

[[v23-5-27]]

^<<v23-5-27,27>>^ Nenhum dos seus soldados se cansa ou tropeça, nenhum descansa ou dorme. Eles estão preparados para lutar: os cinturões estão bem apertados, e as tiras das sandálias não se arrebentam.

[[v23-5-28]]

^<<v23-5-28,28>>^ As suas flechas são pontudas, e os seus arcos estão prontos para atirar. Os cascos dos seus cavalos são duros como pedra, e as rodas dos seus carros de guerra parecem redemoinhos.

[[v23-5-29]]

^<<v23-5-29,29>>^ Esses soldados rugem como leões, como leões ferozes que matam um animal e, rosnando, o arrastam para um lugar onde ninguém o pode arrancar deles.

[[v23-5-30]]

^<<v23-5-30,30>>^ Quando chegar aquele dia, esse povo rugirá como o mar contra o povo de Israel. Se alguém olhar para a terra, verá somente escuridão e tristeza e nuvens negras escondendo a luz.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]