include::./index.adoc[]

[[v23-19-0]]
=== Isaías, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-19-1]]

^<<v23-19-1,1>>^ Esta é a mensagem contra o Egito: O Senhor , montado numa nuvem, vai indo depressa para o Egito. Os ídolos daquele país tremerão diante dele, e todos os egípcios ficarão com medo.

[[v23-19-2]]

^<<v23-19-2,2>>^ O Senhor  Deus diz: "Vou atiçar os egípcios uns contra os outros; irmão lutará contra irmão, vizinho contra vizinho, cidade contra cidade, província  contra província.

[[v23-19-3]]

^<<v23-19-3,3>>^ Os egípcios perderão a coragem, e eu farei com que os seus planos fracassem. Então eles consultarão os ídolos e os adivinhos, os médiuns e os feiticeiros.

[[v23-19-4]]

^<<v23-19-4,4>>^ Mas eu entregarei os egípcios nas mãos de um rei mau, e ele os governará com crueldade. Eu, o Senhor , o Deus Todo-Poderoso, falei."

[[v23-19-5]]

^<<v23-19-5,5>>^ As águas do Nilo vão baixar; o rio vai ficar completamente seco.

[[v23-19-6]]

^<<v23-19-6,6>>^ As águas irão baixando; os canais do rio ficarão todos secos e vão cheirar mal. Nas margens, as taboas e os juncos  murcharão,

[[v23-19-7]]

^<<v23-19-7,7>>^ todas as outras plantas também morrerão, e as plantações das beiras do rio secarão. Tudo o que foi plantado será levado pelo vento e desaparecerá.

[[v23-19-8]]

^<<v23-19-8,8>>^ Os pescadores ficarão desanimados e chorarão; os seus anzóis e as suas redes não prestarão para nada.

[[v23-19-9]]

^<<v23-19-9,9>>^ Os que fazem tecidos de linho ficarão aflitos;

[[v23-19-10]]

^<<v23-19-10,10>>^ os tecelões e os artesãos cairão no desespero.

[[v23-19-11]]

^<<v23-19-11,11>>^ As autoridades da cidade de Zoã não têm juízo; os sábios conselheiros do rei lhe dão conselhos tolos. Como é que vocês se atrevem a dizer ao rei: "Somos descendentes dos antigos sábios; os nossos antepassados eram reis"?

[[v23-19-12]]

^<<v23-19-12,12>>^ Rei do Egito, onde estão agora os seus sábios? Que eles lhe digam o que é que o Senhor  Todo-Poderoso está planejando fazer contra o Egito!

[[v23-19-13]]

^<<v23-19-13,13>>^ As autoridades de Zoã perderam o juízo, e as da cidade de Mênfis estão enganadas. Os governadores das províncias estão fazendo o povo do Egito errar o caminho.

[[v23-19-14]]

^<<v23-19-14,14>>^ O Senhor  pôs neles um espírito de confusão; os conselhos que eles dão só confundem ainda mais os egípcios, e estes parecem bêbados escorregando no seu próprio vômito.

[[v23-19-15]]

^<<v23-19-15,15>>^ Ninguém, seja rico ou pobre, importante ou humilde, pode fazer nada para ajudar o Egito.

[[v23-19-16]]

^<<v23-19-16,16>>^ Naquele dia, os egípcios parecerão mulheres: ficarão todos tremendo de medo quando o Senhor  Todo-Poderoso levantar a mão para castigá-los.

[[v23-19-17]]

^<<v23-19-17,17>>^ Eles terão medo da terra de Judá; e, todas as vezes que ouvirem falar dessa terra, eles ficarão apavorados pensando naquilo que o Senhor  Todo-Poderoso já planejou fazer contra eles.

[[v23-19-18]]

^<<v23-19-18,18>>^ Naquele dia, haverá no Egito cinco cidades em que os moradores falarão hebraico  e jurarão obedecer ao Senhor  Todo-Poderoso; uma dessas cidades será chamada de "Cidade do Sol".

[[v23-19-19]]

^<<v23-19-19,19>>^ Naquele dia, haverá no Egito um altar dedicado a Deus, o Senhor , e na fronteira do país será levantada uma coluna em honra do Senhor .

[[v23-19-20]]

^<<v23-19-20,20>>^ Eles serão construídos para serem sinais e testemunhas da presença do Senhor  Todo-Poderoso na terra do Egito. E, quando os egípcios forem perseguidos e clamarem ao Senhor  pedindo ajuda, ele lhes enviará um salvador e defensor que os livrará dos seus inimigos.

[[v23-19-21]]

^<<v23-19-21,21>>^ E o Senhor  mostrará aos egípcios quem ele é, e eles o conhecerão. Eles adorarão o Senhor  e lhe apresentarão sacrifícios  e ofertas de cereais. Farão promessas ao Senhor  e as cumprirão.

[[v23-19-22]]

^<<v23-19-22,22>>^ E o Senhor  ferirá os egípcios, mas depois os curará. Eles se arrependerão e voltarão para o Senhor , e ele atenderá os seus pedidos e os curará.

[[v23-19-23]]

^<<v23-19-23,23>>^ Naquele dia, haverá uma estrada ligando o Egito com a Assíria: os egípcios irão até a Assíria, e os assírios irão até o Egito, e juntos os dois povos adorarão o Senhor .

[[v23-19-24]]

^<<v23-19-24,24>>^ Naquele dia, estas três nações — Israel, Egito e Assíria — serão uma bênção para o mundo inteiro.

[[v23-19-25]]

^<<v23-19-25,25>>^ O Senhor  Todo-Poderoso as abençoará, dizendo: "Eu abençoo o Egito, o meu povo; a Assíria, que eu criei; e Israel, o meu povo escolhido."

'''

xref:023-isaias/023-isaias-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaias/023-isaias-020.adoc#v23-20-0[Próximo Capítulo &#62;]