include::./index.adoc[]

[[v23-21-0]]
=== Isaías, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-21-1]]

^<<v23-21-1,1>>^ Esta é a mensagem contra a Babilônia, "o deserto do mar": Como os furacões que varrem a região sul, assim o destruidor vem do deserto, daquela terra pavorosa.

[[v23-21-2]]

^<<v23-21-2,2>>^ A visão que Deus me mostrou foi terrível: traição e destruição por toda parte! Exército de Elão, ataque! Exército da Média, cerque as cidades! Deus vai acabar com os sofrimentos que a Babilônia causou.

[[v23-21-3]]

^<<v23-21-3,3>>^ A visão me deixou desesperado; estou sofrendo como uma mulher que está dando à luz. Eu quase não posso ouvir, de tanta dor; quase não posso ver, de tão fraco.

[[v23-21-4]]

^<<v23-21-4,4>>^ Estou cheio de confusão e tremo de medo; esperava que a noite me trouxesse alívio, mas ela só me trouxe pavor.

[[v23-21-5]]

^<<v23-21-5,5>>^ Na visão, eu vi um banquete preparado na Babilônia; os lugares para os convidados sentarem estavam prontos, e eles comiam e bebiam. De repente, alguém deu esta ordem: "Oficiais, levantem-se e peguem as suas armas!"

[[v23-21-6]]

^<<v23-21-6,6>>^ O Senhor me ordenou: "Vá e ponha um soldado de vigia, e que ele conte tudo o que vir!

[[v23-21-7]]

^<<v23-21-7,7>>^ Que o vigia preste muita atenção se enxergar um grupo de cavaleiros avançando em fila de dois e homens montados em jumentos e em camelos!"

[[v23-21-8]]

^<<v23-21-8,8>>^ Então o vigia gritou: "Ó Senhor, dia e noite tenho ficado no meu posto e estou sempre vigiando.

[[v23-21-9]]

^<<v23-21-9,9>>^ Atenção! Aí vêm cavaleiros, em fila de dois!" Depois o vigia disse: "Ela caiu! Babilônia caiu! Todas as imagens que os babilônios adoravam estão despedaçadas no chão!"

[[v23-21-10]]

^<<v23-21-10,10>>^ Vocês, meu povo, foram maltratados, foram malhados como o trigo no terreiro. Mas eu lhes estou anunciando a mensagem que recebi do Senhor  Todo-Poderoso, o Deus de Israel.

[[v23-21-11]]

^<<v23-21-11,11>>^ Esta é a mensagem contra Edom: Alguém me chama do país de Edom e diz: "Guarda, quanto falta para terminar a noite? Guarda, quanto falta para terminar a noite?"

[[v23-21-12]]

^<<v23-21-12,12>>^ O guarda responde: "A manhã vai chegar, mas a noite voltará outra vez. Se quiser perguntar de novo, volte e pergunte."

[[v23-21-13]]

^<<v23-21-13,13>>^ Esta é a mensagem contra a Arábia: Os fugitivos da tribo de Dedã são forçados a acampar no deserto.

[[v23-21-14]]

^<<v23-21-14,14>>^ Moradores de Temá, socorram os dedanitas, dando-lhes água e comida.

[[v23-21-15]]

^<<v23-21-15,15>>^ Pois eles estão fugindo de uma batalha feroz; tentam escapar dos seus inimigos, que querem matá-los com as suas espadas, com os seus arcos e flechas.

[[v23-21-16]]

^<<v23-21-16,16>>^ O Senhor me disse: — Daqui a exatamente um ano, a grandeza das tribos de Quedar terá desaparecido.

[[v23-21-17]]

^<<v23-21-17,17>>^ Poucos dos flecheiros valentes de Quedar estarão vivos. Eu, o Senhor , o Deus de Israel, falei.

'''

xref:023-isaias/023-isaias-020.adoc#v23-20-0[&#60; Capítulo Anterior] | <<v23-21-0,Topo>> | xref:023-isaias/023-isaias-022.adoc#v23-22-0[Próximo Capítulo &#62;]