include::./index.adoc[]

[[v23-16-0]]
=== Isaías, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-16-1]]

^<<v23-16-1,1>>^ Da cidade de Sela, no deserto, os moabitas enviam carneirinhos como presente para aquele que governa no monte Sião .

[[v23-16-2]]

^<<v23-16-2,2>>^ Como passarinhos que foram espantados dos seus ninhos, assim os moabitas andam de um lado para o outro nas margens do rio Arnom.

[[v23-16-3]]

^<<v23-16-3,3>>^ Eles dizem ao povo de Judá: "Digam o que devemos fazer; venham nos ajudar e nos defender. Sejam para nós como uma árvore que ao meio-dia espalha a sua sombra, que é escura como a noite.

[[v23-16-4]]

^<<v23-16-4,4>>^ Estamos fugindo de Moabe; venham nos proteger daqueles que nos querem matar e deixem que nós moremos na terra de vocês." Quando terminar a perseguição, e o perseguidor cruel tiver saído do país,

[[v23-16-5]]

^<<v23-16-5,5>>^ então um descendente de Davi será rei. Ele governará com fidelidade, procurará julgar com justiça e se esforçará para fazer o que é direito.

[[v23-16-6]]

^<<v23-16-6,6>>^ O povo de Judá diz: "Ouvimos falar do orgulho dos moabitas; sabemos que eles são um povo vaidoso e cheio de si, arrogante e convencido. Mas eles não têm nada de que se orgulhar."

[[v23-16-7]]

^<<v23-16-7,7>>^ Por isso, os moabitas vão chorar; todos eles vão gritar de tristeza quando lembrarem dos bolos de passas que costumavam oferecer aos ídolos na cidade de Quir-Heres.

[[v23-16-8]]

^<<v23-16-8,8>>^ Agora estão abandonadas as plantações de uvas de Hesbom e de Sibma, aquelas plantações cujo vinho deixava bêbados os chefes de muitas nações. Elas se estendiam até a cidade de Jazer; iam para o leste até o deserto e para o oeste até o outro lado do mar Morto.

[[v23-16-9]]

^<<v23-16-9,9>>^ Por isso, eu choro pela cidade de Jazer e também pelas parreiras  de Sibma. Com as minhas lágrimas, rego as cidades de Hesbom e de Eleal, pois não se ouvem mais os gritos de alegria dos que ali fazem as suas colheitas.

[[v23-16-10]]

^<<v23-16-10,10>>^ Desapareceram das terras boas toda alegria e felicidade; não há mais canções alegres nas plantações de uvas. Ninguém pisa as uvas para fazer vinho; Deus acabou com os gritos de alegria.

[[v23-16-11]]

^<<v23-16-11,11>>^ Como as cordas de uma lira , o meu coração treme de tristeza pelo povo de Moabe e pelos moradores de Quir-Heres.

[[v23-16-12]]

^<<v23-16-12,12>>^ Os moabitas se cansarão de tanto ir aos seus lugares de adoração nos montes para orar aos seus deuses, mas isso não adiantará nada.

[[v23-16-13]]

^<<v23-16-13,13>>^ Esta foi a mensagem que o Senhor  anunciou há muito tempo a respeito de Moabe.

[[v23-16-14]]

^<<v23-16-14,14>>^ Mas agora o Senhor  diz: — Daqui a exatamente três anos, Moabe, com a sua enorme população, perderá todo o seu poder. E os moabitas que ficarem vivos serão poucos e fracos.

'''

xref:023-isaias/023-isaias-015.adoc#v23-15-0[&#60; Capítulo Anterior] | <<v23-16-0,Topo>> | xref:023-isaias/023-isaias-017.adoc#v23-17-0[Próximo Capítulo &#62;]