include::./index.adoc[]

[[v23-44-0]]
=== Isaías, 44
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-44-1]]

^<<v23-44-1,1>>^ O Senhor  Deus diz: "Escute, Israel, pois você é o meu servo , o povo que eu escolhi!

[[v23-44-2]]

^<<v23-44-2,2>>^ Eu, o Senhor , sou o seu Criador e o tenho ajudado desde o dia em que você nasceu. Israel, meu servo, não fique com medo, pois eu o amo e o escolhi para ser meu.

[[v23-44-3]]

^<<v23-44-3,3>>^ Vou fazer com que caia chuva no deserto e com que em terras secas corram rios. Assim também derramarei o meu Espírito sobre os seus descendentes e lhes darei as minhas bênçãos.

[[v23-44-4]]

^<<v23-44-4,4>>^ Eles crescerão como a grama bem-regada, como chorões que nascem na beira dos rios.

[[v23-44-5]]

^<<v23-44-5,5>>^ "Muitos se juntarão ao povo de Deus. Um dirá assim: ‘Eu sou do Senhor ’; outro dirá: ‘o meu nome é Jacó’; outro ainda escreverá na sua mão: ‘Eu pertenço ao Senhor ’; e ainda outro usará Israel como sobrenome."

[[v23-44-6]]

^<<v23-44-6,6>>^ O Senhor , o Rei e Salvador de Israel, o Deus Todo-Poderoso, diz: "Eu sou o primeiro e o último, além de mim não há outro deus.

[[v23-44-7]]

^<<v23-44-7,7>>^ Haverá outro que seja igual a mim? Pois que venha à minha presença, apresente as suas razões e prove que está dizendo a verdade. Quem anunciou tudo o que ia acontecer? Já houve alguém que desde o princípio sempre pudesse contar as coisas do futuro?

[[v23-44-8]]

^<<v23-44-8,8>>^ Meu povo, não tenha medo, nem fique apavorado! Não é verdade que desde o princípio eu sempre anunciei a vocês o que ia acontecer? Vocês são minhas testemunhas de que isso é verdade. Será que há outro deus além de mim? Não! Não existe outro protetor; eu não conheço nenhum."

[[v23-44-9]]

^<<v23-44-9,9>>^ Os que fazem imagens não prestam, e os seus deuses, que eles tanto amam, não valem nada. Os que adoram imagens são tolos e cegos e por isso serão humilhados.

[[v23-44-10]]

^<<v23-44-10,10>>^ É uma grande tolice fazer uma imagem para ser adorada como se fosse um deus.

[[v23-44-11]]

^<<v23-44-11,11>>^ Todos os que a adorarem serão humilhados. Os que fazem ídolos são apenas seres humanos; nada mais. Que eles se reúnam e se apresentem no tribunal! Ali ficarão apavorados e serão humilhados.

[[v23-44-12]]

^<<v23-44-12,12>>^ O ferreiro pega um pedaço de metal, coloca nas brasas e depois com toda a força vai batendo nele com o martelo até formar a imagem. Ele trabalha tanto, que não come, nem bebe e acaba perdendo as forças.

[[v23-44-13]]

^<<v23-44-13,13>>^ O escultor mede um pedaço de madeira e com um giz desenha nele a figura do ídolo. Depois, com as suas ferramentas, ele faz uma estátua com a forma de um belo ser humano, para ser colocada num templo.

[[v23-44-14]]

^<<v23-44-14,14>>^ O escultor vai à floresta para cortar uma árvore; escolhe um cedro, um cipreste ou um carvalho. Ele só corta árvores bem grossas ou então planta uma e espera até que a chuva a faça crescer.

[[v23-44-15]]

^<<v23-44-15,15>>^ O homem usa uma parte da madeira para fazer um fogo; ali ele se esquenta e também assa o pão. A outra parte da madeira é usada para fazer uma imagem; e o homem fica de joelhos e a adora.

[[v23-44-16]]

^<<v23-44-16,16>>^ Assim metade da madeira serve para fazer um fogo; o homem assa a carne, come e fica satisfeito. Também se esquenta e diz: "Que fogo bom! Já me esquentei bem!"

[[v23-44-17]]

^<<v23-44-17,17>>^ Com a outra metade da madeira, o homem faz uma imagem, isto é, um deus; depois, fica de joelhos e a adora. E faz esta oração: "Tu és o meu deus; salva-me!"

[[v23-44-18]]

^<<v23-44-18,18>>^ Essa gente não tem juízo. Eles fecharam os olhos e não podem ver nada; fecharam também a sua mente e não entendem nada.

[[v23-44-19]]

^<<v23-44-19,19>>^ O homem que faz imagens não entende nada e não tem a inteligência necessária para dizer a si mesmo: "Ora, com metade dessa madeira eu fiz um fogo; assei o pão, assei a carne e comi. E com a outra metade eu fiz esta imagem nojenta. Agora, aqui estou eu, adorando um pedaço de madeira!"

[[v23-44-20]]

^<<v23-44-20,20>>^ Adorar uma imagem não adianta nada; é o mesmo que comer cinzas. O homem que adora imagens não pensa direito, mas vive enganado. Ele não pode se salvar, pois não é capaz de dizer: "Isto que está na minha mão não é um deus coisa nenhuma."

[[v23-44-21]]

^<<v23-44-21,21>>^ O Senhor  Deus diz: "Povo de Israel, lembre disto! Não esqueça que você é o meu servo . Eu o criei para que me servisse e nunca esquecerei você.

[[v23-44-22]]

^<<v23-44-22,22>>^ Já perdoei as suas maldades e os seus pecados; eles desapareceram como desaparece a cerração. Volte para mim, pois eu sou o seu Salvador."

[[v23-44-23]]

^<<v23-44-23,23>>^ Ó céus, gritem de alegria por causa daquilo que o Senhor  Deus fez! Cantem louvores, lugares profundos da terra! Montanhas e florestas, com as suas árvores, cantem todos de alegria! Pois o Senhor  salvou o povo de Israel e assim mostrou a sua grandeza.

[[v23-44-24]]

^<<v23-44-24,24>>^ O Senhor , o Salvador de Israel, diz: "Meu povo, eu sou o seu Criador; antes que você tivesse nascido, eu já o havia criado. Sozinho, eu criei todas as coisas; estendi os céus e firmei a terra sem a ajuda de ninguém.

[[v23-44-25]]

^<<v23-44-25,25>>^ Eu não deixo que se cumpram as mensagens de profetas  mentirosos e faço com que os adivinhos fiquem parecendo tolos. Faço com que os sábios se enganem e transformo toda a sua sabedoria em tolice.

[[v23-44-26]]

^<<v23-44-26,26>>^ Mas eu faço com que se cumpra a mensagem do meu servo e com que as palavras dos meus mensageiros aconteçam. Prometo que Jerusalém terá moradores novamente e que as cidades de Judá serão reconstruídas. Farei com que elas se levantem do meio das suas ruínas.

[[v23-44-27]]

^<<v23-44-27,27>>^ Basta que eu dê uma ordem, e o mar seca, e os rios ficam sem água.

[[v23-44-28]]

^<<v23-44-28,28>>^ Sou eu quem diz a Ciro : "Você governará em meu nome e fará o que eu quero. Você ordenará que Jerusalém seja reconstruída e que sejam postos os alicerces do novo Templo."

'''

xref:023-isaias/023-isaias-043.adoc#v23-43-0[&#60; Capítulo Anterior] | <<v23-44-0,Topo>> | xref:023-isaias/023-isaias-045.adoc#v23-45-0[Próximo Capítulo &#62;]