include::./index.adoc[]

[[v23-20-0]]
=== Isaías, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-20-1]]

^<<v23-20-1,1>>^ Sargão, o rei da Assíria, enviou o seu exército, comandado pelo comandante-em-chefe, para atacar a cidade de Asdode, e ele a conquistou.

[[v23-20-2]]

^<<v23-20-2,2>>^ Três anos antes disso, o Senhor  Deus tinha dito a Isaías, filho de Amoz: — Tire a roupa de pano grosseiro que você está vestindo e tire também as sandálias. Isaías tinha obedecido e havia andado meio nu e descalço.

[[v23-20-3]]

^<<v23-20-3,3>>^ Depois da conquista de Asdode, o Senhor  disse: — Durante três anos, o meu servo  Isaías andou meio nu e descalço como um sinal e aviso daquilo que vai acontecer com o Egito e com a Etiópia.

[[v23-20-4]]

^<<v23-20-4,4>>^ O rei da Assíria levará como prisioneiros os egípcios e os etíopes, tanto os moços como os velhos. Eles irão meio nus e descalços, com as nádegas descobertas, trazendo assim vergonha para o Egito.

[[v23-20-5]]

^<<v23-20-5,5>>^ Então aqueles que confiavam na Etiópia e que se gabavam do Egito ficarão desiludidos e decepcionados.

[[v23-20-6]]

^<<v23-20-6,6>>^ E os povos que vivem no litoral do mar Mediterrâneo dirão: "Vejam só o que aconteceu com aqueles em quem nós confiávamos e a quem fomos pedir proteção contra o rei da Assíria! E, agora, como é que nós vamos escapar?"

'''

xref:023-isaias/023-isaias-019.adoc#v23-19-0[&#60; Capítulo Anterior] | <<v23-20-0,Topo>> | xref:023-isaias/023-isaias-021.adoc#v23-21-0[Próximo Capítulo &#62;]