include::./index.adoc[]

[[v23-18-0]]
=== Isaías, 18
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-18-1]]

^<<v23-18-1,1>>^ Como vai sofrer a nação que fica às margens dos rios da Etiópia, a terra onde se ouve o zumbido de insetos!

[[v23-18-2]]

^<<v23-18-2,2>>^ Esse país nos manda os seus mensageiros que descem o rio Nilo em barcos feitos de junco . Mensageiros velozes, voltem para casa! Voltem para o seu povo forte e poderoso, aquela gente alta e de pele lustrosa; um povo de quem o mundo inteiro tem medo e que vive numa região dividida por rios.

[[v23-18-3]]

^<<v23-18-3,3>>^ Escutem, todos os povos do mundo, todos os moradores da terra! Vejam a bandeira que será levantada nas montanhas e ouçam o som da corneta.

[[v23-18-4]]

^<<v23-18-4,4>>^ Pois o Senhor  Deus me disse: "Do meu lar, no céu, olharei calmo e tranquilo como o sol que brilha num dia de verão, como as gotas de orvalho que aparecem no tempo da colheita."

[[v23-18-5]]

^<<v23-18-5,5>>^ Quando as flores da parreira  já tiverem caído, e as uvas estiverem amadurecendo, mas antes do tempo da colheita, Deus podará a parreira com o seu facão, cortará os galhos e os jogará fora.

[[v23-18-6]]

^<<v23-18-6,6>>^ Os corpos dos soldados mortos serão abandonados; no verão, serão comidos pelos urubus, e no inverno os animais selvagens os devorarão.

[[v23-18-7]]

^<<v23-18-7,7>>^ Naquele dia, ofertas serão apresentadas ao Senhor  Todo-Poderoso por um povo corajoso e forte, uma gente alta e de pele lustrosa; um povo de quem o mundo inteiro tem medo e que vive numa região dividida por rios. Eles apresentarão as suas ofertas no monte Sião , no Templo onde o Senhor  Todo-Poderoso é adorado.

'''

xref:023-isaias/023-isaias-017.adoc#v23-17-0[&#60; Capítulo Anterior] | <<v23-18-0,Topo>> | xref:023-isaias/023-isaias-019.adoc#v23-19-0[Próximo Capítulo &#62;]