include::./index.adoc[]

[[v23-58-0]]
=== Isaías, 58
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-58-1]]

^<<v23-58-1,1>>^ O Senhor  Deus diz: "Grite com toda a força, sem parar! Grite alto, como se você fosse trombeta! Anuncie ao meu povo, os descendentes de Jacó, os seus pecados e as suas maldades.

[[v23-58-2]]

^<<v23-58-2,2>>^ De fato, eles me adoram todos os dias e dizem que querem saber qual é a minha vontade, como se fossem um povo que faz o que é direito e que não desobedece às minhas leis . Pedem que eu lhes dê leis justas e estão sempre prontos para me adorar."

[[v23-58-3]]

^<<v23-58-3,3>>^ O povo pergunta a Deus: "Que adianta jejuar, se tu nem notas? Por que passar fome, se não te importas com isso?" O Senhor  responde: "A verdade é que nos dias de jejum vocês cuidam dos seus negócios e exploram os seus empregados.

[[v23-58-4]]

^<<v23-58-4,4>>^ Vocês passam os dias de jejum discutindo e brigando e chegam até a bater uns nos outros. Será que vocês pensam que, quando jejuam assim, eu vou ouvir as suas orações?

[[v23-58-5]]

^<<v23-58-5,5>>^ O que é que eu quero que vocês façam nos dias de jejum? Será que desejo que passem fome, que se curvem como um bambu, que vistam roupa feita de pano grosseiro e se deitem em cima de cinzas? É isso o que vocês chamam de jejum? Acham que um dia de jejum assim me agrada?

[[v23-58-6]]

^<<v23-58-6,6>>^ "Não! Não é esse o jejum que eu quero. Eu quero que soltem aqueles que foram presos injustamente, que tirem de cima deles o peso que os faz sofrer, que ponham em liberdade os que estão sendo oprimidos, que acabem com todo tipo de escravidão.

[[v23-58-7]]

^<<v23-58-7,7>>^ O jejum que me agrada é que vocês repartam a sua comida com os famintos, que recebam em casa os pobres que estão desabrigados, que deem roupas aos que não têm e que nunca deixem de socorrer os seus parentes.

[[v23-58-8]]

^<<v23-58-8,8>>^ "Então a luz da minha salvação brilhará como o sol, e logo vocês todos ficarão curados. O seu Salvador os guiará, e a presença do Senhor  Deus os protegerá por todos os lados.

[[v23-58-9]]

^<<v23-58-9,9>>^ Quando vocês gritarem pedindo socorro, eu os atenderei; pedirão a minha ajuda, e eu direi: ‘Estou aqui!’ "Se acabarem com todo tipo de exploração, com todas as ameaças e xingamentos;

[[v23-58-10]]

^<<v23-58-10,10>>^ se derem de comer aos famintos e socorrerem os necessitados, a luz da minha salvação brilhará, e a escuridão em que vocês vivem ficará igual à luz do meio-dia.

[[v23-58-11]]

^<<v23-58-11,11>>^ Eu, o Senhor , sempre os guiarei; até mesmo no deserto, eu lhes darei de comer e farei com que fiquem sãos e fortes. Vocês serão como um jardim bem-regado, como uma fonte de onde não para de correr água.

[[v23-58-12]]

^<<v23-58-12,12>>^ Em cima dos alicerces antigos, vocês reconstruirão cidades que tinham sido arrasadas. Vocês serão conhecidos como o povo que levantou muralhas de novo, que construiu novamente casas que tinham caído."

[[v23-58-13]]

^<<v23-58-13,13>>^ O Senhor  Deus diz: "Obedeçam às leis  a respeito do sábado; não cuidem dos seus próprios negócios no dia que para mim é sagrado. Considerem o sábado como um dia de festa, o dia santo do Senhor , que deve ser respeitado. Guardem o sábado, descansando em vez de trabalhar; não cuidem dos seus negócios, nem fiquem conversando à toa.

[[v23-58-14]]

^<<v23-58-14,14>>^ Se me obedecerem, eu serei uma fonte de alegria para vocês e farei com que vençam todas as dificuldades; e vocês serão felizes na terra que eu dei ao seu antepassado Jacó. Eu, o Senhor , falei."

'''

xref:023-isaias/023-isaias-057.adoc#v23-57-0[&#60; Capítulo Anterior] | <<v23-58-0,Topo>> | xref:023-isaias/023-isaias-059.adoc#v23-59-0[Próximo Capítulo &#62;]