include::./index.adoc[]

[[v23-38-0]]
=== Isaías, 38
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-38-1]]

^<<v23-38-1,1>>^ Por esse tempo, o rei Ezequias ficou doente e quase morreu. O profeta  Isaías, filho de Amoz, foi visitá-lo e disse: — O Senhor  Deus diz assim: "Ponha as suas coisas em ordem porque você não vai sarar. Apronte-se para morrer."

[[v23-38-2]]

^<<v23-38-2,2>>^ Então Ezequias virou o rosto para a parede e orou assim:

[[v23-38-3]]

^<<v23-38-3,3>>^ — Ó Senhor , lembra que eu tenho te servido com fidelidade e com todo o coração e sempre fiz aquilo que querias que eu fizesse. E chorou amargamente.

[[v23-38-4]]

^<<v23-38-4,4>>^ Aí Deus mandou que Isaías

[[v23-38-5]]

^<<v23-38-5,5>>^ voltasse a falar com Ezequias e lhe dissesse: — Eu, o Senhor , o Deus do seu antepassado Davi, escutei a sua oração e vi as suas lágrimas. Vou deixar que você viva mais quinze anos.

[[v23-38-6]]

^<<v23-38-6,6>>^ Livrarei você e esta cidade de Jerusalém do rei da Assíria e defenderei esta cidade.

[[v23-38-7]]

^<<v23-38-7,7>>^ O Senhor  Deus lhe dará um sinal para provar que vai cumprir a sua promessa.

[[v23-38-8]]

^<<v23-38-8,8>>^ Na escadaria feita pelo rei Acaz, o Senhor  fará com que a sombra volte dez degraus. E a sombra voltou dez degraus.

[[v23-38-9]]

^<<v23-38-9,9>>^ Depois que o rei Ezequias sarou, ele escreveu o seguinte hino de louvor:

[[v23-38-10]]

^<<v23-38-10,10>>^ "Eu pensava que iria morrer na flor da idade, que daqui em diante moraria no mundo dos mortos .

[[v23-38-11]]

^<<v23-38-11,11>>^ Pensava que nesta vida eu nunca mais veria o Senhor , que nunca mais veria outro ser humano.

[[v23-38-12]]

^<<v23-38-12,12>>^ A minha vida foi cortada e terminada como uma barraca de pastores que é desmontada e levada para longe ou como um pedaço de pano que o tecelão corta de uma peça de tecido. Dia e noite eu pensava que Deus já ia acabar comigo.

[[v23-38-13]]

^<<v23-38-13,13>>^ A noite inteira, eu gritava de dor, como se um leão estivesse quebrando os meus ossos. Dia e noite eu pensava que Deus já ia acabar comigo.

[[v23-38-14]]

^<<v23-38-14,14>>^ Eu soltava fracos gemidos de dor como uma andorinha e gemia como uma pomba. Os meus olhos se cansaram de olhar para o céu. Ó Senhor, estou sofrendo! Salva-me!

[[v23-38-15]]

^<<v23-38-15,15>>^ Mas como é que posso reclamar, se foi o próprio Deus quem fez isso comigo? Estou tão aflito, que já não consigo dormir.

[[v23-38-16]]

^<<v23-38-16,16>>^ "Ó Senhor, é por causa das coisas que tu fazes que todos nós vivemos; e eu também estou vivo por causa delas. Dá-me saúde a fim de que eu viva!

[[v23-38-17]]

^<<v23-38-17,17>>^ Eu sei que foi para o meu próprio bem que sofri tanta aflição. Mas tu me salvaste da morte, pois perdoaste todos os meus pecados.

[[v23-38-18]]

^<<v23-38-18,18>>^ No mundo dos mortos, ninguém te agradece, ninguém louva o teu nome; os que estão ali não confiam na tua fidelidade.

[[v23-38-19]]

^<<v23-38-19,19>>^ São os vivos que te louvam, como eu te louvo agora. E os pais dizem aos filhos que todos podem confiar em ti.

[[v23-38-20]]

^<<v23-38-20,20>>^ Tu me salvaste, ó Senhor . Por isso, tocaremos as nossas harpas  e cantaremos louvores a ti; a vida inteira nós te louvaremos no teu Templo."

[[v23-38-21]]

^<<v23-38-21,21>>^ Pois Isaías tinha dito: — Ponham uma pasta de figos em cima da úlcera do rei, e ele ficará bom.

[[v23-38-22]]

^<<v23-38-22,22>>^ E o rei Ezequias tinha perguntado: — Qual será o sinal de que eu poderei ir até o Templo?

'''

xref:023-isaias/023-isaias-037.adoc#v23-37-0[&#60; Capítulo Anterior] | <<v23-38-0,Topo>> | xref:023-isaias/023-isaias-039.adoc#v23-39-0[Próximo Capítulo &#62;]