include::./index.adoc[]

[[v23-52-0]]
=== Isaías, 52
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-52-1]]

^<<v23-52-1,1>>^ Acorde, ó Jerusalém, acorde já e renove as suas forças. Cidade santa, vista os seus vestidos mais caros, pois os pagãos, aquela gente impura , nunca mais morarão com você.

[[v23-52-2]]

^<<v23-52-2,2>>^ Ó Sião , bela cidade, prisioneira e sentada no chão, livre-se das suas correntes; levante-se, sacuda o pó das suas roupas e sente-se no seu trono.

[[v23-52-3]]

^<<v23-52-3,3>>^ O Senhor  diz ao seu povo: — Quando vocês foram levados como escravos para outro país, ninguém pagou nada por vocês; assim também eu não pagarei nada para livrá-los da escravidão.

[[v23-52-4]]

^<<v23-52-4,4>>^ O Senhor  Deus diz: — Primeiro, o meu povo foi para o Egito a fim de morar lá; e eles foram porque quiseram. Mais tarde, a Assíria os levou como escravos e não pagou nada por eles.

[[v23-52-5]]

^<<v23-52-5,5>>^ E o que é que estou vendo agora? A Babilônia fez a mesma coisa: levou o meu povo como escravo sem pagar nada por ele. Aqueles que o estão dominando dão gritos de vitória e me ofendem sem parar.

[[v23-52-6]]

^<<v23-52-6,6>>^ Mas virá o dia em que o meu povo conhecerá o meu nome e saberá que sou eu, o Senhor , quem diz: "Eu estou aqui!"

[[v23-52-7]]

^<<v23-52-7,7>>^ Como é bonito ver um mensageiro correndo pelas montanhas, trazendo notícias de paz, boas notícias de salvação! Ele diz a Sião: "O seu Deus é Rei!"

[[v23-52-8]]

^<<v23-52-8,8>>^ Escutem os gritos dos vigias! Eles gritam de alegria, todos juntos, pois veem com os seus próprios olhos a volta do Senhor  para Sião.

[[v23-52-9]]

^<<v23-52-9,9>>^ Jerusalém arrasada, cante de alegria, pois o Senhor  tem pena do seu povo e vai salvar Jerusalém.

[[v23-52-10]]

^<<v23-52-10,10>>^ Na presença de todas as nações, o Senhor  vai mostrar o seu santo poder. O mundo inteiro verá que foi o nosso Deus quem nos salvou.

[[v23-52-11]]

^<<v23-52-11,11>>^ Meu povo, saia da Babilônia! Saiam todos e não toquem em nada que seja impuro . Que se purifiquem  os que carregam os objetos sagrados do Templo!

[[v23-52-12]]

^<<v23-52-12,12>>^ Desta vez, vocês não sairão com pressa, não precisarão fugir, pois o Senhor  os guiará. O Deus de Israel os protegerá por todos os lados.

[[v23-52-13]]

^<<v23-52-13,13>>^ O Senhor  Deus diz: "Tudo o que o meu servo  fizer dará certo; ele será louvado e receberá muitas homenagens.

[[v23-52-14]]

^<<v23-52-14,14>>^ Muitos ficaram horrorizados quando o viram, pois ele estava tão desfigurado, que nem parecia um ser humano.

[[v23-52-15]]

^<<v23-52-15,15>>^ Mas agora muitos povos ficarão admirados quando o virem, e muitos reis não saberão o que dizer. Pois verão coisas de que ninguém havia falado, entenderão aquilo que nunca tinham ouvido."

'''

xref:023-isaias/023-isaias-051.adoc#v23-51-0[&#60; Capítulo Anterior] | <<v23-52-0,Topo>> | xref:023-isaias/023-isaias-053.adoc#v23-53-0[Próximo Capítulo &#62;]