include::./index.adoc[]

[[v23-14-0]]
=== Isaías, 14
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-14-1]]

^<<v23-14-1,1>>^ Mais uma vez, o Senhor  Deus terá compaixão de Israel e o escolherá para ser o seu próprio povo. Fará com que os israelitas voltem para a sua própria terra, e estrangeiros irão morar ali com eles.

[[v23-14-2]]

^<<v23-14-2,2>>^ Pessoas de várias nações irão com os israelitas para a sua terra, a terra do Senhor , e ali se tornarão escravos e escravas do povo de Israel. Os israelitas terão como escravos aqueles que antigamente eram seus donos e dominarão aqueles que antes os dominavam.

[[v23-14-3]]

^<<v23-14-3,3>>^ Povo de Israel, chegará o dia em que o Senhor  Deus vai livrá-los da escravidão, e assim vocês ficarão livres dos sofrimentos e dos trabalhos pesados que são forçados a fazer.

[[v23-14-4]]

^<<v23-14-4,4>>^ Quando esse dia chegar, zombem do rei da Babilônia, recitando esta poesia: Vejam como desapareceu o rei cruel! Vejam como acabou a sua violência!

[[v23-14-5]]

^<<v23-14-5,5>>^ O Senhor  tirou o poder dos maus; ele quebrou o bastão dos governadores cruéis,

[[v23-14-6]]

^<<v23-14-6,6>>^ que na sua ira maltratavam os povos e na sua fúria perseguiam as nações que haviam conquistado.

[[v23-14-7]]

^<<v23-14-7,7>>^ Agora o mundo inteiro está calmo e em paz, e todos cantam de alegria.

[[v23-14-8]]

^<<v23-14-8,8>>^ Até os ciprestes e os cedros do Líbano estão contentes com a queda do rei da Babilônia e dizem: "Desde o dia em que ele caiu, não apareceu ninguém para nos derrubar."

[[v23-14-9]]

^<<v23-14-9,9>>^ Lá embaixo, no mundo dos mortos , os seus moradores se preparam para receber o rei da Babilônia. As sombras daqueles que eram poderosos na terra acordam, os que foram reis se levantam dos seus tronos.

[[v23-14-10]]

^<<v23-14-10,10>>^ Todos eles dirão ao rei: "Você também perdeu as forças! Agora você é igual a nós!

[[v23-14-11]]

^<<v23-14-11,11>>^ Aonde foi parar a sua vaidade? Onde está agora a música das suas harpas ? Elas estão aqui no mundo dos mortos, onde você vai se deitar em cima de vermes e vai se cobrir com bichos."

[[v23-14-12]]

^<<v23-14-12,12>>^ Rei da Babilônia, brilhante estrela da manhã, você caiu lá do céu! Você, que dominava as nações, foi derrubado no chão!

[[v23-14-13]]

^<<v23-14-13,13>>^ Antigamente você pensava assim: "Subirei até o céu e me sentarei no meu trono, acima das estrelas de Deus. Reinarei lá longe, no Norte, no monte onde os deuses se reúnem.

[[v23-14-14]]

^<<v23-14-14,14>>^ Subirei acima das nuvens mais altas e serei como o Deus Altíssimo."

[[v23-14-15]]

^<<v23-14-15,15>>^ Mas você foi jogado no mundo dos mortos, no abismo  mais profundo.

[[v23-14-16]]

^<<v23-14-16,16>>^ Os mortos vão olhar espantados para você e vão perguntar: "Será este o homem que fazia os reinos tremerem, que fazia o mundo inteiro tremer de medo?

[[v23-14-17]]

^<<v23-14-17,17>>^ Será este o homem que fez o mundo virar um deserto, que arrasava cidades e não deixava os seus prisioneiros voltarem para casa?"

[[v23-14-18]]

^<<v23-14-18,18>>^ Todos os reis do mundo foram sepultados com homenagens, cada um na sua própria sepultura,

[[v23-14-19]]

^<<v23-14-19,19>>^ mas você não foi sepultado. Como se fosse um aborto nojento, o seu corpo foi jogado fora e pisado. Está coberto de corpos de soldados mortos na batalha, daqueles que desceram até a cova cheia de pedras.

[[v23-14-20]]

^<<v23-14-20,20>>^ Você não foi sepultado como os outros reis, pois arrasou o seu próprio país e matou o seu próprio povo. Que morram todos os descendentes desse rei maldito!

[[v23-14-21]]

^<<v23-14-21,21>>^ Por causa da maldade dos seus antepassados, matem logo os seus filhos a fim de que eles nunca venham a governar a terra, nem encham o mundo de cidades.

[[v23-14-22]]

^<<v23-14-22,22>>^ O Senhor  Todo-Poderoso diz: — Vou atacar e arrasar a cidade de Babilônia. Vou acabar com todos: pais e filhos, avós e netos. Sou eu, o Senhor , quem está falando.

[[v23-14-23]]

^<<v23-14-23,23>>^ Farei com que a Babilônia vire um lamaçal, um lugar onde viverão as corujas. Vou varrê-la com a minha vassoura, e ela desaparecerá. Eu, o Senhor  Todo-Poderoso, falei.

[[v23-14-24]]

^<<v23-14-24,24>>^ O Senhor  Todo-Poderoso jurou: "Vou fazer o que resolvi; vou realizar o meu plano.

[[v23-14-25]]

^<<v23-14-25,25>>^ Vou acabar com os assírios que estão na minha terra de Israel, vou pisá-los nas minhas montanhas. Livrarei o meu povo da escravidão, quebrarei as correntes com que os assírios o prenderam e tirarei das suas costas as suas cargas pesadas.

[[v23-14-26]]

^<<v23-14-26,26>>^ É este o plano que tenho para o mundo inteiro; a minha mão está levantada para castigar as nações."

[[v23-14-27]]

^<<v23-14-27,27>>^ O Senhor  Todo-Poderoso resolveu fazer isso; haverá alguém que o faça parar? Ele levantou a mão para castigar; haverá quem a faça abaixar?

[[v23-14-28]]

^<<v23-14-28,28>>^ No ano em que o rei Acaz morreu, veio de Deus esta mensagem:

[[v23-14-29]]

^<<v23-14-29,29>>^ "Povo da Filisteia, não fique alegre por estar quebrada a Assíria, o bastão que os castigava. Pois, quando uma cobra desaparece, vem outra pior, e do ovo de uma cobra sai um dragão voador.

[[v23-14-30]]

^<<v23-14-30,30>>^ Como um pastor cuida das ovelhas, assim eu cuidarei dos pobres do meu povo e farei com que vivam em segurança. Porém farei com que vocês, filisteus, morram de fome; não deixarei nenhum vivo.

[[v23-14-31]]

^<<v23-14-31,31>>^ Chorem e gritem de dor, cidades dos filisteus! Fiquem todas apavoradas! Pois do Norte vem uma nuvem de pó: é um exército que não tem nenhum covarde nas suas fileiras."

[[v23-14-32]]

^<<v23-14-32,32>>^ Que resposta será dada aos mensageiros que vieram da Filisteia? A resposta será esta: "O Senhor  Deus fundou Sião , e ali os pobres do seu povo encontram abrigo."

'''

xref:023-isaias/023-isaias-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-isaias/023-isaias-015.adoc#v23-15-0[Próximo Capítulo &#62;]