include::./index.adoc[]

[[v23-1-0]]
=== Isaías, 1
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v23-1-1]]

^<<v23-1-1,1>>^ São estas as mensagens a respeito de Judá e de Jerusalém que o Senhor  Deus deu a Isaías, filho de Amoz, durante os reinados de Uzias, Jotão, Acaz e Ezequias em Judá.

[[v23-1-2]]

^<<v23-1-2,2>>^ Escutem, ó céus, preste atenção, ó terra, pois o Senhor  Deus falou! Ele disse: "Criei filhos e cuidei deles, mas eles se revoltaram contra mim.

[[v23-1-3]]

^<<v23-1-3,3>>^ O boi conhece o seu dono, e o jumento sabe onde o dono põe o alimento para ele, mas o meu povo não sabe nada, o povo de Israel não entende coisa nenhuma."

[[v23-1-4]]

^<<v23-1-4,4>>^ Ai desse povo mau, dessa gente cheia de pecados! Todos são ruins, todos são perversos. Eles abandonaram o Senhor , rejeitaram o Santo Deus de Israel e viraram as costas para ele.

[[v23-1-5]]

^<<v23-1-5,5>>^ Por que vocês continuam a pecar? Será que querem receber mais castigos? A sua cabeça está ferida, e todos estão desanimados.

[[v23-1-6]]

^<<v23-1-6,6>>^ Da cabeça até os pés, o corpo de vocês está machucado, cheio de ferimentos e de chagas abertas, que não foram lavadas, nem enfaixadas, nem limpadas com azeite.

[[v23-1-7]]

^<<v23-1-7,7>>^ A terra de vocês está arrasada, as cidades foram destruídas pelo fogo. Na presença de vocês, os estrangeiros arrasaram a sua terra, e ela ficou em ruínas. Os estrangeiros acabaram com ela.

[[v23-1-8]]

^<<v23-1-8,8>>^ Só ficou Jerusalém, como se fosse uma barraca de vigia numa plantação de uvas, como uma cabana numa plantação de pepinos ou como uma cidade cercada pelos inimigos.

[[v23-1-9]]

^<<v23-1-9,9>>^ Se o Senhor  Todo-Poderoso não tivesse deixado que alguns de nós vivêssemos, seríamos agora como a cidade de Sodoma, estaríamos destruídos como Gomorra.

[[v23-1-10]]

^<<v23-1-10,10>>^ Autoridades de Jerusalém, escutem o que o Senhor  está dizendo! Moradores da cidade , deem atenção ao ensinamento do nosso Deus!

[[v23-1-11]]

^<<v23-1-11,11>>^ O Senhor  diz: "Eu não quero todos esses sacrifícios que vocês me oferecem. Estou farto de bodes e de animais gordos queimados no altar; estou enjoado do sangue de touros novos, não quero mais carneiros nem cabritos.

[[v23-1-12]]

^<<v23-1-12,12>>^ Quando vocês vêm até a minha presença, quem foi que pediu todo esse corre-corre nos pátios do meu Templo?

[[v23-1-13]]

^<<v23-1-13,13>>^ Não adianta nada me trazerem ofertas; eu odeio o incenso que vocês queimam. Não suporto as Festas da Lua Nova , os sábados e as outras festas religiosas, pois os pecados de vocês estragam tudo isso.

[[v23-1-14]]

^<<v23-1-14,14>>^ As Festas da Lua Nova e os outros dias santos me enchem de nojo; já estou cansado de suportá-los.

[[v23-1-15]]

^<<v23-1-15,15>>^ "Quando vocês levantarem as mãos para orar, eu não olharei para vocês. Ainda que orem muito, eu não os ouvirei, pois os crimes mancharam as mãos de vocês.

[[v23-1-16]]

^<<v23-1-16,16>>^ Lavem-se e purifiquem-se ! Não quero mais ver as suas maldades! Parem de fazer o que é mau

[[v23-1-17]]

^<<v23-1-17,17>>^ e aprendam a fazer o que é bom. Tratem os outros com justiça; socorram os que são explorados, defendam os direitos dos órfãos e protejam as viúvas."

[[v23-1-18]]

^<<v23-1-18,18>>^ O Senhor  Deus diz: "Venham cá, vamos discutir este assunto. Os seus pecados os deixaram manchados de vermelho, manchados de vermelho escuro; mas eu os lavarei, e vocês ficarão brancos como a neve, brancos como a lã.

[[v23-1-19]]

^<<v23-1-19,19>>^ Se forem humildes e me obedecerem, vocês comerão das coisas boas que a terra produz.

[[v23-1-20]]

^<<v23-1-20,20>>^ Mas, se forem rebeldes e desobedientes, serão mortos na guerra. Eu, o Senhor , falei."

[[v23-1-21]]

^<<v23-1-21,21>>^ A cidade de Jerusalém era fiel a Deus, mas agora está agindo como prostituta. Estava cheia de gente boa e honesta, mas agora só ficaram assassinos.

[[v23-1-22]]

^<<v23-1-22,22>>^ Jerusalém, você era como prata pura, porém agora não vale nada; era como o melhor vinho, porém agora é como vinho misturado com água.

[[v23-1-23]]

^<<v23-1-23,23>>^ As suas autoridades são pessoas revoltadas e têm amizade com ladrões. Estão sempre aceitando dinheiro e presentes para torcer a justiça. Não defendem os direitos dos órfãos e não se preocupam com as causas das viúvas.

[[v23-1-24]]

^<<v23-1-24,24>>^ Portanto, escutem o que diz o Senhor , o Deus Todo-Poderoso, o forte Deus de Israel! Ele diz ao seu povo: "Eu me vingarei de vocês, meus inimigos; vou acertar as contas com vocês, meus adversários.

[[v23-1-25]]

^<<v23-1-25,25>>^ Na minha ira , vou castigá-los para que fiquem completamente puros, assim como o metal é purificado pelo fogo.

[[v23-1-26]]

^<<v23-1-26,26>>^ Eu lhes darei autoridades e juízes como os que vocês tinham no passado. Então Jerusalém será chamada de ‘Cidade da Justiça’ e ‘Cidade Fiel’."

[[v23-1-27]]

^<<v23-1-27,27>>^ O Deus justo salvará Sião , salvará todos os seus moradores que se arrependerem.

[[v23-1-28]]

^<<v23-1-28,28>>^ Mas acabará com todos os rebeldes e pecadores, com todos os que abandonam o Senhor .

[[v23-1-29]]

^<<v23-1-29,29>>^ Vocês vão ficar com vergonha das árvores sagradas de que vocês tanto gostavam; vão ficar desiludidos com os jardins sagrados que lhes davam tanto prazer.

[[v23-1-30]]

^<<v23-1-30,30>>^ Vocês se tornarão como árvores de folhas murchas, como um jardim que ninguém rega.

[[v23-1-31]]

^<<v23-1-31,31>>^ Os poderosos serão como a palha, e as suas ações, como uma faísca: eles serão destruídos pelo fogo, e não haverá quem possa salvá-los.

'''

xref:022-canticos/022-canticos-008.adoc#v22-8-0[&#60; Capítulo Anterior] | <<v23-1-0,Topo>> | xref:023-isaias/023-isaias-002.adoc#v23-2-0[Próximo Capítulo &#62;]