include::./index.adoc[]

[[v24-35-0]]
=== Jeremias, 35
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-35-1]]

^<<v24-35-1,1>>^ Quando Jeoaquim, filho de Josias, era rei de Judá, o Senhor  Deus me disse:

[[v24-35-2]]

^<<v24-35-2,2>>^ — Jeremias, vá procurar a família dos recabitas e fale com eles. Depois, leve-os a uma das salas do Templo e lhes ofereça vinho.

[[v24-35-3]]

^<<v24-35-3,3>>^ Então eu fui buscar os recabitas e levei a família inteira ao Templo: Jazanias (filho de outro Jeremias, que era filho de Habazinias) e todos os seus irmãos e filhos. Eu os levei até a sala dos seguidores do profeta  Hanã, homem de Deus. Hanã era filho de Jigdalias. Essa sala ficava perto da sala dos oficiais e em cima da de Maaseias, filho de Salum, importante oficial do Templo.

[[v24-35-4]]

^<<v24-35-4,4>>^ Então eu fui buscar os recabitas e levei a família inteira ao Templo: Jazanias (filho de outro Jeremias, que era filho de Habazinias) e todos os seus irmãos e filhos. Eu os levei até a sala dos seguidores do profeta  Hanã, homem de Deus. Hanã era filho de Jigdalias. Essa sala ficava perto da sala dos oficiais e em cima da de Maaseias, filho de Salum, importante oficial do Templo.

[[v24-35-5]]

^<<v24-35-5,5>>^ Depois, coloquei diante dos recabitas jarras cheias de vinho e copos e disse: — Tomem um pouco de vinho.

[[v24-35-6]]

^<<v24-35-6,6>>^ Mas eles responderam: — Nós não bebemos vinho, pois o nosso antepassado Jonadabe, filho de Recabe, deu a seguinte ordem: "Nunca bebam vinho, nem vocês nem os seus descendentes.

[[v24-35-7]]

^<<v24-35-7,7>>^ Não construam casas, nem cultivem a terra. Não façam, nem comprem plantações de uva. Não tenham lugar certo para morar. Morem em barracas a vida toda para que assim vivam muito tempo nesta terra."

[[v24-35-8]]

^<<v24-35-8,8>>^ E nós temos obedecido a todas as ordens do nosso antepassado Jonadabe, filho de Recabe. Nunca bebemos vinho, nem nós, nem nossas esposas, nem nossos filhos e filhas.

[[v24-35-9]]

^<<v24-35-9,9>>^ Não construímos casas para morar: moramos em barracas. Não temos plantações de uva, nem terras, nem sementes. Temos obedecido a tudo o que o nosso antepassado Jonadabe ordenou.

[[v24-35-10]]

^<<v24-35-10,10>>^ Não construímos casas para morar: moramos em barracas. Não temos plantações de uva, nem terras, nem sementes. Temos obedecido a tudo o que o nosso antepassado Jonadabe ordenou.

[[v24-35-11]]

^<<v24-35-11,11>>^ Mas, quando o rei Nabucodonosor, da Babilônia, invadiu o país, resolvemos vir a Jerusalém para fugir dos exércitos babilônios e sírios. É por isso que estamos vivendo aqui.

[[v24-35-12]]

^<<v24-35-12,12>>^ Então o Senhor  Todo-Poderoso, o Deus de Israel, mandou que eu fosse dizer o seguinte ao povo de Judá e de Jerusalém: — Eu, o Senhor , pergunto: por que vocês não querem me ouvir, nem obedecer às minhas ordens?

[[v24-35-13]]

^<<v24-35-13,13>>^ Então o Senhor  Todo-Poderoso, o Deus de Israel, mandou que eu fosse dizer o seguinte ao povo de Judá e de Jerusalém:

[[v24-35-14]]

^<<v24-35-14,14>>^ Os descendentes de Jonadabe têm obedecido à sua ordem de não beber vinho. E até hoje nenhum deles bebe, pois todos obedecem ao mandamento que ele deu. Mas eu sempre tenho falado a vocês, e vocês não têm obedecido.

[[v24-35-15]]

^<<v24-35-15,15>>^ Tenho sempre mandado todos os meus servos , os profetas, e eles têm ordenado que vocês abandonem os seus maus caminhos e façam o que é certo. Eles avisaram que vocês não deviam adorar, nem servir outros deuses para que assim pudessem continuar a viver na terra que dei a vocês e aos seus antepassados. Mas vocês não quiseram me ouvir, nem obedecer.

[[v24-35-16]]

^<<v24-35-16,16>>^ Os descendentes de Jonadabe têm obedecido ao mandamento que o seu antepassado lhes deu; no entanto, vocês, o meu povo, não me têm obedecido.

'''

xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[&#60; Capítulo Anterior] | <<v24-35-0,Topo>> | xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[Próximo Capítulo &#62;]