include::./index.adoc[]

[[v24-48-0]]
=== Jeremias, 48
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-48-1]]

^<<v24-48-1,1>>^ O Senhor  Todo-Poderoso, o Deus de Israel, disse o seguinte a respeito de Moabe: "Tenham pena do povo da cidade de Nebo porque ela está destruída! Quiriataim foi tomada, a sua fortaleza poderosa foi arrasada, e o seu povo ficou humilhado.

[[v24-48-2]]

^<<v24-48-2,2>>^ Acabou-se a glória  de Moabe. Em Hesbom, o inimigo faz os seus planos: ‘Vamos acabar com a nação de Moabe!’ Exércitos marcharão contra a cidade de Madmém, e nela só restará o silêncio.

[[v24-48-3]]

^<<v24-48-3,3>>^ O povo de Horonaim grita: ‘Tudo está arrasado! Tudo está destruído!’

[[v24-48-4]]

^<<v24-48-4,4>>^ "O país de Moabe ficou em ruínas; as crianças estão chorando.

[[v24-48-5]]

^<<v24-48-5,5>>^ Escutem os seus soluços no caminho que sobe para Luíte, ouçam os seus gritos de aflição na estrada que desce para Horonaim.

[[v24-48-6]]

^<<v24-48-6,6>>^ Ouve-se gente gritando: ‘Depressa! Fujam para salvar a vida! Corram como um jumento selvagem no deserto!’

[[v24-48-7]]

^<<v24-48-7,7>>^ "Moabe, você confiou na sua força e na sua riqueza, mas agora você mesmo será dominado. O seu deus Quemos será levado para fora do país, junto com os seus príncipes e os seus sacerdotes.

[[v24-48-8]]

^<<v24-48-8,8>>^ Nenhuma cidade escapará da destruição; tanto o vale como o planalto ficarão arrasados. Sou eu, o Senhor , quem está falando.

[[v24-48-9]]

^<<v24-48-9,9>>^ Preparem uma pedra para o túmulo de Moabe, pois logo esse país será destruído; as suas cidades ficarão em ruínas, e ninguém mais vai morar lá."

[[v24-48-10]]

^<<v24-48-10,10>>^ Maldito aquele que é relaxado no serviço de Deus! Maldito aquele que guarda a sua espada para não matar!

[[v24-48-11]]

^<<v24-48-11,11>>^ O Senhor  Deus disse: — O povo de Moabe sempre viveu em segurança e nunca foi levado como prisioneiro para fora do seu país. Moabe é como o vinho guardado, que nunca foi agitado, nem derramado de uma vasilha para outra. O seu gosto nunca se estragou, e o seu sabor não mudou.

[[v24-48-12]]

^<<v24-48-12,12>>^ — E assim está chegando o dia em que vou mandar pessoas para derramarem Moabe como se fosse vinho. Essas pessoas despejarão as vasilhas de Moabe e as quebrarão.

[[v24-48-13]]

^<<v24-48-13,13>>^ Então os moabitas ficarão desiludidos com o seu deus Quemos, assim como os israelitas ficaram desiludidos com Betel, um deus em que eles confiavam.

[[v24-48-14]]

^<<v24-48-14,14>>^ Homens de Moabe, como é que vocês dizem que são heróis, que são soldados corajosos na guerra?

[[v24-48-15]]

^<<v24-48-15,15>>^ Moabe e as suas cidades serão destruídos, e os seus melhores moços serão mortos. Sou eu, o Rei, quem está falando. O meu nome é Senhor , o Todo-Poderoso.

[[v24-48-16]]

^<<v24-48-16,16>>^ A desgraça dessa nação está chegando; a sua destruição virá logo.

[[v24-48-17]]

^<<v24-48-17,17>>^ Tenham pena de Moabe, vocês que moram perto, todos vocês que conhecem a sua fama. Digam: "O seu grande poder se acabou; a sua glória  e a sua força não existem mais."

[[v24-48-18]]

^<<v24-48-18,18>>^ Vocês que moram em Dibom, desçam do seu lugar de honra e sentem no chão, no pó. O destruidor de Moabe está aqui; ele arrasará as suas fortalezas.

[[v24-48-19]]

^<<v24-48-19,19>>^ Vocês que vivem em Aroer, fiquem na beira do caminho e esperem; perguntem aos que estão fugindo o que foi que aconteceu.

[[v24-48-20]]

^<<v24-48-20,20>>^ Eles vão responder: "O país de Moabe caiu. Chorem por ele, pois está destruído. Anunciem pelas margens do rio Arnom que Moabe foi arrasado!"

[[v24-48-21]]

^<<v24-48-21,21>>^ As cidades do planalto foram condenadas: Holom, Jasa, Mefaate,

[[v24-48-22]]

^<<v24-48-22,22>>^ Dibom, Nebo, Bete-Diblataim,

[[v24-48-23]]

^<<v24-48-23,23>>^ Quiriataim, Bete-Gamul, Bete-Meão,

[[v24-48-24]]

^<<v24-48-24,24>>^ Queriote e Bosra. Todas as cidades de Moabe, de longe e de perto, foram condenadas.

[[v24-48-25]]

^<<v24-48-25,25>>^ O poder de Moabe foi esmagado, e a sua força foi destruída. Eu, o Senhor , estou falando.

[[v24-48-26]]

^<<v24-48-26,26>>^ E o Senhor  continuou: — Façam com que Moabe fique bêbado, pois se revoltou contra mim, o Senhor  Deus. Moabe rolará no seu próprio vômito, e os outros zombarão dele.

[[v24-48-27]]

^<<v24-48-27,27>>^ Moabe, você lembra de como zombou do povo de Israel? Você tratou esse povo como se tivesse sido preso junto com uma quadrilha de ladrões.

[[v24-48-28]]

^<<v24-48-28,28>>^ — Vocês que vivem em Moabe, abandonem as suas cidades e vão viver no meio das rochas. Façam como as pombas que constroem os seus ninhos na beira dos precipícios.

[[v24-48-29]]

^<<v24-48-29,29>>^ Temos ouvido falar do orgulho de Moabe. Esse povo é orgulhoso, soberbo, vaidoso e cheio de si.

[[v24-48-30]]

^<<v24-48-30,30>>^ Eu, o Senhor , conheço o seu orgulho. Os moabitas se gabam de coisas que não valem nada, coisas que acabam.

[[v24-48-31]]

^<<v24-48-31,31>>^ Por isso, eu chorarei por todo o povo de Moabe e pelo povo de Quir-Heres.

[[v24-48-32]]

^<<v24-48-32,32>>^ Chorarei mais pelo povo de Sibma do que pelo povo de Jazer. Cidade de Sibma, você é como uma parreira ; os seus ramos passam por cima do mar Morto e vão até a cidade de Jazer. Mas agora os inimigos acabaram com as suas plantações de cereais e de uvas.

[[v24-48-33]]

^<<v24-48-33,33>>^ A felicidade e a alegria desapareceram das boas terras de Moabe. Não se faz mais vinho; não há ninguém para fazer vinho e gritar de alegria.

[[v24-48-34]]

^<<v24-48-34,34>>^ — O povo das cidades de Hesbom e Eleal grita, e o seu grito pode ser ouvido até em Jasa. Pode ser ouvido pelos moradores de Zoar e até em Horonaim e Nova Eglate. O próprio riacho Ninrim secou.

[[v24-48-35]]

^<<v24-48-35,35>>^ Eu farei com que o povo de Moabe pare de apresentar ofertas queimadas no alto dos montes e de oferecer sacrifícios  aos seus deuses. Sou eu, o Senhor , quem está falando.

[[v24-48-36]]

^<<v24-48-36,36>>^ — Por isso, o meu coração chora por Moabe e pelo povo de Quir-Heres, como alguém que toca música fúnebre numa flauta; pois tudo o que tinham acabou.

[[v24-48-37]]

^<<v24-48-37,37>>^ Em sinal de tristeza, todos eles raparam a cabeça e cortaram a barba. Todos fizeram cortes nas mãos e vestiram roupa feita de pano grosseiro.

[[v24-48-38]]

^<<v24-48-38,38>>^ Nos terraços de todas as casas e em todas as praças só há choro porque eu quebrei Moabe como um jarro que ninguém quer.

[[v24-48-39]]

^<<v24-48-39,39>>^ Moabe está arrasado! Gritem! A desgraça caiu sobre Moabe. O país está em ruínas, e todas as nações vizinhas caçoam dele. Eu, o Senhor , estou falando.

[[v24-48-40]]

^<<v24-48-40,40>>^ — Eu, o Senhor , prometi que uma nação atacará Moabe e cairá em cima dele como uma águia com as asas abertas.

[[v24-48-41]]

^<<v24-48-41,41>>^ As suas cidades e fortalezas serão tomadas. Naquele dia, os soldados de Moabe terão tanto medo como a mulher que está com dores de parto.

[[v24-48-42]]

^<<v24-48-42,42>>^ Moabe vai ser destruído e não será mais uma nação, pois se revoltou contra mim.

[[v24-48-43]]

^<<v24-48-43,43>>^ Medo, covas e armadilhas esperam pelos moradores de Moabe. Sou eu, o Senhor , quem está falando.

[[v24-48-44]]

^<<v24-48-44,44>>^ Os que fugirem de medo cairão nas covas, e os que conseguirem sair das covas ficarão presos nas armadilhas, pois eu marquei o dia da destruição de Moabe.

[[v24-48-45]]

^<<v24-48-45,45>>^ Outros fogem cansados e procuram proteção na cidade de Hesbom. Mas Hesbom, a cidade que já foi governada pelo rei Seom, está em chamas. O fogo queimou as fronteiras e os picos das montanhas de Moabe, que ama tanto a guerra.

[[v24-48-46]]

^<<v24-48-46,46>>^ Coitado do povo de Moabe! O povo que adorava o deus Quemos foi destruído, e os seus filhos e filhas foram levados como prisioneiros.

[[v24-48-47]]

^<<v24-48-47,47>>^ Porém no futuro farei com que Moabe volte a ser o que era antes. Este é o julgamento do Senhor  Deus a respeito de Moabe.

'''

xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[Próximo Capítulo &#62;]