include::./index.adoc[]

[[v24-7-0]]
=== Jeremias, 7
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-7-1]]

^<<v24-7-1,1>>^ O Senhor  Deus mandou que eu fosse ao portão do Templo, aonde o povo de Judá estava indo para a adoração. Ele mandou que eu ficasse ali e anunciasse ao povo a mensagem do Senhor  Todo-Poderoso, o Deus de Israel. A mensagem era esta: — Mudem de vida, mudem a sua maneira de agir, e eu deixarei que vocês continuem vivendo aqui.

[[v24-7-2]]

^<<v24-7-2,2>>^ O Senhor  Deus mandou que eu fosse ao portão do Templo, aonde o povo de Judá estava indo para a adoração. Ele mandou que eu ficasse ali e anunciasse ao povo a mensagem do Senhor  Todo-Poderoso, o Deus de Israel. A mensagem era esta:

[[v24-7-3]]

^<<v24-7-3,3>>^ O Senhor  Deus mandou que eu fosse ao portão do Templo, aonde o povo de Judá estava indo para a adoração. Ele mandou que eu ficasse ali e anunciasse ao povo a mensagem do Senhor  Todo-Poderoso, o Deus de Israel. A mensagem era esta:

[[v24-7-4]]

^<<v24-7-4,4>>^ Não confiem mais nestas palavras mentirosas: "Nós estamos seguros! Este é o Templo do Senhor , este é o Templo do Senhor , este é o Templo do Senhor !"

[[v24-7-5]]

^<<v24-7-5,5>>^ — Mudem de vida e parem de fazer o que estão fazendo. Sejam honestos uns com os outros.

[[v24-7-6]]

^<<v24-7-6,6>>^ Parem de explorar os estrangeiros, os órfãos e as viúvas. Não matem mais pessoas inocentes neste lugar. E parem de adorar outros deuses, pois isso vai acabar com vocês.

[[v24-7-7]]

^<<v24-7-7,7>>^ Se vocês mudarem de vida, eu deixarei que continuem morando aqui, na terra que dei para sempre aos seus antepassados.

[[v24-7-8]]

^<<v24-7-8,8>>^ — Vejam! Vocês estão confiando em palavras mentirosas e sem valor.

[[v24-7-9]]

^<<v24-7-9,9>>^ Vocês roubam, matam, cometem adultério, juram para encobrir mentiras, oferecem sacrifícios  a Baal  e adoram outros deuses que vocês não conheciam no passado.

[[v24-7-10]]

^<<v24-7-10,10>>^ Fazem coisas que eu detesto, depois vêm e ficam na minha presença, no meu próprio Templo, e dizem: "Nós estamos seguros!"

[[v24-7-11]]

^<<v24-7-11,11>>^ Será que vocês estão pensando que o meu Templo é um esconderijo de ladrões? Eu tenho visto o que vocês estão fazendo. Sou eu, o Senhor , quem está falando.

[[v24-7-12]]

^<<v24-7-12,12>>^ Vão a Siló , o primeiro lugar que escolhi para nele ser adorado, e vejam o que eu fiz ali por causa da maldade de Israel, o meu povo.

[[v24-7-13]]

^<<v24-7-13,13>>^ Vocês têm cometido todos esses pecados de que falei. Eu os avisei muitas e muitas vezes, mas vocês não quiseram me ouvir; e, quando eu chamei, não me responderam. Sou eu, o Senhor , quem está falando.

[[v24-7-14]]

^<<v24-7-14,14>>^ Por isso, a mesma coisa que fiz com Siló vou fazer com este meu Templo em que vocês confiam. O que fiz em Siló vou fazer neste lugar que dei a vocês e aos seus antepassados.

[[v24-7-15]]

^<<v24-7-15,15>>^ Vou expulsar vocês da minha presença como fiz com os seus parentes, o povo do Reino do Norte.

[[v24-7-16]]

^<<v24-7-16,16>>^ Deus disse: — Jeremias, não ore por este povo. Não peça, nem implore em favor deles; não insista comigo, porque eu não atenderei.

[[v24-7-17]]

^<<v24-7-17,17>>^ Será que você não vê o que eles andam fazendo nas cidades de Judá e nas ruas de Jerusalém?

[[v24-7-18]]

^<<v24-7-18,18>>^ As crianças apanham lenha, os homens acendem o fogo, e as mulheres assam bolos para oferecer à deusa que é chamada de "Rainha do Céu". Também derramam bebidas como oferta a outros deuses e fazem isso para me irritar e ferir.

[[v24-7-19]]

^<<v24-7-19,19>>^ Mas será que é a mim que eles estão ferindo? Eu afirmo que não! Eles estão ferindo a si mesmos e vão passar vergonha.

[[v24-7-20]]

^<<v24-7-20,20>>^ Assim eu, o Senhor  Deus, derramarei a minha ira  e o meu furor sobre este lugar. Descarregarei o meu furor sobre as pessoas e os animais e até sobre as árvores e as plantações. E a minha ira será como um fogo que ninguém pode apagar.

[[v24-7-21]]

^<<v24-7-21,21>>^ — Alguns sacrifícios  são completamente queimados sobre o altar, mas a carne de outros sacrifícios vocês têm o direito de comer. Porém eu, o Senhor  Todo-Poderoso, o Deus de Israel, digo que não me importo que vocês comam a carne toda.

[[v24-7-22]]

^<<v24-7-22,22>>^ Quando tirei do Egito os seus antepassados, não dei ordens a respeito do oferecimento de animais que são completamente queimados nem a respeito de outros tipos de sacrifícios.

[[v24-7-23]]

^<<v24-7-23,23>>^ Mas o que ordenei foi que me obedecessem, de modo que eu seria o Deus deles, e eles seriam o meu povo. Disse que vivessem sempre como eu tinha mandado, para que tudo corresse bem para eles.

[[v24-7-24]]

^<<v24-7-24,24>>^ Mas eles não me deram atenção, nem obedeceram. Pelo contrário, fizeram tudo o que o seu coração teimoso e mau queria. Assim, em vez de melhorarem, eles pioraram.

[[v24-7-25]]

^<<v24-7-25,25>>^ Desde o dia em que os seus antepassados saíram do Egito até hoje, tenho sempre mandado todos os meus servos , os profetas , a vocês.

[[v24-7-26]]

^<<v24-7-26,26>>^ Mas vocês não lhes deram atenção, nem obedeceram. Pelo contrário, continuaram teimosos e fizeram ainda pior do que os seus antepassados.

[[v24-7-27]]

^<<v24-7-27,27>>^ — Portanto, Jeremias, você dirá todas essas palavras, mas eles não vão dar atenção; você os chamará, mas eles não vão responder.

[[v24-7-28]]

^<<v24-7-28,28>>^ Você lhes dirá que eles são um povo que não obedece a mim, o Senhor , o Deus deles. São um povo que não aceita ser corrigido. Não existe mais sinceridade; nem se fala mais nisso.

[[v24-7-29]]

^<<v24-7-29,29>>^ Deus disse ainda: "Chore, povo de Jerusalém. Corte os seus cabelos e jogue fora. Cante música triste no alto dos montes, pois eu, o Senhor , estou irado e abandonei o meu povo."

[[v24-7-30]]

^<<v24-7-30,30>>^ — O povo de Judá fez uma coisa que eu acho errada. Eles colocaram os seus ídolos, que eu detesto, no meu Templo e o mancharam. Sou eu, o Senhor , quem está falando.

[[v24-7-31]]

^<<v24-7-31,31>>^ Construíram um altar que foi chamado de Tofete, no vale de Ben-Hinom, e ali queimam os seus filhos e filhas como sacrifício . Eu não dei ordem para isso e nunca pensei nisso.

[[v24-7-32]]

^<<v24-7-32,32>>^ Portanto, certamente virá o tempo em que esse lugar não será mais chamado de Tofete nem de vale de Ben-Hinom, mas de "vale da Matança". Vão sepultar gente em Tofete por não haver outro lugar.

'''

xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[&#60; Capítulo Anterior] | <<v24-7-0,Topo>> | xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[Próximo Capítulo &#62;]