include::./index.adoc[]

[[v24-40-0]]
=== Jeremias, 40
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-40-1]]

^<<v24-40-1,1>>^ O Senhor  Deus falou comigo outra vez depois que o comandante-geral Nebuzaradã me havia posto em liberdade na cidade de Ramá. Eu tinha sido acorrentado, junto com todo o povo de Jerusalém e de Judá que estava sendo levado como prisioneiro para a Babilônia.

[[v24-40-2]]

^<<v24-40-2,2>>^ O comandante-geral me chamou de lado e disse: — O Senhor , seu Deus, ameaçou destruir esta terra

[[v24-40-3]]

^<<v24-40-3,3>>^ e agora fez o que tinha dito. Tudo isso aconteceu porque o seu povo pecou contra o Senhor  e não lhe obedeceu.

[[v24-40-4]]

^<<v24-40-4,4>>^ Agora, estou tirando as correntes dos seus pulsos e pondo você em liberdade. Se quiser vir comigo para a Babilônia, venha, e eu cuidarei bem de você. Mas, se não quiser, não venha. Você pode ficar em qualquer lugar deste país. Vá para onde quiser e achar melhor.

[[v24-40-5]]

^<<v24-40-5,5>>^ Mas, como eu estava demorando a me decidir, Nebuzaradã me disse: — Volte e fique com Gedalias, filho de Aicã e neto de Safã. O rei da Babilônia colocou Gedalias como governador das cidades de Judá. Você pode ficar com ele e viver no meio do povo ou então ir para onde achar melhor. Nebuzaradã me deu mantimentos e um presente e deixou que eu fosse embora.

[[v24-40-6]]

^<<v24-40-6,6>>^ Então fui e fiquei com Gedalias, em Mispa. E ali passei a viver no meio do povo que tinha ficado na terra de Judá.

[[v24-40-7]]

^<<v24-40-7,7>>^ Alguns oficiais de Judá e os seus soldados, que estavam no campo, não haviam se entregado. Eles ouviram falar que o rei da Babilônia tinha posto Gedalias, filho de Aicã, como governador do país e como responsável por todos aqueles que não haviam sido levados como prisioneiros para a Babilônia. Só os mais pobres ficaram no país.

[[v24-40-8]]

^<<v24-40-8,8>>^ Então Ismael, filho de Netanias, e Joanã, filho de Careá, e Seraías, filho de Tanumete, e os filhos de Efai, da cidade de Netofa, e Jezanias, de Maacá, foram com os seus homens até Mispa a fim de falar com Gedalias.

[[v24-40-9]]

^<<v24-40-9,9>>^ E Gedalias lhes disse: — Eu dou a minha palavra que vocês não precisam ter medo de serem dominados pelos babilônios. Fiquem morando nesta terra, trabalhem para o rei da Babilônia, e tudo correrá bem para vocês.

[[v24-40-10]]

^<<v24-40-10,10>>^ Eu mesmo vou ficar em Mispa e, quando os babilônios chegarem, serei o representante de vocês. Vocês podem colher e guardar frutas, armazenar vinho e azeite e morar nas cidades que vocês conquistaram.

[[v24-40-11]]

^<<v24-40-11,11>>^ Da mesma forma, todos os judeus que estavam em Moabe, Amom, Edom e em outros países ouviram dizer que o rei da Babilônia tinha deixado que alguns judeus ficassem vivendo em Judá. Souberam também que ele havia posto Gedalias como governador deles.

[[v24-40-12]]

^<<v24-40-12,12>>^ Aí os judeus saíram de todos os lugares onde estavam espalhados e voltaram para a terra de Judá. Eles foram até Mispa, onde vivia Gedalias, e fizeram muito vinho e colheram muitas frutas.

[[v24-40-13]]

^<<v24-40-13,13>>^ Depois disso, Joanã, filho de Careá, e os chefes dos soldados que não se haviam entregado aos babilônios foram a Mispa, onde Gedalias estava,

[[v24-40-14]]

^<<v24-40-14,14>>^ e lhe disseram: — Sabe que Baalis, rei de Amom, mandou Ismael, filho de Netanias, matar o senhor? Mas Gedalias não acreditou.

[[v24-40-15]]

^<<v24-40-15,15>>^ Então Joanã lhe disse o seguinte, em particular: — Deixe que eu mate Ismael, e ninguém vai ficar sabendo quem o matou. Por que deixar que ele mate o senhor? Se isso acontecer, todos os judeus que se ajuntaram em volta do senhor se espalharão, e isso será uma desgraça para todo o povo que ficou em Judá.

[[v24-40-16]]

^<<v24-40-16,16>>^ Mas Gedalias respondeu: — Não mate Ismael! O que você está dizendo a respeito dele é mentira.

'''

xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[&#60; Capítulo Anterior] | <<v24-40-0,Topo>> | xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[Próximo Capítulo &#62;]