include::./index.adoc[]

[[v24-42-0]]
=== Jeremias, 42
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-42-1]]

^<<v24-42-1,1>>^ Então todos os chefes do exército e Joanã, filho de Careá, e Azarias , filho de Hosaías, e pessoas de todas as classes

[[v24-42-2]]

^<<v24-42-2,2>>^ vieram falar comigo. Disseram o seguinte: — Por favor, Jeremias, atenda o nosso pedido: ore ao Senhor  Deus por nós e por estes que foram deixados nesta terra. Antes, nós éramos muitos, mas agora somos poucos, como você está vendo.

[[v24-42-3]]

^<<v24-42-3,3>>^ Ore ao Senhor , seu Deus, para que mostre o caminho que devemos seguir e o que devemos fazer.

[[v24-42-4]]

^<<v24-42-4,4>>^ Eu respondi: — Está bem! Vou orar ao Senhor , o Deus de vocês, como pediram. Depois, eu contarei o que ele disser. Não esconderei nada de vocês.

[[v24-42-5]]

^<<v24-42-5,5>>^ Então eles disseram: — Que o Senhor  Deus seja uma testemunha fiel e verdadeira contra nós, se não obedecermos a todas as ordens que ele nos der por meio de você!

[[v24-42-6]]

^<<v24-42-6,6>>^ Gostemos ou não dessas ordens, nós obedeceremos ao Senhor , nosso Deus, com quem você vai falar em nosso favor. Se obedecermos ao Senhor , tudo correrá bem para nós.

[[v24-42-7]]

^<<v24-42-7,7>>^ Dez dias depois, o Senhor  Deus falou comigo.

[[v24-42-8]]

^<<v24-42-8,8>>^ Aí chamei Joanã, filho de Careá, e todos os chefes do exército que estavam com ele, e todo o povo — pessoas de todas as classes —

[[v24-42-9]]

^<<v24-42-9,9>>^ e disse: — O Senhor , o Deus de Israel, a quem vocês me pediram que orasse, disse o seguinte:

[[v24-42-10]]

^<<v24-42-10,10>>^ "Se vocês quiserem continuar a viver nesta terra, eu edificarei a nação e não a destruirei; plantarei e não arrancarei. A destruição que fiz cair sobre vocês me deixou muito triste.

[[v24-42-11]]

^<<v24-42-11,11>>^ Não tenham mais medo do rei da Babilônia, pois estou com vocês. Eu os salvarei e os livrarei do poder dele. Sou eu, o Senhor , quem está falando.

[[v24-42-12]]

^<<v24-42-12,12>>^ Terei pena de vocês e farei com que ele também tenha e deixe que vivam nesta terra."

[[v24-42-13]]

^<<v24-42-13,13>>^ — Mas vocês que ficaram em Judá não devem desobedecer ao Senhor , seu Deus, mas devem concordar em morar nesta terra. Não digam assim: "Nós vamos morar no Egito, onde não teremos mais de enfrentar a guerra, nem ouvir o toque de atacar, nem passar fome." Se vocês falarem assim, então o Senhor  Todo-Poderoso, o Deus de Israel, dirá: "Se vocês estão mesmo resolvidos a viver no Egito,

[[v24-42-14]]

^<<v24-42-14,14>>^ — Mas vocês que ficaram em Judá não devem desobedecer ao Senhor , seu Deus, mas devem concordar em morar nesta terra. Não digam assim: "Nós vamos morar no Egito, onde não teremos mais de enfrentar a guerra, nem ouvir o toque de atacar, nem passar fome." Se vocês falarem assim, então o Senhor  Todo-Poderoso, o Deus de Israel, dirá: "Se vocês estão mesmo resolvidos a viver no Egito,

[[v24-42-15]]

^<<v24-42-15,15>>^ — Mas vocês que ficaram em Judá não devem desobedecer ao Senhor , seu Deus, mas devem concordar em morar nesta terra. Não digam assim: "Nós vamos morar no Egito, onde não teremos mais de enfrentar a guerra, nem ouvir o toque de atacar, nem passar fome." Se vocês falarem assim, então o Senhor  Todo-Poderoso, o Deus de Israel, dirá: "Se vocês estão mesmo resolvidos a viver no Egito,

[[v24-42-16]]

^<<v24-42-16,16>>^ então vão ter de enfrentar a guerra, de que vocês têm medo. A fome que vocês temem vai segui-los, e vocês morrerão no Egito.

[[v24-42-17]]

^<<v24-42-17,17>>^ Todos os que estiverem resolvidos a viver no Egito morrerão na guerra, ou de fome, ou de doença. Não sobrará ninguém; ninguém escapará da desgraça que farei cair sobre vocês."

[[v24-42-18]]

^<<v24-42-18,18>>^ — O Senhor  Todo-Poderoso, o Deus de Israel, diz: "Se vocês forem para o Egito, a minha ira  e o meu furor cairão sobre vocês como caíram sobre o povo de Jerusalém. Vocês vão se tornar uma coisa horrível e espantosa. Os outros zombarão de vocês e usarão o seu nome para rogar pragas. E vocês nunca mais verão este lugar."

[[v24-42-19]]

^<<v24-42-19,19>>^ E eu disse ainda: — O Senhor  Deus disse que vocês, que ficaram em Judá, não devem ir para o Egito. Por isso, agora eu os aviso:

[[v24-42-20]]

^<<v24-42-20,20>>^ Vocês estão cometendo um erro que pode lhes custar a vida. Vocês me mandaram falar com o Senhor , nosso Deus, e me disseram: "Ore ao Senhor  por nós. Depois, conte-nos tudo o que ele disser que devemos fazer, e nós faremos."

'''

xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[Próximo Capítulo &#62;]