include::./index.adoc[]

[[v24-10-0]]
=== Jeremias, 10
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-10-1]]

^<<v24-10-1,1>>^ Povo de Israel, escutem a mensagem de Deus, o Senhor , para vocês!

[[v24-10-2]]

^<<v24-10-2,2>>^ Ele diz: "Não sigam os costumes de outras nações. Elas podem ficar espantadas quando aparecem coisas estranhas no céu, mas vocês não devem se assustar.

[[v24-10-3]]

^<<v24-10-3,3>>^ A religião dessa gente não vale nada. Cortam uma árvore na floresta, e um artista, com as suas ferramentas, faz um ídolo.

[[v24-10-4]]

^<<v24-10-4,4>>^ Então o enfeitam com prata e ouro e o firmam com pregos para que não caia aos pedaços.

[[v24-10-5]]

^<<v24-10-5,5>>^ Esses ídolos não podem falar: são como um espantalho numa plantação de pepinos. Eles têm de ser carregados porque não podem andar. Não tenham medo deles: não podem fazer mal, nem podem fazer bem."

[[v24-10-6]]

^<<v24-10-6,6>>^ Ó Senhor  Deus, não há ninguém igual a ti. Tu és grande, e o teu nome é poderoso.

[[v24-10-7]]

^<<v24-10-7,7>>^ Quem não te respeitará, ó Rei de todas as nações? Tu mereces todo o respeito. Não há ninguém como tu entre todos os sábios das nações.

[[v24-10-8]]

^<<v24-10-8,8>>^ Todos os seus sábios são ignorantes e tolos. Será que os ídolos de madeira podem lhes ensinar alguma coisa?

[[v24-10-9]]

^<<v24-10-9,9>>^ Esses ídolos são folheados com prata da Espanha e com ouro de Ufaz; tudo é trabalho de artistas. Os seus vestidos são roxos e vermelhos, feitos por tecelões habilidosos.

[[v24-10-10]]

^<<v24-10-10,10>>^ Mas o Senhor  é o Deus verdadeiro; ele é o Deus vivo, o Rei eterno. Quando o Senhor  fica irado , a terra treme; as nações não podem suportar a sua ira.

[[v24-10-11]]

^<<v24-10-11,11>>^ Digam às nações que os deuses, que não fizeram a terra e o céu, serão destruídos. Eles desaparecerão completamente da terra.

[[v24-10-12]]

^<<v24-10-12,12>>^ Pelo seu poder, o Senhor  Deus fez a terra; com a sua sabedoria, ele criou o mundo e, com a sua inteligência, estendeu o céu como se fosse uma coberta.

[[v24-10-13]]

^<<v24-10-13,13>>^ Quando Deus dá ordem, as águas rugem no céu. Ele manda as nuvens subirem dos fins da terra. Ele faz o raio para a chuva e manda o vento sair dos seus depósitos.

[[v24-10-14]]

^<<v24-10-14,14>>^ Diante disso, todos os seres humanos são tolos e ignorantes. Todos os artistas ficam envergonhados com os ídolos que fazem, pois são deuses falsos, deuses que não têm vida.

[[v24-10-15]]

^<<v24-10-15,15>>^ Não valem nada; são uma tapeação. Serão destruídos quando o Senhor  vier castigá-los.

[[v24-10-16]]

^<<v24-10-16,16>>^ O Deus de Jacó não é assim; foi ele quem fez todas as coisas e escolheu Israel para ser o seu povo. O seu nome é Senhor , o Todo-Poderoso.

[[v24-10-17]]

^<<v24-10-17,17>>^ Moradores de Jerusalém, a cidade está cercada pelos inimigos! Peguem as suas trouxas,

[[v24-10-18]]

^<<v24-10-18,18>>^ porque agora o Senhor vai jogar vocês para fora desta terra a fim de que venham a ter juízo. Sou eu, o Senhor , quem está falando.

[[v24-10-19]]

^<<v24-10-19,19>>^ O povo de Jerusalém grita: "Estamos gravemente feridos! As nossas feridas não querem sarar! E nós pensávamos que podíamos aguentar estas coisas!

[[v24-10-20]]

^<<v24-10-20,20>>^ As nossas barracas estão destruídas, e as cordas que as seguravam arrebentaram. Os nossos filhos partiram, foram todos embora. Não sobrou ninguém para armar as nossas barracas de novo, e não há ninguém para colocar as cortinas."

[[v24-10-21]]

^<<v24-10-21,21>>^ Eu respondi: "As autoridades são tolas: não pedem que o Senhor  Deus as guie. Foi por isso que elas fracassaram, e o nosso povo foi espalhado.

[[v24-10-22]]

^<<v24-10-22,22>>^ Escutem! Acabam de chegar notícias! Há uma grande agitação num país do Norte. O seu exército vai fazer com que as cidades de Judá virem um deserto, um lugar onde vivem os lobos."

[[v24-10-23]]

^<<v24-10-23,23>>^ Ó Senhor  Deus, eu sei que o ser humano não é dono do seu futuro; ninguém pode controlar o que acontece na sua vida.

[[v24-10-24]]

^<<v24-10-24,24>>^ Ó Senhor , corrige o nosso povo, mas não sejas duro demais. Não nos castigues quando estiveres irado porque aí acabarias com toda a nossa gente.

[[v24-10-25]]

^<<v24-10-25,25>>^ Derrama a tua ira sobre as nações que não te adoram, sobre os povos que te rejeitam. Pois mataram a nós, os descendentes de Jacó, e arrasaram o nosso país.

'''

xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[&#60; Capítulo Anterior] | <<v24-10-0,Topo>> | xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[Próximo Capítulo &#62;]