include::./index.adoc[]

[[v24-37-0]]
=== Jeremias, 37
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-37-1]]

^<<v24-37-1,1>>^ O rei Nabucodonosor, da Babilônia, pôs Zedequias, filho de Josias, como rei na terra de Judá, no lugar de Joaquim, filho de Jeoaquim.

[[v24-37-2]]

^<<v24-37-2,2>>^ Mas nem Zedequias, nem as autoridades, nem o povo obedeceram à mensagem de Deus, que eu, o profeta  Jeremias, lhes entreguei.

[[v24-37-3]]

^<<v24-37-3,3>>^ O rei Zedequias mandou que Jucal, filho de Selemias, e o sacerdote Sofonias, filho de Maaseias, fossem falar comigo. Eles disseram: — Por favor, Jeremias, ore ao Senhor , nosso Deus, por nós.

[[v24-37-4]]

^<<v24-37-4,4>>^ Eu ainda não tinha sido preso e andava livremente no meio do povo.

[[v24-37-5]]

^<<v24-37-5,5>>^ Nesse tempo, o exército egípcio havia saído do Egito. E, quando os babilônios que estavam cercando Jerusalém souberam disso, foram embora.

[[v24-37-6]]

^<<v24-37-6,6>>^ Então o Senhor , o Deus de Israel, me mandou dizer o seguinte a Zedequias, rei de Judá: — O exército egípcio, que vem vindo para socorrer você, vai voltar para o Egito.

[[v24-37-7]]

^<<v24-37-7,7>>^ Então o Senhor , o Deus de Israel, me mandou dizer o seguinte a Zedequias, rei de Judá:

[[v24-37-8]]

^<<v24-37-8,8>>^ Aí os babilônios voltarão para atacar esta cidade. Eles vão conquistá-la e pôr fogo nela.

[[v24-37-9]]

^<<v24-37-9,9>>^ Eu, o Senhor , lhes dou este aviso: não se enganem, pensando que os babilônios não vão voltar. Eles voltarão.

[[v24-37-10]]

^<<v24-37-10,10>>^ Ainda que vocês derrotassem todo o exército da Babilônia, que está atacando, e ainda que desse exército sobrassem apenas homens feridos, deitados nas suas barracas, isso não adiantaria nada. Pois mesmo assim esses homens se levantariam e poriam fogo nesta cidade.

[[v24-37-11]]

^<<v24-37-11,11>>^ As tropas dos babilônios se retiraram de Jerusalém porque o exército egípcio estava chegando.

[[v24-37-12]]

^<<v24-37-12,12>>^ Nesse tempo, eu resolvi sair de Jerusalém e ir ao território da tribo  de Benjamim para receber certa propriedade, que era parte de uma herança.

[[v24-37-13]]

^<<v24-37-13,13>>^ Ao chegar ao Portão de Benjamim, o chefe da guarda, chamado Jerias, que era filho de Selemias e neto de Hananias, me fez parar e disse: — Você está fugindo para o lado dos babilônios!

[[v24-37-14]]

^<<v24-37-14,14>>^ — Isso é mentira! — respondi. — Eu não estou fugindo para o lado dos babilônios! Mas Jerias não quis me ouvir. Ele me prendeu e me levou às autoridades.

[[v24-37-15]]

^<<v24-37-15,15>>^ Elas ficaram furiosas comigo e me deram uma surra. Em seguida, me prenderam na casa de Jônatas, escrivão do rei. Essa casa tinha sido transformada em prisão.

[[v24-37-16]]

^<<v24-37-16,16>>^ Aí me puseram numa cela cavada na terra, e eu fiquei ali muito tempo.

[[v24-37-17]]

^<<v24-37-17,17>>^ Depois, o rei Zedequias mandou me buscar. Quando cheguei ao palácio, ele me perguntou em segredo: — Jeremias, você recebeu alguma mensagem de Deus, o Senhor ? — Sim! Recebi! O senhor, ó rei, será entregue nas mãos do rei da Babilônia.

[[v24-37-18]]

^<<v24-37-18,18>>^ Então aproveitei para perguntar a Zedequias: — Qual foi o crime que cometi contra o senhor, ó rei, ou contra as autoridades, ou contra este povo, para que me pusessem na cadeia?

[[v24-37-19]]

^<<v24-37-19,19>>^ Onde estão os seus profetas que lhe diziam que o rei da Babilônia não ia atacar nem o senhor nem este país?

[[v24-37-20]]

^<<v24-37-20,20>>^ Portanto, ó rei, meu senhor, agora peço que faça o que vou pedir. Por favor, não me mande de volta para a casa do seu escrivão Jônatas, pois, se eu voltar, vou acabar morrendo ali.

'''

xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[&#60; Capítulo Anterior] | <<v24-37-0,Topo>> | xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[Próximo Capítulo &#62;]