include::./index.adoc[]

[[v24-33-0]]
=== Jeremias, 33
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-33-1]]

^<<v24-33-1,1>>^ Enquanto eu ainda estava preso no pátio da guarda, o Senhor  Deus falou mais uma vez comigo. Ele disse:

[[v24-33-2]]

^<<v24-33-2,2>>^ — Quem está falando é o Senhor , que fez a terra, lhe deu forma e a colocou no lugar. O seu nome é Senhor .

[[v24-33-3]]

^<<v24-33-3,3>>^ E Deus continuou: — Jeremias, se você me chamar, eu responderei e lhe contarei coisas misteriosas e maravilhosas que você não conhece.

[[v24-33-4]]

^<<v24-33-4,4>>^ Eu, o Senhor , o Deus de Israel, afirmo que as casas de Jerusalém e o palácio real de Judá serão derrubados quando os babilônios construírem rampas de terra para atacar a cidade.

[[v24-33-5]]

^<<v24-33-5,5>>^ Alguns homens lutarão contra os babilônios, mas estes encherão as casas com os corpos daqueles que vou matar na minha ira  e no meu furor. Eu abandonei esta cidade por causa das maldades do seu povo.

[[v24-33-6]]

^<<v24-33-6,6>>^ Mas eu curarei esta cidade e o seu povo e novamente lhe darei saúde. E farei com que tenha tempos de paz e segurança.

[[v24-33-7]]

^<<v24-33-7,7>>^ Trarei progresso para o povo de Judá e de Israel e construirei tudo de novo, como era antes.

[[v24-33-8]]

^<<v24-33-8,8>>^ Eu os purificarei de todos os pecados que cometeram e perdoarei as suas maldades e a sua revolta contra mim.

[[v24-33-9]]

^<<v24-33-9,9>>^ Jerusalém será para mim um motivo de alegria, de honra e de orgulho. E todas as nações do mundo vão tremer de medo quando ouvirem falar das boas coisas que estou fazendo para o povo de Jerusalém e do progresso que estou trazendo para esta cidade.

[[v24-33-10]]

^<<v24-33-10,10>>^ O Senhor  Deus disse: — Andam dizendo que este lugar é como um deserto, sem gente e sem animais. É verdade que as cidades de Judá e as ruas de Jerusalém estão vazias, sem gente e sem animais. Porém nesses lugares vocês ouvirão de novo

[[v24-33-11]]

^<<v24-33-11,11>>^ gritos de alegria e de felicidade e o barulho alegre das festas de casamento. Vocês vão ouvir pessoas cantando e trazendo ofertas de gratidão ao meu Templo. Elas cantarão assim: "Deem graças ao Senhor  Todo-Poderoso porque ele é bom, e o seu amor dura para sempre." Eu farei com que nesta terra haja tanta prosperidade como antes. Eu, o Senhor , estou falando.

[[v24-33-12]]

^<<v24-33-12,12>>^ O Senhor  Todo-Poderoso disse: — Nesta terra, que é um deserto sem gente e sem animais, ainda haverá pastos para onde os pastores poderão trazer os seus rebanhos.

[[v24-33-13]]

^<<v24-33-13,13>>^ Os pastores ainda contarão as suas ovelhas nas cidades das montanhas, nas cidades das planícies de Judá e da região sul, na terra de Benjamim, nos povoados em volta de Jerusalém e nas cidades de Judá. Eu, o Senhor , estou falando.

[[v24-33-14]]

^<<v24-33-14,14>>^ O Senhor  disse ainda: — Está chegando o tempo em que vou cumprir a promessa que fiz ao povo de Israel e de Judá.

[[v24-33-15]]

^<<v24-33-15,15>>^ Nesse dia e nesse tempo, farei surgir um verdadeiro descendente de Davi, e ele fará nesta terra o que é direito e justo.

[[v24-33-16]]

^<<v24-33-16,16>>^ Quando esse dia chegar, o povo de Judá será salvo, e o povo de Israel viverá em segurança. E eles vão dar a Jerusalém este nome: " Senhor , nossa Salvação".

[[v24-33-17]]

^<<v24-33-17,17>>^ Eu, o Senhor , prometo que sempre haverá um descendente de Davi para reinar em Israel.

[[v24-33-18]]

^<<v24-33-18,18>>^ E sempre haverá sacerdotes da tribo  de Levi para estar na minha presença e para trazer ofertas a serem completamente queimadas, ofertas de cereais e sacrifícios  de animais.

[[v24-33-19]]

^<<v24-33-19,19>>^ O Senhor  Deus me disse o seguinte:

[[v24-33-20]]

^<<v24-33-20,20>>^ — É impossível quebrar as leis  que fiz para que o dia e a noite venham sempre um depois do outro.

[[v24-33-21]]

^<<v24-33-21,21>>^ Assim também é impossível quebrar a aliança  que fiz com o meu servo  Davi, isto é, que ele sempre terá um descendente que seja rei. Também não posso quebrar a aliança que fiz com os sacerdotes da tribo de Levi, que me servem no Templo.

[[v24-33-22]]

^<<v24-33-22,22>>^ Eu aumentarei muito os descendentes do meu servo Davi e os sacerdotes da tribo de Levi. Aumentarei tanto, que será tão impossível contá-los como é impossível contar as estrelas do céu ou os grãos de areia da praia.

[[v24-33-23]]

^<<v24-33-23,23>>^ O Senhor  me perguntou:

[[v24-33-24]]

^<<v24-33-24,24>>^ — Jeremias, você sabe que andam dizendo que rejeitei Israel e Judá, as duas famílias que eu havia escolhido? Assim desprezam o meu povo e não o consideram mais como uma nação.

[[v24-33-25]]

^<<v24-33-25,25>>^ Mas eu, o Senhor , digo que fiz leis para o dia e a noite e leis que controlam a terra e o céu.

[[v24-33-26]]

^<<v24-33-26,26>>^ E, assim como mantenho essas leis, também manterei a aliança que fiz com os descendentes de Jacó e com o meu servo Davi. Escolherei um descendente de Davi para governar os descendentes de Abraão, de Isaque e de Jacó. Farei com que o meu povo prospere novamente e terei compaixão dele.

'''

xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[Próximo Capítulo &#62;]