include::./index.adoc[]

[[v24-15-0]]
=== Jeremias, 15
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-15-1]]

^<<v24-15-1,1>>^ Então o Senhor  Deus me disse: — Mesmo que Moisés e Samuel estivessem aqui implorando, eu não teria dó deste povo. Mande essa gente embora. Que sumam da minha frente!

[[v24-15-2]]

^<<v24-15-2,2>>^ Quando perguntarem para onde devem ir, responda que eu disse isto: "Alguns estão condenados a morrer de doença — assim será! Outros estão condenados a morrer na guerra — assim será! Alguns estão condenados a morrer de fome — assim será! Outros estão condenados a ser levados como prisioneiros — assim será!"

[[v24-15-3]]

^<<v24-15-3,3>>^ — Eu, o Senhor , resolvi que vão acontecer estas quatro coisas horríveis: eles morrerão na guerra, os cães arrastarão os seus corpos, as aves os comerão, e os animais selvagens devorarão as sobras.

[[v24-15-4]]

^<<v24-15-4,4>>^ Farei com que todos os povos do mundo olhem para eles com horror por causa daquilo que Manassés, filho de Ezequias, fez em Jerusalém quando era rei de Judá.

[[v24-15-5]]

^<<v24-15-5,5>>^ Deus diz: "Quem terá dó de vocês, moradores de Jerusalém? Quem vai se preocupar com vocês? Quem vai parar um pouco para perguntar como vocês estão passando?

[[v24-15-6]]

^<<v24-15-6,6>>^ Vocês me rejeitaram e viraram as costas para mim. Aí levantei a mão e esmaguei vocês porque estava cansado de perdoar. Sou eu, o Senhor , quem está falando.

[[v24-15-7]]

^<<v24-15-7,7>>^ "Em todas as cidades desta terra, eu os joguei contra o vento como se faz com o trigo para separá-lo da palha. Eu destruí vocês, o meu povo, e matei os seus filhos porque vocês não abandonaram os seus maus caminhos.

[[v24-15-8]]

^<<v24-15-8,8>>^ Fiz com que houvesse entre vocês mais viúvas do que os grãos de areia da praia do mar. Matei os seus filhos na flor da idade e fiz as mães deles sofrerem. De repente, fiz cair sobre eles aflição e terror.

[[v24-15-9]]

^<<v24-15-9,9>>^ A mãe que perdeu os seus sete filhos desmaiou, respirando com dificuldade. Para ela, o dia virou noite; ela se sente infeliz e vive desesperada. Vou deixar que os inimigos matem todos vocês que ainda estão vivos. Eu, o Senhor , estou falando."

[[v24-15-10]]

^<<v24-15-10,10>>^ Eu disse: — Como é dura a minha vida! Por que a minha mãe me pôs no mundo? Eu tenho de discutir e brigar com toda a gente desta terra. Não emprestei dinheiro, nem tomei emprestado, e mesmo assim todos me amaldiçoam.

[[v24-15-11]]

^<<v24-15-11,11>>^ Ó Senhor  Deus, se eu não te servi bem e se não te pedi em favor dos meus inimigos quando estavam passando dificuldades e aflições, então que as maldições deles se cumpram.

[[v24-15-12]]

^<<v24-15-12,12>>^ Ninguém pode quebrar o ferro, especialmente o ferro do Norte, que é misturado com bronze.

[[v24-15-13]]

^<<v24-15-13,13>>^ Deus me disse: — Jeremias, vou mandar que os inimigos carreguem as riquezas e os tesouros do meu povo como castigo pelos pecados cometidos em toda esta terra.

[[v24-15-14]]

^<<v24-15-14,14>>^ Farei com que sejam escravos dos seus inimigos, numa terra que não conhecem, pois a minha ira  é como um fogo que ficará sempre queimando.

[[v24-15-15]]

^<<v24-15-15,15>>^ Então eu respondi: — Ó Senhor , tu és que sabes. Lembra de mim e ajuda-me. Vinga-me daqueles que me perseguem. Não tenhas paciência com os meus inimigos para que eles não me matem. Lembra que é por causa de ti que eles me insultam.

[[v24-15-16]]

^<<v24-15-16,16>>^ Tu falaste comigo, e eu prestei atenção em cada palavra. Ó Senhor , Deus Todo-Poderoso, eu sou teu, e por isso as tuas palavras encheram o meu coração de alegria e de felicidade.

[[v24-15-17]]

^<<v24-15-17,17>>^ Não tenho gasto o meu tempo rindo e gozando a vida junto com outras pessoas. Por causa do trabalho pesado que me deste, fiquei sozinho e muito indignado.

[[v24-15-18]]

^<<v24-15-18,18>>^ Por que continuo a sofrer? Por que as minhas feridas doem sem parar? Por que elas não saram? Será que não posso confiar em ti? Será que és como um riacho que seca no verão?

[[v24-15-19]]

^<<v24-15-19,19>>^ O Senhor  respondeu: — Se você voltar, eu o receberei de volta, e você será meu servo  de novo. Se você disser coisas que se aproveitem e não palavras inúteis, você será de novo meu profeta . O povo voltará para você, mas você não deve voltar para eles.

[[v24-15-20]]

^<<v24-15-20,20>>^ Farei com que você seja para este povo como um forte muro de bronze. Eles lutarão contra você, mas não conseguirão derrotá-lo, pois eu estarei com você para protegê-lo e salvá-lo.

[[v24-15-21]]

^<<v24-15-21,21>>^ Eu o livrarei das mãos dos perversos e o libertarei do poder dos violentos. Eu, o Senhor , falei.

'''

xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[&#60; Capítulo Anterior] | <<v24-15-0,Topo>> | xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[Próximo Capítulo &#62;]