include::./index.adoc[]

[[v24-12-0]]
=== Jeremias, 12
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-12-1]]

^<<v24-12-1,1>>^ — Ó Senhor  Deus, se eu discutisse esse meu caso contigo, tu provarias que estás com a razão. Mas eu preciso te fazer algumas perguntas sobre a tua justiça. Por que os maus ficam ricos? Por que os desonestos conseguem sucesso?

[[v24-12-2]]

^<<v24-12-2,2>>^ Tu os plantas, e as suas raízes se firmam; eles crescem e produzem fruto. Vivem sempre falando bem de ti, mas na verdade não se importam contigo.

[[v24-12-3]]

^<<v24-12-3,3>>^ Mas tu, ó Senhor , me conheces; tu vês o que estou fazendo e sabes como te amo. Ó Senhor , arrasta essa gente como ovelhas para o matadouro; separa-os para o dia da matança.

[[v24-12-4]]

^<<v24-12-4,4>>^ Por quanto tempo a nossa terra ficará seca? Até quando o capim murchará em todos os pastos? Os animais e as aves estão morrendo por causa da maldade dos moradores da terra, que dizem: "Deus não vê o que estamos fazendo."

[[v24-12-5]]

^<<v24-12-5,5>>^ Deus respondeu: — Jeremias, se você se cansa apostando corrida com os homens, como é que vai correr mais do que os cavalos? Se você não se sente seguro numa terra de paz, como é que vai conseguir viver nas matas do rio Jordão?

[[v24-12-6]]

^<<v24-12-6,6>>^ Até os seus irmãos, gente da sua própria família, são traidores. Todos eles criticam você pelas costas. Não confie neles, ainda que venham com conversa de amigo.

[[v24-12-7]]

^<<v24-12-7,7>>^ O Senhor  disse: "Abandonei o meu povo e rejeitei a nação que escolhi. Entreguei o povo que eu amo na mão dos seus inimigos.

[[v24-12-8]]

^<<v24-12-8,8>>^ O meu povo escolhido virou contra mim como um leão na floresta. Eles gritaram contra mim, e por isso eu os detesto.

[[v24-12-9]]

^<<v24-12-9,9>>^ O meu povo escolhido é como um pássaro atacado de todos os lados por gaviões. Venham, animais selvagens, venham tomar parte na festa!

[[v24-12-10]]

^<<v24-12-10,10>>^ Muitos governadores estrangeiros destruíram a minha plantação de uvas, pisaram os meus campos e fizeram da minha linda terra um deserto.

[[v24-12-11]]

^<<v24-12-11,11>>^ Arrasaram a terra, e ela está abandonada diante de mim. A terra toda virou um deserto, mas ninguém se importa.

[[v24-12-12]]

^<<v24-12-12,12>>^ Em todos os morros do deserto, apareceram homens para assaltar os outros. Eu mandei a guerra para destruir o país inteiro; ninguém pode viver em paz.

[[v24-12-13]]

^<<v24-12-13,13>>^ O meu povo plantou trigo e colheu espinhos; trabalhou muito, porém não ganhou nada. Por causa do fogo da minha ira , as suas colheitas fracassaram."

[[v24-12-14]]

^<<v24-12-14,14>>^ O Senhor  Deus disse: — Agora, vou falar sobre os vizinhos maus de Israel que arruinaram a terra que eu dei ao meu povo. Levarei essa gente para longe das suas terras, como se fossem plantas arrancadas. E tirarei o povo de Judá do meio deles.

[[v24-12-15]]

^<<v24-12-15,15>>^ Mas, depois de levá-los para longe, terei pena deles e trarei cada nação de volta para a sua terra, para o seu país.

[[v24-12-16]]

^<<v24-12-16,16>>^ Eu quero que eles aceitem de todo o coração a religião do meu povo. Quero que aprendam a dizer: "Juro pelo Senhor , o Deus vivo" — assim como no passado eles ensinaram o meu povo a jurar pelo deus Baal . Se fizerem isso, eles também farão parte do meu povo e terão sucesso.

[[v24-12-17]]

^<<v24-12-17,17>>^ Mas eu arrancarei pelas raízes e destruirei completamente qualquer nação que não quiser obedecer. Eu, o Senhor , falei.

'''

xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[Próximo Capítulo &#62;]