include::./index.adoc[]

[[v24-47-0]]
=== Jeremias, 47
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-47-1]]

^<<v24-47-1,1>>^ Antes de o rei do Egito atacar a cidade de Gaza, o Senhor  Deus me falou a respeito dos filisteus.

[[v24-47-2]]

^<<v24-47-2,2>>^ Ele disse: "Vejam! No Norte, as águas estão subindo e de lá vão correr como um rio no tempo da enchente. Elas cobrirão a terra e tudo o que nela existe, as cidades e os seus moradores. Eles gritarão pedindo socorro; todos nesta terra gritarão de dor.

[[v24-47-3]]

^<<v24-47-3,3>>^ Eles ouvirão o ruído das patas dos cavalos, o barulho dos carros de guerra e o estrondo das suas rodas. Os pais não voltarão para buscar os seus filhos, pois os seus braços estarão fracos, caídos.

[[v24-47-4]]

^<<v24-47-4,4>>^ Chegou o dia de destruir o país dos filisteus, chegou o dia de impedir que as cidades de Tiro e Sidom recebam ajuda dos seus aliados. Eu, o Senhor , vou destruir os filisteus, todos os que vêm da ilha de Creta.

[[v24-47-5]]

^<<v24-47-5,5>>^ O povo de Gaza ficou muito triste, e os moradores de Asquelom estão calados. Até quando vão chorar os que ficaram na terra dos filisteus?

[[v24-47-6]]

^<<v24-47-6,6>>^ Vocês gritam: ‘Espada de Deus! Quando é que você vai parar de matar? Volte para a sua bainha, fique ali e descanse!’

[[v24-47-7]]

^<<v24-47-7,7>>^ Mas como é que a espada pode descansar, se eu lhe dei trabalho para fazer? Eu mandei que ela atacasse a cidade de Asquelom e o povo que vive no litoral."

'''

xref:024-jeremias/024-jeremias-046.adoc#v24-46-0[&#60; Capítulo Anterior] | <<v24-47-0,Topo>> | xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[Próximo Capítulo &#62;]