include::./index.adoc[]

[[v24-20-0]]
=== Jeremias, 20
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-20-1]]

^<<v24-20-1,1>>^ Pasur, filho de Imer, era sacerdote e chefe dos serviços do Templo. Ele me ouviu dizer essas coisas

[[v24-20-2]]

^<<v24-20-2,2>>^ e por isso mandou que eu fosse surrado e preso com correntes no Portão de Benjamim, o portão de cima que dá para o Templo.

[[v24-20-3]]

^<<v24-20-3,3>>^ Na manhã seguinte, depois que Pasur me soltou das correntes, eu disse: — O Senhor  Deus mudou o seu nome de "Pasur" para "Terror-por-todos-os-lados".

[[v24-20-4]]

^<<v24-20-4,4>>^ O Senhor  mesmo disse: "Pasur, eu farei com que você seja um terror para você mesmo e para todos os seus amigos. Todos eles serão mortos pelas espadas dos inimigos deles, e você vai ver isso. Todo o povo de Judá será dominado pelo rei da Babilônia. Ele vai levar alguns para a Babilônia como prisioneiros e mandará matar outros.

[[v24-20-5]]

^<<v24-20-5,5>>^ Deixarei que os inimigos levem embora toda a riqueza desta cidade. Eles pegarão todas as coisas de valor e os tesouros dos reis de Judá e carregarão tudo para a Babilônia.

[[v24-20-6]]

^<<v24-20-6,6>>^ E você, Pasur, com toda a sua família, será preso e também será levado para lá. Ali você morrerá e será sepultado junto com todos os seus amigos, a quem você anunciou tantas mentiras."

[[v24-20-7]]

^<<v24-20-7,7>>^ Ó Senhor  Deus, tu me enganaste, e eu fiquei enganado. Tu és mais forte do que eu e me dominaste. Todos zombam de mim, caçoando o dia inteiro.

[[v24-20-8]]

^<<v24-20-8,8>>^ Cada vez que falo, tenho de gritar e anunciar: "Violência! Destruição!" Ó Senhor , eles me desprezam e zombam de mim o tempo todo porque anuncio a tua mensagem.

[[v24-20-9]]

^<<v24-20-9,9>>^ Mas, quando penso: "Vou esquecer o Senhor e não falarei mais em seu nome", então a tua mensagem fica presa dentro de mim e queima como fogo no meu coração. Estou cansado de guardá-la e não posso mais aguentar.

[[v24-20-10]]

^<<v24-20-10,10>>^ Ouço as multidões cochichando: "Há terror-por-todos-os-lados." E dizem: "Acusem Jeremias! Vamos denunciá-lo!" Até os meus amigos íntimos esperam que eu tropece. Eles dizem: "Talvez ele caia numa armadilha; então nós o pegaremos e nos vingaremos."

[[v24-20-11]]

^<<v24-20-11,11>>^ Mas tu, ó Senhor , estás comigo e és forte e poderoso. Os que me perseguem tropeçarão e nunca vencerão. Eles ficarão muito envergonhados por causa do seu fracasso. A desgraça deles não acabará e nunca será esquecida.

[[v24-20-12]]

^<<v24-20-12,12>>^ Assim, ó Senhor  Todo-Poderoso, com justiça tu nos pões à prova, pois sabes o que está na nossa mente e no nosso coração. Deixa que eu veja a tua vingança contra os meus inimigos, pois coloquei a minha causa nas tuas mãos.

[[v24-20-13]]

^<<v24-20-13,13>>^ Cantem ao Senhor  Deus, louvem o Senhor porque ele livra os pobres do poder dos maus.

[[v24-20-14]]

^<<v24-20-14,14>>^ Maldito seja o dia em que eu nasci! Esqueçam o dia em que a minha mãe me deu à luz!

[[v24-20-15]]

^<<v24-20-15,15>>^ Maldito seja o homem que alegrou o meu pai quando lhe deu esta notícia: "É menino! Você tem um filho!"

[[v24-20-16]]

^<<v24-20-16,16>>^ Que esse homem seja como as cidades que o Senhor  Deus destruiu sem dó! Que ele ouça gemidos de dor pela manhã e gritos de batalha ao meio-dia,

[[v24-20-17]]

^<<v24-20-17,17>>^ porque não me matou antes de eu nascer! Pois assim a barriga da minha mãe teria sido a minha sepultura, e eu nunca teria nascido.

[[v24-20-18]]

^<<v24-20-18,18>>^ Por que nasci? Será que foi só para ter tristeza e dor e acabar a minha vida na desgraça?

'''

xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[Próximo Capítulo &#62;]