include::./index.adoc[]

[[v24-39-0]]
=== Jeremias, 39
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-39-1]]

^<<v24-39-1,1>>^ No décimo mês do ano nono do reinado de Zedequias em Judá, o rei Nabucodonosor, da Babilônia, veio com todo o seu exército e atacou a cidade de Jerusalém.

[[v24-39-2]]

^<<v24-39-2,2>>^ No ano décimo primeiro do reinado de Zedequias, no dia nove do quarto mês, eles conseguiram abrir uma brecha na muralha da cidade.

[[v24-39-3]]

^<<v24-39-3,3>>^ Quando Jerusalém foi tomada , todos os altos funcionários do rei da Babilônia vieram e sentaram nos seus lugares, no Portão do Meio. Entre eles, estavam Nergal-Sarezer, Sangar-Nebo, Sarsequim e outro Nergal-Sarezer.

[[v24-39-4]]

^<<v24-39-4,4>>^ Quando o rei Zedequias e todos os seus soldados viram o que havia acontecido, tentaram fugir da cidade durante a noite. Eles saíram pelo caminho do jardim do rei, foram pelo portão que ligava as duas muralhas e fugiram na direção do vale do Jordão.

[[v24-39-5]]

^<<v24-39-5,5>>^ Mas o exército dos babilônios os perseguiu e prendeu Zedequias na planície de Jericó. Eles o levaram como prisioneiro ao rei Nabucodonosor, que estava na cidade de Ribla, na região de Hamate. Ali Nabucodonosor o condenou.

[[v24-39-6]]

^<<v24-39-6,6>>^ Em Ribla, o rei da Babilônia mandou matar os filhos de Zedequias na presença do pai. Também mandou matar as autoridades de Judá.

[[v24-39-7]]

^<<v24-39-7,7>>^ Depois, mandou furar os olhos de Zedequias e o prendeu com correntes de bronze a fim de levá-lo para a Babilônia.

[[v24-39-8]]

^<<v24-39-8,8>>^ Enquanto isso, os babilônios incendiaram o palácio real e as casas do povo e derrubaram as muralhas de Jerusalém.

[[v24-39-9]]

^<<v24-39-9,9>>^ E Nebuzaradã, o comandante-geral do exército babilônio, levou como prisioneiros para a Babilônia os que haviam sido deixados na cidade e os que haviam fugido para o lado dele.

[[v24-39-10]]

^<<v24-39-10,10>>^ Mas deixou ficar na terra de Judá algumas pessoas mais pobres, que não tinham propriedades, e lhes deu plantações de uvas e terras.

[[v24-39-11]]

^<<v24-39-11,11>>^ E Nabucodonosor, rei da Babilônia, deu a Nebuzaradã a seguinte ordem a meu respeito:

[[v24-39-12]]

^<<v24-39-12,12>>^ — Vá buscar Jeremias e cuide bem dele. Não o trate mal, mas faça por ele o que ele quiser.

[[v24-39-13]]

^<<v24-39-13,13>>^ Assim Nebuzaradã, junto com Nebusazbã, alto oficial, e Nergal-Sarezer, que também era alto oficial, e todas as outras autoridades do rei da Babilônia

[[v24-39-14]]

^<<v24-39-14,14>>^ mandaram me tirar do pátio da guarda. Fui entregue a Gedalias, filho de Aicã e neto de Safã, e ele me levou para casa. Assim eu fiquei em Jerusalém, no meio do povo.

[[v24-39-15]]

^<<v24-39-15,15>>^ Enquanto eu ainda estava preso no pátio da guarda, o Senhor  Deus falou comigo. Ele me mandou

[[v24-39-16]]

^<<v24-39-16,16>>^ que dissesse a Ebede-Meleque, da Etiópia, que o Senhor  Todo-Poderoso, o Deus de Israel, tinha dito o seguinte: — Conforme prometi, não trarei progresso e sim destruição a esta cidade de Jerusalém. E, quando isso acontecer, você estará aqui para ver.

[[v24-39-17]]

^<<v24-39-17,17>>^ Mas eu, o Senhor , o protegerei, e você não será entregue nas mãos daqueles de quem está com medo.

[[v24-39-18]]

^<<v24-39-18,18>>^ Eu o salvarei: você não morrerá. Você continuará vivo porque confiou em mim. Eu, o Senhor , falei.

'''

xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[&#60; Capítulo Anterior] | <<v24-39-0,Topo>> | xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[Próximo Capítulo &#62;]