include::./index.adoc[]

[[v24-50-0]]
=== Jeremias, 50
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-50-1]]

^<<v24-50-1,1>>^ O Senhor  Deus me deu a seguinte mensagem a respeito da Babilônia e do seu povo:

[[v24-50-2]]

^<<v24-50-2,2>>^ "Deem a notícia às nações! Avisem a todos! Deem o sinal e espalhem a novidade! Não deixem que ela fique em segredo! ‘A Babilônia caiu! O seu deus Bel-Marduque está desesperado! Os ídolos da Babilônia estão cobertos de vergonha, e as suas imagens nojentas estão cheias de medo!’ "

[[v24-50-3]]

^<<v24-50-3,3>>^ — Um povo do Norte veio atacar a Babilônia, e ela vai virar um deserto. As pessoas e os animais fugirão, e ninguém mais viverá ali.

[[v24-50-4]]

^<<v24-50-4,4>>^ O Senhor  Deus disse: — Quando esse tempo chegar, o povo de Israel e o povo de Judá voltarão chorando e procurarão a mim, o seu Deus.

[[v24-50-5]]

^<<v24-50-5,5>>^ Perguntarão onde é o caminho para Sião  e vão seguir nessa direção. E vão dizer assim: "Vamos nos ligar com Deus, o Senhor , e fazer com ele uma aliança  que durará para sempre."

[[v24-50-6]]

^<<v24-50-6,6>>^ — O meu povo é como ovelhas perdidas nas montanhas por culpa dos pastores. Como ovelhas, caminharam de montanha em montanha e esqueceram a sua casa.

[[v24-50-7]]

^<<v24-50-7,7>>^ Foram atacados por todos aqueles que os encontraram. Os seus inimigos dizem: "Eles pecaram contra Deus, e por isso o que fizemos não está errado. Eles deveriam ter ficado fiéis a Deus, o Senhor , como os seus antepassados ficaram."

[[v24-50-8]]

^<<v24-50-8,8>>^ — Israelitas, fujam da Babilônia! Deixem o país! Sejam os primeiros a sair!

[[v24-50-9]]

^<<v24-50-9,9>>^ Pois levantarei no Norte um grupo de nações fortes e farei com que ataquem a Babilônia. Essas nações ficarão em linha de batalha para lutar contra a cidade e a conquistarão. Os seus soldados atiram flechas como bons caçadores que nunca erram o alvo.

[[v24-50-10]]

^<<v24-50-10,10>>^ Tirarão todas as riquezas da Babilônia e levarão embora tudo o que quiserem. Eu, o Senhor , estou falando.

[[v24-50-11]]

^<<v24-50-11,11>>^ O Senhor  Deus diz: — Povo de Babilônia, vocês levaram todas as riquezas da minha nação. Vocês agora estão alegres e felizes, andando soltos como um bezerro no pasto ou rinchando como um cavalo bravo.

[[v24-50-12]]

^<<v24-50-12,12>>^ Mas a cidade de vocês ficará humilhada e muito envergonhada. A Babilônia será a nação menos importante de todas; ela vai virar um deserto seco, sem água.

[[v24-50-13]]

^<<v24-50-13,13>>^ Por causa da minha ira , Babilônia ficará arrasada, e ninguém viverá ali. Todos os que passarem por lá ficarão admirados e espantados, vendo o que aconteceu com a cidade.

[[v24-50-14]]

^<<v24-50-14,14>>^ — Flecheiros, fiquem em linha de batalha para lutar contra Babilônia e cerquem a cidade. Atirem todas as suas flechas contra ela, pois pecou contra mim, o Senhor .

[[v24-50-15]]

^<<v24-50-15,15>>^ Soltem o grito de guerra em volta da cidade toda! Agora, Babilônia se entregou. Abriram brechas nas suas muralhas e as derrubaram. Eu, o Senhor , estou me vingando dos babilônios. Vocês também se vinguem deles e os tratem como eles trataram os outros.

[[v24-50-16]]

^<<v24-50-16,16>>^ Não deixem que plantem, nem que façam colheitas na Babilônia. Todos os estrangeiros que vivem lá ficarão com medo do exército inimigo e voltarão para as suas pátrias.

[[v24-50-17]]

^<<v24-50-17,17>>^ O Senhor  Deus diz: — O povo de Israel é como ovelhas que os leões caçam e espalham. Primeiro, os israelitas foram atacados pelo rei da Assíria, e depois o rei Nabucodonosor, da Babilônia, roeu os ossos deles.

[[v24-50-18]]

^<<v24-50-18,18>>^ Por isso, eu, o Senhor  Todo-Poderoso, o Deus de Israel, castigarei o rei Nabucodonosor e a sua nação, do mesmo jeito que castiguei o rei da Assíria.

[[v24-50-19]]

^<<v24-50-19,19>>^ Levarei o povo de Israel de volta para a sua pátria. Eles vão se alimentar do que cresce no monte Carmelo e na região de Basã e comerão tudo o que quiserem do que dá nas terras de Efraim e Gileade.

[[v24-50-20]]

^<<v24-50-20,20>>^ Quando esse dia chegar, ninguém achará mais pecado em Israel nem maldade em Judá, pois perdoarei aqueles que eu deixar com vida. Eu, o Senhor , estou falando.

[[v24-50-21]]

^<<v24-50-21,21>>^ O Senhor  diz: — Ataquem o povo de Merataim e Pecode. Matem, acabem de uma vez com eles. Façam tudo o que estou mandando.

[[v24-50-22]]

^<<v24-50-22,22>>^ O barulho da batalha é ouvido no país, e há grande destruição.

[[v24-50-23]]

^<<v24-50-23,23>>^ A Babilônia quebrou o mundo a marretadas, e agora a marreta está quebrada em pedaços! Todas as nações estão espantadas, vendo o que aconteceu com a Babilônia.

[[v24-50-24]]

^<<v24-50-24,24>>^ Você, Babilônia, sem saber, caiu na armadilha que eu armei. Você foi apanhada e presa porque lutou contra mim.

[[v24-50-25]]

^<<v24-50-25,25>>^ Eu, o Senhor , o Deus Todo-Poderoso, abri o lugar onde as minhas armas estão guardadas. Tirei as minhas armas para fora, pois estou irado e tenho um serviço a fazer na Babilônia.

[[v24-50-26]]

^<<v24-50-26,26>>^ Ataquem de todos os lados e arrebentem os depósitos de cereais! Amontoem as riquezas como se fossem montes de cereais! Destruam o país! Não deixem sobrar nada!

[[v24-50-27]]

^<<v24-50-27,27>>^ Matem todos os seus soldados! Acabem com eles! Coitado do povo da Babilônia! Chegou o dia do seu castigo!

[[v24-50-28]]

^<<v24-50-28,28>>^ Já posso ver os refugiados que escaparam da Babilônia chegando a Sião  e contando como o Senhor , nosso Deus, se vingou daquilo que os babilônios fizeram contra o Templo dele.

[[v24-50-29]]

^<<v24-50-29,29>>^ — Digam aos flecheiros que ataquem Babilônia. Mandem para lá todos os que sabem usar o arco e a flecha. Cerquem a cidade e não deixem ninguém escapar. Que a Babilônia pague por tudo o que fez! Façam com ela o que ela fez com os outros, pois me tratou com orgulho a mim, o Santo Deus de Israel.

[[v24-50-30]]

^<<v24-50-30,30>>^ Por isso, os seus jovens serão mortos nas ruas, e todos os seus soldados serão destruídos naquele dia. Sou eu, o Senhor , quem está falando.

[[v24-50-31]]

^<<v24-50-31,31>>^ — Babilônia, você está muito orgulhosa, e por isso eu, o Senhor , o Deus Todo-Poderoso, estou contra você! Chegou a hora de castigá-la.

[[v24-50-32]]

^<<v24-50-32,32>>^ Você, nação orgulhosa, tropeçará e cairá, e ninguém a ajudará a se levantar. Eu porei fogo nas suas cidades, e tudo o que está em volta será destruído.

[[v24-50-33]]

^<<v24-50-33,33>>^ O Senhor  Todo-Poderoso diz: — O povo de Israel e o povo de Judá estão sofrendo perseguição. Todos aqueles que os prenderam os estão vigiando de perto e não querem soltá-los.

[[v24-50-34]]

^<<v24-50-34,34>>^ Mas aquele que vai libertá-los é forte; o seu nome é Senhor , o Todo-Poderoso. Ele mesmo defenderá a causa deles e trará paz à terra; mas para o povo da Babilônia ele trará confusão.

[[v24-50-35]]

^<<v24-50-35,35>>^ O Senhor  diz: "Morram a Babilônia! Morra o seu povo, as suas autoridades e os seus sábios!

[[v24-50-36]]

^<<v24-50-36,36>>^ Morram os seus adivinhos mentirosos e tolos! Morram os seus soldados, que estão apavorados!

[[v24-50-37]]

^<<v24-50-37,37>>^ Acabem com os seus cavalos e com os seus carros de guerra! Morram os soldados tão fracos que ela contratou! Destruam os tesouros dela! Peguem as suas riquezas e levem embora!

[[v24-50-38]]

^<<v24-50-38,38>>^ Virá uma seca à sua terra, e os seus rios secarão. A Babilônia é uma terra de ídolos medonhos, ídolos que têm feito o seu povo de bobo."

[[v24-50-39]]

^<<v24-50-39,39>>^ — E assim feras do deserto, lobos e aves imundas morarão em Babilônia. Nunca mais viverá gente ali; o lugar ficará para sempre sem moradores.

[[v24-50-40]]

^<<v24-50-40,40>>^ Acontecerá com Babilônia o que aconteceu com Sodoma e Gomorra, que eu destruí junto com as cidades que ficavam ao seu redor. Nunca mais ninguém viverá lá. Sou eu, o Senhor , quem está falando.

[[v24-50-41]]

^<<v24-50-41,41>>^ "Um povo vem vindo de longe, de uma terra do Norte; uma forte nação e muitos reis estão se preparando para a guerra.

[[v24-50-42]]

^<<v24-50-42,42>>^ Estão armados com arcos e espadas. São cruéis e não têm piedade. Eles vêm montados em cavalos, fazendo o barulho do mar quando está bravo. Eles estão prontos para atacar a Babilônia.

[[v24-50-43]]

^<<v24-50-43,43>>^ O rei da Babilônia ouve as notícias, e os seus braços ficam moles. A aflição e a dor tomam conta dele como acontece com a mulher na hora do parto."

[[v24-50-44]]

^<<v24-50-44,44>>^ — Assim como um leão sai da floresta na beira do rio Jordão e sobe até a terra de pastos verdes, assim eu, o Senhor  Deus, virei e farei com que os babilônios fujam correndo da sua cidade. Então o chefe que eu escolher governará a nação. Quem pode se comparar comigo? Quem tem coragem de me desafiar? Que governador poderia me enfrentar?

[[v24-50-45]]

^<<v24-50-45,45>>^ Por isso, prestem atenção no plano que eu, o Senhor , fiz contra a cidade de Babilônia; escutem o que vou fazer com o seu povo. Até as suas crianças serão arrastadas, e os que ouvirem falar disso ficarão horrorizados.

[[v24-50-46]]

^<<v24-50-46,46>>^ Quando Babilônia cair, o barulho será tão grande, que a terra tremerá, e os gritos de pavor serão ouvidos pelas outras nações.

'''

xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[&#60; Capítulo Anterior] | <<v24-50-0,Topo>> | xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[Próximo Capítulo &#62;]