include::./index.adoc[]

[[v24-13-0]]
=== Jeremias, 13
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-13-1]]

^<<v24-13-1,1>>^ O Senhor  Deus me mandou comprar uma roupa de baixo, isto é, um calção novo, e vesti-lo. Mas disse que eu não o lavasse antes.

[[v24-13-2]]

^<<v24-13-2,2>>^ Eu fiz o que o Senhor  mandou: comprei o calção e vesti.

[[v24-13-3]]

^<<v24-13-3,3>>^ Aí o Senhor  falou comigo outra vez. Ele disse:

[[v24-13-4]]

^<<v24-13-4,4>>^ — Vá até o rio Eufrates e esconda o calção num buraco na rocha.

[[v24-13-5]]

^<<v24-13-5,5>>^ Eu fui e o escondi perto do rio Eufrates, como o Senhor  havia mandado.

[[v24-13-6]]

^<<v24-13-6,6>>^ Algum tempo depois, o Senhor  me disse que voltasse ao rio e apanhasse o calção que ele me havia mandado esconder ali.

[[v24-13-7]]

^<<v24-13-7,7>>^ Voltei lá, procurei e achei o lugar onde o havia escondido. Mas o calção tinha apodrecido e não prestava mais.

[[v24-13-8]]

^<<v24-13-8,8>>^ Então o Senhor  me falou de novo. Ele disse:

[[v24-13-9]]

^<<v24-13-9,9>>^ — É assim que eu vou destruir o orgulho do povo de Judá e o grande orgulho de Jerusalém.

[[v24-13-10]]

^<<v24-13-10,10>>^ Esse povo mau não quer ouvir o que eu digo e sempre foi teimoso. Eles adoram e seguem outros deuses. Por isso, vão ficar como essa roupa, que não presta mais para nada.

[[v24-13-11]]

^<<v24-13-11,11>>^ E, assim como o calção fica bem justo na cintura, eu gostaria que todo o povo de Israel e de Judá ficasse bem perto de mim. Eu queria que eles fossem o meu povo para darem louvor e glória  ao meu nome; mas eles não quiseram me obedecer.

[[v24-13-12]]

^<<v24-13-12,12>>^ Deus me disse: — Jeremias, fale ao povo de Israel que eu, o Senhor , estou dizendo: Toda jarra de vinho deve ficar bem cheia. Eles vão dizer que sabem muito bem que toda jarra de vinho deve ficar bem cheia.

[[v24-13-13]]

^<<v24-13-13,13>>^ Diga-lhes então que eu, o Senhor , vou encher de vinho o povo desta terra até que todos fiquem bêbados: os reis, que são descendentes de Davi, os sacerdotes, os profetas  e todo o povo de Jerusalém.

[[v24-13-14]]

^<<v24-13-14,14>>^ Então quebrarei todos, tanto os velhos quanto os jovens, como se quebram os jarros que são jogados uns contra os outros. Destruirei essa gente sem dó, sem piedade e sem misericórdia.

[[v24-13-15]]

^<<v24-13-15,15>>^ Povo de Israel, é Deus quem está falando. Sejam humildes e prestem atenção.

[[v24-13-16]]

^<<v24-13-16,16>>^ Confessem os seus pecados ao Senhor , seu Deus, antes que ele faça vir a escuridão, e, no escuro, vocês tropecem nas montanhas. Vocês esperam a luz, mas ele a mudará em sombras escuras, ele a transformará em profunda escuridão.

[[v24-13-17]]

^<<v24-13-17,17>>^ Se vocês não prestarem atenção, eu chorarei em segredo por causa do seu orgulho. Chorarei amargamente, derramarei lágrimas porque o povo de Deus foi levado como prisioneiro.

[[v24-13-18]]

^<<v24-13-18,18>>^ Deus me disse mais isto: — Diga ao rei e à mãe do rei que desçam dos seus tronos porque as suas lindas coroas caíram da sua cabeça.

[[v24-13-19]]

^<<v24-13-19,19>>^ As cidades da região sul estão cercadas pelos inimigos, e ninguém pode chegar lá. Todo o povo de Judá foi levado prisioneiro, foram todos levados para fora do país.

[[v24-13-20]]

^<<v24-13-20,20>>^ — Olhe, povo de Jerusalém! Os inimigos vêm vindo do Norte! Onde estão as pessoas que foram entregues para que vocês cuidassem delas? Onde está o povo que é o seu lindo rebanho?

[[v24-13-21]]

^<<v24-13-21,21>>^ O que é que vocês vão dizer quando aqueles que vocês pensavam que eram seus amigos forem colocados acima de vocês, como seus governadores? Vocês vão sentir dores como a mulher que está dando à luz.

[[v24-13-22]]

^<<v24-13-22,22>>^ Jerusalém, você pode perguntar a você mesma: "Por que aconteceu isso comigo? Por que arrancaram as minhas roupas? Por que abusaram de mim?" Então fique sabendo que é porque os seus pecados são muitos.

[[v24-13-23]]

^<<v24-13-23,23>>^ — Por acaso, um homem preto pode mudar a cor da sua pele ou um leopardo tirar as suas manchas? Se isso fosse possível, vocês, que só sabem fazer o mal, também poderiam aprender a fazer o bem.

[[v24-13-24]]

^<<v24-13-24,24>>^ Deus os espalhará como a palha que voa quando sopra o vento do deserto.

[[v24-13-25]]

^<<v24-13-25,25>>^ O Senhor  Deus disse que esta será a recompensa de vocês; é isso que vão receber porque vocês o esqueceram e confiaram em falsos deuses.

[[v24-13-26]]

^<<v24-13-26,26>>^ Deus mesmo arrancará as roupas de vocês e os fará passar vergonha.

[[v24-13-27]]

^<<v24-13-27,27>>^ Deus tem visto vocês fazendo coisas que ele detesta. Como um homem que anda atrás da mulher do seu vizinho, como um cavalo que procura a égua, assim vocês vão atrás de deuses pagãos nas montanhas e nos campos. O povo de Jerusalém está condenado! Quando é que vocês vão se purificar ?

'''

xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[&#60; Capítulo Anterior] | <<v24-13-0,Topo>> | xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[Próximo Capítulo &#62;]