include::./index.adoc[]

[[v24-46-0]]
=== Jeremias, 46
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-46-1]]

^<<v24-46-1,1>>^ O Senhor  Deus me falou a respeito das nações.

[[v24-46-2]]

^<<v24-46-2,2>>^ Ele me falou sobre o exército de Neco, rei do Egito, que foi vencido em Carquemis, perto do rio Eufrates, pelo rei Nabucodonosor, da Babilônia. Isso aconteceu no quarto ano do reinado de Jeoaquim, filho de Josias, em Judá. A respeito do Egito Deus disse o seguinte:

[[v24-46-3]]

^<<v24-46-3,3>>^ "Os oficiais egípcios gritam: ‘Aprontem os seus escudos  e marchem para a batalha!

[[v24-46-4]]

^<<v24-46-4,4>>^ Ponham arreios nos cavalos e montem! Formem filas e ponham os capacetes! Afiem as lanças e vistam as couraças !’

[[v24-46-5]]

^<<v24-46-5,5>>^ "Mas o que estou vendo?" — pergunta Deus. "Os egípcios estão fugindo de medo. Eles correm apavorados e fogem tão depressa, que nem olham para trás.

[[v24-46-6]]

^<<v24-46-6,6>>^ Aqueles que correm depressa não podem escapar; os soldados não conseguem fugir. No Norte, perto do rio Eufrates, eles tropeçam e caem.

[[v24-46-7]]

^<<v24-46-7,7>>^ Quem é este que vem subindo como o rio Nilo, como um rio inundando as suas margens?

[[v24-46-8]]

^<<v24-46-8,8>>^ É o Egito, subindo como o Nilo, como um rio alagando as suas margens. O Egito disse: ‘Vou subir e cobrir o mundo; vou destruir as cidades e os seus moradores.

[[v24-46-9]]

^<<v24-46-9,9>>^ Egípcios, mandem os cavalos saírem e façam os carros de guerra correrem! Mandem os soldados avançarem: os homens da Etiópia e da Líbia, que carregam escudos, e os homens de Lude, que atiram flechas com os seus arcos.’ "

[[v24-46-10]]

^<<v24-46-10,10>>^ Esse é o Dia do Senhor , o Deus Todo-Poderoso! Hoje, ele se vingará; hoje, ele castigará os seus inimigos. A sua espada os devorará até não querer mais e beberá o sangue deles até ficar satisfeita. Hoje, o Senhor  Todo-Poderoso oferecerá as suas vítimas em sacrifício no Norte, perto do rio Eufrates.

[[v24-46-11]]

^<<v24-46-11,11>>^ Povo do Egito, vá a Gileade , vá procurar remédios! Todos os seus remédios não adiantam, pois o seu mal não tem cura.

[[v24-46-12]]

^<<v24-46-12,12>>^ As nações ouviram falar da vergonha da sua derrota; a terra inteira escutou os seus gritos. Um soldado tropeçou no outro, e os dois caíram no chão.

[[v24-46-13]]

^<<v24-46-13,13>>^ Quando o rei Nabucodonosor, da Babilônia, veio atacar o Egito, o Senhor  Deus me disse o seguinte:

[[v24-46-14]]

^<<v24-46-14,14>>^ "Anunciem isto nas cidades do Egito, em Migdol, Mênfis e Tafnes: ‘Preparem-se para se defender; tudo o que vocês têm será destruído na guerra!

[[v24-46-15]]

^<<v24-46-15,15>>^ Por que foi que o seu deus poderoso caiu? Foi porque o Senhor  Deus o jogou no chão!’

[[v24-46-16]]

^<<v24-46-16,16>>^ Os soldados do Egito tropeçaram e caíram e disseram uns aos outros: ‘Vamos depressa! Vamos voltar para casa, para o nosso povo, e assim escaparemos da espada do inimigo!’

[[v24-46-17]]

^<<v24-46-17,17>>^ Deem ao rei do Egito este novo nome — ‘Falador Espalhafatoso — o homem que perdeu a sua oportunidade.’

[[v24-46-18]]

^<<v24-46-18,18>>^ "Sou eu, o Rei, quem está falando. Eu sou o Deus vivo. O meu nome é Senhor , o Todo-Poderoso. Como o Tabor é mais alto do que outros montes, e o monte Carmelo fica acima do mar, assim aquele que vai atacar é mais forte do que vocês, egípcios.

[[v24-46-19]]

^<<v24-46-19,19>>^ "Povo do Egito, apronte-se para ser levado como prisioneiro! A cidade de Mênfis vai virar um deserto, será arrasada e ficará sem moradores.

[[v24-46-20]]

^<<v24-46-20,20>>^ O Egito é como uma bela vaca, mordida por um moscão que vem do Norte.

[[v24-46-21]]

^<<v24-46-21,21>>^ Até os seus soldados pagos para lutarem são tão mansos como bezerros gordos. Não ficaram firmes para lutar; todos eles viraram as costas e fugiram porque chegou o dia da sua desgraça, chegou a hora da sua destruição.

[[v24-46-22]]

^<<v24-46-22,22>>^ O Egito foge, assobiando como uma cobra, porque o exército inimigo está chegando. Os inimigos atacam com machados, como se fossem cortadores de lenha.

[[v24-46-23]]

^<<v24-46-23,23>>^ Eles derrubam a sua floresta, onde é tão difícil entrar. Os seus homens são tantos, que não podem ser contados; os soldados inimigos são mais numerosos do que gafanhotos.

[[v24-46-24]]

^<<v24-46-24,24>>^ O povo do Egito está humilhado porque foi dominado pela nação do Norte. Eu, o Senhor , estou falando."

[[v24-46-25]]

^<<v24-46-25,25>>^ O Senhor  Todo-Poderoso, o Deus de Israel, disse: — Eu castigarei Amom, o deus de Tebas, e também o Egito, os seus deuses e os seus reis. Castigarei o rei do Egito e todos os que confiam nele.

[[v24-46-26]]

^<<v24-46-26,26>>^ Eu os entregarei aos que querem matá-los, isto é, ao rei Nabucodonosor, da Babilônia, e ao seu exército. Porém mais tarde o povo viverá outra vez na terra do Egito. Eu, o Senhor , estou falando.

[[v24-46-27]]

^<<v24-46-27,27>>^ "Descendentes do meu servo  Jacó, não tenham medo! Povo de Israel, não fique assustado! Eu os livrarei dessa terra distante, da terra onde vocês são prisioneiros. Vocês voltarão e viverão em paz; viverão em segurança, e ninguém fará com que fiquem com medo.

[[v24-46-28]]

^<<v24-46-28,28>>^ Estarei com vocês para salvá-los. Destruirei completamente todas as nações por onde os espalhei, mas vocês não serão completamente destruídos. Vocês não ficarão sem castigo, mas, quando eu os castigar, não serei duro demais. Eu, o Senhor , falei."

'''

xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[Próximo Capítulo &#62;]