include::./index.adoc[]

[[v24-6-0]]
=== Jeremias, 6
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-6-1]]

^<<v24-6-1,1>>^ Povo da tribo  de Benjamim, saia de Jerusalém e fuja para um lugar seguro! Toquem corneta em Tecoa e ponham um aviso em Bete-Haquerém, pois desgraça e grande destruição vão chegar do Norte.

[[v24-6-2]]

^<<v24-6-2,2>>^ Jerusalém, bela e encantadora cidade, o seu fim está perto.

[[v24-6-3]]

^<<v24-6-3,3>>^ Os reis vão acampar aí com os seus exércitos. Eles vão armar barracas ao seu redor, cada um no lugar que escolher.

[[v24-6-4]]

^<<v24-6-4,4>>^ Eles vão dizer: "Preparem-se para atacar a cidade! Aprontem-se! Vamos atacar ao meio-dia!" Mas depois dirão: "É muito tarde, o dia já está quase no fim, e as sombras estão ficando compridas.

[[v24-6-5]]

^<<v24-6-5,5>>^ Aprontem-se! Vamos atacar esta noite; vamos destruir as fortalezas de Jerusalém."

[[v24-6-6]]

^<<v24-6-6,6>>^ O Senhor  Todo-Poderoso deu esta ordem aos reis: — Cortem árvores e façam rampas, preparando-se para atacar Jerusalém. E disse: — Vou castigar esta cidade porque ela está cheia de violência.

[[v24-6-7]]

^<<v24-6-7,7>>^ Como de um poço sai água, de Jerusalém sai o pecado. Na cidade, falam de violência e destruição; só vejo doenças e ferimentos.

[[v24-6-8]]

^<<v24-6-8,8>>^ Povo de Jerusalém, que essas coisas sirvam de aviso para vocês; se não, eu os abandonarei. Farei com que a cidade vire um deserto, um lugar onde não mora ninguém.

[[v24-6-9]]

^<<v24-6-9,9>>^ O Senhor  Todo-Poderoso me disse: — Na terra de Israel, não sobrará ninguém: ela ficará limpa como uma parreira  que foi colhida duas vezes. Como um lavrador colhe as suas uvas, assim você deve salvar todos os que puder.

[[v24-6-10]]

^<<v24-6-10,10>>^ Eu respondi: — Com quem devo falar? E, mesmo que eu fale, quem vai me ouvir? Eles taparam os ouvidos, pois não querem prestar atenção. Eles não querem ouvir a tua mensagem e zombam do que dizes.

[[v24-6-11]]

^<<v24-6-11,11>>^ Ó Senhor  Deus, o teu furor me dominou; estou cansado de guardar a tua ira  dentro de mim. Então Deus me disse: — Faça cair a minha ira sobre as crianças nas ruas e sobre os moços nas suas reuniões. Maridos e esposas serão levados como prisioneiros, e também os velhinhos.

[[v24-6-12]]

^<<v24-6-12,12>>^ As casas deles ficarão para outros, e também as suas terras e as suas esposas. Vou castigar o povo desta terra. Sou eu, o Senhor , quem está falando.

[[v24-6-13]]

^<<v24-6-13,13>>^ Todos, ricos e pobres, procuram ganhar dinheiro desonestamente. Até os profetas  e os sacerdotes enganam as pessoas.

[[v24-6-14]]

^<<v24-6-14,14>>^ Eles tratam dos ferimentos do meu povo como se fossem uma coisa sem importância. E dizem: "Vai tudo bem", quando na verdade tudo vai mal.

[[v24-6-15]]

^<<v24-6-15,15>>^ Será que ficaram envergonhados por terem feito essas coisas que eu detesto? Não! Não ficaram envergonhados de jeito nenhum. Eles nem sabem o que é sentir vergonha e por isso vão cair como outros têm caído. Quando eu os castigar, eles vão ficar arrasados. Eu, o Senhor , falei.

[[v24-6-16]]

^<<v24-6-16,16>>^ O Senhor  Deus disse ao seu povo: — Fiquem nas encruzilhadas e vejam quais são as melhores estradas, procurem saber qual é o melhor caminho. Andem nesse caminho e vocês terão paz. Mas eles responderam: — Nós não vamos andar nesse caminho!

[[v24-6-17]]

^<<v24-6-17,17>>^ Deus colocou vigias para prestarem atenção no aviso das cornetas. Mas os vigias disseram: — Nós não vamos prestar atenção.

[[v24-6-18]]

^<<v24-6-18,18>>^ Então Deus disse: — Ouçam, ó nações da terra, e vejam o que vai acontecer com o meu povo.

[[v24-6-19]]

^<<v24-6-19,19>>^ Escute, ó terra! Vou trazer desgraça para esse povo, desgraça que eles merecem porque não obedeceram às minhas palavras e desprezaram os meus ensinos.

[[v24-6-20]]

^<<v24-6-20,20>>^ Que me importa o incenso que me trazem de Sabá ou as plantas cheirosas que vêm de longe? Não aceitarei as ofertas deles, nem ficarei contente com os seus sacrifícios .

[[v24-6-21]]

^<<v24-6-21,21>>^ Assim eu, o Senhor , vou fazer com que esse povo tropece e caia. Pais e filhos morrerão, e amigos e vizinhos também.

[[v24-6-22]]

^<<v24-6-22,22>>^ O Senhor  Deus diz: — Um povo vem vindo de longe, de uma terra do Norte; uma forte nação está se preparando para a guerra.

[[v24-6-23]]

^<<v24-6-23,23>>^ Estão armados com arcos e flechas e espadas. São cruéis, não têm piedade. Eles vêm montados em cavalos, fazendo o barulho do mar quando está bravo. E estão prontos para atacar a cidade de Jerusalém.

[[v24-6-24]]

^<<v24-6-24,24>>^ — Ouvimos a notícia — diz o povo de Jerusalém —, e as nossas mãos ficaram moles; a aflição tomou conta de nós, como as dores de uma mulher no parto.

[[v24-6-25]]

^<<v24-6-25,25>>^ Não vamos nos arriscar a ir ao campo nem a andar pelas estradas, pois o inimigo está armado, e há terror por toda parte.

[[v24-6-26]]

^<<v24-6-26,26>>^ Deus diz ao seu povo: — Como sinal de tristeza, vistam roupa feita de pano grosseiro e rolem nas cinzas. Chorem como se chora a morte de um filho único; derramem lágrimas amargas, pois o destruidor atacará de repente.

[[v24-6-27]]

^<<v24-6-27,27>>^ Jeremias, ponha o meu povo à prova, como se prova o metal; examine bem e procure descobrir como estão agindo.

[[v24-6-28]]

^<<v24-6-28,28>>^ Todos eles são mais do que rebeldes e andam espalhando calúnias. São todos perversos, duros como bronze ou ferro.

[[v24-6-29]]

^<<v24-6-29,29>>^ E assim como nem mesmo um forno bem quente consegue derreter a prata a fim de separá-la das impurezas, também não adianta tentar purificar o meu povo, pois os maus não são separados dos bons.

[[v24-6-30]]

^<<v24-6-30,30>>^ Os maus serão chamados de "prata impura" porque eu, o Senhor , os rejeitei.

'''

xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[Próximo Capítulo &#62;]