include::./index.adoc[]

[[v24-29-0]]
=== Jeremias, 29
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-29-1]]

^<<v24-29-1,1>>^ Eu escrevi uma carta aos judeus que Nabucodonosor havia levado como prisioneiros de Jerusalém para a Babilônia: autoridades, sacerdotes, profetas  e todo o povo.

[[v24-29-2]]

^<<v24-29-2,2>>^ Isso aconteceu depois de terem saído de Jerusalém o rei Joaquim, a sua mãe, os oficiais do palácio, as autoridades de Judá e de Jerusalém, os carpinteiros e os outros operários especializados.

[[v24-29-3]]

^<<v24-29-3,3>>^ O rei Zedequias, de Judá, mandou que Elasa, filho de Safã, e Gemarias, filho de Hilquias, levassem a carta ao rei Nabucodonosor, da Babilônia. Ela dizia:

[[v24-29-4]]

^<<v24-29-4,4>>^ "O Senhor  Todo-Poderoso, o Deus de Israel, diz o seguinte a todos os judeus que ele deixou Nabucodonosor levar como prisioneiros de Jerusalém para a Babilônia:

[[v24-29-5]]

^<<v24-29-5,5>>^ ‘Construam casas e morem nelas. Plantem árvores frutíferas e comam as suas frutas.

[[v24-29-6]]

^<<v24-29-6,6>>^ Casem e tenham filhos. E que os filhos casem e também tenham filhos. Vocês devem aumentar em número e não diminuir.

[[v24-29-7]]

^<<v24-29-7,7>>^ Trabalhem para o bem da cidade para onde eu os mandei como prisioneiros. Orem a mim, pedindo em favor dela, pois, se ela estiver bem, vocês também estarão.

[[v24-29-8]]

^<<v24-29-8,8>>^ Eu, o Senhor  Todo-Poderoso, o Deus de Israel, os estou avisando para que não se deixem enganar pelos profetas que vivem no meio de vocês nem por aqueles que dizem que podem adivinhar o futuro. Não deem atenção aos sonhos deles.

[[v24-29-9]]

^<<v24-29-9,9>>^ Eles dizem mentiras em meu nome. Eu não os enviei. Eu, o Senhor , estou falando.’

[[v24-29-10]]

^<<v24-29-10,10>>^ "O Senhor  Deus diz ainda: ‘Quando os setenta anos da Babilônia passarem, eu mostrarei que me interesso por vocês e cumprirei a minha promessa de trazê-los de volta à pátria.

[[v24-29-11]]

^<<v24-29-11,11>>^ Só eu conheço os planos que tenho para vocês: prosperidade e não desgraça e um futuro cheio de esperança. Sou eu, o Senhor , quem está falando.

[[v24-29-12]]

^<<v24-29-12,12>>^ Então vocês vão me chamar e orar a mim, e eu responderei.

[[v24-29-13]]

^<<v24-29-13,13>>^ Vocês vão me procurar e me achar, pois vão me procurar com todo o coração.

[[v24-29-14]]

^<<v24-29-14,14>>^ Sim! Eu afirmo que vocês me encontrarão e que eu os levarei de volta à pátria. Eu os ajuntarei de todos os países e de todos os lugares por onde os espalhei. E levarei vocês de volta à terra de onde os tirei e levei como prisioneiros. Eu, o Senhor , estou falando.’

[[v24-29-15]]

^<<v24-29-15,15>>^ "Vocês dizem que o Senhor  lhes deu profetas aí na Babilônia.

[[v24-29-16]]

^<<v24-29-16,16>>^ Prestem atenção no que ele diz a respeito do rei que ocupa o trono de Davi e a respeito dos moradores de Jerusalém, isto é, dos parentes que não foram levados com vocês como prisioneiros.

[[v24-29-17]]

^<<v24-29-17,17>>^ O Senhor  Todo-Poderoso diz: ‘Eu mandarei contra eles guerra, fome e doença; e farei com que sejam como figos estragados, ruins demais para serem comidos.

[[v24-29-18]]

^<<v24-29-18,18>>^ Eu os perseguirei com guerra, fome e doença; e as nações do mundo ficarão horrorizadas com o que virem. Em todos os lugares para onde eu os espalhar, as pessoas ficarão chocadas e horrorizadas com o que aconteceu com eles. Zombarão deles e usarão o seu nome para rogar pragas.

[[v24-29-19]]

^<<v24-29-19,19>>^ Isso acontecerá porque não obedeceram à mensagem que eu sempre lhes enviei por meio dos meus servos , os profetas. Eles não quiseram me ouvir.

[[v24-29-20]]

^<<v24-29-20,20>>^ Mas agora todos vocês, que eu deixei o rei da Babilônia levar de Jerusalém como prisioneiros, escutem o que eu, o Senhor , estou dizendo.’

[[v24-29-21]]

^<<v24-29-21,21>>^ "O Senhor  Todo-Poderoso, o Deus de Israel, falou contra Acabe, filho de Colaías, e contra Zedequias, filho de Maaseias, que estão usando o nome de Deus para anunciar mentiras. Deus disse que os entregará nas mãos do rei Nabucodonosor, da Babilônia, e que este os mandará matar diante dos olhos de vocês.

[[v24-29-22]]

^<<v24-29-22,22>>^ Quando aqueles que foram levados como prisioneiros de Jerusalém para a Babilônia quiserem amaldiçoar alguém, vão dizer assim: ‘Que o Senhor  Deus faça com você o que fez com Zedequias e Acabe, que foram assados vivos por ordem do rei da Babilônia!’

[[v24-29-23]]

^<<v24-29-23,23>>^ Isso acontecerá com Zedequias e Acabe porque a sua conduta foi vergonhosa — cometeram adultério e, contra a vontade de Deus, contaram mentiras em seu nome. Deus sabe o que fizeram e é testemunha contra eles. O Senhor  falou."

[[v24-29-24]]

^<<v24-29-24,24>>^ O Senhor  Todo-Poderoso, o Deus de Israel, me mandou dizer o seguinte a Semaías, da cidade de Neelão: — Você enviou cartas em seu próprio nome a todo o povo de Jerusalém, a Sofonias, filho do sacerdote Maaseias, e a todos os outros sacerdotes. Nessas cartas, você dizia a Sofonias:

[[v24-29-25]]

^<<v24-29-25,25>>^ O Senhor  Todo-Poderoso, o Deus de Israel, me mandou dizer o seguinte a Semaías, da cidade de Neelão:

[[v24-29-26]]

^<<v24-29-26,26>>^ "O Senhor  Deus o fez sacerdote em lugar de Joiada, e agora você é o chefe dos serviços do Templo. É seu dever mandar prender qualquer louco que quiser passar por profeta e pôr uma coleira de ferro no pescoço dele.

[[v24-29-27]]

^<<v24-29-27,27>>^ Então, por que é que você não repreendeu Jeremias, da cidade de Anatote, que tem bancado o profeta no meio do povo?

[[v24-29-28]]

^<<v24-29-28,28>>^ Jeremias deve ser repreendido porque mandou dizer aos prisioneiros na Babilônia que eles iam ficar ali por muito tempo e que por isso deviam construir casas, morar nelas, plantar árvores frutíferas e comer as suas frutas."

[[v24-29-29]]

^<<v24-29-29,29>>^ O sacerdote Sofonias leu esta carta para mim.

'''

xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[Próximo Capítulo &#62;]