include::./index.adoc[]

[[v24-31-0]]
=== Jeremias, 31
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-31-1]]

^<<v24-31-1,1>>^ O Senhor  Deus diz: — Está chegando o tempo em que eu serei o Deus de todas as tribos  de Israel, e elas serão o meu povo.

[[v24-31-2]]

^<<v24-31-2,2>>^ No deserto, tive pena daqueles que haviam escapado da morte. Quando o povo de Israel procurava descanso,

[[v24-31-3]]

^<<v24-31-3,3>>^ eu, vindo de longe, apareci a eles. Povo de Israel, eu sempre os amei e continuo a mostrar que o meu amor por vocês é eterno.

[[v24-31-4]]

^<<v24-31-4,4>>^ Eu construirei de novo a nação. Mais uma vez, vocês pegarão os seus tamborins e dançarão de alegria.

[[v24-31-5]]

^<<v24-31-5,5>>^ Mais uma vez, vocês farão plantações de uva nos montes de Samaria, e quem plantar colherá as frutas.

[[v24-31-6]]

^<<v24-31-6,6>>^ Está chegando o tempo em que os vigias gritarão nas montanhas de Efraim: "Venham! Vamos subir até Sião , onde está o Senhor , nosso Deus!"

[[v24-31-7]]

^<<v24-31-7,7>>^ O Senhor  diz: "Cantem de alegria por causa de Israel, a maior de todas as nações. Cantem este hino de louvor: ‘O Senhor  salvou o seu povo, ele livrou o resto do povo de Israel.’

[[v24-31-8]]

^<<v24-31-8,8>>^ Eu os trarei do Norte e os ajuntarei dos lugares mais distantes da terra. Com eles virão os cegos e os aleijados, as mulheres grávidas e as que estão para dar à luz. Eles vão voltar como uma grande nação.

[[v24-31-9]]

^<<v24-31-9,9>>^ Quando eu os trouxer, eles virão chorando e orando. Eu os levarei para a beira de águas correntes, por uma estrada plana, onde não tropeçarão. Sou como um pai para Israel, e Efraim é o meu filho mais velho."

[[v24-31-10]]

^<<v24-31-10,10>>^ O Senhor  diz ainda: "Nações, escutem o que eu, o Senhor , estou dizendo e anunciem as minhas palavras nas ilhas e terras distantes. Eu espalhei o povo de Israel, mas vou ajuntá-lo de novo e guardá-lo como um pastor guarda o seu rebanho.

[[v24-31-11]]

^<<v24-31-11,11>>^ Eu libertei os descendentes de Jacó e os salvei das mãos de uma nação mais forte do que eles.

[[v24-31-12]]

^<<v24-31-12,12>>^ E vão chegar e cantar de alegria no monte Sião; vão se alegrar com os meus presentes, com os cereais, o vinho, o azeite, o gado e os carneiros. Eles serão como um jardim bem-regado e terão tudo o que precisarem.

[[v24-31-13]]

^<<v24-31-13,13>>^ Então as moças, os moços e os velhos vão dançar e se alegrar. Eu os animarei e mudarei o seu choro em alegria e a sua tristeza em prazer.

[[v24-31-14]]

^<<v24-31-14,14>>^ Alimentarei os sacerdotes com muita comida boa e darei ao meu povo tudo o que precisar. Eu, o Senhor , estou falando."

[[v24-31-15]]

^<<v24-31-15,15>>^ O Senhor  diz: "Ouviu-se um som em Ramá, o som de um choro amargo. Era Raquel chorando pelos seus filhos; ela não quer ser consolada, pois todos estão mortos.

[[v24-31-16]]

^<<v24-31-16,16>>^ Pare de chorar e enxugue as suas lágrimas. Tudo o que você fez pelos seus filhos será recompensado; eles voltarão da terra do inimigo. Sou eu, o Senhor , quem está falando.

[[v24-31-17]]

^<<v24-31-17,17>>^ Há esperança para você no futuro; os seus filhos voltarão para casa. Sou eu, o Senhor , quem está falando.

[[v24-31-18]]

^<<v24-31-18,18>>^ "Escuto estas queixas do povo de Israel: ‘Ó Deus, nós éramos como touros novos ainda não amansados, mas tu nos ensinaste a obedecer. Faze-nos voltar, ó Deus, e voltaremos a ti, pois tu és o Senhor , nosso Deus.

[[v24-31-19]]

^<<v24-31-19,19>>^ Nós nos afastamos de ti, mas logo nos arrependemos. Depois que nos castigaste, curvamos a nossa cabeça em sinal de tristeza.’

[[v24-31-20]]

^<<v24-31-20,20>>^ "Povo de Israel, você é o meu filho querido, o filho que eu mais amo. Sempre que digo o seu nome, penso em você com amor. O meu coração se comove, e eu certamente terei misericórdia de você. Sou eu, o Senhor , quem está falando.

[[v24-31-21]]

^<<v24-31-21,21>>^ Ponha avisos e marque a estrada; repare bem no caminho por onde você passar. Volte, povo de Israel, volte para as cidades que eram suas.

[[v24-31-22]]

^<<v24-31-22,22>>^ Povo rebelde, até quando você vai ficar na dúvida? Eu, o Senhor , criei uma coisa nova e diferente na terra: uma mulher protegendo um homem."

[[v24-31-23]]

^<<v24-31-23,23>>^ O Senhor  Todo-Poderoso, o Deus de Israel, diz: — Quando eu trouxer os israelitas de volta à sua pátria, eles de novo dirão na terra de Judá e nas suas cidades: "Que o Senhor  abençoe o monte sagrado  de Jerusalém, onde ele, o Deus de justiça, mora."

[[v24-31-24]]

^<<v24-31-24,24>>^ O povo viverá em Judá e em todas as suas cidades; e haverá lavradores e também pastores com os seus rebanhos.

[[v24-31-25]]

^<<v24-31-25,25>>^ Eu animarei os cansados e darei comida a todos os que estão fracos de fome.

[[v24-31-26]]

^<<v24-31-26,26>>^ Então eu acordei descansado e bem-disposto.

[[v24-31-27]]

^<<v24-31-27,27>>^ — Eu, o Senhor , digo que está chegando o tempo em que encherei de gente e de animais as terras de Israel e de Judá.

[[v24-31-28]]

^<<v24-31-28,28>>^ Assim como cuidei deles para arrancar, derrubar, arruinar, destruir e arrasar, assim também cuidarei deles para plantar e construir. Sou eu, o Senhor , quem está falando.

[[v24-31-29]]

^<<v24-31-29,29>>^ Quando esse tempo chegar, o povo não dirá mais: "Os pais comeram uvas verdes, mas foram os dentes dos filhos que ficaram ásperos."

[[v24-31-30]]

^<<v24-31-30,30>>^ Pelo contrário, quem comer uvas verdes é que vai ficar com os dentes ásperos; e cada um morrerá por causa do seu próprio pecado.

[[v24-31-31]]

^<<v24-31-31,31>>^ O Senhor  Deus diz: — Está chegando o tempo em que farei uma nova aliança  com o povo de Israel e com o povo de Judá.

[[v24-31-32]]

^<<v24-31-32,32>>^ Essa aliança não será como aquela que eu fiz com os antepassados deles no dia em que os peguei pela mão e os tirei da terra do Egito. Embora eu fosse o Deus deles, eles quebraram a minha aliança. Sou eu, o Senhor , quem está falando.

[[v24-31-33]]

^<<v24-31-33,33>>^ Quando esse tempo chegar, farei com o povo de Israel esta aliança: eu porei a minha lei  na mente deles e no coração deles a escreverei; eu serei o Deus deles, e eles serão o meu povo. Sou eu, o Senhor , quem está falando.

[[v24-31-34]]

^<<v24-31-34,34>>^ Ninguém vai precisar ensinar o seu patrício nem o seu parente, dizendo: "Procure conhecer a Deus, o Senhor ." Porque todos me conhecerão, tanto as pessoas mais importantes como as mais humildes. Pois eu perdoarei os seus pecados e nunca mais lembrarei das suas maldades. Eu, o Senhor , estou falando.

[[v24-31-35]]

^<<v24-31-35,35>>^ O Senhor  fez o sol para ser a luz do dia, a lua e as estrelas para brilharem de noite. Deus faz o mar ficar bravo e faz rugir as suas ondas; o seu nome é Senhor , o Todo-Poderoso.

[[v24-31-36]]

^<<v24-31-36,36>>^ Ele promete que, enquanto durarem as leis da natureza, Israel será sempre uma nação.

[[v24-31-37]]

^<<v24-31-37,37>>^ Se algum dia for possível medir os céus e examinar os alicerces da terra, então eu rejeitarei o povo de Israel por causa de tudo o que ele tem feito. O Senhor  Deus está falando.

[[v24-31-38]]

^<<v24-31-38,38>>^ — Está chegando o tempo — diz o Senhor  — em que esta cidade será construída de novo, desde a torre de Hananel até o Portão da Esquina.

[[v24-31-39]]

^<<v24-31-39,39>>^ Dali a linha da divisa continuará até o monte Garebe e daí vai virar na direção de Goa.

[[v24-31-40]]

^<<v24-31-40,40>>^ Será sagrado para mim, o Senhor , o vale todo onde são jogados os mortos e o lixo. Serão sagrados também todos os campos que ficam além do riacho do Cedrom até o Portão dos Cavalos, a leste. Nunca mais Jerusalém será derrubada, nem destruída.

'''

xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[Próximo Capítulo &#62;]