include::./index.adoc[]

[[v24-41-0]]
=== Jeremias, 41
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-41-1]]

^<<v24-41-1,1>>^ No sétimo mês daquele ano, Ismael, filho de Netanias e neto de Elisama, que era da família do rei, foi até Mispa com dez homens para encontrar-se com Gedalias. Enquanto estavam todos ali, tomando uma refeição juntos,

[[v24-41-2]]

^<<v24-41-2,2>>^ Ismael e os dez homens que estavam com ele pegaram as suas espadas e mataram Gedalias. Assim mataram aquele que tinha sido posto pelo rei da Babilônia como governador do país.

[[v24-41-3]]

^<<v24-41-3,3>>^ Ismael também matou todos os judeus que estavam com Gedalias em Mispa e os soldados babilônios que estavam lá.

[[v24-41-4]]

^<<v24-41-4,4>>^ No dia seguinte, antes que alguém soubesse que Gedalias tinha sido morto,

[[v24-41-5]]

^<<v24-41-5,5>>^ chegaram ali oitenta homens. Eles vinham de Siquém, Siló e Samaria. Estavam com a barba raspada e as roupas rasgadas e tinham feito cortes no corpo. Eles traziam cereais e incenso para oferecer a Deus, o Senhor , no Templo.

[[v24-41-6]]

^<<v24-41-6,6>>^ Então Ismael saiu chorando de Mispa e foi encontrar-se com eles. Quando chegou perto deles, disse: — Entrem e venham ver Gedalias.

[[v24-41-7]]

^<<v24-41-7,7>>^ Quando eles entraram na cidade, Ismael e os seus homens os mataram e jogaram os corpos num poço.

[[v24-41-8]]

^<<v24-41-8,8>>^ Mas havia no grupo dez homens que disseram a Ismael: — Não nos mate! Temos trigo, cevada , azeite e mel escondidos no campo. Aí ele desistiu e não os matou como havia feito com os seus companheiros.

[[v24-41-9]]

^<<v24-41-9,9>>^ Era grande o poço em que Ismael jogou os corpos dos homens que ele havia matado. O rei Asa o havia cavado para se prevenir contra os ataques do rei Baasa, de Israel. Ismael encheu esse poço com os corpos dos homens que haviam sido mortos.

[[v24-41-10]]

^<<v24-41-10,10>>^ E depois Ismael partiu para o país de Amom, levando como prisioneiros as filhas do rei e todo o resto do povo que estava em Mispa. O comandante-geral Nebuzaradã tinha deixado Gedalias como o responsável por essa gente.

[[v24-41-11]]

^<<v24-41-11,11>>^ Joanã, filho de Careá, e todos os chefes do exército que estavam com ele ouviram falar do crime que Ismael havia cometido.

[[v24-41-12]]

^<<v24-41-12,12>>^ Então reuniram os seus soldados e foram combater contra Ismael. Eles o alcançaram perto do grande poço de Gibeão.

[[v24-41-13]]

^<<v24-41-13,13>>^ Quando os prisioneiros de Ismael viram Joanã e os chefes do exército com ele, ficaram alegres.

[[v24-41-14]]

^<<v24-41-14,14>>^ Aí viraram e correram para o lado de Joanã.

[[v24-41-15]]

^<<v24-41-15,15>>^ Mas Ismael e oito dos seus homens escaparam de Joanã e fugiram para o país de Amom.

[[v24-41-16]]

^<<v24-41-16,16>>^ Então Joanã e os chefes do exército que estavam com ele reuniram os soldados, as mulheres, as crianças e os eunucos  que Ismael havia levado de Mispa como prisioneiros, depois de ter matado Gedalias. Assim reuniram a gente que Joanã havia tomado de Ismael em Gibeão

[[v24-41-17]]

^<<v24-41-17,17>>^ e partiram, parando um pouco em Gerute-Quimã, perto de Belém. Eles queriam ir até o Egito

[[v24-41-18]]

^<<v24-41-18,18>>^ para fugir dos babilônios. Estavam com medo deles porque Ismael tinha matado Gedalias, aquele que havia sido posto como governador do país pelo rei da Babilônia.

'''

xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[&#60; Capítulo Anterior] | <<v24-41-0,Topo>> | xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[Próximo Capítulo &#62;]