include::./index.adoc[]

[[v24-22-0]]
=== Jeremias, 22
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-22-1]]

^<<v24-22-1,1>>^ O Senhor  Deus mandou que eu fosse ao palácio do rei de Judá, descendente de Davi, para dizer ao rei, aos seus oficiais e ao povo de Jerusalém que escutassem estas palavras do Senhor :

[[v24-22-2]]

^<<v24-22-2,2>>^ O Senhor  Deus mandou que eu fosse ao palácio do rei de Judá, descendente de Davi, para dizer ao rei, aos seus oficiais e ao povo de Jerusalém que escutassem estas palavras do Senhor :

[[v24-22-3]]

^<<v24-22-3,3>>^ — Eu, o Senhor , lhes digo: façam o que é justo e honesto. Protejam dos exploradores aqueles que estão sendo explorados. Não maltratem, nem explorem os estrangeiros, os órfãos e as viúvas. Não matem pessoas inocentes neste lugar sagrado.

[[v24-22-4]]

^<<v24-22-4,4>>^ Se vocês, de fato, fizerem o que eu estou mandando, então os descendentes de Davi continuarão a ser reis. Eles continuarão a passar pelos portões deste palácio sentados em carros e montados em cavalos, junto com os seus oficiais e com o seu povo.

[[v24-22-5]]

^<<v24-22-5,5>>^ Mas, se vocês não obedecerem às minhas palavras, então eu juro por mim mesmo que este palácio se tornará um monte de pedras. Sou eu, o Senhor , quem está falando.

[[v24-22-6]]

^<<v24-22-6,6>>^ — O palácio real de Judá é lindo como a terra de Gileade e como os montes Líbanos, mas eu farei com que vire um deserto, um lugar onde ninguém mora.

[[v24-22-7]]

^<<v24-22-7,7>>^ Estou mandando homens para destruí-lo. Todos eles virão com os seus machados, derrubarão as suas lindas colunas de madeira de cedro e as jogarão no fogo.

[[v24-22-8]]

^<<v24-22-8,8>>^ — Depois, muitos estrangeiros vão passar e perguntar um ao outro por que é que eu, o Senhor , fiz uma coisa dessas com esta grande cidade.

[[v24-22-9]]

^<<v24-22-9,9>>^ Aí eles responderão que foi porque vocês abandonaram a aliança  que fizeram comigo, o Deus de vocês, e adoraram e serviram outros deuses.

[[v24-22-10]]

^<<v24-22-10,10>>^ Povo de Judá, não chore pelo rei Josias, nem lamente a sua morte, mas chore amargamente por Joacaz , seu filho. Vão levá-lo, e ele nunca mais voltará, nunca mais verá a terra onde nasceu.

[[v24-22-11]]

^<<v24-22-11,11>>^ Pois o que o Senhor  Deus diz a respeito de Joacaz, filho de Josias, que ficou no lugar do seu pai como rei de Judá, é o seguinte: — Ele foi embora daqui para sempre, para nunca mais voltar.

[[v24-22-12]]

^<<v24-22-12,12>>^ Ele morrerá no país para onde o levaram e nunca mais verá esta terra.

[[v24-22-13]]

^<<v24-22-13,13>>^ Ai daquele que constrói a sua casa com injustiça e desonestidade, não pagando os salários dos seus vizinhos e fazendo com que trabalhem de graça!

[[v24-22-14]]

^<<v24-22-14,14>>^ Ai daquele que diz: "Vou construir para mim uma casa bem grande, com quartos espaçosos no andar de cima!" Então ele põe janelas na casa, forra as paredes com cedro e pinta de vermelho.

[[v24-22-15]]

^<<v24-22-15,15>>^ Será que você é rei só porque constrói casas forradas de cedro, melhores do que as dos outros? Josias, o seu pai, viveu uma vida normal; sempre foi justo e honesto, e tudo o que ele fez deu certo.

[[v24-22-16]]

^<<v24-22-16,16>>^ Ele tratou com justiça os pobres e os necessitados, e tudo lhe correu bem. Quem faz isso mostra que, de fato, me conhece. Sou eu, o Senhor , quem está falando.

[[v24-22-17]]

^<<v24-22-17,17>>^ Mas você só enxerga os seus interesses egoístas. Você mata os inocentes e explora o seu povo com violência.

[[v24-22-18]]

^<<v24-22-18,18>>^ Por isso, Deus diz o seguinte a respeito de Jeoaquim, rei de Judá e filho de Josias: "Ninguém vai chorar a morte de Jeoaquim nem dizer: ‘Que coisa horrível, amigo, que coisa horrível!’ Ninguém vai chorar por ele nem gritar: ‘Meu senhor! Meu rei!’

[[v24-22-19]]

^<<v24-22-19,19>>^ Ele será sepultado como se sepulta um jumento morto; será arrastado e jogado para fora dos portões de Jerusalém."

[[v24-22-20]]

^<<v24-22-20,20>>^ Povo de Jerusalém, vá até o Líbano e grite, vá à terra de Basã e grite bem alto. Que a sua voz seja ouvida desde as montanhas de Moabe, pois todos os países amigos que você tem foram derrotados!

[[v24-22-21]]

^<<v24-22-21,21>>^ Deus lhe falou quando você estava bem de vida, mas você não quis ouvir. Isso é o que você tem feito desde a sua mocidade, pois nunca obedeceu a Deus.

[[v24-22-22]]

^<<v24-22-22,22>>^ As suas autoridades serão espalhadas pelo vento, e os seus amigos serão levados como prisioneiros de guerra. Então a sua cidade será humilhada e envergonhada por causa de todo o mal que você tem feito.

[[v24-22-23]]

^<<v24-22-23,23>>^ Você, que está muito seguro entre os cedros trazidos do Líbano, como vai gemer quando chegarem as dores, dores iguais às da mulher na hora do parto!

[[v24-22-24]]

^<<v24-22-24,24>>^ O Senhor  Deus disse a Joaquim , rei de Judá e filho de Jeoaquim: — Juro pela minha vida que, ainda que você fosse um anel de rei na minha mão direita, eu o arrancaria.

[[v24-22-25]]

^<<v24-22-25,25>>^ Vou entregá-lo às pessoas que o querem matar, e das quais você tem medo: ao rei Nabucodonosor, da Babilônia, e aos seus soldados.

[[v24-22-26]]

^<<v24-22-26,26>>^ Jogarei você e a sua mãe numa terra estranha, onde vocês não nasceram, e lá morrerão.

[[v24-22-27]]

^<<v24-22-27,27>>^ Vocês terão saudades da sua terra, porém não voltarão para lá.

[[v24-22-28]]

^<<v24-22-28,28>>^ Então eu disse: — Será que Joaquim é como um pote quebrado que foi jogado fora e que ninguém mais quer? Por que é que ele e os seus filhos foram levados e jogados numa terra que não conhecem?

[[v24-22-29]]

^<<v24-22-29,29>>^ Ó terra, terra, terra! Escute o que o Senhor  disse:

'''

xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[&#60; Capítulo Anterior] | <<v24-22-0,Topo>> | xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[Próximo Capítulo &#62;]