include::./index.adoc[]

[[v24-19-0]]
=== Jeremias, 19
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-19-1]]

^<<v24-19-1,1>>^ O Senhor  Deus me disse que fosse comprar um pote de barro. Disse que levasse comigo algumas autoridades do povo e alguns sacerdotes mais velhos

[[v24-19-2]]

^<<v24-19-2,2>>^ e fosse ao vale de Ben-Hinom, na entrada do Portão dos Cacos. Ali eu devia anunciar em voz bem alta a mensagem que ele ia me dar.

[[v24-19-3]]

^<<v24-19-3,3>>^ Deus me mandou dizer o seguinte: — Reis de Judá e povo de Jerusalém, escutem o que eu, o Senhor  Todo-Poderoso, o Deus de Israel, vou dizer. Vou fazer cair sobre este lugar uma desgraça tão grande, que todos os que ouvirem falar dela ficarão horrorizados.

[[v24-19-4]]

^<<v24-19-4,4>>^ Vou fazer isso porque o meu povo me abandonou e profanou  este lugar, queimando aqui incenso a outros deuses. Mas nem esse povo, nem os seus antepassados, nem os reis de Judá sabiam nada a respeito desses deuses. Essa gente encheu este lugar com o sangue de pessoas inocentes

[[v24-19-5]]

^<<v24-19-5,5>>^ e construiu altares para o deus Baal , a fim de queimar os seus filhos no fogo, como sacrifício . Eu não dei ordem para isso, não falei disso e nunca pensei nisso.

[[v24-19-6]]

^<<v24-19-6,6>>^ Por isso, eu, o Senhor , digo que chegará o tempo em que este lugar não se chamará mais Tofete nem vale de Ben-Hinom e sim "vale da Matança".

[[v24-19-7]]

^<<v24-19-7,7>>^ Neste lugar, destruirei todos os planos do povo de Judá e de Jerusalém. Deixarei que os inimigos os derrotem e os matem na batalha. Darei os corpos deles como alimento para as aves e as feras.

[[v24-19-8]]

^<<v24-19-8,8>>^ Destruirei esta cidade de modo tão terrível, que cada um que passar por ela ficará espantado e horrorizado ao ver tudo o que aconteceu.

[[v24-19-9]]

^<<v24-19-9,9>>^ Os inimigos cercarão a cidade e procurarão matar os seus moradores. O cerco será tão terrível, que a gente que vive em Jerusalém comerá a carne dos seus filhos e filhas e devorará os seus próprios vizinhos.

[[v24-19-10]]

^<<v24-19-10,10>>^ Então o Senhor  me mandou quebrar o pote na frente dos homens que haviam ido comigo.

[[v24-19-11]]

^<<v24-19-11,11>>^ E mandou dizer-lhes que o Senhor  Todo-Poderoso tinha dito o seguinte: — Como se quebra um pote, e ele não pode mais ser consertado, assim eu quebrarei este povo e esta cidade. Os seus mortos terão de ser sepultados até mesmo em Tofete, pois não haverá outro lugar para sepultá-los.

[[v24-19-12]]

^<<v24-19-12,12>>^ Tratarei esta cidade e os seus moradores assim: farei com que ela fique como o vale de Tofete. Sou eu, o Senhor , quem está falando.

[[v24-19-13]]

^<<v24-19-13,13>>^ As casas de Jerusalém e as casas dos reis de Judá ficarão imundas como o vale de Tofete. Também ficarão imundas todas as casas onde queimaram incenso no terraço para adorar as estrelas e onde derramaram bebidas como oferta a outros deuses.

[[v24-19-14]]

^<<v24-19-14,14>>^ Então voltei de Tofete, onde o Senhor  me havia mandado anunciar a sua mensagem. Fui ao pátio do Templo, fiquei de pé ali e falei a todo o povo

[[v24-19-15]]

^<<v24-19-15,15>>^ que o Senhor  Todo-Poderoso, o Deus de Israel, tinha dito o seguinte: — Vocês são teimosos e não querem ouvir o que eu digo; por isso, farei cair sobre esta cidade e sobre todos os povoados vizinhos toda a desgraça que prometi.

'''

xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[&#60; Capítulo Anterior] | <<v24-19-0,Topo>> | xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[Próximo Capítulo &#62;]