include::./index.adoc[]

[[v24-49-0]]
=== Jeremias, 49
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-49-1]]

^<<v24-49-1,1>>^ O Senhor  Deus disse o seguinte a respeito dos amonitas: — Onde estão os homens de Israel? Será que não há alguém que defenda a terra que Deus lhes deu para ser sua propriedade? Por que foi que deixaram que o deus Moloque  tomasse a terra da tribo  de Gade e que os seus adoradores fossem morar lá?

[[v24-49-2]]

^<<v24-49-2,2>>^ Mas está chegando o dia em que farei o povo da cidade de Rabá ouvir barulho de guerra. Essa cidade amonita ficará arrasada, e os seus povoados serão destruídos pelo fogo. Então o povo de Israel tomará outra vez a sua terra daqueles que a tomaram dele. Sou eu, o Senhor , quem está falando.

[[v24-49-3]]

^<<v24-49-3,3>>^ Grite, povo de Hesbom! A cidade de Ai está destruída! Chorem, mulheres de Rabá! Vistam roupa feita de pano grosseiro e lamentem. Corram de um lado para outro, sem rumo. Moloque, o deus de vocês, será levado como prisioneiro, junto com os seus sacerdotes e todas as autoridades.

[[v24-49-4]]

^<<v24-49-4,4>>^ Povo infiel, por que é que vocês se gabam? O seu poder está no fim. Por que é que vocês confiam na sua própria força e dizem que ninguém terá coragem de atacá-los?

[[v24-49-5]]

^<<v24-49-5,5>>^ De todos os lados, eu vou fazer com que o terror caia sobre vocês, e todos fugirão. Correrão para salvar a vida, e não ficará ninguém para reunir de novo as suas tropas. Sou eu, o Senhor , o Deus Todo-Poderoso, quem está falando.

[[v24-49-6]]

^<<v24-49-6,6>>^ — Porém no futuro farei com que os amonitas voltem a ser o que eram antes. Eu, o Senhor , estou falando.

[[v24-49-7]]

^<<v24-49-7,7>>^ O Senhor  Todo-Poderoso disse o seguinte a respeito do país de Edom: — Será que o povo da cidade de Temã perdeu o juízo? Será que os seus conselheiros não sabem mais dar conselhos? A sabedoria deles acabou?

[[v24-49-8]]

^<<v24-49-8,8>>^ Moradores de Dedã, virem e corram! Fujam e se escondam! Eu vou destruir os descendentes de Esaú, pois chegou a hora de castigá-los.

[[v24-49-9]]

^<<v24-49-9,9>>^ Quando alguém colhe uvas, sempre deixa algumas nos pés; e, quando os ladrões chegam de noite, levam apenas o que interessa.

[[v24-49-10]]

^<<v24-49-10,10>>^ Mas eu tirei todos os tesouros dos descendentes de Esaú e acabei com os seus esconderijos, e assim eles não podem mais se esconder. O povo de Edom e os seus parentes e vizinhos estão destruídos. Não escapou ninguém.

[[v24-49-11]]

^<<v24-49-11,11>>^ Deixem os seus órfãos comigo, que eu tomarei conta deles. As suas viúvas podem confiar em mim.

[[v24-49-12]]

^<<v24-49-12,12>>^ O Senhor  disse ainda: — Se até os que não mereciam foram castigados, será que você está pensando que ficará sem castigo? É claro que você também será castigado.

[[v24-49-13]]

^<<v24-49-13,13>>^ Eu mesmo jurei que a cidade de Bosra vai se tornar um espetáculo horrível e um lugar deserto; os outros vão zombar dela e usar o seu nome para rogar pragas. E todos os povoados em volta da cidade ficarão arrasados para sempre. Eu, o Senhor , estou falando.

[[v24-49-14]]

^<<v24-49-14,14>>^ Então eu disse: — Recebi uma mensagem de Deus, o Senhor . Ele enviou um mensageiro para dizer às nações o seguinte: "Reúnam os seus exércitos e ataquem Edom!"

[[v24-49-15]]

^<<v24-49-15,15>>^ O Senhor  fará de você, Edom, uma nação fraca, e ninguém o respeitará.

[[v24-49-16]]

^<<v24-49-16,16>>^ O seu orgulho o enganou. Não pense que alguém tem medo de você. Você vive nas cavernas das rochas, lá no alto da montanha; mas, embora more tão alto como uma águia, o Senhor  o derrubará. Eu, o Senhor , estou falando.

[[v24-49-17]]

^<<v24-49-17,17>>^ O Senhor  disse: — Cairá sobre Edom uma destruição tão horrível, que todos os que passarem ficarão espantados e horrorizados com o que virem.

[[v24-49-18]]

^<<v24-49-18,18>>^ Acontecerá com Edom o que aconteceu com Sodoma e Gomorra, quando foram destruídas junto com as cidades vizinhas. Ninguém viverá mais lá, nem mesmo por pouco tempo. Sou eu, o Senhor , quem está falando.

[[v24-49-19]]

^<<v24-49-19,19>>^ Assim como um leão sai da floresta na beira do rio Jordão e sobe até a terra de pastos verdes, assim eu virei e farei com que os edomitas fujam correndo da sua terra. Então o chefe que eu escolher governará a nação. Quem pode se comparar comigo? Quem tem coragem de me desafiar? Que governador poderia me enfrentar?

[[v24-49-20]]

^<<v24-49-20,20>>^ Por isso, prestem atenção no plano que eu, o Senhor , fiz contra o povo de Edom; escutem o que vou fazer com os moradores da cidade de Temã. Até as crianças e os velhinhos serão arrastados, e todos ficarão horrorizados.

[[v24-49-21]]

^<<v24-49-21,21>>^ Quando Edom cair, o barulho será tão grande, que a terra tremerá, e os gritos de pavor serão ouvidos até no golfo de Ácaba.

[[v24-49-22]]

^<<v24-49-22,22>>^ O inimigo atacará a cidade de Bosra como uma águia que, com as asas abertas, se atira lá do alto contra a sua vítima. Naquele dia, os soldados de Edom terão tanto medo como a mulher que está com dores de parto.

[[v24-49-23]]

^<<v24-49-23,23>>^ O Senhor  Deus disse o seguinte a respeito de Damasco: — Os moradores das cidades de Hamate e Arpade estão preocupados e assustados porque ouviram más notícias. O medo rola em cima deles como o mar, e eles não têm descanso.

[[v24-49-24]]

^<<v24-49-24,24>>^ O povo de Damasco está fraco e virou para fugir apavorado. Estão cheios de dor e de angústia como uma mulher que está com dores de parto.

[[v24-49-25]]

^<<v24-49-25,25>>^ Essa famosa cidade, que era feliz, agora está completamente abandonada.

[[v24-49-26]]

^<<v24-49-26,26>>^ Portanto, naquele dia os moços e todos os soldados serão mortos nas ruas da cidade. Sou eu, o Senhor  Todo-Poderoso, quem está falando.

[[v24-49-27]]

^<<v24-49-27,27>>^ Eu queimarei as muralhas de Damasco, e o fogo destruirá os palácios de Ben-Hadade.

[[v24-49-28]]

^<<v24-49-28,28>>^ O Senhor  Deus disse o seguinte a respeito da tribo  de Quedar e das autoridades da cidade de Hazor, que foram derrotadas pelo rei Nabucodonosor, da Babilônia: — Saiam e ataquem o povo de Quedar; destruam essa tribo do Oriente!

[[v24-49-29]]

^<<v24-49-29,29>>^ Peguem as suas barracas, os seus rebanhos, as cortinas das suas barracas e tudo o que encontrarem nelas. Tomem os seus camelos e digam: "Em toda parte, o povo está com medo!"

[[v24-49-30]]

^<<v24-49-30,30>>^ — Povo de Hazor, eu, o Senhor , estou avisando vocês: fujam para longe e se escondam. O rei Nabucodonosor, da Babilônia, que planejou atacá-los, diz o seguinte:

[[v24-49-31]]

^<<v24-49-31,31>>^ "Vamos! Ataquem aquela gente que pensa que está firme e segura! A cidade deles fica longe das outras e não tem portões nem fechaduras." Sou eu, o Senhor , quem está falando.

[[v24-49-32]]

^<<v24-49-32,32>>^ — Tomem os camelos e todo o gado deles! Eu espalharei por toda parte essa gente que corta o cabelo bem curto e farei com que a desgraça caia sobre eles de todos os lados. Sou eu, o Senhor , quem está falando.

[[v24-49-33]]

^<<v24-49-33,33>>^ Hazor vai virar para sempre um deserto, um lugar onde somente lobos viverão. Ninguém vai morar ali, nem por pouco tempo.

[[v24-49-34]]

^<<v24-49-34,34>>^ Logo depois que Zedequias se tornou rei de Judá, o Senhor  Deus me falou sobre o país de Elão.

[[v24-49-35]]

^<<v24-49-35,35>>^ O Senhor  Todo-Poderoso disse: — Eu matarei todos os flecheiros que fizeram de Elão um país poderoso.

[[v24-49-36]]

^<<v24-49-36,36>>^ Farei com que os ventos soprem de todos os lados contra Elão, e o seu povo se espalhará por toda parte, até que não haja mais nenhum país para onde eles não tenham fugido.

[[v24-49-37]]

^<<v24-49-37,37>>^ Vou fazer com que o povo de Elão fique com medo dos seus inimigos, daqueles que os querem matar. Na minha grande ira , eu acabarei com eles; mandarei exércitos contra eles até que sejam completamente destruídos. Sou eu, o Senhor , quem está falando.

[[v24-49-38]]

^<<v24-49-38,38>>^ Destruirei os reis e os líderes de Elão e colocarei ali o meu trono.

[[v24-49-39]]

^<<v24-49-39,39>>^ Porém no futuro farei com que o país de Elão volte a ser como era antes. Eu, o Senhor , falei.

'''

xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[Próximo Capítulo &#62;]