include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-32-1]]

^<<v24-32-1,1>>^ No ano décimo do reinado de Zedequias em Judá, que era o ano décimo oitavo do reinado de Nabucodonosor na Babilônia, o Senhor  Deus falou comigo.

[[v24-32-2]]

^<<v24-32-2,2>>^ Nesse tempo, o exército do rei da Babilônia cercava Jerusalém, e eu estava preso no pátio do palácio real.

[[v24-32-3]]

^<<v24-32-3,3>>^ O rei Zedequias havia mandado me prender, acusando-me de anunciar que o Senhor  tinha dito o seguinte: "Eu entregarei esta cidade ao rei da Babilônia, e ele a conquistará.

[[v24-32-4]]

^<<v24-32-4,4>>^ O rei Zedequias não escapará dos babilônios, mas será entregue ao rei deles. Zedequias verá o rei da Babilônia cara a cara e falará com ele pessoalmente.

[[v24-32-5]]

^<<v24-32-5,5>>^ Será levado para a Babilônia e ficará ali até que eu cuide dele. Mesmo que lute contra os babilônios, não poderá vencer. Eu, o Senhor , estou falando."

[[v24-32-6]]

^<<v24-32-6,6>>^ O Senhor  Deus me disse

[[v24-32-7]]

^<<v24-32-7,7>>^ que Hanamel, filho do meu tio Salum, ia me procurar e pedir que eu comprasse as terras dele em Anatote. Isso porque sou o seu parente mais chegado e tenho o direito de comprá-las.

[[v24-32-8]]

^<<v24-32-8,8>>^ Então, exatamente como o Senhor  tinha dito, o meu primo Hanamel me procurou no pátio da guarda e me disse: — Compre as minhas terras que ficam em Anatote, no território de Benjamim. Você é o meu parente mais chegado e por isso tem o direito de comprar essas terras e ficar com elas. Aí entendi que era Deus que estava me mandando fazer isso.

[[v24-32-9]]

^<<v24-32-9,9>>^ Assim comprei as terras de Hanamel e pesei o dinheiro para ele. O preço foi de duzentos gramas de prata.

[[v24-32-10]]

^<<v24-32-10,10>>^ Assinei a escritura e fechei-a com um selo . Depois, chamei testemunhas e pesei o dinheiro numa balança.

[[v24-32-11]]

^<<v24-32-11,11>>^ Então peguei a cópia fechada com o selo, a qual tinha o contrato e as condições, e também a cópia aberta

[[v24-32-12]]

^<<v24-32-12,12>>^ e dei as duas a Baruque, filho de Nerias e neto de Maaseias. Fiz isso na frente de Hanamel, das testemunhas que assinaram a escritura e de todos os judeus que estavam sentados no pátio.

[[v24-32-13]]

^<<v24-32-13,13>>^ Diante de todos eles, eu disse a Baruque:

[[v24-32-14]]

^<<v24-32-14,14>>^ — O Senhor  Todo-Poderoso, o Deus de Israel, mandou que você pegue estas escrituras de compra, tanto a cópia fechada com o selo como a aberta, e as coloque num pote de barro para que durem muitos anos.

[[v24-32-15]]

^<<v24-32-15,15>>^ O Senhor  Todo-Poderoso, o Deus de Israel, disse que neste país ainda serão compradas casas, terras e plantações de uvas.

[[v24-32-16]]

^<<v24-32-16,16>>^ Depois que dei a Baruque, filho de Nerias, a escritura de compra, eu orei assim:

[[v24-32-17]]

^<<v24-32-17,17>>^ — Ó Senhor , meu Deus, com o teu grande poder e com a tua força, fizeste o céu e a terra. Nada é impossível para ti.

[[v24-32-18]]

^<<v24-32-18,18>>^ Tens sido bondoso para milhares de pessoas, mas também tens castigado os filhos por causa dos pecados dos seus pais. Tu és o grande e poderoso Deus; o teu nome é Senhor , o Todo-Poderoso.

[[v24-32-19]]

^<<v24-32-19,19>>^ Tu fazes grandes planos e coisas maravilhosas. Tu vês tudo o que as pessoas fazem e tratas cada uma de acordo com o seu modo de agir e de viver.

[[v24-32-20]]

^<<v24-32-20,20>>^ Fizeste milagres e maravilhas na terra do Egito e continuas a fazer o mesmo até hoje, tanto em Israel como em todas as outras nações. Por isso, agora és conhecido em toda parte.

[[v24-32-21]]

^<<v24-32-21,21>>^ Tiraste o povo de Israel da terra do Egito por meio do teu poder e da tua força e por meio de milagres e maravilhas que encheram de terror os nossos inimigos.

[[v24-32-22]]

^<<v24-32-22,22>>^ Deste aos israelitas esta terra boa e rica, como havias prometido aos seus antepassados.

[[v24-32-23]]

^<<v24-32-23,23>>^ Mas, quando eles entraram nesta terra e tomaram posse dela, não obedeceram aos teus mandamentos, nem viveram de acordo com os teus ensinamentos; não fizeram nada daquilo que havias mandado. Por isso, fizeste cair sobre eles toda esta desgraça.

[[v24-32-24]]

^<<v24-32-24,24>>^ — Os babilônios construíram rampas de terra em volta das muralhas da cidade a fim de invadi-la e agora estão atacando. A guerra, a fome e as doenças vão fazer a cidade cair nas mãos deles. Como vês, tudo o que disseste aconteceu.

[[v24-32-25]]

^<<v24-32-25,25>>^ No entanto, Senhor , meu Deus, tu me mandaste comprar terras na presença de testemunhas, apesar de os babilônios estarem quase tomando a cidade.

[[v24-32-26]]

^<<v24-32-26,26>>^ Então o Senhor  me respondeu:

[[v24-32-27]]

^<<v24-32-27,27>>^ — Eu sou o Senhor , o Deus de toda a humanidade. Nada é impossível para mim.

[[v24-32-28]]

^<<v24-32-28,28>>^ Por isso, vou entregar esta cidade ao rei Nabucodonosor, da Babilônia, e ao seu exército, e eles a tomarão.

[[v24-32-29]]

^<<v24-32-29,29>>^ Os babilônios, que estão atacando, vão entrar na cidade e pôr fogo nela. Eles queimarão as casas onde o povo me tem provocado queimando incenso ao deus Baal  nos terraços e derramando bebidas como oferta a outros deuses.

[[v24-32-30]]

^<<v24-32-30,30>>^ Desde o princípio, o povo de Israel e o povo de Judá só têm feito coisas más. As suas maldades têm provocado a minha ira .

[[v24-32-31]]

^<<v24-32-31,31>>^ Esta cidade tem provocado a minha ira e o meu furor desde o dia em que foi construída. Eu resolvi acabar com ela

[[v24-32-32]]

^<<v24-32-32,32>>^ por causa de todas as maldades que têm sido feitas pelo povo de Israel e pelo povo de Judá, pelos seus reis e autoridades, pelos seus sacerdotes e profetas  e pelo povo de Jerusalém.

[[v24-32-33]]

^<<v24-32-33,33>>^ Eles me viraram as costas. E, embora eu continuasse ensinando essa gente, eles não escutaram, não aprenderam a lição, nem deram atenção às ameaças.

[[v24-32-34]]

^<<v24-32-34,34>>^ Até ídolos horrorosos eles colocaram no Templo construído em meu nome e o profanaram .

[[v24-32-35]]

^<<v24-32-35,35>>^ No vale de Ben-Hinom, eles construíram altares ao deus Baal, para ali queimar os seus filhos e as suas filhas em honra do deus Moloque . Eu não lhes dei ordem para isso e nunca pensei que eles fizessem uma coisa tão nojenta como essa e levassem o povo de Judá a pecar.

[[v24-32-36]]

^<<v24-32-36,36>>^ Depois, o Senhor , o Deus de Israel, disse o seguinte: — Jeremias, o povo anda dizendo que a guerra, a fome e as doenças vão fazer esta cidade cair nas mãos do rei da Babilônia. Agora, escute o que vou dizer!

[[v24-32-37]]

^<<v24-32-37,37>>^ Vou ajuntar aqueles que na minha ira , cólera e furor eu espalhei. Eu os trarei de volta a este lugar e os deixarei viver aqui em segurança.

[[v24-32-38]]

^<<v24-32-38,38>>^ Eles serão o meu povo, e eu serei o seu Deus.

[[v24-32-39]]

^<<v24-32-39,39>>^ Eu lhes darei este único propósito na vida: temer  sempre a mim, para o próprio bem deles e dos seus descendentes.

[[v24-32-40]]

^<<v24-32-40,40>>^ Vou fazer com eles esta aliança  eterna: nunca deixarei de lhes fazer o bem; farei com que me respeitem com sinceridade para que nunca se afastem de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ Terei prazer em lhes fazer o bem e com todo o meu coração e com toda a minha alma deixarei que fiquem morando nesta terra.

[[v24-32-42]]

^<<v24-32-42,42>>^ — Assim como eu trouxe esta desgraça a este povo, também lhe darei todas as boas coisas que prometi.

[[v24-32-43]]

^<<v24-32-43,43>>^ Jeremias, o povo anda dizendo que esta terra vai ficar como um deserto, sem gente e sem animais, e que será entregue aos babilônios. Mas eu digo que neste país ainda se comprarão terras.

[[v24-32-44]]

^<<v24-32-44,44>>^ As pessoas vão comprar, assinar escrituras, fechá-las com selos  e chamar testemunhas. Isso acontecerá nas terras da tribo  de Benjamim, nos povoados em volta de Jerusalém, nas cidades de Judá e nas cidades das montanhas, das planícies e da região sul. Eu trarei o povo de volta ao seu país. Eu, o Senhor , falei.

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]