include::./index.adoc[]

[[v24-52-0]]
=== Jeremias, 52
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-52-1]]

^<<v24-52-1,1>>^ Zedequias tinha vinte e um anos de idade quando se tornou rei de Judá; e reinou onze anos em Jerusalém. A sua mãe se chamava Hamutal, filha de outro Jeremias, que vivia na cidade de Libna.

[[v24-52-2]]

^<<v24-52-2,2>>^ O rei Zedequias pecou contra Deus, o Senhor , fazendo o que era errado, como o rei Jeoaquim também havia feito.

[[v24-52-3]]

^<<v24-52-3,3>>^ O Senhor  ficou muito irado  com o povo de Judá e de Jerusalém e por isso fez com que fossem levados como prisioneiros. Zedequias se revoltou contra o rei da Babilônia.

[[v24-52-4]]

^<<v24-52-4,4>>^ No ano nono do reinado de Zedequias em Judá, no dia dez do décimo mês, o rei Nabucodonosor, da Babilônia, veio com todo o seu exército e atacou Jerusalém. Eles acamparam fora da cidade e construíram torres em volta para cercá-la.

[[v24-52-5]]

^<<v24-52-5,5>>^ A cidade ficou cercada até o ano onze do reinado de Zedequias.

[[v24-52-6]]

^<<v24-52-6,6>>^ No dia nove do quarto mês daquele mesmo ano, a fome apertou na cidade; o povo não tinha nada para comer.

[[v24-52-7]]

^<<v24-52-7,7>>^ Quando os babilônios abriram brechas nas muralhas, todos os soldados judeus tentaram fugir durante a noite, embora a cidade estivesse cercada. Foram pelo caminho do jardim real, atravessaram o portão que liga as duas muralhas e fugiram na direção do vale do Jordão.

[[v24-52-8]]

^<<v24-52-8,8>>^ Mas o exército dos babilônios perseguiu o rei Zedequias e o prendeu na planície de Jericó. E todos os seus soldados o abandonaram.

[[v24-52-9]]

^<<v24-52-9,9>>^ Zedequias foi levado como prisioneiro ao rei Nabucodonosor, que estava na cidade de Ribla, na região de Hamate. Ali Nabucodonosor o condenou.

[[v24-52-10]]

^<<v24-52-10,10>>^ Em Ribla, o rei da Babilônia mandou matar os filhos de Zedequias na presença do pai. Também mandou matar as autoridades de Judá.

[[v24-52-11]]

^<<v24-52-11,11>>^ Depois, mandou furar os olhos de Zedequias e o prendeu com correntes de bronze a fim de levá-lo para a Babilônia. E Zedequias ficou na prisão em Babilônia até o dia da sua morte.

[[v24-52-12]]

^<<v24-52-12,12>>^ No ano décimo nono do reinado de Nabucodonosor, da Babilônia, no dia dez do quinto mês, Nebuzaradã, conselheiro do rei e comandante-geral do seu exército, entrou em Jerusalém.

[[v24-52-13]]

^<<v24-52-13,13>>^ Ele incendiou o Templo, o palácio do rei e as casas de todas as pessoas importantes de Jerusalém.

[[v24-52-14]]

^<<v24-52-14,14>>^ Os seus soldados derrubaram as muralhas da cidade.

[[v24-52-15]]

^<<v24-52-15,15>>^ E Nebuzaradã levou como prisioneiros para a Babilônia os que haviam sido deixados na cidade, os que haviam fugido para o lado dele e o resto dos operários especializados.

[[v24-52-16]]

^<<v24-52-16,16>>^ Mas deixou em Judá algumas das pessoas mais pobres e as pôs para trabalhar nas plantações de uvas e nos campos.

[[v24-52-17]]

^<<v24-52-17,17>>^ Os babilônios quebraram as colunas de bronze e as carretas que estavam ao lado do Templo e também o grande tanque de bronze. Então levaram todo o bronze para a Babilônia.

[[v24-52-18]]

^<<v24-52-18,18>>^ Levaram as pás e as vasilhas usadas para carregar as cinzas do altar e as tesouras de cortar pavios de lamparinas. Levaram as tigelas onde era recolhido o sangue dos sacrifícios , as vasilhas de queimar incenso e todos os objetos de bronze usados no culto.

[[v24-52-19]]

^<<v24-52-19,19>>^ Levaram todas as peças feitas de ouro ou de prata: as vasilhas pequenas, os pratos de carregar brasas, as tigelas em que era recolhido o sangue dos sacrifícios, as vasilhas para cinza, os candeeiros, as vasilhas de incenso e os vasos usados nas ofertas de bebidas.

[[v24-52-20]]

^<<v24-52-20,20>>^ Não foi possível calcular o peso dos objetos de bronze que o rei Salomão havia feito para o Templo, isto é, as duas colunas, as carretas, o grande tanque e os doze bois que o sustentavam.

[[v24-52-21]]

^<<v24-52-21,21>>^ As duas colunas eram iguais: cada uma tinha oito metros de altura por cinco metros e trinta e cinco centímetros de circunferência. Eram ocas, e a grossura do metal era de dez centímetros. No alto de cada coluna havia um remate de bronze, que media dois metros e vinte de altura. Em toda a volta do remate havia um enfeite rendilhado e com romãs. Tudo isso também era de bronze.

[[v24-52-22]]

^<<v24-52-22,22>>^ As duas colunas eram iguais: cada uma tinha oito metros de altura por cinco metros e trinta e cinco centímetros de circunferência. Eram ocas, e a grossura do metal era de dez centímetros. No alto de cada coluna havia um remate de bronze, que media dois metros e vinte de altura. Em toda a volta do remate havia um enfeite rendilhado e com romãs. Tudo isso também era de bronze.

[[v24-52-23]]

^<<v24-52-23,23>>^ No enfeite rendilhado de cada coluna havia cem romãs, sendo que noventa e seis delas podiam ser vistas do chão.

[[v24-52-24]]

^<<v24-52-24,24>>^ Nebuzaradã, o comandante-geral, também levou como prisioneiros Seraías, o Grande Sacerdote , e Sofonias, o segundo sacerdote, e os três outros oficiais de importância no Templo.

[[v24-52-25]]

^<<v24-52-25,25>>^ Da cidade, ele levou o oficial que tinha sido o comandante das tropas, sete conselheiros do rei que ainda estavam lá, o oficial encarregado de alistar homens para o exército e mais sessenta homens importantes.

[[v24-52-26]]

^<<v24-52-26,26>>^ Nebuzaradã os levou ao rei da Babilônia, que estava na cidade de Ribla,

[[v24-52-27]]

^<<v24-52-27,27>>^ na terra de Hamate. Ali o rei mandou surrá-los e depois matá-los. Assim o povo de Judá foi levado como prisioneiro para fora da sua terra.

[[v24-52-28]]

^<<v24-52-28,28>>^ Este é o número de prisioneiros que Nabucodonosor levou: no sétimo ano do seu reinado, levou três mil e vinte e três;

[[v24-52-29]]

^<<v24-52-29,29>>^ no décimo oitavo ano, oitocentos e trinta e dois, de Jerusalém.

[[v24-52-30]]

^<<v24-52-30,30>>^ No vigésimo terceiro ano, Nebuzaradã levou setecentos e quarenta e cinco. Ao todo, foram levadas quatro mil e seiscentas pessoas.

[[v24-52-31]]

^<<v24-52-31,31>>^ No ano em que se tornou rei da Babilônia, Evil-Merodaque foi bondoso com o rei Joaquim, de Judá, e o libertou da prisão. Isto aconteceu trinta e sete anos, onze meses e vinte e cinco dias depois que Joaquim havia sido levado como prisioneiro.

[[v24-52-32]]

^<<v24-52-32,32>>^ Evil-Merodaque tratou Joaquim com bondade e lhe deu uma posição mais alta do que a dos outros reis que eram prisioneiros com ele em Babilônia.

[[v24-52-33]]

^<<v24-52-33,33>>^ Assim deixaram que Joaquim tirasse as suas roupas de prisioneiro, e vestisse as suas próprias roupas, e comesse junto com o rei pelo resto da sua vida.

'''

xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[Próximo Capítulo &#62;]