include::./index.adoc[]

[[v24-51-0]]
=== Jeremias, 51
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-51-1]]

^<<v24-51-1,1>>^ O Senhor  Deus diz: — Eu farei com que venha um vento destruidor contra a Babilônia e o seu povo.

[[v24-51-2]]

^<<v24-51-2,2>>^ Mandarei estrangeiros para destruírem o país como o vento que joga longe a palha. Quando chegar esse dia de destruição, eles atacarão de todos os lados e deixarão a terra deserta.

[[v24-51-3]]

^<<v24-51-3,3>>^ Não permitam que os soldados da Babilônia atirem as suas flechas ou vistam as suas couraças . Não deixem de matar os jovens! Destruam todo o exército!

[[v24-51-4]]

^<<v24-51-4,4>>^ Eles serão feridos e morrerão nas ruas das suas cidades.

[[v24-51-5]]

^<<v24-51-5,5>>^ Eu, o Senhor  Todo-Poderoso, não abandonei Israel e Judá. Mas o povo da Babilônia tem pecado contra mim, o Santo Deus de Israel.

[[v24-51-6]]

^<<v24-51-6,6>>^ Fujam da Babilônia! Salve-se quem puder! Não sejam mortos por causa do pecado da Babilônia. Agora, eu me vingarei dela e lhe darei o castigo que merece.

[[v24-51-7]]

^<<v24-51-7,7>>^ A Babilônia era na minha mão como um copo de ouro que fazia o mundo inteiro ficar bêbado. As nações beberam o vinho que havia nela e ficaram loucas.

[[v24-51-8]]

^<<v24-51-8,8>>^ De repente, a Babilônia caiu e ficou arrasada. Chorem por ela! Arranjem remédio para as suas feridas, e assim talvez ela seja curada.

[[v24-51-9]]

^<<v24-51-9,9>>^ Os estrangeiros que moravam lá disseram: "Quisemos ajudar a Babilônia, mas já era tarde demais. Vamos sair e voltar cada um para a sua pátria. Deus castigou com toda a sua força a Babilônia e a destruiu completamente."

[[v24-51-10]]

^<<v24-51-10,10>>^ O Senhor  Deus diz: — O meu povo grita assim: "O Senhor  mostrou que estamos certos. Vamos a Jerusalém contar ao povo o que o Senhor , nosso Deus, tem feito."

[[v24-51-11]]

^<<v24-51-11,11>>^ O Senhor  despertou o ânimo dos reis da Média porque ele quer destruir a Babilônia. É assim que ele vingará a destruição do seu Templo. Os oficiais ordenam: — Afiem as suas flechas! Aprontem os seus escudos !

[[v24-51-12]]

^<<v24-51-12,12>>^ Deem o sinal para atacar as muralhas de Babilônia! Reforcem a guarda! Coloquem sentinelas! Ponham homens de tocaia! O Senhor  Deus fez o que havia planejado; ele cumpriu a ameaça que tinha feito a respeito do povo da Babilônia.

[[v24-51-13]]

^<<v24-51-13,13>>^ A Babilônia tem muitos rios e muitos tesouros, mas chegou a hora, e o fio da sua vida está cortado.

[[v24-51-14]]

^<<v24-51-14,14>>^ O Senhor  Todo-Poderoso jurou pela sua própria vida que ia trazer muitos homens para atacarem a Babilônia. Eles chegarão como uma nuvem de gafanhotos e darão o grito de vitória.

[[v24-51-15]]

^<<v24-51-15,15>>^ Pelo seu poder, o Senhor  Deus fez a terra; com a sua sabedoria, ele criou o mundo e, com a sua inteligência, estendeu o céu como uma barraca.

[[v24-51-16]]

^<<v24-51-16,16>>^ Quando o Senhor  dá ordem, as águas rugem no céu. Ele manda as nuvens subirem dos fins da terra. Ele faz o raio para a chuva e manda o vento sair dos seus depósitos.

[[v24-51-17]]

^<<v24-51-17,17>>^ Diante disso, todos os seres humanos são tolos e ignorantes; todos os que fabricam ídolos ficam desapontados porque fazem deuses falsos, que não têm vida.

[[v24-51-18]]

^<<v24-51-18,18>>^ Esses ídolos não valem nada; são uma tapeação. Serão destruídos quando o Senhor  vier castigá-los.

[[v24-51-19]]

^<<v24-51-19,19>>^ O Deus de Jacó não é assim; foi ele quem fez todas as coisas e escolheu Israel para ser o seu povo. O seu nome é Senhor , o Todo-Poderoso.

[[v24-51-20]]

^<<v24-51-20,20>>^ O Senhor  Deus diz: "Babilônia, você foi o meu porrete de guerra, você foi as minhas armas de combate. Por meio de você, eu despedacei nações e acabei com reinos.

[[v24-51-21]]

^<<v24-51-21,21>>^ Por meio de você, esmaguei cavalos e cavaleiros e destruí carros de guerra e aqueles que os dirigiam.

[[v24-51-22]]

^<<v24-51-22,22>>^ Por meio de você, matei homens e mulheres, despedacei velhos e moços e esmaguei homens e moças.

[[v24-51-23]]

^<<v24-51-23,23>>^ Por meio de você, esmigalhei pastores e os seus rebanhos, despedacei lavradores e os seus bois de arado e esmaguei governadores e altas autoridades."

[[v24-51-24]]

^<<v24-51-24,24>>^ O Senhor  Deus diz: — Vocês verão como vou fazer com que a Babilônia e o seu povo paguem por todo o mal que fizeram a Jerusalém.

[[v24-51-25]]

^<<v24-51-25,25>>^ Babilônia, você é como uma montanha que destrói o mundo inteiro; mas eu, o Senhor , sou seu inimigo. Eu a pegarei e arrasarei; eu farei você virar cinza.

[[v24-51-26]]

^<<v24-51-26,26>>^ Nenhuma das suas pedras será usada para uma nova construção. Você vai virar para sempre um deserto. Sou eu, o Senhor , quem está falando.

[[v24-51-27]]

^<<v24-51-27,27>>^ — Deem o sinal de ataque! Toquem as cornetas para que os povos escutem! Preparem as nações para lutarem contra Babilônia! Digam aos reinos de Ararate, Mini e Asquenaz que ataquem. Indiquem um oficial para comandar o ataque. Tragam um grande número de cavalos, como se fossem uma nuvem de gafanhotos.

[[v24-51-28]]

^<<v24-51-28,28>>^ Preparem os reis da Média, as suas autoridades, os seus oficiais e todos os países que eles controlam, para que eles guerreiem contra Babilônia.

[[v24-51-29]]

^<<v24-51-29,29>>^ A terra treme e se abala porque o Senhor  está fazendo o que planejou. Ele fará Babilônia virar um deserto onde não mora ninguém.

[[v24-51-30]]

^<<v24-51-30,30>>^ Os soldados babilônios pararam de lutar e ficam nas suas fortalezas. Perderam toda a coragem; parecem mulheres. Os portões da cidade estão quebrados, e as casas pegaram fogo.

[[v24-51-31]]

^<<v24-51-31,31>>^ Saem correndo mensageiros, um depois do outro, para contar ao rei da Babilônia que a cidade foi invadida de todos os lados.

[[v24-51-32]]

^<<v24-51-32,32>>^ O inimigo tomou as passagens do rio e pôs fogo nas fortalezas. Os soldados babilônios ficaram apavorados.

[[v24-51-33]]

^<<v24-51-33,33>>^ Dentro de pouco tempo, o inimigo os cortará e pisará como trigo no terreiro. O Senhor  Todo-Poderoso, o Deus de Israel, está falando.

[[v24-51-34]]

^<<v24-51-34,34>>^ O rei da Babilônia cortou Jerusalém em pedaços e a devorou. Ele esvaziou a cidade como um jarro; como um monstro, ele a engoliu. Ele tirou o que queria e jogou o resto fora.

[[v24-51-35]]

^<<v24-51-35,35>>^ Diga o povo de Sião : "Que a Babilônia receba de volta a violência que nos fez!" E diga ainda o povo de Jerusalém: "Que a Babilônia seja castigada pelo que sofremos!"

[[v24-51-36]]

^<<v24-51-36,36>>^ Assim diz o Senhor  Deus ao povo de Jerusalém: — Defenderei a causa de vocês e os vingarei. Secarei a fonte de água da Babilônia e farei com que os seus rios sequem.

[[v24-51-37]]

^<<v24-51-37,37>>^ Então Babilônia se tornará um montão de pedras, onde vivem animais ferozes. Será um espetáculo horrível. Ninguém vai morar lá, e todos os que olharem para Babilônia ficarão horrorizados por causa do que aconteceu com ela.

[[v24-51-38]]

^<<v24-51-38,38>>^ Todos os babilônios rugem como leões e rosnam como leõezinhos.

[[v24-51-39]]

^<<v24-51-39,39>>^ Será que eles são esganados? Farei uma festa para eles. Eu os embriagarei e alegrarei. Aí eles dormirão e nunca mais acordarão.

[[v24-51-40]]

^<<v24-51-40,40>>^ Eu os levarei para serem mortos, como se fossem cordeiros, bodes e carneiros. Eu, o Senhor , estou falando.

[[v24-51-41]]

^<<v24-51-41,41>>^ O Senhor  Deus diz: — Babilônia, a cidade que era admirada em todo o mundo, foi tomada! Que espetáculo horrível ela se tornou para as outras nações!

[[v24-51-42]]

^<<v24-51-42,42>>^ O mar rolou sobre Babilônia e a cobriu com ondas violentas.

[[v24-51-43]]

^<<v24-51-43,43>>^ As cidades estão arrasadas; são como um deserto sem água, onde ninguém mora e por onde ninguém passa.

[[v24-51-44]]

^<<v24-51-44,44>>^ Eu castigarei Bel, o deus da Babilônia, e farei com que ele devolva as coisas que roubou. As nações não o adorarão mais. — As muralhas de Babilônia caíram.

[[v24-51-45]]

^<<v24-51-45,45>>^ Povo de Israel, fuja de lá. Que cada um salve a sua vida do fogo da minha ira !

[[v24-51-46]]

^<<v24-51-46,46>>^ Não percam a coragem, nem fiquem com medo das notícias que ouvirem. Cada ano, se espalha uma notícia diferente; são notícias de violência na terra e de um rei lutando contra outro.

[[v24-51-47]]

^<<v24-51-47,47>>^ E assim está chegando a hora em que vou castigar os ídolos da Babilônia. Os moradores da sua terra ficarão com vergonha por causa da derrota, e todos serão mortos.

[[v24-51-48]]

^<<v24-51-48,48>>^ Quando Babilônia cair e for destruída pelo povo que vem do Norte, então tudo o que existe no céu e na terra cantará de alegria.

[[v24-51-49]]

^<<v24-51-49,49>>^ Babilônia matou gente em todo o mundo e agora ela cairá porque matou tantos israelitas. Eu, o Senhor , estou falando.

[[v24-51-50]]

^<<v24-51-50,50>>^ O Senhor  diz: — Meu povo que está na Babilônia, vocês escaparam da morte! Agora andem! Não fiquem esperando! Embora estejam longe de casa, pensem em mim, o Deus de vocês, e lembrem de Jerusalém.

[[v24-51-51]]

^<<v24-51-51,51>>^ Vocês dizem: "Estamos envergonhados porque fomos insultados. Estamos humilhados porque os estrangeiros invadiram os lugares santos do Templo."

[[v24-51-52]]

^<<v24-51-52,52>>^ Por isso, digo que está chegando a hora em que vou castigar os ídolos da Babilônia; e os feridos vão gemer, espalhados pelo país inteiro.

[[v24-51-53]]

^<<v24-51-53,53>>^ Mesmo que a Babilônia pudesse subir até o céu e construir ali uma fortaleza, ainda assim eu mandaria gente para destruí-la. Eu, o Senhor , estou falando.

[[v24-51-54]]

^<<v24-51-54,54>>^ O Senhor  Deus diz: "Escutem os gritos em Babilônia, gente chorando por causa da destruição que há no país.

[[v24-51-55]]

^<<v24-51-55,55>>^ Estou destruindo Babilônia e fazendo com que ela fique quieta. Como ondas violentas, os exércitos invadem e atacam com gritos barulhentos.

[[v24-51-56]]

^<<v24-51-56,56>>^ Vieram para destruir Babilônia; os seus soldados são presos, e os seus arcos e as suas flechas são quebrados. Eu, o Senhor , sou Deus que castiga o mal; eu vou tratar Babilônia do jeito que ela merece.

[[v24-51-57]]

^<<v24-51-57,57>>^ Farei com que os seus governantes fiquem bêbados e também os seus sábios, as suas autoridades e os seus soldados. Eles vão dormir e nunca mais vão acordar. Sou eu, o Rei, quem está falando. O meu nome é Senhor , o Todo-Poderoso.

[[v24-51-58]]

^<<v24-51-58,58>>^ As grossas muralhas de Babilônia serão completamente arrasadas, e os seus altos portões serão destruídos pelo fogo. Todo o trabalho dos povos não vale nada; os esforços das nações se acabam nas chamas." O Senhor  Todo-Poderoso falou.

[[v24-51-59]]

^<<v24-51-59,59>>^ Seraías, filho de Nerias e neto de Maaseias, era o oficial ajudante do rei Zedequias, de Judá. No quarto ano do reinado de Zedequias em Judá, Seraías estava de saída para a Babilônia, e então eu lhe dei algumas ordens.

[[v24-51-60]]

^<<v24-51-60,60>>^ Escrevi num livro como a Babilônia ia ser destruída e todas as outras coisas que iam acontecer com ela.

[[v24-51-61]]

^<<v24-51-61,61>>^ E disse a Seraías: — Quando você chegar à cidade de Babilônia, faça questão de ler em voz alta tudo o que está escrito aqui.

[[v24-51-62]]

^<<v24-51-62,62>>^ Depois, ore assim: "Ó Senhor  Deus, tu disseste que vais destruir este lugar, de tal modo que aqui não ficará nenhum ser vivo, nem pessoas nem animais. A cidade será como um deserto para sempre."

[[v24-51-63]]

^<<v24-51-63,63>>^ Quando você acabar de ler para o povo este livro, amarre uma pedra nele e jogue-o no rio Eufrates.

[[v24-51-64]]

^<<v24-51-64,64>>^ Então diga: "Isto é o que acontecerá com a Babilônia — ela vai afundar e nunca mais se levantará, por causa da destruição que Deus vai trazer sobre ela." As palavras de Jeremias terminam aqui.

'''

xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[&#60; Capítulo Anterior] | <<v24-51-0,Topo>> | xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[Próximo Capítulo &#62;]