include::./index.adoc[]

[[v24-17-0]]
=== Jeremias, 17
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-17-1]]

^<<v24-17-1,1>>^ O Senhor  Deus disse: — Povo de Judá, o seu pecado está escrito com ferro pontudo; está gravado com uma ponta de diamante no seu coração e nos cantos dos seus altares.

[[v24-17-2]]

^<<v24-17-2,2>>^ Os seus filhos lembram dos altares e dos postes que foram levantados para a deusa Aserá , perto das árvores verdes, no alto dos morros

[[v24-17-3]]

^<<v24-17-3,3>>^ e nas montanhas que estão no interior do país. Farei com que os inimigos de vocês levem embora todas as suas riquezas e tesouros por causa dos pecados que vocês cometeram em toda esta terra.

[[v24-17-4]]

^<<v24-17-4,4>>^ Vocês terão de abandonar a terra que lhes dei. E farei com que vocês sejam escravos dos seus inimigos numa terra que não conhecem, pois a minha ira  é como um fogo e queimará para sempre.

[[v24-17-5]]

^<<v24-17-5,5>>^ O Senhor  Deus diz: "Eu amaldiçoarei aquele que se afasta de mim, que confia nos outros, que confia na força de fracos seres humanos.

[[v24-17-6]]

^<<v24-17-6,6>>^ Ele é como uma planta do deserto que cresce na terra seca, no chão salgado, onde não cresce mais nada. Nada de bom acontece com ele.

[[v24-17-7]]

^<<v24-17-7,7>>^ "Mas eu abençoarei aquele que confia em mim, aquele que tem fé em mim, o Senhor .

[[v24-17-8]]

^<<v24-17-8,8>>^ Ele é como a árvore plantada perto da água, que espalha as suas raízes até o ribeirão. Quando vem o calor, ela não tem medo, pois as suas folhas ficam sempre verdes. Quando não chove, ela não se preocupa; continua dando frutas.

[[v24-17-9]]

^<<v24-17-9,9>>^ "Quem pode entender o coração humano? Não há nada que engane tanto como ele; está doente demais para ser curado.

[[v24-17-10]]

^<<v24-17-10,10>>^ Eu, o Senhor , examino os pensamentos e ponho à prova os corações. Eu trato cada pessoa conforme a sua maneira de viver, de acordo com o que ela faz."

[[v24-17-11]]

^<<v24-17-11,11>>^ O homem que ganha dinheiro desonestamente é como a ave que choca ovos que não botou; durante a sua vida, ele perde as suas riquezas e no fim não passa de um tolo.

[[v24-17-12]]

^<<v24-17-12,12>>^ O nosso Templo é como um trono glorioso ; desde o princípio, ele está num alto monte.

[[v24-17-13]]

^<<v24-17-13,13>>^ Ó Senhor  Deus, tu és a esperança do povo de Israel; todos os que te abandonam serão humilhados. Desaparecerão como nomes escritos na areia porque abandonaram a ti, o Senhor , a fonte de água fresca.

[[v24-17-14]]

^<<v24-17-14,14>>^ Ó Senhor , cura-me, e ficarei curado; salva-me, e serei salvo, pois eu canto louvores a ti.

[[v24-17-15]]

^<<v24-17-15,15>>^ Os outros me dizem: "Onde estão as ameaças que o Senhor  nos fez? Que elas se cumpram agora!"

[[v24-17-16]]

^<<v24-17-16,16>>^ Mas, Senhor, eu nunca pedi que fizesses a desgraça cair sobre eles, nem pedi que passassem por tempos difíceis. Ó Deus, tu sabes disso; tu sabes o que eu disse.

[[v24-17-17]]

^<<v24-17-17,17>>^ Não sejas para mim um motivo de terror; tu és para mim um lugar seguro no dia da desgraça.

[[v24-17-18]]

^<<v24-17-18,18>>^ Que sejam humilhados os que me perseguem, mas eu não! Que eles fiquem cheios de terror, mas eu não! Manda que a desgraça caia sobre eles; acaba com eles completamente.

[[v24-17-19]]

^<<v24-17-19,19>>^ O Senhor  Deus me disse: — Jeremias, vá e fique no Portão do Povo, por onde os reis de Judá entram e saem da cidade; depois, vá a todos os outros portões de Jerusalém.

[[v24-17-20]]

^<<v24-17-20,20>>^ Diga a todos que escutem as minhas palavras; diga isso aos reis, a todo o povo de Judá e a todos os moradores de Jerusalém que entram por esses portões.

[[v24-17-21]]

^<<v24-17-21,21>>^ Diga que, se eles querem continuar a viver, não carreguem nenhuma carga no sábado. Que nesse dia não tragam nada para dentro dos portões de Jerusalém,

[[v24-17-22]]

^<<v24-17-22,22>>^ nem carreguem nada para fora das suas casas. Diga que não trabalhem no sábado. O sábado deve ser guardado como dia sagrado, conforme mandei aos seus antepassados.

[[v24-17-23]]

^<<v24-17-23,23>>^ Eles não me ouviram, nem me deram atenção. Pelo contrário, foram teimosos; não quiseram me obedecer, nem aprender.

[[v24-17-24]]

^<<v24-17-24,24>>^ — Diga a esse povo que me obedeça de todo o coração. Que no sábado não carreguem nenhuma carga para dentro dos portões desta cidade! Diga que guardem o sábado como dia sagrado e não façam nenhum trabalho nesse dia.

[[v24-17-25]]

^<<v24-17-25,25>>^ Então, sim, os seus reis e príncipes entrarão pelos portões de Jerusalém e terão o mesmo poder real que Davi teve. Eles andarão em carros e montarão cavalos, junto com o povo de Judá e de Jerusalém; e na cidade de Jerusalém sempre morará gente.

[[v24-17-26]]

^<<v24-17-26,26>>^ Eles virão das cidades de Judá e dos povoados em volta de Jerusalém, e também do território de Benjamim, das planícies, das montanhas e da região sul. Eles trarão ao meu Templo ofertas a serem queimadas e sacrifícios , ofertas de cereais e incenso e ofertas de gratidão.

[[v24-17-27]]

^<<v24-17-27,27>>^ Mas, se não me obedecerem, e não guardarem o sábado como dia sagrado, e se nesse dia carregarem cargas para dentro dos portões da cidade, então eu porei fogo nesses portões. O fogo destruirá os palácios de Jerusalém, e ninguém poderá apagá-lo.

'''

xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[&#60; Capítulo Anterior] | <<v24-17-0,Topo>> | xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[Próximo Capítulo &#62;]