include::./index.adoc[]

[[v24-4-0]]
=== Jeremias, 4
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-4-1]]

^<<v24-4-1,1>>^ O Senhor  Deus diz: — Povo de Israel, se você vai voltar, volte para mim. Eu odeio os ídolos; acabe com eles e seja fiel a mim.

[[v24-4-2]]

^<<v24-4-2,2>>^ Então, sim, você estará sendo verdadeiro, correto e honesto quando jurar pelo meu nome. Todas as nações pedirão que eu as abençoe e elas me louvarão.

[[v24-4-3]]

^<<v24-4-3,3>>^ Deus diz aos homens da tribo  de Judá e da cidade de Jerusalém: — Passem o arado na terra que não foi preparada para plantar e não semeiem as sementes no meio de espinhos.

[[v24-4-4]]

^<<v24-4-4,4>>^ Povo de Judá e moradores de Jerusalém, sejam fiéis à aliança  que fizeram comigo, o Senhor , e se dediquem a mim de todo o coração; se não, a minha ira  queimará como fogo. E, por causa das maldades que vocês têm feito, o meu furor será como fogo, e ninguém poderá apagá-lo.

[[v24-4-5]]

^<<v24-4-5,5>>^ Toquem a corneta em toda a terra! Gritem bem alto e bem claro! Digam ao povo de Judá e de Jerusalém que corra para as cidades protegidas por muralhas.

[[v24-4-6]]

^<<v24-4-6,6>>^ Mostrem o caminho que vai a Sião ! Corram para os abrigos! Não demorem! Do Norte, Deus vai trazer desgraça e grande destruição.

[[v24-4-7]]

^<<v24-4-7,7>>^ Como um leão que sai do seu esconderijo, um destruidor de nações vem vindo para acabar com o povo de Judá. As cidades de Judá serão destruídas, e ninguém morará nelas.

[[v24-4-8]]

^<<v24-4-8,8>>^ Portanto, vistam roupa feita de pano grosseiro como sinal de tristeza. Lamentem e chorem, pois o fogo da ira de Deus não se desviou de Judá.

[[v24-4-9]]

^<<v24-4-9,9>>^ O Senhor  Deus disse: — Naquele dia, os reis e as autoridades perderão a coragem, os sacerdotes ficarão abalados e os profetas  ficarão admirados.

[[v24-4-10]]

^<<v24-4-10,10>>^ Então eu disse: — Ó Senhor , meu Deus, tu enganaste completamente o povo de Jerusalém! Disseste que ia haver paz, mas o que há é uma espada encostada na garganta deles.

[[v24-4-11]]

^<<v24-4-11,11>>^ Está chegando o tempo de dizer ao povo de Jerusalém que do deserto um vento muito quente vai soprar sobre o povo de Deus. Não será o vento fraco que separa a palha do trigo.

[[v24-4-12]]

^<<v24-4-12,12>>^ O vento que vem mandado por Deus será muito forte. Agora, é Deus mesmo que está dando a sentença contra o seu povo.

[[v24-4-13]]

^<<v24-4-13,13>>^ Olhem! Os inimigos vêm vindo como nuvens. Os seus carros de guerra são como uma forte ventania, e os seus cavalos são mais rápidos do que as águias. Estamos perdidos! Estamos acabados!

[[v24-4-14]]

^<<v24-4-14,14>>^ Jerusalém, limpe a maldade do seu coração para que você seja salva. Até quando você vai continuar com os seus maus pensamentos?

[[v24-4-15]]

^<<v24-4-15,15>>^ Mensageiros da cidade de Dã e das montanhas de Efraim anunciam as más notícias da invasão.

[[v24-4-16]]

^<<v24-4-16,16>>^ Eles mandam avisar as nações e dizer a Jerusalém que os inimigos vêm vindo de um país distante e que eles vão dar o seu grito de guerra contra as cidades de Judá.

[[v24-4-17]]

^<<v24-4-17,17>>^ Eles vão cercar Jerusalém como homens que guardam uma plantação, pois a nossa nação se revoltou contra Deus, o Senhor .

[[v24-4-18]]

^<<v24-4-18,18>>^ Judá, você trouxe esse mal para você mesmo por causa do seu modo de viver, por causa das coisas que tem feito. O seu pecado trouxe esse sofrimento e feriu o seu próprio coração. Eu, o Senhor , estou falando.

[[v24-4-19]]

^<<v24-4-19,19>>^ Que dor! Não posso suportar tanta dor! Ah! meu coração! O meu coração está batendo forte! Não posso ficar calado, pois ouvi a corneta e os gritos de guerra.

[[v24-4-20]]

^<<v24-4-20,20>>^ Uma desgraça vem atrás da outra; o país inteiro está arrasado. De repente, as nossas barracas são destruídas, e as suas cortinas são rasgadas em pedaços.

[[v24-4-21]]

^<<v24-4-21,21>>^ Até quando terei de ver as bandeiras inimigas e ouvir o som da corneta na batalha?

[[v24-4-22]]

^<<v24-4-22,22>>^ Deus diz: "O meu povo não tem juízo e não me conhece. Eles são como crianças tolas que não compreendem as coisas. Para fazer o mal, são espertos, mas não sabem fazer o bem."

[[v24-4-23]]

^<<v24-4-23,23>>^ Então olhei. A terra era um vazio, sem nenhum ser vivente, e no céu não havia luz.

[[v24-4-24]]

^<<v24-4-24,24>>^ Olhei para as montanhas, e elas estavam tremendo; e os montes balançavam para lá e para cá.

[[v24-4-25]]

^<<v24-4-25,25>>^ Vi que não havia ninguém e que até os passarinhos tinham fugido.

[[v24-4-26]]

^<<v24-4-26,26>>^ Vi ainda que a terra boa tinha virado um deserto e que as cidades tinham sido arrasadas por Deus, por causa do seu grande furor.

[[v24-4-27]]

^<<v24-4-27,27>>^ Deus disse que a terra toda vai virar um deserto, mas ele não a destruirá completamente.

[[v24-4-28]]

^<<v24-4-28,28>>^ A terra chorará, e o céu ficará escuro, pois Deus falou e não mudará de ideia. Ele já decidiu e não voltará atrás.

[[v24-4-29]]

^<<v24-4-29,29>>^ Quando ouvirem o barulho dos cavaleiros e dos atiradores de flechas, todos sairão correndo. Alguns fugirão para a floresta, e outros subirão pelas rochas. Todas as cidades ficarão vazias, e ninguém morará nelas.

[[v24-4-30]]

^<<v24-4-30,30>>^ Jerusalém, você está condenada! Por que se veste de vermelho? Por que usa joias e pinta os olhos? Não adianta nada você querer ficar bonita! Os seus amantes a rejeitaram, e o que eles querem é matá-la.

[[v24-4-31]]

^<<v24-4-31,31>>^ Ouvi um grito igual ao de uma mulher com dores de parto, um grito como o de uma mulher dando à luz o seu primeiro filho. Era o grito de Jerusalém respirando com dificuldade, estendendo as mãos em desespero e dizendo: "Estou perdida! Eles vêm vindo para me matar!"

'''

xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[Próximo Capítulo &#62;]