include::./index.adoc[]

[[v24-25-0]]
=== Jeremias, 25
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-25-1]]

^<<v24-25-1,1>>^ No quarto ano do reinado de Jeoaquim, filho de Josias, em Judá, eu recebi do Senhor  uma mensagem a respeito de todo o povo de Judá. Isso aconteceu no primeiro ano do reinado de Nabucodonosor, da Babilônia.

[[v24-25-2]]

^<<v24-25-2,2>>^ Eu disse a todo o povo de Judá e a todos os moradores de Jerusalém:

[[v24-25-3]]

^<<v24-25-3,3>>^ — Durante vinte e três anos, desde o ano décimo terceiro do reinado de Josias, filho de Amom, em Judá, até hoje, o Senhor  Deus tem falado comigo, e eu sempre lhes tenho contado o que ele diz. Mas vocês não têm dado atenção.

[[v24-25-4]]

^<<v24-25-4,4>>^ Vocês não ouviram, nem deram atenção, embora o Senhor  continuasse a enviar os seus servos , os profetas .

[[v24-25-5]]

^<<v24-25-5,5>>^ Eles disseram que vocês deviam abandonar a vida errada que estão levando e as coisas más que estão fazendo. Assim poderiam continuar a viver na terra que Deus deu a vocês e aos seus antepassados para ser sua propriedade para sempre.

[[v24-25-6]]

^<<v24-25-6,6>>^ Os profetas disseram que vocês não deviam andar procurando outros deuses para adorar, que não deviam fazer o Senhor  ficar irado  por causa dos ídolos que vocês fizeram.

[[v24-25-7]]

^<<v24-25-7,7>>^ Mas o Senhor  mesmo diz que vocês não quiseram ouvi-lo. Pelo contrário, fizeram com que o Senhor  ficasse irado por causa dos seus ídolos e por isso vocês foram castigados.

[[v24-25-8]]

^<<v24-25-8,8>>^ — Portanto, porque vocês não quiseram escutar as suas palavras, o Senhor  Todo-Poderoso diz:

[[v24-25-9]]

^<<v24-25-9,9>>^ "Eu mandarei buscar todos os povos do Norte e também meu servo, o rei Nabucodonosor, da Babilônia. Vou trazer esses povos para lutarem contra os moradores desta terra de Judá e contra todas as nações vizinhas. Eu as destruirei completamente; elas ficarão arrasadas para sempre e serão um espetáculo horrível e assustador. Sou eu, o Senhor , quem está falando.

[[v24-25-10]]

^<<v24-25-10,10>>^ Vou acabar com os seus gritos de alegria e de felicidade e com o barulho alegre das festas de casamento. Vocês não terão mantimento para comer nem azeite para as lamparinas.

[[v24-25-11]]

^<<v24-25-11,11>>^ Toda esta terra ficará arrasada e será um espetáculo horrível. Todas estas nações serão dominadas pelo rei da Babilônia durante setenta anos.

[[v24-25-12]]

^<<v24-25-12,12>>^ Depois disso, eu castigarei o rei da Babilônia e a sua nação por causa do pecado deles. Destruirei o seu país e o deixarei arrasado para sempre. Sou eu, o Senhor , quem está falando.

[[v24-25-13]]

^<<v24-25-13,13>>^ Castigarei aquela nação com tudo aquilo que ameacei fazer, com todas as coisas escritas neste livro, as coisas que Jeremias falou contra todas estas nações.

[[v24-25-14]]

^<<v24-25-14,14>>^ Eles se tornarão escravos de muitas nações e de reis poderosos e assim eles me pagarão por tudo aquilo que fizeram."

[[v24-25-15]]

^<<v24-25-15,15>>^ O Senhor , o Deus de Israel, me disse: — Aqui está um copo cheio do vinho da minha ira . Pegue este copo e faça com que bebam dele todos os povos aos quais eu estou enviando você.

[[v24-25-16]]

^<<v24-25-16,16>>^ Quando beberem, tremerão e ficarão loucos por causa da guerra que mandarei contra eles.

[[v24-25-17]]

^<<v24-25-17,17>>^ Então peguei o copo da mão do Senhor , e fiz com que bebessem dele todos os povos aos quais o Senhor  me havia mandado.

[[v24-25-18]]

^<<v24-25-18,18>>^ Tanto Jerusalém como todas as cidades de Judá, junto com os seus reis e as suas autoridades, tiveram de beber. Beberam para se transformar num deserto, num espetáculo horrível e assustador, do qual as pessoas falam para rogar pragas. E isso é o que se vê hoje .

[[v24-25-19]]

^<<v24-25-19,19>>^ Esta é a lista de todos os outros que tiveram de beber do copo da ira de Deus: O rei do Egito, os seus oficiais e as suas autoridades; todos os egípcios e todos os estrangeiros no Egito; todos os reis da terra de Uz; todos os governadores das cidades dos filisteus: Asquelom, Gaza, Ecrom e o que resta de Asdode; todo o povo de Edom, Moabe e Amom; todos os reis de Tiro e de Sidom; todos os reis das terras que ficam no litoral do mar Mediterrâneo; as cidades de Dedã, Temá e Buz; todos os povos que cortam curto o cabelo ; todos os reis da Arábia; todos os reis das tribos do deserto; todos os reis de Zinri, Elão e Média; todos os reis do Norte, de longe e de perto, um depois do outro. Todas as nações do mundo tiveram de beber. E o último que vai beber será o rei da Babilônia.

[[v24-25-20]]

^<<v24-25-20,20>>^ Esta é a lista de todos os outros que tiveram de beber do copo da ira de Deus:

[[v24-25-21]]

^<<v24-25-21,21>>^ Esta é a lista de todos os outros que tiveram de beber do copo da ira de Deus:

[[v24-25-22]]

^<<v24-25-22,22>>^ Esta é a lista de todos os outros que tiveram de beber do copo da ira de Deus:

[[v24-25-23]]

^<<v24-25-23,23>>^ Esta é a lista de todos os outros que tiveram de beber do copo da ira de Deus:

[[v24-25-24]]

^<<v24-25-24,24>>^ Esta é a lista de todos os outros que tiveram de beber do copo da ira de Deus:

[[v24-25-25]]

^<<v24-25-25,25>>^ Esta é a lista de todos os outros que tiveram de beber do copo da ira de Deus:

[[v24-25-26]]

^<<v24-25-26,26>>^ Esta é a lista de todos os outros que tiveram de beber do copo da ira de Deus:

[[v24-25-27]]

^<<v24-25-27,27>>^ Aí Deus me disse: — Diga ao povo que eu, o Senhor  Todo-Poderoso, o Deus de Israel, estou mandando que eles bebam até ficarem bêbados e vomitarem, até caírem e não poderem mais se levantar por causa da guerra que mandarei contra eles.

[[v24-25-28]]

^<<v24-25-28,28>>^ E, se eles não quiserem pegar o copo da sua mão, Jeremias, se recusarem beber, diga que o Senhor  Todo-Poderoso disse que eles serão obrigados a beber.

[[v24-25-29]]

^<<v24-25-29,29>>^ Começarei a destruição pela minha própria cidade. Será que eles estão pensando que vão escapar do castigo? De jeito nenhum! Eles serão castigados, pois eu mandarei guerra a todos os povos do mundo. Eu, o Senhor  Todo-Poderoso, estou falando.

[[v24-25-30]]

^<<v24-25-30,30>>^ — Você, Jeremias, anuncie tudo o que eu disse. Diga a este povo o seguinte: "O Senhor  vai trovejar lá do céu e falar lá do lugar santo onde mora. Ele trovejará contra o seu povo, gritará como aqueles que pisam uvas para fazer vinho. E todos na terra o ouvirão.

'''

xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[&#60; Capítulo Anterior] | <<v24-25-0,Topo>> | xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[Próximo Capítulo &#62;]