include::./index.adoc[]

[[v24-30-0]]
=== Jeremias, 30
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-30-1]]

^<<v24-30-1,1>>^ O Senhor , o Deus de Israel, me disse o seguinte: — Jeremias, escreva num livro tudo o que eu lhe falei, pois está chegando a hora de eu fazer voltar o meu povo, tanto Israel como Judá. Vou trazê-los de volta para a terra que dei aos seus antepassados, e eles serão donos dela novamente. Eu, o Senhor , falei.

[[v24-30-2]]

^<<v24-30-2,2>>^ O Senhor , o Deus de Israel, me disse o seguinte:

[[v24-30-3]]

^<<v24-30-3,3>>^ O Senhor , o Deus de Israel, me disse o seguinte:

[[v24-30-4]]

^<<v24-30-4,4>>^ O Senhor  Deus diz o seguinte a respeito de Israel e de Judá:

[[v24-30-5]]

^<<v24-30-5,5>>^ "Ouvi um grito de terror, grito de medo e não de paz.

[[v24-30-6]]

^<<v24-30-6,6>>^ Parem e pensem! Será que um homem pode dar à luz uma criança? Então por que vejo todos esses homens com as mãos na barriga, como a mulher que está com dores de parto? Por que estão todos tão pálidos?

[[v24-30-7]]

^<<v24-30-7,7>>^ Está chegando um dia horrível! Nenhum outro dia pode ser comparado com ele. Para os descendentes de Jacó, será um tempo de aflição, mas eles serão salvos dela."

[[v24-30-8]]

^<<v24-30-8,8>>^ O Senhor  Todo-Poderoso diz: — Quando esse dia chegar, eu quebrarei a canga que está no pescoço deles e arrancarei as suas correntes. Então eles não serão mais escravos de estrangeiros.

[[v24-30-9]]

^<<v24-30-9,9>>^ Pelo contrário, servirão a mim, o Senhor , seu Deus, e também ao descendente de Davi, que eu lhes darei como rei.

[[v24-30-10]]

^<<v24-30-10,10>>^ "Descendentes do meu servo  Jacó, não tenham medo! Povo de Israel, não fique assustado! Eu os libertarei dessa terra distante, da terra onde vocês são prisioneiros. Os descendentes de Jacó voltarão e viverão em paz; viverão em segurança, e ninguém fará com que fiquem com medo. Sou eu, o Senhor , quem está falando.

[[v24-30-11]]

^<<v24-30-11,11>>^ Estarei com vocês para salvá-los. Acabarei com todas as nações por onde os espalhei, mas vocês não serão destruídos. Vocês não ficarão sem castigo; mas, quando eu os castigar, não serei duro demais. Eu, o Senhor , estou falando."

[[v24-30-12]]

^<<v24-30-12,12>>^ O Senhor  diz à cidade de Jerusalém: "O mal deste povo não tem cura, e as suas feridas não saram.

[[v24-30-13]]

^<<v24-30-13,13>>^ Não existe ninguém para cuidar de você. Não há remédio para as suas feridas, não há esperança de cura.

[[v24-30-14]]

^<<v24-30-14,14>>^ Todos os seus amantes a esqueceram e não lhe dão confiança. Eu a ataquei como se você fosse um inimigo; o seu castigo tem sido duro porque os seus pecados são muitos, e a sua maldade é grande.

[[v24-30-15]]

^<<v24-30-15,15>>^ Não se queixe mais por causa dos seus ferimentos, pois eles não têm cura. Eu a castiguei assim porque os seus pecados são muitos, e a sua maldade é grande.

[[v24-30-16]]

^<<v24-30-16,16>>^ Mas agora todos os que a destruíram serão destruídos, e todos os seus inimigos serão levados como prisioneiros. Todos os que a perseguiram serão perseguidos, e todos os que a assaltaram serão assaltados.

[[v24-30-17]]

^<<v24-30-17,17>>^ Os seus inimigos dizem: ‘ Sião  é desprezada, ninguém se importa com ela!’ Mas eu lhe darei saúde novamente e curarei as suas feridas. Eu, o Senhor , estou falando."

[[v24-30-18]]

^<<v24-30-18,18>>^ O Senhor  diz: "Eu trarei os descendentes de Jacó de volta para a sua terra e terei misericórdia de cada família. Jerusalém será construída de novo, e no palácio morará gente outra vez.

[[v24-30-19]]

^<<v24-30-19,19>>^ As pessoas que vivem ali cantarão louvores e darão gritos de alegria. Farei com que cresçam em número e sejam tratadas com respeito.

[[v24-30-20]]

^<<v24-30-20,20>>^ A nação se firmará como antigamente, e a sua gente será forte de novo. Eu castigarei todos os que a fazem sofrer.

'''

xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[&#60; Capítulo Anterior] | <<v24-30-0,Topo>> | xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[Próximo Capítulo &#62;]