include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-3-1]]

^<<v24-3-1,1>>^ O Senhor  Deus diz: — Se um homem se divorciar da sua mulher, e ela o deixar para casar com outro, o primeiro marido não poderá casar com ela outra vez. Isso mancharia completamente a terra de Israel. Mas você, meu povo, tem tido muitos amantes e agora quer voltar para mim! Sou eu, o Senhor , quem está falando.

[[v24-3-2]]

^<<v24-3-2,2>>^ Olhe para o alto dos montes e veja: será que existe algum lugar onde você não agiu como prostituta? Você ficava na beira da estrada esperando os fregueses, como um árabe que espera no deserto para assaltar alguém. Você manchou a terra de Israel com a sua prostituição e os seus vícios.

[[v24-3-3]]

^<<v24-3-3,3>>^ É por isso que não tem chovido, e as chuvas da primavera deixaram de cair. Mas você tem até jeito de prostituta e mostrou que não tem vergonha.

[[v24-3-4]]

^<<v24-3-4,4>>^ — E agora você me diz: "Tu és o meu pai, tu me tens amado desde que eu era criança.

[[v24-3-5]]

^<<v24-3-5,5>>^ Tu não ficarás com raiva de mim para sempre." Povo de Israel, foi isso o que você disse, mas continuou fazendo todo mal que podia.

[[v24-3-6]]

^<<v24-3-6,6>>^ No tempo do rei Josias, o Senhor  Deus me disse: — Você está vendo o que fez Israel , aquela mulher infiel que virou as costas para mim? Ela subiu em todos os montes altos e ficou debaixo de todas as árvores que dão sombra, agindo como prostituta.

[[v24-3-7]]

^<<v24-3-7,7>>^ Eu, o Senhor , pensei assim: "Depois de fazer tudo isso, com toda a certeza ela voltará para mim." Porém não voltou, e Judá, a sua irmã infiel, viu isso.

[[v24-3-8]]

^<<v24-3-8,8>>^ Judá também sabe que eu me divorciei de Israel e que a mandei embora porque ela me abandonou e virou prostituta. Mas Judá, a sua irmã infiel, não ficou com medo. Ela também virou prostituta

[[v24-3-9]]

^<<v24-3-9,9>>^ e não ficou envergonhada. Ela manchou a sua terra porque cometeu adultério, adorando pedras e árvores.

[[v24-3-10]]

^<<v24-3-10,10>>^ E o pior de tudo é que Judá, a infiel irmã de Israel, só fingiu que voltava para mim: ela não foi sincera. Eu, o Senhor , estou falando.

[[v24-3-11]]

^<<v24-3-11,11>>^ Aí Deus me disse que, embora o povo de Israel o tivesse abandonado, ainda era menos culpado do que a infiel Judá.

[[v24-3-12]]

^<<v24-3-12,12>>^ Ele mandou que eu fosse até o Norte e dissesse ao povo: — Ó Israel infiel, volte para mim. Sou eu, o Senhor , quem está falando. Sou bondoso e por isso não ficarei com raiva de você, não ficarei irado  para sempre. Sou eu, o Senhor , quem está falando.

[[v24-3-13]]

^<<v24-3-13,13>>^ Basta você reconhecer que é culpada e que se revoltou contra o Senhor , seu Deus. Confesse que debaixo de todas as árvores que dão sombra você deu o seu amor a deuses estrangeiros e não me obedeceu. Eu, o Senhor , estou falando.

[[v24-3-14]]

^<<v24-3-14,14>>^ O Senhor  Deus diz: — Volte, povo infiel, pois vocês são meus. Eu vou pegar vocês, um de cada cidade e dois de cada grupo de famílias, e vou levá-los de volta ao monte Sião .

[[v24-3-15]]

^<<v24-3-15,15>>^ Eu darei a vocês líderes que me obedeçam, e eles governarão com sabedoria e inteligência.

[[v24-3-16]]

^<<v24-3-16,16>>^ Então, quando vocês se tornarem um povo numeroso naquela terra, ninguém mais falará a respeito da arca da aliança . Vocês não pensarão mais na arca, nem lembrarão dela; não precisarão dela, nem farão outra.

[[v24-3-17]]

^<<v24-3-17,17>>^ E aí, quando chegar o tempo certo, Jerusalém será chamada de "Trono do Senhor  Deus", e todas as nações se reunirão ali em meu nome. Não farão mais aquilo que os seus corações teimosos e maus mandarem.

[[v24-3-18]]

^<<v24-3-18,18>>^ O povo de Israel se unirá com o de Judá, e eles voltarão juntos da terra do Norte para a terra que dei aos seus antepassados.

[[v24-3-19]]

^<<v24-3-19,19>>^ O Senhor  Deus diz: "Povo de Israel, eu queria aceitá-lo como meu filho e lhe dar uma terra agradável, a terra mais linda do mundo. Pensei que você ia me chamar de pai e que nunca mais me abandonaria.

[[v24-3-20]]

^<<v24-3-20,20>>^ Mas, como a mulher que trai o marido, assim você me traiu. Sou eu, o Senhor , quem está falando."

[[v24-3-21]]

^<<v24-3-21,21>>^ No alto dos montes, se ouve um barulho; são os israelitas chorando e pedindo perdão porque têm vivido uma vida de pecado e têm esquecido o Senhor , seu Deus.

[[v24-3-22]]

^<<v24-3-22,22>>^ Voltem, todos vocês que abandonaram o Senhor , pois ele vai curar a sua infidelidade. Vocês dizem: — Sim! Estamos voltando para o Senhor , pois ele é o Senhor , nosso Deus.

[[v24-3-23]]

^<<v24-3-23,23>>^ Não recebemos nenhuma ajuda dos deuses pagãos que temos adorado com gritos no alto das montanhas. Só o nosso Deus, o Senhor , pode ajudar o povo de Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ Por termos adorado Baal , o deus da vergonha, perdemos tudo o que os nossos pais conseguiram desde que éramos crianças, isto é, as ovelhas, o gado, os filhos e as filhas.

[[v24-3-25]]

^<<v24-3-25,25>>^ Vamos nos humilhar; vamos ficar cheios de vergonha. Desde o tempo em que o Senhor  nos tirou do Egito, nós e os nossos antepassados temos pecado contra ele e não lhe temos obedecido.

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]