include::./index.adoc[]

[[v24-36-0]]
=== Jeremias, 36
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-36-1]]

^<<v24-36-1,1>>^ No quarto ano em que Jeoaquim, filho de Josias, reinou em Judá, o Senhor  Deus me disse:

[[v24-36-2]]

^<<v24-36-2,2>>^ — Jeremias, pegue um rolo — um livro — e escreva nele tudo o que lhe falei a respeito do povo de Israel e de Judá e a respeito de todas as nações. Escreva tudo o que eu disse desde a primeira vez em que falei com você, quando Josias era rei, até hoje.

[[v24-36-3]]

^<<v24-36-3,3>>^ O povo de Judá vai ficar sabendo de toda a destruição que estou pensando fazer cair sobre eles. Aí talvez todos abandonem os seus maus caminhos, e eu perdoarei a maldade e os pecados deles.

[[v24-36-4]]

^<<v24-36-4,4>>^ Depois, eu chamei Baruque, filho de Nerias, e ditei tudo o que o Senhor  me tinha dito, e ele escreveu num rolo.

[[v24-36-5]]

^<<v24-36-5,5>>^ Então lhe dei as seguintes instruções: — Eu estou proibido de ir ao Templo.

[[v24-36-6]]

^<<v24-36-6,6>>^ Mas quero que você vá até lá quando o povo estiver jejuando. Leia o rolo em voz alta, de modo que eles escutem tudo o que o Senhor  Deus me disse e que eu ditei a você. Faça isso de maneira que o povo e também os que vierem das cidades de Judá possam ouvir.

[[v24-36-7]]

^<<v24-36-7,7>>^ Pode ser que assim eles orem a Deus e abandonem os seus maus caminhos, pois o Senhor  está furioso e muito irado  com este povo.

[[v24-36-8]]

^<<v24-36-8,8>>^ Então Baruque leu no pátio do Templo as palavras do Senhor , exatamente como eu havia mandado.

[[v24-36-9]]

^<<v24-36-9,9>>^ No nono mês do quinto ano do reinado de Jeoaquim, filho de Josias, em Judá, o povo ficou em jejum diante de Deus, o Senhor . Tomaram parte nesse jejum todos os que viviam em Jerusalém e todos os que tinham vindo das cidades de Judá.

[[v24-36-10]]

^<<v24-36-10,10>>^ Então Baruque leu no rolo tudo o que eu tinha dito, e todo o povo escutou. Ele fez essa leitura num dos pátios do Templo, na sala de Gemarias, que era filho de Safã e escrivão do rei. Essa sala, que ficava na entrada do Portão Novo do Templo, dava para o pátio de cima.

[[v24-36-11]]

^<<v24-36-11,11>>^ Micaías, filho de Gemarias e neto de Safã, ouviu Baruque ler no rolo aquilo que o Senhor  tinha dito.

[[v24-36-12]]

^<<v24-36-12,12>>^ Aí desceu ao palácio real e foi até a sala do escrivão do rei, onde todas as autoridades estavam reunidas. Encontravam-se ali Elisama, conselheiro do rei, e Delaías, filho de Semaías, e Elnatã, filho de Acbor, e Gemarias, filho de Safã, e Zedequias, filho de Hananias, e todas as outras autoridades.

[[v24-36-13]]

^<<v24-36-13,13>>^ Micaías contou tudo o que tinha ouvido Baruque ler para o povo.

[[v24-36-14]]

^<<v24-36-14,14>>^ Então as autoridades mandaram que Jeudi, que era filho de Netanias, neto de Selemias e bisneto de Cusi, fosse dizer a Baruque o seguinte: — Venha e traga o rolo que você leu para o povo. Aí Baruque pegou o rolo e foi ao palácio.

[[v24-36-15]]

^<<v24-36-15,15>>^ E eles lhe disseram: — Por favor, sente-se e leia o rolo para nós. E Baruque leu para eles.

[[v24-36-16]]

^<<v24-36-16,16>>^ Depois de terem escutado tudo, eles olharam assustados uns para os outros e disseram a Baruque: — Temos de contar isso ao rei.

[[v24-36-17]]

^<<v24-36-17,17>>^ Então perguntaram: — Diga uma coisa: como é que você escreveu tudo isso? Foi Jeremias que ditou?

[[v24-36-18]]

^<<v24-36-18,18>>^ — Jeremias ditou palavra por palavra, e eu escrevi tudo com tinta neste rolo! — respondeu Baruque.

[[v24-36-19]]

^<<v24-36-19,19>>^ Então eles disseram: — Você e Jeremias precisam se esconder. Não deixem ninguém saber onde vocês estão.

[[v24-36-20]]

^<<v24-36-20,20>>^ As autoridades deixaram o rolo, isto é, o livro, na sala de Elisama, o escrivão do rei. Em seguida, foram até a sala onde o rei estava e lhe contaram tudo.

[[v24-36-21]]

^<<v24-36-21,21>>^ Então o rei mandou que Jeudi fosse buscar o rolo. Ele foi à sala de Elisama, trouxe o rolo e leu para o rei Jeoaquim e todas as autoridades que estavam em volta dele.

[[v24-36-22]]

^<<v24-36-22,22>>^ Era tempo de frio, e o rei estava no seu palácio de inverno, sentado perto do fogo.

[[v24-36-23]]

^<<v24-36-23,23>>^ Cada vez que Jeudi terminava a leitura de três ou quatro colunas, o rei cortava com uma faquinha aquele pedaço do rolo e jogava no fogo. Ele continuou fazendo isso até que o rolo inteirinho virou cinza.

[[v24-36-24]]

^<<v24-36-24,24>>^ Mas nem o rei nem nenhuma das autoridades que ouviram todas aquelas coisas ficaram com medo ou mostraram qualquer sinal de arrependimento.

[[v24-36-25]]

^<<v24-36-25,25>>^ Acontece que Elnatã, Delaías e Gemarias tinham pedido ao rei que não queimasse o rolo, mas ele não deu atenção.

[[v24-36-26]]

^<<v24-36-26,26>>^ Pelo contrário, mandou que o príncipe Jerameel, junto com Seraías, filho de Azriel, e Selemias, filho de Abdeel, prendessem o meu secretário Baruque e a mim. Mas o Senhor  nos havia escondido.

[[v24-36-27]]

^<<v24-36-27,27>>^ Depois que o rei Jeoaquim queimou o rolo que eu havia ditado a Baruque, o Senhor  Deus me disse

[[v24-36-28]]

^<<v24-36-28,28>>^ que pegasse outro rolo e escrevesse tudo o que estava naquele que o rei tinha queimado.

[[v24-36-29]]

^<<v24-36-29,29>>^ E o Senhor  me mandou dizer o seguinte: — Rei Jeoaquim, você queimou o rolo, perguntando: "Por que foi que Jeremias escreveu que o rei da Babilônia certamente virá, e destruirá esta terra, e matará a sua gente e os seus animais?"

[[v24-36-30]]

^<<v24-36-30,30>>^ Por isso, eu, o Senhor , digo a você, rei Jeoaquim, que nenhum dos seus descendentes será rei no reino de Davi. O seu cadáver ficará largado ao sol durante o dia e à geada durante a noite.

[[v24-36-31]]

^<<v24-36-31,31>>^ Castigarei você, os seus descendentes e as suas autoridades por causa dos pecados de vocês todos. Nem você nem o povo de Jerusalém e de Judá se importaram com os meus avisos. Por isso, farei cair sobre todos vocês a desgraça que prometi.

[[v24-36-32]]

^<<v24-36-32,32>>^ Então peguei outro rolo, entreguei ao meu secretário Baruque, e ele escreveu tudo o que eu ditei. Escreveu tudo o que estava no rolo que o rei Jeoaquim havia queimado. E ainda ditei muitas outras coisas parecidas.

'''

xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[&#60; Capítulo Anterior] | <<v24-36-0,Topo>> | xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[Próximo Capítulo &#62;]