include::./index.adoc[]

[[v24-16-0]]
=== Jeremias, 16
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-16-1]]

^<<v24-16-1,1>>^ O Senhor  Deus falou comigo novamente. Ele disse:

[[v24-16-2]]

^<<v24-16-2,2>>^ — Não case, nem tenha filhos neste lugar.

[[v24-16-3]]

^<<v24-16-3,3>>^ Eu vou lhe dizer o que acontecerá com os filhos e as filhas que nascerem aqui, e também com as mães que os tiverem e com os pais que os gerarem.

[[v24-16-4]]

^<<v24-16-4,4>>^ Eles morrerão de doenças horríveis. Ninguém chorará a morte deles, e não serão sepultados. Ficarão espalhados pelo chão como esterco. Serão mortos na guerra ou então morrerão de fome, e os seus corpos serão comidos pelas aves e pelos animais selvagens.

[[v24-16-5]]

^<<v24-16-5,5>>^ — Não entre numa casa onde tenha gente chorando. Não fique triste, nem chore por causa de ninguém. Pois eu não abençoarei mais esse povo com a minha paz; não os amarei mais, nem terei pena deles. Sou eu, o Senhor , quem está falando.

[[v24-16-6]]

^<<v24-16-6,6>>^ Tanto os ricos como os pobres morrerão nesta terra, mas ninguém vai sepultá-los, nem chorar por eles. Ninguém se cortará, nem rapará a cabeça em sinal de tristeza.

[[v24-16-7]]

^<<v24-16-7,7>>^ Ninguém comerá, nem beberá junto com uma pessoa para a consolar pela morte de um querido. Ninguém mostrará simpatia, nem mesmo por uma pessoa que tenha perdido o seu pai ou a sua mãe.

[[v24-16-8]]

^<<v24-16-8,8>>^ — Também não entre numa casa em que haja festa. Não se sente, e não coma, nem beba com eles.

[[v24-16-9]]

^<<v24-16-9,9>>^ Escute aquilo que eu, o Senhor  Todo-Poderoso, o Deus de Israel, estou dizendo. Vou acabar com os gritos de alegria e de felicidade e com o barulho alegre das festas de casamento. E vocês verão tudo isso acontecer neste lugar.

[[v24-16-10]]

^<<v24-16-10,10>>^ — Quando você anunciar essas coisas, eles vão perguntar por que foi que resolvi castigá-los tanto assim. Eles vão perguntar: "De que crime somos culpados e que pecado cometemos contra o Senhor , nosso Deus?"

[[v24-16-11]]

^<<v24-16-11,11>>^ Então você dirá que a resposta do Senhor  é esta: "Os seus antepassados me abandonaram, e foram atrás de outros deuses, e os serviram, e adoraram. Eles me deixaram e não obedeceram aos meus ensinamentos.

[[v24-16-12]]

^<<v24-16-12,12>>^ Mas vocês fizeram pior do que os seus antepassados. Todos vocês são teimosos e maus e não querem me obedecer.

[[v24-16-13]]

^<<v24-16-13,13>>^ Por isso, eu os expulsarei desta terra e os jogarei numa terra que nem vocês nem os seus antepassados conheceram. Ali vocês adorarão outros deuses dia e noite, pois eu não serei bondoso para vocês."

[[v24-16-14]]

^<<v24-16-14,14>>^ O Senhor  Deus diz: — Está chegando o tempo em que ninguém mais jurará por mim como o Deus vivo que tirou do Egito o povo de Israel.

[[v24-16-15]]

^<<v24-16-15,15>>^ Mas jurarão por mim como o Deus vivo que trouxe o povo de Israel do país do Norte e de todos os outros países por onde eu os havia espalhado. Vou trazê-los de volta para a sua própria terra, para a terra que dei aos seus antepassados. Eu, o Senhor , estou falando.

[[v24-16-16]]

^<<v24-16-16,16>>^ O Senhor  Deus diz: — Mandarei vir muitos pescadores para pescarem essa gente. Depois, mandarei vir muitos caçadores para os caçarem em todas as montanhas e lugares altos e até nos buracos das rochas. Sou eu, o Senhor , quem está falando.

[[v24-16-17]]

^<<v24-16-17,17>>^ Eu vejo tudo o que eles estão fazendo. Nada fica escondido de mim, e os pecados deles não escapam da minha vista.

[[v24-16-18]]

^<<v24-16-18,18>>^ Vou fazer com que paguem em dobro pela sua maldade e pelo seu pecado. Eles profanaram  a minha terra com ídolos que são tão mortos como os defuntos; eles encheram a minha terra com os seus falsos deuses.

[[v24-16-19]]

^<<v24-16-19,19>>^ Eu disse: — Ó Senhor  Deus, tu me proteges e me dás força; tu me ajudas na hora do sofrimento. Dos fins da terra, as nações irão a ti e dirão: "Os nossos antepassados só tinham falsos deuses, tinham somente deuses inúteis.

[[v24-16-20]]

^<<v24-16-20,20>>^ Será que o ser humano pode fazer os seus próprios deuses? Não! Porque não seriam deuses de verdade."

[[v24-16-21]]

^<<v24-16-21,21>>^ O Senhor  disse: — Por isso, farei com que eles conheçam a minha força e o meu poder uma vez para sempre. E eles saberão que o meu nome é Senhor .

'''

xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[&#60; Capítulo Anterior] | <<v24-16-0,Topo>> | xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[Próximo Capítulo &#62;]