include::./index.adoc[]

[[v24-21-0]]
=== Jeremias, 21
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-21-1]]

^<<v24-21-1,1>>^ O rei Zedequias, de Judá, mandou que Pasur, filho de Malquias, fosse junto com o sacerdote Sofonias, filho de Maaseias, e me fizesse o seguinte pedido:

[[v24-21-2]]

^<<v24-21-2,2>>^ — Jeremias, peça a Deus, o Senhor , que nos ajude, pois o rei Nabucodonosor, da Babilônia, está fazendo guerra contra nós. Pode ser que o Senhor  faça um milagre em nosso benefício e obrigue Nabucodonosor a se retirar.

[[v24-21-3]]

^<<v24-21-3,3>>^ Então o Senhor  falou comigo, e eu disse

[[v24-21-4]]

^<<v24-21-4,4>>^ que levassem a Zedequias a seguinte resposta do Senhor , o Deus de Israel: — Quem vai bater em retirada são os soldados que Zedequias está pondo para guerrear contra o rei da Babilônia e o seu exército que está do lado de fora das muralhas de Jerusalém. Eu amontoarei as armas deles no centro da cidade.

[[v24-21-5]]

^<<v24-21-5,5>>^ Eu mesmo lutarei contra vocês com toda a minha força, ira  e raiva e com o meu grande furor.

[[v24-21-6]]

^<<v24-21-6,6>>^ Nesta cidade, matarei tudo o que tem vida; tanto as pessoas como os animais morrerão de uma doença horrível.

[[v24-21-7]]

^<<v24-21-7,7>>^ O rei Zedequias, os seus oficiais e as outras pessoas que não morrerem por causa da guerra, da fome e da doença — todos estes eu deixarei que sejam presos pelo rei Nabucodonosor e pelos outros inimigos que querem matá-los. Nabucodonosor mandará matá-los; ele não terá dó nem piedade de nenhum deles. Eu, o Senhor , estou falando.

[[v24-21-8]]

^<<v24-21-8,8>>^ Em seguida, Deus mandou que eu dissesse ao povo: — Escutem! Eu, o Senhor , deixo que vocês escolham entre o caminho da vida e o caminho da morte.

[[v24-21-9]]

^<<v24-21-9,9>>^ Quem ficar nesta cidade será morto na batalha, pela fome ou pela doença. Mas quem sair e se entregar aos babilônios que estão cercando a cidade não será morto: o que essa pessoa vai ganhar é escapar com vida.

[[v24-21-10]]

^<<v24-21-10,10>>^ Pois eu resolvi não proteger esta cidade e sim destruí-la. Ela será entregue ao rei da Babilônia, e ele a queimará completamente. Eu, o Senhor , estou falando.

[[v24-21-11]]

^<<v24-21-11,11>>^ — Jeremias, diga aos descendentes do rei Davi, que são a família real de Judá, que escutem aquilo que eu, o Senhor , estou dizendo: "Façam justiça todos os dias. Protejam dos exploradores aqueles que estão sendo explorados. Se não, as maldades que vocês estão praticando farão a minha ira queimar como fogo que não pode ser apagado.

[[v24-21-12]]

^<<v24-21-12,12>>^ — Jeremias, diga aos descendentes do rei Davi, que são a família real de Judá, que escutem aquilo que eu, o Senhor , estou dizendo: "Façam justiça todos os dias. Protejam dos exploradores aqueles que estão sendo explorados. Se não, as maldades que vocês estão praticando farão a minha ira queimar como fogo que não pode ser apagado.

[[v24-21-13]]

^<<v24-21-13,13>>^ Jerusalém, você está num lugar bem alto, acima dos vales, como uma rocha que fica acima do planalto. Mas eu, o Senhor , lutarei contra você. Você diz que ninguém tem a coragem de atacá-la, que ninguém consegue tomá-la.

'''

xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[&#60; Capítulo Anterior] | <<v24-21-0,Topo>> | xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[Próximo Capítulo &#62;]