include::./index.adoc[]

[[v24-9-0]]
=== Jeremias, 9
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-9-1]]

^<<v24-9-1,1>>^ Eu gostaria que a minha cabeça fosse como um poço de água e que os meus olhos fossem como uma fonte de lágrimas, para que eu pudesse chorar dia e noite pela minha gente que foi morta.

[[v24-9-2]]

^<<v24-9-2,2>>^ Eu gostaria de ter um lugar para ficar no deserto, onde pudesse estar longe do meu povo. Todos eles são adúlteros, são um bando de traidores.

[[v24-9-3]]

^<<v24-9-3,3>>^ Estão sempre prontos para contar mentiras. O que manda na terra é a desonestidade, e não a verdade. O Senhor  Deus diz: "O meu povo faz maldade em cima de maldade e não quer saber de mim."

[[v24-9-4]]

^<<v24-9-4,4>>^ Cada um precisa estar prevenido contra o seu amigo, e ninguém pode confiar no próprio irmão porque todo irmão é tão falso como Jacó. Todos andam caluniando os seus amigos.

[[v24-9-5]]

^<<v24-9-5,5>>^ Todos eles enganam os seus conhecidos, e ninguém fala a verdade. Eles ensinaram a sua língua a mentir; pecam e não abandonam a sua vida de pecado.

[[v24-9-6]]

^<<v24-9-6,6>>^ Fazem uma violência atrás da outra e tapeação em cima de tapeação. Deus diz que este povo não quer aceitá-lo.

[[v24-9-7]]

^<<v24-9-7,7>>^ Por causa disso, o Senhor  Todo-Poderoso diz: "Vou purificar o meu povo como se faz com o metal; eu o farei passar por uma prova. O meu povo fez o mal — o que é que eu posso fazer com ele?

[[v24-9-8]]

^<<v24-9-8,8>>^ A sua língua é como uma flecha envenenada, e a sua boca fala mentiras. Cada um diz palavras amáveis ao seu vizinho, mas na verdade está preparando uma armadilha para ele.

[[v24-9-9]]

^<<v24-9-9,9>>^ Será que eu não devo castigá-los por causa dessas coisas? Não devo me vingar de uma nação como esta? Eu, o Senhor , estou falando."

[[v24-9-10]]

^<<v24-9-10,10>>^ Eu, Jeremias, disse: "Vou chorar por causa das montanhas, vou lamentar porque as pastagens estão secas, e ninguém passa por elas. Não se ouve mais o mugido do gado; as aves e os animais selvagens fugiram e foram embora."

[[v24-9-11]]

^<<v24-9-11,11>>^ Deus disse: "Vou fazer Jerusalém virar um montão de pedras, um lugar onde moram lobos. E as cidades de Judá se transformarão num deserto onde ninguém mora."

[[v24-9-12]]

^<<v24-9-12,12>>^ Eu perguntei: — Ó Senhor  Deus, por que a nossa terra está em ruínas? Por que está seca como um deserto, tão seca, que ninguém passa por ela? Quem é bastante inteligente para entender isso? Será que explicaste essas coisas a alguém, para que essa pessoa possa explicar aos outros?

[[v24-9-13]]

^<<v24-9-13,13>>^ E o Senhor  respondeu: — Isso aconteceu porque o meu povo abandonou os ensinamentos que eu lhe dei. Eles não me obedeceram, nem fizeram o que mandei.

[[v24-9-14]]

^<<v24-9-14,14>>^ Pelo contrário, foram teimosos e adoraram as imagens do deus Baal , como os pais deles ensinaram.

[[v24-9-15]]

^<<v24-9-15,15>>^ Agora, escute o que eu, o Senhor  Todo-Poderoso, o Deus de Israel, vou fazer. Darei ao meu povo plantas amargas para comer e água envenenada para beber.

[[v24-9-16]]

^<<v24-9-16,16>>^ Espalharei o meu povo pelo meio de nações que nem eles nem os seus antepassados sabiam que existiam. Mandarei exércitos contra o meu povo, até que seja completamente destruído.

[[v24-9-17]]

^<<v24-9-17,17>>^ O Senhor  Todo-Poderoso disse: "Atenção! Chamem mulheres que são pagas para chorar, mulheres que saibam cantar músicas tristes."

[[v24-9-18]]

^<<v24-9-18,18>>^ O povo disse: "Que elas venham depressa e cantem uma canção triste para nós para que os nossos olhos se encham de lágrimas e fiquem molhados de tanto chorar!"

[[v24-9-19]]

^<<v24-9-19,19>>^ Ouçam o povo de Sião  chorando e dizendo: "Estamos perdidos! Estamos muito envergonhados! As nossas casas foram derrubadas, e temos de deixar a nossa terra."

[[v24-9-20]]

^<<v24-9-20,20>>^ Eu disse: "Mulheres, ouçam o que o Senhor  Deus disse e deem atenção às suas palavras. Ensinem as suas filhas a chorar; ensinem as suas amigas a cantar canções tristes.

[[v24-9-21]]

^<<v24-9-21,21>>^ A morte subiu pelas nossas janelas e entrou nos nossos palácios. Acabou com as crianças nas ruas e com os moços nas praças dos mercados.

[[v24-9-22]]

^<<v24-9-22,22>>^ Os corpos dos mortos cairão, serão como esterco espalhado nos campos, como espigas cortadas e caídas das mãos dos que fazem a colheita, espigas que ninguém recolhe. Isso é o que Deus me mandou dizer."

[[v24-9-23]]

^<<v24-9-23,23>>^ O Senhor  disse: — O sábio não deve se orgulhar da sua sabedoria, nem o forte, da sua força, nem o rico, da sua riqueza.

[[v24-9-24]]

^<<v24-9-24,24>>^ Se alguém quiser se orgulhar, que se orgulhe de me conhecer e de me entender; porque eu, o Senhor , sou Deus de amor e faço o que é justo e direito no mundo. Estas são as coisas que me agradam. Eu, o Senhor , estou falando.

[[v24-9-25]]

^<<v24-9-25,25>>^ O Senhor  disse ainda: — Está chegando o tempo em que vou castigar o povo do Egito, de Judá, de Edom, de Amom, de Moabe e todos os que vivem no deserto e costumam cortar o cabelo bem curto . Todos esses povos são circuncidados , mas não têm guardado a aliança , que foi selada  pela circuncisão. Todos esses povos e todo o povo de Israel não têm guardado a aliança que fizeram comigo.

'''

xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[Próximo Capítulo &#62;]