include::./index.adoc[]

[[v24-38-0]]
=== Jeremias, 38
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-38-1]]

^<<v24-38-1,1>>^ Certa vez, Sefatias, filho de Matã, e Gedalias, filho de Pasur, e Jucal, filho de Selemias, e Pasur, filho de Malquias, ouviram o que eu estava dizendo ao povo. Eu dizia que

[[v24-38-2]]

^<<v24-38-2,2>>^ o Senhor  Deus tinha dito o seguinte: — Quem ficar na cidade morrerá em combate, ou de fome, ou de doença. Mas aquele que sair e se entregar aos babilônios não será morto; pelo menos, escapará com vida e continuará a viver.

[[v24-38-3]]

^<<v24-38-3,3>>^ Eu estava dizendo que o Senhor  também tinha dito isto: — Certamente entregarei esta cidade ao exército do rei da Babilônia, e ele a conquistará.

[[v24-38-4]]

^<<v24-38-4,4>>^ Então as autoridades disseram ao rei: — Este homem tem de morrer. Falando desse jeito, ele está tirando a coragem dos soldados que estão na cidade e desanimando todo o povo. Este homem não está procurando ajudar; o que ele quer é a desgraça de todos.

[[v24-38-5]]

^<<v24-38-5,5>>^ O rei Zedequias disse: — Muito bem! Façam o que quiserem com Jeremias. Eu não posso segurar vocês.

[[v24-38-6]]

^<<v24-38-6,6>>^ Então eles me pegaram e me puseram dentro do poço que havia no pátio da guarda e que era do príncipe Malquias. Eles me desceram com cordas. Não havia água no poço; só lama; e eu me atolei na lama.

[[v24-38-7]]

^<<v24-38-7,7>>^ Ebede-Meleque, um eunuco  nascido na Etiópia, que trabalhava no palácio real, ficou sabendo que me haviam jogado no poço. Então saiu do palácio e foi falar com o rei, que naquela hora estava julgando causas no Portão de Benjamim. Ebede-Meleque disse o seguinte:

[[v24-38-8]]

^<<v24-38-8,8>>^ Ebede-Meleque, um eunuco  nascido na Etiópia, que trabalhava no palácio real, ficou sabendo que me haviam jogado no poço. Então saiu do palácio e foi falar com o rei, que naquela hora estava julgando causas no Portão de Benjamim. Ebede-Meleque disse o seguinte:

[[v24-38-9]]

^<<v24-38-9,9>>^ — Ó rei, meu senhor, o que aqueles homens fizeram está errado. Jogaram Jeremias no poço, e ele na certa vai morrer de fome, pois não há mais comida na cidade.

[[v24-38-10]]

^<<v24-38-10,10>>^ Aí o rei deu ordem para Ebede-Meleque levar trinta homens dali e me tirar do poço antes que eu morresse.

[[v24-38-11]]

^<<v24-38-11,11>>^ Então Ebede-Meleque levou os homens ao depósito do palácio. Pegou alguns trapos e roupas usadas e os desceu por meio de cordas para dentro do poço onde eu estava.

[[v24-38-12]]

^<<v24-38-12,12>>^ E disse: — Jeremias, ponha esses trapos debaixo dos braços para que as cordas não machuquem você. Eu fiz o que ele mandou.

[[v24-38-13]]

^<<v24-38-13,13>>^ Então me puxaram com as cordas e me tiraram do poço. Depois disso, fiquei no pátio da guarda.

[[v24-38-14]]

^<<v24-38-14,14>>^ O rei Zedequias mandou que me levassem até a terceira entrada do Templo, onde ele estava. Então disse: — Jeremias, vou lhe fazer uma pergunta e não quero que você esconda nada de mim.

[[v24-38-15]]

^<<v24-38-15,15>>^ Eu respondi: — Se eu disser a verdade, o senhor me matará; e, se eu lhe der conselhos, o senhor não ouvirá.

[[v24-38-16]]

^<<v24-38-16,16>>^ Aí o rei Zedequias me prometeu, em segredo, o seguinte: — Pelo Senhor  Deus, que está vivo e que nos deu a vida, juro que não matarei você, nem o entregarei aos homens que querem matá-lo.

[[v24-38-17]]

^<<v24-38-17,17>>^ Então eu disse a Zedequias que o Senhor  Todo-Poderoso, o Deus de Israel, tinha dito o seguinte: — Rei Zedequias, se você se entregar aos oficiais do rei da Babilônia, você não será morto, e esta cidade não será queimada. Tanto você como a sua família ficarão vivos.

[[v24-38-18]]

^<<v24-38-18,18>>^ Porém, se você não se entregar, então esta cidade será entregue aos babilônios, e eles a queimarão. E você não escapará deles.

[[v24-38-19]]

^<<v24-38-19,19>>^ O rei Zedequias respondeu: — Mas eu tenho medo dos judeus que passaram para o lado dos babilônios. Pode acontecer que os babilônios me entreguem a esses judeus, e eles me torturem.

[[v24-38-20]]

^<<v24-38-20,20>>^ Aí eu disse ao rei: — O senhor não será entregue a esses judeus. Por favor, obedeça à mensagem do Senhor  Deus, como lhe falei. Então tudo lhe correrá bem, e o senhor não será morto.

[[v24-38-21]]

^<<v24-38-21,21>>^ Mas Deus me mostrou o que acontecerá se o senhor não quiser se entregar.

[[v24-38-22]]

^<<v24-38-22,22>>^ Todas as mulheres que ficarem no palácio real de Judá serão levadas para os oficiais do rei da Babilônia. E elas irão dizendo assim: "O rei foi enganado e dominado pelos seus melhores amigos. E, agora que ele afundou os pés na lama, os seus amigos o abandonaram."

[[v24-38-23]]

^<<v24-38-23,23>>^ Eu disse ainda: — Rei Zedequias, todas as suas mulheres e os seus filhos serão entregues aos babilônios, e o senhor também não escapará deles. O senhor será levado como prisioneiro pelo rei da Babilônia, e esta cidade será destruída pelo fogo.

[[v24-38-24]]

^<<v24-38-24,24>>^ Aí Zedequias me recomendou: — Jeremias, não conte esta conversa a ninguém; se não, a sua vida correrá perigo.

[[v24-38-25]]

^<<v24-38-25,25>>^ Se as autoridades souberem que eu estive falando com você, vão lhe perguntar o que foi que conversamos. E vão prometer que não o matarão se você lhes contar tudo.

[[v24-38-26]]

^<<v24-38-26,26>>^ Se isso acontecer, diga que você veio me pedir que não o mandasse de volta à casa de Jônatas, pois ali você morreria.

[[v24-38-27]]

^<<v24-38-27,27>>^ Então todos os oficiais vieram e me fizeram perguntas. E eu respondi como o rei havia ordenado. Eles me deixaram em paz porque não tinham ouvido nada da conversa.

'''

xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[&#60; Capítulo Anterior] | <<v24-38-0,Topo>> | xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[Próximo Capítulo &#62;]