include::./index.adoc[]

[[v24-34-0]]
=== Jeremias, 34
// ntlh ?, NTLH - Nova Tradução na Linguagem de Hoje

[[v24-34-1]]

^<<v24-34-1,1>>^ O rei Nabucodonosor, da Babilônia, e o seu exército estavam atacando Jerusalém e as cidades vizinhas. Ajudavam nesse ataque as tropas de todas as nações e reinos dominados por ele. Nesse tempo, o Senhor  Deus falou comigo

[[v24-34-2]]

^<<v24-34-2,2>>^ e mandou que eu levasse a seguinte mensagem ao rei Zedequias, de Judá: — Eu, o Senhor , o Deus de Israel, vou entregar esta cidade ao rei da Babilônia, e ele a destruirá com fogo.

[[v24-34-3]]

^<<v24-34-3,3>>^ Você não escapará; pelo contrário, será preso e entregue a ele. Você verá Nabucodonosor e falará com ele pessoalmente. Depois, você irá para a Babilônia.

[[v24-34-4]]

^<<v24-34-4,4>>^ Rei Zedequias, escute o que eu, o Senhor , estou dizendo a seu respeito: você vai morrer em paz e não na guerra.

[[v24-34-5]]

^<<v24-34-5,5>>^ E, como queimaram incenso no sepultamento dos seus antepassados que foram reis antes de você, assim queimarão incenso em sua honra. Vão chorar por sua causa, dizendo: "O nosso rei morreu!" Eu, o Senhor , falei.

[[v24-34-6]]

^<<v24-34-6,6>>^ Então eu contei tudo isso ao rei Zedequias, em Jerusalém,

[[v24-34-7]]

^<<v24-34-7,7>>^ quando o exército do rei da Babilônia estava atacando a cidade. Esse exército também estava atacando Laquis e Azeca, as duas únicas cidades cercadas de muralhas, em Judá, que ainda resistiam.

[[v24-34-8]]

^<<v24-34-8,8>>^ O Senhor  Deus falou de novo comigo depois que Zedequias fez um acordo  com os moradores de Jerusalém para darem liberdade aos seus escravos.

[[v24-34-9]]

^<<v24-34-9,9>>^ Cada um devia pôr em liberdade os seus escravos hebreus, tanto homens como mulheres, para que assim nenhum hebreu tivesse como escravo uma pessoa da sua raça.

[[v24-34-10]]

^<<v24-34-10,10>>^ E todo o povo e as autoridades concordaram em libertar os seus escravos, prometendo nunca mais escravizá-los. Eles libertaram os escravos,

[[v24-34-11]]

^<<v24-34-11,11>>^ mas depois mudaram de ideia, e os fizeram voltar, e os obrigaram a se tornarem escravos de novo.

[[v24-34-12]]

^<<v24-34-12,12>>^ Então o Senhor , o Deus de Israel, me mandou dizer ao povo: — Quando tirei do Egito os antepassados de vocês e os livrei da escravidão, fiz uma aliança  com eles. Eu disse que

[[v24-34-13]]

^<<v24-34-13,13>>^ Então o Senhor , o Deus de Israel, me mandou dizer ao povo:

[[v24-34-14]]

^<<v24-34-14,14>>^ de sete em sete anos deviam libertar qualquer patrício hebreu que eles tivessem comprado e que tivesse sido escravo deles durante seis anos. Mas os seus antepassados não me deram atenção, nem me obedeceram.

[[v24-34-15]]

^<<v24-34-15,15>>^ Porém alguns dias atrás vocês mudaram de ideia e fizeram o que me agrada. Todos concordaram em libertar os seus patrícios hebreus e fizeram um acordo na minha presença, no Templo construído em honra do meu nome.

[[v24-34-16]]

^<<v24-34-16,16>>^ Mas depois vocês novamente mudaram de ideia e profanaram  o meu nome. Todos vocês fizeram voltar os escravos que haviam sido libertados e os obrigaram a ser escravos de novo.

[[v24-34-17]]

^<<v24-34-17,17>>^ Por isso, eu, o Senhor , digo que vocês me desobedeceram e não deram a liberdade aos seus patrícios hebreus. Pois bem! Eu vou dar liberdade a vocês: liberdade de morrer na guerra e de morrer de doença e fome. Farei com que sejam um espetáculo horrível para todas as nações da terra. Sou eu, o Senhor , quem está falando.

[[v24-34-18]]

^<<v24-34-18,18>>^ As autoridades de Judá e de Jerusalém, os oficiais do palácio, os sacerdotes e todo o povo fizeram uma aliança comigo, passando entre as duas metades de um boi cortado ao meio. Mas eles quebraram a aliança que fizeram na minha presença e não cumpriram o que prometeram.

[[v24-34-19]]

^<<v24-34-19,19>>^ As autoridades de Judá e de Jerusalém, os oficiais do palácio, os sacerdotes e todo o povo fizeram uma aliança comigo, passando entre as duas metades de um boi cortado ao meio. Mas eles quebraram a aliança que fizeram na minha presença e não cumpriram o que prometeram.

[[v24-34-20]]

^<<v24-34-20,20>>^ Por isso, eu os entregarei aos seus inimigos que os querem matar, e os corpos deles serão comidos pelas aves e pelos animais selvagens.

'''

xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[&#60; Capítulo Anterior] | <<v24-34-0,Topo>> | xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[Próximo Capítulo &#62;]